### ISSUE TITLE
Weapon shader not affected by changes with surface lighting slider

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#1]

**Comment by plemsoft** [comment]
Surface sun factor and surface level + red green blue , work fine here in Pubic Preview. Is this from the old version ?

**Comment by plemsoft** [comment]
Tested in Public Preview and latest GitHub version and it works here.
If anyone see this problem please let me know and i will reopen it , just let me know what version your testing this on :)
