### ISSUE TITLE
defaultterrainheight doesn't work

### ISSUE THREAD

**Issue by Dimoxinil** [TheGameCreators/GameGuruRepo#100]
If you you modify the value defaultterrainheight in the file setup.ini. This function has no effect.

**Comment by plemsoft** [comment]
defaultterrainheight is used when creating a new terrain, try to set it to 450 and start GG , you will see that you now only have water and the terrain is generated below waterline , this will not work on old levels but only when generating a new terrain.

Not sure why Lee has assigned it as a bug , i think it does what it was made for ?

**Comment by Dimoxinil** [comment]
Yes..  the bug only affects the maps created with the directx9 version of GG, just like mine.  I work with superflatterrain but as It doesn't work in the PP I can't do more tests, but all the entities of my maps are  floating in the air at this time.. like my future.

Well.. I'll manage all right. I just have to change a few scripts, move all the objects of the map and.. hope for the best.

**Comment by plemsoft** [comment]
superflatterrain - Yes thats another bug , i will have a look tomorrow and see if i can get it working again :)

**Comment by LeeBamberTGC** [comment]
Its worth noting that defaultterrainheight does not affect superflatterrain, which is always set at 1000. As stated, this field is used for generating terrain at a specific height when superflatterrain is zero.
