### ISSUE TITLE
Transparency Issue

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1001]
Reported by SCIENCEBOY DUNGEON

I made a small dungeon with the puddle and shadows replicated I think it's the trenchancy. you will need to place the entities in the character folder just drop it there and the map should pick it up

See "GGMAX BUG FROM science boy" folder

**Comment by plemsoft** [comment]
@rvanner I did not understand this one, if its about transparent sorting order it has been fixed, if not please post more information, thanks.

**Comment by LeeBamberTGC** [comment]
@plemsoft This was one of mine, fixed many moons ago :)
