### ISSUE TITLE
Ensure the trashcan shows (to delete an object) if drag into the lower current objects area (not just the upper part)

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1005]

**Comment by rvanner** [comment]
![image](https://user-images.githubusercontent.com/1503593/111216396-47d69580-85cc-11eb-83d4-0aa1ad61b9c0.png)

**Comment by plemsoft** [comment]
@rvanner Thanks this was fixed a few version ago.
