### ISSUE TITLE
Need to gracefully continue when sound device fails

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#1009]
Avoid crashing the software when the sound device fails to create resources:

![image](https://user-images.githubusercontent.com/35840583/111305489-ec012080-864e-11eb-9131-7f650420d991.png)

**Comment by plemsoft** [comment]
@LeeBamberTGC Thanks for reporting this issue, this has been fixed and will be in the next commit :)
