### ISSUE TITLE
Importer do not display object correct.

### ISSUE THREAD

**Issue by plemsoft** [TheGameCreators/GameGuruRepo#101]
When you enter importer the select object is not displayed correct before you select a texture.
![importerbug](https://user-images.githubusercontent.com/18662417/36845583-a17809b0-1d57-11e8-9c85-0851d878f0c2.png)

**Comment by earthling45** [comment]
Yes, i've noticed this with the saw blade.
I'm not using it much and the character was fully visible as was the blade.
Well, you might notice or have noticed that you sometimes have to select center mesh for it to be visible.
The biggest problem is when you add a collisionbox and select top view.
A part of the model is transparent and the only movement option is up and down which obviously does not help in top view. :)
