### ISSUE TITLE
Don't allow group editing of other groups if they are not selected

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1019]
If you edit a group of objects, don't allow other objects from other groups to be edited at the same time. The user must turn off edit group before they can edit another group.

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by 3coms** [comment]
@rvanner > The user must turn off edit group before they can edit another group.
This is happening to me as well.
