### ISSUE TITLE
Light Leaks

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1023]
Lighting has developed leakes through wall. Very apparent in Lee's HDR Demo map.

![HDR MAP](https://user-images.githubusercontent.com/35708217/111888883-85765c80-89d8-11eb-9bb9-45e304f600f6.png)

**Comment by LeeBamberTGC** [comment]
Env probes now scan for being inside rooms and reduces accordingly, removing this artifact!
