### ISSUE TITLE
Editor Keys - G and F Confused

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1024]
The editor keys are confused:
G does not go to top view.
F sometimes works as G key should, and causes UI spasms.

Video Link:
https://vimeo.com/526846466/689bc80d97

System Specs:
DXDIAG required!

**Comment by synchromesh62** [comment]
Tested and confirmed.
Replicated exactly as the video above shows.

**Comment by rvanner** [comment]
@michaeloldman F key will now toggle between top and 3D views. G key will be used for grid mode in a future version.

I will close this issue now.
