### ISSUE TITLE
Textures not being applied to imprted character

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1025]
Added DNS textures to the object and saved.  object remains white even after restarting MAX.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: DH61WW
Processor: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 CPUs), ~3.3GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 3GB
Dedicated Memory: 2988 MB
Current Mode: 1600 x 900 (32 bit) (60Hz)

**Comment by synchromesh62** [comment]
Any chance of a pic ?
I have added DNS to most of my models without issue but you must have .. textured = named_d.dds 
in the .fpe or they can show white.

**Comment by rvanner** [comment]
@redagent101 Are you able to show a video of this or screen shots to help the team respond?

**Comment by redagent101** [comment]
I will upload a video / pic when I get some time.  Not doing it now, so need to double check I can reproduce it again,
thanks
Mike
BOTR (redagent101)
