### ISSUE TITLE
Editor Bug - Model Selection

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1026]
Models move from original posistion when clicked.

Happens when you edit a model, then run test-game, and then try to edit again.

https://vimeo.com/527076431/554b56b2ef

System Specs:
DXDIAG required!

**Comment by plemsoft** [comment]
@michaeloldman This system was change a few version ago, do you still see this in the latest version ?

**Comment by michaeloldman** [comment]
@plemsoft Yes still seeing similar issue. 
Although now it tends to happen mainly to models inside other models -  near ceilings for example. and they don't move across like in opening video, but instead take off somewhere on the map - when it happens the coordinates for both X and Z will be something like -50 or around the 100 mark, but the Y stay unchanged.

Here be a Video of current issue:
https://vimeo.com/546433199

**Comment by LeeBamberTGC** [comment]
This has been a pretty long-standing one. This Friday's build will have a new system that keeps the object attached to the mouse cursor when dragged in any of the three positioning modes, even if the object is in the air during find surface mode movement.

**Comment by rvanner** [comment]
@michaeloldman Are you now content with how it works?
