### ISSUE TITLE
Structure feature freeze and crash GGMax

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#1028]
The game engine crash as soon as I use the structure feature and lay the floor, after switching to walls GG Max freeze and stop working. 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: ROG Zephyrus M15 GU502LW_GU502LW
Processor: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
Memory: 16384MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070 with Max-Q Design
Dedicated Memory: 8031 MB
Current Mode: 1280 x 1024 (32 bit) (60Hz)
Card name: Intel(R) UHD Graphics
Dedicated Memory: 128 MB
Current Mode: Unknown

**Comment by LeeBamberTGC** [comment]
This has been moved to Developer Mode and as such now experimental. We intend to overhaul this feature for the release of MAX.

**Comment by plemsoft** [comment]
@Hamada880 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Hamada880** [comment]
It is no longer crash the GGMax. So that yes I can confirm, just other bugs I report it in different post.
