### ISSUE TITLE
Splash screen/Auto Update screen does not load automatically when Max starts

### ISSUE THREAD

**Issue by denukvt** [TheGameCreators/GameGuruRepo#1029]
Title says it all...screen for updates does not load automatically on start up. Selecting from help menu allows update screen to run and updates etc to take place.

System Specs:
DXDIAG required!

**Comment by synchromesh62** [comment]
Have you turned it off in your settings ?
Edit \ Settings \ General \ **Show welcome screen on start up** 
Should be ticked.

**Comment by LeeBamberTGC** [comment]
Updater fixed a few times since this report, and new announcement system offers the update when a new one is detected.
