### ISSUE TITLE
Models vanishing

### ISSUE THREAD

**Issue by Snake675** [TheGameCreators/GameGuruRepo#103]
After playing around a bit, several models and all enemy weapons are gone. I can select the Models and i can see the icon to the right but they can't be placed in the level any more.

**Comment by LeeBamberTGC** [comment]
Thanks for posting here. I just pointed you here from your forum post, but seems you knew the way :)

**Comment by Snake675** [comment]
Yea, sorry. I realised knowing GitHub allready from my other hobbies [electronics and drones] ;)

BTW: The latest version of GG shows some really nice improvements, thanks Lee, nifty piece of work! Looking forward to next release...
