### ISSUE TITLE
Light Blending Not Gradual

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1030]
This image shows example of how light does not blend gradually - just stops at certain point in a visible line.
![Lighting_Wrong_02](https://user-images.githubusercontent.com/12246318/112402204-2f027880-8d60-11eb-9112-566ce6c26af1.png)

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Build 2021.02.04 - Exhibits same issue :)

**Comment by michaeloldman** [comment]
Thanks Lee.
The env probes have broken more than they have fixed\improved me thinks...
I would still class this as a bug to be honest...

**Comment by synchromesh62** [comment]
Awesome News .. 
Thanks Lee Really appreciating your efforts

**Comment by LeeBamberTGC** [comment]
In next build you now have control over light prove scale, and can scale them zero if you like. Removes this issue and restored to previous visuals somewhat:

![image](https://user-images.githubusercontent.com/35840583/117828102-7211a000-b269-11eb-9fe5-c63b4c6ca01c.png)
