### ISSUE TITLE
Markers - Not Retaining Position

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1032]
Marker points sometimes fall to different height.
- Happens randomly when you save open map.
- They should always stay where they were placed originally.

Classic was notorious for this, and was one of its most annoying issues.
MAX needs to do better :)

**Comment by michaeloldman** [comment]
Marker in original position:
![MarkerBugs_01](https://user-images.githubusercontent.com/12246318/112617055-94498d00-8e78-11eb-8a48-63bd11cb9752.png)

Points have fallen below floor - at some stage??
![MarkerBugs_02](https://user-images.githubusercontent.com/12246318/112617226-ca870c80-8e78-11eb-96aa-94d41dd8a0d0.png)

**Comment by LeeBamberTGC** [comment]
Object placement modes improved for this Friday;s build. Used P to enter waypoint mode and could move the nodes around without them falling through the floor object:

![image](https://user-images.githubusercontent.com/35840583/117738996-3b9a3d80-b1f5-11eb-9733-12a1f4031beb.png)

**Comment by rvanner** [comment]
@michaeloldman Is this now fixed for you? Can you please confirm?

**Comment by michaeloldman** [comment]
@rvanner So far not seen it happen since Lee sorted it so will close issue :)
