### ISSUE TITLE
2021.03.26 - Broken Fog

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1033]
The fog is not behaving  :)
Easily replicated using stock assests.

Video link:
https://youtu.be/glCy_ZUHVxQ

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Custom media pic example:
![RenderBugs](https://user-images.githubusercontent.com/12246318/112709765-34062a00-8f10-11eb-80fd-5e386851d27c.png)
![RenderBugs_02](https://user-images.githubusercontent.com/12246318/112709771-39fc0b00-8f10-11eb-8346-2b987c41cb51.png)

**Comment by michaeloldman** [comment]
![RenderBugs_04](https://user-images.githubusercontent.com/12246318/112744976-81f25f00-8ff0-11eb-98f8-9f98095ac2bd.png)

https://youtu.be/DoFkJCj8Gp8

**Comment by michaeloldman** [comment]
2021.02.04 Still Broken
Default level settings - just lower fog range to 1-19
![2021 02 04 - Fog Bugged](https://user-images.githubusercontent.com/12246318/113463334-eee27a80-9470-11eb-8469-b01eb5a4cd19.png)

**Comment by LeeBamberTGC** [comment]
Works fine in latest Friday build. Ensure your light color is set to the same as the fog color to match up the sky and fog atmospherics,and have fog opacity to full:

![image](https://user-images.githubusercontent.com/35840583/117739202-b9f6df80-b1f5-11eb-861f-d1f6ddaa8a67.png)

**Comment by michaeloldman** [comment]
@LeeBamberTGC Not sure what is causing it tbh.
The map in the video is over on discord - you can download and test - tis all stock media :)

**Comment by LeeBamberTGC** [comment]
@michaeloldman When you are next about, can you email it to me. I scrolled around Discord for 10 minutes, then decided to go back to coding (much more fun) :)

**Comment by Kitakazi** [comment]
Hi I've been having this issue as well. You can reproduce it easily on the hdr-dynamicexposure.fpm level.  Set the Fog range to like 2-60, go into the level and take a few steps back and you should see something like the screenshots I attached. It almost like aliasing, or some weird distortion so it looks really bad when moving around. See attached screenshots, the sandbags and background distort really bad. 

![Max Screenshot 2021 05 12 - 00 02 20 29](https://user-images.githubusercontent.com/51464873/117921398-4b2d8b00-b2b6-11eb-9565-f4e21bcb8941.png)
![Max Screenshot 2021 05 12 - 00 05 47 66](https://user-images.githubusercontent.com/51464873/117921416-51236c00-b2b6-11eb-9044-e9b07f61432a.png)

**Comment by LeeBamberTGC** [comment]
Definitely a broken (or very unsatisfactory) effect with too much messing about. Have moved this to the weather work, combining with terrain work to ensure we have great fog effects, and easy control of fog.

**Comment by OldFlak** [comment]
I cannot reproduce this now (build 2022.03.04) but will leave open for other contributors to verify if it is OK for them as well :)

**Comment by Kitakazi** [comment]
I don't have this issue anymore

**Comment by OldFlak** [comment]
@rvanner 
I think it is safe to close now - cannot reproduce issue specific to this thread, and neither can Kitakzi :)
