### ISSUE TITLE
Group Page Up Broken

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1034]
Page up has no effect on groups
- Required for precise placement of objects

Can easily replicate with stock media...

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Build 2021.02.04 - Exhibits same issue :)

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting this issue, this has been fixed and will be in the next update, give it a good test so we are 100% sure we don't break groups in any situation, :)

**Comment by michaeloldman** [comment]
@plemsoft - Sorry to say but not working on my system. Page up\down does nothing from me.
Also double-clicking an entity within a group ungroups all objects within that group.

Will make a video asap to demonstrate what I be seeing :)

**Comment by plemsoft** [comment]
@michaeloldman Works fine here, did you download the latest version ? , also tried double click and no ungroup :)

https://drive.google.com/file/d/19P14QdrigtaGQlGbgBB_c592-5uqK-Di/view?usp=sharing

**Comment by michaeloldman** [comment]
@plemsoft Using latest version downloaded Friday Evening my time.
Just tried verify to see if there is another update but fails. So could be tis not very latest version.

![Verify Fails](https://user-images.githubusercontent.com/12246318/117567058-859ff800-b0fd-11eb-85bb-666a3a3fa75b.png)

**Comment by plemsoft** [comment]
@michaeloldman Yes best to wait until the server is up again, so we are sure you have the latest :)

**Comment by michaeloldman** [comment]
@plemsoft Using latest update
Groups
- Page Up\Down not working
- Groups do not stay grouped when copies placed in scene

https://youtu.be/r4qVzohC_yE

**Comment by LeeBamberTGC** [comment]
@michaeloldman This Friday's build will allow child groups to be retained when created from group parent.

The PAGE UP and DOWN only works to move the group up and down the level when the cursor is IN the 3D Level Editor view, this is to protect the IMGUI UI from using the key strokes for its own ends.
