### ISSUE TITLE
Groups Vertical Grid Broken

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1035]
Using vertical stack tool does not snap to Grid Position
- Required for precise placement of objects
- When Grid is selected objects should move to **grid position** same as in horizontal mode

Easily replicated with stock media.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Build 2021.02.04 - Exhibits same issue :)

**Comment by rvanner** [comment]
@michaeloldman Is this still an issue for you?

**Comment by michaeloldman** [comment]
@rvanner They still don't snap to grid unless you use PageUp\PageDown.

I don't use the positioning tools on the right panel as I find they are not user friendly when building complex levels.

So while not an issue for me it still does not work as I would expect it to. 

Bu if nobody else sees it as a problem then you can close the issue if you like :)

**Comment by rvanner** [comment]
OK, I have changed this from High to Medium. We will get to it at some point.

**Comment by LeeBamberTGC** [comment]
@OldFlak Works nicely in latest build:

![image](https://user-images.githubusercontent.com/35840583/157254876-a689f29c-5df8-4f50-850b-c11af9039fa4.png)

**Comment by OldFlak** [comment]
@LeeBamberTGC Hi Lee thanks for looking at this - but no not fixed :)
As this vid shows the group moves to grid horizontally, but in vertical mode only moves incrementally.
The vid also shows other weird things happening when moving objects.

https://youtu.be/zGCZx9yuQtc

Note while the video is using a group of boxes in keeping with the OP - it is the same with single items. 
For me the editor is just not nice to use and especially annoying with more complex interior scenes.
