### ISSUE TITLE
MAX Build 2021.03.26 cannot use Bug Reporter

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#1037]
Hi
installed latest version this morning, downloaded and installed fine, first startup MAX crashed to desktop, restarted computer, started MAX worked fine, closed MAX left it for 10 mins reopened MAX and crashed to desktop here is the log file:

*********LOG START*******************************************************************************************************************
 
131 : Name of true app: Guru-MapEditor                          S:323MB V: (2110,0)     
132 : Flag to produce log files set in SETUP.INI (producelogfiles=1) S:0MB   V: (2110,0)     
133 : postprocessing flag at 0 and pixel shader version of 0.00 S:0MB   V: (2110,0)     
134 : The executable folder will be: C:\Users\kevan\Documents\GameGuruApps\GameGuruMAX\\MyGames\ S:0MB   V: (2110,0)     
136 : Entering 'Files' folder, now at: C:\Program Files\GameGuruMAX\Max\Files S:0MB   V: (2110,0)     
137 : set legacy convert mode                                   S:0MB   V: (2110,0)     
138 : _obs_memorychunkinit                                      S:0MB   V: (2110,0)     
141 : Guru-MapEditor                                            S:6MB   V: (2117,0)     
142 : detected map editor is in effect                          S:0MB   V: (2117,0)     
142 : setting display mode via DirectX                          S:0MB   V: (2117,0)     
143 : set camera aspect                                         S:0MB   V: (2117,0)     
144 : Special VR-Mode Flag: 3                                   S:0MB   V: (2117,0)     
145 : pixel states                                              S:0MB   V: (2117,0)     
146 : welcome_init(1)                                           S:0MB   V: (2117,0)     
147 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\animated-backdrop.png,65122,0,0 S:0MB   V: (2117,0)     
148 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome-assets\splash-logo.bmp,65151,0,0 S:0MB   V: (2117,0)     
149 : welcome_staticbackdrop();                                 S:0MB   V: (2117,0)     
150 : welcome_init(2)                                           S:0MB   V: (2117,0)     
151 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-page.png,65118,0,0 S:0MB   V: (2117,0)     
152 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome-assets\product-logo.png,65119,0,0 S:0MB   V: (2117,0)     
153 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\animated-backdrop.png,65122,0,0 S:0MB   V: (2117,0)     
154 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-1.png,65141,0,0 S:0MB   V: (2117,0)     
155 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-2.png,65142,0,0 S:0MB   V: (2117,0)     
156 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-3.png,65143,0,0 S:0MB   V: (2117,0)     
157 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-4.png,65144,0,0 S:0MB   V: (2117,0)     
158 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-5.png,65145,0,0 S:0MB   V: (2117,0)     
159 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-6.png,65146,0,0 S:0MB   V: (2117,0)     
160 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-7.png,65147,0,0 S:0MB   V: (2117,0)     
161 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-8.png,65148,0,0 S:0MB   V: (2117,0)     
162 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-9.png,65149,0,0 S:0MB   V: (2117,0)     
163 : LOADING FONTS                                             S:0MB   V: (2117,0)     
164 : initbitmapfont - startlegacy image loading                S:0MB   V: (2117,0)     
164 : initbitmapfont - deleting old images                      S:0MB   V: (2117,0)     
165 : initbitmapfont - first font load                          S:0MB   V: (2117,0)     
172 : initbitmapfont - first font shrink                        S:1MB   V: (2118,0)     
175 : initbitmapfont - remaining font loads                     S:0MB   V: (2118,0)     
220 : shrinkbitmapfont - new medium small size text             S:6MB   V: (2125,0)     
226 : initbitmapfont - finish legacy loading                    S:1MB   V: (2126,0)     
227 : Just about to read languagebank\english\textfiles\guru-wordcount.ini S:0MB   V: (2126,0)     
228 : Language File Path:C:\Program Files\GameGuruMAX\Max\Files\languagebank\english\textfiles (exist=1) S:0MB   V: (2126,0)     
231 : trueappname_s=Guru-MapEditor                              S:2MB   V: (2129,0)     
232 : Create full path structure (0) for standalone executable  S:0MB   V: (2129,0)     
240 : _mp_init:                                                 S:9MB   V: (2139,0)     
241 : _material_init (0)                                        S:0MB   V: (2139,0)     
250 : We can write to the Game Guru folder!                     S:0MB   V: (2139,0)     
270 : ide input mode                                            S:0MB   V: (2139,0)     
271 : VR System disabled to improve launch speed (temporary)    S:0MB   V: (2139,0)     
272 : sync states                                               S:0MB   V: (2139,0)     
273 : window states                                             S:0MB   V: (2139,0)     
284 : preload generic textures early                            S:0MB   V: (2139,0)     
285 : camera states                                             S:0MB   V: (2139,0)     
286 : memory states                                             S:4MB   V: (2143,0)     
318 : pre widget init state                                     S:5MB   V: (2148,0)     
319 : WIDGET INIT                                               S:0MB   V: (2148,0)     
320 : widget status update                                      S:0MB   V: (2148,0)     
326 : SLIDERS INIT                                              S:2MB   V: (2150,0)     
337 : LOAD COMMON ASSETS                                        S:0MB   V: (2150,0)     
337 : LOADING FONTS                                             S:0MB   V: (2150,0)     
338 : initbitmapfont                                            S:0MB   V: (2150,0)     
339 : initbitmapfont - startlegacy image loading                S:0MB   V: (2150,0)     
339 : initbitmapfont - deleting old images                      S:0MB   V: (2150,0)     
340 : initbitmapfont - first font load                          S:0MB   V: (2150,0)     
344 : initbitmapfont - first font shrink                        S:1MB   V: (2151,0)     
346 : initbitmapfont - remaining font loads                     S:-1MB  V: (2150,0)     
373 : shrinkbitmapfont - new medium small size text             S:3MB   V: (2154,0)     
374 : initbitmapfont - finish legacy loading                    S:0MB   V: (2154,0)     
375 : LOADING SHADERS                                           S:0MB   V: (2154,0)     
375 : INIT VECTORS                                              S:4MB   V: (2158,0)     
376 : INIT SKY ASSETS                                           S:1MB   V: (2159,0)     
377 : entering skybank                                          S:0MB   V: (2159,0)     
378 : checking skybank files                                    S:0MB   V: (2159,0)     
378 : atmos                                                     S:0MB   V: (2159,0)     
380 : cartoon                                                   S:0MB   V: (2159,0)     
382 : clear                                                     S:0MB   V: (2159,0)     
383 : cloudy                                                    S:0MB   V: (2159,0)     
385 : dark                                                      S:0MB   V: (2159,0)     
386 : golden                                                    S:0MB   V: (2159,0)     
388 : hazy                                                      S:0MB   V: (2160,0)     
389 : mooncloud                                                 S:0MB   V: (2160,0)     
391 : night                                                     S:0MB   V: (2160,0)     
393 : red                                                       S:0MB   V: (2160,0)     
394 : Ssunset                                                   S:0MB   V: (2160,0)     
397 : finished sky bank scan                                    S:0MB   V: (2160,0)     
398 : INIT TERRAIN ASSETS                                       S:0MB   V: (2160,0)     
408 : INIT GAME VISUAL ASSETS                                   S:0MB   V: (2160,0)     
422 : visuals.sky$=None                                         S:0MB   V: (2160,0)     
422 : visuals.terrain$=                                         S:0MB   V: (2160,0)     
423 : visuals.vegetation$=                                      S:0MB   V: (2160,0)     
443 : INIT DECAL ASSETS                                         S:412MB V: (2572,0)     
448 : INIT LIGHTMAP ASSETS                                      S:0MB   V: (2572,0)     
449 : SCANNING G-LIST                                           S:0MB   V: (2572,0)     
451 : gun 1:modern\colt1911\gunspec.txt                         S:0MB   V: (2572,0)     
452 : gun 2:modern\Grenade\gunspec.txt                          S:0MB   V: (2573,0)     
453 : gun 3:modern\Magnum357\gunspec.txt                        S:0MB   V: (2573,0)     
454 : gun 4:modern\RPG\gunspec.txt                              S:4MB   V: (2577,0)     
455 : gun 5:modern\Shotgun\gunspec.txt                          S:0MB   V: (2577,0)     
456 : gun 6:modern\SniperM700\gunspec.txt                       S:0MB   V: (2578,0)     
457 : gun 7:modern\Uzi\gunspec.txt                              S:0MB   V: (2578,0)     
458 : total guns=7                                              S:0MB   V: (2578,0)     
651 : LOAD PLAYER SOUNDS                                        S:55MB  V: (2634,0)     
708 : CREATING TERRAIN                                          S:7MB   V: (2641,0)     
709 : NEWMAP: Starting new map                                  S:0MB   V: (2641,0)     
741 : visuals.sky$=None                                         S:33MB  V: (2675,0)     
742 : visuals.terrain$=                                         S:0MB   V: (2675,0)     
743 : visuals.vegetation$=                                      S:4MB   V: (2679,0)     
744 : NEWMAP: _gridedit_clear_settings                          S:23MB  V: (2702,0)     
745 : NEWMAP: cleantestmapfolder                                S:0MB   V: (2702,0)     
855 : total extra PFBs=1                                        S:-20MB V: (2681,0)     
856 : NEWMAP: _terrain_createactualterrain                      S:0MB   V: (2681,0)     
943 : NEWMAP: Save newly flattened terrain                      S:175MB V: (2856,0)     
991 : NEWMAP: Save terrain data                                 S:92MB  V: (2949,0)     
1000 : NEWMAP: Finish creating new map                          S:12MB  V: (2961,0)     
1022 : SCANNING SKY SETTINGS                                    S:0MB   V: (2961,0)     
1023 : Initialise sky textures                                  S:0MB   V: (2961,0)     
1023 : Load sky cube:skybank\None\None_cube.dds                 S:0MB   V: (2961,0)     
1024 : INIT POST PROCESSING                                     S:0MB   V: (2961,0)     
1025 : INIT RAGDOLL SYSTEM                                      S:0MB   V: (2961,0)     
1026 : CREATING P-LIST                                          S:0MB   V: (2961,0)     
1273 : CREATING E-LIST                                          S:8MB   V: (2970,0)     
1308 : LOADING INTO P-LIST                                      S:8MB   V: (2978,0)     
1309 : CREATING B-LIST                                          S:0MB   V: (2978,0)     
1311 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE databank\indicator.png,63200,0,0 S:0MB   V: (2978,0)     
1312 : INIT EDITOR RESOURCES                                    S:0MB   V: (2978,0)     
1313 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE editors\gfx\memorymeter.png,65112,0,0 S:0MB   V: (2978,0)     
1317 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\english\artwork\testgamelayout-noweapons.png,65137,0,0 S:0MB   V: (2978,0)     
1319 : LOAD MAIN RESOURCES                                      S:1MB   V: (2980,0)     
1320 : UPDATE VISUAL SETTINGS                                   S:0MB   V: (2980,0)     
1321 :                                                          S:0MB   V: (2980,0)     
1391 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome\welcome-play.png,65167,0,0 S:0MB   V: (2979,0)     
1393 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome-assets\product-example.png,65169,0,0 S:0MB   V: (2979,0)     
1393 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome-assets\gameguru-news-banner.png,65174,0,0 S:0MB   V: (2979,0)     
1675 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome\welcome-play.png,65167,0,0 S:0MB   V: (2979,0)     
1677 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome-assets\product-example.png,65169,0,0 S:0MB   V: (2979,0)     
1691 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE editors\uiv3\pointer2.png,43046,0,0 S:0MB   V: (2980,0)     
1695 : CWD:C:\Program Files\GameGuruMAX\Max\Files
LOAD IMAGE editors\uiv3\ABOUT-Country.png,43052,0,0 S:0MB   V: (2980,0)     
2501 : preload CCP textures early                               S:299MB V: (3279,0)     
2502 : Guru Map Editor Loop Starts                              S:0MB   V: (3279,0)   

*******************************LOG END********************************************************************************************

Tried to use the inbuilt bug reporter, followed the instructions and linked my GitHub account but MAX keeps asking me to link my account so for me i cannot use the Bug Reporter

**Comment by GraPhiX-Guru** [comment]
Clean Install Build 2021.04.09
Still cannot use the bug reporter
![gh](https://user-images.githubusercontent.com/35724756/114241147-a2230600-9980-11eb-91e5-0870c74e2a7a.png)

**Comment by rvanner** [comment]
We have decided to remove this bug reporting system and will be asking users to post directly into GitHub.
