### ISSUE TITLE
Issue Lua Command: "SetGlobalSoundVolume ( id, volume )"

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1038]
Command SetGlobalSoundVolume ( id, volume) does not seem to work.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue,
I made a small script and it looks like it is working fine here ? , how do you use it . i tested like this:

 LoadGlobalSound ( "....wav", 5 )
PlayGlobalSound ( 5 ) 
SetGlobalSoundVolume ( 5, 90 )

Changed to: SetGlobalSoundVolume ( 5, 60 ) and you could hear it was lower.

Could you post the script that do not work for you , and i will have a look, Thanks for your help :)
