### ISSUE TITLE
Simulated Sky and Skybox Together

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1039]
Simulated Sky also displays when Skybox is selected.

This is essentially a bug - easily replicated in New or Existing maps
Might be worth bottling though!

Video:
https://vimeo.com/530146509/c4b055d94b

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
This would actually be a great feature, with some tweaking, for adding depth and life to static skyboxes.

**Comment by michaeloldman** [comment]
Build 2021.02.04 - Sorted :)
But new issues exist now 
#1061 
#1062

**Comment by rvanner** [comment]
Presume this is now not an issue. I'm closing it down. Please re-report if it happens again.
