### ISSUE TITLE
Objects can displays wrong, if dbo is generated outside importer.

### ISSUE THREAD

**Issue by plemsoft** [TheGameCreators/GameGuruRepo#104]
Objects can look wrong if the dbo is generated outside the importer, if a .x is missing a dbo and its auto generated the model dont always display correctly.

![bone-anim-error](https://user-images.githubusercontent.com/18662417/36928190-ebf00c5e-1e83-11e8-8e11-20ac25ed1e85.png)

**Comment by Pirate-Myke** [comment]
Try adding this statement to the FPE file and see if it fixes it.

skipfvfconvert = 1

**Comment by Pirate-Myke** [comment]
Do all you objects have bone driven animation?

**Comment by plemsoft** [comment]
Hi Pirate :) , ohh its a more generic error just posting it here to get it in the change log.
The problem is actually that the dbo is missing some FVF semantic names, that cause object to not display correct , like the animation above. If you use the importer the semantic is added correct and it display correctly, so im fixing the dbo when generated outside the importer.

I rarely use the importer but just add the .x , and when you do this you can get weird results like above, and you think there is something wrong with the model , but the real problem is the generated dbo not your model. 

I believe many people is working like this , so this is causing strange object problems when your not using the importer :)

**Comment by Pirate-Myke** [comment]
I never use the importer myself, as 3ds max has a plug in from Mark bliss er that exports an x file for Game guru.
Most of the stock characters are made in 3ds max and I have that max file.

**Comment by Pirate-Myke** [comment]
But using the fvf convert stateen in the fpe has always fixed for my needs.

**Comment by plemsoft** [comment]
Hi Pirate,
Yes skipfvfconvert = 1 will skip the fvf convert and use whatever is in the dbo, but in dx11 we also need to be able to change the fvf without getting problems with the models , this is used by weapons and lightmapper , so a good start is to make sure we are able to change fvf and the dbo is setup correctly :)

Also if you try to import one of your own models using the importer you notice that it do not have the skipfvfconvert but the model is still ok, this is because the dbo is correct.

So getting the models to display correct without using skipfvfconvert = 1 is a good first step.

**Comment by Pirate-Myke** [comment]
Ok. Will test a few animated objects and not include fvf statement and see what happens with the beta version I have.

**Comment by Pirate-Myke** [comment]
Ok, ran a few animated characters thru the importer without the FVFconvert statement in the FPE file, and there is the difference of the models dbo file being distorted if not thru the importer. 400kb difference in the dbo size for this model I used.

Kind of bummed out now. Was not really interested in the importer at all, since I have been doing this for a while by hand making the FPE files. But I see that I may have to run all my bone driven animated meshes thru it to make the DBO file proper.

**Comment by plemsoft** [comment]
No need to change anything , that can be done in the code after loading the dbo created this way, but im not done with the bug fix yet so...

**Comment by Pirate-Myke** [comment]
OK, no problem. I will wait for fixes. Thanks.
