### ISSUE TITLE
Max not showing Friday update splash info.

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#1040]
Max is showing last Fridays Data and Content information.. but is also showing the Update buttons yes/No to update. but I already have Last fridays update its this fridays I want.. I am not going to Press Yes on an unknown update..?? whats up

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
Language: English (Regional Setting: English)
System Model: All Series
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1600 x 1200 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1280 x 1024 (32 bit) (60Hz)

**Comment by LeeBamberTGC** [comment]
@rvanner Can you confirm this bug. Just ran on a test laptop and the 2021.03.26 build announcement showed up fine, and no update message showing, just CONTINUE button.

**Comment by rvanner** [comment]
@thor49 Can you send a screen shot of what you are seeing please?

**Comment by thor49** [comment]
![GGMax-UpdateScrn](https://user-images.githubusercontent.com/35811289/112833084-1fe83700-908e-11eb-8c92-e65c41b00e9f.jpg)
Here you are...

**Comment by rvanner** [comment]
@LeeBamberTGC Over to you on this one!

**Comment by thor49** [comment]
![GGmax-About](https://user-images.githubusercontent.com/35811289/112833538-c59ba600-908e-11eb-9410-a37f7eac61a2.jpg)
Here is my About screen

**Comment by thor49** [comment]
Hi Lee -- I have now pressed the Yes button and downloaded the new update.. But I only see the change description after the update is downloaded... I am sure we used to see the description of the changes first - then did update.. I know I am getting old maybe my memory..

**Comment by LeeBamberTGC** [comment]
Yes, before we posted the announcement as a news item, but then when you forced the update to a previous one, the latest announcement still showed. In the new system, you only see the announcement of the build you actually have. Only the update message pops up now to inform you of a new version, and you only see the latest announcement log when you have that build.

Do you think we should override the current change log announcement with the latest announcement if the software detects there is a new version available to the public from the one you have?

**Comment by thor49** [comment]
I think I was spoilt.. when I used to receive the internal announcements days before the Friday update.. and knew in advance what was going to happen..  It was just a bit strange to be stuck on the old update announcement.. 
I would prefer to see [ Here is the new stuff ( description ).. do you want to change to it now  Y/N]

**Comment by LeeBamberTGC** [comment]
@rvanner What do you think?  Have it so public builds that are not on the latest update, get the NEWS Announcement text instead of showing what is in the latest version (instead of what is in the current local build)?
