### ISSUE TITLE
SetAnimationFrames(e,v) doesn't work as displayed

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1044]
In global.lua we have SetAnimationFrames(e,v) displayed as a command, however this command doesn't work as its displayed. Instead its:
SetAnimationFrames(v,v)

with start frame and end frame, There is no way (that I know of) to define an entity ID. Its likely a typio, though would be nice if we could also define the entity number and start and end frame.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, and yes it is a typo SetAnimationFrames is a global that are used to set the start and end animation used by the next call to play or loop animation.

Thanks for your help :)
