### ISSUE TITLE
Weird image  on editor when changewindow size

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1045]
It is easy to replicate, just open a map in editor, change the GGMax window size, and wander a bit around your map, changing the camera angle, you will see weird image effects, IDK how to name it, so please, refer to the video link.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by rvanner** [comment]
@3coms Is this still an issue or can this be closed now?

**Comment by 3coms** [comment]
Fixed
