### ISSUE TITLE
F key can get stuck

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1046]
By pressing F to change the camera view, if you move around with the mouse buttons and press F a few times you will sometimes get a repeating F key event and you cannot get out of the camera view you're in.

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by 3coms** [comment]
Tried to reproduce it, but it works fine for me. So it should be fixed, though
