### ISSUE TITLE
GGMax_2021_03_26 close selecting mesh

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1049]
Go to ADD entity panel>select a building, and GGMax close suddenly.
Althought the same building open in GG without issues.
Adding video link and pic to show the issue.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by 3coms** [comment]
The building in GG
![GG_Warzone_Building1](https://user-images.githubusercontent.com/47690174/113222581-a5830700-9287-11eb-9783-f321a76eb627.jpg)

The video link

[](https://youtu.be/U3lNRH9EDKY)

The building was modeled today, therefore is not an old stock one.

**Comment by 3coms** [comment]
https://youtu.be/U3lNRH9EDKY

**Comment by 3coms** [comment]
I must ad the building is 60k in polycount and 4k texture, the same for other debris mesh that is on the top of the roof, anyway it appears no to be that issue for GG.

**Comment by plemsoft** [comment]
@3coms Thanks for reporting this issue, this should be fixed in the latest version, please give it a try and let me know :)
