### ISSUE TITLE
When you change between objects not all of the material values get updated

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1050]
Highlight an object and open the Materials section. Change the reflectance of an object, now select another object and the reflectance slider is not updated (and some others).

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue , i was not able to reproduce this in the latest version, the custom material had a rewrite , could you try it in the latest version and let me know if you still see this problem. Thanks.

**Comment by rvanner** [comment]
@plemsoft Yes, looks fixed now.
