### ISSUE TITLE
The widget casts a shadow

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1052]
It should not be casting a shadow

**Comment by rvanner** [comment]
Example: 
![image](https://user-images.githubusercontent.com/1503593/113315520-47950480-9305-11eb-9dcb-5cbf45e4ea6f.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by 3coms** [comment]
Gizmo does not cast shadows anymore, at least for me.
