### ISSUE TITLE
Change "Allow" to "Allows" in some pop up text help

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1053]
Change "Allow" to "Allows"  
![image](https://user-images.githubusercontent.com/1503593/113320118-0f43f500-930a-11eb-9f6d-64e9a74db1d3.png)

Do this for ALL the hint texts in this section

**Comment by plemsoft** [comment]
Fixed.

**Comment by rvanner** [comment]
@plemsoft Did you do all the texts, eg:
![image](https://user-images.githubusercontent.com/1503593/129706894-9344de37-c8d2-400e-a082-e814c6676089.png)

**Comment by plemsoft** [comment]
Yes :)

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
