### ISSUE TITLE
Latest GG-Max keeping last active Folder for all activities

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#1054]
Use the Model importer - choose some textures..
Exit model importer add a model to level goto object properties to add Script and GGMax shows the Texture folder not the Scriptbank.
Search for scriptbank manually.
Now Go to Main menu and select Open Map level and GGmax shows the Scriptbank folder.. 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
Language: English (Regional Setting: English)
System Model: All Series
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1600 x 1200 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1280 x 1024 (32 bit) (60Hz)

**Comment by rvanner** [comment]
This is covered in another issue so will close this issue as it's a duplicate.
