### ISSUE TITLE
2021.02.04 - Startup - Not Reliable

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1057]
MAX startup is getting worse with each build - it used to be lightning fast, at the moment Classic would win the race :)
- Often get 10-15 seconds of white screen and MAX not responding (not consistent)
- MAX will crash to desktop on startup (random)

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Managed to record this - sometimes tis a tad worse, but this is more the norm..
https://vimeo.com/532833858

**Comment by rvanner** [comment]
@michaeloldman Thanks! That delay is bad. If MAX is processing something during that time frame then it should feedback what it's doing to the user. We should also have a splash screen showing and not a big white screen and the window showing not responding.

**Comment by michaeloldman** [comment]
@rvanner Indeed - it is usually around 15 seconds at first.
But each time I close and restart MAX it may get a tad longer but usually not much longer than in the video.

But MAX is getting increasingly temperamental - it is not unusual for him to crash to the desktop after 10-15 seconds...

MAX used to start up almost instantly - and 'not responding' delays like in the video were only caused when opening a level where you had painted the terrain - may be still related to that perhaps?

**Comment by rvanner** [comment]
@michaeloldman How's the startup these days for you?

**Comment by michaeloldman** [comment]
@rvanner sorry rick, missed your reply (didn't get email it seams)
Anyhow the actual start issue reported here is no longer an issue. 

Although MAX does still take a lot longer to load an actual level than is did previously, but that is a different case altogether, so this issue can be closed :)
