### ISSUE TITLE
Editor - Player Soundset

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#106]
When you are selecting a soundset for the player to use (for example male or female) the editor says to select a WAV. Though your suppose to just select a folder. so the description for this section should change. Additionally when you click on the soundset drop down to select a folder for the soundset voices it doesnt allow you too. This is cause its trying to select a file rather than a folder. So when you hit open it does not work.

Its important to note that soundset for the player references from the "voices" folder.

Related Forum Thread:
https://forum.game-guru.com/thread/219388

**Comment by LeeBamberTGC** [comment]
I have changed the description to "Specify a WAV from a soundset, that folder will be selected". As instructed, you need to actually select a WAV file for this to work.
