### ISSUE TITLE
2021.02.04 - Stock Skybox Issues

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1061]
Multiple issues with stock skyboxes

**Not working**. Have no detail, and just uses color from previous skybox selection:
- Moon Cloud
- Red

**Noticeable banding**:
- Clear
- Dark
- Golden
- Sunset
 
**Bad rendering** at top of skybox:
- **Slightly** noticeable (probably acceptable)
- - Clear
- - Dusk
- - Night
- - HighCloud
- - Sunset

- **Bad** - easily noticeable:
- - Cloudy
- - Fluffy
- - Overcast

Example pic of **bad** rendering:
![Skybox_Issue_02](https://user-images.githubusercontent.com/12246318/113462904-e38e4f80-946e-11eb-9146-0e60db0cb419.png)

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by rvanner** [comment]
This is all old and no longer relevant. Closing down.
