### ISSUE TITLE
2021.02.04 - Skybox Square Object

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1062]
Square object showing up when using some skyboxes.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Forgot to add screenie :)

![Skybox_Issue_01](https://user-images.githubusercontent.com/12246318/113506892-c353b300-958a-11eb-95db-cbda71d86b6f.png)

**Comment by rvanner** [comment]
This has gone. Re-report if you find it.
