### ISSUE TITLE
2021.02.04 - Save Prompt Fails

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1063]
MAX does not prompt to save after changing settings in test-game
Open saved level:
- run test-game, make changes to visual settings
- exit test-game 
- close MAX
- does not prompt to save changes

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by michaeloldman** [comment]
Thanks - can close now :)

**Comment by michaeloldman** [comment]
Awesome!
You guys should stop and have a cup of tea\coffe\cocoa or something!
