### ISSUE TITLE
Importer not automatically assigning textures.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1064]
Before the last update the importer would automatically assign textures to the imported object as long as it was named correctly. For example you import a chair and your chair textures are named chair01_color - chair01_normal and so on... It should automatically find the textures associated with the entity. 
At the moment importing a model does not automatically select any texture. The textures are just blank requiring manual selection. Which cna be a real problem when importing an asset pack. 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MS-7A70
Processor: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 CPUs), ~3.0GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2080
Dedicated Memory: 8010 MB
Current Mode: 3840 x 2160 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2080
Dedicated Mpublic-api-auth-token: 58287:$2y$10$L034yk4od8VvapVAstTEdu5VE5ew9c0gEa2vbqmnQQMmwQgervG22

**Comment by Kitakazi** [comment]
Haven't tested it to much but I tried to import an OBJ file and the textures worked fine. But if I try to import an FBX it does not assign textures automatically.

**Comment by michaeloldman** [comment]
Does the same with X, but it is random. 
I use same naming convention for all my models. 
Even so, the importer assigns textures automatically - Sometimes it does - Sometimes it doesn't. 
Definitely saves time when it does work...

**Comment by Belidos3D** [comment]
I don't think this is actually a bug, with ASSIMP (which is the importer used) whether it automatically detects textures or not depends on the creation of the model and how things are named, as far as i know it will only automatically pick up the textures if the texture name is the same as the material name inside the model, so if someone creates a model and leaves the material name in the model as default (usually material, material.oo1, material.002 etc.) and then renames the texture to something else, then ASSIMP won't know what texture to use.

**Comment by Kitakazi** [comment]
Well before the update, it worked fine the week before, I tried to import same models. Last week it found the textures fine. After the update it didn't.

**Comment by LeeBamberTGC** [comment]
I still have some work to do with the surface texture aspects of the import process. The back-end is done, I just need to expose the ability to choose the channel that stores the various PBR-specific texture types. If you have a model that when imported shows NO texture, if the license permits, send to me directly at lee@thegamecreators.com (or a link to where you bought it).

**Comment by Kitakazi** [comment]
Sure thing.
