### ISSUE TITLE
When trying to create a new level the dialog box that asks if you want grass or not pops up before the dialog box that asks if you would like to save.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1065]
If you have a level and try to create a new one, the dialog box that asks if you want grass or not appears before the box that asks if you want to save your crrent level. 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MS-7A70
Processor: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 CPUs), ~3.0GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2080
Dedicated Memory: 8010 MB
Current Mode: 3840 x 2160 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2080
Dedicated Memory: 8010 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Would be better to come up with a way to get rid of dialog box for grass\clean terrain all together.
Just have a drag\drop system instead.
- New level is always plain checkered terrain
- Drag texture of choice to flood fill level
- That way you can grass or any other texture of choice as the base terrain coverage

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue, this has been fixed and will be in the next update :)
@michaeloldman Thanks for your suggestion , a future update will fix that issue :)
