### ISSUE TITLE
Max 2021.04.02 - CC looks odd now

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1066]
Verified files for the 2021.04.02 version and CC looks odd on GGMAX startup.  Character is disfigured.
Using the Max bug tracker here so not able post pic but is on forum thread (bug)

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: TECRA Z40-A
Processor: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 CPUs), ~2.4GHz
Memory: 4096MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) HD Graphics Family
Dedicated Memory: 112 MB
Current Mode: 1366 x 768 (32 bit) (60Hz)

**Comment by plemsoft** [comment]
@redagent101 Thanks for reporting this issue, this has been fixed and will be in the new update :)
