### ISSUE TITLE
MAX: 2021-04-02 "Level Objects" window issue

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1067]
The Level objects window is now floating upon startup of GGMAX.  Did'nt in last version version or version before that.  Using Max bug reporting system here so can't upload picture.  Is on the forum thread (bugs).

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: TECRA Z40-A
Processor: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 CPUs), ~2.4GHz
Memory: 4096MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) HD Graphics Family
Dedicated Memory: 112 MB
Current Mode: 1366 x 768 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Saw this also - **Reset Interface** sorts it.
But of course one should not have to sort the UI just because a build gets updated.

**Comment by rvanner** [comment]
@michaeloldman  Any idea how it actually happened? Was it just between updates?

**Comment by redagent101** [comment]
Yes, it only happens when updating to the 2021.04.02 version.  doesn't do it on previous versions.

BR
Mike
BOTR

________________________________

**Comment by michaeloldman** [comment]
`Any idea how it actually happened? Was it just between updates?`
@rvanner - have also seen it before - when we were required to remove core files before updating.

I thought it may have had something to do with custom docking. But it happened with this build, although I was using the default interface layout when I updated to 2021.02.04.

**Comment by plemsoft** [comment]
@redagent101 Thanks for reporting this issue, this has been fixed , actually it a flag that we have to set on each new build , we must have forgot in that build , sorry for that and hopefully we don't forget it in the future :)
