### ISSUE TITLE
2021.02.04 UI Bugs

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1068]
Windows (eg Settings) will move when clicking on blank space of background 
- should only move when you click\drag the window header - standard window behavior.

Color pickers will move if you click\drag background 
- should not move at all - standard color picker behavior.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting these issues, both have been fixed and will be in the next update :)

**Comment by 3coms** [comment]
Settings now do not allow drag&drop and/or mouseclick do nothing while it is open. Nice solution :)
