### ISSUE TITLE
Water

### ISSUE THREAD

**Issue by stanmorganLinux** [TheGameCreators/GameGuruRepo#1069]
During placement of water only grass was visible in the editor, and during run.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: HP Pavilion Desktop PC 570-p0xx
Processor: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) HD Graphics 630
Dedicated Memory: 128 MB
Current Mode: 1440 x 900 (32 bit) (60Hz)

**Comment by rvanner** [comment]
New terrain and water systems will sort all of this out.
