### ISSUE TITLE
Possible memory leak or similar issue.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#1070]
So I am in the process of developing a maze generator script and am using a wall entity form the buildings folder.
Basically the script generates a large maze then positions the walls where they need to be to flesh it out, the walls have no script attached (or rather they have the default.lua script specified but it amounts to the same thing).

In pushing the maze size to see how big I could go I had about 1600 walls on the map and that's when I hit a strange bug.
The maze size is 40x40 cells and during testing I was wandering around the maze quite happily for about 20 minutes when suddenly the FPS dropped to 8 (from a steady 60 up to that point) the Tab mode showed the AI slider maxed out.  A short while later GG crashed back out to the editor and reloaded the map.  

After much head scratching and several repetitions of the fault I discovered that the walls were all set as alwaysactive=yes, deleting them all and replacing them with walls with alwaysactive=no stopped this from happening, the AI slider dropped to minimum and stayed there no matter how long I wandered around my maze.

To me this indicates that somewhere in code triggered by the alwaysactive flag there is probably a memory leak or something causing Lua's housekeeping to fail to clean up properly (which amounts to the same thing), I think it was shear luck that I happened to inadvertently have so many always active entities that I hit the problem reasonably quickly but even with less always active entities (and many entities are set always active by the engine, e.g. characters and markers) there may be a slow but steady leak (or whatever is the cause) which will eventually cause a failure.

**Comment by AmenMoses** [comment]
Confirmed it is a memory leak.
To replicate plonk down a tree, set it static=no and alwaysactive=yes.
Extract it, press i and paint a few thousand all over the map.
Press test level and bring up the task manager, then just sit back and watch GG's memory grow until it crashes and burns!

**Comment by Granada1** [comment]
Good catch Amen 👍

**Comment by smallg2020** [comment]
getting the leak here too, i noticed if i turn off AI (with F11 toggles) it goes away so definitely seems to be a lua issue.
it happens with non-always active entities too but it's slower due to it not happening if they are out of range - so i guess they only leak (or continue to leak) when they are activate in the level (i.e. nearby).

**Comment by AmenMoses** [comment]
Update:
drawcalloptimizer=0 
In the setup.ini file seems to stop the memory leak!
Think this may be one for Preben.

**Comment by AmenMoses** [comment]
Ok, so I think I may have tracked it down.

M-Game.cpp calls DeleteObject(tmpobj), this functiuon checks that the specified object exists, in particular that the id is less than g_iObjectListCount.
Looking up through the code to see where tmpobj is defined it appears to be a number way above what g_iObjectListCount is likely to be so the DeleteObject() call isn't doing anything.

**Comment by plemsoft** [comment]
@AmenMoses A'Maze'ing code :) , the best think to do when changing objects in lua , is to set them to "spawnatstart" = no , this way the drawcall optimizer know it should ignore them.

Checked the DeleteObject(tmpobj) , and it looks fine , the CloneObject a few line below will make sure to adjust the g_iObjectListCount and resize the array. also if you look around 100 lines below this , it also have a DeleteObject(tmpobj) , so the object do get deleted. The first check "if (g_ObjectList[tmpobj])" is just to make sure that it dont already exists (for some reason).

If the drawcall optimizer need to optimize all these objects it will use more memory, but should be stable not leak.

Do you still see memory leak if you use ""spawnatstart = no" ?. if so its back to "alwaysactive=yes" and a lua leak somewhere :)

**Comment by AmenMoses** [comment]
Explain why drawcalloptimizer=0 stops the memory leak then.

**Comment by plemsoft** [comment]
@AmenMoses It will do the same as "spawnatstart = no" , it will disable the optimizer and will not create additional objects and use additional memory when you click "test game".

The optimizer create new objects of the "merged" object, and hide the original objects. But it only do this when you click "test game" and only before your level start, so after your level is running the optimizer is done and cant use any more memory.

Also if you notice, in test game if you "run" to the place where you put all the "dummy" wall objects, you see that even if you have placed all the walls in your maze , at the original position you will still have a copy of all the walls , this is the drawcall optimized objects.

**Comment by plemsoft** [comment]
"Explain why drawcalloptimizer=0 stops the memory leak then." , do you see the leak after you started "test game" and while running ? and do you not see it if you use drawcalloptimizer=0  ? strange ?

**Comment by AmenMoses** [comment]
Yes.

The leak continues until GG dies, drawcalloptimizer=0 in the setp.in and no leak.

This is on a level with just a lot of trees, no scripts (apart from the core ones) involved.

The always active part seems to be a red herring as the leak occurs with any dynamic entities present, see smallg's comment.

All a bit puzzling.

**Comment by smallg2020** [comment]
spawnatstart = no (no leak while the objects are inactive/not spawned) but no, not fixing the issue as as soon as they spawn it starts leaking memory.
p.s. takes ages to spawn a large group of objects - was this always the case?

definitely still leaking if not always active, just much more noticeable on always active as you will only leak for entities in range otherwise.

[https://youtu.be/0uG_4X232Fs](url)

**Comment by AmenMoses** [comment]
I just tried changing the drawcalloptimizer settings and this time it didn't seem to make any difference, but this time I was using simple crates instead of animated trees.

Just trying to replicate it on my maze again.

**Comment by plemsoft** [comment]
@AmenMoses Yes i can see that leak, trying your maze script, must be something lua related ? , but cant be any draw call optimizer related. @smallg2020 Yes without the draw call optimizer it still leak. so next must be to look at the lua stuff :)

**Comment by AmenMoses** [comment]
So I went back to the original map, just thousands of always active trees, no extra scripts running.

That's probably the one to use to replicate this, assuming it is a single memory leak we are looking for.

The AI bar is high, not sure what that bar actually measures though.  All the trees have 'defalult.lua' attached which looking at the source code means they shouldn't even be included in the Lua calling bit.


[alltrees.zip](https://github.com/TheGameCreators/GameGuruRepo/files/6290235/alltrees.zip)

Just rename to .fpm to use.

**Comment by AmenMoses** [comment]
Running my maze level again (all walls active but with alwaysactive=no and issimobile=yes), if I leave it running then over a very long time the memory usage creeps up but it is not a continuous increase, it goes up a bit then down a bit etc but over all it is increasing nonetheless so we may actually be looking at more than one leak. 

The drawcall option setting seems to have been a red-herring, today it doesn't seem to make any difference to the outcome except to effect the starting memory usage value.

**Comment by AmenMoses** [comment]
So a bit more investigating:
Isolated the issue with the 'thousands of trees' fpm to the  lua_loop_allentities function in M-LUA.cpp.
Added the following line to the start of the loop through all entities:

if (t.entityelement[t.e].eleprof.aimainname_s.Lower() == "default") continue;

And the memory leak stops. (this line is actually just a copy of the logic applied further down the routine just before it attempts to call the _main function for the active entity)

But, I still don't have a clue as to where the memory leak is occurring within this loop.

**Comment by plemsoft** [comment]
@AmenMoses Thanks for the help :) , found the problem, its actually in the call to "UpdateEntityRT" that cause it, this line leak.
"LimbName(iObjectNumber, t.entityelement[t.e].detectedlimbhit);" , replace this line with:

`
										if (ConfirmObjectAndLimb(iObjectNumber, t.entityelement[t.e].detectedlimbhit))
										{
											// get name of frame
											sObject* pObject = g_ObjectList[iObjectNumber];
											LPSTR pLimbName = pObject->ppFrameList[t.entityelement[t.e].detectedlimbhit]->szName;
											pLimbByName = pLimbName;
										}
`
And no more leak , well its used in more places where it also have to be fixed.

Fixed and ready for the next update :)

**Comment by AmenMoses** [comment]
So the leak is actually in the LimbName function.

I replaced it with:
DARKSDK_DLL LPSTR LimbName ( int iID, int iLimbID )
{
	// check the object exists
	if (!ConfirmObjectAndLimb(iID, iLimbID))
		return NULL;

	// return name of frame
	return g_ObjectList[iID]->ppFrameList[iLimbID]->szName;
}

And tested on both the alltrees.fpm and the large maze and can confirm no more memory leak, hoorah.

**Comment by AmenMoses** [comment]
Looks like LimbTextureName ( int iID, int iLimbID, int iTextureStage ) may have the same issue.

**Comment by plemsoft** [comment]
@AmenMoses CreateDeleteString is used in places where you change the returned data after getting the data.
like: 
LPSTR test = LimbTextureName ();
test = test + "1";

This would change the original string , like if you returned "g_ObjectList[iID]->ppFrameList[iLimbID]->szName", thats why CreateDeleteString  is used so you never change the original data.

So better to leave those CreateDeleteString there and just change it where needed or free the strings after use like "delete [] test".

BTW: also checked the LimbTextureName functions and now free data where needed.
