### ISSUE TITLE
level objects window

### ISSUE THREAD

**Issue by niijel** [TheGameCreators/GameGuruRepo#1072]
it now apears on top of toolbar, not docked and when removed by clicking X in top right cannot be re-opened?

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z170XP-SLI
Processor: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 CPUs), ~3.5GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 2560 x 1440 (32 bit) (59Hz)

**Comment by rvanner** [comment]
@niijel I presume this very old report has since been fixed. Closing this issue. If you still have issues please re-report and show a screen shot. Thanks!
