### ISSUE TITLE
Improve memory use by adding in instancing of objects

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1074]
Just adding barrels to an empty level seems to eat system memory.

**Comment by AmenMoses** [comment]
![max_memory](https://user-images.githubusercontent.com/35708338/113783038-08aee680-972b-11eb-8c12-e1920202c794.png)

Clean load of MAX, dragged on a bunch of barrels and brought up the task manager.

There is probably in the region of 300 barrels and nothing else.  

Gen 9 i5 6-core + RTX 2060 Graphics card btw.

**Comment by AmenMoses** [comment]
![memory test](https://user-images.githubusercontent.com/35708338/116885994-75c97500-ac20-11eb-90a5-68368327aa51.png)

So I deleted everything MAX related from my machine and installed from fresh with the mini installer.
MAX is installed on my 'F' SSD drive (where I keep all my GG dev stuff).
Screen resolution is  2560x1440
Exactly 900 static oil cans placed on the map in the picture.
Too the screen shot, saved the level, restarted MAX, loaded the level - same results.

**Comment by rvanner** [comment]
@LeeBamberTGC Can you or Preben look into this sometime this week?

**Comment by LeeBamberTGC** [comment]
@plemsoft Do you think this has been resolved with your recent memory leak fix as it was not in the Friday build?

**Comment by AmenMoses** [comment]
Hi Lee,

I don’t think it is related, the memory leak was on active entities but this one is there for static as well.

Cheers,
Chris.

**Comment by plemsoft** [comment]
@LeeBamberTGC Yes the recent memory tweaks has reduced this a lot. but the next step is adding the instancing when we are done with the "final" clone features, This will get it to a normal mem use for this type of reusable objects.

1000 oil cans:
![1000-oil-cans](https://user-images.githubusercontent.com/18662417/117011049-bba03f00-aced-11eb-960d-b7ec3d90b54e.jpg)

**Comment by rvanner** [comment]
@LeeBamberTGC Has instancing been implemented in MAX to date and thus solve this?

**Comment by plemsoft** [comment]
@rvanner Instancing has not been added, to instance a object all "material" settings need to be the same , so as long as the importer features and the "Custom Material" settings is not final, its hard to setup instancing. Perhaps this should be moved to TW so we can discuss the best way to do this.

**Comment by rvanner** [comment]
@plemsoft Agreed. I will create a message thread on TW so we can talk about it within the team.

**Comment by rvanner** [comment]
@LeeBamberTGC I know memory issues have been fixed but this is more to do with adding instancing of objects to save further memory use. We don't have time now before EA to implement so I will mark this as Post EA and rename it.
