### ISSUE TITLE
I have issues when i want import my models in game guru

### ISSUE THREAD

**Issue by hamedsheygh** [TheGameCreators/GameGuruRepo#1076]
the importer break all of my low poly and high poly models .I think the smooth shade of importer goes wrong many times.
For example i cant import my door way model correctly that only have 16 polygons.(i have the same problem when i disable shade smooth in blender too.)And actually my models works great in other engines. my models formats: fbx , x
My system : 
Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz 
Installed memory (RAM): 16.0 GB
Graphic card : 6 GB nividia extreme gaming

**Comment by hamedsheygh** [comment]
### gg

**Comment by rvanner** [comment]
@hamedsheygh The importer is not fully complete and has known issues. Can you post some screen shots so we can see what issues you are having?

**Comment by hamedsheygh** [comment]
![gg](https://user-images.githubusercontent.com/82085749/113923567-ea65eb00-97fd-11eb-93bc-1b878d10eb30.PNG)
my friend use my door way model in gg and have same problem but i only own gg classic and the results are added below.

**Comment by hamedsheygh** [comment]
![gg1](https://user-images.githubusercontent.com/82085749/113924090-9f98a300-97fe-11eb-826c-3a1e5749ac11.PNG)
original model

**Comment by Belidos3D** [comment]
Can you show a wireframe image of that model in edit mode please. The reason that happens is usually because of NGons, if the front face on that model is one huge NGon which I'm guessing it is then GameGuru will not be able to interpret the hole in it and will try to fill it in as best it can, i'm surprised if it would work in anything else either because there's no engine built that would be able to correctly display an NGon of that shape, it would only work in Blender, because it was made in Blender.

**Comment by hamedsheygh** [comment]
![Screenshot (400)](https://user-images.githubusercontent.com/82085749/114009779-b4198180-9878-11eb-8678-ae23ec361f38.png)
what is ngon? i build all of my models with boolean tool in blender and all of are loaded in unity and unreal without a problem.
if i use boolean tool in blender and try to load the model in gg the model will loaded invisible sadly.

**Comment by GraPhiX-Guru** [comment]
basically all you really need to do is triangulate your model

**Comment by hamedsheygh** [comment]
thank you graphics but how to do that? with knife tool or something else.? is there any automatic way to do that?

**Comment by hamedsheygh** [comment]
@GraPhiX-Guru

**Comment by GraPhiX-Guru** [comment]
are you on GameGuru Discord ? if so can you export your model to obj and send it to me, i will show you how to get rid of the Ngons, i do not use Blender so will use another program

**Comment by Belidos3D** [comment]
> thank you graphics but how to do that? with knife tool or something else.? is there any automatic way to do that?

Yup that's a huge nasty NGon. 

All you need to do is in Edit mode switch to vertex select (1 on the keyboard) and join the vertices where i have put the red lines in the picture below, you do that by selecting two vertices and pressing J, do that for both the red lines and do the same on the reverse side of the model. 

That's all you will need to do, GameGuru will triangulate the mesh automatically, you don't need to triangulate as, it just doesn't know how to change complicated shaped NGons so it's not doing it properly as it is, most game engines will have the same issue. However if you want to triangulate it before hand you can press A to select all of the faces, then press ctrl+T and blender will triangulate it for you. 

![114009779-b4198180-9878-11eb-8678-ae23ec361f38](https://user-images.githubusercontent.com/37830536/114023132-65fd8180-986a-11eb-9d16-ea094ad23012.png)

**Comment by rvanner** [comment]
@hamedsheygh Do you still have issues with the importer in the latest MAX? If you do, can you send a model that shows the issue?

**Comment by rvanner** [comment]
@PaulSJ I don't think this is our issue? If you agree then please close it down.
