### ISSUE TITLE
Why is Save shortkey Control+Q? Would be better as Control+S

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1077]

**Comment by synchromesh62** [comment]
**Why is Save shortkey Control+Q?**

Control+S is already used to slowly zoom out of the editor Viewscreen
Hence using Control+Q

**Comment by rvanner** [comment]
@synchromesh62 Of course it is! Doh. OK, I'll kill this one. Cheers.
