### ISSUE TITLE
Entity panel bug

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1079]
All is scrolling at high speed, and I have to close it to stop it scrolling.
Adding some YT video link showing the bug, once there, is so easy to get the point.
Also include Importer bug I'm going to report too, with their own video link.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by 3coms** [comment]
[](https://youtu.be/jdCPgwoVtfQ)

**Comment by 3coms** [comment]
[](https://youtu.be/jdCPgwoVtfQl)

**Comment by 3coms** [comment]
The YT link
https://youtu.be/jdCPgwoVtfQ

**Comment by plemsoft** [comment]
@3coms Thanks for reporting this issue, this has been fixed and will be in the next update :)
