### ISSUE TITLE
Importer bug

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1080]
GGMax closing when try to import dbo and/or X file, just fbx is working fine for me.
Adding YT video link showing the bug.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by 3coms** [comment]
YT Link
https://youtu.be/OW4Z2aieUVE

**Comment by 3coms** [comment]
Most of you already have some of my models, my suggestion, try to import it dbo and/or X files, using custom paths to save them.

**Comment by rvanner** [comment]
@3coms Is this still an issue for you? If so, can you send me one X file so we can look into it. Thanks.

**Comment by 3coms** [comment]
Fixed.
