### ISSUE TITLE
Request for new feature ( outline entity )

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#1084]
HI. would it be possible to give us this function that can out line an entity in the game to attract the players attention so that the player can interact or pick up the entity Some thing like we have now in the Max editor like this: https://forum.game-guru.com/thread/222661?page=1#msg2640428

Ps:.. If this is possible and not to much extra work , how about also give it to GG Classic as well
     would be supper awesome

Thanks so much

**Comment by michaeloldman** [comment]
Yes - this would be a great feature to have - Not a new concept by any means, Republic Commando had it way back in 2005 for example - but is something that would really be useful for all types of games. Would especially cool if you had some control over highlight color used - would love to have it in puzzle games.

So it would be great way to help Make MAX Great! :)

**Comment by Pcskiller** [comment]
Any feedback on this?

**Comment by Pcskiller** [comment]
???

**Comment by OldFlak** [comment]
@Pcskiller Tis in lates EXP 👍

**Comment by LeeBamberTGC** [comment]
New LUA commands added:
SetEntityOutline: SetEntityOutline(e,value) -- this command changes the entity object outline property.
GetEntityOutline: GetEntityOutline(e) -- this command gets the entity object outline property.

**Comment by OldFlak** [comment]
@LeeBamberTGC cool stuff 👍 
Have not looked at coding this feature yet, the only commands I can see int the Global are the ones mentioned above
- do we (if not, can we) have ability to set the color of the outline :)

Thanks for considering :)
