### ISSUE TITLE
Advanced link in the Rotation and Scale sections of Object Tools

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1086]
If the advanced tools are not turned on, then if you are viewing the Rotation and scale sections the "Advanced" link should be shown below them.

ie this;
![image](https://user-images.githubusercontent.com/1503593/114662339-6d9caa80-9cf0-11eb-8b13-d49d24428037.png)

Should be below this;

![image](https://user-images.githubusercontent.com/1503593/114662312-5eb5f800-9cf0-11eb-9982-f6b35384fa60.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next update :)
