### ISSUE TITLE
Bug reporting system description edit box can go crazy as you type

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1087]
Yes, a bug in the bug reporting system!

OK, so as you type the description of a bug report the edit box can go haywire. Watch this video to see what happens:

https://youtu.be/3LQcQuuOqSs

**Comment by michaeloldman** [comment]
Also has a fit if you paste text into it (CTRL+V)

Tis not really friendly to use. Really only good for one liners atm :(

What I do is: add the title, add short amount  of text in description, create the report, then click it to go to the github and format the text the way I really want it to read.....

**Comment by rvanner** [comment]
@LeeBamberTGC Try copying the text in Michael Oldman's message above and pasting it into the bug report description. When I did it the page scrolled like it does in my video. So still dodgy!

**Comment by rvanner** [comment]
We are now removing the bug reporting system and directing users to the GitHub board instead.
