### ISSUE TITLE
Icon on a group should reflect it's current state

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1089]
The lock / unlock icon should show what state it's in, not the state it will be in when you next click it.

So for example, this should show the group unlocked (not locked):

![image](https://user-images.githubusercontent.com/1503593/114665168-9626a380-9cf4-11eb-8688-5dc3d14326e7.png)

**Comment by plemsoft** [comment]
Fixed

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
