### ISSUE TITLE
Physics - FPS Drop When Player Pushes Corners

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#109]
Serious FPS drop if player collides between two static entities (walls such as fences and gates).

Best way to test this is to place two fences together to make a corner and have the player push against that corner. The FPS can drop as much as 40 frame per second. 

Duplicate issue #23

**Comment by tarkus1971** [comment]
Yes, confirmed.

**Comment by LeeBamberTGC** [comment]
Can you give the names of the fences/gate entities and perhaps even attach an FPM which makes reproducing and fixing quicker. Just went through some of the early issues tracker bugs and I spent more time recreating scenarios only to find no bug to fix than actually doing some proper codin'.  Would help a lot, thanks!

**Comment by Teabone3** [comment]
Here is how to reproduce 
Security Fence in the Scenery folder:

https://www.youtube.com/watch?v=ZnvVIK3bRbE

**Comment by tarkus1971** [comment]
It seems to happen when two or more entities with POLY collision overlap.

**Comment by StabInTheDarkSoftware** [comment]
https://forum.game-guru.com/thread/219369?page=2

**Comment by thecyrus** [comment]
I also noticed it in a chair near to the wall, for example.

**Comment by Teabone3** [comment]
Has this been fixed in later builds? I still consider this a bug. Going to do some testing.

**Comment by synchromesh62** [comment]
Try collisonmode = 9 in the fpe 
That should fix it.

**Comment by LeeBamberTGC** [comment]
I have edited the Security Fence collisionmode to zero (box) as that is the correct shape for this model. If you find any other models that are using the wrong collision shape, report them and we can make sure the stock assets are corrected. As Preben says, the convex hull is a new collisionmode if you want to retain some of the shape of the model without hitting the physics performance.
