### ISSUE TITLE
UI transparency does not work when using the BLUE style

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1091]
The new BLUE UI style does not work with transparency.

**Comment by rvanner** [comment]
If you click on Enable Custom Colors it also reverts to grey color mode.

**Comment by rvanner** [comment]
When you reset to defaults the UI changes to Grey, it should change to Blue.

**Comment by plemsoft** [comment]
@rvanner Added a little transparent and fixed the others listed here.
