### ISSUE TITLE
Don't allow settings to be resized very small

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1092]
You can resize settings so it looks poor. Here's an example;

![image](https://user-images.githubusercontent.com/1503593/114713452-0a7b3a00-9d29-11eb-9e55-422bd818f338.png)

There should be a minimum width and height for this window. 

Make sure the color values don't come out of their boxes;
![image](https://user-images.githubusercontent.com/1503593/114713613-372f5180-9d29-11eb-82a4-a51d48b68be0.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this, the problem has been fixed and will be in the next update :)
