### ISSUE TITLE
[GGC] Lightmapping issue: Lightmapping breaks LOD

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#1094]
Lightmapping in Game Guru Classic appears to break LOD meshes on some models. This video shows two instances of the same crate, the one on the left was placed into the level and lightmapped, and then I placed the one on the right (which hasn't been lightmapped). You can see the LOD meshes pop in for the crate on the right, but not the left one. 

[https://youtu.be/titDA-QryV4](https://youtu.be/titDA-QryV4)

You'll also notice the lightmapped crate is super bright. This could be related to issue #976

**Comment by plemsoft** [comment]
@AvengingEagle Thanks for reporting this issue, yes thats how the lightmapper works , it will remove all LOD and create a single object of all objects located in that grid, As the lightmapper create a single object you save on drawcalls and its way faster, so LOD is not needed for the individual objects.

Im not sure why the object is brighter , did you move the object after lighmapping ? , could you try to make a new lightmap and check if its still bright ?, Thanks for your help :)

**Comment by AvengingEagle** [comment]
I could not replicate the issue when I lightmapped again and I couldn't work out why because I hadn't changed anything. Then I realised; previous I had my lightmapping size in setup.ini set to 340 to save memory and create blurry lightmaps. I arrived at this number back in 2019 when I had been testing and found 256 too low resolution but 512 too sharp for the soft light sources I am trying to recreate. Last week, I set my lightmap size back to 512 to run some tests, this appear to have solved the issue. 

The learning here is: always set the lightmap size to 256, 512, 1024, or 2048.

**Comment by plemsoft** [comment]
@AvengingEagle FYI: if you want a more blurry shadow you should try to use setup.ini command "lightmappingblurlevel=100" set it to "lightmappingblurlevel=300" to get it more blurry. it only have 4 option so you can use 50,100,200,300 for this command anything else will not make a difference.

**Comment by AvengingEagle** [comment]
What does lightmappingquality= do? Mine is currently set to 500.

**Comment by plemsoft** [comment]
@AvengingEagle It control the scale of the UV mapping and then again how many objects can be batched and use the same lightmap texture / UV map, it would be better to just increase the lightmap texture size then experimenting with this :)
