### ISSUE TITLE
Change "Entity" to "Object" in these help pop ups

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1095]
Do a search and replace because there's a lot of them;

![image](https://user-images.githubusercontent.com/1503593/114759722-70ca8180-9d56-11eb-8618-9071889129b5.png)

**Comment by plemsoft** [comment]
Fixed.

**Comment by rvanner** [comment]
@plemsoft Can you mark the ones you have fixed in the spreadsheet as well? Thanks.

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
