### ISSUE TITLE
Shadow Cascade Improvement Suggestion

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#11]
Here are 2 screenshots to compare:
http://www.slungo.com/gglsample1.png
http://www.slungo.com/ggsample1.png

If you looks at the complete screen you notice that most shadow pixels are in the distance , and the samples could be reduced, sure 8 cascades looks better in the mid range and far away , but i think that fewer cascades and shadow sample decreasing by distance would make better results.

Processing 4 1024 cascades is much slower then 1 cascade using 2048. so there is a huge fps increase if perhaps all the far away cascades 4-8 was one 2048. ( all the cascades dont need to be the same size , perhaps thats something for the setup.ini different image size for each cascade. ).

**Comment by plemsoft** [comment]
This was made from version "2018.06.16 - DirectX 11 & PBR"+
