### ISSUE TITLE
Entity - Bunny Character's Feet in Ground

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#110]
Bunny from Cartoon theme is slightly lower in the ground, hiding its feet. Noticed this in previous PP as well.

**Comment by HierToo** [comment]
@Teabone3 can you please test it again if this still exists? I can not replicate this bug.

**Comment by Teabone3** [comment]
Since this issue is still present. I'll show a screenshot of what it looks like. Place Bunny from Cartoon theme folder onto map. Sinks through terrain.

**Comment by redagent101** [comment]
had the same issue today with a WW2 character from FPSC.  I set the defaultheight parameter in FPE to defaultheight=3.0 and that fixed the issue.  I will test this on the bunny character see if it fixes the problem, if not will look into further

**Comment by redagent101** [comment]
fixed issue by setting defaultheight to 3.0 in FPE.  This is a DLC pack issue and requires TGC or whoever created the pack to fix the FPE and any other entities that have same issue.
![easter bunny sinking issue fixed](https://user-images.githubusercontent.com/15969299/58964823-75f83600-87a7-11e9-97f1-fda1b09d2f87.png)

**Comment by redagent101** [comment]
sorry wrong bunny, will do same for cartoon bunny.  need new glasses.

**Comment by redagent101** [comment]
ok setting defaultheight to 3.0 doesn't work in test game.  will investigate further.

**Comment by redagent101** [comment]
FPE(s) now updated for both bunny entity types. see attached.
![cartoon bunny sinking issue fixed_due to FPE](https://user-images.githubusercontent.com/15969299/58966596-77772d80-87aa-11e9-8e36-cbd1137082fb.png)
[Rabbit Armed.txt](https://github.com/TheGameCreators/GameGuruRepo/files/3257734/Rabbit.Armed.txt)
[Rabbit.txt](https://github.com/TheGameCreators/GameGuruRepo/files/3257735/Rabbit.txt)

**Comment by redagent101** [comment]
Note : attached FPEs as .txt as uploader doesn't recognise .FPE

**Comment by Teabone3** [comment]
Thanks for looking into this one
