### ISSUE TITLE
Tick box positions

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1103]
Tick boxes should always be on the left for consistency.

![image](https://user-images.githubusercontent.com/1503593/115014802-b6985e80-9eaa-11eb-90fc-c9ba7266a1d8.png)

![image](https://user-images.githubusercontent.com/1503593/115014853-c6b03e00-9eaa-11eb-8cfe-09c6b15c644e.png)

**Comment by plemsoft** [comment]
Fixed.

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
