### ISSUE TITLE
Max - Build 2021.04.16 crashes more than any other version

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#1109]
Max crashes to desktop if I try load pre-saved levels.
Max crashes if I try to start new level with some of the models from the saved levels. These had always worked with the previouse versions..Max is very unstable..

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: All Series
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1600 x 1200 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1920 x 1080 (32 bit) (75Hz)

**Comment by rvanner** [comment]
@LeeBamberTGC I have this issue too. I was loading a level made by Martin to make a screen shot and now it failed to load.

**Comment by thor49** [comment]
Also in the new Object Tools - Materials section ...with the new dropdown box...
Every time I have tried to use it Max Has crashed to desktop..
I can get the albedo in then the Normal .. but try something with those RGBA buttons
and choose texture file and it then crashes..

**Comment by LeeBamberTGC** [comment]
@thor49 There was a serious crash on certain objects (single textured ones). I have made a mini-update to the current public build which should be available by 5 PM GMT.  If you can go to your auto updater and verify files you should see an extra line in the changelog announcement that includes the crash fix item. Let me know if you see this new version, and if it solves the crash you are having. Thanks!

**Comment by thor49** [comment]
Hi Lee - I got the update..
The Object Tools - Materials section RGBA buttons above... This is the first time I have been able to use these without a crash...

But my saved levels are still crashing trying to load...
One of them I did get to load.. but it crashed to desktop while a tried a test run... after 10-15 seconds.
Tried it again and it loaded but one of the characters had lost the hair texture.. used the materials Object tools
to get that back but when I ran level the Hair texture had gone back to white no texture..

On some saved levels it just goes into a not responding loop -- I eventually have to use task manager to  End task.
but the majority of levels it just crashes to desktop try to load...
Then on one attempt to load a level I got this error box..(below)
![GGmax-error1](https://user-images.githubusercontent.com/35811289/115450783-42e0b380-a214-11eb-8aa1-2efdd31efb1c.jpg)

Also the Character Creator.. select female - select wearing white glasses and instant crash to desktop on prev-version
on this update goes into constant (loading) unresponsive loop... have End task with task manager..

**Comment by thor49** [comment]
By the way Lee what is the correct way to use the new RGBA buttons on the textures is there a document to tell us what
we should be attaching to these...

**Comment by thor49** [comment]
Hi Lee disregard the Character Creator report - I think I had the Error box above still active on my screen..
and then I re-checked the character creator bug before I told you about it.. so I think I started a new instance of GGmax..
I have now just tried the white glasses and it is working ok in this update.
( I have noticed this before that I can have 2 instances of GGMax running.. this should be stopped )
oops

**Comment by thor49** [comment]
Spoke to soon Character Creator the white glasses are now loaded but then try brown blouse and GGmax Crashes to desktop.

**Comment by Granada1** [comment]
Tested myself changed to female ,chose white glasses ok. Tried to save character and Max crashed to desktop

**Comment by LeeBamberTGC** [comment]
Just tried with latest internal build (out in about 30 minutes) and no crash, and looks fine:

![image](https://user-images.githubusercontent.com/35840583/115464086-71668a80-a224-11eb-9151-4abff9033df8.png)

**Comment by Granada1** [comment]
Hi Lee, did you try to save the character

**Comment by LeeBamberTGC** [comment]
Yes the character you see in the shot is a saved character creator character :)

**Comment by Granada1** [comment]
just tried with this build got her to save but crashed when dragging her in
![LBuild_002](https://user-images.githubusercontent.com/35897659/115471474-f73c0300-a22f-11eb-8b02-2b9a05cf9fef.png)

**Comment by LeeBamberTGC** [comment]
The crash is a little odd. Any chance you can find time to do a small video showing her being created, saved, then dragged in? If you have SETUP.INI with producelogfiles=1 and send me the .log file, I might be able to see where it crashed too.

**Comment by thor49** [comment]
This is the version I am using.. just did verify files now today
![max-ver](https://user-images.githubusercontent.com/35811289/115541783-6f89df00-a297-11eb-93f4-94cd73e085f8.jpg)
...
CC Female white glasses -- crash to desktop..

**Comment by thor49** [comment]
How do I get the version you are using...

**Comment by LeeBamberTGC** [comment]
It's only an internal build (usually unstable) but we should have it stable and ready for Friday :)

**Comment by thor49** [comment]
Thank you Lee..
Max - new Build 2021.04.30 -- I can now load my old previous saved levels.. good work..
