### ISSUE TITLE
Time of day does not match editor with in game

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1112]
I have a level set with Morning for time of day. When I use test game the scene changes and is darker.

Watch this video, you can see it's light in the editor but when the test game starts it seems to be dusk or dawn:

https://youtu.be/m3Hy6hoNWKk

**Comment by plemsoft** [comment]
Fixed :)

**Comment by rvanner** [comment]
Fixed in latest version. Closing this issue.
