### ISSUE TITLE
The save game path changes after an import

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1113]
The save game location changes to where I last imported a 3d object. 

It should stay in the mapbank folder and only change if the user changes where they last saved a map file.

**Comment by plemsoft** [comment]
Fixed: Load/Save fpm will now default to the mapbank. This is where the "Write Folder Location" is set, could be "c:\\user..." or a custom write folder.

**Comment by rvanner** [comment]
Fixed in latest version so closing this issue now.
