### ISSUE TITLE
Loading GG classic maps crashes to desktop

### ISSUE THREAD

**Issue by PaulFox12** [TheGameCreators/GameGuruRepo#1115]
Loading almost any GG classic maps crashes max to desktop, sometimes it gets as far as "converted x models from classic to max" and then crashes, other times it doesn't even get this far. 
Aware there is not fully backwards compatibility with classic but crashes don't give any indicator what's not working/compatible in the classic map

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Aspire VN7-593G
Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 CPUs), ~2.8GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) HD Graphics 630
Dedicated Memory: 128 MB
Current Mode: 1920 x 1080 (32 bit) (59Hz)
Card name: NVIDIA GeForce GTX 1050 Ti
Dedicated Memory: 4021 MB
Current Mode: Unknown

**Comment by Kitakazi** [comment]
I have also been unable to open my classic maps in Max. Before last week I'd say there was a 50/50 chance it would crash when trying to open my classic maps. Now it is 100%.

**Comment by plemsoft** [comment]
@PaulFox12 Thanks for reporting this issue , this has been fixed, sure there can still be some problems with some classic media, but it will not crash.

**Comment by Kitakazi** [comment]
@plemsoft 
Fixed for next update or the one released yesterday? Cause I can't open any of my classic maps on the current version.

**Comment by plemsoft** [comment]
@Kitakazi No sorry it did make it into that build, i was to slow :) , but in the next build.

**Comment by Kitakazi** [comment]
Thats great news, thanks.

**Comment by LeeBamberTGC** [comment]
New mini-update live :)
