### ISSUE TITLE
Unable to move around the viewport in GGMax build 2021.04.23

### ISSUE THREAD

**Issue by HeadClot** [TheGameCreators/GameGuruRepo#1116]
I am unable to move around the view port in any way shape or form. I have tried pressing the WASD keys as well as the arrow keys. Nothing happens. I am on MAX Build 2021.04.23 if that helps. I have tested this against an older Game Guru build and the viewport naviagation works there.

Reproduction steps:

1. Download GGMax build 2021.04.23 from the launcher.
2. Press W A S D keys as well as the right mouse button. 3. No view port movement will occur. 
What should happen:

I should be able to move around the scene using the WASD Keys and right mouse button.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MS-7A38
Processor: AMD Ryzen 5 2600 Six-Core Processor             (12 CPUs), ~3.4GHz
Memory: 32768MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: Radeon RX 570 Series
Dedicated Memory: 8171 MB
Currentpublic-api-auth-token: 184578:$2y$10$jNmAO1TSeIpYlpXj4y/Tt.DRJRcNsc1NTl4GfuaZYnc91uDXEo36q

**Comment by rvanner** [comment]
Have you left clicked into the view port first to make sure it has the focus?

**Comment by HeadClot** [comment]
Yes I have.

**Comment by rvanner** [comment]
@HeadClot Could you make a small video and share it with us. It's a very odd issue. 
What keyboard are you using on your PC?

**Comment by HeadClot** [comment]
Yeah I can do that. Let me grab a video recording software :)

As for what Keyboard I am using It is a Microsoft Wired Keyboard. It is really nothing special.

**Comment by HeadClot** [comment]
Hey - I just downloaded the latest build to get a video of the issue that I have posted. Seems like It has resolved. 

I am able to navigate around the viewport now.
