### ISSUE TITLE
HUD and arms show on terrain

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1121]
Pointing the camera to the terrain shows the HUD/Arms shadow.  using the inbuilt bug reporting system so cant upload pic here.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: TECRA Z40-A
Processor: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 CPUs), ~2.4GHz
Memory: 4096MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) HD Graphics Family
Dedicated Memory: 112 MB
Current Mode: 1366 x 768 (32 bit) (60Hz)

**Comment by redagent101** [comment]
![visible_hud_arms_camera_directed_to_floor](https://user-images.githubusercontent.com/15969299/116773698-e28d1580-aa4e-11eb-8033-60785ea0a67e.png)

**Comment by redagent101** [comment]
this is in relation  to version 2021.04.30

**Comment by redagent101** [comment]
I will test on PC to see if it still does it as my laptop GFX card isnt min specs.

**Comment by redagent101** [comment]
does the same on my PC GEForce GTX-1060 (3GB).
![hud_and_arms_shadow_on_terrain_visible](https://user-images.githubusercontent.com/15969299/116775303-46690b80-aa5a-11eb-8d70-20922b0a15bf.png)

**Comment by Granada1** [comment]
I get the same, on internal levels also

**Comment by plemsoft** [comment]
@redagent101 Thanks for reporting this issue, this has been fixed and will be in the next update :)
