### ISSUE TITLE
Entity crashes Max

### ISSUE THREAD

**Issue by andypmillard** [TheGameCreators/GameGuruRepo#1122]
Click add, new entity window appears. Click an entitiy and Max either locks up and then crashes or crashes straight away. Tried various entities with the same result.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: System Product Name
Processor: AMD Ryzen 7 3700X 8-Core Processor              (16 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1660
Dedicated Memory: 5991 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1660
Dedicated Memory: 5991 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by plemsoft** [comment]
@andypmillard Thanks for reporting this issue, we had a crash with some models in the last version , this has been fixed in the latest version , so please give it another try when you get the next update, thanks :)

**Comment by rvanner** [comment]
@andypmillard Is this now fixed for you? I would like to close down this issue if it's now fixed.
