### ISSUE TITLE
invisible characters creator

### ISSUE THREAD

**Issue by sciencebloke50** [TheGameCreators/GameGuruRepo#1123]
character creator male only shows head female totally invisible and the zombie is ok

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MBB-36008
Processor: AMD Ryzen 5 3600 6-Core Processor               (12 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 970
Dedicated Memory: 4043 MB
Current Mode: 1680 x 1050 (32 bit) (59Hz)

**Comment by plemsoft** [comment]
@sciencebloke50 Thanks for reporting this issue, this has been fixed and will be in the next update :)
