### ISSUE TITLE
CC-only head shows v2021_04_30

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1125]
Only the head shows in CC, current version 2021_04_30.
Unable to upload here as Im using the inbuilt bug system.  Will add to  github shortly.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: TECRA Z40-A
Processor: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 CPUs), ~2.4GHz
Memory: 4096MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) HD Graphics Family
Dedicated Memory: 112 MB
Current Mode: 1366 x 768 (32 bit) (60Hz)

**Comment by redagent101** [comment]
![CC_GGMAX_v2021_04_30](https://user-images.githubusercontent.com/15969299/116852101-a3e09200-abeb-11eb-91eb-6d78b4675c85.png)

**Comment by redagent101** [comment]
still to double check on my PC which uses GeForce GTX 1060 (3GB).  Most likely will be same outcome.

**Comment by plemsoft** [comment]
@redagent101 This has been fixed and will be in the next update :)
