### ISSUE TITLE
Weapons and arms not on the screen

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#1126]
After the latest update, the weapons are no longer on screen while aimming or shooting , just the shadows. 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: ROG Zephyrus M15 GU502LW
Processor: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) UHD Graphics
Dedicated Memory: 128 MB
Current Mode: 1920 x 1080 (32 bit) (240Hz)
Card name: NVIDIA GeForce RTX 2070 with Max-Q Design
Dedicated Memory: 8031 MB
Current Mode: Unknown

**Comment by Granada1** [comment]
I can confirm that , also weapon zoom is reversed

**Comment by plemsoft** [comment]
@Hamada880 Thanks for reporting this issue, this has been fixed and will be in the next update :)
