### ISSUE TITLE
Editing Grouped Objects

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1129]
There's still some odd behaviour when editing grouped objects. 

See this video;
https://youtu.be/EYjI9094Avk

**Comment by plemsoft** [comment]
@rvanner It was fixed today , in this issue: https://github.com/TheGameCreators/GameGuruRepo/issues/1019 , ready from the next update :)

**Comment by rvanner** [comment]
OK, I'll check when I get the next build and then it fixed I'll close this off.
