### ISSUE TITLE
Skybos fogging line

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#113]
![snapshot100](https://user-images.githubusercontent.com/36561118/37145991-67fc4b34-22ba-11e8-97db-8cadb7cc6124.jpg)

Typo: should be skybox above in title.

In the image above there is a defined line in the sky when fogging is set to very low distance from player but with a high intensity, I am using Prebens shaders, so it maybe to do with the skybox fogging.

**Comment by Teabone3** [comment]
What skybox is that?

**Comment by tarkus1971** [comment]
red sky skybox, with fogging.

**Comment by plemsoft** [comment]
Just tried this using the red skybox , and i did not have this problem , i even tried with cartoon like you have.

What version of GG are you using and what shaders are you using ?
