### ISSUE TITLE
Turning Off the Flashlight Will Drop FPS for a split second. Causing a "stutter"

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1134]
Turning off the Flashlight will drop about 1 FPS then quickly recover. It is barely noticable but I could feel it freeze for that nano second when I was playing the cellar demo, thats how I even noticed this.

If you go to the cellar demo and spam your F key and look at the Profiler you will see the FPS begin to drop. I was able to get it to drop to about 41 by spamming the flashlight on and off. It also looks like the DrawCalls spike for a nano second everytime the flashlight is turned off, maybe that is what causes the fps to drop?

**Comment by Kitakazi** [comment]
This doesn't happen on a blank map, I noticed and tested it on the cellar demo.

**Comment by LeeBamberTGC** [comment]
I can reproduce this, thanks for the info.

**Comment by LeeBamberTGC** [comment]
Fixed for this Friday's update :)

**Comment by Kitakazi** [comment]
Seems fixed now. Thanks.
