### ISSUE TITLE
When moving an object around, the right window will move up and down when you click and let go of the object. 

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1135]
See this video and how the right panel keeps changing as I click and drag an object. Ideally the right panel will stay the same and not keep jumping up and down.

https://youtu.be/c_Is9gL48rA

**Comment by plemsoft** [comment]
Fixed :)

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
