### ISSUE TITLE
Pressing Right Click to aim with a weapon zooms out instead of zooming in.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1138]
Press right click with a weapon equiped to aim down the sights of your gun and you will be zoomed outward instead of inward.

FoV should get smaller not bigger. 

System Specs:
DXDIAG required!

**Comment by Kitakazi** [comment]
Any update on this issue being fixed? 
Not trying to be annoying but it's getting old trying to test combat with the AI and aim-down-sight making it harder to.. aim...

Whatever is suppose to control the zoom is somehow backwards. Might have to do with Max FoV settings being vertical while classic is horizontal? And this was not compensated for maybe?

**Comment by LeeBamberTGC** [comment]
Could you make a short video so we can see what you see, thanks!

**Comment by Kitakazi** [comment]
https://www.youtube.com/watch?v=ZqS7JUV0iF4
sure, here it is. I press right mouse button to ADS. What should happen: It should Zoom In / camera should magnify when aiming / FoV should become a lower value. W/e you want to call it. 

What actually happens, camera zooms out/ aiming get wider / FoV goes to a higher value. It is all backwards. 

In the video I put max then classic comparison. In Classic aiming your weapon correctly zooms in - In Max aiming the weapon Zooms out :(


This my theory about what is broke- which is very possible is 100% the wrong reason. But I dunno maybe it will help solve the issue so throwing it out there. 
I'm sure you know but Max is set to Vertical FoV which is a default of 60 and Classic is Horizontal FoV a default of 90. Lets say I have a FoV of 60 on Max, it's like Zoom-In code thinks my 60 FoV is a 90 FoV value, which would be correct if it was classic. still when you zoom in. So it always reduces the FoV by, lets say 10 in classic. But that is actually setting the FoV to 80 instead of 50 in Max. 

Like w/e the checks the player FoV and then reduces the FoV accordingly is off by about 20 numbers upward to many. 

But I could be totally wrong with that theory.

**Comment by Kitakazi** [comment]
Which is why on this guys issue 
https://github.com/TheGameCreators/GameGuruRepo/issues/1399
he can see the part of his RPG he isn't suppose to see. Cause the FoV is not getting set to a smaller value when he aims, it is getting bigger, one.

**Comment by Kitakazi** [comment]
I have made a band-aid fix for this issue. Editing the code in gameplayercontrol.lua I changed line 551 
which was originally 
trealfovdegree=GetGamePlayerStateCameraFovZoomed()*((GetGamePlayerStatePlrZoomIn()*GetFireModeSettingsSimpleZoom()))

I have changed to 
trealfovdegree=GetGamePlayerStateCameraFovZoomed()-2*((GetGamePlayerStatePlrZoomIn()*GetFireModeSettingsSimpleZoom()))

which all I did was add the -2 after GetGamePlayerStateCameraFovZoomed() 
here you can see in my screenshots the aiming now functions as one would expect... aiming the gun now zooms in, rather than zooming out. 
But there is def some other issue going on cause I don't think adding a -2 to that really makes sense cause looking at the code it should be zooming in with how it is now. Maybe some issue with what ever number is being returned from when it Gets the camerafov number. 

Here is screenshot comparison. 
![Desktop Screenshot 2021 11 05 - 23 38 10 71](https://user-images.githubusercontent.com/51464873/140598159-78274ef4-7353-4d73-82c3-8109903eff8f.png)

here is the original broken ADS
![Desktop Screenshot 2021 11 05 - 23 38 21 50](https://user-images.githubusercontent.com/51464873/140598187-c1b6ccdd-c108-4f13-ad71-1f6cd1610154.png)

and here is my bandaid fix that makes the ADS function as it should

![Desktop Screenshot 2021 11 05 - 23 42 16 96](https://user-images.githubusercontent.com/51464873/140598225-69d295b0-1833-4894-b0a1-438414288ce7.png)

**Comment by rvanner** [comment]
@LeeBamberTGC Worth sorting this now?

**Comment by LeeBamberTGC** [comment]
@Kitakazi Yes this was a silly one :)  Fixed next week's build!

**Comment by Kitakazi** [comment]
Cool, thank you.
