### ISSUE TITLE
GGMax 2021-05-07 Getting wrong entity name in "current objects" panel

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1143]
1- Copy/paste entity.2- Rename the new entity.

a- In the _current objects_ panel the name remains as the original one (please refer to the pic below).
b- Getting "indexing with nil value" LUA error, I guess because GGMax treating the new entity as Label_QR_07 rather than as Label_QR_12, due that the Label_QR_12 entity "does not exists", therefore their ID either exists, so, thrown nil value error.

PD: I'm getting entity IDs thru their names. There is no way to get entity names in the editor, in fact anywhere, atm, for that reason I've suggested a label with the entity ID, closest to the entity name.

Sorry, the internet connection failing. I'll try to upload the images asap.

**Comment by 3coms** [comment]
![GGmax_2021_05_07_wrong_entity_name_error_pic02](https://user-images.githubusercontent.com/47690174/117649885-55ee0000-b190-11eb-8db6-f4757e2f73a2.png)

**Comment by plemsoft** [comment]
@3coms Thanks for reporting this issue, i assume your using _init_name to store the entity name ? , i just tried to make a quick script that display the entityname and it looks like it work perfectly it display the correct name even after you change it ?

Please try the attached script:

Also could you post your script here, so im able to check what the problem is with your script, Thanks :)

[spinprompt.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7006511/spinprompt.zip)

**Comment by 3coms** [comment]
@plemsoft 
It has nothing to do with LUA, maybe I explained the wrong way.

I've tried a few minutes ago, and now the thing is different but curious, it is as follow:
1- Place the "Boiler - Unit" from Cellar over the empty map.
2- Make a copy (crtl+c/ctrl+v) now you have 2 "Boiler - Unit"
3- changed the name to differentiate them from each other. Change the copied mesh from "Boiler - Unit" to " Boiler - Unit_1"
4- Instantly both become "Boiler - Unit_1".
5- Make a 3º copy from the "Boiler - Unit_1" and name it "Boiler - Unit_2"
6- Instantly all they become "Boiler - Unit_2"

As you can see, has nothing to do with LUA, maybe LUA might be a consequence, but no the cause.

**Then, why I told about LUA?**
Because there is no way to know the entity ID in the editor (forget LUA), I not this most likely is temporary, but atm you need LUA to know the entity ID, and you need the entity name to know the entity ID, and 50 items name the same doesn't help either.

As you can see, I'm using stock mesh so you can easily replicate the bug (if any)

**Note:** From far ago there is another easiest way to know the entity name via LUA: **GetEntityName(e)** the issue with that command among others, is that it is not documented on Global var, so, no many people know it exists.

Curious eh?

**Comment by plemsoft** [comment]
@3coms Found it, yes it was a bug and it has now been fixed , thanks for your help :)

**Comment by 3coms** [comment]
Glad to help. Wait next update to confirm it. :)

**Comment by plemsoft** [comment]
@3coms FYI: It will not be in todays release, perhaps first in the Friday build :)

**Comment by 3coms** [comment]
@plemsoft 
I am not worried about this, I have the Robinson Crusoe book. LOL
