### ISSUE TITLE
Catagories error

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1144]
Catagory selection doesnt seem to work 
Add item
Select the dropdown for Catagories Ticking or unticking them seems to change nothing ?

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MS-7C02
Processor: AMD Ryzen 5 2600X Six-Core Processor            (12 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: Radeon RX 580 Series
Dedicated Memory: 8171 MB
Current Mode: 1920 x 1080 (32 bit) (59Hz)

**Comment by rvanner** [comment]
@synchromesh62 Is this an issue for you still or can this be closed off as it's old?

**Comment by plemsoft** [comment]
@synchromesh62 The dropdown was replaced, do the new one work for you ? :)

**Comment by synchromesh62** [comment]
OMG this ones old .. Yes of course as you say this was replaced and no longer a valid issue .
I will close it ..
