### ISSUE TITLE
User reports he cannot use MAX after recent update

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1145]
_This report came in via the tech support;_

Enjoying the UPDATES, but the latest one made it impossible to do anything, the 3d view of my entities causes the engine to crash, system info: Device name TARDIS Processor Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz 2.71 GHz Installed RAM 32.0 GB Device ID 792994C5-8395-4D67-8944-35493547E4D8 Product ID 00325-80590-25948-AAOEM System type 64-bit operating system, x64-based processor Pen and touch No pen or touch input is available for this display gpu: radoen 200 series, 4 gig. gone back to using a previous build that allows me to actually use my assets (reason its a issue is I'VE literally SPENT loads and loads and loads in the store) and i just can't use any thing. also, I was using max to import some of my own models and then exporting them to classic and this was great for world building until the latest update, now it wont allow the exports to open in classic, where as before it did with no issues. this version just seams like a set back, the entity menu is difficult to navigate unlike classic, the having to click on a separate screen and then another screen to import things is a little bit annoying, where one click in was PERFECT. feels like the engines taken a HUGE step back and Can't do anything with it at all now, which is a shame because been really enjoying it!! all the best, hope your well.

**Comment by LeeBamberTGC** [comment]
Could you tell me the full model name of your GPU card, thanks!

Also, we have added to the DBO format for MAX, so DBOs created in MAX will not be backwards compatible to GameGuru Classic, and is not something we anticipate supporting. We certainly support going from Classic to MAX, but not the other way around.

Also for quick access to importer, just use CTRL+I to instantly go into the Model Importer.

**Comment by rvanner** [comment]
I have messaged the customer to see if this is an issue for him still.
