### ISSUE TITLE
saved level not saving default grass terrian

### ISSUE THREAD

**Issue by rustynuts121** [TheGameCreators/GameGuruRepo#1147]
I started to  create my jungle competition and as Lee suggested I enabled the default grass terrian. But after working on it for a while I saved it and then came back to continue, but upon reloading the level, the grass texture has gone and it has defaulted back to the grey and white squares. 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Shadow Computer
Processor: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz (8 CPUs), ~2.5GHz
Memory: 12288MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1080
Dedicated Memory: 8079 MB
Current Mode: 1920 x 1080 (32 bit) (59Hz)

**Comment by Ratall** [comment]
[https://github.com/TheGameCreators/GameGuruRepo/issues/1151](url)

**Comment by rustynuts121** [comment]
This issue has been fixed for me in the latest build.
