### ISSUE TITLE
Standalone Issue with Default Character Speed.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1148]
I have a 2 level game I have been working on for some time now. Individually both levels work. When making a standalone with both however, causes issues. The player speed and other values are not affected by the levels settings. So on level 2 my player speed is the same as level 1. However, I needed to alter the players scale in level 2 and hence the players speed and jump height etc. to match. So I now have Sonic speed in level 2 which is not exactly what I want :)

Workarounds "may" be possible but this should be working out the box!
https://vimeo.com/548551678
Shows the crazy speed on level 2.

Edit - Oh This is in 3rd Person BTW, although the video probably made that obvious!

**Comment by plemsoft** [comment]
@Retrogamebloke Thanks for reporting this issue, this has been fixed and will be in the next update :)
