### ISSUE TITLE
GGMax 2021 05 14 wierd behavior

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1149]
GGMax_2021_05_07
Runing a level that works fine in  preview version, now suddenly do so, please, refer to the video, it shows better the bug.
It happens to me today again with a different map, and this time is like a light flickering around the mesh (building), is like Z-clash effect, not the case, since those geometry are clean geometry.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by 3coms** [comment]
YT video link

https://youtu.be/2DTWcxEURUE

**Comment by 3coms** [comment]
![GGmax_2021_05_07_weird_behavior_pic01](https://user-images.githubusercontent.com/47690174/118169703-8a301d80-b429-11eb-940d-ce5aef905b7e.png)

**Comment by rvanner** [comment]
@3coms Is this still an issue or a very old one that's now fixed?

**Comment by 3coms** [comment]
OK, it is worse than that.

**What I did and what I've got.**

1- Open map1, and this is what I've got:

![Robot_clerk_tes1_map_GGMax_2021_08_06_pic01](https://user-images.githubusercontent.com/47690174/129386267-c18ee9e5-2f12-4bf0-9092-09921029fb1a.png)

2- Open a backup, and I've go this one:

![Robot_clerk_Backup_map_GGMax_2021_08_06_pic01](https://user-images.githubusercontent.com/47690174/129386439-c5df5c3a-e2e6-4972-9f91-5de13d60526a.png)

3- Then I tried with a new map, and I've got this one:

![GGMax_2021_08_06_New_Map_pic01](https://user-images.githubusercontent.com/47690174/129386562-869d682a-348a-4f14-a6fb-7001aa1ce419.png)

4- Then I've close GGMax and re-open it, this time I open a new map and place the warehouse there, and this time it works fine.

**Conclusion**
The only way I see to test this one is to recreate again the whole map from scratch, and this going to takes some time, so, maybe at the weekend I can do it.

**Comment by 3coms** [comment]
![Robot_clerk_Warehouse_NewMap_GGMax_2021_08_06_pic01](https://user-images.githubusercontent.com/47690174/129387208-43875156-f7ab-4621-a1f5-803fb8fa8a54.png)

So, this shows that the model has nothing to do. :)

**Comment by rvanner** [comment]
Hi, are you saying there's not an issue now? If there is an issue, can you zip up the level and send it?

**Comment by 3coms** [comment]
Solved
