### ISSUE TITLE
Models with single .png texture problem (Solved)

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#115]
If a model has a single .png texture instead of N D S textures it gets textures from other models superimposed on it.
![gg2](https://user-images.githubusercontent.com/36109432/37245466-28630116-2490-11e8-8f86-01e373514e15.png)

**Comment by Pirate-Myke** [comment]
What is your texture size?

**Comment by BodRH** [comment]
Both models in this picture are 2048 x 2048 but it happens with all models with a single .png texture no matter what size they are, it was first noticed on a dynamic glass model which was 512 x 512 but after a lot of investigating it is every single .png textured model I ever made.

**Comment by Pirate-Myke** [comment]
Ok. I will have a play at this also.

**Comment by BodRH** [comment]
In the screenshot I made PBR textures for the pick up and it is the _gloss and metalness textures causing the problem as the sky is being reflected on the carpark floor but it also happens with N D and S textured models, it looks like the N texture is superimposed on the .png textured models.

**Comment by Pirate-Myke** [comment]
Can you email me the media you used in the image above? Myke1net@hotmail.com
I can't make it do this with anything I have.

**Comment by BodRH** [comment]
The carpark is in my free models and media thread on this page https://forum.game-guru.com/thread/215012?page=13, I put the pick up in the level first and then put the top level of the carpark down and moved the pick up onto it, it doesn't only happen to me though, the only reason I tried the PP again was because of the PM's I was getting about this happening with other models, the first one was with the Mallard train I made, it is projecting it's N texture onto the original small apartment I made on this page of the thread https://forum.game-guru.com/thread/215012?page=2, I tried it myself and you can see the _normal texture on the roof ( it's also on the walls inside and out), it also made the apartment shiny for me because I have now made PBR textures for the Mallard, the Mallard models in my free models thread use N D and S and still project the N texture onto the model. I have uploaded the PBR textured pick up to the last page of the thread so you can download the carpark and the pickup. 
![shigg](https://user-images.githubusercontent.com/36109432/37252152-6cad97bc-2514-11e8-8916-63cd23083a3b.jpg)

**Comment by Pirate-Myke** [comment]
Yes, having the texture name without any extension seems to be causing the projection of normal map on other object issues.
I gave your .png single texture the _D extension and the normal being projected to other object went away on all your objects I tested.

**Comment by BodRH** [comment]
Thanks Myke, at least it's an easier fix than making a whole set of new textures for each model with a single .png texture, I will go through the models in the thread and alter the single .png uploads so the textures have  _D in the name and alter the fpe's to suit.
Thanks again.

**Comment by Pirate-Myke** [comment]
Your welcome.

**Comment by plemsoft** [comment]
I will also fix it in the code so it will work without renaming to _d , for the next version :)

**Comment by BodRH** [comment]
I've already started changing the models in my thread as I got fed up of getting PM's moaning about them, I'm up to page 5 of 15 but not all of them use single .png textures so I will carry on.

**Comment by BodRH** [comment]
I just tried today's PP version and it still does the same with single .png textures with no _D extension.

**Comment by plemsoft** [comment]
Hi Bod,
It will be in the next PP version if my branch with bug fixes are approved :)

**Comment by BodRH** [comment]
OK, thanks Preben.
