### ISSUE TITLE
2021.05.14 - Emissive lighting strength on *some* entities that had a value of 1 is now 64

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1150]
Loaded up a level i'm working on and noticed alot of my assets that had emissive lights with a value of 1 now have a value of 64. It didn't happen to every entity though, as you can see in the screenshot the lights on the ceiling didn't change but all the other lights in the scene did change to 64 value by themselves. 

Not sure if this was intended with a change to emissive lights or if a bug. 
![emissive](https://user-images.githubusercontent.com/51464873/118227726-a6928100-b44e-11eb-84a3-7280c290b427.png)

**Comment by Kitakazi** [comment]
hmmm with the latest update now none of my assets in the scene are showing their emissive lights.

**Comment by LeeBamberTGC** [comment]
Are you able to go into your object properties and set the emissive color and strength, the save the level and reload, and see the change has been saved?

It is worth noting that any previous levels you may have created with the dev build are all subject to bring invalidated as we develop the software, so best not to create anything too massive, only test levels to help you work with the builds (at least at this stage).

**Comment by Kitakazi** [comment]
Hi, yea I can go into the object properties and set the emissive color and strength back to how I need it just fine. And yea I just test Max usually using some classic FPMs I made so they are only test levels. :) 

Which I think the issue I've been having with emissive lights are only on objects that have classic FPE settings. I need to test some more but if I import the DBO and set the textures and then save it the same name and overwrite it, it seemed to fix the issue. But my classic levels have a TON of entities with emissive lights and having to do that would be alot of time. No big deal though.

**Comment by LeeBamberTGC** [comment]
@Kitakazi I have marked this as a feature, which would involve a feature of the legacy FPM level/entity conversation which checks all objects with lively emissive properties and configures the new MAX objects so they appear as expected when viewed.

**Comment by Kitakazi** [comment]
I believe this bug has been fixed, I have not encountered it. Closing.
