### ISSUE TITLE
Creating a new level with grass ticked on, then reloading it later reverts to "grid" terrain

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#1151]
Was making a map for jungle comp, but I had to shut down GG Max due to previously reported issue of "editor progressively slowing down over time" Reloaded map to continue work, but now the terrain texture has swapped to the default white grid texture.

**Comment by cstriage13** [comment]
Have this same issue
![Screenshot 2021-05-14 050138](https://user-images.githubusercontent.com/84180614/118255983-8e345d80-b472-11eb-8f25-bde45cca78a3.png)

**Comment by Ratall** [comment]
[https://github.com/TheGameCreators/GameGuruRepo/issues/1147](url)

**Comment by synchromesh62** [comment]
This was fixed in the latest update friday.
Can you try loading the map in again ?

**Comment by cstriage13** [comment]
Done that now everything paints in the squares and is not as a regular
paint brush or it goes to a very low res render of the texture and fills
whole square.

**Comment by cstriage13** [comment]
Here is the screen shot.
![today](https://user-images.githubusercontent.com/84180614/118376369-350d1c80-b58d-11eb-81f4-5efba32b1a33.png)

**Comment by cstriage13** [comment]
I do not believe it is my specs. Its a two year old computer but its a work horse I have no problems at all using blender or 3ds max etc. 
![pc](https://user-images.githubusercontent.com/84180614/118376579-66d2b300-b58e-11eb-821e-9d044e17d1c7.png)

**Comment by rvanner** [comment]
This will be fixed when the new terrain system replaces this old slow one.

**Comment by rvanner** [comment]
Closing this because the new terrain system will sort all of this.
