### ISSUE TITLE
Update did not work, uninstalled and downloaded it again but installing again does not work

### ISSUE THREAD

**Issue by Bollehopp** [TheGameCreators/GameGuruRepo#1154]
`![image](https://user-images.githubusercontent.com/78963280/119241204-a2501d00-bb4c-11eb-86ad-9753356864ed.png)

This error keeps happening each time I try to reinstall Max again. After last Fridays update which never worked I have tried to reinstall max but without success. Basically I press "Ok" It comes back to this window saying error files missing and blablabla.. Its almost in an eternal bug loop of not downloading max.

**Comment by rvanner** [comment]
Closing this now. There's a much newer Tiny Installer, please try that and report if you have any issues.
