### ISSUE TITLE
(GG Classic) Terrain Textures: Specular maps not working?

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#1155]
I wanted to ask if terrain textures are working properly in gg classic ?
Because adding a specular map to the texture set doesnt do anything.

Or maybe I am missing something ?

**Comment by rvanner** [comment]
You should ignore the current terrain system. There's a brand new one in development, so wait for that one.

**Comment by Duchenkuke** [comment]
riiick! not for max for CLASSIC ? :D

**Comment by rvanner** [comment]
Sorry! I have re-opened the issue and will assign labels to it.

**Comment by Duchenkuke** [comment]
okay thank you :)

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this issue, You need to put your specular map into the alpha channel of your color (diffuse) texture. Then it will work :)

**Comment by Duchenkuke** [comment]
yea I saw the thread that mentions it yesterday..
Could you possibly send me a sample?
Because the ones I tried did actually not work. 
I have made the diffues texture half transparend and had the specular texture underneath it.. but I guess that is wrong ?

**Comment by plemsoft** [comment]
@Duchenkuke You can try "\Files\terrainbank\ice\Texture_D.dds" it has specular in the alpha channel.

![diffuse-alpha](https://user-images.githubusercontent.com/18662417/119324236-e728a080-bc7f-11eb-83ef-e5326f18ee19.jpg)

**Comment by Duchenkuke** [comment]
oh waiitt, so I have to assign it there!? 

ookay ! Thanks! I will try and see

**Comment by plemsoft** [comment]
@Duchenkuke You can set it per texture like "Path_D.dds" but then you need to re-bake the super texture, you do that be selecting the texture again in the palette and it will create a new super texture :) , you can check in the super palette "Texture_D.dds" if it has been baked.

**Comment by Duchenkuke** [comment]
okay thanks for the info, I will try it!

**Comment by GraPhiX-Guru** [comment]
Hi Preben, i have packed the specular into the alpha channel of the D texture, tried 32 bit PNG and BC3(DXT5) but the global slider has no effect, is there something else required ?

**Comment by plemsoft** [comment]
@GraPhiX-Guru Ups yes sorry, you need to comment out this line in settings.fx "#define NOTERRAINSPECULAR" and recompile the shaders. Looks like terrain specular has not been on by default for some years :)

**Comment by GraPhiX-Guru** [comment]
thank you re compiling now :)

**Comment by GraPhiX-Guru** [comment]
not sure whats going on but i made the change you suggested no joy but GG gave quite a few errors
![error1](https://user-images.githubusercontent.com/35724756/119344900-2363fd00-bc90-11eb-9e2a-465af993a65b.png)
![error2](https://user-images.githubusercontent.com/35724756/119344906-25c65700-bc90-11eb-9e31-687abac590a6.png)
![error3](https://user-images.githubusercontent.com/35724756/119344913-27901a80-bc90-11eb-9c6d-6bf74c2d0568.png)
![error4](https://user-images.githubusercontent.com/35724756/119344919-2959de00-bc90-11eb-822d-63911403ba37.png)
![error5](https://user-images.githubusercontent.com/35724756/119344923-2a8b0b00-bc90-11eb-9bea-eaaa3f301c71.png)

slider still as no effect not sure if i can post settings.fx and settings.blob here but this line i changed and commented out

//#define NOTERRAINSPECULAR // Ignores the W component of the terrain diffuse/albedo texture for zero specular effect

**Comment by GraPhiX-Guru** [comment]
should these lines be enabled?

//#define SPECULARCAMERA
//#define SPECULARCAMERAINTENSITY (0.4)

**Comment by Duchenkuke** [comment]
I can confirm that "#define NOTERRAINSPECULAR" doesnt change when recompiling.

I have disabled it and the terrain still looks the same. 
It would be awesome if this could be adressed

**Comment by plemsoft** [comment]
@Duchenkuke @GraPhiX-Guru As i remember this was fixed on discord ?

**Comment by Duchenkuke** [comment]
Yes but it should be in the public build

**Comment by plemsoft** [comment]
@Duchenkuke Checked and the fix should be fine to add, will add it to the preview for now, thanks :)
