### ISSUE TITLE
Object Library does not remember user settings

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1158]
If you leave MAX and re-load it, the Object Library reverts back to the default settings. 
I like to make it full screen and choose scenery items only as a default start. 
Please make it remember how it's setup

**Comment by plemsoft** [comment]
Fixed: Now restore , last search , filter settings, maximize state and columns settings :)

**Comment by rvanner** [comment]
Fixed in latest version. Closing this issue. 
Thanks for this @plemsoft , it makes a big difference! 👍
