### ISSUE TITLE
Object Importer Does Not Export _color Alpha Gradient

### ISSUE THREAD

**Issue by Kasseyus** [TheGameCreators/GameGuruRepo#1160]
When Importing Object into MAX, the Alpha Clipping setting is not reflected in the final FPE.

e.g..
;visualinfo
textured         = 
baseColorMap0    = Texture_color.dds
alphaRef0        = 0.85  <----  This line is missing!

**Comment by Kasseyus** [comment]
Seems to be working now.

**Comment by Kasseyus** [comment]
Issue can be reproduced on object with only 1 texture.  Objects with multiple textures seem to be OK.

**Comment by Kasseyus** [comment]
Example from FPE files directly after Import....

;visualinfo
textured         = 
baseColorMap0    = acacia trunk_color.png
alphaRef0        = 1.00
normalMap0       = acacia trunk_normal.png
normalStrength0  = 1.00
surfaceMap0      = acacia trunk_surface.dds
roughnessStrength0= 1.00
metalnessStrength0= 1.00
transparency0    = 0
renderorderbias0 = 0.00
reflectance0     = 0.00
basecolor0       = 4294967295
emissivecolor0   = 0
baseColorMap1    = acacia leaf_color.png
alphaRef1        = 0.88
normalMap1       = acacia leaf_normal.png
normalStrength1  = 1.00
surfaceMap1      = acacia leaf_surface.dds


;visualinfo
textured         = Scrub Bush_color.dds
baseColorMap     = Scrub Bush_color.dds
normalMap        = Scrub Bush_normal.dds
normalStrength   = 1.00
surfaceMap       = Scrub Bush_surface.dds

**Comment by LeeBamberTGC** [comment]
@Kasseyus Fixed in latest build:

;visualinfo
textured         = music.png
baseColorMap     = music.png
alpharef         = 0.44
transparency     = 0
renderorderbias  = 0.00
reflectance      = 0.04
basecolor        = 4294967295
emissivecolor    = 0
textureref1       = music.png
effect           = effectbank\reloaded\apbr_basic.fx
