### ISSUE TITLE
Static Thumbnail Does Not Update When FPE Thumbnail Settings Change

### ISSUE THREAD

**Issue by Kasseyus** [TheGameCreators/GameGuruRepo#1161]
The static image that represents the thumbnail does not update when the FPE settings that determine zoom, rotation, etc are changed.  

It will remember the last time the thumbnail was saved on the users machine via 'Update Settings', but if that altered FPE is distributed to other users computers, they appear to have the old static thumb.  

The thumbnail will use the newer settings when hovered over for the animating spin, but revert to the old image when de-hovered.

**Comment by Kasseyus** [comment]
As of build 2021-5-28 a good example is the 'Large Industrial Dumpster'

**Comment by plemsoft** [comment]
@Kasseyus Thanks for reporting this issue, you need to double click the thumb and use the "Update Thumbnail" button :)
