### ISSUE TITLE
Entity Loads In With BLACKED OUT Texture Due to BASE COLOUR.  

### ISSUE THREAD

**Issue by Kasseyus** [TheGameCreators/GameGuruRepo#1163]
Entity loads in with Pure Black Base Colour, making the textures appear also black.   Can be fixed my manually changing base colour in engine, but not ideal.

AFAIK, nothing in the FPE is causing this as DBO file can be replaced with a known working asset and renders normally (provided).

[Basement Stairs - Full.zip](https://github.com/TheGameCreators/GameGuruRepo/files/6554339/Basement.Stairs.-.Full.zip)

**Comment by GraPhiX-Guru** [comment]
this line in fpe causes the issue i am currently creating an RGBA-INT32 converter so that we can but the colour in the fpe
basecolor        = 4294967295

**Comment by Kasseyus** [comment]
It thought that too, but deleting that line has no effect on the issue.  I think it may be related to the model file as replacing the DBO with another file known to work correctly...  works correctly.

The only way I've been able to get it to import correctly is to remove all MAX references in the FPE file in relation to advanced textures.. i.e..  Just the _color and the shader.

**Comment by GraPhiX-Guru** [comment]
i am having issues getting the RGBA to INT32 but i will work it out :)
![int32](https://user-images.githubusercontent.com/35724756/119853566-3a148900-bf08-11eb-8ac6-5bf289f1bfe3.png)

An interesting point to make is that regardless of the character length of the Int32, the byte count will always be the same. This is why the 32 bit number 1 can still represent a color that contains 4 values. This can be deceptive to people at first glance, but I assure you that even the 32 bit number 0 represents a color(Black) so not sure why the basecolor defaults to black.

**Comment by plemsoft** [comment]
@Kasseyus I remember this was fixed some time ago, could you give it another try in the latest build and let me know if this is still a issue , and close it of ok , Thanks for your help :)
