### ISSUE TITLE
FBX faulty

### ISSUE THREAD

**Issue by sciencebloke50** [TheGameCreators/GameGuruRepo#1168]
the head on the FBX model is not working fully and it is an imported model and on sale so i have been informed by Lee B to put up the FBX model to work on

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MBB-36008
Processor: AMD Ryzen 5 3600 6-Core Processor               (12 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 970
Dedicated Memory: 4043 MB
Current Mode: 1680 x 1050 (32 bit) (59Hz)

**Comment by rvanner** [comment]
@sciencebloke50 Can you zip up and send the model so we can test it?

**Comment by sciencebloke50** [comment]
Hi Richard
No problem will send in a short while today
Many thanks
________________________________

**Comment by sciencebloke50** [comment]
lee stephenson45 has shared a OneDrive file with you. To view it, click the link below.
<https://1drv.ms/u/s!AisI7wQGNVm2ggZL8ziCJYYM00d0>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://1drv.ms/u/s!AisI7wQGNVm2ggZL8ziCJYYM00d0>
FBX weeper model.zip<https://1drv.ms/u/s!AisI7wQGNVm2ggZL8ziCJYYM00d0>

good morning Rick,

please find attached the FBX model

________________________________

**Comment by LeeBamberTGC** [comment]
@sciencebloke50 Alas "This item might not exist or is no longer available". If it persists in the latest EXP build, please post the new model zip here and I will reopen this one and look closer. Much work on FBX importing since May last year :)
