### ISSUE TITLE
MAX - Grass Vegetation system is broken

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#1172]
Try to add grass - you get tight spirals of
green or brown -- No grass 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: All Series
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1600 x 1200 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1920 x 1080 (32 bit) (75Hz)

**Comment by thor49** [comment]
Also load up old saved level and grass has turned into tight spirals of brown or green spaced out across terrain..

**Comment by synchromesh62** [comment]
Best to ignore the terrain system right now.
Its being completely replaced

**Comment by cstriage13** [comment]
I was going to say the same thing. But here's a screen shot anyways. 
![Screenshot 2021-06-06 025242](https://user-images.githubusercontent.com/84180614/120917262-e3c7e880-c673-11eb-80e9-e465940b03ea.png)

**Comment by rvanner** [comment]
@LeeBamberTGC Can you fix this ASAP! We still need the legacy grass system working.

**Comment by LeeBamberTGC** [comment]
Will be fixed for this Friday build.

**Comment by rvanner** [comment]
Closing this now.
