### ISSUE TITLE
Duplicating meshes bug - GGMax 2021_05_28

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1173]
1- Copy mesh name from mesh A.
2- Paste name in "ifUsed "  slot of the mesh B.
3- The mesh B is being duplicate, as result of press CTRL V, in order to paste the Mesh A name, in the ifUsed slot of the Mesh B.
Adding some vid showing the bug.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by 3coms** [comment]
https://youtu.be/kzz72ltaonA

**Comment by plemsoft** [comment]
@3coms As i remember i already fixed this, could you try it in the latest and close this issue, if its not a problem anymore , Thanks for your help :)

**Comment by 3coms** [comment]
Fixed and close, thanks. :)
