### ISSUE TITLE
Feature Request - "alttexture ="

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1176]
Hello, I'm requesting the feature of having an FPE option for having an alternative texture that can be called with LUA. 
alttexture = x
FPSCreator had this and it was really good. 
Here are some of the uses off the top of my head.

Having a model with a light on it, you can set the alttexture to so that when the player switches off the light, the light changes to the off texture. and then you can switch the light back on and it displays the bright on texture.

Panels ingame that a player uses. For example the panel in a game might have it's standard texture that says "Locked" when the player unlocks the door or w/e the panels alttexture would be "Unlocked." 

Having a "bloody" alttexture for enemies, when they die the alttexture is called and now they look like they are dead and bloody.

These are just some quick examples I thought of, but it really was so helpful in FPSC Im suprised GGClassic never had this feature.

**Comment by fearlesswee** [comment]
I agree, it would also be incredibly useful to be able to define numerous alttextures, in such a way like:
-alttexture1 =
-altexture2 = 
-altexture3 = 

and so on.

Use cases for numerous alt-textures over having just one:

- Different textures depending on HOW the enemy died, such as switching to a crispy blackened texture if they burnt to death, a texture that only has blood on the head if they got headshotted, a texture that only has blood on the torso if they got shot in the chest, etc.
- A TV that can randomly display still images
- A pseudo gif/animated texture (Each alt texture would be a frame of animation, and a script would cycle through them in order)
- Having a car that the player can customize the color of in-game

**Comment by LeeBamberTGC** [comment]
LINKED ISSUES:
https://github.com/TheGameCreators/GameGuruRepo/issues/3142
https://github.com/TheGameCreators/GameGuruRepo/issues/3050
https://github.com/TheGameCreators/GameGuruRepo/issues/2948
https://github.com/TheGameCreators/GameGuruRepo/issues/2554
https://github.com/TheGameCreators/GameGuruRepo/issues/1176

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Thanks for adding this in. 
However, would it be possible to allow us to change the emissive textures? I think alot of uses for switching textures would be for specifically emissive textures. Computer screens, lights, panels, etc.
