### ISSUE TITLE
Having no lights in a scene and setting all environmental lights to black, there is still some sort of ambient light 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1178]
With no lights in a scene and lighting settings all set to black it is still far to bright. 
Here is a screenshot from the cellar demo, I have set all environmental lights to black, and deleted all the light entities in the scene. Auto-Exposure is turned off and gamma set below the default to 2.0,

The screenshot is dark but it is not dark enough, as you can see something is lighting up the walls and the table, but how is that possible if there is no light in the scene?

![notdarkenough](https://user-images.githubusercontent.com/51464873/120454018-224e6200-c359-11eb-9606-1ffb2ae25485.png)

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue, the additional light is coming from the environment probe that are placed outside, if you do not setup your own probes where they are needed, it will use the general probe. So to fix your issue select the "Simulated Sky" and set all the colors to "black", or use a black skybox.

At some point we might add more features to control the probes or disable them, but until then you can use the above.

Hope this helps :)

**Comment by Kitakazi** [comment]
I see, That makes sense. Thanks for the reply.
