### ISSUE TITLE
DYNAMIC Entities do not use Position and Rotation Offset Values from Import

### ISSUE THREAD

**Issue by Kasseyus** [TheGameCreators/GameGuruRepo#1180]
When importing new entities, can set the POSITION and ROTATION Offset to correct orientation issues.

for STATIC flagged entities, this works as intended.

for DYNAMIC (non-STATIC flagged) entities, these values are ignored.

NOTE: This is not apparent in the Editor Window, which appears normal.  Issue occurs when running Test Game.

**Comment by LeeBamberTGC** [comment]
@Kasseyus In latest build, both static and dynamic creations produce correct results when positioned and rotated:

![image](https://user-images.githubusercontent.com/35840583/155129995-1cf457c4-35ec-4f81-9d06-92d109fc3b04.png)

As you can see, static holds its position high up and slightly rotated in its chosen BOX collision shape.

Dyanamic also holds its rotation within its BOX collision shape, and the positional shift was countered by the box physics and the mesh pulled to the terrain floor.

**Comment by ZakJudges** [comment]
Works in latest build
