### ISSUE TITLE
When editing custom materials clicking the thumbnail of a texture then selecting a new texture will change the wrong texture input.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1182]
For example, pick any model and go to the Edit Custom Materials tab in  Object Tools, click the actual Thumbnail of the Albedo texture, it will open up your documents to select a new one, then click any new image you want to use and it will change the texture for the Normal map instead of the Albedo. 

System Specs:
DXDIAG required!

**Comment by rvanner** [comment]
@Kitakazi Can you check this in the latest build this weekend and confirm this is fixed for you?

**Comment by Kitakazi** [comment]
Just tested. It is fixed.

**Comment by rvanner** [comment]
Great! Closing this down now.

**Comment by rvanner** [comment]
Ha! I see you already closed it :-)
