### ISSUE TITLE
Importer Creates Redundant _surface Files?

### ISSUE THREAD

**Issue by Kasseyus** [TheGameCreators/GameGuruRepo#1184]
When Importing Entity, e.g.   "Object.FBX" and "Object_color.dds", "Object_normal.dds" and "Object_surface.dds" exist in same directory.

Entity will import, and graphical information is automatically filled in, except it will also create a redundant surface file called "Object_color_surface.dds", which is a blank file and will ignore the existing surface file.

Demo Video Link: 
https://youtu.be/-4WbYqf4nf8

**Comment by ZakJudges** [comment]
Hi @Kasseyus 
Are you still experiencing this bug in the latest build?

**Comment by ZakJudges** [comment]
Importer now cleans up any surface files generated
