### ISSUE TITLE
Slipts in the land

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#1186]
While make a small hiilly field the lad start to spilts away sowing the water 

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: X570 UD
Processor: AMD Ryzen 7 2700 Eight-Core Processor           (16 CPUs), ~3.2GHz
Memory: 32768MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2060
Dedicated Memory: 5967 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by rvanner** [comment]
@Snage62 Is this GGMAX? If so, this will all go away when we are ready to release the new terrain engine

**Comment by rvanner** [comment]
Closing this because the new terrain system replaces this.
