### ISSUE TITLE
Placing Objects high in the sky with simulated sky on will always show in front of the clouds. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1189]
With the simulated sky on, if you place an object very high into the sky the clouds will always appear to move behind the object, even when it looks like they should be moving well below/in front of the object.

**Comment by rvanner** [comment]
@PaulSJ Is this something that can be fixed or is it just the draw order of how the clouds render?

**Comment by PaulSJ** [comment]
Not a problem in the latest version
