### ISSUE TITLE
GGC Issue: Widget Odd Behavior

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1190]
When rotating objects, they widget will now become wonky and rotate as well and get its rings stuck at odd perspectives.
![widget](https://user-images.githubusercontent.com/35990109/121450690-381be280-c96a-11eb-9afb-8e999a81c211.JPG)

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, i was not able to reproduce this, could you make a small video to show the issue or give me a step by step to reproduce it, also let me know if this is in the latest version , thanks for your help :)
