### ISSUE TITLE
GGC Issue: Magnify Glass Icons when in Freeflight Mode Do Nothing

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1191]
This may have been intentional, but the magnify glass icons in the editor UI do nothing if you leave top-down mode (G).

Basically they do not work while you are in free-flight mode. However mouse wheel for zooming in and out does work.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed and will be included in the next update :)
