### ISSUE TITLE
Welcome screen missing close/cancel button

### ISSUE THREAD

**Issue by renegms** [TheGameCreators/GameGuruRepo#1194]
When I open the Welcome screen again in the menu, there is no close or cancel button. It is missing. Our I don't see it where it is hiding.

**Comment by rvanner** [comment]
@renegms You just click Create a new game. But I do see the issue here. It should have a close X button if you don't want to do anything.

**Comment by rvanner** [comment]
We have since added a back button.

![image](https://user-images.githubusercontent.com/1503593/129360614-46e46203-3c08-498a-81d3-1beaffbb80db.png)
