### ISSUE TITLE
;orientation not in import file

### ISSUE THREAD

**Issue by GrobyKen** [TheGameCreators/GameGuruRepo#1195]
Now it could be me but the new version of GG loaded on to my kit today does not write the ';orientation' group in to the fpe file when using the import model system. I am importing fbx models.

**Comment by rvanner** [comment]
@GrobyKen Is this Classic or Max?

**Comment by GrobyKen** [comment]
Sorry. Classic.

**Comment by plemsoft** [comment]
@GrobyKen Thanks for reporting this issue, this has been fixed and will be included in the next update :)
