### ISSUE TITLE
Player Character has slow movement, weapon movement animations sped up, physics system is weird

### ISSUE THREAD

**Issue by Rhett-R** [TheGameCreators/GameGuruRepo#1196]
The movement speed for the character has been reduced significantly and/or the weapon animations when moving have been sped up. The brass ejects very slowly as if the force of gravity has been reduced, among other physics issues. You can see a video of what is happening [here](https://youtu.be/05eC8E3p4Gw).

**Comment by plemsoft** [comment]
@Rhett-R Thanks for reporting this issue, could you let me know the FPS when you play the game in the video, there is some code that will reduce the physics if your fps get to low, so i will need the FPS your seeing so im able to adjust this. Just press F11 to see the fps. Thanks for your help :)

**Comment by plemsoft** [comment]
@Rhett-R I Improved this system and should be better from the next update, give it and test after the next update and let me know how it goes :)

**Comment by Rhett-R** [comment]
Hi @plemsoft,
Thanks, will test it as soon as it comes out. :)
Also, sorry for not providing the previously required information. I don't check GitHub often.

**Comment by rvanner** [comment]
@Rhett-R Is this now fixed for you?

**Comment by Rhett-R** [comment]
@rvanner Seems for the most part to be working alright. I validated the GG files from Steam as well. However, a new bug seems to have presented itself where if your health drops to a negative value you don't actually die per se (the red screen appears but the actual death is not executed).
![image](https://user-images.githubusercontent.com/65373855/132155517-ed5bd6e3-8c56-4094-a537-cd2e2c9478b7.png)

**Comment by rvanner** [comment]
@Rhett-R Could you post that issue as a new issue please? I will close this one down now.
