### ISSUE TITLE
WASD, Not working

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#1197]
Made a section of my dungeon with Max and the A and D keys did not work, allthe puddle disappears, the the dungeon start to split.

Any help will be greatly recived.
Nigel.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: X570 UD
Processor: AMD Ryzen 7 2700 Eight-Core Processor           (16 CPUs), ~3.2GHz
Memory: 32768MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2060
Dedicated Memory: 5967 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by rvanner** [comment]
@Snage62 Do you mean in the editor or when you are testing the game?

**Comment by Snage62** [comment]
Hi Richard. 
Its wben i test the game, I ve send. Video of it yo Lee  so you can see whats happening.
Thanks Nigel. 

Sent from Yahoo Mail on Android 
 
  On Mon, 14 Jun 2021 at 8:14, Richard ***@***.***> wrote:   


@Snage62 Do you mean in the editor or when you are testing the game?

**Comment by rvanner** [comment]
@Snage62 Yes a video will be a great help. Thanks!

**Comment by Snage62** [comment]
Hi Lee & Richard
Here is the Video of what is happening, I made the dungeon in Game Guru and set it to Grid mode, I have not had time
 to try and see if it works ok in Max,  I had noticed that it is very hard to slide the Dungeon items together.  I hope you can help, because I have done 6 full size dungeons in Game Guru and  if I have to redo them in Max then I will. Its hard being a one man band. I really appreciate you help on this. 

Thanks
Nigel 
Ps The Video is too large, will send it this evening.
