### ISSUE TITLE
Grouped objects - rotating a group will lead to an object losing it's rotation

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1199]
See in this video how one of the walls loses it's rotation as I keep rotating the group.

https://youtu.be/8xq07Aauiwo

**Comment by LeeBamberTGC** [comment]
Please test this with the latest build, I could not reproduce it. What was the name of the asset you dragged in?

**Comment by rvanner** [comment]
@LeeBamberTGC It's from the military pack that we have yet to add into the released version. I will check it now in the latest build and let you know.

**Comment by rvanner** [comment]
@LeeBamberTGC Yes, still happens.

**Comment by rvanner** [comment]
FYI, I made a group from this model from that pack then dragged in a group of it and rotated it, after a number of rotations one of them went wrong;

![image](https://user-images.githubusercontent.com/1503593/123821737-939b1980-d8f3-11eb-8e0c-96a02eddf4a4.png)

**Comment by LeeBamberTGC** [comment]
Any chance you can reproduce this with one of the objects we have in the stock build?

**Comment by rvanner** [comment]
@LeeBamberTGC Not been able to do it with stock media. You have the military pack, so check out these right angled walls and they will show up this issue.

**Comment by rvanner** [comment]
This is still an issue in the latest version. Check out this video. It's when you rotate with one of the other objects that it can get messed up.
https://youtu.be/dqnTDnsKYRY

**Comment by rvanner** [comment]
Still happens today!

**Comment by rvanner** [comment]
Seems fixed now!
