### ISSUE TITLE
The element icons should not scale larger when you drag the window to the left

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1201]
See how large they can get:

![image](https://user-images.githubusercontent.com/1503593/122522280-ae28e500-d00d-11eb-85c8-db847bf1f612.png)

**Comment by LeeBamberTGC** [comment]
NOTE: Recommend scale as normal, but when wider than four or more objects across, switch to a single row and cap the size, then center the 10 icons as the panel is further expanded wider.

**Comment by plemsoft** [comment]
Fixed, now change to single row when space available :)

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
