### ISSUE TITLE
Max not remembering import co-ordinates

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1202]
Max not remebering import co-ordinates like rotations etc

**Comment by rvanner** [comment]
@LeeBamberTGC Could you have a look at this for the next build? It's holding up the importing of a new pack of assets.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Basically some of these imports are almost unfindable either out at sea, high in the sky or even under terrain.
I spent ages on a load getting the position and orientation right to find after they did not save.
I probably should have checked but you know what its like when you get a rhythm going before you know it 30 odd models have been imported. :)

**Comment by rvanner** [comment]
@synchromesh62 Can you zip up a few of the objects that cause this issue and send direct to Lee?

**Comment by synchromesh62** [comment]
Yep sure i will get that done.

**Comment by rvanner** [comment]
@synchromesh62 Can you send the files today? I'd like to get Lee looking at this ASAP. :-)

**Comment by synchromesh62** [comment]
@rvanner 
Hi Rick
I sent the files to lee on 22-6-21.
Same day you requested me to on the Discord

**Comment by rvanner** [comment]
@synchromesh62 OK thanks!

@LeeBamberTGC Can you look at the import issues on these models this week?

**Comment by LeeBamberTGC** [comment]
There will be a new button in this weeks build to center the mesh data for those models that are shifted away from their true center.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Awesome.
Thanks Lee
That will help so much :)

**Comment by rvanner** [comment]
@synchromesh62 Is there an issue around this or can we close it now?
