### ISSUE TITLE
Importer issues in Classic

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#1203]
Currently, when importing custom assets with PBR textures into classic using the importer, whilst the assets themselves appear to import fine, they are invisible in both the editor window, and during test game, however the collision seems to be working on said assets

**Comment by Kasseyus** [comment]
There is a file missing from the FPE that specifies the model.

e.g. .  Model = signpost.dbo

You can add this manually and it works as it should. (as a quick fix until it's really fixed)

**Comment by GraPhiX-Guru** [comment]
i can confirm the ;orientation section is missing from the FPE a quick fix for end users is to add these lines after ;visualinfo section

;orientation
model            = your model name here
offx             = 0
offy             = 0
offz             = 0
rotx             = 0
roty             = 0
rotz             = 0
scale            = 100
collisionmode    = 0
defaultstatic    = 1
materialindex    = 0
matrixmode       = 0
cullmode         = 0

**Comment by plemsoft** [comment]
@mav3r1ck198-1 Thanks for reporting this issue, this has been fixed and will be included in the next update :)
