### ISSUE TITLE
GG Classic (June 2021 fixes)-Entities in editor missing in test game mode

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1204]
Missing entities in test mode but in editor.  reverted back to xmas 2020 and they appear in test game mode.
![GGClassic_current_public_preview_build_june2021_character_mssing_in_level_present_in_editor](https://user-images.githubusercontent.com/15969299/122878955-3f5ecb00-d330-11eb-9d6d-b3b5fbfae96f.png)
![GGClassic_xmas_2020_fixes_character_present_in_level](https://user-images.githubusercontent.com/15969299/122878961-408ff800-d330-11eb-8be9-56ca35ab6f0b.png)

**Comment by redagent101** [comment]
has something changed in the fpe?

**Comment by redagent101** [comment]
just to add ,march fixes 2021-all showing in that version also.
BOTR

**Comment by plemsoft** [comment]
@redagent101 Thanks for reporting this issue, could you e-mail me the object that are missing in test game , there was some support for older animation missing in the last update so i assume that is the problem, but just to make sure, please e-mail the object so im able to test:  plemsoft@plemsoft.com

Thanks for your help :)
