### ISSUE TITLE
Adding more than one light with a behaviour into the Editor and then testing the level only shows one light

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1206]
I tried to set up 4 rotating spotlights: 

![image](https://user-images.githubusercontent.com/1503593/123099485-23d7eb00-d42a-11eb-81fa-791a327fee58.png)

But when I tested the level only one was shown.

**Comment by rvanner** [comment]
This bug is actually to do with the lights not using the rotation set in the editor. So they are actually working but they are not offset and so it looks like just one light.

**Comment by plemsoft** [comment]
@rvanner Just tried this , and it worked fine here ? , what script was you trying to use ? , i used rotate light.

![rotatelight](https://user-images.githubusercontent.com/18662417/130026090-544cca7a-1aad-4e66-bd05-12aacac73d13.jpg)

**Comment by rvanner** [comment]
@plemsoft Yes, in the latest version it's working better than when I first reported this. I just added 4 rotating spot lights and got some odd results;

1. I would expect all the lights to rotate the same way if I do not change any values. I found 2 went clockwise and 1 went ant-clockwise
2. The 4th light didn't move at all.

So still some issues here.

Do you want to see a video of it?

**Comment by plemsoft** [comment]
@rvanner Looks like the script do not start at the correct angle , try this script and let me know if it fix your issue :)

[RotateLight.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7013542/RotateLight.zip)

**Comment by rvanner** [comment]
@plemsoft Sorry, that did not work for me. I copied it into the script bank markers folder but got the same result. See my video;

https://youtu.be/aFjgBwC5EI0

**Comment by rvanner** [comment]
@LeeBamberTGC Why did you close this? I just tried it in the latest build. The lights rotate but they don't start with their chosen rotation from the editor.

**Comment by plemsoft** [comment]
@rvanner You need to use the above script , @LeeBamberTGC i was not able to upload to "MAX_BUILD_FILES" looks like its been removed, so use the above script.

**Comment by rvanner** [comment]
@plemsoft Yes that fixed it for me.

@LeeBamberTGC Can you ensure the new script is updated to the build and then close this issue?

**Comment by LeeBamberTGC** [comment]
Done :)
