### ISSUE TITLE
Copy and paste a light object and the colour palette does not show in the properties

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1207]
It should show like this;

![image](https://user-images.githubusercontent.com/1503593/123101084-97c6c300-d42b-11eb-832a-f5295884bf93.png)

But you see this;

![image](https://user-images.githubusercontent.com/1503593/123101110-9dbca400-d42b-11eb-8910-47be91b3345c.png)

You can get the palette to show if you click the 3D scene

**Comment by plemsoft** [comment]
@rvanner Cant reproduce here , old issue ?

**Comment by rvanner** [comment]
Yes, fixed now.
