### ISSUE TITLE
The element icons need a grey version for when users choose grey user interface

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1208]
It will avoid the icons looking out of place and ensure the choice of grey is used everywhere in the editor

![image](https://user-images.githubusercontent.com/1503593/123248682-1d0baf80-d4e0-11eb-836b-8c7e65d6081f.png)

**Comment by plemsoft** [comment]
@rvanner The blue color is inside the actual icon , so i need a new set of icons to do this, perhaps instead of using "blue" as the background of the icon, it should be a semi transparent "gray" so the background color of the window can be seen through, this would give them a little color from the background, but still be seen as buttons, but a artist needed.

**Comment by rvanner** [comment]
@plemsoft I will get updated blue and new grey icons from our artist. Lee added new blue icons but the transparency was missing so they now have white edges showing.

**Comment by michaeloldman** [comment]
@rvanner yes reported the icon corner issues.
The grey interface looks much better with proper icons ( I edited mine)

![dark theme matching element icons](https://user-images.githubusercontent.com/12246318/130356739-42b233b1-a3b4-44e3-bfc8-0fd707b8bd8e.png)

When I was editing them I was thinking semi transparency might work (as Preben mentions above) so you could have one icon set for any theme?

**Comment by rvanner** [comment]
@plemsoft I sent you new icons on Friday, so you should be able to sort this now.

**Comment by plemsoft** [comment]
@rvanner The Friday set was incomplete (see e-mall) , i completed the blue set myself, and used the set from @michaeloldman that was complete. Look way better now :)

**Comment by rvanner** [comment]
Fixed in latest version. Closing this issue.
