### ISSUE TITLE
Level crashing in test mode Game Guru Classic

### ISSUE THREAD

**Issue by C4ever08** [TheGameCreators/GameGuruRepo#1209]
So since the march update I've bee having an issue when creating a new level. I built an indoor level in ebe and its fine when that is saved but then When i add weapon to start marker and start adding entities I will go into test mode and usually I will fire off my gun then it crashes resuming from last session and breaks my level even A.I wont shoot at you.

I decided to rebuild the level and save each time I added something new till i would get that crash again and this isn't the only level it happens on it seems every time I start a new level this occurs I can send you the levels and assets if needed to help resolve this issue

Alright I did more tests it seems to be A.I and weapons, stock and custom that crashes the test mode once they shoot me or I shoot them  or add any new assets I went back to the autumn update and its still the same.

**Comment by plemsoft** [comment]
@C4ever08 Thanks for reporting this issue, yes please e-mail me a copy of the level so im able to check what the problem is. plemsoft@plemsoft.com

Thanks for your help :)

**Comment by ScorpioGames** [comment]
I'm having a similar issue... it seemed to have happened after adding new weapons from the tgc store... I'm not sure if it's relevant but i have a lpg that popped up for my map telling me to replace two ebe files that don't exist on the map.. being ebe138 and ebe140.. I can't find either on my map and can only find 138 in the folders.. I apologize I'm a noob.. but this issue seriously seems to have come out of nowhere.

**Comment by ScorpioGames** [comment]
My current project was going very smooth until this.. I have hit a wall.
