### ISSUE TITLE
[Gameguru Classic]   DNS  Texture Worklflow - _S (Specular not working in standalone)

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#1210]
Hi.

Title says it all, specular maps arent working in standalone gameguru.
I dont know why.

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this issue, it looks like the PBR materials are not getting copied to the standalone, could you try to copy the materials over by hand and let me know if it fix your issue, the materials are needed for the old DNS to work in PBR:

\Game Guru\Files\effectbank\reloaded\media\materials\

Thanks for your help :)

**Comment by Duchenkuke** [comment]
thanks for answering preben!

Yes I can confirm that copy the materials folder to the standalone fixed it.
Nice!

**Comment by plemsoft** [comment]
@Duchenkuke materials will now also be included in the standalone, ready from the next update :)
