### ISSUE TITLE
Issue: Impacts Remain in editor after Test

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1216]
If you hit an object its material index generated impact graphic will remain in the editor. Not a huge issue.
![flash](https://user-images.githubusercontent.com/35990109/123555507-2ac96b00-d754-11eb-8bce-0edd11745d83.JPG)

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed and will be included in the next update :)
