### ISSUE TITLE
Character Creator Save Broken

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1217]
If you change the path then the character finalise screen does not appear.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: PCX0DX                          
Processor: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 CPUs), ~2.3GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) UHD Graphics
Dedicated Memory: 128 MB
Current Mode: 1920 x 1080 (32 bit) (144Hz)
Card name: NVIDIA GeForce RTX 2070 with Max-Q Design
Dedicated Memory: 8031 MB
Current Mode: 1920 x 1080 (32 bit) (144Hz)

**Comment by LeeBamberTGC** [comment]
Character creator improved quite a lot since July. Saves fine.
