### ISSUE TITLE
LUA - SetGamePlayerStateWaterlineY

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#122]
When using the LUA command **SetGamePlayerStateWaterlineY** and giving it a value... The water height will not return to its original state when exiting a test game. I came back to find that my map's water height had changed within the editor due to the in game usage of this command.

There needs to be a new value (perhaps) that saves the original water Y position and when the user exits the test game, the water returns back to the original Y position.

In the meantime I will use **SetGamePlayerStateWaterlineY(500)** at the beginning of each of my maps. As a way to prevent this bug.

**Comment by HierToo** [comment]
Will look at the fix. Could break my water mod....

**Comment by Teabone3** [comment]
What are the details of your water mod? I've been working on swimming which uses gameloop.lua and the global player controls lua with minimalist modifications and currently no new additional variables. But does rely heavily on the GetGamePlayerStateWaterLineY.

https://forum.game-guru.com/thread/219463

**Comment by plemsoft** [comment]
Dont break anything , just reset the water line when you return to the editor.

	t.terrain.waterliney_f = g.gdefaultwaterheight;

This is ALL the code involved :)
