### ISSUE TITLE
Spot Light rotation widget is broken

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1220]
The actual light and the 3d model in editor of the Spot Light entity are not lined up correctly. So the widget rotates the model of the light in the editor fine but where the actual light points is anyone's guess.  There is also a point when rotating on the Z-axis the 3d model will bug out. uploaded video showing this. 

https://www.youtube.com/watch?v=3ODZv8d4NGA

**Comment by LeeBamberTGC** [comment]
Fixed for next internal build.
