### ISSUE TITLE
Model Importer Save Broken

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1222]
Similarly to the Character Creator bug, when the path to save the imported model is changed, the finalise object creation screen will not appear.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: PCX0DX                          
Processor: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 CPUs), ~2.3GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) UHD Graphics
Dedicated Memory: 128 MB
Current Mode: 1920 x 1080 (32 bit) (144Hz)
Card name: NVIDIA GeForce RTX 2070 with Max-Q Design
Dedicated Memory: 8031 MB
Current Mode: 1920 x 1080 (32 bit) (144Hz)

**Comment by rvanner** [comment]
@ZakJudges Please check and confirm this is working in the latest build. If it is, please close.

**Comment by ZakJudges** [comment]
@rvanner It's working in my branch but still needs to be merged, so will likely be in next weeks build. Will hold off on closing it for now.

**Comment by rvanner** [comment]
@ZakJudges Can you make sure Lee gets your latest changes so he can include it in tonight build?

**Comment by ZakJudges** [comment]
@rvanner No worries, will do.
