### ISSUE TITLE
Issue with Resource Search on Startup

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1225]
...connected a 3”1/4 USB disk reader on PC and Game-Guru tried to search something there.

Removed it and it works correctly.

**Comment by plemsoft** [comment]
@ZakJudges Thanks for reporting this issue.

If you just wait, do it startup at some point ? or do it just hang at startup ?
If this is the case, could you try to set "producelogfiles=1" in setup.ini , and add the generated "Guru-MapEditor.log" here so im able to see at what point it is stopping.

Also let me know what drive letter your USB drive have, Thanks for your help :)

**Comment by ZakJudges** [comment]
@plemsoft This was reported by a user, but I don't have their contact details to ask them. I'll see if I can get them :)

**Comment by rvanner** [comment]
@plemsoft I think this came from Lee and was reported by Mark Blosser.

**Comment by plemsoft** [comment]
@LeeBamberTGC It was not from Mark, do you remember who reported this ?

**Comment by LeeBamberTGC** [comment]
@plemsoft I think it was emailed to me many months ago. Was strange enough so I added it to the issues board. If it cannot be reproduced, it might not have been a software bug, just a system thing.
