### ISSUE TITLE
add object touches right edge of window and crashes GG

### ISSUE THREAD

**Issue by niijel** [TheGameCreators/GameGuruRepo#1227]
open the add popup, drag it to right, when it touches right edge of screen/window it crashes GGmax

**Comment by rvanner** [comment]
@niijel Can you confirm if this is still an issue in the latest version of MAX? I cannot make this happen.

**Comment by niijel** [comment]
I can confirm this still occurs in the latest build.

**Comment by niijel** [comment]
making main window less than full screen - still get same problem, do you need any files or other info off me to help resolve this?

**Comment by rvanner** [comment]
@niijel Could you make a small video to show the issue please?

**Comment by niijel** [comment]
What I saw when the add window touches the right edge of main window has changed with this weekends release - it still crashes but the add window turns purple? I used nvidia shadowplay to record the crash and it doesnt show the purple but does show the add window blown up large. I assume this is related to frame buffers or masking - but maybe just a different appearance after the initial crash. Video attached...

**Comment by niijel** [comment]
screen grab with shadowplay doesnt show what I actually see, I dont see the add screen become large and mouse pointer never returns from the activity indicator. Hopefully some clues in this:-
NVIDIA System Information report created on: 08/28/2021 21:08:26
System name: NIIJEL-PC

[Display]
Operating System:	Windows 10 Home, 64-bit
DirectX version:	12.0 
GPU processor:		NVIDIA GeForce RTX 2070
Driver version:		466.77
Driver Type:		DCH
Direct3D feature level:	12_1
CUDA Cores:		2304 
Core clock:		1620 MHz 
Memory data rate:	14.00 Gbps
Memory interface:	256-bit 
Memory bandwidth:	448.06 GB/s
Total available graphics memory:	16358 MB
Dedicated video memory:	8192 MB GDDR6
System video memory:	0 MB
Shared system memory:	8166 MB
Video BIOS version:	90.06.3D.00.2F
IRQ:			Not used
Bus:			PCI Express x16 Gen3
Device ID:		10DE 1F02 1F0210DE
Part Number:		G160 0051

[Components]

nvui.dll		8.17.14.6677		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.14.6677		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.14.6677		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.14.6677		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.14.6677		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvWSSR.dll		27.21.14.6677		NVIDIA Workstation Server
nvWSS.dll		27.21.14.6677		NVIDIA Workstation Server
nvViTvSR.dll		27.21.14.6677		NVIDIA Video Server
nvViTvS.dll		27.21.14.6677		NVIDIA Video Server
nvLicensingS.dll		6.14.14.6677		NVIDIA Licensing Server
nvDevToolSR.dll		27.21.14.6677		NVIDIA Licensing Server
nvDevToolS.dll		27.21.14.6677		NVIDIA 3D Settings Server
nvDispSR.dll		27.21.14.6677		NVIDIA Display Server
nvDispS.dll		27.21.14.6677		NVIDIA Display Server
PhysX		09.19.0218		NVIDIA PhysX
NVCUDA64.DLL		27.21.14.6677		NVIDIA CUDA 11.3.121 driver
nvGameSR.dll		27.21.14.6677		NVIDIA 3D Settings Server
nvGameS.dll		27.21.14.6677		NVIDIA 3D Settings Server

**Comment by rvanner** [comment]
@plemsoft Please check this video in this report, its shows an odd behaviour of the object library.

**Comment by plemsoft** [comment]
@niijel When a window hits the edge Max will convert the window from a child into a parent window, so it can work on its own, we do this to support Multiple Monitors so your able to drag the window into another monitor.

Do you have more then one monitor ?

If not then i expect that you have setup multiple displays in NVIDIA Control Panel, please check under "Set Up Multiple Displays." and if you have more then one displays setup try to uncheck the last, let me know if that fixed it.

Still not working, do you run any special virtual desktop or similar apps ?

Thanks for your help :)

**Comment by niijel** [comment]
I only have single monitor, only one shown on nvidia control panel.
But I do use stardock fences 3 on my desktop, which has capability of multiple desktops but I have that feature disabled. 
I disabled fences in my startup and reset, still have same issue.
then I noticed that I have the windows 10 built in multiple desktops active [ctrl+win+left arrow/ctrl+win+right arrow]
attached is the windows settings page with my settings - hope this helps!
![ggmax-error](https://user-images.githubusercontent.com/7059822/132948156-8e29787a-56cf-4e8d-8e28-e30f0f7f29e9.png)

**Comment by plemsoft** [comment]
@niijel I see you closed this issue, just for the record could you let me know what the problem was, thanks for your help :)

**Comment by niijel** [comment]
Sorry - didnt mean to close it. Its open again!

**Comment by plemsoft** [comment]
@niijel We found the problem, but need you to test it in the next update:

After the next Friday build:
Go to "Settings->Developer" and make sure "Disable Object Library Viewport" is checked.

After that , try to move the window to the edge, and let me know if it fix your issue, Thanks for your help :)

![objectlib-viewport](https://user-images.githubusercontent.com/18662417/139850396-eb07dcee-de65-4dd7-8ce7-66bfbd2450ce.jpg)

**Comment by niijel** [comment]
I can confirm that on fridays build - ticking 'disable object library viewport' prevents the issue. - when unticked issue was as before. Good job finding that one :-)
