### ISSUE TITLE
Model importer problem

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#123]
When using the model importer the model looks fine in the importer but when placed in the level the texture is used as a tile and is repeated 1000's of times on the model, manually making an FPE works fine.

![ggbug](https://user-images.githubusercontent.com/36109432/37556982-b845fd3c-29f5-11e8-9a48-4f039e18b47f.jpg)
![bug](https://user-images.githubusercontent.com/36109432/37556985-bd2c2268-29f5-11e8-9470-bc798c69fcc3.jpg)

**Comment by plemsoft** [comment]
Looks like it only happens if you do not select a shader , even if entity_basic is already selected (displayed) , you need to select it again for it to work.

I will fix it in the next release so you do not have to select a shader , but entity_basic will be "selected" for you by default.

**Comment by BodRH** [comment]
Thanks Preben.
