### ISSUE TITLE
Material Editing Issue

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1230]
When changing materials of objects in the importer or object tools...if the selected texture is not in the same directory as the imported model, the texture will not apply and instead the model will display the default white texture. If a texture is selected again with a different path to the model, a crash will occur.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: PCX0DX                          
Processor: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 CPUs), ~2.3GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Intel(R) UHD Graphics
Dedicated Memory: 128 MB
Current Mode: 1920 x 1080 (32 bit) (144Hz)
Card name: NVIDIA GeForce RTX 2070 with Max-Q Design
Dedicated Memory: 8031 MB
Current Mode: 1920 x 1080 (32 bit) (144Hz)

**Comment by rvanner** [comment]
@ZakJudges Can you check this works in the latest build and close it off if all working?

**Comment by ZakJudges** [comment]
All working. Closing it off.
