### ISSUE TITLE
Duplicate category listings for Object Library

### ISSUE THREAD

**Issue by madmattius** [TheGameCreators/GameGuruRepo#1234]
Hi,

After I upgraded to the lastest Alpha today - 20210709, I noticed there are duplicate category listings in the Object library (pic attached). All the categories renamed to remove "The" are listed and empty when you browse inside them. All the pinned categories in the screenshot are fine. I didnt have any objects in the "User" category to start with. 

I did have to make two attempts to download the latest update as I had some sort of interrupt with about 1.9gb to go. Once fully downloaded it installed fine however. 

Regards
Matt
![Desktop-screenshot](https://user-images.githubusercontent.com/87215836/125149888-125b4680-e17f-11eb-851e-b852b96a3908.png)

**Comment by rvanner** [comment]
@madmattius Use explorer and go to this folder; C:\Program Files\GameGuruMAX\Max\Files\entitybank

Remove any empty folders, this will clean up the list.

Currently the installed does not clean up older folders.

**Comment by rvanner** [comment]
This is just a side effect of using alpha versions. A clean install will fix this. Closing this issue now.
