### ISSUE TITLE
Light Probe Scale Issue

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1235]
steps to reproduce:
place a light in the scene
copy and paste the light
select the light (Color Palette menu does not appear)
if you click off of the light then the correct menu layout will appear,
...however, if you click on another object then both objects are highlighed.
when trying to scale the light probe, the scale is not applied, and sometimes affects other objects instead

This also happens with other objects after you copy and paste.

**Comment by LeeBamberTGC** [comment]
@rvanner @PaulSJ Should we remove the light probe scale from the EA version, and fix this at a set size?  It is currently a confusing message to most users, and I do think after EA we should opt for allowing a separate placement of virtual probes in a scene not connected with the light element.

**Comment by rvanner** [comment]
@LeeBamberTGC The light probes need some discussion. Chris M. has issues with his level due to the auto probe system mixing in with the torch. Suggest we have a call on this today if poss. Say 3pm?

**Comment by LeeBamberTGC** [comment]
@rvanner Was rather hoping I could do some actual coding today, but sure, feel free to call me at 3 PM :)

**Comment by LeeBamberTGC** [comment]
NOTE: Removed LIGHT PROBE SCALE, will have a better feature for after EA release (perhaps manual placement of env map probes for advanced users)
