### ISSUE TITLE
new  tree models frame rate issues

### ISSUE THREAD

**Issue by sciencebloke50** [TheGameCreators/GameGuruRepo#1237]
all objects work fine lots of jungle trees and rocks etc there are no issue even with a lot.

but
place a few of the new trees done and the frame rate drops to 6fpm this is with even 2 trees its low frame rates, i took physics off and they still eat the framerate

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MBB-36008
Processor: AMD Ryzen 5 3600 6-Core Processor               (12 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 970
Dedicated Memory: 4043 MB
Current Mode: 1680 x 1050 (32 bit) (59Hz)

**Comment by LeeBamberTGC** [comment]
Whole new tree system added to allow MANY trees :)

**Comment by sciencebloke50** [comment]
yes thank you lee

any idea if you will at some point make advance on larger terrain?


many thanks for your reply

________________________________

**Comment by LeeBamberTGC** [comment]
@sciencebloke50 The current MAX allows terrains of up to 5km, that takes an hour to walk across your game level. I think that is pretty big enough for the EA version :)

**Comment by sciencebloke50** [comment]
Oh yes I agree I was thinking next year if you would possibly have a look and you did say you would look into it, so I was chancing my arm on finding out a vague idea. I have lots to do myself building my new world models for the rpg genre. Many thanks again


Uncle lee

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
