### ISSUE TITLE
Muzzleflash problem:

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#124]
Muzzleflash problem:
When you shoot to the ground, the muzzleflash does not display well.
![snapshot5](https://user-images.githubusercontent.com/36647058/37567756-ac92bfa2-2ae0-11e8-9c14-b3b763f6fc80.jpg)

**Comment by LeeBamberTGC** [comment]
This has been fixed in a recent build, and also fixed the smoke (muzzle flash before weapon draw, smoke after weapon draw).
