### ISSUE TITLE
GameGuru MAX Updater

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#1243]
The MAX updater is getting bigger and bigger, i think the interface needs a change, allowing users just to download the core files, add the assets to a separate list with check-boxes, i don't think the assets would change that much i think it is a case of just downloading the new ones but this can be done as a background task rather than being bundled with the core files, i don't have a problem with large downloads but i do know many do.
As more assets are released the larger/longer downloads will cause grief !!

**Comment by rvanner** [comment]
@GraPhiX-Guru This is planned later on. The idea will be to have some core objects and then the sub folders can be downloaded by users when it's more convenient for them. I'll keep this as an issue until the team work on it.

**Comment by GraPhiX-Guru** [comment]
The Installer is the 'Ambassador' for MAX it is the first thing users see and use it should be at the forefront of the development cycle, it all fine and dandy getting MAX to work but it is more important to get it out to users fast and clean, cater for the minority not the majority in this case

**Comment by Belidos3D** [comment]
This should be high importance. Nobody wants to be downloading multiple gigabytes of data for what could be potentially for some people hours before they can use a product, you could lose the interest of a lot of customers before they even use the product. Plus while you're asking us to be testing the product for you, we need to be able to get in there and test things, not spend hours waiting for downloads.

**Comment by rvanner** [comment]
I'll change it to high. We will review what to do in a few weeks time.

**Comment by GraPhiX-Guru** [comment]
Thank you @rvanner  but one more observation to consider, last week was a 10gb download in one week it grew to 15gb whilst I appreciate the assets we are getting (its brilliant) I think the rollout should be separate to the core program at this rate in 1 month we could see 35gb + !!!

**it needs addressing before we get to 20gb+ downloads**

**Comment by rvanner** [comment]
@GraPhiX-Guru The latest Tiny Installer now lets you choose what to download. Try it and let me know if it's a better experience.
