### ISSUE TITLE
Settings: Show welcome screen on startup

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1245]
This tick box does not match the tick box on the welcome screen itself. They both should work in parallel.

![image](https://user-images.githubusercontent.com/1503593/125454385-0632e091-3cbb-4cdc-86a7-8373b88a78dd.png)

![image](https://user-images.githubusercontent.com/1503593/125454460-aa686850-4211-4612-b822-36f57b243d08.png)

**Comment by plemsoft** [comment]
Fixed.

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
