### ISSUE TITLE
The widget has a highlight around it

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1248]
The widget itself should not have the yellow surround:

![image](https://user-images.githubusercontent.com/1503593/125465521-05e06bce-5d34-4236-b78d-d7624b35fe42.png)

**Comment by LeeBamberTGC** [comment]
@rvanner It does not have an outline, it is the object itself completing its own outline:

![image](https://user-images.githubusercontent.com/35840583/164209304-ddf525b2-7d9e-43b8-a534-268ca6d39274.png)

And now:

![image](https://user-images.githubusercontent.com/35840583/164209731-f8d11844-a4cf-4d27-b345-9181ead4410f.png)

I do not think this is critical and should be closed until we get a lot of community flak on this visual.

**Comment by rvanner** [comment]
OK, that explains it. The stencil buffer is not the best system for highlighting objects. We should do something better later on. 
Closing this now.
