### ISSUE TITLE
problem in the Win Zone.

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#125]
The GG software does not work well after: Type a name (the next stage) in - field if used (Win Zone properties). And after saving the stage.
[WINZONE.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1822866/WINZONE.zip)

**Comment by Shahin3d** [comment]
It happens when that: pbroverride = 0

**Comment by LeeBamberTGC** [comment]
Can anyone confirm this with a simple step by step from a fresh level, thanks!

**Comment by honkeyboy** [comment]
@ Lee i have found a bug whereas the winzone doesnt work above ground level works fine on the ground but if say i put it on a platform it fails might be worth checking to see if it just my end (i got around this by using say a terminal with jump to level)

**Comment by Belidos3D** [comment]
|i'm not sure if that's actually a bug HonkeyBoy, this has always been like this and i asked a long time ago about it, and was told that zones only work at terrain level, whether that has changed or not i don't know.

**Comment by honkeyboy** [comment]
Oh? didnt know that m8 lol used to work for me on the sci fi levels (typical rofl)

**Comment by Shahin3d** [comment]
This problem has been fixed in the new update.
I have no problem.
