### ISSUE TITLE
Need a field to enter an object's strength value

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1252]
There's no field for an object's strength. Suggest it's added to the Developer Mode settings of an object.

**Comment by plemsoft** [comment]
@rvanner Please explain what you mean by "object's strength" , Thanks :)

**Comment by rvanner** [comment]
@plemsoft An object has a strength value. The player might hit it with a melee weapon or shoot at it. If the strength value is low then the object will break / be destroyed. A higher value means it will be tougher to break.

**Comment by plemsoft** [comment]
@rvanner Ahh health , we already have that under "general" and its already called strength :)

**Comment by rvanner** [comment]
I think this has been added since I reported this. Closing this issue down now! :-)
