### ISSUE TITLE
Fog settings are not remembered after a save and a load

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1256]
1. Make a level
2. Set some fog
3. Save the level
4. Quit Max
5. Reload Max
6. Load the level
7. The Fog settings are not as they were edited before save

**Comment by rvanner** [comment]
Issues was reported on DIscord by OldFlak;

BUG 2021.07.16
Editor Settings Not Being Saved
- Fog settings not being saved
- - distance always set to 60\100 
- - consistently ignores saved values when restarting MAX
- Texture settings not being saved even when running level - random
- - example shadows on\off

**Comment by plemsoft** [comment]
Fixed :)
