### ISSUE TITLE
Importer Texture Assignment Issues - Cancel undoes previous selections 

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1257]
**Reported on Discord by OldFlak**
Importer Texture Assignment Issues - Cancel undoes previous selections (not new, been there since day one)
- example: select any Surface Channel, decide you didn't really want to do that, choose Cancel
- - this effectively undoes all previous selections for each surface channel
- - you now have to select each channel again and apply the textures
Expected behavior:
- Cancel returns to previous selections, and changes nothing

**Comment by rvanner** [comment]
I will ask OldFlak to check this when he gets the new build.

**Comment by michaeloldman** [comment]
@rvanner Tried this with two models in current build 2021.08.20
- One model with single mesh and texture set - works perfectly
- Other model with multiple meshes refencing multiple textures sets - also works perfectly

This issue can be closed now.

Greta work MAX team!

**Comment by rvanner** [comment]
@ZakJudges Great work on this one!
