### ISSUE TITLE
Importer Texture Assignment Issues - Can't clear entry

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1258]
**Reported on Discord by OldFlak**
Importer Texture Assignment Issues - Can't clear entry (not new, been there since day one)
- Assign texture to emissive channel
- Decide you really didn't want to do that
- - you can not clear the entry - MAX keeps putting it back
Expected behavior:
- when you clear a entry, MAX should not repopulate the field
- this should apply to all fields throughout the editor panels not just when adding textures via the importer

**Comment by LeeBamberTGC** [comment]
@rvanner Can now clear emissive field and it will not revert to old path for next EXP build.
