### ISSUE TITLE
When in stack mode, the 3D light icon gets messed up

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1263]
See this screenshot, the normal bulb has a spot light model mixed with it;

![image](https://user-images.githubusercontent.com/1503593/125956032-d38b8cda-0650-4e59-8a60-ae8e560ce902.png)

**Comment by rvanner** [comment]
This is also now happening as soon as you drag in a light object.

**Comment by plemsoft** [comment]
Fixed.

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
