### ISSUE TITLE
Character possible bug

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#1264]
when building a character i found this.
![charbug](https://user-images.githubusercontent.com/41600041/126063002-19fde1d5-3a8c-436d-af31-99b485137d63.png)

Also i don't know if i have missed this one, but i hope there will be more than one face to choose from when the character builder ifs finished.

Thanks
Pcs

**Comment by rvanner** [comment]
@Pcskiller These older clothes are likely to be removed. We will also ensure cloths that don't match can never be chosen at the same time. In next week's version you will have access to more female choices.

**Comment by Pcskiller** [comment]
Thank you so much for your reply.

Just some questions, :
would it be possible to add a setting for hands as well so that we can
remove the hand gloves to go with or without a certain character.

At the end of the character creator, would there be altleast more than one
male and female character to choose from?
 the clothes and head gear all is fantastic, but it would help if one make
a game were there are going to be alot of people in a town that does not
all look the same with the shape of there faces.

Thanks so far for a fantastic character creator.

Pcs
