### ISSUE TITLE
Object Library Bug

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1265]
When hovering over object previews to display a live image, some of the lighting settings for the level are 
applied to the object being previewed. 

![ObjectLibBug](https://user-images.githubusercontent.com/32545391/126130614-7dfa3f34-a39b-49a3-9cdc-4d045ab9a01b.png)

**Comment by michaeloldman** [comment]
Yes seeing the same also. Fog affects it as well.

**Comment by rvanner** [comment]
This a duplicate report. I will close this one. It's reported here;
https://github.com/TheGameCreators/GameGuruRepo/issues/1282
