### ISSUE TITLE
Import Model Issue - No Material Index Assignment

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1266]
Cannot see any way to assign material index to a model.

How does the engine know if the model is metal, wood, glass etc....

**Comment by rvanner** [comment]
@ZakJudges What do you think about this? Is it a required extra feature?

**Comment by ZakJudges** [comment]
@rvanner This can already be accomplished by enabling custom materials and changing the settings of the object. But it would be handy to have preset values for different material types when importing a model that does not make use of a surface texture.

![Screenshot 2021-08-13 113034](https://user-images.githubusercontent.com/32545391/129344343-4f82ae6b-3ca0-431d-ae2d-fce107eae17c.png)

**Comment by michaeloldman** [comment]
Those settings are for the textures. 

But how does the engine know if it is Metal, Wood, Glass, Ground etc.
So when you walk on it it plays the appropriate foot fall sound, or when you shoot it, it will give off wood, metal, glass, dust fragments.....

**Comment by ZakJudges** [comment]
@michaeloldman apologies, I did not think far enough into that :) @rvanner We already store the material type for generating foot fall sounds etc for other objects, so I don't think it would take too much time to add in. But better to verify that with @LeeBamberTGC

**Comment by michaeloldman** [comment]
@ZakJudges no apologies needed
We just smashing bugs :)

A dropdown list in the importer widow (same as we do for collision) to select the material index would make sense to me.
But the same dropdown list should be accessible in the properties panel so you can change\disable it if you want when adding to the scene.

To me it needs to be on a per instance setting, so you can turn it on\off for performance sake in complex scenes. 

So perhaps just a option in properties panel that is disabled by default would make more sense?

**Comment by rvanner** [comment]
OK, I understand what this is for. We do need to allow the assignment of a material type. I'll make a note in the dev plan.

**Comment by rvanner** [comment]
@michaeloldman The importer now has material assignment;
![image](https://user-images.githubusercontent.com/1503593/132118626-8b0e9dcd-efbd-4115-b5c9-3c94ac9d9293.png)
Can you check and let me know if I can now close this issue?

**Comment by michaeloldman** [comment]
@rvanner Awesome - will check it out :)

**Comment by michaeloldman** [comment]
Excellent addition - I think it would also make sense for the same settings to be accessible after import, perhaps in the Developer Mode tab on Object Tools panel.
