### ISSUE TITLE
Medieval weapons bugs

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#127]
We would like to inform another bug that we encountered at the medieval weapons section. Few weapons appears as pitch black only when you put them on ground, save standalone and run the game from the .exe file. In the .fpe files of the following weapons the "textured" line has .tga extension and this can be fixed by changing it to .dds. An example is attached. (medieval 1)

-Weapons

Dagger
Flail
Halberd
Hatchet
Mace
Sword
Bow_arrows

Whatsmore is that a more serious bug appears in a standalone game when the following weapons are equipped. Some weapons appears to have another weapon's texture in game. Important thing is that it does not appear in the editor but only in .exe

-Weapons

Slingshot
Crossbow
Hatchet
Halberd
Dagger
Flail
Sword
Mace
Bow

The second listing is done by the hierarchical order of the weapons' texturaziton that we found. So what we mean is that if you have slingshot with all of the weapons lying on the ground in .exe than all the other weapons will have slingshot's texture when you equip it and hold it. If you dont have slingshot all the other weapons will have crossbow's texture and it goes on like that. Your help will be appreciated. An example is attached. (medieval 2)

PS: in the gamecore\guns\medieval folder when any of the low hieracrhical weapon is chosen (such as sword that we fixed in medieaval2) we saw that the .dds texture is not found at "textured" line in the gunspec.txt file. The bug can be half-solved by adding a gun_D.dds at textured line for every weapon but now the hand texture of the weapons will be false (hand will be covered with sword's texture for example). So it can be either fixed by adding hand texture to the existing file or coding the hand into the .txt but we couldnt find a way to do both.

Sample Levels:
http://www.yalcinkayabilgisayar.com/bug2.zip

**Comment by LeeBamberTGC** [comment]
This has been fixed in the latest build. Should be able to try in PP before end of 13/04/18 GMT.
