### ISSUE TITLE
Character Creator: Texture seams

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1271]
![Screenshot 2021-07-21 115237](https://user-images.githubusercontent.com/32545391/126478344-1086170e-e7a2-4796-9c3a-f0c66ca9ce62.png)
![Screenshot 2021-07-21 115256](https://user-images.githubusercontent.com/32545391/126478349-53ec087e-4c01-45eb-a017-41e6489ad63a.png)

**Comment by rvanner** [comment]
Fixed today by Mark. Files being sent to Lee.

**Comment by bond1mjb** [comment]
Thanks Rick,

Ok, will do!

-Mark
