### ISSUE TITLE
Character Creator: Gap in Balaclava

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1272]
![Screenshot 2021-07-21 115449](https://user-images.githubusercontent.com/32545391/126478725-38428472-4fb3-4a45-9d78-d91adc6c070a.png)

**Comment by rvanner** [comment]
@LeeBamberTGC Same for this one. Change the head if the user chooses a headdress that only fits a certain head.

**Comment by ZakJudges** [comment]
Made balaclava double-sided

**Comment by LeeBamberTGC** [comment]
@ZakJudges Let me know when you check this in and I will make it part of the build :)

**Comment by ZakJudges** [comment]
@LeeBamberTGC It's already checked in :) My latest commit at 09:23 is the one to merge, it has the stuff I'm currently working on disabled to avoid any issues with the build whilst I'm still developing it. Thanks :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Chhers, thanks!
