### ISSUE TITLE
Character Creator: Faces Cut Through Head Gear

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1274]
![Screenshot 2021-07-21 115612](https://user-images.githubusercontent.com/32545391/126479150-34e8ebe2-9133-4624-8ef0-a325f9b3d3e1.png)

**Comment by rvanner** [comment]
@LeeBamberTGC Shouldn't it be the case that if the user chooses the balaclava or similar face masks, you switch to the military head?
