### ISSUE TITLE
Character Creator: Hat is Rotated

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1275]
![Screenshot 2021-07-21 115756](https://user-images.githubusercontent.com/32545391/126479296-834e549e-3abd-40ee-80a2-16156ff9b08e.png)

**Comment by rvanner** [comment]
@ZakJudges Please remove this hat from the character creator

**Comment by ZakJudges** [comment]
@rvanner Will do!
