### ISSUE TITLE
Gloss maps for New Building Pack PBR stuff all black

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#128]
Looking thru the new PBR textures for the building pack stuff, I noticed that all gloss maps are black and thus all objects are shiny instead of there respective glossiness in the editor.

**Comment by Belidos3D** [comment]
Yup, i think the artist that updated them didn't realize that the _gloss in GameGuru is not an actual gloss map but a roughness map named _gloss, thus black and white are the opposite to expected, not sure why Lee did it that way instead of just making it the standard metallic/roughness.

**Comment by LeeBamberTGC** [comment]
Fixed the gloss (roughness) maps in the Buildings Pack DLC changes.  Longer term we will be looking to improve the textures and create better high-def textures for them, just need a willing artist to get within our gravitational force :)

**Comment by Pirate-Myke** [comment]
I am willing to fix and work on pbr textures.

**Comment by LeeBamberTGC** [comment]
Do you have specific textures in mind within the Buildings Pack, or assets in general?  Email me directly and we can discuss it at lee@thegamecreators.com, thanks!

**Comment by Belidos3D** [comment]
Now that i have found a .X importer for Blender (still need to test it first though) over time i will probably be making some alternate textures for default models (specifically the asylum), if i do i'll drop them in an email to you Lee so you can include them with the rest.

**Comment by GraPhiX-Guru** [comment]
hmmmm I had an army of volunteers to do this work and you shut us down :(
https://forum.game-guru.com/thread/219292

**Comment by LeeBamberTGC** [comment]
As this is a huge issue, I have created extra documentation for the community to help with this over the next weeks and months. Here it is (scroll to bottom): https://github.com/TheGameCreators/GameGuruRepo/wiki/How-To-Contribute-To-The-GameGuru-Master-Build
