### ISSUE TITLE
Light areas around the characters is spoiling the visual quality

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1281]
Here's a character inside a building. Around the edges of the character are light areas. I know this is to do with how the scene is being lit but it's not something I see in games. We need a solution for this.

![image](https://user-images.githubusercontent.com/1503593/126659770-71065d33-27ae-496d-877e-3866784d2a7b.png)

**Comment by rvanner** [comment]
@bond1mjb Do you have any ideas on how to solve this?

**Comment by LeeBamberTGC** [comment]
@rvanner Drop in a light into the building and expand the light probe scale so it provides a good env map for the character

**Comment by bond1mjb** [comment]
Yes Lee is 100% right.   This is caused when the ambient environment light
doesn't match up to the environment the character is in.   When I was using
Wicked Editor, I found it good practice to use a new light probe whenever
the scene's lighting changed significantly, and scale it to cover the
area.      Just one of those things that PBR shading does, but when it's
tweaked right everything blends SO nicely!

-Mark

**Comment by rvanner** [comment]
@LeeBamberTGC I find this difficult to setup and so will many users who don't understand the technical side to lighting a scene. Should buildings come with lighting and light probes all ready in place?

**Comment by LeeBamberTGC** [comment]
We could make all buildings smart objects so they all include basic lighting with correct light probes (and operating doors and windows) :)

**Comment by bond1mjb** [comment]
The smart object idea is good.   Lighting in games is more complex now, and
this would ease the learning curve and prevent users from making things
look bad out of the box.   I know I struggled with this when I was making
the cellar demo in Wicked Editor.

-Mark
