### ISSUE TITLE
When setting up an imported model, the thumbnail is affected by the current level's lighting

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1282]
I had a level with a very red sky. As you can see, the thumbnail is affected by this setting

![image](https://user-images.githubusercontent.com/1503593/126766339-5b0cb395-d36d-471c-9a7f-5a18921f202b.png)

**Comment by rvanner** [comment]
The object should be blue, not red tinted.

**Comment by rvanner** [comment]
This still seems to be an issue. It's okay to leave for now, we can fix post EA release.
![image](https://user-images.githubusercontent.com/1503593/153887501-a11ca604-435b-4338-a5c0-9aca3797772b.png)

**Comment by plemsoft** [comment]
@rvanner This has been fixed and will be in the next update , @LeeBamberTGC Please also merge wicked on your next build :)

**Comment by rvanner** [comment]
Confirmed as fixed.
