### ISSUE TITLE
Copy and paste stops the selection of objects

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1284]
This is how to make it happen;

1. Select an object in the level
2. Copy the object with Control+C
3. Paste a new copy with Control+V
4. Now try to drag one of the objects. All you can do is drag the camera around
5. You have to drag a new object in from the left before you can select the objects again
6.

**Comment by plemsoft** [comment]
Fixed.

**Comment by rvanner** [comment]
@plemsoft Now if you cut an object you cannot paste it back into the editor. It should do what copy and paste does.

**Comment by plemsoft** [comment]
@rvanner FYI: "Cut" has never been part of the objects copy/paste system (it just delete the object), you already have a report for Lee to fix this here: https://github.com/TheGameCreators/GameGuruRepo/issues/1244 , Only the above issue was fixed :)

**Comment by rvanner** [comment]
OK, I'll close this issue.
