### ISSUE TITLE
GGMax importer and cullmode issues

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1285]
I am going to use a simile to describe the problem:
Suppose you place a person on a teleporter so that he travels from point A to point B, and indeed the person is transported but arrives at point B with disordered atoms, arms on the head, ears on the mouth, nose on the back, etc. This is just what is happening with the GGMax importer; the importer is the teleporter and the test subject is my model, which reaches point B, but with all the atoms out of order, my building is deformed, as you can see in the image.

![B7_GGmax_importing_Wrong_pic01](https://user-images.githubusercontent.com/47690174/126797416-38cd7f35-2892-4caf-8ca6-35240f5050a8.png)

I must add that if I manually copy all the files (X, BMP, fpe, and so on) the model works, although it has a problem with culling. This can be seen in the image below.

![B7_Wrong_culling_GGMax_pic02](https://user-images.githubusercontent.com/47690174/126797660-4815fe84-1cbd-4dd3-b346-c7489da05cdd.png)

![B7_Wrong_culling_GGMax_pic03](https://user-images.githubusercontent.com/47690174/126797856-8e08d7b9-256d-4c8c-9a27-87910b148cc9.png)

The Culling issue happens depending on the camera angle.
I have tried, Cullmode = 0, =1, = -1, with no to avail.

I consider that they are two different problems, but both with the same model, and since I am going to send the model, TGC can take advantage of the occasion and reproduce/repair both problems at the same time.

@ Zac
I'm going to send you a download link via google drive as in the past time, if you have some issue with this, please, let me know.

**Comment by 3coms** [comment]
@ZakJudges 
Download model Google drive Link, sent to you,

**Comment by ZakJudges** [comment]
@3coms I've received it. Thanks!

**Comment by 3coms** [comment]
I had tried the GGMax importer feature, but this time, with a different mesh.
This time I've tried the City2 as FBX file, and I've attached all the parts in just one mesh, obviously with their own material/Texture each.
1- The mesh comes with wrong rotation applied. (pic 1)
2- GGMax refuses the mesh origin point, and apply their own, as you can see in pic2 the mesh is 0,0,0, it is remarked with a green box, in 3ds max.
3- Once tested the map, the mesh (city2) is CollisionOff, I've tried StaticMode = static, PhysicsOn in the mesh properties panel, but does not make the difference, it has no collision.

![City2_FBX_Imported_Wrong_Rotation_GGMax_pic01](https://user-images.githubusercontent.com/47690174/126876826-206bbd73-28a6-439a-b00a-bc599684f64d.png)


![City2_FBX_Imported_Wrong_OriginPoint_GGMax_pic01](https://user-images.githubusercontent.com/47690174/126876787-09d57380-47e4-43e6-8438-7e14c52475a0.png)

**Comment by 3coms** [comment]
I've noticed in the fpe file GGMax importer generates, that it says: _collisionmode  = 0_, so, I've changed it to _collisionmode  = 1_
but it looks like the DBO file generated by the GGMax importer, does no reflecting the changes, so, the question raise, does GGMax scan the DBO files to check changes and update them?
If we aren't able to edit DBO, how we are going to get the changes reflected on the DBO file?

Regarding security, DBO is the way to go, but at least custom meshes should have the option to choose X file as file format, then you can make all the changes you need>delete DBO>GGMax generate a new one with the changes done. imho. :)
Then, when the user makes the standalone file, so, GGMax converts all those X files to DBO, before doing nothing, but meantime the user has the ability to make changes to their own models as needed.

**Comment by Granada1** [comment]
I agree on the last point do the conversion to DBO when compiling stand alone 👍

**Comment by 3coms** [comment]
GGMax importer applies textures wrong.
Mesh: 1 mesh
Textures: 1 unwrapped UV texture - 4k
GGMax importer just applies the texture as is, ignoring UV map coordinates.

In 3ds Max

![Old_Talker_3dsMax_pic01](https://user-images.githubusercontent.com/47690174/127755956-fae2fb5f-72b8-411c-893f-35e473c49d04.png)

In GGMax importer

![Old_talker_Textures_wrong_applied_GGMax_Pic01](https://user-images.githubusercontent.com/47690174/127755963-459fd27c-2f54-438e-8356-fc39c8ca0ac6.png)

**Comment by rvanner** [comment]
@ZakJudges I'm reviewing all the bugs in the database. Was any of this fixed or is it still to be looked at?

**Comment by ZakJudges** [comment]
@rvanner It still needs to be looked at. Currently it's in the importer phase 2 schedule

**Comment by ZakJudges** [comment]
> GGMax importer applies textures wrong.
> Mesh: 1 mesh
> Textures: 1 unwrapped UV texture - 4k
> GGMax importer just applies the texture as is, ignoring UV map coordinates.
> 
> In 3ds Max
> 
> ![Old_Talker_3dsMax_pic01](https://user-images.githubusercontent.com/47690174/127755956-fae2fb5f-72b8-411c-893f-35e473c49d04.png)
> 
> In GGMax importer
> 
> ![Old_talker_Textures_wrong_applied_GGMax_Pic01](https://user-images.githubusercontent.com/47690174/127755963-459fd27c-2f54-438e-8356-fc39c8ca0ac6.png)

@3coms Any chance you could send this one too? Thanks :)

**Comment by 3coms** [comment]
@ Zac
Done. :)

[Old_Jackson1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7077965/Old_Jackson1.zip)
