### ISSUE TITLE
Sun direction isn't stored

### ISSUE THREAD

**Issue by mrfenix** [TheGameCreators/GameGuruRepo#1292]
When reloading a level, the sun direction isn't the same as when the level was last saved.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: System Product Name
Processor: AMD Ryzen 5 2600X Six-Core Processor            (12 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: Radeon RX Vega
Dedicated Memory: 8119 MB
Current Mode: 1920 x 1080 (32 bit) (59Hz)
Card name: Radeon RX Vega
Dedicated Memory: 8119 MB
Current Mode: 1920 x 1080 (32 bit) (59Hz)
Card name: Radeon RX Vega
Dedicated Memory: 8119 MB
Current Mode: 1920 x 1080 (32 bit) (59Hz)

**Comment by plemsoft** [comment]
@mrfenix Thanks for reporting this issue, this has been fixed and will be in the next update :)
