### ISSUE TITLE
Candle, Flame, light

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#1296]
I made the candle like Lee did in video
if you pan around it the items dont stay together.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: X570 UD
Processor: AMD Ryzen 7 2700 Eight-Core Processor           (16 CPUs), ~3.2GHz
Memory: 32768MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2060
Dedicated Memory: 5967 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by rvanner** [comment]
@Snage62 Can you make a video showing your issue?

**Comment by rvanner** [comment]
@Snage62 We need more info about this please.

**Comment by rvanner** [comment]
@Snage62 I have just tried this and it works fine for me. Here's a video of how I did it. I only combined the candle with a particle effect but you will see the process. 
https://youtu.be/RPrRFo3jSIQ

I will close this issue now. If you disagree, please re-report the issue and show a video of your problem if you can.

Thanks.
