### ISSUE TITLE
Ambience \ Horizon etc colour setting do not save and revert back.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1298]
As the Heading states ..
Ambience  \ Horizon etc settings do not save and revert back. 

Reproducing the issue .. 
1 run test game 
2 set your ambience etc 
3 exit to editor and save 
4 run test game again and they have reverted back to default.
This issue has been reported many times but the Ambient colour was set to almost black and not so noticeable.

Edit .. The fog is also not working. Just a side note :)

![SETTINGS](https://user-images.githubusercontent.com/35708217/128261123-9d311da8-b5f5-47cb-9696-a899f513dfac.png)

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
