### ISSUE TITLE
No collision on these walls

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1299]
You can just walk through these when in test game;

![image](https://user-images.githubusercontent.com/1503593/128381430-8d791afb-ec81-490f-8510-6a9aafe313b5.png)

**Comment by synchromesh62** [comment]
Some of us have noticed the importer has collision issues..
they just do not set so it could be related

**Comment by plemsoft** [comment]
@rvanner Just checked and i can see that the fpe files for these objects are updated in the latest release, and i do not have this issue, could you test in the latest , i think someone already fixed this :)

**Comment by rvanner** [comment]
Yes, fixed!
