### ISSUE TITLE
Weapons 'keyframe speed' in GUNSPEC.INI not working

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#13]
Was this keyframe speed command integrated in build may 2017? If so I've just been having trouble implement it. would it be possible for you to help me troubleshoot it?

**Comment by LeeBamberTGC** [comment]
Works fine in latest PP build. I copied the futuretek shotgun weapon a duplicate folder, renamed the folder, edited the GUNSPEC.INI inside it, added keyframe speed = 250 to the lines, then saved and ran GameGuru, dropped in a start marker and attached the new renamed gun, and when I went to Test Game, the plasma animation and retrieve animation played at 2.5 times faster than normal.
