### ISSUE TITLE
GGC tab tab visual settings broken

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#1300]
I saw a similar issue for MAX. Same goes for Classic too.  I have gameguru 2021.06.10b june fixes. In test game tab tab menu,
fog nearest = 3600
fog distance = 2000
default values are not true and when i pull it back to 100 it restores the previous wrong values again after reloading.
Didnt test other visual options

**Comment by GOR-Developer** [comment]
I have the same problem. I checked the rest, only these 2 parameters are not saved.

**Comment by MorttMedia** [comment]
I have problem with fog and settings. I do not even have a slider for fog distance.
When I write a script to set fog intensity and fog distance, the results are just over bright. Like white screen.
it says from the script fog distance is 1 million but in TAB TAB it says 1990.
None of them work.
Cant find Contrast setting either. GetContrast. or GetBrightness.

**Comment by ScorpioGames** [comment]
I have this same issue it can be fixed TEMPORARILY by clicking on the lower end of the bar an insane amount of times until it reaches 100.. but the next time you test your game i think it is back to 3000 something..

**Comment by Teabone3** [comment]
I have the same issue. A fix would be appreciated.

**Comment by Teabone3** [comment]
> 
> 
> I have this same issue it can be fixed TEMPORARILY by clicking on the lower end of the bar an insane amount of times until it reaches 100.. but the next time you test your game i think it is back to 3000 something..

I also noticed that even if you get it back under 100 it will jump to 100 immediately if you click anywhere else on the screen with the tab still open.

**Comment by plemsoft** [comment]
@sfkylcnky Thanks for reporting this issue, this has been fixed and will be in the next update :)
