### ISSUE TITLE
Grouping Items

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#1301]
When i gaet to the stage wher I need to svae my new group I cant because I don't have the save button to do so.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: X570 UD
Processor: AMD Ryzen 7 2700 Eight-Core Processor           (16 CPUs), ~3.2GHz
Memory: 32768MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2060
Dedicated Memory: 5967 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by Snage62** [comment]
Has you can see from the photos I don't have a save button to save my groups.
![Photo 1](https://user-images.githubusercontent.com/39164408/128630146-1a68eb83-437a-4574-9203-803f58a1b4cf.jpeg)
![Photo 2](https://user-images.githubusercontent.com/39164408/128630159-f5b7701d-0c63-4ba0-a35e-9ace69aed74a.jpeg)
Tot save me doing another bug report, the tiny installer is not giving me the chance to pick what I want to download, because its not there.
Up to Now Lee, you and the team are creating what could be the best and most easy gaming editor on the in the high street and it looks and feels great for the price. Keep those ideas coming and here's to the best bit to come.


Nigel

**Comment by synchromesh62** [comment]
You have to go to Settings \ Advanced settings and tick the " Additional Object Tools " to enable it.
Hope that helps
