### ISSUE TITLE
Apostrophes not displaying properly in the video description text

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1304]
In these two video descriptions;

![image](https://user-images.githubusercontent.com/1503593/128884260-cb413692-da49-4918-aea8-25b1d0179a27.png)

![image](https://user-images.githubusercontent.com/1503593/128884278-c7d2a3f2-b64b-4a11-9a88-56f4c5eb1ca8.png)

**Comment by plemsoft** [comment]
@rvanner You saved the .tut file as a UTF-8 file and not as a text file, anyway i fixed it so no need to change , but you should always save as a text file, so we dont get these strange chars :)

**Comment by rvanner** [comment]
@plemsoft These descriptions are up on Google Docs. I will have to move them to notepad!

**Comment by rvanner** [comment]
Checked and all working! Closing this issue now.
