### ISSUE TITLE
Bad and triangular shadows are seen on objects.

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#131]
Bad and triangular shadows are seen on objects.
![importing fbx files of course some objects](https://user-images.githubusercontent.com/36647058/37738232-f24c33b2-2d73-11e8-98cb-e867941a0a9c.jpg)
![snapshot25](https://user-images.githubusercontent.com/36647058/37738234-f279c76e-2d73-11e8-8a87-9291b8c7ad6b.jpg)

**Comment by Teabone3** [comment]
I've noticed this of late on some models.

**Comment by demented-mind** [comment]
There was a very large triangle shadow from a building model. If the model name is needed I'll chase it down.

![snapshot1](https://user-images.githubusercontent.com/18433764/37870638-aaa74342-2fa0-11e8-98f4-3120fc3c95c9.jpg)

**Comment by plemsoft** [comment]
Shadow bias has been fixed in the latest version from version "2018.06.16 - DirectX 11 & PBR".
