### ISSUE TITLE
Skybox Affects Interior Lighting

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1313]
BUG 2021.08.06
Skybox Affects Interior Lighting
- Skybox reflects on interiors

Expected Behavior
- Only lights should affect interior
- Reflections should not come from outside unless near windows or opening

This scene is using simulated sky
![No SkyBox](https://user-images.githubusercontent.com/12246318/129430828-aa73f93f-4afb-467d-aafa-3a3025744902.png)

This is the same scene., but with HighCloud skybox enabled - no other changes.
![HighCloud Skybox reflections on interior](https://user-images.githubusercontent.com/12246318/129430890-a4d3da19-ffb4-47d7-9cf6-9704f6fd5a5d.png)

Also interiors have to use simulated sky with lighting intensity set to 0 and Ambient Color set to black, or you will get unwanted light in the scene.

This means that you can't have levels that go from outside to inside scenes.

**Comment by PaulSJ** [comment]
Should be fixed in latest version

**Comment by OldFlak** [comment]
@PaulSJ - perhaps it would be a good idea to wait for confirmation before closing issues.

**Comment by LeeBamberTGC** [comment]
@OldFlak I have reopened :)  Let me know how it goes with today's build, thanks!

**Comment by OldFlak** [comment]
@LeeBamberTGC Thanks for looking into this
This is what I am seeing in - 2022.02.18 Wed build

Using High Cloud
![image](https://user-images.githubusercontent.com/12246318/154155954-ffa72027-5c72-4c13-b80d-0e025aab2e32.png)

![image](https://user-images.githubusercontent.com/12246318/154156451-c9c95790-cc4e-42a0-9b45-30b66030c70c.png)

Perhaps still relating to the skybox rendering over top of scene here #1852

**Comment by plemsoft** [comment]
@OldFlak This looks like a fog issue (fog opacity = 0), try playing with fog and try fog opacity , does it remove this effect ?

**Comment by OldFlak** [comment]
@plemsoft Hi Preben. Yes it is definitely related to fog it is same issue as exterior issue with skyboxes.
https://youtu.be/LK7XR8966bo

**Comment by OldFlak** [comment]
@plemsoft - Preben here is another vid using inside level.

As you can see fog affects the skybox in various ways - you can get rid of the issue but in doing so you can't use fog effectively for atmosphere if you want to stop skybox rendering over the scene.

 It effectively makes skyboxes useless..

https://youtu.be/ElUcJ4okKps

**Comment by plemsoft** [comment]
@OldFlak Could you try these shaders and let me know if it fix your issue, thanks  "remember to backup your old shaders" :)

[shaders.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8102481/shaders.zip)

**Comment by OldFlak** [comment]
@plemsoft Hi Preben, thanks :)
The zip only had CSO files, so I just replaced existing ones - is that correct?

Here be couple videos - one interior and one exterior to show results

**Interior**
https://youtu.be/jpIECC3enAM

**Exterior**
https://youtu.be/DAcC_mCUebo

**Comment by plemsoft** [comment]
@OldFlak Yes thats correct just replace :) , ahh i see - try these shaders and let me know if its ok :
[shaders-2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8103585/shaders-2.zip)
)

**Comment by OldFlak** [comment]
@plemsoft Getting there Preben

Those shaders work great for exterior levels - I can finally see distant mountains :)
https://youtu.be/FiKzncpDqyE

Still an issue with interior levels though

This level has skylights and windows to the outside world - this is one of the storerooms with not outside views
![Skybox Interference](https://user-images.githubusercontent.com/12246318/154837810-072ebd22-03eb-4c8f-95fd-40e9f1f778f5.png)

https://youtu.be/Py5q4tmTPmM

**Comment by plemsoft** [comment]
@OldFlak Thanks for getting back, i will commit what we have now , what you still see is the fact that skybox change ambience , that can be changed after you select a new skybox, so think they are ready, thanks for your help :)

**Comment by LeeBamberTGC** [comment]
@plemsoft As it seems you are working on this, I have moved the assignment of the issue to you.  I have also moved the priority of the remaining skybox issue to MEDIUM so you can focus on the HIGH items on your list.  The goal this week is for all team members to have no HIGH items left on their list. Once I finish with mine, I will help others with their HIGH items. We can then look at MEDIUMs including this one :)  @rvanner Do you agree?

**Comment by OldFlak** [comment]
2022.03.31 - As this issue is related to fog here be a couple screenshots to show where this is at

The current state is that Fog is not very good at all when using skybox.

**Fog - Great with Simulated Sky**
![image](https://user-images.githubusercontent.com/12246318/161418856-a1979a32-ca2b-4967-bd52-420ea85f9848.png)

**Fog - Rubbish with Skybox**
![image](https://user-images.githubusercontent.com/12246318/161418904-de420f5e-9a39-4d43-83e6-643765421ee5.png)

**Comment by OldFlak** [comment]
Not seeing this atm so closing
