### ISSUE TITLE
Imgae Zone - Image Flipped, Color and Aspect Ratio are Incorrect

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1314]
When using Image Zone the image:
- is flipped (left to right)
- color is not correct
- aspect ratio of image is not correct - image is squashed up

One of MAX's logos looks like this in test-game
![ImageZone Bugs](https://user-images.githubusercontent.com/12246318/129431151-912f06a0-ae2f-400b-8608-9f0ad13208c5.png)

Also the image zone seams pointless to me - needs more options to make it useful.
The ability to choose how it gets displayed
- fade in
- start small grow to full size

How it gets removed
- Fade out
- move off screen, to top of screen for example as it fades out

Show in zone
- on first entry
- on every entry

Just suggestions of course, but can't really see how useful it would be in a game as it is :)

**Comment by 3coms** [comment]
![Imagezone_image_ok_GGMax_2021_08_06_pic01](https://user-images.githubusercontent.com/47690174/129446590-ea02a171-2986-4173-bb6b-a321f08e3696.png)

![Imagezone_image_flipped_GGMax_2021_08_06_pic01](https://user-images.githubusercontent.com/47690174/129446620-ac2b77b5-6858-4064-a349-3a5e1e403389.png)

That's a good reason to give us the most control over imagezone, no just to choose one image GGMax has on the image Lib.
Imagezone needs the control and LUA support, GG has.
We need to be able to control the size, angle, position, etc.

**Comment by rvanner** [comment]
Working but there are still issues with how MAX displays images (will report in a new thread)

**Comment by plemsoft** [comment]
@michaeloldman This has been fixed and will be in the next update :)
