### ISSUE TITLE
Particles - Not the Same as ones created  in PE

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1316]
BUG 2021.07.30
Particles not same as ones created in PE
- Some particles are not the same in MAX as those created in Particle Editor
- in following example, both shape and colors are wrong

PE Version:
https://vimeo.com/581914784

MAX Version:
https://vimeo.com/581914274

**Comment by rvanner** [comment]
@michaeloldman Can you share the particle file that was exported?

**Comment by michaeloldman** [comment]
Here yah go Rick
[Particle.zip](https://github.com/TheGameCreators/GameGuruRepo/files/6986580/Particle.zip)

Pretty much any flat particle (like portals) from the stock ones in PE will not work correctly in MAX, same with many of the ball types as well.

**Comment by OldFlak** [comment]
This is fixed atm so closing :)
