### ISSUE TITLE
Jungle Assets need removing

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1317]
These two should be removed, they are spelled wrong and duplicated of the new versions;

![image](https://user-images.githubusercontent.com/1503593/129439303-a6cd0054-10fd-47c0-b1a6-c146f7a0c3d9.png)

![image](https://user-images.githubusercontent.com/1503593/129439306-53d643dc-9c27-4996-b7bb-93c57f19a98a.png)

**Comment by plemsoft** [comment]
@LeeBamberTGC Jungle Collection - Delete files - "Leafy Vine Tendrail" , "Vine Tendrail".
