### ISSUE TITLE
Making the particle marker bigger [GGMax - Request]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1319]
Please, can you make the particle marker bigger? it is a pain to work with, when in between on a bunch of other meshes?
Thanks in advance
3com

**Comment by rvanner** [comment]
@bond1mjb I think it might better to change the particle marker into a semi-transparent sphere. It can be hard to pick up and move it with the three rings because you can end up clicking through it.

**Comment by bond1mjb** [comment]
@rvanner  Here is a new particle marker keeping the 3 ring style but with a center sphere for easier selection.
![particle marker new](https://user-images.githubusercontent.com/87768878/129969459-06744690-03c9-4268-bfd8-1435f42234db.jpg)
[particles.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7010086/particles.zip)

**Comment by 3coms** [comment]
The problem with the particle marker is the particle itself, it covers the marker, so you even can see it, and you have to get closest to the marker, if we add the neighbor meshes, plus other effects, it all becomes too difficult.
Any way you can disable the animation and stick just with the marker.
Your marker might be a good way to go. :)

As a side note, when you try to rotate the particle, the marker rotates, but the particle keeps static, it does no move.

**Comment by bond1mjb** [comment]
Attached is a second variation that has the center sphere, but also wider rings that hopefully won't get obscured by the particle itself.   Looks like an atom:)


![particle marker side](https://user-images.githubusercontent.com/87768878/129971563-0b3453bf-43be-425c-a6dd-1e6c0b039476.jpg)
[particleswide.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7010141/particleswide.zip)

**Comment by 3coms** [comment]
Hopefully, Lee includes your _atom_ in the next updates. :)
Well done!

**Comment by synchromesh62** [comment]
Was there a reason it changed from the original blue one?
I thought that looked pretty cool to be honest :)

**Comment by 3coms** [comment]
Here ya go.

[Particle marker.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7010853/Particle.marker.zip)

![particle_marker_pic01](https://user-images.githubusercontent.com/47690174/129988014-35f43262-66e3-40ca-b3e3-636b8c0c1572.png)

**Comment by 3coms** [comment]
Forget to mention that the mesh has an emissive texture, so, you can use it as you need.

**Comment by rvanner** [comment]
@bond1mjb Thanks!
