### ISSUE TITLE
Images do not display in game as expected

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1323]
This image file;
![image](https://user-images.githubusercontent.com/1503593/130200248-4621760e-8b2f-4770-89c3-23d50e3fdbb9.png)

Shows up in game like this;
![image](https://user-images.githubusercontent.com/1503593/130200276-3e2ba224-03dd-471f-8550-4a1bf07f7f50.png)

- The colours are all wrong
- The aspect ratio is not respected

**Comment by rvanner** [comment]
And it looks to be reversed. So maybe that previous bug is still present.

**Comment by rvanner** [comment]
I also made two image zones, only the first one would show in game.

**Comment by plemsoft** [comment]
Fixed.

**Comment by rvanner** [comment]
Fixed in latest version. Closing this issue.
