### ISSUE TITLE
Structure editor gizmo displays in game test mode. 

### ISSUE THREAD

**Issue by cstriage13** [TheGameCreators/GameGuruRepo#1324]
This image should be self-explanatory, Tis a little issue when ever you guys have time.
![Screenshot 2021-08-20 060027](https://user-images.githubusercontent.com/84180614/130224426-857e17f7-57a7-4853-a356-98a3403b2cb8.png)

**Comment by plemsoft** [comment]
@cstriage13 Thanks for reporting this issue, this has been fixed and will be in the next update :)
