### ISSUE TITLE
Problem With GameGuru Max Installation

### ISSUE THREAD

**Issue by henoida** [TheGameCreators/GameGuruRepo#1325]
Hi;

I purchased the pre-release version of GameGuru Max today. I received an email with a link to download the installation file "GameGuruMaxTinyInstaller.exe"

Upon execution, it appears to be installing the program but then the 'update' window pops up with many options to download.  I've tried all selected... I've tried only the core files selected, and every conceivable combination thereof and I keep getting an error message
"Failed to parse file list, please try again (error code 4: User does not own product!)

I'm running a 10th generation i7 2.90 GH CPU with 16 GB of ram on Windows 10 Home 64 bit 
During installation, I opted to use an alternate installation path... could this be the issue?  Please advise

**Comment by Granada1** [comment]
Might be good to wait a while , everyone will be trying to download . It will work 👍

**Comment by ZakJudges** [comment]
Hi @henoida 
Are you still receiving this error message?

**Comment by henoida** [comment]
Yes, I am.


    On Monday, August 23, 2021, 05:40:49 a.m. ADT, ZakJudges ***@***.***> wrote:  
 
 


Hi @henoida
Are you still receiving this error message?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZakJudges** [comment]
@henoida I recommend visiting https://www.thegamecreators.com/account/order/list and checking that you have no problems logging in and viewing your order for GameGuru MAX.
Then try a clean install by removing the software and downloading "GameGuru MAX Tiny Installer.exe" from https://www.thegamecreators.com/account/product/list

Once downloaded, you can log into your account from the installer and attempt the download process again. If you encounter any more issues then just reply to this comment. Thanks.

**Comment by henoida** [comment]
My order is not listed on the order list page.  
I have two email accounts. My 'gmail' account is listed in my  member profile ***@***.***), but I think I may have used my 'rogers' account to purchase GameGuru Max ***@***.***).  
I'm thinking that this is probably where things have gone wrong.
Sales transaction # is TGC7CB0CEBD6

    On Monday, August 23, 2021, 09:54:00 a.m. ADT, ZakJudges ***@***.***> wrote:  
 
 


@henoida I recommend visiting https://www.thegamecreators.com/account/order/list and checking that you have no problems logging in and viewing your order for GameGuru MAX.
Then try a clean install by removing the software and downloading "GameGuru MAX Tiny Installer.exe" from https://www.thegamecreators.com/account/product/list

Once downloaded, you can log into your account from the installer and attempt the download process again. If you encounter any more issues then just reply to this comment. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZakJudges** [comment]
@henoida Yes that will most likely be the problem. Are you able to log into your other account?

**Comment by henoida** [comment]
No, I can't even remember the user name for the other account, only that it uses my ***@***.*** email address. Sorry.




    On Monday, August 23, 2021, 10:19:03 a.m. ADT, ZakJudges ***@***.***> wrote:  
 
 


@henoida Yes that will most likely be the problem. Are you able to log into your other account?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZakJudges** [comment]
@henoida In that case, you could visit https://www.thegamecreators.com/ 
From there, you can click the green help button in the bottom right of the screen to contact TGC and get help accessing your account that you made the purchase from.

![techsupport](https://user-images.githubusercontent.com/32545391/130494988-8c793130-7fea-4574-af0f-2edbc9a9c0c9.png)
