### ISSUE TITLE
GameGuru Max 2021.08.20 update: zombie_attack.byc won't download

### ISSUE THREAD

**Issue by rsearle** [TheGameCreators/GameGuruRepo#1326]
Version 2021.08.20 file zombie_attack.byc download hangs. Version update stalled with 7 files to go.

**Comment by rvanner** [comment]
@rsearle Hi, we're about to enter a month of testing. Is this still an issue for you?

**Comment by rvanner** [comment]
@rsearle Is this still an issue for you? Please respond so I can assign this to a team member. Thanks.

**Comment by rvanner** [comment]
Closing this now. Sounds like a very old and out of date issue.
