### ISSUE TITLE
2021.08.20 - Character Lighting

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1327]
BUG 2021.08.20
Character Lighting
- Characters don't have uniform lighting
- Looks like the face has been grafted on

![Untitled](https://user-images.githubusercontent.com/12246318/130356041-c8dcb1f9-5436-455d-876b-adb6ba9c6265.png)

**Comment by rvanner** [comment]
@michaeloldman Was this a model from the core library or one you made? The core library characters all need to be re-made. There's a system the matches the chosen skin color and this is gone wrong on this old character.

**Comment by michaeloldman** [comment]
@rvanner Yes it must be an old character then.
The one in screenie is **Sue - Military Contractor** from the library. 
Apart from the few with masks on, they all show obvious lines where the head joins the neck, even the ones that look like the colors are correctly chosen. The light angle shows it up more at certain angles.

Not sure how you would fix it thou. Maybe they all should have collars, or a necklace, etc, where the head joins are to hide it more. Which of course means the neck would have to be part of the head.
