### ISSUE TITLE
2021.08.20 - Element Icons Render Issue

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1329]
BUG 2021.08.20
Element Icons Render Issue
- Element icons now have dots in corners

![elements icons dots](https://user-images.githubusercontent.com/12246318/130356150-428a34e0-a713-447a-a665-3e9a94593fa2.png)

**Comment by rvanner** [comment]
This will be fixed in the next build. There was no alpha in these pngs last time.

**Comment by plemsoft** [comment]
Fixed

**Comment by rvanner** [comment]
Fixed in latest version so closing this issue now.
