### ISSUE TITLE
Shader - Water Surface Bottom

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#133]
I've been making some progress with a modification to the player global controls script that allows for the player the enter water without instantly dying. Everything is going perfectly as expected so far, however but for one thing. Once the player is submerged under water the water shader surface appears to only display the last reflection the the player saw before entering the water.

You can see more of what I'm talking about if you preview the videos found in the thread below:

https://forum.game-guru.com/thread/219463

**Comment by plemsoft** [comment]
This was fixed in the latest PP :)
