### ISSUE TITLE
2021.08.20 - Current Tiny Installer

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1330]
BUG 2021
Current Tiny Installer (downloaded yesterday)
- Tiny Installer informs that it will delete all files in Program Files several times during install process (every time it starts to download a given Pack?)
- This means you have to sit and watch the whole download process as it won't proceed unless you click OK
- for my install that's like two hours keeping eye on the process

Expected behavior
- Ask once at start
- and complete the install unattended

**Comment by rvanner** [comment]
It's a good point! We'll add a flag to note that it's been agreed to.

**Comment by ZakJudges** [comment]
@michaeloldman This should be fixed now. However, I have not experienced this bug, so if it happens again after the next update please let me know. Thanks :)

**Comment by rvanner** [comment]
@LeeBamberTGC Can you roll out a new version of the Tiny Installer so we can check this is now fixed?
