### ISSUE TITLE
2021.07.30 - Animations Too Slow

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1332]
BUG 2021.07.30 - Also present in 2021.08.20
Animations Too Slow
- Animations are slower than in previous build

https://vimeo.com/582059893

The animations for open and close for this force-field happen over 2 frames each.
- so you should barely be able to see it happening
- but max is playing the animations more like they have 10 frames or more for each action

**Comment by LeeBamberTGC** [comment]
Animation speed now correctly paced based on frame rate (and not double frame rate as was calculated before).
