### ISSUE TITLE
When Importing an Object if you set the scale above 200 it will not have any collision. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1337]
Import a wall and in import settings set to static and Collision to Box. Set scale to 300. 

Then drop into level and you will see object will act as if it has no collision. 

Also just like to point out this is issue number 1337. Which is pretty cool :) 

Edit- ***
After more testing it seems if you import an object and then later edit the FPE file and set scale to 300 it will also lose its box collision.

**Comment by Kitakazi** [comment]
Tested on multiple floors and walls. Have not tested with other collision options, only Box.

**Comment by ZakJudges** [comment]
@Kitakazi Thanks for the information. I've imported an object and scaled it to large proportions. When debugging the physics, everything looks okay and the physics continue to function on my end. Are you overlapping any of the scaled objects? This could potentially cause unwanted behaviour at the start of the game.
If this isn't the case, could you send a video and an object that is causing the bug? Thanks :)

**Comment by Kitakazi** [comment]
[Wall_Red.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7097138/Wall_Red.zip)

**Comment by ZakJudges** [comment]
@Kitakazi Thank you for the model and video. I have confirmed the issue you are experiencing. Looking into it soon :)

**Comment by Kitakazi** [comment]
this has been fixed.
