### ISSUE TITLE
GameGuru Classic - Ammo, Keys, and Doors in third person

### ISSUE THREAD

**Issue by Belidos3D** [TheGameCreators/GameGuruRepo#1338]
There has been an issue with ammo and key pickups, and door scripts in third person for quite some time, i managed to narrow it down to the way that GameGuru Classic detects distance and angle from an object in those scripts, i rewrote them for third person when i created my isometric dungeon kit. 

If you want those new scripts to add to GameGuru Classic you are more than welcome to download them and use them, you can find them attached to my post on the forums ...

https://forum.game-guru.com/thread/222965#msg2643094

**Comment by rvanner** [comment]
@plemsoft Please consider updating these when you work on GGC

**Comment by plemsoft** [comment]
@Belidos3D Thanks for the support , i checked the latest version and it looks like third person are able to open doors and pickup keys with no angle problems , it was not able to pickup ammo , so i added support for that , thanks for your scripts :)
