### ISSUE TITLE
Jagged shadows if slider is above 10

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#134]
As anyone noticed the jagged shadows it is worse if the slider is above 10 
https://youtu.be/313E96Uul7U

**Comment by GraPhiX-Guru** [comment]
here is another video showing the issue, also look at the red seat not sure what's going on with the normals there https://youtu.be/U6n_YJebeEg

**Comment by plemsoft** [comment]
This should be way better in the latest PP , could you retest this and let me know if we can close this :)

**Comment by GraPhiX-Guru** [comment]
Yes its a lot better thank you :)

**Comment by plemsoft** [comment]
Thats great news , the rest of your flickering problems will be solved with the DX11 depth buffer fix :)
