### ISSUE TITLE
Zombie does not respect gravity

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1340]
I wanted to see what would happen if the Zombie was high up above the terrain and should be following a way point. He tried to walk into thin air and then turned back. He really should drop down to continue his journey.
![image](https://user-images.githubusercontent.com/1503593/130590814-054e292d-100b-48f9-be99-1dcfe2cfab27.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Please attach an FPM and steps to see this for myself, thanks.

**Comment by rvanner** [comment]
I'll close this now. It's very old and we'll test Zombies again.
