### ISSUE TITLE
Rotated wall piece was ignored by the AI system, the zombie walked through it

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1342]
As you can see, the Zombie just walks through this static geometry:

![image](https://user-images.githubusercontent.com/1503593/130592994-19f0799b-f055-4242-aad7-a515ee9edcf3.png)

Even with the wall moved more into the terrain he still walked through it;
![image](https://user-images.githubusercontent.com/1503593/130593455-50725b5e-f6e4-444d-87cd-40ade08728f5.png)

**Comment by rvanner** [comment]
I scaled the wall up some more and then it worked. Is there a size limit on ground obstacles?

![image](https://user-images.githubusercontent.com/1503593/130593695-718ddb44-137d-42dd-bcf3-2c4b63adca6d.png)

**Comment by LeeBamberTGC** [comment]
Fixed for next build
