### ISSUE TITLE
GGC Issue: Start Marker Rotation by Widget Not Working

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1348]
If you rotate the start marker once. Then test. Then rotate it again to the lower right view and place a barrel in front of it, when you test game you will not see the barrel in view. Its almost as if the start marker didn't rotate that second time at all, though appearing to have within the editor.

![not in view](https://user-images.githubusercontent.com/35990109/130829542-9624554e-1700-418f-bee8-d560622962ae.JPG)
![nobarrel](https://user-images.githubusercontent.com/35990109/130829818-d9179ca3-c18d-4a32-b1e3-27a8a3ce05ac.jpg)

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed and will be in the next update :)
