### ISSUE TITLE
fun with zombies

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1349]
Zombie behavior works great with one zombie, but put a few together and something goes wrong:

1. First of all they move _synchronized_ which is funny and a but creepy but not what you want.
2. The trigger doesn't work. They attack when you are not in reach or don't attack when you are.
3. You can kill them but they don't fall but freeze (by the way grenades lose their texture when you you throw them). That you can kill them is fine but is not part of the behavior. Maybe there should be an interrupt/trigger system like "if shot go to", "if loud sound move towards it" , "if hit and hit is turn undead spell move away" or "if stuck stop moving".

**Stinking zombie**
I tried to make a stinking zombie, a smart object with a zombie and a particle emitter emitting a green cloud. But the emitter doesn't move with the zombie. (behavior is not save correctly in smart object)

**spitting zombie**
The same smart object with a spitting particle. Zombie hits left, right and then spit some disgusting particles. The make that possible it should be possible to have two objects in an behavior, hit left hit right and start particle wait stop particle hit left hit right etc.

Maybe a message system between behaviors would be nice if shot fired send message, if message interrupt zombie and move to sound.

**Comment by LeeBamberTGC** [comment]
@smmaas Many zombie improvements in this Fridays build.  Please check your issue to see all has been fixed:

![image](https://user-images.githubusercontent.com/35840583/154491929-5454c54a-dd39-4b88-a579-40dd8293337e.png)

Zombies now start at different times and modulate their speeds between MIN and MAX so they never sync, and also added different walks for the zombies so they can be totally different when in a group.

Zombies now also see and hear you at the right times, and will use either death anim or ragdoll based on the scene around them, and a special fall over and get up if you don't quite kill them enough :)

**Comment by ZakJudges** [comment]
Works fine in latest build
