### ISSUE TITLE
Lightmapping problem.

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#135]
After posting on the forum in some detail about some faces becoming solid black after lighmapping Preben has discovered what the problem is, here is what he posted in the reply.

"static_basic.fx - hudfogresult.rgb = normalize(IN.WorldNormal).rgb;

The normals is wrong in the lm dbo files. ( only for some objects )."

It is beyond me and Preben is going away for a well earned break so I posted the issue here as advised.
![untitled](https://user-images.githubusercontent.com/36109432/37864065-35de3bc2-2f61-11e8-9534-fed5b576423d.png)

**Comment by LeeBamberTGC** [comment]
Can you attach the model that the above screenshot shows, and I can take a closer look, thanks!  Just post here and then email me at lee@thegamecreators.com so I know its arrived right away :)

**Comment by BodRH** [comment]
Preben took that screen shot, I'm not sure which model he used but I have one very similar in my free 
models thread which does exactly the same (attached).

[dhouse.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1851072/dhouse.zip)

**Comment by Belidos3D** [comment]
This looks to be exactly the same issue i reported in the first DX11 beta, which i sent you a whole level including all my models to look at Lee. For some reason certain models do not lightmap and show up as pure black on the side not facing the sun, it happens with a lot of the stock models too.

**Comment by BodRH** [comment]
The strange thing is that they lightmap fine if you rotate them, even if you rotate them all the way back to their original position after first running lighmapping then lightmap again.

**Comment by Belidos3D** [comment]
Yes, it's to do with the direction of the sun, it's always the face of the model that does not receive any light fro the sun.

**Comment by BodRH** [comment]
I understand that but not how it lightmaps fine on all surfaces when rotated.

**Comment by Belidos3D** [comment]
I have no idea, i'm just adding my experience to yours so lee has more information at hand :)

**Comment by plemsoft** [comment]
Lee:
You can test using \CityscapePBR\Concrete Cylinder

![lmerror](https://user-images.githubusercontent.com/18662417/38305789-72337352-380e-11e8-9c8f-6e75724d3cd0.jpg)

**Comment by LeeBamberTGC** [comment]
Looks like a fix at the start of 2017 on the lightmapper exchanged the correct normals with the original ones but did not account for the way the lightmapper applies the final LM calculation to the finished result. Now restored to the original design, though I believe the lightmapper is due a serious update (or even swapping out for something more formidable from third party land).  Issue solved for next update.
