### ISSUE TITLE
Detailed Object List does not turn off once it's turned on

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1350]
Having turned this feature on, you cannot turn it off.

Also, remove the full stop at the end of the line in settings

![image](https://user-images.githubusercontent.com/1503593/130948988-70205133-92e0-4bb1-ab5d-afc77f859440.png)

**Comment by plemsoft** [comment]
Fixed :)

**Comment by rvanner** [comment]
Fixed!
