### ISSUE TITLE
Behaviour

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#1356]
![image](https://user-images.githubusercontent.com/89519185/131216306-920bc0dd-7e66-49c8-944a-ba1915876a12.png)
when adding a new behavior, it is impossible to close the window on the cross

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Where can I find the Behaviour Editor? When I create a new behaviour these windows are not popping up.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Select the AI from the Developer Mode settings panel, and they will appear when you go to TEST LEVEL
