### ISSUE TITLE
GGC Issue: Fog Nearest

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1357]
"Fog Nearest" is default to an absurdly large value. Well over 1000. 

Might be related to #1300

**Comment by rvanner** [comment]
Fog will be reviewed when the new terrain system is in place.

**Comment by michaeloldman** [comment]
Not seeing that - Think it is a Classic issue not MAX?

**Comment by rvanner** [comment]
@michaeloldman Thanks for the clarification!

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed and will be in the next update :)
