### ISSUE TITLE
Need a super-high resolution Shadow solver for micro-details on models (i.e. less than 5 unit geometry detail)

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1358]
Shadows are much improved from previous builds but still create weird visuals in some areas.

This pic shows a part of a model where no lights are casting shadows (the way it should look): 
![shadow a](https://user-images.githubusercontent.com/12246318/131270217-af1694a4-1d52-40a7-ad00-37f63c766d49.png)

This shows the same part of the model in area where light source is casting shadow - creating weird effect:
![shadow b](https://user-images.githubusercontent.com/12246318/131270258-aceb9b04-e88b-4a1f-9fea-35f55af89997.png)

This shows the same part of the model in area where light source is casting shadow - but with torch as further reference:
![shadow c](https://user-images.githubusercontent.com/12246318/131270323-d5c2934e-818f-47d9-9264-bd85447c3669.png)

You get similar effects on ceiling and wall areas where the geometry is a tad higher than the surrounding flat geometry.
Another Example:
![shadow d](https://user-images.githubusercontent.com/12246318/131270869-f0efb411-259b-4cd5-a536-bd2ffe08a9d0.png)

**Comment by casigus** [comment]
these are very minor issues. like.....really, a bit of shadow not shadowwy? I personally dont see anything wrong here.

**Comment by plemsoft** [comment]
@OldFlak Try increasing the resolution of the shadow map, you can do this be lowering the "sun shadow distance".
Try that and see if any setting is working for you :)

![shadowresolution](https://user-images.githubusercontent.com/18662417/137484087-6e574ba0-6003-433b-967d-ca4fa1ae0409.jpg)

**Comment by OldFlak** [comment]
@plemsoft yes , have played a bit with those settings, and doesn't change it
![2021 10 16 - shadow issues - 02](https://user-images.githubusercontent.com/12246318/137484884-14a1a2c4-745c-496b-bc4c-4269e0e7e9d7.png)

also tried changing **Spot and Cascade to 1024**, and **Point Lights to 2048**, can't have both at 2048, max goes into a fit and changes it back.

**Comment by OldFlak** [comment]
This is much worse in current EXP build - with or without MSAO enabled
![image](https://user-images.githubusercontent.com/12246318/165744140-8827cb1c-5be2-43d8-9a9d-b90ec9fef087.png)

Changing to 1024 helps marginally in some places but still very noticeable :)

**Comment by OldFlak** [comment]
Some more feedback: 

The shadows behave badly when at default settings. 
In this scene the Point Light above the sphere is using the Flame Light script:
![image](https://user-images.githubusercontent.com/12246318/165870116-67f623d5-03fa-4f1f-9643-c17fe03b9adf.png)

As you can see in the video the effect on the ceiling is not good:
https://youtu.be/OVZTYUENouE

Changing the shadow quality improves it nicely - although a tad noticeable still - it is passable to me. 
The main problem here is MAX does not remember the Shadow settings.

This has only just been introduced as I have not noticed it in previous builds. Again same thing with or without MSAO enabled.

**Comment by plemsoft** [comment]
@OldFlak It will now remember your Shadow settings, this fix did not go into the Friday build (i was to slow for the deadline) so you have to wait until the next EXP in a few days :)

**Comment by OldFlak** [comment]
Thanks Preben :)

**Comment by OldFlak** [comment]
High team -thanks for all your hard work and an ever increasingly great engine!

FYI - I left this bug open as the original issue with shadows is not completely fixed. You can still easily get incorrect shadow effects.
Here is a shot taken two minutes ago:

![image](https://user-images.githubusercontent.com/12246318/170227483-09c6fc66-86ba-4b2b-995d-0fa8ba91425c.png)

Using Steam version here :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Any chance you can send me just this one model and maybe an FPM with the start marker facing this. That way I can see the issue, and your shadow settings, etc.  From there, I can get a handle on a fix for you.  Thanks!

**Comment by OldFlak** [comment]
Hi Lee,
Sorry for late reply – just got back from short holiday (waaayy too shot!)

Here is a link to a test level for you.
https://www.dropbox.com/s/47vglbh04pufahr/MAX%20ShadowIssue.zip?dl=0

Please note the level only uses a few of the models in the folder but since it is not that huge I just included all of them - easier than sorting out the unused ones 😊

The level uses the same fog, sky, and lighting settings as in my game level.
The start maker points you to the area as shown in the pic on GitHub, but if you wander around you can see issues in other areas, for example the issue is very noticeable along the path edges.

Hope it helps you sort it if possible.

Thanks for great work, awesome engine, and putting up with my plethora of reports!

Regards
Michael

**Comment by LeeBamberTGC** [comment]
@OldFlak Seems we are too aggressive in our optimization here. The point shadows where using 16 bit resolution for the depth buffer which causes vague shadows at distance. I have changed to 32 bit depth buffers so they match  spot and directional., let me know if this hurts your game project performance.  Fixed for Fridays build.

**Comment by OldFlak** [comment]
Hi Lee - great work - much better!

Still seeing a slight jaggie effect on shadows cast from geometry that is on an angle.
But certainly much better - and doesn't seem to affect fps that much even at 2048, although that may be different on complex scenes.

Some feedback shots fro you:

Points at 512:
![Shadow 512](https://user-images.githubusercontent.com/12246318/174420663-59dfa363-6251-413d-b4be-0f10ade01fd5.png)

Points at 1024:
![Shadow 1024](https://user-images.githubusercontent.com/12246318/174420669-86a7e226-2977-4012-8618-3f914a81b24d.png)

Points at 2048:
![Shadow 2048](https://user-images.githubusercontent.com/12246318/174420679-923685cd-fb1e-40a1-bbd8-368b0f216f38.png)

----

Still seeing the same issue on some areas as posted in OP
![image](https://user-images.githubusercontent.com/12246318/174420748-01e49f88-a9c0-47f8-9541-dd4f1d682e40.png)

----

But overall - tons better than before :)

**Comment by LeeBamberTGC** [comment]
@OldFlak I think to get that level of shadow detail we probably need secondary bespoke shadow maps to target details that are lower than 5 units thick (the typical minimum for casting shadows with the current system).  I was thinking this was needed for character faces, but I think there are numerous areas in a game level where you need this level of quality.

**Comment by OldFlak** [comment]
@LeeBamberTGC Hi Lee, thanks for looking at this.

That would explain the reason little edges also cause artifacts on some geometry as well.

In this level the shadows are not too bad even at 512, but (as marked with the arrow) little edges do not quite get it right.
![image](https://user-images.githubusercontent.com/12246318/174916824-7c836c65-121f-44bf-a1d2-a19f013ccf28.png)

Changing up to 2048 makes no difference here.
That said it seems acceptable to me for the most part - but look forward to greater detail in the future.

MAX looks pretty darn good tho - great work by all the team!
