### ISSUE TITLE
Character Behavior LUA errors 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1360]
Get the error that is in screenshot when trying to Test Game with a character and the patrol.lua

![image](https://user-images.githubusercontent.com/51464873/131447269-79f37b12-b381-4c71-937b-efc09c6db7ef.png)

Using zombieattack.lua gives me this error -

![image](https://user-images.githubusercontent.com/51464873/131447404-4863ead2-b75e-4dab-a91b-294528e80c01.png)

**Comment by rvanner** [comment]
@Kitakazi Max or Classic?

**Comment by Kitakazi** [comment]
Max

**Comment by LeeBamberTGC** [comment]
Can you send me your "global.lua" file that is located next to the "masterinterpreter.lua" file, thanks!
