### ISSUE TITLE
GGmax still applying AO texture instead of Normal texture.

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1361]
**What I did**
1- Place my mesh on the map
2- The looks are far to be as expected, so I noticed in material settings that there is AO setup rather than the Normal material.
3- All the materials are named like the first one, so, all they now are "hell_path 01, hell_path 02, 03, and so on" so, too difficult to know who is who there.
4- I've tried to set up the normal material from my folder, GGMax refuses to write the material path in the right way, it keeps placing the "markers" folder on the path, where it has nothing to do with markers.
(please refer to the pic below - red arrows)
5- I've tried to remove the path manually, but it appears again, it is like a fixed path, and there is nothing you can do. 

![Wrong_textures_ao_rather_normal_GGMax_2021_08_27_pic01](https://user-images.githubusercontent.com/47690174/131524310-36b97605-2005-4e97-8917-c2745b155bf5.png)

And trust, it has nothing to do with my mesh, it is happening from a long time ago, with different meshes, as well. :)

**Comment by 3coms** [comment]
I must add, each time I try to change the path, GGMax increases the numeric prefix added, i.e. _normal1.png_, the next time: _normal2.png_, and the last time as shown on the pic above: _normal3.png_, when the real name is just "_normal.png_"

**Comment by 3coms** [comment]
Notice the expected look of the mesh, this is an Assimp shot.

![the_hell_Assimp_pic01](https://user-images.githubusercontent.com/47690174/131528204-3aaeb4ec-3881-4652-bba6-b47e755ff57f.png)

**Comment by 3coms** [comment]
I've tried again, and now GGMax included "vegbank" in the _Normal_ file path.

![Wrong_textures_ao_rather_normal_GGMax_2021_08_27_pic03](https://user-images.githubusercontent.com/47690174/131535034-bf4c6523-94bf-48b3-ad52-5222f7d19a13.png)

**Comment by ZakJudges** [comment]
@3coms Does this also occur when importing models? Or only in Object Tools? Thanks :)

**Comment by 3coms** [comment]
@ZakJudges 

![hell_gate_GGMax_2021_08_27_Pic02a](https://user-images.githubusercontent.com/47690174/132244770-1dbaeef9-55c0-4671-97c6-a0d517203f36.png)

Notice that sort of cliff (green arrow), so, that formation is the result of importing the mesh (this is only 1 mesh).
GGMax manage to make a rock formation with my mesh, so, what I did?
I place the rock formation in the scene. (taking something good from something bad) LOL

**Comment by ZakJudges** [comment]
Hi @3coms, does this still happen to you in the latest build? :)

**Comment by 3coms** [comment]
@ZakJudges 
Hi
Fortunately, it does no longer happen in the latest builds, so, I gonna close this one. :)
