### ISSUE TITLE
GGC Issue - Ally Imp Stays Dead After Test Mode

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1365]
If you the ally imp ever gets killed (or if you kill it) it will remain dead after you exit the Test Mode. It will also appear dead in the editor window as well. During your next Test it will also stay dead on the ground.

Temporary work around fix is to click on the dead ally imp in the editor and enter its properties panel. This seems to undo the ragdoll and restore the imps health.

![deadim](https://user-images.githubusercontent.com/35990109/131945921-0642a969-cbfb-42b3-b6fc-19a2b086fb30.JPG)

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed and will be in the next update :)
