### ISSUE TITLE
GGC Issue: Red Dragon Mesh Warped

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1366]
When the red dragon enters its flying animation , its mesh starts to warp , extending its limbs. 

![dragon_wraped](https://user-images.githubusercontent.com/35990109/131947076-08dc4031-e41f-4d66-8d19-59455f9038fb.jpg)

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed and will be in the next update :)
