### ISSUE TITLE
GGMax Issue: Import animated GTLF

### ISSUE THREAD

**Issue by MajesticGames** [TheGameCreators/GameGuruRepo#1367]
I have created a simple geometry (door) with an armature with two bones in blender. One of the bones move the door from the edge (this bone doesn't deform the geometry). This model is exported using GTLF export module of blender.

When I import the GLTF in GG Max, the frame of the door, the door and the most important... the animation are rotated... the door is not rotated in Y axis otherwise X axis. (you can see the next video)

https://user-images.githubusercontent.com/33732701/131957156-96c0d3df-1364-4a1c-add2-9bf4f94d2f9a.mp4

**Comment by Duchenkuke** [comment]
the title says gameguru classic (GGC) Why does this get assigend to gg max ? @Mods Please label the reports properly.

**Comment by MajesticGames** [comment]
Sorry, it's my first post and I made a mistake. The problem is with Max. 
Thank you.

**Comment by synchromesh62** [comment]
@Duchenkuke 
Does classic even import GLTF ? 
I dont think so ? ... I would have assumed it was Max as well

**Comment by Duchenkuke** [comment]
well now it says gg max in the title... wtf ?? so It was a mistake by the poster actually

**Comment by MajesticGames** [comment]
I change the title, because I had made a mistake. I am sorry for any confusión this may have causes.

**Comment by Duchenkuke** [comment]
okay^^ no worries
