### ISSUE TITLE
Bounding box incorrect size calculation

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1368]
When importing an object with a position and rotation offset, the resulting bounding box is too large for the object.

![boundingboxbug](https://user-images.githubusercontent.com/32545391/131975625-ecbf8ff7-cc35-47a5-9145-440aa8761a00.png)

**Comment by GraPhiX-Guru** [comment]
the order of rotations matters (expect if you rotate around the same axis then you can add or substitute the angles). Also i think the order of transformation matters: if you first do translation and then rotation, you may get different results as if you first rotate and then do a translation.

I Usually first scale, then rotate and finally translate.

I may be barking up the wrong tree but i had a similar issue with my Application.

**Comment by ZakJudges** [comment]
@GraPhiX-Guru yes turns out I was applying rotations needlessly. Thanks :)

**Comment by GraPhiX-Guru** [comment]
You are Welcome, glad you sorted it :)
