### ISSUE TITLE
If Illumination (and _i) maps are a different resolution than the color/etc. map, the game is treating them as detail maps.

### ISSUE THREAD

**Issue by MadLobsterWorkshop** [TheGameCreators/GameGuruRepo#137]
Noticed this while testing some of my items in the preview. Moving close to one of these items causes the item to go all black except for a tiling pattern of the illumination map.

**Comment by Pirate-Myke** [comment]
Not seeing that with my test I just ran. Would you like to post one for testing?
https://puu.sh/zRENY/422ef96f68.jpg
https://puu.sh/zREOs/f217d12ff2.jpg
https://puu.sh/zREOD/588045d8ea.jpg

**Comment by plemsoft** [comment]
Ahh i see what you mean, try to rename your "_i.dds" to "_illumination.dds" , that should fix it. Let me know if this fix your problem, so we can get it into the code :) Thanks.

**Comment by LeeBamberTGC** [comment]
Fixed in current live version in that _I textures no longer override the reflection texture (but still works for legacy PBROVERRIDE=0 legacy mode).  Only _CUBE texture can now override the PBR automatic reflection mapping.
