### ISSUE TITLE
Can't delete unwanted imported models

### ISSUE THREAD

**Issue by ivanski1983** [TheGameCreators/GameGuruRepo#1370]
I imported a model and selected the wrong collision style. I went the the default /user folder path in the entity bank and the folder is empty. Am I missing something? 

TIA

**Comment by Kitakazi** [comment]
Probably went to wrong folder there is a GameGuruApps>GameGuruMax folder and just a GameGuruMax folder. Check both of those?

**Comment by rvanner** [comment]
@ZakJudges Please add a way for users to change the collision style within the object tools menu. Ask Preben if you need guidance.

**Comment by ZakJudges** [comment]
@rvanner Will do!
