### ISSUE TITLE
GGC Issue: Death by Explosive Barrel Freezes Game

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1372]
If you place an explosive barrel on the map and shoot it at close distance, the player will become locked and the screen will remain red. Additionally the player will not respawn to the start location. He will be stuck in place unable to move.

It should be noted that this issue seems to be related to explosive barrels that are connected to "graphix_explosion.lua". So the generic red explosive barrel will work fine but not the others in the Barrel folder that are explosive.

**Comment by Teabone3** [comment]
Additionally, if you test the map again, the screen will be red and fade back to normal.

**Comment by rvanner** [comment]
@Teabone3 Is this Max or Classic? Can you share a video?

**Comment by Teabone3** [comment]
Classic,
I will see if i can put a video together soon. Also someone else is experiencing the same issue that im directing to post here as well.

**Comment by Teabone3** [comment]
Graphix has a fixed lua script for this.

**Comment by plemsoft** [comment]
@Thanks for reporting this issue, this has been fixed and will be in the next update, found the change from Graphix :)
