### ISSUE TITLE
AI Issues

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1373]
Issues Latest Build 2021-09-03

AI
Behaviors only seem to work for one entity at a time.
If you try to add another character they get confused and follow others flags.

Nodes seem very temperamental to join especially if you try to add a character they refuse to connect. 

Strafting seems to be struggling with the Navmesh and ignoring or losing it.
They either seem to stand still running on the spot or get stuck in Models.

( Perhaps this is all still on the to do list though )

**Comment by rvanner** [comment]
@synchromesh62 Can you please only report one issue per bug report? Please report the Importing and saving issues under different bug numbers and then edit this one. Thanks.

**Comment by LeeBamberTGC** [comment]
AI pretty good now with latest build :)
