### ISSUE TITLE
Object thumbnails don't have a curved bottom right edge

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1378]
As you can see, the bottom right edge is no longer curved:

![image](https://user-images.githubusercontent.com/1503593/132217168-de943cad-f510-40f2-a1cf-82c37d52d831.png)

**Comment by rvanner** [comment]
@plemsoft Can you change it so they are right angles on each corner?

**Comment by plemsoft** [comment]
@rvanner Its a left over from the old icons, and this is only available in the "dark" style , we dont have rounded corners for other styles like "blue" , should we make all styles look like "blue" without corners , or would you like rounded corners on all styles ?.

**Comment by rvanner** [comment]
@plemsoft Make them all like the blue without corners thanks.

**Comment by plemsoft** [comment]
Fixed.
