### ISSUE TITLE
GameGuru Classic - September Fixes

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#1382]
Whilst working on the explosions script i was testing on a map i created a few years ago, this allows me to test each type of explosion.
In the latest September release there seems to be an issue with collision, the barrels sink into the terrain

please see video https://youtu.be/XTF7aUo8D6A

**Comment by Teabone3** [comment]
I can confirm this. It was the first thing I noticed last night - but thought it was an issue on my part with placing them partly into the terrain - which turned out to be not the case.

**Comment by Teabone3** [comment]
Placed a bunch of barrels on a hill and they fell through the ground

![barrels](https://user-images.githubusercontent.com/35990109/132798944-bb19bd4d-dda5-47e6-a19d-57b6e4d6c91c.jpg)

**Comment by synchromesh62** [comment]
Confirmed in Before and after shots.
Cube falls from Ceiling to floor.

![PSP1](https://user-images.githubusercontent.com/35708217/132833023-85f7ac11-aa08-41e6-84fa-bb8bcbccfce7.png)

![PSP2](https://user-images.githubusercontent.com/35708217/132833052-dbc2d096-6b2e-47cd-8412-abc28b1c7e2b.png)

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this issue, this has been fixed and will be in the next update :)
