### ISSUE TITLE
GGC (Classic) Issue: Lua Command "Panel" No Longer Works

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1383]
The lua command to create panels for text, appear to no longer work.

Example:
Panel(25,18,75,40)

Nothing will display in game.

**Comment by synchromesh62** [comment]
Confirmed in these 2 before and after shots 

![P1](https://user-images.githubusercontent.com/35708217/132832657-e8362bf7-821d-407c-a987-fef4fdb04476.png)

![P2](https://user-images.githubusercontent.com/35708217/132832686-58a0594a-fdee-41a7-b3a7-c636991df476.png)

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed and will be in the next update :)
