### ISSUE TITLE
Stand Alone Games still throw error 8003 on 2021.09.03

### ISSUE THREAD

**Issue by VArterJr** [TheGameCreators/GameGuruRepo#1385]
*Stand Alone Games* still throw error 8003 on 2021.09.03. I have tried several games, quite simple things in the games, etc. This one I'm testing is super small and has one character, two barrels, one tent, an audio zone, and a text zone. That's it. Some basic gravel grass around the small playing area. Works fine in Test mode in GGM. I've had SA Game issues since day one but wanted to wait until closer to release to report it. Since you are only a few months out, this is now a bit concerning.

<img width="327" alt="01RunSAGameError" src="https://user-images.githubusercontent.com/4485488/132863934-11b2c15e-d5ba-40d1-bb54-dc0a43c0f077.png">
<img width="121" alt="02Error8003" src="https://user-images.githubusercontent.com/4485488/132863938-70605103-b7e2-4117-bce0-9aa444f9e384.png">

**Comment by GraPhiX-Guru** [comment]
Stand Alone process as not been touched in MAX as of yet, it is still being developed

**Comment by plemsoft** [comment]
This has already been fixed.
