### ISSUE TITLE
Falling through generated terrain

### ISSUE THREAD

**Issue by niijel** [TheGameCreators/GameGuruRepo#1386]
create new map, get new scenery, place start point, run round mountain, fall through ground land in water under terrain.
seems to be were the terrain is steep or 'sharp'. Happened in multiple places within a few seconds. walking on smooth flat terrain seemed ok.
![underneath-ggmax](https://user-images.githubusercontent.com/7059822/132947733-4a84980b-72d8-4152-8261-7bcc9d40c4ab.png)

**Comment by LeeBamberTGC** [comment]
Build updated, should be fixed now.

**Comment by thor49** [comment]
Hi Lee I tried the new update and can walk on terrain and see the new message at end of Yellow Edit box stopping you
leaving the play area..
But when I save and then load the terrain level back up Press play..  I then fall through terrain.. 
with the displayed message You can't leave the play area... but you can't stop yourself..?

**Comment by LeeBamberTGC** [comment]
@thor49 Just did these steps in the latest build:

1. Launched MAX
2. Clicked Test Level to see phyiscs work by default
3. Exit test level then clicked save, gave the name 'mynewlevel.fpm'
4. Loaded this level back in
5. Clicked Test Level and as you report, fall through terrain

Thanks for the report!  It seems loading a level resets the terrain physics flag.

**Comment by LeeBamberTGC** [comment]
Fixed for next build :)
