### ISSUE TITLE
Runtime error 7008

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#1388]
![image](https://user-images.githubusercontent.com/89519185/132955114-2776efd4-a696-4e7d-876d-996dfa08ddc4.png)
when launching the military collection map, an error occurs

**Comment by synchromesh62** [comment]
That was created with the old terrain .. Its probably not compatible with the new yet.

**Comment by casigus** [comment]
aye also had this. did a another install on a seperate disk and whiklst it does load, theres no clipping on the ground so you just fall through it, dropped a model in, lets you stand on that ok, but yeah. I mean it looks gorgous! the land, water, sky, the clouds are beatiful. but broken!

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/132957626-e3706edc-48dc-4912-a7eb-29c6b1d0e607.png)

![image](https://user-images.githubusercontent.com/68471279/132957640-700650a4-bdbb-4244-a1b9-6776ed1c31e7.png)


![image](https://user-images.githubusercontent.com/68471279/132957671-16683e20-c2b1-4863-b633-9c3901171fa6.png)

**Comment by casigus** [comment]
Ok done a seperate install, deleted the game guru folder in the gameapp folder in my documents, then launched, created a new terrian and BAM we're in. 
![image](https://user-images.githubusercontent.com/68471279/132958046-24a8d14a-80cc-49df-96ae-02528411b845.png)

so give it a go, see if that fixes it!

**Comment by ZakJudges** [comment]
@LeeBamberTGC Is this one fixed in the latest build? :)

**Comment by LeeBamberTGC** [comment]
Yep indeedy, this one fixed for this Friday's build.
