### ISSUE TITLE
No save after using f9 function

### ISSUE THREAD

**Issue by m2design** [TheGameCreators/GameGuruRepo#139]
In test if I use the f9 function to relocate or rotate any model in the map and then chose to exit back to the editor and then exit the session I do not get a prompt asking if i want to save changes, the program just closes with out a save. Then I have to redo all changes made using f9.

**Comment by thecyrus** [comment]
Well, I think it will be easily fixed.
In the meantime, work it around by saving manually before closing.

**Comment by LeeBamberTGC** [comment]
When editing in F9 mode, and return to editor and leave, you now get the option to save in the latest build 13/04/18 end of GMT.
