### ISSUE TITLE
crash import gameguru classic

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1391]
Models are imported without problem but max crashes on terrain

**Comment by ZakJudges** [comment]
Hi @smmaas, could you please provide steps to reproduce this so we can look into this for you?

**Comment by rvanner** [comment]
@smmaas Can you please post more information so we can look into this crash?

**Comment by smmaas** [comment]
This is a very old one, at the moment I can't import anything at all (Issue 1810) so I would close this one.
