### ISSUE TITLE
New Terrain - If you press new level to create new map - Old level entities are not cleared

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#1393]
1. I created a terrain and added AI character and Path.
2. I had to add floor panels to get the AI to walk the Path.
3. I then decided to make new Terrain type Level.
4. Pressed create new level choose terrain type and size etc.
5. The level was created .
6. Pressed Test level and immediately fell through terrain.
7. And landed on the floor panels from the first level beneath the new terrain.
8. The AI character was still there walking along the path running its script..?

**Comment by thor49** [comment]
Hi Lee 
I was thinking about this last night.. and I think on the first Terrain level I had a Start Marker on the floor panels..
When I started the new terrain level I did not add a new Start Marker.. So maybe that caused the fall through terrain..
Don't want you to waste time looking for another Physics problem...

**Comment by LeeBamberTGC** [comment]
This has been fixed for this Friday's build. Selecting New Level will wipe out the old one, much like it did before except you are now given the terrain generator UI too.  Select EMPTY to revert to a grey flat floor.
