### ISSUE TITLE
Estimate Wrong Towards End Of Auto Update

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#1394]
See updater UI:
![image](https://user-images.githubusercontent.com/35840583/133505575-bf97d6ad-d544-4d8b-9eb8-dbc43ee7e733.png)

**Comment by michaeloldman** [comment]
Last update stopped on this screen for a bout 15 minutes.

![Download stuck here](https://user-images.githubusercontent.com/12246318/133948100-f714ff18-8705-47de-9ea7-dae2a4e06dec.png)
It also downloaded the MAX collection even though it is not selected.

**Comment by ZakJudges** [comment]
@LeeBamberTGC @OldFlak Before I close this, I just want to check if there have been any more occurrences of strange estimates? :)

**Comment by OldFlak** [comment]
I will pay closer attention to next update and record the last part see if it is still iffy or not :)
