### ISSUE TITLE
GGC (Classic) Issue: Rocket Man shoots two rockets at same time

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1395]
The rocket man will sometimes shoot two rockets at the same time. Only way to reproduce this is to walk side ways to avoid the rockets and he'll attempt to shoot two simultaneously at the player.

Video:
https://www.youtube.com/watch?v=P9Pk1FxXk-w

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed and will be in the next update :)
