### ISSUE TITLE
GGMAX-version 17Sep2021: RPG issue

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1399]
please see pic attached.

![rpg_issue](https://user-images.githubusercontent.com/15969299/133818671-a9586ff5-9bc0-4a6d-9f7d-39bdc72f88a0.png)

**Comment by LeeBamberTGC** [comment]
The old RPG will be removed from the weapon selections for the first release. Watch this weeks broadcast :)

**Comment by Kitakazi** [comment]
Pretty sure that issue with the RPG is caused when ADS because the FOV gets bigger instead of smaller I reported this issue a while ago.

https://github.com/TheGameCreators/GameGuruRepo/issues/1138
