### ISSUE TITLE
In Preview, some entities are rendered wrong

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#14]
With pbroverride = 1, existing models become partially or totally black. Also, there's a sort of "phishnet" shining on the terrain. And lightmapping often creates crazy or flickering shadows.

**Comment by plemsoft** [comment]
phishnet on terrain is fixed. 
Lightmapper is duplicate issue.

> "existing models become partially or totally black"
This was fixed in the shaders in the beta , so are also included here.

**Comment by Teabone3** [comment]
Fixed in the Beta as in not the PP right?
