### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1400]
![image](https://user-images.githubusercontent.com/68471279/133847873-1628ac21-f1cb-4508-adc3-4be4c287ab89.png)

SO updated it, and it wiped my assets folder and maps for some reason or other, but after re-arranging managed to import them back in, anyway, launched it. everythings janky, constant freeze ups, cant really do anything with out it not responding. the visuals are amazing thou, the sky, the water the land, its really amazing, hopefully we'll get this working eventually.

**Comment by ZakJudges** [comment]
@casigus If you navigate to your Documents folder then GameGuruApps, you should hopefully see a backup of your previous writable folder. This should contain all the missing imported models and maps. 

Regarding the freezing, I would suggest doing a clean install of the software. If you are still experiencing these issues afterwards, then please let me know and I'll see what I can do to help :)

**Comment by casigus** [comment]
yassssssssssss. found it. yass did the re-install, still the same! cleared the tgc in appdata ect ect. seams a wee bit more stable!

your cool! be safe 😄

________________________________
t

**Comment by ZakJudges** [comment]
@casigus Thanks for the info. So I can try to reproduce this, are you able to provide a video of the issue? Thanks :)

**Comment by casigus** [comment]
the issue only occurs when you build close to the map edges, seams to be okish now :)
