### ISSUE TITLE
GGC (Classic) Issue: Standalone Style.txt Defaults

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1403]
_Simply put the style.txt file doesn't copy over its contents properly when making a standalone._

**titlesbank\style.txt**

If you change the style.txt to reference another style folder for custom titlescreen and loadscreen etc, and then make a standalone of your game, it will ignore what you have entered in the style.txt and always revert your style back to "default" during the standalone building process.

This means I have to continuously change the standalone's version of style.txt each time I make a new update (standalone) of my game.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, i was not able to reproduce it , tried putting "easter" in style.txt , when i exported the standalone it worked as it should ? , did you test this after updating or validate ? that would explain it :)
