### ISSUE TITLE
Terrain showing inside Object Library Preview

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#1408]
We need to switch off terrain rendering when doing the previews:

![image](https://user-images.githubusercontent.com/35840583/134030403-2d48f1f2-f964-4435-afd8-fdd5f7104b40.png)

**Comment by michaeloldman** [comment]
Yes notice that one as well:
![Terrain In Backdrop pics](https://user-images.githubusercontent.com/12246318/134261401-3d83f114-4afb-45fd-b0f5-149131f0b98d.png)
Sometimes reassigning the backdrop fixes it, but mostly doesn't do anything or just makes it worse.

**Comment by LeeBamberTGC** [comment]
@plemsoft I will leave this one on your plate :)

**Comment by plemsoft** [comment]
Fixed :)

**Comment by OldFlak** [comment]
Not Fixed in current version - 2021.10.01
![MAX Rendering Scene In Objects Library](https://user-images.githubusercontent.com/12246318/135753263-2da65bb3-fe7d-45ad-8975-2c2dc38ebc98.png)

**Comment by plemsoft** [comment]
@OldFlak It looks like a custom thumb from your write folder, could you try to double click it and select "update thumbnail" , thanks :)

**Comment by OldFlak** [comment]
@plemsoft 
That was the result of hovering mouse over the item 
- it was showing the level under it as the item animated.

Yesterday it was reliably doing the same thing on every tile, even after rebooting system
- Today not doing it at all anywhere

So perhaps still a random issue? :)

**Comment by LeeBamberTGC** [comment]
@OldFlak I think this relates specifically to the level that was loaded into the editor when you browsed the object library.

@plemsoft It could be the position we place our preview objects for rendering the object library thumbnails. Perhaps take a leaf out of the character creators book and make the coordinate incredibly out of reach from the game level geometry.

NOTE: I was not able to reproduce this with my own levels in the latest build. Hopefully, it is (a) fixed, or (b) reproducible.
