### ISSUE TITLE
The problem of enemy characters

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#141]
1. When the **enemy characters** placed on objects - the time of **testing** they **fall on the ground**.

![en-1](https://user-images.githubusercontent.com/36647058/38076894-51ad603c-334c-11e8-8df6-4c8f5d595257.jpg)
![en-2](https://user-images.githubusercontent.com/36647058/38076902-56406126-334c-11e8-9985-895643ff9efd.jpg)
![en-3](https://user-images.githubusercontent.com/36647058/38076908-59801e4e-334c-11e8-84d4-0c3b0339ce9c.jpg)

**I saw this in all the characters of the enemy.**

**Comment by Belidos3D** [comment]
Try placing a floor zone on the area that you want them to stand, that's what they're for.

**Comment by Shahin3d** [comment]
This report has been fixed in the new update.
