### ISSUE TITLE
2021.09.17 MAX - Messing with Custom Writable Folders

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1410]
BUG 2021.09.17
MAX messing with Custom Writable Folders
- Max renames custom writable folders
- Creates new folder system in custom location
- the warning dialog when updating only mentions core folders, not custom writable folders

Expected Behavior
- Leave custom writable folders alone
- Have to copy a whole heap of media over as result
- the idea of custom writable area is that all custom media is kept safe

Also same in very latest release

OldFlak....

**Comment by michaeloldman** [comment]
@ZakJudges it seams it only does this on the first update for each build

So when MAX prompts you to install new update 
- it will create backup folder of Writable Folders

However if you just verify a build it leaves the folders as is.

OldFlak....
