### ISSUE TITLE
Movement of the water causes ghosting effect on entities in front of it

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1411]
The movement of the water causes entities that are in front of the water to also start rippling themselves. 
![1](https://user-images.githubusercontent.com/51464873/134441297-b4f4a251-d2b5-4793-8fa6-c9ab2c463615.png)
![2](https://user-images.githubusercontent.com/51464873/134441301-1e62fae1-2ff3-4573-a4f3-271bcdb046b0.png)

**Comment by michaeloldman** [comment]
This has been an issue pretty much from day one.
Here be a vid of it in current build:
