### ISSUE TITLE
2021.09.17 MAX - Post Processing Settings Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1412]
When you open a map, Auto Exp Rate, Auto Exp Level, Gamma in Post Processing are always set to default.
![Exposure Settings Not Saved](https://user-images.githubusercontent.com/12246318/134604521-258b1b84-1e08-4a0a-922e-a20ade02eea3.png)

OldFlak....

**Comment by ZakJudges** [comment]
@plemsoft I'm also finding that FXAA keeps on being turned off every time I start MAX
