### ISSUE TITLE
2021.09.24 MAX - Terrain Mini Map Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1413]
Playable Area on Mini Map and actual terrain do not match (noticed it in all builds with terrain)
- The more you move the yellow box on mini map the worse it seams to get
![Playable area on mini mpa and actual terrain does not match](https://user-images.githubusercontent.com/12246318/134618063-ee678ad7-4c89-47e6-8267-b42a1fd62c4e.png)

OldFlak....

**Comment by plemsoft** [comment]
Minimap was replaced with other system.
