### ISSUE TITLE
[MAX] - Toggle off rimlighting? 

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#1416]
Max's graphics have always looked off to me somehow, but until today I couldn't pinpoint what it was. I noticed when putting a character indoors, his pants were glowing in the dark!

![Rimlight_1](https://user-images.githubusercontent.com/56294129/134808932-8dfc8f2b-9b12-4fc0-b628-a1b7c11e25b2.PNG)

This effect from what I can tell is known as "rimlighting", which is normally done to give a sort of "outline" to objects in order to make them stand out from the environment. This may be useful for a more "cartoony" visual style, such as in Team Fortress 2 (which makes excellent use of rimlights), but since GG MAX is meant to be able to make a wide array of games and visual styles, it would be immensely appreciated if this effect could be turned off, either globally with a toggle or even per-entity (so we could still have rimlighting on things we want to stand out, such as collectibles.)

(Here's an example from TF2, with rimlight on VS off. It's especially noticeable on the feet/boots, much like in GG MAX.)

![TF2_Rimlight](https://user-images.githubusercontent.com/56294129/134809368-e1c2a157-ba59-47e4-9ae6-16fdb39bc495.jpg)

This rimlight effect also seems to cause a very weird "sheen" effect on flat surfaces, such as the walls of a building. This I would absolutely consider a "bug" and not an "enhancement."

![Rimlight_2](https://user-images.githubusercontent.com/56294129/134809460-2b2acb1d-1d18-4595-b8ec-d84b4922bff1.PNG)

**Comment by PaulSJ** [comment]
Should be fixed in the latest version
