### ISSUE TITLE
Waypoint in the game does not work.

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#142]
**Waypoint** in the game does not work.
When I tested the game, I noticed that **Waypoint** does **not work for enemy characters** and is useless.

![waypoint](https://user-images.githubusercontent.com/36647058/38077230-8ac912fc-334d-11e8-834c-7883b4ceeb0a.jpg)

**Comment by LeeBamberTGC** [comment]
Can you send me an FPM using a stock character which I can run to see the character not following the waypoint? Make sure you choose an AI script that follows paths and that the player is out of sight so the character does not disengage the path and attacks the player.

**Comment by Shahin3d** [comment]
WayPoint does not work well for all enemy characters.
![untitled](https://user-images.githubusercontent.com/36647058/38141383-1c81dcce-344d-11e8-8af6-627b4b048d3b.png)
![snapshot48](https://user-images.githubusercontent.com/36647058/38141379-16da5da0-344d-11e8-8ecb-7219d2e8b500.jpg)

[fpm-file.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1863853/fpm-file.zip)

**Comment by LeeBamberTGC** [comment]
Fixed the module_combatmelee.lua to accept the bash combat type to allow the first character to find a patrol by default. Characters 2 and 3 followed the path fine, the last one was set to a guard style script and would not follow a path. Attached an improved FPM to see waypoints at a safe distance:
[Test-Waypoint.zip](https://github.com/TheGameCreators/GameGuruRepo/files/3330537/Test-Waypoint.zip)

**Comment by Shahin3d** [comment]
There are still a few problems.
Should be re-examined.

**Comment by LeeBamberTGC** [comment]
@Shahin3d You will need to be specific to reopen this task. Provide an FPM with stock media, a full step by step on what should be done, and what to watch for, and highlight the issues spotted, thanks!
