### ISSUE TITLE
Object Library - Mousing Over an Entity Causes a Flash of Light On Models In the Scene

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1424]
Make a dark scene with some entities that have decent metallic value and this happens when you mouse over an object in the library.
https://www.youtube.com/watch?v=_NSjIUTVhH4

video starts at 10 seconds in

**Comment by plemsoft** [comment]
@Kitakazi I think this was already fixed, could you try it in the latest version and let me know, thanks :)

**Comment by Kitakazi** [comment]
@plemsoft 
I believe this is fixed. Closed.
