### ISSUE TITLE
Possible Navmesh being seen as floor bug 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1425]
I suddenly started having a vertical door issue as seen in the video where the door jumps a foot when opening and closes a foot above ground. At first i thought it may be the script but the only thing i have come up with is the Navmesh is being seen as the floor under certain circumstances as i have also seen reports that some models do not sit directly on the floor when placed on the map ..
Could this be a bug or maybe script missing some kind of new command to ignore the Navmesh.

Basically its just a ( move object vertically up \ down ) script that i use for a door & it could just be this is not practical for Max ?

https://youtu.be/HBrz_Qo5o4Q

This pic shows my suspicions with the mesh visible ?

![mesh](https://user-images.githubusercontent.com/35708217/135444529-abc0a8af-447d-47c0-afbd-21f1604b2ab3.png)

EXTRA INFO 
The door uses **isimmobile = yes** ( to stop it falling over ) and trying the same thing with a cube with **isimmobile =no** as soon as it hits the navmesh it falls the rest of the way. 
https://youtu.be/0VIGddEvvpI

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I have made an official door_rising behavior in the latest build. See if that works for your purposes in this case. I use it in my own Switch Escape demo for the roller doors.

**Comment by synchromesh62** [comment]
If your referring to the internal build then yes it perfect i have been playing with it :)
Thanks Guys.
I will close this one down
