### ISSUE TITLE
White Screen of Death

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#1426]
Hi Lea and Team,

Just been having a play around with Max and very impressed. But, when I start to make a  scene and do anything in the Editor the screen goes White and closes the the program,  this can vary from 30 seconds to 5 mins, it's all about what I would like in my scene, also any character I put in the scene along with my player we both end up under water.  

Could you tell me when I could load my dungeons that I have made into max and use them in a reasonable way. The dungeon maker that I use is Lafette, I have emailed him but he does not reply.

**Comment by ZakJudges** [comment]
Hi @Snage62, so I can look into this, could you send a video of the crash, as well as a model that is not working properly? :)

**Comment by ZakJudges** [comment]
@Snage62 Closing this issue, assuming it has been fixed in recent months. Please re-open it if you are still encountering it. Thank you.
