### ISSUE TITLE
GGMAX Created Level Save Issue / Crash Upon Loading Levels 

### ISSUE THREAD

**Issue by Ghazzly** [TheGameCreators/GameGuruRepo#1429]
Any levels created in the latest update build do not reopen properly after saving.
Upon reopening the saved level, everything built is erased.

The terrain area is also reset and moved to the default location

Demo Level's also crash when testing. 
(I'm guessing that's because they were made before the new terrain system

Also, the indoor shooter level cellar does not load at all, Instant crashing upon selection

**Comment by ZakJudges** [comment]
Hi @Ghazzly, Would you be able to check if you still experience these issues after verifying your files in the updater? :)

**Comment by Ghazzly** [comment]
> Hi @Ghazzly, Would you be able to check if you still experience these issues after verifying your files in the updater? :)

Hey,

Yeah ill get right on it when I'm home from work and let you know.

Thanks Zak

**Comment by Ghazzly** [comment]
Hi @ZakJudges 

Still getting the same issue as before even after verifying my files.

Here's a short clip of whats happening
https://youtu.be/rmTcBvzJA9k

**Comment by Ghazzly** [comment]
Hi @ZakJudges 

I've recorded a short video on what is happening, Although the recording is poor and there's a few artifacts from the recording software that I cannot explain why they appear but they aren't actually from Game Guru Max.

However, Upon saving my level and then reopening it, This is what happens

https://youtu.be/g0SYUPSowAE

Thanks

**Comment by ZakJudges** [comment]
Hi @Ghazzly, thank you for recording the video. I haven't been able to reproduce the issue seen, is there any chance you would you be able to send the map file too?
@LeeBamberTGC Would this one be for you or @plemsoft? :) Seems it could be terrain physics, or just the wrong coordinates being used after loading.

**Comment by Ghazzly** [comment]
Hi @ZakJudges Yeah I'll provide the map file later on tonight.

It also happens with the demo levels, the floor/terrain doesn't load in properly so the player just constantly falls.

Had the same issue a few times after generating my Arctic terrain and placing the player start then running the game, the player will then fall through the level.

I'll attach the file around 5pm

Thanks for getting back to me.

**Comment by Ghazzly** [comment]
[Test 3.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7290834/Test.3.zip)

@ZakJudges  Please find attached zip file with the map created in the video I shared previously.

Sorry for delay
