### ISSUE TITLE
NPCs Shooting Through Walls

### ISSUE THREAD

**Issue by lordjulian1** [TheGameCreators/GameGuruRepo#143]
NPCs shoot through walls of EBE structures. Sometimes you can also see bits of them or their weapons protruding through the wall.  Issue remains even if the wall's thickness is doubled by using internal and external walls.

**Comment by Teabone3** [comment]
Seems to work fine with entity walls. Even thin ones. But with EBE they can shoot through.

**Comment by LeeBamberTGC** [comment]
I created a simple EBE structure (3x3 with some walls and a gap) in PP build 15/04/18 with one soldier and lots of health, switched on debug view to see the obstacles and pathfinding, and the enemy only shot me with line of sight, not through any wall. 

![image](https://user-images.githubusercontent.com/35840583/38840182-438a7452-41d6-11e8-9df4-e86ed502f2e6.png)

**Comment by lordjulian1** [comment]
I really want to help you with this so I will give you all the info I can (it might be overkill). Here are my system specs:

OS Name	Microsoft Windows 7 Home Premium
OS Name	Microsoft Windows 7 Home Premium
Version	6.1.7601 Service Pack 1 Build 7601
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	JULIAN-PC
System Manufacturer	Acer
System Model	Aspire 5755G
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz, 2201 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Acer V1.19, 17/02/2012
SMBIOS Version	2.7
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume2
Locale	United Kingdom
Hardware Abstraction Layer	Version = "6.1.7601.24094"
User Name	Julian-PC\Julian
Time Zone	GMT Daylight Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.85 GB
Available Physical Memory	3.65 GB
Total Virtual Memory	15.7 GB
Available Virtual Memory	10.8 GB
Page File Space	7.85 GB
Page File	C:\pagefile.sys

Now, I think our esteemed forum moderator synchromesh was one of the first to identify this bug. He/she told me he'd posted the issue on the forum and gave me this link:
[](
https://forum.game-guru.com/thread/219140#msg2592855)

I used small G's module_combatcore.lua script and it fixed the issue for me.

If it's happening on my system I would guess it is happening on others too. As a brute force or belt-and-braces measure, would it do any harm to add a ray cast?

**Comment by lordjulian1** [comment]
For some reason the link to the forum post wasn't included in the above. Here it is:

[](https://forum.game-guru.com/thread/219140#msg2592855)

**Comment by plemsoft** [comment]
@lordjulian1 Is this still a issue in the latest versions ?

**Comment by LeeBamberTGC** [comment]
Potential fix for next beta build: https://forum.game-guru.com/thread/220855
