### ISSUE TITLE
Gameguru max will not open after updating 2021.10.01

### ISSUE THREAD

**Issue by Shirley196** [TheGameCreators/GameGuruRepo#1430]
I have update game guru max to 2021.10.01 using the auto updater opened the game it freezes the screen and l get a runtime error 502 0 and sometimes the welcome page comes up for 2 seconds and goes to a freezen screen 
![20211004_142322](https://user-images.githubusercontent.com/91857788/135780869-e5606f16-6f3e-4a42-aecf-ccfc3616b49a.jpg)
![20211004_141250](https://user-images.githubusercontent.com/91857788/135780874-1aa98d24-f274-47d1-9f11-aac24ef16657.jpg)

**Comment by ZakJudges** [comment]
Hi @Shirley196, does the issue persist in a clean install of the software? :)

**Comment by Shirley196** [comment]
Yes l have reinstall it twice now last weeks update worked fine just this weeks update

**Comment by ZakJudges** [comment]
@plemsoft Any ideas? :)

**Comment by plemsoft** [comment]
@Shirley196 Try this: in your Max install folder, rename this file "changelog.txt" to "testchangelog.txt" , and let me know if this fix your issue, thanks :)

**Comment by Shirley196** [comment]
> @Shirley196 Try this: in your Max install folder, rename this file "changelog.txt" to "testchangelog.txt" , and let me know if this fix your issue, thanks :)

Hi thanks l have try this but still is doing the same thanks

**Comment by plemsoft** [comment]
@Shirley196 Thanks, we dont have many places that are able to produce a 502 error , one place that can do this is on the "changelog" screen (renaming changelog.txt should skip this screen), anyway the main problems is that somehow one of your files is bad or are missing. could be locked ?

Try this:
Reboot your computer.
Do not startup max, but instead start "GameGuru MAX Updater.exe".
Run "Verify Files".

Let me know if this fix the issue, Thanks :)

**Comment by Shirley196** [comment]
> @Shirley196 Thanks, we dont have many places that are able to produce a 502 error , one place that can do this is on the "changelog" screen (renaming changelog.txt should skip this screen), anyway the main problems is that somehow one of your files is bad or are missing. could be locked ?
> 
> Try this: Reboot your computer. Do not startup max, but instead start "GameGuru MAX Updater.exe". Run "Verify Files".
> 
> Let me know if this fix the issue, Thanks :)

Hi i have restarted the computer 3 or 4 times and have run the gameguru max updater 3 or 4 times but says all the files are there and do you want to start game guru .  The welcome screen comes up for about to seconds and then goes to the screen 1st picture screen and you cant open anythink on it or move the mouse around 

Thanks shirley

**Comment by Shirley196** [comment]
> @Shirley196 Ok so you dont get the 502 error anymore ? but freeze like in the first screenshot ?

Yes its the freezen

**Comment by plemsoft** [comment]
@Shirley196 Please let me know your computer specs , GPU , MEM ... Also try this: in setup.ini change this line "producelogfiles=0" to "producelogfiles=1" , this will generate a "Guru-MapEditor.log" when you startup max, it is located in your write folder. Please also upload this log here so im able to see where it fails , Thanks for your help :)

**Comment by Shirley196** [comment]
> @Shirley196 Please let me know your computer specs , GPU , MEM ... Also try this: in setup.ini change this line "producelogfiles=0" to "producelogfiles=1" , this will generate a "Guru-MapEditor.log" when you startup max, it is located in your write folder. Please also upload this log here so im able to see where it fails , Thanks for your help :)

![20211006_202144](https://user-images.githubusercontent.com/91857788/136158309-1daf51fa-62de-4baf-bf02-7181443d870d.jpg)
Th
![20211006_201811](https://user-images.githubusercontent.com/91857788/136158322-35e2af88-4511-4556-807d-a89e51fc1235.jpg)
E file already had producelogfiles set at one as shown in the photos l cant find the guru-mapeditor.log thanks shirley

**Comment by plemsoft** [comment]
@Shirley196 If you do not use a custom write folder, the log will be placed here:
"\Users\YOURUSERNAME\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log"

**Comment by Shirley196** [comment]
> @Shirley196 If you do not use a custom write folder, the log will be placed here: "\Users\YOURUSERNAME\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log"
> 
> FORGOT: What GPU do you have ?

![20211006_203502](https://user-images.githubusercontent.com/91857788/136159632-45e0db2f-e022-46a2-81df-7df6422e4cd9.jpg)
![20211006_203447](https://user-images.githubusercontent.com/91857788/136159639-8f2eae24-9119-48b0-bf95-d29887840c7a.jpg)
![20211006_203408](https://user-images.githubusercontent.com/91857788/136159649-eb55e65e-59c4-41c6-93ce-5613d39b00cc.jpg)
![20211006_203424](https://user-images.githubusercontent.com/91857788/136159665-518e894f-5498-463e-93c3-55ab7c49ab9b.jpg)

**Comment by Shirley196** [comment]
> > @Shirley196 If you do not use a custom write folder, the log will be placed here: "\Users\YOURUSERNAME\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log"
> > FORGOT: What GPU do you have ?
> 
> ![20211006_203502](https://user-images.githubusercontent.com/91857788/136159632-45e0db2f-e022-46a2-81df-7df6422e4cd9.jpg) ![20211006_203447](https://user-images.githubusercontent.com/91857788/136159639-8f2eae24-9119-48b0-bf95-d29887840c7a.jpg) ![20211006_203408](https://user-images.githubusercontent.com/91857788/136159649-eb55e65e-59c4-41c6-93ce-5613d39b00cc.jpg) ![20211006_203424](https://user-images.githubusercontent.com/91857788/136159665-518e894f-5498-463e-93c3-55ab7c49ab9b.jpg)

I found it sent it through

**Comment by plemsoft** [comment]
@Shirley196 I noticed in your crash image (pic 1) , that it looks like you have 2 copies running ?

![crash-problem](https://user-images.githubusercontent.com/18662417/136163953-cb8e03f0-757e-4f18-9be9-9d18f3b07e6d.jpg)

Or is one of them the updater ?
What is your GPU ?
Could you make a fresh screenshot of where it crash, and where only one copy is running , thanks.

**Comment by Shirley196** [comment]
> @Shirley196 I noticed in your crash image (pic 1) , that it looks like you have 2 copies running ?
> 
> ![crash-problem](https://user-images.githubusercontent.com/18662417/136163953-cb8e03f0-757e-4f18-9be9-9d18f3b07e6d.jpg)
> 
> Or is one of them the updater ? What is your GPU ? Could you make a fresh screenshot of where it crash, and where only one copy is running , thanks.
One is the updater and the other is guru max

**Comment by Shirley196** [comment]
![Uploading 20211006_211903.jpg…]()

This is the start up

**Comment by Shirley196** [comment]
![20211006_211909](https://user-images.githubusercontent.com/91857788/136166113-dd68eb1c-9de8-40e2-aa52-80176898ca49.jpg)

**Comment by Shirley196** [comment]
![Uploading 20211006_211903.jpg…]()

**Comment by Shirley196** [comment]
![20211006_211907](https://user-images.githubusercontent.com/91857788/136166593-d24fa863-3829-4954-89c2-ab4c0133ce2d.jpg)
![20211006_211909](https://user-images.githubusercontent.com/91857788/136166606-27c7a76d-e4a3-404d-8a18-c84db42e03b9.jpg)

**Comment by GraPhiX-Guru** [comment]
I notice from your screen shots you are not connected to the internet, it also looks like you have a third party AV installed.

try disabling/uninstalling your third party AV program restart your PC and make sure you are connected to the internet
![Screenshot 2021-10-06 092719](https://user-images.githubusercontent.com/35724756/136167456-4f5a4c8d-fd22-40a8-aaf3-48ff31162415.png)

**Comment by Shirley196** [comment]
> I notice from your screen shots you are not connected to the internet, it also looks like you have a third party AV installed.
> 
> try disabling/uninstalling your third party AV (it looks like it as issues) program restart your PC and make sure you are connected to the internet ![Screenshot 2021-10-06 092719](https://user-images.githubusercontent.com/35724756/136167456-4f5a4c8d-fd22-40a8-aaf3-48ff31162415.png) ![Screenshot 2021-10-06 092818](https://user-images.githubusercontent.com/35724756/136167672-09a9b08d-aab1-4677-96ca-5bfc46bb215a.png)

Hi it still does the same even when im contected to tbe internet which one is the thirdparty AV thanks

**Comment by GraPhiX-Guru** [comment]
it looks like Mcafee AV this ico
![Screenshot 2021-10-06 095029](https://user-images.githubusercontent.com/35724756/136171111-3af3b00f-feb5-419f-91a0-3c24de20ad6c.png)
n

**Comment by GraPhiX-Guru** [comment]
To be honest as long as you keep up with Windows 10 updates a third party AV program is not needed, the security features built into Windows 10 should be enough, most third party AV products slow you PC down

**Comment by Shirley196** [comment]
> > To be honest as long as you keep up with Windows 10 updates a third party AV program is not needed, the security features built into Windows 10 should be enough, most third party AV products slow your PC down
> 
> Im uninstalling now

No its still the same freezon screen
