### ISSUE TITLE
Weird installation error

### ISSUE THREAD

**Issue by Ohneiros** [TheGameCreators/GameGuruRepo#1433]
Cheers! I've been dealing with this problem for about a month now. GameGuruMax created some folders in my installation that were originally on GameGuru (Classics and subfolders, Purchases, and others). In addition to it, I can't run any level that contains even a single entity. I already did powerful uninstalls with iOBit, manually cleaned the registry of all traces of GameGuru, GameGuruMAX and TGC, but the problem persists. Any idea of what could be causing this? Important note: I imported an asset from the Abandoned Apartment DLC shortly before this problem started.

**Comment by ZakJudges** [comment]
Hi @Ohneiros, would you be able to verify your files using the auto updater, and then let me know if the problem persists? Thanks

**Comment by Ohneiros** [comment]
Thanks for the reply. Yes, I have verified them every time I tried
reinstalling (about 5 times already) but the problem is still there.
