### ISSUE TITLE
GameGuruMAX[Build 2021.10.08] Sky Glitches and Crashing

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#1435]
Hi
I have just updated this morning, unfortunately i cannot add any items from object library as soon as i try MAX Hangs, if i click on the preview icons the sky glitches badly, the sky does have artefacts anyway before i try and add an object.
The cloud edges are very pixelated which is enhanced when i click on an item in object library.
video of what happens: https://youtu.be/TdmnR2RrmXw

Regards
Kevan

**Comment by OldFlak** [comment]
Yes, seeing the same thing with the sky glitching when previewing models in Object Library

But have no problem adding items to map.

**Comment by GraPhiX-Guru** [comment]
Think i have found the cause, if the object library window is past the main window (even thought it is fulscreen) MAX will hang and crash, if the object window is inside the main window i can add items.

Screenshot: the yellow arrow shows where the edge of the object window is, this will hang MAX
![boundry](https://user-images.githubusercontent.com/35724756/136654712-5f2d31cd-dd42-4c6e-bb92-7588dd6eda78.png)
.

**Comment by Kitakazi** [comment]
I just had the sky glitch and crash happen to me but it was when I placed a really long object that cut through the terrain.  I reproduced it a few times only with really big objects that would spawn dissecting terrain immediately after clicking the object in the library.

**Comment by LeeBamberTGC** [comment]
I just tried moving the object library window to the described location and dragged in an object fine:
![image](https://user-images.githubusercontent.com/35840583/137503125-e93e4335-e058-478c-b5f5-aed8ebd96aef.png)


What I could do with is a video which shows from launching MAX to dragging in stock objects from the MAX Collection, that way I can see the crash, and then reproduce it here.

**Comment by LeeBamberTGC** [comment]
@GraPhiX-Guru I noticed the build version was from last week. Can you try the build from today as I tried to reproduce your video with todays version and no crash, so MIGHT have been fixed.  Releasing publicly soon!

**Comment by GraPhiX-Guru** [comment]
Hi Lee
sorry been trying to finish my app, Unfortunately it still happens in latest build, what is interesting is if the main window is not full screen it is fine, only when maximised does the issue occur.

Latest test https://youtu.be/Y1Y7rtYTCqk

**Comment by plemsoft** [comment]
@LeeBamberTGC I know the problems here and will take it when im back on bug fixing, so just assign it to me :)

**Comment by plemsoft** [comment]
sky glitches fixed , and a possible fix for the crash , not able to reproduce it but when the main window is not active we put the app to sleep, when you add more windows (dragging a window outside the main window) , the main window now don't have focus and we set the app to sleep, a check for this was added and i expect this to fix the crash, need confirmation :)

**Comment by GraPhiX-Guru** [comment]
MAX Test Build 1031-1 as fixed this issue, thank you @plemsoft 
https://youtu.be/dA_-VKRt8EE
