### ISSUE TITLE
GameGuruMAX[Build 2021.10.08] Skybox glitching

### ISSUE THREAD

**Issue by PaulFox12** [TheGameCreators/GameGuruRepo#1437]
Skyboxes (not simulated sky) glitch and shake around when moving using WASD keys both in editor and test game.

**Comment by plemsoft** [comment]
Same: https://github.com/TheGameCreators/GameGuruRepo/issues/1857
Perhaps the same: https://github.com/TheGameCreators/GameGuruRepo/issues/1910

**Comment by plemsoft** [comment]
@PaulFox12 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by plemsoft** [comment]
@PaulFox12 Is this issue solved for you ? , could you check in the latest build and if fixed close this issue, thanks :)

**Comment by PaulFox12** [comment]
Confirmed fixed in latest build
