### ISSUE TITLE
[GG CLASSIC] Please take a look at the lightrays in gameguru classic

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#1442]
Lightrays used to look really good in the older gg versions, but now its just.. idk how to even describe it. 
It looks off !
It also costs much performance and its basically useless.

is there a way to have beautiful lightrays at a low performance cost ?
Ive seen lightrays done very well in some games.

**Comment by plemsoft** [comment]
Dup please see: https://github.com/TheGameCreators/GameGuruRepo/issues/855#issuecomment-788684166

**Comment by Duchenkuke** [comment]
its an entirely different issue and not a duplicate. Again an issue closed and hoped that it will be forgotten.

**Comment by LeeBamberTGC** [comment]
@Duchenkuke You did not respond, so we closed it during the cleaning of all issues where the original poster did not get back to us. Removed the duplicate tag.

**Comment by Duchenkuke** [comment]
Thank you. Must have been during the Winter Season so I missed it very likely.

**Comment by Duchenkuke** [comment]
Also I must apologize... It happens again and again - I get really frustrated of the state gg classic is in. I just think it could have been so much more. Better Ambient Occlusion alone would be such a huge difference.
The Visuals Max has to offer are by far not what I was expecting honestly. But this is just my personal opinion, so it doesnt matter because I am just a single customer. Sorry !

**Comment by LeeBamberTGC** [comment]
@Duchenkuke No need. Your passion is an inspiration dude!  Keep pushing, eventually, we will have something truly special. We are looking to expand Classic in 2022, no details as yet, but it looks like Classic will live alongside MAX :)  The good thing about Classic light rays is that we wrote the shaders, so have FULL control. MAX light rays are from Wicked, so we need to navigate that shader system.

NOTE: Do you have shader HLSL writing experience? If so, if we open-sourced that part of Classic, would you be able to correct/improve the light ray system?

**Comment by Duchenkuke** [comment]
I wish I had HLSL knowledge.^^ Cybernescence would be the one who could do it maybe. 
What I can do best is probably to observe things. My attention to detail may be my strength. 
I am very happy that with the help of Preben and Cybernescence, we managed to add following graphic effects to gg:

Lumasharpen
Tone Mapping
Sepia Filter
Film Grain
better SSAO (than bevore)

For gameguru it would be a huge deal to have HBAO - I can make a video about it if wanted, I have a reshade that adds this but something like this needs to be in the core engine really. 
I am always open for exchanging ideas for gameguru. 

Anyway, Its great youre not forgetting about gg classic. Wolf and I have cool projects in the making and we will hold the classic flag high. 

If I can do anything to help, let me know.

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Send me the link video on HBAO. I remember it certainly, but cannot recall it. It is a screen space AO right?

**Comment by Duchenkuke** [comment]
oh there is no video yet. I can make one tho, maybe tomorrow morning.
I only have an example where I had HBAO in Taipeh Contract (with reshade I might add)
https://www.youtube.com/watch?v=itOy6YWfqSg&t=

I think it should be a very doable task to add some new shaders or just changed already existing ones to significantly improve the image quality of gg.

**Comment by Duchenkuke** [comment]
> @Duchenkuke Send me the link video on HBAO. I remember it certainly, but cannot recall it. It is a screen space AO right?

yes but it works horizontally - I cant tell exactly how it works, my technical knowledge about it is limited. 
But compared to SSAO (wich is currently in gg classic) it is way more visible and much darker - and thus making a huge change for levels.

**Comment by LeeBamberTGC** [comment]
@plemsoft I think you can probably grab an old Steam build and do a light ray screenshot then see how it looks with today's build, it might simply be that we changed some defaults, etc.  I do not recall rewriting the light ray shader.

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this issue, the shader has been fixed and will be in the next update :)

**Comment by Duchenkuke** [comment]
awesome! Thanks Preben!

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Do you want to confirm this as closed, beta now up on Steam :)

**Comment by Duchenkuke** [comment]
Please let me test it and I will shortly confirm this being fixed or not

**Comment by Duchenkuke** [comment]
also it would be great to know what files have been changed so I can incorporate the shader fix into my main gg installation.

**Comment by Duchenkuke** [comment]
Looks better than before for sure! Thanks

**Comment by Duchenkuke** [comment]
Hey @LeeBamberTGC 
It would be great to know wich files have been replaced in the current Public Preview!
The Standalone folder for my game is huge and it contains many customized files. I would like to make the upgrade manually - But for this I need to know wich files to replace. Could you please send me some info on that ?

**Comment by plemsoft** [comment]
@Duchenkuke It was a shader only change , so you just need to copy over:
Scatter.fx
Scatter.blob
From "\Files\effectbank\reloaded\" :)

**Comment by LeeBamberTGC** [comment]
@Duchenkuke This is the FX shader file of the current one I have, does it match yours:

// Lightray Shader
#include "constantbuffers.fx"

float4 SkyColor : Diffuse
<    string UIName =  "SkyColor";    
> = {1.0, 1.0, 1.0, 1.0f};

matrix ViewProjection:ViewProjection;
matrix ProjMat={0.5,0,0,0.5,0,-0.5,0,0.5,0,0,0.5,0.5,0,0,0,1}; 

float3 LightDir={-0.0,-0.5,-0.723};
float Density=1.0f;
float AlphaAngle=1.0;
float LightRayLength=0.5;
float LightRayQuality=15.0f;
float LightRayDecay=0.975f;
float LightRayFactor=1.0f;
float4 ScrollScaleUV;
float SpecularOverride;

Texture2D BlackTexture : register( t0 );
SamplerState SampleClamp
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
};

struct InPut
{
    float3 Pos         : POSITION;
    float3 Normal      : NORMAL;
    float2 UV          : TEXCOORD0;
};
struct OutPut
{
	float4 OPos : POSITION; 
 	float2 Tex  : TEXCOORD0;
};

OutPut VS(InPut IN) 
{
 	OutPut OUT;
	OUT.OPos=float4(IN.Pos.xyz,1);
 	OUT.Tex=IN.UV;
	return OUT;
}

float4 PSScatter(OutPut IN, uniform int SampleNum) : COLOR
{
	float2 NewUv = IN.Tex;
	NewUv.x = 1.0 - NewUv.x; //PE: direction is inverse.
	float4 ScreenToLight=mul(ProjMat,mul(float4(-LightDir.xyz,0),ViewProjection));
	float2 DeltaTex=((ScreenToLight.xy/ScreenToLight.z)- NewUv )*sign(ScreenToLight.z);
	float thelength=length(DeltaTex);DeltaTex /=thelength;
	thelength=min(thelength,Density);DeltaTex *=thelength;

	float3 Scatter=0;
	float FallOff=1.0;
	DeltaTex /= SampleNum;
	DeltaTex *= LightRayLength;
	for (int i=0; i < SampleNum; i++)
	{		
	  NewUv += (DeltaTex*LightRayLength);
	  Scatter += (BlackTexture.Sample(SampleClamp,NewUv).xyz*AlphaAngle)*FallOff;
	  FallOff *= LightRayDecay;
	}
	Scatter /= SampleNum;
	float3 result = Scatter.xyz*SkyColor.xyz*SkyColor.a*LightRayFactor;
	float alphafactor = (result.x + result.y + result.z ) / 3.0f;
	return float4(result.xyz, alphafactor );
}

float4 PSNone(OutPut IN) : COLOR
{
	return BlackTexture.Sample(SampleClamp,IN.Tex);
}

// techniques   

technique11 ScatterLOW
{
	pass p1
	{		
        SetVertexShader( CompileShader( vs_5_0, VS() ) );
        SetPixelShader( CompileShader( ps_5_0, PSScatter(10) ) );
        SetGeometryShader( NULL );
	}
}

technique11 ScatterMEDIUM
{
	pass p1
	{		
        SetVertexShader( CompileShader( vs_5_0, VS() ) );
        SetPixelShader( CompileShader( ps_5_0, PSScatter(20) ) );
        SetGeometryShader( NULL );
	}
}

technique11 ScatterHIGH
{
	pass p1
	{		
        SetVertexShader( CompileShader( vs_5_0, VS() ) );
        SetPixelShader( CompileShader( ps_5_0, PSScatter(35) ) );
        SetGeometryShader( NULL );
	}
}

technique11 ScatterHIGHEST
{
	pass p1
	{		
        SetVertexShader( CompileShader( vs_5_0, VS() ) );
        SetPixelShader( CompileShader( ps_5_0, PSScatter(80) ) );
        SetGeometryShader( NULL );
	}
}

technique11 NoScatter
{
	pass p1
	{		
        SetVertexShader( CompileShader( vs_5_0, VS() ) );
        SetPixelShader( CompileShader( ps_5_0, PSNone() ) );
        SetGeometryShader( NULL );
	}
}

**Comment by Duchenkuke** [comment]
Thank you!
And what about this issue? 
I need to know what files have been changed so I can assure the players that the game has been updated properly. Thank you.
https://github.com/TheGameCreators/GameGuruRepo/issues/2449#issuecomment-1153891843
