### ISSUE TITLE
Editor Camera Jerky Movements

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1446]
The editor camera will sometimes jerk to a random position. 

One way to reproduce this mouse over either File, Edit, Help, or Temp in the top left. Then right click in the 3d Level Editor anywhere on the screen and the camera will jerk to a random spot. 

https://www.youtube.com/watch?v=2BarKOLqNgM

**Comment by LeeBamberTGC** [comment]
This was related to the camera speed over terrain. We have amended this for smoother camera flight, and slower movement when up close to ground objects.

**Comment by Kitakazi** [comment]
hmm as of the latest update this bug still exists. Same thing as the youtube video I linked above. Place mouse on File, Edit, or Help then move mouse to the editor and press Right Click and the camera will rotate to a random spot.

**Comment by rvanner** [comment]
Yes this is a know issue which I think I reported in another report some time ago. Easy way to make it happen is to hold right mouse down in the right hand window and move the mouse over the 3D view and the camera view will change significantly. It needs to wait for the right mouse button to be released.
