### ISSUE TITLE
Don't allow characters to be scaled, it will cause too many issues

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1450]
We don't want to allow this for example;

![image](https://user-images.githubusercontent.com/1503593/137471002-4e995077-860f-420f-9909-969f98638aea.png)

**Comment by ZakJudges** [comment]
@LeeBamberTGC @rvanner Will do! Should the scaling be restricted to non-advanced, or all users? :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges All users.
