### ISSUE TITLE
MAX 2021.10.15 - Soundinzone Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1458]
If a you walk into a zone with Soundinzone script it will play the audio as expected. 

But it should only restart the audio if it has finished playing, rather than restart every time to leave/enter zone.

**Comment by LeeBamberTGC** [comment]
@OldFlak Changed soundinzone behavior so sound continues to play (and does not restart if you leave and re-enter zone)

**Comment by OldFlak** [comment]
It stops altogether now 
- the description indicates it will play the sound when you enter the zone
- so should it not play the sound again if you re-enter the zone?
- - _the problem before was it would keep restarting_ the sound even if it had not finished playing yet

The way it works now is essentially the same as the plrinzone script, which destroys the zone so it can't be played again

:)

**Comment by OldFlak** [comment]
@LeeBamberTGC 
_Right now it will play the sound once when you enter the zone. If you leave and enter before the sound has finished it will not repeat the play. If you leave the zone and enter sometime later, it will play the sound again._

Yes, this is how it should work - but it doesn't. In my tests it only plays once. If you come back to the zone at a later time, it _doesn't_ play the sound again.
