### ISSUE TITLE
Collision shape issue?

### ISSUE THREAD

**Issue by ivanski1983** [TheGameCreators/GameGuruRepo#1465]
I have imported my own bridge and collision shape is set to polygon because the convex hull is not working correctly for this object. When I initially place the bridge the collision shape is correct (image1), but when I rotate the bridge the bridge the collision shape is off (image2)

![image1](https://user-images.githubusercontent.com/78671386/137607632-7c3af546-427f-442d-a030-e8eb1e57f774.png)
![image2](https://user-images.githubusercontent.com/78671386/137607633-abca89a0-c8e3-4212-9562-c483098d0cbf.png)

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke Could you confirm your import model issue still exists, and if so, post a new issue with new shots and perhaps email me the model in question. I will assign to Zak as part of the model importer fixes.

@ivanski1983 Could you email me your custom bridge to lee@thegamecreators.com so I can reproduce the issue. Unless you know of a built-in asset that shows the same issue.

**Comment by LeeBamberTGC** [comment]
@ivanski1983 Thanks for sending the bridge model. With the latest internal build, I imported the model and rotated along the X by 90 degrees to fix the orientation issue (was pointing straight up), then applied some textures and imported as a static polygon model:

![image](https://user-images.githubusercontent.com/35840583/155132056-d919a2d7-c9fe-4544-afc3-0af9fa968961.png)

This rotated and worked fine over multiple level tests.  I then switched it to HULL DECOMP which is what you ideally want as it allows for concave structure.  I also rotated this several times in multiple level tests, no problems:

![image](https://user-images.githubusercontent.com/35840583/155132326-5c640421-cf68-4126-b91f-60ab86d8b28b.png)

I finally selected the CONVEX HULL (not an ideal physics shape for this model), and although I could not go ON the bridge I could slide alongside it from any rotation:

![image](https://user-images.githubusercontent.com/35840583/155132300-e919e33a-bfe5-444e-b930-2d6c4f7b7355.png)

Not able to produce this one, can you do a similar step by step with this Fridays release and let me know if you can reproduce what I have done above. Thanks.
