### ISSUE TITLE
AI getting stuck

### ISSUE THREAD

**Issue by frantic999** [TheGameCreators/GameGuruRepo#1466]
I have designed a level with game guru and I'm trying to get the AI to work, so far it works on a flat new map, but not on a created one. I have moved the character away from objects they either don't attack or do a stuck jiggle walk if i set a way point,i have changed messed around with settings ect ,i emailed customer services who suggested posting here

https://youtu.be/HY6iYfX2PX4 
https://www.youtube.com/watch?v=IG8hC2MU1aU&t=76s

**Comment by synchromesh62** [comment]
Confirmed on testing.
Initially it seems to work fine but at some point they just lock up as the video supplied shows.

**Comment by frantic999** [comment]
would the level of detail in a map cause the ai not too function?
tried on a blank map with a default character worked
added to my map same character didnt work
went back to first map worked added more buildings still worked
my maps have alot of detail in them thats the only thing i can think it being
im on a decent enough pc just not sure about how good this game engine is and what nit can handle

**Comment by frantic999** [comment]
I'm making an a warehouse map kind of like goldeneye  ,so far the AI is holding up but the map is still quite small an unfinished .I figure the AI might work better in a smaller space if it has walls to reference ,will post the results

**Comment by plemsoft** [comment]
@frantic999 Thanks for reporting this issue, your videos do not work, could you sent me your level.fpm , where one of the guards are frozen, this way im able to debug it , if you do not want to upload it here, please e-mail the level to me at plemsoft@plemsoft.com , please mention this issue in the e-mail , thanks for your help :)
