### ISSUE TITLE
GGC (Classic) Issue: "Camera Zoom"

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1469]
From the TAB-TAB menu, it seems the "camera zoom distance" slider doesn't seem to actually do anything. Not to be confused with Camera FOV or Camera Distance.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, we dont have a "camera zoom distance" in tab tab ? do you mean "Camera Zoom Percentage" if so its used in LUA only , check out "gameplayercontrol.lua" GetGamePlayerStateCameraFovZoomed() Itsused to control the player FOV :)
