### ISSUE TITLE
Checkpoint problem for third person character

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#148]
**Checkpoint problem** for third person character
Checkpoint character in the third person at the time of testing, it works fine.
But:
**The checkpoint for the third person character does not work well after the save standalone.**
third-person character: After passing through the area Checkpoint - **If you die and start playing again** - finds a problem.
**The problem is that all the animations of the third character are destroyed
And the character moves like a fixed object.**
![01](https://user-images.githubusercontent.com/36647058/38196166-b035f25c-3696-11e8-831d-632bfde9f590.png)

**after save standalone:**
![02](https://user-images.githubusercontent.com/36647058/38196315-85c56df8-3697-11e8-8e43-357accb9a1da.png)

I tested this problem for all third-person characters.
They all have this problem.
Please test yourself and fix this problem

**Comment by Shahin3d** [comment]
It happens when that: pbroverride = 0

**Comment by HierToo** [comment]
@Shahin3d can you please test it again if this still exists? I can not replicate this bug.

**Comment by Shahin3d** [comment]
Hello
I had this problem when pbr was off.
I do not have this problem right now.
Because I use a on pbr rendering.
