### ISSUE TITLE
Blending/Smoothing is too weak and slider for speed of script does nothing

### ISSUE THREAD

**Issue by karmacomposer** [TheGameCreators/GameGuruRepo#1487]
When trying to smooth terrain, it is very weak. Large scale terrain changes cannot be smoothed very much. Either the editor needs a strength option/slider or the speed value causes more or less smoothing to happen.

**Comment by LeeBamberTGC** [comment]
@karmacomposer Solved many moons ago with the sculpt speed slider:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/22e71215-6562-46c7-a4b0-99fbf4d2bf4b)
