### ISSUE TITLE
Decals doesn’t keep its properties once the game launched its set back to default. Fire decals.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#1489]

**Comment by ZakJudges** [comment]
@Hamada880 Thank you for reporting this issue :) A fix has been added that should appear in this Friday's build

**Comment by Hamada880** [comment]
Tested it and it is working so far. Thanks for the efforts and the hard work👍🏻

**Comment by ZakJudges** [comment]
Great! Thanks for confirming, closing this issue :)
