### ISSUE TITLE
More Tweaks Required With The Ragdoll Constraints

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#1497]
![image](https://user-images.githubusercontent.com/35840583/138971805-5d2b3a9a-ba81-4f69-a137-33370d6b8dc1.png)

**Comment by ZakJudges** [comment]
@LeeBamberTGC I've made some more changes to the ragdoll setup. I haven't seen any twisting after testing, but if anything strange happens just let me know and I'll take another look at it :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Added for next internal build.
