### ISSUE TITLE
Zombie AI is BAD

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#15]
Even if some are saying that zombies have been fixed, I'm having the same issues I was reporting this summer. Zombies using "ai_fastzombie" script are close to unusable.

Slow zombies are better.

But the "fast" zombies" still remain stuck or glitch in a sort of invisible wall.

**Comment by Teabone3** [comment]
I completely agree. I just did a test last night and the fast zombies appear to be broken in some manner. They occasionally run at you then dart in another direction really fast.

**Comment by Teabone3** [comment]
I think the FPE files for those zombies need fixing to match the speed then. So this could technically be classified as a bug rather than an enhancement. Because they do not operate properly in their default condition.

**Comment by thecyrus** [comment]
Yes, animation matching and default speed changing, it should be simple to fix.

**Comment by Teabone3** [comment]
They appear to be working properly now in PP2 (2nd Public Preview)

**Comment by thecyrus** [comment]
@Teabone3 Why do you say that?

I just tried Fast zombie again in PP2 and they're the same.
Slow ones are better, and Fast ones need a speed reduction.
