### ISSUE TITLE
audio clipping / cutoff with automatic weapons

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#150]
I dont know what is causing this issue but gg has terrible ways to handle automatic rifles. The sounds are always cutoff and messy. Maybe we can get this right?

**Comment by LeeBamberTGC** [comment]
In the next build we have a new mode for FIRELOOP, when set to -1 it will use single-instance sound plays instead of looping the sound, makes for better audio and no cut off :)

**Comment by Duchenkuke** [comment]
oh my god thats awesome. Thanks so much!
