### ISSUE TITLE
Gun crosshairs are needed for the pistol and automatic weapon

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1501]
Hollie pointed this out to me yesterday! Can you add these in from GGC?

**Comment by Retrogamebloke** [comment]
I have to agree on having a crosshair. Some may well want to be ultra realistic, but some just want a bit of fun and having a crosshair surely helps many of us do that. I think it should be an option in Max, preferably in the final game settings as well so users can choose if they want crosshairs or not. It would also be a nice touch to be able to change the crosshairs colour when it is on target.
Why limit it to what other modern games do? Give us the option of both. A cross hair should be a simple change imo.

**Comment by mav3r1ck1981** [comment]
@Kasseyus this can be done via the game hud in the storyboard editor so can be closed
