### ISSUE TITLE
Max - Yellow editable area marker is no good - creates BAD experience

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#1502]
1. You set your editable area size.
2.  you start editing your terrain.
3. you spend quite along time setting your path ramps and all is looking great ( having fun)
4. Your edits are no where near the yellow barrier. Time to see what it looks like.
5. Press test run.
6. Walk along your path.. just getting to the good part of your work.. and MESSAGE
7. You cannot leave the play area...  I am no where near the yellow barrier it is miles away..
8. This is not a good experience.. you spend hours editing a level and you cannot use it.
9. Something must be changed - You cannot have someone obeying your yellow area then impose another invisible area on them.
10. Either the yellow area goes or you obey the Yellow rules.. if I have edited the terrain I must be able to walk it...

**Comment by ZakJudges** [comment]
This was fixed some time ago, closing this issue
