### ISSUE TITLE
memory issues

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1504]
this is how much memory MAX was using during a freeze up, no idea what it means, HOWEVER you smart lot might have the brains to know what would cause MAX to use 7 gig of memory and then crash!! 

:) 

![image](https://user-images.githubusercontent.com/68471279/139352949-d55ecfba-b668-4ab1-87f7-e675c4c74e06.png)

**Comment by fearlesswee** [comment]
@LeeBamberTGC AmenMoses on the Discord mentioned having 800 copies of the same building model eats up an absurd amount of memory at 3.5 GB, which hints at a possible lack of proper instancing? (The geometry, textures, physics shape, etc. should be loaded into memory once, then for each "copy" it only stores the position, scale, and rotation, which should only take up 80 kb of memory to store the pos/scale/rot information of 800 copies according to AmenMoses' calculations.)

I decided to test this independently on my own rig, and I've seen similar results.

![image](https://user-images.githubusercontent.com/56294129/139512044-296495af-3e1d-4e13-8902-3b8303be21c0.png)

Putting down a lot of instances of the same house model eats up a LOT of memory. I added numerous more houses to confirm:

![image](https://user-images.githubusercontent.com/56294129/139512104-4c9574b8-8a02-473d-a7fd-fcff879141e1.png)

Nearly 4 GB of memory wasted on a single model! Yikes!

In general, I've also been seeing less than great framerates on my 1660 SUPER, and there's a lot of hitching, especially when swapping weapons or when a character ragdolls. I think MAX needs a good long two or three weeks before Early-Access just working solely on optimization and bugfixing. At the moment MAX absolutely chugs and sputters performance-wise, which it absolutely should **NOT** be doing in such barren and simple levels.

**Comment by casigus** [comment]
okkkkk pokey. Was running max fine, was rather smooth, then the screens started flickering, and my AMD drivers crashed, theres no sign of over heating, tempatures are normal, and tripple titles run fine, yet max for some reason crashed the drivers, even turning 3 out of 4 of my monitors off. Had to do a full restart, but its deeply concerning when an error completely messes up the GPU drivers like that. PANIC'D, feared the worse! still feeling panicy after that!!!!

**Comment by plemsoft** [comment]
@casigus How many objects do you have in your level ? , just approximate :)

**Comment by casigus** [comment]
Oh on this one, a fair few, but and its running really good actually with all these objects in one place, the crash of all my pc and the amd drivers happened opening up the assets screen which tends to crash things quite alot or just slow down, the 17 gig max out happened with NOTHING on the map. so it can be all over the place really!

**Comment by casigus** [comment]
ok tracked down the time it crashed (again) on event viewer. 
!
![image](https://user-images.githubusercontent.com/68471279/139555720-a8ac9e1d-3720-4985-934e-97ed2de075f6.png)

![image](https://user-images.githubusercontent.com/68471279/139555728-9f130aaa-47c5-43e4-bcac-4ce788c9417b.png)

from the first crash

![image](https://user-images.githubusercontent.com/68471279/139555780-9ef544eb-b768-4a73-bfba-2ad73e035f49.png)

im no expect but there is indeed a memory issue with max.

**Comment by casigus** [comment]
the solution to get max functioning was to switch all the post processors off, works fine, turned the shadows off too. Im hundred percent convinced its a opptermizion problem.

![image](https://user-images.githubusercontent.com/68471279/139559208-a90651e1-1a93-4797-8545-141a4b5d7d51.png)

also the SOLDIER A.I just doesn't work, the only A.I ive ever had working is the zombie crawler, also the auto widget tool keeps flipping its self off, that tool should be on automaticly, its super usefull for placement. waters blank too, no water fog, but the engine runs quite well when all the settings are turned off, ALSO the scirpting wont let you change the script for trigger zones, (sound ect) the buttons just not clickable anymore.


![image](https://user-images.githubusercontent.com/68471279/139559247-8a1f838b-d1e0-4e9c-bbaa-62d48d577e30.png)

it appears developer mode for the zones wont function. 

andddddddddddd that's me done fore day!!! hope this helps :)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/139565165-00830db5-f316-4c7c-9489-1844b9be8add.png)

oh and this. seen this a FAIR few times, this happened on a small level.

**Comment by plemsoft** [comment]
@casigus When you have one of these huge memory use, could you make a copy of your "Guru-MapEditor.log" file and upload it here, that would really help, you find the log in your write folder. Thanks for your help :)

**Comment by casigus** [comment]
hello! CHECKED the folder, thertes no map editor log :(

**Comment by plemsoft** [comment]
@casigus You find it at this location on your system:

c:\Users\USERNAME\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log

Or if you use a custom write folder , it will be placed there :)

**Comment by casigus** [comment]
Oh. well. there we go!!! sorted!!! 😄 hope that helps!!



________________________________

**Comment by plemsoft** [comment]
@casigus I do not see the "Guru-MapEditor.log" here , did you upload it yet ?

**Comment by casigus** [comment]
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/7460832/Guru-MapEditor.log)

oh boy. tempormental internet here. replied via email but the attachment didn't send over. here it is. again.

**Comment by plemsoft** [comment]
@casigus Memory do not really get high in the log you sent here, could you wait until you see a high mem use, and then after that , sent a new "Guru-MapEditor.log"  , Thanks for your help :)

**Comment by casigus** [comment]
then your map log file is broken. no program should be using this much memory!

but aye next time i get the crash Ill get that sent over too you :D see what magic you guys can do ahah. no thanks needed, happy to help!! :D 

![image](https://user-images.githubusercontent.com/68471279/139869647-84d282a6-77d1-43fe-adbd-3175e5f22197.png)

**Comment by plemsoft** [comment]
@casigus Memory has been optimized since this issue, could you let me know if this is still a issue for you , Thanks :)

**Comment by casigus** [comment]
oh yes memory usage is less, however it does jump back up when calculating nav meshes, but put that in as a report.
