### ISSUE TITLE
Game Guru Crash

### ISSUE THREAD

**Issue by r2ks** [TheGameCreators/GameGuruRepo#1508]
when I go to add a object and click on Buildings then the game guru crashes
![GG Error click buildings](https://user-images.githubusercontent.com/93450376/139560766-e104232f-3daa-4027-8d26-49916bfedecd.png)

**Comment by PaulFox12** [comment]
This also happens to me, even in the latest build (2021.11.12)

**Comment by plemsoft** [comment]
@r2ks Thanks for reporting this issue, this has been fixed and will be in the next update :)
