### ISSUE TITLE
WATER. 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1510]
Water at 24: 

![image](https://user-images.githubusercontent.com/68471279/139590007-ca67abd0-b807-4b0c-b159-99d1886eb84e.png)

water at 25:

![image](https://user-images.githubusercontent.com/68471279/139590033-c1d79ca2-6efb-46b4-8447-d585b2898c60.png)

water at 26:

![image](https://user-images.githubusercontent.com/68471279/139590049-eaf8146a-ba95-4eb1-b780-3d5ba9710491.png)

**Comment by rvanner** [comment]
@plemsoft The value changes for water height are too sensitive. Need a better scale.

**Comment by plemsoft** [comment]
@casigus This should be fixed in the latest version , and be more easy to adjust :)

**Comment by casigus** [comment]
fantastic. if any more water problems pop up ill report it in.
