### ISSUE TITLE
Incorrect 'back' arrow action in MAX

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#1511]
If in the model import screen you click on the 'back' arrow it goes to the Game Storyboard screen. 

https://vimeo.com/640941087

**Comment by rvanner** [comment]
This does need tidying up. It will probably be sorted next week once the Storyboard is called up properly.

**Comment by AmenMoses** [comment]
Any idea when this might get fixed?

**Comment by rvanner** [comment]
@ZakJudges Can you deal with this one today please?

**Comment by ZakJudges** [comment]
@rvanner Will do!
