### ISSUE TITLE
ai doesn't work

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1512]
![image](https://user-images.githubusercontent.com/68471279/139750932-a373658f-eb88-44f8-89c5-255c25a0dd94.png)

the standard chomper, lovely design, but this and the soldiers, NONE of the AI works, hasn't done for months, even after fresh installs, it just sits there. IN the builder its animated, but when you go to test mode, just doesn't move or respond.

**Comment by rvanner** [comment]
@casigus Only the character in the Showcase section uses the latest AI. Once the AI script is completed we will be updating all the characters. I will still mark this for Lee to check though. Thanks for the report.

**Comment by casigus** [comment]
oh. opps ahahahah sorry!!!

________________________________

**Comment by ZakJudges** [comment]
This was fixed some time ago, closing this issue
