### ISSUE TITLE
GameGuru Max - menu editor and Russian letters, Cyrillic. Is this a bug?

### ISSUE THREAD

**Issue by janekste** [TheGameCreators/GameGuruRepo#1515]
Menu editor and fonts. If GameGuru Max supports TrueType fonts, then why can't I enter text in Russian? When I type a text in Russian, I get question marks.

I thought that TrueType font support would allow me to create games in any language. Why only English again?

ARIAL font. In the menu editor, I can choose different fonts. I see that there is an "Arial" font in the list. This font in Windows 10 supports Cyrillic, Russian letters. Then why doesn't this font work with Cyrillic in GameGuru Max? Is this a bug?

![game menu russian fonts](https://user-images.githubusercontent.com/55485525/140048335-8fc5bae0-1db4-4963-97bb-d1b9164436e4.jpg)

**Comment by plemsoft** [comment]
@janekste Thanks for reporting this issue, this has been fixed for "Default Font" and Arial, ready from the next update :)

**Comment by janekste** [comment]
@plemsoft I confirm that I can now create a game menu in Russian. Bug fixed. It is very important for me to be able to use Cyrillic, Russian letters. Thank you for your work.

I hope that in the future the trigger "Text Zone" will also display Russian letters. The Cyrillic alphabet should work in all GameGuru Max scenarios, not just in the menu editor. But about this, I should probably create a new separate topic.

![русский шрифт меню](https://user-images.githubusercontent.com/55485525/155821882-e8140d0f-734f-4267-b99a-23e83fbe5cbe.png)
