### ISSUE TITLE
Possible Slowdown Issue/Reason.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1517]
I have been playing about scripting and due to a bit of a fluke editing the map, spotted this.
![image](https://user-images.githubusercontent.com/44620846/140237599-e2334fd8-a418-4e80-b0ac-61c80bcb8ac2.png)
You can see the shadows and such are all rendered under the terrain, including swaying with the water. Normally you can't ever see this as the camera never goes below the terrain, but my script has no such limits set so got to see perhaps a reason why speed has fallen significantly in the last month or so.

https://user-images.githubusercontent.com/44620846/140238472-2b39a3c2-1cea-4c19-8f15-db9df6c95de0.mp4

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
