### ISSUE TITLE
Terrain pallete not working

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#152]
not sure if its just me but I cannot use custom textures on the terrain, if you right click the terrain pallete and choose a custom texture it does not load it paints the original texture instead.

can anyone else confirm this?

**Comment by plemsoft** [comment]
Works fine here, my guess is that some files are locked for some reasons, try to go in to the folder "\files\levelbank\testmap\" and delete ALL files located here, then give it another try. do it work ?

**Comment by GraPhiX-Guru** [comment]
Hi Preben

tried it and no change here is a video with the issue https://youtu.be/OnPsXp11r7E
regards
Kevan

**Comment by GraPhiX-Guru** [comment]
Yes I always run GG in admin mode, LOL I have posted on the forums this morning asking for the manifests of the exe's to be elevated to admin mode automatically ;)

https://youtu.be/fwEAl1j2tFU

yes the dds file is created I can choose any of the textures already there but not a custom one as there been any change to the texture requirements the ashphalt texture is one I created last year, I have created a forum post I will upload this texture there and you can try it :)

**Comment by GraPhiX-Guru** [comment]
link to forum post https://forum.game-guru.com/thread/219552

**Comment by plemsoft** [comment]
Hi GraphiX
ahh i see thats a easy one :) , the png need to be in 32 bit format , in the code - Decompress/Copy from a 24b to our texture_d 32b will not work.

So just load your png and save as 32 bit.

**Comment by GraPhiX-Guru** [comment]
yep that fixed it strange though it worked in the DX9 version
