### ISSUE TITLE
Fullscreen on first launch of update.

### ISSUE THREAD

**Issue by Zorgo33** [TheGameCreators/GameGuruRepo#1520]
This is not that big of a deal, but i figured to post this because i think it's strange to have it and needs removal. Basically, the engine runs fullscreen on first launch of any updated versions, on the next launch, it's normal. As i said, not that big of a deal but it's pretty weird and pointless and shouldn't be hard to remove : )

**Comment by plemsoft** [comment]
@Zorgo33 Thanks for reporting this issue, this was fixed in this Fridays build :)
