### ISSUE TITLE
testing so far update.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1521]
smooth as hell, running super stable, moving around so much smoother, building loading the assets super fast, feels like this release is the most stable version thus far. yet to find any problems bugs, but ill report them in as soon as possible.

build a big level, no slow downs, 

super impressed. 

![image](https://user-images.githubusercontent.com/68471279/140591393-eb845321-400a-49cd-bfb6-a3dcc6d38f1a.png)

**Comment by rvanner** [comment]
@casigus That's great to hear.

Can you post this type of feedback into the forums? We use the GitHub issues board for problems.

Thanks!
