### ISSUE TITLE
ai not fuctional part 2/terrian crashes

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1522]
the walking around works fine, the soldier ai doesn;t, the zombies do attack which is great but these guys don't

![image](https://user-images.githubusercontent.com/68471279/140621711-e0d04a60-8687-4225-8b58-e8a38b4f5943.png)

when clicking the soldier from the show case, 
![image](https://user-images.githubusercontent.com/68471279/140621741-4cdfd01b-d57b-4ecc-8edc-f09784620d2a.png)

its phumb nail completely changes, but either way it wont attack.

just stands there happy as larry.

![image](https://user-images.githubusercontent.com/68471279/140621758-6b55c858-410f-49d1-9d55-2f6a767d9a2c.png)

-engine restarts so much quicker, however the terrian generator still causes some crashes from time to time! but things feel smoother,

**Comment by LeeBamberTGC** [comment]
@casigus Would be great to split these issues up so we can deal with them one by one, and ask questions on specific issues. Dealing with "terrian generator still causes some crashes from time to time" does not really pinpoint a bug that we can quickly fix, we would just be rooting around in the dark in the hopes of fixing something, somewhere.

**Comment by casigus** [comment]
okiies :D best of luck finding the cull prit. other than these two problems, the engine is running 100% better :D crashes are few and far between! great work.
