### ISSUE TITLE
Once you have about 6 or more Spotlights on the map selecting a Spotlight causes big frame rate drops

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1523]
Once you get about 6 or more Spotlights, once you select one or create a new one it will lag hard untill you deselect the spotlight.

**Comment by LeeBamberTGC** [comment]
@plemsoft I think stage one is finding out why 6 spotlights hurts performance, and then if this is a Wicked limitation for real-time lights (not sure at all about that), we could set up some virtual lights and only use the real spot lights for the nearest 5 spot lights closest to the player.

**Comment by Kitakazi** [comment]
It only lags in the editor once you select the spotlight, once you deselect or go into test game everything runs smooth.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Great additional info, and suggests Wicked is fine for the many lights option, and is in fact some editor specific slow down caused when the spot light has been highlighted for action.

**Comment by Kitakazi** [comment]
Could be related but adding in trigger zones also drops frames hard when one is selected. Once it is placed and not selected in editor everything runs smooth but on an empty map with nothing but spot lights and trigger zones, selecting or adding in a new trigger zone dropped frames from 60 to low 40s. Basically same thing that happens when adding/moving spot lights. 
Does not happen with the Player Start Marker though. 


![image](https://user-images.githubusercontent.com/51464873/140684592-404926a0-fb59-43ab-b274-918327070f85.png)

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue, this has been fixed for the next update, the env. probes was updated each frame (a slow process) when a spotlight was selected, this has been change so it only update the probes when you release the mouse :)
