### ISSUE TITLE
Animation loop not seamless

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#1528]
https://vimeo.com/643646724

This is the "Walk_Loop" animation and it appears as if it is ending a frame too early or something.

A lot of other loops in other models are similarly non-seamless  so I'm thinking it is a problem in the code rather than the models themselves.

**Comment by fearlesswee** [comment]
Noticed this on weapons too. If you walk around holding the default included pistol or AKM you can see the walking animation doesn't loop very well, it noticeably "hitches" each time it starts over.

**Comment by LeeBamberTGC** [comment]
@fearlesswee Solved for next build, using new interpolation transition for all Wicked engine animations now, nice and smooth!

**Comment by AmenMoses** [comment]
By next build do you mean later today or next week, cos I can't see any change in the build that I just updated to.

**Comment by LeeBamberTGC** [comment]
@AmenMoses The current public build reintroduced animation lerping to smooth the transition between the current (last) frame and the first frame, and removes the sudden 'flick' that we saw before. There could still be an issue of the looping animation itself has not been lined up for seamlessness, which requires the end frame to match the first frame.

**Comment by AmenMoses** [comment]
This is with the latest build that downloaded a few minutes ago:

https://vimeo.com/646159914

Also I notice the rabbits having a bad day!

**Comment by rvanner** [comment]
@AmenMoses The Rabbits made my day! :-)

**Comment by LeeBamberTGC** [comment]
@AmenMoses I have reproduced the animation glitch at good-speed movement. Related to the positional movement deltas rather than the animation loop itself. Fixed for the next build :)
