### ISSUE TITLE
PlayAnimation( e ) does not stop at end of animation

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#1529]
Using the following Lua:

		SetAnimationName( e, "Walk_Loop" )
		PlayAnimation( e )

With a standard character the animation continues on past the end of the "Walk_Loop" frames and plays though all frames that the character has.  

My expectation is that when the end frame has played out the animation should stop and either GetObjectAnimationFinished( e   -- or obj?  ) should return 1 or g_Entity[ e ].animating should change to 0, neither of which seem to occur.

**Comment by LeeBamberTGC** [comment]
@AmenMoses I will make a fix for this evenings internal build so you can test the new functionality, which will be that the played animation stops on its last frame and stays there.

**Comment by AmenMoses** [comment]
Will it also set g_Entity[ e ].animating to 0 or  GetObjectAnimationFinished() return 1 so I can detect when it has fiinished?

**Comment by LeeBamberTGC** [comment]
@AmenMoses Yes the .animating will be set to zero when the play is finished, and GetObjectAnimationFinished will also return 1 at this event too :)
