### ISSUE TITLE
crash during test mode!

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1530]
hello ! noticed max now crashes every time during test mode, heres a screen shot of the event. Hope it helps :)

![image](https://user-images.githubusercontent.com/68471279/140834775-a7861462-c82e-4b22-bda6-274e74557991.png)

![image](https://user-images.githubusercontent.com/68471279/140834808-442be6dc-a0b1-4181-8a0f-6aeb43911656.png)

![image](https://user-images.githubusercontent.com/68471279/140834828-0a95d796-c583-430f-910e-441d11a975d9.png)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Can you chase this down and see if we can reproduce it at this end, thanks!

**Comment by casigus** [comment]
UPDATE: ive moved max and myy assets to an SSD and it has improved performance for sure, less crashes and quicker load times, but not everyone will have ssds. Hope you find out what's causing this, however as you said in wednesdays live stream here will be memory improvements in the next build so Ill run it through the tests with that see if we get any of these issues. :)

**Comment by ZakJudges** [comment]
Hi @casigus, thank you for the report. The next time the crash occurs, could you attach Guru-MapEditor.log, along with a description of what you were doing in test mode immediately before the crash, or a video would help too. That would allow me to hopefully reproduce so we can work on a fix :)

**Comment by casigus** [comment]
sure thing!!!!

________________________________

**Comment by casigus** [comment]
once again theres no map log, but have gathered all the crash infomation from the event log. 

![image](https://user-images.githubusercontent.com/68471279/141473219-3a422c7c-f03b-4e12-95e8-1234d5f9a322.png)

![image](https://user-images.githubusercontent.com/68471279/141473243-1793e73a-050d-4d97-b9ec-7011ebfc54cc.png)

[Report.txt](https://github.com/TheGameCreators/GameGuruRepo/files/7527793/Report.txt)
![image](https://user-images.githubusercontent.com/68471279/141473259-1515ab6d-d962-40e4-bace-7c41863753f2.png)

had to convert the the report to  txt file as the forum wouldnt allow me to attach the "report.wer" file. not sure if any of this will help

the crash in max completely shut down my system, everything freezing up. its been doing this in every update from the first time I joined the testing! 

MAX can't seam to handle a some assets, but because I have a fair few, i can't pin point which ones exactly. 

Ive built maps with entire cities and they've been fine, yet built maps with only a few assets and itt becomes unstable as hell. 

hope you can find the problem.

**Comment by casigus** [comment]
**<Keywords>0x80000000000000</Keywords>**  appears to be the keywords, which according too google is:

System file corruption – As it turns out, this particular issue can occur due to system file corruption. If you’re getting constant Event Viewers with this error, you should be able to resolve the issue by repairing Windows files and fixing logical errors with a utility like SFC or DISM.
Corrupted Visual C++ Redist Packages – Improperly installed or corrupted C++ Redistributable packages can also be responsible for constant errors of this type. Several affected users have reported that they managed to fix the problem by uninstalling every Redist pack and then reinstalling them cleanly.

**Comment by LeeBamberTGC** [comment]
@casigus If the crash happens quickly before a LOG file can be created, try this debug build as it should show you a dialog when it crashes out. Send me a shot of this dialog and I will know more. Remember to backup your real MAX exe before doing this:

https://drive.google.com/file/d/14WrHMqFeGwsvFqLI2f69zqlzjTPpTp5l/view?usp=sharing

**Comment by casigus** [comment]
ON it :D ! shall get that done now for you!!

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/141479523-f2ce0d6f-91cc-4e08-bd53-4c35b8e9d3e4.png)

this is what happens when trying to luanch Max :)

**Comment by Granada1** [comment]
Hi casigus , this link might help you out
https://windowsreport.com/program-doesnt-start-error-0x000007b/?amp

**Comment by casigus** [comment]
with respect, this only happens in max, and none of the other software on this pc :) its a max issue.

**Comment by LeeBamberTGC** [comment]
@casigus Alas I was hoping for a source code file and line number. Can you double check you extracted this EXE:

https://drive.google.com/file/d/14WrHMqFeGwsvFqLI2f69zqlzjTPpTp5l/view?usp=sharing

And copied it into the root folder. Maybe have the old and new side by side, and show properties of each so I can see, thanks!

**Comment by casigus** [comment]
aye its the correct one, 
![image](https://user-images.githubusercontent.com/68471279/141497754-251a6306-c70e-49c7-9bfd-17e205e2caf4.png)

and it just said nope.  same error,  it refuses to run that .exe :( sorrry. 
![image](https://user-images.githubusercontent.com/68471279/141498304-38f8aae0-9cb6-4f3b-9cc1-650763ca7c39.png)

**Comment by ZakJudges** [comment]
@casigus Does the problem persist when MAX is installed on the same drive as Windows?

**Comment by casigus** [comment]
i can't install it on the same drive as windows, the windows ssd isn't big enough to install anything to it aside from the OS. :)

**Comment by ZakJudges** [comment]
@casigus By any chance are your J: or F: drives external?

**Comment by casigus** [comment]
j is external, but did have it on an internal (f) and same results, J is an external SSD hooked up to usb 3 via a sata too usb cable, ran red dead 2 off this thing with ease. 🙂

________________________________

**Comment by ZakJudges** [comment]
Shot in the dark here, but could you try moving your MAX install to an internal drive (if not already there), replace the exe with the debug build that Lee sent, and then run the exe as an administrator? :)

**Comment by casigus** [comment]
i already have it on a internal drive for a situation like this! yes Ill give that a go now, see if lees exe works !

________________________________

**Comment by casigus** [comment]
yeah. no joy with that saddly!!! worth a shot !!! 🙂

________________________________

**Comment by casigus** [comment]
and its working. the update appears to have sorted what ever was causing that crash out. great job guys!
