### ISSUE TITLE
Objects inside locked objects should not also show as locked

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1532]
This building is locked in the Level Editor but the barrel is not locked and yet it shows with a red outline;

![image](https://user-images.githubusercontent.com/1503593/141096263-7ef1ecc7-abc5-4b92-b449-4470871fab8d.png)

Maybe a different method is needed.

**Comment by plemsoft** [comment]
@rvanner Its the same as this: https://github.com/TheGameCreators/GameGuruRepo/issues/1248
We dont really have another system for this at the moment ?

**Comment by rvanner** [comment]
OK, I will close this one.
