### ISSUE TITLE
Basement Collection Doors are not Working

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1534]
![image](https://user-images.githubusercontent.com/44620846/141219875-4dfa18e9-4944-49a2-8a75-a75925b0b8c4.png)
Drop any of these doors in an empty map and all have issues. None have door script attached. When you add one manually it then fails to work in various ways. Some don't animate, but still allow you through, some do nothing and some fall through the floor. The ones included with the buildings collection work a lot better, but still lose collision when opened, which these days is a bit old school and easily fixed. Also you get a message when you can open the door but not when you can close it.

**Comment by LeeBamberTGC** [comment]
@rvanner These came from a third party source and added to our library as static objects for scenery creation. If we want them as functioning doors, we need an artist to rework the door partts in the same way we have the Buildings Collection doors, that is, centered at 0,0,0 so the door is hinged, ready for future physics, and animating an open sequence, followed by a close sequence.

**Comment by rvanner** [comment]
@LeeBamberTGC Mark has fixed these doors, I'll email them to you for the next build.

**Comment by LeeBamberTGC** [comment]
@rvanner Yikes, need more work here.  The door DBO have black base color so they show up black. Also they are hinged in the MIDDLE of the door, should be at the edge of the door where it would swing open, etc:

![image](https://user-images.githubusercontent.com/35840583/141925114-cb6985f6-2e18-4a24-a71d-60676ab19b4e.png)

Animation does seem fine, however, but keep the door to swing out only 89 degrees so it would not go through a wall if there was one on the adjacent side. Thanks!
