### ISSUE TITLE
Terrain Generator Shadow

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1535]
![image](https://user-images.githubusercontent.com/44620846/141222363-5d1ddbc9-e1e6-4102-b52b-04471f740472.png)
What is that? Something is casting a shadow. I thought it could be from the min-map display, but turning it off make no difference.

**Comment by rvanner** [comment]
@plemsoft Here's a video of the issue;

https://youtu.be/wAJkenFlfPc
