### ISSUE TITLE
Importing a Character with animations from Mixamo no longer works

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1537]
Download a character and animations from Mixamo and try to import using the importer. It doesn't load the animations. Worked fine in previous versions.

**Comment by rvanner** [comment]
@Kitakazi Can you share a model that worked before and now fails?

**Comment by Kitakazi** [comment]
[test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7530361/test.zip)

**Comment by rvanner** [comment]
Thanks @Kitakazi 

@ZakJudges Please try to import the shared model into MAX.

**Comment by Kitakazi** [comment]
The model is named xbot the other file is an animation downloaded from mixamo.

**Comment by Retrogamebloke** [comment]
I have also seen this. It used to work ok (bar my reported scale issue) but now it refuses to load more than one animation up. It does however load a dbo I made a few versions ago with anims still intact.

**Comment by Kitakazi** [comment]
Any update on this?

**Comment by ZakJudges** [comment]
Hi @Kitakazi, I was able to successfully import xbot.fbx and taunt.fbx. Afterwards I opened the importer with xbot.dbo and loaded taunt.dbo with the "Load Animation File". I repeated this process with another animation from mixamo.com and was able to use xbot.dbo with multiple animations. 

Alternatively, if you have already imported the animations, you can create a text file that lists which animations the model should use. You can then press "Load Animation File" and select the text file, which will apply the animations to your model. I have attached an example from the software for you to reference.

[fox.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8152488/fox.txt)

I do think the current implementation isn't very user friendly, so I will mark this as an enhancement. The current method does not allow for importing animations that do not have any mesh data. Having the "Load Animation File" be able to import the animation and apply it to the object that is already imported would solve this.

**Comment by Kitakazi** [comment]
@ZakJudges 
Ok that does work for me as well. But before I posted this on github the way it worked was that once you opened the .fbx of the character you could select load animation and then select the animation.fbx and it would add it to the character right there inside the importer which was super easy and seemed to work well? There was no need to create the .dbo and then go back and reopen the .dbo and then import the animations. 

But it does work following your steps so I guess I can close this one.
