### ISSUE TITLE
MAX Issue - Enable Snap Mode - Use Grid Position - Clicks/Select Entity Moves It

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1542]
Hello. With Enable Snap Mode and Use Grid Positions enabled, every time I click an entity to select it, it moves. The movement amount corresponds to the Grid Offset settings. Selecting an entity should not move it.

**Comment by ArgentArts** [comment]
Do you need a video showing this happening?

**Comment by rvanner** [comment]
@ArgentArts Yes we're aware of this and will be fixing it this coming week.
