### ISSUE TITLE
GGC Issue: Allied Knight Animation 

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1544]
Sometimes allied knight will slide around without walking animation. This occurs if you he gets blocked from being able to follow you and you go further enough away and go back to him.

**Comment by casigus** [comment]
hai! got some of your stuff from the store. really like your work :D yeah ive had some issues with animations not getting any working full stop. SOME  do, but the majority dont, not sure if its simple as they are not cross compatible!!

keep up the good work :D

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, i was not able to reproduce it but find a error that could cause this, so please give it a good test in the next update :)

**Comment by LeeBamberTGC** [comment]
Pretty happy to follow me:

![image](https://user-images.githubusercontent.com/35840583/145673735-89a0924e-f74d-4bac-ab48-6cf5cd21ba1d.png)
