### ISSUE TITLE
Feature Request for MAX - Keyboard Shortcuts for Translate, Rotate, and Scale

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1545]
I often work with the gizmo/widget for translating, rotating, and scaling an entity. Currently, to switch between modes, we have to leave the entity and go to the top of the right-side panel to click a button to change modes. I would like to see simple keyboard shortcuts added to switch between modes (translate, rotate, and scale). I know about the rotate shortcut that, when pressed, rotates the object. This is not what I am looking for. Instead, I just want to change the mode I am in so I can manually adjust a selection via the mouse.

Thanks.

**Comment by rvanner** [comment]
@ArgentArts Nice idea. Do you have a suggestion for the hotkeys to do this?

**Comment by ArgentArts** [comment]
The common hotkeys on most programs (from 3D modeling programs to other game engines) is to use the W, E, and R keys. W for Translate, E for Rotate, and R for Scale (yep, scale, not rotate). However, I can see how these might not work since W is used to move forward as you would in a game. Therefore, I might suggest simply 1, 2, and 3, if they are not being used for something else.

**Comment by rvanner** [comment]
@ArgentArts I think keys 1,2,3 makes sense due to existing keys being taken up.

@ZakJudges Please add this ability to the product.

**Comment by rvanner** [comment]
@ZakJudges I know that we changed the position, rotation and scale into one list but it would be good to have the quick keys for when the 3D gadget is on screen. So you can quickly move between movement, rotation and scale. Can you add it back in please?

I also noticed that when the gadget is selected you see these three buttons which are of no use;
![image](https://user-images.githubusercontent.com/1503593/153367930-e3d0299e-a304-457f-a9d3-248dc4bb8f49.png)

**Comment by ZakJudges** [comment]
@rvanner Currently, the buttons will show up when "Enable Widget when Needed" is selected, and they should allow you to change between the Position, Rotation and Scale widget without having to use the keyboard. When the widget is displayed, you can use F2,F3 and F4 to switch between position, rotation and scale, but I could change these to 1, 2 and 3 if you like?

**Comment by rvanner** [comment]
@ZakJudges Ah good point! Keep them as they are. Closing this now!
