### ISSUE TITLE
GGMAX - Feature request - double clicking level in storyboard to edit

### ISSUE THREAD

**Issue by PaulFox12** [TheGameCreators/GameGuruRepo#1547]
Being able to double click a level in your project storyboard to have it open in the editor, currently no way to quickly edit a level in your storyboard other than closing storyboard>File>Open Level

**Comment by rvanner** [comment]
Yes, it's on our list to do this with a click on the thumbnail screen shot.

**Comment by PaulFox12** [comment]
Fixed in build 2021.11.19
