### ISSUE TITLE
POLY poly polyyyyyyyyyyyyyy GONE

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1548]
![image](https://user-images.githubusercontent.com/68471279/141651370-f0e7d4e1-ab8a-4945-b546-53848414730f.png)

HellO!!!

SO. a fair few of the assets have broken, both the max assets and my own, with some turning from poly to box, and even when changing them to corvexx or poly again they still have the same  collision of a box'd object meaning you can't pass  through.

**Comment by ZakJudges** [comment]
Hi @casigus, So I can reproduce, would you be able to make a new level, place a couple of stock max assets down that show the issue. Then save the level and send it? :)

**Comment by casigus** [comment]
sure thing ill get that done for you 🙂

________________________________

**Comment by ZakJudges** [comment]
Hi @casigus, this issue should now be fixed. Could you confirm when you create a new map, you no longer experience the bug? Thanks :)

**Comment by casigus** [comment]
yasssssssssssss!! :D fixed :D
