### ISSUE TITLE
Zombies don't attack

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1549]
HELLO again!!

![image](https://user-images.githubusercontent.com/68471279/141651688-cccd0597-29c0-4419-ba68-fbd04368a0de.png)

was told that AI only works for the showcase in a previous post, but not entirely sure where we are at with that, but yeah the zombies don't attack, they just look at you. Same with the soldier AI.

also, ive imported  some classic characters and they are rigged, however they don't aniamted, just wonderiing is this because hey are classic assets and won't translate into the new engine? 

Imported a fuse edit (wont animated) and played around with the fpe copying some of the animation from the soldiers, then added the soldier script, and it does come at you, firing the gun however its not animated and it looks super creepy! 

:)

**Comment by LeeBamberTGC** [comment]
@casigus Can you create a blank level and drop in a zombie, then save and send to me showing the zombie not doing any AI. I cannot reproduce at my end.  Maybe make a video of that same level being run too so I can see what you see.  

P.S. MAX is not able to take character creator creations from Classic, the changes have been too extreme to support the older Classic characters.  We will be releasing new MAX compatible charactrers moving forward, and a guide on how you can assemble your own parts to make characters with.

**Comment by casigus** [comment]
strange!

im not sure what happpened, just booted the pc up, dropped a zombie in and.....it was working, tried with a few other zombies and they too are now suddenly working? very odd! must have been a odd glitch on my end!!

________________________________

**Comment by Retrogamebloke** [comment]
I have the same issue. AI works fine on a flat terrain, but drop them on even a slightly bumpy surface and they just stand and stare as mentioned above.

**Comment by LeeBamberTGC** [comment]
Any chance of an FPM file, I can then see exactly what you see :)  I drop in my soldier and he runs around like a happy chappy.

**Comment by casigus** [comment]
loading up max now to test the flat terrain issue with soldiers and zombies! ill get the files back to you depedning on results.

**Comment by casigus** [comment]
okies ! fpes, videos and the test map as requested :) 

https://drive.google.com/drive/folders/1xizhO0lZlUrLvieCVhXwDHSpy9VV1an3?usp=sharing

**Comment by ivanski1983** [comment]
I am now currently having this issue where the AI is not doing anything on a level build but works fine on a new build

**Comment by casigus** [comment]
yeah lots of amazing improvements actually!! zombies are working great! sorry forgot to close this!!! :D
