### ISSUE TITLE
On the LOAD GAME page, the **ammo-health-panel** icon is displayed and is not hidden !!!

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#155]
0- After Save standalone
1- Run Game
2- Start Game
3- Save Game
4- Press the ESC button
5- Back to Main menu
6-Load Game page (You see this problem)
On the LOAD GAME page, the **ammo-health-panel** icon is displayed and is not hidden !!!
![ammo-health-panel](https://user-images.githubusercontent.com/36647058/38636964-0911825c-3ddf-11e8-9282-63abc34eb47f.png)

**Comment by Teabone3** [comment]
I've not done many standalone exports, but does this happen commonly?

**Comment by Shahin3d** [comment]
I did several standalone exports - Yes, this happens.

**Comment by LeeBamberTGC** [comment]
Fixed for next build at end of 13/04/18 GMT in PP release.
