### ISSUE TITLE
Water problem

### ISSUE THREAD

**Issue by Jackdanielsvs68** [TheGameCreators/GameGuruRepo#1551]
When the water is set on the saved test track, the river flows out by changing the level difference by 1 meter, the water disappears when modified downwards. And the trees disappeared completely. This is a track saved before the last update. 
![Képernyőfelvétel (336)](https://user-images.githubusercontent.com/94233170/141673277-6a0d0aa7-a1b3-4188-8f9c-562612b4cf34.png)
![Képernyőfelvétel (337)](https://user-images.githubusercontent.com/94233170/141673280-0a4c873d-a3e8-4a82-8f69-8750897a28de.png)

**Comment by rvanner** [comment]
@Jackdanielsvs68 We have fixed an issue with the water where the individual changes were too large (1 meter at a time). So try the next build and let us know if it's better for you.

**Comment by Jackdanielsvs68** [comment]
![Képernyőfelvétel (340)](https://user-images.githubusercontent.com/94233170/141679327-fd9cb60e-fe5a-475e-ba8b-349478ef2aa4.png)

**Comment by LeeBamberTGC** [comment]
@rvanner We recently discussed this. Can you add the feedback on what we need the water level to do in terms of accurate changes and then we can see if this solves this issue.

**Comment by rvanner** [comment]
@LeeBamberTGC The suggestion from @PaulSJ was to change the water slider to use a floating point value for finer control.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Slider gadget tweak, the goal is the user should be able to finely control the water height on a shoreline that slopes very gently from land to water.

**Comment by Jackdanielsvs68** [comment]
I'm so sorry, but I'm working on a bigger, more branched project with the gg classic lately. At max, I watch weekly videos, download updates, and just check out what's new. My saved tracks where the problem occurred were deleted due to a system installation. I’m looking forward to early access, and I’ll deal with it in more detail. Thank you for your interest.

**Comment by Jackdanielsvs68** [comment]
I created a new track, it seems to work, I can change it every meter, and it seems to be happening. Although when I create the map, the water level is negative in the settings, it is already 70 meters when editing the level.
![Képernyőfelvétel (4)](https://user-images.githubusercontent.com/94233170/154835896-3d2fb843-acff-4f14-be47-78c55c2eaf9f.png)
![Képernyőfelvétel (5)](https://user-images.githubusercontent.com/94233170/154835897-a13b38a1-c0c5-4563-b3f4-5e4c6f8bd90d.png)
