### ISSUE TITLE
GGMAX 2021.11.12 Build Crash

### ISSUE THREAD

**Issue by PaulFox12** [TheGameCreators/GameGuruRepo#1552]
GGMAX crashes when running test game. Physics are generated, then the prompt says beginning main game loop before it promptly crashes to desktop with no message.
Log file attached
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/7533827/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Can you attempt to reproduce this from the report, thanks!

**Comment by PaulFox12** [comment]
Unsure if its related but PC memory usage seemed to spike to around 18GB during the test game loading screen. The fpm is only a 30MB file so I can't understand how this much memory is needed

**Comment by LeeBamberTGC** [comment]
@PaulFox12 Can you send a shot of your Task Manager with a blank terrain. Here is mine:

![image](https://user-images.githubusercontent.com/35840583/141924024-940d118e-0a0c-4eb4-90da-14a7fbcde3e9.png)

**Comment by plemsoft** [comment]
@LeeBamberTGC FYI:
245801 : Attempt to create nav mesh                             S:0MB   V: (8387,0)     
292424 : rcRasterizeTriangles: Out of memory.                   S:18939MBV: (27326,0)

rcRasterizeTriangles run for 47 sec. and run out of mem , somehow the area got to large ?

**Comment by LeeBamberTGC** [comment]
@plemsoft That darn nav mesh again :)  In fact I am looking at the nav mesh code RIGHT NOW in fact, to solve the play area stuff and also to speed that and the terrain physics too. More on this later this evening, but hopefully a new solution to make it super fast and the FULL SIZE of the editable area!
