### ISSUE TITLE
Footstep slow playback depending on framerate

### ISSUE THREAD

**Issue by Zorgo33** [TheGameCreators/GameGuruRepo#1553]
https://user-images.githubusercontent.com/27580830/141692403-7e4a1be6-6260-4275-a4ce-d124c041e27b.mp4

I noticed on high framerates the footstep playback plays much slower, on lower fps it speeds up a bit.

**Comment by rvanner** [comment]
@LeeBamberTGC Sounds should be timer based

**Comment by LeeBamberTGC** [comment]
@Zorgo33 Footfalls are FPS independent for a good while now.
