### ISSUE TITLE
system crashes saving level

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1554]
System crashes Runtime Error: error 8204 () when saving a level. Start new project, edit level by clicking pencil on Level 1 window, create level, go back with error in left corner, give name for new level, system crashes.

**Comment by smmaas** [comment]
I can save again after I run update (same version) but  the problem returns. When I haven't figured out yet.

**Comment by plemsoft** [comment]
@smmaas Thanks for reporting this issue, i was not able to reproduce this, but 8204 has to do with memblocks so i secured all the cases where this error can happen. So should not happen again, will be ready from the next update, please give it a good test and let me know if it fix your issue, thanks for your help :)

**Comment by rvanner** [comment]
@smmaas Can you try this again with the latest build? We would like to close this issue down if it's now fixed. Thanks!

**Comment by smmaas** [comment]
can be closed
