### ISSUE TITLE
With just 60 trees gameguru slows down to 12.6 fps

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1556]
![image](https://user-images.githubusercontent.com/45684694/141701805-c31ff07d-a20b-4b5b-b4c7-47933c0e9842.png)

**Comment by rvanner** [comment]
@smmaas The trees from the library are currently very ineffecient. You should use the terrain trees if you want to populate lots of trees around. In the future we will add more terrain trees and also look at how to improve the performance of standard objects in a scene.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
