### ISSUE TITLE
Strange shadows

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1557]
![image](https://user-images.githubusercontent.com/45684694/141704475-6917ab3b-1d8c-481f-b7fc-0bca66a41fe2.png)

these strange shadows appear ans disappear when you walk away

**Comment by rvanner** [comment]
@smmaas Can you make a small video showing this happening?

**Comment by smmaas** [comment]
https://user-images.githubusercontent.com/45684694/141768742-002899ca-4efe-472d-9097-771bc3ed3625.mov


this video als shows an other problem; falling through the terrain when walking sideways.

**Comment by rvanner** [comment]
@smmaas The video is not playing for me. Can you share it via YouTube?

**Comment by smmaas** [comment]
https://vimeo.com/646638328

**Comment by rvanner** [comment]
@smmaas Could you send me your map file (.fpm)? Please set the start marker to where you see these shadows.

**Comment by smmaas** [comment]
I can sent the file but the problem has disappeared. I have no backup so I tried to rollback, the only thing I have done was to replace trees with treesystem trees (issue 1556) so I disabled the treesystem and replanted 60 slow trees but the problem didn't come back. So I recreated the level from scratch but could not recreate the problem.

**Comment by rvanner** [comment]
@smmaas OK, let's close this issue for now. If you see it again then please make a new report and send a map file. Thanks.
