### ISSUE TITLE
Particles need to be sorted and rendered with transparent objects (back to front)

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1558]
https://www.youtube.com/watch?v=CYu5Dl4_r8E

Place particle behind glass or another entity with transparency and you cannot see it.

**Comment by rvanner** [comment]
@Kitakazi Nice find! Thanks for reporting.

**Comment by Kitakazi** [comment]
@rvanner 
Can this be flagged as a bug? Im worried it may be missed? Not really sure the process though so no big deal if marking as a bug doesnt do anything.

**Comment by synchromesh62** [comment]
> @rvanner Can this be flagged as a bug? Im worried it may be missed? Not really sure the process though so no big deal if marking as a bug doesnt do anything.

Have you tried ticking the **double sided** box in Materials ..
That worked for me

**Comment by Kitakazi** [comment]
@synchromesh62 
I'm at work at the moment, so I'm not sure but are you saying that making the material on the Particle doubled sided? will make it appear through transparent objects (I wasnt even aware that particles had a material setting)? Or that I would need to make the transparent object double sided cause that would cause issues for alot of models.

**Comment by synchromesh62** [comment]
> @synchromesh62 I'm at work at the moment, so I'm not sure but are you saying that making the material on the Particle doubled sided? will make it appear through transparent objects (I wasnt even aware that particles had a material setting)? Or that I would need to make the transparent object double sided, but I dont see how this option would really make sense.

Not the particle .. I have glass doors and can only see the particle when i set my door to **double sided** ticking the box in Materials .. Worth a try :)

**Comment by Kitakazi** [comment]
Well that works but it wrecks the model since its not suppose to be double sided. Either way its definitely a bug hope it doesn't get forgotten about :(

**Comment by LeeBamberTGC** [comment]
@Kitakazi Much transparency work since March. Just tried with five particles and a transparent window, and it looked fine:

![image](https://user-images.githubusercontent.com/35840583/173081098-ccc745fc-1c45-4a98-945a-b5c31364f480.png)

Maybe you can send a transparent object that does not work and we can go deeper if not fixed.

**Comment by Kitakazi** [comment]
Huh thats odd I just tried with a window from the Buildings Collection entity named "Building - Window" and it did not work. I have verified my files on steam and still had no luck getting this to work. 
However, the entity in your screenshot I believe is "Warehouse - Window" and that one does indeed work. This is the only entity I have seen actually work.  

Please test with "Building - Window" and see if it works for you?

![image](https://user-images.githubusercontent.com/51464873/173165895-2f926d10-dd5f-4d35-aae3-1a5293c49a77.png)

**Comment by Kitakazi** [comment]
Ah I believe the reason that asset worked in your post is because it has double sided enabled. Transparent entities that have Double Sided checked in will indeed show particles on the other side. However if the transparent entity is not double sided it will not show the particle on the other side. 


![image](https://user-images.githubusercontent.com/51464873/173165964-c6231285-5b20-4a3f-b1c1-ce7ab3a61f8f.png)

**Comment by Kitakazi** [comment]
Sounds good, thanks.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Improved particle system now renders particles within the transparency queue, accounting for camera distance to always keep see through objects rendered back to front order for correct visuals:
![image](https://user-images.githubusercontent.com/35840583/230521954-b289eaf5-50c3-4233-887f-474a9a2aeee0.png)

Ready shortly for next EXP build.

**Comment by Kitakazi** [comment]
Awesome! Thank you.
