### ISSUE TITLE
Load Project Backups Option

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1560]
I'm not sure if this is a bug or not. When you select load project and tick the show backups box nothing appears. I have several automatic backups still but it does not list them or give you a way to load them.
![image](https://user-images.githubusercontent.com/44620846/141796672-fd62938f-6900-43ef-a2be-08a977a8c1e9.png)

**Comment by plemsoft** [comment]
@Retrogamebloke Its not a automatic backup, it will only make a backup if you "overwrite" a project , after that it will have a backup :)

**Comment by Retrogamebloke** [comment]
Oh, so this is not a way to load old projects from the automatic backup made when you update max then?
![image](https://user-images.githubusercontent.com/44620846/141812750-e0b2dc88-7ba2-4acd-9e94-0dda6ceb6740.png)

**Comment by plemsoft** [comment]
@Retrogamebloke No , the deleting of projects ... backup ... will go away at some point :)
