### ISSUE TITLE
Undo Option Does Not Work With Terrains.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1562]
Undo does not work with terrain edits. We can revert back with the restore brush, but that does not help if you have sculped an area and then make a mistake and want to undo it.

**Comment by rvanner** [comment]
@Retrogamebloke Yes we know we still have to add Undo to terrain. This will be done shortly after the release.

**Comment by rvanner** [comment]
This is now implemented.
