### ISSUE TITLE
Importing Animated Model Inconsistent in MAX

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1564]
Hello. I am testing bringing in my own animated models. I started simple, using a simple cube that I shaped like a door in Blender and then animated it using keyframes (no bones) to swing open. I made three animations - open, close, and still. Then I exported via FBX from Blender and brought the door into MAX. The model imports fine and the scale is good. However, I am getting mixed results when it comes to animation. The first door imported and the importer showed me the animations. Nice. The second door I made imported, but said no animations were found. The third door imported, showed the animations, but when put into MAX and the Door Behavior added, it sank into the ground, tilting this way and that, until it disappeared. Other doors, animated the same way as the first, mostly come into MAX with no animations. However, if I bring any of these doors back into Blender (via importing the FBX), the animations are there. 

Is this an issue with the importer? Or is there some other issue? I don't know. I've begun to try various export settings for FBX, but now I am just getting the message that no animation was found. 

I can zip up the various door examples and attach them here, if that would help.

**Comment by ZakJudges** [comment]
Hi @ArgentArts, would you be able to send all of the examples mentioned? That way I can reproduce the issue and take a closer look to see what's going on.
It does sound like an issue with the importer. If you have the original .blend files, could you also try to export them as glTF files? That would give me more of a clue as to where in the import process the problem is occurring. Thanks!

**Comment by ArgentArts** [comment]
@ZakJudges - Thanks for getting back to me. I don't have the .blend files as I had only made a simple cube that was stretched to a basic door shape ... no materials, etc. These were only for export/import testing. But I do have all the FBX files. I've made a ZIP file with all the doors within them for you to look at.

[doors.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7557248/doors.zip)

I've also notices, while working on a level using models I had made, that some models come in perfectly, some come in with their vertical alignment messed up (Z-up vs. Y-up) and, yet, all of these models were exported the same way from the same program (Blender). In fact, I had built the level in Blender, then centered and exported each piece separately using the same export settings. So, I see no reason that about 50% of he pieces should be tilted to one side and the rest came in as they should have.

**Comment by ArgentArts** [comment]
Is there any resolution on this? I am still struggling to get a basic animated door successfully into MAX using a basic keyframed animated door.

**Comment by ZakJudges** [comment]
Hi @ArgentArts,
I will be taking a closer look at the importer issues at some point in the near future :)

**Comment by ArgentArts** [comment]
@ZakJudges ,

I've discovered the issue as I had reported this and a different issue here:

https://github.com/TheGameCreators/GameGuruRepo/issues/1599

I believe most of this is end-user error. If you read to the end, you'll find what I'd discovered.
