### ISSUE TITLE
GameGuru CLASSIC: allowfragmentation = 2 sets g_PlayerGunCount to 0 

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#1565]
Dear Support, I have found out that 

allowfragmentation = 2 sets g_PlayerGunCount to 0 when loading between levels.

This means that the PlayerGunCount is 0 even though the player has at least 1 weapon in his inventory.
 
setting allowfragmentation = 1 helps but can it be tweaked so that it also works with 2 ?

Please fix it as this breaks some scripts in the standalone. 

Thank you.

**Comment by AmenMoses** [comment]
To give a little more background we have a script that uses g_PlayerGunCount  > 0 as a trigger to display a custom crosshair, with allowfragmentation = 2 in the .ini file the standalone displays the custom crosshair in the first level but in the second level, even though the player still has weapons carried over, the crosshair is not displayed.

By the addition of a debug Prompt we were able to establish that in the second level the value of g_PlayerGunCount  was being reset to 0, even though the player still has weapons.

Weirdly setting  allowfragmentation = 1 in the .ini file the crosshair is displayed on the second level and the value of g_PlayerGunCount  is no longer reset to 0.

This one will be worth watching I'm sure.

**Comment by plemsoft** [comment]
@Duchenkuke  @AmenMoses Thanks for reporting this issue, this has been fixed and will be in the next update :)
