### ISSUE TITLE
GameGuru MAX - Save Last Camera Position on Save and Reload

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1566]
Currently, in GameGuru MAX, when you start MAX and load a level you had previously saved, the default is for the camera to be way up in the sky looking straight down on your level/scene. This is not always desirable. I am working on an interior-only level and never need to see the scene from way up there, but always need to see the scene from within the walls of my game. Therefore, I would like to suggest an option to save the view port camera location on save. This way, when starting MAX up and loading in a scene you'd previously worked on, it would also automatically set the camera to where it was when the level was saved. 

It's a bit of a PITA to have to fly on down to your level and try to get the camera to where it was so you can start working (as the first thing you have to do each time you restart MAX).

**Comment by rvanner** [comment]
New levels are now able to save the location of the camera. So when you return to a level you be exactly where you were last editing.

**Comment by ArgentArts** [comment]
Awesome! Will we see this in the Friday update?

**Comment by rvanner** [comment]
Yes, I've tested it in the internal build and it works just fine.
