### ISSUE TITLE
Wrong slashes in url in description of repository

### ISSUE THREAD

**Issue by Hammerstad** [TheGameCreators/GameGuruRepo#157]
Hi

The description of the repository reads `The GameGuru Repository For Community Collaboration http:\\www.game-guru.com`. If you are using Opera as your web browser, URLs with backslashes instead of slashes will be converted to `about:blank`, instead of converting the backslashes to slashes (like IE does).

May I suggest that you change the slashes to forward slashes instead of backslashes?

**Comment by LeeBamberTGC** [comment]
Thanks for the tip, corrected in description :)
