### ISSUE TITLE
GameGuru MAX - Object Library Preview Issues - Bug

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1570]
If you import a model and, for whatever reason, you need to adjust its position, scale, and rotation before accepting it, the model often doesn't show in the preview you get and you have to sort of guess where the model is, frantically moving the mouse, hoping to catch a glimpse of it so you can then position it as you like in the preview. And, then, even if you do find the model and accept the preview, after it's saved, and you go to the Object Library, the model may not show up there at all ... or it shows up way off to one side. The Object Library Preview seems to only work correctly with models that import perfectly and require no adjustments before accepting them.

**Comment by ArgentArts** [comment]
Here's a screen shot of what I mean:

![preview](https://user-images.githubusercontent.com/36735507/142373883-4869e9f8-f1ee-4b98-90d0-9d0fd950b6d8.png)

**Comment by rvanner** [comment]
@ArgentArts I would help @ZakJudges fix this if you could share a model that has this issue during import.

**Comment by ArgentArts** [comment]
[PR_Pedistal.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7561264/PR_Pedistal.zip)

Here's one of them, I believe.

**Comment by ArgentArts** [comment]
I forgot to say that this model needs to have the scale set to 3000 or more when importing it. It's tiny.

**Comment by plemsoft** [comment]
@ArgentArts This is what i see after importing the object , only setting scale to 3000, looks ok , did you change any other parameters ? , could you give it another test in the latest build and let me know if it also look fine for you , thanks :)

![import-test](https://user-images.githubusercontent.com/18662417/155986098-24f20b73-d6c1-4378-b33a-b5eb42af28e0.jpg)

**Comment by ArgentArts** [comment]
Nope. This is not working for me. This is what I see after clicking Import:

![import](https://user-images.githubusercontent.com/36735507/156035989-861516cd-e5fe-4360-9c22-260d5b74a007.png)

**Comment by plemsoft** [comment]
@ArgentArts I think this is related to the widescreen issues you had : https://github.com/TheGameCreators/GameGuruRepo/issues/1597 , this was fixed, could you test it in the next build and let me know if it also works for you , Thanks :)

**Comment by ZakJudges** [comment]
@plemsoft I forgot to mention, I don't think resolution is the only thing affecting this.
I managed to reproduce the issue on a 1080p display:
- Imported an object from the building collection
- Applied a decently large rotation and position offset
- This is what I saw: 
- 
![Screenshot 2022-03-01 133658](https://user-images.githubusercontent.com/32545391/156179627-0a0ef387-1698-4a5b-a7e4-ddc1daf48f33.png)

**Comment by ZakJudges** [comment]
Here you go :)

[thumbnailbug.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8162689/thumbnailbug.zip)

**Comment by ArgentArts** [comment]
This is fixed in the latest build:

![shot1](https://user-images.githubusercontent.com/36735507/156883797-60cca58a-a16d-46bc-b4a2-716f93ec4a7c.png)

All the "bad" ones are from previous builds. The arrow points to a new one taken with this last one. :)
