### ISSUE TITLE
GameGuru MAX - Lighting Bug

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1572]
I have been experiencing what looks like a bug with lighting in MAX. I've placed a light under a helmet in my level and it casts nice shadows:

![light1](https://user-images.githubusercontent.com/36735507/142284026-67da4f9f-9c80-4e67-9e6f-01d9f4904b7e.png)

But if I move further away, the model no longer restricts the light:

![light2](https://user-images.githubusercontent.com/36735507/142284111-7411b451-b8b0-4cad-954c-0e141936d856.png)

I would like the model to always restrict the lighting. This is happening with every model in my scene. For example, I have a barrel of toxic waste. I've placed a light over the top of the barrel to cast a light and shadow (from the barrel) on the wall the barrel sits next to. When closer to the barrel, it looks great. But when the player moves a bit away, the barrel no longer casts any shadow and it just looks like a light is against the wall.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Looks related to shadow settings, have you tried adjusting those to get the shadow depth you need for your level design?

**Comment by ArgentArts** [comment]
Frankly, in the lastly build, this issue appears to have gone away. I can move back very far and the entity continues to cast shadows in my scene.

**Comment by ArgentArts** [comment]
Actually, Lee. I was wrong. This IS still happening. It happens when there are more than five point lights in a scene. I'll do a video and start a new but on it.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Since this report, we may have fixed this and improved the shadow light count properties too, please confirm now fixed and we can close this one:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/88399e13-8075-49cb-b71d-88146596d0df)

**Comment by MonkeyFrogStudio** [comment]
Appears fixed from my testing. Thanks!
