### ISSUE TITLE
Terrain and Water controls; HideTerrain() and HideWater()

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1578]
In the default scriptbank there is the script goindoors.lua that is suppose to hide the terrain and water. But it does not work.

**Comment by Necrym59** [comment]
Both the
  HideWater()
  ShowWater()
  HideTerrain()
  ShowTerrain()
Lua commands are inactive or now redundent

**Comment by synchromesh62** [comment]
> 

Ye i think they were for the old terrain system before Max go the new one.

**Comment by Kitakazi** [comment]
So you guys know of a way to hide the terrain?

**Comment by synchromesh62** [comment]
> So you guys know of a way to hide the terrain?

As far as i know there is not a way to do this yet.

**Comment by Kitakazi** [comment]
This has been added, thanks.
