### ISSUE TITLE
GameGuru MAX  -  Edit Mode vs Standalone Mode

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#1579]
Hello, 

I am "mikeven" in GG Forum, but that nickname is already used on Github (it is not me), that's why I am "marcuswilm" here.

GG Max is now very pleasant to use with a superb Terrain editor and with an very good advanced Materials editor.

I want to contribute to its positive evolution with this report of a few bugs.

Here is the link to an online short video capture showing those bugs :  https://vimeo.com/647701152
 
 
What you could see in that video  :   
- short industrial stairs :  collision mode (polygon) is selected but is not active at first launch in the editor; not active in the standalone version.
- the imported "door" (created with Blender 2.90) :  animation with the behavior "Door" works correctly in the Editor and in the standalone version, but its initial state is not reset in the editor after a first launch activating the behavior.
- Joe - military ally :  two files are missing in the standalone version -> wrong material rendering.

Other bugs (or missing features) : 
- no rotation button for the Player start position, but the key "R" can be used.
- rotation and scale tools have sometimes abnormal values (wrong angle of rotation "180° = 360°", impossible to reset a correct proportional X,Y,Z scaling after having proeeded to some adjustments.
- when the Terrain is modelled in "Display Terrain Debug Mode" (a very interesting one) then there are often problems with the Player/Terrain collision (the player falls under the terrain).

Thanks for your hard work.

mikeven

**Comment by marcuswilm** [comment]
Hello Zak,

Thank you for your detailed review of my bugs report.
Indeed I should have posted a separate report for each bug.

Today I verified the persistance of the bugs mentioned in this report.

- Joe military ally : **bug fixed**.
- short industrial stairs : ****bug fixed** IF** the default Collision Shape "Convex Hull" is replaced by "Polygon" in the Editor.
- no rotation button  for the Player start position  :  now it is OK, that button is active.
- rotation tool : (180° = 360°) : **bug fixed**.
- scale tool : there is still a bug with that feature. I'll soon post a **new report** with a video to demonstrate it.
- player falls under the terrain :  I think that this bug still remains and it happens when the collision's process with the terrain doesn't work properly. Most of the time it happens on steep slopes. Personally I found an effective solution to that problem thanks to a customized behavior where I inserted these lines of code : 
- `    if surfboard < heightTerrain then
        surfboard = heightTerrain
    end`
With that behavior the Player walks (or swim or fly) on a surfboard. All collisions with the terrain or with the water are controlled with that Behavior. Demo in this video [https://vimeo.com/664737880](url).

Have a nice day.

**Comment by ZakJudges** [comment]
@marcuswilm thanks for confirming those :) Do you have an example map that shows the player falling under the terrain?

**Comment by marcuswilm** [comment]
Zak, it was a good idea to ask me to provide an example of a map where the player is falling under the terrain.
Unfortunately the projects where it happened contain terrains created with previous alpha versions and when they are run with a recent version of GG MAX their appearance is completely different and unusable.

I must admit that I was wrong when I thought that the bug still remained in the latest alpha versions.
I cannot reproduce it anymore when I generate new terrains.

As mentioned in my previous comment I'll open an new report to demonstrate the problem encountered with the Scale Tool. 
Therefore I suggest you to definitively close the current report because all the other bugs are now resolved.

Thank you.

**Comment by marcuswilm** [comment]
Hello Zak,

I see that this report is not already closed, that's why I take this opportunity to mention here that I just posted a separated and well documented report about the bug with the Scale Tool. (link to that new report : [https://github.com/TheGameCreators/GameGuruRepo/issues/2185](url) )
:-)
