### ISSUE TITLE
Normals are flipped

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#158]
Not sure when this happened or if these are right and I am wrong but I find I am now having to flip the 'y' on my normal i.e. If I have an emboss on my normal map and I don't flip the 'y' it becomes a recess is ths correct am I supposed to be flipping my normal map, I don't remember having to do it before.

Please do not confuse this with 'Flip Handedness' its just the normals 

regards
Kevan

**Comment by LeeBamberTGC** [comment]
Your DNS style non-PBR normals can remain the same, but PBR shaders require normals that are -Y (green channel) for some models.  Can you send me a single model and texture set that causes this question and I can take a closer look.

**Comment by GraPhiX-Guru** [comment]
ahh good to know thank you :) now that I know the y is negative I will adjust my normal map accordingly.
I don't see this as a bug just informative, we have not really had any instructions on the map types so little bits like this helps :)
thanks Lee keep up the good work
