### ISSUE TITLE
GameGuru MAX - Panel Docking Issues & Icon Size - Bugs

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1580]
I enabled docking in MAX and found issues. I was going to capture a screen shot of one of them, but now my UI is a bit messed up in MAX and I am not sure how to get it back. What I had done is to undock the Level Objects panel from the upper-left. I had intended to put it at the bottom of the screen (below the view port). That didn't work out, so I went to put it back. After doing so, it totally hid the grouping panel that was at the bottom-left and I can't find a way to get it back. Is there a way to reset the UI to default? 

When I had undocked the Level Objects panel and placed it at the bottom, it stretched all the way across the screen and hid the bottom parts of the right and left-side panels. Instead of showing the Level Objects, it filled the panel with the icons that are at the bottom (the game tool stuff) and made them super-large, filling the entire height of the panel. I was planning to recreate this and offer a screen shot, but I had undocked it from the bottom and docked it back to the left side, causing the issue I reported above (completely hiding the grouping panel). Not only is the grouping panel gone, but there is no tab for the Level Objects panel, so I have no means of grabbing the panel and undocking it again. 

Lastly, the icons that appear at the bottom of the Level Objects panel resize as you make the panel larger or smaller. Here's a screen shot of that:

_Larger icons due to expanding the Level Objects panel:_
![icons](https://user-images.githubusercontent.com/36735507/142670773-7e2a3945-fec4-4029-8c07-fdf3362ef50b.png)

_"Normal" icon size with Level Objects panel not expanded:_
![icons2](https://user-images.githubusercontent.com/36735507/142671362-cd3febfd-ef18-4ae5-b353-5352cb548858.png)

Depending on the size of the panel, these can get really huge. I would rather see these icons not resize at all, but only reposition themselves within the panel (i.e. stay centered).

**Comment by ArgentArts** [comment]
Okay. I see that Reset to Default resets the UI, too. :)

**Comment by rvanner** [comment]
Undocking is bugged at present. We'll get it fixed soon.

**Comment by plemsoft** [comment]
@ArgentArts Thanks for reporting this issue , found the problem with the hidden "Level Objects" window, and fixed it, about the icons they have now changed and go to columns , if this is still a issue for you please create a new issue as this is how its designed and not really a bug , Thanks for your help :)

**Comment by ArgentArts** [comment]
There are still issues with docking. I undocked the grouping area at the bottom and now I cannot move it at all:

https://user-images.githubusercontent.com/36735507/156883515-5d7a3241-36f6-4853-80da-f8ff328838c9.mp4

**Comment by ArgentArts** [comment]
And now I get this when I open MAX:

![doc2](https://user-images.githubusercontent.com/36735507/156883625-44e4ec87-6844-4afd-951c-6a124457295c.png)

**Comment by plemsoft** [comment]
@ArgentArts I can see that it do not have a tab bar on the top that are used to move and dock it.
Did you enable docking in settings , then tried to move windows around , then disabled docking , and restarted ? , if so it would not have a tab bar.
Could you try to enable docking and restart. Then check if your able to move it around. id so i know what to fix :)

**Comment by ArgentArts** [comment]
I had not disabled docking at all. Only enabled it, moved a window, and tried to move it back. Nothing more. I had done a restart with docking enabled. That's were the second screen shot comes from. ;) I finally did a reset on the UI to get it back to normal.
