### ISSUE TITLE
Enemies Killed by Allies Rotation Issue

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1582]
![image](https://user-images.githubusercontent.com/44620846/142712153-68ef44f8-d656-479c-9d54-61ccbf230132.png)
If you don't get a shot in and the ally kills a zombie, on exit they stay rotated in last pose and will stay like that on a second test. If you click them they revert back.

**Comment by rvanner** [comment]
Yes, we know about this. I'm closing this because it's on our dev list to do.
