### ISSUE TITLE
Not happy

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1583]
The last update deleted all my projects. Only imported objects in user where not deleted.

**Comment by ArgentArts** [comment]
Did you read the warning that pops up when you go to update? It states the following:

"Any user files in:

"c:/Program Files/GameGuruMAX/"

will be deleted, make sure you have moved them out of this
folder if you want to keep them.

Are you sure you want to continue?"

You had to press "Yes" to proceed. And, by doing so, you deleted any files in that folder.

**Comment by synchromesh62** [comment]
Go to the new GameGuruApps and you will find your old Backed up in that folder .
Should look like 
![BU](https://user-images.githubusercontent.com/35708217/142723169-63cedd10-175a-4c16-8d42-cdfc43cb25c1.png)

**Comment by smmaas** [comment]
I do read that why it's called "not happy" and not "very angry" but still project should be in a user directory that isn't removed with an update. So it's a bug!

**Comment by ArgentArts** [comment]
Actually, no. You can set things up in MAX so that your user directors are outside of the default MAX directories. If you do this, you won't lose anything when you update MAX. That's why it states, "Any user files IN ... " If they are not IN that folder, they are going to be safe.

**Comment by rvanner** [comment]
@smmaas Sorry you were not happy with what MAX did. As these are Alpha builds you need to be careful with your own files. Please store all your game files in your Documents folder where they will be safe.
