### ISSUE TITLE
GameGuru MAX - More Complete Changelog File?

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1585]
Is there a more complete changelog file for updates for MAX? The current changelog for alpha 2021.11.19 states the following:

"Added weapon choice in character creator and rifle choice for all. 
Added gun specification support to control exact placement of weapons. 
Behaviors can now run other behaviors, soldiers can now also patrol. 
Eliminated the play area limit, now physics and nav mesh size of editable area. 
Overhauled all characters and character parts in character creator. 
Added new bushes to tree collection to complete the vegetation needs.. "

But more was changed since the previous alpha than that. For example, the camera now recalls the last position when MAX is closed. Any new features added or bugs fixed should be listed so that testers can go through them and test them to ensure they are fixed or working correctly. So, is there a more complete changelog and, if not, can we get one for the next alphas?

Thanks.

**Comment by rvanner** [comment]
There's only what Lee has supplied. We'll aim to be more detailed in future builds.

**Comment by ArgentArts** [comment]
No worries. It's just that a lot of bugs and feature requests get submitted here. It would be nice to know what made it into a build so that we testers can ... well ... test them. ;)
