### ISSUE TITLE
GUI Suggestion

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1586]
Instead of having a fairly unobvious button on the top right that opens up new options in the lefthand panel, have tabs you can open up as needed on the left panel.
![image](https://user-images.githubusercontent.com/44620846/142737347-5516be7a-e0b0-426b-94da-4f329d16eb35.png)
Just a quick mockup. Would make more sense to me and be instantly obvious you open those tabs to get the additional options.
![image](https://user-images.githubusercontent.com/44620846/142737740-374c4891-68ec-44b7-ac70-ee01b6d57261.png)
Perhaps not quite as clean looking, but adds space back to panels, if that is a concern. Those run icons are nice, but take a lot of unnecessary screen estate.

**Comment by ArgentArts** [comment]
Or ... have that section be it's own panel, separate from the Level Objects panel. And, in that panel, have the three icons - Shooter, RPG, and Puzzle. Clicking each will expand the options available (the icons shown that you can use). This way, the end-user could dock that section wherever they wanted.

**Comment by Retrogamebloke** [comment]
Yes. As long as the options are next to the buttons that open up. Either way would be better than the arbitrary buttons on top right.

**Comment by ArgentArts** [comment]
I agree. They need to think about conservation of motion a bit. That's a lot of motion to click something at the top-right just to go over and click something at the middle-left of my screen. And I have an ultra-wide monitor, so ... ;)

**Comment by rvanner** [comment]
We have a lot of UI changes planned, so please wait to see the changes we'll be making soon!
