### ISSUE TITLE
GameGuru MAX - Request - Have MAX Open Directly to the Editor

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#1587]
Currently, when you start MAX, it asks if you want to start a new project or open an existing one, then it takes you directly to the storyboard editor where you have to click on a level to get to the editor. I don't think this is a good workflow. Instead, what I think should happen is you start MAX and it opens directly into the editor with an empty viewport (or even the standard default terrain). Then, if the end-user wants to start a new project, they go to the File menu and select New Project. If the end-user wants to use the storyboard, they go to the top menu and select Storyboard Editor and it appears. I think most people expect a program to just open up to where you get to work just like any 3D modeling or paint program. 

Even if we should create a new project first or select an existing one (most of the game engines work this way), it should still open to the editor and not the storyboard editor. The storyboard editor should be accessed by the end-user only when they want to via accessing it from it's appropriate menu or icon.

Just my opinion ... but I found the current workflow a little confusing at first. Mainly because I started the latest alpha with a current project instead of a new one and, as a result, I did not see the giant "CLICK HERE" on the level part of the storyboard. ;) So, I initially was frustrated trying to get to my level to work on it.

**Comment by ArgentArts** [comment]
Maybe what we need is an Expert Mode and a Beginner Mode. The very first time MAX is started after a fresh install, it offers Expert or Beginner. If Expert is checked, it defaults to opening directly to the editor, ready for work. If Beginner is checked, it opens to an initial screen and sort of "walks" the end-user through setting up a project (New Project, Storyboard, then editor, etc.).

**Comment by rvanner** [comment]
How about a Sandbox mode?

**Comment by ArgentArts** [comment]
What do you mean when you say "sandbox mode"?

**Comment by rvanner** [comment]
We can consider this after Early Access.
