### ISSUE TITLE
Latest Release notes

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#159]
don't want to sound stupid but where are the release notes for the latest betas the email says check GitHub but I cannot find any info on what as been added or fixed? or is it a case of reading through all the issues that have been closed ?

**Comment by Granada1** [comment]
Been trying to find info as well ,come on Lee where did you hide it

**Comment by Teabone3** [comment]
I think the change log needs to be updated

**Comment by LeeBamberTGC** [comment]
Simply go to the code commits log and look for any entry with an asterix in front of it (*). Here is the link: https://github.com/TheGameCreators/GameGuruRepo/commits/master
