### ISSUE TITLE
GameGuru MAX - Request - Empty Level Truly Empty

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#1593]
Currently, an empty level has a solid grid in it. It's not truly "empty". You can place a player start on it and, if you run the game, they player can walk on it. So, it has collision. I would like MAX to start with a truly empty level with "Empty Level" is selected as an option. 

One reason for this is if I am creating an indoor-only level and I start building at "ground level" and then, later, decide I need to build downward, the grid becomes an obstacle. I'd have to move everything else up, which would be a PITA.

I also wonder if this solid grid has any performance hit, no matter how small.

**Comment by ArgentArts** [comment]
BTW - The current solid grid level (currently used for the empty level) could also be kept as an option, so it doesn't need to be completely discarded.

**Comment by MonkeyFrogStudio** [comment]
Duplicate.
