### ISSUE TITLE
Weapon AO maps appear to no longer be working

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#16]
Other PBR entities enjoy the use of the AO map, and the gun_ao (PBR mode) also needs this.

**Comment by LeeBamberTGC** [comment]
Seems there was a define flag preventing weapon shaders to use the AO, but this has been removed for the next March PP build and also tested it with a modified Uzi PBR weapon and gun_AO map inserted into the gun folder and it worked fine.
