### ISSUE TITLE
Latest release lightmapper issues

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#160]
The lightmapper is much better and heading in the right direction but it's still giving me problems, I haven't changed anything in the level and I still lightmap using "lightmappingsizeentity=2048" as before but now I have strange shadows where there is nothing to cast the shadow and the levels are unplayable due to stuttering frame rate and lag, I am getting between 60 and 3 fps ( especially bad when player turns) with VSYNC on and between 140 and 0 fps with lock ups when VSYNC is off, this is with a GTX980Ti and its about the same with a GTX960, both have the most current drivers. The pictures show the rogue shadows, in the 2nd one there is a striped effect on the left wall.
![lmi1](https://user-images.githubusercontent.com/36109432/38767111-4acdd4f6-3fd4-11e8-975c-5aeeea2c3905.jpg)
![lmi2](https://user-images.githubusercontent.com/36109432/38767113-4f7cfea0-3fd4-11e8-865d-934eeb65acbf.jpg)

**Comment by LeeBamberTGC** [comment]
Could you assemble a small level using stock media, and then a step by step what I should observe about the lightmapping of that level, and then attach the FPM of that level, that would be super useful, thanks!

**Comment by BodRH** [comment]
I deleted the lightmaps folder for the level, dropped lightmappingsizeentity to1024 and ran lighmapping again, I'm now getting a steady 60fps with no lag or stuttering apart from when I first picked up the bow, the strange shadows are still there but I can sort that out with a bit of remodelling and considering how many entities are in the level just having to change 5 is no problem, but I don't understand how when using 2048 it was fine pre DX11 and is now so choppy.

**Comment by LeeBamberTGC** [comment]
When you see stutter, it is likely there is too much texture data being sent to the card, so reducing the lightmaps to 1024x1024 would alleviate this scenario.  Texture balancing is a pretty tricky art, and there is no single snapshot feature which shows your texture use. It's more a case of figuring out when you need high-resolution textures, and when you can get away with smaller textures to create your larger scenes.  I have switched this to an 'enhancement' to start a discussion about how we can help users manage their texture data volume to avoid stuttering the graphics card.

**Comment by BodRH** [comment]
I made this video to better explain what is happening with lightmapping. 

https://www.youtube.com/watch?v=wmHOBphKK9c&feature=youtu.be

**Comment by LeeBamberTGC** [comment]
Can you provide the exact location of the entity used in the video from the stock assets, thanks!

**Comment by BodRH** [comment]
The wall isn't a stock asset, it's the one I sent you as mentioned in this thread on the forum.
https://forum.game-guru.com/thread/219581?page=2#msg2599867

**Comment by LeeBamberTGC** [comment]
We have seen this elsewhere, even in some stock media, and the cause is the model geometry. Correcting the geometry issues solves the lightmapper issue reported here.  You need to make sure the geometry is clean, not double-sided, normals facing outward with no erroneous data values.  In some cases its just a case of trial and error with the export until you get a clean model in GameGuru, and we recommend a tool called Ultimate Unwrap 3D Pro for loading and tweaking exported X models.
