### ISSUE TITLE
Performance Issues with latest build

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1601]
https://www.youtube.com/watch?v=9RbqPuJMxHg

I have attached a video showing some pretty gnarly frame rate drops. This level ran smooth 60fps a week or two ago np. 
The Shadow Draw Calls spike super high not sure why, but the Draw Call on Objects are really high too,  I haven't tested in stand-alone yet to see if the lag still happens there. 

Turning off the shadows completely does help some, but the frame drops are still pretty big. Moving around in the editor seems normal though and frames do not drop.

**Comment by Kitakazi** [comment]
Also the editor profile shows Shadow Renderings Terrain and Grass im not sure if that means anything but the terrain is empty and there is no grass in the scene. So not sure why that is showing anything at all either.

**Comment by Kitakazi** [comment]
Performance issues have gotten much worse since I posted this. Opening my FPM's can take anywhere from 3-10 minutes.
Trying to launch Test Game will take up to 5 minutes. The program will become unresponsive multiple times, windows will try to get me to close the program, etc. Once actually in a test game performance is not good, frames constantly spike downwards, issue #1590 makes shooting a weapon impossible, numerous lighting and shadow bugs. 

Additionally as of the current build, changing materials and collision shapes on an entity inside the editor will not save, even after saving your level. As soon as you close Max and reopen it will all be reverted back.

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue , we have optimized a lot since this issue, please test this in the latest version and let me know if this is still a problem, thanks for your help :)

**Comment by Kitakazi** [comment]
@plemsoft Man, the performance is a little bit better but overall it's still pretty bad. The levels do load waaaay faster and to get into test game is way faster as well which is nice. If this loading speed is the same in standalone that would be game changing.

But, once in the actual test game... the performance is still really bad. Testing right now on Version 2022.02.25
I've mainly been working on purely indoor levels and they are pretty plain. Just general things like corridors, floors, walls, and some props. No AI, very little animated objects, no crazy textures sizes, most objects are box shape collision. 

I just loaded up the same level from the first post of this thread, I basically have not touched it since I posted this. Because I didn't want to spend time adding more things when it barely ran as is. 

Still has all the same issues. With vsync on - frames spike from 60 to 35 constantly. I'd say the average frame rate is around 45. Shooting weapons just wrecks frames but even with no weapon or anything just simply trying to walk around feels like I'm fighting the engine to just move. Walking up ramps and stairs is weird too it "feels" like the character gets stuck in them, and might just be in my head but I have noticed whenever there is stairs or a ramp it tends to cause fps to drop. But even then walking around on the floors feels like a battle. Aiming the camera in certain directions will tank frames. 
----
And 2 additional smaller issues I notice on this level, is there is some sort of aliasing going on, even with MSAA x8 and FXAA enabled, it stands out really bad. Also I always notice issue #1558 when testing this one as well.

**Comment by Kitakazi** [comment]
Ok just updated to version 2022.03.04 the internal build.

**Comment by Kitakazi** [comment]
Updated to Internal build 2022. 03.04
No change in performance. 
Is there any sort of culling enabled? I notice draw calls spike to around 8k if I point the camera in the direction where there are entities, way down the map. I wonder if things are being culled out at all or if it is rendering all entities, even the ones not visible?

**Comment by plemsoft** [comment]
@Kitakazi Could you try to play this level in the latest build , and note the draw call , should now be lower, please also post your "Guru-MapEditor.log" here so i can check , thanks for your help :)

**Comment by Kitakazi** [comment]
@plemsoft 
Just tested this level, the parts the were smooth before are now very smooth, however the areas that were bad are still very bad and still drops frames pretty rough.  Going from 60 to 40 and even 60 to 30 for no apparent reason. But for walking around alot of the level is just a solid 48-45 fps. 

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8354578/Guru-MapEditor.log)

Additionally,  when I first went to test game this randomly happened tonight. 
https://youtu.be/YmJsG9Ajfh4
A giant white block appeared, the texture on it looks like the normal maps of the floor from that room. If you watch when the test game is loading there is a very bright light coming from that same direction. I'm not sure if that is related but I see that bright light every time I do a test game on this level. But this is the first time I've ever seen anything like that big white block that appeared. No idea if this is related to performance issues from this level, but thought you should know.

**Comment by Kitakazi** [comment]
Although I have skybox set to "none" turning off the sun shadow has boosted performance by about 5 fps.

**Comment by Kitakazi** [comment]
@plemsoft 
As of this latest update this level running waaaay better. There is 1 hallway that the frames will drop from 60 to 45-50ish but its mostly at 60 fps. Shooting the AK47 still drops frame rates but this is like 90% better. Closing this.
