### ISSUE TITLE
GameGuru MAX - Bug - Nodes Leave Balls In Game

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1607]
After Activating and Deactivating Shooter Games and setting up a node or two, you are sometimes left with a white ball in your scene which cannot be selected in any way. It shows up both in the editor and in the running game. 

![go1](https://user-images.githubusercontent.com/36735507/143254980-5f7974eb-f8e0-47cf-bffa-2a382d7ef3c7.png)

![go2](https://user-images.githubusercontent.com/36735507/143254987-71499a34-8ba8-4277-a192-4aa412743c9e.png)

**Comment by plemsoft** [comment]
@ArgentArts This was fixed in a older version , could you test this in the latest and let me know if this has been fixed for you , thanks :)

**Comment by ArgentArts** [comment]
This appears to be fixed. Thanks.
