### ISSUE TITLE
GameGuru MAX - Bug - Animated Double Door Model - One Door No Collision

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#1610]
I've been doing a lot of tests with doors in GameGuru MAX and I have a set of sliding double-doors. This particular set is strange in that the left door provides collision to the player, but the right does not. I've imported it to use standard box collision, so I assumed it should be using a box around both models when they are closed, suspending collision when they are being animated, resuming collision once they are closed again. But when closed I can walk through the one and not the other. Here is the FBX file:

[Sci-Fi_Door_01.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7598737/Sci-Fi_Door_01.zip)

**Comment by ArgentArts** [comment]
On further investigation, it's a coin flip as to which door will provide collision or if neither door will provide collision. It seems that MAX does not like that I have two models animated and exported as one ... or something.

**Comment by MonkeyFrogStudio** [comment]
Doesn't seem to be an issue any more.
