### ISSUE TITLE
GameGuru MAX - Bug - Custom textures reverting to original ones

### ISSUE THREAD

**Issue by ondrejciz1993** [TheGameCreators/GameGuruRepo#1612]
I am having trouble with assigning of custom textures to models. Let's say I have an asset that is already imported in the engine and I want to change the texture in editor by enabling the custom materials. So far it works well and the textures are displayed correctly, but the problem is that the textures keep reverting to the original ones.

This seems to happen quite randomly. Sometimes they revert back after selecting another entity or moving the selected model, but sometimes after reloading the level this does not happen, but the textures disappear again when saving the level. Sometimes this happens with all textures and sometimes for example just with the surface texture.

**Comment by ZakJudges** [comment]
Hi @ondrejciz1993, are you still experiencing this issue in the latest build? :)

**Comment by ondrejciz1993** [comment]
> 

Hi, I tried some tests and it seems to be fixed. Thank you.

**Comment by ZakJudges** [comment]
Thank you for confirming :) Closing this issue
