### ISSUE TITLE
Game Guru Max CRASH (November 2021)

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#1615]
Hi 
Since last weeks update Max was working well , as I put a few Small game ideas together,  ha I was saving the a game the not responding came up in the top left of the screen it was there for a few seconds before crash the my PC, I promptly got Max up and running  and there where no save games in my folder there should have be 4 that I have made over the weekend. any Ideas why this has happened.

All so notice that when I placed Soldier's  into one of the game You could walk right though him. The AI was good up on approaching enemy work men, they began moving forward, shouting and shooting at my character.
One other thing I can't seam to get all the terrain editor Icons to appear on screen limited to make hills only.
Keep up the good.

Keep up the Great wok that you are doing.
Quick Question for Lee, I use Lafette Mystical Dark age pack, it has a good Dungeon kit I was wondering how I can change the brick texture from dark grey to say a sandstone texture or any colour.

Thank Lee
and your Team

**Comment by LeeBamberTGC** [comment]
@Snage62 Has the crash from last year been fixed for you?
