### ISSUE TITLE
Waterlevel and enable trees are not saved

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1621]
The waterlevel and the enable trees setting are not saved and the level is loaded with the default setting.

**Comment by ZakJudges** [comment]
Hi @smmaas, I couldn't reproduce this issue. Are  you still experiencing it in the latest build? :)

**Comment by smmaas** [comment]
Problem has disappeared some time ago.

**Comment by ZakJudges** [comment]
Thank you for confirming. Closing this now
