### ISSUE TITLE
Walking the plank

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1623]
https://vimeo.com/manage/videos/650559763

**Comment by rvanner** [comment]
@smmaas Can you please upload this plank object? We can then check the collision that it's using.

**Comment by ZakJudges** [comment]
Closing this issue due to lack of information. There has been lots of fixes for physics shapes since issue was created, so it is likely fixed. 

If the issue persists, feel free to reopen and we can take a look :)
