### ISSUE TITLE
I fall through objects physics shapes

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1624]
The same object twice; same collision settings but I fall through one 

https://vimeo.com/manage/videos/650559869

**Comment by rvanner** [comment]
@smmaas Please share this model so we can analyse what's happening with it.

**Comment by LeeBamberTGC** [comment]
@smmaas Fixed in this weeks build.

**Comment by LeeBamberTGC** [comment]
@smmaas Is this still an issue, or has it been fixed. Will close soon :)

**Comment by ZakJudges** [comment]
Closing this issue, if the problem persists, feel free to reopen. Thanks.
