### ISSUE TITLE
rasterizing navigation

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1625]
At the moment it takes 4 minutes to start a level. The longest time is needed for "rasterizing navigation mesh". Would it be an idea to have an option to test an level without "rasterizing".

**Comment by Retrogamebloke** [comment]
I get this with old levels made in prior versions. Wait times of up to 4 or 5 mins to load the level, another 4 to run and then, runs really slow in game as well. A freshly made map seems to run fine. But not put much in bar trees as yet.

**Comment by rvanner** [comment]
@LeeBamberTGC will be focusing on this issue soon with the hope to have test game work immediately.

**Comment by ZakJudges** [comment]
Closing this issue as it was fixed some time ago
