### ISSUE TITLE
why

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1628]
spent hours and hours building a really pretty level (yes I know, we shouldn't be doing any serious projects as its still in testing) but BUT this has happeneed before, spent a day just playing around building, and with OUT explanation OR even a message or code or error or warning, MAX turns the collison of all the object off.  i DONT usually get annoyed by bugs as its still in alpha, but this bug really did my head in as its twice its happened now.

TRIED to select everything to give all the objects collision, but that doesn't work. Now I'm left with something I was really pleased with thats useless.

![image](https://user-images.githubusercontent.com/68471279/143688565-94df9562-c74a-444f-b910-43916c783aa9.png)

**Comment by rvanner** [comment]
@casigus Can you zip up and send us the map so we can have a look at it?

**Comment by ZakJudges** [comment]
@casigus Are you still experiencing this issue in the latest build?

**Comment by casigus** [comment]
yasss.

**Comment by casigus** [comment]
i mean noo. s'all good. :D
