### ISSUE TITLE
Particles Static Only?

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1629]
I realise this is a speed consideration. But please allow particles to be set to dynamic in some way, so we can move them in scripts.
![image](https://user-images.githubusercontent.com/44620846/143692607-3c1f85f1-015c-4c39-8c30-2afbd2ea7fcd.png)
My script works well with my place holder icon.
![image](https://user-images.githubusercontent.com/44620846/143693328-02115430-2da1-49cd-8745-a2796a582d99.png)
But would look much better with a particle effect.

**Comment by fearlesswee** [comment]
Entirely agree, there's numerous uses for moving particles, like status effects for an enemy (dripping with poison, on fire, etc.), movable objective markers, an dust effect that follows behind your car, etc.

**Comment by mav3r1ck1981** [comment]
@Kasseyus just an FYI next time youre cleaning up. @Necrym59 has provided a particle mover script in the stock behaviors.
