### ISSUE TITLE
Particles stay on screen when testing ( MAX )

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#1632]
I've noticed when trying out particles using the old particle system, when I turn off the test game them go back in the particles from the old test I just turned off are still there frozen to the screen.
Here is some leaf particles that are still there from the past test.
![Screenshot (32)](https://user-images.githubusercontent.com/75592663/143789605-157c93f8-a3ab-4d25-918e-1b9a1c6afdb8.png)
.

**Comment by plemsoft** [comment]
Fixed :)

**Comment by bluemeenie195** [comment]
Thank you, Preben

**Comment by Retrogamebloke** [comment]
Ah, nice to see it is fixed I have seen the same with my Lost smoke monster effect :) I would like a lot more control of the new particle system though, it has been crippled in recent updates as far as I can see. Used to be able to attach a script to move em, but last time I tried not possible :(

**Comment by bluemeenie195** [comment]
Sorry for the delay, But Particles still stay on screen after you exit out and start again
![Screenshot (36)](https://user-images.githubusercontent.com/75592663/148267744-111bbe47-096f-49ce-9961-591fac4662ab.png)

**Comment by bluemeenie195** [comment]
Could be tied to this problem
https://github.com/TheGameCreators/GameGuruRepo/issues/1724
