### ISSUE TITLE
UI problem when scaled to larger screens

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1633]
![widescreen_problem](https://user-images.githubusercontent.com/95015657/143828971-bbb143ec-ba30-4a36-a39a-5556f236a83b.jpg)

A possible neat fix maybe to move it to the sidebar.
![possible_fix](https://user-images.githubusercontent.com/95015657/143828994-b31c995d-2d4b-416a-b327-0cc9c4ccfef6.jpg)

**Comment by Necrym59** [comment]
Minimap out of position compared to area selector depending on screen ui scaling

**Comment by rvanner** [comment]
@Necrym59 We plan to change this editor. We want the user to just drag around the editable area so the mini map will be removed once this is in.
