### ISSUE TITLE
Max - Store bought FBX characters no longer walk forward they animate but only walk on spot. 

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#1635]
Since you did your mods to make MAX Character Creator models walk with foot planting. ( internal engine mods)
My FBX original characters no longer move forward they where quite happily following me around the terrain.
But now they just walk on the spot - they don't even turn to face my direction..
What is the magic sauce you have put on the MAX Character Creator models...

**Comment by thor49** [comment]
Have you come to the decision to dumb down Max so you can't write your own scripts anymore...
First you chop the legs off my original character models (walking on the spot)..( hundreds of pounds worth stuck)
Now I find I can't get access to my own written scripts from the object tools.. I have been writing scripts for Classic and Max for years
and having fun and enjoying the creation of ideas.. now you have took a sledge hammer to the AI system and nocked me back to the stone age.. I don't use the box connect system.. I write code using a code editor.. All my scripts where working perfectly
until you hi-jacked the only  commands that we have to move the characters around...( for your foot-plant-system)

RDFindPath(g_Entity[e]['x'],g_Entity[e]['y'],g_Entity[e]['z'],TargetX,TargetY,TargetZ)
pathPntCnt[e] = RDGetPathPointCount()
StartMoveAndRotateToXYZ(e,myspd,turnspd)
targPntIndex[e] = MoveAndRotateToXYZ(e,myspd,turnspd)

Using these commands everything was working great now 
Please , Please give me these code functions back 
OldStartMoveAndRotateToXYZ(e,myspd,turnspd)
OldMoveAndRotateToXYZ(e,myspd,turnspd)

**Comment by LeeBamberTGC** [comment]
@thor49 No plans to hi-jack, dumb down, chop off legs, using sledge hammers that I am aware of.  Can you post an attachment of a simple level and asset to show the issue you are having, thanks!

**Comment by LeeBamberTGC** [comment]
P.S. Made a fix for this week's build which fixes a bug causing characters not walk on the spot and not use the movement speed setting in the advanced properties of the object.  Maybe be related :)

**Comment by thor49** [comment]
Hi Lee (sorry just letting of steam) ..
I was having so much fun - my characters moving around the terrain then (stuck about 3 versions back).
I just noticed today that I can't get access to my scripts from the Behavior panel..
1. I click on the Behavior panel. - it shows the Behaviore Library page.
2. I klick on  -  MyScripts  folder in the left Panle list.
3. Then click - Newfantasy  folder inside my MyScripts folder.
4.  The right panel is Empty. (it should show all my scripts in that folder).
5. This used to happen in the older versions - but there where a load of little icons tick boxes at the bottom 
   of the the panel for diff-options I would untick these and presto my scripts would fill the panel.
6. So now I only have an empty window.. There is no way to see my scripts..

On the stuck characters  I saw in your code the rem about moving the move with animation into the main engine
so took that to be the reason for my character not working anymore.

I hope the fix this week does the trick - I really do enjoy writing code and trying to get the characters to do what you want
and it was working so well.. fingers crossed...

**Comment by thor49** [comment]
The other thing I just noticed. I am sure I was able to type the Path and script name into the Object tools panel in the older versions.  There does seem to be less Developer options available in Object Tools panel..

**Comment by synchromesh62** [comment]
@thor49 
Add this to the top of your scripts for example.
--DESCRIPTION:custom-door
Your scripts will then show up

**Comment by thor49** [comment]
Thanks Synchro just tried that and yes I can see my scripts.. 
Only thing is I have hundreds of them.. I 'll just update them as I need them..
Thanks..

**Comment by LeeBamberTGC** [comment]
@thor49 There is a fix in this week's build that restores the movement speed when applied to characters that do not have a Bip01 spine so you can move them by specifying the speed in the object properties.  If the object is not set as a character, then the MoveForward will be fine to move entities about.

**Comment by thor49** [comment]
Thanks Lee - looking forward to Friday..

By the way Lee. The terrain system is really great.
 In fact it's a bit intimidating to think how to fill that area.. really blows my mind..
Keep up the good work..

**Comment by thor49** [comment]
GOOD NEWS - I have found a solution..

I tried all day trying to find Difference between Models that worked and those that did not.. To no avail.. 

Tried re-Importing some models did not go well... 

Then I thought maybe I could code my script differently..

Then I noticed my (non working models) where always pointing in
the correct direction.. but just walking  on the spot..
( Penny dropped) why don't I just do the move forward when the
 targPntIndex[e] = MoveAndRotateToXYZ(e,myspd,turnspd, MoveType) 
 returns a positive flag...

And Yes my (non working) models start moving to the targets and Stop when they get there..

Thank you Lee.. I think I am back on track...

Have a Happy Christmas and good Health to you and yours..

**Comment by LeeBamberTGC** [comment]
@thor49 That's great news. I am leaving this one open so any other 'movement of imported' issues arise for you :)
