### ISSUE TITLE
GG MAX / Imported model does not render properly

### ISSUE THREAD

**Issue by sirlion87** [TheGameCreators/GameGuruRepo#1636]
I bought a prop for use in my project but the 3D model doesnt render properly after importing it. Here-s the issue
![o2](https://user-images.githubusercontent.com/92697844/144467030-f8de355c-c6bf-424b-94ed-6f925ded2048.jpg)
My model as it should be

![o1](https://user-images.githubusercontent.com/92697844/144467087-cc493d88-7bfd-4dbf-8610-7830eba7b65b.jpg)
My model in MAXs import window. As you can see part of the model cant be rendered.

The model in question
[Plate.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7643728/Plate.zip)

As a side note, please consider adding an Edit button in the assets window so that we can easily edit imported assets again if needed instead of having to hunt down the fpe file associated with them.

**Comment by Granada1** [comment]
![Random_003](https://user-images.githubusercontent.com/35897659/144481758-1db1a1e5-e404-4b24-9d9e-135bc10b3b8b.png)
Hi , Select each mesh and click double sided in the importer

**Comment by Granada1** [comment]
Better Picture 

![Random_004](https://user-images.githubusercontent.com/35897659/144482335-934711c1-d6aa-4b4f-9b19-77b088b065f2.png)

**Comment by sirlion87** [comment]
Sweet. Thank you.

**Comment by sirlion87** [comment]
> Better Picture
> 
> ![Random_004](https://user-images.githubusercontent.com/35897659/144482335-934711c1-d6aa-4b4f-9b19-77b088b065f2.png)

Warning THE ISSUE IS NOT SOLVED. I just downloaded the new version of GG MAX and tried doing what Granada said.
The option to use "double sided" is not saved.

Look here:
![1](https://user-images.githubusercontent.com/92697844/144722180-7364ba24-47d4-495b-a7d5-8a751e012ebe.jpg)

In game
![2](https://user-images.githubusercontent.com/92697844/144722186-b6e1c49d-2c98-441d-91e3-7a70eedefd5c.jpg)

**Comment by plemsoft** [comment]
@ZakJudges This has been fixed and committed ready from the next update :)
