### ISSUE TITLE
Serious Engine Speed Issues

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1637]
![slowdown_examples](https://user-images.githubusercontent.com/44620846/144485558-ebc87c47-df8e-40d7-9ba9-81f7120bf529.jpg)
Various examples of crazy slow fps rates.
![map](https://user-images.githubusercontent.com/44620846/144485916-dc5a16de-077c-456e-a059-3cd0c74ffba4.jpg)
Only covered a tiny part of the map.
The framerate bobs up and down making you feel like your stuck in quicksand.
Athlon 1700 8 core CPU, Nvidia 970GTX 16 gig Memory.

**Comment by AmenMoses** [comment]
![island](https://user-images.githubusercontent.com/35708338/144486871-738ec625-fc0a-4af2-8fc6-6b5b53fa0f4c.png)

Same map on a 6-core gen 9 i5 with RTX 2060!

**Comment by ArgentArts** [comment]
Is this map share-able so others can test it to see how well (or not well) it functions on other PCs?

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
