### ISSUE TITLE
GameGuru MAX (update 2021-11-26) - Crash of the Standalone with the error code 7008

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#1638]
It happened with this workflow  :   
- design of the landscape + adding trees and plants (those ones that are also available in GG Classic).
- after having saved the map and the game project, I selected the option "Play Game > Normal" in the "Game Storyboard" menu.
- I was glad to see that the plants were included in the landscape.
- Then I exported the game  ( save standalone game).
- I tried to run that game, but its execution immediately stopped after the screen "loading ..." with the error code 7008 (If I correctly remember).
- I reloaded the project again and again, trying to find out what could cause that failure. For that purpose I deleted the vegetation and any other entities included in the project, but that error code was systematically issued with the execution of the standalone.
 
- Later, after having reinstalled GG MAX (updated 2021-11-19), I noticed that the standalone game of that problematic project worked fine with that version.

**Comment by plemsoft** [comment]
@marcuswilm Thanks for reporting this issue, this has been fixed and will be in Todays update :)
