### ISSUE TITLE
Bug: pbroverride=0 causes endless loop 

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#164]
Making pbroverride = 0 in the setup file causes GG to go into a crash / resume session endless loop when loading a map. No error number, just an endless loop, have to end task to get out of it. This is with most, if not all of my own maps. 

This is in PP 2018.04.14 DX11

**Comment by plemsoft** [comment]
Just tried this and did not have that problem , i did notice that sometimes Steam do not update the .blob files , could you try this, edit setup.ini and set  "forceloadtestgameshaders=1" , just to make sure you have the correct shaders compiled for "pbroverride = 0" :)

**Comment by tarkus1971** [comment]
Re-installed new DX11 and problem was gone. Now I have some entities not on my maps anymore. Only a few so it's not a biggie.

**Comment by Belidos3D** [comment]
Are those entities that have odd sized textures? ie not 512, 1024, 2048, etc. If so then that's the reason, GG now needs textures to conform to that format.

**Comment by LeeBamberTGC** [comment]
Was able to reproduce this with PBROVERRIDE=0 and some entity combinations and fixed for current live version.
