### ISSUE TITLE
Add back the ability for custom terrain textures

### ISSUE THREAD

**Issue by DieselDaveFB** [TheGameCreators/GameGuruRepo#1640]
Can we get this feature implemented back in to the editor? There is a new terrain texture button but as of the last two builds that I have been a part of, it's inop.

Thanks,
RealityForgotten (Dave)

**Comment by rvanner** [comment]
This has been removed for the Early Access version. It's something we will add in post EA release.

**Comment by DieselDaveFB** [comment]
It's a pretty important feature to have. Not sure why something like this would be pushed until after early release.
