### ISSUE TITLE
Issues with collision detection on imported and standard assets

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#1642]
I am having issues with the collision on custom objects. 
I have checked my models several times and I have even had them working in game, but out of nowhere they have just stopped working.

I had a simple building with an arch, worked fine for a while, but when I imported a new model it re calculated all the collision, and now it doesn't work anymore. Even some of the assets that came with GGMax have stopped detecting collision correctly. 

The second issue is any rotation on an object and collision stops working altogether. I have imported a number of building several times, however whenever I rotate the buildings I can walk through them no matter what collision method I use.

**Comment by ArgentArts** [comment]
You should attach a sample model here that has the issue so the TGC team can try to replicate it and, then resolve it. :)

**Comment by smmaas** [comment]
issue 1624 could be the same problem half of the bridge was copied and rotated.

**Comment by AmenMoses** [comment]
Not model specific, tried to set up some stock models for physics use and kept getting failures in constraint creation (which indicates Bullet doesn't consider them valid physics objects).

Set a box to be dynamic with physics, box shape and was able to walk through it in test game, was not rotated either.

**Comment by LeeBamberTGC** [comment]
@42Pix3ls Much work done on collision modes and physics for this weeks build.
