### ISSUE TITLE
GameGuru MAX - Bug - Trees Still in Water

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1643]
As of Build 2021.12.03 trees still propagate in water:

![tree_water](https://user-images.githubusercontent.com/36735507/144710447-63cc2749-5ce8-4c06-9228-d705077af87e.png)

**Comment by rvanner** [comment]
@ArgentArts I just tried this and trees do not show under the water plane when it's moved up and down. Go to the terrain section where you will now find the water section and move the height up and down.

**Comment by rvanner** [comment]
@ArgentArts Can I close this please? This is an old issue.

**Comment by ArgentArts** [comment]
Absolutely! :)
