### ISSUE TITLE
Objects move slightly when selected

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1645]
https://vimeo.com/653354939

**Comment by AmenMoses** [comment]
Yes and iit's very annoying!  :)

**Comment by rvanner** [comment]
We'll sort it asap!

**Comment by Retrogamebloke** [comment]
Yes it is annoying and weirdly before the last couple of updates did not do it at all. It did it for trees, but not for objects. But yeah, you have your map set but need to alter some objects properties, it moving each time is a real pain in the rear, particularly if they are walls or fences :)

**Comment by LeeBamberTGC** [comment]
Fixed for the next update, only when you move the mouse will the object attempt a move.
