### ISSUE TITLE
Max hangs when loading a level

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1646]

**Comment by rvanner** [comment]
Does this happen every time? Is so, can you send us your level?

**Comment by smmaas** [comment]
Level send by wetransfer, also contains the objects for 1623 and 1624 and the performance issue 1625. user/extra/plank01 and user/bruggen/kettingbrug.

**Comment by Retrogamebloke** [comment]
I have been having this problem as well. Load your level and it sits there until you quit. Try again and presto works! Still a bit slow to load but loads. The really weird thing here is when I get this behaviour my level runs way faster. In fact it runs as I would expect a 970GTX to run the scene. It's a weird one I have mentioned on Discord a fair bit the last few days. I seem to be in the minority though as no-one else seems to get the issue.

**Comment by plemsoft** [comment]
@smmaas This has been optimized and will be in the next update, you also get faster load :)

**Comment by rvanner** [comment]
@smmaas & @Retrogamebloke Is this still an issue for you now or can we close this issue down now?

**Comment by plemsoft** [comment]
@smmaas Feel free to create a new issue if you still see this in the latest version, thanks :)
