### ISSUE TITLE
GameGuru MAX (alpha 2021-11-19 and probably alpha 2021-12-03) :  Object Tools > setting "isImmobile"

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#1647]
Guess method : It seems that when the setting "isImmobile" is enabled in the Object Tools Parameter, it ensures that the entity to which it is applied doesn't "float" in the air when the level is played in developer  mode ( during the edition of the level).

Problem :  Even if that setting is enabled in the Editor, it is not saved (save level or save standalone). 
Therefore when the level is reloaded or when the standalone is executed, the entities to which that setting was applied in the Editor have forgotten that they have to stay on the ground.

I don't see any line in the .FPE files that could identify that setting "isImmobile".
However I admit that if that setting is necessary for an animated entity, its name "isImmobile" is confusing.

**Comment by Retrogamebloke** [comment]
IsImmobile is actually just a way to ensure physics objects stay put and don't use the physics engine to move in any way but are still physical objects in game. I have noticed some issues in this area as well. A level that was working great when first set, can suddenly break when reloading the level or in standalone. I'm talking npc navigation here. Been having this issue for a couple of days and even when you go back and set everything as you should, never seems to fix it.

**Comment by plemsoft** [comment]
@marcuswilm Thanks for reporting this issue , this is working in the latest build , please let me know if this is also fixed for you , thanks :)

**Comment by marcuswilm** [comment]
@Retrogamebloke : Thank for your comment that I discovered today. 

@rvanner :  Thank you for your e-mail. I may confirm that this issue was **fixed** with the alpha version 2022-02-18.

:-)
