### ISSUE TITLE
footstep sounds are bugy - sound plays way to less

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#165]
Since the new update, the footfall sounds are kind of messed up.. 

When I dont have any weapons equiped, the sound plays not like it should.

Can be seen in this video right at the start:
https://www.youtube.com/watch?v=0tnzIksR80w&t=

Please fix it :)

**Comment by LeeBamberTGC** [comment]
Have you found the FOOTFALL PACE in the Player Start marker which has been added so you can control this?

**Comment by Duchenkuke** [comment]
yes, I always have used it to change the player movement a bit
![2](https://user-images.githubusercontent.com/35990507/38821617-5d6d4f5a-41a1-11e8-883e-d95758a799af.PNG)

**Comment by LeeBamberTGC** [comment]
Try it at 150, you will find the footfall pace increases. You can also see the logic here: https://github.com/TheGameCreators/GameGuruRepo/blob/master/GameGuru/Files/scriptbank/gameplayercontrol.lua and look for the 'ttFootfallPaceMultiplier' variable for the details.

**Comment by Duchenkuke** [comment]
but it works fine when a weapon is equipped... I dont get it.

**Comment by LeeBamberTGC** [comment]
It was a bug, when no weapon was equipped the footfall multiplayer was 0.4. sorted in next build.
