### ISSUE TITLE
Widescreen FOV distortion

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1650]
Image 1 is upon immediate loading of a level in GGM. The FOV in the 3d level editor window is distorted.
![1](https://user-images.githubusercontent.com/95015657/144928800-c314c818-42a6-493d-8e4a-08f410a8f595.jpg)

After clicking the windows restore down/maximise button the FOV is then displayed correctly.
![2](https://user-images.githubusercontent.com/95015657/144928842-6f1414c0-2370-403a-a211-e70c7f644d65.jpg)

**Comment by plemsoft** [comment]
@Necrym59 Thanks for reporting this issue , as i remember we made some fixes to FOV could you let me know if this is still a issue in the latest build , thanks for your help.

@rvanner I do not have a widescreen monitor, and cant test this myself.

**Comment by plemsoft** [comment]
@Necrym59 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Necrym59** [comment]
This is now confirmed fixed as of Build 2022.03.04 - thankyou guys

**Comment by plemsoft** [comment]
Thanks for confirming :)
