### ISSUE TITLE
Changing the Collision Shape on an entity will change the collision for all copies of that model.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1651]
Put 2 (or more) of the same model in a level. Change the collision shape on only one of them and the others will also change, even when they were not selected.

**Comment by Retrogamebloke** [comment]
I have noticed this as well. Not sure if it's a feature (sort of makes sense) or a bug (sometimes we want different settings for objects) I get silly issues like collision working at one point, load your level back up and collision is messed up! Working fine when making the level, but broken when loading the same one.
For example I am using the broken fence object in a level. Had to turn off collision entirely to get npc's to walk through. Worked, but they could walk through the fence bits. Added invisible walls for those parts and it worked a treat. Next time I loaded the level all broken and no amount of changes could really fix it :( Levels are defo losing some settings and can't fix em after at present.

**Comment by Kitakazi** [comment]
Well considering it wasn't like this a few weeks ago I'm guessing it's a
bug.

**Comment by LeeBamberTGC** [comment]
@ZakJudges I believe you added the code to allow per object changing of the collision shape. Can you check to make sure it works in all the above scenarios, thanks!

**Comment by ZakJudges** [comment]
@Kitakazi This should be fixed now. Can you confirm you no longer experience the issue? :)

**Comment by Kitakazi** [comment]
@ZakJudges Seems to be fixed now. Thank you!
