### ISSUE TITLE
GameGuru MAX ( any alpha versions ) : Collision Shape = Polygon

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#1653]
I think that the best way to explain the problem relative to the "Collision Shape = Polygon" is to provide this link to a little standalone created with GameGuru MAX alpha 2021-12-19 and shared on my [OneDrive](https://1drv.ms/u/s!AjokN1FU3jK1mBt9UbdkQlB4XwEk?e=zbeUJo) 

You have the choice in that shared folder :  the standalone (217 MBytes) and its zipped version (151 MBytes). Sometimes from upgrade to upgrade, Windows 10 cannot unzip files/folders that were zipped with its own builtin zipper (?!).

Workflow : 
- I created a mesh (see screen capture) and its uv mapped material with my preferred modeler MetaSequoia 4 Pro.
- I exported in GlTF format and I created a basic animation (no rigging) in Blender 2.90 and again it was exported in GlTF format.
- GameGuru MAX has now a nice GlTF importer (even if the import of the morphs  - available in that format and playable in the Microsoft 3D Viewer of Windows 10 - are not available in GameGuru MAX).
- In the level created with an untextured small terrain, I placed a first copy of that entity with these settings in the "Object Tools" :  
   - Grid and Alignment Settings :  Selection of "Enable Grid Mode" +"Use Grid Positions" + "Zones Follow Terrain" + "all Grid Offsets = 99" .
   - General :  Selection of "Physics On" + "Collision Shape = Polygon".
   
- With the selection of that first entity on the terrain + the "Shift" key, I created rows and columns.
- I noticed that with that automatic alignement on the grid, those entities (with a correct "Polygon" collision) were "interpenetrating" each other.

- In the standalone, you could also notice strange shadows appearing randomly and caused by two white sphere that weren't included in the level.
- 
![collisions_polygons](https://user-images.githubusercontent.com/94678034/145211274-4f935374-2944-4805-ab6d-696cecac3688.jpg)

**Comment by ZakJudges** [comment]
Hi @marcuswilm, apologies for the late response, just working through a back log of bugs :) 
Since  this issue was created, there has been more work to the grid alignment system that should sort this issue for you

**Comment by marcuswilm** [comment]
Hello ZakJudges,

Thank you for your work and replies relative to some of my old bug reports. 

I think that this bug was corrected in the latest versions of GG MAX.
Therefore I am closing this thread.

Have a nice day.
