### ISSUE TITLE
Tent Dirty Framed Object GameGuru MAX

### ISSUE THREAD

**Issue by tylo74** [TheGameCreators/GameGuruRepo#1654]
the meshbox is messed up I can walk straight through it as if the mesh box is extended bigger than the tent itself the meshbox is too large for the tent size

**Comment by rvanner** [comment]
This model:

![image](https://user-images.githubusercontent.com/1503593/145436680-94abd8b6-4ab0-42ce-bbb8-acd7e883b423.png)

**Comment by LeeBamberTGC** [comment]
Fixed for friday build

**Comment by rvanner** [comment]
Confirmed as fixed.
