### ISSUE TITLE
GameGuruMAX - Cannot Add or Edit Behaviours

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#1655]
The buttons on the behaviour panel are not accessible, please see screenshot
![issue](https://user-images.githubusercontent.com/35724756/145430445-42c5268a-442f-49eb-8ae8-cfb135ff7cff.png)

**Comment by rvanner** [comment]
This has changed in our internal builds. Please check after the Friday release and see if you still have an issue.

**Comment by Retrogamebloke** [comment]
You can still change behaviour if you select the tiny strip of the bottom option. Obviously, this needs to be fixed, but can be still used in the meantime.

**Comment by rvanner** [comment]
Old issue, no longer relevant.
