### ISSUE TITLE
Slider control on object postion panel discrepency

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1657]
The slider control on the object postion panel for the Y axis dosent re-centre correctly after use, or after typing a number in then set back to 0. Not a show stopper but needs a look into
![position-slider](https://user-images.githubusercontent.com/95015657/145521247-ec514d81-116c-49cf-8aa5-6c4744b3895b.jpg)
.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb This looks fine for me, but the report is old so worth checking to see if you can reproduce it.

**Comment by dllllllllllb** [comment]
Works fine for me as well :]
