### ISSUE TITLE
Textures missing on this Arctic model

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1658]
This Arctic model has no texture when you add it to your level;

![image](https://user-images.githubusercontent.com/1503593/145551262-da4b727b-eb57-4e4a-9d0b-d0bd019a7a56.png)

**Comment by rvanner** [comment]
![image](https://user-images.githubusercontent.com/1503593/145551607-553b7574-b72d-4c4a-be5e-34ce1a7ea87c.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Looks fine, can you try again?:

![image](https://user-images.githubusercontent.com/35840583/145577263-ed1f0f71-2965-43ac-a8c8-8548373e6c37.png)

**Comment by rvanner** [comment]
@LeeBamberTGC Zak showed me this issue so I tried it on my install and had the same problem. I can show you in our call in a mo.
