### ISSUE TITLE
Loading maps lose object textures

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1659]
Image of saved map from previous version
![saved](https://user-images.githubusercontent.com/95015657/145659934-1f2d76aa-881f-489f-8f00-1372912d7da2.jpg)

Image of same saved map when loaded in newest version 2021.12.10
![new](https://user-images.githubusercontent.com/95015657/145660001-7df62887-f32f-4c30-8875-16c7f514c656.jpg)

Doesnt seem to remember any textures applied to objects, moreover it seems to apply random textures.

**Comment by Necrym59** [comment]
After re applying textures to the objects as per the first screen shot i then tested the game and this was the result
![testmap_result](https://user-images.githubusercontent.com/95015657/145661296-42805172-11e2-4de4-bc46-a2363234db52.jpg)
.

**Comment by Necrym59** [comment]
It 'seems' they keep their applied textures only if you lock them afterwards before saving the map, if that helps.

**Comment by plemsoft** [comment]
@Necrym59 Thanks for reporting this issue , a lot of changes has been made to how the custom materials works , just tested this in the latest version and it works perfectly fine here, could you also try this in the latest version and let me know ifd this has been fixed for you , thanks :)
![custom-textures](https://user-images.githubusercontent.com/18662417/155503790-590a20f7-63f5-49d5-a9c3-e7b519bf7181.jpg)

**Comment by Necrym59** [comment]
This is now confirmed fixed as of Build 2022.03.04 - thankyou guys

**Comment by plemsoft** [comment]
Thanks :)
