### ISSUE TITLE
Flashlight problems

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#166]
Whenever I have to save performance I turn off the lightrays.

Problems is that somehow the flashlight is tied to the lightrays now and this should be changed!

The Light will show on entities, but not on the terrain.

It worked in DX9 so I think its fixable. Thanks very much.

**Comment by LeeBamberTGC** [comment]
Dropped in crate, ran test game, flash light works on entity and terrain floor, with both lightrays mode set on and off.  Can you send me an FPM and a step by step to clearly show the issue, thanks.
![image](https://user-images.githubusercontent.com/35840583/38821504-91efc3d8-4198-11e8-8aac-e139eb9782f8.png)

**Comment by Duchenkuke** [comment]
hmm... okay..

I have an outdated seupt.ini tho.. maybe this issue is just on my end - those small updates mixed some of my stuff up. I will try some stuff and report back later!

**Comment by corrosionsting** [comment]
I am having this issue on a few maps

**Comment by Duchenkuke** [comment]
since the new version, I have this too again. pls open the thread again.

**Comment by corrosionsting** [comment]
This is definitely back

**Comment by LeeBamberTGC** [comment]
Okay, we need a good step by step from a fresh run on a blank map, using stock media and a clear idea of your TAB TAB settings and what you see and what you expected to see. Sounds a lot but it is the only way to get an accurate reproducible. Thanks.

**Comment by Duchenkuke** [comment]
It is acutally very simple. 

I just opened a new map - completely empty. 

I turned off lightrays - and the flashlight disapears!
I think it would be better to untie the flashlight from the lightray slider. Because lightrays are quite a frame killer...

**Comment by corrosionsting** [comment]
I can confirm the above statement

**Comment by plemsoft** [comment]
This was a problem with the camera postion changing in the shaders when lightrays was set on off , this has been fixed in the latest public preview.
