### ISSUE TITLE
Lua error upon testing a map

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1660]
Receiveing this lua error approx 10 secs in upon testing this map
![lua_error](https://user-images.githubusercontent.com/95015657/145661357-c0d6b31b-40ab-40f8-813e-fc3d6c3c6bc7.jpg)

![test_game_eror](https://user-images.githubusercontent.com/95015657/145661329-fd12578d-6328-4b40-8644-9f746a512af8.jpg)

No real reason i can see nothing special in the map just a couple of rocks and a fish in the river

**Comment by Necrym59** [comment]
Have since removed the fish and error is gone

**Comment by Necrym59** [comment]
Seems only when the fish are in the water the error occurs they work fine on dry land

**Comment by Necrym59** [comment]
I believe its because the script attached to the offending fish isnt complete.

**Comment by AmenMoses** [comment]
Who attached the mammals script to the fish?  Doh!

**Comment by LeeBamberTGC** [comment]
@AmenMoses TWas me :)  Can you send me your fish script, and any other in-progress scripts for birds if you have one? I can then make the substitutions. Thanks!

**Comment by AmenMoses** [comment]
Still have a few issues regarding the fish to sort out, the mammals script isn't really ready yet either!

Oh and I haven't even started on the birds.

**Comment by LeeBamberTGC** [comment]
@AmenMoses No worries, just got excited to show off your mammal logic, looking very nice indeed!!

**Comment by Necrym59** [comment]
I think this one is essentially fixed isnt it

**Comment by LeeBamberTGC** [comment]
Mammals and Fish now connect to the correct behaviors :) Only bords remain.  This one can be declared fixed.
