### ISSUE TITLE
Gameguru MAX - Yet another Model Importer issue

### ISSUE THREAD

**Issue by sirlion87** [TheGameCreators/GameGuruRepo#1663]
Hi. I wanted to import some tablecloth models. Importing the basic model itself works just fine, however, MAX remembers a normal map I assigned previously to another model and forcibly adds it to my next models even though I never specified a normal map for them.

Here is my model ready for import, no normal map or albedo assigned
![1](https://user-images.githubusercontent.com/92697844/145683572-1832de3b-dc42-4177-a1c4-a97615a25587.jpg)

But the model importer just casually adds one to it
![2](https://user-images.githubusercontent.com/92697844/145683594-2679974c-50ac-4f90-aa26-cca2148ac665.jpg)

And on top of this, it doesnt seem to recognize that it is indeed a normal map, because the in-game model looks violet instead of white.
![3](https://user-images.githubusercontent.com/92697844/145683604-060f1f98-70d8-4225-b59b-1da28bf477e0.jpg)

**Comment by ZakJudges** [comment]
Hi @sirlion87, are you still experiencing this issue when importing the object in the latest build? If so, would you be able to send me the model (zak@thegamecreators.com) so I can reproduce the issue? Thanks :)

**Comment by sirlion87** [comment]
Hello. Thank you for reminding me of this thread, I actually tested it already 2 patches ago and the issue was no more. I have no idea what caused it in the first place. For now, it seems to have been solved itself (?)
