### ISSUE TITLE
Game Guru Composite Artifacts 

### ISSUE THREAD

**Issue by cstriage13** [TheGameCreators/GameGuruRepo#1665]
Check out the tree line at the top, sky and tree line do not render cohesively and do not composite.  Happens with current update.

![Screenshot 2021-12-12 045331](https://user-images.githubusercontent.com/84180614/145709575-33143d5d-4c6f-40a3-a31a-40de1cc5364c.png)

**Comment by PaulSJ** [comment]
Duplicate of #2193
