### ISSUE TITLE
GG Classic  all sound disappear if there is no interact with editor or standalone

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#1666]
I have noticed it for along time now but only decided to report this now. if i am busy in the editor or playing  standalone game and lets say i have to leave and go and go something else , if i came back after a certain time ( not sure how long but a while) then GG have no sound or it looks like the sound is mute. even if i load another map or reload the same map it does not fix the sound. i have to exit the editor or standalone game and restart it, only then does the sound come back

**Comment by Pcskiller** [comment]
I am using win10.  I will check if it could be an screensaver , wil test
and report again

**Comment by Pcskiller** [comment]
its not the screensaver

**Comment by LeeBamberTGC** [comment]
@Pcskiller Classic uses the DirectSound interface, which needs to 'own' the device when using the software. If you ALT+TAB out of the application and use something else, that other app could steal the device ownership away from the software.  If you can run tests around this scenario, and see if you can find a reliable way to reproduce this, we can then have a handle on it and more importantly, know when we have fixed it.  Once you can reliably reproduce each time, I have a few ideas that might force the device to reset when you ALT-TAB back into Classic.

**Comment by LeeBamberTGC** [comment]
@Pcskiller Tempted to close this soon as no other reports of something similar. Do let me know, even if it does get closed if you find more data on the issue, and if you found any workarounds aside from restarting Classic when it happens. Also maybe post iof you replace your PC/motherboard and if that solved it too.

**Comment by Pcskiller** [comment]
I will let you know if i found anything else or new on this problem.
