### ISSUE TITLE
X model imports doesnt translate animations correctly in Game Guru Max

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1667]

**Comment by Necrym59** [comment]
The X model import of animated objects does not seem to translate the animations correctly and do not correspond to the animations in the model. Attached is and example to trial I could not get this correctly in,
[WWII Soldier 01 (Assault).zip](https://github.com/TheGameCreators/GameGuruRepo/files/7699875/WWII.Soldier.01.Assault.zip)

**Comment by LeeBamberTGC** [comment]
@Necrym59 Try using the Guru-Converter in the root, it works better for X than the ASSIMP import model system

**Comment by Necrym59** [comment]
I would but it there is no such animal on my computer that runs. Only Guru-Converter.exe which refuses to run, just loads and dissapears, or is it a command line thing.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Just place any X file in the Files folder and run the converter. When you next look, you will see the DBO equivalent next to it :)

**Comment by Necrym59** [comment]
Ahh ok that worked many thanks Lee
