### ISSUE TITLE
Display/Bug Problem with the storyboard

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1668]
If editing or just entering a menu screen the thumbnails are not updated and just disappear altogether.
![storyboard](https://user-images.githubusercontent.com/95015657/145730946-8ed6e2bf-6884-4b1f-9833-37760a4b49c1.jpg)

However the actual menu is still there.
![storyboard_edit](https://user-images.githubusercontent.com/95015657/145730969-b87a9601-0f06-477e-885f-f84f889a407a.jpg)

**Comment by rvanner** [comment]
@Necrym59 Can you make a video of this issue? I am not seeing this here on my PC.

**Comment by Necrym59** [comment]
Videos as Requested
[GameGuru MAX 2021-12-13 19-40-27-Storyboard_Bug.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7702251/GameGuru.MAX.2021-12-13.19-40-27-Storyboard_Bug.zip)

**Comment by Necrym59** [comment]
Done and postedSent on the go with Vodafone
-------- Original message --------From: Richard Vanner ***@***.***> Date: 13/12/21  7:24 pm  (GMT+10:00) To: TheGameCreators/GameGuruRepo ***@***.***> Cc: Necrym59 ***@***.***>, Mention ***@***.***> Subject: Re: [TheGameCreators/GameGuruRepo] Display/Bug Problem with the storyboard (Issue #1668) 
@Necrym59 Can you make a video of this issue? I am not seeing this here on my PC.

**Comment by rvanner** [comment]
@Necrym59 Thanks for the video. This relates to the same issue I have on my PC. 

@plemsoft Looks like the screen grab is not correctly grabbing the correct area of the screen when it updates the thumbnails. It's exaggerated on this ultra wide display.

**Comment by plemsoft** [comment]
@Necrym59 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Necrym59** [comment]
This is now confirmed fixed as of Build 2022.03.04 - thankyou guys
