### ISSUE TITLE
Bug:  Runtime Error: 0 : BT Error: Terrain dont exit Function:BT SetTerrainLODDistances()

### ISSUE THREAD

**Issue by Dimoxinil** [TheGameCreators/GameGuruRepo#167]
GameGuru PUBLIC PREVIEW 2018.04.14

Using Lua  **SetSkyTo()** with  **superflatterrain=1** GameGuru crashes  wit  the following message:
Runtime Error: 0 : BT Error: Terrain dont exit Function:BT SetTerrainLODDistances()

This happens both in old or new maps.

**Comment by LeeBamberTGC** [comment]
Well spotted, fixed in next PP build up in a few hours (early 17/04/18 GMT)
