### ISSUE TITLE
FIRE!!!!!!

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1670]
WHEN YOU up the emission strenght on fire, the fire looks banging, proper intense glow! however the emission function also switches its self off or the fire decal turns into a weird black textureless smoke!!

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/145848753-7ec7a6f6-e1df-4d64-a42e-3f210e43c67f.png)

**Comment by LeeBamberTGC** [comment]
@casigus Cannot reproduce this with stock assets, may have been fixed many moons ago.

**Comment by casigus** [comment]
yeah! must have been! can't say I've seen this happen again!
