### ISSUE TITLE
GG MAX - Model Importer overwrites old model with same name

### ISSUE THREAD

**Issue by sirlion87** [TheGameCreators/GameGuruRepo#1671]
Yeah I just discovered this to my own detriment, whenever you have two models with the same name, no matter if they are actually different in size, texture references or others, the new one always overwrites the old one without asking for permission to do so or alternatively creating a new name. Big oversight, especially for people who purchases models that have "model" as a generic name and need to change it themselves. I would strongly suggest adding a prompt that will warn the user of a duplicate in the models folder.

**Comment by ZakJudges** [comment]
@sirlion87 Thank you for reporting this issue. A fix has been added and will be in next Friday's build
