### ISSUE TITLE
goingindoors!

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1679]
SO i've added the goingindoors script to this trigger zone as i WANT to build a space level which you look out tthe windows and its space!!! added a starry skybox which is perfect, but can't seam to turn the terrain off!!

![image](https://user-images.githubusercontent.com/68471279/146648580-ebc9bbbd-5fd9-4a66-89b2-aedb64004686.png)

**Comment by Granada1** [comment]
Best start with a new level and chose empty , you will still have a ground pane  though

**Comment by casigus** [comment]
yas.....that's the problem! 😅

________________________________

**Comment by synchromesh62** [comment]
Terrain is totally different to GG and created in house.
Until we have more info on how to ( or if we even can ) its just not possible right now

**Comment by casigus** [comment]
ah! understood!! 🙂 thanks for the reply 😄

________________________________
