### ISSUE TITLE
Vanishing Grass

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1684]
Max standalones are losing the grass. Also in editor the grass gets disabled after a save. You can re-enable in editor, but standalones always seem grassless. Reloading always seems to start with grass disabled also.
![image](https://user-images.githubusercontent.com/44620846/146687995-9ffee953-c458-4015-b8fe-646189a0d83a.png)

**Comment by plemsoft** [comment]
Fixed :)
