### ISSUE TITLE
Entities - Foliage falls down slopes

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#169]
Some foliage such as Bush 7 (Animated) falls down slopes when in test mode. They can also be pushed by the player.

**Comment by Emperor2000** [comment]
@Teabone3 Have you tried turning off physics or making the entity static? I know my reply is really late by the way.

**Comment by Teabone3** [comment]
I can fix all these problems myself no problem. But I'm posting here so they can be fixed within the build so that other people don't have to waste the time to fix each time a new update is sent out. The fix would be more related to immobile and physics. Wouldn't want to make static as then they would become collide-able.

I also no longer contribute to Github fixes since my account got too mucked up working on the underwater functionality stuff way back.

**Comment by Teabone3** [comment]
This should be a simple fix. If I get my github fixed up i could easily solve this issue. Just having a lot of issues getting my github back up to speed again.

**Comment by LeeBamberTGC** [comment]
Just tried this entity and others, they are now static (but still animate) :)  No rolling down hills!
