### ISSUE TITLE
Request: Update the Blood Splat Effect

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1691]
The current blood splat effect when you shoot an enemy leaves alot to be desired. I believe it is the same one from Classic at the moment which is just not up to standards with what a modern Shooter game should have. 

Since there is a cool new particle system perhaps the blood splat could be a particle? 

Additionally having different blood splats to choose from could be really nice. Maybe a dropdown box in a Characters setting, so you could have a red spurt from humans, a blue splatter from aliens, black oil or sparks from robots, etc.

**Comment by fearlesswee** [comment]
I agree, the current blood splat feels like the ones from Doom (1993's Doom, not 2016's Doom.)

Replacing them with actual particles that look like liquid would be a lot better.

**Comment by mav3r1ck1981** [comment]
@Kasseyus this is also now provided in the core build
