### ISSUE TITLE
MAX - Replace outdated (and ugly) 2D images for explosions, bullet hit FX, etc. with particles!

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#1692]
It doesn't make sense to have this amazing particle system in place for MAX, but still use the 90's-esque 2D images which looked awful even for Classic's time, let alone MAX's! 

To that end, I'm requesting that all "effects" (such as explosions, blood puffs, bullet surface hit puffs, projectile effects, projectile hit effects, etc.) use a particle instead. (Maybe 2D sprites can be kept as an option for backwards compatibility or plain user preference.) This would not only help bring these outdated effects into the modern era, but would also look _**far**_ better in VR (once VR functionality swings around, that is.)

**Comment by mav3r1ck1981** [comment]
particle system for impacts etc is now in the core

**Comment by fearlesswee** [comment]
Closing as completed :)
