### ISSUE TITLE
Weird Shadows When Reducing Camera Range.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1693]
![image](https://user-images.githubusercontent.com/44620846/147107619-db2084f8-eb18-46b7-b6ca-2627b028c90d.png)
If you reduce the camera range lower you end up with odd shadows over the terrain.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke Fixed many moons ago, please attach FPM and camera range setting value if you can reproduce.
