### ISSUE TITLE
GameGuru MAX - Importer - Rotation on Z axis - please verify if it works correctly in the latest alpha.

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#1694]
Hello,

Please could you verify that the "Rotation on Z axis" in the importer of the latest alpha is correct.

In the alpha version 2021-11-19 the "Rotation on Z axis" and the "Rotation on X axis" are producing exactly the same rotation (on X axis).

**Comment by marcuswilm** [comment]
Hello Zak,

Thank you for your request.
It is nice to see new dynamic young members in The Game Creators team.

That issue relative to the rotation in the importer has been corrected in the latest versions of GG MAX.

:-)

**Comment by ZakJudges** [comment]
@marcuswilm Thank you, closing this issue :)
