### ISSUE TITLE
Character headgear disappears when viewed through transparent object

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#1695]
In GameGuru MAX alpha 2021-11-19 I noticed that here are a few issues with the characters as shown with those commented screen captures : 
![character01](https://user-images.githubusercontent.com/94678034/147154379-98f84730-118e-4e47-be3d-5c1a20155eb7.jpg)
![character02](https://user-images.githubusercontent.com/94678034/147154385-74de3cd0-5e3f-4021-b8b3-d0b2ec44899a.jpg)
![character03](https://user-images.githubusercontent.com/94678034/147154391-e76fecb9-0c8e-4247-9b43-661057b17508.jpg)
![character04](https://user-images.githubusercontent.com/94678034/147154394-8a2990c1-1ce2-41ef-b3e6-3a394354285f.jpg)

 Marry Christmas 2021 and Happy New Year 2022 to the great developers team of GameGuru (MAX and Classic) and of the other nice games engines of The Game Creators.

:-)

**Comment by ZakJudges** [comment]
Note: I have renamed this issue, as the only bug from above remaining (not fixed or unreported) is missing headgear

**Comment by marcuswilm** [comment]
Hello @ZakJudges.
Thank you for your comment.
I think that this problem (missing headgear)  is caused by the combination of textures where the alpha channel is used to produce the transparency.

**Comment by plemsoft** [comment]
@marcuswilm Just tested this and it looks like its fixed in the lastest EXP build :)

**Comment by marcuswilm** [comment]
Hello @plemsoft ,  this report is a very old one.  According to your test, I think it's time to close it. 
Then I do that now. Thank you. :)
