### ISSUE TITLE
GGMAX - Object Importer seems to crash after 2 or 3 imports.

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1697]
The Object Importer and Max crashes after importing 2 or 3 consecutive imports. This didnt happen in previous versions.
Also from a productive point of view can we have a Importer menu option so you dont have to load a level before you can import/convert.

**Comment by ZakJudges** [comment]
Hi @Necrym59 , are you still experiencing crashes in the latest build?

**Comment by Necrym59** [comment]
Hi Zac - No it seems to be ok now, just did half a dozen imports with no problems. Great work my friend.
