### ISSUE TITLE
Walls clipping when overlapped / Wall thickness / Scaling walls

### ISSUE THREAD

**Issue by ivanski1983** [TheGameCreators/GameGuruRepo#1698]
If objects overlap they clip in the editor and during test level.  Anything I can do to correct this other than scaling the wall size?
![155E326F-E9AB-4F9A-8590-50831F60D3D8](https://user-images.githubusercontent.com/78671386/147366137-3472af8c-6028-4216-aa4e-109a347b2dd0.gif)

Are the walls meant to be different thicknesses?
![Walls](https://user-images.githubusercontent.com/78671386/147314102-4e06f936-86c7-46b1-9c22-bca60e031203.png)
 
Scaling walls
When walls are scaled the texture also scales, any way around this?
  - Also would clickable + and - buttons be faster for fine tuning adjustment.

Thanks

**Comment by ArgentArts** [comment]
When two pieces of geometry are overlapped "perfectly", any 3D game engine is going to struggle with attempting to display both pieces of geometry. It's the nature of the beast. You shouldn't overlap walls in that manner. They can cross each other, but should only butt up against each other. Use snapping to ensure your walls butt up against each other so they don't overlap.

**Comment by ivanski1983** [comment]
Makes sense, I was trying to make walls a specific length hence the overlap. I didn’t like scaling because it scaled the texture pattern as well. I guess I’ll open up blender and do some tinkering. 
Thanks
