### ISSUE TITLE
GG CLASSIC - Grass shadows are strange

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#1699]
This issue has been a part of gameguru for a VERY long time.

For Example, I made this GameGuru Level. Its a jungle that has a lot of foliage high above terrain.
![Guru-MapEditor 2021-12-25 11-09-56-79](https://user-images.githubusercontent.com/35990507/147382812-12f1b14b-1fd0-4990-a402-f2f69a14da12.png)

A large part of the grass on the ground should be in the shadows as you can see here:
![Guru-MapEditor 2021-12-25 11-10-06-73](https://user-images.githubusercontent.com/35990507/147382821-c8e7a159-487b-4d04-a413-441d0d5c688c.png)
but instead, the shadow only appears to some grass and not all.
Why is that ? It makes everything look terrible. Please Preben if possible, try to fix it :)
Merry Christmas and thank you!
![Guru-MapEditor 2021-12-25 11-10-02-61](https://user-images.githubusercontent.com/35990507/147382831-1ecdc6ad-78c1-4726-8c7c-4e261341958c.png)

**Comment by Duchenkuke** [comment]
could this be fixed for the june update? I think a simple shader change would do the trick

**Comment by Duchenkuke** [comment]
yes will do right away, hang on!

**Comment by Duchenkuke** [comment]
Here is how it looks at the moment.
![Guru-MapEditor 2022-06-16 15-33-55-15](https://user-images.githubusercontent.com/35990507/174081722-b678c1eb-97ce-48cc-80c1-ba931987f8d1.png)
 
![Guru-MapEditor 2022-06-16 15-33-30-54](https://user-images.githubusercontent.com/35990507/174081693-132e66e2-0cdc-4d76-a38c-5e5672be93fb.png)

![Guru-MapEditor 2022-06-16 15-33-27-00](https://user-images.githubusercontent.com/35990507/174081663-d7e7ee31-7a52-4c5b-9de5-4149f0a160ef.png)

**Comment by Duchenkuke** [comment]
the shadows are there, but not all sides of the grass are actually "in the shadow" The sunlight still applies to some of the shadows.

**Comment by Duchenkuke** [comment]
[grasstest.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8919314/grasstest.zip)

and this is the map file

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Bug was due to some shadow improvements on non-grass entities and leaked into the veg system which is much simpler. Fixed for the next update:

![image](https://user-images.githubusercontent.com/35840583/194891547-bea8a231-b202-4b28-bba4-0f8712d277ff.png)

**Comment by Duchenkuke** [comment]
This is awesome. Thanks very much!

So what file has been edited to fix this? I would need that file to fix the standalone game as well.
Please Lee, let me know, thanks!

**Comment by Duchenkuke** [comment]
you are the best... this helps A LOT  ! Thank you!!
