### ISSUE TITLE
Garbo Chess level is a little bland

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#17]
The level file called Garbo Chess.fpm in mapbank has a good chess game, but the surrounding level is flat and uninteresting. It would be good if the level was decorated with stock assets to look more interesting for a new user.

**Comment by Belidos3D** [comment]
Garbo Chess? That's not a TGC default map, that's a map done by AmenMoses to demonstrate his scripting using a 3rd party chess code, as far as i know it shouldn't be there unless you downloaded it from the forum.
