### ISSUE TITLE
GameGuru Max: ISSUE - Weapon Holding

### ISSUE THREAD

**Issue by ReeceDreavyn** [TheGameCreators/GameGuruRepo#1700]
Some of the characters appear to really struggle to hold a weapon correctly.
![Screenshot (94)](https://user-images.githubusercontent.com/96688257/147428354-da680d00-9c2a-4476-a7e0-6c98335c4a45.png)

**Comment by ReeceDreavyn** [comment]
I have triple-checked, it's all of them and they also aren't shooting at you until you are at point-blank range.

**Comment by ZakJudges** [comment]
Hi @ReeceDreavyn, apologies for the late response! This issue should have been fixed some time ago
