### ISSUE TITLE
GGMAX - Spotlight Radius is not saved when saving

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1701]
Hello,

The "**Spotlight Radius**" setting is not saved when saving (_for directional lights_). After saving, if I close GGM and reopen my project, this parameter returns to its default setting. This is very problematic, because it generates significant lighting problems.

**Comment by plemsoft** [comment]
@UltraVox001 We fixed this in another issue thanks :)
