### ISSUE TITLE
GGMAX - The "Tree Water Distance" function in Developer Mode cannot be saved.

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1702]
The "**Tree Water Distance**" function in Developer Mode cannot be saved.
The trees reappear near the water despite the saving.

Screenshot before saving :
![ScreenshotBeforeSaving](https://user-images.githubusercontent.com/96718175/147449595-ce511c2e-07e3-4432-8944-95bdeac12d8e.jpg)

Screenshot after saving :
![ScreenshotAfterSavingAndReopenMap](https://user-images.githubusercontent.com/96718175/147449614-7b89c8e1-535a-496e-98a8-7ccacca4c846.jpg)

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue, tree water distance is now saved in the latest build :)
