### ISSUE TITLE
GGMax Issue when adding lights: CRASH

### ISSUE THREAD

**Issue by ReeceDreavyn** [TheGameCreators/GameGuruRepo#1704]
When adding a light source to a scene, I am met with Runtime Error 7023 (pictured below) which then causes GG Max to crash and close instantly. To note, it was working fine last night and was working until I booted up my machine for the first time this morning. I have restarted my machine to try and eliminate the problem but no luck.
![Screenshot (95)](https://user-images.githubusercontent.com/96688257/147502017-125b96d0-1f55-47e4-a163-b6ce8ef9c993.png)

**Comment by ZakJudges** [comment]
Hi @ReeceDreavyn Apologies for the late response. This should have been a while ago, but if you continue to experience the issue it would be worth verifying your files on Steam, as it is very likely a problem with a missing file
