### ISSUE TITLE
Lighting stops working properly when you get closer GGMax

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#1706]
At the moment when I am at at distance, the lighting works beautifully but when I get close it seems to break. example attached, same light at different distances
![Screenshot 2021-12-28 072519](https://user-images.githubusercontent.com/95527550/147505123-98eb87a6-b776-4898-acb2-077420c2ec85.png)
![Screenshot 2021-12-28 072452](https://user-images.githubusercontent.com/95527550/147505125-69b35686-c705-4a9f-8d03-f6b56fd0fd55.png)
.

**Comment by UltraVox001** [comment]
I have the same problem as you. Almost all the lights are malfunctioning. Shadows are generated when you get close enough to the light. One step back and the shadows disappear. There are also lights that go through the walls of the houses. Modifying the "Light Probe Scale" or activating (or not) the "Cast Shadow" does not change this problem. I tried changing the Shadow value of "Point Lights" from 1024 to 2048, but my graphics card didn't like it. While waiting for a solution...

**Comment by ArgentArts** [comment]
Yep. This is an old one. I report this here:

https://github.com/TheGameCreators/GameGuruRepo/issues/1572

They know about it, but don't seem to be that interested in doing anything about it ... yet ...

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Since this report, we may have fixed this and improved the shadow light count properties too, please confirm now fixed and we can close this one:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/88399e13-8075-49cb-b71d-88146596d0df)
