### ISSUE TITLE
GGMAX - The "Light Shafts" function cannot be saved.

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1707]
This parameter has no adjustment, but it sometimes provides unwanted effects of too thick "trail of light". I turned it off to get a cleaner result. After saving the map, I reopen GGM, the function box is unchecked but the parameter is active! You have to check the box again and uncheck it again to deactivate the "Light Shafts".

Screenshot (very bad effect) :
![SUN](https://user-images.githubusercontent.com/96718175/147534536-96a625e7-116e-4221-a545-4c78736f3733.jpg).

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue, light shaft is now saved with the level , but the problem in the above image was the fog bug that we fixed earlier , thanks for your help :)

**Comment by UltraVox001** [comment]
@plemsoft 
After disabling Light Shats in the editor and saving the map. I reopen and the Light Shats box is disabled, but the rendering of Light Shats is still active.
![LS-Off](https://user-images.githubusercontent.com/96718175/155508057-8a022c68-4361-4359-bcbe-9bbedfcd0f4d.jpg)
![LS-Off-but-On](https://user-images.githubusercontent.com/96718175/155508064-45834a76-0708-49a5-a312-a877c0b47914.jpg)

**Comment by plemsoft** [comment]
@UltraVox001 My bad , did not test that , this has been fixed for the next update , thanks for your help :)
