### ISSUE TITLE
GGMax - Structure Editor bugs - unusable

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1709]
Hi,
For the past few weeks I have been unable to use Structure Editor. There are graphical bugs and placement bugs.

1/ I only have access to 5 x 5 boxes, instead of 10 x 10.
2/ There is a very important graphic shift between the pointer of my mouse and the pre-selection of GGMax.
3/ If I click once outside the structure being designed, it is impossible for me to re-edit the structure, which forces me to abandon it.

Take a look at this screenshot :
![EBE](https://user-images.githubusercontent.com/96718175/147574251-fccf5e53-d28a-4602-b510-ecf623d8b6a6.png)
The red area you see in the screenshot is the area I can use.
The other boxes are inaccessible. When I click on it, nothing happens.

Here a short video when I use it :
https://i.gyazo.com/1d8b4116b16cdf248101fec3cd8fa518.mp4

I have uninstalled GGMax several times and then reinstalled. Always the same problem.
I even changed my hard drive, and also reinstalled Windows 10 in the meantime. Always the same problem.

Are these bugs known to other users ?

Thanks.

**Comment by Kitakazi** [comment]
Yea they don't have plans to mess with the structure editor anytime soon I believe. That's why it was hidden under developer options in the first place.

**Comment by UltraVox001** [comment]
Kitakazi : you confirm you have the same problem?
Is it from me or is it for everyone?
I wonder how Lee was able to make a test map with that...

**Comment by Kitakazi** [comment]
Yea it hasn't worked for me in months. It worked to some degree when Max
was brand new.

If you need an EBE structure you can make it in classic then just import it
into Max tho.

**Comment by UltraVox001** [comment]
Thank you for your reply.

In one of these latest videos (the second to last, I think) Lee says EBE works and can be used. Sometimes I have the impression that he does not use the same tools as the community...

**Comment by synchromesh62** [comment]
The cellar was made a long time ago when the EBE did function
Since then so much has changed with \ terrain \ Key controls \ Camera Dragging \ etc i doubt Lee has even used it since and just assumes it still works. It was hidden away in Developer mode as the intention was or is to overhaul it so i doubt it will be on any needs to be fixed list at the moment.
