### ISSUE TITLE
No button save character creator

### ISSUE THREAD

**Issue by arubiobote** [TheGameCreators/GameGuruRepo#171]
In character creator, the weapon choice button and the save character button have disappeared. In the last preview if both appeared
<img width="960" alt="gamegurucharactercreator" src="https://user-images.githubusercontent.com/15078001/38890586-211db576-4282-11e8-8347-2f0e5701aebd.png">

**Comment by LeeBamberTGC** [comment]
Just launched a fresh GameGuru, went to FILE menu and Character Creator, and saw this. Can you do the same, thanks.
![image](https://user-images.githubusercontent.com/35840583/38894106-3dbfef6c-4284-11e8-84a3-281b41dea3c0.png)

**Comment by LeeBamberTGC** [comment]
P.S> Ensure you have Restricted Content Mode OFF (HELP menu, toggle restricted content mode and use code 9119).

**Comment by arubiobote** [comment]
Once the restricted content mode with code 9119 is activated, the rest of the buttons appear, although I have just seen the problem that the save button does not appear. But if you see in the image that I attached, it seems that the problem is due to the configuration of the screen that does not allow to correctly select the weapon to use and the button that should be lower than to save by this screen configuration is not shown .

<img width="960" alt="gamegurucharactercreator2" src="https://user-images.githubusercontent.com/15078001/38895100-6536c3da-428f-11e8-959c-55312d3a5006.png">

I'm going to try to change this configuration (although with Steam it is Steam itself that launches the screen size of the system) and see if it can be corrected to inform it in case someone else is going through it.

Many thanks Lee

**Comment by arubiobote** [comment]
Ok Lee. Fixed up. The initial problem was that of Toggle Restricted Content, with this it is fixed.

In my case, if it happens to more people, with windows 10 it was configured 150% of the font size that is recommended, by lowering it to 125% and the buttons appear that were not seen as seen in the annexes themselves It happens to more people.

<img width="960" alt="gamegurucharactercreator3" src="https://user-images.githubusercontent.com/15078001/38895413-4b879350-4290-11e8-820d-4affdd5630fe.png">

<img width="601" alt="gamegurucharactercreator-configscreen" src="https://user-images.githubusercontent.com/15078001/38895430-54254188-4290-11e8-81b9-b970bb030187.png">

Thank you very much

**Comment by LeeBamberTGC** [comment]
Thanks again, I have added your advice to the GameGuru Wiki:
https://github.com/TheGameCreators/GameGuruRepo/wiki/The-Documentation-Of-GameGuru

**Comment by LeeBamberTGC** [comment]
Ensure that your native resolution is large enough when using a large scale percentage with GameGuru, closing this one.
