### ISSUE TITLE
cloud 9

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1714]
when saving, clouds reset to the defualt settting and some objects move out of  place. 

![image](https://user-images.githubusercontent.com/68471279/147787728-88193d26-d31d-4ba9-b566-af9a082d0af2.png)

**Comment by UltraVox001** [comment]
It's true. But try to save your map using "Save As", rather than "Save". There are Developer Mode settings that cannot be saved with "Save", but would work with "Save As". I do not know why. And I also have objects that sometimes move. They fall under the map while they are all LOCK.

**Comment by casigus** [comment]
aye!!!! THANKS ULTRA :)
