### ISSUE TITLE
GGMax Bug Report - The sound of footsteps is rarer on the descent

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1718]
It has been several times since I noticed it but I forgot to mention it.
Maybe someone else has already done it.

The sound of my footsteps is twice as rare on the descent. On the flat and uphill, all is well. But when descending the footsteps seem twice as far apart. It's even more noticeable when I run downhill.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Fixed moons ago with improved terrain material detection and proper footfall system
