### ISSUE TITLE
Report by Wep : No collision on entity with melee hammer

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#172]
You can also use the melee hammer to find the spots by hitting the walls on Concrete Bunker (3).

**Comment by LeeBamberTGC** [comment]
Fixed for next update, thanks for the video, really helps!!

**Comment by korodai** [comment]
Thank you for fixing this. Can you add the Position Light command to the next update also?

**Comment by korodai** [comment]
Well, this isn't fixed after all.
