### ISSUE TITLE
Max particle problems using old system

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#1724]
Using the the old particle system in Max will still go to the smoke particle after a few times.
https://youtu.be/WoWaBdST-UQ

**Comment by AmenMoses** [comment]
On exiting test mode GG/MAX doesn't clean up the particle asset, in particular the image sheets and emitters themselves.

There is a function to clear the assets but it doesn't appear to be called properly.

**Comment by rvanner** [comment]
Can you try it in the latest version released last night. There have been changes to the particle system

**Comment by bluemeenie195** [comment]
Seems to be working now.
I used about 12 barrel entities with the waterfall script and played the test game multiple times. It never went to smoke particle.
Thank you
