### ISSUE TITLE
The Q key is used for 2 different actions in the editor which causes problems. (Move Camera Up and Toggle Trees)

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1726]
Pressing Q to Move camera down will move the camera but also Toggles the trees on/off and vice versa. 

Personally I like having camera up and down on Q and E. 

It looks like both the V and T key take the user to Edit Terrain mode so maybe one of those keys could be used to toggle trees?

**Comment by UltraVox001** [comment]
The Q key disables trees in Developer Mode only.
Disable Dev Mode and this issue will be resolved.
Go to Edit -> Setting -> and uncheck "Display Terrain Debug Mode" box.
