### ISSUE TITLE
max looks for files in the wrong directory

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#1727]
Loading a max saved map, outside of the normal directory, it tries to read and look for a entity in the classic folder instead of the correct directory the files should be in the max directory.
![runtime error 105](https://user-images.githubusercontent.com/82841733/148271801-652896ec-1117-49a5-a482-a31bd8d83d77.jpg)

**Comment by synchromesh62** [comment]
Why have you got Max installed in your Steam GameGuru Path ?
Thats probably the problem.

**Comment by UltraVox001** [comment]
Have you checked if the "Save Game Folder Location" option is checked, in Edit -> Setting -> Advanced ?

**Comment by wizardofid29** [comment]
sorry didn't update the name correctly. At first I thought the map was
deleted but was saved in another directory, as such it looked for
files in that directory structure instead of gameguru max directory

**Comment by LeeBamberTGC** [comment]
@wizardofid29 Lots of improvements to the writables system since this was posted, can you reproduce in the latest EXP build?
