### ISSUE TITLE
GGMAX - Request

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1729]
Can we have a terrain hole non collision zone to make entrances to a caves/underground base level models so you cna transition from one to another- most important. This allows us to make caves or bases in other apps to place underneath/through the terrain.

**Comment by Necrym59** [comment]
Secondlly There is no need for the EBE i feel you could concentrate on MAX and release another DLC tool for editing indoor areas. You could source a free tool such as GZBoom builder which the source can be modified to suit as the editor, it exports perfectly to OBJ format with all textures ready to import into MAX

**Comment by UltraVox001** [comment]
You are right to ask!

Personally, I would have preferred a terrain generator using Voxel technology. This would have allowed us to create hundreds of caves in the mountains (dig into them with the mouse), without having to use any external application (tedious and slow).

When we are looking to create realistic biomes, we have to find the only way to get it.
Voxel Dig : https://youtu.be/GKW0tLHPFCA?t=336

PS : I haven't used GZBoom Builder for a long time, but it's true that it would be much more efficient than an EBE. :)
