### ISSUE TITLE
Can't fill in Terrain with any terrain tool if the area has been Auto-Flattened. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1731]
See video: https://youtu.be/3cXz71-z1SE

Additionally picking the other terrain sculpting tool does not work either.

**Comment by UltraVox001** [comment]
This new option should not arrive until tomorrow. How did you get it ? In addition, it is completely unnecessary. And what do you do in Developer Mode for such a simple operation ? Go to Edit -> Settings -> Developer, and uncheck the "Display terrain Debug Mode" option, then try to modify your terrain again.

**Comment by Kitakazi** [comment]
I'm an internal tester.

**Comment by Granada1** [comment]
( Can't fill in Terrain with any terrain tool if the area has been Auto-Flattened. )
Once it has been flattened it’s locked 👍

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed the bug in the latest build so you can drag multiple objects around and auto flatten will apply and update. YOu will not be able to edit any area currently under the autoflatten area as it is a complete override. You can edit just outside the area however, and when the feather blend is in, you can edit my modulation more as you leave the edge of the protected area.
