### ISSUE TITLE
Can't install GameguruMAX Alpha

### ISSUE THREAD

**Issue by joeydono** [TheGameCreators/GameGuruRepo#1732]
Hi, I logged into gameguru, downloaded tiny installer and installed it. I ran it, it say its missing files and wants to download files. I checked to download core files only and this keeps coming. Up(see pic)

![Screenshot (39)](https://user-images.githubusercontent.com/7487882/148429177-21c6fdd6-ef9a-4f38-9b3d-fe3a383e8c00.png)

**Comment by rvanner** [comment]
Is this fixed for you now? I think I emailed you as to how to fix it.

* We suggest you delete the hidden temp files and try running the tiny installer from scratch again. These files will be found here; C:\Users\<theirname>\AppData\Local\AGKApps\TheGameCreators\GameGuruMAXUpdater
* Also delete any other folder in this folder that starts with "GameGuruMAX"

**Comment by joeydono** [comment]
Any thoughts?

________________________________

**Comment by rvanner** [comment]
@ZakJudges Can you please respond to @joeydono today with some advice?

**Comment by joeydono** [comment]
I just got it sorted, went. To updates in about, and found it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
