### ISSUE TITLE
GG Classic Issue: Debug Text on Zombies

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#1733]
There seems to be debug text left over on zombies. 

![debugtext](https://user-images.githubusercontent.com/35990109/148504311-eefbcb17-fcac-41fe-8e10-04280c02fc22.jpg)
![debug2](https://user-images.githubusercontent.com/35990109/148504465-83e6ffda-acc6-4a28-b804-cea739756638.jpg)

**Comment by LeeBamberTGC** [comment]
@Teabone3 Fixed for next Classic beta
