### ISSUE TITLE
Nodes not working in latest build.

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#1735]
Hi. as describe in this video https://youtu.be/g7bjisz7L8c at 7:10 in the video you explain about the shooter connections that comes available once the scooter function is selected. well I tried it in this latest build of Friday 07/01/20222 and I don't see those functions, are they disabled or are they just not working for some reason like a bug or are these functions only working for one week after the release until the new features are added the next week Friday or what?

**Comment by ZakJudges** [comment]
Apologies for the late response. The icons that became available after pressing the Shooter Games button were removed some time ago. Now, after pressing the Shooter Games button, you can click on an object and drag to create a connection. The functionalities of the buttons are throughout the software, and you don't need to click the Shooter Games button to use them
