### ISSUE TITLE
MAX - Physics holes in terrain in latest build.

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#1736]
It seems like the greedy mesh algorithm (or whatever method Lee used to optimize the terrain physics polycount) sometimes leaves holes in the terrain. When generating a level and running around it, occasionally you'll just fall through the floor and into the void, where you'll quickly start drowning from being underwater. It's hard to reliably spot/find these holes without actively running through a level and finding them by falling into them.

**Comment by Retrogamebloke** [comment]
Found the same issue. Not only did I fall through the floor in places, the enemies did as well!

**Comment by fearlesswee** [comment]
From what I can tell this issue has been dealt with for a while, as when this issue was "active" you couldn't really run for more than a minute in any direction without eventually landing in a terrain gap, but now I can run all about a terrain for 20+ minutes without finding a single one.
