### ISSUE TITLE
GameGuru MAX - Bug - 1-7 Build - Initial Run Game on Empty Loads Trees/Grass

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#1737]
Did a fresh install of the latest build of GameGuru MAX (1 - 7 - 2022 build) and created a brand new EMPTY level. I added some tile models to test some pixelated materials and encountered an issue. Here's a screen shot of the simple level in MAX:

![empty](https://user-images.githubusercontent.com/36735507/148624363-3569f0a7-0a50-4535-9e35-e38e2f6fa27a.png)

After running it the very first time:

![not_empty](https://user-images.githubusercontent.com/36735507/148624371-5cc2482c-8496-4ef9-8fb9-b2d264a37d89.png)

As you can see, MAX added in grass and trees even though my empty level had no grass and trees. Neither trees nor vegetation were checked under View Options on the left panel, either. After exiting the game and running it the second time, the level ran fine (no trees and grass). Every time afterward, the level runs fine. However, if I exit GameGuru MAX, restart, and run the level for the first time, the trees and grass appear again.

What I think is going on is the first time I run the game MAX is not generating the nav mesh for the terrain and it is loading some previous data. I think it is pulling trees and grass from the default biom you get when you go to first create a level (before I chose EMTPY). When I exit the game and go to run it the second time, I get the bar at the top of the screen showing me that it is generating the new nav mesh. This is missing the first time I go to run the game.

**Comment by ArgentArts** [comment]
I was incorrect. I reran my test and found out what was going on. Even though I had an EMPTY level, when I first run MAX and load my level for the first time, it checks the bottom three here:

![checked](https://user-images.githubusercontent.com/36735507/148625212-9dd6a56a-1009-427b-b0b1-89998f5db38c.png)

This is why the trees and grass show up (even though I didn't put any in my empty level. But after I exit the level, it unchecks all three. MAX should not be checking and unchecking boxes on its own, though.

**Comment by Retrogamebloke** [comment]
I have had this issue as well. Loaded my interior map and presto grass and trees! Checked the new settings after and they were unchecked. Unfortunately didn't run it again straight away, rebooted and reloaded. After that it was back to normal although defo a bit slower than before. When the trees and grass were in it actually seemed to run better!
![image](https://user-images.githubusercontent.com/44620846/148632776-d90bda40-3f10-4d35-a697-ea55a636a16a.png)

**Comment by Kitakazi** [comment]
I'd like to add I have an empty level as well that I noticed although no trees or grass are on the empty terrain if I enable 'Display Terrain Debug Mode' and press Q to show trees, it will show a TON of trees on my level that I did not place and should not be there.

**Comment by ArgentArts** [comment]
It is not. This can be closed.

**Comment by ZakJudges** [comment]
Thank you for confirming :)
