### ISSUE TITLE
[Max] Missing Media.txt  in mapbank is showing media that was never in my level. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1738]
I deleted a folder from my entitybank on accident, I figured I didnt really need it anyway so I went to look at my Missing Media text file to see what exactly I would be missing and what I had been using on my FPM. I knew the list would be small so I was surprised to see this. 

MISSING MEDIA:
entitybank\BoltActionGaming\noir\PBR\Cybernoir Car 1 Black.fpe=replaceentitybank\BoltActionGaming\noir\PBR\Cybernoir Car 1 Black.fpe
entitybank\BoltActionGaming\noir\PBR\Cybernoir Car 1 Maroon.fpe=replaceentitybank\BoltActionGaming\noir\PBR\Cybernoir Car 1 Maroon.fpe
entitybank\BoltActionGaming\noir\PBR\Cybernoir Car 1 Silver.fpe=replaceentitybank\BoltActionGaming\noir\PBR\Cybernoir Car 1 Silver.fpe
entitybank\BoltActionGaming\noir\PBR\Cybernoir Truck 1 Cargo.fpe=replaceentitybank\BoltActionGaming\noir\PBR\Cybernoir Truck 1 Cargo.fpe
entitybank\BoltActionGaming\noir\PBR\Cybernoir Truck 1 Dark.fpe=replaceentitybank\BoltActionGaming\noir\PBR\Cybernoir Truck 1 Dark.fpe
entitybank\BoltActionGaming\noir\PBR\Cybernoir Truck 1 Light.fpe=replaceentitybank\BoltActionGaming\noir\PBR\Cybernoir Truck 1 Light.fpe
entitybank\BoltActionGaming\noir\Building 1.fpe=replaceentitybank\BoltActionGaming\noir\Building 1.fpe
entitybank\BoltActionGaming\noir\Building LOD 1.fpe=replaceentitybank\BoltActionGaming\noir\Building LOD 1.fpe
entitybank\BoltActionGaming\noir\Building LOD 2.fpe=replaceentitybank\BoltActionGaming\noir\Building LOD 2.fpe
entitybank\BoltActionGaming\noir\Building LOD 3.fpe=replaceentitybank\BoltActionGaming\noir\Building LOD 3.fpe
entitybank\BoltActionGaming\noir\Can 1.fpe=replaceentitybank\BoltActionGaming\noir\Can 1.fpe
entitybank\BoltActionGaming\noir\Can 2.fpe=replaceentitybank\BoltActionGaming\noir\Can 2.fpe
entitybank\BoltActionGaming\noir\Can 3.fpe=replaceentitybank\BoltActionGaming\noir\Can 3.fpe
entitybank\BoltActionGaming\noir\Can 4.fpe=replaceentitybank\BoltActionGaming\noir\Can 4.fpe
entitybank\BoltActionGaming\noir\Digital Interface Device.fpe=replaceentitybank\BoltActionGaming\noir\Digital Interface Device.fpe
entitybank\BoltActionGaming\noir\Electrical Box.fpe=replaceentitybank\BoltActionGaming\noir\Electrical Box.fpe
entitybank\BoltActionGaming\noir\Flying Car.fpe=replaceentitybank\BoltActionGaming\noir\Flying Car.fpe
entitybank\BoltActionGaming\noir\Noodle Bowl.fpe=replaceentitybank\BoltActionGaming\noir\Noodle Bowl.fpe
entitybank\BoltActionGaming\noir\Outdoor Table.fpe=replaceentitybank\BoltActionGaming\noir\Outdoor Table.fpe
entitybank\BoltActionGaming\noir\Picture 1.fpe=replaceentitybank\BoltActionGaming\noir\Picture 1.fpe
entitybank\BoltActionGaming\noir\PBR\Cybernoir Car 1 Black.fpe=replaceentitybank\BoltActionGaming\noir\PBR\Cybernoir Car 1 Black.fpe
entitybank\BoltActionGaming\noir\Picture 2.fpe=replaceentitybank\BoltActionGaming\noir\Picture 2.fpe
entitybank\BoltActionGaming\noir\Sign 1.fpe=replaceentitybank\BoltActionGaming\noir\Sign 1.fpe
entitybank\BoltActionGaming\noir\Sign 2.fpe=replaceentitybank\BoltActionGaming\noir\Sign 2.fpe
entitybank\BoltActionGaming\noir\Sign 3.fpe=replaceentitybank\BoltActionGaming\noir\Sign 3.fpe
entitybank\BoltActionGaming\noir\Street Pillar 1.fpe=replaceentitybank\BoltActionGaming\noir\Street Pillar 1.fpe

---

I am 100% sure the only entities that it should actually show from that entire list were
entitybank\BoltActionGaming\noir\Electrical Box.fpe=replaceentitybank\BoltActionGaming\noir\Electrical Box.fpe
entitybank\BoltActionGaming\noir\Noodle Bowl.fpe=replaceentitybank\BoltActionGaming\noir\Noodle Bowl.fpe
entitybank\BoltActionGaming\noir\Picture 1.fpe=replaceentitybank\BoltActionGaming\noir\Picture 1.fpe

That is it. No idea why it thinks those other assets were in my scene because they were/are not.

**Comment by Retrogamebloke** [comment]
This could explain a lot of issues. Slow load speeds and in game performance ones. I've felt for awhile saving and loading are insanely slow. Also why fresh new maps run fairly well compared to older maps running like they are in glue.

**Comment by Kitakazi** [comment]
I guess I will close this. If this happens again I will reopen.
