### ISSUE TITLE
Save and Load Speed is Intolerable!

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1739]
Been having this issue for several weeks at least now. Loading an existing map takes an age. It gets worse the longer you edit and tweak the level. I have simply quit in disgust a few times now and it really puts me off using Max at all. Something is not right, Unreal is faster than this even when it's compiling shaders and baking light maps! At least that is often a one off process, in Max it's every time you load or save!

https://user-images.githubusercontent.com/44620846/148632958-9dc5764f-45b8-4cd8-96c1-b7324ffb5964.mp4

Oh system specs are Ryzen 1700 8 core CPU (first gen Ryzen). 32 gig of DDR5 ram. Geforce 970GTX. 1TB SSD plus 2TB normal drive. Max is installed on the normal drive, but data is all on SSD. If that helps :)

**Comment by Kitakazi** [comment]
I have same issues, trying to open an FPM is brutal. Same with attempting to launch testgame. 
Trying to open/testgame an FPM with alot of entities in nearly impossible atm.
