### ISSUE TITLE
Flashlight on terrain not showing

### ISSUE THREAD

**Issue by corrosionsting** [TheGameCreators/GameGuruRepo#174]
Sometimes the flashlight works on terrain, and sometimes it doesn't.

**Comment by corrosionsting** [comment]
This is directly related to lightrays.

**Comment by Pirate-Myke** [comment]
It seems when you first start test game on a fresh map and press test game. When the game starts and you turn on the flash light, the lightray slider does dim it down as the slider increases.

I changed the terrain and sky box and turned my terrain shader to highest and it would not do this again this session.

Restarting Game Guru and repeating this to see if it is just a one time fluke per session or not.

**Comment by corrosionsting** [comment]
This definitely has something to do with lightrays.

**Comment by corrosionsting** [comment]
To go with this, maps that are affected, shooting a gun causes the terrain to flash white rapidly

**Comment by LeeBamberTGC** [comment]
Does this still happen with the latest monster update and the new dynamic lighting system?

**Comment by plemsoft** [comment]
@LeeBamberTGC As i remember i fixed the flashlight issue in the monster release , so i assume this is fixed @corrosionsting Let me know if this is not the case , until then i will mark it as fixed.
