### ISSUE TITLE
Zombie Attacks still Broken

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1740]
This is not a new issue, but I am sick of seeing it, so reporting now. Every time a zombie grabs you, you lose your weapons after it lets go. This is useless and if on purpose, a rubbish game mechanic. Having to re-equip a weapon mid scramble is awful.

I have also noticed a serious flickering of said zombie anims after you have escaped. Flickering on and off on screen. Can't say for the latest version 07/01/22 but for all versions up to that, it is there.

Zombies still start attacking empty air if you trigger them and run off. Not only is this not good to look at, it also causes issues with allies, who when shooting said zombie from miles away, gets hurt by the zombies attacks when all they are attacking is empty space. Note here, we need some control over this. Had a level where you are supposed to rescue an ally. Not only did said ally run through the wall before I could free them, they also attacked zombies behind bars that in real life no-one would bother with. Combined with them taking damage from distance made my idea pretty useless. Plus the ally ran though walls at will. Given up on that particular idea for the moment.

**Comment by fearlesswee** [comment]
To build onto this bug, it's possible to be grabbed by two zombies at once, and you'll flicker rapidly back and forth between them, you can also be "freed" from one zombie and freely walk around while flickering back near the other zombie.

This is also personal preference, but the zombie grabbing onto you for EVERY attack is annoying, and it's extremely annoying how it cannot be avoided. I believe instead the zombie should mostly try attacking with his claws, but will only sometimes lunge forward, which if you get hit by it will go into the bite animation, but if you dodge out of the way in time he will instead be open for attack.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke @fearlesswee Going through the issues here: in latest EXP build

* Weapon now returns after being brain fed to quicken game play involving Zombies
* No more flickering in Zombie animations during short, medium and brain-eating attacks
* Brain feeding much reduced now, had to die three times before one of my pair of Z1 zombies brain fed
* The zombie air attack is deliberate, they start the attack, but the player has a chance to move out of the way. If they do not, and the player is still within effective atack range, the player will get hit
* Only one zombie can brain feed on the player now, the others can continue short range attacks if they feel like it
* Added a new property so you can switch off the brain feed attack from a Zombie:
![image](https://user-images.githubusercontent.com/35840583/230783209-83b75350-0991-4f27-ac7b-658abb96a6aa.png)

For the characters running through walls, can you report this separately as I have not need this issue for some time now.

**Comment by Kasseyus** [comment]
@LeeBamberTGC There seems to be an issue where the Zombie's Bite Attack results in graphical artefacts during the attack.  It may be related to the above issue.  This can be seen by placing a character creator zombie in an empty world and letting it chomp on you.  I get the issue 100% of the time.

**Comment by LeeBamberTGC** [comment]
@Kasseyus Fxied for sure in next DEVTEST build ensuring camera no longer flickers when in brain feed mode!

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke  Fxied for sure in next DEVTEST build ensuring camera no longer flickers when in brain feed mode!
