### ISSUE TITLE
GG Max Bug Report - Terrain creation bug (Rainforest)

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1741]
Hi,

I am using the very latest EA version of Max.

When creating a new map, I am in the Rainforest biomes (default). I haven't touched any terrain option yet, but I see in front of the camera (near the yellow point on the right), a terrain bug. A square of terrain very raised. All around, no trees in a large area. The vegetation is there, on the ground, but not the trees. Strange.

![BugTerrainGen](https://user-images.githubusercontent.com/96718175/148644752-09948c76-92ac-4064-a662-8fb2d579e3e8.jpg)

I specify that I let Max do and that I did not touch any setting. What you see on the screen is what I discover when I arrive on the map, from the first second.

After creating the terrain, this bug is still there, on the map. I can drop trees on the square structure, but I cannot modify or delete this square structure.

![BugTerrainGen2](https://user-images.githubusercontent.com/96718175/148645172-4ea07ab1-0fde-4904-bb37-e21385e55efd.jpg)

Hope this can help.

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by UltraVox001** [comment]
Ok thank you very much. :)
