### ISSUE TITLE
biomes Terrain Bug

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#1742]
Hi Lee 

I have two problems with the terrain biomes as you can see from the pictures below
![Floating grass](https://user-images.githubusercontent.com/93008801/148653960-570ba90c-43cb-47f1-83e1-f2ec815c5f04.jpg)
![falling out of scene](https://user-images.githubusercontent.com/93008801/148653967-17ec8086-61b4-4b90-87ad-f82d2ac6d421.jpg)
As you can see the grass is floating in the air and not level with the land mass and the second picture shows you falling out of the scene after moving a little distance from where you started.

This seems to happen on all of the biomes after updating to the new update. I can't even use height maps as it does the same thing

I was wondering if anyone else has had this problem.

Many Thanks
Tam51

**Comment by UltraVox001** [comment]
Go to "Add vegetation", click on Clear, then on Populate.
The same goes for tree bugs.

Yes, the problem of "holes" in the map has already been reported. :)

**Comment by LeeBamberTGC** [comment]
@Tam51 Is this fixed in latest bui;ld?

**Comment by rvanner** [comment]
Closing this now. No reply from user and not seen this since.
