### ISSUE TITLE
Stand alone issues.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1744]
Stand alone issues.

Decided to test the stand alone functionality of Ggmax, there are some problems (no doubt will be fixed in future updates) but just in case thought I would report my findings thus far.

Loading times are really bad, even on a SSD. Managed to stand up, go for a walk, make a brew, and open a word processing document to start typing this up as I wait!

When you save a game and reload, max will cut all the audio, meaning if you saved with a ambient track playing, it won’t be playing after a reload, so if your shot, you die, you re-load, everyhings dead. 

When reloading, all the triggers where turned off, as was the behaviour of any characters. It did reset when saved again however! 

Having the “lives” system is very dated, modern fps don’t tend to have lives, and its good to see thats no longer there, but that has created the problem of if you die, its instant game over, back to the title screen. Imagine, a game with 5 levels, and you die on level 5, BOOM back to the menu, and with the loading saving system unable to function, its problematic! 

Whats needed is a autosave at check points and just after a levels loaded so upon death the respawning happens at those points.

Not entirely sure whats going on with the menu’s HOWEVER clicking the load game brings up the sound menu, saving brings up graphics, even with the correct connections in the project screen!

The image trigger is great, I LOVE the 3d effect of it in game HOWEVER it causes some serious lag. The ravens are dead (ironic) rip, they no longer function. Video triggers work perfect, as does sound and 3d sound ! 

Weather decals are broken, snow/rain appearing oddly! (but I believe from one of the wednesday broadcasts its something being worked on) 

Some objects models cause the fps to drop to 1-5, if your facing the direction of that model/entity everything moves in slow motion and after testing and testing different models, I’ve yet to find a cause, maybe its a texture issue? A shadow issue? A polygon issue?

Doors have been frustrating, esp linking them to a switch or key. Half the time the just don’t work, either the door and key aren’t talking to each other or the door opens and the shape of the door (ggmax doors) wont let you through as if the shape has changed) 

Objects randomly deleting them selves. Experienced this a few times where I’d have a object (record player in this case) playing music with a 3d sound script, and it would just disapear with out explanation.

No foot sounds, never had foot sounds (snow/grass ect) just the generic classic sound. 

Running max and stand alone is a process killer. Everything running on my pc dies, including web browsers. So I’ll be there on max with youtube or twitch open, and Max just eats everything up.

When it works, it works wonderfully, there are some fantastic new features I’m loving and I take my hat off too the team. I don’t want this to come across as a dig, its a result of my testing and I have every faith that with every update we get, these things will be fixed. Wish I had the tech no how to help! 

What concerns me is that a lot of these issues occurred in classic, back last year when was using it, ESP with the loading and saving side of things!

That’s all for Now. I’ll keep poking and prodding around!

Happy Monday folks. 

![image](https://user-images.githubusercontent.com/68471279/148714352-8a61842d-5613-4a77-bcfb-b082d9ba8bcd.png)

**Comment by plemsoft** [comment]
@casigus We have optimized load times and memory use , could you let me know if this is fixed for you in the latest build, Thanks :)

**Comment by casigus** [comment]
things are alot better for sure.
