### ISSUE TITLE
GGMAX: install errors regardless of rolling back and re-installs

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1746]
I get this error in the error_install.txt file 5,559 times:
HTTP download failed for file "", HTTP status: 200, Internal Error: "Could not find file raw:C:/GameGuruMAX/"

I have tried to roll back several times and re-install several times.  I have deleted the documents gameguru apps folder and cleaned up temp files etc.

**Comment by redagent101** [comment]
Other forum members have also had intall errors , but I can't comment what their log reads
Please can this be look into as I cannot install GGMAx at all now.

BOTR

**Comment by UltraVox001** [comment]
Have you tried to grab a new installer from your account on The Game Creators website ?
Did you try to install the program in administrator mode ?

**Comment by ZakJudges** [comment]
Hi @redagent101 
Does the issue persist when running "GameGuru MAX Updater.exe" as an administrator?
If so, what drive are you trying to install to? Thanks :)

**Comment by redagent101** [comment]
@UltraVox001 : Why, has a new  version of the tiny installer been uploaded?  if so, I will grab a new version.  If not, I will use the same version.  Have other users been informed of any new installer?
@ZakJudges :  Yes, all running under admin mode and I install to C:\GameGuruMax which I have always intalled to without issues.  it's only been the last 2 or 3 versions that have started causing this error. 

thanks BOTR (forum member)

**Comment by ZakJudges** [comment]
@redagent101 Thanks for the info. You could try installing to a different location. Failing that, you could temporarily disable any anti-virus software just whilst the updater runs, to see if that could be causing the issue.
In install_error.txt, is the only error "Could not find file raw:C:/GameGuruMAX/"? Or are there any other ones in there too?

**Comment by redagent101** [comment]
I don't have virus software running.  That's the only error in the error log but it repeats.  I will download the tiny installer again and retry using admin mode as usual.  if not, I will wait till the March release.

**Comment by UltraVox001** [comment]
No, I don't think a new version of this installer is available. I am considering that your executable may be damaged. But that would be strange. However, it doesn't cost a thing to try.

I'll let ZakJuges take care of your problem.

**Comment by redagent101** [comment]
still get same errors. its ok, I will try again in March when it gets officially released
BOTR (Bored Of The Rings) on the forums

**Comment by redagent101** [comment]
tried again, took forever and then:

HTTP download failed for file "Max/Files/skybank/sunset/sunset_cube.dds", HTTP status: 200, Internal Error: "None"
HTTP download failed for file "Max/Files/skybank/cloudy/cloudy_cube.dds", HTTP status: 200, Internal Error: "None"
HTTP download failed for file "Max/Files/mapbank/zombie cellar demo - level1.fpm", HTTP status: 200, Internal Error: "None"
HTTP download failed for file "Max/Files/tutorialbank/0201-level-editor.mp4", HTTP status: 200, Internal Error: "None"
HTTP download failed for file "Max/Files/tutorialbank/0201-level-editor.mp4", HTTP status: 200, Internal Error: "None"

**Comment by ZakJudges** [comment]
@redagent101 Are you now able to run MAX, albeit with the missing files that failed to download?

**Comment by redagent101** [comment]
I can confirm it runs even with the missing files that failed to download.  Any reason for that?

**Comment by redagent101** [comment]
I meant to mention that I only attempted to download the core files without all the media addtional files.  I'm going to try and see if I still get errors downloading all the additional media files.

**Comment by ZakJudges** [comment]
At a guess, its now a separate issue. In the original error code you received, the error was marked as internal. Whereas for the new error codes, the problem seems to be related to the downloading of the files. One thing I could suggest, if after verifying your files you get the same error, you could try searching in your MAX installation for the files generating the errors, then deleting them if you have them, and then verifying the files again.

**Comment by redagent101** [comment]
thanks for the tip, I will try that.

**Comment by redagent101** [comment]
ok, so it it seems I have to install all additional media files for the install to work without errors.  Something needs looking into here as this shouldn't happen.  

![GGMAX_install](https://user-images.githubusercontent.com/15969299/149150697-06cd3d10-49be-49bf-9863-5c99d56fd149.png)

**Comment by ZakJudges** [comment]
Hi @redagent101. In the latest build, are you still encountering errors when only some of the asset collections are ticked? :)

**Comment by redagent101** [comment]
issue still there I'm afraid.
![Untitled](https://user-images.githubusercontent.com/15969299/154755696-5210fe4c-a1bc-40f2-a4a1-a8e226066caa.png)

**Comment by redagent101** [comment]
[install_errors - Copy.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8101883/install_errors.-.Copy.txt)

**Comment by redagent101** [comment]
all seems ok now post files verification.
![GGMAX_post_verify_files](https://user-images.githubusercontent.com/15969299/154796937-87219679-ded7-46bf-b10c-0c72efac01a9.png)

**Comment by ZakJudges** [comment]
Hi @redagent101, thank you for letting me know. I'll close this issue now, but if it happens again feel free to reopen it :)
