### ISSUE TITLE
Frame rate can be massively reduced due to some CPU hog

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1747]
Here are two stats from the exact same level. It would seem the engine can run very slow some times and I have to reset to get my 60fps back.

![image](https://user-images.githubusercontent.com/1503593/148984131-4eb429ef-d474-44be-a886-fb64caa5de38.png)

**Comment by Retrogamebloke** [comment]
I haven't had above 30 on any map with a terrain for an age. Flat ones fare better but still can slow down badly on occasion. I had a super slowdown on an indoor map which looks to be caused by the ammo lying on the floor

https://user-images.githubusercontent.com/44620846/149146531-1609d295-04f7-4a06-9ba3-d55f5eb20915.mp4

.

**Comment by UltraVox001** [comment]
@Retrogamebloke

Suggestion :

1/ Remove the Behaviors from the weapon and/or ammo.
2/ Save the map.
3/ Close Max
4/ Reopen your map
5/ TestGame the map (without Behaviors)
6/ Recall the Behaviors for these objects
7/ Test and tell us.

**Comment by Retrogamebloke** [comment]
![fps_flat](https://user-images.githubusercontent.com/44620846/149907318-a936edd5-82bc-4fa3-890b-5761e5ac906a.jpg)
Flat map screenshot as requested.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke Can you tell me what resolution you are running at, thanks!

**Comment by Retrogamebloke** [comment]
![image](https://user-images.githubusercontent.com/44620846/149924792-0cc901db-c49e-46d4-8b0f-21f2913f7e73.png)
1920x1080

**Comment by Retrogamebloke** [comment]
The map above was made in an existing project I have been working on for the compo. A fresh project and flat map gives me 60 initially.
![image](https://user-images.githubusercontent.com/44620846/149926724-a1d5e11c-49ba-4301-941c-8463092314cc.png)
So not sure why the big fps difference on a fresh project.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke We are going to be doing some aggressive performance analysis in Feb, are you up for being a test subject using such tools as GPA and VTUNE?  Your graphics card and system seem fine, so it looks like some weirdness we need to track down. I think Rick sees this slowdown sometimes too, VERY hard to reproduce this one.

**Comment by Retrogamebloke** [comment]
I'll give em a go if I can.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke We are now in FEB, which means time to see where your performance is going.  Can you confirm you are still getting as CPU hog on a blank level in the latest internal build from this week, thanks!

@dllllllllllb Can you work with this to see if we can reproduce the slow down at our end using advice posted here.  Once we can reproduce the slow-down, we know where to apply the improvements.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I can't reproduce it. I made 5 levels, all use a different biome as base, all had objects in them, I play tested them all, went back to each of them and none have dropped frames for me. 

I also maxed out the movement speed and ran around the entire map to see if some things aren't unloading properly, but my FPS still didn't drop at all.

**Comment by LeeBamberTGC** [comment]
@rvanner Please close this one if this week's build has solved the performance issue. Preben added some object management stuff in Wicked which should really smooth out any performance spikes with continued MAX usage.

**Comment by rvanner** [comment]
Closing thanks to all the great optimisations made these past 2 weeks.
