### ISSUE TITLE
Lighting auto dims and brightens

### ISSUE THREAD

**Issue by ivanski1983** [TheGameCreators/GameGuruRepo#1749]
https://youtu.be/C02mPW7rLRw

Happens on simulated sky and sky box.

**Comment by UltraVox001** [comment]
This is perfectly normal.
Go to "Effect Environment", then to "Post Processing" and uncheck the "Auto Exposure" option.
Or keep it active, but set "Auto Exp Rate" to a slower setting.
This setting should be changed according to the map style (interior or exterior).

**Comment by ivanski1983** [comment]
Thanks for the info
