### ISSUE TITLE
GG Max Bug Report - Objects that disappear under the map

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1750]
Hi,

This problem is very recurrent. My map has been saved hundreds of times without encountering any problem. However, sometimes many 3D objects are found under the map. Here is a screen of what we should see :
![Kitchen1](https://user-images.githubusercontent.com/96718175/149107097-135a6a15-f274-4a98-8e1c-d428b56ece06.jpg)

Here is a screen of what Max gives me :
![Kitchen2](https://user-images.githubusercontent.com/96718175/149107207-6e0759e8-ca61-4653-afbe-4a8fd3ea25c6.jpg)

Fortunately, I make backups of my map several times a day. Because repairing this kitchen is tedious. Especially since there is also furniture from the upper floor which is found under the map. However, all these objects are in Static mode.

At this stage of Max's development, I suggest you consider this issue as a matter of urgency.
If I hadn't saved the map in the Game Project, I would have had a few hours of work to do again.

A Static object must not know how to change position.

Note that activating the "LOCK" function on all these objects does not change the problem.
Sometimes Max decides to put them under the map.

**Comment by Retrogamebloke** [comment]
The editor can be very annoying at times. The fact you can't drop under the map exacerbates this issue ten fold. As Ultravox says above unless you save often with every slight change you can end up losing a lot of work. the fact that it can take 5 to 10 mins+ to save and load means this is somewhat offputting.

**Comment by rvanner** [comment]
@UltraVox001 Is this still an issue for you?

**Comment by UltraVox001** [comment]
@rvanner 
I can close here. But allowing the camera to pass under the map (in Edit mode) would be a good thing.
