### ISSUE TITLE
GG Classic ignoring script.

### ISSUE THREAD

**Issue by MorttMedia** [TheGameCreators/GameGuruRepo#1753]
GG Classic does not read the default.lua script unless it is in a folder/directory in the scriptbank folder/directory. That mean every entity that uses the default.lua script will not work. This appears to be is a BUG and definitely  not a scripting issue. Reloaded GG classic after removing installed version and the problem is still the same.

**Comment by AmenMoses** [comment]
It is intentional as I explained before.

**Comment by Teabone3** [comment]
The default.lua script doesn't actually do anything and its not intended to. This is its contents:

```
function default_init(e)
end

function default_main(e)
end
```
