### ISSUE TITLE
When moving this character, it cuts into the terrain and it's position goes haywire

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1758]
https://youtu.be/QOyi16qTC3Y

**Comment by UltraVox001** [comment]
Yes. It is a problem that I encounter every day. Annoying! Some objects go very far (several kilometers). And when we use the Undo function to reconcile them, this function undoes another previous action, which doubles the work to be redone.

**Comment by rvanner** [comment]
@LeeBamberTGC This is still a problem in MAX.

**Comment by rvanner** [comment]
@LeeBamberTGC It's very easy to re-create. Just make a hill as seen in this video, have the camera at the same height as you see in the video and then move the character around;
https://youtu.be/S0Xv6qn-NEM

**Comment by LeeBamberTGC** [comment]
@rvanner With the next EXP build, check to see if I have fixed this one.

**Comment by rvanner** [comment]
@LeeBamberTGC Seems fixed! Nice one!
