### ISSUE TITLE
HIGH PRIORITY - Videos/Audio dont play together if under spawn

### ISSUE THREAD

**Issue by corrosionsting** [TheGameCreators/GameGuruRepo#176]
If a storyzone is placed under the player spawn (to play immediately upon the map starting) the video will play, without sound, and then the sound will play afterwards...

**Comment by ViperSmoke** [comment]
I have the same bug.

**Comment by corrosionsting** [comment]
yeah, this is annoying

**Comment by ViperSmoke** [comment]
Video ad esempio: https://www.youtube.com/watch?v=8bAR504gxo8&feature=youtu.be

**Comment by LeeBamberTGC** [comment]
You need to make sure the audio is in sync with the video stream. Since these media items where decoupled when we relegated DirectShow, the audio needs to be the right format. See videoaudio.ogg and video.ogv for recommended formats.
