### ISSUE TITLE
Objects judder when I try to move them with Snap Grid turned on.

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1760]
Video shows the issue;
https://youtu.be/4wKlReGQ0Fc

Don't ask for the level. I had a crash (placing trees) and lost it.

**Comment by UltraVox001** [comment]
I tried to reproduce this problem using the same 3D objects as you. The house (Warehouse brick) and the low wall (Walls - Stone Wall Style A), grouped by 6. I tried on an empty lot (without terrain, empty map), then with an auto generated terrain. Then with a ground retouched with the tools. And lastly, I tried a terrain retouched by the "auto flatten" function, when you put the house on the ground.

I have failed to reproduce the problem.
![snapmodebug](https://user-images.githubusercontent.com/96718175/149505113-01d0b321-e23c-452c-b325-2e701d73d634.jpg)
There is one thing that I noticed : when Max starts to make problems like this, it is better to save the map, close Max and reopen it. Often times it gets much better after being reopened.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 You made your wall group too straight :)  The bug shows itself when you create a not very well lined up wall as Rick did, and the issue relates to grouped objects trying to snap to each other.  Fixed for next internal build.
