### ISSUE TITLE
When rotating this group of objects, one of them does not rotate properly

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1761]
Video shows the issue;
https://youtu.be/ym2OiFgpuJI

**Comment by LeeBamberTGC** [comment]
@rvanner You had a similar report on this, but I still need to be able to reproduce it.  Can you create steps from scratch which shows how to assembled that wall and then made a group to rotate, it is the sequence that will reveal the bug and of course, the fix.

**Comment by rvanner** [comment]
@LeeBamberTGC Check out this video which should show you how to recreate this bug;
https://youtu.be/-YAN1hol6eY

**Comment by LeeBamberTGC** [comment]
Prevented user from rotating AND dragging at the same time, can still rotate when not dragging at the same time, and rotation works fine as either a group or multi-object selection from a cut-paste operation.
