### ISSUE TITLE
GG Max Bug Report - Materials checkbox causes issues on some 3D objects

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1762]
Hello,

A few tests on an executable version allow me to confirm the following : the "Materials" box, when it is checked, then unchecked, no longer allows the lighting to be restored on certain 3D objects.
![MaterialSetting](https://user-images.githubusercontent.com/96718175/149615581-bda4aa0a-3277-4c71-9ab6-548b8464733e.png)
Here is the overall scene with two pieces of furniture :
![global](https://user-images.githubusercontent.com/96718175/149615603-2c680aff-3f09-40b9-bebb-ed5fcad0768d.jpg)
Now I check, then uncheck the "Materials" box.
Here is a perfectly operational piece of furniture, without the lighting of the torch.
![Meuble1SansLight](https://user-images.githubusercontent.com/96718175/149615652-2ba8a0f7-adde-44fb-96b5-d814c9c6413e.jpg)
Here is the same piece of furniture, with the torch lighting.
![Meuble1AvecLight](https://user-images.githubusercontent.com/96718175/149615669-ae313fd9-514b-4166-bf25-d5d1caeba533.jpg)
Now the second piece of furniture, one of the problematic ones.
After checking, then unchecking the "Materials" box. The piece of furniture not lit by the torch :
![Meuble2SansLight](https://user-images.githubusercontent.com/96718175/149615703-532189ae-8561-4d08-aacf-713378a04b85.jpg)
The same piece of furniture, but lit by the torch :
![Meuble2AvecLight](https://user-images.githubusercontent.com/96718175/149615727-af8b6134-442c-402e-b7aa-16ade139f42f.jpg)
You notice that there is no difference in lighting on the front of this furniture.

In the map I sent to Rick, at least three 3D objects are impossible to light. Rick can find 2 of these objects on the ground floor, the two dressing rooms are not operational in the light. And another object is upstairs : the water dispenser is downright black. When it should be white. All this if you check, then uncheck the "Materials" box.

The result in the executable version is obvious.
Here is the water dispenser in the editor :
![water1](https://user-images.githubusercontent.com/96718175/149616245-9284fd0f-c0b3-4314-b04c-b9416ed1d7cc.jpg)
Here is the water dispenser in the executable :
![water](https://user-images.githubusercontent.com/96718175/149616259-bfbc201e-0095-4a4f-aca6-14f273b7e667.jpg)
So Max doesn't know how to restore these objects to their initial settings.
I hope it can help.

**Comment by 3coms** [comment]
You are right, I'm having the same issue as your last pic.
Entity settings need the way to set the material (listing all the materials out there, as GG does)l, even importer as well.

**Comment by ZakJudges** [comment]
Hi @UltraVox001, are you still experiencing this issue in the latest build? :)

**Comment by UltraVox001** [comment]
@ZakJudges 
It's old. Lol.
It's OK now. :)
