### ISSUE TITLE
GG Max Bug Report - No animations found in the Character Creator

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1763]
This is the latest version of GG Max EA.
No animation is available.
The old ones, like the new ones.
![animations](https://user-images.githubusercontent.com/96718175/149619468-de7113d4-03af-4d55-8f63-fc9e1f744214.jpg)
I hope it can help.

**Comment by rvanner** [comment]
@ZakJudges Please fix this first thing on Monday.
