### ISSUE TITLE
GGMAX - Group Thumbnails Problem

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1765]
When creating groups the resulting thumbnails are not generated properly
![GroupThumbnails](https://user-images.githubusercontent.com/95015657/149638405-7378982e-57dc-487f-a8c2-d7ed99e92163.jpg)

Possibly related to other screen capture error reported.

**Comment by plemsoft** [comment]
@rvanner I do not have a widescreen monitor to test/fix this, perhaps another dev. have one ?

**Comment by plemsoft** [comment]
@Necrym59 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Necrym59** [comment]
This is now confirmed fixed as of Build 2022.03.04 - thankyou guys
