### ISSUE TITLE
GG MAX Crashes after  2022.01.14 update

### ISSUE THREAD

**Issue by perovdm** [TheGameCreators/GameGuruRepo#1766]
Hi, After the  2022.01.14 update GameGuru MAX Crashes when I load and play an existing level. The whole thing closes about 2 seconds after the level starts. i.e. after the loading bars disappear and the game starts. It only seems to happen if I add a new character into the level ( Any other object seems to be fine). 
I have tried with a new level and that seems to work fine. 
Overall the editor also seems to be more sluggish. Loading & saving seems longer and adding new object items takes a few seconds where in the past it used to be almost instantaneous.

Windows Application log:
Faulting application name: GameGuruMAX.exe, version: 0.0.0.0, time stamp: 0x61e1e738
Faulting module name: GameGuruMAX.exe, version: 0.0.0.0, time stamp: 0x61e1e738
Exception code: 0xc0000005
Fault offset: 0x0000000000371046
Faulting process id: 0xfbc
Faulting application start time: 0x01d80a777d489a89
Faulting application path: D:\Program Files\GameGuruMAX\Max\GameGuruMAX.exe
Faulting module path: D:\Program Files\GameGuruMAX\Max\GameGuruMAX.exe
Report Id: e1aa9ec4-207b-4cf2-a397-3a31504140a7
Faulting package full name: 
Faulting package-relative application ID: 

System:
 Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: X570 AORUS ELITE WIFI
                     BIOS: F34 (type: UEFI)
                Processor: AMD Ryzen 9 5900X 12-Core Processor             (24 CPUs), ~3.7GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32712MB RAM
                Page File: 27559MB used, 22559MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 3080

**Comment by perovdm** [comment]
An update on this, if I change the character behavior to "Stand Idle" the game does not crash, but if I change it to Patrol or Soldier Attack it crashes.

**Comment by UltraVox001** [comment]
It's normal. Lee "forgot" to add the new character animations in this update. As a result, even the old ones have been erased. Do not use it until the next update. About this, read : https://github.com/TheGameCreators/GameGuruRepo/issues/1763

**Comment by ZakJudges** [comment]
Apologies for the late response. This was fixed some time ago, as part of work on new character animations. Closing this issue
