### ISSUE TITLE
There is still errors with the download / update of max

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#1768]
I still have download problems when i want to update or download Max,
i have tried to install to a new drive and also did a fresh  install but same story 
https://forum.game-guru.com/thread/223278#msg2645977

**Comment by rvanner** [comment]
@Pcskiller Can you please split this into separate issues? We like to have one issue per submission because it makes it easier to manage them. Keep this one as a download issue and raise new issues for the other items. Thanks.

**Comment by Pcskiller** [comment]
Ok

**Comment by Pcskiller** [comment]
Any news on the problem.???  i still get error code when i try to download the files list or try to verified the files.

**Comment by synchromesh62** [comment]
Wow are you still getting this issue 
Could it possibly be your router or internet provider .. 
Its such a strange one.

**Comment by ZakJudges** [comment]
Hi @Pcskiller, could you try delete C:\Users\<username>\AppData\Local\AGKApps\TheGameCreators\GameGuruMAXUpdater AND GameGuruMAXUpdater(new) - if it exists. This will prompt you to log in again. If you cannot find the folder, make sure that View->Hidden Items is enabled in Documents

Then could you run the updater as administrator and let me know if the problem persists? :) It might also be worth checking any antivirus software you have, in case it identifies the updater as a threat.

**Comment by ZakJudges** [comment]
Hi @Pcskiller, are you still having any issues with the updater?

**Comment by Pcskiller** [comment]
yes some time i have to download tree or four times with errors and then after that then it download correctly

**Comment by ZakJudges** [comment]
@Pcskiller Thank you for the info. Would you be able to attach install_errors.txt the next time you get an error? It's usually located in Documents\GameGuruApps\GameGuruMAX

**Comment by Pcskiller** [comment]
[install_errors.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8146718/install_errors.txt)

**Comment by Pcskiller** [comment]
[install_errors.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8146746/install_errors.txt)

**Comment by Pcskiller** [comment]
[install_errors.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8146885/install_errors.txt)

**Comment by ZakJudges** [comment]
@Pcskiller The first install_errors.txt suggest something is going wrong between the server and your pc. The second and third error logs suggest that the updater cannot access the folder where Max is installed. Could you try running the updater in administrator mode, and send the install errors one last time?

**Comment by Pcskiller** [comment]
Ok this is the error after running
[install_errors.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8147070/install_errors.txt)
 as administrator

**Comment by Pcskiller** [comment]
[Uploading install_errors.txt…]()

**Comment by ZakJudges** [comment]
Hi @Pcskiller, thank you for the error log. Do you have this file installed? "Max/Files/tutorialbank/0801-character-creator.mp4"

**Comment by ZakJudges** [comment]
@Pcskiller Thank you, the file should be nearly 300MB. I've opened a new issue detailing a fix for this - see #2331 

I will keep this issue open so I can let you know when the fix goes live :)

**Comment by Pcskiller** [comment]
Thank you

**Comment by Pcskiller** [comment]
Thank you

**Comment by Pcskiller** [comment]
![gger](https://user-images.githubusercontent.com/41600041/156987860-20e0570d-1caf-43e1-ad1f-473b168beea5.png)
[install_errors.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8195687/install_errors.txt)

ok i have the same problem.  I have updated and got error and opened max could see the new update announcements.
then closed and run the updater again ant this is the error

The first error happened when there were only 136mb left to update and with the second as you can see is more.

**Comment by ZakJudges** [comment]
@Pcskiller Thank you for the extra information. Could you let me know how much of this file downloaded?  "Max/Files/tutorialbank/0701-game-storyboard.mp4"

**Comment by Pcskiller** [comment]
![gger1](https://user-images.githubusercontent.com/41600041/157060520-5bab637e-5fc4-4301-bb5b-0b07628d2501.png)

**Comment by ZakJudges** [comment]
Hi @Pcskiller, could you give this updater a go and let me know if you get the same error? You'll need to replace your current copy of the updater with this attached one. Thanks!
[GameGuru MAX Updater (new).zip](https://github.com/TheGameCreators/GameGuruRepo/files/8199174/GameGuru.MAX.Updater.new.zip)

**Comment by Pcskiller** [comment]
Thanks, i will test as soon as possible
