### ISSUE TITLE
GG Max Bug Report - Uncertain limit of lights connected to a switch

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1769]
Look at this first screenshot :
![8LightsConnected](https://user-images.githubusercontent.com/96718175/149657042-a4c3d3b6-4a0b-417c-aa4f-6a1a0b87c9b3.png)
There are 8 lights connected to my switch. I cannot connect a ninth because the link refuses to be established. Even after saving and reloading the map in Max.
Look at this second screenshot :
![10LightsConnected](https://user-images.githubusercontent.com/96718175/149657058-70a040f0-b36c-4f17-baa5-024147b3f52e.jpg)
There are 10 lights connected to my switch.
The 11th refuses the connection.

In the first screenshot, notice that if I unlink the switch from Light 8, I can connect Light 9, so I'm limited to a maximum of 8 lights. But then why can I connect 10 Lights on the second screenshot ?

So there is a connectivity issue between the lights and the switches.
Ideally, I would appreciate that this limit does not exist. If I want to connect 1000 lights to a single switch, I have to know how to do it.

I hope it can help.

**Comment by ZakJudges** [comment]
Hi @UltraVox001. The current limit is 10 visual logic connections per object.  I wasn't able to reproduce the issue of being limited to less than 10. Are you still experiencing it with the latest build? :)

Re increasing the limit, if you create a new issue and label it as an enhancement or feature request, that will allow us to look at it in the future :)

**Comment by UltraVox001** [comment]
All 10 switches work.
But, surprise by re-opening this morning's map : look who I see :)
![10switch](https://user-images.githubusercontent.com/96718175/154502760-c3a80c84-1803-4a47-b871-f14c1ce72dfc.jpg)
I send you the map...
[DoorRising.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8089395/DoorRising.zip)
Pay no attention to the name of the map.

**Comment by ZakJudges** [comment]
@UltraVox001 Thanks for confirming. Closing this issue now.

I was able to reproduce #1876. Thank you
