### ISSUE TITLE
Glass, metal yellow color effect bug

### ISSUE THREAD

**Issue by corrosionsting** [TheGameCreators/GameGuruRepo#177]
Glass and metal entities have a yellow sludgelike overlay on them that changes as you move closer and change your position

**Comment by corrosionsting** [comment]
This is with pbr

**Comment by GraPhiX-Guru** [comment]
can you post pictures or even better a video

**Comment by Teabone3** [comment]
Do they change color based on what Skybox you have active during tests?

**Comment by Pirate-Myke** [comment]
Can you email me one of the objects and the textures, and the fpe file so I can check it out please.
Thanks.

**Comment by LeeBamberTGC** [comment]
Not able to reproduce this, all PBR entities look as intended in the stock library and DLCs.
