### ISSUE TITLE
Objects and characters not maintaining settings

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#1772]
I spent a long time getting my characters and models in my demo level perfect and working really well. After saving and closing for the night, when I loaded back up the next day all the settings showed the same however they all acted like they were the default settings. even when I change them and test the level they still stay on the default. 

I tried exporting a stand alone and it made no difference.

**Comment by UltraVox001** [comment]
@42Pix3ls 

Can you give us more details about these lost parameters ?
Is this a problem with the collisions of your objects ?
Please provide details with specific examples.

**Comment by 42Pix3ls** [comment]
After the most recent update I have noticed that the settings at least for the zombies don't work when you have them linked to a trigger zone and hidden at the start of the level. If I have the zombies load in with the level they all dash at me like I had setup. as soon as I link them to the trigger zone and spawn in they default to the arms out slow shamble.

**Comment by LeeBamberTGC** [comment]
@42Pix3ls I just created a fresh game project and level, adding a zombie set to an alternative walk animation, hidden at start of level, trigger zone surrounded by barrels, and when player enters the zone the zombie appears and using teh correct walk animation.  Cannot reproduce:

![image](https://user-images.githubusercontent.com/35840583/150838028-ec721a77-c5f8-4991-a1ad-72774437205d.png)

Can you send me an FPM level from te latest build from Friday so I can see what you see, thanks!

**Comment by 42Pix3ls** [comment]
> Can you send me an FPM level from te latest build from Friday so I can see what you see, thanks!

I am just at work, would you like me to upload it to g drive and post the link here for you?

**Comment by 42Pix3ls** [comment]
Ok here is the .fmp for the level affected [.fpm download ](https://drive.google.com/drive/folders/1ug9b1Kg7B76hcCxkPqGznpyhykwu-OAa)

**Comment by LeeBamberTGC** [comment]
@42Pix3ls Great level, I hope you are entering it into our competiion this month, I would very much like to see this in our EA version in March :)  As to your issue I could not reproduce, no zombies seemed to be in the level. I loaded your level, added a zombie, linked it to your trigger zone and ran, and it worked fine:

![image](https://user-images.githubusercontent.com/35840583/150950900-9c78a49e-a841-40fb-8602-09b2ad7517c8.png)

Can you reproduce the steps I made above?

**Comment by 42Pix3ls** [comment]
Hi Lee, thanks for taking a look at it. I have completely removed every trigger zone and zombie in the level. Starting from scratch the issue hasn’t come back but before that no zombie that I added would work. I don’t know if it was the order things had been done or what but it is working now so I thank you my good sir!

yes I will be submitting this level :)

**Comment by ZakJudges** [comment]
Hi @42Pix3ls, apologies for the late response. I could not reproduce this issue, do you still experience it in the latest build? Thanks :)
