### ISSUE TITLE
Some models export and render white

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#1773]
When building a stand alone some of the models only render as white as if the texture didn't exist. This includes the bullet decals. Example attached in youtube video

[https://youtu.be/xHeeQdo1IsI](url)

**Comment by rvanner** [comment]
@42Pix3ls The video link does not work. Can you check and re-share?

**Comment by UltraVox001** [comment]
@rvanner : [](https://www.youtube.com/watch?v=xHeeQdo1IsI)

**Comment by plemsoft** [comment]
@42Pix3ls Thanks for reporting this issue , this has been fixed and will be in the next update :)
