### ISSUE TITLE
I hate trees

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1776]
Trees are poppig up all the time after I have cleared all trees

**Comment by rvanner** [comment]
@smmaas Can you be more specific. What are your exact actions for this issue?

**Comment by smmaas** [comment]
I want a level with no automatically places tress. So I generate a level and clear all trees. I place some trees by hand, save en reload  and the system creates new trees, I clear them away, save load and again unwanted trees. I have to do this a few times until it stop accept for one or two trees popping up now and then.

**Comment by smmaas** [comment]
Before save game

![before](https://user-images.githubusercontent.com/45684694/149781402-f88dfc97-ecde-4cf4-b3d2-4c13fb479692.jpg)

after load again

![after](https://user-images.githubusercontent.com/45684694/149781506-136cdc9d-59af-4ab8-b4ad-21ebaf8ad30b.jpg)

**Comment by UltraVox001** [comment]
I confirm this problem, having seen it many times. Max still doesn't remember the trees we erased. And he replaces new ones randomly in erased areas.

**Comment by plemsoft** [comment]
@PaulSJ Here is how to reproduce it: https://drive.google.com/file/d/12stgTN2oz_gmeyyADdpARFrRqAURAFEt/view?usp=sharing
(dont happen everytime , but most times ). I assume that when we do a GGTerrain_InvalidateRegion that not all the trees are part of pTreeChunks , and that some trees that are not part of pTreeChunks could popup after a InvalidateRegion ?

**Comment by PaulSJ** [comment]
Fix might not be in the release version but should be shortly after

**Comment by ZakJudges** [comment]
Hi @smmaas @UltraVox001, could you confirm if this issue is now fixed for you? Thanks!

**Comment by smmaas** [comment]
Haven't had the problem for a while so it looks fixed

**Comment by ZakJudges** [comment]
Thanks for confirming, closing this issue
