### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1777]
While trying to do something more serous I had two crashes losing everything. Can't reproduce but one happend while moving the camera and the other while adding a tree. Please add an autosave/recover option

**Comment by rvanner** [comment]
@PaulSJ I also had a crash when moving a tree on Friday. Any ideas if this is in your code?

**Comment by UltraVox001** [comment]
You can make your backups yourself with great ease. All your maps are here : C:\Users\Your_Name\Documents\GameGuruApps\GameGuruMAX\Files\mapbank
Save this directory (copy/paste) as often as possible to avoid accidental loss and destruction of files.

**Comment by smmaas** [comment]
I was thinking about autosave every 5 or 10 minutes while working at least until the program is save.

**Comment by UltraVox001** [comment]
Many users complain that the loading and saving times are too long. If this option were to exist, it would have to be optional. In addition, saving a map completely blocks Max's process. Unable to move the camera or perform any action.

**Comment by smmaas** [comment]
I was one of those complaining, but this could be done by a background proces.
