### ISSUE TITLE
Objects fall

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1779]
Object fall down if you don't lock them like lights on the wall.

**Comment by rvanner** [comment]
If Objects are set to active and are affected to physics then they will fall to the ground. Which objects are you reporting about?

**Comment by smmaas** [comment]
The  problem is that also static objects sometimes drop

**Comment by rvanner** [comment]
@smmaas Can you share some names of objects that do this? It's probably just how they have been setup.

**Comment by smmaas** [comment]
I imported this torch from classic, put it on the wall with a light, torch dropped light stayed (static, polygon)

![after](https://user-images.githubusercontent.com/45684694/149806862-e7a866fc-1ba3-40ff-bfa2-c0ca82c66ead.jpg)

**Comment by rvanner** [comment]
This might just be how it was set up when it was imported. My colleague @ZakJudges will discuss this with you when we start the big bug fixing in February. Thanks for sharing your findings.

**Comment by ZakJudges** [comment]
Hi @smmaas, are you still experiencing this issue in the latest build? 
If so, do you still have a copy of the imported model's dbo and fpe files? Or steps to reproduce?  Thanks :)
