### ISSUE TITLE
Possible Animation issue

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#178]
Hi
if I don't have playanimineditor = 1 set at 1 all the time animations will not play I have tested with apbr_basic.fx and apbr_anim.fx both do the same :(

https://youtu.be/S0lHwZTfg08

**Comment by GraPhiX-Guru** [comment]
Also the anim speed if set to a different value than 100 if you exit the test run then run it again the anims default to 100 I have to go into each property and click apply again for it to take effect even though the values are there https://youtu.be/IzML8jXVhAE

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this,

This has been fixed and are ready for the next release :)

**Comment by plemsoft** [comment]
@GraPhiX-Guru Also fixed anim speed problems when returning from test game.

**Comment by plemsoft** [comment]
@GraPhiX-Guru 

From the next update you will be able to use:

playanimineditor = 0
and 
startanimingame = 1

To only display the animations when the game is running.
