### ISSUE TITLE
GG Max Bug Report - F11 key causes Runtime error + crash in TestLevel mode

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1784]
F11 key causes Runtime error + crash in TestLevel mode (tested successively on 4 maps) :
![Error](https://user-images.githubusercontent.com/96718175/149768643-722dd3de-cf95-4e82-acf7-791ee5b5e3b1.jpg)
I hope it can help.

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue, this was fixed in last Fridays build , could you confirm this and close the issue if its also fixed for you , thanks for your help :)

**Comment by UltraVox001** [comment]
@plemsoft 
Problem solved. Thank you. :)
