### ISSUE TITLE
Jungle Tree got black areas in roots.

### ISSUE THREAD

**Issue by littleisland** [TheGameCreators/GameGuruRepo#179]
Hi, i did the upgrade to GameGuru 2018.04.17 (DirectX 11 & PBR). After this the "Jungle Tree 02" from the "foliage" entities folder is now drawn partially with black areas instead of the roots. Please have a look at the picture below.

![grafik](https://user-images.githubusercontent.com/38508205/38953781-1c065740-4350-11e8-9768-5c62bf351c58.png)

**Comment by plemsoft** [comment]
This has been fixed in the latest version.
