### ISSUE TITLE
AUTOFLATTEN does not work for me

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1792]
Since version 2022_01_14 autoflatten doesn't work for me despite re-installing from scratch via the tiny installer.
And despite having downloaded all the GGMax collection packs, again.

I should add that I wrote a script that converted all models to autoflatten=0 and it worked fine, of course until the next update, from which point autoflatten no longer works for me, even after a fresh install with new models, etc.
I wonder if this has something to do with it? but it doesn't make sense considering everything is installed from scratch again.

https://youtu.be/WDBSQ1E2iy0

**Comment by UltraVox001** [comment]
Go to: C:\Program Files\GameGuruMAX\Max\Files\entitybank\Buildings Collection\Building
Open several .FPE files and check line number 18.

**Comment by 3coms** [comment]
I've removed all that has to do with GGMax and did a clean install (tiny installer) and tick all the collection packs to download, so now all is new, fresh, and untouched, despite so, it does no work.
About script has nothing to do, without a trigger to run it.
I've tried twice doing the same clean, fresh install no to avail. 
Anyway, thanks for the tip. :)

**Comment by UltraVox001** [comment]
The installer checks if any old files are there. If it finds any, sometimes, it doesn't overwrite them during installation.
After uninstalling Max, you must ensure that the following directories no longer exist :
- C:\Program Files\GameGuruMAX
- C:\Users\Your_Username\Documents\GameGuruApps

You can also launch the Max installer and do a Verify Files.
Right now.

**Comment by 3coms** [comment]
Ok, guys, finally I manage to fix it. :)
What I did:
1- Removed all fpe files from Documents/GGameGuruApps\GameGuruMAX\Files\entitybank folder as Preben suggested.
No to avail.
2- I removed the whole building/shanty collection folders from there.
3- Since I backup the collection packs, so I copy/paste them in C:\Program Files\GameGuruMAX\Max\Files\entitybank
4- Verify files
5- Run GGMax and all works ok.

![autoflatten_Working_OK_GGMax_2022_01_21_pic01](https://user-images.githubusercontent.com/47690174/150128081-1d378e34-5669-4b47-8a50-ad5d9cfa0704.png)
