### ISSUE TITLE
GG Max Bug Report - Lost collisions on many objects after a Save

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1796]
EDIT : Pirate Myke (Mod Team) made video tests and demonstrates the reality of this problem.
Read here, on the [GG Max Forum](https://forum.game-guru.com/thread/223291).
I invite you to watch my short video :
[https://www.youtube.com/watch?v=Tx_c1sJna7Q](https://www.youtube.com/watch?v=Tx_c1sJna7Q)
And that of Pirate Myke :
[https://www.youtube.com/watch?v=WlB2c7_Maeo](https://www.youtube.com/watch?v=WlB2c7_Maeo)
END EDIT.

@rvanner please. Read this in full.

I have been seeing this problem for several days now, which is very common.
Watch this short [video](https://i.gyazo.com/a6f0f11966f5fe8b509d41d649546730.mp4).
How is it possible ?
Here is what I do :

- First, I load the map into Max.
- Then, I want to delete 2 identical objects which have no collisions. They are in the house.
- Once removed, I run a TestLevel. Everything is fine. The house has its Polygon collisions.
- I save.
- I close Max.
- I reopen it.
- I load the map.
- I run the TestLevel.
- The house no longer has collisions. 👎 

Just saving the map changed the house collisions. Why ?

Note that this problem repeats itself over and over again, every day. Sometimes it's not the house that loses its collisions, but certain objects, whether inside or outside the house. It is therefore a "random" problem. Although I find that the house is often the target of this problem.

This forces me to make many manual backups in the mapbank directory. And because of this, I'm moving very slowly since this problem occurs. There is "something" that imposes a "No Collision" on objects that need collisions.

I don't know what it is, but it's a real problem.

We can assume that on a small blank map, this problem will be difficult to reproduce. This problem would be easily solved if Max agrees to change the Collisions mode of the house. But he refuses. And I reported it [here](https://github.com/TheGameCreators/GameGuruRepo/issues/1790).

I sent a map to @rvanner, on the forum in private message (second message, Map16.fpm). On this map, more than 70% of the objects have lost their collisions. All this after a simple backup. Why ? But I feel like @rvanner never logs into the forum. Messages are "unread". And I am unable to find the collisions of the house. :(

**Comment by UltraVox001** [comment]
Note that this problem also occurs on "empty" maps. I dropped off a house and wanted to put a radio antenna on the roof. The roof is inaccessible. It is thus useless that this antenna has collisions (it is necessary to relieve the engine on the useless collisions). I disable collisions, but they are still there : [video](https://i.gyazo.com/a025e36508821d52b710bb574706abe9.mp4).
![RadioTower](https://user-images.githubusercontent.com/96718175/150501319-444d4739-a157-4a33-b14f-803757d91fc6.jpg)

**Comment by UltraVox001** [comment]
And it goes on, again and again.
![ForcedCollision](https://user-images.githubusercontent.com/96718175/150591492-ecd3f042-f4ca-4082-8fa0-95590d6e86f3.jpg)
How to pass a door when its outline has a spherical collision, while 2 minutes before its collision was polygonal ? Max changes parameters while saving, and it refuses to override collisions. This problem is boring ! And I suggest you deal with this MAJOR problem, now.

**Comment by synchromesh62** [comment]
**" This problem is boring ! And I suggest you deal with this MAJOR problem, now."** 
Do you have to be so rude. 
Yours is not the only list of bugs that needs sorting.

**Comment by UltraVox001** [comment]
I think there is a problem with the translation. Where have I been rude ? I've never been with anyone. On the net and in reality. I am exposing a problem that prevents any possibility of creating anything, because the choice of collisions works in a "random" way. It changes, either with Saving or Loading the map. And when I change it manually, nothing happens. However, the month of March 2022 is fast approaching. As a bonus, TGC asks us to make demo maps. How to make a map with random collisions ? I'm aware of all the bugs, since I gave many of them to TGC on this Github. Like others before me. But I'm certainly not rude. I report a technical impossibility which seems to me extremely serious. And I think on the list of all the existing bugs, if this one is not considered very quickly, no one will be able to use Max for a somewhat serious project. This is the 9th map that I start again because of this problem. So it seems to me that this is an urgent problem. Not urgent for me, urgent for Max!
