### ISSUE TITLE
ScrollingTexture.fx can't load

### ISSUE THREAD

**Issue by littleisland** [TheGameCreators/GameGuruRepo#180]
Hi, I'm using the GameGuru build 2018.04.17. During startup of GameGuru I'm getting a message that the ScrollingTexture.fx can't load, because of incorrect version of the HLSL level. I put a screenshot of the message box below.

![grafik](https://user-images.githubusercontent.com/38508205/38954622-685718f8-4352-11e8-8bf5-27ca5487bdef.png)

I renamed the file, so that GameGuru succeeds running. But then - of course - some animations are not working (for example the the waves pack, which i bought from the TGC store).

Some idea to get that working again?

**Comment by Pirate-Myke** [comment]
Can you post a image of the texture you are using with this shader?
The shader itself is dx9 and will not work with the new version as written. Contact the store seller for an updated script.

Now what you may be able to do is adapt one of the new shaders to it and modify it to your needs till the store seller fixes it. But I would need to see the texture sheet, in order to point you to the right shader for dx11.

**Comment by littleisland** [comment]
Thanks for reply, Pirate-Myke,
I will contact the store seller. Further more, i put the waves entity as a zip file below. Hoping, that's what you requested.

[waveplane800.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1925775/waveplane800.zip)

**Comment by Pirate-Myke** [comment]
Looking at this now.

**Comment by Pirate-Myke** [comment]
You need to assign the object the effect_scroll.fx file. This shader will do what you need it to do and is dx11 ready.
You can change the speed in these lines.
float4x4 WorldViewProj : WorldViewProjection;
float time : time;
float sintime : SinTime;
float directionX = 0.1f;
float directionY = 0.0f;

Save the file.
Dont forget you will need to recompile the shader by using the
forceloadtestgameshaders=0 set to forceloadtestgameshaders=1
And restart game guru. Place the object in the editor map and test.

**Comment by littleisland** [comment]
Thanks a lot. I will try this and tell you!

**Comment by LeeBamberTGC** [comment]
This shader is not part of the core product.

**Comment by littleisland** [comment]
@Pirate-Myke 👍 
Thanks again. It works!!
