### ISSUE TITLE
GG Max - Suggested Feature - Inanimate doors with Rotation Script (New TGC Behavior)

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1800]
I have discussed this elsewhere on this Github. We found that the current system for doors lacks imagination and is expensive to create, as TGC has to pay people to create animated doors. However, there is another possibility, simpler and free : [video](https://www.youtube.com/watch?v=IJN6gIs4dkM).

The script used in this video was created by AmenMoses. It turns any flat vertical mesh into a doorway. Of course, you noticed that this script uses a central pivot. So we need a pivot suitable for inanimate doors. That's all.

The fact is that Max has almost no working doors, with animation. But this animated (or not) door story is a bit ridiculous. It is needed for some futuristic doors with special openings, but most traditional doors should work without any animation. It would be better to create Behaviors for opening and closing doors that we could use on inanimate objects on which we would apply a simple rotation.

So, even a piece of wall, or a Fence, or virtually any other 3D game object could function as a door when given the proper Behavior. You know, a door that opens is just a rotating object for 1 second. You might as well create a script, a Behavior that would allow any object to be a door. So all doors, even inanimate ones, would work perfectly with Max by applying a simple rotation.

The Behavior could even give us choices : open to X degrees, to the right or to the left. Vertical, horizontal opening, etc. This script would do some great things, as shown in the video above.

Why bother finding doors with animations, when you can do without them, and create surprising things with simple means ?

Currently, Max does not offer anything on this subject. This new Behavior is sure to please everyone. Because the creative possibilities are endless.

I hope it can help.

**Comment by ArgentArts** [comment]
Completely agree. This could be expanded to sliding doors, too. So, the end-user could enter a number for sliding a door on the X, Y, or Z axis to get a door to move up, right, or left according to the object's axis. For rotating objects, as UltraVox001 stated, it would be great if the end-user could simply enter the degrees the door opens. It would also be nice if there were a mechanism where the end-user could define the pivot incase the model has the pivot in the center or some other location.

**Comment by UltraVox001** [comment]
Yes, and you have no doubt noticed the big flaw in the current doors ? Once opened, you can walk through it. Because the collision is content to disappear and does not reappear in the axis where the door is. This is the dumbest door system I've seen in my life. :)

**Comment by ArgentArts** [comment]
Yep. Apparently, this is the way they do it in Classic, too ... cancel the collision while the door animation plays. It's pretty bad.

**Comment by synchromesh62** [comment]
In its defence the collision is cancelled so you the player and the NPC's do not get snagged up in the doors. 
There are modified scripts on the forum for GG that keep collision but caused the issues i mention so they were not as poular as expected.

**Comment by ArgentArts** [comment]
Yes, it is a solution, but it is not the best solution. Other games do not shut off the collision when opening/closing doors, allowing the player to pass through the door as it is in the process of opening or closing (i.e. to walk through the door as if they are a ghost). So, while this solution "works", shouldn't TGC seek a better solution since there obviously are better, working solutions out there (especially since every other game out there uses them)?

**Comment by UltraVox001** [comment]
It is necessary to restore the collisions of the inanimate objects and to know how to make of them doors in rotation on an axis. The fact that in some special cases we can be stuck between a door and a wall should not make us deactivate the collisions of all the doors of all games make with GG Max. It would have been more efficient to do as in almost all the games which encounter this type of problem : we open a console and type /stuck

The command could teleport the player in any direction within 2 meters of their position. Or she could open or close the nearest door.

Problem fixed.

**Comment by synchromesh62** [comment]
Finally managed it thanks to Graphix's idea
Same script as the previous video ( AmenMoses Script ) I just moved the door left in a model program off its origin :)
https://youtu.be/XFu9fT-hGt4

**Comment by UltraVox001** [comment]
A wonderful progress! I congratulate you for this work. It's absolutely awesome.
Do you think you can provide options for this Behavior, as proposed above ?
(degrees, axes of rotation, left, right, vertical or horizontal, etc.)

In other words, are there any limitations, and if so, which ones ?

**Comment by mav3r1ck1981** [comment]
@Kasseyus this has been in the core for years now and can be closed
