### ISSUE TITLE
GG Max Bug Report - Overstretched tall Tree Textures

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1803]
Look at this screenshot :
![Tree](https://user-images.githubusercontent.com/96718175/150344666-e6b8af8f-cca4-4612-901c-b787a17577c4.jpg)
Large tree textures are too stretched. This most likely stems from the new "Tree Height" feature which stretches tree textures. By the way, I congratulate TGC for adding these new features. It's already much better. Keep improving ! :)

**Comment by UltraVox001** [comment]
The White Pine tree has a disastrous rendering. This was already the case before the implementation of the "Tree Height" function. Fix it, or delete it. But do not offer it in this state. :)
![pine](https://user-images.githubusercontent.com/96718175/150493798-a2d7182d-6bcc-4cba-bcfc-8747406d1337.jpg)

**Comment by rvanner** [comment]
@UltraVox001 These should all be fixed now. If you agree please close down this issue.
