### ISSUE TITLE
DDS5

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1804]
Certain models with dds textures cause the entire engine to die a horribly firery death, in this case I moved the cementry pack from classic tto ggmax, some great models in there and the textures (very big textures) completely slow things down till a near halt. Doing some tests, converting them from dds5 to dds1, and trying them out.

I know these assets where buit for classic, but i've experienced this same slow down issue before and never understood what was causing it.

**Comment by rvanner** [comment]
@casigus Can you share a few of these models with me and I can get the guys to check them out to why they are causing issues.

**Comment by casigus** [comment]
YES! great idea ! ill get on that now!!!

**Comment by casigus** [comment]
https://drive.google.com/file/d/1IB6crRweVRIjD-tOgK7eN9cyTEEU957E/view?usp=sharing okies uploaded one of the models here! :D im going to keep playing around on my end, see if its a texture size thing. Did try it with out the texrtures and seamed to work great so thus leaning towards the DDS5 thing.

**Comment by rvanner** [comment]
@ZakJudges One for you to investigate please.

**Comment by ZakJudges** [comment]
Hi @casigus, in the provided files, there was no .dbo or .x file, only the textures and fpe. Would you be able to send it if its still causing issues? Thanks :)

**Comment by casigus** [comment]
there you go. it happens with alot of other ojects too ive noticed, even when you change collisions. causes a massive slow down.

**Comment by ZakJudges** [comment]
Hi @casigus, thank you for reporting this issue. I was able to reproduce the slowdown issue without the textures. The model attached has 87 meshes within it, so I'm assuming its perhaps an issue with that. However, I'll be taking a closer look at it alongside the scheduled importer work :)

**Comment by casigus** [comment]
glad I was able too assist!
