### ISSUE TITLE
Grass and trees not loading in test mode

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#1805]
Since resetting all visuals none of my grass or trees work in test mode. They are all still in place in the editor
![Screenshot 2022-01-21 224754](https://user-images.githubusercontent.com/95527550/150522687-c051ac81-93ce-4820-9040-bc25f7c0ab57.png)
![Screenshot 2022-01-21 224753](https://user-images.githubusercontent.com/95527550/150522699-01872b41-b69f-4054-a03f-a86b6b305729.png)
.

**Comment by UltraVox001** [comment]
Yes, it can happen. Have you tried the options "Clear All Vegetation", then "Populate Vegetation Everywhere" ? Same for trees. Usually it helps to solve this problem.

**Comment by Granada1** [comment]
Have you checked these
![AFps_002](https://user-images.githubusercontent.com/35897659/150532261-56dc5646-aa39-46c1-9480-3efd0f97461b.png)

**Comment by UltraVox001** [comment]
This too. Sometimes there is no problem. Just oversights. :)

**Comment by 42Pix3ls** [comment]
Neither of those solutions worked however when I updated to the lasted build it has come right. is there a caching system in the editor?

**Comment by UltraVox001** [comment]
There has been a major overhaul of vegetation and tree systems in the latest version of Max.

**Comment by rvanner** [comment]
@42Pix3ls Is this fixed now? Can this be closed?

**Comment by ZakJudges** [comment]
If I remember correctly, this was fixed a long time ago. Closing as had no more reports of the issue. If the problem persists, feel free to reopen, thanks :)
