### ISSUE TITLE
GG Max Bug Report - Auto Reset Physics on grouped objects

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1807]
Little experiment tried this morning with the latest version of Max EA. Experience reproduced several times on blank maps (terrain + vegetation + trees). Nothing else. I used a house with a few items inside. Maybe twenty objects. So very little. I save the whole in a Group, as if I were making a Prefab with the intention of multiplying it 3 or 4 times, scattered on the map. After dropping my group on a brand new map created by Max, the TestLevel displays this :
![ObjectGroup](https://user-images.githubusercontent.com/96718175/150629302-224b30e0-6e42-4fa5-a4f0-b1f50c901075.jpg)
All items have been physics reset. So assembling objects into a group causes them to lose important parameters. This forces the user not to use this function. Except maybe for the little things like a candle and a flame...

The reset data is of the types :
- Physics
- Collisions Mode
- Materials
- Lighting Relationships
- AI Relationships
- Behaviors of all Switches and Entities
- Associated sounds (Switches, Doors, etc...)

Like on this screenshot where this door should be displayed in "Double Sided" Material mode.
Here it is disabled.
![DoubleSided](https://user-images.githubusercontent.com/96718175/150629803-0dfaee3c-2818-48c9-a3a7-d12ded8e3d75.jpg)

Also, if a Switch and a Light are part of the group, all relationships are destroyed. All Lights added in the group also lose the small gray ball to create the Relationships with the switches. However, the "Toggle Light" Behavior is present in the settings. Which forces the user to delete the light to add a new one. Therefore, the entire lighting of the group is to be redone.
![LightBehavior](https://user-images.githubusercontent.com/96718175/150630510-64f302a7-b559-4cb6-97fc-a5e010901dfb.jpg)

I hope it can help.

**Comment by smmaas** [comment]
An other question: why does a house with physics on starts floating in they air??

**Comment by UltraVox001** [comment]
That's the problem I'm exposing : this house is flying because the physics have been changed when grouping objects.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Some fixes here, one involving the collision mode not being maintained when copying objects during group creation, and another related to this which could change the collision state of objects placed after group work. Now a building with contents can be grouped and duplicated with no ill effects with physics:

![image](https://user-images.githubusercontent.com/35840583/155165957-4550d10c-5171-4d82-b843-746cf89edf9e.png)

All other properties; materials, light properties, behaviors, settings, sound choices, are all preserved.

I also also added code to duplicate the logic connections, and interested to see if this is an option some users might want turning off.  If so, we can add it as an enhancement request.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
I'm impressed with this bug fix. Its very important. The creation of prefab will be greatly facilitated. :)
I keep this page in memory and I will come back to confirm after the tests.
A big thumbs up for you! :)

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
Test with last internal version.
- The normal Lights are well memorized in the group with the chosen parameters.
- The Directional Lights are not memorized in the group. They reappear as normal Lights.
- A door with Behavior Door Rising reappears without any Behavior.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 No such thing as directional light type. I did create a group with a single spot light and one object, then created a group and cloned it, which worked fine:

![image](https://user-images.githubusercontent.com/35840583/155520853-8221cb46-d7b1-4aab-b351-7f5b2bdfb4d4.png)

Did same thing with adding two doors, set them to rising behavior, created a group, cloned that group and then edited the group so I could view the behaviors, and the new group objects retained the behavior choice:

![image](https://user-images.githubusercontent.com/35840583/155521241-6e83b839-7905-4dd1-bc0c-7d4da886be50.png)

**Comment by UltraVox001** [comment]
You are right.
I just updated Max and it works great. I think my version was from yesterday or before yesterday.
Sorry for the loss of time and thank you for this addition. :)
