### ISSUE TITLE
delete after update

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1808]
Every update deletes my levels but, as advised I make a copy before updating (as the system does as well). After the update I rename the copy to its old name and continue work with the old version. This way I not only get my old stuff back but also I overwrite the things the update has changed. So here is my question, which files do I need to copy back the get my game back without overwriting the new files. 

changes after update

files/level/testmap 15 files are removed
files/mapbank   my levels *.fpm are removed
files projectbank  my project is removed  
files/ gamecore amd editors are deleted
imported_models is removed

if I only copy *.fpm and my project in projectbank everything seems to work but I lose the thumbnails of my level in the start screen and the storyboard and strange things happen to my terrain.

**Comment by UltraVox001** [comment]
Usually, Max creates a backup folder of all your maps. But for this update, I did not have a backup. However, I haven't lost anything. All my Projects and all my Maps are there, in the "projectbank" and "mapbank" directories. For me too the thumbnails (projects and maps) disappear.

**Comment by rvanner** [comment]
@ZakJudges Can you give @smmaas advice on this please?

**Comment by ZakJudges** [comment]
Hi @smmaas, as far as I'm aware, the files that you are looking for will be in:
- projectbank
- mapbank
- any in a "user" folder (best to search for these from within the "Files" folder)

**Comment by OldFlak** [comment]
MAX will remove any files in core directory - so make sure you are not saving anything there.

There is a **BUG** where the **updater makes a backup of the writable folders** and **creates new blank ones**. 
The whole idea of writable folders is for your custom media to be safe, not have to copy it all over after every update.

MAX - just leave the writable folders alone already :)

**Comment by rvanner** [comment]
@ZakJudges Can you comment on this Bug issue please?

_There is a BUG where the updater makes a backup of the writable folders and creates new blank ones.
The whole idea of writable folders is for your custom media to be safe, and not have to copy it all over after every update._

**Comment by ZakJudges** [comment]
@rvanner @OldFlak For the time being, we need this behaviour so we can simulate day one installations for each build so we are not fixing issues related to leftover files and slowly confusing matters. However, I agree its certainly not ideal, and is for the development phase only :)

**Comment by OldFlak** [comment]
@ZakJudges that does not make any sense to me at all. 
The writable folders are for **custom media** so there should not be any leftover files in the writable area that need to be updated anyway?

**Comment by ZakJudges** [comment]
@OldFlak As far as I'm aware, whilst the writable folders are indeed for custom user media, they also serve to store all files that are generated automatically by the engine for your games. For example, terrain physics objects. And so, we backup and create a new writable folder to prevent any files relating to areas in active development from causing crashes/bug reports that require a lot of time to investigate.
I know its inconvenient for the user, but its only whilst certain areas of the engine continue to be developed :)

**Comment by OldFlak** [comment]
Yes I understand what you are saying, but the updater should be working properly now - there is always going to be updates down the line.

So only replace what is needed not all custom media as well, would be a better option?

jmo :)

**Comment by ZakJudges** [comment]
The updater no longer makes any changes to the writeable folder. Closing this issue
