### ISSUE TITLE
random tree height

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1809]
placing trees one by one with "add tree" doesn't uses random height. 

![after](https://user-images.githubusercontent.com/45684694/150632310-acd8c291-777d-4fa4-bad3-23a7ba6968e9.jpg)

Trees in picture where placed one by one from left to right.

**Comment by plemsoft** [comment]
@smmaas Thanks for reporting this issue , just tried this in the latest build ,and it looks like it works here, could you try this in the latest build and let me know if you still have this issue, thanks for your help :

![tree-height-add](https://user-images.githubusercontent.com/18662417/151699800-4df376bc-1262-42ce-968d-40abed7cf091.jpg)
)

**Comment by smmaas** [comment]
Works great thanx

**Comment by smmaas** [comment]
Actually I looked some more into it and it doesn't. At least it stops working after a save and reload. The back row i planted first and the front row after a saved and reloaded the scene.

![image](https://user-images.githubusercontent.com/45684694/153730552-1f613dcb-ded0-4ff6-b761-b39f8f8c18f3.png)

**Comment by plemsoft** [comment]
@smmaas Thanks , this has been fixed and will be in the next update :)
