### ISSUE TITLE
Setting entity sound volme now controls all entities and background sound

### ISSUE THREAD

**Issue by corrosionsting** [TheGameCreators/GameGuruRepo#181]
In my ai scripts, I set the sound volume of their sounds to match distance. Now, everytime they make a sound, it affects ALL sounds playing.

**Comment by Teabone3** [comment]
Which sound volume commands/variables in LUA are you using?

**Comment by LeeBamberTGC** [comment]
use SetGameSoundVolume and SetGameMusicVolume for global volume control, and use SetGlobalSoundVolume to control the volume of specific sounds loaded from script, and for entity sounds, ensure you specify MONO WAV sounds and they will be played back as 3D sounds. You can modulate the sound by editing the WAV if you need it louder or quieter while playing as a 3D sound.
