### ISSUE TITLE
Physics shapes part 2

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1811]
see issue 1782

Physic shapes from some Imported objects don't scale properly

in picture from left to right

original object, scale, scale Y, scale Z, scale X

![before](https://user-images.githubusercontent.com/45684694/150634204-b574ef54-4757-466d-aeeb-b8c31663985e.jpg)

notice the scale direction X and Z are reversed for these  imported objects (for imported object Z is up).

**Comment by ZakJudges** [comment]
Likely fixed as part of work on #1624. If the problem persists, feel free to reopen. Thanks :)
