### ISSUE TITLE
Build 2022-01-21  /  Zombie AI conflict (x3)

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1812]
This could be because Lee is working on AI but it was not apparent on the internal builds last week.

Every launch is different. 
1 .. Sometimes Zombies work and sometimes they just stand there.
2 .. Sometimes Zombies follow flags or not and just bash them.
3 .. Sometimes AI follow Zombie flags despite having **followApath**  unticked  ( **Perhaps Red flags for Zombies** ? )
When it does work its brilliant but right now its all over the place.

**Comment by rvanner** [comment]
The character creator was not creating characters with the correct behaviour. Let me know if this is still happening.

**Comment by ZakJudges** [comment]
Hi @synchromesh62, are you still experiencing these AI issues in the latest build? :)

**Comment by synchromesh62** [comment]
At work at the moment i will try as soon as i get back  :)

**Comment by synchromesh62** [comment]
> Hi @synchromesh62, are you still experiencing these AI issues in the latest build? :)

Hi Zak checked this out again when i got home and still a no go :(
Although saying that occasionally they will return and follow the fags but rarely
Heres a quick vid 
https://youtu.be/XqX-Yc-sXdw

Ideally like the soldiers it would be nice to set a Zombie to walk a path \ corridor then attack when they see you and return to the path once your out of range. They are always standing still initially with flags or not.

**Comment by ZakJudges** [comment]
@LeeBamberTGC One for you :)

**Comment by LeeBamberTGC** [comment]
Basically focusing on AI for soldiers first, and when all my soldier items are fixed, I have about 6-7 zombie AI items to go through. Hopefully the fix will come soon :)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 All other zombie AI issues now in the current build, so when I send the internal build email you can check to see if any of the above 3 issues remain.   The only thing to bear in mind is that older levels might not have the new properties for the Zombies so always a good idea to click them and make sure their properties are correct before clicking test level and saving.

**Comment by synchromesh62** [comment]
Checking them out at this very moment  .. So far so good :)

**Comment by synchromesh62** [comment]
> @synchromesh62 All other zombie AI issues now in the current build, so when I send the internal build email you can check to see if any of the above 3 issues remain. The only thing to bear in mind is that older levels might not have the new properties for the Zombies so always a good idea to click them and make sure their properties are correct before clicking test level and saving.

Checking them out at this very moment .. So far so good :)
