### ISSUE TITLE
GGMAx Painting texture doesn't work

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#1813]
Painting Texture doesn't work in the latest update. 01-22-22

**Comment by UltraVox001** [comment]
What texture are you trying to apply ?

**Comment by Hamada880** [comment]
Sure, I have use the empty terrain floor and non of the textures paint or even tree or grass. Will update you with screen shot tonight.

**Comment by Hamada880** [comment]
Tested the engine after reinstall it. Now the painting works in empty terrain room.
