### ISSUE TITLE
Fish

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1814]
https://vimeo.com/669016848

**Comment by UltraVox001** [comment]
I confirm. It was reported that Max's build has a lot of issues with the AI this week. We know that Lee is working on this problem. Let's wait until next week for better results.

**Comment by AmenMoses** [comment]
There  is no fish AI yet, but placing down entities and them moving with no behaviour attached is a bug (one I thought had been fixed some time ago!).

**Comment by rvanner** [comment]
Fish AI was recently added. Is this still an issue?

**Comment by UltraVox001** [comment]
@rvanner 
There is no AI script for fish in the public version of Max EA.

**Comment by rvanner** [comment]
@UltraVox001 OK, you should see it working next week!

**Comment by LeeBamberTGC** [comment]
@rvanner It is only in our internal build, and will be shown on Wednesday and released to pre-order users on Friday.

**Comment by LeeBamberTGC** [comment]
@smmaas Can you confirm fish are okay for you now.

**Comment by ZakJudges** [comment]
Fixed as of latest build
