### ISSUE TITLE
unstable mess.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1815]
![image](https://user-images.githubusercontent.com/68471279/150661199-83af6b72-8132-443a-8e2a-f16fdaa5573c.png)

Currently trying to make a demo game for the demo game comp and ggmax is so unstable, you sneeze and it crashes.

Im using max on a ssd, (one i bought entirely dedicated to running max) there are no other assets installed here apart from the ones it comes with and it crashes all the time, I can't get any of this demo done because its just too unstable.

On top of that, I can hear my internal mechanized disk going nuts.

WHY?? there IS nothing on that DRIVE that has anything to do with max, my operating system is on a ssd, but every single time it crashes like this or freezes up, I CAN HEAR my internal drive going nuts.

WHY is Max trying to access my drive that has nothing installed from MAX or connected to max on itt??

eitherway im getting really pissed off because been trying to put a demo together but thus far its proving IMPOSIBLE. 

I'm loosing my god dam mind over this.

**Comment by Granada1** [comment]
Max also stores files in your documents folder

**Comment by smmaas** [comment]
At the moment max uses insane amounts of memory. When I start a level t goes up to 12MB. Maybe it's memory swapping?

**Comment by rvanner** [comment]
The recent memory leak was fixed. Is this still a problem for you?

**Comment by casigus** [comment]
Yah the memory leak is stilll a thing saddly.

**Comment by LeeBamberTGC** [comment]
@casigus You may not have the fix, it is only in the internal build, it will be in this Friday's build for the public release :)

**Comment by casigus** [comment]
woooooo. superb.
