### ISSUE TITLE
GG Max - Suggested Feature - Remember Edit Settings parameters and view Collision modes in Edit mode

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1816]
Every time you use Max, you have to go back to Edit -> Settings to set parameters, because Max doesn't remember them. Ideally, these settings should be stored in a simple config.ini file

Currently, when launching Max, I have to go to "Settings -> General", to disable "Auto Flatten", then to "Developer" to enable the "Show Additional Developer Options", since that is the only way to access the "Render Physics Shapes" option in the TestLevel, to control the collision modes.
![RenderPhysicsShapes](https://user-images.githubusercontent.com/96718175/150673318-8a16df78-e137-40d4-aaac-a73969ac3f93.jpg)
Ideally, the "Render Physics Shapes" option should be accessible in the TestLevel without checking anything, but also (if possible) in Edit mode, **for the selected object only.** This would make it possible to check collisions without having to test the Level. I don't know if it's a possible thing, but it would save us precious time.
![ShowAdditionalDeveloperOptions](https://user-images.githubusercontent.com/96718175/150673323-2248d01d-3062-4db1-bfbb-4e88628476ba.png)
I propose a visual control of collision modes in Edit mode for easier and faster control.
I hope it can help.

**Comment by ZakJudges** [comment]
Hi @UltraVox001, if you set superdevelopermode = 3 in setup.ini, the physics shapes should be available to render without having to enable the setting. The current implementation isn't really suitable for large levels as it is very slow. I agree viewing collision shapes per-object in the editor is a good idea. I shall mark this as an enhancement and the team can take a look after early-access :)

The problem with the auto flatten checkbox at present is that it does not accommodate cases where some levels have auto-flatten and some do not. So this will likely be replaced in the future with a better solution
