### ISSUE TITLE
deadlineeeeeeeeeeeee

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1818]
The dead line for the demo entry is the 30th.

Ive been working very god dam hard to push something out of my sleep deprieved brain,

it has been a battle up hill because every 
single time I try to test a level.

this.

![image](https://user-images.githubusercontent.com/68471279/150739577-13765fbe-9e60-4d65-a4d0-35609ec803db.png)

how can I get it done and in before the 30th with this. its got worse with the last two updates.

**Comment by LeeBamberTGC** [comment]
@casigus The crashes are not your fault. Please do submit what you have prior to the deadline as there will be some small-time for refinements for those that show promise.

**Comment by casigus** [comment]
thanks lee. too many sleepness nights here trying to get this done.

**Comment by casigus** [comment]
*sleepless
