### ISSUE TITLE
Pixelated Palm Tree

### ISSUE THREAD

**Issue by littleisland** [TheGameCreators/GameGuruRepo#182]
Hi, with GameGuru build 2018.04.17 the "Palm 01" entity of the "foliage" folder looks much more pixelated now. Please have a look at the picture below.

![grafik](https://user-images.githubusercontent.com/38508205/38958105-91c00f06-435c-11e8-85a7-d2c79061e205.png)

Notice the bright interrupted edges of the palm tree leafs. The effect is also boosted due to the fact, that the palm tree is animated and because of this, the bright artifacts are "wandering" while the leaf is moving. This issue also applies to some other trees and foliages delivered with GameGuru.

Some idea how to resolve this?

**Comment by LeeBamberTGC** [comment]
Seems this has been fixed with more recent tweaks to the rendering system (attached)
![image](https://user-images.githubusercontent.com/35840583/60193329-5ea0eb80-982f-11e9-818e-13613d9dac0a.png)
