### ISSUE TITLE
There should be a different message for when you try to run another GameGuru MAX and GameGuru MAX is already running:

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1824]
There should be a different message for when you try to run another GameGuru MAX and GameGuru MAX is already running:

![image](https://user-images.githubusercontent.com/1503593/150758214-3be18bad-f76a-4cea-81c6-a704f6bb7c02.png)

**Comment by rvanner** [comment]
Have this message “A copy of GameGuru MAX is already running."

**Comment by plemsoft** [comment]
@rvanner Text changed :)
