### ISSUE TITLE
Assest Tree Collection

### ISSUE THREAD

**Issue by joeydono** [TheGameCreators/GameGuruRepo#1826]
Hi, I have ticked the tree collection for download, but all that comes up is verify files. So I click that, it doesn't download anything, it just verifies gameguru . I go into the game to add trees, under the tree assets it says 0. I tried unticking the trees assets, (red X) again nothing happens., also the character creator screen is very dark!

**Comment by UltraVox001** [comment]
It's normal. TGC discovered that trees were causing Max crashes. They removed them temporarily, the time to solve the problem on all the tree models.

**Comment by UltraVox001** [comment]
Here is Character Creator as it appears on my screen.
Can you post a comparison image ?
![cc](https://user-images.githubusercontent.com/96718175/150791905-2867b1f8-ec81-4204-bcfc-4834a27877d9.jpg)

**Comment by joeydono** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/7487882/150795357-00f54922-975b-4721-908a-fa937844e173.png)

**Comment by UltraVox001** [comment]
You have found an interesting issue that is worth reporting. :) This only happens with a very dark map where some settings have been turned off. To fix this, click on the "Environment Effects" icon (top right), then increase the "Sun intensity" and "Exposure" sliders.

**Comment by rvanner** [comment]
I had a similar issue. This image is taken after the Character has been made. You can see the bright lighting around the character and even the solar flare effect in the icon.

![image](https://user-images.githubusercontent.com/1503593/150933350-f2af998c-e1ef-4085-8fd8-0ef8cb42a15d.png)
