### ISSUE TITLE
Zombies not retaining settings when spawned by trigger zone

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#1827]
When the zombies spawn in at the very start of the level the settings work but when you use a trigger zone to spawn them in they are set to default settings. I have attached a video to outline what I mean.

[https://www.youtube.com/watch?v=Az4mZ-sQVaY](https://www.youtube.com/watch?v=Az4mZ-sQVaY)

**Comment by UltraVox001** [comment]
You are right.
This issue has been reported before, and a TGC developer is working on it. Still a little patience. :)

**Comment by LeeBamberTGC** [comment]
@42Pix3ls Yes this report was commented on in the other issue. Best to report only one issue per post. Some users cram several issues into one issue naughtily, and in this case we seem to have a duplicate and it's probably a good idea Lee does not have to type his identical replies multiple times :)
