### ISSUE TITLE
demo part 2 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1828]
TRYING to make a demo.

every time I save my progress, some of the sound zones and trigger zones stop working in test mode.

this is my 3rd attempt and making a new map.

![image](https://user-images.githubusercontent.com/68471279/150891101-b2506c6e-fda1-449c-860d-3eb0a0086561.png)

ive SPENTT everyday since thursday trying to get this demo to work.

Its impossible. 

What the f**k is going on here? why is saving causing the trigger zones to just NOT work.

:( I've had enough. Gonna give it one more day then im done with testing max, its begining to get me realy pissed off.

Also regarding the state of max atm, the demo deadline needs to be pushed back so everyone has the chance to make a working demo and have it sent in.

otherr wise itts just impossible.

**Comment by Granada1** [comment]
That sort of language and attitude will get you no where

**Comment by rvanner** [comment]
@plemsoft Could you have a look at this? Seems to very frustrating for @casigus in making his game and if it can be fixed easily it would benefit everyone.

**Comment by plemsoft** [comment]
@casigus I cannot see from the picture what is wrong , could you e-mail me your level (.fpm) and let me know what zone is not working and what its supposed to do , i will then have a look if im able to see anything. e-mail: plemsoft@plemsoft.com
Thanks for your help :)

**Comment by plemsoft** [comment]
@casigus Did not get a e-mail from you, did you sent it ?

**Comment by casigus** [comment]
things are very much more stable with the new build :)
