### ISSUE TITLE
Shadowing and shading on weapons

### ISSUE THREAD

**Issue by corrosionsting** [TheGameCreators/GameGuruRepo#183]
Holding weapons, with entity shading at anything lower than high, shows no shadows or light on the hands, they just look very dark.

**Comment by LeeBamberTGC** [comment]
Can you post a screenshot of a specific weapon with TAB TAB open so we can see the settings, thanks.

**Comment by plemsoft** [comment]
This was a problem with "pbroverride=0" and medium not having any shadows , this has been fixed in the latest Public Preview.
