### ISSUE TITLE
Max Spotlight Brightness Bug

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#1830]
There is a bug, where spotlights some distance from the player appears brighter than it should before dimming to the correct brightness when the player gets closer to the spot light.

This is a major game breaking issue

https://youtu.be/Du2cyvPAPsU

**Comment by UltraVox001** [comment]
Yes. Theoretically, you should see this bug on all lights, without exception. It's just a matter of distance. I've been waiting for a fix for weeks...

**Comment by ArgentArts** [comment]
Ahhhh ... the lighting bug ... still there ... still there ... sigh ... ;)

**Comment by plemsoft** [comment]
@wizardofid29 Thanks for reporting this issue, I added some extra shadow lights, so you should not run out (and see the effect from the reported issue). ready from the next build.

**Comment by wizardofid29** [comment]
Thanks will give it a go and revert back and close

**Comment by UltraVox001** [comment]
@plemsoft 
> Thanks for reporting this issue, I added some extra shadow lights, so you should not run out (and see the effect from the reported issue). ready from the next build.

I hope you are right.
Because it becomes urgent : [Urgent Light Issue Video](https://www.youtube.com/watch?v=i75Oq8Mkcjc).
