### ISSUE TITLE
GameGuru Max Issue with background apps

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#1831]
There is an issue with gameguru max becoming unstable and often crashing with background 3D and 2D apps running.

Example gameguru max, does not like when bandicam is started after gameguru max, same applies to similar apps and 3d apps.
In the case of bandicam it needs to be started before max, otherwise, gameguru max just flat outs hangs when you try to run test game and it is true for a lot of video capturing apps and other 3d apps started after gameguru max.

**Comment by ZakJudges** [comment]
Hi @wizardofid29, apologies for the late response! I have not been able to reproduce this. However, since this issue was created, there has been some work on the Windows message handling loop, so it is possible that it is already fixed.

Do you continue to experience it in the latest builds?

**Comment by wizardofid29** [comment]
Yeah whether or not it is still there in isolated instances IDK, considering this was reported over a year ago. ? One would think a "high" label app crash bug would have received the necessary attention and closed ages ago @LeeBamberTGC.

But to confirm, works fine now with various 3D and 2D apps, like photoshop, max ect.
