### ISSUE TITLE
Make a mountain level with grass but test game has the filter turned off

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1835]
I made a mountain level and turned on grass. Looked okay in the Level Editor but when I ran test game it was turned off. Should be on if that is how I designed it from the Terrain Gen.

![image](https://user-images.githubusercontent.com/1503593/151047226-701fb851-e237-4f3b-9415-f050f1a6a932.png)

**Comment by OldFlak** [comment]
Yes, idk - I thought that as well - at first. 
But having the checkbox makes sense as does having to enable/disable it. Same as we do with the boundary markers.

It is a great idea for testing levels - there are times when I don't want grass enabled in test game.

So how would the editor know if I don't want it to show in test game - it would just introduce more needless clicks to the UI?

**Comment by ZakJudges** [comment]
@rvanner This relates to the work I carried out last month. "Level" view options now control the visual settings that are saved to the .fpm files whereas "Editor" settings only control visuals whilst editing and are temporary. When you first load a map, the Editor settings will default to whatever was saved in the visual settings.

If you like, I can free up some space and rename the "Level" column to "In-Game" or something like that to make the distinction clearer :)

**Comment by plemsoft** [comment]
@rvanner This was related to another issue, and was caused if you used the checkbox inside "Grass Painting" , this has been fixed and will be in a later commit later today :)
