### ISSUE TITLE
Enemy AI

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1836]
You can walk and run up to the back of an Enemy and barge into them but they don't react.

Max should let you;

- Walk slowly up to an enemy and melee them from behind (sneak attack)
- If you run at them they should hear you from say 5 meters away and turn to take you on

**Comment by LeeBamberTGC** [comment]
@rvanner Uses the Make AI Sound system to emit sound events when walking and louder ones when running. When in crouch mode, no sounds are emitted allowing the player to sneak up to the character.
