### ISSUE TITLE
So many bugs... please test more next time before releasing a major "update"

### ISSUE THREAD

**Issue by corrosionsting** [TheGameCreators/GameGuruRepo#184]
The update has a lot of good things, but honestly, a lot of these bugs are kind of inexcusable... please in the future, just test a little more before releasing...

**Comment by corrosionsting** [comment]
This is just so frustrating having to undo and redo a bunch of stuff on work that I've already completed. Having to go back to alter each and every map and such to fix bugs now occurring.

**Comment by corrosionsting** [comment]
I don't even think I can use the update...

**Comment by jbthenext** [comment]
GitHub Issue Tracker is for tracking bugs only, for discussions please use the forum.
