### ISSUE TITLE
GGMAX - Product Improvement Request

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1841]
The current control of files/folders for a project is i presume leftover from previous Gameguru iterations.
If possible for a cleaner control of game projects so the scripts, objects, etc are contained within the projects area can we get the game folders generated/created underneath the game projects name when a project is created. (example image)
![alternate](https://user-images.githubusercontent.com/95015657/168048490-72c9578d-673b-4e60-aa10-0b7e953c959b.png)
All this means is change the GameGuruMAX folder name to the project name

**Comment by Necrym59** [comment]
Also the Terrain and Object Buttons dont really belong way over the left hand side of the app they should reside closer to the other right hand side icons. 
![Option](https://user-images.githubusercontent.com/95015657/151080484-584366a6-df6d-4785-92a9-7809b374b518.jpg)
Also as they only activate the edit tabs for Terrain or objects they could almost be done away with if terrain or object edit tabs are selectable as in the possible options below
![Option1](https://user-images.githubusercontent.com/95015657/151080566-efa66408-19fb-41ea-b139-f8304a791046.jpg)
![Option2](https://user-images.githubusercontent.com/95015657/151080576-a498da80-572a-4ee7-8ebf-6e3ca354a8bf.jpg)

**Comment by Granada1** [comment]
Agreed 👍

https://github.com/TheGameCreators/GameGuruRepo/issues/1794

**Comment by rvanner** [comment]
At this stage we would not want to be changing the folder structure. It could delay our launch plans and cause all manner of issues.

The UI will not be changing from its current layout for Early Access. We will consider this for a future update though.

**Comment by Granada1** [comment]
`The UI will not be changing from its current layout for Early Access. We will consider this for a future update though. `

good news 👍

**Comment by Necrym59** [comment]
No problems i understand the intricasies of the product deadline no point introducing new dramas. It is ok for now, especially for single projects but it would be worth looking at in the future to look at the project system structure as its flawed layout will lead and is already leading to problems when developing multiple projects. As for the UI thats ok it was just a future idea.

**Comment by OldFlak** [comment]
I would say delay the launch and implement proper Project Folder system, atm MAX's housekeeping under the hood is pretty messy as it is :)

This is one of those areas that needs to be done right **before going to V1**, as it will lead to a ton of broken projects if it is changed later, or we will be stuck with the mess it is now for MAX's lifetime.

**Comment by LeeBamberTGC** [comment]
@OldFlak See other issue for movement on this feature: https://github.com/TheGameCreators/GameGuruRepo/issues/2349

**Comment by LeeBamberTGC** [comment]
P.S. For V1 you only get FIVE:

![image](https://user-images.githubusercontent.com/35840583/219093192-6091110b-2dcd-43e1-ad76-50f6a13dc705.png)
