### ISSUE TITLE
 Max player animation speed bug/issue

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#1844]
There might be a engine timer and player animation issue when FPS drops down to 40- 30, player animation seems to be directly tied to FPS, when the FPS drops so does the player animation speed, that includes running speed as well, which results in mirco stuttering.

**Comment by LeeBamberTGC** [comment]
@wizardofid29 Player footfall sounds and HUD model animations now FPS speed independent.
