### ISSUE TITLE
GG Max (internal) Bug Report - The vegetation has completely disappeared (UI + Map)

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1847]
Screenshot :
![NoVegetation](https://user-images.githubusercontent.com/96718175/151235767-52e5901f-2095-4ae1-9ba2-8f91f1f2abed.jpg)

**Comment by rvanner** [comment]
@UltraVox001 Yes this is due to Lee not syncing with Paul's recent changes. Should be fixed later today in a new internal build. Best not to report these here. Please just email Lee directly on internal build issues please.

**Comment by UltraVox001** [comment]
@rvanner 
Oh! Yes I understand.
Sorry, internal system is new to me.
