### ISSUE TITLE
GG Max (internal) Bug Report - Strange spheres appear in empty maps

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1848]
Strange spheres appear in empty maps, in Edit mode and TestLevel.
They are not selectable.
2 screenshot : 
![spheres1](https://user-images.githubusercontent.com/96718175/151238828-25a92dca-dd4c-4a8b-89b2-f2e25dcae8b1.jpg)
![spheres2](https://user-images.githubusercontent.com/96718175/151238842-9b949243-3359-4946-9a2f-3bea71d478ef.jpg)
And a brain on the ground :
![Mind](https://user-images.githubusercontent.com/96718175/151239730-262ac856-b334-4ac4-9ff2-e38af0f1527e.jpg)

**Comment by rvanner** [comment]
@UltraVox001 Again this is an internal build issue. Lee knows and a fix is coming.
