### ISSUE TITLE
Shooting guns on some maps with the terrain flashlight bug

### ISSUE THREAD

**Issue by corrosionsting** [TheGameCreators/GameGuruRepo#185]
causes terrain to flash white

**Comment by LeeBamberTGC** [comment]
Can you provide a step by step of how to see this issue, which entities you drop in, which gun? Thanks.

**Comment by corrosionsting** [comment]
Seems to be any gun. Just once in awhile with the flashlight not showing on terrain and when you shoot, the terrain flashes white

**Comment by LeeBamberTGC** [comment]
Cannot reproduce with latest version.
