### ISSUE TITLE
Zombie issue still exists 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1850]
Constantly still getting emails and posts about this issue which i thought had been fixed or its back.
Any chance it can be checked in the latest GameGuru Classic Build :)

In / scriptbank / ai /module_combatmelee.lua 
Line 64 is:
module_core.debug(e,AIObjNo,PlayerDist,combattype)
Should be
-- module_core.debug(e,AIObjNo,PlayerDist,combattype)

![Z1](https://user-images.githubusercontent.com/35708217/151262479-b608a33a-0f75-43e3-a357-68a4aad33c6f.png)

**Comment by rvanner** [comment]
@plemsoft Could this be quickly patched?

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed for next Classic beta
