### ISSUE TITLE
MAX - Skybox Renders Over Terrain

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1852]
These issues still happen in current build
Seems to be related to fog, because the more fog you have in the scene the more the skybox overlays everything

**As posted on Discord:**

**BUG 2021.01.14 - Skybox Render Issues**
Skybox is reflected across terrain as if it is water
![image](https://user-images.githubusercontent.com/12246318/151291004-818e31d2-b550-4e48-86f3-f91d59c63d7f.png)
It also overlays interiors of buildings
![image](https://user-images.githubusercontent.com/12246318/151291026-91d3fe6b-a050-4c01-b7bb-7a859b70f942.png)
This one shows issue in outside levels much better
![image](https://user-images.githubusercontent.com/12246318/151291084-06a11e6e-d161-4941-b759-a0e8d3f6f387.png)

**BUG 2022.01.14 - Fog Contributes To Sky Box Issues**
As reported the skyboxes overlay the terrain - fog seems to be contributing to that issue?
- here you can see the fog is more reflective that the water
https://youtu.be/ZlZhzhh4R00

**Comment by OldFlak** [comment]
@PaulSJ - Email sent :)

**Comment by plemsoft** [comment]
@OldFlak Fixed in another issue :)
