### ISSUE TITLE
MAX - Terrain Generator - Biomes

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1855]
Actually not a fan of the biomes in the terrain editor, it makes too much of a drastic change even to heightmaps

I would rather mess with sliders and get the look I want then just select the biome textures I want

The way it works now is your map can only be one type of biome - what happens when I want my forest map to be covered with snow

**Comment by smmaas** [comment]
I would remove biomes completely from the terrain editor en have a biome painter in the editor. Select trees, vegetation, texture and maybe some objects/animals  and start painting. This would be far more flexible and it would be an easy way to have different biomes in one level.

**Comment by rvanner** [comment]
For now this is how it works. Longer term we can add more features and make it do more. Closing this now.
