### ISSUE TITLE
MAX - Terrain Generator Time-of-Day Annoyance 

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1856]
When creating terrain, selecting different biomes keeps changing the time of day 
- it would be more user friendly if it only changes when the user selects a different time-of-day option
- most of the time you have to select the time-of-day again so you can see the terrain

**Comment by rvanner** [comment]
For now this is how we have designed it. We want new users to see different possibilities.

**Comment by OldFlak** [comment]
Can we have a checkbox then? Completely annoying as it is :) 
Just lots of needless clicks....

**Comment by rvanner** [comment]
Check box is now in the latest build!
