### ISSUE TITLE
MAX - BUG 2022.01.21 - Skybox Jiggles

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1857]
Skybox jiggles as player walks
Just ran a standalone from previous build and the skybox jiggles in that as well - so quite possibly been there for some time now

https://youtu.be/4UadPWAG_gw (edited)

**Comment by plemsoft** [comment]
@OldFlak Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment]
@plemsoft Exciting to see what the fix to this one was :)
