### ISSUE TITLE
MAX - BUG 2022.01.21 - Pine Tree Texture

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1859]
Pine Tree Texture still Not Good
- happens at base of every instance of tree
![image](https://user-images.githubusercontent.com/12246318/151293646-6263ccb4-bc73-4047-9633-7714c4ab2a5e.png)

Also lots of places where parts of leaves are are not joined to branches
- looking at the texture for it they should look good
- UV issue?
![image](https://user-images.githubusercontent.com/12246318/151293672-1b8810fc-e1fb-4252-a86d-d3aee2db8a20.png)

**Comment by rvanner** [comment]
This was due to the system not showing the highest LOD versions. You will now see high poly trees when you are close up to them.

**Comment by OldFlak** [comment]
Nice main trunk and branches look great now.

Base still not good - perhaps need to plant them deeper?

**Comment by rvanner** [comment]
I think that looks acceptable now. I'm closing this issue.
