### ISSUE TITLE
Problem with the feet-step sound's - GAMEGURU DX11 17-04-2018

### ISSUE THREAD

**Issue by ghost** [TheGameCreators/GameGuruRepo#186]
I found a problem with the feet-step sound's, even play with the setting the result isn't like dx 9.

Video for example: https://youtu.be/4N536r4_HBo

**Comment by LeeBamberTGC** [comment]
Will look into why TAB TAB causes footfalls to increase in speed

**Comment by ViperSmoke** [comment]
It seems like a fps' problem, 'cause on my computer I have 144 FPS and I set the optimal setting for 144 fps, the step sound is correct but if someone else play at 60 fps on another computer, the step sound is wrong and more speed.

(sorry i do not speak english very well)

**Comment by LeeBamberTGC** [comment]
We modified the footfall system since last year and this seems to be fixed. The sound of first and third person characters running on various materials seem now to be in sync with different FPS rates
