### ISSUE TITLE
MAX - BUG 2022.01.21 - Light Editor Issues

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1860]
Yet another FYI for editor issues
MAX says the light is at angle of 270, but he is not sure if you really wanted that.
![image](https://user-images.githubusercontent.com/12246318/151293762-bbc24e1d-0ec1-498c-be3a-0325a0f08565.png)

So to fix you have to type 270 again 
![image](https://user-images.githubusercontent.com/12246318/151293823-aefa339e-b5e4-47cc-ba73-1fb21606ac25.png)

**Comment by ZakJudges** [comment]
Hi @OldFlak, thank you for reporting this issue. I could not reproduce it since fixing #1775 

Could you confirm if you still experience the issue after updating later this week? Thanks :)

**Comment by OldFlak** [comment]
@ZakJudges - Yes fixed it seems - thanks for your great work :)

Been playing with lights a fair bit over last few days and have not seen the issue in any 2022.02.18 builds 
- so I think it is safe to close issue
