### ISSUE TITLE
GG Max Suggested Feature - Texture Transition effect (Edit Mode)

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1862]
The difference between the texture transition made by the terrain generator (on the right), and those of the textures applied manually (on the left), is visually far too great. The transition is too abrupt on the left. Since this transition setting exists in GG Max, just integrate it above the texture palette (in the Painting field). It would make the grounds/terrains much more beautiful.

On this screenshot, we immediately understand the problem and we believe we are viewing a game from the 90s. Max is better than that. :)
![TextureTransition](https://user-images.githubusercontent.com/96718175/151300130-2549e767-e2fb-4ef1-b3da-8a7a7152648b.jpg)
Viewed from a nearby small hill, it's even worse.
![TextureTransition2](https://user-images.githubusercontent.com/96718175/151303881-21cd0604-eea5-4c9c-b70a-5a0e876509b9.jpg)

**Comment by smmaas** [comment]
Not only the textures but the water is not very realistic.

**Comment by UltraVox001** [comment]
@smmaas 
This is a ground texture test map.
Water doesn't matter.

**Comment by smmaas** [comment]
Does this look like water? Where it does matter

![image](https://user-images.githubusercontent.com/45684694/151380313-339003f5-9875-4abc-b93f-a35e5585ae2c.png)

**Comment by UltraVox001** [comment]
@smmaas 
If you don't like the water, ask for new water. But don't use a stream dedicated to soil textures to talk about water. The two systems are completely different and use unrelated materials.

**Comment by smmaas** [comment]
No it is a stream about games looking like games from the 90s

![image](https://user-images.githubusercontent.com/45684694/151421015-8e65c6b5-ee80-40d4-9a2f-a97dfbdee6f7.png)

**Comment by UltraVox001** [comment]
What do you read in the title of this post ? --> ”Texture Transition effect”
TGC won't process your water request, because you're posting it inside a Ground Textures Post.

Make a separate request for water.

**Comment by rvanner** [comment]
There are plans to allow users to change when these transitions happen. This will be a post Early Access feature though.
