### ISSUE TITLE
MAX - BUG 2022.01.21 - Sun Rays Do Not Originate From Sun Disc

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1865]
Sun rays do not always originate from the sun disc position when using both Simulated  and Skybox

Using Simulated Sky: 
All seems fine on first run - change settings and it gets messed up
This pic is set to Morning
![image](https://user-images.githubusercontent.com/12246318/151322634-7ff24f58-486c-4fa4-9285-5b37da1cc7c2.png)

Using Skybox:
Never originates from correct location
This pic is using Cloudy
![image](https://user-images.githubusercontent.com/12246318/151322729-e396c173-dae4-40ee-af81-52f96602c103.png)

It seems that the rays are originating from tree branches and sometimes from simulated clouds.

**Comment by plemsoft** [comment]
@OldFlak Tried both here , and they seams to line up ok here , so what settings are you changing ? :)

![rays-sun](https://user-images.githubusercontent.com/18662417/152325316-474063d9-f7ec-4e55-932a-ca776e37011a.jpg)

**Comment by OldFlak** [comment]
@plemsoft 
Hi Preben - I used Morning settings for Simulated Sky
You may need to wander around the map a bit, after a while seams to go all wrong.

The current build is bugged and MAX won't run levels for me atm (just crashes to desktop running test game) when he get up and running again I will do a vid with a stock map :)

**Comment by OldFlak** [comment]
@plemsoft managed to reproduce 

Sent email with current pic and a level to hopefully help you find it :)

**Comment by plemsoft** [comment]
@OldFlak Thanks , i was able to reproduce it and fixed it , ready from the next update :) , not sure if Lee will merge anymore today, but then in next weeks build.

**Comment by OldFlak** [comment]
I be confident Preben has fixed the issue, but have not been able to test and confirm this is fixed or not.
Checked for updates but not seeing any?

**Comment by dllllllllllb** [comment]
@OldFlak I tested this issue on Friday and the rays weren't originating from the sun as you described. Yesterday we had an update which fixed this issue for me (Tested this on the same map), so I closed it :] If the issue persists on your end please let us know, I'll keep an eye on this.
