### ISSUE TITLE
MAX - BUG 2022.01.14 - Duplicating Lights

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1866]
Duplicating lights is broken - not useful at all as it is.

The way it works now, you simply can't duplicate a light because it will not stay in the position of the original
- this means you have to create each light individually even if you want several with exact same properties
- also when you click a light it usually thinks it is some kind of morph
- need off switch for smart placement - mostly it is the opposite

**Comment by LeeBamberTGC** [comment]
@dllllllllllb For this one, let's start simple and gather more information as we go along. First ensure that when you select an existing light in the level, and then use the CURRENT OBJECT panel (bottom left) to duplicate the light and drag it into the scene, it shares the SAME properties as the light being copied.

If the user is in the HORIZONTAL POSITIONING MODE for the object, retain the lights Y position so you can copy the height of the original light as this would be very useful. You might need some help from me on locating the right code for this.

We can then dive into the other ways of duplicating objects (like CTRL+C then CTRL+V) as once we have duplication working fine we can extend it to other methods.

**Comment by OldFlak** [comment]
Can we just have an Off switch for smart mode 
- both lights and normal objects are made frustratingly difficult because of it

See #2215

**Comment by dllllllllllb** [comment]
@LeeBamberTGC When you drag light from the bottom left corner, it has the same properties but Horizontal Only Mode is not applied and you can freely drag the light in all axis. I researched how the light is added to the scene and came across AddEntityToCursor(), looked more into it and found that there are no checks for iObjectMoveMode == 0 in there, although I'm not entirely sure if this is where positioning of the light is determined. I need some help locating the code :)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb This one (like #2215) delves more into the object placement system so I will assign myself this one and tackle both issues in one go.  I will assign a few more from my list to you.

**Comment by OldFlak** [comment]
Just to update - current EXP still has the same issue - lights are extremely cumbersome to clone, it is just as east to create a new light every time.

Actually, it is cumbersome to clone any object and expect it to remain at same height.
