### ISSUE TITLE
levels "merge"

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1868]
When having more than one level in one project they start to interfere with each other. I find objects from one level popping up in an other level. Creating a new level trees only appeared at areas where in an other level is water! 

![image](https://user-images.githubusercontent.com/45684694/151347121-40ca701f-8b89-4761-b42b-98ba0af9d9f1.png)

![image](https://user-images.githubusercontent.com/45684694/151347446-229e7166-6d53-496f-8bd6-f3300639a708.png)

**Comment by UltraVox001** [comment]
Nice bug!
Did you open both maps, one after one ?

**Comment by smmaas** [comment]
Sorry I was. It are two levels in different projects. Edam3d is a project I've been working on for some time. Test is the project with the problem. I tried it a few times. The problem did disappear after creating a new level 3 times but came back after I had openend edam3d again.  Restarting gmax didn't help.

https://vimeo.com/670832693

**Comment by Necrym59** [comment]
I beleive that these project issues will continue to grow as no designated specific project folder is generated or used to isolate a project, i have reported it as an issue for the future to be addressed, multi projects assets are all dumped in together at the moment.

**Comment by smmaas** [comment]
I agree, the game save folder should be an project setting and not a global setting.

**Comment by synchromesh62** [comment]
**I agree, the game save folder should be an project setting and not a global setting.**

Thats not why GameGuruApps is updated and backed up.
New things are added, reshuffled ( not every time ) but for example if Preben updates the Storyboard Or Lee swaps some files around then this may require a new GameGuruApps to be up to date.

Look how its changed over time. There is no way just renaming the old one would work properly now.
Older
![GA1](https://user-images.githubusercontent.com/35708217/151460633-1cbd9969-8cf2-4760-b380-d800e7ea36bf.png)

Newer
![GA2](https://user-images.githubusercontent.com/35708217/151460653-4f4edcc5-a68c-4364-bf77-389b3fb65bf4.png)

**Comment by plemsoft** [comment]
@smmaas Thanks for reporting this problem , this has been fixed and will be in next Friday build :)

**Comment by smmaas** [comment]
looks good!
