### ISSUE TITLE
entity_animate64.fx

### ISSUE THREAD

**Issue by demented-mind** [TheGameCreators/GameGuruRepo#187]
I ran into this problem when I used Bolt Action Gaming's rainbox, snowbox, and sablemars weather items. It is rather easy to duplicate; although it is a 3rd party entity. This is why I placed my comment/concern in his post. So, once it is in GG and you select "weather_TOD_example2.fpm" as shown in the following image . . .
![game guru - - terrain editing mode 4_18_2018 4_46_35 pm](https://user-images.githubusercontent.com/18433764/38960675-06bc187c-432b-11e8-9a98-98503fe1c119.png)

. . . as the map tries to load an error message pops up as show in image below.
![untitled](https://user-images.githubusercontent.com/18433764/38960681-0cb99952-432b-11e8-8827-e8bd2d10d885.png)

Now, you will notice that the effect file is "effect_animate64.fx." There is no blob file with this name. The only other decals that use this effect file is the free version of the rainbox (either V2 or V4). It also crashes with the same error message. It seems to me this should be an easy fix as DirectX is telling us exactly what is wrong; if only one would look at the image. So, I will give you what it says as text:

> Failed to load the shader 'effect\reloaded\effect_animate64.fx'. **All Game Guru shaders** need to be **HLSL level 5.0 or above.** 

Do you think this needs to be updated to level 5.0? I don't know how to do it.

I then changed the parameter of forceloadtestgameshaders from "0" to "1". This didn't work and gave me this message:
![d3dx11compilefromfile failure 4_18_2018 5_30_44 pm](https://user-images.githubusercontent.com/18433764/38961579-c86e1454-432e-11e8-92d7-ed7264579049.png)

I don't understand why this so difficult for somebody to figure out and fix?

**Comment by Pirate-Myke** [comment]
He wrote in a post on the main forum to assign the FPE file the decal_animate64.fx shader, and they should work again. He is in the middle of updating them.

**Comment by demented-mind** [comment]
Thanks Myke, that works. However, do you know how to get rid of the dark shadow that's on the ground below the rain decal?

**Comment by corrosionsting** [comment]
I already posted this and pirate myke fixed my issue. Try reading through closed threads
