### ISSUE TITLE
Switch can be activated through walls

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1875]
Big red button switch can be activated from behind and through walls:
![switch](https://user-images.githubusercontent.com/32545391/151538871-60f18028-1c0c-4f4d-8ffb-68fc571b2953.png)

**Comment by UltraVox001** [comment]
Yes, I have already talked about it [here](https://github.com/TheGameCreators/GameGuruRepo/issues/1770).
