### ISSUE TITLE
AI and Nodes issue.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1876]
Initially i though this maybe part of the WIP but been there a while now.

This is a basic setup

![AI1](https://user-images.githubusercontent.com/35708217/151550601-f4b8fb86-1ae7-4cd4-8154-c31e74d933a8.png)

When connected a brain appears on the floor and can be seen ingame and stays if you reload the map

![AI2](https://user-images.githubusercontent.com/35708217/151550758-ec9c23a7-cee4-4df0-9c83-e1aed32a1504.png)

![AI3](https://user-images.githubusercontent.com/35708217/151550788-80b0afd4-9202-411a-8262-2cabdf222e64.png)

Finally if you add a new start marker the old node stays again visible in game

![AI4](https://user-images.githubusercontent.com/35708217/151550862-024cb6d9-f16b-4af1-a578-2855367e1066.png)

**Comment by UltraVox001** [comment]
This brain spawns on the ground in all empty levels (with or without AI). I reported it to Rick. There are also about ten spheres, not too far from the brain. Above the ground, about 10 meters above sea level.

**Comment by synchromesh62** [comment]
**"There are also about ten spheres, not too far from the brain. Above the ground, about 10 meters above "terrain".**
Thats already been fixed. 
The Brain has only ever spawned for me when i connect Nodes

**Comment by UltraVox001** [comment]
Ok I haven't checked since yesterday.
I'll look right away.

**Comment by UltraVox001** [comment]
During the creation of the "terrain".
![1](https://user-images.githubusercontent.com/96718175/151557417-e9a1c649-6986-4929-ab1b-de940dda4b1f.png)

After creation.
![2](https://user-images.githubusercontent.com/96718175/151557429-34163ac8-fd6f-404a-8795-f3d7cb4ec74a.png)

**Comment by synchromesh62** [comment]
Havent seen that one before.
Just rechecked and not seeing it now anyway .. Weird

**Comment by UltraVox001** [comment]
He hides well :)
You have to look for it, a little.

**Comment by ZakJudges** [comment]
@synchromesh62 Are you still experiencing this problem with the latest iteration of the visual logic? :)

**Comment by ZakJudges** [comment]
@synchromesh62 I couldn't reproduce it. Is there any chance you have a map that shows the issue? :)

**Comment by UltraVox001** [comment]
I see it too. He is present in the first second of this video made this morning. (this video is fake problem, solved.)
[https://www.youtube.com/watch?v=pQspA0pyALs](https://www.youtube.com/watch?v=pQspA0pyALs)

**Comment by UltraVox001** [comment]
Hum, I just re-opened the map I'm talking about. But he is no longer there.
Update from Max today at 1:35 p.m.

**Comment by ZakJudges** [comment]
@UltraVox001 Thanks for the extra info. 
@synchromesh62 Do you also see this issue fixed after updating today?

**Comment by ZakJudges** [comment]
Hi @synchromesh62, just wanted to check this is fixed for you? :)
