### ISSUE TITLE
Need a New Simpler pickupsimple behavior

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1879]
First thing i noticed today was my Custom Pickuppable scripts no longer function correctly and objects im carrying go right through the walls But fair enough they are my Custom ones. However i also found it seems to have effected the stock version as well.

If you attach the stock **pickupsimple** to an object then run test game it sinks into the floor and does not function correctly 
Video supplied. 
https://youtu.be/zeiQcn2TcmQ

**Comment by AmenMoses** [comment]
Probably same issue as #1806

**Comment by LeeBamberTGC** [comment]
Made a simplification to keep this script working. Needs a proper investigation by the original author, seems that there is a feedback loop happening on the position values causing the final object position to spin off in an erratic fashion. May be caused by newer terrain height values, or incorrect ray casting of terrain (if any), or pos.rot values not being updated by physics system.

**Comment by AmenMoses** [comment]
Original script works perfectly in Classic and as I can't actually see what has changed in MAX there is no way I can investigate!

Putting the proper script in MAX and trying it then just placing an object on the terrain causes it to sink through the terrain when the script is doing nothing.

Placing pickuppables on a 'floor' and they behave better, i.e. they can be picked up, manipulated and dropped but stacking no longer works, it's like something in the engine is fighting the script which doesn't happen in Classic.

**Comment by AmenMoses** [comment]
Right so with todays build the proper pickuppables script (i.e. the Classic one) works except for stacking, i.e. the objects no longer sink into the terrain. Pick up, throw, rotate all works fine.

So there is still something amiss in the engine that is fighting the script but for single item manipulation all is good.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Can you attach the script you are happy with, just in case the one I might use differs, thanks!!

**Comment by AmenMoses** [comment]
I'm happy with the one in Classic!

**Comment by LeeBamberTGC** [comment]
Alas the 'pickuppable.lua' script from the latest Classic is not compatible with the new MAX DLUA system for behavior description and properties.  I will remove "pickupsimple.lua" for now and add a new issue to create a simple one once I have got through a few more of my issues list :)

**Comment by LeeBamberTGC** [comment]
Now handled in the largest of the pickup issues reported and most populated: https://github.com/TheGameCreators/GameGuruRepo/issues/2848#issuecomment-1100489547

**Comment by davetgc** [comment]
My thoughts are that we should drop the script entirely and have a player option to allow pick up and carry with a weight slider to set the maximum weight. This frees to object up to have a different script.
