### ISSUE TITLE
GGMAX - Terrain specular bug

### ISSUE THREAD

**Issue by PaulFox12** [TheGameCreators/GameGuruRepo#1880]
Specular maps of terrain really seem to be blown out in latest build (28/01/22), everything looks wet and shiny

![terrain specular](https://user-images.githubusercontent.com/78652980/151636400-7149645f-67b6-44fc-a748-1b96743bd2aa.PNG)

**Comment by rvanner** [comment]
@PaulSJ What time of day is this set at and are you using the very latest build?

**Comment by PaulSJ** [comment]
I need more details to replicate this
