### ISSUE TITLE
GGMAX - Weapons clip through objects

### ISSUE THREAD

**Issue by PaulFox12** [TheGameCreators/GameGuruRepo#1881]
Weapons seem to be clipping through objects whereas they should always render on top of everything - see image in latest build (28/01/22)

![guns clipping](https://user-images.githubusercontent.com/78652980/151636514-788458f4-aedd-4b96-8298-3922bf879cbd.PNG)

**Comment by UltraVox001** [comment]
This bug is known. It will be corrected in February.

**Comment by rvanner** [comment]
I'm closing this because it's in another report.
