### ISSUE TITLE
GGMAX - Vegetation and trees bug

### ISSUE THREAD

**Issue by PaulFox12** [TheGameCreators/GameGuruRepo#1882]
Trees are defaulting to cacti in terrain generator no matter which biome is selected, Grass also seems to fade off far to early to terrain (Which now looks very low res due to what I am assuming is texture LOD) . An ability (in developer mode if needed) to change vegetation draw distance seems essential here as 10 meters of grass around a player is woefully little.

![grass blending_LI (2)](https://user-images.githubusercontent.com/78652980/151637143-bdd3fa0f-77b7-47bb-a1ab-b3c99df7bd2f.jpg)

**Comment by UltraVox001** [comment]
I don't see anything wrong with the default trees. They are Pines.
Use the updater to check your files and let us know if it works better.

Vegetation Draw Distance can be increased, but this will also increase the distance between vegetation.
![DrawDistance](https://user-images.githubusercontent.com/96718175/151650780-d645cd07-89ad-43af-bc10-6d5413b2f783.png)
I asked the question in the last Live and according to Lee, this will soon improve.

**Comment by rvanner** [comment]
We'll be fixing this next week when we have more tree types.

**Comment by plemsoft** [comment]
@PaulFox12 Thanks for reporting this issue, this has been fixed and will be in next Fridays build :)
