### ISSUE TITLE
crashhh

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1884]
![image](https://user-images.githubusercontent.com/68471279/151641482-ab5fcfc1-39bb-4fa0-912d-7d7463191768.png)

no idea why ggmax struggles with this one level in particular (for the demo submissions) either hangs on the loading for up to 300 minutes then eventualy loads the game level or just crashes. Using mainly ggmax assets, with a few non ggmax assets but it did the same before adding any none max assets.

heres a link to the map so you can have a poke around and try and figure out whats going on.

30 minutes to load one small map seams very odd.

https://drive.google.com/file/d/1vNm3Jf2faMVfhgS8a_rjTXULvPDT0SH1/view?usp=sharing

**Comment by UltraVox001** [comment]
You shouldn't have to wait 30 minutes to do anything in Max.
Any operation only takes a few seconds, even in a map with 600 3D objects.

In your link, there is no .fpe file (the map).

**Comment by casigus** [comment]
very strange. heres the link, https://drive.google.com/file/d/1oVvxJw0ceXIauEyWPuNJmET-lCuRp63V/view?usp=sharing sorry not sure what went wrong there. Yeeah ive re-installed it many many times and its still doing the same thing.

**Comment by casigus** [comment]
Oh. I had uploaded it correctly, for some reason when uploading the fpm to google drive it splits it into this.....
![image](https://user-images.githubusercontent.com/68471279/151656199-2de8a79d-ac14-409e-8c69-037cfc450b69.png)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/151656214-f3ecd520-2b4d-4025-9cb1-6645401d0eca.png)

**Comment by UltraVox001** [comment]
Compress the .fpm file into a .ZIP or .RAR or even .7ZIP.
Then on google drive.

**Comment by ZakJudges** [comment]
Hi @casigus, the slowdown appears to be related to two things. 
Firstly, there are a lot of expensive physics objects in the level (anything with polygon, hull decomp). It's best to simplify the collision shape for these objects unless you really need them - objects like factory lights usually don't need any collision. The team has some strategies around this area planned for the future. So hopefully, we can warn users of potential performance problems soon.
The secondary cause of the slowdown is the navmesh, however, this is being actively worked on. You should see some improvements in the coming days and weeks :)

**Comment by casigus** [comment]
aye!! what baffes me is ALOT of the included ggmax assets are set to covexx and hull ducomp, for example random boxes, I'd have assumed they'd be set to be shaped accordinly, I guess that error was on my part. started changing the colisions and it does improve performance too.
