### ISSUE TITLE
GGMAX: Standalone Game has wrong map - build 2022.01.28

### ISSUE THREAD

**Issue by perovdm** [TheGameCreators/GameGuruRepo#1885]
When I save my game as standalone, it loads the incorrect map, in fact I cant remember ever creating this map. I double checked in the storyboard and it is pointing to my map, and loads it fine in the editor, but just not when making it standalone.

Storyboard:
![Capture3](https://user-images.githubusercontent.com/74854393/151645006-d101d858-0e4c-46e6-8e34-6cddb837a3cf.PNG)

This is the incorrect map
![GameGuru MAX 29_01_2022 4_00_29 pm](https://user-images.githubusercontent.com/74854393/151645060-97597a95-887c-47fa-a676-138144514995.jpg)

**Comment by UltraVox001** [comment]
Give it a try by creating a new Project and adding your map to it, then compiling with Max.
Let us know.

**Comment by synchromesh62** [comment]
Are you saving your map in the mapbank folder in GameGuruApps
Like GG Classic im going to assume it must be saved there so Max can find it when compiling the standalone otherwise it just puts a default one there instead which is what you might be seeing ?

**Comment by perovdm** [comment]
Ok Saving the level in the mapbank folder solved this issue, thanks.

**Comment by rvanner** [comment]
@plemsoft Maybe a warning with advice should come up if this happens? It's confusing for the user if the standalone game had a different level in it?

**Comment by plemsoft** [comment]
@rvanner Error has been added when you try to add a level from outside the mapbank :)
