### ISSUE TITLE
Can not remove unwanted objects from project.

### ISSUE THREAD

**Issue by dennimoto** [TheGameCreators/GameGuruRepo#1886]
Can not delete unwanted objects from "Level Objects" pane. A trash icon hovers over objects when clicked, but seems to serve no purpose. The DEL key is also ineffective to removing items from the pane.

**Comment by UltraVox001** [comment]
Theoretically, objects that are not in the map disappear from this list after closing and reopening Max.

**Comment by plemsoft** [comment]
@dennimoto The trash icon is only to delete the object attached to the cursor, if a object from the "Level Objects" is not used in the level anymore, max will auto delete then when you save the level. Hope this explains your issue , thanks :)
