### ISSUE TITLE
Terrain generator cacti auto population

### ISSUE THREAD

**Issue by dennimoto** [TheGameCreators/GameGuruRepo#1887]
After selecting the desert biome in the terrain generator, any subsequently selected biome only auto-populates with cacti.

**Comment by UltraVox001** [comment]
Ok, I confirm this bug. However, creating the terrain and choosing other trees does work.
This bug is related to another post : [1882](https://github.com/TheGameCreators/GameGuruRepo/issues/1882)

**Comment by rvanner** [comment]
This will be fixed in the next build, we have all the new trees now and will setup the biomes.

**Comment by plemsoft** [comment]
@dennimoto Thanks for reporting this issue, yes it was a duplicate and are already fixed for the next update :)
