### ISSUE TITLE
Sky box rendering in MAX not as good as Classic

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1888]
This has been reported to me by user GraPhiX 

Morning Rick,

 
Here is the test pattern in Classic https://youtu.be/PpncIr3-MdY

And the test pattern in MAX https://youtu.be/B10gRyhYTVA

These test patterns were designed to help me get locations within a skydome and to test post processing and any other FX as you can clearly see the fx used in classic must have anti aliasing of some kind the lines are not jagged

But in MAX the lines look awful.

If you add the skybox to max and turn on FXAA it does smooth out slightly but I thing another setting must be used in classic that is missing in MAX.

Kevan (GraPhiX)

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this issue , i dont see the same here, could you try this in the latest version and let me know if this is still a problem , this is what i see compared with yours. Without fxaa , sure it looks better with fxaa :)

![skybox-compare](https://user-images.githubusercontent.com/18662417/155122274-4c92a204-2961-4f90-abd8-2fc216ff74b5.jpg)

**Comment by GraPhiX-Guru** [comment]
Hi Preben yes Skybox rendering as improved in the latest version, my comparison was with Classic & MA
![gc-gm](https://user-images.githubusercontent.com/35724756/155125771-13cc911e-1765-40f3-9619-00a29282f414.png)
X
Classic on the right MAX on the left

**Comment by plemsoft** [comment]
@GraPhiX-Guru Yes looks better now , also i think the difference with the classic and max now is the missing mipmaps in your skybox, we generate those for you in classic but not in max you need to add mipmaps yourself. Anyway looks fine without , even better with fxaa , let me know if this issue can be closed, thanks for your help :)

**Comment by GraPhiX-Guru** [comment]
Thank you Preben, yes i will enable mipmaps in xSkyBox+ now that I know things are working as they should.

This can now be closed :)
