### ISSUE TITLE
Tab Tab Not opening settings panels

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#189]
Cannot seem to get the tab tab panels to open after the DX11 + PBR Update. Anyone else found this.

**Comment by GraPhiX-Guru** [comment]
Hi tarkus, its works fine for me :( sorry I know that's no help

**Comment by tarkus1971** [comment]
Thanks Graphix, I Have just found there was a Windows 10 update lurking and waiting to be installed, restarted after update and all was back again, my bad.

Solved.
