### ISSUE TITLE
Trash can attached to mouse when adding player start marker

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#1890]
GGMAX, build 28-Jan-2022, video link:
https://www.youtube.com/watch?v=uSOHVIWuv4A

BoredOfTHeRings on forums - my files have been verified- I have a 20M35 on NVIDIA GeForce GTX 1060 3GB

**Comment by redagent101** [comment]
sorry this is for GG MAx

**Comment by UltraVox001** [comment]
What happens if you "Add" an item from the Max bank ?

**Comment by redagent101** [comment]
that is ok, no issue there, I'm going to retry verifying files again and then if that fails go back to previous version and see if it was in last version.

**Comment by UltraVox001** [comment]
The trash is supposed to appear when the mouse hovers over an object already present in the list.

Does this bug prevent you from working with Max ?

**Comment by redagent101** [comment]
ok, this doesn't appear to be a bug it's part of the functionality.  I will close
