### ISSUE TITLE
GG Max - Bug Report : AI PathFinding stopped due to too long distance between AI and Player

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1891]
An AI test on guards (Patrol) around a military base : 
[Video 1](https://www.youtube.com/watch?v=YQW7_1MannQ).
[Video 2](https://www.youtube.com/watch?v=aBcJF7uU8R0).

Enemies walk through Static/Box objects, then when moving away, walk in place. The navigation mesh does not calculate anything, where it should calculate to avoid static objects. This is problematic, because the AI has to work. Besides the fact that the Character passes through objects, the distance between me and the enemies prevents Path Finding from working correctly. The patrol does not go to the second flag which is at the end of the path. The guard walks in place, as long as I don't approach him.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Go to the AI Management component (activated in developer mode) and tick to see the nav mesh. If there is no nav mesh it explains both the issues reported here. I am assigning to Paul who is working on a system to handle VERY LARGE nav meshes.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
I don't know about you, but for me no character can move.
I can't even bind the Character to a Flag.
![Nothing](https://user-images.githubusercontent.com/96718175/153653483-1fdbf116-1830-4b5c-bda6-952fded9dc05.jpg)
![NoLinkIsPossible](https://user-images.githubusercontent.com/96718175/153653632-02962e8c-e9ad-4f87-b337-d77f82ea02da.jpg)
But, many thanks for the giant nav meshs (coming soon) :)

**Comment by UltraVox001** [comment]
Problem "solved" in another way.

**Comment by UltraVox001** [comment]
@PaulSJ @LeeBamberTGC 
I have a complete map (military base), with a lot of 3D objects, on which there is no Nav Mesh. So I managed to reproduce the problem (unintentionally). All enemy Characters pass through objects that I purposely placed in their path. When I activate "AI Management", the ground does not turn yellow like with a Nav Mesh. It's strange because it worked with yesterday's update. But not with today's. On the other hand, it works on an empty map (new) with 1 Character and 2 or 3 objects. But as soon as Max is in "real conditions" (with a true complete map,) there is no more nav mesh.

If you are interested in this map, let me know.
Max internal update of 15-02-2022 (morning).

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Yes indeed, we have reproduced the disappearing nav mesh for large levels. Paul is on the case this week :)
