### ISSUE TITLE
Cannot locate exe file

### ISSUE THREAD

**Issue by rpinson57** [TheGameCreators/GameGuruRepo#1892]
I have reinstalled the program 3 times and verified files twice. I keep getting this message when I try to start the program with the shortcut of by using the exe file directly...
![Untitled](https://user-images.githubusercontent.com/98671419/151680637-e671b5e8-8db7-4dc2-aa34-85d86ace6d23.png)

Any help will be greatly appreciated

**Comment by synchromesh62** [comment]
I noticed on the forum you are using Windows 8.1
Max is Windows 10 and above so i think this is the problem.
The good news is you could upgrade to 10 for free still.

**Comment by UltraVox001** [comment]
Have you tried running the program in administrator mode ?

**Comment by synchromesh62** [comment]
**Have you tried running the program in administrator mode ?**
It wont work on 8.1
The minimum operating system to Windows 10 or above for compliance with the Windows Mixed Reality requirements.

**Comment by rpinson57** [comment]
Thanks everyone.
Didn't see the part about windows 10
