### ISSUE TITLE
GGMAX: Running Zombies 

### ISSUE THREAD

**Issue by perovdm** [TheGameCreators/GameGuruRepo#1893]
I do not know which release this started happening in but the zombies with "ChaseModes" as "Dash" keep running if you side step them. This might be a feature though :) 

Kind of funny, so not sure if I want it fixed.
![GameGuruMAX RunningZombie](https://user-images.githubusercontent.com/74854393/151682564-c4124603-49f9-4088-8832-991a335da5f6.gif)

Replicated multiple times. Also some of the Zombies have guns and there is no option to remove it.
![Running Zombie2](https://user-images.githubusercontent.com/74854393/151682568-ddc70ce2-2781-4ace-a234-f1a1ad205fed.gif)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Can you close this one once the bug has been confirmed. Same as the one you reported.

@perovdm Can you tell me how to integrated the vid animation into the issue report, it is VERY cool!!

**Comment by synchromesh62** [comment]
This one is now working as expected :)

**Comment by perovdm** [comment]
@LeeBamberTGC it is just an animated gif, exported in Premiere Pro with 15fps and 640x480 res to make sure its under the 10MB git limit.

**Comment by LeeBamberTGC** [comment]
@perovdm Would be great if GitHub automated that so we can drag in little MP4s directly into the issue :)

**Comment by perovdm** [comment]
@LeeBamberTGC Wonder if thats possible to do with github actions. I remember reading somewhere about doing pdf conversions with github actions like that
