### ISSUE TITLE
GG Max Bug Report : Show Navigation Debug Visual - Ennemis FOV Bug

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1895]
The field of view (FOV) of enemies, accessible from the "Show Navigation Debug Visual" function, is only visible for a few Characters. When I drop multiple Characters, some enemy Characters have no FOV (red area on the ground).
![NoEnnemiFOV](https://user-images.githubusercontent.com/96718175/151694031-ab5980f1-16b8-4d21-98c6-ce2d8e9eae01.jpg)
Ideally, this parameter should display the FOV of all Characters on the map, or at least in the area where the Player/Camera is.
![OkEnnemiFOV](https://user-images.githubusercontent.com/96718175/151694035-be36f5ca-5b1c-4163-ae06-5071d4276dac.jpg)
No FOV here for two Character :
![NoFOV](https://user-images.githubusercontent.com/96718175/151696256-3edd50aa-2870-45a3-a717-a95dc441f217.jpg)
The parameter should also be accessible in Edit mode, on the selected Character, to specify the parameter according to the map and the environment near the Character.

**Comment by LeeBamberTGC** [comment]
Fixed for next weeks build.
