### ISSUE TITLE
Tree and Grass should be set to visible if a level is made to use them

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1898]
If you make a level in the Terrain Generator and choose to turn on Trees & Grass from the terrain generator. When you come to the level editor you can see the trees and grass but they do not show up in Test game. You have to turn them on with the visual settings. They should be on by default if the user had chosen them to be on.
![image](https://user-images.githubusercontent.com/1503593/151703225-e7ad4924-41e5-43a1-8e64-25d18c601f91.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue , this has been fixed and will be in the next update :)
