### ISSUE TITLE
Terrain area and grab icon can get out of sync with the terrain

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1899]
By rising the height of the terrain I was able to make the yellow area show up like this;
![image](https://user-images.githubusercontent.com/1503593/151762376-43b4d7e0-1d8e-4e3c-b221-6829f5cd07d5.png)

**Comment by plemsoft** [comment]
@rvanner FYI: Missing Image ?

**Comment by rvanner** [comment]
@plemsoft Image posted now
