### ISSUE TITLE
Cartoon Impact Error

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#190]
Just loaded an old level that worked with previous PP version and got this error. (See Image) 

This occurs even if both cartoon settings are // in the settings file. 

So the only way to stop this happening is to to switch on cartoon impact but set it to a really low value. 

Bug. ?
[CartoonImpactError.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1927022/CartoonImpactError.zip)

**Comment by plemsoft** [comment]
This is not a bug, "#define CARTOONIMPACT (4.2)" should always exists (be defined) and must not have "//" infront.

You can only use "//#define CARTOON" , "#define CARTOON" to enable/disable this feature :)
