### ISSUE TITLE
Auto flatten is not cleared between making new levels

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1900]
If you use auto flatten on a level and then make a new level you end up with this type of issue;

![image](https://user-images.githubusercontent.com/1503593/151703354-5abe8562-961e-4caa-9faa-c8378db31ed0.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue , this has been fixed and will be in the next update :)
