### ISSUE TITLE
GGMax is darkening my models leaving them completely black. [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1904]
![Darken_meshes_GGMax_2022_01_28_pic01](https://user-images.githubusercontent.com/47690174/151705909-b2e0002b-cfff-42c4-9790-d7cfd8748259.png)

This door

![Darken_meshes_GGMax_2022_01_28_pic02](https://user-images.githubusercontent.com/47690174/151705930-054fd911-f735-4e64-922e-65794c907b0a.png)

it should look like this

![Darken_meshes_GGMax_2022_01_28_pic02a](https://user-images.githubusercontent.com/47690174/151705947-27588be4-e0de-42c7-b3ee-aaf2de1f83b5.png)

As you can see, it's not a problem with the model or the texture, the only difference is that the one that looks good is an X file loaded in the old school way, while the model that looks badly textured was imported from GGMax.
Obviously, I configured the textures correctly, during the import process.

Perhaps having the opportunity to set all the materials in the import panel, could help create the fpe file, avoiding having to put things like **material = -1** to a wooden house.

**Comment by UltraVox001** [comment]
This is a Max bug that I have already reported here : [1762](https://github.com/TheGameCreators/GameGuruRepo/issues/1762).
Normally, checking the "Cast Shadow" box should render your textures.
But sometimes Max misbehaves with Materials...

**Comment by 3coms** [comment]
Don't help if you changed manually **materialIndex = 3**  in the fpe file, if this change is not reflected in the DBO file, the next time you run GGMax. :)

**Comment by 3coms** [comment]
About "Cast Shadow" it does not help me, I've tried it and many other things before posting here, as usual ;)

**Comment by UltraVox001** [comment]
Yes. It doesn't help you because there is this bug. Without the bug, you would have found your textures. Look at the last image of my Post [1762](https://github.com/TheGameCreators/GameGuruRepo/issues/1762). The object has become black like your door. Normally it is white. Max doesn't know how to reset Materials settings. He makes a mistake and does not know how to go back.

**Comment by ZakJudges** [comment]
Hi @3coms, are you still experiencing this issue? :)

**Comment by 3coms** [comment]
> Hi @3coms, are you still experiencing this issue? :)

Hi 

sliding door -  GGMax 2022_02_25 - today's test

Importing X file

https://youtu.be/xguAoHt2qIc

Importing as FBX file

https://youtu.be/vZ7WsBZ2gGY

**Comment by 3coms** [comment]
So, please give full support to X file, at least till importing full working. :)

**Comment by ZakJudges** [comment]
@3coms so I can look into this, could you send me the X and FBX file? :)

**Comment by LeeBamberTGC** [comment]
@3coms The MAX ASSIMP X importer is not identical to the "Guru-Converter.exe" converter in the MAX root folder. If your import does not work great with the importer, try putting your X file in the Files folder and running the above, and also make sure your BASE COLOR is not black with black alpha, needs to be WHITE so the texture can multiply with it to form the final color.

**Comment by 3coms** [comment]
> @3coms so I can look into this, could you send me the X and FBX file? :)

Done. I sent you the download link; if any issue, please, let me know. :)

**Comment by 3coms** [comment]
@LeeBamberTGC 
No alpha channel on this mesh, it is no need for it. :)

![No_alpha_channel_door_slide_pic01](https://user-images.githubusercontent.com/47690174/155143902-8f0ecbca-8268-42da-b168-b0c6c96a8724.png)

**Comment by ZakJudges** [comment]
@3coms got it, thanks!

**Comment by 3coms** [comment]
As you can see all those have a white alpha channels. :)
