### ISSUE TITLE
GGMAX: Save Standalone Game does not export some textures - build 2022.01.28

### ISSUE THREAD

**Issue by perovdm** [TheGameCreators/GameGuruRepo#1907]
When Saving as standalone game textures for some of the Zombies do not export.
![Capture2](https://user-images.githubusercontent.com/74854393/151719087-32eb518b-0c7d-4cc4-a53f-654610023618.jpg)

**Comment by plemsoft** [comment]
@perovdm Thanks for reporting this issue , this has been fixed and will be in the next update :)
