### ISSUE TITLE
GGMAX: Shotgun Reticle clips behind objects - build 2022.01.28

### ISSUE THREAD

**Issue by perovdm** [TheGameCreators/GameGuruRepo#1908]
The reticle for the shotgun optical sight disappears behind objects in a distance

![GameGuruMAX 2022-01-30 12-37-56-037_3](https://user-images.githubusercontent.com/74854393/151720024-4d3f994e-6b02-4b98-ba45-4edb06909fde.gif)

**Comment by LeeBamberTGC** [comment]
@rvanner New Wicked Engine system does not allow reticles as extensions to the weapon off into the scene. If a crosshair is essential, do it like the other weapons with the sight on the weapon itself.
