### ISSUE TITLE
GG Max Bug Report - Crosshair mode causes the Skybox to shake

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1910]
Crosshair mode causes the Skybox to shake (only on non-simulated SkyBoxes).
See this [Video](https://www.youtube.com/watch?v=dSIfeVJ7cao).

The reflections in the viewfinder are unpleasant.
This should be fixed or optional.

**Comment by PaulSJ** [comment]
Duplicate of #1437

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue, this has been fixed and will be in the next update :)
