### ISSUE TITLE
GG Max Bug Report - Sun from non-simulated SkyBoxes passes through all of Max's hangars

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1911]
Sun from non-simulated SkyBoxes passes through all of Max's hangars.
The non-simulated SkyBox used here is "highcloud".
The Filter Effect used is "Strong Hamber"
The metal hangars are those of Max.
This bug is visible on all metal hangars offered by Max.
![SunSkyBoxHangarIssue0](https://user-images.githubusercontent.com/96718175/151758121-d81ff43e-5fb8-43bf-9cff-72aa49a1265f.jpg)
![SunSkyBoxHangarIssue1](https://user-images.githubusercontent.com/96718175/151758128-84e7ad28-5d95-4f55-be7a-d2340fb83069.jpg)
![SunSkyBoxHangarIssue2](https://user-images.githubusercontent.com/96718175/151758136-515fd09e-598b-4978-81ab-1c7678f1b6c2.jpg)
![SunSkyBoxHangarIssue3](https://user-images.githubusercontent.com/96718175/151758144-cbe269b2-79bc-43f6-a38f-47d5165ea7e5.jpg)
![SunSkyBoxHangarIssue4](https://user-images.githubusercontent.com/96718175/151758148-ac8a834b-9089-4685-a3b2-12ea4d447c27.jpg)
![SunSkyBoxHangarIssue5](https://user-images.githubusercontent.com/96718175/151758153-3e79ead3-b1a6-4fec-94ae-b5f681d54038.jpg)
![SunSkyBoxHangarIssue6](https://user-images.githubusercontent.com/96718175/151758156-3617d2da-e246-4426-83b7-9b88d0f5ab4d.jpg)

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue , this looks like a fog problem we fixed the other day, could you try this in the latest version and let me know if it has been fixed , Thanks for your help :)

**Comment by UltraVox001** [comment]
@plemsoft 
Yes, the problem is solved.
Thank you. :)
