### ISSUE TITLE
TEST GAME - Loading bar reverses at the end.

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1913]
See this video;
https://youtu.be/TJnjgKnJeI8

**Comment by LeeBamberTGC** [comment]
@dllllllllllb A good mind bender this one, writing an improved loading bar progress system that accounts for the different 'stages' of the level test setup process, and a good way to learn the game engine a little more :)

**Comment by rvanner** [comment]
Testing this morning. The loading bar still jumped back when doing the test level process. So not fixed yet.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Add a little error trapping to detect when the progress value passed in is lower than the current one, and ensure the values start at zero. You should then be able to trace which function is calling an eroneous value into the progress bar system.  Once that is done, you can add some code which would make it impossible for a lower value to override a higher one visually after the progress bar values have been reset to zero.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Made a mistake by relying on the progress percentage of each item to never be exactly 100.0f and go into a check that makes sure the value is not higher than 100.0f. Now the appropriate combined level loading progress is set after the loading loop for each item is over.
