### ISSUE TITLE
MAX - 2022.02.04 - Player Marker Shows Incorrect Behavior Image

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1915]
Blue theme is **never **OK MAX!

![image](https://user-images.githubusercontent.com/12246318/151888970-e92d0bb0-a46c-41eb-aa34-63003c9430c4.png)

**Comment by plemsoft** [comment]
@OldFlak Thanks for reporting this issue, this has been fixed :)

**Comment by OldFlak** [comment]
Thanks Preben - fixed in latest build
