### ISSUE TITLE
MAX - 2022.02.04 - Storyboard Description

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1916]
Text does not fill available space

![image](https://user-images.githubusercontent.com/12246318/151889126-f5736904-9e4a-4d64-adae-5a29b4a904bf.png)

**Comment by rvanner** [comment]
@plemsoft Needs a slider!

**Comment by plemsoft** [comment]
@OldFlak Thanks for reporting this issue, this has been fixed, but the rect is calculated when you enter the description, so you will need to adjust your text again, after this update. @rvanner also added a slider if needed :)

**Comment by OldFlak** [comment]
@plemsoft Thanks Preben - all good in new build :)
