### ISSUE TITLE
MAX - 2022.02.04 - Painting Not Restricted To 3D Level Editor

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1917]
Can paint and delete when clicking mouse over tool bar and side menu areas
-  happens with both grass and terrain

**Comment by ZakJudges** [comment]
@OldFlak Thanks for reporting this issue. A fix should appear in a build later this week :)

**Comment by OldFlak** [comment]
This is fixed for terrain painting - but models still get highlighted as you move mouse over side panels as well

**Comment by ZakJudges** [comment]
@OldFlak Thank you for confirming. I have created a new issue for the object highlighting - see #2195
