### ISSUE TITLE
MAX - 2022.02.04 - Poor Performance Rendering 

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1918]
FPS is not good even without grass
- MAX is rendering everything behind this hill perhaps?
- note mem counter in top corner - just under 35 fps

![image](https://user-images.githubusercontent.com/12246318/151889539-f19c1809-7659-4dd1-a1b8-118e29a9d445.png)

With grass on, and distance set to 1500 it still only gets 35 fps most of the time.

**Comment by rvanner** [comment]
I'm closing this because we are working on optimisations now,
