### ISSUE TITLE
DirectX 11 Bug

### ISSUE THREAD

**Issue by SuttonKen** [TheGameCreators/GameGuruRepo#192]
Hello,
I am having a issue with my new update for game guru. I get an error for directX 11 and the program software won't load,
[DxDiag.txt](https://github.com/TheGameCreators/GameGuruRepo/files/1927993/DxDiag.txt)
 are you using directX 11.1 ?  I am running windows 7 I have attached my system info 
thank you...
Ken-

**Comment by LeeBamberTGC** [comment]
I checked your DXDIAG and it looks like you are running an integrated HD Graphics GPU is that right?  If so, the system is below the minimum specification for GameGuru (https://www.videocardbenchmark.net/gpu.php?gpu=Intel+HD+Family). You can revert back to the DirectX 9 version by going to Steam GameGuru properties, selecting the beta tab and choosing "public-release-lastdx9' and restarting GameGuru, this should solve it for you.

**Comment by SuttonKen** [comment]
Hi Lee,
so new video card it is.... thank you brother, you're the best.
Ken-
