### ISSUE TITLE
GGMAX Enhancment - Elevator

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1921]
A generic apply on any object script for an Elevator designed for MAX, has behavourial settings for speed and height. Objects used needs no weight or friction to work, instructed in description. Complete with icons etc, 
Maybe the gurus can see if it fits the bill for inclusion or any adjustment.
[elevator.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7974886/elevator.zip)
![el](https://user-images.githubusercontent.com/95015657/151890420-e8e2eaae-071b-4d96-8b0d-19a756453141.jpg)

**Comment by UltraVox001** [comment]
First of all, a big THANK YOU for this script which, like the Ladder Script, adds another essential thing to FPS.
Here are my comments as a Beta-Tester on this first version.

**Advantages :**
- Can be used on virtually any object.
- Very easy to use and adjust.

**Disadvantages (current version) :**
- Going up or down on the Elevator is done with jerks.
- Once activated, the Player is stuck on the Elevator (no movement is possible, except that of the mouse).
- As the Elevator goes up, The Player (his FPS camera) is gradually pulled down (under the Elevator).
- If the variable MOVESPEED is greater than 33 (like 34), we fall to the ground, under the Elevator, before reaching the variable MAXHEIGHT set to 500. If I set MAXHEIGHT to 600, I must also decrease the setting of MOVESPEED to avoid falling under the Elevator. Therefore, setting a very high MAXHEIGHT value requires a proportionally lower MOVESPEED value, so as not to fall below.

An awesome script that needs improvement for better InGame performance!
Well done. :)

**Comment by Necrym59** [comment]
Can i ask what you used for the object and what settings you used on the object. I have attached an updated script that should be smoother and shouldnt make you go in the floor, no movement on the elevator is suppposed to be that way but i will look into other options for that and a call switch
[Elevator_v2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7976083/Elevator_v2.zip)

**Comment by UltraVox001** [comment]
Thank you for your improvements on this script.

This V2 version is already much smoother. I can use any speed and any height, the camera is stable. I'm still stuck on the Elevator. No movement is possible, except the mouse.

Object used for this test :
![Tile](https://user-images.githubusercontent.com/96718175/151920236-51c23972-e0f9-42f0-b9e3-91f1da9318ed.png)
Object : Green Ceiling - Tile
Physics : On
Gravity : Off
Weight : 0

Thank you. :)

**Comment by UltraVox001** [comment]
If I do speed tests, with settings 500 and 500 in the behavior, the object used for the Elevator can disappear under the ground after coming down. I use an Empty map.

**Comment by UltraVox001** [comment]
Behavior setting :
200
93
If I go to 94, the Elevator goes back under the ground after the descent.

**Comment by UltraVox001** [comment]
If possible, allow us to assign optional sounds to the Elevator. (Go up/Go down).
Obviously this can wait until the Elevator is fully operational.
V2 is already correct :)

**Comment by Necrym59** [comment]
Version 3 - tweaked a bit plus includes sound play events. 
The Elevator script has be set up for up to 3 sounds, Sound 0 for start, Sound 1 for moving, Sound 2 for stopping
Sample sounds supplied to be placed in your games audiobank folder.
[Elevator_v3.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7976659/Elevator_v3.zip)
.

**Comment by UltraVox001** [comment]
Great! You just have to remember to stop the "elevator-moving.wav" sound when the Elevator arrives at a destination (up or down). If not, the "moving" sound continues too long.

Or, program that playing the "elevator-stop.wav" sound stops the "elevator-moving.wav" sound.
Is it possible ?

**Comment by UltraVox001** [comment]
Sound details :
- The sound "Sound1" must play in a loop as long as the Elevator is active.
- Until destination where sound "2" must stop "Sound1".

**Comment by Necrym59** [comment]
Fixed now as a loop until Stop works better with a smaller sound byte for the moving sound as well
Version 4 :)
[Elevator_v4.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7976878/Elevator_v4.zip)

**Comment by UltraVox001** [comment]
Thx ! The script to stop "Sound1" is only taken into account when the Elevator arrives at the bottom.
When Elevator goes up and arrives at the top, Sound1 continues.

Come on, you're almost there :D

**Comment by Necrym59** [comment]
Lol my bad. Fixed
[Elevator_v5.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7976982/Elevator_v5.zip)

**Comment by UltraVox001** [comment]
Haha! Almost !
Sound1's loop only works downward. :)
It must also work uphill :D

Test carried out on the following setting :
2000
80

Come on, this time you're really there :D

**Comment by Necrym59** [comment]
This time for sure!
[Elevator_v6.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7977063/Elevator_v6.zip)

**Comment by UltraVox001** [comment]
Great, you made it!
You have done wonders in 1 hour of time :D
Many thanks to you :)

**Comment by UltraVox001** [comment]
Here is the test map, for those interested. :)
[ELEVATOR V6.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7977121/ELEVATOR.V6.zip)

**Comment by Granada1** [comment]
Great work here guys 👌thank you

**Comment by Necrym59** [comment]
Updated to v7
Activate by switch enabled , cleaned up redundent code, now only use the E key to go up and down
[Elevator_v7.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7983641/Elevator_v7.zip)
Modified map with switch
[ELEVATOR V7.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7983651/ELEVATOR.V7.zip)

**Comment by Necrym59** [comment]
There could be a problem here switches dont appear to work mor than once.

**Comment by UltraVox001** [comment]
Currently the switch has no effect. The switch knows how to activate or deactivate an object. I don't think he knows how to move the Elevator. It's not like with a Light (unfortunately).

**Comment by UltraVox001** [comment]
Oh yes, of course.
I forgot to change the Behavior :)

**Comment by UltraVox001** [comment]
Everything is working.
You just have to set the AI to Toggle.

**Comment by Necrym59** [comment]
Really i did that and it failed, just spent ages trying to find out why. I have just reapplied it and it works - go figure! Well i am at peace for now :)

**Comment by UltraVox001** [comment]
No wonder. Max is having difficulty with AI management currently.
Despite this, you have done a very good job.
Sincerely, I congratulate you. :)

**Comment by Necrym59** [comment]
Thanks mate, well i guess it stays as is until some of the fixes come in. It seems to work smoothly and ok for now.

**Comment by Necrym59** [comment]
Ha bent it to my will a bit more V8
[Elevator_v8.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7984937/Elevator_v8.zip)
Untill some things like remote switches behaviour etc are fixed this will have to do.

**Comment by Necrym59** [comment]
Bent it to my will a bit more. V8
[Elevator_v8.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7984974/Elevator_v8.zip)

Cant do much more until some things are fixed i think.

**Comment by UltraVox001** [comment]
Thx, but I don't see any change in usage.
Everything seems to be working fine. What have you changed?

**Comment by Necrym59** [comment]
Just some clean up concerning distance and object status nothing major but its just a bit cleanerSent on the go with Vodafone
-------- Original message --------From: UltraVox ***@***.***> Date: 2/2/22  8:24 pm  (GMT+10:00) To: TheGameCreators/GameGuruRepo ***@***.***> Cc: Necrym59 ***@***.***>, Author ***@***.***> Subject: Re: [TheGameCreators/GameGuruRepo] GGMAX Enhancment (Issue #1921) 
Thx, but I don't see any change in usage.
Everything seems to be working fine. What have you changed?

**Comment by Necrym59** [comment]
Also have a related conveyor script
[conveyer.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7993147/conveyer.zip)

**Comment by UltraVox001** [comment]
I thought about it yesterday, but I didn't dare suggest it to you. I just tested it and it works fine. Well done! Maybe an alternative script with other options to tick, to make it self-contained, like always moving (back and forth), like in a factory.

We can also imagine a Flags system so that the conveyor moves on a path (forward, backward, left and right). Is this possible, do you think?

**Comment by UltraVox001** [comment]
Another problem in the current version : the direction is always the same. The direction should be the one that corresponds to the rotation applied to the object. I tried but it always goes in the same direction. Unless you are able to determine which direction it will go from the Behavior?

If it can help you improve.

**Comment by UltraVox001** [comment]
New problem detected : if the Conveyor is dropped in the same map as the Elevator, they activate each other.

**Comment by Necrym59** [comment]
Cant see that problem both are independent here? Actually cant see how that can be they are suppposedly seperate objects.
Perhaps its due to the work around i did with the switch behaviour i can eradicate that bit and wait till they have it done.
[Uploading elevator_conveyer.zip…]()

**Comment by Necrym59** [comment]
Cant see that problem both are independent here? Actually cant see how that can be they are suppposedly seperate objects. Is the name of the elevetor object the same as the conveyor. Perhaps its due to the work around i did with the switch behaviour i can eradicate that bit and wait till they have it done. Try this map it works fine for me including a rotated conveyer
[elevator_conveyer.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7997680/elevator_conveyer.zip)
.

**Comment by UltraVox001** [comment]
Thank you. I will test your card tonight.

I discovered another "bug". When I retrieve a weapon from the ground (Knife, AK...), the Elevator starts up. Yet the weapon is at least 20 meters away from the Elevator. Same with the Conveyor.

**Comment by Necrym59** [comment]
Now that is weird i will try and duplicate it.

**Comment by UltraVox001** [comment]
Your map works.
In mine, when I click on a Conveyor, I get teleported to the other. Weird.
However, I am a Beta-Tester for TGC.
I'm using an internal version of Max, a bit ahead of regular users.
Here is the map I use.
[ElevConv.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7998707/ElevConv.zip)

**Comment by Necrym59** [comment]
elevator on your map if used once then moves everytime you select a conveyer its like MAX doesnt clear the last used object index from memory when used and there doesnt seem to be a command to clear/reset it those that seemed appropriate dont seem to work, it maybe a MAX cache problem ive been at it for hours trying everything under the sun - perhaps one of the Gurus will know, ill keep trying as well.

**Comment by Necrym59** [comment]
Heres an updated conveyor see how you go with this one. Added in auto run mode option plus craceful join or exit on conveyor in auto mode. Let me know how it goes
[conveyer_v2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8006827/conveyer_v2.zip)
.

**Comment by UltraVox001** [comment]
I really enjoyed this version of the Conveyor.
This automatic exit works with the direction of the Player's camera. It's excellent !
Have you considered using your Conveyor with Flags ? (optional)

**Comment by UltraVox001** [comment]
Have you tried to drop 3 conveyors (or +) on the ground, in auto mode and in 3 different directions ?
Frankly, it's fun and it opens up perspectives. :)

**Comment by Necrym59** [comment]
Lol no havent played too much ill give it a go glad you enjoyed it. Havent got to the flags part yet thats gonna be a bit hairy with behaviors in flux and all but ill give it a shot. Also i will relook at the elevator soon after playing with the conveyor have an idea for a muti floor stop elevator.

**Comment by UltraVox001** [comment]
> have an idea for a muti floor stop elevator.
Excellent. :) I thought about it from day one, but I didn't want to impose work on you.

**Comment by UltraVox001** [comment]
With several Conveyors on the ground. When you leave a conveyor and move away from it, the message at the bottom of the screen remains displayed, even if you are far from all the conveyors. This is the reason why I am "teleported" on the first conveyor used, even when I use another one.

You should try to display this message only when the camera is pointing downwards. Or, force the message to clear when a conveyor arrives at its destination. Even at more than 200 meters I still have the message "Press E". :)

**Comment by Necrym59** [comment]
I will have a look the teleportation issue seems to be MAX not releasing a used 'e' object when you use another object it still retains the previous one regardless if its a handgrenade or another object, i cant seem to see how to clear it from memory i will have another look maybe someone could give us a hint or perhaps its a bug.

**Comment by UltraVox001** [comment]
I don't have that problem with weapons. The text disappears as soon as I move away from a weapon, or as soon as I pick up the weapon.

**Comment by Necrym59** [comment]
Fixed text problem
[conveyer_v3.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8008631/conveyer_v3.zip)

**Comment by UltraVox001** [comment]
Yes, the text and teleportation are solved, well done. :)

It does not solve the problem of multiple conveyors. I have 3 on the floor. Activating the second causes the first to react, because I used it first. There is still this memory problem that Max absolutely wants to use.

I would almost believe that I have to rename 3 scripts with different names to use 3 conveyors in the same map.

**Comment by Necrym59** [comment]
Yeah its odd you may have to bring it up with Lee, unless im doing somthing stupidly wrong. Id like to know.

**Comment by UltraVox001** [comment]
> Are they diffent named conveyers perhaps - dont know if that helps.

No, it doesn't change anything.

**Comment by Necrym59** [comment]
Elevator Update
Now has a mid floor height option.
[Elevator_v9.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8011787/Elevator_v9.zip)

**Comment by UltraVox001** [comment]
Tested this morning. This stuff is going to be great. :)
Set to :
400
200
80
All is well on the way up, until the Elevator drops all the way down.
Once at the bottom, he doesn't want to go back up.
Sound plays, but Elevator does not go up.

**Comment by Necrym59** [comment]
Sorry my bad - one misplaced comma. Version 10 attached
[Elevator_v10.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8013170/Elevator_v10.zip)

**Comment by UltraVox001** [comment]
I just tested. It works very well. :)
I even tried with a single floor.
400
400
80
Where I expected to find a bug, there is none. ;)
Well done. :)

**Comment by UltraVox001** [comment]
@Necrym59 
In this case, the script presented here could (perhaps) be useful to you :
[https://forum.game-guru.com/thread/223291?page=2#msg2646602](https://forum.game-guru.com/thread/223291?page=2#msg2646602)
PS : I answered you on the forum.

**Comment by Necrym59** [comment]
Elevator V12
-zip includes royalty free sound files
[Elevator_v12.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8137019/Elevator_v12.zip)

**Comment by UltraVox001** [comment]
@LeeBamberTGC and @rvanner 
Tested and approved. :)
Elevator up to 2 floors, with adjustable height, per floor.
You choose the height for both floors.
You can go up and down with A and W.
Good script for Max ;)
