### ISSUE TITLE
MAX - 2022.02.04 - PBR Rendering Feedback

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1922]
Plants and rocks all shiny

![image](https://user-images.githubusercontent.com/12246318/151890320-e228df1e-0cfa-4763-ab4b-9ff582a79c15.png)

![image](https://user-images.githubusercontent.com/12246318/151890381-e4db8982-ef10-4064-b377-1727ff0c5d90.png)

![image](https://user-images.githubusercontent.com/12246318/151890422-dd16b185-8d54-4e4d-b1d5-06db6281c234.png)

**Comment by rvanner** [comment]
@OldFlak Is this still a valid issue for you?

**Comment by OldFlak** [comment]
@rvanner Thanks for follow up :)

Tis not as aggressive as previously and it can actually look quite nice. The problem now is that it is not consistent when it does apply the effect.

In this pic it looks ok 
![image](https://user-images.githubusercontent.com/12246318/161536004-ef76a872-5ee7-44bb-aa93-6f4d1a7f2354.png)

But if you turn away and look back again it may be the same, or it may not have any shine at all - tis bit random.

**Comment by rvanner** [comment]
@OldFlak Are these your own imported models?

**Comment by rvanner** [comment]
@plemsoft Can you take a look at these and let us know if there's something wrong with their textures?

**Comment by plemsoft** [comment]
@OldFlak Is this your optimized media are the original ?

**Comment by OldFlak** [comment]
@plemsoft Hi Preben thanks for follow up - get same with either versions

**Comment by plemsoft** [comment]
@OldFlak Yesterday we switched to your optimized version updated on steam now, Thanks :) , and "reflectance      = 0.00" and when i try to add the tall grass there is absolutely no reflection. i expect this is from a old level where the reflectance could have been set different when you added the objects  ?

You had a typo in "Tall Grass.fpe" "surfaceMap       = JungleGrass_surface.dds" should be "surfaceMap       = Jungle Grass_surface.dds" , (i get that updated tomorrow) , but even after fixed this there is still 0 reflection.

Please try with "your" optimized Jungle Collection (download latest from steam) with a fresh level and let me know if its still a issue , thanks :)

**Comment by OldFlak** [comment]
Thanks Preben will check them out - Yes there were typos in coupler of the FPE's which I did send to Rick, but good to see you found them :)
Thanks for your great work :)
