### ISSUE TITLE
Zombie A.I is Busted

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1924]
Zombie A.I is broken. Here is video. 
https://www.youtube.com/watch?v=pTCGlqPaiz8

**Comment by rvanner** [comment]
@Kitakazi This should not happen now. Can you please confirm?

**Comment by Kitakazi** [comment]
I just did a fresh install on steam and played the demo level Mystery of Z Island and the zombie A.I was still busted. The first zombie I ran into took off sprinting to the boonies. The others were very buggy.

**Comment by Kitakazi** [comment]
I updated to the internal 04.08 and the zombies seem better. If they aggro to the player and then the player moves out of range they get really weird really quick. Usually they start to spin in circles. 

@rvanner
