### ISSUE TITLE
Normal textures added to assets after import, disappear once the level is saved

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#1925]
I have a pack of modular caves that i have brought over from classic. In classic the fpe recognises the PBR textures correctly, however in Max, only the _color file is found. As you can apply texture files to individual assets in Max, i have added the normal maps back onto each mesh for the desired effect. However, once the level is saved, the normal maps are removed and the mesh revert to only _color maps.

![github image](https://user-images.githubusercontent.com/82544140/151996784-0fc13f2c-f3a5-4151-bf33-2c7bc37adf23.png)

**Comment by ZakJudges** [comment]
Hi @mav3r1ck198-1, are you still experiencing this issue in the most recent build? :)
