### ISSUE TITLE
Back button to jump back to the importer

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1926]
Add a new back icon to this screen so users can change their importing data before it's too late;

![image](https://user-images.githubusercontent.com/1503593/152002496-0823ea0b-1baa-4980-a6e8-b57e9c8d180a.png)

@ZakJudges Lee has asked for this to be done so please deal with it asap. Thanks!

**Comment by Necrym59** [comment]
You dont know how many times I had wished for that, but I never remembered to ask for it.

**Comment by ZakJudges** [comment]
@rvanner This should be in tomorrows build. To avoid some issues and save time, I placed the back button above the thumbnail. But just let me know if you'd like it changed tomorrow

**Comment by rvanner** [comment]
@ZakJudges Can you post a screen shot of the back arrow here?

**Comment by ZakJudges** [comment]
This is how it looks currently:
![Screenshot 2022-02-14 143551](https://user-images.githubusercontent.com/32545391/153884111-5a0f5381-8645-4fd5-8b9c-5692f506497b.png)
