### ISSUE TITLE
MAX - Characters will often phase through walls/other solid objects

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#1929]
Characters have a tendency to turn into ghosts and walk through solid objects!

Okay, not really.

But they do walk through solid objects, when trying to walk to a point or flag they sometimes "overshoot" the position and keep walking, resulting in them phasing through any walls or objects that happen to be in their path. Why characters don't have proper physics against level geometry I may never know, but at the very least they should more reliably stop on their destination point to mitigate this issue.

This issue is easily replicated; on the "outdoor ramps" asset, place a few soldiers, place a start marker and set health to invulnerable, and then aggro the soldiers and run around the asset to make them calculate and follow paths. They tend to phase into the empty space beneath the asset and get stuck, but can also phase back out and make a path up the stairs.

**Comment by rvanner** [comment]
@fearlesswee Is this still an issue for you in the EA release?

**Comment by fearlesswee** [comment]
I actually haven't tested this extensively anytime recently, as I'm having other issues with MAX (see: #2738)

I'll quickly repeat my testing method tomorrow, to try and see if they still like to ghost around. I will say at first glance it certainly seems to be a lot rarer at least, as before you almost couldn't have AI in your level without them phasing through walls once or twice.

**Comment by rvanner** [comment]
Thank you

**Comment by fearlesswee** [comment]
So far from my testing I think this issue has been dealt with; before it was extremely easy to get them to phase through walls but now they're quite good at following paths even in narrow spaces, like buildings! I think it's safe to say this issue is fixed.
