### ISSUE TITLE
GGMax close when selecting material settings [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1933]
This happens to me builds ago, so, now it gets back again on the 2022_01_28 build.

https://youtu.be/PjwV_vS69bk

It happens to me on different levels; in fact, this is a new level, just snow terrain, and place my snowy cabinet to test it.
Notice in the video how wrong is GGMax rendering the custom meshes (snowy cabinet)

It should look like the pic below (Assimp)

![snowy_cabinet_Assimp_pic01](https://user-images.githubusercontent.com/47690174/152259287-10a624d5-ce37-4b1a-bb12-f84bf097456d.png)

I go to the material setting to try to fix that terrible look, but the GGMax suddenly closes.

**Comment by 3coms** [comment]
I had tried importing the mesh, but it gives the same bad textured mesh and closes when hit on material settings, as well.

**Comment by LeeBamberTGC** [comment]
I suspect this is model related as I cannot reproduce when importing stock assets. Can you email me the model, thanks!

**Comment by 3coms** [comment]
Done :)

**Comment by ZakJudges** [comment]
@3coms Thanks for reporting this issue. The model had 179 meshes which was too much for the materials menu to handle. I've added a fix which you should see in next weeks build :)

**Comment by 3coms** [comment]
Can the materials menu handle it by material, rather than by mesh?
There might be 50 boxes but all then share the same material, when I set up material for one of them, automatically GGMax updates material settings in other ones. Right now I have to set up the same material for the 50 boxes one by one.
So, if you have box1, box2, box3.....box50, this is insane to list them there; on this way you just have 1 box on the list, since it shares material with the other 49 boxes. 

Another way you will have to do as you pointed out; **item_count = mesh_count+1** and you are safe :)
Thanks, mate for giving it a go. :)

**Comment by ZakJudges** [comment]
@3coms If you select "Edit all Mesh Materials" on the mesh dropdown, any material setting that you change will be applied to all meshes in the object :)

**Comment by 3coms** [comment]
Not so clear how to work this one, imagine a scenario, a multi_object mesh with several textures; each texture follows a name convention done in the 3ds soft, in order to make GGMax the life easier; but you get on GGMax material settings names such as "Noname material" so, if your meshes have 30 pieces, so, you have 30 _nonames_ in the material list, so, then, how to?
How do you know who is who?

GGMax from time to time gets a fixed material path, and there is no way to change it.
For example, I get on a normal map file path something such as _gamecore/brass/brass12...._.  it has nothing to do with my texture path, and if I try to change it, GGMax automatically back to their path. :)

Anyway, the goal here is GGMax closing when hitting material settings, and it is fixed for me as well. :)
Thank you, Zac, good job. :)

**Comment by ZakJudges** [comment]
@3coms Ah I understand now. I can take a look at this when I get round the importer bugs - here's an issue describing the problem. https://github.com/TheGameCreators/GameGuruRepo/issues/1096
Is this what you mean? :)

**Comment by 3coms** [comment]
@ZakJudges 
Exactly!
Thanks for taking a look. :)

**Comment by 3coms** [comment]
@ZakJudges 
Sorry guy, but I have some doubts about how the "Edit all Mesh Materials" feature work.
Let's say I have 20 boxes (box1, box2...box20) and all the sharing material (for some reason I don't have them merged into one mesh); how I choose there the 20 boxes to assign the material to those, and not to other mesh?
Well, I guess I select 1 box and GGMax automatically assigns the material to the 20 boxes, but how do I set there what meshes I want to texture? there just there is the option to choose a color, normal, surface, etc, but how do I set the mesh I want to texture?
Or when I choose a texture file, automatically GGMax knows who shares that texture, and does the trick? if so, wonderful work!. :)
Can you please, clarify a bit, if possible?

**Comment by ZakJudges** [comment]
@3coms At the moment, in your scenario, there is no way to apply a texture to some of the meshes but not all of them in one go. You can only select one mesh or all of them. I agree its not the best way of doing things, so if you have any suggestions, just make an issue and label it as an enhancement, then we can take a look after Early Access :)

The importer should try to assign the textures automatically, based on what the object file contains, and the availability of the textures. I believe there is a couple of bug reports regarding this, so its likely not working in all scenarios, so I'll be taking a look in the near future :)

**Comment by 3coms** [comment]
I agree there is no way now to assign the same material to all meshes sharing it at a time, wait for better times. :)
I also agree that GGMax should assign all textures automatically, and then there is no need to do anything else. :)
After all the X file already stores all the material paths and names, who shared what, and who use that material or this other.
So those meshes sharing the material **table** go within a table/array, and when the user selects a material **table**, then assigns that material to all the elements inside the table/array. (Nah guy, just kidding :))
Thanks again for take a look, I gonna way best times. :)
