### ISSUE TITLE
MAX - 2022.02.04 - Capsule Moving With Player - Ruins Fog Effect

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1936]
Can't think of a better way to describe it so here be a video:
https://youtu.be/64SSHUH_ryo

Similar to the issue we had when Auto Exposure was introduced:

Settings:
![Player Capsule Fog Issue Settings](https://user-images.githubusercontent.com/12246318/152425394-8e21c95e-35a1-4fd0-ac87-052e9a93f17c.png)

**Comment by OldFlak** [comment]
FYI - this issue is noticeable with very little fog as well, but fog makes it very obvious..

**Comment by rvanner** [comment]
@OldFlak Maybe this is an old issue? If you want a proper fog level you need to do the following;

Environment Effects: Set "None" for Sky
Weather: Set Fog range between say 0 and 4 and Set Fog Opacity to 100

**Comment by OldFlak** [comment]
@rvanner No tis still issue in latest :)
That is not a solution - can't have nice foggy morning with out sky :)

**Comment by OldFlak** [comment]
Not seeing this at present - so closing.
