### ISSUE TITLE
Welcome Screen  - add in the new demo games from community and staff when they are confirmed

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1937]
Update the build with the games when they are chosen and show them in the Welcome Screen

**Comment by plemsoft** [comment]
@rvanner I believe Lee is adding these as they come in :)

**Comment by LeeBamberTGC** [comment]
@plemsoft Yep, adding Island Showdown this week, plus any more RIck deems worth today :)
