### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1938]
When the tutorials are ready, make them auto play when you first enter each new editor.

The video to be shown full screen and can be skipped by the user if they want.

These will appear for:
- Storyboard
- Terrain Generator
- Level Editor
- Object Library

![image](https://user-images.githubusercontent.com/1503593/152519864-6b182e5f-ad8d-4eb4-855c-a7e5fc2ff506.png)

**Comment by plemsoft** [comment]
@rvanner I believe we fixed most of this on TW , the only thing is the new design would you like me to add that at this point ?

**Comment by rvanner** [comment]
@plemsoft I consider this done now. I think the design you implemented is fine. I also don't think we should autoplay the videos, let the user choose when to watch them.
