### ISSUE TITLE
Terrain Generator: Black screen pause

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1947]
When starting a new level the screen remains black for a few seconds, it didn’t do this before.

**Comment by plemsoft** [comment]
@rvanner This is needed to fix some other issues, where tree settings from other levels would go into the terrain editor, and trees was not reset when changing biomes , so we need to reset tree/grass when we enter terrain generator. That's why you get the additional 2 sec.

**Comment by rvanner** [comment]
@plemsoft Can you show some text so the user knows it's not crashed?

"Preparing the Terrain Generator. Please wait..."

**Comment by plemsoft** [comment]
@rvanner Text added.
