### ISSUE TITLE
Terrain Generator: Move the Generate Terrain for Level button to the bottom of the UI

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1948]
Move the Generate Terrain for Level button to the bottom of the UI and ensure it cannot scroll off the screen
![image](https://user-images.githubusercontent.com/1503593/152522597-be19c700-6511-43ab-bf90-29fb65a699ea.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next build :)

**Comment by rvanner** [comment]
@plemsoft This is great. Just need to close up this area of the box;
![image](https://user-images.githubusercontent.com/1503593/152938840-4caf5b7a-1261-4059-aec1-953a15c8f18c.png)
