### ISSUE TITLE
New rendering technique allowing object to render last

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1949]
Lee to code a render state that renders an object last into the scene. 

This can then be used;

- To draw a weapon last so it does not cut into objects nearby
- The terrain generator grab box so it is not lost behind a mountin

**Comment by LeeBamberTGC** [comment]
@rvanner New build for this evening will have additional functionality to set objects to render anywhere despite the depth buffer preventing it. Weapons no longer insert into walls and trees, and @plemsoft can set the terrain generator marker so you always see it (see function called WickedCall_SetObjectDisableDepth)

**Comment by plemsoft** [comment]
@rvanner Also added to grab box now.
