### ISSUE TITLE
Add the text “Editable Area: 3.26 Km / 2.02 Miles” 

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1950]
Where the editable area size is shown, add the text "Editable Area:" before the size data.
Also move the text so it's on the inside of the box
![image](https://user-images.githubusercontent.com/1503593/152523494-b5533999-c056-4726-8dc0-6cc111fc58ff.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next build :)
