### ISSUE TITLE
Terrain Generator: Camera angle to show some sky

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1951]
The default angle does not show any sky. Change it so that it looks like the right image here.
![image](https://user-images.githubusercontent.com/1503593/152523820-87d36b16-30a7-430e-ae6b-16e9fdd8d2d8.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next build :)
