### ISSUE TITLE
Terrain Generator: Add an option for the Randomization of the time of day

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1952]
Add a new “Randomize” option in the time of day drop down. This would be the default time of day when you come into the editor. If it’s changed then don’t randomize the Sky when users press on the different biome buttons.

![image](https://user-images.githubusercontent.com/1503593/152523975-5086b606-da96-4d59-80c5-107fd7b5d7cf.png)

**Comment by plemsoft** [comment]
@rvanner When we select a random time of day, we display the random selected time in this drop down, it cant display "Randomize" and also the random selected time , should i add a checkbox above it instead "Randomize Time of Day" ?

**Comment by rvanner** [comment]
@plemsoft Yes, add the checkbox please.

**Comment by plemsoft** [comment]
@rvanner This has been fixed.
