### ISSUE TITLE
Terrain Generator: Editable area indicator visual bug

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#1955]
When you position your camera outside of the editable area and rotate it, certain angles will make solid lines that shoot off into the sky.

Example 1: https://gyazo.com/12badd2b756684bde1ceacfb6d9c702c
Example 2: https://gyazo.com/b45dcb6ea420b3f6dd62db3db60c4fb9

**Comment by LeeBamberTGC** [comment]
@plemsoft Can you confirm and close this if it is fixed
