### ISSUE TITLE
Roads.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1961]
trying to place some roads and its causing the terrian to automaticly adjust under the road which I don't want it to do, this road is suppose to be a bridge and every ttime I try bridging the gap over the river, it just automaticly changes the terrain, is this a feature? and if so how do I turn it off?

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/152554834-e6e041b9-f99e-4f03-8971-fee9ddc19ccc.png)

**Comment by synchromesh62** [comment]
Settings \ General \ Untick .. **auto-flatten terrain under large objects**  to turn it off completely
Or **autoflatten = 0**  in the .fpe for if you just want to turn off certain ones .

**Comment by casigus** [comment]
oh thank you!!!! :D :D
