### ISSUE TITLE
Zombies following flags issue

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1963]
I believe Zombies can or will follow flags when idle. ( which is awesome when it works )
Initially they stand there and do not wander the path
If they see you they will chase and return and then maybe patrol the flags
Or they return and bash the hell out of the flag :)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Sorted for afternoon build.  The endless way has now been gifted to Zombie-kind:

![image](https://user-images.githubusercontent.com/35840583/154499504-b8f293b7-4f29-4a12-a076-cc7159ce5e8f.png)

**Comment by ZakJudges** [comment]
Zombies follow flags in latest build
