### ISSUE TITLE
Zone Audio issue

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1964]
I've been trying to get an Audio Zone to work for over an hour. It only worked once.
I changed the Behavior setting and presto, nothing.
![Sound](https://user-images.githubusercontent.com/96718175/152589594-4f78c7b3-a5fd-49c7-a786-5e51dde71899.jpg)
I tried on an almost blank map.
Same problem.
![Sound2](https://user-images.githubusercontent.com/96718175/152589610-2146c30c-746f-4a4c-8f17-017821341a17.jpg)
I tried other sounds.
Same problem.

Is there a report for this problem ?

**Comment by LeeBamberTGC** [comment]
@dllllllllllb A nice one to investigate and attempt to reproduce.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Is this still an issue?

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
The problem is the "Fade In Zone" Behavior.
It only works once. At the second TestLevel, there is no sound.
In addition, illuminating the Audio Zone with a Light and Cast Shadow activated, causes this :
![LightInZone](https://user-images.githubusercontent.com/96718175/157250772-8c06cf41-6958-47d1-ad4f-63516bee1334.jpg)
![FadeInZone](https://user-images.githubusercontent.com/96718175/157250783-3a0b0acb-cba3-4da1-9bae-cc2dfb4ccc29.jpg)

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Seems a slip in the code allowed some objects to cast shadows even though they had been set to not cast, things like markers and the weapon, etc. Sorted for next internal build.
