### ISSUE TITLE
GGMax_2022_01_28 rendering wrongly X file [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1966]
I'm going to talk about a hypothetic scenario to describe the bug (if any)
**Note:** Don't want to discuss how a mesh should be set up in the 3ds soft before porting to GGMax, but just want to clarify which workflow in GGMax should be.

1- Modeled a bunker on 3ds max with let's say 100 walls, 100 planks (the floor), 100 planks (the roof)), total = 300 objects.
2- Group everything, and export it as an X file to GGMax. 

And this is what I get on GGMax:

![sculpture_mesh_GGMax_2022_01_28_pic01](https://user-images.githubusercontent.com/47690174/152609888-4f03d7d5-48ab-4f30-89cc-c87992db494c.png)

And this is what it should be (Assimp)

![bunker1_Assimp_pic01](https://user-images.githubusercontent.com/47690174/152609994-3436d313-3ff0-4277-a391-8824fbab787f.png)

3- Then I decide to merge everything into 1 mesh in 3ds max and - re-imported it to GGMax, the same result.
4- Then I decide to break the model into sections (secc1/secc4, plus the floor, plus the tuberia, plus the boxes, etc)

Then I get pieces (sections) super resized and so tricky to resize then again to match the rest of the mesh.

![bunker1_GGMax_2022_01_28_Rezising_meshes_pic01](https://user-images.githubusercontent.com/47690174/152610377-37acb4cd-3d58-46ed-85d6-8b3e34c33816.png)

You can notice at the bottom of the pic how they should be, and at the top of the pic, how biggest they are.

5- So, I tried merging the model section1 and section 2 together into 1 mesh, in 3ds max, and this is what I get on GGMax:

![bunker1_sect1_sect2_GGMax_2022_01_28_pic01](https://user-images.githubusercontent.com/47690174/152611010-36b2b4cb-cb68-4198-bba5-c2267711607a.png)

A well-done mesh on GGMax! :)

So, the question raised is, does this should be the accurate workflow on the 3ds soft to match with GGMax requirements? or is there something wrong with GGMax rendering those sorts of meshes?

Edit: some video links: https://youtu.be/39OOC-SCbLI

**Comment by 3coms** [comment]
The mesh works right using step 5. :)

![Bunker_Central_Hraulica_GGMax_2022_01_28_pic01](https://user-images.githubusercontent.com/47690174/152615108-dc8d3681-2ca5-4d27-978a-ae8930867727.png)

**Comment by 3coms** [comment]
Guys think not every user stuff is going to be just a rec house, more complex geometry might come, and GGMax should be ready to deal with, correctly. :)

**Comment by 3coms** [comment]
Meshes really bad textured, it may be related with or does not, look for yourself

![Horrible_textured_Mesh_GGMax_2022_01_28_pic01](https://user-images.githubusercontent.com/47690174/152655469-61a7ceae-713a-42fe-b59b-bfe41b2d0927.png)

compare the texture with the final result, has nothing to do.

**Comment by 3coms** [comment]
Same X mesh on 3ds max

![mesh_3ds max_pic01](https://user-images.githubusercontent.com/47690174/152655671-4c4adbc3-c8b9-46ab-a345-60004637fb5c.png)

**Comment by 3coms** [comment]
Sorry guys, but this has nothing to do with an enhancement this is a bug with all their words. :)

And has nothing to do with the model itself, today has the same issue with a simple table:

In GGMax as X file

![snowy_cabinet_bad_assembly_GGMax_2022_02_11_pic02](https://user-images.githubusercontent.com/47690174/153000958-699939c7-45c9-41f3-bf81-db7955e29265.png)

Importer

![snowy_cabinet_bad_assembly_IMPORTER_GGMax_2022_02_11_pic02](https://user-images.githubusercontent.com/47690174/153001149-7799fb03-93dd-4d96-b469-05b1a1cbb733.png)

As it should look (Assimp)

![snowy_cabinet2_Merged_Assimp_pic02](https://user-images.githubusercontent.com/47690174/153001240-30fbef09-c735-441d-9721-8f47a3ef9f44.png)

https://youtu.be/39OOC-SCbLI

**Comment by LeeBamberTGC** [comment]
Can this bug be reproduced with stock media?

**Comment by 3coms** [comment]
> Can this bug be reproduced with stock media?

I've tried but can't get it; so, I did a different approach and try it as FBX, that's the result:

In Win10 3D viewer

![snowy_cabinet2FBX_W10_3D_Viewer_pic01](https://user-images.githubusercontent.com/47690174/153044414-864e2757-e716-46d1-af8b-dcdb9ed5255d.png)

In GGMax 2022_02_11

![snowy_cabinet2FBX_IMPORTER_GGMax_2022_02_11_pic01_pic01](https://user-images.githubusercontent.com/47690174/153044516-66ad5c2f-e53c-4d40-acc7-8fab2254a4eb.png)

So, I tried as GLB and this was the best

![snowy_cabinet2GLB_IMPORTER_GGMax_2022_02_11_pic01_pic01](https://user-images.githubusercontent.com/47690174/153044754-fb4fceeb-739a-48e2-bd2d-2c89759e0ec1.png)

**CONCLUSION**
GGMax fail with the X and FBX file, but it works as expected with GLB. :)

**Note:** notice the mem in the above pics, real mem from 13 thru 15 GB looks to me too much just for a cabinet with a few winter stock trees. :)
