### ISSUE TITLE
GGMAX 2022-02-04 AI weapons floating in air

### ISSUE THREAD

**Issue by PaulFox12** [TheGameCreators/GameGuruRepo#1969]
AI weapons float in the air after the character dies in the latest build, tried this with multiple characters and weapons.

![AI guns floating](https://user-images.githubusercontent.com/78652980/152647184-87ffcf60-9dd4-4651-8b60-dfcd270eba5c.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Yes this one has been fixed from another report. When character went direct to ragdoll, the weapons did not get their physics. They do now, whether the character dies from ragdoll or via deathanim.
