### ISSUE TITLE
DX11 Lighting issue

### ISSUE THREAD

**Issue by Emperor2000** [TheGameCreators/GameGuruRepo#197]
There are major issues with the lighting. See for yourself:

Before:
![schermopname 633](https://user-images.githubusercontent.com/38536470/39005552-d030bd72-4400-11e8-88ae-602876100be7.png)
After:
![schermopname 1448](https://user-images.githubusercontent.com/38536470/39005566-d8a87c06-4400-11e8-901e-882ea934302b.png)
Before:
![616done](https://user-images.githubusercontent.com/38536470/39005607-ecf6873e-4400-11e8-8975-bc09796be18b.png)
After:
![schermopname 1454](https://user-images.githubusercontent.com/38536470/39005629-fce2f70e-4400-11e8-900e-3f60dc6fd868.png)

**Comment by Emperor2000** [comment]
If you ask me before looks a thousand times better..

**Comment by Emperor2000** [comment]
No I haven't, that might make a difference. Yet I am guessing it shouldn't
look like that right? Since it doesn't really look like an improvement (to
me)?

2018-04-20 3:18 GMT+02:00 Lee Bamber <notifications@github.com>:

**Comment by Emperor2000** [comment]
UPDATE: Most of these issues have been fixed!

**Comment by LeeBamberTGC** [comment]
Would you like to close this issue and create new ones specifically on the issues that are not currently resolved with the latest Public Preview build, thanks.
