### ISSUE TITLE
GGMAX Enhancment - Generic Climbing

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1970]
Attached is version 1 of a generic climbing script plus editor placeholder object.
Object will turn invisible in game.
[climber_v1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8008533/climber_v1.zip)

**Comment by UltraVox001** [comment]
Works very well. :)
I don't see the difference with Ladder. It's an invisible ladder, like when I set Material Alpha Cliping to 0 on a Ladder.

Good game. :)

**Comment by Necrym59** [comment]
Yes it essentially the same but nicer to use in the editor (for those not yet used to such things ie: dummies lol) MAX may like the idea they want it easy for people. works great on cliffs etc.

**Comment by UltraVox001** [comment]
For the moment I tried with a wall placed at the bottom of a cliff. But this cliff is rocky, with shapes that the wall cannot match. Surely several walls are needed to adapt to the "terrain".

**Comment by Necrym59** [comment]
have you tried several wall one after another

**Comment by UltraVox001** [comment]
Your script will erase it :)
With Ladder script, maybe... But I don't think Ladder script reacts well to multiple rock shapes.
You have to try with several walls but that doesn't make it easy when you have "climbable" mountains everywhere.

**Comment by UltraVox001** [comment]
I think if the script needs to repeat on multiple walls, the text at the bottom of the screen should be optional.

**Comment by AmenMoses** [comment]
Why require libraries if you aren't using them?

**Comment by UltraVox001** [comment]
> Why require libraries if you aren't using them?

It is true that the appearance of the object does not change in the editor, even after pasting the Behavior to it.
The climber_placeholder.dds image does not appear anywhere.

**Comment by Necrym59** [comment]
bah forgot about the libraries bit have to delete them lol out was using them for script testing stuff

**Comment by Necrym59** [comment]
It is true that the appearance of the object does not change in the editor, even after pasting the Behavior to it.
The climber_placeholder.dds image does not appear anywhere.

umm you lost me a bit what do you mean climber_placeholder.dds image is only the placeholders object image

**Comment by UltraVox001** [comment]
I don't understand the usefulness of the climber_placeholder.dds image.
I thought this image was going to appear somewhere.

**Comment by Necrym59** [comment]
only for seeing positional purposes in the editor

**Comment by UltraVox001** [comment]
Hmm, then I must have made a mistake. In the editor I see my object to climb. But shouldn't I also see this image on top of this object, in the editor?

**Comment by Necrym59** [comment]
you should have somthing like this in yourb editor
![editor](https://user-images.githubusercontent.com/95015657/152657752-cc29e910-4246-4b9a-9ca8-14fd60808e89.jpg)

**Comment by UltraVox001** [comment]
No I have nothing but my object. I think the "climber" folder is misplaced in my architecture.

You say put it in entitybank.
I tried :
- Documents\GameGuruApps\GameGuruMAX\Files\entitybank\
- Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user
- C:\Program Files (x86)\GameGuru Max\Max\Files\entitybank

But nothing appears as in your image.

**Comment by Necrym59** [comment]
Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user\climber is where i have mine

**Comment by UltraVox001** [comment]
Yes, that is precisely where it is. Weird.
![c1](https://user-images.githubusercontent.com/96718175/152658370-b30d3b49-1ced-4e47-b98f-59ceef86a894.jpg)
![c2](https://user-images.githubusercontent.com/96718175/152658372-2b732b69-f2dd-4572-a8a1-40ab2040c995.png)

**Comment by Necrym59** [comment]
might be a transarency issue try turning it off in materials section

**Comment by UltraVox001** [comment]
Transparency is disabled. I turned it on and then off, but nothing more.
This image does not display on any other object. I tried several walls.
Another mystery that will take me 2 days to realize that it's just stupidity :D

No, the cliff is not part of Max. I took the first "Rock" I found. It's an old thing, probably from the days of Reloaded. But it's a detail. With or without a cliff, I'm supposed to see the image on the blue wall.

**Comment by Necrym59** [comment]
well just pu any old image on it for positional puposes until you find out meanwhile im doing rock climbing 
![rock_climbing](https://user-images.githubusercontent.com/95015657/152659080-7274fc86-30d4-4970-b773-00f26a4c9f6a.jpg)

**Comment by Necrym59** [comment]
Just in case its corrupted here is the image im using
[climber_placeholder -Image.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8008930/climber_placeholder.-Image.zip)

**Comment by Necrym59** [comment]
LOL you have nearly as many assetts as me

**Comment by UltraVox001** [comment]
Even the script doesn't work anymore.
I'm tired with this.
I will start again tomorrow morning. :)

**Comment by Necrym59** [comment]
Yes i find removing stuff and restarting max clears it cacheSent on the go with Vodafone
-------- Original message --------From: UltraVox ***@***.***> Date: 6/2/22  8:23 am  (GMT+10:00) To: TheGameCreators/GameGuruRepo ***@***.***> Cc: Necrym59 ***@***.***>, Author ***@***.***> Subject: Re: [TheGameCreators/GameGuruRepo] GGMAX Enhancment - Generic Climbing (Issue #1970) 
Even the script doesn't work anymore.
I'm tired with this.
I will start again tomorrow morning. :)

**Comment by UltraVox001** [comment]
I started all over again this morning. I still don't see a picture.
I'm lost... There's something I'm missing!
Here is my map : [Climb.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8009510/Climb.zip)

**Comment by Necrym59** [comment]
see what you get here - screen shot it
[Climbupdated.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8009535/Climbupdated.zip)

**Comment by UltraVox001** [comment]
It works ! What is my mistake ?
![c1](https://user-images.githubusercontent.com/96718175/152669905-849b55e3-2b53-40df-a4d2-fc8e0b8e42a5.jpg)

**Comment by Necrym59** [comment]
not sure you selected or added the the placement object into your object list you select it like any object

**Comment by UltraVox001** [comment]
Yes, because I have no other choice!
I have to start by adding the blue wall to stick your Behavior to it.
But once it's done, I don't have access to the Placement object.
![c1](https://user-images.githubusercontent.com/96718175/152670332-ffb91946-b1d1-4d2b-b6c4-c17beacb0a33.jpg)
So, where is he ?
How to select it ?

**Comment by Necrym59** [comment]
really goo for unusual situations like climbing down a well or climbing an encased or covered ladder thats part of a model or mineshafts etc

**Comment by Necrym59** [comment]
just select add then look in user then in climber folder

**Comment by Necrym59** [comment]
just add it to the map like any object (like you would a ladder)

**Comment by UltraVox001** [comment]
Okay ! So I no longer need the wall, only the placement object. Here's what I didn't understand. :) I didn't risk seeing your image appearing instead of the wall, because I didn't know that you had to go and find another object (the placement object). I thought the wall would (visually) turn into a placement object :)

Well, it works fine now :)
Thanks for the explanation.

**Comment by Necrym59** [comment]
no problems sorry, i should have put some instructs in if it get put in official Max then the scripts and objects would be easily available (no hunting for it)

**Comment by UltraVox001** [comment]
I just have to reassign the Behavior to the placement object, because it's the wrong one, by default.
Other than that, it works perfectly. :)
![c1](https://user-images.githubusercontent.com/96718175/152670664-9307d8f1-b5ec-479e-825b-972efe5fb536.jpg)

**Comment by Necrym59** [comment]
great have fun with it

**Comment by UltraVox001** [comment]
Yes, I'm already having fun with it. :)

As I told you yesterday, it took me 2 days to realize that it was nothing :) If I don't know the exact procedure, I'm not likely to understand. :) And so, I expect a result that will never happen. :)

In your .zip, you should just put the "climber" directory in entitybank/user (to avoid rookie mistakes and possible disappearance of the script). And add a simplified explanation : **After assigning the Behavior to any wall/object, with all the necessary settings on this wall/object, click on Add (top left) and go to User/Climber and select the placement object. Then you can remove the wall/object and use that placement object, replacing the wall.**

**Comment by UltraVox001** [comment]
It's strange. I changed the width of the placement object because the wall is wide. And now it doesn't work anymore. So, I deleted it from the map, then re-selected the placement object in the object list. It appears on the map with its original size. Very well. But it no longer works. I think he doesn't like Scale's changes.

**Comment by Necrym59** [comment]
Make sure the front is facing you on the object
As for the install, sorry it was defaulted to max directory structure not user folder in docs. 
If they put it in the object would be placed in the GameGuruMAX\Max\Files\entitybank\Max Collection\Climber folder and the script will go to the GameGuruMAX\Max\Files\scriptbank\objects\folder

**Comment by UltraVox001** [comment]
He is Front.
I only modified the Scalling.
![c1](https://user-images.githubusercontent.com/96718175/152671218-8fa13ab5-5378-44d4-9ee2-032fd2c3f9a4.jpg)

**Comment by Necrym59** [comment]
should be ok reapply the script incase its cached wrong

**Comment by UltraVox001** [comment]
Max doesn't want to know anything.
Reassigning the script, Save, then Close, Reopen, always the same.
Can you test the map ? 
[Climb.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8009647/Climb.zip)

**Comment by Necrym59** [comment]
Tried yours it failed time and tima again, have no idea why, just made another map and its fine.
[Climb2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8009719/Climb2.zip)
simple way out of thi is
ensure your placeholder files are in
Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user\climber - 4 files in here
and your script is here
\Documents\GameGuruApps\GameGuruMAX\Files\scriptbank\climber - 3 files
Restart Max fresh
start a new map and see what happens

**Comment by UltraVox001** [comment]
Yes it works, even after changing the Scaling. I don't know why it's not working on my map.
I confirm on all the files are in the right place. Without it, it would never have worked before.

**Comment by Necrym59** [comment]
I have no idea, maybe that map got corrupted or somthing.

**Comment by Necrym59** [comment]
Heres an easier/cleaner method
rename the climber in your entitybank to _markers
thats it now restart max
now when you want one in the editor just select it from the Game Elements section.

**Comment by UltraVox001** [comment]
Done. :)

**Comment by Necrym59** [comment]
When I thnk about it now its actually a placement marker anyway.

**Comment by Necrym59** [comment]
An editor element and script to place Climbers on the maps.
Useful for climbing tunnels, chimneys, mineshafts, cliffs, vines, drainpipes, window entry, vents, airshafts etc. Use for ladders /shafts or vents built into existing models.

To use - Just select climber from the markers and place, scale to suit etc. Behaviour section you can change prompts etc. for differet uses.
[climber_v2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8045238/climber_v2.zip)

Sample map:
[Climb_Sample.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8045241/Climb_Sample.zip)
![climbers](https://user-images.githubusercontent.com/95015657/153521093-4e098908-1dd5-4cf5-bc37-3531f0b693d6.jpg)

**Comment by UltraVox001** [comment]
I'm on your test map. When I arrive at the top of a climber, I systematically fall all the way down. On all climbers. And for some reason, the watchtower climber is visible in Test Mode. Others don't.

For me, impossible to climb up without falling.
Same for the well. I fall back down without knowing how to get out of there.

**Comment by UltraVox001** [comment]
What works for me:
- The boxes
- The window of the blue building
- The tree
- The large cliff behind the tower
- The hole in the rocks (on the right).

The rest is impractical.
Impossible to climb on the roof of the building.
Impossible to climb the watchtower.
Impossible to get out of the well.

**Comment by Necrym59** [comment]
weired perhaps its the version change you can always take that number up to 8 and see waht happens

**Comment by UltraVox001** [comment]
We should wait until tonight for you to have a version very close to mine. There are a lot of changes internally. My version is infinitely better optimized (lights, shadows, collisions, etc...).

**Comment by Necrym59** [comment]
Try sacaling the Z a bit on that one and see what happens, can you climb the drain pipe!

**Comment by UltraVox001** [comment]
Yes, it was clearly the Z that was the problem. :)
I climb on the roof without any difficulty. :)

**Comment by UltraVox001** [comment]
I can climb everywhere now.
Just increase Z, a little.
The initial setting is too small.

**Comment by UltraVox001** [comment]
I will try to reset your script to 3 (instead of 8).

**Comment by UltraVox001** [comment]
hmm, at 3 it doesn't work. However I increased the Z scale on the problematic objects.
I go up the script to 5.

**Comment by UltraVox001** [comment]
To make sure it works everywhere:
- Script set to 8
- Raise Z
- Increase Y (it must exceed the object)

**Comment by Necrym59** [comment]
yes the last one is obvious is suppose
Z can be done in the editor
I will update the script to 8 that compensator should cover everyone.

**Comment by Necrym59** [comment]
So what do you think, it has a lot of uses im using it to climb into a vent system on a map.

**Comment by UltraVox001** [comment]
I will test it right away. But I had modified your map accordingly. Should I try on the original map to check if your new settings are better, without any adjustments in the map?

**Comment by Necrym59** [comment]
meh better to adjust on somthing yourself MAX embeds the scripts in mapfiles so they can get twitchy when changed. better to do fresf things. Im also now working on a hanging script :)

**Comment by Necrym59** [comment]
If your refering to the textures not being retained on the rocks thats a Max bug been reported ages ago
i suppose its going to be a case of adjusting climbers to suit your needs really, but thats what its for. Plus we have version differences so i cant check yet perhasp tommorrow will reveal things.

**Comment by UltraVox001** [comment]
I fixed the bug for the Climb above the crates. He didn't have the right Behavior.
So I checked the ladder. But she has the correct Behavior. I don't know why it shows as TestLevel.

**Comment by UltraVox001** [comment]
No, I'm referring to your script which displays in TestLevel mode. He should not.

Textures are not your problem. :)

**Comment by Necrym59** [comment]
As i said Max embeds scripts and has a hissy fit when fiddled with, delete the offending object and place a new one and it should be fine.

**Comment by UltraVox001** [comment]
It's ok now.

**Comment by Necrym59** [comment]
Cool, enjoy im getting pizza!

**Comment by Necrym59** [comment]
Also updated to version 5
- Should fix some issues with dropdowns as it has a deeper(z) in the placeholder to begin with now.
- Also added the option to turn on/off A and D keys to exit the climber. People just have to edit the prompt text if they use it.
[climber_v5..zip](https://github.com/TheGameCreators/GameGuruRepo/files/8052684/climber_v5.zip)

**Comment by UltraVox001** [comment]
Thank you.
I downloaded and installed it. I will test it this morning, a little later.

**Comment by UltraVox001** [comment]
I tested the script and everything seems to work fine.

**Comment by Necrym59** [comment]
Excellent, i can rest in peace on this one.

**Comment by Necrym59** [comment]
Attached is V6 of the climber script and markers
- Now includes climbing speed option.
This should be the final release for all intents and puposes.
[climber_v6..zip](https://github.com/TheGameCreators/GameGuruRepo/files/8105559/climber_v6.zip)

**Comment by UltraVox001** [comment]
Tested and approved. :)

**Comment by rvanner** [comment]
@LeeBamberTGC Please grab the latest version and add it to the build.
Thanks @Necrym59 and @UltraVox001

**Comment by LeeBamberTGC** [comment]
@rvanner Added to next internal build.

**Comment by Necrym59** [comment]
Attached V7
- Fixed the readability of the behaviour prompts/options and their variables
- Internal fix for use of the default prompt to display when climbing ladder even after the E key option to mount is used. Turning off the Default prompt then only uses the E to mount prompt.
[climber_v7..zip](https://github.com/TheGameCreators/GameGuruRepo/files/8145630/climber_v7.zip)

**Comment by Necrym59** [comment]
Updated to V18 same code base as ladders now to remove some glitches with the latest build.
-  Now has allowances for sound for climbing and exiting climb.
-  Climber placeholder model redone for more reliable climbing.
[climber_v18..zip](https://github.com/TheGameCreators/GameGuruRepo/files/8147869/climber_v18.zip)

**Comment by UltraVox001** [comment]
Whatever I do, the Climber is always displayed in the TestLevel.

**Comment by UltraVox001** [comment]
Ok. Tested and approved. :)

**Comment by Necrym59** [comment]
Version 19 Update
Allows for climber grip adjustment in certain situations.
[climber_v19.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8341635/climber_v19.zip)

**Comment by Necrym59** [comment]
Climber Version 20
- Brought into line with ladder script v20
- Option to hide/show arms/weapon while climbing
- Default is Hide Weapon/arms
[climber_v20.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8401802/climber_v20.zip)

**Comment by synchromesh62** [comment]
Got to hand it to you.
Awesome script.

**Comment by Necrym59** [comment]
Climber Version 23
- Fixes problems with rotations
- Better gripping
- [climber_v23.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9077984/climber_v23.zip)
