### ISSUE TITLE
Zones need height limit

### ISSUE THREAD

**Issue by ivanski1983** [TheGameCreators/GameGuruRepo#1971]
I can place a text zone or win zone and if I'm on another floor it triggers it...

example:
https://youtu.be/n7u5RpPyOu8

text zone placed on ground and it triggers on all floors

**Comment by UltraVox001** [comment]
Yes, it's the same problem with Audio Zones (when they work...).

**Comment by mav3r1ck1981** [comment]
@Kasseyus this has been implemented as standard
