### ISSUE TITLE
Weapons stop shooting_GGMax_2022_01_28 [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1972]
Weapons stop firing before the magazine is completely empty.
And even when re-load level to test mode, it keeps without firing till you reload it.

assault_rifle

![assault_rifle_stop_shooting12_GGMax_2022_01_28_pic02](https://user-images.githubusercontent.com/47690174/152657298-a2969493-1df4-4af5-9b00-87a3dc841cf3.png)

gun_machine

![gun_machine_stop_shooting32_GGMax_2022_01_28_pic01](https://user-images.githubusercontent.com/47690174/152657316-35d124a1-54b6-4691-a08b-38e409e471a9.png)

Notice assault_rifle still has 23 bullets and the gun_machine 30.

**Comment by AmenMoses** [comment]
It's intentional, i.e. a misfire or blockage.

There is a gunspec file setting for it IIRC.

**Comment by 3coms** [comment]
@AmenMoses 
Thanks for clarifying, have no idea about it, does no use dealing with guns, but now need to break something ;)
