### ISSUE TITLE
GGMAX - Shadow Issue

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1976]
Shadows are not being applied properly on some objects, namley in this example the desert cliffs opened/single sided vector objects
![shadows](https://user-images.githubusercontent.com/95015657/152694485-6c4bbf54-1e0f-4ea3-81cb-76f1e1a58beb.jpg)
.

**Comment by LeeBamberTGC** [comment]
@bond1mjb Can you seal these assets as that will fix the shadow issue, ask Chris for the original files.

**Comment by bond1mjb** [comment]
@LeeBamberTGC   Sure, I've sent an email to Chris.

**Comment by bond1mjb** [comment]
@LeeBamberTGC  Chris says he no longer has the files for these assets.  So without any way to get these into 3ds Max for editing, I'm afraid I can't do anything to fix this.

**Comment by LeeBamberTGC** [comment]
@bond1mjb If they are static, there 'could' be a way for MAX to load in a DBP and export an OBJ, would that be of help?

**Comment by bond1mjb** [comment]
@LeeBamberTGC Oh sure, OBJ would work. I can import anything other than DBO.

**Comment by LeeBamberTGC** [comment]
@bond1mjb I will email you soon :)

**Comment by bond1mjb** [comment]
@LeeBamberTGC Here are the fixed desert cliffs, already converted to DBO, just copy over the old ones.  
[Desert Collection CLIFF SHADOW FIXES.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8577721/Desert.Collection.CLIFF.SHADOW.FIXES.zip)

**Comment by LeeBamberTGC** [comment]
@bond1mjb These work great, and the Canyon Offensive level works well with the modified assets.

**Comment by bond1mjb** [comment]
@Lee Bamber ***@***.***> Oh sure, OBJ would work. I can import
anything other than DBO.
