### ISSUE TITLE
GGMAX - Imported Character Behaviour

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1978]
This attached character animates/reacts properly with behaviours but will not move from its placed position and i cant find any reason for it. 
[Terrorist.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8011231/Terrorist.zip)

**Comment by UltraVox001** [comment]
There are several animations that cause problems in the importer. Selecting them unchecks the "Animate Preview" box. They are like blocked. You cannot play multiple animations. The problem could come from there.

**Comment by Necrym59** [comment]
Dunno its strange im not expert on aniamated things its weird its animations all work he runs, reacts walks etc as he is supposed to but just does it on the one spot paerhaps one of the animation experts may discover what causes it.

**Comment by UltraVox001** [comment]
In the importer ?
For me, the first 3 or 4 work. Not the others.
I think there are several things to improve in this importer. It is far from operational.

**Comment by Necrym59** [comment]
Try the sample i put up in gam and youll see what i meanSent on the go with Vodafone
-------- Original message --------From: UltraVox ***@***.***> Date: 7/2/22  7:28 pm  (GMT+10:00) To: TheGameCreators/GameGuruRepo ***@***.***> Cc: Necrym59 ***@***.***>, Author ***@***.***> Subject: Re: [TheGameCreators/GameGuruRepo] GGMAX - Imported Character Behaviour (Issue #1978) 
In the importer ?
For me, the first 3 or 4 work. Not the others.
I think there are several things to improve in this importer. It is far from operational.

**Comment by UltraVox001** [comment]
He is completely motionless.

**Comment by Necrym59** [comment]
Attach character attack brhaviourSent on the go with Vodafone
-------- Original message --------From: UltraVox ***@***.***> Date: 7/2/22  7:52 pm  (GMT+10:00) To: TheGameCreators/GameGuruRepo ***@***.***> Cc: Necrym59 ***@***.***>, Author ***@***.***> Subject: Re: [TheGameCreators/GameGuruRepo] GGMAX - Imported Character Behaviour (Issue #1978) 
He is completely motionless.

**Comment by UltraVox001** [comment]
It was already done. He's not moving. Surely something to do in the importer, and that I do not like you. To begin with, Character Settings are missing for this character (in Max).
![CharacterSettings](https://user-images.githubusercontent.com/96718175/152765688-8831b884-0d8b-475e-b8cb-57b00ae4d223.png)
So I can't make it an enemy, or change its life points. I restarted 3 times.
I'm no expert on animated stuff either. I have much less trouble with static objects. :)

**Comment by Necrym59** [comment]
I have since come to understand this has somthing to do with the new animation system, there is no support for older style models unless a script is created for them. This is ok but not very plug and play. It would be nice and important to either get the character creator assets DLC out as soon as possible for us non-modellers and/or create a crossover animation matrix for existing older chracters. Otherwise we are all stuck with nothing but the few supplied.

**Comment by UltraVox001** [comment]
Me too.
