### ISSUE TITLE
MAX - 2022.02.04 - Editor vs Test Game vs Standalone - Trees

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1979]
I wonder if this issue is related to show\hide trees option in the editor?

**Issue:**
This shot is in the Editor - note there are no trees over water and if you look around the bank there are not many trees either

![Trees 01 - Editor](https://user-images.githubusercontent.com/12246318/152704472-c8cfffa2-ddc9-4b63-ac61-2bb422d26df6.png)

This is in Test-Game - note there are trees over water, and trees on the bank

![Trees 02 - Test Game](https://user-images.githubusercontent.com/12246318/152704485-c0181451-146c-4549-a39c-35ed374a3b6f.png)

This is in Standalone - offending trees are rightly not there

![Trees 03 - Standalone](https://user-images.githubusercontent.com/12246318/152704489-aeab4fee-e732-40c4-8c30-239f9a62a68a.png)

**Comment by ZakJudges** [comment]
Hi @OldFlak, there has been some recent work on the tree system which should be in the first post-ea update. Could you let me know if you still experience the issue after trying out that build? :)

**Comment by PaulSJ** [comment]
Is this still an issue in the current version?

**Comment by OldFlak** [comment]
Ah, yes meant to close this - not seeing that now :)
Thanks Paul
