### ISSUE TITLE
DX11 Update vegetation size

### ISSUE THREAD

**Issue by Emperor2000** [TheGameCreators/GameGuruRepo#198]
It seems as if vegetation loses it's quanity, height and width settings when importing a dx9 map to dx11.

**Comment by Emperor2000** [comment]
Completely forgot about this! Sorry, It's odd because it only seems to have occurred a few times, but not every map had the issue.

**Comment by boltactiongaming** [comment]
I was able to find what is impacting the vegetation draw distance - it's tied to the occlusion slider.
If you slide it all the way to 0 vegetation will go to maximum draw distance.  If you turn it up, it only goes out about 2000 units.

**Comment by LeeBamberTGC** [comment]
@Emperor2000 : Can you confirm the occlusion slider makes the effect described above, thanks!

**Comment by plemsoft** [comment]
@Emperor2000 Tried a old DX9 map in DX11 , and the occlusion slider did not have any impact on vegetation  , also they had the correct  height and width.

So i assume this has been fixed in a later version , can you confirm this , thanks :)
