### ISSUE TITLE
MAX - 2022.02.04 - Test Game vs Standalone - Airborne Grass and Trees

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1980]
Grass and trees being airborne are prevalent in this build as likely reported already.
Interestingly the issue is much less severe or not even present in Standalone builds.

Here is one spot in test-game - grass and trees up in air

![TGvsEX - Grass Trees - Test-Game](https://user-images.githubusercontent.com/12246318/152704628-2e49eabb-d6ec-4446-b587-2eea226c93bb.png)

Here it is the same location in Standalone - everything is planted

![TGvsEX - Grass Trees - Standalone](https://user-images.githubusercontent.com/12246318/152704635-797fe6d2-8508-4ec8-873a-e26dd7a5a334.png)

This shot is also in a Test-Game run

![image](https://user-images.githubusercontent.com/12246318/152704698-ad582c9b-31af-4cdb-a967-2d2edf587254.png)

In Standalone it is almost all grounded

The grass issue is not restricted to areas where terrain has been edited, but it is more prevalent in those areas.

Perhaps part of the problem is that the grass is following the original un-sculpted terrain?

**Comment by ZakJudges** [comment]
Hi @OldFlak, I wasn't able to reproduce this issue, though I do remember encountering it early last month. Are you still experiencing it in the latest build? If so, could you send me a .fpm file showing the issue? :)

**Comment by OldFlak** [comment]
Steering away from outside levels due to poor performance and player movement issues. 

But not seeing this issue atm, so will close - Thanks Zac :)
