### ISSUE TITLE
MAX - 2022.02.04 - Test Game vs Standalone - Lighting

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1981]
Lighting is better in Standalone:

In this building note the lighting - how the center support frame with the fans has outside influence:

![TGvsEX - Interior Lighting - Test Game](https://user-images.githubusercontent.com/12246318/152704996-68b6fe4b-30bf-492b-b2bc-5d4077234a3c.png)

This is how it looks in Standalone - nice!

![TGvsEX - Interior Lighting - Standalone](https://user-images.githubusercontent.com/12246318/152705003-a49f756a-3cbe-4fce-9f41-461994a1aa79.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb A nice lighting-related one, see if you can reproduce with a small stock asset level.

**Comment by OldFlak** [comment]
This is no longer an issue that I can produce so closing :)
