### ISSUE TITLE
Suggest better terrain blending for less-ruined look

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1983]
Textures do not blend very well

![Textures Do Not Blend Very Well](https://user-images.githubusercontent.com/12246318/152705216-19fb6fbe-c622-4a4f-be73-341d23a913a6.png)

**Comment by OldFlak** [comment]
No - not an enhancement - tis clearly a bug that ruins the look :)

See #2053

**Comment by PaulSJ** [comment]
@OldFlak Do you have a level I can load to see this issue? I can't replicate what you are seeing
