### ISSUE TITLE
MAX - 2022.02.04 - UI Layout In A Muddle

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1984]
I get the whole make it *New User Friendly* idea, but is it not creating an inconsistent UI layout with unnecessary clutter, scrolling, and clicking?

For example - unnecessary clutter in places where it can be avoided.

![01 - UI Mess](https://user-images.githubusercontent.com/12246318/152706145-8b5f5d31-1a1b-4f34-ad71-e73566979226.png)

Also controls being place inconsistently just creates confusion.  

![02 - UI Mess](https://user-images.githubusercontent.com/12246318/152706302-cedcea54-e4e2-450c-b2fe-0fba58059413.png)

Tis the same reason MS don't make cars - we need the steering wheel to be in the same place :)

**Comment by plemsoft** [comment]
@[rvanner](https://github.com/rvanner) FYI: new design ?

**Comment by LeeBamberTGC** [comment]
@rvanner The behavior tab ONLY includes parameters given by the behavior script LUA file. The palette and sliders for range are more akin to the grass and terrain textures UI design. I agree there might be an advanced layout option which can reduce the real estate for established and experienced MAX users.  One for the list perhaps.

**Comment by OldFlak** [comment]
Thanks for considering :)

**Comment by rvanner** [comment]
I'll add these to a Post EA list for now and close this down. I am sure we can improve the UI in another review later on.
