### ISSUE TITLE
Memory not freed after creating new level

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1985]
- Create a new project
- Create new level and bring up terrain generator
- Exit back to storyboard without generating terrain
- Repeat a few times
- Note the memory used increases every time you start the terrain generator

I did this 6 times and ended up using over 6GB of memory 
![Screenshot 2022-02-07 112042](https://user-images.githubusercontent.com/32545391/152778906-ac992498-21c1-45b6-9b00-2ae41915da75.png)

**Comment by UltraVox001** [comment]
@ZakJudges 
I can't find the option to show these stats in Max.
Is it an external program ?

**Comment by UltraVox001** [comment]
It's ok thank you :)

**Comment by UltraVox001** [comment]
Here I just opened a project that contains a map. But I did not load the map.
![OpenProject](https://user-images.githubusercontent.com/96718175/152824138-406d9a09-64fa-4cc6-b3e6-fe1e287e33d1.png)
