### ISSUE TITLE
AI / Trigger Zones - Alerted Enemies Reset

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#1986]
When you walk over a trigger zone while enemies connected to that zone are dead, they will respawn and I think their stats(like Health) are reset as well. 
Video: https://www.youtube.com/watch?v=JjV5MIvNf0g

The same thing happens when the enemies are connected to alert each other when they see the player.
Every time the player goes into hiding and enemies spot the player again, enemies health resets and dead enemies that are connected get resurrected.

**Comment by Necrym59** [comment]
Now thats a bug that could be made into a Respawn Zone feature Lee.

**Comment by LeeBamberTGC** [comment]
Was a nice feature, but made killing a squad like killing mushrooms :) Fixed for next build.
