### ISSUE TITLE
Reduce shadow memory usage for MEDIUM and LOW graphics settings

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#1989]
If confirmed the shadows are taking 800+MB, reduce the resolution the shadows use for MEDIUM and LOW settings when set from the SETTINGS and from the in-game menu.

**Comment by LeeBamberTGC** [comment]
@PaulSJ I only know the shadow settings superficially, but I have snapped the settings which controls the HIGH/LOW setting, the shadow settings and the current resolutions, and from this I suggest choosing smaller sizes for the MEDIUM and LOW:

![image](https://user-images.githubusercontent.com/35840583/153028377-31898c54-cb11-47cd-85ac-e1c9ce3ffaab.png)

**Comment by plemsoft** [comment]
@LeeBamberTGC @PaulSJ I will make it dynamic so we dont pre allocate if not needed , and will change Low/Medium/High so resolution goes down (if not already set low).

Perhaps later we could look at lowering the shadow distance to perhaps 250000 (currently 500000) , and set the resolution to 1024 by default , the lower shadow distance will give the same shadow quality using 1024 as the camera get closer when making the shadows. so should not give any differences other then shadow bias ... might have to be adjusted.

**Comment by PaulSJ** [comment]
@plemsoft I think reducing the shadow range would only let you remove the closest cascade, since reducing it by half for example would replace each cascade with the level that used to be one higher. This would leave you with a new cascade at the lowest level which you can remove and keep the same quality. It wouldn't let you adjust the shadow map resolution.

**Comment by PaulSJ** [comment]
@LeeBamberTGC I think those changes are on a different branch since I don't have any Graphics Settings drop down box from (1) in your screenshot. Is it safe to merge the master into my branch or should I merge another branch to get these changes?

**Comment by plemsoft** [comment]
@LeeBamberTGC I made it dynamic, and merged pauls transparent shadows changes , and we now use way less mem. All committed.

I will add the lower res for Medium/Low settings tomorrow :)

**Comment by LeeBamberTGC** [comment]
@PaulSJ Latest master is pretty up to date from this morning, so I think you will be safe merging it to your branch to get the extras you need.  I plan to do a big merge and test later this evening, just waiting for everyone's final commits :)
