### ISSUE TITLE
Gameguru Indoor Lightmapping bugs

### ISSUE THREAD

**Issue by TheMECHAN1C** [TheGameCreators/GameGuruRepo#199]
Gameguru Indoor Lightmapping bugs.
The archive attached contains 2 maps. Both are renders after lights baking (F3).

1) TEST_Lightmapping_withstaticlights.fpm
I just baked static lights. 
BUGS: Blue static light appears only on some objects (boxes, crates, table), while there are no any blue lights on the walls, floor and ceiling!
2) TEST_Lightmapping_wp_withstaticlights.fpm
I put all construction entities (Bunker pack by Voodoo) on the following properties: 
Static - YES, Physics - NO. 
(According to this guide: http://gamegurureport.blogspot.com/2016/06/technique-evaluation-gameguru-interior.html?m=1)
The result is better, but still bugs! 
BUGS: Blue static light appears on some objects (boxes, crates, table), and on walls, floor, ceiling of certain bunker parts only!

[TESTs.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1929136/TESTs.zip)

**Comment by LeeBamberTGC** [comment]
I loaded the FPM (which partially loaded with the stock assets), and noticed one of the entities was dynamic, which will not be lit by lightmapping. The scene lightmapped as expected with the static light affecting anything static (attached is a shot).  Marking this old bug as fixed.
![image](https://user-images.githubusercontent.com/35840583/60273333-d1709c00-98ed-11e9-9030-3245e9d0c0a8.png)
