### ISSUE TITLE
No Cacti!

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1991]
In the latest update of trees we've now lost the cacti. 

@PaulSJ Can you process ALL the cacti trees that Mark created and submit to Lee by Wednesday?

@bond1mjb Do you need to supply new versions of the cacti to Paul?

**Comment by bond1mjb** [comment]
@rvanner @PaulSJ   I included the new cactus billboard in the last set of downloads.   And there was also a  smaller cactus under the "bush" category.  

My original set of cacti included 10 variations, but I don't think we ever used all of them, just a couple.   If want me to export all of these variations using our new naming system I can do that today.

Here's a pic of the original set of cacti:
![cacti](https://user-images.githubusercontent.com/87768878/152942498-084f982f-8264-4594-9ee2-0e69600da4dc.jpg)

**Comment by rvanner** [comment]
@bond1mjb The more we have, the better the visuals in user's levels. So export any extra variation large cacti and the smaller ones can be added to the bush folder.

**Comment by bond1mjb** [comment]
@rvanner Ok, the larger ones in the back I'll treat as trees, and the smaller ones in front as bushes.

**Comment by rvanner** [comment]
@PaulSJ Lee says Mark has uploaded the Cacti, can you please integrate them today (Wednesday) so we can complete the biome styles?

**Comment by rvanner** [comment]
@dllllllllllb Can you import the smaller cacti into the Vegetation section of the Object Library please? Add a new Small Cacti section there. [DOWNLOAD LINK](https://drive.google.com/file/d/1F-DJUf9aMFnIp_6OxGYLYapIXuxKctAL/view?usp=sharing)

**Comment by dllllllllllb** [comment]
@rvanner When I'm importing Cacti using their albedo and normal, they don't look like they do in the screen shot above. (also there are no surface.dds in the files you sent me)

Cactus_var5 with specific color and normal for cactus_var5: 
![image](https://user-images.githubusercontent.com/61796872/153617266-4041f0e8-d8c9-4a41-a2b6-8a628855545f.png)

Cactis_var5 with color and normal in the main folder:
![image](https://user-images.githubusercontent.com/61796872/153617782-32196668-8983-4e48-abe9-72ac32a5dbc1.png)

Should I use what works best or maybe is there an updated version of these files?

**Comment by dllllllllllb** [comment]
@rvanner Here are the imported small cacti: [download link](https://drive.google.com/file/d/1ITmpIUrWezPF4wmUE29hXEMhT9BWkdLB/view?usp=sharing)

**Comment by rvanner** [comment]
@LeeBamberTGC See the link above, please add to the build!

**Comment by LeeBamberTGC** [comment]
Added for next weeks build

**Comment by LeeBamberTGC** [comment]
Added this THIS weeks build - easier to add asset and does not endanger stability on release day.
