### ISSUE TITLE
The Flicker Light Behavior is not controllable with a Switch

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1993]
The switch does not know how to turn on/off a Light if its Behavior is Flicker Light. In the TestLevel, all lights linked to the switch work, except the one that has this Behavior.
![Flicker Light](https://user-images.githubusercontent.com/96718175/152954422-77c69e14-2d87-4a5e-9dff-5a72f53e1979.jpg)

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
Great news. :)
If possible, try to fix the problem with the Spot Light Radius. It is systematically Reset at 45 degrees, and this prevents the developer from using it. These degree parameters are not memorized and it resets to 45.
![SpotLightRadius](https://user-images.githubusercontent.com/96718175/152986752-749cdbf2-593b-4618-be72-b7a6a912877a.jpg)

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Best as a new issue so the title reflects the bug reported, and may be assigned to a different team member based on the issue.

**Comment by UltraVox001** [comment]
It has already been reported several times, but it may have been "forgotten".
The current lighting is banal. It could be much nicer...
I don't know if someone already does it or not. It's been reported for weeks, months.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Understood. Assuming it is reported elsewhere, I can close this one :)
