### ISSUE TITLE
Test game is very slow before you can start playing and needs optimising

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1994]
@PaulSJ Lee asked me to assign this to you. Can you profile the processes taking place during the test game initialization to see if it can be optimised?

Lee mentioned that 400 DBO objects are created and then discarded which is a big hog. He thinks a new data structure is needed which could avoid this. Best you check in with @LeeBamberTGC about this when you come to this issue.

**Comment by PaulSJ** [comment]
@LeeBamberTGC Can you detail which functions I should be looking at to help me when I get to this issue?

**Comment by LeeBamberTGC** [comment]
@PaulSJ Yes indeed. The journey starts here: "physics_createterraincollision", and does the following:

1. Uses the most accurate terrain height data from the terrain system
2. Divides up the entire editable area into a 20x20 grid of tiles
3. For each tile, uses the 'bNewFloodFillTerrainPhysicsReducer' to work out a series of planes that represent the terrain physics we need for that tile
4. From the 'tile planes', we create a DBO object that re-uses vertex positions to keep within the 16-bit index buffer limit
5. For each DBO created, we create a physics mesh from it, and save out its BVH data to a file
6.. We hide all the DBOs created, so they do not get rendered, but keep the terrain physics generated for the test level

The idea for improvement is there is no need to do steps [4] through [6], and you can take the plane list and directly create physics from it, skipping the intermediate step.

The second performance hit is the nav mesh generation, but the terrain physics above is the more costly process and speeding that up will help with test level launching performance the most.
