### ISSUE TITLE
Navmesh creation

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1995]
Another area of optimisation that we would like you to review is the navmesh creation.

**Comment by PaulSJ** [comment]
@LeeBamberTGC I've not looked at the navmesh code before so I will need more info on this issue. Specifically the rough timeline of how the navmesh gets created and the functions that do those steps.

**Comment by LeeBamberTGC** [comment]
@PaulSJ Your journey will start when this function is called "game_createnavmeshfromlevel":

1. It first determines if any static objects have moved, or anything else that requires the nav mesh to be generated
2. If no, then the old nav mesh can be loaded in to skip the generation step
3. If yes, we generate a low resolution DBO object based on the height data from the terrain
4. This area is NOT the editable area but an area defined by the population of objects in the world, and restricts the size of the nav mesh to those objects for performance reasons
5. Once the DBO has been created for the terrain topography, all static objects are added to the DBO as limbs/meshes, creating a super sized object that represents the mesh we want to calculate the nav mesh from
6. The location of all trees are also added to the mesh, using simple cylinders in place of the real tree geometry
7. Finally the whole DBO super object is saved in the file "levelbank\\testmap\\rawlevelgeometry.obj"
8. This OBJ file is then passed to the RECAST part of the navmesh system to generate the real navigatable data for DETOUR
9. The function "g_RecastDetour.buildall();" does all this, and from here you are in the hands of the authors who created the industry standard Recast Detour system

Possible ideas for optimization include dividing the nav mesh work into tiles, doing only the one under the player/camera first and starting the game, then using threading to calculate the rest of the navigatable data in the background, and activate those portions as they are completed.  Another quicker option might be to see WHY recast takes so long on some typical meshes, or trying different configurations of mesh data to see if there is an optimal size/complexity that allows recast to perform quickly.  

The idea solution is that the nav mesh is generated in the background all the time, and when the user changes the static scene, recast immediately starts on that dirty rectangle so the navigation data is ready far in advance of the user pressing the test level button, and any jobs are localised to the changed area so should be quick once the user starts the edit-test-edit process.

**Comment by fearlesswee** [comment]
I'm all for the tile-based approach; currently there's only a single navmesh that is attempted to be generated for the whole level, which is often wildly inaccurate or outright skips portions of the level entirely. I 100% agree the ideal solution would be to divide the world into tiles, generate the navmesh for the tile occupied by the player start marker, then spawn them in and generate new navmesh data for neighboring tiles in the background as the player moves around the world. 

I would also like to bring back up the idea of having an _option_ on standalone export to pre-bake all the navmesh information for the entire level, to speed up load times in the final game ( #1602 ). This would be exceptionally useful for levels that are very detailed, and thus generating navmesh on the fly, even in the background, would take far too long.
