### ISSUE TITLE
Spawning enemies is bugged

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1996]
Spawning on enemies is bugged at present.

@ZakJudges Has a level that shows the issue.

**Comment by ZakJudges** [comment]
@rvanner I think it was @plemsoft that had this issue :)

**Comment by rvanner** [comment]
@ZakJudges Yes but I thought you said you had a level that showed it?

@plemsoft Can you share your fpm that shows Lee this issue?

**Comment by ZakJudges** [comment]
@rvanner I have a level that shows the ai walking through walls. I'll create a new issue for it

**Comment by davetgc** [comment]
I can confirm this: Spawned characters are pretty broken.

[The Ascent.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8079353/The.Ascent.zip)

[https://www.youtube.com/watch?v=pEN1oCR0QaE&feature=youtu.be](url)

**Comment by rvanner** [comment]
@davetgc Do you know if this is this still an issue?

**Comment by davetgc** [comment]
Hi,

Just tested, this works now.

**Comment by rvanner** [comment]
Thanks for checking Dave!
