### ISSUE TITLE
Characters able to walk through walls

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1999]
[Files.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8023350/Files.zip)

In the attached project, it seems like the navmesh doesn't generate properly, making the characters follow straight lines irrespective of any level geometry

**Comment by LeeBamberTGC** [comment]
@ZakJudges Could not reproduce. The mapbank in the ZIP contained a single file of 0KB called Step 1 (no FPM).

**Comment by ZakJudges** [comment]
@LeeBamberTGC Ah sorry, here's a copy:
[AI issue.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8048155/AI.issue.zip)

 I noticed my reported memory usage increases a lot during the nav mesh generation, I'm wondering if it could be an issue with that? :)

**Comment by UltraVox001** [comment]
Currently with the latest internal version, I cannot link a Character to a Flag. Looks like the Character doesn't have what it takes to be linked, unlike the Flags. All Characters I tried are provided by Max, + two Characters I created with CC. None can be linked to a Flag.

**Comment by UltraVox001** [comment]
@synchromesh62 
I can not do that. I could with the previous build, but not with this one.
![NoYellowBall](https://user-images.githubusercontent.com/96718175/153664787-5f74ea0c-47df-4832-90f6-980c602d800d.jpg)
Here is my map.
[EmptyMap2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8051434/EmptyMap2.zip)

**Comment by UltraVox001** [comment]
I also can't create an AI group linked to each other.
In Target mode (Shooter Games icon), this moves characters with the mouse, instead of linking them.
Strange.

**Comment by synchromesh62** [comment]
She is most definitely working for me and no issues so far ?
try another verify and reboot ?

**Comment by UltraVox001** [comment]
Max is reboot. See for yourself :)
[https://www.youtube.com/watch?v=yQ9l0Czrumw](https://www.youtube.com/watch?v=yQ9l0Czrumw)
Unable to connect AI to a Flag.
I can't invent it.

**Comment by UltraVox001** [comment]
With a map created with a previous build (1 week maximum), everything works.
![OkLink](https://user-images.githubusercontent.com/96718175/153670752-6277dcd4-7b13-46e4-97c3-bc143815de81.jpg)

**Comment by Granada1** [comment]
I can link but its not working well, also character only uses first flag
![FlagTest](https://user-images.githubusercontent.com/35897659/153672834-796ef240-a172-4ad0-a350-d5168f9eee49.png)

**Comment by UltraVox001** [comment]
Obviously there are Characters that work, and others that don't.
![OkLink](https://user-images.githubusercontent.com/96718175/153673936-2c09ba9d-23c3-4e19-83c1-32d9ee419d93.jpg)
This is not a problem with my version of Max (I've uninstalled and reinstalled 4 times this week).
This is a problem related to some Character of Max.

**Comment by UltraVox001** [comment]
Good. To finish with that, you just need to find a single character that works with PathFinding, so that all the others work too. This is the case of Astra. She didn't work until I found another working Character.
Strange!

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Using EmtyMap2 as the files to reproduce this. Loaded into this weeks internal build, first noticed the character is set to static, not a great start if you want her following paths :)

![image](https://user-images.githubusercontent.com/35840583/153876269-064364e8-7a08-407a-a0a8-03f5842f1c0a.png)

Selected her and pressed Y to switch her back to dynamic, and when do test level she started navigating around the walls as normal:

![image](https://user-images.githubusercontent.com/35840583/153876598-45bae45f-4049-4b09-b85d-1a962c95c62e.png)

![image](https://user-images.githubusercontent.com/35840583/153876750-31237215-8676-48d8-a188-75f03e9526e6.png)

Also plotting paths nicely around the sttatic objects. Can you provide a new FPM that shows the original bug report of CHARACTERS ABLE TO WALK THROUGH WALLS, thanks!

**Comment by LeeBamberTGC** [comment]
@UltraVox001 No worries, sounds like perhaps some map corruption with the visual logic data. If you can reproduce again from scratch, please do post a new issue with an FPM and I will attempt to reproduce.
