### ISSUE TITLE
Metalness effect seems to act more like a Specular effect

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#2]
The metalness image content comes through strongly on weapon when facing away from sun (illuminated by sun) and fades away when in shadow. Much like old spec maps would do. The effect is also solely bound to sunlight direction and does not seem to be affected by lights placed in the scene.

I may be completely wrong here but I was under the impression that metalness masking had something to do with reflection/cube mapping. I have provided a screenshot of my metalness test and the checkerboard type debug map I used:

![image](https://user-images.githubusercontent.com/5113534/34998619-7fdcfbc8-fad7-11e7-97cd-266e7e2369e4.png)

**Comment by plemsoft** [comment]
To be able to make metal on a object you need to combine the metalness with a gloss texture or you will get a results like in the picture. The generic gloss that are added to a objects with missing _gloss texture is setup like a neutral material. 
Try to add a dark/black _gloss texture to the object , and you will see the reflections from the surroundings (cubemap) and light extractions will also start to work.
The Cook Torrance Specular highlight is only active on the Sun , This is not a bug. This great looking Specular is also more slow to process , so adding it to all light sources would make everything a bit more slow. The objects still have specular/light from other sources then the sun but use a faster way to process it.
As an enhancement perhaps this should be added as a define you need to activate, if you want Cook Torrance from all light sources.

**Comment by Belidos3D** [comment]
Just as a note for those using PBR painting programs: The _gloss texture in gameguru is not the same as a gloss texture generated in most pbr painting programs, it's actually a roughness texture (metalic workflow normally works alongside roughness textures not gloss textures) that has been named _gloss, they're similar textures except the black and white is flipped.
