### ISSUE TITLE
Story zones are not working

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#20]
The story zone marker does not play video at all

**Comment by Shahin3d** [comment]
In story zone
* not play movie wmv format
*MP4 and OGV movie formats are displayed
But their sound is not broadcast

**Comment by LeeBamberTGC** [comment]
With DirectX 11, they dropped DirectShow legacy support completely, replacing it with something newer that excluded Windows 7 from support. This means we could not load WMV video anymore. To rescue the situation we used a new video playback manager that does support MP4 and OGV video files, but only the video. If you want audio as well, export the WAV or OGG from the video and include that file in the Audio property that is part of the StoryZone marker.  If you want sound natively in the video playback, this would now be a feature request as it requires more work in the new video manager to find, convert and sync the audio with the video.
