### ISSUE TITLE
Problem with the garbage entity. (Earthquake effect)

### ISSUE THREAD

**Issue by ViperSmoke** [TheGameCreators/GameGuruRepo#200]
I have a problem with the garbage entity, when I move the camera's player the object shake.

Video for example: https://youtu.be/-faGk9GofT4

![screenshot 24](https://user-images.githubusercontent.com/38324570/39013472-c26ccbec-4417-11e8-8289-06fa92981d7f.png)

**Comment by Teabone3** [comment]
It needs to be raised up by a fraction. A possible update to the FPE would be required where we can have it by default raised a bit so that it doesnt happen.

**Comment by ViperSmoke** [comment]
The monster update has solved the problem.
