### ISSUE TITLE
Add the "i" spray feature to the UI

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2000]
![image](https://user-images.githubusercontent.com/1503593/152980462-7492f185-7475-4fa2-b9a8-49b5dc771721.png)

**Comment by plemsoft** [comment]
@rvanner Is this for after EA , should we mark it as an enhancement ?

**Comment by rvanner** [comment]
We wanted it in for EA please.

**Comment by LeeBamberTGC** [comment]
@plemsoft The I key is already working in the software for quick access to spraying things. I believe it needs to be in the EA version, both as a keyboard shortcut entry and as a button as tick describes. I do not think it affects the video footage shot so far too much.

**Comment by plemsoft** [comment]
@rvanner This has been added , ready from the next update :)
