### ISSUE TITLE
Night time skyboxes - turn off sun rays

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2003]
Turn off sun rays when the sun is below the horizon, thus avoiding this visual issue;

![image](https://user-images.githubusercontent.com/1503593/152981448-e1dc0020-2739-4b97-91e5-5536db54ff68.png)

**Comment by UltraVox001** [comment]
Adding a starry sky in the simulated skybox generator would be nice.
The nights are strange in Max...
