### ISSUE TITLE
Made a level with orange fog but the thumbnail did not use the same fog settings

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2006]
This is what the level looks like;
![image](https://user-images.githubusercontent.com/1503593/152982232-c1f26a72-bfac-484d-b5e3-04c3e202bb44.png)

When I take a screen shot you can see the level is not the same
![image](https://user-images.githubusercontent.com/1503593/152982310-90a100f6-7294-4703-8a7d-57504c47e160.png)

**Comment by plemsoft** [comment]
@rvanner Fixed.
