### ISSUE TITLE
GameGuru no longer runs

### ISSUE THREAD

**Issue by Fcuked** [TheGameCreators/GameGuruRepo#201]
After the latest update, the program no longer runs.
In steam all files successfully validated (preparing to launch  = access is denied )
Run from GG icon  = access is denied,
windows and all drivers are up to date  it is not being blocked by anything.
It is not steam as all other games and programs are work fine.
Have uninstalled and reinstalled still the same thing.
It was running fine before this update
Have tried running both steam and GG as admin.

**Comment by LeeBamberTGC** [comment]
Can you send us a screenshot of the "access is denied" error as this is an unfamiliar GameGuru error and sounds like an operating system one?

**Comment by Fcuked** [comment]
![capture1](https://user-images.githubusercontent.com/38544502/39035540-4b9e1d6c-4472-11e8-9b56-6cf7c6bec2b7.JPG)
![capture](https://user-images.githubusercontent.com/38544502/39035545-5154204e-4472-11e8-8793-496adbdb328f.JPG)

**Comment by plemsoft** [comment]
Try to restart windows and see if that fix it , this error can happen if the process is already running, a restart of windows fix that :)
