### ISSUE TITLE
GG Max Light Bug - Spot Light Radius is not memorised

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2010]
At the request of Lee, I am making this new post to express the following problem :
Try to fix the problem with the **Spot Light Radius**. It is systematically **Reset at 45 degrees**, and this prevents the developer from using it. These degree parameters are **not memorized** and it **resets to 45**. This issue was reported weeks, or months ago. But no one ever fixed it.
![SpotLightRadius](https://user-images.githubusercontent.com/96718175/152989552-71969f23-a541-440c-b102-cd73d31d04b0.jpg)

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue, this has been fixed , sure the default palette will still have the default (45) , but if you create your own "Add Light" it will now remember your angles and radius :)

**Comment by UltraVox001** [comment]
@plemsoft 
Thank you. But when did you fix it ?
Because the internal version of yesterday did not arrange anything.
I reported it to Lee who asked me to post a new text on Github : [https://github.com/TheGameCreators/GameGuruRepo/issues/2036](https://github.com/TheGameCreators/GameGuruRepo/issues/2036)
![SpotLightRadiusAlwaysResetAt45](https://user-images.githubusercontent.com/96718175/153407253-b267b25b-1b55-48dc-be8b-de74db814a2c.jpg)

**Comment by UltraVox001** [comment]
@plemsoft 
Second attempt.
Saved with radius 10 :
![Saved with radius 10](https://user-images.githubusercontent.com/96718175/153410163-33d34ac6-02d8-4564-9461-fe30982a432e.jpg)
Loaded with radius 45 :
![Loaded with radius 45](https://user-images.githubusercontent.com/96718175/153410266-0ecbf009-be95-4be5-a677-27fc0d3db1e5.jpg)

**Comment by plemsoft** [comment]
@UltraVox001 Fixed for the next build :)

**Comment by UltraVox001** [comment]
Thank you very much. :)
I will come back to close this post (and the other too) after confirmation.
