### ISSUE TITLE
GameGuru MAX - Bug - Keyboard Shortcut Sidebar Issue

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2018]
When nothing is selected and you attempt to twirl down the Keyboard Shortcuts menu on the right sidebar, you cannot. It's not until something is selected in the viewport before you can actually succeed in twilling it down:

https://user-images.githubusercontent.com/36735507/153037087-bab9e371-3a01-407b-826c-49cec22bf983.mp4

**Comment by plemsoft** [comment]
Zak code reassign :)

**Comment by ZakJudges** [comment]
@ArgentArts thanks for reporting this issue. I've added a fix that you should see in next week's build
