### ISSUE TITLE
GG Max Bug Report - Camera + Shift Selection Issue

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2020]
This is what happens when I position myself above my military base and I turn my back on it.
Then I make a selection in the void, with Shift + LMB, and this selects what is behind me...

See my video : [https://www.youtube.com/watch?v=I88hERBAkrw](https://www.youtube.com/watch?v=I88hERBAkrw)

I hope it can help.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Fixed for this weeks next internal build.
