### ISSUE TITLE
MAX - 2021.02.11 - ALT Key Fires Weapon?

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2024]
Alt key fires a weapon

**Comment by OldFlak** [comment]
@dllllllllllb 
Found more info on this:
https://youtu.be/yHBYaBCHryo

**Comment by dllllllllllb** [comment]
@OldFlak Player arms have been fixed. I tested all weapons and all of them do either a push or a melee attack with the weapons stock when I press the alt key. Is the bug still happening on your end, if so, could you please give me more information on how to reproduce it.

**Comment by OldFlak** [comment]
@dllllllllllb - Thanks Maciek for looking into this.

Not seen this issue in 2022.02.18 builds - so probably safe to close - thanks
