### ISSUE TITLE
MAX - 2022.02.11 - Scots Pine Texture Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2026]
Just some feedback - not a showstopper.

Similar on both Scots Pine 1 and 2

![Scots Pine Texture Issue](https://user-images.githubusercontent.com/12246318/153190722-048ba85f-cad8-4065-9c04-4253af5186e1.png)

**Comment by bond1mjb** [comment]
@PaulSJ  Here are new trunk exports for scotspine1, scotspine2, and scotspine dea
[scotspine seam fix.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8035299/scotspine.seam.fix.zip)
d

**Comment by PaulSJ** [comment]
Confirmed fixed, thanks

**Comment by OldFlak** [comment]
Not fixed in Build 2022.02.18
![image](https://user-images.githubusercontent.com/12246318/153742310-bc22e3f9-7dc0-4105-87f9-484e2b8e7939.png)
