### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2029]
![image](https://user-images.githubusercontent.com/68471279/153195176-f6ec46fb-1852-4599-8072-e8447fb64f43.png)
  that. :)

**Comment by LeeBamberTGC** [comment]
@casigus I loaded your compo game project, deleted all but the first level, did not include non-stock assets, and was able to create a standalone game and run the first level (which is great by the way). The 7007 error was fixed a short while ago so this specific issue is solved in this Friday's build.  See your other issues for tackling the HUGE LEVEL/PROJECT related crash.

![image](https://user-images.githubusercontent.com/35840583/154519586-3d3ea37b-6f27-4b31-8ecf-7d36273fbca5.png)

**Comment by casigus** [comment]
fantastic. glad you got things working.
