### ISSUE TITLE
Indoor Lightmapping bugs - Indoor entities cast shadows from the sun (no windows)

### ISSUE THREAD

**Issue by TheMECHAN1C** [TheGameCreators/GameGuruRepo#203]
Indoor Lightmapping bugs. 
The archive attached contains 2 maps. Both are renders after lights baking (F3).

00_ST3N_NEW_test_blue_physicsON
I just baked static lights.

00_ST3N_NEW_test_red_physicsNO
I put all construction entities (Bunker pack by Gtox) on the following properties: 
Static - YES, Physics - NO.
(According to this guide: http://gamegurureport.blogspot.com/2016/06/technique-evaluation-gameguru-interior.html?m=1)

BUGS: In all cases there objects cast shadows from the sun (omg!) 
There are no any little window in my "bunker", but every object cast shadow from the sun. 

If I have mistaken, and this is not a bug, then how to turn off the shadows from the sun and make my indoor entities cast shadows from my light sources (markers) only? 
 
[mapbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1933275/mapbank.zip)

**Comment by LeeBamberTGC** [comment]
To turn off lightmapping from the sun directional light, you can open SETUP.INI and change the flag "lightmappingdeactivatedirectionallight=0" to "lightmappingdeactivatedirectionallight=1", then save and relaunch GameGuru.

**Comment by LeeBamberTGC** [comment]
Closing this down as there are other feature requests about shadows. Hope the advice above helps!
