### ISSUE TITLE
Running Zombies still ignore collisions and run past you 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2030]
As the heading says Running Zombies still ignore collisions and run past you 
Video below.
https://youtu.be/u4g3fepV8Kg

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed for this afternoons build (soon).

**Comment by rvanner** [comment]
@synchromesh62 Can you confirm this is now fixed for you?

**Comment by synchromesh62** [comment]
> 

Yes fixed some time back now. Apologies there were a few reports at the time i assumed they would all be closed
