### ISSUE TITLE
Gameguru Max Lighting bug

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#2031]
When you set the ambient light (sun) below the horizon, results in a vegetation error like this

![lighting bug](https://user-images.githubusercontent.com/82841733/153263551-005374fc-af4e-4966-b3ad-efea94ec0b97.jpg)

**Comment by LeeBamberTGC** [comment]
@PaulSJ Anything quick and clever we can do to prevent a directional light that is under the terrain and pointing upward, and thus lighting a side of the grass vegetation can be nullified?  Typically the terrain would stop the light, but I am not liking the idea of using the whole terrain as a blocker. Best just to agree the sun is on the other side of the planet and so there is NO DIRECTIONAL LIGHT from the sun at these times.  Thoughts welcome, then assign back to me.

**Comment by PaulSJ** [comment]
@LeeBamberTGC I've modified the directional light to always cast a shadow when it is below the horizon, changes are on PJ-Branch4 on both repositories.

**Comment by LeeBamberTGC** [comment]
Commit included in Friday AMs internal build this week.
