### ISSUE TITLE
MAX - Standalones Are Not Independent of GameGuruMAX

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2033]
Created standalone with every build this year - all worked perfectly fine - aside form know issues
Created one in Build 2022.02.04 and it worked OK

Build 2022.02.11 seems to have issues with standalones and won't run - neither will the one I built using 2022.02.04

So it seems standalones are using GameGuruMAX installation to run - and are not creating their own runtime exe

**Comment by Skevos-Mavros** [comment]
I noticed a (related?) issue - I can create and run a stand-alone game, but if I go back into GGM and change, say, the speed of my player and the way gravity affects them, those changes show up in my _previously created_ stand-alone.  This suggests that the stand-alone is not looking within its own folders for such things, but in the folder of the project?

**Comment by OldFlak** [comment]
@plemsoft Hi Preben - as far as I can tell this is now OK in 2022.03.11
Standalones have quite a few issues that were not there in previous builds - but I think this specific issue is ok to close - thanks :)

**Comment by plemsoft** [comment]
@OldFlak Yes only on copy of Max is allowed to run, standalone or editor its the way it must be :)
