### ISSUE TITLE
AI issues seen in Mountain Snow Level

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2037]
@LeeBamberTGC I had trouble making one video with Sony Vegas. So I decided to make lots of small ones!

These give you a lot to get your teeth into!

**Solider stands on a crate in front of him**
https://youtu.be/ix7SH27yj1E

**Weapons left floating in the air**
https://youtu.be/gflgFXMqsas

**Solider runs into a crate
Solider comes out of the crate but does not fight
Decal on fire is out of wack**
https://youtu.be/SwqTssnpedE

**Death pose looks silly
Soliders ignore the player
Another solider ignores player
Death pose looks silly**
https://youtu.be/_CZl7fnlX_c

**Solider goes up vertical wall and into it**
https://youtu.be/KCEfRORjvC0

**Melee needs some hurt sounds**
https://youtu.be/tZYE2mPIel4

**Soliders should turn while they draw their weapons**
https://youtu.be/uGpZk_m1i9I

**Comment by LeeBamberTGC** [comment]
COMPLETED ITEMS:
Solider stands on a crate in front of him
Weapons left floating in the air = FIXED
Solider runs into a crate
Solider comes out of the crate but does not fight
Decal on fire is out of wack
Death pose looks silly
Soliders ignore the player
Another solider ignores player
Death pose looks silly
Solider goes up vertical wall and into it
Melee needs some hurt sounds
Soliders should turn while they draw their weapons

**Comment by LeeBamberTGC** [comment]
Using cut-down level, can now test all these fixes with internal build, uploading soon.

**Comment by LeeBamberTGC** [comment]
@rvanner I am emailing the cut down start of the mountain snow level so you can test the character combat for the first 4 enemies so you can confirm the fixes.

**Comment by rvanner** [comment]
I'll close this. We have a new version of this level so I'll play though and post any issues I find.
