### ISSUE TITLE
Unwanted reflection of the terrain (while goindoors.lua)

### ISSUE THREAD

**Issue by TheMECHAN1C** [TheGameCreators/GameGuruRepo#204]
This archive contains 2 fpe files (+2 screenshots):

Both of the same map (my Polygon), walls and floor must be white, but scince the update - they are not. 
Before the update they was as white as snow (with textures), unless I changed brightness.

1) Lushy terrain: unwanted grass reflection. Completely uncorrect.
2) Asteroid terrain: also unwanted reflection, looks like the dust and dirt. Better, but still not good.

[POLIGON.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1933320/POLIGON.zip)

**Comment by LeeBamberTGC** [comment]
Those are from the cubemap and the PBR reflection property, you will need to either change the terrain style to a solid white terrain, or change the PBR texture or shader of the entity so it does not use the cubemap.
