### ISSUE TITLE
Level Testing - Crash when creating mesh vertex and indices

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2044]
When I make a new Desert level and proceed to playtest the level I get an exception thrown: write access violation.
pVertPtr was nullptr.

Happened consistently 6 times in a row.

**Comment by plemsoft** [comment]
@dllllllllllb When you get the crash , locate this line just above "SetupMeshFVFData (pMesh, GGFVF_XYZ, dwVertexCount, dwIndexCount, false);" , please check what dwVertexCount = , i guess it is > 0xFFFF if so this could happen, also please post if this happens in physics_createterraincollision or game_createnavmeshfromlevel :)

**Comment by dllllllllllb** [comment]
@plemsoft This happens in physics_createterraincollision

It says that the dwVertexCount is undefined but it is set to iVertexIndex which is = 71248

https://prnt.sc/26szaji

**Comment by plemsoft** [comment]
@dllllllllllb Yes its to large, we can only use 16 bit for vertex max 65535, so search from this place (up) and find "int iFullResolutionSize = 5000;" , try to lower this value by 100 next (4900) and keep doing this until it dont crash, please post the iFullResolutionSize that works on your level :)

**Comment by dllllllllllb** [comment]
@plemsoft My iFullResolutionSize was originally set to 8000 (I didn't tinker with it). Setting it to 5700 is the max size before my level crashes.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Yes, every morning I check the GGM updater, both GitHub repositories for changes, then clean and rebuild both solutions.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Yes

**Comment by dllllllllllb** [comment]
@LeeBamberTGC When I swap to the Master branch I have the change from your screen shot, but when I change back to my branch it reverts that change.

Master Branch:
![image](https://user-images.githubusercontent.com/61796872/153455557-a65bc192-5cae-489d-b4f0-fa66f4052a54.png)

My Branch:
![image](https://user-images.githubusercontent.com/61796872/153455727-4ed31e1d-03a7-4d16-ac1e-081fc1a5c8d2.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Looks like your branch does not have the latest from the master. Do do this, whilst in your branch, use GitHub Desktop and click the current branch dropdown and select the merge button:

![image](https://user-images.githubusercontent.com/35840583/153457125-59460bd3-9435-4f44-8868-875bef3eddfb.png)


You can then select the MASTER trunk and it will take all the latest from the master add MERGE them with your branch, and you will then see the latest lines of code, including the new size of 5000.  Remember to complete all your own commits with comments before doing a merge.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I did that and now have 62 pushes to do (didn't have any before), don't want to mess anything up so should I push these? 
![image](https://user-images.githubusercontent.com/61796872/153458208-7a95b005-f2c3-4f97-9bd8-491b8e2fb5b8.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb You are right to be cautious.  If you are pushing to your own branch it would be fine as I check merges to the master.  Let's have a call Friday AM and walk through the process. That sounds about right there are 60 commits you have not been privy to since you created your branch last week.
