### ISSUE TITLE
GG Max Bug Report - Door Rising Behavior does not render door collisions on closing

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2046]
Door Rising Behavior does not render door collisions on closing
See my video : [https://www.youtube.com/watch?v=35trHl8dYcI](https://www.youtube.com/watch?v=35trHl8dYcI)
And I can't connect a second gate with the same Behavior (to be confirmed by other Beta-Testers).

I hope it can help.

**Comment by LeeBamberTGC** [comment]
Fixed for next internal build, and the fix will also allow all isimmobile physics objects to move correctly (the orientation of objects was not preserved) in the ODESetBodyPosition function.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
I just tried with the latest build at 7:25 p.m. (French time).
The door collision is permanent. The door movement is correct, but the collision is unchanged.
Do you have to do anything special ? I tried various combinations, without success.
![door-collision](https://user-images.githubusercontent.com/96718175/155014177-bee4dc7c-fec3-4de6-b826-78e67e1633b9.jpg)

**Comment by LeeBamberTGC** [comment]
Try loading the Switch Escape level and changing the logic for the first switch to toggle and then see if you can close the door and have the door stop the player walking through.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
It works on your level, but not on mine. I have exactly the same settings as you. But it does not work. Here is my test map.
[Plaines.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8112251/Plaines.zip)
I don't understand what's wrong. All this is very simple.
