### ISSUE TITLE
custom models.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2050]
built this, exported via blender, imported into max. In the editor, it registers the surfaces fine.

![image](https://user-images.githubusercontent.com/68471279/153515882-586c508b-dd82-4fcb-9512-775c775ee365.png)

in game testing, zero collision.

![image](https://user-images.githubusercontent.com/68471279/153515705-9bdf6383-365d-453c-8a36-99a34fd47e3c.png)

**Comment by ZakJudges** [comment]
Hi @casigus, are you still experiencing this in the latest build?

**Comment by casigus** [comment]
yeah actually. doesn't happen alot, but some imported models just don't have collisions once entering test mode.

**Comment by ZakJudges** [comment]
@casigus Would you be able to send me a model that shows the issue? Preferably the dbo and fpe if possible :)

**Comment by casigus** [comment]
yeah ill have to find it but i will do
