### ISSUE TITLE
MAX - 2022.02.11 - Texture Blending Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2053]
Noticeable Terrain Texture blending issue
This area is only sculpted no alteration of Terrain Texture here just sculpting
- on bigger areas is a ton worse

Note the areas circled in tis pic
![Texture Blending Issue](https://user-images.githubusercontent.com/12246318/153535905-c4ed3bde-6007-4bcc-8684-02e24fbe80bc.png)

Video of the bad look it gives terrain
https://youtu.be/rYqvvxhNNBs

No doubt related to #1983 and clearly ruins visuals - since no-one will refrain from sculpting terrain and it **clearly ruins visuals** it is a **bug** not enhancement!  :)

**Comment by dllllllllllb** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/1983
