### ISSUE TITLE
floating trees and vegetation in  the snow

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#2059]
![image](https://user-images.githubusercontent.com/45684694/153580091-af373818-2410-41df-99c1-266454772921.png)

**Comment by plemsoft** [comment]
@PaulSJ I think i know what this is, i will take a look and let you know :)

**Comment by plemsoft** [comment]
@smmaas Thanks for reporting this issue, i think i got it fixed now, please confirm after the next build thanks :)
