### ISSUE TITLE
Zombie character texture

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#206]
Problem: Zombie character texture
I tested a zombie characters
Sometimes, after how many times the game is tested:
Texture characters, zombies, were transparent.
The plants are seen behind the body of the character.
![snapshot14](https://user-images.githubusercontent.com/36647058/39086828-7e3b8174-45ad-11e8-8779-4aaa2a6cf84e.jpg)
![snapshot15](https://user-images.githubusercontent.com/36647058/39086833-8c9c35f6-45ad-11e8-9a6f-876363f7378f.jpg)
![snapshot16](https://user-images.githubusercontent.com/36647058/39086834-908c6de8-45ad-11e8-9188-675b48c1b2c5.jpg)

**Comment by Teabone3** [comment]
Very odd indeed...

**Comment by Shahin3d** [comment]
This problem exists for characters in the third person.
![snapshot5](https://user-images.githubusercontent.com/36647058/39249841-c93ecd84-48b4-11e8-8fc1-67b5627feb1f.jpg)

**Comment by korodai** [comment]
Distant entities appear in front of the astronaut.

![astronaut](https://user-images.githubusercontent.com/38481020/41792003-77af6426-7625-11e8-812d-2f78d26dd574.jpg)

**Comment by plemsoft** [comment]
@Shahin3d Thanks for reporting this.

When do this start , in standalone after restarting the game many times ?
or just trying "test" game many times ?

**Comment by plemsoft** [comment]
@Shahin3d
Could you test this in the Beta version 2019-06-15B, and let me know if it work for you , thanks :)

The beta is available now.

**Comment by Pirate-Myke** [comment]
I am not having any transparency issues with them in Beta version 2019-06-15B.
Did repeated test games 8 times with no issues. Objects and decals used. with two different zombies and painted grass.

Here is my map layout for testing.
https://puu.sh/DHr4R/579f2a0105.jpg

**Comment by LeeBamberTGC** [comment]
Recent transparency work has fixed this issue in the latest builds.

**Comment by Shahin3d7** [comment]
Thank you
fixed this issue.
