### ISSUE TITLE
stacking objects with angle leave a space in between (without angle works)

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#2062]
![image](https://user-images.githubusercontent.com/45684694/153584112-b43374ff-6d38-4c77-a3ca-afa4cd58d5c3.png)

**Comment by LeeBamberTGC** [comment]
@smmaas Works fine with the latest EXP build on Steam shortly (and in Friday public build). Can you check again and if it still happens mention the object name so I can try with the exact object, thanks:

![image](https://user-images.githubusercontent.com/35840583/164548891-82b10d82-9397-434b-99f6-1e3df465aee9.png)

**Comment by ZakJudges** [comment]
Works fine in the latest build
