### ISSUE TITLE
GG Max Bug Report - What the .EXE does not consider

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2064]
Small test with an Max executable (internal version) to determine the possible problems.

- Unlike the TestLevel, the AI ​​does not use any PathFinding. Enemies react to my presence and want to kill me, but completely ignore PathFinding. They remain positioned in the same place with an idle animation.
![NoPathFinding](https://user-images.githubusercontent.com/96718175/153594826-bc56be61-7bf5-49b1-a25f-ccc346e1e956.jpg)

- Some lights are exaggeratedly increased compared to the same scene in the TestLevel and the Editor.
Editor : 
![Light1-Editor](https://user-images.githubusercontent.com/96718175/153595324-ac6e0f9a-bd97-4aa2-8520-9987723fa0fa.jpg)
TestLevel :
![Light1-TestLevel](https://user-images.githubusercontent.com/96718175/153594901-7f902ef0-f13c-43f6-9e60-3988e7d37a08.jpg)
Executable : 
![Light1](https://user-images.githubusercontent.com/96718175/153594950-da454575-21d5-4a7f-980a-37fdc03f9e93.jpg)

- Since Lee's last changes regarding the Cast Shadow option of lights and the increase up to 16 dynamic lights, some maps were running with 35-45 FPS, now render at 60 FPS. Tested on an old i5 with a GTX 1060 (6 Gigas), and 16 Gigas Ram. I congratulate everyone on this spectacular step forward. :)
![60FPS](https://user-images.githubusercontent.com/96718175/153618896-15ee6711-3c29-4e39-aa66-acb662185f69.jpg)

- Death poses are ridiculous. They come from the old Ragdoll system. But it conforms to the TestLevel. No significant changes in this regard. I killed 14 enemies and all of them used Radgoll on flat ground (military base).
Screens : 
![DeathAnimation1](https://user-images.githubusercontent.com/96718175/153595231-d441d381-0d2b-4aa2-b676-47f3ae6d235d.jpg)
![DeathAnimation2](https://user-images.githubusercontent.com/96718175/153595248-73a92e09-962b-47b2-9140-e39b0347767e.jpg)
![DeathAnimation3](https://user-images.githubusercontent.com/96718175/153595262-abdd53a7-28f8-48f2-870f-00070aae38f3.jpg)
I hope it can help.

**Comment by ZakJudges** [comment]
Hi @UltraVox001, the navmesh code  is currently being worked on and we expect the pathfinding and death animations to be fixed as a result :)

I wasn't able to reproduce a light having a different intensity in standalone compared to editor. Are you still experiencing it in the latest build?

**Comment by UltraVox001** [comment]
Editor
![LightEditor](https://user-images.githubusercontent.com/96718175/156184240-007b2579-e43b-4ce9-a1c6-7057c8d35987.jpg)
Standalone
![LightStandalone](https://user-images.githubusercontent.com/96718175/156184278-6a5dd070-b9c4-436d-bdc5-76b7737138f4.jpg)
There is quite a significant difference. But that only happened on that Light. I will close here.
