### ISSUE TITLE
Terrain Editor - Brush indicator disappears when you open water tab

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2066]
When you have one of the "Sculpting Terrain" tools selected and open the water tab, the brush indicator disappears but you can still edit the terrain. Brush indicator comes back when you close the water tab.

**Comment by PaulSJ** [comment]
@plemsoft set ggterrain_extra_params.edit_mode or ggterrain_extra_params.sculpt_mode to 0 to disable terrain editing when leaving the terrain tab

**Comment by plemsoft** [comment]
@dllllllllllb Fixed for next build :)
