### ISSUE TITLE
GGMax scaling X files when place them over the map [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#2076]
Not final Friday's build yet.
Notice the soldier near the scene, as a reference.

The mesh in 3ds max

![resize_small_mesh_3dsMax_pic01](https://user-images.githubusercontent.com/47690174/153641821-8938dbd3-68d2-4977-83ff-b10ce70c36fd.png)

In GGMax

![resize_small_mesh_GGMax_2022_02_11_pic01](https://user-images.githubusercontent.com/47690174/153641939-7d57f955-429b-411f-9a79-2035617b22ee.png)

![resize_small_mesh_GGMax_2022_02_11_pic02](https://user-images.githubusercontent.com/47690174/153642044-c34e7a42-7899-4cd0-97f2-62e045e911dd.png)

There is nothing on the fpe that might scale the mesh when loaded in GGMax; are you resizing meshes when converting to DBO?

Note: compare 3ds max with the GGMax ones, and find the difference :)
clue, the irons are not placed in the same place with respect to the original model in 3ds max.

**Comment by 3coms** [comment]
With respect to X files, please back to the GG system. :)

**Comment by 3coms** [comment]
You can avoid it scaling your mesh in the GGMax importer; anyway, the iron remains misplaced, and this is happening because, for any reason, lately I'm being forced to merged my multi-compound meshes into one.
Originally that mesh was 4 meshes plus the iron, GGMax make a sculpture with it when placed over a map; so, now I'm forced to work each city's building one by one, and import them from GGMax to adjust the size there. A lot of buildings are going to form that city, so, obviously one for try is fine, but not all of them, :)

![resize_small_mesh_GGMax_IMPORTER_2022_02_11_pic01](https://user-images.githubusercontent.com/47690174/153650961-5a195aef-5f70-4088-87ae-1c44e4296651.png)

**Comment by 3coms** [comment]
Just to verify the model is not the issue, I bring up just another one. :)

in 3ds max

![resize_small_mesh_3dsMax_pic02](https://user-images.githubusercontent.com/47690174/153680547-5bd07694-e12b-44c1-afc8-d1b7fbb22fdc.png)

in GGMax

![resize_small_mesh_GGMax_2022_02_11_pic03](https://user-images.githubusercontent.com/47690174/153680598-82e5eda0-27f9-4cee-a30c-394e72af20d9.png)

in GGMax importer

![resize_small_mesh_GGMax_IMPORTER_2022_02_11_pic02](https://user-images.githubusercontent.com/47690174/153680664-4c441532-d7d2-4ea7-9c1a-4b6de9668c0e.png)

Obviously here you can adjust the size, but the question is why it comes that extremely small. :)

**Comment by marcuswilm** [comment]
Hello to the participants in this thread initiated by 3coms (3com in GG forum).

Upon request of that valued member (and skilled artist), may I suggest you to examine the content of this thread that I posted today in GG Forum (Product Chat (Early Access) : [https://forum.game-guru.com/thread/223626](url) .

Thank you.

:)
