### ISSUE TITLE
Tree painting not working after clearing trees

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#2079]
Since the new update, I decided to clear all the trees and paint them myself. After clearing them I can no longer paint them down unless I place trees first, clear them, and then when I paint it puts them back where I had placed them. I have attached a video to demonstrate. [https://youtu.be/9NjHg7gYQrM](https://youtu.be/9NjHg7gYQrM)

**Comment by LeeBamberTGC** [comment]
@42Pix3ls Is this still an issue, marked as fixed needs confirmation due to time.

**Comment by 42Pix3ls** [comment]
Unfortunately I still have the issue with the latest build. I will look at it again on the weekend build

**Comment by ZakJudges** [comment]
Hi @42Pix3ls, is this issue now fixed for you?

**Comment by 42Pix3ls** [comment]
Perfect, Thank you.
