### ISSUE TITLE
New grass types not painting underwater

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#2080]
The new kelp type will only paint on land. the see weed works underwater but not the kelp. I have attached a video to demonstrate. [https://youtu.be/pzdlDLCjleU](https://youtu.be/pzdlDLCjleU)

**Comment by UltraVox001** [comment]
Already reported here : [https://github.com/TheGameCreators/GameGuruRepo/issues/2069](https://github.com/TheGameCreators/GameGuruRepo/issues/2069)

**Comment by PaulSJ** [comment]
Duplicate of #2303
