### ISSUE TITLE
Tree painting crashes level

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#2082]
Steps to reproduce crash bug

1. Create a level
2. Clear level of all trees
3. Select a few trees to paint. (3-5)
4. Manually add trees by painting one by one, at various places in the level
5. At some point during the process, 50+ trees it will crash to desktop without a error message.

**Comment by rvanner** [comment]
@wizardofid29 Just tried this and it worked fine for me. What biome did you use and what size level was it? Can you try again in the latest version and report back please?

**Comment by rvanner** [comment]
It looks like a memory leak as soon as you Clear all trees!

**Comment by rvanner** [comment]
@PaulSJ As soon as I use Clear All Trees the memory debug starts increasing. Can you have a quick look please?

**Comment by plemsoft** [comment]
@PaulSJ Took a quick look and found the problem, FYI: "TreeChunk* pChunk = &pTreeChunks[ i ]; pChunk->Update();" is called constantly in update, if no visible and "if (numValid == 0)" data was not freed. will commit it shortly. @wizardofid29 Thanks for reporting this issue, this has been fixed and will be in the next update :)
