### ISSUE TITLE
Bad imported Cacti

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2084]
These two are not imported properly;
![image](https://user-images.githubusercontent.com/1503593/153703003-a4a22dc8-05d9-4bf0-b465-8729c7ef8cc5.png)

**Comment by dllllllllllb** [comment]
@rvanner This is what I mentioned in the [issue](https://github.com/TheGameCreators/GameGuruRepo/issues/1991#issuecomment-1036325590)

When I use the specific color.dds and normal.dds for this cacti
![image](https://user-images.githubusercontent.com/61796872/153845980-7e4e873b-0847-47a7-a564-35d12eb039f4.png)
This is the result I get:
![image](https://user-images.githubusercontent.com/61796872/153846027-e8d1a3b9-93e7-4239-ac68-04ac1f2c9cc7.png)

When I use the color.dds and normal.dds from the main folder
![image](https://user-images.githubusercontent.com/61796872/153846205-314d0780-5f28-44f7-9a05-a2cbdec3f6d4.png)
This is the result I get:
![image](https://user-images.githubusercontent.com/61796872/153846243-6b5572e3-3780-46cc-b5fb-190b4f17acfb.png)

The second looks better but not quite right in my opinion, this is how the nopal cactus should look:
![image](https://user-images.githubusercontent.com/61796872/153846993-afc8e72b-8951-4818-b1c1-fc5519de161d.png)

I wasn't sure which ones to use, so I used the color.dds and normal.dds files that were specific for these cacti.

I can import these cacti using the color.dds and normal.dds from the main folder if you're happy with how they look

**Comment by rvanner** [comment]
@dllllllllllb You are best checking with @bond1mjb who made the models.

**Comment by bond1mjb** [comment]
@dllllllllllb @rvanner  Thanks for the reference image, I tried to get away with using the same texture for all the cacti but I guess this one needs it's own unique texture set for real world accuracy.  Files attached.


![nopal2](https://user-images.githubusercontent.com/87768878/153987809-ae0dd6df-233f-4338-ade2-ca71dbdc719f.jpg)

[cactus_var10 nopal.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8065551/cactus_var10.nopal.zip)
