### ISSUE TITLE
Missing textures (black) in PBR latest update

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#209]
![image](https://user-images.githubusercontent.com/12373041/39096987-90079380-4656-11e8-992e-3b53ff8aa162.png)

Here we go again.
I tought this had been fixed, but I still have to set pbroverride to 0 if I want to avoid this.

**Comment by thecyrus** [comment]
If I do Lightmapping, crazy shadows and strange light shapes appear on the building.

**Comment by LeeBamberTGC** [comment]
There has been a bug fixed for the next update which resolves the black polygon issue for non-lightmapped models, which may also fix the above issue but please do add further comments here if the next update does not resolve it for you.  Expect an update in the Public Preview very soon,  You can switch to it now, and it will autoupdate when its available.

**Comment by LeeBamberTGC** [comment]
Let me know if the latest update fixes the black polygon issue and I will close this report, thanks!

**Comment by korodai** [comment]
I still see triangles after this update.

![gameguru](https://user-images.githubusercontent.com/38481020/39163442-7dd29f32-4748-11e8-9e2a-4b1a81d1fc30.jpg)

**Comment by LeeBamberTGC** [comment]
Is this a stock asset?  If not, can you zip it up and send it to me at lee@thegamecreators.com, thanks!

**Comment by Teabone3** [comment]
Is this issue related to #179 ?

**Comment by thecyrus** [comment]
@LeeBamberTGC In this case, it's one of ValuableAssets building, I bought all of them.

@Teabone3 Maybe it is.

**Comment by LeeBamberTGC** [comment]
I dropped in an asset from Guru Roads : City Builder one of the reported assets with this issue and it rendered fine with the latest build, so unless this happens with another asset I will close this bug report: 

![image](https://user-images.githubusercontent.com/35840583/40316740-2c0d1940-5d17-11e8-99cf-a7abd6bf8ab3.png)
