### ISSUE TITLE
GameGuru MAX - Possible Issue with Player Weapons

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2097]
I have a simple test level (warehouse with odds and ends in it, some lights, and a few zombies). I get 100 FPS consistently with this level no matter where I am or what direction I am looking in. So, I started to experiment with different player weapons and that's when I saw drastic frame rate differences depending on which weapon I was using. 

- No Weapon - Consistent 100 fps
- Assault Rifle - 50+ fps (it jumped all over the place, but was frequently down in the 50s)
- Patrol Rifle - 50+ fps (like the Assault Rifle)
- Pocket Knife - 85+ fps
- Melee Combat - Consistent 100 fps
- Snubnose Revolver - fairly consistent 100 fps (a few dips, but rare)
- Compact Assault Rifle - 50 fps (this one had the worst performance of any of the weapons, consistently on the low side)
- Magnum Pistol - 85+ fps
- Tactical Pump Shotgun - 50+ fps
- Sledgehammer - 60+ fps

With all of these (except the Melee Combat and the Snubnose, most of the time) there was a lot of jumping around with the frame rate. Sometimes it would clime up from 52 or 53 fps to 70+ and, at other times, it would land in the 60s. It was all over the place. The frame rate changed depending on where I was looking (how much was in the scene). 

To me, this looks like something is wrong with the weapons (or at least most of them) if they are hitting the frame rate that hard, sometimes cutting my frame rates in half. I can load my scene full of zombies and soldiers, for example, and have no weapons, and still get 100 fps on my system. They will gleefully chase me around and there are virtually no frame drops. Even with the 12 shadow casting lights in the scene. But add in these weapons and that changes things. Even with NO zombies and NO soldiers (so no AI is occurring?) the same frame rate drops occur. So, if the zombies and soldiers aren't causing such a loss of FPS, why are the weapons?

**Comment by UltraVox001** [comment]
I see the same thing as you with the presence of weapons.

Off Topic : did you like the new weapon shooting sounds ?
Rick asked me to make some, because the basic sounds were old :
- Assault Rifle
- Patrol Rifle
- Pocket Knife
- Compact Assault Rifle
- M67 Grenade

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Try it with this morning build as Preben has improved object management on the Wicked side. This might solve the performance spikes caused by weapon rendering.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Tested it in empty level, different biomes and with various objects in the level etc. and I didn't get consistent FPS drops. Every time I changed weapon, I dropped 2-3 frames but they went back up almost instantly.

I have quite a beefy PC, so it might be a good idea if someone else also tested this.

**Comment by ArgentArts** [comment]
I tested this with a MAX generated outdoor level and the weapons barely affected the frame rate. However, even without weapons, my frame rates were in the low 50s, unlike my indoor level were I was getting a consistent 100 fps. But I also tested this with an empty level. My frame rate there was a consistent 100 fps with and without weapons. So, this massive drop in frame rate was only happening in my indoor level with all the models and lights/shadows. Even so, without the weapons, my frame rate, in my test level, was a consistent 100 fps. So, why are the weapons affecting frame rate there so badly?

**Comment by ArgentArts** [comment]
Do you want me to zip up the test level for you? It only uses MAX content in it?

**Comment by dllllllllllb** [comment]
@ArgentArts Yes please, send it to my email: maciej@thegamecreators.com 

Thanks!

**Comment by dllllllllllb** [comment]
@LeeBamberTGC @ArgentArts I tested this on 2560p x 1440p with 144 FPS while recording. Simply holding the weapon and running around doesn't impact the FPS. (it shows that the fps dropped but the FPS reported are average, you can't see it in the video because it's only 60fps, but there was no stutter). However the animation have a huge impact on performance, especially when zooming in with a weapon. ([see 0:38](https://youtu.be/LNI5ReN4dvI?t=38))

Video: https://www.youtube.com/watch?v=LNI5ReN4dvI

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Good video, and easy to see the drop from 140 to 70 with some weapon actions, so definately something we can reproduce!

@PaulSJ Once you are finished with terrain and nav mesh, here is a nice one to performance analyse, and find out why we see this drop. If I had to guess, it might be 'creating objects' or 'changing resources' a LOT and this is causing the FPS drops.

**Comment by ArgentArts** [comment]
Firstly, in my level (which that was from), all of that was in a warehouse. So, where's the warehouse? Secondly, when I tested it, even just holding the weapon caused the fps to drop in many areas. I will create videos to show the drops. My screen res, though, is 3440 x 1440.

**Comment by PaulSJ** [comment]
@LeeBamberTGC My first thought is that weapons are drawn as transparent objects which don't benefit from the Z-prepass step, so it could be that when weapons cover a large portion of the screen they are doing a lot of unnecessary pixel shader calculations. If this is the case then I would expect the "Transparent Scene" part of the profiler to show a large increase with weapons on screen.

If weapons could be drawn as opaque as much as possible then this should improve performance, and also fix a hack we added for light shafts appearing through the weapons.

If it's still causing problems when I finish terrain and navmesh then I'll take a closer look.

**Comment by ArgentArts** [comment]
I tried to do a video, but when I ran the screen capture software, my FPS dropped to 50fps and it was steady for all weapons. So, instead, I did screen shots.

No weapon, only melee - 100 fps. (locked to 100 do to vsynch, I'm sure):
![weapon_none](https://user-images.githubusercontent.com/36735507/154089191-e87dc38a-9607-47b4-9286-a87b5226d72e.png)

Next weapon - 59fps:
![weapon1](https://user-images.githubusercontent.com/36735507/154089379-6059af13-c79d-44ae-b543-ffbfd096bbc5.png)

Notice, I am not using the weapon. Just standing there. Even so, the frame rate has dropped from 100 to just under 60.

Next weapon - 67fps:
![weapon2](https://user-images.githubusercontent.com/36735507/154089616-0bef67ae-82c8-4ec9-9617-9faa76329a5a.png)

The snubnose surprisingly gets me 99fps:
![weapon3](https://user-images.githubusercontent.com/36735507/154089737-88bd96e4-400c-4301-aced-87e3a93813d6.png)

58fps for the assault rifle:
![weapon4](https://user-images.githubusercontent.com/36735507/154089855-9ca42e85-5b63-49c0-a2f1-596fd9d21761.png)

55fps:
![weapon5](https://user-images.githubusercontent.com/36735507/154089968-09b51d5e-e294-4f88-a12a-326ac51cd2ee.png)

57fps:
![weapon6](https://user-images.githubusercontent.com/36735507/154090034-bb166ffb-02c5-4248-a44c-c443afc1ee25.png)

**Comment by ArgentArts** [comment]
BTW - my test level above has 12 lights in it, all casting shadows. With no weapons or only melee, I still get 100fps (as per the screen shots).

**Comment by plemsoft** [comment]
@ArgentArts The optimizing was done during last weekend and is not in your current build, you should see better results in next Fridays build :)

@PaulSJ The current optimizing is not in your branch, you should merge master in both's REPO before checking. i tried a profile and the most time used was in RunAnimationUpdateSystem this line "while (animationdata->keyframe_times[keyRight++] < fAnimTimeEnd) {}" , and not related to this but: ggterrain "pagesNeeded.Sort();".

**Comment by ArgentArts** [comment]
@plemsoft - Awesome. I will test it with the next build and report.

**Comment by ArgentArts** [comment]
Just tested with the latest build and things actually look worse. I am getting a consistent 50fps with ALL weapons now. At least some weapons were 60+ fps and one was in the 90s. With no weapons, I still get a consistent 100fps with my test level and 12 shadow casting point lights. Here are two example screen shots:

No Weapon:
![no_weapon](https://user-images.githubusercontent.com/36735507/154775144-51ae528f-653e-4c2e-a79f-221fb138dba8.png)

With a Weapon:
![with_weapon](https://user-images.githubusercontent.com/36735507/154775166-74a88db0-02cb-473f-9265-94ddfd13e1f0.png)

**Comment by Kitakazi** [comment]
Same issue here. Frames drop by about 10 when equipping weapons and frames tank when firing weapons.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb The LUA Logic has been solved in the latest build (at least for some logic). I will quickly check the weapon drain on the GPU has gone down then mark this as fixed for EA, and later we can see why that 1ms happens at all.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Is this still an issue?
