### ISSUE TITLE
Max build 2022.02.11 ( fog opacity reset problem )

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#2098]
Fog opacity resets itself every time you leave the test game then restart it.

**Comment by UltraVox001** [comment]
Are you sure you saved your map before leaving Max? I just did the test with the 3 available parameters. And all are fine after saving, quitting and restarting Max.
![fog](https://user-images.githubusercontent.com/96718175/153837871-d5ecf6b5-1429-4441-aa7b-9bab05c52263.png)

**Comment by bluemeenie195** [comment]
Yes, I saved it, but once you go back in it resets. Almost like it shuts off completely and as soon as you touch the opacity slider it goes back to where you want it.
No problems with past updates.

**Comment by plemsoft** [comment]
@bluemeenie195 Thanks for reporting this issue, this has been fixed and will be in the next update :)
