### ISSUE TITLE
GG Max - Improving FPS with SkyBoxes

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2099]
Test carried out in a large military base with lots of 3D objects, with and without SkyBoxe.
Watch the video : [https://www.youtube.com/watch?v=HIAf2lOuI_s](https://www.youtube.com/watch?v=HIAf2lOuI_s)
The loss of FPS (with SkyBoxe) is considerable. The FPS loss is 50% when I use any SkyBoxe. FPS goes back to 60 when I turn off. Of course, the sun from the skyboxes generates shadows. This is what should be improved.

Banal test machine :
Intel(R) Core(TM) i5 4460 - CPU 3.20 GHz (4 cores)
NVIDIA GeForce GTX 1060 (6 GB)
16 GB Ram - SSD Hard Drive - Windows 10 Pro 64 bit

I hope it can help.

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue, wonder if this is a swapping problem , could you try this test. when you have the low fps and a skybox , open shadows and try to set resolution from 2048 to 512, did it improve fps, also try 1024 and let me know if that also increase fps, thanks for your help :)

**Comment by UltraVox001** [comment]
@plemsoft 
Yes, this seems to me to be clearly related to shadows.
Test video : [https://www.youtube.com/watch?v=zMeD2alcRVQ](https://www.youtube.com/watch?v=zMeD2alcRVQ)

**Comment by plemsoft** [comment]
@UltraVox001 Not really a problem with shadows but more a case of how we use the GPU mem,  @rvanner Another issues where lower GPU mem will stop swapping , not sure where we are at lowering GPU mem ( like the 1024 shadow i suggested ? ), Let me know :)

**Comment by plemsoft** [comment]
@UltraVox001 Also could you let me know how many spot and point lights you have on the level , Thanks :)

**Comment by UltraVox001** [comment]
@plemsoft 
Is there a way to find out in Max, or do I have to count all the lights, one by one? If you give me an email address, I can send you the map. This is a test map, but it has several 3D model packs from TGC. No exterior model.

**Comment by plemsoft** [comment]
@UltraVox001 Just use the "Detailed Object List" , should display all your lights , but i mainly is just looking for if you use 16+ spot or 16+ point , if you cant see it e-mail me the fpm and i will check plemsoft@plemsoft.com :)

**Comment by UltraVox001** [comment]
@plemsoft 
It's exciting ! I can't wait to see the result. It becomes very interesting with Max. :)
Thank you very much. I would come back here to confirm.

**Comment by UltraVox001** [comment]
@plemsoft 
Wow ! You solved a very important problem, while giving the user some crucial choices!
The consequence is immediately visible. And the FPS gain is obvious. :)
Watch the video : [https://www.youtube.com/watch?v=PaUwZXSOBnQ](https://www.youtube.com/watch?v=PaUwZXSOBnQ)
I congratulate you and the whole team for this spectacular progress !

Regarding the Cast Shadow option, I would like to ask you a technical question :
Look at these two screenshots.
With Cast Shadow :
![WithCS](https://user-images.githubusercontent.com/96718175/154043837-722d1598-c645-4b60-adb7-8463a86bcffd.jpg)
Without Cast Shadow : 
![WithoutCS](https://user-images.githubusercontent.com/96718175/154043902-d8143fe1-caca-4a18-a0c6-30ee3caab9ec.jpg)
When the Cast Shadow is disabled, obviously the shadow disappears. It's normal. :) But is it normal for the light to flash behind the wall, and through it ? Do you think it is possible to avoid lighting through a static object with collisions, without casting a shadow ?

Thank you again for your quality work.
