### ISSUE TITLE
Runtime Error 0: Cannot initialize DirectX11 () Windows 7

### ISSUE THREAD

**Issue by Arjayx2** [TheGameCreators/GameGuruRepo#210]

**Comment by LeeBamberTGC** [comment]
Can you confirm your GPU make and model, and the amount of dedicated video memory you have? Thanks.

**Comment by Arjayx2** [comment]
I Have Geforce Nvidia 9400M and I Have Dedicated Video Memory of 256 MB and
I have A Ram Of 4gb

**Comment by jbthenext** [comment]
The Nvidia Geforce 9400M is a DirectX10 Shader Model 4 card.

GameGuru requires at least DirectX11 Shader Model 5 which your card doesn't support this isn't a GameGuru issue your card is simply too old.
