### ISSUE TITLE
MAX - 2022.02.18 - Items moving when clicked

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2100]
Just use Lees demo, set to grid mode, and click the various Steam particles or any other object to reproduce

**Comment by OldFlak** [comment]
As said yes it is set to grid - but items should not move just because they are clicked - so no, it is not normal behavior.

**Comment by ArgentArts** [comment]
What I meant was, if the entity is "between" grid points, when clicked, it will snap to the nearest grid point to ensure that entity is now snapped to the grid system since snap to grid is turned on.

**Comment by OldFlak** [comment]
Yes, but it should only move to grid if you actually try move it (click drag) not simply when clicked to edit properties.

**Comment by OldFlak** [comment]
More info using 2022.03.11

Despite the concept of the Smart Placement system, widgets are the most robust and common way to interact with objects and ought to work flawlessly.

A few things to note in this vid 
1) the **number of times you have to click an object** to get access to the widget when locked
2) the widget should **always be active** once the object is unlocked
3) the **item moving up or down** when clicking the widget handle
- in the vid the objects are behaving quite well
- sometimes they end up so high in the sky or under ground you need to use Detailed Object List to find them again if the widget loses focus
- and this is just a simple scene - more complex interior scenes are simply just annoying to work on at best

https://youtu.be/Z5O2yzCy6Y0

**Comment by OldFlak** [comment]
The current bug fix log says the issue of models moving when clicked is sorted - but it still does it.
Try setting height of an object to 100.5, when you click it it will jump to 100

**Comment by ArgentArts** [comment]
@OldFlak I just tested it with the latest build and it does not for me. I set the height of an object to 100.5 and clicked it and it stayed in place. I tried clicking it both with and without the widget active just to see. In both cases, the object stayed at 100.5.

**Comment by OldFlak** [comment]
Yes, I get mixed results - that was an example :)

It will be fine if the object in question is already in grid position and that is where you want it to be. But if it is a tad off of exact grid position it will move when clicked when grid is on.

https://youtu.be/Ytqj3zThCvU

Also in the vid note the odd setting for Y position of model once it has moved to grid position.
I wonder if it is partly to do with the way many numeric controls in MAX often change the number to a 1 digit less than what is input.

The point is a model should not move at all when clicked in any situation.
For example, you may have an object snapped to a wall or moved incrementally into position so it is against the wall, and it will move to grid when clicked.

**Comment by LeeBamberTGC** [comment]
@OldFlak In the next EXP build, I have removed the code that attempted to align the Y causing the issue you saw, and have moved it earlier in the process of detecting the floor so we still get good predictable Y when dragging into an EMPTY level without messing with ongoing object placement work.

![image](https://user-images.githubusercontent.com/35840583/165085270-caa5e96d-614b-4de2-ace4-f61e37e35621.png)

**Comment by OldFlak** [comment]
As reported in other threads - tis completely busted atm. Keep at it Lee :)

**Comment by LeeBamberTGC** [comment]
@OldFlak In next EXP build, object will only move when mouse clicks and then moves with it

**Comment by OldFlak** [comment]
All sorted Lee :) Thanks

MAX is shaping up to be awesome indeed!
