### ISSUE TITLE
demo dilemas 2

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2107]
![image](https://user-images.githubusercontent.com/68471279/153861342-85736862-a8af-4109-a7b4-7c7011723eb7.png)

last night max was accessing assets with no problem. today it wontt open with out crashing and when it does open this happens:

![image](https://user-images.githubusercontent.com/68471279/153861464-00682c47-d243-4cfe-a995-22bb9dd3407f.png)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/153861532-18f51c61-cfb5-412c-8923-b915905cbb90.png)

**Comment by plemsoft** [comment]
@casigus In settings try "Reset Interface" , and then try to open the object library again, did it work ? if so , i suggest you in settings -> Developer check "Disable Object Library Viewport" this will prevent it from happen again , Let me know if this solves your issue, thanks.

**Comment by LeeBamberTGC** [comment]
@casigus If you can confirm, I can close this as solved.

**Comment by casigus** [comment]
not changed anything but it is more stable today!

**Comment by ZakJudges** [comment]
Hi @casigus, is this now sorted for you? Thanks :)

**Comment by casigus** [comment]
yeah way  more better now!!
