### ISSUE TITLE
Under water plants don't paint under water

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2110]
I wasn't able to paint these purple kelp under the water, they only painted above water;

![image](https://user-images.githubusercontent.com/1503593/153898322-629bbbc3-229b-4e2d-a201-87cb75bed64d.png)

**Comment by UltraVox001** [comment]
[2069](https://github.com/TheGameCreators/GameGuruRepo/issues/2069) :)

**Comment by PaulSJ** [comment]
Fixed on PJ-Branch2
