### ISSUE TITLE
New blood splats are a bit too over the top

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2111]
These new HUD blood damage graphics are too extreme:

![image](https://user-images.githubusercontent.com/1503593/153903745-1747fd1b-1307-4bca-ba88-0cde61ba1e26.png)
![image](https://user-images.githubusercontent.com/1503593/153903767-46989a28-895a-4080-a866-f3edb21ce7e5.png)

Would be better if they were semi-transparent.

See some game examples (probably not this extreme):
![image](https://user-images.githubusercontent.com/1503593/153904118-66f5cb19-c556-40fc-b284-25812e8fc1e6.png)

**Comment by bond1mjb** [comment]
Oops!  I thought these were meant for decals applied to scenery when shooting at enemies.   I didn't realize they were player HUD overlays!  I will create appropriate new ones.

**Comment by LeeBamberTGC** [comment]
@bond1mjb I think just semi-transparent for now, and we can tweak them as we get feedback on the new look :)

**Comment by fearlesswee** [comment]
I think making the screen blood 3D droplets that have a glass-type shader so they react to the environment would be a lot more "2022" feeling rather than decals/sprites, just my 2 cents :)

**Comment by rvanner** [comment]
@LeeBamberTGC This is much better for EA. When we add the HUD editor we can allow users to set their own styles.
