### ISSUE TITLE
MAX - 2022.02.18 - Trees Appear Disappear in View of Player

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2114]
Trees appearing and disappearing in view of player - ruins visual appearance of game (albeit very cool)
This is a standalone footage - but same happens in Test-Game

https://youtu.be/GY_T16TCxjU

**Comment by OldFlak** [comment]
They still do it tho Lee - not as bad as before but still noticeable :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Maybe related to your use of heightmap terrain when adding your trees, and might explain why I cannot reproduce here with my default forest biome run-through.

**Comment by OldFlak** [comment]
Just tried this again Lee, and it tis acceptable now - so all good thatks :)
