### ISSUE TITLE
Add new advanced settings to the veg section

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2115]
Add these new advanced sliders so users can set the grass and underwater grass start and end heights

![image](https://user-images.githubusercontent.com/1503593/154069890-daa3130e-9b50-40d1-8ebe-0dcd164dae04.png)

**Comment by rvanner** [comment]
@plemsoft How soon can you do this?

**Comment by plemsoft** [comment]
@rvanner Added for the next build :)
