### ISSUE TITLE
Object Placement is set wrong when you drag an object from the level objects into the scene

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2118]
When dragging an object from the level objects panel, the placement should just find the floor. Currently it's finding the floor and the orientation. Watch this video;
https://youtu.be/v02kEb0EPDQ

**Comment by LeeBamberTGC** [comment]
@rvanner Looks like you had orientation mode on, but then switched off the stack find mode. Addd code so when stack find mode is off, orientation mode is also disabled to avoid confusion.  Will be in next build.
