### ISSUE TITLE
UV Seams Visible on PBR models.

### ISSUE THREAD

**Issue by StabInTheDarkSoftware** [TheGameCreators/GameGuruRepo#212]
UV seams are now visible. I believe it is caused by an incorrect calculation in the shader using the normal map. These seems were not visible in the original Repo version. I am labeling it a BUG.
I have added 2 screen shots. The one without the UV seam visible is from the original repo version.
![snapshot26](https://user-images.githubusercontent.com/10798882/39274622-943373e6-48b0-11e8-9413-4319f2836528.jpg)

![normal map seam](https://user-images.githubusercontent.com/10798882/39274548-58fe9fbc-48b0-11e8-99fd-fba82518ca85.jpg)

**Comment by Pirate-Myke** [comment]
Play with these in the fpe file and see if they help.

preservetangents = 1
INVERTNORMAL = 1

These are new fpe commands from last update.

**Comment by LeeBamberTGC** [comment]
Yes, the PRESERVETANGENTS field switches off a calculation in the shader to generate fresh tangents and binormal vectors. In the older build, this calculation was not performed so you would be using the tangents and binormals generated by the GameGuru engine and sent as part of the vertex data to the shader.  I do plan further work in this areas as it seems newer PBR assets coming from FBX land can have specific normal + tangent pairings in the exported model data to align the normal texture into tangent space, and without this critical transformation done correctly in respect to the model, you will see these seam effects. Alas there does not appear to be one single solution, and is as much related to the model data as it is to the technique used to provide the vectors for the tangent space transformation.

**Comment by StabInTheDarkSoftware** [comment]
preservetangents = 1 has fixed the seams. Maybe you could do a check if the model is PBR and has the
correct tangents and use them, instead in calculating new ones.
![snapshot13](https://user-images.githubusercontent.com/10798882/39308739-3671763e-4934-11e8-8829-c7e63a6cf9cb.jpg)
