### ISSUE TITLE
trigger zone placing error

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2121]
when you place a trigger zone and try to resize the zone, ggmax freezes up and everything you try and place in map after that will spawn on the point of the trigger zone you where trying to edit:

![image](https://user-images.githubusercontent.com/68471279/154098789-d84fecb4-0a54-4a31-bbba-e1eb9445f101.png)

![image](https://user-images.githubusercontent.com/68471279/154098835-5219f4a7-2a84-4e4c-814e-ec8a1e13f8d1.png)

**Comment by casigus** [comment]
ill look into it asap.

**Comment by LeeBamberTGC** [comment]
@casigus Any progress or should I close this one?

**Comment by casigus** [comment]
its a less of issue now, noticed it less after last weeks update.
