### ISSUE TITLE
GameGuru MAX - Character Creator Issue - Selecting Head Gear than Selecting None Removes Hair

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2123]
If you've taken time to select hair for your character in the Character Creator, including Facial Hair and then go to Head Gear, put on one of the pieces of head gear that completely cover the head and face (like Military Helmet Black), then select NONE because you don't want it, you lose all your previously selected hair. I realize that selecting this type of head gear has to remove the hair so it doesn't penetrate the head gear model, but shouldn't it restore the hair if another head gear type is selected or if none is selected?

In fact, if you've selected a particular type of hair, like the pink hair, and then select a helmet that covers the head and then change to another head gear that shows some hair, another hair type will be used instead (perhaps the character's default hair?). Shouldn't the end-user's selected hair be remembered?

**Comment by ArgentArts** [comment]
Head gear that covers the face also removes glasses if glasses had previously been selected as well. Again, I realize why this happens (this type of head grear removes them), but shouldn't the Character Creator remember what the end-user previously had and restore that if the player has changed their mind when selecting NONE for head gear? I would hate to have to go back and reselect my head hair, facial hair, and glasses over again because I had experimented with some head gear.

**Comment by ZakJudges** [comment]
@ArgentArts Thank you for reporting this issue. A fix has been added, and you should see it in the next build :)

**Comment by ArgentArts** [comment]
This appears to be fixed! Thanks!
