### ISSUE TITLE
GameGuru MAX - Tactical Pump Shotgun Issue - Not Smoothed

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2126]
There's an issue with the Tactical Pump Shotgun. The arms and model are not smoothed (smoothing was not set when the model was exported from the modeler):

![shotgun](https://user-images.githubusercontent.com/36735507/154141956-de17928f-7ffe-4eda-bda0-dd70d68f6b3b.png)

As a result, you can see the hard, polygonal edges on the arms and gun surfaces.

**Comment by UltraVox001** [comment]
Fixed in next build. :)

**Comment by LeeBamberTGC** [comment]
Sorted for this afternoons build.

**Comment by ArgentArts** [comment]
Looks fixed to me in the last build.
