### ISSUE TITLE
GGM Crashes when Object Library file selector is moved to the edge of the interface.

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2129]
On my system (running full screen on a 4K screen) GGM crashes when the Object Library file selector is moved to the edge of the interface.  This screen shot was taken at the moment GGM froze.

![2022-02-14 (17)](https://user-images.githubusercontent.com/56815299/154156036-52d4e196-307a-4993-ac09-c7d90773098f.jpg)

Thanks.

**Comment by GraPhiX-Guru** [comment]
Go to settings and in developer options make sure 'Disable Object Library Viewport' is checked
![vp](https://user-images.githubusercontent.com/35724756/154156949-2d42e686-3e76-4547-b5f0-35efaed9d700.png)

**Comment by Skevos-Mavros** [comment]
That workaround works!  Thanks!

Though the bug should still be fixed, especially since I'm on a single monitor and that setting is for Multi-Monitor Support. It never would have occurred to me to tick that box - thanks again!

> Go to settings and in developer options make sure 'Disable Object Library Viewport' is checked ![vp](https://user-images.githubusercontent.com/35724756/154156949-2d42e686-3e76-4547-b5f0-35efaed9d700.png)

**Comment by Skevos-Mavros** [comment]
That workaround works!  Thanks!

Though the bug should still be fixed, especially since I'm on a single monitor and that setting is for Multi-Monitor Support. It never would have occurred to me to tick that box - thanks again!

> Go to settings and in developer options make sure 'Disable Object Library Viewport' is checked ![vp](https://user-images.githubusercontent.com/35724756/154156949-2d42e686-3e76-4547-b5f0-35efaed9d700.png)

**Comment by plemsoft** [comment]
@Skevos-Mavros Thanks for reporting this issue , seams like you have a problem with multi-viewports on your system, anyway this has been fixed and will be on by default, so you dont have to use that checkbox. the fix also works for other types of windows like tooltip that you reported in another issue :)

**Comment by Skevos-Mavros** [comment]
I can confirm that this problem has been **_FIXED_**.

I have another (much more minor) issue with the Add Object browser, but I'll stick that in a separate issue.

Thanks!
