### ISSUE TITLE
New construction Site Pack Backwards UV mapping

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#213]
On the new box Items, the writing is backwards. Boxes 1 thru 4

https://puu.sh/A9WF5/f0d8480929.jpg

**Comment by LeeBamberTGC** [comment]
Fixed for the next build, well spotted. If you see any more reversed textures, please post here :)

**Comment by LeeBamberTGC** [comment]
Also spotted the cylinder had some writing on it, so flipped those too.
