### ISSUE TITLE
GGM Player slows down in certain directions.

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2133]
For several versions I've encountered an issue where the player (testing or standalone) seems to be walking and jumping through molasses.  This slow down happens:

- on old maps and new,
- in some directions but not others,
- affects walking, running, jumping, and falling,
- and temporarily goes away if I look at the ground while moving.

See video for an example.

https://youtu.be/kUjw2nVMlsw

Thanks

**Comment by UltraVox001** [comment]
@Skevos-Mavros 
Please provide your PC specs.
TGC is trying to resolve this issue.
Thank you.

**Comment by LeeBamberTGC** [comment]
@Skevos-Mavros Updated the player capsule physics system so moving up and down slopes performs equally well, including jumping and footfall sounds.  There is a connected issue still to be worked on which looks at player interaction with static object physics, which is current reported here: https://github.com/TheGameCreators/GameGuruRepo/issues/1269

This one I think is ready for testing with the latest internal build.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
It's the same problem as mine : [https://github.com/TheGameCreators/GameGuruRepo/issues/2240](https://github.com/TheGameCreators/GameGuruRepo/issues/2240)

**Comment by LeeBamberTGC** [comment]
@Skevos-Mavros I agree, it does look like a GPU drain. As the other issue 2240 has more evidence for a GPU issue rather than a physics one, I will close this as we already have another physics player movement issue live and @UltraVox001 has the detailed report if this is a GPU issue.
