### ISSUE TITLE
Question - Is Submitting Crash Reports to Microsoft Useful?

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2135]
On those occasions that GGM crashes (much less often now thanks to the tip I received at https://github.com/TheGameCreators/GameGuruRepo/issues/2129) Windows prompts me to submit a crash report to Microsoft.

Is this useful?  Does the data make its way to TheGameCreators?  Or can I skip it?

Thanks!

![GGM Crash Report](https://user-images.githubusercontent.com/56815299/154179047-72ce6e1f-278b-4cc9-a1e5-9cf83e0394b9.png)

**Comment by plemsoft** [comment]
@Skevos-Mavros Thanks for your question , yes you can skip it, no one is going to see it anyway :)
