### ISSUE TITLE
GGM Selection Bounding Box Only Works in Full Screen

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2136]
When using SHIFT+Drag to multi-select items in the GGM editor with a bounding box, the bounding box works fine when the GGM editor is fullscreen:

https://youtu.be/1h_dMUSgf1k

But when not full screen, the bounding box does not line up with the mouse pointer:

https://youtu.be/LdXgBVN0uis

Thanks,

**Comment by plemsoft** [comment]
@Skevos-Mavros Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Skevos-Mavros** [comment]
Oops - just noticed that this was still open.

Yes, the original bug has been fixed, thanks!

BUT... the bounding box still operates in an unexpected/unintuitive way:

https://youtu.be/LftybFj4UWQ

In the video above, I'm holding down both shift and the left mouse button continuously.  As the pointer leaves the 3D view and enters the rest of the interface, it behaves in unexpected ways (switching to drag-terrain mode).  Based on most other software, I would have expected the bounding box to vanish as it does but NOT to be able to drag the terrain from outside the 3D view.

Should this be a separate bug report, or leave it here?

Thanks!
