### ISSUE TITLE
GGM Windowed Tooltip Crash

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2137]
When GGM Editor is not full screen, tooltips seem to cause GGM to crash.  See video:

https://youtu.be/rbvuiYic1Kg

This SEEMS to only happen when the tooltip extends beyond the GGM Window.  This doesn't seem to happen in fullscreen at all.

Thanks,

**Comment by plemsoft** [comment]
@Skevos-Mavros Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Skevos-Mavros** [comment]
I can confirm that this problem has been **_FIXED_** (ie, tooltips are now always within the editor window, thus avoiding the crash).

Thanks!

BTW, in this situation (where a bug I submitted has been fixed), should I just "Comment" that it has been fixed (as I'm doing now), or should I "Close with comment"?  I'm not sure of the correct procedure/etiquette here.

**Comment by plemsoft** [comment]
@Skevos-Mavros Thanks for getting back, and yes just close the issues when you have seen that they work :)
