### ISSUE TITLE
GG Max Bug Report - Use switches and take a weapon through walls

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2139]
- A switch should not work through a wall :
![SwitchWall](https://user-images.githubusercontent.com/96718175/154209764-5a4b4a8c-b50e-495f-a01f-64701199ba0f.jpg)
- The player must not know how to take a weapon through a wall :
[https://i.gyazo.com/15d593adef969efd4ee2f66c758da3f1.mp4](https://i.gyazo.com/15d593adef969efd4ee2f66c758da3f1.mp4)
- Same problem for ammunition.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb You can use a ray cast to see if the camera can see the object. If the ray hits some obstruction, do not allow the user to see the prompt or use the switch/weapon pickup/etc

**Comment by dllllllllllb** [comment]
@LeeBamberTGC To find the code I looked for rays, I came across WickedCall_SentRay and started tracing back from this. It got me into M-Lua and following that lead me to nowhere. I then tried to look for the actual interaction with the object so I tried to find the code involving pressing "E" key. I looked into t.plrkeyE, KeyState(g.keymap[18]), t.tKeyPressE, g_keyPressE, g_PlrKeyE with no results. Tried looking into IntersectStatic / IntersectAll but no call hierarchy was found for these. Then looked into IntersectCode but again I couldn't find anything useful. 

I need a lead to go off from :)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb No need to hack anything on the C++ side, just use the LUA command:

IntersectAll: x=IntersectAll(x1,y1,z1,x2,y2,z2,IgnoreObj) -- returns 1 if the ray cast hits ANY entity or lightmapped geometry

Add it to any behavior LUA scripts for things like switches, collecting weapons and ammo.  Let me know if you need help understanding what the parameters do, but you can search through all the existing scripts for examples of its usage.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Not at all, much simpler than that :)  Check out the SWITCH.LUA script, this is the one that the switch object uses. You can see the code operates the switch behavior and decides what the switch does, and decides when the user sees the prompt to press the E key:

 if PlayerDist < 60 and g_PlayerHealth > 0 then
  local LookingAt = GetPlrLookingAt(e)
  if LookingAt == 1 then
   if g_Entity[e]['activated'] == 0 then
    if GetGamePlayerStateXBOX() == 1 then
     PromptLocalForVR(e,"Y Button " .. g_switch[e]['ontext'],3)
    else
     if GetHeadTracker() == 1 then
      PromptLocalForVR(e,"Trigger " .. g_switch[e]['ontext'],3)
     else
      PromptLocalForVR(e,"E " .. g_switch[e]['ontext'],3)
     end
    end
    if g_KeyPressE == 1 then

Simply add the IntersectAll command somewhere around the 'LookingAt ' code so the line of sight must be clearbefore the user gets to have the option of pressing E.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Wow, ok. I tried calling IntersectAll inside there but it wouldn't change colour to look like other functions and searching for it inside global.lua also didn't give me any results so I assumed I will somehow have to integrate it and went down the rabbit hole... 

Well, at least (i think) I learned how it works 😄

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
![switch](https://user-images.githubusercontent.com/96718175/157847388-41919949-441f-4ba2-a17a-27b657da87f1.jpg)

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Fixed for next build. @dllllllllllb Situation of two coders working on the same script :)  Always get a little paranoid when changing script, best to check with me before starting and making sure you have the latest from me before starting.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
It's better than before. It works, but not always. Some switches may still offer to be used while on the other side of the wall. This especially happens when there are two switches in the same place, but on either side of a wall.
![Switch](https://user-images.githubusercontent.com/96718175/158808538-7c541438-8371-4663-b605-99d33b2fb83b.jpg)

**Comment by ZakJudges** [comment]
confirmed, doesn't work in the above case. @LeeBamberTGC I can do this one if you like, I think it would just be a case of a dot product between the switch direction and camera direction

**Comment by LeeBamberTGC** [comment]
@ZakJudges Already code in place to cast a ray to the target and if it is blocked, the switch/weapon cannot be operated.   There is no guarentee which orientation an object will be so the dot product may not help.  The test is whether the player can SEE the target object and only then have the option to operate it. If the WALL is in the way, the other switch should NOT be presented. That will be the bug here if still present.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Now uses a ray cast and detection so must be in line of sight with object before can interact with it.
