### ISSUE TITLE
GG Max Feature Request - The Materials section should include the sound (footsteps) of the object (Material sound)

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2140]
I face this every day. I place an object on the ground (tiled floor, house, hangar...) and the sound produced is not always the right one. As Max's V1 and V2 hangars don't produce a metal sound when stepped on. However, the floor is metallic.

In addition to the textures, the Materials section of the selected object should include and allow the selection of the sound produced by our steps, when we walk on them. At a minimum, Max should provide a button that opens the .FPE file of the selected object. This would save the user from wasting time looking for files, while Max knows exactly where to find them and open them in Notepad.

Once the sound has been changed in the .fpe, one should not have to restart Max for the new sound to take effect. This should be considered when launching the TestLevel.
![Materials](https://user-images.githubusercontent.com/96718175/154212576-b86593ef-0b0d-4f2a-9d0f-c98ae3f69c28.jpg)

**Comment by ArgentArts** [comment]
This is a definite must-have!
https://github.com/TheGameCreators/GameGuruRepo/issues/2268

**Comment by ArgentArts** [comment]
Forget FPE files. Seriously. We should not have to leave MAX to do something as simple as add a sound file for a footfall. We should not have to be editing .ini files, .fpe files, etc. to get games to work. This is supposed to be pretty close to an "easy game" system. Simply add a field to the material area where we can load in a sound file right there in the MAX properties panel.

**Comment by LeeBamberTGC** [comment]
@ArgentArts We cannot delete FPE files, they define the out-of-the-box settings for different objects.

**Comment by ArgentArts** [comment]
I did not say to delete any FPE files. Where did you read that? I said we should not have to be editing FPE files or INI files. The point is, the end-user should not have to leave MAX, search through directories to find the correct FPE or INI files, open them, and make changes. Instead, they should be able to do what they need to do RIGHT IN MAX.

**Comment by ArgentArts** [comment]
What about about "forget FPE files" was that we should not have to leave MAX to do things like add sound files for footfalls, etc. Sorry if that was misunderstood.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Right, gotcha.  I agree completely, leaving the software and messing about with internal files to do general game-making stuff is a BIG NO-NO for MAX!  There are a number of materials at the moment, the biggest ones I can think of are the terrain materials which are fixed, and the custom materials per object. I assume you mean being able to override the given 'material mode' with a custom material such as Alien Velcro, and then provide your own sound variations for footfalls, impact, etc. the current system needs these many:

![image](https://user-images.githubusercontent.com/35840583/155592028-efa0353b-3fe3-47fb-aa23-b04f0d58cf79.png)

**Comment by ArgentArts** [comment]
What I mean, for myself, is if I import a model, such as a tile to be used for a floor, I want to be able to assign a footfall sound to it. I make my own models and am primarily interested in interior-only levels. But even with terrains, I would want to be able to assign my own sounds, if I wanted to. 

For models, I think it would be best/easiest, if there were a simple sound import area under Material when you click on an imported entity, right there under all the other stuff, like Normal, Metallic, Emissive, etc. It could be the last thing in line - perhaps a check-box for "Use Footfall?" If checked, you get access to importing a sound file.

**Comment by LeeBamberTGC** [comment]
@ArgentArts So we can keep materials for terrain and custom materials separate, how about the concept of a 'real world material' and having sounds associated with them, and the user being able to create additional material types. This way the user can assign existing materials that we have already provided:

![image](https://user-images.githubusercontent.com/35840583/155593097-9677cd48-69e5-4a0b-bc0d-612de538adda.png)

And can then add their own material name, decal type, and sound set if they need more wood, metal, concrete, etc effects for their game level?  I am thinking something like how you select a particle from the Particle Library, but you can add (import) more to your library if you wish.

**Comment by ArgentArts** [comment]
That sounds good to me as long as it's simple to use, flexible, and allows the end-user to easily assign sounds to what they need. 

The only caution I throw out there is this - when MAX first started, it was all about the end-user being able to import their own grasses and painting with them, importing their own trees and painting them in, etc. Then, it became bioms and, as of now, the end-user cannot paint their own grasses and plants and cannot paint their own trees. The simplicity of customization went out the window at some point over this idea of bioms. Don't get me wrong, I think the bioms are pretty cool. It's just a shame that user-customization became lost or put last in all this. Whatever happens here, with being able to add our own sounds, it needs to be easy and flexible so that the end-user is free to create, not bound and locked into something that's akin to the current biom system, imo.

I hope that doesn't sound harsh. It's not meant to be.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
What @ArgentArts is saying is that editing an .FPE file should be done in Max.
Here in this case, we would need to add a sound to a Material, without having to :
1/ Look for the .FPE
2/ Modify the .FPE manually
3/ Save the Map
4/ Exit Max
5/ Reopen Max
6/ Load the Map
7/ Test the Material
All this, just to add a sound to a Material.

Not only would Max need to know how to do this from the "Materials" section, but we would need the change to be considered in the TestLevel, without rebooting Max.

We need a quick and simple solution. And your proposal is already going in the right direction. :)

**Comment by ArgentArts** [comment]
Yep. A simple method of importing a sound file at the end of the material properties area in MAX is all that's needed. You select your entity (a floor tile, for example), go to edit the material (select the Material tab on the right-side), and import a sound file. DONE. That's it. Simple.

**Comment by UltraVox001** [comment]
@ArgentArts 
However, consider what @LeeBamberTGC says. The list of files to provide does not stop at 1 sound. Several are needed. The sound of sidesteps is not the same as that of moving forward or backward. The one for running too, it is different from the one for walking. etc You have to be aware of all this and not imagine that it is enough to add 1 sound. :)

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
I suggest you add a button in the UI (Materials section) that opens a Panel for managing all Footsteps. If the user only has one sound, too bad for him. :) The most important thing is to allow us to modify all the footsteps at our convenience, and to allow Max to play the TestLevel without having to reboot Max (immediate taking into account of new sounds).

**Comment by UltraVox001** [comment]
In the worst case, add an option to reset the original sounds. :)

**Comment by ArgentArts** [comment]
![footfall](https://user-images.githubusercontent.com/36735507/155596416-bfaca63b-c23b-4f26-97b8-383451570e6a.png)

Well, I created this before what UltraVox001 had said, but it could also open to folder of sounds. 

Better yet, there could be a set of rules for how to create sounds. For example footfall sounds should end with the following:

_walk
_run
_sidestep

Etc.

You can start the sound name with anything you like, but as long as it is followed with these endings, MAX will know what do do with them. Thus, wood_walk and wood_run and wood_sidestep would be used appropriately in-game.

**Comment by ArgentArts** [comment]
Hey! At least there's a discussion going on about this. ;)

**Comment by ArgentArts** [comment]
Okay, so, here's how we make it simple -

Many game engines, MAX included, already have naming conventions for things like materials. If you import a model and it's albedo is named Rifle_albedo, then it looks for Rifle_normal, Rifle_Metallic, etc. (or Rifle_n, Rifle_m, etc.). You don't have to import a folder of textures or import all textures. The game editor looks to see if all textures are there and imports the ones that are. If any are missing, it ignores them and moves on. MAX can do the same with sound files. 

On the Material tab in Properties, we have a Footfall Sound import (like I originally had before I'd changed the image above). The end-user imports the Walk sound file (the equivalent of a material's albedo or color file, being the first or prominent) and MAX then looks for all the rest, loading them if it finds them based on a naming convention. The naming convention is a "_" followed by the appropriate word, such as "walk", "run", "backwards", "sneak", "sidestep" or whatever else MAX will use.

**Comment by mav3r1ck1981** [comment]
@Kasseyus this is already implemented and could be closed?
