### ISSUE TITLE
Terrain Generator

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2141]
The Generate Terrain Button is missing in the latest internal build!

**Comment by rvanner** [comment]
@plemsoft Can you fix now and send me a new exe? I need to make a tutorial video this morning and this button has to be on screen. Thanks.

**Comment by rvanner** [comment]
@plemsoft It's now showing up! I have no idea how it disappeared. I'll keep an eye on it to see if it disappears again. Maybe check the code to see if something could make it hidden?

**Comment by plemsoft** [comment]
@rvanner Strange ? i dont see anything that could hide it ?

**Comment by rvanner** [comment]
I'll close this for now. I'm sure it'll be reported again if it's something that appears often.
