### ISSUE TITLE
MAX - 2022.02.18 - Illumination Textures Missing From Standalone

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2144]
2022.02.18 Tuesday Build

MAX doesn't copy over _illumination textures to standalone in this build
I still have a few models not updated yet that use the _illumination naming convention
- not sure if it is intentional
- so just wondering if it is now requirement to always use _emissive naming for illumination textures

**Comment by LeeBamberTGC** [comment]
@OldFlak No worries, I will extend support for the emissive system to recognize _illum and _illumination though certainly for our own stock and game kit files we will be using the naming convention of _emissive.

I think this is the same as the issue: https://github.com/TheGameCreators/GameGuruRepo/issues/315

Here is the code we use to detect and include support texture files, let me know if you spot anything odd that might cause your standalone not to include your ILLUM texture:

					int iNewPBRTextureMode = 0;
					if ( cstr(Left(Lower(Right(t.tfile_s.Get(),10)),6)) == "_color" ) iNewPBRTextureMode = 6+4;
					if ( cstr(Left(Lower(Right(t.tfile_s.Get(),11)),7)) == "_albedo" ) iNewPBRTextureMode = 7+4;
					if ( iNewPBRTextureMode > 0 ) 
					{
						cstr pToAdd;
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_color."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_albedo."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_normal."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_specular."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_metalness."+t.tfileext_s; addtocollection(pToAdd.Get());
						#ifdef WICKEDENGINE
						pToAdd = cstr(Left(t.tfile_s.Get(), Len(t.tfile_s.Get()) - iNewPBRTextureMode)) + "_surface." + t.tfileext_s; addtocollection(pToAdd.Get());
						#endif
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_gloss."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_mask."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_ao."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_height."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_detail."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd = cstr(Left(t.tfile_s.Get(), Len(t.tfile_s.Get()) - iNewPBRTextureMode)) + "_illumination." + t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd = cstr(Left(t.tfile_s.Get(), Len(t.tfile_s.Get()) - iNewPBRTextureMode)) + "_illum." + t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd=cstr(Left(t.tfile_s.Get(),Len(t.tfile_s.Get())-iNewPBRTextureMode))+"_emissive."+t.tfileext_s; addtocollection(pToAdd.Get());
						pToAdd = cstr(Left(t.tfile_s.Get(), Len(t.tfile_s.Get()) - iNewPBRTextureMode)) + "_cube." + t.tfileext_s; addtocollection(pToAdd.Get());
					}


Notice that your main color texture needs to be called _color or _albedo to activate the extra includes.

**Comment by OldFlak** [comment]
@LeeBamberTGC Yes thanks for looking at this Lee. 

I don't need this myself, as it is my intention to use _emissive anyway as I prep them for the import process (just updated the few stragglers I had) so I be happy for it to stay as is.

For me this is not an issue, but rather an observation:
I was just thinking of when others try to import from Classic, a lot of models out there were using the _illumination extension so it may affect those users.

So is probably ok to close thread :)

**Comment by OldFlak** [comment]
@LeeBamberTGC Hi Lee just FYI - this is not fixed.
Left a few illumination stragglers in order to test. Created standalone with 2022.02.25 Friday release build and still same issue with not being copied to standalone.

Some audio files do not get copied over, and some don't play although they have been copied over.

Also copies over files that are not used at all.
For example all particles from both default and custom folders get copied even when only one or two custom ones are used.

**Comment by LeeBamberTGC** [comment]
@ZakJudges Bouncing any save standalones to you, let me know if you need any insights :)

**Comment by ZakJudges** [comment]
Hi @OldFlak, I tried to reproduce this one but the standalone had the _illumination correctly copied across. Are you still seeing this issue in the latest build? If so, would you mind sending me a model you are seeing the issue with? Or alternatively, if you let me know the filepath of the texture not being copied over, that may give me some insight as to where things are going wrong :)

**Comment by OldFlak** [comment]
@ZakJudges Thanks for looking into this

Sorry for late reply. Have not tried for a awhile as Standalones have been quite a mess in other areas since bug bash began.

So made standalone using 2033.03.31 EA.

Issue remains:
The bars on this fencing are all meant to be illuminated.
![image](https://user-images.githubusercontent.com/12246318/161419359-6fa098b8-d234-4b6b-8975-96803581d7c3.png)

This is the folder where the texture should be:
![image](https://user-images.githubusercontent.com/12246318/161419468-66bd0b32-6c2f-48fb-a736-62423052f48b.png)

This is the folder where it should be copied from:
![image](https://user-images.githubusercontent.com/12246318/161419566-5c145b46-81c2-4c39-9992-f580319cea46.png)

**Comment by ZakJudges** [comment]
@OldFlak Thanks for the extra info. I agree that other areas need more work before this so I will change it to medium priority for now :)
