### ISSUE TITLE
If you Undo the placing of objects that were part of a group, the group becomes invalid to use

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2146]
How to create this issue;

- Put down some objects
- Make them into a group
- Press UNDO to remove all the objects
- The group is still in the group list but it cannot be used now

![image](https://user-images.githubusercontent.com/1503593/154288982-b443f1b9-7c04-4d88-a624-a8e01b946539.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Do not forget the MAX tag so we can filter and find quicker, thanks!

**Comment by LeeBamberTGC** [comment]
@ZakJudges Prevent a group creation from being UNDO'd

**Comment by ZakJudges** [comment]
@plemsoft I'm not sure about this one. If you restart Max then the group is fine to use again, so I'm guessing its just an issue with an eleprof variable, but I'm not sure which one. Any ideas? Thanks :)

**Comment by plemsoft** [comment]
@ZakJudges Yes the grouplist point to the entityelements that are now deleted , so yes the group would fail, guess the best way is to remove all the elements in the group when you undo and also remove the group. isEntityInGroupList will check if a entity is inside a group and return the group index if so :)

**Comment by ZakJudges** [comment]
@plemsoft Thanks :) I ended up adding Group/UnGroup to the undo system so that when you undo grouped objects, the group is first ungrouped before the objects are deleted, that way the group data is never altered. That fixes this bug, but I am still having issues with restoring the group data to how it was before, when performing a redo. Any chance you could take a look at my commit when you have time and see what else I would need to add to GroupUndoSys? :)

**Comment by rvanner** [comment]
@ZakJudges Still not working in latest build so I am removing the label.

**Comment by plemsoft** [comment]
@ZakJudges For the Redo to work:
Say you have a group of 4 barrels.
When you make the first undo ( on the first barrel that are part of the group) you now ungroup it and save this event. And remove the first barrel and save this event.
When you have undo'ed all 4 barrels, you hit redo , then redo this entity like normal.

When you redo the "ungroup" event , you rubberband the 4 new barrels (entity ids) and call a CreateNewGroup(-1); , that will recreate the group again.

Somehow you need to mark the the barrels that was part of the group when you make the "undo" so your able to make a new group of these marked barrels when you hit a redo event.

**Comment by ZakJudges** [comment]
@plemsoft Got it, thanks :)
@rvanner The fix should be in the next experimental build :)

**Comment by ZakJudges** [comment]
@rvanner Could you confirm if this is now fixed for you? Thanks :)

**Comment by rvanner** [comment]
Fixed!
