### ISSUE TITLE
GG Max Bug Report - All SkyBoxes shake when walking

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2150]
All SkyBoxes shake when walking.
The bug is found on the latest internal build of this Wednesday.
I see it on a new map, but also on the old ones.

**Comment by LeeBamberTGC** [comment]
@PaulSJ I know we have discussed this a few times, and the shake is LIKELY related to float precision. I say likely as I have other values out on the edge such as physics and they behave fine, so there might be another cause for the sky shake at extremes. Just assigning to you so you can have a think out of the box. End of the day, we do not really need the simulated sky to be rendering from the players position, the sky is so far away we might just keep it at 0,0 on the XZ and see if that helps.

**Comment by ZakJudges** [comment]
Hi @UltraVox001, is this issue now fixed for you? Thanks!
