### ISSUE TITLE
demo dilema part 3

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2151]
after a previous post was informed that my map and most of the collisons where set to convex hull (these are the ggmax assets) and that convex hull kills performance, if that's the case why are they set to this by defualt when it would just make more sense for them to be box collisions?

![image](https://user-images.githubusercontent.com/68471279/154318880-ad59731b-e646-4910-b690-bcf1997891fb.png)

what this means for me is, my game demo is a performance nightmare. I assumed ggmax would have its included would be optimized for the best performance?

regardless. My demo is broken. Two weeks and 14 hour days for nothing.

**Comment by UltraVox001** [comment]
GG Max, Unity, Unreal, Hero Engine : all 3D engines are "performance nightmares" for users who don't know how to use them. Max can help you speed up certain phases of development. But he can never think for you.

**Comment by casigus** [comment]
ayeeee 100% changing habbits with otther levels and thanks to vox's explanations the other day, things work really well. Im just urghhhhhhhh at the dam demo :(

**Comment by ArgentArts** [comment]
I get it. I do. But whining isn't helping. And GitHub isn't the place for it, either. This is a place to REPORT BUGS and to make REQUESTS to improve GameGuru CLASSIC and GameGuru MAX. We shouldn't be cluttering up GitHug with things that don't further along the development of the software. Not trying to be mean, mind you. :)

**Comment by UltraVox001** [comment]
Since launching Max, I've built at least 30 "complete" maps. I almost destroyed them all. :) Because Max is an Alpha. It is in full development phase, and the month of February is dedicated to debugging. Despite all the maps I made, I never thought of creating one for the TGC demo. I worked hard (and I'm not the only one) on maps as complex as possible. Because I want to find bugs for TGC to fix. It's the only thing that matters to me. The TGC competition? Frankly, I don't care. I suggest you use Max for something other than "competition".
![demo](https://user-images.githubusercontent.com/96718175/154330178-002b3934-6427-4276-9d9b-b0c56ec55372.jpg)

**Comment by casigus** [comment]
i feeel exactly tthat! love the look of that!!! yeah i was reporting that the assets should be default to box or polygon.

**Comment by ArgentArts** [comment]
No, assets should default to whatever works for them ... box, polygon, cylinder, etc. BUT that may not work for you and you may need to turn collision completely off if a player cannot get to the object anyway. So, it technically doesn't matter what it's set to by default as you should be checking it anyway. ;)

**Comment by UltraVox001** [comment]
@ArgentArts +1 :)
@casigus :
By default ? I would be TGC, there would be no collisions by default. This would force the user to read a collision tutorial. Because there is (almost) nothing more important when you start in 3D with a level editor.

**Comment by ArgentArts** [comment]
Again, we're not trying to be mean, but game development, even with an "easy game creation" system, is never truly easy. There is always something to learn. And optimizing is always the name of the game. There are always trade-offs to keep things running in real-time, especially if your trying to get a game to run on systems that are not top-of-the-line.
