### ISSUE TITLE
Adding a distorted Character Model

### ISSUE THREAD

**Issue by Shalshek** [TheGameCreators/GameGuruRepo#2154]
Hi! I'm sorry, maybe someone has already asked this question, but their hands are already dropping, and I can't find any information about this in any way. When loading a new model, it turns into this (see photo). This applies to ALL models downloaded from the Internet. When creating a model in the mixamo editor, everything is normal. Can you tell me how to fix this problem? (gameguru classic license)
![WTZWsLOb_LY](https://user-images.githubusercontent.com/99836387/154344368-9d7f1eac-8e54-4aac-a9fd-0241d5624eb0.jpg)

**Comment by plemsoft** [comment]
@Shalshek Thanks for your question , normally this is a problem with the pose of the object you download , there are some great tutorial on the forum that explains this, also if you have problems like this a good way to get help is to post on the forum. There are many threads about importing from mixamo here is one you can try:

https://forum.game-guru.com/thread/222087#msg2633601

There is no directly converter for mixamo in GameGuru you need to setup/prepare the model yourself, as many have done before with success, the process is not easy but possible with a little patience.

Hope this answers your question , thanks :)
