### ISSUE TITLE
GG Max Bug Report - Door Rising script malfunction

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2155]
Script tested on several maps with the latest internal version.
Door Rising video : [https://www.youtube.com/watch?v=pQspA0pyALs](https://www.youtube.com/watch?v=pQspA0pyALs)

I hope it can help.

**Comment by ArgentArts** [comment]
I've not tried the door rotate script yet (perhaps I should before I comment), but shouldn't a door model have the origin in the correct place for it to work? In other words, if the origin of the model is in the center, then the model will rotate about its center. If the model's origin is at one corner, then it will rotate at that corner. This is typically how these scripts work and, if so, it's important to have a model's origin set properly. Note - you are using a wall, not a door, to test this. As such, whomever made the wall would most likely have the wall's origin at it's center and, thus, it would rotate there if you tried to use it as a door.

**Comment by synchromesh62** [comment]
> Scripts tested on several maps with the latest internal version.
> 
> Door Rising video : https://www.youtube.com/watch?v=pQspA0pyALs Door Rotate video : https://www.youtube.com/watch?v=AYjqT4oKLD8 The door gradually rises upwards, and the axis of rotation is incorrect.
> 
> I hope it can help.

You need to make sure the wall \ door is set to **isimmobile**  and of course it depends where the origin is on the model.
I just tried the stock one on my door and it worked fine and then a Military one with a centre origin which also rotated perfectly 

https://youtu.be/n73fyoTb1ys

The idea of this of course is mainly for Custom doors so if you wanted to creat a normal one you would have to set the origin left or right off the model.

![origin](https://user-images.githubusercontent.com/35708217/154370274-4e117990-1603-42fd-bcb6-7b937b431915.png)

**Comment by UltraVox001** [comment]
You are both right about the rotation script. The "isimmobile" must be activated, and of course it requires a model with a suitable axis. So I changed the title of this post.

**Comment by UltraVox001** [comment]
And now the Rising script works too, while the door was on IsImmobile in this demo.
I do not understand anything anymore !
In the map in which I discovered the bug (not the one in the video), I hadn't touched this door for days.

**Comment by UltraVox001** [comment]
I close here.
Thank you both.
