### ISSUE TITLE
 levels fail to load after a certain size has been reached

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#2156]
Hi
levels fail to load after a certain size has been reached in the other over 10GB of system memory.
the video shows the bug: https://youtu.be/TJSBcueAgNg

![Untitled2](https://user-images.githubusercontent.com/47690174/154398854-3eed4435-9f15-45b2-949d-da84d3385e6c.png)

Notice the 44 GBs real mem waste and the 0.3 fps; of course, it crashes and had to rid of it via TM; for some reason, the pic is named "untitled2" lol

So, I had tried an early build of the same level, and it loads (take for a while) and prepare yourself to make travel thru the 3ª dimension; after that, you can see the real level and you can see it has nothing to do in test mode, compare with the editor one.

I know most of my custom models are high poly, high texture res, and even a big complex geometry most of the time; but guys, those sorts of models are going to come and GGMax should be prepared to deal with them, that's the reason I often am testing GGMax with those sorts of meshes. :)

It is a hard word, but someone has to do it. lol

**Comment by LeeBamberTGC** [comment]
@3coms I have emailed you for the last loadable level so we can see where the memory is going. It is likely just shear sizes, and the solution will either be some kind of threshold to stop levels getting too large before crashing out, or some kind of conversion or mitigation step to reduce how much memory the assets actually take.

We do have one big optimization on the cards to reduce the number of custom materials being used, and adding an virtual object system, both these ideas have the potential to drastically reduced the memory hit, and increase performance for both editor and final game.

**Comment by LeeBamberTGC** [comment]
A related issue duplicated this one, so redirected here. I have a game project with one level that loads and runs, so we are okay with a single level in that case, though many levels in the game project and a standalone game created from it also showed the issue of memory consumption as each level was loaded in to create the standalone.

Next step here is to track where this memory is going, and we will need a large level that can load and run, but take MAX to the 'max' as it were.

**Comment by LeeBamberTGC** [comment]
ANYONE READING THIS : If you have a level that loads into MAX and takes around 9-10GB of memory in the process, but can still complete the load AND RUN, please email it directly to me at lee@thegamecreators.com

From this, we can trace where the memory is going!

**Comment by casigus** [comment]
could be going with the collisions, since ive started turning everything either a box or a polygon things have improved drastically:

https://www.youtube.com/watch?v=fmGetkdyXKQ

**Comment by LeeBamberTGC** [comment]
@casigus Nice video, I look forward to playing with the finished level!  When you have time can you attempt to make a standalone executable out of one level with this Friday's build and send it to me at lee@thegamecreators.com.  Cheers!!

**Comment by casigus** [comment]
yah ill give it another try.

**Comment by LeeBamberTGC** [comment]
@casigus Did you get time to do this?

**Comment by casigus** [comment]
forgive me, ive tuned off most of this week, not really done anything. brain needed a rest. I'll get it done with the new update. I tried to go big with the standalone demo and that was my mistake, so going to build a single level using max only assets and showing off the different things max can do. sorry aboot the delay, mental health has to come first, but ill get this done.

**Comment by LeeBamberTGC** [comment]
@3coms A lot of work on memory reduction for larger levels in this weeks build.

**Comment by 3coms** [comment]
@LeeBamberTGC 
I've noticed it in today's test of my Cellar_building level, it drops from **21 GBs and 2,1 fps** to just **6GBs and 60 fps**, which is so cool. :)
I will be testing my large levels, in the next builds. :)
