### ISSUE TITLE
Add a tick box to Developer Settings for the FPS and Memory read out

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2158]
Add it here please:

![image](https://user-images.githubusercontent.com/1503593/154442535-d20491fb-29a3-4d01-bf02-e32556b2f326.png)

**Comment by plemsoft** [comment]
@rvanner Fixed for next update :)

**Comment by rvanner** [comment]
@plemsoft OK, so the version I updated didn't turn off the stats so I assume the next on will.

**Comment by plemsoft** [comment]
@rvanner It works for both mode , superdevelopermode=3 and the checkbox , so you properly have "superdevelopermode=3", to test it you should set it to superdevelopermode=0 like a normal user :)
