### ISSUE TITLE
Terrain editing happens when you click in the Object Library!

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2159]
This is a big bug! As you use the Object Library, any clicks you make are also picked up by the terrain editing tools!

![image](https://user-images.githubusercontent.com/1503593/154448005-a9d24122-e982-4d6a-936a-8ea341cac1ad.png)

**Comment by ZakJudges** [comment]
@rvanner This will most likely be related to my fix for #1917 
I think I know the issue and can sort it now :)

**Comment by plemsoft** [comment]
@ZakJudges Yes remember !bImGuiGotFocus , i assign it to you :)
