### ISSUE TITLE
realshadowcascadecount in setup.ini bug

### ISSUE THREAD

**Issue by UnknowNomad** [TheGameCreators/GameGuruRepo#216]
Any values below 8 creates shadow glitch instead of skipping those shadow cascades.

Reproduction:
1) Set this value to below 8
2) Launch GameGuru
3) (Optional) Load The Big Escape level
4) There will be shadow line, which would disappear if you get close to terrain. Present both in editor and test game.

**Comment by plemsoft** [comment]
This was fixed from version "2018.06.16 - DirectX 11 & PBR"
