### ISSUE TITLE
Object Library

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#2160]
It would be nice to be able to select more than one object at a time to add the the level , like a weapon with its ammunition

**Comment by rvanner** [comment]
Press CONTROL each time you select an object!

**Comment by ArgentArts** [comment]
I think he means from the Level Objects panel. So, if he wanted to add BOTH the Snub Nosed Pistol AND its Ammunition in one shot, he would have to be able to select both from the Level Objects panel on the right or from the Add menu when it's open.

**Comment by Granada1** [comment]
```
I think he means from the Level Objects panel. So, if he wanted to add BOTH the Snub Nosed Pistol AND its Ammunition in one shot, he would have to be able to select both from the Level Objects panel on the right or from the Add menu when it's open.

```
That’s exactly it

**Comment by Granada1** [comment]
(Press CONTROL each time you select an object! ) 
Just tried with latest update and it worked
,closing

**Comment by Granada1** [comment]
If you mean trees and grass , I can select multiple just by right clicking !

**Comment by ArgentArts** [comment]
I mean the object list on the left side. Sorry. Where you select guns, walls, and things you've already placed in your level.
