### ISSUE TITLE
Object Groups: There is a big performance hit if a group includes a flatten object (building)

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2161]
As you drag in an object which includes an object that needs to flatten the terrain, the FPS slows down as it tries to flatten the terrain. Should only do this once placed down.

Watch the video:
https://youtu.be/KjmYkq3m8Po

**Comment by LeeBamberTGC** [comment]
@rvanner For tagging, please include the MAX label and also choose a single category tab so it can be easily classified and assigned.
