### ISSUE TITLE
Object Groups: It's possible to delete a group without being warned

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2162]
1. I have a group made
2. I bring a copy in to the scene
3. I delete the original group by dragging it to the left panel (this is when I should be warned)
4. The group icon is removed but I still have a group in the level

See this video;
https://youtu.be/AMXB2gI2-io

**Comment by LeeBamberTGC** [comment]
@rvanner Now added warning when dragging into the current object/group window, and does NOT delete the parent group any more.  In next EXP build.

**Comment by rvanner** [comment]
@LeeBamberTGC You cannot seem to delete the non-parent groups.

**Comment by LeeBamberTGC** [comment]
@rvanner I created three characters, made them a group, then dragged in a copy of the group to stand in front of the first set. I click the first set (the old parent group), pressed DELETE and they deleted. Then clicked the second copied set, and pressed DELETE, the warning shows up. To delete the final parent group, select it, then click the UNGROUP button, then you can delete them manually. Works with last nights build:

![image](https://user-images.githubusercontent.com/35840583/165294025-7a0a07b7-74b6-4d20-b909-4728b8ba9bde.png)
