### ISSUE TITLE
Lighting issue with some assets.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2163]
Some assets in MAX don't light equally. In the example below the boiller and the insulation roll have different natural lighting. The roll appears as if it has no texture, while the boiler in unaffected by shadow.

![lightingissue](https://user-images.githubusercontent.com/99803873/154458812-299c8874-f17e-4f65-b184-312c89547648.jpg)

**Comment by ArgentArts** [comment]
I had this happen in the editor, but it sorted out after testing the game. Hasn't happened since, so it seemed sort of random on my end. I'll look for it to happen again, though.

**Comment by LeeBamberTGC** [comment]
@davetgc Can you list the name and location of the objects you noticed this effect?  I cannot reproduce with randomly selected objects in a room with no lighting.
