### ISSUE TITLE
Standalone missing files

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2164]
Characters from the character creator are missing some files when exporting as standalone. Seems to be files using the a,b,c naming convention.

![Screenshot 2022-02-17 104000](https://user-images.githubusercontent.com/32545391/154459295-1c6f1544-51c2-4354-825b-10d568a86944.png)

@plemsoft Is this something you are able to sort, or should the textures be renamed to only use a numbering system? :)

**Comment by plemsoft** [comment]
@ZakJudges I do not see that here ? , it takes the textures from the .fpe and copy over all those (that are used), do you have a sample where it do not copy over all textures ?

**Comment by ZakJudges** [comment]
@plemsoft Turns out custom characters are fine, and all textures are copied correctly. But for characters that come with Max (entitybank -> Characters), the issue occurs

**Comment by plemsoft** [comment]
@ZakJudges Fixed for the next update :)
