### ISSUE TITLE
Runtime Error 501 \ imagezone in standalone

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2166]
Getting Runtime Error 501 via the imagezone in standalone and noted the imagebank not being copied to standalone.
Manually copying it across did NOT fix the issue .

![error](https://user-images.githubusercontent.com/35708217/154488688-7bfdb228-12d2-42dc-a9eb-fd8aa1fa533b.png)

**Comment by ZakJudges** [comment]
hi @synchromesh62, I confirmed the imagebank folder is not copied to standalone. However, I did not encounter a crash, instead I got a blank image. Are you still getting a crash in the latest build? :)

**Comment by synchromesh62** [comment]
> hi @synchromesh62, I confirmed the imagebank folder is not copied to standalone. However, I did not encounter a crash, instead I got a blank image. Are you still getting a crash in the latest build? :)

Hi Zak sorry for the delay i had to wait till i got home from work
yes still getting the runtime error and no image bank copied over.

**Comment by synchromesh62** [comment]
> @synchromesh62 I've added a fix for script image files not being copied over. It should be in a build tonight or tomorrow. I would imagine that will fix the crash for you, but if not just let me know. Thanks :)

Awesome thanks .. I will let you know
