### ISSUE TITLE
UI - Value conversion errors

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2167]
Some UI elements aren't converting user input to fractions properly, denominators are missing an "f" at the end which result in rounding the user input. [See this issue ](https://github.com/TheGameCreators/GameGuruRepo/issues/2152)

**Comment by LeeBamberTGC** [comment]
@ZakJudges The changes should be in this weekend's build, so you can confirm then.  Not much detail on this issue report, so providing a random selection of float-based values retain their slid value, this can be regarded as fixed.
