### ISSUE TITLE
Can select objects hidden by terrain

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2169]
**Objects behind terrain**: It appears to be possible to pick up large objects that are hidden by the terrain, this means that you can inadvertently move things you can't see. On a number of occasions I found large rocks and similar have changed position after accidental selection. This only seems to happen if the object is at least partially visible above the terrain. (but can be hidden from the current view point.).

**Comment by LeeBamberTGC** [comment]
@davetgc Now detects if terrain pixel closer than object pixel hit, allowing more intuitive selections.  Will be in next internal build.

**Comment by ZakJudges** [comment]
works in latest build

**Comment by davetgc** [comment]
Thanks!
