### ISSUE TITLE
Feature :Request : An idea about saves 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#217]
Back in the day of mapping with the Radiant quake editor when you saved a map you actually got 2 files ... " .map " and " .Bak "
 The " .Bak" was basically a backup you renamed to ".map " if anything went wrong ( it did and was more common back then )

 Just wondering how difficult something like this would be to implement into GG ...
 Seems like a good thing if you don't backup every save manually ?

**Comment by Granada1** [comment]
Great idea ,even my old modeling program saves two files

**Comment by HierToo** [comment]
What exactly is the .bak file? The old fpm(before the save) or the current save state. Sorry that I ask, but it was not clear to me and I never used quake editor.

**Comment by Granada1** [comment]
It’s just a backup file Jenerated every time you save ,just renamed and saved alongside the original

**Comment by synchromesh62** [comment]
> What exactly is the .bak file? 
The .Bak file was simply the .map file renamed so it was able to back up the exact same name map twice.
So you would get ..
MyMap.fpm
MyMap.Bak
This was automatic so if you did forget to make a copy and things went wrong you would simply name the .bak to .fpm .. Its not foolproof but got me out of trouble more than once :)

**Comment by Granada1** [comment]
Sometimes when you run your map gg can break it,but you would have a backup to open and work on

**Comment by HierToo** [comment]
I will look at it. Should not be too hard.

**Comment by synchromesh62** [comment]
> That makes no sense to me! If you save your map and it has an error then the .bak map has an error too. 

Like I said its not foolproof .. but did get me out of trouble many times back in the day.
GTK Radiant still does it so they must feel its a proven method :)
