### ISSUE TITLE
GameGuru MAX - Request - Expand Door Rising Behavior

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2173]
I would like to request that we expand the Door Rising Behavior to make it a Door Sliding Behavior that would allow the end-user to choose the direction the door would slide open - up, down, left, or right. This way this behavior could be used for all sorts of sliding doors and not just for doors that slide upward. A check box for the direction or a dropdown box could be used for the end-user to select the direction of the slide behavior. Then it becomes one behavior for multiple door slide types. :)

**Comment by AmenMoses** [comment]
See #2279 for script

**Comment by ArgentArts** [comment]
Thanks! Works a treat!

**Comment by AmenMoses** [comment]
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8155303/door_sliding.zip)

With this one you can control delay time and opening/closing time.  Both values in milliseconds btw.

**Comment by ArgentArts** [comment]
Thanks! That's pretty awesome! :)

**Comment by LeeBamberTGC** [comment]
@AmenMoses Much nicer script. I have replaced the rising one with this one and updated the switch demo level.

**Comment by AmenMoses** [comment]
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8163720/door_sliding.zip)

Synchromesh found a problem with it, here is the fixed version.

**Comment by ArgentArts** [comment]
Can we get two things added to this script (I know, greedy ;) ) - 

1 - The ability to change the default message about the door being locked and having to find a way to open it
2 - A check box (or something) to just press "E" (or whatever key) to just activate the door without a button

Thanks. :)

**Comment by LeeBamberTGC** [comment]
@ArgentArts Happy to, find in this weeks internal build:

![image](https://user-images.githubusercontent.com/35840583/157003838-12f5b45f-97ce-4e98-bfa8-5a3711b031f6.png)

**Comment by ArgentArts** [comment]
Awesome! Thanks!
