### ISSUE TITLE
Glare issue, New Build 17-02-22

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2174]
Glare issue since yesterdays update on dark levels.
Its every time you launch and if just touch any Sky \ sun setting it instantly reverts to normal however it does not retain the settings and crops up again whilst playing the level and its a rinse, repeat to get it back to normal.

See attached Vid 

https://youtu.be/DauqiDwoqJA

**Comment by LeeBamberTGC** [comment]
@dllllllllllb One for you to investigate. What setting gets updated when you adjust the sun intensity during the test level session?

**Comment by ZakJudges** [comment]
Hi @synchromesh62, is this issue now fixed for you? Thanks :)
