### ISSUE TITLE
Cancel loses your work  ( Nasty one )

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2179]
So you spend hours sculpting your terrain and decide its time to save but for some reason you accidently click **New Level** 
No problem click **Cancel** 
It kind of is because you lose the lot.
**Video below** 
https://youtu.be/YSL4lTfx738

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this issue, and yes it was a nasty one, it has been fixed and committed, but not sure if @LeeBamberTGC merge anymore for the Friday build ?.

**Comment by LeeBamberTGC** [comment]
@plemsoft I froze commits to last night for the build we are testing this morning. I am however starting the internal build for next week, so it will be in that one :)
