### ISSUE TITLE
Feature Request: Lua command to control intensity and range of lighting

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#218]
We can turn them on and off right now.
But would be better for flickering lights if we could control the range and intensity in LUA.

**Comment by tarkus1971** [comment]
Be nice to be able to use Lua to move the lights too in realtime.

**Comment by AmenMoses** [comment]
This is already in my local repository, I'll try and push it to GitHub later today.

**Comment by tarkus1971** [comment]
That's great AmenMoses, also when will the other physics stuff you have done be added, I can pick up, drop but as yet not throw entities.

**Comment by Pirate-Myke** [comment]
Thank you.

**Comment by Pirate-Myke** [comment]
This enhancement should be closed. This was added in April of last year.
Thank you.
