### ISSUE TITLE
GG Max Bug Report - 2 errors with Crash when canceling the save of a objects group

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2180]
1/ Place 2 objects on the map.
2/ Select both elements to group them
3/ Click on "Group Objects"
4/ Click on Save Group
5/ Name the group and validate with ENTER
6/ When the "Object Library Preview" window appears, click on **Back To Importer** (small triangular icon located at the top left of the window), as if to cancel your save and go back to the map editor.
![ObjectLibraryPreview](https://user-images.githubusercontent.com/96718175/154620982-aa6135aa-6048-4472-bdc0-aa30c3c99193.png)
Result : 2 error messages followed by a crash.
Operation performed 3 times. Systemic crash.
Screens :
![error1](https://user-images.githubusercontent.com/96718175/154620302-23829657-dd33-4004-a98a-26acca8b0469.png)
![error2](https://user-images.githubusercontent.com/96718175/154620310-5f99c4e7-de19-431c-a9d4-cb9dbf685eb0.png)
Moreover, if the save concerns a group containing a Light (directional or standard), the group is unable to restore the parameters of the light (Color, Light Distance, SpotlightRadius, LightProbeScale, etc...). Instead of my settings, Max renders a standard light with its initial settings.

Note that after the crash, the group is stored in the entitybank\user files with an .fpe file, but this group does not exist in the map ("Group" tab).

I hope it can help.

**Comment by ZakJudges** [comment]
@UltraVox001 Thanks for reporting this issue. A fix should appear in the build later today :)
