### ISSUE TITLE
Old Grouping Tutorial video

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2181]
@LeeBamberTGC The grouping video has not been updated with the latest version.

**Comment by LeeBamberTGC** [comment]
@rvanner Can you confirm the size of the file is: 153 MB (160,447,483 bytes)

**Comment by rvanner** [comment]
@LeeBamberTGC The new version is now uploaded to Google Drive, grab it and replace this older version.

**Comment by LeeBamberTGC** [comment]
Will be in Friday build.
