### ISSUE TITLE
GameGuru MAX (alpha 2022-02-04 and previous versions) : Bug with the Scale Tool (Object Tools)

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#2185]
Hello,

This is an old bug that I am reporting again for a better visibility in this new thread.

The Scale Tool doesn't show the correct scale after it was applied on an item.

Here is the link to a short video showing the process to reproduce that bug : [https://vimeo.com/679061663](url)

And here is a commented screen capture showing the result of that bug :  

![wrong_scale](https://user-images.githubusercontent.com/94678034/154658926-ba188d87-927d-4a4d-918d-4c0800d138b3.jpg)

**Comment by dllllllllllb** [comment]
@marcuswilm Hi, I can't seem to open the link to your video, it leads to the issues board: https://github.com/TheGameCreators/GameGuruRepo/issues/url

**Comment by ArgentArts** [comment]
Here's his correct link:

https://vimeo.com/679061663

**Comment by LeeBamberTGC** [comment]
@dllllllllllb @ZakJudges @PaulSJ @plemsoft  If you have any SCALE RELATED issues, please assign them to be and I will tackle them all in one go. There is some confusion on how the current system works and it is not 100% intuitive, so want to look at this a fresh with all issues in one place :)

**Comment by plemsoft** [comment]
@LeeBamberTGC FYI: https://github.com/TheGameCreators/GameGuruRepo/issues/1745

**Comment by LeeBamberTGC** [comment]
New scaling behavior in EXP build on Steam later this evening.  Renamed Scale to 'Scale Multiplier Percentage' and now reflects the actual scale of the object from its FPE properties for consistency.  Slider is reset when go to new object to have a good range of scaling (one percent through to 10x), which may be repeated, or scale entered manually.

![image](https://user-images.githubusercontent.com/35840583/164537434-f06cd774-5e0d-46db-9cd2-c4dafe86a2b9.png)

**Comment by marcuswilm** [comment]
@LeeBamberTGC thank you for this good news. I am not working with the Steam build. Please, will the next update of the alpha version for TGC members also been updated with that fixed and revised setting ?

I also would like to know if the collision shape of a rescaled asset in the editor could also be rescaled with that setting.

Anyway as always congratulations to you and to the GG MAX developers' team. GameGuru MAX is growing nicely.

**Comment by ArgentArts** [comment]
@LeeBamberTGC Instead of having four scale bars (one for all three axis and one for X, Y, and Z), why not just have three (X, Y, and Z) and have a LOCK icon that would lock the scale of all three. When locked, you use only one to adjust all three. When unlocked, you adjust all three individually.

**Comment by LeeBamberTGC** [comment]
@ArgentArts I like the lock idea, and also the fact we clean up the UI a little too :)  Physics does scale when the scaling tool is used, no worries.

**Comment by LeeBamberTGC** [comment]
P.S. This build will be released this Friday evening :)

**Comment by ArgentArts** [comment]
@LeeBamberTGC Glad you like the idea. It brings things in line with standards that are seen in most programs, too, I think.

**Comment by marcuswilm** [comment]
@LeeBamberTGC  A successful test with the collisions on rescaled assets : https://vimeo.com/703896483 (49 seconds - 68 MBytes - HD - no sound). 

Thanks for watching.

:)

**Comment by LeeBamberTGC** [comment]
Good stuff!
