### ISSUE TITLE
UI - Water fog minimum can be only set to either 0 or 100

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2189]
"Water fog minimum" in the water advanced settings tab can be only set to either 0 or 100

**Comment by ZakJudges** [comment]
@dllllllllllb I wasn't able to reproduce this one. Are you still experiencing it in the latest build? :)

**Comment by dllllllllllb** [comment]
@ZakJudges Works fine in the current build :]
