### ISSUE TITLE
Storyboard Editor: Add the Terrain Generator to the tutorial list in this section

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2194]
In the Storyboard Editor, show both the Storyboard Editor and the Terrain Generator Tutorials in this screen.

![image](https://user-images.githubusercontent.com/1503593/154686490-1c317e8f-54f5-413e-a14b-05a7fb661661.png)

**Comment by ZakJudges** [comment]
Fixed in latest build. Closing
