### ISSUE TITLE
Able to highlight objects whilst hovering UI

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2195]
In this example, my cursor was hovering where the red x is, but the object was still highlighted. 

![Screenshot 2022-02-18 155951](https://user-images.githubusercontent.com/32545391/154717555-c6321951-09a4-44bc-8b32-e26c160a7fe7.png)

**Comment by Skevos-Mavros** [comment]
It's also possible to paint terrain and spray trees from there too.  :-/

**Comment by ZakJudges** [comment]
Hi @Skevos-Mavros, the issue of being able to paint terrain and trees should have been fixed in the latest build. Could you confirm if you still experience it after updating? :)

**Comment by Skevos-Mavros** [comment]
> Hi @Skevos-Mavros, the issue of being able to paint terrain and trees should have been fixed in the latest build. Could you confirm if you still experience it after updating? :)

Oops!  Yes, this seems to be fixed in the current version.  My bad!  Thanks!

**Comment by Skevos-Mavros** [comment]
Oops (again).  When I said this was fixed, I was referring to my comment about painting terrain and trees from outside the 3D view.

The original bug report by @ZakJudges  that OBJECTS highlight when the mouse hovers outside the 3D view, is still happening.

Sorry if my reply was unclear.  How does one unclose an Issue?

**Comment by ZakJudges** [comment]
@Skevos-Mavros I have added a fix for the objects being highlighted when the mouse isn't hovering the viewport :) Should be in this Friday's build

**Comment by Skevos-Mavros** [comment]
Sorry I'm so late getting back here.  Yes, this seems to be fixed.  Thanks!  But I don't have the option to comment and close on this one.

**Comment by ZakJudges** [comment]
Great, thank you for confirming. Closing this issue
