### ISSUE TITLE
Sometimes Test Mode crashes when editing settings tab

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#22]
After several sessions, when entering the setting tab (TAB TAB), GameGuru crashes with a hard crash

**Comment by Teabone3** [comment]
Wonder if this is related to #50 ?

**Comment by plemsoft** [comment]
Believe i fixed this , need someone to confirm , if you got this problem sent me a email plemsoft@plemsoft.com and i will sent you some new .exe files for testing. thanks for your help :)

**Comment by plemsoft** [comment]
Fixed in latest branch.
