### ISSUE TITLE
Light Mapped PBR objects loose environment reflection

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#220]
Using PBR assets, after lightmapping the objects loose there reflections of the environment.

PBR objects real time lighting.
https://puu.sh/Ad19D/88c39068a1.jpg

PBR objects after F3 light mapping, and level saved and reloaded.
https://puu.sh/Ad1hE/8e7a950f65.jpg

**Comment by plemsoft** [comment]
@Pirate-Myke Thanks for reporting this,

Could you test this in the latest version and let me know if this has been fixed , thanks :)

**Comment by Pirate-Myke** [comment]
2019.06.24 - June Update BETA
https://puu.sh/DKrFh/722fc9310f.jpg
Red light is static, yellow dynamic.

https://puu.sh/DKrEl/5baa079201.jpg
Terrain is jungle, Sky is custom

Light mapped results no extra custom cube map.
https://puu.sh/DKrDx/e5e103ae5e.jpg
https://puu.sh/DKrDk/810553620d.jpg
https://puu.sh/DKrCn/527c5e7494.jpg
https://puu.sh/DKrBV/9c23246538.jpg

Custom cube map:
https://puu.sh/DKr99/10ab644f90.jpg
https://puu.sh/DKr9D/6840703bbf.jpg

153 pieces with this model at 60K polys. Moves position after light mapping. But I am asking a lot from the engine here. Player camera has not moved from these 2 images.
https://puu.sh/DKrjJ/466bac6127.jpg
https://puu.sh/DKrk2/2a1cc2e03c.jpg

But for this issue, It now functions for me. Thank you.

**Comment by LeeBamberTGC** [comment]
@Pirate-Myke Any chance you can provide an FPM that uses stock assets to show the last issue you refer to, thanks!
