### ISSUE TITLE
Flat areas can move in test game

### ISSUE THREAD

**Issue by PaulSJ** [TheGameCreators/GameGuruRepo#2201]
If an object that has a flat area is set as a dynamic object then when it moves it also moves its flat area causing performance issues.

**Comment by LeeBamberTGC** [comment]
@PaulSJ Is this still an issue?

**Comment by PaulSJ** [comment]
Yes. It's a bit of a contrived case since buildings shouldn't be dynamic, but it is something that users are able to do. I think the best solution would be to turn off flat area updates once in test game or standalone mode. An alternative solution would be to disable flat areas for dynamic objects entirely.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Add some code which DISABLES the autoflatten if the object is not static

**Comment by dllllllllllb** [comment]
@LeeBamberTGC The changes I made in #2191 fixed this. I made a dynamic warehouse , placed it on a corner and when I run test game / standalone it doesn't autoflatten the terrain as the warehouse falls.
