### ISSUE TITLE
Shadows Flickering 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2204]
Shadows Flickering like crazy in newest update. Possibly related to #2203

https://www.youtube.com/watch?v=J_6GyGt2y-U

**Comment by plemsoft** [comment]
@Kitakazi Yes you need a few more casters , in shadow setup , select the number of casters for point and spot light, just increase them a bit :)

**Comment by Kitakazi** [comment]
Ah ok, that did indeed fix it. Thanks
