### ISSUE TITLE
GG Max inconsistent Nav Mesh

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2205]
Nav mesh fault.
FYI, no Character (ally, enemy, zombie), no animal, no Flag on this test map.
The Nav Mesh is calculated for whom, or what ?
![NavMesh01](https://user-images.githubusercontent.com/96718175/154794370-dc450d71-fe79-4ebd-81aa-68868c275252.jpg)
Max update this morning around 9am.

**Comment by rvanner** [comment]
Don't worry about the navmesh, we are looking to add a much quicker solution.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Many nav mesh improvements since this post, should be fine now.
