### ISSUE TITLE
GG Max - Auto Flatten Terrain Under Large Objects : Non-storable option

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2207]
Once this box is unchecked in the Settings, it must be unchecked each time you reopen Max.
However, the other boxes in "Advanced" and "Developer" are memorized.

I wish this one was too. :)
![autoflatten](https://user-images.githubusercontent.com/96718175/154798358-15e86f85-5da4-4afc-9d8b-12b5473ffa4c.png)

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue, this has been fixed and will be in the next update :)
