### ISSUE TITLE
GG Max Bug Report - All biomes are broken in Terrain Builder

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2208]
Here is a screen of each biome that Max offers me by default. I didn't touch anything.
I restarted Max. Same problem.
Rainforest :
![RF](https://user-images.githubusercontent.com/96718175/154800486-0718d8f3-d935-4923-83d0-ccdcb7c4705f.jpg)
Mountain : 
![Mountain](https://user-images.githubusercontent.com/96718175/154800505-334c105d-131b-4c92-b78d-bbe85a71c655.jpg)
Canyion : 
![canyon](https://user-images.githubusercontent.com/96718175/154800541-9e921b30-d122-4395-a1b1-79d0b7def78f.jpg)
Snow : 
![snow](https://user-images.githubusercontent.com/96718175/154800562-f2516e87-432a-4351-87b5-5803e4f94956.jpg)
Forest : 
![forest](https://user-images.githubusercontent.com/96718175/154800578-7d5d9a59-bfec-43e3-9b70-d12eba82936e.jpg)
Desert : 
![desert](https://user-images.githubusercontent.com/96718175/154800590-cca3233b-4003-43f2-ad16-5a72f0ce808e.jpg)
Plains : 
![plains](https://user-images.githubusercontent.com/96718175/154800599-6780a5a8-3476-4e9a-a101-060a15bf2a37.jpg)

**Comment by LeeBamberTGC** [comment]
New internal build includes necessary files as of 15 minutes from this message :)

**Comment by UltraVox001** [comment]
It's ok now. Thank you. :)
