### ISSUE TITLE
Light Mapping does not include Emissive

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#221]
I don't think the emissive textures are being included in light map data 
https://youtu.be/VMJYCIJgJ5g

**Comment by Pirate-Myke** [comment]
Emmisive, detail, and reflectivity. Also smoothing groups on some models.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GraPhiX-Guru** [comment]
not sure if this is possible but if you are fixing the lightmapper would it be possible to make the emissive maps cast light rather than emulate it? much like a dynamic light but with limited range, I have noticed that I have to add dynamic or static lights to me emissive model for it to cast any light in DX9 I did not have to do that.

**Comment by BodRH** [comment]
Does the model not have to be dynamic for emissive to work ?

**Comment by BodRH** [comment]
I have only ever got it to work when the model is dynamic if using lightmapping, for me when lightmapping static models the emissive or earlier _I textures always disappeared.

**Comment by Pirate-Myke** [comment]
I will retest my objects again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GraPhiX-Guru** [comment]
ooohhh thanks Bod will check that ;)

**Comment by Pirate-Myke** [comment]
Mine work for PBR in static mode.
My textures are labeled texture_illumination.dds they are in DXT1 compression.
https://puu.sh/AdyUk/f5af7bbb5e.jpg

I also have dynamic and static lights in this.

**Comment by Pirate-Myke** [comment]
More PBR Testing without static or dynamic lights using F3 light mapper.
Illluminations seems fine with the apbr_illum.fx shader.
The rest with the apbr_basic shader with detail maps, loose reflections and detail map.
https://puu.sh/AdDlf/e57dc4540a.jpg
https://puu.sh/AdDjO/0c4da78ab1.jpg
https://puu.sh/AdD5d/033f14290c.jpg

Real Time light.
https://puu.sh/AdD5S/9be7c444f8.jpg
Baked Light.
https://puu.sh/AdDlY/2bb89ec60b.jpg

Real time light.
https://puu.sh/AdD4M/2f78fce4fb.jpg
Baked Light.
https://puu.sh/AdDmp/d6f88c7881.jpg

**Comment by GraPhiX-Guru** [comment]
I tried setting the tubes to dynamic I'm afraid that did not work sorry Bod :( what I have done is removed GG cleaned my registry re installed GG updated my NVidia drivers to the latest game ready and now it works :) for all my emissive textures. the tube on the far left as no emissive and you can clearly see it has been lightmapped https://youtu.be/QqKfss6k9so still could do with some light being cast from the emissive assets though ;)

**Comment by GraPhiX-Guru** [comment]
There is something wrong with lightmapping for sure https://forum.game-guru.com/thread/219745#msg2601458
