### ISSUE TITLE
GG Max Bug Report - 7 (not 10) lights connected to a Switch

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2211]
I had already posted something about this problem and thought it was solved.
I can connect 7 objects (6 lights + 1 door) to a Switch, but nothing else.
The limit is supposed to be 10.
Watch the video : [https://www.youtube.com/watch?v=jRk3UCwPybA](https://www.youtube.com/watch?v=jRk3UCwPybA)
Sorry for the lag, but when I stream I lose a lot of FPS.
I think that a test carried out on an empty map is worthless. My map contains a whole military base.
It is under these conditions that we really test things :)

**Comment by synchromesh62** [comment]
Just tried it and got 10 lights. 
I will try a few combinations 

![T1](https://user-images.githubusercontent.com/35708217/154820809-ddd4f392-29d5-48e4-a71f-216a46a6b51e.png)

![T2](https://user-images.githubusercontent.com/35708217/154820811-db47e6b8-930c-45ef-bfcf-ad187b014cef.png)

**Comment by UltraVox001** [comment]
I understand where the bug comes from.

If you're using a Switch that you copy-pasted from another Switch, you'll get this bug. And my switch had been copied and pasted from another. With a new switch, everything is fine. I can connect 10 sources.

There is therefore a bug, since Max does not consider the switches obtained by a copy/paste in the same way, compared to those obtained via the Add Light button.

To reproduce this bug, drop a switch on a wall (obtained in a normal way) and connect 10 lights to it. Then copy/paste that switch somewhere else, then try connecting 10 lights to it.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb One to reproduce and then trace the code to see why only 6 connections allowed. As reported, you should be able to make up to 10 connections.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Copying an object also copied its object relation data which made connecting lights to a copied switch impossible in my case, resetting this data fixed it for me and I can attach 10 lights to a copied switch. 

I found the code where the switch is copied using Ctrl+C / Ctrl+V but I can't find the same code for when the switch is dragged from the bottom left corner.

Here are the vars I'm resetting:
![image](https://user-images.githubusercontent.com/61796872/155514334-5544ceb6-e905-4a7d-b315-a446cfb36ae1.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb It was the right play to wipe out the relational data.  Always when pasting or dragging in a new object, the engine must use the addentitytomap so make sure all calls to this pass through code that will reset the above data of any duplicated object.  Dropping in a breakpoint to the addition of the object will allow you to trace back to who created that object.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC From what I understand, when you drag an entity from the bottom left section, it doesn't actually make a new entity until it is placed on the map. I think that drag and drop shares a lot of the code with map editing code, so all the code related to dragging in a new entity that triggered my breakpoint is also used when moving an already existing entities. 

I can't reset visual logic relations there, as simply clicking on an object will reset these relations.

Maybe I just weren't able to find it. I followed gridedit_addentitytomap() to see where it is called and tested all areas that triggered my breakpoints, but they always resulted in resetting relations after selecting an entity.

Maybe there is a bool that's set to true when a new entity is being dragged?

**Comment by LeeBamberTGC** [comment]
@dllllllllllb No worries, assign it to me as I have some familiarity with the object placement system. I have assigned a few new issues for you this week so plenty for you to get stuck into :)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb As you summised, you located the addentitytomap function which will create the duplicated object. You will also know it is the t.grideleprof structure that stores the object properties for the copy:

![image](https://user-images.githubusercontent.com/35840583/156211332-1a259f70-1093-417a-93d2-4289021c2558.png)

So you are looking foir code which populates "t.grideleprof"from the object being duplicated, which when you search through all usages for a possible "t.grideleprof =" you find five sites where this is assigned. Adding a break point at each one and repeating the duplication shows you which copy was responsible.  Also, three of the five found are duplication events, and so wiping out the data for these will fix further related issues:

Creating a nice clear function we can re-use is step one:

#ifdef WICKEDENGINE
void entity_cleargrideleprofrelationshipdata (void)
{
	// wipe out relational data when adding new object
	t.grideleprof.iObjectLinkID = 0;
	for (int i = 0; i < 10; i++)
	{
		t.grideleprof.iObjectRelationships[i] = 0;
		t.grideleprof.iObjectRelationshipsData[i] = 0;
		t.grideleprof.iObjectRelationshipsType[i] = 0;
	}
}
#endif

And then using the function when a duplication takes place:

							t.grideleprof = t.entityelement[e].eleprof;
							entity_cleargrideleprofrelationshipdata();

Hope this helps your journey  :)

I will make the changes and upload to the internal build soon so you can test and confirm the fix.

**Comment by ZakJudges** [comment]
works in latest build
