### ISSUE TITLE
Player will fall through the terrain when creating a new Empty Level

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2212]
Create a new level and select "empty" start a test game and you will fall through the terrain everytime.

**Comment by ArgentArts** [comment]
Not for me. I can create an empty and walk/run on it just fine. 
![empty](https://user-images.githubusercontent.com/36735507/154822444-22a4cfb4-5d55-44dc-b5f6-c7924541800a.png)

**Comment by synchromesh62** [comment]
> Not for me. I can create an empty and walk/run on it just fine. ![empty](https://user-images.githubusercontent.com/36735507/154822444-22a4cfb4-5d55-44dc-b5f6-c7924541800a.png)

Kitakazi is on an internal build.
@Kitakazi  Terrain physics is currently being worked on so i would not worry about it for the moment.

**Comment by Kitakazi** [comment]
K I will close this for now then
