### ISSUE TITLE
All Biomes are missing terrain textures

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2213]
![image](https://user-images.githubusercontent.com/51464873/154820127-5d9ececc-a3cc-4c65-b2ef-1d8e8ef6ff30.png)

Create a new level, all biomes are missing the terrain textures.

**Comment by synchromesh62** [comment]
That was the internal yesterday .. its been updated ?
when did you update

**Comment by ArgentArts** [comment]
Not here. I have all my terrain textures:
![ttextures](https://user-images.githubusercontent.com/36735507/154822367-5900982e-fe0c-4ea0-82fc-fc2bf3384ef1.png)

**Comment by plemsoft** [comment]
@ArgentArts Your missing the biomes setup files , just verify and they will download :)

**Comment by ArgentArts** [comment]
@plemsoft As stated, I am NOT missing them. I have ALL my terrain textures. :)

**Comment by Kitakazi** [comment]
Ye I just verified and it is fixed.
