### ISSUE TITLE
MAX - Suggestion - Update Option On Welcome Screen

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2216]
Can we perhaps have a check for updates button on the welcome screen?
- would be much easier that having to select and open a project before we can check for updates

![image](https://user-images.githubusercontent.com/12246318/154828346-f6e2100c-92b0-49a3-98c4-289556502e29.png)

**Comment by ArgentArts** [comment]
Rick suggested something similar here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2197

**Comment by OldFlak** [comment]
Thanks for considering - Using Steam so not an issue :)
