### ISSUE TITLE
GGMAX - Grass problem.

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2217]
The Grass Density setting is doing nothing??
The Grass Distance setting is also changing the Grass density??

Also Grass at the map edges should extend beyond the map edge at least the distance of the Grass distance setting for map realism instead its cut off like with a knife as shown.
![mapedge](https://user-images.githubusercontent.com/95015657/154830583-5c1571da-c5ce-44e5-b884-d00e4701957f.jpg)

**Comment by ArgentArts** [comment]
You're right, Grass Density is currently not changing anything and it should be.

Having said that, changing the Grass Distance setting changes the Grass Density, making it less dense the more distance you make it. This is the current trade-off. You want to the grass to be seen further in the distance? Then you get a less dense grass. That's been explained a few times in the live broadcasts, etc. But this entire system is still a work in progress. 

As far as the edge of the map area ... if I were you, I wouldn't want my players ever reaching the edge and bouncing against that invisible wall. So, I'd be erecting some sort of barrier, like a mountain or something, to keep them from ever reaching it. That way, they would never see that knife edge where the grass cuts off.

**Comment by Necrym59** [comment]
yes i understand the distribution that trade off a bit but at present its not working correctly but thats development for ya. As for the map edges if they implement somthing similar what i have mentioned here https://github.com/TheGameCreators/GameGuruRepo/issues/2093
then reaching a map edge could load then next sectional map, (excellent for rpg games etc.) in which case just extendg the ground vegetion to the distance setting just beyond the map edge would be an ideal nice touch and much more realistic.

**Comment by PaulSJ** [comment]
Grass denisty slider should be fixed for the next version

**Comment by Necrym59** [comment]
Fixed
