### ISSUE TITLE
GG Max -Can walk through a warehouse door after its been raised then lowered.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2218]
As the title explains, after raising then lowering a warehouse door, you and mobs can walk straight through the door.

**Comment by UltraVox001** [comment]
Problem already reported [here](https://github.com/TheGameCreators/GameGuruRepo/issues/2046) (and fixed for the next build).

**Comment by Tum1370** [comment]
@LeeBamberTGC 
This is now fixed, Closing.
