### ISSUE TITLE
GG Max - Particles not resetting when test level for second time

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2219]
On the Demo Level Switch Escape, i was testing the visual logic for the Zone to Object, And Object to Object logic that you use for the Button and Steam out of the pipes.
I changed all of the logics to toggle other object / toggle object.
I was hoping this was going to enable pressing the button to redirect the steam, and remove the hurt zone, like it is suppose to, But it was not always working like that and seems to get confused.

Is this suppose to work like this ? OR should toggle mean, toggle ?

Also, After testing the game once, The Particle Steam that comes from the 3 cylinders after pressing the button, Never reset, and they are visible at the start of the level when you play the level again.

**Comment by LeeBamberTGC** [comment]
The logic has been designed as you describe. I am keeping the BUG tag as the particle issue is a confirmed bug to be fixed.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Pressing the switch activates the particle and after leaving the test level, the particle is still activated. After deleting the particle widget, particle effect is still there. I tried changing visual logic to toggle the particles however that didn't make a difference. Then I tried replacing them, but I can't connect new particles to the switch and I can't rotate the particles so the steam goes in the right direction.

I also noticed that the particle in the other room is not rotated properly and I can't rotate it back to what it should be.
![image](https://user-images.githubusercontent.com/61796872/159017210-2732505b-ecdf-4a57-ad43-646e0bf53005.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Finish up this one and assign to me, I will take a look :)

**Comment by LeeBamberTGC** [comment]
@Tum1370 I will commit this for our internal testing :)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Was related to a bug in the switch escape level, try with today build.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Just tested the Switch Escape demo and same thing. The steam was still coming out the 3 cylinders on the 2nd time, before even pressing the switch.
They do not reset.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Defo fixed this time :)  Watch out for Fridays release.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Sorry Lee but i have just tested this demo again on the latest Experimental build, and this was my second playthrough.
You can see the steam coming from the 3 containers, even before i press the button.

![Untitled](https://user-images.githubusercontent.com/66874403/174300173-bcd199f2-9abe-409c-bad0-405546650365.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Are you using the Steam or the non-Steam version?

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you send me the FPM called "switch escape.fpm" from your "GameGuruApps\GameGuruMAX\Files\mapbank" folder. The particles will not reset if you are on the older map that we used before.  I can compare yours with the one I have..

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Just tested this demo map again, by deleting my whole save folder and letting Max rewrite it.
Yes the latest version of Switch Escape is now resetting in the editor when i test it after the first time.

I guess this is because even though Max updates regular, It does not update the demo maps in the My Documents folder, where all our own projects are.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for confirming :)
