### ISSUE TITLE
EBE Building - Lighting Problems / shader problem ?

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#222]
Somehow I have this problem since yesterday. I dont know what cause it. Even building an enitre EBE building again from scratch didnt work!

Please.. have a look. I tried everything now, maybe you have an idea? 
https://www.youtube.com/watch?v=6PVILgpT4wI&feature=youtu.be

**Comment by LeeBamberTGC** [comment]
It looks like an issue that has since been fixed with recent changes to the PBR shader.  If you can provide an FPM that uses stock assets, we can determine the case.

**Comment by Duchenkuke** [comment]
I uninstalled gameguru half year ago, I cant provide any files.
