### ISSUE TITLE
Fringing on backlit trees against simulated clouds

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2220]
For several versions I've been noticing a distracting fringing around the edges of trees, especially when backlit against a simulated sky.  It's most obvious when the leaves are against clouds that are significantly different in colour from the sky behind those clouds, but it is there more subtly all the time - it's as if the edges of the leaves are being blended with the colour of the sky, regardless of the colour of the clouds (that's just a guess).  The image attached shows the effect at its most pronounced.

Thanks!

![GGM Fringing 2022-02-21a](https://user-images.githubusercontent.com/56815299/154867536-814e2f09-401d-4823-92c3-b6b71fff4b93.jpg)

**Comment by dllllllllllb** [comment]
Probably related to #2193
