### ISSUE TITLE
Sun Rays still not QUITE lined up with the sun

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2221]
A while back (https://github.com/TheGameCreators/GameGuruRepo/issues/1865) it was reported that sun rays weren't originating from the sun disk, and the issue was reported as fixed, but on my system the issue was greatly improved but it's still not quite right.  See attached image.

Thanks!

![GGM Sun Rays 2022-02-21a](https://user-images.githubusercontent.com/56815299/154867687-edf47973-1719-41f1-92da-30c0757a9b22.jpg)

**Comment by LeeBamberTGC** [comment]
@Skevos-Mavros Since fixed many moons (and suns) ago, now rays originate from actual sun location in sky:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/87bbb5a9-7ec4-4577-bc6c-b9eebdcaf762)
