### ISSUE TITLE
Unexpected Behaviour from "Grass Draw Distance" slider at low values.

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2227]
On the current version (2022.02.18) the "Grass Draw Distance" slider gives odd results at low values (see video).

https://youtu.be/9420Q67O-90

As I slide the slider to the left, results are as expected at first - grass appears denser as the draw distance gets closer.  But at low values the grass becomes segmented into squares that "pop" in and out of vision as I move towards and away from the surface.  Then at very low levels the grass vanishes altogether, regardless of view distance.

Thanks!!

**Comment by rvanner** [comment]
@plemsoft As we discussed, these sliders seem to be reversed;
![image](https://user-images.githubusercontent.com/1503593/155127429-8f1e11d0-0847-4a1f-8780-1612c4a4321c.png)

**Comment by plemsoft** [comment]
@Skevos-Mavros Thanks for reporting this issue , yes it need a little distance before it can fade from one chunk to another , i set this limit so you cant go below 2 chunks so its possible to fade :)

@rvanner @[rvanner](https://github.com/rvanner) , i remember we fixed that issue in a TW , and is not related to the original issue :)

**Comment by Skevos-Mavros** [comment]
Yes, this issue seems to be fixed.  Thanks!
