### ISSUE TITLE
export issues. 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2228]
Export report.

Trigger zones moving/not working at all.
(the most annoying EXAMPLE is the exit marker moving meaning you can’t complete a level)

Animations do not work with custom assets, IE if some one is dancing. Just stood frozen. 

Zombiiii attack caused the entire game to freeze, the level kept running and the zombie dies, was stood their frozen. Had to do a restart. 

Weapons do not transfer to next level. Start unarmed on each level. Multiple characters causes drastic slow down.

Weapon un-equips when attacked by zombie, biting animation bugs out.  

Ally weapons killing player.

Enemy characters walking through walls!?! Ahhh!

Runtime error 7007 randomly. Then its stops. Then it runs the standalone, then it randomly happens again.

Loading a saved game loads a completely broken level, all the triggers have are turned off (very much like gg classic)

DEATH. When you die, the level doesn’t restart, the game ends which is realllllly dumb, imagine playing a multi level game, and you get to levell 4 and you die and you have to restart? Well you can’t load your saved game because it loads a broken mess. 

Loaded into a level, fell through the ground and into the water, then death.

Did manage to get 4 levels in, the issues with the things moving and trigger zones not where they should be where rectified by editing the exported map, which fixed the issues. At level 4 stability began to break down and collisions changing.

Collisions set as polygon have changed to boxes in the export.

AND that’s it for now!!! OFF too bed.

**Comment by ZakJudges** [comment]
Hi @casigus, I wasn't able to reproduce any of the crashes, or the trigger zones moving/disappearing when loading a standalone game. Are you still experiencing those in the latest build? 

For the other bugs, would you be able to create new issues for those, with steps to reproduce? Having one bug per issue helps us organise and assign the tasks better :)

**Comment by casigus** [comment]
ive yet to export a standalone so i can't confirm till I do.

**Comment by ZakJudges** [comment]
Hi @casigus, I believe that most of the issues listed should now be resolved. Could you confirm if this is the case? For any that are not, we can create new issues for them so they are easier to track :)

**Comment by casigus** [comment]
animations don't export with custom assets last time I checked, but alot has been fixed.

**Comment by ZakJudges** [comment]
@casigus Thank you for confirming. Would you be able to send me a model that shows the problem and I can create a new issue from it? :)
My email address is zak@thegamecreators.com

**Comment by casigus** [comment]
yeah let me find one !

________________________________

**Comment by casigus** [comment]
yayyyyyyyyyyyyyyyyy. :D !!
