### ISSUE TITLE
Choosing Delete Mode in Vegetation also changes the Texture Mode to Restore Mode

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2230]
Choosing Delete Mode in Vegetation also changes the Texture Mode to Restore Mode.
The reverse also happens.
See the Video : [https://www.youtube.com/watch?v=LHYEARcuL9k](https://www.youtube.com/watch?v=LHYEARcuL9k)

**Comment by plemsoft** [comment]
@UltraVox001 Thanks for reporting this issue , this has been fixed and will be in the next update :)
