### ISSUE TITLE
Terrain Generator

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2232]
@plemsoft Here are the tweaks for the terrain gen when the sky changes to a sky box:

![image](https://user-images.githubusercontent.com/1503593/155127120-503830d2-46f4-4eea-8b46-6c18fc61069a.png)

Also make sure that when the user first clicks on any of the biomes they don't get a night scene as the first choice.

**Comment by plemsoft** [comment]
@rvanner Fixed for the next update :)
