### ISSUE TITLE
Show this in a message box over the Storyboard screen and then flip to the terrain gen

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2233]
To avoid an ugly black back ground. Show this in a message box over the Storyboard screen and then flip to the terrain gen.

![image](https://user-images.githubusercontent.com/1503593/155127634-3ca1c5d3-6c3a-410b-b63c-1e703891d23b.png)

**Comment by plemsoft** [comment]
@rvanner Fixed for the next update :)
