### ISSUE TITLE
Mesh falling from the sky in test mode - GGMax_2022_02_25 [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#2234]
First of all, this is just a report. since you are working on terrain physics right now, it might help as a clue.
Label it as your criteria. :)

My mesh (a house) in the editor

![cellar_building_isImmobile_GGMax_2022_02_25_pic01](https://user-images.githubusercontent.com/47690174/155149789-34a40ace-2560-4a41-9b72-c717d06ba37b.png)

**Notice "IsImmobile" tickbox is checked.**
Obviously, it has nothing to do with mesh as you can see in the video below.

In test mode

https://youtu.be/5b7BJqbC6Wo

**Comment by LeeBamberTGC** [comment]
@3coms Any chance you reproduce this bug with stock media and a small FPM level we can load in at this end?

**Comment by 3coms** [comment]
> @3coms Any chance you reproduce this bug with stock media and a small FPM level we can load in at this end?

I had tried today in the very latest build and it no longer happens, which is very good news. :)
I had tried the X and DBO imported files, and both work as expected; although they are the same meshes in the above video.
https://youtu.be/yObIHpwXFBc

So, I'm going to close the thread as fixed. :)
