### ISSUE TITLE
Red dot sights obstructed by objects

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2236]
In these screenshots, you can see the enemies' hands cover the red dot. Happens when you get close to objects.
![Screenshot 2022-02-22 154509](https://user-images.githubusercontent.com/32545391/155168175-62af0ec5-a83e-4b32-82c4-a34244115f61.png)
![Screenshot 2022-02-22 154530](https://user-images.githubusercontent.com/32545391/155168186-e967843e-3568-4c4c-a938-e9f28fc7ace9.png)

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I tried playing with Z depth render but I couldn't get it to work properly. It's like the red dot is separate from the gun since the Z Depth is already disabled on the gun. 

What we could do is get rid of the red dot and replace it with in game crosshair like we did with the Patrol Rifle. We would first need to get the Patrol Rifle crosshair to match the movement of the gun.

**Comment by LeeBamberTGC** [comment]
@ZakJudges Is this still happening, we now have a cross hair feature :)

**Comment by ZakJudges** [comment]
@LeeBamberTGC This still happens to the "Compact Assault Rifle" which has the old red dot sight.

The new red dot has some positioning issues:
![2022-04-21 13-14-03_Moment](https://user-images.githubusercontent.com/32545391/164456682-62d2857a-a4d4-4d71-83ef-6c60ba91581f.jpg)
This doesn't happen to the old red dot sight because it is rendered behind the gun, whereas the new one is on top.

In my opinion, the red dot sight should remain unchanged and the original issue should be fixed, rather than switching to the cross hair. I'm all for having a crosshair when not zoomed in, but I think the original red dot sight looked far superior. Here it is for comparison:
![Screenshot 2022-04-21 131752](https://user-images.githubusercontent.com/32545391/164456764-8ff40523-6fe5-4670-82b7-2006a42ca52f.png)

**Comment by LeeBamberTGC** [comment]
@ZakJudges As this needs remodelling of the weapon (which we do not have access to right now), I have removed the laser sight to at least resolve this bug in another way. Once the new weapon system is live, we can correct and improve laser guides for all weapons, and give the user the option to switch them on and off.

**Comment by LeeBamberTGC** [comment]
@ZakJudges Will be in this evenings EXP build.
