### ISSUE TITLE
Auto flatten areas are not cleared if you don't save your changes and it affects other levels

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2238]
- I added some buildings to a level

- I quit back to the Storyboard and did not save the changes I had made

- I went into a plains based level and found these showing up:

![image](https://user-images.githubusercontent.com/1503593/155177920-5f85d3af-7d2e-4c97-b774-655f23355ffb.png)

- I then went back to the level where I had added the buildings and the auto flatten areas were still showing

![image](https://user-images.githubusercontent.com/1503593/155178076-2aad9418-7831-4a7c-8b4e-aec7c3f42007.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Nice one for you. Find out how the flattened areas are created and removed for objects that are flagged to use them, then determine why flatten events remain when a level is abandoned and a new one started. All flatten IDs must be deleted if a new level is required.
