### ISSUE TITLE
MAX - 2022.02.25 - Editor - Can Not Remove References

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2241]
This is not a new issue. You cannot delete unwanted references. 
Once you assign an emissive texture when importing the model you cannot remove it. You have to abort the import and start again.

Does the same in editor as well: 
https://youtu.be/8hv5x4tULR4

**Comment by ArgentArts** [comment]
Looks like they really need to add a DELETE button to those. Ugh. 

I've also run across where my emission settings are not updating after a save if I update them after importing. But I want to test some more before reporting.
