### ISSUE TITLE
MAX - 2022.02.25 - Editor Rogue Entries

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2243]
Editor still has a tendency to put rogue entries in text fields. 
It seems to happen when selecting items that have Dynamic LUA scripts assigned - always places rogue entry in last sound slot

https://youtu.be/cUtjtjMaWCk

**Comment by LeeBamberTGC** [comment]
@plemsoft May need to hide sound 4 if it's the same string that DLUA uses for parameter storage.

**Comment by plemsoft** [comment]
@OldFlak Fixed for next update :)

**Comment by OldFlak** [comment]
@plemsoft Hi Preben - not seeing this issue in today's build - looks like you nailed it :)

**Comment by OldFlak** [comment]
@plemsoft Hi Preben - Just noticed sound slot 4 is missing - surely you didn't take the hide issue approach!

So this is not fixed - but a work-around?
