### ISSUE TITLE
MAX - 2022.02.25 - Editor - Incorrect Scale Values

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2244]
Editor returns incorrect X, Y, and Z scale values.

This has been there since before Lee started working on the Smart Placement stuff

https://youtu.be/GAWTQnnq-30

**Comment by LeeBamberTGC** [comment]
Fixed for next EXP build on Steam. Values reflect actual scale from FPE and better scale multiplier slider.

**Comment by OldFlak** [comment]
Hi Lee - no not fixed in current steam version
In this pic (stock asset) note the scale vales, and also the position value
-All Scale settings should be 100
-With position: tis at 0.1, some models come in at -0.1 - should be 0?

![image](https://user-images.githubusercontent.com/12246318/164959988-dae6f289-ef32-49e2-bee5-2f6aa109fef4.png)

**Comment by LeeBamberTGC** [comment]
@OldFlak Fixed issue of inaccuracy when placing in an EMPTY scene keeps to Y position zero now for accurate placement of objects. Also fixed the scale issue not reporting 100 for XYZ, which will be in the next EXP build on Steam.

**Comment by OldFlak** [comment]
@LeeBamberTGC YES! fixed great work :)
Thanks Lee for persevering with this issue - much appreciated :)
