### ISSUE TITLE
MAX - 2022.02.25 - Editor - Properties Tabs Will Not Expand

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2245]
This one seems a little random. Sometimes it decides not to expand Materials Tab.

https://youtu.be/sI9ItapEwJY

**Comment by ZakJudges** [comment]
Hi @OldFlak, I wasn't able to reproduce this issue but I've added a fix which should sort it. Could you let me know if you still experience the issue in Friday's build? :)

**Comment by OldFlak** [comment]
@ZakJudges thanks for looking into this Zac - not seeing it in current Steam build.
Will close - and let you know if it pops up again :)
