### ISSUE TITLE
Enemies can climb steep slopes

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2247]
https://www.youtube.com/watch?v=I-hbTMpBNSw

In the video, the enemy was able to climb a very steep slope then proceeded to run away into the distance.

The map that showcases the issue is attached.
[aitest.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8125378/aitest.zip)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Thanks for the map. We do have an improved navmesh system on the way which will handle terrain details such as unclimbable slopes and underwater areas, and I suspect this issue will go away when we implement that. Leaving this for now and will re-test when we have new navmesh :)

**Comment by LeeBamberTGC** [comment]
@PaulSJ Just confirmed this is so:

![image](https://user-images.githubusercontent.com/35840583/157298157-259b9a3a-f60d-4b91-bb85-8a43d6328aeb.png)
