### ISSUE TITLE
Enemies can't hear other enemies shooting

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2248]
https://www.youtube.com/watch?v=jR0w3V0XweA
If the player stops making noise and goes out of sight of an enemy, they will go back to their initial state even when other enemies nearby are shooting at the player.

**Comment by LeeBamberTGC** [comment]
@ZakJudges At the moment the idea is that we connect characters together to form 'squad' cooperation for specific areas of your level design.  Are you recommending something more akin to 'agro' by default, so ANY character within range of a combat sound and set to an enemy of the player heads towards the gunfire and engages in combat?  I am thinking perhaps we have some kind of higher intelligence manager which limits how many enemies charge in, so half the map does not decend on the player :)

**Comment by ZakJudges** [comment]
@LeeBamberTGC In my opinion, enemies of the player should be able to hear any combat sound if they are within range. However, I think you raise a good point about half the map descending on the player. Perhaps enemies from different 'squads' have a very limited range of hearing combat from other squads? Here is a video showing a problem with the current implementation:

https://www.youtube.com/watch?v=hKRiVzP3NfI

In the video, I was able to pick off some enemies standing in a line without any of them noticing each other die. 

The last enemy was shot but not killed, and since I was out of range went back to an idle stance like nothing was wrong. I can raise a new issue if you feel its unrelated though :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges In next build, characters will respond to ANY sound, not just enemy-triggered sounds, and face the enemy when they hear that sound.  It skips an enemy verify by sight step, but makes the action faster and more convincing.
