### ISSUE TITLE
Enemies can attack you through walls

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2249]
![enemy_clipping_wall](https://user-images.githubusercontent.com/32545391/155349062-e692514b-6a05-4691-9484-5a8db64d5c8a.png)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Added code to latest build so the GETCLOSE behavior of the soldier no longer passes through walls.  If you see other ways the characters will go through walls, that is not a direct forward movement towards a point close to the player, post here.

**Comment by LeeBamberTGC** [comment]
In the next build, uploading shortly, will email.

**Comment by ZakJudges** [comment]
#2632
