### ISSUE TITLE
Game Guru Dom0 Trouble 

### ISSUE THREAD

**Issue by DarcyJane** [TheGameCreators/GameGuruRepo#225]
I just made a Dom0 in Blender 3d ..I cut out the door and windows...i add,ed texture to is on Gimp..I took the UV and textured it..saved as Domo.png...I went to blender and there it was the texture. the SPHERE looked great in blender ..the front side had the door...the windows looked great all of in on blender...the front the back the right the left the top the bottom...the bottom of the Dom0 is the floor.....Everything showed up great on blender...But when I saved it as a Dom0.x and imported it into Game Guru ...once it was imported I looked at it from the front back right left top botton..it looked great...BUT  when I seen the door ...Everything inside the Dom0 was BLACK...inside...I could not see the floor at all....Any way I saved it were it says save....and when it was ....I went to my folder and I seen the icon Dom0...that look ok....BUT...WHEN I BROUGHT IT OUT ONTO THE GROUND...AND WENT INTO PLAY TO SEE IT....I COULD SEE THE WINDOWS AND THE DOOR...BUT LOOKING THROUGHT THE DOOR AND THE WINDOWS ALL I COULD SEE IS GRASS....IT is not suppose to be grass inside the Dom0 I should see the texture of the inside walls and floor....but I do not see that....Know if I walk around it from the outside I see the back side the right side the left side all textures...But if I stand from the Front side ..I see the door ..BUT I SEE THE GRASS....LOOK AT THE PHOTO SHOT..YOU WILL SEE WHAT I AM TALKING ABOUT...YOU WILL SEE THE FRONT SIDE WERE THE DOOR IS....AND TO THE RIGHT SIDE YOU WILL SEE THE BACK SIDE OF THE Dom......I saved my file  Dom0.x    I saved my texture Dom0.png   scale size 300.000  size  .....the photo will help you..From Darcy Jane FRESTURATED 
![gameguru dom0](https://user-images.githubusercontent.com/38920655/39538677-16a434c4-4e2d-11e8-94b9-70b4a393c2e0.jpg)      i did what u said Still see Grass

**Comment by BodRH** [comment]
If the Dom0 is single skinned the back faces won't show as the normals are on the outside, like if you check "Backface culling" in Blender.

![bfc](https://user-images.githubusercontent.com/36109432/39564535-82148a36-4eac-11e8-8a1e-eca3eba599e2.png)

**Comment by DarcyJane** [comment]
Thank you I will try it Peace

**Comment by DarcyJane** [comment]
Thank you very much this will help me learn better..Peace *)

**Comment by BodRH** [comment]
When importing the model to GameGuru make sure you use polygon for collision mode and try adding forcesimpleobstacle = 3 to the .fpe.

**Comment by LeeBamberTGC** [comment]
Closing this with advice as provided.
