### ISSUE TITLE
How to set up the raising of the ammo from a third person

### ISSUE THREAD

**Issue by Shalshek** [TheGameCreators/GameGuruRepo#2253]
The December update states "Third-person players can now pick up ammo", but my character does not want to pick up ammo. How should it be configured? (GameGuru classic)
![ggg](https://user-images.githubusercontent.com/99836387/155390418-7ee88a0e-f6a7-4919-957a-a92200fbd013.png)

**Comment by plemsoft** [comment]
@Shalshek Thanks for the question, first make sure you run the latest version , then make sure that the ammo you add to the level fit the weapon of the third-person players weapon. There is no special configuration.

As you can see in this video , not all ammo count:
https://drive.google.com/file/d/13-uCQGAr7HSugpyXKH4LTu7xA858_Lkw/view?usp=sharing

Hope this helps :)
