### ISSUE TITLE
GG Max Bug Report - All ground textures now only play one unique sound

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2254]
Video test with last internal build : [https://www.youtube.com/watch?v=nHhSRI_M4dE](https://www.youtube.com/watch?v=nHhSRI_M4dE)
I hope it can help.

**Comment by PaulSJ** [comment]
Although I did the terrain texture system, Lee does the sounds

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Fixed in this weeks internal build.

**Comment by UltraVox001** [comment]
It's ok now. :)
