### ISSUE TITLE
GG Max Bug Report - Animated objects are inanimate in Standalone

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2255]
Animated objects are inanimate in the Standalone version.
But they are properly animated in the Editor and in the TestLevel.
Whether the Physics is active or not, does not change anything.
Whether the IsImmobile box is active or not, does not change anything.
Editor video : [https://www.youtube.com/watch?v=BbuSjPWSFjY](https://www.youtube.com/watch?v=BbuSjPWSFjY) (the turbines are rotating)
Standalone video : [https://www.youtube.com/watch?v=fq34wX2CHLs](https://www.youtube.com/watch?v=fq34wX2CHLs) (the turbines are stationary)
Did I forget something ?
I hope it can help.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you confirm this in the latest build, this way you can confirm the fix when it is done?  Maybe prepare a VERY SMALL FPM file with the single object that exhibits the behavior.

**Comment by ZakJudges** [comment]
Hi @UltraVox001, would you be able to send me the model you are seeing the issue with? That will allow me to reproduce this and hopefully find a fix :) My email address is zak@thegamecreators.com

**Comment by UltraVox001** [comment]
@ZakJudges 
It's sent :)
