### ISSUE TITLE
GG Max Bug Report - After a few minutes of inactivity Max searches for data in other hard drives

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2256]
After a few minutes of inactivity, when I return to Max's editor, it searches for data that **does not exist** in my other hard disks. Yet all of Max's data is in my SSD (C drive) and nowhere else. Yet I hear Max looking for something on my E and F drives (mechanical drives) and during this time **Max is frozen** on the screen.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb @ZakJudges @PaulSJ Can you spend 5 minutes to confirm if this bug happens to you. I have not seen this. My HHDs thrash all the time, but then the OS and other background tasks make regular use of the whole of my system.  Could be a false positive this one.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
No, it's not a false positive. :) My system never uses my E and F drives. They are dormant when I use Max and even when I'm on the web. Max is the only one to reactivate them after a few minutes of inactivity.

**Comment by ZakJudges** [comment]
I also wasn't able to reproduce this one

**Comment by UltraVox001** [comment]
I will try what you suggest.
For information, a person had noticed this problem. It's @casigus

**Comment by PaulSJ** [comment]
I left the editor idle for 5 minutes and watched its disk usage in Task Manager, it remained at 0MB/s the whole time

**Comment by UltraVox001** [comment]
Here are two screens with Max's activities on my D drive.
I have 3 hard drives. A disk C (SSD) on which Max is installed, and two other disks : D and F. (E is a virtual drive that I disabled).
![D-Drive](https://user-images.githubusercontent.com/96718175/155538030-27bdd2c7-1f21-409b-93db-c2901888c6e2.png)
![D-Drive-MaxAccess](https://user-images.githubusercontent.com/96718175/155538037-555b2241-bd69-4542-b039-8aa6ab0a8a9d.png)
When I load a big map on Max, and I'm going to browse the web for several minutes, and when I come back, I get Max's window and as soon as I move the camera, it freezes for several seconds (on average, 6-8 seconds) time to access disk D to write data (apparently).

**Comment by ZakJudges** [comment]
@UltraVox001 the file being accessed is pagefile.sys

As far as I know, this file can be thought of as storage for when your RAM is full. The unused memory will be stored in pagefile.sys, and be restored again later. I'm guessing when you resume Max, the data in the RAM that Max was using is then restored from the pagefile.

Since your pagefile is on the D drive and not C (your SSD), I would imagine the source of the freeze is the time it takes to move the data from the pagefile back to RAM. However, I would definitely get a second opinion on that, as I'm not entirely sure :)

**Comment by UltraVox001** [comment]
I wonder what this file is doing on my D drive.
My Windows is on C, like Max.

**Comment by UltraVox001** [comment]
The choice of a mechanical drive instead of an SSD for data transfers... frankly :)
