### ISSUE TITLE
Maxing out normals to get shadows working

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#2265]
Hi guys ,as the title says i am having to max out the normal setting to get proper shadows working, tried different settings with no luck , i sent a link to Lee for the model a couple of days ago

https://www.youtube.com/watch?v=C54HVOLFJ10

This is from a early build

https://www.youtube.com/watch?v=pG0AdWZ5Pno

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you reproduce this for me with stock media? @Granada1 Perhaps you can email Maciej the files he needs to reproduce.

**Comment by Granada1** [comment]
@LeeBamberTGC ,i cant find the email address for dllllllllllb  !

**Comment by dllllllllllb** [comment]
@Granada1 My email is maciej@thegamecreators.com :)

**Comment by dllllllllllb** [comment]
@Granada1 My email is maciej@thegamecreators.com :)

**Comment by Granada1** [comment]
Link to model and textures sent

**Comment by Granada1** [comment]
Seems to work now by adding (smooth angle 101 )to the Fpe
