### ISSUE TITLE
ImageZone locks up Standalone Game

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2267]
As stated in Standalone the Game locks up with a **Runtime error** when using an Image Zone 
Also noted that the images are not carried over and manually doing it does not work.

![imagezone](https://user-images.githubusercontent.com/35708217/155571162-ec08d635-b949-457f-a62d-72c66d582e09.png)

**Comment by UltraVox001** [comment]
Does this problem also occur in the TestLevel ?
Because I have an almost identical error message when I use a night vision script :
![RuntimeError](https://user-images.githubusercontent.com/96718175/155571991-d9f96d0c-48e2-4554-83ca-b6dece2b8ba0.png)

**Comment by synchromesh62** [comment]
> Does this problem also occur in the TestLevel ? Because I have an almost identical error message when I use a night vision script : ![RuntimeError](https://user-images.githubusercontent.com/96718175/155571991-d9f96d0c-48e2-4554-83ca-b6dece2b8ba0.png)

It works fine for me in testgame. Its just standalone it locks up and its a CTRL-ALT-DEL to get out of it

**Comment by ZakJudges** [comment]
A fix should be in a build tonight or tomorrow :)

**Comment by synchromesh62** [comment]
> A fix should be in a build tonight or tomorrow :)

Thanks Zak it seems to be working just fine now :)
