### ISSUE TITLE
GameGuru MAX Terrain editing icons need changing

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#2269]
Hi the erase and restore icons are the same, and i have clicked on the wrong icon more than once, i am an old man LOL.

Can we have a different icon for restore ? i have attached one that does look more like an undo ;) feel free to use.

Current Icon:
![ssrestore](https://user-images.githubusercontent.com/35724756/155582934-e7038b37-75f4-4bda-a878-c70ffa02f777.png)

Custom Icon:
![restoreblue](https://user-images.githubusercontent.com/35724756/155583491-e0543bdc-c07f-426a-8d2c-6fe0c626a88c.png)

here is a white with transparent background version

[restore.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8134818/restore.zip)

regards
Kevan

**Comment by ZakJudges** [comment]
Apologies for the late response! Thank you for the files, it looks like the vegetation UI has been changed since this issue was created, and now there are only Paint or Delete icons. Closing this issue :)
