### ISSUE TITLE
SetSkyTo() bug?

### ISSUE THREAD

**Issue by KasparsM** [TheGameCreators/GameGuruRepo#227]
if i try to set sky to SetSkyTo("sunset") or as in skyspec file SetSkyTo("Sunset Sky"), the last in skybank folder, it do not changes. i used both words, but none worked. i tested other sky, it works fine, so its not my script problem.

**Comment by HierToo** [comment]
You are right and I fixed it

**Comment by KasparsM** [comment]
it looks like when saving standalone it only saves one sky to skybank folder. i have daynight script which changes sky according to hours variable, in editor it works, but in standalone not, i checked standalone skybank folder and found only one sky.

**Comment by HierToo** [comment]
Fixed

**Comment by HierToo** [comment]
fixed with #228
