### ISSUE TITLE
MAX should report missing media but not crash

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2273]
Due to a partly updated build these screens appeared. Ideally MAX will let the user know files are missing and advise the user verify their files and then continue without crashing.
![image002](https://user-images.githubusercontent.com/1503593/155684447-8601ec6c-c5f7-4451-9698-18fd3de5668e.png)
![image001](https://user-images.githubusercontent.com/1503593/155684459-b5fbdb90-2bda-44eb-a40b-1f463af43025.png)

**Comment by ZakJudges** [comment]
@rvanner I think this one might cause more problems than it solves. The way I see it, there are two options to allow the user to continue using the software with missing files: 

- We add a lot more error trapping code, which would cover a large amount of the codebase, which could take some time.
- We replace any missing files with a blank useable one. Should avoid most crashes, but might still cause some strange behaviour to the point where we will likely need to add a lot more error trapping code anyway.

I'm not 100% sure that is the case though :) 

@LeeBamberTGC Any thoughts on this?

**Comment by ZakJudges** [comment]
It should also be noted that after implementing #2331 , partially updated builds should be less common
