### ISSUE TITLE
Max installer needs to avoid looking like it's not trusted

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2274]
![image003](https://user-images.githubusercontent.com/1503593/155684648-00ab4b28-7a68-43d5-8fd8-a18b703577f2.png)

**Comment by rvanner** [comment]
@ZakJudges Do you know (or can you check) that the installer has a publisher certificate?

**Comment by rvanner** [comment]
@ZakJudges Yes, check with Lee when he's back to work out the next steps.

**Comment by LeeBamberTGC** [comment]
@rvanner All three downloadable EXEs are signed and certificates are up to date.  Try this again with the latest Tiny installer and if happens again click the MORE INFO.
