### ISSUE TITLE
Particles - X/Y/Z scale bug

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2277]
When you change particle X/Y/Z scale, it applies the new scale to all axis and the slider sets itself to 1

**Comment by dllllllllllb** [comment]
@LeeBamberTGC @rvanner While working on this I found other issues. 
When you change the scale of an object, select a different one and go back to the same one, the scale value is not saved but the object keeps it set scale, so the slider would say scale is equal to 100 but it would actually be 150 and use 150 as base for scaling. This makes scaling objects inconsistent. My proposition is to have a float in sObject struct that stores its scale and use that in the slider for overall scale.

The way objects are scaled (just inside the slider) is overcomplicated, while modifying the code to see which part does what etc. I used a different slider that allows for decimal points. This works much better in my opinion, it gets rid of the "steps" in which objects are scaled by allowing for finer controls and gets rid of negative number conversion.

It also gives meaningful value to scale, where 1.0 is the original scale, 2.0 means that the object is 2x the base size and so on.
https://gyazo.com/d03fcf6a414346dd16270ea88045eddf

**Comment by LeeBamberTGC** [comment]
@dllllllllllb We cannot change how the scaling works to that degree as it will create knock-on effects as yet unrealized.  For this issue, fixing the particle so that we only have one scale slider and removing X Y Z control should allow you to close this one.

**Comment by OldFlak** [comment]
Given this is still Alpha and that scaling in X Y and Z is needed for particles wouldn't it be best to fix it properly now?
It is Alpha - Doesn't matter what it breaks it should be fixed properly.

No hacks or workarounds for MAX :)
