### ISSUE TITLE
Weird rotation issue with DYNAMIC scaled entities

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#2279]
See video: https://vimeo.com/681897554

Only difference between the working one and the weird one is the scaling value in the .fpe file, i.e. first is 100 second is the default 50.

Using this script (which I wrote in response to another issue):
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8141977/door_sliding.zip)

**Comment by AmenMoses** [comment]
They are rotated by about 45 degrees btw, with no rotation the problem doesn't show up.

i.e. 
![rotate issue](https://user-images.githubusercontent.com/35708338/155737413-358d33ff-1771-42a5-9ea0-0c8a297f9423.png)

**Comment by AmenMoses** [comment]
Is this related to #1648?

**Comment by AmenMoses** [comment]
Why did the Classic tag get removed?  The bug occurs in both but is more noticeable in MAX as many of the stock entities are scaled!

**Comment by LeeBamberTGC** [comment]
@AmenMoses Added a crate with a 100 scale, made it HULL DECOMP, duplicated it and shrank the clone, then ran test game with physics wireframe on, the collision shapes look fine:

![image](https://user-images.githubusercontent.com/35840583/174785497-891c37e4-1264-4b05-b6f1-d9eeb5fd4bba.png)

Then rotated 45 degrees with the R key, box collision shapes were still fine:

![image](https://user-images.githubusercontent.com/35840583/174785595-07cfbe2e-f790-4afc-80c6-fc7cc810b7f4.png)

**Comment by AmenMoses** [comment]
Are they dynamic entities?

**Comment by LeeBamberTGC** [comment]
@AmenMoses All CONVEX, HULL DECOMP and POLYGON collision shapes are static. No support yet for dynamic complex shapes.

**Comment by AmenMoses** [comment]
Yeah, but that has no bearing on the problem as these ARE dynamic entities!  (so presumably box shape)

**Comment by ZakJudges** [comment]
Notes on this issue: does not occur if you set the object to isimmobile when using door_sliding behavior. It is possible that in the script, when the door position gets stored, the reported ObjectPosition is somehow different to the physics world position

**Comment by LeeBamberTGC** [comment]
@AmenMoses Lots of object placement work in the level editor since this post (and physics system work). Let me know with a small FPM example if you can still get this issue to appear, thanks!
