### ISSUE TITLE
Terrain Generator into Level Editor

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2281]
When a user has made a new level with the terrain generator and then come into the Level editor, do the following to make the experience easier for them;

- Position the camera at the height seen in the image below (so near the ground)
- Clear all trees within 800 units of the center so the user can see an area to start adding objects into

![image](https://user-images.githubusercontent.com/1503593/155746504-b5bfedc0-5bae-49e4-9bd6-08a5ffb0fe1f.png)

**Comment by plemsoft** [comment]
@rvanner Fixed for the next update :)
