### ISSUE TITLE
Very slow frame rate when running Skype and test level

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2282]
Why is my CPU maxing out when I try to demo MAX during a Skype call?

![image](https://user-images.githubusercontent.com/1503593/155746921-91349614-b34c-4583-8f8d-dbfbde99415e.png)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Step one is can you reproduce the issue reported, then to drill down to find the critical path and the bottleneck.

**Comment by ZakJudges** [comment]
@rvanner Do you have the map file that you were experiencing the issue on? :)

**Comment by rvanner** [comment]
@ZakJudges Sorry, no idea where that level is now. @LeeBamberTGC has always said that we should break down the General section into more sections. So when it happens again we will have a better idea what the bottle neck is. Maybe you can do that?

**Comment by ZakJudges** [comment]
@rvanner Sure, I can do that. @LeeBamberTGC how much detail would you like it to be broken down into? Also, should I keep this high priority, or tackle this after bugs when we are focusing on optimisations? :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges I have set to MEDIUM, we can set back to HIGH next week when the whole team drill down on optimization work.

**Comment by LeeBamberTGC** [comment]
NOTE: Run Skye, new screenshot.

**Comment by rvanner** [comment]
Closing this now that frame rates are vastly improved.
