### ISSUE TITLE
Remove the light probe scale slider (not used any longer)

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2284]
![image](https://user-images.githubusercontent.com/1503593/155748078-82e6a4a5-b4ea-48c9-bc54-686cfc29aabb.png)

**Comment by ArgentArts** [comment]
Light probe scale is still there as of this Friday's build.

**Comment by ZakJudges** [comment]
@ArgentArts this should be in the next build. We try to minimise the amount of new code in Friday's release, so we can test it beforehand :)
