### ISSUE TITLE
If a user types in a new game name and presses ENTER, continue and make the game (no need to press the button)

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2288]
Allow the user to type a name of a game and if they press ENTER let that be the same as pressing Create Game Project

![image](https://user-images.githubusercontent.com/1503593/155749491-f5f9093d-6187-4811-9c2d-58f8e407bd3a.png)

**Comment by ArgentArts** [comment]
I'm kind of mixed on that one. I may hit ENTER and then realize I've misspelled the name of my game. Having to go and actually click Create Game Project sort of forces me to recheck things before committing.

**Comment by plemsoft** [comment]
@rvanner Fixed for the next update :)
