### ISSUE TITLE
For each demo game, add controls and objectives to the loading screens

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2289]
For each demo game, add some text like this so new users know the controls and have an idea of what to do in the game.
The text will have to be pasted into the background of the loading screen.

![image](https://user-images.githubusercontent.com/1503593/155750321-abb10a84-d816-4902-bc9f-50e86ce1c468.png)

**Comment by dllllllllllb** [comment]
@rvanner I can't figure out how to add a text box to the loading screen, how did you do it?
Or do you want me to just write out what each loading screen should say?

**Comment by dllllllllllb** [comment]
@rvanner Island Showdown backgrounds are really low resolution, adding text to it in photoshop will be very pixelated and look bad. Should I add it anyway or use a higher resolution background from the image bank?

**Comment by rvanner** [comment]
@dllllllllllb OK good! Just one point re the Island Showdown loading screen, that is not an image from that game. Its' from an older jungle map making competition. Can you change it for an image from the actual game (note that I will be sending a newer version of this game soon).

**Comment by dllllllllllb** [comment]
@rvanner Is the newer version send yet? If not, could you please send me a message here when it is :]

**Comment by rvanner** [comment]
Just posted a link on Teamwork about this.
