### ISSUE TITLE
GG Max - Bug - Character HP and Gun Damage

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2294]
I have just tested several scenarios with guns and characters and every time the damage and health of enemy does not seem correct.
As a example, I set a enemy to only have 20 HP, and had a pistol to only do 2 damage per shot.
But every test, i always one shot the enemy.

I tested this same theory with different numbers and always did not add up right on damage / hp .

**Comment by ZakJudges** [comment]
Hi @Tum1370, is this issue now fixed for you?

**Comment by Tum1370** [comment]
Closing this issue, i think it seems to be working fine now.
