### ISSUE TITLE
Create more 'hurt animations' to slightly move character from direct fire

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#2296]
Suggest variations of animation to move the character with a hurt animation to:

2 x left
2 x right
2 x upper body hit
2 x lower body hit

**Comment by LeeBamberTGC** [comment]
@rvanner Would you like to ask Gaby ti proceed with these eight animations, and let me know if you have any questions? It will make the hurt system for characters pretty impressive when these variations are implemented.

**Comment by rvanner** [comment]
Hi Lee, sure I can do that. Can you just detail a bit more of what you want them to look like and how long they should animate for? Maybe these are just say .4 of second long for example?

**Comment by LeeBamberTGC** [comment]
@rvanner The animations will be very similar to the Punched_(n_Face animation, with arms halfway between the normal idle and outstretched for aiming. This way they can be used for unarmed, pistol, and rifle carriers. It would be about 1.5 seconds in length. As with the punched in face animation, the character will stagger the feet slightly in the prescribed directions to affect movement during the animation of a distance of one step. Both lower and upper body would ultimately be one step backward.  Finally, the animation starting frame should be part-way into the reaction as this animation is played very quickly during an impact event and does not need to warm up from an idle pose (as though starting the punched in face 10% into the anim).
