### ISSUE TITLE
GameGuru MAX - Bug - Level Disappears

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2299]
Did a Fresh Install of MAX, built a new test level to test PBR materials, saved everything, closed MAX, opened again, and this is what happened:

https://user-images.githubusercontent.com/36735507/155825175-6ecdbc2b-0d27-49c6-8880-8a9cc3c5dff8.mp4

As you can see, the level initially loads, then it disappears. Initially looking around, there is nothing. Then, after a bit, there is a tall, square column in the middle of nowhere. 

My level is saved and I can load it after this by going to File>Open Level. After opening the level, it works fine. I can test run it, etc. However, saving the level again does not resolve the issue. Every time I start up MAX and run this level from the the Storyboard, it loads initially, then turns to an empty level as in the video.

As a side note: the reason everything is dark is because I've set the environment that way. So, that's not part of the issue.

**Comment by ArgentArts** [comment]
Here's another example of this happening:

https://user-images.githubusercontent.com/36735507/155826061-637f3109-878f-4d30-9f6a-9b8bc4163711.mp4

It's repeatable every time for me.

**Comment by plemsoft** [comment]
@LeeBamberTGC I added a fix for this and sent you a e-mail, properly you missed it in these crazy times :) , anyway i think you needed to do it by hand for the Friday build, the commit is here: https://github.com/TheGameCreators/GameGuruV3Repo/commit/120158af464b0a9a11299dad3783f15a5d8a77cd

**Comment by LeeBamberTGC** [comment]
@plemsoft We missed the deadline for Friday commits, but it is now in the new internal build uploaded and ready to release very soon.

**Comment by ArgentArts** [comment]
This is fixed in today's build in all of my levels.
