### ISSUE TITLE
Strange slowdown during player collision

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#23]
GG drops from 60fps to 30fps seems to occur when the player collides with an entity that is 1) rotated 2) has polygon or box collision and rotated, there is the usual slowdown with polygon collision still, but their framerate does not go back to 60fps until the player is out of occlusion range it seems.

**Comment by StabInTheDarkSoftware** [comment]
Bullet Physics was not implemented correctly.

**Comment by LeeBamberTGC** [comment]
As Stab says, the current implementation uses an expensive method to perform polygon collision, essentially taking each polygon and testing it in turn (the tests are fast, but with lots of polygons it still results in an overall game slowdown). The rule is not to use polygon collision for dynamic entities nor for models that have a lot of polygons, especially polygons that are small and close together as this really upsets the solver. A better system is to use something called Convex Hull Meshes which reduce the work required to confirm contact between two bodies.  I have reclassified this issue as an enhancement for now so I can deal with crash bugs and forward compatibility issues relating to the step up to DirectX 11. Once they are dealt with, I will have time to see if I can create a new labels category for 'Optimization' which would be the best moniker here.

**Comment by Teabone3** [comment]
Didn't notice this issue here. Made a recent post which includes video on how to reproduce and an FPM file #109

**Comment by LeeBamberTGC** [comment]
Very much related to the collision setting of the asset. For high polygon models, the physics engine works harder. For things like fences, using a box collision is the right collision shape.  Mor info in the other bug duplicating this one: #109
