### ISSUE TITLE
MAX - 2022.02.25 - Normal Grass Under Water

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2303]
Water plants no longer being painted under water 
- previous versions worked fine 
- now tis hit and miss

![image](https://user-images.githubusercontent.com/12246318/155842705-f85102aa-7ad8-4357-9bab-492d2ac6698b.png)

**Comment by PaulSJ** [comment]
The current version should now allow you to paint any grass anywhere, even underwater

**Comment by OldFlak** [comment]
Thanks Paul - Will check it out

In the above level there was no painting done at all - it just rendered grass like that.

However even so, it is not an engine decision.
- The engine should just default to only placing water plants in the water - yes
- But we should be able to paint grass anywhere we want, if we want

The engine should not enforce anything - defaults are ok as long as you can override them.

**Comment by OldFlak** [comment]
@PaulSJ Tested in current build. Steam version.
Paints all grass correctly - and also allows me to paint grass under water if I should want to.
So issue sorted :)
