### ISSUE TITLE
character triggers

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2305]
![image](https://user-images.githubusercontent.com/68471279/155846153-cf2fbe74-f190-4a4e-9ea7-155c8ce92d28.png)

there is now no way to connect trigger zones to characters......

**Comment by UltraVox001** [comment]
Are you sure about that ?
![TZoneConnectedToCharacter](https://user-images.githubusercontent.com/96718175/155847200-cc77c33b-79ad-4a18-ad98-0985ed5ce1fe.jpg)

**Comment by casigus** [comment]
Ohhh got ya.

**Comment by LeeBamberTGC** [comment]
@casigus Just tested to make sure with the latest internal build, seems fine:

![image](https://user-images.githubusercontent.com/35840583/156222552-aaf5347e-fc93-462c-8cc2-2cd5637433aa.png)

**Comment by casigus** [comment]
aye im sure everythings fine, I had a tonne of issues with the new build with objects resizing them selves when saving a level (working on that demo for you) so went back to a previous build! :)
