### ISSUE TITLE
objects resizing them selves after saving or game testing.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2306]
![image](https://user-images.githubusercontent.com/68471279/155847468-2bfc8dae-0a9c-40cd-8e5b-57f560cdafb8.png)

**Comment by ivanski1983** [comment]
I’m having this issue too.

**Comment by UltraVox001** [comment]
Reported and fixed here : [https://github.com/TheGameCreators/GameGuruRepo/issues/2316](https://github.com/TheGameCreators/GameGuruRepo/issues/2316)

**Comment by plemsoft** [comment]
Yes a dup: Fixed for the next update :)
