### ISSUE TITLE
switch error. 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2307]
that keeps popping up! 

![image](https://user-images.githubusercontent.com/68471279/155847932-e8fb8212-b344-4719-969b-1b2231ec7de6.png)

**Comment by LeeBamberTGC** [comment]
@casigus Added error trapping to prevent this if some objects using the module without being initialised:  if g_module_activationcontrol[e] == nil then g_module_activationcontrol[e] = {} end

**Comment by casigus** [comment]
aye everythings working again now, gone back to the build released on the 18th, which works well.
