### ISSUE TITLE
Terrain Chunk Corruption

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2308]
![image](https://user-images.githubusercontent.com/68471279/155848918-a85b1b87-05f7-4f01-969d-9415fa081ab0.png)

random chunks of  the terrian randomly appearing like this.....

**Comment by PaulSJ** [comment]
@casigus Is this still an issue? If so can you give some setps to reproduce it?

**Comment by casigus** [comment]
nope  tis  not  !!
