### ISSUE TITLE
Custom Hud - Fonts display poorly

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#231]
Hey all :)

As the title says. fonts displayed on a custom hud display poorly like they are distorted.

Tested with the X9 version and they display perfectly.

Reliquia....

**Comment by tarkus1971** [comment]
I have noticed this with prompts as well, the edges of some of the letters seem rough. the "O" in particular

**Comment by michaeloldman** [comment]
Yes, it also is affecting images on a custom hud as well, just a little less noticeable.

Reliquia....

**Comment by LeeBamberTGC** [comment]
The rendering of the images are 1:1 pixel, but if you can provide an image, a script, an FPM and a screenshot of what you see, we can re-open this issue,

**Comment by michaeloldman** [comment]
Hi Lee :)
Thanks for hard work on the bug slaughtering :)
Custom HUD, script and FPM sent via email.

This is what it displays like:
![FontDisplayproblem](https://user-images.githubusercontent.com/12246318/60277027-19b8aa00-9940-11e9-934e-818e80cf60ea.png)

Reliquia....

**Comment by michaeloldman** [comment]
Here is an image that just gets displayed on screen using simple display to screen script
SetImagePosition(50,50)
ShowImage(0)
    
![000](https://user-images.githubusercontent.com/12246318/60277890-ccd5d300-9941-11e9-9282-5269a5b674d4.png)

Looks like this in test game:
![ImageDisplayproblem](https://user-images.githubusercontent.com/12246318/60278219-5c7b8180-9942-11e9-9ade-5422a3954f39.png)

Reliquia....

**Comment by LeeBamberTGC** [comment]
Fixed for next beta build (28th). Turns out the UV coords did not apply the pixel center offsets as required for perfect 1:1 rendering of the text.   See attached for before and after shots.
![image](https://user-images.githubusercontent.com/35840583/60304602-d6573f00-9931-11e9-8537-96dfb52d9818.png)

**Comment by michaeloldman** [comment]
Awesome :) Thanks Lee 

Reliquia....
