### ISSUE TITLE
Trigger behavior button inop

### ISSUE THREAD

**Issue by ivanski1983** [TheGameCreators/GameGuruRepo#2313]
The behavior button on the trigger zone is not working correctly. I have to go to developer mode and select the behavior from there. It will update on the behavior tab but still is not clickable.

**Comment by LeeBamberTGC** [comment]
@ivanski1983 Yep, some recent improvements took one step back here. Added ability to change TRIGGER ZONE behavior as the exception to the GAME ELEMENTS, which otherwise use fixed behaviors to denote their function.  In the next internal build.
