### ISSUE TITLE
MAX - 2022.02.25 - Scale Particle Is Broken

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2315]
Worked in previous build - tis not working now

Used to be able to scale particle bigger or smaller 
- now only goes bigger which for many particles is not much use at all

**Comment by dllllllllllb** [comment]
#2277

**Comment by OldFlak** [comment]
2022.03.04 - the scale issue is fixed as far as scope of this thread is concerned

Just need scale X to work properly now :)
