### ISSUE TITLE
MAX - 2022.02.25 - Sound Slot 4 Missing

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2317]
Sound slot 4 has gone missing - not seeing it in the editor. 
Another UI bug?

**Comment by plemsoft** [comment]
Fixed for the next update :)

**Comment by OldFlak** [comment]
@plemsoft Hi Preben - issue remains in 2022.03.04 build

**Comment by plemsoft** [comment]
@OldFlak You tested before Lee had uploaded the new build , could you try to validate and try again :)

**Comment by OldFlak** [comment]
No was tested with 2022.03.04 - will verify and try again :)

**Comment by OldFlak** [comment]
@plemsoft Verified and tested again - fixed now thanks Preben :)
