### ISSUE TITLE
GG Max Bug Report - The "Show Live FPS" checkbox does not work

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2319]
The "Show Live FPS" checkbox does not work.
Checked or not, this function is always active.

**Comment by plemsoft** [comment]
@UltraVox001 Sorry forgot to mention superdeveloper 3, you know :)

**Comment by UltraVox001** [comment]
I was using the previous internal update.
Everything works now. Sorry. :)
