### ISSUE TITLE
MAX - 2022.02.25 - Standalone - Save Game Brings Up Wrong Screen

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2320]
Selecting Save Game in standalone is bringing up the Load Game screen
- double checked that they are hooked up correctly

Also note the numbering on the already saved games 
- are they not meant to always be numbered 1-8?

![image](https://user-images.githubusercontent.com/12246318/155880700-c136efe6-b4ed-4c61-97c2-b5b093f868b2.png)

**Comment by plemsoft** [comment]
@OldFlak Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by OldFlak** [comment]
@plemsoft Hi Preben, this is fixed in latest build - thanks :)
