### ISSUE TITLE
MAX - 2022.03.04 - Water Fog Not Working

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2329]
Not new - they have never worked really.
Play with water fog sliders - there is practically no control for the water fog

**Comment by PaulSJ** [comment]
@OldFlak Is this still an issue? Water fog sliders seem to work here

**Comment by OldFlak** [comment]
Hi Paul thanks for reply :)

The sliders have very little effect over the range of the slider.

For example: Water Fog Maximum only has effect from 0 to around 15:
![image](https://user-images.githubusercontent.com/12246318/164116258-548cbc7e-63a2-409f-a79c-88c8ed8c271a.png)

Here it is set to 15 and fog is all but gone:
![image](https://user-images.githubusercontent.com/12246318/164116336-f7373c99-a876-41ea-9cc7-2373a15d29b0.png)

And here it is set to 100 and practically no difference to when set at 15
![image](https://user-images.githubusercontent.com/12246318/164116388-9981af2e-1c5e-49cd-9e46-4bc733c7a673.png)

**Comment by PaulSJ** [comment]
It is because you are using shallow water. If the water were deeper then you would see the effect over a larger portion of the slider

**Comment by OldFlak** [comment]
> It is because you are using shallow water. If the water were deeper then you would see the effect over a larger portion of the slider

No the sliders are broken :)
Half the slider is useless - has no effect at all.
![image](https://user-images.githubusercontent.com/12246318/164714380-76c66180-7573-4dc5-82f4-e8841f8b3ae9.png)
