### ISSUE TITLE
GG Max - Latest Build - Cannot walk through raised warehouse door.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2332]
Just tried my warehouse level, and now after raising my warehouse door, the door goes up, but i cannot walk through the empty spot.
Its like the door is still lowered.

I tried removing the logic and re adding new logic from this weeks build, but still the same thing.

I went and tried the Switch Escape level, and the warehouse door raise ok on that level.

**Comment by ArgentArts** [comment]
I think they would need a lot more information to help you with this sort of thing. It could be so many thing. Is it your own warehouse (i.e. a warehouse that you created) or one of the warehouses from MAX's collection? Did you set your own collision to the warehouse or did you use the collision method that the model came with? which behavior are you using on the door? Etc. Etc. When reporting things like this, I would provide as much information as you can in order to help the TGC team help you.

**Comment by Tum1370** [comment]
Its basically an identical copy of the switch escape level, All i have done is try my best to recreate the level, as to learn how it was made. Using just assets that are with Max.
But this was working fine last weeks build, but now its not.
I would imagine this has something to do with the fact that last week, You would raise the warehouse door, and after lowering it down again, you could just walk through the door.
I guess this is another fix gone wrong.

**Comment by UltraVox001** [comment]
I reported this to @LeeBamberTGC  several days ago, but I don't think he believed me :)
[https://github.com/TheGameCreators/GameGuruRepo/issues/2046](https://github.com/TheGameCreators/GameGuruRepo/issues/2046)
The strangest thing is that it works on his map, but not on mine.

**Comment by synchromesh62** [comment]
> I reported this to @LeeBamberTGC several days ago, but I don't think he believed me :) #2046 The strangest thing is that it works on his map, but not on mine.

I played with this and had to raise the height in the script for the door i was using. It seemed to need more clearance however Amen has released a better version that seems to work at any height and can be used as a sliding door as well.

**Comment by UltraVox001** [comment]
@synchromesh62 
Where is the link to this version of Amen, please ?

**Comment by synchromesh62** [comment]
> @synchromesh62 Where is the link to this version of Amen, please ?

I have attached it here .. Cant find the actual issue he posted it in :)
I think Lee has added it as well to tonight's build.
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8160896/door_sliding.zip)

**Comment by ArgentArts** [comment]
He originally posted the script (and updated it) here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2173

Lee also said he's replaced his script with this one, too.

**Comment by Tum1370** [comment]
` thanks, i had just downloaded the Door Slide script, works much better .`

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Am closing this issue as the new Door Sliding script fixed this issue.
