### ISSUE TITLE
GameGuru MAX - Island Showdown T-Pose and Teleport

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2333]
There are a few minor visibility issues with the Island Showdown that detracts from the demo. When you initially start toward the main island, there are two soldiers that you see on patrol. When you see them in the distance, instead of walking in patrol, it appears as if they walk in one direction and then teleport back to the start position and begin to walk back, teleport, walk back, teleport, over and over again. After you get close enough, the teleporting stops and they follow their paths. Here's a video (look toward the center to see the two men on patrol - the video is from an ultra-wide screen - I recommend right-clicking and downloading to view):

http://www.argentarts.com/uploads/teleport.mp4

Later, when you go to the left-side, you can see a soldier standing there. Because he is far enough away to not detect you, he is still in his t-pose:

![t-pose](https://user-images.githubusercontent.com/36735507/156046215-3795389d-31a4-461b-9bfb-4e73ee2fd480.png)

Neither of these things look good for demonstrating MAX, I think, and should be fixed before the Early Access release.

**Comment by UltraVox001** [comment]
Yes. This is because the mesh nav system is not complete. I reported this issue a while ago and I know TGC is working on it. When the new nav mesh is finished, the demo will automatically be operational.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Fixed for next internal build. Also suspended logic beyond freeze distance to save performance for large enemy levels.

**Comment by ArgentArts** [comment]
Appears fixed with this release.
