### ISSUE TITLE
Intro video played too big on a laptop so you could not skip it

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2335]
This happened yesterday when we had turned off the DPI setting:

![image](https://user-images.githubusercontent.com/1503593/156123589-cf9071f0-b84f-4db5-a57d-9cfe540dc7bb.png)

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next update :)
