### ISSUE TITLE
GG Max Bug Report - Changing the Grass Draw Distance setting does not allow me to save the map

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2342]
Changing the Grass Draw Distance setting does not allow me to save the map.
Video : [https://www.youtube.com/watch?v=jc8UG9ClMiw](https://www.youtube.com/watch?v=jc8UG9ClMiw)

**Comment by ZakJudges** [comment]
Hi @UltraVox001, is this issue now fixed for you? :)
