### ISSUE TITLE
When a new level is created from the terrain editor, place a player start marker in the centre of the map

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2344]
So this is an addition to clearing any trees out of the way. Now add in a start marker and make sure the camera is pointing at it.
Also add a help text that shows:

"A start marker has been added to your new level. This is where you will start in this level when you press Test Level. You can move the marker somewhere else at any time."

**Comment by plemsoft** [comment]
@rvanner This has been fixed for the next build :)

**Comment by ZakJudges** [comment]
@plemsoft FYI: the message appears each time you save. I don't think it replaces an existing marker though, so its not urgent :)

**Comment by plemsoft** [comment]
@ZakJudges Thanks fixed :)
