### ISSUE TITLE
GameGuru MAX - Objects with Double-Sided Materials Cannot be Selected from Both Sides

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2348]
If you have an object with a double-sided material, it can only be selected from the front side and not the backside:

https://user-images.githubusercontent.com/36735507/156200612-6b817277-05af-4001-a5ba-7099d156105e.mp4

In other words, the side that originally did not show the material is un-selectable.

**Comment by OldFlak** [comment]
This is possibly the same issue #2355
https://youtu.be/PhGZ7V0AyI0

**Comment by LeeBamberTGC** [comment]
Fixed for next EXP build on Steam :)

**Comment by ArgentArts** [comment]
Confirmed working. Thanks! :)
