### ISSUE TITLE
Player Being Shot Through EBE Wall

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#235]
Reported by email. Copied here:

I've just been testing with characters in the EBE. I am still seeing the player get shot through the walls and characters becoming inactive as shown here:

https://www.youtube.com/watch?v=TelxA_Ofg60
https://www.youtube.com/watch?v=wSjh1ajz_f8
https://www.youtube.com/watch?v=Nke74qRiX9k

[may be duplicated elsewhere in issues tracker]

**Comment by lordjulian1** [comment]
I posted this bug some weeks ago if you recall.

**Comment by thecyrus** [comment]
Confirmed, I keep being shot trough walls and seeing enemy parts out of walls. Not only in EBE.

**Comment by LeeBamberTGC** [comment]
Character AI can no longer shoot through EBE walls (and other 3D model entities that they happen to be 'inside'. Fixed for next PP build.
