### ISSUE TITLE
GG Max - Playing / Editing Demo game gets copied to my own Projectbank folder 

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2350]
Just tried a new install of Max, and i tested the 3 demo games, and everytime the games then appear in my own Projectbank folder in My Documents folder.

Seems very messy, That folder should just be for my own Projects ?

**Comment by Tum1370** [comment]
Also, seems very awkward to delete a whole project. Could do with a delete option from the Max Hub ?

I tried deleting the 3 demo games from my projects folder, as i mentioned in the first post, But after deleting them, the Switch Escape demo never worked properly again.

I had to uninstall and reinstall the whole of Max for it to work properly again.
Only to have it then copy and place the game in to my projectbank for my projects.

**Comment by LeeBamberTGC** [comment]
@plemsoft I also noticed this. I assume this is to keep the mapbank level file read only for demo games, and if you modify them they are stored in the project folder directly. Is this so?

**Comment by Tum1370** [comment]
I noticed it only does this with both Cellar and Switch escape demos.
Island showdown demo does NOT copy files to the projectbank folder.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed and will be in the next update :)
