### ISSUE TITLE
MAX - 2022.03.04 - Selecting Transparent Objects

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2355]
Cannot select transparent objects from both sides
- this is not a new issue, selecting transparent objects has been broken for many months now

Probably more likely just related to double sided objects?

https://youtu.be/PhGZ7V0AyI0

**Comment by LeeBamberTGC** [comment]
Fixed for next EXP build on Steam :)

**Comment by OldFlak** [comment]
Fixed in current build thanks Lee :)
