### ISSUE TITLE
GameGuru HUB - can it be full screen?

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2359]
@plemsoft Is it possible to use the full size of the screen for the HUB and avoid the grey background;
eg
![image](https://user-images.githubusercontent.com/1503593/156374225-815a0e14-42b2-4bb9-b9da-4818638de4ac.png)

**Comment by plemsoft** [comment]
@rvanner I can change to color, is this better ?

![back-color](https://user-images.githubusercontent.com/18662417/156576767-2a4d08a4-dba1-4cda-938a-18c52fbdcbcd.jpg)

**Comment by rvanner** [comment]
@plemsoft Yes it's better but why can't it zoom to full screen? Is it just because it's designed for a set width?

**Comment by plemsoft** [comment]
@rvanner No it just looks different when full screen , this is how it looks , would you prefer that ?

![resize-hub](https://user-images.githubusercontent.com/18662417/156592485-72888ce2-4d45-41d2-a247-c80f5bc45394.png)
