### ISSUE TITLE
Bug: transparent textures in the wall, SIDE VIEW

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#236]
I don't know if this has already been reported.
I'm experiencing this in latest GG version, and I saw this with different entities.
I can see the outside when walking very near to a wall.
![image](https://user-images.githubusercontent.com/12373041/40379636-f1e39060-5df6-11e8-8d78-b01d90e55400.png)

**Comment by LeeBamberTGC** [comment]
This relates to the new camera near/far settings in the DX11 update, to handle Z clash effects better. To resolve the issue you see, simply adjust the camera distance slider in the Test Game TAB TAB settings panel until it goes away for the assets you are using in your level.
