### ISSUE TITLE
No footsteps sound

### ISSUE THREAD

**Issue by ChristopherFalcon** [TheGameCreators/GameGuruRepo#2362]
I'm having an issue with MAX regarding footstep sounds. There is none. No matter the material or object. Only sound is from jumping but none for movement. Tested different materials (snow, sand, grass etc.), objects (wooden building, metal floor etc). Any ideas? Video below: 
https://youtu.be/9Z8XYDYd5Eg

**Comment by UltraVox001** [comment]
In your video, I heard the sound of water and the sound of wood.

Go to "Environment Effects", then to "Ambient Music Track", and uncheck the "Enable Ambient Music Track" box. Only the sounds of the footsteps will remain. This will allow us to check which sounds are actually missing.

For me, except for water, there is only one footstep sound that works : grass.
I have already reported this problem.

**Comment by ChristopherFalcon** [comment]
Hi,

I did what you asked. It seems that all sounds except for jumping and water are super low volume. It seems like wood and grass are the only two working. New video below:
https://youtu.be/jW3R0IpWdxY

**Comment by UltraVox001** [comment]
Ok. So you are in the same situation as everyone else. :)
This is a small bug that I have already reported and will be resolved very soon. I'm sure.

I suggest you don't use ambient sounds with maximum volume level. Their volume has always been too loud compared to footsteps. Personally, I think I set this volume to 85 or 86. Never more.

**Comment by LeeBamberTGC** [comment]
@ChristopherFalcon This weeks build restores material sounds for terrain footfalls. The sounds are quite as they should not overpower the rest of the sound scape. The only remaining AI sound issue is that caused by player running down hill and not getting their full quota of foot sounds.  Ev erything else should be ready to test.

**Comment by ZakJudges** [comment]
Hi @ChristopherFalcon, could you confirm if this issue is fixed for you in the latest build? Thanks :)
