### ISSUE TITLE
More light issues

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2363]
![image](https://user-images.githubusercontent.com/68471279/156479737-f5b996f0-2a18-436b-b45d-2c33c50a115c.png)

placed abooot 50 of these lights. Saved the level, every single f**king one of them turned from static to Physics on and in game they act accordingly.

**Comment by synchromesh62** [comment]
Lights are dynamic .. you cannot make them static ?

**Comment by ArgentArts** [comment]
I'm confused, too, by the terminology you're using here. Are you talking about MAX or Classic? MAX does not use any static lights at all. They are all dynamic lights. All of MAX's lights are real-time (dynamic) as there is no lightmapper in MAX. Up to 16 of the ones nearest the camera can cast shadows. You determine which lights are shadow casting lights by ticking the shadow check box for each point light.

So, what's actually happening? What are you trying to do that MAX isn't doing here?

**Comment by ZakJudges** [comment]
#2351

**Comment by LeeBamberTGC** [comment]
@casigus See link above to your other report which covers the same issue in general, and also has less profanity ;)

**Comment by casigus** [comment]
sorry for the swear! was a wee bit wound up by the lights! yeah forgive the second report, only made it again as it happened on a different map. I'll try and keep the same issues in the same places.
________________________________
