### ISSUE TITLE
Suggested MINIMUM SPECIFICATION and RECOMMENDED SPECIFICATION for MAX

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#2374]
This is the initial min spec we have been using thus far:

MINIMUM CONFIGURATION
Supported OS: Windows 10 (64-bit versions only).
Processor: Intel Core i7-3770 | AMD FX-8350, or better.
RAM: 6GB
Video Card: NVIDIA GeForce GTX 970 | AMD Radeon R9 290, with 4 GB VRAM, or better
Notebook support: Laptop models of these desktop cards may work as long as they are on-par in terms of performance with at least the minimum configuration.
DirectX: Version 11
Hard Drive Space: 30 GB available space.
Peripherals Supported: Windows-compatible keyboard and mouse
Network: Broadband Internet connection

RECOMMENDED CONFIGURATION
Supported OS: Windows 10 (64-bit versions only)
Processor: Intel Core i7-8700K | AMD Ryzen 7 3700X, or better.
RAM: 12GB
Video Card: NVIDIA GeForce RTX 3090 | Radeon RX 6900 XT, with 8 GB VRAM, or better
Notebook support: Laptop models of these desktop cards may work as long as they are on-par in terms of performance with at least the minimum configuration. 
DirectX: Version 11
Hard Drive Space: 30 GB available space.
Peripherals Supported: Windows-compatible keyboard and mouse
Network: Broadband Internet connection

**Comment by PaulSJ** [comment]
Personally I think the RTX 3090 and 6900XT might be overkill. I'm running a 5700XT and don't experience many issues, so perhaps an RTX 2080 and 6700XT might be better for the recommended?

**Comment by jbthenext** [comment]
I totally agree, a 3090 as recommended is totally overkill and hardly anyone will have one anyway. It also makes it sound like the graphics will require extreme GPU power and feature ray tracing which they do not. Even a recommended as RTX 2080 seems a bit high to be I would go with RTX 2070 or if going with something from this generation a RTX 3060 Ti/6700 XT and AMD

This matches up more with the CPU you are recommending which are many generations old now

**Comment by LeeBamberTGC** [comment]
Thanks, everyone for pitching in, I agree with everyone so far.  I will pick the lowest powered of the suggestions for recommended as I agree no sense using overkill recommendations when they are not needed.

**Comment by dllllllllllb** [comment]
Overkilled recommended configuration will put off people from getting GGM. 

My recommended:
CPU: Intel i7-9700K / AMD 3700X 
GPU: Nvidia RTX 2080 / Radeon 6700XT 
RAM: 16GB

**Comment by ArgentArts** [comment]
Forgive my ignorance, but how important is system RAM to running MAX? I've got tons (64GB), so I've not paid attention. But would 16 really be recommended? What about Lee's suggestion of 12? And why the RTX 2080? Isn't that the top-of-the-line 2x card? Why not the 2070 instead?

**Comment by ArgentArts** [comment]
For people reporting frame rates, it's helpful to also report screen resolutions, too. There's a big difference between 60fps at 1080p, 1440, and 4k. And even an ultra-wide monitor. It helps to know how many pixels your card is pushing. I think most of us could get 100+ fps at 640x480 or some such. :P

**Comment by PaulSJ** [comment]
I guess it depends how much detail is in a "recommended" map, since thousands of objects will bring even the best cards to their knees. 

I think this highlights a problem we have compared to standalone games, they know what their most demanding level is, but we aren't limited because users can add as much as they want.

I haven't had any problems with the example levels with the 5700XT (at 1440p), so I could get behind the recommended level being the 5700XT / RTX 2070

**Comment by ArgentArts** [comment]
However, I can zoom around Island Showdown with my old GTX 1080 ti in real-time in the editor view port ... so, there's that. Again, ultra-wide at 3440 x 1440. I would say that if TGC is using this as a demo, it's in the range of what's "recommded". If my card can handle it, then they shouldn't "need" a 2080 at minimum to get recommended results. Just my opinion. ;)

**Comment by 3coms** [comment]
NVIDIA GeForce RTX 3090 - 1.700 dollars, too much for the pocket. :)
Running GFX 1060 and getting 60 fps in huge maps.

**Comment by AmenMoses** [comment]
Has anyone done any profiling to figure out where the bottlenecks are?

Possibly now you have some demo levels to play with you can find the one with the poorest frame rates and profile with it.

With Wiz of Ids Snowy Mountain Stroll I'm seeing 30 FPS at points on the map with an RTX 2060 @ 2K resolution (not to mention humongous loading time with SSD).

**Comment by LeeBamberTGC** [comment]
@AmenMoses We have improved the nav mesh generation for this weeks build, more to do but much better.  Most of the team will also be switching to profiling too, and get at those low hanging fruit, using our demo levels as the primary source of sub-60 fps on min-spec. We have larger plans for more aggressive handling of things like 1000's+ object rendering, but that is for after EA. For March we will have all demos running 60fps+ on the min spec. That is the goal :)

**Comment by OldFlak** [comment]
**MINIMUM CONFIGURATION**
Perhaps the minimum specs need to be higher.

On a system with better than current default specs at 1080p, a 1km outside map can still be as low as 35 fps with nothing other than default tree\grass, and a start marker, and can even have 60 fps but experience severe player movement in places. 

**RECOMMENDED CONFIGURATION**
Not sure MAX can boast enough to warrant that.

With state of the art hardware you would expect state of the art rendering - which wicked can do - but much of which is turned off or not implemented in MAX.

**Comment by plemsoft** [comment]
We should base the min, GPU on G3D-Mark:
![g3d-mark](https://user-images.githubusercontent.com/18662417/156721702-7e54a0a8-537a-4c38-8acb-bf37cf66831e.jpg)

Card around 9600+ should do.

About min. dedicated GPU mem , tested this with our current added demo games. using a 3GB card one of our demo's produced GPU swapping , switch escape , lowering the point light resolution from 1024->512 made the fps on this level go from 9.1fps to 60fps, this indicate that it was swapping on a 3GB card, so i suggest this is the lowest dedicated GPU mem.

Sure we will start to optimize now , so im sure the min, 3GB will be fine in the end.

min. CPU i suggest i5-7400 or CPU with 5600+ marks.
![cpumark](https://user-images.githubusercontent.com/18662417/156723730-cc748eed-9eda-4558-bef4-7e590c80fa20.jpg)

Min. system ram. we can base this on out current demo games and mem use.

Escape from the Zombie Cellar: Peaked at 5.8 gb. (8gb system mem min.)
Island showdown: peak 8.5gb (12gb system mem min.)
Jungle fever: peak 10.6 (12gb system mem min.)
River rider: peak 8.2 (12gb system mem min.)
switch escape: peak 7.3 (12gb system mem min. , might run on 8gb but would be at the edge where it could crash).

So with out current demos i suggest 12gb min. system mem. , or if set at 8gb the demos should display the min. required in the description.

**Comment by jbthenext** [comment]
Feel like the supported OS being listed as Windows 10 may indicate a lack of support for Windows 11.

I would suggest changing both to Windows 10 or later (64-bit versions only)

**Comment by ArgentArts** [comment]
Why did the minimum RAM take a hike from 6GB to 12? Does someone really need 12GB to actually run MAX for a low-spec, minimum PC? And didn't you sort of promise that MAX would run as a minimum on a 970? Personally, I don't mind the hike in the video card, but there are early adaptors that bought MAX based on you stating that they could run it on their older video cards. Now you're going to tell them that they're going to need a 1060 as a base?

**Comment by LeeBamberTGC** [comment]
@ArgentArts Updated to GTX 970, there is not much difference in performance. The 12GB was due to the current largest demo needing 11GB as of today, can drop this once we have memory under tighter control.  Anyone who pre-ordered due to early specs during development, I am sure we will refund them, the GTX 970 was only ever a guide as the software did not exist at the outset of the development to know for sure.

**Comment by ArgentArts** [comment]
Frankly, anyone who does not have at least 16GB should not be trying to develop a game. Windows will eat up the first 8 or so anyway. ;)

**Comment by Retrogamebloke** [comment]
A 1060 is barely faster than a 970, unless the vid mem is pushed too hard and it needs more than 3.5 gig (the last 512mb is a slower memory type. Nvidia cost cutting :( A 970 should be able to cope with Max's graphics quality pretty well as long as you don't go overboard with objects and effects.
Minimum spec sound ok here. I actually remember when the 960 was minimum :)
