### ISSUE TITLE
MAX - 2022.03.04 - Decals Incorrect Color

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2379]
The center portal in this shot is a decal - the decal texture is blue not white

![image](https://user-images.githubusercontent.com/12246318/156685566-b5ff82ab-49dc-4ca8-933a-5e41a61fd28b.png)

**Comment by ZakJudges** [comment]
Hi @OldFlak, would you be able to send me the model so I can try to reproduce this? My email is: zak@thegamecreators.com

**Comment by OldFlak** [comment]
@ZakJudges Hi Zak, thanks for looking at this.
The decal didn't have the texture applied to the Emissive channel, deleting and adding the model to editor again fixed the issue.
Was a little strange that is had not been edited, and was working in previous builds, although I had not opened that level for some time, so no idea which build it glitched out on.

Tis ok to close thanks.

**Comment by ZakJudges** [comment]
Hi @OldFlak, thanks for confirming. There was some work done to the saving/loading of decal materials a couple of weeks ago. At a guess, I'd say that it might have caused an issue, with it being an old map. I'll close this issue, but if it happens again feel free to re-open it :)
