### ISSUE TITLE
Further Improve speed of standalone Nav mesh generation

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2380]
**Level Editor**
When you are in the Level Editor the first time you run test-game it takes a while to build the nav/physics, the next time you run test-game it instantly loads the level.

**Standalone**
In Standalone there is still the noticeable delay while it build the nav/physics - it is same as the first run in the editor.

**Comment by OldFlak** [comment]
Some vids in 2022.03.11 for more info

On first run or any edits the editor has the delay to build nav/physics
On consecutive runs it is instant as it has built the nav/physics and saved it out, and can then load it instantly
Editor:
https://youtu.be/Y9eKSuySL-A

Standalone does not use the saved out nav/physics
https://youtu.be/tN82K8i_Up8

The level has already loaded, that's why the in-game start screen is appearing - There is an added delay while it builds the nav/physics

It should not display any of the Game level until it is ready to play and should use the optimized nav/physics in the standalone

**Comment by LeeBamberTGC** [comment]
@OldFlak Already made some big performance improvements with nav mesh generation, marking as an enhancement so we can look to find even more speed.

**Comment by OldFlak** [comment]
Hi Lee, yeah I think this is much better than when I first created this issue.
Will close it as it, and wait for performance work later down the track :)
