### ISSUE TITLE
MAX - 2022.03.04 - Ambience Not Playing In Standalone

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2381]
We had this before and it was sorted but tis back again, only this time it is random.

Ambience does not play in standalone builds - random - some levels will some won't.

**Comment by OldFlak** [comment]
Also not playing sounds assigned to DLUA scripts - random sometimes they play sometimes they don't

**Comment by ZakJudges** [comment]
Hi @OldFlak

> Ambience does not play in standalone builds - random - some levels will some won't.
I wasn't able to reproduce this. Is the file for the ambience copied to the standalone folder, for the levels that don't play it? :)

> Also not playing sounds assigned to DLUA scripts - random sometimes they play sometimes they don't
Same again for this, I couldn't reproduce. Are the sounds being used with audio zones, or from scripts unrelated to zones? :)

**Comment by OldFlak** [comment]
@ZakJudges Hi Zak thanks for looking into this 

The level where the ambience doesn't play is using Ambience Controls in Properties - this is file in custom folder location and is not getting copied over.

The scripts are attached to entities and have sounds in slot 0 and slot 1 and slot 2
- files in slots 0 and 1 reside in the custom folder location, some get copied over some don't
- files in slot 2 (stock) are copied over but do not play

It all works fine in Test-Game, and in all versions prior to February worked in standalone

**Comment by ZakJudges** [comment]
Hi @OldFlak, thanks for getting back to me. Would you be okay to email me the project that is showing the issues? If so, my email address is zak@thegamecreators.com

Also, are there any differences in file paths between sounds that get copied over, and sounds that don't? :)

**Comment by OldFlak** [comment]
Hi @ZakJudges 

> Also, are there any differences in file paths between sounds that get copied over, and sounds that don't?

Yes the files are located in Custom writable Area (Drive D on my system) and are organized in various folder

___

The ambience files are in one folder - for one level it is copied over for another level it copies over the wrong file.
___

As for the audios files not playing when called by script:
After messing around for a bit I think the issue with sounds not playing when called by script is that unless the audio is referenced via the DLUA script so that the slots for them appear in Behaviors section, they usually don't play and it is these ones that do not get copied over to standalone.
- it is also doing the same in the editor

**Comment by ZakJudges** [comment]
Hi @OldFlak, apologies for the late response! I have recently fixed a few cases of files not being copied over to standalone, which should also include files specified via scripts. If you continue to experience the files not being copied over to standalone, could you send me a script that shows the issue? My email is zak@thegamecreators.com. Thanks :)

**Comment by OldFlak** [comment]
Will do - have not built a standalone for some time now, to much broken in MAX atm - but may get time today or tomorrow to test.

As a side note:
proper project system would fix all standalone issues and negate the need for pointers to files or to scan scripts for required any media
- everything in the game resides in it's own project folder
- copy everything in the project folder and add required runtime files
- done
Plus allows for good housekeeping under the hood :)
