### ISSUE TITLE
Autoflatten doesn't update with scaling

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2383]
- Place down a building with autoflatten
- Scale the building
- The flattened area will not update to reflect the scale until you select the building

**Comment by rvanner** [comment]
@ThomasJowett Because this is related to the auto flatten work you are on now, we're assigning this one to you.

**Comment by LeeBamberTGC** [comment]
Confirmed fixed in latest build.
