### ISSUE TITLE
AI can walk in to each other, and blocking each other from moving

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2384]
I set up a path of 5 flags, and had 3 enemy AI patrol between random flags, but i was finding after watching them that quite often they would walk in to each other, and blocking each other from moving any more.
Is it possible to add some kind of detection so they would walk around each other ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed patrol behavior so they no longer walk on spot when on a flag and can see the enemy:

![image](https://user-images.githubusercontent.com/35840583/158835691-96987015-f27b-4d92-a744-ca95b7d951ab.png)

All characters are able to move about, no one gets stuck in latest internal build.

I appreciate there is better 'crowd control' systems we can use, but that will be a post EA and a new issue with perhaps a nice video link showing a good way to do it.

**Comment by ZakJudges** [comment]
Fixed in latest build
