### ISSUE TITLE
Terrain artefacts when viewed from a distance

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2386]
To reproduce:
- Sculpt terrain using ramp mode with a decently large brush size
- Move the camera far away 
- See the artefacts appear as the terrain transitions from one LOD to the next

![Screenshot 2022-03-04 115330](https://user-images.githubusercontent.com/32545391/156759212-3c067bf0-e1f4-4333-b630-8d019f111cb0.png)

As you move closer again, the artefacts disappear
![Screenshot 2022-03-04 115346](https://user-images.githubusercontent.com/32545391/156759202-5899abe0-a2b0-4357-8239-bb99810a26bc.png)

**Comment by ZakJudges** [comment]
After more testing, it looks like whenever you use the ramp tool to sculpt, the material map is not updated correctly. When viewed from a distance, the edges of the newly sculpted area have the wrong material.

**Comment by PaulSJ** [comment]
It's most likely the shadows, the shadow mesh is a lower detail than the visual mesh so when it has sharp transitions it can cause self shadowing artefacts

**Comment by ZakJudges** [comment]
@PaulSJ Ah, that would make sense. The material map being incorrect may be a separate issue in that case. What do you think?
![Screenshot 2022-03-11 134100](https://user-images.githubusercontent.com/32545391/157879226-59f2a514-a953-4386-8500-8d0a7ca2bb3e.png)
![Screenshot 2022-03-11 134119](https://user-images.githubusercontent.com/32545391/157879241-d7f648c0-fa0f-406e-a5c5-7d7d61ec3e1d.png)

**Comment by LeeBamberTGC** [comment]
Fixed many moons ago :)
