### ISSUE TITLE
HUB: Change the Demo games list to match how the My games section displays the games

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2389]
Currently looks like this;
![image](https://user-images.githubusercontent.com/1503593/156764871-de5b834a-cd65-4442-b253-34df6eec4fcb.png)

Change to look like this:
![image](https://user-images.githubusercontent.com/1503593/156764931-0457a5ba-57d0-419b-b594-415470d88b2e.png)

**Comment by plemsoft** [comment]
@rvanner Fixed and ready :)
