### ISSUE TITLE
Storyboard: NEW Controls section

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2395]
The menu system is missing a controls advice screen. New users will not know what keys to use and so we really need to add this in to help all users.
![image](https://user-images.githubusercontent.com/1503593/156770561-ab9e416d-a03b-4d11-9fe1-eb73058eb4ed.png)

![image](https://user-images.githubusercontent.com/1503593/156770604-d4b181de-b681-4b7a-a39a-1f64b8a3b8c2.png)

Have these options that can be modified and moved around this screen:

Movement
W - Forward
A - Strafe Left
S - Back
D - Strafe Right
Mouse - Look Around
Space - Jump
Shift - Run

Weapons
LMB - Shoot
RMB - Aim
Alt - Melee Attack
R - Reload
1-9 Weapons Slots

Actions
F- Flash Light
E - Use

Esc - Menu

**Comment by rvanner** [comment]
When the above is added, please add a new option to the Loading Level Screen;

"When in game, press the Escape key for controls and other settings."

**Comment by plemsoft** [comment]
@rvanner Fixed for next build :)
