### ISSUE TITLE
MAX Application Focus

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2396]
Allow MAX shared focus when first loading, only restrict when in Editors. Currently the system waits until it has the focus to load up or loading levels which is annoying.

**Comment by LeeBamberTGC** [comment]
@rvanner Added code that will prevent the 'inactive mode' for 45 seconds during the launch sequence, long enough for the lowest of systems to get you to the intro/hub area of the software.
