### ISSUE TITLE
HUB: How it plays the games

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2397]
When you play a demo game or one of your own games:

- Skip the standalone message, this should not appear

When the game is quit:
- Return to the Demo game menu where you started from
- Don't show the intro video
- Don't show the storyboard

**Comment by plemsoft** [comment]
@rvanner Fixed for next build :)

**Comment by rvanner** [comment]
@plemsoft When quitting the game, the user should come back to the My Games section in the HUB. Currently you come back to the Storyboard. You should come back to where you started the game.

**Comment by plemsoft** [comment]
@rvanner Not here works fine ? , please try again , perhaps you tested before the commit was in the build ?
