### ISSUE TITLE
Terrain Generator: The Generate Terrain button is too small. 

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2399]
Make the button 100% taller and change it to read as:

Generate Terrain and
Open the Level Editor

Help text should read "Generates the terrain for your level and takes you to the Level Editor"
![image](https://user-images.githubusercontent.com/1503593/156772403-4b2a0955-bd95-400d-940c-c3b66c3de705.png)

**Comment by ArgentArts** [comment]
I would change the color, too, to make it stand out as the last thing that needs to be done to move on.

**Comment by plemsoft** [comment]
@rvanner Fixed and ready :)
