### ISSUE TITLE
MUSIC.LUA is not playing my custom music OGG files

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#24]
This is the modified script that is placed in the scriptbank, and the music OGG files are stored in audiobank\world\

[musicLUA.zip](https://github.com/LeeBamberTGC/GameGuruRepo/files/1635847/musicLUA.zip)

Once I have assigned this script to a dynamic entity set to Always Active, and assign the second script inside a marker zone to trigger the music setup above, nothing happens.

**Comment by LeeBamberTGC** [comment]
I  used your music.lua and amended it to point to the available atmospheric OGG files, then created a simple level that triggers music track 2 to play when entering a zone (attached). All works fine.  If you submit the OGG files you are using this might reveal why you are not hearing anything.
[musicandtrigger.zip](https://github.com/TheGameCreators/GameGuruRepo/files/1787099/musicandtrigger.zip)
