### ISSUE TITLE
New Beta Issue 25 May

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#240]
I know its under NDA so I will just post a link to the thread on the beta board not sure if you read the beta threads anymore https://forum.game-guru.com/thread/219710#msg2600880

**Comment by LeeBamberTGC** [comment]
For internal beta issues, you can email me directly at lee@thegamecreators.com to ensure all issues are caught before we move to the PublicPreview builds.
