### ISSUE TITLE
GG Max - Bug - After copying old project then saving something new in project it disappeared

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2407]
As the title says.
I copied a simple project over from the previous version of Max.
Was working fine, But after adding 1 new character Ally to the game, then resaving level, now when i reload Max, the level is empty and starts on the Terrain Generator mode.
The level is still in the Mapbank folder, and worked fine prior to the Save.

**Comment by plemsoft** [comment]
@Tum1370 There was a bug in converting old project in the old build , could you repeat this process in todays Friday build (when released) and let me know if the problems is also fixed for you , thanks for your help :)

**Comment by plemsoft** [comment]
@Tum1370 Thanks for getting back :)
