### ISSUE TITLE
GameGuru MAX - Snapping Not Quite Perfect

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2408]
Something is a bit off with snapping. It's not quite perfect. In the following example, the floor tile is exactly 30 units long and snapping is set to 15. Each piece should snap perfectly together and, in most cases, they do. In the following example close-up, you cannot see the seam between the tiles:

![snapping0](https://user-images.githubusercontent.com/36735507/156852519-ab9eac27-da1c-4f46-81d4-e8f3bf0c4c86.png)

But in some cases, you can see a seam. Sometimes it's very slight:

![snapping2](https://user-images.githubusercontent.com/36735507/156852594-521e1802-e8e3-49b0-a786-34c0eb0ace27.png)
 
But other times it's a bit more severe:

![snapping1](https://user-images.githubusercontent.com/36735507/156852626-91584d47-6c71-494d-9d4d-39c43989d501.png)

In this last case, the tile even looks raised up slightly.

Snapping should always work perfectly and should never produce seams when there aren't any (as in the first screen shot). These tiles, in other game engines, tile perfectly, and should do so in MAX as well. And they do ... most of the time. So, there seems to be a slight issue with MAX's snapping.

**Comment by LeeBamberTGC** [comment]
@ArgentArts We do round XZ (and now Y) to the nearest units of 5, could this be it?

**Comment by LeeBamberTGC** [comment]
NOTE: Also related issue here with video: https://github.com/TheGameCreators/GameGuruRepo/issues/2327

**Comment by ArgentArts** [comment]
@LeeBamberTGC Not sure, to be frank. I don't know enough about it. I've not looked this in some time, but do need to revisit it. I've been creating tiles that hide these areas so that there's no way to see any possible seams. But, out of curiosity, why are values being rounded to 5? That seems like a strange value to use to me.

**Comment by rvanner** [comment]
@ArgentArts I think it would really help if you can send Lee a small level with a few of the models you are using so he can see it.

**Comment by ArgentArts** [comment]
@rvanner I've attached a link to a level showing the issue (see post above) for Lee. I hope it helps.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Fixed for the new build now up on the EXPERIMENTAL build on Steam, works nice now when in smart snap mode.

**Comment by ArgentArts** [comment]
@LeeBamberTGC  Yes, works a treat in smart snap mode, but still can produce a seam when in normal snapping mode:

![aling3](https://user-images.githubusercontent.com/36735507/164483591-ec3e2256-4bfe-4cc7-9e57-1458993a969b.png)

In the above case, the first three tiles snapped well, but the fourth was off. I deleted it and snapped it again and it was better (than the screen shot above), but still off. 

In my opinion, if MAX is going to have a snapping mode (other than the smart snapping mode), then it needs to work, too. These modular pieces are built to work and snap together and they do ... most of the time. ;) Why can't they work all the time regardless of the snapping mode?

**Comment by LeeBamberTGC** [comment]
@ArgentArts What do you mean when you say "normal snapping mode".  When in the grid snap mode, smart position aligns all three axis XYZ horiz only does XZ and vert only does Y.

**Comment by ArgentArts** [comment]
Sorry I wasn't clear. Hadn't had my coffee yet. ;)

When I use GRID POSITIONS, I can still get the error:

![snap](https://user-images.githubusercontent.com/36735507/164485857-04ebb5b9-d918-4334-8a5c-acd408fa704d.png)

But when I use SNAP MODE, I haven't gotten the alignment error yet.

**Comment by ArgentArts** [comment]
@LeeBamberTGC BTW - Looking at my screen grab of the error, it looks like an error in the Y direction to me.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Fixed for next build, up in about 30 minutes :)

**Comment by ArgentArts** [comment]
Looks beautiful now! Totally awesome fix! Thank you so very much!!!
