### ISSUE TITLE
GGMAX - Screen Display Bug

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2409]
The loading of Max hub is rediculously large on a wide screen
![wide_screen](https://user-images.githubusercontent.com/95015657/156858803-e119c338-da58-4e7f-b0f3-c81df966b9af.jpg)
Now these icons are HUUUUGE im not going to miss clicking those
![huge](https://user-images.githubusercontent.com/95015657/156867210-345f8466-9800-4dd4-bc11-4eb9630c84f7.jpg)

Can we have an option to have a more controllable windowed option for this screen
![better_screen](https://user-images.githubusercontent.com/95015657/156858852-e7d3ecd3-91e2-4586-a8bb-01760ce41c68.jpg)

Thanks guys I know you have a lot to do but it looks a bit off  as it is and wide screen scenarios have to be catered for as well.

**Comment by ArgentArts** [comment]
How wide of a screen do you have? I have an ultra-wide (3440x1440) and it's not that bad:
![screen](https://user-images.githubusercontent.com/36735507/156860211-4b8c9b00-37cf-43a9-a80f-f3fe629ef062.png)

**Comment by Necrym59** [comment]
5120 x 1440

**Comment by ArgentArts** [comment]
Do you have the Odyssey G9? If so, how is it?

**Comment by Necrym59** [comment]
Yes its the Sammsung Odyssey running at 240hz and its "awsome", i need the screen real estate for the graphics and programming stuff i do, not to mention any games which play fantastic.

**Comment by ArgentArts** [comment]
I know this isn't a forum, so this will be my last comment on this - I had thought about getting one myself (have a 34" ultra-wide at the moment) because I do 3D and 2D graphics myself. But haven't pulled the trigger yet ... plus wanted to wait for the price to come down on video cards. Glad to hear you like it. :)

**Comment by Necrym59** [comment]
Since all the "Thumbnails" on the left have inbuilt videos/description even thought the layout is questionable,  what is the point of the large photo on the right. Better to turn this in thumnails and descriptions only, fitting more on screen. The descriptions should go below each thumbnail it loos too disassociated with the image at the moment.. A possible layout adaptible to screen sizes would be thumbnail/video/descriptors approx 3 or 4 across and an unrelated changing screenshot area to the right for Create New Game. Example here
![possible_layout](https://user-images.githubusercontent.com/95015657/157102335-4906fca6-eeaa-42ab-85bc-5415cb61b933.jpg)

**Comment by rvanner** [comment]
Now that it's displaying on your PC okay I will close this issue. Thanks.
