### ISSUE TITLE
GGMAX - Texture Problem

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2411]
Terrain Material 7 has a problem
Image here of it applied to a couple of objects and also sprayed on the ground, as you can see it doesnt spray well on the terrain???
![mat7](https://user-images.githubusercontent.com/95015657/156863371-eb722466-5b00-41ee-96ee-4f6ec99cd28d.jpg)

**Comment by PaulSJ** [comment]
Duplicate of #2473
