### ISSUE TITLE
Story Board fonts not currently working in Standalone.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2415]
Created a Standalone last night and the fonts selected are not showing up.
They are copied over but all i see is the default font on the menu. 
The font i used in the creation of the menu was **OFLGoudyStMTT.ttf**

**Comment by ZakJudges** [comment]
@synchromesh62 Thank you for reporting this issue. I've added a fix which you should see in tomorrow's build :)

**Comment by ZakJudges** [comment]
Hi @synchromesh62, could you confirm if this issue is now fixed for you? Thanks :)

**Comment by ZakJudges** [comment]
Thanks for confirming, closing this issue
