### ISSUE TITLE
GGM - Zombie / Animals getting held up by others

### ISSUE THREAD

**Issue by ivanski1983** [TheGameCreators/GameGuruRepo#2419]
Zombies and animals get stuck behind each other as in the video below instead of finding a way around.

https://youtu.be/idJnbh0jv18

**Comment by ivanski1983** [comment]
Also zombies and rats get hung up on others that do not spawn at start

https://youtu.be/KFK6BrG3WAE

A zombie that was set not to spawn at start was placed in front of this zombie in the video

**Comment by LeeBamberTGC** [comment]
@ivanski1983 New internal build will no longer prevent progress along navmesh if the blocking object is not active (spawned). They still prevent overlap if they are active and visible as designed. Also updated overlap code so 'non repel' characters like rats can pass through repellers, so rats can move freely through regular characters (i.e. under their feet).
