### ISSUE TITLE
Dynamic entity has no collision for bullets.

### ISSUE THREAD

**Issue by gg-Anubis** [TheGameCreators/GameGuruRepo#242]
My dynamic entities (animated stuff) do no register a bullet hit.
And enemy soldiers can shoot right through the (animated) door(/entity), even when it's closed.

I doesn't matter if i used the door (once) or not. If i don't trigger the door from opening, i cannot walk through, but bullets will.

**Comment by LeeBamberTGC** [comment]
Can you attach a small FPM level using stock assets and a small step by step to describe what I should do to reproduce this bug?  Maybe take one of the animating doors from the stock library and use it with a small level and start marker, thanks.

**Comment by gg-Anubis** [comment]
[dynamicdoortest.txt](https://github.com/TheGameCreators/GameGuruRepo/files/2048404/dynamicdoortest.txt)

Renamed to *.TXT, you need to rename back to *.FPM

Simple layout.. 1 dynamic door, a wall, a soldier and startmarker with attached RPG.

Do nothing, and you will get shot by the soldier.. door is still closed..

Shoot to the door (below halfway) and you will kill the soldier.. door still closed.

Shoot to the door (above halfway) and 'quickly' walk to the door to open,, and you will still see the rpg granate in the air..

**Comment by LeeBamberTGC** [comment]
All three scenarios fixed for next PP build - this relates to any model using the old pos/rot animation system and direct intersect collision checks.
