### ISSUE TITLE
Standalones seem to be affected by updates.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#2422]
I imagine it is probably something to do with the backup process on Max updates. Standalones that work fine from an older version lose the background menu images after an update. I never copy the files across to the Max folder manually, just grab them from in Max. After updates the standalones seem to lose the images and show a default terrain that shouldn't even be there.
![image](https://user-images.githubusercontent.com/44620846/156932088-4211402f-cfce-42d2-a28e-ceb85b2a5d25.png)
This is on first running a standalone after an update.

![image](https://user-images.githubusercontent.com/44620846/156932113-d8ddd579-745d-4cd4-ac6d-a6ba0eb3ec70.png)
This is after running the game and going back to main menu. It keeps the last view seen.

![image](https://user-images.githubusercontent.com/44620846/156932152-06767eb4-438d-4a2b-b76f-2543b623e0ed.png)
This is when reloading standalone up again after the first run. Textures are now working but still stuck under a terrain that looks like a default one.

Now in one way I actually like this one. If it loaded the correct level for game and could be positioned properly, would make a great animated menu system. On the other hand at the moment it seems to be wasting time and resources loading a default map that is not used at all. I also briefly see the default map pop up after loading the game (just for a brief moment) and that is in Max editor as well.

https://user-images.githubusercontent.com/44620846/156932762-640b1515-7195-42b9-9255-b4e1aca113c3.mp4

Quick example of how it can look and look okay :)

**Comment by ZakJudges** [comment]
Hi @Retrogamebloke 
After the most recent update, the updater should no longer alter the writeable folder which should solve this issue :)
