### ISSUE TITLE
GameGuru MAX - BUG - Importer Does Not Replace Existing Properly

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2424]
When Re-importing an object to replace it (due to making corrections, updates, etc.), the importer does not properly replace the model. Here's a video:

https://user-images.githubusercontent.com/36735507/156932729-64abed92-82c9-4038-90ac-6385d15d57ae.mp4

In this video, I used the same model, but with different textures/material applied (yes, differently named). I made sure the model was named the same as that which I wanted to replace. The importer asked if I wanted to replace it, overwriting the old one. I clicked yes and proceeded. Nothing changed in the MAX view port. However, after exiting MAX and restarting:

![replace2](https://user-images.githubusercontent.com/36735507/156932841-ea63e27c-965d-48ec-a5f4-fa188685a693.png)

The model was changed (as can seen above) because the new model showed up with the origin in the ground (like in the importer), but the old material was still applied. So, even though I had imported a new model to replace the old one, it kept the old material/textures, even though it changed out the model. 

I believe that the material/textures should be changed, too. This would allow the end-user to update their level if they need to make changes without having to go through and manually replace each piece. If they'd previously placed 100 pieces that now need to be changed, simply importing the new version and letting the importer overwrite it would be ideal. Having to manually replace all of them would not.

But even if you try to replace the model with an identical model with identically NAMED textures/material, the importer will show it correctly, but it WON'T overwrite the material. As a result, MAX will keep the old material no matter what:

https://user-images.githubusercontent.com/36735507/156933280-bb8311ce-f0d2-4460-beac-c083241537ae.mp4

As you can see in the above video, I wanted to replace the brick sphere with the same brick sphere, but with the red "X" painted on it. The importer shows the correct textures. It asks if I want to overwrite the original file. I click yes to proceed. Yet, the screen shot it makes does not show the "X" and the sphere that ends up in the view port does not have the "X" because the importer did not overwrite the material. It's like it looked and said, "Oh! There's already a material here! Why make a new one?"

This means that I cannot update my models and materials without having to do it manually for each and every one. If the importer would just overwrite EVERYTHING when I click YES, then this would make it simple for the end-user to update all assets used in a level that needed to be updated.

**Comment by ArgentArts** [comment]
For just changing the material, I realize I could click on the entity, go to the Materials tab, and make changes there. But that brings up another issue. From what I've seen, that only affects the ONE entity and not all of them (as it should). So, if I need to fix or replace the material on 100 placed items, that's going to be a pain.

Secondly, we are now dealing with a Surface material, but we originally used three individual textures for Roughness, Metallic, and Ambient Occlusion. Instead of just replacing these, the end-user would have to find a way to create a Surface material when they already have their corrected textures. Why, when they can simply re-import their model, have the importer replace the model AND the materials and be done with it?

Level design and building is a fluid thing. Changes happen ... a lot. Having the importer overwrite both the model and the textures/materials would go a long way toward helping us create our games.

**Comment by synchromesh62** [comment]
I have been updating my level a lot , Re-importing and having to replace the one on the map as like you it does not replace it.
Conclusion ... 
All the settings i think are saved to the Map file and not the .Dbo or .fpe 
Its the only thing that makes sense of it all.

**Comment by ArgentArts** [comment]
Yeah, this really needs to be fixed. It's a PITA to have to replace each piece, one by one, on my level.

**Comment by synchromesh62** [comment]
> Yeah, this really needs to be fixed. It's a PITA to have to replace each piece, one by one, on my level.

Its actually quite clever i will give them that but most certainly not ideal for the reasons above :)

**Comment by Granada1** [comment]
Me to , same problem with my latest experiment

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio A short while ago the hot swap system was improved that detects changes to entities while you are still in the level. I tested just now and it seems to work fine, no movement of the model/object and the texture swapped in just fine:
Before:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b8f1f7e6-9ab4-4a8c-bc3f-b4805eb4fd99)
After:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2d1f73e4-6893-4efa-b94a-63462e79f3b6)

Notice the tape on the cardboard box, lining up with the R in the sign, no shift in position. Try in current EXP build and confirm the fix, thanks!

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC 

Try this to see how well this works:

- Import an object (model with textures/materials) into MAX and give it a name like, Test1
- Save the object
- Create and save the thumbnail
- Place the object in a level and save
- Import a completely different object (different model from the first object with it's own textures/materials) and give it the EXACT same name as the first model (in this case, Test1)
- Save the object in the same place as the first model
- Click YES when MAX warns you that the model already exists and if you want to replace it
- Create the thumbnail and see that the thumbnail offered you is from the FIRST MODEL with no way to create a thumbnail of the newly imported model (not without exiting MAX and deleting the old thumbnail)
- Look at your scene and see that the originally placed model has NOT changed at all (it's the same model and textures as the first imported model)
- Save and exit MAX
- Restart MAX, load the level, notice that the NEW model is not there BUT the OLD textures/materials are being used.

So, there are a few things going on here:

- The newly imported model of the same name is NOT being shown in the editor without a complete restart of MAX
- There's no way to update the thumbnail without first deleting the old thumbnail that was generated. 
- After a restart, the new model finally does show in the scene, but has the old model's textures applied.

This last bit, I am guessing has to do with the FPE for the model. I am guessing that MAX has correctly replaced the old .dbo file with the new one, but the FPE is not being regenerated to target the new textures.

Here's an example:

Let's say the first model is Box1 and has the following textures:

- Box1_albedo
- Box1_Normal
- Box1_Surface

Now we want to replace box one completely in our game. So, we import a model called Open_Box_02, but when we import it into MAX, we change the name in the name field at the top of the importer to Box1 so that it will replace Box1 with Open_Box_02. This model has the following textures:

- Open_Box_02_Albedo
- Open_Box_02_Normal
- Open_Box_02_Surface

We accept the dialog to replace the original Box1 when we import the new model, but a new FPE is not generated. So, Box1.fpe is looking for:

- Box1.dbo (which it finds, but it's been replaced by the second model, Open_Box_02 - renamed to Box1)
- Box1_Albedo
- Box1_Normal
- Box1_Surface

This is incorrect because the NEW Box1 has different textures. Thus, the FPE needs to get replaced or updated to reflect that.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio The new EXP build improves the ability for the importer to refresh entities at the right time, including when one is entirely overwritten and a new thumbnail is created.  Let me know how it goes :)

**Comment by LeeBamberTGC** [comment]
Custom material choices are retained per level and I do not reset them. Should I?

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC I think of it this way - If I've overwritten a model by importing a new one to replace it, selecting YES to agree to overwrite it, then it should replace everything. If it doesn't, then you end up with a mess when you have the old model's textures with the new model. If they are, for example, completely different models, then the UVs will be different. And if the UVs are different, then the textures from model #1 won't work on model #2, but will create a mess. 

When someone is overwriting something, I think they should realize that it means it will completely REPLACE what was there before. Else, no need to overwrite, but just import it as new (change the name) and go from there. ;)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC One possible reason for this to work this way (overwriting an object replaces both model and textures in a level) is to make it easier for level designers to simulate "greyboxing". Greyboxing is when you create a rough, playable draft of your level's play area using temporary models. This allows the developer to test their level to ensure it works as intended (i.e. the player can make the jumps, doesn't get stuck somewhere, can complete the level in reasonable time, etc.). Once the greyboxed level passes, then the level designer can start to replace the temporary models with permanent ones.

Often temporary models used in greyboxing are simple objects. But if those objects are named appropriately, then swapping out the temp geometry for permanent geometry is as easy as importing and overwriting the temp model with the permanent one.

Let's say that I have created several areas where the player needs to jump across a broken bridge. The broken bridge model is named Bridge_Broken_01. The greyboxed model is super-simple, but occupies the correct space to fit where it does and the gap is such that we could test to ensure the player can jump it, etc. After passing muster, I could then overwrite Bridge_Broken_01 with the final model, replacing the model object and textures. Doing so would save a heck of a lot of time. If I had three or four of these bridges in that level, then all of them would get replaced with the final model (i.e. the greyboxed bridges would get removed and replaced by the final model created for this purpose). 

With MAX as it is now, we would have to go through the level, delete each temporary bridge model, drag in the new one, and reposition it. If the greyboxed ones were already positioned as I wanted (proper height, orientation, etc.), then simply importing the new model and overwriting the old would just replace them exactly where they are, same orientation, etc.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC BTW - this could be a tickbox in Advanced. That way, the average user isn't going to overwrite and replace stuff they don't intend to.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio We will go with your suggestion and ensure the refreshed swapped in object does not carry any custom material changes forward as it has an equal chance of a mess occurring:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/3faec96a-3447-4d77-af78-1085888c4a25)
Will be in the next EXP build then we can close this one.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC From my early tests, this seems to be working wonderfully! Thanks for this!
