### ISSUE TITLE
[GG Max] Strangeness about Ally AI

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#2425]
When they go under water (for some reason), you can see their naked faces... Except when you're underwater too. And they don't drown, from what I've seen.

![soldiers faces](https://user-images.githubusercontent.com/12373041/156938778-7287a8f5-e45c-4a02-b2b5-835ebc3fec12.png)
![soldiers](https://user-images.githubusercontent.com/12373041/156938781-42cb2afc-4515-4fbe-b231-0aa0eae7c371.png)

**PLUS**: If you go a little far, they stop following you and you lose them. This may be an AI enhancement question.

**Comment by ZakJudges** [comment]
Hi @thecyrus, the issue where the soldiers headgear disappears underwater should now be fixed. Could you confirm if that is the case? Regarding the other issues, we have more development on the AI planned which will solve these issues :)
