### ISSUE TITLE
Massive FPS drop in test game with build 04/03/2022

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2426]
I'm having to rollback as this build has dropped my FPS from 60 to 10 in test game, editor seems unaffected.

![image_2022_03_07T08_23_20_802Z](https://user-images.githubusercontent.com/99803873/156996418-a153f50f-e8b0-4b63-a9d7-9eead98306ef.png)

i7-4770S @ 3.10 GHZ, 4 core, 8 processors.
RTX 2060
4GB Ram (This wasn't an issue with previous build.).

**Comment by LeeBamberTGC** [comment]
@davetgc Big performance boost for this weeks build.

**Comment by davetgc** [comment]
Hi Lee,

Just to let you know that it was the build 04/03/2022 that broke my
performance.

Thanks,

**Comment by ZakJudges** [comment]
Hi @davetgc, is the massive FPS drop now fixed for you?

**Comment by davetgc** [comment]
Yes, it is working.
