### ISSUE TITLE
GameGuru MAX - Bug - Switch Behavior - "E" Still There if No Text for On/Off Text

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2428]
The Switch Behavior allows the end-user to define the text they would like for turning the switch on or off, including having no text. However, if you opt for no text, then the "E" will still show up at the switch area:

![switch](https://user-images.githubusercontent.com/36735507/157070831-94b0f64b-51e6-4375-919a-26878c0fa8ad.png)

This is due to the way the LUA is structured since it will grab whatever the action key is set to. However, in many games you're not told to press a key to open a door. You just try and it either opens or it doesn't (many horror games work this way, for example) and having a message would ruin the fun of discovering which doors work and which don't, etc. In cases like this, no message at all is preferred. Therefore, it would be great to be able to remove ALL of the text message, if the end-user wants that, including the "E".

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I did 2 solutions to this:
1)- If there is no custom text, the prompt will not be displayed
[Switch Fix - Doesn't display prompt if there is no message.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8223052/Switch.Fix.-.Doesn.t.display.prompt.if.there.is.no.message.zip)
Changes: added and if statement that checks if the g_switch[e]['ontext'] && ['offtext'] have custom text before displaying on line 29 and 45.

2)- No hardcoded prompt text. This is in my opinion better, as it gives more flexibility for the user :]
[Switch Fix - No hard coded prompt.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8223059/Switch.Fix.-.No.hard.coded.prompt.zip)
Changes: Deleted hard coded text for each option when displaying prompt on line 30,33,35,44,47 and 49.

**Comment by ArgentArts** [comment]
This appears the be fixed in today's release. At least the "E" doesn't show up for me any more. :) Thanks! :)
