### ISSUE TITLE
Set birds to take longer before resetting to their initial position

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#2435]
Birds can appear almost right away back where they started, very spooky:

![image](https://user-images.githubusercontent.com/35840583/157078921-0731fab3-824e-4169-ac91-4d02d689547e.png)

**Comment by LeeBamberTGC** [comment]
@AmenMoses Yes that works great, you never see them 'appear' but when you turn your head and look back, there they are :)  I would have a timer which leaves it about 30 seconds before they can be placed back, that way they may be there if the player went somewhere and then came back to a previous location, but ideal;ly not when the player just turned around and happened to be a specific trigger distance away from the birdies :)

**Comment by AmenMoses** [comment]
[bird.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8200121/bird.zip)

**Comment by LeeBamberTGC** [comment]
@AmenMoses Many thanks, added this this weeks internal build.
