### ISSUE TITLE
Shift select (rubber band) a bunch of characters and hit delete key and MAX Crashes

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#2436]
As per title.

I have about 40 birds in a test level, rubber band selected all of them and hit delete and crashed out to desktop.

**Comment by AmenMoses** [comment]
Tried the same thing with only selecting about 10 at a time and it didn't crash.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Fixed in Friday build.

**Comment by AmenMoses** [comment]
Appears to be fixed.
