### ISSUE TITLE
Island Showdown tree LOD scale bug

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2437]
If you get close to the circled tree, a massive low poly version will appear
![InkedScreenshot 2022-03-07 120748_LI](https://user-images.githubusercontent.com/32545391/157206833-d562476e-e795-4537-97ed-a963ae0fcb08.jpg)

Here is the spawn position, in relation to where the tree is:
![Screenshot 2022-03-07 120902](https://user-images.githubusercontent.com/32545391/157206798-880c3564-dcb5-42d6-b6cf-6ed4947f9ed5.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Reproduce this in the Island Showdown level, and where you see these massive trees, you can go in and replace the trees, when they are all sorted, save the level and that will be our new one, thanks!

**Comment by PaulSJ** [comment]
I think this was fixed before release

**Comment by LeeBamberTGC** [comment]
@PaulSJ That's great, @dllllllllllb Just needs confirming as fixed and then you can close :)
