### ISSUE TITLE
TPV - Right mouse button

### ISSUE THREAD

**Issue by gg-Anubis** [TheGameCreators/GameGuruRepo#244]
Right mouse button is (normally) used in First Person for Zoomscope (scope.dds in gamecore/gun dir).
But the engine also tries to zoom in while using Third Person.. With a short glitch of the zoomscope. And the main character turning him/herself to the mouse pointer.

I also see the character does animate for strafing.. using the RMB (keep pressed) and A or D.. but then the LMB does not work..  and a constant glitching of the zoomscope, but i can strafe while pointing my gun at the enemy, but i can not shoot since LMB does not work in conjunction with the RMB being pressed.

**Comment by gg-Anubis** [comment]
smallg gave me a new gameplayercontrol.lua and this fixed this issue.
Except for the strafing, still can't use LMB (shoot) while holding RMB (to Strafe using A and D).
But the glitching is gone. So is the speed change i mentioned in another Issue. (Speed change after 5.,25 update)

I renamed the *.lua to *.txt.. since .lua is not accepted on github.
[gameplayercontrol.txt](https://github.com/TheGameCreators/GameGuruRepo/files/2041676/gameplayercontrol.txt)

**Comment by gg-Anubis** [comment]
comment of smallg on the gameplayercontrol.lua

it is just a quick edit i did to check you're not in TPV when pressing the right mouse button but no it won't be in the new versions unless someone decides to add it.

**Comment by LeeBamberTGC** [comment]
This issue has been repeated.  Issue 241.
