### ISSUE TITLE
Flashlight error .. Latest internal build

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2440]
Obviously first thing i tried was my own level :)
Flashlight messes up when holding Weapon and corrupts when moving around.

Without Weapon
![WW1](https://user-images.githubusercontent.com/35708217/157240771-79e4ee8c-1bfc-4ba3-8532-adb8f7442439.png)

With Weapon
![WW2](https://user-images.githubusercontent.com/35708217/157240805-635c852a-1885-43f0-9cbb-527f3517828d.png)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
 i can fix my flashlight issues by resetting the visuals but the FOV has changed.
I need to put it back to the sweet spot for the jumpscares but cannot find the editor FOV slider (has it been removed ?
Really makes hell of a difference

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I do not think it was in the editor, it was always in the test level TAB TAB controls on the right. I changed it from 45 to 60, but if you set it to another value the level will remember it when you save.

**Comment by synchromesh62** [comment]
> @synchromesh62 I do not think it was in the editor, it was always in the test level TAB TAB controls on the right. I changed it from 45 to 60, but if you set it to another value the level will remember it when you save.

Oh what a pillock i am :)
Apologies of course your right it was always there i just could not find it :)
Thanks Lee that's fantastic and it seems its all working fine now but it was resetting the visuals that cleared the shadows and flashlight issues so anyone else i see getting the same i will advise :)

**Comment by ZakJudges** [comment]
Seems to work here in the latest build
