### ISSUE TITLE
Weapons Vanish on second level of a Standalone

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#2441]
All weapons and ammo collected on the first level now seem to vanish on second. Even weapons placed down in second level pick up and refuse to work. I have default on both levels set to unarmed. It used to work a couple of versions ago.

**Comment by ZakJudges** [comment]
Hi @Retrogamebloke, I wasn't able to reproduce the issue of weapons not working after being picked up. Here is what I did:
- Created two levels and placed down some weapons and a win zone
- Exported to standalone
- Picked up a patrol rifle, ammo and fired some shots
- Entered win zone to go to next level
- I was able to pick up and use weapons as normal

Are you still experiencing this issue in the most recent build? :)

Regarding being able to keep your weapons between different levels, I believe that the team will be working on a system for moving between different maps and retaining state, so this will be addressed in the future :)

**Comment by Retrogamebloke** [comment]
In the last build, weapons worked again as normal. Not seen this issue recently.

**Comment by ZakJudges** [comment]
Thank you for confirming. I will close this issue, but if it happens again feel free to reopen :)
