### ISSUE TITLE
Display Image in Zone Issue

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#2444]
Getting some odd ones here again. Image is garbled.
![image](https://user-images.githubusercontent.com/44620846/157302983-b533fabe-7000-4ef2-8779-f37b50fc6b54.png)
Screen shot shows both original image, how it looks in editor in behaviour section and how it looks in game. DDS image exported using GIMP.
![image](https://user-images.githubusercontent.com/44620846/157303396-14ada103-597d-4003-ad12-123a0e3b71ee.png)
Using those settings. But it does pick up and display in the behaviour section, so doubt it is the image.

**Comment by Retrogamebloke** [comment]
Since managed to have another look. Can't get the DDS image to work, but tried a .png and working as should.
![image](https://user-images.githubusercontent.com/44620846/157332713-87c2540a-c359-4947-8279-8b2dfb5f474b.png)
Be nice to know if my DDS settings were wrong. Tried all 3 types available in GIMP.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke For DDS, use DXT1 for best compression with one bit of alpha.  Failing that you can still use PNG as that allows you to continue editing a lossless image during development.
