### ISSUE TITLE
No Unarmed Player Walk Animations

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#245]
Noticed this for a few a while now. Figured it was time to put it out there :)

When played has no weapon the camera movement is smooth - there is no walk\run animations. Which just feels kind of weird. 

Reliquia....

**Comment by LeeBamberTGC** [comment]
Can anyone produce a small FPM and step by step which reproduces this issue, thanks!

**Comment by gg-Anubis** [comment]
No FPM needed here.
Start a new map. Place start marker, choose (any weapon) as a weapon.
Start the map, you will be there on an empty map, holding a gun.
Walk and notice you have a walk-animation/wobble.
Now press 0 (put away gun) and walk again.. wobble is gone.

Somehow the wobble is only there when 'you' got something in your hands.

**Comment by Granada1** [comment]
I think the wobble might be part of the weapon hud animation

**Comment by michaeloldman** [comment]
Just to add, all my test maps since using GG have been without weapons, and the walk\run wobble has always been there. It just disappeared recently, but can't say exactly which build it started with. 

Reliquia....

**Comment by Granada1** [comment]
That’s my idea out the window then 😟

**Comment by LeeBamberTGC** [comment]
The wobble is still there, it just got slower due to a bug. If you change Wobble Height to 1000 you will see the wobble remains. Fixed for next PP build so speed defaults to normal non-weapon (1.0) when not holding a weapon (i.e. weapons can have a modifier which slows down the players speed in scenarios such as carrying heavy weapons).

**Comment by michaeloldman** [comment]
Awesome - thanks Lee!

**Comment by michaeloldman** [comment]
Hi all :)
Monster update - awesome!!

Just a heads up on the player controls.

The walk wobble is back - great stuff Lee 👍 

However I just feel the player movement could have more work in that it feels like you are in slow-motion particularly the fall speed - should it not be faster? If we fell so slowly in real life we could get out a pen and paper and calculate the best way to land so as to suffer less injury (lol).

Now I know this stuff can be adjusted in properties, but I just feel it should be more realistic by default.

Reliquia....

**Comment by LeeBamberTGC** [comment]
I've switched this to a feature request, can you provide new default value suggestions you consider more real-world. Happy to change the defaults if I get a few community members agreeing with your new values :)

**Comment by michaeloldman** [comment]
Hi Lee :) 
Thanks for the response. 
I will have a play and see what I find best and let you know.

By the way when I re-posted here, I then noticed the thread was marked closed and figured it may just get hidden from the main issue thread, so I posted a new issue for it (#306) so sorry for the double up.

Reliquia....
