### ISSUE TITLE
Can see through walls, doors, sheds and furniture 

### ISSUE THREAD

**Issue by HannahIsCrying** [TheGameCreators/GameGuruRepo#2451]
I’ve been working on a game for a few weeks now and just out of nowhere now when I walk too close to walls, trees and sheds I can see right through them and onto the other side. This is a big problem because when in play mode and I’m starting off in a room in a house I can see through in other rooms or out into an empty world if I get too close. This doesn’t happen if I start off on a new flat level. It’s just happening in the game I’ve been working on for weeks now but wasn’t happening before. I don’t know why this is or how to resolve it.  

Link to clip showing what it looks like: https://www.youtube.com/watch?v=sHAV-140zu0

**Comment by LeeBamberTGC** [comment]
@HannahIsCrying Check your camera settings in Test Level to make sure you have not changed the near slider. A value that is too high will allow you to see through things.

**Comment by HannahIsCrying** [comment]
> @HannahIsCrying Check your camera settings in Test Level to make sure you have not changed the near slider. A value that is too high will allow you to see through things.

Thanks a lot! It's fixed the problem!

**Comment by ZakJudges** [comment]
This was confirmed fixed by the author, closing this issue
