### ISSUE TITLE
Test level memory leak

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2453]
To reproduce:
- Test a level (I used Island showdown)
- Exit back to editor
- Repeat a few times
- Note that not all of the memory that gets allocated when testing is released when coming back to editor

**Comment by GraPhiX-Guru** [comment]
Hello
I use GC.Collect in .net is there any Garbage collector in C++ or does it have to be done manually ? a simple Delete maybe?

**Comment by plemsoft** [comment]
@GraPhiX-Guru Sorry in c++ we are left on our own so yes deleted is needed :) , i take a look,

**Comment by plemsoft** [comment]
@ZakJudges Yes navmesh allocations do not free after test game, so first time you run it, it will have higher mem, but second time it should be the same (it free on second test game) , anyway when I get to it I will test it :)

**Comment by PaulSJ** [comment]
It looks like darkai_setup_characters() is calling WickedCall_RefreshObjectAnimations() which is creating new AnimationComponent objects which then triggers wiScene::Scene::RunAnimationUpdateSystem() to allocate memory when copying the backwards_compatibility_data with
```animation_datas.Create(sampler.data) = sampler.backwards_compatibility_data;```
This memory is never freed.
@LeeBamberTGC Hopefully this means something to you, if not then i'll dig a little deeper.

**Comment by LeeBamberTGC** [comment]
@PaulSJ MAX was developed during a time when Wicked Engine was overhauled, and animation data was partially moved.  The old implementation needed the old animation data for certain functions, so needed to be retained and accessed. It is okay if this data is created, and deleted when a new level is loaded, the data is however needed for both level editor and game for the object animations to work.

**Comment by PaulSJ** [comment]
Should be fixed in the next version
