### ISSUE TITLE
Problew with playermarker settings in standalone 

### ISSUE THREAD

**Issue by slaur3n** [TheGameCreators/GameGuruRepo#246]
In level1 ive set the speed to 100, and no starter weapon. Lvl 2 speed is 0, and starts With a gun. When exported to standalone, lvl1 settings are on lvl2 aswell. Help, huge problem for my Project.

**Comment by LeeBamberTGC** [comment]
This is intended behavior so that the player's weapon states can be carried over to whatever level they zoom into. To give players a weapon on level 2, just add it as an entity on the ground with ammo.
