### ISSUE TITLE
GameGuru MAX - Request - Player Start Without Flashlight/Torch

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2460]
Someone had requested this during the live broadcast today - to have an option where the player start without the flashlight/torch, but be able to find it later and pick it up. This would be great to have as a game element in MAX instead of the player permanently having a flashlight/torch.

**Comment by mav3r1ck1981** [comment]
@Kasseyus this has been implemented
