### ISSUE TITLE
GG Max - Bug - Smart placement of objects

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2465]
As you can see in the screenshot, When i try and smart stack the crate on to the ground, it appears below the ground level.
No matter how much moving around i do, the only way i can place it is by raising it myself above the ground level.

Some objects were placing ok, It only seems to effect certain objects.

![image](https://user-images.githubusercontent.com/66874403/157650011-44357f4d-90b4-477f-85b3-2674139f6de5.png)

**Comment by LeeBamberTGC** [comment]
Fixed in EXPERIMENTAL build.

**Comment by rvanner** [comment]
Tested and working with this crate box now!
