### ISSUE TITLE
GameGuru MAX - Bug - Object Jumps Back When Clicked with Gizmo

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2469]
The latest internal build seems to introduce a bug when using the gizmo. If you try to click on the gizmo and the gizmo is not directly over the model geometry (i.e. the model's center is not over or within it's geometry), the model jumps back away from the mouse cursor. In the video that follows, I am attempting to position a roof piece over a wall piece in one of my levels as a test. The roof piece is set up so that it's center is is on the ground so that it "floats" perfectly as high up as the wall. This way I don't have to try to snap it to the wall height. Here's a screen shot from within Blender to ensure I am making sense:

![ceiling](https://user-images.githubusercontent.com/36735507/157715278-18bd2ae1-909b-466a-84c1-f5003fb840f8.png)

And here's the video of what happens when I try to use the gizmo to position the ceiling piece:

https://user-images.githubusercontent.com/36735507/157715543-3b0074ab-d7b0-4a20-b218-4140d8ff159a.mp4

Initially, if I drag on the geometry, it's fine. But if I attempt to use the gizmo, the model jumps back away.

**Comment by ArgentArts** [comment]
Same as here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2511

**Comment by rvanner** [comment]
@ArgentArts Is this fixed now or does Lee still have work to do?

**Comment by ArgentArts** [comment]
Yes! Thank you! :)
