### ISSUE TITLE
Standalone game, Press F11 shows huds

### ISSUE THREAD

**Issue by gg-Anubis** [TheGameCreators/GameGuruRepo#247]
I do like the option of F11 in standalone to see my FPS, but it also shows the standard Huds, which i do not use and are normally hidden.

**Comment by HierToo** [comment]
@gg-Anubis  can you please test it again if this still exists? I can not replicate this bug.

**Comment by gg-Anubis** [comment]
@HierToo,
Not at home right now, or the coming days.
I will try later and let you know.

**Comment by LeeBamberTGC** [comment]
Fixed for next beta build.
