### ISSUE TITLE
Crouch behind a rock, the AI stops attacking

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2472]
Was just test playing and found that once in combat, and you stand behind a tree, or crouch behind a rock, the AI stops attacking.
Seems a bit dumb, and very easy to beat the AI.
Also, when in combat, can just back away and you lose aggro with the enemy. Seem to easy again.

EDIT: Also following a simple path between 2 flags that are on a watchtower they get confused and fall off.

EDIT 2: Also can we get AI to reset itself and run back to starting positions after it loses aggro.

**Comment by ZakJudges** [comment]
Fixed as of latest build
