### ISSUE TITLE
One of the Terrain texture in the desert biome is messed up!

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2473]
eg:
![image](https://user-images.githubusercontent.com/1503593/157737868-0bd2e418-82a9-480d-a3f5-d18d78b80a2d.png)

**Comment by davekirk85** [comment]
Isn't this because the slope is so steep that it auto changes it to rock texture? can't you paint back over it with sand?

**Comment by plemsoft** [comment]
@PaulSJ This texture is not working. "\Files\terraintextures\mat7\Color.dds" , the old BC7 version was not working it could not be loaded, we converted it to BC1 and it was working , but now it looks like this ? , do you have a BC7 version of this texture that are working ? , if so please sent it to @LeeBamberTGC :)

**Comment by GraPhiX-Guru** [comment]
Hi i have used one of my apps to correct this texture, please try this one
[Color.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8230111/Color.zip)

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks , but for some reason it to dark compared to the original ?
![terrain-to-dark](https://user-images.githubusercontent.com/18662417/157832441-cc73f8af-7968-45a7-8d8a-78c02f117244.jpg)

**Comment by GraPhiX-Guru** [comment]
strange looks ok on my system try this one
[Color.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8230519/Color.zip)

**Comment by plemsoft** [comment]
@GraPhiX-Guru That one works , Thanks for the help.

@LeeBamberTGC E-mailed new version for next build :)

**Comment by GraPhiX-Guru** [comment]
No Problem, i have found what the issue was with the original texture, the original was saved as 2048x2048 R8G8B8A8_UNORM_SRGB 2D this wont work as a BC7 texture for MAX the source should be linear i.e. 2048x2048 R8G8B8A8_UNORM 2D this will then convert to MAX BC7 compatible texture

**Comment by PaulSJ** [comment]
> the old BC7 version was not working it could not be loaded

Not sure why that would be the case, here is the original version from Mark which has always worked for me https://drive.google.com/file/d/1D63gy70nM_1nGSKQZFZOODFh6FFEchYK/view?usp=sharing

**Comment by LeeBamberTGC** [comment]
@PaulSJ I received a texture from Preben which I think came from Graphix and is now in the build, and it looks okay for me,

![image](https://user-images.githubusercontent.com/35840583/157877802-9ee01b21-f02c-4948-9cc8-dc13f88c7652.png)
