### ISSUE TITLE
GG Max - Guns and ammo move off the tables i had them placed on.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2478]
This bug seems to of happened after updating my windows 10.
Before updating today the saved game was fine, but after updating i have now got a couple of guns, and all the ammo that i had placed on these tables, moved positions. As you can see from the first and second screenshots.
Every table had a different gun, all 6 guns that are in max were available and placed on tables with there ammo.

The shot gun was on a table, but for some reason now it appears under ground, i found it by clicking on the shotgun using detailed object list.
I guess all the missing ammo will be the same, and placed under the ground somewhere.

These were all placed using Smart placement again.

![image](https://user-images.githubusercontent.com/66874403/157855030-b7ae20e1-bacc-4982-86e5-170fc698c448.png)

![image](https://user-images.githubusercontent.com/66874403/157855268-8106721a-3d4f-4bce-abe9-299da2287013.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Items did not fall under the table with creating, testing saving, or loading, but did when I used terrain sculpt brush to raise or lower:

![image](https://user-images.githubusercontent.com/35840583/164542082-9d021446-b576-4f51-9889-41ee2914fa83.png)

I am assuming this is the bug, and it will be fixed in the next EXP build on Steam.  Now when moving terrain floor, objects stay relative to old positions:

![image](https://user-images.githubusercontent.com/35840583/164547169-733bfd88-2eb5-404a-9193-8c39e3e3984b.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC 
If this was a fix for the latest build on Friday 22/4/22.
Then this fix has made Smart Placement terrible.
It is making it very hard now for me to continue my level as lots of objects dont place properly on lots of other objects.

I have already started a new bug regarding the latest build, as i didnt know if these are related.

https://github.com/TheGameCreators/GameGuruRepo/issues/2957

The latest build this Friday has made things so much worse for me. I spent 8 hours fixing a AI problem i never had before this build, And now having this smart placement bug i cannot really continue building level until this is fixed.

**Comment by Tum1370** [comment]
Please release a quick fix for the Smart Placement so i can continue creating my second level. Hopefully dont have to wait for ages for another update to this problem

**Comment by LeeBamberTGC** [comment]
@Tum1370 Has this specific issue "Guns and ammo move off the tables i had them placed on", been fixed?

**Comment by Tum1370** [comment]
@LeeBamberTGC 
I could not even tell you if this bug was fixed.
This was a very early TEST MAP and i have not seen this bug since that test map.

Fridays build though has made Smart Placement useless for me though.
I cannot easily place objects on top of other objects now.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Okay I agree it is the same issue as the link below, so will close this one and we can continue through with this one:

https://github.com/TheGameCreators/GameGuruRepo/issues/2478#issuecomment-1109851707
