### ISSUE TITLE
Zombie Animation issues

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2479]
Issues seen in the video:
-0:07-0:10: Zombie changes direction briefly before performing death animation (also happens to second zombie around 0:23)
-0:10-0:15: Zombies feet slide whilst performing death animation

Map is attached to reproduce:
[blank1103.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8231330/blank1103.zip)

https://user-images.githubusercontent.com/32545391/157854780-dc83ed16-5e23-4d64-ada0-7c7fbc830afb.mp4

**Comment by LeeBamberTGC** [comment]
@ZakJudges Fixed for next internal build.
