### ISSUE TITLE
Initializing spawned soldier too slow

### ISSUE THREAD

**Issue by gg-Anubis** [TheGameCreators/GameGuruRepo#248]
If the enemy spawns in front of the player.. you will have him shot before he can even act..
It takes around 2 seconds after spawning before he becomes active.
Those 2 seconds its just a static shooting bag.

Doesn't matter if the (unspawned) soldier is Always Active or not.

Attached FPM *renamed to *.txt

[soldier_init_test.txt](https://github.com/TheGameCreators/GameGuruRepo/files/2057780/soldier_init_test.txt)

**Comment by LeeBamberTGC** [comment]
tested with latest beta and the spawned character now attacks instantly (attached is a test map).
[SpawnInstantAttack.zip](https://github.com/TheGameCreators/GameGuruRepo/files/3335676/SpawnInstantAttack.zip)
