### ISSUE TITLE
Please stop duplicating surface map [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#2481]
GGMax generates the surface map and uses it, ignoring my surface map.
For example, I have:
table_color, table_normal, table_metalness, table_gloss, table_surface DDS maps; and GGMax generates the "_table_color_surface.dds_" file.
First, that name does not match the other ones.
Second, the surface map already exists in the folder, so, why does not use mine?

As a side note, due to this GGMax behavior, I end up with duplicate files that I have manually removed, nothing wrong when talking about a couple of files, but here often are 300+ files. :)

**Comment by ZakJudges** [comment]
@dllllllllllb This one is importer related :)

**Comment by OldFlak** [comment]
Yes - Longtime issue now :)
**Never** create surface maps - only use the one provided. Simples :)

**Comment by 3coms** [comment]
_if fileExist(Path)_ is so simple as well :)

**Comment by 3coms** [comment]
GGMax includes the **marker** folder in the mesh path, and there is no way to change it; as you can guess **marker** has nothing to do with my mesh. (red arrow)
the surface map has the right path because I change it, but color and normal are unchangeable.

![material_badListed_GGMax_EA_pic02](https://user-images.githubusercontent.com/47690174/162794069-509d3adf-2719-4579-96a0-1982cfdb6b35.jpg)

**Comment by ZakJudges** [comment]
Hi @3coms, the issue of the duplicated surface maps should be fixed in the next update. For more details on the fix, see this issue #2421 
Thanks :)

**Comment by 3coms** [comment]
@ZakJudges 
Ty mate, well done!
