### ISSUE TITLE
You can't pick up weapons whilst inside a text zone

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2483]

**Comment by rvanner** [comment]
@dllllllllllb Maybe you can have a stab at this one while Lee is away?

**Comment by dllllllllllb** [comment]
@ZakJudges It works perfectly fine for me https://www.youtube.com/watch?v=m3c5xgSg7y0
Can you please give me more details on how to reproduce it.

**Comment by ZakJudges** [comment]
@dllllllllllb I haven't been able to reproduce this one. It might have just been a one off or has already been fixed. It happened to me originally on the Mystery of Z-Island demo, at the beginning next to the tent and also in the second level when you are in the control room.
