### ISSUE TITLE
Characters Ignore Navmesh Bounds

### ISSUE THREAD

**Issue by PaulSJ** [TheGameCreators/GameGuruRepo#2489]
Characters seem to be able to ignore the navmesh bounds when repositioning
![Outside Navmesh Bounds](https://user-images.githubusercontent.com/8309736/157927257-f0830f92-19a7-4d9d-bd0e-4023c3b5b265.jpg)

**Comment by LeeBamberTGC** [comment]
@PaulSJ Made a different approach which literally prevents the character from moving outside of their navmesh path trajectory. If you can confirm this as fixed, we can close this and look to make improvements after EA for a better fidelity of movement within the nav mesh.

**Comment by PaulSJ** [comment]
@LeeBamberTGC Definitely better than it was, but if I move up the hill characters will sometimes follow me
![Navmesh Bounds](https://user-images.githubusercontent.com/8309736/158643529-c4216bd1-efd7-4683-bb3e-f4180ad4360a.jpg)

**Comment by LeeBamberTGC** [comment]
@PaulSJ Can you make a small video with the latest master and the Snowy mountain level so I can see how you provoke the character to go off-nav :)

**Comment by PaulSJ** [comment]
@LeeBamberTGC Video 1: https://drive.google.com/file/d/1cSBTZsWFw8lA8IODdKj877fA2PN71OfN/view?usp=sharing
Video 2: https://drive.google.com/file/d/1T3i4viwNuc2SN6gBx7ycFjAn1rsoSQyS/view?usp=sharing
Run using the latest master at the time

**Comment by LeeBamberTGC** [comment]
@rvanner I have done some running about with the very latest on this level, and cannot really get the characters to move off the nav mesh. Be aware there are a LOT of nav mesh on the hills and plenty routes up there.  Let me know if you spot any high issues and put them on the board for Thursday, thanks!

**Comment by rvanner** [comment]
@LeeBamberTGC Here's a video of me playing the snow level. You will see:

- At 40 seconds in, one of the characters manages to escape the tunnel area, he goes to the left behind the box and manages to get behind the scene
- At 55 seconds, a soldier runs up above the navmesh area to the edge of the snow line. I would not expect he could do that

https://youtu.be/17nrRpqT1aA
