### ISSUE TITLE
Freeze/UnFreeze Player

### ISSUE THREAD

**Issue by demented-mind** [TheGameCreators/GameGuruRepo#249]
When you use FreezePlayer() it works fine;l however, the lighting gets brighter. Not enough for a show stopper but still looks amateurish and is noticeable. The UnFreezePlayer() does return the lighting to it's original state. **## But**, the player jumps up. In other words the camera moves higher as if the -SPACEBAR- key is pressed. This is annoying and also doesn't look good -- so much so that I will not use it in this state and because I would like to use it it's kind of a show-stopper for me.

The attached zip file contains an fpm and dat file plus the lua file. I could not duplicate the FreezePlayer issue except that shadows are lost (disappear) and you sort of can tell that something is going on with the lighting but not as obvious as in my game. However, the UnFreezePlayer issue does persist. When running the included map move the player within 220 units from the barrel and you will freeze. After a couple of seconds you will unfreeze. You will notice this by the player jumping up as if you pressed the spacebar key. Move away from the barrel ( > 320 units from the barrel) to reset the freeze command.

[demented_mind_test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2065537/demented_mind_test.zip)

I'm using Beta Build 2018-05-31

Alienware Aurora R7 with SSD 256GB boot drive ( C: ) and a secondary drive ( D: ) that is 2TB 
Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 3.19 with Intel Turbo-burst
Installed RAM 16.0 GB
64-bit operating system, x64-based processor
Windows 10 Home
NVIDIA GeForce GTX 1070 with 8192 MB GDDR5 and 8095 MB shared system memory

**Comment by demented-mind** [comment]
I included map/script files to make testing easier.

**Comment by LeeBamberTGC** [comment]
Already reported and fixed for #435, so closing this one too.
