### ISSUE TITLE
Add a "+" sign to the centre of the next available slot in the My Games section

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2491]
![image](https://user-images.githubusercontent.com/1503593/157928932-6f4c5358-f90b-477e-9c03-08d37aca99a8.png)

**Comment by OldFlak** [comment]
Looks to be stretched and not centered on my system (1920x1080)

![image](https://user-images.githubusercontent.com/12246318/158588758-afb84e5a-3914-41d5-9957-4b277dc57894.png)

**Comment by rvanner** [comment]
@ZakJudges See @OldFlak 's feeback above, looks like the Y height needs fine tuning

**Comment by ZakJudges** [comment]
@OldFlak Thank you for reporting this. Could you let me know if it is fixed for you in tomorrow's build? :)

**Comment by OldFlak** [comment]
@ZakJudges - Just updated
Still seeing same thing although more centered now, the plus image is stretched and distorted
![HUB - Distorted Plus Image](https://user-images.githubusercontent.com/12246318/158718652-958e5b9c-d667-440d-af25-ec8b7a111a05.png)

**Comment by ZakJudges** [comment]
@OldFlak Third time's a charm. A fix should be in tomorrows build :)

**Comment by OldFlak** [comment]
This is not fixed. 
![HUB - Distorted Plus Image](https://user-images.githubusercontent.com/12246318/158921567-d071c367-de59-4289-a95e-1ea90c217112.png)

Best to not have it there at all if you can't get it to display correctly :)

**Comment by ZakJudges** [comment]
Hi @OldFlak, here is how it looks on my side:
![Screenshot 2022-03-18 090617](https://user-images.githubusercontent.com/32545391/158973438-473f2c94-3e94-47cc-9660-57f08d8e51aa.png)

Would you be able to check this again, after the Friday build goes live? I'm thinking perhaps my changes didn't make it into the latest internal build :)

**Comment by OldFlak** [comment]
@ZakJudges Thanks for reply - yes that is perfect! - Will try with next build :)
