### ISSUE TITLE
Reflective glitch

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2495]
![image](https://user-images.githubusercontent.com/1503593/157931123-7b83f421-e532-4e54-a17d-9bb6b7bde79a.png)

**Comment by davekirk85** [comment]
look in the reflection settings, i think it is the 3rd one down, just untick it and it fixes it

**Comment by rvanner** [comment]
@dllllllllllb Can you do as @davekirk85 has suggested and if it fixes this update the game?

**Comment by rvanner** [comment]
This was fixed by Paul earlier this week so closing this now.
