### ISSUE TITLE
invulnerability works in standalone ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2498]
Invulnerability works in Standalone Game ..
Not sure if this is by design or a bug
I assumed invulnerability was for testing in the editor .

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
