### ISSUE TITLE
TriggerZones and TextZones are not height sensitive.........

### ISSUE THREAD

**Issue by UNIRD12B** [TheGameCreators/GameGuruRepo#2499]
when you place a TriggerZone or a TextZone on a second or third floor of a building
if you pass below it on the first floor the Zone is triggered since there
does not seem to be a HEIGHT setting in the script..
is it possible to update the script to add in a value that allows the HEIGHT
of the placed Zone to be triggerable only from a more defined height
other than from the ground to the boundless sky ?
I see other have been asking for this to be fixed since some time in 2018 or even earlier....
Thx
UNIRD12B

**Comment by mike123yy** [comment]
I have the Same problem as of May 9, 2022.

**Comment by earthling45** [comment]
Why not have trigger boxes instead of zones? would this not eliminate a lot of problems.
The player must come in contact with the collision box in order to trigger what the particular trigger box controls.
This would also solve the issue with switches which as i've read can be controled because the player is within the required distance all though there is a wall between the player character and the switch.
Setting a trigger box, adjust hight/widh/length and means that the player must always be in the right area in order to control that switch or something else.

**Comment by LeeBamberTGC** [comment]
@ZakJudges See the WIN ZONE for how I added the code to solve this. Extend the feature to all other zones that detect the players presence.

**Comment by UNIRD12B** [comment]
ok ,
  thx , but , it still doesnt seem to work for messages.
as messages on the second floor activate when  you pass under them
on the first floor.
UNIRD12B

**Comment by ZakJudges** [comment]
@UNIRD12B I will post here when the fix has made its way into a build that you are able to test :)

**Comment by UNIRD12B** [comment]
Great,  Thx so much.UNIRD12BOn May 11, 2022 11:41 a.m., ZakJudges ***@***.***> wrote:
@UNIRD12B I will post here when the fix has made its way into a build that you are able to test :)

**Comment by UNIRD12B** [comment]
well, 
  i just tried the new update
and so far ,
the TEXTZONE still done not work properly with
respect to height and i could find no ZONEHEIGHT  at all.
sorry
UNIRD12B

**Comment by UNIRD12B** [comment]
" If you are still able to trigger zones from the floor above, simply reduce Zoneheight :)"
PS. thids is the exact opposite of my problem , as i explained above...

"when you place a TriggerZone or a TextZone on a second or third floor of a building
if you pass below it on the first floor the Zone is triggered since there
does not seem to be a HEIGHT setting in the script.."

thx again

**Comment by earthling45** [comment]
> " If you are still able to trigger zones from the floor above, simply reduce Zoneheight :)" PS. thids is the exact opposite of my problem , as i explained above...
> 
> "when you place a TriggerZone or a TextZone on a second or third floor of a building if you pass below it on the first floor the Zone is triggered since there does not seem to be a HEIGHT setting in the script.."
> 
> thx again

Under behavior tab you'll find a slider with which to adjust zoneheight.

**Comment by UNIRD12B** [comment]
So far,  Can't see that even with today's update..On May 13, 2022 2:01 p.m., earthling45 ***@***.***> wrote:

" If you are still able to trigger zones from the floor above, simply reduce Zoneheight :)" PS. thids is the exact opposite of my problem , as i explained above...
"when you place a TriggerZone or a TextZone on a second or third floor of a building if you pass below it on the first floor the Zone is triggered since there does not seem to be a HEIGHT setting in the script.."
thx again

Under behavior tab you'll find a slider with which to adjust zoneheight.

**Comment by UNIRD12B** [comment]
cant see any slider there yet at all....
ecen with all the advancced settings

**Comment by synchromesh62** [comment]
> cant see any slider there yet at all.... ecen with all the advancced settings

Its there for sure .. Not sure why its not there for you.
![zone](https://user-images.githubusercontent.com/35708217/168420814-8ced3763-4fd1-409c-beaf-5cdb4cf3168d.png)

**Comment by UNIRD12B** [comment]
Thx ,
  i know you say its there but for some reason..
I cant see it in any of the marker and i wonder if thats true with others also ?

**Comment by synchromesh62** [comment]
Was there an update yesterday ? 
Im on the experimental build.

**Comment by UNIRD12B** [comment]
ok , im on yesterdays update and its still not there,,,
.......maybe its only on the experimental update yet....

**Comment by UNIRD12B** [comment]
Publicpreview was the answer....On May 14, 2022 3:32 p.m., synchromesh62 ***@***.***> wrote:
Was there an update yesterday ?
Im on the experimental build.

**Comment by ZakJudges** [comment]
Hi @UNIRD12B, there was another update yesterday. The zoneheight variable should definitely be there now. Could you confirm if this issue can now be closed? Thanks :)

**Comment by UNIRD12B** [comment]
Hi JakJudges ,yes  I explained in my answer to you last week that it was actually in last week's...PUBLICPREVIEW.. and ,It seems , so far ,  to work as proposed.Thx so much.UNIRD12BOn May 23, 2022 4:28 a.m., ZakJudges ***@***.***> wrote:
Hi @UNIRD12B, there was another update yesterday. The zoneheight variable should definitely be there now. Could you confirm if this issue can now be closed? Thanks :)

**Comment by ZakJudges** [comment]
Thanks for confirming, closing this issue

**Comment by UNIRD12B** [comment]
ok ,
  thx , but , it still doesnt seem to work for messages.
as messages on the second floor activate when  you pass under them
on the first floor.
UNIRD12B

On 2022-05-11 7:37:44 AM, Lee Bamber ***@***.***> wrote:
@ZakJudges [https://github.com/ZakJudges] See the WIN ZONE for how I added the code to solve this. Extend the feature to all other zones that detect the players presence.

**Comment by LeeBamberTGC** [comment]
@ZakJudges One for you :)

**Comment by ZakJudges** [comment]
Hi all, apologies for the late reply. I have added a fix which brings the text zone trigger height in line with the other zones. Should be in the next experimental build. Thanks :)

**Comment by UNIRD12B** [comment]
Thx for the update..UNIRD12BOn Jan. 3, 2023 6:00 a.m., ZakJudges ***@***.***> wrote:
Hi all, apologies for the late reply. I have added a fix which brings the text zone trigger height in line with the other zones. Should be in the next experimental build. Thanks :)
