### ISSUE TITLE
GG Max - Changing Gun settings on Developer Settings

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2500]
I have the developer settings showing on the Object tools section of Max.
I tried changing the gun settings for a Patrol Rifle.
Changed the Reload Quantity from 30 to 50. But in game the mag size was still 30.

Changed the Accuracy from 200 to 1. But in game it still did not seem to effect anything, and even though the crosshair was direct on target, it did not seem to hit.

Changed the damage from 38 to 100. But in game a enemy with 100 hp, still took several shots to die.

Do these settings actually work or not ?

**Comment by Tum1370** [comment]
Strange, as i have just tried changing the Reload quantity again and this time its working.
Seems buggy to sometimes work and other times not work,

Going to test the accuracy and damage again

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you send me an FPM level showing this with stock weapons, and a step by step so I can follow through and reproduce, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC 
This was a while ago when i tested this.
But after creating a simple map with the Patrol Rifle, I changed the Reload Quantity from 30 to 90 as you can see in screenshot 1.
But in game testing this, Sometimes the reload is 90, but then other times the reload is only the standard 30.

I have not retested the accuracy as this gun has already been fix, and is more accurate now anyway.
I have not retested the damage.

Screenshot 1 = Developer Setting changed from 30 to 90.
Screenshot 2 = Sometimes the reload is 90 bullets as in this pic.
Screenshot 3 = Sometimes the reload is the standard 30, even though set at 90.

![Reload](https://user-images.githubusercontent.com/66874403/165954031-6218e6d0-9dd3-41f5-bb21-750cfb6d8449.png)

![Reload 1](https://user-images.githubusercontent.com/66874403/165954498-433fbb41-749c-4ae3-8e3b-45e2681bd894.png)

![Reload 2](https://user-images.githubusercontent.com/66874403/165954710-afba7657-e0cf-47df-8de7-e4c7b7ee1896.png)

**Comment by ZakJudges** [comment]
@LeeBamberTGC This is caused by weapons having multiple sets of settings for each of their firemodes. When the firemode is changed with the V key, the 'old' settings are then restored until the V key is pressed again. Do you recommend propagating any developer setting changes throughout all firemodes, or adding in more settings to the developer section?

**Comment by LeeBamberTGC** [comment]
@ZakJudges Yes anything weapon flavored, assign to me. I am doing weapons now :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges As per my comments about adding a mew <Quantity> macro for LUA descriptions (like how <Sound0> works), you will also find a raft of values that control changes to weapon settings. I would do the same here, and expose them as macros so they can be specified in the weapon behavior and expose the required values.  I suggest things like <WeaponReloadQty> <WeaponDamage> <WeaponAccuracy>.  For now, only act on the primary weapon mode, we can look at how best to handle secondary weapon modes which have their own settings. There is also existing code which propagates these new settings to the weapon system before the level starts.  A nice juicy one for you.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Updated system so developer mode setting changes are applied in all cases, even on the first load and run scenario as above.  Will be in the next EXP build :)

**Comment by Tum1370** [comment]
@LeeBamberTGC This seems to be fixed now on latest EXP build, I will close this issue now. Thanks
