### ISSUE TITLE
GameGuru MAX - Tree Collision Needs Account for Trunk Width

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2503]
Tree Collision needs to a way to determine trunk size (width) somehow. I don't know how to do this or if this is possible, but having one-width-fits-all is not going to work for the trees. 

I was examining why I was getting massive slowdowns in the Island Showdown when running around in the Jungle and it turned out to be the trees placed there by the developer that had **Hull Decomp** set for collision. Changing all those to **Tree Collison** gave me a consistent FPS throughout the entire game. Great! However, Tree Collision did not compensate for the massive trunk size of the Squat Tropical Tree and, as a result, the player could walk through most of it, which is not ideal. If, when selecting Tree Collision, the software could examine the tree model for about the height of the player collision capsule and create a cylinder to the thickness of the model at that height, that might work. 

The better solution might be to ensure that all tree models used in MAX have a proper trunk collision model, a simple cylindrical collision mesh that properly fits the trunk and the trunks orientation. Hull Decomp is definitely NOT a solution for dense woods and jungles.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Fixed for all 38 tree types for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0abe0181-1ed6-4fc9-8ed2-5dc7d1a5cd38)
