### ISSUE TITLE
GG Max - How do we send character to next level after it kills a boss at end of level ?

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2506]
As the title says, How do we send the player to then next level after it kills a final boss on a level ?
I can see win zones, but they only activate when you enter the zone.

Is it possible to have the boss drop a key or object on death, so we can use that object to enter new level ?

**Comment by dllllllllllb** [comment]
@Tum1370 I believe features like this will come to Max when we'll work on the RPG genre :]

**Comment by Tum1370** [comment]
So really the only way currently to do this is for the player to enter the win zone?

**Comment by thecyrus** [comment]
I did this by adding a line of code in the boss AI, but it would be a great feature to have Win conditions.

**Comment by Tum1370** [comment]
@thecyrus 
How do we add a line of code please to do this ? And what line of code do you add ?

**Comment by thecyrus** [comment]
Just add the key command to finish a level, JumpToLevelIfUsed(e) in the exit procedure of an enemy.
For example:
function ai_ENEMY_exit(e)
	module_combatcore.releasecover(e)
	JumpToLevelIfUsed(e)
end

And then you put the level name in the "IfUsed" property of the character.

In this case you win the level right when its health reaches zero, you don't even see it dying and win the level straight away.

**Comment by thecyrus** [comment]
What I wrote above was a GG Classic example. But if you put in the main function:

if g_Entity[e]['health'] == 0
then JumpToLevelIfUsed(e)
end

It should go for your purpose.

**Comment by mav3r1ck1981** [comment]
@Kasseyus there are behaviors stock in max that allow this scenario to be created and work successfully
