### ISSUE TITLE
Optimised Jungle Assets don't have collision

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2507]
Player is now able to walk through all Jungle rocks 
- not only when adding new ones, but also any that are already in the level

**Comment by dllllllllllb** [comment]
I tested this in the dev build, placed all rocks from the jungle collection, tested the level and all collisions were working properly. I saved this level, loaded in a different level, then went back it and again, collisions were working properly.
I quit GGM, loaded it back up and once again, it was working properly.
https://www.youtube.com/watch?v=1SjJY-Gk-aE

@OldFlak Did you modify the rocks in any way or are you using other rocks that I have not tested? 
If not, please send me the .fpm of the level you see this issue in. My email: maciej@thegamecreators.com

**Comment by OldFlak** [comment]
@dllllllllllb Hi - thanks for looking into this.
The issue occurs when using the optimized version of Jungle assets - sent to rick a while back now.

Just tested after a verify and stock ones don't have the issue, but the optimized ones do.
- yet the only difference in FPEs are the references to to the textures
- they worked fine before first 03 commits build (03 commit builds broke a lot of things)

**Comment by rvanner** [comment]
@plemsoft I have assigned the issue that suggests using the optimised Jungle assets. Can you also check the collision on those assets based on this report?

**Comment by plemsoft** [comment]
@OldFlak All fixed and updated on steam , Thanks for your help :)
