### ISSUE TITLE
MAX - 2022.03.11 - Glitchy Trees

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2508]
Looks to be a z-clash issue to me (see video)
My Guess is that it has something to do with the weird bug where duplicate trees appear and disappear near each other
- see #2114

![MAX 2022 03 11 - Glitchy Trees](https://user-images.githubusercontent.com/12246318/158086385-48e9581e-a6cb-4743-be8c-bca08ac73dbc.png)

https://youtu.be/ZRhaFQgFeAY

**Comment by PaulSJ** [comment]
@OldFlak Is this still an issue in the current version?

**Comment by OldFlak** [comment]
@PaulSJ Can be hard to find sometimes but got this after a bit of poking around.

![image](https://user-images.githubusercontent.com/12246318/164701248-20b87099-b3d9-4ccd-8e0b-2d61f71dfa35.png)

**Comment by PaulSJ** [comment]
Could you share that level with me, or give me some steps to reproduce it?

**Comment by OldFlak** [comment]
@PaulSJ Hi Paul - spent a good 10-15 minutes in latest Experimental build trying to reproduce, but not seeing it now.
Before could produce it reliably so might be safe to close this now - can always reopen if it comes back.

Thanks for persevering with it :)
