### ISSUE TITLE
MAX - 2022.03.11 - More Editor Bugs - Audio Not Playing

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2509]
Some audio attached to objects do not play in editor or standalone
- some do some don't
- for example two doors with exact settings and audio. One will play sound when activated, one won't

**Comment by dllllllllllb** [comment]
@OldFlak I just tested this with a dozen doors and switches, and all of them play their sounds correctly. Is this happening with any specific objects / behaviours?

**Comment by emo10001** [comment]
I am having this issue as well.  Quite a few sounds will not play when you preview them.  You get the "progress bar" of the sound playing, but there is no sound.  Other sounds play fine.  For the sounds that do not play, if I browse to them in the file system and play them outside of GGM, they play just fine (with VLC for example).

Examples:
OpenDoor.wav
Parrots Wings Flap - 1.wav

Actually I would say the majority don't play.

Just fyi, I'm listening to them when editing the Title Screen and choosing "Music Track".

Also noticed in the Island Escape demo level, the gunshot for the player made no sound.  But did make sounds for the NPC's

**Comment by emo10001** [comment]
Ok, something of note on this.  It could be a bitrate issue.  Every sound that **will** play, the bitrate is 1411 kbps, but for all the sounds that won't play it's 705 kbps.

**Comment by ZakJudges** [comment]
Hi all, I haven't been able to reproduce this. Could someone send me a standalone or level that shows the issue? My email address is zak@thegamecreators.com

**Comment by ZakJudges** [comment]
Hi all, closing this issue as haven't been able to reproduce. If anyone still experiences this, please send me an asset/level that shows the issue and I will reopen the issue. My email address is zak@thegamecreators.com
