### ISSUE TITLE
Seperate Audio file in storyzone wont trigger when placed over start position marker

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#251]
Customer reported  separate audio file will play with video if you walk into a story zone but only the video will play if placed over a start marker for an intro purpose.

Tested and confirmed ..

NOTE.. 
This  was so much better as an all in one player even if it was only WMV

**Comment by LeeBamberTGC** [comment]
Can you provide a small FPM showing this with stock media?  We had to discontinue WMV when we upgraded to DirectX 11, but there might be a solution with MP4 video files that contain their own audio, we just need to find a way to do this with the new video player tech (posting examples here would help).

**Comment by synchromesh62** [comment]
Easier to show you Lee via this little video
Added story zone
Added mp4 file
added sound track 
Walk into zone its fine and sound plays perfectly
Place on start marker to play video instantly and no sound
https://youtu.be/wVa7PVlo2Ns

It would be great if we could have vid and sound combined again 
VLC Is open source and plays pretty much anything … could that or the codecs be incorporated perhaps ?
https://www.videolan.org/vlc/index.en-GB.html

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Thanks for the instructions, that will help. We are currently using THEORA for video playback so if you can dig out some sample code which shows how to play the audio track of the MP4 file, that would do the trick :)

**Comment by plemsoft** [comment]
@synchromesh62 Thanks , the issue has been fixed and are added to the next update :)
