### ISSUE TITLE
player death go to Fail Screen in standalone

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2510]
Back by popular demand:
- Ambience stops playing after death and respawn in standalone

**Comment by LeeBamberTGC** [comment]
@OldFlak In next EXP build, the player dying in standalone no longer restarts, so this old issue is not directly repro, however adding a checkpoint into the level does allow a restart of the player. so the fix ensures the ambience resumes when the player respawns into the checkpoint.  This system is reused in the game menu pause/resume but is no longer affected also.

**Comment by LeeBamberTGC** [comment]
Okay, EXP uploaded, try it out though I did spot another bug that is probably reported that checkpoints do not work in standalone :(

**Comment by OldFlak** [comment]
Gave that a test Lee, but on player death you go to Fail Screen, so as you said checkpoints are not working in standalone

**Comment by LeeBamberTGC** [comment]
@OldFlak Latest EXP build allows checkpoints to start the player at that point instead of going to the Lose Screen in standalone exports.
