### ISSUE TITLE
sensistivity issue

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2511]
theres a problem moving things, you place sometthing down and move or try to resize and it shoots off, the sensitivity appears to be broken !

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/158205932-b331366b-1639-4e14-9e7a-c5f6214b065f.png)

prime example, resizing this and itt instantly jumps in size.

**Comment by casigus** [comment]
just ran the latest version, this is still an issue, not as bad as last weeks build but its still overly senstive.

**Comment by LeeBamberTGC** [comment]
Fixed for todays experimental build. Only scale still broken.

**Comment by ZakJudges** [comment]
@casigus Could you confirm if this issue is now fixed for you? Thanks!

**Comment by casigus** [comment]
yes!  very  much so!!
