### ISSUE TITLE
crash!

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2516]
memory problems again:

![image](https://user-images.githubusercontent.com/68471279/158235355-9314fdc4-7052-4280-8598-f5b5a5729e87.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you get this level and see if you can reproduce it, thanks!

**Comment by dllllllllllb** [comment]
@casigus Please email me with the .fpm file of the level the crash occurs in :]
My email: maciej@thegamecreators.com
Thanks!

**Comment by casigus** [comment]
saddly its also packed with non max assets which seam  to be causing the issues. ill see if i can  find a report in windows with more info on the crash

**Comment by plemsoft** [comment]
@casigus Is this level running for you now in the latest version ? , if not could you create a standalone of the level and zip the standalone folder and e-mail it to me, i will then be able to debug the level , Thanks for your help e-mail: plemsoft@plemsoft.com

**Comment by casigus** [comment]
i'll have a nosey, alot of the crashes have stopped now  !!
