### ISSUE TITLE
Lightmapping not working

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#252]
Hi
no static entity will light map correctly, if you change it to dynamic it will lightmap
https://forum.game-guru.com/thread/219745#msg2601458

**Comment by GraPhiX-Guru** [comment]
dynamic entities do not lightmap :( I did not know that so please ignore this, static still does not lightmap though

**Comment by LeeBamberTGC** [comment]
Can you attach a small FPM using stock media showing your static lights placed and lightmap baked. I can then determine why you are not seeing the lighting baked into the scene. I am assuming you are using the current public build.

**Comment by GraPhiX-Guru** [comment]
Hi Lee
sure, I have done a video (just in case I am doing it wrong) and a fpm
https://youtu.be/Xpp-2kNetTY
[fpm.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2093565/fpm.zip)

**Comment by GraPhiX-Guru** [comment]
if you change your settings to medium after light mapping it kind of works but is still poor quality https://youtu.be/OJLCfcweFgw

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this,

Tested your fpm and it looks like it work in the current version.

Could you test this in the latest version and let me know if it was fixed , thanks :)

**Comment by GraPhiX-Guru** [comment]
Hi Preben thank you it does seem to work now :)
https://youtu.be/EZD8hU4hvKw
