### ISSUE TITLE
Behaviours - Switch interaction bug

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2520]
I think this is caused by recent changes that require you to look at the object to interact with it.

When a switch is even slightly inside another objects it is impossible to interact with it.
https://gyazo.com/0c9d276ac7c5f30b220ea7671378ddea

After moving it out of the object, it is still hard to interact with it.
https://gyazo.com/96c537e318fb7456497a2dcd3203429f

**Comment by LeeBamberTGC** [comment]
Fixed for this weeks build :)
