### ISSUE TITLE
Behaviours - Switches don't toggle lights (they can toggle everything else)

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2521]
Lights connected to a switch won't toggle on/off.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Are you trying to toggle a light that is set to CONSTANT LIGHT (i.e. constantly on?)

**Comment by ArgentArts** [comment]
@LeeBamberTGC I was attempting to use a light with the Togglelight Behaviour set to it and it would not toggle off/on with a switch. Instead, it stayed constantly on. Even if I unchecked the Light On box, the light remained on.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC It's not fixed, here's the setup I was testing it with:
![image](https://user-images.githubusercontent.com/61796872/159043574-45c06d6d-3b72-4446-9b8a-5d099ac30f3a.png)
https://gyazo.com/0c72a0b3425bffd086358bec78e10671

**Comment by LeeBamberTGC** [comment]
@ArgentArts A default light would show the constantlight behavior in the current build. You would need to choose another light behavior to get it to toggle:

![image](https://user-images.githubusercontent.com/35840583/159351400-e3651cb4-3c92-47f3-9353-9830665fb27f.png)

**Comment by ArgentArts** [comment]
@LeeBamberTGC Not sure why you're telling me this. In my screen shot you can clearly see that I have the light set up with a Togglelight Behaviour. ;)

**Comment by ArgentArts** [comment]
@LeeBamberTGC The last I tested this was three days ago, as can be seen in my screen shot. The "Togglelight" behaviour is what it was called then and, at that time, it did not work. In any case, I was not using a constant light, which is why I was confused as to why you were directing your previous comment toward me. :)

**Comment by ArgentArts** [comment]
@LeeBamberTGC - Just installed the latest internal build (3.25) and here's what I've got:
![togglelight](https://user-images.githubusercontent.com/36735507/159361285-90a5e06c-32ea-465b-89c6-f03690c5a8e2.png)

**Comment by LeeBamberTGC** [comment]
@ArgentArts You might have some rogue files in your writables area, should look like this with a newly added light:

![image](https://user-images.githubusercontent.com/35840583/159363790-60b63a01-3f9d-4990-a33d-7d6b1dbe697b.png)

**Comment by ArgentArts** [comment]
No, I mean when you choose the togglelight behaviour in order to try to use a switch to control a light. Constantlight is the default, yes. But if you switch the behaviour from Constantlight to Togglelight and then set up a switch to control it, the switch does nothing and the light stays on.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Can you snapshot your scriptbank markers folder, thanks:

![image](https://user-images.githubusercontent.com/35840583/159368519-e9d8c6cd-9a1d-47a0-a21c-5239a531bf4e.png)

**Comment by ArgentArts** [comment]
@LeeBamberTGC The one in my Documents folder or the one in the official GameGuruMAX install folder?

**Comment by LeeBamberTGC** [comment]
@ArgentArts The GameGuruMAX install folder, there should be no scripts in the documents folder, at least none I am responsible for :)

**Comment by ArgentArts** [comment]
![markers](https://user-images.githubusercontent.com/36735507/159368989-417a0d93-fd25-4e94-b8ba-fa3960a85eca.png)

**Comment by LeeBamberTGC** [comment]
@ArgentArts Looks like the auto-updater is not distinguishing between lower and upper cases for existing files.  For now, just delete the scriptbank entirely, and verify files through the auto-updater and you should be right.

@ZakJudges Perhaps you can create an issue about this so we can solve it after EA.

**Comment by ArgentArts** [comment]
@LeeBamberTGC That did the trick. The Behaviour is displaying correctly ("Toggle Light") and the switch now works. :) Thank you!!!
