### ISSUE TITLE
Entity placement

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2526]
It's very easy to try to place an object, especially when close to it and have it fly off and land a long way off, or even be told it is outside of the editable area, even when not close to the edge. 

It's a very frustrating thing.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you see if you can reproduce this one with stock art and a step by step, thanks!

**Comment by davetgc** [comment]
Hi Lee,

I've made a small video. This is me trying to build a wall. It didn't
happen this time but sometimes entities get placed far across the map and
you don't know that you've even placed them.

https://youtu.be/MMhhC8qI92o

**Comment by LeeBamberTGC** [comment]
Fixed in EXPERIMENTAL build.

**Comment by rvanner** [comment]
Tested and fixed.
