### ISSUE TITLE
LUA Logic and AI Logic Slowdown on Ricks PC

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#2527]
Needs to be 60 FPS.

**Comment by LeeBamberTGC** [comment]
@rvanner It appears the majority of the 78 characters in the snowy mountain level were actively checking the floor under their feet four times per cycle, not a great use of CPU time.  I have added code that keeps characters dormant until they are seen by the camera, line of sight with the player. They then perform actions normally.  My own AI Logic went from 2.9ms to 0.3ms on starting the level, you should see 60 fps now. 

Also sorted the erratic AI of the soldiers related to newer line of sight code so they can be hurt, and so can the player, with no misses. I do think close range shotgun and headshots from sniper should be instakills.

It will be in the next internal build for 2 PM.

**Comment by rvanner** [comment]
Ha! That sounds like a great breakthrough. Let me know as soon as the new version is ready.

**Comment by LeeBamberTGC** [comment]
@rvanner Okay, update now and let me know if you get 60 FPS.
