### ISSUE TITLE
If the water level is raised higher in the Terrain Editor, when the Level Editor starts, position the start marker on some land

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2533]
In this early preview video the YouTuber makes a level and he starts the level underwater
Can a check be made and if the camera is underwater can it be made to find the nearest land?
https://youtu.be/qtA0EFdGGPM

**Comment by ZakJudges** [comment]
@rvanner If the middle of the map is under water, points are now checked on a circle around the middle to find land. This circle will keep increasing in size until either land is found or it reaches the edge of the map. If no land is found then it will default to the middle, but above the water.
