### ISSUE TITLE
Max bug with old particle system

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#2537]
I've noticed when testing particle scripts using the old particle system, the particles will change to the default smoke particle after so many times. I know this was done to save memory with GG classic, but can it be shut off in Max ?
Thanks

**Comment by AmenMoses** [comment]
It's probably because the script is not freeing up the storage, try specifying an Id for the images, i.e.:

ParticlesLoadImage( <file>, 10 )

**Comment by bluemeenie195** [comment]
Thanks AmenMoses, I'll give that a try.

**Comment by bluemeenie195** [comment]
Thank you, It's all set now
