### ISSUE TITLE
GG Max - Zombies eating noise does not stop if you kill them on the floor

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#2539]
[https://youtu.be/4Q52bqCDtpY](https://youtu.be/4Q52bqCDtpY)

If you kill them while the eating sound is playing, it doesn't stop.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I looked into it this afternoon and again I'm having trouble with finding where the code is. 
I checked:
darkai_killai() as it had sound reset section
Entity.h
MakeAISound()
SetRawSoundData()
PlaySound()
and went through every single PlaySound() call but nothing has triggered my breakpoint.

I imagine the "Feeding" tickbox in "Zombie Attack" sets the animation and plays a sound but I can't find where that code is located. Can you please point me in the right direction :]

**Comment by LeeBamberTGC** [comment]
@dllllllllllb You will need to use the BEHAVIOR EDITOR to find that code, but the underlying command is in the script command called "PlaySound" and "LoopSound" you can start your trace there for when it is triggered, and then you know which sounds to stop when that character is killed.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I used the behaviour editor to change the .byc file but nothing I made has worked. (I made sure to update the behaviour every time).

It seems like the death of the zombie has a priority when executing code or the entity is deleted before the code is executed. I have tried adding these to the Zombie Attack behaviour but they have not worked:
In Feeding State (there already is one of those later down the flow chart)
https://prnt.sc/427WCSs8L_7R

In Damage State (Just to see if it would actually stop the sound)
https://prnt.sc/jpe6X89JiNx1

When you set Zombies health to 1 and shoot it while it's on the floor, it won't stop the feeding sound after it dies.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb No worries, thanks for assigning it back. My approach will be to stop 'all' sounds' that had been emitted by a character if it dies, that way it does not matter what mode the behavior was in when the character dies.  I believe there was some code to do this in the engine but I am guess it is being bypassed. I will post the solution here for your benefit when it is fixed :)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb The location for the new code ended up in M-DAINew.cpp and just under the code which stopped the characters weapon fire when they died. Here is the extra code:

	// reset any looping/sounds
	t.ttsnd = t.charanimstates[t.tcharanimindex].firesoundindex;
	t.charanimstates[t.tcharanimindex].firesoundindex = 0;
	if (t.ttsnd > 0)
	{
		if (SoundExist(t.ttsnd) == 1)
		{
			StopSound (t.ttsnd);
		}
	}
	#ifdef WICKEDENGINE
	// additionally any sounds triggered by this entity
	int e = t.charanimstates[t.tcharanimindex].e;
	for (int s = 0; s < 6; s++)
	{
		int ttsnd = 0;
		if (s == 0) ttsnd = t.entityelement[e].soundset;
		if (s == 1) ttsnd = t.entityelement[e].soundset2;
		if (s == 2) ttsnd = t.entityelement[e].soundset3;
		if (s == 3) ttsnd = t.entityelement[e].soundset4;
		if (s == 4) ttsnd = t.entityelement[e].soundset5;
		if (s == 5) ttsnd = t.entityelement[e].soundset6;
		if (ttsnd > 0)
		{
			if (SoundExist(ttsnd) == 1)
			{
				StopSound (ttsnd);
			}
		}
	}
	#endif

In the next build :)
