### ISSUE TITLE
Cant walk inside an EBE structure 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#254]
For some reason since the last update I cannot walk in EBE structures that have a default roof.
Nor old EBE structure ..Its as if the scaling of the player is slightly bigger 

Easy to test … Just create a room and put a flat roof on and place a start marker ..
Funny thing though … If you create a tunnel you can walk through it ?

**Comment by GraPhiX-Guru** [comment]
I can confirm this with the latest beta 15.06.2018
https://youtu.be/u7vioT6FuNo

**Comment by LeeBamberTGC** [comment]
This has been fixed for the latest PP build - turns out the player capsule shape was intersecting the roof at the start of the game level.
