### ISSUE TITLE
GGMAX - Behaviour / Settings Enhancment

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2543]
The Behaviour section should have the view cone, view angle and rate of fire, not the Developer section as it is now, it makes no sense in there. 
Secondly can we get an 'Item Dropped' field for any enemy/npc  in Character Settings that can be used for any named item to be dropped upon its death. It could be standard, health, ammo or 'special named ' that could be picked up/used by other lua scripts for loot drops. This would be ideal even now for fps and also required for future rpg game variations.

**Comment by ArgentArts** [comment]
I think we're thinking in similar terms:

https://github.com/TheGameCreators/GameGuruRepo/issues/2525

**Comment by Necrym59** [comment]
Well ill be.. i didnt even see your request - great minds think alike :)
