### ISSUE TITLE
MAX - Useful Features We Had - Please Bring Them Back

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2545]
We used to be able to clone locked objects - now you have to unlock them first

If you lock objects - it is three clicks to get the widget to show

Some objects, especially with transparency, can only be selected via the Detailed Objects List

Nothing stays at the original height when cloned, no matter what method you use

Not to mention all the darn popups
- I promise I clicked the button to plant trees or grass on purpose :)

**Comment by ArgentArts** [comment]
> We used to be able to clone locked objects - now you have to unlock them first

You can still clone it. Just select it and then drag it in from the Current Objects area. Even if locked, it will create a duplicate. 

Using CTRL+C and CTRL+V also works on locked objects.

> Some objects, especially with transparency, can only be selected via the Detailed Objects List

I can select invisible objects (alpha clip set to 0) by clicking in their general location in the view port.

> Nothing stays at the original height when cloned, no matter what method you use

Yeah, this is a pain. I wanted to clone several lights and keep them all at the same height. I had to keep going to the position area and typing in the Y position for each light. Quite a PITA.

**Comment by OldFlak** [comment]
This is not a forum - please don't clutter thread with banter or workarounds :) 

Locked objects **do not** show in Current Object area
Selecting semi transparent objects is broken - some work some don't. Not referring to alpha clip.

All issues in op used to be flawless - used to be.

**Comment by OldFlak** [comment]
![Lock Objects Not Clonable](https://user-images.githubusercontent.com/12246318/158804927-a1d73b84-1833-44cf-960e-6c5048f68c93.png)

**Comment by ArgentArts** [comment]
Not sure why you're being like this. I know this is not a forum. I am trying to help. Because:

Locked objects DO show up in the current objects area:

![locked](https://user-images.githubusercontent.com/36735507/158811161-ae3c4a6c-7b13-4151-85ec-df61e2828ec7.png)

**Comment by ArgentArts** [comment]
Ah! I stand corrected. And this needs to be reported. GROUPED locked objects show up in the Current Objects area, but individual objects that are locked do not. Ugh. What a mess. Sorry about that.

**Comment by OldFlak** [comment]
No problem :)
We just need to think of the person who gets assigned to look into the issue - they have to read the whole thread :)

Yes the editor is a mess if you ask me - thanks for helping out tho :)
Your pic above is good example of helping fix the issue. Never thought to try Groups might be a good lead for them...

**Comment by ArgentArts** [comment]
Yeah, I didn't think I was showing you workarounds, but was showing that what you thought didn't work actually did. But you were right. Sorry about that. In the end, though, it turned up yet another bug. ;)

**Comment by OldFlak** [comment]
`In the end, though, it turned up yet another bug. ;)`
No it did not turn up another bug - it is already reported as such in very first line of op :)
But thanks for helping out....

**Comment by ArgentArts** [comment]
Uhm ... no. The bug I was referring to was that locked GROUPED objects show in the Current Objects area, but ungrouped locked objects don't. So, no, it was NOT in the first line of the op ...
