### ISSUE TITLE
GameGuru MAX - Locked Objects Issue

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2547]
Locked individual objects do not show, when selected, in the Current Objects area. Grouped objects that are locked do. Both should show up as current objects in the Current Objects area when selected.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Fixed a while ago this one, can you confirm, and if still present, maybe attach a shot :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC  This is not fixed. If you select a locked object, it does not show in the Current Objects area. Here's an example from the current experimental build:

![current1](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/e25de66c-d0a9-48e9-9789-5c3c26236855)

![current2](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/d6b98d1c-428f-45e2-a3e8-9da5d1fb39a0)

**Comment by synchromesh62** [comment]
> @LeeBamberTGC This is not fixed. If you select a locked object, it does not show in the Current Objects area. Here's an example from the current experimental build:
> 
> ![current1](https://user-images.githubusercontent.com/36735507/266614784-e25de66c-d0a9-48e9-9789-5c3c26236855.png)
> 
> ![current2](https://user-images.githubusercontent.com/36735507/266614805-d6b98d1c-428f-45e2-a3e8-9da5d1fb39a0.png)

Thats not a bug .. Unless im misreading.
Locked objects cannot be selected the same way so they will not show on the left 
You can only highlight them to unlock as shown in the video below

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/7cdd55a0-d001-4a1e-a557-743ba479b6dd

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 You need to go to the top and re-read the original post. 

If you have a group and lock it, when you select that LOCKED group, it shows up in the Current Objects area. If you have an individual object and it's locked, if you select it, it does not. Either NEITHER kind of locked object should show up there or BOTH should, not one and not the other.

**Comment by synchromesh62** [comment]
Maybe Lee has but this is the way its always worked for me ?
Grouped objects are editable even locked they can be ungrouped whereas single objects are not. 
To me it covers every scenario .. Perhaps im wrong and its not been updated yet

**Comment by MonkeyFrogStudio** [comment]
It's not about how it's always worked. It's about how it should work, though I could be wrong. If a locked object is not supposed to show up under Current Objects, then it shouldn't show up - regardless of whether it's a GROUP or an individual object. But if it's supposed to, then it's supposed to. And, therefore, BOTH should show up. If the group is locked, it should be treated like any other object and be locked, etc.

If a group is locked, it should be locked and, therefore, not editable. The reason you lock any object is to prevent it from being editable. If someone wants to edit an object or a group that's locked, they should unlock it. 

At best, this means, to me, that the "lock" function is not consistent.

**Comment by synchromesh62** [comment]
> It's not about how it's always worked. It's about how it should work, though I could be wrong. If a locked object is not supposed to show up under Current Objects, then it shouldn't show up - regardless of whether it's a GROUP or an individual object. But if it's supposed to, then it's supposed to. And, therefore, BOTH should show up. If the group is locked, it should be treated like any other object and be locked, etc.
> 
> If a group is locked, it should be locked and, therefore, not editable. The reason you lock any object is to prevent it from being editable. If someone wants to edit an object or a group that's locked, they should unlock it.
> 
> At best, this means, to me, that the "lock" function is not consistent.

For me it just means a locked group object can still be ungrouped, maybe a bit deleted if you want then grouped again but it still remains locked, Whereas an single object i want locked i can never accidently select it which is the whole purpose of locking it. That makes perfect sense to me .. I guess we just have our own ways of looking at it but whichever way Lee goes isnt a problem.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio I can confirm grouped show up, and individuals do not, an inconsistency: so removed fixed status
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ab7e2bde-83a2-4aa1-a936-b706f8cd0b1e)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Fixed for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/712e21e0-2428-461b-b225-c5c7a04eab35)

**Comment by MonkeyFrogStudio** [comment]
This appears to be working consistently now. Thanks! :)
