### ISSUE TITLE
[SOLVED] Run against walls, models and you can see through them ..

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#255]
Run against walls, models and you can see through them ..
Only noticed today

**Comment by plemsoft** [comment]
Yes is made to stop more z fighting , so the near plane is moved up a little, to fix this you can set your camera distance to around 70 to stop it.

Or if you want the old setup , you can edit the setup.ini and change "lowestnearcamera=6" to "lowestnearcamera=2" , but this will then again produce more z fighting, so your best option is to lower your camera distance in tab tab :)

**Comment by thecyrus** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/236

**Comment by synchromesh62** [comment]
Can this be done by default somehow … I can alter it for me but not everyone else ?
We just had a blast at MP and it looks really bad when you get near a wall. I cannot adjust other player settings

**Comment by synchromesh62** [comment]
Going to try setting  my camera to 60 ( which works by the way ) and saving then try a MP game and see if everyone's sets that way ... If it does then no problem :)

**Comment by synchromesh62** [comment]
PERFECT !! 
works great even im MP :)

**Comment by korodai** [comment]
After trying this solution I can still see inside trees.

**Comment by plemsoft** [comment]
Repeat: Or if you want the old setup , you can edit the setup.ini and change "lowestnearcamera=6" to "lowestnearcamera=2" , but this will then again produce more z fighting, so your best option is to lower your camera distance in tab tab :)

Perhaps try : lowestnearcamera=4

**Comment by korodai** [comment]
I didn't have a "lowestnearcamera" in my setup.ini. I added "lowestnearcamera=2" and also slowly lowered the camera distance from 100 to 2, and I still can see inside trees. I'll try lowestnearcamera=4 next.

**Comment by plemsoft** [comment]
korodai: Are you running the latest beta ? "2018.06.15"+ lowestnearcamera is only supported in those version :)

**Comment by korodai** [comment]
Thanks for your help.  I only have the Steam public preview so I will have to wait for the latest beta.

**Comment by plemsoft** [comment]
This will also improve when this is solved:
https://github.com/TheGameCreators/GameGuruRepo/issues/256

**Comment by korodai** [comment]
I have 2018.6.18 now. With "lowestnearcamera=4" "lowestnearcamera=2" "lowestnearcamera=1" "lowestnearcamera=0" I can see inside trees.

**Comment by plemsoft** [comment]
korodai: Just lower your camera distance in tab tab until it goes away :)

**Comment by korodai** [comment]
Thanks. I think it happened because the trees were animated and were moving closer to the camera. It doesn't seem to happen with static trees that don't move.
