### ISSUE TITLE
GameGuru MAX - Bug or Request? - Developer Show Additional Developer Options Has to Be Checked Every Time!

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2552]
Every time I shut down and restart MAX Advanced/Show Additional Developers Options gets unchecked. This means I have to re-check it every time I restart MAX. And since you always have to hit that YES button every time you click the Developer TAB, this is a small PITA. Since we are actively testing MAX, I want this thing checked every time I am in MAX. And I probably always will. So, I don't know if this is a bug or not, but can we please get it so once this is checked, it stays check until we uncheck it?

Thanks. :)

**Comment by dllllllllllb** [comment]
I've mislabelled this, I thought that some settings aren't saving and you have to check them every time you launch.

The prompt shows up every time you go into the advanced / developer setting to let people know that these settings add a lot of things and could potentially break things.

The bool responsible for this is static, so it gets set to false every time you load GGM. We would either need to add another variable to the preferences (which I was told not to touch) or check if one of the settings is already turned on.

@rvanner @LeeBamberTGC  Should we change when the prompt popup shows up or leave it as is?

**Comment by LeeBamberTGC** [comment]
Currently a feature. Let's see if it gets in users way.

**Comment by ArgentArts** [comment]
I personally find the constantly clicking YES to proceed a PITA, but can live with it. What I don't want is to have to constantly reactivate Additional Developers Options each time I start MAX as I use them a good bit when testing something.

**Comment by LeeBamberTGC** [comment]
@rvanner What should happen here?

**Comment by rvanner** [comment]
@LeeBamberTGC I agree with @ArgentArts , one click to agree is enough for me. No point asking over and over again.

**Comment by MonkeyFrogStudio** [comment]
Zak has fixed this. Thanks! :)
