### ISSUE TITLE
Open GL problem on Dell G15 5511, RTX 3060, i7, Win11pro.

### ISSUE THREAD

**Issue by djeronimoBiH** [TheGameCreators/GameGuruRepo#2555]
I have this Win11pro problem (screen shot attached). Configuration is Dell G15 5511, RTX 3060, i7, Win11pro.

![GGMax OpenGL problem](https://user-images.githubusercontent.com/13538007/158906726-a2be3772-a471-4e32-b266-9e8f72634fee.png)

**Comment by mav3r1ck198-1** [comment]
do you know what GeForce drivers you are currently running? there were known conflicts between win11 and nvidia, especially whereby it couldnt "find" GPUs from the 30 RTX series. I had the same and rolled back to Win10. 

Also, i dont think that GGMax supports Win11 yet, its based around systems using Win10 so it could be in relation to that?

**Comment by djeronimoBiH** [comment]
I do not think win11 is the problem. It is somewere between OpenGL and GGMax.

**Comment by synchromesh62** [comment]
> do you know what GeForce drivers you are currently running? there were known conflicts between win11 and nvidia, especially whereby it couldnt "find" GPUs from the 30 RTX series. I had the same and rolled back to Win10.
> 
> Also, i dont think that GGMax supports Win11 yet, its based around systems using Win10 so it could be in relation to that?

Great info on the driver ( that's probably the problem )
But having asked around many are using Win 11 and have been for quite some time without any issue.
I have even tried it myself and there were no problems so it does support it for sure.

**Comment by djeronimoBiH** [comment]
![Nvidia](https://user-images.githubusercontent.com/13538007/159117172-817a45d7-6607-4177-a1c5-5ecc122ccebd.png)

**Comment by djeronimoBiH** [comment]
Just updated driver but still crashes with the same error :(

**Comment by plemsoft** [comment]
@djeronimoBiH Thanks for reporting this issue , it looks like the updater is using your integrated graphics card "Microsoft basic display adapter" , please try to update the drivers for your integrated graphics card and check if that solve the problem.

I have not tested on windows 11 , so this could be the problem.

Also another thing you could try is open "Nvidia Control Panel" -> "Manage 3D Settings" -> "Program Settings" tab, and add the "GameGuru MAX Updater.exe" to the list and make sure it use your "RTX 3060".

Let me know if any of this solve your issue, thanks for your help :)

**Comment by djeronimoBiH** [comment]
> @djeronimoBiH Thanks for reporting this issue , it looks like the updater is using your integrated graphics card "Microsoft basic display adapter" , please try to update the drivers for your integrated graphics card and check if that solve the problem.
> 
> 
> 
> I have not tested on windows 11 , so this could be the problem.
> 
> 
> 
> Also another thing you could try is open "Nvidia Control Panel" -> "Manage 3D Settings" -> "Program Settings" tab, and add the "GameGuru MAX Updater.exe" to the list and make sure it use your "RTX 3060".
> 
> 
> 
> Let me know if any of this solve your issue, thanks for your help :)
> 
> 
> 
> 

Ouuu this could be the solution. I've not checked my integ. card. Thank you and as soon as I try thos I will let you know about results.

Cheers.

**Comment by djeronimoBiH** [comment]
Noup, still the same

![image](https://user-images.githubusercontent.com/13538007/160235586-106a5dea-e228-41fe-8916-5cdf10e07179.png)

**Comment by plemsoft** [comment]
@djeronimoBiH Did you update your integrated graphics card drivers to support opengl 2 ?

**Comment by djeronimoBiH** [comment]
> opengl 2

I did
![image](https://user-images.githubusercontent.com/13538007/160236204-beb2642a-4e27-4798-92a8-e7ed8cc44641.png)

**Comment by djeronimoBiH** [comment]
Maybe I should try this https://www.youtube.com/watch?v=TsY_-PvB13g

**Comment by plemsoft** [comment]
@djeronimoBiH You did not update the drivers is still "Microsoft basic display adapter" , what card is the integrated ?

**Comment by djeronimoBiH** [comment]
wherever i check I only get MS Basic adapter

![image](https://user-images.githubusercontent.com/13538007/160236708-66bd0449-decc-438e-820c-536e97a0e937.png)

**Comment by plemsoft** [comment]
@djeronimoBiH Looks like "Dell G15 5511" use "Intel UHD Graphics " , so i would try to install the latest drivers from intel seams they recently added windows 11 support try this link: https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html
On that page try the "Automatic Driver and Software Updates" and check if its able to locate a new driver for you :)

**Comment by plemsoft** [comment]
@PaulSJ From our call today, when we get to windows 11 , perhaps its possible to check if Vulkan is available if OpenGL fails ? :)

**Comment by PaulSJ** [comment]
On laptops I believe the OS can choose which GPU an app runs on so even with Vulkan it might only see the integrated GPU available, and if OpenGL didn't work on it then Vulkan definitely won't. So in cases like these I think the only solution would be to update the integrated graphics driver.
