### ISSUE TITLE
AI - AI walks in place

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2557]
https://gyazo.com/903352fbc94b69747254d4856a6ef543
 https://prnt.sc/xi1cvwaAe45b

Edit: Some extra material, maybe it will help :] 
https://gyazo.com/ce434c7f4cd9b5c7770017d7c4d5199d

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Fixed for the next build. Was related to the overlap system not accounting for the Y location of the characters.
