### ISSUE TITLE
AI - Trigger boxed don't alert AI properly

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2558]
This happened to me with the 1st enemy encounter in the River Raiders demo.
Even though I'm inside the trigger box, AI just aims forwards and stands there.
![image](https://user-images.githubusercontent.com/61796872/158978896-ed8c4b7c-6570-4671-9b21-6aa71e069500.png)

**Comment by ZakJudges** [comment]
This happens to me as well. I think it was introduced as part of the optimisation work where AI only do anything if the player has line of sight on them. Whilst dormant, they don't respond to any visual logic

**Comment by LeeBamberTGC** [comment]
@ZakJudges Just so, all characters are dormant until the player camera sees them, and wakes them up. Also fixed a bug here so dormant characters also do not process their LUA script, to save performance and avoid them getting their animations stuck.  Triggers fine and billy bob now comes out when he sees you :)  Will be in next build.
