### ISSUE TITLE
Weapons - AI with Patrol Rifle deal 380 dmg to the player per shot

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2563]
@LeeBamberTGC I know you have changed the damage value to be higher so the weapon feels like a sniper, but it has also affected the enemy AI and I think it's a bit too powerful. 380 damage per shot is a bit too much for the player to handle, especially with multiple enemies.

Let me know what you think and if we should nerf the weapon damage or make AI deal less damage with it :]

**Comment by LeeBamberTGC** [comment]
@dllllllllllb See if you can nerf it to restore the damage of the sniper, but when the player shoots, it is x10 damage if they are using the zoom feature (secondary mode).
