### ISSUE TITLE
Enemies dance when they lose you after combat

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2568]
https://www.youtube.com/watch?v=rvIUAK6k9k8

To reproduce:
- approach a group of enemies so they notice you
- run away from enemies until they lose sight of you
- turn around and see them stuck until you get near them again

**Comment by LeeBamberTGC** [comment]
@ZakJudges FIxed for next build, they will idle at the last player spot position, and when combat time runs out, they return to their starting position.
