### ISSUE TITLE
Specular texture memory issues.

### ISSUE THREAD

**Issue by plemsoft** [TheGameCreators/GameGuruRepo#257]
when using pbroverride=1.

Old specular (_s.dds) is still loaded into memory, and are also copied to your standalones.

I expect this is caused by the _s.dds reference still being inside the dbo files and come in this way ?

Fixing this will give a nice boost in loading time and save memory.

To get a list of all loaded textures use:
producelogfiles=1
memgeneratedump=1

Im working at something else at the moment so if someone else would look at this, it is open.

**Comment by HierToo** [comment]
So if we delete the dbo files this is fixed?

**Comment by plemsoft** [comment]
No that will not help , the reference need to be inside the dbo, should just be ignored in PBR mode.
