### ISSUE TITLE
Standalone - "Skirt Grey" doesn't export to standalone properly

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2571]
In Level editor:
![image](https://user-images.githubusercontent.com/61796872/159044960-999664e5-4a18-4c02-8792-1a05a84d716f.png)

In standalone:
![image](https://user-images.githubusercontent.com/61796872/159045004-cb452d33-2d5b-4aa2-929a-1879798150b2.png)

**Comment by rvanner** [comment]
Confirmed as fixed.
