### ISSUE TITLE
GameGuru MAX - Minor Bug - Window Resizes After Test Game

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2572]
I've been doing screen shots for the manual at a specific size (1024 pixels across) and use a program called Sizer to ensure the windowed version of any program is exactly the size I need for any screen shots I take. Any time I do a test game (goes to full screen and then back to the editor) the editor GUI has been resized somewhat and I have to reset its size once again.

This is extremely minor, but I don't see any reason for the GUI's size to change here.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Seems to be fixed for the next EXP build:L
BEFORE:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/544a8a5a-3f2a-419c-8dac-88a1d189733d)

AFTER:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/82c70838-78c7-4b97-8e2d-37131d04d9fb)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC 

Unless the fix has not yet filtered down to the experimental build, this is still acting up. Here's a screen grab showing the issue:

![resize](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/abf5494d-d8e5-4a95-a218-870f18577e1c)

The screenshot contains two screen grabs overlaid on top of each other. The larger editor is 1920x1080 in size. After running a test game, then exiting, the editor has resized itself slightly.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio If you double click the title bar to maximise the MAX window, does it still happen?

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC 

If I resize the MAX editor to a window, then double-click the title bar to maximize it, and then double-click to go back to windowed mode, the MAX editor window restores to the previous size. Therefore, if I use Sizer (see first post) to get the editor to 1920 x 1080 for screen shot purposes, then run a test game (again, for screen shots), once I exit the test game, the MAX editor has resized (like the previous post with the overlapping screen grabs).

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Thanks for the extra info, I will check out 'Sizer'.  If you maximise MAX then run test game and come back, are you still maximised?

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC 

If I resize the window, then maximize and run a test game, when I return to windowed mode, the MAX editor is a very different size ... it's almost full screen, but not quite.

Here's the link to Sizer:

http://www.brianapps.net/sizer/

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Can you give me a step by step how to force SIZER to ewsize the MAX window so I can reproduce what you see, thanks:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f837ebb9-f706-4684-af0d-c05e7f55867e)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC 

With Sizer installed, resize the MAX editor to any size you like, other than full-screen, of course. Then move the mouse over an edge until the Windows arrows show up indicating you can resize the window. Instead of resizing, right-click. This will bring up the Sizer window with your sizes in it. Select one and the window who's edge your on will resize to that size.

BTW - from my limited tests, it's not Sizer causing the issue. If I resize the MAX editor to any size, leave it windowed, run a test game, and then exit the test game, the MAX editor window has slightly resized itself.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Excellent, confirmed:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b7f317b9-20db-487b-a093-c2c711e8bfd9)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Fixed for next EXP build, it seems the size taken was the child window, not the whole window, so it would eventually shrink to a VERY small window going back and forth, well spotted!

**Comment by MonkeyFrogStudio** [comment]
Thanks, @LeeBamberTGC ! :)
