### ISSUE TITLE
GameGuru MAX - Bug - Zone Issue with Delete and Undo

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2576]
Add a Music Zone:

![mzone1](https://user-images.githubusercontent.com/36735507/159047564-00ade9ed-8de2-45b4-a7f8-d2e802d0f0d2.png)

Decide you don't need it and delete it. Decide you do need it and hit CTRL+Z to undo your deletion (you'll have to hit CTRL+Z twice for some reason):

![mzone2](https://user-images.githubusercontent.com/36735507/159047641-d2c2ea31-0096-48b5-8bd8-43a6bdc9c732.png)

When you do this, the boundaries disappear and there's no way to resize the zone.

**Comment by ArgentArts** [comment]
In fact, this happens with EVERY ZONE of every kind - music, audio, text, trigger, etc.

**Comment by ZakJudges** [comment]
@ArgentArts Thank you for reporting this issue, I have added a fix which you should see in this weeks build :)
