### ISSUE TITLE
GG Max - Speed running

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2578]
Just created a standalone test game, and i was speed running in it.
Am not sure whether it just standalone or even when you sometimes test game.
Sprinting certainly needs some kind of stamina. Am not sure whether thats the cause, but it would make sense to run out of stamina when sprinting.

**Comment by ArgentArts** [comment]
Requested the same here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2400

**Comment by thecyrus** [comment]
This would be a great feature to add to GG Classic too...

**Comment by Tum1370** [comment]
This is still happening. If you have your character speed set at 100 he seems to run fast whatever weapon am carrying.
Can sorta adjust it by lowering player speed from 100. 
But really this should not be happening. 100 speed should be normal speed.

**Comment by Tum1370** [comment]
Am closing this one.
For some reason it is marked as an enhancement, but this was a bug, that is not in the newest builds.
