### ISSUE TITLE
update 3.18 2022    cant find original maps and cant load them in

### ISSUE THREAD

**Issue by UNIRD12B** [TheGameCreators/GameGuruRepo#2580]
just did the update and now I can no longer add in my original maps
by copying then in to the proper folders.
same with Projects folder.
and since there is NO SEARCH function at all ...I cant go from within GGMax
and try to locate them to load them in that way,,,,
Why are all original things still erased each time even this late in developement ????
HELPPPPPPPPPPPPPPPPP

UNIRD12B

**Comment by ArgentArts** [comment]
In the future, until we get regular updates that don't replace everything, just to the backup file that MAX creates and copy the entire contents of the "files" folder over the new "files" folder. When Windows warns about writing over files, select the "no to all" option so no files overwrite anything. That way, only your files will be copied over and they will all go into the correct places.

This way, it's just click-n-drag and done.

**Comment by UNIRD12B** [comment]
Thx so much ,
   very good answer ,
   ill try it next time for sure.
Thx
UNIRD12B
