### ISSUE TITLE
GG Max - Trigger points that alert enemy, but the enemy does not run out and attack

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2581]
The update to the AI seems to of messed up older AI that was previously setup.
Seems very buggy setting it up.

I had some characters that only spawned from trigger spots, but they spawn inside buildings, and after spawning, it should attack, as its been alerted, Then after the player attacks it, another one spawns by been alerted.
But they just spawn inside the building and dont run out and attack anymore.
Before latest build, they ran out and attacked after been alerted.
Also on this latest build, IF they hear a sound, but cant see you, they dont attack as well.

**Comment by Tum1370** [comment]
This is still happening in Early Release version.
Trigger points that alert and enemy, but the enemy does not run out and attack.

**Comment by rvanner** [comment]
@Tum1370 Could you attache a simple fpm that shows this issue? It would help Lee fix it quickly. Thanks.

**Comment by Tum1370** [comment]
@rvanner @LeeBamberTGC 
As requested just created a simple world. There are 2 enemy that spawn after the trigger zone has been moved in to by the character. The trigger zone alerts them, but they do not run out of the buildings until they either hear or see the character.

[BadAI.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8404647/BadAI.zip)

**Comment by Tum1370** [comment]
New Information.

How does the AI start to activate normally ?
I thought if we have an Enemy set to follow a path, That AI would start walking its path before the character sees the Enemy ?

But that is not the case, as Many times now i test this, And every time the AI Enemy just stands still, Until the player sees the AI Enemy. Then it starts to walk the path.

Looks terrible as the game seems like it has no life, And the life springs to movement when visible from the player. 
This needs fixing.

**Comment by plemsoft** [comment]
@Tum1370 Is this still a issue for you ? , tried your .fpm above but its damaged somehow ?

**Comment by plemsoft** [comment]
@Tum1370 Just tried this , and it looks like its working , only thing i had to do was increase the "View Range" see video and then they started to attach me.
https://www.youtube.com/watch?v=DAGjBh14bqk

**Comment by Tum1370** [comment]
@plemsoft Did you set it so the enemy can not hear, Maybe they heard you and ran out ?
Try this little test here. They dont run out when you move on to the grass, were they should as the trigger alerts them.
The view range is set to 2000
[TEST LEVEL.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11157373/TEST.LEVEL.zip)

**Comment by plemsoft** [comment]
@Tum1370 Ups forgot , you need to set the enemy to "Always Active" to get to those ranges, give it a test and feel free to close the issue :)

**Comment by Tum1370** [comment]
@plemsoft I still think this is a bug, Yes i changed the character on the level i sent to Always Active, and then they do run out and attack when the trigger happens.
But they are well within the 3000 min distance.
Really they should not be set to Always Active when within the 3000 AI activate distance ?

**Comment by plemsoft** [comment]
@Tum1370 There is no 3000 limit anymore , there are functions based optimizing that are all different, the way to avoid all optimizing/limits, is now to use "Always Active" :)

**Comment by Tum1370** [comment]
@plemsoft Ok ill close this one for now, as its easy fixed by using Always Active. Thanks
