### ISSUE TITLE
Crashing when looking for snake [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#2582]
GGMax_2022_03_18
GGmax close when just typing **SN** letters, as the video shows.

https://youtu.be/qbusg-C8qrA

EDI: The snake is not in the **animal** category.

**Comment by ArgentArts** [comment]
Can't reproduce that here. I can get through the entire word "snake" without issue.

**Comment by 3coms** [comment]
**The snake is not in the animal category.**

Just adding something:
Just realize that for every strange reason, I don't own the snakes on my animal's folders, maybe this is causing the error, GGMax looking for something that does not exist, and crash.

If so, you have to deal with keywords then don't throw results, or return null values.
And why I don't own the snakes?
