### ISSUE TITLE
GG Max - Zombies and armed soldiers can 'poke' through a closed door

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#2584]
https://youtu.be/Z38xJsgtrXY - recorded after last update; GG Max Build 2022.03.18

**Comment by synchromesh62** [comment]
In TGC's  Defence i am using the custom **door rotate script** created by Amen Moses.
I dont think the door blocker covers that one. 
Only the official Stock door.

**Comment by Ghost-l0l** [comment]
yeah, I saw that; It's interesting, because this door is a real physical object, you can put barrel next to it and door will push your barrel away, which can be very useful in many scenarios :) yet still can't stop those zombies

**Comment by synchromesh62** [comment]
If you just want to stop them dead place another door in the doorway and **untick** show on startup
This will allow you to walk through but put a break in the navmesh so they cannot pass.

![block](https://user-images.githubusercontent.com/35708217/159136051-7831676e-5a2b-44fd-860a-8e6bf32438e9.png)

**Comment by ArgentArts** [comment]
All enemies seem to go through doors with this last update. I've reported it elsewhere. This is with their own scripts, too. It was fixed for a moment ...  but is broken again. Lee is aware of it, though.

**Comment by AmenMoses** [comment]
> Only the official Stock door.lua which works totally differently.

Well if Lee or someone would communicate how the nav mesh blocking is supposed to work I'll happily change my script!

I suspect it is some internal engine thing though as I can't see any new Lua commands in the standard script.

**Comment by AmenMoses** [comment]
Just realised there are two door.lua scripts, one in scriptbank and one in the objects sub folder.

Just going to look at the objects one to see if I can see any clues.

**Comment by ArgentArts** [comment]
The soldiers and zombies also can pass through any door with the sliding door script, too. Just an FYI.

**Comment by AmenMoses** [comment]
RDBlockNavMesh( x ,y, z, radius, blockmode ) 

That's the new command, and it has been added to the sliding door script so obviously not working properly atm.

**Comment by LeeBamberTGC** [comment]
@Ghost-l0l Yes this was due to some duplicate scripts door sliding and rotating door. Now using official versions for next build :)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you confirm this fix for me, thanks!

**Comment by dllllllllllb** [comment]
@LeeBamberTGC They don't go through the door, but they stand inside of it 
![image](https://user-images.githubusercontent.com/61796872/159450837-0a1679ea-eceb-4f15-91bb-74de5ff77be0.png)

They also seem to really like the direction they were looking at when they got blocked by the door and refuse to rotate.
https://gyazo.com/d347465d3caf9febce28b0b27a949d2b

**Comment by LeeBamberTGC** [comment]
@Ghost-l0l In the latest EXP build the nav mesh blockers for closed doors will prevent a character from being allowed to stand inside a door, and will make their way to a valid nav mesh area. Can you confirm this issue is fixed for you, and if not, attach a small FPM so I can see how you reproduced it, thanks!
