### ISSUE TITLE
GG Max - female zombie falls on the ground and then stand up with buggy animation

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#2585]
https://youtu.be/FoYS9ZVYLkU

**Comment by rvanner** [comment]
Still happens in EA release

**Comment by ZakJudges** [comment]
@LeeBamberTGC In the animation "Zombie_Death_Back" - the zombie ends up face-down on the floor, but in "Zombie_Death_Back_Get_Up", the zombie is face-up. There is no 'get up' animation for when the zombie is face-down. Is it possible we are missing an animation? I could also just disable the zombie ability to get back up, if you'd prefer.

**Comment by LeeBamberTGC** [comment]
@ZakJudges Leave assigned to me, I have a female Zombie in my RPG demo being silly so can look at this :)

**Comment by LeeBamberTGC** [comment]
@Ghost-l0l Yes indeed, no correct animation pair for falling over and getting up. I have changed the behavior to Get Winded instead for which I DO have some animations :)  Adds more color to the combat and avoids the user waiting while the immune zombie gets back up :)  All correct now in next EXP build.
