### ISSUE TITLE
Player falls through the terrain on test game

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2587]
On the default Max map - enter test game and the press escape. Enter test game again and the the terrain will change textures and the player will fall through the map. 

Happens on 2nd "test game" and everyone afterwards. 

Creating a new level will cause the player to always fall through the terrain on test game.

**Comment by rvanner** [comment]
@Kitakazi Can you make a video of this please?

**Comment by Kitakazi** [comment]
Version 2022.03.25

https://youtu.be/Gg8RnjfnOOg

**Comment by rvanner** [comment]
@Kitakazi Thanks for the video.

@LeeBamberTGC Watch the video, it's displaying the same type of issues I have been having recently.
