### ISSUE TITLE
Underwatermode After Save standalone

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#259]
After save standalone:
**Underwatermode** does not exist in the **setup.ini** file and is not rendered in the game.
A number of new options added to setup.ini have the same status.
Please test and fix.

**Comment by plemsoft** [comment]
Thanks the following new variables are now also reflected in the standalone setup.ini

realshadowsize0,realshadowsize1,realshadowsize2,realshadowsize3,realshadowsize4,realshadowsize5,realshadowsize6,realshadowsize7,realshadowdistance,standalonefreememorybetweenlevels,memskipwatermask,underwatermode,memskipibr

Did i miss some ? :)
