### ISSUE TITLE
The good and the bad side of auto placement

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#2593]
Very frustrating , a button to turn of auto placement in the main gui instead off keep jumping to settings would be great and speed up workflow

https://www.youtube.com/watch?v=NUS2xTMXhRI

**Comment by ArgentArts** [comment]
Yes, please! 99% of the time I don't want auto placement at all. Please provide an easy way to turn this off. Requested something similar here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2412

**Comment by Granada1** [comment]
Fixed in latest build , thank you
