### ISSUE TITLE
GG Max Bug Report - Issues with Gyzmo to manipulate objects

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2594]
This has been happening for several versions of Max.
It is very difficult to manipulate an object with gyzmo.
Video : https://youtu.be/oDrcU2gxzVQ

**Comment by Granada1** [comment]
Use smart placement to put it where you want it then switch it off to do the final adjustments until a fix arrives 🤞

**Comment by synchromesh62** [comment]
Im finding even smart placement moves when you re-select and item.
Its great putting a light down but jumps for me on reselection.

**Comment by ArgentArts** [comment]
Reported in several places, including here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2469

Really, really want this fixed ASAP. :)

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Widget fixed for the next update :)

**Comment by ArgentArts** [comment]
Has the update been released with this fix yet? I wouldn't close this until it's been released and we've verified it as fixed. ;)

**Comment by LeeBamberTGC** [comment]
@ArgentArts I am always happy for original posters of an issue to close their own issue as it saves the core team having to do too much house cleaning.  I believe there is another issue with the same fix still open, so the issue is still present to be confirmed fixed by a second user.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
Yes, I confirm that it works fine now.
I close here.
