### ISSUE TITLE
Game Guru Max Problem with update 03.18

### ISSUE THREAD

**Issue by AlterMatz** [TheGameCreators/GameGuruRepo#2596]
Hi since the Update to 2022.03.18 i have a problem.
The software crashes after pressing the Buttom "Generate Terrain and open the level editor".
The software stopps and i am on the desktop. I tried to reinstall or deinstall but that did not help.

**Comment by thecyrus** [comment]
A lot of people is having this issue, already reported.
And it doesn't only crash while opening the editor, but also trying to play a level.

**Comment by mav3r1ck198-1** [comment]
Yup, this has happened 16 times for me since Friday, with 9 crashes ending in blue screen

**Comment by AlterMatz** [comment]
I hope they can fix it before the 25 of march.

**Comment by LeeBamberTGC** [comment]
@AlterMatz A fix has been applied to this weeks build that catches this crash and should hopefully resolve your issue. Do let us know here on Friday if all is well with your build, thanks!

**Comment by AlterMatz** [comment]
Thanks i will give you a feedback on friday.

**Comment by AlterMatz** [comment]
Great job! Everything works again. Demo can be played. Tarrain Editor does not crash. Zombies don't go through doors. Great job! Thanks.
