### ISSUE TITLE
GameGuru MAX - Crashing Frequently on Importing Models

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2597]
Most of my testing over the months have been with creating my own indoor test maps using my own models. Which means I've been using the importer a lot. Rarely have I encountered a crash (i.e. the importer, in the past, has been rock-solid). However, since the 3.18 update, I've gotten frequent crashes on importing new models. Crashes have been as frequent as 1 in 3 or half my imports. When I say crash, I mean that I'm exited completely out of MAX.

The crash occurs right after clicking the final button, after the imported model is shown against the background. Ultimately, the imported model is saved to the entitybank, though.

**Comment by Necrym59** [comment]
I can confirm this, I had reported it before and it seemed fixed for a while, now it seems to crash again after a few imports. Also while your at it can we have a importer that doesnt have to load into a map to use, one that is stand alone in its own gamespace using the asimp.dll. Then it could be launched from a button on the storyboad or as a standalone app.

**Comment by ZakJudges** [comment]
Hi @ArgentArts, could you confirm if this issue is now fixed for you in the latest build? Thanks

**Comment by ArgentArts** [comment]
@ZakJudges  So far, I'm getting no crashing when importing.
