### ISSUE TITLE
keys and switches

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2598]
Having an issue with keys and switches popping up with errors:

![image](https://user-images.githubusercontent.com/68471279/159188761-96a0ba36-41d0-45fa-8adf-340555968f6d.png)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/159188929-9529d352-ccdd-4911-b5e9-62ed1ff2bbcd.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you reproduce this one with stock assets?

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I'm not getting these errors.

@casigus Can you delete the scriptbank folder in "GameGuruMAX\Max\Files", update and verify files using the updater and let me know if you still get this issue :]

**Comment by casigus** [comment]
ah! was  going to give that a go actually! I'll post results when done !!!! 🙂
________________________________

**Comment by casigus** [comment]
yas all good now :)
