### ISSUE TITLE
MAX - 2022.03.18 - FPS Counter Not Independent of Game Logic

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2599]
Should display at all times and not be affected by in-game lua
In the Vid, keep an eye on the FPS counter top right of the screen

https://youtu.be/u1Zg0GqWjoA

**Comment by ZakJudges** [comment]
@plemsoft Having some trouble with this one. I've tried to move ShowMemDebug() so that it isn't affected when the hud is turned off, but I'm running into issues when ImGui tries to render it. Any ideas what approach you'd take? Thanks :)

**Comment by OldFlak** [comment]
Thanks for looking at this team.
While you are at it, can we have option to put it top center of screen as well :)

**Comment by OldFlak** [comment]
This issue has returned in EXP - 19-12-2022

**Comment by LeeBamberTGC** [comment]
@OldFlak Just tried with my simple test level on the EXP build, FPS/MEM shows even when PROMPT text now showing:
![image](https://user-images.githubusercontent.com/35840583/208417542-619089bb-4a46-4135-a7bf-6058741f3c0b.png)

Can you send an FPM level that shows it, might be related to which scripts are running?

**Comment by OldFlak** [comment]
Hi Lee - yes it happens when you have a script that hideshuds 
My levels all use a custm HUD, the custom hud uses HideHuds and that in turn hides the fps counter

Here be simple script - just attach to something (always active on) and run the level

[mycustomhud.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10262963/mycustomhud.zip)
 
Thanks for looking into it :)

**Comment by LeeBamberTGC** [comment]
@OldFlak I found code specifically designed to hide this when HIDEHUD feature was used. I have commented that code out so you can have it both ways. Now a user would untick this debug info if they wanted to do things like screenshots.  Uploading new EXP build now.

**Comment by OldFlak** [comment]
Thanks Lee - awesome tool this MAX would be, a fella you can be proud of :)

**Comment by LeeBamberTGC** [comment]
:)
