### ISSUE TITLE
Create a guide to help show how to use the Mega Pack 2 Dungeon pieces

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#26]
The dungeon folder from the Mega Pack 02 pack has pieces that create a dungeon, but it's not clear how they should be assembled to create a dungeon. Can a guide be created?

**Comment by Kasseyus** [comment]
Many of the models in the Mega Pack range were created by 3rd party authors and the instructions for their use may not always be available.  Trial and error are the best tools to use here, however many models such as this have been designed to clip together using the GameGuru grid system, which can be accessed by pressing 'B' twice within the software.  Any entity on your cursor will then conform to a rigid placement system until the grid is de-selected by a further press of 'B'.

There are 3 levels of grid.  1> No Grid.  2> Small Grid.  3> Large Grid.  Pressing 'B' will cycle through them.
