### ISSUE TITLE
Textures Medieval weapons are inappropriate

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#260]
Textures Medieval weapons are inappropriate

![snapshot1](https://user-images.githubusercontent.com/36647058/41617106-e5726c96-7414-11e8-879f-1f155a2e7c1b.jpg)
![snapshot2](https://user-images.githubusercontent.com/36647058/41617107-e59a0e22-7414-11e8-9bdb-99b39ad213f0.jpg)
![snapshot3](https://user-images.githubusercontent.com/36647058/41617109-e5bf9052-7414-11e8-9500-a87b305bb2dc.jpg)

**Comment by LeeBamberTGC** [comment]
They are appropriate for making Medieval games.

**Comment by HierToo** [comment]
You should verify you GG files. Your weapons have not a hand texture.

**Comment by Shahin3d** [comment]
This problem has been fixed in the new update.
I have no problem.
