### ISSUE TITLE
GameGuru Max launcher crashes

### ISSUE THREAD

**Issue by migervais** [TheGameCreators/GameGuruRepo#2602]
Hi there,
 
I just purchased GameGuru Max early access (OR: TGC94D9A7D4D) yesterday. After installing it I tried to run the launcher in administrator mode but the program crashes every time.
II was quite sure my configuration was ok but now I’M wondering if there is a memory issue or other potential problem. I have run a DxDiag and I’m pasting below some of the relevant data so you can have a look at it.
Regards
Michel Gervais
 
------------------
System Information
------------------
      Time of this report: 3/21/2022, 07:25:28
             Machine name: DESKTOP-NAFJUCC
               Machine Id: {F6103A14-6D11-48D3-B820-6EB3663A7565}
         Operating System: Windows 10 Famille 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
                 Language: French (Regional Setting: French)
      System Manufacturer: Dell Inc.
             System Model: Inspiron 7559
                     BIOS: 1.2.7 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 CPUs), ~2.6GHz
 
                              Mémoire physique (RAM) installée          8,00 Go
                              Mémoire physique totale            7,87 Go
                              Mémoire physique disponible    3,44 Go
                              Mémoire virtuelle totale             15,0 Go
                              Mémoire virtuelle disponible      7,93 Go
                              Espace pour le fichier d'échange              7,17 Go
 
                
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 120 DPI (125 percent)
       System DPI Setting: 120 DPI (125 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
DirectX Database Version: 1.3.5
           DxDiag Version: 10.00.19041.0928 64bit Unicode
 
------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
      Display Tab 2: No problems found.
        Sound Tab 1: No problems found.
          Input Tab: No problems found.
 
--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)
 
---------------
Display Devices
---------------
Card name: Intel(R) HD Graphics 530
        Manufacturer: Intel Corporation
           Chip type: Intel(R) HD Graphics Family
            DAC type: Internal
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_8086&DEV_191B&SUBSYS_07061028&REV_06
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
Driver Problem Code: Unknown
      Display Memory: 4158 MB
    Dedicated Memory: 128 MB
       Shared Memory: 4030 MB
        Current Mode: 1920 x 1080 (32 bit) (60Hz)
         HDR Support: Not Supported
 
Card name: NVIDIA GeForce GTX 960M
        Manufacturer: NVIDIA
           Chip type: NVIDIA GeForce GTX 960M
            DAC type: Integrated RAMDAC
         Device Type: Render-Only Device
          Device Key: Enum\PCI\VEN_10DE&DEV_139B&SUBSYS_07061028&REV_A2
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
Driver Problem Code: Unknown
      Display Memory: 8085 MB
    Dedicated Memory: 4055 MB
       Shared Memory: 4030 MB
 
------------------------
Disk & DVD/CD-ROM Drives
------------------------
      Drive: C:
Free Space: 836.8 GB
Total Space: 952.7 GB
File System: NTFS
      Model: ST1000LM014-1EJ164

**Comment by migervais** [comment]
Hello,

I didn't get any reply from you yet.
So far, I am unable to run the software I purchased

**Comment by LeeBamberTGC** [comment]
@migervais Your system does not appear to meet the minimum specifications. Best you apply for a refund at this time. We are looking to test on lower-end systems, but for release our min specs are:

MINIMUM CONFIGURATION
Supported OS: Windows 10 or newer (64-bit versions only).
Processor: Intel Core i5-7400 | AMD Opteron 4274 HE, or better.
RAM: 16GB
Video Card: NVIDIA GeForce GTX 970 | AMD Radeon R9 Fury, with 4 GB VRAM, or better
Notebook support: Laptop models of these desktop cards may work as long as they are on-par in terms of performance with at least the minimum configuration.
DirectX: Version 11
Hard Drive Space: 30 GB available space.
Peripherals Supported: Windows-compatible keyboard and mouse
Network: Broadband Internet connection
