### ISSUE TITLE
Objects in the basement collection appear black when inside buildings (compared to other objects)

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2604]
@PaulSJ Lee wants you to look into this issue please. Is there an issue with their textures?

![image](https://user-images.githubusercontent.com/1503593/159298013-8f74925b-867a-478d-a4f9-dab196656902.png)

![image](https://user-images.githubusercontent.com/1503593/159298296-7dfd01e0-60ce-48a0-890a-4ab09e6f6a30.png)

**Comment by PaulSJ** [comment]
@rvanner Some of the objects such as the Distribution Box have all 0 in their ambient occlusion texture, this makes it appear black under ambient lighting. It should have at least some non-zero values in there for most objects.

**Comment by rvanner** [comment]
@PaulSJ Thanks for that info.

@LeeBamberTGC Is there a quick way to add data to the assets missing AO data?

**Comment by LeeBamberTGC** [comment]
The AO channel is now inside the _SURFACE texture so this needs to be repaired for all affected models.  The quickest way is to load in all these textures, and add WHITE to the channel controlling AO, and include these in this week's build. You need someone who can load, edit and save these DDS texture files.
Paul, can you let Rick know which channel (RGBA) includes the AO, it escapes me right now :)

**Comment by PaulSJ** [comment]
It's the red channel

**Comment by rvanner** [comment]
@ZakJudges Can you sort these assets out please?

**Comment by ZakJudges** [comment]
@rvanner will do. Is it all objects from the Basement Collection?

**Comment by rvanner** [comment]
I don't think it's all of them. Eg the blue brick walls seem fine. Place them down into a room and see which ones turn black.

**Comment by ZakJudges** [comment]
Thanks for the extra info, will do

**Comment by rvanner** [comment]
@ZakJudges Please get the new files added to the build this morning. Thanks.
