### ISSUE TITLE
Widget is Broken

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2605]
Place any entity on the map and try to move it with the widget. Click the arrows will instantly move the entity in random direction by a small amount. Click the drag boxes of the widget will instantly move the entity a large amount in a random direction, making the widget near impossible to use. 

See video: https://www.youtube.com/watch?v=elYTymzP9Ew

**Comment by ArgentArts** [comment]
Reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2594

and here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2469

**Comment by ArgentArts** [comment]
I disagree with labeling this as a "medium" bug. It makes it virtually impossible to use the widget/gizmo to place elements in your game level. And, at times, it can cause real issues, such as causing an element to fly off screen or under the terrain. It's a serious bug that is causing me to stop work on my game levels.

**Comment by Ghost-l0l** [comment]
Agree with Argent Arts - it's very important issue; And it gets waaay worse when you add more assets to your lvl.  Rotating is also very glitchy. It's slowing down building every level by few, or sometimes few dozen clicks Per Object! In more complex levels you literally need to chase your assets around the map!

**Comment by rvanner** [comment]
@Ghost-l0l and all. Lee knows you all want it fixed, it's on his list! :-)

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for next update :)
