### ISSUE TITLE
Multiple crashes 

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#2607]
Windows 10 professional 64-bit
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
RAM: 32GB
GPU: Nvidia GeForce GTX 3060 RTX

Max version: 2022.03.18

Multiple crashes since update, usually within 5 minutes of opening the software.

If i manipulate the terrain in the terrain generator, crashes to desktop
ALL demos crash within 5 minutes of beginning to play
Manipulating the terrain whilst in the editor

MY Pc has bluescreened 9 times out of 16 crashes over 3 days

**Comment by dllllllllllb** [comment]
Related - #2608

**Comment by LeeBamberTGC** [comment]
@dllllllllllb See if you can reproduce, thanks!

**Comment by dllllllllllb** [comment]
@mav3r1ck198-1 Can you please update your Nvidia drivers and GameGuru Max to the latest version. Let me know what version of GGM you're on and if GGM still crashes for you.

**Comment by mav3r1ck198-1** [comment]
Hello! My Nvidia drivers are the latest 512.15, and i did a fresh install on Max with evening. No change in the amount of crashes, ALL the demos crash within a couple of minutes

**Comment by mav3r1ck198-1** [comment]
completely fresh install this evening, 9 crashes in 4 hours, 1 blue screen

**Comment by Ratall** [comment]
@mav3r1ck198-1 They will need a full DxDiag dump plus Copies of your Guru-Game.log  and Guru-MapEditor.log if you have them to have any hope of diagnosing this.

**Comment by rvanner** [comment]
@mav3r1ck198-1 Is this still happening in the latest version for you?

**Comment by mav3r1ck198-1** [comment]
@rvanner the latest update is much more stable for my system now :) altho will still crash when using custom assets

**Comment by rvanner** [comment]
@mav3r1ck198-1 Could you share your custom models that crash MAX's importer? That would help the team hunt down the issues.

**Comment by plemsoft** [comment]
@mav3r1ck198-1 If you dont like to post the custom assets that crash MAX here, please e-mail the object to me and i will have a look e-mail: plemsoft@plemsoft.com , thanks for your help :)

**Comment by plemsoft** [comment]
@mav3r1ck198-1 Will close this as its now stable on your system :) , if you have a issue with custom assets crashing please open a new issue, Thanks.
