### ISSUE TITLE
Shadows and bad light in process lightmap

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#261]
After doing the process lightmap -SHIFT + (F4)
 Shadows and bad lighting and appear unrelated
(Lighting is Static Mode = Yes)

![snapshot4](https://user-images.githubusercontent.com/36647058/41626524-c186880e-7431-11e8-81b6-becdbdca6ad6.jpg)
![snapshot5](https://user-images.githubusercontent.com/36647058/41626526-c28bae1e-7431-11e8-8e48-7d2e36cd3176.jpg)
![snapshot7](https://user-images.githubusercontent.com/36647058/41626552-d6657370-7431-11e8-8237-6041c2d24b0c.jpg)
![snapshot9](https://user-images.githubusercontent.com/36647058/41626567-e5e5e668-7431-11e8-8a71-717e4bcebb06.jpg)
![snapshot11](https://user-images.githubusercontent.com/36647058/41626568-e60d3ccc-7431-11e8-9cb7-e5c3073be1d6.jpg)

**Comment by plemsoft** [comment]
@Shahin3d Thanks for reporting this,

Could you test this in the latest version and let me know if this has been fixed , thanks :)

**Comment by plemsoft** [comment]
Normals on lightmapped objects was fixed in a previous update.
