### ISSUE TITLE
Latest version GameGuruMAX cannot create my own level

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#2610]
Latest version of MAX, all demos work fine, any custom map i create crashes MAX to the desktop

video here https://youtu.be/xl7mMxvXZ_w

i have uninstalled and reinstalled twice issue persists, i have attached the log file
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8323134/Guru-MapEditor.log)

**Comment by GraPhiX-Guru** [comment]
Here is a video when opening a Demo, as you can see that works fine
https://youtu.be/_54Lbu39YOc

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you reproduce this for me with stock media, thanks!

**Comment by GraPhiX-Guru** [comment]
Been scratching my head with this, i have tried numerous things to no avail but this morning Nvidia released Driver Version 512.15 (Game Ready) so i did a 'Clean' Install of Nvidia Drivers my previous drivers were 511.** so they were not that far out of date.
After installing and re booting i can now load my custom levels !! not sure why the driver fixed it for me when the demo levels ran with 511.** but strangely it cured my problem, the driver install must have touched something i may of missed.

I hope this information may help others with similar issue.

![nd](https://user-images.githubusercontent.com/35724756/159654928-df17e8de-f8f1-4bde-9c5a-aa8a6874caf8.png)

New video https://youtu.be/qnyEe1Uwwfg
