### ISSUE TITLE
flags not working?

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2613]
Either flags aren't working, or I'm not using them correctly.

Character gets the the 1st one and then doesn't move on, but continues to walk on the spot. Youtube video link showing issue below.

https://youtu.be/7rdEKINELT8

**Comment by ArgentArts** [comment]
@davetgc Did you connect the character to the first flag (seems so) and the first flag to the second flag, the second flag to the third, etc., using the logic connectors after clicking on the Shooter Icon?

![flags](https://user-images.githubusercontent.com/36735507/159503949-590ed83c-e69e-4520-a6cd-623911f22bdd.png)

**Comment by ArgentArts** [comment]
Awesome! 

You should probably close this issue then, so TGC doesn't go searching for a bug. :)

**Comment by LeeBamberTGC** [comment]
@davetgc I have added some extra code so the character comes to a stop when they run out of flags they can validly follow.  Connecting the flags creates the path.
