### ISSUE TITLE
Collision Issues and falling through 

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#2615]
![github](https://user-images.githubusercontent.com/82544140/159521240-719f2058-4cc2-4aa9-adb8-a41c581e231d.png)

This is potentially caused by user error so please bear with. 

Flattened the top of a mountain, added my own asset (castle turret), applied polygon collision, added a start marker to walk the walls and pressed test game.  when in the game. the character falls through the asset and then falls through the terrain, as per the image attached.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you try reproducing this, thanks!

**Comment by dllllllllllb** [comment]
@mav3r1ck198-1 Can you please send me the custom asset that you're experiencing this issue with. My email: maciej@thegamecreators.com ( Please include link to this issue in your email, saves me time trying to figure out which issue the email is relating to :] )

**Comment by rvanner** [comment]
@mav3r1ck198-1 Can you send in your level that shows this? We need to be able to see it happen to be able to fix it. Thanks.
