### ISSUE TITLE
GGMAX - Enemy Characters

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2619]
Is it possible to have the enemy characters not start in T pose in game when at a distance.
![tpose_enemies](https://user-images.githubusercontent.com/95015657/159604717-cb83c808-21ab-4f0a-a1a1-e1f8dd76c425.png)

They do show ok in the editor though
![enemy_editor](https://user-images.githubusercontent.com/95015657/159604741-50ac2465-2c95-47da-9762-4b65c1e9f11e.png)

**Comment by dllllllllllb** [comment]
@Necrym59 Can you please make sure GameGuru Max is up to date. I've tried this on the latest build and characters aren't starting in T-poses. This was an issue that got fixed not that long ago.
![image](https://user-images.githubusercontent.com/61796872/159666517-03bd38f1-aedd-49ed-ac0a-d3320352364c.png)

**Comment by Necrym59** [comment]
Well i took that image today on GameGuru MAX Build 2022.03.18
But after looking at it again its not every time its random, so i wouldnt be too concerned about it, and its only at long distance probably past the 3000 script limit .

**Comment by dllllllllllb** [comment]
@Necrym59 Our Internal build has this fixed. I'll leave it open for now, if you see this issue again with build version 2022.03.25, tag me here and I'll label it properly :]

**Comment by Necrym59** [comment]
Yep seems to be fixed now.
