### ISSUE TITLE
problems after Save game : In the Player Checkpoint and Musicinzone sections

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#262]
After Save Standalone and run game and save game:
I see two problems after run game and Save the stage.
(problems after Save game : In the Player Checkpoint and Musicinzone sections)
Please see the attached video and test and fix
The Fpm file is in the attachment.

Problem number 1: After dying
Music turns off.
And again, you need to go back to 
Musicinzone to turn the music on.

Problem number 2:
After Loding stage
Area (Player Checkpoint) does not work
And if you died ...
You will be redirected to the
 first part of the game. Namely: (Player Start)

![untitled](https://user-images.githubusercontent.com/36647058/41656730-37ba653a-74a6-11e8-987d-f6c27d988a9a.png)

[mapbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2119141/mapbank.zip)

[Checkpoint-movie.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2119341/Checkpoint-movie.zip)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
I uploaded his zipped video to You Tube.. Not great quality but shows the issues
https://youtu.be/cGQcOKEAPrI

**Comment by LeeBamberTGC** [comment]
For next update.
Added ability back in to specify the sound of the Player Checkpoint
Checkpoints now restore any looped sounds playing
Standalone SAVE GAME and LOAD GAME restore checkpoint info and sound loop states
