### ISSUE TITLE
GameGuru MAX - Bonus Content Gone with Last Internal Update?

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2620]
I updated just a moment ago and the bonus content (sci-fi male and female figures, etc.) are not found. I had a few of them in my test levels and they're not there any more and they cannot be found when I go to add them (bonus content is not a part of the menu now).

**Comment by rvanner** [comment]
This is by design. The bonus content will have to be installed via the downloadable installer from your TGC account. Only pre-order customers get this content and so we needed to take it out now before the release version.

**Comment by ArgentArts** [comment]
Just downloaded and installed my order and the bonus content is not there. So, how do I get the bonus content back?
