### ISSUE TITLE
If Intro video is set to play, it should not play after a game is played from the HUB when you come back

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2622]
If Intro is set to play on boot up, don't show it if MAX is reloading after a game has been played from the HUB.

**Comment by rvanner** [comment]
@dllllllllllb Not sure if you are the right person for this. Assign to who can fix it quickest, it needs to be fixed before release. Thanks.

**Comment by dllllllllllb** [comment]
@rvanner I'll look into it and if I can't get it done within 1/2h I'll assign it to someone else

**Comment by dllllllllllb** [comment]
Since the GGM is restarting after you quit the game, I think it will need to save and read a setting when exiting / loading. I don't want to mess things up before release.

**Comment by rvanner** [comment]
@dllllllllllb That's how I'd do it. So some flag that says this was started from the HUB and not from scratch. We need this in so please code it.
