### ISSUE TITLE
Playing standalone game won't let you load a different project

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2623]
~~When you press "Play Game" on Demo X, exit it and then load Demo Y, you will get Demo X storyboard.~~
When you play a game from the Demo section, you can't load a different level without restarting GGM.

Video: https://www.youtube.com/watch?v=Y7ExCgL3TzA

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Added code at end of welcome HUB processing the special flag, so if final destination is the HUB, the flag is reset so the storyboard is no longer affected:

	if (bReturnToWelcome == true)
	{
		bSpecialEditorFromStandalone = false;
		bReturnToWelcome = false;
	}

**Comment by LeeBamberTGC** [comment]
NOTE: On server by 12:30
