### ISSUE TITLE
Trees - "Western Pine Tree" is loaded in as "Cactus Var 1"

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2625]
Steps to reproduce:
Place a bunch of Western Pine Trees,
Save level
Load in a different level
Go back to the level with Western Pine Trees

![image](https://user-images.githubusercontent.com/61796872/159687716-67b9bc51-6df9-47dd-b192-395a0c241e10.png)
![image](https://user-images.githubusercontent.com/61796872/159687746-5c6994e9-0066-4a74-9b53-1418dfe44b7d.png)

**Comment by PaulSJ** [comment]
Thanks, should be fixed on master branch
