### ISSUE TITLE
cannot get to level editor

### ISSUE THREAD

**Issue by Grogadog** [TheGameCreators/GameGuruRepo#2626]
after getting to terrain editor and making a couple of minor changes to size etc. I click the create level and goto level editor button and the game drops out out to desktop. I have removed GameguruMax with revo uninstaller and re-installed (2 hours). still same problem.
Same thing happens when I try to play a demo game - okay until it says loading level editor, than drops to desktop.
my laptop.

OS Name	Microsoft Windows 11 Home
Version	10.0.22000 Build 22000
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	STEVESOMEN
System Manufacturer	HP
System Model	OMEN by HP Laptop 17-cb1xxx
System Type	x64-based PC
System SKU	2S386EA#ABU
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	AMI F.15, 15/09/2020
SMBIOS Version	3.2
Embedded Controller Version	5.30
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	8748
BaseBoard Version	05.30
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Binding Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United Kingdom
Hardware Abstraction Layer	Version = "10.0.22000.527"
Username	STEVESOMEN\steve
Time Zone	GMT Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.8 GB
Available Physical Memory	7.66 GB
Total Virtual Memory	18.2 GB
Available Virtual Memory	6.08 GB
Page File Space	2.38 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualisation-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualisation Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes
 display -
Name	NVIDIA GeForce RTX 2080 Super
PNP Device ID	PCI\VEN_10DE&DEV_1ED3&SUBSYS_8748103C&REV_A1\4&1848D782&0&0008
Adapter Type	NVIDIA GeForce RTX 2080 Super, NVIDIA compatible
Adapter Description	NVIDIA GeForce RTX 2080 Super
Adapter RAM	(1,048,576) bytes
Installed Drivers	C:\WINDOWS\System32\DriverStore\FileRepository\nvhm.inf_amd64_d745ea92fee8ab77\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvhm.inf_amd64_d745ea92fee8ab77\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvhm.inf_amd64_d745ea92fee8ab77\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvhm.inf_amd64_d745ea92fee8ab77\nvldumdx.dll
Driver Version	30.0.14.9733
INF File	oem69.inf (Section052 section)
Colour Planes	Not Available
Colour Table Entries	4294967296
Resolution	1920 x 1080 x 144 hertz
Bits/Pixel	32
Memory Address	0x77000000-0x77FFFFFF
Memory Address	0x30000000-0x3FFFFFFF
Memory Address	0x40000000-0x41FFFFFF
I/O Port	0x00004000-0x0000407F
IRQ Channel	IRQ 4294967272
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\NVHM.INF_AMD64_D745EA92FEE8AB77\NVLDDMKM.SYS (30.0.14.9733, 37.79 MB (39,626,408 bytes), 29/01/2022 09:35)

**Comment by Grogadog** [comment]
just seen other user has same issue. https://forum.game-guru.com/thread/223405

**Comment by PaulSJ** [comment]
Can you rename the file "Max/GameGuruMAX.exe" and replace it with this debug version https://drive.google.com/file/d/13sUz32VZHmxbT-hHifHvcczNOefsS8Eb/view?usp=sharing it will be a lot slower but should hopefully give you an error message instead of a crash

**Comment by Grogadog** [comment]
---------------------------
GameGuruMAX.exe - System Error
---------------------------
The code execution cannot proceed because VCOMP140D.DLL was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

**Comment by GraPhiX-Guru** [comment]
I believe you have The Visual C++ Redistributable Packages missing you will need to install x86 and x64 versions from Microsoft

**Comment by PaulSJ** [comment]
Sorry, I forget about the debug runtime, place the following DLLs next to the EXE https://drive.google.com/file/d/1RjZMuTjZCuz6UqUReR1MMU39-MaIWiMa/view?usp=sharing you can delete them when you are done with the debug EXE.

**Comment by Grogadog** [comment]
No I have these. I have visual studio on my computer

**Comment by Grogadog** [comment]
[image: image.png]

**Comment by Grogadog** [comment]
Okay, I have replaced the .exe file in the 'max' folder. i have placed the
two debug files in the 'max' folder. same problem, drops to desktop.
S.

**Comment by Grogadog** [comment]
[image: image.png]

**Comment by thecyrus** [comment]
So many of us have reported this problem, it's really weird.

**Comment by Grogadog** [comment]
Just a note, I think this is the first time i have tried GGM since windows
11 update!

**Comment by Granada1** [comment]
`Just a note, I think this is the first time i have tried GGM since windows
11 update! `

there are a few it us running windows 11 so it should be ok 👍

**Comment by ArgentArts** [comment]
FYI - Running MAX on Windows 11 here with no issues.

**Comment by PaulSJ** [comment]
@Grogadog Unfortunately I can't see your image, can you upload it somewhere, or add it to a comment through the Github webpage?

**Comment by Grogadog** [comment]
sent to github S.

**Comment by acratwastaken** [comment]
<img width="294" alt="Capture99" src="https://user-images.githubusercontent.com/102273604/159835226-2d8a05b9-650f-4fa8-a799-adeaccdd7157.PNG">
I had the same issue and tried all the solutions. now I have this

**Comment by Ratall** [comment]
see also #2596

**Comment by PaulSJ** [comment]
@Grogadog Can you try this version and see if it solves the problem https://drive.google.com/file/d/1ATOJsaeB8PY8jmmW1EOGQD8ab9kmdleI/view?usp=sharing

@acratwastaken Does the assertion say what file or line it happened in?

**Comment by Grogadog** [comment]
Yes this works, level editor loaded, added an asset and saved - okay so
far. added trees, paint, and veg , no problem , saved and run - okay.
Thanks.
Steve

**Comment by Grogadog** [comment]
Thanks for help, creating scenes - the randomized landscapes are great - no more messing with individual trees etc. (unless you want to of course). Looking good.

**Comment by Grogadog** [comment]
---------------------------
GameGuruMAX.exe - System Error
---------------------------
The code execution cannot proceed because VCOMP140D.DLL was not found.
Reinstalling the program may fix this problem.
---------------------------
OK
---------------------------
