### ISSUE TITLE
GameGuru MAX - BUG - Resized Window Hides Create New Game Button!!!

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2627]
If you resize your freshly opened GameGuru MAX, the Create New Game Button and the tick box below it disappear:

![resize1](https://user-images.githubusercontent.com/36735507/159786578-e9e68ffb-6089-4d86-8d10-293d8dd6c3a8.png)

It doesn't matter which color scheme (at least the default blue or this dark one), it's not apparent that you can scroll down to access it. It just looks like you can't proceed to create a new game from here. But you can scroll down after all:

![resize2](https://user-images.githubusercontent.com/36735507/159786808-addf3043-66d2-4c46-9a90-136b9b955ad8.png)

This area needs to resize with the window so the button and tick box are always visible to the end-user.

**Comment by plemsoft** [comment]
@ArgentArts Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by ArgentArts** [comment]
Fixed! Thanks!
