### ISSUE TITLE
GameGuru MAX - Bug - Resized Window Major Issue with Terrain Generator Window!!!

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2628]
If you try to run MAX in a Window, it causes issues with the Terrain Generator Window:

![resized3](https://user-images.githubusercontent.com/36735507/159787843-03efd169-89be-44a6-a9c5-30a45a563c74.png)

The reason I want to run MAX in a window is for creating tutorials. My monitor is an ultrawide (3440x1440) and I have MAX resized to 1920x1080 for video capture purposes.

**Comment by ArgentArts** [comment]
If you don't get this when you resize the MAX window with the Terrain Generator, after resizing, move the window around. You should see the view port area does not move correctly with the rest of the window.

**Comment by ArgentArts** [comment]
https://user-images.githubusercontent.com/36735507/159858015-f21fbcd6-a8b9-48ee-82ff-126f8b5e65aa.mp4

**Comment by plemsoft** [comment]
@ArgentArts Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by ArgentArts** [comment]
Fixed! Thanks!
