### ISSUE TITLE
Game Guru Max - High FPS speed issue

### ISSUE THREAD

**Issue by Zorgo33** [TheGameCreators/GameGuruRepo#2629]
When testing game guru max and getting around 240 fps on a test level, speeds of enemy and animal, sometimes weapon animations seem a little bit sped up. The video below might not show it perfectly, but sometimes it's very noticable when playing any levels.

Here's a video showing the issue
https://www.youtube.com/watch?v=ohuf3oFTPZ8&ab_channel=Zorgo33

**Comment by AmenMoses** [comment]
Why on earth would you be running with vsync off?

**Comment by ArgentArts** [comment]
This is why you want to have vsync on. ;)

**Comment by Zorgo33** [comment]
I have vysnc on, my monitor's refresh rate is 240hz

**Comment by LeeBamberTGC** [comment]
@Zorgo33 Does this still happen with the mammal creatures in the latest EXP build, I believe work has been done to tie movement deltas to FPS independence now.
