### ISSUE TITLE
Model importer completely broken.

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#263]
Model doesn't show up in preview, there is no thumbnail, if you go through the motions to import it the model is the correct shape but the texture is shrunken and tiled on it many times.

![app](https://user-images.githubusercontent.com/36109432/41716807-9230e166-754f-11e8-8c3f-3bc3997a73f5.jpg)
![app2](https://user-images.githubusercontent.com/36109432/41716814-9836ee20-754f-11e8-955e-0dce0e7fccfd.jpg)
![app3](https://user-images.githubusercontent.com/36109432/41716824-9e2f8332-754f-11e8-967a-013f585fe656.jpg)
![app4](https://user-images.githubusercontent.com/36109432/41716829-a167b6d2-754f-11e8-852f-a0de558e2ac5.jpg)

**Comment by BodRH** [comment]
It's obviously not the models, I tried some others which had the same result so I made my own .fpe files and thumbnails and the models are fine.

![pow](https://user-images.githubusercontent.com/36109432/41722229-c1e63680-755f-11e8-81d4-2512fb0ffdc9.jpg)

**Comment by LeeBamberTGC** [comment]
Can you send me the model and textures at the point you are importing them to me at lee@thegamecreators.com, thanks!

**Comment by BodRH** [comment]
I've sent the model and texture from the last picture but you can try it with any .x model, it's the same with them all, unless you use apbr_noalpha.fx there is no model showing in the preview and if you do use no alpha the model is completely black, at the moment there is only the _color.png texture, I don't make the others until I have finished the model set which share a texture because I am always adjusting it.

**Comment by LeeBamberTGC** [comment]
Fixed for the next PP build. The model in its native state has no texture file assigned (just reports material_color) which suggests no texture file was associated with the mesh, but the importer now shows the model with a blank texture which you can then replace with the texture that accompanies the model.
