### ISSUE TITLE
Enemies able to shoot you through walls

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2632]
![enemythroughwall](https://user-images.githubusercontent.com/32545391/159914078-59af59c9-638a-4f7d-a37e-1502168c9cac.png)

If an enemy is in a room with a locked door and they are alerted to you, in some buildings they are able to shoot you through the walls

**Comment by rvanner** [comment]
@ZakJudges Is this still an issue?

**Comment by ZakJudges** [comment]
@rvanner I'm no longer being shot at through the walls, but the enemies weapons and hands are still visible and can be shot

**Comment by Granada1** [comment]
Had this problem yesterday so I will add to this

**Comment by LeeBamberTGC** [comment]
NOTE: Several iterations of the AI has fixed ray casting through this buildings walls, and AI script for better targetting and path finding. Also improved nav mesh commands in the script to handle when character trapped outside a valid nav mesh.  No more shooting through this wall.
