### ISSUE TITLE
If you highlight a zone sphere and then press TEST Level, the sphere appears in the game

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2634]
eg:

![image](https://user-images.githubusercontent.com/1503593/159934993-801c1f20-14d3-4862-a8d7-195de89cdde5.png)

**Comment by dllllllllllb** [comment]
@rvanner I can't get the sphere to stay in the level. Every time I move my mouse over "Test Level" or any UI element / game object it disappears https://gyazo.com/97191f49737910b1a552a6ddecee10f3
