### ISSUE TITLE
Terrain editor - Auto flatten interaction

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2638]
https://gyazo.com/cb304338d33b93bae7ba9ad63207384a

Steps to reproduce:
Place an object with autoflatten enabled
Have the object you just placed selected
Edit terrain
Go back to object tools

**Comment by ZakJudges** [comment]
Closing this issue as could not reproduce, and there have been fixes to the autoflatten system since this issue was created
