### ISSUE TITLE
Not all doors can be opened.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2639]
Only the following doors can be opened or given keys.

'Building door light red' (both versions, 'DOOR1', 'Building - light brown', 'warehouse Green door'

**Comment by dllllllllllb** [comment]
I've added a door that doesn't have the door behaviour by default. Changed static mode to Physics on and added a "Door Rotate" behaviour. When I try to open it, the door disappears : https://gyazo.com/ba7e00c502a580df368369afbc60bd08

**Comment by davetgc** [comment]
Also, I got the jail door working, but it's incorrectly set up and the
model rotates from the centre.

**Comment by davetgc** [comment]
True, but the average user isn't going to want to do that :).

**Comment by synchromesh62** [comment]
Then they would have to use the official door.lua 
but probably still have to create their doors the same as the TGC ones - pre animated

**Comment by synchromesh62** [comment]
> I've added a door that doesn't have the door behaviour by default. Changed static mode to Physics on and added a "Door Rotate" behaviour. When I try to open it, the door disappears : https://gyazo.com/ba7e00c502a580df368369afbc60bd08

You must have **isimobile** ticked ..

**Comment by davetgc** [comment]
Will do.

**Comment by ZakJudges** [comment]
@davetgc Is this now sorted for you?

**Comment by davetgc** [comment]
Yes, it is.
