### ISSUE TITLE
GG MAx - Switch Escape Demo - Switch for first door has moved 

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2643]
As the title says, Just tried the Switch Escape demo on Early Release Max, and it seems like the switch to raise the first door has been moved accidentally from above the pipe.
See pic

![Untitled](https://user-images.githubusercontent.com/66874403/160162761-2e9ff130-d343-476b-8ee0-7a9ef842987c.png)

**Comment by dllllllllllb** [comment]
@Tum1370 This was deliberately done to hide the switch at the beginning of the level. I didn't notice that there was another part to this switch :] I'll move it and send the .fpm to Lee.
