### ISSUE TITLE
GG Max - problems with placing, rotating and scaling and some thoughts about bugs in general

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#2646]
https://youtu.be/pSnWhD9ZZXg
Placing, rotating and scalling objects still buggy;
Video recorded with Max Build 2022.03.25

**Comment by rvanner** [comment]
@LeeBamberTGC This is the video I mentioned in our call today. Please watch the whole video to see the problems Ghost lol has had making his levels and also to see his suggestions for reducing the size of textures. If you disagree with changing the texture compression format then please document why in this thread.

**Comment by rvanner** [comment]
@Ghost-l0l Lee made some changes in the last update. Have these improved the widget for you or is it still buggy?

**Comment by Ghost-l0l** [comment]
Its improved; Not perfect, but improved - objects no longer "escape" form your cursor, so thats a big step in right direction :D Rotating and scalling can still be buggy, but that also depends on particular objects - depending on how the axiss are set in any given asset it can be very somooth or very problematic; But in general I'd say it's much better now!

**Comment by LeeBamberTGC** [comment]
@Ghost-l0l Latest EXP build on Steam corrects smart object positioning, the widget and the grid/snap system. Hopefully a better placement experience awaits :)

**Comment by ZakJudges** [comment]
Hi @Ghost-l0l, are you still seeing issues in the latest build? :)
