### ISSUE TITLE
Shooting Weapons Once Again Drops Frame Rate

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2650]
Seems like issue from #2097 is back. Or something similar. 

Tested on the snow level, just equip the AK47 and starting firing. FPS will steadily decline.

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue, could you try this .exe and check if its improved:

https://drive.google.com/file/d/13Awt70p_ORwd9ulb66iW2rSUaKZ-6uD8/view?usp=sharing

If not could make a screenshot with tab open so im able to see where the CPU/GPU times is used when fps drops, Thanks for your help :)

**Comment by plemsoft** [comment]
@Kitakazi Ups forgot please also check if the .exe improve this issue : https://github.com/TheGameCreators/GameGuruRepo/issues/1601

**Comment by Kitakazi** [comment]
No sir the new .exe did not improve the issue. Very small but it seemed to make the issue slightly worse. Also made #1601 slightly worse as well. 
Here is a video of the issue I used the .exe you linked for this video. 
https://youtu.be/IySK__iHpzw

And just FYI I am using the steam version of Max now.

**Comment by Kitakazi** [comment]
Hmm I just tested with the normal .exe and Im not sure if the issue was actually worse with your new .exe it was really hard to tell i'd overall about the same.

**Comment by Kitakazi** [comment]
With the last update frame rate dropping with weapons is fixed now
