### ISSUE TITLE
GGMAX 25 MAR Version - Stutter (on Snowy Demo) 

### ISSUE THREAD

**Issue by cybernescence** [TheGameCreators/GameGuruRepo#2652]
Moderate to severe stutter experienced:

Choose Snowy Demo
Play Game - first run through seems fine, c. 50FPS
On death within level, choose continue then start game
After reload, stuttering starts pretty much  immediately.

(Specs RTX2070 Super, 32GB RAM, I7)

Cheers.

**Comment by plemsoft** [comment]
@cybernescence Thanks for reporting this issue, could you try this .exe and let me know if it fix the stutter on second run :)

https://drive.google.com/file/d/13Awt70p_ORwd9ulb66iW2rSUaKZ-6uD8/view?usp=sharing

If not could you make a screenshot with tab open so i can see where the CPU/GPU times is spent when you have the stutter , Thanks for your help :)

**Comment by cybernescence** [comment]
Hi Preben - unfortunately still seems the same with that build.

I see you are now THE Dear IMGUI expert :) Outstanding job on all those UI widgets!

Cheers

![Snowy Stutter](https://user-images.githubusercontent.com/35750023/160240155-3cba8f58-6ec9-4070-aa88-71b4a3b3c088.png)

**Comment by plemsoft** [comment]
@cybernescence Thanks :) , could you make a screenshot where it dont stutter so i can see the difference (values) , thanks :)

**Comment by cybernescence** [comment]
It's quite difficult to catch the point it stutters (micro stutters) but I tried. The first profile column, is first run plays Ok, second and third are different times to try to snapshot the stutter period. The third column popped up extra CPU and other stats (see red box)? Bit weird though might be a red herring / profiler glitch - but if accurate adding on a huge 31ms?
![Snowy Stutter 2](https://user-images.githubusercontent.com/35750023/160271974-b56eb680-4dd0-4a93-9a7e-eff42d7fe69d.png)

**Comment by plemsoft** [comment]
@cybernescence Please test this on the 2022.04.08 version and let me know if it fix your issue, also the double CPY Frame bug was fixed, thanks for your help :)

**Comment by plemsoft** [comment]
@cybernescence Any news on this ? :)

**Comment by cybernescence** [comment]
This issue can be closed. Thanks @plemsoft
