### ISSUE TITLE
Error Code And Untextured Enterties

### ISSUE THREAD

**Issue by GrobyKen** [TheGameCreators/GameGuruRepo#2654]
Is anyone else getting this  half textured enterties? I have checked the fpe file and all textures are there. It's happening across all the packs.  I'm also getting a Run Time Error 7018 on a regular basis
![GGMax](https://user-images.githubusercontent.com/66643109/160236919-15f2536a-ed9c-4023-8693-c2a29fdf61a0.jpg)
.

**Comment by GrobyKen** [comment]
OK so I run the file checking process and it found 1.2 Gig of files needed looking at. I assume this is a check sum test or something similar. After that a quick test has shown the entities to be now OK. Not checked all yet and the 7018 error has not yet occurred. I will carry on testing and come back here if it happens again but in my case it looks like it could have been some corrupt file downloads. I did download the entire 24 Gig in one hit.

**Comment by GrobyKen** [comment]
Seems to have cured the problem. So watch those downloads :)

**Comment by AlterMatz** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/2656
I had the Runtime Error 7018

**Comment by GrobyKen** [comment]
Could be as it was for me, see above.

**Comment by AlterMatz** [comment]
I created an ebe. Then a second one in the same level. There was a crash while saving. Then the error code. The stored Ebe was represented as a cube and not as a room. After I deleted them from the folder, the error was gone.
