### ISSUE TITLE
Runtime Error: 7018() Game Guru Max

### ISSUE THREAD

**Issue by AlterMatz** [TheGameCreators/GameGuruRepo#2656]
I do not know if this reported already. After using the Lagacey Structur Editor i become an Error. Runtime Error:7018()
The designed room is not in the directory but only a cube. Any idea? Otherwise, everything is going great. A room only works two rooms as constructing EBE in the same level leads to a crash while safing the structure. Creating individual rooms separately and later merging them into a level is possible
![Error](https://user-images.githubusercontent.com/100475522/160248467-1a41e820-bc2a-4ce4-a3e5-43e3404edc8b.JPG)
.

**Comment by AlterMatz** [comment]
After deleting the crashed Structure the Error is gone. Any clue?

**Comment by LeeBamberTGC** [comment]
@AlterMatz Any chance you can create a short video from initial launch of MAX through to using the Structure Editor and this crash, it will really help narrow down the culpret :)

**Comment by AlterMatz** [comment]
Hm there is a small problem. I don't have the error anymore at the moment. As I said, I wanted to create 3 EBE rooms in one level. After pushing the rooms together, a room in the EBE folder preview was displayed as a cube. When restarting Max, the error message came. I deleted the broken room with everything that goes with it and the error was gone. I could try to recreate the error. This error comes mainly when something is to be saved and something wents wrong . Had the error already when a character should be saved and something went wrong. The character or object was then previewed as a cube in Max. If this broken file is deleted, the error is also gone. So it looks like the error comes when a file is broken and Max tries to load it. Sorry for my broken English ;)

**Comment by AlterMatz** [comment]
![Error2](https://user-images.githubusercontent.com/100475522/160429987-c4c88670-dcf7-4dbc-9cd9-b08f82689948.JPG)
When i load the Level this is what i got
![Room](https://user-images.githubusercontent.com/100475522/160430280-61247058-64a7-4c9e-b722-685a56070ca9.JPG)
This is how the room looks in orginal.
I tried to recreate the Error but it does not happen.
It only occurs when something goes wrong when saving a character or EBE.
The defective file is displayed in the Entinity database as a cube in the preview. Deleting it solves the Problem with the Error. Sorry that I can't really help. If the error occurs again, I will report with video.

**Comment by Smeghead911** [comment]
This is also happening to me. I can edit the levels with some objects, but most of them seem to bring up the Runtime Error: 7018()
The following collections bring up the error: Arctic, Basement, Buildings, Characters, Fence, Industrial, Jungle, MAX, Shanty Town.
Bonus and Booster Packs don't bring up the error though, they're fine.
The attached capture doesn't show the error box, just me clicking on it (but it's invisible to me on the capture...)
I can't load anything above 10mb unfortunately so the capture is cut to the actual clicking on the Arctic assets, then the error pops up, click ok and GGMax closes down.

https://user-images.githubusercontent.com/102665573/160826366-0a04b4fc-3eec-4357-b303-bdb2459c2891.mp4

**Comment by LeeBamberTGC** [comment]
@Smeghead911 If you are a Steam user, you can try running the VERIFY FILES that will ensure you are not missing any files. This issue can happen if there are missing files in the installation or corrupt files.

**Comment by Smeghead911** [comment]
Hi Lee,
Thank you for responding, I am a Steam user, however my GGMAX was purchased as an early adopter from the TGC website. I'm just updating to 2022.03.29 currently. I think that I can link my GGMAX to Steam later anyway. I have done with other apps that I didn't purchase through Steam originally.

**Comment by LeeBamberTGC** [comment]
@Smeghead911 Understood. Probably best you make lots of backups then do a fresh install and remove any old files from the dev phase builds. Steam includes all the assets and skips our internal auto update systrem so should be a very reliable way to get the latest files all nice and clean :)

**Comment by Smeghead911** [comment]
I'll try that if the update still brings the issue up. Looking at the entity bank files, they all seem to be there on my machine but I could be missing something.
Thanks again for the advice.

**Comment by Smeghead911** [comment]
Happy to report that the update to 2022.03.29 seems to have fixed my issue :)

Tried all of the lists of game objects and none of them resulted in the error.

The initial install must have somehow missed or dropped some files.

**Comment by LeeBamberTGC** [comment]
@Smeghead911 That is excellent, thanks for reporting back!!
