### ISSUE TITLE
GameGuru Max runtime error 7018(Loading-main)

### ISSUE THREAD

**Issue by tacooo12** [TheGameCreators/GameGuruRepo#2657]
Trying to run demo games I get the runtime error 7018(Loading-main). Also when I try to make a level I can make a level, but can not use 3d objects. I try to add a 3d object or simply hover over a selection and I get the runtime error 7018(0).

**Comment by AlterMatz** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/2656
Had the same Problem

**Comment by AlterMatz** [comment]
Hm there is a small problem. I don't have the error anymore at the moment. As I said, I wanted to create 3 EBE rooms in one level. After pushing the rooms together, a room in the EBE folder preview was displayed as a cube. When restarting Max, the error message came. I deleted the broken room with everything that goes with it and the error was gone. I could try to recreate the error. This error comes mainly when something is to be saved and something wents wrong . Had the error already when a character should be saved and something went wrong. The character or object was then previewed as a cube in Max. If this broken file is deleted, the error is also gone. So it looks like the error comes when a file is broken and Max tries to load it.

**Comment by LeeBamberTGC** [comment]
@AlterMatz If you find a way to reliably create the broken asset, and can provide a step-by-step, we should be able to fix this to prevent it from happening in the future.

**Comment by tacooo12** [comment]
I updated my video card driver. That did not do much to help that I could tell. I have tried hovering over the 3d models and some show up fine and others turn white. And others like the exploding barrel cause the runtime error. I can place the ones that show up fine after hovering my mouse pointer, such as the crow, or non exploding barrel. The rabbit is a cube when placed in a level and the rat is a tiny sphere(weird). I managed to place a gun, ammo, and grenades, so I did have something to play with. Took a look at some of the DDS files and some look fine and others are white such as the campfire.

The model file I assume is the dbo file and the exploding barrel(1k) seems small compared to the non exploding rusty barrel(223k).

**Comment by plemsoft** [comment]
@tacooo12 The "Barrel Explosive.dbo" should be 171kb, if its only 1kb on your system then you had a download problems , please try to redownload everything again :)

**Comment by tacooo12** [comment]
This last update was a winner. The demos now work fine. I will look at the level maker next to see if things are working there also.

**Comment by tacooo12** [comment]
Ok I've done my best to look at the models and the ones with problems in the Showcase Collection are the sewer rat( no 3d model), AKM rifle(file folder looks to be labeled wrong or FPE file is referenced wrong for the model), and the Lit Candlestick(does not appear when selecting it for placement). In the MAX Collection, the Lit Candlestick(does not appear when selecting it for placement-same with the dying campfire), the Dying Campfire, and the Rock Boulder has problems(At one point it was named Lee and showed up as a white sphere, very strange). Just one in the Industrial Collection- the Red Short Industrial Stairs(does not appear when selecting it for placement). If I see anything else or experience it I will report it.

**Comment by LeeBamberTGC** [comment]
@tacooo12 If you are running the Steam version, try the VERIFY FILES method to make sure all your needed files are on your local PC.

**Comment by tacooo12** [comment]
Lee,

I am not running GG Max on Steam. I have been using the verify files method in the app by checking for updates. I guess the Steam version is your priority now, so I will be patient, that you will update the download for the non-Steam version at some point soon.

Dale

**Comment by ZakJudges** [comment]
Apologies for the late response. This should be fixed, now that we have gone Steam only
