### ISSUE TITLE
GGMAX - Missing ladder sounds

### ISSUE THREAD

**Issue by dennimoto** [TheGameCreators/GameGuruRepo#2658]
The sound files that are referenced in the ladder behavior description ("Climbing Loop" and "Exit Climb") seem to be missing. Steam version.

**Comment by Necrym59** [comment]
There is none the option is there for you to supply if you want other sounds, 
just use the footsteps sounds available in max to suit thsi is what i use.

**Comment by dllllllllllb** [comment]
@dennimoto Sounds aren't attached to ladders by default. "Climbing Loop" and "Exit Climb" sounds don't exist in the max library. If there is a ladder sound missing from one of the demos, please let me know which demo has this issue.

**Comment by dennimoto** [comment]
I haven't notice any missing sounds in the demos.

It was the way I had interpreted the text in the behavior description that led me to believe there were default sounds to select, so my bad. ;)
