### ISSUE TITLE
MAX - Clicking widget causes object to teleport 

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#2659]
TItle. The widget, when first clicked to start dragging the entity around, will cause the entity to "shoot" in a direction based on the widget arrow/box as if you had jerkily dragged it in that direction. This makes the widget completely unusable. 

https://user-images.githubusercontent.com/56294129/160258186-78479179-8eaa-49e3-91b7-c146b209f632.mp4

**Comment by ArgentArts** [comment]
This has been reported several times here on GitHub. In one of them, Lee has stated it's fixed for the next update.

**Comment by fearlesswee** [comment]
Ah my bad then, I haven't seen any of them so I presumed I was the first to report this.

**Comment by ArgentArts** [comment]
No worries. This gizmo/widget bug has been a real PITA and I can't wait to get the update! ;)
