### ISSUE TITLE
Failed to download the file list, error 0, please try again

### ISSUE THREAD

**Issue by cernisr** [TheGameCreators/GameGuruRepo#2663]
I'm unable to install the early access version of GGM. After about a 10 second pause, I get this message. I've tried dozens of times at various times of the day over the last 3 days. Running as Admin makes no difference. Windows 10 x64.

**Comment by Necrym59** [comment]
Did you purchase a steam key version

**Comment by cernisr** [comment]
No.

**Comment by LeeBamberTGC** [comment]
@cernisr If you like you can contact TGC support and they will be happy to switch you to a Steam Key as the installation process is different enough it might bypass the issue you are having with the non-Steam installer.

**Comment by ZakJudges** [comment]
Closing this issue: Auto-updater no longer in use - all users sent Steam keys
