### ISSUE TITLE
Importing custom objects

### ISSUE THREAD

**Issue by Sayajina** [TheGameCreators/GameGuruRepo#2664]
Hi all. I'm a Rhinoceros 3D user and I've noticed I'm not being able to import custom objects inside Guru Max, despite trying either FBX or .X formats when exporting from Rhino. I still need to try some other softwares regarding importing/exporting, but wondering why this might be happening.

Error message says it fails to load, suggests converting the model file to the latest export version of the format (?)

Any thoughts?

**Comment by Granada1** [comment]
Sounds like the ring exporter needs updating !

**Comment by ArgentArts** [comment]
From what I understand, MAX uses ASSIMP for importing files. It's pretty robust. I know I have no issues importing FBX exported from Blender. One thing you might want to try is importing your FBX into Blender and re-exporting from there. Then importing into MAX. Since we all know that Blender's FBX export format works fine with MAX, perhaps this will do the trick for you?

With Rhino, are there a few different FBX versions to choose from when exporting? FBX gets updated all the time. Perhaps your version of Rhino is using an older version.

**Comment by Necrym59** [comment]
Try using the free fbx converter from autodesk
https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives

**Comment by Sayajina** [comment]
> From what I understand, MAX uses ASSIMP for importing files. It's pretty robust. I know I have no issues importing FBX exported from Blender. One thing you might want to try is importing your FBX into Blender and re-exporting from there. Then importing into MAX. Since we all know that Blender's FBX export format works fine with MAX, perhaps this will do the trick for you?
> 
> With Rhino, are there a few different FBX versions to choose from when exporting? FBX gets updated all the time. Perhaps your version of Rhino is using an older version.


Thought of this and it sounds like the best way indeed. I will try this out, thank you. 

Still, considering Rhino is up to date and most of my workflow is based there, I'm curious enough to learn if any of the FBX export settings could be tweaked to sort this out for future purposes. 
![Rhino7-fbx export options](https://user-images.githubusercontent.com/102475953/160418783-73b4f7d2-f4f9-4d51-a846-ce54820094af.jpg)


I've been postponing my blender tutorials, but I think it's about time I jump into this and bring the best out of all knowledge backgrounds. Great effort for the community, thank you all for replying.

**Comment by Sayajina** [comment]
Back here again with updates:

Turns out, the solution to the importing custom model issue was right in front of me.
Either Blender or Rhinoceros exported FBX files are well read by MAX importer, no need to convert them again on Blender or such. 

My mistake was that the source FBX file was on a different Drive Disk from where I've installed Guru Max, so it probably didn't find the correct authorizations to access it properly.
I've decided to make copies of imported files within the Guru Max installation directory and does seem to do the trick.

Problem solved. But, sometimes Guru Max still crashes with no warning after creating a custom library asset. When I reload the app, the asset exists in the library and it is usable, but maybe sharing all this experience might be helpful for the developers.

Happy to be tweaking with this incredible software. Eager to see it fully developed and not just for shooting games, but also for any kind of customized digital interaction <3

**Comment by LeeBamberTGC** [comment]
@Sayajina Glad you found a solution for importing your FBX files, the issue with new entities being added while MAX is running and then crashing is reported in another issue report so I will close this one as complete.  Do let us know if you find other exports not behaving as this is a vital component to being able to create your own style and vision for your games.
