### ISSUE TITLE
GuruMax will not GO!

### ISSUE THREAD

**Issue by iplayablockhead** [TheGameCreators/GameGuruRepo#2669]
Program starts and get to loading screen then just quits/shuts down!
My RIG is - i7-4790 CPU @ 3.60GHz windows 10 64bit OS with 32GB memory and a 1060 6GB Nividia

I have tried deleted the readme file as per the DEV, if you require any other details please ask.
I have posted on steam community hub on several occasions like others. 

THANK YOU

**Comment by LeeBamberTGC** [comment]
@iplayablockhead I have uploaded a fix to the PUBLICPREVIEW. Let me know if this works for you. Instructions here: https://forum.game-guru.com/thread/223455

**Comment by iplayablockhead** [comment]
I have uninstalled, reinstalled, tried the public beta, have removed the VR setting and even deleted the readme file... nothing helped to date. So the GameGuru is still not working

**Comment by iplayablockhead** [comment]
if you would I could stream/record a video of what it is doing with the task manager open also to show you...
I also noted that in the task manger, when GGM was starting and the is was not responding it was trying to launch a map editor 32bit version. have not idea is this has anything to do with it but trying to help out.

IS there a crash report somewhere I could post?

**Comment by LeeBamberTGC** [comment]
@iplayablockhead I have updated a new PUBLICPREVIEW on Steam, update to that then run the VERIFY FILES. Let me know if that fixes things for you :)

**Comment by iplayablockhead** [comment]
I fid that yesterday. And am on the Publix previewSent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Lee Bamber ***@***.***> Date: 2022-03-29  6:33 a.m.  (GMT-05:00) To: TheGameCreators/GameGuruRepo ***@***.***> Cc: iplayablockhead ***@***.***>, Mention ***@***.***> Subject: Re: [TheGameCreators/GameGuruRepo] GuruMax will not GO! (Issue #2669) 
@iplayablockhead I have updated a new PUBLICPREVIEW on Steam, update to that then run the VERIFY FILES. Let me know if that fixes things for you :)

**Comment by LeeBamberTGC** [comment]
@iplayablockhead I made the update about 30 minutes ago, that one should restore your version as intended, and allow you to run and keep your projectiles too :)

**Comment by iplayablockhead** [comment]
Thanks will test shortlySent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Lee Bamber ***@***.***> Date: 2022-03-29  7:09 a.m.  (GMT-05:00) To: TheGameCreators/GameGuruRepo ***@***.***> Cc: iplayablockhead ***@***.***>, Mention ***@***.***> Subject: Re: [TheGameCreators/GameGuruRepo] GuruMax will not GO! (Issue #2669) 
@iplayablockhead I made the update about 30 minutes ago, that one should restore your version as intended, and allow you to run and keep your projectiles too :)

**Comment by iplayablockhead** [comment]
Okay that patch seems to have corrected the issue. Thank uSent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Lee Bamber ***@***.***> Date: 2022-03-29  7:09 a.m.  (GMT-05:00) To: TheGameCreators/GameGuruRepo ***@***.***> Cc: iplayablockhead ***@***.***>, Mention ***@***.***> Subject: Re: [TheGameCreators/GameGuruRepo] GuruMax will not GO! (Issue #2669) 
@iplayablockhead I made the update about 30 minutes ago, that one should restore your version as intended, and allow you to run and keep your projectiles too :)

**Comment by LeeBamberTGC** [comment]
@iplayablockhead Awesome, thanks for confirming!!
