### ISSUE TITLE
The SHADER OPTIONS settings - Lighting = REALTIME: are not saved

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#267]
The SHADER OPTIONS settings - Lighting = REALTIME: are not saved
And returns to PRE-BACK mode

![untitled](https://user-images.githubusercontent.com/36647058/41812987-23cb69ea-7742-11e8-8e3a-ba812baa2b5d.png)

**Comment by LeeBamberTGC** [comment]
Can you provide a step by step from a blank level, lightmapping it and observing when the problem above shows itself, thanks.

**Comment by Shahin3d** [comment]
Thank you
I do not have a problem.
