### ISSUE TITLE
Reports of No behaviour for static objects for Characters 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2671]
As the title states im seeing quite a few Reports of **No behaviour for static objects for Characters** on the forum and Steam 
This shows up on the right behaviour panel and you cannot do anything with it.

**Comment by ArgentArts** [comment]
It's strange, too. I tested every character in MAX after a fresh install and none of them come in for me as static objects. They all come in as characters with their character behaviors.

**Comment by synchromesh62** [comment]
> It's strange, too. I tested every character in MAX after a fresh install and none of them come in for me as static objects. They all come in as characters with their character behaviors.

Same for me to be honest yet i do recall the same issue not long ago with my doors suddenly giving the same error but a reboot sorted it. This does not seem to be the case with these users.

**Comment by Tum1370** [comment]
I have had this several times to, The last time it happened for me was on the latest Steam version.
I am sure a reload of Max sorted this for me. But still it needs fixing.

**Comment by ZakJudges** [comment]
Hi all, has anyone seen any more reports of this since the latest update?
