### ISSUE TITLE
MAX Crash issues from users who have contacted us via support

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2674]
User#1
I got the key and installed GGM on my computer. I'm trying to launch GGM, but it's not launching
Video: https://youtu.be/djEeILxysD8
CPU Intel Core i9-10940X BOX
Memory 32 GB
Video GeForce RTX 3050 8GB
All latest drivers. I click the LAUNCH button in Steam, but it had no effect. I also tried to stop the antivirus. I'll send the video later.
================
User#2
While start Gameguru Max its stops working after loading screen
[user2.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8362120/user2.txt)
=================
User#3
I couldn't launch the program, it crashes when I try to launch it. I'd like to make a guide video but it doesnt seem possible, now. But I will make a video about this technical problem, soon. You may check it on my Youtube channel. Here is the link: 
PC Specification:
CPU: AMD Ryzen 5 3600 MPK 3.60GHz
GPU: Gigabyte GeForce GTX 1060 WINDFORCE OC
RAM: PNY XLR8 (2x8GB) DDR4 3200MHz
M2: PNY XLR8 CS3030 500GB
SSD: Samsung 860 Evo 250GB
Mainboard: Asus Prime B450M-K II
==================
User#4
Hi there I have tried to download the latest version, but it won't run. I get an error message. I have tried twice now and just get the same message.
Not sure how to deal with this.. also it takes many hours to download is that normal? I am running a 1050 graphics card on an i7 processor.
![image](https://user-images.githubusercontent.com/1503593/160386389-dae4524c-ca02-497a-9cb8-ff17b538948a.png)
![image](https://user-images.githubusercontent.com/1503593/160386460-afdfc45b-a55b-476e-be10-3df86c607f86.png)

**Comment by LeeBamberTGC** [comment]
@rvanner 

* From User 1 I need the their "Guru-MapEditor.log" from the "Documents\GameGuruApps\GameGuruMAX" folder
* User 2 does not meet minimum specifications: GeForce GT 710 is a terrible GPU.
* User 3 specs look fine, I need the video to know more
* I need to know what GPU user 4 has

**Comment by thecyrus** [comment]
For those who don't meet the minimum requirements, GG Max just crashes.
It would be better to display a message like "Your system does not meet software requriements", or correct it to run anyway but slower and let them take the risk.

**Comment by ynamdev** [comment]
I tried to run GGM on Different PC with 4GB GTX 1650 Graphic Card but the Framerate of the Game is terrible at that machine too, I have high hopes with GGM.

**Comment by LeeBamberTGC** [comment]
@thecyrus So you know of other software that implemented your idea well, as it would be good to get some inspiration on how they go about it. Detecting every type of CPU and GPU is not an option, but maybe there is a smarter way?

**Comment by LeeBamberTGC** [comment]
@ynamdev Alas the 1650 is below the minimum specification as the GPU does not have the horsepower to push the work we need MAX to do. The current min spec is a GTX 970 or above (about 9000+ on PassMark).

**Comment by thecyrus** [comment]
I don't know Lee, maybe catching the exception that causes Max to crash, it happens when a machine is way below the requirements and it must crash for a reason.

I remember early Alpha's that used to run slow on a test machine I use with a GTX 760, now it just crashes to desktop.
It's not a huge or priority issue btw.

**Comment by rvanner** [comment]
Closing this now because these issues are no longer being reported.
