### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Artyimeus** [TheGameCreators/GameGuruRepo#2675]
When i place something like a Wall and later when i want to change the position, when i select it and move it 1 millimetre the wall just disappears and its soo far away from the position it was. I can still move it but it isnt working properly. Just 1 millimetre and i need to struggle to put it back where it was.

**Comment by Granada1** [comment]
This is being fixed as we speak , hopefully a update will be out soon including the fix

**Comment by Artyimeus** [comment]
> 

alright thanks

**Comment by Granada1** [comment]
Looks like the fix is up now , follow this to get the update please 

https://forum.game-guru.com/thread/223455

**Comment by dllllllllllb** [comment]
@Artyimeus As Granada1 said, this is a known issue and is being worked on.
Once the improvements roll out and you come across any issues please let us know :]

**Comment by Artyimeus** [comment]
@dllllllllllb Sorry to say that but it still doesnt work. when i want to change the position its gonna move soo far away, that i need to search it. I tried the current update + with the tutorial @Granada1 said

**Comment by Granada1** [comment]
I can’t try this today but it was working fine yesterday , I will try again tomorrow if allis well and I can get on my comp

**Comment by dllllllllllb** [comment]
@Artyimeus Thanks for reaching out. We ideally need a video to see in which scenarios the object placement doesn't work as it should.
