### ISSUE TITLE
Selected sounds for Player Start are not copied after the Save Standalone.

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#268]
Selected sounds for Player Start are not copied after the Save Standalone.
And only the folder (voices\player) is copied.

![c-1](https://user-images.githubusercontent.com/36647058/41813106-b0d26e68-7744-11e8-83f4-5e446d00f9bb.jpg)

![c-2](https://user-images.githubusercontent.com/36647058/41813109-bf52c6a4-7744-11e8-8802-6120799a31ec.JPG)

**Comment by plemsoft** [comment]
@Shahin3d Thanks for reporting this,

This has been fixed and are ready from the next update :)
