### ISSUE TITLE
Zombies struggle on slopes

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2682]
https://user-images.githubusercontent.com/32545391/160433850-ad586a16-ba85-4305-b24f-7566e9634370.mp4

**Comment by ZakJudges** [comment]
Note: still an issue in recent builds. Happens when on a slope, and the player is standing in a spot that is not accessible within the navmesh.

**Comment by LeeBamberTGC** [comment]
Added new commands to master interpreter that can detect if a target can even be reached.
