### ISSUE TITLE
GameGuru MAX - Updater Bug - Updater In a Perpetual State of Install

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2685]
After updating to today's internal build, the updater never gets to the finish line, letting me know I can start MAX. After installing, the button at the bottom says, "Install GameGuru MAX":

![install](https://user-images.githubusercontent.com/36735507/160451333-7df78d03-38a1-44d0-a3de-a9ba0bf31235.png)

If I click that, it goes through the install process all over again and I end up back at the same screen all over again. The only way out is to click the "X" at the top-right. Once you do that, you can use the GameGuru MAX desktop shortcut (or the EXE) to run MAX normally.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Good find. Should be fixed in 20 minutes.

**Comment by ArgentArts** [comment]
Updater worked perfectly with this last update (3.29).
