### ISSUE TITLE
switch and lights do not work as in broadcast 81

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#2687]
please see link the nodes do not work
https://forum.game-guru.com/thread/223448#msg2647340

**Comment by dllllllllllb** [comment]
@Pcskiller It works perfectly fine on my end. https://www.youtube.com/watch?v=5jEi0yMsdkQ

Can you please delete the scriptbank folder in GameGuruMAX\Max\Files and update GameGuru Max.

**Comment by Pcskiller** [comment]
ok will try it
