### ISSUE TITLE
Light placement not working as it should be

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#2688]
Light locks when dragged in ,Steam latest build files verified and rebooted

https://www.youtube.com/watch?v=jFVpQaPoFtU

After closing and re opening Max seems to have sorted itself out ,so I will close this for now 🤞

**Comment by ArgentArts** [comment]
I am getting this, too. However, it only happens if I have the widget active. If I deactivate the widget, the light drags in correctly. If I reactivate the widget, then the light locks into place (as in your video) and I cannot move it by dragging (apart from using the widget).

**Comment by ArgentArts** [comment]
Looks like this light placement error is back with tonight's experimental build.

**Comment by rvanner** [comment]
I agree, dragging in lights without the widget don't orientate to the walls around it

**Comment by LeeBamberTGC** [comment]
Fixed for this evenings EXPERIMENTAL build.
