### ISSUE TITLE
Ryzen 5600G Performance Problems

### ISSUE THREAD

**Issue by joseywales72** [TheGameCreators/GameGuruRepo#2689]
Ryzen 5600G @3.9Ghz, 2 GB of VRAM@3466Mhz. Performance is abysmal, even in low graphics settings. Also, I experience something rather odd. When walking towards an open area with many objects, frame rate drops but also the walking speed of the player drops to a crawl too. When frame rate increases, for example in an enclosed space, walking speed increases too. I guess, the engine does not drop any frames to keep a steady pace but this leads to an uneven playing experience.
An option to change the resolution would be very welcome. The recommended configuration requires 4 GBs of VRAM, I'm aware of that but, 900P or 720P of resolution would make the engine snappier for people with mediocre VGAs
![riverraid](https://user-images.githubusercontent.com/11440359/160457716-b2437f35-a05f-448c-a45c-a36d776f3b1c.jpg)
![snow_highest](https://user-images.githubusercontent.com/11440359/160457723-422a7d03-a453-411b-9935-01bf8abd04dc.jpg)
![snow_low](https://user-images.githubusercontent.com/11440359/160457726-735b2eea-2bdf-448e-8204-fc292b830778.jpg)
.

**Comment by Fubrubruoahaha** [comment]
"When walking towards an open area with many objects, frame rate drops but also the walking speed of the player drops to a crawl too."

I get the same issue on my 1060 GTX (6GB), Ryzen 5 2600x, 32 GB DDR4.

I noticed in snow demo map, the more objects in draw calls, slower it got with character running in slow mo (I was getting 30-34 FPS in open areas, 60 FPS in small closed rooms).

I can play pretty much every Unreal 4 game maxed out at 60 FPS, even in Unreal editor. So this is insane, the performance drop in MAX on same rig that I'm playing Prey (CryEngine) on, maxed out. No instancing issue?

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Assign any performance or optimization issues to Paul from here on in, for the time being.

**Comment by PaulSJ** [comment]
The Ryzen 5600G is using integrated graphics, so it's below the minimum spec, but some changes have been made to object culling that should show some improvement, see if the next version is any better.

You could also try reducing the shadow quality and quantity to see if that helps.
