### ISSUE TITLE
strange animation issue on the assault rifle

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#2690]
https://www.youtube.com/watch?v=VkgwsUCUO6g

**Comment by Granada1** [comment]
If you are hitting the V key it’s the change fire mode animations. Single and auto fire

**Comment by LeeBamberTGC** [comment]
@mav3r1ck198-1 This is by design, you can switch between primary and secondary modes.  Feel free to close this one.

**Comment by mav3r1ck198-1** [comment]
Hi Lee, I appreciate that pressing the V key allows for a secondary use of that weapon, however if you watch the animation, you will see there is an error. The right hand appears as a static mesh, with an additional animated mesh overlaid. The same occurs with the gun itself. 
It makes it appear as if the normals are inverted. 

Sent from the all-new AOL app for Android 
 
  On Wed, 30 Mar 2022 at 12:18, Lee ***@***.***> wrote:   


@mav3r1ck198-1 This is by design, you can switch between primary and secondary modes. Feel free to close this one.

**Comment by LeeBamberTGC** [comment]
Fixed a good while ago this one: )
