### ISSUE TITLE
No Guns Loading in Demos

### ISSUE THREAD

**Issue by mrfenix** [TheGameCreators/GameGuruRepo#2696]
When playing the demo games, the player does not have any weapons displayed. The player can select a gun or fists, when firing the sound is played but no FPS models are displayed and AI takes no damage. This is from the intro screen when I click Start Game and then it loads the main menu and then I click New Game

**Comment by Tum1370** [comment]
I opened this ticket about this problem 26 days ago.
I have uninstalled / reinstalled several times now.
I have removed the download version and then installed the Steam version, yet still i have the same problem.
Here is the original post about this problem and more information about it.

https://github.com/TheGameCreators/GameGuruRepo/issues/2405

**Comment by ZakJudges** [comment]
fixed - see #2405
