### ISSUE TITLE
MAX - Performance on Build -> 2022.04.29

### ISSUE THREAD

**Issue by harkinhails** [TheGameCreators/GameGuruRepo#2697]
Just got the update on Steam and it says performance improvements, but I see no difference at all between this build and last.

**SYSTEM**: Ryzen 6 2600X, 32 GB DDR4, 1060GTX (6GB), 7200RPM NAS, Windows 10 LTSC (1809), nVidia Driver 511.79

**Snowy Stroll Level**: [01](https://i.imgur.com/WAKCbQG.png) | [02](https://i.imgur.com/3sr4C9j.png) | [03](https://i.imgur.com/lJl3SOM.png)

**Island Map**: [01](https://i.imgur.com/61ztlBm.png) | [02](https://i.imgur.com/l8jXx2r.png) | [03](https://i.imgur.com/yOKfqdB.png) | [04](https://i.imgur.com/OEzDJUF.png) (Reduced Camera Far Plane to 1 to get 60 FPS, but that's unplayable and ugly, visually.)

**Few more things**:
1. Increasing FOV (I set it to about 80 normally) to even 120 didn't result in any FPS drop. 
2. Open areas still kill frame rate, almost as if objects don't have any LOD.
3. I believe the new build gave me like 1 more FPS.

Still the system I can run Unreal 4 and Crysis engine pretty much maxed out on, so it is definitely not an issue with hardware. Game load times are not affected much by my NAS (switched from SSD recently) so doubt it asset streaming issue.

**Comment by ArgentArts** [comment]
I don't believe that MAX has auto-LOD in yet. Other culling features are planned, but not yet implemented. That's part of what's going on now, from what I understand. 

One of the things that really slows things down is shadows from the sun. You can go into your TABTAB menu and hit tab a third time to access the Visuals. There you can adjust Shadows:

![shadows](https://user-images.githubusercontent.com/36735507/160692053-2d4e693c-850a-4ac5-9e32-615c6c1d069b.png)

If you don't see that option there, then you may need to expose it by going to Edit>Settings and going to the Advanced tab:

![shadows2](https://user-images.githubusercontent.com/36735507/160692160-1eeb6e9c-7036-4685-85d9-0caff32d2978.png)

Turning down shadows for the sun can help boost FPS a little more.

MAX is running on purely real-time lighting. No baking of lighting at all. Unreal, Crysis ... they all do some lightmapping. As a result, MAX is very intensive on the GPU. Your GPU is a 1060 with only 6GB vram. It's a bit older and will struggle a bit with MAX in its current state. It should do better once they get more culling options and other optimizations in. But it's not there ... yet.

**Comment by harkinhails** [comment]
I seriously doubt it that shadows will cause such performance drop, pretty sure I remember using Unreal editor with lightmapping off and only realtime lighting (UDK too).

In-fact, on the Island map:

[01](https://i.imgur.com/L9Pjoah.png) (Default Map shadows/quality settings.

[02](https://i.imgur.com/MEEQCQg.png) (Turning all shadows off, lights quantity to 0, gave me 1 less FPS)

[03](https://i.imgur.com/sJBrQF2.png) (I maxed out shadow res and quantity, and gained 2 FPS, 1 more than default)


I should mention, I know 1060 GTX is ancient, but it's the [most used card on Steam](https://store.steampowered.com/hwsurvey/directx/) (and not going down anytime soon). If MAX doesn't perform well on this card, expect a LOT of angry people reviewing your games on Steam. There's a reason I haven't bothered buying a new GPU since like 2019 when I bought it, I can still run majority of AAA games pretty much maxed out on 1080p, despite me lusting over RTX stuff. :P

**Comment by harkinhails** [comment]
I thought you could create LOD's manually for objects. [Documentation ](https://gameguru-max.document360.io/docs/trees)talks of trees with LOD.

I don't know why a demo game is shipped without any performance optimization, unless manual LOD isn't a possibility with custom models? Still curious about instancing, is it planned feature or already in MAX? (I assumed Wicked Engine had such performance optimizations tbh)

**Comment by ArgentArts** [comment]
There are LODs for MAX's trees for their bioms. There aren't LODs for anything else (any of the assets you bring in via the Object Library). So, anything that's not a "tree" does not currently have any LODs. As stated previously, auto-LODs are planned, but not implemented. So are other culling and optimization features.

MAX is Early Access software. While some optimizations are there, not all are currently in place, according to the developers. More are planned and we should start seeing these soon-ish. For now, just keep reporting your issues here, like you have, and they will take note of it.

As stated previously, your major slow-downs, as far as MAX is concerned with its current lack of optimization and culling features, is your video card. I have a 1080 ti on my system and I get 55-60+ fps on these same demos.

One thing to consider, too, is these demos were created by users, like you and I. I've not gone through them in detail in edit mode yet, but I've seen a few things that could speed them up. For example, in one of the demos, small things that the player could never ever get to had collision meshes. These are potentially heavy on the engine, especially when there's no need for them. I know that there were many trees in the island demo that were using hull decomposition for collision detection in the past and that was killing my frame rate. When I swapped that out for MAX's tree collision, I got a lot of frames back. I've not checked to see if they've changed any of this or not.

**Comment by PaulSJ** [comment]
@harkinhails Please can you take a screenshot of both the upper and lower halves of the profiler in any problem areas

**Comment by harkinhails** [comment]
Sure:


**ISLAND**

[A](https://i.imgur.com/zxAufmi.png) (UP)
[A](https://i.imgur.com/AXKAkdb.png) (DOWN)



**SNOW STROLL**

[A](https://i.imgur.com/pQygoF7.png) (UP)
[A](https://i.imgur.com/0YIvNJn.png) (DOWN)

[B](https://i.imgur.com/eq2gbg6.png) (UP)
[B](https://i.imgur.com/Ghkb2lv.png) (DOWN)



**ZOMBIE CELLAR** (This is all 60 FPS, but just in-case it helps)

[A](https://i.imgur.com/VjQWGw0.png) (UP)
[A](https://i.imgur.com/UU4ympO.png) (DOWN)



Also, all shots are taken with FOV set to 80, all shadow quality maxed out (I lose like 3-4 FPS max on maxing shadow quality and quantity in most areas).

**Comment by PaulSJ** [comment]
Thanks, I'll investigate this issue

**Comment by ArgentArts** [comment]
Someone really needs to go through the demos, too. I was taking a look at Jungle Fever, for example. A lot of the giant rocks that surround the area are using Convex Hull as a collision type ... even those boundary rocks that the player will never come into contact with. Convex Hull hits any engine heavily. There are objects, out of reach to the player, that have collision meshes. There are tons of meshes in the level that could easily get away with box collision, but are using polygonal collision instead. 

So, even if the engine still needs optimization and better object culling, the demo levels could stand a going-through to be better optimized as well.

In the Island Showdown - there are a lot of trees that are using Hull Decomp for their collision method. Again, this is a heavy-hitter as far as the engine is concerned. Precious frames are being consumed calculating collision for these trees. Every single one of those large rock formations is using Hull Decomp, too. Even rocks that are out in the water use this. A simpler version of collision detection (and, in some situations, having no collision at all) would help free up some cycles and could possibly increase frame rates. I know I was able to eke out extra frames while deep in the jungle of Island Showdown by replacing Hull Decomp on the trees that had it.

**Comment by ArgentArts** [comment]
For example, I took the entrance to the Snowy Stroll and went through everything. All the light fixtures had some form of collision detection. I made them each have "no collision". I took anything out of reach of the player and assigned it "no collision". The benches had convex hull and I gave them box collision (since no one can get under them, etc.). I also gave the pipes box collision instead of convex hull, etc.

Originally the entrance area to this level was running at about 55+ fps for me. Now? It runs from 80-100fps just by making these collision changes. 

There are are gates, high up in the ceiling that fence off lighting where the player could not hope to get to them ... they all had collision of one type or another. Since the player cannot ever touch them, there's no need for collision. Setting them to "no collision" helps to speed things up.

**Comment by harkinhails** [comment]
> Some changes have been made with object culling that should improve this. It's difficult to know how much, but see if the next version is any better.

Looking forward to testing it when it's on Steam. I'll post updates here.



> Someone really needs to go through the demos, too. 

Haha, that's what I said before, "I don't know why a demo game was shipped without any performance optimization."

It gives a really bad impression when demos are giving such performance hits. When next update is released, I wanna try editing some of these demos myself to see how performance can be improved further. Should be interesting (but really, we need LOD system really badly in MAX).

**Comment by ArgentArts** [comment]
Sure. But, remember, these are all user created demos ... except the Switch Demo. So ...

But, you're right. They ship with MAX and will reflect on the engine.

**Comment by harkinhails** [comment]
BUILD 2022.03.31

I believe in gained like 1 FPS in problem areas. It helped make the combat and movement feel slightly less laggy, but it's still awful to play any demo map with large levels.

ISLAND

[A](https://i.imgur.com/pzGVex4.png) (UP)
[A](https://i.imgur.com/RDdmKI6.png) (DOWN)

SNOW STROLL

[A](https://i.imgur.com/2M2XjAR.png) (UP)
[A](https://i.imgur.com/YmgxfrL.png) (DOWN)

[B](https://i.imgur.com/XZq9PEA.png) (UP)
[B](https://i.imgur.com/sO9urIM.png) (DOWN)

**Comment by harkinhails** [comment]
It has been a year, so I formatted and re-installed Windows 10 (Enterprise LTSC 21H2). Performance is exactly the same, no change in FPS.

Lots of objects being rendered in open areas kills the FPS completely. It won't change unless LOD system is in place, or unless every GG Max game is only indoors, close quarters. You'll need a higher end GPU than 1060 to render everything at playable frames.

Oh well, I'm going to try to create a custom map for performance test and see what happens with future updates, if FPS increases (cause of custom objects with no LOD).

**Comment by Necrym59** [comment]
LOD wont be an issue when they get the texture streaming happening with objects, textures is always an issue, moreso than geometry.

**Comment by harkinhails** [comment]
So I would say, after two patches I've gained about 6 stable FPS in MAX. In most open areas I get 36 FPS now and it fluctuates when coming to smaller areas from 45-60 FPS. 

In snow stroll map I was falling off the first ladder a lot before, which is not the case as the FPS is going up (I've said it before, it's unplayable at 30 FPS). I was able to run around and shoot some enemies, but the action lagged constantly as the camera moved around tracking enemies, getting jitters as FPS spiked up and down, making the gameplay unplayable. I lasted 2-3 mins before I shut the demos off, since I didn't want a headache.


**FEW OBSERVATIONS:**

- Turning sun shadow below 2048 is just unacceptable, it looks WAY too blocky and ugly in this day and age and I don't think any demo map should by shipped without setting it to 2048. You can say lighting indoors is an exception but I'm not sure. 1024 should be minimum for all shadow settings, but it looks ugly still. 2048 should be default and maps should be optimized around 2048. I think the big problem is that developers using Max are testing performance on these low settings. Most gamers crank these settings up, they don't want to play with ugly shadows especially.

- Similarly, on 1080p monitor any FOV below 80-90 is unplayable headache. All maps should set FOV to 80 by default. Low FOV might give some FPS to players but it's also a game no one wants to sit through and is not realistic setting most gamers will pick (complains of headaches/nausea will fill game reviews).


**2022.04.08**

ISLAND: [01](https://i.imgur.com/Wf9je4V.png) | [02](https://i.imgur.com/SgnGoDw.png)

SNOW: [01](https://i.imgur.com/m4lPk0E.png) | [02](https://i.imgur.com/jcZA9Bx.png) | [03](https://i.imgur.com/J08YZeM.png) | [04](https://i.imgur.com/vWxDhFI.png)

**Comment by ArgentArts** [comment]
Many of us have wide and ultrawide monitors. I would get a headache playing these at 80+ FOV. Thank goodness they at least provide an FOV slider in the Game Adjustments section so we can change this, if we need/want to. ;) I keep mine between 45-60, depending on the game. So, the default is going to depend on where people play it.

**Comment by harkinhails** [comment]
> Many of us have wide and ultrawide monitors. I would get a headache playing these at 80+ FOV. Thank goodness they at least provide an FOV slider in the Game Adjustments section so we can change this, if we need/want to. ;) I keep mine between 45-60, depending on the game. So, the default is going to depend on where people play it.

I think you're missing the point.

[67.24% of Steam users](https://store.steampowered.com/hwsurvey/) have 1080p monitors.

Are you planning to ship your game with default FOV less than 80-90, especially when in-game FOV slider doesn't tell you what FOV you are setting or when most people don't even see settings when loading game, assuming there are no game settings in GG games? (which I have seen in every GG game played on YouTube)

To fix this issue every GG standalone will actually have to start with game options on main menu, not in-game.

**Comment by harkinhails** [comment]
I see the new update is out. The only difference for me testing-wise, is that I am now on a 1440p (2560 x 1440) monitor, the new rising star of Steam after 1080p. 

Time to test.

**Comment by harkinhails** [comment]
Specs are same, other than res is now 1440p (2560 x 1440) at 10 bit.

So the new update, is surprisingly "smoother" for me. I was actually able to run around shooting enemies without seeing any "stutter" that was in previous versions. I do realize my display card is from 2016, so I'm not expecting miracles on this, esp. on the new res (6 GB ram helps).

Looking forward to future improvements. At-least I can use Max now without any headaches, so huzzah..

Shots with stats. I enabled SSAO btw. Enabling SSR took away 4-5 FPS for me, but not sure these demo maps are optimized at all so I can't complain:

[01](https://i.imgur.com/OZRfMkI.png)
[02](https://i.imgur.com/lnpz70c.png)
[03](https://i.imgur.com/nlrYAM1.jpg)
[04](https://i.imgur.com/IXH5xWc.jpg) 
[04](https://i.imgur.com/vw9RdDi.jpg) With SSAO Off
[05](https://i.imgur.com/eStdEv2.png)

**Comment by ArgentArts** [comment]
@harkinhails A note on the current state of SSAO - It currently only affects models manually placed and not the objects placed by MAX's Terrain Generator (terrain generator trees, terrain, grass). So, if you run a demo like Island Showdown, you'll see SSAO affecting the palm trees because these were placed by the person who made the game (as well as some of the larger trees in the forest). But most of the trees will remain unaffected. So, SSAO is only going to be largely visually affective in demos like Canyon Offensive, which uses a lot of user-placed objects. Just an FYI.

**Comment by harkinhails** [comment]
Alright, with latest build (2022.04.29), I'm noticing more improvement in FPS and pretty much no stuttering or hiccups when turning camera around. I can actually play around now and shoot without stutter giving me a headache.

I STILL feel like, at the current visual quality level, performance should be in 60s on my rig, but there are improvements with every build so I'm hoping it reaches higher number in the future.

Also, it's painful to play Max games without any AA. Like SSAO, AA needs to be turned on by default. Since MSAA takes away 4-5 FPS for me (even in this build) and FXAA takes away 1 FPS, I would turn on FXAA by default for all builds. A sharpen filter will help with FXAA Vaseline look.

Shots with stats:

**Island Showdown**: [01](https://i.imgur.com/Xk7kTYW.png) | [02](https://i.imgur.com/QW86Vs0.png) | [03](https://i.imgur.com/Nz6J1GM.jpg) | [04](https://i.imgur.com/rkJLzdS.jpg)

**Snowy Mountain Stroll**: [01](https://i.imgur.com/3wjNI6p.png) | [02](https://i.imgur.com/GemW8Kx.png) | [03](https://i.imgur.com/hfADurx.jpg)

**River Raiders**: [01](https://i.imgur.com/Ls5K7wp.png) | [02](https://i.imgur.com/nOlDYxR.jpg) | [03](https://i.imgur.com/HLSYXxY.png) | [04](https://i.imgur.com/a2E53aW.jpg)

**Bounty**: [01](https://i.imgur.com/ttzK8rG.png) | [02](https://i.imgur.com/SFMuNNM.png)
