### ISSUE TITLE
GameGuru MAX - Particle panel doesn't display particle thumbs

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2698]
The particle panel never shows me all the particles as thumbnails. As a result, I can never know which particle is which, including the ones I create and import for myself:

![particles](https://user-images.githubusercontent.com/36735507/160689888-ebc697a7-27f9-419d-86a8-f7ae920f68cc.png)

Adding at least the particle names below each thumbnail would help. But having the proper images show up here would be a great help.

**Comment by Necrym59** [comment]
How come you have so many

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Thanks for reporting this issue, if you click "Add new particle" it will start to generate the missing particle thumbs, just keep this screen open until all thumbs has been generated, and it will use them the next time. display of names added from another issue or hover will display the name :)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft Thing is, all the particles in the Add New Particle are rendered completely. But I'm getting this:

![part1](https://user-images.githubusercontent.com/36735507/166411385-dac70367-f538-498a-bf77-79d7110ac8b1.png)

So, I'm thinking that I have these leftover thumbnails from somewhere that I need cleared out. Maybe that's why they aren't "rendering" but stay blank (only say "Particle" on them)? I have no idea where to find them to attempt to get rid of them. 

MAX really needs a way to clear away stuff like this (if this is actually the case).

**Comment by MonkeyFrogStudio** [comment]
Ugh. I just cleared them out with the Delete Particle button. Not sure why I never saw that before. I feel dumb. ;)

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Great you found it, feel free to close this one, your "names" is in another issue :)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft "your "names" is in another issue :)" Not sure what that means ...
