### ISSUE TITLE
UI - Moving GGM across various aspect ratios doesn't display UI properly

### ISSUE THREAD

**Issue by Benjib0y** [TheGameCreators/GameGuruRepo#2701]
Just installed and run GGMax for the first time. started a new project, went into the Terrain Generator to create a new level. The 'Generate Terrain and Open the Level Editor' button is missing, and there's no way back to the storyboard editor.
Ahha!
I have just figured out that this happens when I move the GG window to the 1080p TV screen I have attached as screen 2 to the HDMI port, rather than leaving it on my old 1280x1024 4:3 monitor. In fact if I open GG, the button's there and when I move the window across, it disappears, and reappears if I move the window back.
I have tried setting/unsetting the dpi awareness button and that has no effect.

**Comment by plemsoft** [comment]
@Benjib0y Is this still a issue for you in the latest version ? , if so could you let me know if it helps if you minimize the window and then restoring the window after you dragged it to another monitor ?

**Comment by Benjib0y** [comment]
Sorry, not been on for a while. I'll check nd let you know.

**Comment by Benjib0y** [comment]
I just downloaded the latest update and tried to create  new level. Same as before. By default the GGM window opens on screen 1, (1280x1024). When I go into the terrain editor and move the window to screen 2, (1080P) the two buttons at bottom right disappear. When I move the window bck to screen1 they reappear.

**Comment by plemsoft** [comment]
@Benjib0y What happens if you minimize the window while on screen 2 , and then maximize it again does that fix anything ?

**Comment by Benjib0y** [comment]
Sorry Preben, it doesn’t.

Ben

 渜
