### ISSUE TITLE
Save standalone game

### ISSUE THREAD

**Issue by HannahIsCrying** [TheGameCreators/GameGuruRepo#2704]
Every time I try to save my game as a save standalone it gets to about 5-25% before a runtime error pops up. 

Runtime error! 
Program: ...x86/Steam/steamapps/common/GameGuru/Guru-MapEditor.exe
This application has requested the runtime to terminate it in an unusual way. Please contact the applications support team for more information. 

This error has happened to me A LOT of times since I first started using gameguru. Sometimes if I keep exiting out the game, restarting game and retrying again and again it eventually works. Right now, that isn't helping. 

![image](https://user-images.githubusercontent.com/101230547/160963290-548761f2-4ff2-4622-a9e7-5b90e9a2d583.png)

**Comment by thecyrus** [comment]
@dllllllllllb It's not Max, it's Classic this time.

**Comment by LeeBamberTGC** [comment]
@HannahIsCrying Sounds like an intermittent issue. Can you do an experiment and from a blank level, save standalone under five different game names, and see how many crash out while doing the standalone save process. This will confirm the basics are working with your system. We can go from there :)
