### ISSUE TITLE
Enemy shout out sounds don't carry over to standalone

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#2713]
Enemy shout out sounds Not carrying over to standalone 
Latest experimental build

**Comment by ZakJudges** [comment]
Hi @Granada1, thanks for reporting this issue. A fix has been added which you should see in next weeks build :)

**Comment by ZakJudges** [comment]
Hi @Granada1, there will be a new experimental build up later today. Would you be able to confirm if this issue is fixed for you when you next update? :)

**Comment by Granada1** [comment]
Will do
