### ISSUE TITLE
GameGuru MAX - Bug - Emissive behaviour only appears when the object is selected

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2714]
Emissive amount appears to change if object with emissive texture is selected or not:

https://user-images.githubusercontent.com/36735507/161101199-0f5cade8-8411-4bfe-840d-afcbbf19a2f8.mp4

This makes it difficult to determine what the actual emissive amount will look like before running the game.

In my other level, which has point lights in it (unlike the above test level), the exact same emissive texture on the exact same model does not glow at all no matter how much I turn up the emissive amount. It only turns white:

https://user-images.githubusercontent.com/36735507/161101917-1b645d22-ebb8-410b-b189-29fc855e0adb.mp4

**Comment by PaulSJ** [comment]
@ArgentArts Is it only this object that has an issue? I tried adding an emissive texture to one of the default barrels but it's emissiveness wasn't affected by selection/deselction

**Comment by ArgentArts** [comment]
Here's the barrel, if you want to use it in your tests:

[SFBarrel.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8544380/SFBarrel.zip)

Forgive the 2k textures. I've not optimized this model, yet.

**Comment by PaulSJ** [comment]
Weirdly I still can't replicate this
https://user-images.githubusercontent.com/8309736/165310984-215707d0-c979-43fe-9d1a-e66681456285.mp4
Do you see this issue in a new empty level?

**Comment by ArgentArts** [comment]
@PaulSJ Here's two videos in two completely different levels (the last one's a new, empty level in the latest experimental build):

https://user-images.githubusercontent.com/36735507/165335155-ad5474a6-305a-4615-a3d0-79162ce14657.mp4

https://user-images.githubusercontent.com/36735507/165335166-1f487b62-cd01-4b1c-84e1-119fd9d49aea.mp4

**Comment by MonkeyFrogStudio** [comment]
@PaulSJ What more information can I provide? I've given videos showing it still happens. And it's still happening for me even in today's experimental build.

**Comment by MonkeyFrogStudio** [comment]
I don't think this is happening any longer, so I am closing this.
