### ISSUE TITLE
BUG: Elapsed Time Handeled Incorrectly

### ISSUE THREAD

**Issue by StabInTheDarkSoftware** [TheGameCreators/GameGuruRepo#272]
BUG: Elapsed time should not be multiplied or hard coded.

> void game_timeelapsed ( void )
> 
> {
> 
> 	// Calculate time between cycles
> 
> 	float fThisTimeCount = timeGetSecond();
> 
> 	t.ElapsedTime_f = fThisTimeCount - t.LastTimeStamp_f;
> 
> 	g.timeelapsed_f = t.ElapsedTime_f * 20.0;
> 
> 	t.LastTimeStamp_f = fThisTimeCount;
> 
> 
> 
> 	//  Cap to around 25fps so that leaps in movement/speed not to severe!
> 
> 	if (  g.timeelapsed_f>0.75f  )  g.timeelapsed_f = 0.75f;
> 
> 	if (  g.timeelapsed_f<0.00833f  )  g.timeelapsed_f = 0.00833f;
> 
> }

**Comment by LeeBamberTGC** [comment]
It's a generic multiplier currently required by the engine (used to be based on another system, not seconds stored as floats) so removing the multiplayer would slow lots of elements such as motion and animation down by a factor of 20. As you say, the engine has a lot of legacy stuff in there, this being one of them. If you need the true per-second timer, you can always use 'timeGetSecond' directly.

Before I classify this as 'not a bug', what specific issue is the above code causing in the game engine?

**Comment by StabInTheDarkSoftware** [comment]
Physics needs to use an accurate elapsed time for frame rate independence of the physics.

> http://www.bulletphysics.org/mediawiki-1.5.8/index.php/Stepping_The_World

**Comment by LeeBamberTGC** [comment]
I currently use timeGetSecond for the physics elapsed time:

	//  Update physics system
	t.tphysicsadvance_f = timeGetSecond() - t.machineindependentphysicsupdate;
	if (  t.tphysicsadvance_f >= (1.0/120.0) ) 
	{
		//  only process physics once we reach the minimum substep constant
		if ( t.tphysicsadvance_f>0.05f ) t.tphysicsadvance_f = 0.05f;
		t.machineindependentphysicsupdate = timeGetSecond();
		ODEUpdate ( t.tphysicsadvance_f );
	}

**Comment by StabInTheDarkSoftware** [comment]
The snippet you posted above is still manipulating the elapsed time.
One elapsed time should be used for all of the engine to keep everything in sync. 
ODEUpdate() is incorrect and should simply be,

> 	float ms = g_GGPhysicsWorld->GetDeltaTimeMilliseconds();
> 	//stepSimulation second parameter keeps physics constant regardless of framerate.
> 	g_GGPhysicsWorld->m_dynamicsWorld->stepSimulation(ms / 1000.0f, 20);

**Comment by ViperSmoke** [comment]
Is that problem connect with the feet-step sound bug that I notice time ago?
And it still creates problems for me. https://github.com/TheGameCreators/GameGuruRepo/issues/186

It seems like a fps' problem, 'cause on my computer I have 144 FPS and I set the optimal setting for 144 fps, the step sound is correct but if someone else play at 60 fps on another computer, the step sound is wrong and more speed.

(sorry I don't  speak english very well)

**Comment by StabInTheDarkSoftware** [comment]
Well, I tried to help by explaining that this is a major bug.
