### ISSUE TITLE
GameGuru MAX - Bug - Click+Drag from Panel Sometimes Drags Viewport Objects

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2727]
I cannot get this to happen all the time, but when it does, it's a PITA. Sometimes, when you CLICK+DRAG from the Level Objects panel, Game Elements panel, or Current Objects/Groups panel, you end up also selecting and moving an object already placed in your level that's partially behind the UI (i.e. you can sometimes select objects through the UI). Therefore, as you drag from these panels, you end up also moving this other object, which is undesirable, to say the least.

Nothing in the view port should be selectable through the UI.

**Comment by plemsoft** [comment]
@ArgentArts Thanks for reporting this issue, i was not able to reproduce it, could you make a short video that displays this ? , thanks for your help :)

**Comment by ArgentArts** [comment]
@plemsoft I will try. I have tried. It happens, but I've not been able to catch it on video ... yet. But I'll get it to happen. ;)

**Comment by ArgentArts** [comment]
Here you go:

https://user-images.githubusercontent.com/36735507/162247302-c5688a9b-cb29-4572-af43-ed541b526873.mp4

Captured with the latest experimental build.

**Comment by plemsoft** [comment]
@ArgentArts Great i was able to reproduce it and have fixed it for the next update , thanks for your help :)

**Comment by ArgentArts** [comment]
Awesome!

**Comment by ArgentArts** [comment]
@plemsoft As of the 2022.04.013 version, this has resurfaced. It's like this version of MAX is a regression or like someone snuck in an older version of the software! Even the F1 to toggle on/off the widget no longer works!

**Comment by LeeBamberTGC** [comment]
@ArgentArts The Experimental build was just to test a work in progress new feature, check again this evening for a new update to Experimental which should restore much from early April :)

**Comment by ArgentArts** [comment]
@LeeBamberTGC Thanks! Will do! :)

**Comment by ArgentArts** [comment]
Looks to be fixed!
