### ISSUE TITLE
GameGuru Max Bug - Alpha clipping issue found in "Snowy Mountain Stroll" demo

### ISSUE THREAD

**Issue by SquireOfGothos** [TheGameCreators/GameGuruRepo#2729]
I posted this issue in the forum and it's been confirmed as a bug.  In the Snowy Mountain Stroll demo the fencing panels only have wire on one side.  This can be seen in the building that has two rooms and a ramp leading up to each. Here are a couple of screen shots:

![Fence](https://user-images.githubusercontent.com/15776865/161296935-b2f034d6-a858-4966-9e78-fba35352fae5.jpg)
![No fence](https://user-images.githubusercontent.com/15776865/161296942-a9189ffc-0cef-4e71-b642-80d38c24f89a.jpg)
.

**Comment by ArgentArts** [comment]
If you set the material to double-sided, the fence displays properly, too.

**Comment by dllllllllllb** [comment]
@rvanner as ArgentArts said, fences just need to be ticked to be double-sided. I've done this to all fences in Snowy Mountain Stroll along with the puddle reflection changes and sent the updated files to Paul.

**Comment by plemsoft** [comment]
@dllllllllllb FYI: Added a fix that will make it work from the .fpe so you don't have to set the double-sided checkbox, when you add a new object to your level. dup: https://github.com/TheGameCreators/GameGuruRepo/issues/2748
