### ISSUE TITLE
Texture enemy characters: After testing a few times or Die - Transparent mode is found

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#273]
Texture enemy characters: After testing a few times or Die - Transparent mode is found.
Previously reported: Issue (Zombie character texture #206)
This is a bad problem.
Please fix it.

![snapshot8](https://user-images.githubusercontent.com/36647058/41982542-f7b8024e-7a40-11e8-9c47-d25d285e92de.jpg)
![snapshot10](https://user-images.githubusercontent.com/36647058/41982543-f7e27e98-7a40-11e8-8adc-5429d80c7a73.jpg)
![snapshot13](https://user-images.githubusercontent.com/36647058/41982545-f80b03ae-7a40-11e8-8efd-8ffa58192e4e.jpg)
![snapshot15](https://user-images.githubusercontent.com/36647058/41982546-f8350758-7a40-11e8-82c6-87e05399f45e.jpg)

**Comment by Peri32** [comment]
I its also happen to me, with random characters even with a twin character with different weapon 

![image](https://user-images.githubusercontent.com/43548667/45966414-bce83600-c033-11e8-8401-5bd58d62fd84.png)

**Comment by plemsoft** [comment]
@Shahin3d Thanks for reporting this,

When do this start , when you die , or after you use Spawn of enemy characters ?

**Comment by Peri32** [comment]
Sometimes when I test the level, back to map editor and test again, then I
can see the enemy transparency, its some times one or two types of enemies
models its random.

But if I move the model with drag mode ir back to normal.

I will send you video next.

Thanks

בתאריך יום ו׳, 14 ביוני 2019, 14:59, מאת Preben Eriksen ‏<
notifications@github.com>:

**Comment by plemsoft** [comment]
@Shahin3d @Peri32 Could you test this in the Beta version 2019-06-15B and let me know if it works , thanks :)

**Comment by Peri32** [comment]
Yes but can I roll it back without damage?

בתאריך יום ב׳, 17 ביוני 2019, 15:51, מאת Preben Eriksen ‏<
notifications@github.com>:

**Comment by plemsoft** [comment]
@Peri32 Pirate-Myke already confirmed that it was working , so if your not comfortable with running/installing the beta, there is no need :)

**Comment by Peri32** [comment]
Great news I happy you solve it with the next virsion thanks :)

בתאריך יום ג׳, 18 ביוני 2019, 13:27, מאת Preben Eriksen ‏<
notifications@github.com>:

**Comment by Shahin3d** [comment]
Thank you
I do not have a problem.
