### ISSUE TITLE
GameGuru MAX - Request - Ladder Behaviour to Hide Arms/Weapons 

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2730]
I think it would look a lot better if the player hands/weapons were not visible when using the ladder. Therefore, if possible, I'd like to see if the Ladder Behaviour could be modified so that when the player is on the ladder the hands/weapons are hidden?

Thanks. :)

**Comment by Necrym59** [comment]
Those animations would have to be done by the TCG team not the ladder behaviour i think, theirs no way to change except to hide wepon holding mode, which i could do. They really need to have a climbing arm animation to switch in and out.

**Comment by ArgentArts** [comment]
I didn't ask for an animation. I asked to hide the arms/weapon. This is already possible ... just like when you run the game with no melee and no weapon. The arms are hidden. ;) That's all I asked for. ;)

**Comment by Necrym59** [comment]
OK will do, ill update the ladder im doing a couple of improvements anyway so ill slot that in.

**Comment by ArgentArts** [comment]
Wow! Is this your Behaviour? I wasn't trying to give you work to do. ;)

**Comment by ArgentArts** [comment]
And I definitely don't need it now or for some time to come. I was just messing with the Snowy Stroll demo and noticed how awful it looked to see that pistol in my hand as I climbed the ladder. ;)

**Comment by Necrym59** [comment]
Too late 
[ladder_v19.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8400339/ladder_v19.zip)

**Comment by ArgentArts** [comment]
You, sir, rock!

**Comment by ArgentArts** [comment]
@Necrym59 Is this supposed to hide the arms/weapons? I tested it in Snowy Stroll on the ladder and it was the same.

**Comment by Necrym59** [comment]
It works - did you select the right script v19 and did you select hide from the behaviour
![v19](https://user-images.githubusercontent.com/95015657/161336882-97e27e88-ad6c-482d-9863-c7c68625ff4f.jpg)

**Comment by ArgentArts** [comment]
Yep. My bad. It does work. I didn't see the Climb Style drop-down.

But try this ... set Climb Style to Hide Weapon. Run the game. Climb up the ladder and the weapon hides. Nice! Get off the ladder at the top. Weapon reappears. Nice! Slowly back up so that you get back on the ladder again and start back down the ladder ... the weapon does not hide going down the ladder. ;)

**Comment by Necrym59** [comment]
from entry at the top, ok ill look into it.

**Comment by ArgentArts** [comment]
I know, I'm a pain. ;)

**Comment by Necrym59** [comment]
> I know, I'm a pain. ;)

lol its ok do you think i should make hide weapon as the default?

**Comment by ArgentArts** [comment]
I would. But that's how I think. Personally, I think it looks silly to climb up the ladder with the gun out. Imagine how that would look if you were armed with one of the rifles!

**Comment by Necrym59** [comment]
lol ok

**Comment by Necrym59** [comment]
There works ok now up and down
[ladder_v20.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8400872/ladder_v20.zip)
and default is hide weapon

**Comment by Necrym59** [comment]
no wait defasult isnt working

**Comment by ArgentArts** [comment]
No worries. I'm off to prepare dinner ... be back in a bit. :)

**Comment by Necrym59** [comment]
Ok here its all working now, default is hide weapon, now works when entry from top of ladders
[ladder_v20.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8400908/ladder_v20.zip)

**Comment by Necrym59** [comment]
Off to get breakfast :) back later

**Comment by Necrym59** [comment]
Request done and completed see
https://github.com/TheGameCreators/GameGuruRepo/issues/1872
