### ISSUE TITLE
GameGuru MAX - Bug - EBE Flashes White When Other Object Selected

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2731]
See video:

https://user-images.githubusercontent.com/36735507/161327431-1b944192-1a88-47c1-b9b4-4a68cb3dcd05.mp4

**Comment by Hughjanus2022** [comment]
The same

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by MonkeyFrogStudio** [comment]
Looks to be fixed! Thanks!!!
