### ISSUE TITLE
Request - Exposed material properties in LUA

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2736]
Can we please get any or all of these settings exposed in lua, especially the alpha and transparency and emmisive setings. 
eg SetEmissiveTexture(e, value) if possible.
![lua_settings](https://user-images.githubusercontent.com/95015657/161371322-f4e0d967-8b7b-4ce3-a074-e22f1d542d92.jpg)

**Comment by MonkeyFrogStudio** [comment]
We definitely need the ability to control these settings via LUA. For example, the ability to change emissive colors or brightness would be great. As an example, we could make an emissive color pulse for emissive lights on a control panel or change a red light on a locked door door panel to green when it has been unlocked, etc. If transparency/alpha clipping is exposed to LUA, then objects could be faded in/out, etc.

**Comment by Necrym59** [comment]
Any or all of the above would be of use but especially Transparancy and emmisive control in lua. 
Transparency control for fading in or out would be an excellent tool. Emmisive as stated above could be used for pulsing and other eeefects.

**Comment by LeeBamberTGC** [comment]
As a thank you to Necrym50 for making well over 40 behaviors (with icons) for the community, I have added 28 new LUA commands to control all material properties of an object:

Entity Material Commands:
SetEntityBaseColor: SetEntityBaseColor(e,r,g,b) -- this command changes the entity object material property
GetEntityBaseColor: r, g, b = GetEntityBaseColor(e) -- this command gets the entity object material property
SetEntityBaseAlpha: SetEntityBaseAlpha(e,value) -- this command changes the entity object material property
GetEntityBaseAlpha: value = GetEntityBaseAlpha(e) -- this command gets the entity object material property
SetEntityAlphaClipping: SetEntityAlphaClipping(e,value) -- this command changes the entity object material property
GetEntityAlphaClipping: value = GetEntityAlphaClipping(e) -- this command gets the entity object material property
SetEntityNormalStrength: SetEntityNormalStrength(e,value) -- this command changes the entity object material property
GetEntityNormalStrength: value = GetEntityNormalStrength(e) -- this command gets the entity object material property
SetEntityRoughnessStrength: SetEntityRoughnessStrength(e,value) -- this command changes the entity object material property
GetEntityRoughnessStrength: value = GetEntityRoughnessStrength(e) -- this command gets the entity object material property
SetEntityMetalnessStrength: SetEntityMetalnessStrength(e,value) -- this command changes the entity object material property
GetEntityMetalnessStrength: value = GetEntityMetalnessStrength(e) -- this command gets the entity object material property
SetEntityEmissiveColor: SetEntityEmissiveColor(e,r,g,b) -- this command changes the entity object material property
GetEntityEmissiveColor: r, g, b = GetEntityEmissiveColor(e) -- this command gets the entity object material property
SetEntityEmissiveStrength: SetEntityEmissiveStrength(e,value) -- this command changes the entity object material property
GetEntityEmissiveStrength: value = GetEntityEmissiveStrength(e) -- this command gets the entity object material property
SetEntityReflectance: SetEntityReflectance(e,value) -- this command changes the entity object material property
GetEntityReflectance: value = GetEntityReflectance(e) -- this command gets the entity object material property
SetEntityRenderBias: SetEntityRenderBias(e,value) -- this command changes the entity object material property
GetEntityRenderBias: value = GetEntityRenderBias(e) -- this command gets the entity object material property
SetEntityTransparency: SetEntityTransparency(e,value) -- this command changes the entity object material property
GetEntityTransparency: value = GetEntityTransparency(e) -- this command gets the entity object material property
SetEntityDoubleSided: SetEntityDoubleSided(e,value) -- this command changes the entity object material property
GetEntityDoubleSided: value = GetEntityDoubleSided(e) -- this command gets the entity object material property
SetEntityPlanarReflection: SetEntityPlanarReflection(e,value) -- this command changes the entity object material property
GetEntityPlanarReflection: value = GetEntityPlanarReflection(e) -- this command gets the entity object material property
SetEntityCastShadows: SetEntityCastShadows(e,value) -- this command changes the entity object material property
GetEntityCastShadows: value = GetEntityCastShadows(e) -- this command gets the entity object material property

I tried the emissive strength command with my camp fire object and it worked first time. I would appreciate if someone could go through the rest to make sure they (a) work and (b) return the correct value with the Get variant. Will save me much time. 
Check it out in the next EXP build up sometime today.

**Comment by earthling45** [comment]
So does this mean we are going to be able to have working traffic lights through the use of emissive control, brake lights and head lights. :)
We might need to work on a car again. :)

**Comment by LeeBamberTGC** [comment]
@earthling45 I am not thinking about vehicles right now, but if you had three models, one for each colored light, you can control their emissive strength no worries :)  The commands are per-object not per-mesh, but down the road (aha) we can look at that.

**Comment by Necrym59** [comment]
Many Thanks Lee

**Comment by Necrym59** [comment]
I have tested all the values and they all seem to work fine, excellent work and thanks again Lee
Now, to see what damage I can wrought with these arsenal of commands, one setp closer to world domination :)
