### ISSUE TITLE
GameGuru Max Bug - 3D Level Editor-Terrain Tools-Palette not loading selection

### ISSUE THREAD

**Issue by AndrewMarais** [TheGameCreators/GameGuruRepo#2737]
When changing the texture(right click) opens a file selection.
Then selecting a TGA file, it does not load the file but randomly changes the selected texture, instead of taking the file/image selected.

![image](https://user-images.githubusercontent.com/28435414/161373040-7f5c5db8-64d0-4e43-a7bb-05d782471b08.png)

**Comment by PaulSJ** [comment]
That is a feature left over from the old terrain and is not currently supported, I've removed the right click menu for a future version. 

If you want to replace terrain textures then you can replace the files in the Files/terraintextures folder, but you will need to match the file formats (color=BC7, normal=BC5, surface=BC1) and all textures must be 2048x2048.
