### ISSUE TITLE
MAX - Crash central

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#2738]
Running the latest EA build on Steam.

MAX will crash randomly and extremely frequently when trying to place down assets or change audio attached to entities. I will also 100% crash when I am trying to open a saved level that I sunk 2 hours into :(

Validated files twice, Steam reported all files successfully validated. Nothing seems consistent about the crash with placing assets/changing audio slots; I can place an asset and instantly crash, then reboot the software and place the exact same asset in roughly the same place with no issue; same with audio and placing the same audio in the same entity slot.

NEVER had these issues with the preorder alpha builds; they ran like a dream more or less. Now the EA version crashes when I so much as think too hard!

**Comment by Kitakazi** [comment]
Hi I'm also experiencing constant crashes. Also using the Steam Version.

I was using the importer a bunch trying to test some animations and all of the sudden when I tried to save my model Max crashed and has been a crash fest ever since. 

If I try to add a single entity by clicking Add (under level objects) I will instantly crash about 95% of the time.  Starting to think it may be 100% of the time now.

**Comment by plemsoft** [comment]
@fearlesswee Could you post your "Guru-MapEditor.log" file here just after you had the crash , Thanks :)

**Comment by plemsoft** [comment]
@Kitakazi Sound like you have a bad object , so each time you click "Add" it will try to generate a thumb and crash, could you e-mail me this bad object (from the last time you used the importer, where it crashed after "save"), i will then be able to see why the bad object generate a crash, thanks for your help :) plemsoft@plemsoft.com

**Comment by fearlesswee** [comment]
@plemsoft Okay, where could I find said file?

**Comment by plemsoft** [comment]
@fearlesswee Could you try to: rename this file "\user\BarbedManFix.fpe" to "\user\BarbedManFixTEST.fpe" , then check if your able to load your level , and if you are , could you e-mail me all the files related to "BarbedManFix" so im able to check why this object crash your level , Thanks for your help :) , plemsoft@plemsoft.com

**Comment by fearlesswee** [comment]
Ayup! That did the fix. I did notice another bug once I did get into my level however, many items that were suspended off the ground, such as a hatchet stuck into the side of a tree, and some props placed ontop of tables, all seemed to "fall" and conform to the terrain below them.

[https://www.mediafire.com/file/b8ey1zrdw3cad6y/barbedmanfix.zip/file](url)

**Comment by fearlesswee** [comment]
Emailed you the files, btw. It's a free model from sketchfab that I'm just using to test gameplay logic for now, so I didn't mind posting it here publicly but you did specify to email you!
