### ISSUE TITLE
Entities models jump high over obstacles

### ISSUE THREAD

**Issue by Daveutopias** [TheGameCreators/GameGuruRepo#274]
Hi, I have discover this new bug, when an entities try to follow me and I try to circumnavigate the obstacle, that entities if the obstacles is not so high it make an high jump over it, it make an "small moon" jump, this bug was saw also on YouTube from some youtubers

**Comment by Daveutopias** [comment]
also shark inside the ocean jump up over the water 
![snapshot35](https://user-images.githubusercontent.com/40697420/42140699-f67e725e-7da2-11e8-9985-edae23353ec5.jpg)
![snapshot37](https://user-images.githubusercontent.com/40697420/42140700-fb6b18da-7da2-11e8-94da-12c88a72a3ff.jpg)
![snapshot39](https://user-images.githubusercontent.com/40697420/42140701-0008399a-7da3-11e8-9821-e531b940b6b2.jpg)

and bad children from lafette make high jump over the moon, some entities do not cross or circumnavigate the obstacles , it make a jump so high

**Comment by LeeBamberTGC** [comment]
Can you reproduce this issue with stock assets and attach an FPM I can load at this end to reproduce, thanks!

**Comment by korodai** [comment]
I noticed "Dog (Rottweiler) animated" by Dagored jumping very high over obstacles.

**Comment by LeeBamberTGC** [comment]
Where is the "Dog (Rottweiler)" asset located, thanks!

**Comment by korodai** [comment]
The dog's not stock. It's from the TGC Store. I was just mentioning that it also jumps.

**Comment by Daveutopias** [comment]
sure! i was able to reproduce it (after severely times i got it!)

[CHARACTER BIG jumps.fpm.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2162956/CHARACTER.BIG.jumps.fpm.zip)
[CHARACTER BIG jumps.dat.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2162957/CHARACTER.BIG.jumps.dat.zip)

just this time it happens when a character was put where only character can pass, if you try to put it beyond the arch you will see that it will try to circumnavigate the obstacle instead of crossing it (I think this is another bug!) so we have two bugs here.
i hope you have understand what i mean.

the i have found others bug, if you put the starter point at the arc, you cannot move, also if you lift or down the green starter point
[cannot move  inside ARC BUG.fpm.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2162987/cannot.move.inside.ARC.BUG.fpm.zip)
[cannot move  inside ARC BUG.dat.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2162988/cannot.move.inside.ARC.BUG.dat.zip)


sorry that are three bugs
![high jump 1](https://user-images.githubusercontent.com/40697420/42274134-db1b6e6e-7f8b-11e8-8033-8d5abc790b2b.png)
![high jump 2 1](https://user-images.githubusercontent.com/40697420/42274138-e083e886-7f8b-11e8-8eca-d0937b74543c.png)
![high jump 2 2](https://user-images.githubusercontent.com/40697420/42274143-e5c840f8-7f8b-11e8-9e8a-ac8f5b11dabf.png)
![high jump 2 3](https://user-images.githubusercontent.com/40697420/42274150-ea6a2cf2-7f8b-11e8-929a-32ed59e4a7b6.png)

**Comment by Daveutopias** [comment]
here we go, here the example where characters do NOT want to walk inside the arc
[circunnavigate instaed of going inside arc.dat.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2163063/circunnavigate.instaed.of.going.inside.arc.dat.zip)
[circunnavigate instaed of going inside arc.fpm.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2163064/circunnavigate.instaed.of.going.inside.arc.fpm.zip)

**Comment by LeeBamberTGC** [comment]
All the ZIP files are password protected. Can you provide the password to unlock them?

**Comment by LeeBamberTGC** [comment]
If they are just FPM files, they will not contain the custom media I can see in the screenshots. Could you send me an FPM that does not use any custom/store media and only uses stock media that comes with GameGuru? That will allow me to reproduce under tightly controlled conditions, and find a fix quickly.

**Comment by Daveutopias** [comment]
i was wondering was stock media and not custom, i will  try again
[try this jump high.dat.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2167326/try.this.jump.high.dat.zip)
[try this jump high.fpm.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2167327/try.this.jump.high.fpm.zip)

**Comment by AmenMoses** [comment]
https://vimeo.com/278543092

**Comment by LeeBamberTGC** [comment]
Just what I needed, thanks. I can reproduce the issues now :)

**Comment by Daveutopias** [comment]
thank's AmenMoses to the direct video, is exactly what done some entities, drunk included, I hope my help will be useful for something.


@LeeBamberTGC no problem.

**Comment by LeeBamberTGC** [comment]
When the next PP build goes out (soon), try the attached FPM which shows working AI obstacle generation and drunken characters that dont fly into the air.
[try.this.jump.high_fixed.fpm.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2168203/try.this.jump.high_fixed.fpm.zip)

**Comment by Daveutopias** [comment]
ok, thank youuu

**Comment by Teabone3** [comment]
I've been noticing this issue with a number of character entities both stock and from the store. They also occur with the zombie characters.

**Comment by LeeBamberTGC** [comment]
I have not noticed it with the stock Zombies (as they use the module_combatmelee AI subsystem). Any way to create a small FPM with the zombie in question much like it was demonstrated with the Drunken character?

**Comment by Daveutopias** [comment]
@teabone3 i was wondering that was fixed anyway, cause i have noticed that already with the dolphin (see the first screenshots, angry bad kids from lafette, then rottweiler and many other entities doing this high jump, i suppose to wait next PP build to see this fixed

**Comment by LeeBamberTGC** [comment]
This level has bad obstacle data, if you view the scene with debug to full you will see its the obstacle bounds that block the AI. Best to create a new level with the latest version and attach the FPM here if you find something wrong. We can work best from there, thanks!

**Comment by plemsoft** [comment]
Just tested in the latest version , and there is no jumping , if anyone else can test this or produce a new fpm that display the error , please let me know , until then i will mark this as fixed.
