### ISSUE TITLE
Interior faces missing from many models in 01/04/2022 build.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2740]
![image](https://user-images.githubusercontent.com/99803873/161380102-27b84bfe-1ed4-44b9-8670-02bdd9b98404.png)

Making the model double sided fixes the issue, so I'm guessing something has changed, preventing the interior being drawn.

**Comment by ZakJudges** [comment]
Hi @davetgc, I believe this was fixed as of the latest experimental build. Could you confirm if that is the case? Thanks :)

**Comment by davetgc** [comment]
Hi Zak, I can't answer that as for some reason, I had to repair files, and
now the latest internal build I now have is dated 31/03/2022. Not sure what
happened to 01/04/2022 and beyond.

**Comment by ZakJudges** [comment]
@davetgc Could you try the latest Steam experimental build? That one has all the latest fixes :)

**Comment by davetgc** [comment]
Hi, yes, fixed in experimental build. Thanks.

**Comment by ZakJudges** [comment]
Hi @davetgc, I wasn't able to reproduce the issue in the latest experimental. Would you be able to verify your files and see if the problem persists? Thanks

**Comment by davetgc** [comment]
Yes, it is working.
