### ISSUE TITLE
MAX - 2022.03.31 - Tiny Installer Installs Everything

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2741]
Installs everything even when boxes are not checked

**Comment by plemsoft** [comment]
@rvanner This is caused by the "demo games" , currently they require all the collection to be installed , i can see that disabling of downloading the "demo games" has been disabled , should we allow deselecting downloading of "demo games" and then also allow deselecting of collections ?.

**Comment by rvanner** [comment]
We didn't want a situation where users downloaded the core and then could not see anything in the HUB. I will make a note for now and we can review the install options and procedures once we have a more stable core engine. This is really a medium issue for now.

**Comment by OldFlak** [comment]
I don't want any of it on my system (won't use it) so the option should be there to not install them - SSD space is too precious to be wasted on stuff you won't use.

No media should be in the core anyway - it should all be in Writable Area. On my system I have a dedicated HDD for Game dev - which is where my writable area is located. It has tons of space - that is where all media should be, not in the core? If it was putting it there it would be ok.

As a side note although it downloaded everything for the demo games, not all media is there - example: Lees switch demo has no models in it at all, just markers and particles, and switches.

**Comment by OldFlak** [comment]
Disregard this if you want - using Steam version on Drive D seams to work just fine so not an issue for me (plenty space on D)
