### ISSUE TITLE
Game Guru Max - Object script issue. No pick up script

### ISSUE THREAD

**Issue by Zorgo33** [TheGameCreators/GameGuruRepo#2745]
I've mentioned this in a broadcast of game guru max, and there was supposed to still be a script for picking up objects physically (like pickupsimple.lua) but with a diffrient name. Looked trough every single one and didn't find a single one that has the logic of carrying an object with physics. 

So i can say, physics pickup script is missing.

**Comment by AmenMoses** [comment]
[pickuppable.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8404302/pickuppable.zip)

You mean this?

**Comment by Zorgo33** [comment]
Yes

**Comment by LeeBamberTGC** [comment]
Confirmed, closing this to allow for the larger issue to solve this one: https://github.com/TheGameCreators/GameGuruRepo/issues/1879
