### ISSUE TITLE
help me, tree shaders make me occlusion

### ISSUE THREAD

**Issue by Daveutopias** [TheGameCreators/GameGuruRepo#275]
i have recently update my game guru to last version of 06.18.2018, i have opened my saved project, then when i try to test in game i was surprised to see a framerate poor (like 3 fps) and all the tree entities was obstacles me by the shaders fault (example if i walk near a tree with a long shader, that shader prevents me to walk)

**Comment by Daveutopias** [comment]
![snapshot2](https://user-images.githubusercontent.com/40697420/42135924-c9bdd2fa-7d52-11e8-99b8-6b0f24f371ff.jpg)
![snapshot3](https://user-images.githubusercontent.com/40697420/42135925-cd4f1280-7d52-11e8-9fbb-958eaabdc403.jpg)
 they are pre - bake shaders that prevent me to move,

**Comment by Daveutopias** [comment]
finally i have found what make me occlusion! i have done a depp research inside the game and it was berry bush tree that have bad collision (before the 18.6.2018 version was ok)
please fix this problem!
![snapshot43](https://user-images.githubusercontent.com/40697420/42140655-940f7686-7da2-11e8-941e-e3d5bfb33b80.jpg)
![snapshot44](https://user-images.githubusercontent.com/40697420/42140659-9bcafeae-7da2-11e8-9335-85573b6f3399.jpg)

anyway buttons from f1 to f4 doesn't work anymore

**Comment by LeeBamberTGC** [comment]
Can you specify the folder for the "berry bush tree" you mentioned, I am assuming its one of the stock assets?  Also the lightmapper now needs you to hold down SHIFT before pressing F2 through F4.

**Comment by Daveutopias** [comment]
nope these asset was from users, but i do not understand, before the last update fro game guru was not giving any problem

**Comment by LeeBamberTGC** [comment]
Every update has the power to change anything, which is why we maintain an issues tracker to detect any functional differences between versions. If I can have the exact model referred to, I can reproduce it here and find a fix for the next update.
