### ISSUE TITLE
GG Max - Bug - Ally AI stops following when i run close to 2 birds

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2750]
I had a Ally AI following me, i have run all over the map with no problems, and the ally follows me.
But when i place a couple of birds down in an area, The Ally AI stopped following me when i got close to the birds.
I was not close enough to the birds for them to fly away.

It was like i had got in some kind of range for the birds to know i was there, but not in range to fly away.
And that totally stopped the Ally AI from moving.

Even after the birds had flown away, i ran back to the AI and he just stands there motionless.

**Comment by ZakJudges** [comment]
Hi @Tum1370, apologies for the late response. I have added a fix for this issue, which should be available in the next experimental build on Steam :)

**Comment by Tum1370** [comment]
@ZakJudges I can confirm that this bug is now fixed on latest EXP build.
Thanks for the fix Zak, i will close this issue now.
