### ISSUE TITLE
GGMAX movement problem

### ISSUE THREAD

**Issue by Jackdanielsvs68** [TheGameCreators/GameGuruRepo#2751]
Hi Guys!
The problem is that when I’m in test mode, the player wanders very slowly, but when I look down at the ground, it accelerates. I also made a short video about this, which I uploaded to youtube. Could there be a setup problem? The video card is a G-force 1050 2 gb gddr5 7000 mhz. Amd ryzen 5 1600 6 core 12 threads b 450 motherboard, 16 GB ddr4 memory. 

The video [link](https://www.youtube.com/watch?v=KniWvoIDR7k&t=40s)

**Comment by AmenMoses** [comment]
A 1050 is not really up to the job!

**Comment by dllllllllllb** [comment]
Duplicate #2240

**Comment by Jackdanielsvs68** [comment]
![Képernyőfelvétel (17)](https://user-images.githubusercontent.com/94233170/161789595-2372d04a-52e0-463f-8010-7d95dc7b4596.png)
![Képernyőfelvétel (18)](https://user-images.githubusercontent.com/94233170/161789603-18a07ad2-06c1-4818-8ba4-df287787b2e9.png)
I removed the trees, then put some back and the terrain under the house was back, which was visibly hidden in the video.
