### ISSUE TITLE
GG Max - AI Enemy Stands still until it is visible from the player

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2755]
How does the AI start to activate normally ?
I thought if we have an Enemy set to follow a path, That AI enemy would start walking its path before the character sees the Enemy ? 

But that is not the case, as Many times now i test this, And every time the AI Enemy just stands still, Until the player sees the AI Enemy. Then the enemy AI always says "What was that noise" Then ALL Enemy AI in area starts to walk their path. 
This is even if i tick the "Always Active" box in developer settings.

I think this bug is also causing the problems with my other issue with trigger points as the AI there only starts to move when the player visually sees the enemy. https://github.com/TheGameCreators/GameGuruRepo/issues/2581

Looks terrible as the game seems like it has no life, And the life springs to movement when visible from the player. 
This needs fixing.

**Comment by Necrym59** [comment]
I think the raycasting for the AI control performance is an issue, would probably be better overall to divorce tha AI control from the main program and have them run by an AI director program process much like a server client scenario.

**Comment by LeeBamberTGC** [comment]
@Tum1370 This is currently by design to help performance for all the level characters that are not playing an active role.  How about a system where you can activate characters when you enter a zone area and if you set them to activate always?

**Comment by Tum1370** [comment]
@LeeBamberTGC Really whatever you do , something needs to be done, as presently the AI looks totally dumb and unreal.

My suggestion would be a system when the player gets within a certain distance of all AI, it starts acting like it should.
You should not have to set a zone for the AI to start working.

It is really making it difficult to get a simple game looking ok with AI that stands still even when it is in range, but out of sight, like inside a building, or just around a corner.

**Comment by LeeBamberTGC** [comment]
@Tum1370 How about an activate at X range property, that way you can control when the character should 'join' the game play.  Just switching every character in the level to ON would just turn your FPS to mush :)

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Yes that is exactly what i mean. 
I certainly do not mean every character in the level to be active, that is pointless.
But really if the DEV has the option to set the distance to which AI starts to move, that would be perfect.

As an example, i have a prison block, and it is in view of the player, There are some characters inside, that you can see through windows, and the guards walking around the outside, and inside.
Currently, i can see the prison, see the inside characters just stood like statues, and nothing happens until i actually see one of the outside guards.
But having the option to set the distance on each character, the distance from player before it starts moving, would be perfect.
This way we could get it set perfect so that prison look lively, just before i get in visual range.

**Comment by Tum1370** [comment]
Ill close this issue because i think Lee has already fixed this.
