### ISSUE TITLE
GameGuru MAX - Bug - Door Blue - Door and Door White - Door Don't Function Properly with Door Rotate

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2756]
Both Door Blue - Door and Door White - Door are not animated and, as such, cannot use the Door Behavior. They also do not work with the Door Rotate Behavior, either. Even if you set IsImmobile, the door will rotate, slide-move, and float up a bit. This means that these doors can only be used as decoration in their current states and cannot be used to open/close.

**Comment by LeeBamberTGC** [comment]
@ArgentArts All doors in MAX stock objects now work using door or door rotate logic :)
