### ISSUE TITLE
light  placement glitch

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2757]
placing lights  doesn't seam to work correctly,  either the light merges with a previous placed light  or just randomly sticks to any surface.

![image](https://user-images.githubusercontent.com/68471279/161822620-e190f2c0-7a9a-4edd-96fb-4c938b62ce14.png)

**Comment by LeeBamberTGC** [comment]
Fixed in EXPERIMENTAL build.

**Comment by ZakJudges** [comment]
working in latest build
