### ISSUE TITLE
memory issues?

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2759]
looks like we've gone  back to the memory  issues  with the most  recent update:

![image](https://user-images.githubusercontent.com/68471279/161878487-0282d248-4fef-48c1-8184-6909d850dbb8.png)

**Comment by plemsoft** [comment]
@casigus Could you upload your "Guru-MapEditor.log" from when the crash happen, then im able to see where it crash , also could you let me know your system specs. Thanks for your help :)

**Comment by casigus** [comment]
121 : Name of true app: Guru-MapEditor                          S:34MB  V: (4056,0)     
135 : Flag to produce log files set in SETUP.INI (producelogfiles=1) S:0MB   V: (4056,0)     
140 : postprocessing flag at 0 and pixel shader version of 0.00 S:0MB   V: (4056,0)     
145 : The executable folder will be: F:\documents\GameGuruApps\GameGuruMAX\\MyGames\ S:0MB   V: (4056,0)     
149 : Entering 'Files' folder, now at: K:\Game GuruMax\Max\Files S:0MB   V: (4056,0)     
154 : set legacy convert mode                                   S:0MB   V: (4056,0)     
157 : _obs_memorychunkinit                                      S:0MB   V: (4056,0)     
162 : Guru-MapEditor                                            S:0MB   V: (4056,0)     
166 : detected map editor is in effect                          S:0MB   V: (4056,0)     
170 : setting display mode via DirectX                          S:0MB   V: (4056,0)     
174 : set camera aspect                                         S:0MB   V: (4056,0)     
179 : Special VR-Mode Flag: 3                                   S:0MB   V: (4056,0)     
183 : pixel states                                              S:0MB   V: (4056,0)     
191 : welcome_init(1)                                           S:0MB   V: (4056,0)     
195 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\animated-backdrop.png,65122,0,0 S:0MB   V: (4056,0)     
199 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome-assets\splash-logo.bmp,65151,0,0 S:0MB   V: (4056,0)     
203 : welcome_staticbackdrop();                                 S:0MB   V: (4056,0)     
208 : welcome_init(2)                                           S:0MB   V: (4056,0)     
212 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-page.png,65118,0,0 S:0MB   V: (4056,0)     
217 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome-assets\product-logo.png,65119,0,0 S:0MB   V: (4056,0)     
221 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\animated-backdrop.png,65122,0,0 S:0MB   V: (4056,0)     
225 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-1.png,65141,0,0 S:0MB   V: (4056,0)     
229 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-2.png,65142,0,0 S:0MB   V: (4056,0)     
234 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-3.png,65143,0,0 S:0MB   V: (4056,0)     
238 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-4.png,65144,0,0 S:0MB   V: (4056,0)     
242 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-5.png,65145,0,0 S:0MB   V: (4056,0)     
246 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-6.png,65146,0,0 S:0MB   V: (4056,0)     
251 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-7.png,65147,0,0 S:0MB   V: (4056,0)     
255 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-8.png,65148,0,0 S:0MB   V: (4056,0)     
260 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\\artwork\welcome\welcome-line-9.png,65149,0,0 S:0MB   V: (4056,0)     
264 : LOADING FONTS                                             S:0MB   V: (4056,0)     
268 : initbitmapfont - startlegacy image loading                S:0MB   V: (4056,0)     
273 : initbitmapfont - deleting old images                      S:0MB   V: (4056,0)     
277 : initbitmapfont - first font load                          S:0MB   V: (4056,0)     
291 : initbitmapfont - first font shrink                        S:1MB   V: (4057,0)     
293 : initbitmapfont - remaining font loads                     S:0MB   V: (4056,0)     
358 : shrinkbitmapfont - new medium small size text             S:6MB   V: (4063,0)     
363 : initbitmapfont - finish legacy loading                    S:1MB   V: (4064,0)     
364 : Just about to read languagebank\english\textfiles\guru-wordcount.ini S:0MB   V: (4064,0)     
372 : Language File Path:K:\Game GuruMax\Max\Files\languagebank\english\textfiles (exist=1) S:0MB   V: (4064,0)     
394 : trueappname_s=Guru-MapEditor                              S:0MB   V: (4064,0)     
411 : Create full path structure (0) for standalone executable  S:0MB   V: (4064,0)     
910 : _mp_init:                                                 S:0MB   V: (4064,0)     
910 : _material_init (0)                                        S:0MB   V: (4064,0)     
930 : We can write to the Game Guru folder!                     S:0MB   V: (4064,0)     
993 : ide input mode                                            S:0MB   V: (4064,0)     
994 : VR System disabled to improve launch speed (temporary)    S:0MB   V: (4064,0)     
998 : sync states                                               S:0MB   V: (4064,0)     
1002 : window states                                            S:0MB   V: (4064,0)     
1013 : preload generic textures early                           S:0MB   V: (4064,0)     
1092 : camera states                                            S:5MB   V: (4070,0)     
1092 : memory states                                            S:0MB   V: (4070,0)     
1550 : pre widget init state                                    S:28MB  V: (4098,0)     
1551 : WIDGET INIT                                              S:0MB   V: (4098,0)     
1555 : widget status update                                     S:0MB   V: (4098,0)     
1632 : SLIDERS INIT                                             S:15MB  V: (4114,0)     
1664 : LOAD COMMON ASSETS                                       S:1MB   V: (4116,0)     
1664 : LOADING FONTS                                            S:0MB   V: (4116,0)     
1669 : initbitmapfont                                           S:0MB   V: (4116,0)     
1673 : initbitmapfont - startlegacy image loading               S:0MB   V: (4116,0)     
1677 : initbitmapfont - deleting old images                     S:0MB   V: (4116,0)     
1681 : initbitmapfont - first font load                         S:0MB   V: (4116,0)     
1695 : initbitmapfont - first font shrink                       S:0MB   V: (4116,0)     
1697 : initbitmapfont - remaining font loads                    S:0MB   V: (4116,0)     
1759 : shrinkbitmapfont - new medium small size text            S:5MB   V: (4122,0)     
1760 : initbitmapfont - finish legacy loading                   S:0MB   V: (4122,0)     
1764 : LOADING SHADERS                                          S:0MB   V: (4122,0)     
1768 : INIT VECTORS                                             S:0MB   V: (4122,0)     
1772 : INIT SKY ASSETS                                          S:0MB   V: (4122,0)     
1777 : entering skybank                                         S:0MB   V: (4122,0)     
1781 : checking skybank files                                   S:0MB   V: (4122,0)     
1786 : CGYSkyboxStarry                                          S:0MB   V: (4122,0)     
1790 : CWD:K:\Game GuruMax\Max\Files\skybank
LOAD IMAGE cgyskyboxstarry\preview.bmp,43301,0,0 S:0MB   V: (4122,0)     
2287 : clear                                                    S:175MB V: (4297,0)     
2290 : cloudy                                                   S:0MB   V: (4298,0)     
2297 : descent                                                  S:0MB   V: (4298,0)     
2297 : CWD:K:\Game GuruMax\Max\Files\skybank
LOAD IMAGE descent\preview.bmp,43304,0,0 S:0MB   V: (4298,0)     
2727 : dusk                                                     S:172MB V: (4470,0)     
2730 : fluffy                                                   S:-1MB  V: (4469,0)     
2735 : highcloud                                                S:0MB   V: (4469,0)     
2740 : london                                                   S:0MB   V: (4469,0)     
2743 : CWD:K:\Game GuruMax\Max\Files\skybank
LOAD IMAGE london\preview.bmp,43308,0,0 S:0MB   V: (4469,0)     
2857 : night                                                    S:96MB  V: (4565,0)     
2860 : overcast                                                 S:0MB   V: (4565,0)     
2865 : stormy                                                   S:0MB   V: (4566,0)     
2870 : sunny                                                    S:0MB   V: (4566,0)     
2875 : sunrise                                                  S:0MB   V: (4566,0)     
2880 : sunset                                                   S:0MB   V: (4566,0)     
2884 : wolf359                                                  S:0MB   V: (4566,0)     
2895 : finished sky bank scan                                   S:0MB   V: (4566,0)     
2896 : INIT TERRAIN ASSETS                                      S:0MB   V: (4566,0)     
2900 : INIT GAME VISUAL ASSETS                                  S:0MB   V: (4566,0)     
2906 : visuals.sky$=None                                        S:0MB   V: (4566,0)     
2910 : visuals.terrain$=                                        S:0MB   V: (4566,0)     
2914 : visuals.vegetation$=                                     S:0MB   V: (4566,0)     
3007 : INIT DECAL ASSETS                                        S:896MB V: (5463,0)     
3044 : INIT LIGHTMAP ASSETS                                     S:2MB   V: (5465,0)     
3045 : SCANNING G-LIST                                          S:0MB   V: (5465,0)     
3134 : gun 1:BSP Sci-Fi\BSP Sci-Fi\Flux M200 Ravager\gunspec.txt S:1MB   V: (5467,0)     
3134 : gun 2:BSP Sci-Fi\Flux M200 Ravager\gunspec.txt           S:0MB   V: (5467,0)     
3139 : gun 3:BSP Sci-Fi\IronFist Shotgun\gunspec.txt            S:0MB   V: (5467,0)     
3143 : gun 4:BSP Sci-Fi\QuasarGun\gunspec.txt                   S:0MB   V: (5467,0)     
3148 : gun 5:BSP Sci-Fi\S4-VC6 Pistol\gunspec.txt               S:0MB   V: (5467,0)     
3152 : gun 6:BSP Sci-Fi\Sniper R400 Panther\gunspec.txt         S:0MB   V: (5467,0)     
3157 : gun 7:BSP Sci-Fi\Typhoon\gunspec.txt                     S:0MB   V: (5467,0)     
3161 : gun 8:cartoon\RayGun\gunspec.txt                         S:0MB   V: (5467,0)     
3165 : gun 9:Cybernoir\HIP-0\gunspec.txt                        S:0MB   V: (5467,0)     
3169 : gun 10:Cybernoir\MetaMerican SPS-58\gunspec.txt          S:0MB   V: (5467,0)     
3174 : gun 11:Cybernoir\Shiriyama BBSTR 10\gunspec.txt          S:0MB   V: (5467,0)     
3178 : gun 12:Cybernoir\ShiriyamaRiot12\gunspec.txt             S:0MB   V: (5467,0)     
3183 : gun 13:Cybernoir\Vunderland\gunspec.txt                  S:0MB   V: (5467,0)     
3187 : gun 14:Cybernoir\Vunderland FA1\gunspec.txt              S:0MB   V: (5467,0)     
3191 : gun 15:Cybernoir\W-AZP 3\gunspec.txt                     S:0MB   V: (5467,0)     
3196 : gun 16:dagored\lasergun\gunspec.txt                      S:0MB   V: (5467,0)     
3200 : gun 17:enhanced\AK\gunspec.txt                           S:0MB   V: (5467,0)     
3204 : gun 18:enhanced\AR\gunspec.txt                           S:0MB   V: (5467,0)     
3209 : gun 19:enhanced\B810\gunspec.txt                         S:0MB   V: (5467,0)     
3213 : gun 20:enhanced\Gloves_Unarmed\gunspec.txt               S:0MB   V: (5467,0)     
3217 : gun 21:enhanced\M29S\gunspec.txt                         S:0MB   V: (5467,0)     
3222 : gun 22:enhanced\M67\gunspec.txt                          S:0MB   V: (5467,0)     
3226 : gun 23:enhanced\Mk18\gunspec.txt                         S:0MB   V: (5467,0)     
3230 : gun 24:enhanced\Mk19T\gunspec.txt                        S:0MB   V: (5467,0)     
3234 : gun 25:enhanced\R870\gunspec.txt                         S:0MB   V: (5467,0)     
3239 : gun 26:enhanced\SledgeHammer\gunspec.txt                 S:0MB   V: (5467,0)     
3244 : gun 27:erart\magical_hand\gunspec.txt                    S:0MB   V: (5467,0)     
3248 : gun 28:erart\octopus\gunspec.txt                         S:0MB   V: (5467,0)     
3251 : gun 29:fantasy\axe\gunspec.txt                           S:0MB   V: (5467,0)     
3257 : gun 30:fantasy\bow\gunspec.txt                           S:0MB   V: (5467,0)     
3261 : gun 31:fantasy\IceStaff\gunspec.txt                      S:0MB   V: (5467,0)     
3265 : gun 32:fantasy\knife\gunspec.txt                         S:0MB   V: (5467,0)     
3270 : gun 33:fantasy\knightsword\gunspec.txt                   S:0MB   V: (5467,0)     
3275 : gun 34:fantasy\Magic Staff\gunspec.txt                   S:0MB   V: (5467,0)     
3280 : gun 35:fantasy\PoisonStaff\gunspec.txt                   S:0MB   V: (5467,0)     
3284 : gun 36:fantasy\skellysword\gunspec.txt                   S:0MB   V: (5467,0)     
3289 : gun 37:fantasy\Staff\gunspec.txt                         S:0MB   V: (5467,0)     
3294 : gun 38:futuristic\FuturetekShotgun\gunspec.txt           S:0MB   V: (5467,0)     
3299 : gun 39:Garden weapons\Garden axe\gunspec.txt             S:0MB   V: (5467,0)     
3304 : gun 40:Garden weapons\Hand cultivator\gunspec.txt        S:0MB   V: (5467,0)     
3309 : gun 41:Garden weapons\Hand grubber\gunspec.txt           S:0MB   V: (5467,0)     
3313 : gun 42:Garden weapons\Hand hoe\gunspec.txt               S:0MB   V: (5467,0)     
3318 : gun 43:Garden weapons\Hand trowel\gunspec.txt            S:0MB   V: (5467,0)     
3329 : gun 44:Garden weapons\Pruning shears\gunspec.txt         S:0MB   V: (5467,0)     
3333 : gun 45:Garden weapons\Sickle\gunspec.txt                 S:0MB   V: (5467,0)     
3338 : gun 46:Garden weapons\Slasher\gunspec.txt                S:0MB   V: (5467,0)     
3343 : gun 47:graphix\G-Sabre-Blue\gunspec.txt                  S:0MB   V: (5467,0)     
3348 : gun 48:graphix\G-Sabre-Red\gunspec.txt                   S:0MB   V: (5467,0)     
3352 : gun 49:Gtox medieval\Axe\gunspec.txt                     S:0MB   V: (5467,0)     
3357 : gun 50:Gtox medieval\Battle axe\gunspec.txt              S:0MB   V: (5467,0)     
3361 : gun 51:Gtox medieval\Broadsword\gunspec.txt              S:0MB   V: (5467,0)     
3366 : gun 52:Gtox medieval\Carving knife\gunspec.txt           S:0MB   V: (5467,0)     
3370 : gun 53:Gtox medieval\Cleaver\gunspec.txt                 S:0MB   V: (5467,0)     
3375 : gun 54:Gtox medieval\Cutlass\gunspec.txt                 S:0MB   V: (5467,0)     
3380 : gun 55:Gtox medieval\Demon sword\gunspec.txt             S:0MB   V: (5467,0)     
3384 : gun 56:Gtox medieval\Dragon staff\gunspec.txt            S:0MB   V: (5467,0)     
3389 : gun 57:Gtox medieval\Ebony bow\gunspec.txt               S:0MB   V: (5467,0)     
3394 : gun 58:Gtox medieval\Falchion\gunspec.txt                S:0MB   V: (5467,0)     
3398 : gun 59:Gtox medieval\Iron dagger\gunspec.txt             S:0MB   V: (5467,0)     
3403 : gun 60:Gtox medieval\Iron halberd\gunspec.txt            S:0MB   V: (5467,0)     
3407 : gun 61:Gtox medieval\Katana\gunspec.txt                  S:0MB   V: (5467,0)     
3412 : gun 62:Gtox medieval\Longsword\gunspec.txt               S:0MB   V: (5467,0)     
3417 : gun 63:Gtox medieval\Plain halberd\gunspec.txt           S:0MB   V: (5467,0)     
3422 : gun 64:Gtox medieval\Rusty knife\gunspec.txt             S:0MB   V: (5467,0)     
3427 : gun 65:Gtox medieval\Scythe\gunspec.txt                  S:0MB   V: (5467,0)     
3432 : gun 66:Gtox medieval\Short sword\gunspec.txt             S:0MB   V: (5467,0)     
3436 : gun 67:Gtox medieval\Spiked mace\gunspec.txt             S:0MB   V: (5467,0)     
3441 : gun 68:Gtox medieval\Steel mace\gunspec.txt              S:0MB   V: (5467,0)     
3445 : gun 69:Gtox medieval\Steel sword\gunspec.txt             S:0MB   V: (5467,0)     
3450 : gun 70:Gtox medieval\Studded club\gunspec.txt            S:0MB   V: (5467,0)     
3454 : gun 71:Gtox medieval\Wizard's staff\gunspec.txt          S:0MB   V: (5467,0)     
3459 : gun 72:Gtox medieval\Wooden bow\gunspec.txt              S:0MB   V: (5467,0)     
3464 : gun 73:Gtox medieval\Zweihander\gunspec.txt              S:0MB   V: (5467,0)     
3468 : gun 74:Gtox weapons\Sword10\gunspec.txt                  S:0MB   V: (5467,0)     
3473 : gun 75:medieval\Bow\gunspec.txt                          S:0MB   V: (5467,0)     
3477 : gun 76:medieval\Crossbow\gunspec.txt                     S:0MB   V: (5467,0)     
3481 : gun 77:medieval\Dagger\gunspec.txt                       S:0MB   V: (5467,0)     
3485 : gun 78:medieval\Flail\gunspec.txt                        S:0MB   V: (5467,0)     
3490 : gun 79:medieval\Halberd\gunspec.txt                      S:0MB   V: (5467,0)     
3494 : gun 80:medieval\Hatchet\gunspec.txt                      S:0MB   V: (5467,0)     
3498 : gun 81:medieval\Mace\gunspec.txt                         S:0MB   V: (5467,0)     
3502 : gun 82:medieval\Slingshot\gunspec.txt                    S:0MB   V: (5467,0)     
3507 : gun 83:medieval\Stones\gunspec.txt                       S:0MB   V: (5467,0)     
3512 : gun 84:medieval\Sword\gunspec.txt                        S:0MB   V: (5467,0)     
3516 : gun 85:mele\crowbar\gunspec.txt                          S:0MB   V: (5467,0)     
3520 : gun 86:melee\baseball bat\gunspec.txt                    S:0MB   V: (5467,0)     
3529 : gun 87:melee\battle axe\gunspec.txt                      S:0MB   V: (5467,0)     
3533 : gun 88:melee\bow saw\gunspec.txt                         S:0MB   V: (5467,0)     
3537 : gun 89:melee\broadsword\gunspec.txt                      S:0MB   V: (5467,0)     
3542 : gun 90:melee\carving knife\gunspec.txt                   S:0MB   V: (5467,0)     
3546 : gun 91:melee\cleaver\gunspec.txt                         S:0MB   V: (5467,0)     
3550 : gun 92:melee\combat knife\gunspec.txt                    S:0MB   V: (5467,0)     
3555 : gun 93:melee\cricket bat\gunspec.txt                     S:0MB   V: (5467,0)     
3560 : gun 94:melee\crowbar\gunspec.txt                         S:0MB   V: (5467,0)     
3564 : gun 95:melee\Cutlass\gunspec.txt                         S:0MB   V: (5467,0)     
3568 : gun 96:melee\Demon sword\gunspec.txt                     S:0MB   V: (5467,0)     
3573 : gun 97:melee\ebony bow\gunspec.txt                       S:0MB   V: (5467,0)     
3578 : gun 98:melee\Falchion\gunspec.txt                        S:0MB   V: (5467,0)     
3582 : gun 99:melee\file\gunspec.txt                            S:0MB   V: (5467,0)     
3586 : gun 100:melee\fire axe\gunspec.txt                       S:0MB   V: (5467,0)     
3591 : gun 101:melee\garden fork\gunspec.txt                    S:0MB   V: (5467,0)     
3595 : gun 102:melee\hammer\gunspec.txt                         S:0MB   V: (5467,0)     
3600 : gun 103:melee\homemade scythe\gunspec.txt                S:0MB   V: (5467,0)     
3604 : gun 104:melee\homemade slasher\gunspec.txt               S:0MB   V: (5467,0)     
3609 : gun 105:melee\Iron dagger\gunspec.txt                    S:0MB   V: (5467,0)     
3614 : gun 106:melee\lead pipe\gunspec.txt                      S:0MB   V: (5467,0)     
3618 : gun 107:melee\Longsword\gunspec.txt                      S:0MB   V: (5467,0)     
3623 : gun 108:melee\machete\gunspec.txt                        S:0MB   V: (5467,0)     
3628 : gun 109:melee\panga\gunspec.txt                          S:0MB   V: (5467,0)     
3633 : gun 110:melee\pickaxe\gunspec.txt                        S:0MB   V: (5467,0)     
3637 : gun 111:melee\rake\gunspec.txt                           S:0MB   V: (5467,0)     
3642 : gun 112:melee\screwdriver\gunspec.txt                    S:0MB   V: (5467,0)     
3647 : gun 113:melee\shovel\gunspec.txt                         S:0MB   V: (5467,0)     
3651 : gun 114:melee\sledgehammer\gunspec.txt                   S:0MB   V: (5467,0)     
3656 : gun 115:melee\spanner\gunspec.txt                        S:0MB   V: (5467,0)     
3660 : gun 116:melee\tire iron\gunspec.txt                      S:0MB   V: (5467,0)     
3664 : gun 117:melee\wrench\gunspec.txt                         S:0MB   V: (5467,0)     
3669 : gun 118:modern\colt1911\gunspec.txt                      S:0MB   V: (5467,0)     
3673 : gun 119:modern\Grenade\gunspec.txt                       S:0MB   V: (5467,0)     
3678 : gun 120:modern\Magnum357\gunspec.txt                     S:0MB   V: (5467,0)     
3682 : gun 121:modern\Shotgun\gunspec.txt                       S:0MB   V: (5467,0)     
3686 : gun 122:modern\SniperM700\gunspec.txt                    S:0MB   V: (5467,0)     
3692 : gun 123:modern\Uzi\gunspec.txt                           S:0MB   V: (5467,0)     
3696 : total guns=123                                           S:0MB   V: (5467,0)     
7125 : LOAD PLAYER SOUNDS                                       S:0MB   V: (5468,0)     
7396 : CREATING TERRAIN                                         S:7MB   V: (5476,0)     
7396 : NEWMAP: Starting new map                                 S:0MB   V: (5476,0)     
7446 : visuals.sky$=None                                        S:0MB   V: (5476,0)     
7447 : visuals.terrain$=                                        S:0MB   V: (5476,0)     
7451 : visuals.vegetation$=                                     S:0MB   V: (5476,0)     
7455 : NEWMAP: _gridedit_clear_settings                         S:0MB   V: (5476,0)     
7460 : NEWMAP: cleantestmapfolder                               S:0MB   V: (5476,0)     
16777 : total extra PFBs=1                                      S:1MB   V: (5477,0)     
16778 : NEWMAP: _terrain_createactualterrain                    S:0MB   V: (5477,0)     
16782 : NEWMAP: Save newly flattened terrain                    S:0MB   V: (5477,0)     
16788 : NEWMAP: Save terrain data                               S:0MB   V: (5477,0)     
16792 : NEWMAP: Finish creating new map                         S:0MB   V: (5477,0)     
16796 : SCANNING SKY SETTINGS                                   S:0MB   V: (5477,0)     
16801 : Initialise sky textures                                 S:0MB   V: (5477,0)     
16806 : Load sky cube:skybank\None\None_cube.dds                S:0MB   V: (5477,0)     
16811 : INIT POST PROCESSING                                    S:0MB   V: (5477,0)     
16815 : INIT RAGDOLL SYSTEM                                     S:0MB   V: (5477,0)     
16821 : CREATING P-LIST                                         S:0MB   V: (5477,0)     
18456 : CREATING E-LIST                                         S:93MB  V: (5571,0)     
18527 : LOADING INTO P-LIST                                     S:9MB   V: (5581,0)     
18528 : CREATING B-LIST                                         S:0MB   V: (5581,0)     
18943 : INIT EDITOR RESOURCES                                   S:43MB  V: (5624,0)     
18944 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE editors\gfx\memorymeter.png,65112,0,0 S:0MB   V: (5624,0)     
18969 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\english\artwork\testgamelayout-noweapons.png,65137,0,0 S:0MB   V: (5624,0)     
18974 : LOAD MAIN RESOURCES                                     S:1MB   V: (5626,0)     
18975 : UPDATE VISUAL SETTINGS                                  S:0MB   V: (5626,0)     
18980 :                                                         S:0MB   V: (5626,0)     
18998 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome\welcome-play.png,65167,0,0 S:0MB   V: (5626,0)     
19004 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome-assets\product-example.png,65169,0,0 S:0MB   V: (5626,0)     
19005 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome-assets\gameguru-news-banner.png,65174,0,0 S:0MB   V: (5626,0)     
19030 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE ,65174,0,0     S:0MB   V: (5626,0)     
19235 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE editors\uiv3\pointer2.png,43046,0,0 S:3MB   V: (5629,0)     
19255 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE editors\uiv3\ABOUT-Country.png,43052,0,0 S:1MB   V: (5630,0)     
19413 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE entitybank\_markers\Trigger Zone.bmp,43093,0,0 S:0MB   V: (5631,0)     
19414 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE entitybank\_markers\flag.bmp,43094,0,0 S:0MB   V: (5631,0)     
19424 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE editors\uiv3\dotchrome.dds,43096,0,0 S:0MB   V: (5631,0)     
20457 : preload CCP textures early                              S:177MB V: (5808,0)     
20458 : Guru Map Editor Loop Starts                             S:0MB   V: (5808,0)     
41490 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE ,65174,0,0     S:227MB V: (6036,0)     
41498 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome\welcome-play.png,65167,0,0 S:0MB   V: (6036,0)     
41500 : CWD:K:\Game GuruMax\Max\Files
LOAD IMAGE languagebank\english\artwork\welcome-assets\product-example.png,65169,0,0 S:0MB   V: (6036,0)     
124128 : Clearing 18 TXP cache files                            S:190MB V: (6227,0)     
124129 : Clearing complete.                                     S:0MB   V: (6227,0)

**Comment by casigus** [comment]
andddd  
![image](https://user-images.githubusercontent.com/68471279/162012090-aeaa9e87-e790-4b79-a732-a321fb62bd8c.png)

the  gpu has 4 gigs of memory, its  a amd thingy ma bob :)

**Comment by plemsoft** [comment]
@casigus In your log, it looks like you have not loaded any levels or added and objects , how did this crash ?

**Comment by casigus** [comment]
Obiviously I have loaded levels.  

this happens in every build post release,  including the patch'd steam version. rolled back max to the week before launch version, not  has this issue once. its a  memory  issue caused by the last  few updates.

the crash happens with no real pattern, barring one. Placing  an object,and boom crash,  memory error, and its any  time  of object,  even a decal did it.  So  its something broken since the launch. Also if its  not updating the log then I guess  that's another  problem to update  with too.

**Comment by plemsoft** [comment]
@casigus Do you have any custom objects on your level ? not stock ? , if so i think we already fixed the issue, there was a problem with custom objects that could make it crash , this has been fixed and will be in the next update , Let me know :)

**Comment by casigus** [comment]
Ayeeee! I sure do!!


On 8 April 2022, at 06:52, Preben Eriksen ***@***.***> wrote:


@casigus<https://github.com/casigus> Do you have any custom objects on your level ? not stock ? , if so i think we already fixed the issue, there was a problem with custom objects that could make it crash , this has been fixed and will be in the next update , Let me know :)

**Comment by plemsoft** [comment]
@casigus Was this fixed for you in the current version "2022.04.22" ?

**Comment by casigus** [comment]
yassss!!  :)
