### ISSUE TITLE
Runtime Error: 0 : Enhancement Runtime Error 133 ()

### ISSUE THREAD

**Issue by relishrompgames** [TheGameCreators/GameGuruRepo#2762]
I was working on my game, imported 3 simple models. Placed them. GGMax crashes.

Restart and load my game and then "Runtime Error: 0 : Enhancement Runtime Error 133 ()"

**Comment by plemsoft** [comment]
@relishrompgames Is this the same game as you wrote about here: https://github.com/TheGameCreators/GameGuruRepo/issues/2761
?

**Comment by plemsoft** [comment]
@relishrompgames I assume this was related to your other issue, that are fixed, if not just open this issue again, Thanks for your help :)
