### ISSUE TITLE
Placing lights - They are in the wrong x,y,z position.

### ISSUE THREAD

**Issue by relishrompgames** [TheGameCreators/GameGuruRepo#2766]
When I place the lights, they seem to located at the wrong x,y,z coordinates. See this video. 

https://youtu.be/DxFNZhM49Yo

[youtube]DxFNZhM49Yo[/youtube]

**Comment by LeeBamberTGC** [comment]
Fixed in EXPERIMENTAL build.

**Comment by ZakJudges** [comment]
Working in latest experimental
