### ISSUE TITLE
MAX Crashes on launch

### ISSUE THREAD

**Issue by PeteHollyer** [TheGameCreators/GameGuruRepo#2768]
[dxdiagreport.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8437689/dxdiagreport.txt)

I've included the dxdiag report; hope this can be fixed. I should note that I boot on C Drive, Max is installed on my D Drive. ALSO I don't use laptop monitor, but instead a 27  inch Dell flat screen monitor

I've downloaded and played with earlier versions without problems. I'm currently using steam pre-release.

thx
Pete

**Comment by plemsoft** [comment]
@PeteHollyer Thanks for reporting this issue, do you get any messages ? , if not could you post your "Guru-MapEditor.log" file here so im able to see how far it comes , Thanks for your help :)

**Comment by ricscar2570** [comment]
I have the same problem since the beginning. Where could I find the *.log file ?
Tx!

**Comment by PeteHollyer** [comment]
The main screen appears…nothing populated(Menu/toolbar, etc)…the “Game GURU Max has stopped responding “
Then the standard popup debug window.

I’ll post log asap

Pete

Sent from Mail for Windows

**Comment by PeteHollyer** [comment]
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8443168/Guru-MapEditor.log)

FOUND IT!!!

it's in "C:\Users\Pete\Documents\GameGuruApps\GameGuruMAX"

**Comment by relishrompgames** [comment]
By any chance, are you using Game Guru Classic entities? Thanks!

**Comment by PeteHollyer** [comment]
I own just about everything you guys have made...BUT currently installed I only have AppGameKit Classic AND AppGameKit Studio installed and ALL the Graphics packs associated with them. 
For GameGuruMAX,  I ONLY have the Steam GameGuruMax and the associated Graphics Booster Pack Installed.
Pete

**Comment by PeteHollyer** [comment]
I uninstalled the DLC (Booster pack), and launched Max This time  it shows a new screen with sample games (I assume the Application desktop titled "Game Guru MAX Hub Screen"), and "stuff" BUT this screen is completely frozen. As you see in the LOG it makes it a little.  I included screen shots and a second LOG (Ignore first)
![CrashNow](https://user-images.githubusercontent.com/13394981/162222744-d8eb3534-64f6-4488-94e3-64203c918d0a.png)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8443844/Guru-MapEditor.log)

 farther! 

[Guru-MapEditor.log](http
![Previous Crash](https://user-images.githubusercontent.com/13394981/162222719-bacd0881-5797-43ea-994e-37bed2e86f2b.png)
s://github.com/TheGameCreators/GameGuruRepo/files/8443794/Guru-MapEditor.log)
.

**Comment by plemsoft** [comment]
@PeteHollyer Just checked your card. 960M
https://www.videocardbenchmark.net/compare/GeForce-GTX-960M-vs-GeForce-GTX-960/3176vs3114

The speed is way below the minimum spec, that currently is GeForce GTX 960, anyway it should startup as it do have 4gb dedicated mem , but the speed would not be good, anyway could you try to update to the latest drivers for your card and check if that solve your issue , thanks :)

**Comment by plemsoft** [comment]
@PeteHollyer Found a bug that could cause this, this has been fixed and will be in the next update :)
