### ISSUE TITLE
Crash - Qt5WinExtras.dll was not found

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#2774]
![image](https://user-images.githubusercontent.com/38034903/162225035-7cffcaab-f463-4f11-ad84-32f9a501ee3e.png)
No idea what's causing this. I tried reinstalling and even downloading Python. Help please

**Comment by plemsoft** [comment]
@MartinCranshaw Thanks for reporting this issue, its not a Max crash , but i crash from your "Radeon Settings" , i cant say why it crash, but i would try to install the latest update to your graphics drivers, that i believe also include the "Radeon Settings" program "AMDRSSrcExt.exe" , check if that solves your issue :)

**Comment by MartinCranshaw** [comment]
Thanks plemsoft. I scrapped the level as I been experimenting with it and a new clean level seems fine. Newest drivers on Video card thankyou for getting in touch.

**Comment by plemsoft** [comment]
@MartinCranshaw Ah in that case you could have been running out of mem. that could cause the crash in "Radeon Settings", in settings->developer try to tick "Show Live FPS And Memory Stats" , This will display the mem used by Max. But other programs running at the same time also need mem, so if your level gets to big and other programs starts crashing, check your mem use and you have an idea about how much mem your able to use before your running low :)
