### ISSUE TITLE
Snubnose Revolver problem in standalone game

### ISSUE THREAD

**Issue by mujaidin71** [TheGameCreators/GameGuruRepo#2775]
In standalone game "Snubnose Revolver" cannot be reloaded by Pistol ammo or 44 Magnum ammo (compatible in description alt poolammo gunspec.txt).

I have make an video exemple for you! please fix!

https://www.youtube.com/watch?v=fHUiWVLzkTg

**Comment by ZakJudges** [comment]
Hi @mujaidin71, this has been fixed and should be in the next available update :) #2443

**Comment by mujaidin71** [comment]
Thank you very much, but when the date fix will be released also because it is not possible to play with that weapon!

**Comment by ZakJudges** [comment]
@mujaidin71 I believe the next update will be publicly available later today :)

**Comment by mujaidin71** [comment]
this is great news! have a nice day! :-)

**Comment by ZakJudges** [comment]
Hi @mujaidin71, could you confirm if this issue is now fixed for you? Thanks :)

**Comment by mujaidin71** [comment]
yes is now OKAY!  thanks!

Il giorno mar 19 apr 2022 alle ore 12:38 ZakJudges ***@***.***>
ha scritto:

**Comment by ZakJudges** [comment]
Great, thank you for confirming. Closing this issue now
