### ISSUE TITLE
Importer no longer importing many textures.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2779]
![image](https://user-images.githubusercontent.com/99803873/162371445-18358a22-cfde-44d7-af55-b3374e5b04e9.png)

Models that could be imported previously no longer have textures. This model is large pipe from the Classic Cold War pack and was last successfully imported 16/03/2022. Now the texture isn't being imported.

Some models do still work.

**Comment by synchromesh62** [comment]
Tested and confirmed.
Importer not assigning textures

**Comment by ZakJudges** [comment]
Hi @davetgc, I imported the model seen in the screenshot and confirmed the issue you are seeing. I also tried it in a previous build from September, and still saw the issue. Would you be able to send me one of the models that still works? That would allow me to compare the two, so I can see where things go wrong. Thanks!

**Comment by ZakJudges** [comment]
Hi @davetgc, a fix will become available in the experimental build in the next day or so. Could you let me know if it sorts the issue for you? Thanks!

**Comment by davetgc** [comment]
Thanks Zak, I'll let you know.

**Comment by davetgc** [comment]
Hi Zak, the models previously raised now work, however, some models still don't, Tried to import from the Classic Desert Pack. Joshua Tree 1.

![image](https://user-images.githubusercontent.com/99803873/164400953-f4394e62-f413-4168-ad42-292fff02655f.png)

**Comment by ZakJudges** [comment]
Hi @davetgc, thanks for the extra info. I'll take another look at this later today :)

**Comment by ZakJudges** [comment]
Hi @davetgc I've added a fix for Classic .X files importing without textures. It should be in tomorrow's experimental build :)

**Comment by davetgc** [comment]
Thanks!

**Comment by davetgc** [comment]
As an update. The classic Fantasy pack also doesn't import, but has a
slightly different issue

[image: image.png]

**Comment by ZakJudges** [comment]
@davetgc I can't see the image, would  you be able to attach it via GitHub directly?

**Comment by davetgc** [comment]
I'm just getting import errors when trying to upload the image! I'll email it to you.

**Comment by ZakJudges** [comment]
Hi @davetgc, are you happy for this one to be closed now? :)

**Comment by davetgc** [comment]
I think there are still some issues, I'll look tomorrow.

**Comment by ZakJudges** [comment]
@davetgc Any update on this? :)

**Comment by LeeBamberTGC** [comment]
I will test and close this soon, please let me know if it is still an issue, thanks!

**Comment by davetgc** [comment]
Hi, No, it doesn't always work.  I'll hunt down a model from a model pack
that's still broken.

**Comment by LeeBamberTGC** [comment]
@davetgc Thanks!  You can send it directly to lee@thegamecreators.com :)

**Comment by davetgc** [comment]
I'll need to test. I'll let you know.
