### ISSUE TITLE
4K TV needs UI to be larger

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2780]
@plemsoft A user sent me this screen shot of MAX from his 4K TV. The UI buttons are very small. Is there an easy way to enlarge them all? He has tried the DPI setting but that did not help.
![image](https://user-images.githubusercontent.com/1503593/162382645-6ddb8ae1-6818-462e-8ce3-824e40dc29b0.png)

**Comment by plemsoft** [comment]
@rvanner To make the buttons larger, you need to uncheck "Enable DPI Awareness" in settings:

![settings-dpi](https://user-images.githubusercontent.com/18662417/162418633-b5149b6d-afe7-4272-b193-7491eb135002.jpg)

Then your able to use windows 10 "Display Settings" to set your button  and text size:

![display-settings](https://user-images.githubusercontent.com/18662417/162418920-c00ebed6-5551-4b23-a866-bffb8f88439d.jpg)

**Comment by rvanner** [comment]
Thanks Preben!
