### ISSUE TITLE
Standalone - Menu Flickering

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2784]
https://www.youtube.com/watch?v=XJ-Pw4nTHgc

**Comment by ZakJudges** [comment]
Note for future: When a new titles page is switched to, the last page is freed (images deleted) but the new page is not displayed until the following frame - leading to the flickering. With recent storyboard changes, it looks like the titles page system will be replaced. This can be fixed at the same time as that.

**Comment by plemsoft** [comment]
@dllllllllllb Just tried this in the latest EXP build and it looks like its been fixed, could you confirm this and close the issue if it also works for you , Thanks :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges @Maciek might be busy, can you confirm this fix, thanks!

**Comment by ZakJudges** [comment]
@plemsoft Hi Preben, this still happens under the following conditions:

- Untick "Transparent Backdrop" in the Game Paused screen and add an image as the backdrop
- Play the standalone and bring up the Game Paused screen
- Now navigate to another screen that does not have a transparent backdrop such as load game
- See the flicker when switching screens

Thanks :)

**Comment by plemsoft** [comment]
@ZakJudges Thanks can see it now, and fixed it for the next exp :)
