### ISSUE TITLE
Standalone - Health regeneration doesn't work

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2786]
Player health flashes yellow but doesn't regenerate.

**Comment by ZakJudges** [comment]
@dllllllllllb I wasn't able to reproduce this one. Do you have steps I could follow?

**Comment by dllllllllllb** [comment]
@ZakJudges I can't reproduce it as well. It happened in Canyon Offensive demo, not sure what could have caused it. I'll close it for now, if it happens again I'll re-open it with more info.
