### ISSUE TITLE
GameGuru MAX - Bug? - Possible Collision Issue with Polygon Collision?

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2788]
I'm in the process of creating my tutorial for collision shapes when I ran across this:

https://user-images.githubusercontent.com/36735507/162482379-312f411b-e83c-4c00-90a2-aca18f2be60f.mp4

Notice that no matter which collision shape I assign to the barrels, I can jump up on them, but polygonal collision gives me issues. If I am against the barrels, I cannot jump up on top. I have to be back away from the barrels to jump up on top of them. With all the others, no matter which collision shape I assign them, I am able to jump right up on top, even if I am flush up against the collision shape.

**Comment by Tum1370** [comment]
@ArgentArts How did you turn on this visible collision mesh ?

**Comment by ArgentArts** [comment]
First, go to Edit>Settings and go to the Developer tab and make sure to tick "Show Additional Developer Options":

![dev](https://user-images.githubusercontent.com/36735507/162496974-df6a3261-26e5-4f3a-8719-a92cee712e25.png)

Then, when in your test game, use the TABTAB menu. On the right-side, look for Physics and tick the "Render Physics Shapes" and wait a moment for it to render them (it may take several moments before they appear):

![dev2](https://user-images.githubusercontent.com/36735507/162497450-c10988fd-a15d-4931-b65e-64e08c133d95.png)

**Comment by Tum1370** [comment]
@ArgentArts Thanks

**Comment by ZakJudges** [comment]
@LeeBamberTGC I think this is due to the object having a large number of polygons with different directions having to resolve collisions with the player capsule, compared to the simpler shapes, causing the results to be inconsistent with the simpler collision shapes. Not really sure if we are able to do anything about that? I think its just a case of polygon collision not being well-suited to the object.

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges I would agree. I would never use polygonal collision for a shape like this. I just wanted to point it out as I noticed it when making my tutorial on collision shapes.
