### ISSUE TITLE
Winzone needs to take into account Y value

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#2790]
In the latest demo (Canyon Offensive) if you stand under the helicopter platform (i.e. in the first portion of the demo) it triggers the winzone!

**Comment by synchromesh62** [comment]
Ye this is why i requested a **show on startup** tick box for Trigger zones.
that way another triggerzone ( perhaps around a radio requesting extraction ) would spawn it.

**Comment by Ghost-l0l** [comment]
every trigger zone works like that, and it is like that in gg classic too! In my opinion it was done best in fps creator, where you had easy to adjust, semi-transparent box that could be stack on top of each other and will still work. Right now we working with 2d plane that pretends to use 3d space. Thats not good. If Max is supposed to be used also in indoor levels then this whole system needs to be reworked.

**Comment by Ghost-l0l** [comment]
> Ye this is why i requested a **show on startup** tick box for Trigger zones. that way another triggerzone ( perhaps around a radio requesting extraction ) would spawn it. And of course have many other handy uses :)

spawning 1 trigger with another trigger while both of them not usin Y value would be a "good enough" workaround if you can trick players with you designs... but it wouldn't solve the problem. If this winzone was turned on by other triggerzone, player could still get back and walk under that helicopter (unless he was so immersed in gameplay that he would forget about checking it out). What about open worlds where you can get back to places? What about multi-floor indoor levels?

**Comment by synchromesh62** [comment]
> > Ye this is why i requested a **show on startup** tick box for Trigger zones. that way another triggerzone ( perhaps around a radio requesting extraction ) would spawn it. And of course have many other handy uses :)
> 
> spawning 1 trigger with another trigger while both of them not usin Y value would be a "good enough" workaround if you can trick players with you designs... but it wouldn't solve the problem. If this winzone was turned on by other triggerzone, player could still get back and walk under that helicopter (unless he was so immersed in gameplay that he would forget about checking it out). What about open worlds where you can get back to places? What about multi-floor indoor levels?

In short .. I would still want the **show on startup** tick box anyway. 
It does solve the problem of a trigger zone being there when i want it to and one event leading to another :)

**Comment by Ghost-l0l** [comment]
@synchromesh62 yeah I can agree that your idea is very good, tickbox like that would be very usefull and it will let users set events in order, or simple chain-reactions with just few clicks. 
 But Its not solving the problem that AmenMoses is talking about here. Even Fps Creator can recognize Y value in triggerzone placements, why GG can't? It's important issue, especially indoors, on more complex multi-layerd levels.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Takes account for player Y in next EXP build.

**Comment by mike123yy** [comment]
I see this thread is showing fixed but needs confirmation. I'm still having this problem as of May 9. I have a two-story building and if the player walks below or above a trigger zone or win zone on a different floor it will activate the trigger. I agree with the comments above, these zones do need the spawn at start checkbox then we can make the player go to the guided area and trigger the trigger zone or win zone and that would solve a lot of problems

**Comment by ZakJudges** [comment]
Apologies for the late response. This should now be fixed. Additionally, the Trigger Zone and Win Zone both have Spawn At Start Checkboxes
