### ISSUE TITLE
Screen freezes

### ISSUE THREAD

**Issue by bjaysgames** [TheGameCreators/GameGuruRepo#2792]
Screen freezes while editing in level.  Have to unplug to begin again.

**Comment by bjaysgames** [comment]
I'm using an HP computer with Windows 10.  When working in level 1 of the game I set up, the cursor begins to move jerkily and then stops.  I cannot do anything so I have to unplug the computer and reboot.  There is nothing more to tell you.  I have the older version of GameGuru which works perfectly well.
Hope you can help, and thanks again.

**Comment by ArgentArts** [comment]
For system specs, they might need a little more than that - what CPU, what GPU, who much system RAM? You have Windows 10 - is that the 64 bit version (I'm sure it is, but just checking). Your HP computer - is that a laptop or a desktop computer? Do you know if it's using an onboard GPU, like an Intel graphics chip or does it have a dedicated graphics card, like an Nvidia or AMD video card? Or perhaps both?

**Comment by dllllllllllb** [comment]
@bjaysgames We will need more information to help you. 
As ArgentArt said, it will be good to know your computer specs like your CPU, GPU and RAM. 
Send us your .log files that are located in C:\Users\*Your user name*\Documents\GameGuruApps\GameGuruMAX.
Was this issue happening with previous builds?
Does your screen freeze randomly or after you do something like adding an object into the scene?
Could you please take a video of what is happening.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
