### ISSUE TITLE
GameGuru MAX - Bug - Reflections Not Aligned and Smears

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2798]
If you look at this screen shot for Snowy Stroll, you can see that reflections don't align properly and there's still that bug with smearing:

![reflect](https://user-images.githubusercontent.com/36735507/162557455-e9efddcc-e545-49be-a242-06380f2dc3dc.png)

**Comment by PaulSJ** [comment]
@LeeBamberTGC Fix is on PJ-Branch11

**Comment by LeeBamberTGC** [comment]
@PaulSJ Also confirmed as fixed, will post to Experimental build later this evening :)

**Comment by ArgentArts** [comment]
This appears fixed in this evening's build. However, I noticed a glitch while playing the demo, Snowy Mountain Stroll, that did not appear when I went in to edit it and ran the test game. One of the reflective areas glitched when I played the demo from the MAX UI, but did not if I opened it to edit and ran it from there as a test game.

**Comment by PaulSJ** [comment]
@ArgentArts Unfortunately I can't see any issues playing Snowy Mountain from the hub, is it glitching in the same way as before or is this a new glitch?

**Comment by rvanner** [comment]
![image](https://user-images.githubusercontent.com/1503593/164189988-37fe1717-446e-4595-b0cd-34c14afd5077.png)

**Comment by ArgentArts** [comment]
@PaulSJ I'll try to catch a video later today. It's different. One of the puddles reacted as if there were two there ... like a Z-sorting error of some sort.

**Comment by ArgentArts** [comment]
The glitch did not show up on my second time through the demo level. So, I'm going to assume that my glitch was a glitch. ;) Ignore my previous post about this, though I will keep an eye out.

**Comment by ArgentArts** [comment]
All's good!
