### ISSUE TITLE
GameGuru MAX - Question - Why is Cursor Always Slammed Up to Top-Left When Playing Demos?

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2799]
Any time I play a demo game, once the first menu screen appears, my cursor jumps to the top-left. Is there a reason for this? This doesn't seem to happen with any other game I play (not that I recall). I have only a few other games installed at the moment. When I ran them, this did not happen to my mouse cursor.

**Comment by AmenMoses** [comment]
I presume it is because the mouse X,Y values default to 0 rather than 50 or to whatever the real position is in windows at that time.

**Comment by ArgentArts** [comment]
Perhaps, but I find it really disconcerting for some reason ...

**Comment by ArgentArts** [comment]
@dllllllllllb This is not just about the Save Standalone, but about any time the game is run, even in test game.
