### ISSUE TITLE
Specular Override no longer works on non-hand entities

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#28]
So I have my advanced time of day and weather system on the store and in PP it doesn't function to increase specularity to provide a wet effect.  It *DID* work on the hands though.  It was speculated (no pun intended) that it was because it only works on PBR assets now.  Any words on if this is true?

**Comment by LeeBamberTGC** [comment]
It appears the PBR shader could only apply its specular override if the original PBR gloss texture had a value (as it multiplied by it). I have changed this now so a specular value of 100 will not affect the PBR gloss and metalness values, but anything higher will add glossiness and metalness to the entity, and a value lower will subtract. Use this one carefully as it does BREAK the Physically Based Calculation and you can produce undesirable effects in some cases.  Fix will be in next PP March build.
