### ISSUE TITLE
Galaxy seed no longer works

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#280]
Galaxy seed no longer works and crashes GG in the process

**Comment by LeeBamberTGC** [comment]
I tried with the latest beta, and Galaxy Seed level loaded and ran fine (beta went up a few hours ago).

**Comment by korodai** [comment]
Changing the sky to Night has crashed Game Guru twice for me in the last week.

**Comment by synchromesh62** [comment]
Hmm im getting a lock and this message .
Failed to load shader' effectbank\galalaxy seed\galaxy_seed.fx.
All GameGuru shaders need to be HLSL Level 5.0 or above. 

I Tried just adding the Galaxy seed assets to a blank map with the same result ?
I will try a few more things :)

**Comment by plemsoft** [comment]
@synchromesh62
Just validate your installation on steam , and it will work , i think the problem is that "galaxy_seed.fx" is included in Rolfy's skybox pack and are overwriting the DX11 stock version ?, Try to validate and see if it works.

Each time you download from the store you will get the "not working" old DX9 version.

I dont have the skybox pack so i cant validate this myself.

**Comment by synchromesh62** [comment]
Ok all very strange for me but I think I got it ..
Validation did not work at first.
I had to manually delete Effectbank\galaxy seed ( which never returned on verify but cured the issue ) 
I then had to delete the lightmap folder from the galaxy seed map as it looks awful ( was the original lightmapped or did I somehow do it ) ?

Anyway all ok in the end … Thanks Guys :)

**Comment by Granada1** [comment]
Just ran it on the new beta and it ran ok,not so good looking as I remember I have the spinning ball but the sky is static,is that right I can’t remember about the sky

**Comment by synchromesh62** [comment]
The sky does not appear to be Galaxy seed on loading … I had to manually select it from the list.
Try that :)

**Comment by Granada1** [comment]
That sorted it thanks steady 60 FPS everything set to max,very happy

**Comment by Pirate-Myke** [comment]
I just loaded up the map (June 2018) file and ran it. The default sky was set to dark. I set it to Galaxy seed and the sky renders and has the spinning planets.
