### ISSUE TITLE
Project disappeared after update

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#2801]
Yesterday I was messing around in a sandbox project for a couple of hours, trying a few things out. I decided to take a break so I saved and closed the app. I noticed there was an immediate update being installed of a couple of GBs in size but I didn't see what it was. After my break I booted up the program again and noticed that everything I had worked on was gone. The entire project, map, and everything had been wiped. I checked the projectbank and mapbank folders and all they contain is the demo stuff. 

I posted this issue in the discussion and someone was nice enough to respond very quickly and asked that I report this here. Please let me know if you have any questions.

**Comment by dllllllllllb** [comment]
@tfrakey Can you please check the C:\Users\*YourName*\Documents\GameGuruApps folder and see if there are any backup folders in there.

**Comment by LeeBamberTGC** [comment]
@tfrakey Is this still an issue, or has it been fixed?

**Comment by ZakJudges** [comment]
Closing this issue due to lack of info. If the problem persists, feel free to reopen and we will take a look :) 
Was likely due to old auto-updater backing up folders and creating a new writable folder. We have since gone Steam only, and this problem should no longer occur.
