### ISSUE TITLE
Editor is very small

### ISSUE THREAD

**Issue by IceAxe18** [TheGameCreators/GameGuruRepo#2806]
Everything is so small

![20220409104442_1](https://user-images.githubusercontent.com/25734121/162585696-0523622a-cb33-44c9-9bf3-e3815b386625.jpg)

**Comment by Necrym59** [comment]
are you using a TV

**Comment by ArgentArts** [comment]
When sharing this sort of thing, it's helpful to provide additional information - what's the screen resolution? Is this a TV or a monitor? Etc. It helps the developers to know what's actually going on. Otherwise ... ?!?

**Comment by IceAxe18** [comment]
Alienware X17 Gaming Laptop
Nvidia Geforce RTX 3080 
Display settings is at 3840 x 2160

**Comment by ArgentArts** [comment]
Have you tried going to Edit>Settings and, once the pop-up menu appears, goin to the Advanced tab and checking/unchecking "Enable DPI Awareness" to see if that makes a difference for you?

![dpi](https://user-images.githubusercontent.com/36735507/162597249-386d3be0-186b-448e-8ef5-97668c0e15c8.png)

**Comment by IceAxe18** [comment]
I can barely see it, but its enabled.

**Comment by Necrym59** [comment]
3840 x 2160 pretty high dpi setting for a 17" laptop no wonder its small, why run it that high on a laptop?

**Comment by IceAxe18** [comment]
This is what my desktop looks like in 3840 x 2160:

![Desktop1](https://user-images.githubusercontent.com/25734121/162601713-7eb2e128-fd83-4a33-a390-23d87e89291a.jpg)

**Comment by Necrym59** [comment]
Hmm now that is weird, ive never had that problem with resolution wish i did cause i have an wide and i would like the space you have. I have this atrocity
![eeek](https://user-images.githubusercontent.com/95015657/162604441-88ccce0a-7e43-4d60-92d5-0e1c9711a985.png)

**Comment by synchromesh62** [comment]
Try ticking or unticking the **enable DPI awareness** checkbox In Settings \ Advanced 
See if that has any effect

**Comment by IceAxe18** [comment]
I unchecked "Enable DPI Awareness", and now it looks somewhat normal.

![20220410132032_1](https://user-images.githubusercontent.com/25734121/162638439-6f00e3be-7315-46e9-a58d-95cf64873250.jpg)

**Comment by dllllllllllb** [comment]
@IceAxe18 If you are not experiencing this issue anymore, please close the issue or let me know it's still happening and I will assign someone to look into this :]
