### ISSUE TITLE
04.08 update

### ISSUE THREAD

**Issue by MickeyBow** [TheGameCreators/GameGuruRepo#2807]
Problems so far: Update as find more
Well one of the fixes
A few users were not seeing weapons appearing when they pressed Play Game from the Hub. This should be fixed.
Still not fixed and also the text for using stuff is still mirrored.
The Patrol Rifle has no cross hair or aim point.

The Patrol Rifle and the AK when you have both all ammo goes to the AK you only have 30 bullets in the Rifle.
It also deleted bonus assets and booster pack.
Particle in the nine boxes for the particles is there supposed to be images of the particles or just boxes that say particle.

**Comment by dllllllllllb** [comment]
@MickeyBow There are existing threads for these issues, if there was a fix that didn't fix the issue, please report it in the appropriate issue thread. Also when submitting new bugs, please make a separate issue for each one, it helps us with organisation. 

Weapon not appearing issue: https://github.com/TheGameCreators/GameGuruRepo/issues/2405

Patrol Rifle is missing a crosshair file, I will take care of that.

Particle preview enhancements have been already reported.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Crosshair added for the next build. When it is public, please confirm fix and close, thanks!

**Comment by ZakJudges** [comment]
Crosshair present in latest build
