### ISSUE TITLE
snow tree spawn when not selected 

### ISSUE THREAD

**Issue by butch098** [TheGameCreators/GameGuruRepo#2808]
when using the tree spray tool , i select jungles themed trees and theres snow trees that spawn in without being selected

**Comment by dllllllllllb** [comment]
@butch098 I just tied it myself and it seems to work properly for me, I selected these trees: 
![image](https://user-images.githubusercontent.com/61796872/162701077-2a73bcd6-5d9f-44a2-b525-5f9bff61c9e1.png)

Can you please show me which trees you have selected that cause this issue.

**Comment by butch098** [comment]
Sure here  Envoyé à partir de Courrier pour Windows De : MaciekEnvoyé le :lundi 11 avril 2022 10:55À : TheGameCreators/GameGuruRepoCc : butch098; MentionObjet :Re: [TheGameCreators/GameGuruRepo] snow tree spawn when not selected (Issue ***@***.*** I just tied it myself and it seems to work properly for me, I selected these trees:Can you please show me which trees you have selected that cause this issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by DaveTGC2** [comment]
I've spoken to the original poster, and I can confirm that this is still an issue. I replicated it using jungle trees. I've also noted randomly spawning cacti.

**Comment by butch098** [comment]
these are the trees i use

**Comment by davetgc** [comment]
I've confirmed the snow tree issue:

https://user-images.githubusercontent.com/99803873/166873495-e03766e3-d10c-4d61-b394-1679cd07672d.mp4

**Comment by butch098** [comment]
It is fixed , thank you very much ! great work  Envoyé à partir de Courrier pour Windows De : ZakJudgesEnvoyé le :lundi 23 mai 2022 10:27À : TheGameCreators/GameGuruRepoCc : butch098; MentionObjet :Re: [TheGameCreators/GameGuruRepo] snow tree spawn when not selected (Issue #2808) Hi @butch098, this bug should now be fixed. Could you confirm that is the case after downloading the latest update? Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ZakJudges** [comment]
Thanks for confirming, closing this issue

**Comment by butch098** [comment]
Np  Envoyé à partir de Courrier pour Windows De : ZakJudgesEnvoyé le :lundi 23 mai 2022 11:52À : TheGameCreators/GameGuruRepoCc : butch098; MentionObjet :Re: [TheGameCreators/GameGuruRepo] snow tree spawn when not selected (Issue #2808) Thanks for confirming, closing this issue—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
