### ISSUE TITLE
SetAmbienceIntensity  and fogzoneintensity do not seem to work

### ISSUE THREAD

**Issue by UNIRD12B** [TheGameCreators/GameGuruRepo#2809]
I cant seem to use either of these in a script any more...no response.
UNIRD12B

ex.. code..

local change_amount = {}
local plyr_in_zone = {}
function fogzoneintensity_init_name(e,name)
change_amount[e] = tonumber(name)
plyr_in_zone[e] = 0
end
    
function fogzoneintensity_main(e)
 if g_Entity[e]['plrinzone']==1 then
  if plyr_in_zone[e] == 0 then
  SetFogIntensity(change_amount[e]) 
  SetFogDistance(change_amount[e])
  ActivateIfUsed(e)
  plyr_in_zone[e] = 1 
end
else
plyr_in_zone[e] = 0
 end
end

**Comment by Necrym59** [comment]
Its been reported already none of the environment Set commands are available the moment, thay are not exposed to lua

**Comment by LeeBamberTGC** [comment]
@UNIRD12B Fog can be controlled in latest version:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/98f41b6a-adb9-4ce9-b100-6885aea9a261)
Changed the code to see it:
local change_amount = {}
local plyr_in_zone = {}

function fogger_init_name(e,name)
	change_amount[e] = tonumber(name)
	plyr_in_zone[e] = 0
end

function fogger_main(e)
	if g_Entity[e]['plrinzone']==1 then
		if plyr_in_zone[e] == 0 then
			SetFogIntensity(0.5)
			SetFogNearest(change_amount[e]-1000)
			SetFogDistance(change_amount[e])
			ActivateIfUsed(e)
			plyr_in_zone[e] = 1
		end
	else
		plyr_in_zone[e] = 0
	end
end

**Comment by Necrym59** [comment]
This was working and there was a fog script in the core somewhere

**Comment by UNIRD12B** [comment]
ThxI'll try it.Unird12bOn Oct. 13, 2023 5:11 p.m., Steve ***@***.***> wrote:
This was working and there was a fog script in the core somewhere
