### ISSUE TITLE
02-07-18 BETA

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#281]
Hi  well done on the progress so far  just a couple of things I need someone else to confirm but I have a couple of issues when LM PBR assets

1. some assets jump out of there Collison boxes which also causes drastic frame drops 
2. not sure if its my models but not all collision boxes are showing with the debug slider 
3. it breaks transparency on some models 

I can confirm all texture maps are now visible after LM 
https://youtu.be/p0E6PnJrEgM

**Comment by Pirate-Myke** [comment]
Here is a link to what I posted in the bug report thread in the main forums.
https://forum.game-guru.com/thread/219834#msg2602664

https://youtu.be/D7pqgQHZZUo

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this,

Looks like that rotation problem we had way back , i think this was fixed , could you confirm , Thanks :)

**Comment by plemsoft** [comment]
This was fixed in a previous update.
