### ISSUE TITLE
Enemy disappearing

### ISSUE THREAD

**Issue by bjaysgames** [TheGameCreators/GameGuruRepo#2811]
How do I keep an enemy from disappearing after he is killed?

**Comment by dllllllllllb** [comment]
@bjaysgames Enemies usually fall to the ground and lay there. They don't disappear even after a while or if I wonder off far away from them. Can you please provide more information.

**Comment by ZakJudges** [comment]
Closing due to lack of response. If the problem persists, feel free to reopen and we can take a look. Thanks
