### ISSUE TITLE
Bug in GGMax - LUA script error when playing Canyon Offensive

### ISSUE THREAD

**Issue by SquireOfGothos** [TheGameCreators/GameGuruRepo#2812]
I'm using GG Max Build No. 2022.04.08 and noticed the following LUA error pop up when playing the latest demo Canyon Offensive (very good by the way):

.\scriptbank\vectlib.lua:40: attempt to index local 'v' (a nil value)

It occurred after using the switch to open the bunker door which did not open.  However, after this the the demo still seemed to be running.  This does not happen every time, the first time I played this demo the door in the image opened without a LUA error.  Also, have not been able to reproduce on replaying the demo, so this probably makes this a very difficult issue to find.
 
![CanyonOffensiveLUAError](https://user-images.githubusercontent.com/15776865/162610113-dae0d8de-1b10-414f-acc7-62a70658d84e.jpg)

**Comment by Ghost-l0l** [comment]
@SquireOfGothos "Canyon Offensive (very good by the way)" :D Big thank you! :D  (this bug never happend to me tho)

**Comment by AmenMoses** [comment]
Weird one, can you think of anything strange that you may have done prior to the error occurring, like taking a shortcut for example?

I have tried to replicate it and haven't done so yet.

**Comment by SquireOfGothos** [comment]
I don't remember taking any shortcut. The only oddity I did notice, and 
this is not unique to Canyon Offensive, is that an enemy walked through the 
closed door of the bunker to shoot at me. I've had enemy firing at me 
through walls and able to kill them in other demos. When they die they fall 
through walls. I suspect that's a GGMax engine issue though, as is dead 
enemy floating. Whether this had something to do with the LUA error I don't 
know. I suspect it's not an issue with your game though, but possibly with 
GGMax engine and difficult to find!

Regards
Ray

**Comment by SquireOfGothos** [comment]
Played again and I still can't reproduce the problem so no idea why it happened.  Guess we can sign this one off as an oddity.
