### ISSUE TITLE
GG Max - Bug - Ally Hostage Character can run straight through locked door.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2815]
I am using a Building - Door Light Brown door, along with along with a Shanty Building - Old Large.
I Had to adjust the door size to fit the door.
I then place a ALLY Character inside the locked building, He is a hostage.
But the ALLY character runs straight through this door, even when it is locked.

Even changing the character to enemy, he can still run straight through this locked door.
My own character can not get through the door, and the door works fine, Unlocks when i get the key, and opens fine.

The 1st image is as he ran up to door, the 2nd image is after i moved further back and he ran through the door.
And the 3rd image, is the exact same door, but on the outer part of the same building, and as you can see the character can not run through this door. So only the inner door causing the problem.

![image](https://user-images.githubusercontent.com/66874403/162620122-a25adf72-4a73-4270-b65f-25cf390fa1b4.png)

![image](https://user-images.githubusercontent.com/66874403/162620155-437bd8b7-c5de-4666-9dc2-fa07bcc3fde9.png)

![image](https://user-images.githubusercontent.com/66874403/162620220-f57901b9-a55d-470d-89b1-23fe610d0f4f.png)

**Comment by Tum1370** [comment]
Sorry, i have figure this problem out, It seems that when the base of this building is slightly below the ground, it was causing my issue. Not sure why this would allow the character to walk through the door though.

**Comment by Tum1370** [comment]
I think i have this fixed for now, But it will keep resetting when i update Max again.
I Have changed 20 in the following DOOR.LUA text to 50.

RDBlockNavMesh(g_Entity[e]['x'],g_Entity[e]['y'],g_Entity[e]['z'],20,blockmode)

Now the Ally Hostage does not walk through the door.

**Comment by Necrym59** [comment]
Copy the edited door lua into your own scriptbank folder usually Documents\GameGuruApps\GameGuruMAX\Files\scriptbank
then rename it eg: 'my_door.lua' and change the function names inside the lua from door_init(e) to my_door_init(e) and 
door_main(e) to my_door_main(e). Then you have your own script that wont be overwritten every update.

**Comment by Necrym59** [comment]
Doors always seem to be a bit of a problem. Pehaps a collision box should be created when a door is closed or around the door itself when opened.

**Comment by Tum1370** [comment]
@Necrym59 
Hi, I guess i have to also change the following procedure to "function my_door_properties(e, range, delay, unlocked, lockedtext)"

function door_properties(e, range, delay, unlocked, lockedtext)

I will start to learn LUA for myself soon, but at the minute i have only just started with Gameguru Max, I never used normal gameguru before.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Has the DOOR lua changed on the latest update ? I use to change the navmesh from 20 block to 50 block which fixed this issue, But i cannot find the navmesh section now in the door lua

**Comment by LeeBamberTGC** [comment]
@Tum1370 Door script changed further in latest EXP build now uploaded.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Thanks, Just tested the latest EXP build, Was working fine on my level were my hostage was running through doors.
Ill close this issue now.
