### ISSUE TITLE
Kit's Features and Thoughts

### ISSUE THREAD

**Issue by KitBallard64** [TheGameCreators/GameGuruRepo#2817]
Was directed to post this here from Steam, so I'll mostly just copy that over to here
-------------------------------------------------------------------------------------------------
There's a few things I would love to see at some point. This is a pretty good start for sure, and I don't know what's planned in general, but a couple ideas I would love to see are things like:

Ways to configure some of the behavior systems that doesn't have editable options (like weapons, since it seems all weapons feel similar in damage, in a sense). Edit: Now I'm thinking about it, might of been in the dev tools and I just forgot.

Ability to add more than 1 behavior to an Object. (Though this may come with the "Rpg" or "Puzzle" Update, now I'm thinking of it)

Kind of ties into the previous one: A timer for triggers, to add a delay to fire an event. (again, might be with the different modes coming later)

A way to import a FBX Character as well, a character (Like Enemy/Allie)

A bit more information on how the app handles and imports animations. As far as I know of it uses animations in a FBX. Maybe a way to import or set an animation (Say I use 3 different types of characters with the same bones I could just add it to their animation tree).

More First Person editable options, such as HUD editing, arm models, and weapons.

Kinda known and I'm 100% sure this is planned but course importable weapons (and not just pew pews)

Some Documentation of how you handle your LUA. I highly doubt I would make my own, but I'm sure some assistance for others to know your call systems be nice.

More options to the Visual Logic. At the moment, you can only tell som'in to turn on or off, or make an NPC to goto a place or not. New options such as turning a collider on/off, turning gravity on/off, disabling the object as a whole (good for goofy drop traps or scares. I have a sliding door as a work around for now)

Maybe have a trigger system follow an object. Like "rig" it to something. Can make a droppable damage zone on a pallet and if it hits you, you take damage. (And make it only trigger once, or have a way to turn itself off)

You already know my thoughts on how confusing it was on the readability of where Visual Logic is, so I won't get back into that.

These are just a few off the top of my head. The options we have, and seeing how well put together this is already and look forward to seeing more to this. of course, I'm not expecting anything written here and hell, I don't mind none of this being added. I just thinking out loud more than anything. I honestly appreciate what we do have and am interested to see where this leads in the future, specially with it's upcoming extra logic systems of RPG and Puzzle. I'm sure a lot of this is already in the planning or development stages and not really looking for an answer~♪ I hope you guys have a good day and keep it cool!
---------------------------------------------------------------------------------------------

Like I said in the post, I'm sure a lot of that's already planned and in the works, as some of my wishes kind of crosses paths with ideas that RPG or Puzzle could do.

I'll also forward this from a reply, as it has a few fun ideas also:
`[Диджей Кот]
Some of my ideas:
- More AI settings (e.g. aim, awareness or stealth, fire rate, etc.)
- More weapons (e.g. sniper rifle, smg, etc.)
- Editable screens and hud
- More environments to generate (suburbs, city, etc.)
- Urban and town models
- Stealth (hiding, takedowns, etc.)
- Weapon attachments (laser, suppressor, scopes/sights, etc.)
- Cutscenes and more in-depth triggers`

I personally like the City generation idea. Simple buildings that don't need to generate indoor options can keep the engine cleaner to generate.

Either way, I can't wait to see where this goes in the future. Take care ya'll~

Kito

edit: Not sure why 2 parts of this is bolded, but sorry if it sticks out too much ^_^¿

**Comment by ArgentArts** [comment]
The devs like it if you post each feature request and bug as a separate topic/thread here on GitHub. That way it's easier to track them. When it's a big, long list like this, it's easy for things to get lost or forgotten. 

Personally, I don't think you'd want to add more than one Behavior to an object as that is inviting all sorts of conflicts that could occur. What you'd want is to have specific Behaviors created to do what you need done. 

> More weapons (e.g. sniper rifle, smg, etc.)

The Patrol weapon is a sniper rifle. The AK47 (Assault Rifle) is an SMG.

> Editable screens and hud

Screens are editable, TGC says a HUD editor is planned.

> Weapon attachments (laser, suppressor, scopes/sights, etc.)

The Patrol weapon has a scope/sites. Use the RMB to use the smaller scope and "V" to switch to the further sighting scope.

> Cutscenes and more in-depth triggers`

TGC has stated that cutscenes are not planned for MAX, but there is an inexpensive product you can purchase (made by some MAX users) called CineGuru you can use to make cutscenes. 

More in-depth triggers can be created yourself by using the visual logic system MAX provides or by using the linking system. You just have to play around with the tools MAX has provided you.

> A way to import a FBX Character as well, a character (Like Enemy/Allie)

A guide for exactly how to do this is in the works and will be released eventually. MAX is in Early Access and these things are planned.

**Comment by KitBallard64** [comment]
More behaviors would help to let objects do multiple things. Don't see why it can't be done as other systems I've goofed with has such systems in place already. And there are checks to prevent overlaps or conflicts that can be scripted into the app itself. Like, adding an Ai will prevent any extra behaviors to be added (or ones that wouldn't work with it).

Most of those you quoted was from someone else's post. I just didn't want to trim it up to remove most of their wishes. I personally agreed with the city generator part.

I'm sure the FBX Character importer is on it's way as a proper thing.

This was more of a "my first impressions" post from steam and one of the devs told me to post it here. As stated from my copied post, I'm sure most of it's already in the planning. I'm not expecting anything here to be added, but most ideas would help out with my own thoughts on what I'd like to throw into stuff.

**Comment by ArgentArts** [comment]
Well, this is GitHub. The purpose here is to help the developers to, well, develop their software. In order for them to do that, it's best to post each suggestion, feature request, and bug as a separate issue. That way they can track it individually. It makes it easier on them and it also ensures they see each and every one. It's for everyone's best interest. :)

**Comment by dllllllllllb** [comment]
@KitBallard64 Please post each request as a separate issue, that way we can assign each request to the appropriate member of the team and track which request has been fulfilled.
