### ISSUE TITLE
Stand and Speak or Get Close and Speak not working correctly

### ISSUE THREAD

**Issue by LostSoul54** [TheGameCreators/GameGuruRepo#2818]
Stand and Speak or Get Close and Speak not working correctly using recorded voice over from editor window. Sounds play correctly in editor and will work the first time entering the game, It will not work on an subsequent tests of the level. It will work again after restarting the application. It will randomly choose another sound after this starts working again. Will not always play the sound that is set

**Comment by dllllllllllb** [comment]
@LostSoul54 It works perfectly fine on my end. Can you please make sure that the "Use Sound Variants" box is ticked off. 
![image](https://user-images.githubusercontent.com/61796872/162696275-4c7bf45d-f003-48a9-8be4-ad35c26894b1.png)

If it still doesn't work, can you please delete the GameGuruMAX\Max\Files\scriptbank folder and redownload it.

**Comment by mike123yy** [comment]
I have the same issue and I tried your suggestions. I unchecked the sound variance box and then deleted the script bank folder and had steam verify the files to reinstall what was missing. Still not working though. The patrol and speak doesn't work either.

**Comment by mike123yy** [comment]
I seem to have found a solution, at least in my problem with it not working. It refuses to work if the NPC is set to neutral. You have to set him to enemy to activate the dialogue.

**Comment by LostSoul54** [comment]
Confirmed it must be set to Enemy. Ally or Neutral not working. This needs to be fixed

**Comment by ZakJudges** [comment]
Fixed as part of work on #3555
