### ISSUE TITLE
GameGuru MAX - Question - Is Max NOT Getting SSAO?

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#2819]
I noticed in a March update Q&A, Lee stated there are no plans to add SSAO to Max, despite it having been implemented a few years ago into Classic.

With Max only having dynamic lights to cast shadowing, SSAO seemed like **_essential_** tech, I just assumed was on the way at some point in the future as a given. 

I've noticed the visuals for Max are still a bit lackluster (particularly outdoors), scenes still look a bit "flat", and I had assumed that when SSAO (or some similar derivative) was implemented, it would finish bringing everything together and that would be the end of it. But reading this statement from March was VERY disheartening, so I just wanted to know if there was anymore details about this at the moment?

**Comment by LeeBamberTGC** [comment]
We have SSAO, but I refer MSAO :)  In this Friday's release!

Before:
![image](https://user-images.githubusercontent.com/35840583/164560818-efac15af-3475-4140-8b92-896cbafad787.png)

After:
![image](https://user-images.githubusercontent.com/35840583/164560827-20991aa7-f7ad-4700-8a95-3ed9064c9c7d.png)
