### ISSUE TITLE
Question: Is GameGuru MAX supported on laptop?

### ISSUE THREAD

**Issue by blackbone17** [TheGameCreators/GameGuruRepo#2823]
I have a Victus - AMD Ryzen 7 5800H - 16GB RAM - RTX 3050 4GB VRAM and I was wondering if it could work properly, and also how much big of a map you can create. Thanks in advance.

**Comment by LeeBamberTGC** [comment]
Yes, any laptop that meets our minimum specifications here: https://www.game-guru.com/about?_ga=2.26553594.637122419.1649674225-1982497974.1625668666
