### ISSUE TITLE
Every time I save the game the software crashes ?!!

### ISSUE THREAD

**Issue by gamesambassador** [TheGameCreators/GameGuruRepo#2829]
Every time I save the game the software crashes and I uninstalled the software and re-installed it again and nothing changed, and  I have also tried to verify integrity software files and The problem has not been resolved, Can you help me please, thank you

**Comment by dllllllllllb** [comment]
Hi @gamesambassador , can you please post your computer specs, CPU, GPU, GPU driver version, RAM and OS. 

Also in the C:\Users\*Your used name*\Documents\GameGuruApps\GameGuruMAX there should be two .log files, please post them below as well. 

Does the software crash when you try to save a empty level? Are you using custom assets in your level? The more information you can provide the better :] Thanks!

**Comment by gamesambassador** [comment]
hi You mentioned Do I use custom assets in my  level , yes ,  I copied Game Guru Classic assets to Max , Is that a problem .

**Comment by gamesambassador** [comment]
hi  Yes, this was  the problem and when I removed the assets it did not crash, Problem solved, thank you for your help
