### ISSUE TITLE
GameGuru MAX - Bug - Custom Save Location on Import Object Request MAX Restart

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2830]
MAX allows the end-user to save imported 3D objects to their own custom folders. This is great. However, if you select anything other than the default \use folder, then after importing nothing will show in the Add menu, neither the 3D model nor the newly created folder. In order to get both to show up, you have to exit out of MAX and restart.

**Comment by davetgc** [comment]
@ZakJudges - I'm also pushing this one as another one that's hitting artist productivity.  Thanks.

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, I have uploaded a new EXP with a fix for this, ready to test :)

I also updated the directory that the folder selector starts in when you change the path, so that it starts in your writable folder.

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges So far, this seems really great. It saves a lot of time defaulting to the user area rather than the Steam area. Thanks for that.
