### ISSUE TITLE
User reporting: RUNTIME ERROR: 0 : D3D11CREATEDEVICEANDSWAPCHAIN = E_INVALIDARG ()

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2834]
@PaulSJ Do you have a clue why the user would see such an error?

See report on Steam here;
https://steamcommunity.com/app/266310/discussions/0/3282569790362975004/

**Comment by rvanner** [comment]
@PaulSJ Stand down, this is a Classic bug! @plemsoft Can you reply on this when you are back please?

**Comment by plemsoft** [comment]
@rvanner User fixed it by validating files.
