### ISSUE TITLE
Turning off Drag/Drop Entity Mode also Turns off the Outlines for Selected Entites

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2843]
If you turn off Drag/Drop Entity mode under the Developer tab it will turn off the Outline on Selected Entities. Even if Use Outline for Selected Editor Objects option is turned on.

**Comment by LeeBamberTGC** [comment]
@rvanner Should remove the option to switch off the drag/drop entity mode, it is all we use now, and OFF just supports really old code now.

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Well alot of times when I select an entity the Widget does not pop up, it feels like the engine thinks I want to use drag mode on the entity or something and I am forced to click the entity again and again before I can finally get the widget to appear (sometimes this can even slightly move my entity when I don't want it to).
But turning off drag/drop mode always makes the widget appear when I select an entity. Which I would prefer.  Maybe this is a bug where the widget should always appear on mouse click? I'm not really sure.
