### ISSUE TITLE
Ensure die when fall from great height

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#2846]
Right now the player with 500 health survives this with only 150 points lost:

![image](https://user-images.githubusercontent.com/35840583/163430453-0aa8832d-db7e-463f-8f22-1d722e97f7c8.png)

Set for more damage by default!

**Comment by ZakJudges** [comment]
@LeeBamberTGC Added in a fall damage multiplier set to 4 by default which causes 506 damage when falling from the Aztec temple

**Comment by ZakJudges** [comment]
@LeeBamberTGC Whilst you are on the Aztec kit, would you be able to confirm this fix works for you? :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Happy with this now, jumping 400 units down with 400 health will kill the player :)
