### ISSUE TITLE
02-07-18 Beta : Global Sound at start (map editor)

### ISSUE THREAD

**Issue by demented-mind** [TheGameCreators/GameGuruRepo#285]
This is not a game stopper. I load a global sound at the very beginning of the level. When I load the level for the very first time there will be an error message generated indicating the file is not found. I believe the script tries to play that sound before it is actually loaded and can't find it. So when the level is rel-loaded it will be OK because it is loaded and apparently saved. 

This has been troublesome for that past several betas and before the first PP, so it's not an issue with the current beta, that's just what I am running at the moment.

**Comment by plemsoft** [comment]
@demented-mind Thanks for reporting this,

> so it's not an issue with the current beta

So the issues has been fixed in the latest beta ?

If not could you sent me a fpm and script that show this issues , thanks :)
