### ISSUE TITLE
GameGuru MAX - Bug - Unable to Change Button Appearance for Graphic Settings Buttons

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2851]
Currently, we are unable to change the button appearance for the Low, Medium, and High buttons for Graphic Settings. If you click the Back button, the controls appear to change the button appearance:

![graphics1](https://user-images.githubusercontent.com/36735507/163454450-0cb79436-a961-4679-9d86-cbeb8565ec1b.png)

But if you click on any of the graphic setting buttons, these controls disappear:

![graphics2](https://user-images.githubusercontent.com/36735507/163454502-a0441bee-1d6b-4cdd-981d-49c9bb2bb0fd.png)

This means that we cannot set the appearance for these buttons and, as such, they stand out like a sore thumb if we've used custom buttons for all the other buttons on our screens.

**Comment by DarthPickles666** [comment]
I can provide a perfect example of this looking completely odd. 
![image](https://user-images.githubusercontent.com/101579658/163454825-76f409e6-a6d2-4ffb-b76d-8074774b7b39.png)
![unknown](https://user-images.githubusercontent.com/101579658/163454871-8f1d3767-e8ad-4294-a1da-8bc4df0bc631.png)

**Comment by plemsoft** [comment]
@ArgentArts This has been fixed and will be in the next update :)

**Comment by ArgentArts** [comment]
Confirmed!
