### ISSUE TITLE
GG Max - Bug - Standalone Character Created Enemies Had Black Trousers instead of Camo Trousers

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2853]
As the title says, I have just tested doing a Standalone of a level, And i had 2 Character Created Guards, Both had full camo gear, including trousers and hats.
In the editor they are working fine, 
On Standalone they all had Black Trousers, and Black hats.

**Comment by rvanner** [comment]
@Tum1370 Can you please paste images of them before and after? It will help identify the issue. Thanks

**Comment by Tum1370** [comment]
I’ll redo this and post mages when home from work later.

**Comment by Tum1370** [comment]
OK in the first image, i have tested the single level, and you can see the characters all have Camo trousers
on the second image, this is a Standalone, and you can see all characters trousers are Black.

![Camo Trousers](https://user-images.githubusercontent.com/66874403/163558574-87b2ac56-003e-4bc9-8b68-a357e63825f3.png)

![Black Trousers](https://user-images.githubusercontent.com/66874403/163558582-9dd60033-f85e-4397-a1c9-d0591dd69d79.png)

**Comment by Tum1370** [comment]
Here is a simple one to see that i made. First image is on Standalone game, And the guards have black trousers.
Second image is TEST PLAY from editor, they all have camo trousers like they are suppose to.

![image](https://user-images.githubusercontent.com/66874403/163591794-6eedab76-a423-4cf1-97db-2d995444b63a.png)

![image](https://user-images.githubusercontent.com/66874403/163591916-07f446b0-2e16-4825-901b-7741c6fbe947.png)

**Comment by Tum1370** [comment]
After playing my standalone level, I also noticed that a different character creator character also had black trousers, but also had black arms, It is like there are missing materials when creating a standalone.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed an will be in the next update :)

**Comment by Tum1370** [comment]
@plemsoft 
Hi, Sorry to say but this is not fixed in todays update.
Quick test of a standalone was still showing Black hat and trousers, instead of camo trousers.
I guess the other texture issues will be still here as well.

![image](https://user-images.githubusercontent.com/66874403/164747008-64e0ad11-c220-4e33-81af-0db7e226e787.png)

**Comment by Tum1370** [comment]
@plemsoft 
Here is a easier screenshot to see them.
All trouser and head camo gear is really dark, And the other 2 characters have other problems, with like skin, and hair etc.
Seems the character created models are not saving properly still in Standalone.

The first image is Standalone.
The second image is playing from editor, and how they are suppose to look.

![image](https://user-images.githubusercontent.com/66874403/164757273-070cd014-88f3-48df-95ef-bfc7a6e813f8.png)

![image](https://user-images.githubusercontent.com/66874403/164757541-b5352186-4e48-4d89-8b8c-7e80bb75d552.png)

**Comment by plemsoft** [comment]
@Tum1370 Please make sure your using the 2022.04.22 version , and you also need to export the standalone again before it will work :)

**Comment by Tum1370** [comment]
@plemsoft 
I am using latest version, It doesnt work

**Comment by Tum1370** [comment]
@plemsoft 
For me, this build on the 22/4/22 has been a terrible release.
I had to spend 8 hours on Friday night fixing a messed up AI system on a level i had finished, (Which was working fine before the update)
I was so hoping the Standalones was fixed and after Fridays download, so i could let my friend try a level, but still the character creators characters had black trousers and messed up textures.
And now today, i am stopping my new level due to problems with smart placements.

**Comment by plemsoft** [comment]
@Tum1370 could you try to show me all the files in this folder:
\Users\USERNAME\Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user\charactercreatorplus\
And also show me all the files in the same standalone folder "\Files\entitybank\user\charactercreatorplus\" so im able to see the difference , Thanks :)

**Comment by Tum1370** [comment]
On a level, i have placed 4 character created characters in a area near a winzone helicopter, I am now creating the standalone and will Zip it and send it to you, Hopefully this will have the GAME OVER bug and the character black trousers etc bug.

**Comment by plemsoft** [comment]
@Tum1370 Thanks , could you also zip this folder "\Users\USERNAME\Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user\charactercreatorplus" so i can see what textures is missing, Thanks for your help :)

**Comment by Tum1370** [comment]
@plemsoft I think i have already tried copying those entire files from that folder to the standalone folder, but it still has the problems with black textures.
I have just created the Standalone, I have added 4 character created characters so you can see the problems with the characters, 
The GAME WON bug though does not seem to be happening with this standalone though, But at least you can see the black trousers / hats /skin colouring bug.

**Comment by Tum1370** [comment]
@plemsoft 
The Standalone ZIP is to big to send as a email.
I will place it in Dropbox and send you a link.

**Comment by Tum1370** [comment]
@plemsoft 
I have sent you the email with the Standalone and that folder.
They are dropbox links 

Thanks

**Comment by Tum1370** [comment]
@plemsoft 

This is what the 4 characters in the Standalone ZIP that i just sent you, look like for me. 

![image](https://user-images.githubusercontent.com/66874403/164970556-8b43e799-a9c4-47f3-a4eb-697668c54bb0.png)

**Comment by Tum1370** [comment]
@plemsoft 
Did you receive the ZIP with the Standalone in ?
Was the missing textures or black trousers happen for you as well on the standalone ?

**Comment by plemsoft** [comment]
@Tum1370 Yes got them will have a look :)

**Comment by plemsoft** [comment]
@Tum1370 Thanks for the files, i found the problem it was the surface and normal not getting into the standalone depending on skin colors. This has also been fixed and will be in the next update :)

For now you can copy these files to your standalone by hand:
\Files\charactercreatorplus\parts\adult male\adult male facialhair 04_surface.dds
\Files\charactercreatorplus\parts\adult male\adult male legs 12_surface.dds
\Files\charactercreatorplus\parts\adult male\adult male legs 12_normal.dds
\Files\charactercreatorplus\parts\adult male\adult male headgear 08_surface.dds
\Files\charactercreatorplus\parts\adult male\adult male headgear 08_normal.dds
\Files\charactercreatorplus\parts\adult male\adult male hair 11_surface.dds
\Files\charactercreatorplus\parts\adult male\adult male body 03_normal.dds
\Files\charactercreatorplus\parts\adult male\adult male body 03_surface.dds

**Comment by Tum1370** [comment]
@plemsoft 
Ok thanks, I will try this when home. 
I am sure I did try copying the entire adult male folder in to stand-alone folder before. 

Maybe wheb I copied before I placed them in wrong folder.

**Comment by plemsoft** [comment]
@Tum1370 Could you try this in the latest EXP build and close this issue if its fixed for you , Thanks :)

**Comment by Tum1370** [comment]
@plemsoft 
Just created a quick test again on the experimental build.
On a standalone game, the character created characters were all looking fine now.
Thanks, I will close this one now.
