### ISSUE TITLE
GG Max - triggerzone invisible under water, but visible again when you're also underwater

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#2859]
Canyon Offensive demo got whole big area with water to knee level, and there's few triggers there that most users will probably never see because of this bug: https://youtu.be/fpSpDva5rJA

**Comment by ThomasJowett** [comment]
This issue is a duplicate of #1540 . All transparent objects are not rendered under the ocean.

**Comment by PaulSJ** [comment]
Duplicate of #1540
