### ISSUE TITLE
GG Max - Standalone - Icon - Even after changing icon to a 256x256 png Standalone ICON is still Max icon

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2864]
As the title says, Changing the ICON of the Standalone does not change the ICON from the standard Max icon.

**Comment by Necrym59** [comment]
so..why and how are you changing an icon on an unfinished gaming product?

**Comment by Tum1370** [comment]
To TEST how it works. 
And it did NOT work.

**Comment by Necrym59** [comment]
Well it wont work until they enable it

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been added for the next update :)

**Comment by plemsoft** [comment]
@Tum1370 Here is a video about how to change it: https://drive.google.com/file/d/148qjKrHq_LI0Q2Qu0qxCOoDdtKtp82qh/view?usp=sharing

FYI: You MUST select another icon (even if its the same, conversion has changed) or it will not work , give it another try :)

**Comment by Tum1370** [comment]
@plemsoft 
This is the problem. I did exactly what you have done in the video. 
I selected the icon, a 256x256 png. 
Then after creating Stand-alone it is still the game guru icon. 

I tested this on last nights experimental build. 
Does not change the icon for me.

**Comment by synchromesh62** [comment]
Tried this just now after reading this ..
Worked fine for me just using my Avatar.png file.

![ICON](https://user-images.githubusercontent.com/35708217/166666696-4b3df688-1dad-425e-9ff1-52fa3afe8e1c.png)

**Comment by Tum1370** [comment]
As soon as am home from work I’ll do a video of this. Definitely wasn’t working for me last night.

**Comment by Tum1370** [comment]
@plemsoft @synchromesh62 
Sorry guys, my mistake.
This time, i re selected the same icon, and after creating standalone the icon was on the EXE file.
Thanks, I will close this issue now.
