### ISSUE TITLE
GG Max - WinZone - Loading Next Level before audio finished playing

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2865]
I have a Winzone when you get to a helicopter, THe Winzone plays the Audio "Its about time, lets get out of here"
But if you create a standalone, then play the game, and when you get to the Winzone, The next level starts to load before the audio message has finished playing.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Code added to WINZONE behaviour to play the sound completely before triggering the level change/game win:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/41158b27-3a49-4b83-a5a3-5984399acec8)
