### ISSUE TITLE
GG Max - Bug - Saving Group - Does not work

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2871]
I know groups are really buggy presently, but i just tried creating a barrel, had a fire particle in it, and 4 pieces of plywood, one had fire sound in it.
The group saved, but the image did not save, So the object library is just a blank image for the item.
Then after trying to place the object, nothing was placing. The group had not saved properly.

**Comment by Tum1370** [comment]
After testing groups for a while tonight, I can create the group of many objects, like tent, trees, shrubs, characters and flags.
I cannot save this group, that is always buggy.
But i can place the group, while the items are grouped.
But it seems you have to be very careful on what you do with groups else what you place, moves, and messes up.

They really do need a lot of work to be really good.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Issue duplication, this should be fixed in the next EXP build:
![image](https://user-images.githubusercontent.com/35840583/229366041-779d04bf-b4bd-4ec4-a755-22359be77ccb.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC Just tested this group bug, Put a barrel down, 4 planks, and a particle with fire smoke, All grouped properly, and placed properly when i used the grouped object.
Ill close this issue as fixed.
Thanks
