### ISSUE TITLE
Gameguru CLASSIC   ----   Water doesnt reflect decals or transparent objects.

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#2872]
Can this be fixed please?

Thank you

**Comment by Duchenkuke** [comment]
awesome!

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Not uploaded the new beta yet, still coding :)

**Comment by Duchenkuke** [comment]
kk :)

**Comment by LeeBamberTGC** [comment]
@Duchenkuke New BETA and PUBLICPREVIEW builds now uploaded. Hopefully all will be well and you can close a few issues down :)

**Comment by Duchenkuke** [comment]
awesome! What is it called on steam in the betas tab ? just "publicpreview" ?

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Available now with the BETA build or the PUBLICPREVIEW (no password required on the PP)

**Comment by Duchenkuke** [comment]
confirmed as fixed.
