### ISSUE TITLE
Moving Buildings

### ISSUE THREAD

**Issue by realPrunelle** [TheGameCreators/GameGuruRepo#2875]
GGMax: When I save my game, sometimes any Building is moving. Not far, just 1 meter or something like this.
I'm not be able to reproduce it. Sometimes it happens, sometimes not. So I'm not be able to find the reason.

It is a general problem. Not just one map.

**Comment by plemsoft** [comment]
@realPrunelle There was a fix in the latest version , please try to update and let me know if this issue has been fixed, Thanks for your help :)

**Comment by realPrunelle** [comment]
Hey @LeeBamberTGC ,

this issue here? It seems to be fixed at the moment.
