### ISSUE TITLE
GameGuru Max crashes

### ISSUE THREAD

**Issue by Indidev234** [TheGameCreators/GameGuruRepo#2877]
Hello, please, how to fix the problem of Game Guru Max crashes? I have a steam version. First it launches the Loading Screen, passes 10 seconds, then a black screen and a crash. + When I try to run Game Guru Max on another PC, it gives the error "the entry point to the dll was not found (hereinafter, the location folder of game guru max in steam and an indication of the exe file)".
I tried to fix the problem ON FOUR computers of different models, newness, etc., NOTHING helps. How to cope with this?

my system requirements:
Windows 10 (64-bit)
DirectX 11
NVIDEA GeForce 1050 Ti
Processor: Intel Core i3-8100 CPU @3.60 Ghz
Installed memory (RAM) 16.0 GB
Network: Broadband Internet connection
Storage: 30 GB available space
NVIDiA High Definition Audio/Realtec High Definition Audio
And it is logical that I have a keyboard and mouse that are compatible with Windows 10 and Windows in general
![ScreenShot_20220417132801](https://user-images.githubusercontent.com/103853649/163710607-2c65bdbd-2ade-4aeb-9327-3217ef005809.jpeg)
l

**Comment by plemsoft** [comment]
@Indidev234 Thanks for reporting this issue, could you locate this file "Guru-MapEditor.log" it should be in your "\Users\USERNAME\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log" folder , and post it here, so im able to see where it crash  , thanks for your help :)

**Comment by Indidev234** [comment]
> 

I'm sorry, I didn't find this folder and this file, the fact is that I have a Steam Version, and I don't have anything like that in the Documents on my disk With the path you specified. Can you specify where exactly to get this file?

**Comment by plemsoft** [comment]
@Indidev234 Yes it could be window 10 related , why cant you upgrade ? , anyway you could also try to upgrade your graphics drivers to the latest version and see if that fix your issue,  the SetThreadDescription is used in the wicked engine and could be driver and or a windows 10 not updated problem.

Also on your second computer ,there was a fix in the latest version that could fix that issue, so please also try updating MAX and give it a try on your second computer :)

**Comment by Indidev234** [comment]
Game Guru Max also crashes and also does not start. I even reinstalled Windows today and updated to the latest version 21H1. Please understand what is the problem? I'm fine with the drivers.

**Comment by plemsoft** [comment]
@Indidev234 Please make sure you installed windows 10 64bit version and not the old 32bit version.
The only other thing i can think of is that you have some special antivirus software, if you have anything running could you try to disable it and check if Max then startup for you.

If the "Guru-MapEditor.log" is not created on your system , then MAX has not started and/or something is preventing it from starting. The only thing that can do this is other software preventing it from running, or your graphics card do not support DirectX 11 features level 11_1, to validate this please try to run "dxdiag" and use "Save all information" and post it here. thanks for your help :)

**Comment by Indidev234** [comment]
Sorry, I really checked everything that is possible, I don’t even have Anti-Virus here and the built-in 64-bit one (there is no 32-bit version on my Windows disk) is disabled. I have Direct X 11, everything works correctly and the version is also acceptable. Can you offer something less formulaic and understandable for every user, especially for those who go into game dev, as a solution to the problem? 
I spent the full price of the GameGuru MAX - Starters Pack on this unique engine on Steam, which is about 1200 rubles plus a commission, on which I lost about 300 rubles due to sanctions, so I need a specific solution to the problem.

**Comment by plemsoft** [comment]
@Indidev234 Could you post your "dxdiag" here as described above, thanks :)

**Comment by Indidev234** [comment]
This is from the first PC, tomorrow I will do it from the second
![с 1 пк](https://user-images.githubusercontent.com/103853649/165191852-b084f4d7-8b88-4b4b-9026-5b79e9963937.PNG)

**Comment by plemsoft** [comment]
@Indidev234 Ohh i need the full information, you need to use "dxdiag" and use "Save all information"  , and post the text file here :)

**Comment by rvanner** [comment]
@LeeBamberTGC & @PaulSJ Adding you both into this to see if you can help too.

**Comment by Indidev234** [comment]
![2](https://user-images.githubusercontent.com/103853649/166448132-04e83aa6-6dab-48bb-9d3b-07e214e16ea0.PNG)
Finally I was able to take a picture from the computer where the exe file error is

**Comment by Indidev234** [comment]
[DxDiag.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8612157/DxDiag.txt)

**Comment by PaulSJ** [comment]
@plemsoft SetThreadDescription is officially supported in Windows 10 version 1607 and above, but it just sets a human readable description for a thread, so we should be able to remove it without any problems. However if it really is a Windows version issue then there may be other functions that will generate similar errors.

**Comment by Indidev234** [comment]
Guys, I solved the problem, the problem is in curves and support updates, I had to manually reinstall some of them with Windows rollback, but still the system drivers, I think, are a little overstated for the average consumer) I deleted the negative feedback from the steam, now it remains to deal with the same problem on other PCs

**Comment by Indidev234** [comment]
Thank you all for helping with the problem, you are great fellows, it is for such responsiveness that my team adores you)

**Comment by LeeBamberTGC** [comment]
@Indidev234 Glad you found a fix :)
