### ISSUE TITLE
GG Max - Standalone - Game Won - After winning the game, the game did not display Game Won screen

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2881]
After beating my single level game, the standalone game just shut down, and did not display any won screen.

**Comment by Tum1370** [comment]
Additional information regarding this bug.

If you press PLAY GAME and test your whole game from the HUB, after completing the first level, the game just displays GAME OVER.
I have tried both "Use storyboard logic" or "Goto Specific Level" on the WinZone on the first level, and both do the same thing.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, currently you need to test your game in the storyboard using these setting:
![test-game-storyboard](https://user-images.githubusercontent.com/18662417/164968297-aa019f01-aa73-4c31-8fb7-c219b7f4cfa0.jpg)

Give it a try and let me know if that fix your issues, Thanks :)

**Comment by Tum1370** [comment]
@plemsoft 
This reported bug was about the Standalone version. The storyboard section was additional information.
From what i remember, After playing a Standalone, the game shut down, rather than displaying GAME WON screen.

**Comment by plemsoft** [comment]
@Tum1370 Could you try to make a standalone using the latest version and if you still see the issue, could you zip the standalone folder and e-mail me a download link and i will see if im able to fix the issue , Thanks for your help e-mail: plemsoft@plemsoft.com

**Comment by Tum1370** [comment]
@plemsoft 
I Have emailed you the links for a standalone, But this Standalone is not suffering from this bug.
I will try again creating more standalones later, and if i find the same bug i will send you a link to the standalone.

**Comment by plemsoft** [comment]
@Tum1370 Are you still seeing this issue in the latest build ? , if not please close this down, you can always create a new issue if you see it again :)

**Comment by Tum1370** [comment]
@plemsoft 
Just done a very quick test of this on a level, Standlone was going to Game Complete screen after completion now. 
I will close this one for now.
This was the experimental build i tried it on.
