### ISSUE TITLE
Crash on GLTF Import

### ISSUE THREAD

**Issue by 68chase** [TheGameCreators/GameGuruRepo#2882]
Consistently when I import a .gltf file (actually add object to the library) GGMAX crashes.  However, the model does get added to the library.

**Comment by ZakJudges** [comment]
Hi @68chase, would you be able to attach here or email me a model you are seeing the issue with? My email address is zak@thegamecreators.com

**Comment by ZakJudges** [comment]
Hi @68chase, could you confirm if you still experience this issue in the latest build? Thanks

**Comment by 68chase** [comment]
Sorry I just see the response.  I will try it with last weeks build and see if it still is crashing.

**Comment by 68chase** [comment]
I can confirm the crash didn't happen with the latest version.  Thanks for fixing.

**Comment by ZakJudges** [comment]
@68chase Thank you for confirming :) I will close this issue now
