### ISSUE TITLE
Gameguru max keeps crashing

### ISSUE THREAD

**Issue by Hughjanus2022** [TheGameCreators/GameGuruRepo#2883]
textures won't load, keeps going white and disappearing altogether
and structure editor won't work sometimes

**Comment by DaveTGC2** [comment]
Thanks for the report. Can you please post your system specs.

**Comment by rvanner** [comment]
@Hughjanus2022 Can you please post some screenshots? Is this the Structure Editor or some other part of the software?

**Comment by plemsoft** [comment]
@Hughjanus2022 Could you explain more about the problem , is the white textures when you import your own models ? or perhaps if your able to make a video of the issue, it would really help us see the problem. Thanks for your help :)

**Comment by Hughjanus2022** [comment]
Not importing anything, just using built in structure editor
textures will go white our disappear completely
My pc MSI GL62M 7RD-056Performance Gaming Laptop Core i7-7700HQ GTX 1050 16GB 1TB

**Comment by LeeBamberTGC** [comment]
@Hughjanus2022 Alas the GTX 1050 is below the minimum specification at the moment for MAX. You need at least a GTX 970 (see PassMark for comparisons on speeds).

**Comment by plemsoft** [comment]
@Hughjanus2022 Thanks for reporting this issue, the structure editor textures will not go white anymore this has been fixed, i assume this is your main issue here, this will be in the next update :)
