### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by zirathashe** [TheGameCreators/GameGuruRepo#2884]
for some reason ggm crashed twice today. its the first time its ever happened to me. i dont know what happened or why. its my first time submitting a report in a long time so im sorry if i dont remember what all im supposed to do here.

i dont know what i did that caused it as both times happened by doing completely different things. it may very well be because of my pc specs
![Screenshot (862)](https://user-images.githubusercontent.com/58756931/163796579-42e0706f-f3dd-4d01-9d72-edaf04e0c60f.png)
![Screenshot (860)](https://user-images.githubusercontent.com/58756931/163796595-70e533d6-7f9d-403a-b26a-4ef5d65c01c9.png)
.

**Comment by AmenMoses** [comment]
How much VRAM does you graphics card have?  System RAM is low so could very well be RAM related.

**Comment by DaveTGC2** [comment]
I would agree with AmenMoses, your ram is below the minimum level, this will be looked at by the dev team, but does seem the likely cause.

**Comment by rvanner** [comment]
@LeeBamberTGC Here's an example of where we should be showing the user what they have used and what's left on their device to avoid a crash.

**Comment by LeeBamberTGC** [comment]
@zirathashe Can you find stats showing your GPU and video memory of the card, thanks!

**Comment by zirathashe** [comment]
![Screenshot (1078)](https://user-images.githubusercontent.com/58756931/163996915-70960a06-da8b-48f0-b608-3a55ef259977.png)
i hope this is what your looking for. took me a minute to figure out where to look to see how much vram i have. sorry

**Comment by zirathashe** [comment]
![Screenshot (1079)](https://user-images.githubusercontent.com/58756931/163997237-4b7acb90-6b0b-40d8-86da-cd78ec78e6f9.png)
heres what i could find on gpu. sorry for my lack of knowledge on where to find this stuff

**Comment by LeeBamberTGC** [comment]
@zirathashe Alas, your graphics card does not meet the minimum spec for MAX.  YOu need something about four times quicker and twice as much video memory. Passmark shows the GT 1030 at a 2500 score whereas the minimum spec GPU should be more like a 9000 score.

**Comment by zirathashe** [comment]
> @zirathashe Alas, your graphics card does not meet the minimum spec for MAX. You need something about four times quicker and twice as much video memory. Passmark shows the GT 1030 at a 2500 score whereas the minimum spec GPU should be more like a 9000 score.

i didnt have issues until i switched to steam version. before that, i never had any crash issues

**Comment by zirathashe** [comment]
can you recommend me some improvements i can make to not meet the minimum, but the recommended. not just ram and gpu, but everything including processor. (im aware my proc is low)

**Comment by LeeBamberTGC** [comment]
@zirathashe It is not that MAX wont run below min spec, but we do not extensively test below that spec so cannot guarantee a minimum level of functionality. As to recommendations, look for a laptop or desktop that uses the words 'gaming PC' somewhere in the language. This generally describes a system that can handle modern games with all settings set to high.  Like most things, the more you spend the better you get. Here is an article from a trusted source: https://www.pcgamer.com/uk/best-gaming-pc/

**Comment by zirathashe** [comment]
thank you and sorry for the trouble.
