### ISSUE TITLE
lost my document levels

### ISSUE THREAD

**Issue by BladRunner1** [TheGameCreators/GameGuruRepo#2888]

**Comment by BladRunner1** [comment]
guru max early access lost mt edited lvls documents

**Comment by BladRunner1** [comment]
help needed

**Comment by Necrym59** [comment]
check your Documents\GameGuruApps folder your previous levels should have been backed up

**Comment by plemsoft** [comment]
@BladRunner1 Thanks for reporting this issue, was you able to find the backup folder ?, also the current and future version will not delete/backup your files when installing new updates :)

**Comment by plemsoft** [comment]
@BladRunner1 I assume you found the backup folder :) , is not feel free to open a new issue, Thanks.
