### ISSUE TITLE
Transparent Shadows Can Be Seen Through Models With Flipped Normals

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2890]
This is the issue - First place an object, I believe it can be any object as long as you turn on Transparent and Cast Shadows on under Custom Materials. Then set up a light so that this object is casting a nice shadow.
Next enable "Transparent Shadows" from under the Shadows menu.
 Next place one of the problem models down. (Model with Flipped Normals)
Then go into test game, and only when the Flashlight is on, you should be able to see the shadows of the first object through the model with flipped normals. 
![2](https://user-images.githubusercontent.com/51464873/163840792-37854627-d63a-4f7f-a260-e482d308925f.png)
![1](https://user-images.githubusercontent.com/51464873/163840788-6efc4580-e205-45f9-8bf6-ddc945d3f631.png)

Per Preben -

>  The problem is that the models have flipped normals. Your best option would be to flip the normals and then reimport the objects that do not work.
> 
> For a work around you would have to change the .fpe files and change these lines to:
> 
> castshadow0      = 1
> doublesided0     = 1
> And/Or if per mesh is not used:
> 
> doublesided     = 1
> castshadow      = 1
> This will make sure the normals are useable from both sides and that a shadow can block whats behind the object , option 1 is the best :)
> 
> best regards Preben Eriksen,

**Comment by rvanner** [comment]
@plemsoft Is this fixed?

**Comment by plemsoft** [comment]
@Kitakazi Did the above fix your issue ?

**Comment by Kitakazi** [comment]
@plemsoft 
Yes this fixed my issue. Thank you!
