### ISSUE TITLE
RunTime Error 7018 ()

### ISSUE THREAD

**Issue by vstrode** [TheGameCreators/GameGuruRepo#2891]
When trying to open GG Max demo or edit or anything.

AMD FX-8350 8 Core proc 4.00GHZ
16GB RAM
SSD
Win 10 64 bit 21H2

**Comment by DaveTGC2** [comment]
Hi, is this a new issue? Have you ever been able to open MAX or the demos? Are you using the TGC or Steam version?

**Comment by vstrode** [comment]
Steam.
I have never been able to open anything since I bought MAX last week.

I use the regular Gameguru ok.

________________________________

**Comment by plemsoft** [comment]
@vstrode That error normally happen when you have a bad download of one of the files, could you try to validate you steam files , and let me know if that fix your issue.

See "HOW TO VERIFY YOUR FILES:": https://forum.game-guru.com/thread/223455

Thanks for your help :)

**Comment by plemsoft** [comment]
@vstrode Did verify your files fix your issue ?

**Comment by plemsoft** [comment]
@vstrode Any news on this issue, let me know, or i will just assume everything if now fine for you :)

**Comment by vstrode** [comment]
I had to completely dl everything and reinstall but got it working.

________________________________

**Comment by plemsoft** [comment]
@vstrode Thansk for getting back , and happy you got it working :)
