### ISSUE TITLE
Crashing When Testing Levels

### ISSUE THREAD

**Issue by NaeNae20** [TheGameCreators/GameGuruRepo#2892]
When I try to test my levels in the level editor it just crashes around loading half way. The levels are not full of multiple objects and there isn'y very much logic. Anyone have any ideas?

**Comment by DaveTGC2** [comment]
Hi, can you please let us know your system specs? Thanks,

**Comment by NaeNae20** [comment]
cpu is AMD Ryzen 5 3600 6-core

**Comment by NaeNae20** [comment]
> Hi, can you please let us know your system specs?
> 
> Also, are you using any custom media?
> 
> Thanks,

GPU = NVIDIA GeForce RTX 2060
CPU = AMD Ryzen 5 3600 6-core
OS = Win10
RAM = 16g
Internet speed = max of ~500→875MBPS; Avg. highs looking at 100KBPS on my device.
SSD = max of 466GB
no HDD

**Comment by NaeNae20** [comment]
update. it does load in but its just really slow on the verge of crashing but then runs fine when I am playing.

**Comment by plemsoft** [comment]
@NaeNae20 Do you have any custom media on the level ? , if so could you make a standalone -> zip the folder and e-mail me a download link , then im be able to see what the problem is, if you dont use any custom media just zip the level.fpm file and e-mail it to me, thanks for your help :) e-mail: plemsoft@plemsoft.com

**Comment by NaeNae20** [comment]
I do, I added custom audio to the game.

**Comment by plemsoft** [comment]
@NaeNae20 I did not get any e-mail from you, did you sent one ? , also please try it in the 04.22.2022 version and let me know if it has fixed the issue , thanks for your help :) e-mail: [plemsoft@plemsoft.com](mailto:plemsoft@plemsoft.com)

**Comment by plemsoft** [comment]
@NaeNae20 If you not able to e-mail me a download link, could you post your "Guru-MapEditor.log" here, you should load your level and then play it, exit Max and then upload a copy if "Guru-MapEditor.log
" here, it is located on your system here:
\Users\USERNAME\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log
This way I'm able to check if its a memory issue, if you do not have this issue anymore please also let me know, Thanks for your help.

**Comment by NaeNae20** [comment]
NVIDIA GeForce RTX 2060
Windows 10
16g ram

**Comment by LeeBamberTGC** [comment]
@NaeNae20 Can you try the Steam BETA version called 2022.08.19 and see if that solve it for you?

**Comment by ZakJudges** [comment]
Closing this issue due to lack of response. If the issue persists, feel free to reopen. Thanks
