### ISSUE TITLE
Selecting an asset - moves camera beyond the selected item

### ISSUE THREAD

**Issue by jasailor** [TheGameCreators/GameGuruRepo#2894]
When I select a placed asset in a scene, the camera zooms to the asset and then goes through it and a distance beyond it before it stops.    Version 2022.4.8.

JASailor

**Comment by rvanner** [comment]
@jasailor Could you make a small video of this issue please?

**Comment by jasailor** [comment]
https://user-images.githubusercontent.com/41845014/164074401-3fdbd3b0-d984-4900-b295-9cb942894be4.mp4

Here you go.  Happy hunting.

Jim

**Comment by rvanner** [comment]
OK, this is not really a bug but we should improve the system so if you do double click on an object you zoom close to it. What's currently happening is that the double click is taking you to the terrain location where the mouse points to.

@plemsoft Can you detect if the double click is on an object and zoom close in to that object?

**Comment by jasailor** [comment]
Sent you the video.  FYI - Didn’t show that the selection was initiated with a “double click”.

**Comment by jasailor** [comment]
So doctor if I do something and it hurts,  the best think to do is not do it any more.   It works for me.  You can close the issue and chalk up a point!    😊

**Comment by rvanner** [comment]
@jasailor I think we still need to make it a better experience. So double clicking on an object should let the camera zoom to that location.

**Comment by rvanner** [comment]
@plemsoft OK, that sounds fine

**Comment by rvanner** [comment]
Fixed
