### ISSUE TITLE
Custom Behavior Replaces Default

### ISSUE THREAD

**Issue by lordjulian1** [TheGameCreators/GameGuruRepo#2895]
I was experimenting with creating a Custom Behaviour. I had the character keel over when close to the player. But now, the default attack bevaviour seems to do the same. What have I done wrong?
[https://youtu.be/akbUWP0mIRE](https://forum.game-guru.com/outbound?url=https%3A%2F%2Fyoutu.be%2FakbUWP0mIRE)

**Comment by ZakJudges** [comment]
Hi @lordjulian1, apologies for the late response. Are you still experiencing this issue in the latest build?
