### ISSUE TITLE
GameGuru MAX - Bug - Light Placement Issue with Widget

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2896]
With tonight's experimental build, this old bug has reappeared:

https://github.com/TheGameCreators/GameGuruRepo/issues/2688

**Comment by Necrym59** [comment]
I was about to report that one
still issues with dynamic lights not doing as their told position/angle wise.

**Comment by LeeBamberTGC** [comment]
Fixed for this evenings EXPERIMENTAL build.

**Comment by Necrym59** [comment]
New 'experimental humor' bug found in this build or is it a new feature ;)

**Comment by rvanner** [comment]
Works fine now!
