### ISSUE TITLE
Widget mode hides all the smart object modes but this means you cannot unlock/lock objects

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2898]
![image](https://user-images.githubusercontent.com/1503593/164190712-e244226c-3c73-49f7-bc32-f7af124ac43f.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Please use just one category tag for easier management of tasks, and add the BUG tag so it counts in my bug list.  Developer mode users using the widget can lock objects using this one:

![image](https://user-images.githubusercontent.com/35840583/164192126-e942a158-85da-4126-9206-af5999afe1ba.png)

**Comment by rvanner** [comment]
When did we decide to hide those icons? That is news to me.

**Comment by LeeBamberTGC** [comment]
@rvanner The buttons where completely redundant in widget mode, why would you want to keep them, confusing the user?

**Comment by rvanner** [comment]
@LeeBamberTGC OK, so this is a recent change? Well, I locked the object and now because it's locked I cannot select it and see it in the Current Objects list and therefore I cannot unlock it! I think the same lock/unlock should be repeated here;
![image](https://user-images.githubusercontent.com/1503593/164199863-2a8b5c0d-16dc-4da3-ac80-72bc0e0874d2.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Good point, will add the LOCK/UNLOCK button back into the right panel.

**Comment by LeeBamberTGC** [comment]
@rvanner Added LOCK OBJECT(S) / UNLOCK OBJECT back into the right panel, and for consistency and space saving made it a button to match the developer widget mode buttons.  We also have room for 2 more buttons for the future. Will be in this evenings EXPERIMENTAL build.
.

**Comment by OldFlak** [comment]
@LeeBamberTGC 
We used to have the lock in the Identity Section - It made sense there - at least it did to me :)

**Comment by ArgentArts** [comment]
In any case, now we don't have to turn the widget on/off via the Developer menu. We can do that via the F1 toggle. So, accessing the lock/unlock (and Smart Object Mode) is only a single click away via F1 if the widget is activated.
