### ISSUE TITLE
Is there an editor for scripting LUA in GameGuru?

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#29]
Something like this but built in: https://forum.game-guru.com/thread/219215

**Comment by Kasseyus** [comment]
A great guide for scripting can be found here: https://steamcommunity.com/sharedfiles/filedetails/?id=398177770

A custom scripting editor is not really needed, as there are lots of free to use applications that already do a good job.  Notepad and Notepad++ are prime examples.
