### ISSUE TITLE
Salmon has wrong Script

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#2901]
![image](https://user-images.githubusercontent.com/99803873/164211854-363de4e3-2ec1-4d95-a5a6-325be90130cd.png)

The Salmon has a non-existent script attached to it (Mammal Wander), when the script should be Fish.

**Comment by LeeBamberTGC** [comment]
@rvanner We have two Salmon. May I suggest we remove all objects from the Showcase folder, they are duplicates and some are unrepaited older objects now. Instead we detect when Showcase\object.fpe is loaded, and redirect to the correct place, we can then replace the showcase folder with a showcase TXT file which will act as a reference to the real object location and allow us to switch and swap featured showcase objects each build.

**Comment by rvanner** [comment]
@LeeBamberTGC Please go ahead and make the showcase point to the real location of the object to avoid duplication issues like this.

**Comment by ZakJudges** [comment]
Issue not present on latest experimental
