### ISSUE TITLE
Character Creator Crashed

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2905]
I went into the CC to make a new character and received this error;

![image](https://user-images.githubusercontent.com/1503593/164264040-9417ecf1-94ec-4c32-a491-7b1e2c311940.png)
Followed by
![image](https://user-images.githubusercontent.com/1503593/164264075-319b4fcb-b248-46f2-8956-8fe6cd04cb47.png)

**Comment by rvanner** [comment]
The CC does not clear the last loaded character. Could that be a cause of concern?

**Comment by rvanner** [comment]
I also just tried to make another character and when I came to save it I got the crash out again (which I thought was fixed).

**Comment by ZakJudges** [comment]
At a guess, the first crash is caused by the auto swap system trying to swap something that doesn't exist. I would raise a new issue for the second crash (when creating the thumbnail)

**Comment by rvanner** [comment]
Will do!
