### ISSUE TITLE
When I save a new character, some times MAX just crashes out

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2907]

**Comment by plemsoft** [comment]
@rvanner Tried to create 10 chars with no problems , could you let me know at what point it crash ? , when clicking "save" or when clicking "add to object lib" ? perhaps if you could catch it on video i can try the same as you did. 
Also when the crash happen , could you zip up your "Guru-MapEditor.log" , just to see if there is something strange going on :)

**Comment by rvanner** [comment]
@plemsoft I've recorded a video of it happening. Will take a while to process and upload. I'll share it here when it's ready.

**Comment by rvanner** [comment]
It's still processing so give it 10 minutes;
https://youtu.be/cTu0eq6FB6Q

**Comment by plemsoft** [comment]
@rvanner Do you have the "Guru-MapEditor.log" , and do the "Man5" exists after you restart ? , look at "Tiger Man" and "Zoe Zombie" the thumbs is getting refreshed while the chars is saving think it has something to do with that , will have a look :)

**Comment by rvanner** [comment]
Here you go:

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8530114/Guru-MapEditor.log)

**Comment by plemsoft** [comment]
@rvanner Do you have a saved 'Group" smart object inside your user folder ?

**Comment by rvanner** [comment]
@plemsoft What file extension would it have? 

Do you mean in here?
C:\Users\rick_\Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user\charactercreatorplus

**Comment by rvanner** [comment]
Yes, works fine now!
