### ISSUE TITLE
Lock / Unlock buttons

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2908]
![image](https://user-images.githubusercontent.com/1503593/164290364-92edd43e-f40f-4ffc-af9b-6b67db090bb5.png)

**Comment by ArgentArts** [comment]
How about making this the lock/unlock icon so it's consistent with the rest of the UI?

![lock](https://user-images.githubusercontent.com/36735507/164308825-4df3c65a-676a-4856-9cc3-885ee26c9b91.png)

**Comment by rvanner** [comment]
@LeeBamberTGC I agree with @ArgentArts we should use the icons

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by ArgentArts** [comment]
Locked Icon appears and works. Thanks!

The only thing I would recommend is that the icon change a color or do something other than just show the open/closed lock. Something that indicates it's active. Unlocked is fine, I think. But locked should should maybe be red like the locked object's outline is? Thoughts?
