### ISSUE TITLE
GameGuru MAX - Bug - Characters/Enemies Can Charge Through Doors ... Again!

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2909]
This old bug is back in the latest experimental build with my interior level. The enemy, once they detect the player, can charge right through a closed door and get me.

**Comment by ArgentArts** [comment]
And walls, too (in my interior levels). Enemy characters seem to be able to slip between the cracks in the walls to chase after my player. It's like these old errors have crept back in again.

**Comment by ArgentArts** [comment]
If you need my test level, let me know. I'll zip it up for you.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Yes please, best way for me to reproduce quickly :)

**Comment by LeeBamberTGC** [comment]
@ArgentArts It will be somewhere, finding it is the issue for me :)

**Comment by ArgentArts** [comment]
@LeeBamberTGC I'll get the level zipped up for you and send you an email. :)

**Comment by ArgentArts** [comment]
@LeeBamberTGC I've sent you an email with a link to two test levels to help with this issue.

**Comment by ArgentArts** [comment]
@LeeBamberTGC At your convenience, please let me know if you'd gotten the email with the link to the levels. Thanks. :)

**Comment by LeeBamberTGC** [comment]
@ArgentArts Sorry for the delay. I have my inbox down to reasonable levels now, and can confirm your email and the attachment has been downloaded safely :)

**Comment by MonkeyFrogStudio** [comment]
Is fixed with the latest experimental build.
