### ISSUE TITLE
Move object and it does not find the floor in basic placement mode

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2911]
I would expect the barrel to find the floor is the icon is ticked on the right. It works for objects dragged in from the left panel but not when you move one already in the scene. 
![image](https://user-images.githubusercontent.com/1503593/164406763-cc8730a6-59a6-44d6-a398-b90b57d8e2d1.png)

**Comment by LeeBamberTGC** [comment]
@rvanner This was the original control, only finding floor when camera looking down to see the floor surface. Have changed it so it will also try to find a floor surface if camera is also looking straight ahead into the horizon, but will NOT find a surface if the camera is looking more upward as the user is NOT looking at the floor area at all.  In the next EXP build.

**Comment by rvanner** [comment]
@LeeBamberTGC If I move an object that is already in the scene and the movement system has find the floor AND match orientation, then the object should orientate too. This is the main issue. eg these two should be like the one of the left
![image](https://user-images.githubusercontent.com/1503593/165248165-e67093b2-4968-46bc-a45a-84fe84058cf3.png)

**Comment by LeeBamberTGC** [comment]
@rvanner The two on the right I clicked dragged dropped, and click hold and dragged in from the left. The one on the left I previously dragged in on the flat ;part, then moved it up the hill and it oriented fine. Can you reproduce my image:

![image](https://user-images.githubusercontent.com/35840583/165274104-d14077a3-3628-457f-a9e2-e7444f641218.png)

**Comment by rvanner** [comment]
@LeeBamberTGC OK, seems it works for these barrels but not for the Aztec items I was testing with (send by Mark). He must not be importing them properly. I will close this issue now and we can sort the Aztec stuff out next week.
