### ISSUE TITLE
LUA error during Test game

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2915]
Just got this when I did Test game;
![image](https://user-images.githubusercontent.com/1503593/164491178-17c617a5-7521-461f-8089-4f9386089e66.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Does it happen the next time you launch the MAX build and click Test Level with an empty map?

**Comment by rvanner** [comment]
@LeeBamberTGC I cannot make it happen again. I'll look out for it and report more should it reappear.

**Comment by LeeBamberTGC** [comment]
I have traced this one to the "run_away_if_hurt_properties" or similar not being called for objects when init, works when you change the behavior and then try again. I suspect the initial load of the LUA script is messing up the properties part that passes in the correct params and calls the "_properties", or in this case not doing!

**Comment by LeeBamberTGC** [comment]
Related to this one: https://github.com/TheGameCreators/GameGuruRepo/issues/2928
