### ISSUE TITLE
Sound Problem in standalone

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#292]
This is about Pause Menu.
When we pause the game, if there is a _looped_ sound, it _restarts_ from the beginning when we resume the game.
And if there's a _one-time_ sound, like a music or a vocal message, it _disappears_ when resuming.

It's a big problem to me.
I need every sound to continue just the same as it was before pausing the game.

**Comment by thecyrus** [comment]
I will call this issue "Please don't stop the music". :D

**Comment by LeeBamberTGC** [comment]
Marking this as a bug, as there should be a way to identify all playing sounds, pause them and then resume them once the in-game menu is left.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Looks Like Lee already understands the problem.

**Comment by LeeBamberTGC** [comment]
Changed code so now all relevant sounds and music loops are paused and resumed, instead of just stopped.

**Comment by thecyrus** [comment]
Thank you, this was very relevant to me.
