### ISSUE TITLE
GGMAX - Health Script issue

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2922]
The Health Behaviour states: "The object will give the player a health boost if the current health is under 80."
this is incorrect it just gives health when the distance is smaller than 80. The bahaviour should be modified to somthing like this
![health_new](https://user-images.githubusercontent.com/95015657/164584248-23c89a1c-4ea3-46cf-8d20-2da54b7a5873.png)
that allows to ajust the pickup range and how much health received.

**Comment by Necrym59** [comment]
Alternative health.lua supplied
[health.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8562610/health.zip)

**Comment by LeeBamberTGC** [comment]
@Necrym59 A VERY good piece of script there, please send more :)
