### ISSUE TITLE
Key should stack on top of table but stays on the floor

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2927]
![image](https://user-images.githubusercontent.com/1503593/164713233-aea3bbcf-2bf5-43f7-b964-ab5b01d5340c.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Going to need a little more. I dropped in a table, then dragged in  a key, it was on the table. I dropped on the floor, then dragged that key to the table, it found the top:

![image](https://user-images.githubusercontent.com/35840583/165073194-23a5f343-c00b-4988-a63e-3c04b21762cd.png)

**Comment by rvanner** [comment]
@LeeBamberTGC Seems to be to do with other tables in the library. You can see the keys on the cellar table but these others don't let you put the keys on top of them. Something to do with their setup?

![image](https://user-images.githubusercontent.com/1503593/165078867-ce6145e2-58ba-4487-8340-d128120b6884.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Seems the Household objects where not converted as good as some other objects, and have a weird inverted polygon cull/normal/scale data that renders okay, but confuses the ray caster. I have updated the FPEs to compensate and objects are now placed correctly. Let me know if other Booster Pack objects exhibit the same issue,  In next EXP build.
