### ISSUE TITLE
LUA bug

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2928]
@LeeBamberTGC I made this test level and have run into a LUA bug. Map file attached for you to see the issue.

![image](https://user-images.githubusercontent.com/1503593/164714462-435c6947-c6d8-40e7-b602-7ce7167eb96a.png)
[keyanddoors.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8540997/keyanddoors.zip)

**Comment by Necrym59** [comment]
I got the error only once, however these doors dont make sense i opened a door with no key
![closed_nokey](https://user-images.githubusercontent.com/95015657/164788419-8a21fe4f-2f4e-4fb0-8d77-cf9e275cac46.png)
then it asked for one once it was opened.
![opend_no_key](https://user-images.githubusercontent.com/95015657/164788470-d757c4a2-5f6e-4a14-8310-9e579a5a5a38.png)

**Comment by Necrym59** [comment]
I then i restarted and opened all doors except one that actually needed the key??
![all_opened](https://user-images.githubusercontent.com/95015657/164789023-e4d4fc91-a4dd-4ab8-a23a-890a4c849054.png)
Also the doors opened or prompted to open closer to the hinged edge

**Comment by rvanner** [comment]
@Necrym59 Can you please check this now works for you in the latest experimental build?

**Comment by Necrym59** [comment]
No doors open without key, thay all asked for it (thats ok) i picked up the key and went to open the second door from the end
and recieved an error
![error](https://user-images.githubusercontent.com/95015657/165167715-4375844d-20aa-49da-825e-bfff93599027.png)
then i continued after error closed and the door next to it opened automatically??
![doors](https://user-images.githubusercontent.com/95015657/165167846-6beacf91-7cde-430e-b0dc-f7a33aab3cad.png)

**Comment by Necrym59** [comment]
Seems to function ok on a new map - the proximity of doors to close to each other just causes some unusal openings i thinkk thats to be expected normally you would have doors that close i dont think

**Comment by LeeBamberTGC** [comment]
@Necrym59 Yes the fix last night on EXP only works for newly added objects, older levels before that fix, you will need to click each object and view the DLUA behavior panel, it will then create the missing data causing this.
