### ISSUE TITLE
QUESTION About : Pixelated shape mode in terrain mode

### ISSUE THREAD

**Issue by Daveutopias** [TheGameCreators/GameGuruRepo#293]
Hi, with the latest version of PP BUILD i see there are NO correction against some textures that are more bright then before, i mean that now with new pbr rendering i have noticed some interrupted bright of mountain in terrain mode, check the screenshot, maybe i think this could be fixed with more accurated with new version?
![pbr wrong](https://user-images.githubusercontent.com/40697420/42544461-481097c6-84b2-11e8-99b7-b7906d6a7abd.png)
![pbr wrong 2](https://user-images.githubusercontent.com/40697420/42544464-4e00e582-84b2-11e8-80c8-5c6cbe235afd.png)

**Comment by LeeBamberTGC** [comment]
I have marked this as a bug, and can be really seen in the MARS TERRAIN of the SciFi Pack too, and related to the fact the terrain was created before the PBR renderer came online. Legacy terrain needs to tone down the glossiness A LOT, in some way that resembles the pre-PBR rendering method.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed still the same ..

![gloss](https://user-images.githubusercontent.com/35708217/74201444-b88cdf00-4c61-11ea-96f3-45ded90fd256.png)

**Comment by LeeBamberTGC** [comment]
Added new NOTERRAINSPECULAR to effectbank\settings.fx to switch off specular for terrains by default (slight performance boost too). If you are using newer terrains, you can comment out this and recompile shaders to have specular on again for all terrains.
