### ISSUE TITLE
Character Creator will have the wrong background when you go back into it

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2932]
eg;

1. Load up the CC
2. Change from Male to Female
3. Save the character
4. Load up the CC again, the character is the female from before but the background is the male background

![image](https://user-images.githubusercontent.com/1503593/164741103-6a819b05-9c1d-40f7-9590-a9a895f3af94.png)

**Comment by ArgentArts** [comment]
Not sure why they need two different backgrounds, to be frank ...

**Comment by rvanner** [comment]
Confirmed as fixed!
