### ISSUE TITLE
GameGuru MAX - Request - Enable Trees to NOT Turn On Trees Everywhere

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2936]
Currently, if I create an empty level and want to add a some grass and a tree or two, I have to turn on trees. But when I do that, trees spring up everywhere! What if I only want to add a few trees? What if my level is an indoor level, but I have a small courtyard in the midst that has three or four trees I want there with some grass? I'd love to just use MAX's system to just plant a few trees without having MAX decide that my entire level needs a zillion trees everywhere else. ;

![trees](https://user-images.githubusercontent.com/36735507/164776396-932fa8d3-a933-436a-aba3-5da25c8e8c79.png)
)

**Comment by synchromesh62** [comment]
Easy 
Enable Trees, Clear all Trees, then spray wherever and whenever you like 
As the video below shows :)
https://youtu.be/a3UlLdKj18U
Hope that helps

**Comment by ArgentArts** [comment]
@synchromesh62 Thanks! That works a treat!

Heh. What I'd done? I'd created an empty level as a test, zoomed in, painted some terrain, painted some grass, then enabled trees and planted a few. It all looked good. Then I moved my camera back to see this forest everywhere! I was like, "Where did all that come from?!?" Hah! Because I was so close to the ground to begin with, when I had initially enabled trees, I didn't see any of them appear. :P
