### ISSUE TITLE
Some Character models Rotated (Y) 180 after test run in editor. 

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#2939]
Some of my Store bought character models are rotated 180 around Y after test run.
1. As screen 1 shows the skeletons are all facing me
![skel-1](https://user-images.githubusercontent.com/35811289/164785758-41296d8f-574b-41e3-a70a-670ea3a6a84a.jpg)
.
2. I do test run the skeletons all move and walk and run forwards in the correct directions.
3. I exit from the test run back to editor. But all the Skeletons have rotated 180 and
   are facing away from me.
![skel-2](https://user-images.githubusercontent.com/35811289/164786014-7408ddd8-8e1a-4e0d-b0eb-4704f99bdc88.jpg)

4. Now if I start test run again. All the skeletons are moving walking and running backwards.
5. But If I click the mouse on a skeleton it will instantly rotate back to its normal 
   position facing me. (and will work normally in test run)
6. Also if I don't click the highlighted yellow skeleton.. 
   but press any of the other ones. 
   Then the one I click and the Yellow highlighted one both instantly rotate to 
   the correct position facing me.
![skel-3](https://user-images.githubusercontent.com/35811289/164786367-e478b9eb-9201-4d22-837e-8990e0be51c3.jpg)

Now all of these models had been working perfectly for months and months but a few
months back this rotate(Y) problem appeared.

I think it may be due to some speed improvement works and some form of initialisation
has be missed off in the editor.

One other thing I think all these models where ones that used the 
 [roty = 180]
 [fixnewy = 180]
in the FPE file.

**Comment by thor49** [comment]
It's not just the model skeletons I have shown in the images above.. but many other characters I own have this problem.

**Comment by LeeBamberTGC** [comment]
@thor49 You will need to contact the author of those characters so they can fix them for MAX.  We can only fix the characters that come out of the box with MAX or its DLC.
