### ISSUE TITLE
shadow bug - terrain shader set to medium

### ISSUE THREAD

**Issue by demented-mind** [TheGameCreators/GameGuruRepo#294]
This is not a show stopper but it might still be a bug.

When the shader options are set as follows:

Terrain - medium
Entity   - lowest
Grass   - lowest

The shadow of the entity whacks out. When you use mouse-look the shadow of the objects will move around with the view. See this [link](https://vimeo.com/279541579). It seems that any other combinations will work fine. This is why it is not a show stopper. The whole video linked will show this as being the case.

**Comment by LeeBamberTGC** [comment]
Well found, fixed for next PP build later today
