### ISSUE TITLE
GG Max - Bug - Placing 1 tree using ADD A TREE in Terrain Tools

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2943]
I have just noticed that on one of my maps i can NOT place a single tree using the Add a Tree option in Terrain Tools. Spraying Trees still works fine.

But on a different map i can place trees normally. So this BUG is only happening on one map that i have.

Now after further testing, I noticed on the map i cannot place a tree, i found this.
After placing a single tree in a couple of locations, They did not show. But when i moved the slider of the Tree Water Distance, The trees i placed in a couple of locations then suddenly appeared.

This was nothing to do with been placed to close to water.

**Comment by PaulSJ** [comment]
@Tum1370 Can you send me the level that experiences a problem, or give me some steps to reproduce this?

**Comment by Tum1370** [comment]
@PaulSJ 
Am sorry i cannot reproduce this problem on any other map than the one i have the problem with.
BUt the problem does exist, but i am not sure why its only happening on one map.

**Comment by PaulSJ** [comment]
If you can please send the level to paul@thegamecreators.com

**Comment by Tum1370** [comment]
@PaulSJ 
Which files do you need sending ? Just the .fpm file ?

I have just retested this one map that i have this problem with, and it is still happening on the Experimental build.

I placed 3 single trees, and they did not appear until i slightly moved the tree water distance slider. This is even though the trees are no where near the water.

**Comment by PaulSJ** [comment]
Thanks, I'm able to replicate it with your level, I'll see if I can track down the cause.

**Comment by PaulSJ** [comment]
The fix should be in the next version

**Comment by PaulSJ** [comment]
@LeeBamberTGC Can you pull the changes from PJ-Branch11 into the master branch?

**Comment by Tum1370** [comment]
@LeeBamberTGC @PaulSJ 
Am closing this issue. Just tested the latest experimental Max and this is now fixed for the map it was happening on.
Thanks
