### ISSUE TITLE
model importor issues.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2946]
i'll just  post screen shots for this one.

object  breaks.
![image](https://user-images.githubusercontent.com/68471279/164945456-d188aaf5-04cd-4154-be73-b9cc6786b44d.png)

fine in 3d   viewer/blender

![image](https://user-images.githubusercontent.com/68471279/164945694-d246f82a-a4b5-4c3a-bc1d-594b59aca100.png)

object (despite having .mtl there and required textures)

![image](https://user-images.githubusercontent.com/68471279/164945481-8cda9d97-c342-46e3-b8e3-0162cf319a8d.png)

I  have. no idea.

![image](https://user-images.githubusercontent.com/68471279/164945500-6b4621b5-677c-46f4-8d17-614495be193d.png)

**Comment by ZakJudges** [comment]
Hi @casigus, so I can look into these issues for you, could you please send me the models and textures to zak@thegamecreators.com

That will allow me to reproduce the issues and see where things are going wrong. Thanks!
