### ISSUE TITLE
GameGuru MAX - Bug - Filter Effect Cannot Be Set to NONE in Demo Games

### ISSUE THREAD

**Issue by ArgentArts** [TheGameCreators/GameGuruRepo#2947]
In the editor, if you go to Filter Effect, you can select any filter effect and then turn them off by clicking on NONE:

![filter1](https://user-images.githubusercontent.com/36735507/164945804-99a2249b-127d-400d-a6aa-06630b3a95cc.png)

In a test game, via TabTab, you can do the same. However, in any of the Demo Games, if you use TabTab, the NONE button is missing. Therefore, if you select one of the filters, you are not able to select NONE and, therefore, are forced to use one of the filters since you cannot turn it off:

![filter2](https://user-images.githubusercontent.com/36735507/164945843-fb2b8366-339d-4650-af77-424edd76529d.png)

Again, this is ONLY with the DEMOS. The NONE button shows up in TEST games via TabTab.

**Comment by ArgentArts** [comment]
@rvanner It's not TEST GAME that's the issue, but in the DEMOS (correcting the tags).

**Comment by plemsoft** [comment]
@ArgentArts Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by ArgentArts** [comment]
Is now working as of the latest experimental build. Thanks!
