### ISSUE TITLE
population of vegitation do not work, and density slider aswell.

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#2949]
i see that after the latest build / upgrade that the populate of the grass function do not work , you can select any type of vegetation but it does not populate it. , it only populate one default grass type and not the one you selected.  ,  and also the density slider also don't work,

**Comment by PaulSJ** [comment]
@Pcskiller I'm not able to replicate this in the current version, does it only happen on a particular level or in new levels as well? Are there any steps I need to take beforehand to encounter this problem?

The density slider doesn't have an immediate effect, it will take effect when you next paint some grass.

**Comment by Pcskiller** [comment]
It happens on any level, old or new and my Software is up to date.

**Comment by Pcskiller** [comment]
"The density slider doesn't have an immediate effect, it will take effect when you next paint some grass."
Isn't the density slider to also work on the populated vegetation as well ,  because i can set it any were and then press the populate button and then it does populate,,  but the density stays the same and it always just populate with one basic grass type, not any of the ones i have selected.

**Comment by PaulSJ** [comment]
Ah I see, it's the repopulate button that isn't respecting user settings. Fixed for the next version.

**Comment by Pcskiller** [comment]
HI, it looks like its fixed. Thank you.

**Comment by Pcskiller** [comment]
Ok, Sorry to burst the buble but this is not fixed or its broken again.
