### ISSUE TITLE
Monster Beta - Terrain textures not picking from right mouse click.

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#295]
Seems like the texture picking for terrain painting is not working in the latest monster beta

Reproduction:
Open Game Guru.
Choose the paint terrain tool.
Right mouse click on any of the tiles.
Window opens to choose new texture.
Pick texture.
GG says it is generating the new terrain texture.
After completion, there is no change from the default pallet.

**Comment by synchromesh62** [comment]
Strange its working for me ?
Ones I made "without" including the alpha channel still wont load in but stock and others I made seem to be fine .. Using Monster update

**Comment by demented-mind** [comment]
Using Monster Update works for me as well. Did you happen to paint the terrain after changing it? When I first chose a texture, it was so close that I  didn't think it changed but as soon as I started painting the terrain it used what I had chosen. So apparently it _was_ too close to call. 😄

**Comment by Pirate-Myke** [comment]
Ok, Terrain Diffuse textures need to have alpha in them to work now.

Disregard this issue.
