### ISSUE TITLE
Max2022.04.22: Importer :Bug loosing material names

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#2951]
The imported often replaces material names that exist in source import with noname making it extremely difficult to match up textures. Particularly with complex models with may parts and textures.

**Comment by ZakJudges** [comment]
Hi @Ratall, so I can look into this, could you send me a model that you are seeing the issue with to zak@thegamecreators.com

That will allow me to reproduce what you are seeing so I can work on a fix. Thanks!

**Comment by Ratall** [comment]
@ZakJudges I did some more investigating last night and I believe the import sets the material name to noname if
A) The Material has no texture associated with it.
B) The texture file is associated with another material as well.
for example
![gets a material name](https://user-images.githubusercontent.com/35710601/165209132-15878586-f109-4c07-98fd-5c9878408044.png)

Gets a material name But
![Gets noname texture file already used by Floor_wood_Pbr](https://user-images.githubusercontent.com/35710601/165209276-5f2f50c1-8718-4fe7-8663-1149a7ea716c.png)
Does not as it uses the same texture as above

this one gets noname as it has no texture
![Gets noname as no texture file](https://user-images.githubusercontent.com/35710601/165209496-35f85172-7f09-4d1e-aaee-df8ebacedbc2.png)

It is important to get the material names even if there is no texture files so I came tweek things like base colour.

the model is from iclone and has some copyright restrictions so I will have to create something that has the above problem if you still need one,
Thanks.

**Comment by Ratall** [comment]
Alas no change 

![Alas nochange](https://user-images.githubusercontent.com/35710601/166082654-460f8c71-d35d-4d13-8749-e34ed5e45970.png)
this is an fbx import I will try in in some other formats

**Comment by ZakJudges** [comment]
Hi @Ratall, thank you for getting back to me. I will not share the model and will delete it after testing. My email address is zak@thegamecreators.com 
Alternatively, you can direct me to another model freely available online that shows the issue, and I can reproduce it from there. Thanks!

**Comment by Ratall** [comment]
@ZakJudges I sent it via Google (I think I have never done that Before) it is a bit large(81 materials, 68 textures) but that is what makes it a hard test.

**Comment by ZakJudges** [comment]
Hi @Ratall, can I just double check if the 81 materials are all supposed to be unique? Or if some are reused across multiple meshes? Thanks!

**Comment by Ratall** [comment]
G'Day @ZakJudges
Some are used across multiple meshes.
Is that a problem?

**Comment by ZakJudges** [comment]
Hi @Ratall, at the moment, the Max importer assumes that each mesh has a unique material and so will have a hard time figuring out materials that should be applied to multiple meshes. We do have a system planned to handle this (see #3064 and #2805 for more info) but no ETA on that yet.
It should also be noted that the importer does not support embedded textures in files, and requires the actual texture files to be present alongside the object file.

There are some things you could try to force the importer to use a different approach to texturing the meshes of the house:

- Ensure that each mesh that makes up the object has a name in your 3D modelling software
- Given a mesh called "mymesh", the textures should be named like so: "mymesh_color.dds", "mymesh_normal.dds", "mymesh_surface.dds" 
- Ensure that each mesh has at least a _color texture assigned to it
- Ensure that texture files are placed in the same folder alongside the object file, and not in separate folders

Following the above steps should allow the importer to find the textures when no materials have been assigned during creation of the object. Hope that helps until we can implement the previously mentioned system. Any questions just let me know :)

**Comment by Ratall** [comment]
Ok @ZakJudges 
I'll go thru my modelling software an see which is easiest to script a converter.
Is combining all meshes for a material into one(mesh) or creating individually named materials for each mesh the best approach?
Quick question which versions of FBX is the importer certified on.

 I noticed that assimp.dll is require for the standalone would it not be easier maintenance wise if the importer was kept completely separate from the main engine or are you guys planning on adding in game importuning; I mean importing in the future.

**Comment by ZakJudges** [comment]
Hi @Ratall,

I am still working on a guide to find which versions of file formats the importer can handle without issue. One of our artists uses FBX 7.3 (2013) and has no problems with that. However, it does increasingly seem that in most cases, problems arise based on how the model was created, rather than the version of the file used. I'll hopefully have more info on this in the near future :)

> I noticed that assimp.dll is require for the standalone

Good catch, I have added this info to the existing issue about redundant standalone files (#2301)

**Comment by Ratall** [comment]
See Also #3311

**Comment by ZakJudges** [comment]
Hi, a fix for the material names being wiped out has been uploaded to a new Steam experimental build
