### ISSUE TITLE
Max2022.04.22: Importer : Bug under Materials Surface file path defaults to Imported Models

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#2954]
When selecting material while importing surface defaults the \Documents\GameGuruApps\GameGuruMAX\imported_models whereas Albedo and Normal default to the directory you are importing the model from..

**Comment by ZakJudges** [comment]
Hi @Ratall, thank you for reporting this issue. A fix has been added which you should see in the next update. I will post here when the update is available, and the fix ready to test :)

**Comment by Ratall** [comment]
That seems to be OK now
Thanks
