### ISSUE TITLE
Max2022.04.22: Bug Importer After selecting Surface file textbox for filename remains empty

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#2955]
![Surface filename nissing](https://user-images.githubusercontent.com/35710601/164955174-62c2bc03-66e7-45dd-9d50-30e84acec1b4.png)

**Comment by ZakJudges** [comment]
Hi @Ratall, I wasn't able to reproduce this one. Could you send me a video of the issue occurring when you select a texture? Thanks

**Comment by Ratall** [comment]
@ZakJudges In the video I did it 2 ways the first worked and the field reflected the file name the second i used the 3 dots and it did not. 
hope this helps

[Wait till the end.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8559704/Wait.till.the.end.zip)

**Comment by ZakJudges** [comment]
Hi @Ratall, thank you for the video. I have added a fix which should be available in this Friday's update. When you get the update, could you confirm if the issue is fixed for you? Thanks :)

**Comment by Ratall** [comment]
That seems to be OK now
Thanks
