### ISSUE TITLE
Max : request : Ability to enable/disable Auto flatten in object tools

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#2959]
Sometime 2 object close to each other with auto flatten on will create conflicts. Other times you just do not know that an objects auto flatten will do to surrounding objects and terrain till you place it.

**Comment by plemsoft** [comment]
@Ratall Thanks for your request, this has been added, you find the auto flatten button in the "general" section :)

**Comment by Ratall** [comment]
Thanks
