### ISSUE TITLE
Max2022.04.22: Bug Saved Group fails to load correctly

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#2965]
![Failed group load](https://user-images.githubusercontent.com/35710601/165039053-c974bfb9-4ffd-4ec1-8a34-68d3c4f83bb5.png)
Original next to failed load from object library

**Comment by Ratall** [comment]
@plemsoft Thanks for your diligence, look forward to testing it in the next update.

**Comment by Ratall** [comment]
Still Broken in 2020.04.29
![Lefthand as saved right as loaded](https://user-images.githubusercontent.com/35710601/166082231-2ea6e86a-fc35-488f-a2ae-6d8564e5869a.png)
The left hand version is as created the right is as loaded.

**Comment by Ratall** [comment]
See also #3030

**Comment by plemsoft** [comment]
@Ratall Just tested this in the lastes EXP build , and was not able to reproduce it , could you try again and let me know if its also fixed for you, Thanks for your help :)

**Comment by LeeBamberTGC** [comment]
@Ratall Fixed for next EXP build:
![image](https://user-images.githubusercontent.com/35840583/229365170-872a11cd-958e-45f1-bd9a-2d3b7189537b.png)
