### ISSUE TITLE
GameGuru Max Issue - MASSIVE FPS Drop When Using "SetPlayerFOV"

### ISSUE THREAD

**Issue by DarthPickles666** [TheGameCreators/GameGuruRepo#2970]
Hi there, so I've noticed a massive issue when using a script for a Helmet HUD on one of my outdoor levels. Without this script running, I get 80FPS (which is a separate issue altogether), then when I load up the level with the script running from the start, it drops down to 20FPS!!! This is a HUGE issue, especially since my game is Sci Fi and I would prefer it if I had the Helmet HUD. 

I've attached a picture of the FPS counter with and without the HUD (top left corner) 

![image](https://user-images.githubusercontent.com/101579658/165124254-34a1ddfb-243b-4988-9758-97484279a887.png)

![image](https://user-images.githubusercontent.com/101579658/165124789-1acfc6a7-cdbf-4fdf-941e-c8e2d98cae27.png)

Thanks

Jereth

**Comment by DarthPickles666** [comment]
Just to add, it ONLY does this massive FPS drop when the script for the HUD is running. Without it, it runs fine at 80FPS.

**Comment by rvanner** [comment]
@LeeBamberTGC Paul said he wasn't the best at looking into this. Maybe you or Preben?

**Comment by DarthPickles666** [comment]
Hey folks, I believe it's been fixed, someone has edited the script and I'm now getting the 80 fps again. Not sure if this is an issue for anyone else, but the script seems fine now. 

![image](https://user-images.githubusercontent.com/101579658/165142077-f618365e-d2be-4523-9624-bbab4a44a738.png)

**Comment by AmenMoses** [comment]
The culprit was SetPlayerFOV() which was being called every frame.

smallg changed the script to only call SetPlayerFOV() when needed, i.e. not to call it unless the value changed.

But it might be good idea to look at what the function is actually doing in MAX as I'm pretty sure it didn't do that in Classic (Cine|Guru allows smooth camera fades using FOV changes every frame).

**Comment by Necrym59** [comment]
Sorry my mistake in the script - couldnt wait for me to have a sleep to fix it ;)

**Comment by LeeBamberTGC** [comment]
NOTE: Added code so only do massive FPS hungry visual update if the FOV actually changes. Lots happening when you change FOV as it updates related things in the visuals code :)
