### ISSUE TITLE
When you drag in a group in Widget mode, the group gets dropped on the left you cannot drag it in exactly

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2972]
![image](https://user-images.githubusercontent.com/1503593/165145909-5dc4de27-dee1-4d66-8fd6-a02aa48b54af.png)

**Comment by LeeBamberTGC** [comment]
@rvanner Cannot reproduce with curent build, suggest trying EXP build this evening (will send email to all).

**Comment by LeeBamberTGC** [comment]
@ZakJudges This works when NOT using the widget, so compare that correct behavior to when MR Widget is active, and see how the behavior changes.  That difference is the bug, and ensure the dragging in acts like the non widget approach, just for the drag event.

**Comment by rvanner** [comment]
@ZakJudges I think it's just how the widget works vs no widget. I am happy to close this now.
