### ISSUE TITLE
GG Max - Experimental Build - BUG - Dragging Objects from Level Editor to Level Objects panel does NOT delete

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2977]
In the experimental build on Steam, When you drag an item from the level editor to the Level Objects panel to delete it, It does NOT delete it now.
All it does is place that object in the Editor again, but out of sight behind the Level Objects panel.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
Fixed, am closing this one. 
Thanks
