### ISSUE TITLE
Switch Behavior Linked to Door with Door Sliding Behavior Does not Close the Door

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2978]
Like the title says if you attach a Switch to a Door with the Door Sliding Behavior it will open the door but activating the switch again does not close the door. 

Additionally the Door Sliding Behavior does not have an option to have the door start Unlocked.

**Comment by ArgentArts** [comment]
Switch opens and closed the sliding door for me:

https://user-images.githubusercontent.com/36735507/165385281-e83c2959-2a4b-4dc8-a8bf-f482bf73d38b.mp4

**Comment by Kitakazi** [comment]
Huh thats weird. I have no idea why mine does not close the door. I will test some more in a bit 

And yea I was thinking if you wanted the door to open automatically when in range there was no way to have the door start unlocked. Not really a big deal.

**Comment by ArgentArts** [comment]
Yes, you can start with the door unlocked and have it open when a player is in range. I have all my sliding doors opening that way. They auto-open when the player crosses the trigger area I've set up.
