### ISSUE TITLE
GameGuru MAX (alpha 2022-04-22) : Object Tool - Rotation Angle Z 

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#2980]
Hello,

In my opinion there is a problem with the 'Rotation Angle Z' setting of the 'Object Tool'.

Please could you verify ?

Thank you.

**Comment by ArgentArts** [comment]
Just checked on one of my objects and it appears to be working as it should. Why do you say there's a problem?

**Comment by LeeBamberTGC** [comment]
@marcuswilm Rotation Angle Z looks fine, Z goes into the distance and 45 degrees rotates the table along that axis:

![image](https://user-images.githubusercontent.com/35840583/165487193-14e80af3-c031-4216-b75d-ff08084c741f.png)

**Comment by marcuswilm** [comment]
@ArgentArts (Monkey Frog)
@LeeBamberTGC 

Hello and thank you for your fast reaction to this report of a possible issue.

I want to show this short video ( 53 seconds - 27 MBytes - HD - no sound) published on my Vimeo channel where you can see that when the Rotation Angle Y is ~= 0 then the Rotation Angle Z parameter applies an unexpected rotation of the asset.

Here is the link : https://vimeo.com/703681867

Thanks for watching.

**Comment by LeeBamberTGC** [comment]
@marcuswilm Alas that is how our Euler rotation works, in the XYZ rotation order. When you set Y to 60 degrees, it rotated the eventual Z axis rotation first by 60 on the Y.  For world rotation, try pressing F3 and using the widget rotation which is now world based and uses Quaternions to retain the correct global rotation for your object.

**Comment by LeeBamberTGC** [comment]
P.S. Feel free to close this one :)

**Comment by marcuswilm** [comment]
@LeeBamberTGC  Thank you for this clear explanation. It surely helps me to understand the rotation's rules in GameGuru.

Therefore I agree with you about closing this report.

:)
