### ISSUE TITLE
Grouping objects

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2981]
It should be possible to group objects using Control+Left Click to highlight objects one at a time.

Lee - I could not even select more than one object doing this, so I don't think it's possible yet.

**Comment by ArgentArts** [comment]
@rvanner It does work, just not like it's supposed to. ;) If you select something so it's highlighted, then CTRL+CLICK another object, the second object will be selected only. Keep CTRL depressed and then go back and re-click the first object and you'll find that it is now added to the group selection. You can now keep CTRL depressed and keep clicking to keep adding more to the group. 

But, you're right, this is not the way it should work. You should just be able to select the first object, press and hold CTRL and then click the next object to just add it.

**Comment by LeeBamberTGC** [comment]
@rvanner Yes indeed, tidy little bug this one. Fixed for next EXP build.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC This does not appear to be working yet. I still have to click to select the first object, the CTRL+Click on the second object DESELECTS the first selected object. After that, CTRL+Click will add to the selection.

Now, if you CTRL+Click the FIRST object, it works correctly from there on out. But if you already have an object selected (i.e. it wasn't selected first with CTRL depressed), then when you CTRL+Click the next object, the other object will be deselected, and that's not the desired outcome.

In most software, you should be able to select the first object the standard way (via a simple click) and, from that point on, use CTRL to ADD to that selection.
