### ISSUE TITLE
MSAO on by defaul

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2983]
Ensure MSAO is enabled as a default setting to ensure quality visuals from the start

**Comment by ArgentArts** [comment]
@rvanner Do we want to have MSAO turned on by default from the the start when MSAO does not (yet) affect outdoor levels? Currently, MSAO does not affect terrain, grasses and plants, or trees placed by MAX's Terrain Generator. 

https://github.com/TheGameCreators/GameGuruRepo/issues/2937

**Comment by LeeBamberTGC** [comment]
@plemsoft Feel free to commit to your own branch, and I will merge this evening along with my own fixes for next week.  My own version of it works well and has been tested, I am sure we did the same code changes :)

**Comment by synchromesh62** [comment]
> @plemsoft Feel free to commit to your own branch, and I will merge this evening along with my own fixes for next week. My own version of it works well and has been tested, I am sure we did the same code changes :)

Hi Lee apologies for Re-Opening
MSAO now indeed enabled by default but does not show unless you disable and re-enable it.

**Comment by synchromesh62** [comment]
Just got another tiny update that looks like its fixed
