### ISSUE TITLE
Flicker issue

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2984]
@plemsoft I spoke to @PaulSJ about this and he thinks it's something you're doing.

It seems this flicker issue is related to the animating of objects in the object library. See this video;

https://youtu.be/kxaav93t2bo

**Comment by plemsoft** [comment]
@rvanner Possible fixed in current EXP build :)

**Comment by rvanner** [comment]
@plemsoft Yes seems to be fixed! Well done all. I have noticed another small issue which I will put into a new issue.
