### ISSUE TITLE
Animation not playing in-game

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2985]
exported everything perfectly in  Blender.

import intto ggmax

![image](https://user-images.githubusercontent.com/68471279/165531292-0c7370e5-5707-4ba1-a88f-ae7f8b7f5373.png)

the animations  work  in  the  importer, but  the second  its imported. The animations  no longer  work.
when  the  obj is in  the  importer mode, it  becomes super  janky, rather  than the  smooth  slow sinking in the export.

![image](https://user-images.githubusercontent.com/68471279/165531705-4742cbb5-361b-4656-8630-ade62eb70c72.png)

double checked  the model in 3d viewer,  animations are fine.

![image](https://user-images.githubusercontent.com/68471279/165531976-742d97a9-04cf-4490-84ab-d7d611b361b1.png)

is this a max bug  or am  I  missing something.

Attached  the model exports to see  if you can get the same  results.

forgive   the  naming,  after  exporting and re-importing  my brain started to  melt

https://drive.google.com/drive/folders/19DP2O0xfiqx6PMB7ffnw5eICln2p_Mqe?usp=sharing

**Comment by ZakJudges** [comment]
Hi @casigus The strange movements are caused by the ship being under the terrain. The ship will then be in a constant state of collision and the physics engine tries to move it so it is no longer colliding with anything. 
I did notice that the animation didn't play after importing, so I will take a look at that and rename the issue :)

**Comment by casigus** [comment]
ive been having animations problems with thhe entire build,  they animations dont play when imported, and when  they  do they are incredible janky. did a  roll back  of a  second  max install and the  importer   worked okish with the animations working  as  i exported them.

**Comment by casigus** [comment]
yeah! BEFORE the updates,  animations  used to be smooth,  now when they import it causes a slow  down  jank/stuttering  effect.

examples:

https://youtu.be/Iq0HdN_COJE




also the  importer  messes up  the  model,  

![image](https://user-images.githubusercontent.com/68471279/165800196-8159dbf9-5faa-43e6-a2d9-e6536cca02f0.png)

now the  doors are there  but  the import  process has  caused  them to swap posistions  and end up mergingn into  the middle of t he  object.

or in this case, it just imports abox,  where in the 3d view the models fine,

![image](https://user-images.githubusercontent.com/68471279/165800598-cdf6311c-1fc9-46d9-b7b4-1542bd5e2643.png)

this one  is  self explanatory:

![image](https://user-images.githubusercontent.com/68471279/165800859-60ed2254-e65c-4a7e-959b-7e9a64b5b5ad.png)

![image](https://user-images.githubusercontent.com/68471279/165800929-01a66a64-199b-49a4-9fab-4e51cabb1140.png)

**Comment by ZakJudges** [comment]
Hi @casigus, the animation issue should now be ready to test :)

**Comment by casigus** [comment]
yeah! works great. <3
