### ISSUE TITLE
GG Max - Bug - Experimental Build - Standalone game, No Red Dot on Compact Rifle Scope

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2988]
On the experimental build i have just created a standalone to test something else, But i am seeing no RED DOT on the Compact Rifle Scope.
I have set player in invulnerable. Not sure whether that has caused the problem ?

![image](https://user-images.githubusercontent.com/66874403/165567442-f2beae44-83f6-4276-a227-21093bbe50de.png)

**Comment by ZakJudges** [comment]
@Tum1370 The red dot sight for that weapon was removed due to another bug. 

@LeeBamberTGC Just checking if the cross-hair red dot was supposed to be added in it's place? Or if we are just waiting until the weapon is re-modelled to add it back in?

**Comment by Tum1370** [comment]
@ZakJudges @LeeBamberTGC 
Ah ok. 
Ye it needs adding back to make the gun useable. 

Thanks

**Comment by Tum1370** [comment]
:( No red dot on latest Friday update, and the compact rifle is what i based my levels all on.
Now its a pointless gun without a red dot on the scope :(

**Comment by LeeBamberTGC** [comment]
@Tum1370 Leave it with me, now assigned to me and Lee has a plan :)

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Hi, Do you have any more news on a new red dot or scope fix for the compact rifle please ?
Its hard to Test a game that just has a blank scope.

**Comment by LeeBamberTGC** [comment]
@ZakJudges I know we mentioned the new cross hair red dot does not look right now, but see if you can add an offset to the new dot so it centers on the weapons scope. The new cross hair works great for zoomed weapons, but I think it could be extended to allow for these types of red dot markers too (as they point directly at the target). The old method of rendering a quad off in the middle distance and then textured had some flaws, not least that the dot did not represrnt the target if the weapon was animating too much.  It is the camera direction that determines the final hit location.

**Comment by ZakJudges** [comment]
@LeeBamberTGC Could you add this to the build, which will add a red dot crosshair to the Compact Assault Rifle: 
[gamecore.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8679079/gamecore.zip)

Regarding the offset, what approach do you suggest I take to centre the cross-hair based on the movement of the scope? :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges It can be a forced value stored in the GUNSPEC so can be weapon specific to adjust the cross hair. It does not have to follow the scope for V1, and we will tie it into the animation bone position for a V2 implementation with some blending. The main thing is that the red dot is where the bullet goes for now.

**Comment by Tum1370** [comment]
On the latest build, the RED DOT is back, but it actually appears before you have the scope raised. 
The moment you press the right mouse button the red dot appears, before the scope.

**Comment by Tum1370** [comment]
This has been fixed, Will close this issue.
