### ISSUE TITLE
GameGuru MAX - Bug - Changing Shadow Quantity and Shadow Resolution in Editor Does not Carry Over to Test Game

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2989]
If you change the Shadow Quantity and Quality in the editor:

https://user-images.githubusercontent.com/36735507/165629239-27df6dd7-21b8-4596-b8da-383498b7e8b6.mp4

It does not carry over to the editor and you have to use TabTab to change it again in Test Game:

https://user-images.githubusercontent.com/36735507/165629317-a75b0cc7-6e0f-484b-aac8-47b85e9b5d36.mp4

This is as of today's experimental build.

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Thanks for reporting this issue, this has been fixed on will be in the next update :)

**Comment by MonkeyFrogStudio** [comment]
Works on my end! Thanks for the fix!!!
