### ISSUE TITLE
RunTime Error 7018() - Request for Steam Key

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#2992]
Wasn't sure if I needed to make this a new issue, I commented already in this thread:
https://github.com/TheGameCreators/GameGuruRepo/issues/2835

I am getting this (7018) error when either loading a demo level or trying to add an asset to a new map. I sent Rick an email to get a Steam Key, as instructed in the other topic.

Not sure if it's relevant, but this time around I installed GGM on my HDD, instead of my C/OS drive, because my SSD was getting full, and now I'm getting this error. I only installed the 2 options ticked by default in the installer.

**Comment by Kravenwolf** [comment]
Hi Rick,

This appears to have solved the issue. I can now play/test any of the demo games without issue, and add any items from the asset library into a level.

Thanks!

**Comment by rvanner** [comment]
Good to hear!
