### ISSUE TITLE
error on Ammo  ( latest experimental )

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2994]
Just downloaded the latest to find this pops up on most of demos with weapons.

![ammo](https://user-images.githubusercontent.com/35708217/165860586-ff2f2aa6-e6ba-4ded-bb04-02b0983ed872.png)

**Comment by 3coms** [comment]
I've got it when loading the Disruption demo.
![disruption_ammo_error_GGMax_EA_pic01](https://user-images.githubusercontent.com/47690174/165870033-b236719a-415d-4ad2-8fc9-ee7d4074b2a7.png)

**Comment by Necrym59** [comment]
Try this
[ammo_fixed.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8587601/ammo_fixed.zip)

**Comment by synchromesh62** [comment]
> New AMMO script fixes the latest build for this morning.

This seems to be fixed for me .. Nice and fast fix thanks.
I will check with 3com and if his is ok i will close it :)
