### ISSUE TITLE
GameGuruMax Crash

### ISSUE THREAD

**Issue by shanenine** [TheGameCreators/GameGuruRepo#2996]
Hello All, I continue to have issues getting Game Guru Max to load. I've deleted old, downloaded new, took a break came back downloaded newest early release version, changed set up file in VR section to from 3 to 0 but nothing I do seams to work. In the  Guru Map editor text file it always seams to stop at the same phrase ": Guru Map Editor Loop Starts                              S:0MB   V: (4106,0)" I attached my computer specs and a copy of map editor text. I believe there has to be a way for it to run on this computer I just don't know what else to try. I have a post in the forum and have got great help there but not the fix just yet and when I google the issue with text phrase there are multiple persons who have had the same issue. Any help would be appreciated. Thank you

[Guru-MapEditor2.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8587823/Guru-MapEditor2.txt)
[device info.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8587825/device.info.txt)

u

**Comment by plemsoft** [comment]
@shanenine Thanks for reporting this issue, looking at your Guru-MapEditor.txt it looks like a older version, what version are you using ? , also could you try to install the latest version and generate a new "Guru-MapEditor.txt" here , thanks for your help :)

**Comment by shanenine** [comment]
Hello, Updated to newest release version 2022.04.29 and it still crashed. I attached the new map editor text below. 

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8595628/Guru-MapEditor.log)

**Comment by plemsoft** [comment]
@shanenine What is the last thing you see on screen before it crash ? if possible could you make a video of the crash , Thanks for your help :)

**Comment by shanenine** [comment]
Hello, I get a window that say Game Guru Max early access loading that stays for about 8 seconds then nothing. No error message or anything else just crashes. Attached is the map editor file it just made ends at same place still.
Thank you

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8603982/Guru-MapEditor.log)
.

**Comment by shanenine** [comment]
Well I believe I have figured out my problem, it doesn't make since but I did get Game Guru to load. It appears that if I have head phones and mic plugged into front of computer game guru max will load. If I remove the head phones it goes back to not loading. Weird?
