### ISSUE TITLE
Group Icon is not correct

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2999]
I made a group and the icon looks messed up. Maybe due to recent changes to how the object library rendering is done;
![image](https://user-images.githubusercontent.com/1503593/165904222-2ce3ed37-8c37-4823-bed4-01372734f004.png)

**Comment by plemsoft** [comment]
@rvanner Could you try it in the latest EXP, i do not see it here and you might have the test version i sent you yesterday :)

**Comment by rvanner** [comment]
Still doing it!
![image](https://user-images.githubusercontent.com/1503593/165927363-51d6d7b9-587e-4299-bb7c-611a5b6de696.png)
