### ISSUE TITLE
Gloss effect test shows good diffusement range for highlight between glossy and matte surfaces

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#3]
However, the highlight strength seems the same for both min and max levels. I would not expect that matte areas would have as bright of a highlight as max gloss areas.

![image](https://user-images.githubusercontent.com/5113534/34998661-97a41354-fad7-11e7-852e-5c910b4e62b0.png)

**Comment by plemsoft** [comment]
Yes it should and do, not sure why it is so intense in this screenshot is there more light sources , or is it the tab-tab settings ?

![pbr-specular-gloss](https://user-images.githubusercontent.com/18662417/35279336-1eae6244-004d-11e8-88c9-b33d8a5a3dd0.png)

The gloss control how light is spread out on the object, when you have a glossy material the light is concentrated in a small area of the object, then when you lower the gloss until you have a matte material the "same" light is spread out on the object on a large area , so you nearly cant see it.

Perhaps you could test if this comes from any of the tab-tab settings ?
