### ISSUE TITLE
Camry36PL (GAMEGURU) ERROR

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#30]
Oto mapa temat związany z komentarzem z filmu: 

https://www.youtube.com/watch?v=A-_CHu7M8vs&feature=youtu.be

Grę udało się teraz zapisać poza grą lecz te skrypty nadal nie działają (Udało się utworzyć gotowy produkt) 

[test.zip](https://github.com/LeeBamberTGC/GameGuruRepo/files/1648330/test.zip)

**Comment by Teabone3** [comment]
Translated:

> Here is the topic map related to the comment from the movie:
> 
> The game has now been saved outside the game but these scripts still do not work (We've managed to create a finished product)

**Comment by LeeBamberTGC** [comment]
This was a bug that caused the popup text during the save step to enter an infinite loop (waiting for the IDE to confirm the text was shown but never did). This has been fixed in the latest PP March build which you are welcome to confirm.
