### ISSUE TITLE
SSAO Flickering Issue

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3001]
When SSAO is enabled, buildings flicker as you get close to them:

https://user-images.githubusercontent.com/32545391/165911675-3a17fbd0-cd96-49d5-bd2f-225d18190675.mp4

[testlevel.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8589377/testlevel.zip)

**Comment by LeeBamberTGC** [comment]
NOTE: Fixed many moons ago (an improvement), but it will never be pixel perfect given how SSAO works.
