### ISSUE TITLE
[MAX] g_Entity[e]['plrvisible'] only returns 1 for first character

### ISSUE THREAD

**Issue by smallg2020** [TheGameCreators/GameGuruRepo#3004]
seems like the AI vision is bugged, g_Entity[e]['plrvisible'] only returns 1 for the first character, all others are returning 0
same for the stock scripts or custom
[https://youtu.be/O3KRli-0X4o](url)

```
--DESCRIPTION: test player visible to this entity

function canseeplayer_properties(e)

end 

function canseeplayer_init(e)
	SetAnimationName(e,"idle")
	LoopAnimation(e)
end 

function canseeplayer_main(e)
	LookAtPlayer(e,10)
	GetEntityPlayerVisibility(e)
	local csp = g_Entity[e].plrvisible
	PromptLocal(e,"g_Entity[e].plrvisible = "..csp)
end
```
[canseeplayer.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8590454/canseeplayer.zip)

p.s. it would be nice if we can also make the check optionally respect the view range and cone

**Comment by LeeBamberTGC** [comment]
@smallg2020 Fixed many moons ago with several overhauls of how line of sight visibility is handled and data passed to the scripts.
