### ISSUE TITLE
GG Max - Bug - Developer Settings - Use Key and If Used options

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3005]
Just testing the "Use Key" and "If Used" options in the developer settings.
As you can see from the screenshots, The door name is TESTDOOR, The "Use Key" is set to TESTDOOR. And on the big key the "If Used" is set to TESTDOOR.
But the door remains locked after picking up the key.

![DoorTest](https://user-images.githubusercontent.com/66874403/165961211-5c1f2994-1307-4fc2-94bd-ee043f24e55b.png)

![DoorTest 1](https://user-images.githubusercontent.com/66874403/165961409-760ae050-0a3c-43cc-af17-4e4b902c083d.png)

![image](https://user-images.githubusercontent.com/66874403/165961536-98c5dfe3-26b6-4123-913c-6d38e45364d5.png)

![image](https://user-images.githubusercontent.com/66874403/165961586-5ddad649-6307-4be7-88ba-5e6065afb154.png)

**Comment by Necrym59** [comment]
Why arnt you using the fps logic connection.

**Comment by Tum1370** [comment]
Because after you use 8 for one door, it stopped working, So i gave this a go to see if it worked.
And it does not work, so it needed reporting.

**Comment by LeeBamberTGC** [comment]
@Tum1370 New door and key scripts in stock next EXP build. @Necrym59 Check out the latest versions of these scripts for your own collection
