### ISSUE TITLE
GG Max - Request - Initial Standalone Menu Screen - Needs settings options on First menu

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3006]
I created a standalone for a level for my friend to test.
When he tested it, The first thing he mentioned was that he had no options to change the graphic settings, and ended up going looking in to the folder and setup configuration.

Maybe its a good idea to add all the setting options on to the first menu page you start at when loading in to the game, as currently you only see START, LOAD GAME, ABOUT, and  QUIT GAME.

**Comment by ArgentArts** [comment]
Requested here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2796

And requested more Storyboard flexibility here as well:

https://github.com/TheGameCreators/GameGuruRepo/issues/2870

**Comment by Necrym59** [comment]
Do you actually read other posts first.

**Comment by Tum1370** [comment]
No, i dont really go through looking at every post.
But the more people who report the issues, is better.

**Comment by Necrym59** [comment]
Just reporting for the sake of it just clutters up the board and consumes the devs time sifting through the repeats - check if possible if the problem has been reported before and add your comment to that post, pretty simple really.

**Comment by Tum1370** [comment]
No, i dont really go through looking at every post.
But the more people who report the issues, is better.
