### ISSUE TITLE
GameGuru Max - 10 Suggestions And Enhancements

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3007]
It was suggested to me that i should post my list of suggestions/enhancements here, created a account just to post this, it will be for the most part a copy and paste of what i posted on Steam, but with a few additions - apologies if some of these have already been suggested, but here we go:

1. Vehicles:
Considering how big these levels/maps can be, adding vehicles is something i see as a must, starting with off-road vehicles as we don't have any urban areas or cityscapes to create at the moment, also boats, helicopters, motorcycles and et cetera.

2. Improved Swimming:
Adding a full swimming mechanic is another thing that you NEED to add, it's a classic FPS staple and also necessary for those who want to make underwater sections for their games.

3. Caves/Mines:
Being able to make holes in hills and mountains and shaping out caves, this is something that is currently impossible without a lot of hassle, but would add more flexibility in level design, you could also make bunkers, and whole underground sections with this mechanic. (can also work in tandem with point 2.)

4. Waterfalls/Scalable Water Zones:
Being able to add waterfalls and water above the already set level would add another layer of depth to level creation, this does not have to be extremely complicated, for instance the water could function as a square or rectangular object which you then can scale in size, make sure it has the same properties as the regular water so you can for instance swim in it, waterfalls could also work the same way as scalable objects, and working together could add a lot of level/map detail (a pond on top of a mountain creating a waterfall for instance). 

5. Friendly NPC's/More NPC Behaviors:
i hope you're making it possible to have friendly NPC's that you can toggle to follow you, or fight for you. As an example i personally want to create games in vein of the original Rainbow Six/Ghost Recon, so this would be a necessity, but could also obviously come in handy for later additions such as the RPG game type.

6. Improved Ragdolls/Animations:
The current ragdolls and death animations have a tendency to bug out, like characters in a death animation sticking out of the ground, or clipping through it, combining the death animations and ragdolls (characters ragdoll at the end of a death animation) could help alleviate some of the more awkward bugs that occur upon an NPC's death.

7. Blood & Gore: 
I'd like this added simply for the sake of immersion, blood on walls, blood pooling and trails, this is especially good for horror games, or games with a more mature theme, (maybe even toggle-able dismemberment?)

8. Things You May Already Plan On Adding:
A few more weapons like a sniper rifle, rocket launcher (with new death animations for explosions), dual wielding weaponry, SMG's, and grenades for a basic FPC weapon set, you could add different types of weapons for different settings through DLC/Expansion Packs.

9. More Assets/Environment Types: 
Things on my (and i think most peoples) personal wishlist include urban territories, cityscapes, a variety of sci-fi styles, post-apocalyptic, cyberpunk/steampunk/biopunk, western, pirate (would be fun with added vehicles such as functioning ships or boats)
 
10. Completely customizable assets:
This would involve something similar to the character creation menu, basically you could take a wall (as an example) and re-decorate certain parts, maybe repaint a wall texture, or a certain section of the wall or you could just simply re-texture it by uploading a personal image file, this could then be saved as a completely separate piece from the asset pack in the user folder as a unique wall (in this instance, could also work with most pieces in an asset pack, like chairs, tables, floors... maybe even making your own weapon skins?)

Hope some of these are useful, and good luck on further progression, having a lot of fun so far.

**Comment by Lemuripest93** [comment]
Gotcha, will repost these as separate posts.

**Comment by Lemuripest93** [comment]
Feel free to remove this post/thread.

**Comment by Necrym59** [comment]
All been asked for before, dont know why people never read though previous posts.
