### ISSUE TITLE
Respawn issue & AI Fire rate issue.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#301]
https://vimeo.com/280065221

The video uses stock soldier with respawning script (basically the same functionality as the one in smallg's script thread on the forums.

Problem 1)  On respawning the character is 'washed out' or too bright.

Problem 2) The 'fire rate' of the AI character is way too high and does not respond to the 'fire rate' parameter setting.   I tried altering a custom character script to call the FireWeapon Lua command only once every two seconds and discovered that this just makes the AI fire erratically, i.e. once in a blue moon, I would expect the engine to respond instantly to the FireWeapon command unless it is too soon since the last shot depending on the 'fire rate' setting in the parameters, so you can control the firing rate from within a script, but this seems impossible at present.

Running latest Beta build by the way (the 'Monster'   2018-07.13 one).

**Comment by AmenMoses** [comment]
I think these two problems are related, if I change the 'specular' setting in the parameters for the character problem 1) changes, i.e. the 'washed out' look becomes a 'too dark' problem and the character starts behaving strangely, for example walks backwards.

I suspect that somehow the 'parameter' settings are being applied incorrectly because the 'fire rate' setting is just below the specular one!

**Comment by AlexKVideos1** [comment]
If you give any character a semi auto gun, it just ends up becoming full auto, terrible if you want to make a sniper. Must need fix!

**Comment by plemsoft** [comment]
@AmenMoses Thanks for reporting this,

This has been fixed and are ready from the next update :)

Also added lua command FireWeaponInstant()
