### ISSUE TITLE
GameGuru Max - Suggestions/Enhancements 6/10 - Improved Ragdolls/Animations

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3013]
The current ragdolls and death animations have a tendency to bug out, like characters in a death animation sticking out of the ground, or clipping through it, combining the death animations and ragdolls (characters ragdoll at the end of a death animation) could help alleviate some of the more awkward bugs that occur upon an NPC's death.

Alternatively just either stick with more animations and have the bodies align with the environment upon death, similarly to the original 'Halo' or 'Soldier of Fortune 2' or just overhaul the entire ragdoll skeleton to be less janky.

**Comment by Necrym59** [comment]
This is not Halo or SOF, its an editor, you can of course script extra animations yourself if you not happy with the ones supplied until they get around to doing some extra options later on.

**Comment by Lemuripest93** [comment]
Closing this one in favor of #3654, as active ragdolls are far more attractive as an option.
