### ISSUE TITLE
Collision/Physics selection feature request

### ISSUE THREAD

**Issue by Pekuru** [TheGameCreators/GameGuruRepo#3015]
Currently, you're tied to a set amount of Collision types and how to implement your own is a bit unclear. Suggestion is to add a extra dropdown/option for collision selection where you can manually select a .obj file to serve as your collision model.

**Comment by Necrym59** [comment]
Its already in there just create an OBJ file for the colision model of the model you have imported and place in the same folder it will be used as the collision model automatically when you select convex hull.

**Comment by ZakJudges** [comment]
Closing this issue as since the issue was created, a new "collision mesh" collision type has been added.
