### ISSUE TITLE
GameGuru Max - Suggestions/Enhancements 9/10 - Asset Packs/Environments

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3017]
Some assets or environments i think should be included in future asset packs and expansions: urban territories, cityscapes, a variety of sci-fi styles, post-apocalyptic, cyberpunk/steampunk/biopunk, western, pirate, and (dark) fantasy styles.

**Comment by rvanner** [comment]
Thanks for your suggestions. We will build new packs as we progress and offer more choices.

**Comment by casigus** [comment]
you  can literally import  models into max,  and the engine is really  really    easy to take a model,  import, and bam you have building. plus this  isn't really a bug, its a request, might I suggest posting  ideas  in  the forums rather than filling  up the bug reporting with things that aren't bugs. I say  this  because  the devs  have  alot of things to look through, and  people will also come  to see  if  other people are  experiencing the same problem. I'm seeing alot of SUGGESTIONS  posts of  late. '

**Comment by Necrym59** [comment]
Yes lots instant expert suggestions and they wont be happy until it slices bread and makes coffee it seems

**Comment by Lemuripest93** [comment]
I uploaded my posts here because it was suggested to me by one of the developers on Steam that i'd do so because he was in agreement with another user that the list was useful, not here to overwork the devs - not to cause any problems, this is the site i was linked to post to, this is the site i posted to, end of story.

**Comment by synchromesh62** [comment]
> I uploaded my posts here because it was suggested to me by one of the developers on Steam that i'd do so because he was in agreement with another user that the list was useful, not here to overwork the devs - not to cause any problems, this is the site i was linked to post to, this is the site i posted to, end of story.

I can confirm i recommended Lemuripest93 to post his requests here which is also what this repository is for and it was then requested by another member of the the team to break them up and post them individually for easier reading. 
There were some good suggestions worth looking at for future work.

**Comment by casigus** [comment]
well that  is fair sync. thanks for  the clarification :)

**Comment by casigus** [comment]
and the ideas    are  good, amazing fantasttic  well  thought out  ideas!  :D

**Comment by casigus** [comment]
also there  a  section  on the  game guru  forums that  have a tonne of free media,   including  scripts and  models , some work with max:  https://forum.game-guru.com/board/25

**Comment by Necrym59** [comment]
Im all for suggestions, you do realise that most of these suggestions have already been asked for its better if people take the trouble to read other posts and add to those rather than make clutter with a lot of extra posts.

**Comment by Lemuripest93** [comment]
@Necrym59 Repeat suggestions and ideas can also be read as higher demand, if TGC works like most other studios - then this is simply being broken down into useful data.

**Comment by Lemuripest93** [comment]
DLC packs have been added for a while now and will continue to come out, so no point in this staying open.
