### ISSUE TITLE
Transparency Bug

### ISSUE THREAD

**Issue by Maro32** [TheGameCreators/GameGuruRepo#3020]
The rocks around the waterfall become shadowless transparent items when I hover the cursor over them.

[Transparency Bug.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8592299/Transparency.Bug.zip)

**Comment by plemsoft** [comment]
@Maro32 Thanks for reporting this issue, and sorry for the late reply , i just tested your level and did not see any problems with the shadows , but i also did not see a waterfall ? , anyway the level you sent looks like a update must have fixed it, it looked like it should. Please let me know if its also fixed for you , Thanks for your help :)
