### ISSUE TITLE
Zombies In The Floor

### ISSUE THREAD

**Issue by relishrompgames** [TheGameCreators/GameGuruRepo#3021]
I used the stock warehouse, placed some zombies and their feet are in the floor.
![floor](https://user-images.githubusercontent.com/98617471/165987684-3676d4f3-89f5-42a6-911d-2ee65e9f9faa.jpg)

**Comment by LeeBamberTGC** [comment]
@relishrompgames In the latest build, characters now auto scan for floor and ensure they are on it rather than in it.
