### ISSUE TITLE
GameGuru MAX - Request - MAX to Remember Settings for Project on Re-Open

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3023]
I'm sure that most of us (none of us?) complete a game in a day. We often will close MAX and re-open it to continue working on a project, doing so day after day. But when we load our projects back into MAX we discover that whatever settings we were using, such as Grid settings, Developer Mode settings, etc., are completely forgotten and we have to go through the trouble of having to reset everything all over again.

I would like to request that MAX remembers our project settings after a save and reloads them when we re-open a project. If the end-user had Enable Grid Mode checked and Use Grid Position ticked, Grid Offset set to 0.00 for X and Y and Grid Size set to 32.0 for X and Y, then it should re-open the project with these exact settings unless the end-user changes them. As you can see, that's a lot to have to change every time you open MAX.

Please consider adding this feature to MAX. Thanks. :)

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, I have added saving/loading of the grid settings to prevent them being reset. Your choice for "Show Additional Developer Options" will also be retained. I have uploaded a new Steam experimental with the changes

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, are you happy for this issue to be closed? :)

**Comment by MonkeyFrogStudio** [comment]
Yes! Sorry I've not closed it yet. Will do now. :)
