### ISSUE TITLE
GGMAX - Invisible and Invisible prompt behavior

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3027]
If interested here is an amalgamated updated Invisible behaviour. Includes the user selectable prompt, range and collision options all in one behaviour for your consideration.
[invisible.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8596452/invisible.zip)

**Comment by Hamada880** [comment]
Will give that a try as I was searching for this feature around GGMax. Thanks so much for sharing.

**Comment by Hamada880** [comment]
Have to say amazing work on that script. Thanks for the effort and time :)
