### ISSUE TITLE
My Cursor on screen

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3029]
I have just rendered my test game as a stand alone for GGM and for some reason my cursor appears on the screen and I can't look around. Yet the right button still lets me aim and the keys still let me move?

I've tried Tab & Enter, Alt & Enter, Tab & Alt, but it still persists. I even switched off one screen on my dual display and it still happens?

Any Ideas????

**Comment by ZakJudges** [comment]
Hi @Curiosityuk, apologies for the late response. I have not been able to reproduce this issue. Do you still experience it in the latest builds?
