### ISSUE TITLE
SMART   objects  bug

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3030]
Hello!

smart objects seam to be having  some   issues with custom  assets,  they save fine but when you try to  place them back in, well all sorts of magical   weirds happen:

![image](https://user-images.githubusercontent.com/68471279/166157120-973a8c06-052f-47be-9b61-1a57d340d3e3.png)

https://www.youtube.com/watch?v=8-ZDfniHqpM

**Comment by ZakJudges** [comment]
Note: could not reproduce in latest EXP build. If I remember correctly, this one was fixed last year when the Building Editor was added to Max. Was caused by objects that were rotated in a group having their rotation reset to 0 on load
