### ISSUE TITLE
Standalone issue : program can't start because api-ms-win-shcore-scaling-l1-1-1-dll is missing

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3044]
User reported on Steam anyone he shares his game with **( who does not have Max installed )** gets this error.
**this program can't start because api-ms-win-shcore-scaling-l1-1-1-dll is missing**
A missing file perhaps ?

**Comment by ZakJudges** [comment]
Hi @synchromesh62, I did a search but we do not include that file with Max. Have you seen any more reports of this missing DLL recently? :)

From looking online, it looks to be one that ships with Windows by default

**Comment by synchromesh62** [comment]
> Hi @synchromesh62, I did a search but we do not include that file with Max. Have you seen any more reports of this missing DLL recently? :)
> 
> From looking online, it looks to be one that ships with Windows by default

Hi Zak 
I have not seen any further reports of this so i will close it down
