### ISSUE TITLE
Parrots occassionally freezing in mid flight

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3045]
Not sure when this started, I only spotted it today, but the parrots are now occasionally freezing in mid flight.

https://user-images.githubusercontent.com/99803873/166878363-25bdb93d-7142-44e8-9c30-cc5b82068a1b.mp4

That's parrot green, but also seen on parrot.

**Comment by synchromesh62** [comment]
To high a Polly count is my guess.
Sorry couldnt resist :)

**Comment by davetgc** [comment]
Please try harder :)

**Comment by AmenMoses** [comment]
It's probably dead.

When the health drops to 0 the script is no longer executed.

**Comment by Necrym59** [comment]
its just kipping, beautiful plumage..

**Comment by rvanner** [comment]
Flying critters need to fall to the ground when damaged (explosion hits them).

**Comment by AmenMoses** [comment]
Or just give them a heap of health so they can fly away and live happily ever after.

**Comment by AmenMoses** [comment]
Then the script becomes much more complex, plus there are no decent death poses for the birds, needs something like the mammals where the bird would be sort of draped on the ground.

**Comment by ZakJudges** [comment]
Hi all, I have added a fix for this which should be in the next experimental build, later today. Birds are now given loads of health to prevent death and the freeze shown above. If the script is ever updated with a death animation or similar, I will remove this fix
