### ISSUE TITLE
Environmental menus not opening in latest experimental build

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3046]
Clicking on the post-processing/filter/etc menus only opens them briefly.

https://user-images.githubusercontent.com/99803873/166885673-c94943f9-7c5f-4748-b13a-21237e7451e5.mp4

**Comment by MonkeyFrogStudio** [comment]
Interesting! I am not experiencing this with the latest experimental build. All menus are opening fine for me.

**Comment by davetgc** [comment]
I had to revert to an earlier build today. Sounds like a strange one.

**Comment by synchromesh62** [comment]
On the very odd occasion when i click add the window opens as a very narrow bar that you cannot do much with but clicking the Reset Interface sorts it ... Maybe try that first next time .. It just resets the visual no other settings.
 
![reset](https://user-images.githubusercontent.com/35708217/166919585-53ee54fa-aaef-43c6-ad04-d2727b2c8b62.png)

**Comment by rvanner** [comment]
I am not seeing this on my build. Maybe verify your files?

**Comment by davetgc** [comment]
Verifying files has fixed this one. Thanks.

**Comment by Necrym59** [comment]
I vae had that, ive found dont have an object selected when you do it seems to work.
