### ISSUE TITLE
GameGuru MAX - Request - Parallax Occlusion Mapping for Materials

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3049]
I would love to see Parallax Occlusion Mapping added to MAX at some point. It's an amazing way to add details to models without adding geometry. If used wisely, such as creating a texture atlas or a single material sheet of "decals" or "atlases" these details can be used an all sorts of models all over a level to add immense amounts of details with little overhead (again, if used wisely). Here's an example of a sci-fi crate I made in Blender that uses a parallax occlusion material for all the details:

https://user-images.githubusercontent.com/36735507/167040453-aedda8fe-4878-4ef6-bcd5-f06c764c8831.mp4

Here's a still of the crate:
![paralax1](https://user-images.githubusercontent.com/36735507/167040509-02e76302-2a3e-43d1-b10e-28d446ee0403.png)

And this shows which parts are the parallax occlusion pieces:
![paralax3](https://user-images.githubusercontent.com/36735507/167040792-9a61e5af-2acf-4db9-9f6a-da82e4e003ad.png)

**Comment by Necrym59** [comment]
Parallax Occlusion Mapping should be implemented, it is in nearly all the engines now, no point in being left behind now. Its overhead is small if used wisely especially on object and decals. Im sure the wiked engine would have this capability. The effects are remarkable and effective especially with dynamic lighting .
![sample_decal](https://user-images.githubusercontent.com/95015657/167041345-de0234d8-c5db-4d32-b4fd-88408c96df29.gif)
even used on standard areas it can make vast differences to the overall game giving AAA quality.
![paralax_sample](https://user-images.githubusercontent.com/95015657/167041396-dfd798c3-e9b0-43bf-a349-fe53d6958ebe.png)

**Comment by MonkeyFrogStudio** [comment]
Wicked Engine already has Parallax Occlusion Mapping:

https://camo.githubusercontent.com/50bd9b992205e0dc49ce57d1857d63707dd84f6062fdb02a20bd17e9e624010e/68747470733a2f2f747572616e737a6b696a2e66696c65732e776f726470726573732e636f6d2f323031392f30312f706f6d2e706e67

**Comment by fearlesswee** [comment]
Parallax occlusion mapping would especially be super beneficial to terrain, which can be pretty flat and "smooth" feeling atm.

**Comment by MonkeyFrogStudio** [comment]
@fearlesswee From what I understand, parallax occlusion mapping is one of those things that you have to use carefully because it can hit hit the engine pretty hard if used too heavily. Instead, they need to use PBR materials on the terrain (if they're not) with a sufficient normal map and nice roughness, etc., to get the terrain to look less "smooth".

**Comment by earthling45** [comment]
POM is very suiting for terrain and walls. FS22 now uses (though done ugly in certain areas) POM for ground and walls. The fps even on 3440x1440 never dip below 60 fps.

But i see what you are getting at, i did something similar a few years ago when we were suposed to get POM in classic. :)

Only normal map
![FLjL4rl](https://user-images.githubusercontent.com/35744254/167150199-530c6a5d-0958-4ef6-b159-3a83b1657945.png)

with heightmap
![elyobZr](https://user-images.githubusercontent.com/35744254/167150256-d4e7597d-245d-453e-a988-a96a43fecec4.png)

Yet i wonder if those extra polygons are still going to matter much if displacement is used.
This question because of those multi million polygon structures with which 3com has been testing. :)

**Comment by MonkeyFrogStudio** [comment]
> Yet i wonder if those extra polygons are still going to matter much if displacement is used.

Parallax Occlusion Mapping doesn't create any extra polygons. It's purely a texture trick:

"Parallax Mapping refers to the offsetting of the texture coordinates and Occlusion refers to the ability to shadow the parallaxed result accurately. Parallax Occlusion Mapping, or POM for short, works by taking iterative steps along the height field checking for intersections."

**Comment by earthling45** [comment]
> Parallax Occlusion Mapping should be implemented, it is in nearly all the engines now, (god even minecraft are using it) no point in being left behind now. Its overhead is small if used wisely especially on object and decals. Im sure the wiked engine would have this capability. The effects are remarkable and effective especially with dynamic lighting . ![sample_decal](https://user-images.githubusercontent.com/95015657/167041345-de0234d8-c5db-4d32-b4fd-88408c96df29.gif) even used on standard areas it can make vast differences to the overall game giving AAA quality. ![paralax_sample](https://user-images.githubusercontent.com/95015657/167041396-dfd798c3-e9b0-43bf-a349-fe53d6958ebe.png)

The latter example is displacement i think, not parallax. :)

**Comment by earthling45** [comment]
> > Yet i wonder if those extra polygons are still going to matter much if displacement is used.
> 
> Parallax Occlusion Mapping doesn't create any extra polygons. It's purely a texture trick:
> 
> "Parallax Mapping refers to the offsetting of the texture coordinates and Occlusion refers to the ability to shadow the parallaxed result accurately. Parallax Occlusion Mapping, or POM for short, works by taking iterative steps along the height field checking for intersections."
> 
> It's more like a normal map on steroids, adding additional "height" information for more accurate lighting and deeper/higher effects. However, it still has very similar limitations (i.e. viewed from severe angles will reveal the surface is actually flat, etc.) and is very GPU intensive, so should be used wisely.

I know but POM requires extra passes whereas displacement adds extra geometry, which is preferable.

**Comment by cybernescence** [comment]
![parallax occlusion with soft shadows](https://user-images.githubusercontent.com/35750023/183993503-43b3ba27-e750-4762-99cb-80fea92c2865.GIF)
Also hoping to get this into GG Classic, prototype with soft shadows in the gif (the test cube has only 6 planes, no other geometry)

**Comment by LeeBamberTGC** [comment]
@cybernescence Looks fab!!  I notice as well, might be my imagination, but are you moving the SUN in Classic? :)
