### ISSUE TITLE
GGMAX - FOV not working

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3052]
FOV does not work in the graphics menu in standalone games nor by lua commands. It only seems to work from the slider in camera settings in test mode.

**Comment by ZakJudges** [comment]
Hi @Necrym59, I have added a fix which should sort this issue for you. I will post here when it's in a build you can test to confirm the fix. Thanks for reporting :)

**Comment by Necrym59** [comment]
Seems ok but all the scripts with FOV are broken now i have to find whats different about it

**Comment by Necrym59** [comment]
Hi Zac FOV is working ok just ' g_MouseWheel ' is broken so i cant adjust FOV in scripts except by keyscans can you verify this.
Thanks

**Comment by Necrym59** [comment]
Attached is a testFOV script that used to work with the mousewheel
[testfov.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8705547/testfov.zip)

**Comment by ZakJudges** [comment]
Hi @Necrym59, I got rid of start_wheel and instead checked if the mouse was greater than or less than 0, which seemed to sort the issue
```
if g_MouseWheel < start_wheel then 
	mod = mod - 1
	start_wheel = g_MouseWheel
elseif g_MouseWheel > start_wheel then 
	mod = mod + 1
	start_wheel = g_MouseWheel
end 
```
to this: 
```
if g_MouseWheel < 0 then 
	mod = mod - 1
elseif g_MouseWheel > 0 then 
	mod = mod + 1
end 
```

**Comment by Necrym59** [comment]
Oh thanks for that Zac,  although that does work it seems the reporting from g_MouseWheel has changed since i had done the original script, it doesnt seem to be reporting back increments at all, that appears to be the problem, it may be an issue and need to be looked into.

**Comment by ZakJudges** [comment]
@Necrym59 Thanks, would you be able to start a new issue? Helps us track our bugs better :)

**Comment by Necrym59** [comment]
Ok will do..
Cheers
