### ISSUE TITLE
Height mapping

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#3053]
I think we are going to need a tutorial on Height Mapping and how we go back to importing it into Max, I have just made a map with 3D Mapper online generator,  of my local area and would like to try importing it into Max.

What do I need to do this. any advice would be great.

Thanks 
Nigel

**Comment by Necrym59** [comment]
what place did you do the map on

**Comment by Snage62** [comment]
Hi Necrym59
This is the site I used ( https://3d-mapper.com/_MAP/index.php? )  They charge 5$ for personal usage.

I will try the address you have provided, 
Thanks

**Comment by rvanner** [comment]
Tutorial released!
https://youtu.be/JhK_AlACJbU

I am sure there's more to learn re heightmaps. I'd suggest following the forum post about the competition where users will share their experiences too.
