### ISSUE TITLE
Games crash when run from the HUB

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#3054]
**User P. Hawse is having issues running MAX demos from the HUB**
I unplugged my TV and connected headphones. Then i ran a windows chkdsk /f on my c drive. that seemed to help now when i launch into the gamegurumax i can open the demos in the editor and play them from there.
I haven't tried anything in there except that and zooming out and moving around a bit. However if i try to launch any of the demos from the hub i crash immediately to the desktop no error or anything just a hard crash of the  software. 

Next I grabbed the very latest NVIDIA driver for my GPU installed it and rebooted.  I get the exact same crash to desktop trying to play any demo from the hub. And i can still play from inside the editor using the rocket icon or edit the level after the GPU driver update. So only the play demo from the hub is broken still. Any ideas ?

I have a windows 10 machine with an  intel i5 (6500) and an nvidia GTX 1650 (the model with 4gigs of ram)  32 gigs of ddr4 ram ( 2 x 16 gigs) there are 2 500 gig samsung evo SSD.

**Comment by ZakJudges** [comment]
cannot reproduce - but I do remember a similar issue that has since been fixed. It is likely that this one is also fixed
