### ISSUE TITLE
MAX BUG. Zombies can not be killed through a fence but can hurt player through it  and walk through it

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#3055]
Like the heading says Zombies can not be killed through a fence but they can and can walk through it see video.
The fence is From Max fence collection
[[Sz5KLUeSFJc](https://youtu.be/Sz5KLUeSFJc)](url)

**Comment by Pcskiller** [comment]
I have just tested the small concrete walls as well, it looks like as soon as the Zombies attack the player in the bite animation then they can  somehow go through the fence or the wall while they are biting the player. So i guess it will happen to any fence or wall that they can see over or see through the fence or wall

**Comment by Pcskiller** [comment]
made some more test see video  
[[Yr4RGqZIUJY](https://youtu.be/Yr4RGqZIUJY)](url)

**Comment by LeeBamberTGC** [comment]
@Pcskiller Made changes to script and zombie behavior, can no longer eat brains through fence, as player now needs to be much closer, and also fixed smaller issues of only attacking when have line of sight. Bear in mind some chain link fences have gaps, and you can shoot through the edges of these gaps (and likewise the zombies can hit you back). Also stopped the very slow creep in position when zombies seemingly idle.

**Comment by LeeBamberTGC** [comment]
@Pcskiller Is this still an issue, or has it been fixed. Will close soon :)

**Comment by Pcskiller** [comment]
Lee sorry for the late replay, i will test when i come from work, just give
me some time this afternoon.

**Comment by ZakJudges** [comment]
Closing this issue. If the problem persists, feel free to reopen. Thanks :)
