### ISSUE TITLE
trees appearing  that are not selected.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3060]
these lovely snowy   trees keep  spawning in no  matter  what you  select or unselect!

![image](https://user-images.githubusercontent.com/68471279/167229637-0d5ffa78-827b-4440-80f0-c7863b014b6d.png)

**Comment by rvanner** [comment]
@PaulSJ Can you look into this as a matter of urgency? It's very annoying and should not be happening. It's reported in other github reports too.

@casigus Nice looking level!

**Comment by ZakJudges** [comment]
@casigus Apologies for the late response to this. I remember fixing a nearly identical issue a long time ago. Could you confirm that you no longer experience this one? Thanks :)
