### ISSUE TITLE
GGMAX - Ammo behaviour Issue - Build 2022.05.06

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3061]
The current Ammo behaviours does not give the amount shown in the Ammo quantity field. The actual amount given is the Ammo amount brought in from the FPE, this quantity setting is found on the Developers Settings Panel and needs to move to the Behaviour section. Previously Refered to https://github.com/TheGameCreators/GameGuruRepo/issues/2923
Unless there are plans to replace that FPE quanity with a selectable one then the script needs changeing to evaluate which ammo pool the ammo has gone into giong into and adjust accordingly or a change to AddPlayerAmmo command to account for the qty.

**Comment by LeeBamberTGC** [comment]
@ZakJudges I recommend adding a new 'macro' to the LUA description scanner (we use this to look for <IfUsed> and <Sound0>, and when we find these in the description we expose them as part of the Behavior Properties component.  I think a new one called <Quantity> will do the trick nicely as I believe the quantity for ammo is a generic one, and could be used for other systems too.  Worth checking if the ammo value is specific to ammo or a generic qty value.

**Comment by ZakJudges** [comment]
@LeeBamberTGC I'm not too sure what you mean. Could you clarify what you want the new 'macro' to do? Should it just alter eleprof->quantity for the ammo? Thanks :)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Yep, allowing the behavior to edit eleprof->quantity directly will do it :)

**Comment by ZakJudges** [comment]
@LeeBamberTGC Added a new properties variable type: When "&" comes before the variable name, the corresponding eleprof variable will be found and pointed to for ImGui to alter. At the moment, the only eleprof variable you can specify is "quantity" but the system could support whatever variables we wish. The only restriction is that the name in the script matches the variable name on the C++ side (but is not case sensitive)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Works as charm in the latest build on EXP!!
