### ISSUE TITLE
GGMAX - Add Audio zone issue  - Build 2022.05.06

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3062]
After placing 3 Audio zones with 3 different sounds unusual events happen. 
1. Sometimes a sound is played that is not allocated to the zone used.
2. Sometimes no sound is played at all
3. Sometimes a sound allocated to zone 1 played in zone 3 but no sounds in 1 and 2
4. Same as point 3 but no sounds in 2 and 3 and sound played in 1 from another zone.
5. If the zones overlap or close proximity they dont work at all. 
This problem did not occur in previous versions.

**Comment by LeeBamberTGC** [comment]
@Necrym59 This was related to the waypoint zones corrupting and reusing waypoint references, causing all manner of strangeness. Waypoints no longer produce corrupt data and a level load stage cleans up any older bad ones.
