### ISSUE TITLE
GG Max - Bug ?? Fish resizing and movement 

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3065]
Is this a bug or as intended ?
When you place some fish in a pool, Even if you resize the fish, and place them near the surface of the water, They are always smaller again and at the bottom of the pool.
Some fish seem to swim properly, Others dont seem to swim at all.

Also just see a fish start at the top, then sink to the bottom and below the ground.

**Comment by AmenMoses** [comment]
The fish script randomly scales the fish! (that's not a bug)

Active entities get slammed to the terrain at the start for some reason. (I believe this is a MAX bug)

Define "swim properly", are they animating and not moving, moving and not animating, neither or something else?

There are some strange ray casting issues in MAX atm which could explain the last point.

**Comment by Tum1370** [comment]
@AmenMoses I will close this issue, When i tried this i was not aware how the script worked.
I have tested again on a new map and the fish were working correctly. I never messed around with fish size this time, expecting a very large fish to swim around lol
