### ISSUE TITLE
DSNI Weapon Illumination - Not Working?

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#307]
Hi all :)

So I be making a test level where you can defend yourself from those pesky Drones using the Quasar Gun.

In the previous PP this all worked fine, but in the monster update the illumination is not working.

This is a custom weapon - BSP QuasarGun. Anyone else have that weapon that can check?

Reliquia....

**Comment by Gladkhelek** [comment]
I have this same issue! Having a bunch of lights is awesome now, but now the lights won't show up on the model view of my gun, hands holding the firearm. When walking past the lights, they have no visual effect on the item at all, it wasn't like this before the update.

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting this,

Think i fixed that in another update , just in case a did a quick test:

![snapshot9](https://user-images.githubusercontent.com/18662417/60176876-d236fe80-9817-11e9-8e35-ce26845a8c97.jpg)

Looks fine now :)

**Comment by michaeloldman** [comment]
Yes, all appears good now - thanks.

Reliquia....
