### ISSUE TITLE
Sound fading not working correctly 

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#3070]
there seems to be a problem with the sound control.
1. If you place down a Zombie that starts off eating then you can hear it a mile away, the sound starts of to loud.
2. ' Any Npc that is talking while they are shooting , the sound do not fade out correctly if player is far away.
Maybe we can get a control slider over the fade sound per entity if the main control do not work.

**Comment by LeeBamberTGC** [comment]
@Pcskiller A recent fix solved the issue of the 3D sounds not working, that would appear as though distant sounds did not control the volume and direction properly. Resolved now.
