### ISSUE TITLE
GGMax - Feature Request - Move camera to selected object in hierarchy (like Unity)

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3071]
I'm working on my comp entry and have a very large terrain (~12km) and cannot find the location of my start marker, haha.

Something that is VERY useful when designing large levels in Unity (I'm sure Unreal does it, too) is the ability to see a list of all of the assets currently in a level (**including markers**) off to the side in a hierarchy (ex., "light1", "light26", "startmarker", etc.), and then being able to double click on one of those objects (in my case, the start marker), which will automatically move the camera to that location (to the model's origin, I assume) in the map so I can find it immediately.

In the meantime, it's back to searching my 12 square kilometer map for my start marker...

**Comment by MonkeyFrogStudio** [comment]
@Kravenwolf 

You can do this in MAX already. First, click the down arrow under Level Objects and select Detailed Object List:
![detailed](https://user-images.githubusercontent.com/36735507/167309771-bfcd92a9-6115-483f-8197-7b481e40b715.png)

You can then twirl down one of your objects (they are grouped by name) to select a particular one:
![detailed2](https://user-images.githubusercontent.com/36735507/167309845-c4664ffb-a390-4ddd-998e-6c7dfeac7497.png)

Double-clicking on it will instantly fly your view port to the object in your scene.

If you don't see the Detailed Object list in your drop down, then go to Edit>Settings. When the pop-up appears, go to the Advanced tab. Once there, tick the "Allow Selection of Detailed Objects List" box:

![detailed3](https://user-images.githubusercontent.com/36735507/167310016-bd3cae03-7954-46d3-8459-9d04f4a18a6a.png)

**Comment by Kravenwolf** [comment]
**@MonkeyFrogStudio**,

Thank you. Would not have expected such a useful feature like this to be buried away in the "advanced features" settings, so I just assumed it wasn't implemented and didn't bother to do any digging. Makes me wonder what else Max can do that I'm not aware of yet! Took a quick glance through the user manual (which I'll admit I didn't sift through up until today!), and didn't see anything covering this, either. Though I just skimmed through it.

**Simple fix might be something like this, there appears to be room for it:**
 
![dol](https://user-images.githubusercontent.com/103399301/167317263-293325b6-b7d2-49d6-b8fb-27b9405ce5aa.jpg)

**Comment by MonkeyFrogStudio** [comment]
Not sure that needs to be there. I think having it under the twirl down (where the arrow is) is fine (as a selection). It just doesn't need to be something that's either turned on or off via Developer's Features, imo (see this thread: https://github.com/TheGameCreators/GameGuruRepo/issues/3075 )

**Comment by Kravenwolf** [comment]
Yes, I've found it now. Where it is it fine as a dropdown, doesn't need a dedicated button as I previously suggested, IMO. But, yes, something about digging into the menus to enable "advanced" features is a bit counterintuitive to GGM's "ease-of-use" selling point. 

Maybe just a button over by the "RPG Games" button that toggles ALL of the advanced settings on and off? Or make advanced settings tabs red? Just a few suggestions.

**Comment by rvanner** [comment]
@Kravenwolf Glad you found it. I'll also add more advice in the user guide (maybe a tips section).
