### ISSUE TITLE
Automatic terrain alignment breaks down when I put a large and small object (a house and a barrel, a box)

### ISSUE THREAD

**Issue by janekste** [TheGameCreators/GameGuruRepo#3072]
Hello.
I found a strange problem. I put a model of the house. I put small objects next to the house. The result: the house is moving and the automatic smoothing of the terrain breaks down.

I recorded a video for you in which I show the problem from all sides. GameGuru MAX Build 2022.05.06
https://youtu.be/9oWYR5gYJmg

Thank you for your time.

![image](https://user-images.githubusercontent.com/55485525/167297436-b60e0fd5-4424-4e48-9ca5-6f3481bb63b9.png)

**Comment by LeeBamberTGC** [comment]
@janekste Looks to be fixed in the latest build, tried the building and dumpster and terrain responds correctly:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/1d6f35ea-2f9d-443a-b4ee-d25371fad80c)

**Comment by janekste** [comment]
@LeeBamberTGC I don't see the problem anymore. Probably everything is fixed.
