### ISSUE TITLE
Unable to place editable area after importing heightmap

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#3073]
Hi i've recorded a little video on what is happening after importing a heightmap. 

https://www.youtube.com/watch?v=QSNpcBE2uB4

As can be seen in the video, positioning the editable area is no problem without adding a custom heightmap but after i've loaded a custom heightmap i'm unable to position the editable area.
The heightmap is PNG 4096x4096 and 16 bit grey scale.

**Comment by earthling45** [comment]
So apparently we need to adjust the size of the created and imported heightmap to fit within the editable area and positioning isn't possible because the imported heightmap isn't part of the procedural terrain?

Also a question about converting to raw, can somebody point us to a good tool for converting the PNG to raw format which is compatible with GGM?
I've tried an online converter but that wasn't compatible. :)

**Comment by rvanner** [comment]
@PaulSJ Could this be due to the width of the users monitor?

**Comment by earthling45** [comment]
Info on the monitor. 21:9 res 3440x1440. :)

**Comment by PaulSJ** [comment]
This is behaving as intended. The chosen heightmap is always centered on 0,0 as is the yellow editable area. Only the procedural terrain moves around. When you move the yellow box, the editable area doesn't actually move, the procedural terrain just changes its offset so a new part of it is at 0,0.

I've found ImageJ to be a good tool to convert images to RAW format.

**Comment by earthling45** [comment]
Thanks for looking into this PaulSJ. I'll close this issue. :)
