### ISSUE TITLE
GameGuru Max Swimming Bug - Clipping Through Objects/Ladders Break Swimming

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3074]
Thanks for adding swimming guys, it's been a major wish of mine since FPS Creator and is greatly appreciated, that being said there's a few bugs to be ironed out. Made a little test area to showcase said bugs: https://youtu.be/EUPnd_IGOfc
 
Text report if not watching video: 
Upon swimming you will start clipping into objects (jumping/climbing on top of objects is currently impossible whilst swimming,) if climbing unto a ladder in the water and getting off, it breaks the swimming and you sink like a rock.
 
Not sure if you're already aware of these and working on ironing them out, but felt the need to report them regardless.

**Comment by Lemuripest93** [comment]
> @Lemuripest93 Thank you for reporting these issues. A fix has been added and will be in the next build. I will post here when you are able to download and test it, and hopefully we can confirm the fix :)

Thanks a lot, looking forward to it!

**Comment by rvanner** [comment]
Confirmed as fixed.
