### ISSUE TITLE
GGMax - Possible Bug - Shift+Left Click to duplicate particles does not work

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3076]
Tried this and retested in a blank level to confirm issue. Added a stock particle effect to my map and scaled it up a bit. Tried to duplicate that particle effect by clicking on it again and then pressing shift+left click to place it while grabbing a duplicate of that same particle. Placing the duplicate down does not copy the settings of the previous particle and also appears to only show the effects of the particle that was last placed in the editor while using the shift+left click method.

(Selecting if from the "current objects" tab appears to work fine. Seems to only be an issue with particles when shift+left clicking to duplicate?)

**Comment by MonkeyFrogStudio** [comment]
@rvanner I don't see this as an enhancement, but as a bug. If you duplicate a particle, the duplicate won't work. Well, that's not entirely true. The last selected of the two will work, but only one of them will work. If you use SHIFT+Click to create several duplicates, then only ONE of them will ever work, even if you run the game. This is clearly a bug.

**Comment by MonkeyFrogStudio** [comment]
Here's a video showing this in "action":

https://user-images.githubusercontent.com/36735507/167406877-b549d570-85b5-4012-9e89-ac039988142b.mp4

**Comment by LeeBamberTGC** [comment]
@ZakJudges Look for DuplicateFromList, it is a good indicator of how objects are duplicated. May not be the function, but has variables that share common features, and eventually you will add a break point near one that shows you the code responsible. Breakpoints are ALWAYS your friends in alien territory :)

**Comment by ZakJudges** [comment]
@Kravenwolf @MonkeyFrogStudio I have added a fix for this. Will post here when it is ready to test so you can confirm the fix. Thanks :)

**Comment by ZakJudges** [comment]
Hi @Kravenwolf @MonkeyFrogStudio The update that includes the fix should now be available. Could you confirm if this issue no longer occurs? Thanks!

**Comment by MonkeyFrogStudio** [comment]
Looks to be fixed on my end! Thanks, @ZakJudges !

**Comment by ZakJudges** [comment]
Great, thanks for confirming :) Closing this issue
