### ISSUE TITLE
Can Collision when Crouched be Looked At?

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3077]
See video
https://youtu.be/PykKiPhsNSE

The height at which the player can crouch under objects doesn't seem right. The actual distance the player / camera moves down is good but the collision at which the player can move under objects just seems off. Objects have to be way above the players head in order to pass under them. 
In the video I'm using the same wall model but I lowered the height a little bit on the 2nd one.  From my perspective it looks like I should easily be able to go through it but I cannot. Traversing vents in video games has been a popular staple since about forever. Currently its not possible to have the player go through a ventilation system, unless the vents are comically large.

**Comment by LeeBamberTGC** [comment]
NOTE: This is the standard full height and half height capsule sizes, and all assets up to now have been designed with these two sizes in mind.  Hacking in a change to crouch would change core defaults, never a good thing to do lightly. The solution suggested is an option to change both player full height and crouch heights, and change physics capsule heights too as the user requires.  Naturally, it means standard doors will look weird, but for custom-created art this might be necessary. More work is needed as it also affects nav meshes and has a knock-on for being able to change similar metrics for characters as lowering player height changes the perceived human scale of everything.  Perhaps V1 is a simpyl change to crouch physics height and camera offset height, and see how much mileage we get from those tweaks alone.

**Comment by Kitakazi** [comment]
Aye I figured it would not be something easily changed. I think your suggested V1 change to crouch physics height would solve the issue. I think the camera when crouched looks pretty good right now and the physics/player-capsule when crouched just needs to be very slightly tweaked. If the camera needs to also be slightly tweaked to go a hair lower it probably could but I definitely don't want anything drastic.  
I know my request is very nit-picky but I feel like it is really close to being perfect.
