### ISSUE TITLE
Audiobank Material: Can't add new Material/Footstep sounds via the Editor UI 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3078]
GGClassic had 18 different materials in the audiobank that controlled footstep sounds. 
Currently Max only has 10 but the other options are missing. Here is the current list. 
[materialdefault_test.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8648794/materialdefault_test.txt)

I tried to create a material #4 since there is currently no mat4 listed, but had no luck in getting a new material/footstep sound to work. 

Not sure if this is a bug or more audio was going to be added later and those material slots are turned off but currently 10 different footstep sounds is not enough. Especially considering the only footsteps in the list are "outdoor" sounds.

**Comment by Kitakazi** [comment]
Pretty sure this is a bug, I follow all the steps to add new audio to a new material created in an available spot in the materiallist/audiobank. These steps work in Classic, and in Max they do not work. I can replace footstep audio with my own for the materials that already exist and it works fine. 
So I believe this is a bug as I don't see any reason why I can add in footstep sounds for say materialindex 4 which is blank by default.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you show me the section in the user manual that explains this functionality? I am pretty sure we did not add it yet :)

**Comment by Kitakazi** [comment]
@LeeBamberTGC 

Err maybe I mis-understood your answer on the broadcast https://youtu.be/KyIWNfdsgyE?t=1418
You said it was possible to add new footstep sounds but not something you can do in editor, and since the audiobank and materialindex txt file are set up similar to classic I figured that editing those, is what you meant by saying it could be done. 

I asked that question because I figured it was not possible to say add footsteps to, for example, materialindex = 4 as I believed I had followed the correct steps to create a new footstep sound. But then you said it could be done, just not in the editor, so thats why I suggested this was a bug. 

Hopefully that makes sense... And I guess you are saying if I wanted to add a new footstep sound to materialindex 4 it would take more than just editing the materialindex  and adding a new folder with my footstep sounds?

**Comment by LeeBamberTGC** [comment]
@Kitakazi Thanks for the clarity. I will edit the title so it better describes the new functionality. 

You sure can edit the existing files in the installation, but the danger is that these are overwritten (maybe) when you next update as they are the official sound settings for MAX.  You would need an offline and non-updating installation to keep your own material and sound changes.

The above feature would allow you to 'add' new user materials and sounds that are retained when you update :)
