### ISSUE TITLE
GGMax - Swimming Bug

### ISSUE THREAD

**Issue by rick594** [TheGameCreators/GameGuruRepo#3079]
When Swimming a river in play mode, can't exit the water instead the player swims under the ground and the water still surrounds the player. I've tried this on both my desktop and laptop.
See attached video:

https://user-images.githubusercontent.com/100201525/167432998-a09956d6-7a23-46ec-9ea6-7314d252d1d7.mp4

o

**Comment by ZakJudges** [comment]
Hi @rick594, this has been fixed and will be in the next update. I will post here when it is available to download and test :)

**Comment by rvanner** [comment]
Confirmed as fixed.

**Comment by rick594** [comment]
Thanks.
