### ISSUE TITLE
no  material sound

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3082]
walking  makes no sound  on  any surface or  object.

**Comment by ZakJudges** [comment]
Hi @casigus, are you still experiencing this issue in the latest build? I wasn't able to reproduce it

**Comment by casigus** [comment]
yeah! had this issue for months even with complete re-installs! no sound  at  all.

**Comment by ZakJudges** [comment]
@casigus Do you have access to the experimental build?

**Comment by casigus** [comment]
i believe so on steam?

**Comment by casigus** [comment]
oh wait. no. i do not.
![image](https://user-images.githubusercontent.com/68471279/168890040-9e5a4b12-c832-4d80-a1ac-50efd0aa2a8e.png)

i mean do have a max installer saved somewhere, the one on my store accounts disapeared !

**Comment by LeeBamberTGC** [comment]
@casigus Use beta code "lettesterin456" to get access to the EXP build :)

**Comment by casigus** [comment]
ahah testerin. on IT ill shout back results!

**Comment by casigus** [comment]
Oh boy! that didn't go well at all! 1.1fps and still no material sound! fps is 25/30 in the editor but the second the game map loads up BOOM fps drops too 1/2

**Comment by LeeBamberTGC** [comment]
@casigus Is this a separate issue? Is the material sound sorted for the current EXP build?

**Comment by casigus** [comment]
nope! still no material sound unfortunately.

**Comment by LeeBamberTGC** [comment]
@casigus Try adding some snow down and walking on that. Or walking through shallow water at the waters edge.

**Comment by casigus** [comment]
on it!

**Comment by casigus** [comment]
now! going into shallow water, nothing, deeper water, the sounds are quite good, as for the snow. nothing.

**Comment by LeeBamberTGC** [comment]
@casigus Can you make a video and attach here with the FPM level you made to test, I can then see what you see (and hear) and also reproduce with the level, that might get us closer. Also try VERIFY FILES on Steam in case those audio files are missing or corrupt.

**Comment by casigus** [comment]
yes! heres the video, https://www.youtube.com/watch?v=gd5Mjrp7dVA&feature=youtu.be

and heres the level!

https://drive.google.com/file/d/109EbyavFsvvSirtNqzxL77R-aIy9YT3a/view?usp=sharing

:)

**Comment by LeeBamberTGC** [comment]
@casigus Thanks for the video. Could you do a second one with the ambient sound off, and just pick a large flat area of snow and run through it without jumping for 20 seconds. I can then should be able to pick up any footfall sounds If any.

**Comment by casigus** [comment]
yes! here you go!

did the verifying file thingy ma bob but alas still no joy.

heres the video!


https://www.youtube.com/watch?v=r1LYc8DQZVM

curiously has anyone else had this issue?

**Comment by casigus** [comment]
oh intresting.

its very odd!! even when stand alones are exported still can't hear footfall! been like that for months!!

**Comment by LeeBamberTGC** [comment]
@casigus Can you put this in your "Steam\steamapps\common\GameGuru MAX\Max\Files\scriptbank" folder, run test game and send me a screenshot of the prompt that will show at the bottom of the screen, thanks.
[gameplayercontrol.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8729197/gameplayercontrol.zip)

**Comment by LeeBamberTGC** [comment]
@casigus That at least shows the physics of the terrain is returning the correct material index, so we know we are standing and moving on snow :)  So that leads us to the sound files.  Can you zip up this folder "Steam\steamapps\common\GameGuru MAX\Files\audiobank\materials" and email it direct to me at lee@thegamecreators.com thanks!!

**Comment by casigus** [comment]
done ! :)

**Comment by LeeBamberTGC** [comment]
@casigus All files look great, and I assume you can play the WAVs on your PC no problems if you select them directly and play?
[gameplayercontrol.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8739080/gameplayercontrol.zip)
Try this new script, it moves the prompt to the point where the play sound is called, and screenshot the numbers when you are moving over snow, thanks!

**Comment by casigus** [comment]
here you go! aye sounds play externally to max ! :) 

![20220520142221_1](https://user-images.githubusercontent.com/68471279/169537332-c920aaae-8773-400c-a340-88c67176e8fe.jpg)

![20220520142233_1](https://user-images.githubusercontent.com/68471279/169537338-2be06276-c4b6-4475-8a2e-9b147888667d.jpg)

![20220520142253_1](https://user-images.githubusercontent.com/68471279/169537340-9b83eed8-837d-4eda-8e38-6bffcf753a5f.jpg)

**Comment by LeeBamberTGC** [comment]
@casigus Do other sounds play such as ambient music and swimming/underwater sounds?  Does the sound play when you wade through shallow water (not swimming just running along the edge of the water)?  The more sounds you can confirm play the more code I can rule out, thanks again!

**Comment by casigus** [comment]
theeeeeeeeeeee water sounds fine, ambient fine, music fine, running along the water fine! PLAYER plays hurt sounds !

**Comment by LeeBamberTGC** [comment]
@casigus I have fixed something in the latest build that 'might' have solved this as it relates to material detection and triggers. I will mark it as temp fixed to see if this is the case, and you can report back when you get the next build.  Check with the Steam EXP build in 24 hours, it should be there to do a test.

**Comment by casigus** [comment]
ohh acee. look forward to giving that a go!! has anyone else had this problem or just my pc being weird? great work as always and looking forward to the stream later!

**Comment by casigus** [comment]
yeah the sound plays fine doing that! but the rest of the level is silent!

**Comment by LeeBamberTGC** [comment]
@casigus Closing this as I believe you fixed it yourself, yay!
