### ISSUE TITLE
GameGuru MAX - Bug - Importing New Object Resets Shadows

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3088]
As the title says, when you import a new object, it resets whatever settings you have for Shadows/lights:

https://user-images.githubusercontent.com/36735507/167702616-e7d7adc5-3673-4b2b-ac1d-b12b040faece.mp4

This is happening as of the latest experimental build as of today.

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, thanks for reporting this issue. I have added a fix and will post here when it is in the experimental build :)

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges This appears to be fixed with the latest experimental build. At least the shadow settings are staying the same for me after importing a new object. ;)
