### ISSUE TITLE
Choppy Performance 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3091]
See video - https://www.youtube.com/watch?v=4E1W7WmVKRA

This is with shadows all turned off. 
Running around the level just seems to drop frames suddenly, feels like it freezes for a split second before going back to normal.

**Comment by Kitakazi** [comment]
I have some other levels that have many more assets in them and they run really smooth, so no idea why this one started suddenly being so choppy :(

**Comment by rvanner** [comment]
Looking at the stats, the probe re-fresh is causing a spike:
![image](https://user-images.githubusercontent.com/1503593/168225029-d819eaca-25ba-4184-8c4a-f439fdb9e44c.png)

@PaulSJ Is there a way to improve it's performance?

**Comment by PaulSJ** [comment]
There must be a lot of objects in that level, I've added code that will cull objects more agreesively from the environment maps

**Comment by Kitakazi** [comment]
@PaulSJ 
Hi Paul, the latest update did not fix my issue. This level only has about 2000 objects in it. 
The stuttering is pretty bad in the editor as well as test game. Here is a video of the editor 
https://www.youtube.com/watch?v=FgikYiaVaEA&feature=youtu.be

**Comment by Kitakazi** [comment]
No change with latest build. Performance still very choppy. 
If the camera just looks straight ahead smooth 60fps. If the player turns the camera FPS drop to 40's or 50's and will move wildly from  45-59. 
Tried setting my monitor to 1080 down from from 4k. No change.

**Comment by Kitakazi** [comment]
Loaded up this level last night. 
With VSYNC off and not moving my the camera my FPS will stay at 120 or more. Once I begin to look around FPS spike downwards and backup wards dramatically. 
Not sure if this information helps at all but the level does run in 4k at 100+FPS as long as the camera doesnt move. Even when pointed in a direction where there is the largest amount of drawcalls.

**Comment by Kitakazi** [comment]
The new Horseshoe Bend demo has very poor performance. Will try and do some testing to see if removing the AI will help but yea getting about 40-45 FPS on RTX 2080. Should be pumping 145 FPS for what that level has in it.

**Comment by Kitakazi** [comment]
3840x2160
RTX 2080
16gb ram 
Intel i5 
This is all running on an SSD.

**Comment by earthling45** [comment]
16 mb must obviously be 16GB, was late last night. :)

I wonder which i5 and what the single core performance is of that chip.
MSI afterburner is a free tool which can be downloaded and run during a test to monitor your system, i am of course quite curious on how your CPU cores are utilized. :)

I'll do a test on my system tonight to see how the Ryzen2600 does in this demo.

**Comment by LeeBamberTGC** [comment]
@Kitakazi The horseshoe bend demo was created by a community member and the reason for the performance hit is the number of characters placed close together and oh so many of them. The system is trying to control them all. Hiding them and activating them in waves is a better method to preserve performance, but I agree the engine should be able to dial back the logic if the character count and concentration is too much for the system it is running on.
