### ISSUE TITLE
Swimming

### ISSUE THREAD

**Issue by Jisafu** [TheGameCreators/GameGuruRepo#3093]
After the player swim there is an error, the swimming dont stop and it is not possible to go on land, when swimming under water it is OK to go on land

**Comment by ZakJudges** [comment]
Hi @Jisafu, this has already been fixed and will be in the next update. I will post here when the update is available to download so you can confirm the fix. Thanks :)

**Comment by synchromesh62** [comment]
@ZakJudges 
Just to confirm this is not in the experimental build then ?
Updated last night and its still doing this for me ?

**Comment by ZakJudges** [comment]
@synchromesh62 The fix isn't yet in the experimental build, but it should be in the next one :)
