### ISSUE TITLE
GameGuru Max - Request - Swimming Speed Slider

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3094]
Lots of posts about swimming here lately, though i haven't seen this mentioned so i'll do it, i think there should be a swimming speed slider implemented like we have for character speed above water since right now swimming is a little bit too slow, this should preferably be added into the next update, though you guys ultimately decide when it happens.

Just thought this was important to mention, thanks for your hard work.

**Comment by ZakJudges** [comment]
@rvanner I could add a speed slider when I tackle the new swimming bugs if you like? It shouldn't take long to do :)

**Comment by rvanner** [comment]
@ZakJudges Yes, please add it!

**Comment by Lemuripest93** [comment]
> @rvanner I could add a speed slider when I tackle the new swimming bugs if you like? It shouldn't take long to do :)

Sounds good to me, take your time with the bugs first though!

**Comment by Lemuripest93** [comment]
Speed slider has been added, and confirmed working.
