### ISSUE TITLE
Level disappeared from storyboard editor

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#3097]
my current game I'm making has several levels. It's allowed me to create up to four without any problems but when I added the fith level it disappears when I close the program. It allows it to be created and worked on but when I save and exit it no longer shows on the storyboard editor. I tried to re-create the level with the same name and that one disappears also. It doesn't want to seem to let me make more than four levels. When I created a new level with the same name it asked me if I wanted to overwrite the current level so it knows it's still there it's just not showing. I'm assuming this is a bug and not a level limit for the early access version.Anyway to get around this in the meantime?

**Comment by mike123yy** [comment]
I figured I should add this, if you go to add existing level the level is on the list and will allow you to add it to the storyboard and work on it. So it definitely still exists and is not being deleted.They're just being removed from the storyboard once you exit

**Comment by ZakJudges** [comment]
Hi @mike123yy, apologies for the late response. I could not reproduce this issue. Do you still experience it in the latest build? 

Note that the Storyboard is saved with the "Save Game Project" button. Saving a map does not save the storyboard. This means that if you are working on a map, save it and then immediately exit the software, the Storyboard will not have been saved.
