### ISSUE TITLE
GG Max - In terrain generator you can't move the editable area if heightmap is loaded 

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#3099]
https://youtu.be/Gy0wCM4XgUw

**Comment by earthling45** [comment]
Hi, see this closed topic for the answer.

https://github.com/TheGameCreators/GameGuruRepo/issues/3073

**Comment by Ghost-l0l** [comment]
Ah ok so it can be closed
