### ISSUE TITLE
Problem in changing animation speed

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#310]
GameGuru Public Preview V. 2018.07.18
If the animation speed changes to the third person character.
The animation speed of all enemy characters also changes at the same time!!!
And vice versa.

![01](https://user-images.githubusercontent.com/36647058/42959528-659782e4-8b9e-11e8-886b-32c93f5d682f.JPG)
![02](https://user-images.githubusercontent.com/36647058/42959535-6bcdde6a-8b9e-11e8-9035-be72abef7d32.JPG)

**Comment by Shahin3d** [comment]
This happens to all objects.

![capturej](https://user-images.githubusercontent.com/36647058/43039205-dbdf36ea-8d3d-11e8-8a82-f1a2f27bc964.JPG)
![capturej2](https://user-images.githubusercontent.com/36647058/43039207-e1171af6-8d3d-11e8-977f-f06ce4733411.JPG)

**Comment by plemsoft** [comment]
@Shahin3d Thanks for reporting this,

This has been fixed and are ready from the next update :)

**Comment by Shahin3d** [comment]
Thank you
fixed this issue.
