### ISSUE TITLE
GG Max - bulletholes appear (or not) randomly

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#3102]
https://youtu.be/8-YcbBNVFhE - video is stuttering a little, but that's fault of Obs recording, not Max :)

**Comment by LeeBamberTGC** [comment]
@Ghost-l0l Fixed in latest EXP Build was caused by ripple decal effect hiding decals that could not be reused for muzzle flashes and bulletholes.
