### ISSUE TITLE
GG Max - request - using particles as bullet impact effects

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#3103]
https://youtu.be/iNeC61_38dc 
Right now Max got only basic sprites that appear on impact (I mean - if they appear at all...) but Max got particle system already included - maybe it can be used for showing some bullet impacts?

**Comment by fearlesswee** [comment]
I've been suggesting this for a while. The sprite-based effects were antiquated in classic's days, now in MAX they're practically medieval! At the absolute least the range at which the sprite-based effects appear should be massively increased, and they should be fixed to consistently appear on every surface. Right now weapons have next to zero visual feedback which makes them feel genuinely awful to shoot. Gamefeel is a very important factor to a game being fun and there's many contributing factors, with strong visual feedback for every action being high on that list.

**Comment by mav3r1ck1981** [comment]
@Kasseyus another one you can probably close, impact effects are now particles,
