### ISSUE TITLE
Switch in Switch Escape no longer working.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3107]
Pulling the switch to open/c;lose the shutter has no effect in latest experimental build.

**Comment by LeeBamberTGC** [comment]
@davetgc Check latest from this morning, works fine at my end :)

**Comment by davetgc** [comment]
Hmmm..

This is what's happening to me. Unless I'm being really stupid, something is wrong 

https://user-images.githubusercontent.com/99803873/168268692-b6212516-75e7-42d4-871f-210877669803.mp4

**Comment by LeeBamberTGC** [comment]
@davetgc That's a VERY old level. Maybe rename the writables folder in case an OLD FPM map is in there.

**Comment by davetgc** [comment]
Lol. Okay. Don't know what happened there!
