### ISSUE TITLE
The player does not shoot when moving to a new level

### ISSUE THREAD

**Issue by Shalshek** [TheGameCreators/GameGuruRepo#3109]
Hi! (GameGuru Classic)
I have fully exported my game (save standalone) and it has 15 levels. When loading the first level, everything is fine, my player shoots as it was intended. But when moving to the next level, my player refuses to shoot and reload. The player does not react in any way to pressing the left mouse button or the reload button of the weapon "R".

An interesting point: if I save the game, go to the main menu, then load again to the same level, then the shooting returns again, but only until the next level is reached. Then again the player refuses to shoot.

**P.S. My third-person player**

Please help me!

**Comment by davetgc** [comment]
P.S. My third-person player? Does this mean you're using a script to create a 3rd person player?

**Comment by Shalshek** [comment]
@davetgc I didn't write a special script for this. Just set the Player model to the level start marker.

**Comment by davetgc** [comment]
Ok, thanks.

**Comment by Shalshek** [comment]
Hello! Sorry to bother you! Is there any progress in my problem? How long does it usually take to solve such problems? 
Thanks.

**Comment by DaveTGC2** [comment]
@Shalshek - The dev team doesn't work at the weekends, but I'm sure someone will get back to you soon. Unfortunately, I don't know what progress has been made so can't answer your question.

**Comment by Shalshek** [comment]
@LeeBamberTGC 
@plemsoft 
Hello! is there any progress in my problem? I would like to get a solution to this problem as soon as possible. thank you!

**Comment by Shalshek** [comment]
@LeeBamberTGC 
Hello! will this bug be fixed in the upcoming update gameguru classic?
Thank you!

**Comment by Shalshek** [comment]
@LeeBamberTGC 
Unfortunately, the notification did not come. I really hope for your help in this problem. I am studying at the university with a degree in game and computer software developer and I need to finish work on my project to defend my term paper. Can I count on fixing this bug in the upcoming update? I really count on your help!

**Comment by Shalshek** [comment]
@LeeBamberTGC 
Unfortunately, the notification did not come. I really hope for your help in this problem. I am studying at the university with a degree in game and computer software developer and I need to finish work on my project to defend my term paper. Can I count on fixing this bug in the upcoming update? I really count on your help!

**Comment by Shalshek** [comment]
@LeeBamberTGC 
Unfortunately, the notification did not come. I really hope for your help in this problem. I am studying at the university with a degree in game and computer software developer and I need to finish work on my project to defend my term paper. Can I count on fixing this bug in the upcoming update? I really count on your help!

**Comment by LeeBamberTGC** [comment]
@Shalshek Step one is to reproduce this. Can you create a fresh project with two levels, and show the weapon not shooting when the player moves to level two?  If you can create this with stock weapons and send me the Standalone Game and a step-by-step on what I should do to see the issue, we can start from there.

**Comment by Shalshek** [comment]
@LeeBamberTGC 
Here is a test of the game. This happens with any weapon.
https://drive.google.com/file/d/1ppUGdEF9CLjevX4n3_rjNWhp1C-qJYdP/view?usp=sharing

**Comment by Shalshek** [comment]
@LeeBamberTGC Now everything works fine! Thank you very much for the work done! You were able to help me in time!
