### ISSUE TITLE
spotlight turns off after doing these steps

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#311]
spotlight and other lights turns off after doing these steps !!!

1- Making the game
2. The process F1 to F4 lightmapping.
3-Save Standalone
4- Play Game
5- Save Game
6-Return to main menu
7- Load Game
**8- You see that the spotlight and other lights turns off !!!**

![01](https://user-images.githubusercontent.com/36647058/42962616-48685190-8ba7-11e8-8675-bf50869bba13.png)
![02](https://user-images.githubusercontent.com/36647058/42962618-48b9c796-8ba7-11e8-8fb3-738f73f762d3.png)
![03](https://user-images.githubusercontent.com/36647058/42962620-48e42d88-8ba7-11e8-8d8b-e6e3f04d9947.png)
![04](https://user-images.githubusercontent.com/36647058/42962621-491e58fa-8ba7-11e8-860b-2c5d73f0465a.png)
![05](https://user-images.githubusercontent.com/36647058/42962615-4842dd5c-8ba7-11e8-9642-83ced768e916.png)
![06](https://user-images.githubusercontent.com/36647058/42962617-4892cf10-8ba7-11e8-895a-720ad07621c6.png)

**Comment by Shahin3d** [comment]
This problem has not been fixed yet.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Followed the directions exactly … Video supplied … Could not reproduce ?
https://youtu.be/_IOzIHmoLMU

**Comment by LeeBamberTGC** [comment]
Also cannot confirm, assuming this bug was fixed long time ago. Below is the proof FPM showing the lightmapped level, which when made into a standalone keeps the spotlight working fine:

[atester.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4357541/atester.zip)
