### ISSUE TITLE
GGMAX - Lag and crash

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#3110]
Hi!
I have had several problems lately with GameGuru Max. As you can see from the video ( https://youtu.be/ybmT_Ly8ibQ ) I have several frame drops and after a few minutes it crashed. I must also point out that before being able to load the project, GGMAX crashed 4 times. I have tried a lot of things, I have tried to lower the quality of the shadows, I have tried to completely remove the trees since I have seen that they were a problem for many other users, but the situation has not changed.

SYSTEM SPECS: i5 10400f, GTX 1660 Super, 16GB Ram.

**Comment by LukeTheLukeLTL** [comment]
I also tried to create a standalone to see how it went, and I had the same problems there.

**Comment by rvanner** [comment]
@LukeTheLukeLTL Can you press TAB TAB when in test game to show the various performance stats? This will help us see where the lag is coming from.

**Comment by rvanner** [comment]
@PaulSJ Can you take a look at this issue and give your opinion please? The video linked above shows the CPU and GPU maxing out and then a crash happens.

**Comment by PaulSJ** [comment]
The occasional pause looks like the environment probe refresh, that should be fixed by the latest changes. 

The general performance issues seem to be caused by the number of objects in the level (CPU Update step) and the shadow rendering (GPU Shadow Rendering step). Reducing the graphics quality should help the shadow performance but I think the only way to improved the CPU performance would be to use less objects.

**Comment by LukeTheLukeLTL** [comment]
@PaulSJ I have tried for the past few days to remove unnecessary objects (I have removed about 100 objects) but the performance has not changed. Removing other objects doesn't make sense to me, because otherwise the game would be empty. At this point I think there is something wrong with the engine as I have read that other users are also having the same problems.

**Comment by ZakJudges** [comment]
Hi @LukeTheLukeLTL, apologies for the late response. Do you still experience the crash in recent builds?

**Comment by LukeTheLukeLTL** [comment]
No at the moment I haven't had any crashes, and the lag even if it's not completely gone however the games run much better than before. So for now I am closing this issue, in case the problem reappears I will reopen it.
