### ISSUE TITLE
Character Movement

### ISSUE THREAD

**Issue by oliamit12** [TheGameCreators/GameGuruRepo#3111]
Hi, All the characters on 1  build level have ceased to advance over the terrain although walk animation is working. It seems to be this 1 build, IT only took 9 hours. Is There a fix? Thanks.

**Comment by rvanner** [comment]
Do you have more information on this issue? Can you share a screen shot or a video?

**Comment by davetgc** [comment]
This might be linked to this issue, I've only spotted it today.

https://user-images.githubusercontent.com/99803873/168304777-fa5459fe-feaf-45e0-8148-aaf3e555bc0b.mp4

As far as I can tell, it happened after the player was killed in test game.

**Comment by oliamit12** [comment]
This video portrays the problem I have, but with every A.I. in the build. Thank You. I really liked the level, but now it's useless as no matter what I try Ican't get any of them to move. even fresh ones.
