### ISSUE TITLE
Feature request: trigger item to disappear

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#3112]
It would be helpful if besides using the trigger zones for spawning items or enemies you can also use the triggers zone to make the items disappear.  For instance, if you were doing a horror game and you had a creature or ghost standing in the dark in front of you you could make it so when the player approaches them they would disappear for a creepy effect. It would also work well for an item to be there one minute and when you come back it was gone.

**Comment by Necrym59** [comment]
Try this
[hide_v1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8683969/hide_v1.zip)
just apply to the object you want to hide fill in the behaviour settings

**Comment by mike123yy** [comment]
This works great for having the ghost disappear! Thanks for the script. Although since it doesn't use a trigger zone it wouldn't work for other scenarios. Here's one I'm using in my game for an example:
 I have a house the player walks through with the dining room that I'm going to have the ghost rearrange the chairs when the player leaves the room. So they couldn't disappear when you come in the range, they would need to disappear when you left the room and entered the designated area(a spot that I could make sure the player wasn't able to see the switch). So I would need to have one set of chairs in the normal position that would need to disappear with the trigger zone and another set of chairs in the new position that would be activated by the trigger zone out of view of the dining room. If the player were able to see the change take place it wouldn't look very convincing. If this script could be activated by the trigger zone it would be perfect for everything I need though.

**Comment by Necrym59** [comment]
Ok let me think on this and ill have a crack at enhancing the script for Hide/Unhide scenarios

**Comment by mike123yy** [comment]
Thanks! That would be great. I appreciate the help. There's no need to make the script make things appear though.All it really needs to do is when the item it's attached to is connected to a trigger zone it will disappear when the zone is activated.

**Comment by Necrym59** [comment]
Ok this one should do the trick from a trigger zone. You have the option to Hide or Show an object(s).
[hideshow_v2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8691855/hideshow_v2.zip)

**Comment by mike123yy** [comment]
Awesome! This is exactly what I needed! Thank you much, it works great! Thank you for taking the time to do this

**Comment by Necrym59** [comment]
OK try this one, if you select 'show' it will automatically hide it on game startup.
[hideshow_v3.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9213746/hideshow_v3.zip)

**Comment by Hamada880** [comment]
I will tested it tonight while I'm at work :p will also give feedback and thanks so much for the quick replies. 👍👍

**Comment by Hamada880** [comment]
It works perfectly for hidden item at the start and it toggle it's visibility nicely. However, shown items at the start doesn't toggle its visibility more than one time. 

To explain more about my scene, it is dark room with light switch and once it's flicked factory light object with emission appears and when the switch is off both light and object is hidden to show factory light object without the emission.

**Comment by Necrym59** [comment]
Ok try this
Trigger zones are onec only so cannot trigger on/off use a switch
If connected to switch the behaviour will toggle between hidden and shown.
[hideshow_v5.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9225890/hideshow_v5.zip)

**Comment by Hamada880** [comment]
Can't thank you enough, will test it out and thanks though a heads of time :)

**Comment by Hamada880** [comment]
Worked perfectly, thanks so much 👍👍

**Comment by synchromesh62** [comment]
That is one of my most goto scripts by Necrym59
One script with 1000 uses. Excellent work mate :)
