### ISSUE TITLE
Big FPS drop in build 12/05/2022

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3113]
FPS on an empty map has nearly halved.

![image](https://user-images.githubusercontent.com/99803873/168219789-d4a86795-139e-4a3c-9c8d-7e48081babbd.png)

Not present on more complex maps!

![image](https://user-images.githubusercontent.com/99803873/168220235-b87b3b27-4a5d-443b-8254-a6ba18a600f6.png)

**Comment by davetgc** [comment]
[mapbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8684467/mapbank.zip)

Added FPM file of problem level.

**Comment by rvanner** [comment]
The GPU stats are peaking over 16ms which is where the frame rate starts to hurt. The forest biome has a lot of packed in trees and so I would suggest spacing them out more. Even the level where it looks like there's more going on is getting close to the 16ms red line.

@PaulSJ Any other views?
