### ISSUE TITLE
The "undo" function (Ctrl+Z) is a little janky when painting terrain for me

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3121]
Can someone else confirm? When painting terrain, sometimes pressing Ctrl+Z will not work to undo the stroke I just applied unless I press it two or three times. Doesn't happen all the time though (~50%), but does appear to be an issue based on how large of an area I paint on a single stroke. It also looks like **_maybe_** moving the camera after painting an area on the terrain causes it to require a second undo press?

**EDIT:** Actually, with some further testing, it appears the Ctrl+Z undo action literally skips every OTHER keypress when painting terrain. To confirm, paint a single stroke of terrain and press Ctrl+Z. It should work. Then paint another stoke of terrain and press it again. Won't work the second time. Paint a third stroke, and that one can be undone with Ctrl+Z. Paint a forth...nope.

**Comment by Kravenwolf** [comment]
Thanks Zak!

**Comment by LeeBamberTGC** [comment]
I will test and close this soon, please let me know if it is still an issue, thanks!

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Please do continue the test and let me know how it goes, thanks!!
