### ISSUE TITLE
The player is pushed back when pressing spacebar[GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#3123]
When using the ladder in the water, pressing the spacebar pushes the player back, this way the player will never get out of the water.
The player should be pushed in the direction he is facing. :)

https://youtu.be/yPPLzlf0FPI

**Comment by Necrym59** [comment]
Space bar is for Jump off while climbing,  just climb to top to get off ladder

**Comment by 3coms** [comment]
Got it!
Apparently, the player must climb a distance equal to the size of the ladder in order to drop the ladder; although when Amenmoses wrote the original script there was no possibility of using the ladder in the water, now the part of the ladder that is submerged in the water would have to be taken into account, but this would be going too far, as it is, it seems fine to me.
Basically, the principle is the same that we have applied so many times in GG, to fix the player to a platform, an elevator, etc.
