### ISSUE TITLE
GGMAX - Build 2022.05.13   Saving grouped objects issue

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3124]
When saving grouped object it doesnt save the current rotations/angles of those objects in the group, or isnt reapplying them on import. However it does save a thumbnail showing how it should be. Also when saving and the naming field dialog appears can we have a save button as well as the cancel button.
Example a group was created from two chairs and a light, The thumbnail is created correctly and correct orientations.
![createdgroup](https://user-images.githubusercontent.com/95015657/168404411-4a88b219-7d91-4f9c-8bcd-03c10305db4a.png)
The thumbnail above created is shown in the items windows but if you look at a full screen of that thumnailed group only the 1st object selected in that group is shown. and the tumbnail is temporarily changed to the 1st object.
![fullscreenview](https://user-images.githubusercontent.com/95015657/168404488-b452fe85-7e5b-4370-ad79-5ad164c37ed9.png)
If you then place that group into a scene rotations revert back to original settings.
![comparison](https://user-images.githubusercontent.com/95015657/168404570-5040fe11-41a2-45f4-afb6-8c0030038735.png)

**Comment by MonkeyFrogStudio** [comment]
Saved group objects do not keep their rotation. Here's what the group should look like:

![save_group2](https://user-images.githubusercontent.com/36735507/168404019-76b5fbd3-e190-4b1e-b7ee-ed25877c39c6.png)

Here's how the saved group comes into MAX:

![save_group](https://user-images.githubusercontent.com/36735507/168404056-6da51a84-1bca-487f-ad7f-fe11c3299f1e.png)

Also, the saved group changed the **spotlights** from the original group and made them all into **point lights**.

**Comment by Ratall** [comment]
Bug reported #2965

**Comment by Necrym59** [comment]
> Bug reported #2965

Yes this has other items reported as well
