### ISSUE TITLE
GGMAX - Build 2022.05.13  Hole tearing in water issue

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3128]
When firing into water, hole tearing in the surface texture where the transparent splash is occurring.
https://user-images.githubusercontent.com/95015657/168452818-79f6e79d-6048-4458-9ddf-cbf60d69644a.mp4
![holes](https://user-images.githubusercontent.com/95015657/168452883-8c429f80-a2e6-485c-902b-7009c1277f5d.png)

**Comment by rvanner** [comment]
I can confirm:
![image](https://user-images.githubusercontent.com/1503593/168604932-50e33d1a-4119-48ab-9ed9-528c09647351.png)
