### ISSUE TITLE
Dyanamic objects do not move after explosion other objects!

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#313]
Dyanamic objects do not move after explosion other objects!
And like static objects are immobile.
They were thrown before the update.
Even the characters are fixed and can not be thrown.

![1](https://user-images.githubusercontent.com/36647058/42969905-f9ee6318-8bbc-11e8-8030-a9e59ae74d35.jpg)
![2](https://user-images.githubusercontent.com/36647058/42969911-ff417648-8bbc-11e8-965d-616afb569a28.jpg)
![3](https://user-images.githubusercontent.com/36647058/42969915-036094a2-8bbd-11e8-98d9-c31460960372.jpg)
![4](https://user-images.githubusercontent.com/36647058/42970486-a7133b30-8bbe-11e8-9036-6239e68a2274.jpg)
![snapshot18](https://user-images.githubusercontent.com/36647058/43032927-59d15046-8cd6-11e8-9871-f9733a365d02.jpg)

**Comment by Shahin3d** [comment]
I hope to be fixed before the release of the new version.

**Comment by AmenMoses** [comment]
Found the problem, pushing a fix ...

**Comment by LeeBamberTGC** [comment]
Fixed for next build :)  Thanks!
