### ISSUE TITLE
Severe Performance Issue - with large geometry wrapping player position - Max 22.05.13 version

### ISSUE THREAD

**Issue by cybernescence** [TheGameCreators/GameGuruRepo#3131]
Hi guys. I am trying to build an 'Aztec' level using AA models and cannot get a satisfactory performance from Max. 
I've investigated as far as I can without source code access :). The same models I can get running in both Wicked and Classic (a modified 32 bit indice version). 

Presently with Max I can't even get all the models in without FPS dropping drastically and stuttering in 'play' mode. When I move the player position away from the models, the FPS recovers back to 60 FPS. It seems to be a 'collision' type issue rather than a rendering issue, but persists even if I take all collision and physics off the models via the UI. I assume you are not using the 'Wicked' method of capsule collision?

Below is a comparison / metrics of the three for info (Max/Wicked/Classic).

![aztec comparison](https://user-images.githubusercontent.com/35750023/168471908-7d66b9a4-4a75-4329-bb2f-c369d2bc93e6.jpg)

Other people are having a similar issue (mentioned on the GG Max discord).

Vids of levels running in Wicked and Classic below. I can't do a Max vid as performance is that bad in this use case. 

https://youtu.be/JPeiKfdmtcQ
https://www.youtube.com/watch?v=LtX5xfpWlSI

Cheers.

**Comment by casigus** [comment]
yeah the fps for atricious atm.

**Comment by plemsoft** [comment]
@cybernescence Thanks for reporting this issue, and sorry for the delay, Max do use capsule collision just like Classic , so at least it should give you the same FPS as classic , Do you still see this issue in the lastest build or is it already fixed ?, Thanks for your help :)

**Comment by cybernescence** [comment]
Hi Preben, it's fixed now, just checked on the experimental Max build. Thanks

@plemsoft
