### ISSUE TITLE
Collision Mesh Issues - .fbx and .obj scaling incorrect (MAX Version 22.05.13)

### ISSUE THREAD

**Issue by Pekuru** [TheGameCreators/GameGuruRepo#3132]
Update 22.05.13 saw the introduction of Collision Mesh shapes derived from .obj files with identical names as the .fbx/.dbo in the same folder as the actual model. Upon inspection of this feature the transformation parameters don't seem to work properly.

To test it's functionality I have tried 3 different ways of exporting:
- .obj file using the exact same parameters as how the .fbx is exported.
- Not applying the end transformations to the finished collision mesh.
- Using the exact same .fbx saved as .obj to use as collision.

_For reference: .fbx export parameter is set to 0.32 which works perfectly for actual meshes and brings them in-engine with perfect scaling._

With various results. All three seem to have the same thing in common: They're way too small! All three produce near identical results to what is displayed beneath.

![Common Screenshot 2022 05 15 - 15 24 30 04](https://user-images.githubusercontent.com/9923839/168475600-c49c23b5-3c60-4a3a-a4eb-e5352833a1d9.png)

**Comment by LeeBamberTGC** [comment]
@Pekuru Send me these models FBX + OBJ to lee@thegamecreators.com in confidence and I will try to reproduce what you see. We have been using the OBJ collision mesh for assets we are creating in house and have not seen this one, and my instinct is to look closer at the FBX scaling first, but once I have the models I will know more :)

**Comment by Pekuru** [comment]
@LeeBamberTGC Email has been send!

**Comment by LeeBamberTGC** [comment]
@Pekuru Was looking for this link, phew :)  You need to import as FBX, assign your textures, then set the collision to HULL DECOMP and then everything is fine:

![image](https://user-images.githubusercontent.com/35840583/174783100-7de6dfe9-5309-4cc2-9ec3-5d7456256cef.png)

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
