### ISSUE TITLE
frame rate so low.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3133]
the frame  rate is....

awrful.

![image](https://user-images.githubusercontent.com/68471279/168488015-81d262fb-434d-4d81-a71a-f1ea88144ba9.png)

**Comment by rvanner** [comment]
@casigus Please turn on the stats so we can see what's going on in this scene.

**Comment by Ghost-l0l** [comment]
over 10 milion polygons, whole army of characters, lots of dynamic lights - all in 1 scene - thats alot things to handle at once; whats your pc specs?  
And I you got alot of different assets loaded into this level so memory is fully loaded with gigabytes of textures  - as your memory counter shows 33gb - that's ALOT if you ask me, when I'm building levels I always try to keep it under 10gb (and even 10gb sometimes feels like too much). Check your assets, some of them might have very heavy textures, some of them probably got very high polycounts, and after you add-up alot of it at once, engine will start to crawl.
