### ISSUE TITLE
Bullet Impact Decals not appearing in the correct spot

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3135]
When you damage an object the bullet impact decals are not appearing at the correct location. In this screenshot I am shooting the metal wall, and look where the "spark" from the bullet hit is appearing. 
![20220516005425_1](https://user-images.githubusercontent.com/51464873/168528863-3926ab53-b712-4a81-ada9-5532470c7c6f.jpg)

**Comment by Kitakazi** [comment]
Bullet holes are not showing up either.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Confirmed in current build, thanks!

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Reopening this one. I think it was fixed? But as of the current build the Impact Decals and Bullet Holes are missing again.
