### ISSUE TITLE
GameGuru MAX - Bug - Importer Does Not Generate Proper DDS from Surface file if PNG

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3139]
I use Substance Painter to create my PBR materials for MAX. With it, I can export out my textures when completed so I end up with an albedo, normal, and a single texture that contains the roughness, metallic, and AO in their proper channels. Of course, I've named this last texture "surface". Substance Painter does not export DDS files, so the surface file I end up with is a png. When I import my model into MAX, the importer catches all the files (albedo, normal, and surface) and places them in the correct slots. However, it attempts to generate a DDS file for the surface and that files is not correct. Instead of getting the surface file that I'd created, I end up with this:

[surface_file.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8706458/surface_file.zip)

It's just a small, solid-orange square with none of the information I'd put into my surface texture. As a result, I have to click the "..." button and import the PNG version, which then works fine. However, this means that I don't end up with a DDS version of my surface file. 

Also, that surface file is generated and saved outside of the folder where the model is imported. It's created at:

GameGuruApps>GameGuruMAX>imported_models

This folder ends up getting filled with useless DDS surface files, all orange (like the above example).

**Comment by MonkeyFrogStudio** [comment]
Here's a screen shot of the initial import of an object:

![surface1](https://user-images.githubusercontent.com/36735507/168767128-ffd1c2d0-1ea8-4004-ae8f-59ec6bd559ae.png)

Notice the orange surface texture and how the object in the view port is bland.

Now here's a screen shot with the proper surface texture imported:

![surface2](https://user-images.githubusercontent.com/36735507/168767351-14cc5bbc-bb46-4b2b-8709-a7f4a1e36a76.png)

**Comment by ZakJudges** [comment]
@LeeBamberTGC Notes: In `WickedCall_TextureMesh()` 
After `if (bGotSurfaceTexture == false)`
Only .dds files are checked, png isn't considered

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio In the next EXP build the importer will be able to detect a PNG-based surface file during the import process:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5652db7d-669a-4790-b068-543fecc791bd)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
This as now had a slight adverse effect to multi material models on import
The normals are showing but pointing to surface and the surface is not showing at all ?

![IMPORT](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/564673c1-fde4-4917-b2f5-d66eea3eeeaa)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I imported a multi-material GLTF and this is what I saw, the normal and surface are fine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f4740e9a-a843-40f9-9ce0-1dcdbdb42793)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5f6f594c-a8b7-4a02-95d9-b1da9c244a41)

Is there something else you are doing beyond a basic import to see the issue you are having?

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Im not the only one to have this problem since the update **however** i use .png but used the generated .dds surface or created my own as .dds .. Bit of a mix i know
It now seems to be an all or nothing ( all png or all .dds ) to get them to import correctly.
Thats not a problem for new stuff i create but all my old has the issue 

Try importing this test and you will see exactly what i mean :)
If i have to redo them all then i will but maybe its just a quick fix ?
[TEST- BARS.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13256673/TEST-.BARS.zip)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 That's great I can reproduce with this model, leave it with me :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b0fab79b-6435-4c63-b47d-21e3cc74056e)

**Comment by synchromesh62** [comment]
Awesome Lee thanks so much !!
