### ISSUE TITLE
Shadows - Draw Issue

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#314]
Hi all :)

PP 2018.07.18 -  Monster Update

Noticed today that shadows are not getting drawn correctly in some places, mainly from items casting a shadow over much lower terrain - like valleys.

Hopefully these images show the issue.
These two images show how the tree is in front of a mound of terrain:
![shadowbug_01](https://user-images.githubusercontent.com/12246318/42996211-36fb8bd4-8c56-11e8-96c2-c2f18bc71d1d.jpg)
![shadowbug_02](https://user-images.githubusercontent.com/12246318/42996220-3b9ba8a4-8c56-11e8-8d4d-fba498e33338.jpg)

These two show the trees shadow being cast on the ground in the valley as if there is no mound of dirt in front of it - like it is just floating in the air.
![shadowbug_03](https://user-images.githubusercontent.com/12246318/42996227-408bb3ea-8c56-11e8-9b93-0c7b9fc37c1a.jpg)
![shadowbug_04](https://user-images.githubusercontent.com/12246318/42996234-44c54e4e-8c56-11e8-81f6-6178373aae3f.jpg)

Reliquia....

**Comment by BodRH** [comment]
I noticed this too, it only seems to happen with dynamic entities like the candlestick, the shadow is on the table and on the floor.

![gggg](https://user-images.githubusercontent.com/36109432/43035471-708e6a28-8ce8-11e8-851e-51e1be6f24d7.jpg)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 

Pictures and information supplied above

**Comment by LeeBamberTGC** [comment]
Added terrain shadow casting to resolve the apparent floating shadow issue, which was caused by the tree casting a shadow but not the mound/terrain it sat on.  Added new flag to SETUP.INI, on by default, called "terrainshadows=1"

**Comment by michaeloldman** [comment]
awesome Lee :)
