### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3140]
I can see the animation tabs in the character creator, but when I import a model that claims it is rigged and animated. It fails massively. 

Is this something I'm doing wrong or is there an issue with the animation when importing models? 

Hope that makes sense?

**Comment by ZakJudges** [comment]
Hi @Curiosityuk, could you attach a screenshot of what you see in the "animation tool" menu, whilst importing the model you are having issues with:
![Screenshot 2022-05-23 101147](https://user-images.githubusercontent.com/32545391/169785850-bc03435f-68c2-4e49-a0e6-91fac295bdf1.png)
