### ISSUE TITLE
GameGuru MAX - Bug? - Import Object Path Defaults to MAX Install Directory Instead of GameGuruApps Folder

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3141]
GameGuru MAX creates a "safe" place for the user to store their own work and objects under GameGuruApps>GameGuruMAX>Files. This should be the default location to save objects, levels, etc. However, when importing a model, if we choose a custom path:

![path](https://user-images.githubusercontent.com/36735507/168765945-216e685c-d769-4d91-b628-559a8e238452.png)

... it default opens to the GameGuru MAX install directory:

![path2](https://user-images.githubusercontent.com/36735507/168766105-2c446333-db61-4d10-acd1-0eee83de8a95.png)

I think it should default, instead, to the GameGuruApps>GameGuruMAX>Files directory, instead, since this is where we ultimately want users to store their custom content.

**Comment by LeeBamberTGC** [comment]
@ZakJudges No worries, I have assigned to me :)

**Comment by MonkeyFrogStudio** [comment]
This appears to be fixed with Zak's latest fixes.
