### ISSUE TITLE
GameGuru MAX - Request - Need Ability to Swap Textures and Animated Textures/Materials

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3142]
Let's say I have a sci-fi door that's locked. It has a panel with a big, red light indicating that it's locked. Then, when the player uses the keycard, the light changes to green and the door opens. Now, I am not talking about an actual light, but the emissive texture color for this object. We need a method for swapping out that emissive texture. 

We also need a method to display animated textures/materials on objects ... TV screens, radar, other types of indicators, panels, etc.

**Comment by davetgc** [comment]
Animated/Video textures is coming up a lot.

**Comment by MonkeyFrogStudio** [comment]
@davetgc That is awesome!

**Comment by MonkeyFrogStudio** [comment]
@davetgc These are old features that have been in 3D games almost since the beginning (in one form or another). Even the original DOOM had some form of animated textures. Yet, we cannot do this in GameGuru MAX in 2022. ;) So, yeah, I bet a lot of people are asking for this.

**Comment by Kitakazi** [comment]
Yes please we need a way to change emissive textures and probably color textures. Just like MonkeyFrogs example.
FPS Creator had the "ALT Texture" where you could set in the FPE of an object its alternative texture. It was perfect for things like lights, flickering lights, switches, monitor screen changes, text changes on displays, etc. Really good for when a player activates an object and you want to display a small change.  I asked in a broadcast if this was ever going to come back and Lee basically said no because he didn't think people used it. Which from my experience I thought people used it all the time. 
People did try to fake blood and damage with it by having an enemies texture switch to a bloody alternative texture, which didn't always look the best, but I'm talking about ALTTEXTURE for the small details like likes and computer screens. 
But it allows for so many possibilities creatively. 

Also, yes video animated/textures are a must!

**Comment by LeeBamberTGC** [comment]
LINKED ISSUES:
https://github.com/TheGameCreators/GameGuruRepo/issues/3142
https://github.com/TheGameCreators/GameGuruRepo/issues/3050
https://github.com/TheGameCreators/GameGuruRepo/issues/2948
https://github.com/TheGameCreators/GameGuruRepo/issues/2554
https://github.com/TheGameCreators/GameGuruRepo/issues/1176

**Comment by DaveTGC2** [comment]
I think the important thing here, is that we recognise, that it's not just animated textures, but users will want to sync audio to the images.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC 

Here are a few examples from an old game - Doom 3:

_(Watch until about the 9:18 mark)_
https://youtu.be/3wj9jq8s36s?t=494

_(Watch until about the 9:59 mark to see how the keypad changes based on a click)_
https://youtu.be/3wj9jq8s36s?t=592

(Watch until about the 30:12 mark ... same sort of keypad change as above)
https://youtu.be/3wj9jq8s36s?t=1811

The reason I even showcase stuff from Doom 3 is simply because it's so old and has these features in it. I definitely think that MAX needs to be able to at least do that sort of thing.

This one's a computer screen from the game Prey:

_(Watch until about the 1:45 mark)_
https://youtu.be/iUOv6RHrh9o?t=101

There are so many uses for animated/moving textures/materials and reasons to swap out a material in a game. :)

**Comment by MonkeyFrogStudio** [comment]
> I think the important thing here, is that we recognise, that it's not just animated textures, but users will want to sync audio to the images.

@davetgc Wouldn't that be done via a video texture, which would contain the appropriate sound?

**Comment by DaveTGC2** [comment]
@MonkeyFrogStudio  Ideally, but I'm aware some users are talking about breaking a video into images and creating an atlas texture, this won't work if someone wanted to say, have a cinema screen. Back in the FPSC days, using the video texture feature, a user created a cinema where you could take the whole of the original day of the living dead film. (Public domain now.).

**Comment by MonkeyFrogStudio** [comment]
@davetgc Certainly. Thee reason they are talking about breaking a video down into images to create an atlas is in an attempt to get moving textures working NOW since MAX does not support them at the moment. It's an attempt to make a work-around. So, if they are going to go that route, then they can also create a Behavior that will not only play the animation (the atlas), but also play a sound, etc. 

If Lee incorporates video textures, then there will be no need for creating an atlas for these sorts of things. ;)

**Comment by MonkeyFrogStudio** [comment]
This has been added. So, closing. :)
