### ISSUE TITLE
Cloned entities won't connect to the shooter logic

### ISSUE THREAD

**Issue by smallg2020** [TheGameCreators/GameGuruRepo#3145]
if you clone an object that is already connected to a flag or object via the visual logic system you can't connect anything to the cloned object
[https://youtu.be/6J4KBLwSGC8](url)

**Comment by smallg2020** [comment]
good news is i discovered if you duplicate from the "current objects" box (bottom-left where your grouped items are) it does clone correctly and you can connect the cloned object fine so you can use that instead of the shift drag or control-c/v duplicate

**Comment by ZakJudges** [comment]
Hi @smallg2020, thank you for reporting this issue. I have added a fix which should be included in the next update (hopefully this Friday). I will post here when it is available for download so you can test it. Thanks :)

**Comment by LeeBamberTGC** [comment]
I will test and close this soon, please let me know if it is still an issue, thanks!
