### ISSUE TITLE
Additional parameter to control Y offset of LookAtTarget(e,v,othere)

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#3149]
https://vimeo.com/711314839

My two actors are being told to look at the player, using:

	SendMessageF( "lookattargete", e, 0 )
        SendMessageF("lookatplayer", e, 10)
in the script.

But notice how they can look left at the player, almost to 90 degrees, but can't look right to the same extent, in fact it looks to be only just off centre, maybe 20 degrees.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Can be modified with the FPE values () but changed defaults anyway for better left right head turn for all default CCP characters ( was 45 degree each way now 75 degrees each way and neck left/right limits adjusted to match CCP rig). in NEXT EXP BUILD.

**Comment by AmenMoses** [comment]
@LeeBamberTGC As we are now using character lookat functions in anger so-to-speak as part of Cine|Guru for MAX development we have noticed that when you say lookat an entity it seems to actually look at the entity x, z position but at y+ a hard coded offset (+50 at a guess).

Could we possibly have this y offset passed in as a parameter instead (i.e. as an optional parameter so if not set use whatever the current value is as a default), that way for cinematics we can actually have actors looking at keys or rabbits or whatever by setting the offset appropriately in the actors script.

(in addition you could have the default offset specified as a percentage of the height of the entity so when a character looks at a taller character or a shorter one they look in the right direction)

**Comment by LeeBamberTGC** [comment]
@AmenMoses Do you mean an additional parameter for this command: LookAtTarget(e,v,othere)

**Comment by AmenMoses** [comment]
@LeeBamberTGC I'm actually using SendMessageF("lookattargete", e, othere ) but yes that's what I mean.

**Comment by LeeBamberTGC** [comment]
@AmenMoses I have added a new global.lua command for the next EXP build that adds the support you posted, and here is the breakdown as I assume you prefer to call the commands directly:

function LookAtTargetWithOffset(e,v,othere,yoffset)
 SendMessageF("lookattargete",e,othere)
 SendMessageF("lookattargetyoffset",e,yoffset)
 SendMessageF("lookattarget",e,v)
end
