### ISSUE TITLE
Stand Alone - File Copy Issue

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#315]
Hi All :)

So stand-alone builds seam to work great now.

Much better start-up and Loading times - awesome work :)

The only issue I have found so far is that the Illumination texture for PBR models does not get copied over in the process.

Reliquia....

**Comment by michaeloldman** [comment]
Also doesn't copy over _CUBE maps for PBR either :)

Reliquia....

**Comment by demented-mind** [comment]
I also test buildings from the subfolder "Insides". Reference following link. Has image of buildings used and two videos. One test run and the other standalone.

https://forum.game-guru.com/thread/219900?page=2#msg2603899

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting this,

This has been fixed and are ready from the next update.

Fixed: illumination/emissive/cube was not added to standalone.

**Comment by michaeloldman** [comment]
awesome - thanks for the hard work :)

Reliquia....
