### ISSUE TITLE
GameGuru MAX - Bug? - Object Library Not Quite Alphabetical? 

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3150]
Where is the Object Library getting the names of the objects from, because it doesn't seem to sort object correctly by alphabet:

![alphabet](https://user-images.githubusercontent.com/36735507/169142247-95430508-a9a1-45ed-88ce-855172f74139.png)

Notice in my object list, MFD Floor Extend is followed by MFD Wall which is then followed by MFD Door Frame. I've named these so that, hopefully, all the floor pieces will be next to each other, but Wall and Door Frame are in-between Floor Extend and Floor and Floor Extend shows up before Floor.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Fixed in next EXP build

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Looks like it's fixed! Thanks! :)
