### ISSUE TITLE
GameGuru MAX - Bug - Objects Imported as Physics On Despite Static Checked

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3151]
As the title says, objects are being imported into MAX as Physics On despite the Static box being ticked on import with the latest experimental build (2022.05.20).

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, I wasn't able to reproduce this. Do you have a model you could send me that shows the issue after importing? My email address is zak@thegamecreators.com

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges After doing some more tests this morning, it may not be the importer. However, pieces are coming into the view port in the level editor as Physics On despite having been imported as Static. This has been happening to me after closing MAX and restarting later, then dragging pieces into the view port from the Level Objects area.

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Sent an email with a model and further observations via my Monkey Frog email address. If you don't receive it, let me know and I will send again via my personal email address.

**Comment by ZakJudges** [comment]
@MonkeyFrogStudio Thanks! I have received the model

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Things seem to be working fine for me (now) on my end, too. Not sure what was going on. So, I will close this, but keep an eye open for if it happens again.
