### ISSUE TITLE
GGMAX - Enhancment Requirement in Lua

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3152]
Lee is it possible to expand/extend the collision radius of the player capsule and if so can we have the command exposed in lua, i have a number of scripts now and others that could really benefit from adjusting the collision radius to encompass carried objects etc. and it could greatly enhance the scope of things in MAX.

**Comment by AmenMoses** [comment]
If you simply scale up the capsule you will have problems getting through doorways etc.

What is really needed is to be able to add a separate shape to the player capsule and have them dealt with together, something like this must be possible as weapons do not get pushed through walls etc.

**Comment by Necrym59** [comment]
Yes your right, i agree it would have to encompass the carried objects and augment the collision shape so how is it done with the carried guns at present and can we have that capability enabled to lua, it opens up a whole lot of possibilities for things.
