### ISSUE TITLE
GameGuru MAX - Bug - Group Issue with Spotlights

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3153]
I created a group that contained several elements (floor pieces, wall pieces, etc.), including a few spot lights. This group was duplicated several times to create a hallway. The test level was then saved and, later, re-opened to be worked on. Here's what I discovered:

![groups](https://user-images.githubusercontent.com/36735507/169242481-d9405b3a-8fe9-4f63-821b-f730b21a50eb.png)

- Some of the spotlights had just disappeared! The far-right example is from the original group made (the first group).
- The second arrow (from the right) - the spotlight is exactly as I had left it.
- The third arrow - The spotlights had rotated from their original positions.

Finally, NONE of these were groups any longer. They were all individual pieces, as if I had purposefully undone the groups.

This is with the latest experimental build (2022.05.20).

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Thanks for reporting this issue , and sorry for the delay , this has been fixed and will be in the next update :)

**Comment by MonkeyFrogStudio** [comment]
Looks to be fixed! Thanks!
