### ISSUE TITLE
GameGuru MAX - Bugs - Aztec Game Kit Teaser

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3154]
I noticed a few issues with the Aztec Game Kit teaser:

- The player has issues climbing up any of the steps. The only way I could get up any of the stairs of the temples was to use the jump key.
- There was no ambient music like in the live broadcast.
- There as no combat music like in the live broadcast.

**Comment by MonkeyFrogStudio** [comment]
Combat music plays as of the Friday release. The other things reported above are still issues.

**Comment by LeeBamberTGC** [comment]
For next EXP build :)
