### ISSUE TITLE
MAX - Dynamic Lua issues

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#3158]
I expected this:
-- DESCRIPTION: Shake type [@SELECTION=0(0=Add,1=Set)]
to give two selections with the default being the Add selection.
Instead I only get one option, i.e. for Add, the Set option does not show up.

I expected this:
-- DESCRIPTION: Fraction of film time [FTIME#=0.5(0,1)]
to give a slider going from 0 to 1 initialised to the default of 0.5.
Instead I get just the ability to enter the numerical value and am able to enter values greater than 1!

**Comment by Necrym59** [comment]
I thing the @ selection starts at 1 from what ive found. eg [@selection=1(1=Add,2=Set)] thats the way ive always used it
otherwise you have to check for nil all the time.
Also do we have a + or - option with Dynamic lua for negative numbers as well as positives?

**Comment by AmenMoses** [comment]
If I start them from 1 I get a blank option with 0 in it.

**Comment by AmenMoses** [comment]
Well I'll be ... today the selection is working going from 1, I'm not getting the blank entry anymore!

Oh well, the slider for floats and the negative values still need sorting out.

**Comment by ZakJudges** [comment]
@AmenMoses Thanks for reporting these issues. I have added a fix for both which should be in an experimental build in the next couple of days.

**Comment by ZakJudges** [comment]
Hi @AmenMoses, are you happy for this issue to be closed? :)

**Comment by Necrym59** [comment]
Hi Zac, What is the Lua statement for the control or slider for negative/positive figures selection? example going from -10 to +10
or is it a single value field control.

**Comment by ZakJudges** [comment]
@Necrym59, is this what you mean?
![Screenshot 2022-05-30 122554](https://user-images.githubusercontent.com/32545391/170982794-c14bd9ba-db25-4e02-a523-2f8ac5055a14.png)

If so, here is how I did it:
`-- DESCRIPTION: [#test1=0(-10,10)]

-- DESCRIPTION: [#test2=0.5)]`

**Comment by AmenMoses** [comment]
@ZakJudges  Looks ok to me.

**Comment by Necrym59** [comment]
Thanks Zac looks great, cheers.
