### ISSUE TITLE
Combat music playing outside combat

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3163]
I enabled combat music (cellaratmos.wav) and the ambient music track (forest.wav) and when I tested the level the combat music played instead of the ambient music, even though I wasn't in combat.

[forest.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8738131/forest.zip)

https://user-images.githubusercontent.com/32545391/169496598-201ff735-f4a4-4e70-8982-20277719e101.mp4

**Comment by LeeBamberTGC** [comment]
@ZakJudges Yes this is the functionality. The tick will force the combat to start when the level starts, mainly for levels that are always in combat at the start, and then a script can switch it off when the user wishes.
