### ISSUE TITLE
Melee attack behavior cannot handle characters with guns and vice versa

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3165]
If you have a character with the "Melee Attack" behaviour and in character settings give them a gun then in-game, the character will stand still and look at you. But you can still hear the melee attacks and they do damage to you.

If you have a character with the "Character Attack" behaviour and in character settings give them a melee weapon then in-game, the character will just look at you and sometimes move their arms slightly.

Suggest limiting which weapons characters can have based on their behaviour or moving the weapon selection to the behaviour itself.

Also, now that we have a melee behaviour, "Character Attack" should be renamed so it implies that the characters cannot use melee weapons. Perhaps "Ranged Attack"

**Comment by LeeBamberTGC** [comment]
@ZakJudges Some good points!  @rvanner Should we rename the Character Attack to Ranged Attack?  It is dangerous to remove the Character Attack behavior as many levels will be looking for that script, but we could have a system which can rename it from the UI perspective but keep the old file name in the background. A simpler option is to make it clear in the descrption that it is for RANGED combat only.

**Comment by DaveTGC2** [comment]
I personally think from an ease of user friendliness think the character should default to the correct behaviour depending on the weapon they are given. Maybe a check in the character script for the kind of weapon, if it's melee, call the melee script? When RPG goes in, I imagine users would want the characters to have inventories, and weapon swapping would be part of that. Certainly in games like Fallout New Vegas or Skyrim, NPC's will swap between the most appropriate weapon. We might save ourselves some time by addressing it early on?

**Comment by LeeBamberTGC** [comment]
@DaveTGC2 Hmm, interesting perspective.  How about this one.  We set ALL characters to Character Attack and that script can look at what weapon the character has and call the correct sub-script, be it a RANGED attack, MELEE attack, MAGIC attack, etc. That way the user can CHOOSE to explicitly set a behavior, but OUT OF THE BOX, the engine just knows which one to use?

**Comment by DaveTGC2** [comment]
Actually, that's what I was getting at, but you explained it better :).

**Comment by ZakJudges** [comment]
Note: no longer happens with default stock assets, since the guns are hidden in the Melee Attack behavior weapon drop down, and the melee weapons are hidden in the Character Attack behavior. However, DLCs pose a problem:
- Select a character with the Character Attack behavior
- Note the all DLC weapons are listed
- Select a melee weapon
- See the issue when running test level
