### ISSUE TITLE
Melee weapons don't line up with character hand

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3166]
When melee attack characters are in a combat stance, the melee weapon does not line up properly with the characters hand
![Screenshot 2022-05-20 121809](https://user-images.githubusercontent.com/32545391/169517431-4c58d2c6-d1e5-4ed8-bf25-5f47c1f46518.png)

**Comment by LeeBamberTGC** [comment]
@ZakJudges Yes, it is one frame behind the character anim frame as it only knows the position of the hand from the last frame when placing the weapon in the game. We will need a way to 'glue' objects to others so they can be resolved in the same frame, one for me for sure :)

**Comment by LeeBamberTGC** [comment]
NOTE: new weapon system for projectiles now glues the weapon directly to the hand of the character so there is no lag between animation and the weapon movement. Individual weapons can also be tweaked for better fitment, but we will handle these on a case by case report.
