### ISSUE TITLE
Character animates slowly after test game

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3169]
[entitybank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8741110/entitybank.zip)

- Happens to animated models brought into max via the importer
- Whilst the entity is attached to the cursor, the animation speed is slow
- Upon releasing the mouse button, the animation speed is fast again

**Comment by LeeBamberTGC** [comment]
Fixed a while ago :)
