### ISSUE TITLE
ladder movement issue

### ISSUE THREAD

**Issue by therickman** [TheGameCreators/GameGuruRepo#3170]
Hello , 
if the ladder is inclined  ( say 40 degrees or less  - used to bridge two zones which are not the same height ) but not straight up, moving close to the ladder's botttom  will make the character move straight up in the air, vertically. 

If you jump on the ladder from the side, you can walk on the ladder, though.

**Comment by Necrym59** [comment]
you dont need a ladder script to be used at 40 degrees you can just move normally you can set the incline in the player settings

**Comment by therickman** [comment]
Hello thanks a lot for your answer.
You are right : I just needed to set it as a static object. I can move normally on it.
So there is no issue with it then. My mistake.
