### ISSUE TITLE
BUG - Crash on Saving

### ISSUE THREAD

**Issue by TheCyberViking** [TheGameCreators/GameGuruRepo#3171]
I started having this bug since the second last update and it's really annoying while working and saving I get maybe 3 saves on a level and then GameGuru just crashes and my save gets completely corrupted. when I load back up the game the level isn't in the storyboard but is replaced by generic storyboard place holder, when I import the level file from the save location, its completely empty environment returned to the default 2.5km

**Comment by ZakJudges** [comment]
Hi @TheCyberViking, apologies for the late reply. Are you still experiencing this issue in the latest build?

**Comment by ZakJudges** [comment]
Hi @TheCyberViking I will close this issue now as I haven't been able to reproduce in the latest build. If you continue to experience the issue, feel free to reopen, or email me at zak@thegamecreators.com

Thanks :)
