### ISSUE TITLE
GameGuru Max - Bug? - Aztec Pack - Model 'Temple B' Causes Frame Drops

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3172]
I'm having some strange frame drops with both model variants of 'Temple B' from the Aztec DLC Pack, when you run up the stairs - around the top stair and floor there's some significant frame drops (see video below), not really sure what's causing it, my rig is more than powerful enough to run the engine and this is the first time the frame rate has dropped this low, i also tried this when _not_ recording in a more populated map and the frame rate on top of the model stayed at a constant 45 FPS in the same area.

The video: https://youtu.be/9IqXBlqedyQ

Some optional information: 
the only apps that were running were Steam and GG Max (plus OBS when recording, though this had no impact on the FPS.)

**Comment by Ghost-l0l** [comment]
It happens for me too, probably because it's very high poly model (there's few other high poly models in pack and same thing will happen when you try to use them).

**Comment by Lemuripest93** [comment]
> It happens for me too, probably because it's very high poly model (there's few other high poly models in pack and same thing will happen when you try to use them).

Yeah, i did an experiment and placed 8 rows of 'Temple A' down each containing 10, so 80 of them, and tried to see how my rig would fare, and my FPS would drop down to 30-something then re-stabilize and hoover around 50/60. Then i placed 1 'Temple B' in the middle and when approaching it, it would stay around 20 and 30 FPS nearly constantly until i walked away far enough from it.

Using 80 'Temple A's is probably not intended, but it's crazy what one extra model can do.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
