### ISSUE TITLE
GameGuru Max - Bug - Ragdolls Clip Through The Ground/Bug Out.

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3173]
Wanted to play around with the ragdolls to see their tolerance for certain scenarios (in this case falling), the results speak for themselves: https://youtu.be/mzUOXj9ry6s

Whilst unintentionally hilarious, this should probably be fixed.

**Comment by AmenMoses** [comment]
Apart from not making craters that looks about right. :)

**Comment by Lemuripest93** [comment]
![ggmaxdeadbodybug](https://user-images.githubusercontent.com/104637906/169714024-baade8d8-64f0-45d3-b957-e23d17c35c99.png)

This also happens sometimes during death animations, lol

**Comment by Lemuripest93** [comment]
As #3271 was closed, i will be adding the video from that post in here: https://www.youtube.com/watch?v=ms9dKSzj9SI

Personally i'd dispute these are different issues, but to reiterate... as seen in the video, ragdolls will contort and stretch in really bizarre ways, i've yet to find the reason as to why this happens, it happens at completely random times.

**Comment by Lemuripest93** [comment]
@plemsoft Really? i look forward to testing it out! :)

**Comment by Lemuripest93** [comment]
I've done thorough testing and can confirm ragdolls no longer clip through the ground, excellent work!

As for the second bug where the ragdolls stretch and contort, i've not found evidence it still exists, so i will close this for now, i will re-open if i discover the bug is still there.

Again, thanks for the fix!
