### ISSUE TITLE
Shadow Settings keep resetting when entering Test Game

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3174]
Everytime you enter a test game the shadow settings under the Shadows tab will be reset. 
For example: 
Here I set the shadows to these settings.
![image](https://user-images.githubusercontent.com/51464873/169666238-289cf4f3-140b-4f0e-ad7c-4e9d1cb03cc9.png)

And when I enter test game they revert to these settings.
![image](https://user-images.githubusercontent.com/51464873/169666199-4f5fbcf0-2c49-474f-b763-c41aba56c486.png)

**Comment by ZakJudges** [comment]
Hi @Kitakazi, I have a feeling your test level graphics settings are set to medium. Could you confirm if that is the case? You can view the setting here:
![Screenshot 2022-05-23 154838](https://user-images.githubusercontent.com/32545391/169846391-8ad5826a-6fd2-4f9b-a0ed-7ce14fe9384f.png)

**Comment by Kitakazi** [comment]
Ah yea, that must be what was going on. Thanks.
