### ISSUE TITLE
GGM - Entity Library Index Does Not Update

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#3178]
If you create a folder within the entitybank, or any file for that matter, you will not be able to see the new content appear in the Entity Library, as the index does not automatically update when you click the "Add" button.

To resolve, you should make it so when "Add" is pressed it rescans the entitybank library. Or add a small refresh button to the entity library window.

Currently, the way I update the index is by closing and re-launching GGMax completely. 

This is my first time testing Game Guru Max since its official release and the first issue i ran into.

**Comment by Teabone3** [comment]
I should add that this is also an issue for the script library. It won't show newly added scripts unless you fully close Game Guru Max and re-launch.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Forcing the ADD to refresh all librariesd would be a small performance hit, so I have placed it under the Advanced Developer Mode Tools toggle and added tooltips to guide users to this feature:

"Enable additional settings (auto-refresh library folders, physics debugging, developer mode tools, save anim templates)"

For next EXP build.
