### ISSUE TITLE
Standalone Executable Messaging Changes

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#3184]
Some changes required for the standalone experience:

1. Change this text: 
![image](https://user-images.githubusercontent.com/35840583/170019727-eb210f46-b57b-4b8a-abdf-9407b3e11200.png)
With the following replacement: "PLEASE NOTE: During the Early Access development phase, all games saved as standalone are considered test games. The games will include a startup message informing users that the game has been made with the Early Access version. If you would like to apply for the EA restriction to be lifted please follow this LINK and fill out the short form."

2. Change this text: 
![image](https://user-images.githubusercontent.com/35840583/170019819-854be0b8-7a47-4e03-8b9d-d6436f68e63e.png)
To read: "If you develop a full game and would like to apply for it to be published before the full release of GameGuru MAX then please follow this LINK and fill out the short form."

The LINK can be obtained from rick@thegamecreators.com

**Comment by LeeBamberTGC** [comment]
@ZakJudges After the design doc and script validation work assigned this week, can you make it your next task, thanks :)  Ask Rick for the LINK as I currently do not have this to hand. It is a URL to a form that users can fill in and submit.

**Comment by ZakJudges** [comment]
@LeeBamberTGC Committed to my branch, ready to test :)
