### ISSUE TITLE
GGMAX - TGC Download version - The demo games never run from Play Game button GGMax just closes down.

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#3186]
I can run the demo game from the Editor rocket button but have never been able to run one  from the  Play Game button.

Where are the demo game folders located ?

**Comment by ZakJudges** [comment]
Hi @thor49, do you see an error message when you try to use the "Play Game" button?

**Comment by thor49** [comment]
Hi ZakJudges :-  No I don't see any message.. GGMax just closes back to desktop..

Just so we are on the same page.. 
I just install GGMax and then go to Demo games and Press Play button.
I don't  have to build the standalone demo games myself.. then go and press the Play button.?
If that is the case then why is the Play button not greyed out until they are built.. ?

If they are prebuilt then where are the Exe files located.. I have searched all GGmax folders and can't find them..
Hope this helps..

**Comment by ZakJudges** [comment]
@thor49, they should just work by pressing "Play Game". All of the required files for the demo games are located throughout the install location (mapbank, projectbank, etc). 
Could you navigate to your writable folder (usually documents->GameGuruApps->GameGuruMAX unless you changed it) and then find the mapbank folder and delete any that you did not make? That will ensure the demo maps are copied again and we can try to fix the crash from there. It would also be best to make a copy of your writable folder before doing this. Thanks :)

**Comment by thor49** [comment]
ZakJudges :- OK I am doing backup copy now .. may take a while..(time remaining fluctuates between 2hrs and 20mins)
will get back to you later..

**Comment by thor49** [comment]
ZakJudges :- Ok I deleted the all demo game fpm and lst (MASM) files from the writable mapbank folder.
I then did Verify files with the Updater. 
I ran GGMax and the demo games still do not work..
One thing I notice is that the lst(MASM) files are the only ones with todays date.(30/05/2022)
take Grand Canyon demo
a grand canyon adventure.fpm (06/05/2022)
a grand canyon adventure.lst (30/05/2022)

should I try and delete the mapbank files in the GGMax non-writable folder..

**Comment by ZakJudges** [comment]
@thor49, since you verified your files with the Updater, your mapbank files should be up to date. Would you be able to record a video showing the issue? That might give me some ideas of what we can try. Thanks :)

**Comment by LeeBamberTGC** [comment]
@thor49 Is this still an issue, or has it been fixed?

**Comment by thor49** [comment]
Have just tried this on the Steam Public Preview and the DX12 (experimental) versions  and both work from the Play button.
You can now close this report...
Thanks
