### ISSUE TITLE
cant launch gameguru

### ISSUE THREAD

**Issue by chipchuh** [TheGameCreators/GameGuruRepo#3188]
![2022-05-25_202803](https://user-images.githubusercontent.com/104046757/170299884-0c9456b7-9e39-4642-91fc-64ffaadd2652.png)
cant launch gameguru
i have win 8.1 x64 nvidea 1050 Ti

**Comment by Ratall** [comment]
Gameguru Max requires Windows 10 or newer (64-bit versions only) and your GPU is under spec.  You may find gameguru Classic more suitable.

**Comment by jbthenext** [comment]
As previously stated your operating system is not supported, Microsoft ended support back in 2018. You need to update to at least Windows 10 to use GameGuru MAX

**Comment by chipchuh** [comment]
I'm wondering if gameguru supports procedural animation or programmatic bone movement to avoid using standard animation? For example, I want the character's hand to move towards the cursor and the head to look towards the camera. 27.05.2022, 18:34, "Jason Brook" ***@***.***>: As previously stated your operating system is not supported, Microsoft ended support back in 2018. You need to update to at least Windows 10 to use GameGuru MAX—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
