### ISSUE TITLE
Explosions - Enhancement Suggestion

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#319]
Hi all :)
The best way to make any game unique is to add custom media - for everything :)

Now, we have the setting to make an entity explode-able, but it always plays the same one.

It would be nice to be able to have an option to assign a sprite-sheet of  your choice. That way we can add our own custom effects for when an object is destroyed in-game.

We can always just replace the default one - yes - but if we could assign the sprite sheet to be used for each object it would make for a whole lot more interesting effects for our games.

It could work the same way as when we select an audio file or assign a lua script to an object.

Is this easy to add, or can we do it somehow already?

Reliquia....

**Comment by Shahin3d** [comment]
Hello
If it chose for each object a separate explosion texture ... I think we will have a beautiful effect.
If can add texture selection in the properties section.

**Comment by michaeloldman** [comment]
It would be nice to be able set a random angle of rotation for the sprite sheet if you wanted as well.

Maybe a new **On Destroy** category in the Properties Panel :)

![enhancementselectsprite](https://user-images.githubusercontent.com/12246318/43045569-4842c87c-8dfe-11e8-8cf2-d3025237058d.jpg)


Reliquia....

**Comment by Shahin3d** [comment]
Oh my god
this is very good
Really true
Thank you

**Comment by michaeloldman** [comment]
We would also need a setting for the positioning of the sprite. 

1) Bottom - For animations that play from bottom of the frame upwards
2) Top - For animations that play from the top of the frame downwards
3) Middle - For animations that play from the center of the frame outwards

So we could use animations that play from different points of the object being destroyed:
1) From the ground up - eg; mushroom cloud
2) From the top down - eg; an object on a ceiling
3) From middle of object - eg; something exploding in the air:

Could someone add this tomorrow please :)

I will be happy to provide some sprite sheets for the engine :)

Reliquia....

**Comment by GraPhiX-Guru** [comment]
have a look here https://forum.game-guru.com/thread/220232?page=2#msg2609133

**Comment by michaeloldman** [comment]
Hi GraPhix :)

Yes been watching your thread with great interest, you have done some excellent work there.

To my way of thinking this stuff should definitely be accessible from the Properties Tab - it just makes sense for it to be there - as it adds endless possibilities that are configurable from within the Game Guru editor.

However your tinkering is a great temporary solution :)

Reliquia....
