### ISSUE TITLE
Please make GameGuru MAX to run on Win7

### ISSUE THREAD

**Issue by bbacle** [TheGameCreators/GameGuruRepo#3190]
Can you please make GameGuru MAX able to run on Windows 7?
I know that Win10 has been out for a while, but there are many like me who still run Win7.
Thanks.

**Comment by GraPhiX-Guru** [comment]
Unfortunately that will never happen, Windows 7 is no longer supported by Microsoft, also the VR technology being used in MAX requires Windows 10.
I would highly recommend upgrading to at least Windows 10 maybe even Windows 11 as Windows 10 support will cease in 2025

**Comment by bbacle** [comment]
> Unfortunately that will never happen, Windows 7 is no longer supported by Microsoft, also the VR technology being used in MAX requires Windows 10. I would highly recommend upgrading to at least Windows 10 maybe even Windows 11 as Windows 10 support will cease in 2025

I know that Win7 is no longer supported, & I do have Win10 on my system, but I had rather use Win7 to make my games in.

**Comment by jbthenext** [comment]
This will not happen I am afraid as previously mentioned Windows 7 is now discontinued and is not relevant for new software.
