### ISSUE TITLE
GGMAX - Water level Bug in Lua

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3191]
Using Lua, setting the command SetWaterHeight(v) changes the water level attributes ok but not the visual water level, i tried using the commad to ShowWater() but it does not update the visual water level set by attributes. Is this a problem or am i missing somthing.

**Comment by ZakJudges** [comment]
@Necrym59, try calling` SetUnderwaterOff()` 
If that doesn't work then feel free to label this as a bug and I will take a look

**Comment by Necrym59** [comment]
Hi Zac tried that it didnt work is not so much underwater its the outside visual dosnt change in height. I tested the water height from 1000 to 2000 and the height responds but the water visual layers dont move they stay at the 1000 level, as a result you can drown in mid air :) there doesnt seem to be a reset or update command for the visuals it at all. I guess call it a bug.

**Comment by ZakJudges** [comment]
Hi @Necrym59, would you be able to send me the script that you are experiencing the issue with? That would allow me to reproduce it quicker and hopefully have a fix sooner :)

**Comment by Necrym59** [comment]
[ZakJudges](https://github.com/ZakJudges)
Hi Zac attached is the script attach tany object - always on
link a switch or trigger zone with logic control
thats it.
It does what its supposed to do it just doesnt do it visually, unless im missing somthing! 
[watercontrol.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8800259/watercontrol.zip)

**Comment by ZakJudges** [comment]
Hi @Necrym59, I have added a fix for this, should be available in the next experimental build :)

**Comment by ZakJudges** [comment]
The new water height was not being passed to the visuals, only the physics :)

**Comment by Necrym59** [comment]
All ok confirmed fixed
