### ISSUE TITLE
Image quality is low in Image Zone

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#320]
Image quality is low in Image Zone.
And the actual image size and quality can not be displayed.

![01](https://user-images.githubusercontent.com/36647058/43044197-1cba401e-8db7-11e8-84f8-b661dd16e262.png)

**Comment by michaeloldman** [comment]
I reckon this would be the same bug that is affecting images and fonts on Custom HUDs. It was introduced with first DX11 update IIFC :)

Reliquia....

**Comment by LeeBamberTGC** [comment]
Text has been improved in next beta build, can you provide an FPM using stock media to show the image issue, thanks!

**Comment by Shahin3d** [comment]
Thank you
I do not have a problem.
