### ISSUE TITLE
Crash when applying emissive texture from outside MAX root - 8003

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#3200]
Select a character, choose an emissive texture file outside of the MAX areas, when then test game, we get his error and a crash:

![image](https://user-images.githubusercontent.com/35840583/170698729-ecde7366-f798-4b75-98fb-7b427daea88f.png)

**Comment by ZakJudges** [comment]
@LeeBamberTGC Seems this isn't an issue in the latest build - guessing you fixed it already :)
