### ISSUE TITLE
Some zombies have emissive textures for the eyes, but have an emissive strength of 0

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3201]
![Screenshot 2022-05-27 134123](https://user-images.githubusercontent.com/32545391/170701243-a1dbe676-9063-4d1f-b0a9-27155d6c504a.png)

**Comment by LeeBamberTGC** [comment]
This is my design as most zombies will NOT have glowing eyes, it is for the user to decide to have radioactive eyeballs :)
