### ISSUE TITLE
built-in store logging issue

### ISSUE THREAD

**Issue by therickman** [TheGameCreators/GameGuruRepo#3207]
Hello, 
this is to report an issue when logging  to TGC store from within GGMAX. ( STEAM VERSION)

When the store page opens in the browser, the alternate connection method to the right is not accessible. It is the one that allows to connect via the gamecreators  account, which I use to connect via my steam account. ( and this my be the reason for the bug ) 

The solution is to connect to the gamecreators account via steam BEFORE launching GMAX. Then it works. But as I had no gmax asset in TGC , nothing happened next in gameguru max. ( no downloads message if I remember well ).

**Comment by LeeBamberTGC** [comment]
@therickman Glad it now works for you.  There is a broadcast later today at 7 PM BST where I will be demonstrating how to get a model free from the Game Creator Store and that should allow you to test the second part of the downloader.

**Comment by therickman** [comment]
Hello , this is fixed. tried with a free asset on gamecreators store and process went smoothly. Thanks !
