### ISSUE TITLE
GGMAX - Game Creator Store downloader feature not working

### ISSUE THREAD

**Issue by Zorgo33** [TheGameCreators/GameGuruRepo#3209]
I've encountered an issue with the feature to write TGC store purchased items to game guru max library trough the provided menu, it gives out an error ''could not find any files to download'', althought i have a pretty big list of assets ready to download.
![Screenshot 2022-05-28 181018](https://user-images.githubusercontent.com/27580830/170831499-1233e2c4-fb16-41fc-96c5-62f9c5b76471.png)
![Screenshot 2022-05-28 181104](https://user-images.githubusercontent.com/27580830/170831502-087c4c67-768b-4c18-869c-b79eff38a919.png)

Let me know if it's releated to the asset compatibility (then my question is quite stupid) and i'll remove the issue comment here.

**Comment by LeeBamberTGC** [comment]
@Zorgo33 How many of your purchases are flagged as GameGuru MAX compatible by the artist?  MAX will currently only show MAX compatible assets as determined by the author.  That said, you did highlight a bug showing the write folder shown is wrong, and should be defaulting to your docs folder, will sort for the next build.

**Comment by Zorgo33** [comment]
So that's what i was thinking, most assets aren't really supported for game guru max. Though i thought the engine would automatically convert them as in placing such assets in files trough file explorer

**Comment by LeeBamberTGC** [comment]
@Zorgo33 At the moment it is down to the artist and the store moderator to decide if the asset is MAX compatible (i.e. not broken) and those will show up for you.   We are looking at the process of converting Classic projects (and assets) over to MAX as this is a big request from both communities, and when we have a good and complete solution, we can create a corridor for Classic assets that we are reasonably sure will work 'out of the box'. Might take a while though for an automated process :)

**Comment by LeeBamberTGC** [comment]
Latest version working great for downloading MAX items bought from the Game Creator store :)
