### ISSUE TITLE
Standalone not working correctly on large maps

### ISSUE THREAD

**Issue by JimJamsGames** [TheGameCreators/GameGuruRepo#321]
Hi,

I have a number of issues when trying to build standalone with largish maps, I have an issue with 2 of my own maps which might be difficult to replicate due to a lot of custom media. But when build a 2 map standalone only the first map is being created.

The nearest I've come to a similar result is attempting to link 2 default maps, Contruction Site Pack.FPM and The Big Escape.FPM, (adding a winzone to the contruction site map to link to The Big Escape. In this case, most of the data appears to be transfered across, but no .exe is created.

**Comment by plemsoft** [comment]
@JimJamsGames Thanks for reporting this,

I tried your example , and it worked fine here , but there has been many fixes made to standalone export , so if you could try this in the next update and let me know if it works for you , it will really help thanks :)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Self assigned by Preben.. Not sure if it was fixed

**Comment by plemsoft** [comment]
Yes old fixed bug closing , thanks.
