### ISSUE TITLE
Door Sliding Delay Not Working

### ISSUE THREAD

**Issue by Maro32** [TheGameCreators/GameGuruRepo#3210]
Hi!

From the new update, it seems that the "Close Delay" feature of the Door Sliding behavior has no effect on the door. Even if I set an enourmosly large number, such as 10000, the door opens and closes exactly the same time as I set the delay to 0.

**Comment by Necrym59** [comment]
Close delay only works in auto mode, how are you opening it?

**Comment by Maro32** [comment]
> Close delay only works in auto mode, how are you opening it?

Ohh, I see! Thanks for the reply! I used in manual mode. The truth is I miss the delay in manual mode. Some of my doors used to open delayed, and now they doesn't work as intended.

**Comment by Necrym59** [comment]
Im looking at a change to it to add a delayed opening hopefully it be in soon
