### ISSUE TITLE
GG Max - AI - Alert other character ?

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3211]
I can remember seeing a live stream were if you had all the enemies linked, and after you attack one of them, that one alerted the others it was linked to, so then they worked as a team.

Well this is certainly not working in the current build.

**Comment by MonkeyFrogStudio** [comment]
Did you have it set up like it describes here in the User Guide:

https://gameguru-max.document360.io/docs/connecting-enemies-together

**Comment by Tum1370** [comment]
I would not of posted if I hadn’t. 
it’s not hard setting up the visual AI. 

The AI really needs a huge overhaul as it lets Max down a lot.

**Comment by Tum1370** [comment]
Am closing this one as after testing it now its been fixed already.
