### ISSUE TITLE
Standalone export no longer working, getting error

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#3213]
every time I try to export my game to standalone or any other level or project I keep getting this error.
Path cannot be found
LOOKING IN C:\PROGRAM FILES(X86)\STEAM\STEAMAPPS\COMMON\GAMEGURU MAX\FILES
Followed by 
RUNTIME ERROR 8003 O
this never happened before so I figure it's an issue with the latest build. I verified the files on steam and it couldn't find any problem. I also cut all of the files out of the folder and let them re-download then pasted back in but I didn't let any of the new files be overwritten.This way all the main files would be replaced but any of my custom files would be put back. Still getting the error though

**Comment by Tum1370** [comment]
This is already reported here. 

https://github.com/TheGameCreators/GameGuruRepo/issues/3203

**Comment by mike123yy** [comment]
Thanks, I guess I overlooked that one when I was searching .  Glad it's been reported and look at

**Comment by ZakJudges** [comment]
Hi @mike123yy, thank you for reporting this issue. A fix has been added and I will post in #3203 when the fix is available to download. Closing this issue as a duplicate
