### ISSUE TITLE
GameGuru MAX not installed

### ISSUE THREAD

**Issue by z2a2008** [TheGameCreators/GameGuruRepo#3214]
it started with the fact that GameGuru MAX stopped updating
![update_crush](https://user-images.githubusercontent.com/106475907/170870703-64d09a5c-95d1-41f0-a22f-48bc325d7381.jpg)
reinstalled the program - now it is not installed
![not_install](https://user-images.githubusercontent.com/106475907/170871071-215a3964-62ad-4d3a-934f-811975aebec7.jpg)
please help

**Comment by ZakJudges** [comment]
@z2a2008 Is there a file called "install_errors.txt" that gets generated after this occurs? It will be in documents->GameGuruApps->GameGuruMAX if so

**Comment by z2a2008** [comment]
Good afternoon.
Thank you for the prompt response.
I attach the install_error file.
Sincerely, Andrey Zykov
[install_errors.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8815837/install_errors.txt)
.

**Comment by ZakJudges** [comment]
@z2a2008 Thanks for the file, could you try to delete the file "Max\version.ini" and see if that sorts the problem? :)

**Comment by z2a2008** [comment]
Good afternoon.
If I understood correctly, the version.ini file should be located here: C:\Program Files\GameGuruMAX\Max, but it is not in this directory! (moreover, in the properties of the explorer it is indicated - show hidden files
![version ini_absent](https://user-images.githubusercontent.com/106475907/172213627-3615d28c-1f1a-470e-85e8-bab4e76c8e97.jpg)
)

**Comment by LeeBamberTGC** [comment]
@z2a2008 Looks like a bad installation, are you running low on Disc space?  Here is what my folder looks like:

![image](https://user-images.githubusercontent.com/35840583/172214156-8456e283-a075-4763-8326-c94cdbf267f9.png)

Let me know if you want to switch to a Steam key as some users found this smoother on some systems.

**Comment by z2a2008** [comment]
06.06.2022, 20:33, "Lee Bamber" ***@***.******@***.*** Looks like a bad installation, are you running low on Disc space? Here is what my folder looks like:Let me know if you want to switch to a Steam key as some users found this smoother on some systems.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>Good afternoon.After analyzing the situation with the incorrect installation of GameGuru MAX, I came to the question - did I download the correct distribution? Is the GameGuru MAX Tiny file really Installer.exe can it have such a small size (137.80MB)?Sincerely, Andrey ***@***.***

**Comment by LeeBamberTGC** [comment]
The tiny installer is indeed a small file, but when you run it, it will connect to our server and download the rest of the files which is about 3-10GB, depending on what asset collections you tick.  Once installed, you can click the VERIFY FILES that will ensure your local files match the ones on our server.  Might be worth repeating the installation step a fresh, and make sure you have at least 20GB free on your main Program Files drive.

**Comment by z2a2008** [comment]
"..Let me know if you want to switch to a Steam key as some users found this smoother on some systems.."
let's try switching to the Steam key (maybe it will help solve the problem). What needs to be done for this?

**Comment by LeeBamberTGC** [comment]
@z2a2008 If you use our support system and make this request, a team member can sort that for you. Here is the link: https://www.thegamecreators.com/contact

**Comment by ZakJudges** [comment]
Closing this issue as the old updater is no longer in use. All users were sent a Steam key, available from their TGC account dashboard
