### ISSUE TITLE
Spawning in a character, with Character Behaviour set to Ally causes them to do no damage for their opening shots. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3215]
See video:  https://www.youtube.com/watch?v=mRzFx_Oogn4

What I expect: 
Ally spawns in, walks to the flag linked to it and then upon seeing the enemy instantly kills the enemy with the first pistol shot. (enemies HP is set to 1)

What happens:
Ally spawns in, ignores any flags linked to it, walks past the enemy then turns towards it and shoots many rounds at a point blank range and the enemy takes no damage. 
Also when the Enemy gets shot by the Ally there is no blood impact decal that shows them taking damage.

**Comment by Kitakazi** [comment]
Reopening as this bug is now back.

**Comment by LeeBamberTGC** [comment]
Not reproduced in the next build, but allies are lethal from the moment they spawn now. Also fixed issue with their strength being correct when they spawn (and do not take damage as a result when spawn).

**Comment by Kitakazi** [comment]
fixed. closing.
