### ISSUE TITLE
collisions

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3216]
just spent the last week in blender and importing these models into max.

the collisions work in the editor.

in the game test MOST if not all of them HAVE no collisions.

![image](https://user-images.githubusercontent.com/68471279/170910158-000e90f7-6651-416d-8e61-f187f10e38fd.png)

Im actually fuming.

a week of work wasted. 

gonna go head butt a wall.

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/170911301-ece73e05-cce7-4bd9-b418-8794c8547691.png)

**Comment by casigus** [comment]
and of course.

https://www.youtube.com/watch?v=BQSHA-DxUic

and im done. good night/morning. 5am. been up to long trying to fix this.

**Comment by ZakJudges** [comment]
Hi @casigus, so I can look into this issue for you, could you send me one of the models you are experiencing the issue with? If possible, the original source file (fbx/glTF/etc), as well as the dbo and fpe that was created after importing into Max. Thanks!

**Comment by casigus** [comment]
yeah! put a few of them in a zip for you! theres some obj there too, but there zero texturing on them ones, but yeah here you go.

https://drive.google.com/file/d/1bHL8fTxTwDgdvqMk--zfEuw74fPRniL6/view?usp=sharing

**Comment by ZakJudges** [comment]
Hi @casigus, I imported two random objects and both had correct collisions. Would you be able to send me the dbo and fpe on one that you have no collisions with? Thanks!

**Comment by casigus** [comment]
Did you import the glf models? Those are the ones causing the issues..I'll send them over when get to my desk too ????


On 31 May 2022, at 09:30, ZakJudges ***@***.***> wrote:


Hi @casigus<https://github.com/casigus>, I imported two random objects and both had correct collisions. Would you be able to send me the dbo and fpe on one that you have no collisions with? Thanks!

**Comment by ZakJudges** [comment]
@casigus Yes, I tried a few of the glTF ones. Here are the results:
![Screenshot 2022-05-31 110040](https://user-images.githubusercontent.com/32545391/171148380-af69207b-acc7-4608-998a-50d15c32adbe.png)

**Comment by casigus** [comment]
so why is my pc not importing thing correctly. OBJ's work fine but these dont. how can i bring up this mode so i can show you what mine look like?

**Comment by ZakJudges** [comment]
@casigus Can you send me a dbo and fpe of one of the models you are having the issue with?
To render the physics shapes, first make sure that this checkbox is ticked:
![Screenshot 2022-05-31 131004](https://user-images.githubusercontent.com/32545391/171170255-4e1749ff-f463-4313-ac0d-4ce19266fc27.png)

In game, you can then press tab tab and you should see this option:
![Screenshot 2022-05-31 131033](https://user-images.githubusercontent.com/32545391/171170349-d103f60e-24c2-4f87-9c40-adf11ef612fc.png)

**Comment by casigus** [comment]
opps. ahah

https://drive.google.com/file/d/1613nXmmHFxPzN5FoV734R9p2yAgmoZtn/view?usp=sharing

well theres a few there.  ive just started model import from blender but to objs, so far collisions are good.
