### ISSUE TITLE
GG Max- Bug - Group Bug ? Barrel Bug ?

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3219]
I created a burning barrel, consisting of 5 planks of plywood, a barrel, the flames and a smoke particle.
Now after creating a group of these 8 objects, the objects that i grouped, when i click the barrel, the barrel materials automatically change different settings.
The Grey Barrel - Damaged is suppose to only have Cast Shadows ticked, and the Transparent and Double Sided are not ticked.
But as you can see in the screenshot, the barrel now has Cast Shadows unticked, and Transparent and Double Sided ticked.

This is easy to fix as you just change the settings back, But this must be a bug with possible groups, and the barrel taking on the properties of something else in the group when I click the barrel. 
Its more of a frustrating bug having to keep changing the properties back to what they should be.

![Untitled](https://user-images.githubusercontent.com/66874403/171177761-ee0a69fe-b308-40d1-92a2-d839ce8c5ed5.png)

**Comment by plemsoft** [comment]
@Tum1370 This is not a group problem , but a problem with what is selected , this has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
@plemsoft 
Mine works fine with the weapons like that.
follow this.

Create new project, and delete HUD, add RPG huds.
Create blank level.
Add Magnum pistol starter weapon to player start marker.
Place "Golden Goblet" in front of player, change from Static to Physics On, Tick Is Collectable.
Add behaviour "Armour" so we can pick this up, else we cannot collect this.
Create collectable.
(Maybe save and reload to make sure collectable works)
Now TEST GAME

When looted golden goblet, place it in the hotbar anywhere.
Then move it back from hotbar to inventory.

Your gun is now messed up.
