### ISSUE TITLE
GGMax - Bug/Oversight - Ragdoll - Shooting multiple enemies piled on top of each other causes them to "die" standing

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3222]
I noticed if multiple enemies follow you down a narrow corridor or through a doorway and you kill all of them quickly in rapid succession, some of them tend to "die" while they are still standing because I guess their bodies still have physics/collision on after they're dead, which the other bodies' ragdoll treat as an object? 

Maybe disable collision on ragdoll objects with other ragdoll objects? Not sure what to suggest here!

****Here's a screenshot. Dead men may tell no tales but they do appear to stand around from time to time!**

![ragdoll_oopsies](https://user-images.githubusercontent.com/103399301/171234085-ad39e84e-f1ca-4548-9f6d-544e0bf5cdce.jpg)

**Comment by LeeBamberTGC** [comment]
@Kravenwolf This one has been a long time coming. Spent some time refining the ragdoll, adding it to the physics debug toggle so you can see the ragdoll capsules, and adjusted the masses so almost all characters will collapse under its own upper body weight:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ddc93c1d-0fcc-48c1-b9b0-946586debd27)
For next EXP build :)
