### ISSUE TITLE
GGMax - Bug - Saving group objects appear to reset some of those grouped objects' rotations/positions

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3223]
I created a makeshift "spotlight" using a post, a light fixture and a light marker. I had to rotate the light fixture to align it with the post, and the post is scaled up by about 400%. I think it turned out alright:
 
![group-bug1](https://user-images.githubusercontent.com/103399301/171235214-2c644930-bd8d-42ba-9db8-3b90d7be133b.jpg)

After grouping those 3 objects and saving them as a new object, adding that newly saved object to the map appears to have reset the rotation/orientation of some of those objects within that grouped object (I think that makes sense; here's a screenshot to show what's happening -- I rotated the light fixture to stand vertically, after adding the grouped object to my map, that light fixture's rotation was set back to it's default value, and the light marker appears to have changed it's position, too):
 
![group-bug2](https://user-images.githubusercontent.com/103399301/171235202-9463bed6-3aad-43bf-a6e8-d4d419a684c9.jpg)

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Plenty recent work on Smart Objects, and created groups should now retain all their set properties.
