### ISSUE TITLE
GGMax - Bug - Importing a custom object or character will reset the sky box's ambient light values to their defaults

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3227]
Adding a custom imported character (from the character creator), or a custom grouped object, or custom imported 3D object appears to, for some reason, reset the "Lighting Color" and "Ambient Color" values for whichever skybox you have selected, if you customized them.

Strangely though, this change appears to only occur in the editor. Jumping into test game loads the custom light values you changed. Jumping back out of the game and into the editor shows the default values again.

May need someone else to test this one to confirm? Select a skybox, change the Lighting and Ambient colors, test game. Then return to the editor and create and import a new character (or create, save and import a new grouped object). The skybox should change.

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Confirmed, now fixed for the next EXP build.
