### ISSUE TITLE
GGMax - Bug - Picking up a third weapon "hides" one of your weapons from cycling through on the mouse wheel

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3228]
_(Confirmed multiple times)._ 

To test, add the patrol rifle and the pocket knife on the ground. Then a bit ahead of those, add the M67 grenade. Pick up the first two, and use the mouse wheel to scroll back and forth between them.
 
Then pick up the M67 grenade. Now, use the mouse wheel again to cycle through your three weapons and you'll see that one of them is missing! 

Is it magic? Probably not, because all 3 of the weapons you've picked up can still be accessed by pressing the number keys!

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
