### ISSUE TITLE
Game Guru MAX - Model importer issue

### ISSUE THREAD

**Issue by Zorgo33** [TheGameCreators/GameGuruRepo#3229]
I've noticed the model importer having a little problem when choosing to edit all mesh materials, the option to use RGBA buttons doesn't seem to work. For choosing each separate part it does work, only for all mesh materials not.
![Screenshot 2022-06-01 012836](https://user-images.githubusercontent.com/27580830/171294888-f830c4a1-d490-4656-a3bf-be88e6c8d703.png)

**Comment by Zorgo33** [comment]
(Also, on editing materials outside the model importer - in the level, RGBA buttons feature isn't there at all)

**Comment by LeeBamberTGC** [comment]
@Zorgo33 You can now specify the RGBA textures during the import process with ALL MESHES selected in the NEXT EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/67eaf4bc-dc14-4497-a1ba-b082c00a5709)
