### ISSUE TITLE
Grouped objects bug

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3232]
Placing objects on or near duplicates of a group often adds them to the group.

To test. group some objects. Duplicate that group so there is more than one of them.

Place another object near on in that group. The object will become part of that group.

**Comment by LeeBamberTGC** [comment]
@davetgc Created a group and duplicated twice, then added a new ball near the third group but it did not stick to the group:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0cc89500-ecec-4d4b-a418-892362d5d10a)

**Comment by davetgc** [comment]
I can't replicate now, so I'm saying it was fixed with an earlier update. Thanks.
