### ISSUE TITLE
Enemy characters holding custom weapon no muzzle flash

### ISSUE THREAD

**Issue by jbthenext** [TheGameCreators/GameGuruRepo#3233]
When enemy characters are holding a custom weapon there is no muzzle flash.

See any of the BSP weapons on the store for examples

**Comment by LeeBamberTGC** [comment]
@jbthenext Looks like any decals in the writable area (where purchases are downloaded) were not being included in the decal list, and so the characters did not know how to find the decal to show during a muzzle flash. Sorted for the next build.  Also accounts for weapons carried by characters but not placed as a collectible in the level (a related bug).  Further fix ensures bulletholes and impact decals occur all the time, as fixed an issue causing them to disappear sometimes. Phew, 3 for the price of 1.  Next build in Steam EXP Build in 24 hours :)
