### ISSUE TITLE
Key+Door Issue

### ISSUE THREAD

**Issue by Maro32** [TheGameCreators/GameGuruRepo#3234]
Hello!

There's an issue when you use the 'Key' and the 'Door' behaviors toghether. If you pick up the key and use it to open the door, the key will respawn to it's original place. You can try it in the Canyon Offensive demo map.

**Comment by LeeBamberTGC** [comment]
@Maro32 Fixed a while ago, now you can drop down a key, then a door, then logically associate the two, make a small change in the door behaviour properties and test level, and the key will need to be collected before the door can be opened, and the key will not return when used.
