### ISSUE TITLE
The fish that come with the Booster Pack swim through walls

### ISSUE THREAD

**Issue by Thedric** [TheGameCreators/GameGuruRepo#3238]
They behave great, otherwise, but when I try putting a wall down into the water, so I can block off an area, they swim right through it. I'm using the brick walls from the Aztec DLC, and I certainly can't WALK (or swim) through them, so I think the collision mesh is all right. But the fish just glide on through. I wouldn't mind, if I had another way to contain them in an area (other than trying to build a berm out of raised ground around the space—that always moves all of my models around and drives me insane). I just want to make a sort of fish pond that I can walk around.

**Comment by LeeBamberTGC** [comment]
@Thedric Fish can now be penned in for the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/15ac1b13-6924-4187-a9f4-4434db0cc24b)
