### ISSUE TITLE
GameGuru MAX - Request - Hide Game Elements

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3241]
When working on a level, sometimes things can get crowded with all the game elements - flags, various zones, particles, player start, etc. It would be great if we had a button to hide/unhide these elements so we could concentrate on level building. We already have buttons that hide/unhide logic nodes for Shooter, RPG, and Puzzle. So, one more for Game Elements would be great, I think.

**Comment by Kravenwolf** [comment]
Make it the "H" key like Blender, please, just for me, so I don't need to remember two hotkeys :)

**Comment by synchromesh62** [comment]
Apologies if im misreading this but isnt this already in the Game Element View Options ?

![Z1](https://user-images.githubusercontent.com/35708217/171843273-0f233f96-b7a8-4ae3-bc42-7bc93caef61b.png)

![Z2](https://user-images.githubusercontent.com/35708217/171843288-1da626f0-99d1-4731-9a6c-4cc81def93ac.png)

**Comment by MonkeyFrogStudio** [comment]
Wow! No! You are completely correct! I keep forgetting about that area even being there! I will close this because, well, it's already a thing! Thank you, @synchromesh62 !
