### ISSUE TITLE
GGMax - Bug - You can walk inside one specific type of auto-generated trees (collision issue)

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3242]
When creating a forest terrain biome(?), one of the auto-generated trees with a specific texture (?) (see screenshots) has an issue with collision. The player can walk through one of it's sides and stand directly inside of it's center:

![tree-collision1](https://user-images.githubusercontent.com/103399301/171751756-619340ea-7ae2-4e0f-8d55-5a76896fae23.jpg)

![tree-collision2](https://user-images.githubusercontent.com/103399301/171751766-1809239d-cc65-422b-b981-c0120dd8f3cf.jpg)

 
On the other hand...it **_is_** a nifty place to hide some super-secret dev-ammo! Sorry, couldn't resist :)
 
![tree-collision3](https://user-images.githubusercontent.com/103399301/171752036-42a55ef6-22c9-4305-9d58-d48284c68085.jpg)

**Comment by LeeBamberTGC** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0721a8e9-4e2c-41e8-8b3a-3339e6f905fe)
All 38 tree types fixed for next EXP build
