### ISSUE TITLE
MAX - Importer Shows Multiple Versions of Surface

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3244]
When you import a model the import window shows multiple versions of the surface map.
Using Steam Version here:
![image](https://user-images.githubusercontent.com/12246318/171773537-3f12c31b-109b-4fc3-af7c-e7dbdf094d42.png)

**Comment by LeeBamberTGC** [comment]
@OldFlak Fixed for next EXP build

**Comment by OldFlak** [comment]
Sorry Lee this is sorted - just forgot to confirm :)
