### ISSUE TITLE
MAX - Editor Forgets Grid Settings

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3245]
Editor always defaults Grid Offset to 50.0 
Would be nice if it remembered when it is set to 100.0

**Comment by MonkeyFrogStudio** [comment]
Agreed. I requested the same thing (and a bit more) here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3023

**Comment by MonkeyFrogStudio** [comment]
This should be fixed in the latest experimental update! :)

**Comment by ZakJudges** [comment]
Closing this issue as confirmed fixed in #3023

**Comment by OldFlak** [comment]
Nice, it will be a useful addition - thanks :)

Not using experimental here yet, but when it has some of the more important bugs sorted will move to it.
