### ISSUE TITLE
MAX Dynamic Lua - inconsistent handling of "file" type variables

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#3246]
If the dynamic Lua in the script contains the word 'file', e.g.:
-- DESCRIPTION: [TextFile$=""]

Then in the editor you get the ability to browse for a file and select it, which then passes the full path of the file into the Lua script.
![file selection](https://user-images.githubusercontent.com/35708338/171848493-885c09bb-86c0-412a-b86d-b10b6472410e.png)

This is great but unlike for videos or sounds the file is not copied over to the standalone.
Nor, like for videos and sounds is the file looked for in a MAX subfolder (i.e. the 'speech' files are looked for in audiobank and videos in videobank).

Maybe as part of the 'file' handling you could add the ability to pass in a default subfolder in which the file browser should look (e.g. "scriptbank/Cine Guru" or maybe have a databank folder as a repository for files.

So when a user is creating a cinematic for example they could select the action files, cinematic specific images, subtitles files, credit files etc in Files/databank/cinematics  rather than having them scattered all over the place.

Oh and referring to the image above, there is no option to delete the sound entries that aren't needed!

Btw, when you get around to RPG and Adventure genres the ability to load text files into behaviours is going to become really important, things like subtitles for character dialogue or lists of inventory items make a lot of sense being stored in text files.

**Comment by ZakJudges** [comment]
Hi @AmenMoses, thank you for reporting these issues, and apologies for the late response!

I have added a fix for the files not being copied over to standalone. I have also created separate issues for the feature requests (#4169, #4170)
