### ISSUE TITLE
GGMax - Bug - After changing water height, the terrain sculpting brush does not work unless you switch to object mode and then back

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3251]
Sculpting brush disappears and refuses to do anything after you change the water's height. Switching the the brush to paint terrain, grass and trees still function. Switching back again to the sculpting brush show it's still hidden and inoperable. 

To recover the sculpting brush, you have to switch into object mode and then switch back to terrain mode.

**Comment by DaveTGC2** [comment]
I can confirm this.

**Comment by ZakJudges** [comment]
Hi @Kravenwolf. Thanks for reporting and apologies for the late response. I have added a fix for this issue to the experimental build on Steam

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
