### ISSUE TITLE
Scripts that come with the game don't always activate

### ISSUE THREAD

**Issue by Thedric** [TheGameCreators/GameGuruRepo#3253]
I have several NPCs in my game, all from the Aztec DLC, and I've been having trouble with them activating sometimes, but not always. For instance, one NPC is a guy in a cage (this one, I actually created in the Character Creator) and I'm using the "Hostage Runs Away" script. He is generally kneeling down, when I test the game, but whether or not he jumps up and runs away seems to be kind of random. Sometimes he does; sometimes I can keep bumping into him over and over again, and he just sits there. 

I have a couple of NPCs wandering around, following flags, and they work reliably. The slave girl using the "Wander Around" script generally works, but sometimes she's just standing there motionless. 

I'm on Windows 10 with 64GB RAM, using an NVIDIA GeForce RTX 2070 with 8GB.

**Comment by LeeBamberTGC** [comment]
@Thedric Plenty of work on AI, navmeshes, characters since this report. If you find time, check out the AZTEC level in the HUB and confirm if these issues are now resolved on that stock level and your own creations, thanks!
