### ISSUE TITLE
MAX Logic links not freed up when entity deleted

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#3254]
e.g.  Plonk down eleven  active entities and connect one of them to the other ten.

Now delete the other ten and plonk down another active entity and try to link them, it won't allow it. 

Whilst on the subject it might be useful to have Lua commands that can make/delete the logic links at runtime.

One reason for this would be if you need to trigger 20 entities from one camera the connections on screen will become a right mess very quickly (if more than ten were allowed of course!) but if the script could make the links then I could use linking/repeater objects dotted around the map each connected to one of the entities that need to be triggered and then at runtime the script could create the links under the covers to link them all up so the logic works, also it would enable scripts to clean up logic links that no longer attach to valid entities (for example because the linked to entity has been destroyed or has no health).

**Comment by ZakJudges** [comment]
Hi @AmenMoses, apologies for the late reply. I have uploaded a new Steam experimental build which should fix this issue. Once the fix is confirmed, I will keep the issue open as an enhancement for the visual logic Lua commands

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
