### ISSUE TITLE
Cannot place Video File Into Documents Videobank folder and play videos from there

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3257]
**Reported on Steam and confirmed.** 

No import Video button for Videozones.
You can manually copy them into the videobank first of course but only the core videobank works
Although visible once placed in the GameGuruApps\ files \ videobank they will not work when selected,

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Hmm ok but how are users supposed to use their videos in a video zone ?
Unless they copy them to the core videobank or is that the intention.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Yes copy your custom video to the "Documents\GameGuruApps\GameGuruMAX\Files\videobank\user" folder, then select it from the Video Zone:

![image](https://user-images.githubusercontent.com/35840583/173338275-48c7a6d8-ffa4-458c-ba72-c9c58069fa3f.png)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
I think we have crossed wired here .. 
 "Documents\GameGuruApps\GameGuruMAX\Files\videobank\user"
Thats what i have been saying you can copy them there and select them ... But they do not play.

They only play if you copy then to the C:\Program Files (x86)\Steam\steamapps\common\GameGuru MAX\Files\videobank.
Then they will play ... Or is it just me ?
