### ISSUE TITLE
Grenades underwater

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#326]
One for Lee

https://youtu.be/BlGYH9kVKkA

Dave

**Comment by Teabone3** [comment]
With most games grenades do work under water, only they do not display the same explosion particle/decal. Instead its a water based visual.

**Comment by Granada1** [comment]
Very true here is a better one 

https://youtu.be/mc7Oxg19lVU

Dave

**Comment by ErrantAI** [comment]
Yes please.

At a basic level, have a small splash when projectile hits water (like the gun hit effect or a small amount larger) and then the scaled up splash effect that currently happens upon detonation in addition to the projectile's normal explosion effect.   No additional assets are needed to make this happen at a basic level.
