### ISSUE TITLE
Glitch in terrain editor

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#3260]
latest update (27/05/22) feels like it did before EA. Anomalous graphics issues in the terrain editor, freezing within the level editor, and crashes when trying to import custom meshes.

Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
32GB DDR4 RAM

NVIDIA GeForce 3060 RTX Laptop

![image](https://user-images.githubusercontent.com/82544140/172026572-95c9b72a-4c63-40fa-b73c-693d00f965ab.png)
![unknown](https://user-images.githubusercontent.com/82544140/172026595-cebc14e5-eb66-43ff-8bba-65c883579495.png)
![unknown 1](https://user-images.githubusercontent.com/82544140/172026599-18c6e507-89ef-4520-8cd1-1ac93f5b72ce.png)

**Comment by mav3r1ck198-1** [comment]
![image](https://user-images.githubusercontent.com/82544140/173144556-13473191-89d3-4279-91b0-500a94850495.png)


Continues to happen with the latest update, then crashes to desktop

**Comment by LeeBamberTGC** [comment]
@mav3r1ck198-1 Try updating to new graphics drivers, I also had a strange crash a while ago, and when I moved to the latest NVIDIA drivers, no more crash.  Do you see this with any of the demo levels provided in the HUB?
