### ISSUE TITLE
Im preorder user and could'nt get the latest update. 

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3261]
Hi, I have tried to update GGmax last Friday 06/03/22 but the software doesn't show any new version of ggmax. I also tried yesterday and today as well with no luck, so how can I get the latest update. Also, is it possible to get the steam version instead of the standalone version of GGMax??

**Comment by MonkeyFrogStudio** [comment]
There was no update last Friday. This was announced during the live broadcast the Wednesday before.

**Comment by Hamada880** [comment]
Okay, how about way to get the steam version instead of the standalone edition is possible?

**Comment by MonkeyFrogStudio** [comment]
You have to contact TGC (the people you bought MAX from) and ask them about doing the swap.

**Comment by synchromesh62** [comment]
Contact Rick on Customer Support.
He will be able to swap for you.

**Comment by LeeBamberTGC** [comment]
@Hamada880 Let me know if our support system helped, and if so, I can close this :)

**Comment by Hamada880** [comment]
I will reach out to Rick, thanks guys and thanks Lee. You can close it.
