### ISSUE TITLE
Massive frame drop

### ISSUE THREAD

**Issue by DaveTGC2** [TheGameCreators/GameGuruRepo#3263]
I accidentally added some physics objects half submerged into the ground. Dropping the FPS from 50=60fps to 4fps.  Framerate not restored even when there objects are set to static.  Sometimes relaunching MAX fixes the issue. Seems as if MAX is getting caught in a physics loop.

![image](https://user-images.githubusercontent.com/101805541/172044923-4eec0806-f0aa-49fc-a8da-b51d3bcdb368.png)

**Comment by SampeyFS** [comment]
Yes, I too put 4 houses down to 18 FPS from 40 that was going
