### ISSUE TITLE
Entire level disappeared, blank level.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3264]
![image](https://user-images.githubusercontent.com/99803873/172047792-97aaeafe-a2d1-401e-a303-83adda9ac0db.png)

On relaunch level data missing!

Previously:
![20220604140858_1](https://user-images.githubusercontent.com/99803873/172047869-8c83e0e4-92c6-4167-927d-30f9798c57ad.jpg)
![20220604140953_1](https://user-images.githubusercontent.com/99803873/172047870-0f2ef857-b3b9-4d17-b261-533c702ce980.jpg)

Project file attached: Lots of custom media:

[Overland.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8839850/Overland.zip)

**Comment by davetgc** [comment]
[mapbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8843204/mapbank.zip)

**Comment by davetgc** [comment]
Added mapbank files as well.

**Comment by plemsoft** [comment]
@davetgc Your project was setup to use "mapbank\Main World.fpm" and not "Scortched.fpm" did you delete "Main World.fpm" ?

**Comment by davetgc** [comment]
@plemsoft - Whoops. sent the wrong files
[mapbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8843507/mapbank.zip)

Basically, the file no longer seems to contain any data.
.

**Comment by plemsoft** [comment]
@davetgc Yes the map is empty, must have crashed while saving.

@LeeBamberTGC This commit could overwrite mem/code and cause a crash:
https://github.com/TheGameCreators/GameGuruV3Repo/commit/0948ee555132f350d377ca7b6f48086b7d3e469d
"i" should have been "j".
