### ISSUE TITLE
MAX - Orientation of physical object not matching visible orientation in editor

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#3265]
So this one is hard to explain so I'll just say what happened and how I found it.

The cinematic scripts use the Lua function GetObjectPosAng( objectId ) to get the position and orientation of the camera and endpoint entities, then at runtime the cinematic camera is moved along the path between them and rotated from the starting orientation to the endpoint orientation.  (rather simplified version btw)

Anyhow I had a camera and endpoint in the editor  which were visibly orientated completely differently, i.e. the camera was pointing down towards the scene and the endpoint was pointing horizontally at the scene.  The test level had been saved and reloaded which may have something to do with what happens next.

So in test game the cinematic camera did not rotate!

After several hours of head scratching and placing debugging Prompts into the scripts I came to the conclusion that the only way what I was seeing was possible was if the GetObjectPosAng call for the endpoint was returning the same angular values as it was for the camera, even though visually in the editor they were different.

So I then simply rotated the endpoint a tiny bit in the editor and bingo, it worked perfectly.  (I surmise that this tiny adjustment was enough to update the physical object internally to match the visible one)

So at a complete guess what is maybe happening is that certain ways of rotating entities in the editor (maybe using the shortcut keys which I do a lot) do not update the physical object whereas using the widget did seem to update it, alternatively the only other cause I can think of is that on saving the level and reloading it the physical orientation is not updated to match the visual one.

Without knowing what caused them to be different in the first place makes it hard to replicate but I will try to do so when I have nothing better to do.

**Comment by AmenMoses** [comment]
So it maybe a coincidence but I just loaded my cinematic testing level and some of my camera trigger zone entities were showing the entity as being in a different position from the zone itself, I deleted them and put down new trigger zones to continue testing and MAX promptly crashed out with no error when I clicked on one to move it.

Anyhow, a possible cause of this is that the saving and reloading is somehow not retaining positional data on all entities correctly, seems to be only active entities that are affected for me but I've seen others reporting entities moving around and from their description it sounded like they were referring to static entities.

**Comment by Necrym59** [comment]
Object collison boxes do not rotate more than 90 degrees they revert back to their original angles even though the visual of the object does rotate more than 90 degrees.

**Comment by AmenMoses** [comment]
@Necrym59 You are probably only looking at the Y angle, this doesn't exceed +/-90 degrees as that is where the Euler gimbal points are at.
If you look at the X & Z angles at the same time you will see they flip 180 as the Y angle goes through the gimbal positions.
That's just how Euler angles work.

**Comment by AmenMoses** [comment]
I seem to get the problem more often when I use the R key to rotate stuff btw.

**Comment by AmenMoses** [comment]
As I don't actually know what caused it to happen in the first place all I can do is wait for it to happen again, of course if you have fixed it then it won't happen again!

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
