### ISSUE TITLE
partial collisons

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3266]
more collision issues.

half of these collisons work.

some don't

theres no pattern to it. another week wasted doing custom models.

![image](https://user-images.githubusercontent.com/68471279/172071776-7cfaa70c-caf7-4eed-82fb-b09c6f2144c0.png)

**Comment by davetgc** [comment]
I believe this may be to do with the offsets during importing. @LeeBamberTGC - I've emailed you a model that seems to be affected by no collision.

**Comment by davetgc** [comment]
https://user-images.githubusercontent.com/99803873/174068208-f4243163-3867-4d00-9822-ea102d611e2a.mp4

**Comment by LeeBamberTGC** [comment]
@davetgc Yes, it is related to using the offset feature in the model importer. NOw fixed for this Friday's update :)

**Comment by LeeBamberTGC** [comment]
@davetgc Also fixed the separate issue with the strange static building that had bones in for some reason, ready for this week's build:

![image](https://user-images.githubusercontent.com/35840583/174817699-5fcf199a-af85-48b3-b9af-7cf5410a823f.png)

**Comment by ZakJudges** [comment]
Hi @casigus, are you happy for this issue to be closed now? :)

**Comment by casigus** [comment]
this is still an issue yeah actually, but ive found work arounds for it.

**Comment by ZakJudges** [comment]
@casigus Thanks. Could you email one of the models that still has the issue to Lee? :)
