### ISSUE TITLE
Fix issue of black squares, missing images when return to HUB from Terrain Generator

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#3269]
See if can reproduce issue of creating a new project, new terrain, but then cancel the terrain generation process and return to HUB, are the images missing:

![image](https://user-images.githubusercontent.com/35840583/172204595-683ee317-e887-4717-a6c0-ae21aed52f0d.png)

**Comment by ZakJudges** [comment]
Note: unable to reproduce, no further reports of issue. Downgrading to medium

**Comment by LeeBamberTGC** [comment]
Not able to reproduce in latest build.
