### ISSUE TITLE
GameGuru Max - Bug - NPC's Ragdolls Strangely Twist/Contort

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3271]
I haven't seen this reported yet, not sure if you're aware of this one, but when shooting an NPC they sometimes twist/contort into weird shapes, i made a video showcasing the bug here (fair warning, this could be considered nightmare fuel): https://www.youtube.com/watch?v=ms9dKSzj9SI

I'm not quite sure what causes the bug, but i've had more luck replicating it when shooting an enemy from the back a certain distance away, though it does also happens during close combat as seen in the latter part of the video.

This post can also be considered a follow up to the one i made here: #3173

**Comment by ZakJudges** [comment]
closing this issue in favor of #3173, all further discussion can take place there
