### ISSUE TITLE
GGMax -> Zombies

### ISSUE THREAD

**Issue by realPrunelle** [TheGameCreators/GameGuruRepo#3272]
Can anybody tell me why the Zombies go through walls? Is it normal ?

[](https://www.youtube.com/watch?v=xQF607YnAnM)
https://www.youtube.com/watch?v=xQF607YnAnM

**Comment by realPrunelle** [comment]
Will there happen something to this?

**Comment by LeeBamberTGC** [comment]
@realPrunelle Can you create a new small FPM level with stock assets showing the zombies escaping their seal compound and I can try and reproduce here? The arms sticking through the wall is a known bug and will require the zombies to detect if they have space in front of them, and if not, lower their arms (or rather not use the arms outstretched pose). You can manually change this animation in the Zombies properties, maybe select Gammy Hand mode.

**Comment by realPrunelle** [comment]
> @realPrunelle Can you create a new small FPM level with stock assets showing the zombies escaping their seal compound and I can try and reproduce here? The arms sticking through the wall is a known bug and will require the zombies to detect if they have space in front of them, and if not, lower their arms (or rather not use the arms outstretched pose). You can manually change this animation in the Zombies properties, maybe select Gammy Hand mode.

Hey Lee,

you got my mail some days ago?

Greetings,
Andreas

**Comment by LeeBamberTGC** [comment]
@realPrunelle I cannot locate the email alas. Can you resent to lee@thegamecreators.com thanks!

**Comment by realPrunelle** [comment]
I send it days ago. Did you get it? If not, I can write it here.

**Comment by LeeBamberTGC** [comment]
@realPrunelle Got it now, thanks!!
