### ISSUE TITLE
GGMax - Bug -CRASH - copy/pasting several objects you have selected together multiple times (Shift+Left-Click) crashes editor

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3276]
I tried putting 100 exploding red barrels together in 10 rows of 10...for...ahem...science. (Certainly wasn't going to stack a bunch of things on top of them and watch everything go flying everywhere, if that's what you were thinking!)

ANYWAY, using this copy/paste method when selecting multiple objects together too many times appears to crash the editor. 

**Video:**
**https://www.youtube.com/watch?v=iKm4QIiAep0**

_(Please also note the grid snapping tool needs work. It's having trouble detecting where other objects are to snap to them.)_

**ADENDUM:** **After further testing, it appears attempting to copy/paste too many objects at a time crashes the editor. But, that's not ALWAYS the case. In my third test, there were no issues when I was copying 5 objects at a time. 10 worked, too. Attempting to copy/paste 20 worked once. Second attempt crashed the editor. But in the video example, you can see I duplicated 20 objects multiple times without any issue. However, it did crash in a previous test map before just duplicating 10 after 90 were in place. Maybe objects already copy/pasted in this way when then copy/pasted AGAIN is somehow causing this issue?**

**Comment by ZakJudges** [comment]
Note on this issue: If you copy required number of objects to cause a crash, but instead of pasting the objects you save the level, you will get a read access violation at this line:
writer.WriteString( t.entityelement[ent].eleprof.soundset5_s.Get() );

**Comment by plemsoft** [comment]
@Kravenwolf Thanks for reporting this issue, and sorry for the delay, this has been fixed and will be in the next update :)
