### ISSUE TITLE
GGMax crashes when custom asset is added to the level editor

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#3278]
New since last update, i can load a level and use the importer to import custom assets fine, when i add said assets to the world in the level editor, GGMax freezes (the only thing i can do at this point is click the save button which still activates) and then GGMax crashes to a white screen. I then have to shut it down, restart and the process continues for every new asset.

![image](https://user-images.githubusercontent.com/82544140/172591896-1fae2c03-ea6b-4b6f-930d-8f1a4908af12.png)

This happened previously before GGmax went into Early Access, the EA update fixed this issue previously, Currently, GGMax is unusable for me.

**Comment by mav3r1ck198-1** [comment]
Edit to previous post, the issue is getting worse. It will not allow me to complete an asset import without going to white screen and rebooting the software as of 11:35am 08/06/22

**Comment by mav3r1ck198-1** [comment]
This appears to be an issue relating to advanced settings within the Nvidia dashboard. I have rest all the options to standard, and no longer have the issue of crashing in this manner. Hope that helps

**Comment by LeeBamberTGC** [comment]
@mav3r1ck198-1 Thanks for the extra investigation. Sounds like a driver issue conflict with MAX, glad you found a way through. It could be the driver or MAX, no way to know without reproducing all the hardware and software of the system exactly, not easy at all. We continue to evolve the graphics engine side, so this may resolve itself over time, as indeed with the release of new drivers also (or make things worse) :)  I will close for this, and if you see this occur again, reopen and add new info on how your driver/graphics hardware is set.
