### ISSUE TITLE
Some Particles Not The Same As Shown in Particle Editor

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#3282]
Compare the WIREFRAME1 template from the Particle Editor:
![image](https://user-images.githubusercontent.com/35840583/172819768-cad6ac30-9db1-445c-9e3e-5c5da0a9a3a4.png)

With how it looks when exported and rendered in MAX:
![image](https://user-images.githubusercontent.com/35840583/172820113-5bef423b-4d60-415a-9149-256c7526a007.png)

The cube initially looks fine, but whereas the Particle Editor preview has the box rotating, in MAX it seems to shrink and expand. This issue applies to many of the more geometric effects, such as rotating rings, etc.

**Comment by Lemuripest93** [comment]
> There seems to be quite a few of these, like the Alien Portal one ... instead of being a ring-like portal, it shows up more like a splash or wave effect.

I was just about to make a video demonstration of this, i think it's all of the ones labeled "portal" as they all seem to appear the way you've described them when exported into Max, they're not circular but rather like a waving line.

**Comment by PaulSJ** [comment]
This should be fixed in the next version
