### ISSUE TITLE
GGMAX - Filter Effects Problem

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3290]
When selecting the Filter Effects panel in Max im getting a juddering from the filter effects section. Doesnt seem to matter what setting i change on the video card either.
https://user-images.githubusercontent.com/95015657/173221534-187fe8d9-1b99-411d-944d-71057aaf0c2a.mp4

**Comment by ZakJudges** [comment]
@Necrym59 Apologies for the late reply. I have added a fix that should prevent this. I moved the filter effects into their own child component so that you can scroll them individually, which will hopefully get rid of the flickering.
A new EXP should be available in 5 mins or so :)

**Comment by Necrym59** [comment]
Fixed perfectly as usual ZaK, Thankyou
