### ISSUE TITLE
Gameguru Max Crashs after saving

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#3291]
https://user-images.githubusercontent.com/107326667/173226738-9bce262c-2d97-4b2d-8829-57791bf4ce37.mp4

**Comment by ShadowMasterOfGames** [comment]
This happens to me as well but Max is also undoing all of my textures. So, I not do any more work on my level until the developers fix this issue. Hours of work, you think by press save it would be saved but when you go back into Max nothing you save is there

**Comment by davetgc** [comment]
I reported this a few days ago, something seems to be clearing the FPM data.

**Comment by RajMaha1** [comment]
I've made a lot of custom data my own blender projects and gameguru models

**Comment by LeeBamberTGC** [comment]
@RajMaha1 Can you send me the "Guru-MapEditor.log" file that has been generated in "Documents\GameGuruApps\GameGuruMAX". From there I can see where MAX got to in the save step before crashing out, and I can then add some extra debug to see precisely where.  Can you also attach a ZIP of all your media the level uses and the FPM so I can attempt to reproduce at this end. My email is lee@thegamecreators.com

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames You will see this from time to time in an EA development version. Whilst in this state, best to make multiple SAVE AS copies of your level as you progress, this ensures you can step back to earlier uncorrupted versions and you avoid loosing lots of hard work.  Can you email me at lee@thegamecreators.com the FPM level that was saved and corrupted, thanks.

**Comment by davetgc** [comment]
Hi Lee, there's a lot of media, it'll take me some time to get it all together.

**Comment by RajMaha1** [comment]
should send the fpm on it but it wont find other files

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8890631/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@RajMaha1 No worries, send me the FPM and I can then say which media I am missing so you can find those separately :)

**Comment by LeeBamberTGC** [comment]
@RajMaha1 Any chance you can collect all custom assets and related files and zip them to send to me?  Here is the log showing the assets I am missing:

MISSING MEDIA:
entitybank\user\Lite Brown Rock .fpe=replaceentitybank\user\Lite Brown Rock .fpe
entitybank\user\Burnt Plane.fpe=replaceentitybank\user\Burnt Plane.fpe
entitybank\user\Caravan A.fpe=replaceentitybank\user\Caravan A.fpe
entitybank\user\Candle small round.fpe=replaceentitybank\user\Candle small round.fpe
entitybank\user\Croft Barn.fpe=replaceentitybank\user\Croft Barn.fpe
entitybank\user\boat v3.fpe=replaceentitybank\user\boat v3.fpe
entitybank\Booster Pack\Tool Shed Pack\Lawnmower2.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Lawnmower2.fpe
entitybank\Booster Pack\Decorations Pack\SM StandingGlobe 01.fpe=replaceentitybank\Booster Pack\Decorations Pack\SM StandingGlobe 01.fpe
entitybank\user\charactercreatorplus\Haley.fpe=replaceentitybank\user\charactercreatorplus\Haley.fpe
entitybank\user\charactercreatorplus\Saiya the teacher of fights.fpe=replaceentitybank\user\charactercreatorplus\Saiya the teacher of fights.fpe
entitybank\Booster Pack\Household Pack\Beds\Sofa Bed 1a.fpe=replaceentitybank\Booster Pack\Household Pack\Beds\Sofa Bed 1a.fpe
entitybank\Booster Pack\Household Pack\Furmiture\SM Cabinet 02a.fpe=replaceentitybank\Booster Pack\Household Pack\Furmiture\SM Cabinet 02a.fpe
entitybank\Booster Pack\Household Pack\Furmiture\SM OldBathtub 01.fpe=replaceentitybank\Booster Pack\Household Pack\Furmiture\SM OldBathtub 01.fpe
entitybank\Booster Pack\Household Pack\Sofas\Couch 04b.fpe=replaceentitybank\Booster Pack\Household Pack\Sofas\Couch 04b.fpe
entitybank\Booster Pack\Retro Pack\Television2.fpe=replaceentitybank\Booster Pack\Retro Pack\Television2.fpe
entitybank\Booster Pack\Household Pack\Tables\Table 03.fpe=replaceentitybank\Booster Pack\Household Pack\Tables\Table 03.fpe
entitybank\Booster Pack\Retro Pack\VCR.fpe=replaceentitybank\Booster Pack\Retro Pack\VCR.fpe
entitybank\Booster Pack\Household Pack\Furmiture\Bookshelf 01c.fpe=replaceentitybank\Booster Pack\Household Pack\Furmiture\Bookshelf 01c.fpe
entitybank\Booster Pack\Retro Pack\VHS-Tape3.fpe=replaceentitybank\Booster Pack\Retro Pack\VHS-Tape3.fpe
entitybank\Booster Pack\Tool Shed Pack\Workbench2.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Workbench2.fpe
entitybank\Booster Pack\Tool Shed Pack\Propane-Tank.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Propane-Tank.fpe
entitybank\Booster Pack\Tool Shed Pack\Grill.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Grill.fpe
entitybank\Booster Pack\Tool Shed Pack\WeedWacker.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\WeedWacker.fpe
entitybank\Booster Pack\Tool Shed Pack\Workbench3.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Workbench3.fpe
entitybank\Booster Pack\Tool Shed Pack\Leafblower.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Leafblower.fpe
entitybank\Booster Pack\Tool Shed Pack\Chainsaw1.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Chainsaw1.fpe
entitybank\Booster Pack\Tool Shed Pack\Drill-Box2.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Drill-Box2.fpe
entitybank\Booster Pack\Tool Shed Pack\Ear-Protection.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Ear-Protection.fpe
entitybank\Booster Pack\Tool Shed Pack\Impact-Drill.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Impact-Drill.fpe
entitybank\Booster Pack\Tool Shed Pack\Shelf5.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Shelf5.fpe
entitybank\Booster Pack\Tool Shed Pack\Battery.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Battery.fpe
entitybank\Booster Pack\Tool Shed Pack\Bag.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Bag.fpe
entitybank\Booster Pack\Tool Shed Pack\Compressed-Airtank.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Compressed-Airtank.fpe
entitybank\Booster Pack\Tool Shed Pack\Fan.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Fan.fpe
entitybank\Booster Pack\Tool Shed Pack\Hammer.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Hammer.fpe
entitybank\Booster Pack\Tool Shed Pack\hacksaw.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\hacksaw.fpe
entitybank\Booster Pack\Tool Shed Pack\Grinder.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Grinder.fpe
entitybank\Booster Pack\Tool Shed Pack\Vice2.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Vice2.fpe
entitybank\Booster Pack\Tool Shed Pack\Trashcan2.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Trashcan2.fpe
entitybank\Booster Pack\Tool Shed Pack\Trashcan1.fpe=replaceentitybank\Booster Pack\Tool Shed Pack\Trashcan1.fpe
entitybank\Booster Pack\Construction Pack\TallGasCanister.fpe=replaceentitybank\Booster Pack\Construction Pack\TallGasCanister.fpe
entitybank\Booster Pack\Construction Pack\ElectricDrill.fpe=replaceentitybank\Booster Pack\Construction Pack\ElectricDrill.fpe
entitybank\Booster Pack\Construction Pack\Sander.fpe=replaceentitybank\Booster Pack\Construction Pack\Sander.fpe
entitybank\Booster Pack\Camping Pack\Hatchet.fpe=replaceentitybank\Booster Pack\Camping Pack\Hatchet.fpe
entitybank\Booster Pack\Camping Pack\Lantern.fpe=replaceentitybank\Booster Pack\Camping Pack\Lantern.fpe
entitybank\Booster Pack\Construction Pack\Roadblock1.fpe=replaceentitybank\Booster Pack\Construction Pack\Roadblock1.fpe
entitybank\Booster Pack\Camping Pack\Log-Bench.fpe=replaceentitybank\Booster Pack\Camping Pack\Log-Bench.fpe
entitybank\user\Photograph of a book cover.fpe=replaceentitybank\user\Photograph of a book cover.fpe
entitybank\user\Gettysburg overlook battlefield .fpe=replaceentitybank\user\Gettysburg overlook battlefield .fpe
entitybank\user\Elizabeth Photograph.fpe=replaceentitybank\user\Elizabeth Photograph.fpe
entitybank\Booster Pack\Household Pack\Tables\Table 02c.fpe=replaceentitybank\Booster Pack\Household Pack\Tables\Table 02c.fpe
entitybank\user\Fighting Ground sign post.fpe=replaceentitybank\user\Fighting Ground sign post.fpe
entitybank\user\Gettysburg Battle Grounds .fpe=replaceentitybank\user\Gettysburg Battle Grounds .fpe
entitybank\user\Eternal Light in Gettyburg.fpe=replaceentitybank\user\Eternal Light in Gettyburg.fpe
entitybank\user\Barn in Gettyburg.fpe=replaceentitybank\user\Barn in Gettyburg.fpe
entitybank\user\Female Fighter Photo.fpe=replaceentitybank\user\Female Fighter Photo.fpe
entitybank\user\Fort Delaware.fpe=replaceentitybank\user\Fort Delaware.fpe
entitybank\user\Kitchen by euanford12321.fpe=replaceentitybank\user\Kitchen by euanford12321.fpe
entitybank\user\Stove by Kless Gyzen.fpe=replaceentitybank\user\Stove by Kless Gyzen.fpe
entitybank\Purchased\Sula\Town Construction Pack #2\roads\road01.fpe=replaceentitybank\Purchased\Sula\Town Construction Pack #2\roads\road01.fpe

**Comment by RajMaha1** [comment]
is alright if Send the enititybank file

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC i think you meant to ask me for the missing file, the burnt plane and Croft Barn is my assets not @RajMaha1 lol as soon as the thunderstorm stop, I will try to email you those files. Also I sent you an email earlier letting you know about my first email failing. 

I use my business email account so I can send up to 500mb but I could not even send you 40MB yesterday, you might want to look into that (when you got time 🤗) 

maybe I doing something thing wrong when I zip the files.

**Comment by ShadowMasterOfGames** [comment]
@RajMaha1 

Lee meant me not you, my friend. those are my files 100% He just had the wrong name. I am email those files right now to Lee. He has a lot on his plate with everything. Just want to straight this out with you, my friend

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC Just sent you those FPE files that you had asked for. My email is info@chriswphotography.com, so you will be able to find it faster. Again I am sorry for the confusing between RajMaqha1 and me. Those are my custom files all 60 of them lol

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames @RajMaha1 Sorry for the mixup, long days these days :)

@s
Thanks for the files. I would also need the model files and texture files that the FPEs need so they can put the models in the levels. It might be best to zip up the entire entitybank folder and email (as @RajMaha1 has done), this way you do not need to pick through lots of custom assets.

All I have so far does not show the crash when I save the level back out. I also need these custom assets too:

MISSING MEDIA:
entitybank\user\charactercreatorplus\Haley.fpe=replaceentitybank\user\charactercreatorplus\Haley.fpe
entitybank\user\charactercreatorplus\Saiya the teacher of fights.fpe=replaceentitybank\user\charactercreatorplus\Saiya the teacher of fights.fpe
entitybank\Purchased\Sula\Town Construction Pack #2\roads\road01.fpe=replaceentitybank\Purchased\Sula\Town Construction Pack #2\roads\road01.fpe

Zipping up the whole entitybank folder should catch these :)

**Comment by LeeBamberTGC** [comment]
@RajMaha1 Thanks for the 19GB of assets, took some digging but it turns out you are dragging in old assets from FPS Creator Reloaded or similar, and some of these caused a string error.  The good news is that this crash will not happen with stock assets or those imported via the model importer, only if you just drop in old legacy entities as is, and start using them.

I have added code to avoid the crash and your level now loads and saves without issue, and retains the texture information of the original old entity, even with the strange strings inside the produced DBO.  When we look at Classic 2 MAX conversions, we will give this more attention so the migration from old to new is more seamless.

**Comment by RajMaha1** [comment]
it it fixed? Thanks for all the help

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC I just try to email that file and it is over 500 mb, could I up load them on here instead?

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames @RajMaha1 Fixed for the Friday build. No need for further files :)

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC thank you again

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC So far it is working great, thanks for the fix
