### ISSUE TITLE
GGMax Crash when trying to save a test standalone

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#3292]
https://user-images.githubusercontent.com/107326667/173247114-9729d711-fe7e-4777-8a69-2fa8d2773867.mp4

**Comment by davetgc** [comment]
Hi, 

Is this the same level that you reported the save crash?

**Comment by RajMaha1** [comment]
Yeah it is

**Comment by ZakJudges** [comment]
Hi @RajMaha1 Apologies for the late reply, are you still experiencing this issue in the latest build?

**Comment by RajMaha1** [comment]
No I'm not experiencing it butim on the prior build

**Comment by ZakJudges** [comment]
Hi @RajMaha1, there has been more development on save standalone and this should not be an issue in the most recent build :)

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
