### ISSUE TITLE
GG MAX - Crash when i try to load a level

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#3293]
Hello,
I am having a problem with GGMAX. Yesterday I saved a level I was working on and it was going normally, it wasn't even lagging (It was going at 35/40 FPS). But today when I tried to open it it no longer worked. When I try to open it just the program crashes. I tried to restart the PC several times and tried to check the GGMAX files to see if there was something wrong, but it was all right.
Here is a video to show you what happens: https://youtu.be/8vd--cI5u1g

PC SPECS: i5 10400f, GTX 1660 Super, 16GB RAM.

**Comment by davetgc** [comment]
Hi,

Are you using any custom media in your level?

**Comment by LukeTheLukeLTL** [comment]
Yes, i'm using some models downloaded from Sketchfab and i'm also using some model from GameGuru Classic

**Comment by LukeTheLukeLTL** [comment]
I tried to create a standalone and there the level works perfectly. I also tried with the "Play Game" function in the hub and it works there too without any problem. The only problem therefore is that I cannot open the project in the editor.

**Comment by LukeTheLukeLTL** [comment]
I close the discussion as I have found an old backup and I am going on starting from that backup. However, the fact that no one responded to try and fix the problem is a very bad thing.
