### ISSUE TITLE
Lua Crash with a level since Friday (10/06/2022) build

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3296]
A existing FPM with custom media is crashing with a lua error when running test game. Other levels without custom media seem to launch okay. The level in question was launching perfectly until the update Friday. As you can see, the script is a default MAX script. Have re-validated files, not difference.

https://user-images.githubusercontent.com/99803873/173312223-1dde1eef-2259-433d-9e69-6b0c58a57961.mp4

**Comment by AmenMoses** [comment]
The error is related to the SetActivatedWithMP function which is defined in global.lua.

So what this means is that either:-
1)  Somewhere you have a script referencing this function before global.lua has been loaded
2)  Something is nulling SetActivatedWithMP 
3)  You have an old global.lua being loaded which doesn't include this function
4)  There is some problem in your global.lua which is occurring before it gets to define this function

**Comment by davetgc** [comment]
Deleting my scriptbank and verifying files has fixed this.
