### ISSUE TITLE
Can't edit an object after placement Game Guru Max

### ISSUE THREAD

**Issue by m0dzyz** [TheGameCreators/GameGuruRepo#3298]
I can't select a road object that came out of "City Construction Pack (PBR)
 by Sula" after I place it in the Game Guru max level editor.

**Comment by synchromesh62** [comment]
I think you would have to contact the Store on that one but checking the assets it seems the author has ticked them as GameGuru Classic only and not Max supported ?

![pack](https://user-images.githubusercontent.com/35708217/173575602-d7d25ee9-8f5e-45f9-9787-61671b90a328.png)

**Comment by m0dzyz** [comment]
Yeah, I have found other sets that work with Max thanks.

**Comment by LeeBamberTGC** [comment]
Always best to check the artist has confirmed full MAX compatibility, mileage varies with importing older assets or Classic assets.
