### ISSUE TITLE
Sky Lines???

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3299]
![lines](https://user-images.githubusercontent.com/104730909/173450166-6174e2c6-56e4-4a0c-9fb4-4ef1c4adb886.jpg)

Just working on a level and I look up and see this. Lines in the sky.

Is this bug known or is this unreported as yet?

**Comment by LeeBamberTGC** [comment]
@Curiosityuk Probably an early render bug with sky boxes. All stock sky boxes and simulated sky no longer have any lines in the sky :)
