### ISSUE TITLE
Camera control seems to be affected by physics engine

### ISSUE THREAD

**Issue by boltactiongaming** [TheGameCreators/GameGuruRepo#33]
I am using PointCamera to point at an object, in this case - a falling barrel that rolls down a slope.  It works great - while it's in the air.  But once it hits the ground it starts skipping hard.  Near as I can tell either the physics engine, terrain, or the fact it's on the x/z plane is causing problems with it.

per Lee:
"There could be a number of reasons for this, so I think the best step is to use the new issues tracker and make sure this issue can be explored fully:https://github.com/LeeBamberTGC/GameGuruRepo/issues

The only good way is to 'step through' the physics simulation, which is not for everyone, but we do have someone who is pretty adept at physics and is looking at GameGuru right now on GitHub so once this is on the issues tracker and speaks to physics issues, I can half imagine he will be all over it :)"

**Comment by LeeBamberTGC** [comment]
Can this issue be reproduced? Ideally an FPM using stock media and a step by step describing what to do and what is observed, and what is expected to happen.

**Comment by boltactiongaming** [comment]
Yes, you need a script that will just lock onto a specific entity (in my case, a barrel falling from the sky).


I will try to make a super-simple script and fpm that will verify this for you.

I should have them for you tonight.


Thanks

Mike


________________________________

**Comment by boltactiongaming** [comment]
I made a demo level w/ dumbed down camera control script to illustrate this issue.
In PP it is relatively smooth in free-fall until it hits the ground.  In non-pp release I get a jerky camera on the way down and a jerky camera pretty much all the time.  You can download it here: https://drive.google.com/open?id=15RUALOmzq0R4fAkUE8qGxFz4J03iDqKd

**Comment by plemsoft** [comment]
g_Entity[e][...] is not real-time , so use this instead:
 	PointCamera(0,GetEntityPositionX(camtarget),GetEntityPositionY(camtarget),GetEntityPositionZ(camtarget))	

Should make the camera smooth , if not let me know and i will reopen :)

**Comment by boltactiongaming** [comment]
unfortunately still having the same issue.  Test it yourself with my test map I posted, you can see it running really jerky (even moreso than previously)



________________________________

**Comment by plemsoft** [comment]
Hi,
I always test :) , and it run smooth here , but not if you use g_Entity[e]['...'] , you can see it here in this video , how it do not update g_Entity[camtarget]['y'] on all "called" , but the GetEntityPosition commands works fine for this:

https://www.youtube.com/watch?v=EfWA_ZTX6dY

New test code:
```lua
--[[
Bolt Action Gaming's extremely simplified camera script for testing purposes.
]]--

function simplecam_init()
	yescamera = 1
	doonce=0
	camtarget = 2 -- entity id of object being dropped. 
	called = 0
end 
function simplecam_main(e)
Prompt("YEP")
 if yescamera == 1 then 
  if g_PlayerHealth > 0 and g_PlayerThirdPerson==0  then
    if doonce == 0 then 
		SetCameraPosition(0,g_Entity[e]['x'],g_Entity[e]['y'] + 100,g_Entity[e]['z'])
		SetCameraOverride(3)
		doonce = 1 
		Hide(e) 
	end 

 	PointCamera(0,GetEntityPositionX(camtarget),GetEntityPositionY(camtarget),GetEntityPositionZ(camtarget))	
	called = called + 1
	Prompt( called .. " , " .. g_Entity[camtarget]['y'] )
  end
  else
	SetCameraOverride(0)
  end   
end
```

**Comment by boltactiongaming** [comment]
weird. I tested it too and it was jerky.  I'll try to make a video tonight once I duplicate it.



________________________________
