### ISSUE TITLE
curious?

### ISSUE THREAD

**Issue by Bullyblasta** [TheGameCreators/GameGuruRepo#3306]
does the medieval and fantasy packs from GGClassic work for GGMAX? also, if i export my game would i be able to put it on a flashdrive and have a friend play it, would they need GGMAX to play it

**Comment by DaveTGC2** [comment]
Standalone games can be played by anyone. They don't need MAX to do that.

**Comment by jbthenext** [comment]
This is not a bug report or feature request, please use the forums or discord for things like this in future
