### ISSUE TITLE
MAX Importer takes material name from texture file name not model material name 

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#3311]
As a Material consists of not just a texture file  but a mixture of settings and a  number of files. the name assigned to material by the artist should  be transferred on import.

 It is also not unusual for an artist to use the same texture in multiple materials at the moment these all end up with the same name. 

imagine  a model with both patent and plain leather this may use the same Albedo with a different normal and surface file.
Currently this would result in two textures named after the Albedo file name.

Another example may be when the difference between materials is only the base colour (different colour bottles)

When no texture file exists for a Material which exists when a base colour is used to define the basic material (a fairly common practice) you get a material name of noname not exactly useful. 

The only work round is to make multiple copies of the albedo files with different names which is horrifically inefficient.

**Comment by MonkeyFrogStudio** [comment]
@ratall MAX does use the material names that you assign to your models. When you import a model, under the Material tab, you see this:

![material](https://user-images.githubusercontent.com/36735507/174396058-168544f8-ad41-436e-a25a-bfbc04d479c8.png)

The red arrow points to a drop-down menu where you can select any of the materials you've created for your model. Each material has the name you assigned it in your modeling program. You can see my material here is named MFD_Floor.

The sections below this show the textures that make up this material - albedo, normal, surface (metallic, roughness, and AO), and emissive. 

If you have several models that share textures, MAX will recognize this. Each model will come in with it's own materials, keeping the material names you've assigned, and using the information in the material to determine which textures to use for that model. I use this method frequently with Trim Sheets in MAX. It works great and MAX does not create any additional textures at all. There are no multiple copies made at all.

**Comment by Ratall** [comment]
Sorry beg to differ.
I have created a simple example to illustrate my point.
It consists of a box with the word material imbedded in the material name and the word texture imbedded in the texture names. I include the fbx so you can see for yourself.

[Box_3db fbx.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8931391/Box_3db.fbx.zip)

Below shows the material name a associated textures in 3d browser.

![3dbrowser mat v text](https://user-images.githubusercontent.com/35710601/174403680-226551ef-c771-4362-b891-8c376c35ca3b.png)

Below shows the import screen in Max

![material v textur max](https://user-images.githubusercontent.com/35710601/174403714-8e23a656-1d5c-49f1-89de-646c120ef53f.png)

As you can see max version reflects the texture file name not the material name.

**Comment by MonkeyFrogStudio** [comment]
@Ratall What software are you using? Because that is not my experience using Blender at all. Here's my example:

_Name of material in Blender:_
![material1](https://user-images.githubusercontent.com/36735507/174405235-da304c7c-15af-4702-acf0-3b9e5140db98.png)

_Name of material in MAX:_
![material2](https://user-images.githubusercontent.com/36735507/174405270-e813610d-b212-4acd-bbce-7cc7d7e51c60.png)

So, it works, as you can see. Therefore, I am going to assume (and, yeah, that's dangerous, that something else is going on). 

I'll take a look at your FBX, when I can, too.

**Comment by Ratall** [comment]
I am exporting from Iclone and use 3d Browser to gather the files.   

I notice that your texture file has the Material name imbedded in it.  Which is why you see the material name correct in Max.   I believe Max is getting the name from the texture file not the material name specified in the FBX. 

It is also why in my example I ensured that the texture file names did not contain the material name so there was no doubt as to where the name was coming from in max.

**Comment by MonkeyFrogStudio** [comment]
@Ratall You know, you are absolutely correct! Wow. My naming conventions, going through Substance Painter, have been saving my backside. And I assumed (dangerous, I know) that MAX was grabbing the Material Name from the FBX file.

**Comment by Ratall** [comment]
You are lucky unfortunately not all modelers use that convention particularly those who create architecture where the standard approach appears to be to use a library of textures with standard names like oak, concrete etc and materials are variants of these. I have been playing with one model that has 3 different materials for concrete; rough_ concrete, polished_concrete and concrete they all use the same diffused (concrete) but different normals and gloss. with Max they all end up named concrete.

Anyway now that we have establish the problem exist is there any chance of getting it fixed.

**Comment by MonkeyFrogStudio** [comment]
They're really good about seeing these reports here and they're in the midst of bug fixes. I'm sure they will change this. If not, we'll just have to keep bugging them. Thanks for your persistence in this. What you've pointed out is important.

**Comment by ZakJudges** [comment]
Hi @Ratall This should now be fixed in the latest Steam experimental build

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
