### ISSUE TITLE
When you shoot from a Gun the Muzzle Flash Light Appear on the back of the weapon and inside the Scope .

### ISSUE THREAD

**Issue by doctorikc** [TheGameCreators/GameGuruRepo#3313]
When the Gun Fires the muzzle flash light should not appear on the back or inside back of the scope .... please fix that .

**Comment by LeeBamberTGC** [comment]
NOTE: Fixed for stock weapons but if a specific weapon still shows incorrect muzzle light position, please post weapon name, location and a shot, thanks!
