### ISSUE TITLE
GGMAX - Strange Lights on new map

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3314]
Created a new map and a strange light spot has appeared and wont go....any ideas.
![Lights2](https://user-images.githubusercontent.com/95015657/174429024-331a0ab1-fc92-4462-bd1e-e2a1a0af0683.png)
![Lights1](https://user-images.githubusercontent.com/95015657/174429028-eefe5700-8f0b-4e5d-b161-2bd3fa9aec57.png)

**Comment by Bullyblasta** [comment]
just my opinion but it looks like you have a spotlight under your higtmap

**Comment by Lemuripest93** [comment]
I've also had this, it's not a spotlight, the light disappeared on it's own without having to do anything after restarting the program a few times, strange indeed.

**Comment by Necrym59** [comment]
No stray spotlights in fact no items on the map at all when this screen shot was taken

**Comment by ZakJudges** [comment]
Hi @Necrym59, apologies for the late response. I could not reproduce this issue. Have you experienced it in recent builds? Thanks!

**Comment by Necrym59** [comment]
@ZakJudges 
No i havent seen this for a while now, perhaps its resolved itself with fixes along the way
I shall close this issue and wait and see
