### ISSUE TITLE
Door Issue

### ISSUE THREAD

**Issue by Maro32** [TheGameCreators/GameGuruRepo#3315]
Hello!

When I use multiple sliding doors in a level and each with it's own switch, I found that only 1 door can be opened at a time. So if I open a door, all the others are shut despite they are not logically connected to the switch that I used. Even if a switch doesn't connect to any door, it will shut all the doors. Am I doing something wrong or is it a bug? I attach a file where you can try it.

[Door Bug.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8933293/Door.Bug.zip)

**Comment by AmenMoses** [comment]
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8934233/door_sliding.zip)

So there is another 'better' version.

But make sure that is you are using a switch to activate the doors you don't also have 'Open With E Key' selected, that can confuse things in the logic.

If #3198 got implemented then it would be feasible for scripts like this to check if a connection to a switch were already present and if so disable the E key functionality to avoid issues like this.

**Comment by Maro32** [comment]
@AmenMoses it works perfectly, thank you very much for that too! TBH I didn't plan to use switch and 'Open With E Key' method on the same door, but thanks for the advice, I appreciate it and the updated LUA file as well.

**Comment by LeeBamberTGC** [comment]
@AmenMoses @Maro32 Will be in this Friday build

**Comment by Maro32** [comment]
@LeeBamberTGC thank you very much too!

**Comment by ZakJudges** [comment]
Hi all, closing this issue as it seems to be fixed. It the problem persists, feel free to reopen. Thanks!
