### ISSUE TITLE
Updating GG MAX wipes scriptbank and certain entitybank folders

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#3316]
Before updating, I had a _scriptbank\Cine Guru_ folder that I created, that's been deleted.
I also had an _entitybank\Cine Guru MAX_ folder where I'd copied and pasted some assets from classic (rather than using the importer). That folder has gone too, although the entities I have imported using the importer are still accessible via the _GameGuruApps\GameGuruMAX\Files\entitybank_ folder.

**Comment by MonkeyFrogStudio** [comment]
@AvengingEagle Did you create your custom folders (scriptbank\Cine Guru and entitybank\Cine Guru MAX) in the GameGuruApps\GameGuruMAX\Files area or did you create them in the place that GameGuru was installed (i.e. the Steam folder)? If you create custom folders in the install area, they can get removed on updates. The intent is for you to create custom folders and place custom content all in the GameGuruApps area.

**Comment by AvengingEagle** [comment]
@MonkeyFrogStudio I did not know this. Thank you.

**Comment by MonkeyFrogStudio** [comment]
@AvengingEagle You're very welcome. :)

Consider the GameGuruApps folder your Project Folder. It's where everything you do should go. It protects all of your work. It also makes it easy to back-up your work. All you have to do is copy and ZIP the contents of the GameGuruApps folder and you have a complete backup. This way, TGC can completely delete and replace whatever's going on in the install directory and you're still protected.
