### ISSUE TITLE
magpiee?

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3318]
placed a bunch of these down ASSUMING they'd have the lua applied to them already.

went to test the level. not a single one did anything, went to check, and this is what they all look like.

![image](https://user-images.githubusercontent.com/68471279/174457523-dd55fd4f-1701-4e80-92d9-fd6399c0408d.png)

now got to go delete all the dam things.

very annoying.

**Comment by LeeBamberTGC** [comment]
@casigus All stock animals in MAX now have correct behaviours attached to them.
