### ISSUE TITLE
GGMAX - Inconsistancies in reported Rotations

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3320]
This was discovered during some lua testing, when placing an object then rotating using either the 'R' key or Widget the rotation results are not the same as ones when the object is either rotated with the slider or by character input. This means depending on how you read  a result it changes the way the data is used. Can we get a consistant reading please.
![rotations](https://user-images.githubusercontent.com/95015657/174471245-da133beb-5d42-4605-b9f0-8f96d3fc534a.png)

**Comment by LeeBamberTGC** [comment]
@Necrym59 Alas MAX uses two rotation systems, the traditional EUILER and then the more useful QUAT which preserves rotations better and prevents gimble lock. Unfortunately when converted back to Euler they look a bit silly. Maybe a future feature completely hides the EULER side and you only ever see QUAT coordinates.
