### ISSUE TITLE
Aztec game kit script problems

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#3322]
having problems with the hostage script and melee script working.

https://youtu.be/qzMRxNZnWPw

**Comment by ZakJudges** [comment]
Closing as duplicate of #4002  which has since been closed.
If this was not caused by the same issue as 4002, then it is likely fixed now as part of work on https://github.com/TheGameCreators/GameGuruRepo/issues/3737#issuecomment-1342581448
