### ISSUE TITLE
importer issues.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3324]
step 1. export model as fbx (animated)

![image](https://user-images.githubusercontent.com/68471279/174634699-e65f2f77-9e86-400f-bc2a-12b72b230571.png)

step 2 import into ggmax.

![image](https://user-images.githubusercontent.com/68471279/174635167-2f1f1317-86ba-4019-9c26-4cc7cd38806e.png)

model imported. no animations. 

![image](https://user-images.githubusercontent.com/68471279/174635214-4d18be46-d10b-4c24-9ac1-d2d01947aa68.png)

check model in 3d viewer.

animations work as set.

![image](https://user-images.githubusercontent.com/68471279/174635338-f7cdb449-6154-48d2-b967-fac019abe84d.png)

next step, export model AGAIN,  (.glb) this time. 
![image](https://user-images.githubusercontent.com/68471279/174635436-b8f3078e-2b4a-4f68-a170-de87bcc91fa0.png)

reimport into ggmax again.

max freezes ENTIRE pc. then crashes.

the end.

**Comment by LeeBamberTGC** [comment]
@casigus Can you email me the model that animates in the 3D viewer and has no animations in the importer, thanks!

**Comment by casigus** [comment]
hai Lee apparantly Its because I've not rigged it, meaning max doesn't regocnise the animations or something like that. i dont even know IF i still have this file!
