### ISSUE TITLE
Problem with enemies and allys

### ISSUE THREAD

**Issue by PalmTree11** [TheGameCreators/GameGuruRepo#3327]
When my character is with an ally and I free a hostage, the ally shoots the hostage. Also, if I am with an ally and we are hiding behind a building, the enemy character can see the ally through the wall and the ally can see the enemy character through the wall and they both start shooting at each other.

**Comment by PalmTree11** [comment]
Just tested this in the Version 1 release and it is still an issue

**Comment by LeeBamberTGC** [comment]
@PalmTree11 Modified AI for next EXP build so the behaviour works even if setting the hostage to ALLY and NEUTRAL. The default is ENEMY so your ally will start shooting, but set the hostage to NEUTRAL and the ally will leave him/her alone.
