### ISSUE TITLE
WinZone Scene Tranfer Fails

### ISSUE THREAD

**Issue by jasailor** [TheGameCreators/GameGuruRepo#3328]
I set up a "winZone" to try to open the next scene.  Although the display happens and the sound is played the transfer does not happen.

Winzone Parameters:
![winzoneparms](https://user-images.githubusercontent.com/41845014/174660139-078cd646-d299-4812-80b6-c496d29c817c.JPG)

Shows how the "goto" scene is connected:
 ![WinTransferToScene](https://user-images.githubusercontent.com/41845014/174660447-0710faa4-fed7-4c99-96c4-3887e87bc7d4.JPG)

Thanks,

Jim

**Comment by Necrym59** [comment]
Win zone only works in the standalone not in test levels!  Have you tried it in a standalone game?

**Comment by jasailor** [comment]
Nope.   I’ll try that.   Thanks much.   Is that documented someplace that I missed?

Regards,
JASailor

**Comment by synchromesh62** [comment]
You can test it from the Storyboard as a full standalone without actually creating one. ( If you have created a project )
Doing it that way will test run as if it was a standalone loading all levels.

![SB](https://user-images.githubusercontent.com/35708217/174799160-a638192a-f792-4c75-a823-0e2ad1f3dcb2.png)

**Comment by Necrym59** [comment]
Well ill be damned, i havent ever noticed that tick box, thankyou Synchro.

**Comment by jasailor** [comment]
Thanks all!
