### ISSUE TITLE
GGMAX - Minor Issue - FPS/memory counter text in the editor hides minimize icon for library when it is full screen

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3337]
Took me a minute or two to find it behind the text, thought it disappeared entirely until I saw the little 'x' to the right. 

Move the text over 20 or 30 pixels to the left and problem solved, yes?

![obstructed](https://user-images.githubusercontent.com/103399301/174943094-5f9ab312-b0e7-4c4f-aed0-dc1a80e3aecf.jpg)

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Probably the easiest bug fix in 2023, thanks for the report, fixed for the next EXP build :)
