### ISSUE TITLE
BSP WWII asset pack 4 

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#334]
Since the monster update I can walk straight through all the walls in this pack.  

https://www.tgcstore.net/pack/10583

collision not working on any walls or (fake) doors.

**Comment by LeeBamberTGC** [comment]
Have you tried it with the latest PP build uploaded yesterday?

**Comment by tarkus1971** [comment]
Yes, and I tried after verifying steam files, has it maybe to do with collisionmode = 3 in the packs fpe files? 

I will re-test when I'm home later, at work right now.

**Comment by LeeBamberTGC** [comment]
Could you contact the author of the items you purchased from BSP and let him know about the new collision modes and that collision mode 3 and 4 are now designated for specific shapes, thanks!
