### ISSUE TITLE
GG Max - Bug - Underwater Grass start / end height

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3345]
When on the Terrain Editor, The Start / End height for underwater does not save.
I Have tried several times now to set the max underwater height to 97, but then after saving, and reloading, it is set back at 100
.
![Untitled](https://user-images.githubusercontent.com/66874403/175373380-2c65cc68-d867-42ff-82a1-316a5c8c9efd.png)

![Untitled](https://user-images.githubusercontent.com/66874403/175374021-d0dec653-fcf6-4ffd-ac67-98e5d5c0c20b.png)

**Comment by ZakJudges** [comment]
@Tum1370 thank you for reporting this issue. I have uploaded a new EXP with a fix :)

**Comment by Tum1370** [comment]
@ZakJudges 
Just tested this fix, and can confirm that the Underwater start / end height now saves after changing it.
Thanks for the fix, ill close this issue now.
