### ISSUE TITLE
Aztec Priest Attendant - GameGuru MAX

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#3348]
Hello just installed steam version of MAX just trying Aztec DLC and noticed the Female Priest as a dagger when run game but not in editor, which is fine but she only as her finger tips on the dagger.

![Aztec](https://user-images.githubusercontent.com/35724756/175562731-0e3adf0e-ef93-4360-867e-d8c84eace1a1.png)

**Comment by GraPhiX-Guru** [comment]
here is a video to reproduce the steps
https://youtu.be/KHMANgmBbY8

**Comment by LeeBamberTGC** [comment]
@GraPhiX-Guru Dagger weapons are now better placed:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8a8da84a-b70f-4504-8f4c-8dd66eb7736d)

**Comment by GraPhiX-Guru** [comment]
thank you
