### ISSUE TITLE
GameGuru MAX - Bug - Steam Version Does Not Run in Offline Mode

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3349]
Today, my internet was down for several hours. No worries! I thought I'd get some work done in GameGuru MAX! After clicking the GameGuru MAX - Steam icon, Steam attempts to start, tells me it cannot connect, and offers to start in Offline Mode. That's to be expected and what I wanted. Fine. Steam's running. Next, MAX starts ... but then I get this:

![offline](https://user-images.githubusercontent.com/36735507/175609785-659c8c97-2a4d-481f-ab22-a4f925442738.png)

Offline mode in Steam of often used by people who don't want to be online for whatever reason and, as I pointed out above, is there for when your internet is down, but still allows you to run your Steam apps and games. However, as the error shows, when Steam is in Offline mode, MAX does not detect that Steam is running and, as a result, you cannot run MAX.

**Comment by MonkeyFrogStudio** [comment]
Speaking a bit with Dave, he says this may be due to the Steam Authenticity Check. I feel it's important to be able to run MAX, even if Steam is in offline mode, which is a legitimate mode Steam provides us. Not everyone in the world has a great internet connection and not everyone has the internet 24-7. Being able to work in MAX, even if the internet is down is important, I think.

One possible solution - I have a 3D software that requires an internet check-in. If it cannot connect to the server, it drops into a 30-day mode. It will check every day for 30 days. If no connection to the server is made within that time, the software ceases to function until such a time as a proper connection can be made. This allows the legally licensed software to still be used, even if the internet is down (or even if the company's server is down). MAX may not need 30 days, but perhaps some grace period would work so that, in the event of internet outage, legally licensed users can still use their copy of MAX.

**Comment by Necrym59** [comment]
I second that I have run into this a few times already with outages etc. Please allow it to run in offline mode.

**Comment by MonkeyFrogStudio** [comment]
This appears to be fixed.
