### ISSUE TITLE
Frame rate limited to 40fps?

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3351]
Is there a limit to the FPS after the latest update? I was able to get close to 150fps and the least I got was 120fps in the same scene, while the latest update drops to 40fps.

**Comment by MonkeyFrogStudio** [comment]
I'd say that something else is going on. I am getting my normal frame rates (around 100fps) in my scenes with the latest updates.

**Comment by Hamada880** [comment]
I have the latest Updated for Nvidia drivers and same for my Intel. Yet still getting 40fps even in empty new scene.

**Comment by davetgc** [comment]
I'm getting a steady 60fps, so I'm guessing there's something in your level that has affected FPS. Can you take a look at anything new you've added please and report back?

**Comment by Hamada880** [comment]
I have played the level and like I said I even started a new level and empty scene and still getting the 40fps. Is there way to find how fast it is going or using benchmark to find out the exact fps?

**Comment by davetgc** [comment]
Press TAB in game, and you'll see the metrics panel, please post a
screenshot of this as we can then see what resources are being used.

**Comment by Hamada880** [comment]
There also screen shot for both empty and new scene and my own one. ![image](https://user-images.githubusercontent.com/81198887/176679865-25850cc2-25be-42bc-a9c2-67743cf47aca.jpeg)![image](https://user-images.githubusercontent.com/81198887/176679879-d51552d5-3ad2-4bad-b05b-144b03e36716.jpeg)

**Comment by Hamada880** [comment]
I have found that Nvidia drivers have an impact on how fast the software runs. If someone has Nvidia GC can confirm the issue. My card is Nvidia GeForce RTX 2070 with Max-Q Design

**Comment by Hamada880** [comment]
I have found the issue, either windows update or Nvidia caused Nvidia whisper mode to be on and runs at 40 and limit every software to run slow. Now I have fixed the issue and will test GGMax today and confirm to close the issue.

**Comment by Hamada880** [comment]
The issue is actually solved by turning that whisper mode to fully 120fps. For future reference for other members is to go to your Nvidia control Panel, manage 3D settings and after choosing GGMax on program settings, change whisperMode fps and get it to max 120fps. 

![image](https://user-images.githubusercontent.com/81198887/181425182-7965be7f-226b-4c40-bec4-2a73a0842c38.jpeg)
