### ISSUE TITLE
New update switched me to STEAM

### ISSUE THREAD

**Issue by count2rfeit** [TheGameCreators/GameGuruRepo#3354]
I just updated and now my GG MAX says it needs to open with STEAM and closes. I bought MAX at the TGC and do not have a STEAM version or STEAM key. Please help...

**Comment by Necrym59** [comment]
...and with a name like that you expect anyone to beleive this?? Otherwise contact the TGC store and they will help an verify your product.

**Comment by synchromesh62** [comment]
I have seen a few reports like this now meaning the users cannot use Max.
Marked as Urgent.

**Comment by count2rfeit** [comment]
Thank you @synchromesh62 ,

**Comment by LeeBamberTGC** [comment]
@count2rfeit Just uploaded a new build. Use the CHECK FOR UPDATES and let me know what happens through the process. If you get a new build, it will have extra checks to know if you are a non-Steam user.  If a fail, send me the "Guru-MapEditor.log" file in "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX". Also confirm you have not changed any defaults for the installation or the writables folder via settings, thanks!

**Comment by count2rfeit** [comment]
@LeeBamberTGC ,
I used the CHECK FOR UPDATES, and it said my version was "up to date"... so I did the verify files and it did seem to change some things. So, now my MAX is working again!
Thanks to everyone for the help with this issue.
