### ISSUE TITLE
Equipping a weapon causes frames to drop... 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3356]
Playing Indian Strike Force and there is a big difference in performance when player does not have a weapon equipped vs when the player does have weapon equipped. 

https://youtu.be/499wzqkuKmQ

**Comment by plemsoft** [comment]
@Kitakazi Think i remember we fixed this some time back , is this still a issue for you ? your video do not work anymore, sorry for the delay :)

**Comment by Kitakazi** [comment]
Yea I think this was fixed sry forgot to close. I'll test when I get home if its still an issue ill reopen but im pretty sure this one is fixed.

**Comment by Kitakazi** [comment]
@plemsoft @LeeBamberTGC Reopening issue as of last update selecting a weapon causes frames to drop by about 10 fps. 
Make sure to turn Vsync off then just equip a weapon.  Try on the zombie cellar demo. 

https://youtu.be/QNrrORhgqoo?si=YeboY7mJJgpkhO_G

**Comment by LeeBamberTGC** [comment]
@Kitakazi The fps drop is normal if you switched off VSYNC. A drop from 125fps to 115fps indicates an extra process is taking up an extra 0.0006 seconds per frame to perform, which is likely the rendering of the gun and controlling its logic. Can you confirm a drop when VSYNC is on, running at your native monitor refresh rate?
