### ISSUE TITLE
MAX - New Demo "Indian Strike Force" initially at 3 FPS!

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#3358]
So when I select it in the hub and click Play Game, at the end of the video intro initially I only have 3 FPS.  If I do nothing except look around with the mouse it stays at 3 FPS but when I move the player the FPS rises until I get a smooth 60 (and it stays at 60 for the rest of the demo which is good!).

I tried a few of the other demos and none of them do this only the new one.
![newdemo](https://user-images.githubusercontent.com/35708338/175788290-c8d56b84-1589-4f23-93d8-99584e26ba92.png)

**Comment by MonkeyFrogStudio** [comment]
It does this for me, too. Reminds me of this old bug:

https://github.com/TheGameCreators/GameGuruRepo/issues/2300

**Comment by synchromesh62** [comment]
Same for me but i found if i remove the video from the start marker and re-saved it was fine and has been since.
Related in some way ?

**Comment by plemsoft** [comment]
@AmenMoses Just tried this, but i dont see any intro video also i dont have the fps problem , the level must have changed at
 some point , is this still a issue for you in the latest build ?

**Comment by AmenMoses** [comment]
I still see a video but the FPS drop seems to have gone away.

**Comment by LeeBamberTGC** [comment]
@AmenMoses I have done some fixes around this kind of delay, one of them related to the recalc of lots of 3D sounds at the start of a level. I will close this :)
