### ISSUE TITLE
List of newly found issues

### ISSUE THREAD

**Issue by flarpt21** [TheGameCreators/GameGuruRepo#3359]
Zombie behavior and editor instabilities.
The zombie issues are that they randomly face directions not placed in, thereby ruining the action. 
Randomly between fixes & saves. Fixing and resaving does not solve, then other zombies can be affected or not. Random.

So playing through you end up walking right up to zombies facing the wrong way, the way opposite set & saved seconds prior. More than half the time. It is random between fixes and saves. 

And their animations and settings change too. You set them one way but on playthrough they are screwed up. Most of the time. Occurs in the editor and even after saving stand alone too... Makes zero sense. Totally random issue.... Don't even try to create a zombie and copy/paste it or drag drop it.... It will not ever work as set.

The other zombie bug is that they keep getting up. Randomly. Unkillable. Knock them down, back up they get until all ammo spent.
In both demos and the game I am making. Random zombies, random playthroughs. 

You keep killing them and they keep hissing and getting right back up again. Only A handful, and not the same ones every time. Can EASILY DEPLETE your ammo and still get back up no matte how many times you knock them down. No, not shooting them while down, I know that is flawed too. So many flaws...

The same issues with sounds.
Does not matter what sound you give a bird or zombie, most times it will not play period. Birds fly off silently. 

However the Sound triggers zones work consistently well though. Although garbage for customer playthrough as the second you enter a campfire zone the ROAR of the fire SLAPS you in the face, instead of drifting in as you get closer.... Not pro at all.

Stuff like this. Non stop.
Set up a zombie to perform a set of actions facing a direction and to make certain sounds. But most of the time it is turned the wrong way no matter how much you reset and save them. Then it'll throw a different behavior or speed or strength at you... 
Then their settings change net reset, save and playthrough.
A runner suddenly stumbles with the arms out way too slow...... All in one session, freshly reset, fixed and saved..

Not just my game either. Happens randomly in other demos. Buggy. Ending and restarting max does not help. That was 8 hours of my weekend so far.☺
LOVE this software. Want to love it way more and make $$. Cannot as is. Hanging in there with you guys. Be encouraged!☺

**Comment by AmenMoses** [comment]
[bird.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8987118/bird.zip)

That will play the sound attached to slot 0 when a bird takes off.

**Comment by flarpt21** [comment]
Thank you, I will try it. None of the other flapping ones would play. I was thinking to set them to a zone but had other issues I was trying to solve so it lost priority. Fingers crossed☺ and thank you.

**Comment by flarpt21** [comment]
Success w the bird sounds THANK YOU !☺
Zombies are still hit and miss. By the time I get to many they are facing wrong directions and they do not make sounds. But this is 
moving in a direction and I thank you for the bird file. Inch by inch☺

**Comment by davetgc** [comment]
The zombies getting up isn't a bug. They don't always die when knocked down. However, it has been raised that zombies should have a instant headshot kill option and a user definable recovery chance.

**Comment by davetgc** [comment]
Also, could you please post these as separate issues, each with it's own title. It makes it easier for the development team to deal with issues and collate related problems.

**Comment by flarpt21** [comment]
Thank you, I sure appreciate the help. Worked GREAT☺!
    On Sunday, June 26, 2022 at 01:24:27 PM EDT, AmenMoses ***@***.***> wrote:  
 
 


bird.zip

That will play the sound attached to slot 0 when a bird takes off.

**Comment by plemsoft** [comment]
These should now be separate issues so will close this one :)
