### ISSUE TITLE
HUGE frame drops after killing enemies

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3360]
This Level normally runs fine, staying around 60FPS but after killing enemies the frames drop under 10FPS making the level unplayable. It must be a bug I have well above the recommended specs. I had no huge issues with performance until recently. I've tried everything like turning off collision background objects lowering graphic settings changing draw distance, but the problem persists.

https://youtu.be/51Dyqzv8iPc?t=30

Windows 11 Pro
Intel Core  i7-10700K @ 3.80GHz
NVIDIA RTX 3070
32GB RAM

**Comment by ZakJudges** [comment]
Hi @Sinergygames, apologies for the late response. I have not been able to reproduce this issue. Does it still occur in recent builds? Thank you

**Comment by plemsoft** [comment]
@Sinergygames I can see in your video that the problem is the physics updating , this has since been improved a lot, and should also have fixed your issue. Please try it in the latest EXP build and let me know if its also fixed for you :)
