### ISSUE TITLE
triggers.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3361]
all the triggers have decided to....break. no idea when it happened, noticed it happened after a model import.

![image](https://user-images.githubusercontent.com/68471279/175969720-89eaf66a-b316-4976-b291-dc0628eacf7c.png)

now they look like this and no longer function!

**Comment by ZakJudges** [comment]
Hi @casigus Apologies for the late reply. I couldn't reproduce this. Are you still experiencing it in the latest build? :)

**Comment by casigus** [comment]
yeah not seen this anymore. :)
