### ISSUE TITLE
When AI running to dest, and get stopped, find a way around each other

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#3362]
The AI can still end up running on spot when they cannot find a way around their fellows:

![image](https://user-images.githubusercontent.com/35840583/175973964-c1451d46-a33b-4cf6-86d2-9702ab6f48bd.png)

Add code so when player cannot see them, allow them to PASS THROUGH EACH OTHER as this will keep the game moving.

When the player IS LOOKING at their stupidity, add code to have them bump past each other (and swap positions) without needing them to move to one side and potentially pass through walls. Could be supported with a 'push past animation;' so they can both stay on their path line.

**Comment by AmenMoses** [comment]
What would happen if each NPC added it's current position to the navmesh as an obstacle, then removes itself when it moves (like we do for doors).

Or would that be a performance hog?

**Comment by LeeBamberTGC** [comment]
Much improved system in latest build.
