### ISSUE TITLE
triggers not triggering

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3363]
set this trigger to deactivate this object and it just doesn't.

![image](https://user-images.githubusercontent.com/68471279/175980147-6a67dcc2-06a7-4303-88de-831e2f802695.png)

**Comment by ZakJudges** [comment]
Hi @casigus Apologies for the late reply. What object did you link to the trigger zone, to deactivate?

**Comment by casigus** [comment]
ohhh this is long sorted now :) thanks zak!
