### ISSUE TITLE
When aiming/shooting guns, water disappears

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3364]
Maybe it a bug or has to do with water height but still, this does not look right and should be fixed.
https://youtu.be/NcvajKUUC3g?t=12

**Comment by Lemuripest93** [comment]
Been meaning to report this myself, got the same issue.

**Comment by Necrym59** [comment]
Already reported
https://github.com/TheGameCreators/GameGuruRepo/issues/3128

**Comment by ZakJudges** [comment]
Closing this issue. Duplicate of #3128
