### ISSUE TITLE
GameGuru Max - Bug - Falling On Objects/Assets Doesn't Kill The Player

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3365]
As the title suggest, when you jump from a lethal jumping distance, falling unto certain(? not sure if all) objects or assets will leave the player still living, falling unto the ground still kills the player.

Video demonstration: https://www.youtube.com/watch?v=K1iHuFiV-c0

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Just tried with the latest EXP build jumping off a stack of 6 watchtowers onto the curved steps in polygon collision mode and I went splat:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2330e4dc-b4d4-4ba4-b8a6-7fd9e45c70f6)

**Comment by Lemuripest93** [comment]
Yup, this appears to have been fixed, thanks!

I'll close this one for now, i'll reopen if something pops up.
