### ISSUE TITLE
GGMAX - Discrepency in reported Allegiance

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3368]
3 characters, 1 on Enemy ,1 on Allly and ,1 on Neutral as according to the character behaviour panels
upon testing with the "GetEntityAllegiance(e)" - get the allegiance value for this entity (-1-none, 0-ally, 1-enemy, 2-neutral)
this was the actual result reported back. 
![Allegiance_Discrepency](https://user-images.githubusercontent.com/95015657/176138680-9334adc9-f1f3-4738-8f12-6fb0562b811f.png)

Also the MakeAISound(x,y,z,radius,category,e) -- specified category of game architype (0-neutral, 1-enemy, 2-player) doesnt marry up with the above ( 0-ally, 1-enemy, 2-neutral) 
can these discrepencies be rectified and made consistent as its almost impossible to script and check for.

**Comment by Necrym59** [comment]
On further checking it seems the the reporting is correct its just the command instructionals are wrong, they should read:
SetEntityAllegiance(e) -- set the allegiance value for this object (0-enemy, 1-ally, 2-neutral)
GetEntityAllegiance(e) -- get the allegiance value for this object (-1-none, 0-enemy, 1-ally, 2-neutral)
As for -  MakeAISound(x,y,z,radius,category,e)  i havent tested yet to see if the instructions of game architype (0-neutral, 1-enemy, 2-player) is incorrect or not.

**Comment by AmenMoses** [comment]
If you call GetEntityAllegiance(e)  for an entity that is not a character what do you get as a value?  (-1 I should hope!)

Also can you do SetEntityAllegiance( e , -1 )

And lastly can you call SetEntityAllegiance( e , n ) for a non-character entity and have it 'stick' so to speak.

Just thinking of gun turret use, being able to set the allegiance of them even though they aren't characters would be nice, if it works.
