### ISSUE TITLE
texture wtf

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3369]
this took over two hours of applying all the textures after a previous how many hours putting together in blender.

half the textures EVEN thou they are RIGHT there in the folder with the material file and ALL the correct textures, and once ID done that, and believe me it took ages to get all the textures back where I wanted them to be, THE SECOND its imported, MAX completely changes all the textures.

I'm pissed off. 
anyway. here's what it looks like.

How its suppose to be textured (it looks better from the inside)

![image](https://user-images.githubusercontent.com/68471279/176160613-5ccfd803-aac3-4bd9-80ef-c39908b07daa.png)

HOW it god dam turned out after the importing process:

![image](https://user-images.githubusercontent.com/68471279/176160296-39cdb6ba-e9c1-41c5-b542-3521982a7404.png)

**Comment by casigus** [comment]
deleted the TEXTURE causing the problem, reimported with out editing all the missing textures just to test, its fine. 
![image](https://user-images.githubusercontent.com/68471279/176163148-e8cee8ff-b9a1-4e00-ad87-d32f8d564cef.png)

**Comment by casigus** [comment]
Moved the object a tiny little bit. the textures revert back to the this. also happens when setting everything as double sided. 
![image](https://user-images.githubusercontent.com/68471279/176163368-7c6d5e21-9d96-4eed-bd1c-02dcbaf3abc0.png)
i am beyond pissed off.

**Comment by synchromesh62** [comment]
No need to get annoyed
You have to understand the way max imports .. Here is what i worked out.
When you import a model and save it in your Map the model settings are saved to the map.
When you re-import your model the .fpe settings are changed ( now different from the map settings )
So when you replace the model the map loads in the old fpe settings.
Simply Drag in the Model you just imported .. That one will look fine
Note the Position settings on the right and delete the old model.
Edit the postion settings of the new model and save ... Your Done !!

![modelset](https://user-images.githubusercontent.com/35708217/176276499-307f5349-0ae4-4b84-8440-4b96002f258b.png)
Its not a bug as such its the way Max imports and saves to the map file.
I do this all the time :)

**Comment by casigus** [comment]
thanks <3
