### ISSUE TITLE
some BUGS and NEEDs: FBX importer more accurate

### ISSUE THREAD

**Issue by Daveutopias** [TheGameCreators/GameGuruRepo#337]
Hello, since new fbx importer feature is out i have tryied to add some new royalty free models, most of time the importer feature work fine, sometimes (i have a display of 14.4 in x 8.2 in x 15.7 in, 
1024 x 768 at 75 Hz ) i cannot see the "blank buttons" for adding textures, yes the program can add it automately but sometimes they are out of screen, please fix this, then another think is there are some possible way to import animations? because I can not do it, if I add one model after another I have to spammed the import model button to make it work or click add entities, most of the time imported models are not seen during the import process (only if they have textures. dds I see them, but those .png no (maybe it depends on the model, I do not know), the collisions sometimes do not work properly (if I put polygons instead of box the model is sometimes beyond), some models have the skin all stretched and they look different from how I open them in Microsoft print 3d (opening the .fbx)

**Comment by Daveutopias** [comment]
hello, i will send some pics about to help to understand what i mean:
![cant see charachter](https://user-images.githubusercontent.com/40697420/44717510-74356f80-aabd-11e8-91b0-06d9163fcc3a.jpg) (and he have only on textured file)
![snapshot229](https://user-images.githubusercontent.com/40697420/44717544-8c0cf380-aabd-11e8-8e4a-f3f26a738f6c.jpg)
![snapshot230](https://user-images.githubusercontent.com/40697420/44717552-8e6f4d80-aabd-11e8-90f7-a825ea5a5921.jpg)
![snapshot231](https://user-images.githubusercontent.com/40697420/44717561-916a3e00-aabd-11e8-9137-00ff04ec0796.jpg)
and sometimes some models have all black button displayed on screen (with oversize button textures) and sometimes the same model with other dress (come from mixamo) do NOT come with button textures BLANK!
![too much blank button oversize where to press save entities](https://user-images.githubusercontent.com/40697420/44717839-79df8500-aabe-11e8-9b52-e303c5cfb368.jpg)


i have tried last PP build of 08.24.2018, this do not was fixed with these fixline like : "Better detection for 8-system bone weights so irregular 1-system bone weights don't corrupt model"; , i have read last changelog at forum here https://www.thegamecreators.com/post/gameguru-public-preview-update

collison mode: if i add these entites i can walk inside body

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Importer has been updated since this report. it all depends on the model being imported.
