### ISSUE TITLE
GGMAX - PromptLocal Enhancement Required

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3372]
The Prompt Local command needs to be augmented or a new command created for overhead of characters. For example
 PromptLocal(e,"Health "..g_Entity[e]['health']) is currently hard wired to place the text at the base of the character/Entity as per the first image on the left,  can we possibly have this  command modified to PromptLocal(e,y,text) so as to use an overhead prompt modified position by 'y' value. This will be badly needed for RPG games in the future and is really needed now for some things.
![PromptLocal](https://user-images.githubusercontent.com/95015657/176318389-768049cc-6035-42dd-8f15-9a10512a041b.png)

**Comment by AmenMoses** [comment]
I would go further.
I would add x,y,x offsets.
e.g. PromptLocal( e, text, xo, yo, zo )
That would allow prompts for things like doors where the origin is not centred to have the prompt appear in a position relative to the origin.
Also I have noticed that the PrompLocal no longer shows the prompts at the origin properly anyhow, they seem to be affected by the camera angle and whiz off to one side as you turn, very disconcerting when trying to use them to debug things as the prompt can appear under a completely different entity than the one it is intended for!

**Comment by Necrym59** [comment]
I agree Amen i just didnt want to make it a big job but your correct x,y,z is probably a good move for a change for a variety of reasons. I wasnt sure wether that angle movement was just my setup or not but if its effecting everyone hopefully the fixed xyz positioning will fix it.

**Comment by 42Pix3ls** [comment]
Just the ability to overlay information over an enemy would be really useful

**Comment by Necrym59** [comment]
Also while if you look at this can we make a color version as well eg: PromptLocalColor( e, text, xo, yo, zo, 0, 0, 0 )
