### ISSUE TITLE
Character Not moving between flags in patrol mode

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#3373]
https://user-images.githubusercontent.com/107326667/176419396-ed2151fb-34bc-4962-afdf-c1e94607ffca.mp4

**Comment by MonkeyFrogStudio** [comment]
Did you use the visual logic system to link the character to the flags (and then each flag in order)?

**Comment by RajMaha1** [comment]
https://user-images.githubusercontent.com/107326667/176456387-26b5f3cf-2b10-4e2b-b556-dfef2ffd182a.mp4

Yeah I did no worries it seems to be something to do with my level

**Comment by davetgc** [comment]
Please let me know if this is still a problem. Many thanks,

**Comment by RajMaha1** [comment]
Sorry for not responding i loaded a old backup and it fixed

**Comment by RajMaha1** [comment]
I've got another glitch similar to this again could some help me fix it
