### ISSUE TITLE
Game Guru Max freezing every few seconds (Not Responding) 

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3376]
I was working on a level for a few hours and then out of nowhere Game Guru Max started freezing every 15 seconds or so, in game and in the editor, it's a small level, I tried restarting the software, but the problem persists. In this short video you'll see the level freeze at random multiple times for no reason.

https://youtu.be/TRdpLDwbebY?t=16

**Comment by LeeBamberTGC** [comment]
@Sinergygames Not seen this in recent reports, but we have fixed certain issues that may have caused this. If it repeats, please post a new stock level here and we can reproduce and fix. P.S. NICE LEVEL!!
