### ISSUE TITLE
What's the best way to find misplaced object in a large map

### ISSUE THREAD

**Issue by njab64** [TheGameCreators/GameGuruRepo#3379]
Is it possible to list (show/highlight) all of a selected (ie all Billy Joe's/barrels ) entity/object in a map. Then by clicking on an entity in the list  jump to its location?   Avoid losing entities in large maps.

**Comment by MonkeyFrogStudio** [comment]
When in the editor, under Level Objects, there is a downward pointing arrow to the right-side of that panel (Add, then a search bar, then the arrow). Click that arrow and select, Detailed Object List. Once you do, there will be lists of objects in your level categorized by type. Click one of the small arrow to the left of the type you want (like Barrels) and a list of all the barrels in your level will be exposed. Double-clicking on any of them will zoom you to that object in your level and center it in your view.
