### ISSUE TITLE
collision issue HAS not been fixed.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3382]
![image](https://user-images.githubusercontent.com/68471279/176777363-1522560d-02c0-46b5-b5be-d123422c4da7.png)

the collisions are exactly as before.  non existent.

**Comment by casigus** [comment]
now that model right there, the glf imports with NO collisions, so go back to blender, export a obj. this happens.

![image](https://user-images.githubusercontent.com/68471279/176778210-e4436cab-c67c-42b3-9b47-d74e1c913610.png)

**Comment by davetgc** [comment]
Can you please either post the model here, or email to lee@thegamecreators.com so it can be tested.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
