### ISSUE TITLE
Animated object not playing smoothly 

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#3383]
I brought an animated object over from classic. back a few months ago the animation played fine but now it is all jerky and plays the entire animation in less then a second.

**Comment by davetgc** [comment]
Hi, once more, which object is this please?

**Comment by 42Pix3ls** [comment]
There were a number of animated objects, not just one. Seems like an issue with some old animated objects in .x form. after a lot of mucking around exporting the.x as a .fpe and having it set as the fpe 2013 the inimations work again

**Comment by davetgc** [comment]
Okay, I'll close this for now, but if you find other problems, please report them.
