### ISSUE TITLE
Adding animated tree hard crashes MAX

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#3384]
Adding an animated tree to a scene in max from the classic collection and running test mode hard crashes max.

if you have saved an re load the game it seems to work after that.

**Comment by davetgc** [comment]
Hi, which tree is this please?

**Comment by 42Pix3ls** [comment]
I added a bush and then a tree first it was Bush 01 (animated) then Tree 3 (animated) since the initial crash from each they seem to be fine.

**Comment by davetgc** [comment]
Fixed after export.
