### ISSUE TITLE
Particle editor

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3385]
the PARTICLE editor ISN'T saving particles to ggmax, exports it to some random folder on your pc which is very annoying esp when trying to then track down the edited particle of which you'll have to manually copy and paste it into your games folder. for the ammount I paid for this it really should do all this automatically.

**Comment by davetgc** [comment]
Have you moved the MAX default install folder? There is a know bug where this causes issues and we're working on it.
