### ISSUE TITLE
mammal_generic.lua   crash

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#3386]
mammal_generic.lua   crash

the animal script occasionally crashes and freezes error line 18 says

**Comment by davetgc** [comment]
Is this with default mammal, or custom ones?

**Comment by SampeyFS** [comment]
the script is not original can you insert the script respam objects?

**Comment by davetgc** [comment]
Are you saying you've made a custom script and it's crashing?

**Comment by SampeyFS** [comment]
noscript is original of the game when you put the animals it is written errro line 108 and the script mammal_generic.lua is written

**Comment by SampeyFS** [comment]
the problem seems solved thanks

**Comment by davetgc** [comment]
Great. I'll close this for now, but if you have problems again, please feel free to raise it again.
