### ISSUE TITLE
Particle Editor - Missing the Export Button. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3388]
Just installed the Particle Editor DLC from Steam. Im using the Steam version of GGMax. In the Particle editor built-in tutorial and Lee's live broadcast there is an "Export to GGMax Button." My particle editor does not have this button. 

![image](https://user-images.githubusercontent.com/51464873/176972199-d2a85317-15d2-4a7e-a1b2-38c1d5fa533f.png)

**Comment by davetgc** [comment]
Is this on a 4k screen? Sometimes large screens cause issues with the placement.

**Comment by Kitakazi** [comment]
Yes I have a 4k monitor. I changed it to 1080 to test but it still is missing the export to GGMax. 

![image](https://user-images.githubusercontent.com/51464873/177020167-769a9094-4046-4fb4-a61d-88360c8e1798.png)

**Comment by Kitakazi** [comment]
Lee said something on the broadcast today about having a Writeables folder causing issues with saving particles I think, not 100% sure if he was talking about the same thing. But maybe that is causing the issue. I have tried looking for where the files are after I click Save Effect File, to see if I can just manually add the files to my Particles Bank but I cannot locate all the nessecery files to add to my Particles Bank folder I can only locate a few of them.  It does not look like selecting Save Effect File actually saves all the files Max needs only the files needed to pull up the effect in the Particle Editor. Not 100% sure but it probably doesn't create all the needed files until user presses the Export button, which I don't even have. 

I tried copying the DLC folder files into my writeables folder and that did not work. 

I'm not really sure if there is anything else I can really do, is there any update on when this will be fixed? I have no problem spending money on TGC products to help development but this doesn't even work at all.

**Comment by Kitakazi** [comment]
@davetgc 
Can this label be changed? It has been 3 weeks now and this issue is still present. Feels like I just set $30 on fire.

**Comment by Kitakazi** [comment]
@LeeBamberTGC pls help :( 

I figured I would get a refund from Steam and just buy the AppGameKit Particle Editor. However I purchased this over 14 days ago which is the cutoff for DLC refunds for Steam.  I think using a Custom Writable folder is causing this issue. 

I have talked to 2 other users that had this same issue of the Export button not showing up and both used a Custom Writable Folder. It is not really possible for me to use the Default Folder because it puts all the files on my C drive which is a small SSD that only has Windows on it. If this isn't going to be fixed in the near future can I have a copy of the AppGameKit Particle Editor? I don't like asking for free things but I'd like to dive into making cool particles sooner than later.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you tell me where you pointed your writables folder, just so I can reproduce the scenario at my end, thanks!

**Comment by Kitakazi** [comment]
Its just pointed to my other SSD - F:\GameGuruApps\

**Comment by LeeBamberTGC** [comment]
@Kitakazi I have relayed this finding to Gabor, the author of the Particle Editor, so he can read the writables folder location from MAX to know where the new writables location is. For now, you can revert to the Documents default location and Particle Editor should show you the export button. Alternatively, you can export in the normal 'AGK' way and pl;ace the files manually in the particles folder as that is all the GGM export really does.

**Comment by Kitakazi** [comment]
Sounds good, thanks!
