### ISSUE TITLE
Possible Importer Crash

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3389]
![image](https://user-images.githubusercontent.com/68471279/177017353-9773e540-e675-493f-90ac-628c959762a0.png)

then it went to a memorry error which couldn't screen shot,

then all my screens started flickering.

then all but one of my screens went blank.

then max shut down.

also had it pop up saying max couldn't inntiate direct x 11.

and now my entire system is  having a complete melt down.

what the hell is going on?

**Comment by synchromesh62** [comment]
**and now my entire system is having a complete melt down.**
If your entire system is having an issue are you sure its Max causing the problem or your system causing the problem ?

**Comment by casigus** [comment]
after the crash, did a restart, everythings fine. the problems happen with the model importer, everything falls apart after that.

**Comment by synchromesh62** [comment]
> after the crash, did a restart, everythings fine. the problems happen with the model importer, everything falls apart after that.

Excellent at least its confirmed to be a Max failure. ( better that than the alternative )
When you said your entire system had failed with a memory error i was thinking a coincidental hardware failure.
It would not be the first time that had happened to me.

**Comment by casigus** [comment]
ayee! i did panic!!!!

**Comment by davetgc** [comment]
This actually looks like a browser crash.

Also, please name issues with a clear description of the problem. THIS doesn't really tell the team anything.

**Comment by LeeBamberTGC** [comment]
@casigus Can you confirm this meltdown is happening in the current EXP buld,. thanks:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8f4cbc19-c4fe-4816-9fdc-6da564392906)

**Comment by casigus** [comment]
yeo not seen this one for ages!!
