### ISSUE TITLE
Using CTRL+C/V on a model, then changing the scale will turn the model invisible

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3391]
https://youtu.be/uFybxr5uxbw

How to reproduce: 
Click a new object and then click again to place in scene. It must placed down. Use CTRL + C and CTRL + V to copy and paste. 
On the new model open the Scaling in the object tools and try to change the Scale. 
Model will turn invisible. 

You must use CTRL +C/V to copy and paste, using shift click will not cause this bug.

**Comment by MonkeyFrogStudio** [comment]
Can confirm! Not only does the object disappear, but I cannot select anything else afterward by clicking in the viewport. I had to go to the detailed list and first select from there (double-click) before I could.

**Comment by Kitakazi** [comment]
Forgot to add for this bug to happen you must try to scale object with the "Scale Multiple Percentage" slider.

**Comment by ZakJudges** [comment]
Hi @Kitakazi, apologies for the late response.

Thank you for reporting this issue. I have added a fix which should be in the next experimental build :)

**Comment by Kitakazi** [comment]
Not a problem, thank you for fixing this one!
