### ISSUE TITLE
Stuck in behaviour editor

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#3392]
I was having a play around with the behaviour editor and when I was done I was not able to get out of the menu. The top right x to close the menu did not work.

**Comment by MonkeyFrogStudio** [comment]
Can confirm that the X does not close the editor. However, you can use the Close Behavior Editor button to exit:

![behave](https://user-images.githubusercontent.com/36735507/177045345-bf999345-7be9-4ad1-8686-a05cea8662d9.png)

**Comment by 42Pix3ls** [comment]
Thank you, I must have overlooked the extremely obvious button hehe

**Comment by Teabone3** [comment]
What does that small x button actually do?

**Comment by MonkeyFrogStudio** [comment]
@davetgc Why is this closed? While there is a button to close the Behavior Editor, the "X" in the upper-right still does nothing and should either be removed (if the button is to only be used) or should function to close the Behavior Editor, too.

**Comment by davetgc** [comment]
Sorry, I thought that this was considered fixed. I'll reopen in a bit.
