### ISSUE TITLE
MAX, model importer not exporting textures correctly.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3395]
The importer appears to be correctly importing a model from sketchfab, but isn't correctly assigning the textures on export.

@LeeBamberTGC - I've emailed you this model.

In the importer:
![20220704141804_1](https://user-images.githubusercontent.com/99803873/177153738-58414bc8-b301-4c77-9b6e-b1d2ab3c2273.jpg)

On export:

![20220704141831_1](https://user-images.githubusercontent.com/99803873/177153781-b3acaef7-a450-4d29-8de3-0b3aae433b84.jpg)

**Comment by Zorgo33** [comment]
Hmm, make sure your model textures aren't using names of materials you already have (on previous models for example, like mat1 and the new ones are also mat1 and etc). If that's not the case, well... then it's a bug.

**Comment by mav3r1ck198-1** [comment]
Ive had similar happen when the model has had multiple LODS.

**Comment by mav3r1ck198-1** [comment]
ive got that model from Sketchfab, looking at the texture files attached to your imported model, they dont look the same as the ones that come with it.  Zorgo33 may have good insight here

![image](https://user-images.githubusercontent.com/82544140/177209087-3aa20e7d-ffbe-4691-b1e8-d5f3800c9673.png)

**Comment by davetgc** [comment]
That's possible.

**Comment by LeeBamberTGC** [comment]
NOTE: I received this model and texture files and tried it with the latest MAX, it looked fine, with no texture mess-ups though a little low resolution when you get right up to the door:

![image](https://user-images.githubusercontent.com/35840583/184662903-e718fcbb-70cb-4237-8cee-241de853f2f5.png)
