### ISSUE TITLE
GameGuru MAX - Bug - Imported Particles Cannot be Rotated

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3396]
Particles that come with GameGuru MAX can be rotated via the sliders, but not by using the widget. However, particles exported from the Particle Creator don't seem to be able to be rotated at all, even with the slider. The particle widget rotates, but the particle itself does not rotate.

1 - If a particle can be rotated by the sliders, should we not be able to also rotate it via the widget?
2 - Is there a setting that needs to be set in Particle Editor to enable them to be rotatable in MAX or is this a bug?

Thanks.

**Comment by mav3r1ck198-1** [comment]
Ive noticed the same. I am using the TGC separate particle editor rather than the steam version

**Comment by davetgc** [comment]
Is this just the widget that it doesn't rotate with, as I can rotate with shortcuts.

**Comment by MonkeyFrogStudio** [comment]
@davetgc > Is this just the widget that it doesn't rotate with, as I can rotate with shortcuts.

From my first post:

> Particles that come with GameGuru MAX can be rotated via the sliders, **_but not by using the widget._**

**Comment by davetgc** [comment]
Thanks, I should read more :)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Nice update to the particle effects, now you can see shapes and working rotation.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Is this in the latest experimental build?

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Still not seeing this in the last few exp. builds ...

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Portal5 viewed from above and rotated 45 degrees:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/78018758-5b5a-4fc9-b73a-8cf2c0ee629c)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC In my first post here, I'd asked if particles could be rotated via the widget and not just with the sliders, like we can rotate an standard object. The rotate widget shows on the particle, but it does nothing when you attempt to use it.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC What information are you waiting for?

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Can you confirm that when you drop in the portal5, click it, and then use the R key, it rotates on the Y axis?

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/1c7cdd35-c019-4519-be2c-59601c6facf6)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/9567ecb5-5b2a-473b-8971-729c6547fbf3)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5af5c7bd-bb15-4a0c-80a8-921b70295cb4)

I have reproduced the issue of the widget circles not rotating the particles, is this the final fix needed:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4aedf177-a0ee-46f6-833f-902192e2e4b8)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Rotation and Scale via widget supported in next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4f8e7e4f-503e-4cdb-b355-b7680f43c01e)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f4c04678-7cbb-40f7-8c77-feed27a48d72)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Awesome! I will check it out once I update. ;)

**Comment by MonkeyFrogStudio** [comment]
Confirmed! Thanks, @LeeBamberTGC !
