### ISSUE TITLE
Problems with games I create.

### ISSUE THREAD

**Issue by RobDaHob** [TheGameCreators/GameGuruRepo#3399]
Hi,
Tryed to export my game to  another computer also win10.
But it wouldent load. 
Do see it is trying, get some graphic lines on the monitor but stops loading.
Do the game me made need Internet to load? Dident test that.
Rob

**Comment by davetgc** [comment]
Do the system specs of the other computer meet MAX minimum specs?

**Comment by RobDaHob** [comment]
i have been dealing with this from day one. no one can play my games if they do not have ggm installed or have not had ggm installed on their gaming laptops at some point. remember, these are the laptops they game on every day. these are hardcore gamers that run AAA games daily.

i have no idea what is going on but i have shared 10 games to 11 friends. none of the games would open. after my friends installed ggm and then removed it all could play any of my games.

my youngest son is an avid pc gamer with a maxxed out gaming pc. he couldn't open any of my games. i told him to buy ggm on steam, uninstall it and then see if the games would open. he did and the games now play just fine.

without ggm you get a huge number of dll errors that you can spend a week chasing down and still never fix. this is on GAMING systems that play EVERY day.

there is something going on and i have no idea what it is, but it's not just you and it has nothing to do with low spec machines.
Last edited by [afusales](https://steamcommunity.com/profiles/76561198272294742); 2 Jul @ 9:18pm

**Comment by RobDaHob** [comment]
Dont wait for me - my computer is not new but do have what it takes.
You should check yourself what makes and not and not let us do your job.
Please.
Rob

**Comment by synchromesh62** [comment]
I think this now can to be confirmed an issue that needs investigation as i have seen this also reported by a few other users.
Same thing standalones work fine if they have Max installed or Install Max but not on a good spec PC without Max installed.

**Comment by ZakJudges** [comment]
Hi all, apologies for the late response. I have added a fix, which should hopefully sort the issue of missing DLLs, when playing a standalone game without having GameGuru Max installed. A new experimental build will be uploaded later today. After updating, would someone be able to let me know if the fix worked? Thank you :)
