### ISSUE TITLE
Parental controls bug find!

### ISSUE THREAD

**Issue by a3dartist** [TheGameCreators/GameGuruRepo#34]
Hi guys I recently encountered a bug on loading game-guru with a steam key everything loads fine on my friends PC but after the terrain loading their is a screen that pops up for parental controls for blood and gore content it halts and shuts down the PC. So I went to my friends house to figure out why it wouldn't load game-guru and shuts down the PC when trying to load the software. It's because you have to hit the ESC key really fast before it shuts down the PC in order for the software to run. Thanks to Wyatt for letting me fix it so he can play around with game-guru with me. I found the bug after giving two of my serial keys away, but I have the software running on his PC now! I wanted to make this aware as a bug in the software!

**Comment by LeeBamberTGC** [comment]
I have changed the software now so that the parental control popup does not show when you first install and use the software, this will prevent this happening again. You can still activate restricted content mode from the Help menu.
