### ISSUE TITLE
runtime error after changing terrain

### ISSUE THREAD

**Issue by wonderdaan** [TheGameCreators/GameGuruRepo#340]
LENOVO YOGA 520
Intel Core i5
NVIDIA GeForce MX130
1920 x 1080 pixels
Quad core (4)

Dear all,

I have this problem whenever I select a terrain type (e.g. yellow bricks) and want to exchange it with another terrain type from the folder (in this case sandy). The editor crashes and gives the runtime error pictured in attachment.

Am I doing something wrong? Can someone help me?
![schermopname 18](https://user-images.githubusercontent.com/42210355/43839987-cec01a52-9b1f-11e8-8fdb-731cf1b4fbe8.png)

TIA,
Daan

**Comment by wonderdaan** [comment]
UPDATE: After this runtime error, I find myself in the automated previous version and although I have saved the desert terrain just before this, my terrain has completely changed from desert to forest. 

Even all my own backup version (2 on different locations!) of this map - which were 100% saved as desert, now all open with forest terrain. What the heck???

Please please pleas help me, I have so much planned and I live for making this game, but I'm beginning to think it's just not going to work out :'(

Sorry to be such a weeny baby but I'm really desperate.

**Comment by wonderdaan** [comment]
Okay, this is what I get now when I try to change the terrain in desert 1 again via gametesting settings.
![schermopname 19](https://user-images.githubusercontent.com/42210355/43855650-9aa4cc00-9b46-11e8-9574-c4cb88e854fb.png)

**Comment by LeeBamberTGC** [comment]
@wonderdaan I cannot reproduce this with the latest public build, can you try it again and let us know, perhaps with a step by step, thanks!
