### ISSUE TITLE
Needs Steam client to run???

### ISSUE THREAD

**Issue by RobDaHob** [TheGameCreators/GameGuruRepo#3400]
Needs Steam client to run???
Basically I am without wifi, was hoping to work on my level, now I can't because I need steam to run. Which isn't happening tonight. Anyone have a workaround? Hopefully? Worked before.
(Queston from discusson at Steam, would be good if possible, Rob)

**Comment by MonkeyFrogStudio** [comment]
Reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3349

**Comment by davetgc** [comment]
This is a duplicate, so I'll close this one. Thanks for reporting.
