### ISSUE TITLE
Fog not consistant across entities and terrain.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3401]
The fog distance has a different effect on entities and terrain. As you can see in the screenshot the grey areas on the distant terrain are large entities or trees sticking out of the terrain. It needs to all be the same.

![20220705121823_1](https://user-images.githubusercontent.com/99803873/177306602-424b544a-cdc2-4e40-9b0c-292e5414ab35.jpg)

**Comment by LeeBamberTGC** [comment]
@davetgc Fog is now consistent across skies, trees and objects in the level:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/04397dec-228c-4420-9482-0a915c15b83d)

**Comment by davetgc** [comment]
Perfect.
