### ISSUE TITLE
GG Max - Bug - Group Objects do not save correctly

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3402]
After trying many different groups, some with many items, and others with a few, i have found that basically groups do not save correctly.

Here is a basic group with 8 items.
A barrel, Fire entity, particle of smoke, and 5 planks of wood.
As you can see in the screenshots, first screenshot is the group i save, the second screenshot is after placing the group.

![Untitled](https://user-images.githubusercontent.com/66874403/177342699-3dabb105-5398-4eca-a4b3-e851224d5e4d.png)

![Untitled](https://user-images.githubusercontent.com/66874403/177342856-8707883c-b978-4c9f-999b-7624b81883aa.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed in next EXP build, used the barrel, smoke and five planks to make my own smart object:
![image](https://user-images.githubusercontent.com/35840583/229365606-4e3aa535-3a88-4649-b12f-694f78e27e06.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC Am closing this issue as i just tested this and it seems to of been fixed now in latest EXP build.
Thanks for the fix. :)
