### ISSUE TITLE
Carrying weapons over

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3403]
Is there anyway of carrying over the players weapon with the same amount of ammo they left the last scene with?
Because when I am testing a game. After I have finished the level and move to the next, my player seems to have no weapon?
Is there something I am missing?

**Comment by LeeBamberTGC** [comment]
@Curiosityuk Fixed a while ago, now standalone levels will retain ALL player stats including the weapons, ammo and what you are carrying at the time.
