### ISSUE TITLE
GameGuru Max  APPCRASH 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#3405]
Wrong Bucket 1908918079605682370, type 4
Event Name: APPCRASH
Answer: Not available
CAB ID: 0

Issue signature:
P1: GameGuruMAX.exe
P2: 0.0.0.0
P3: 62c2cffc
P4: StackHash_b794
P5: 10.0.19041.1806
P6: 1000a5b9
P7: c0000374 game guru max throws errors on windows 10 x64

**Comment by LeeBamberTGC** [comment]
@SampeyFS Is this still happening with the latest build?
