### ISSUE TITLE
Zombies won't die

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3406]
That's not quite true, but we are receiving a lot of negative feedback that they are really difficult to kill, with many users thinking they simply can't be killed.

IMO, we need a slider for the changes of them standing back up, and a tickbox for headshots to be an instant kill.

Secondly, we've had complaints that zombies can't be harmed when they are standing back up,

**Comment by davetgc** [comment]
Great Lee, that should be very popular.

**Comment by ThanosDawn** [comment]
1. No knockdown settings functionality [confirmed](https://www.youtube.com/watch?v=aGIZ9uSMx68)
2. Zombie invulnerability during knockdown fix [confirmed](https://www.youtube.com/watch?v=GK6bjKHqtJs) (a little wonky with some values and minor issues like the ragdolls but works like a charm from my little testing)
3. Headshot insta kill functionality [confirmed](https://www.youtube.com/watch?v=LMtiveOxWqc)
^

**Comment by davetgc** [comment]
I can confirm these fixes work.

**Comment by LeeBamberTGC** [comment]
That's great, closing this one down and please do report new ones as they occur, we will get them all eventually :)
