### ISSUE TITLE
Some fast found, breaking bugs

### ISSUE THREAD

**Issue by ThanosDawn** [TheGameCreators/GameGuruRepo#3408]
1. wrong collision placements on the [basement collection door frames](https://www.youtube.com/watch?v=qWDGXrIJ9VQ)
   - Collision boxes not on the frames (~3m in front of the frames)
2. weird decision on some objects and [script bugs](https://www.youtube.com/watch?v=KhWuQwQKmlE)
   - Barbed Wire asset treated as static object, therefor scripts (especially the Spiketrap script) can´t be applied
   - Spiketrap script non functional on some objects
   - Door script doesn´t provide animation, keys respawn upon activation of linked object [PARTLY FIXED]
   - Move away script bugging out in certain angles based on objects current speed (might be limited to a few objects, requires more testing)
   [Partly Fixed 08/07/2022 - Keys no longer respawn upon activating linked object]
4. [Zombies](https://www.youtube.com/watch?v=yW_vmU9VJ-4) [FIXED 08/07/2022]
5. more collision and different asset issues: [Max collection](https://www.youtube.com/watch?v=xJdw2rjsBZM)
   Max collection Assets:
   Missplaced colision boxes:
   - Artillery Gun, Basement Access Frame, BRT GAZ, Chair, Chest Animated, Copter, Helicopter, Pallet Truck, Pipes Small 90 Long, Pipes Small 90 Short, tent0 
   - most (smaller, lighter objects block players movement)
   - Campfire asset moveable when getting stuck on it
   Misc issues:
   - Girl asset bugging into the ground into a random manner upon level start
   - Ladder Painted Wood Short, Ladder Painted Wood Tall assets place player on the ground again upon reaching the top
   - Web Large, Web Long, Web Small too big collision boxes, only visible from the front
   - Picdoors, Shelfdoors assets are static objects, therefor (despite their name) can´t be used as a door, and no script is applyable.

**Comment by ThanosDawn** [comment]
> Hi, thanks for posting. It really helps the team if you can post these as separate issues with a description, and not just a video, then we can link duplicate and quickly see the issue.
> 
> Many thanks,
Added in a list for better identification and I´ll add future findings as seperate posts
^

**Comment by davetgc** [comment]
Can you please start a new thread with the collision issues? Many thanks.
