### ISSUE TITLE
BUG Weapon Animations playing in slow motion

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3409]
For some reason jumping and then immediately sprinting after makes the weapon animations play in slow motion
 https://youtu.be/msNZC9k4LPg?t=6

**Comment by Sinergygames** [comment]
This issue has been fixed in the latest update, we'll kinda. Now jumping won't make the animations slow down. Now I don't know if this was Intentional but the running animations on all guns plays slow like at half speed Since the update. It doesn't look right when running.

**Comment by LeeBamberTGC** [comment]
@Sinergygames FIxed a while ago and related to the animation speed not being constantly updated by the FPS indepdendence system, sorted now for all weapons and all scenarios.
