### ISSUE TITLE
Easy Building Editor thingys.... visible in standalone 

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#341]
I dont know how they are called but these things
![unbenannt](https://user-images.githubusercontent.com/35990507/43861102-20784a32-9b56-11e8-9487-b335fb4e1570.PNG)
are visible when you run your level as standalone.

This is a problem I want to report. Thank you very much

**Comment by synchromesh62** [comment]
I had this but it seemed to fix itself after I freshly installed the Beta … It could already be fixed .. 
What version are you using ?

**Comment by Duchenkuke** [comment]
I use the public version "monster update"
I will remove all EBE structures from my level anyway - takes too much framerate

**Comment by synchromesh62** [comment]
Once Im happy and delete my .ebe file so its a standalone model the framerate seems fine to me ?

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this,

This has been fixed and are ready from the next update :)
