### ISSUE TITLE
Add 30 Day Grace on Steam Authentication (only need to check once every 30 days)

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#3411]
To avoid the need to be online ALL the time, add a system to allow offline use as long as MAX checks into Steam every 30 days.

**Comment by MonkeyFrogStudio** [comment]
Requested here, too:

https://github.com/TheGameCreators/GameGuruRepo/issues/3349

**Comment by ZakJudges** [comment]
@LeeBamberTGC Did you already fix this one? :) I am able to run Max whilst offline
