### ISSUE TITLE
GG Max - AI - Hard Coded active distance of 3000 needs removing

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3417]
Please remove the hard coded distance that allows the AI to become active.
It can really spoil games where you are trying to have snipers. 
I Have tried everything from trigger zones that dont do anything, when having them try to activate an enemy.
I have tried setting Always Active in developer settings.

Its just stupid when you look through a scope, and see all the AI stood there still.
You can even walk forward (Whilst looking through the scope), and you get to see the AI start moving, But if there path takes them out of the range again they just stop moving.

After several tests, the activation distance must be set at 3000, This should NOT be hardcoded, and should be editable by the developer.

No matter whether the actually level looks amazing, with poor AI the game is poor.

I really hope there is a huge overhaul of the whole AI system. We need AI to be able to Sneak, Take Cover, Prone, Crouch, be always active if needed, work as a team (which is suppose to happen already, but does not)

EDIT : 
I would like to have a game with Snipers in the distance etc, that i can set the view range to quite far, but with the current system, the sniper in the distance would just not activate.
Then with snipers in the distance, the player would have to be careful, and take cover whilst killing enemies etc close by.

**Comment by MonkeyFrogStudio** [comment]
@Tum1370 Have you tried playing with View Range:

![viewrange](https://user-images.githubusercontent.com/36735507/178098645-6e9c558f-5059-46a6-bf4d-2bb0cfa4c85a.png)

It allows you to adjust the distance that the enemy "sees" you:

Set to 500:
![range1](https://user-images.githubusercontent.com/36735507/178098719-b501c89b-27c3-438b-ab9d-13b8c8cd6b72.png)

Set to 1000:
![range2](https://user-images.githubusercontent.com/36735507/178098726-6744faa2-53af-4ecf-a4e6-79371d19d72f.png)

Even though the slider only slides up to 2000, you can manually set the number to anything (5000, etc.).

**Comment by Tum1370** [comment]
@MonkeyFrogStudio That setting does not make any difference to activating the AI. 
As an example, go to the new Horseshoe bend demo, Edit the starter marker to the patrol rifle, instead of the compact rifle.
Then turn around, and check all the enemy through the scope.
They are all just stood still, and no matter whether i change the view range to a huge amount, they do not activate.
I Even then went to developer settings and selected Always Active, But same thing, they stand still.

It seems to be hardcoded to a certain distance from the player.
Like i said in first post, if you walk forward looking through the scope, you actually then get to the point when the AI starts to move, but if they follow a path away from the character, they simple stop again.

**Comment by Tum1370** [comment]
I would like to have a game with Snipers in the distance etc, that i can set the view range to quite far, but with the current system, the sniper in the distance would just not activate

**Comment by Tum1370** [comment]
After testing this a bit, i think the hard coded activating of AI is set to roughly 3000.

I set a character view range to 2800, and after moving forward, i could see the character start moving when looking through a scope. But then i had the character follow a path away from me, and the character suddenly stopped after a short walk.

i then tested setting the character view range to 3000, and as i walked towards the character, when the character actually activated, it could instantly see me and started to shoot.

Really we need an option to disable or set the activating range to whatever we would like, per character, rather than having it hardcoded in.

**Comment by PaulFox12** [comment]
I believe this was also a limitation in classic, it's incredibly irritating and stops you being able to have long distance combat with snipers etc. The distance should be set by the developer of the game, not the engine.

**Comment by Tum1370** [comment]
God i hope they remove it and let the developer decide in Max, else it will make the engine pretty useless else.

**Comment by Necrym59** [comment]
Those sorts of enhancements will come in time it doesnt make the engine bad at all, just changes to options when other bugs/things have been bedded down. Its still early access days yet.

**Comment by Tum1370** [comment]
I dont see why any engine would have hard coded limits on things like this ?
What we should have is every AI in game, should have an option to set for how far away we want it to activate, or whether we want it always active.
The default value would just be set at 3000.

This limit, and other hard coded set limits are so frustrating in what is suppose to be a game engine, that a developer sets the limits.

Something like changing this from what it is now, to what i suggested would probably not take long at all.

**Comment by Tum1370** [comment]
@MonkeyFrogStudio  Because i was told to post it in the stream last night.

**Comment by MonkeyFrogStudio** [comment]
They told you to post it because most likely they didn't recall it being on the board. It's SOP (standard operating procedure) to ask people to post on the board. But this is a duplicate and most of they time they just close them.

**Comment by LeeBamberTGC** [comment]
Duplicated, using other issue and closing this one. Will be done.
