### ISSUE TITLE
shadows kill it

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3418]
the second I try to have any ammount of shadows on in ggmax, it literally kills it. this is with all settings on low, and shadows on their lowest setting. Now I'm aware my gpu is abit old, so yes its potentially down to that, but if I can't have any decent lighting, why AM I even bothering anymore?

working on getting a new pc this year, but not sure if this comes under bugs or not, but yep soon as shadows are on.

DEATH occurs. 

![image](https://user-images.githubusercontent.com/68471279/178109444-e5910d6a-0877-4030-ae2f-7871542bc080.png)

**Comment by earthling45** [comment]
It helps if you give the specifications of your setup.

**Comment by davetgc** [comment]
Yes, please post your specs.

Many thanks,

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/178483234-5a69c652-858b-4529-bacd-8d9f3d607d1c.png)

:)

I mean getting a new pc built atm with a vastly better GPU, so alot of this could be down to a crap gpu.

**Comment by davetgc** [comment]
Your GPU isn't listed, but could well be the cause.

**Comment by casigus** [comment]
ah yes the gpu is problematic actually, sorry ! i

![image](https://user-images.githubusercontent.com/68471279/178497769-7e6095b3-bbdb-467b-bf54-48cfb62d3e9f.png)


the gpu is...the issue i believe, yes it may have 4gig of memory, but that doesn't mean anything if its a really cheap end one. got a new build on the way sooo hopefully that will improve everything.

**Comment by davetgc** [comment]
I think you're right, that card is below minimum spec, so is likely the cause of your problem.

**Comment by casigus** [comment]
absolutely. yeah. new system is being built !
