### ISSUE TITLE
GG Max- AI can shoot through terrain even though it cannot see you

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3419]
As the title says, The AI can shoot you through a hill even though it cannot see you.
As you can see in the screenshot, the AI is targeting me and shooting me through the hill.

![Untitled](https://user-images.githubusercontent.com/66874403/178111914-1855104a-e656-4802-873a-fd6fc26c7e75.png)

**Comment by davetgc** [comment]
Hi, are you able to make a video of this behavior?

Many thanks,

**Comment by Tum1370** [comment]
@davetgc you can see from the screenshot, with the AI testing lines showing the green line coming through the ground.

**Comment by Tum1370** [comment]
@davetgc 
HI, am not good with videos, but i have created a very simple map, the just test and you will see the enemy shoots you through the terrain.

[Shoot Through Terrain.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9093327/Shoot.Through.Terrain.zip)

**Comment by davetgc** [comment]
Updated this to high priority.

**Comment by ZakJudges** [comment]
@LeeBamberTGC Notes on this issue:
The result from ODERayTerrainEx seems inconsistent. Sometimes the terrain is detected, sometimes it is not. I have attached a map to reproduce the issue
[aa.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10941519/aa.zip)

**Comment by LeeBamberTGC** [comment]
NOTE: Video showing the issue for when I get to it: https://www.youtube.com/watch?v=klTrNEPvhGg

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed in EXP build, uploading soon.  Let me know here if you can still reproduce it under certain terrain designs.

**Comment by Tum1370** [comment]
@LeeBamberTGC Am sure i am still get shot through the terrain on my level.

**Comment by Tum1370** [comment]
@LeeBamberTGC I think i maybe found the problem i am having with the latest build and the AI shooting through the terrain.
Look at the screenshot, i have removed all the grass so can see the edges of terrain etc
I have added the AI Management Nav on so you can see the AI
Now on the screenshot, where i have circled RED, there is 2 AI actually shooting me through the terrain.
You can only just see the very TOP of their HEADS.

Maybe this is the new problem, The AI sees and shoots you, even if its only the TOP of the AI HEAD that sees you ?

![Untitled](https://user-images.githubusercontent.com/66874403/230913874-1da34614-1222-4ff4-889a-d629905233d4.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed for the NEXT EXP build :)  No more shooting from the eyeballs.

**Comment by Tum1370** [comment]
@LeeBamberTGC Just tested this one, and now the AI does not shoot out their eyes lol
But what i do see after testing several times, The AI just Stops at the brow of the hill, and does not push forward to take a shot, if you are still in visual range.

The AI really needs a huge overhaul i think, Sometimes its just very very dumb. 

Whilst i was testing this bug, i crouched on one side of a hill, The AI was just on other, not shooting at me because of the hill.
Then after the combat timer had ran out, the AI starts to walk off.
I then run up the hill, Shoot the AI in the back, It takes the shot, then continues walking away. Very dumb.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for confirming the fix. I have created a separate issue relating to AI improvements: https://github.com/TheGameCreators/GameGuruRepo/issues/4463
