### ISSUE TITLE
EBE - "TAB" does not work properly if a new floor is added to existing structures

### ISSUE THREAD

**Issue by C0mbie** [TheGameCreators/GameGuruRepo#342]
After adding a new floor to an existing EBE structure, If you press "TAB" the interior will not be displayed properly (e.g. invisible or dark/black floor, various visual glitches) making it hard or impossible to add new entities inside.

An example is provided below.

Normal situation:
![screen2](https://user-images.githubusercontent.com/42276000/43966146-690fb020-9cc1-11e8-945c-652d6430f1ac.PNG)

New floor is added:
![screen3](https://user-images.githubusercontent.com/42276000/43966163-729e06b4-9cc1-11e8-95f9-83e9aa6513b1.PNG)

What happens:
![screen1](https://user-images.githubusercontent.com/42276000/43966182-7d5c81ac-9cc1-11e8-8e22-869052c7fcd8.PNG)

**Comment by AmenMoses** [comment]
Ctrl + mouse wheel

**Comment by synchromesh62** [comment]
Ctrl + mouse wheel doesn't help … 
Definitely a fault as sometimes its only parts of the floor that are missing and show grass

**Comment by AmenMoses** [comment]
Ahh, probably something to do with occlusion then.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed with similar EBE issue reported … Probably related to the same issue using Tab

**Comment by LeeBamberTGC** [comment]
Same bug as two previous bugs, now fixed. Three For One Sale :) This one is fixed.
