### ISSUE TITLE
spent 20 mins placing lights.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3422]
after which when selecting the model to move it to the centre of the map. All the lights turned black.

![image](https://user-images.githubusercontent.com/68471279/178123384-9257fb0f-aede-46e3-83bd-70ce27166bd5.png)

yay.

**Comment by davetgc** [comment]
Please supply a video, if possible, for these kind of bug reports.  To help the team quickly identify issues, we need a clear description.
