### ISSUE TITLE
GGMAX - Ladder Behaviour Update

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3423]
Ladder updated to v23
- Fixed the joining of rotated ladders
- Fixed smoother joining of ladders when underwater. 
[ladder_v23.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9077991/ladder_v23.zip)

**Comment by davetgc** [comment]
Hi, has this been sent to Lee?

**Comment by Necrym59** [comment]
Yes was sent on 19/06/22 posted here as a reminder in case missed.

**Comment by Necrym59** [comment]
Latest release still hasn't updated to the new v23 yet
