### ISSUE TITLE
Request from Steam ..  "Show on Startup" tickbox for zones to enable spawning.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3426]
"Show on Startup" tickbox for zones to enable spawning.
Lots of used for this but this was mainly using a switch to spawn a winzone ( right under your feet to end a level perhaps )
or collect an item which in turn spawns a winzone to enable the end of a level.

https://steamcommunity.com/app/1247290/discussions/0/3416559828452846385/

**Comment by AmenMoses** [comment]
Just needs a change to the winzone behaviour I would have thought.

**Comment by AmenMoses** [comment]
The same thing could be done to most other marker behaviours btw, it's not really that difficult.

**Comment by synchromesh62** [comment]
> The same thing could be done to most other marker behaviours btw, it's not really that difficult.

Fantastic thanks Amen. Seems to work a treat :)

**Comment by synchromesh62** [comment]
> Is this working now?

It will work with Amen's edited **winzone.lua** but really needs to be a separate **task-winzone .lua** to avoid confusion if its added to the core.
