### ISSUE TITLE
some object physics shape are broken

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#3427]
for some models that are imported. for few launches in game are working allright, but after some time the hitbox of the objects just randomly moves away.

![GameGuru MAX - test1 fpm_ 10 07 2022 15_33_26](https://user-images.githubusercontent.com/109030026/178147851-6bb72759-c662-4dcc-9fda-620e1d2bd9e4.png)

**Comment by 42Pix3ls** [comment]
I am having the same issue 

![image](https://user-images.githubusercontent.com/95527550/178423968-4c46398d-1624-44fc-83b2-09edbfe64062.png)

**Comment by ZakJudges** [comment]
Hi all, closing this issue in favor of #4141. Please feel free to add any more comments to that thread
