### ISSUE TITLE
Ensure that the latest install path is stored in the registry for the Steam version of MAX

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3430]

**Comment by LeeBamberTGC** [comment]
@ZakJudges It seems we already do a good job of recording in the registry where the latest MAX was run from. Here is the code in the software that writes to it:

		// Write latest location of software to registry (for future patch installers)
		HKEY hKeyNames = 0;
		LPCSTR pSubKeyName = "Software\\GameGuruMAX";
		LPSTR pThisVersion = g.version_s.Get();
		LPSTR pThisPath = g.fpscrootdir_s.Get();
		DWORD dwDisposition;
		DWORD Status = RegCreateKeyExA(HKEY_CURRENT_USER, pSubKeyName, 0L, NULL, REG_OPTION_NON_VOLATILE, KEY_ALL_ACCESS | KEY_WRITE, NULL, &hKeyNames, &dwDisposition);
		if ( Status == ERROR_SUCCESS )
		{
			if ( dwDisposition == REG_OPENED_EXISTING_KEY )
			{
				RegCloseKey ( hKeyNames );
				Status = RegOpenKeyExA(HKEY_CURRENT_USER, pSubKeyName, 0L, KEY_WRITE, &hKeyNames);
			}
		}
		if ( hKeyNames != 0 )
		{
			if ( Status == ERROR_SUCCESS )
			{
				Status = RegSetValueExA(hKeyNames, "Version", 0, REG_SZ, (LPBYTE)pThisVersion, (strlen(pThisVersion)+1)*sizeof(char));
				Status = RegSetValueExA(hKeyNames, "LatestInstallPath", 0, REG_SZ, (LPBYTE)pThisPath, (strlen(pThisPath)+1)*sizeof(char));
			}
			RegCloseKey(hKeyNames);
		}


From this, you can work out how to read the registry string for the install path.
