### ISSUE TITLE
Characters/Animals not moving

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3432]
no matter what settings I use the characters and animals stay in place for some reason only the birds react and fly away this problem I'm only having on this map if I load another level this does not happen, I'm not sure what's causing it please help! 
https://youtu.be/yKCaqsRzNY0
https://youtu.be/BGzhXl5oXrI

**Comment by ZakJudges** [comment]
Hi @Sinergygames, apologies for the late response. In the latest EXP build, these issues should now be fixed

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
