### ISSUE TITLE
importer error strikes back

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3434]
very bizaaar error.

this is the model in the importer as I want it to look:

![image](https://user-images.githubusercontent.com/68471279/178399057-3662d4fb-e378-4247-b4d5-73838e40a012.png)

and this is after i've imported it:

![image](https://user-images.githubusercontent.com/68471279/178399123-1db193e1-6e40-444f-9879-f313f4e05b64.png)

some where along the way the texture has changed it self, even when i apply the correct texture in the editor post import, max just changes it back to this one.

I dont get it.

![image](https://user-images.githubusercontent.com/68471279/178399225-bb3ee929-162f-48cc-b8a7-fcb5349f4d9f.png)

on top of that the collisions for parts of the model still dont work, the player just falls through them as if there was nothing there. 

Am I doing something wrong? been trying to get this right since 9am till now (its 3am the next day)

**Comment by davetgc** [comment]
Hi, can you please share the model so that it can be tested.

Many thanks,

**Comment by casigus** [comment]
absolutely. sent this one to lee, you want a look at it to??

**Comment by davetgc** [comment]
Hi, no, that's fine if Lee has the model.

**Comment by davetgc** [comment]
Can you check that the model isn't using a duplicate texture. It's possible that you have a different texture with the same name in the root folder.
