### ISSUE TITLE
Getting imported FBX alive with behavior??

### ISSUE THREAD

**Issue by RobDaHob** [TheGameCreators/GameGuruRepo#3435]
Getting imported FBX alive with behavior??
Or just animate the ppor thing   -  as static.
Is it anyway to make imported fbx 3d model alive with behavior.
Did test give an imported character behavior but nothing happend...
Can you get them animated?
Any clues
thx
Rob

**Comment by davetgc** [comment]
Models must be animated outside of MAX. No game making software can animated a non animated model. If you are able to share the model, we can take a look and give advice.

**Comment by earthling45** [comment]
OBJ extension does not hold info on animation, only the geometry so FBX should be used for animated objects.
If you have an animated character you should have a list of the animations and frame numbers for those animations before you import it in Max.
This is something for very experienced modelers though and i am not one of them.
I thinkk you should take this question on the Gameguru Discord or the GameGuru forum to ask help of the community members on how to import an animated model. :)

**Comment by RobDaHob** [comment]
How do I import them?
Thx for your help anyhow.
Max will be great.
Rob
