### ISSUE TITLE
Max is of no use if no work

### ISSUE THREAD

**Issue by RobDaHob** [TheGameCreators/GameGuruRepo#3436]
I I cant spree the games me done..
So try make it what it say it is.
Try it in different computers.
And make it a working app.
thx
Rob

**Comment by davetgc** [comment]
Please explain what isn't working for you, and also, would you be able to post your system specs.

Many thanks.

**Comment by RobDaHob** [comment]
Just dident work on my other computer were Max was not installed.
What happend to the other posts on this subject?
Just like you to check it works on computers that not have max installed.
Thats it.
Thx
Rob

**Comment by davetgc** [comment]
Hi, this issue has been raised by several people and is being investigated,

Hopefully, we'll have a solution soon.


st
