### ISSUE TITLE
Game Guru Max: Crash on Incorrect Dynamic Lua List Item Value

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#3443]
if you assign a value that does not exist for list items in dynamic lua, the Engine will crash.

 For example [Selection!=3(1=item1,2=item2)]

Since item 3 doesn't exist.

Perhaps we could have an error could prompt? For now in the meantime I'll be more careful :D

**Comment by Necrym59** [comment]
Selection! is on/off check box type there is no 3rd selection try using [@Selection=3( 1=item1, 2=item2, 3=Item3 )]

**Comment by ZakJudges** [comment]
Hi @Teabone3, apologies for the late response. I think work on #3323 might have fixed this issue, as I could not reproduce it in the latest EXP build. 
I used [@Selection=3(1=item1,2=item2)] which this resulted in the list being displayed with only item1 and item2, without a crash.

**Comment by Necrym59** [comment]
Seems fine here Zak

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
