### ISSUE TITLE
GameGuru Max - Request - Enhancement - Ragdolls (Don't) Float On Water

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3446]
Been meaning to report this one for a little while.

Video demonstration: https://www.youtube.com/watch?v=jj6JU3AYP4E

As can be seen in the video above, when the character falls they don't recognize the water, meanwhile the pistol he was holding sinks gently down to the bottom, as does the crates i end up "pushing" into the water later in the video through a small explosion.

EDIT: 
There is a resolution to this that can be considered an enhancement, the first clue is in the post title, "ragdolls don't float on water." from what i've seen so far every item with physical properties sink to the bottom, but what if ragdolls float on top of the body of water? this becomes relevant in terms of RPG gameplay as this means it's easier to loot dead bodies, you don't have to dive into the deep blue if a body somehow ends up falling into a river.

Or maybe you have both? maybe a body only stays afloat for a set amount of time before sinking, just some food for thought.

EDIT 2: This is not a bug but an enhancement in it's entirety, appropriate change has been made to the title, also AmenMoses made a very similar post before mine (posted below), so refer to that one also when looking into this.

**Comment by DaveTGC2** [comment]
There is no water physics are present, so this would be considered an enhancement for improved water.

**Comment by AmenMoses** [comment]
#1573

**Comment by Lemuripest93** [comment]
> There is no water physics are present, so this would be considered an enhancement for improved water.

Ah, got it, will change title.

**Comment by nomad5oul** [comment]
As an extension please can we make ragdolls continue to be active after death

**Comment by davetgc** [comment]
This is technically an extension of this issue: https://github.com/TheGameCreators/GameGuruRepo/issues/1573

Please add to that post, rather than start a new one, thanks.
