### ISSUE TITLE
ggmax Collison shapes not working on blender assets on polygon collision mode

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#3448]
https://user-images.githubusercontent.com/107326667/179291385-aef56a77-f553-4fb6-93cb-759ced134b1b.mp4

**Comment by RajMaha1** [comment]
https://user-images.githubusercontent.com/107326667/179292339-21232b3e-e1f2-4ea1-ae5e-4b66b7c1a93c.mp4

**Comment by MonkeyFrogStudio** [comment]
I'm not experiencing this at all and I use Blender exclusively to develop my own models, specifically for interior-only levels. I find that all collision modes, polygon included, and even using my own collision meshes, work fine in MAX. When running a test game, can you use TAB TAB and under the Physics tab, tick the Render Physics Shapes tick box? This will show the collision mesh/shape your model is using. If you don't see the Physics tab, then go back to the editor, go to Edit>Settings and under Developer, tick the Show Additional Developer Options tick box. Then you should be able to access it in the test game.

**Comment by MonkeyFrogStudio** [comment]
Here's an example:

![collision](https://user-images.githubusercontent.com/36735507/179305802-68a7f72b-35d4-4d4d-bcea-88add21fadf4.png)

Just imported this model, made in Blender, and applied polygon collision as a test. It shows up as it's supposed to and the wall stops my character from passing through it.

**Comment by RajMaha1** [comment]
just wondering if i'm doing anything wrong or does this need fixing

**Comment by MonkeyFrogStudio** [comment]
If you click on your object in MAX and go to the General tab on the right, does it say that the Static Mode for the object is Static (if that's what you want the object to be) and under Collision Shape, does it say Polygon (or some other collision shape)?

**Comment by RajMaha1** [comment]
yeah I'm using polygon and I'm experiencing some planes having no collision

**Comment by MonkeyFrogStudio** [comment]
Can you show some screen grabs from the test game like I said above, using the Tab Tab menu to access Render Physics Shapes?
