### ISSUE TITLE
Emissive textures

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#345]
If you set an emissive texture it is tiled on the model when you get close up, in the screenshots the lit windows are using the emissive texture but when the player gets close to the model the emissive texture is all over it, the model is using apbr_basic.fx
![snapshot27](https://user-images.githubusercontent.com/36109432/43973783-5bac12fc-9cd0-11e8-8710-7862866ebb64.jpg)
![snapshot25](https://user-images.githubusercontent.com/36109432/43973803-6596fcf0-9cd0-11e8-8ab2-d7b1712f8fd5.jpg)

**Comment by michaeloldman** [comment]
I have found you have to use apbr_illum.fx for models with illumination.

Refer this discussion [here](https://forum.game-guru.com/thread/219745#msg2601657)

Reliquia....

**Comment by BodRH** [comment]
I already tried that and it does exactly the same, in fact I have tried every available .fx listed in the model importer and nothing solves it, every model which shares the texture gets tiled over the _color texture with the _emissive texture.

**Comment by plemsoft** [comment]
@BodRH I tried different things and actually got a similar result when i tried to lightmap a building that was using a _emissive texture , can you confirm that the above screenshots is also lightmapped ?

**Comment by BodRH** [comment]
Yes it was lightmapped.

**Comment by michaeloldman** [comment]
Yeah, light-mapping a level with either _illumination or _emissive extension, and also using either apbr_basic.fx or apbt_illum.fx  will result with the map tiled over the model, and all illumination is lost, and regard.

I have found that sometimes when you have several different models using illumination on the same map that not all models are affected. Like one may work fine.

I have wondered if this perhaps has something to do with the _detail map not being used, like does it happen when a _detail map is present, but have not got around to testing that.

May give that a go if I have time tonight.

Reliquia....

**Comment by plemsoft** [comment]
Thanks,

Added illumination/emissive support to the lightmapper.

Ready from the next update :)
