### ISSUE TITLE
EBE Save Abends MAX

### ISSUE THREAD

**Issue by jasailor** [TheGameCreators/GameGuruRepo#3450]
I am using EBE classic within MAX to construct rooms within a Classic asset SciFi Pack - Room 2 (base).   I create an EBE model with and align it with the corner of the Room2.   I can select the EBE asset in the scene and make changes to the EBE object and it works fine and edit the EBE as needed.  (Will be a great way to create interiors inside blank building assets.)   When I go to save the edited EBE, however, it requests a EBE name and when supplied it abends MAX without saving the updates to the EBE. 

Let me know the nature of the further information you may need.

JASAILOR

**Comment by davetgc** [comment]
Hi,

The EBE is a legacy feature and no longer supported. We have plans that are fairly well developed to replace this with a newer, more advanced feature.
