### ISSUE TITLE
GG Max - Bug - Water issue

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3451]
As you can see from the screenshot, When you fire a gun in to the water, the water goes all strange and disappears and you can see the lake without the water in sections.

![Untitled](https://user-images.githubusercontent.com/66874403/179370815-4ffe0555-79e1-4283-b347-fa3be01598ca.png)

**Comment by davetgc** [comment]
Confirmed

**Comment by LeeBamberTGC** [comment]
@Tum1370 No more artifact in latest EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/cbf3fce5-1d3c-48d5-83b2-b326ab017e21)

**Comment by Tum1370** [comment]
@LeeBamberTGC Just tested on the latest build, and can confirm that this bug is now fixed. 
Thanks for the fix Lee, i will now close this issue. :)
