### ISSUE TITLE
GameGuru Max - Bug - Sliding Door Refuses To Move Unless Close-By

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3456]
IMPORTANT EDIT: Ignore the post below (or read it for context), this is no longer an enhancement post but a bug post, check comments.

This one should be somewhat simple to implement, and the reason for requesting it is, not surprisingly to do with RPG's, castle gates, city gates, hangar doors, just **_big_** heavy gates and doors in general are pretty much impeded by the current limit on distance, included below is a video showcasing what happens when you use the max distance on a massive door, or rather a wall in this case - but it serves the point.

https://user-images.githubusercontent.com/104637906/179405091-3b9f4ab4-6917-46fb-a1b2-db3c01456572.mp4

![ggmgaterequest0](https://user-images.githubusercontent.com/104637906/179405104-56c177bc-1a70-4f7d-942f-7601ea79c62d.png)

The new limit doesn't have to be 1500, some testing would probably be required for the final result, but that value more or less makes sense in my head.

Alternative: 
This could be a new set of behaviors for larger doors/gates just like we have "Door, Door Rotate and Door Slide" we could have "Big Door, Big Door Rotate and Big Door Slide", or something similar, though this **_is_** just an alternative and not required. Basically only go this route if it should clutter up usability for regular sized doors.

**Comment by MonkeyFrogStudio** [comment]
@Lemuripest93 There is no limit on Distance. The slider may only go to 100, but you can use the numeric entry box and type in any number you like. So, replace that 100 with 1500 if you want.

**Comment by Lemuripest93** [comment]
> @Lemuripest93 There is no limit on Distance. The slider may only go to 100, but you can use the numeric entry box and type in any number you like. So, replace that 100 with 1500 if you want.
> 
> BTW - This is true of all the sliders. They may only go to a certain number, but you should be able to type in any number you like regardless of the slider limit.

God damn it, lol you're right! i wish i knew this sooner, thanks a lot man!

**Comment by Lemuripest93** [comment]
@MonkeyFrogStudio 
I've actually run into a different problem now that i figured this out thanks to your help, i can open the doors just fine, but when i try to close them, they'll refuse to unless i physically move closer to them.


https://user-images.githubusercontent.com/104637906/179427641-2cd0358b-b197-4a5b-9cf6-44f472227997.mp4

**Comment by Lemuripest93** [comment]
Ticking 'Always Active' under 'Developer Settings' solved the issue, please consider making 'Always Active' a tickable setting outside of the 'Developer Settings'.
