### ISSUE TITLE
Undiscoverable entities in map editor

### ISSUE THREAD

**Issue by demented-mind** [TheGameCreators/GameGuruRepo#346]
A complete description and video can be seen [here](https://forum.game-guru.com/thread/219963).

Please take this seriously because it is quite troublesome when wanting to use entities that have this issue.

https://forum.game-guru.com/thread/219963

**Comment by plemsoft** [comment]
@demented-mind Thanks for reporting this,

This has been fixed in the latest beta , could you please confirm , thanks :)
