### ISSUE TITLE
GameGuru MAX - Bug - Importer Can Lose Object Names When Importing Multiple

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3462]
I did a test today where I imported a room that consisted of 21 parts. Each part had it's own unique name. This was exported out of Blender as a single FBX file and imported into MAX. Some of the objects have most of their name missing (all but the first letter):

![missing](https://user-images.githubusercontent.com/36735507/179847258-363ba63e-e1bf-44f5-95dc-a62e05371ac3.png)

I need to go through and figure out which ones didn't get the correct name. Once I do that, I will report that here.

EDIT: Also, we can see that MAX is still generating material names off the textures themselves instead of the actual material name the model has. However, none of my textures are simply named "Q", so I don't know why these models didn't get a full name.

**Comment by MonkeyFrogStudio** [comment]
Looking through the list, I found that all the missing names (all the ones simply named "Q") had the word "Door" in their name:

Q_Door_Frame_01
Q_Door_Wall_01
Q_Door_Left_01
Q_Door_Right_01

The materials are named similarly (Q_Door_Frame_M, Q_Door_Wall_M, etc.). There is no material/texture named "Q". So, no idea why MAX has truncated these names.

**Comment by MonkeyFrogStudio** [comment]
This is still an issue. In the following image I show an object imported as one object consisting of four models, each with their own material. Here's how the material names show up in MAX:

![material](https://user-images.githubusercontent.com/36735507/200129246-3e9607d0-0348-48ad-a0c3-17f9162e3fd5.png)

As a result, I can't tell which material I am selecting, other than looking at the albedo file. 

**_As a secondary note - Two of the four have Emissive textures and two do not. Even so, MAX adds Emissive textures to the two materials that do not have them. This should not happen._**

**Comment by Ratall** [comment]
This issue has existed a long time see #3311 read to the end

**Comment by MonkeyFrogStudio** [comment]
@Ratall Yes, I am aware of that thread. However, the point of this one is 1) that the names are simply missing, not just incorrect and 2) that this is the result of importing a single object made up of multiple parts, each with it's own material. This is not just about incorrect names, it's about missing names.

**Comment by Ratall** [comment]
@MonkeyFrogStudio Sorry I was not implying you were not aware of the thread but I do think they are related problems ,

 Max does not seem to get its information from the correct places in the imported file. 

The problem I encountered was not just the names being incorrect, it seemed to get the names from the texture file names using the bit before the first "_" (for example "MFD" from "MFD_ Device" ... ) but If there was no texture file it used the generic holder of "noname"

 I do not know if this is a problem with assimp or the way it is being used.   

I must also admit that I have not been using max for some time so I am not aware of the latest problems.  Unfortunately I do not have time or energy to fiddle around trying to lever my models in  via its currently braindead importer so I have dropped trying to use it.

I think most people agree that Max has the potential to be a great product but really needs to learn to play well with others.

**Comment by GraPhiX-Guru** [comment]
@MonkeyFrogStudio do any of your assets or texture name or even the groups have spaces in them ? i had a similar issue removing all white spaces from the names resolved it for me

**Comment by MonkeyFrogStudio** [comment]
@GraPhiX-Guru Nope. No spaces. However, they do have underscores. So, names could be something like:

door_hall_01
floor_hall_01
Etc.

My suspicion is that MAX doesn't like the underscores. I suspect it's related to this one I reported:

https://github.com/TheGameCreators/GameGuruRepo/issues/3676

If I have a model named **_floor_hall_01_**, then I end up with six files (bmp, fpe, dbo, color, normal, and surface). That part's fine, however, the names of the first three files will have the underscore removed while the last three files will retain them. So, the fpe for **_floor_hall_01_** would become '**_floor hall 01.fpe_**' while the color texture would be '**_floor_hall_01_color.dds_**'.

I don't know why MAX changes the names. But, as you can see by my request above, I've asked for that to be fixed. ;)

**Comment by ZakJudges** [comment]
Hi all, this is likely now fixed as part of work on #3676 

The fix is part of the Steam experimental build

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges This is indeed fixed! Just tested with a single FBX that contained 21 objects and many materials (same model from the first post) and everything came into the importer perfectly. Thank you! I'm closing this one, too.
