### ISSUE TITLE
GG Max - ALL the AI just stood there still not doing anything, until i was almost up to them

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3465]
Just tried the Horseshoe band demo, on the latest experimental version of Max.
All the AI near start of map, runs towards the starting area of the player, then returns to there positions.
If the player moved, The AI then starts running back to where to player was, after they get back to there starting positions.
This just keeps happening after every time they return to there starting area.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
After testing this a lot, on a new map. the latest Experimental build AI basically runs to the last location that the player was, If it doesnt see you it gets to the last player location, then it returns to its start location. After getting back to start location, it then starts running to the new last location of the player.

I hope this additional info can get this fixed very quickly.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Latest EXP build fixes the issue, let me know how it goes, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC  
I have just re tested this on the latest Experimental build, but now the bug seems different.
I only had a quick test as i have to go out now, but when i loaded in to Horseshoe Bend, and then started walking towards the entrance to the camp.
ALL the AI just stood there still not doing anything, until i was almost up to them.
They then started shooting me, and  running after me.

They did not start walking the path that is assign to them.

**Comment by Lemuripest93** [comment]
I can confirm i've got the same issue when it comes to NPC's only activating a certain distance away, but i also think this is related to another bug i posted about a few days ago: #3456 (check my last comment at the bottom)

Here is a new video with both a character walking a path, and the same sliding door issue from the other post i made:
https://www.youtube.com/watch?v=db9IjDK0-pY

As can be seen, when i spawn in, the NPC walks just fine, and the doors opens just fine, but when placed further away, they both stop working until you reach a certain distance - with a more crowded map like in my original post, doors stop working from a short distance, and characters rarely or even refuse to walk paths at all and just stand in place walking without moving.

Are these related at all or am i wrong?

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Did you tick the always active flag in the developer settings property for the relevant objects?

**Comment by Lemuripest93** [comment]
@LeeBamberTGC Did now, that was the solution! :)

Could 'Always Active' be made a feature outside of 'Developer Settings'? would definitively be useful.

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Good idea, will be in next build :)

**Comment by Tum1370** [comment]
@LeeBamberTGC 
This has lot been fixed yet. 
please read my last message here.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Only just got home from work, and noticed there was another GG max update, Going to Test horseshoe bend now and report back to you.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Oh ye, definitely not fixed.
Loaded in to Horseshoe Bend, Then Walked up to the camp entrance.
The AI should all start walking their paths when am within the 3000 range, but they dont.
They all just stand still, and only wake up i think when i am within the view range.
Then they start to attack and run after me.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Check for a new EXP build in 20 minutes, should restore your patrollers. The change was with =alert which now allows them to be quicker on the draw when this is ticked and starts them in a higher state of alert.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Perfect now, All working fine.
Thank you.
