### ISSUE TITLE
GG Max - BUG - Please FIX the Always Active option to allow AI to ignore 3000 distance limit

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3469]
As per the mention in the live broadcast today, You did not realise that the Always Active option did not work on characters that were further than the hard coded distance of 3000.

Could you please fix this option, so it allows us to start having some long distance snipers on our games, at a much greater distance away from the player.

**Comment by MonkeyFrogStudio** [comment]
You already asked for this here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3417

And TGC labelled that one already as an enhancement. Why post it again? All that does is clutter up the board.

**Comment by MonkeyFrogStudio** [comment]
Sigh. I get that. I was there at the broadcast. Lee just didn't remember that this was already requested. You should either close this one or close the other one. There's no need for two of them on GitHub. That's the point.

**Comment by synchromesh62** [comment]
> Sigh, i will close both when fixed. Thanks

If you want to close your other which is labelled enhancement i will label this fresh new one as a bug.
It will stand out much better for Lee as a new bug.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
As requested in the Stream Always Active not working and assigned to yourself.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed for EXP build, please confirm, and thanks for the reminder.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Thanks, Just tested this on latest Experimental build and was working fine.

Thank you :)

**Comment by synchromesh62** [comment]
Yep confirmed working brilliantly 
Thanks Lee
