### ISSUE TITLE
 Max - BUG - Something strange is going on with my doors

### ISSUE THREAD

**Issue by ShadowMasterOfGames** [TheGameCreators/GameGuruRepo#3472]
@LeeBamberTGC 

Not sure if this is a bug or something else.

My doors that are using the regular door script are swinging open on their own in the editor and in test game mode, can anyone help with this?

Edit: By the way, in the test level, you cannot walk through the door until you use the E keys on them but you can see everything inside the building. The video explains it better than I can.

I am using the experimental on steam, here are videos showing the strange behavior of the doors:
Inside of the Editor
[https://screenrec.com/share/QJomYL61Dc](https://screenrec.com/share/QJomYL61Dc)
Inside the test level
[https://screenrec.com/share/zviFxsfASI](https://screenrec.com/share/zviFxsfASI)

**Comment by synchromesh62** [comment]
Confirmed Door animation animating in editor and ingame 

![DOORS](https://user-images.githubusercontent.com/35708217/180271630-84919ad7-ffac-423e-8b57-e2c29de42f03.gif)

**Comment by synchromesh62** [comment]
> @ShadowMasterOfGames Fixed for next build, thanks for the great report!

If its the experimental update we just had i can confirm its fixed.
Awesome thanks
