### ISSUE TITLE
BUG Characters Not Walking up stairs correctly 

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3473]
I'm trying to get the enemy to walk up and down the watchtower steps I have everything setup correctly, this should work just fine but when I place the flags going up the steps like you see in the video the Characters does not turn they just moonwalk up and down.
https://youtu.be/nldwTPQUZ1k

**Comment by LeeBamberTGC** [comment]
@Sinergygames Works great now in latest EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/37e8b031-4e14-4148-a5fc-3e2f18dba4f8)
