### ISSUE TITLE
Player Capsules Are Too Big

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3476]
https://youtu.be/fv_8N3Q-tOo
EDIT**

It is the PLAYER Collision Capsule that is way to big.

**Comment by Kitakazi** [comment]
Yea I can when I get home from work but that video above is from the new Demo level. Right when you hit test game you spawn there.

**Comment by AmenMoses** [comment]
![AI capsules](https://user-images.githubusercontent.com/35708338/180564902-2326c076-e5ec-45d1-b2ee-a0d9087bf38f.png)

I think it is the player capsule that is too big!

**Comment by Kitakazi** [comment]
Yea, definitely the player capsule!
Thank you AmenMoses!

I will edit the title when I get home today.

**Comment by Kitakazi** [comment]
Making the player capsule smaller by default would probably fix #3077 as well.
