### ISSUE TITLE
Particle Editor - TGC version disabling on update.

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3481]
Hi Lee I bought Gameguru max directly from the website and much later bought the Particle Editor. The only problem is every time there is a update and I update Gameguru Max it disables the Particle Editor in the Edit dropdown menu. I have to keep re-installing the Particle Editor software. Will this issue be fixed.

Many Thanks
Tam51

**Comment by LeeBamberTGC** [comment]
@Tam51 Fixed a while ago when we moved the Particle Editor Tool into the main MAX core product, turning the PE DLC into a collection of particle library choices.  The option should now always be available.
