### ISSUE TITLE
GGMAX - Minor Bug - Switching from the ramp/slope terrain tool before creating a slope leaves the marker visible

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3482]
If you click once to start a slope, then change brushes or modes before clicking a second time to create that slope, the slope marker will remain on the screen, rather than disappear when deselecting that tool. 

![ramp-bug](https://user-images.githubusercontent.com/103399301/180607963-ccbeeb6d-5184-4f8e-99bf-d1e3076e1e5b.jpg)

**Comment by davetgc** [comment]
Confirmed.

**Comment by ZakJudges** [comment]
Hi @Kravenwolf, thank you for reporting this issue. This has been fixed and should be in tomorrow's build :)

**Comment by Kravenwolf** [comment]
@ZakJudges, I just updated my Steam version of MAX and gave it a try. 

I am using V22.12.13 (I don't run the EXP builds). In this build, the ramp marker goes away if you click on another sculpt tool, HOWEVER, if you click to create a slope, then switch over to paint the terrain, the marker stays attached to the cursor. Selecting a terrain texture from there will then allow you to paint terrain with the slope tool marker still following your mouse.

**Comment by ZakJudges** [comment]
Hi @Kravenwolf, apologies for the late response! The fix was uploaded to the EXP build. We are planning another public build once the work on RPG has finished :)
