### ISSUE TITLE
GameGuru MAX - Bug - Enemies STILL Walk Through Closed Doors (and Nav Mesh Issue, too)

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3486]
This is why I am reluctant to create a demo or do any "serious" work on an interior level in MAX:

https://user-images.githubusercontent.com/36735507/180620062-3cddeece-e918-49b4-a474-c9e707e8f28a.mp4

This was taken with the latest build, too.

**Comment by synchromesh62** [comment]
Confirmed i had this with a Zombie tonight also .. 
Dis think it maybe a fluke at first but with report seems to also confirm my experience.

**Comment by MonkeyFrogStudio** [comment]
In my latest tests, the enemy isn't able to cross the threshold of my door frame any longer. So, I did some tests and discovered something. 

If I take away the door, MAX generates the following nav mesh:

![collision1](https://user-images.githubusercontent.com/36735507/180627034-a04e8093-fdd1-4303-86cf-f2eb241f0d0a.png)

My door frame has a small ramp at the base of it and, as you can see, the nav mesh goes over that ramp nicely. The enemy can easily run through the door frame to get at me. However, things change once I add the door. The door is set to Physics On, box collision, and IsImmobile is checked. The Door Sliding behavior is being used to cause the door to slide upward. After placing the door in the level, the nav mesh is generated differently:

![collision2](https://user-images.githubusercontent.com/36735507/180627093-7a7061fc-5f29-461d-ac9a-0a5bc0be9198.png)

As can be seen, the nav mesh is now pushed BELOW the ramp of the door frame. As a result, the enemy stops at the other side (where the nav mesh meets the ramp) and cannot cross over. 

The only change, as indicated, is the addition of the door, which is not a static object, but a physics object. So, why is the nav mesh being forced below the small ramp at the base of the door frame when this object is in place?

**Comment by MonkeyFrogStudio** [comment]
I believe this is fixed now.
