### ISSUE TITLE
GameGuru MAX - Bug - Base Male and Female Rigged Models Don't Work (.blend file)

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3487]
If you open the .blend file for the base male or female model and then export that out as an FBX, the model imports into MAX, but does not deform with the bones. It moves with the animations as if it's a stiff, wooden board. I might be doing something incorrectly, but so far I've not been able to get these figures to work and import into MAX.

**Comment by MonkeyFrogStudio** [comment]
An example:

https://user-images.githubusercontent.com/36735507/180627528-8b2fe389-c325-44fc-ab2f-26531683b304.mp4

**Comment by bond1mjb** [comment]
@MonkeyFrogStudio Yeah skinned FBX import is not working correctly at the moment in GGMAX.   I assume it's a problem with the assimp library that GGMAX uses, since the FBX file imports into Blender and 3ds Max just fine.

GGMAX uses .X format for all characters and weapons, so you will need to export to that format for the time being until more formats are supported.   But you will need an older version of Blender to do this.

These are the steps I used.   First, download Blender 2.79 from here:  [https://download.blender.org/release/Blender2.79/blender-2.79b-windows64.zip](url)  Then download the directX exporter and install it as instructed: [https://github.com/spamandeggs/directX_blender/wiki](url)

Import the FBX file into Blender 2.79, and export to .X using the settings below:
![blenderx](https://user-images.githubusercontent.com/87768878/180629857-33ede4bc-07bb-48d1-b2b7-5e4af9f14ad6.jpg)

Now you can import the resulting .X  file into GGMAX, and all is working including animations, although I had to scale the character up by 4000.  


![xMAX](https://user-images.githubusercontent.com/87768878/180629923-1e4c4641-13a5-4714-a7ce-0d1b00710155.jpg)

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb That's ... just ... X format? I know, but that's such an old, outdated, obsolete and severely restricted format. I've not tested anything but the FBX that was in the Guides folder. What about OBJ and GLB/GLTF for character models?

Thanks, btw, for the help with older Blender versions (if I wanted to go that route).

But, yeah, this needs to be fixed as soon as possible. Not being able to import a character model using a modern 3D file format is ... just not good. ;)

**Comment by bond1mjb** [comment]
@MonkeyFrogStudio Yeah X format exporters are getting harder to find these days.   Of the "major" 3d apps, only 3ds Max still has an actively maintained X exporter.   

FBX for skinned animated models is broken in GGMAX at the moment.   As is GLTF - which is weird because Wicked Engine supports GLTF just fine, I just this character exported to GLTF  with the latest Blender, and it imports into Wicked just fine.   So it's weird that GGMAX doesn't work with GLTF.    And OBJ format doesn't support animation, period.

So unfortunately at the moment, it looks like Blender users will need to use a pipeline of:
Blender 3 --> FBX ---> Blender 2.79 ---> X ---> GGMAX

Hopefully at some point GGMAX will also be able to handle FBX and GLTF for skinned models.

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb Not just Blender users, but people who are not using 3ds MAX, apparently. I also have MODO, but that's not going to help as it doesn't export to X. And, as you've pointed out neither FBX nor GLB is working, either.

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb Question - I've used bones to animate hard-body objects, like opening/closing doors. I've exported these to FBX and they import into GGMAX just fine (i.e. the animations work as they are supposed to). Is this because we are not deforming the mesh? Does this mean that only hard-body type animations currently work with non-X formats?

**Comment by bond1mjb** [comment]
@MonkeyFrogStudio  I think that is correct.  As a test, this cage door is directly animated, no bones, just rigid body animation. It imports with animation into GGMAX fine (nevermind the jerkiness of the looping gif):
![CAGE](https://user-images.githubusercontent.com/87768878/180636289-49b219ea-f17c-4df8-81b4-80d25c6a67f6.gif)

But this lightswitch uses bones to animate the lightswitch, and it will not import correctly.  Only the switch should move, but instead the whole thing flaps around just like the character.   So at least for me, exporting directly from 3ds Max,  skeletal animation using bones/skinning does not work at all for FBX.

![SWITCH](https://user-images.githubusercontent.com/87768878/180636374-65d8e4f9-9793-4c22-89f8-e09f18b17e11.gif)

**Comment by bond1mjb** [comment]
@MonkeyFrogStudio  Question, when you say you used bones for rigid animations, did you "skin" the mesh to the bone, or just link the bone to the mesh?   There's a difference.

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb It's been awhile since I'd done this, but I used bones and parented them to the door so that moving the bone would move the door. This is used when you have a single model consisting of more than one part - i.e. a sliding door consisting of a left-side and right-side that need to slide to the left and right. You cannot animate the parts separately since it is one model, but you can use bones to affect only the parts. So, I've done this with a door that consisted of two parts and a door that consisted of three parts, but were all one model (one animation using Open and Close animation names to work with MAX's Door Behavior).

**Comment by MonkeyFrogStudio** [comment]
This animated door, for example, was made with bones and not just keyframe animation:

http://www.monkeyfrogstudio.com/uploads/MAX/quad_door.mp4

**Comment by bond1mjb** [comment]
@MonkeyFrogStudio  We might be getting caught up in semantics since 3ds Max and Blender have such different workflows for this type of thing.   I'm just not familiar enough with Blender to do a deep dive.

In any case, FBX import for skeletal animations is broken in GGMAX at the moment.  I have to assume GGMAX is at fault, since the FBX character file checks out fine in the official Autodesk FBX Reviewer:

![adfbx](https://user-images.githubusercontent.com/87768878/180695243-fa130196-8583-479e-aebe-9262fad11001.jpg)



And just to be doubly sure,  it imports perfectly into Unreal Engine too, with bones and animations intact:

![unrealbasemale](https://user-images.githubusercontent.com/87768878/180695167-2930497a-5f02-4d0c-aa60-f64e324c383f.gif)

**Comment by LeeBamberTGC** [comment]
@bond1mjb Can you email me the FBX rig that works in UR but not MAX, that will give me somewhere to start. The FBX and GLTFs I got from SketchFab a while back all worked fine for me, I guess gremlins still remain :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC You can find the model that both of us were using in the Guides folder of the GameGuru MAX install - 

Program Files (x86)>Steam>steamapps>common>GameGuru MAX>Guides>Characters

Both the base male and female compressed files have an FBX in them. It's that FBX that is not working correctly. Or you can take the .blend file, open it in Blender, and export that as an FBX to use as well.

**Comment by bond1mjb** [comment]
@LeeBamberTGC  Here is the base male character in FBX and also GLTF format.  Neither one imports animation correctly in GGMAX.    The GLTF version works in Wicked Editor (Wicked doesn't support FBX).


[basemaletemplates.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9210452/basemaletemplates.zip)

![wicked](https://user-images.githubusercontent.com/87768878/181531077-aa7aadd3-3a0a-4d55-905c-931bf5af9174.jpg)

**Comment by LeeBamberTGC** [comment]
I will grill AssImp and see why we are getting gremlins.

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges 

Bond1 made a Blender rig that is capable of allowing Blender users to create rigged characters for MAX (characters, replacing the arms, etc.). However, he discovered that the FBX import is completely broken when it comes to rigged characters. The only way to get them into MAX is to use X instead of FBX. However, that would mean rolling back to an old version of Blender (2.79 or earlier). But even that doesn't solve the issue because the X exporter for those versions of Blender causes issues that renders the rig/animations useless. Ultimately, this means that it is currently impossible for Blender users to create rigged characters and bring them into MAX due to the import issues with FBX.

Here is the thread on the GameGuru Forum for reference:

https://forum.game-guru.com/thread/223894?page=1#msg2650081

**Comment by davetgc** [comment]
@ZakJudges - I've received a number of reports that this is becoming a big issue for artists. Given how popular Blender is, it will be affecting a lot of users.

**Comment by MonkeyFrogStudio** [comment]
Turns out GLTF/GLB does not import rigged/animated characters properly into MAX, either. They work in other packages, just not in MAX (see the above forum thread for more information).

**Comment by ZakJudges** [comment]
Hi all, thanks for the info. I will look into this when I am next on bugs, hopefully Thursday/Friday

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Awesome! Thanks for this. It's pretty important, especially with how many people are pleading for a means to get their own characters into MAX. We see it asked about almost every live broadcast and it comes up both on the forums and Discord.

**Comment by ZakJudges** [comment]
Hi all, I am not too sure on the cause of this, so I am comparing an animated character that imports correctly into Max (from Mixamo), to the base male character that does not. However, I'm not familiar enough with Blender to see how these characters are set up differently. I can see there are differences, I just don't know what the differences mean. Here are both characters, imported into blender:
![Screenshot 2022-11-17 101535](https://user-images.githubusercontent.com/32545391/202422518-dc9c3ef8-07bc-48cd-8966-185d809b43b8.png)

I did notice that if I export the base male character as an FBX and then re-import it into Blender, the animation issue is also visible in Blender:

https://user-images.githubusercontent.com/32545391/202422828-711e400c-812f-4e64-8c68-94a2f3278722.mp4

BUT, opening the exported FBX with the Windows 3D model viewer gives correct results: 
![Screenshot 2022-11-17 103143](https://user-images.githubusercontent.com/32545391/202423281-8f11e09d-4843-4ac3-8cc7-52f21dd5c3f4.png)

So it looks like all the data needed for the animation is indeed there, it is just being interpreted differently to how it should be. If anybody can advise on the difference between how the two models are set up in Blender, that could give me a clue where to look on the ASSIMP side, and find the cause. Thanks.

Here are the FBX files for the base male and Mixamo characters, if anyone wants to import them into Blender themselves: 
[Animation.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10030565/Animation.zip)

**Comment by GraPhiX-Guru** [comment]
Just a FYI Assimp still has issues with FBX quite a few bugs actually https://github.com/assimp/assimp/issues?q=is%3Aissue+is%3Aopen+fbx

**Comment by bond1mjb** [comment]
I've attached the base male exported from Blender using the "better fbx" addon, and this version will re-import back into Blender ok with animation intact, and also checks out in Autodesk's FBX reviewer.   But won't import into GGMAX correctly.

![autodeskfbx](https://user-images.githubusercontent.com/87768878/202498882-0c7de104-64b5-407d-8caa-4991ee5e58a5.jpg)
![blender](https://user-images.githubusercontent.com/87768878/202498906-b264cb9b-2c53-4193-8738-69b8f5f65b18.jpg)
[blender.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10033376/blender.zip)

**Comment by bond1mjb** [comment]
Here also is a GLTF exporter from Blender that passes Khronos group validation, loads into their model viewer and Wicked Engine, but won't play animation correctly in GGMAX.
[blenderGLTF.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10033436/blenderGLTF.zip)

**Comment by bond1mjb** [comment]
Just doing more testing with the Blender FBX file exported with the "better fbx" addon.   In addition to the the apps mentioned above, it also imports into 3ds Max and Unreal Engine as well.  The GLTF from Blender looks good in Wicked too.   I'm at  loss, both the GLTF and FBX work in everyting I've tried EXCEPT for GGMAX.    

![blenderMAX](https://user-images.githubusercontent.com/87768878/202580383-794d2922-f5ac-4509-8a5c-4307cffe9239.jpg)
![Unrealblender](https://user-images.githubusercontent.com/87768878/202580391-bfda558a-d14d-4202-b9a9-5c615d76a61c.jpg)
![wicked](https://user-images.githubusercontent.com/87768878/202581349-2f303a03-2d7b-4364-b367-d16df580ca99.jpg)

**Comment by bond1mjb** [comment]
Also tried out Sketchfab with both the FBX and GLTF, looks good there too.   I'm just trying to find something other than GGMAX that also fails to help narrow down the problem.
![sktechfab](https://user-images.githubusercontent.com/87768878/202583288-42b178a4-864a-4643-959b-4121b93d0f6c.jpg)

**Comment by bond1mjb** [comment]
@ZakJudges   I imported both the Mixamo character and Blender FBX into 3ds Max to see if I could spot any differences.   I can't really see any meaningful differences.  The Mixamo FBX file also has a light and camera embedded into the file, but I doubt this would make any difference.    The bone names are obviously different, and also the mixamo character is comprised of two skinned meshes, while the GGMAX character is made up of 1 skinned mesh with four materials per the Character Creator (head,body,legs,feet)

**Comment by bond1mjb** [comment]
@ZakJudges   I found this Assimp Viewer, and the FBX imports fine here too, with animation intact!   So now it's even more weird that GGMAX won't load the animation correctly since it also uses Assimp.

![assimpviewer](https://user-images.githubusercontent.com/87768878/202594134-e622e714-575d-4188-9028-981797e2f967.jpg)

**Comment by ZakJudges** [comment]
@bond1mjb Thank you for the additional testing! I guess there must be something in the imported ASSIMP model that we are not applying/applying wrongly to the DBO. I will take another look today :)

**Comment by bond1mjb** [comment]
@ZakJudges No problem, the Blender template currently in the guides folder should be considered outdated,  I just hastily exported an FBX file from 3ds max toward the end of my CC work thinking Blender users would be able to use it.  

The Blender file at this post represents a proper Blender rig and should be the one used for testing FBX and GLTF export: [https://forum.game-guru.com/thread/223894#msg2650081](url)

**Comment by LeeBamberTGC** [comment]
AL: I have added an updatred BLEND file to the guides folder and Mark's excellent template guide for the next build. Thanks for contributing to this thread, we will keep it open to discuss the new BLEND file and guide in case more is needed to enable artists to use this path for asset creation.

**Comment by bond1mjb** [comment]
Found the problem.   Specifically for FBX, the importer does not like spaces in the bone names.   The CC skeleton is a 3ds max Biped, which by default contains spaces in the bone names.   After replacing the spaces with underscores, FBX import of the base male from Blender works fine, with animations intact.   I suppose this issue can be closed now.

**Comment by LeeBamberTGC** [comment]
@bond1mjb Can you send me an FBX that has the spaces in the bone names? I can add a check during the import process to alter the user that if they are using Blender, to ensure they are not using spaces in their bone names.

**Comment by bond1mjb** [comment]
@LeeBamberTGC  I've attached an FBX file exported from Blender that uses the default CC skeleton with a simple arms animations.   This FBX file contains spaces in the bone names, and will not import the animation into GGMAX.   But If I just replace the spaces with underscores, this same model WILL import into GGMAX correctly.
[basemale-withspaces.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10444133/basemale-withspaces.zip)

**Comment by LeeBamberTGC** [comment]
@bond1mjb Went one further and added some conversion code which allows blender imports (as FBX) to have spaces and MAX converts them just as they go into the engine, anim now works with the file you sent me :)

![image](https://user-images.githubusercontent.com/35840583/213143501-0a9456d9-dc33-442e-ba05-41a8a6a73e9d.png)

**Comment by bond1mjb** [comment]
@LeeBamberTGC Awesome,  I'm sure many will appreciate this!

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio As you are the owner of this issue, are you happy to close?
