### ISSUE TITLE
GameGuru MAX - Bug - Long Afterglow After Firing Weapon

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3488]
Fire a weapon, and there's an afterglow that hangs around for about a second after the shot:

https://user-images.githubusercontent.com/36735507/180653263-4442c448-a287-4e57-a65a-01fc799a234e.mp4

**Comment by AmenMoses** [comment]
https://vimeo.com/732925954/910e1ed8fd

I'm hearing a strange sound as well.

**Comment by MonkeyFrogStudio** [comment]
This is still present as of the 8.19 developer's release.

**Comment by MonkeyFrogStudio** [comment]
Just a reminder that this is still present in the latest experimental build (2022.9.16).

**Comment by MonkeyFrogStudio** [comment]
This appears to have been fixed.
