### ISSUE TITLE
Gameguru max not detecting the right amount of frames in my animation

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#3492]
https://user-images.githubusercontent.com/107326667/180748236-4d834b1c-9d16-43b9-a352-1759cbab4550.mp4

could someone help me out with my model and why export so little frames than the original

**Comment by RajMaha1** [comment]
it got 201 frames in fragmotion

**Comment by bond1mjb** [comment]
The importer sometimes doesn't handle X files consistently, so first convert your model to DBO, and import that instead.

1.  In your GameGuru MAX install folder you will see a folder named "Files".  Copy your exported X file from Fragmotion to this folder.
2.  Go badk to your GameGuru MAX install folder and run "Guru-Converter.exe"
3.  Back in the "Files" folder where you copied your X file, you should now have a new DBO file
4.  Noiw you can import this DBO , and all your animation frames should show up.

**Comment by Necrym59** [comment]
Convert your x file to fbx and it should come correctly

**Comment by davetgc** [comment]
Can you please say if this has fixed your issue?

**Comment by RajMaha1** [comment]
Yeah i turn off export frame rate it fixed the issue
