### ISSUE TITLE
BUG - Enemies Not following player into buildings and can attack through walls.

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3495]
At first, I thought maybe the door collision was preventing the enemies from going in but turning it off didn't fix the issue. Sometimes the enemies just run into the walls outside of the building, they never go inside, but can still attack me though the walls. I have multiple houses places throughout the level and all of them have these issues. 
https://youtu.be/pCBJTDLpcGI?t=21
https://youtu.be/3lpguN_2x9w?t=18

**Comment by MonkeyFrogStudio** [comment]
Have you tried looking at the nav mesh to see what's going on?

**Comment by Sinergygames** [comment]
I have not, good idea so I just checked it and it seems that the nav mesh cuts off on all the doorways in the house I have not made any changes to the model I don't know why this is happening or how to fix it. here is a short video showing that area with the navigation debug visuals enabled. [https://youtu.be/G-q3hxdhiv0](url)

**Comment by Sinergygames** [comment]
So, this is very weird. I tried to check the nav mesh for the house on an empty level and it appears to be fixed, so I reloaded my level and placed the house at a random spot, and it also appeared to be fixed. So, the next thing I tried is removing the houses where I'm having issues and replacing them, but the problem persists. I even tried removing every object inside the house, but it doesn't change it still cuts off at all the doorways. https://youtu.be/BLFY0YVmz8M?t=1

**Comment by MonkeyFrogStudio** [comment]
Have you tried adjusting the height of the buildings that are giving your issues? Maybe push it down just a tad? 

Not saying that MAX should be doing this, but maybe it would help. I did a test and the floor of my house (same one you were showcasing) was just a bit above the terrain and the nav mesh was broken at the doors and porch (not connected to the outside). I lowered the house just a bit and then it all connected up again and the soldier was able to come inside.

**Comment by Sinergygames** [comment]
That didn't work for me, it made no difference. I also lowered the house till the floor disappeared and added a new separate floor asset but I'm still having the same problem. I'm running out of ideas; I've been trying to fix this for a while now...
![Desktop Screenshot 2022 07 26 - 12 55 01 99](https://user-images.githubusercontent.com/103884149/181065591-bce61c5e-41c9-4dfd-a87e-006235e76acb.png)

**Comment by MonkeyFrogStudio** [comment]
At least this is well documented for the TGC team to look at. Hopefully it will get resolved soon. There is certainly something strange going on with the nav mesh, though. I have a thread here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3486

Toward the end, I found that the nav mesh was being "pushed" below my geometry by a physics object (a door). This was also causing the soldier to not be able to cross a boundary.

**Comment by LeeBamberTGC** [comment]
@Sinergygames Much better nav mesh since this report, and the door open/close logic is better without hiding critical nav mesh polygons. Also, the AI will no longer try to attack through walls as there is no line of sight, and will instead respond to sounds and follow the nav mesh route to discover the cause.  Let me know if this is better for you, or if you have a small stock level that can demonstrate any remaining issues you have with the navmesh/AI, thanks!
