### ISSUE TITLE
GGMax - Behaviors Multiple Image Selections Causes Freeze

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#3498]
In Dynamic Lua if you have more then one Image Path field and you select them in the behaviors panel, once more then one image is selected, the editor starts to lock up and only one image displays in the editor on the side panel. Eventually the editor will freeze.

**Comment by ZakJudges** [comment]
Hi @Teabone3, I could not reproduce this issue. Here is what I did:
I added the document behavior to an object, then in the script, I added an extra image file field. I then changed both images using the image library. 
Is this what you mean, or am I doing something differently to you? I did notice that the behavior panel does not allow the selection of images, so its possible that this has already been fixed. Thanks :)
![Screenshot 2023-02-10 090822](https://user-images.githubusercontent.com/32545391/218051139-71c3cfd7-1dbd-4e3e-bf3c-b84b39891de3.png)
