### ISSUE TITLE
Destoyed Objects and NavMesh

### ISSUE THREAD

**Issue by njab64** [TheGameCreators/GameGuruRepo#3499]
Is there a way of having a object with a Mesh  that a character cant walk through but once destroyed, either by script Destroy(e) or linked trigger the navmesh allows the character to find a path where the object was.  

https://youtu.be/ZquPxzVfrjg

**Comment by davetgc** [comment]
Please use Github to post bugs, and ask questions via our discord. This enables the team to focus on improving the engine.

**Comment by njab64** [comment]
So this isnt a bug then ?? I think its a pretty big flaw if the max programming cant navigate a destroyed navmesh.

**Comment by davetgc** [comment]
I'm sorry, it sounded like a question. If the model is gone, ie. destroyed, the player should be able to move through the space. I've not been able to replicate this as an issue. If you can post a  map file using default media that show this is a problem we'll be able to investigate it further.

**Comment by njab64** [comment]
[#3499.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9252262/3499.zip)
