### ISSUE TITLE
LUA - LoopSound Doesnt Move with Entities

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#35]
Bug with LUA Command LoopSound(e,v)

LoopSound does not seem to move with assigned entities. The sound loop appears to remain in the position the entity is placed in the editor but not move with a moving entity.

If its helpful, I have only been able to move entities with MoveForward and MoveBackward if collision is set to off in LUA via CollisionOff(e). Not sure if that could be whats causing the bug.

More on this topic:
https://forum.game-guru.com/thread/219269

**Comment by tarkus1971** [comment]
I noticed this a while back, and if when entity does move with playsound, if the player turns his back on the moving object the sound should change direction. It doesnt though.

**Comment by LeeBamberTGC** [comment]
Fixed for March PP, making sure the sound is WAV MONO for 3D loading, set the entity to active always so it keeps going outside of outer range deactivation and use a script which calls LoopSound constantly to update the position, and it will work:

function movewithsound_init(e)
 CollisionOff(e)
end
function movewithsound_main(e)
 MoveForward(e,300.0)
 LoopSound(e,0)
end
