### ISSUE TITLE
Combat Music Issue?

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3500]
Other than adding a music loop to the combat music section and ticking enable.
Is there anything else I should be doing?

Because at present, when I am in a fire fight, nothing happens music wise?
Is it supposed to come on automatically or am I missing something else to activate it?

**Comment by Curiosityuk** [comment]
Hello?

**Comment by davetgc** [comment]
This appears to be working for me, can anyone else confirm this as a bug?

**Comment by Curiosityuk** [comment]
It’s strange because it play’s ambience alright, but no combat music. Although at the moment it’s not even doing that because it’s constantly crashing.
