### ISSUE TITLE
GGMAX - Bug - Raising water height over player in test game then dropping it back down keeps underwater audio sound playing

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3502]
See title.

**Comment by Necrym59** [comment]
Issue Fixed
[watercontrol_v4.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9214183/watercontrol_v4.zip)

**Comment by Kravenwolf** [comment]
Hello @Necrym59! Will this be included in the next official build? Should I close this issue? :)

**Comment by Necrym59** [comment]
I have sent it to Lee so he should put it in the next build but just leave open here until they do if you can
