### ISSUE TITLE
GGMAX - Bug - Hiding HUDS in test game (Ctrl + H) cuts my frame rate in half!

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3503]
This probably isn't noticeable on the higher-end cards, but my 3GB 1060 averages around 50FPS in MAX on a newly create empty biome. Pressing Ctrl +H to hide the HUDS drops my frames down to around 20! When I press it again to unhide them, my frames jump back up to normal again (50 FPS) after a second or two.

Video below. All I'm doing is hiding the HUDS. Keep an eye on the frame rate on the top-right throughout the video. The screen recording software dropped my average **normal** frame rate into the 30-4o range, but you can still see a significant drop whenever I hide the HUDS:

https://www.youtube.com/watch?v=sEsddksi9dU&feature=youtu.be

**Comment by Kravenwolf** [comment]
I should also probably note it isn't just the frame rate display showing a low FPS because it takes a second to update like it does when you first launch GGM, etc., the frames actually are that low while the HUDS are hidden, you can feel it while walking around!

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Not repro in latext build, can you confirm with some new shots, thanks. My tests:
BEFORE:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/70bcc62e-6f7e-499f-a8e1-7df4992ecaef)
AFTER:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/334a56f9-b309-4bce-a8b4-63799e7fc198)
