### ISSUE TITLE
GGMAX - Minor Bug - Pressing shift while in the air jumping gives you a 2x speed boost!

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3504]
If you're walking, jump, then press and hold the shift key DURING your jump, your velocity in the air will double (like you just started running in the air).

Maybe disable the speed increase from sprinting if the shift key is pressed while in air?

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Maybe fixed in latext build, pressing and holding SHIFT during large jump had no effect on speed:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6608451b-85c3-4b0a-b87c-81c70060c515)
