### ISSUE TITLE
Custom models causing importer crashes.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3505]
Ggmax keeps crashing. You sneeze, it crashes. Its unstable as hell and i’m loosing my god dam mind.

I noticed some of the elements of my titanic build where wrong so went back to blender to do some edits. After a week of edits, went back to re-import the model just as I did before.

OBJ:

BOOM
Crash.

Entire pc freezes, every single one of my 4 screens turns white, the ggmax crash stops my pic.

Re-loaded. Re-imported. Nothing. No model, same one as before but when it imports, its black. Externally in 3d viewer and 3d builder, the models there, SO Go back export again.

Nothing. No model viewed in max.

Check in 3d viewer/builder again, its there. Export from 3d builder to .glf. Fine works, re-imports inton ggmax.

Imports fine. Test in game, no collisions. Fall through the air till hitting the floor. In the builder the collisions are clearly f**king working becuae it lets you place characters on the mode with no problem.

So back to blender. Export as  FBX, import into max. MAX tells me theres assimp error and refuses to import. Go back try again. Pc freezes. Need to do a hard restart. Come back. Re-export. Models now decided to face the wrong way up, despite not changing anything in blender. Model is correct in 3d/vewer go back. Try again. CRASH.

FINALly FINNALLY got a model IMPORTED!!! REJOICE….

No textures.

None

So just applied one texture. Imported. 

COLLISONS finally A WORKING MODEL!

Rejoice.

Go back to re-import (the exact SAME fracking model)

Spend 1 hour putting the textures on to the dam thing manually which is thee most mind numbing thing I’ve ever had to do in my life.

But finally!! Excitement! Joy! Finally.

IMPORT.
Play test.

NO.
FRACKING
COLLISIONS.
ITS THE SAME
FECKING MODEL. THE EXACT SAME ONE. 
NOTHING HAS CHANGED. APART FROM IVE MADE IT LOOK HOW IT WAS SUPPOSE TO BUT MAX even though its specifically suppose to read the .mtl file.

IT. doesn;t.

I give up

Recorded most of the is process, although lost a few clips because max killed my entire system.

THIS pc, although not perfect.

Can run everything between red dead redemption 2, assassins vahalla, star wars battle front 2, no mans sky WITH mods, the death stranding directors cut. Everything runs fine with this pc, ZERO CRASHES.

BUT THE SECOND I start to use max, the entire PC becomes unstable and falls apart.
Its ALWAYS always always max. 

I am this close to jumping out of the window. I am so utterly fed up with this now to a point that I’m going to just delete everything and quit.

Stability is not getting better. It is infact getting worse.

I’m gonna go head butt a wall now and go to sleep. I’m done for the time being. This whole thing is taking the piss and has broke my head.

It shouldn’t be this unstable. Its actually ridiculous. 

I started to loose count. EVERY single export AND IMPORT into max FAILED. I’M really really fed up now with this. Theres no pattern to this either, it makes zero sense in my view, i feel like it happens randomly. What’s going on.

Is this my pc?
Is this max?
Why have things gone so god dam wrong?

Heres some of the issues in this “short” video (ive actually sped up some of the footage x400)

https://youtu.be/ZLdTEBSmMRk

**Comment by leonardosedevic** [comment]
Look at my post here: https://github.com/TheGameCreators/GameGuruRepo/issues/3501
the actual version is so unstable, so buggy that is useless !

**Comment by casigus** [comment]
thanks ! ill have a look now ! :)

**Comment by casigus** [comment]
haha yeah!! literally commented on that. its unusable. really is.

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/181613254-6da09184-42c8-4d02-a0cf-a71a9ebdc8f8.png)

obj imports with no models or texture, glfs import with no collisions, fbx causes assimp error.

and then a f**king box appears.


WHY AM i the only ONE HAVING these utterly f**king stupid problems?

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/181613462-d523363e-2555-4c3c-bb0b-75bc728f4acd.png)
 
oh now its doing it with that model which worked perfectly fine importing a few minutes ago but HAD no f**king textures. sent models in to be looked at, and my email was just ignored.

im getting sick of this sh*t.

**Comment by casigus** [comment]
update. used an updated blender. fbx's are still brokem gtls have no collsions, OBJS. FINE.

https://www.youtube.com/watch?v=Sk9su3b5LoA&ab_channel=CJ

**Comment by davetgc** [comment]
Thanks for the feedback, but I'll ask again that clear titles are used. This helps others see if issues have been reported and helps the team spot bugs.

Also, many of your issues appear to be linked to custom model, can you please supply models that are causing the issues so they can be tested.

**Comment by casigus** [comment]
forgivee the random title, when your having constant crashes it gets incredibly thrustraiting  and ive supplied many many models, and nothing.
