### ISSUE TITLE
Turn off character AI whilst developing game ?

### ISSUE THREAD

**Issue by njab64** [TheGameCreators/GameGuruRepo#3506]
Might be a stupid question and probably a big ask, but....

Would it be possible to have a option in the advanced menu to switch all character AI to Idle/off. So when you are developing a map you can play the game and walk through your map checking everything is in place / zones work etc without being attacked. Bit like Westworld before they switch on the robots.

**Comment by Kravenwolf** [comment]
Requested here:
https://github.com/TheGameCreators/GameGuruRepo/issues/3243

**Comment by njab64** [comment]
Ok, great apologies for doubling up, bit slow...  should have read old issues. Glad someone had already thought of it though it's driving me nuts....

**Comment by njab64** [comment]
My work a round, if I havent missed the boat again :) is to create script with a global customvalue ie 'g_ westworld_idle'.   1 or 0  On/Off.  Attach that to a random item in the map ie a barrel.  Use  copies of the character attack and zombie attack scripts   add an 'if g_westworld_idle == 0 then' statement in the main function.

if g_westworld_idle ==  0 then
 if g_my_wander_attack[e] ~= nil and g_my_wander_attack_behavior_count > 0 then
  g_my_wander_attack_behavior_count = master_interpreter_core.masterinterpreter (g_my_wander_attack_behavior, g_my_wander_attack_behavior_count, e, g_my_wander_attack[e], g_Entity[e])
 end

**Comment by davetgc** [comment]
Duplicate, closing this one.
