### ISSUE TITLE
Max - Importer - Must Restart Max to See Model After Importing to Custom Writeable Folder 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3507]
I recently found out that when users import a model into Max using the default location of the GameGuruApps folder they can instantly see the model in their Library. But I've been using a Custom location for my GameGuruApps folder for a long time now and have always needed to restart the editor in order to see the model I had just imported, always thought this was just the way it was. 

Additionally the window that is suppose to open that lets you create the thumbnail of the model will rarely open when importing model to custom GameGuruApps folder location. If I reimport the same model, then it will always open the thumbnail creator.

**Comment by MonkeyFrogStudio** [comment]
Reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2830

**Comment by davetgc** [comment]
Duplicate, closing this one.
