### ISSUE TITLE
GG Max: Steam Offline mode not working 

### ISSUE THREAD

**Issue by mauriegit** [TheGameCreators/GameGuruRepo#3512]
Good Day

For a quite a while now, every time I attempt to access GG Max when my Steam is set to offline mode, I get a message stating "You must be signed  in to your Steam account to access GG Max"", and can't login, although I am already signed in to Steam on offline mode?

Other games on my Steam Library work fine in offline mode and GG Max also did initially. I do not always have internet access available and it is frustrating if I can't access the software.

Please assist.
Kind Regards
Bassfisherman12

**Comment by MonkeyFrogStudio** [comment]
Reported here already:

https://github.com/TheGameCreators/GameGuruRepo/issues/3349

**Comment by mauriegit** [comment]
Thank you.

Please let me know when we can expect this issue to be resolved.

Kind regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by davetgc** [comment]
There will be a grace period added to allow MAX to be used for short periods offline, however, Steam access will be required occasionally.

**Comment by mauriegit** [comment]
Thank you.
Kind regards


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
