### ISSUE TITLE
frame rate issue in editor compared to test game

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#3513]
simple test level, 6 mesh (each under 2k polys) 8 point lights and 1 spotlight, 2 particle emitters.

In the editor, im struggling to get over 5FPs, meaning its incredibly difficult to build any more to the level, travelling around the assets is very slow.
![image](https://user-images.githubusercontent.com/82544140/181640259-126bbf25-dbf0-45c8-bfda-033c14872614.png)

However, once in the testgame, the frame rate shoots up to 90-100fps.
![image](https://user-images.githubusercontent.com/82544140/181640387-1ace4fdc-737b-43a8-bf20-bb8b18beedcc.png)

Ive removed and added back, each asset individually without any noticeable effect.

**Comment by davetgc** [comment]
Please post your system specs and if possible provide a video.

Thanks,

**Comment by mav3r1ck198-1** [comment]
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
32 GB CORSAIR DDR4 RAM
GeForce RTX 3060 Laptop GPU

**Comment by mav3r1ck198-1** [comment]
ill try and get a video in the morning

**Comment by mav3r1ck198-1** [comment]
https://youtu.be/Vyp7mMEH0xc

**Comment by mav3r1ck198-1** [comment]
Interesting. when turning off VSYNC, all of these issues disappear for the editor

**Comment by LeeBamberTGC** [comment]
@mav3r1ck198-1 Did you turn VSYNC off in the SETUP.INI to get the editor back to full speed?

**Comment by mav3r1ck198-1** [comment]
Hi @LeeBamberTGC no, i did it in the TAB TAB menu during test game. If that hadnt worked, i would have done into the setup.ini however.

**Comment by LeeBamberTGC** [comment]
@mav3r1ck198-1 Before we opt for the hack, can you activate the stats in the editor to find out which element is slowing your system down in the editor, Might be an idea to find the true culpret:

![image](https://user-images.githubusercontent.com/35840583/183892857-82eb515f-4d2e-412d-8d25-2d5e23ae048b.png)

**Comment by mav3r1ck198-1** [comment]
![image](https://user-images.githubusercontent.com/82544140/183904362-ab40844b-5622-44da-8cb4-f7aff017afa0.png)


Ironically, when ive opened the editor now, its working fine, last night i was down to 0.9fps

**Comment by LeeBamberTGC** [comment]
Schrödinger's cat again :)

**Comment by LeeBamberTGC** [comment]
@mav3r1ck198-1 If it happens again, quickly jump into the above stats and make a snapshot, it could be a good clue.  If nothing more happens, it may have been a non MAX related system issue. If it does, and you cannot get a grab of the stats in a week, post again here and we will do the hack (i.e. VSYNC off when in editor mode) :)

**Comment by mav3r1ck198-1** [comment]
![image](https://user-images.githubusercontent.com/82544140/186259906-be4b7868-2f12-4305-a21c-4756f25cd441.png)


This is with VSYNC off in the setup.ini file

**Comment by mav3r1ck198-1** [comment]
![image](https://user-images.githubusercontent.com/82544140/186260261-eb737553-288f-49fa-83f1-6baf9607a6cd.png)

**Comment by LeeBamberTGC** [comment]
@mav3r1ck198-1 I would need to see the whole stats as the millisecond figures which I need are further down.  CPU looks fine, so I suspect GPU is a big hitter.  Send all the GPU stats when this happens and we can see who is responsible :)
