### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3514]
I can't find a hurt zone? Does GGM have one? If not, has this been replaced with something else?

**Comment by MonkeyFrogStudio** [comment]
Firstly, GitHub is for reporting bugs and making feature requests. It's not for seeking help. To get help either use the GameGuru forum or their Discord channel. There's usually someone there on Discord to lend a helping hand.

Secondly, all you have to do is set up a Trigger Zone. Then, with the zone selected, go to Behavior on the right-side. Click the default Plrinzone behavior to select another one. From the pop-up that appears, look for HURT. Use the Behavior to cause your zone to hurt the player when they are in it.

**Comment by Curiosityuk** [comment]
The thing was, I didn't know if it was a bug or not?. Or whether it was a something that was over looked.

But cheers for the info, I'll give it a try.

**Comment by Curiosityuk** [comment]
Dave
            How can you close the job when I still have the issue? 
I  understand it might not happen to you, but It does to me so maybe if I send a video over it might help?
