### ISSUE TITLE
GG Max - Bug - Standalone not saving User Particles but saving other particles in to Standalone folder

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3515]
As the title says, When creating a Standalone game, The USER particles are not saving over to the Standalone folder.
But in the particlebank folder in the Standalone folder, there is a load of particles that am not even using in the game.

**Comment by Tum1370** [comment]
After checking a different bug regarding creating Standalones has been fixed, I also checked this bug.

I can confirm that CREATE STANDALONE still does NOT copy over the PARTICLES to the Standalone folder.
It also STILL copies loads of particles that the Standalone DOES NOT USE.

**Comment by ZakJudges** [comment]
Hi @Tum1370, apologies for the late response and thank you for reporting this issue.  

A new EXP should be up in 5 mins with a fix for this. Note: for now, the entire particlebank/user folder will be copied across - there is another bug getting in the way of only including particles that are actually used in the level. I will create another fix for that when I get round to #2301 - the same goes for the default particles that get included automatically :)
