### ISSUE TITLE
AMD RX 6800 problem?

### ISSUE THREAD

**Issue by NekronNex2** [TheGameCreators/GameGuruRepo#3518]
hello. i have the following problem. when i start the game guru Max i only have a black screen in the middle. i don't see any terrain or caracter. i only see black.

i previously had a system with amd cpu and nvidia rtx 2070. here i had no problems. then my nvidia broke and i got a new system with Intel I7 and AMD RX 6800.since then i have a black screen in the middle. reinstalling did nothing.

greetings

**Comment by earthling45** [comment]
Hi @NekronNex2 see this thread https://github.com/TheGameCreators/GameGuruRepo/issues/3444

**Comment by davetgc** [comment]
This is most likely related to the latest drivers and has been reported before. Please try rolling back your GPU driver and let us know if that helps.

**Comment by NekronNex2** [comment]
Can only confirm that it is because of the drivers. with the version 22.5.1 everything works fine.
