### ISSUE TITLE
Object selection problem in editor.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3522]
![image](https://user-images.githubusercontent.com/68471279/181996578-355345bb-052b-48b1-9327-3fddc45309d4.png)
 any one ever have this where theres a object placed down, and NO matter how many times you click it, MAX is like NOPE.

JUST refuses to click the dam thing when you want to move it.

also my idea here was to fill up the no collisions with a object then make it invisible as my version of max and PC can't ever import objects with the correct collisions. which is actually getting to a point where I want to scream, delete the entire project and give up. yes. I know. its in early access, but things just seam to be getting worse and worse with every single update we get.

also swimming feels...off. wrong. I can't place it. It felt great before, but now it just doesn't feel right, its sinking you straight away, having to keep hold of several keys too just stay above water? lots and lots and lots of random buggy things too, including max using 32 gigs of memory which its utterly redicolous. 

ANYWAY. I'm gonan go stick my head into a bucket of ice.

have a good weekend folks!

**Comment by davetgc** [comment]
This could well be related to the object. Are you able to supply them so they can be tested?

Also, can you please use clear titles for issues,

**Comment by mav3r1ck198-1** [comment]
have you tried holding shift and poly grabbing the object? I have the same issue when trying to pick up previously deployed particle emitters, using the shift key works as a workaround

**Comment by casigus** [comment]
yeah!!! had this happen a few times with random objects! no joy!
