### ISSUE TITLE
Marketplace Get More Objects Bug

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3525]
Hi There has anyone had problems with the Marketplace. Every time I click on Marketplace GGmax crashes without any warning and goes back to windows desktop. I have even tried re-installing GGmax and still no joy. I have also noticed when I go to get more objects it does the same thing just closing GGmax and goes back to windows desktop.

THX
Tam51

**Comment by MonkeyFrogStudio** [comment]
Can confirm. It's happening on my install as well.

**Comment by Lemuripest93** [comment]
I just tested this and can also confirm that this is happening.

**Comment by davetgc** [comment]
This seems to be working now. Please let us know if it's not working for you.

**Comment by Tam51** [comment]
Hi davetgc it still doesn't work on my copy of GGmax. It just closes GGmax on Marketplace and Get More Objects

**Comment by MonkeyFrogStudio** [comment]
Works on my end.
