### ISSUE TITLE
Error 7006  0

### ISSUE THREAD

**Issue by RobDaHob** [TheGameCreators/GameGuruRepo#3526]
Did a big map in the mountains
But after I put in the "skull gate" 
it comes with this error and ends. 7006 and a zero.
Dident help to remove the skull gate.
Know it says same error no reason what me do..
Any clues??
Love 
Rob

**Comment by Hamada880** [comment]
I have had the same issue, if you install the Aztec pack and GGMax in two different directories.

**Comment by RobDaHob** [comment]
Solved it. I just moved the start position closere to the end. Then I could move it back. No clue why it happend. Had not change the first start position. But whatever - case closed.
