### ISSUE TITLE
Imported models invisible.

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#3527]
Since the last build my models are showing up when imported but when I return they are invisible. On import, it had no issues and displayed just fine. 

![image](https://user-images.githubusercontent.com/95527550/182052213-3df5ac5c-5d73-4b93-948d-9c67767f7f14.png)

**Comment by synchromesh62** [comment]
Is the Transparent box supposed to be ticked ?

**Comment by MonkeyFrogStudio** [comment]
Can't get that to happen on my end. I tried a few of my models, imported them, saved the level, exited MAX, re-opened MAX and the level, and the models were there. Ran a test level and the models where there. I'm running the latest build.

**Comment by 42Pix3ls** [comment]
Sorry, I should have mentioned that it is a sprite sheet

**Comment by 42Pix3ls** [comment]
> 

That was just me clicking every option desperately trying to get it to appear

**Comment by davetgc** [comment]
Check that cast shadow and transparent settings are both off. It this still continues can you please post a video?
