### ISSUE TITLE
Bug! Copy and paste removed objects normals, Surface and sometimes emission maps.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3529]
Upon testing and creating level. I found a bug where copying and pasting the same asset removes added maps such normals and surface.

**Comment by MonkeyFrogStudio** [comment]
I've tried to duplicate that here and it's not happening for me. I tried it two different ways - 1) with a model that I had brought into MAX (copy, paste, no issue) and 2) with a model that I brought into MAX and changed it's textures after bringing it into my scene. After copy/paste, the object pastes with the changed maps (normals, surface, etc.). 

Are there any specific steps I should follow to see this happening?

**Comment by Hamada880** [comment]
I tried the floor plan and copy it a few times as soon as I moved it to align it with other planes.it losses the normal and surface map,just the diffuse map stays on. Try to move the copied part and see if it changes the properties.

**Comment by davetgc** [comment]
I can't replicate this either. Please can you post a video or a step by step,

**Comment by Hamada880** [comment]
Yes,I will try to make video of it and post it.

**Comment by Hamada880** [comment]
I also have found #3536 similar issue after copy and paste and it might be related to same bug I have.

**Comment by plemsoft** [comment]
@Hamada880 Thanks for reporting this issue , this has been fixed and will be in the next update :)
