### ISSUE TITLE
The Lighting of Gameguru 

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#353]
A new user wrote this thread and in my opinion it is one of the most important subjects.
https://forum.game-guru.com/thread/220000?page=1#msg2604855

Gameguru needs:
- Dynamic Lights casting real time shadows
- a WORKING Lightmapper
- Particles

**Comment by Teabone3** [comment]
particles would be a whole other topic unrelated to lighting :D
