### ISSUE TITLE
GG Max - Bug - Latest Experimental Build - Clicking GET MORE OBJECTS shuts down Max

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3533]
As the title says, If you click GET MORE OBJECTS from the object library in the latest Experimental version, Max just closes.

**Comment by Tam51** [comment]
Does the same when you go to Marketplace which I have already mentioned. Marketplace crash #3525

**Comment by davetgc** [comment]
This was working when tested today. I'll close this for now,  but it you can demonstrate it happening we can look into it.
