### ISSUE TITLE
Were can I post maps now when in early mood?

### ISSUE THREAD

**Issue by RobDaHob** [TheGameCreators/GameGuruRepo#3535]
Were can I post maps now when in early mood?
Love 
Rob

**Comment by MonkeyFrogStudio** [comment]
You already asked about something like this here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3532

GitHub is not about asking these sorts of questions. Ask them on the Discord channel or the forum. GitHub is for posting bug reports and requesting feature additions to the program.

**Comment by davetgc** [comment]
Please use our discord for this kind of question.

Many thanks,
