### ISSUE TITLE
Character Creator, Baseball Cap Hair Issue 

### ISSUE THREAD

**Issue by Technodweeb** [TheGameCreators/GameGuruRepo#3538]
When you create a female  or male character then change to the baseball hat it  changes to to the default hairstyle, even if you chose a different hair style. Men its short brown hair and women is short blonde hair.

Also It would be great if both male and female could share hats and regular t-shirts for women instead of tank tops.. come on guys..

**Comment by ZakJudges** [comment]
Hi @Technodweeb, apologies for the late response. 
Note that when hats etc are added to the character, the hair styles are automatically swapped out to the "Caesar" and "Pixie" styles for the male and female characters respectively. This is to ensure that the hair for the characters does not show through the hats.

Re having male and female characters having the same hats/shirts/etc, I agree. It is something we would like to see improved, once we reach a v1 release :)

I will mark this issue as an enhancement, to keep it here for reference

**Comment by Technodweeb** [comment]
thanks
