### ISSUE TITLE
Visual Issue - Building Pack

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#354]
Some of the buildings , when viewed from the direction of the sun, have what appears to be normal maps or something of the sort displaying incorrectly.

![building](https://user-images.githubusercontent.com/35990109/44689755-93cd8900-aa26-11e8-83d3-3323aeaa83bb.JPG)

**Comment by Teabone3** [comment]
I believe it was mentioned this might have been fixed. Can someone confirm?

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
This issue was fixed in a later update ..
