### ISSUE TITLE
Custom Script NPC's always have weapon.

### ISSUE THREAD

**Issue by oliamit12** [TheGameCreators/GameGuruRepo#3544]
The option in the sidebar to assign weapons (or not) to an npc has gone.I am using scripts from 3rd parties and the characters always turn up with a weapon. Can this option be re-instated for custom/3rd party scripts as I can't code. Thanks.

**Comment by davetgc** [comment]
The option is there using the default character attack script. This is very likely being caused by the custom script. You will need to contact the 3rd party with your concerns.

Thanks,
