### ISSUE TITLE
Adding Animation via Character Creator causes error.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3545]
![image](https://user-images.githubusercontent.com/99803873/182613765-513a894d-4ba0-448a-b3dc-b1328f4bdbf9.png)

Adding a new animation from the animation booster pack via the character creator causes this error on completion.

**Comment by LeeBamberTGC** [comment]
@davetgc Seems to work fine in the latest build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b4520857-0336-4e8e-9f7f-102857a0eb90)
