### ISSUE TITLE
Adding animations via character creator doesn't make them available.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3546]
Adding a new animation set via the character creator doesn't make that animation available as part of the drop down, only the default animations show. This is not expected behavior.

**Comment by LeeBamberTGC** [comment]
@davetgc Seems to work now. Created stock character and assigned the RIFLE animation set:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5717e18d-6601-47cf-b306-df667a5631fb)

Then dropped into the level and assigned PLAY ANIMATION script and set all anims to the idle_aim. Set the character to use the DEFAULT ANIMATION (from the model, not from the weapon):
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0c9887f7-c6ae-480c-96b5-2df76cde979a)

Ran TEST LEVEL and the correct animation is being used:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/02d73bce-dc33-4b9d-b2fd-c70a73db5441)
