### ISSUE TITLE
Marketplace and Get More Objects Bug still not working

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3552]
https://user-images.githubusercontent.com/93008801/182699269-11896d70-1fa1-473f-8330-793dc2e238b9.mp4

https://user-images.githubusercontent.com/93008801/182699275-faeb4169-da39-422a-ab01-83e9cbaa3d0a.mp4

Hi Lee I posted this before about the Marketplace and Get More Objects not working GGmax just closes down as you can see from the videos. Will this be fixed as davetgc said it should be working but it's not working. I have tried re-installing GGmax and I still get the same problem. This is a non steam version 

Many Thanks
Tam51

**Comment by Tum1370** [comment]
@Tam51 This is fixed, but the fix wont be available until the update goes live. I think the update goes live on this Friday.

**Comment by Tam51** [comment]
Moved to steam version. So I'm closing case
