### ISSUE TITLE
teleport script

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3559]
![image](https://user-images.githubusercontent.com/68471279/183219696-67ed1bc4-ef18-4129-8d2e-2d9cb107aa8a.png)

I set the teleport script to teleport the player as per usual, however when I save the map or click on the trigger it deletes the set target for the teleport.

**Comment by ZakJudges** [comment]
Hi @casigus, are you still experiencing this in the latest build? Thanks :)

**Comment by casigus** [comment]
i'll need to check that one !

**Comment by ZakJudges** [comment]
Hi @casigus I will close this issue. If you experience it again, feel free to re-open or email me at zak@thegamecreators.com

Thanks :)
