### ISSUE TITLE
Random closing down crash

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3563]
Hi There is anyone experiencing random crashes while importing new objects in GGmax. It works for a while but sometimes it just closes. I hope this Bug will be fixed soon. Very strange as it didn't do this before the new update.

**Comment by MonkeyFrogStudio** [comment]
Reported here:
https://github.com/TheGameCreators/GameGuruRepo/issues/3556

It would be helpful if you added your comment there as well as your system specs.

**Comment by Tam51** [comment]
I have reported to #3556 with specs
