### ISSUE TITLE
shake script not working properly

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#3564]
![Screenshot 2022-08-06 122748](https://user-images.githubusercontent.com/107326667/183246960-aa120921-cc63-4846-bf89-cddfd3bfd0d8.png)

https://user-images.githubusercontent.com/107326667/183247059-a7cb04f6-5152-4cb8-b73e-1cc2fbdab85b.mp4

**Comment by synchromesh62** [comment]
Not really showing a lot and you do not say what the problem is ?
So have you connected it to a dynamic asset and then linked it to a trigger zone as described in the info?
Just tested and working great my end

**Comment by RajMaha1** [comment]
Thank You

**Comment by synchromesh62** [comment]
Add a sound effect the the zone and its excellent :)
