### ISSUE TITLE
MAX - Standing near a pointlight bathes the entire world in it's color

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#3565]
In MAX, standing near a pointlight will bathe the entire world in the color of the light, which makes it completely impossible to make a dark level with ANY light sources other than the player's flashlight. Since if you stand near the light source, it will completely illuminate the entire world and thus the dark areas, completely ruining the atmosphere and visuals. (This also creates a weird "lighting warbling" effect as you run past numerous lights, which makes it feel like your character is on drugs.)

I think this may be caused by the environment probe that follows the player around(?) If you're particularly unlucky, when this probe updates and takes a "snapshot" of the nearby lights as you're firing your weapon, it can bathe the entire world with the muzzleflash light for a couple of seconds which is extremely annoying.

In my humble opinion, as this completely ruins the project I'm trying to make, and will ruin anyone else that relies on lighting (ahem, as there's a lighting competition going on!!!) I think this bug should be quite high priority. :)

[https://streamable.com/4l17ea](https://streamable.com/4l17ea)

**Comment by fearlesswee** [comment]
I definitely recall something being mentioned about a environment probe that follows/updates with the player, but beyond that I don't really know how it works under-the-hood.

Could it be maybe the probe is too large, so it's applying the light's influence to the entire world instead of just the area around it? Or is it the opposite and the probe is too small, so it thinks the light takes up a way larger percentage of the world than it really does? 

I just hope this is easy to fix, and doesn't get marked "enhancement" and then ignored (like every other enhancement it seems...) because it's integral to the kind of project I'm working on that this is addressed.

**Comment by MonkeyFrogStudio** [comment]
What you do is set up your levels Ambient Color (under Environmental Effects, under the Customize Sky tab). Use a fairly dark gray or blue-gray, etc., so that it barely illuminates your interior. This is the first step toward setting up lighting for your level and should be the basis for the darkest areas you want viewable.

After that, you can adjust area lighting in places by using a spotlight. Set it's Spotlight Radius to something large, set a large enough Light Distance to bathe the area you want in this light. Set it's Light Color to something dark (though lighter than your Ambient Color (see above)), like a gray or blue-gray, etc. 

Lastly, use point lights to further enhance areas.

Barely any ambient and dark gray for spot light:
![light](https://user-images.githubusercontent.com/36735507/183251687-5d13d6a4-e09c-4651-b15c-37ea5b8813be.png)

A bit brighter ambient and a bit lighter for the spot light:
![light2](https://user-images.githubusercontent.com/36735507/183251732-dc26e81e-b5f4-4a17-8b74-74ee641c402c.png)

**Comment by fearlesswee** [comment]
I've already changed the level's ambient/lighting to pitch black. (That's the first thing you do to make a dark level after all lol) I also specifically don't want ambient lighting everywhere, I want to be able to have dark areas that have _no_ lighting until the player comes by with a flashlight! Doing a hacky "light with large radius and very low/dark color to try and override the environment probe" trick kinda mitigates the glow just a tiny bit, but it still definitely and obviously occurs, and washes out any dark areas and generally ruins the kind of atmosphere I'm going for. :(

The issue is fundamentally a bug with how lights are handled engine-wise. Standing near a point light will light the entire world with it's glow, which makes it impossible to have dark areas where the player cannot see without the flashlight, since the pointlight's influence will essentially give the player "night vision" as long as they stand near it. It ruins tension/atmosphere when every nook and cranny is highlighted so plainly, not to mention feels jarring as all heck.

Plus this bug can happen with the muzzle flash too, if you get particularly unlucky and fire right as the environment probe takes a "snapshot" of the nearby lighting. So you could be in a dark room, fire a shot at an enemy, and suddenly the whole world is glowing yellow for a couple of seconds giving you that "night vision" effect.

**Comment by MonkeyFrogStudio** [comment]
> Doing a hacky "light with large radius and very low/dark color to try and override the environment probe" trick ...

You do realize that just about everything done in a game is a hack and a trick, right? ;)

> Standing near a point light will light the entire world with it's glow

Doesn't for me:
![light3](https://user-images.githubusercontent.com/36735507/183254170-62a15fe4-e2ed-44ea-b9cc-4c8e86aba245.png)

You just have to control the light via it's color.

**Comment by fearlesswee** [comment]
As a quick test, here's the level without the moody dark blue fog, completely pitch black
![image](https://user-images.githubusercontent.com/56294129/183254201-6679552d-d33f-46bb-9ea3-529492b7d9a0.png)
Logically the scene should remain pitch black in areas that have no lights. But if I move the camera close to the point light...
![image](https://user-images.githubusercontent.com/56294129/183254212-55d01135-6d77-49f3-b4fd-26a7936761fe.png)
Everything lights up. There isn't really a way around this, if I want to have specifically dark areas to build tension/atmosphere. I specifically don't want to have to light my entire level like the 4th of july just to get around a bug.

**Comment by MonkeyFrogStudio** [comment]
That's not happening on my end. At least not yet. Not sure why it's happening to you, to be frank.

**Comment by fearlesswee** [comment]
> > Doing a hacky "light with large radius and very low/dark color to try and override the environment probe" trick ...
> You do realize that just about everything done in a game is a hack and a trick, right? ;)
Oh I know, I was just specifically saying the hack _doesn't work_ lol

**Comment by MonkeyFrogStudio** [comment]
> Oh I know, I was just specifically saying the hack doesn't work lol

But it is working on my end. I can make a level as dark as I want, use point lights or spotlights where I like, and they only light the area where they are within the distance I set. Going into the light does not light up the entire room, only the area where the light is.

Here's a video of my test level with ambient turned to black and a pure white point light in the center of the room. I walk into and out of the light and only the area of the light is effected, not the entire room:

https://user-images.githubusercontent.com/36735507/183254707-69e8326d-147d-413c-8b3f-62b229fe615b.mp4

**Comment by fearlesswee** [comment]
I've done some more testing, it seems the light's distance has a big factor on how strongly it lights the environment when this bug occurs. A point light at the default 100 distance lights the surrounding environment only a bit, but increasing it to 200 makes the entire world lit almost like sunlight.

Created a new empty level, placed down 3 corridors, and some pointlights. The first one has a light distance of 200, the second one is default 100. The 200 distance one essentially activates the sun, but the 100 one you can see only weakly lights the ceiling a touch. It's hard to tell in your video due to the compression, but I think you can see a similar effect of the door frame being weakly highlighted as you walk into the light. Try setting the light in your test to have a larger distance and see if the bug occurs more noticeably? 

[https://streamable.com/u2zpni](https://streamable.com/u2zpni)

**Comment by MonkeyFrogStudio** [comment]
Seems like a light probe issue (as you suspected), but I am still not getting this in my levels. Here's a light at 200, pure white:

![light4](https://user-images.githubusercontent.com/36735507/183257274-486d85c6-da80-4b1f-9671-9454afda0e0d.png)

And the same light at 200, but made less than pure white to control it better:

![light5](https://user-images.githubusercontent.com/36735507/183257286-17931921-5fb8-4ad8-8e8f-94d459714c72.png)

**Comment by fearlesswee** [comment]
Here's a really strange oddity, here's 2 pointlights, both with a range of 200, but one is alone on the terrain, one is in a house. Standing near the one out on the terrain does cause the bug but only a little bit, going to the one near the house causes the bug BIG time, and I only noticed this after reviewing the footage but there appears to be some kind of shadowing bug with the other point light, it looks like it's casting the same shadows of the house that the current light is casting???

What the heck is going on here...?

I'm getting a hunch it might be down to duplicating lights...? I wonder if I tediously hand-place each light it'd solve it? But that wouldn't explain why it can also happen with the muzzleflash light though... gah! Why does MAX have to be so freakin' buggy lol

[https://streamable.com/67e6v0](https://streamable.com/67e6v0)

**Comment by fearlesswee** [comment]
Regardless, I'm just sick of messing with this bug now as it's clearly entirely out of my control, so I'll wait for Lee/TGC to weigh in.

**Comment by MonkeyFrogStudio** [comment]
One thing to try - Untick Autoexposure:

![autoexpose](https://user-images.githubusercontent.com/36735507/183258174-45b7baae-2d56-4ac7-825e-f8c2763ab80c.png)

If that's ticked, that would explain what's going on when you enter a light like that.

**Comment by fearlesswee** [comment]
Autoexposure is already off, since it brightens the screen so much when in dark areas so much to the point that lights are painful to look at. Infact, ALL post-processing is off in that level except for FXAA, SSR, and reflections. And before you suggest it, turning those off have no effect.

(By the way, I know what the auto exposure tick box looks like, I don't need a giant red arrow to point it out lol)

**Comment by MonkeyFrogStudio** [comment]
Not claiming you're a newbie at all. Just trying to help, if possible. But I would have no way of knowing for certain that you knew where that tick box was, so I just made a screen shot just in case. There are others who've been using MAX as long as you and I have, that don't know these things. So, this was not trying to be insulting, but just checking all boxes just in case.

**Comment by davetgc** [comment]
@fearlesswee  - Thanks for the report, I can't replicate this either. Could you please post your system specs as I'm starting to suspect a GFX card issue or a driver issue.

**Comment by fearlesswee** [comment]
@davetgc 

SYSTEM SPECS:
CPU: Ryzen 3600 6-core processor
GPU: NVIDIA GeForce GTX 1660 SUPER
Storage: 512GB SSD
RAM: 8 GB (plus 6 GB virtual memory)

By no means top-of-the-line, but certainly no slouch. I'm not getting any performance issues either, my level runs at 144 fps no issue. I'll try running MAX on integrated graphics to see if we can nail it down to being the GPU(?)

**Comment by fearlesswee** [comment]
I can say with near 100% certainty it has something to do with the environment probe, as when I was testing this issue in-editor a while ago I noticed that a nearby glass surface was reflecting the start marker as the level was glowing red from a nearby light, and when I moved my camera enough to update the probe the reflection of the start marker disappeared precisely alongside the glow.

**Comment by fearlesswee** [comment]
Took a while to get back to this, but with a fresh install of MAX on a laptop with a GTX 1050 running on latest drivers and latest version of MAX this issue does not occur, however on the original system with latest drivers and update it still occurs. 

So, the issue does seem to be specific to the GPU, I hope this can help this get tracked down and fixed.

**Comment by fearlesswee** [comment]
Waiting patiently for any updates/news on this bug, as it still occurs in the latest build and makes it impossible to make dark/moody levels. I have an entirely new machine with an RTX 3050 card, and this bug still occurs, which now means on 3 separate machines, on numerous separate levels, this bug has occurred. It's currently a huge thorn in my side and prevents me from progressing through with my game idea, as it absolutely kills any kind of moody lighting and actually causes nausea with the world constantly changing colors as you run through it.

**Comment by fearlesswee** [comment]
[https://streamable.com/wve9yq](url)

I've tried numerous things, turning off every single post-processing effect, turning off reflections, etc. (the bug is also clearly not auto-exposure, as not only is said feature ticked off, but you can see the "glow" isn't just the screen becoming brighter, but rather the entire world being lit by the color of the pointlight; a red light makes the world glow red, a green light makes the world glow green, etc.)

And with the fact this bug happens independently across 3 different systems, one with AMD hardware, and 2 with NVidia hardware, it can be safely ruled out as anything regarding a specific install or machine issues. It's an engine-level bug and it's been a nonstop bother for me trying to make a moody/dark level.

**Comment by davetgc** [comment]
I still can't replicate this issue, but I've assigned it to be investigated further. Hopefully, we'll get to the bottom of it.

**Comment by fearlesswee** [comment]
It completely baffles me why it seems like I'm the only one cursed with this awful bug. 3 separate machines, 3 separate installs, 3 separate GPU manufacturers tested. Same bug everytime. But somehow for everyone else? Magically doesn't occur for them, defying logic entirely. 

I can say with 100% certainty at this point it's caused by the auto-updating environment probe that follows the player around. My hunch as to "how" is that the probe seems to be way too small, to the point where when the camera is near a pointlight the environment probe samples the area around the camera, which is entirely filled by the light's influence, and then assumes the entire scene is lit by that light, and basically "extends" that light's influence to the entire scene/world. I can definitely recall back when there was no automatic probe, and you could make your own environment probes placed around the map by placing a light, turning down the light radius, and turning up the probe radius, this bug did NOT occur. 

Perhaps _at least_ as a sort of "bandaid" fix for now, you could look into adding a developer option to tweak this automatic environment probe; to alter the scale, or to even just disable it entirely? At this point this extremely annoying bug is holding up progress on my game idea completely, as it's not only extremely mood-killing, but actually makes it physically nauseating to play. 

I'm praying that this can finally, _finally_, **finally** get sorted so I can move ahead with my game idea after months of waiting, but if it just remains as an "unreplicatable" bug (which, given it happens to me 100% of the time with no kind of "special setup" required, on 3 separate machines, with 3 separate installs, and on all 3 GPU manufacturers; Nvidia, Intel integrated, and AMD, it completely baffles me why it can't be replicated) I might just have to give up on MAX for now. And as an enthusiastic backer who bought into MAX way back before Wicked Engine was even considered, and MAX was basically Classic with a better UI, I don't say that lightly :(

**Comment by synchromesh62** [comment]
> It completely baffles me why it seems like I'm the only one cursed with this awful bug. 3 separate machines, 3 separate installs, 3 separate GPU manufacturers tested. Same bug everytime. But somehow for everyone else? Magically doesn't occur for them, defying logic entirely.
> 
> I can say with 100% certainty at this point it's caused by the auto-updating environment probe that follows the player around. My hunch as to "how" is that the probe seems to be way too small, to the point where when the camera is near a pointlight the environment probe samples the area around the camera, which is entirely filled by the light's influence, and then assumes the entire scene is lit by that light, and basically "extends" that light's influence to the entire scene/world. I can definitely recall back when there was no automatic probe, and you could make your own environment probes placed around the map by placing a light, turning down the light radius, and turning up the probe radius, this bug did NOT occur.
> 
> Perhaps _at least_ as a sort of "bandaid" fix for now, you could look into adding a developer option to tweak this automatic environment probe; to alter the scale, or to even just disable it entirely? At this point this extremely annoying bug is holding up progress on my game idea completely, as it's not only extremely mood-killing, but actually makes it physically nauseating to play.
> 
> I'm praying that this can finally, _finally_, **finally** get sorted so I can move ahead with my game idea after months of waiting, but if it just remains as an "unreplicatable" bug (which, given it happens to me 100% of the time with no kind of "special setup" required, on 3 separate machines, with 3 separate installs, and on all 3 GPU manufacturers; Nvidia, Intel integrated, and AMD, it completely baffles me why it can't be replicated) I might just have to give up on MAX for now. And as an enthusiastic backer who bought into MAX way back before Wicked Engine was even considered, and MAX was basically Classic with a better UI, I don't say that lightly :(

If your getting it with 3 different GPU's then that really only leaves the model itself in question perhaps as that is the only common thing i see in all your pics ?
I did a quick test using my own and seems to be fine ?
https://youtu.be/4eUQqgyVSzI

**Comment by fearlesswee** [comment]
[https://streamable.com/67e6v0](url) 

Sadly no, if you check the test I did here a while ago it happens with stock media as well.

**Comment by fearlesswee** [comment]
Update: Funnily enough, the current SSAO bug that causes AO power to just darken shadowed areas rather than increase the AO "range" actually seems to somewhat counteract the bug when cranked up to max by just overpowering the shadowed areas of the scene so much that the color bleed can't be seen.

**Comment by fearlesswee** [comment]
>Can you tell me any particular Stock media you mentioned that gives the same problem.

Any stock media, including the terrain itself. If you want to ensure it's a 1:1 comparison, then try an "empty" biome with the stock "1 story house" from the building collection I used in my test.

[https://streamable.com/67e6v0](https://streamable.com/67e6v0)

**Comment by fearlesswee** [comment]
AHA! I knew it! I'm not the only one getting this, and it has nothing to do with the media I'm using. It's absolutely 100% an engine-level bug with the lighting system/environment probe.

#4214

**Comment by Kravenwolf** [comment]
May be an issue with physically-based rendering. Doesn't look like it's being updated in real-time, so the lighting conditions the player was under a second or two ago may be getting applied to any and all PBR surfaces in their current position. More apparent when the camera is moved very quickly:

https://www.youtube.com/watch?v=2axvJL4pPhA

**Comment by Kravenwolf** [comment]
**UPDATE:** 
Ticking "Planar Reflections" on affected objects seems to make the issue go away on my end, but they look expensive.

**Video Here:**
https://youtu.be/Iy3tfGxop8E

This does present quite a bit of an issue as far as "presentation" goes for indoor environments in particular, @davetgc :)

**Comment by MonkeyFrogStudio** [comment]
I could well be wrong, but I don't think the issue is with PBR per se. I think the issue is with the light probe. MAX only has one light probe and it's attached to the player. After the player travels a certain distance (and it's not very big), the light probe updates and you see this issue. You can see the same thing happening with reflections in things like windows and other reflective surfaces, even outside. 

Most game engines allow the developer to place light probes where they're needed, so you wouldn't see this sort of shift or popping of light and reflections. But not MAX. I had brought up an issue about this quite some time ago here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2246

Apparently it was a limitation of the Wicked Engine at the time? I wonder if the latest Wicked is still like this and if we will benefit once (if?) MAX gets updated to DX12 and the latest Wicked.

**Comment by Kravenwolf** [comment]
It looks like in your original thread Paul did say it's on the "to do list", which is fantastic news if that's still the case;

_"I think there does need to be a manual light probe system for those users that want to use it, but it would be a big change so we'll have to look at it after the initial release"_

Hopefully as more artists keep acknowledging it as an issue it will stay relevant. :) I assume it's not a high priority right now because there aren't many people using MAX in EA that are working on any serious projects, so it isn't encountered very often. It will probably start getting asked about more and more when MAX leaves EA and people who start working on serious projects and start adding in a bit of polish stumble their way into it.

Anyway, I have nothing else relevant to add to this issue, so I'll stop spamming the comment sections about it.

**Comment by LeeBamberTGC** [comment]
@fearlesswee New probe system in next EXP build, with added properties for lights in the advanced mode.  You can now opt-in a light to be a light probe location and can set the range of the env map capture:
![image](https://user-images.githubusercontent.com/35840583/230136733-88675685-2c2b-4eef-8e23-0a594757dbd3.png)

Also added some nice smoothing stuff to transition calmly between the newly recruited 8 physical probes to cater for as many virtual probes as you need for your level

**Comment by MonkeyFrogStudio** [comment]
@fearlesswee That's not how you should be using a light probe, to start. That one green light should just be a light and not a probe. Keep that green light and then set another light in the center of the room at about the player's head height and tick the Probe tick box. You can turn the probe's light off by setting the color to black and/or by setting the light range to zero. Then set the probe range to ensure it covers the entire room. Then test again.

**Comment by MonkeyFrogStudio** [comment]
I think the current light probe (also known as reflection and/or environment probes) are not implemented properly either in MAX or the version of Wicked that MAX is currently using. In most game engines, you are able to create a box around the area that should reflect back the information of the probe. This box can be shaped to fit the area (thought kept as a box with six sides). So, if you have a building that is longer than wide, you could make the probe fit that and only those things inside that long building would be affected by that probe. 

The current implementation in MAX only has a RANGE for that probe. I am assuming this means that a perfect cube is being projected and as the range is increased, the cube just grows larger. If this is the case, then the probe will extend well beyond the bounds of a longer than wide building, as an example, which is not ideal.

However, if this is the implementation, and we know it is, then we can build levels with this in mind. Heck, even with the better implementation (where you can size the box as needed), you still have to be careful how you build the level so that you don't get spillover, etc.

Every game engine has it's quirks that need to be worked around to get the results the developer is after.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio @fearlesswee Thanks for the feedback, I will see what I can do :)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio @fearlesswee Newer probe system uploaded with new Add Environmental Probe button in game elements, and control over size. rotation and global level env resolution. We will need to go through all the demo levels too to add these extra elements, but they do make a huge difference:

![image](https://user-images.githubusercontent.com/35840583/230260585-a9132b27-6861-4cf4-a0db-3b59c0c012ab.png)
VS
![image](https://user-images.githubusercontent.com/35840583/230260826-cc174d21-93f2-4c3f-a8ea-6ecf6cbbe95c.png)

**Comment by fearlesswee** [comment]
Going through some of my older issues and closing this as fixed, as the latest iteration of the probe system means this issue is no longer present.
