### ISSUE TITLE
Documentation IS Important Too....

### ISSUE THREAD

**Issue by jasailor** [TheGameCreators/GameGuruRepo#3568]
GGMax Team,

I'm posting a comment about an important component of the new MAX software.   The Users Guide/written documentation is not keeping up with the product.  Game GG Max is developing into a nice product, but if the written documentation doesn't reflect its capabilities it will not reach its planned potential.   

Most novice folks don't want to do endless experiments or do hours  of trial and error to see how things work.  They also don't have the patience to search within a ton video's trying to find the 15 seconds of casual comments on how do something.  The User Guide was a good start and I was very hopeful, but it needs to continue be enriched to keep up with all the new capabilities on a detailed level.  

IT Axioms: 
- Good software with comprehensive written documentation = great acceptance by all types of users.
- Good software with a dependency on using videos, minimum written documentation, postings on various forums leads to frustration, lack progress = limited FUN and accomplishment!  I

Sorry for the bit of a rant, but you guys are working so hard on this product and it is becoming exactly what you described and we all hoped for.  It's targeted for the novice with great opportunity for technical expansion and it certainly has a good start.  Please do not leave that vision behind by not providing documentation that allows the casual game creator to make easy simple and satisfying progress.   

Hopeful,

JASAILOR

**Comment by synchromesh62** [comment]
This has been mentioned before 
The main problem right now is its all changing so much sometimes on a daily basis with things moved around and so much more to be added. RPG, Puzzle, VR will all have to be integrated and there is no doubt the UI will change, Then a whole new Weather system planned, Structure editor. Already we have had stuff moved about and changed last week to accommodate the   new animations with a shift around and new check boxes added. 

Your not wrong but i can understand now things are moving so fast its just not ideal to update it at Breakfast to find Lee has changed the layout and added stuff just before Tea time :)

That said a lot of **where is this and where is that , How do you** most common questions are in fact in the manual or tutorial videos but they do not look and if you say **That is in the manual or video tutorial check it out** your accused of sarcasm and a non helpful community :)

**Comment by AmenMoses** [comment]
I disagree with your Axioms.

Having been in the industry for more decades than I like to admit to, I can honestly say I've rarely met anyone who rtfm!

**Comment by jasailor** [comment]
I appreciate everyone's comments and the strong community that supports GameGuru.   Many of you have been learning this environment for a long time and are truly experts.  

I have been a senior leader in IT for a long time and am just trying to keep a balance as this product develops.  The tag line for the software is "game making for everyone" and not "try to discover all the software capabilities and then try to figure out how they work by trial and error".   "Everyone" is a 10 year old, game making for the first time or an old IT guy like me that just wants to have some fun.  Both don't have much patience for investigating intrinsic capabilities, but only want a quick reference to know what all is available.  Over the years, it appeared to me that GameGuru with all its capabilities had limited acceptance largely because the true functionality was not immediately obvious to those outside of the "community".   I think that MAX is in danger of taking the same path.  For example, the new capability released on Friday that allows you to pick up a document and read it.   I think that is really cool, but just seeing the little document object among all the other objects, one would never know it is even there.  To know what it does you would have had to see the segment on Lee's 107th video.  

I would like to see the MAX platform be well accepted as a game creation tool and not just an R&D platform.  It is always brought up the development is changing too fast for the documentation to keep up.  Well perhaps the releases should be slowed down so associated updated documentation can also be released.  Can you imagine how many potential "drive by" customers are being turned off by just not knowing all the great capabilities.  It is possible to have both a great software tool and associated complete documentation.  For example , the Game Creator tool - Dark Basic had rich documentation (although published books) that allowed someone to find a function's its use case example very quicky.  

In any case this is my last post regarding this.  I hope no one in the community was offended or POd by my comments.  My only purpose was to bring it up so Lee and his team would consider this observation.  Great success so far - keep going....

Cheers!

JASAILOR

**Comment by davetgc** [comment]
Thanks for the feedback. There are a number of tutorials and as the product grows more will be added. Full documentation in an early access product is difficult due to changes, but it will grow over time.
