### ISSUE TITLE
Zombies sometimes not taking damage and red dot "bugs".

### ISSUE THREAD

**Issue by regamox** [TheGameCreators/GameGuruRepo#3569]
Hey. [Here are some bugs](https://www.youtube.com/watch?v=4thD9Bz_D2U) I found. I belive the actual red dot is a placeholder? It does the work so it's fine but yeah, still a little problem nonetheless.

**Comment by davetgc** [comment]
Do you mean because the zombies stand back up? This is a feature of the zombie and sometimes they come back.

**Comment by regamox** [comment]
I thought it was pretty obvious what I was talking about. No, I am talking about the part after that, where I shoot at still zombies and they don't take damage.

**Comment by davetgc** [comment]
You mean on the floor? When they are dead?

**Comment by regamox** [comment]
Go to 0:16 on the video. Do the zombies look like they're taking damage? Please watch the entire video to understand and not just a bit of the video at the start.

**Comment by davetgc** [comment]
Can you please upload a map using default media that can be tested. The zombies look to be out of effective range in the video as opposed to not be taking damage.

**Comment by regamox** [comment]
I feel like a scoped weapon should not be that inaccurate, maybe you should be able to modify certain aspects of the gun like this.  I experienced this in the Foggy Forest demo, which, if I understand correctly, is using default media.

**Comment by davetgc** [comment]
Ok, I'll test the Foggy Forest, but I think this is about the weapon
settings rather than a bug as such.
