### ISSUE TITLE
2022.08.05 update made level unstable.

### ISSUE THREAD

**Issue by Ohneiros** [TheGameCreators/GameGuruRepo#3572]
Greetings! I've made a mid-complexity level of a cave, with several "reveal" zones and switch-door relations. Almost 80% of the game's objects were only revealed when activating the reveal zones. Everything ran really smoothly, but since the last update, the level started to crash after activating the first switch - and two reveal zones along the way. Ticking the "show at start of level" box in all static objects and deleting the reveal zones related to these objects seems to have helped somehow; however, the level editor takes way longer to load than before, and occasional crashes will still happen. Updating hardware drivers did not help.

I'm running everything in 1366x768 with Nvidia set to "performance" for hardware reasons. Here are my specs: 

Processor	Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz   2.50 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor
Windows 10-Home Edition 

Quick question: would adding more RAM help the issue? 

Thanks in advance!

**Comment by MonkeyFrogStudio** [comment]
The latest release has been crashing for everyone ... rather randomly, it seems. You can see the report on it here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3556

**Comment by davetgc** [comment]
This is a multiple report and should now be fixed.
