### ISSUE TITLE
GameGuru MAX - Bug - Trigger Zones making spawned enemies have more health

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3573]
I created a video showing this bug, in the video you can see the character only has 5 health and when she's not connected to a trigger you can take her down quickly as expected, but when she's connected to a trigger with no other adjustments, she has a huge amount of health. Should also know this just started happening after the most recent update. https://youtu.be/XwRMJE7uWcc?t=1

**Comment by LeeBamberTGC** [comment]
@Sinergygames Most likely fixed a while ago, but just tried with my small test level, set an enemy with 5 health to spawn when enter a zone:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/187b1806-51ca-40ce-b7c6-6ffb9c324050)

In test level, took one shot to kill the guy:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2cc1fd04-fcca-4a94-9c16-13e3267580bb)
