### ISSUE TITLE
Latest Version Crashing

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#3574]
Hi since installing the latest update.
My game now crashes within a couple of minutes.
Praying for a fast update as I've spent way to much time on this..
Video drivers-Latest
Windows 10 fully updated
System cleaned.
Ryzen 5 5600x 6 Core + 6 Thread
RX 580 with 8 gig ram
16 Gig Ram
Cheers

**Comment by MonkeyFrogStudio** [comment]
Reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3556

It would be good if you added your system specs there, as well. 

Also, it's good to do a brief search on GitHub to see if the issue has already been reported.

**Comment by MartinCranshaw** [comment]
Specs as above Ryzen 5 5600x 6 Core + 6 Thread
RX 580 with 8 gig ram
16 Gig Ram.
It would appear that the issue has been reported. I wondered if it was anything to do with AMD?
I'm somewhat fractious as I've now hit a dead end.
I tried rolling back the version. But I can only install up to three ago or the newest version which crashes.
Thanks for your reply.

**Comment by earthling45** [comment]
> Hi since installing the latest update. My game now crashes within a couple of minutes. Praying for a fast update as I've spent way to much time on this.. Video drivers-Latest Windows 10 fully updated System cleaned. Ryzen 5 5600x 6 Core + 6 Thread RX 580 with 8 gig ram 16 Gig Ram Cheers

Is this with the latest fix? Build 2022.08.05

**Comment by davetgc** [comment]
This should have been fixed on the  08/08/2022., it this still an issue?

**Comment by MartinCranshaw** [comment]
I think so. Maybe too many coincidences, thanks.
I'll let you know.
Cheers
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by MartinCranshaw** [comment]
Still crashing. Sadly.

**Comment by davetgc** [comment]
Sorry to hear that. Have you updated to the latest Steam version?

**Comment by Curiosityuk** [comment]
I have the none steam version and this too is still crashing after a few minutes.

**Comment by MartinCranshaw** [comment]
> This should have been fixed on the 08/08/2022., it this still an issue?

Newest downloadable is 05/08/. So I'm guessing that it will be fixed in the next update? Cheers

**Comment by MonkeyFrogStudio** [comment]
@MartinCranshaw The 5/8 update was the emergency update that was supposed to take care of the crashing issue (and did for most people).

**Comment by Curiosityuk** [comment]
I've just tried verifying the files and then restarted my computer etc but unfortunately it is still crashing.

**Comment by davetgc** [comment]
If you're still experiencing crashes, can you please give a little more
information? Is it a straight crash to desktop for example?

**Comment by MartinCranshaw** [comment]
I think I've cracked it.
I typed %temp% into Windows Run.
It comes up with a list of files.
Some are in use by the system and can't be deleted. Others with long numbers and letters can be deleted. I had to use administrator privilege's. Sent the lot to the recycle bin in case they needed to be recovered.( It took a bit of time)
Max now running like a dream again. Thanks everyone for looking in to it,

**Comment by Curiosityuk** [comment]
Yeah, When it crashes I goes straight to desktop.

**Comment by davetgc** [comment]
That's great, and useful to know.

**Comment by MartinCranshaw** [comment]
Windows cleaning of temp files doesn't work by the way. Perhaps a batch
file to delete on closing of Max might be a good idea. Cheers

*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by davetgc** [comment]
@MartinCranshaw  - So, did clearing the files work at first, and then MAX started crashing again?

**Comment by MartinCranshaw** [comment]
Sorry that wasn't very clear.
Cleaning the temp files using the %temp% command does work.
But going into Windows disk clean up which also has the ability to remove
temp files doesn't. These files remain.
Cheers
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by Curiosityuk** [comment]
I tried what you suggested Martin and GGM is still crashing.

**Comment by MartinCranshaw** [comment]
Hi Curiosity.
Although doing what I suggested solved many problems.
I found out later that GGMAX was still crashing especially in Wooded areas.
Are you using an AMD Video card?
If so I discovered that GGMax didn't have it's own profile and was just running on global settings.
Having added it to Amd' it is now running perfectly
![Adding Ggmax to amd game profile1](https://user-images.githubusercontent.com/38034903/184850399-a8c698e4-f827-45e5-9bf1-60b3f893ec73.jpg)
![Adding Ggmax to amd game profile2](https://user-images.githubusercontent.com/38034903/184850436-9ac5c36b-a25a-487c-9bb5-ce4a1ff24fde.jpg)
.

**Comment by Curiosityuk** [comment]
Hi Martin. 
                   My card is a NVIDIA GeForce RTX 2060.
I never had any real issues until lately. And as you stated it was a forest section I was testing.


> Hi Curiosity. Although doing what I suggested solved many problems. I found out later that GGMAX was still crashing especially in Wooded areas. Are you using an AMD Video card? If so I discovered that GGMax didn't have it's own profile and was just running on global settings. Having added it to Amd' it is now running perfectly ![Adding Ggmax to amd game profile1](https://user-images.githubusercontent.com/38034903/184850399-a8c698e4-f827-45e5-9bf1-60b3f893ec73.jpg) ![Adding Ggmax to amd game profile2](https://user-images.githubusercontent.com/38034903/184850436-9ac5c36b-a25a-487c-9bb5-ce4a1ff24fde.jpg) .

**Comment by MartinCranshaw** [comment]
I had to buy another copy on Steam as I wanted the Animation pack and
couldn't purchase it from TGC store.
I made a simple terrain with trees to test it. Ran around for approximately
1 minute before it crashed.
Cheers.

*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw Is your original issue resolved?  Just for info the next DX12 update will solve the remaining AMD related issue :)

**Comment by MartinCranshaw** [comment]
Hi Lee, The Steam version is crashing but the TGC version appears to be OK?
Looking forward to DX12.
Cheers
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
