### ISSUE TITLE
Sci-fi weapons Bug

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3577]
Hi There I'm having problems with the following weapons. Sci-Fi Assault rifle, Sci-Fi Auto Slug and Sci_fi Vickers

Sci-Fi Assault rifle Pic
![Sci-Fi assault rifle](https://user-images.githubusercontent.com/93008801/183454511-86cca26e-6456-453f-9183-d52c7cbf541e.jpg)

Sci-Fi Auto Slug Pic
![Sci-Fi Auto slug](https://user-images.githubusercontent.com/93008801/183453571-896e8972-996a-42b5-83ac-82df642e664d.jpg)

Sci-Fi Vickers Pic
![Sci-Fi Vickers](https://user-images.githubusercontent.com/93008801/183453604-2c8d9bb6-be33-4b17-9423-068f5322fecb.jpg)

As the pictures show above. Is anyone else having this problem

**Comment by davetgc** [comment]
Not all weapons are supported, and these are very old. So, It's not a bug, but simply not compatible. You would need to make changes to the model I suspect.
