### ISSUE TITLE
MAX - Scrolling Texture Support

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3581]
Can we please have support for scrolling textures.

They are super useful for transforming a lifeless level into one that is alive with motion.

We can use it GGC for adding life to the scene.
Note how the skylight uses it, and it is used for fluid in this vid:

https://vimeo.com/manage/videos/419574933

**Comment by MonkeyFrogStudio** [comment]
Requested here (animated textures):
https://github.com/TheGameCreators/GameGuruRepo/issues/3142

I've heard through the grapevine that animated textures/materials may be on the way soon-ish.

**Comment by OldFlak** [comment]
Yes, I am not talking about swapping textures, or video projection, but simply moving the texture across the mesh.

The skylight and fluid in the above video are just a texture scrolling over the mesh. 

By using simple UV orientation you can get nice effects like in this video:
https://vimeo.com/manage/videos/471252578
In the video:
- the text banner on the fence/barrier is not rotating but just employs texture scrolling
- the ocean of the world is not only rotating via script, but also uses texture scrolling 
- the fluid pipes above the world use texture scrolling
Note:
The parts mentioned all use the same texture sheet, in fact the fluid in the first video also uses the very same texture sheet.

The force-fields in the video are animated the same way.


Of course video projection would be a great feature as well
- but also requires dedicated video for any intended projection
- so has specific uses

Texture scrolling is simple to create and far more versatile for many scenarios
- 1 texture, many models referencing it
- Super versatile :) 


Can we have all of the above tomorrow - thanks team :)

**Comment by MonkeyFrogStudio** [comment]
Yes, that's exactly. That's what an animated text is and what I was referring to in that GitHub request when I said:

> We also need a method to display animated textures/materials on objects

Animated textures/materials are used for exactly what you're talking about - things like lava flowing along a mesh, etc. So, the other request was for what you're after AND the other things (swapping and video).

**Comment by davetgc** [comment]
This has been request many, many times and Lee has even spoken about it in several broadcasts. So, we are aware that it's been asked for.,
