### ISSUE TITLE
Zombie behavior

### ISSUE THREAD

**Issue by ZetComGames** [TheGameCreators/GameGuruRepo#3582]
![X2UUmhcfG2c](https://user-images.githubusercontent.com/109797224/183571585-32d4fd40-6be2-4b4d-86f5-444f93b4e89e.jpg)
when the zombie loses sight of the player, it changes course in an unknown direction and stops reacting to the player.

**Comment by davetgc** [comment]
Is this the same issue as this?

#3591

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
