### ISSUE TITLE
Sound Slot 4 Not Working.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#3584]
The first three slots work ok but the last one refuses to play at all using PlaySound(e,4) or PlaySoundIfSilent(e,4) etc. It would be useful to have a few more slots as well or to be able to add them as needed.

**Comment by AmenMoses** [comment]
The first 4 slots work, i.e. 0 .. 3.

#1681

**Comment by davetgc** [comment]
Treating slot 1 as slot 0, etc. Does this fix the issue for you?

**Comment by AmenMoses** [comment]
No, in Classic we have 5 slots, numbered 0 to 4, in MAX slot 4 no longer works in all cases.

Slots 0 to 3 still work though.

**Comment by AmenMoses** [comment]
So scripts written for entities with 5 sound samples attached in Classic will no longer work if brought over to MAX.

**Comment by davetgc** [comment]
It also makes sense to up the sound slots to 5 in MAX, for future compatibility with Classic.

**Comment by Retrogamebloke** [comment]
"It also makes sense to up the sound slots to 5 in MAX"
Yes, as it's in the editor :) But upping sounds in both would be better still now Classic has 64-bit as well. Either a higher limit or a way to add sounds as you go beyond the default. Global sounds are fine in lua, but most people won't venture there :)

**Comment by LeeBamberTGC** [comment]
Currently, sound slot 4 was re-used to hold the DLUA values. Alas, we did not consider Classic scripts to move to MAX given all the changes we have made to the underlying graphics engine and 2 years of changing things on the game engine side. At this time there are no plans to offer full compatibility of Classic scripts in MAX, only that some might work with small modifications.

I am leaving this open as a bug as there will be a lot of confusion from Classic scripters moving over, and I think we can get the engine to store its DLUA data somewhere else :)

**Comment by AmenMoses** [comment]
That explains a lot.

**Comment by Retrogamebloke** [comment]
Ah, well if it can't be changed quickly, perhaps removing it from the gui would be an idea?
![image](https://user-images.githubusercontent.com/44620846/185464693-5ad64ef6-183b-44aa-8111-09118222e8c2.png)
It's clearly in the Max IDE and as such people will expect it to work. At least temporarily until a fix or improvement is made.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke Fortunately, we already had some extra sound slots from previous engine work, so with some careful restructuring, the MAX engine now leaves soundset4 alone, and uses the internal soundset 5 and 6, which means we can have Sound0 through Sound6 (6 in total), and a few bugs in there are also fixed so hopefully no more cross corruption if you try to use the sound4 field in your scripts.  Worth testing out these changes in today's update due later!

**Comment by Retrogamebloke** [comment]
![image](https://user-images.githubusercontent.com/44620846/186277687-0a848174-75b3-4698-9d7a-ce74da96034a.png)
Sound 4 is now duplicated in the editor list. Tried calling sound 4 to 7 in lua with no success with the Play command. I either get no sound, or a random one. I am loading a few direct sounds as well, which are probably the random sounds I get.

Not fixed as yet as far as I can see. No way to add sounds 0-6 in editor ( we have 0-4 still with a second 4 at the end) and even in lua, sounds don't play from editor slots above 3. Add a sound to slot 4 and both 4 slots are again duplicated with same sound, but still do not play. Setting it as 5 or 6 is the same.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke Yes I found a slip in the developer mode area for sound 5 and 6. I have fixed this for the next EXP build but also added a new behavior called Loop3DSound Multiple that will expose all the sounds to regular users who are not in the developer mode and so you can more easily test all sound slots trigger fine.  It is also a nice behavior if you have two or more sounds you want to play at the same time for devices that make a distance sound, but a more refined sound when closer (controlled by changing your WAV volume of the closer sound). Eventually, when we have non-LUA methods to chain logic, we will get more users controlling this level of detail and sound slot/volume/freq choices.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke Slot 4 was eaten to use for the DLUA system, but recent additions have extended and fixed the sound slot options from Developer Settings view:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ca0fcd57-ab89-4c07-b563-f5460f64c3af)
