### ISSUE TITLE
Saving the level changes the terrain....

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3585]
saved this MAP and it changed the terrain.

![image](https://user-images.githubusercontent.com/68471279/183728097-2fdeb2bc-269b-44d8-ba17-8c1aa34e367c.png)

**Comment by davetgc** [comment]
Sorry, I can't really see what happened there. Could you please supply some more information. How did it change for example?

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
