### ISSUE TITLE
Cannot close the in-game "Visuals" window.

### ISSUE THREAD

**Issue by regamox** [TheGameCreators/GameGuruRepo#3587]
I am experiencing this on the demo version btw, don't know about the full version. And I don't know if it's clear, but when talking about the visuals window, I am talking about the one you open by pressing tab twice when playtesting your game.

**Comment by MonkeyFrogStudio** [comment]
Did you try hitting TAB again to close it?

**Comment by regamox** [comment]
I am feeling stupid haha, I don't know how I didn't try this. But you still cannot close it by clicking the X button so still a minor issue. No one cares though so I will mark it as closed.

**Comment by MonkeyFrogStudio** [comment]
No worries. It happens. The X button should work (else, why's it there, right?). I think that's been reported previously, though on the Behavior Editor, which operates from the same space.
