### ISSUE TITLE
GG classic global and music Lua incompatible and not allowing the player to move.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3590]
Once GGclassic put to test a level an error for global and music lua files incompatible and freeze the player in spot.

![image](https://user-images.githubusercontent.com/81198887/184039804-a9a022d4-3db0-40cc-9838-aaaaae157c32.jpeg)![image](https://user-images.githubusercontent.com/81198887/184039815-dee10c3e-8b07-492e-a6c4-f416ad8e1d05.jpeg)![image](https://user-images.githubusercontent.com/81198887/184039821-ca2c9744-95e7-43a5-8d48-5b06342a4612.jpeg)

**Comment by davetgc** [comment]
Are you compiling the source yourself?

**Comment by Hamada880** [comment]
No it is steam version

**Comment by cybernescence** [comment]
Looks like you are trying to use lua that has been compiled by the 32bit version (from a standalone) with the new 64bit version. That won't work, so you'll need to either use the uncompiled lua to test or create a new standalone with the 64bit version to recreate new compiled lua.

**Comment by Hamada880** [comment]
I'm not familiar with the process.The lua I used was free standalone but used it for gameguru and never got an issue. So if you have steps to follow it will be great. I also started an empty scene and still gets the same errors.

Also my question? If the lua is 32bit and gameguru 64now, won't that cause all the lua scripts to give error upon testing??

**Comment by cybernescence** [comment]
What are you trying to do? Are you creating a standalone and then running the standalone and getting this error? Or something else? The lua scripts are compiled when you make a standalone, the scripts compiled by the 32bit version of Classic won't run with the 64bit version, but if you create a new standalone with the 64bit version it will recompile the lua scripts and should be fine. If you could tell me what you are doing step by step I can try and recreate

**Comment by Hamada880** [comment]
What I did is tested a new empty scene to try the new added feature and as soon as I clicked on that test game as it loads the level I got these errors. The player wasn't moving at all. I even closed the with ESC and added player starting point to see if it helps but it is the same result.

**Comment by cybernescence** [comment]
Ok, sounds like you could try a steam verify after the new version installed. It still seems like you have old versions of the lua being picked up by the new version of GG.

**Comment by Hamada880** [comment]
Okay, I'm try that and see if it fix the issue I have.

**Comment by Hamada880** [comment]
The issue, have been fixed. Thanks so much for helping:)
