### ISSUE TITLE
GG Classic compile x64 bit - Editor is still 32 bit

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#3592]
Hi,

Just wondeing why Editor is only selectable in VS as 32 bit and not 64 bit also?
The rest compiles ok thouigh.

**Comment by cybernescence** [comment]
Lee said on one of the weekly streams that the UI was created from old out of support third party 32bit technology. So I Imagine it wasn't worth the effort to try an update to 64bit even if it was possible. Not sure it matters TBH as all it's doing is passing requests from the UI to the main 64bit exe? Cheers.

**Comment by redagent101** [comment]
yes this is true, it's no biggy at all.  ok this can be closed.
