### ISSUE TITLE
fbx model no correct collision

### ISSUE THREAD

**Issue by vinurd** [TheGameCreators/GameGuruRepo#3595]
there are problems with fbx/ it is inaccurately positioned, does not exactly put down collisions-they are displaced. On the advice from the chat I replaced it with gltf and the model was installed normally.

[fbx](https://dropmefiles.com/7p2J4) and  gltf model

video - https://youtu.be/vK1IjRGvFOU?t=10252

**Comment by MonkeyFrogStudio** [comment]
Your zip file is password encrypted. So, I cannot take a look at it to see what the issue may be.

**Comment by Tam51** [comment]
That's easy to open the password is in the name of the file 123

**Comment by davetgc** [comment]
Please can you let us know if this issue has been resolved, often in these cases it's an issue with the original model rather than the importer.

**Comment by vinurd** [comment]
I clicked apply all transformations and selected the check mark in the export apply transformations. I don't have a collision on the object

**Comment by MonkeyFrogStudio** [comment]
These are my current export settings in Blender:

![settings](https://user-images.githubusercontent.com/36735507/184478267-edc0efd8-0937-425b-9787-5525a44bc673.png)

As you can see from my screen shot above, I do get collision set properly to your object. Now, I did select Polygonal Collision, else it comes in with Box by default (as all models do in MAX unless told otherwise).

**Comment by vinurd** [comment]
I found what the error is.Uploaded the same model. In the first case, I don't touch it in the editor.In the second, I scaling her and changed her position. The same model.Photo
[url=https://ibb.co/NWj9Qjv][img]https://i.ibb.co/NWj9Qjv/2022-08-13-17-37-19.png[/img][/url]
[url=https://ibb.co/vLrLkBS][img]https://i.ibb.co/vLrLkBS/2022-08-13-17-45-53.png[/img][/url]

**Comment by davetgc** [comment]
Can you confirm if this is fixed for you please?

**Comment by MonkeyFrogStudio** [comment]
@vinurd I can't replicate this on my end. I've imported my own custom model, assigned a collision shape, and placed it on the level. Then I scaled it and moved it to a new position. When I run the test game and tick Physics Objects, the collision mesh is correctly placed on the object.

**Comment by earthling45** [comment]
This is easy to replicate if you follow the steps as he explained.
Import an object, do not move or scale it and it is ok.
Import the same object again, scale and move it a little and the result is that the collision is out of place.
So in short, if during the importing of a model changes are made to the position or scale, the collision is likely not updated when the position and or scale are changed during the importing of a model.
See image.
![physic shapes](https://user-images.githubusercontent.com/35744254/184547444-c7018a5c-bb80-4a2b-96d9-62399bdc1386.jpg)

**Comment by earthling45** [comment]
@davetgc i did the above test importing on the latest preview build.

**Comment by MonkeyFrogStudio** [comment]
Gotcha! I didn't realize the scale and translation were taking place during the IMPORT process. You're absolutely correct, if you scale and move the object during import, it doesn't scale and translate the collision mesh appropriately:

![collision](https://user-images.githubusercontent.com/36735507/184550455-504314db-ee6b-48aa-bf10-f378ce51a8d3.png)

**Comment by earthling45** [comment]
It would help if the collision mesh is also visible in the importer like in GG. :)
I haven't tried it but i do think that after scaling and moving re-selecting the prefered collision option would also place it in the right position. In fact, i'll try this out now.

**Comment by davetgc** [comment]
Ok, thanks for the further information.

**Comment by LeeBamberTGC** [comment]
@vinurd In current build, imported an FBX, scaled, then moved both position and rotation on the Y, and the static polygon collision mesh lined up nicely:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/71354fff-a31d-467c-8813-df1e9e5217a5)
