### ISSUE TITLE
GGclassic textures type invisible.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3596]
The texture type" stone,sand, snow...etc" is now hidden or not in the texture pallet on the right lower corner. After the last public preview update.

**Comment by Bullyblasta** [comment]
i had that issue when i first got GGClassic, but uninstalled GGClassic and reinstalled and it worked fine. so if that doesnt work for you im sorry. hope you can fix it

**Comment by Hamada880** [comment]
I will tested it,see if it works

**Comment by LeeBamberTGC** [comment]
@Hamada880 In latest version tested for the October update, all 16 texture choices for terrain painting show up nicely:

![image](https://user-images.githubusercontent.com/35840583/194892643-242d1afb-ee3b-4641-a9a3-e8b32680871c.png)

There was no SNOW texture in the default texture set for GameGuru Classic.  Of course, you can change a texture using the right mouse button:

![image](https://user-images.githubusercontent.com/35840583/194892826-46200eea-68b3-489d-ab3c-9233bc182a79.png)

Now snow, but as you can see custom textures are fine also:

![image](https://user-images.githubusercontent.com/35840583/194892962-baf1e6d3-b4b5-4475-a8de-84e3b92be1d9.png)

**Comment by Hamada880** [comment]
I have update the GGMax this morning but haven't yet tested the texture. I'm tested and confirm the fix. Thanks for the update.

**Comment by Hamada880** [comment]
It works fine now, this issue can be now closed. Thanks for the update and the bug fix.
