### ISSUE TITLE
Height of Player

### ISSUE THREAD

**Issue by SOLODESIGN** [TheGameCreators/GameGuruRepo#3597]
Hi,
I was wondering if we could have the ability to raise or lower the height of the player, Example: The player is in a MECH robot that towers over the terrain area so moving the line of sight up would help this. The player is in a tank so lowering the player line of sight would help with this.

You can do this in CLASSIC so I would have thought it is an easy fix to do it in MAX...

Many thanks

Solo

**Comment by MonkeyFrogStudio** [comment]
Requested here, also:
https://github.com/TheGameCreators/GameGuruRepo/issues/3294

**Comment by davetgc** [comment]
Duplicate, thanks for the suggestion, but please check before posting, as this will save the team a lot of time not replicating issues. Thanks.
