### ISSUE TITLE
the player leaves behind mirror spheres

### ISSUE THREAD

**Issue by vinurd** [TheGameCreators/GameGuruRepo#3602]
camera movement in the editor and in the game leaves mirrored spheres
[url=https://yapx.ru/v/TT17j][img]https://i.yapx.ru/TT17j.png[/img][/url]

**Comment by davetgc** [comment]
Hi, unfortunately that link is private. Where possible, please upload videos/images directly to GitHub, so that they can be found without going an external source.

**Comment by Curiosityuk** [comment]
Yeah, I had that too and then it crashed as usual :-(

**Comment by davetgc** [comment]
I've not seen this, are one of you able to supply a video showing this please?

**Comment by vinurd** [comment]
this glitch disappeared after a new entry into the program

**Comment by vinurd** [comment]
after a while, he reappeared.

video  https://youtu.be/zvSEOQ2Ah1c

**Comment by vinurd** [comment]
I figured out what it is! you have a binding to the E button and trees to the Q button https://youtu.be/oMGoz5m6SJg
