### ISSUE TITLE
Added animation slots not shown in behaviour editor

### ISSUE THREAD

**Issue by njab64** [TheGameCreators/GameGuruRepo#3603]
Bug / Enhancement/ Being an idiot, take your pick...

I'm trying to add animation slots (booster pack) to a existing character (Old Billy Joe) to get him to sit, then stand and walk to the player/target when in range. All seems fine, animations add as new slots and character is saved. However when I use the Edit behaviour and look for the added animations only the default/original animation template is listed. (hope that makes sense)

As a comparison.. If I import a character .dbo as a 3D model the animations are listed, but it then doesnt have the AI logic. ie Go To Target doesnt work.

**Comment by davetgc** [comment]
Thanks, but this has already been reported here: #3546 and I understand is being worked on. Please consider using the search before posting, as this can save the team a lot of work not chasing multiple reports.
