### ISSUE TITLE
Particle bomb dont sets off by trigger platform

### ISSUE THREAD

**Issue by RobDaHob** [TheGameCreators/GameGuruRepo#3606]
Particle bomb dont sets off by trigger platform
Or how do i set it off?
Rob

**Comment by davetgc** [comment]
Hi, I'm not sure what you mean here. can you please supply some more information.

**Comment by RobDaHob** [comment]
In particle effect you have explosions, they dont loop like smoke or other stuff.
But I tryed to set it off with a trigger plattform. set the connection to activate but nothing happens.
Can you please tell me how you set off this particle effect explosion with a trigger plattform???
Hope you understand
Rob

**Comment by vinurd** [comment]
in the object settings, check the explosive

**Comment by RobDaHob** [comment]
ok, thx

**Comment by vinurd** [comment]
if I understand correctly, it is necessary that the particles are triggered once through a trigger

https://youtu.be/YOkUQDSJ2Vo

**Comment by RobDaHob** [comment]
Was more complicated then i thought, thx.
