### ISSUE TITLE
GG CLASSIC 64bit .fbx Import no longer working correctly!

### ISSUE THREAD

**Issue by markfitz2014** [TheGameCreators/GameGuruRepo#3608]
Since the latest 64bit update I am no longer able to even import a cube from Blender using fbx the same as I can with the June 2022 update version. Show s incorrectly in the importer I am unable to correctly setup collision etc..

**Comment by LeeBamberTGC** [comment]
@markfitz2014 Just tried with a few FBX's I have sitting about, including our Dragon, all seems fine:

![image](https://user-images.githubusercontent.com/35840583/194893469-4cce0050-f4c3-40b0-93c3-e7268acbadb2.png)

Can you attach your FBX you exported from Blender, sometimes FBX variants can be tricky and varied :)

**Comment by LeeBamberTGC** [comment]
NOTE: Collision for the imported model is controlled from the right panel with a few choices available:

![image](https://user-images.githubusercontent.com/35840583/194893852-6102a65e-dcb8-40a9-9e6c-6142c1a32643.png)

**Comment by markfitz2014** [comment]
Thank you for the email, unfortunately I am unable to access my PC as I
have an issue with either the CPU, cooler or both. I will receive new parts
in a few days and hopefully have the issue resolved soon.

If I remember correctly the issue was that the second object imported by
*.fbx would show as the first object. I think I used a cube textured first,
then a corner wall section with floor for the second ( like a hollowed out
cube with ceiling, floor and two walls ) no i did not use boolean
difference operations or modifiers. This was with the first x64 update of
classic, so I will check back as soon as I get my PC up and running again.

Sorry for the delay in responding. I had to get an old laptop fixed up and
running to access emails and basic stuff for now.

**Comment by LeeBamberTGC** [comment]
@markfitz2014 Are you able to reproduce this with a fresh install of the latest build which is 64-bit. I saw another report similar to this one that happened during the transition from 32 bit version related to a rogue old file in the iimporter folder.
