### ISSUE TITLE
GameGuru MAX - Bug - Need to Recalc All Paths when Navmesh Changes (due to door blockers)

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3609]
I've reported this before, but it was a part of another bug. I felt this was important enough to post on it's own because it's a showstopper, imo. The navmesh can be altered by a physics object, like a door, causing issues. Here's an example:

![navmesh1](https://user-images.githubusercontent.com/36735507/184854691-005555a7-67f2-459e-b687-993d57d7b77c.png)

In the above screenshot, the doors have not been placed in the level. As a result, the navmesh is clean and the enemy soldier at the end can move freely through the threshold of the doorway. This means he can get to me and attack me.

In this screen shot, the doors have been put in place and opened:
![navmesh2](https://user-images.githubusercontent.com/36735507/184854871-747c9c30-cdc1-4133-8f0c-3165dc0a06e3.png)

As you can see, the navmesh is "broken" where the doors were. It's pushed down below the ground. As a result, the enemy cannot cross the threshold of the doorway and is stuck on the other side, unable to pursue me.

The door is a physics object, set to Physics On, btw.

**Comment by MonkeyFrogStudio** [comment]
Upon further investigation, it's the Sliding Door behavior that's causing the issue (haven't checked other behaviors).

Here's a screenshot of the door set to Physics On, but no Behavior attached:
![navmesh3](https://user-images.githubusercontent.com/36735507/184859582-093c5543-e48e-4307-a780-118fdab6363f.png)

Notice the navmesh is fine and, given the chance, the enemy can pass through the doorway's threshold to get to me.

Here's the same setup, but the door has the Sliding Door Behavior attached to it:
![navmesh4](https://user-images.githubusercontent.com/36735507/184859738-5c2aecaf-6833-43dd-bc8b-48c1fb027661.png)

Notice the navmesh is now broken and the enemy cannot cross the doorway's threshold. Doesn't matter if the other door is opened, etc., that area is blocked off.

**Comment by MonkeyFrogStudio** [comment]
As a side note: The door is set to Physics On, Always Active, and IsImmobile is set to Yes.

**Comment by MonkeyFrogStudio** [comment]
Just checked the door with the Door Behavior (the one that's meant to be used with animated doors) and it also causes the navmesh issue.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC - 

Yes, but it's not working correctly, making it so that the soldier cannot cross the doorway threshhold if there is a door - even an open door - in the doorway using one of the door behavior scripts. Here are screen shots to illustrate:

This is the doorway without a door in it:
![nav1](https://user-images.githubusercontent.com/36735507/184893876-bb644366-e2b9-4dd8-b6d0-a35cd7c4f74c.png)

Notice how the navmesh is complete and, thus, the enemy soldier can travel through the doorway.

This is the doorway with only ONE side of a sliding door in the doorway:
![nav2](https://user-images.githubusercontent.com/36735507/184894039-9dcea5a0-423c-410b-acf0-6823c2ef3a7e.png)

Notice how the navmesh is cut off across the ENTIRE doorway despite there being only one side of the double-sided sliding door in place. This means the enemy soldier cannot even go round the one closed door (despite the other door clearly missing). But that's okay because I would normally have the other door in place. So, let's open the door that is there, and refresh the navmesh.

This screen shot shows the navmesh after the door has been opened using the Sliding Door behavior:
![nav3](https://user-images.githubusercontent.com/36735507/184894486-2d6c0544-60ac-41cf-b7b2-1af20f2d041e.png)

As you can see, the navmesh has somewhat returned, but there are now GAPS that weren't there before (when there was no door). These gaps prevent the enemy soldier from crossing over. As a result, he cannot pass through the doorway to came after me.

**Comment by MonkeyFrogStudio** [comment]
Having said that - with both doors in place, the navmesh does appear to be restored once both doors are open. I will do some further testing.

**Comment by MonkeyFrogStudio** [comment]
In this case, the navmesh did update (I'd unticked and reticked the AI checkbox to see it) when the doors closed, but even though the soldier was far away, he was still able to walk through the doorway (and through the closed door):

![nav4](https://user-images.githubusercontent.com/36735507/184897456-c84c1b74-969d-41cb-8d12-bad9d99892e2.png)

**Comment by MonkeyFrogStudio** [comment]
And now it's pretty consistent:

https://user-images.githubusercontent.com/36735507/184898879-f2ac2b24-3881-441d-aa2d-9c234130b43f.mp4

**Comment by MonkeyFrogStudio** [comment]
This just shows me refreshing the navmesh after opening and closing the door to verify that it does update (and it does), but the soldier still gets through the door:

https://user-images.githubusercontent.com/36735507/184912970-4441f401-f3f7-4347-a5e3-5a47cfd2be65.mp4

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC This was being talked about on Discord and AmenMoses said the following:

**It's probably because the soldier is attacking based on the navmesh path it has already calculated rather than creating a new one.  What the script really required is a raycast check to see if the  spot it is trying to get to is actually visible (I did this for the mammals IIRC) and if not recalculate the navmesh path.**

That makes sense to me. After all, in the above video we can see the red line (which I am assuming is the navmesh path Amen is talking about) and the soldier following it through the door well after the door is closed.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Yes AmenMoses is correct, once the path has been calculated (the red line), the character will follow it, even if the nav mesh changes in the meantime. It used to constantly calculate the line but this caused a performance hit when lots of characters are moving, and some jitteriness as characters choose slight variations each time it was calculated.

I suppose the solution is to refresh all existing paths when the nav mesh blockers are changed, that way it is a single extra calc and would ensure the paths always reflect the state of the nav mesh.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Thanks for looking into this. Sounds like that could be a good solution.

Question, if you don't mind - is there any reason that the NPC can't raycast to detect objects? Therefore, if they are following their path and they raycast and detect a closed door in front of them, they would have to stop (or calculate a new path?). This would also make it so that NPCs could "detect" things like barrels and other objects that might be set to Physics objects, etc., allowing the NPC to calculate a path around the physics object (instead of marching through them, like I've seen them do with barrels from time to time in a level). It could also open the door for NPCs to be programmed to take cover behind physics objects, like barrels, etc., when they are present.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Here's an example of what I'm talking about:

https://user-images.githubusercontent.com/36735507/185104962-99952552-71af-45a5-8a54-edf00e4744a5.mp4

The barrels are set to Physics On, collision shape is set to Cylinder, Always Active is checked, and IsImmobile is set to Yes. He doesn't even "see" the barrels and, as a result, rushes through them. 

If we turn off IsImmobile (set it to No) so the physics barrels can be interacted with, then we get this:

https://user-images.githubusercontent.com/36735507/185105871-db783e75-b29e-459e-8826-260807dd85aa.mp4

The NPC cannot "see" them and, as a result, they walk right through them. No one would do that.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio What you are looking for is dynamic pathfinding, and currently we only have static nav mesh path finding. The object needs to be static to affect the nav mesh, all dynamic objects have no effect on the navmesh except blockers like doors which need an expensive calc to update the mesh.

Constantly ray casting to avoid dynamic objects would be a performance hit, and levels can have hundreds of characters in a relatively close area and then you get FPS problems if they all ray cast all the time. The second video is what I would expect if a character pushes through physics objects. If the physics object is too heavy or has high friction, the AI knows they are not moving and attempts to flank left/right to find a better way around. It's not genius level, but they do avoid running on the spot forever.

I was tinkering with the idea of adding dynamics into the path that gets created from the nav mesh. I already do some manual intervention to smooth out the path around sharp corners to look more organic when walking and running. If this was further tweaked to bend the path around things like other characters and dynamic obstacles you want to go around rather than through, that might serve as a good improvement.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Thanks! Sounds great! Can't wait to see all this in action. :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC 

> If the physics object is too heavy or has high friction, the AI knows they are not moving and attempts to flank left/right to find a better way around.

Except that doesn't seem to be working, either. In the following video, I've placed three barrels in the path of an enemy. The original default weight and friction was 100. I kept increasing this and testing. In the video, the weight and friction is set to **_1000_**! And the enemy just pushes through the barrels just like when they were set to 100:

https://user-images.githubusercontent.com/36735507/185112195-55d6901e-11ac-4f6c-b62d-f7405e0f1db1.mp4

**Comment by AmenMoses** [comment]
There is a maximum mass value to the calculations in the physics package (about 400kg IIRC) due to the fact that masses above that cause issues in Bullet. (i.e. very massive entities can punch other entities through the terrain!) 

The problem is that as characters aren't under Bullet control the effective 'force' they exert is more than what is required to shift a 400kg mass.

**Comment by MonkeyFrogStudio** [comment]
Wow. So, it doesn't really matter what we set for weight and friction, characters will just always be able to push through them.

**Comment by MonkeyFrogStudio** [comment]
So, the real answer here seems to be to place these entities, especially the characters, under control of the physics engine. Isn't that how most games handle this?

**Comment by AmenMoses** [comment]
Well it's a bit more involved than that but yes in a properly integrated solution you have call back handlers for physics objects which will be triggered by Bullet when it detects the impending collisions and within those handlers you have some logic to deal with each impending collision appropriately.

I haven't seen the MAX code but IIRC GG didn't do it that way.

**Comment by davetgc** [comment]
@MonkeyFrogStudio  - Is this fix for you?
