### ISSUE TITLE
weapons

### ISSUE THREAD

**Issue by BiancaValerie** [TheGameCreators/GameGuruRepo#3611]
![Guns](https://user-images.githubusercontent.com/111377284/184927732-066731e7-9791-467e-9cbc-815ad2bb5f74.png)
the weapons have a strange texture

**Comment by Hamada880** [comment]
I can also confirm that same issue is happening in the DLC "Enhanced weapons pack" it seems like the mesh of the weapons deforms.

**Comment by Granada1** [comment]
Look’s like unassigned vertices !

**Comment by Hamada880** [comment]
Yes, only a few weapons.I'm try to list them below. 

- R870 Tactical shotgun DLC
-Akm assault rifle
-MK18 Sub
-Mk19T 
-M292 snubnose magnum

**Comment by davetgc** [comment]
Thanks for the report, but this is a duplicate post. https://github.com/TheGameCreators/GameGuruRepo/issues/3617 I'll close this one to avoid confusion.

**Comment by LeeBamberTGC** [comment]
@BiancaValerie Fixed for the next BETA and PP builds on Steam, check out the Enhanced Weapons Pack and let me know if all is well. Also if you find any more, please do a post here on the issues board, thanks again!
