### ISSUE TITLE
GG Classic 64bit Map Editor Brightness Issue

### ISSUE THREAD

**Issue by nomad5oul** [TheGameCreators/GameGuruRepo#3612]
Hi

I noticed after installing the latest August 2022 GG classic update from Steam the map editor view is a lot darker than before.

Here is how the big escape map used to look in the old 32bit version:
![image](https://user-images.githubusercontent.com/37256116/184946988-51c1ed4b-f12b-463f-bd34-22b3727bbe52.png)

This is how the big escape legacy map looks in the latest 64bit map editor. It is noticeably darker:
![image](https://user-images.githubusercontent.com/37256116/184947124-35a5320a-94fc-4260-a2a8-f3320a4500de.png)

Finally, here is the new big escape level in the latest 64bit map editor. It is almost completely dark:
![image](https://user-images.githubusercontent.com/37256116/184947268-d59c5b24-4e66-4b00-8167-186b46380270.png)

I'm not sure what is causing this but it does not appear to be under user control and it would be good if all maps can have an appropriate level of brightness to them for editing purposes.

**Comment by JCLEONITA** [comment]
confirm  i have the same issue too

june  and march build were fine
