### ISSUE TITLE
MAX -- Bug -- Entities with Polygon Collision are still mis-aligned 

### ISSUE THREAD

**Issue by ShadowMasterOfGames** [TheGameCreators/GameGuruRepo#3614]
There are still entites that are extremely misaligned as my picture below shows. This bug needs to be fixed, I do not know why the author closes his #3560 when is not even fixed yet. So, I am reopening these issues.

![2022-08-16](https://user-images.githubusercontent.com/78239028/184990365-9af81c2c-b971-4501-a0e4-4e8e29770cf0.png)
![2022-08-16 (2)](https://user-images.githubusercontent.com/78239028/184990424-e8d2c422-9fe2-4d29-8ab2-ad622c6aad00.png)
![2022-08-16 (3)](https://user-images.githubusercontent.com/78239028/184990480-8e1e6f51-d90f-47bb-bb75-681f9a5a17f4.png)
![2022-08-16 (4)](https://user-images.githubusercontent.com/78239028/184990512-a8157249-1385-4b8b-8228-346ab099a1c4.png)
![2022-08-16 (5)](https://user-images.githubusercontent.com/78239028/184990568-597132b5-a71b-462e-ae92-a5ffbd84b5fb.png)
 Please do not close this issue until it is fully fixed

**Comment by MonkeyFrogStudio** [comment]
Which assets are these that are misaligned? What are their names? I can't find most of these in my MAX collection? Did you import them yourself? Or ... ?

**Comment by ShadowMasterOfGames** [comment]
@MonkeyFrogStudio, the barn is custom however the collision was working fine until the last three updates. 

The military truck in the tent is Max, it is called BRT GAZ. you can clearly see the misalignments in my pictures above. 

the last picture shows a box around one of my characters as well.  That is why I posted pictures to show the misalignment which they do clearly

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames I thought the .BULLET file was out of date, but alas no. Something has been broken:  Do let me know if you find any other out-of-the-box game assets that have wrong collision shapes.  Also, email me your worst offending custom model in their original 3D format and a step-by-step of what you did to get them into MAX and I will attempt to reproduce the misaligned physics shape. My email is lee@thegamecreators.com

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC -- I just email you (my email is info@chriswphotography.com) I title it #3560, sent you my level in one email and the other has the barn model in it

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC  -- also a side note, some of my characters have the hostage behavior attached but yet they stand there pointing like they have guns, and the ones that are actually on their knees, you cannot release them as well. Thought since you got my level anyways, you could check those as well. However, if you want me to open another issue just for the hostage behavior, I will

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames If you can create a separate issue for the 'hostage character' issue, that would be great, I want to keep this issue about the misaligned collision shapes :)  Working on this one now, slowed by the fact the DX12 engine does not like to render 27 million verts [sigh].

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC this seems to be working fine now after your fix to #3560, so you can close this one too as well

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames Great stuff!
