### ISSUE TITLE
Enhanced weapons distorted in Classic 64bit 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3617]
Just had this reported on Steam and confirmed.
The enhanced Weapons pack is does not like the 64bit in classic. 
https://steamcommunity.com/app/266310/discussions/1/3437955554614048640/

**Comment by MonkeyFrogStudio** [comment]
Already reported here:
https://github.com/TheGameCreators/GameGuruRepo/issues/3611

**Comment by synchromesh62** [comment]
Ok thanks .. Closing this one

**Comment by Hamada880** [comment]
> Already reported here:
> 
> https://github.com/TheGameCreators/GameGuruRepo/issues/3611

Thanks for pointing this was reported earlier. The original post was closed for being duplicated!

**Comment by LeeBamberTGC** [comment]
@Hamada880 Yep, the bug has been fixed, let us know if you find another weapon behaving badly :)
