### ISSUE TITLE
GGClassic - Idea/Suggestion - Triggerable winzones.

### ISSUE THREAD

**Issue by RequiemForRavenholm** [TheGameCreators/GameGuruRepo#3618]
Currently in GameGuru Classic, it is not possible to create a winzone or triggerzone that can start inactive or be triggered. Adding functionality for this would be, in my opinion, a great decision as it would enable much more interesting level design in GameGuru.
![2](https://user-images.githubusercontent.com/111458220/185222380-e9e35411-938e-421b-a09a-e8653df6adf9.PNG)
![image_2022-08-17_201739381](https://user-images.githubusercontent.com/111458220/185224278-c4ee9f22-9ccb-4678-8063-755f0f2ca35c.png)
(I apologise if this post is poorly written/formatted. This is my first post on here and my first post on Github as a whole.)

**Comment by synchromesh62** [comment]
Its a good idea .. We could use this feature in Max also and its been requested
It would enable Zones triggering Zones which would add some cool functions to both engines.

**Comment by Teabone3** [comment]
Not impossible.

 In fact its not even an extra line of code, you just have to add an activate check.

```
function winzone_inactive_init(e)
end
function winzone_inactive_main(e)
 if g_Entity[e]['plrinzone'] == 1 and g_Entity[e]['activated'] == 1 then
  JumpToLevelIfUsed(e)
 end
end
```

You can download the script from the attachment.

1. Place the winzone_inactive.lua script in your scriptbank folder.
2. Place a Win Zone on your map
3. Give your Win Zone a name (by default it is "Win Zone")
4. Place a Trigger Zone on your map
5. Where it says IfUsed on the Trigger Zone, type the name of your Win Zone or just type "Win Zone"

That's pretty much it.



[WinZoneInactive.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10233705/WinZoneInactive.zip)

**Comment by Teabone3** [comment]
I've created a more simpler solution for this that won't require selecting scripts in the editor.  By modifying just the stock winzone.lua script. 

I've created a pull request for it:

https://github.com/TheGameCreators/GameGuruRepo/pull/4015

**Comment by LeeBamberTGC** [comment]
@Teabone3 Thanks Teabone, will be in next update for Classic :)
