### ISSUE TITLE
Add glTF 2.0 Import

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#362]
Hello. It would be great to add glTF 2.0 import to GameGuru:

https://www.khronos.org/gltf/

glTF is free and open. It is quite powerful, allowing importing of geometry, all materials (including PBR), animations, and more. Complete scenes can be exported/imported in one go.

.X is old. FBX is a hassle (and controlled by Autodesk) and, from what I hear, expensive for developers. glTF is supported by most 3D DCCs at some level. For example, MODO has native glTF export. Blender, Max, Maya, and C4D have plugin support for it. And many of those with plugin support will be adding it natively. This means that with glTF import as part of GG, a 3D developer could go straight from their 3D app to GG.

**Comment by Granada1** [comment]
UU3D now comes with glTF 2.0 export

**Comment by ArgentArts** [comment]
Substance Painter also exports to glTF. A lot of software has added it. Even possible to import glTF into engines like Unity and Unreal. It's not a good idea to ignore glTF. glTF is becoming what they hoped .dae (Collada) would become ... a true, universal 3D import/export format.

**Comment by LeeBamberTGC** [comment]
Already on the case, I have posted a freelance job in the GG forums and also chasing my own private means too. I think GLTF is definitely the future ;)

**Comment by ArgentArts** [comment]
Awesome! Glad to hear it!

**Comment by Pirate-Myke** [comment]
Excellent, can't wait to try it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
