### ISSUE TITLE
why have the way setting animations changed?

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3623]
setting animations before opened a lovely easy to use window with all the animations I bought and could chose from, super easy, now when clicking on animations, it opens a folder??? just seams really annoying. the animation screen was super easy to use, this is just annoying as hell.

![image](https://user-images.githubusercontent.com/68471279/185401504-fbcdd0e5-ee55-4ec9-8e5c-0ab99bd8952a.png)

am I missing something?

**Comment by davetgc** [comment]
Is this fixed now?

**Comment by casigus** [comment]
oh yes! sorted now! such a weird bug! good old classic restart sorts it.
