### ISSUE TITLE
Feature request! Animated decals.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3627]
I asked for this feature on the last broadcast and Lee mention it was replaced with particles and asked to mention a use for animated decals and if we needed it to added to GGMax. Examples of animated decals " billboards signs, can be also used to fake highlights areas,objects or building,it will be essential for Future VR and RPG genre. I think it's not costing much in performance since it's an animated sprites.

Thanks also to all the team of GGMax and GGclassic for all the hard work. Let's make GGMax great again 😁

**Comment by Necrym59** [comment]
You can do those decals already

**Comment by Hamada880** [comment]
Have tested it myself and used the same flame decals but it doesn't work all. Keep in mind,I followed same dimensions, sprites number in column but failed to get it animated. I also used both behavior facing decals and the other decal behavior. Will provide screenshots of my object and its not a plane btw.

**Comment by Hamada880** [comment]
So after a few tests,I find out in order to make animated decals works it should be done on the flame plane by replacing the original flame sprite sheet and it can't be done or works in any other object. There is decal extra tab on the flame decals that can't be added on any object even if the decals behaviors were added. There are a few more tests to be done and I will post gifs of my tests.
