### ISSUE TITLE
My characters not walking in direct path in patrol mode GGMax/Character Not moving between flags in patrol mode

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#3628]
https://user-images.githubusercontent.com/107326667/185602657-0e573872-7909-4c63-9f2a-f026c3591225.mp4

**Comment by davetgc** [comment]
Hi, sorry, I'm not sure what we're supposed to see here. Could you please show the patrol points and a longer video.

**Comment by RajMaha1** [comment]
https://user-images.githubusercontent.com/107326667/186265094-2e55cba4-e365-429a-a52d-6730c4254fae.mp4

**Comment by RajMaha1** [comment]
Yeah it is

**Comment by RajMaha1** [comment]
Can someone help me with this i cant continue progress once this is fixed sorry for being impatient

**Comment by davetgc** [comment]
This has been flagged and will be looked into. No development work takes
place over the weekend, as the team needs a rest sometimes :).

**Comment by RajMaha1** [comment]
Could i add with walk away script its not working properly as well should create a new issue

https://user-images.githubusercontent.com/107326667/187196073-74432103-e6cd-414d-9512-0b55d1ec627f.mp4

**Comment by ZakJudges** [comment]
Hi @RajMaha1, apologies for the late response. I have not been able to reproduce this issue. There have been a couple of fixes to the character behaviors in recent months. Do you continue to experience this issue in the latest experimental build on Steam? Thanks :)

**Comment by ZakJudges** [comment]
Hi @RajMaha1, are you happy for this issue to be closed?

**Comment by CharleneMaure** [comment]
Yes
