### ISSUE TITLE
GameGuru Classic storyzones: videos require a 'click' to finish

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#3630]
When using storyzones in the latest GG Classic update, the videos hang on the last frame and require a physical click of the mouse from the player to end.

Simple to replicate:
![GGC_storyzone](https://user-images.githubusercontent.com/60984223/185703129-23f8be80-35c2-4a2c-86d8-efe24ca3646c.jpg)

What I'm seeing in-game:
https://youtu.be/8UbQxwMj3PQ

**Comment by davetgc** [comment]
Hi Lee, this could affect some of our current plans?

**Comment by LeeBamberTGC** [comment]
I do not see this bug affecting any plans in place, would be good to know if this has been in for a while or a recent change so the bug can be narrowed down.

**Comment by AmenMoses** [comment]
It's not doing it with all videos btw.

The videobank/video.mp4 that comes with GG doesn't do this, but another .mp4 that I happen to have in videobank does.

**Comment by AmenMoses** [comment]
The operationamazon/intro.mp4 from the MAX videobank does show the issue however.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Yes I can reproduce this one, thanks for the extra info!

**Comment by LeeBamberTGC** [comment]
@AvengingEagle Fixed for the next update :)
