### ISSUE TITLE
Ai Enemy and Ally wont fight 

### ISSUE THREAD

**Issue by ruckupvr** [TheGameCreators/GameGuruRepo#3631]
I just did the update today, and all of a sudden my AI wont engage. I have one set to Ally and the other set to Enemy, Prior to the update they would automatically fight. Now they wont do that. Thank you for looking into this or advising me if it is user error. Have a great day

**Comment by Tam51** [comment]
I have found enemies won't engage in fighting Ally characters  but zombie enemies will fight ally zombies. That's what I have found out in my test. I was wondering if anyone else has come across this problem.

**Comment by synchromesh62** [comment]
Just gave this a try and seems to work fine for me ?
Any chance of a Video to see what your seeing ?

**Comment by ruckupvr** [comment]
All good now. I just deleted them and put them back in the game. It was obviously something I did but I dont remember changing anything... But it works now Thank you

**Comment by synchromesh62** [comment]
Problem with EA is things get updated and changed .. You may not have changed anything but the FPM map file saves a lot of info so you could be loading in old info before AI was updated.. 
Replacing the characters maybe just put it right. :)
