### ISSUE TITLE
Magic Button

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#3634]
Hi Lea & Team

Is there any chance that you can add a button in My Games  added to the Edit my game icon 

like this please  Edit Game.
                          Delete Game.

Thanks 
Snage66

**Comment by MonkeyFrogStudio** [comment]
Something similar already requested here:
https://github.com/TheGameCreators/GameGuruRepo/issues/2214

And here:
https://github.com/TheGameCreators/GameGuruRepo/issues/2087

**Comment by davetgc** [comment]
Hi, thanks for the comment, but this has already been mentioned. To help the team, please read or search for similar topics before posting. If you find one, you can comment there, which will help us to know which features are more important to our users.
