### ISSUE TITLE
reflection in puddles

### ISSUE THREAD

**Issue by vinurd** [TheGameCreators/GameGuruRepo#3638]
![2022-08-22_17-28-54](https://user-images.githubusercontent.com/32761694/185888705-1ea7c98b-5dcd-46b1-8f7f-5b6e005203cc.png)
![2022-08-22_17-25-24](https://user-images.githubusercontent.com/32761694/185888735-589ed138-d6fc-41d3-ab4a-428b27849ccf.png)
I decided to try a puddle in an open space.  nothing is reflected

**Comment by davetgc** [comment]
A similar issue has been posted here:  #2495. Please use search before posting an issue, so the team only has one report.

Many thanks,
