### ISSUE TITLE
Lightmapping rotates entities that have been rotated

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#364]
Hi if you place an entity on the map and rotate it from its drop point when you lightmap it rotates the entity can be seen clearly here https://youtu.be/qmcggUIhIKo

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Works perfectly for me using either "R" to Rotate or the Widget then lightmapping.
I noticed Preben self assigned this back then … Could he have already fixed it ?

**Comment by plemsoft** [comment]
@GraPhiX-Guru Yes it is a old fixed bug , will close it now, thanks :)
