### ISSUE TITLE
GameGuruMAX - Teleport bug

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#3641]
when you using the teleport the FOV will zoom after you are teleported.
Im using FOV 60 after i get into the teleport zone its zoomed to something about 41. for example
![GameGuru MAX - m7 fpm_ 22 08 2022 16_25_17](https://user-images.githubusercontent.com/109030026/185945994-208af421-8364-4930-a2cf-b59069540bfe.png)
![GameGuru MAX - m7 fpm_ 22 08 2022 16_25_37](https://user-images.githubusercontent.com/109030026/185946055-6348e093-38c8-4292-aef8-d1eaf76ca2a7.png)

**Comment by Tam51** [comment]
I just tried the teleport and I can't get it to work either

**Comment by LeeBamberTGC** [comment]
@Keepo1 Just tried this with the latest build and the TELEPORT script, all works fine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b6c51d30-c2bf-4bb7-9b5c-55dc6bee46b0)
