### ISSUE TITLE
runtime error 501:image number 96000 (loading main)

### ISSUE THREAD

**Issue by oliamit12** [TheGameCreators/GameGuruRepo#3644]
I get this message when trying to run a saved stand alone game.

**Comment by davetgc** [comment]
Are you using any custom image or image behaviors?

**Comment by oliamit12** [comment]
It's the imagepanel Behaviour. the images don't transfer to the standalone folder. Don't know if it's just me. I did use custom images, but it did that before I added them.

**Comment by Mishahhi** [comment]
The problem may already be solved, but I found the same error during level loading. The error was in the UAV (night vision device). Somehow the compilation of the project wrote another folder "imagebank", thus making them two folders, one with the files in it and the other with a UAV file that wasn't even there. 
I solved the problem by deleting the second folder, and the UAV image (mask) with the folder name "misk" from the GameGuru MAX folder moved to the folder "imagebank" in my project

There is a possibility that the problem will occur on other devices as well, haven't checked.
