### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3647]
Whenever I try to scroll through the Max Collection folder a box pops up with Runtime Error 7018 (See screenshot) and then crashes to desktop. This is the steam version

![Issue](https://user-images.githubusercontent.com/104730909/186191497-2454c319-dd1b-4026-8d12-e92ef38542df.jpg)

**Comment by Tam51** [comment]
It's working for me without any problems and I have the steam version. You could have a corrupted file. Have you tried un-installing the software and re-installing GGmax again.

**Comment by davetgc** [comment]
Do you have any imported media?

**Comment by Curiosityuk** [comment]
I think I’ve sorted it and I think you both might be right.

I have reinstalled with no issues and I’m reinstalling models one by one.

So at present it’s working. So thank you guys 👍

**Comment by DaveTGC2** [comment]
No problem, incorrectly installed media is known to cause a crash. While we are working to find all instances, it's a complex job.  If you find the offending model, please post back here so we can take a look at the cause.
