### ISSUE TITLE
GGMAX -  ZDepthMode Problem

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3649]
When beginning the GetEntityZDepthMode(e) reports Object as 1 for the zdepth mode (i presume this is the default)
everything seems ok

Setting the Object to SetEntityZDepthMode(e,2) changes the rendering perfectly to mode 2 as it should
but GetEntityZDepthMode(e) reports the Object as 1 for the zdepth mode even thought its status has changed.

Setting the object back to SetEntityZDepthMode(e,1) doesnt work it stays rendering at SetEntityZDepthMode(e,2)
and GetEntityZDepthMode(e) still reports the Object as 1 for the zdepth .

Even setting at SetEntityZDepthMode(e,0) - GetEntityZDepthMode(e)  still reports as the Object as 1 for the zdepth.

**Comment by LeeBamberTGC** [comment]
@Necrym59 I think we solved this a while ago, feel free to close if confirmed as fixed.

**Comment by Necrym59** [comment]
Yep my slackness in keeping up with closing stuff - done
