### ISSUE TITLE
GGMAX - Fog Commands not available in LUA

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3650]
Set Fog commands do not seem to be available as yet
 
SetFogNearest(v)
SetFogDistance(v)
SetFogRed(v)
SetFogGreen(v)
SetFogBlue(v)
SetFogIntensity(v)

**Comment by LeeBamberTGC** [comment]
NOTE: These commands currently exist, just broken in MAX.

**Comment by ZakJudges** [comment]
Hi @Necrym59, I have uploaded a new Steam experimental build which links the fog commands to the Wicked weather system. Could you let me know if the commands now work as expected? :)

**Comment by Necrym59** [comment]
Hi Zac works perfectly
great work Zac

**Comment by Necrym59** [comment]
This problem seems related
https://github.com/TheGameCreators/GameGuruRepo/issues/3650#issuecomment-1310878430

**Comment by Necrym59** [comment]
All works perfectly now
