### ISSUE TITLE
Trigger Zone Issues.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3652]
Can we please take a look at Trigger zones .. A big part or the attaching Behaviours etc
 They keep distorting when you click them and are just not stable. 
We really need them to adjust correctly and stay as we set them or its just frustrating trying to work with them.

**Comment by Rickaitch** [comment]
Confirmed in #3639 and assigned to Lee.

**Comment by synchromesh62** [comment]
Just an update on this im working on an indoor level and have the structure **locked.**
It is a better to adjust them if you have the structure **unlocked.** They play a little nicer :)
But still the other issues are making them very finnicky.

**Comment by Granada1** [comment]
I have the  same problem with my SiFi test level , locked or unlocked

**Comment by synchromesh62** [comment]
> I have the same problem with my SiFi test level , locked or unlocked

Make sure you also have this ticked ... It helps a lot.

![block](https://user-images.githubusercontent.com/35708217/187027530-3ca0bdbc-040c-4669-8c1a-58b4eb866199.png)

**Comment by Granada1** [comment]
Thanks 👍

**Comment by davetgc** [comment]
Duplicate, and Lee is aware. Thanks.
