### ISSUE TITLE
Transparency Issue On Model With 2 Materials. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3656]
Video showing issue: https://youtu.be/MNMC0PeBgKc

On my model I have 2 Materials, the first one is Glass and Transparency is ticked ON. The second Material is for the rest of the object and it has Transparency checked OFF. 

When I import the model everything looks good. When I select the model and place it into my scene everything looks good. However, once I press Test Game the entire model acts as if Transparency is checked ON for both the Glass and the second material. If I turn off the Transparency for the Glass and Test Game the model is fine. To me it seems like somehow the Transparency set to ON for the Glass is overriding the 2nd material having Transparency checked off.

**Comment by Kitakazi** [comment]
Ok I just noticed on the video at 42 seconds in when I exit Test Game. It is showing Transparency is ticked ON and the 2nd Material is selected. However before I hit Test Game the 2nd Material had Transparency set to OFF. Once I click on the model after exiting Test Game it goes back to normal.

**Comment by Granada1** [comment]
I’ve seen this also , it seems to merge into one when testing game

**Comment by Kitakazi** [comment]
I think this had something to do when importing the model with an older importer. I havent tested with this exact model but other models I had that also had this bug were fixed by re-importing the original FBX file. Closing this one for now unless I notice it happen with a new model when imported.
