### ISSUE TITLE
can't remove weapons

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3658]
really dont want anyone to have guns for this project and just can't seam to remove them.

![image](https://user-images.githubusercontent.com/68471279/187097360-2e204e63-9453-4429-a788-7a429f0913fa.png)

**Comment by ZakJudges** [comment]
Hi @casigus, are you happy for this issue to be closed now? :) The character creator now allows you to specify "No Weapon" for a character, and choose a behavior for them to use. Additionally, you can add <Unarmed> to a scripts description to force the character unarmed. Thanks!
