### ISSUE TITLE
GGMAX - NPC Enhancement

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3662]
Can an NPC have the ability to respond to an object that has been thrown at them like a flinch when hit with an object and if possible the effect of health reduction upon physical hits based on the force/mass of the object. This allows for things being thrown or dropped on them. For smaller items a flinch movement and small damage would suffice.

**Comment by synchromesh62** [comment]
That would be a fantastic addition to your throwing script :)

**Comment by AmenMoses** [comment]
The original pickuppables script has actual physics collision detection code that does damage to any entity hit by a thrown object.
