### ISSUE TITLE
hurt.lua is missing damage setting in-editor

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3664]
![Screenshot 2022-08-31 191949](https://user-images.githubusercontent.com/32545391/187751195-40c7862a-8ce0-4b85-b131-6505abc888ca.png)

**Comment by Necrym59** [comment]
[hurt.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9572538/hurt.zip)

Will that do it Zak

**Comment by ZakJudges** [comment]
@Necrym59 Perfect, thanks!

**Comment by ZakJudges** [comment]
@LeeBamberTGC Here are the files, ready for the build: 
[scriptbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9798651/scriptbank.zip)

**Comment by LeeBamberTGC** [comment]
@ZakJudges New script added for next build.
