### ISSUE TITLE
GGMAX - Destroy(e) command is not working

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3666]
The Destroy(e) command is not working so all ammo / health etc can be picked up intefinatley :)

**Comment by davetgc** [comment]
I've tested this and it seems to be working. Is anyone else having this issue?


https://user-images.githubusercontent.com/99803873/188110652-f65624fc-fd31-4e90-8959-ea4d20c80204.mp4

**Comment by Necrym59** [comment]
Ok i have found the problem, if the ammo is set to Always On, Destroy doesnt destroy it, its position will still deliver ammo forever when you walk back over it. Same for Health or any item that supposed to be destroyed that happens to have Always active ON (which is most behavior items) .

**Comment by davetgc** [comment]
Ok, that sounds like a bug.

**Comment by Necrym59** [comment]
Seems to be ok now
