### ISSUE TITLE
Behaviors

### ISSUE THREAD

**Issue by Haldogo** [TheGameCreators/GameGuruRepo#3667]
Only the Character behavior seams to be working. If Character is enamy they shoot you, if ally they follow you around. Any thing else they just stand there.
Thanks 
Tom Jones

**Comment by davetgc** [comment]
Hi, do you mean the Neutral characters? That's the default behavior. If you link them to flags, they will follow the path.  You can add additional behaviors to a character by adding another script, for example : Patrol and Speak.

I hope that's helped.

**Comment by Haldogo** [comment]
No Its the enamy and the ally. None of the other behaviors  seam to work

**Comment by Haldogo** [comment]
Good Morning  just checked. Only the enemy setting does anything. but the move close and speak behavior is working.
