### ISSUE TITLE
Strange water reflection

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#367]
I'm developing a script for a hovercar and noticed that the reflection from the water looks rather strange, can't really describe what is wrong but here is a video demonstrating the issue:

https://vimeo.com/288401227

Positioning of the camera uses the following commands:
SetCameraOverride( 3 )  -- once on entering vehicle

SetCameraPosition &  SetCameraAngle  -- every frame to track vehicle movement

In addition I use SetFreezePosition, SetFreezeAngle and TransportToFreezePosition to move the player character with the vehicle (although positioned above it so it doesn't interfere with the physics )

**Comment by LeeBamberTGC** [comment]
This looks like a bug where the reflection camera is not taking the override of the camera into account.

**Comment by plemsoft** [comment]
@AmenMoses Thanks for reporting this,

This has been fixed for the next update :)
