### ISSUE TITLE
GameGuru MAX - Request - Add Collision Mesh Collision Type to Importer

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3672]
I'd like to see the Collision Mesh collision type added to the importer so we can select it on import, not only after importing the model and bringing the object into our level. Currently, on import, these are the collision types made available to us:

![cm2](https://user-images.githubusercontent.com/36735507/188297320-672e5c40-03bb-4c7a-af68-9110788a47a4.png)

But after the model is imported and brought into a level, Collision Mesh is then made available:

![cm1](https://user-images.githubusercontent.com/36735507/188297330-27daecd1-8959-48db-974c-1c656212f824.png)

One reason I would like to see this added is I am making a model pack and most of the pieces use their own custom collision mesh that I've made for them. However, I cannot select Collision Mesh on import. As a result, none of the models will use that custom collision mesh, despite the FPE file's collision being set to 9, without the object first being brought into the level and the collision type changed. This means that if I give this pack to someone or sell it, the end-user will have to make these changes themselves for each object once they bring it into their level. If I can set this on import, then it will be set for the customer, too, and they won't have to make any changes themselves.

**Comment by Skevos-Mavros** [comment]
Is there any chance that "Polygon" in your first image is the same collision type as "Collision Mesh" your second image? I'm not in front of my PC to test.

**Comment by MonkeyFrogStudio** [comment]
@Skevos-Mavros No. Polygon is for polygon collision. When this is selected, it creates a collision mesh using every face of the object. It is the worst type of collision to use because most object meshes have a lot of faces. Collision Mesh was added specifically for using a custom collision mesh (a separate mesh created to be used just for collision). Here is an example:

![cm](https://user-images.githubusercontent.com/36735507/188345000-c490aba3-b3d2-46cb-b88d-4c8bdff125d2.png)

The object on the left is using Polygon collision. The object on the right is set to Collision Mesh and using a custom collision mesh that I had created for this particular model.

**Comment by Skevos-Mavros** [comment]
Ah yes, I remember that now. Thanks for the clarification! 👍

**Comment by ZakJudges** [comment]
@MonkeyFrogStudio Thanks for reporting this, I have added an option to specify "Collision Mesh" in the importer. Should be available in the next experimental build :)

**Comment by MonkeyFrogStudio** [comment]
Thanks for this!
