### ISSUE TITLE
GameGuru MAX - Bug - Object List not Working Correctly - Latest Experimental Build (9-9-22)

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3678]
The Object list is not working correctly for me. When I mouse over an object in the list, instead of it rotating, I get a grid:

![object2](https://user-images.githubusercontent.com/36735507/188743277-49fba421-243e-4bff-8523-399ed325a781.png)

And if I click to edit the object, I get a messed up area and the list for backgrounds becomes a list instead of images:

![object](https://user-images.githubusercontent.com/36735507/188743486-1269796c-ef33-4682-95fa-0a163a2679c7.png)

**Comment by Necrym59** [comment]
Can confirm similar when highlighted objects in the object thumbnail list i get a blank thumbnail plus if i go to change the thumnail look at object it crashes Max

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio @Necrym59 Thanks for the report. The EXP build this time is literally an experimental one. The faint-hearted should revert the latest public one which is the build before this one. Anyone crazy enough to keep moving forward, thanks for the help. I am assuming everyone has DX12 capable hardware and uses the latest (or best) drivers.

The first question, are the issues only happening with custom art or stock ones? If stock, please send me the location and name of the stock object in question, thanks!

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC It happens with both stock and custom objects. MAX is not discriminating here. :P

No worries  on it being a "true" experimental build. I don't mind testing. It's why I report like I do.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio All the ones I am using are fine, please send me the location and name of the stock object that mis-behaved, thanks!

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Found something interesting - if I run MAX full-screen, then the objects will not rotate on mouse over and, instead, I get a grid for the display there. But if I run MAX in a window, then the objects rotate on mouse-over. However, two more things - at full-screen, if I click the lower-right button to edit the backdrop, I get a messed up screen area (like in the second screen shot above). When MAX is windowed, when I click that same button, MAX crashes out.

Here are videos of both:

https://user-images.githubusercontent.com/36735507/188943447-75b04c5d-37aa-4d78-a2bb-d9fb69d5d8e3.mp4

https://user-images.githubusercontent.com/36735507/188943485-304e8902-403c-43ec-928c-5762129a24f2.mp4

The location of all these stock objects is in the MAX installation area under Steam.

**Comment by MonkeyFrogStudio** [comment]
BTW - In case it helps, here's my video card info:

Nvidia GTX 1080 ti 11GB VRAM, running the latest Game Ready drivers.

Screen resolution = 3440 x 1440.

**Comment by Necrym59** [comment]
As at GameGuru MAX Build 2022.10.14
Thumbnails do not preview rotate or generate new thumbnails
https://user-images.githubusercontent.com/95015657/198931484-7d722186-3bb0-4f2d-b229-330423451fd2.mp4

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio This should be resolved now we are back in DX11.1 land. Check the EXP build to see if this is the case, thanks!

**Comment by MonkeyFrogStudio** [comment]
Correct! It works as it should with the DX11 experimental. :)
