### ISSUE TITLE
Glaxy Seed .fx bugs

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#368]
Hi,

I used Build 2018.08.24 Monster Update (Public Preview). The following products are not working as standalone. (it works fine in the game guru test game section)

Glaxy Seed:

Glaxy Seed
Console (lights)
Corridor (siren amber)
Corridor (siren blue)
Corridor (siren green)
Corridor (siren red)
Corridor corner
Corridor t-junction
Corridor x-junction
Corridor

Standalone exe gives the following errors:
galaxy_seed.fx
siren_effect.fx
siren_effect2.fx
siren_effect3.fx

I think the fx files need to be updated for use in dx11.

**Comment by Pirate-Myke** [comment]
If you look into the stand alone build under the effectbank/galaxy seed folder, you will see that all the files do not get copied over.
https://puu.sh/BqBK3/1616b9ec8a.png
https://puu.sh/BqBJe/114a15bbb1.png

Copying the rest of the files over, then makes it work.
https://puu.sh/BqBNk/7567cd4815.jpg

Simple fix, but part of a larger issue, that is being addressed.

**Comment by plemsoft** [comment]
@sfkylcnky Thanks for reporting this,

This has been fixed and will be in the next update :)
