### ISSUE TITLE
add guide on how to add or replace the terrain texture ( texture paint library )

### ISSUE THREAD

**Issue by Nader-B10** [TheGameCreators/GameGuruRepo#3682]
add a guide on how to add or replace the terrain texture.. I mean the one in the texture paint library... since the import texture feature won't be added anytime soon and it's still far away
................................................................................................................................................
( I asked about this in yesterday's broadcast and Lee answered and told me to post this request here because he will forget )...thank you Lee :)

**Comment by GraPhiX-Guru** [comment]
Whilst not official you can have custom terrain textures but you have to replace current ones, this video will give you an idea you don't need my application if you use your own paint package that supports the file formats.

https://www.youtube.com/watch?v=FR9DDEWuyQE

new version https://www.youtube.com/watch?v=VkGfevKfcC0

**Comment by LeeBamberTGC** [comment]
@Nader-B10 In latest version, we have added the ability to specify a custom terrain texture folder :)
