### ISSUE TITLE
GG Enhanced Weapons Pack - visual glitches and performance issues

### ISSUE THREAD

**Issue by InquisitorKane** [TheGameCreators/GameGuruRepo#3683]
Hello,
I have bought the GG Enhanced Weapons pack and have a visual glitch with few weapons. When picked up, shows as on the picture attached, persisting also when trying to aim down the sights.

![GG-akm-visual-bug](https://user-images.githubusercontent.com/80776617/189138072-f406eb15-98bd-4cef-bcc1-9e6edbabe043.PNG)

Visually glitching weapons:

- AKM
- Shotgun
- Grenade
- Both pistols

**Also ever since I installed this thing, loading assets or ruinning a level (even simplest ones with one weapon, single enemy and one pillar) takes forever to load and stays on black screen for 3 minutes with no indication anything is happening.**

**Comment by DaveTGC2** [comment]
Hi, could you please post your system specs?

**Comment by InquisitorKane** [comment]
> Hi, could you please post your system specs?

Hello, here you go.

Graphic card is **GeForce RTX 2070 SUPER**
![image](https://user-images.githubusercontent.com/80776617/189188890-69e8c4fc-7502-4fbd-9f25-a4534247606d.png)

**Comment by cybernescence** [comment]
related to - https://github.com/TheGameCreators/GameGuruRepo/issues/3617

**Comment by Hamada880** [comment]
This has also been reported twice my other request was closed for duplicate. Not yet confirmed it was fixed. Hopefully it is coming on the next update.

**Comment by InquisitorKane** [comment]
I can confirm the issue has been fixed. Tried all the ranged weapons and graphics are working.

Thank you! :)
