### ISSUE TITLE
From Steam - Add Lua command to toggle always active

### ISSUE THREAD

**Issue by DaveTGC2** [TheGameCreators/GameGuruRepo#3684]
Hey Devs does this lua command already exist(cannot seem to find it on the global.lua file)?

If it does not exist can it be implemented?
like this
g_Entity[e]["alwaysactive"] = true/false

It is alright if this is not possible but would appreciate it if it can be implemented.

trying to squeeze out some extra performance with my custom spawner script.

Currently I'm working on a game that uses only one big level and it is loaded only once, wrote my own custom ai and custom spawner each time the player dones/fails the objective his position will reset and the npc's spawned will be different each time(No Level reloads).

My custom spawner has a list of nps that will be spawned each objective. what I want is to set those npcs always active to true via lua because my level is big.

and once my custom spawner despawns(Move the npcs far far away from the playable are) it will set those npcs always active to false.

Currently my fps goes around 40-60 fps with 32 npc's always active so having this LUA code implemented will be really handy for my custom spawner in terms of performance.

**Comment by Necrym59** [comment]
Are they set to Always active in the FPE already just as a side question?

**Comment by AmenMoses** [comment]
Use the activated field, i.e. change the AI scripts to check if activated is 0 and if so simply return.

Then your custom spawner set activated to 1.

**Comment by Necrym59** [comment]
g_Entity[e]['active'] =
g_Entity[e]['activated'] =

are available in lua i think
