### ISSUE TITLE
GameGuru MAX - Request - Add Import Button to Video Library

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3689]
Currently, when you access the Video Library, there is no option to import a video. There is only a button for using a selected video:

![video2](https://user-images.githubusercontent.com/36735507/189500596-afc0eeac-7c5c-434a-9517-706750e62aa8.png)

However, other libraries provide a button to import things, like sound files:

![video1](https://user-images.githubusercontent.com/36735507/189500624-5735d6c5-795a-4a65-a4b4-a32f058aa80c.png)

I'd like to request an import button be added to the Video Library, too.

**Comment by MonkeyFrogStudio** [comment]
Also reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3257

**Comment by MonkeyFrogStudio** [comment]
For consistency sake, all libraries (video, sound, etc.) should have the same import functionality to make it easier for the end-user to import their files. The end-user should not have to locate the proper folder and drop their stuff in there. MAX should do that heavy lifting for them via an import button (like with the audio library).

**Comment by davetgc** [comment]
Closed as duplicate. Thanks for reminder.
