### ISSUE TITLE
Lost audio playback of any audio 

### ISSUE THREAD

**Issue by IniquitoutPRime** [TheGameCreators/GameGuruRepo#3691]
From testing a game, to selecting a wav object in game. I've lost audio playback from FX to even audio added. Tutorials are fine in playback. I attempted to create a new game to see if it was a corrupt file. I still have any audio output when hitting testing. 

I 
Version 2022.08.19

**Comment by davetgc** [comment]
Is this happening with just one WAV file, or many?
