### ISSUE TITLE
Report from Steam .. You can only use one fadeinsound on a map.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3693]
Reported on Steam
Tested and confirmed.
If you place an asset with a fade in sound connected it works but any other assets with the same fadeinsound script added after do not seem to work.

**Comment by AmenMoses** [comment]
[fadeinsound.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9550726/fadeinsound.zip)

**Comment by AmenMoses** [comment]
Even better version:
[fadeinsound.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9550845/fadeinsound.zip)

**Comment by AmenMoses** [comment]
Did that fix the issue?

**Comment by synchromesh62** [comment]
> 

i linked it to the OP on Steam but no response from him yet.
https://steamcommunity.com/app/1247290/discussions/0/3374907062182406134/
