### ISSUE TITLE
Animated Skeleton

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#3694]
I got this Skeleton from Skecthfab for free, can any one help me with the animation please.

https://user-images.githubusercontent.com/39164408/189754937-5fd0de62-2e60-4bce-95db-edb17d658d77.mp4

**Comment by MonkeyFrogStudio** [comment]
This place is for reporting bugs and making feature requests, not for asking for help. That should be done on the forums or Discord channel.

**Comment by Snage62** [comment]
My apologies for this, but you should have more respect for the customers who are paying your wages.
