### ISSUE TITLE
Firing Full Auto Into Zombie Will Freeze its Animation

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3696]
Video: https://youtu.be/i-fwnLz0Uw8

Fire full auto into a Zombie and it freezes its animation. I believe it used to play multiple hurt/damaged animations when being shot by full auto weapons.

**Comment by davetgc** [comment]
Hi, could you please post your system specs and if possible, make a video of the issue.

Thanks.

**Comment by Kitakazi** [comment]
19 seconds in the video link from the 1st post. When firing full out into the zombie it freezes in whatever animation frame it is currently in untill the player stops firing or the zombie dies.

**Comment by Kitakazi** [comment]
@davetgc 

I have fixed this issue kind of.  But here is a better video showing the problem.  In the video I set the zombies HP to like 50,000 and gave myself like 50,000 bullets in one clip. As you can see full auto completely locks up and freezes the Zombie. 
https://youtu.be/5oCuRR8KlVc

By removing "Always... Stop Animation" From the logic box in the Damaged State of the Zombie Attack Behavior I think it feels much better and no longer completely freezes the zombie. Here is a video showing my "fix."  

https://youtu.be/qm6MsNJwp4g

You can find this Logic Box in the Damaged State.
![image](https://user-images.githubusercontent.com/51464873/195023721-10774466-23ec-4427-a8ca-5b3bcb658a3c.png)
