### ISSUE TITLE
When behaviours are updated to 'insert' params, any level using old param layout are corrupted

### ISSUE THREAD

**Issue by ShadowMasterOfGames** [TheGameCreators/GameGuruRepo#3697]
@LeeBamberTGC As you have asked, I am opening this issue about the Hostage Behavior. 

Some of my characters have the hostage behavior attached but yet they stand there pointing like they have guns, and the ones that are actually on their knees, you cannot release them.  

You already have my level and all characters are Max. However, I will attach some videos and screenshots sometime today when I get on my computer or tomorrow at the latest.

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames Thanks for creating the new thread :)

**Comment by davetgc** [comment]
@ShadowMasterOfGames - Are you able to make a video showing this issue?

**Comment by ShadowMasterOfGames** [comment]
I will make a video as soon as I can

**Comment by ShadowMasterOfGames** [comment]
@davetgc i will try my best to get a video up but lee should be able to reproduce it since he has my level, if I need to send more files for that level, I can

**Comment by davetgc** [comment]
@ShadowMasterOfGames - Well, that's clearly not a good thing :)

Can you please post your full system specs?

Secondly, are you using custom media? Can you please post your metrics in game (Press TAB in game). so we can see what's happening.

**Comment by ShadowMasterOfGames** [comment]
@davetgc why remove the behavior tag? this is about the hostage behavior which is the main issue, I just explain that I cannot take a video of the hostage behavior not working because I cannot do anything in test lvl since my fps is crap. I could open another issue for the Frame Per Second problem but it is all tied to the same lvl

**Comment by ShadowMasterOfGames** [comment]
@davetgc, @LeeBamberTGC FINALLY, and after getting motion sickness (crappy fps) here is the long waited video of the hostage behavior NOT working Please do not ask for another video from Test1.fpm lol not sure if my nerves can handle it lol

I can send you the custom items that I use in that lvl if you need them to reproduce the issues. I will say one thing, it makes the game extremely hard to shoot with 2fps to 8fps lol just saying lol now for the video we have all been waiting patiently 

https://screenrec.com/share/4GXc6zvTCV

**Comment by ZakJudges** [comment]
@ShadowMasterOfGames This should be fixed in the next experimental update. Find more details here: #3737

**Comment by ShadowMasterOfGames** [comment]
@ZakJudges, I am going to check tomorrow Saturday the 17th, I was involved in a three vehicle accident on December 13th, 2022 where I was pinned between two cars. So I will let you know by Monday at the latest, if that is okay

**Comment by ShadowMasterOfGames** [comment]
@ZakJudges btw it not that my held weapon as much as you cannot release them, which was still going on in the last build I checked was Friday the 9th but will recheck it with the newest release and get you answers by Monday

**Comment by ShadowMasterOfGames** [comment]
@ZakJudges nope they still will not leave, only one out of eight hostages actually ran away as my new improved video shows, and still 3 are holding weapons. Not fix yet!!! 

New video December 17th, 2022
https://screenrec.com/share/m0V3pJaFWu

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames I knocked up a level with the latest EXP build with 8 hostages from the stock assets and they all got released when I ran up to them:

[Hostages.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10254144/Hostages.zip)

Can you load this FPM level and let me know if you see the same thing, as that would discount the engine and the characters and the script, so we can then determine why your version differs.

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC the one that ran away on my level, I did change the behavior to something else and then switched it back, so maybe I will have to switch all the hostages behavior with another behavior and then switch it back to get the editor to read the new hostages behavior?

I know a lot of people was complaining about Max not refreshing behaviors, could that be what is going on in my case the old hostages behavior is not being refreshed to the updated version?

if so, I can live with that for now but there is always going be updates to behaviors and no what how old a level is, it should read the update files for the behaviors or anything for that matter and I have also ran the verification of files through steam twice before I made my last video. I know that no DX11 bug are being fixed right now just the main editor bugs because of the on going DX 12 merge in the background.

However, I think (it possible) Max really needs to have a refresh system built in so people will not have to switch out behavior to get the update behavior to work. I will try my best to get on Monday and swap out the old hostages behavior with something else. Then swap it back to hostage behavior and see if Max reads the new update version. 

Thanks again for looking into this issue @LeeBamberTGC

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC after reinstalling twice, verifying four times, and finally switching from Sunday experimental and swapping out each hostage behavior with another behavior and then back to hostage behavior only 7 out of 8 hostages ran away, the farm decide to stay as a hostage even though I told him repeatedly to go home. 

Here is the video, by the way, thank you for making the combats behavior smarter, They are kicking my butt now lol I can fully say with comfit that the combat behavior is working extremely well  

p.s. seems Sunday experimental is broken, every time that I try to load in test level or game it crashed. Max fully shut down every time.

https://screenrec.com/share/E7zPq3mhvt

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC I sent you my **test1** (again) in one email, and my **scripts** in another one and trying to send you my custom characters and my custom assets

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames The TEST1 level is pretty strange. It seems you have made your characters LOCKED for your hostage, and also sometimes set to ISIMMOBILE=YES.  Looks like your characters have been set to fail big style :)  Ensure they are first dynamic, unlocked, set to ENEMY of the player, then change the behavior to stand and speak, then back to hostage and you should be fine with corrected settings:

![image](https://user-images.githubusercontent.com/35840583/208433893-0b249928-a228-4cd3-af8c-fc61d79ef616.png)

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames Your level did show some other issues that helped however, so watch out for a new EXP build in an hour or so :)

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC  Thanks for your help with my level, since my three car accident (which I was pinned between two cars), I have been able to sit to long to do much with Max. Thanks again

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC The hostage behaviors work but now got to do the same thing for ammo and health behavior, they only work after you swap them out for something else and then back which is a pain. Is DX11 causing these issues or is this another behavior bug that I need to open another issue for?

Got to be a way for Max to figure out that there is an updated behavior or a way to refresh behaviors without swapping behaviors. People might start to complain if they got to do each behavior for each item. There got to be a better system for behaviors, especially if there are updates to them.

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames Most of the time updates will automatically work with the object, but when params are inserted during a script update, things can get messy. For now, we are making sure new parameters go on the end of the behavior so future corruption can be avoided. We really need a system to preserve param values, even if their order or config changes,

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
