### ISSUE TITLE
Boat Behavior 

### ISSUE THREAD

**Issue by PalmTree11** [TheGameCreators/GameGuruRepo#3698]
It seems the boat behavior is not working properly. When I hit E to embark, I end up submerged in the water

**Comment by Necrym59** [comment]
Your settings are not correct for the boat
In the general section
- Set Physics=ON
- Affecteby Gravity = OFF
- Collision Shape=Polygon
- Alwas Active=ON
- IsImmoble = YES
then it should fine

**Comment by PalmTree11** [comment]
Thanks for your fast reply Necrym59. I followed your directions exactly and still ended up with the same result.  Then I tried it on a different map and it worked fine!  Not sure what happened but glad it is working. Thanks for your help!

**Comment by Necrym59** [comment]
Sometimes Max holds onto things, usually if you delete the offending object inthis case the boat, then save the map then reload and put a new boat in with the settings above it most probably would work , but im glad it you sorted it out.

**Comment by almusx** [comment]
Set Draft to 0, other values than 0 the character get out of the boat.
