### ISSUE TITLE
Shaders - Decal Animation Shader (CRASH)

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#37]
One of the decal animation shaders crashes and freezes Game Guru and has the ability to crash whole systems. This is an issue that is experienced by only 25% of the community, so it may have to do with video card make or video card settings.

Experienced by Windows users of Windows 7 and Windows 10

The shader that is causing the freezing and crashes is located:
effectbank\reloaded\decal_animate4.fx

Decals that use it are fire and smoke in the Decal folder. I personally have not tested the other decal animation shaders to see if they cause the same problems. 

Related forum threads:
https://forum.game-guru.com/thread/219065
https://forum.game-guru.com/thread/219051
https://forum.game-guru.com/thread/219025
https://forum.game-guru.com/thread/219175
https://forum.game-guru.com/thread/219244

**Comment by plemsoft** [comment]
Fixed in latest branch.
