### ISSUE TITLE
Importing models freezes GameGuru

### ISSUE THREAD

**Issue by Tony1965** [TheGameCreators/GameGuruRepo#370]
Hi.

I've just installed Gameguru after doing a new install of windows 10 and for some reason every time I select import model GameGuru hangs and I have to click on the close [x] button a couple of times to get the import dialog box up.

Regards
Tony

**Comment by LeeBamberTGC** [comment]
Send me the model you are trying to import at lee@thegamecreators.com and I will see if I can reproduce.

**Comment by LeeBamberTGC** [comment]
Can you make a small video, as it sounds like you are not getting to the part where you select a model file from your PC?

**Comment by Tony1965** [comment]
After hours of messing around trying to sort the problem out I eventually found the problem.
It was my SSD drive, I've replaced it with a HDD drive and GameGuru is running much better than it did before. Strange only Gameguru was effected?
