### ISSUE TITLE
Play Animation Appears Not To Be Working

### ISSUE THREAD

**Issue by jasailor** [TheGameCreators/GameGuruRepo#3700]
I have created a character via  Character Creator and added "sitting" from the Animation Booster pack by loading the animations to the bottom of the animations created with the character creator.   I then add the character to the level and change the behavior to "Play Animation" and proceed to attempt to add the sitting animation but it unfortunately is not in the drop down list.   If I just add random animations from the drop down list shown it doesn't recognizes the provided animations and just plays random animations.  

Not sure if it is a bug or I missed hearing some trick buried in one of the videos.   No way of telling if there isn't referenceable description or spec as to how it should be working. 

This issue was also mentioned in a previous couple of issues but an answer wasn't provide for either.   

Please let me know if more information is required.   Thank you.

**Comment by davetgc** [comment]
Hi, Could you make a video please of the process you're using, so we can compare what you're doing to what should happen.

**Comment by jasailor** [comment]
[Video for Issue 3700.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9627822/Video.for.Issue.3700.zip)

Davtgc,   Here is the mp4 video.   Let me know if you need anything else.    Looking forward to your response.\

Jasailor

**Comment by jasailor** [comment]
DaveTgc,    Perhaps you could just send me the steps that are needed to do what I described and I could try them as well.

Thanks 

JASAILOR

**Comment by jasailor** [comment]
Davtgc,

I have uploaded the video a week ago and haven't heard anything.  Is this what you needed?  Please confirm!

Jasailor

**Comment by jasailor** [comment]
I uploaded the video over a week ago.   Is it sufficient to determine what is going on?   Please confirm.   An alternative is to give me a list of steps I need to do to accomplish adding the animation play behavior to the character.  Thanks much!Regards,JASailorOn Sep 22, 2022, at 2:39 AM, davetgc ***@***.***> wrote:﻿
Hi, Could you make a video please of the process you're using, so we can compare what you're doing to what should happen.

**Comment by davetgc** [comment]
Hi, Thanks, I didn't notice the video at first as it was  a zip file. Thanks for that.

For future reference, you can upload a video directly to GitHub, which will make it easier for others to find it,

**Comment by jasailor** [comment]
Rookie mistake.  😬  ThanksRegards,JASailorOn Sep 30, 2022, at 11:54 AM, davetgc ***@***.***> wrote:﻿
Hi, Thanks, I didn't notice the video at first as it was  a zip file. Thanks for that.
For future reference, you can upload a video directly to GitHub, which will make it easier for others to find it,

**Comment by jasailor** [comment]
David,Recommendations for getting added “animations  to play”  with the “Play Animations” behavior?Also,  can I get the code to access the Beta Tab on Steam?  Regards,JASailorOn Sep 30, 2022, at 11:54 AM, davetgc ***@***.***> wrote:﻿
Hi, Thanks, I didn't notice the video at first as it was  a zip file. Thanks for that.
For future reference, you can upload a video directly to GitHub, which will make it easier for others to find it,

**Comment by jasailor** [comment]
David,

Any update?

Jim

**Comment by jasailor** [comment]
David,

Is this issue being considered?    Has there been any progress?

JASAILOR

**Comment by davetgc** [comment]
Hi, Sorry for the lack of response.

I'm passing this one up the chain now, I'm not sure if it's a bug, or just needs more explanation. :).

**Comment by Kitakazi** [comment]
same thing happens for me. Its not just the Play Animation behavior but I don't think any extra, chosen animation is getting saved to the characters at all. I made a character and then added the "situp" animation from the booster pack, when I go to the Behavior Editor and try to make my own script to play it, it does not show up at all.

**Comment by LeeBamberTGC** [comment]
@jasailor Will be fixed in next EXP build :)

**Comment by jasailor** [comment]
Lee  B., Dave. C.Thank you!   It now works as I believe you intended.   Have a great holiday!Regards,JASailorOn Dec 10, 2022, at 12:19 PM, Lee Bamber ***@***.***> wrote:﻿
@jasailor Will be fixed in next EXP build :)
