### ISSUE TITLE
Game guru feature Request - Ideas -4

### ISSUE THREAD

**Issue by Ethansprow** [TheGameCreators/GameGuruRepo#3701]
May you make a jump scare and transform  that to a enemy behavior? I know there’s going to be a behavior to behavior feature but Using that I was thinking probably going be weird Also can you make a dodging behavior with Melee enemies and the player and maybe there can be setting how far you can go with dodging?

**Comment by davetgc** [comment]
Thanks for your comments. Please name you requests clearly, e.g.  Add dodging, and please only add one request per post. In addition, please check that requests haven't already been added. I'm closing this for now, but ask that you make separate feature requests.

Many thanks,
