### ISSUE TITLE
GG Max - Bug - New WINKILL behaviour - Counts Foxes and Dark Foxes as enemies on enemy count

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3702]
I have just tested the WinKill behaviour, and found that it counts the Foxes and Dark Foxes as enemies when displaying the enemy count.

I have fish on the map i tested it on, and they are not part of the count.

.

**Comment by AmenMoses** [comment]
Did you try setting them as 'neutral' or 'ally'?

I think by default characters are set to 'enemy'.

**Comment by Tum1370** [comment]
@AmenMoses Yes that was the problem.
All the foxes were set at enemy, After changing them all to Neutral it works fine.
Really the foxes and animals  should automatically be set to neutral ??

I will close this issue as this problem is not the WinKill behaviour.

Thanks
