### ISSUE TITLE
Importer not calculating size properly

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#3703]

**Comment by RajMaha1** [comment]
![Untitled](https://user-images.githubusercontent.com/107326667/190470490-ae2ba7ff-7b78-43df-800a-6b530c589521.jpg)

**Comment by DieselDaveFB** [comment]
I would like to add more info to this issue. It would appear that the importer is not properly scaling models to each objects exported scale and units of scale (Metric CM/Meter and Imperial/Inches) I have created 3 very short videos showcasing the issue as it's easier to show than to describe specifics.

https://www.youtube.com/watch?v=9oyviRaOEgU

https://www.youtube.com/watch?v=A9jqAEsWbFQ

https://www.youtube.com/watch?v=BBSKeSTun1Y
