### ISSUE TITLE
Player flash light behavior request!

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3704]
I know it is possible to disable the flash light at the beginning of game but turn it back on using behavior not possible or maybe by picking up an object like flash light would allow the player flash light turned back on.

**Comment by synchromesh62** [comment]
The good news is a behavior for this (and more) has already been created.
The bad news is it has not been added yet.
Even so its great to know it is on the way :)

**Comment by Hamada880** [comment]
That is good and bad news as you said. Hopefully it gets tested and added soon since GGMAX will be the ultimate horror game maker engine.
