### ISSUE TITLE
Gameguru Max - texture issue

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#3706]
the textures changed in engine are set to defauld texture after standalone render.

**Comment by ZakJudges** [comment]
Hi @Keepo1, thank you for reporting this issue. I have uploaded a new experimental build to Steam with a fix :)

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
