### ISSUE TITLE
GameGuru MAX - Bug - Multiple Particles Don't Work in Current Experimental Build

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3708]
If you drag in more than one particle into a scene, only the last particle will work. In fact, if you have several particles and each one has a different particle effect, when you drag in the last one, that one particle will display several particle effects as if there were more than one particle on top of each other.

![particle2](https://user-images.githubusercontent.com/36735507/190687573-049ed599-eaee-404f-990d-ea08e24b3202.png)

It doesn't matter how you create the additional particle (dragging in a new particle, selecting a current particle and dragging in a new one from the Current Objects area, or using SHIFT+Click to duplicate), only the last placed particle works at all. And even then, it can be a mess (as pointed out above, the last placed particle may display multiple particle effects).

**Comment by Necrym59** [comment]
I can confirm this,  i had the same when i created a green gas particle and a smoke one appears in the middle of it
![particles](https://user-images.githubusercontent.com/95015657/190840568-2b62f644-49db-4aa1-ba23-b215a63ede1d.png)

**Comment by Tam51** [comment]
I have the same problem. Also collectable count objects don't work

**Comment by MonkeyFrogStudio** [comment]
Just tested again with the latest experimental build and it's still not working (same as in the first post).

**Comment by 3coms** [comment]
GGMax_EXP 2022_10_07 updated

https://www.youtube.com/watch?v=TpbAahOm82Q

**Comment by Tam51** [comment]
Particles are still not working on the new update. I had to go back to 2022.08.19 to get them work again. I've been waiting for this to be fixed I hope it will be fixed soon.

**Comment by LeeBamberTGC** [comment]
@Tam51 There are a number of glitches thanks to the DX12 work, particles doing silly things being one of them. Stepping back to the early build is the ay to go. Should be finished soon with the DX12 work and Wicked Merge, then we should not have this kind of disruption on the new foundations for some time after :)

**Comment by Ohneiros** [comment]
It's a really weird problem. For me it started last update with all particles showing some weird green dots around them, which only went away when I deleted all of them (around 20 in the whole level). Since then, every time I insert a new particle, all the previous ones stop working. On re-start, sometimes they'll work, but not always. I hope this is somehow helpful.

**Comment by davetgc** [comment]
This is still an issue with the latest public build, so I'm posting to bounce it a bit.

**Comment by LeeBamberTGC** [comment]
@davetgc Is it fixed in the latest EXP build? We reverted to DX11 which unbreaks the particle system :)

**Comment by MonkeyFrogStudio** [comment]
It's fixed in the latest experimental builds.
