### ISSUE TITLE
GameGuru MAX - Bug - Stand Alone Doesn't Run with Latest Experimental Build

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3709]
As the title says, running the EXE generated by the stand alone simply crashes out the game (it never starts).

**Comment by Technodweeb** [comment]
I am experiencing the same issue.

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, I wasn't able to reproduce this one. Do you still experience it in the latest experimental build? :)

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges This is an old one relating to the DX12 experimental version. Once you all went back to the DX11 version, this went away.

**Comment by Technodweeb** [comment]
This has cleared up for me as well..
