### ISSUE TITLE
Massive frame drops in GGCLASSIC after the latest public preview update.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3710]
I'm experiencing massive frame drops close to 18 fps after I was getting sold 120fps in a new scene.

**Comment by 3ofSpades** [comment]
Newer isn't always better. Try reverting to the June update. And tagging the app manifest file for gameguru as read only in your steam library directory. You can stay on an older version that works and disable updates.

**Comment by Hamada880** [comment]
Yes, I'm revert back to the older update just needed to report the issue to make sure it's reported for later fix. I also will update this issue once I get the latest update.

**Comment by Teabone3** [comment]
I am not experiencing the same. What is your GPU/Video Card?

**Comment by Hamada880** [comment]
I'm notice another steam update and I have two graphic cards intel and Nivida GeForce Rtx 2070

**Comment by Hamada880** [comment]
Intel running GGClassic drops the frame rate, however nivida run it in much higher frame rate and after Sept 14th update I don't have the same issue. Just wondering why it runs sometimes using intel rather the the Nivida card.

**Comment by LeeBamberTGC** [comment]
@Hamada880 Is it happening with latest public release?  No other reports similar to this?  I assume reverting to June release helped.

**Comment by Hamada880** [comment]
After the latest update no. I also dedicated GGclassic to run on Nivida. I'm try same test for the intel and see if I'm experiencing same frame drop.

**Comment by LeeBamberTGC** [comment]
@Hamada880 Can you step back through the Classic update public releases and identify which one as fast and which next one was slow running the same demo level (or blank new scene).   With this, I can look at the Classic change log and identify what might have caused it.

**Comment by Hamada880** [comment]
I will be more than happy to do that. Currently we have massive power outage in Fl. Will update you with the needed info.

**Comment by Hamada880** [comment]
Here is what I found:
-June fixes 2022  runs at 24 fps still experience a few frame drops when the laptop runs the software using intel,on The latest Public preview is the lowest fps and it's about 15 fps.However,March fixes 2022 is much better and smoother with 25 fps compare to June fixes 2022. 

I changed the preferred card from Auto to Nvidia and now I'm getting back sold 120 fps on new scene with the latest public preview.

**Comment by LeeBamberTGC** [comment]
@Hamada880 Are we calling this one as closed as the frame difference between 24 and 25 between versions is within expected results, and your solution to force use of the NVIDIA to get 120 fps sounds like you are on your way :)

**Comment by Hamada880** [comment]
Much appreciated the efforts Lee to look and help users using GGclassic as well.
