### ISSUE TITLE
Behavior - "Seccam" does not work correctly

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3713]
I attach this Behavior to my entity. 
I have the Physics = On, Immobile = Yes, I also have Visibility in the Behavior settings set to Visible. 
I press Test Game and the entity has vanished.

**Comment by Necrym59** [comment]
Physics = On
Immobile = Yes
Affected by Gravity=On
Works perfectly here

**Comment by Kitakazi** [comment]
Setting entities Strength higher than "1" fixed this issue.
