### ISSUE TITLE
Gameguru Max - Bug - Binoculars and Night vision scripts zoom when they shouldn't

### ISSUE THREAD

**Issue by imeyefly** [TheGameCreators/GameGuruRepo#3715]
I found an issue with the binoculars and night vision scripts. When you first pick up the binoculars, the players field of view gets zoomed in a little bit. Even before pressing the button to use them. But that particular bug only happens the first time you pick them up after starting GameGuru Max. You need to restart the software to get that bug again. The second bug with them is that after you use them the players field of view doesn't get reset correctly. It stays zoomed in to what I believe is the Min Zoom distance like you are still using them.

To test it, I looked at where the edge of the screen was before and after I picked them up. And also the same test before and after I used them. And you can see the fov is zoomed in when it shouldn't be.

**Comment by Necrym59** [comment]
This has been fixed and should be in the next update with any luck asnd is here if needed sooner
[nightvision_v11.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9596804/nightvision_v11.zip)

**Comment by imeyefly** [comment]
Awesome! Thank you. You rock!

**Comment by UltraVox001** [comment]
Hell all,

I couldn't find the original post for the Nightvision plugin, so I'm posting a small problem here :

On a French keyboard, the Player moves in the 3D environment with the ZQSD keys.

Z = Advance
Q = Left side
S = Back
D = Right side

So moving left (Q key) with nightvision On, turns Off nightvision.
Please rectify to the best of your ability. :)

Thank you.
