### ISSUE TITLE
Blackout 3D Editor screen?

### ISSUE THREAD

**Issue by Dr-Colosso** [TheGameCreators/GameGuruRepo#3718]
I've reloaded my GameGuru Max onto my new computer. It opens and runs, but the 3D Editor screen is all black. I've reinstalled it twice and added more ram, but its still messed up. Are there any users or developers able to help me figure this one out?

**Comment by earthling45** [comment]
If you have an AMD RX card, see this thread.
https://github.com/TheGameCreators/GameGuruRepo/issues/3444

**Comment by MonkeyFrogStudio** [comment]
It would be very helpful to the developers if you'd provide your system information (Windows version, CPU, video card, RAM, etc.).

**Comment by Dr-Colosso** [comment]
Processor: AMD Ryzen 5 5600G with Radeon Graphics 3.90 GHz
RAM: 16.0 GB (15.3 GB usable)
System: 64-bit operating system, x64-based processor
Windows 11
Video: AMD Radeon RX 6400 w/8

Hope this helps. I tried some older drivers, but it still isn't working.

**Comment by davetgc** [comment]
This sounds like an AMD issue, thanks for reporting. Could you please add this issue to this thread. It helps the team if users can search for their issues and update existing threads, Thanks.

[#3444](https://github.com/TheGameCreators/GameGuruRepo/issues/3444)

I'm closing this one for now to avoid duplication.
