### ISSUE TITLE
grassbank - Some vegetation not showing in palette.

### ISSUE THREAD

**Issue by MissShadow69** [TheGameCreators/GameGuruRepo#3719]
when in the engine i am missing vegetation even tho they are in the grassbank correctly. all of the grass ones are missing. (not the flowers, just the grass itself) how do i fix that.

**Comment by MissShadow69** [comment]
![grass](https://user-images.githubusercontent.com/76533235/191897928-912babda-845f-41bc-ba51-026cad9c2800.JPG)
![grass2](https://user-images.githubusercontent.com/76533235/191898081-857f4726-eda9-42ac-ad55-8022d52bf02d.JPG)

**Comment by davetgc** [comment]
Can anyway else replicate this issue?

**Comment by MissShadow69** [comment]
nope not that i have found. it just wont show them

**Comment by MissShadow69** [comment]
...update please

**Comment by LeeBamberTGC** [comment]
@MissShadow69 Can you zip up your whole GRASSBANK folder and send to lee@thegamecreators.com  Thanks!!

**Comment by Technodweeb** [comment]
After yesterdays update, Dec 9, I no longer have plain grass options in my palette either.  Just flowers.

**Comment by LeeBamberTGC** [comment]
@MissShadow69 Was able to select and draw grass in the latest EXP build:
![image](https://user-images.githubusercontent.com/35840583/207033874-3ebd9e1e-ea4f-41e4-9abb-8d497c90223b.png)

Has the grass bank folder been manually changed in any way as file corruption might cause what is described.

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
