### ISSUE TITLE
MAX -  forcing "user" folder usage

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3720]
Seems the DX12 version forces the use of the 'user" folder, at least for scripts.

Can we drop this approach - what is the point of it.

MAX still finds all scripts inside the "scriptbank" folder, as they work if already linked to a model in earlier versions, but no longer shows them in the "behavior" window for selection in DX12 version.

However, if you move all your scripts into the "user" folder they no longer work when attached to a model in previous build.

It is not just that it Breaks existing maps, but it is just not necessary to force the use of the "user" folder anyway, as the "custom write area" is already a user folder.

It would have been better to have proper Project Folders from the getgo.

Thanks for considering.

**Comment by thor49** [comment]
Hi OldFlak
I thought this when I tried the DX12 version..
but then found you can see the scripts when you select  [Purchased ] selection in the Behaviour window..
I am not forced to change to the user folder.
Hope this helps..

**Comment by OldFlak** [comment]
Yes, but none of my stuff is purchased - tis all custom made by me

And it never used to work that way before, so it got broken along the way

Current DX11 experimental has inherited the same issue

**Comment by Kitakazi** [comment]
It was not like this a few builds back. Not sure why it was changed but it's really annoying and hard to search for scripts. Going to "purchased" then clicking a folder sometimes sends the 'Behavior Library'  back to the default Objects folder for some reason. I dunno it's really broken at the moment. It used to just show all folders in my scriptbank in the Behavior Library which was perfect.

**Comment by OldFlak** [comment]
I have just resigned to the fact that it works best if everything goes in the 'user' folders for each section
tis a ton of work to start moving everything over especially all my models, as it also means rebuilding every level, and reassigning every script.

So tis kinda start from scratch for me - but as the catch phrase is 'early access' any cries fall on deaf ears :)

Soldier on then ....

**Comment by LeeBamberTGC** [comment]
Not deaf just busy ears :). Bumping this

**Comment by LeeBamberTGC** [comment]
@OldFlak In the latest EXP build, I added a new script into the HORROR folder of the writables area and it correctly aggregated it into the behaviours from the non-writable root scriptbank:

![image](https://user-images.githubusercontent.com/35840583/208250396-2094cdae-0f40-42af-840e-edb7981fbc99.png)

Can you describe your issue based on the above, i.e. where do you place your script files that they are not shown in the behaviour library view?  One small issue is that you need to exit and relaunch MAX when adding scripts to the writables as it does not auto-refresh like the Purchased folder does sometimes.

**Comment by Kitakazi** [comment]
The Behaviour Library View is only showing the default folders and does not show any other folders with scripts in them that are made by the user.  Try and create a new folder in the scriptbank called LeesFolder and put a script inside and it will not show the folder.  

For w/e reason it shows other user made Folders under the "Purchased" section. But it's buggy and when you select a folder while viewing them under Purchased tab it resets the users folder selection and goes back to the default view.

**Comment by OldFlak** [comment]
Hi Lee :)
Thanks for the bump - like I say I have gone down the path (quite some way already) of using custom folder for everything and rebuilding maps accordingly now. Tis a bit of work but will only result in a cleanout along the way :)

I do realize there are far more pressing things to get sorted :)

For the benefit of others, and sorting this thread out, I will attempt to show the issue in more detail.

Try making a new folder named mygame in the root folder and place a bunch of scripts in it:
scriptbank\mygame\script1, script2, script....

What you will find is that they do not show up when you go to object library unless you select 'View all' or 'Purchased'

On the other hand, if your custom folder has a subfolder with same names as default it will show those scripts when the corresponding default folder is selected.

The main problem is when you have custom folders outside of the user folder:
Hopefully this little video explains better what is happening:
https://youtu.be/OXMdVcqrHAs

Regards

**Comment by LeeBamberTGC** [comment]
@OldFlak New EXP build now uploaded that will show all your custom script folders in the writables scriptbank. Happy Christmas!!

**Comment by OldFlak** [comment]
Thanks Lee :)
