### ISSUE TITLE
GGMax DX12 version - Trying to use Character Creator Max crashes to desktop.

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#3721]
GGMax DX12 version when I press the Character Creator button I get Runtime ERROR 5103 then
get rid of error box and Max crashes to Desktop.

**Comment by davetgc** [comment]
Can you please post your system specs. Many thanks,

**Comment by thor49** [comment]
PC Spec :- 
	Intel Core i7-4790 CPU @ 3.6GHz
	16.0 GB DDR3

	NVIDIA GeForce RTX 2070  
	8.0 GB

**Comment by Tam51** [comment]
I have the same problem with Character Creator same error message 5103

PC Specs:
Intel i5 11600K CPU 3.9GHz
48 GB DDR 4
NVIDIA GeForce RTX 3060 12GB

**Comment by LeeBamberTGC** [comment]
@thor49 Big update happening now with the DX12 build. More changes than I had planned, but will work out for the better I am sure. Will let you know when you can try out the new DX12 build :)

**Comment by thor49** [comment]
Yes the Character Creator is now working in DX12 on my computer...

Thanks for your great work.
