### ISSUE TITLE
GGMax DX12 version (experimental) Particles are still not working.

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#3722]
GGMax DX12 version . 
1. ADD Particle (you either get a particle showing or you don't)
2. Goto Particle section choose other particle type. ( same as above it either shows or does not)
3.  If you do get a particle to appear. ( on some of them you get extras)
4. Extras - you get the particle you choose plus random other particles appearing at the same time (in the same place)
5. PLUS - sometimes these extras appear a great distance from the original that is still showing 
6. They also appear as rapid firing particles firing horizontally into the distance.
7.  some of the effects are quite impressive if you could get them on demand. mind blowing..
8. (I have gone back to use public preview version)

**Comment by ramraider2k6** [comment]
The GGMAX particle editor exporter appears to show correctly but in game the animated particles (not rotation but particles with multiple frames in are not being honored. You get a strange moire effect in place of the texture animation

**Comment by davetgc** [comment]
Thanks for the report, but this has been reported here: #3708

Please check what others have posted before reporting as this helps the team to quickly locate bugs. Please feel free to add information to the reports of others.
