### ISSUE TITLE
Behavior "Stand And Speak More" Is Broken

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3723]
Stand And Speak More - does not work correctly. Tested on build 8.19 and latest experimental build. 

1. I set this behavior to my character. 
2. Set Number of Speaks to 4. 

I expect the character to say each voice line from the Speech boxes. 
Instead she only says 1 voice line. Selecting "Use E key" does nothing, character still only says 1 voice line when player is in range.

**Comment by davetgc** [comment]
Hi, are you able to supply a video or a map file demonstrating this?

**Comment by Kitakazi** [comment]
Video: https://youtu.be/mGuA0F2O2C4

Only plays 1 voice line instead of multiple voice lines. The character on the right has "use E key" selected but using the E key does nothing.

**Comment by Kitakazi** [comment]
I believe this is fixed now.
