### ISSUE TITLE
GGMax DX12 version - Levels with lots of AI are very slow at least half speed of the DX11 version.

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#3724]
GGMax DX12 version - My level has 40 AI doing battle RPG swords. 

1. In the DX11 version my level has FPS 50 - 72 .
2. In the DX12 version my level has FPS 22 - 24

**Comment by davetgc** [comment]
Hi, please can you post your system specs?

**Comment by thor49** [comment]
PC Spec :- 
	Intel Core i7-4790 CPU @ 3.6GHz
	16.0 GB DDR3

	NVIDIA GeForce RTX 2070  
	8.0 GB

Extra Info..
If I delete 12 characters from my level...
DX11 version move up to FPS 52-74 very little.
DX12 version  moves up into FPS 40-45 very big move up.

**Comment by thor49** [comment]
More Info..
DX11 version non AI levels FPS 65 - 75 depends on complexity.
IDX12 version non AI levels FPS 75  solid very impressive. immediately noticed improved speed when I first ran it.. 
Then when I tried my AI level and the huge drop I could not believe it. ??

Also my AI are mostly not Character Creator models but store bought characters...(monsters, guards, swordsmen)
and some of the old models from FPS/Classic days. Guards on Horseback, skeletons

I am also using my own AI scripts.. 
Has the DX12 caused some problem with the path finding code. Has Lee changed something due to DX12.. ?

**Comment by davetgc** [comment]
Ok, that sheds some more light on it. Can you please pack some of the characters and the AI behaviours and forward them to Lee, (or post here if you can share), so that they can be tested.  At present character importing isn't supported, so there could be a lot of issues causing slow downs.

**Comment by thor49** [comment]
Hi Dave 
Thanks for the heads up..
So I deleted all my non standard AI models and only used the Aztecs. ( over 40 in total)
still using my AI control script system..
DX11 version - FPS hi 60's - 74 
DX12 version - FPS hi 60's - 75
so only a couple FPS either way between the 2 systems... 
big relief its not the AI path finding code... 
So you can mark this report as completed ..

I will do some more tests and searching,
to track down the problem models.
Then I will make a new report something like.. 
DX12 may effect some non-standard character models..

**Comment by davetgc** [comment]
Thanks. I'll close this for now, but if you can find what issues the older characters have, please let me know. We might be able to improve performance in those areas.
