### ISSUE TITLE
GGMAX Bug: Pressing a weapon slot key (that is not empty) while doing a melee attack will not change to another weapon but will redo the melee attack (allowing for spamming)

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#3725]
Here's a video showing it, I don't think I was very clear with that title :/ I am just spamming the number 1 key after doing a melee attack.

https://user-images.githubusercontent.com/112423658/192037009-f2a73ec0-e384-47d9-abdf-2c5f1b85fa90.mp4

**Comment by ZakJudges** [comment]
Hi @waterdrinkingfox, thank you for reporting this issue. A new EXP build is now available on Steam with a fix :)

**Comment by waterdrinkingfox** [comment]
Yup, it's fixed! Thanks :)
