### ISSUE TITLE
GGMAX - Sub Folder import not working

### ISSUE THREAD

**Issue by ramraider2k6** [TheGameCreators/GameGuruRepo#3726]
![image](https://user-images.githubusercontent.com/9202717/192097113-57496993-77ae-435a-9083-fb44be3aaeb0.png)
You can not import to a subfolder under the User folder. You are given the option to do it though.

**Comment by MonkeyFrogStudio** [comment]
Not sure why this is not working for you. I import to a sub-folder under the user folder all the time. Having said that, which "user" folder are you trying to import to? Are you trying to import to the install directory (i.e. where GameGuru MAX is installed in Steam) or the actual user area (Documents>GameGuruApps>GameGuruMAX>Files>entitybank>user)? You should always use the one in your Documents are as this will not get altered or overwritten by updates.

**Comment by davetgc** [comment]
Hi, can anyone else confirm this?
