### ISSUE TITLE
GGMAX: Test level mode takes too long to start on large maps

### ISSUE THREAD

**Issue by korodai** [TheGameCreators/GameGuruRepo#3727]
If one entity is placed in the lower left corner of the map and one entity is placed in the upper right corner, it takes close to ten minutes to enter test level mode each time. GG Max becomes unresponsive until finally test level mode starts.

This is on a forest map with the largest editable area selected.

**Comment by davetgc** [comment]
Hi, can you please post your system specs?

Can anyone else confirm this?

**Comment by MonkeyFrogStudio** [comment]
Yes. It seems to happen here. If I create a 5k map with the forest biom and place a single object at one corner and anther object at an opposite corner (so, the further points or thereabouts), when you press Test Game, it takes a long, long time to generate. I wasn't willing to wait 10 minutes, so after several minutes, I force-quite MAX.

**Comment by synchromesh62** [comment]
The problem here is by placing and object in each corner its generating a complete 5km Navmesh rather than generating as you create your level.

**Comment by MonkeyFrogStudio** [comment]
Of course. However, I did this with the desert biom and it took less than a minute (didn't time it). With the forest biom, it was many minutes in. So, regardless, it seems like a heck of a long time to generate the nav mesh. Especially if you change something and MAX has to do it again.

**Comment by korodai** [comment]
> Hi, can you please post your system specs?
> 
> Can anyone else confirm this?

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz

Operating System Version:
    Windows 10 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce RTX 3070
    
Memory:
    RAM:  16303 MB

Storage:
    Number of SSDs: 2
    SSD sizes: 1050G1000G
    Number of HDDs: 0

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Idea ?
At the moment the navmesh is generated by the assets placed on the map (hence corner to corner) but what if it was generated by the player?
For example a 1km radius around the player ... that would certainly knock the Navmesh generation time down and maybe optimise the maps a little.
Maybe a daft idea but you never know :)

**Comment by fearlesswee** [comment]
@synchromesh62 I could have sworn they already switched to a tile-based generation? If not this should absolutely be added; generate a navmesh around the player and load them in, then generate more navmeshes for tiles surrounding the player as they move around in the background

**Comment by korodai** [comment]
Maybe add an option not to generate a navmesh until ready.
