### ISSUE TITLE
Gameguru Max - Bug - Ladder Respawn Bug 

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3728]
If you die while climbing on a ladder you will respawn on the ladder instead of checkpoint or Player Start Position. Randomly came across this while play testing my level I was able to easily reproduce it in this video. https://youtu.be/8F3Bs_-saDk

**Comment by ZakJudges** [comment]
Hi @Sinergygames, apologies for the late response. 

Thank you for reporting this issue.  I have added a fix which should be in the latest experimental build :)
