### ISSUE TITLE
Black Screen in Editor

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#373]
Im getting a black screen after changing terrain to Mars2, and then going back into the editor, unresponsive, can click to see drop down menus but they are not responding.

**Comment by LeeBamberTGC** [comment]
Can you provide a sceenshot (or even better a video) showing this scenario as I cannot reproduce it from the information I have at the moment, thanks.

**Comment by tarkus1971** [comment]
Have tried again but I also cannot make this happen again, maybe a random glitch.

**Comment by LeeBamberTGC** [comment]
If you post again, a good step by step would help me reproduce and fix it. Thanks for the report.
