### ISSUE TITLE
Question from Steam forums ... Roadmap? Also suggestions.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3730]
Do you have any outlined plan on what's coming up? When the program will become official? I'd love to see a roadmap of what you're going to do to the engine.
I got Game Guru classic through a humble bundle a million years ago, and all the DLC through future bundles. I honestly found it lacking, only able to really make a FPS with it.
I'm liking how much better Max works and hope I can use it better than classic. I like that you have plans on making puzzle games and RPGs as a standard practice in the engine whenever you get around to it.

Stuff I'd love to see implemented:

A way to access scripts INSIDE of the engine, even if it's just a button to open the folder (SO I don't have to do it through steam) - making a slightly easier workflow.

Modular script chunks - A way to piece scripts together to better customise actions, behaviour, or create fully custom stuff with minimal programming. (I did get codeworks made by an indie dev to help me with visual scripting, but something similar built in that already knows the calls it needs to make would be very nice.)

Skeleton re-targeting so I can import models or animations from elsewhere and make it work.

Modular building parts - you have some pre made buildings, which is nice, you also have the legacy builder thingy which works well enough, but I'd love to see you put in floors, walls, windows, doors, etc that I can just put together as I see fit (maybe windows with built in bool info like what Blender currently does with its archmesh addon.)

A way to right click and delete items I put in the objects tab and ended up not wanting to use.

A way to delete characters I created and don't want to use.

Drag and drop importing from folders.

Better comments in your code (What absolutely everything does, so we know what to modify if we want to make our own branches from your code). -ALTERNATELY- A master list of ways to override your code and plug in our own stuff.

An auto import of Game Guru classic DLC that's already in our steam library.

A way to modify and create our own HUD system (take out the "Oh this is a game guru game..." reaction from players who see the bog standard game guru heath and ammo HUD.)

Reverse the way you have your context sensitive interactions programmed. (Instead of clicking Shooter game, then drawing a line from thing to thing, you draw a line from thing to thing, then pick the behaviour from an on screen drop-down). -QOL upgrade.

An in-engine way to change statistics and items without needing to import each one, or to do it from the object menu instead of needing to place the thing in the scene before being able to change the stats. (Range, damage, ammo, etc.)

Change Damage Multiplier to Damage number, and let us put in numbers instead of using a slider.

I'd love for you guys to make a set of physics based dice that can talk to whatever they're linked to and tell said items what number they rolled. (RPG system booyah!)

A way to Customise how water behaves. (No underwater actions (Only swim on the surface), Die on touch, Swim, etc.) Also you need an under water shader to change how the game looks under water.

Platformer game mode! -I see plans for puzzle and RPG game modes, but nothing for platformers. I want logic to jump on things heads, or a way to make it a side scroller without experimenting with the camera for hours. (Also customisable player character).

Loot dropping behaviours, with a customisable loot table. (Add to player inventory, eplode on to ground, move along the ground toward player, etc.)

Ways to preview how your built in scripts will run before loading them into the level (enemy behaviour, weapon stats, voice clips etc.)

A way to program plants, grass and foliage before painting it into the world (how it blows, can I cut the grass? Will it flatten when stepped on? Will damage destroy it? Etc.)

Projectile weapon behaviour - your ray-traced gun is cool, but I want bullets.

This is about all I can think of for now. Some of this I haven't seen even in GGClassic.

Thank you for taking your time to read this, and I appreciate any consideration you put into any of these things that I'd love to see.

**Comment by AmenMoses** [comment]
https://vimeo.com/754859012

"I'd love for you guys to make a set of physics based dice that can talk to whatever they're linked to and tell said items what number they rolled. (RPG system booyah!)"

Did that years ago and it still works in MAX!
