### ISSUE TITLE
If you set the spotlight radius to 180 exactly, then the light does not show in the editor at all

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3731]
I've made floor tiles for interior levels that work like this:

![shadow3](https://user-images.githubusercontent.com/36735507/192578874-3fd37124-9d0a-4818-bb48-480f0447496e.png)

![shadow4](https://user-images.githubusercontent.com/36735507/192578895-fcc10759-fa1a-4e54-bd74-66aa37175176.png)

So, each tile uses the same material, of course, and is used over and over again to build corridors, etc. However, this has revealed an issue with MAX and lights/shadows. If I place an object on ONE of the floor tiles, depending on the angle of the camera/view, the shadow cast by that object will appear on OTHER floor tiles that use the same material:

![shadow](https://user-images.githubusercontent.com/36735507/192579504-c1f1e401-2ca0-4a5b-baa3-6a81d91020e2.png)

In the above image, you can see the edge of a barrel placed on the floor and you can see it's shadow on the floor tile next to it. If I were to keep walking so that the barrel is out of sight, that shadow, from the barrel, would pop up on the next floor tile after the one you see in the image. It would keep showing up on each floor tile as I move (with the camera at that angle).

![shadow2](https://user-images.githubusercontent.com/36735507/192579781-0b7013fd-fe25-4894-be5c-7328f51d9403.png)

In this example, I've placed a loose floor panel on the floor. Again, it's shadow is cast on the adjacent floor tile.

**Comment by MonkeyFrogStudio** [comment]
Found the issue! I was using spotlights and had the Spotlight Radius cranked up to 200 to get more of a radius of effect (trying to more simulate area lights). The large radius caused the errant shadows. Turning the Spotlight Radius back down to 160 for each spotlight made the extra shadows go away.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio I have switched this to a feature request as I am sure you might have liked to keep your range and still have quality shadows :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC It's not a feature. It's a bug. If you have a spotlight RADIUS (not range) turned up too high (more than 180 or 200, etc.) then shadows end up in the totally wrong place. As shown in the screen shots above, the shadows from the barrel or loose floor panel are nowhere near the object. This only happens when you crank up a spotlight's radius (not range) to something past 180 or 200 or so).

This is not a request to remove range (and has nothing to do with range at all). The simple solution is to cap the spotlight RADIUS to 180 since there's no need for a spotlight to shine ... well ... backwards, too.

**Comment by LeeBamberTGC** [comment]
Agreed

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Added cap in next EXP build to limit RADIUS between 3 and 180.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Just tested this and there's a small issue. If you set the spotlight radius to 180 exactly, then the light does not show in the editor at all. The spot light shows at 179 and lower, though.

![spot1](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/1f435f70-faff-41b9-a8ab-9693bfac761e)

![spot2](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/e007d2b3-99f8-471d-bf8d-934d86f1a51d)

If you run a test game with the spotlight radius set to 180, the spotlight will flicker on and off as the player moves. Set to 179 and lower, it's steady.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Set a blank scene with a chair and spotlight at 180 degrees, and the spotlight did show both in the editor and game:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/fc867609-7f8a-49c1-a425-24679fda68d1)
I did notice however the shadow disappeared between 175 and 180:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/d4917cf6-b06a-4424-aa91-1c70ac1577ae)
So I have set a new cap of 170 for spotlights for now, it's a limit of how these spot lights calculate shadows but at least users will SEE their shadows and spot light when maxed out:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0c1db208-6c66-47b6-a9e8-d8d6db37e3a4)
For the next EXP build.
