### ISSUE TITLE
Video Importer \ Browser Button Missing

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#3734]
Currently the only way to add your own videos is by accessing the Core of Gameguru Max, can we have an importer button, just like what the sounds have, where we select the file and hit import, we need that for videos as well, so we select a file and then hit import and use it in your game.

**Comment by synchromesh62** [comment]
Better still if the video we browse to is added to a GameGuruApps \ files \ Video \ folder 
So it does not need to go in the Max core for our own :)

**Comment by synchromesh62** [comment]
@davetgc 
Lee requested we post this on the Live Stream ... Really its neither an enhancement nor a bug as i Labelled it as really, it's a missing or forgotten editor control for an existing feature.
Right now, you cannot add your own videos to your game making the Video Zone pretty useless.

**Comment by davetgc** [comment]
@synchromesh62  - I was just trying to keep full on bugs away from the missing features, even from oversight. Lee should be aware of it as I've allocated it to him. He's pretty good on keeping on top of them.

**Comment by synchromesh62** [comment]
> 

Ahh ok no worries .. 
Just was not sure if you knew it was added by Lees Request. 
I just thought it may get bypassed as enhancement :)

**Comment by davetgc** [comment]
I've added bug back, just to keep you happy :)

**Comment by plemsoft** [comment]
@extremestrategy Thanks for reporting this issue, this has been fixed and will be in the next EXP update :)
