### ISSUE TITLE
GG Max - Bug - Black Window with demo games and New Game

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#3735]
Hello,

Since installing my new PC, I can no longer use GG Max. The program starts normally. But the demo game's are full black. There is nothing on the screen. Everything is black. The sound works. It's the same with New Games. Black screen from the start, including in terrain creation mode.

What to do ?
Thanks for your help.

Aztec Game screenshot : 
![aztec](https://user-images.githubusercontent.com/96718175/193091263-1fa4cc81-d548-4b77-a441-715c541a4758.png)
Full black, only the Life indicator appears at the bottom right of the screen.
----------
Config PC Windows 10 64 bit.
i5 12400F - 12 threads - 4.40 Ghz
64 Gigas RAM DDR5
Radeon RX 6950 XT with 16 Gigas RAM

**Comment by UltraVox001** [comment]
Screenshot for New game Level after terrain generating :
![NewGame](https://user-images.githubusercontent.com/96718175/193094847-3e76b0b5-b2c3-4ab0-bede-c19422a803f6.png)

**Comment by davetgc** [comment]
Hi, thanks for the report, and I'd advise using search in future as this issue has been reported several times.

Some AMD cards are having this issue and it is not directly MAX related, but connected to AMD drivers. Most people have solved this by rolling back/updating drivers until they find one that works.

We are working on a workaround, but as it's related to a 3rd party issue, it may take a little while to find a solution that suits everyone.

In the meantime, following my suggestion above should fix your problem, please let me know if it doesn't.

As this has been reported several times, I'll close this for now.
