### ISSUE TITLE
GGMAX - Light Issue

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3736]
There seems to be a mismatch in the angles concerning lights, in the example below a spotlight placed in the same y orientation as an object does not match in either the positional icon or actual light angle direction.
![ENTITYvLIGHT](https://user-images.githubusercontent.com/95015657/193163708-bb1779aa-4d7c-4e99-a0ae-4982e9c98b12.png)

**Comment by davetgc** [comment]
I can confirm this.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Dropped in torch and spot light, both with rotations of 0,0,0 and they lined up nicely:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/66502b96-9bf6-4e12-a5c3-d5e06d1673d9)

**Comment by Necrym59** [comment]
Excellent works nice thankyou
