### ISSUE TITLE
Weapons missing in Character creator

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3743]
Hi There I'm having problems with the Character Creator Plus in GGMax. When I go to select Character Details and try to select a weapon for the character some of the weapons are missing as you can see from the image below.
![image_2022-10-03_161531664](https://user-images.githubusercontent.com/93008801/193613480-00149fcb-f1af-44a4-80cd-e2b6ba475d3b.png)

has anyone else had this problem as I have tried re-installing GGMax and I still get the same problem. Any help

**Comment by davetgc** [comment]
Hi,

Have you tried validating the files via Steam?

Are the weapons available once a character has been placed, or available to be placed as pickups?

**Comment by Tam51** [comment]
Hi

I have tried validating the files via Steam still the same problem. Once I place a character it appears with a sci-fi weapon. I can change the weapon to the missing weapons but the character animation screws up like the walking animation and can't set it to idle even when its set to idle.

**Comment by Tam51** [comment]
Hi

I was wondering if this problem has anything to do with changing graphics card from AMD RX480 to GeForce RTX 3060 as I noticed a problem when importing objects. It was all cloudy until I went into the setup file and changed vsync=1 to 0

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
