### ISSUE TITLE
error 7018 - Legacy building editor.

### ISSUE THREAD

**Issue by ghost** [TheGameCreators/GameGuruRepo#3745]
![Screenshot (1310)](https://user-images.githubusercontent.com/58756931/193939249-2526bb81-a299-4160-ab65-14ce2b2f1569.png)
![Screenshot (1311)](https://user-images.githubusercontent.com/58756931/193939252-ae185e86-fedd-4d43-bb4c-ddde77857c47.png)
i used the legacy builder editor to make a room. i saved the room. it crashed. tried loading it back. this popped up and the room i saved turned into a small white cube.

**Comment by davetgc** [comment]
Hi,

I'm sorry that you're having problems. However, the legacy building editor is due to be replaced, and isn't officially supported, and so any bugs are unlikely to be fixed unless they break legacy support. 

Does anyone else have this issue?

**Comment by Tam51** [comment]
Hi I get another problem if I make a room with legacy building editor I can't walk in the room and if I place the player inside the room you just fall through the scene into water.

**Comment by synchromesh62** [comment]
> Hi I get another problem if I make a room with legacy building editor I can't walk in the room and if I place the player inside the room you just fall through the scene into water.

I really would not worry about it. 
With the imminent release of the new structure editor the Legacy builder is now pretty much redundant and is likely to be removed very soon.

**Comment by davetgc** [comment]
As @synchromesh62 has said, the legacy editor will be replaced soon, so any bugs with it are unlikely to be fixed as it will be obsolete.

**Comment by zirathashe** [comment]
i know its not going to get fixed. i just wanted people to know the bug existed. sorry for the trouble.

**Comment by zirathashe** [comment]
> Hi I get another problem if I make a room with legacy building editor I can't walk in the room and if I place the player inside the room you just fall through the scene into water.

this has only happened a couple of times. i eventually started raising the player start marker off the ground a bit and that seemed to help.

**Comment by davetgc** [comment]
@zirathashe - There's no trouble. Thanks for reporting. It's also possible that bugs like this will get fixed, to maintain legacy support, what won't happen is additions to legacy features.
