### ISSUE TITLE
 [ MAX ] Zombies and Animal stuck in idle animation on certain terrain.

### ISSUE THREAD

**Issue by tottieman** [TheGameCreators/GameGuruRepo#3747]
When I placed any zombies, any animals or enemy ai on sculpted terrain, some move, and others just stay in idle.

I tested on another terrain, and they move, so on some terrain they do but other they don't.

**Comment by davetgc** [comment]
Hi,

Can you please provide some more information. e.g. Which zombies/animals and which terrains? 

Are you able to provide a video?

Many thanks,
