### ISSUE TITLE
MAX - No standalone file encryption?

### ISSUE THREAD

**Issue by harkinhails** [TheGameCreators/GameGuruRepo#3748]
Working on a small test project, I exported a standalone to check and.. all of my purchased assets (audio esp.) were laid out in the open. So I ended up going back, ripping out any asset I paid for and now have to search for free alternatives, cause I don't want to get into legal trouble for handing out paid assets for anyone to CnP.

Is there a planned solution for this? A encrypted PAK file or something similar that can't be just opened/extracted using 7zip (probably something that requires a bit more effort for an average user) would be nice.

I know you aren't supposed to sell anything, but you can't even share a small test demo or something with anyone because of this issue. Where's the fun in that? Recording YouTube video is hardly a replacement, since performance is not good for my PC and video will look like laggy shite.

**Comment by synchromesh62** [comment]
@harkinhails 
Yes standalone encryption has not been added yet .. I mentioned before on the forums that because of this you have to be very choosy who you share your Custom levels with at the moment as they can use your stuff. Encryption will be added but probably at the same time the Splash Screen is removed is my guess.

**Comment by harkinhails** [comment]
Yeah, but I hope some simple packaging method is added before that.

Right now, I've decided to keep the custom assets in and just record a video in the future (no matter how laggy). It's just a test level anyway, doesn't have to be shared to be seen. But I can see it as a legal issue for those who do end up sharing standalone with licensed assets that don't allow such sharing (I think there should be a warning for that in editor when exporting a standalone).

**Comment by MonkeyFrogStudio** [comment]
This was already reported and talked about here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2442

But it's good that TGC is reminded of this. However, I am sure (at least I hope) it will come once development is a little further along.

**Comment by davetgc** [comment]
Not at the moment, but once V1 is out the door, we can look at things like this.

I'm closing this for now, and it's a duplicate.

**Comment by imothep85** [comment]
In 2024 it's still not in place :D
