### ISSUE TITLE
[MAX] Zombies dont start Feeding until the player sees them. (AI not starting until player has vision?) 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3752]
If you place a zombie and turn on "Feeding" in the Behavior settings the Zombie will not start in the Feeding state as you would expect, but rather is playing an Idle animation until the player has sight of the Zombie - Or the zombie has sight of the player. Then it switches to Feeding. 

https://youtu.be/cDhFlHRZpDE

This bug probably happens with other AI as well and other custom Behavior values I just wasn't sure what to title this post. As I discovered it with the Zombies. But I also tested with a custom character/animations and made a simple Behavior that if the "Feeding Box" is checked in, it should start with the "feeding" animation that I chose.  (I named the state Sleep in my custom script but same thing.) 

https://youtu.be/fGporkgiv7Q

As you can see the same thing happens with my custom character. It's like the AI script isn't actually starting until the player has vision of the enemy character and visa-versa. And although the video doesn't show it, I can wait for any amount of time and they won't start Feeding until player goes into sight of the enemy.

When the level runs the AI should start in the Feeding state since that is the very first thing the script looks for when it runs. Not really sure how both characters are playing Idle animations when the check for Feeding comes before anything would tell them to play Idle animations.  

Also I tried setting "Always Active" to ON to see if that would fix it but it did not.

**Comment by zirathashe** [comment]
ive had the simular issues with human ai where they T pose until you get within a certain distance. (in that case its not vision, but distance)

**Comment by LeeBamberTGC** [comment]
@Kitakazi In next EXP build, when ALWAYS ACTIVE set to YES the dormancy system is disabled so characters aware from start of level

**Comment by Kitakazi** [comment]
Fixed, closed.
