### ISSUE TITLE
Distorted full screen object library previews

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3757]
Hover over an object until the loading bar disappears and press "Fullscreen Preview" - the large thumbnail is distorted. Pressing "Fullscreen Preview" before the loading bar disappears does not show the issue. I also got a crash doing this but have not been able to reproduce it

Hover over an object in the Object library until AFTER the loading bar disappears and press "Fullscreen Preview" and then see the object distorted:
![Screenshot 2022-10-14 091814](https://user-images.githubusercontent.com/32545391/195798293-82aca005-cf2a-4c1a-a96e-05bddab74919.png)

Repeat the process for another object but press "Fullscreen Preview" BEFORE the loading bar disappears and the preview is fine:
![Screenshot 2022-10-14 091759](https://user-images.githubusercontent.com/32545391/195798257-dc822f72-0c79-428d-b2f0-4180cd85571e.png)

**Comment by MonkeyFrogStudio** [comment]
The object library has been messed up for some time in experimental:

https://github.com/TheGameCreators/GameGuruRepo/issues/3678

**Comment by LeeBamberTGC** [comment]
@ZakJudges This has now been fixed in the latest EXP build now we reverted to DX11.1

**Comment by ZakJudges** [comment]
Confirmed fixed :)
