### ISSUE TITLE
No Object Library Preview shown after importing object

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3758]
![Screenshot 2022-10-13 152258](https://user-images.githubusercontent.com/32545391/195798855-377ecc97-0604-4cac-beca-45c9df82bda2.png)

[Defeated.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9783951/Defeated.zip)

**Comment by MonkeyFrogStudio** [comment]
The object library has been messed up for some time in experimental:

https://github.com/TheGameCreators/GameGuruRepo/issues/3678

**Comment by ZakJudges** [comment]
This was fixed some time ago
