### ISSUE TITLE
Custom terrain textures are not copied over to standalone

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3759]
- change custom terrain texture folder
- save level and project
- Export standalone
- Play standalone and see no custom textures

**Comment by LeeBamberTGC** [comment]
NOTE: Possible related report here from Steam:

"I mean the original terrain textures.when I paint and save the terrain with the original textures, they are gone after reloading. But only the newly painted ones. All textures painted before the update are still present."
