### ISSUE TITLE
Standalone Save & Load Characters Glow bug

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#376]
Hi,

Try placing any of the characters listed below on the map and save as standalone. Run your game from the .exe you created. After you open your game, save it. Then, exit and re-open it. When you load your game from the main menu the character you have placed will glow unusually. I gave an example for Decayed 1 and screenshots are available below.

Classics\Characters\Freaks\Axe Brute
Classics\Characters\Freaks\Dante Beast 3
Classics\Characters\Freaks\Dogman 1
Classics\Characters\Freaks\Lobotomy 1
Classics\Characters\Freaks\Lobotomy 2
Classics\Characters\Freaks\Chainsaw Brute 1
Classics\Characters\Viral Outbreak\Decayed 1
Classics\Characters\Viral Outbreak\Decayed Twitcher 2
Classics\Characters\Viral Outbreak\Grendel 1
Classics\Characters\Viral Outbreak\Pincher 2
Classics\Characters\Viral Outbreak\Spiky 1
Characters\Zombies\Horror Zombie
Fantasy Pack\Characters\Desiccated Priest

![1](https://user-images.githubusercontent.com/37545408/45356712-be921280-b5cc-11e8-91e7-eae59efb28e9.jpg)
![2](https://user-images.githubusercontent.com/37545408/45356716-c356c680-b5cc-11e8-8a07-4214d40f35f3.jpg)

**Comment by Shahin3d** [comment]
Hi
I've also seen this problem.

Before saving
![snapshot24](https://user-images.githubusercontent.com/36647058/45928018-9948c100-bf49-11e8-9fa2-39b4dd577444.jpg)

After saving and reloading
![snapshot23](https://user-images.githubusercontent.com/36647058/45928023-a4035600-bf49-11e8-8140-761436d54087.jpg)

**Comment by synchromesh62** [comment]
Ok not mine are not getting as bright but something is going on ..
Perhaps this vid might help Lee ..
https://youtu.be/vS-qePyyVGk
