### ISSUE TITLE
Object tools menu disappears 

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3764]
- Select Terrain, Painting, Trees and Vegetation mode
- CTRL+I to open importer
- Object tools menu disappears and Level tools menu increases in size

https://user-images.githubusercontent.com/32545391/195817565-3b531e90-78b8-4987-9cfe-38a24768db0f.mp4

**Comment by ZakJudges** [comment]
Probably related to #3765

**Comment by LeeBamberTGC** [comment]
NOTE: Fixed many moons ago :)
