### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by XDeadcrow12** [TheGameCreators/GameGuruRepo#3766]
Could someone make a Western weapon and Gun pack for 
GG Max ?. it would really help for one of my projects.
I couldn't seem to find anything in relation of that nature
so that is why I am asking. if there is one already please let 
me know.

**Comment by Lemuripest93** [comment]
Additional content like this wont be added until MAX is in V2, basically once VR, RPG, Puzzle, as well as a slew of performance patches had been added the focus will return to enhancements and DLC and the like, so you've got to be a little bit more patient before things like these get added, i don't work for TGC or anything, this is just repeated information from the broadcasts on YouTube.

**Comment by XDeadcrow12** [comment]
I see. well I appreciate the information.

**Comment by Lemuripest93** [comment]
No problem :)

**Comment by XDeadcrow12** [comment]
On a side note do you know who to make
a complaint to as far as a bug in the system ?.
In GG Max every time I try to raise the Grass it will just
disappear completely. I am horrible with computer language
so when it comes to technical issues I have little to no idea
what I'm doing..

**Comment by Lemuripest93** [comment]
I'd recommend opening a new issue and labeling it a bug, for instance "GGM - Bug - Grass Disappears When Raised" something like that, then include as much information as possible, upload a video to YouTube (or any other video sharing website,) or video file to your post.

**Comment by synchromesh62** [comment]
> On a side note do you know who to make a complaint to as far as a bug in the system ?. In GG Max every time I try to raise the Grass it will just disappear completely. I am horrible with computer language so when it comes to technical issues I have little to no idea what I'm doing..

Right here and you have just done it :)
Ideally though the Devs need to be able to reproduce the issue especially if there have been no similar reports. 
A video of what you're seeing would be a great help if possible.

**Comment by davetgc** [comment]
As stated, please post bugs as a separate issue, clearly labeling the issue. Also, if possible, please supply a video of the issue.

I'm going to close this one for now and will allocate the new one once you post it.

**Comment by XDeadcrow12** [comment]
Glad i at least got it in there and Thank you
synchromesh62. I can try to make a video not
sure if it will work though.

I really don't like having to contact anyone
because I tend to even do that incorrectly so all I
can do is the best that I can.

like i said i don't really know what i'm doing
as stated.

I will however try to send issues separately
since two seems to be too much.

Have a good day.
