### ISSUE TITLE
Particles not working after update

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3767]
Hi The particles are not working in the new update. I'm going have to stick with 2022.08.19 version as particles are working in that version which means I won't have the building editor. Can someone please fix this problem as it's been a on going problem for awhile now.
THKs

**Comment by MonkeyFrogStudio** [comment]
Already been reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3708

**Comment by davetgc** [comment]
Closed as a duplicate
