### ISSUE TITLE
Standalone Save & Load Radar bug

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#377]
Hi,

Place a radar in a game and save it as standalone. Run your game from the .exe and save it from the in-game menu. Close and re-open the game and when you will try to load your previous save from the main menu the game will not load and an error will prompt. Screenshots available.

![radar1](https://user-images.githubusercontent.com/37545408/45356784-fef19080-b5cc-11e8-88e6-902fd180a2a4.jpg)

![radar2](https://user-images.githubusercontent.com/37545408/45356795-044edb00-b5cd-11e8-8882-dc9d23c62c6c.jpg)

**Comment by LeeBamberTGC** [comment]
PROPOSED SOLUTION: Fix the interoperability of the radar script so that it works as expected and resolve any crashing or errors that presently occur.   If you can provide an FPM of the level using stock media, that would help accelerate the fix, thanks!

**Comment by LeeBamberTGC** [comment]
Some lines attempted to access indexed entity data before it was ready, wrapped in safety code and now works as expected. Both loading save positions from the game and from the main menu.
