### ISSUE TITLE
October Update crashes Max Radeon RX 580 Series

### ISSUE THREAD

**Issue by oliamit12** [TheGameCreators/GameGuruRepo#3770]
Win 10
![Image1](https://user-images.githubusercontent.com/105463253/195921975-86ec2b76-34af-418b-a10c-92caf4917dec.png)
![Image2](https://user-images.githubusercontent.com/105463253/195921993-d8aaf071-14cd-448a-9c11-e2a1c1bf3cbd.png)
![Image3](https://user-images.githubusercontent.com/105463253/195922001-1e298d05-d87a-4faf-b95f-7cda3447c499.png)

**Comment by oliamit12** [comment]
![Image4](https://user-images.githubusercontent.com/105463253/195924768-8a57fb5e-1296-4d02-a45a-ae1720098ab5.png)

**Comment by oliamit12** [comment]
![amd issue](https://user-images.githubusercontent.com/105463253/195970747-32b29d32-5241-402d-a83d-fd390f39f006.png)

**Comment by davetgc** [comment]
Is this a MAX crash,or a AMD issue?

**Comment by AmenMoses** [comment]
This is the same issue Lee is looking at using the card he obtained from synchromesh.

**Comment by synchromesh62** [comment]
> Is this a MAX crash,or a AMD issue?

Yep Max bug for sure .. Lee is currently using my card ( which gave the same problem ) to solve the issue.

**Comment by oliamit12** [comment]
What more information do you need ? Is it from me or elsewhere?

**Comment by synchromesh62** [comment]
> Do you want more information from me ?

No Lee is actually testing an RX580 .. The problem is exactly as your message showed onscreen 
The Driver times out. You can roll back via Steam to the 2022-8-19 version though which will work perfectly until its sorted.
No key needed you just select it from the drop menu and it will auto update after a few seconds.
