### ISSUE TITLE
Gameguru Max - Bug - Gaping Infinite Hole In Map

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3771]
After the latest update there's a massive gaping hole in one of my test maps, which seems to stretch on for infinity - though it does actually end, but then you're just left falling in the void.

Video Demonstration: https://youtu.be/adIfo9G0HNE

I genuinely have no clue how this happened, or how to replicate it, but it may have appeared the first time i opened the Building Editor, though i'm not sure if that's the problem.

**Comment by Lemuripest93** [comment]
I think i found the issue, the hole appears in the map once you drop a building from the Building Editor into the map:


https://user-images.githubusercontent.com/104637906/195940091-09e71da0-99e4-46d1-affe-306b1fcfe269.mp4

**Comment by MonkeyFrogStudio** [comment]
Already reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3756

**Comment by Lemuripest93** [comment]
Woops, thanks for the heads-up, closing this one.
