### ISSUE TITLE
GameGuru Max - Bug - Building Editor - Shiny Walls And Texture Issues + more

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3772]
I've got some issues playing around with the Building Editor, which is great fun by the way - but there are some bugs to iron out.

Video Demonstration: https://youtu.be/XTuWc4HJSe8

Text Report: 

Bug 1 - The shiny walls, floors and ceilings. (high metalness?)

Bug 2 - Overlapping textures.

Bug 3 - If you create a smaller room on top of a larger room, the ceiling will bleed through.

These are all visible in the video, though stupidly i didn't focus that hard on the third bug, but it is visible right away as i go through the door of the large building the first time.

EDIT:

Bug 4 - If you decide to create a room, but then click away (when the white pillars/walls are highlighted in red), floors start disappearing, if you do it on the roof of a building, the editor crashes.

**Comment by Lemuripest93** [comment]
Bug 5 - Textures On Big Buildings Completely Bug Out

Tried making a medium sized apartment complex, ran into some pretty significant texture errors.

The results speak for themselves: https://www.youtube.com/watch?v=uc-ARe4M2to

**Comment by Lemuripest93** [comment]
Bug 6 - When you rotate a building made in the Building Editor, the warehouse type door does not close all the way when opened and then closed. (will update this if more doors start to behave strangely)

**Comment by Lemuripest93** [comment]
I will be doing some trials again later to see if i can recreate it, will be updating this post then, in the meantime i can tell you that it was a medium sized buildings (10 x 15 squares on the default grid setup) with 4 rooms [2 rooms divided into 4], the bug happened when i was making another room - changed my mind then clicked away, it removed two floor panels opposite of each other, i was curious then tested what would happen if i did it on the roof of the building - crashed the program.

Not sure if i'm able to recreate it, so again i will update this if i can, hopefully the additional details are of help, very strange bug.

**Comment by Lemuripest93** [comment]
Discovered a new bug whilst trying to rediscover the fourth one, please let me know if you're aware of this one already.

Bug 7 - When copying and pasting a building [Ctrl + C / Ctrl + V] it crashes the engine.

**Comment by ZakJudges** [comment]
@Lemuripest93 Thanks for the heads up, will try to get that crash fixed soon :)

**Comment by Lemuripest93** [comment]
Bug 8 - Building has added floor and overlapping textures in editor

Whilst Bug 5 is squashed, a new one has appeared in it's place. I made a motel type building yesterday, and when trying to retrieve it to test if Bug 5 had completely vanished... it seems to have added another floor on it's own, plus overlapping textures after doing the experimental build.

Video: https://youtu.be/Z_c4x92iRFU

**Comment by LeeBamberTGC** [comment]
@ZakJudges You might want @Lemuripest93 to separate issues into their own reports so we can tackle each one individually :)

**Comment by Lemuripest93** [comment]
@LeeBamberTGC Sorry man, thought it would clutter things up if i added tons of bugs on the main page, if i could be let known which ones have been fixed i'll add the rest separately later.

**Comment by ZakJudges** [comment]
@Lemuripest93 All of them apart from bug 5 and bug 7 need added. Thanks :)

**Comment by Lemuripest93** [comment]
No problem, will add them individually 👌
