### ISSUE TITLE
GG MAX Crashes when I start my levels

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#3773]
Hello,
I have a problem with the latest build. When I start my GGMAX levels it crashes after about 30 seconds without giving any error message. If I try to start a new project or try to open the demos they work, although there is a visible decrease in performance compared to the previous build.

PC SPECS: i5 10400f, GTX 1660 Super and 16GB RAM.

**Comment by davetgc** [comment]
Have you added any custom media?

**Comment by LukeTheLukeLTL** [comment]
> Have you added any custom media?

Yes, my levels have many models downloaded from the Internet.

**Comment by LukeTheLukeLTL** [comment]
For now I have solved the problem. If it happens again I will open another thread
