### ISSUE TITLE
Building Editor export creates hole and export folder not visible on first use

### ISSUE THREAD

**Issue by ksantiago1974** [TheGameCreators/GameGuruRepo#3776]
Hey guys, so I tried the Building maker/editor and after test building a house, and save it, it doesn't show on my object library. if you could help I appreciate it.

**Comment by Lemuripest93** [comment]
Try restarting Max, had the same issue, then after restarting it appeared - though it's a bit bugged right now and will create a hole in your map if you place the building down, just be wary of that.

**Comment by Hamada880** [comment]
I can confirm the bug that makes the hole in the floor. However building the structure is the best version so far.

**Comment by davetgc** [comment]
A library refresh feature is coming and has already been discussed internally.

**Comment by DieselDaveFB** [comment]
Yup, massive hole is formed when building is placed. I tested this with a building that had doors and windows and one without doors and windows to see if the boolean function was causing the hole.

**Comment by davetgc** [comment]
Can you please post a video or an image of the hole?

**Comment by DieselDaveFB** [comment]
yes

**Comment by DieselDaveFB** [comment]
https://www.youtube.com/watch?v=Dy78HoOearU

**Comment by LeeBamberTGC** [comment]
Thanks all, both are reproducible.

**Comment by LeeBamberTGC** [comment]
@DieselDaveFB Fixed this one in new EXP build, let me know if all is well :)

**Comment by LeeBamberTGC** [comment]
@ksantiago1974 Also, on a fresh install, MAX now creates the buildingeditor folder so exports work first time :)

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
