### ISSUE TITLE
Building Editor - Exported building creates hole in terrain

### ISSUE THREAD

**Issue by DieselDaveFB** [TheGameCreators/GameGuruRepo#3777]
When placing a building created with the building editor, the terrain, roughly the size of the imported building, lowers to the water level. This was tested with two types of buildings, 1 with doors and windows and 1 with only walls and no boolean operations added. Both produced the same "hole" in the terrain. Please reference linked video of the issue.

https://www.youtube.com/watch?v=Dy78HoOearU

Thanks, 
Dave

**Comment by MonkeyFrogStudio** [comment]
This was already reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3756

**Comment by LeeBamberTGC** [comment]
@DieselDaveFB Fixed this one in new EXP build, let me know if all is well :)

**Comment by DieselDaveFB** [comment]
I can confirm that in the EXP build the issues appears to be resolved :)

`Dave
