### ISSUE TITLE
Rotating Smart Objects causes child element rotations to corrupt

### ISSUE THREAD

**Issue by Jisafu** [TheGameCreators/GameGuruRepo#3778]
When rotating the building in GGMax editor and after play a test the building turn back to the original state and the doors and windows stay at the rotating point

**Comment by ZakJudges** [comment]
Hi @Jisafu, I haven't been able to reproduce this issue. Could you post a video that shows the issue occurring? That would give me a good idea of how to reproduce it. Thanks

**Comment by Jisafu** [comment]
Hey ZakJudes I hope this is clear enough, sorry for my english
![Test001](https://user-images.githubusercontent.com/105353315/196935800-24a4e089-c230-42ba-92ae-8a8cff1deb22.png)
![Test002](https://user-images.githubusercontent.com/105353315/196935890-d13a466a-796b-4a10-a0c2-2741d2f037ac.png)
![Test003](https://user-images.githubusercontent.com/105353315/196935924-9bf97d78-d3e4-4599-adcc-76cd8cd48bec.png)
![Test004](https://user-images.githubusercontent.com/105353315/196935978-4fa68d20-f0c8-469a-8ba5-87c853f1272f.png)
![Test005](https://user-images.githubusercontent.com/105353315/196936013-4c2ee310-5b25-4d8f-aff4-596e0dc812e8.png)

**Comment by Jisafu** [comment]
Hey @ZakJudges, picture 4 = Close play mode and turn the building 90°

**Comment by Jisafu** [comment]
Hello,
The enhanced photo 4

**Comment by Jisafu** [comment]
![Test004_2](https://user-images.githubusercontent.com/105353315/196952481-61511a94-72ac-4b98-88ed-380ec382d471.png)

**Comment by ZakJudges** [comment]
@Jisafu Thank you, I have now been able to reproduce the issue :)

**Comment by ZakJudges** [comment]
@LeeBamberTGC This seems to be an issue with rotation of smart objects:

- Place smart object (I used building editor building)
- Rotate the object using the "Rotation Angle Y" widget in the right-hand panel
- Click on the object again and see the rotation issue
- Does not happen when rotating object with the R key

**Comment by LeeBamberTGC** [comment]
@ZakJudges Thanks for that, was able to reproduce and is fixed in the next EXP build :)

**Comment by Jisafu** [comment]
Ok, Thanks

**Comment by LeeBamberTGC** [comment]
@Jisafu Further fixes for BE and importing smart objects, closing this but report back if not working in the latest EXP build.
