### ISSUE TITLE
Reference Issue#3768

### ISSUE THREAD

**Issue by andypmillard** [TheGameCreators/GameGuruRepo#3779]
You asked for my specs, see below.
TUF Gaming X570-PLUS mthbd
AMD Ryzen 7 3700x  8-core  3.59Ghx processor
16GB ram
Windows 10 Home 21H1 build 19043.2130 64 bit
Dual monitors both 1920 x 1080 and 24"
NVIDIA GeForce GTX1660  6GB
m2 Sabrent Rocket NVMe 4.0 SSD C: drive 931GB
additional HDDs 2 x 931GB , 698GB , 37GB

**Comment by MonkeyFrogStudio** [comment]
You should just add that information to that issue/thread instead of posting is separately so the devs don't have to go searching for it. :)

https://github.com/TheGameCreators/GameGuruRepo/issues/3768

**Comment by LeeBamberTGC** [comment]
Ala moved :)
