### ISSUE TITLE
Terrain texture keeps changing to grass

### ISSUE THREAD

**Issue by Emperor2000** [TheGameCreators/GameGuruRepo#378]
I have tried everything, but my terrain in a certain level keeps changing to grass. For example, I select death valley terrain texture, everything is fine. I save map and boom its back to grass, when I try edit it still says it's death valley, but it just resets to grass. Ive tried copying project, changing options, reimporting, I really have no clue on how to fix this.

**Comment by LeeBamberTGC** [comment]
Can anyone else reproduce this?  Perhaps you can make a small video so I can see the substeps you are taking, thanks!

**Comment by michaeloldman** [comment]
This was a problem we had on occasion using the old terrain system. I don't have Death Valley, but if it is the old format just delete the 'superpalette.ter' (terrainbank\deathvalley\superpalette.ter).

This used to get rid of terrain problems like you describe before.

Reliquia....

**Comment by synchromesh62** [comment]
A video or pics will help ..
Which version of GG are you using ?

**Comment by Emperor2000** [comment]
Newest version tbh i dont think the images would add any useful
information, it doesnt matter what i do, the texture wont be the right one
when i save it. When i press tab twice after saving it says i have death
valley (or anyvother texture) even though its just the default grass one.
Op 17 sep. 2018 16:40 schreef "synchromesh62" <notifications@github.com>:

**Comment by michaeloldman** [comment]
Hi, 
I haven't seen this problem for a long time now.

Have you verified the installation via Steam?
Did you try deleting the superpalette.ter just to rule that possibility out?

Sometimes more info can help others help you. Easy enough to provide images I would think....This way we can at least determine if it is a bug or something going on with your setup.

Reliquia....

**Comment by synchromesh62** [comment]
There are currently 3 versions available and without knowing which its harder to determine the fault so that very important .. It will tell you just below the Logo when loading .. Screenshots, vid will also help as well other wise all we have is .. "  level keeps changing to grass "
We cant really do much with just that info and we have no other reports of it here :(

**Comment by GraPhiX-Guru** [comment]
@Emperor2000 what is the version number of GG you are using? I had a similar issue a while back a long time ago, can you post a screenshot of your version please, I maybe able to help if its the same one

**Comment by Emperor2000** [comment]
Im using newest version, the monster update

Op do 20 sep. 2018 om 13:32 schreef Kevan Hampson <notifications@github.com

**Comment by GraPhiX-Guru** [comment]
your willingness not to post a screenshot, only leads me to believe you are using an 'unofficial' version of GG the issue you describe is from a very old version.

I believe this issue can be closed!!

**Comment by GraPhiX-Guru** [comment]
send me a PM on the GameGuru forums from your GG account, if you prove me wrong I will send you a code for all my assets on the store.

**Comment by Emperor2000** [comment]
I can't make a video because for some reason obs doesn't allow me to record properly?

**Comment by plemsoft** [comment]
@Emperor2000 Tried to reproduce this , but was not able to in the latest version , so i assume that this problem has been fixed ? , could you let me know if you still have this problem.
