### ISSUE TITLE
Texture painting not kept after reloading

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3780]
Terrain textures in levels is no longer being maintained between loads after MAX has closed down, so any changes appear to be reverting to the default texture when the level is reloaded.

https://user-images.githubusercontent.com/99803873/195994982-851054d1-14f9-4630-bb46-6eb241c5e79f.mp4

**Comment by Necrym59** [comment]
Still the same as of
GameGuru MAX Build 2022.10.14 - Early Access:
painted textures dissapear when reloaded

**Comment by Rickaitch** [comment]
Same here, newly painted textures disappear when level is re-loaded... but even worse, textures I painted when I first created the level have gone too.  If the data for the those originally painted areas is gone as well, then I've lost MANY hours of work.

**Comment by ZakJudges** [comment]
Hi all, thanks for reporting. This has been fixed and will be in the next experimental build. Will most likely be available to test tomorrow

**Comment by LeeBamberTGC** [comment]
@ZakJudges New EXP Build uploaded with your fix.

**Comment by synchromesh62** [comment]
Confirmed Fixed for me :)
Great work thanks.

**Comment by Necrym59** [comment]
Confirmed Fixed for me too, thankee!

**Comment by Rickaitch** [comment]
Yep, working for me now...
