### ISSUE TITLE
[Gameguru Classic] Encryption Error

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#3781]
![12312](https://user-images.githubusercontent.com/35990507/196002561-3d1b35cf-2429-4d10-abaa-e98ab75761dd.JPG)

During my work on a project I encountered another issue:

This message keeps popping up when I want to load the level.
I was able to isolate the error and it is related to a custom AK model.There is nothing wrong with it tho. I checked multiple times. 
I am willing to send the model to a GG Developer for testing.

Thanks in advance.

**Comment by Zeus2015** [comment]
always pops up in GG classic standalone games at 99% compilation
