### ISSUE TITLE
Player physics bubble should interact with objects.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3782]
The player can walk into physics on objects and has little effect on them.  Maybe add some control for physics weight, etc.?

**Comment by LeeBamberTGC** [comment]
@davetgc Can you provide some extra info here, Classic/MAX, what should be done vs what we have now RE physics.

**Comment by davetgc** [comment]
It might be an idea to move Objects weight and friction to a physics tab so that it is easily found when physics is on. 

But in general when the player pushes against a physics objects it seems really difficult to move.

As an example, take Gas Barrel01a from the military booster pack assets. if you change the physics to ON, and then set the weight to 1 and the friction to 1, walking into it still  won't move it.
