### ISSUE TITLE
10/14 update won't run

### ISSUE THREAD

**Issue by Haldogo** [TheGameCreators/GameGuruRepo#3783]
Running  intel I7-8700 and AMD R9 200  directx 12
I get no capable adapter found. All the older versions work fine
Email: haldogo@charter.net

**Comment by Tam51** [comment]
I could be your graphics card as the new version has gone to DX12. On looking up your graphics card its DX12_0 and at the moment there has been some problems with older AMD cards. I had the same problem on a AMD RX480 but I have now since changed cards and I don't get this issue.

**Comment by Haldogo** [comment]
Yes, I think it’s the graphics card.  I have used that card for a long time and it has always worked.  But if you go to that high a card, how many computers and customers do you eliminate.

**Comment by Tam51** [comment]
As a user of GGmax all I can say is go back to a version that did work 2022.08.19 and I would wait awhile before going to the new version as there are a number of problems with the DX12 version at the moment.

**Comment by davetgc** [comment]
There are some known issues with the latest build and certain cards. I'd suggest reverting to the previous build while this is looked into.

**Comment by ZakJudges** [comment]
Hi @Haldogo, apologies for the late response. This issue should no longer occur in the latest build :)

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
