### ISSUE TITLE
Hole in ground

### ISSUE THREAD

**Issue by BarryOld** [TheGameCreators/GameGuruRepo#3785]
square hole in ground when I put my building from Building Editor to GameGuru Max. Up date on this the hole only comes when I save

**Comment by Nader-B10** [comment]
I am facing the same problem (( square hole in ground when I put my building from Building Editor to GameGuru Max )) 
![image](https://user-images.githubusercontent.com/113104542/196089970-78fcb73c-8979-4c3b-b0bd-b78202df8166.png)

**Comment by davetgc** [comment]
Thanks for reporting this. It has been confirmed.
