### ISSUE TITLE
building editor problem

### ISSUE THREAD

**Issue by ecluse105** [TheGameCreators/GameGuruRepo#3786]
Hello, excuse me because I am French and do not know the English language, I use a translator. I have game guru max on windows 11 and since the last update there is bulding editor and I realized that when we create a building and it is set up in the scene, if we move it vertically below the ground it creates a cavity in the ground like a cave and you can move around in the building without any problem which is not possible with another building taken from buildings collection because if you go down the building in below the ground enters the building.
This may be a bug, but it may be interesting to create caves. I wanted to let you know.
Good day to you

**Comment by ecluse105** [comment]
Here is a picture about bulding editor problem
![Snap1](https://user-images.githubusercontent.com/67858156/196027601-4e9508da-7500-434a-b8fa-a2fbe4ba1447.jpg)

**Comment by davetgc** [comment]
Many thanks, this issues has been reported several times and is hopefully fixed for the next build. Please use search in future before posting as this will help reduce multiple reports on the same subject and speed up fixes. As this is a duplicate, I'll close this report.

#3777
