### ISSUE TITLE
Glow.lua Error is dynamic description 

### ISSUE THREAD

**Issue by GnatByte** [TheGameCreators/GameGuruRepo#3787]
-- DESCRIPTION: This object will vary the strength of any emissive texture applied to it between [MINRANGE=10(0,100)] and [MINRANGE=90(0,100)], at a specific [SPEEDOFCHANGE=10(1,100)], as though glowing slightly.

MAXRANGE is set to MIDRANGE

**Comment by ZakJudges** [comment]
@GnatByte Thank you for reporting this issue. A fix has been added which should be available in the next experimental build on Steam :)
