### ISSUE TITLE
Gameguru MAX -particle issue 

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#3788]
all particles are bound all together in one efect. so all particles look the same.
For example this is an wather drip particle in the picture below.

![wtf](https://user-images.githubusercontent.com/109030026/196045367-a75f4155-6da0-4afc-a5cb-7dca6ce73ef5.png)

**Comment by davetgc** [comment]
Can anyone confirm this please?

**Comment by 42Pix3ls** [comment]
Same issue, and only one emitter will work at a time because of it.

![image](https://user-images.githubusercontent.com/95527550/197369048-5d0aa392-4b8c-495d-ba9c-7b8f6e36becf.png)

**Comment by davetgc** [comment]
This issue has been reported several times, can anyone else please test, so
we can get a global picture of what's happening?

Thanks.

**Comment by LeeBamberTGC** [comment]
@Keepo1 Is this happening in the EXP build?

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
