### ISSUE TITLE
Path Cannot Be Found Error

### ISSUE THREAD

**Issue by andre-lobo** [TheGameCreators/GameGuruRepo#3789]
I Cannot open GURU MAX.

A component of path does not name an existing directory or path is an empty for 'C:\Users\Andre Lobo\Documents\GameGuruApps\GameGuruMAX\Files\entitybank\User' (looking in D:\Games\Steam\steamapps\common\GameGuru MAX)

**Comment by davetgc** [comment]
Hi,

Is this a recent issue?

**Comment by LeeBamberTGC** [comment]
@andre-lobo Sounds like a bug in the most recent update. You can revert to the last good public build from the Steam BETA tab, look for the build called "2022.08.19".  That should help.

**Comment by ZakJudges** [comment]
Hi all, this issue is fixed in the latest build. Closing this issue, if the problem persists, feel free to reopen. Thanks
