### ISSUE TITLE
decal_animate64.fx casts a shadow

### ISSUE THREAD

**Issue by boltactiongaming** [TheGameCreators/GameGuruRepo#379]
I have been running a stable configuration of a 'fix (DX11/PP)' for my advanced time of day and weather system which uses the decal_animate64.fx shader with slightly modified versions of algostep's weather system (just some graphical cleanup/etc). 

After the monster update, however, decal_animate64.fx casts a shadow even with FPE settings set as 'transparency=3  and castshadow=0'.  Note, I keep the DX9 version around as well with effect_animate64.fx and this does NOT cast a shadow.  The FPE/.X/texture files are identical minus the line for the shader.  So this seems obviously to me to be an issue with the decal_animate64.fx shader casting a shadow.

picture:
https://imgur.com/e7Oe7wp

Thanks

**Comment by Pirate-Myke** [comment]
Does transparency 5 or 6 make a difference?

**Comment by sfkylcnky** [comment]
Pirate-Myke: it does not work

![01](https://user-images.githubusercontent.com/37545408/45706860-06dda180-bb86-11e8-927c-4772c80f8330.jpg)
![02](https://user-images.githubusercontent.com/37545408/45706862-07763800-bb86-11e8-88d1-60e24fe9d06b.jpg)
![03](https://user-images.githubusercontent.com/37545408/45706863-07763800-bb86-11e8-932c-4ac96e4cdc7a.jpg)
![04](https://user-images.githubusercontent.com/37545408/45706864-07763800-bb86-11e8-81b4-83bd3e07e10c.jpg)
![05](https://user-images.githubusercontent.com/37545408/45706866-07763800-bb86-11e8-9261-d22b47b15d8e.jpg)

**Comment by Pirate-Myke** [comment]
That might need the edges erased completely in the Atlas texture sheet.

I don't know if decor is about anymore.
I will open the texture sheet and look at it and see if I can spot something.

Opacity has changed a bit since dx11.

**Comment by boltactiongaming** [comment]
While that might eliminate the problem with the edges, will that fix the problem of the shadow?

**Comment by Pirate-Myke** [comment]
I am not quite finished with work yet to test it out. Still an hour of daylight left.

**Comment by boltactiongaming** [comment]
i think I found the problem - tbone suggested using -1 for cast shadow and that seems to have fixed it.
I will update the code on the store.

**Comment by boltactiongaming** [comment]
One negative is he's still reporting the black lines but I can't see that on my version.  You said something about the Decal Myke?

**Comment by sfkylcnky** [comment]
FPE file to show castshadows = -1 and tab-tab menu SAO Radius 0
temporarily solved my problem.
if I am not mistaken, sao highlights the shadows inside the building.
so we need a clearer solution for the future.
thank you very much for your support.

**Comment by michaeloldman** [comment]
Hi all :)

In one of my wip levels I made an AshBox to give the impression that the planet has a light rain of ash from volcanic activity. In principle the model is the same as the free rainbox, but has a lot less planes, and my own texture.

I do not have the issue you describe here.
![ashbox_00](https://user-images.githubusercontent.com/12246318/45877839-82d42580-bde2-11e8-8ae5-c761027872a6.jpg)
![ashbox_01](https://user-images.githubusercontent.com/12246318/45877844-88ca0680-bde2-11e8-8131-be2f095aaeb9.jpg)

FPE settings are:
effect = effectbank\reloaded\decal_animate64.fx
transparency = 5
castshadow = 0

SAO settings is 35 (and if I turn it up to max it makes no difference)

I am using current Public Preview.

Reliquia....

**Comment by boltactiongaming** [comment]
@Pirate-Myke did this ever get looked at with respect to the .fx files?

**Comment by Pirate-Myke** [comment]
I am guessing that it has not been looked at in the shader file yet.

**Comment by plemsoft** [comment]
@boltactiongaming decal_animat64.fx is not a standard shader , but do the same thing as decal_animat8.fx , so just use that instead :)

If you still have this problem, please post the decal_animat64.fx shader here so we can compare, i dont have a copy of it.

But i assume you have already fixed this problem ?

**Comment by LeeBamberTGC** [comment]
The file "decal_animate64.fx" is not a stock shader, will be closing this issue at the end of June.

**Comment by michaeloldman** [comment]
Yeah no problems Preben. 

Using decal_animate8 works fine.

Thanks for all your hard work....
