### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#38]
Hey :)

It's a known issue that gameguru doesnt properly flush the old levels when a new level gets loaded.
For example, I have a game with 4 Levels.
Only level 2 is lightmapped wich causes the filesize to be bigger than the other maps.
Due to the memory issues gg has, level 4 wont load for me. I get a runtime error then.

This is a serious issue and I hope you guys can fix it somehow. Maybe we have to make gameguru 64bit ? 
I wish I had a clue what is causing this...

I wrote a thread also on the forums: https://forum.game-guru.com/thread/219044

**Comment by LeeBamberTGC** [comment]
Making it 64-bit would solve the memory fragmentation issue, but would take a few months to convert the engine and it would also alienate any 32bit users who would no longer be able to run GameGuru. Do we know the percentage of 32 vs 64 bit users on Windows 7 or above?

**Comment by honkeyboy** [comment]
Windows 7 64 bit
57.05%
figures from here
http://store.steampowered.com/hwsurvey/
hope that helps :)

**Comment by LeeBamberTGC** [comment]
So would we be losing around 50% of our users if we went exclusively to 64bit?

**Comment by honkeyboy** [comment]
No idea Lee that accounts for steam users only, Personally i think just deal with what we have for now x64 would be another massive update and tbh i think GG needs to be nice and stable before any other major updates are added. Really i think to get a better picture you'd need figures of how many GG users use x64. Just looked those up out of interest ;)

**Comment by LeeBamberTGC** [comment]
GameGuru is a Steam only title, so all 32 bit users would need to upgrade to 64 bit hardware/software to stay compatible. DirectX 11 was an easier decision as over 93% of users could make the transition. 64-bit may take a few more years to get to over 90% of all users.

**Comment by Duchenkuke** [comment]
I fully agree with honeyboy. Gameguru needs to be fully stable and funtioning first. That is the most important thing and I think many gg users think so too.
BUT, I would like to see that grass paint tool ( multiple grass types ) feature added for sure ;)

Some new cool features would be great of course, give the gamegurus something new to play lol.
Or how about a gun editor ? The possibilities are literally endless...

Sorry but one thing left: something that would be REALLY great too, is a full documentation of the settings.fx, the setup.ini ... all this stuff... I am tired having to dig deep in the forums just to understand the basics of gg. It would be a great thing for all of us.

And yes, I am done now. Have a great evening ;)

**Comment by Duchenkuke** [comment]
"Personally, I think we should get the current features and additions to a stable state, rather then add more to it."

Of course. But one should never stop dreaming, right ?

**Comment by honkeyboy** [comment]
In all honesty the dx11 update has been a really positive update from my end. An increase in fps being the most important well for me anyway. @ Lee your doing a great job m8 so far so no compliants this end m8 :)
@ Myke totally agree m8
tbh the memory issues for me doing non linear stuff i have a nice workaround using a small map as a returnzone so i dont really suffer that bug if it is a bug and i truly beleive it will be honed out eventually by one of our guys and so will be cured :) so lets stick to what we have on that score for now and concentrate on getting the engine running as it should :)

**Comment by ViperSmoke** [comment]
Hi everyone,
I wanna say that for me you shouldn't really rely on steam's survey because the relative page specifically say that "participation in the survey is optional", so many people (included me) doesn't participate a that surveys. And I use a 64-bit system*. 
Also I'm developping a game with 9 levels and I'm just came to know about this bug.
I wanna publish my game but I'm scared about the fact that with this bug it doen't will possible, beacuse people would'nt be able to game ALL the levels.
Correcting this bug is vitally important for me and for all the game creators that have more than one level.

*(windows 10 64-bit)

**Comment by Granada1** [comment]
Never look steam just the forum,things can get spread to far around to keep track

**Comment by plemsoft** [comment]
The original issue has been fixed in the latest version.

**Comment by Lentheman7** [comment]
Would it be possible to make a 32 bit version and a 64 bit version of GG? Would it be too difficult to upgrade both versions with the identical same new features? I could really benefit from the 64 bit version, and I think several other folks would also.
