### ISSUE TITLE
[Standalone] Abysmal loading time and/or 'Not Responding'

### ISSUE THREAD

**Issue by PekeNL** [TheGameCreators/GameGuruRepo#382]
Having downloaded Bugsy's work along with Wolf, I can't get either to work due to a rather insanely big loading time. When the level begins to load, it will load for about 2/3% until it halts. Waiting it out for 30 minutes and nothing happens still. When then clicking somewhere, the standalone freezes and gives me the 'Gameguru-MapEditor is not responding' windows cue.

I've tried playing with and without GG installed. Both offer the same frustration. The demo puzzle game Protascope did work however, since it a rather small game but even that loading time was around 5 minutes.

Computer specification for reference:
Intel i5 6600 3.30Ghz (4CPU)
NVIDIA GeForce GTX 1050Ti (4GB)
Windows 10
Running from an SSD

**Comment by AmenMoses** [comment]
5 minutes for Protoscope?   You have a serious problem somewhere, only takes 30 seconds for me from launch to playing!

**Comment by PekeNL** [comment]
So, for some reason 5 PC restarts fixed it? Its still slow, but not as slow as before. Nonetheless. Other programs and games load and play without problems, so i doubt the go-to 'Its on your end' is applicable here.

**Comment by AmenMoses** [comment]
Well I've searched the repository and can't find any code that says 'if ( owner = 'PekeNL' && PC Restarts < 5 ){ load slowly };'  ;-)

**Comment by LeeBamberTGC** [comment]
@PekeNL : Any chance you can create a 5 minute video of the 'Protoscope' standalone from initial launch to the game itself? I can then study the loading sections and figure out why you are waiting so long, thanks!

**Comment by synchromesh62** [comment]
Agree with AmenMoses … 30 seconds is good and you have a better setup than me ..
I also don't have AI at the moment which is also a boost .. This vid is only 32 seconds but this is what you should see.
https://youtu.be/qekawEK-Y5o

**Comment by plemsoft** [comment]
@PekeNL Great that the restart fixed it in the end , could also have been one of those (updates) running at the time , or a virus scan ? who knows , anyway great it is fixed.

Also loading times improve for all updates , so this should also get better and better :)
