### ISSUE TITLE
No support for amd 6700xt

### ISSUE THREAD

**Issue by Nicks585** [TheGameCreators/GameGuruRepo#3826]
Terrain generator and level editor black screen

**Comment by scharmers** [comment]
AMD GPU support is currently busted across the board. (AMD 5600 XT here, black screen on level load)

**Comment by Nicks585** [comment]
I’d be willing to revert back to a working driver if possible. It’s a shame that classic game guru works but not this. I took a break from dev completely when gg max came out but I still bought alpha, kinda checked it out and then decided recently that I’d give it a shot and see what’s possible only to find out that no matter what I try cannot get it to work

**Comment by dennimoto** [comment]
22.5.1 is the newest AMD driver that will work with MAX for now (I've tested with a 6900XT), but NO AMD drivers work with the experimental branch as far as I can tell
