### ISSUE TITLE
Possible bug! Deleting building and saving the project brings back the hole in the floor.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3827]
I added a building I made to GGMax project and decided to add more floors so I deleted back and As soon as I hit save the hole is back on the floor.

**Comment by ZakJudges** [comment]
@LeeBamberTGC Hole in the floor is show again if you place a BE building, delete it and then save

**Comment by Hamada880** [comment]
> Hi @Hamada880, thank you for reporting this. I have added a fix which you should see on the experimental build on Steam, available in 15 mins :)

Thanks so much and I'm going to tested it out and will follow up with the confirmation. Thanks guys for the great work. Happy Holiday GameCreator team.

**Comment by Hamada880** [comment]
Sadly,I looked for the update but the latest public preview didn't fix the issue or GGMax update.

**Comment by ZakJudges** [comment]
@Hamada880, you can find instructions for accessing the experimental build here: https://github.com/TheGameCreators/GameGuruRepo/issues/3907

Hopefully that sorts the issue for you :)

**Comment by Hamada880** [comment]
Thanks, just about to tested it out one last time to confirm the fix :)

**Comment by Hamada880** [comment]
That sure has fixed the issue, Thanks for listening to us and the hard work👍
