### ISSUE TITLE
Requested feature ! An easy access to our game project from MaxHub.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3828]
Having folder icon by the project name to access the local project folder, will make it easier to delete older projects.

**Comment by MonkeyFrogStudio** [comment]
Already requested here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2349

And the ability to delete project from the MaxHub here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2214

**Comment by Hamada880** [comment]
Thanks, couldn't find it when I searched the issues so I post it.
