### ISSUE TITLE
Changing Building Editor texture file folder doesn't load all the textures.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3829]
Tried to change the Building texture folder. It only picked one png texture and non of the other textures I made for GGMax in dds format loaded or showing in the textures pallet.

**Comment by Hamada880** [comment]
Thanks you for the update, can't wait to try it. Amazing work guy 😃

**Comment by ZakJudges** [comment]
Hi @Hamada880 The new experimental build is now available to download :)

**Comment by Hamada880** [comment]
> Hi @Hamada880 The new experimental build is now available to download :)

Will test it tonight and confirm the fix much appreciated

**Comment by Hamada880** [comment]
> Hi @Hamada880 The new experimental build is now available to download :)

What is the build name or title? Public preview one update still have the same issue. No textures loaded in the texture pallet and all is grayed out.

**Comment by Hamada880** [comment]
I can confirm it works,the name convention has to be done correctly. It still however load png formate too. Which is fine with me :p.
