### ISSUE TITLE
had to change back to the older version of gameguru max because the performance wasn't good

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#3830]

**Comment by davetgc** [comment]
Are you able to show some comparisons between versions? (Press TAB in test game to show the metrics.)

Also, please post your system specs.

Thanks.

**Comment by RajMaha1** [comment]
Smooth version 2022.08.19

https://drive.google.com/file/d/16Egttkbe5iVFIjn3Qnc05Xu7rGpA3dox/view?usp=sharing

Slow Version

https://drive.google.com/file/d/19XTBJRcaN3tA7z8gF78f8q-uKPoh5O96/view?usp=sharing

GTX 1660 ti Max Q

i7 1065g7

**Comment by RajMaha1** [comment]
32 GB Ram

**Comment by RajMaha1** [comment]
https://drive.google.com/file/d/1G7JcP2f8gAf3mqdJlYJEhQJ_FMbmgORN/view?usp=sharing

this is video showing work around to fix it on that specific level

**Comment by RajMaha1** [comment]
I Was using 16K Textures changed them to 4k now works like a charm
