### ISSUE TITLE
Smart objects move themselves after loading

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3833]
https://www.youtube.com/watch?v=Qg3OtF_EFJE

**Comment by LeeBamberTGC** [comment]
Anything connected to cursor is now excluded from the ray cast check, fixing this one in the next EXP build:
![image](https://user-images.githubusercontent.com/35840583/221226006-75923d59-04ce-4c0d-8c89-54f3d94e8ce5.png)
