### ISSUE TITLE
Building Editor: Can't toggle corner

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3834]
User toggled a wall corner and was unable to show it again:

Some how I manage to delete one corner section of a wall but was
unable to paint the corner back.

**Comment by LeeBamberTGC** [comment]
NOTE: Seems to be fine now:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4ba4d6bb-3839-46cf-9a0c-470f2fc5aa8b)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/bd45c9d1-e41c-43fa-879f-6f1058416740)
