### ISSUE TITLE
GameGuru MAX [Sound&Music Import crash] 

### ISSUE THREAD

**Issue by suffer220** [TheGameCreators/GameGuruRepo#3840]
I tried to put custom mp3 or ogg music into my game , when I add the music game guru engine freezes and the engine stops

**Comment by ZakJudges** [comment]
Hi @suffer220, do you have a file that you could post here that shows the crash?

**Comment by suffer220** [comment]
does not write an error message because it exits quickly. The engine stops completely

**Comment by ZakJudges** [comment]
Could you post the custom mp3 or ogg file that is causing the crash? If you do not want to post it here, you could also email it to zak@thegamecreator.com

Thanks

**Comment by suffer220** [comment]
sent the audio file via email

**Comment by ZakJudges** [comment]
@suffer220 I have not received the email. I misspelled my email address, it should be zak@thegamecreators.com

My apologies

**Comment by suffer220** [comment]
and I tried to send it again

**Comment by ZakJudges** [comment]
@suffer220 I have received it now, thanks!

**Comment by suffer220** [comment]
Have you had a chance to try the sound file?

**Comment by ZakJudges** [comment]
Hi @suffer220 I haven't been able to reproduce the crash. Would you be able to post a video of the issue, as well as your system specs below?

**Comment by suffer220** [comment]
I tried to record the problem 
https://youtu.be/qXbtkp7laA4

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
