### ISSUE TITLE
Importer Scaling - Unit of scale not proper (cm, inches)

### ISSUE THREAD

**Issue by DarkHillStudios** [TheGameCreators/GameGuruRepo#3841]
When importing a model that has been created using "Centimeters" or "Inches" the importer does not scale correctly when "Centimeters" or "Inches" is selected as the import scale. Meters works as intended as far as I can tell. 

Please reference attached videos.

Meters: https://www.youtube.com/watch?v=BBSKeSTun1Y

Centimeters: https://www.youtube.com/watch?v=A9jqAEsWbFQ

Inches: https://www.youtube.com/watch?v=9oyviRaOEgU

If this is by design please let me know. I have also looked at Monkey Frog's Blender2Max scale video and it works great for blender units but the issue that I have is the export scale from blender should be a 1:1 ratio if modeling is performed using one of the three listed units of scale (Meter, Centimeter or Inches).

**Comment by DarkHillStudios** [comment]
Any update on this one?

**Comment by LeeBamberTGC** [comment]
@DarkHillStudios No updates but will be checked out as we crunch through the bug list.  We will not change fundamentals as it will break everyone elses experience, but there may be a way to add more scaling options to sync properly with the exports from the tools being used. You mentioned Blebder, can you attach an exported cube in all measurement styles and we can see if the importer can be enhanced to bring them in as intended?
