### ISSUE TITLE
GameGuru Max - Bug - Building Editor - Bug 2/6 - Overlapping Textures

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3843]
Individual posts by request from #3772

Sometimes when texturing buildings in the building editor, textures will overlap, this can be seen in the included video from the 0:38 point to 0:44.

Video link from original post: https://youtu.be/XTuWc4HJSe8

**Comment by ZakJudges** [comment]
Hi @Lemuripest93, I haven't been able to reproduce this one, but I think it may have been because of #3795. The floor of the layer above would be raised just enough to cause the texture overlap. That fix should be in an experimental build by tomorrow :)

**Comment by Lemuripest93** [comment]
I haven't been able to reproduce it either since it happened, so it's probably fixed, but i'll report back if it's not.

**Comment by ZakJudges** [comment]
Hi @Lemuripest93, the new experimental build is now live on Steam :)

**Comment by Lemuripest93** [comment]
Just saw, i'll be doing some tests a little later, got some work to finish up first, i'll report to you if i see anymore of this bug 👌

**Comment by Lemuripest93** [comment]
Okay so i did a few different tests with a few new smaller buildings and they all came out perfect, used a different texture on every single wall on the second floor and every door frame, no texture overlapping, i think it's safe to say that this one is fixed, at least as far as i've tested it.

I'll close this one since i'm confident it's fixed, if anyone feels differently i'm sure it'll be reported.
