### ISSUE TITLE
GameGuru Max - Bug - Building Editor - Bug 5/6 - Warehouse/Light Red Doors Do Not Close Properly

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3846]
Individual posts by request from #3772

When placing a building and rotating it, the warehouse and light red door types do not properly close or align properly to the door frame.

**Comment by Lemuripest93** [comment]
Just an update, this bug has nothing to do with buildings being rotated, the warehouse door (both green and grey) and the light red doors have these issues **without** being rotated as well.

Additionally the warehouse doors are very translucent, if you put them in view for sunlight and go behind them, you can see right through them.
Not sure if you want that to be a separate bug or if you'll fix this alongside the main bug.

Hope this is of help, if you didn't already discover this, lol

**Comment by ZakJudges** [comment]
Hi @Lemuripest93, thanks for reporting this issue. I have created a new issue re being able to see through the doors: #3932

The door alignment issue seems to be a problem in script, rather than the building editor. I will come back to this one, after the Building Editor bugs have been fixed. Thanks :)

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Used the building editot to create a one room building that uses both red doors from the selection, when tested in level there are no gaps around the doors, must have been fixed a while ago:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ed66ff97-2c88-4a74-b8f5-c66cb45711c4)

**Comment by Lemuripest93** [comment]
I can confirm that these are NOT fixed, here's a video demonstration, making a new map and new building from scratch, bugs still intact: https://youtu.be/FejOyhT1ZZc

**The doors need to be opened for the bug to occur.**

Here is the _building_ i made in the video for testing purposes:
[TestForDoors4342342.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13243739/TestForDoors4342342.zip)

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Thanks for the zip. I will also need the file "TestForDoors4342342_smartchild.fpe" and its associations too. Right now I have a missing building model :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/34c18870-b74f-457e-bd21-99c288795f90)

**Comment by Lemuripest93** [comment]
Oh, woops, will upload ASAP.

**Comment by Lemuripest93** [comment]
Here you go, my bad:
[TestForDoors4342342-corrected.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13243808/TestForDoors4342342-corrected.zip)

**Comment by Lemuripest93** [comment]
I would also like to note that there's a new bug, the first door placed on any building seems to not want to open, you see this in the video also at 01:13, i made a new building and it also happens to the green door, not sure if every door is affected.

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Fixed the issue of the dirst door not opening in next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ed490026-0cfd-4a74-bd21-8b978e311a7d)

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Got ya, can reproduce now:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8196f910-92ac-457e-9120-39767b50c02e)

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Fixed for next EXP build.

**Comment by Lemuripest93** [comment]
Sounds good, i'll close this when i'm testing the next XP build.

**Comment by Lemuripest93** [comment]
The light red doors still have a small gap after closing, but since they're hardly noticeable i'm quite satisfied with closing this now, thanks for fixing the most glaring issues with the green/grey doors :)
