### ISSUE TITLE
GameGuru Max - Bug - Building Editor - Bug 6/6 - Buildings Spawn Inside Eachother

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3848]
Individual posts by request from #3772

Stupidly forgot to add this one, but here we go, not sure how common this bug is, but a building i made before the last experimental build experienced some pretty horrific bugs.

Video: https://youtu.be/Z_c4x92iRFU

Not a big deal since i'm going to remake this building, but if anyone made any complex structures they may wanna check up on them.

**Comment by ZakJudges** [comment]
Hi @Lemuripest93, do you still have the file "TestMotel1.mbf" that you could post here? It will be in your custom media folder -> entitybank -> user -> buildingeditor folder

Thanks

**Comment by Lemuripest93** [comment]
I get an error message that "We don't support that file type." could i send it to you via email?

**Comment by ZakJudges** [comment]
@Lemuripest93 Sure - my email is zak@thegamecreators.com :)

**Comment by Lemuripest93** [comment]
Done, good luck.

**Comment by ZakJudges** [comment]
@Lemuripest93 Thank you. I have added a fix which you should see in the next experimental build. I will post here when it is available to download and confirm the fix :)

**Comment by ZakJudges** [comment]
@Lemuripest93 The new experimental build is active - should be able to load your TestMotel1.mbf file and see the fix :)

**Comment by Lemuripest93** [comment]
Yup! this one's fixed as well now, good job! closing this one, confirmed fixed! :D
