### ISSUE TITLE
image zone issue

### ISSUE THREAD

**Issue by therickman** [TheGameCreators/GameGuruRepo#3851]
Hello, I'm using the steam version ( up to date ) : the image zone works only if "fullscreen" is ticked. otherwise, the picture looks like TV noise. Thank you.

**Comment by ZakJudges** [comment]
Hi @therickman, apologies for the late response. I have not been able to reproduce this issue. Do you still experience it in the latest build? It sounds like an issue with the DX12 version, so should be fixed now :)

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
