### ISSUE TITLE
Okay No black screen with the newest AMD 6700xt Driver Now Crashing as it loads my project pretty much instantly

### ISSUE THREAD

**Issue by Nicks585** [TheGameCreators/GameGuruRepo#3853]
no more black screen software crashes near instantly after opening project.

specs

AMD RYZEN 5 5600X
AMD 6700XT
16GB
SSD

**Comment by LeeBamberTGC** [comment]
@Nicks585 I can confirm the bug, and can also confirm it will be fixed for the final DX12 release.  For now, you can revert to the last good DX11 build which you can find in your BETA tab on Steam client, choose the 2022.08.19 build, that should work for you.

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
