### ISSUE TITLE
building editor 

### ISSUE THREAD

**Issue by antoniox116** [TheGameCreators/GameGuruRepo#3857]
hi the builder editor works a little badly if I create small buildings no problem. but if I create bigger buildings it doesn't load me all the textures. thank you
![Common Screenshot 2022 10 21 - 16 49 23 09](https://user-images.githubusercontent.com/116370058/197226063-2eb47e11-3c0a-4cae-9748-42d852b66602.png)
![Common Screenshot 2022 10 21 - 16 49 40 01](https://user-images.githubusercontent.com/116370058/197226110-b87d8362-d8fb-4460-ae59-a1bfcb3c6e3a.png)

**Comment by Lemuripest93** [comment]
This has been fixed and is available as a fixed version in the experimental build, try switching over to that version then re-import your buildings and they should all be working fine, alternatively you can wait until this fix is brought into the public build :)

**Comment by antoniox116** [comment]
ok thank you very much, very kind

**Comment by davetgc** [comment]
Can I close this as fixed?

**Comment by antoniox116** [comment]
Yes thank you

Il mar 1 nov 2022, 10:58 davetgc ***@***.***> ha scritto:
