### ISSUE TITLE
building editor 

### ISSUE THREAD

**Issue by Stefos-art** [TheGameCreators/GameGuruRepo#3858]
When loading a building made in the building editor there are a few problems, some of which have been reported, like doors not closing and textures to shiny.
I have one I don't think has been reported, when saving level with building made in building editor in GamerGuru Max a never ending hole is created next to building as you can see via attached picture 
![Screenshot_47](https://user-images.githubusercontent.com/62201786/197260584-083ef362-f484-43b5-a45c-0f5fdf19f9c2.jpg)

**Comment by Hamada880** [comment]
Yes,the issue have been reported and @ZakJudges pass it to @LeeBamberTGC here is the issue #3827.

**Comment by davetgc** [comment]
Hi, thanks for the report, we are aware of this issue.

Please use the search function when posting issues, to check if something has been reported, this speeds up the debugging process and helps to keep reports in one place.
