### ISSUE TITLE
GG MAX  - Editor - Objects Tools - Base Color 

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#3859]
The bug describded hereafter exists since a long time in GameGuru MAX but it was very difficult to detect how and why it systematically happens during this specific workflow : 

1) an existing asset of the libraries is placed in the scene.
2) its base color is modified
3) that asset is replicated a few times
4) their base color are also modified
5) then the simulation of the scene is started
6) after exit from that simulation, the base color of the replicated assets return to the one defined in the very first asset. That's the problem !   

Today, while I was testing this command 'SetEntityBaseColor' on many replicated assets and applying RGB colors generated with a random generator, I discovered that a lot of those assets didn't show those random RGB colors.
Then I tried to understand why it happened.

The answer was found in the way the replication process is executed in the editor.
A) All assets replicated in one shot while holding the Shift key after having selected the very first instance don't acquire their own base color (even if you try to modify this one).
(see picture A)
![clones-bad-A](https://user-images.githubusercontent.com/94678034/197288783-0a837039-e4cb-4823-97c0-12fa96332179.jpg)

B) If a new serie of clones is created when selecting an asset replicated in step 1 then the assets of that new serie effectively acquire their own base color that can be modified in the editor or with a script.  It is also true for the next series created as describded in this step.  -> That's the logic process.
(see picture B)
![clones-good-b](https://user-images.githubusercontent.com/94678034/197288824-6f3e8c97-8b87-4853-940f-2cb652e9faa1.jpg)

**Comment by LeeBamberTGC** [comment]
@marcuswilm There was a bug a while ago that would mistakenly copy material settings and reset settings incorrectly as objects where managed. This should be resolved now but if you can reproduce with a simple stock object and a step by step, please post here and I will take a closer look :)

**Comment by marcuswilm** [comment]
@LeeBamberTGC Thank you for your message confirming that this bug was fixed.
I made the same tests as shown in this report but this time with the official Steam public release of GG Max and I may confirm that  modifying the color of replicated assets in the editor now works correctly.
:)
