### ISSUE TITLE
GameGuru EBE grid misaligned with entity grid

### ISSUE THREAD

**Issue by T1ppex** [TheGameCreators/GameGuruRepo#386]
Bug reported as requested by Lee Bamber [https://forum.game-guru.com/thread/220071](url)

The roof pieces in the fixtures library now fail to snap to the same grid upon extraction - they are repeatabley offset, unlike they once behaved correctly as shown in  EBE Quick Start Guide https://www.youtube.com/watch?v=6ST1bMziIEw&t=135s 
 
[Grid_Problem.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2414083/Grid_Problem.zip)

Even after extracting both house and roof piece in grid mode (and after checking that they both snap to their grid when moved), the roof piece appears to be snapping to a different grid to the house and so gets misplaced (unless a different snap mode is selected than grid, but then more fiddly than the way shown in the video.

**Comment by synchromesh62** [comment]
Confirmed but you must select and extract the model before putting the roof on ..
This aligns one side of the roof perfectly for me ..

The problem comes when you try to align the other side as the grid snap just wont join

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
This was never a bug .. Just not Extracting the models in the same grid mode
