### ISSUE TITLE
GameGuru Max - Enhancement - Building Editor - Copying And Pasting Floor Templates

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3861]
Being able to create, copy and paste one floor to subsequent floors would be a very ideal feature in my opinion, this way you don't have to manually add new doors, windows, rooms, textures and future additions to the above floors of a building, this is especially important if you're making buildings like apartment complexes, hotels, office blocks and similar. This also means that you will have more consistency because everything will look the same on each floor, and not to forget - save a lot of time in creating buildings, which would be a major positive considering there's a lot of time and work that goes into a game to begin with.

There could be a separate button for this in the building editor, like "Copy and Paste To Next Layer" - or something like that, though i guess you could figure out a better solution if that doesn't work out.

Not sure if this feature has already been internally discussed, but regardless i feel this is a must.

**Comment by ZakJudges** [comment]
Hi @Lemuripest93, you can cut (CTRL+X) or copy (CTRL+C) the current layer, move to the desired layer and then paste (CTRL+V)

There is also options to do this in the toolbar:
![Screenshot 2022-10-24 163236](https://user-images.githubusercontent.com/32545391/197565967-e7077a06-5c45-45a0-a23b-0c477e670246.png)


Is this what you mean?

**Comment by Lemuripest93** [comment]
Ah.. yes it appears it is, my bad, i didn't realize this was already a feature because it was hidden in the 'Edit' tab, guess i'm closing this one, thanks for letting me know 👌
