### ISSUE TITLE
Changing a Project Name ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3863]
Although when creating a project, it says you can change the project name later after checking a question from a Steam user it turns out you cannot :)
Unless I'm missing something.

![Project- name](https://user-images.githubusercontent.com/35708217/198029613-f8cb2036-dae5-45bd-bc9b-226d64b504a8.png)

**Comment by davetgc** [comment]
I've not be able to work out how, so I'm listing this as a bug.

**Comment by Tum1370** [comment]
@synchromesh62 @davetgc 
After having a play around with trying to change a project name.
I have found a method, but really it needs to be a lot easier, with a simple option to change project name

Anyway,  Whilst in the Game Storyboard, You can go to the top menu, select FILE > Save Game Project As option.
This will then save a new project, but also leave the old project there to.

It seems to work fine, but like i say, you could do with a Change Project Name option.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Changed the text to match present functionality in the next EXP build:

				ImGui::TextCenter("Make sure you choose a good name for your project, you will");
				ImGui::TextCenter("not be able to change it later on.");

**Comment by synchromesh62** [comment]
> @synchromesh62 Changed the text to match present functionality in the next EXP build:
> 
> ```
> 			ImGui::TextCenter("Make sure you choose a good name for your project, you will");
> 			ImGui::TextCenter("not be able to change it later on.");
> ```

God Lee im sorry ... I forgot about this one.
Truth is i found a way to do it ... Load the Project then just "Save As"  under a new name and delete the original from the projectbank. Im more than happy with that way of doing it but your edits are fine :)

As you say it now matches the functionality but if anyone really wants needs to change the name my way works great :)
