### ISSUE TITLE
GG Max - Experimental Version - Asset Manager Bug ?

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3865]
HI, 
When using the experimental version of Max i found that the Asset Manager has a bug with some assets.
As you can see the asset pictures are messed up ?

Has this already been reported ? IF so ill delete this one.

![Bug](https://user-images.githubusercontent.com/66874403/198049397-5cd2aefa-bdbe-473b-bb5b-3cd08889eef4.png)

**Comment by MonkeyFrogStudio** [comment]
This has been reported a few times. Here's one instance:

https://github.com/TheGameCreators/GameGuruRepo/issues/3678

**Comment by Tum1370** [comment]
@MonkeyFrogStudio 
OK thanks, i will close this issue then as already reported.
