### ISSUE TITLE
GG MAX - Editor - Using Snap Mode

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#3869]
I recently watched the interesting and useful video published by Lee Bamber ( [https://www.youtube.com/watch?v=UoiRnizjpNI](url) GameGuru - Broadcast  number 118 - Using Snap Mode ).

About the imported assets which are rescaled in the Importer or in the Editor :  
In the editor, the function 'Align Grid Size to Object' don't use the Scale's parameters of those assets.

**Comment by LeeBamberTGC** [comment]
@marcuswilm They are two different kinds of scaling. I have set this to a feature request so you can go into more detail about how you would want to go from the importer through to the snapping system in the level editor, it could be an extra item in advanced or developer mode.
