### ISSUE TITLE
GameGuru Max

### ISSUE THREAD

**Issue by CRGSOS** [TheGameCreators/GameGuruRepo#3872]
Today ADD objects and change BEHAVIOUR not working on my Steam version of game GameGuru Max. Rebooting and redownloading makes no difference. Everything normal last night.
CRGrant

**Comment by davetgc** [comment]
Is this since an update?

**Comment by CRGSOS** [comment]
Dear Dave

Humble apologies – my error in that I lost the relevant windows for ADD  (but this is perhaps something that could be improved). So there is no bug! 

However am I right in thinking the Lua command PANEL()  will not work at present?

Best wishes Roger Grant

Sent from Mail for Windows 10
