### ISSUE TITLE
GameGuru MAX Build 2022.10.14 vsync issue

### ISSUE THREAD

**Issue by PalmTree11** [TheGameCreators/GameGuruRepo#3874]
Since the recent update the frame rate does not go beyond 60 whether vsync is on or off. Prior to that if I took vsync off the FPM would go to 90 or above.

**Comment by MonkeyFrogStudio** [comment]
Already reported here:
https://github.com/TheGameCreators/GameGuruRepo/issues/3679

**Comment by davetgc** [comment]
Thanks for the report. As this is a duplicate I'll close this one for now.
