### ISSUE TITLE
New Update Breaks Drones

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#388]
As the title says the new update breaks the Sci-Fi drones.

When you shoot a drone it no longer head in your direction, but just gets confused and goes anywhere but to where you are.

Additionally when you shoot a drone it no longer blows up but simply disappears.

You can reproduce this by simply adding some drones to a new map.

Reliquia....

**Comment by synchromesh62** [comment]
Confirmed although the Bomber is the worst for me as it loses textures and vanishes totally even in the editor itself..

**Comment by LeeBamberTGC** [comment]
Yes, also confirmed, thanks for the quick report!

**Comment by michaeloldman** [comment]
No problems Lee, just happens that the level I am building atm is using drones to stop your progress, so picked up on it as soon as I loaded the level :)

Also gave the Ally Drone a spin in my level, but he refuses to go any where. It works on a blank level though so don't know what he doesn't like about my WIP level.

Pesky bugs - Great job thus far though Lee 👍 

Reliquia....

**Comment by michaeloldman** [comment]
Also noticing the camera\player movement is not smooth as before.

Reliquia....

**Comment by LeeBamberTGC** [comment]
You can use the LASTDEFAULT option from the drop down beta tab to get the previous Public Preview on your system. When you report 'not smooth' for the player camera, can you be more specific. I am not sure a video would demonstrate your report, but if you think it could, maybe attach that. I have had no other reports of loss of 'smoothness' in frame rate (I presume you are running 60fps constantly).

**Comment by michaeloldman** [comment]
Hi Lee. Ah OK didn't see that option, I may have to look again :)

That said, I think it may be more to do with the installation. Even though I validated via steam, and then rebooted the system, the game play was not very smooth. I don't think it would be noticeable in a video, but it was like the player was constantly trying to move but getting held back and then let go again - like a slow surge - lol if that makes any sense at all.

However after reverting to V1.4 then reinstalling the PP, Validating, and rebooting, it is much better now.
I will be working on my WIP level some more over the next few days so I will see how it goes, and will also try to get the LastDefault back on my system so I can compare it again.

Reliquia....

**Comment by michaeloldman** [comment]
Hi Lee
Given the AI breaking drones issue and my WIP is heavily reliant on drones I would still like to go back, but there is no LASTDEFAULT option in my Steam setup.

Am I missing something here?

Reliquia....

**Comment by LeeBamberTGC** [comment]
I can confirm it not showing up too, not sure why that's the case.  Are you part of the beta testing group as the fix would appear there first?

**Comment by michaeloldman** [comment]
No, I do not have that privilege :)

Reliquia....

**Comment by LeeBamberTGC** [comment]
Hi Reliquia, send me an email directly to lee@thegamecreators.com and I will get you signed up, thanks!

**Comment by Ratall** [comment]
>           Confirmed although the Bomber is the worst for me as it loses textures and vanishes totally even in the editor itself..

The problem with the textures on the Bomber drone is not related and can be resolved by adding 
FULLBOUNDS = 1
CPUANIMS = 1
to the Bomber Drone FPE to bring it in line with the other drones

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Drones still broken... added Video
https://youtu.be/JeQrcGZArIQ
