### ISSUE TITLE
GameGuru MAX - Bug - Saving Group Changes Light Type

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3880]
I was testing to see if another bug I'd reported had been fixed so I could close it:

https://github.com/TheGameCreators/GameGuruRepo/issues/3153

But in the process, I've discovered another bug related to it.

If you create a group that contains a SPOTLIGHT, then save that group using the Save Group option, when you bring that group into a level, the SPOTLIGHTS have changed to POINT LIGHTS:

![group_Light](https://user-images.githubusercontent.com/36735507/200129905-3d1437a0-2c01-45b8-bccb-5e8b484bbce9.png)

The group in the back shows the group as created. The group in the front shows the group being brought in from the Object Library.

How to create this error:

- Create a group that contains a spotlight (it may help to change its orientation, etc.)
- Save the group and save your level
- Exit MAX
- Restart MAX
- Open the Object Library, find your saved group with the spotlight, and drag it into your level

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Confirmed this fix for the next EXP build, created a hut and spotlight with rotate behaviour, saved as smart object then reloaded MAX and dropped smart object in, the spot light type was retained:
![image](https://user-images.githubusercontent.com/35840583/229365925-d5a50bfb-1126-4730-ac83-d3ec34b57186.png)

**Comment by MonkeyFrogStudio** [comment]
This appears to be fixed! Thank you!!!
