### ISSUE TITLE
no picture

### ISSUE THREAD

**Issue by NekronNex2** [TheGameCreators/GameGuruRepo#3881]
hi,

I have an AMD graphics card in game guru max already made the problem that you saw no edit picture, this should gehn now. wanted to try the building editor, but here is also the problem as with GGMAX you see no picture when you want to do something. just black.

greetings

**Comment by davetgc** [comment]
There is a known issue with AMD cards. Have you tried the latest experimental build?

**Comment by NekronNex2** [comment]
yes unfortunately i know the problem with the AMD cards. which eexperimental build do you mean?? in the main game the AMD card works for me, only the building editor does not work.

greetings

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
