### ISSUE TITLE
October fixes

### ISSUE THREAD

**Issue by Zeus2015** [TheGameCreators/GameGuruRepo#3883]
hi,

[https://forum.game-guru.com/thread/223896](https://forum.game-guru.com/thread/223896)

![GameGuruClassic](https://user-images.githubusercontent.com/10551167/200340578-3ceaa32b-67fb-4703-b6b1-c97074b7f4f5.jpg)

GameGuru Classic and GG Max PFS Framerate by 7-8 Frames. on my Machine.

**Comment by davetgc** [comment]
Can you please post your system specs?

**Comment by Zeus2015** [comment]
System specs: Processor Intel i7 6700K, Asus Z270G  Mainboatd, Inno3D Nvidia RTX 3060 Ti , 32GB DDR4 RAM 3600 MHz, 1 TB Samsung M.2 SSD. 64 Bit Windows 11.

**Comment by davetgc** [comment]
Thanks for the information, drivers can occasionally cause these kind of issues.
