### ISSUE TITLE
Texture/ Terrain resetting after save.

### ISSUE THREAD

**Issue by Do0ks** [TheGameCreators/GameGuruRepo#3887]
I found this,

https://github.com/TheGameCreators/GameGuruRepo/issues/3780 

Though my software is up to date via steam, I'm still having this exact issue. 

Any ideas?

**Comment by synchromesh62** [comment]
Fixed but only currently in the Experimental Build.
You can access it via Steam
The Passcode is
lettesterin456

**Comment by Do0ks** [comment]
> 

Awesome! Thanks for that, It works. 

No passcode was required for me.
All I had to do from steam was right click GameGuru -> Properties -> Betas and drop down to "experimental - Internal test build prior to release" and it updated. 

Thanks again!!

**Comment by synchromesh62** [comment]
> > 
> 
> Awesome! Thanks for that, It works.
> 
> No passcode was required for me. All I had to do from steam was right click GameGuru -> Properties -> Betas and drop down to "experimental - Internal test build prior to release" and it updated.
> 
> Thanks again!!

Thats great .. Perhaps they unlocked it but i still get some saying it's not in the list until they enter the password so i just post it anyway :)
