### ISSUE TITLE
editor building non funziona 

### ISSUE THREAD

**Issue by antoniox116** [TheGameCreators/GameGuruRepo#3891]
it does not work when I export the project the textures are not displayed all the ground then opens and the water comes out if then I text the level the screen goes all black and you do not see anything and I have to delete the project I have directx 12 video card However, nvidia only gives me this problem with large buildings

![Desktop Screenshot 2022 11 10 - 11 24 20 36](https://user-images.githubusercontent.com/116370058/201067241-8409f74b-7f9d-4c79-903a-3f8b9d839130.png)
![Desktop Screenshot 2022 11 10 - 11 24 49 15](https://user-images.githubusercontent.com/116370058/201067257-bb875e03-7307-496c-a106-ccbfb0de6c94.png)

**Comment by Tam51** [comment]
Hi There I have the same problem with large buildings
![image_2022-11-10_143603886](https://user-images.githubusercontent.com/93008801/201119621-fb3cd03b-aab2-4ca9-bf38-5f4442b30bf4.png)
 As you can see from the picture

**Comment by ZakJudges** [comment]
Hi all, this has been fixed and is currently in the experimental build on Steam. To access the experimental build, you can right-click on GameGuru Max in your Steam library -> Properties... -> BETAS ->experimental

The password is "lettesterin456"

Note that you will need to reexport your buildings to see the fix

**Comment by antoniox116** [comment]
yes i saw now anyway now i try it for now this can be closed
