### ISSUE TITLE
GameGuru MAX crashes

### ISSUE THREAD

**Issue by queryart** [TheGameCreators/GameGuruRepo#3892]
The program crashes every time I run scenes, games, demos
When I install the beta version, when launching a demo or project, the screen is black. But HUD and sounds work

AMD Radeon RX 6600
AMD Ryzen 5 3600 6-core
16 RAM

**Comment by ZakJudges** [comment]
Hi @queryart This is a known issue and will be addressed in the near future. For now, you can roll back to the last build by right-clicking on GameGuru Max in your Steam library -> Properties... -> BETAS -> Select 2022.08.19 from the dropdown

**Comment by mav3r1ck198-1** [comment]
editor works fine, but every single time i load into test game, GGMax now crashes. This happens in experiemental, public preview, 19/08/22 and 09/08/22. Ive about given up

**Comment by synchromesh62** [comment]
> 

Silly question maybe but are you just installing and running or are you rebooting after you have updated.
reason i ask is i have seen this before, Some give up and power off until the next day when it suddenly magically works when they boot back up.

**Comment by mav3r1ck198-1** [comment]
rebooting each time. Even the Demos crash out to the desktop

**Comment by queryart** [comment]
+++, тоже самое

**Comment by ZakJudges** [comment]
Hi all, apologies for the late response. This is likely a driver issue. Info on a fix here: https://steamcommunity.com/app/1247290/discussions/0/5738182472464125380/

**Comment by ZakJudges** [comment]
Closing this issue as likely solved. If the issue persists, feel free to reopen. Thanks
