### ISSUE TITLE
GGMAX - Some LUA commands not working

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3893]
SetAmbienceRed(0)
SetAmbienceBlue(0)
SetAmbienceGreen(180)
SetAmbienceIntensity(120)
SetSurfaceGreen(180)
SetSurfaceRed(0)
SetSurfaceBlue(0)
SetSurfaceIntensity(140)

The above commands will not activate in a script unless followed by
SetPlayerFOV(fov-0.001)
SetPlayerFOV(fov+0.01)
These commands seem tied to the FOV for some reason.

**Comment by davetgc** [comment]
Looks like they aren't updating automatically.

**Comment by ZakJudges** [comment]
@Necrym59 I have linked the ambience Lua commands to their own dedicated Wicked lighting update function, so they can work without needing to change the FOV. 

However, I am not familiar with the SetSurface...() commands. Looking at Wicked, there is no reference to surface color. Is it supposed to be the sun light? If so, I can link the SetSurface() commands to it for backwards compatibility

**Comment by Necrym59** [comment]
Hi Zac 
yeah it sets the surface reflectance color and intensity - most noticable with the night vision scenario but could be any surface reflectance. Im not sure how it pertains to sun light unless that makes the rgb colouring on a surface in wicked now
whats there now actually works but just wont activate unless that dodgy little FOV trick happens. Shall we try and see with what you have first and see if its eneough?

**Comment by ZakJudges** [comment]
@Necrym59 Sure, a new Steam experimental with the change has been uploaded :) If it doesn't work as expected, I can ask Lee when he is back about it as I am sure he will know more than me

**Comment by Necrym59** [comment]
Actually i just tried it and it seems fine i dont think those SetSurface ones seem to be doing anything at all anyway now that i look at it.
I think it was from my old Classic code they got brought over and I just assumed they worked. They never errored. They may be superseeded now. Should i leave them in for now and just rem them out until you clarify later.

**Comment by ZakJudges** [comment]
@Necrym59 Lets leave them in just in case and we can wait and see if there is a Wicked engine equivalent. I will leave this issue open for now until Lee gets back :)

**Comment by Necrym59** [comment]
No probs im just remming them out and it seems to work fine for now  - will wait till we hear from the holiday guru :)
thanks again Zac

**Comment by Necrym59** [comment]
Zac in GGC it sets the RGB saturation of the Terrain only - it may be redundent in MAX or handled by a different shader.

**Comment by ZakJudges** [comment]
@Necrym59 In that case it would indeed be redundant in Max as the terrain uses different shaders and I couldn't see any variables which do the same in any of the new shaders. However, we could turn this into a feature request if you would like it in :)

**Comment by Necrym59** [comment]
Lol, I dont know to be honest i think whatever gets done with Luts eventually would cover it i think but it could be used to perhaps handle luminosity of the terrain surface rgb, that would def come in handy.

**Comment by ZakJudges** [comment]
No worries, in that case I will close this issue. If you end up needing something like SetSurface...() we can reopen it :)
