### ISSUE TITLE
GGMAX-Massive Hole (endless)

### ISSUE THREAD

**Issue by GavinIssooocoool** [TheGameCreators/GameGuruRepo#3894]
hello, ive encountered a bug. 
![image](https://user-images.githubusercontent.com/32985460/201437866-ca150740-ea16-44ae-b0c8-58e7a07dd9f2.png)
i was putting in my building editor object when suddenly a large, seemingly endless hole appeared. i cant seem to fill it in, any idea how to get rid/hid it?

**Comment by Hamada880** [comment]
The issue been reported twice and the dev team aware of it, this is issue number #3827.

**Comment by davetgc** [comment]
Closed as duplicate
