### ISSUE TITLE
Object library preview crashing MAX

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3896]
Selecting the large object preview causing MAX to crash. Checked with several weapons previews, it might also affect other thumbnails, if anyone can confirm.

**Comment by ZakJudges** [comment]
@davetgc I couldn't reproduce this crash in the latest experimental build, however, it is most likely caused by the DX12 changes.

**Comment by davetgc** [comment]
@ZakJudges  - It could be, it wasn't just me, another user also reported it. I'll try again.

**Comment by ZakJudges** [comment]
Closing this issue as likely caused by DX12. If the issue persists, feel free to reopen. Thanks
