### ISSUE TITLE
'Character Collision' Causes Issues for Non-Human sized Characters. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3898]
The issue is that very small enemies that are close to the ground will completely block the player. The player should be able to walk through enemies that are this size, instead the player will hit the enemies collision when it seems like they should be able to walk forward. 

Setting collisionmode = 11 (turning off collision) fixes this problem but then the player cannot shoot the enemies. 

This was a problem in Classic and completely ruins smaller enemy creatures or monsters. I've seen people complain about this one over the years and was kinda surprised that this is still an issue in Max. 

There should be some way to let the player walk through these kind of enemies. 

Here is an example, https://youtu.be/o38AlANyiCI
Notice how at 36 seconds in, even just one of the little bugs completely blocks me from moving. 
imagine if this happened in Halo when you are fighting the Flood. It would be a disaster!

**Comment by Kitakazi** [comment]
According to Cybernescence, classic has a gunspec variable that allows ray cast to assets that do not have collision. Would this be possible to add to Max, so that the enemies can be set to Collisionmode = 11 and still be able to be killed?

**Comment by davetgc** [comment]
Currently non human characters aren't supported and we don't plan on adding support for V1. However, further down the line we'll be expanding the range of options.
