### ISSUE TITLE
Weird object behavior's

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#3899]
https://drive.google.com/file/d/16ks55mwi_eRojIpyJ9cCrEFheWPvZ0ua/view?usp=sharing

Weird behavior with my horse and carriage

**Comment by davetgc** [comment]
Hi, can you please email Lee@thegamecreators.com with this model, and link to this issue. We can't test without the original model.

**Comment by AmenMoses** [comment]
Looks like the model was made with Z axis being Up instead of Y axis.

**Comment by davetgc** [comment]
I'd agree that's the problem. Was it imported using the importer? Did it look okay then?

**Comment by RajMaha1** [comment]
Yeah in imported it using the importer

**Comment by RajMaha1** [comment]
![image](https://user-images.githubusercontent.com/107326667/203303844-0500164c-baa6-4590-b903-6e4ca0e92a15.png)

exported it even worse i don't know what dimensions to use Thank You:)

**Comment by davetgc** [comment]
You can rotate the model in the importer, have you tried that?

**Comment by RajMaha1** [comment]
yeah sorry i did that it keeps resetting unless i click on it Thank You No Stress

**Comment by davetgc** [comment]
Thanks, it does sound like a bug. Could you please email the model to Lee?

**Comment by RajMaha1** [comment]
whats lee email again sorry
