### ISSUE TITLE
Editor - Closing Library Tab

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#39]
Build: Public Preview

If you close the Library tab in the editor (by clicking on the small X), there is no way to bring it back up. Using Windows 7.

![left_x](https://user-images.githubusercontent.com/35990109/35902268-8d7f5726-0ba8-11e8-9704-cb5d1a09bc48.jpg)

Related Forum Thread:
https://forum.game-guru.com/thread/215312

**Comment by LeeBamberTGC** [comment]
Fixed for next beta build 10/04/18
