### ISSUE TITLE
Gameguru Max Resetting my setting i load it from taskbar or start menu and load different splash screens

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#3900]
![image](https://user-images.githubusercontent.com/107326667/203156473-db291a11-c507-49c3-8bdd-c6be6bae40d8.png)

![image](https://user-images.githubusercontent.com/107326667/203156655-6fcd4b42-7e2e-4e6f-8870-f2941d5ea0ad.png)

https://drive.google.com/file/d/14T5D38qyvSZTwdk5gse9flxgxCIdwDMV/view?usp=share_link

the drive link has video of how it affects me

**Comment by synchromesh62** [comment]
Looks like a conflict to me?
Do you still have the old downloadable version installed as well as the Steam one.
