### ISSUE TITLE
GameGuru MAX - Bug - Characters Walking Through Closed Doors

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3902]
I've found that if you load a saved group into your level, it totally prevents the creation of a Nav Mesh, regardless of what else is in the level. Here are some screen shots of my test on this:

_This shows a hall segment created using four separate objects - floor, two walls, and a ceiling:_
![nav1](https://user-images.githubusercontent.com/36735507/203243457-3cf8a587-0e6b-44fd-a348-cb66896aa2d5.png)

Notice, the nav mesh is created just fine.

_This shows a hall segment with the above four objects imported as a SINGLE FBX file:_
![nav2](https://user-images.githubusercontent.com/36735507/203243630-5d020017-8bbd-4135-8965-d7398fb77061.png)

Again, the nav mesh is created just fine.

_This shows the hall segment created using four separate objects (just like in the first example), but grouped:_
![nav3](https://user-images.githubusercontent.com/36735507/203243819-6c20cc8a-d64c-437f-bfee-19328dd9155f.png)

Once again, the nav mesh is created as it should.

_And, finally, this one shows the group loaded into MAX after having been saved as a saved group:_
![nav4](https://user-images.githubusercontent.com/36735507/203244091-0d7405ee-6783-478c-897e-8cd92153fa05.png)

Notice that NO nav mesh is created at all. I've even left in some of the previous models (that are not grouped) and still no nav mesh is formed.

**Comment by davetgc** [comment]
I can confirm this, many, if not all objects in an imported group have no navmesh.

**Comment by MonkeyFrogStudio** [comment]
@davetgc It's not that they don't have a nav mesh, it's that a saved group totally prevents one from being created. 

If you create an empty level and place a single barrel in it and an enemy, a nav mesh will be generated. But if you then load in a saved group, then run the level, no nav mesh will be generated at all, even with the original barrel still present in the level. As a result, NPCs cannot move, but can only stand there and shout at you.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Can I confirm this cannot be reproduced with any stock media, just imported ones?  If not so, can be knock up an example with a stock object that shows the same issue as it is always a little easier to reproduce and fix when using stock media :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Welcome back! 

Yes, it does this with stock media. Here are some screen shots:

This is with just a barrel object and a police officer:
![nav1](https://user-images.githubusercontent.com/36735507/204152475-2441a3e5-7f8d-47b3-8bdc-008be3e91944.png)

This is with the barrel object duplicated a few times:
![nav2](https://user-images.githubusercontent.com/36735507/204152500-7f2342b7-da7d-4452-a40d-896adc35dadf.png)

This is with all the barrels made into a group, but the group is not saved:
![nav3](https://user-images.githubusercontent.com/36735507/204152521-cd48f6f5-0020-42fa-860a-0b225b09607a.png)

And this is with the group having been saved and then added to the level:
![nav4](https://user-images.githubusercontent.com/36735507/204152526-d3345cc1-0640-4d5e-9980-19885877777b.png)

Once the saved group is added to the level, the nav mesh is not generated.

**Comment by LeeBamberTGC** [comment]
Fixed in next EXP build

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Latest EXP build fixes the nav mesh issue caused by group objects and other methods to introduce a non-visible object into the level.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC What about NPCs still walking through closed doors?

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC I will experiment with stock assets to see if I can reproduce it and get back to you ASAP.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio No worries, I suspect it was the specific nature of the doors you created but thanks for confirming this as it saved me some time. I will ensure your assets work as intended today :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Is there anything I should be doing differently when creating these doors? Just wanted to check.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Not at all, the engine should be able to handle any obstructive model that is a door, and ensure the navmesh does not allow characters to pass through in the same way the player cannot physically pass through :)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Turns out the difference between some doors and yours is that they were offset from center and the nav mesh coordinate for the block was far away from the center of the visible door.  I have updated the three door scripts so they now use the visible objects center for the coordinate rather than the original entity coordinate.  Check out the new EXP build to see if this works for you.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Will test now.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Thanks for this. It "mostly" works. When the door is closed, or opened and then closed, the nav mesh is cut off by the door, as it should be. However, if the NPC has a chance to trace a path through that door (the red line) when it's open, there's a chance they can still get through the door even though it's closed. Now, I am not talking about closing the door when the NPC is almost at the door. I mean even if the NPC is quite a distance away. If that red line is through the door (no matter how far away the NPC is), then he will go through the re-closed door even though the nav mesh is blocked.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Thanks for the feedback. On Wednesday I will look to see if I can cancel nav paths when the nav mesh is updated, that should stop old paths being used to go through doors, etc.  An alternative is to use the block command to check all existing paths and cut them short if they cross through one, that might be a cleaner approach as it would keep any other paths valid if they are not affected.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Latest EXP build adds code to interrupt any old paths after a block action has happened to the nav mesh. This prevents characters from continuing with the old path and disregards existing targeting instructions. They re-acquire the next time they see you.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC That seems to have done it! I can finally block out an enemy by shutting the door! Thank you so very much!
