### ISSUE TITLE
Runtime Error 105: fontbank\FRSCP-Font-24px-Subimages.fnt ()

### ISSUE THREAD

**Issue by mertdemir123123** [TheGameCreators/GameGuruRepo#3903]
Hello, I downloaded the game to steamwork and they told me they got this error, what should I do? I need urgent help.

steamworks error message

Failure:
The build review has failed because the game doesn't launch, and we weren't able to find a solution to get the game working. It's possible there's an issue with the game files, but there might also be one or more missing dependencies.

The issues seems to come from the game engine itself, which allow us to launch from the executable, but not from Steam. We encounter the following errors when attempt to launch the app through Steam:

"D3DX11CreateEffectFromMemory failu... (error message is cut-off)
Effect file not found".

"Runtime Error 105: fontbank\FRSCP-Font-24px-Subimages.fnt ()"

Please test and resolve this launch error issue before submitting for review again.

BuildID: 9996650

**Comment by mertdemir123123** [comment]
@davetgc

**Comment by mertdemir123123** [comment]
@davetgc

**Comment by davetgc** [comment]
Is this with FPS Creator?

**Comment by mertdemir123123** [comment]
> Bu FPS Creator ile mi?

I made a 3d fps game with Gameguru classic, how do I solve this error?

**Comment by davetgc** [comment]
It sounds like the font file is missing, Without seeing the game and the problem in action, it's hard to tell.

**Comment by mertdemir123123** [comment]
> Yazı tipi dosyası eksik gibi geliyor, Oyunu ve sorunu çalışırken görmeden söylemek zor.

I uploaded my game files to yandex, can you check? Please🙏 
https://disk.yandex.com.tr/d/o9Jr0dDym9rUEw[https://disk.yandex.com.tr/d/o9Jr0dDym9rUEw](https://disk.yandex.com.tr/d/o9Jr0dDym9rUEw)

**Comment by mertdemir123123** [comment]
> Yazı tipi dosyası eksik gibi geliyor, Oyunu ve sorunu çalışırken görmeden söylemek zor.

Have you checked, what should I do?

**Comment by davetgc** [comment]
I've not even had a chance to look yet. It could take me a couple of days at least. We don't have enough staff for instant free technical support. I'll investigate this as soon as I have time, but I have a number of other issues to deal with first.

**Comment by mertdemir123123** [comment]
> I've not even had a chance to look yet. It could take me a couple of days at least. We don't have enough staff for instant free technical support. I'll investigate this as soon as I have time, but I have a number of other issues to deal with first. Please be patient.

Thank you, I'm waiting

**Comment by davetgc** [comment]
I've managed to take a look and it launches for me:

![image](https://user-images.githubusercontent.com/99803873/203380602-3a5cd183-d123-44d4-a32a-984a384ffa73.png)

I've also found the files that Steam say are crashing the game and they are in the folder. My guess is it's something to do with the Steam folder configuration., but that's only a guess.

**Comment by mertdemir123123** [comment]
> I've managed to take a look and it launches for me:
> 
> ![image](https://user-images.githubusercontent.com/99803873/203380602-3a5cd183-d123-44d4-a32a-984a384ffa73.png)
> 
> I've also found the files that Steam say are crashing the game and they are in the folder. My guess is it's something to do with the Steam folder configuration., but that's only a guess.
> 
> I can't really help much more as it works for me.
> 
> Have you tried asking a friend to test?

yes, my friend tested it and opened on it.i said that it should open level1exe on steam, but they said that it gave an error, which is very strange

**Comment by davetgc** [comment]
I'm closing this thread as you have started another. Please keep all information in one thread. Thanks.
