### ISSUE TITLE
Add Option to auto-hide Color Picker when user pointer leaves the UI area (and enters the level editor)

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3904]
If you copy the hex code for a light's color to paste it into another light so they match in color using this:

![light_color](https://user-images.githubusercontent.com/36735507/203412955-7fdc5092-4e10-4e9c-8535-b13c629beb80.png)

... instead of the new color code being entered in, MAX will create another light instead. 

Steps to reproduce:

- Create two lights
- Change the color of one light
- Select the code at the bottom of the color-picker and hit CTRL+C
- Select the second light and open its color-picker
- Highlight the code at the bottom and hit CTRL+V to paste in the code from the first light
-  Instead of the selected light's color changing, a new light will be pasted into the scene

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio What may be happening is your pointer strayed into the level editor area when you pasted (/copied) which means you are copying and pasting the light object itself.  When I tried this I saw what you saw, but when I kept my pointer inside the color picker for COPY and PASTE, the color value was copied without any duplication of objects:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/d68353ed-c05d-42b9-ba6a-d66bc9932614)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC This is an old one and it appears to be working correctly for me now. I'll close this one.
