### ISSUE TITLE
Problem with textures

### ISSUE THREAD

**Issue by DvarGame** [TheGameCreators/GameGuruRepo#3905]
when you create a terrain and color it with a texture, then you exit the level while saving it -you re-enter your level all textures are reset

**Comment by synchromesh62** [comment]
This has already been reported and fixed currently in the Experimental Build.
You can try it via Steam. The Beta Code is 
lettesterin456

**Comment by davetgc** [comment]
Closed as a duplicate, but I've added details of how to access the experimental build.
