### ISSUE TITLE
Building Editor Lights ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3906]
Can we have an option to turn off "all " auto lights in the Building Editor
I know there is one for each individual room but that is just annoying and tedious if you want to do your own lighting.

**Comment by ZakJudges** [comment]
Hi @synchromesh62, I have added a tick box that will disable the auto-add light feature for any new rooms created. Your choice of the setting will be retained when relaunching the building editor. The change should be in the next experimental build, just working through some more bugs in the mean time :)

![Screenshot 2022-12-06 103950](https://user-images.githubusercontent.com/32545391/205889781-7f14d37f-a760-4203-b698-6a91b9eb03ab.png)

**Comment by synchromesh62** [comment]
That's Fantastic Thanks Zak

**Comment by synchromesh62** [comment]
> @synchromesh62 A new experimental build is available with the fix and ready to test :)

Hi Zak ... getting the same result here :(
This is the same test model i sent to you.

![SIB1](https://user-images.githubusercontent.com/35708217/206531299-2dc284a0-6c9d-4288-b298-68695ceb9b99.png)

**Comment by ZakJudges** [comment]
@synchromesh62 this experimental contains the fix for Building Editor auto-add lights. Tomorrows experimental will have the importer material fix :)

**Comment by synchromesh62** [comment]
> 

LMAO ..Whoops sorry .. Not even the right Thread :)
That's virgin Email showing me the last clip of a Zak Response with a **View On Github** 
Awesome i will check out the lights .. sorry for the confusion i should look at where i was posting and i would have twigged :)
