### ISSUE TITLE
Do you want to access the experimental build?

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3907]
Hi,

When testing out fixes and additions, we often move them to the Steam experimental build for further testing before adding them the the latest official build. If you'd like to check out what's new, or a looking for a fix that's been made but hasn't moved over to the main build you might want to check it out.

To access the build: Right Click on GameGuru MAX in your Steam library, and select Properties:

![image](https://user-images.githubusercontent.com/99803873/203761686-949cf95e-5d12-4a66-a126-478bf167aa1f.png)

From the GENERAL window,  left click on Betas

![image](https://user-images.githubusercontent.com/99803873/203762078-77b3aa82-8668-448e-a03f-1773e652ae8d.png)

Enter the code: lettesterin456 and Left Click CHECK CODE

![image](https://user-images.githubusercontent.com/99803873/203762428-2472090a-b363-4a55-896a-8d71249bf8db.png)

You'll now be able to select experimental build from the drop-down menu above the code box:

![image](https://user-images.githubusercontent.com/99803873/203762999-fe2dc4a5-c50f-4d13-8eb9-5738530c2220.png)

**Comment by vasilis125koutis** [comment]
thanks
