### ISSUE TITLE
Issue with publishing GGClassic game on Steam

### ISSUE THREAD

**Issue by mertdemir123123** [TheGameCreators/GameGuruRepo#3908]
I made my game with gameguru classic and tested it on 8 computers. It worked flawlessly on all of them and my brother @davetgc tried it too. But then I uploaded my game to steam and they said they got the error I attached to the picture below, I don't know what to do, can anyone help? (even though the file they say they give error is in the game files, my brother @davetgc checked it)
![image](https://user-images.githubusercontent.com/118818388/203768917-b529f98f-9c29-44c0-892f-5f519d2cca05.png)

**Comment by davetgc** [comment]
Also, have you tried adding the build to your Steam library as a non-steam game? This might replicate the error.

**Comment by AmenMoses** [comment]
> Others have successfully published GameGuru Classic games on Steam.

DX11 ones?

**Comment by mertdemir123123** [comment]
> A good point, I'm not sure.

Is there a video on how to do this, can you help me out on youtube or elsewhere?Or if I give you my steam password and username, would you bother to check it out :)

**Comment by davetgc** [comment]
Please don't share your passwords or log in details with anyone.

**Comment by davetgc** [comment]
We're not able to offer support with Steam uploads, sorry. If there is an issue with our software though, we can investigate.

**Comment by synchromesh62** [comment]
What you could try and do is ask any other steam sellers on the Discord perhaps.
Maybe they might be able to shed some light on the problem.

**Comment by mertdemir123123** [comment]
> What you could try and do is ask any other steam sellers on the Discord perhaps. Maybe they might be able to shed some light on the problem.

can i get the discord link

**Comment by davetgc** [comment]
Here you go:

https://discord.gg/SDBqJPrX

**Comment by Teabone3** [comment]
I would assume this is directly related to the fact that users require DirectX to be installed. I had this issue when I did a large distribution of a demo for testing for one of my game demos. It didn't work at all for over 15 people that received the standalone build because they didn't have the DirectX installed that GG games required.

**Comment by mertdemir123123** [comment]
> I would assume this is directly related to the fact that users require DirectX to be installed. I had this issue when I did a large distribution of a demo for testing for one of my game demos. It didn't work at all for over 15 people that received the standalone build because they didn't have the DirectX installed that GG games required.
> 
> A work around, is you create a game launcher installer, and you add DirectX install as an option. Most games back in the day that required DX did the same.
> 
> EDIT: just noticed the error is related to a fontbank file? Does your standalone have the fontbank folder with it?

yes, there is a fontbank file in the game files, what should I do now? If I create a setup file and upload it, will they accept it?

**Comment by mertdemir123123** [comment]
@Teabone3 @davetgc 
They say it works when the game runs normally, but they said they had this problem when they ran it on steam.
![Screenshot_20221128-225558_Chrome](https://user-images.githubusercontent.com/118818388/204369309-73d1cdd2-d93d-4c6e-ae05-3e66e082ef27.jpg)

**Comment by mertdemir123123** [comment]
@davetgc @Teabone3 If I remove the subtitles, do you think the problem will go away?

**Comment by plemsoft** [comment]
@mertdemir123123 Its the working directory that are wrong , check your steam launch settings , I also mentioned this on discord :)

**Comment by LeeBamberTGC** [comment]
@mertdemir123123 Hopefully the above information will help. From the hundreds of GameGuru Classic games that have been published on Steam, and their subsequent slating, we can reasonably confirm that Steam publishing works well :)
