### ISSUE TITLE
My Level is crashing upon start up

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#3909]
https://drive.google.com/file/d/15hkK_LsLbNnj8M41csmP-S19uVuzFMFp/view?usp=share_link

**Comment by RajMaha1** [comment]
Sorry id like to note it happening with all my levels

**Comment by davetgc** [comment]
Do you have custom media?

**Comment by zirathashe** [comment]
> Do you have custom media?

ive had a simular issue as well however it was when i tried to load premade levels that where come with GGMax. the second i try to load them it crashes. i tried uninstalling and reinstalling and it didnt help.
