### ISSUE TITLE
Building Editor - Export does not work when the building is large. GameGuru Max Experimental Build

### ISSUE THREAD

**Issue by janekste** [TheGameCreators/GameGuruRepo#3913]
I can easily export a small building - no problem. But when I try to export a very large building, the building editor crashes to the desktop, closes without an error. In these screenshots, as a test of the possibilities, I tried to build a small city with buildings of two floors. I can build very large buildings. The building editor does a great job with this. But I can't export large buildings, it's impossible - the building editor just closes.
![image](https://user-images.githubusercontent.com/55485525/204160544-19ea7cd7-2c09-4cb1-acd0-27fb4f390789.png)

![image](https://user-images.githubusercontent.com/55485525/204160700-d9a1eb40-656e-425c-ac39-c85ffd03f261.png)

**Comment by janekste** [comment]
There are no warnings for the user about building size limits. The building editor could inform the user about exceeding the limit. So that the user stops increasing the size of buildings in time.

Does this small town really need so much memory? Here are simple square rooms with the same textures. Just squares. I have a good computer i7-6700K, 16 GB RAM, GTX 1070ti 8 GB. I was sure that the building editor would allow me to quickly design a small prototype of the city. I will be able to put a lot of square houses, doors, windows - then export all this, and then in the level editor just decorate with additional models. Or can I just build a maze, a sewer? A big tower? I probably want too much.

Anyway, now you know more about how some weird people like me can use your building editor. I hope that this knowledge will be of some use to you. If a large building cannot be built, I think the editor should somehow inform the user about it.

**Comment by davetgc** [comment]
Thanks. We can talk about this internally, but my guess is most people will feel that the building editor is just that, a system to make buildings, not cities. If you want that, you can make multiple buildings as standalones and import them into MAX. 

I'll mark this as an enhancement for now.

What do others think?

**Comment by MonkeyFrogStudio** [comment]
The scope of the building editor is to do just that create and edit a building (as in a single building). You can then create unique buildings (one at a time), export each, and then, in MAX proper, place them as you please to create a larger scene (such as a cityscape). To me, it's all about the _**intent**_ of the tool. The tool is intended to create a building, not a city.

**Comment by synchromesh62** [comment]
Have to agree with the above that the building editor is exactly that.
You can create big buildings sure but ye i wouldn't expect or even try to create a city. 
It will be even worse when floors are added.

**Comment by Lemuripest93** [comment]
What you can do with the building editor is quite impressive, and i can't wait to see what it'll be like when new versions/revisions come out, but even i have to agree that it's not a city builder, though i've managed to make some decently sized apartment blocks with it, so maybe you can make your city in smaller chunks when performance with Wicked Engine and Max happens? not sure if that will transition over to the building editor as well.

Good looking layout though, especially curious about the two rows of square buildings to the center right, looks like a little market or something. 👍

**Comment by janekste** [comment]
@Lemuripest93 
There are square buildings on the right, there is really a market in the center - you guessed it. Well, then I will build a city in small parts from several buildings at the same time. Anyway, it was just a test. The program allowed me to build a city, but did not allow me to export.

Unfortunately, the program does not inform the user about the restrictions. The program provides a very large construction site and makes me mistakenly think that I can build a very large building.  But the large building area just deceives my eyes. I think that the program should inform the user when his building becomes very large, and that it is not recommended to continue increasing the size.

**Comment by Lemuripest93** [comment]
@janekste If you're able to, you can open the original city file in your screenshot, then erase a few buildings, then save that as "CityPart1".. etc, then just open the original file and rinse and repeat and you have the whole city in multiple parts that you can put back together once exported :)

**Comment by ZakJudges** [comment]
@janekste It's true that we only ever intended for the Building Editor to create single buildings. However, it should still be able to handle very large buildings with the same number of rooms as in your screenshot, so I would consider this a bug. Would you be able to send me the .mbf file for the project in your original post? That will hopefully allow me to find the issue and either fix it or add a warning when nearing the limit. Thanks :)

**Comment by ZakJudges** [comment]
@janekste Thank you for sending that over. I have rewritten the exporter so that it will split up very large buildings into smaller meshes that the engine can handle. It will be in the next experimental build, so you should see the fix by Friday :)
![Screenshot 2022-12-07 113608](https://user-images.githubusercontent.com/32545391/206170355-83582010-608a-46bc-a653-b38c2ef2c95a.png)

**Comment by synchromesh62** [comment]
> @janekste Thank you for sending that over. I have rewritten the exporter so that it will split up very large buildings into smaller meshes that the engine can handle. It will be in the next experimental build, so you should see the fix by Friday :) ![Screenshot 2022-12-07 113608](https://user-images.githubusercontent.com/32545391/206170355-83582010-608a-46bc-a653-b38c2ef2c95a.png)

That's kind of impressive !!
Great work Zak making that possible

**Comment by ZakJudges** [comment]
@synchromesh62 Thanks! I will still most likely add a warning with very large scenes as eventually the export would have too many meshes for Max to handle in a single object. Though I suppose we could also take it one step further, and split cities across multiple Max objects, since the export is just a smart object. Though that is outside the scope of the Building Editor, at least for a V1 release :)

**Comment by janekste** [comment]
@ZakJudges Your work impresses me! I didn't expect you to do that! But you did it! Thanks! 

I'm looking forward to the next update. But I think it's still necessary to add a warning to the user that his object is very large.

**Comment by Lemuripest93** [comment]
@ZakJudges Man you do God's work, this means everyone else will also be able to make much larger and much more impressive buildings, thank you so much 🙏

**Comment by ZakJudges** [comment]
@janekste A new experimental build is available with the fix, and ready to test :)

**Comment by janekste** [comment]
I confirm. Now I can export very large buildings.
