### ISSUE TITLE
Click on the preview of the 3D model in the library of objects - CRASH. GameGuru Max Experimental Build

### ISSUE THREAD

**Issue by janekste** [TheGameCreators/GameGuruRepo#3914]
Crash when I try to preview 3D models in full screen. This happens with all models in the object library. Big and small, it doesn't matter. GameGuru Max always just closes.

![image](https://user-images.githubusercontent.com/55485525/204383058-e124aab6-ebaf-48b0-8568-54526117f576.png)

**Comment by davetgc** [comment]
Have you added any custom media? I've noticed that non-MAX media, can sometimes cause a crash.

**Comment by janekste** [comment]
Yes, I added my custom models many months ago. At that time, everything was ok! I discovered the crash recently in the last public update. In the experimental build, too, crash. Crash occurs with all models without exception, both with GameGuru Max models and with my own. And I added one model a few days ago.

**Comment by davetgc** [comment]
So, it's crashing when there is no image being shown?

**Comment by janekste** [comment]
Just look again at the screenshot I posted. I click on the "Full screen Preview" button and immediately after that a crash occurs. I do not know how I can explain this in more detail.

The model should open to full screen for preview, but it doesn't open. It just happens to crash immediately when I click that square button in the screenshot.

**Comment by davetgc** [comment]
A couple of people have had the same issue, but we've not been able to reproduce. It happened to me twice, and then stopped happening, even on the same build, so this one could be difficult to track down, but thanks for the information and who knows, it could turn out to be easy.

**Comment by janekste** [comment]
This problem disappeared when you brought back the DX11. I can't reproduce this problem anymore.

I confirm. Fixed.

**Comment by LeeBamberTGC** [comment]
@janekste Many thanks :)
