### ISSUE TITLE
game guru max issue

### ISSUE THREAD

**Issue by vasilis125koutis** [TheGameCreators/GameGuruRepo#3915]
i have create a island and with beatch an grass and save the level all beatch and texture terrain is lost and all green again (basic texture) very bad all paths lost from textures and all basic texture green

**Comment by davetgc** [comment]
This is a known bug that has been fixed in the experimental build. You can find details of how to access this build in the pinned thread at the top of this list. Please test your level using that build.

Thanks.

**Comment by vasilis125koutis** [comment]
latest from steam version game guru Max

**Comment by davetgc** [comment]
Hi, yes, the Steam version currently has that bug. It has been fixed, but is being tested, you can access the build with the fix by following the instructions here:

**Comment by vasilis125koutis** [comment]
Ok
