### ISSUE TITLE
GameGuru Max Check for updates

### ISSUE THREAD

**Issue by EssChipmunk** [TheGameCreators/GameGuruRepo#3918]
I am getting an error :- Update to version: Not found when trying to check for updates.
[GG Update.docx](https://github.com/TheGameCreators/GameGuruRepo/files/10134837/GG.Update.docx)

**Comment by synchromesh62** [comment]
Max went Steam only a couple months ago now. The downloadable build is no longer supported but you will find a steam key in your TGC account under **Product Keys**

**Comment by EssChipmunk** [comment]
Thanks for getting back to me.
However, I don't have a product key for GameGuru Max in my list of steam keys

________________________________

**Comment by synchromesh62** [comment]
> 

Ok thats odd but is usually because a different Email was used to order Max.
Do you have another Account ? 
If not, then you can contact Customer support via the website, and they can track it down but don't worry its somewhere :)

**Comment by LeeBamberTGC** [comment]
@EssChipmunk I have included a link to the technical support page to ask for your key, remember to provide the email you used when buying from TGC: https://www.game-guru.com/contact
