### ISSUE TITLE
MAX - Font Control 

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3920]
Can we have 'right justified' for fonts please

We have TextCenterOnColor

Can we also have TextRightJustifyOnColor

Thanks for considering :)

**Comment by Necrym59** [comment]
Cant we just use windows fonts and drop the old font systems its so cumbersome really

**Comment by OldFlak** [comment]
Yes system fonts would be great.
However I was under the impression that using system fonts was a bit of a resource hog? - @LeeBamberTGC 
- if so a tool or a link to a tool for creating our own sprite font would be nice.

**Comment by OldFlak** [comment]
We can already use any windows font in the screen editor - we just copy it over to editors\templates\fonts.
So being able to use it in-game and via lua would be awesome :)

**Comment by Melburnian70** [comment]
I would also love to see these options for text on Buttons:
- Left-justified text
- Other text settings such as colour, size, offset, etc available on the Highlighted and Selected states of Buttons

And, Button sound for Highlighted state of Buttons
:)
