### ISSUE TITLE
Building Editor - CRASH, if I use custom textures\3D-models and try to save\export a building. GameGuru Max Experimental Build

### ISSUE THREAD

**Issue by janekste** [TheGameCreators/GameGuruRepo#3921]
GameGuru Max Experimental Build

When I use standard textures, then everything is fine! But if I use my custom textures, then I can't save and export the building. The program just closes. Crash. The crash only happens when I put custom textures in my project in my documents.

In the screenshots you can see that I use custom textures. I created my own folder with textures in DDS format and placed it in "Documents\GameGuruApps\GameGuruMAX\Files\texturebank\user"

Then I select this folder in the building editor. All textures are working, displayed. But the program does not allow me to save and export the building. Crash. It seems that the program doesn't like the fact that I put custom textures in my documents in the GameGuru Max "Documents\GameGuruApps\GameGuruMAX\Files\texturebank\user".

But if I put my custom textures in the root folder "steamapps\common\GameGuru MAX\Files\texturebank", then everything works, then I can save and export the building with custom textures.

In addition, I will say that I tried to add my custom 3D models of windows, stairs, doors to the building editor. When the models are in my documents "Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user", then the building editor does not see custom models of windows, doors, stairs. But if I add models to the root folder "steamapps\common\GameGuru MAX\Files\entitybank\User", then the building editor starts to see all the custom models. Conclusion: the building editor does not know how to correctly read custom textures and custom models from my "documents\GameGuruApps\GameGuruMAX\Files\"

![image](https://user-images.githubusercontent.com/55485525/205465799-34239e73-ed18-4736-a792-7bddda1af71f.png)
![image](https://user-images.githubusercontent.com/55485525/205465802-1f1a8f1d-35d4-4c90-aef5-e4e58d8251df.png)

**Comment by janekste** [comment]
@ZakJudges Is this fix coming out on Friday? Or is the fix already out? I have GameGuru Max yesterday on Tuesday received an update. Is this fix included in this update yesterday on Tuesday?

I tested the custom textures yesterday after the update. They work. Here is my new screenshot.

But I also told you about the same problem with custom 3D models. Have you fixed that too? Or not? I have added my custom balcony models to the building editor. You can see the balcony in the screenshot. When I put the balcony models in my documents in my project "Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user", then the building editor does not see these balconies. But if I put my custom balcony models in the directory where the GameGuru Max program is installed "steamapps\common\GameGuru MAX\Files\entitybank\User", then I can use my models in the building editor.

There is no "balcony" category in the building editor, so I put my balcony models in the "doors" category.

![image](https://user-images.githubusercontent.com/55485525/206204510-96a7df0d-d351-46ca-a781-f8ecd4e3f853.png)

**Comment by janekste** [comment]
@ZakJudges I confirm. Everything is fixed.

**Comment by ZakJudges** [comment]
@janekste Thanks for confirming :) Closing this issue
