### ISSUE TITLE
Black Screen in Builder Editor

### ISSUE THREAD

**Issue by zirathashe** [TheGameCreators/GameGuruRepo#3923]
trying to load up the builder editor comes up with a black screen and nothing i do fixes or changes it. cant see what im doing.
![Screenshot (35)](https://user-images.githubusercontent.com/58756931/205468135-e1cb7342-9168-4c16-9a41-0258825ebc64.png)

**Comment by ZakJudges** [comment]
Hi @zirathashe, could you post your system specs below? There is a known issue with AMD cards where newer drivers result in a black screen in Max. Could you try and change your driver to 22.5.1 and see if that sorts the issue for you?

**Comment by zirathashe** [comment]
yeah, im using amd unfortunately. give me a minute to look up the specs

**Comment by zirathashe** [comment]
> Hi @zirathashe, could you post your system specs below? There is a known issue with AMD cards where newer drivers result in a black screen in Max. Could you try and change your driver to 22.5.1 and see if that sorts the issue for you?

i just looked. i have 22.11.1
im trying to figure out how to downgrade right now,
