### ISSUE TITLE
GameGuru MAX - Request - Gizmo to Stay Transition/Rotate/Scale Until Changed

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3924]
Currently, if you change the gizmo via the hot keys (F2, F3, and F4) to switch between translate, rotate, and scale, if you click off the object and onto another, the gizmo reverts back to translate. I would like the gizmo to keep whatever the last selected mode was until I decide to change it. Therefore, if I've hit F3 to change it to rotate, I want it to stay in rotation mode even if I select a different object. This way, if I want to rotate a bunch of objects I can just select, rotate, select, rotate, etc. How it is now, I have to hit F3, rotate the object, select the next object, which changes the gizmo back to translate, hit F3 again, rotate, and rinse-and-repeat for each object.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Fixed for the next EXP build, I agree this one was a little annoying after the thousanth F3 press :)

**Comment by MonkeyFrogStudio** [comment]
Yep! Works with the latest build! Thanks!
