### ISSUE TITLE
GG Classic guns don't fire

### ISSUE THREAD

**Issue by Zeus2015** [TheGameCreators/GameGuruRepo#3925]
Hi,
Guns don't not fire with simulated Sky Release 2022.11.1 and 2022.12.6. 
GameGuru Classci (publicpreview).
![gunsdontfire](https://user-images.githubusercontent.com/10551167/205496421-45ac4621-e96b-4c64-8125-85b97e3b15a8.jpg)

**Comment by Zeus2015** [comment]
@LeeBamber 
No fires. !

https://user-images.githubusercontent.com/10551167/206769432-97ddccaf-412b-4fbe-9201-7de5a2b0465b.mp4

**Comment by Zeus2015** [comment]
@LeeBamber 
No fires. !

https://user-images.githubusercontent.com/10551167/206769432-97ddccaf-412b-4fbe-9201-7de5a2b0465b.mp4

**Comment by cybernescence** [comment]
Fixed, needs TGC review and release when possible: https://github.com/TheGameCreators/GameGuruRepo/pull/4013

**Comment by Teabone3** [comment]
I've also experienced this new issue.

**Comment by LeeBamberTGC** [comment]
@Zeus2015 Fixed for next Classic update, thanks Cybernesence :)
