### ISSUE TITLE
Thirdperson character does not play animation

### ISSUE THREAD

**Issue by HierToo** [TheGameCreators/GameGuruRepo#393]
The thirdperson character does not play his animation anymore when the player moves/jumps.
Maybe this has something to do with the removed csi animation

Testcase:
Add a character on the startmarker and test the game.

**Comment by LeeBamberTGC** [comment]
Is this with the latest Public Preview?  What character do you drop into the starter marker?

**Comment by HierToo** [comment]
I use the latest version in the repository. It is Version 2018.09.23.  Here is a testmap:
[third_person_animation_missing.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2424568/third_person_animation_missing.zip)

**Comment by LeeBamberTGC** [comment]
Good catch, I have updated the repo with the changes which solves this issue.
