### ISSUE TITLE
Gameguru MAX - Bug - Zombies not moving

### ISSUE THREAD

**Issue by GavinIssooocoool** [TheGameCreators/GameGuruRepo#3930]
hey there. so I have a small issue. when i use zombies in a game, they do not move. any idea how I can fix this???

**Comment by synchromesh62** [comment]
You mean they won't chase you or follow flags they are attached to?

**Comment by GavinIssooocoool** [comment]
yes, they will not chase the player

**Comment by LeeBamberTGC** [comment]
@GavinIssooocoool A recent nav mesh fix in the latest EXP build may have fixed this, worh a retest.

**Comment by GavinIssooocoool** [comment]
yea that fixed it, thank you!
