### ISSUE TITLE
GameGuru Max - Bug - Building Editor - Large Warehouse Door Gets Closed By Other Doors

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3931]
When you open the large warehouse door, then go to another door - for instance another large warehouse door and open it, it closes the previous one(s), this is the only door that i've discovered having this problem.

Video Demonstration: https://www.youtube.com/watch?v=wDady88ugUU

In the video above i also demonstrate the translucency with the green/grey warehouse door that i commented on in a previous post (#3846), though it's not the focus of this post, just wanted some video evidence of it.

**Comment by MonkeyFrogStudio** [comment]
The large warehouse door uses the **_Door Sliding_** behavior, doesn't it? It seems that the script has a bug in that "E" will only open the door when you're within proximity (as it should), but will CLOSE any opened door in the level, no matter how far away it is.

**Comment by synchromesh62** [comment]
This one is confirmed and currently being investigated by Necrym59

**Comment by ZakJudges** [comment]
@Lemuripest93 Thank you for reporting this issue. A fix should be in tonight's experimental build :)

**Comment by ZakJudges** [comment]
> 


> This one is confirmed and currently being investigated by Necrym59

Somehow I did not see this, it's possible Necrym has already sent the updated script to Lee. But one way or another, there will be a fix :)

**Comment by Lemuripest93** [comment]
My apologies for not responding back, been busy, but i can now confirm that this is fixed - i'll close this as a result.

Good work 👍
