### ISSUE TITLE
Light rays and clouds are visible through doors

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#3932]
![Screenshot 2022-12-06 110611](https://user-images.githubusercontent.com/32545391/205895396-1df28db3-1502-44f1-8577-0c722afe5e6a.png)

**Comment by ZakJudges** [comment]
Note: the door in the screen shot is Warehouse - Green Door

**Comment by davetgc** [comment]
Just to add to this, they can also show through player held weapons. :(

**Comment by LeeBamberTGC** [comment]
Six doors fixed to now be non transparent fixing this one:
![image](https://user-images.githubusercontent.com/35840583/230509151-66fb5289-f0b4-4822-ae7d-ffa2714fd5b3.png)
