### ISSUE TITLE
Importer error in latest build ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3933]
If your using Multi Materials then all the other materials are called **Sibling Frame** and are not selectable to edit separately.
Im assuming this is a bug or unfinished from the update ?

Usually i can select all the individual materials on the right.

![S1](https://user-images.githubusercontent.com/35708217/206297323-ba9cbf6c-8eb1-479b-ac98-8b0463ea821f.png)

Now there is nothing there except **Sibling Frame** 

![S2](https://user-images.githubusercontent.com/35708217/206297465-57ec1b04-882c-4377-9024-db7592e6b726.png)

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 Interesting. I'm not getting that on my end. I just imported an object today made up of four objects, each with it's own material. When I go to the Materials tab on the right and hit the drop down, all the materials are there, properly named.

And, yes, I am on the latest experimental build. 

I wonder what's going on here?

**Comment by synchromesh62** [comment]
@MonkeyFrogStudio 
Ok that's a bit worrying ... The lower pic shows one of my current models by just selecting it then enabling Custom Materials in the editor but the exact same thing happens on Importing, Yet build 19-8-2022 still works just fine which i used to take the top pic

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 
I get the same thing with your test model - sibling frame. I wonder if it has to do with the X format somehow? Have you tried testing with FBX or GLB?

**Comment by synchromesh62** [comment]
> @synchromesh62 I get the same thing with your test model - sibling frame. I wonder if it has to do with the X format somehow? Have you tried testing with FBX or GLB?

Yes i can export to .fbx from sketchup but all the textures are exported as _1.png, _2.png, _3.png etc with a few unknowns and pretty much unidentifiable in Max. It probably is to do with the ,X format but its always been so perfect for me.

**Comment by MonkeyFrogStudio** [comment]
Right. What I was trying to nail down is if this is an X format issue in the MAX importer. If so, then that helps to narrow the field a bit for Zak. ;)

**Comment by synchromesh62** [comment]
> Hi @synchromesh62 Thanks for reporting this. I have added a fix which should hopefully be in the next experimental build. This was caused by my previous fix of ensuring that the names that were imported with ASSIMP were retained. However, in this case, there were no names imported by ASSIMP (possibly a quirk of the ASSIMP .X file importer) - this confused the material dropdown, since all the meshes were named the same "sibling frame". I have added a check for this and if there are no names to use, the dropdown will use whatever material is currently applied to the mesh, as before :)

Zak i love you :)
I know .x is old school now but my method is all i know and it works flawlessly for me.
Thanks so much

**Comment by ZakJudges** [comment]
@synchromesh62 Most welcome! It's definitely worth giving it a good test with various models to make sure it works in all cases, but the model posted above seems to work just fine now :)

**Comment by ZakJudges** [comment]
@synchromesh62 The fix is now available in the latest experimental :)

**Comment by synchromesh62** [comment]
> @synchromesh62 The fix is now available in the latest experimental :)

So far so good .. No issues so far. Thanks Zak :)

**Comment by ZakJudges** [comment]
Thanks for confirming :) closing this issue
