### ISSUE TITLE
A question about Recommended Requirements

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#3934]
Are there any plans that the Performance of the Game engine will chnage because the the rexcommended spec is a gtx 2070. and it would be nice if more other could play my game on there hardware. because getting nowhere with gtx 3050ti, but i am getting forward with my gtx 3080?

**Comment by ZakJudges** [comment]
@RajMaha1 At the moment, the games created with GameGuru Max will have the same minimum spec as GameGuru Max itself. There will be optimizations in the future that should benefit lower-end hardware so it is possible that the minimum spec could be lowered in future. But no firm information yet :)
