### ISSUE TITLE
GameGuru MAX - Bug - Material Names Not Correct

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3935]
@ZakJudges 

I think there is still an issue with the MAX importer and material names for models. I'll provide an illustration.

Here is a simple setup in Blender:

![blender](https://user-images.githubusercontent.com/36735507/206418283-15780d9c-36d7-465d-afc8-679bfaf03152.png)

It consists of three cubes, each with their own material. The names of the materials are Red_M, Blue_M, and Green_M. The textures used are named red.png, blue.png, and green.png. When I export the three cubes as a single object in FBX format, this is what I get in the MAX importer:

![max_import](https://user-images.githubusercontent.com/36735507/206418560-de9c3226-e0c6-4974-b4f5-4e7f878efc5d.png)

The object comes in fine with the materials applied properly, but if you look at the actual material names, they are "red", "blue", and "green". 

Of course, it's the same once in MAX proper:

![in_max](https://user-images.githubusercontent.com/36735507/206419064-21a1c80a-3fe9-4d6e-a0e9-2b8e0763b2db.png)

This seems to indicate that the MAX importer is drawing material names, NOT from the model, but from the textures being used with each object. Since the red cube is using red.png, it doesn't seem to mater that the actual material name applied to that cube is "Red_M". 

Material names can often NOT be named like the textures that make them up are. I may have a material name called, "Desk_Top_M" and it might use an albedo texture named, "wood.png". When imported and the material list accessed, I should see "Desk_Top_M" there.

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Thanks! I will definitely keep an eye out on this one.

**Comment by ZakJudges** [comment]
@MonkeyFrogStudio The fix should now be available to test in the latest experimental. Thanks :)

**Comment by MonkeyFrogStudio** [comment]
This appears to be fixed! Thank you!!!
