### ISSUE TITLE
GG Max - Latest Exp build - AI Not activating until Player is in Line of Sight of AI

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3937]
As the title says, The AI has once again stopped activating until either the AI is in the view of the player, or very close to the player.
This is happening even though the player is within the 3000 distance of the AI, and also happening if the AI is set to Always Active.

Cant really have a game where AI is this dumb and does not activate until the player actually sees the AI.

I have added a photo to show that am very close to the AI and it is still stood in the starting pose.
This AI is suppose to be walking around the square.

![AI Not activating](https://user-images.githubusercontent.com/66874403/206481534-6161b2a9-c486-4504-8976-9e99b3654914.png)

**Comment by Tum1370** [comment]
Here is another very simple example of the AI not even activating until the player has line of sight with the AI.
Once line of sight has happened, the AI starts walking the path.

The first 2 pictures are showing the AI not activated in T Pose.
The 3rd picture shows the AI Start walking the path after my player had LINE OF SIGHT to the AI

The 4th picture shows the very simple setup. The Enemy AI behind 4 Sandbag Barrier, 2 flags for the path, The AI can be set to Always Active or not.
It will never start walking the path, until either the player has LINE OF SIGHT, or the AI Hears movement,

![0](https://user-images.githubusercontent.com/66874403/208315380-b1117ae8-89a5-46db-8c1e-3d7d645b1f89.png)
![1](https://user-images.githubusercontent.com/66874403/208315385-3cb64dd5-03e8-4282-a8e1-ee27ea5d3c8d.png)
![2](https://user-images.githubusercontent.com/66874403/208315390-a2645033-e19d-4cb3-9e25-fc45d25972a3.png)
![4](https://user-images.githubusercontent.com/66874403/208315635-a23814da-dba1-42d4-a90f-7cb72f4a39ef.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Added two new tweaks to the latest EXP build. The engine uses a head height line of sight check by default which makes more sense when looking at characters behind sandbags, and a second tweak so if Always Active is set to ON then the character will activate right away without needing a line of sight check.

**Comment by Tum1370** [comment]
@LeeBamberTGC Thanks Lee,
I have just had a quick test of this. 
I can see that the AI behind Sandbags starts moving now, when within range.

I also tested by having a AI inside a warehouse, and a path that lead outside the warehouse. This AI was set to Always Active.
This AI did not activate, even though it was set to Always Active.

I then retested, and set the AI behind the Sandbags, to Always Active, But moved my starting position to further than the 3000 range. This AI did activate.

I have added the fpm map file so you can see. 
The table is stretched to the maximum 3000 range that the AI activates without been always active. 
The player has the patrol rifle so you can use scope and check when AI starts to move.
As you move slightly forward in to the 3000 range, the Sandbags AI starts to walk, as you can see.

But the AI inside the warehouse, Is set to Always Active, But he does not activate at all, whereas he should be walking his path from the game start.

I hope this simple level shows you what is wrong etc

Thanks
[AI TEST LEVEL.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10279257/AI.TEST.LEVEL.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 I deleted the sandbag character and moved the warehouse one in front of the window so I could test better.  I noticed in the level attached the warehouse character had always active set to NO. I changed to YES and he started his patrol right away:
![image](https://user-images.githubusercontent.com/35840583/208965187-c4d6f5f5-793f-4c3a-abc4-ef4b4734d127.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC AH, just rechecked it and see it was not set to always active. I must off accidentally removed it when testing something else.
Thanks again for the fix, ill close this one off.
:)
