### ISSUE TITLE
Door script issue.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3938]
When a door is opened by pressing E, it works perfectly when opening it, but you can close it from any distance.

**Comment by MonkeyFrogStudio** [comment]
In fact, if there are more than one door, one open and one closed, then pressing E to open the one door will close the other, no matter where it is in the level. This is for the Sliding Door behavior, btw. Haven't tested with the other door scripts.

Pressing E may close any and all opened doors in a level.

**Comment by davetgc** [comment]
@MonkeyFrogStudio - Thanks for the additional information.

**Comment by ZakJudges** [comment]
same issue as #3931

Awaiting confirmation of fix in tonight's experimental build

**Comment by ZakJudges** [comment]
Confirmed fixed in 3931
