### ISSUE TITLE
The building editor breaks the AI of enemies. Enemies lose navigation skills. GameGuru Max experimental build.

### ISSUE THREAD

**Issue by janekste** [TheGameCreators/GameGuruRepo#3939]
The building editor breaks the AI of enemies. Pay attention to the navigation grid. In the second step, the navigation grid disappeared. I lose the ability to see the navigation grid, and the enemy loses his AI - he can no longer move. The navigation grid disappears only when I put buildings created in the building editor on the level. And then the AI will be broken.  I explain step by step. 

Step 1. I'm creating a new level. I'm putting one enemy soldier on the level. I use the "Character Attack" behavior. Starting the level. The enemy soldier is chasing the player, shooting at the player, looking for a way. Everything is OK!

Step 2. I add any one building to the level. The building was created in the Buildings editor. I'm running a level test. The navigation grid display has disappeared. The enemy soldier loses AI, lost the ability to navigate, stands like a pillar. Now the AI is completely broken. It is useless to remove the building from the level. AI at this level is now broken forever. The navigation grid has disappeared forever and is no longer being created.

![image](https://user-images.githubusercontent.com/55485525/206563371-7b6559e1-1fc8-489a-9076-abce25b13eb0.png)
![image](https://user-images.githubusercontent.com/55485525/206563619-275264d1-cab5-4bc3-81d6-91019a5f2463.png)

**Comment by MonkeyFrogStudio** [comment]
This looks like it may be related to this one:

https://github.com/TheGameCreators/GameGuruRepo/issues/3902

**Comment by extremestrategy** [comment]
I've noticed the exact same thing, when a building from the building editor is used the NPC's will no longer move, however they will still attack each other.

**Comment by LeeBamberTGC** [comment]
Fixed in next EXP build

**Comment by janekste** [comment]
I confirm. Fixed.
