### ISSUE TITLE
Medieval and fantasy weapons dont work no more

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#3940]
From Steam: medieval and fantasy weapons dont work no more(that is a bug, yes?), but thank you for the extra simulated nightsky ^^

**Comment by cybernescence** [comment]
Probably related to this fix: - needs TGC review and release when possible: https://github.com/TheGameCreators/GameGuruRepo/pull/4013

**Comment by LeeBamberTGC** [comment]
@cybernescence Confirmed the fix, thanks!
