### ISSUE TITLE
Melee armed Characters hardly responding when player is close.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3942]
Melee Characters are generally now ignoring the player. Melee characters swing once and then stand around.  This is a new issue, since the last experimental build. This seems to be range related, as you need to stand right next to a character, almost touching for them to continue to attack.

The shooting attacks seem to work normally.

**Comment by LeeBamberTGC** [comment]
@davetgc Just tried the PUBLIC build dropped in an AZTEC built for melee and a zombie, then changed it to Melee attack with melee weapon, both worked fine and bashed my head in:

![image](https://user-images.githubusercontent.com/35840583/206733389-504eae77-0e62-418c-9bfc-a5c8b1399c40.png)

Is your bug related to the EXP build or the PUBLIC release?

**Comment by davetgc** [comment]
Hi Lee,

PUBLIC release for me. I also had several characters, maybe it's related to the number.

**Comment by LeeBamberTGC** [comment]
@davetgc Can you send me your level. Also check the EXP build that I have just uploaded, see if get the same thing :)

**Comment by davetgc** [comment]
Hi,

Same issue with the new build. Sending FPM.

**Comment by davetgc** [comment]
Well done Lee.
