### ISSUE TITLE
GG Classic: Runtime Error 7018 () on Character Creator

### ISSUE THREAD

**Issue by THughto82** [TheGameCreators/GameGuruRepo#3944]
When I recently got on GameGuru Classic, I tried to make a basic character, with which I've never had any problems. However, now it just shows a runtime error (Runtime Error 7018 ()) and crashes, then restarts. I've verified file integrity on Steam but still cannot run the character creator. Please help me.
![Game Guru -  Editor  12_9_2022 10_15_51 PM](https://user-images.githubusercontent.com/120233265/206826594-4f5f401a-bad2-4b8d-800e-9e62da105a2a.png)
![Error 12_9_2022 10_17_05 PM](https://user-images.githubusercontent.com/120233265/206826597-64ed053f-f930-4900-86c7-15c79cda9025.png)

**Comment by LeeBamberTGC** [comment]
@THughto82 Added extra information for this specific error message in the NEXT BETA build, switch your branch to it and it should update this evening for you to provide which file is not being found and loaded, thanks!

**Comment by LeeBamberTGC** [comment]
@THughto82 No other reports on this and also made recent fixes, so closing this for the mo:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f42fadbe-266a-46ff-839e-b9393f899ad3)
