### ISSUE TITLE
using empty project

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#3950]
when i fill in the empty space with grass and save it when i choose to re edit it the grass has gone not holding the saved project it is just empty again

**Comment by MonkeyFrogStudio** [comment]
Just checking - but when you're using an empty, did you open the View Options panel and ensure that Vegetation is checked for both Editor and Level?

**Comment by zeebon** [comment]
No I didn’t but it never happened before but I will check anyway

Sent from my iPhone

On 11 Dec 2022, at 19:23, MonkeyFrogStudio ***@***.***> wrote:

﻿

Just checking - but when you're using an empty, did you open the View Options panel and ensure that Vegetation is checked for both Editor and Level?

**Comment by zeebon** [comment]
Yes both are checked in the option panel tried the auto fill on empty the auto fill tree works but the vegetation doesn’t

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ZakJudges** [comment]
Hi @zeebon, I wasn't able to reproduce this issue. Would you be able to post extra steps to reproduce, or a video? Thanks :)

**Comment by ZakJudges** [comment]
Closing this issue due to being unable to reproduce and lack of info. If the problem persists, feel free to reopen.
