### ISSUE TITLE
MAX - Experimental - Storyboard Issues

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3952]
In the latest build (2022.12.13) the storyboard is not working very well.
- The right Panel does not have a scroll bar - so can't get to controls at the bottom
- The screen image does not scale like before even in preview

![image](https://user-images.githubusercontent.com/12246318/206935551-9d40e493-fa31-4638-9030-2c7f80ba6849.png)

**Comment by ZakJudges** [comment]
Hi @OldFlak, thank you for reporting these issues. I have added a fix for the missing scroll bar, should be in an experimental build tomorrow.

> The screen image does not scale like before even in preview

I am not too sure what you mean here. Is this an issue with the backdrop image? Thanks :)

**Comment by OldFlak** [comment]
Thanks Zac - yes scroll bars are back - awesome!

The second issue is with the way the images scale (or rather don't) :)

I rolled back to 2022.08.19 and took a couple screenies to show the issue
Will use the Title Screen as an example. Resolution is 1920 x 1080.
In the editor:
![Title Screen - Editor - 2022 08 19](https://user-images.githubusercontent.com/12246318/207142557-7ecdf6bc-9d1d-4c7c-94e3-40abc2fc6984.png)

This is in preview:
![Title Screen - Preview - 2022 08 19](https://user-images.githubusercontent.com/12246318/207142650-44d7d44a-fe72-402c-9f7b-ded5dff9e664.png)

In both images note how the background image is scaled properly to fit the window

This is how it looks in current Exp:
Editor:
![Title Screen - Editor - Exp](https://user-images.githubusercontent.com/12246318/207154330-176282ae-d726-4ecc-af97-d6bb4a5dada4.png)

Preview:
![Title Screen - Preview - Exp](https://user-images.githubusercontent.com/12246318/207154999-8d5b43c1-baf4-48bf-a679-54c3ab4b7b1d.png)

**Comment by OldFlak** [comment]
There are a few things that would be nice to have:

An on-hover sound for buttons would be cool.

It adds a bit of coolness to your game when you use semi-transparent images for in-game pause screens.
This really requires two images for Save and Load screens:
- One for in the main game menu - this one would not use transparency
- The second one for in-game Pause screens - this one does use transparency if desired

Thanks for considering :)

**Comment by OldFlak** [comment]
Thanks Zac
Yes, I did query 'bachdrop zoom' and 'backdrop strecth' when storyboard was first added - thought it was back-to-front :)
Will check build out when it gets to Steam

**Comment by OldFlak** [comment]
@ZakJudges this issue is resolved - thanks :)
