### ISSUE TITLE
MAX - Audio Playback Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3954]
It has been the same since Classic and all versions of MAX

If you play a sound in-game - it is **not** as loud as it is if you play the same sound with windows media player.

Same can be said for both ogg and wav.

**Comment by LeeBamberTGC** [comment]
@OldFlak Sound playback was recently changed to fix the 3D sound system. Most sounds played in game use the 3D sound system which modulates both volume and distance of the sound, so it will not be as loud as the raw WAV being played.

**Comment by OldFlak** [comment]
OK thanks Lee, understood - will close this issue :)
Thanks for looking into it.
