### ISSUE TITLE
GameGuru MAX - Bug - Test Level Bright at First

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3955]
With the last few builds, including the previous DX12 build, when I run a test game, the level many times starts out bright and then the brightness adjusts, as if auto-exposure is turned on, but I have that setting turned off:

![expose2](https://user-images.githubusercontent.com/36735507/207058528-b8beb32b-cab2-44b3-9dd6-c0518e7f72b9.png)

Here's a video of what's happening:

https://user-images.githubusercontent.com/36735507/207058566-66aa712f-55b8-411c-92e1-f98ccfcd9407.mp4

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio This is an oldie, related to the early poor env map system. Fixed now :)
