### ISSUE TITLE
GameGuru Max - Shooter Game Genre Filter, Game Elements didn't show up

### ISSUE THREAD

**Issue by ascaryaaa** [TheGameCreators/GameGuruRepo#3956]
I saw on the youtube tutorial that if I click the Shooter Game Genre Filter there will be some game elements icon that will show up, but somehow it didn't show up in my GameGuru Max level editor.
This is the screenshot of my GameGuru Max level editor.
![image](https://user-images.githubusercontent.com/73589875/207070395-ecf8d2be-6ade-4c70-ba48-2f3d80d94988.png)

This one is from the official youtube tutorial.
![image](https://user-images.githubusercontent.com/73589875/207070710-3c30b925-ae61-43f7-b467-1975490edffd.png)

Is this because of the version? or are there any settings that I need to do to have those elements? I'm so confused

**Comment by MonkeyFrogStudio** [comment]
This is not how that works. Activating Shooter does not open up new icons on the UI. Instead, it gives you access to logic nodes to connect with objects, in your level, that can take advantage of this system. For example, you can click the Shooter icon and then you can connect NPCs to a trigger point that will warn them if the player crosses the trigger. Or you can connect a switch to a door (if these items have Behaviors attached to them, etc.).

You can learn a bit about it in the User Guide here:

https://gameguru-max.document360.io/docs/shooter-logic
