### ISSUE TITLE
GGMAX - Exp build 2022.12.13

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3959]
Not sure about even listing probelms with the exp builds but here goes just in case they get missed
1. Zone to Zone no longer triggers anything, it used to.
2. Winzone or endgames doesnt work eg: JumpToLevelIfUsed(e) is not working

**Comment by LeeBamberTGC** [comment]
@ZakJudges Can you check these out for me while I work on the new feature for the next booster, thanks!

**Comment by ZakJudges** [comment]
Hi @Necrym59, thanks for reporting these issues. Whilst testing the Winzone "Go to specific level" feature, I encountered a crash in standalone when loading a level after the JumpToLevelIfUsed() command was used. I have fixed the crash and now it works correctly on my side - hopefully that was also the root cause on your side.

Regarding Zone to Zone visual logic, it looks like there is no code to handle this - all cases just say "do nothing". What is it you are using the Zone to Zone visual logic for? I can see if it would be a quick add :)

**Comment by Necrym59** [comment]
Hi Zac
Just a standard Activate/Toggle options all thats needed
plenty of times zones can be used to activate other inactivated zones etc.

**Comment by Necrym59** [comment]
Hi Zac also while your at it the lua function to select a level to go to eg:
[@GoToLevelMode=1(1=Use Storyboard Logic,2=Go to Specific Level)]
wont select a level or work, i have attached two scripts and the logic code seems perfect to me can you see what it may be thats impeding the process??
Thanks 
[fadezone.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10221553/fadezone.zip)
[new_teleport.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10221554/new_teleport.zip)

**Comment by ZakJudges** [comment]
@Necrym59 Thanks for the files, I will look into JumpToLevelIfUsed() today. Would you also be able to send me your updated plrinzone script? Thanks :)

**Comment by Necrym59** [comment]
[plrinzone.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10227253/plrinzone.zip)
Attached for you sir! :)

**Comment by ZakJudges** [comment]
@Necrym59 I have added a fix for the GoToLevel dropdown - should be in the next experimental build :) I tested with the new_teleport and fadezone scripts. The teleport worked as expected, but the fadezone never seemed to hit this line:
![Screenshot 2022-12-14 104517](https://user-images.githubusercontent.com/32545391/207586221-32969d02-b545-4f32-bb22-4c627877d229.png)

**Comment by ZakJudges** [comment]
@Necrym59 Added Zone+Zone into PerformLogicConnections(). Was able to activate another inactive zone using the script you sent :)

These changes should be in the next experimental build. Hopefully that sorts all the issues listed, if not just let me know and I will take another look. Thanks :)

**Comment by Necrym59** [comment]
Hi Zac
ok the fade works perfectly then JumpToLevelIfUsed(e) perfectly ok now
BUT
is there a way to disable the built in fade to black when JumpToLevelIfUsed(e) or an option to turn it if
for example my fadezone can go to black or another image before JumpToLevelIfUsed(e) but then suddenly dissapears when max's fade out comes in before jumping to a level, can that Max fade out part be disabled or overridden either in script or an option?

**Comment by Necrym59** [comment]
Zone+Zone activation works perfectly too Zac
Awsome work, thanks.
