### ISSUE TITLE
Request/suggestion: Particle system

### ISSUE THREAD

**Issue by Emperor2000** [TheGameCreators/GameGuruRepo#396]
Personally this is high up on the list of items I'd like to see. It would be really cool if we had a fully functional (3d supporting) particle system. It would allow for tons of awesome stuff like falling leaves, proper fire, better explosions, etc.

**Comment by LeeBamberTGC** [comment]
In the latest Public Preview a new LUA command has been added which allows you to attach an emitter with a custom particle image animation to an entity. If this what you requested, or did you want it as a drag and drop feature?

**Comment by AmenMoses** [comment]
I will be adding a bunch more Lua commands soon but we will also require media to go with them, for example for falling leaves we would need some appropriate image files, similar for snow etc.

**Comment by Emperor2000** [comment]
I wasn't aware of that!! I'll be sure to check that out, i'm a massive coding noob though ^^

**Comment by Granada1** [comment]
Impressive vid mr Moses,👍

**Comment by AmenMoses** [comment]
I have pushed the updated global.lua with (hopefully understandable) details of how to use the particles system.

I think I will also need to do a tutorial on the forums to show various examples of use similar to my physics thread but for now I am always available to answer specific questions on the forums or via the discord channel.

**Comment by Emperor2000** [comment]
@AmenMoses Very nice video!

**Comment by LeeBamberTGC** [comment]
Okay, I have merged the code so expect it in the next Public Preview :)
