### ISSUE TITLE
GameGuru MAX - Bug - Cannot Hide HUD In-Game

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3960]
We used to be able to hide the HUD if we wanted/needed to with CTRL+H (if I remember correctly), but now we cannot hide the HUD. Currently, the only way to hide the HUD is to delete the HUD elements from the Storyboard.

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, thanks for reporting this issue. I have added a fix which should be in the next experimental build :)

**Comment by MonkeyFrogStudio** [comment]
Works! Thanks!
