### ISSUE TITLE
Screenshaking on respawn after electrocution.

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#3965]
Upon dying to the a trigger zone with the behavior set to Electrocute, and the damage set to 500, when the player respawns the camera will shake and twitch.  Here are the steps used to recreate it.

1: Create a level and add a trigger.
2: Set the Behavior to "Electrocute" and the damage to 500.
3: Play the level and run/walk into the trigger.

https://user-images.githubusercontent.com/114613272/207729300-5d5fa5e1-3112-49fb-b7b6-9b934ff21ba8.mp4

**Comment by Necrym59** [comment]
Doesnt it go back to a checkpoint?? otherwise your spawning in the zone all the time
i could set it to destroy the zone on death that would fix it

**Comment by Necrym59** [comment]
Fixed
[electrocute_v5.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10265884/electrocute_v5.zip)

**Comment by LeeBamberTGC** [comment]
Will be in next EXP build

**Comment by extremestrategy** [comment]
@LeeBamberTGC I tried it with today's EXP build and if anything it's actually worse.

**Comment by LeeBamberTGC** [comment]
The EXP build has V5, this one is V6:

[electrocute_v6.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10279535/electrocute_v6.zip)

**Comment by extremestrategy** [comment]
What do I do with it?

**Comment by LeeBamberTGC** [comment]
@extremestrategy You can put the new LUA file here: "YourDrive:\SteamLibrary\steamapps\common\GameGuru MAX\Files\scriptbank\markers\"

**Comment by extremestrategy** [comment]
I did that and I don't know if I made a mistake switching out the files, but now my character doesn't respawn.

https://user-images.githubusercontent.com/114613272/208971032-83399527-82cc-4dfb-951d-d131cd52df3d.mp4

**Comment by Necrym59** [comment]
Updated due to a double handling of health 
[electrocute_v7.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10282522/electrocute_v7.zip)
Should all work now with any luck

**Comment by extremestrategy** [comment]
It works now, thank you for your time fixing this.
