### ISSUE TITLE
GameGuru MAX - Bug - Latest Experimental Update Breaks Lightcontrol Behavior

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3969]
With the experimental update received just a bit ago, the Lightcontrol behavior stopped working (or stopped working correctly). I was using it with the Change Color feature to change a point light's color when a switch is thrown. It was working about an hour ago. Then I saved, shut down MAX, and when I restarted, there was an update. After that, Lightcontrol was no longer working.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio I added a debug line to see why the condition failed, and it is related to max light distance:

if g_Entity[e]['activated'] == 1 then
		lightNum = GetEntityLightNumber( e )		
		if current_level[e] < lightcontrol[e].max_light_distance then			
			SetLightRange(lightNum,current_level[e])
			if lightcontrol[e].light_object_no > 0 then SetEntityEmissiveStrength(lightcontrol[e].light_object_no,current_level[e]*5) end
			current_level[e] = current_level[e] + lightcontrol[e].speed
			if current_level[e] > (lightcontrol[e].max_light_distance-1) then
				current_level[e] = lightcontrol[e].max_light_distance
			end			
		end
		Prompt(current_level[e] .. " " .. lightcontrol[e].max_light_distance)
		if lightcontrol[e].mode == 4 and current_level[e] == lightcontrol[e].max_light_distance then
			SetLightRGB(lightNum,lightcontrol[e].light_r,lightcontrol[e].light_g,lightcontrol[e].light_b)			
		end
	else
		if lightcontrol[e].mode == 4 then
			SetLightRGB(lightNum,current_light_r,current_light_g,current_light_b)			
		end
	end

Can you add this PROMPT line and take a shot of what you see when the light is triggered, thanks!  Here is mine:

![image](https://user-images.githubusercontent.com/35840583/207890206-e349778d-10b3-45e8-9909-3fc0f42c2520.png)

Also, did you set range sensing to NO when triggering remotely:

![image](https://user-images.githubusercontent.com/35840583/207890455-58a2af0b-2925-4c05-ab6e-c6668f190104.png)

Also, sometimes with new scripts, if the parameters are swapped around or extended, you will need to click on the object and make sure the properties for that behavior are still correct as the level editor needs the latest params for the DLUA system.

**Comment by MonkeyFrogStudio** [comment]
Hi Lee,

Concerning the prompt line, not sure where to add that or what to do with it ... sorry ... artist here, not a programmer. ;)

And, yes, Range Sensing is set to No. 

Here are my settings:
![lightcontrol](https://user-images.githubusercontent.com/36735507/207891711-ceaf12ae-df66-4196-880c-f60e45b6b9a1.png)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Can you send me your level with the start marker where the light triggers, I can then reproduce :) Thanks!

**Comment by MonkeyFrogStudio** [comment]
It's the DLC demo level. I should be uploading it in about 30 minutes. :)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Perfik :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Just gave the projectbank and mapbank files to Dave.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio I have the level, where should I go from the start position and what should I look out for (i.e. look out for what is not happening) :) Thanks!

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC In the start position, there are two doors. One has a red light (locked) and one has a blue (it's behind you). Turn, go through that door and follow the corridor to the next door. Go through. In that room, there is a door to the right. Go through. That will get you into the small inner room (with the glass windows) and to your left is a switch on the wall. Hitting that switch opens the locked door. It also is supposed to change the red light to blue.

I hope that helps.

Of course, you can just look for the switch in the main room when you're in the editor (you should be able to see it through the glass) and see the logic connections once you've turned on Shooter.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Just got a new update. Did it contain the fix? If so, it's still not working on my end.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Not fixed in the latest experimental build. I even reverted the light back to a Constant light, saved, exited MAX, restarted MAX, and then reapplied the lightcontrol behavior (setting it back up, etc.) and the light stays red.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Seems it was a small issue with the script update. I have made a modification and it now works as before, plus allows the light to go back to red when the door is closed too :)  New EXP build available.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC That works! Thanks! :)
