### ISSUE TITLE
Yikes Latest EXP Build can Crash

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3970]
@LeeBamberTGC 

Just loaded up Max after the last update and getting this error on launch

EDIT ... Only in EXP .. Latest Steam update seems fine :)

I think i found it ... I go straight to the default map and use **File Load** for my maps
add the same map to the hub and its fine ?
Makes sense now it cannot find the Hud related .png using file load to load the map
To confirm the issue i did a vid. 
https://youtu.be/e8OjV-Uve8k

![E1](https://user-images.githubusercontent.com/35708217/207936948-0e04ce6d-2cc2-49b0-b8f6-30cd0b7b4acf.png)

**Comment by ZakJudges** [comment]
Hi @synchromesh62, thanks for reporting this issue. I have added a fix, but I am currently experiencing problems syncing files for Max, so I cannot create a new experimental build. To play it safe until a new build can go out, I have rolled the experimental build back to the public build. They should be the same, minus a fix for occasional missing HUDS, but given that fix has caused a crash, my feeling is that it is preferable to have a missing HUD than a crashing Max :)

**Comment by synchromesh62** [comment]
> Hi @synchromesh62, thanks for reporting this issue. I have added a fix, but I am currently experiencing problems syncing files for Max, so I cannot create a new experimental build. To play it safe until a new build can go out, I have rolled the experimental build back to the public build. They should be the same, minus a fix for occasional missing HUDS, but given that fix has caused a crash, my feeling is that it is preferable to have a missing HUD than a crashing Max :)

Thanks Zak 
yep confirmed the public build you rolled back to does not give the issue :)
Agreed its much better than getting the crash until the EXP is sorted.
