### ISSUE TITLE
GG Max - EXP Build - Standalone Test All Levels from storyboard crash

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3974]
Just tested my game from storyboard, Ticked the "Standalone Test All Levels" box.
Hit the "Normal Single Level" button.
Game loads up to the game menu.
Click START.
Crashed.
The game am trying only has one level, but it has 2 winzones that replay the level.

I tried a second game that actually has more levels, and it worked fine.

Then tried a third game, my horseshoe bend game, it also only has one level, but crashed when pressing START after having the Test All Levels ticked.

Seems to be a bug that crashes when you have that TEST ALL LEVELS box ticked, but the game only has one level.
Even though winzones in the level, replay the first level etc

**Comment by ZakJudges** [comment]
Hi @Tum1370, thank you for reporting this issue. I have added a fix that should be in the next experimental update :)

**Comment by synchromesh62** [comment]
Tried this last night and working for me.
There was a small update last night so i assume it contained the fix.

**Comment by Tum1370** [comment]
Just tried this bug again and can confirm it has now been fixed.
Ill close this one off now.
Thanks
