### ISSUE TITLE
cant quite figure out custom textures

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3975]
ive set a custom texture folder but ggmax is like nope, will only detect one of the textures in the folder:

![image](https://user-images.githubusercontent.com/68471279/208147924-71551e15-6b4f-415a-8ff2-38896d28024b.png)

NOT sure if this a bug or not but either way its not very clear how to use custom terrain textures. 

![image](https://user-images.githubusercontent.com/68471279/208148028-4299ee49-148c-4134-899f-3cf76450f69a.png)

**Comment by Nader-B10** [comment]
You have to divide the custom texture... so that each texture has a file and the files are numbered from (mat1), mat2, mat3,.  And so on

**Comment by casigus** [comment]
THAT doesn't work either.

**Comment by OldFlak** [comment]
MAX expects png and creates the dds it requires from them - but weird but tis the MAX way atm :)
So in you custom folder have the required mat folders each with the three texture files; Color, Normal and Surface (all png )
- mat1\Color.png, Normal.png, Surface.png
- mat2\Color.png, Normal.png, Surface.png
- mat3\Color.png, Normal.png, Surface.png
- mat4\. . . . .

Be aware MAX does not match tiles correctly in the editor atm - see #3979 for more info :)

hth...

**Comment by davetgc** [comment]
@casigus - Has this been answered for you?

**Comment by casigus** [comment]
thanks guys! yeah ive found a work around now! exported the defualt textures converteed them to pngs and manually edited them then imported them back in with their defualt names and just copied the dds's over the degfault textures. Needed a cobbled road texture! but it does feel abit likee chasing your own tail to get your custom textures working, might be someething to look at improving in the future for people who want custom textures.
