### ISSUE TITLE
MAX - EXP - Not Reading Editor Values Correctly

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3976]
So I have always thought that walking in MAX feels like the player has one lead foot holding him back
So I was messing with the player speed setting
- what I found is that all you have to do is change the value of 100 to 100 again (yes you read that right) and it is much better
- problem is you have to do that every time you open the map

Found the same with entities as well - for example sometimes you have to reselect the desired 'Static mode' even though the one you want is already selected
 
So seems MAX is still not reading values in the editor correctly.

**Comment by LeeBamberTGC** [comment]
@OldFlak I created a small level and timed how long it took to get to the building in the scene below, then edited the 100 to 100 and tried again and it was the same time to get there. We may have fixed this one, and it may also relate to another fix that caused the player speed to differ based on terrain slopes, time elapsed and FPS-indie code:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/7c1b6ac6-f871-476a-a418-7a0b9f93990d)
