### ISSUE TITLE
AI Set to Ally Does Not Work Correctly

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3977]
Video: https://youtu.be/NDQnLdk0r-s

Setting A.I to Ally does not work correctly. The Ally does nothing but follow the player. 
I expect them to open fire on enemies. 

Also you can see the Allies ran to me although they had no vision of me at the start of the video.

**Comment by Kitakazi** [comment]
Oh yea this is kinda big but you must select the box "Use default animations" under the Character Attack Behavior. This box is unchecked by default and if left unchecked will cause the AI's to not have any animations when test game starts.

**Comment by extremestrategy** [comment]
I have noticed this as well.

**Comment by Kitakazi** [comment]
the combat music is also bugged out in the video. it starts then stops randomly

**Comment by LeeBamberTGC** [comment]
@PalmTree11 Can you make a short video showing an empty level with one character to the point they draw and not shoot, that will give us a better idea what might be happening. Thanks!

**Comment by PalmTree11** [comment]
Opened up a new, empty level to record and the allies worked as they are supposed to. Tried multiple times with different characters just to make sure. When I open up a previous level that I have been working on for a few months, the issue occurs. Maybe something in the old level became corrupt?

**Comment by LeeBamberTGC** [comment]
@PalmTree11 During Early Access development, many things may become corrupt over the course of updating and changing file formats and structures. We try not to mess things up too often, but it is probably a safe thing to say it is probably not a good idea to start a major game before we get to V1 as technically we are still in EA development things can go bump in the night sometimes. A similar report was solved by the user removing the characters from their game, saving that, then restarting MAX and reloading the level, then adding characters a new, as that resets their behaviours and any settings that may have messed up.

**Comment by PalmTree11** [comment]
Thanks Lee. I'll give that a try.

**Comment by PalmTree11** [comment]
It worked!! Thanks Lee for your fast reply!
