### ISSUE TITLE
GGMAX - WEAPON BUG - The muzzle flash light from the patrol rifle lasts too long

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3981]
To test/confirm:
Make the map dark, add a wall (something for the light to bounce off of), then shoot the patrol rifle. It's muzzle flash light lasts for around a full second. Should be cut to about a third of that time, I would say. The other guns seem fine, by comparison.

(It also sounds like it plays it's dryfire sound on the last shot being fired, the other weapons don't appear to do this, either.)

**Comment by ZakJudges** [comment]
Hi @Kravenwolf, thank you for reporting this issue. I have added a fix which you should see in the next experimental build, later today :)
