### ISSUE TITLE
GGMAX - WEAPON BUG - Pushing and meleeing with any weapon leaves bullet holes

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3982]
See title.

**Comment by davetgc** [comment]
Hi,

Are you able to supply a video please?

**Comment by Kravenwolf** [comment]
@davetgc , don't have access to my main YT channel at the moment, but if you can load up an empty map when you get the chance, just add the sledgehammer, the patrol rifle and a grenade, and then grab a column from the aztec collection and give it a smack with each weapon (ALT key).

Rifle butting, striking a wall with a sledgehammer, and the player "pushing" with their hands (ALT with grenade and sledge equipped) leaves bullet holes in whatever stock (and custom) assets you selected.

**Comment by davetgc** [comment]
Ok, I'll take a look. 

FYI you can upload short videos directly to Github threads.

**Comment by Kravenwolf** [comment]
@davetgc, thanks. Here is a short, compressed video.

Seems to happen with any object that has a material type assigned to it. (The barrel and trash can don't appear to have materials assigned to them because striking/shooting them do not leave bullet holes).

Maybe the alt-fire options for weapons don't have a dedicated "select material" / "no material" option yet?


https://user-images.githubusercontent.com/103399301/212857947-ce0132f5-d5fe-4854-8232-f9576ff74254.mp4

**Comment by davetgc** [comment]
I feel this should actually be part of a larger update, one that adds additional, more realistic lookingcombat, rather than a quick fix.

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Seems the MAX engine was ignoring the NOSCORCH field from the GUNSPEC, sorted for the next EXP build.
