### ISSUE TITLE
GGMAX - WEAPON BUG - You can throw grenades through walls

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3983]
To test/confirm:
Add several hand grenades to your map and a few different stock walls and/or structures with walls. Walk up to these walls as close as you can get and throw a grenade. The grenade will be thrown through the wall, HOWEVER, the spoon that drops off of the grenade will not. 

You can also take a step or two back from the wall and then throw the grenade, and it will still go through the wall.

**Comment by LeeBamberTGC** [comment]
@Kravenwolf There was a small adjustment plus a natural position of the grenade that virtually could extend through the wall and thus the grenade started it's life there. Added code to test a direct ray from the player to that starting point, and if it is blocked, start the grenade at the player location. Not great for the player so best to run if you find yourself standing on a grenade now :)  Will be in the next EXP build.
