### ISSUE TITLE
GGMAX - BUG - CRASH! (RUN:7602) - Deleting a trig/sound zone, then selecting an entity, then restoring that zone causes multiple issues, including a crash

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3985]
To test/confirm: 
Add any stock entity, then a trigger zone or a sound zone (probably works on others, too). Now, delete that zone and then select your entity (you can move the entity around if you'd like, but it's not necessary). 

Then, undo the zone delete (Ctrl + Z), and the restored zone will be renamed to the entity's name and it's zone properties will all be removed.
		
**To replicate the CRASH:**
If you do the same test as above, only use a character as the entity you select before undoing your zone delete to restore it, MAX crashes with "Runtime Error: 7602 ()".

**Comment by plemsoft** [comment]
@Kravenwolf Thanks for reporting this issue, this has been fixed and will be in the next update :)
