### ISSUE TITLE
Levitating Trees when using Heightmap generated terrains

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3987]
We have had this before ant tis back again :)

![image](https://user-images.githubusercontent.com/12246318/208335408-6bc9fb14-b299-4697-a5d8-1b4ff3e21ade.png)

**Comment by OldFlak** [comment]
Tad better in current EXP, but still find a few of them

**Comment by OldFlak** [comment]
I don't use any stock FPMs :)
All my levels are heightmaps and all have floating trees - some of which you can stand under to look up the hollow trunk.

That said I would prefer you to leave it for now and sort projects :)

**Comment by OldFlak** [comment]
Hi Lee - I think what causes this is when the tree is next to a rise that the tree branches can touch - so it levitates a tad at runtime.
This tree for example will be in the air just a tad at run time
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/70eb985c-5da6-4690-bdb3-dd697baabd7f)

So this is really just a level design thing to take into consideration - sorry to for the time wasted looking at this issue

**Comment by LeeBamberTGC** [comment]
@OldFlak No worries, just 150 bugs to go and then we can talk about shiny new features and what you need for your project (apart from projects) :)

**Comment by OldFlak** [comment]
Just fyi - the latest build is showing the same issue again on very small inclines now - so tis not completely solved.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/4a9cccb7-2448-4dfc-a4d0-011d97b564d1)

Trees tend to be a huge fps drainer anyway so, probably best to worry about it later in the performance work :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Any chance you send me an FPM level with that slope and that one tree, and the camera positioned so when I run test hame I can see it float? That would ensure this one gets fixed very quickly :)
