### ISSUE TITLE
GG Max - EXP Build - AI instantly dies when it walks in to water.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3989]
As the title says, The AI, will instantly die if it enters any water.

**Comment by davetgc** [comment]
Hi,

Are you able to upload a video please?

**Comment by Tum1370** [comment]
Sorry am unable to upload videos, am not sure how you do that with youtube or whatever.
But it is pretty simple for you to put a small pond on a map, have the AI walk through the water.
The AI dies as soon as entering the water.

**Comment by Tum1370** [comment]
I will close this issue, After testing this, The AI can walk through water if its not to deep, It seems to die if the AI goes under water.
