### ISSUE TITLE
Missing files in standalone. - How to encrypt?

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#399]
It is necessary to copy and paste some files into the .exe after saving the standalone to solve some problems. For example some .fx and .dds files doesn't get copied over to the standalone in the saving process and it can be solved by simply copy-pasting the original files into the standalone but they won't be encrypted. How can I encrypt the files that I copy-pasted before publishing the game? For this would you recommend a third party program or something like a .bat file what is written for this problem? Is it related to the sdkencryptedappticket.dll in gameguru?

**Comment by tarkus1971** [comment]
Not 100% sure but I think if you manually copy files over, THEN make a new standalone afterwards GameGuru will encrypt the files already present. 

I haven't made a standalone for a long time so I am not sure.  Can't test at the moment, not at my gaming PC.

**Comment by Ratall** [comment]
Lee Just a thought would it be possible to add a file that you can place the names of your missing files so make standalone will pick them up? If the file name could be in some way associated with the say <levelname>.add in which you place the files you find missing so the get included and appropriately encrypted. Not an ideal solution but could stope some show stopping problems, Also there may be times when it is just not possible for the software to find everything.
just a thought

**Comment by LeeBamberTGC** [comment]
Ratal, that's a good idea, and would catch all those edge cases we could never anticipate 100% :)  I have switched this to an Enhancement so it can be considered as a feature to add to the build process. I will be revisiting this as part of a small overhaul of how standalone games are created so will fit nicely with that work (i.e. property dialog instead of a single message box).

**Comment by sfkylcnky** [comment]
Hi Lee,

Main problem about .dds files is that if the entity has more than 1 texture, the "textured" line in the entity's .fpe will be empty. Because of the fact that the textures are not defined in the .fpe, those .dds files will not be saved in standalone. Therefore entity does not appear in standalone game. Problem is solved when the mentioned .dds files are copied manually into the appropriate files. Is there a way to define more than 1 texture into a .fpe?

On the other hand in .fx files, when the code includes another .fx with the "#include" line the included .fx file will not be saved to standalone so that the entity that was using that .fx file will not work properly. effectbank\Galaxy Seed\siren_effects.fx can be given as example as it won't save effectbank\Galaxy Seed\constantbuffers.fx
effectbank\Galaxy Seed\settings.fx files to standalone in spite of the fact that it includes them. As mentioned   before at #368 it can be solved by copying the missing .fx files in to the appropriate directory after saving your standalone game but they won't be encrypted.

The missing files from the project that we are working on is attached. Before our official release we would like to get some help on this issue.

[list.txt](https://github.com/TheGameCreators/GameGuruRepo/files/2450512/list.txt)

Moreover, if you look closely to the list you will find it has Construction Site Pack and Antiques In The Attic Pack DLCs which both released at September 2018. We believe that if every sold item was placed on a blank map and tested properly by saving standalone, these kinds of errors can be prevented and you will be selling more flawless DLCs.

**Comment by Ratall** [comment]
Lee

Have you consider making the standalone creation process 2 staged.

1st  an unencrypted collection of assets that will run in the development system with out  reference the development content (essentially redirect the reference to the FILE directory structure to a structure containing only the files to be used in the standalone) 

Allowing the user to add any missing files to this semi standalone copy before encrypting the structure to produce the release standalone. 

Or put more simply provide a way delay the encryption till the standalone structure is tested and all missing media found and unneeded media removed (like the bits of the character creator media you didn't use. Last time I checked you get all the stuff even if you only create a couple of characters). It will also give the user a chance to tweak things with out effecting the source media/lua extra 

Anyway just another one of my strange ideas.

**Comment by LeeBamberTGC** [comment]
Given the chances of a long drawn out firefight catching every rogue scenario for missing standalone executable files, I have opted to code the above idea of a new file which can be used to specify 'extra' folders and files to include in the standalone files transfer prior to encryption, and the follow-up idea of specifying folders and files you want to remove before the standalone is created. This should allow game standalone to be prepared until we can catch all the rogue files that are not being detected for transfer (tricky sometimes as we expand new features which themselves references other files).  Expect this in the next public preview :)

**Comment by Granada1** [comment]
Great addition

**Comment by sfkylcnky** [comment]
Hey Lee, 

Is there any addition made to the 2018.11.26 update regarding this issue? If there is, I couldn't find where it is or how it is done. Just asking.

Kind regards, keep up the good work.
