### ISSUE TITLE
Collision shapes outside of object again

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#3990]
A few objects of recent are showing collision shapes outside the objects, This rock was supposed to have a convex hull but it protrudes out and away from the rock. This however has only happened after I used transform of the x and z scale slider.

![image](https://user-images.githubusercontent.com/95527550/208504098-3feb3192-8166-40b3-aae7-154fbb3a792d.png)

**Comment by ZakJudges** [comment]
Closing, as duplicate of #4141
