### ISSUE TITLE
GameGuru Classic Standalone Warning ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3996]
Getting this prompt when creating a Standalone in classic ( reported by Steam user )
Checked and confirmed but it does seem to encrypt it ?
**This standalone wll not have its assets encrypted - do not release???**

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Try the new BETA and PP builds, let me know if this resolves it. Jason also reported store download issues that this fix should also resolve.

**Comment by synchromesh62** [comment]
> @synchromesh62 Try the new BETA and PP builds, let me know if this resolves it. Jason also reported store download issues that this fix should also resolve.

Seems ok now regarding the Standalone prompt but have nothing to download to try the store at the moment.
But yes i can confirm the standalone prompt fixed :)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Jason confirmed the fix did not work, so dived deeper and found the cause. FIxed for the next BETA and PP builds :)
