### ISSUE TITLE
Game Guru Max - Mysterious light source bug

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#3999]
I ran into an issue today where I had a large bright light in my scene that I did not place (I never placed any that bright). I searched all over but could not find the source of the light. I mentioned it in discord and another user (Pek) explained that he had experienced this issue before and advised the following:

"To reproduce all you got to do is select a asset to spawn from the list while the thumbnails of the assets are still loading.
I think it has something to do with it loading some light source for the preview which bleeds into the actual scene
And since it's still loading it's confused." He further advised that restarting would fix the issue and it did.

**Comment by davetgc** [comment]
Hi, thanks for the report. Could you also please post a screenshot so we can see if what we see is what you're seeing?

Many thanks.

**Comment by ZakJudges** [comment]
Hi @Blood-Moon-Interactive, thank you for reporting this issue. I have added a fix which should be in the next experimental build, later today :)
