### ISSUE TITLE
Scene requires one light to be placed for shader to work

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#4]
May be obvious but it left me scratching my head at first

**Comment by plemsoft** [comment]
scratching ? what shader ? is this missing a pic ?

**Comment by plemsoft** [comment]
Please explain this bug Lee ?

**Comment by LeeBamberTGC** [comment]
Agreed, I cannot reproduce this bug (was reported by email) but without knowing the specifics of the shader and the scenario, unable to act. Closing this one.
