### ISSUE TITLE
GG Max - Exp Build - In Game Hud Editor

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4001]
Just been messing around with the In Game HUD Editor.
And found if i go in to one project and enter the In Game HUD Editor.
When i go back, and go to another project, and go in to the Game HUD Editor, everything is messed up on the 2nd project i go in.

A weird bug.

**Comment by davetgc** [comment]
If I've understood this, I'm not seeing it. Does anyone else have this issue?

**Comment by Tum1370** [comment]
@davetgc This is still bugged. Just tried it now.

**Comment by ZakJudges** [comment]
@Tum1370 Thank you for reporting this issue. I have added a fix which you should see in the next experimental build :)

**Comment by Tum1370** [comment]
@ZakJudges Thanks Zak for the fix, Just tested on Experimental build and working fine now. Going to close this issue.
