### ISSUE TITLE
Max ai problems

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#4002]
having problems with these, also have problems with the animation pack not working all the time.

I show the problems in the YouTube link.

I'm on the D drive.
![Screenshot (62)](https://user-images.githubusercontent.com/75592663/209161417-6f8290ea-d081-4178-9e18-aac95bd7aa39.png)

https://youtu.be/UwVwZ5XNFZQ

**Comment by davetgc** [comment]
Could you please upload your MAP file for this, I've run some tests and the AI is working.

**Comment by bluemeenie195** [comment]
GitHub says it won't support the FPM file type to upload

**Comment by DaveTGC2** [comment]
Can you add it as a zip file?

**Comment by bluemeenie195** [comment]
[fpm.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10307734/fpm.zip)
Thanks, The zip uploaded.
On my laptop Max works fine it's just my main computer that's having problems.

**Comment by DaveTGC2** [comment]
Thanks, that suggests the issue is local to you. Could you also please post your laptop specs.

**Comment by bluemeenie195** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/75592663/209661017-31f9cac4-5204-4a74-bdd4-112e9f3340fe.png)

**Comment by bluemeenie195** [comment]
If I put other ai scripts on the characters they seem to work it's just those three that give me problems

**Comment by bluemeenie195** [comment]
I figured out the problem.
Where do you put your custom scripts now so they don't get overwritten ?

**Comment by synchromesh62** [comment]
> I figured out the problem. Where do you put your custom scripts now so they don't get overwritten ?

Create a scriptbank folder in your GameGuruApps files folder and they will not get overwritten there.
Then backup your GameGuruApps folder every now and again so you always have a backup of all your Custom stuff.
i have a couple and on external drives also .. I dont trust Windows let alone anything else :)

**Comment by bluemeenie195** [comment]
Yep, that was the problem.
I did do that and for months since doing that, putting a scriptbank folder in the GameGuruApps files. The characters ai scripts would not work. They would just stand there, so for my computer anyway it was confusing Max for some reason.

Does the folder have to be named scriptbank ? I wonder if that was the reason

**Comment by synchromesh62** [comment]
> Yep, that was the problem. I did do that and for months since doing that, putting a scriptbank folder in the GameGuruApps files. The characters ai scripts would not work. They would just stand there, so for my computer anyway it was confusing Max for some reason.
> 
> Does the folder have to be named scriptbank ? I wonder if that was the reason

Most likely yes.
although i do have a lot of custom subfolders in my scriptbank which work just fine so your ok to do that.

**Comment by ZakJudges** [comment]
Hi @bluemeenie195, are you happy for this issue to be closed now? 
synchromesh62 is correct, all scripts, whether custom or not should be in the scriptbank folder.

**Comment by bluemeenie195** [comment]
Yes, thanks
