### ISSUE TITLE
New Health/Ammo Behaviour - Does not display Prompt Text - Updated scripts mess up levels with older versions

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4003]
As the title says, The new Health and Ammo Behaviour does not display the Prompt text when on AUTOMATIC pickup.

It does display it when on Manual Pick up !

So if you have the prompt to say "Health Collected" etc, when on Automatic pickup, you do not see that !

**Comment by Tam51** [comment]
I also noticed that you can't pick ammo up or grenades now in the exp build

**Comment by Tum1370** [comment]
> I also noticed that you can't pick ammo up or grenades now in the exp build when on automatic pickup

I guess that is on levels that you have already created.
You have to go over all the ammo and health pots that you have placed, and reselect the new behaviour (Even though it says its the correct behaviour)

**Comment by ShadowMasterOfGames** [comment]
Yup and it a pain trust me on that lol here is the link to Lee answer to my question about this issue 

https://github.com/TheGameCreators/GameGuruRepo/issues/3697#issuecomment-1361103246

**Comment by Necrym59** [comment]
Fixed to use the prompt text for either auto or manual pickup
[ammo_v3.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10302678/ammo_v3.zip)
[health_v3.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10302679/health_v3.zip)

**Comment by Tum1370** [comment]
@Necrym59 Thank you, Is it best for us to just to wait for these 2 scripts to update on Steam ?

**Comment by Necrym59** [comment]
https://github.com/Tum1370
You can use then now im sure Lee will update them anyway when he does an update

**Comment by davetgc** [comment]
@Necrym59 - Does Lee have these fixed scripts?

**Comment by Necrym59** [comment]
Yes he should have them i emailed them to him

**Comment by davetgc** [comment]
Thanks.

**Comment by Tam51** [comment]
Tried the new health script but for some reason I can't pickup or collect any health items now

**Comment by Necrym59** [comment]
Tam i dont know what the problem is exactly it works perfectly here under every test, can you be a bit more specific as to what is happening also just to be sure re apply the newer script to the object.

**Comment by Tam51** [comment]
I found the problem with levels you have created yourself. I had to change the behavior on all my health items to no behavior and then change to the new health behavior. Just changing the health behavior to the new one didn't work for me. A bit of a pain but I've sorted now

**Comment by Tum1370** [comment]
I will close this issue now, Just test on latest Experimental build and this is now fixed.
It would be nice if we had a option to set how many seconds the Prompt Text stays on screen for.
