### ISSUE TITLE
Off world Station DLC Bug

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4004]
Just had a report on Steam and can confirm i see the same thing
computers screens just show as white 

![offworld](https://user-images.githubusercontent.com/35708217/209310704-5b8c9b5a-b90a-4774-8b35-46f90696b908.png)

**Comment by GraPhiX-Guru** [comment]
I can confirm same issue
![cs](https://user-images.githubusercontent.com/35724756/209329025-7bd3a441-4511-4d6d-9292-2fedbee96f63.png)

**Comment by MonkeyFrogStudio** [comment]
This is not a bug. There's two computers sets. One set has screens attached already and they are blank glass with minor smudges on them. The second set has separate monitors to use specifically with the new Alt Texture. You need to select the monitor, make sure it's a physics object, and then add the Behavior, Change Texture:

![change1](https://user-images.githubusercontent.com/36735507/209340461-6e91bb2f-3915-4edd-9fdb-98bf0935c9ea.png)

At a minimum, you add ab Image1file, go down to to Tex Speed and set it to something other than 0 (the example I will show uses 10) and then set both the Tex Row Override and Tex Column Overrider. These last two need to match the number of rows and columns in your alt texture to produce the animation. In this case, it's set to 4 and 4.

https://user-images.githubusercontent.com/36735507/209341134-2767b8ea-72d1-4894-8d09-cbfac2fe0b7a.mp4

There should have been a few alt textures included. If not, let me know and I will provide them here.

**Comment by GraPhiX-Guru** [comment]
Yes its not a bug just a lack of understanding on how ALT textures work, with the correct settings all works fine
