### ISSUE TITLE
Entity in zone triggerzone always triggering even when the object isnt the triggerzone

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#4005]
https://drive.google.com/file/d/1tivqaVBxnebvbet6NT33S-iQ7Uc4NPDx/view?usp=share_link

**Comment by synchromesh62** [comment]
@RajMaha1 
Are you sure you have it setup correctly.
I want this door to open when the NPC enters the zone which seems to work ok.
https://youtu.be/DlzZhpsCa1w
your pic does not show the actual zone just the centre?

**Comment by davetgc** [comment]
Can anyone else shed any light on this one please. This seems to be working for me.

**Comment by synchromesh62** [comment]
> Can anyone else shed any light on this one please. This seems to be working for me.

Works for me still also. The video i posted above was created after the OP posted.
