### ISSUE TITLE
Colliding With a Character Pushes the Player Back

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4007]
If the player walks into a character they are jarringly pushed back. 
It is very annoying especially if trying to move past a character or if you accidently strafe into one. 

Could we have an option to disable this? Maybe keep the current "pushback collision" as 21 and a new collisionmode for character collision that doesn't push the player back but just stops them.

**Comment by Teabone3** [comment]
Which character specifically?

"fatness" is an FPE command that adds invisible collisions to a character entity and you can increase or decrease its size with that command.

**Comment by Kitakazi** [comment]
Ha well that definitely fixes most issues I was having with the characters collision capsules. Had no idea that was a command. Thanks!
