### ISSUE TITLE
GGC: Outdoor Structure Issues with AI

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4012]
It appears are a couple of outdoor structures that may not have their FPE setup correctly to support AI

Specifically the two tents held up by poles. 
Not the tarp tent. 

https://www.youtube.com/watch?v=S28QZFdOi_s

**Comment by Teabone3** [comment]
Ironically the model called "Entrance" in Mega Pack 02, is un-enterable.

These assets all require their FPE to be updated. Is there a way I can send these fixes as a pull request, if i go through them all?

**Comment by LeeBamberTGC** [comment]
@Teabone3 I have created a new folder in the Classic Repo you can use to drop the latest fixes for any FPEs into:

https://github.com/TheGameCreators/GameGuruRepo/tree/master/GameGuru%20Core/GameGuru/Entity%20FPE%20Fixes/entitybank

Ensure you reproduce the folder structure exactly from ENTITYBANK onwards, that way the FPE always goes in the correct place when updating the Steam version. This works in a similar way as the current "Shaders and Scripts" folder (notice how the folder structure is preserved).

**Comment by LeeBamberTGC** [comment]
@Teabone3 Thanks for placing them in the correct folder hierarchy, makes our lives SO much easier, and thanks again for contributing to Classic :)

**Comment by LeeBamberTGC** [comment]
@Teabone3 Changes now live on BETA and PP, thanks again!
