### ISSUE TITLE
GG Classic latest build animation doesn't work.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#4017]
Switched back to September build and all working again.

Simply trying out the Cine|Guru actors example (CG_Bob_and_Jane.fpm) will show the problem but I came across it trying to assist one of the community with their custom AI script, basically the Lua commands to  control animation just don't work in the December build!

**Comment by cybernescence** [comment]
PR to fix: https://github.com/TheGameCreators/GameGuruRepo/pull/4013

**Comment by LeeBamberTGC** [comment]
@AmenMoses  Possible fix in NEXT BETA build, please confirm here, thanks!

**Comment by AmenMoses** [comment]
Well it works again, walking a little faster than they used though.

**Comment by LeeBamberTGC** [comment]
@AmenMoses let's see if we get a new issue to slow them down again :)
