### ISSUE TITLE
terrain after build is broken

### ISSUE THREAD

**Issue by Ghalbeyou** [TheGameCreators/GameGuruRepo#4018]
terrain after build is broken, when i add house to terrain, terranin gets flat, but after build, its not flat!!!!

**Comment by davetgc** [comment]
Is this for GameGuru MAX or GameGuru Classic.

Can you please post some more information, how is it not flat?

**Comment by Ghalbeyou** [comment]
max. when you place house, it flats the terrain, but after exporting the game, the flat area will remove

**Comment by davetgc** [comment]
Sorry for the late replay, so this is related to Standalone?

**Comment by Ghalbeyou** [comment]
yes

**Comment by davetgc** [comment]
Thanks and are you using the latest experimental build or the Steam build?

**Comment by Ghalbeyou** [comment]
steam build

**Comment by davetgc** [comment]
Could you please try the experimental build, to see if this fixes your problem. 

You can find details of how to access that build here:

https://github.com/TheGameCreators/GameGuruRepo/discussions/3916

**Comment by Ghalbeyou** [comment]
No its still there

**Comment by davetgc** [comment]
Okay, could you please post 2 screenshots, one showing the result before export and one after. Also, could you indicate which models you're using.

Thanks.

**Comment by ZakJudges** [comment]
Hi @Ghalbeyou, I could not reproduce this. After placing a building down and saving as standalone, the terrain is still flat when I play the standalone.

**Comment by Ghalbeyou** [comment]
hello, its fixed. thanks 👍
