### ISSUE TITLE
GGC: Fantasy Characters Are Broken (when lightray is enabled)

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4021]
The fantasy characters in GGC are not working correctly. Some move, some dont. They don't seem to attack or animate either. This includes the ally knight.

**Comment by Teabone3** [comment]
Okay issue identified. Its related to the lightrays. Everything works if lightrays are set to 0.

I believe this pull request should fix it #4013

**Comment by davetgc** [comment]
They do seem related.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Possible fix in NEXT BETA build, please confirm here, thanks!
