### ISSUE TITLE
Move Doc360 User Guide to PDF and Link to MAX Help Menu

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#4022]
Zak, I have forwarded you the latest user manual files as a zip. Create a PDF from the pages, then add to the MAX build and replace the URL link in the HELP with the local PDF file so user manual can be accessed again.

**Comment by ZakJudges** [comment]
@LeeBamberTGC I have uploaded a new EXP build, which replaces all links to the online user guide, with the local PDF guide
