### ISSUE TITLE
"Message" Behavior Issue - Attn: Necrym59 and smallg

### ISSUE THREAD

**Issue by jasailor** [TheGameCreators/GameGuruRepo#4023]
Interesting problem!  I set up a trigger zone and set the behavior to Message and when the player enters the zone it doesn’t trigger.   I fiddled with a copy of the script and got it to work by commenting  out  in the main function  >local im = g_message[e]<.   I also had to change the If statement comparison from ‘activated’ to  ‘plrinzone’.   By doing that I got it to display the default message lines  Unfortunately , when I changed message lines on behavior screen it does not change the  messages in game play even though the changes are retained on behavior screen.   

It behaves as though the messages are hard coded someplace between the behavior screen and the scripting.

**Comment by Necrym59** [comment]
Attach the behavior to a rock or barrel, adjust the message settings to suit
put a trigger zone down and logic link it to the rock or barrel with the behavior
It works fine I cant see any problem - just dont attach it directly to a trigger zone

**Comment by synchromesh62** [comment]
Yep working fine here 
https://youtu.be/w31lwAwhgac

**Comment by jasailor** [comment]
Thanks Necrym59!   Your incidental comment about attachment was tremendously significant.   I was indeed attaching it to the trigger.   I spent a lot of time trying to get to work properly.  I wish there was published documentation that explains the nuances of the environment instead of us using trial and error.   Regards,JASailorOn Jan 4, 2023, at 9:45 PM, Necrym59 ***@***.***> wrote:﻿
Attach the behavior to a rock or barrel, adjust the message settings to suit
put a trigger zone down and logic link it to the rock or barrel with the behavior
It works fine I cant see any problem - just dont attach it directly to a trigger zone

**Comment by davetgc** [comment]
Hi, is this considered answered?

**Comment by jasailor** [comment]
To answer your question Dave,  the issue can be closed with a caveat:  please first address these couple of things: 

          1. Add to the "MAX  User Guide" a section on "logic links", providing information on their general use and how to best use them in MAX.  
          2. Also add a  section on the use of "Behaviors".   This is such a powerful concept it needs to be explained along with the nuances how to use each of them.   For example:  needing to add the behavior to an uninvolved asset and  connecting them with a "logic link" to a trigger to avoid issues.       
          3. Update the "Lua GameGure LUA Scripting Summary and Guide" to include the new components of a CCMAX LUA script structure and those statements not in a function at all.  For example:   
          
-- DESCRIPTION: Re-triggerable zone to trigger an event. 
-- DESCRIPTION: [ZONEHEIGHT=100] controls how far above the zone the player can be before the zone is not triggered.
-- DESCRIPTION: Set for [@MULTI_TRIGGER=2(1=Yes, 2=No)]
-- DESCRIPTION: Set [DELAY=0(0,100)] in seconds to delay triggered event.
-- DESCRIPTION: [SpawnAtStart!=1] if unchecked use a switch or other trigger to spawn this zone
-- DESCRIPTION: <Sound0> when entering zone

g_plrinzone = {}
local zoneheight	= {}

It's generally clear how and when the _init and _main functions execute , but what about those things before the _ Init function such as: the use of the "-- DESCRIPTION:" special type of comment and its features to obtain input into behavior scripts.  These hybrid comments are a tremendous capability that needs to be explained.   

Since the product is moving forward so well and has a tremendous potential for making a big impact in the game engine market, I think it would be beneficial to recognize a major part of the your target market (newbies), who will be exposed to GGMAX and expect to see more comprehensive information on its features.  I fear that they will not have the patience or time to go through the now over a hundred videos or posts to catch highlights about these great features, then get discouraged with the lack of details and ultimately not return to the product later.     

The existing "MAX User Guide" was a great start and covers early basic information, unfortunately, a new user may assume it's functionally complete and miss the many great things added since March.   If nothing else, perhaps you folks could add to the document titles for the new functionality with a comment "to be added later" so customers can see the functionality and expect to see the details later.   I've been in IT leadership for a long time and know that a short term investment in documentation has large long term benefits.  It  establishes a product feature baseline reference, reducing wasting technical resource time on addressing non-issues while it informs existing and potential customers  about the product's evolving capabilities increasing their enthusiasm and engagement.  A win-win!

**Comment by jasailor** [comment]
Please close the issue....
