### ISSUE TITLE
GGMAX - AI BUG Shooting through terrain

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#4029]
AI shoots through the terrain.
https://youtu.be/6jEg2VG7sjk

**Comment by Tum1370** [comment]
I reported this problem in July last year.
Still awaiting a fix trhough.

https://github.com/TheGameCreators/GameGuruRepo/issues/3419

**Comment by davetgc** [comment]
Closing as it's a duplicate, but I've updated the previous report.
