### ISSUE TITLE
Ladder Behavior is Bugged

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4030]
Climing all the way to the top of a ladder will launch the player forward by a huge amount. 

Climbing up a ladder and pressing Jump will launch the player in a random direction.

https://youtu.be/pC8lCnb4ltM

**Comment by Necrym59** [comment]
Hi Kitakazi
Can you try this one and let me know if its ok ,it now has an adjustable exit force setting
[ladder_v24.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10367720/ladder_v24.zip)

**Comment by davetgc** [comment]
@Kitakazi - Can you please let us know if this helps?

**Comment by Kitakazi** [comment]
@Necrym59 @davetgc 
Yup that fixed it. Thanks.
