### ISSUE TITLE
GGC - Issue - Character Creator Heads Disappear (in-editor)

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4032]
On occasions, character's created through the Character Creator in GGC will lose their heads in editor.

![cc_Head_gone](https://user-images.githubusercontent.com/35990109/211190230-ec8b5706-a6c1-4363-a069-17cc192844cb.JPG)

Workaround: Test map and encounter the character in-game so its visible, then exit back to editor.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Is it still happening in the March update, and if so, can you send an FPM and your custom CC character files and a step by step to reproduce the missing head in the level editor.

**Comment by LeeBamberTGC** [comment]
Plenty of heads in the September 2023 BETA to be uploaded soon:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2ca319c2-c6df-4c20-84ff-0002ed4c5fbf)
