### ISSUE TITLE
GGC - Issue - Character Creator UI Disappears

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4033]
If you use the character creator a couple times, the CC UI will eventually disappear the next time you open it.

![character_creator_no_ui](https://user-images.githubusercontent.com/35990109/211190346-7ecae9eb-c7b3-4e72-b14b-017e231e857f.JPG)

Workaround: Click the empty area to the top right within the CC window, it should exit back to editor. Then save and then relaunch GGC. You have to do this so that you dont lose any changes to your map, prior to opening the CC.

**Comment by LeeBamberTGC** [comment]
@Teabone3 How many times do I need to do this with the March update to see this issue?

**Comment by LeeBamberTGC** [comment]
@Teabone3 Cannot reproduce this one in the September 2023 BETA build, launched CC ten times, all good:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b0121acf-334b-4e82-98c4-61434e384368)
