### ISSUE TITLE
GGC - Issue - Character Creator Head and Body Alignment

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4036]
The character creator's head moves off the body when using various built in poses from the CC.

![cc_head_Came_off](https://user-images.githubusercontent.com/35990109/211191150-3188a335-c2ab-48e9-b025-18a4b635556b.JPG)

I'm assuming this is because the character's shoulders tilt downward in that biped ad the head remains up. Is this why the soldiers had masks over their chins? :)

**Comment by LeeBamberTGC** [comment]
@Teabone3 Alas, this was one of the limitations of the method used in Classic for the old Character Creator. When we developed MAX, we came up with a new system so this did not happen (using a single mesh to better move the verts about with the bones). The only way to resolve this is to replace it entirely, so marking as a feature request if we ever return to improving this aspect of Classic.

**Comment by Teabone3** [comment]
Totally understandable. Closing issue report.
