### ISSUE TITLE
GGC - Issue - FireWeapon(e) - Enemies Never Reload

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4037]
The GGC AI doesn't ever reload. This seems to be an issue related to FireWeapon(e)

See issue in video below:
https://www.youtube.com/watch?v=uYbnD5YINZ4

Now, I was able to produce a workaround by adding additional Lua to the AI that allows them to respect their clip maximum and reload when that is reached; based on what weapon they are using. This isn't ideal however, as it adds more to the AI rather than optimizes and addresses the actual issue.

There is a section in the AI to handle Reloading, but it doesn't get used properly on its own.

Here is a video of my workaround. The purple text displays what is left in the gun before starting reloading process. This is technically how the AI should be working.

(I've intentionally set him to use a slower rate of fire, just so that i can view the ammo clip usage easier)

https://www.youtube.com/watch?v=eYQtiQ1ypS4

**Comment by Teabone3** [comment]
This issue posted on Steam is semi-related

https://steamcommunity.com/app/266310/discussions/0/6202034451753833467/

**Comment by Teabone3** [comment]
Just wanted to add, that this doesn't seem to be an issue with gunspec and only with the FireWeapon(e) command
Since the enemies not reloading are using guns that have the following setting disabled:

npcignorereload		= 0

**Comment by LeeBamberTGC** [comment]
@Teabone3 Fixed in NEXT BETA build :)  Nice find.
