### ISSUE TITLE
GGC - Issue - Character Creator - Melee Weapon Ammo

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4038]
If you create a character in the CC and give it a melee weapon, for example any of the Fantasy Swords and kill the character. He will drop the weapon on the ground that you can collect.  However if you happen to already be carrying the same weapon, a text prompt will appear saying you "collected ammo".

The cause of this issue is all the fantasy melee weapons appear to have a "1" in their "quantity" property. I believe this should be either 0 or -1.

**Comment by Teabone3** [comment]
Also noticed that the character has "Take Weapon's Ammo" set to 0, which doesn't appear to be working here.
working. That property description says: "Represents how much ammo can be found with the dead character".

**Comment by Teabone3** [comment]
I checked to see what happens when you set Quantity to zero in the melee weapon's FPE file. However the prompt of Collected Ammo still appears if you collect the weapon you are already wielding. Its likely its making this prompt but not actually increasing the "ammo" as the character property settings have Can Take Ammo as 0 and the quantity of ammo the weapon carriers in FPE is 0.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Changed to "Collected enemy weapon" when the weapon collected has RELOADQTY of zero (for melee weapons) in NEXT BETA build.
