### ISSUE TITLE
GGC - Issue - AddPlayerHealth(e) Exceed and Ignores Limit

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4039]
Health item pick ups that use AddPlayerHealth(e) exceed the maximum player health. There are workarounds that can be done in Lua to take the health amount and add but not exceed maximum (g_gameloop_StartHealth).

I fixed the Healing Zones years ago and glad to see that made it into the a final build, though those do not use the AddHealth(e) function that Collectable health pick ups do.

Here is the c++ Code for AddPlayerHealth(e):

`void entity_lua_addplayerhealth ( void )
{
	//  collect health
	t.tqty=t.entityelement[t.e].eleprof.quantity;
	t.player[t.plrid].health=t.player[t.plrid].health+t.tqty;
return;`

What is needed is a check to see if health is equal to or greater than 'g_gameloop_StartHealth' then if not, attempt to increase health by "t.tqty which is "Quantity" in the FPE files, which for some reason is no longer visible in the GGC Editor anymore when clicking on health items. After that process, check to set the health to the maximum health if exceeding. 

Or do a different process to begin with a formula like: 
**25 + (100 -  50)** 
for example which is:
 **t.qty + (g_gameloop_StartHealth - t.player[t.plrid].health**
 or basically
 **Quantity + (Maximum Health - Current Health).**

Health Picks Up should only be used for replenishing the health of the player. We've seen many users bring up this issue over the years. For a Health Boost, this should be a newly created entity that specifically boosts the health beyond its max. If we are to create this item, we will have to ensure not to add any process to health items that attempt corrections of any overage of health but instead use the above formula so that it doesn't take a boost down if one is applied.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Fixed for NEXT BETA build.
