### ISSUE TITLE
Max Repository - Lib Version Issue

### ISSUE THREAD

**Issue by cybernescence** [TheGameCreators/GameGuruRepo#4044]
Hi Lee,

almost managing to compile Max, but the supplied lib files are proving a linking problem - or I'm compiling Max with the wrong version/toolset?

Error	C1047	The object or library file 'D:\DEV\GAMEGURUMAXREPO\GameGuru Core\SDK\OGG\lib64\ogg_static.lib' was created by a different version of the compiler than other objects like '..\Guru-WickedMAX\x64\Release\WickedEngine_Windows.lib'; rebuild all objects and libraries with the same compiler

I don't think the source files are included for ogg_static?

I'm compiling with Visual Studio 2022 (v143) with Windows SDK of 10.0.22000.0

Cheers

**Comment by plemsoft** [comment]
@cybernescence Download all the libs from here: https://github.com/TheGameCreators/GameGuruMAX/releases/tag/VS2022

Worked for me :)

**Comment by cybernescence** [comment]
@plemsoft 

Those are the libs I'm trying to use and getting compile version conflicts :)

So I must have a different VS2022 config than the one needed.

I'll just leave it as I'm not going to uninstall and reinstall VS2022 to try and work with Max (TBH I don't know what else I would do differently anyway to try and get it to work - as on latest version of VS22, toolsets and Win10). I'd prefer to be able to compile everything necessary via VS to prevent these issues.

Cheers.

**Comment by plemsoft** [comment]
@cybernescence I have the same setup, just tried again with the latest changes and it still worked here ? Strange did you "overwrite" when you copied the libs ? @LeeBamberTGC Perhaps you could add "C:\DEV\Compile OGG VORBIS 2022\" and the other in a download link if anyone would like to compile the libs themselves ?

**Comment by LeeBamberTGC** [comment]
@cybernescence Could you zip up your "GameGuru Core\SDK\OGG\lib64" folder and your "GameGuru Core\Guru-WickedMAX\x64\Release" folder, and confirm you are compiling the WICKEDREPO with ReleaseForGG and MAX configured to build as "Release". thanks!  I can then check for you.

**Comment by cybernescence** [comment]
Started again from scratch and now it builds :). I think what I may have done as I was getting link errors for MFC was to rebuild WickedEngine_Windows.lib from the VS sln after the VS update for MFC - this has overwritten the same lib I copied from the zip. So I'd fixed one issue and then caused another.

All good now, thanks for the tips to get it working.

Cheers.
