### ISSUE TITLE
GGC- Issue - When Picking Up Weapon You Already Have

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4045]
If you attempt to pick up a weapon that you are already wielding or have in your inventory, a prompt will appear saying:
Prompt("Press E to pick up the " .. weapon_name[e] .. " or T to replace" )

Both options makes the weapon disappear, T however will make you put away your weapon and then bring it back out.

Attempting a fix for this by using GetWeaponID (weapon_name[e]) doesn't work because, for example the Skelly Sword's entity name is "Skelly Sword" and not "skellysword" which would return the weapon Id if written out that way and compare it with if you are wielding it already -- then prevent pick up.

I think this might work (using weaponsname as an example):

weaponsname = weaponsname:gsub("%s+", "")
weaponsname = string.gsub(weaponsname, "%s+", "")
weaponsname = string.lower(weaponsname)

This will remove the spaces in the name and then lowercase it. Then GetWeaponID will work. This though assumes all weapons are named similar to their file path name and entity name.

There is probably an easier way to do this that I can't think of off the top of my mind, but if not, several conditions would need to be added to test is lowercase connects or remove spaces. Because some weapons do have spaces in their file path names and some do have upper and lower case.

**Comment by LeeBamberTGC** [comment]
@Teabone3 There was another command called GetEntityWeaponID that cut to the chase to get the actual weapon index :)  Modified the weapon.lua script so that collecting repeated guns and melee weapons is handled correctly in NEXT BETA build.
