### ISSUE TITLE
Storyboard to HUD editor bug

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#4047]
When attempting to access the HUD the place where I would select it is in the splash screen tab and not editable accept for adding an image.
![image](https://user-images.githubusercontent.com/114613272/211230972-397635d4-5ab2-48f4-9035-adcd312866b9.png)

**Comment by davetgc** [comment]
Duplicate, Thanks for the report, but I'll close this for now as the team are aware of this issue.
