### ISSUE TITLE
An option for non story levels

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#4048]
Currently in the story board editor the only way to access a map is to start a new game, load a game, or beat a level, would it be possible to add an option for there to be maps that could be accessed straight from another screen that are not apart of the actual game story, allowing for us to have quick battles, training's etc.

**Comment by MonkeyFrogStudio** [comment]
I am not sure I am following you. So, sorry if I am not completely understanding. But I think you can already do what you want in MAX. You can create a new level and it doesn't have to be connected to any level at all. If it is visually linked, you can disconnect that link if you like. Then, in the level you want, you can create a Win Zone and use that to take the player to a specified level of your choice. You just need to tell the Win Zone to either use the Storyboard or to go to a specific level. You don't have to use a Win Zone only for beating a level (i.e. winning a game), but can use it to trigger a transfer to any level you like. Then, in the other level, you can use the same logic to get back to the old level. 

You could, for example, create a selection for a player that offers them a tutorial level or a battle level. They click the switch or walk through the particular door, or make the selection, etc., and it would trigger the appropriate Win Zone, sending the player to that level to run the tutorial or have a quick battle, etc. Once that part is completed, another Win Zone in that level could be used to send them right back to the previous level.

**Comment by extremestrategy** [comment]
@MonkeyFrogStudio  Think Star Wars Battlefront, how they have the campaign and then the "Instant Action" I'm looking for an option to have the Main Menu screen have an option to go to a level outside of the campaign.

**Comment by MonkeyFrogStudio** [comment]
@extremestrategy That makes sense! Thanks for the explanation. And, yes, that would be a great addition.

In the interim, this could currently be handled like they used to do in some older games. You create an initial level that sort of serves as sort of Main Menu. From there, the player can select a place to go (maybe via a series of doors - one for Main Game, one for Tutorial, etc.). When the ones that are not the main game are completed, the player is returned to this Main Menu level so they can move on to the main game, etc.

**Comment by extremestrategy** [comment]
Your welcome, glad you like it.

**Comment by extremestrategy** [comment]
This has actually been fixed for main menu screens.
