### ISSUE TITLE
GameGuru MAX - Bug? - Switch Can't Activate Audio Zone

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4052]
Apparently if you want to trigger an audio zone via a switch, you can't.

Steps to test:

- Drag in an Audio Zone and set the sound you want to play
- Drag in a switch with the switch behavior (or attach a switch behavior if your switch doesn't have one)
- Using visual logic, attach the switch to the audio zone
- Run a test game

In test game, when you click the switch, only the switch button sounds play, but the audio zone is not triggered by the switch (or at least no sound plays).

**Comment by synchromesh62** [comment]
Doesnt the audio zone only detect the player walking into it ?
not sure a switch is even supposed to do that

**Comment by Necrym59** [comment]
Audio zone is stock and hasnt been changed to allow for switches only for player detection.
Synchros solution works fine, if you wish another sound when hitting a switch as well
or if requested i could update the sound zone for switch triggering as well although i dont see the need.

**Comment by MonkeyFrogStudio** [comment]
Thanks for the solutions. I appreciate it. :)

 _i dont see the need._

If there is another way (which Synchromesh showed there is), there isn't a "need". However, think of it from the typical end-users' way of thinking. If someone wants to play an audio file via a switch, what would they use? The average person, possibly new to MAX, looking through the items available, might think that Audio Zone was the most logical. Now, as Synchro pointed out, you can just use a standard Trigger Zone. Great. But they are ALL zones, right? So, if someone wanted to play an audio, their mind would naturally go to Audio Zone and not Trigger Zone (or any of the other zones).

While there is no need since there is a way to do it, personally I think that all the zones should work in a similar way (where it makes sense for them to). Therefore, if one zone (i.e. the trigger zone) can be ticked to not show on startup, then why not the audio zone as well? Or if the standard Trigger Zone can also play sounds, why bother with having an Audio Zone if a standard Trigger Zone can do the trick just as well?

**Comment by synchromesh62** [comment]
> Thanks for the solutions. I appreciate it. :)
> 
> _i dont see the need._
> 
> If there is another way (which Synchromesh showed there is), there isn't a "need". However, think of it from the typical end-users' way of thinking. If someone wants to play an audio file via a switch, what would they use? The average person, possibly new to MAX, looking through the items available, might think that Audio Zone was the most logical. Now, as Synchro pointed out, you can just use a standard Trigger Zone. Great. But they are ALL zones, right? So, if someone wanted to play an audio, their mind would naturally go to Audio Zone and not Trigger Zone (or any of the other zones).
> 
> While there is no need since there is a way to do it, personally I think that all the zones should work in a similar way (where it makes sense for them to). Therefore, if one zone (i.e. the trigger zone) can be ticked to not show on startup, then why not the audio zone as well? Or if the standard Trigger Zone can also play sounds, why bother with having an Audio Zone if a standard Trigger Zone can do the trick just as well?

Necrym59 created the new triggerable trigger zones by popular request but the need of an audio version was never mentioned or requested but initially i was thinking the same myself really about the one zone does all but that is not the case .. 
Both Audio Zone and Music Zone have their own features like Play once for audio or Play only in zone only for Music etc.
Putting all this in one zone could get messy, confusing  and really not required if they are there already.

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 I was not suggesting that one zone do it all. I was suggesting that if a few zones have the tick box for Show On Start, then they all should have them. If one trigger zone can be activated by a switch, then others should, too (where it makes sense). 

Like you, I also find solutions, sometimes in strange ways. :) I found one for this one, too (on my own), even though I had opened this post. I didn't open it  I needed this feature, but because someone else was trying to figure it out. And, from a logic standpoint, it makes sense that if you want to trigger audio, you use an Audio Trigger. And if you want to trigger it via a Switch, you should be able to via a switch. 

Workarounds are great. I use them all the time in a variety of places (MAX and elsewhere). But just because we can use a workaround to accomplish something does not mean we shouldn't suggest a better way to do something. ;)

**Comment by synchromesh62** [comment]
**I was not suggesting that one zone do it all. **
I misread this then.
**Or if the standard Trigger Zone can also play sounds, why bother with having an Audio Zone if a standard Trigger Zone can do the trick just as well?**

As i mentioned Neccrym59 took it upon himself to create the triggerable Trigger zone by a lot of requests but no one mentioned the others but then the problem is a switch will only spawn the audio zone if that was implemented which you still have to walk into to hear the sound and this can already be done with the trigger zone. The feature is already there 
Personally i do not see using the logic as work arounds. That is what it is for so you can manipulate them in different ways to get the results you want.
Anyway its not really my call i just tried to help with a solution.

Best person to request it from is @Necrym59 If anyone would be implementing this feature its most likely him.

**Comment by davetgc** [comment]
I think these things should be consistent.  I'll add this as a feature request.

**Comment by synchromesh62** [comment]
Good News Necrym has created one that triggers 
Tested today and it works great ..

**Comment by Necrym59** [comment]
Updated the core soundinzone behavior
include the requested 'SpawnAtStart' capability so its inline with other zones 
[soundinzone_v2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10396622/soundinzone_v2.zip)
Sent to lee for checking and inclusion
