### ISSUE TITLE
Default terrain tree system doesn't cast shadows.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#4054]
I did realize that the default tree system doesn't cast shadows in dark environments using lights while the added tree props does cast shadow. Here is the photo of the example. 
![image](https://user-images.githubusercontent.com/81198887/211454550-d4990060-e83b-43df-a8ac-72326e427c8a.jpeg)

**Comment by davetgc** [comment]
This seems to be working for me, can anyone else confirm please? Maybe I'm not going dark enough.

**Comment by Hamada880** [comment]
> This seems to be working for me, can anyone else confirm please? Maybe I'm not going dark enough.

I'm not using any sky dome btw and just getting the ambient light to black . What settings you are using?
