### ISSUE TITLE
Bug discovered, two spot light influence one another.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#4055]
I discovered this bug when I added two spot light in same area the new spot light influence the older one when rotation is selected and redirected.

**Comment by MonkeyFrogStudio** [comment]
Just to support this post, here's showing it in action:

https://user-images.githubusercontent.com/36735507/211467426-af3e1277-74b3-4508-a8dc-2aa93d229243.mp4

**Comment by ZakJudges** [comment]
Hi all, thanks for reporting this issue and for the video. I have added a fix that should be in the next experimental build :)

**Comment by ZakJudges** [comment]
Closing this issue as it is likely fixed. If the problem persists, feel free to reopen
