### ISSUE TITLE
GGC Issue - Soundset Issues with CC Generated Characters

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4057]
All characters made in the Character Creator are by default using the female soundset. Even when you select the male custom face icon character.

Could this have anything to do with it?
![female_cc](https://user-images.githubusercontent.com/35990109/211685855-83cc094e-a810-40c0-8cff-4ff1c801f271.JPG)

**Comment by Teabone3** [comment]
A quick fix would be to allow for "male" to be the default if the character creator is not using the female head. Which if you do use the female head it seems in the code below it would select soundset = female.

https://github.com/TheGameCreators/GameGuruRepo/blob/master/GameGuru%20Core/GameGuru/Source/M-CharacterKit.cpp

**Comment by cybernescence** [comment]
Fastest way to fix this is to add soundset = male into the Uber Soldier.fpe

The character creator uses the Uber Soldier.fpe as a template and as a default should be male. A female head will then override so that soundset = female. It was maybe taken out at some point to stop the default sounds? Not sure. 

If want to change the code to make an explicit default, then the code to change is further down the function you've highlighted but not that part of the code.

Cheers

**Comment by Teabone3** [comment]
Thanks! I've made a fix for this but I've not added a pull request for it, as its attempting also include commits of my other pull request that is currently pending. Not sure if to proceed or to wait till the other one is approved and merged.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Note that in the latest MAIN commit I have amended the "Entity FPE Fixes" folders slightly so it is easier at our end of add them to builds and get the changes out the door quickly. It's small, but it means you should take your fixes, cancel your pull requests, then update your repo, then copy the fixed files in the new folder structure. It will not change again. Hope this makes sense :)

**Comment by Teabone3** [comment]
Thanks Lee, I hope I did this correctly, I've created a new pull request, just one commit, which adds the soundset = male to the AI which allows for characters from character creator to have voice or voices other than female by default.

So this should be the fix for this issue #4096

**Comment by LeeBamberTGC** [comment]
@Teabone3 Fixed for next BETA and PP update
