### ISSUE TITLE
GGC - Issue - Character Blood Effects Disabled if Disabled in Start Marker For Player

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4058]
Both the player and character entities have a property called Blood Effects. However,

If you disable the Blood Effects in the Start Marker for the player, this disables all Blood Effects for all characters, even if you have Blood Effects enabled in the character entity properties panel.

This means you cannot have a situation where don't have blood effects on the screen, but want it for the individual characters when you hit them. Despite their being the isolating options for this in the UI.

![bloodeffects1](https://user-images.githubusercontent.com/35990109/211706345-5ef28410-2fa3-4da7-8476-25cb4b46e2a5.JPG)
![bloodeffects2](https://user-images.githubusercontent.com/35990109/211706348-11ea3f63-a7b7-4ecb-a2f6-c446d82ead84.JPG)

**Comment by Teabone3** [comment]
For when a fix is made for this, some consideration will also be needed to ensure the 3rd person character bleeds when the player option for it to bleed is enabled.

**Comment by cybernescence** [comment]
I've fixed this, I'll set-up a PR as part of some other changes.

Cheers

**Comment by Teabone3** [comment]
Thanks @cybernescence that would be awesome. Does your changes effect in any way gameplayercontrol.lua? I recently changed line 1782

From:

 if g_PlayerHealth >= 100 then 
 
To:
if ( g_PlayerHealth >= (g_gameloop_StartHealth/2) ) then 

To add a fix for the dying effects not referencing the maximum player health but instead referencing only a fixed 100 value. Additionally adds a /2 to check for 50% of the health instead of 99.

**Comment by LeeBamberTGC** [comment]
@cybernescence I have committed all of Teabone's PRs today, No rush on yours I will be doing builds as soon as they come in for BETA and PP. Plan is a public update in March as usual :)

**Comment by cybernescence** [comment]
@Teabone3 No, haven't touched the lua code. The change just does what you originally asked, that blood effects can be added/removed to player or NPCs individually (rather than turning off the effect for the the player also turns the effect off for all NPCs.). Cheers

**Comment by LeeBamberTGC** [comment]
@Teabone3 Needs confirming of cybers fix so we can close this one.
