### ISSUE TITLE
GGC - Feature Request - Red Screen + Heartbeat as Start Marker Properties

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4059]
The most requested feature that I can recall in the past half decade has been the ability to have more controls over the player's red screen of damage (not blood decals) and the heartbeat sound.

We should have these as options in the player start marker and two separate options. In fact, you could bundle Red Screen effect with the Blood Effect so disabling Blood Effects on the player start marker will stop the red screen effect from playing.

For heartbeat sound either an option to turn this off or on, or a percentage value out of 100 for when to play it. -1 or 0 being not at all.

(I'm full away of workarounds to disable or enable red screen and change heartbear sound, more controls would be more preferred). Especially for newcomers. These effects are usually the tell-all to any Game Guru made game and if you watch people playing these games they tend to throw their headphones off. Its sensory overload for only 99% of health in game. It just happens away too often, so adding these options would be better.

**Comment by Teabone3** [comment]
I've made a pull request which fixes many issues related to the heartbeat and red screen effect #4097
Though it would still be good to have separated options to turn off either heartbeat or red screen within start marker.

The #4097 4097 changes when the heartbeat and red screen occur. Its now set to 50% of health instead of 99 points of health. Which used to also ignore if the maximum was ever greater than 100 in editor.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Fixed for next BETA and PP update
