### ISSUE TITLE
Please add Model pack 3 assets

### ISSUE THREAD

**Issue by tomik18** [TheGameCreators/GameGuruRepo#406]
Cardboard boxes, wooden boxes & crates, heavy duty containers, doors, gates, lights, barrels, power boxes, pipes, planks, shelves, windows.

**Comment by synchromesh62** [comment]
This may not be possible as the original creator has probably not allowed his assets to be given away free.
The free classic collection only contains assets from packs that the original authors has granted permission.

**Comment by tomik18** [comment]
so TGC is not author Model pack 3 ?

**Comment by LeeBamberTGC** [comment]
Please send the link to the Model Pack 3 you refer, there are a lot of model packs out there called Model Pack 3 :)

**Comment by tomik18** [comment]
[https://www.google.sk/search?q=fps+creator+model+pack+3&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjR4az3_OTdAhUoxosKHWzaDUkQ_AUICigB&biw=1680&bih=939#imgrc=3-wDdGyQVBHlGM:](url)

**Comment by tomik18** [comment]
[https://imgur.com/a/YHQ7Vlb](url)

**Comment by tomik18** [comment]
![modelpack3_features](https://user-images.githubusercontent.com/32257860/46282250-4b4b4300-c571-11e8-83c6-24448cd6b282.jpg)

**Comment by synchromesh62** [comment]
That particular one is available here on the FSPC GitHub 
https://github.com/TheGameCreators/FPS-Creator-Classic
But the download is missing a lot of assets which is why im assuming only some assets were givem permission for ?

**Comment by LeeBamberTGC** [comment]
Gotcha, as stated the FPSC model packs are from eons ago and I cannot remember who owned that pack, or why the entire complement of assets is not in the FPSC repo. It's also worth mentioning we are not planning to release new assets that are non-PBR as we feel we have plenty of the legacy art to go around (over 6GB of it in the core product) :)

**Comment by Teabone3** [comment]
Yeah if it wasn't included in the free expansion pack it probably means we just didnt get the approval or response to include. Great items there though for sure.

There are some remaining items that didnt get included in the expansion pack, if you're interested in downloading:

http://freetoronto.org/gameguru/
