### ISSUE TITLE
GG Max: Camera Rotation not working smoothly in Level Editor?

### ISSUE THREAD

**Issue by mauriegit** [TheGameCreators/GameGuruRepo#4063]
Good Day

On the GG Max level editor, rotating my camera with the right mouse click button does not always run smoothly. Sometimes it gets stuck, and freezes, or won't rotate at all, other times it rotates at normal speed, then gets stuck during rotation. 

This is quite a challenge when working with complex structures, as I need the rotation when assembling prefab objects, to see they align correctly. The rest of the camera functionality and keybord shortcuts seems to work fine.

Please assist.
Regards

**Comment by MonkeyFrogStudio** [comment]
What are you system specs? It sounds like the frame rate is dropping as you work, especially when "complex structures" are in view.

**Comment by mauriegit** [comment]
Hi

Specs:

Aorus CPU
Graphics: GTX 3060

My PC, though bought in 2020, is pretty much brand new, custom built.

My apologies. Complex structures refer to prefab assembly, but have experienced this even with very few objects sometimes.

I purchased your Off World station pack, and I am practicing using the parts, so the camera rotation is quite essential. I checked the frame rate, appears normal?

Regards.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by MonkeyFrogStudio** [comment]
Yep! Sounds like you have a (more than) good enough system to run MAX. Thanks for sharing your system specs.

Something is going on, but I don't think it's MAX. Until recently, I was running an older system with an older card, and was having no issues in the view port, even with complex levels. I've always found the view port to operate very smoothly for me. I wonder if something else is going on?

BTW - Which version of MAX are your running? Is it the latest experimental build?

Also, thanks for getting the Offworld Station DLC! :)

**Comment by mauriegit** [comment]
Hi
Thank you.

My camera rotation worked better now when I switched to Steam online mode, but bear in mind there will be times when  I’ll have to switch to offline mode.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by MonkeyFrogStudio** [comment]
It shouldn't make a difference. All that's happening with MAX and Steam is a check in (it needs to check in once a month, I think) to make sure it's an authentic (not pirated) version. Other than that, there should be no difference running with Steam online or off.

**Comment by mauriegit** [comment]
Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mauriegit** [comment]
Hi

Hope you are well. My apologies. My proper PC specs are as follows. I believe I am far exceeding the minimum requirements to run GG Max, unless I’m missing something?


  1.  MS Windows 10
  2.  CPU: AMD Ryzen 7 5800X 8 Core Processor
  3.  GPU: Nvidia GeForce RTX 3060

I am also running the software on a super fast SSD, and GG Max currently only uses 811.7 MB of my memory (checked the performance on my task manager).

Since our last communication, my camera rotation has worked better, but still slows down and gets stuck now and then. No other performance issues on the software or frame rate (I checked that too). So as of currently I can manage relatively well, but I would still appreciate any further advice or investigation if possible on this issue please.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mauriegit** [comment]
Hi MonkeyFrogStudios

I have since fixed this issue, and will be closing this ticket. Apparently the problem was because I didn't double left-click on an object, before trying to rotate with the right click. I am now able to rotate my camera smoothly without any problems. But thank you for your assistance. Much appreciated.

Regards
