### ISSUE TITLE
GG Max - Bug - Mammal Behaviour not working on some maps

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4065]
Hi,
As the title says, The Mammal Behaviour does not work on some maps.
Here is a screenshot of the player stood right in front of a fox that does not run off.
I have enabled the test level AI mapping and you can see the many red lines coming from the Fox, i guess these are the paths it may choose.
But it does not move away.

This also is the same for rabbits and other animals that use this script

I even tried this on a new EMPTY level. Still did the same thing.

![Untitled](https://user-images.githubusercontent.com/66874403/212077602-2b8dc245-f56e-4b9c-9c9d-9c998b53d460.png)

![Untitled](https://user-images.githubusercontent.com/66874403/212080923-21d7b5ab-78f5-4143-9246-27a6af794391.png)

**Comment by davetgc** [comment]
Hi, are you able to post a video please? I've tested this and can't find a map they don't work on.

**Comment by Tum1370** [comment]
@davetgc I have said before i dont do videos.
This is a bug, everyone on discord has the same problem.
You dont need a  map.
Start a EMPTY world, place the animal down, It doesnt move.

**Comment by Tum1370** [comment]
3 animals, empty map, i run straight up to them and they all just stand there.
This is a bug, i cannot do a video.

![Untitled](https://user-images.githubusercontent.com/66874403/212339398-292e5061-1e24-4f98-b34c-258a5af8bfc8.png)

**Comment by davetgc** [comment]
Ok, I've confirmed this now. Thanks for the report.

**Comment by ZakJudges** [comment]
@Tum1370 Thanks for reporting. A new Steam EXP is up now with a fix :)

**Comment by Tum1370** [comment]
I can now confirm this bug has been fixed on the latest EXP build. 
Am closing this issue.

Thanks
