### ISSUE TITLE
GG Max - Bug - Experimental Build - Create Standalone Game crashes 

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4066]
Just tested creating a Standalone game on the Experimental Build.
After the Standalone has been created, i moved the game folder to my desktop, Then loaded the Standalone game.
Had these 2 errors when trying to play the game.

![Untitled](https://user-images.githubusercontent.com/66874403/212083899-9dac9e66-f938-490a-b322-e7fc92be6b50.png)
![Untitled1](https://user-images.githubusercontent.com/66874403/212083913-908ab1f6-5fb7-4279-a662-0dac548eb56d.png)

**Comment by davetgc** [comment]
This certainly looks like a bug. Can anyone else replicate this please, so we can rule out local issues.

**Comment by Tum1370** [comment]
This is only happening on the experimental build.
I just retested this on the normal version of Max and the Standalone works fine.

Surely you can just test this quickly yourself ?

**Comment by davetgc** [comment]
Unfortunately my time is limited. If I were to test every bug reported, I'd have no time for anything else. There are others in the team and community who do a good job at testing.

**Comment by Tum1370** [comment]
I also noticed that on the Standalone i made using the normal Steam build of Max, I had used a green smoke particle from the particle editor. That did NOT copy over to the standalone.
I checked this bug, and noticed it was reported it in July last year, so guess it still needs fixing,

**Comment by synchromesh62** [comment]
As i happened to be doing some testing i gave it a try.
I can confirm the issue when running the Standalone.

**Comment by Tum1370** [comment]
@davetgc  Hi Dave, This is still crashing when creating a Standalone game and running the Standalone.

**Comment by Tum1370** [comment]
I can now confirm this bug is fixed on latest EXP build. 
Closing this issue.

Thanks
