### ISSUE TITLE
appauling performance and fps

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4071]
5 fps.

even with everything turned off, shadows and all the other visuals. its been like this for months and just not seeing any improvements to a point I'm considoring giving this entire titanic project up.

got a video of how it looks and feels. The lights are acting very strange, turning off and on as you move to different locations, the auto exposure is all over the place, everything looks terrible and it just runs awrful.

https://www.youtube.com/watch?v=5caWVO_6sKU

**Comment by davetgc** [comment]
Auto exposure can hit frame rates, but I can't help noticing the massive number of draw calls and the millions of poly the engine is attempting to render. Also, you are limited to the number of lights available, with a maximum of 16.

**Comment by casigus** [comment]
I give up. 16 lights max is useless. You give us a massive open space and we can have a max of 16 lights?!!!!!??? What's the actual point? If I knew how limited ggmax actually was I'd have never tried in the first place. People Will want to build and build big. These limitations are huge creative restrictions. The end result of this will be 100s of ggmax games that are pretty much carbon copies of each other. I'm pushing a rock up a mountain. I'm just going to count my losses and cancel THIS entire project. I can't finish it with all these limits. Thanks for your help.


On 14 January 2023, at 07:20, davetgc ***@***.***> wrote:


Auto exposure can hit frame rates, but I can't help noticing the massive number of draw calls and the millions of poly the engine is attempting to render. Also, you are limited to the number of lights available, with a maximum of 16.

**Comment by davetgc** [comment]
You're misunderstanding, not 16 lights for your entire map, but 16 lights active at once.

**Comment by Ghost-l0l** [comment]
huge amount of polygons and drawcalls is only part of the problem; when I was building aztec example map I had about 20milion polys rendered at once (not all the time but in some areas of the level) and still about 50fps. 
![performance1](https://user-images.githubusercontent.com/101792609/212475810-ce8ae8e9-6d09-4fb1-b8bf-6153ca9f3f83.jpg)

Few things that might cause slowdown:

- big number of active animated characters on the scene. GG Max stock characters have huge amount of animations saved as one long sequence, so the dbo file can weight up to 8-12mb. Usually you won't see it in gameplay, as most scripts will use maybe about 20% of all these animations, but engine will still load everything everytime for each character model. 

- Textures used in your custom models are probably big and heavy, you probably can compress them a lot without much noticeable difference in quality (same thing can be said about a lot of gg max stock models)

- There's probably too many polygon collisions. Is that ship one big model with polygon collision? Polygon collisions are very heavy to calculate for any engine. "Big" games usually use very simple collisions for most assets, usually it's just done so well  gamers don't even notice. 

- Huge amount of dynamic lights and scripts active at once surely also add to the problem

That's just few of my guesses, worth to check it out. I can agree that Max optimization is far from perfect, but all those things I've mentioned would cause slowdowns in any engine. Just remember that "big" games trick u all the time, and when you try to match that AAA scale and visual quality without these "tricks" (ok its not really a trick, just optimization of every possible aspect of the assets/scripts/level design etc) you will run into a wall every time.

**Comment by casigus** [comment]
thanks ghost, yeah you've preetty much hit the nail on the head. Im in a count my losses move on thing atm.  your scene is beatiful btw. really loving the way you've built that.

am gonna just bury my head in the sand for now. Honnestly a year and a half of this titanic game and im so fed up with it.

the motivation to carry on is firmly out the window.
________________________________

**Comment by synchromesh62** [comment]
**16 lights max is useless**.
I thought it was up to 16 lights casting shadows in one area ? and  that was distance detected so another area could have another 16.
other than that you can have as many as you like i thought if you mix ones with "Do not cast shadow" 
Leadwerks only gave you 8 that cast shadows.

**Comment by davetgc** [comment]
@casigus - Has this answered your questions. All engines need some optimization on the part of the developer, where good level design can solve a whole host of issues. We will of course continue to work on performance, but it's a two way street.

**Comment by casigus** [comment]
yes! also decided to take a long break from the project too to rest my brain.

thanks everyone for the info!


________________________________
