### ISSUE TITLE
opening the menu restarts the audio track.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4072]
when your making a game that depends on the audio track to flow with the in game events and you need to pause for what ever reason, its really not ideal that bringing the menu up resets the track.

heres what happens:

https://www.youtube.com/watch?v=i_ZNZKm2j3M&feature=youtu.be

the audio is suppose to run with the entire collision sequence, however with this it just breaks everything. 

its just one thing after the other with ggmax.

**Comment by LeeBamberTGC** [comment]
@casigus In latest version, the music is paused and resumed when in standalone in-game menu
