### ISSUE TITLE
GameGuru MAX - Bug - Import Issue?

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4076]
I think there may be a rounding issue when importing models because sometimes a model that aligns perfectly in Blender will not align perfectly in MAX depending on where the object origin is. I will try to demonstrate.

Here's a screen shot of two pieces that are snapped together in MAX:

_This one shows one piece selected so you can see where the two pieces meet:_
![align1](https://user-images.githubusercontent.com/36735507/212525895-4a3eb6fa-c513-41de-8f7d-e09d73588fea.png)

_This one is without either piece selected:_
![align2](https://user-images.githubusercontent.com/36735507/212525930-25535bab-d650-4f2c-bc9e-dce5963c0ad1.png)

Notice that they snap together just fine. 

Now, if I alter the piece's origin to another place where it should still snap perfectly with other pieces, this happens:

_Again, a piece is selected to show where they are snapped together:_
![align3](https://user-images.githubusercontent.com/36735507/212525991-7311b406-8688-4e96-88eb-658614af389a.png)

_And with neither piece selected:_
![align4](https://user-images.githubusercontent.com/36735507/212526004-48ad59bd-5763-4557-abc8-dc0a60a3bf5f.png)

In the last image, you can see a gap has appeared between the pieces, despite being snapped exactly as the other piece was. However, if I rotate the object around 180 degrees, then it snaps perfectly on that side. Rotate it back (or an additional 180 degrees) to the original side and the gap is there (as seen in the screen shot). The first one (first two images)? I can rotate it 180 degrees and both sides snap as they should. 

For all intents and purposes, this is the same model. The only difference is the second model's origin had been shifted. I had shifted it to allow the model to be more easily rotated into place. It snaps perfectly, with the same snap settings, in Blender, but leaves a gap in MAX after import. So each version snaps perfectly in Blender, then I am assuming (and, yes, that's dangerous) that something is going on with A) the importer (perhaps a rounding error is slightly shifting the vertices of the object) or B) with the FBX export from Blender.

While the gap in the last image does not seem significant, it's easily seen when walking around the level. And, depending on where I place the origin, the gap can get even worse.

**Comment by davetgc** [comment]
A couple of artists have mentioned this, so something is slight off with the importer.

**Comment by MonkeyFrogStudio** [comment]
Getting this more and more. Here's an image where the model aligns perfectly in Blender, but doesn't in MAX:

![align](https://user-images.githubusercontent.com/36735507/213883401-9042978f-d72a-4b2b-a3a1-dce46c43b1fd.png)

The opposite end still aligns perfectly in MAX, though. It's just this one side at the moment.

**Comment by MonkeyFrogStudio** [comment]
This appears to be fixed.
