### ISSUE TITLE
Just small bug after the latest update! The news box!

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#4078]
I launch steam and it went through the Normal update and I looked to see what is new on the latest update, I found the news screen on the top left corner of the screen and only shows small part of it. ![image](https://user-images.githubusercontent.com/81198887/212590725-2dab513a-de46-4b15-82d0-fe11f33d3126.jpeg)

**Comment by davetgc** [comment]
I'm not seeing this, it looks like a local issue. Has anyone else experienced this at all?

**Comment by Hamada880** [comment]
After the latest update today it works as before.

**Comment by davetgc** [comment]
So, is this fixed, and can it be closed?

**Comment by Hamada880** [comment]
Yes, I'm going to mark it as completed, just tested it again and I can confirm it works now.
