### ISSUE TITLE
Can't create button at main menu

### ISSUE THREAD

**Issue by Wilco9000** [TheGameCreators/GameGuruRepo#4081]
I delete button at main menu of the game and cant create another one.

**Comment by davetgc** [comment]
Can you please explain a little more. I'm assuming you're talking about MAX. If possible, please provide screenshots or ideally a video.

**Comment by Wilco9000** [comment]
> Can you please explain a little more. I'm assuming you're talking about MAX. If possible, please provide screenshots or ideally a video.

![1](https://user-images.githubusercontent.com/122837775/213244832-d64f7c90-5c8d-4984-ad38-d85a328461ad.jpg)

**Comment by ZakJudges** [comment]
Hi @Wilco9000, thanks for reporting this issue. I have added some code that will prevent deletion of buttons in the default storyboard screens. This change should be in the next experimental build.

We are still actively developing the Storyboard Editor, and plan to allow adding your own buttons. But for now, preventing button deletion should do. 

Unfortunately, to get the button back at the moment, you would need to create a new storyboard project. All of your maps will still be intact in the mapbank folder. Alternatively, you can wait for the ability to add buttons back in.
