### ISSUE TITLE
wander_around.lua ignores range value

### ISSUE THREAD

**Issue by smallg2020** [TheGameCreators/GameGuruRepo#4082]
there's a bug with the default wander_around.lua logic where it ignores the 'range' value when checking how close the player is.
i have attached a fixed version of the byc file that will make the script work as intended
[wander_around.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10436618/wander_around.zip)

**Comment by davetgc** [comment]
Thanks

**Comment by ZakJudges** [comment]
@smallg2020 Thanks for the fix. I have uploaded the updated .byc file to the experimental build
