### ISSUE TITLE
Wander Behaviour does not work at distance

### ISSUE THREAD

**Issue by stuartds86** [TheGameCreators/GameGuruRepo#4083]
Hi. When using the Wander Behaviour. NPCs are not active at any great distance from the player. It seems like always on doesn't work nor does changing the range they are active. So NPCs only become active when player is close to them. Having wandering NPCs active at greater ranges would be useful for sniper missions. I raised this on Discord Scripting Thread on 17/01/2023 and SmallG came up with a solution that it might be worth integrating into the main product. Thanks.

**Comment by davetgc** [comment]
I can confirm this.

**Comment by Tum1370** [comment]
@davetgc 
I tested this one yesterday, The behaviour Wander has a maximum range of 400.
If i set the maximum range to above the 400, and set Always Active enabled (which is only really needed at ranges over 3000), The Wander does not work.

The 400 Maximum range seems to be hardcoded in the behaviour ??

**Comment by ZakJudges** [comment]
Hi all, this should now be fixed the latest experimental build, thanks to #4082
