### ISSUE TITLE
GameGuruMAX Relfection Update issue

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#4087]
There is a window reflection bug

https://user-images.githubusercontent.com/82841733/213157463-8ad9ffdf-a58f-4ba9-8d44-5ac94a01deb4.mp4

**Comment by davetgc** [comment]
Hi, that video was empty for me. Can anyone else see it?

**Comment by MonkeyFrogStudio** [comment]
@davetgc If you download it, you can then play it.

I will try to upload it here from my PC to see if it plays for you:


https://user-images.githubusercontent.com/36735507/213366362-b92e0ed1-c8eb-4421-ba49-760f5ff6a41e.mp4

**Comment by davetgc** [comment]
All I'm getting is audio.

**Comment by MonkeyFrogStudio** [comment]
@davetgc See if you can view this one:

https://user-images.githubusercontent.com/36735507/213367880-8d9174d7-a200-4304-be3e-cc245d5632be.mp4

**Comment by davetgc** [comment]
That works, thanks.

**Comment by LeeBamberTGC** [comment]
@wizardofid29 This relates to a crude env map system issue which has since been updated.
