### ISSUE TITLE
GG Max- Bug - Character heads disappear after a range of 3600

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4088]
I was just testing setting up some long ranged character targets for sniping with the patrol rifle.
Am finding that after having the characters at a further distance than about 3600, The Heads of the characters disappear. 
Does not look good for sniper games.

![Untitled](https://user-images.githubusercontent.com/66874403/213158459-edeb6bbc-86b5-4477-94d0-94c2a024d63a.png)

**Comment by ZakJudges** [comment]
Hi @Tum1370, thank you for reporting this issue. I have added a fix which you should see in the next experimental build, later today :)

**Comment by Tum1370** [comment]
@ZakJudges I can confirm that this bug is now fixed on the latest EXP build.
Thanks for the fix Zak, Ill close this issue now.
