### ISSUE TITLE
GameGuru MAX - Request - Snapping for Storyboard Elements/HUD

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4090]
I would like to request adding snapping to the Storyboard editor, especially in the HUD editor so we can exactly line up HUD elements, buttons, etc.

**Comment by davetgc** [comment]
Does the grid system not work well enough?

**Comment by MonkeyFrogStudio** [comment]
@davetgc This request is for the STORYBOARD editor. There is no snapping there at all. The visible grid does not help when you want to perfectly align HUD elements. That grid is also not resize-able, since it's just a visual piece, so even using it visually is limited.

In any case, this was brought up during the live broadcast and Lee agreed it was needed. I added it here as a request so that it wouldn't be forgotten.

**Comment by davetgc** [comment]
Sorry, I misread :).

**Comment by synchromesh62** [comment]
@MonkeyFrogStudio 
Am i miss reading this ?
![grid](https://user-images.githubusercontent.com/35708217/213922498-86b5341d-a8c4-4e19-b1a1-b68398d8f5bb.png)

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 Was that in there before I'd made this request? To be frank, I haven't messed about with the storyboard editor in months. But when I'd asked Lee about it during the live broadcast, he said it was needed, which is why I'd made the request here. But, like I said, I might have missed it since it's been so long since I'd toyed with this area and I don't recall it being there originally.

**Comment by synchromesh62** [comment]
> @synchromesh62 Was that in there before I'd made this request? To be frank, I haven't messed about with the storyboard editor in months. But when I'd asked Lee about it during the live broadcast, he said it was needed, which is why I'd made the request here. But, like I said, I might have missed it since it's been so long since I'd toyed with this area and I don't recall it being there originally.

Well i thought it had been there for some time so i rolled back from the EXP to the 14-10-22 build and although there is no hud editor in that one the grid size and snapping is for the storyboard.

**Comment by MonkeyFrogStudio** [comment]
Thanks. I will close this.
