### ISSUE TITLE
GameGuru MAX - Request - Inventory to Allow Use of Mouse Cursor

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4093]
It's pretty common in RPGs, when accessing the inventory, to be able to use the mouse cursor to select inventory items so you can use them or even just move them. Some may want to do simple "housekeeping" and have all their apples next to each other or have their pistol next to their pistol ammo, etc. So, being able to move things about in your inventory is a nice feature to have (and, again, quite common in RPGs and other games that have an inventory system). It also allows the developer of their game to cut down on the number of key binds used. So, a double click on an item uses it (or select the item and press the Action/Use key - normally "E" - to use). 

This could also open the possibility of a **_right-click_** menu, too. For example, right-click to access things like drop or delete selected inventory item, multi-select and right-click to combine (like creating a potion), move to junk (some RPGs have a junk screen where you can dump a bunch of stuff from your inventory, then go and delete it all at once), etc.

**Comment by davetgc** [comment]
I'd say this is a must have feature to bring the editor in line with most games.

**Comment by Necrym59** [comment]
have you used the mousecontrol script?

**Comment by MonkeyFrogStudio** [comment]
We're just asking for basic functionality to be used in while in an inventory screen. This is not about behaviors, etc. ;)

**Comment by Necrym59** [comment]
I was just answering daves mention that he wanted an easy way of allowing mouse use to activate objects in game, the mouse control does that. Mouse cursor in the inventory and huds is a given.

**Comment by MonkeyFrogStudio** [comment]
Aw, sorry. Was thinking of the original topic of this request. Perhaps, next time, address Dave specifically or quote what you're replying to. But I also should have read better. Apologies. :)
