### ISSUE TITLE
Alpha channel problems...

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#41]
In the public preview some entities have graphical glitches..
I wrote a thread about this in the forum. Maybe someone can help !

https://forum.game-guru.com/thread/219287

**Comment by plemsoft** [comment]
That is caused if the fpe is not using the tree shaders. could you let me know where i can find this tree with this problem so i can check the fpe and shaders :) , if its a custom object just email it to me at plemsoft@plemsoft.com , and please also include the .fpe file.

**Comment by plemsoft** [comment]
Thanks for your e-mail.

This is a custom object by BSP, to correct the problem edit the "Deat Tree 01.fpe" using notepad.

Locate this line:
effect        = effectbank\reloaded\entity_basic.fx
And replace it with this line:
effect        = effectbank\reloaded\treea_basic.fx

Save the file, and your done!

The other Trees in the BSP pack also have this problem, perhaps you could PM BSP and ask if he could change the fpe files directly in the pack so other people will not get the same problem.

Also treea_basic.fx is faster, so this will also speed up your level a little bit :)

**Comment by Teabone3** [comment]
Could the fixed label be added? That way it be easier to see which issues are closed.

**Comment by Duchenkuke** [comment]
its not fixed yet... his fix didnt work


________________________________
Von: Teabone <notifications@github.com>
Gesendet: Freitag, 2. Februar 2018 20:53
An: TheGameCreators/GameGuruRepo
Cc: Duchenkuke; Author
Betreff: Re: [TheGameCreators/GameGuruRepo] Alpha channel problems... (#41)


Could the fixed label be added? That way it be easier to see which issues are closed.

**Comment by plemsoft** [comment]
You need to use pbroverride=0 in the PP version.

In the GitHub version pbroverride has been disabled and it is working.

Left trees is using "effect = effectbank\reloaded\treea_basic.fx".

![trees](https://user-images.githubusercontent.com/18662417/35759427-eb36e88e-0879-11e8-8eb8-bfab7facbe83.jpg)

**Comment by plemsoft** [comment]
Teabone , just found the tags and added fixed :)

**Comment by Duchenkuke** [comment]
Alright, Thank you Preben 😊


Will set pbroverride to 0 in the meantime.


________________________________
Von: Preben Eriksen <notifications@github.com>
Gesendet: Samstag, 3. Februar 2018 01:53
An: TheGameCreators/GameGuruRepo
Cc: Duchenkuke; Author
Betreff: Re: [TheGameCreators/GameGuruRepo] Alpha channel problems... (#41)


Teabone , just found the tags and added fixed :)

**Comment by Duchenkuke** [comment]
Even with deactivated pbroverride the issue is still there -.-


Just wanted to let you know lol


________________________________
Von: Felix Kolbeck
Gesendet: Samstag, 3. Februar 2018 07:50
An: TheGameCreators/GameGuruRepo
Betreff: AW: [TheGameCreators/GameGuruRepo] Alpha channel problems... (#41)


Alright, Thank you Preben 😊


Will set pbroverride to 0 in the meantime.


________________________________
Von: Preben Eriksen <notifications@github.com>
Gesendet: Samstag, 3. Februar 2018 01:53
An: TheGameCreators/GameGuruRepo
Cc: Duchenkuke; Author
Betreff: Re: [TheGameCreators/GameGuruRepo] Alpha channel problems... (#41)


Teabone , just found the tags and added fixed :)

**Comment by plemsoft** [comment]
>Even with deactivated pbroverride the issue is still there -.-

Even with pbroverride= 0 , you still need to edit the fpm and change to this shader:
effectbank\reloaded\tree_basic.fx

**Comment by Duchenkuke** [comment]
I did.


________________________________
Von: Preben Eriksen <notifications@github.com>
Gesendet: Samstag, 3. Februar 2018 13:36
An: TheGameCreators/GameGuruRepo
Cc: Duchenkuke; Author
Betreff: Re: [TheGameCreators/GameGuruRepo] Alpha channel problems... (#41)


Even with deactivated pbroverride the issue is still there -.-

Even with pbroverride= 0 , you still need to edit the fpm and change to this shader:
effectbank\reloaded\tree_basic.fx

**Comment by Teabone3** [comment]
I should add that this issue is also present in a building model in the Mega Pack 3 DLC. Part of the building has rails that are very thin and the edges of them are not only white... but appear to have a type of cubemap active on them.
