### ISSUE TITLE
Triggering object from trigger zone and ifused field broken.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4103]
Using player in zone behavior and triggering/spawning an objects named in the ifused field rather than via visual editor, the object is no longer trigged/spawned. This behavior is vital when spawning objects at large distance apart.

**Comment by synchromesh62** [comment]
Issue confirmed .. 
Very handy for triggering an item over a vast distance you cannot link with logic.

**Comment by ZakJudges** [comment]
Hi @davetgc Thanks for reporting, a fix should be in the next EXP build :)

**Comment by Necrym59** [comment]
Updated plrinzone to have ActivateIfUsed(e) back in
but im not sure if its activating Zak
[plrinzone_v4.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10470809/plrinzone_v4.zip)

**Comment by synchromesh62** [comment]
Ok yesterday i tried it with @Necrym59 script and it still did not work.
Today its working fine ?
Confirmed Ifused Working with the script above.

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
