### ISSUE TITLE
Swimming Speed Doesn't Save

### ISSUE THREAD

**Issue by Technodweeb** [TheGameCreators/GameGuruRepo#4104]
When I change the swimming speed of the user then save, close the program and then reopen the level, the swim speed is back to original setting. ( I am using the current Expeimental Build)

**Comment by ZakJudges** [comment]
Hi @Technodweeb, thank you for reporting this issue. I have added a fix that you should see in the next experimental build :)

**Comment by Technodweeb** [comment]
Thanks!

**Comment by Technodweeb** [comment]
Works Now thanks!
