### ISSUE TITLE
Project Folders GGMax- Sorting Issue

### ISSUE THREAD

**Issue by Technodweeb** [TheGameCreators/GameGuruRepo#4106]
When opening the Project Folder Page,  Under My Projects, the "Most Recent "sort  option is not working. It doesn't NOT show you the most recent project first. Least Recent is off too. A to Z works so does Z to A

**Comment by LeeBamberTGC** [comment]
@Technodweeb Seems to work in latext EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/359fdee5-46c4-489e-91fd-ecbf869536e3)
VS
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/161dc751-2b5c-4073-9117-16f471151e8b)

**Comment by Technodweeb** [comment]
Yes it does thank you!  I asked that question in January, and  apprecaite your still getting to it.
Thanks again Lee!

**Comment by Technodweeb** [comment]
It is not sorting correctly again. Recent projects does not sort it so the most recent project is first. Least  ecent projects is the same.
Sorting by alphabet is ok. as before. Thanks!
