### ISSUE TITLE
Feature Request: Demo Games

### ISSUE THREAD

**Issue by Technodweeb** [TheGameCreators/GameGuruRepo#4107]
Could we have an option to choose to download the Demo Games ,  rather than have them automaitcally download to our hard drives?

**Comment by davetgc** [comment]
Does anyone else find this an issue. The media for the demo games is present in MAX, so all the demo games really are are a project and a map file?

**Comment by synchromesh62** [comment]
Its only the .fpm files  1.02 gig of space is used.
your not going to save that much really .. However i would prefer those .fpm's to be put in a sub folder so they are not mixed with mine ..for example ..  **\ Documents \ GameGuruApp s\ GameGuruMAX \ Files \ mapbank \ Demos\**

**Comment by Technodweeb** [comment]
I prefer to just keep my own work on my computer and examples of work, that I may need or want to check out. It would be nice to have the option to add them or to remove them.   If that isn't possible then I will just delete the ones I want to get rid of from the folders.

**Comment by Tum1370** [comment]
Ye i agree with Synchro that the Demo do not take much space, but would definitily be better kept in a separate DEMO folder
