### ISSUE TITLE
Lua Error on standalone

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#4109]
![image](https://user-images.githubusercontent.com/107326667/213918267-e14bdc63-9cd8-41f7-9453-d36fb1b8bd91.png)

**Comment by Tum1370** [comment]
I Guess this is on the experimental build of Max ?
I reported this last week, yet its still not marked as a bug.

**Comment by davetgc** [comment]
Closed as duplicate of #4066
