### ISSUE TITLE
Max launching error and crash 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4110]
This just started happening on launching.
Have we had an update today ?
Reinstalled from fresh to confirm.

![broken](https://user-images.githubusercontent.com/35708217/213940460-2a1b0680-ce7f-4451-87fb-c79341e9fba7.png)

**Comment by Tum1370** [comment]
Yes the update was about 30 minutes ago, and can confirm that when i try and test a level i get the errors.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 @Tum1370 Seriously guys and gals, I uploaded 5 minutes ago. Do you live in the MAX universe these days :)  New update uploaded with much fix :)

**Comment by synchromesh62** [comment]
So far so good :)

**Comment by synchromesh62** [comment]
Thanks Lee 
Seems to have sorted the issues all but the **imagezone** not working
Not sure if this is related or was already there though.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Looks like a typo in the script, fixed now :)

**Comment by synchromesh62** [comment]
> @synchromesh62 Looks like a typo in the script, fixed now :)

Confirmed all working as it was now including Image Zone 
Thanks Lee
