### ISSUE TITLE
Bug: "What's new?" screen is broken.

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#4111]
https://user-images.githubusercontent.com/112423658/214091436-75885d9d-7e84-4c01-b47d-b656af7e1dde.mp4

The only way to leave the screen is to press escape.
(using the latest experimental build)

**Comment by Tum1370** [comment]
This is working fine on my version. I am using the latest Experimental build.
Maybe verify your files ?

**Comment by MonkeyFrogStudio** [comment]
Working fine here, too.

**Comment by waterdrinkingfox** [comment]
I verified files but it didn't work. Had to reinstall GGMax for it to get back to normal. Weird.
