### ISSUE TITLE
negative values in dynamic lua

### ISSUE THREAD

**Issue by smallg2020** [TheGameCreators/GameGuruRepo#4112]
can we please get the ability to set negative values in the behaviour editor without needing to fight the system?
i.e. if we set a slider with a minimum negative or a normal value but set the default value less than 0 it will always reset to 0

**Comment by smallg2020** [comment]
yh but only until you try change the value, looks like the slider can't go below 0 so ranges and normal integer settings always revert  to 0 if you try put a value below 0
[https://youtu.be/ErjCj2wMdng](url)

**Comment by Necrym59** [comment]
On the INT one there doesnt seem to be a negative i can see that now
On the Float it seems ok
On the Range you havent put the # at the front eg: [#NegativeRange=-10(-10,10)] it should give negative values

**Comment by smallg2020** [comment]
true, i didn't really want a float so i didn't try it, weird that it works ok with floats but not integers, i'll just use float ranges for now, thanks :)

**Comment by Necrym59** [comment]
yeah dont know why integers dont have it maybe the range is enough

**Comment by ZakJudges** [comment]
@smallg2020 Thank you for reporting this issue. This turned out to be a bug with the DLua system. A new EXP build has been uploaded with the fix, which should allow negative values with integer sliders :)

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
