### ISSUE TITLE
GG Max - Saving Standalone - Does not save a map if its not connected on Storyboard

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4113]
HI,
I just had a quick test of creating a Standalone game where i do not actually have it set up in Storyboard to go to next level.
But on the actually map itself, I use the WinZone, GOTO SPECIFIC LEVEL, Then select the Level.
After saving as a Standalone, The only Map that was saved in the Standalone was the First map.

![1](https://user-images.githubusercontent.com/66874403/214367323-460ab7f9-bcb6-4852-b457-068d6d2e8134.png)
![2](https://user-images.githubusercontent.com/66874403/214367338-22befec7-9edb-4ef2-bfa4-40b1f45ce20a.png)

**Comment by Tum1370** [comment]
Thanks for the fix.
Just tested this one and can confirm it is fixed in EXP build.
Ill close this now.

**Comment by Tum1370** [comment]
I have reopened this issue, As after testing it, I noticed that after the fix, When creating a Standalone game, ALL maps that are on the Storyboard are copied in to the Standalone, And not just the Maps that are either connected on the Storyboard, or setup on the Map using a Winzone to GOTO a specific level.

The fix just seems to COPY EVERY map that is on the Storyboard whether the game needs it or not.

**Comment by Tum1370** [comment]
@ZakJudges  LOL, i suppose i dont really have a case for not connecting the map in storyboard.

Do you want me to close this issue ? As its not a real problem !

**Comment by ZakJudges** [comment]
No worries, I will close this issue in that case. Thanks :)
