### ISSUE TITLE
Particles not spawning from trigger zones when called by IfUsed field

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4126]
When a particle is set to not show at start, it doesn't spawn when activated from a trigger zone via the developer IfUsed Field, but does work via Visual Logic.

**Comment by Tum1370** [comment]
Just to add to this new post regarding Particles.

When you create a Standalone, Particles do not copy over to the Standalone that are used, But it does copy over loads of particles that are not used on the map.
I posted about this July last year and its still not fixed. Maybe look at this bug at same time.

**Comment by LeeBamberTGC** [comment]
@davetgc Fixed for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/73728d70-63cd-4585-8ed0-b5601817c587)
