### ISSUE TITLE
Performance inconsistant and jerky with latest builds.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4127]
I'm seeing more jerky/stop start. freezing, etc  happening with the recent builds. This used to be a problem, which went away with the X12 work, it has returned with X11 and the latest builds. At a guess I'd say the builds in the last week as it wasn't apparent when we first returned to X11.

I've a level that ran at a steady 60fps, and now has inconsistent FPS drops to 30fps, which then shoot back up. It doesn't always happen in the same places, so it's difficult to pin down.  Draw calls seem to be back up with the later builds as well.

**Comment by synchromesh62** [comment]
Tested and confirmed
seeing the same thing. As stated it was an old one we had in the DX11 builds and not sure if it was totally fixed before we went to the DX12.

**Comment by ZakJudges** [comment]
Hi all, do you continue to experience this issue in the most recent EXP build?

**Comment by davetgc** [comment]
Hi @ZakJudges - Let me run some tests, it was happening to me yesterday, so I'll let you know if it still is.

**Comment by davetgc** [comment]
@ZakJudges - It has improved in the latest build, but there are still brief and noticeable freezes, especially when the draw calls change dramatically. I think this highlights the need for a more effective occlusion system.

**Comment by Kitakazi** [comment]
Yes I experience this.  ALOT of freezes and stutters.  

It doesn't seem to me that the occlusion system is working correctly. For example I have a big indoor level with alot of assets. The player goes down a long corridor that leads pretty far away from the main group of assets. Once I get super far away if I turn the camera towards the direction of the main chunk, frames will tank hard even though the camera is facing a wall and there is no clear sight to these assets that are 10,000 units away. 

But even besides that just turning the camera quickly on almost any level will produce stuttering and freezes.
