### ISSUE TITLE
I downloaded this game engine but...it doesn't work I downloaded it twice and moved the files twice from D to f...it didn't work either and I deleted it and downloaded it again the program opens and gives me a black screen and closes...I want a solution please

### ISSUE THREAD

**Issue by MohamedAhmed19** [TheGameCreators/GameGuruRepo#4128]
I downloaded this game engine but...it doesn't work I downloaded it twice and moved the files twice from D to f...it didn't work either and I deleted it and downloaded it again the program opens and gives me a black screen and closes...I want a solution please 
I checked... The texture editor works and the effects editor works too, but the game engine works and gives me a black screen that goes out by itself... Ram 8 +16... Nvidia Mx130... Computer OS 64... Processor Intel(R) Core (TM) i7-10510U CPU @ 1.80GHz 2.30GHz 
There are other games and software that have a problem with the MX130 but it runs smoothly like a cyberbank... If I move the files to the c drive does that make it Works? .. Because the program, as I said, works, but it opens and closes again, but it works

**Comment by AmenMoses** [comment]
If you are referring to MAX then the MX130 is well below minimum spec!

**Comment by MohamedAhmed19** [comment]
This is a laptop, not a computer... unfortunately the card cannot be replaced

**Comment by davetgc** [comment]
I'm afraid that your system doesn't reach minimum spec. This will be the causes of the crash. You can compare your card with the minimum card requirements here: https://gpu.userbenchmark.com/Compare/Nvidia-MX130-vs-Nvidia-GTX-970/m439531vs2577

There should be no need to move your files after installing from Steam.

**Comment by MohamedAhmed19** [comment]
> أخشى أن نظامك لا يصل إلى الحد الأدنى من المواصفات. سيكون هذا هو سبب الانهيار. يمكنك مقارنة بطاقتك مع الحد الأدنى لمتطلبات البطاقة هنا: https://gpu.userbenchmark.com/Compare/Nvidia-MX130-vs-Nvidia-GTX-970/m439531vs2577
> 
> يجب ألا تكون هناك حاجة لنقل ملفاتك بعد التثبيت من Steam.
> 
> لسوء الحظ ، إذا كنت ترغب في إنشاء ألعاب ، وتحديدا الألعاب الراقية ، فإن معظم المطورين يجدون أنهم بحاجة إلى آلة متطورة.


No intention to lower the minimum engine...or any other solution...please

**Comment by DaveTGC2** [comment]
We will be working on performance improvements, but we are using the Wicked engine as a base, and this has it's own requirements.  I'm afraid it seems unlikely that we'll be able to reduce requirements enough for non gaming machines.

**Comment by MohamedAhmed19** [comment]
What should i do to make it work on my device…any solution…please

**Comment by DaveTGC2** [comment]
The only solution at the moment would be to upgrade your machine. Sorry about that, but lots of software has minimum specs.

**Comment by MohamedAhmed19** [comment]
After your updates, will the engine work on my device...or is there no hope?

**Comment by DaveTGC2** [comment]
We can't promise anything, but we aren't targeting mobile cards. So, for now, I'd say no. Sorry.
