### ISSUE TITLE
Issues with Lights

### ISSUE THREAD

**Issue by hopelessdecoy** [TheGameCreators/GameGuruRepo#4129]
- Lights disappear when testing and editing the level but are viewable at different angles in both, almost like they are getting occluded but are still in view.
- After deleting lights their light remains behind in editor and test runs

![Screenshot 2023-01-28 141436](https://user-images.githubusercontent.com/9456373/215286658-80aec805-43c5-41fc-a702-a502ebcdc92c.png)

**Comment by davetgc** [comment]
How many lights are you using? There is a limit of 16 active lights at any one time. If you have more than that, MAX will choose the closest.

**Comment by hopelessdecoy** [comment]
> How many lights are you using? There is a limit of 16 active lights at any one time. If you have more than that, MAX will choose the closest.

Well in the image 0, before I deleted everything 4

**Comment by synchromesh62** [comment]
If your seeing artifacts of deleted lights then yes they should not be there
But if you save and reload the map they will be gone.

**Comment by MonkeyFrogStudio** [comment]
> How many lights are you using? There is a limit of 16 active lights at any one time. If you have more than that, MAX will choose the closest.

I believe you can have as many lights as you like, provided they don't cast shadows, and all will show, but you can only have up to 16 SHADOW casting lights. You also need to up the number in settings to 16 to get them, since the default is something lower, like 8 or 12.

**Comment by synchromesh62** [comment]
You can have as many as you like casting or not casting shadows you just have to manipulate them well :)
The vid below shows 18 lights in the first section and you will see the 2 extra cast shadows as you get close. But as you enter the new section you have another 16 casting shadows. If there are 20 lights in a room you can easily get away with only 10 casting a shadow so its all seamless from one area to the next.
https://youtu.be/Npx9JM_AIc0

However i am unable to reproduce the artifacts the OP is reporting in the latest exp build.

**Comment by MonkeyFrogStudio** [comment]
That's what I was saying (or trying to say). You can have as many non-shadow casting lights in a scene with ALL of them on at all times everywhere in the level. No real restrictions there. But when it comes to shadow casting lights, the most you can have turned on at time are 16. Only the nearest 16 will casting shadows.

**Comment by wizardofid29** [comment]
I have been able to recreate this bug with 10 lights.
https://youtu.be/zvqS7FWSvN8

**Comment by LeeBamberTGC** [comment]
@wizardofid29 The video link and the bugs zip link are invalid when I clicked to download them this evening: "Sorry, the file you have requested does not exist."

**Comment by LeeBamberTGC** [comment]
@wizardofid29 Do you know about the shadow casting light limit settings for the level:
![image](https://user-images.githubusercontent.com/35840583/229386005-988e99ca-5cac-4878-ab1c-b55b6fc01155.png)

As you can see, if I reduced the point lights allowed to 4, my eight light arrangement in the building will flicker as the engine tries to find the best 4 lights to cast shadows from.  Increasing to 8 or above solves the flicker.

Just to note, this is not a limit on TOTAL LIGHTS, just the lights that are closest to the player at the time.  It helps with performance to reduce this number but you can increase it and it will save with the level if your level needs a minimum number of lights working in close proximity.

**Comment by wizardofid29** [comment]
@LeeBamberTGC 
No it is an issue with corrupted light data.Everything was set to max. the scene had about 8 lights in total.

Again the youtube link
https://www.youtube.com/watch?v=zvqS7FWSvN8

I send the link to the files several weeks ago. @davetgc will confirm, he saw the test map and there was issue with corrupted light data in some instances.It may be due to minimizing max and working in another 3d app, restore to full screen again and minimizing. This stops the max renderer when minimized. It is entire possible if minimized for long periods could theoretically cause an issue light data.

**Comment by LeeBamberTGC** [comment]
@wizardofid29 Can you resend your links. I tried the links you sent a few weeks back and it said they did not exist any more :(

**Comment by wizardofid29** [comment]
Unfortunately I have since deleted them. It has been a few weeks. :) Will see if I can recreate the issue.
