### ISSUE TITLE
Generated particles and defined materials don´t show in stand alone build

### ISSUE THREAD

**Issue by AxelOffline** [TheGameCreators/GameGuruRepo#4131]
HI everyone,
how are you doing?

I found two issues with GameGuru Max :
a) particle effects generated with the particle editor and imported to gameguru max don´t show up in the stand alone bulid. Standard particle effects seem to translate normally.
b) materials defined for objects don´t show in the stand alone build either. The drop down field regarding freely defined materials in the editor window seems to revert to the standard material every time another object is selected
![GameGuruMax Editor File](https://user-images.githubusercontent.com/106450649/215322437-798cabcb-5030-48e0-a089-8ddf32260c55.png)
![GameGuruMax gameFile](https://user-images.githubusercontent.com/106450649/215322442-6dabcaae-84fe-409e-8813-4fac493eb052.png)
![GameGuruMax gameFile standard effect](https://user-images.githubusercontent.com/106450649/215322474-82737689-7d04-4ae2-98a3-afdec2f01658.png)

Thanks for your help and all the best to Zak.

Have a great day,
Axel

**Comment by davetgc** [comment]
Just to clarify, you're saying that user added textures aren't moving over the the standalone?

**Comment by AxelOffline** [comment]
Yes, exaclty this seems to be the case. Maybe I overlooked the approriate option in a settings menu?

**Comment by Tum1370** [comment]
HI,
I reported this in July last year.
Also, you get a load of Particles transferred to the Standalone that is not in the map.

https://github.com/TheGameCreators/GameGuruRepo/issues/3515

**Comment by ZakJudges** [comment]
Hi @AxelOffline, thank you for reporting these issues. A new EXP build has been uploaded that should fix both :)

**Comment by Tum1370** [comment]
I can confirm that this is now fixed.

**Comment by AxelOffline** [comment]
Hi Zak,

Great, thanks a million, looking forward to it and sending you the video as soon as the prototype is in sufficient shape.

Thanks again and have a great day,
Axel

Sent from Mail for Windows

**Comment by ZakJudges** [comment]
Closing this issue as confirmed fixed.

**Comment by AxelOffline** [comment]
Hi Zak,
I´m using the steam version, any guess, when the update will go online there?

Thanks and have a great day,
Axel

Sent from Mail for Windows

**Comment by ZakJudges** [comment]
Hi @AxelOffline, we expect to release a new public Steam build in the near future. If you would like to have the fix before then, you can check out our experimental Steam build. Instructions here: https://github.com/TheGameCreators/GameGuruRepo/issues/3907
