### ISSUE TITLE
Hard Crash when placing multiple objects

### ISSUE THREAD

**Issue by Indiemandeceased** [TheGameCreators/GameGuruRepo#4132]
The game engine is regularly crashing to desktop during copy paste asset placement - it will occur usually around the fourth - fifth copy paste of a similar model for instance adding in fencing and/or walls. The same type of crash was experienced when adding Normal texture to a model's material within the editor.

**Comment by davetgc** [comment]
Hi, could you please post your system specs. I frequently copy objects and I've not encountered a crash.

Also, are you using custom, or default media?

**Comment by Indiemandeceased** [comment]
Hi, as requested:

Intel Core i3 10105F @ 3.7 GHz (4.2GHz boost)
16 Gb Ram (DDR4)
MSI  GeForce 1650 4gb Nvidia Graphics Card
Samasung Evo 500gb SSD & 4tb Hard disk storage. 
Windows 11 21H2

Media in use is a mix of built in - GameGuru Classic and Unity Asset Store items.

Thanks.

**Comment by Lemuripest93** [comment]
Been reported before, #3276 #3831, i've also experienced this but since it's already been reported i haven't bothered to post about it myself, my case is similar to kravenwolf (the first linked issue in this post.)

If i copy and paste more than 12 items at a time several times it's an instant hard-crash (doesn't matter if it's custom media or what comes with the editor), keeping it under this limit works fine indefinitely.

**Comment by davetgc** [comment]
I can't replicate this, but others seem to be able to.

**Comment by Indiemandeceased** [comment]
I have also noticed the same hard crash when scrolling through assets - for instance typing rocks into the search bar will bring up all assets of that type but if I attempt to scroll through them the game engine crashes to desktop in the same manner as described above.

**Comment by davetgc** [comment]
Hi, I've noticed that, and it appears to happen when you're using media
that hasn't been correctly prepared for MAX. E..g. Classic media that has
been directly ported over rather than imported via the importer.

**Comment by ZakJudges** [comment]
Hi all, thanks for reporting this issue. As it is a duplicate, I will close this one in favor of #3276
