### ISSUE TITLE
GGMAX - Lua command request

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#4133]
Can we have if possible the the 'Sun Lighting' and 'SunIntensity' commands be exposed in LUA.
Example:
 SetSunLightingColor(r,g,b) 
 SetSunIntensity(v)

**Comment by Necrym59** [comment]
@ZakJudges
This one is another one for you when you have the time :)

**Comment by ZakJudges** [comment]
@Necrym59 Should all be available to test now :)

**Comment by Necrym59** [comment]
All working perfectly
Thankyou Zak
