### ISSUE TITLE
Idea for the Building Editor

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#4134]
https://user-images.githubusercontent.com/107326667/215477467-7f7fd916-6e51-401e-b6f8-a50b92436d28.mp4

It Would be nice if the building editor had more selective brush stroke so you could be more acute and more artistic freedom

**Comment by davetgc** [comment]
The building editor is intended to be a simple tool for creating basic building shapes, not really an artists tool.  It could be me, but I'm not really understanding the video in relation to the BE. Does anyone else have any feedback on if this would be a useful feature?
