### ISSUE TITLE
AMD Radeon Video Card

### ISSUE THREAD

**Issue by mundt1974** [TheGameCreators/GameGuruRepo#4137]
I have AMD Radeon RX 6950 XT 16 GB GPU:  
CPU: AMD Ryzen 9 3950X 16- Core
Mem:  128 GB 

If I try to edit or run a game there is no video or screen to see.

**Comment by mundt1974** [comment]
![Screenshot 2023-01-31 092327](https://user-images.githubusercontent.com/124063122/215786595-8e62f872-e81b-4bf4-a12d-041ce1f52722.gif)

**Comment by mundt1974** [comment]
![Screenshot 2023-01-31 092530](https://user-images.githubusercontent.com/124063122/215787043-3c83457c-0f5a-457e-821e-5c0e45bdb631.gif)

**Comment by mundt1974** [comment]
It does not matter if I run a demo game or create a game. There is still no screen to view the game or edit mode!

**Comment by davetgc** [comment]
Hi, have you tried the experimental build?  This issues should have been fixed for AMD users in a build a few weeks ago.

https://github.com/TheGameCreators/GameGuruRepo/discussions/3916

Hopefully this will solve your problem until the official fix goes live.

**Comment by Charli3Dubs** [comment]
it hasn't fixed my issue even rolling back and deleting my drivers nothing works. 6750xt.

**Comment by davetgc** [comment]
Ok, please check this thread to see if the advice here helps you.

#4124

**Comment by ZakJudges** [comment]
@mundt1974 following advice in #4124, is this issue now solved?

**Comment by mundt1974** [comment]
I also noticed that the memory in the top right corner of the screen is really low.  Mine only shows 6 plus GB
    On Friday, February 3, 2023 at 06:30:54 AM EST, ZakJudges ***@***.***> wrote:  
 
 


@mundt1974 following advice in #4124, is this issue now solved?

**Comment by synchromesh62** [comment]
@ZakJudges 
Check out this thread on Steam .. Many with this issue which seems it can be rectified using DXVK
Second post down .. Not sure if it will help bring anything to light.
https://steamcommunity.com/app/1247290/discussions/0/5738182472464125380/

**Comment by Charli3Dubs** [comment]
> @ZakJudges Check out this thread on Steam .. Many reporting this issue which seems it can be rectified using DXVK Second post down .. Not sure if it will help bring anything to light as to why Max is doing this for this range of cards. Lee also chimed in on this one suggesting they try the EXP but the results are the same in other threads even with the EXP build. https://steamcommunity.com/app/1247290/discussions/0/5738182472464125380/

DXVK worked like a charm for the 6750XT! Thank you! I can finally use this software! lol

**Comment by ZakJudges** [comment]
Closing this issue in favor of #4124
