### ISSUE TITLE
PBR not active after importing model.

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#414]
I've named the textures as required and importing went without problems but PBR is not active and i also cannot scroll through the maps.
When i try the experimental parallax shader it does work but looks terrible. :)

**Comment by earthling45** [comment]
It works now after setting pbroverride=0 to =1 in the setup.ini.

**Comment by HierToo** [comment]
Ok, maybe you should not deactivate pbr ;)
If you use pbroverride=0 you need to name the textures the old way _d,_n,_s and so on
You can close this here 👍
