### ISSUE TITLE
Custom asset collision shape broken, again?

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#4141]
I have been importing custom meshes in to a blanks scene for testing. Both using polygon and box you can see tha the collision mesh is laying on its side. When I import the asset the orientation had it on its back so I totated it to stand up. It looks like the collision mesh does not rotate with the mesh. 

I am importing using GLB 

![box](https://user-images.githubusercontent.com/95527550/216607612-1d7a6faf-f5d6-405f-bb34-a69035375204.png)
![polygon](https://user-images.githubusercontent.com/95527550/216607622-297bbe0a-cfbf-4dda-abab-5b132cc8c17c.png)

**Comment by ZakJudges** [comment]
Note: To reproduce - import object, rotate 270 degrees on x-axis. Set static, polygon collision. The physics of the first mesh in object is always correct. Any subsequent meshes in the object have incorrect physics shapes

**Comment by ZakJudges** [comment]
Note: also see issue #3990, same bug occurs with scaled entities

**Comment by ZakJudges** [comment]
Can also be seen in the Aztec Game Kit teaser:
![Screenshot 2023-02-24 135824](https://user-images.githubusercontent.com/32545391/221196863-379451b4-45f9-4b60-8446-12c733a090dc.png)

**Comment by plemsoft** [comment]
@42Pix3ls or @ZakJudges Could you e-mail me the object from the first post so i can test, i fixed the problem with the Aztec Temple but that was related to using .obj for collision mesh, so do not think its the same issue, e-mail: plemsoft@gmai.com , Thanks :)

**Comment by plemsoft** [comment]
@42Pix3ls Both have been fixed and will be in the next build :)

![issue4141](https://user-images.githubusercontent.com/18662417/228481559-b344832d-249a-497e-ace0-f9d274699be9.jpg)

**Comment by 42Pix3ls** [comment]
Awesome! Thank you. Sorry I have been flat out of late
