### ISSUE TITLE
Better quality textures

### ISSUE THREAD

**Issue by Ghalbeyou** [TheGameCreators/GameGuruRepo#4143]
hey, the software is awesome, but the textures are so bad. upgrade them. like 8k

**Comment by MonkeyFrogStudio** [comment]
8k? Seriously?

**Comment by Lemuripest93** [comment]
In my humble opinion, 4k are more than enough, even 2k, 8k is rarely if ever used, even in triple-A game releases.

**Comment by realPrunelle** [comment]
> hey, the software is awesome, but the textures are so bad. upgrade them. like 8k

Wich Draphic Card do you have, that you think a Gamelevel will run smooth with 8K textures everywhere?

**Comment by Ghalbeyou** [comment]
rtx 3050

**Comment by Ghalbeyou** [comment]
> In my humble opinion, 4k are more than enough, even 2k, 8k is rarely if ever used, even in triple-A game releases.
> 
> Though i guess it's up to the devs if they agree if this is a good decision or not.

yes ik. i mean if somebody wants to make aaa game with this engine, they need better textures

**Comment by Ghalbeyou** [comment]
> 8k? Seriously?

yep

**Comment by Ghalbeyou** [comment]
> Most games do not use 8k textures. Even AAA games like the current Dead Space release are going to use a variety of textures, topping off at 4k, most being 2K and even lower, depending on the texture. If textures on some MAX assets don't look good to you, making them 8k is not going to fix the issue. It's the quality of the texture/material.
> 
> Fortunately, MAX allows you to use your own models and materials. So, if you want better, make them. Or buy them.

ok, but make textures better

**Comment by Ghalbeyou** [comment]
not 8k or 4k, 1k

**Comment by MonkeyFrogStudio** [comment]
You're getting these assets in MAX for free. If you want better, then make them. Or buy them somewhere. As stated above. 

BTW - I don't work for TGC, the creators of MAX. I'm a user like you. But, come on. ;)

**Comment by Ghalbeyou** [comment]
ur right

**Comment by Ghalbeyou** [comment]
do u got discord?

**Comment by synchromesh62** [comment]
If your hoping to release your Game for VR users also then 8K textures will probably kill it.
Even the best VR titles use the lowest they can get away with in certain area's and for the more inconspicuous things.
You may not be planning VR but as it will default to a vanilla screen if a headset is not detected then its a good selling feature to have anyway :)

**Comment by Ghalbeyou** [comment]
Ok thx

**Comment by Lemuripest93** [comment]
A little tip to making a game look better is also art style, if you're creative then making your own texture a specific art style can trick you into thinking the game looks better than it does, you'll never really _need_ 8k textures for making a game - ever, unless you want photorealism, in which case this might not be the engine for you.

Also this is just my opinion, but there's more than just looks that goes into making a game good to play, start by making the game that _you_ want to play, if you think the game you've made is fun, then those higher quality textures probably aren't necessary😉
