### ISSUE TITLE
GameGuru Max - Enhancement - Building Editor - Auto Flatten Setting In Building Editor

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#4146]
It would be great if we had a setting in the building editor to set whether or not the building on default auto flattens the terrain, instead of having to ungroup the building every time for us to then uncheck auto flatten on the main structure, as leaving auto flatten on pulls the terrain through your assets if you put the building above ground.

On a personal basis this would be useful as i'm using the building editor to not just make big buildings, but i also make smaller additions to pre-made custom assets, and it would make things quicker and easier by just dragging and dropping instead of going through the ungrouping process every time :)

This functionality could be added above or below 'Auto Add Lights' under 'Room Details' or maybe have a popup with a checkbox when you try to export?

![autoflattenBuEd](https://user-images.githubusercontent.com/104637906/216783366-4e07ab38-3158-468d-a3bd-cb4658cff5ef.png)

Edit: added a screenshot from a cyberpunk game i'm working on in the engine to showcase auto flatten on/off on building editor buildings.

**Comment by davetgc** [comment]
You can turn off auto flatten via the settings.  It's under the general settings.

**Comment by synchromesh62** [comment]
Are you sure you have it set to off ?
working fine on one i just created and tried ?

![SE](https://user-images.githubusercontent.com/35708217/217642891-20d22390-7a9d-4121-97ef-098b9bc14b29.gif)

**Comment by Lemuripest93** [comment]
Strange, could this be a bug? i don't have the option with any of my building editor buildings to set auto flatten on or off, i have to manually ungroup the building then highlight the main structure and only then does the settings appear.

Whilst writing this i also just made a new building and i get the same issues as before. Could be i'm doing something wrong or i'm missing something obvious.

I'll update this later with a video to show the entire process.

**Comment by Lemuripest93** [comment]
Here you go:
https://www.youtube.com/watch?v=RmAVGbck6YA

**Comment by synchromesh62** [comment]
> Here you go: https://www.youtube.com/watch?v=RmAVGbck6YA

That looks weird and i just noticed you place it on top of a model so i tried that and it worked fine for me ?
Forgot to mention though i am using **the experimental build**
Are you on that one or tried it ?

**Comment by Lemuripest93** [comment]
> Also not sure why you are getting terrain on the floor around the outside.

Do you mean at the 1 minute mark in the video? it's just a misaligned model which is a mistake on my part so the terrain juts out of the model a bit.

Also yes i am on the experimental build, been for a few months now, i've had this issue since the Building Editor was first introduced. 🤷‍♂️
