### ISSUE TITLE
GGM - Behavior Library List Tree Issues

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4147]
If you open the Behavior Library, click purchased, and click on a sub folder within the usernames name (or if you click the users name) the Behavior Library, while it will display the contents within to the right, on the left the tree will automatically close.

**Comment by ZakJudges** [comment]
Hi @Teabone3, I have not been able to reproduce this issue. Would you be able to share a screenshot of one of your purchased folders in scriptbank, so that I can copy the directory structure and hopefully reproduce. Thanks :)
