### ISSUE TITLE
Black Zones on Entity Textures

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#415]
Ever since we started using updated GameGuru (dx11) black zones started to appear at some of the entities. Here are few that we encountered which severly damages visuals.

Middle East Building (01) - entitybank\Mega Pack 01\Buildings
Middle East Building (08) - entitybank\Mega Pack 01\Buildings

![1](https://user-images.githubusercontent.com/37545408/46534958-94253380-c8b2-11e8-91c3-d5eb4e5e23c1.jpg)

Log_Cabbin - entitybank\Classics\Wild_West

![2](https://user-images.githubusercontent.com/37545408/46534959-94bdca00-c8b2-11e8-925d-b78fab428ef0.jpg)

**Comment by LeeBamberTGC** [comment]
Thanks for the detailed link addresses to the stock assets, just what we need to reproduce, thanks!

**Comment by sfkylcnky** [comment]
Middle East Building (19) - entitybank\Mega Pack 01\Buildings
![03](https://user-images.githubusercontent.com/37545408/46735455-f90bcf80-cc9e-11e8-8d54-1cbf8c91292b.jpg)

Bread Stall - entitybank\Classics\Medieval\Props
![04](https://user-images.githubusercontent.com/37545408/46735456-f90bcf80-cc9e-11e8-9dcf-afb490c12a39.jpg)

Ruin_14 - entitybank\Mega Pack 03\Buildings
![05](https://user-images.githubusercontent.com/37545408/46735457-f90bcf80-cc9e-11e8-9f5e-1fee34c5dc4e.jpg)

Inn - entitybank\Classics\Medieval
![06](https://user-images.githubusercontent.com/37545408/46735458-f90bcf80-cc9e-11e8-8402-82f8fe0cd514.jpg)

Medieval Building 5 - entitybank\Classics\Viking
![7](https://user-images.githubusercontent.com/37545408/46735451-f8733900-cc9e-11e8-9fda-b76a8c6a1df2.jpg)

Viking Building 9 - entitybank\Classics\Viking
![8](https://user-images.githubusercontent.com/37545408/46735452-f8733900-cc9e-11e8-861d-88c0b8ea215e.jpg)

Viking Building 1 - entitybank\Classics\Viking
![9](https://user-images.githubusercontent.com/37545408/46735453-f8733900-cc9e-11e8-9828-8ee20e431848.jpg)

Medieval Building 5 - entitybank\Classics\Medieval
![10](https://user-images.githubusercontent.com/37545408/46735454-f8733900-cc9e-11e8-8df0-1e71abcc1f07.jpg)

**Comment by GameGuruEvan** [comment]
Issue Resolved - Changes will be deployed in next update.

**Comment by LeeBamberTGC** [comment]
Reported as not fixed, so going through models with latest build to confirm

**Comment by Pirate-Myke** [comment]
These look like the old style of meshes without smoothing groups assigned.
More of a model issue like mega pack 03 before the fixes.

My opinion.

**Comment by sfkylcnky** [comment]
Problem still exists. Freshly deleted and reinstalled the assests and engine with the latest April Fixes release. I don't know why can't we get support on this? Isn't this an additional asset pack that is purchased through GameGuru's store? Isn't 2 years is an adequate time to get support on the visual bugs of entities that you bought and waiting to be fixed? No need to mention that some of those are total buzzkill as they are huge in size.

**Comment by LeeBamberTGC** [comment]
@sfkylcnky Could you provide a list of assets in the format:

entitybank\folder path\entity name

This way we can collect them together and assign an artist to correct the geometry on these models, thanks!

**Comment by sfkylcnky** [comment]
entitybank\Mega Pack 01\Buildings\Middle East Building (01)
entitybank\Mega Pack 01\Buildings\Middle East Building (08)
entitybank\Mega Pack 03\Buildings\Ruin_14
entitybank\Classics\Medieval\Props\Bread Stall
entitybank\Classics\Medieval\Inn
entitybank\Classics\Medieval\Medieval Building 5
entitybank\Classics\Medieval\Medieval Building 11
entitybank\Classics\Viking\Viking Building 9
entitybank\Classics\Viking\Viking Building 1
entitybank\Classics\Wild_West\Log_Cabbin

I believe this is want you wanted Lee. I have gone over the previous list i gave at the earlier comments and corrected them.

**Comment by LeeBamberTGC** [comment]
@sfkylcnky Awesome, thanks friend!  Just what I needed.  Upgrading this to a bug to be actioned.

**Comment by plemsoft** [comment]
Checked all the objects, and they need new normals. @GraPhiX-Guru is on it , Thanks for your help :)

**Comment by GraPhiX-Guru** [comment]
![snapshot6](https://user-images.githubusercontent.com/35724756/80860926-0b73a280-8c63-11ea-8aee-ce09780aaebf.jpg)
first batch done

**Comment by GraPhiX-Guru** [comment]
All assets repaired, the bread stall needs TLC and re making i have patched it best i can.

**Comment by plemsoft** [comment]
Got all the models from @GraPhiX-Guru and e-mailed everything to @LeeBamberTGC , ready to be included in the next update , Thanks for your help @GraPhiX-Guru :)

**Comment by LeeBamberTGC** [comment]
All reported models (and texture) fixed in uploaded BETA and PP builds. Please report with new GitHub issue item if you find any more, special thanks to GraPhiX and friends for helping resolve these ancient issues in our legacy asset libraries!
