### ISSUE TITLE
weird Terrain Glitch in experiemental build

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#4152]
flashs on and off flashes 
doesnt break my game but okay

![Terrian](https://user-images.githubusercontent.com/107326667/217002497-331873b5-2aed-4f5c-8b11-ee6113ed19f0.png)

**Comment by davetgc** [comment]
This looks card or driver related, does anyone else have this issue? I did see something similar many months ago on transparent objects, but haven't been able to duplicate.

Anyone else?

**Comment by Necrym59** [comment]
Definatley a driver/card issue - i would try a different driver at least, i presume its an AMD card?

**Comment by afriendlycow** [comment]
I'm having this issue here, the URL provided.  https://medal.tv/games/requested/clips/VxFjcz3kS1Em7/d13373zfmpvh?invite=cr-MSx5a0UsMzg5MzkwNCw
