### ISSUE TITLE
My Sound scripts have stopped working and only a few are working

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#4155]
https://user-images.githubusercontent.com/107326667/217667277-12102fa0-814c-43e7-8175-b2a05bfbaad0.mp4

![image](https://user-images.githubusercontent.com/107326667/217667339-589bbd9c-b148-4042-8630-cb88ee3cc1e1.png)

![image](https://user-images.githubusercontent.com/107326667/217667392-ac337058-5e08-4d21-b313-44cc2fedd0b6.png)

ive tried to get it working with my simple 

PlaySoundIfSilent(e,0) isn't working

**Comment by RajMaha1** [comment]
![image](https://user-images.githubusercontent.com/107326667/217742658-619526cb-456b-4124-ace8-e4c070c46b31.png)
 i found calling ot from anothor worked with a gameuguru max asset

**Comment by Teabone3** [comment]
Are you trying to play a local sound or a global sound?

**Comment by Necrym59** [comment]
These are your own scripts??

**Comment by RajMaha1** [comment]
my own scripts

**Comment by davetgc** [comment]
Do all of the MAX supplied scripts work, as we can't give support for 3rd party scripting issues.
