### ISSUE TITLE
GGMAX - Lua Command Required

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#4158]
@ZakJudges 
We need a corresponding command to the 'SetExposure(v)'
to query the existing value of the current setting eg:  'GetExposure()"

**Comment by ZakJudges** [comment]
@Necrym59 New EXP build should be up in 15 mins with the fix :)

**Comment by Necrym59** [comment]
As usual it works perfectly - thankyou Zak
