### ISSUE TITLE
Audio problem: When Player Start is placed on the Story Zone

### ISSUE THREAD

**Issue by Shahin3d7** [TheGameCreators/GameGuruRepo#416]
When Player Start is placed on the Story Zone.
I want the time to start the game - at first Run the movie.
But When Player Start is placed on the Story Zone.
I noticed a Audio problem:
1- Game Test Time، Sound not be played.
2- But after the save standalone, the sound is executed - But there is a problem: the volume of audio is very low quality.
Will this problem be solved quickly?

![story zone](https://user-images.githubusercontent.com/43903231/46569246-11a67d80-c95f-11e8-9b7e-4aafbcca388d.PNG)

[TEST-Story Zone.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2452845/TEST-Story.Zone.zip)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Fixed in Recent Update ...
