### ISSUE TITLE
GG Max - Bug - AI Sounds do not work properly.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4160]
The AI Sounds have not worked since the Sound Variants options was added.

All the sounds do NOT work correctly.
I only ever hear the sounds for when the AI SEES or HEARS you.
The sounds for LOST TARGET, or KILLED target never get played now.
SUGGESTION
Sound Variants needs to be easier to setup if it actually works.
We should be able to set several different sounds per sound setting. ie Add several file names per SOUND 0 and it randomly selects one of them.

PLEASE UPDATE THIS OLD POST AS A BUG AS THIS IS BUGGED https://github.com/TheGameCreators/GameGuruRepo/issues/4026

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed lost target and kill sound playback for character attack behavior.  Another issue is extant marked as an enhancement issue of the sound variant system dynamically randomizing the sound choices 'during the game'. Right now it is coded to select the random sound before the level starts, and that character sticks with it.

**Comment by Tum1370** [comment]
@LeeBamberTGC  Thanks, With the sound variants selected ? How are we suppose to set those things up ? Is it by naming them all the same as the current ones ? Is there not an easier method for that please ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 For improvement dialogue, here is the issue I have updated to contain feature additions and discussion on how the current system currently works for comparison: https://github.com/TheGameCreators/GameGuruRepo/issues/2108

**Comment by Tum1370** [comment]
@LeeBamberTGC Thanks Lee, ill take a look at that. :)

**Comment by Tum1370** [comment]
@LeeBamberTGC I just tested this audio bug, and i can now hear the sound for when they kill the player, but i still have not heard any sound for LOST TARGET.
Also the sound variant are not working, All i hear is the same phrases everytime.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Send me the FPM level you set up to force a lost target using stock media. My quick level with me hiding behind a rock and no path to me worked fine.

**Comment by Tum1370** [comment]
@LeeBamberTGC Here is a TEST LEVEL for the AI Sounds.
2 warehouses, 1 AI (Set with about 3 second combat time so it will lose you quickly.
Start test, run around the build to get out of sight. (I usually turn on the AI Management so i can see where he is)

You do not hear the LOST YOU sound at all.

**Also, inside the zip is a TEXT file of some missing media on this new BLANK map, I Get this a lot, What is causing that ?**

[TEST LEVEL.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11233520/TEST.LEVEL.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 New EXP build up that fixes the sound issue, the character in your level now alerts when spotting the player, fixes the issue with him sometimes not shooting when right in front, and las the lot sound when the combat time expires or is generally lost the target.

**Comment by Tum1370** [comment]
@LeeBamberTGC Just tested the audio sound bug again, and can confirm its working correct.
It would be much better when you can get the sound variants to actually randomise every time they actually talk, rather than just everytime the level starts again.
Anyway, thanks again, i will close this issue now.
