### ISSUE TITLE
GG Classic - Most "Viral outbreak" characters are flattened/messed up

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#4162]
![image](https://user-images.githubusercontent.com/56294129/218240638-0f914d70-def9-4c3f-b791-fbd217adcc91.png)

As you can see here, the viral outbreak characters are all strangely flattened and contorted, with the exception of the "spiky" character. When selecting one of these characters to place into a scene, the editor screen goes black for a moment, and then the character loads in messed up, as if it's trying to convert a file and is messing up or something.

Occurs on latest "december fixes" build.

Fixes I have already tried with no success:
1. Verifying files (Said "2 files failed to validate and will be reacquired", but had no effect.)
2. Deleting the classics/characters/viral outbreak folder and validating to reacquire them
3. Fresh install of entire GameGuru installation

**Comment by realPrunelle** [comment]
Some of the Zombies have the same Bug.

**Comment by Necrym59** [comment]
[decayed1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10776477/decayed1.zip)

**Comment by fearlesswee** [comment]
Going through my old issues, closing as this seems to have been fixed in the march update for me, but if @realPrunelle is still having issues with the zombies then this should be re-opened.
