### ISSUE TITLE
Newest GGMAX update won't allow me to add new objects to map

### ISSUE THREAD

**Issue by Technodweeb** [TheGameCreators/GameGuruRepo#4173]
Since this AM's steam update I can no longer add objects to my level, or a new level in a new game map.  

Sys Specs: Alienware Aurora R10, Windows 10 64 bit, 64GB Dual Channel HyperX(TM) FURY DDR4 XMP at 3200MHz, AMD Ryzen(TM) 9 5900X (12-Core, 70MB Total Cache, Max Boost Clock of 4.8GHz) Nvidia GeForce RTX 3080 10Gb GDDR6X

The Version that the about screen says I am running is  2022.02.11 but that seems weird. I also verified the files in steam and all is well there.

**Comment by MonkeyFrogStudio** [comment]
I'm not experiencing this here. I've got the latest experimental update (from this morning) and I can add new objects to old maps, create new maps and add new objects there, too.

**Comment by Technodweeb** [comment]
Restarted everything several times, created a new map deseet default. It still will not allow me to add a new object.
I click the button but no window opens.
I can add a particle, change the landscape and other things, I just can't add an object. It was working yesterday.

**Comment by MonkeyFrogStudio** [comment]
Very interesting. Sorry you're experiencing this. I'm still not having any issues here and others on the Discord channel seem to be doing fine with the latest experimental build, too. Strange ...

**Comment by Technodweeb** [comment]
I  Figured it out... the window was stuck off screen. I have two monitors one is ultrawide and it was way off to the right of my ultrawide out of view. I change the monitor resolution and was able to drag it out.. weird.. Sorry to Alarm.
