### ISSUE TITLE
GameGuru Classic Beta not encrypting again

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4175]
Just been reported on Steam and I have tested to confirm and checked that it does not encrypt the files.
This issue is the Beta ... The Retail also tested and all good.

![decrypt](https://user-images.githubusercontent.com/35708217/219819766-67b20e53-b6ef-4aee-ae06-e89a0ea10020.png)

**Comment by LeeBamberTGC** [comment]
Lee to keep extra paranoid on this before public builds :)  Sometimes the BETA will be available unencrypted for quick experiments, but all PUBLIC releases will be full encryption mode!
