### ISSUE TITLE
GameGuru MAX - Request - No "Enable Custom Material" Tick on Right Panel

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4176]
This is something that used to not be there - the tick box for Enable Custom Material. It used to be enough to simply twirl down the Materials Tab to access and make changes to your material. Now, you have to both twirl down the Materials Tab and then also tick the Enable Custom Materials tick box. It's just an extra click that, in my opinion, is not needed.

Perhaps the idea here is to keep people from making mistakes or the somehow protect them. But that was already being done. The Materials Panel is not open by default. After selecting an object in the view port, you have to actively move the mouse cursor over to the right side panel, go to Materials, and then click it to twirl it open. This means you have to actively be attempting to access the object's materials to begin with. Now? Well, now there's an extra obstacle that gets in the way.

That Materials panel is not just for swapping out color, normal, and surface textures, but also to make adjustments to a model's emissive value, it's transparency, reflectance, and more. These things may need to be adjusted from time to time and now there's an extra (unneeded) step that just gets in the way.

Please stop putting all these "child proofing" steps between us and actually creating our games. It's like constantly having to click "YES" every time we want/need to access Advanced and Developer modes in Settings. Totally unnecessary and absolutely a PITA.

**Comment by davetgc** [comment]
I agree, this does seem an unnecessary step.

**Comment by MonkeyFrogStudio** [comment]
So, this isn't really "fixed", it's just ticked by default. I suppose that works, but why is it even there?
