### ISSUE TITLE
Save & Load game problem: When Player Start is placed on the Story Zone

### ISSUE THREAD

**Issue by Shahin3d7** [TheGameCreators/GameGuruRepo#418]
After save standalone and run game
If When Player Start is placed on the Story Zone
Save & Load I saw a problem:
1-If on your first level, the Player Start is placed on the Story Zone
2-Save the game at the first level
3-Go to the second level
4-Load the first level
In this section you will see the problem: The first level is not loaded & The second level runs with difficulty.
[Test-File.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2454189/Test-File.zip)

Link VideoBug:
https://drive.google.com/file/d/11cfwZjgPVoVD_9f4cnbBwFXKwrRa9zgN/view?usp=sharing

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 

Tested and not a bug ..
The storyzone destroys itself ( via the script ) after it has activated so you are saving the game with the storyzone already gone.. Hence not being there on reload ..
