### ISSUE TITLE
GG Max - EXP Build - Bug - Pickup Text / Usage Text stops appearing after taking damage on Armour

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4180]
After trying out Armour on my test game, I found that after i have taken damage to the armour, The text that appears for picking up stuff, like keys, health, ammo etc Does NOT appear on the screen.

**Comment by Necrym59** [comment]
I havent been able to reproduce it, but this stuff is being worked on anyway, so no point in declaring bugs on somthing thats not even implemented fully yet as most likley they will be cleaned out anyway.
