### ISSUE TITLE
Going underwater while zooming in with a firearm will keep the zoom, but the weapon will automatically be unequipped.

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#4186]
https://user-images.githubusercontent.com/112423658/220818271-6980920e-844d-4666-bd04-1d699ea0b1de.mp4

**Comment by ZakJudges** [comment]
Hi @waterdrinkingfox, thank you for reporting this issue. I have added a fix which should be in the next experimental build later today :)

**Comment by waterdrinkingfox** [comment]
Hey! The main bug has been fixed, but it seems like there's is still a "unzoom" animation even if you don't have any weapon equipped
https://user-images.githubusercontent.com/112423658/221427394-1a18e124-b193-4a1b-aea0-19d8191060f8.mp4

**Comment by ZakJudges** [comment]
Hi @waterdrinkingfox, thanks for the testing and additional bug report. I have added another fix, which should be in the next EXP build later today :)

**Comment by waterdrinkingfox** [comment]
Everything works good! Thanks for fixing :)
