### ISSUE TITLE
Zooming in on water with a scoped firearm will sometimes make the water disapear but only from the scope.

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#4187]
https://user-images.githubusercontent.com/112423658/220820792-33dbf250-4245-493c-9340-09773950e20f.mp4

**Comment by LeeBamberTGC** [comment]
@waterdrinkingfox Looks fine in latest EXP build, can you confirm:
![image](https://user-images.githubusercontent.com/35840583/230485554-473b83c5-8954-415d-8d4b-718c61827a34.png)

**Comment by waterdrinkingfox** [comment]
GGMax isn't working for me as of right now, I'll test this when it works back again.
