### ISSUE TITLE
Editor Profiler has incorrect values when hovering over an object in the Object Library

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#4190]
- Check the "Enable the 3D Editor Profiler" setting
- Open the Object Library
- Hover the mouse over an object so that it loads the preview
![Screenshot 2023-02-24 100711](https://user-images.githubusercontent.com/32545391/221151479-f659b2fb-bc08-4f6f-bccb-be2108c59830.png)

**Comment by LeeBamberTGC** [comment]
Seems to work now in latest build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ee235bee-c8b2-4f81-ba1e-5593648d40bf)
