### ISSUE TITLE
Standalone: missing mouse cursor

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#4191]
After creating a standalone, the mouse cursor is not displayed above any backdrops. 
![Screenshot 2023-02-24 145632](https://user-images.githubusercontent.com/32545391/221210500-a8987326-dfb0-4339-9bbd-158cb4bb2d6b.png)

It is also displayed under the buttons in the pause menu:
![Screenshot 2023-02-24 145747](https://user-images.githubusercontent.com/32545391/221210748-5587a634-d206-4a93-99a1-4cbb2a9b45e4.png)

**Comment by plemsoft** [comment]
Tested and its fixed :)
