### ISSUE TITLE
Weapons transparent looking at the sun.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4192]
As the heading states .. Weapons transparent looking at the sun either Simulated or Skybox.
Apparently been an issue for a while but cannot see its reported here.

![TG](https://user-images.githubusercontent.com/35708217/221237109-62e6bddb-fb17-45e7-9be4-6b435d3bc635.png)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Had to make a compromise here. Until we get a new weapon-smith artist to separate the transparent parts of the weapon model, I have updated the graphics engine to add the necessary prepass depth for the solid parts of the weapon but not draw the semi-transparent parts. Performance is not affected, and the functionality of all guns is fine. We are planning to improve the projectile weapon system to separate the hands, so we can throw this work into that.  Bug is fixed for this issue int he next EXP build.

**Comment by synchromesh62** [comment]
Looks great to me.
Huge improvement in fact its difficult to see any problem now.
I will close this one down as sorted :)
