### ISSUE TITLE
Smart object creation broken.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4193]
It now seems very difficult to use/create smart objects.

The thumbnail tool/window doesn't appear when clicking save.  (after entering save name), so it appears no 

Sometimes dragging a grouped object from the group library doesn't bring over all of the grouped objects.

A number of artists are also reporting extreme difficulties when attempting to link objects.

See also #3030

**Comment by wizardofid29** [comment]
Smart objects are broken, well when you save them, when you use a grouped object within the current level no issues, some times there is issues when you rotate a grouped entity. When you save it however, it may randomly select an entity in the group to save out

**Comment by MonkeyFrogStudio** [comment]
Here are a few more reports on groups/smart objects:

https://github.com/TheGameCreators/GameGuruRepo/issues/3880

https://github.com/TheGameCreators/GameGuruRepo/issues/3153

Also, the thumbnail generated when you create a group/smart object is often so bad that it's hard to tell what the actual group is.

**Comment by LeeBamberTGC** [comment]
@davetgc Latest EXP build uploading soon should have fixed this:
![image](https://user-images.githubusercontent.com/35840583/229365963-adc5025c-8472-4ac4-b73d-93de4ec9451f.png)
