### ISSUE TITLE
GameGuru MAX - Bug - Object Library Shows Double Objects on Import

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4197]
Currently, when you import objects into MAX, the Object Library will show two copies of it. Sometimes there's only one thumb with the other being grey. Sometimes both will have thumbs. And sometimes it's not just the newly imported object that's doubled, but other objects in the same folder. 

Restarting MAX resolves the issue ... until you import another model.

**Comment by MonkeyFrogStudio** [comment]
Now, for some reason, MAX is showing TRIPLE images for everything in the Object Library after importing a new object.

**Comment by MonkeyFrogStudio** [comment]
This is what I'm talking about:
![duplicate](https://user-images.githubusercontent.com/36735507/223533003-25f61c2a-1c87-4be6-9e09-ebe682428d7f.png)

Notice how there's two of everything? This only occurs in the folder to which you import a new object. Restarting MAX resolves it ... until the next time you import a new object.

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, I haven't been able to reproduce this. Does it happen with any model that you import, or only certain ones? Also, do you know the path to your writable folder? (the default is documents->GameGuruApps->GameGuruMax). Thanks!

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Interestingly enough, this doesn't appear to be happening any longer ... at least with a new test level. I tried using several different paths. In any case, here's the gamegurumax.pref file you asked for:

[gamegurumax.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11003701/gamegurumax.zip)

**Comment by ZakJudges** [comment]
@MonkeyFrogStudio @Pasquill3d Out of curiosity, when experiencing this issue, do you have a VR headset connected?

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Nope. I don't own a VR headset ... yet. ;)

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges I am not at the import stage in the next DLC, but should be soon. So, if I keep experiencing the issue, I can report it and let you know.

**Comment by plemsoft** [comment]
@MonkeyFrogStudio @Pasquill3d Just tried this and was not able to reproduce it, we did make some changes to the reload of media and the media scanner the last week perhaps this also fixed this issue, could you try it in the latest version and let me know if its also fixed for you , Thanks for the help :)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft I've not been getting this recently, though I've not been doing a ton of importing at the moment. I will keep an eye out, though. Closing this. If it crops up again, I will start a new thread on it.
