### ISSUE TITLE
GGMAX - Emissive Bug - Changing the emissive value in-editor on an object then selecting a different object undoes the emissive change

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4198]
If you adjust the emissive value for an object that is using an emissive map, then select a different object in your level, the emissive value for the first object will return to it's default value, and will appear that way in test game. Clicking on that emissive object again will cause it to return to the new emissive value you assigned to it, and show it that way in test game as long as it was the last object you selected.

This is made more apparent when dramatically increasing the emissiveness value of an object.

See video. 
https://user-images.githubusercontent.com/103399301/221412442-eafc4b7b-63e2-4945-b54a-41c6768bb24e.mp4

I adjusted the emissiveness of the right object from it's default value or ~2 to ~13. However, unless it was the last object I selected before jumping into test game, it will show in-game with it's default emissive value of 2. Selecting it again in the editor shows it's slider value is still set to the increase I assigned to it. This creates more problems when you have more than 1 emissive object that you've changed the value for, since you cannot select more than one to resolve the error (multi-select will not work).

**Comment by MonkeyFrogStudio** [comment]
I can confirm this as it's happening on my end as well.

**Comment by ZakJudges** [comment]
Hi @Kravenwolf, thank you for reporting this issue. I have added a fix which should hopefully sort it. For any saved levels, you may need to delete the affected object and then re-add it. The fix should be available in the next experimental build :)

**Comment by Kravenwolf** [comment]
@ZakJudges, I don't use the experimental builds, but if you let me know when all of these fixes are added to the official builds, I'll be more than happy to confirm them and report back :) Just wanted to let you know I'm not ignoring you!
