### ISSUE TITLE
Lightmapping does not work

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#42]
Since the dx11 update the lightmapping does not work or is completely messed / OR almost not noticable.
This should be adressed sooner or later. Would be nice :)

**Comment by LeeBamberTGC** [comment]
Life, The Universe, And Everything BUG ;)

**Comment by Duchenkuke** [comment]
Lightmaps DO work when done in an empty map.. 
SO I guess you can close this one..

**Comment by LeeBamberTGC** [comment]
Slight improvement with next beta build as at 13th March so it now lightmaps all static entities given to it (but does not use PBR for lightmapped surfaces to retain backward compatibility)
