### ISSUE TITLE
GGMax Bug: After a certain distance, the head of a character disapears

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#4200]
https://user-images.githubusercontent.com/112423658/221430688-0d16702c-de9d-4eb5-8c1b-5c2d4bd19e47.mp4

Seems like the head reappears when the character dies...

**Comment by davetgc** [comment]
Thanks for the report, this has already been reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/4088
