### ISSUE TITLE
GameGuru MAX - Bug - Double Sided Texture Issue

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4201]
If you have a model that is only a single plane and set the material to Double Sided, then selection outline does not show when the object is selected in the view port. If you untick Double Sided, then you can see the selection outline again. This only seems to affect single plane objects.

**Comment by MonkeyFrogStudio** [comment]
Here's an example of an object in MAX with Double-Sided ticked and the object selected:

![double_sided](https://user-images.githubusercontent.com/36735507/221982850-2c6b2452-b2f2-4886-a275-3018435accd2.png)

Notice there is no selection outline on the object. If I were to untick double-sided, then the selection outline would appear again.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio May have been fixed a while ago, yellow outline shows on single sided decal with DS on and off:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ba38bd8f-e87a-43a7-96ee-836a5b5f3d95)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/7673d2ca-5adf-4e69-b49c-f06b4bb3f23c)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC I don't see it fixed here with the latest exp. build. Here's an example:

![ds1](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/68bd84b9-6886-4c05-a22a-3533134fed38)

If double-sided is ticked off, the yellow outline is shown on the puddle. With it on, it disappears.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Been working with another related bug about highlighting methods, and it seems you need TRANSPARENCY OFF to reproduce my fix. When TRANSPARENCY AND DOUBLE SIDED run together, the highlight disappears as there is nothing for the stencil buffer to get ahold of.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC I can confirm that the fix works with transparency off. Is there a method that can possibly be employed for when transparency is on? Just curious.

**Comment by GraPhiX-Guru** [comment]
The tricky part with transparency is that you often want to blend the transparent object with what's behind it. With the stencil buffer, you're typically dealing with binary conditions (draw or don't draw). 
To try and handle transparency you could try to sort your transparent objects back to front to render them in the correct order.
You can possibly use the depth buffer in conjunction with the stencil buffer to ensure correct depth testing.
In some cases, you might need to render the scene in multiple passes, especially if you're dealing with multiple layers of transparency.

But i am no professional coder LOL just my logical thinking.
