### ISSUE TITLE
Locking a BE object and then unlocking it only unlocks the main walls, not doors and stairs.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4203]
If you lock a building created in the building editor everything, including lights placed inside are locked. If you then unlock it, only the floors walls and ceilings unlock, all the other objects remain locked.

**Comment by LeeBamberTGC** [comment]
@davetgc Looks fine in the latest RC build uploading now, can lock and unlock the smart object, nothing is affected. Only when you break the smart object by ungrouping them that you are now dealing with individual objects.
