### ISSUE TITLE
GameGuru MAX - Bug - Render Bias Issue

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4204]
I've got a cluster of papers:

![papers](https://user-images.githubusercontent.com/36735507/222566342-72cfc4ed-36a3-4f29-8b53-a25e86070c9a.png)

It's one model, but two materials, and there are some overlapping polygons with a little space between them. But because they are papers, they are very thin (single poly thin) and are very close to each other when they overlap. Because of this, sometimes the papers under show through the top as a result of z-buffer issues. To correct this, I set the render bias to compensate and it works well. However, after saving the level, exiting MAX, and starting again, it's like MAX has forgotten the render bias settings for the model (even though it's in the FPE, too). I have to actually select the model, go to the material tab, go to render bias, and even though the correct numbers are in there for each material, I have to move the sliders (to some other number and then back to where they were again). Once I do this, both the editor and test game will show the model and render bias properly. But if I exit and restart, it forgets them completely (even though, again, they are shown correctly in the materials tab under render bias).

Sometimes render bias is also forgotten when exiting a test game and going back to the editor. When this happens, you can see the flickering of the textures in conflict as you move about the view port. And if you go back into test game, the issue persists there. The only way to fix it is to, once again, access the material tab, go to render bias, and reset the numbers there (for each material), making sure to put them back where they were.

_(And, yes, I know I could have made this one big plane with a single texture on it ... and I may go that route ... but I still wanted to report this issue ;) )_

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Render bias setting save fixed a while ago, but confirmed as fixed now. Also added extra into to the property so it reads: "Set the transparency render order distance bias to prioritise rendering of overlapping objects. They must be transparent and double sided". Bias cannot defeat z-clash but it can draw objects in a specific order when they are the same distance away from the camera.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ab61e068-ea5d-4100-82fc-0b081a1d5043)
