### ISSUE TITLE
GGM - GRAPHICAL BUG - Auto Exposure can't be turned off. Oof! (UPDATE: May actually be an issue with PBR)

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4214]
So apparently, there's no way to disable Auto Exposure. :/

I unticked the Auto Exposure box so my indoor map would stop having it's brightness randomly changed up and down and up and down and up and down while walking along a long corridor, but even with it "disabled" (allegedly), unticked and unchecked under the post processing tab, Auto Exposure is still ruining my day.

It randomly increases and decreases the ambient lighting in my interior map when I'm just walking along, weather it's on or "off"(allegedly). It looks terrible and unrealistic, it feels terrible, it makes me feel terrible, and my day, my week and my month is now ruined.

Now for your viewing pleasure, please enjoy this video of Auto Exposure doing it's thing, even though it's turned "off" (allegedly):
[https://www.youtube.com/watch?v=fgMRIECFmuM](url)

Please fix.

**Comment by fearlesswee** [comment]
I don't think that's auto-exposure, it seems to be the same exact lighting bug I had thought that only I was somehow getting!

#3565

**Comment by fearlesswee** [comment]
Just as a quick double-check, try setting the ambient of your level to be very dark, and change the color of the light to something more obvious, like red or green. If this is indeed the same bug that I've been suffering from for months now as it appears to be, then you should see the world is lighting up with the color of the pointlight due to some oversight with the dynamic environment probe following the player around.

**Comment by Kravenwolf** [comment]
@fearlesswee, I played around with it for a bit using your suggestion and it looks like it may be some sort of an issue with PBR, and the materials not being updated in real-time?

**New video:**
https://youtu.be/2axvJL4pPhA

To test, I added some "mirrors" that have PBR materials assigned to them to the ends of the halls to make the changes more apparent. If you look at their reflections in the video, it takes a moment for them to update to the surrounding area as the player's camera moves toward or away from them very rapidly. 

The same thing is happening with the wall that is also using PBR mats, it's just much less apparent but both surfaces are using PBR. They continue to glow red for a second or two after I quickly zoom the camera towards it and out from underneath the red light I was standing under on the opposite end of the hall.

It may be helpful to run a similar test using objects that don't have PBR materials on them, and see if they also change colors the same way, but I've spent enough time on this issue for one night.

I'm not a programmer, so will need someone who actually has a clue what they're talking about to chime in (and hopefully fix my mirrors! #4216)

**Comment by Kravenwolf** [comment]
**UPDATE:** 
Ticking "Planar Reflections" on affected objects seems to make the issue go away on my end, but they look expensive.

**Video Here:**
https://youtu.be/Iy3tfGxop8E

**Comment by fearlesswee** [comment]
That would be the environment probe which follows the player/camera around, which is in charge of non-planar reflections and evidently pointlight influence. So this definitely seems to be the same bug I've been getting, and the solution would be some tweak/fixes to the player environment probe itself as I had concluded.

**Comment by MonkeyFrogStudio** [comment]
Yep, definitely not auto exposure, but the light probe. It will do the same thing with reflective surfaces, too. I've complained about this previously.

**Comment by Kravenwolf** [comment]
Major wrench in the pipework for creating stunning, quality visuals in interior spaces under particular lighting conditions. Very much needs to be addressed.

**Comment by fearlesswee** [comment]
> Major wrench thrown into the pipeline for creating stunning, quality visuals in interior spaces under particular lighting conditions. Very much needs to be addressed.

TELL ME ABOUT IT! My project is all about a dark, moody setting with limited light sources to create a tense horror atmosphere. But when you stand within a pointlight's glow and get free night vision, it ruins the entire thing. It also literally causes nausea with the constantly light warping/shifting as you walk down a hallway pass multiple lights, especially of varying colors.
