### ISSUE TITLE
GG Max - EXP Build - Bug - Messed up cursor on Standalone Test all Levels

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4218]
Just noticed that the cursor messes up when testing game from the Storyboard.

Step by Step.
1. Tick Standalone Test all levels, Then hit Normal Standalone.
2. Check out ABOUT, and notice that the cursor is not visible,
3. Go back to main screen, and hit START.
4. When game starts you will notice that the cursor is on screen now in the game.

I tried this on a different game and same thing happened, except when in game i had 2 cursors in game.

![0](https://user-images.githubusercontent.com/66874403/222967040-d8f0e16b-0dd1-4d36-ab79-ffac7adc4940.png)
![1](https://user-images.githubusercontent.com/66874403/222967043-1c94886b-3c22-4daf-9c69-d558d4e8bc0e.png)
![2](https://user-images.githubusercontent.com/66874403/222967048-8ecbdccc-9465-4ed0-9ac5-d46b3018708e.png)
![3](https://user-images.githubusercontent.com/66874403/222967051-55551ef8-8ee4-493f-9733-86f31aecf966.png)

![10](https://user-images.githubusercontent.com/66874403/222967344-5a346bd0-c5ce-413a-af5e-98296d189b1d.png)

**Comment by ZakJudges** [comment]
Hi @Tum1370, thank you for reporting this issue. I have added a fix which you should see in the next experimental build :)

**Comment by Tum1370** [comment]
@ZakJudges  Just retested this bug and can confirm it has been fixed, Thanks for the fix Zak.
Ill close this issue now.
