### ISSUE TITLE
Weapon class segregation by keyboard number

### ISSUE THREAD

**Issue by Lentheman7** [TheGameCreators/GameGuruRepo#422]
I thought it would be nice to have a built in system for weapon class segregation [EAI's term] that would allow certain weapons to be assigned to a specific keyboard number such as the **pistol or the magnum** could be weapon number **1**, a **shotgun or rifle** could be weapon **2**, and a **machine gun or melee** weapon could be number **3** etc. 

I have noticed that whatever weapon you pick up first is automatically relegated to being assigned to number 1 on the keyboard, and each weapon after that goes to the next higher number. It might be nice to have weapons assigned to a specific number no matter what order they are picked up. This might help keep the guns in a specific order like many modern games do. It might also help the player to keep everything straight in their own mind with less powerful guns in the low number, and more powerful guns in the higher numbers... or the weapons can be assigned by the game designer.

**Comment by ErrantAI** [comment]
If implemented, there should be no hardcoded classes/slots.  Such feature should only apply if specified in a weapon's gunspec to allow for maximum flexibility.  Something like weaponslot=x (1-9 value)

**Comment by mav3r1ck1981** [comment]
@Kasseyus this has been implemented to the core now
