### ISSUE TITLE
Scripting animation Issue - GG MAX

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4220]
in ould version i imported model with animation and used logic box to make an character.
when im importing model with animation now, my animations for the models are replaced for preset animations.
so I cant do nothing with the character.
![GameGuru MAX -  05 03 2023 19_47_22 (2)](https://user-images.githubusercontent.com/109030026/222980003-89f9a6f8-f289-402b-8710-fb78b7acd091.png)
![GameGuru MAX - m4a fpm_ 05 03 2023 19_45_21 (2)](https://user-images.githubusercontent.com/109030026/222980005-4ad36244-4f45-4fb0-a440-f9c1ee4f9895.png)

**Comment by davetgc** [comment]
I'm guessing the character is custom. Which script are you using?

Are you able to supply the character for testing?

**Comment by Keepo1** [comment]
the model on 2.pic has 4 animation i gave to it with own names specific fot this model i made, but behaivor in editor they don't show up, insteat ot them they are defaultanimations from ggmax animation list.

**Comment by davetgc** [comment]
This sounds like an issue with the custom model, and there are some fairly strict rules on custom characters.

There is a script called Npc Control which is designed for custom characters. See if that helps.

**Comment by Keepo1** [comment]
Yes i worket with it in past and it worked just fine, but it´s not working now forl cca last 5 versions. 
But i will try to rewrite it manualy and see if it works...
