### ISSUE TITLE
GameGuru MAX - "Line" to Ground Seen When Moving Object?

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4221]
I don't recall this being seen in the editor previously, though I suppose I might have missed it - but now I can see a line that goes from the bottom of an object to the ground (or object beneath it) whenever I am moving an object (it's not visible when I release the mouse cursor to stop moving the object):

![line](https://user-images.githubusercontent.com/36735507/223202895-05340c7c-1e24-4a34-9d31-2c23f671bf3a.png)

I think this is the "probe" that looks for object beneath what's selected to snap objects to each other, but that's just a guess. I am assuming that it's supposed to be invisible to the end-user, but is visible now.

**Comment by MonkeyFrogStudio** [comment]
Here's another shot of the line showing up:

![line2](https://user-images.githubusercontent.com/36735507/223222634-1e3c5ef7-fc31-4615-89e1-ab3ee780ad11.png)

**Comment by davetgc** [comment]
I'm marking this as a question, as I've no idea if this is a deliberate change.

**Comment by MonkeyFrogStudio** [comment]
@davetgc Personally? It doesn't look like a deliberate change because the line, in most cases, is barely visible. If it's meant to be seen, then it really needs to be seen (if you get what I mean). I mean, in that first image, the line is so thin I almost didn't notice it at first. ;)

**Comment by synchromesh62** [comment]
> @davetgc Personally? It doesn't look like a deliberate change because the line, in most cases, is barely visible. If it's meant to be seen, then it really needs to be seen (if you get what I mean). I mean, in that first image, the line is so thin I almost didn't notice it at first. ;)

The line is only in smart mode .. 
If I remember correctly its deliberate for placement alignment.
