### ISSUE TITLE
GameGuru MAX - Bug - CTRL+Click No Longer Multiselects

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4222]
As the title says, using holding down CTRL and clicking no longer multiselects objects with the latest experimental build.

**Comment by MonkeyFrogStudio** [comment]
Here's a video:

https://user-images.githubusercontent.com/36735507/224058812-b7a03cbf-a1f1-4fe2-9f11-f73dd5995ea5.mp4

I've pressed and held CTRL throughout and cannot get more than one object selected.

**Comment by MonkeyFrogStudio** [comment]
@davetgc I just did a test in a brand new level with only three objects in it. There, I can easily multi-select using CTRL+click. But in the video above, you can see that I can't. So, I wonder if it has to do with the shear number of objects in the above level vs. the test level with few objects?

**Comment by davetgc** [comment]
Yes, I could see the issue in the video. I still can't reproduce it. It
could be to do with the number of objects.

**Comment by ZakJudges** [comment]
@davetgc there is no limit that would prevent multi-selecting objects, that I know of.

@MonkeyFrogStudio Are you still unable to multi-select in the level shown above, after relaunching Max?

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Yes, I am still unable to multi-select using CTRL+Click on the above level. It's been this way with that level for quite some time (i.e. several relaunches and even system restarts).

**Comment by ZakJudges** [comment]
@MonkeyFrogStudio Just a couple more questions to try and narrow this down:
- Are you able to select the object by holding shift+dragging the mouse?
- Could this be asset specific? I.e. If you place some stock objects down, does the issue persist?

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges 

If I drag out a selection box, I can multi-select within the selection box. If I use SHIFT+drag afterward to add more to the selection, then no, only the objects in the new selection box are selected.

It is definitely not asset specific. If I add in any standard objects that ship with MAX, the same thing happens in this particular level.

**Comment by ZakJudges** [comment]
@MonkeyFrogStudio There is nothing in the code that immediately jumps out to me as the cause, so I will likely need your map to reproduce the issue. Would you be able to email it to me, whenever you get a chance? :)

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges It's a demo level for a DLC and quite large (all the unique objects are 1.2GB). But Dave has the level. I've asked him to test and the multi-select issue is not happening on his end, either. Only for me.

Now, as I had stated previously, I can multi-select in a new level, regardless of the objects used, just not in this one particular one.
