### ISSUE TITLE
Custom Enhanced Weapons Hud won't show in latest version GG Classic

### ISSUE THREAD

**Issue by maiacoimbra** [TheGameCreators/GameGuruRepo#4226]
hello folks i want to report a bug that i find in the lastest realese of GG Classic 
My custom weapons hud apper empty , and  i think the problem resides here , i am using more than one texture and the engine update can read all of them, because in the older versions GG can read it.
i check the image links and they are not in any folder so, they are relative links , should work 
in FPE file is also correct 
and in " gunspec.txt " i just leave the gun_color field empty for the engine could load every texture and just wont work at all in the latest version 

but in March 2021 Version works normally

![BGR_01](https://user-images.githubusercontent.com/41338802/224022546-6147b92e-ec8b-482e-880c-84b102fc4af9.jpg)
![BGR_02](https://user-images.githubusercontent.com/41338802/224022553-22464fa0-4504-4d03-8630-9a937bfd157d.jpg)
![BGR_03](https://user-images.githubusercontent.com/41338802/224022558-e4195491-d6f7-43ae-83b1-3eb6c57b9758.jpg)

**Comment by LeeBamberTGC** [comment]
@maiacoimbra We had a dodgy DBO converter in a few of the previous updates, corrected in the latest builds. I am uploading a new BETA build soon, can you check against this after doing the following:

1. Locate your gamecore and the guns folder in there and remove any DBO files you find there. These are most likely corrupted. The latest version will replace those DBO from the original X files and you should see correct weapons again.
