### ISSUE TITLE
Popup Annoyances

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#4227]
I have called this a bug - because they are **never helpful**, but **always annoying**

Can we please have an option to disable it on side panels and the library. I promise the images are already big enough without popups

These kind of UI "enhancements" just get in the way of finding what you are looking for
![image](https://user-images.githubusercontent.com/12246318/224300963-f55a11df-a621-4db6-b42b-661fbfd61c5f.png)

**Comment by davetgc** [comment]
What do others think? Is the annoying and are the images large enough?

**Comment by MonkeyFrogStudio** [comment]
It is very annoying. I was going to report something like this myself, actually.

**Comment by MonkeyFrogStudio** [comment]
I would recommend either a way to shut off this "feature" via Settings or have an area in each thumbnail that the end-user could click to access a larger view, if they needed one. Sort of like how we have an area we can click in the object library to generate a new thumbnail.

**Comment by OldFlak** [comment]
We have been asking for an option to turn them off on side panels as well, along with tooltips, since they were added
- a simple checkbox to turn it off for the whole UI would be great 

The fact that they don't provide any further info than already shown exacerbates the whole experience

I would imagine it would be the most commonly ticked option in MAX setting panel

**Settings:**
Checkbox: Turn Off Popups and Tooltips
Time delay: Adjust the time before popups appear when enabled

Substance Painter has the same thing - very annoying - in fact it is the only thing I dislike about it

Make MAX Great!
:) :)

**Comment by synchromesh62** [comment]
A setting to turn off would be good as agreed they can be annoying.
However not sure how tiny the small pics get on some of these crazy resolutions some use so removing completely may not be such a good idea ?
