### ISSUE TITLE
GameGuru MAX - Bug - HUD Not Right on Ultrawide Display

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4230]
I have an ultrawide display with a resolution of 3440 x 1440. Currently, the health HUD is not displaying correctly:

![hud](https://user-images.githubusercontent.com/36735507/224505359-09d82506-950b-4841-87af-3fd7f8259d2e.png)

If I switch to 1920 x 1080, then the HUD looks correct.

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, would you be able to check if the HUD is also displayed wrong in the In-game HUD screen? I recall fixing a similar issue in the past, it's possible that I missed something

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Yep. It was wrong in the Storyboard Editor. Not sure why, because I've not even played with HUDs ... yet. But this is not a bug, so I'll close it. Thanks! :)
