### ISSUE TITLE
GameGuru MAX - Bug - Change Texture Emissive Not Showing Unless Custom Material Enabled

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4231]
There's an issue with the current experimental build and the Change Texture Behavior when it comes to using emissive textures. I'll try to show the issue. 

Here's a test game with a sign on a building:
![e1](https://user-images.githubusercontent.com/36735507/224509883-e67ce12d-fa82-486b-852d-5b9b227d3d31.png)

The sign should be lit up via the emissive texture it uses via the Change Texture behavior (this is an animated sign) but, as you can see, it's not. Going back to the editor, the Enable Custom Materials for the object is unticked:

![e2](https://user-images.githubusercontent.com/36735507/224509944-67cac8f9-2105-4173-a235-6cd060f49328.png)

If I tick it:

![e3](https://user-images.githubusercontent.com/36735507/224509948-fb08faa5-9a0d-4757-8836-5df819a4015d.png)

Then suddenly the sign comes to life:

![e4](https://user-images.githubusercontent.com/36735507/224509957-f38e42c7-3d46-4f5f-a9fa-74ac75e98811.png)

Ticking Enable Custom Material should have nothing to do with the Change Texture Behavior and it didn't in the past. After this last update, I've had to go through every single object using the Change Texture Behavior and tick the Enable Custom Material box for each object where I didn't need to do that previously.

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, thank you for reporting this issue. I have added a fix which should be available in the next experimental build. The fix should also sort #4176 for you at the same time
