### ISSUE TITLE
GameGuru MAX - Bug - Sharp holes on the second map 

### ISSUE THREAD

**Issue by Mishahhi** [TheGameCreators/GameGuruRepo#4232]
After creating the second map, observed holes down or holes up (backwards) in the game itself. Initially, I thought it had something to do with compiling build, which showed up to 4000% and then abruptly became 100%. Turned out it wasn't. If there is a way to fix this bug, happy to help. At the moment there is a video and screenshots of a similar bug. 

Please note that these holes are not shown at all in the editor. Only after compiling the project. 

STR: 
1. Create the first map (with transition to the second map)
2. Create second map (connect visual points to transition)
3. Compile project 
4. Run the ready project 
5. Move to the second level 

![Screenshot_1](https://user-images.githubusercontent.com/20231122/224531563-16b3f8df-0407-4f9d-85e4-f5fa481e6cf7.png)
![Screenshot_2](https://user-images.githubusercontent.com/20231122/224531571-9a9167ed-4369-4d87-b960-b651c3b93c9a.png)
https://youtu.be/IuvSUTxmdm4
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/10950264/Guru-MapEditor.log)

**Comment by davetgc** [comment]
By compile, do you mean to create a standalone?

**Comment by Mishahhi** [comment]
yes
