### ISSUE TITLE
cant hide the hud

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4233]
with the titanic game, I really dont want a HUD, and its not letting me switch it off in the settings nor does the hide hud script work at all. :(

![image](https://user-images.githubusercontent.com/68471279/224570865-41205667-76fe-45cf-88da-7c709739005c.png)

**Comment by ZakJudges** [comment]
Hi @casigus, if you would prefer to not have any HUDs in your game, you should be able to load up the in-game HUD screen, and then delete everything on it, leaving you with a blank screen, like so:
![Screenshot 2023-03-17 092344](https://user-images.githubusercontent.com/32545391/225864968-5f317154-d140-4a98-8d5f-6eca791e3126.png)

Re the Hide Hud screen not working, was it attached to a trigger zone? Or something else? Thanks :)

**Comment by casigus** [comment]
THAT did it! :D
