### ISSUE TITLE
GG Max - Bug Changing HUD

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4235]
Hi,

After testing changing the HUD a lot, and using COPY and PASTE of Colour numbers to get the same colour for some parts of my HUD, I Have noticed that if i dont save and reset Max often, The HUD will just start to mess up as you can see in the screenshots below.
Even though the HUDs are created correctly, In game they mess up.

Like i said, If i only create each part of the HUD seperately, Close Max, Open Max, and then create the next section, and keep repeating this process, The HUDS work correcly.

But i should NOT have to keep saving projecting, shutting Max down, Opening Max and creating next bit just to create a HUD.

**Comment by Tum1370** [comment]
Here is the new project HUD screen, and in game screen. I named this project the same as the old project. But i did totally delete the old project folder.

HUD Screen
![1](https://user-images.githubusercontent.com/66874403/224692051-c7c425b1-4880-4581-95cc-54c5b5ceff7e.png)

in Game . See how the Green Armour image, and the Red Heart image are missing in game.

![2](https://user-images.githubusercontent.com/66874403/224692187-d44bc18c-dede-4752-862c-78373d47a93c.png)

**Comment by ZakJudges** [comment]
Hi @Tum1370, thank you for reporting this issue. I have added a fix which should hopefully be available in the next experimental build on Steam :)

**Comment by Tum1370** [comment]
@ZakJudges I am going to close this issue for now. I have not had any issues lately changing the HUD around so hopefully your fix has sorted it. Thanks Zak
