### ISSUE TITLE
GG Max - EXP Build - Bug - Gameguru shuts down when you create a new Project

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4236]
When you click create new project, after entering the Project name, Gameguru shuts down.
It does create the project though after you load back in.

**Comment by davetgc** [comment]
It's the same for me.

**Comment by ZakJudges** [comment]
Hi @Tum1370, thank you for reporting this issue. I have added a fix which should sort this issue for you. The fix should be available in the next EXP build

**Comment by Tum1370** [comment]
@ZakJudges Thanks for the fix Zak.
I can confirm that this bug is now fixed. Ill close this issue now.
