### ISSUE TITLE
3rd person and fantasy DLC map broken ( Reported on Steam )

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4239]
3rd person and fantasy DLC map broken ( Reported on Steam )
Have to agree after testing the Fantasy DLC demo is running pretty abysmal right now and although 3rd Person is only basic all the speeds are incorrect and have been a little neglected with all the other work going on.
Definitely could do with a little TLC just to make what is there usable.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed for NEXT BETA build, turns out the weapon speed mod of the staff was slowing down our wizard :)
