### ISSUE TITLE
Mega Pack 03

### ISSUE THREAD

**Issue by HellReaperX** [TheGameCreators/GameGuruRepo#424]
![mega pack 03](https://user-images.githubusercontent.com/44069729/46837094-e3fb7300-cd68-11e8-9a13-d0e398e2a491.jpg)

Experiencing issues with Ruin 2, Ruin 2_b and Ruin 11 being pure black

Building #15 if you get close enough to the railings outline you can see right through em and noticed this with other buildings in this pack with posters on the wall as the outline is see through as well. highly noticeable even during night time scenes or use of fog. 

happens in PP and in 2018.07.30 build

**Comment by Emperor2000** [comment]
I have the same problem

**Comment by HellReaperX** [comment]
Im noticing anything with transparency is effected by this bug, example the Ivy and vines from the Fantasy Pack. It would be cool if you got the permission to work on it GraPhiX-Guru.
