### ISSUE TITLE
Standalone terrain error?

### ISSUE THREAD

**Issue by Dr-Colosso** [TheGameCreators/GameGuruRepo#4240]
My standalone level has odd pits forming in the terrain. The level tests fine in the editor, but this pits appear in the standalone game. 

![pit](https://user-images.githubusercontent.com/113945750/225332186-04d72deb-b347-4ef7-8d40-46ea8f62f037.jpg)

**Comment by Dr-Colosso** [comment]
![example](https://user-images.githubusercontent.com/113945750/225434078-9d15eba0-3e41-4038-a2fe-93abf65f4a4f.jpg)

**Comment by ZakJudges** [comment]
Hi @Dr-Colosso, I have not been able to reproduce this bug in the latest experimental build on Steam. Would you be able to try the experimental build (https://github.com/TheGameCreators/GameGuruRepo/issues/3907), and let me know if that sorts the issue for you?

If not, would you be able to send me the map, and I will see if I can reproduce the bug. Thank you :)

**Comment by Dr-Colosso** [comment]
I am currently running the experimental build. The levels are packed with custom and altered objects. I can send the level map, but you would be missing most of the assets in the level.

**Comment by Dr-Colosso** [comment]
Further testing today showed the terrain pits are forming in sections of my map that I have flattened. when I changed the terrain max hight to zero the pits go away. I don't know if this helps, but I will keep testing.

**Comment by plemsoft** [comment]
@Dr-Colosso Also not able to reproduce , i assume one of your custom object has "autoflatten      = 1" in the fpe file, could you check this list of fpe's that was missing when i tested:

MISSING MEDIA:
entitybank\user\teleporteri.fpe=replaceentitybank\user\teleporteri.fpe
entitybank\user\volcan.fpe=replaceentitybank\user\volcan.fpe
entitybank\user\skel1.fpe=replaceentitybank\user\skel1.fpe
entitybank\user\skel2.fpe=replaceentitybank\user\skel2.fpe
entitybank\user\bars.fpe=replaceentitybank\user\bars.fpe
entitybank\user\teleporter1.fpe=replaceentitybank\user\teleporter1.fpe
entitybank\user\lizard.fpe=replaceentitybank\user\lizard.fpe
entitybank\user\greenlamp.fpe=replaceentitybank\user\greenlamp.fpe

Do any of these have "autoflatten      = 1" in the fpe ? , if so could you zip it including all the media and e-mail it to me at plemsoft@gmail.com , so i can test again , Thanks :)

**Comment by Dr-Colosso** [comment]
Thanks for working with me on this. Give me a couple of days to review them
and let you know.

**Comment by Dr-Colosso** [comment]
I have been through all the .fpe files you listed and none have an
"autoflatten" option listed.

**Comment by plemsoft** [comment]
@Dr-Colosso Could you zip your standalone and e-mail a download link to me at plemsoft@gmail.com , then im able to see the same as you , Thanks for your help :)

**Comment by Dr-Colosso** [comment]
I will recreate it and send it to you. I have deleted and remade the levels
all flat to correct that issue.

**Comment by plemsoft** [comment]
@Dr-Colosso Thanks for getting back :)
