### ISSUE TITLE
standalone export issue.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4241]
tried to export a stand alone.

this happened.

![Screenshot 2023-03-15 142314](https://user-images.githubusercontent.com/68471279/225345814-74a9fb8b-0b0b-485d-add2-445856ff3134.png)
![Screenshot 2023-03-15 142249](https://user-images.githubusercontent.com/68471279/225345822-79676235-b92f-4fcd-87cb-f57ffc5c36eb.png)

**Comment by davetgc** [comment]
Hi, can you post your system specs please.

Thanks.

**Comment by ZakJudges** [comment]
Hi @casigus, are you able to run all of the levels in that project without encountering that crash? If so, would you be able to email me the project and map, and I will see if I can reproduce on my end? Thanks :)

My email is zak@thegamecreators.com

**Comment by casigus** [comment]
yeah all levels run fine. completely re-installed max, and yeah the exact same bug appears. 
![image](https://user-images.githubusercontent.com/68471279/226101045-ef5b88cd-53be-4302-b3d4-874a6529e53b.png)

tried the same with a completely empty level, and it did the exact same thing. sending the project/map/files wont fix it, plus the files are FAR too big to send over and would take alot of time.

if an empty map is doing it and its still happening after a fresh install, this is clearly something else.

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/226101118-e9c8035e-4cc6-4924-b4bb-b5d253a33c7f.png)

**Comment by casigus** [comment]
happens with every single game project.

![image](https://user-images.githubusercontent.com/68471279/226101267-ff5106b9-8268-4c8f-9cc9-a084a43cc9bf.png)

![image](https://user-images.githubusercontent.com/68471279/226101277-ad5c082e-0eaf-4869-8054-89bbf5b79a5d.png)

**Comment by casigus** [comment]
deleted the contents of this folder: 
![image](https://user-images.githubusercontent.com/68471279/226101636-5b09c7fd-70d4-4f19-9ab1-c7668e608c44.png)
 and its letting me export one of the demo games.

**Comment by casigus** [comment]
this error also happened with gg classic...

https://steamcommunity.com/app/266310/discussions/0/610574106416451839/

**Comment by casigus** [comment]
created a new folder (import/project folder) created a test project game, it exported fine. copied the testeed game project back to my old files/folder, went to export, same problem. 
![image](https://user-images.githubusercontent.com/68471279/226107015-81912b6f-7768-4046-a855-84e8f05ab4a3.png)
im done.

**Comment by casigus** [comment]
gone back to a previous build, and yeah exports. 
![image](https://user-images.githubusercontent.com/68471279/226108713-83674d94-637b-49c5-ab0f-7d30cafa2dc4.png)

so this is something tied to the latest updates causing ggmax to get confused with my custom files and unable to find something.

![image](https://user-images.githubusercontent.com/68471279/226108815-39558d22-dec1-4f70-84ec-027a703f5127.png)

**Comment by casigus** [comment]
Went back to a previous update, max does export the game as a standalone HOWEVER, this is what the maps look like, 
![image](https://user-images.githubusercontent.com/68471279/226110263-be13215e-e4f5-4ffa-8ec8-5cf1985e0055.png)
completely empty. ALL the files work fine and I can place them, however returning to a previous update just wipes the map of everything.....

**Comment by casigus** [comment]
This is the last version of ggmax that will export any of my game work. 
![image](https://user-images.githubusercontent.com/68471279/226110786-1ee6f8b2-958f-4467-8d48-27aaa303227c.png)

HOWEVER the maps been completely wiped, all objects appear in the max as they where, but they entire maps completely blank (hours of work) 

something is very very broken with ggmax.

**Comment by casigus** [comment]
the experimental release has fixed this issue.
