### ISSUE TITLE
Flashlight

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#4242]
When i use flashlight.lua then then the image of the lantern itself appears in the light from the lantern
![image](https://user-images.githubusercontent.com/89519185/225546503-58c46c6f-9b14-47c6-82c7-d64828e7f28e.png)

**Comment by davetgc** [comment]
Hi,

Could you please describe the process you used for this to happen?

**Comment by Denis87z** [comment]
this happens sometimes. When the light is turned on, the shadow of the flashlight is highlighted in different places. 
>Воскресенье, 19 марта 2023, 9:00 +03:00 от davetgc ***@***.***>:
> 
> 
>Hi,
>Could you please describe the process you used for this to happen?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <TheGameCreators/GameGuruRepo/issues/4242/1475116690 @ github . com> 
 
 
--
Denis Shagarov
