### ISSUE TITLE
GGMax BUG: When a player reaches a win zone, the FPS drops significantly, before going back to normal when the next level is loaded.

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#4245]
Specs: RTX 3060 Laptop
Ryzen 5600h
16gb of RAM

https://user-images.githubusercontent.com/112423658/225748873-dd7f448b-2d0e-4774-9774-adc85495094f.mp4

Frames per seconds are shown at the top right corner (the line where it says "Images/s")
Also, when a player reaches the win zone, a text will be displayed for a second which just says "win zone". When testing a game it's alright but this also happens on a standalone (aswell as the main bug, the FPS drop).

**Comment by blackhat110** [comment]
> Tekst strefy wygranej ma pokazać, że trafiłeś w strefę wygranej. MAX nie przechodzi na kolejny poziom w grze testowej.
> 
> Czy ktoś jeszcze może potwierdzić spadek FPS?

I have the same
