### ISSUE TITLE
MAX - RPG logic omission; perks!

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#4247]
A surprising omission to RPG logic seems to be a big staple of RPG games; a perk system!

Typically in an RPG, each time you level up, you get some points to allocate into base stats (as we have now), in addition to one (or more) "perk points" that can be spent on "perks".

Perks are separate from base stats (though to unlock a perk it may require you have a certain rank in one or more base stats, such as a perk that increases jump height requiring you have a certain "agility" level); they either add an entirely new ability (ex: A perk that adds a 10% chance when you take damage that half of it is reflected back towards the enemy, or a perk that allows you to force-open locked doors), augment an existing ability (ex: Increasing jump height, or allowing the player to double-jump), or provide a boost to stats that aren't touched by base stats (ex: a perk that reduces sway while aiming in a sniper scope, or a perk that reduces health regen delay and increases health regen speed).

In addition to this, sometimes a single perk might have several levels or ranks, which when further unlocked will increase the benefits of the perk, or increase the abilities granted. (For ex: A perk called "Acrobat" that grants higher jump height on rank 1, grants double-jumps on rank 2, and removes/reduces fall damage on rank 3. Another ex: A perk called "Gunner" that increases firearm damage by 5% with each rank, up to rank 5.)

As for actual implementation, I'm not entirely sure of how they could/should be implemented, but they should definitely allow for custom .Lua logic to be hooked up to them so that we can accomplish just about anything we'd like with perks.

**Comment by Necrym59** [comment]
How about we get the system working first
