### ISSUE TITLE
GG MAX-standalone bug

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4248]
after standalone render items in your inventory are not displaying,
the cursor is not displaying eather, so you can´t interact with any of the HUD screens...

![GameGuru MAX - GB2 fpm 17 03 2023 16_49_41](https://user-images.githubusercontent.com/109030026/225955026-07884e7d-153a-445e-9017-8f7ca97f9a7b.png)
![GameGuru MAX 17 03 2023 16_32_43](https://user-images.githubusercontent.com/109030026/225955041-585d26ad-0214-4a56-ac07-9a53e43677e1.png)

**Comment by plemsoft** [comment]
@Keepo1 Thanks for reporting this issue , just tried to export the "RPG Template" project and i do see the inventory icons ?, could you try the same and see if it works , if not please make sure your on the latest EXP build , if it still do not work , let me know where you store your inventory icons , Thanks :)

**Comment by Keepo1** [comment]
@plemsoft yes it works now. thanks.
