### ISSUE TITLE
GGMAX - The new command SpawnNewEntity can't clone Characters or Particles correctly.

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#4249]
-- spawn new game object

In Lee's last broadcast anouncing this new command..

	local newe = SpawnNewEntity(targE)

Lee said..

1.  It should/could be possible to spawn a new cloned object entity.
     (yes I can do this)

2.  It should/could be possible to spawn a new cloned character entity.
     ( Yes/No only partly works)

3.  It should/could be possible to spawn a new cloned Particle object.
    ( Yes/No only partly works)

-----------------------
The Character...

1. The model is cloned and appears.
2. It does not work as character. It just stands there.The original character will attack and move.
3. It has no character capsule collision shape or any kind of collision.
4. I can attach a lua script to it (useing lua) and veiw the model is animating. (view Animations script)

------------------------
The Particle...

The Particle is cloned and appears but..

1. It is the original default (pink dots) not the (yellow fountain) I had set the particle to.
2. Also the RED UI gadget is shown as well.

**Comment by thor49** [comment]
I see Lee has mentioned this new command  
local newe = SpawnNewEntity(targE)
in his latest video saying how great it would be to spawn new enemies..
Go try it out... He obiviosly has not been shown this report... ??
Whats up..

**Comment by thor49** [comment]
assign to @https://github.com/LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@thor49 Any chance of a small level using stock assets and behavior to show the issue, it will save me some time in reproducing this one, thanks!

**Comment by thor49** [comment]
Simple test level

1. Add Rabbit to level. 

2. Add object to run clone script...
   ( -- Clone_Entity v4 by Necrym59 )
   This Clone Entity script is in the RPG scriptbank folder.
    Necrym59 added it last week..
   (his script names the target as 'Rabbit' this can be changed for other tests)

3. Add switch to activate the clone script.

4. Link the (2)object clone script object to the switch with visual logic.

5. Run level.. the Rabbit will be cloned.

6. Look at the Rabbits Physics shape - It has none.. it cannot move..it is a statue.

The Name of the entity to be cloned can be changed in the clone script.. to then test
Particles , Enemy with weapon, etc..

**Comment by LeeBamberTGC** [comment]
@thor49 Thanks for the step by step, very useful. Next EXP build will have spawning capability for rabbits and zombies:
![image](https://user-images.githubusercontent.com/35840583/233638092-f81060f0-df1f-4831-9b26-d0d4dc6313e5.png)

**Comment by thor49** [comment]
Characters :-
1. The new Character is cloned and appears and is holding weapon. (Tick)
2. The clone runs the correct script and attacks my enemy. (Tick)
3. The Clone has no physics capsule or shape..  (?)
4. I can walk through the clones they have no collision.(?)

**Comment by thor49** [comment]
Lee ..  I am doing more testing on this.. 
1.  I have a small test level  ( here all the clones disappear when level is exited ) (tick)
2. I have a large test level (here all the clones are still their when level is exited) (?)
3. When I re-run the large test level then all the clones are still their as statues
4.  If I hit them with spear they show concrete bullet hole decals.
5.  In editor I cannot select them, If I try draw rectangle around one I some times get a selection but it is showing a rock wall as the selected entity in the right properties dialog box. (maybe where concrete decals come from)
6.  I am sure the rock wall object is part of some group entities that are in the level.(I have a lot around the level)

So I am wondering where are the Clone entity ID numbers are being taken from, could there be some kind of corruption going on.

**Comment by LeeBamberTGC** [comment]
@thor49 These items are confirmed:

* The Clone has no physics capsule and I can walk through the clones they have no collision - FIXED FOR NEXT EXP Build

I cannot reproduce this with latest EXP build:
* I have a large test level (here all the clones are still their when level is exited) (?)
* When I re-run the large test level then all the clones are still their as statues
* If I hit them with spear they show concrete bullet hole decals.
* In editor I cannot select them

May be best if you attach a small FPM using stock media so I can run it and see the clones stay in the level when I leave test level.
