### ISSUE TITLE
Terrain Texture Creation adds 2GB of memory load, crashing test and standalone games

### ISSUE THREAD

**Issue by IvanErtlov** [TheGameCreators/GameGuruRepo#425]
During Test Game of a larger detailed map, and when starting the same map as standalone, this happens in the terrain texture generation step:

> 773938 : Loaded scriptbank\ehurtzone.lua                        S:0MB   V: (1358,0)     
774016 : Loaded scriptbank\bunkertor.lua                        S:0MB   V: (1358,0)     
774100 : Loaded scriptbank\door5000.lua                         S:0MB   V: (1358,0)     
774175 : Loaded scriptbank\kammlerdoor2.lua                     S:0MB   V: (1358,0)     
783109 : GENERATING TERRAIN SUPER TEXTURE                       S:1998MBV: (3357,0)     
783192 : INITIALISING POSTPROCESS                               S:0MB   V: (3357,0)     
783290 : postprocessing initialised                             S:3MB   V: (3360,0)     
783373 : INITIALISING PHYSICS                                   S:0MB   V: (3360,0)     
783451 : _physics_createterraincollision                        S:5MB   V: (3366,0)     
783526 : get terrian sectors                                    S:0MB   V: (3366,0)     

> 

With those 2 extra GB of memory consumption, the crash follows nin the next steps.

Log attached.

[Guru-Game_LOG_checkterrain_supertexture.txt](https://github.com/TheGameCreators/GameGuruRepo/files/2475991/Guru-Game_LOG_checkterrain_supertexture.txt)

**Comment by Teabone3** [comment]
This is concerning. Wonder if anyone else has experienced the same. Though im assuming they would need to have just as detailed a map to experience it.

**Comment by plemsoft** [comment]
Hi Ertlov,
did a quick test , and the reported mem used for "GENERATING TERRAIN SUPER TEXTURE" is reported before the actual function is called, so the actually mem spike is coming from one of your .lua scripts.

Try this:

Rename half of all your lua script so they cant be found.
Run your game with the log on.
If you dont see the mem spike , one of the lua scripts that you renamed has this problem.
Keep renaming and testing until you find the script that have this problem,

When you find the lua script with the problem , try to see if you can spot the problem , or post the lua script here :)

**Comment by plemsoft** [comment]
Edit: before the reported mem spike, we also have loading of all media used in lua scripts.
So in your case perhaps you have some lua scripts that contain Video references that should not be there ?

**Comment by plemsoft** [comment]
Edit2: Hmm this could be a decryption problem with very large video files , could you first try to delete your _e*.* videos and copy the original videos into the same folder (not crypted) ,and give it a try :)

They should not be named _e but have the original filenames.

**Comment by IvanErtlov** [comment]
Ok it seems to be that video playback swallows RAM equal to each frame in all of the videos.

**Comment by plemsoft** [comment]
@IvanErtlov Thanks for reporting this,

This has been fixed you know ;) , and are ready from the next release.

https://github.com/TheGameCreators/GameGuruRepo/commit/d521b9d831b3c4f618edfb5d60ce3c613bab5f1e
