### ISSUE TITLE
Game Guru Classic- Saving Standalone still has issue

### ISSUE THREAD

**Issue by C4ever08** [TheGameCreators/GameGuruRepo#4250]
![Game Guru -  mapbank_Mantis Corp_Mantis Corp fpm  -  Entity Editing Mode  2023-03-17 11_42_22 AM](https://user-images.githubusercontent.com/80596156/225964642-1e8add7a-ec3a-444c-b408-1b897102370c.png)

so lately after the March update of this year I have ran into this issue when making a standalone. So once I make a standalone when it gets to 99% a box appears like so in the pic  I can then click ok and it resumes to 100%. Also noticed I have to carry over scripts that weren't during the standalone process. So I'm not sure if that is causing not carrying  over my scripts or not but just want to make sure i reported this and hopefully see it fixed thanks.

**Comment by AmenMoses** [comment]
The 'require' scripts are not being copied over, plus they are not being processed.

What should happen is that scripts should be read and processed recursively, so for example if script A requires script B and script B requires script C and script C contains a LoadImage( 'somefile.png') then all three scripts and somefile.png should be copied over to the standalone.

**Comment by AmenMoses** [comment]
The same thing occurs in MAX.

**Comment by OldFlak** [comment]
For MAX
- Another plug for proper projects - copy over everything in the project - no need to read anything at all then

**Comment by plemsoft** [comment]
This is fixed in max from another issue :) , Classic still need to be fixed.

**Comment by LeeBamberTGC** [comment]
@AmenMoses @plemsoft Could not dig out the MAX changes that corrected this, but have added these lines that are missing in the standalone export code:

	addtocollection("scriptbank\\physlib.lua");
	addtocollection("scriptbank\\quatlib.lua");
	addtocollection("scriptbank\\utillib.lua");

**Comment by OldFlak** [comment]
Last time I tired standalone after V1, 90 percent of my images, a few models, and a couple scripts were not copied over.
GGc way is flawed 
- please add projects. Everything in the project gets copied over - job done :)

**Comment by C4ever08** [comment]
I do apologize for the long delay for responding. I am however still getting that prompt after it gets to 99% during creating a standalone in GGC.

**Comment by LeeBamberTGC** [comment]
@C4ever08 When you run Classic, do you see the "2023.09.06 - September Fixes" prompt?  If so, then it could be your script has become corrupt, this can be solved by a VERIFY FILES from Steam Client or if that fails, back up your files, then do a complete reinstall of GameGuru Classic as that will restore all core files to their latest versions.

**Comment by C4ever08** [comment]
Ok Lee that worked no more prompt. You can now close this for GGC. Thank you
