### ISSUE TITLE
Bug Chest/Shop

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4256]
report a bug between the shop script and the chest I can see the shop items put the product name the hud disappears in the shopkeeper

**Comment by SampeyFS** [comment]
![20230318162627_1](https://user-images.githubusercontent.com/108415264/226115552-bd345fa6-90f6-4689-8c77-6505f1157752.jpg)
![20230318122209_1](https://user-images.githubusercontent.com/108415264/226115553-fd189238-90a9-47cb-a728-a43161811c6a.jpg)

**Comment by LeeBamberTGC** [comment]
@SampeyFS The shot you provide is not the shopkeeper it is a chest. You click an item to see a larger image and its title in the center area. Same for the crafting screen, click an item and you see it in the bottom left panel with title.
