### ISSUE TITLE
User defined global naming convention is confusing

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4258]
![image](https://user-images.githubusercontent.com/99803873/226157418-e8fb35cd-797a-4847-8de3-642af663ddd0.png)

When adding a new global to the screen editor, it's confusing when creating the global name. The box is called, User Defined Global Value, when it would make more sense to be called User Defined Global Name.

**Comment by ZakJudges** [comment]
@LeeBamberTGC Assigned to you as it isn't really a bug - though I do agree that changing it to User Defined Global Name/Variable would make for a much better user experience :)

**Comment by LeeBamberTGC** [comment]
@davetgc Changed for next EXP build :)
