### ISSUE TITLE
User definded globals aren't removed when resetting huds.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4259]
![image](https://user-images.githubusercontent.com/99803873/226159067-978e05be-7137-4b95-982a-47c67e1282dc.png)

When you reset the huds, user defined globals loose their names, but still remain as nameless globals in the list.

**Comment by ZakJudges** [comment]
@davetgc Added a fix to sort this. Should be in next EXP build :)

**Comment by davetgc** [comment]
@ZakJudges - Thanks, well done.
