### ISSUE TITLE
.ogg music file not loading

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#426]
I have .ogg music files not loading into GameGuru. 

Error Message box reads:

This file is encrypted and cannot be loaded into GameGuru Editor.

It then lists the location and filename of the .ogg file.  The file is NOT encrypted in any way.  

Have to use task manager to close error so loading of testgame continues, when I start testgame after the error. The music file plays fine??????

I'm using a zone to trigger the music file.

When I go from testgame back to editor, just a black screen and have to use task manager to end task editor. 

Anyone else having this problem??

**Comment by tarkus1971** [comment]
This also occurs with .wav files too.

**Comment by tarkus1971** [comment]
Lee found the problem, not a bug.

I just happened to call a folder in audiobank 

_e_home

I remember standalone folders have the _e prefix.  Once I renamed the folder the error was gone.

Mark this as NOT A BUG.

**Comment by tarkus1971** [comment]
Now found out why "black screening" my start marker was in a position that seem to cause the player to start crouched.  Once I moved start marker the "black screening" ceased. Odd.

**Comment by plemsoft** [comment]
@tarkus1971 Thanks for reporting this,

Wow your good fixed all your issues , thanks for the help :)
