### ISSUE TITLE
Dropping an object for the inventory doesn't put it back in the level.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4261]
It doesn't appear as it dropping item for the inventory drops it back into the level. I'd say this is the expected behavior. I've listed this as a bug as, if intentional, isn't what will be expected.

**Comment by LeeBamberTGC** [comment]
@davetgc Some objects like resources assigned with the resources did drop back into the world, but now extended this system to resources that are collected such as health that can be collected as a single quantity, then dropped one by one as required.
