### ISSUE TITLE
white creen

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#4272]
when i start my tst level simetimes a white screen appears.
![image](https://user-images.githubusercontent.com/89519185/226629811-534121cf-69d2-4b9a-97e6-76fa0fc2fdee.png)

**Comment by davetgc** [comment]
Can you please post your system specs?

**Comment by Minyo86** [comment]
I have the same problem. Every time I place an entity created with the building editor, the test does not start.
my spec:
Processor: AMD FX(tm)-8350 octa-core processor, 4.00 GHz
Memory: 32.0 GB
VGA: AMD Radeon RX 560 Series 4GB
Win 10 Pro

**Comment by LeeBamberTGC** [comment]
Added code so splash is always shown, and no white refresh screen shows at start
