### ISSUE TITLE
luce con swic bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4273]
the lights that are turned on do not turn off with the swic they remain on even if you remove the tick in both (parts)

**Comment by davetgc** [comment]
Can you please post a sample fpm using default media so the dev team can see what you're doing?

**Comment by SampeyFS** [comment]
when you put the button to turn the light on or off it stays on even if you remove the ticks start

**Comment by plemsoft** [comment]
Im able to reproduce and have assigned it to me :)

**Comment by plemsoft** [comment]
@SampeyFS Thanks for reporting this issue , this has been fixed and will be in the next update :)
