### ISSUE TITLE
Bug save hud

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4276]
![Uploading Senza nome.png…]()

**Comment by SampeyFS** [comment]
![Senza nome](https://user-images.githubusercontent.com/108415264/226977989-5eda6a33-d282-4c65-af2a-252a7473f634.png)

**Comment by davetgc** [comment]
Is this that the inventory item has no image?

**Comment by SampeyFS** [comment]
yes I put the product icon but the program the doesn't save it puts this I figured out what is doing this thing is collection - items.tsv
