### ISSUE TITLE
GG Max - EXP Build - BUG - Crafting Formula

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4277]
After looting a collectable CRAFTING FORMULA item, The message about "Crafting Formula added to the Crafting Formula Inventory" is constantly displayed as you can see in the screenshot.

This does NOT disappear.

![Untitled](https://user-images.githubusercontent.com/66874403/227017748-e932e896-307a-4561-b53a-68d571715415.png)

**Comment by ZakJudges** [comment]
Hi @Tum1370 , thank  you for reporting this issue. I have added a fix which should be in the next experimental build on Steam :)

**Comment by Tum1370** [comment]
@ZakJudges Just tested this in one of the new EXP builds. I did notice that the Crafting Formula has been renamed to Recipe now.
But i can confirm that this bug is now fixed.

Thanks Zak
