### ISSUE TITLE
GG Max - EXP Build - Bug - Save Standalone does not work with errors

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4278]
As the title says, I Have just tried to created a simple RPG test level as a standalone, using the EXP build, but i get this error when Starting the game.

![Untitled](https://user-images.githubusercontent.com/66874403/227019720-51f20def-716b-4313-b460-7eba2970f464.png)

**Comment by casigus** [comment]
can you go to your ggmax install folder and copy the script folder from there into your game folder, that might fix the problem.

**Comment by Tum1370** [comment]
@casigus I copied the one file "utillib.lua" over to the scriptbank folder in the game folder and it worked fine.
I did have it set to play in VR though, that does not work.

**Comment by casigus** [comment]
yeah the vr doesn't really work here either, did follow the steps but nope. Using a Oculus Rift S so it should be ok but my gods it went funky. MY head is still hurting from the eye wobbles !

**Comment by MonkeyFrogStudio** [comment]
I get the same thing when I try to run a stand alone game.

**Comment by Tum1370** [comment]
I have just retried creating a standalone after the 2 GGM updates i see today, and now i get a different error message when trying to run the Standalone.

![Untitled](https://user-images.githubusercontent.com/66874403/227273847-f1d71b42-74fe-4a77-8ca2-fbe084a72f21.png)

**Comment by Tum1370** [comment]
@synchromesh62 Just tried redoing this Standalone of a simple RPG test level. I didnt tick the VR box this time, and i get the same error, something about the animation of a character creator character.
![Untitled](https://user-images.githubusercontent.com/66874403/227283990-ae83e99e-08d1-4580-952d-cffb1983af57.png)

**Comment by synchromesh62** [comment]
Teaching granny to suck eggs im sure but you have tried the usual verify process right. ?

**Comment by Tum1370** [comment]
Yes, i have also just downloaded another update of GGM and tested the standalone again, and get the same error message as above.
Probably not copying certain files over to standalone ?

**Comment by Granada1** [comment]
Sounds like Lee is working hard on it

**Comment by Tum1370** [comment]
Ye he seems to be, Another EXP update just went live, downloaded it, Verified the files, and exactly the same error message.
Maybe it is this encryption stuff causing the problems ?

**Comment by plemsoft** [comment]
@Tum1370 This has been fixed and will be in the next EXP update , perhaps it dont make it into todays update but then in the next :)

**Comment by plemsoft** [comment]
@Tum1370 Its not been merged , so will first be in the next update , perhaps Monday :)

**Comment by Tum1370** [comment]
@plemsoft Ok, thank you for the fix :)

**Comment by Tum1370** [comment]
@plemsoft Thanks for the fix on this, Just downloaded the latest EXP build and my Standalone games are working without this error.
Ill close this issue now.
