### ISSUE TITLE
Encryption Worries.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4279]
Lee mentioned no encryption for standalones in the stream for V1 which is a little worrying ?
Sure models are protected in the closed .dbo format but this will not stop other Max users using others work including audio, textures, scripts and most of all DLC's. Surely the Classic encryption could be added being so similar.
Any games released on Steam would be open season really :(

**Comment by Granada1** [comment]
Definitely needed from the start I think

**Comment by qcrocknet2020** [comment]
I vote to have this as a HIGH priority in V1. I would never release a standalone game made in GGM that has all my models, audio, scripts...  open to everyone. Other engines include encryption by default (unity, unreal, ect..), why not GGM? What is the reason? Instead of telling the users to find their own way of encrypting, why not have it by default or propose an alternative instead. How would an EXE of GGM would be able to read encrypted sounds, models... done by a third party encryption tool?

**Comment by waterdrinkingfox** [comment]
Totally agree. It's a basic feature of many engines, even GGClassic...

**Comment by LukeTheLukeLTL** [comment]
I agree. This is something that definitely needs to be added.

**Comment by Necrym59** [comment]
I must admit i agree, I think it should be in from the start of public release, if people release games with bought third party assets their could be no end to them being reused by others and legal issues would result, even those converted to dbo would not be safe from abuse. Serious thought must be given in my opinion before relase of v1.

**Comment by Blood-Moon-Interactive** [comment]
I agree - I feel like the removal of the splash screen and the movement to version one implies a readiness to start exporting, sharing, and even selling finished products. Encryption in that case is critical to protect the interests of both the developer and the artists of the assets being used.

**Comment by jimipcool** [comment]
I have been really happy with the recent additions to GameGuruMax but no encryption on release is gonna be a dealbreaker for me since i dont have the time and means to invent a whole process just to make the standalone game work for endusers

**Comment by 3coms** [comment]
The stuff should be protected, especially third-party stuff.
When TGC allows releasing games, I'm afraid we are going to see some "jewelry" out there, if you even add the non-encryption, well, you'll end with many troubles.

**Comment by wizardofid29** [comment]
@LeeBamberTGC From an artist perspective with a steam DLC coming out soon, as well as other artists that have released steam DLCs. This is a problem, a huge one you aren't protecting the artist interests. There is a fair obligation that require that interests being protected

**Comment by MonkeyFrogStudio** [comment]
As a creator of a few DLCs (and wanting to do more) and as someone that wants to create games with GameGuru MAX, I am more than a bit upset that soon people will be allowed to publish and share games that could allow anyone with MAX to use the assets from those games. Sure, as others have pointed out, .dbo itself is protected. But as others have pointed out, anyone with a copy of MAX could simply take those .dbo files (along with their associated files) and simply use them in their own projects. Heck, all they would have to do is copy the folder over and have instant access to all of them.

A DLC is one thing, but if I create my own game with my own custom assets, my own custom sounds, etc., then anyone with MAX could get the game and use those assets for their own purposes. Yet, that would NOT be my intention for any game I create and release. It wouldn't matter if the game were offered for free or for sale. My assets in my games are for me to use alone, not for anyone else. 

MAX should definitely have a form of protection for games published. Frankly, in my opinion, until that protection is in place, I would not recommend the banner be removed that was prohibiting the publishing of games made with MAX.

**Comment by LeeBamberTGC** [comment]
@wizardofid29 @MonkeyFrogStudio Thanks for the feedback. Encryption added to EXP build for your assets, excluding some of the TGC owned media folders:

pMatch = "Files\\editors";  if (strstr (szCurrentDirectory, pMatch) != NULL) bDoEnc = false;
pMatch = "Files\\effectbank";  if (strstr (szCurrentDirectory, pMatch) != NULL) bDoEnc = false;
pMatch = "Files\\terraintextures";  if (strstr (szCurrentDirectory, pMatch) != NULL) bDoEnc = false;
pMatch = "Files\\treebank";  if (strstr (szCurrentDirectory, pMatch) != NULL) bDoEnc = false;
pMatch = "Files\\grassbank";  if (strstr (szCurrentDirectory, pMatch) != NULL) bDoEnc = false;

For now.
