### ISSUE TITLE
GGM - BUG - "forwardfacing" objects get confused when placing them on ceilings

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4282]
Objects using "forwardfacing" to "snap" to ceilings appear to get confused. They snap the model to the ceiling sideways, but then after placing it that way and pressing "R" to rotate the object, it instantly snaps back to it's appropriate origin and rotates as it should.

https://user-images.githubusercontent.com/103399301/227109304-c316d406-b872-44b7-a51f-221a07a73f69.mp4

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Can you reproduce this with the latest EXP build using a stock object. I used the light bulb and it worked nicely. The system does depend on the original 0,0,0 orientation of the object. The light as you can see is sideways normally:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/323b5b19-9f6a-4ef3-a3a2-0e4faa8b9036)
But is rotated to find the ceiling when using the smart placement system:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f83e46a3-d095-4c20-9f3e-5c403e5145f8)
Notice the X axis of 270 when finished placement.
