### ISSUE TITLE
GGM - BUG - The Aztek Knife appears to have an extra anim frame or two in it's alt-fire mode (V)

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4284]
You can see the player's left arm pop into the screen for just one or two frames when a certain animation is played. Seems too fast to be an intentional animation, but I could be wrong.

https://user-images.githubusercontent.com/103399301/227106741-d7970509-8e89-4a78-b79f-e7087bb38aec.mp4

**Comment by LeeBamberTGC** [comment]
@Kravenwolf This animation was replaced a good while ago to remove the odd rogue frame. Ensure your writeables guncore folder does not have an old copy of "gamecore\guns\aztec\AztecDagger" and then text with the latest EXP build to confirm no more issues with the Aztec Dagger.
