### ISSUE TITLE
Trader sell not working.

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#4287]
I don't seem able to sell back to the Trader. No value appears on the sale side. I can get it to come up with the cost price but not set value. Also when I click  'Sell' nothing happens. Thanks
Fixed now.

**Comment by davetgc** [comment]
We are waiting on some documentation for this. The team is pretty busy at the moment, can anyone confirm if they have this working, or is it a bug?

**Comment by Tum1370** [comment]
Trader buy and sell both work fine for me on exp build.
