### ISSUE TITLE
Emissive texture doesn't work when spawn 

### ISSUE THREAD

**Issue by Dimoxinil** [TheGameCreators/GameGuruRepo#429]
Emissive texture doesn't work when spawn the same character more than once.

**Comment by LeeBamberTGC** [comment]
Could you provide a step by step using a stock character on how this issue can be seen, thanks!

**Comment by Dimoxinil** [comment]
I think..  there is no animated entities with emissive maps in the stock character.

if you add any emissive texture to one of the stock characters and Spawn the same character several times.. you can see the problem.

**Comment by Dimoxinil** [comment]
I added a emisive texture to a stock character.. Combat MutantEmisisive

I attached the link:
[dropboxlink](https://www.dropbox.com/s/lq04uf0mb6w296q/Combat%20MutantEmisisive.zip?dl=0)

**Comment by Dimoxinil** [comment]
An explanatory video of the problem:  [youtube](https://youtu.be/W1TrFGCDLgc)
and..
a zip file with the gameguru scene and all the necessary files.  [dropbox](https://www.dropbox.com/s/b47vcl6s7ss59rp/files.zip?dl=0)

**Comment by plemsoft** [comment]
@Dimoxinil Thanks for reporting this,

This has been fixed and are ready from the next release :)
