### ISSUE TITLE
GG Max - EXP Build - BUG - Player Inventory DROP

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4291]
Hi, If you DROP an item from the player inventory, and the item you drop is not in one of the first 4 slots on the top row, The item will drop to the ground, but the image of the item remains in the inventory. 
Even after dropping the item, you can move the image in the inventory around, but the item is not there.
If you move the image to one of the first 4 slots on the top row, the image will disappear.

![1](https://user-images.githubusercontent.com/66874403/227272630-cb4d33ab-2c3a-45ba-9857-9e668c778289.png)
![2](https://user-images.githubusercontent.com/66874403/227272644-6a7e5e2d-0b29-47d7-a816-a9b770913ad7.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Many improvements to RPG inventory, containers, and DROP. Check next EXP build and let me know if all is well, thanks. If not, maybe a small stock level and some steps :)

**Comment by Tum1370** [comment]
@LeeBamberTGC This bug has been here ever since the inventory has been implemented.
It was still here in the latest EXP build i download earlier.

**Only DROPPING from the first 2 slots in inventory actually makes the icon disappear.**
Everywhere else the icon stays there in the inventory after pressing drop. But the item still drops. It is just the ICON remains.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Not uploaded an EXP build so far today. Uploading now.  Try again in 2 hours :)

**Comment by Tum1370** [comment]
@LeeBamberTGC I tested this on latest EXP build, and exactly the same, First 2 slots the item drops fine, Any other slot in inventory, the item drops, but the Icon remains in inventory.

**Comment by LeeBamberTGC** [comment]
@Tum1370 In this shot from my latest build, I picked up three plants, a scroll and a potion:
![image](https://user-images.githubusercontent.com/35840583/231821116-1c929739-9389-49a6-8530-170b87f7d3a2.png)
I then dropped each one down in a line, but did not drop the last one. As you can see all cleared from the inventory except the one I did not drop.  Are you able to repeat this process in your build?

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok I have just tested this bug about the ICON remaining in the Inventory, after dropping an item. I used the latest EXP build, I deleted the RPG Template prior to testing so it download latest version.

Screenshot shows you, that the RED CIRCLE is the same items as in your screenshot, DROPPEd but is FLOATING in mid air.
The YELLOW CIRCLES show the MAGIC SCROLL. As you can see, the ITEM dropped, but the ICON remains in the INVENTORY.

![Untitled](https://user-images.githubusercontent.com/66874403/231821774-085e85f0-dc6b-4841-abf3-8d85b604cefc.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for this I can now reproduce:
![image](https://user-images.githubusercontent.com/35840583/231825246-0884f5fb-1650-44ff-8d64-b67a986a0316.png)

Seems you need to pick it up, the move it in the inventory before dropping it down.

**Comment by Tum1370** [comment]
@LeeBamberTGC Sorry for delay, was having a problem with my 3rd quest in a test questline on my RPG TEST level. 
Just tested this Player Inventory DROP / ICON bug, I Tested it on my made Woodlands level, and my Body Armour was dropping from all slots in the inventory, and the icon was disappearing.
Thanks for the fix, I will close this issue now.
