### ISSUE TITLE
Experimental build does not make a stand alone game / VR and Windows

### ISSUE THREAD

**Issue by MauriceHoffman** [TheGameCreators/GameGuruRepo#4296]
When i want to make a stand alone game / exe with and without VR on different directories C: / D: etc GameGuru Max crashes.

See the pics for the details
![Screenshot 2023-03-24 083420](https://user-images.githubusercontent.com/43264399/227455796-d3987eea-8606-421a-9d53-5c449c769bda.png)
![Screenshot 2023-03-24 083637](https://user-images.githubusercontent.com/43264399/227455832-001c3334-669b-4b9e-8032-d850d4fdf08b.png)

**Comment by Nader-B10** [comment]
I am facing the same problem

**Comment by MauriceHoffman** [comment]
I am trying a fresh install now, i install it on my D: drive but he looks for something on the C: drive maybe that is the cause ?

**Comment by plemsoft** [comment]
@MauriceHoffman Thanks for reporting this issue , could you let me know where you currently have MAX installed ?, also let me know if you at some point had it installed in "c:\Program Files (x86)\Steam\steamapps\common\GameGuru MAX\" , Thanks :)

**Comment by MauriceHoffman** [comment]
Hello i installed MAX i=on the c:/ drive and now it is working well. I let Steam normally install all my games and utils on the D: drive but i can confirm that then you can't make a standalone executable

**Comment by plemsoft** [comment]
@MauriceHoffman The update is now available in the EXP build , could you try it again , Thanks for your help :)

**Comment by plemsoft** [comment]
@MauriceHoffman The error indicate that your minning one of these file:

\SteamLibrary\steamapps\common\GameGuru MAX\Files\databank\bloodsplash7.png
\SteamLibrary\steamapps\common\GameGuru MAX\Files\databank\bloodsplash8.png
\SteamLibrary\steamapps\common\GameGuru MAX\Files\databank\bloodsplash4.png
\SteamLibrary\steamapps\common\GameGuru MAX\Files\databank\bloodsplash5.png
\SteamLibrary\steamapps\common\GameGuru MAX\Files\databank\bloodsplash6.png
\SteamLibrary\steamapps\common\GameGuru MAX\Files\databank\bloodsplash1.png
\SteamLibrary\steamapps\common\GameGuru MAX\Files\databank\bloodsplash2.png
\SteamLibrary\steamapps\common\GameGuru MAX\Files\databank\bloodsplash3.png

Please try to "validate" your files in steam and try again , let me know how it goes , thanks for your help :)

**Comment by MauriceHoffman** [comment]
it is when i am running standalone, what do you mean by minning ? These are demo projects i haven't touched or altered something

**Comment by MauriceHoffman** [comment]
The files are in the directory

**Comment by plemsoft** [comment]
@MauriceHoffman "Missing" sorry a typo, OK so the original issue is fixed for you , your able to generate the standalone now?
What demo project did you try to generate a standalone from ?

**Comment by LeeBamberTGC** [comment]
@ALL: No reports since March 2023 so closing the original issue in favor of newer standalone issue reports.
