### ISSUE TITLE
GameGuru MAX - Stand Alone - Unneeded Things

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4297]
I created a test stand alone game to send to Preben to showcase a bug. The stand alone consists of a single EMPTY level (i.e. the flat, grey grid) with one object and the player start marker. Nothing more. The stand alone folder is **1.11GB** in file size! Looking in the folder I've discovered the following is there:

- audiobank - 26.3MB

This folder contains all the audio for materials, misc, and voices, despite the fact that there are no materials, misc, or character voices used in the test level.

- charactercreatorplus>skins - 111MB

This folder contains the skins for the Character Creator. However, once again, there are no characters in use in this test game.

- grassbank - 65.3MB

This folder contains the grass DDS textures. But, once again, there is not a single blade of grass in my game. So, why's this even here?

- particlesbank - 5.09MB

Now, the size of this one is not an issue. The issue here is that ALL of my custom particles are in this folder. But I am NOT using a single particle in this particular test game. In fact, these particles were created as tests ages ago and are not part of any game or level I've created. Nevertheless, MAX has seen fit to copy ALL of them over to the start game folder.

- terraintextures - 426MB

Now, this one gets me. It contains within it ALL the terrain texture DDS files. But my test stand alone had NO terrain being used. It's an EMPTY. Why does the stand alone have to carry over ALL of the terrain materials? I mainly create interior-only levels any way. So, why would I want my game to carry this additional 426MB of materials that are not being used at all?

- treebank - 137MB

Here we go again! The tree billboards and DDS textures are all here. Why? This is an EMPTY level with not a single tree in it.

I skipped several folders when going over this, but I just wanted to point out that the stand alone game is overly bloated. My one object in the game is a mere 5.8MB. The images it uses (this is for an issue with Change Texture) are a total of 1.6MB. I realize that MAX needs several files to run, but **1.11GB**? More than half a gig is unused terrain and tree textures.

**Comment by OldFlak** [comment]
Yes, seeing similar.
Standalone copies media not used, and lots of media from custom location is not copied at all
