### ISSUE TITLE
GameGuru MAX - Bug - Storyboard Issues

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4298]
Just started to (finally) play with the Storyboard editor beyond creating new levels. I wanted to add a button to go to Settings (to change graphical settings) from the title screen. I added some text, realized I didn't need it, right-clicked and hit delete, but the text won't delete. So, that text is not permanently there since I cannot delete it.

I added a button, changed the text to read SETTINGS and selected Go To Another Screen under Action. When I go back to the Storyboard Editor (where all the storyboards are), there is no way to wire up the new button. This means that I cannot wire up or connect my new SETTINGS button to Graphics Settings (or anything else, for that matter).

As a side note - Rightclicking to access a menu to delete something is not ideal. Why can't we select an object in one of the story boards and simply hit the DEL button?

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Thanks for reporting this issue, this has been fixed and will be in the next EXP build :)

**NOTE: A update to the storyboard is still planned later, so its still limited but what you tried above is now possible.**

**Comment by MonkeyFrogStudio** [comment]
Thanks! Can confirm fixed.
