### ISSUE TITLE
Weapons - Soldiers without Guns in Hand

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#43]
Mutant, Combat and Uber Soldiers appear to all have invisible guns in their hands. Colt and Uzi are invisible. 

Related thread:
https://forum.game-guru.com/thread/219285

**Comment by LeeBamberTGC** [comment]
Hi plemsoft, do you want to create a branch for any fixes you are doing for GameGuru?  I was just going through the 'backward compatibility' bugs and was going to tackle this but you have assigned it to yourself :)

**Comment by plemsoft** [comment]
Sure i will sent my branch :) , committed some , to tired now so will commit the rest tomorrow but ALL that i assigned myself to has been fixed.
