### ISSUE TITLE
GG Max - EXP Build - Collectable list file does not update and delete items

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4301]
After testing this several times, and having to redo all my collectables, i find that if you delete an item that was a collectable it does not delete from the collectable file. But it seems to add an extra item to the end of the item list.
Also after trying to add / adjust an item name or image in collectables then does not save, and the old one keeps showing up.

Seems very buggy.

**Comment by plemsoft** [comment]
@Tum1370 Believe this is related to https://github.com/TheGameCreators/GameGuruRepo/issues/4367 , could you test in the next EXP update and see if it also fix this issue :)

**Comment by Tum1370** [comment]
@plemsoft Hard to say whether this one is currently fixed because Max creates a collectable list when there is nothing even on the level set as collectable.

**Comment by Tum1370** [comment]
@plemsoft I am closing this issue, as its basically the same as the other issue about the collectables and collectable files.
