### ISSUE TITLE
NPC bug between flag to flag  

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4303]
They don't go npc's anymore in the route that I had put this morning they were basically going from flag to flag it just goes back and forth in the same spot

**Comment by SampeyFS** [comment]
https://user-images.githubusercontent.com/108415264/227615447-d9842fee-beeb-41da-9abe-0298190692c7.mp4

**Comment by LeeBamberTGC** [comment]
@SampeyFS I think this was fixed a while ago. Just added two flags, a character and linked them up. All works fine with Patrol behavior walking the Aztec back and forth:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/3743a8ba-fb6b-443a-bd56-b1a78ada2a3c)
