### ISSUE TITLE
GG Max - Bug - Particles - Reset to Default Particles does not work, and Explosion particle does not work

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4304]
As the title says.
The RESET TO DEFAULT PARTICLES does not do anything now.
And also the circle EXPLOSION particle, does not work.

![Untitled](https://user-images.githubusercontent.com/66874403/227627659-6aa02f21-3918-45dd-bd37-76ff8bd3ed0b.png)

**Comment by plemsoft** [comment]
@Tum1370 This has been fixed and are in the latest build :)

**Comment by Tum1370** [comment]
@plemsoft Does RESET to Default particles not do anything now ? I press it and nothing happens, and it seems the first 9 particles cannot be changed now.
So what is the point of RESET TO DEFAULT PARTICLES even for now ?

**Comment by plemsoft** [comment]
@Tum1370 Try to select a particle and click "Reset to Default Particles" if will then reset and select the default particle, well i can see that it is not very useful, the code looked like that was what it was supposed to do ?

@LeeBamberTGC What is this button supposed to do ? , perhaps it should just be deleted not very useful :)

**Comment by plemsoft** [comment]
@Tum1370 Removed the button for now (next EXP build) until its defined what it should do , If everything else is fixed in this issue feel free to close this one, thanks for your help :)

**Comment by Tum1370** [comment]
@plemsoft OK thanks, ill close this bug now.
