### ISSUE TITLE
bug icon inventory/Items 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4305]
It is still present the lack of icons if you had solved it is back again this thing
![icon](https://user-images.githubusercontent.com/108415264/227638377-c1c544fb-5e33-469b-bc20-90899c841d62.png)

**Comment by SampeyFS** [comment]
![icon](https://user-images.githubusercontent.com/108415264/227638530-bd1f1794-0247-4fb6-bd9d-de6f84ba9636.png)

**Comment by SampeyFS** [comment]
insert them but max removes them

**Comment by LeeBamberTGC** [comment]
@SampeyFS In next EXP build I cannot reproduce this one. I had a fresh game project, empty level, added Milk, changed it to manual and collectable, changed the icon to a jewel and test level, it showed as a jewel in the inventory:
![image](https://user-images.githubusercontent.com/35840583/231853706-b76baf98-0c5e-49cd-a243-ea48404c38aa.png)
![image](https://user-images.githubusercontent.com/35840583/231853741-451755ef-e676-42ce-a9fe-9e822533e284.png)

**Comment by SampeyFS** [comment]
Yes, now it works, can you put that the objects you put in the shop are infinite that don't end?
