### ISSUE TITLE
GG Max - EXP Build - Whole Collectable system is very broken in current build

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4307]
As the title says, I know the collectable system is still very new, and had bugs, But the latest EXP build seems to of made it a lot worse.
Collectables mess up a lot when you try and change them in the editor, rename them, copy them etc.
The collectables file saves things that should not be there, and does not delete stuff that is removed from the game.

After testing it on a few simple things just now, I found that even moving collectables from inventory to hotbar etc, then back etc, was having problems now.

Very unstable.

**Comment by Tum1370** [comment]
Look at this screenshot of a collectable file.
I have actually only created 1 collectable in this very simple RPG Test level.
The collectable i created was a "Healing Potion Recipe"
Yet the file is already very messy with a load of items added, for no reason. I know they are all weapons. But these are weapons that i have not set as lootable, and are props, next to a weapon vendor that i was going to create.

This needs to be a lot more tidier than this.

![Untitled](https://user-images.githubusercontent.com/66874403/228606247-baccacdf-01cd-409e-bf72-2f26592b3e0d.png)

**Comment by Necrym59** [comment]
Thats been fixed as far as i can see

**Comment by Tum1370** [comment]
I think its still there, I have a small test woodland level, got 2 items colectable in it, First Aid box and a Body Armour.
And look how messy the file is, This is just after i created the file as well. It gets worse as you remove / add more collectables.

![1](https://user-images.githubusercontent.com/66874403/229348644-3a0a2f01-f12c-4b1f-8701-aacb29620fe0.png)

**Comment by plemsoft** [comment]
I can reproduce this and have assigned it to me :)

**Comment by plemsoft** [comment]
@Tum1370 This has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
@plemsoft Hi, Just tested a level in VR which has no collectables set. After testing the level this is the items file that got created.
Full off stuff on a level without any collectable even add.

![Untitled](https://user-images.githubusercontent.com/66874403/230329513-6f296cff-120e-43fd-bc88-a35f202d2de7.png)

**Comment by plemsoft** [comment]
@Tum1370 Is this a new project , old project will not recover ?

**Comment by Tum1370** [comment]
@plemsoft This was not a new project, but it also had no collectable files written, as i kept deleting them so they could be written again.
But like i said, there was no collectables even on this RPG Test level.
I have another shooter test level, where the collectable files is written correctly now.
I will close the other issue similar to this one, but leave this one open for a short while to test it a lot.

**Comment by Tum1370** [comment]
@plemsoft Hi, This collectable system is still very messy. I have a small RPG Test level with a recipe for a Healing Pot with some resources. But when i created the collectable i made a slight mistake on the recipe ingredients. So i changed them in game. 
That still didnt work, even though it updated the file to the new ingredients, the recipe did not work.
So i deleted the old recipe from the file, and then re added it using the game and creating collectable.
After reloading the game, the old recipe was then created again in the file.

Seems very messy. And still the new recipe did not work at the crafting table.

For me, this collectable system seems very buggy in its present state.

**Comment by Tum1370** [comment]
@plemsoft I will close this issue, I think its already been fixed now. Thanks
