### ISSUE TITLE
Save game cleared all assets from scene.

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#4308]
So i was working on a test scene. put a good 20 - mnutes in and went to save the level. The level saved but every single asset I had places just vanished as if I had never put them there in the first place. 

A very quick redo to show as an example. Before save. 
![image](https://user-images.githubusercontent.com/95527550/227682328-e033cebe-811e-40e9-86fb-0903ee962a98.png)

After save

![image](https://user-images.githubusercontent.com/95527550/227682378-b152758b-65ef-4ec6-99e4-8211d86cc1b3.png)

This hasnt happend to me before bit I thought I should report it

**Comment by davetgc** [comment]
#4275

**Comment by SampeyFS** [comment]
yes me too

**Comment by plemsoft** [comment]
@42Pix3ls Thanks for reporting this issue, this has been fixed and will be in the next EXP build :)
