### ISSUE TITLE
Black Weapons under dynamic lights

### ISSUE THREAD

**Issue by ghost** [TheGameCreators/GameGuruRepo#431]
Hi guys, 
I'm working to a game set inside of a building with a dark setting and based only on dynamic light. So using only the LUA's control I hided those elements earn fps. The problem is that whichever weapons, also the bought one in the Dlc of AI ERRANT, under a dynamic light result completlely black but before dx11 they worked.
I thought that the Monster update had resolve that bug but It didn't.
Attached a video to explane you the problem but I can't allow to raise the brightness of the level because I will ruin the atmosphere. There Will be the possibility ti Hide the brightness of the weapon without light up the rest because eith this problem it's impossibile made a game with weapon in the dark. Is the only one bug that Will not allow me to publish my project.
I use in setup pbroverride=0
Sorry for my english.

Video to show the problem: https://youtu.be/ntI6qvtayTM

**Comment by plemsoft** [comment]
Thanks for reporting this,

Tested this and pbroverride=0 and pbroverride=1 seam to produce the same results now, but you are also able to control this using "boostintensity" in gunspec.txt.

Try to set:

boostintensity=50

You can raise this value until you get the results your looking for.
