### ISSUE TITLE
selection of weapons

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#4312]
I noticed a bug. The player cannot take more than one weapon. Other weapons disappear, but they cannot be retrieved

**Comment by davetgc** [comment]
Can anyone else confirm this please?

**Comment by synchromesh62** [comment]
Confirmed not working in the latest exp

**Comment by plemsoft** [comment]
@Denis87z @synchromesh62 Are you loading the level from the "Game StoryBoard" ?

**Comment by LeeBamberTGC** [comment]
@Denis87z When you collect a second weapon of the same type, look in your inventory main panel. The system is designed to hold duplicate weapons in your main inventory rather than clutter the hotkeys panel with duplicates.
