### ISSUE TITLE
mission bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4313]
when you put the different missions you write one then when you go to put the other missions it deletes the first one you put so it does the first mission you can't do other missions it always deletes the first mission

**Comment by Necrym59** [comment]
Your not using it correctly

**Comment by LeeBamberTGC** [comment]
@SampeyFS Many fixes to the quest systen. Try the next EXP build with a fresh game project and two quests. Also check out RPG Template to see 4 quests on the go.

**Comment by Grogadog** [comment]
Lots of problems with collecting multiple items in quest scroll. Works okay with 1 item. change quest to two items but only have that first item in level - works okay. add another item, neither can be collected into quest. picked up and added to inventory though.

**Comment by Necrym59** [comment]
@Grogadog 
This is a known problem and is being looked into.

**Comment by Grogadog** [comment]
Ok, thanks.
