### ISSUE TITLE
GGMAX Bug (EXP Build) - "Game Elements" appear in standalone

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#4315]
As you can see from the picture, "Game Elements" appeared in the standalone, in addition to these around I also found the checkpoint and Win Zone one. However, this bug appears only when I enter the second level, in the first one it doesn't happen. 
![BugGGMAX](https://user-images.githubusercontent.com/103126963/227775508-4745d35e-eb6d-4539-9009-1d13b4946fa1.png)

**Comment by MonkeyFrogStudio** [comment]
I had this happen in a test game yesterday, too. Immediately on a one-level game.

**Comment by plemsoft** [comment]
Im able to reproduce so will assign it to me :)

**Comment by plemsoft** [comment]
@LukeTheLukeLTL This has been fixed and will be in the next EXP update :)
