### ISSUE TITLE
Recipe Save Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4316]
It does not save the recipe when you write it as soon as you return to the written recipe you find everything empty

First 

It does not save the recipe when you write it as soon as you return to the written recipe you find everything empty

After

![image](https://user-images.githubusercontent.com/108415264/227776605-f9c9a96e-0baa-4207-8741-7326b5ac5f06.png)

**Comment by Necrym59** [comment]
You havent set the Item Style = recipe

**Comment by SampeyFS** [comment]
I know it was a test to see if it saved

**Comment by LeeBamberTGC** [comment]
@SampeyFS Continuing on from my milk project, I changed the description to RECIPE and it saved fine, as I relaunched MAX and loaded the project and level, and the description was remembered:
![image](https://user-images.githubusercontent.com/35840583/231854217-6e608f00-68cc-4966-ba15-30dd4b37f556.png)

Check in the latest EXP build (uploading soon) as there have been fixes to icons and collectable items management
