### ISSUE TITLE
GG Classic: Music Volume not changeable

### ISSUE THREAD

**Issue by Captain-Perl** [TheGameCreators/GameGuruRepo#4317]
In the game menu there are options for graphics and sound settings. In the sound settings of the standalone version the user can regulate the volume of the music (default at 100%) at a horizontal control element. **But whatever the user selects there, the music volume remains the same: at 100%.**
This bug occured before and after the "Bugfix" from 20230308.

I have the music in some ambience zones which refer to their OGG-Files in a project folder unter audiobank/music. The music is played when the players enters the zone, but always at 100%.

I have even tried to use a script which should decrease the volume by changing it as per _SetGameMusicVolume_ command, combining it with an object (like Lees classic barrel) to give the user the possibility to lower the sound from within the game, but the engine did not react to the command; the music sound level remained the same. 
In contrast, changing it by _SetGameSoundVolume_ worked, but then all other sounds (footsteps, weapon sounds, NPC talk by PlaySound() etc.) lose volume, too.

So it seems to me that the engine sees ambience music as gamesound, not music.
Music has its own control setting and should by controlled by it. But we have a game sound control which does everything and a music control which does nothing.

I know there are bigger bugs around but this is annoying, particularly when a NPC has something to say and the music drowns it.

**Comment by AmenMoses** [comment]
The music system is separate, see music.lua for details.  The ambience zones do not use the music system.
