### ISSUE TITLE
Cant connect nodes

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#4318]
https://user-images.githubusercontent.com/107326667/227786592-19ff4129-728f-4125-9459-8e565158cc80.mp4

**Comment by davetgc** [comment]
Thanks for the video. This is working for me. Is anyone else experiencing this?

**Comment by SampeyFS** [comment]
both also does it to me I also confirm it

**Comment by janekste** [comment]
I also have this problem.

**Comment by SampeyFS** [comment]
they don't connect, they struggle

**Comment by plemsoft** [comment]
@CharleneMaure Could you zip this folder:
c:\Users\USERNAME\Documents\GameGuruApps\GameGuruMAX\Files\projectbank\TheLegendOfTheWest
And e-mail me a copy so im able to see the problem, e-mail: plemsoft@gmail.com , Thanks for your help :)

**Comment by plemsoft** [comment]
@CharleneMaure This has been fixed and will be in the next EXP update :)

FYI: After the update, you will need to click "Reset HUD Screens" and "Add RPG Screens" to fix your current project.
