### ISSUE TITLE
[GG MAX] Request / Improvement Recommendation VEGETATION SHADERS/GRASS

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#4319]
So after using gg max for a while and still not being satisfied with my results in outdoor areas, I coming up with this idea.

The Terrain and Vegetation doesnt "connect" with each other because I feel like there are different lighting methods going on for them.

I took a screenshot with normal vegetation:
![GameGuruMAX 2023-03-26 18-27-11-77](https://user-images.githubusercontent.com/35990507/227790095-565b05d4-5f58-416f-a55e-ad0f8da21f9e.png)

then I edited the image (partially) to simluate a brighter grass. And doesnt this look much better? 
I would really like to see a way to change the lighting or brightness of grass on the ground.
There has got to be a way of doing this. Please note that I only edited a part of the grass in that image:
![GameGuruMAX 2023-03-26 18-27-11-77 - Kopie](https://user-images.githubusercontent.com/35990507/227790153-20893141-3891-42fb-9875-b13ba3566dab.png)

**Comment by Ghost-l0l** [comment]
Yeah, that would be good to have (in classic too);
 Or even go 1 step further and make separate sliders to set brightnes/contrast for each type of objects separately, and then have one general slider on top of all of that 
 
So 1 slider for grass, 1 for entities, 1 for terrain and 1 for your gun on screen - in gg classic these are treated like 4 separate "layers" with different levels of brightness/contrast (controlled by different shaders)

Whole thing could work like mixing volume of audio tracks, where you can set volume for each track and then set general level of volume for the whole project

![image](https://user-images.githubusercontent.com/101792609/227792304-e0f140fa-e998-4538-91a4-4fc086689338.png)

**Comment by 42Pix3ls** [comment]
I belive it is not just the lighting but the fact that the trees are static while the gragra"plows in the wind" this is very disjointed and is really obviouse

**Comment by C4ever08** [comment]
Yea I agree does seem odd the grass is so flat or opaque compared to the grass ground texture, And with that grass and ground really don't match all that well as you can see here and Ive tried different grasses and terrain and ones always darker then the other. I like the idea for sliders 
![GameGuru MAX - Dietara fpm_ 2023-03-24 11_47_19 AM](https://user-images.githubusercontent.com/80596156/227800729-a5b6ec71-5567-4bf5-93aa-b920ef741839.png)

**Comment by Duchenkuke** [comment]
Same map, better image editing this time, added a fake "depth of field" effect and brighter vegetation.

NEW VS ORIGINAL GG MAX screenshot

[GameGuruMAX 2023-03-27 00-01-47-16](https://user-images.githubusercontent.com/35990507/227807738-e6468138-5658-4367-ab8f-7eb7ec5ffb44.png)

![GameGuruMAX 2023-dd-27 00-01-47-16](https://user-images.githubusercontent.com/35990507/227807775-468ed14b-1c1a-4099-90c5-d3a2f0afb3d7.jpg)

**Comment by MonkeyFrogStudio** [comment]
I wonder if part of the problem is this:

If you look in the grassbank folder, none of the images there have any surface maps. Without the surface map, MAX can't determine the grass's roughness and metallic values at all. You tend to end up with flat (color-wise) surfaces that don't really react to light well as a result.
