### ISSUE TITLE
[STORYZONE] Skip Video doesnt end sound associated

### ISSUE THREAD

**Issue by IvanErtlov** [TheGameCreators/GameGuruRepo#432]
That was already working 2 version ago.

**Comment by plemsoft** [comment]
In your storyzone lua scripts:
PlayVideo(e,1) , is blocking so try to change your scripts to something like this:
----
function storyinzone_init(e)
end

function storyinzone_main(e)
 if g_Entity[e]['plrinzone']==1 then
    PlaySound(e,0)
    PlayVideo(e,1)
    StopSound(e,0)
    ActivateIfUsed(e)
	music_play(1,1)
	music_set_volume(85,100)
    Destroy(e)    
 end
end
---

Just add the StopSound(e,0) after the PlayVideo , did it work ? :)

**Comment by plemsoft** [comment]
As i remember we fixed this :)
