### ISSUE TITLE
GG Max - EXP Build - Editor Bugged ??

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4325]
See these images where strange spheres, and blue line boxes appear within the editor when you move around the world.
![1](https://user-images.githubusercontent.com/66874403/227946672-ebce6943-b040-4a34-9e84-5e9cc0d9cb5a.png)
![2](https://user-images.githubusercontent.com/66874403/227946677-b706132b-0235-499c-918a-41eec4682507.png)
![3](https://user-images.githubusercontent.com/66874403/227946683-e18a8a4f-4311-4456-a799-434de2c5bcb0.png)

**Comment by davetgc** [comment]
@Tum1370 - If it happens again, please let us know. I wasn't disputing that it was happening, but we need to get as clear a picture as possible. If it's happening to several users then we can get a clearer picture.

**Comment by Tum1370** [comment]
I have reopened this. I thought it was not happening, but it is still happening.
All files verified. System restarted.
Max created new Documents folder and stuff, Started a new map, Moved around the editor and get exactly the same things.
Blue box lines, and these globes appearing.

Where abouts are Maxs setting files stored as i cannot find them in appdata folder anywhere ?

**Comment by Tum1370** [comment]
@davetgc  THIS DOES NOT NEED CLOSING< I REOPENED IT

**Comment by davetgc** [comment]
Is this happening to anyone else? As I'm not seeing it, I can't confirm the cause. 

I can obviously see from the screenshots that it's happening to @Tum1370, but the more information the better.

**Comment by Tum1370** [comment]
This issue has been closed, i have already reposted this issue

**Comment by plemsoft** [comment]
@Tum1370 This is debug info we use , you can use key E to toggle display of probes , and there are many other key combinations, but the problem is that you have enabled "Display Terrain Debug Mode" just uncheck that in Settings->Developer , this option is really only for internal debugging and you should really use it :)
