### ISSUE TITLE
1001 appearing in game

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#4329]
Uploading GameGuru MAX - 217.fpm_ 2023-03-27 16-54-22.mp4…

in most recent update

**Comment by davetgc** [comment]
What scripts are you using?

**Comment by CharleneMaure** [comment]
https://user-images.githubusercontent.com/107326667/228365461-a3334ecb-4da1-4b7f-b43f-70333a8ae51e.mp4

But reverting to an older version of gameguru max fixed the problem

**Comment by LukeTheLukeLTL** [comment]
I have also noticed this problem. I have seen it appear, for example, after you kill an enemy.

**Comment by davetgc** [comment]
Is this still an issue?

**Comment by CharleneMaure** [comment]
Might be an issue if update to a newer version

**Comment by CharleneMaure** [comment]
gone in recent exp build
