### ISSUE TITLE
Animated door not registering bullet hits after closing.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#433]
https://vimeo.com/296442799

Video shows the problem, standard door from the Fixtures folder. 

When closed to start with the door registers bullet hits, whilst open or after being closed it does not, even though neither the player nor the zombie cannot walk though it but as you can see from the video after being closed the  player can shoot the zombie through the door.

**Comment by plemsoft** [comment]
@AmenMoses Thanks for reporting this,

Just tested this with 4 different doors from the fixture folder , and all seam to work in the latest version.

Must have been fixed along the way, give it a spin in the latest beta :)
