### ISSUE TITLE
GG Max - The shop name ?? Cant seem to find anyway to change it from "The Old Witch"

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4332]
As the title says, How do we change the shop names ?
I checked the Trader behaviour, and no options for name ?
The character name doesnt make any difference to name.

**Comment by Necrym59** [comment]
![behavior](https://user-images.githubusercontent.com/95015657/229347033-9d368737-1d5e-41e6-bb20-ead20a641d14.png)
![behavior](https://user-images.githubusercontent.com/95015657/229347040-eb9de633-070c-4530-b1fa-d6e638c25f69.png)

You can change In the behaviour and behavior editor

**Comment by Tum1370** [comment]
Ok thanks, i think this needs to be easier though. No rush as only testing stuff currently.

**Comment by Tum1370** [comment]
@davetgc Closed issue ? Why ? This is not fixed. The option for naming a trader does NOT want to be hidden away in the behaviour editor. Please re open it or shall i just open a new issue ?

**Comment by Tum1370** [comment]
I have open a new issue regarding this. The Trader name is NOT want to be hidden away in the behaviour script / editor.
It is an Important part of a game and should be easily accessible.
Thanks

**Comment by davetgc** [comment]
It was closed as it isn't a bug. I'm not saying it couldn't be easier, but the priority is bug fixing in the run up to the V1 release. This feature works,

**Comment by Tum1370** [comment]
This is a major problem, Who wants every trader called The Old Witch, I have opened this again anyway
