### ISSUE TITLE
MAX - Custom Animations in Behavior Editor

### ISSUE THREAD

**Issue by OmnixiaDEV** [TheGameCreators/GameGuruRepo#4335]
Custom Animation for imported models are not showing in the Behavior editor Play/Loop Animation action.

Not sure if this is a bug, nonetheless the community suggest I report it.

**Comment by davetgc** [comment]
Do you have a sample model affected by this issue you can share?

**Comment by OmnixiaDEV** [comment]
I tried using a character creator model with the hammering_wall animation from the booster pack

**Comment by davetgc** [comment]
Thanks for the information.

**Comment by LeeBamberTGC** [comment]
@OmnixiaDEV When you select the PLAY ANIMATION behavior, remember to tick the DEFAULT ANIMATION lower down, this will use the animations you set into the model and you will find the animations waiting for you :)
