### ISSUE TITLE
Recipe saving bug 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4337]
it doesn't save when you write the recipe or product description you have to restart max and (( sometimes it works but it doesn't always save it)

**Comment by SampeyFS** [comment]
I did some tests I noticed that it saves but max doesn't read them

**Comment by DaveTGC2** [comment]
Is this the same issue you reported here? : #4316

**Comment by SampeyFS** [comment]
yes but I noticed one thing that saves but max doesn't read

**Comment by SampeyFS** [comment]
![image](https://user-images.githubusercontent.com/108415264/228323240-8768d595-6f51-4cab-a1a8-02fa2d254af2.png)

inserted this as you see is empty     Turkey Normal	GGClassic\Medieval\Turkey.fpe	imagebank\RPG\turkey_icon.jpg	Turkey Normal	30	15	shop2	turkey
