### ISSUE TITLE
GG Max - EXP Build - Hotbars and Player Start Position Weapon Cannot be dropped and Magnum Pistol has no icon

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4339]
As the title says, With the new Collectable system, If your player has a starting weapon that is assigned in the "Player Start Position", it starts to fault the hotkey system, and messes up the game.
You cannot changed the weapon position, You cannot put the weapon in to your inventory. You cannot drop the weapon.
The Magnum pistol, does not even have the icon in the latest build.

I think you need to update the "Player Start Position" as this seems to be the problem.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this is expected as the weapon that you add to the player start position, is not a level-object and cant be dropped , so it will be locked into slot 1.

Tested the missing icon , and it did work here on the latest EXP build , so not sure about that, could you try to show it in a video , that would really help, Thanks for your help :)

**Comment by Tum1370** [comment]
@plemsoft I will try and find out why sometimes i dont get the image in the hotkey, But now that you have that gun in hotkey 1, try and move it to hotkey 2, or try and move it to inventory. You will see the gun starts to mess up, and will not fire.
I am sure this happens with the other guns as well, if you try and move them from the starting position.

This is why i say, The Player Start Marker really needs updating, maybe dont give that gun at start or something, else it can leave a nasty bug for the player.

**Comment by Tum1370** [comment]
@plemsoft Ok after retesting this bug again. I Found out what messes the "Player Start Marker" weapon up.
If you pick up a collectable item, then place that collectable item in one of the hotkey spots, Then move that item back to the inventory. You will see the guns mess up.

**Comment by plemsoft** [comment]
@Tum1370 Sorry still cant reproduce it ? could you make a fpm using stock assets and email me the fpm so im able to test, Thanks for your help , e-mail plemsoft@gmail.com :)

https://www.youtube.com/watch?v=9r1N3hYRzME

**Comment by Tum1370** [comment]
@plemsoft 
Mine works fine with the weapons like that.
follow this.

Create new project, and delete HUD, add RPG huds.
Create blank level.
Add Magnum pistol starter weapon to player start marker.
Place "Golden Goblet" in front of player, change from Static to Physics On, Tick Is Collectable.
Add behaviour "Armour" so we can pick this up, else we cannot collect this.
Create collectable.
(Maybe save and reload to make sure collectable works)
Now TEST GAME

When looted golden goblet, place it in the hotbar anywhere.
Then move it back from hotbar to inventory.

Your gun is now messed up.

**Comment by plemsoft** [comment]
@Tum1370 This has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
@plemsoft Am glad you finally see the bug ? and was able to fix it.  Thanks, Ill close this issue now.
