### ISSUE TITLE
characters with explodable=1 doesn't explode when spawn

### ISSUE THREAD

**Issue by Dimoxinil** [TheGameCreators/GameGuruRepo#434]
1º you spawn a enemy with explodable  = 1
work ok
2º kill the enemy
kaboonn!! work ok
3ºSpawn the same enemy again.
He doesn't explode anymore.

An explanatory video of the problem:  [youtube](https://youtu.be/W1TrFGCDLgc)
and..
a zip file with the gameguru scene and all the necessary files.  [dropbox](https://www.dropbox.com/s/b47vcl6s7ss59rp/files.zip?dl=0)

**Comment by plemsoft** [comment]
@Dimoxinil Thanks for reporting this,

This has been fixed and are ready from the next update :)
