### ISSUE TITLE
GG Max - Building Editor is still bugged

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4340]
As you can see from the 3 screenshots.
I created the building in first screenshot and exported it to the map.
The second screenshot is the second floor of the building (From within the editor), and you can see the warehouse doors are in place correctly.
The third screenshot is testing the game, and the character running inside to the second floor. 
3 of these doors have moved. I did not go further so maybe even more moved.

![0](https://user-images.githubusercontent.com/66874403/228329191-4e9e5c4b-7f0b-41d6-97bd-f2931ed90884.png)
![1](https://user-images.githubusercontent.com/66874403/228329224-b68cda9b-9187-42c7-975b-254866b8233f.png)
![2](https://user-images.githubusercontent.com/66874403/228329267-bf64fbf7-f2ca-42bd-895a-0b91608899af.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you attach the original Building Editor save the project for this building, it will help with testing.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
I think thats all the files from this building.
[buildingeditor.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11100525/buildingeditor.zip)

**Comment by Tum1370** [comment]
@LeeBamberTGC  I have just tested this building again, and i realise something.
The doors that are out of place in the second level, are warehouse doors that have been opened on the ground floor ?

Am not sure whether this is actually a bug ? or a design fault ? What do you think ?

**Comment by Tum1370** [comment]
@LeeBamberTGC After my last comment regarding this issue, i tried to change this building to use normal doors on the inside levels, and the one warehouse door inside, has a wall above it. But as you can see from the images below, the first image is inside the building editor with the new design. The second image is after exporting the image and placing it in the level. 
The whole building has messed up after exporting, even though in the editor it looks fine.

![1](https://user-images.githubusercontent.com/66874403/228557200-d90fd055-7929-4c01-8a84-344d82e8781d.png)
![Untitled](https://user-images.githubusercontent.com/66874403/228557204-98bfeb0d-fdac-49ed-9cf2-14200773f767.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC I Just tried to create another building, Larger building, Lots of windows, 3 levels, doors. And once again, it has messed up.
Hot swapping certainly doesnt work for me, as in this building i noticed i misplaced a window when i placed the building in the level, After going back to building editor to swap it, and resave it, and export it, Nothing happened. with the one in the level, even though the one in the building editor changed.

I am trying to just create a big indoors building so i can create a closed proximity inside test for testing VR.

I have attached the files again.

[VRTest.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11109806/VRTest.zip)

**Comment by Tum1370** [comment]
Also look at these 2 screenshots. First one is showing the building placed in the level, with the out of place window that i was trying to remove.
The second screenshot i dont know what has happened. But all the windows have now changed to something different as you can see? I didnt really do anything and this happened.
This is why i say, the building editor is currently very buggy, and very hard to use, especially on large buildings.

![1](https://user-images.githubusercontent.com/66874403/228789271-d8e2e55c-be09-4ddb-808e-692a9494047c.png)
![2](https://user-images.githubusercontent.com/66874403/228789285-f09bcbaf-7efc-4794-b809-9d6d720ff5b1.png)

**Comment by Tum1370** [comment]
Some more information for you, hopefully to assist in finding out this building editor bug.
Look at this totally EMPTY level, that i placed the building that i created using the building editor on.
Look at the DETAILED OBJECT LIST. It is full of everything that was in the building, and it still remains in the level, even though the building is not even here anymore.



![1](https://user-images.githubusercontent.com/66874403/228793870-23c8e0eb-899e-4cfa-85b4-a2896b8fc9c0.png)
![2](https://user-images.githubusercontent.com/66874403/228793881-272caa8a-0dde-4344-8be6-746f7c8b3c1a.png)
![3](https://user-images.githubusercontent.com/66874403/228793889-04cd51a8-39b2-4c60-aedc-c64fe6695f71.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Lots of work on the BE and importing smart objects, many issues resolved. Try the EXP build with the new building creation and see if it stays intact, and is removed from the level and library when the last instance of it is removed from the level.

**Comment by plemsoft** [comment]
The windows/doors are they still "locked" after you deleted the building ? (last screen shot) ?

**Comment by Tum1370** [comment]
@plemsoft Yes, i just retested this same building, The placed the building, Locked it, Unlocked it, deleted it, This time it worked fine.
The second time, i locked it, unlocked it, deleted it, And all the windows / doors remained. They were ALL locked still and didnt unlock with the group.

**Comment by LeeBamberTGC** [comment]
@plemsoft I can handle this one now, just finishing off BE and smart object fixes, so already have this in my head, and will then look at group creation and management which is related :)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Working on this now, closed the other issue so we can keep things in one place. Should be an easy fix.

**Comment by LeeBamberTGC** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/35840583/229363721-cd501ae5-7487-43f6-a1c4-5e927c6edd3c.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 This scenario fixed for next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Just tried placing that same building from above, in the latest EXP build just gone live. And this is all i see now after placing it.
So i also went back to building editor, re checked the building, which looked good, then exported. And placed again. 
Same thing. Building is not even there, but i do see it as i try and place it, but it looks wrong, like missing windows and stuff.

Am not sure what youve done, but this looks bad, and doesnt even work at all now.
Screenshot 1, is the 3 storey building in the BE.
Screenshot 2 is whilst i am placing the building, you can already see the windows and stuff missing from building.
Screenshot 3 is Building after its been placed.

I have also attached the building files,


![1](https://user-images.githubusercontent.com/66874403/229369916-9eef0e8e-e7d1-4a73-8baa-35366d158584.png)

![Untitled](https://user-images.githubusercontent.com/66874403/229369844-f71e2881-bcdc-41de-b579-75566193a252.png)

![Untitled](https://user-images.githubusercontent.com/66874403/229369791-7c925d6b-e411-4d52-a498-bd59bdeac704.png)


[buildingeditor.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11132929/buildingeditor.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Yes, an unrelated fix caused this mess. New build up very soon :)

**Comment by LeeBamberTGC** [comment]
@Tum1370 New build up which solves this one.  If you are happy with this one, we can close this issue :)

**Comment by Tum1370** [comment]
Much better thanks, I really put this building through its paces by placing several, locking, unlocking, rotating, deleting, etc. 
After a load of trying i did manage to get one of the buildings to delete like this though.
But its a huge improvement, And even after trying again i didnt get this to happened again.

![Untitled](https://user-images.githubusercontent.com/66874403/229371677-d2878340-c9d0-4a31-a33b-cdeba1300fc0.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC Just had another really good go at testing placing this huge building. I only had it place wrong twice, Once it had no windows and doors, the other it had everything but the walls.
But like i said, i really put it through its paces and almost all times it places correctly, and deleted correctly.
Would you like me to close this one of for now ? 
I can always reopen it if i find there is a major problem still ?
See below they are all placed correctly, and ive really spun them around a lot and tested them a lot.

![Untitled](https://user-images.githubusercontent.com/66874403/229372050-34651ce5-e9af-432f-a6fb-ea24acc4669c.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Yes we will close this one and if you do get a scenario you can reproduce every time (so I can reproduce) then add it here and we can reopen this.

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok thanks, ill let you know if i see it happen more :)
