### ISSUE TITLE
Texture Trees Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4342]
![image](https://user-images.githubusercontent.com/108415264/228512268-97a0455f-1a11-42f5-afcc-f2252e7d2c40.png)

Problem present in plants that are placed by hand the light is too dense for the plant it causes the FPS to drop and it feels bad like this

**Comment by SampeyFS** [comment]
![Senza nome](https://user-images.githubusercontent.com/108415264/228512334-4258543c-d358-47c4-a23e-aafdec5f486a.png)

**Comment by davetgc** [comment]
Have you placed thousands of trees? MAX can handle a lot, but a huge forest will cause an FPS drop.

**Comment by MonkeyFrogStudio** [comment]
How are you placing a tree "by hand"? Can you explain the process you're using? Are you using the "paint" tool to paint in new trees? Or are you doing something else?

**Comment by SampeyFS** [comment]
No process I put the plant the texture is too light sorry but can't you see it?

**Comment by SampeyFS** [comment]
![image](https://user-images.githubusercontent.com/108415264/228568562-1b66dbf9-e7a1-44f2-9880-0f2a303edc33.png)

**Comment by MonkeyFrogStudio** [comment]
So, you're placing tree as an object, not via the brush used to paint trees on a terrain. Thank you.

I am definitely not getting that on my end. Here's in the editor:

![tree1](https://user-images.githubusercontent.com/36735507/228569917-ab7ec785-bee4-47fa-a384-56677e150760.png)

And here's the same in a test game:

![tree2](https://user-images.githubusercontent.com/36735507/228570061-45dcb6fd-99ee-4e8a-8d99-02822d83cc28.png)

**Comment by MonkeyFrogStudio** [comment]
And the same using the OAK tree:
![oak1](https://user-images.githubusercontent.com/36735507/228570885-dc94f5d2-948b-455e-b56c-3530aa229fd5.png)

![oak2](https://user-images.githubusercontent.com/36735507/228570898-73fba0db-6f6e-4d8d-8142-df94f9cfaa23.png)

**Comment by davetgc** [comment]
Can anyone else replicate this issue please?
