### ISSUE TITLE
GG MAX exp Scuba baehaivor - bug 

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4345]
the scuba baehaivor is not working 

https://user-images.githubusercontent.com/109030026/228617964-abee9590-8298-4c9f-833a-34528807c186.mp4

**Comment by davetgc** [comment]
By not working, is it because the player is starting to drown?

**Comment by Keepo1** [comment]
No It didnt work at the level i had deep wather and where it worked in earlier versions i tried it on my other map if it forks but it does not.

**Comment by Necrym59** [comment]
Tested here its working perfectly what version are you using??
