### ISSUE TITLE
GameGuru MAX - Issue - RPG Template Demo Uses Aztec Kit

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4346]
Currently, the RPG Demo Template demo uses several assets from the Aztec kit. If the end-user doesn't have the Aztec kit, then those assets are missing and the demo looks like this:

![rpg](https://user-images.githubusercontent.com/36735507/228648902-4cd126ad-59a4-445b-b870-6f39ce033a3d.png)

Notice the "witches" are missing, the wall's missing that the map is hanging on, etc. 

Since this is a demo that is to ship with MAX to show people who to use the RPG elements, it should only include objects that ship with MAX and not objects from kits that have to be purchased.

**Comment by Tum1370** [comment]
My RPG Template level looks like this to, but i do have the Aztec DLC installed, so i dont know why its not working correctly for me.

**Comment by MonkeyFrogStudio** [comment]
According to the screen shot you've posted, yours does not look like mine. For example, you have both "witches", I don't have any. You have the wall on the left side, I don't have that wall at all (that's why the paper is floating in mid-air). You have the item floating above the zone on the right-side. I only have a light there and no item. You have a large gold pot toward the center, I don't. Etc.

**Comment by Tum1370** [comment]
Ye sorry about that, after posting i checked, and put a EDIT on my post. 
Maybe its using assets from somewhere else as well ?
Like you say, they certainly need to update this to just use stock assets.

**Comment by davetgc** [comment]
There appears to be some confusion here that will need addressing.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Quite right, some of the objects are from the DLC.  I have updated the level to remove some of the dependencies, now only using the free Aztec items that come out of the box, and added a few Aztec items to MAX as well to keep the level flow intact.  Now in latest EXP build.

**Comment by MonkeyFrogStudio** [comment]
Thanks! I will test once it's out to the rest of us. :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC I still have missing elements in the RPG demo. And I also get the following error when I try to run a test game:

![error](https://user-images.githubusercontent.com/36735507/230794392-3d2708e9-3284-43da-9257-bd0c0a297ab2.png)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio With the latest EXP build uploaded now, can you reproduce this error and also send me the "RPG Template.log" file that reports which items are missing, thanks!  Before doing the test, best to delete all occurrences of RPG Template in the "GameGuruApps\GameGuruMAX\Files\projectbank" folder, and do a Steam verify so you have the latest -- Quest Poster v4.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC This is working now on my end. Removing the projectbank folder did the trick. Thanks! I'll close this now. :)
