### ISSUE TITLE
GGMAX Bug (EXP Build) - Collision Problems

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#4348]
I saw that you made an update to solve the collision problem, but in my case the problem was not solved. The collisions as you can see from the picture are not in the correct position.
![CollisionProblemGGMAX](https://user-images.githubusercontent.com/103126963/228669157-bf30531e-7f4c-40a2-902e-8894097dd693.jpg)

**Comment by MonkeyFrogStudio** [comment]
Are these custom models/models imported into MAX (i.e. not from MAX's collection or any of the booster packs?

**Comment by LukeTheLukeLTL** [comment]
> Are these custom models/models imported into MAX (i.e. not from MAX's collection or any of the booster packs?

Yes, they are models that I downloaded from Sketchfab

**Comment by MonkeyFrogStudio** [comment]
Are these models freely downloadable? Or can you share them (I can provide an email and promise not to use them)? I think it may be the model (it's origin/center of gravity), and not MAX, that's causing the issue.

**Comment by plemsoft** [comment]
@LukeTheLukeLTL Thanks for reporting this issue , could you e-mail me the model so im able to test , or if possible share a download link here, e-mail plemsoft@gmail.com , Thanks for your help :)

**Comment by LukeTheLukeLTL** [comment]
> Are these models freely downloadable? Or can you share them (I can provide an email and promise not to use them)? I think it may be the model (it's origin/center of gravity), and not MAX, that's causing the issue.

> @LukeTheLukeLTL Thanks for reporting this issue , could you e-mail me the model so im able to test , or if possible share a download link here, e-mail [plemsoft@gmail.com](mailto:plemsoft@gmail.com) , Thanks for your help :)

Yes I can send you the links here since they are not my models and they are free.
Here are the links: 
https://sketchfab.com/3d-models/old-chevy-van-low-poly-model-09d718c9cf72401b8534d265a06a803f
https://sketchfab.com/3d-models/80s-generic-police-car-low-poly-model-61766c1e6e1e4b2b803c174f33433a74

I downloaded for both of them the .gltf model.

**Comment by plemsoft** [comment]
@LukeTheLukeLTL This has been fixed and will be in the next EXP build :)

![physics-bug9](https://user-images.githubusercontent.com/18662417/228834616-cb0affba-58d2-4b1b-b4dd-ddb8d2f4f646.jpg)

**Comment by LukeTheLukeLTL** [comment]
I confirm that after the last update the problem has been fixed, i'm closing the issue now, thank you :)
