### ISSUE TITLE
XP Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4349]
![Senza nome](https://user-images.githubusercontent.com/108415264/228768470-de946ceb-440f-42ce-9ec3-7c3241cfbd9d.png)

As you can see from the photo XP have grown (( Without Doing anything))

**Comment by SampeyFS** [comment]
There is little to explain the XP went up by themselves without having done anything

**Comment by davetgc** [comment]
I've added an XP bar to my level, and I'm not seeing this. Are you able to make a video?

Can anyone else confirm this issue?

**Comment by PetrNaj** [comment]
> Can anyone else confirm this issue?

Yes.
I have five zombies and one rat on the scene.
IF I kill the zombie xp are fine.
If I kill a rat, the xp increases on its own.
My English is not good. I'm sorry

**Comment by SampeyFS** [comment]
Se spari con la pistola senza proiettili, falli fare clic così tante volte che vedrai l'XP salire allo stesso modo in cui sono arrivato al livello 4 solo facendo questo

**Comment by SampeyFS** [comment]
If you fire the pistol without bullets make it click so many times you will see the XP go up the same way I got to level 4 just by doing this

**Comment by plemsoft** [comment]
@SampeyFS Thanks for reporting this issue , this has been fixed and will be in the next update :)
