### ISSUE TITLE
FreezePlayer/UnFreeze Player

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#435]
I am experiencing some incredibly odd behaviors when using the freeze player and unfreeze player LUA commands. I'm using them as I have been able to reintroduce when zombies grab on to the player and bite him/her and the player is unable to move.

When the player is frozen and still tries to look around or move, once the player is unfrozen he seems to teleport all over the place. It is almost as if when you use the mouse look while you are frozen, the players view jumps to the new position when unfrozen, despite the camera not moving while frozen.

**Comment by korodai** [comment]
I disabled the mouse while frozen and the player didn't move when unfrozen.

**Comment by AmenMoses** [comment]
I've never seen the freeze/unfreeze working in any build, I just stopped trying to use it as it plays havoc with Lua.

**Comment by Teabone3** [comment]
I'll try adding some code to disable the mouse while the player is frozen to see if it prevents the mouse-look data from happening.

Perhaps there is a better way to freeze the players movements?

**Comment by korodai** [comment]
DeactivateMouse() and then ActivateMouse()

**Comment by ViperSmoke** [comment]
> DeactivateMouse() and then ActivateMouse()
> 
> Actually my script looks like this:
> ActivateMouse()
> FreezePlayer()
> DeactivateMouse()
> UnFreezePlayer()

Perfect thanks.

**Comment by Teabone3** [comment]
Thanks guys I will try that. Since the only issue I'm dealing with is the mouse look. 

The issue with the teleporting was happening when calling freezeplayer and unfreezing too frequently. So ive got that part avoided now no problem.
