### ISSUE TITLE
Question Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4350]
![image](https://user-images.githubusercontent.com/108415264/228785900-2425c45c-7f0d-44b6-bb1d-368ccf609822.png)

**Comment by davetgc** [comment]
It think that is what I'd expect to happen, but I'll flag it up as confusing.

**Comment by Necrym59** [comment]
Thats an old version of the quest huds, they have changed since this one should close this issue

**Comment by davetgc** [comment]
@SampeyFS  Can you please check that you are on the latest Release Candidate build as I also believe this is fixed.

**Comment by SampeyFS** [comment]
I tested it does not work with many objects it only works with the key I have tried many but it does not give money it confirms the mission is over
