### ISSUE TITLE
Cancel button on quest hud screen confusing.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4351]
The cancel quest button featured in the live broadcast is confusing. It looks as if you click there to close the quest window. maybe change it to say Abandon?

**Comment by MonkeyFrogStudio** [comment]
It's user-define-able, right? So, the end-user should be able to change that to whatever they want.

**Comment by davetgc** [comment]
Yes, it could, but out of the box is seems confusing. It's just about giving the 1st time user the best experience in my eyes.

**Comment by LeeBamberTGC** [comment]
@davetgc Changed to ABANDON for next EXP build

**Comment by davetgc** [comment]
Thanks Lee,

I know it was only a small thing.
