### ISSUE TITLE
Reseting the RPG Screens adds random images to level screens.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4352]
![image](https://user-images.githubusercontent.com/99803873/228831115-18c4f6b9-e05e-4968-9617-909154c3c99f.png)

**Comment by SampeyFS** [comment]
yes Exactly sometimes you can't unhook the connectors

**Comment by davetgc** [comment]
Just to add to this, reloading the project restores the correct images.

I can unhook the connectors though. I've not been able to replicate that one.

**Comment by plemsoft** [comment]
@davetgc This has been fixed and will be in the next update :)
