### ISSUE TITLE
GGMAX Bug (EXP Build) - The light is on even when it's set to "Off"

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#4354]
As you can see from the photos, the light in the game stays on even when I set it to "Off." This problem is present both in the "Test Game" function and in the standalone.
![BugLight1](https://user-images.githubusercontent.com/103126963/228885474-3d17efee-2e68-473c-89f0-261624de473c.jpg)
![InkedBugLight2_](https://user-images.githubusercontent.com/103126963/228885805-48bdb26f-518e-4b75-966d-9b4c6f83cedf.jpg)

**Comment by MonkeyFrogStudio** [comment]
The light is off for me in test game when it's toggle is set to off. However, you should really connect this up to a switch via MAX's Logic Nodes so you have a means to turn it on (and off again).

**Comment by MonkeyFrogStudio** [comment]
Working here:

https://user-images.githubusercontent.com/36735507/228931476-c10f1193-a5f2-4e64-b823-a83df945f025.mp4

**Comment by LukeTheLukeLTL** [comment]
Here is the video, as you can see there is something wrong.
https://user-images.githubusercontent.com/103126963/228942264-19b6b968-0a56-44e0-b825-b4ae76657388.mp4

**Comment by MonkeyFrogStudio** [comment]
As you can see from your video, the switch and light are working. However, it's not initially off for you. But it does work. And, as you can see from my video, it does work properly.

I don't believe there's a need to until Switched On at the start. Basically, what you're doing is like a double negative. The lights off as default, but so is the switch. Instead, try having the light to off and the switch's Switched On ticked. This should (I hope) tell the script that the switch is ACTIVE and the light is OFF. When you flip the switch, it should then toggle the state of the light.

In any case, not sure why it's not working for you, because it is working just right for me, even if I do start it with the Switched On toggle unticked. But give that a try.

**Comment by LukeTheLukeLTL** [comment]
> Instead, try having the light to off and the switch's Switched On ticked.
> 
I have tried but still the problem remains. At this point I think it's a bug.

**Comment by MonkeyFrogStudio** [comment]
Might be. However, if it's a bug, I would be getting it on my end, too, right? Have you tried another light and switch to see what's going on? Have you saved and restarted? Just checking. :)

**Comment by MonkeyFrogStudio** [comment]
Are you on the latest experimental build?

**Comment by LukeTheLukeLTL** [comment]
> Are you on the latest experimental build?

Yes

**Comment by davetgc** [comment]
This is also working for me, can anyone else confirm either way please?

**Comment by LukeTheLukeLTL** [comment]
I tried the stable build and in that build the light works correctly, so it is a problem only in the EXP build.

**Comment by davetgc** [comment]
Could you please test this in the release candidate? You can access that via Steam in a similar way to accessing the EXP build. No password required.

**Comment by LukeTheLukeLTL** [comment]
> Could you please test this in the release candidate? You can access that via Steam in a similar way to accessing the EXP build. No password required.

I also tried the Release Candidate, and it did not solve the problem. This problem occurred about a week ago, so probably one of the last EXP builds corrupted something in my files.

**Comment by davetgc** [comment]
If you create a new map, does the issue persist?

**Comment by LukeTheLukeLTL** [comment]
> If you create a new map, does the issue persist?

Yes, even if I try in a new map the issue persists.

**Comment by davetgc** [comment]
Thanks for all the information.

**Comment by LukeTheLukeLTL** [comment]
Apparently I'm not the only one with this bug, as it had been reported before #4273

**Comment by plemsoft** [comment]
Im able to reproduce and will have a look :)

**Comment by SampeyFS** [comment]
Yes, it stays on for me too

**Comment by plemsoft** [comment]
@LukeTheLukeLTL Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by LukeTheLukeLTL** [comment]
I confirm the issue has been fixed, thanks for the fix :)
