### ISSUE TITLE
boot max bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4358]
![image](https://user-images.githubusercontent.com/108415264/229105581-02073012-fba9-4723-9678-46d250699294.png)

When you boot max it always goes into this it's so much that this does it every boot it does

**Comment by plemsoft** [comment]
@SampeyFS In settings make sure you have checked "Show GameGuru MAX Hub on Startup".

![showhub](https://user-images.githubusercontent.com/18662417/229127120-84078cbe-2a20-4e52-a775-1f88b31a9e53.jpg)

**Comment by SampeyFS** [comment]
OK, thanks a lot
