### ISSUE TITLE
GG Max -EXP - Is Collectable but has no script, How do we pick up the item ?

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4359]
Hi,
As the title says, If we make an item Is Collectable, Lets say "Golden Goblet", we change the item from Static to physics On, Tick Is Collectable.
But without adding a behaviour, We cannot pick this item up ?

I know we could add Health, or Armour or something.

What behaviour are we suppose to use to just pick up the item, without adding health or armour etc ?

**Comment by fearlesswee** [comment]
I think it'd make sense for TGC to include a "junk/misc" behavior that exists solely to facilitate the "pickup and store in inventory" logic with no kind of special "use function" attached. I imagine it'd be pretty easy to make yourself in the meantime by copying one of the other "pick up" type scripts and just gutting the part that gives it the spell/health/mana functionality.

**Comment by Necrym59** [comment]
There is one its called collect_object but its not in the build yet

**Comment by Tum1370** [comment]
@Necrym59 @davetgc I will close this issue now, as like you have pointed out, The script is there, Just not been released yet.
Thanks
