### ISSUE TITLE
Zombies not dying ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#436]
Zombies are not always dying they just stand there with the walking animation or just stop with the walking animation randomly … Reported on steam and I can confirm …

**Comment by Pirate-Myke** [comment]
https://youtu.be/hKbtcW29EOE
A video of the issue with debug on. Maybe this will help.

**Comment by Pirate-Myke** [comment]
[ZombieTestMap.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2521730/ZombieTestMap.zip)

Here is a test map for you Lee.

**Comment by Suspeksorium** [comment]
Here is the fpe file you are asking for. 
I hope i can help with that.

**Comment by Suspeksorium** [comment]
Yes, all the Zombies i try got the same problem.

**Comment by AmenMoses** [comment]
It's because the Zombies are trying to roll and crouch but don't have animations to support it,  The AI modules need to differentiate between characters that have the appropriate animations and those that do not and modify the behaviour appropriately.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Video supplied and information above … Note this seems random..

**Comment by LeeBamberTGC** [comment]
The "ZombieTestMap.zip" actually revealed a different issue to the one supposed. Seems when CAMERA LOCK is on, the shotgun cannot cast a correct ray from the third person character to the enemy (it shot it into the floor).  Once this fix was made, zombies could be shot and damaged in the supplied level without any animation issues.
