### ISSUE TITLE
GG Max - EXP - When armour takes damage message only shows on screen for a fraction of a second.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4360]
As the title says, If you setup a armour, and then that armour takes damage after you get hit.
The message     "Armour protected you! Only " .. damage .. " damage got through"  only shows up for a fraction of a second, and is barely readable.

**Comment by plemsoft** [comment]
@Tum1370 This has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
@plemsoft I just tested this on the latest EXP build. The text does stay on a little better, but still its very quickly.
It is still less than a second, and if i blink i could easily miss it.

**Comment by plemsoft** [comment]
@Tum1370 Ups sorry somebody forgot to include it in the update , but will be in next :)

**Comment by Tum1370** [comment]
@plemsoft Just downloaded the latest EXP build and can confirm this bug is now fixed. Thanks. I will close this issue now.
