### ISSUE TITLE
GG Max - EXP - HUD Button + and -      (How do these buttons work ???)

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4361]
As the title says, In the Player Skills HUD screen, you add buttons next to the Global Variables, and then for that button you select "Return button to LUA"
But all of these 4 buttons on the premade HUD screen are identical. They all return Button to LUA.

How are these buttons tied to a particular stat ?
Even if i move the buttons around, they still add to the stat that they are originally next to.

Very hard to understand without any kind of explanation ?

![1](https://user-images.githubusercontent.com/66874403/229131776-431209d3-b969-46cd-9ca5-c9f0f4c7af41.png)

**Comment by Necrym59** [comment]
These + buttons are connected to a variable to increase the value. To see the connected variable select the + button and uncheck the Hide Text box. The + button text field will be shown and shows you the connected variable.  You can change the text to AWARD:xxx where xxx is the name of your global user-defined value you wish to increment with the + button.

**Comment by Tum1370** [comment]
@Necrym59 Thanks for this, i didnt realise the Hide Text was actually hiding an option.
Ill close this one now as its been explained.
Thanks
