### ISSUE TITLE
GameGuruMax 5. issues - character animation/character conection/Scuba/Inventory/rpg scren values

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4364]
i have found 5 issues which you can see in the video and description below.

[https://www.youtube.com/watch?v=QChqhJsbWNc](url)

starter animation - plays all animation and not the selected one
logic conection - conected characters dosent react
scuba behavior - not working
inventory - icons/values/conected containers are reset to default after saving the project
storyboard - in RPG screens when you change the value of something, it does not change the value

**Comment by davetgc** [comment]
Can you please report these as separate issues, and please use search before posting, to check that these issues haven't been reported before.
