### ISSUE TITLE
MAX - More precise/better pickup/collection mechanics

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#4365]
This problem wasn't a *huge* issue with the strictly "barebones FPS" game target of GGC/GGM in early days, where there was never a reason to *not* collect an item lying around, but now with the addition of RPG logic, including many types of items littered about that a player may or may not want to collect, the basic collection mechanics that solely check for distance to the player object feels out of place and sorely outdated. Here's an example scene:

![image](https://user-images.githubusercontent.com/56294129/229225639-825c2619-b87a-483f-9cff-cec29d29657a.png)

This is a shelf of various items. Let's say for example that the player wants/needs to collect the purple item, and doesn't want/need the other items on the shelf cluttering up their inventory. With the current collection/pickup mechanics, it is **impossible** to only collect the purple item; you will collect every single item on the shelf. (Granted, with the current infinite inventory this is a minor annoyance, but in the future when limited inventory styles are added such as my earlier suggestion of #4334 it would be a much bigger hinderance to gameplay.)

Ideally, pickups should be handled something like the Fallout/Elder Scrolls series, where you are only prompted to collect an item when you are directly looking at/near it, and you can only ever be prompted to collect a single item at a time. (Since as in my example scene, if it only detected the rough angle the player was looking and didn't prompt for a single item at a time, the player might accidentally collect the yellow items behind the purple item, which they do not want.) 

![image](https://user-images.githubusercontent.com/56294129/229226725-1ebbbc2c-4b6c-46b5-a439-16fac7ec11a6.png)

With the addition of RPG game support, which often feature many types of various collectible items placed around an environment, some of which might be junk that only exists to be sold, some might be valuable healing items, others still might even be quest-essential, it makes sense for the pickup mechanics to be made far more precise than they are currently; otherwise we would be forced to arbitrarily have items placed widely apart, which would look rather jarring and game-y. (Imagine walking into a dungeon to find loot, and each and every item has it's own little "pedestal" each placed 10 feet from one another just so the player can actually ensure they only pick up the items they want; it'd look very artificial and strange.)

**Comment by Necrym59** [comment]
Already done and awaiting to be included into a exp build

**Comment by fearlesswee** [comment]
Going through some of my older issues, closing this one as the items have been switched over to a "precise" system for quite a while now.
