### ISSUE TITLE
Bug delete object

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4366]
The problem when you delete the object and put it back is still present even if it doesn't save the Recipes and the things you write

**Comment by davetgc** [comment]
Is this the same issue as this? #4367

**Comment by SampeyFS** [comment]
It is useless that you always write it if it is not corrected I write it

**Comment by davetgc** [comment]
I need to know if you are just reporting the same bug many times.  If you are, please don't. You can edit your old reports if you have new information.
