### ISSUE TITLE
Bug Save Recipe

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4367]
![Senza nome](https://user-images.githubusercontent.com/108415264/229272992-585682e9-f1b5-4c8b-9b7d-8bf1adc12a6a.png)

All the work done Yesterday I find myself with nothing, it seems the time has come to solve the problem

**Comment by davetgc** [comment]
Just to confirm, are you saying that the recipe information isn't saving?

**Comment by SampeyFS** [comment]
yes it doesn't save anything if you do it from the beginning save the beginning that's enough

**Comment by davetgc** [comment]
Thanks.

**Comment by plemsoft** [comment]
@SampeyFS Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by SampeyFS** [comment]
Thanks to you I report what I find

**Comment by MartinCranshaw** [comment]
Recipe still not saving sadly. crafting unusable.

**Comment by SampeyFS** [comment]
the problem has been solved only that if they do not publish the update we are always there that does not save friend

**Comment by MartinCranshaw** [comment]
Thanks, Looking forward to it.
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you
