### ISSUE TITLE
objects disappear

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4371]
Sometimes the objects you put in max disappear, it happened to me with the mission script

**Comment by davetgc** [comment]
Hi, can you please describe what you're doing when these object disappear. Thanks.

**Comment by SampeyFS** [comment]
I put a wall I saved it disappeared

**Comment by davetgc** [comment]
Is this the same bug your reported here: #4275 and was also reported here:  #4310? I need to ask to avoid repeated reports.

Are you using the Release Candidate build? As in report  #4275, it is reported as fixed in that build.
