### ISSUE TITLE
Black screen when launching GGMax, then crash

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#4373]
Hello! Since almost a month, I am getting a black screen for a few seconds when launching Max before it closes itself (only the loading screen appears). I tried reverting back to a to the December release (I was in the exp build) and I still had the same issue, even though it used to work before in the same build. If I remember correctly, GGMax crashed while I was changing some the settings of a weapon, and since then I had the black screen problem. I also tried verifying files, re-installing Max completely, removing all assets that aren't in GGMax by default (I had GGClassic assets), and deleting the .fpm and .lst files of the level I was working on when the engine crashed. Any help? Thanks!

**Comment by davetgc** [comment]
Can you please post your system specs. Thanks.

**Comment by waterdrinkingfox** [comment]
RTX 3060 Laptop
Ryzen 5600h
16GB of RAM

**Comment by waterdrinkingfox** [comment]
Hello. Is there any news on this issue? It's been more than a month and I still cannot continue any projects... If it could be of any help I've also tried standalones and they work correctly, just the editor doesn't work.
