### ISSUE TITLE
All characters set as enemy playing loud sound effect on Death animation 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4374]
As the title states 
All characters set as enemy playing loud sound effect on Death animation,
Apparently this may be linked to the RPG ?
Im just loading a default blank map and it happens.

**Comment by MonkeyFrogStudio** [comment]
Experiencing that here, too. So, can confirm.

**Comment by plemsoft** [comment]
@LeeBamberTGC This is the Level Up sound , we need a way to disable the hole "XP" system , how do you suggest i do this ?

In Lua _G["g_UserGlobal['".."MyXP".."']"] is always "nil" when you start, so cant check that.

Perhaps add a (H) Hidden global with "MyXP" , so we can check if its nil and just ignore the hole level up system then ?

Let me know :)

**Comment by LeeBamberTGC** [comment]
@plemsoft Anything related to the RPG/QUEST system and scripts, assign to me and set to HIGH.  I have a lot of files at this end being modified daily so I can handle those in due course.  I agree the system should detect if the RPG HUD elements are not being used and disable the RPG sub-system running in HUD0.lua.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Next EXP build avoids the RPG mechanics if none are added to the game project, including the BOOM XP upgrade
