### ISSUE TITLE
Bug XP

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4375]
If you shoot the gun with no bullets just make them click so many times you will see the XP go up the same I got to level 4 just doing this

**Comment by SampeyFS** [comment]
https://user-images.githubusercontent.com/108415264/229364010-4fa3c5e3-3844-41ff-bbf7-dcd6ebcdeeaa.mov

Video I managed to make a video I hope to be of help to you congratulations for everything btw

**Comment by plemsoft** [comment]
@SampeyFS Thanks for reporting this issue , this has been fixed and will be in the next update :)
