### ISSUE TITLE
Bug Animals  script

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4377]
![image](https://user-images.githubusercontent.com/108415264/229348863-1cd400c4-5b54-4031-8e74-aa6856549b4f.png)

putting the animals comes out this script error of foxes, rabbits

**Comment by AmenMoses** [comment]
Are all the animals set to always active = yes?

**Comment by SampeyFS** [comment]
yes

**Comment by davetgc** [comment]
I'm not getting any errors, but they aren't doing anything now. They just sit there.

**Comment by synchromesh62** [comment]
> I'm not getting any errors, but they aren't doing anything now. They just sit there.

Same here . .No anims nothing, just statues

**Comment by SampeyFS** [comment]
I've got the script set up if you want I'll pass it

**Comment by AmenMoses** [comment]
I wrote the darn thing!  🤦‍♂️

Used to work fine so something in MAX has changed along the way.

**Comment by AmenMoses** [comment]
Right so someone has altered the script since I wrote it, my line that used IntersectAll has been commented out and instead it now uses IntersectStaticPerformant.

I have no idea what that function is but it is always returning 'nil' so they cannot move.

They are animating for me though, just running the idle animation all the time.

Undoing that change makes them work again.

**Comment by SampeyFS** [comment]
Thanks friend

**Comment by AmenMoses** [comment]
@davetgc Maybe rename this issue to IntersectStaticPerformant (whatever that is) not worky?

**Comment by SampeyFS** [comment]
I tried it, in fact, they still block, the writing also comes out with this that you put in the zip

**Comment by SampeyFS** [comment]
an update is out now what has been changed?

**Comment by AmenMoses** [comment]
I'm not getting that script error so haven't a clue what is causing that.

**Comment by SampeyFS** [comment]
Maybe the skunk is an animal because he's caught stuck and the others go

**Comment by SampeyFS** [comment]
put lots of rabbits, skunks and foxes and see what it does

**Comment by AmenMoses** [comment]
They all seem to work fine except the brown sewer rat, that one is broken for some reason.

**Comment by SampeyFS** [comment]
ah that's what it is then

**Comment by AmenMoses** [comment]
Not getting any Lua errors though.

**Comment by SampeyFS** [comment]
ask small he had helped me on this mistake maybe he remembers what it was

**Comment by AmenMoses** [comment]
Well it's working fine for me so not sure what to ask him!

**Comment by SampeyFS** [comment]
No that writing comes out

**Comment by AmenMoses** [comment]
I'm not getting any writing!

**Comment by SampeyFS** [comment]
I removed the mice it doesn't do it anymore they are the ones that cause the script to crash

**Comment by AmenMoses** [comment]
What mice?  

The black sewer rat works fine but the brown one has issues, think the animations might be dodgy.

Anyhow:  https://vimeo.com/814040749

**Comment by SampeyFS** [comment]
Hello

**Comment by SampeyFS** [comment]
Uploading 20230402_210442.mov…

**Comment by SampeyFS** [comment]
https://user-images.githubusercontent.com/108415264/229373737-4e560db9-683c-4001-a4d9-c04ca502879e.mov

**Comment by SampeyFS** [comment]
No it still seemed to go instead it crashed as you see in the video

**Comment by AmenMoses** [comment]
Notice that after the error showed up you still have a rabbit running around?

That indicates that you have multiple versions of the script present, make sure any old versions are deleted and only the single working script is present in the scriptbank/animals folder (both in the Steam MAX folders and in your Documents area).

**Comment by SampeyFS** [comment]
[mammal_generic.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11133112/mammal_generic.zip)
This doesn't crash had smalling helped me but I don't know what it did try see the lua if you can understand yourself

**Comment by AmenMoses** [comment]
Also make sure all mammals are set always active, by default they aren't for some reason (they are also set as enemies by default, don't know why)

**Comment by AmenMoses** [comment]
The reason smallg's version doesn't crash is because it avoids the problem that is caused when you don't have them always active!

But if they are not set always active then they won't be properly initialised anyhow.

**Comment by SampeyFS** [comment]
where do I have to change can you show me thanks

**Comment by AmenMoses** [comment]
[mammal_generic.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11133143/mammal_generic.zip)

Here is one which will work even when they are not always active.

To set the always active flag select the critter and:
![always active](https://user-images.githubusercontent.com/35708338/229374808-33b4e833-2cda-473d-9acd-cc53dec85bd5.png)

**Comment by AmenMoses** [comment]
So in summary:
1) The IntersectStaticPerformant Lua function doesn't appear to be working in MAX for some reason.
2) The critters fpe settings are wrong.   They should be defaulted to always active=yes(*) and probably to be neutral rather than enemies(**).
3) The brown rat model has something wrong with it, i.e. it doesn't work whereas the brown rat does!

(*) This is so when the player looks down into their plush valley full of wildlife they are not all just stood around like statues, and more importantly so when they are moving they don't suddenly just freeze when an arbitrary distance from the player (but still well within view distance!), especially important in the case of birds.
(**) Otherwise they are going to all show up on radar/map displays by default, probably only wanted by users in special cases rather than as by default because critters don't ever attack the player!

**Comment by SampeyFS** [comment]
oh got it

**Comment by AmenMoses** [comment]
Aha, IntersectStaticPerformant may actually be working but it doesn't pass back 0 reliably, in most cases it is returning nil, I seem to recall the other Intersect function used to have this problem in GG.

So here is yet another version that allows for the nil return (and assume the function actually works).  If anyone finds that with this critters run through walls or whatever then we will know why.

[mammal_generic.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11133212/mammal_generic.zip)

**Comment by SampeyFS** [comment]
okay thanks

**Comment by SampeyFS** [comment]
now it works well hopefully thanks it is better to update the program to put this that works

**Comment by davetgc** [comment]
Thanks for all the information.

**Comment by plemsoft** [comment]
@AmenMoses New script working perfectly! Thanks for the help :) , added for the next update.

**Comment by SampeyFS** [comment]
![20230409213239_1](https://user-images.githubusercontent.com/108415264/230793051-c6a9117d-f168-40b7-a402-cbaa61d71e17.png)


The animals as you can see in the photo are all still like statues @plemsoft

**Comment by plemsoft** [comment]
@SampeyFS Yes i see fixed for the next update :)

**Comment by SampeyFS** [comment]
![image](https://user-images.githubusercontent.com/108415264/231518317-b281ca39-0347-4c63-95e7-26e6fa9439cc.png)


it still crashes nothing is fixed  @plemsoft

**Comment by davetgc** [comment]
@SampeyFS - Just looking at the map/radar in your level. How many characters/objectives do you have active at one time? I'm wondering if this is part of the reason for many of your crashes.

**Comment by synchromesh62** [comment]
Right now they only work for me on flat terrain \ blank Level

**Comment by SampeyFS** [comment]
animals are

**Comment by SampeyFS** [comment]
why animals and people are placed as allies does the same see them as enemies?

**Comment by SampeyFS** [comment]
![Senza nome](https://user-images.githubusercontent.com/108415264/231541659-eb85ccbc-cb74-4676-b516-3ceb7667ffd1.png)

**Comment by plemsoft** [comment]
@synchromesh62 @SampeyFS This has been fixed and will be in the next EXP update :)
