### ISSUE TITLE
GG Max - EXP Build - BUG - RPG Traders shop names needs a option to change the name from "The Old Witch"

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4378]
Hi, Can you please fix the traders script, so that the name of the trader can be changed from "The Old Witch".
I know this can be changed by going in to the behaviour editor, and changing it there, But that is not very user friendly.

The name of a TRADER is a major thing and should not be hidden away in the behaviour script / editor.

The name of the trader should take the NAME of the Character that the Trader Script is added to ? 

EDIT: I am not sure why this is marked Enhancement, Really this should be a MUST, unless you want every single game made by Max by someone who cannot use behaviour editor, with a shop called "The Old Witch"

Thanks

**Comment by MartinCranshaw** [comment]
I deleted the 'Old Witch' text in the trader hud and replaced it with new text.

**Comment by Tum1370** [comment]
It doesnt change the Shop name, The shop name is locked in to the trader script.

**Comment by MartinCranshaw** [comment]
It works for me...[image: trader-hud2.png]
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by Tum1370** [comment]
Try having a second trader, and then see if the name is the same. You would have to have a new HUD screen for every single trader in a game.

**Comment by davetgc** [comment]
Having run some more indepth tests, I'm marking this as a bug. Thanks for the report.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed in next EXP build, new property in trader script to specify the shop title you see

**Comment by Tum1370** [comment]
@LeeBamberTGC Awesome, thank you for adding this. Just confirmed working fine. Ill close this issue now.
