### ISSUE TITLE
GameGuru MAX - Bug - Light Disappears When Multi-Select

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4380]
Started to see this today with the last builds - When I try to multiselect an object and a light, the icon for the light disappears. If I have a group that contains a light in it, if I click to select the group, the light disappears (just the icon, because you can still see the light being cast).

![light](https://user-images.githubusercontent.com/36735507/229378267-d70698c2-c78e-4118-8f60-09dc398229f6.png)

Here's a scene with three grouped objects, each a wall and a spotlight:
![light2](https://user-images.githubusercontent.com/36735507/229378293-17830a5f-390d-4d60-9057-50fce9951479.png)

After clicking to select the first group, the light disappears:
![light3](https://user-images.githubusercontent.com/36735507/229378301-3a2b8cfa-c413-4698-8ec7-9ea315969d6b.png)

When I click to select the second group, that light also disappears and the first one also remains invisible:
![light4](https://user-images.githubusercontent.com/36735507/229378312-5442456c-6633-4d5b-96e9-541242a1da78.png)

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by MonkeyFrogStudio** [comment]
Appears to be fixed. :)
