### ISSUE TITLE
GG Max - EXP Build - BUG - Heatlh Stat need updating like the other new stats.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4383]
As the title says, The old Health Stat system is not working now properly. 
The Health that you set on the Player Start Marker now seems to be the Maximum Health you can ever get to.

I noticed that there is a new Global called MyHealthInitial but this stat does not seem to do anything. You start with the HP that is set on the Player Start Marker, and this is the Maximum HP you can ever get.

We need to be able to have globals for the HP as well, like we do for Armour or Stamina.

We need a MyHealth, MyHealthInitial, MyHealthMax etc

I have a minigame, where i want my player to only start with 100 HP, so it can only handle 2 shots from a pistol.
Then around the map, there are 4 randomly spawned First Aid boxes, each giving a HP boost of 25 HP.
Therefore allowing the player to get upto a maximum of 200 HP, and be able to handle a few more pistols hits.

But in the EXP build, If you collect the First Aid box now, whilst your HP is set at 100, The HP never goes above 100 even after collecting a First Aid box.

So like i said, we need to be able to set these Health Maximum, And Health Starting values ourselves.

**Comment by davetgc** [comment]
I'm marking this as a bug as it's not consistent with other values.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed for next EXP build with RPG system refreshing player stats so maximum comes from MyHealthInitial (specified in the player stats HUD screen) and your start marker player health is the actual current health you start with:
![image](https://user-images.githubusercontent.com/35840583/231449080-7e0e0b9f-4f55-40db-b397-44fc707e420b.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC  Ok thanks

Wouldnt it be better having health the same as the other stats in game now ?
So like the following etc 

MyHealth
MyHealthInitial
MyHealthMax
MyHealthRegen

**Comment by LeeBamberTGC** [comment]
@Tum1370 Not for V1, we are feature freezing and fixing what exists now. There is a role for the Start Marker with some non-RPG health settings easier to find and change. Maybe down the road a unified system could make sense, maybe moving ALL the MyXXXX values into a central location away from the HUD editor.

**Comment by Tum1370** [comment]
@LeeBamberTGC Sorry to say, but this is not fixed for me to.
I changed the MyHEalthInitial stat to a maximum of 150, My playerstart marker had 100 hp.

I added some points to strength, and my HP jumped to 600 after 1 point, then another 100 each extra point i added.

**Comment by Tum1370** [comment]
@LeeBamberTGC Sorry to say this is still not fixed for me.
My PLAYERSTART MARKER HAS THE HEALTH SET AT 100    ( I WANT PLAYER HEALTH MAX AS 100 )
See screenshots.
Screenshot 1 showing stat "MyHealthInitial" Set at 100      ( SUPPOSE TO BE THE MAXIMUM HEALTH )
Screenshot 2 showing the skills page and look at what my health is set there, Even though MAX HEALTH is set at 100
Screenshot 3 showing my in game Health, above 100 because Health Regen is slowing ticking up. (THIS IS ABOVE MY MAXIMUM)
![1](https://user-images.githubusercontent.com/66874403/231826393-2c994615-a9e4-4736-9cbc-20e1b518147c.png)
![2](https://user-images.githubusercontent.com/66874403/231826406-dfde788b-8471-45aa-8fc6-ca2e823541d7.png)
![3](https://user-images.githubusercontent.com/66874403/231826414-a5ab191f-3195-4317-a74e-7e3819d1abe3.png)

**Comment by LeeBamberTGC** [comment]
" in the next EXP build"

**Comment by Tum1370** [comment]
@LeeBamberTGC Just tested this am i guess its working as you intended ??

I set my PlayerStartMarker to the Starting HP, which i want as 100
I set the MyHealthInitial to the Maximum HP i want which is 100.

Now when i tried adding a POINT to my player skills Strength, My HP Maximum goes up by 100.

So if i dont want my HP to ever go higher than 100 the only way to stop this is to stop players using the Points and Skill System ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 Eventually I will be enabling custom HUD0.lua scripts in the project bank so you can customise HOW the player stat skills system works, but for now if you want a fixed health maximum, just delete the player skills HUD screen from your game project, this locks out the player from adding points and using them.

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok thanks Lee, I will close this issue now as after testing it was working fine. 
Thanks

**Comment by Tum1370** [comment]
@LeeBamberTGC Hi Lee, I know i have closed this issue, but i have just found another bug regarding these Health Stats.
As above, we have said the
PLAYERSTARTMARKER = STARTING HP
MyHealthInitial = MAXIMUM HP.

That is working fine, but i just tested my Horseshoe Bend DEMO. I keep it updated so it will work for you when i resend it.
Look at the screenshots.

Screenshot 1 = Basic HUD on Storyboard (NO RPG ADDED HUDS)
Screenshot 2 = PlayerStartMarker setting for HP = 300
Screenshot 3 = In game player Health = 100 / 300

Now when i created this demo, my HP was the SET AMOUNT OF 300 on the PLayerStartMarker.
But now, because i have not added any RPG Added Screens to the Storyboard, The PLAYERSTARTMARKER is WRONG.

When playing i only had 100 HP, Where it should be 300.

Am guessing the problem here is,  MyHealthInitial = 100 (Even though this demo is not using that stat or RPG Screens)

![1](https://user-images.githubusercontent.com/66874403/232098073-80f698bc-e922-44c3-88dd-63d276766ff7.png)
![2](https://user-images.githubusercontent.com/66874403/232098084-d109b9c7-f6ed-4761-9767-06f3b0334177.png)
![3](https://user-images.githubusercontent.com/66874403/232098095-bbe63cd9-abbd-4d11-be4c-5c0855216952.png)
