### ISSUE TITLE
Cannot Select Lights if there is an Entity near the Light

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4384]
After newest update today I can no longer select lights if there is any entity near the light I am trying to select.
 Probably related to  #4380

To Reproduce > Open GGMax and drag in a wall or tree or whatever. Place a light in front of the model. Try and select the light. You will instead select the model that is behind the light. 

Video: https://youtu.be/ZFeNdBp7HqY

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Kitakazi** [comment]
Lord Preben it is nice to see you back. Thank you.
