### ISSUE TITLE
MAX - Error with the player

### ISSUE THREAD

**Issue by blackhat110** [TheGameCreators/GameGuruRepo#4385]
If my speech is incomprehensible, it is because I use an interpreter. There is no change after removing the lighting or recreating the player object. It's about the piercing white fog at the beginning of the game, as seen in the video: https://youtu.be/-FaOhyQppcA

**Comment by davetgc** [comment]
Thanks for the report.

Can you please post your system specs.

Is anyone else experiencing this? I'm not seeing it on my system.
