### ISSUE TITLE
Save project Deleted   Very serious

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4387]
max to cleared the buildings

I had put some buildings immediately after the end of the save the buildings I had put there disappeared max

**Comment by SampeyFS** [comment]
https://user-images.githubusercontent.com/108415264/229541044-d536cc1f-bd6d-4010-9760-1bd09b0a21ac.mov

watch the building disappear

**Comment by SampeyFS** [comment]
I found out what happens when you save it makes it invisible the problem is caused by the candle with the light because when you save it always puts the candle on and the building disappears i.e. it is invisible

**Comment by plemsoft** [comment]
@SampeyFS Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by SampeyFS** [comment]
friend just question it's already out update because I've been away 2 days   @plemsoft

**Comment by plemsoft** [comment]
@SampeyFS Sorry not yet, check when you get a steam update :)

**Comment by SampeyFS** [comment]
don't worry it was just a question good job you and the whole team

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks for confirming the bug fix :)
