### ISSUE TITLE
GG Max - EXP Build - BUG - Every Tree selection is always selected when going to Terrain and Trees.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4389]
As the title says, Every tree is always selected now whenever you go in to the Terrain Editor / Trees.
It use to remember your selection before.

Annoying after a reload of Max having to unselect every tree again, to place trees that you do want.

![1](https://user-images.githubusercontent.com/66874403/229597836-bdc980fa-7e45-4b01-ac71-6491db30dccc.png)

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
@plemsoft Just tested this bug in the latest EXP build and its been fixed, Thanks for the Fix, Ill close this issue now.
