### ISSUE TITLE
Drones error in Beta 30-10-18 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#439]
Drones fire a couple shots then drop to the ground although they keep firing ..
Sometimes they get up again after 10 seconds or so ?

I can confirm they are fine in the current Public Preview 
https://youtu.be/cMT4s45gg5M

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed as still broken.
Video supplied above

**Comment by LeeBamberTGC** [comment]
The introduction of duck and strafe logic to the main AI system caused drones to attempt (and fail) to duck. Added extra states so drones do not try to duck, restoring their hovering ability.  Will be in the next update.

**Comment by michaeloldman** [comment]
Awesome news Lee.
The drones used to proceed to move to the player once they became aware of his presence - will this behavior also work now?

OldFlak....

**Comment by LeeBamberTGC** [comment]
Yes, they detect you by sight within a range, then they will follow you. Now they do not squat on the floor, they can move unhindered. And the bomber drones explode when they are close enough to the player as a treat!
