### ISSUE TITLE
GG Max - EXP Build - BUG - Building Editor doors dont fully close.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4390]
As the title says, If you use a door when creating a building in building editor, After you have opened the door, If you press E to close the door, they never fully close now, as seen in the screenshot.

![Untitled](https://user-images.githubusercontent.com/66874403/229639477-a7c243ed-e876-405e-a01e-dc71e0d62d0c.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you give me the name of this door in the screenshot, thanks!

**Comment by Lemuripest93** [comment]
Already reported here #3846 and being worked on by Zak

:)
