### ISSUE TITLE
GG Max - EXP Build - BUG - Collisions Broken AGAIN

### ISSUE THREAD

**Issue by DarthPickles666** [TheGameCreators/GameGuruRepo#4391]
So I just loaded up a level to test which has been pretty much finished for the last month or two, I've ran tests on it perfectly fine with absolutely zero collision issues on any models. The Collision has been perfectly fine on this model for the last god knows how long, and out of nowhere, this is what is happening. I dont want to have to waste my time re-importing the model then have to import it into every level it features in. (Notice how every other model in the screenshot is perfectly fine)

![image](https://user-images.githubusercontent.com/101579658/229650180-ec601df2-b9a1-4cd9-b0a8-8578dde3082f.png)

**Comment by DarthPickles666** [comment]
I've emailed you.

**Comment by plemsoft** [comment]
@DarthPickles666 Thanks for your e-mail , this has been fixed and will be in the next update :)
