### ISSUE TITLE
Update issue back!

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4392]
https://user-images.githubusercontent.com/99803873/229713212-97e79d7c-2366-4b59-b603-e486b496b92b.mp4

The strange update issue has returned. MAX downloaded the update and now is trapped in a loop of pausing the update. 

@LeeBamberTGC - I'm thinking this might be related to new 3rd party content?

**Comment by plemsoft** [comment]
FYI: I had this some time ago, somehow on my system GameGuruMax.exe was in use, so a reboot fixed it for me :)

**Comment by davetgc** [comment]
I've had to reinstall, but that makes sense, although I couldn't see MAX running.

**Comment by LeeBamberTGC** [comment]
@davetgc @plemsoft Looks like a problem at Steam's end. I saw it myself while updating another of my Steam titles.

**Comment by davetgc** [comment]
This happened again today, but a system reset solved it. Really odd.
