### ISSUE TITLE
GG Max - EXP Build - BUG - Using a collectable does not use the sound media

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4393]
As the title says, If i loot a health pot, or an object that has sound attached when its used, It does not play that sound when the item is used from either the inventory or the hoykeys.

Example, If you just find a health pot, that is not a collectable, the health added sound plays when you pick it up.
If that same item is used from the inventory / hotkeys the sound does not play.

I have a body armour with a zipper sound attached when you use it, The sound plays fine when its not a collectable, but silent when used from inventory.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Updated sound in RPG Template level and sound now plays in AUTOMATIC from the level, and manually when USE is pressed in the inventory as a collectable object.  See Armour Crates for the test.

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just tested this issue on the latest EXP build. I have a body Armour which has a zipper sound attached to it.
Still when i use the body armour from inventory or hotkeys, no sound is played.

**Comment by Tum1370** [comment]
@LeeBamberTGC Hi, This is a brand new Project and Brand New Blank Level, I have attached both the project folder and the level.
1 table, 4 milk bottles, all suppose to do Health sound when you use them.
They are all set at collectables, and the RPG screens are added.
Test Play,
Pick up the 4 milk bottles
Open Inventory.
Clock one of the bottles, then USE.
NO SOUND.


[TEST PROJECT.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11224544/TEST.PROJECT.zip)
[TEST LEV EL.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11224546/TEST.LEV.EL.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for the level, fixed for the next EXP build, the script can handle the fact the WAV cannot be played as a 3D sound

**Comment by Tum1370** [comment]
@LeeBamberTGC Hi, I just tested this bug.
On the blank new level, i added 2 Milk Bottles, and My imported Body Armour.
My body Armour has a zipper sound .wav attach to it. It works fine and plays the sound if i pick it up normally.

Now when i make them all collectables, then pick them up. Then use them from my inventory.
The milk bottles made the Health sound.
But my armour made no sound at all.
Even though its there as you can see in the screenshot.

![Untitled](https://user-images.githubusercontent.com/66874403/231879146-f3419ccd-a563-460b-87b6-2f681c30ad8d.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC I just checked the file and its already a mono.
So not sure why it does not work. I have attached the sound file.
[Zipper Sound.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11226606/Zipper.Sound.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Just added to your project after placing this WAV in the audiobank user folder, and it worked fine:
![image](https://user-images.githubusercontent.com/35840583/231887766-f06c009e-7842-4bfa-940d-eff3db7a71d3.png)
![image](https://user-images.githubusercontent.com/35840583/231887803-880518c2-b5f0-4d66-8b26-6483e7413d34.png)
I have also attached the updated FPM level of my test:
[TEST LEV EL.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11226670/TEST.LEV.EL.zip)

**Comment by Tum1370** [comment]
@LeeBamberTGC I just downloaded that level, and tested it, but i get a lua error now when starting the game as seen in screenshot.
I even created a new level, added my sound to the milk bottle, but still get the same lua error.

Then i noticed there has been another update to Max, So i guess something is broken on latest EXP update.

![Untitled](https://user-images.githubusercontent.com/66874403/231902960-9c956433-b2bb-4f75-b0b4-b2f6cd91228b.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC Testing any level in any project gives me that same lua error.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Dude, you are too fast at testing!! Wamna be in the credits :)  Try new EXP build let me know if the error persists

**Comment by Tum1370** [comment]
@LeeBamberTGC I can now confirm that this bug is now fixed and working correctly. Thanks for the fix Lee :)
I will close this issue now.
