### ISSUE TITLE
GameGuru MAX - Hands Change Depending on Weapon

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4395]
If you have one of the Aztec weapons, like the Aztec dagger, and also use a gun, like one of the pistols, then when you switch between weapons, the hands/arms change:

![pistol](https://user-images.githubusercontent.com/36735507/229902905-75367075-0004-46ab-817e-040b960c71c4.png)

![aztec](https://user-images.githubusercontent.com/36735507/229902923-3d923396-4069-455c-9a0d-3f500366615b.png)

This looks really bad, especially considering the one set of hands is wearing gloves and the other is not.

I realize that melee weapons, like the Aztec dagger, were made to be used with the "naked" arms, but what if you want your game to include both types of weapons? 

I think effort needs to go into converting all the weapons over to the newer set of arms/hands. I know it's a lot of work, but it currently means that the end-user either cannot use certain weapons together or they have to accept that the player's hands change their appearance along with the weapon.

**Comment by Lemuripest93** [comment]
I think hand swapping will be part of the new weapon system Lee's been talking about in the broadcasts, it will be interesting to see if every single weapon will have to be swapped by end user, or a single pair of hands can be chosen and it gets applied to any weapon added to a game.

Would be nice to have some confirmation by one of the devs.

**Comment by davetgc** [comment]
The guns were created using the old system and are integral to the weapons. In future, weapons will include interchangeable hands. It's not really a bug, but a legacy model issue.

**Comment by MonkeyFrogStudio** [comment]
This is fixed with the new weapons system.
