### ISSUE TITLE
update

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4398]
After tonight's update it's 15 FPS

**Comment by davetgc** [comment]
What were you getting before?

Have you added anything to your levels? Are you able to show before and after results?

**Comment by SampeyFS** [comment]
45/50 after update a huge decalogue

**Comment by davetgc** [comment]
Can you provide screenshots of the same level and scene showing the drop in this and an earlier version?

I'm not seeing any drop, and I've test a number of levels.

Is anyone else seeing a significant performance drop?

**Comment by SampeyFS** [comment]
![image](https://user-images.githubusercontent.com/108415264/230311097-bd3db39a-1838-4b16-84d7-3ccfe3cbd557.png) Crash 4 FPS

**Comment by SampeyFS** [comment]
it has come down so much that it is karst as you can see
