### ISSUE TITLE
GameGuru MAX - Bug - MAX No Longer Removes Unused Objects from Level Objects

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4400]
As the title says. I've got a blank level where I tested a few objects, then deleted them and saved the level:

![levelobject](https://user-images.githubusercontent.com/36735507/230177537-8b155b02-b9fd-4c33-8537-739cd89902cf.png)

Also, as a result, if I add an object, delete it, save and exit, come back into MAX and add the same object back into the level and delete it, then you end up with TWO instances in the Level Objects area (see above).

**Comment by SampeyFS** [comment]
yes it does to me too I tried it before

**Comment by plemsoft** [comment]
@LeeBamberTGC
FYI: Same as bankindex=0 , "Save Level"->save_rpg_system_items(), we do not know if masterobject is used in another level, so cant remove them from "collection - items.tsv".

**Comment by LeeBamberTGC** [comment]
@plemsoft I added a delete quest item which works quite well for the quest list across the whole game project, maybe we could add a similar button to Delete Collectable that would delete it from the game project master list, then the user would have to re-add the item in another level if they made a mistake and wanted it after all in their game.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Check out the next EXP build it has better clean up of both parent objects, object instances in the level and the collection list can be managed from the editor.  Start with a fresh game project as corrupted projecrs now exist from old versions that produced bad data.  If you find this issue persists, give me a step by step from a fresh game project how I can reproduce, thanks!

**Comment by MonkeyFrogStudio** [comment]
Looks like it's working so far. I will close this one and open a new one if it were to crop up again.
