### ISSUE TITLE
GameGuru MAX - Bug - Light Probe Issues (Latest EXP Build)

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4405]
@LeeBamberTGC 

Firstly, thanks for adding this! It makes a world of difference.

I cannot get more than one light probe working in a level so far. I will test more. If I have a light probe in a level, then delete it (at least after a test game), then the effects of the light probe remain, even if I run a test game again. 

I will be doing more testing.

**Comment by MonkeyFrogStudio** [comment]
Another issue with the current EXP with light probes - If you make changes, such as selecting a new Global Probe Resolution, the probe gets turned off in the view port and then doesn't update until you click on it again or move it.

Also, the probe balls are showing up in the view port and they get in the way:

![probe](https://user-images.githubusercontent.com/36735507/230276463-d9ddf7e6-3052-41a0-be0f-83fb42fdac5b.png)

**Comment by MonkeyFrogStudio** [comment]
It also seems that the global light probe (just guessing here) also gets a bounding box?

![probe3](https://user-images.githubusercontent.com/36735507/230276940-32186098-f8c6-44dd-83be-4b25c6799b75.png)

**Comment by MonkeyFrogStudio** [comment]
For whatever reason, the objects on the ground, despite being static objects, are not showing up in the light probe's reflection map:

![probe2](https://user-images.githubusercontent.com/36735507/230278052-bbe267e2-b609-429b-9629-6fa3c00c97e7.png)

Notice that the wall and column are.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Can you send me an FPM level with stock media so I can see the one probe limit you are seeing. My own test level shows two, you can see the different env maps being used:
![image](https://user-images.githubusercontent.com/35840583/230411446-8574b907-d8b8-4f9e-b6bc-6f3b99b686c6.png)

The global resolution hiding the env map is a bug.   I will remove the spheres from the debug render but I thought they looked nice and more importantly, showed the env map and thus useful. Consider them gone. 

The massive probe in the sky is a leftover, and so a bug, I will remove it as it is confusing. Without a global probe, Wicked will just render the sky if no probes are manually placed (aside from the old 2 way switch system that kicks in if no probes are used).

The missing static wall is a bug, good find!  I think everything else should stay in the env map including the shadows. Some scenes rely heavily on the shadows to paint the overall scene, and the env map needs to represent that scene closely.

Some good feedback, thanks!

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Okay, new EXP build up with all changes made noted above. All with the exception of the Env Map Resolution that Wicked Engine really does not like changing from 128x128. Seems there are other dependencies on this size, and changing it live leaves rogue resources floating about, and for the end user, if they abuse the setting their memory requirement jumps from 7GB to 12GB.  I have disabled this for now to get a good V1 stable, then we can look at an entirely better system that offers per-probe resolution which makes more sense to me.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio The EXP new build is now up if you want to give it a try. :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Several new issues:

![probe](https://user-images.githubusercontent.com/36735507/230448056-7592f16e-c342-40c4-8d46-b9b71249f15b.png)

- The probe marker is TINY! It's just a bit bigger than a dot! ;)
- Most of the time the gizmo/widget for move/rotate/scale is not visible (despite it being visible in this screen shot)
- The spheres are still there, just tiny (you can see them because of the next issue)
- Each object is getting its own bounding box - the probe game marker and both cubes. One is a tiny bounding box (near left bottom), the other is about the same size as the probe's.
- Sometimes the bounding box is no visible. Moving the probe tends to bring it back.
- The old probe (placed before the update) would not show a bounding box nor a reflection map. I had to remove it and replace it with a new one.

**Comment by MonkeyFrogStudio** [comment]
Another issue:

![probe2](https://user-images.githubusercontent.com/36735507/230449791-1c5becf2-ddb9-41b9-8fbd-9538c14fc4c7.png)

All sides of the cube are being affected by the probe instead of just the insides as before. I think this is due to the second large bounding box? Just a guess.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC 

Placing a second probe made the extra big bounding box disappear:

![probe2](https://user-images.githubusercontent.com/36735507/230451051-3188a748-f128-4399-a909-98ad302c928e.png)

And while the second probe seems to be affecting the static items in the center (the pile of gold objects), the walls on either side are not affected by the probe at all (nothing is being reflected there). But the first probe affects both the object in the center and the walls.

**Comment by MonkeyFrogStudio** [comment]
Another issue:

I had placed two probes, then deleted one. Even so, when I select the remaining probe, the bounding box for the one deleted shows up as well:

![probe](https://user-images.githubusercontent.com/36735507/230473308-b2dab812-cd22-4b55-a44c-afa6de2eeab4.png)

So, at the time of this screen shot, there is only one probe in the scene.

**Comment by MonkeyFrogStudio** [comment]
If you select any light, the bounding boxes for the probes show up (including the one deleted probe). But if you select an object, these do not appear.

Object selected:
![probe2](https://user-images.githubusercontent.com/36735507/230474581-fc142786-65a7-4df3-8dbb-d5208cb604b9.png)

Light selected:
![probe3](https://user-images.githubusercontent.com/36735507/230474626-fe1e76eb-962b-4f40-a45b-150f3660c81c.png)

**Comment by MonkeyFrogStudio** [comment]
Added a third just to test:

![probe](https://user-images.githubusercontent.com/36735507/230476521-8bc69679-539d-4d05-8cbd-85bfdcb6ca23.png)

Selecting any one probe or light will display the bounding boxes for all probes in the scene.

**Comment by MonkeyFrogStudio** [comment]
The small orb with bounding box is NOT visible unless one of the probes is selected. Once visible, if you double-click on it, your view ZOOMS in to focus on it:

![probe2](https://user-images.githubusercontent.com/36735507/230477829-611e8b04-6be6-46f5-9783-6218b7505a65.png)

This does not happen for me for any other object that I double-click on.

**Comment by MonkeyFrogStudio** [comment]
Even if I delete all light probes, the initial probe's effects remain:

![probe](https://user-images.githubusercontent.com/36735507/230478461-c4ca9ae9-5738-48a6-9ef3-77eb262e3ca8.png)

Here's one where the probe never effected the walls:

![probe2](https://user-images.githubusercontent.com/36735507/230478679-a320572f-47a8-496b-bb67-4cce4f7fc548.png)

This is what the first one should return to looking like if there's no probe there at all. However, the gold pile is acting like there's still a probe.

On the third one over, neither the walls nor the gold pile show any affect from a probe (which is correct, since all probes have been deleted):
![probe3](https://user-images.githubusercontent.com/36735507/230479091-588a9b6d-cfb4-4e80-a0e7-ae9baba1ae8b.png)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC The screen flickering in the editor that people are reporting seems to be caused by the new light probes. My test level, with probes in it, is flickering like mad. My other levels, without probes, are not flickering at all. Adding a new light probe to the level that is flickering tends to stop the flickering (after it's had a moment to generate the new reflection). But after saving, even if MAX is not closed, the flickering returns again.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Flickering fixed in latest EXP build, have removed Fixed tag while your other issues are outstanding.

**Comment by LeeBamberTGC** [comment]
@Kravenwolf I have closed those issues so we can finalize the probe work on this issue. Feel free to add here if the next EXP build that deals with probes does not solve all your bugs.

**Comment by MonkeyFrogStudio** [comment]
The large bounding box in the sky is still there:

![probe1](https://user-images.githubusercontent.com/36735507/232033578-7c70d380-bcf2-4390-bf5b-b5730a0bd807.jpg)

But I'm guessing that's supposed to be there based on the fact it's in one of your screen shots (post above) and due to your comment about a global probe. Even so, I thought I'd point it out.

There's still this small, hidden probe:

![probe2](https://user-images.githubusercontent.com/36735507/232033927-24474787-1a3f-429a-87e3-8e1b6f47ca4c.jpg)

I am guessing that is also still supposed to be there?

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Can you send me the FPM level next to the small probe, I am not sure about that one :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Here's the FPM:

[Test1-Level.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11232643/Test1-Level.zip)

The small probe was directly under the player marker. I moved the player marker after noticing it so I could better get it in the screen shot.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Thanks for this, found the little bugger. Will be gone for next EXP build.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC You're welcome. I'll keep testing and pushing the probes and let you know if I find anything else.

**Comment by MonkeyFrogStudio** [comment]
I think it's best to close this one and if I run into an issue with probes in the future, I'll just start a new topic for the issue. So far, these are looking great! Thanks!
