### ISSUE TITLE
Game Element View options gone ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4406]
The Game Element View options are gone ?
Im assuming this was to make room for the **add probe** ?
I always found this pretty handy and plus the fact you cannot have water on a blank level without the ability to enable it from the view options ?
Unless of course im missing something 

![view](https://user-images.githubusercontent.com/35708217/230323798-d41cd928-d676-48b6-bc76-73ff7aad5fab.png)

So if i did want to add water here for example i cannot as this was created on a blank map.

![S1](https://user-images.githubusercontent.com/35708217/230325142-ad31549d-e32c-44d7-bf66-2af514502def.png)

If nothing else can the water be enabled for Blank maps so we can still use it.

**Comment by synchromesh62** [comment]
@plemsoft 
Im assuming you fixed this one as it looks like this has now returned.
Awesome thanks Preben

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Preben and I have an understanding, we break each others fixes ;)

**Comment by plemsoft** [comment]
@synchromesh62 Ups yes forgot to write it was fixed :)

**Comment by synchromesh62** [comment]
Confirmed as fixed so i will close it :)
