### ISSUE TITLE
GGMAX Bug (EXP Build) - Collision Problems AGAIN

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#4407]
I had already reported the problem 1 week ago (#4348) and the issue had been resolved, but after the last update the collisions have returned to the wrong position as you can see from the photos.

![CollisionBugGGMAX](https://user-images.githubusercontent.com/103126963/230364023-87556aec-33e1-4463-ab50-62cdb9468345.jpg)

**Comment by plemsoft** [comment]
@LukeTheLukeLTL Sorry my bad, i fixed it again and it will be in the next update :)

**Comment by LukeTheLukeLTL** [comment]
Yes I confirm that it has been solved, thank you :)
