### ISSUE TITLE
BUG missions

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4408]
When you finish the mission you don't give money and XP

**Comment by davetgc** [comment]
Can you please give us some more information. How have you set up the mission? Can you share screenshots of the settings please,

**Comment by SampeyFS** [comment]
![image](https://user-images.githubusercontent.com/108415264/230435771-bb329937-a7e0-4ccd-95c9-5813c5df00f5.png)

**Comment by SampeyFS** [comment]
I did the test in the new map it works here no I don't know why with the same object the keys is a defect in the collection I think

**Comment by davetgc** [comment]
Thank you, that will help.

**Comment by LeeBamberTGC** [comment]
@SampeyFS Try the next EXP build with a new game project and map to confirm all is working okay. Older maps could contain corruption of the collection list, so best not to use.

**Comment by SampeyFS** [comment]
sisi remade the game again

**Comment by LeeBamberTGC** [comment]
@SampeyFS Shall we close this one if your new game is working?

**Comment by SampeyFS** [comment]
the missions not put it yet

**Comment by LeeBamberTGC** [comment]
@SampeyFS Attach level when you make it, thanks!

**Comment by SampeyFS** [comment]
All right
