### ISSUE TITLE
GG Max - Bug - When you complete a map and the winzone sends you back to same map everything is looted already

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4409]
As the title says, Now the new system is in place to be able to keep items, and send them through to the next map, What happens if you want a map to be replayable ?
I was just testing my map, where i have 4 extraction points, each taking you to a different level.
Currently i only have 2 levels, so 2 of the extraction points are set to take you back to the same level you are on, and 2 are taking you to a new level.

But after testing my standalone, i extracted from my level, and was sent to the same level.
But everything, All boxes i had opened were already open, The Key for the Extract Jeep had already been looted, The extra hidden ammo had already been looted, The armour didnt respawn that is hidden, The first aid boxes didnt respawn.

This really needs to have an  option on the Winzone that sends you to the new level, on whether you want the level spawning as new, or spawning like it does now and everything you looted and killed is already gone.

This is a created BUG.

**Comment by davetgc** [comment]
It's an interesting point. I'd assumed that the system was set up to eventually allow the player to jump back and forth through levels. I'll let the dev team answer this and decide if it's a bug or an unfinished feature.

**Comment by davetgc** [comment]
@Tum1370 - I agree, but as there is a feature freeze and we're only working on enhancements that fix bugs, I'm leaving it to the dev team to make the call. For the future I agree this should be an option.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Added feature back in using a tickbox in the winzone behavior in the next EXP build:
![image](https://user-images.githubusercontent.com/35840583/231491056-4650798c-6dab-47ab-9b6b-843304d31efb.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC This does not seem to be in the latest EXP build. I tried to change all my 4 winzones to the new ones, but the reset states options i not there.
See screenshot below with no option for Reset State.

![Untitled](https://user-images.githubusercontent.com/66874403/231561355-5fd0f156-427b-4fe9-ad70-8e674c9f31ff.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Added for new EXP build, available now:
![image](https://user-images.githubusercontent.com/35840583/231802932-969e6a0e-c953-493b-ae1c-b4e02febc774.png)
