### ISSUE TITLE
F9 edit mode Does not allow selection of EBEs 

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#441]
I went into F9 edit mode to attempt to retrieve a EBE that had sunk below the Ground plain I used F11 to turn off terrain so I could see it. I could not select it Nor could I select another EBE that was above the terrain.

 And before anyone says it I was in entity mode and could select non EBE entities.

I did however accidently select my start marker and manage to duplicate it (not a good Idea)
![duplicatestart markers](https://user-images.githubusercontent.com/35710601/47973567-3b3afc00-e0f9-11e8-9ddc-90f2d9baffd6.PNG)
Fortunately they can be deleted I mention this as it could confuse beginners
Also I am using 2018.10.30 - Monster Update compiled from Repo

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed … EBE structures cannot be selected in F9 Mode

**Comment by LeeBamberTGC** [comment]
F9 mode now allows EBE entities to be detected, selected and copied.
