### ISSUE TITLE
GG Max - EXP - BUG - Can not stop the XP from leveling up a player even though i dont want XP 

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4411]
As the title says, no matter what i tried, i cannot stop the XP from leveling up a player.
I tried removing the MyXP global, but still XP went up as i killed things.
Then when it reaches a certain level it pings to say youve leveled up.

This certainly should not be doing this if the DEV doesnt want a level system in the game!

**Comment by Tum1370** [comment]
@LeeBamberTGC I just tried this on the latest EXP build, I changed the Stat "MyXPMax" from the set 500 to 0
After playing the game, my XP went up, and this stat was set at 500 again.
The stat does not save at 0

**Comment by LeeBamberTGC** [comment]
@Tum1370 Seems after the initial creation, user globals could not be changed in the screen editor. Fixed for next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC Just tested this on latest EXP build, I set the stat MyXPMax to 0.
Tested my game, After killing first enemy, my XP still went up.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Ise use two ways to confirm a fix "Fixed for next EXP build" and "Fixed for this/current/latest EXP build". The former is what I have done the fix but it will be uploaded as part of other fixes in the near future :)

**Comment by Tum1370** [comment]
@LeeBamberTGC I can now confirm that this bug has been fixed. After testing and setting MyXPMax to 0, my character does not level up XP. Thanks Lee. I will close this issue now.
