### ISSUE TITLE
MAX - Lua terrain collision detection no longer working.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#4412]
i.e. the Lua commands:
GetTerrainNumCollisions( objId )
GetTerrainCollisionDetails( objId, index )

Not working.

**Comment by AmenMoses** [comment]
Just a guess but possibly due to the terrain object having a different Id in MAX than it did in Classic?  

IIRC when I implemented the collision detection it uses the Id number to differentiate between terrain and objects.  The objects part still works but the terrain doesn't.

**Comment by plemsoft** [comment]
Related to: https://github.com/TheGameCreators/GameGuruRepo/issues/3419

**Comment by AmenMoses** [comment]
@plemsoft : The physics collision system I added doesn't use ray casting so I can't see how they are related.

**Comment by plemsoft** [comment]
@AmenMoses There is no terrain object, terrain use a custom shape:
https://github.com/TheGameCreators/GameGuruMAX/search?q=GGTerrainPhysicsShape
What are you trying to do ?

**Comment by AmenMoses** [comment]
Well it has worked in Classic fine for years, what changed in MAX to break it?

**Comment by plemsoft** [comment]
@AmenMoses The classic terrain used the build in bullet btHeightfieldTerrainShape for collision and had a objectid assigned to it , this is not possible in Max as the terrain is "endless" , so you cant have data to represent it, so we made a new bullet physics shape that are used, see above :)

**Comment by AmenMoses** [comment]
Aha, so could you add a call-back for that to get the Lua functions working again?

**Comment by plemsoft** [comment]
@AmenMoses Do you have a script i can use to test it ?

**Comment by AmenMoses** [comment]
[grapplinghook2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11183527/grapplinghook2.zip)

Attach to small box or similar, physics on.

**Comment by plemsoft** [comment]
@AmenMoses Thanks , fixed for the next update :)

https://www.youtube.com/watch?v=fxRPA0sHrkM

**Comment by AmenMoses** [comment]
Excellent news, shall test when it arrives.

**Comment by AmenMoses** [comment]
Appears to be working again now.  

Presumably the fix won't break it in Classic!

**Comment by plemsoft** [comment]
@AmenMoses FYI: Classic and Max no longer share the same code. are in separate repos.
