### ISSUE TITLE
Max Light Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4413]
https://user-images.githubusercontent.com/108415264/230454807-ee993856-ebdd-404c-a3da-93bc825f576c.mov

**Comment by MonkeyFrogStudio** [comment]
Did you ever give your system specs? It helps, if you haven't.

**Comment by casigus** [comment]
also have this disco going on!

**Comment by Kitakazi** [comment]
Me too. Just downloaded an update and it's happening on startup everytime.

**Comment by davetgc** [comment]
I can also confirm this.

**Comment by SampeyFS** [comment]
It still blinks it hasn't been resolved buddy @davetgc

**Comment by davetgc** [comment]
@SampeyFS  - This hasn't even been investigated yet.

**Comment by SampeyFS** [comment]
ah ok sorry

**Comment by MartinCranshaw** [comment]
Same problem.

**Comment by davetgc** [comment]
More information here :#4418
