### ISSUE TITLE
GG Max - EXP - BUG - DROP in Inventory not working properly

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4414]
In the latest EXP build,the Inventory DROP doesnt work properly now.

I bought a health pot from a vendor, Then tried dropping it, The actually health applied to me, and didnt seem to drop.
But after stopping the level, the Health pot was then visible in the editor where i dropped it.

So i tried this again, and exactly the same thing. The health pot didnt drop, and didnt appear until i got to the editor, and it applied the health to me.

Also both health pots were still there on the ground when i tested level again.

EDIT: After testing this several time, it seems to be just HEALTH_LUA items that are causing this problem.
And everytime, they apply the health when you click DROP, but the item doesnt drop, Then the item appears in the editor where you dropped it.

The screenshot shows both the dropped Health pots as seen in editor, These are not placed there !

![Untitled](https://user-images.githubusercontent.com/66874403/230455122-57fd0ed0-35e3-411d-abf9-840113c12eef.png)

**Comment by davetgc** [comment]
The flicker bug is confirmed and also reported here: #4413

**Comment by Tum1370** [comment]
@davetgc No, this inventory drop bug is a new one that only started for me after updating last night just before this post.  
Also, I noticed that it only seems to be with items with health.lua attached.

I will test more when at pc but definitely not an older bug.
My inventory drop system was working fine.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Next EXP build has been tested with this simple stock test:

1. New level, add a milk bottle health, set to manual and collectable
2. Add RPG HUD screens then test 
3. You should be able to pick up the bottle and click DROP to drop it.

Can you confirm this works in the next EXP build and we can go from there :)

**Comment by Tum1370** [comment]
@LeeBamberTGC This does the same thing on my level. The health pot doesn’t drop, but adds health, then appears in editor after stopping test.

I tested the method with milk bottles,  that worked,  but the milk bottles were floating above the ground when I dropped them. 

So this is not fixed as well.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for all your testing and quick responses!  The new EXP build is now available covering all the fixes we have discussed today and from previous reports marked as fixed for confirmation. Have a good test with fresh new game projects (old ones will be corrupt) and let me know what else you might find.

**Comment by Tum1370** [comment]
@LeeBamberTGC I have tested this bug a lot on my RPG Test level and it kept on doing the same thing, only for the Health Pot though.

So after creating a Blank level, adding 3 Health Pots collectables, Picked them up, and Dropped them, They all dropped fine. 

So i will now close this issue as fixed. Thanks for the fix. :)
