### ISSUE TITLE
Video Display Problem in GameGuru MAX Build 2022.04.06

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#4418]
Latest build - GameGuru MAX Build 2022.04.06
Now has introduced a flashing display within the editor, happens regardless of map etc. Have no idea how to fix it or what causes it.

https://user-images.githubusercontent.com/95015657/230554205-f4fe6c12-f5ef-4afa-b0e2-027ca9d53114.mp4
https://user-images.githubusercontent.com/95015657/230554243-3e7ee96b-bc37-476a-aa8c-a2118bd0fe20.mp4

**Comment by Necrym59** [comment]
Just tested this with a "skybox" and the problem dissappears, it seems only to happen when using "simulated sky".

**Comment by davetgc** [comment]
Hi, reported here: #4413

Skybox info is useful

**Comment by davetgc** [comment]
Closed as duplicate but linked in other thread.
