### ISSUE TITLE
GG Max VR gun animations slow

### ISSUE THREAD

**Issue by dadgood** [TheGameCreators/GameGuruRepo#4419]
The gun animations are really slow in VR, moving around etc. is fine and FPS is fine it is just the animations for picking up the gun, shooting and changing to another gun. 
The Animations are fine when in normal flat screen mode.
On the one hand its cool to see the animation in slow mo as you don't usually get to see the shooting animation but the downside is I'm already dead by the time the gun actually shoots.

Running on Quest 2 with Virtual desktop.
![bandicam 2023-04-07 20-53-43-596_3](https://user-images.githubusercontent.com/74854393/230583203-a38a4499-27f3-42f4-803b-7a2c5fa7db37.gif)

**Comment by Necrym59** [comment]
I have the same problem on a WMR Headset.

**Comment by synchromesh62** [comment]
Same here with characters moving really slow also.
all linked to the same problem at a guess.
