### ISSUE TITLE
EBE Structures dive underground if you toouch the green arrow to move them

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#442]
If you select a EBE structure by clicking on anywhere other than its site marker then click and hold on the green arrow it will dive below the ground as if you were moving the mouse to the down. Also generally more sensitive to mouse movement than other entities.

Note that clicking on the site marker will cause the EBE to behave like other entities only when clicking on the EBE structure its self do you get this odd skittish behaviour.

**Comment by C0mbie** [comment]
I can confirm that EBE structures are very sensitive in the editor! Fine-tuning of their position is sometimes quite challenging...

**Comment by synchromesh62** [comment]
I do find also that lights cannot be seen using Tab to go inside...
Seems to work on first creation but all goes to pot when you re - edit it ?

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
The Original OP bug seems to have been fixed in the last.
It now jumps upwards slightly but is controllable.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
It would seem this issue is in TOP DOWN  mode rather than 3D Space … I have added a video below.
Perhaps a fix would be just to disable up down arrow on the widget in Top down as its not really for that anyway ?
https://youtu.be/NI6u9D3Q5Xc

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for testing this,

All strange widget behaviors has been fixed here:

https://github.com/TheGameCreators/GameGuruRepo/commit/56037907e098f6e5df71f3194f3ea57846712af1

Just tested in TOP DOWN with EBE , and it also works perfectly :)

Will be available with the next update.
