### ISSUE TITLE
Flickering screen

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#4421]
Hi There has anyone had problems when you start Gameguru Max up the scene is flickering. It still flickers even when you have loaded a level. Just wondering what's going on. I have tried to verify files and I have even re-installed graphics driver and it is still the same.

**Comment by Tum1370** [comment]
@Tam51 HI, This was reported yesterday and already been marked as a bug here.
https://github.com/TheGameCreators/GameGuruRepo/issues/4413

**Comment by davetgc** [comment]
Closed as duplicate and added to original post.
