### ISSUE TITLE
Report from Steam : Fantasy Lake town DLC crashing Max when scrolling through the assets 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4423]
Fantasy Lake town DLC crashing Max back to Windows Desktop when scrolling through the assets.
Reported on Steam by user.
I installed myself and can confirm this is the case.

**Comment by davetgc** [comment]
I'm investigating this, but I can't replicate it.

**Comment by synchromesh62** [comment]
Hi Dave 
Are you using the official DLC downloaded from Steam or the version you were sent to upload ?
Was up till 4 this morning going through this with Eyefly to find out was only trying his original and had no issues :)
I think its the download from Steam.

**Comment by davetgc** [comment]
Yes, the official version

**Comment by davetgc** [comment]
It's taken awhile, but the issue has been tracked down to a file in the floors folder, and a possible MAX bug. Thanks for MonkeyFrog and Synchromesh for some exhaustive testing.

**Comment by Bullyblasta43** [comment]
yes all i did was make a new project, let the default edit area size, made it sky box, made it dawn, natural screen filter, raised the water level up just a bit, created the area, hit add to bring up the assets, and went streight to the fantasy lake town pack, scrolled half way through the assets and it crashed and i attempted to do this multiple times, everything in my files are what comes with MAX, im running a, NVIDIA Geforce RTX 3060 GPU, RYZEN5 5600g CPU, with 16GB of RAM.

**Comment by davetgc** [comment]
@Bullyblasta43 - We have a temporary fix, please go to your MAX install folder, find the Lake Town Booster Pack folder, and the subfolder Floors, and delete this FPE. WVP - Floor - 1 - Full - Tileable.fpe. This will solve the crash. I've attached an FPE above that you can test to see if it fixes the asset.

**Comment by davetgc** [comment]
@Bullyblasta43 

Hi, we've tracked down the issue, but it will take couple of days to get the fix to Steam.

If you're having this issue (and if you aren't please ingore this advice.) here's a temp fix.

Please go to your GameGuru MAX root folder, entitybank/Lake Town Booster Pack/Floors and delete the file.

WVP - Floor - 1 - Full - Tileable.fpe

That will resolve the crash while we resolve the Steam issue.

Once again, we're very sorry for the inconvenience for anyone affected by this.

**Comment by MonkeyFrogStudio** [comment]
You can also rename the WVP - Floor - 1 - Full - Tileable.fpe by removing the spaces (or anything that makes it shorter) and it should work fine.

**Comment by MonkeyFrogStudio** [comment]
As Dave pointed out, the issue is with one file found in the Floors directory - **WVP - Floor - 1 - Full - Tileable.fpe**. Here's what I've found:

- If you relocate the that file to a folder that's not as deep in, such as Lake Town Booster Pack/Test, then MAX won't crash when you scroll through the Object Library looking at Lake Town and a thumb will attempt to be shown for that file in the Test folder.
- If you move all the associated files the FPE is looking for (textures, DBO file, etc.) and the BMP for the thumbnail into that same folder, you will get your correct thumbnail, the 3D turntable, and you can use the object in your level from the Object Library with no crashes.
- If you rename the WVP - Floor - 1 - Full - Tileable.fpe to something shorter, even if you leave it in the original Floor directory, scrolling through the Object Library will not crash.

All in all, it seems that MAX is having an issue with really long file names IF that file is also several sub-folders deep.

**Comment by Bullyblasta43** [comment]
thank you guys so much for the TEMP fix, and hope you guys dont have much truoble fixing the issue for steam. wish you guys luck and try not to stress too much i know peopl can be frustrating and you have to deal with idiots like me that dont know that much about how to do things on PC, keep your heads up, good days are coming.

**Comment by LeeBamberTGC** [comment]
@Bullyblasta43 My full path to this file is "D:\SteamLibrary\steamapps\common\GameGuru MAX\Files\entitybank\Fantasy Lake Town Booster Pack\Buildings\Building Kit\Floors". Can you state your full absolute path to the same DLC folder, thanks!

**Comment by Bullyblasta43** [comment]
@LeeBamberTGC my PC does it like this, Windows(C:)/ Program files (x86)/ steam/ steamapps/ common/ GameGuru MAX/ Files/ entitybank/ Fantasy Lake Town Booster Pack/ Buildings/ Building Kit/ Floors. and inside the floors folder is where i found the asset floor they were saying to either delete or shorten, i decided to just delete it till the issue is fixed.

**Comment by LeeBamberTGC** [comment]
@Bullyblasta43 Hmm, it does not seem to be a character limit then. Try the attached replacement FPE and files. I suspect it relates to the fact the FPE and DBO have different names but suggesting this is a typo:

![image](https://user-images.githubusercontent.com/35840583/230785675-7ac69840-dfc6-46ca-9d6d-0c13ed972237.png)
[WVP - Floor - 1 - Full - Trimmed.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11185910/WVP.-.Floor.-.1.-.Full.-.Trimmed.zip)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC During a test, I had renamed the FPE to something like "test_test_test_1_test.fpe" and it then worked fine. So, not sure it's because the FPE and DBO have different names.

**Comment by Bullyblasta43** [comment]
@LeeBamberTGC that actually worked, its now in the library as, floor 1 trimmed, and can pull it out and use it and scroll through assets without crashing. but i would still take a look at what, @MonkeyFrogStudio was saying just in case there is an issue that may cause a problem later down the road, just saying not trying to tell you how to do your job, i just know coding and file naming and things like that are pretty tricky at times.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio yes it is a funny one, I was not able to reproduce following the steps above, but it is not just the file name length, it might have something to do with how the library parses and uses the name, and some combination can cause issues on some library layouts.

**Comment by LeeBamberTGC** [comment]
@Bullyblasta43 Thanks for the confirmation. We will leave this open a while in case more info comes in, but happy to learn this fixed it. I will make the changes and upload a new DLC tweak so other users can avoid this one.

**Comment by Bullyblasta43** [comment]
@LeeBamberTGC thank you Lee. i appreciate it, and if anything else happens soon with this DLC i will let you know. you guys are doing an amazing job with max and would love to see more DLC like this in the future, keep up the good work and dont let anyone get you down.
