### ISSUE TITLE
GGClassic feature request! Reset visual

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#4424]
It will be amazing to be able to reset any of the visual parameters by right click on any of the slider green box,to get the default settings as its difficult to remember all the parameters values. 
![image](https://user-images.githubusercontent.com/81198887/230696378-6dfcec2d-f71d-43a2-8fa5-83f430d81980.jpeg)

**Comment by Teabone3** [comment]
Very good request. I recall many (including myself) asking for this some years back.
