### ISSUE TITLE
GG Max - EXP - Quest Objectives visible on Map even when quest has not been picked up

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4428]
As the title says, IF you have items set as objectives, they will appear on the minimap  even though that quest for them has not been picked up.
Really needs to only activate when the player actually picks up that quest and its in his quest log.

**Comment by Tum1370** [comment]
Necrym59 has sent me a new version of the HUD script that fixes this bug.
No quest objectives are visible on the new version, prior to picking up the actually quest for them.
If you pick up 2 quests, the only objective that is visible is the active selected quest.

Thanks Necrym59.

**Comment by Tum1370** [comment]
@Necrym59 Hey, This still not been added to the latest EXP build.
I updated to latest build, then deleted the hud0 you sent me, validated files, and testing i had every objective showing again.
I will add you copy of hud0 back for now until this gets fixed.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Can you email me your HUD0 so I can windiff it, the objective marker works for me :)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Added to next EXP build :)

**Comment by Tum1370** [comment]
@LeeBamberTGC I can confirm this is still not fixed in the EXP build i only just download.

**Comment by Tum1370** [comment]
@LeeBamberTGC  As you can see in the screenshot, This is the latest exp build just now, and i deleted the RPG template so it resaved it.
i have just started a test level and see the objectives still showing.

![1](https://user-images.githubusercontent.com/66874403/231544607-a79f13dc-4b0b-4e14-832f-c912f8875a7e.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 As per the issue heading, functionality was changed so objectives now ONLY show when the quest is active.  Best to use the files and builds uploaded via the EXP branch as any bugs and reports from older files cannot be used to reproduce current issues.
