### ISSUE TITLE
Retail version of Max cannot seem to install the Cyberpunk pack dlc

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4429]
whilst trying other versions to rectify the locking on the lakeside pack led to this finding. 

The Retail version of Max cannot seem to install the Cyberpunk pack dlc 
If i install it via the exp etc it **will** install just fine
But then if i roll back to retail ( selecting Non from the dropdown menu ) it is removed and the DLC tick box does nothing

**Comment by LeeBamberTGC** [comment]
@synchromesh62 @davetgc Good find, turns out this DLC was not lonked to the public or publicpreview builds. Shows the importance of testing the DLC both during the model/level testing stage and the post release stage too.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Just rolled back to the retail and can confirm it now installs perfectly to the Steam Retail version :)
