### ISSUE TITLE
Multi - Texture solution in standalone ( Perhaps )

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#443]
Just wondering on this
At the moment the . fpe shows this for example ..

;visualinfo
textured      = BPBLUE_D.dds
effect        = effectbank\reloaded\entity_basic.fx
castshadow    = 0

How  about if this was possible ?

;visualinfo
textured 1     = BPBLUE_D.dds
textured 2     = BPRED_D.dds
textured 3     = BPGREEN_D.dds
effect        = effectbank\reloaded\entity_basic.fx
castshadow    = 0

It may not solve old multitexture models without updating your own .fpe  but making them from scratch this would be brilliant and would solve multi textures being copied to the standalone ?
Pretty sure most wouldn't mind editing their old .fpe to get this feature :)

This would probably be headed an "enhancement" but its a real problem mentioned a lot … If its a 20 minute job it would make many very happy :)

**Comment by HierToo** [comment]
Is this problem still not fixed with my patch? I thought I got it. I tested with several free models with multi-textures and every texture was copied over to the standalone.

**Comment by synchromesh62** [comment]
Mine still does not :(
Is it looking for any particular format ?
I know you did a patch but assumes it wasnt incorporated or you removed it ..

**Comment by synchromesh62** [comment]
Looks like HierToo has sorted this one once its been merged :)

**Comment by synchromesh62** [comment]
This is now fixed !! 
Thanks guys
