### ISSUE TITLE
hurtzones none functional

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4430]
hello!

i tried to create a zone under the MAGMA to hurt the player but nothing happens, also tried to apply the the electrocute script to the entire magma zone and does nothing.

![image](https://user-images.githubusercontent.com/68471279/230746421-4bd72b69-a279-4386-80f9-5203f5f91a25.png)

not sure if this is a case of Im missing something or an actual bug.

**Comment by Necrym59** [comment]
Both the electrocute and hurt zones are working fine, how are you using them exactly how far under the magma do you have them, is the magma no collision??

**Comment by casigus** [comment]
ohhhhhhhh yeah of course. moved the magma and the zone worked fine. !
