### ISSUE TITLE
GG Max - EXP - BUG - Collectables are broken

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4433]
As the title says, I Have just tried a level that i had a couple of collectables on. After reloading the game and testing, they do not pick up, and the collectable list is empty.
If i add them and test them before unloading / reloading they work fine.

This whole collectable system is really frustrating, having to completely delete files, redo levels, readd collectables, for them only to break a lot of the times. This is just a simple level, imagine having a level with loads of broken collectables. Come on guys.

Screenshot 1 : The collectable file.
Screenshot 2 : The collection list in editor after loading in to Max.
Screenshot 3 : The body Armour not collectable in Test Game.
Screenshot 4 : The collection list is empty after Testing Game.

![1](https://user-images.githubusercontent.com/66874403/230877926-18dd40fe-bf21-43f7-9105-6af0e55c5dda.png)
![2](https://user-images.githubusercontent.com/66874403/230877933-165132e5-9691-4f73-95d8-092d82952bbe.png)
![3](https://user-images.githubusercontent.com/66874403/230877944-44b073a6-e807-408e-9bfe-dfb127ad710e.png)
![4](https://user-images.githubusercontent.com/66874403/230877951-8c5727a0-03d9-46ba-99e6-37d11f7054d7.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Added extra code around this area in last few days, and more code today on collection lists. FIxed issue of the collection list needlessly adding new elements each time the level is loaded, so we may have fixed this. In any event, here are my sequence from a fresh project to try and reproduce the above. Can you follow these with stock items and let me know how you fare:

1. Create a new project with an empty biome level, click to Add RPG HUD screens
2. In the level add a Milk Bottle and set it as collectable and in collection settings, click create collectable item
3. Set behavior to manual pickup
4. You should have something like this shot:
![image](https://user-images.githubusercontent.com/35840583/231500776-06fce8bb-dd89-4a1c-b8df-523fd95ed20b.png)

When you TEST LEVEL, you will be able to collect the bottle, and USE or DROP.

When viewing project files, you should see something akin to this:
![image](https://user-images.githubusercontent.com/35840583/231501244-6fd9b4fa-2b8b-4095-b82a-9132f9ce1057.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC Hi, Ill test this as soon as you upload latest exp version. But to be honest, These files are always writing correctly.
The bug reported on this issue was after testing the game, the collection list in game is wrong, even though that file is correct. But i was unable to pick up the collectable.

Also, the collection system gets very messy when trying to EDIT / DELETE collectables from within the editor. Hopefully this is the fix you mean ?

**Comment by Tum1370** [comment]
@LeeBamberTGC  This collectable system is still not working correctly for me. Yes i can pick up the items, The collectable list is not working correct. See the screenshots below. I created new collectables to this map, so it recreated the files.
Screenshot 1 is the file, see the Body Armour and First Aid boxes.
Screenshot 2, only showing body armour, and NO First Aid boxes. There are about 25 hidden First Aid Collectables on this map.

Also, Like i said the collectables get messy, I tried DELETING the 1 BODY ARMOUR COLLECTABLE, by making it Not a Collectable. Resaved the map. But after reloading the map, The collectable list file, and the in game Collectable list was showing identical to Screenshot 1 and 2.

![1](https://user-images.githubusercontent.com/66874403/231562694-0a2f8a01-9b8d-4195-8d2f-f50e828a2a14.png)
![2](https://user-images.githubusercontent.com/66874403/231562704-2c4f3a7a-dc13-4d08-a02b-c157a8cb5942.png)

**Comment by Tum1370** [comment]
Just re tested the collectable system again on a totally new project, And i constantly get the same problems.

Editing / Deleting collectables does not delete them from collectable list.
Totally empty level, still had a collectable milk bottle even though no the level was totally blank. This is because of testing the collectables with 3 milk bottles then deleting them.
Only way to toally get rid of them is to remove it manually from the collection - items.tsv file
Very messy.

And the collection list file in game does not work properly as well.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Any testing on old maps are likely to be corrupted and produce incorrect results for you. Best to start with my Milk project above, and follow my steps, then show me where you are seeing the "the collection list in game is wrong" after testing the level and take a screenshot of it, and if you can add to my steps so I can follow along and reproduce "not being able to pick up the Milk". We can go from there.  Always work from the known to the unknown :)

**Comment by Tum1370** [comment]
@LeeBamberTGC The test level is used, I only have 2 collectables on it, I actually changed the map, turned the 2 in to none collectables. Then created a new project, Added new collectables and i get the same issues. 
But still , Have you actually tried deleting a collectable in the editor ? Then saving, and then check the Collection file ? It still has the collectable saved in there even though its not a collectable any more.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Just breaking this down I can understand the process you are following from the above:

1. Use my Milk game project (described above) with 1 milk bottle set as a collectable in the list (The test level)
2. Add one more milk bottle so "I only have 2 collectables on it"
3. "I actually changed the map" so I assume you saved the level at this point
4. "Turned the 2 in to none collectables" so here I assume you deleted the 2 milk bottles from the level
5. "Then created a new project" !!! This is a worry as it would essentially WIPE OUT everything we have done to this point if we created a whole new game project and started a fresh
6.  "Added new collectables and i get the same issues" so here I assume you are creating a NEW PROJECT, adding 2 milk objects to the empty level. Not sure what the issue actually is you refer as now you have 2 milk objects you can collect.
7. "Have you actually tried deleting a collectable in the editor?" - there is no way to delete a collectable via the editor, unlike delete quest there is no delete collectable, all you can do is delete an object from the level and save.
8. "and then check the Collection file ? It still has the collectable saved in there even though it's not a collectable any more." so for this I assume you expect the object when deleted from the level to automatically delete from the collection list. This is not recommended as other levels might use the collection item you have set up. Deleting a collectable in one level should not delete it from the global list, in case level two needs to details you created for the collection item.

As you can see my saved level after deleting all milk still has the milk listed:
![image](https://user-images.githubusercontent.com/35840583/231838577-c691cc52-0893-4536-85cb-cb549328a322.png)
And as you can see, as long as an item is in the collection list, you can always get at it, even from a new level:
![image](https://user-images.githubusercontent.com/35840583/231838802-6b9ed634-bdfe-4a68-8b02-1ac6d0965671.png)

Still, your feedback is useful as we go through your understanding of the system as I get to see what most users will be going through and we need to get it right.

Now when you add in an object from your library that your game knows is a collectable, it will automatically set it up as one. Also, I have added a "Delete From Collection List" button to Collectable Settings so manual clean up of the global list can take place from the editor:
![image](https://user-images.githubusercontent.com/35840583/231845721-596406e6-18cf-456f-bb74-09ff1ab82265.png)

Will be in next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC Thanks for the explanation, and i look forward to testing your latest EXP build with the Delete button to check how the collectable list can be cleaned up.
I get what you mean that the collectable might be still required in different levels, that are within the same project, I was only thinking of the one level, So that cleared that one up :)
Please hurry and update the EXP so i can play more lol :)

**Comment by Tum1370** [comment]
@LeeBamberTGC I can now confirm that the Delete From Collection LIst is in the EXP build and working correctly.
I tested it on my RPG Test level, and it worked fine.
Item was deleted from collection list, as well as deleted from the file.

I will close this issue for now, and if i find any more problems i can start a new issue.
Thanks for the fix. :)
