### ISSUE TITLE
Crash Max For Windows 11

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4434]
![Senza nome](https://user-images.githubusercontent.com/108415264/230887213-ce8439b4-748e-4950-b4fc-bc4cb03ac275.png)

Program crashes while saving also crashed Windows 11

**Comment by SampeyFS** [comment]
Faulting Application Name: GameGuruMAX.exe, Version: 0.0.0.0, Timestamp: 0x64300ed4
Faulting Module Name: GameGuruMAX.exe, Version: 0.0.0.0, Timestamp: 0x64300ed4
Exception code: 0xc0000005
Error offset 0x000000000070ef79
Process ID that generated the error: 0x0xEB8
Start time of the application that generated the error: 0x0x1D96AF26351979A
Faulting application path: D:\SteamGames\steamapps\common\GameGuru MAX\GameGuruMAX.exe
Path to the module that generated the error: D:\SteamGames\steamapps\common\GameGuru MAX\GameGuruMAX.exe
Report ID: 3f546786-22c3-4617-a41d-7960378443aa
Full package name that generated the error:
Application ID of the package that generated the error:

**Comment by MonkeyFrogStudio** [comment]
@davetgc I've been using MAX on Windows 11 for more than a year now with no issues. Whatever he's experiencing, it's not due to Windows 11.

**Comment by davetgc** [comment]
This doesn't seem to be Windows 11 related, but if anyone else is using W11, please let me know of any issues.

Thanks,
