### ISSUE TITLE
GG MAX  Teleport trigger - DELAY - text countdown should be optional

### ISSUE THREAD

**Issue by tenser-spencer** [TheGameCreators/GameGuruRepo#4437]
Teleport trigger - DELAY - text should be optional
Teleport trigger is a excellent feature and the option for instant and delayed also, very functional. BUT, when using the DELAY, we should have the option if we want to display the countdown text or NOT.  Can we get that controllable option?

**Comment by Necrym59** [comment]
Already updated and sent for testing and inclusion
[teleport_v6.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11194063/teleport_v6.zip)

**Comment by tenser-spencer** [comment]
This uodated version works as expected. Thanks.
