### ISSUE TITLE
standalone on gameguru classic

### ISSUE THREAD

**Issue by Selwyn357** [TheGameCreators/GameGuruRepo#4439]
So I have designed many levels and finished them, when I save the level I want to be played first in the game and load it up in the standalone game mode I click start game on the menu and it starts loading. Once the game loads level then is an entirely different map from mine and it an all water level. I can't figure out why it always do this? A few time my level has properly loaded but the majority of my stand alone saves are not my level at all but an all water map.

**Comment by Selwyn357** [comment]
this second video is the standalone game and shows its in a water level and not the map from the first video

**Comment by Selwyn357** [comment]
sorry the second video is loading very slowly of course hahah

**Comment by davetgc** [comment]
Thanks. I'll leave this open for awhile to see if anyone else can confirm the issue before passing to a dev.

**Comment by Selwyn357** [comment]
thanks!

**Comment by synchromesh62** [comment]
@Selwyn357 
Are you saving your maps to the default **mapbank** folder.
Maps must be saved in that folder. 
Classic looks there for your maps when compiling the standalone.
If they are not there it will add a default instead which is usually under water.

**Comment by davetgc** [comment]
@Selwyn357 - I think @synchromesh62 has a good point. Can you please let us know if that solves anything for you.

**Comment by Selwyn357** [comment]
Nope still the water level

**Comment by davetgc** [comment]
Happy to have helped. I'll close this now.
