### ISSUE TITLE
Standalone not working 

### ISSUE THREAD

**Issue by honkeyboy** [TheGameCreators/GameGuruRepo#444]
Created test maps with winzones  none of which copy across to the standalone just create a my level .exe not the name of the map and no maps in standalone folder. can anyone confirm this for me plz

**Comment by synchromesh62** [comment]
Just tried my game all works here ..
Retarted GG
Placed a marker, building and winzone then created standalone ..
No problems encountered here either ?

**Comment by honkeyboy** [comment]
ok m8 thanks for testing it for me will try a different map :)

**Comment by synchromesh62** [comment]
Did you save it first … if not it will quickly say " Cannot find FPM file " 
but will continue to save a blank " My Level " standalone

**Comment by honkeyboy** [comment]
yeah both levels saved but only named 1 and 2 so maybe the short filenames, building one of my bigger levels next so will see if that was the case also had a loadzone on that level will check into both

**Comment by synchromesh62** [comment]
Any updates on this … Did you get it sorted ?
Still working well for me ..

**Comment by honkeyboy** [comment]
Yes m8 its seems to be short filenames for some reason, my larger game levels create correctly they have a longer name, the test levels named 1 and 2 did not so I have to presume its the length of the map name.

**Comment by plemsoft** [comment]
@honkeyboy Thanks for reporting this ,

This has been fixed and are ready from the next update :)
