### ISSUE TITLE
GG Max - The standard rotating radar stops displaying when player health falls below 99 hp. 

### ISSUE THREAD

**Issue by tenser-spencer** [TheGameCreators/GameGuruRepo#4441]
The standard rotating radar stops displaying when player health falls below 99 hp. It displays again on screen if player health reaches 100 or more. Anybody else notice this?

**Comment by davetgc** [comment]
Is the object the radar script attached to set to always active?

**Comment by plemsoft** [comment]
@tenser-spencer Thanks for reporting this issue, this has been fixed and will be in the next update :)
