### ISSUE TITLE
start standalone  error level

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4442]
https://user-images.githubusercontent.com/108415264/231194603-8b861368-4cf8-48dc-93f0-1ebef0dd3160.mov

**Comment by davetgc** [comment]
From my understanding, on starting a standalone game, the levelled up message is appearing and won't go away.

**Comment by SampeyFS** [comment]
yes yes

**Comment by plemsoft** [comment]
@SampeyFS Works fine for me in the latest EXP build ?

https://www.youtube.com/watch?v=u98OfoIRljU

Could you try again in the latest EXP build (**remember to export the standalone again**) , and let me know if it also works for you , thanks :)

**Comment by SampeyFS** [comment]
but for what do I have to see for the level if it goes?

**Comment by SampeyFS** [comment]
If you mean the standalone level it works I tried it now I killed 6 bandits I leveled up

**Comment by plemsoft** [comment]
@SampeyFS Perfect then it works for both of us :) , i will close this now!
