### ISSUE TITLE
Max won't close out on Steam

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#4444]
When exiting out of Max, Steam still shows Max to be running. when I press stop on The Max steam page Max will show to be stopping, but never stops. I have to control, alt, delete Steam to close Max.

**Comment by bluemeenie195** [comment]
Started doing it after the latest update

**Comment by MonkeyFrogStudio** [comment]
Closes for me, too. I have the latest experimental version installed.

**Comment by bluemeenie195** [comment]
just downloaded the new update and it shuts off now.
