### ISSUE TITLE
Loading Legacy GG Classic FPM Levels into MAX

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#4445]
One function that should be added before the V1 launch is the ability to load old GameGuru Classic FPM Levels into MAX.  This will not be 100% forward compatibility, and excludes everything except:

* Retain terrain heightmap geometry and terrain texture painting so the terrain looks the same in both Classic and MAX
* All entities placed on the map in the same place in the new MAX level, separated into static and dynamic objects
* All appropriate markers transferred over (start marker, lights, zones, etc) that align with MAX game elements

Many features of a Classic level will not be carried over, including:

* Old Character Creator characters
* Scripts and other linked dependencies
* Structure Editor entities
* Lightmaps and related in-level metadata

The process for a user migrating their project from Classic to MAX is to first copy their media from Classic into the entitybank folder of the writables area, then go to the storyboard and select Add Existing Level, specifying the FPM directly from the Classic installation from the mapbank folder.  MAX will detect the location of this FPM and know it is doing an additional conversion from Classic to MAX if such a flag is needed.

**Comment by LeeBamberTGC** [comment]
@plemsoft Wiuth latest commits from earlier, I do not see an import process. These are the steps I made:
![image](https://user-images.githubusercontent.com/35840583/233372850-b0b73bb2-069c-4625-a17b-6336402fbe10.png)

**Comment by plemsoft** [comment]
@LeeBamberTGC Must be a case issue , fixed here: https://github.com/TheGameCreators/GameGuruMAX/pull/13

This is what you should see :)

![classic](https://user-images.githubusercontent.com/18662417/233561373-66fc47ec-0639-4131-9971-68af0c655f1f.jpg)

**Comment by LeeBamberTGC** [comment]
@plemsoft Works great!!
