### ISSUE TITLE
Max Removes objects

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4447]
![image](https://user-images.githubusercontent.com/108415264/231275439-d3af5476-8c7a-4201-a1ad-3151191401df.png)

**Comment by davetgc** [comment]
@SampeyFS - Please provide a clear title when posting any issues and a description of the bug. That screenshot doesn't really explain anything.

**Comment by SampeyFS** [comment]
Max Removes objects

**Comment by SampeyFS** [comment]
No it doesn't work but you don't see that you have removed the objects

**Comment by davetgc** [comment]
@SampeyFS - Sorry, I might be being stupid, but I'm really not sure what issue you're reporting.

**Comment by davetgc** [comment]
I've also noted from your screenshot that you're using a lot of media that appears to come from Classic. Not all classic media is compatible with MAX and can cause problems.

Ideally, you should use the importer to prepare all Classic media for use in MAX.

**Comment by LeeBamberTGC** [comment]
@SampeyFS Is this the same issue (and fix) as you reported in your earlier issue report?
