### ISSUE TITLE
Ability to select custom Map shapshots from the UI

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4451]
As the title says, The map image does not work anymore on the latest EXP build.
See the 2 screenshots below.
Screenshot 1 is the HUD showing the correct settings for the map image.
Screenshot 2 is in game testing, No map image.

This is very Latest Version of Max.

![1](https://user-images.githubusercontent.com/66874403/231483210-26dd7322-c265-45cb-98ad-81dcfa11b1ba.png)
![2](https://user-images.githubusercontent.com/66874403/231483222-1abf2e89-dd67-4439-a996-e4a8735b2ec9.png)

**Comment by Tum1370** [comment]
@davetgc Just adding to this bug Dave. 
After the update with the new system to have the ability to take the screenshot for the map now from the storyboard. I found that if i created a new map screen, then try adding a totally different image for the map, The map that shows is still the image that was taken from the "Take Map Snapshot" button on storyboard.

I even tried just changing the map image to a first aid box, yet still it used the snapshot image, so it seems to be no way to change the image.

**Comment by LeeBamberTGC** [comment]
@Tum1370 In next EXP build, system has been improved to provide correct maps for each of the levels in the game project. A single map image provided from the screen editor could not work. The image provided is just a placeholder, but I have added additional help in the UI and removed the ability to change a map:image type:
![image](https://user-images.githubusercontent.com/35840583/231857823-3a879fe3-fe41-4afd-bc5b-d92c53010c0b.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC So basically this means, we cannot add our own map image, and just use the screenshot one now that you showed us in the live stream yesterday ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 You can edit the produced PNG file directly, just find them alongside your FPM files. They will not be overridden until you use the Take Map Snapshot option again for that level:
![image](https://user-images.githubusercontent.com/35840583/231887009-507eae1d-e62d-4686-af62-8c85fba4ff16.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC ok thanks again Lee, I’ll close this issue as fixed.
