### ISSUE TITLE
GGMAX Bug (EXP Build) - "Load Save" is not working properly

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#4452]
I had this issue in standalone, basically if you load a saved game all the weapons you had disappear, and the weapon you hold has 0 ammo.
Here is the video where I show the issue: https://www.youtube.com/watch?v=5-JQgH509hA

**Comment by LeeBamberTGC** [comment]
@LukeTheLukeLTL New EXP build uploaded that solves the issue of weapon states not being restored after the saved game is reloaded. Thanks for the video, helped a LOT!

**Comment by LukeTheLukeLTL** [comment]
Yes I confirm that the issue has been resolved. Thanks for the fix :)
