### ISSUE TITLE
Missions Feature added

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4457]
still missing the function of when you complete a mission that mission completed is written it should be added anyway it works I agreed with Lee that I wrote a post when I tried the missions add the word mission completed

@LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@SampeyFS The quest complet shows in the quest log when you have completed the quest:
![image](https://user-images.githubusercontent.com/35840583/231803535-432eb58e-65f7-47a2-9a9c-2c787c53bd29.png)

**Comment by SampeyFS** [comment]
why doesn't it come out written to me?

**Comment by SampeyFS** [comment]
What key should you press?

**Comment by LeeBamberTGC** [comment]
@SampeyFS A hunt quest is being worked on now - hope to get it ready for V1 :)
