### ISSUE TITLE
GG Max - BUG - Building Editor buildings and doors

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4458]
I have a large building made using the building editor. 
I have 3 large warehouse doors in the building.

Now when i play the level, these warehouse doors have the "OPEN WITH E KEY" already set,  but i dont want them to open with that.
I want the doors to be opened by using the Door Switch circled in RED.

I have selected all 3 of my warehouse doors, and UNTICKED the OPEN WITH E KEY setting.
Then saved the level. As seen in Screenshot 2.

After reloading, The warehouse doors are once again set to use the E Key.

This needs fixing else every building editor door cannot be changed, if the editor keeps resetting everything.

**ALSO THE WAREHOUSE DOOR HAS NO SOUND CONNECTED TO IT SO GOES UP / DOWN SILENTLY**

![Untitled](https://user-images.githubusercontent.com/66874403/231854381-56a30b69-f266-48e1-aa1f-6a00681d6d8f.png)
![Untitled](https://user-images.githubusercontent.com/66874403/231854857-bf6e20ad-1ece-4892-83b1-76ec977b8230.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Lots changed since April, and this may turn into a feature request. Just created a three door building, ungrouped them, assigned each door to the latest script, switched them to remote opening, connected all to a switch and test game shows all three doors opening when I flip the switch:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/27721cfe-c63d-44eb-8c95-d83ef46e6bb3)

Can you reproduce the above in the latest EXP build?

**Comment by Tum1370** [comment]
@LeeBamberTGC I am not sure now whether when i reported this bug that i actually UNGROUPED the building editor building. Maybe that was what was causing the issue ? 
I have just tested the latest EXP build but now after UNGROUPED the warehouse i created using building editor, but i am now getting this LUA error when my character goes near the SWITCH.

![Untitled](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/4f4729d3-b868-49ff-a347-d6dee18a93e8)

**Comment by LeeBamberTGC** [comment]
@Tum1370 That looks like an updated script from Necrym.  Log into Steam client and the latest EXP build and it should refresh to the latest scripts. In the meantime send me the one you are using now (script as shown above from the Community folder and I will compare with what I have and also find the issue if it is from Necryms code).

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just verified my latest EXP build files, and still get the same error with the Switch Script. I Have attached it here.
[switch.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12280466/switch.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you send a shot showing MAX "trying to use the Community folder one", thanks!

P.S. Necrym has the new script and may have updated since this post, you can also try VERIFY FILES on Steam as there seems to be an issue sometimes with MAX not grabbing the latest from workshop.

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just tested this bug again with the latest version of Max and can now confirm that both the Switch and the original bug with the Building Editor doors are now fixed. Thanks for the fix, I will close this issue now.
