### ISSUE TITLE
Particles Flickering

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4459]
Particles flashing/flickering when viewed at certain angles. On this video I have a smoke particle that I scaled up by 100 and when I walk into it it flickers pretty bad. This didn't use to happen. 
https://youtu.be/F-Tog57hGW8

**Comment by davetgc** [comment]
I can't replicate this, but it does appear to be happening, can anyone provide a clear step by step that will 100% show the issue.

**Comment by Kitakazi** [comment]
@davetgc I'll test more tonight when I get home but go into your level, set down a smoke particle effect and scale it up. Save the level and run test game. It should be flickering in editor and test game. Thats all I did to reproduce for the video but Ill try and test on a blank map when I get home.

**Comment by Kitakazi** [comment]
@davetgc 

Ok here is how to reproduce.  
Go to an empty map, change skybox to none and set lighting color to black. (not sure if this matters this is just what my blank map consisted of.) 

Place a particle down and select the particle "smoke_thick." 
Scale it to 300. 
Set the Opacity to 100. 

Next copy and paste the particle 3-4 times. It should start flickering in the editor at this point. However it won't yet effect test game at this point.

Next set the tree entity called Acacia, from the Max Collection, down behind the smoke particles. 
Then select the entity called Building - Window from the Buildings Collection. Scale it to 500 and set down in front of the smoke particles.

Press Test Game. Go behind the window and look at the tree on the other side of the particles and you should get something like this. 
https://youtu.be/3y3z4NsMyJY

I also made this video earlier showing how I did it, but I was using custom assets in it but it may help so here it  is. 
https://youtu.be/JQau8sedIDo

**Comment by Kitakazi** [comment]
@davetgc @LeeBamberTGC 

Good evening, another way to reproduce this one is to load up the demo map Switch Escape.fpm. 
Press test game and go through the first door where the Steam/Smoke particles are and you will see alot of particles flashing and flickering. 

I would like to request that this bug be escalated to the High label. Because while the engine still runs fine, it is very ugly. For example here is a test level I recorded about a week before this bug appeared. 
https://youtu.be/EDWcPcDRQDs?t=68

Now here is the same level on the current build https://youtu.be/ETALHyD4D80?t=4

However I did make one find that might help solve this issue, on the switch escape.fpm I could stop the smoke particles from flashing by setting the Camera Near Plane to 1000.0 

![image](https://user-images.githubusercontent.com/51464873/234734239-46838709-1f30-4c54-bc51-ad026e812c66.png)

(my back is against the wall where the fire particle is in the start of the level for reference.)

Also, not sure if it is intended but Particles still show even if they should be cut off by the Camera's Far Plane setting. Setting the  Camera's Far Plane to 1 will still show particles.

**Comment by Kitakazi** [comment]
After asking around it seems this bug doesn't affect most people. I tried deleting all particles and related folders and verifying files to re-download them but the issue still happens. I will try and re-install Max next.

**Comment by Kitakazi** [comment]
Re-installing did not fix

**Comment by Kitakazi** [comment]
When messing with particles I keep having random particles appear super high above the area I'm editing. Not sure if this is related to this bug or something else. 

These particles that appear super high in the air cannot be selected. They do not show in the Detailed Object List and will disappear if Max is closed and opened again. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/2b40aee3-1634-4ac3-a3eb-f04bb805bda3)

**Comment by Kitakazi** [comment]
Just leaving an update on this issue. Been testing it after every update but still have the issue :(

**Comment by LeeBamberTGC** [comment]
@Kitakazi The flickering in the switch escape likely comes from the nearby light behaviors that are set to flicker. I deleted all assets except the particle and one room from the switch level and no flickering was seen:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/12e678f7-18fd-499a-8b8e-4b2be59ed971)

[test_particles_from_switch_escape.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11800600/test_particles_from_switch_escape.zip)

I have attached the level os you can load it in and test the particles, and let me know what you see and IF you see any flickering at any camera settings.  I messed with the camera draw depths and FOV but could not get this particle to flicker.,  Let me know, thanks!

**Comment by Kitakazi** [comment]
@LeeBamberTGC forgot to add above. The reason I picked the window entity is I notice the flickering happen more often when the particle is being viewed in front or behind an entity that has a transparent part. I dunno sometimes it looks like the particle itself flickers but sometimes it looks like the transparent sections of entities are the ones that flicker.

**Comment by LeeBamberTGC** [comment]
@Kitakazi The xecond video I could not reproduce, and no flickering at any camera setting could get the two particle columns to flicker against the water:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/105ca362-7bd3-4894-a82f-8a9407d0c941)

Can you confirm that you are not using an AMD card. If you are, can you check if the D3D11.dll exist in this folder: "steamapps\common\GameGuru MAX". If the Vulkan proxy is being used, it might explain differences in handling transparency.

**Comment by Kitakazi** [comment]
Im not using AMD my card is an NVIDIA GeForce RTX 2080. 

I also do not have D3D11.dll not sure if it matters since I'm not using AMD. Either way I'm going to do a fresh install and see if it will fix this issue.

**Comment by Kitakazi** [comment]
I did a 100% fresh re-install. Backed up and then removed all GGMax files from my drive. Installed the standard (non-experimental) version of Max. Did not fix this issue, particles still flashing/flickering.  :(

**Comment by LeeBamberTGC** [comment]
@Kitakazi Thanks for going to the trouble of a refresh, it is always worth doing to make sure no rogue files are about, but with this discounted I would then guess something graphics card/hardware related.  Just confirming you have the OEM "NVIDIA GeForce RTX 2080" card and not a clone or non-NVIDIA manufacturer card?  Do you have another graphics card and the confidence to swap in a replacement card to see if indeed it is that card. If so, I might need to plum to buy the exact card and see if I can reproduce at this end.

**Comment by Kitakazi** [comment]
I don't have another card I can swap at the moment. 
 I am about to build a new PC before the end of this year. Just waiting till I get my yearly bonus in October. I've asked other users and it seems I am currently the only user experiencing this issue, so maybe I have some other issue with my machine causing this. Although everything seems to be fine I don't have issues with anything else. My current CPU is not very good, and its long overdue to be replaced, I wonder if that could cause this issue? 

However I'm going to try and rollback versions to see if I can find a version that doesn't cause the particles to flicker. Because it definitely started immediately after I downloaded an update. 

I would hate for you to go through all the trouble of buying a new video card if I'm the only user experiencing this issue. But 2080 I use is the MSI version it's this exact one.
 https://www.amazon.com/MSI-RTX-2080-GAMING-TRIO/dp/B07GHXQTGZ?th=1

system specs:

Windows 10
Processor: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHZ (4 CPUS), ~3.0GHz
Memory: 16GB
GPU: NVIDIA GeForce RTX 2080
VRAM: 8002 MB

**Comment by LeeBamberTGC** [comment]
@Kitakazi Alas in the UK it costs £750 :)  Link: https://www.amazon.co.uk/MSI-RTX-2080-GAMING-TRIO/dp/B07GQZ3DYL/ref=sr_1_3?crid=1FTW0NFA7Y4LG&keywords=MSI+GeForce+RTX+2080+TRIO&qid=1687727660&sprefix=msi+geforce+rtx+2080+trio%2Caps%2C134&sr=8-3

I could opt for eBay but half the time they are pretty worn out.  As this seems to be an edge issue at the moment, let's wait until we find a similar report from a card that is a little cheaper to buy :)  If you do find an easier version that does not have the flicker, and the immediate update shows it, we can narrow down all the code and asset changes, which may allow us to fix it without needing a card to test on  :)

**Comment by davetgc** [comment]
I've finally seen this happening and it appears to only be happening when you view a particle from a certain angle. My guess is it's something to do with the render bias.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed in next EXP build.

**Comment by Kitakazi** [comment]
Very nice, closing this one
