### ISSUE TITLE
All Hud screens changed to Text only in latest build

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4461]
![image](https://user-images.githubusercontent.com/99803873/231981657-cec18ed4-ed5b-4a60-bc8d-946fb4a987bf.png)

Prior to this, this was all images apart from the text.

**Comment by LeeBamberTGC** [comment]
@davetgc Can you send me the project folder, I can then reproduce.  Also, how does RPG Project look:
![image](https://user-images.githubusercontent.com/35840583/232025844-f55f983c-0570-4eab-a392-3600d9ffb226.png)

**Comment by MonkeyFrogStudio** [comment]
This is what I see when running RPG in the latest experimental mode:

![rpg](https://user-images.githubusercontent.com/36735507/232047315-259329d6-60b8-4cd9-af3d-b3970c6aaef2.jpg)

So, all looks good on my end.

**Comment by LeeBamberTGC** [comment]
@davetgc Yep, during these builds on HUDs, collection lists, quests, etc. Best to start a fresh project as old projects can carry garbage corrupt data which affects the ability to test the latest code.

**Comment by LeeBamberTGC** [comment]
@davetgc I tried your Asset Testing project, looks pretty blank:
![image](https://user-images.githubusercontent.com/35840583/232470518-0ce430a3-10c8-4b8b-b379-dc25105cc304.png)

I think we can put this down to a corrupt project, and the latest build resolved it to use the latest data.

**Comment by davetgc** [comment]
Looks like it, as there should be far more in that project.

I've not seen it since refreshing the huds.
