### ISSUE TITLE
GG Max - EXP - Bug - Every Map i go to ends up with a missing media file (including RPG TEMPLATE and other DEMOS)

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4465]
As the title says, Why are we constantly getting the Missing Media Text file for every single map that we go to now on Max.
See the Screenshots.
Screenshot 1 is RPG Template Demo Map.

![4](https://user-images.githubusercontent.com/66874403/232140015-e5a72a7f-24de-4fa2-b089-48b0315e1aca.png)
![1](https://user-images.githubusercontent.com/66874403/232140034-8ccd2dfa-f8c0-4b22-b2b0-de3e01cb7875.png)
![2](https://user-images.githubusercontent.com/66874403/232140040-8555061f-fcf0-4db3-b315-d6177e6fb791.png)
![3](https://user-images.githubusercontent.com/66874403/232140051-2d3606b1-8496-4948-acaf-f7da743beb03.png)

**Comment by MonkeyFrogStudio** [comment]
Not happening for me at all. I've tested several of the demos, including the RPG demo, can edit them and play them all just fine. Have you tried verifying your files?

**Comment by Tum1370** [comment]
@MonkeyFrogStudio Yes all files verified and fine. All demos and games play fine to.
Am just reporting that this file of missing media gets created in my mapbank whenever i go on a level.
I dont understand why ? It seems a bug to me.

**Comment by Tum1370** [comment]
@davetgc @LeeBamberTGC Please MARK this as a bug.
It is happening.
I have the latest EXP build. I have just verified all files.
I have just deleted MyDocuments Gameguru Apps folder and let Max rewrite the folder, so everything is fresh.
I then went to RPG Template and tested the map.
Then when heading back in to MyDocuments GameGuruApps MapBank folder, there is the missing media text file for the ONE DEMO MAP i tried.
This wants looking in to because it is happening, on a fresh install.

![Untitled](https://user-images.githubusercontent.com/66874403/232443049-95316552-d2da-4b76-b86f-40c56141b973.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC @davetgc 
This is a totally fresh install of the MyDocuments/GameguruApps folder. 
This is the Latest Exp BUILD. thIs is ALL files verified.

As you can see, after testing the 3 demos, circled in RED, All 3 of them produced the MISSING MEDIA TEXT message.
The YELLOW circle is a TOTALLY BRAND NEW EMPTY LEVEL + BRAND NEW PROJECT. 
The moment i test it, Max creates the MISSING MEDIA text file ?

How is this NOT a bug ?

![1](https://user-images.githubusercontent.com/66874403/232454490-118d06c5-9528-4291-ae40-2e7755aebea5.png)
![2](https://user-images.githubusercontent.com/66874403/232454571-9031c5a5-0f4f-47e6-8dde-cccd67c40a5d.png)

**Comment by synchromesh62** [comment]
**How is this NOT a bug ?**

Well it needs to be able to be reproduced and others confirming the issue helps.
Hmm thats very odd though. Just checked a few myself and no missing media ?
apart from that the missing media error message your getting i assume is the same for every map and is totally unrelated to either of them as far as content goes.

**Comment by Tum1370** [comment]
@synchromesh62 The missing media file only appears after you actually test play that map

**Comment by synchromesh62** [comment]
Got It !!
Games run from the Hub give you the missing media error although its a false positive as its not really content of the map.
I usually run mine from file \ load
MISSING MEDIA:
**C:\Users\User\Documents\GameGuruApps\GameGuruMAX\Files\levelbank\testmap\ebe28.fpe=replaceC:\Users\User\Documents\GameGuruApps\GameGuruMAX\Files\levelbank\testmap\ebe28.fpe**

**Comment by Tum1370** [comment]
This BUG is still happening, Every Map you try, demo or your own map, Max will created this MISSING MEDIA txt file in the mapbank folder.

The map still works fine, just Max creating a missing media file for no reason !

**Comment by synchromesh62** [comment]
I have confirmed and added the Bug label to this one but for now its just a harmless text file so i wont add any priority to it.
I will let the Development Team decide on that,

**Comment by davetgc** [comment]
@synchromesh62 - Thanks for the confirmation. I've assigned this to Lee, as you say he can decide.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Probably rogue old folders. Try deleting the "testmap" inside "levelbank\" and try again to see if it produces the error log.

**Comment by Tum1370** [comment]
@LeeBamberTGC This is actually very easy for you to produce. This is my mapbank folder, and one txt file for Switch Escape.
THis is after verifying all my Max files, Deleteing MyDocuments/GameGuruApps folder and letting Max create it again.
Then loading in to Demo Switch Escape, Test PLay.
Then check your folder, the missing media file is there.

![Untitled](https://user-images.githubusercontent.com/66874403/233401563-dc79b63a-e331-471f-bed3-fc62b720e29b.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you show me the end of that line of text, thanks:
![image](https://user-images.githubusercontent.com/35840583/233406181-633d461b-c855-4f76-a805-ce3b97e64bab.png)

**Comment by LeeBamberTGC** [comment]
@plemsoft I have assigned this to you so you can attempt to reproduce this. I am not getting this rogue text file, and the answer to the above will help, last time I think it showed an EBE that we no longer used which indicates an old garbage file somewhere on Tum's system.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed and will be in the next EXP update , you will need to delete the old ".log" files from your mapbank to test this , Thanks for your help :)

**Comment by Tum1370** [comment]
@plemsoft Just tested this on the latest EXP build, and can confirm that this is now fixed. Thank you for the fix :)
Ill close this issue now.
