### ISSUE TITLE
Sound erratic in latest build ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4468]
it seems the sound ( for me at least ) is erratic with Volumes going up or down with each launch of a test game.
Some our suddenly really loud and others you can hardly hear here them and it seems totally random ?
Not sure if its just me but all was fine in the previous build.

**Comment by Tum1370** [comment]
This is also happening to me as well since latest EXP build.

**Comment by synchromesh62** [comment]
Also seeing reports of this in Classic.
Related somehow ?

**Comment by davetgc** [comment]
I've not heard this, but it seems other have.

**Comment by synchromesh62** [comment]
> 

Thanks Preben
So far so good so i think its ok to close this one as fixed :)
