### ISSUE TITLE
Low Fps,in testgame-editor-storyboard.

### ISSUE THREAD

**Issue by gghermm** [TheGameCreators/GameGuruRepo#4469]
Hallo,I now want to completely uninstall Max again.including the documents and common folders.And then install the current Steam version you buy.Do I have to be in a certain build before?It always installs the build you were in.After uninstalling,there were still folders in common.Do I have to delete them too?I had reinstalled max because, from one day to the next, everything just lagged. Mapgenerator-Editor-testgame.Previously I had 10 months and 1500 hours long,with lagging no problems. Now I want everything completely new.I would be happy about a help.

**Comment by davetgc** [comment]
I can confirm I've seen lag in the editor and in the test game, that can be solved by restarting MAX, but can return. Also, some levels are freezing on loading test game.

**Comment by plemsoft** [comment]
@gghermm @davetgc Thanks for reporting this issue, i was able to find a lag in the editor caused be the new DISPLACEMENTMAP even if not used , this has been fixed , but i was not able to find the lag in standalone, could you provide more information about it, mainly at what date did this start , when i got this date i can start to check the commits around that date and se what could have cause this , Thanks for your help :)

**Comment by davetgc** [comment]
@plemsoft - It would have been the build nearest to the 16th April. However, I'm no longer seeing this issue.

**Comment by plemsoft** [comment]
@gghermm @davetgc Thanks that was the terrain collision that was fixed but needed to be ignored by all the scripts, as it was not needed in many raycasts, this was fixed in the weekend 14 april and was included in the 18 april build , so everything match :)
