### ISSUE TITLE
Lighting retained between standalone levels

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4476]
when exporting a standalone game, the engine will keep the same light/water transparency settings as your first map.

So if your first map has been built to be dark with a tint of blue or grey or black or what ever, that will be carried on to every level after making them look awrful.

the only way for your levels lights/transparency to be as you set it to be is to reload the entire level.

**Comment by plemsoft** [comment]
@casigus Thanks for reporting this issue , just tried this in the latest EXP build and was not able to reproduce it, know Lee has fixed a similar issue so could also has fixed this issue. Could you try this in the latest build and let me know if this is also fixed for you , Thanks for your help :)
If its still a issue for you could you try to zip your standalone and e-mail me a download link , this way im able to see that same as you are e-mail: plemsoft@gmail.com

**Comment by plemsoft** [comment]
@casigus Thanks for the level , but its 14gb download, looking forward to trying the game when i get some time, but for now it looks like it is working fine here, going from no ambient/light to another level with some red ambient/light:
https://www.youtube.com/watch?v=FQGk1bR4g8M
Could you try to make a new small project with 2 levels using stock assets that show the problem you have , this would be way more easy for me to track down the problem , thanks for your help :)

**Comment by casigus** [comment]
The whole point of the problem was to send you the game (as requested) too see if it crashes at random intervals like it did during the testing on stream!!! I feel like I'm shouting into the void here and have completely wasted my time. How can you test it and see how it performs ??? It's noting to do with the assets used. It crashes at random intervals ! Urgh. Your suggestion literally has nothing to do with the issues experienced.


On 25 April 2023, at 11:02, Preben Eriksen ***@***.***> wrote:


@casigus<https://github.com/casigus> Thanks for the level , but its 14gb download, looking forward to trying the game when i get some time, but for now it looks like it is working fine here, going from no ambient/light to another level with some red ambient/light:
https://www.youtube.com/watch?v=FQGk1bR4g8M
Could you try to make a new small project with 2 levels using stock assets that show the problem you have , this would be way more easy for me to track down the problem , thanks for your help :)

**Comment by casigus** [comment]
this is no longer an issue with the latest build.

**Comment by plemsoft** [comment]
> send you the game (as requested) too see if it crashes at random intervals like it did during the testing on stream!

The issue here that you reported was "Lighting retained between standalone levels", if you have another problem with your game please open a new issue , happy to see that this issue was also fixed for you :)
