### ISSUE TITLE
standalone object bug

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4477]
in the test level, this object is using a script called move and rotate. the scene works perfectly in the test however in the exported game the object won't move at all it just stays completely still.

![image](https://user-images.githubusercontent.com/68471279/232266282-d4253dd7-978a-4f22-95a3-7a7e459a1988.png)

**Comment by davetgc** [comment]
Can you please test this as a single level just with an object and this script please?

**Comment by casigus** [comment]
on it!

**Comment by casigus** [comment]
and figured it. ggmax isn't exporting the script. just doubled checked the folder and it wasn't in the export, which goes with the issue of ggmax not exporting everything correctly :(

**Comment by davetgc** [comment]
Just to check, is that a custom script?

**Comment by casigus** [comment]
yes! custom script!


________________________________

**Comment by casigus** [comment]
JUST exported this LEVEL as a standalone, the iceberg moves. copied the files from that standalone level into the Titanic Historia  standalone nothing.

its broken. 

![image](https://user-images.githubusercontent.com/68471279/232343802-0b6eb40f-e54d-433c-801e-26a67bde77ad.png)

**Comment by casigus** [comment]
ON TOP of that, tried export the entire project again, max just crashes so thats fun.

**Comment by LeeBamberTGC** [comment]
@casigus We are corresponding via email on this project and other matters, so will move this to MEDIUM as it is a custom script. For HIGH bugs we are only focusing on scripts that come out of the box with the product as most new users will encounter those first and only do custom scripts down the road, and will probably get help from the community too.
