### ISSUE TITLE
Winzone error - GameGuru MAX

### ISSUE THREAD

**Issue by blackhat110** [TheGameCreators/GameGuruRepo#4482]
I've never had this problem, but today winzone started to go crazy and once it works and once it doesn't.

**Comment by davetgc** [comment]
For confirmation, as you saying that sometimes it works, and sometimes it doesn't?

And are you using test game or savestandalone?

**Comment by blackhat110** [comment]
I use standalone. And yes - once it works and once it doesn't

**Comment by blackhat110** [comment]
I use standalone. And yes - once it works and once it doesn't

**Comment by blackhat110** [comment]
It works!
