### ISSUE TITLE
GG Max - EXP - BUG - Changing / Creating HUD screens incredible HARD due to constant BUGS

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4483]
As the title says, Whenever you try to change / create new HUD screens, its incredible hard due to bugs appearing.
I have found that if i add / change 1 thing, save Storyboard, Shut down Max, Reload Max, Then go and change / add another thing, the bugs do NOT happen.

Whenever you try and change to much or a few things before saving / shutting max down, reloading, The bugs appear.

Its hard to explain, but unless you have even tried messing around changing / creating HUDs then you will not see this.

**Comment by davetgc** [comment]
Can anyone else shed any light on this please?

**Comment by Tum1370** [comment]
@davetgc Why dont you just test this, It is bugged and there. Doesnt take much to find it, Try creating a new Inventory HUD screen, adding images, buttons, panels, youll see what happens.
In the end, if you dont start placing one item at a time, saving, unloading max, reloading max, adding one more item, You will see that the HUD starts to mess up when testing game.
Things will disappear on the HUD, things will go to the BACK rather than the FRONT.

These bugs take far longer to fix when you hit them up with Waiting for more information tag.

**Comment by davetgc** [comment]
@Tum1370 - Because I am testing it, and I can't find anything major wrong. My time is limited, so I'm asking for feedback from other users to see if they can replicate this.

**Comment by Tum1370** [comment]
@davetgc Ok, i just tested this on a totally blank project, Added a new HUD screen. Then created exactly the same Inventory HUD screen that i did last night, Same image, same setup, same buttons, Everything was the same.
Created it all in one go, without saving and reloading, Then tested the inventory in a blank test game. 
It worked totally fine.

So i really dont know why last night when i created the NEW HUD SCREEN, for an inventory, It was completely bugging out every time i tried adding stuff and testing it.
I was getting ITEM:DESCRIPTION missing in game
i was getting INVENTORY:PLAYER missing in game.

and so on.
So a very strange bug, but it is there !

**Comment by davetgc** [comment]
@Tum1370 I'm sure it is there, but we need to try to find a way of replicating it for the dev team, as their time is better spent fixing bugs that finding them. So, once again, if anyone else can find a sure way of replicating the issue that would be very useful.
