### ISSUE TITLE
Issue with particle editor and portals

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4484]
When trying to create a new Portal Particle in the particle editor, it seems like when exported, it does not properly import into gamegurumax.

Steps to re-create the issue.

Click on Add New Particle and bring it into the world.
Goto Particles tab on the right and select Add New Particle
Click on Create New particle
Click on File load effect startup and select portal5 or portal5low
Click Save, Fill in your information, and Export effect to max.
Go back to your particle library and bring in your new effect.

The portal effect seems to be getting squished on the Z axes.

**Comment by MonkeyFrogStudio** [comment]
I can confirm that Portal5 comes into MAX as a flat line instead of a round portal shape.

**Comment by smallg2020** [comment]
yes, looks like max is not respecting the emitter type (i.e. where it says 'box' or 'circle' etc) and sets it to 'line' instead
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/66390691/7af3a31e-e83f-43f7-bd35-1e79c5b563bf)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio @kadinshino No longer squished for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/14fdc558-eabb-4914-9dec-1389d02fa1b7)
