### ISSUE TITLE
Script Scuba  it does not work

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4487]
![image](https://user-images.githubusercontent.com/108415264/232715922-53a0cae1-c60b-4e37-bac6-775bbabaf7e5.png)

I did a mission to recover a wreck I put on the tank or mask but the scuba script doesn't work I report it doesn't start automatically when you are underwater

**Comment by davetgc** [comment]
Also reported here : #4345

I can't replicate this one again, can anyone else please confirm.

**Comment by Necrym59** [comment]
Have sent an update through as there were a couple of other things that needed fixing and have been fixed but one needs checking by lee at the moment.
