### ISSUE TITLE
GG Max - EXP - BUG - Changing ABOUT SCREEN or TITLE SCREEN and Image / Text after adding turns in to a button

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4488]
As the title says, If you add a image or text to the ABOUT SCREEN or the TITLE SCREEN, then go back to storyboard, and back in to ABOUT / TITLE screen the image / text will now be a button.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed and will be in the next EXP update :)

**Comment by Tum1370** [comment]
@plemsoft I can confirm that this bug is now fixed, Thanks for the fix. Ill close this issue now.
