### ISSUE TITLE
Grass draw distance does not change in standalone game test via storyboard

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4489]
As the title says, Do the very simple LOW / MEDIUM / HIGH graphic settings actually do anything to the game ?
After testing this they do not seem to work at all, then after checking the screens you can see that the buttons have no actions attached to them ?

![Untitled](https://user-images.githubusercontent.com/66874403/232720410-1d91a55f-8e85-4281-be3c-6dd5002b1b8e.png)

**Comment by Kitakazi** [comment]
Graphics settings should have options for 

-Resolutions
-Vsync
-Anti-Aliasing 
-Shadow Quality
-Maybe other post process effects like Bloom

**Comment by LeeBamberTGC** [comment]
@Kitakazi Once this above is confirmed, we can turn this issue into a feature request for more (and better) options

**Comment by Tum1370** [comment]
@LeeBamberTGC I Think this FIX has now broken my Standalone game graphics.
I always want mine set at HIGHEST.

But i have reported another bug here, i guess this is due to this FIX (Which hasnt fixed it for me) https://github.com/TheGameCreators/GameGuruRepo/issues/4514

Also, I cannot change anything to do with the GAME Settings due to another bug i have reported here. (I cannot even fix this and set it back to normal to test this.
https://github.com/TheGameCreators/GameGuruRepo/issues/4505

**Comment by Tum1370** [comment]
I tested the GRAPHIC SETTINGS using the TEST ALL LEVELS STANDALONE from the Storyboard, and the graphic settings worked fine from there.
But CLEARLY DO NOT work in a Standalone.

**Comment by Tum1370** [comment]
Also, another thing is, "Why dont they start as HIGHEST SETTING" when testing from the STORYBOARD.

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just re tested this GRAPHIC SETTINGS on a newly created Standalone.
I see that they start on MEDIUM SETTING, If i change the SETTING to HIGH, then that works now, And i can see the graphics look like i set in Editor.
But when i QUIT the game, then reload the game, the GRAPHIC SETTINGS are once again RESET to MEDIUM.

This needs to be saved, it would annoy a player having to SETUP Graphics Settings Everytime they load the game.

**Comment by Tum1370** [comment]
@LeeBamberTGC UPDATE to this BUG.
The Graphic Settings in Standalone DO NOT EVEN save between games. So If i play my game, I set the graphic settings to HIGHEST. Play the game, Its on the highest settings.
I then die, Then the game ends. I go back to MAIN MENU.
Click PLAY Again. The GRAPHIC SETTINGS needs to be adjusted again.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Cannot reproduce this one, might be related to the project you are using, as mine is fine. I built a two level game in latest EXP build from fresh, started it, it always defaults to HIGHEST, set it to LOW for this test:
![image](https://user-images.githubusercontent.com/35840583/233641103-8364c98e-1573-4742-a769-741d31031884.png)
I quit the game:
![image](https://user-images.githubusercontent.com/35840583/233641305-290acd54-8e27-436d-a28c-298652f6b6dc.png)
And start a new one:
![image](https://user-images.githubusercontent.com/35840583/233641336-3a217ab2-34f3-4d79-b891-a29b8f349dc3.png)
Pressed ESCAPE and clicked GRAPHICS SETTINGS, still shows as LOW, and has low settings:
![image](https://user-images.githubusercontent.com/35840583/233641406-57be0e95-a874-41b4-af39-3293e43ff856.png)

Cannot reproduce at this time.

**Comment by Tum1370** [comment]
@LeeBamberTGC Are you using a STANDALONE or TEST STANDALONE from the Storyboard ?

**Comment by Tum1370** [comment]
@LeeBamberTGC Ignore that last thing, as i just tested mine from storyboard and exactly same problem. The Graphic Settings DONT save for me AT ALL.

**Comment by LeeBamberTGC** [comment]
@Tum1370 The graphics settings system is not designed to save, only retains its state during the game sessions.  Once selected, it should stay that selection until you quit the game.

**Comment by Tum1370** [comment]
@LeeBamberTGC I was just trying to create a new project with just GRASS on for you to see this bug.
When i created a hilly landscape, Added full GRASS, set at 750 DRAW DISTANCE so basically the best.
The Moment i click TEST GAME, The game sets the GRASS to 3000 for me.

I Assume this is related to this GRAPHIC SETTING Bug as i have never had this before.

Screenshot 1 = Editor
Screenshot 2 = TEST GAME
Screenshot 3 = EDITOR after TEST GAME, See the 3000 set draw distance

![1](https://user-images.githubusercontent.com/66874403/233644703-a1ede470-7cdf-46fd-a753-f876ac8435c0.png)
![2](https://user-images.githubusercontent.com/66874403/233644712-93472eb3-e86e-409b-8f71-973df258552e.png)
![3](https://user-images.githubusercontent.com/66874403/233644723-384e8d0e-227d-4a87-a784-bb090b89c371.png)

**Comment by Tum1370** [comment]
> @Tum1370 The graphics settings system is not designed to save, only retains its state during the game sessions. Once selected, it should stay that selection until you quit the game.

Surely it has to SAVE them ? Think of every game you play, where you setup your graphic / sound settings, save them, Then everytime you play, it uses them settings ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 That would be a feature request as this functionality has not existed before now, and we are in feature freeze mode while we sort out existing functionality bugs.  I agree ultimately we need a more complex graphics settings screen and the ability to save all the choices by the gamer, we can look to design that after V1.

**Comment by Tum1370** [comment]
Ok. Well for me. This bug still exists as it does not remember between games. Without exiting game.

**Comment by Tum1370** [comment]
And that editor bug is very annoying setting grass to 3000. How can you setup your level with that ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you send me all your files so I can see what you see (project folder, level file, any custom assets you are using), thanks!

**Comment by Tum1370** [comment]
Also. The stand-alone setting should auto start at HIGHEST. I don’t want to EVERY time I play the standalone. Pause. Goto setting. Set HiGHEST. Then play.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you send me all your files so I can see what you see (project folder, level file, any custom assets you are using), thanks!  My freshly make two level project always starts in HIGHEST mode as intended. It could be your more custom project is triggering some kind of selection to MEDIUM.

**Comment by Tum1370** [comment]
@LeeBamberTGC I wished i had not even mentioned these GRAPHIC SETTINGS bugs, because its just causing me a load of problems.
Those images above was not even a project, It was a new project called EMPTY, Made hilly using the sculpt terrain, Added grass at DISTANCE 750 (the max and best looking)
TEST GAME, 
totally ruin the grass in TEST game on editor.
Then stopped the TEST, and the editor had reset grass to 3000.

**Comment by LeeBamberTGC** [comment]
@Tum1370 The editor bug and the graphics settings bug are related, but different bugs in terms of reproducing them. The editor one is an easier fix, working on that now. Can you send that new empty project you mentioned that shows the graphics settings not starting in HIGHEST when the standalone exported from the project is run, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC 
This is the empty level.
Crafted landscape, Added grass, DRAW DISTANCE is 750 (The BEST)
TEST GAME
Grass gets reduced from the BEST (750 DRAW DISTANCE)
Stop TEST
Editor is now set at 3000 on the GRASS Draw Distance

[TEST LEVEL.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11296798/TEST.LEVEL.zip)

**Comment by Tum1370** [comment]
@LeeBamberTGC The other level is a fairly big level and will not post here due to size, And i need to package everything as its a small test level i keep working on when i see new stuff added.

**Comment by Tum1370** [comment]
@LeeBamberTGC I am currently TESTING another theory for this STANDALONE bug. 
I have rollback my GameguruApps folder to a version of this project just BEFORE i changed the STORYBOARD GRAPHIC SETTING screen, by adding a background, and changing buttons font / colour / size etc   
(Because this is another bug with the GAME PAUSED SCREEN that i have posted)
Maybe this changing of that screen has messed up the GRAPHIC SETTING start settings ?
Creating Standalone now so will let you know.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
OK, I can 100% CONFIRM that this bug DOES NOT HAPPEN on my level on the project BEFORE i changed the GRAPHIC SETTINGS SCREEN on the STORYBOARD.

The Standalone i just created using this OLDER COPY of my project BEFORE i changed the GRAPHIC SETTING screen, works fine in Standalone, and STARTS on the HIGHEST SETTINGS for GRAPHICS.

I am hoping this HELPS you fix this problem.

I am guessing this BUG is related to this NEWER post i also made here .https://github.com/TheGameCreators/GameGuruRepo/issues/4505

**Comment by Tum1370** [comment]
It would seem that whenever you changed any of the following screens in Storyboard, you start to get bugs.

Graphic Settings.
Sound Settings.
Game Paused Screen.

I am not sure about other screens like LOAD / SAVE etc as i have not tested or changed those yet

**Comment by LeeBamberTGC** [comment]
@Tum1370 I think you tracked it down, well done!  I should be able to handle it from here :)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Took my existing project and added Hello World text to it, then saved new standalone, and it was still fine:
![image](https://user-images.githubusercontent.com/35840583/233686475-42ba9a08-2d93-46fd-926a-77c632db7f38.png)

So I suspect the old game project you had was already corrupt by then (from previous EXP builds) causing the mess up.  If you see it in the future, attack that project folder zipped up and can look at the screens to see HOW they mess up.

I created a standalone from your TESTLEVEL ZIP (containing the TEST PROJECT) you sent earlier, and can confirm the HIGHEST mode was on by default:
![image](https://user-images.githubusercontent.com/35840583/233687466-ad3dcc34-826d-4fec-bdce-9ff05950b173.png)

I can also confirm (and I forgot) that the choice is saved when you leave the standalone and relaunch too, so setting LOW, quitting then rerunning the game it remembers you set it to LOW.

**Comment by LeeBamberTGC** [comment]
@Tum1370 If you can send a new project and let me know what issue to look for, I can attempt to reproduce here.  I have not checked the grass density on these tests as the other issue relating to that setting being messed up in the editor is not yet fixed, sorting that now.

**Comment by Tum1370** [comment]
@LeeBamberTGC That test level I sent earlier wasn’t this bug, that’s the grass density bug. 
That level had nothing to do with the GRAPHI SETTING SCREEN changed. 

Am guessing you didn’t add a transparent image behind the Graphic setting menu. 
por change the butt9ns font text size color etc

this is the bug.  Not just adding text to the screen. 

See the other bug I posted. 
I think ALL the settings screens on Storyboard are totally bugged and cannot be changed.

**Comment by Tum1370** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/4505

**Comment by LeeBamberTGC** [comment]
@Tum1370 New EXP build uploaded for you to test that resolves the issue about retaining the graphics settings, depending on what you select, and handles leaving and entering the game, and no longer messes with these settings when in the editor.  Thanks for the link to the other issue, and the messing up screens, we will use 4505 for that conversation. This one shall remain about the grass draw distance and the LOW, MEDIUM and HIGHEST settings all working in a standalone.

**Comment by Tum1370** [comment]
@LeeBamberTGC Here is a very simple level.
I let Max write a totally new gameguruapps folder, created the project, imported 2 images to change the GAME PAUSED screen. 
Moved and changed the GAME PAUSED buttons.
Then created the Standalone.

I DID NOT REPRODUCE THE GRAPHIC SETTING BUG, The Setting started on HIGHEST, so i am trying to find how to reproduce this on a totally new level now.

But this does show you how changing that ONE GAME PAUSED SCREEN, totally messes up buttons, I cannot delete the image in that screen if i try.
And in the Standalone, Try seeing what each button does ??

[NEW BUGGY PROJECT.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11297930/NEW.BUGGY.PROJECT.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Would this not be better posted on the "https://github.com/TheGameCreators/GameGuruRepo/issues/4505" issue as it relates to the screen messing up VS the grass draw distance that was originally posted?

**Comment by Tum1370** [comment]
@LeeBamberTGC Sorry, i just messed up my test, redoing it now, Yes that one definitilty shows that bug, ill redownload it, and add it there.

I will upload a new one for this bug here soon

**Comment by Tum1370** [comment]
@LeeBamberTGC OK, I finally got this saved so its small enough to post here.
Create the Standalone from this file project.
Start GAME
Look at the Grass.
Pause GAME.
Goto Graphic Settings (SAVE GAME - due to other bug)
Its not on HIGHEST.
Whatever you set it at here, does not change the graphics GRASS in game.

[mapbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11298244/mapbank.zip)
[projectbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11298245/projectbank.zip)
[imagebank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11298249/imagebank.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for these files, I can reproduce your issue now :)

**Comment by Tum1370** [comment]
@LeeBamberTGC Am glad you can finally reproduce this bug, Was driving me mad lol, i like my grass the way i set it lol
Anyway, sorry i keep finding lots of bugs for you to fix.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed for next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC I can now confirm that this bug is now fixed on the latest EXP build. My standalone does not start in HIGHEST setting, but when i change it to highest, the settings stays set at HIGHEST even after reloading the Standalone.
Thanks for the fix Lee. Ill close this issue now.

**Comment by Tum1370** [comment]
@LeeBamberTGC I have reopened this issue about graphic settings. I just tested a game in Test All Standalones, so it runs like the game would do as a standalone.
But even in the Highest graphic setting, the grass draw distance is not like i set it in the editor.

This bug seems to be back again and not fixed.

**Comment by LeeBamberTGC** [comment]
@Tum1370 I created a simple plains terrain and a hill to assess grass draw distance. As you can see, both standalone via the editor and a real standalone showed the same renderings, and you can also see the draw distance changes very little, only the 'density':
LOW:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/06c36d49-7afd-4ec0-98c5-0bb40cd35383)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5e76cc9b-4f6b-4116-a322-188cdbeba0ff)

MEDIUM:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8dbff8b3-8aa2-42c4-a3c2-075d48ae6540)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/502eb04b-7d48-4f95-a0b0-771875fd66b1)

HIGHEST:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/cb9c23ed-ea60-4a16-a1ff-039c7265eceb)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8060dd69-49d1-480b-8294-19660d054cc9)

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Have you actually just added a fix for this then ?

I have just tested this in Standalone Test All levels mode, on the same map that i found this bug.
And can confirm that this time i tested this, the graphic settings worked correctly.

That's why am wondering whether you added a fix ? Because it was definitely not working correctly.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Nothing recent, but did some work on the LOW/MED/HIGH code a while ago, so maybe this April report has been fixed. Still, if you do see it again, resurrect this issue and we will continue the hunt!
