### ISSUE TITLE
Changing Animation Speed doesnt do anything in .fpe

### ISSUE THREAD

**Issue by nigelmerle** [TheGameCreators/GameGuruRepo#449]
Hello there,
I have a big issue where my .x model <on animspeed  = 30>  plays very fast, I try to set animspeed to =1 but animation speed stays the same !!! , i checked in the .x file in notepad and animation is = 30 
I am currently in gameguru private beta, i checked in fragmotion and animation plays fine there, so the problem comes from gameguru

**Comment by GameGuruEvan** [comment]
Please send a zip of the files to gameguruevangelist@gmail.com and I will take a look

**Comment by GameGuruEvan** [comment]
You can get a more comprehensive control over your animations through LUA scripting.  I can direct you to a great guide that covers all aspects of this.  Please see the link below.
https://steamcommunity.com/sharedfiles/filedetails/?id=398177770

**Comment by nigelmerle** [comment]
Dear all thank you for banning me from the world of your wonderful closed forums !, you have such an excellent community !, and so today  some people said to me that they have been ignoring me and have been very unkind to me, i felt discouraged as a new user : it was not a good experience and this is why i am asking for an immediate refund for my gameguru purchase, i don't wish to continue  with this anymore because i feel also  that my money have been stolen from me , I have never been able to create a game with gameguru because the community is  not helpful and i have found out that gameguru is not such the 'easy game maker' as stated in your advertisements !, following to that I have also been getting very naughty comments from qualified members of your community, i think I am not the first person to go through this and everyone is ok with that, everytime a new user ask for something, they ignore us, enough is enough !, as customers i think we deserve the support as we requested !.. It is very worrying that gameguru is making itself such a bad reputation on the market, I hope I don't need to seek for my lawyer to have this matter cleared.
i thank you for your understanding




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Teabone3** [comment]
The only way to get banned from the forums is to breach an item off the AUP:
https://forum.game-guru.com/aup

The tagline for Game Guru is no longer "'easy game maker" as the engine became more and more dependent on LUA scripting.

"everytime a new user ask for something, they ignore us, enough is enough"

The Forums is a community of users just like you. It is of nobody's duty or responsibility to assist anyone really. For the most part the long term members are probably being drained at this point and treated like customer service support.
