### ISSUE TITLE
GG Max - EXP - BUG - Standalone does NOT copy the map image over

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4490]
As the title says, When you create a standalone game, the map image for the levels does not copy in to the Standalone folder.

**Comment by LeeBamberTGC** [comment]
@Tum1370 So if I create a two level RPG game standalone, the report is that the second map is not exported and the second level map when the map screen is activated shows no map?

**Comment by Tum1370** [comment]
@LeeBamberTGC Yes it seems that way to me at the minute. I have not tested this with more than 2 levels so not sure about additional map images as well.

**Comment by Tum1370** [comment]
@LeeBamberTGC I think i misread your question on this one, If you created a 2 Level Game, Both the levels have Map images for the Map Screen Hud, Then created the Standalone game. The only MAP IMAGE that seems to copy over to Standalone is the first Level Map Image. 
The second level copies over, but the 2nd level MAP IMAGE did not copy over.

I have NOT tested this on MORE than 2 levels so this maybe a problem with additional LEVELs MAP IMAGES as well ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed for next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC After just creating a standalone with 2 levels on it, i can now confirm that both MAP IMAGES were copied over to the Standalone. Thanks for the fix, I will now close this issue.
