### ISSUE TITLE
GG Max - EXP - BUG - Standalones and Winzones (Maybe Reset State problem ?)

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4491]
When you have the Winzone set to RESET STATE, and you start the same level again, My Pistol is not appearing in the Hotkey 1 slot that it should be.
Sometimes if i loot something i put that item in to hot key 1 slot, my gun totally disappears from me.
Other times if i put an item in the hotkey 1 slot, it goes in fine and works fine, My gun doesnt drop.

**ALSO, Look at the fish in the pond, First time they work fine, After playing level again some of them STAND UP like in the screenshot.**

![1](https://user-images.githubusercontent.com/66874403/232751221-62b87d4b-403b-4ad1-90fd-6d0b12179ebb.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Nice find, fixed for next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC This is NOT fixed in LATEST EXP BUILD.

But there are new bugs now regarding WINZONES, Am hoping that this fix has not caused my new bug.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Send me your project that shows this not working. I have my own little two level project and my pistol is retained on level two with the latest EXP build:
![image](https://user-images.githubusercontent.com/35840583/233640600-64c1d3c3-8a07-42a3-9eec-904b6d886a7d.png)

**Comment by Tum1370** [comment]
@LeeBamberTGC This is a screenshot of a newly created Standalone with this NOT working.
I cant send this project as it has Character Created Characters and First Aid and Armour entities added.
But as you can see, The gun slot 1 is empty, And the FISH are stood on there tails lol

![Untitled](https://user-images.githubusercontent.com/66874403/233641901-1b310923-5f67-4193-b260-5bce2459c428.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 It is best if I work with stock out of the box projects and levels, that way it reflects what new users will experience, rather than custom creations, etc.  It also speeds up the reproducing of the bug.  Email me your project and level, with all your custom media and I will see if I can reproduce the upright fishes and your hot keys issue which I guess is not a straightforward bug but a cumilation of many events in your creation process to arrive at the level you have now.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Rather than trying to upload my other bigger level with custom stuff, i have recreated a small pond, Added fish, and the character has the pistol.
Got to TEST ALL LEVELS STANDALONE.
Run left into the particles, to the winzone.
when you resapwn, the Pistol is missing from the slot 1
The fish are not acting as they should be. (Check the fish movement BEFORE you run in to the particles


[Desktop.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11297298/Desktop.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Two bugs here. Now reloading and reset level jumping retains a weapon you set as your starting weapon without adding it to the level, and physics collision state toggle now retained in save game files.  Fixed for next EXP build.
