### ISSUE TITLE
GG Max - EXP - BUG - Newly Added Buttons Not Doing Anything When Pressed.

### ISSUE THREAD

**Issue by DarthPickles666** [TheGameCreators/GameGuruRepo#4494]
So in the menu, there is now the option to add more buttons to take you to a new screen. However, when you actually load up a test game and click on the buttons, they do absolutely nothing. The pictures below show the 3 buttons connected to new screens, and the setup for the buttons. 

![image](https://user-images.githubusercontent.com/101579658/232832154-571b97e0-874e-4b27-a5a6-b5089fd0f610.png)
![image](https://user-images.githubusercontent.com/101579658/232832286-1b2a5952-c45b-476d-bf42-489d24e5bce8.png)

**Comment by plemsoft** [comment]
@DarthPickles666 Thanks for reporting this issue , just tried it here and it looks like its working fine, could you zip up your "project" folder and e-mail it to me so im able to see what is wrong with your setup , e-mail: plemsoft@gmail.com
Thanks for your help :)

**Comment by DarthPickles666** [comment]
Hi @plemsoft, I've sent you an email with the project file and a video showing the issues

**Comment by DarthPickles666** [comment]
Gonna add an update here - The buttons dont work in a saved Standalone either.

**Comment by plemsoft** [comment]
@DarthPickles666 Thanks for reporting this issue, this has been fixed and will be in the next EXP build.
Unfortunally you will have the delete all your custom screens and recreate them again, as the ids is messed up.
Also if you want to use multiply "BACK" buttons in a chain , like linking "title screen" -> "custom screen" -> "sound settings" , you will have to change the "back" button on the "custom screen" to "Go to another Screen" and link this "back" button to your  "title screen", like the image below :)

![back-but](https://user-images.githubusercontent.com/18662417/233770693-647a308a-c29d-4c4b-9b05-e0ac40dba35f.jpg)
