### ISSUE TITLE
GG Max - EXP - BUG - AI - Visual Link - Alert other character

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4498]
I remember watching this in one of the live streams, about how you can link multiple AI together using the visual link, And then set it so when one of the characters get attacked, The other characters linked together, then work as a team to attack the player.
This does not work.

i have attached a very simple level, with the 2 AI further back, Set to Always Active, Linked to the front AI.
When the front AI gets attacked, The BACK 2 should run and start working as a team and attack. They DO NOT ATTACK.

DO NOT MOVE FORWARD, JUST ATTACK FROM WHERE YOU ARE, ELSE YOU MIGHT AUTOMATICALLY ACTIVATE THE BACK TO ANYWAY.

[TEST LEVEL.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11271624/TEST.LEVEL.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Character attackers can now be alerted and run to alert positions, making some nice chain reaction gameplay in the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5aaaef51-470d-4cf3-8d72-a6a7062c3bf0)
