### ISSUE TITLE
GG Max - EXP - BUG - WinZones RESET STATE does not ALWAYS reset ALL Collectables

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4501]
As the title says, The Reset State on the Winzone, does NOT ALWAYS reset every single Collectable in the level.
Sometimes you use the winzone, replay the level and ALL collectables are Reset.
Most often it DOES NOT reset ALL collectables, but only RESETS SOME of the collectables.
Screenshot showing the Level has just RESET using the Winzone Reset State, but my character still has 1 First Aid box that he collected in the first time he played this level.
![Untitled](https://user-images.githubusercontent.com/66874403/233116688-eb15d346-4d0c-486a-ac49-e0bb68721601.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 This is by design. The LEVEL STATE RESET only resets the level states, not the player or the players inventory or hotkeys items.  There is a separate issue on the board that requests an additional feature to RESET PLAYER STATES.
