### ISSUE TITLE
GG Max - EXP Build - Cosmetic BUG - Creating Standalone screen

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4504]
When you click the create standalone screen, You always get the option of the location to save the Standalone game.
But the screen still then tells you the OLD original location where Max use to save the Standalone.

Really this just needs changing / removing etc.
Not really a bug, more of a **Why does it say the wrong location of the Game ?**
![Untitled](https://user-images.githubusercontent.com/66874403/233333792-ec227401-2d8f-487d-99b6-f833a5e25f05.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Good point, I have updated the redundant text for the next EXP build :)

**Comment by Tum1370** [comment]
@LeeBamberTGC Thanks, I will close this issue now as its fixed.
