### ISSUE TITLE
GG Max - Bug - Storyboard GAME PAUSED SCREEN

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4505]
After changing the GAME PAUSED SCREEN, Now the buttons do not go to where they are meant to.

All i did was ADD a image at the back of the screen, then changed the FONT / SIZE / COLOUR ? POSITIONS of the buttons, The Actions and the TEXT WORDS are still the same.
But now the following buttons do this.
LOAD GAME goes to SAVE GAME screen
SAVE GAME goes to GRAPHIC SETTINGS screen
GRAPHIC SETTINGS goes to SOUND SETTINGS screen

And SOUNDS SETTINGS + CONTROLS DONT DO ANYTHING.

Screenshot 1 shows what the screen loads like.
Screenshot 2 + 3 show the editor setting with the BUTTON names correct and Actions set to Goto another screen. (I did NOT changed them serttings from the original)

![1](https://user-images.githubusercontent.com/66874403/233337041-5304b29c-aec8-4238-bc32-25fe8620a861.png)
![2](https://user-images.githubusercontent.com/66874403/233337709-073589f1-8edf-40cb-96b0-0dcc256610ff.png)
![3](https://user-images.githubusercontent.com/66874403/233337721-3bc6dd00-226f-4832-8b54-70d46f1bba35.png)

**Comment by Tum1370** [comment]
How are we suppose to FIX this bug ?
I CANNOT DELETE the buttons and RE ADD them ?
I CANNOT DELETE THE ADDED SCROLL IMAGE.

This whole page is bugged, and i didnt really change anything.

**Comment by LeeBamberTGC** [comment]
@Tum1370 No worries, it's my job to fix bugs, I will look at this now and get back to you on my findings :)

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just added that same scroll image to the GRAPHIC SETTING menu, and creating STandalone now to TEST.
I think this will produce the bug about graphics

**Comment by LeeBamberTGC** [comment]
@Tum1370 Yay, I can reproduce the bug when I run the standalone from the NEW BUGGY PROJECT the buttons are indeed messed up when jumping to a new screen:
![image](https://user-images.githubusercontent.com/35840583/233697907-d1b48f17-735d-4751-ab36-750a26ceb931.png)

Leave with me, thanks for the project files!!

**Comment by Tum1370** [comment]
@LeeBamberTGC Also, with that GAME PAUSED screen.
You cannot delete anything, You cannot even delete that big SCROLL image i added.
Once it is added, It is there for good.

**Comment by LeeBamberTGC** [comment]
@Tum1370 In latest EXP build, buttons should now go to their correct screen as described by the storyboard.  The "output_x" system is a little outdated and was causing the issues, could be improved in the future but another approach closer to what the storyboard project data uses allowed this to be restored without changing the data structures for now.

I have changed the title to the new bug reported here, ideally, a new issue should be raised for different bugs as it is hard to mark off issues for testing and closing if new bugs are compounding old issues, especially if they are different fixes.

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok i just tested this GAME PAUSED bug on a Standalone.
Thanks for the fix with the buttons, now working as intended.
I have still noticed though a bug, The files i sent you, Try deleting that Big scroll image from the GAME PAUSED SCREEN that i added.
Nothing will delete it for me.

**Comment by LeeBamberTGC** [comment]
@plemsoft Need a way to delete elements from the core screens (perhaps limit to "newly added ones", keep the fixed ones so the screens cannot be messed up so much they do not work).

**Comment by Tum1370** [comment]
@LeeBamberTGC @plemsoft I just created a NEW PROJECT.
Added a image to the GAME PAUSED SCREEN.
Then tried to delete it.
It still does not delete ?

**Comment by Tum1370** [comment]
The buttons are working fine for me, The only problem i have now is deleting anything i add, like images or anything else.
I do have another issue open here about the deleting problem.https://github.com/TheGameCreators/GameGuruRepo/issues/4530

**Comment by plemsoft** [comment]
@Tum1370 Wait for the next EXP update , its still only a pull request that is waiting for a merge :)

**Comment by LeeBamberTGC** [comment]
@plemsoft @Tum1370 Latest commits now in EXP build :)

**Comment by Tum1370** [comment]
@LeeBamberTGC @plemsoft I can now confirm that this bug, and the deleting of images from these GAME PAUSED, GRAPHIC, SOUND, CONTROLS screens have been fixed in latest EXP Build.

One thing to add though for others who MAYBE have problems deleting images.
If the image is set at BACK, It will not delete.
You will need to set image to FRONT, Then hit Delete.

Thanks for the fix guys., I will close this issue now.
