### ISSUE TITLE
GG Max - EXP - BUG - New Screen on Storyboard

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4506]
When i just tried testing adding a NEW SCREEN on my storyboard, I was seeing if i could add a different LOADING SCREEN between levels.
I Clicked ADD NEW SCREEN.
Then selected a random screenshot (Ignore the image)
Then on the one BUTTON on the new screen, i set it to Goto another Level.
I then connected the New screen to the Next level.

BUT I CANNOT CONNECT THE LEVEL 1 to THE NEW SCREEN. The link does not work.

EDIT : Also, one the WinZone, you have the option to GoTo a Specfic level, But no option to goto Specific Screen, So really have to use the Follow Storyboard option and link it from here.

![Untitled](https://user-images.githubusercontent.com/66874403/233340341-844a7066-f848-4913-987e-1523c6997a26.png)

**Comment by LeeBamberTGC** [comment]
@plemsoft You may have fixed this if you did work on the link IDs, which I noticed was a little messed up. I used a secondary approach to fix the "button not going to correct screen" issue from another issue, but ideally the link IDs need to behave.

**Comment by plemsoft** [comment]
@LeeBamberTGC No the loading screen is special , and currently static "titlebank/loading.lua" , so this is a new feature button "add loading screen" that will have to link level to level. it uses the special progress bar filled from loading progress.

**Comment by plemsoft** [comment]
@Tum1370 @LeeBamberTGC This has been added to the next EXP build.

**Comment by Tum1370** [comment]
@plemsoft @LeeBamberTGC Just testing the NEW LOADING screen button now.
My game uses the Winzone Goto Level option, And does NOT follow the storyboard, As i guess a lot off games will.

Does this NEW LOADING SCREEN work when going to a specific level, or does it just use the SAME OLD LOADING screen ?

This option really needs adding to the WinZones, that you can select loading screen or something ?

**Comment by Tum1370** [comment]
@plemsoft @LeeBamberTGC I just checked in game, I DONT HAVE any options to LINK to New levels LOADING screen, From the WINZONE, GOTO specific level.

**Comment by plemsoft** [comment]
@Tum1370 When you link to the level from the winzone .. it will look up that level , and go back from there and see what loading screen that level have assigned and use that for the loading screen :)

**Comment by Tum1370** [comment]
@plemsoft Ok thanks, ill will try that now

**Comment by Tum1370** [comment]
@plemsoft Sorry to say, but after just adding the 2nd loading screen to my game, When i took my winzone to a specific level, The LOADING screen was the original loading screen.

**Comment by Tum1370** [comment]
@plemsoft I know i closed this issue yesterday, But this NEW LOADING SCREEN has created a new issue.
I have posted the NEW ISSUE here,https://github.com/TheGameCreators/GameGuruRepo/issues/4567

But after rolling back my project saves to before adding the NEW LOADING screen, The BUG was NOT there.
I then re added a new LOADING SCREEN, and this BUG started straight away.

**Comment by Tum1370** [comment]
Closing this issue as a new issue for the new problem has already been opened.
