### ISSUE TITLE
GameGuru MAX - Bug - Smart Object (Group) Doesn't Show Light

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4508]
There is an issue when creating a group where any new group dragged into a scene does not display a light object if there is one that's a part of the group.

This image shows three objects selected, one of which is a standard point light:
![so1](https://user-images.githubusercontent.com/36735507/233436249-abef4988-0309-4142-8e49-04a87e0a3b4b.jpg)

This shows the three made into a group:
![so2](https://user-images.githubusercontent.com/36735507/233436325-51191acd-c1f8-4e0a-a044-2463ab0cb4f5.jpg)

This shows the new group after having been dragged into the scene:
![so3](https://user-images.githubusercontent.com/36735507/233436409-8cb99c1f-2b23-4ddd-9856-f8e60fc37d4e.jpg)
Notice that the light object does not appear.

And here's a second one dragged into the scene:
![so4](https://user-images.githubusercontent.com/36735507/233436553-9a5279c1-6924-4672-91d9-d12175be56e3.jpg)
The light object does not show up there, either.

However, if I ungroup the group, the light object re-appears:
![so5](https://user-images.githubusercontent.com/36735507/233436689-1952af26-068e-4a47-9d49-c60ea5b81b1e.jpg)

And the second group ungrouped as well:
![so6](https://user-images.githubusercontent.com/36735507/233436726-2e0ca0b8-1673-49df-aa60-7c6c972b030b.jpg)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Fixed for next EXP build :)
