### ISSUE TITLE
Bug Script NPC Flashlight

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4509]
![image](https://user-images.githubusercontent.com/108415264/233468774-4c79ffe2-ab2c-4062-9a40-ee3e900fd86d.png)

**Comment by synchromesh62** [comment]
Works perfectly here
Bet you forgot to put the NPC name in :)

**Comment by SampeyFS** [comment]
![image](https://user-images.githubusercontent.com/108415264/233560565-9bf83efc-f060-439e-94be-fa983beb4014.png)

**Comment by synchromesh62** [comment]
You attach the script to a spotlight beside the character not just any old object.

![SP](https://user-images.githubusercontent.com/35708217/233602547-b9077aa4-efa7-4860-9148-5a9f545babd6.png)

**Comment by SampeyFS** [comment]
ah OK now I try THANK YOU

**Comment by SampeyFS** [comment]
![image](https://user-images.githubusercontent.com/108415264/233616468-98ec3886-057f-49af-8470-0a29a1daa31e.png)

Nothing changes always the same lua error

**Comment by synchromesh62** [comment]
just tested again .. you must be doing something wrong
it works fine my end ?

![FL](https://user-images.githubusercontent.com/35708217/233622695-4fc9a117-ad18-4568-93bc-3effc80ba899.png)

**Comment by SampeyFS** [comment]
until there are after you put the script in an object the name of the character and that error comes out to me

**Comment by synchromesh62** [comment]
https://user-images.githubusercontent.com/35708217/233628953-871c0010-2e8f-4c32-bd6f-0b9f81e8185d.mp4

**Comment by SampeyFS** [comment]
Thank you so much it works now my mistake i used to make the group now works thanks man
