### ISSUE TITLE
Hurt Behavior shakes screen

### ISSUE THREAD

**Issue by WhitewolfgamingYT** [TheGameCreators/GameGuruRepo#4513]
When using the hurt behavior and adjusting the timing and damage done it shakes the camera see below.
https://youtu.be/EN2hhJRMybA

**Comment by WhitewolfgamingYT** [comment]
It seems to only shakes the screen when the damage done is changed resetting the damage to 1 and adjusting time allows it to work as its supposed to

**Comment by Necrym59** [comment]
It shouldnt shake at all anyway
