### ISSUE TITLE
GG Max - EXP - BUG - Latest build and NO SPAWNING WINZONES

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4515]
After running around and around on my map after killing everyone, my winzone did not spawn in the latest build.
I have random keys spawn, when you find that one key that spawns, it activates the WinZone, a Jeep, and Some Green smoke.
IT WAS WORKING PERFECT !!!
Now It works find in TEST STANDALONE in MAX.
BUT DOES NOT WORK IN STANDALONE .

This program gets worse and worse with every fix :(

**Comment by LeeBamberTGC** [comment]
@Tum1370 An error crept into WINZONE script, fixed for new EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC Thanks for the fix, ill close this issue now.
