### ISSUE TITLE
Fusebox error

### ISSUE THREAD

**Issue by Jisafu** [TheGameCreators/GameGuruRepo#4516]
Something is wrong with the fusebox (GG Max)
![fusebox_Error](https://user-images.githubusercontent.com/105353315/233658747-59b04a37-8fe7-4824-a6e3-94e73218c8cd.jpg)

**Comment by Necrym59** [comment]
Cannot replicate can you give more information

**Comment by Jisafu** [comment]
I think it's resolved. It was my mistake, sorry
