### ISSUE TITLE
GGMax will NOT RUN - A component of path does not name existing directory or path is empty

### ISSUE THREAD

**Issue by relishrompgames** [TheGameCreators/GameGuruRepo#4518]
I haven't had any issues since I bought GGMax like this one. 

I updated GGMax today and have this error -" A component of path does not name existing directory or path is empty for "C\Users\John\Documents\GameGuruApps\GameGuruMax\files\entitybank\user......" After I click OK I get a 8003 error. ALSO... I uninstalled GGMAX and downloaded it again.  Is this the correct build? GameGuru MAX Build 2022.10.14  That's what downloaded...     Thanks

**Comment by davetgc** [comment]
Please try the experimental build and see if this is still an issue. I've attached a link giving details of how to access it.

https://github.com/TheGameCreators/GameGuruRepo/discussions/3916

**Comment by relishrompgames** [comment]
Solved: - The issue was triggered by me deleting my old maps/test levels in my documents. It looks like GGMax was looking for them and since they were not there GGMax would not run. My solution was to uninstall GGMax and STEAM and then install Steam again and then installed GGMAX. Doing that made GGMax run again.
