### ISSUE TITLE
Menu buttons inoperative running games from the Hub ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4520]
It appears for me that the menu buttons do not respond when running games from the Hub ?
They will if you tick the " **Standalone test all Levels**  "  but other than that they do nothing when clicked.

https://user-images.githubusercontent.com/35708217/233739339-52ea8de3-2b72-4722-904b-932e60c3d79b.mp4

**Comment by Tum1370** [comment]
Just tried this and i get exactly the same thing, They dont do anything, if you DONT have Standalone Test All Levels ticked.
