### ISSUE TITLE
GGM - BUG - VSYNC setting isn't saved with your project

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4522]
VSYNC needs to be toggled off every time you re-open your project. MAX appears to remember and save all of the other settings you change under the post processing tab with your project except for this one.

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Confirmed, the VSYNC does not seem to be saved anywhere. I have added it so it saves per-level, just in case there is a need for certain levels to go nuts with high FPS on machines that can deal.  Will be in next EXP build, but will only take effect when you next save your level with the VSYNC flag assigned.
