### ISSUE TITLE
GG Max EXP Build- Unused Ingredients disappear after crafting

### ISSUE THREAD

**Issue by dadgood** [TheGameCreators/GameGuruRepo#4527]
If you add items to the ingredients bar in crafting and then leave, any surplus items disappear. For example if the recipe requires one Plant A and one Plant B but you had 2 of each and then craft ( This happens whether crafting works or not ), when you leave crafting all plants will be gone from inventory. So in below example, even though the crafting did not work when I click on leave the plants get removed from my inventory.

![image](https://user-images.githubusercontent.com/74854393/233784850-f21bd298-8e05-4603-8038-9f80c3924e7a.png)

![image](https://user-images.githubusercontent.com/74854393/233784858-0d2c4fd1-abf7-4074-afa1-7c1c4a8f45e5.png)

**Comment by LeeBamberTGC** [comment]
@dadgood This is my design. The plants are still on the crafting table in your scenario. You need to drag your ingredients back into your inventory to retain them:
![image](https://user-images.githubusercontent.com/35840583/234048388-bced10a3-6d0d-4e70-91d7-e201b41dd0c9.png)
