### ISSUE TITLE
GGM - BUG - The "door rotate" script seems to confuse the AI

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4528]
They don't appear to know that the "door" is "closed" if the player closes it after it's been opened.

https://user-images.githubusercontent.com/103399301/233786265-4e5f1d47-1e1f-4a87-b5b3-90f44fc5e5be.mp4

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Check the next EXP build, the characters are instructed to stop and conduct a stand-and-shoot logic if their NAVMESH disappears under them (i.e. when the player closes a door):
![image](https://user-images.githubusercontent.com/35840583/234050213-d0e3dd3e-b99a-474d-b0aa-a8791cb0cf8c.png)
