### ISSUE TITLE
GG Max - EXP - BUG - Can NEVER delete an image that you ADD to a SCREEN on Storyboard

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4530]
Whenever you add a image to any of the Main screens on Storyboard, You can never delete that image.

GAME PAUSED
GRAPHIC SETTINGS
SOUND SETTINGS
CONTROLS

Maybe more, these are the ones i have tested, and got images now stuck on them

**Comment by plemsoft** [comment]
@Tum1370 This should be fixed for new project from the next EXP build :)

**Comment by Tum1370** [comment]
@LeeBamberTGC @plemsoft I can now confirm that this bug of deleting of images from these GAME PAUSED, GRAPHIC, SOUND, CONTROLS screens have been fixed in latest EXP Build.

One thing to add though for others who MAYBE have problems deleting images.
If the image is set at BACK, It will not delete.
You will need to set image to FRONT, Then hit Delete.

Thanks for the fix guys., I will close this issue now.
