### ISSUE TITLE
GG Max - NPC Patrolling doesn't work in buildings, with Melee Attack Behavior it doesn't work at all (character just stands)

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#4533]
[https://www.youtube.com/watch?v=cxEMYfp0TwU](url)

**Comment by LeeBamberTGC** [comment]
@NewWave2137 Fixed for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0b50c8c8-2b6a-452b-a3ae-042c6b6d3dbe)
