### ISSUE TITLE
standalone multiple crashes

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4535]
Just had a lovely streamer to a play test of the standalone and it crashes at random intervals with out warning and there are no common factors to the crashes, they just happen when they happen. 

What we did conclude was that its something to do with them having a AMD processor, which rung bells to previous AMD bug reports.

It also feels like theres a memory leak in the standalone which would also explain the randomness of the crashes, they dont happen at the same point, they just tend to happen at any point during play!

**Comment by davetgc** [comment]
Do you know the system specs of the user? It could well be AMD related.

**Comment by casigus** [comment]
on my end the stand alone works from start to finish, did another run through last night no issues, no crashes, everything working as its suppose to.

the lovely person who tested it on her end (and on twitch) it crashed countless times at random intervals.

here are her specs.

CPU: AMD Ryzen9 3900X 12 core 4.6 GHz
CPU Cooling: Corsair H115i Pro XT
GPU: ASUS TUF OC 3080
RAM: 32GB Corsair Vengeance RGB Pro (2 x16GB)
Motherboard: ASUS ROG Crosshair VIII Hero X570
Storage: 3x SSD Samsung 860 Pro Sata III (3TB total)
M2: Samsung 980 Pro 1TB
M2: Samsung 980 Pro 2TB
PSU: Corsair RM850x
Case: Corsair Obsidian 500D Midi Tower - Black Tempered Glass
OS: Windows 10 64bit

her pc is 1000 times better than mine, yet mine runs it better which also thought was very odd.

my system specs are...

[cid:90ac926f-d372-4eab-8b4f-da3bcad7d83c]

[cid:4c8c2130-de3c-46e8-99f0-6f045a7bac9a]


so my guts are saying its some how an AMD issue and a memory leak.



________________________________

**Comment by casigus** [comment]
![342797507_619689196362212_3119893009342992941_n](https://user-images.githubusercontent.com/68471279/234078166-4bed2306-81ab-411b-839a-dd4122fb853e.png)

**Comment by LeeBamberTGC** [comment]
@casigus Since this report we have made many AMD related fixes and all Steam reports on AMD issues now settled. If you find you can still reproduce this one in the latest EXP build, please post here, thanks!
