### ISSUE TITLE
Hud Elements not always displaying in test game

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4539]
In the hud editor the Elements look like this:

![image](https://user-images.githubusercontent.com/99803873/233921956-9f011554-201e-49f6-aef9-b178d9d32508.png)

In test game some are missing, the exact ones appear to be random.

![image](https://user-images.githubusercontent.com/99803873/233922158-2a5d5d37-a37f-492a-a5ba-2e446aaa9c1d.png)

**Comment by plemsoft** [comment]
@davetgc Thanks for reporting this issue, could you zip the project folder that have this problem and e-mail me a download link to e-mail: plemsoft@gamil.com , this will allow me to see what the problem is, thanks for your help :)

**Comment by plemsoft** [comment]
@davetgc I do not see the same here in the project you sent me , there are some images that have "Hide Image in Game" checked, they are the only one that dont display. could you check if that's what you see.  Also i notice there was some missing images that was pointing to "Wasteland HUD's Asset Pack Part 2" this is now called "Wasteland HUD's Assert Pack Part 2", do you have both ?

**Comment by davetgc** [comment]
Hi, that could be the issue, but it clearly should be called Asset Pack :). Let me update my files and I'll let you know.

**Comment by davetgc** [comment]
That seems to be the issue. I'll close this.

**Comment by plemsoft** [comment]
@LeeBamberTGC Perhaps rename Assert to Asset :)
