### ISSUE TITLE
Help Gameguru does not detect bitmap portraits exported from gimp software 64 x 64  !

### ISSUE THREAD

**Issue by nigelmerle** [TheGameCreators/GameGuruRepo#454]

**Comment by nigelmerle** [comment]
Gameguru does not detect bitmap portraits exported from gimp 64 x 64  ! <i am using gameguru beta>

**Comment by HierToo** [comment]
You need to check at the export in gimp
compatibility options -> do not write color space information

Then you can see the bitmaps in GG

**Comment by nigelmerle** [comment]
I did what you said, images still not showing up  in gameguru, im on the beat version

Best regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by HierToo** [comment]
Export Image as BMP:
"Uncheck" Run-Length Encoded
Compatibility Options -> "Check" Do not write colour space information
Advanced Options -> "Check" 24bits

This is tested with Gimp 2.10.6

**Comment by nigelmerle** [comment]
It works now, thanks for your support..it was the 24 bit that made it work 😊

cheers

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nigelmerle** [comment]
Hello I need some advice, I have a multitextured character.And I would like to know if it is possible to declare it that way in the .fpe file, would it work in the beta version of gameguru???

In my fpe I wrote :

;visualinfo
textured1         = angel_D.dds
textured2         = angelhair_D.dds
textured3         = angellogo_D.dds
textured4         = angelwings_D.dds

The other textures I placed them in the same folder :
angel_D
angel_N
angel_S

angelhair_D
angelhair_N
angelhair_S

......etc


I am doing it that way because I would like the character to benefit from character_basic.fx shaders...This particular character I was not able to generate a texture atlas automatically for him because I was getting texture mapping problem in unwrap 3d, texture would be mapped uncorrectly in unwrap 3d. I do not have a lot of knowledge in packing textures, I am currently using unwrap 3d packing solution which seems to be working fine for me 90 percent of the time, I am using their latest beta. I contacted the support there concerning the weird texture issues after packing my character and he told me that because my model textures was tiled and that unwrap 3d does not know how to perform this, so I have to do it manually. I would be happy to know if there are other ways to declare multitextured characters in gameguru other than that in order to benefit from the gameguru shaders.

Best regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nigelmerle** [comment]
I would like to report an issue as well. I have imported all my characters in gameguru, all the animations seems to be working fine, however if I put my custom idle character on a player marker then the weird stuff begin, the model plays more than one animation in a loop while it is supposed to be playing only the idle animation i set in the .fpe...can you confirm if there is a workaround for this.

cheers

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Nigel Merle <nigelmerlin@hotmail.com>
Sent: Wednesday, November 21, 2018 8:16:10 PM
To: TheGameCreators/GameGuruRepo; TheGameCreators/GameGuruRepo
Cc: Author
Subject: RE: [TheGameCreators/GameGuruRepo] Help Gameguru does not detect bitmap portraits exported from gimp software 64 x 64 ! (#454)

Hello I need some advice, I have a multitextured character.And I would like to know if it is possible to declare it that way in the .fpe file, would it work in the beta version of gameguru???

In my fpe I wrote :

;visualinfo
textured1         = angel_D.dds
textured2         = angelhair_D.dds
textured3         = angellogo_D.dds
textured4         = angelwings_D.dds

The other textures I placed them in the same folder :
angel_D
angel_N
angel_S

angelhair_D
angelhair_N
angelhair_S

......etc


I am doing it that way because I would like the character to benefit from character_basic.fx shaders...This particular character I was not able to generate a texture atlas automatically for him because I was getting texture mapping problem in unwrap 3d, texture would be mapped uncorrectly in unwrap 3d. I do not have a lot of knowledge in packing textures, I am currently using unwrap 3d packing solution which seems to be working fine for me 90 percent of the time, I am using their latest beta. I contacted the support there concerning the weird texture issues after packing my character and he told me that because my model textures was tiled and that unwrap 3d does not know how to perform this, so I have to do it manually. I would be happy to know if there are other ways to declare multitextured characters in gameguru other than that in order to benefit from the gameguru shaders.

Best regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by HierToo** [comment]
1) The engine get the texture information for multitexture models directly out of the model

2) Without an example it is hard to judge if your model has a problem or it is the engine. The get a better answer go into the GameGuru forum: https://forum.game-guru.com/

**Comment by nigelmerle** [comment]
But the thing is that nobody want to help me on the forum they told me to contact the support team from the creators website so, it seems  that nobody wants to help ☹,
It seems that the multitextured model loaded with textures, I would be happy if I could get some more keywords to use in the .fpe file.

I told you about another issue I am having but you did not responded to it,it is about a model controls which seems to be messed up when I set the model on a player marker in gameguru.
I am sending you it, can you kindly check it. To reproduce the issue you need to put the character on a player marker in gameguru and go in compile mode and press the: w,s,a,d keyboard buttons and you will see that model is not centered on the screen instead it disappears from screen and goes in wrong direction. Awaiting for your reply.

Best regards


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nigelmerle** [comment]
Hello
When I click on my character I got some strange artifacts appearing on the screen. Check attachments

regards


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nigelmerle** [comment]
But the thing is that nobody want to help me on the forum they told me to contact the support team from the creators website so, it seems  that nobody wants to help ☹,

I told you about an issue I was having but you did not responded to it,it is about a model controls which seems to be messed up when I set the model on a player marker in gameguru.
I am sending you it, can you kindly check it. To reproduce the issue you need to put the character on a player marker in gameguru and go in compile mode and press the: w,s,a,d keyboard buttons and you will see that model is not centered on the screen instead it disappears from screen and goes in wrong direction. Awaiting for your reply.


Links to the model:

https://drive.google.com/open?id=1bmFXldhQDU9s6FuRFpjNK5WEFGnba-9F

Best regards


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by synchromesh62** [comment]
Hi Nigel 
You have had an extreme amount of help on the forums 160 posts in all and still are in fact today Myke is helping you and you have emailed him your models … One issue is solved for you and you start another.
However this is not a forum and its almost impossible to replicate your issues unless Lee uses the identical software and models your using which is Most unlikely ...

**Comment by nigelmerle** [comment]
I am very grateful for your help, thank you to Lee and your team for giving us the chance to build our game on your platform !. I did gave some directives on how to reproduce my issues to help your team eliminate these bugs and issues I am knocking through everyday into gameguru beta, I am on the private beta and this is very important to you. I haven’t finished to import all the characters, some works and some have a few issues.

People on the forum asked me to send my models there and whatever we users do, this is something very private, when publicly uploaded anyone can have access to our work.
I am not mad but only concerned about privacy issues on this forum.
I was kind enough to send my models to mike , some people wouldn’t.

I have received a great amount of help from unwrap3d team as well and they explained to me how to handle these models and I am very grateful for every help I can get including your team, I always try to help myself first even though I am not a programmer I am learning, this process is slow and sometimes it can be a nightmare. I am looking forward for a positive response from your team.

Best regards


Nigel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nigelmerle** [comment]
Dear all thank you for banning me from the world of your wonderful closed forums !, you have such an excellent community !, and so today  some people said to me that they have been ignoring me and have been very unkind to me, i felt discouraged as a new user : it was not a good experience and this is why i am asking for an immediate refund for my gameguru purchase, i don't wish to continue  with this anymore because i feel also  that my money have been stolen from me , I have never been able to create a game with gameguru because the community is  not helpful and i have found out that gameguru is not such the 'easy game maker' as stated in your advertisements !, following to that I have also been getting very naughty comments from qualified members of your community, i think I am not the first person to go through this and everyone is ok with that, everytime a new user ask for something, they ignore us, enough is enough !, as customers i think we deserve the support as we requested !.. It is very worrying that gameguru is making itself such a bad reputation on the market, I hope I don't need to seek for my lawyer to have this matter cleared.
i thank you for your understanding




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Nigel Merle <nigelmerlin@hotmail.com>
Sent: Saturday, November 24, 2018 11:54:05 AM
To: TheGameCreators/GameGuruRepo; TheGameCreators/GameGuruRepo
Cc: Author
Subject: RE: [TheGameCreators/GameGuruRepo] Help Gameguru does not detect bitmap portraits exported from gimp software 64 x 64 ! (#454)

I am very grateful for your help, thank you to Lee and your team for giving us the chance to build our game on your platform !. I did gave some directives on how to reproduce my issues to help your team eliminate these bugs and issues I am knocking through everyday into gameguru beta, I am on the private beta and this is very important to you. I haven’t finished to import all the characters, some works and some have a few issues.

People on the forum asked me to send my models there and whatever we users do, this is something very private, when publicly uploaded anyone can have access to our work.
I am not mad but only concerned about privacy issues on this forum.
I was kind enough to send my models to mike , some people wouldn’t.

I have received a great amount of help from unwrap3d team as well and they explained to me how to handle these models and I am very grateful for every help I can get including your team, I always try to help myself first even though I am not a programmer I am learning, this process is slow and sometimes it can be a nightmare. I am looking forward for a positive response from your team.

Best regards


Nigel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nigelmerle** [comment]
Dear all thank you for banning me from the world of your wonderful closed forums !, you have such an excellent community !, and so today  some people said to me that they have been ignoring me and have been very unkind to me, i felt discouraged as a new user : it was not a good experience and this is why i am asking for an immediate refund for my gameguru purchase, i don't wish to continue  with this anymore because i feel also  that my money have been stolen from me , I have never been able to create a game with gameguru because the community is  not helpful and i have found out that gameguru is not such the 'easy game maker' as stated in your advertisements !, following to that I have also been getting very naughty comments from qualified members of your community, i think I am not the first person to go through this and everyone is ok with that, everytime a new user ask for something, they ignore us, enough is enough !, as customers i think we deserve the support as we requested !.. It is very worrying that gameguru is making itself such a bad reputation on the market, I hope I don't need to seek for my lawyer to have this matter cleared.
i thank you for your understanding




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jbthenext** [comment]
@nigelmerle 

You have had more support than anyone could ever reasonably expect, our support team have spoken to you in detail about the issue giving sound advice and you seem to have ignored it all.

You have been banned by our team because of your rudeness and bad attitude towards friendly forum members which will not be tolerated.

If you feel this is unfair please feel free to get in touch with customer support and they will tell you the same thing.
