### ISSUE TITLE
GGMax - EXP Build - Objects dissapear after saving (sometimes it happens not just after saving but after closing GGMax and opening it again)

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#4540]
https://youtu.be/qv3_3EqdjD8

**Comment by NewWave2137** [comment]
It happens randomly - I added two zombies and sledgehammer, saved level, and closed GG Max. When I returned to this level there was only one zombie, the rest of the objects were gone. I think there are some issues with saving, in one of my levels doors duplicated I don't know why, and when I delete them and click "save" - they return.

**Comment by kadinshino** [comment]
Just want to add this bug is still happening. I just encountered it now. I previously encountered it earlier but thought it was related to something else. but after watching your example video I had the exact same thing happen

**Comment by LeeBamberTGC** [comment]
@NewWave2137 A very strange one.  Naturally if this was a common bug, everyone would be reporting it :)  So my guess is that the location you are saving the FPM level to (for whatever reason) is not allowing the new file to be saved, and when the save process finishes, it loads in a level if there are any entities removed during the edit, thus you see the previous level without the objects placed.  Can you send me a short video showing where your FPM file is being saved ( showing the file properties), like so:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f8471004-b0f0-402a-8cd5-055d39109488)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4bcd4264-5d15-4467-ae73-5727dcc0db81)

And then doing the save, then showing me the same view so I can see the file has indeed been saved with the new changes, like so:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/cb51c04c-6b54-403e-aac0-1d14a11bbf0d)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6643ca8d-d7bb-411e-9b2f-93aa4c1149f6)

Many thanks!

**Comment by NewWave2137** [comment]
@LeeBamberTGC After the last few updates it doesn't seem to happen anymore.

**Comment by davetgc** [comment]
That's good news. Can we close this for now? If the problem comes back, you can reopen this issue.
