### ISSUE TITLE
GG Max - EXP - BUG - Collect Quests - Multiple Quantity

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4542]
I found the wording  wrong. The moment i ACCEPTED the quest, The QUANTITY already says 1 of 3.
This message stays on the screen always. Really that should not be constantly on the screen.
And also, when you go to harvest what i am picking up, I dont get the COLLECT ITEM message, or the ITEM HARVESTED message, probably due to the other message constantly on the screen.

Screenshot 1 : Straight after accepting quest.
Screenshot 2 : Nothing in inventory so why is the message saying 1 of 3 already ?
Screenshot 3 : No message to COLLECT ITEM, or ITEM HARVESTED.

![1](https://user-images.githubusercontent.com/66874403/234079473-8526652e-fad4-4a35-bf09-774482f0809a.png)
![2](https://user-images.githubusercontent.com/66874403/234079479-f98de8a9-9817-48b0-b579-ea77f4ec8f9f.png)
![3](https://user-images.githubusercontent.com/66874403/234079493-0d62352b-14c9-4bf1-b1bd-4260b3287de6.png)

**Comment by Necrym59** [comment]
No multiple quest is not fully functional yet

**Comment by Tum1370** [comment]
@Necrym59 ok thanks, will close those now.
