### ISSUE TITLE
GameGuru MAX - Bug - Material Name Issue with Multiple Materials

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4546]
This is an old one that seems to keep coming back over and over again (or at least it's similar), but single objects with multiple materials import with the names of the materials incorrect. Here's a simple example:

Here are two cubes in Blender. Each cube has it's own material:

![material1](https://user-images.githubusercontent.com/36735507/234275990-1dbc644f-48d4-4ce0-be70-91bf715e3bc7.png)

You can see that the material names are Test1 and Test2.

I exported the model twice. The first time, the two cubes were kept as separate objects, but exported as one. The second time the two models were joined in Blender as one object (each with their own material) and exported as one. When I import either model, I get two materials, but both have the SAME NAME so it's difficult to tell which material name represents which material:

![material2](https://user-images.githubusercontent.com/36735507/234276474-07bf5ea2-97ae-40a3-8e95-437c2cd1124e.png)

This is true for either model (here's the second one):

![material3](https://user-images.githubusercontent.com/36735507/234276538-91510f56-adf5-46ff-afc0-dd481e6a8f0e.png)

One of them came in and choose to name both materials as Test1. The other one came in and decided to name both materials as Test2. Neither successfully names the materials as one being Test1 and the other as being Test2. However, both Test1 materials are separate materials. I can select one of them and change its properties and it changes only the one cube:

![material4](https://user-images.githubusercontent.com/36735507/234276873-6735a948-0d94-4b8c-96ab-4e60c791b75b.png)

The same is true with the other:

![material5](https://user-images.githubusercontent.com/36735507/234276907-0e2e8930-211a-425f-be7a-96c2b9c2619a.png)

This is not correct behavior. MAX needs to be able to import single objects with multiple materials and get the material names correct, else the end-user is going to have to guess at which material is which.

**Comment by MonkeyFrogStudio** [comment]
BTW - Here are the two cube test objects, if you require them to help find the issue:

[cube_test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11322487/cube_test.zip)

**Comment by bond1mjb** [comment]
Works fine here.  I've got two cubes combined as a single object.  The left cube is assigned a material called "test1" and the right cube is assigned a material called "test2".   Both materials import named as expected.  I've attached my FBX file for comparison.    

Tested and working in exports from both 3ds max and Blender.
![mulitmat](https://user-images.githubusercontent.com/87768878/234605000-51eee176-2429-4369-aef2-7410639954dd.jpg)
[boxes multimat.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11333915/boxes.multimat.zip)

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb And, yet, this is what I get when I import the two models from the link I provided above:

![mat1](https://user-images.githubusercontent.com/36735507/234613599-056928e6-1508-4b1b-9393-3a17af71b399.png)

![mat2](https://user-images.githubusercontent.com/36735507/234613635-59eb488d-bae4-4a29-8669-5ecc1d7097f4.png)

One of the above is a single model (joined as one in Blender and exported as FBX). The other is two models (not joined in Blender), but both selected to export as one model via FBX. In both cases, both cubes get the same material name (either Test1 or Test2), though I can change one in MAX and only one cube will change.

**Comment by bond1mjb** [comment]
Can't duplicate on my end.   Your FBX exports don't work, but the FBX I posted works as expected.   

I've attached my Blender test file, you can test it out for yourself, just export using the default FBX settings and the materials will import correctly named.    You can use this to compare to how you are setting up your materials and hopefully find the problem.

Here is some info on setting up multimaterials in Blender: https://docs.blender.org/manual/en/latest/render/materials/assignment.html#multiple-materials

[multimat-blender.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11334394/multimat-blender.zip)

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb Thanks for trying to help. I do appreciate it. Yours do work when imported into MAX, both the FBX you'd posted above and the Blender file (once exported from Blender as FBX). Thanks for providing those.

And, yes, I know how to set up multiple materials. ;) What's there in the docs you linked to is pretty standard stuff. The issue I am running into is that this has all worked for me previously with other models, some with many models and materials (such as a test with a full room (walls, floor, windows, doors) with no issues. So, I'm not sure what I've done wrong here, especially since it's clear, in Blender, that both cubes have different materials. I provided them for TGC to look at and see what could be causing the issue.

**Comment by bond1mjb** [comment]
@MonkeyFrogStudio  If you're interested....I imported your FBX file into 3ds Max, and the material names showed up correctly.  I then exported it from 3ds Max to FBX, and the materials also showed up correctly in GGMAX.

Kinda sounds like this is a Blender export issue.  Since your model works fine when exported from 3ds max.    Still doesn't explain why my Blender file works and your doesn't though....

 
![3dsmax](https://user-images.githubusercontent.com/87768878/234633751-090a20c5-bcbc-474f-8bf2-c57535bac4bc.jpg)

![3dsmaxexport](https://user-images.githubusercontent.com/87768878/234633765-961db805-548a-4e6d-a03a-6848c673e7dc.jpg)

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb Thanks for testing this. It may be a Blender issue or may be a "ME" issue (i.e. something strange I am doing). I will test further to see what may be happening. Thanks again.

**Comment by bond1mjb** [comment]
I'm using Blender 2.91, just too lazy to keep up with the latest version since 3ds max is still my daily driver.   I did a test export of my cubes from Blender 3.3 though and it still worked.

**Comment by MonkeyFrogStudio** [comment]
Thanks. I asked because I am now using Blender 3.5. So, wanted to see what differences we had between us.
