### ISSUE TITLE
GG Max - EXP  - BUG - Player able to IGNORE stamina and run constantly

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4548]
As the title says, I was just testing a level, and found that the player can run constantly even when Stamina runs out.

The STAMINA only seems to effect the player whilst they are moving forward using SHIFT and W keys
If the player starts to move by holding SHIFT + W, but then also HOLD  A or D, the character will move fast and ignore that STAMINA.

This definitely needs fixing else the player can just run around the map superspeed, catching up the enemy and killing easy.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed for next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC Thank you for this fix, After testing the latest EXP build i can confirm this bug has been fixed.
I will now close this issue,
