### ISSUE TITLE
Directx-marcos.h Points to Directx9

### ISSUE THREAD

**Issue by DeVaughn97** [TheGameCreators/GameGuruRepo#4549]
Hi for Directx-marcos.h  I need this file to point to the directx9 headers and objects as opposed to Directx 11 any idea how I can do this?
This is the link to the Original file: https://github.com/TheGameCreators/GameGuruRepo/blob/master/GameGuru%20Core/Dark%20Basic%20Public%20Shared/Include/directx-macros.h

**Comment by AmenMoses** [comment]
Why?

If you need DX9 version (Classic only) go select it in Steam.
