### ISSUE TITLE
SAVE GAME / LOAD GAME new images cannot be set to the back

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4554]
As soon as i add an image to the SAVE GAME / LOAD GAME screen on storyboard, The slots mess up.
Look at how slot 1 is now missing, and the bottom 2 slots are slot 8

This bug is also causing MAX to shut down sometimes when adjusting these screens.

![Untitled](https://user-images.githubusercontent.com/66874403/234616983-79d6a889-d80e-4e87-a060-d0ccc162f089.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 This was fixed in a recent EXP build, and if the screen is now corrupt in your project, there is a new Restore Screen to correct any issues with bad elements in the screen.

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just tested this adding an image to the SAVE GAME screen on a NEW project screen.
After adding the IMAGE then setting it to go to the BACK of the Screen, All the SAVE GAME options were still behind the image, even though i tried Setting each SAVE GAME button to be Front of screen.

This clearly needs more work and fixing before you can change the SAVE / LOAD game screens.
This is not fixed currently. Sorry

**Comment by Tum1370** [comment]
@LeeBamberTGC Here is a Screenshot of the NEW PROJECT SAVE screen, where i tried adding the image to the screen. I then try and SET the image to the BACK, so the buttons would show up on top of the IMAGE that i have set at BACK.  

![Untitled](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/fb794779-f2dd-4ac7-9fe8-acfda0495334)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can now use SEND TO BACK AND FRONT even with stock screen widget elements for full draw order control:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/619b595d-3c5c-4e9f-ad9e-40caa33a32af)
