### ISSUE TITLE
GG Max - EXP - BUG - Add NEW Screen - Goto HUD Screen Numbers wrong

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4555]
As you can see from the screenshots.
After i created my new HUD SCREENS, the Numbers are HUD 6, HUD 9 and HUD 10.

HUD 6 is the old original from when i used ADD RPG SCREENS.

Then i added my own screens, creating HUD 9 and HUD 10.
Which i then changed and created my own Inventory and Map screens.

I then deleted all the HUD screens am not using, Just leaving the ORIGINAL CHEST HUD SCREEN, as i have not created my own screen for Chest yet.

**But look at what options are available in the NEW SCREEN options for using a button to go to a HUD SCREEN.
Here the HUD SCREEN numbers are 2,3 and 4.
Not the 6,9 and 10 that i have.**

![1](https://user-images.githubusercontent.com/66874403/234619921-8754c27f-4472-4dce-aa5d-3ba8b9e1eb47.png)

![2](https://user-images.githubusercontent.com/66874403/234619990-808e4bd8-83ea-4786-ba94-d4472438604a.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Lots of Storyboard screen fixes since April. Can you use the latest EXP build with a fresh project and see if you can reproduce these issues. The old method of corrupting screens should not be possible now, and the Restore Screen should help too.

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok thanks i will give it a try on a new project, But how do we change the screen that Max uses for VR Screen ? It is set at screen 9, and was hardcoded to 9 ?

**Comment by Tum1370** [comment]
@LeeBamberTGC I just tried adding a NEW HUD screen, and when adding a button, it still only has the options for 2,3 and 4 when selecting an ACTION for the button.
No way to go to HUD screens that are not HUD 2, HUD 3, or HUD 4

**Comment by LeeBamberTGC** [comment]
@Tum1370 Now added HUD screen choices 5 to 32 for more flexibility in the next EXP build. Will look to add more actions here down the road when we have a more robust logic system we can apply to screens (similar to behaviors but for screens).

The RESTORE SCREEN is only available on the stock auto-generated screens, it will not restore custom screens (as it will not know what to restore).  If you are looking for more a backup to custom screens, best to make regular backups of your project folder manually until we can add an automated backup system for projects (would be part of the new project system I feel).
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c5b54535-4a4e-4d95-8230-dbd6b110bdfc)

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok thanks Lee, Will test the latest EXP build after i see it update next.
