### ISSUE TITLE
GG MAX - V1 build - VR not saving standalone

### ISSUE THREAD

**Issue by LightofAlfheim** [TheGameCreators/GameGuruRepo#4558]
Hello, I have been trying to test out the vr mode with my game but i get this error when i save with vr mode enabled. Ive tried verifying files on steam with no luck
![image](https://user-images.githubusercontent.com/32985460/234723238-ce253609-a916-4685-91c2-1465eb962bcc.png)

**Comment by davetgc** [comment]
Hi, what VR device are you using?

**Comment by GavinIssooocoool** [comment]
I use a quest 2 with air link, but not on my own PC. Would i have to install MAX on the other PC and build it from there?

**Comment by davetgc** [comment]
I've passed this to the Dev team for further comment. If you can get it working on your other PC, please let us know as it will help to track down the issue.

**Comment by synchromesh62** [comment]
> I use a quest 2 with air link, but not on my own PC. Would i have to install MAX on the other PC and build it from there?

I use Quest 2 and Airlink without any probs
When you say not on your own PC does this other PC meet the minimum specs ?

**Comment by LightofAlfheim** [comment]
> > I use a quest 2 with air link, but not on my own PC. Would i have to install MAX on the other PC and build it from there?
> 
> I use Quest 2 and Airlink without any probs When you say not on your own PC does this other PC meet the minimum specs ?

Yes, I have been able to run the RPG template on the other PC, but I havent been able to run it standalone.

**Comment by LeeBamberTGC** [comment]
@LightofAlfheim Separating out VR for a second, are you reporting that when you save the RPG Template demo as a standalone and run it on the PC it does not work? If so, can you send me a short video showing the exported demo being run from the EXE, thanks!

**Comment by LeeBamberTGC** [comment]
@LightofAlfheim Not seeing any other reports from anyone on this. I will close this for now, but if you find time to make a video and it happens on the next public build, feel free to comment here.
