### ISSUE TITLE
Texture artifacts on my standalone tests 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4559]
As the title states strange texture artifacts appearing on my standalone tests.
Hard to see in some of my levels but its standalone only
Test game from the editor is fine.
Easy to see on plain ceilings 

UPDATE ..After a lot of trial and error it would appear disabling the shadows on the lights gets rid of them
some direction to investigate perhaps ?

![AT1](https://user-images.githubusercontent.com/35708217/234727531-9ddcae7c-098d-4124-9af0-9b4073a6fef3.png)

**Comment by MonkeyFrogStudio** [comment]
Just on a whim - are these ceiling pieces perfectly aligned? Not only vertically, but also horizontally? I had an issue some time back where imported pieces were sometimes off by just a fraction and wouldn't perfectly connect, even with snapping. It was very slight ... and I've not seen the issue in some time, so I assumed it was fixed. But if you move your camera in really closely, are the pieces are perfectly aligned? If they're not, this may be why you're getting shadows there.

Here's the old issue I'd reported:

https://github.com/TheGameCreators/GameGuruRepo/issues/4076

Anyway, just spitballing here. ;)

**Comment by synchromesh62** [comment]
> Just on a whim - are these ceiling pieces perfectly aligned? Not only vertically, but also horizontally? I had an issue some time back where imported pieces were sometimes off by just a fraction and wouldn't perfectly connect, even with snapping. It was very slight ... and I've not seen the issue in some time, so I assumed it was fixed. But if you move your camera in really closely, are the pieces are perfectly aligned? If they're not, this may be why you're getting shadows there.
> 
> Here's the old issue I'd reported:
> 
> #4076
> 
> Anyway, just spitballing here. ;)

Ye it only started just the other day, Before then i never had an issue .. 
At first i thought it may be a rogue normal corrupting the models but it seems to be on all standalones for me but just harder to spot on non plain surfaces.  Like i said if i untick the **Cast shadows** on the lights they vanish completely 

![AT2](https://user-images.githubusercontent.com/35708217/234836138-35a73a9e-e1f3-48d4-8e15-934eb02bfe2d.png)

**Comment by synchromesh62** [comment]
I have found the squares move with the lights .. Almost like a ghost artifact of the probe outline when lee initially combined it to the light assets a week or so ago ?

**Comment by MonkeyFrogStudio** [comment]
Are you using a probe? And, if so, is it at least as large as your room?

**Comment by synchromesh62** [comment]
Update !!
This only happens on my old maps and the issue is not there on any new ones.
Could be i just have to scrap all my old work and start fresh.
