### ISSUE TITLE
In VR, can not pick things up using trigger, open doors using trigger

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4565]
After a lot of testing, and looking at WHY the VR SCREEN worked on the RPG TEMPLATE level, but not on mine, And then looking through  the script, I found that the VR SCREEN is HARD CODED to HUD SCREEN 9.

This makes things difficult, and needs an option to SET the VR SCREEN to any HUD SCREEN we want it to be.

When DEVS add many more HUD SCREENS, or DELETE HUD SCREENS, the numbers will all get messed up.
Another Part of this bug is the bug i have posted here https://github.com/TheGameCreators/GameGuruRepo/issues/4555 Which also causes problems with HUD BUTTONS going to other HUD screens.
You have it only setup to go to HUD SCREENS 2,3 or 4  ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 Added ability to RESET a previously selected key shortcut for HUD Screens (SPACEBAR as this is used for jump for the moment and have a key remap feature request filed to improve on this solution longer term).  With this was able to fix the issue with "`" key bringing up the store HUD (screen 5),   This then allows the VR HUD Screen shortcut of "`" to work properly:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2f92b592-e4fa-4b3e-bcbf-fc79a85ce035)
I also ensured that when Add RPG Screens is selected on a custom project, the VR HUD Screen is included so no need to manually create it, much easier to modify it:
Then added a new LUA command called "ScreenToggleByKey" and updated the HUD0.lua script to use this instead, thus you can now create any HUD screen in the storyboard and assign its key toggle as "`" and this is the screen that will pop up when the B button is pressed on the VR controller. Phew.  Will be in the next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC  Am not sure whether this  is the bug that made the trigger not work in VR or the other bug that i have also posted in.
But since these latest fixes, in VR, i can not pick things up using trigger, open doors using trigger. 
Also i have noticed that when i press the "B" button on the right controller, it opens up the SHOP.
This is whether am near the shop or not, It just opens up the shop screen anywhere.

This bug is certainly not fixed.
