### ISSUE TITLE
GG Max - build from source issue

### ISSUE THREAD

**Issue by cybernescence** [TheGameCreators/GameGuruRepo#4566]
Hi all - congratulations on V1 release :)

I just checked the latest source to see if it would build and hit an issue in master.cpp: 
"masterrenderer.ComposeSimple2D(cmd); //only 2D"

This doesn't appear to exist, I got around it by just calling 
"masterrenderer.Compose(cmd); //Also do 2d compose" 
instead and seems to work OK. 

So probably a minor issue affecting very few, just thought I'd let you know. 
Maybe the public source not the same as live build? If so sorry, no worries.

Cheers.

**Comment by plemsoft** [comment]
@cybernescence Its inside "https://github.com/TheGameCreators/WickedRepo" you just compile that first :)

**Comment by cybernescence** [comment]
Thanks Preben
