### ISSUE TITLE
GG Max - EXP (Version 1) - BUG - Storyboard - Adding NEW LOADING SCREEN creates a BUG with HUD SCREENS

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4567]
As the title says, This was working fine, until i added a NEW LOADING SCREEN.

But after adding the NEW LOADING SCREEN, Now when i test my level, I PRESS "I" for inventory, but instead of the game now bringing up the HUD SCREEN 10  (See screenshot) It brings up the LOADING SCREEN 2.

Sometimes this is on the M key as well and brings up loading screen instead of my MAP SCREEN.

Very BUGGY.

EDIT: I just added a new CUSTOM SCREEN 1, and used it as a Game Over screen for a different level, But this also appears as the MAP screen now when i press my M key.

![Untitled](https://user-images.githubusercontent.com/66874403/234832816-86375967-0bb2-436f-a48d-599f38ea7a8f.png)

**Comment by LeeBamberTGC** [comment]
@Tum1370 yes the toggle key was a little too liberal here, fixed for the next EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC Thanks for the fix of this bug, After testing i can confirm its fixed. I will now close this issue.
