### ISSUE TITLE
 No cursor on the standalone start screen

### ISSUE THREAD

**Issue by Zeus2015** [TheGameCreators/GameGuruRepo#4568]
Hi, 
 no cursor on the standalone start screen,
 no particle editor effect after launching game editor and in standalone.

Windows 11, I7 6700K, RTX 3060 Ti.

**Comment by casigus** [comment]
go to the max folder, find the titlebank folder, copy it into your exported game, BAM it will fix it. 
![image](https://user-images.githubusercontent.com/68471279/235006282-ce41f3d0-f628-443d-b7a7-0ee96c26fec3.png)

**Comment by Zeus2015** [comment]
Thanks, fixed!
Manually move titlesbank folder and move particlesbank folder to
C:\Users\...\Documents\GameGuruApps\GameGuruMax\My Games.
