### ISSUE TITLE
Multiplayer and Unsaved Maps Issue

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#457]
If you accidentally click the multiplayer button, when you exit, you will find all your unsaved work completely removed off the map.

I should note that I don't actually use the multiplayer option. Only time i press the button is most often by accident, when attempting to hit the test level launch for single player.

**Comment by synchromesh62** [comment]
Yes this happens also when exiting MP ( if you load your MP map up for editing first )
It wasn't really a problem for that but yes I can see how it could mess your map up that way

**Comment by korodai** [comment]
Oddly enough I just did this and lost my work, until I clicked the rocket ship and it all returned.

**Comment by Teabone3** [comment]
This issue is still present in the 2019 updates of Game Guru.

**Comment by plemsoft** [comment]
Restoring of old map, after multiplayer will be addressed in this issue:
https://github.com/TheGameCreators/GameGuruRepo/issues/513

**Comment by honkeyboy** [comment]
thanks m8 :)
