### ISSUE TITLE
GameGuru Max - AMD Radeon RX 6600 XT - Black Screen and Crashes

### ISSUE THREAD

**Issue by AndrewvanDijk** [TheGameCreators/GameGuruRepo#4570]
After latest update as of 27 April 14h00 - Small update for AMD black screen
Issue still persists.
I see the other fix that copies the gxdi.dll files has been added to the installation.
Game starts, shows this image 
![image](https://user-images.githubusercontent.com/3898059/234887182-259ef22a-9364-41dd-ac7e-606d24d51c8a.png)

My setup
![image](https://user-images.githubusercontent.com/3898059/234887798-39631712-5f90-4258-9ccb-3b6ab341fb52.png)

![image](https://user-images.githubusercontent.com/3898059/234887896-94810ccb-8f87-4ec3-8500-593f822a6e4e.png)

Side note, all other games including GameGuru Classic work without any problems.

After a couple of seconds the game crashes
Errors in dxgi log
info:  Game: GameGuruMAX.exe
info:  DXVK: v2.0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon RX 6600 XT:
info:    Driver: 2.0.262
info:    Vulkan: 1.3.246
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:      Memory Type[8]: Property Flags = 0x1
info:      Memory Type[12]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 16024 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[11]: Property Flags = 0xe
info:      Memory Type[13]: Property Flags = 0xc6
info:      Memory Type[15]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7
info:      Memory Type[10]: Property Flags = 0x7
info:      Memory Type[14]: Property Flags = 0xc7

dxd11 log
info:  D3D11CoreCreateDevice: Maximum supported feature level: D3D_FEATURE_LEVEL_12_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
info:  Device properties:
info:    Device name:     : AMD Radeon RX 6600 XT
info:    Driver version   : 2.0.262
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_attachment_feedback_loop_layout
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state3
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_memory_priority
info:    VK_EXT_non_seamless_cube_map
info:    VK_EXT_robustness2
info:    VK_EXT_shader_module_identifier
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_external_memory_win32
info:    VK_KHR_external_semaphore_win32
info:    VK_KHR_pipeline_library
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 1
info:    shaderInt64                            : 1
info:    variableMultisampleRate                : 1
info:    shaderResourceResidency                : 1
info:    shaderResourceMinLod                   : 1
info:    sparseBinding                          : 1
info:    sparseResidencyBuffer                  : 1
info:    sparseResidencyImage2D                 : 1
info:    sparseResidencyImage3D                 : 1
info:    sparseResidency2Samples                : 0
info:    sparseResidency4Samples                : 0
info:    sparseResidency8Samples                : 0
info:    sparseResidency16Samples               : 0
info:    sparseResidencyAliased                 : 1
info:  Vulkan 1.1
info:    shaderDrawParameters                   : 1
info:  Vulkan 1.2
info:    samplerMirrorClampToEdge               : 1
info:    drawIndirectCount                      : 1
info:    samplerFilterMinmax                    : 1
info:    hostQueryReset                         : 1
info:    timelineSemaphore                      : 1
info:    bufferDeviceAddress                    : 0
info:    shaderOutputViewportIndex              : 1
info:    shaderOutputLayer                      : 1
info:    vulkanMemoryModel                      : 1
info:  Vulkan 1.3
info:    robustImageAccess                      : 0
info:    pipelineCreationCacheControl           : 1
info:    shaderDemoteToHelperInvocation         : 1
info:    shaderZeroInitializeWorkgroupMemory    : 0
info:    synchronization2                       : 1
info:    dynamicRendering                       : 1
info:  VK_AMD_shader_fragment_mask
info:    extension supported                    : 1
info:  VK_EXT_attachment_feedback_loop_layout
info:    attachmentFeedbackLoopLayout           : 0
info:  VK_EXT_conservative_rasterization
info:    extension supported                    : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state3
info:    extendedDynamicState3DepthClipEnable   : 1
info:  VK_EXT_fragment_shader_interlock
info:    fragmentShaderSampleInterlock          : 0
info:    fragmentShaderPixelInterlock           : 0
info:  VK_EXT_full_screen_exclusive
info:    extension supported                    : 1
info:  VK_EXT_graphics_pipeline_library
info:    graphicsPipelineLibrary                : 0
info:  VK_EXT_memory_budget
info:    extension supported                    : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_module_identifier
info:    shaderModuleIdentifier                 : 1
info:  VK_EXT_shader_stencil_export
info:    extension supported                    : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_external_memory_win32
info:    extension supported                    : 1
info:  VK_KHR_external_semaphore_win32
info:    extension supported                    : 1
info:  VK_NVX_binary_import
info:    extension supported                    : 0
info:  VK_NVX_image_view_handle
info:    extension supported                    : 0
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 2
info:    Sparse   : 0
info:  Memory type mask for sparse resources: 0xf
info:  DXVK: Read 60 valid state cache entries
info:  DXVK: Graphics pipeline libraries not supported
info:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_A2B10G10R10_UNORM_PACK32
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1904x1161
info:    Image count:  4
info:    Exclusive FS: 2
info:  DXVK: Using 12 + 0 compiler threads
err:   D3D11RasterizerState: Antialiased lines not supported
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_A2B10G10R10_UNORM_PACK32
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1920x1177
info:    Image count:  4
info:    Exclusive FS: 2

**Comment by LeeBamberTGC** [comment]
@AndrewvanDijk After you see the splash screen, when do you see next, thanks!

**Comment by AndrewvanDijk** [comment]
Straight after the splash screen, the application goes out.

**Comment by AndrewvanDijk** [comment]
There were old files from 2021 in that folder, I deleted them, and
restarted nedrive.
It is working now,./
Thanks guys

**Comment by AndrewvanDijk** [comment]
Is there a way to setup where the files live, onedrive is slowing the game
down.

**Comment by AndrewvanDijk** [comment]
Testing Foggy Forest, when the zombies run, their animation restarts over
and over, they run in the same area, don't chase after the player.

**Comment by plemsoft** [comment]
@AndrewvanDijk Yes you can set it here:

![settings-save](https://user-images.githubusercontent.com/18662417/235090245-3c06b914-c4ec-47de-aa2f-a1e88f8e06c0.jpg)

Also having onedrive synch all the changes from this location would slow things down and could lead to many other problem, so it would be a good idea to move your game save folder or exclude your current folder from onedrive sync.

If you have another problem after you disable onedrive from your game save folder (Foggy Forest) , you should create a new issue, or it will just get lost, one problem per issue, Thanks for your help :)

**Comment by AndrewvanDijk** [comment]
Great thanks

**Comment by LeeBamberTGC** [comment]
@AndrewvanDijk Thanks for letting us know :)
