### ISSUE TITLE
New Project System to maintain tight control of ALL CUSTOM MEDIA

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4572]
Just tried a standalone build with new V1 - here be the results
When building standalone:
- for the first 2:23 minutes the bar sits a 1% while TM reports GGm is not responding
- then it finished the build with a total time of 3:38 minutes 
Playing the game:
- none of my custom images get copied over, just have black boxes on screen - fortunately I can hide the hud in-game 🙂
- some models are not copied over
- some scripts are not copied over
- some audio not copied over
- some emissives not working - probably did not copy emissive maps over
- seems smooth enough - but was unable to get past the second level (door script missing) so could not get to the next level marker to play more complex levels
- I could copy the media over but that defeats the purpose of Create Standalone and of course leaves media unencrypted 
So if anyone decides to release a game with GGm now be sure you have a way to encrypt any custom media for third parties or it could be shaky ground on the copywrite front

**Comment by LeeBamberTGC** [comment]
@davetgc Email me your project and any custom media, and I will attempt to reproduce your results.

**Comment by davetgc** [comment]
Hi Lee,

It's not my bug, it's from Discord, I'll see what I can do.

**Comment by kadinshino** [comment]
I want to add, I was experiencing the audio export issue on stand-alone builds. It was most noticeable with audio attached to level ambient music. For some reason, those tracks would not get copied over after building a project.

The weird workaround I found for importing any audio was by creating an empty room, Inside this room, I attach the sounds to trigger objects if that sound does not seem to load. After I do this, sounds seem to load after building.

So ambient sounds must not be getting flagged properly to copy over in the build files, and I often see music or ambient tracks missing from the final build unless I do the above "Fix"

**Comment by LeeBamberTGC** [comment]
The Central "New Project System Issue" now here: https://github.com/TheGameCreators/GameGuruRepo/issues/2301
