### ISSUE TITLE
GG Max - EXP (Version 1) - BUG - Ammo behaviour - Prompt Text does NOT show when set to AUTOMATIC pickup

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4573]
As the title says, It looks like when you have ammo set to AUTOMATIC on the PIckup style, The Prompt Text does not show on the screen.

After checking this on another map, I noticed that if you have the Pickup style to Manual, The Prompt Text shows, saying whatever you type in that section, "Press E to Pick Up Ammo"
But the Text After picking up the ammunition is ALWAYS the same, and not changeable.

Surely this Text needs to be set by the DEV, and NOT hard coded in to the system ?

**Comment by Necrym59** [comment]
Fixed
[ammo_v5.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11360314/ammo_v5.zip)

**Comment by Necrym59** [comment]
Fixed and sent in for Lees approval

**Comment by Tum1370** [comment]
@LeeBamberTGC @Necrym59 Thanks for the fixed guys, I will close this issue now.
