### ISSUE TITLE
GGM (V1) - BUG - You can't use the rubber band multi-selection tool in indoor areas because there's always something behind the cursor

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4574]
To activate the rubber band multi-select tool, it seems like you need to shift and left-click somewhere there is NOT an object.

The problem is, with indoor maps, there will ALWAYS be an object (a wall) behind the cursor. This means you can't click anywhere there isn't an object, which means you CAN'T use the rubber band selection tool (shift + left click + drag) in indoor areas. Bummer!

**Video:**

https://user-images.githubusercontent.com/103399301/234943762-5397e4c1-2e05-4d35-9dd2-f02b759323a3.mp4

**Comment by davetgc** [comment]
There is a setting that prevents an object being moved/selection if you're inside it, does that help?

**Comment by Kravenwolf** [comment]
If you mean clicking the lock icon to lock an object in place, no that still doesn't allow the rubber band tool to work if you start your shift + left-click on that asset. You can't use the rubber band tool if there is any object behind the cursor.

**Comment by Kravenwolf** [comment]
Not sure if would that would work because I'm not inside of an object, rather surrounded by dozens of single objects (modular walls, floors, etc.).  s

**Comment by LeeBamberTGC** [comment]
@Kravenwolf In the NEXT EXP build you can now start a rubber band even if you are hovering over and initially clicking an object, so as long as the SHIFT key has been depressed :)
