### ISSUE TITLE
amd black screen update causing crashes

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4577]
I think that updates broke something
the AMD one
since it was applied, ive had crash after crash after crash
that are exactly the same as the ones the testers where getting
my fans on the gpu have also been going nuts too
revving then stopping, revving then stopping.

the crashes I'm getting are exactly like the ones I'd send a test copy of the games to who had AMD gpus.

specs:

![image](https://user-images.githubusercontent.com/68471279/234993519-854f1e75-edae-4f87-ae35-ffa92e8eb55e.png)

video card specs:

![image](https://user-images.githubusercontent.com/68471279/234993615-74851475-c661-468c-9548-6b08372737be.png)

**Comment by kadinshino** [comment]
Also, have a massive GPU load, and on just the starting screen no levels are loaded. Nvidia 3080 TI

Only one crash today but not sure what the cause or if it was related.

![Massive GPU load](https://user-images.githubusercontent.com/71521025/234996596-7deb363a-ba02-4341-a0f6-3b3ef14b37df.png)

**Comment by plemsoft** [comment]
@casigus @kadinshino AMD fix is not active on NVIDIA cards, you can validate this. Is any of these files on your system ?
\SteamLibrary\steamapps\common\GameGuru MAX\d3d11.dll
\SteamLibrary\steamapps\common\GameGuru MAX\dxgi.dll

**Comment by kadinshino** [comment]
> 

![files](https://user-images.githubusercontent.com/71521025/235080542-7ac497fe-dfe8-4afa-91a3-0fd837dde46a.PNG)

I do not have d3d11.dll or dxgi.dll. Do I need to add those or do something to add them?

**Comment by plemsoft** [comment]
@kadinshino No you should not have them , they are only used for the AMD fix , This check was just to prove that your issue do not have anything to do with the AMD fix , Thanks for confirming this :)

**Comment by casigus** [comment]
How can you say it has nothing to do with the AMd fix it when it was this patch that has made max unusable for Nvidia gpus? I was sending test games out to users and the crashes they we're having are identical to the crashes we're now having. "Has nothing to do with the amd fix" and literally happened right after the titled AMD FIX was dropped on steam. That patch changed something making max completely unusable. My gpu should not be reving like this. Nothing has ever caused it to do this. I've played games on super high and it doesn't do this. It has everything to do with the AMD FIX. Worse of all. I can't revert to a previous update because max completely wipes the map of work. This is supposed to be version one and never known it to be so utterly broken.


On 28 April 2023, at 08:22, Preben Eriksen ***@***.***> wrote:


@kadinshino<https://github.com/kadinshino> No you should not have them , they are only used for the AMD fix , This check was just to prove that your issue do not have anything to do with the AMD fix , Thanks for confirming this :)

**Comment by plemsoft** [comment]
@casigus I do not know what your issue is , but could you also confirm this to rule it out. Thanks: https://github.com/TheGameCreators/GameGuruRepo/issues/4577#issuecomment-1527066924

**Comment by casigus** [comment]
Yeah I'll check when get to the pc!


On 28 April 2023, at 09:58, Preben Eriksen ***@***.***> wrote:


@casigus<https://github.com/casigus> I do not know what your issue is , but could you also confirm this to rule it out. Thanks: #4577 (comment)<https://github.com/TheGameCreators/GameGuruRepo/issues/4577#issuecomment-1527066924>

**Comment by casigus** [comment]
Geniune concern for hardware here too. Never known my gpu to act up this way before!


On 28 April 2023, at 09:58, Preben Eriksen ***@***.***> wrote:


@casigus<https://github.com/casigus> I do not know what your issue is , but could you also confirm this to rule it out. Thanks: #4577 (comment)<https://github.com/TheGameCreators/GameGuruRepo/issues/4577#issuecomment-1527066924>

**Comment by casigus** [comment]
my issue is that the amd crash update has completely broke game guru for me....... why I opened this report....

![image](https://user-images.githubusercontent.com/68471279/235152695-0eb422f3-5d51-488a-b633-71306bfd9d59.png)

**Comment by casigus** [comment]
ive narrowed it down to one of the ingame models I imported worked before that last update but now crashes the engine post that update. deleted the model and its working again.....

even the gpu sounds better today.

Ill keep monitoring it.
