### ISSUE TITLE
Uncomment #define LAPTOP in settings.fx creates runtime error

### ISSUE THREAD

**Issue by HierToo** [TheGameCreators/GameGuruRepo#458]
If you uncomment #define LAPTOP in the settings.fx and recompile the shaders with forceloadtestgameshaders=1 in the setup.ini, you get an runtime error and GG restarts again and again.

**Comment by plemsoft** [comment]
@HierToo Thanks for reporting this,

The LAPTOP and other settings is now fixed, ready from the next update :)
