### ISSUE TITLE
Gameguru Max Crashing on test game

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#4583]
https://drive.google.com/file/d/1RLBy4dEpr1pPpR_Yp5D36Gq0AUqzZM_p/view?usp=share_link

**Comment by davetgc** [comment]
Can you please post your system specs.

**Comment by CharleneMaure** [comment]
![image](https://user-images.githubusercontent.com/107326667/235172558-5dfd2f2c-d93a-4e39-8e3d-5805ef3340aa.png)

![image](https://user-images.githubusercontent.com/107326667/235172750-862ea8a0-c7cf-4805-9eff-89c29ddac6c7.png)

**Comment by CharleneMaure** [comment]
do you want me to send some project files

**Comment by davetgc** [comment]
If you can, that would be a great help. You can attach them here, or email them to Lee@thegamecreators.com, referencing this issue.

**Comment by CharleneMaure** [comment]
what project file do i need thanks

**Comment by CharleneMaure** [comment]
https://drive.google.com/file/d/1aUrBBvCMNix6qCMLyeczlql4wdFtAQYj/view?usp=share_link

this just the FPM file tell me if you need anything else

**Comment by davetgc** [comment]
There should also be a file in Projects, the name will depend on what you've called it.

**Comment by CharleneMaure** [comment]
Let file

**Comment by casigus** [comment]
i can also confirm test level crashes max. started after the AMD fix.

**Comment by sirlion87** [comment]
Test level still crashing on standalone maps, as soon as the level is saved and even during editing sometimes.

**Comment by CharleneMaure** [comment]
My level Crashed again all the works useless now

**Comment by CharleneMaure** [comment]
Yeah i import models all the time, i have to be careful with groups because when imported a smart object the crash became apprent on all of my new levels not only the level but the backups wouldn't work on test game, incredibly Stressful sorry you have to hear this, Sorry

**Comment by casigus** [comment]
thats when i noticed the error kicked off with newly imported models AFTER the AMD update. yeah its very stressing I here you! im getting to a point am going to just give up with the software. im getitng so many realllllllllly annoying issues that just make it impossible to actually create anything meaningfull!

max should have stayed in early access. the level of bugs are not ok. 

take some time away from it, i know I am! hope you get a fix soon.
