### ISSUE TITLE
Hologram and Prompt Text Bug.

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4584]
Potential bug when using holograms and other items that use the lower field prompt text.

When you switch a hologram on, it will default to "Displaying Hologram." No matter how far you are from the object or at least within a 1000sqft room, you will get this message while the hologram is on. 

If you have multiple holograms in a room, The prompt text will switch to whatever the last hologram switched on was.

If you clear the field of any text so nothing appears, nothing will show up, or anything that would show up in the lower prompt field will not show up, including prompts from other objects.

An example of an issue is if you are using switches, notifications, or anything else that uses that lower prompt field, it gets overwritten by the hologram behavior.

For example, if you use objective-based switches on a level with holograms, the switch progress will get overwritten by the hologram prompt text.

I think an easy way to resolve this would be to give holograms a range-based Promt text. But this could still have potential issues when having holograms close to other objects that use that prompt field. 

Update: It appears to happen with objects that share the behavior using prompt fields, and triggering at the same time also results in similar behaviors. So there might need to be some sort of prompt stacking feature that can scroll through the prompt fields somehow. 

Maybe a simple fix, for now, is adding a checkbox to exclude objects from using promftfields so we can reduce spam from different behaviors such as Hideshow, "What was that," Holograms, and anything that uses that field pretty much. and this would also fix the holograms behavior of globally overwriting all prompt text.

**Comment by Necrym59** [comment]
[hologram_v5..zip](https://github.com/TheGameCreators/GameGuruRepo/files/11368032/hologram_v5.zip)
Fixed and sent in for update inclusion

**Comment by LeeBamberTGC** [comment]
@kadinshino Will be fixed in NEXT EXP build.
