### ISSUE TITLE
AMD Black Screen on Building Editor

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#4585]
Hello all,

Thank you for your efforts to correct this problem with AMD cards.

I use :
- Windows 11 Pro 64 bit, with 64 gigs of RAM.
- AMD Radeon RX 6950 XT graphics card (16 gigs of RAM)

Here is a screenshot of GG Max after loading a map (work fine).
But the Building Editor is not working (black screen).
![BE](https://user-images.githubusercontent.com/96718175/235287488-2ef210c8-9261-42de-9bde-247c5c2dec70.png)

Thanks you.

**Comment by Frantic-bookworm** [comment]
![20230427_181954 2961](https://user-images.githubusercontent.com/107033025/235316530-02853778-2722-4ed1-b425-b0c8d605c8e9.jpg)
![20230427_181937 2960](https://user-images.githubusercontent.com/107033025/235316597-e0b3251c-2929-428b-b48e-f4dc1ce10a62.jpg)
![image](https://user-images.githubusercontent.com/107033025/235316686-55fbc152-ac6f-441c-86bf-bbbfe9a25a7c.png)
still cannot access editor , play demo games , or load any of my levels the UI is fine access everything just can not see it ...black screen

**Comment by Frantic-bookworm** [comment]
update on above message, ive tried running on a 32 inch wide screen samsung monitor and a 55 inch lg hdr 4k tv and still same issue

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Just a little bit of additional info i have been able to dig up.
Apparently for the AMD Radeon RX 6500 XT... Max will work perfectly apparently using the older 22.5.1 driver
Any driver above this will give the black screen issue.
The current driver is 23.4.3 so its quite an old one.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Extended AMD fix to cover the Building Editor in latest public build :)

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Let me know if you still have issues and I will reopen this :)
