### ISSUE TITLE
GGM (V1) - EXP Build - Text in Textinzone dissapears after 1 second

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#4586]
https://www.youtube.com/watch?v=V8HPoK90BNw

**Comment by OldFlak** [comment]
Yes would perhaps be handy to have the same features as the imageinzone
![image](https://user-images.githubusercontent.com/12246318/235334220-1b234187-3820-4c6a-a175-4857151f69a2.png)

**Comment by Necrym59** [comment]
Text in zone is displayed while in the zone, it works perfectly here, In your video you have another text field sitting on top of the prompt display perhaps try removing it first.
The image behavior has different needs, No need for fullscreen option or click to exit and duration has no meaning as the text is only on within the zone thats what its designed for.

**Comment by Necrym59** [comment]
[textinzone_v3.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11360980/textinzone_v3.zip)
TextInZone behavior updated to v3
- Fixed the the destroy zone option so it has a delay for as long as the text message.
- added extra option for SpawnAtStart for the zone.
