### ISSUE TITLE
GG Max - EXP - BUG ?? - Entitybank Showcase folder keeps downloading, even though not showing up in Max

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4587]
I just deleted the folder in Max's main entitybank called Showcase.
Then after verifying files again, Max then redownloaded this folder ?

This is just duplicates of entities isnt it ?
Why does Max keep re downloading it ?

**Comment by synchromesh62** [comment]
> I just deleted the folder in Max's main entitybank called Showcase. Then after verifying files again, Max then redownloaded this folder ?
> 
> This is just duplicates of entities isnt it ? Why does Max keep re downloading it ?

Because its part of the core ?
If you verify then steam checks the files that our missing or corrupt and replaces them.
That's the whole point of verifying the installation.

**Comment by Tum1370** [comment]
I thought that Lee removed Showcase due it is just copying entities that we already have ?

**Comment by synchromesh62** [comment]
Perhaps he intended to but just checked and i have it after a fresh install yesterday.
Maybe he just hasn't got round to it yet ?

**Comment by Tum1370** [comment]
Ye it was Necrym who mentioned it earlier, I guess Lee removed it from the editor, but forgot to remove it from the download.
It contains a Rabbit with a wrong script in there as well.
