### ISSUE TITLE
GGMAX Bug (EXP V1) - "Graphics Settings" are not working properly

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#4589]
Graphics settings in the standalone are not working properly. Here is the video showing the issues: https://youtu.be/Iv-zk3gknEE
As you can see from the video there are 2 issues:
1) Between "Medium" and "High" there is no difference, so the high settings don't work.
2) The FOV bar doesn't work.

**Comment by SampeyFS** [comment]
Good Games Download :D

**Comment by LukeTheLukeLTL** [comment]
> Good Games Download :D

@SampeyFS I didn't understand if you want to download my video game, but in any case here is the link ;D https://www.indiedb.com/games/lukes-impossible-mission-demo

**Comment by SampeyFS** [comment]
yes thanks great friend yes I also put the games here

**Comment by LeeBamberTGC** [comment]
@LukeTheLukeLTL Is the FOV slider bug still happening?  The MEDIUM and HIGH will probably not LOOK that different in some scenes as it scales back-end things like shadow resolution and light quantities.  Down the road we will probably replace this with the traditional break-down of effect sliders so you know what each preset is doing.
