### ISSUE TITLE
Script encryption issue

### ISSUE THREAD

**Issue by honkeyboy** [TheGameCreators/GameGuruRepo#459]
Hi guys, 
Found:
All encrypted scripts contain user data e.g 
:\Users\Name\Documents\Game Guru Files\My Games\Asgood2\Files\scriptbank\ai_chatanim.lua

Dvader confirmed this for me and testing one of his projects I found the same for his scripts this is the same for all encrypted scripts. If you need an example script let me know and i'll post one.

Can anyone else test and confirm for me

Thanks

**Comment by AmenMoses** [comment]
Confirmed and a bit weird, not sure why the full path and filename of the source script should be included multiple times in the destination file, must be a Lua thing.  Possibly somewhere there is a Lua debug setting that's causing it, I'll have a dig around and see what I can find.

**Comment by honkeyboy** [comment]
Also noticed that the user folder itself had been copied into some entity folders, don't know if this is related

**Comment by AmenMoses** [comment]
One thing I've been meaning to investigate and haven't got around to yet is how easy it would be to redirect the standalone creation to another path rather than the user documents folder.

**Comment by Teabone3** [comment]
That would be fantastic if we can figure that out @AmenMoses

**Comment by honkeyboy** [comment]
Agreed its a bit unnerving having my user folder plastered all over the standalone ;) although it maybe not a big security issue. It is an issue none the less

**Comment by honkeyboy** [comment]
Its also copying the x86 folders in some cases although I will stress its only the folders and not the contents. still as you say m8 it is uncool and a little unnerving having your computer name splattered all over every script, in fact I have copied the originals over and then it works fine without the user names, but these are free or my own scripts which I don't mind people abusing, I had to manuall go into some entity folders and delete out the offending ones, its a bit weird as some do have it and some don't even my own models, it does however seem to be the most recent ones do and the older ones don't ? weird

**Comment by LeeBamberTGC** [comment]
In the next version, you can select the location of the save standalone so you can hide the User path you are using for your PC. Closing this issue unless there is further concern over the LUA encryption.
