### ISSUE TITLE
Standalone  Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4590]
![image](https://user-images.githubusercontent.com/108415264/235311087-adf51e32-4c2f-4e76-94b7-d9423e694f8f.png)

Standalone does not extract the map photo when you extract the game

**Comment by MonkeyFrogStudio** [comment]
@SampeyFS You should do a search first to see if the bug you're reporting has already been reported. It doesn't help to report bugs that are already reported. This bug had already been reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/4490

**Comment by SampeyFS** [comment]
Sorry
