### ISSUE TITLE
Game Guru Scripting for level transport between levels 

### ISSUE THREAD

**Issue by Guruone2023** [TheGameCreators/GameGuruRepo#4592]
The scripts inside GURUMAX aren't working - which means that transport between levels isn't working so how can you go from one level to another in testing this is in release V1

**Comment by Guruone2023** [comment]
Several of the V1 transport and even the WIN scripts don't appear to be working as was advertised - having spend hours actually weeks producing a game for this the product aways seems to come across as rushed and unfinished in some way which isn't great - think that the developers need to seriously start looking at quality or QA process - working in IT Senior level software myself I think this isn't very professional - not when people are paying for it. Each script needs to be tested.

**Comment by synchromesh62** [comment]
> Several of the V1 transport and even the WIN scripts don't appear to be working as was advertised - having spend hours actually weeks producing a game for this the product aways seems to come across as rushed and unfinished in some way which isn't great - think that the developers need to seriously start looking at quality or QA process - working in IT Senior level software myself I think this isn't very professional - not when people are paying for it. Each script needs to be tested.

I tested a few of these the other day and they seemed to work fine. The user in question was setting them up incorrectly.
Can you give me the names of the broken ones not working for you so i can test and confirm they are not working .

**Comment by Guruone2023** [comment]
![image](https://user-images.githubusercontent.com/132165973/235324421-6393eec4-94fd-40d4-98bc-3586f382a8d7.png)
![image](https://user-images.githubusercontent.com/132165973/235324449-ee04eda0-42a8-41d4-bae9-5b5e58d8ec4f.png)
The two scripts are the move player upon entry to the next level ie: tunnel not using storyboard logic and the other is endgame that should simply goto the next level - TELEPORT AND WINGAME

**Comment by Guruone2023** [comment]
Sorry to have been harsh but am like many trying to push the abilities of the GGM in regard to level design and looks - which obviously is frustrating when things don't work as they should - anyway am sure it isn't a serious issue.

**Comment by Guruone2023** [comment]
![image](https://user-images.githubusercontent.com/132165973/235324764-9da67893-059a-40b4-a60b-dfc4dea84105.png)
as you can see it shows the jump but doesn't do it ?

**Comment by Guruone2023** [comment]
![image](https://user-images.githubusercontent.com/132165973/235324829-b815c3bb-b123-4119-9890-f9e8a71861d9.png)
![image](https://user-images.githubusercontent.com/132165973/235324848-9937c0df-797f-484e-a6ba-d419561cf7dc.png)
![image](https://user-images.githubusercontent.com/132165973/235324873-de85f7c3-6f52-45e5-b1b5-50bf2502bc58.png)
![image](https://user-images.githubusercontent.com/132165973/235324899-a96672b2-f837-420b-841f-cc8057b8ae16.png)
actually apart from this the wicked engine is actually very good

**Comment by Guruone2023** [comment]
IT APPEARS TO BE TELEPORT - WIN GAME IN MARKERs

**Comment by Guruone2023** [comment]
![image](https://user-images.githubusercontent.com/132165973/235324987-e804b7d3-aebc-4266-9d40-9d11cb55a5ab.png)

**Comment by Guruone2023** [comment]
![image](https://user-images.githubusercontent.com/132165973/235325420-61cf0fa7-9c28-4228-979b-1650f42e0f64.png)

**Comment by synchromesh62** [comment]
> IT APPEARS TO BE TELEPORT - WIN GAME IN MARKERs

Just tried a very basic setup and it worked fine for me ?
**as you can see it shows the jump but doesn't do it ?**

You realise jumping to the next levels only works in standalone right ?
In test game you only they the **Jump To Level : mapbank \mymap.fpm** to confirm its pointing to the correct map.

**Comment by Guruone2023** [comment]
OK -understand - that does actually a good point and no wasn't aware my bag i guess - should've read that in guides - anyway thanks - guess with the designing going on got frustrated as you can see a lot is going into making the game - Sorry

**Comment by MonkeyFrogStudio** [comment]
If this issue is resolved, then you should close it so the devs don't have to deal with it.

**Comment by davetgc** [comment]
Closing for now. If this is still an issue, please reopen.
