### ISSUE TITLE
Vegetation painter not working

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#4593]
I'm unable to paint any vegetation in my level at this time. I had limited success earlier but when I tried painting additional vegetation the previous plants went away. Recorded a short video to demonstrate.

https://youtu.be/oEjb5XbAIQY

I tried closing and reopening GGM and I tried adding the vegetation to multiple levels. I do mostly indoor levels so I hadn't experienced this issue before. I also tried verifying the files but had no luck.

**Comment by MonkeyFrogStudio** [comment]
Just did a quick test and painting grasses is working on my end. Hmmm ...

**Comment by Blood-Moon-Interactive** [comment]
Yeah I wasn't able to replicate this issue on my laptop, So it does seem to isolated to my desktop. I also want to note that while I did not adjust the sliders in the video, I of course tried that before submitting the issue to both extremes (left and right) without result.

**Comment by plemsoft** [comment]
@Blood-Moon-Interactive Looks like you have disabled vegetation in the "View Options", Please check that :)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft If you have vegetation turned off under View Options, then the Edit Mode area for painting plants would be blank, except for a Enable Grass tick box:

![veg](https://user-images.githubusercontent.com/36735507/235495737-343f5f55-babc-4494-82b5-f8b6acf0b03b.png)

**Comment by Blood-Moon-Interactive** [comment]
@plemsoft Can confirm vegetation is/was ticked in view options, so that is not the cause of this issue.
