### ISSUE TITLE
MAX - errors building from repo

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#4597]
![MAX build errors](https://user-images.githubusercontent.com/35708338/235438819-e79c6f02-a0ce-4c37-a93e-09aa377a46e9.png)

Pretty sure I followed all the steps but get these errors when attempting to build it.

**Comment by cybernescence** [comment]
It builds for me, though I had to rebuild the Wicked solution first (thanks to tip from Preben) and also the ogg/vorbis solutions to get the static libraries.

**Comment by AmenMoses** [comment]
Hmm, rebuilding Wicked got rid of the E0766 errors but it still complains about the missing strmbase.lib.

Where are the ogg/vorbis solutions at?

**Comment by plemsoft** [comment]
@AmenMoses  Strange looks like they are only in the classic repo:
https://github.com/TheGameCreators/GameGuruRepo/tree/master/GameGuru%20Core/Dark%20Basic%20Public%20Shared/Dark%20Basic%20Pro%20SDK/Shared/BaseClasses

Perhaps git lfs was disable at some point  ? Try to copy these into the foler:
https://drive.google.com/file/d/16pK_dvL6T8k0Bwap6DceY2jfMYpg_vzT/view?usp=sharing

**Comment by AmenMoses** [comment]
That worked, cheers.
