### ISSUE TITLE
Blank points after change terrain texture

### ISSUE THREAD

**Issue by rafamem** [TheGameCreators/GameGuruRepo#460]
Please wacht this video in FHD: https://youtu.be/d-NbwtA18Xg

**Comment by GraPhiX-Guru** [comment]
Hi
that's the global specular, trying bringing the slider down, run a test game press tab tab then slide the global specular down until it disappears

**Comment by GameGuruEvan** [comment]
Hi rafamen,

  Did the above solution resolve your problem, or are you still experiencing similar issues?
