### ISSUE TITLE
Phantom Function Bug

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4600]
The function is failing to work properly at all. It's also not showing up in the editor after you go back to edit mode from test mode. Not sure what the intended functions are supposed to be so don't know how much of the script works or not works.

Attach a phantom function to NPC or physical/nonphysics object and observe the bug.

**Comment by Necrym59** [comment]
Seems to work ok here can you be more specific as to whats happening

**Comment by kadinshino** [comment]
> Seems to work ok here can you be more specific as to whats happening

https://user-images.githubusercontent.com/71521025/235725078-b904f4ba-aed4-4dc5-9733-43c1d917040c.mp4

This is whats happening for me

**Comment by synchromesh62** [comment]
You have not attached him to a triggerzone.
He wont do anything ingame if he is not triggered.

**Comment by kadinshino** [comment]
I see now, it looks like it still has issues with the object coming back to full transparency in the editor. 

So when it says face approach, the chair should have turned and moved towards me right? 

https://user-images.githubusercontent.com/71521025/235776243-f8bca827-f51b-477d-97be-3c58a97b0ffa.mp4

**Comment by synchromesh62** [comment]
**" So when it says face approach, the chair should have turned and moved towards me right? "**

Not unless you have set your chair as a character in the .fpe
Otherwise its not going anywhere which is what i did to test this model.

https://user-images.githubusercontent.com/35708217/235797213-b194a74f-f4b6-4ff9-b054-d79cd181a416.mp4

**Comment by Necrym59** [comment]
It seems as though the PushObject command is no longer working it may be broken
