### ISSUE TITLE
max wont export game (again) 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4601]
its 3:16 am.

I've jsut sat at my pc watching and hoping that it would export my final version of the game I have spent years working on.

it failed. again. 

it stayed at 1% for nearly 2 hours. The fans would rev up, slow down, rev up, slow down, max would go from how it looks to not resposnding.

MY PC will continue to rev up, and rev down. and then.

everything stops. the opened web browser (I have twitch open to pass the time waiting for this dam thing to export) cuts out saying its ran out of memory, and seconds later.....max crashes to desktop.

no warnings. NOTHING.

2.
HOURS.

FOr what??

im sorry. but I'm done. This is now begining to affect my mental health in a massive way, messing up my sleeping, triggering my moods to just plummet, sending my anxeity flying in all directions because I HAVE PUT MY GOD dam heart and soul, my tears and sweat and blood INTO THIS GOD DAM GAME.

DID YOU KNOW during the development of Titanic Historia I lost my uncle, lost a goods to illness, but I carried on.

carried the hell on to try and get this absolute MESS of a game finished and exported.

And this is it. The final hurdle and MAX FAILS EVERY TIME.

I'm sick of it.

I'm sick of being told to "send my game files"

THE FOLDERS TO BIG. THE GAME FILES ARE STORED IN DIFFERENT FOLDERS. I CAN'T GO THROUGH THEM ALL AND PICK THEM OUT ONE BY ONE. 

I've tried. No one is helping me. I'm getting no sleep AGAIN because of this.

i want this PROJECT finished, exported so I can move on with my life.

but no.

here we are again.

ggmax WONT export my god dam game and I am loosing my actual mind over this.

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/235572014-c3bb568c-5b5d-48d3-a1ce-cc8a3837f684.png)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/235572032-ba3c8d17-d3c7-4c7e-b746-d499959386d0.png)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/235572389-b15b3ac1-0129-4608-9b5c-16894c465403.png)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/235572457-eb000258-1343-4cf8-a5c3-53c64bd7644e.png)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/235572553-b66d2a6f-ff1d-4985-986f-02d1d7ac25ed.png)

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/235573126-7ab84df6-02a8-4bad-a284-a6828db606ca.png)

memory is climbing and climbing and climbing......

**Comment by davetgc** [comment]
Closed at request of author.
