### ISSUE TITLE
GameGuru Classic - Importer Bug

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#4602]
The importer in Classic does not purge the temp file after importing an asset, the temp file in question is in files\importer\temp\tempFBXVersion6.dbo.

When i import animations for a character it uses that temp file but the temp file never gets refreshed so ALL animations are the first import.

**Comment by smallg2020** [comment]
can confirm this happens with objects and animations.
if you import multiple objects they appear fine in the model window but when you go to add them to the level they're broken (restarting GG doesn't fix it).
[https://youtu.be/p2DtWBiL2nA](url)

**Comment by smallg2020** [comment]
p.s. on the subject of the importer if you cancel the save when importing an object (i.e. when it asks where to save the model) if you close the window instead of saving it crashes GG

**Comment by SlyCrespo** [comment]
I have exactly the same problem. Please fix that soon. Thanks!
