### ISSUE TITLE
The doors in de building editor are not closing right

### ISSUE THREAD

**Issue by renegms** [TheGameCreators/GameGuruRepo#4606]
The doors in the building editor are not closing right when test game. 

See screenshots:
![20230503213643_1](https://user-images.githubusercontent.com/2426728/236027159-d950ec24-e7e8-43f9-87e2-abbf52c14d22.jpg)
![20230503213650_1](https://user-images.githubusercontent.com/2426728/236027287-871b7f14-2fe8-440e-88ca-e785d5fa1f8b.jpg)
![20230503213655_1](https://user-images.githubusercontent.com/2426728/236027404-c87139a8-f0d2-4308-8583-3fdb6fa8c6de.jpg)

**Comment by Lemuripest93** [comment]
Already reported here: #3846 :)

**Comment by renegms** [comment]
Ok thanks, but it is still there not fixed. ;-)

**Comment by davetgc** [comment]
Closed as duplicate : https://github.com/TheGameCreators/GameGuruRepo/issues/3846
