### ISSUE TITLE
building editor window shadow is not correct

### ISSUE THREAD

**Issue by renegms** [TheGameCreators/GameGuruRepo#4607]
building editor transparent window shadow is not correct

See screenshot:
![20230503214320_1](https://user-images.githubusercontent.com/2426728/236029196-cdfa3223-5496-47c8-b30b-6ecbd85a7c97.jpg)

**Comment by davetgc** [comment]
In what way? Do you mean you expect the frames to cast shadows?

**Comment by renegms** [comment]
Indeed I expect the frames also to cast shadow. But that is not the case?

**Comment by Lemuripest93** [comment]
Technically this isn't a bug related to the Building Editor but a model related bug, specifically it's a transparency bug. There's been a lot of these and a bunch of them have been squashed, i guess this one slipped by the devs.

![WarehouseWindow Transparancy](https://user-images.githubusercontent.com/104637906/236650652-4de4ee89-0997-4369-abe9-fcb6a348e5fe.png)

As can be seen in the screenshot, you can see the sun through the frames, similarly to how you _used_ to be able to see it through doors, your weapons, etc.
