### ISSUE TITLE
character start always in t-pose 

### ISSUE THREAD

**Issue by renegms** [TheGameCreators/GameGuruRepo#4608]
character start always in t-pose 1 second, and then goes to animation

see screenshots
![20230503215215_1](https://user-images.githubusercontent.com/2426728/236032277-23035d1d-f1d6-4020-92e8-ed7f1a6bb542.jpg)
![20230503215234_1](https://user-images.githubusercontent.com/2426728/236032541-5976edcf-c602-4890-8dea-a3a991d1158f.jpg)

**Comment by davetgc** [comment]
Characters will always start like that until activated. You could set a character to always active, which will activate it instantly, but it will then be active no matter what distance the player is from it.

Does that solve your problem?

**Comment by renegms** [comment]
Ok thanks, but why not start in idle stand first time! Instead of the t-pose. 
I will try with always active if that helps.

**Comment by Kitakazi** [comment]
@davetgc 
That's not true, characters are starting in T-Pose even when activated and even when "always active" is set to Yes. Please see #3752
