### ISSUE TITLE
FreezePlayer and F9 Edit Mode Conflict

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#461]
While this isnt a huge issue, it is something I noticed.

IF FreezePlayer() is used, you will not be able to then move the camera in F9 Edit Mode.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed .. Although im no scripter I do know " The Big Escape " uses FreezePlayer() before you press "E" to continue … Press F9 on that screen and the camera will not move..

**Comment by LeeBamberTGC** [comment]
Nice find. It seemed player physics was completely shut down during a freeze, which was needed by the F9 player movement system, so F9 bypasses the limit on player physics.
