### ISSUE TITLE
Pause menu error

### ISSUE THREAD

**Issue by blackhat110** [TheGameCreators/GameGuruRepo#4614]
The pause menu does not work properly, no buttons except to resume the game and go to the main menu do not work ie: controls, save, load buttons.

My specifications are:

Intel core i7 10th generation

Nvidia geforce rtx 2060 card

32gb ram

**Comment by davetgc** [comment]
Hi,

Can you please confirm that this is in Standalone?

**Comment by blackhat110** [comment]
@davetgc I confirm

**Comment by LeeBamberTGC** [comment]
@blackhat110 Plenty Storyboard fixes in the latest EXP build, including repaired buttons and ability to restore corrupt screens via Restore Screen option.

**Comment by blackhat110** [comment]
It works
