### ISSUE TITLE
Objects with Multi Mats, and Transparent Materials Bug

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4615]
The issue, I believe, is related to #4267 

I was trying to import a new object and set the transparency settings for only one material type. If you click off the object, all materials default to "Transparent," or if it's checked or not.

This bug has been persistent since at least the last update. I went back to some old files created on 4/27, and the issue is there on some objects but not everything I had uploaded. 

 To make things more complex, On may/1/2023 I uploaded a tree, and all went fine.

I went to upload a simple object today and saw the issue present on a simple object. may/6/2023

https://user-images.githubusercontent.com/71521025/236647717-528cdc8e-6cc5-4a61-add4-e63743c55c44.mp4

It doesn't seem to affect objects that already exist or all object types.

Attached are both object files in case its object dependent. 

[Objects.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11413441/Objects.zip)

**Comment by bond1mjb** [comment]
I can confirm this also.  A multimaterial object loses it's transparency setting as soon as it is moved in the editor:

https://user-images.githubusercontent.com/87768878/236648881-ffe55b14-488e-42da-9efb-59d7abb91838.mp4

**Comment by LeeBamberTGC** [comment]
@kadinshino @bond1mjb Fixed for NEXT EXP build - thanks for the report!!

**Comment by bond1mjb** [comment]
@LeeBamberTGC Awesome, thanks!
