### ISSUE TITLE
Task Object and Task Tool Bug

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4619]
If you create a Task Object to be triggered by a Task Tool, Everything works with the baked-in tool list.

IE, if you use the crowbar on a crowbar task object, it works perfectly fine.

However, if you use "Named Tool." and say use the name "Red Gem," a Task Object will trigger regardless of the tool name if it's set to "Named Tool." and fail to recognize the different types of named tools the user puts in.

So if you want to set up a Task Tool that requires a "Red Gem" and pick up a "Blue Gem," the task object will still trigger as complete. 
This means you cant use different custom tools to activate task objects.

Not sure if this was a posted issue, I could not find it in the repos. 

https://user-images.githubusercontent.com/71521025/236932023-4d51d27b-28bc-4fbf-8ba1-f2b0ab0c53f0.mp4

**Comment by Necrym59** [comment]
this has been fixed
