### ISSUE TITLE
PBR objects that use illumination dont light map

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#462]
All objects in this map are static. Mix of dynamic 4, and static 16 lights are used. apbr_basic.fx and abpr_illum.fx used in the map.
All objects that use apbr_illum.fx shader with the _illumination texture do not light map.

https://puu.sh/C8QuA/665c8810f1.jpg
https://puu.sh/C8Quh/bbc8fe3b3c.png
https://puu.sh/C8Qu9/e602e030c8.png

**Comment by plemsoft** [comment]
@Pirate-Myke Thanks for reporting this,

Should be fixed in the latest update.

**Comment by Pirate-Myke** [comment]
Yes this is fixed for me. Thank you.
