### ISSUE TITLE
[Max] cloning object bug (SpawnNewEntity)

### ISSUE THREAD

**Issue by smallg2020** [TheGameCreators/GameGuruRepo#4622]
if you clone an object and then explode the clone, if you then clone the object again and the system "clones" with the same ID it doesn't clone correctly.

steps.
1. place explodeable barrel - let's call it 1
2. clone it with the SpawnNewEntity(1) - let's call it 2
3. explode obj 2
4. clone barrel 1 - let's call it 3
5. obj 3 is already considered exploded as it's actually object 2

i assume the system is using a pooling system in the background but there needs to be a check for if the object is exploded and a way to reset it if so

**Comment by Necrym59** [comment]
Cant understand why would you clone a clone? Why not just clone the original again.?

**Comment by smallg2020** [comment]
not cloning a clone, try reading the instructions :)

**Comment by LeeBamberTGC** [comment]
@smallg2020 So I do not reproduce a false scenario, can you attach a small FPM with stock objects and zones and a small instruction on what I should do as player? I can then see your cloning, exploding, bug :)

**Comment by smallg2020** [comment]
looks like this one has already been fixed
