### ISSUE TITLE
Game Guru Max Blank Screen AMD

### ISSUE THREAD

**Issue by moorket** [TheGameCreators/GameGuruRepo#4623]
My screen is blank, do you have an idea as to what may be the cause of not being to see the terrain generator.

**Comment by MonkeyFrogStudio** [comment]
When posting an issue, but, or request here, it's best if your title were descriptive so the developers know what the thread is about. Having a title like, "Game Guru Max" is not helpful to them.

Secondly, when reporting an issue like yours, it's always a good idea to post your system specs. For example, there's a known issue with certain AMD video cards. If you'd posted your system specs and you have one of the AMD cards that's causing the issue, then someone could let you know that's the issue, that it's known, and that a fix is being worked on. Without your system specs it's really a guess as to what the issue could be.

**Comment by moorket** [comment]
Thanks for the info!  Shall I redo it?

Device name	TRUSTDESK
Processor	Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz
Installed RAM	64.0 GB (63.9 GB usable)
Device ID	95CA586A-9D68-4B51-9F19-BC2D9CECCDB8
Product ID	00330-80000-00000-AA548
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by moorket** [comment]
I'm looking for vid specs now

**Comment by MonkeyFrogStudio** [comment]
It's most likely the AMD card that's causing the issue. It's an known bug that's been proving difficult to squash, but they are aware of it and working on it.

**Comment by LeeBamberTGC** [comment]
@moorket We released an update on the 10th, adding your specific card to the AMD fix. Can you auto-update on Steam and let me know if it now works for you, thanks!

**Comment by LeeBamberTGC** [comment]
Properly fixed now for next EXP build - was RSSetScissorRects and a recent AMD driver update!
