### ISSUE TITLE
sound trigger error

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4624]
ive placed multiple sound triggers down for events that happen on a game Im just playing around with.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/ed8d8310-aab2-463e-a397-d3261ed8888b)

the above sound trigger plays the sounds in this sound trigger.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/b0dd8c54-a1eb-4faf-ae00-6f04d14387c3)

The sound zones are also randomly changing colour in the editor too....

its a really really really annoying bug.

**Comment by casigus** [comment]
the music zone only triggers when you enter the sound zone.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/2d86c99e-3098-42a2-a6dc-b6c21f4850ee)


seriously what the hell is going on with the trigger zones suddenly breaking?

**Comment by casigus** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/7cc87dcd-e63f-4a87-bff1-6652cefcfe03)
????

**Comment by casigus** [comment]
the zone has literally removed the border and wont play??

**Comment by davetgc** [comment]
Can you supply an FPM please demonstrating this issue?

**Comment by casigus** [comment]
again it goes to the issue of custom media being to large to send a fpm over, but the bug occurs have prolonged use of max which suggests a memory leak issue maybe? but yeah was very very annoying. its basic function breaking down.

**Comment by davetgc** [comment]
Has anyone else encountered this and can find a simple way of replicating it?

**Comment by casigus** [comment]
not seen it pop up yet, but was using ALOT of custom assets, not had it happen again either, but have seen this error a few times, but it just seamed to correct its self eventually! but seams to be just completely random when it happens. was very odd even the trigger zones colour where changing too!
