### ISSUE TITLE
GameGuru Max - SecCam rotation bug

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#4628]
While setting up a security camera and using the SecCam behavior, I discovered something unusual. After reviewing this with Necrym and playing around with it some we discovered that there's an issue with the starting position of the camera when manually positioning it in the level editor. For some reason the position of the camera object is not saved if you use the widget to rotate the object, but if you use the slider it will record the correct starting position. The video below will demonstrate this issue.

https://youtu.be/vmyF616i7R0

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Great repro video, fixed for next EXP build :)

**Comment by Blood-Moon-Interactive** [comment]
I tested and confirmed today that rotating the camera using the widget preserves the position of the camera. Thank you!

**Comment by Blood-Moon-Interactive** [comment]
Fixed
