### ISSUE TITLE
Raise Terrain acting weird

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4629]
I have not not found the root of this issue yet, but it could have something to do with the creation of the extremely steep cliffs and leveling of the surfaces. I used both the Level Mode and Pick/Paint Height tools to do this.

For some reason, the Raise Terrain and Lower Terrain tools eats away chunks of terrain that were at some point flattened and then raised, blened, and/or flattened Every other tool works as expected.

A new video has been posted below.

**Comment by davetgc** [comment]
Hi, can you please repost your video in a supported format?

**Comment by TenebreGaming** [comment]
It's a .mp4... what format does it need to be?

**Comment by TenebreGaming** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/4973c298-c4d7-4ac5-99ab-d0362eb1c85b

This one might be better. I think a nonstandard codec was used on the fisrt one.
