### ISSUE TITLE
GG MAX navigation system bug

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4630]
closed doors are creating a big space where the NPC cant walk, thats problem in small coridors like this...

https://github.com/TheGameCreators/GameGuruRepo/assets/109030026/1fdf367d-48bd-4283-ad7b-88d94e9437ba

**Comment by LeeBamberTGC** [comment]
@Keepo1 Fixed for next EXP build. Replaced the toggle polygon system (that could disable quite large areas under the characters feet) with a path cost system more local to the blockers, preventing characters path going through the bounds of a door.
