### ISSUE TITLE
GG MAX issue - colectable Items

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4631]
colectable item list from one my project is listet with items from other project I have... 
I dont know if its a bug but I think they should be listed separatly.

**Comment by davetgc** [comment]
This could be related to this, some non collectable objects are also appearing in the collectable list:

![20230516113847_1](https://github.com/TheGameCreators/GameGuruRepo/assets/99803873/ed876ecf-2664-47b5-a55d-f2c750608017)

**Comment by LeeBamberTGC** [comment]
@Keepo1 Try with latest EXP build and see if this still happens. Probably best to open the "collection - items.tsv" collection file and delete the ones you suspect are corrupt entries.
