### ISSUE TITLE
behaviour default directories wrong

### ISSUE THREAD

**Issue by Grogadog** [TheGameCreators/GameGuruRepo#4634]
Behaviours
default file directories wrong
Quest poster not in Objects should be Rpg
Count collection not in Objects should be Puzzle .
Will inform anymore as I build game. Thanks

**Comment by Grogadog** [comment]
Also Code switch in objects , should be Puzzle

**Comment by MonkeyFrogStudio** [comment]
All of these are showing up in the correct places on my end. Code Switch is in Puzzle, Quest Poster is in RPG, and Count Collection is in Puzzle on my end.

**Comment by Grogadog** [comment]
Hi , Yes that's right, BUT
Having assigned the behaviour to an object. Then click on the behaviour in
the right panel and the wrong default directory appears,
e.g.
code switch correct found in puzzle directory, close behaviours, now click
the code switch in the right panel, assigned to an object, and the 'object'
list appears!!.
I found some of these problems playing the RPG template. rgp template
wouldn't work until I tweaked it!

**Comment by MonkeyFrogStudio** [comment]
I think that MAX just always defaults to Objects when you click on a Behavior that has already been assigned. So, you have to navigate to the folder you want. I don't think this is a bug, actually. But what you may want to do is request that MAX opens to the folder that the Behavior is from (if you click on one that's already assigned).

**Comment by Grogadog** [comment]
ERROR BUG found.
blackbird object , lua assigned is animals\mammal_wander.lua
No such lua.
Should be animals\bird.lua
The mammal one is : animals\mammal_generic.lua
Steve (Grogadog)

**Comment by Necrym59** [comment]
Those errors usually comne from not deleting the showcase folder which is now redundent

**Comment by Grogadog** [comment]
Did an uninstall about two weeks ago,cleaned out residue ( revo uninstall).
And then reinstalled it!!

**Comment by Grogadog** [comment]
found showcase folder, thanks
Steve
