### ISSUE TITLE
GameGuru Max Melee Weapons DLC Bug

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#4635]
Hi,

Slots 2,3,4,5,6,7,8 do not work when a second weapon is picked up from the ground.

Applies to all weapons in the list below.

Wasteland Workshop Booster Pack:
Crowbar
Spanner No5
ScrewDriver Large Black
Lump Hammer

Wasteland Weapons Booster Pack:
BikeGearKnuckles
BlockBuster
CementMace
machete
Nailbat
pipe
railspikespear
sawbat
signaxe
Wrenchknife

ps all clean, gore, 2k and 4k version

**Comment by davetgc** [comment]
Thanks for reporting this.I suspect that it isn't a bug with the DLC, but with the weapons.

**Comment by sfkylcnky** [comment]
Hi Dave,

You're welcome. I don't think the same as you on this matter.

for example below list works fine.

Aztec Game Kit:
Aztec Dagger
Aztec Axe
Aztec Spear

ps my version GameGuru MAX Build 2023.05.10

**Comment by sfkylcnky** [comment]
Hi Edward,

The list below works fine for me.

Frag Grenade
Pocket Knife
Sledgehammer
Magnum Pistol
Patrol Rifle
Tactical Pump Shotgun
Compact Assault Rifle
Assault Rifle
Snubnose Revolver (it's just like it has no ammo. has anyone seen? Or know where it is?)

**Comment by GraPhiX-Guru** [comment]
I have been looking into this issue all morning, and wondered if it was a code issue, and sure enough smallg found that weapon.lua is causing the problem. he as kindly written a new weapon.lua.
Can @LeeBamberTGC  please test and confirm this version does not break any RPG elements.
Thank You
[weapon.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11497301/weapon.zip)

**Comment by davetgc** [comment]
@LeeBamberTGC - FYI.  I happen to know that a new weapon lua is being written at the moment, which brings it in line with the other collection scripts.

**Comment by sfkylcnky** [comment]
![1](https://github.com/TheGameCreators/GameGuruRepo/assets/37545408/bb0f76fd-9bbd-44f8-ac87-03cb443ca6ad)

Hi GraPhiX,

Your changes are very good. thanks a lot. i have all 25 guns working without any problem.

**Comment by Edward3360** [comment]
@GraPhiX-Guru I can confirm. Your script works perfectly, and solved my problem. Thanks!

**Comment by sfkylcnky** [comment]
@davetgc @Edward3360 @GraPhiX-Guru

hi guys,

i think T to replace feature not working.

**Comment by GraPhiX-Guru** [comment]
> @davetgc @Edward3360 @GraPhiX-Guru
> 
> hi guys,
> 
> i think T to replace feature not working.

No the replace is not working in the engine ATM i think it is being added soon though :)

**Comment by davetgc** [comment]
Hi all, Necrym is working on updating all these scripts to bring consistency to them, so all scripts work in a similar way. @GraPhiX-Guru  - I'm not sure of the value of replace anymore, now that we can have many weapons.

**Comment by LeeBamberTGC** [comment]
@sfkylcnky Latest EXP build made improvements to the weapon slot code so any weapon, even non stock ones show up when collected.  Please test and let me know if they now show up and are selectable when collected.
