### ISSUE TITLE
There is a way to limit fps?

### ISSUE THREAD

**Issue by ghost** [TheGameCreators/GameGuruRepo#464]
It is possible to have an option in the setup.ini for block the fps to 30-60-144? Having a 144hz monitor and activating the vsync it remains at 144 fps and like this the step sound is slow down but putting at 60 or 30 fps the problem doesn't exist.

**Comment by Teabone3** [comment]
In the setup.ini (I believe its called) you turn vsync on and it will limit to 60fps.

**Comment by AmenMoses** [comment]
Setting vsync=1 in the setup.ini file will cap FPS at 60 regardless of what your monitor is.

**Comment by Teabone3** [comment]
I think this question has been answered? And topic should be closed?
