### ISSUE TITLE
Prolonged use hides behaviors and folders.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4640]
As the title says, prolonged use is hiding some folders, notably DLC's and the categories for the behaviours.

Hidden objects and behaviours are still findable with search.

A restart of MAX solves this issue, but it will reoccur.

**Comment by LeeBamberTGC** [comment]
@davetgc I will need some more info to reproduce this one. A very recent change ensured the objects found and displayed did not use 'phonetic' and other weighting systems to show them (from the A-Z fix), and this may have resolved this one in the latest EXP build. If you can use the latest and reproduce this issue, post a step by step and I will investigate, thanks!
