### ISSUE TITLE
Collectables not always avaible across levels in editor.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4641]
Collectables added in previous levels are appearing in the Collection Items List but aren't always placeable or selectable from that list.

In addition, Collectables deleted from the list are still appearing.

Note that in the attached image, none of the objects have been placed in the level,

Also, note that Blank object at the very top of the list.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/99803873/92d306ab-eef5-45b4-863c-76dff3dd260d)

**Comment by davetgc** [comment]
@LeeBamberTGC  - As an update to this, saving a level that doesn't contain a certain collectable, the list is reset to show only the collectables in the level. It should always contain collectables from the collectables list regardless of where they are.

It's also vital that objects listed in the collectables list can be selected to add to the level. E,g. Clicking on a collectable from the list, should attach the collectable object, with all the relevant settings to the cursor for placement.

**Comment by davetgc** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/99803873/82ad483e-a4f0-409a-aee1-8c849688739d)

Another update on this, items (including characters) that aren't collectables are also appearing in the list.

**Comment by davetgc** [comment]
Yet another update. It appears that collectables are loading correctly when the level is first loaded, but are disappearing when the level is saved.

**Comment by LeeBamberTGC** [comment]
@davetgc To oneof the points of this report, simply adding/creating collectable items and saving (I used a simple 2 level project for this) did not cause them to disappear after saving, so I suspect some deeper corruption causing this one. If you can make exrta steps from a fresh project where adding bread and milk to a new level and saving causes them to disappear as collectables, please do post here.

I can confirm that the collectables I added did not show up in level 2 when they should have done so for game project consistency, but did so when I exited MAX and relaunched the prject and loaded level 2 immediately, then I went to view level 1 ad only the bread shows up as a collectable in the list:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/7a8c4cb3-da15-49af-9cf2-b889b6c59a7c)

This suggests a few issues that I can see leading to larger corruption referenced in this report. I did fix an issue from this report that now clears some internal ENTID and E references from the collection list before a new level is loaded, which did indeed restore the correct collection list in my small 2 level project. Try the NEXT EXP build which has this fx to confirm if from a new game project with multiple levels and collection items that no corruption occurs.
