### ISSUE TITLE
Collectibles with melee and other weapons

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4644]
With collectibles enabled and a player starting weapon of "Melee Combat", you can drag another weapon into the spot reserved for the melee weapon (which has no image associated with it and appears empty). If the first inventory slot (upper left corner of inventory) is empty, the weapon will go there instead of the hotkey slot but will be equipped anyway. If however, there is an item in that position, the weapon will be equipped and will not be in the inventory or kotkey list as expected. In fact, it will be assigned to hotkey 2 (though the image of what was in hotkey slot 2 remains) and the item in hotkey slot 2 disappears and cannot be recovered.

Dragging objects from any hotkey slot to any other non-vacant hotkey slot also exhibits similar results and strange behavior. I have noticed that some but not all of the objects are being dropped on the ground nearby.

Grenades also act strangely. If you have one in your hotkey list, you can drag others into that slot (as if ammo?) but sometimes one will increment the count but will show being added to the inventory though (and appears to have an ammo count of 0 and can't be used). It's also odd that even after using all your grenades it still shows in the hotkey slot. This is probably because of the way the weapons are internalized and aren't part of the RPG system.

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Let's walk through the various issues until we have it all. The first part is fixed for the next EXP build, you can assign a Melee Combat to the Player Start Marker, then drop an assault rifle to collect, and it collects in slot 2:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8bb14b36-3c9d-41c6-a3f5-0f5a034a06e9)

You cannot remove the Melee Combat slot as that is fixed as designed, but you can move the rifle about and the hot key KEYS are aligned and work.  

Test this much and let me know what else you find, thanks!

**Comment by TenebreGaming** [comment]
This seems to be working much better now. I will close this issue and open a new one if anything further pops up.
