### ISSUE TITLE
The Assault Rifle/AK47 Model Has a Graphical Bug

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4647]
There is a section of the Assault Rifle gun that is bugged. If you look at this rectangle I have circled in my screenshot the texture is really bugged out. Way to reproduce this is to equip the assault rifle. You can tell super easy when you move around cause it moves like independent of the rest of the gun like its being clipped or something. Screenshots dont do this justice it looks really bad when moving. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/0f422f2d-1d3e-4186-b5e1-13640dc5e13f)

Looking straight up seems to make the bugs super noticeable. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/e55d37eb-4ee8-4292-92e1-5111a1a3b13e)

**Comment by MonkeyFrogStudio** [comment]
Yep. Seeing that here, as well.

**Comment by bond1mjb** [comment]
Changing the polygon draw order, then re-exporting fixes it.   I'm guessing it has something to do with the recent updates to the way transparent objects are drawn.

New export:
https://github.com/TheGameCreators/GameGuruRepo/assets/87768878/b5e0479c-bb0c-4831-8212-ff4060b9e154

**Comment by LeeBamberTGC** [comment]
@bond1mjb When you find time, can you send me the new export and I will add to the next EXP build?  Some work was done on all weapons so they can block the lightrays and handle better with the scene, but looks like this one crept through :)

**Comment by bond1mjb** [comment]
@LeeBamberTGC HI Lee, I've emailed you the new export for the AK47.

**Comment by LeeBamberTGC** [comment]
@bond1mjb Got it, thanks!!  Will be in next EXP build.

**Comment by Kitakazi** [comment]
Just noticed this issue is back. Maybe I closed the issue to early, thought it was fixed maybe not though.

**Comment by Kitakazi** [comment]
nvm this is fixed. I had to re-install steam the other day and it kicked me out of the experimental builds and didnt realize it. sorry.

**Comment by Kitakazi** [comment]
@bond1mjb How did you fix that problem? I'm trying to import a weapon pack I bought off CGTrader. Everything works but I have what looks to be the same type of graphical bug happening on the arms. 
Here is a video https://www.youtube.com/watch?v=upcITCE0ie0

here is the area that is affected. 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/12716574-e125-4101-8e01-65df01a4f3d5)

**Comment by bond1mjb** [comment]
@Kitakazi Hi David,.  I fixed this problem on the assault rifle by changing the draw order of the offending polygons, then re-exporting.   Usually objects that can use transparency get rendered in a back-to-front order.   And the same goes for individual polygons within an object. So depending on how this weapon was modeled by the creator, certain polygons may be getting rendered out of order.   You would just need to import this into your preferred modeling app and change the polygon ordering in those two problem areas.   I'm not sure every modeling software has this capability, but I know 3ds Max does (this is what I use).

**Comment by Kitakazi** [comment]
Thanks, this is all beyond me really and I do not own 3ds Max. I'll try to
figure something out, thanks for the reply
