### ISSUE TITLE
Wasteland Detritus, cobwebs and streetlamp causing MAX to freeze.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4648]
These assets were working on release, but now cause MAX to freeze when launching a test game that contains them.

**Comment by bond1mjb** [comment]
@davetgc Inform the creator of this dlc so resave the "Webs_trim.dds" texture in BC3/DXT5 format with mipmaps.  This fixes the crash.   I would post the fixed texture here myself but don't want to expose the content publicly.

Either the texture was saved in the wrong dds format, or somehow got corrupted at some point.

**Comment by Bullyblasta43** [comment]
dont forget the, "streetlamp_c", the one with 4 lights on the top. drop just that object in and hit test level and it crashes.

**Comment by davetgc** [comment]
Hi, I'm having these issues fixed by the artist now. I'm uncertain of when the error crept in, as all was well on original testing.

**Comment by davetgc** [comment]
[Webs_trim.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11525083/Webs_trim.zip

@Bullyblasta43 - Can you please test this web dds (Replace the file in your entitybank), if it works, I'll arrange for the streetlamp file as well.

**Comment by Bullyblasta43** [comment]
@davetgc - i can confirm that fix has worked, i have checked them all out one by one and no crashes, on top of that, the "streetlamp_c" with the 4 lights on top, no longer causes crashes either, but still might be something to look into  just incase there may be issues in the future.

**Comment by Bullyblasta43** [comment]
sorry it took so long to get back, i was in the middle of a D&D game

**Comment by davetgc** [comment]
@Bullyblasta43 - Thanks for the confirming, we'll move this to the official version.

P.S. D&D is a valuable use of your time :)
