### ISSUE TITLE
Please add a feature to disable sun light completely

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#465]
title says it all - it would be highly useful to disable sunlight for indoor levels

**Comment by Teabone3** [comment]
I also would like this feature. However possible it is to implement. Additionally if anyone knows a workaround in the meantime please let us know, so we can continue working on our game projects.

**Comment by GameGuruEvan** [comment]
For lightmapping, use "lightmappingdeactivatedirectionallight=1" in SETUP.INI and for dynamic lights, just reduce surface intensity to zero and rely on ambient light intensity to remove dynamic sun.

**Comment by Pirate-Myke** [comment]
**Unacceptable.** There is no reason why this cant be disabled for dynamic lighting. It has been a requested feature for 4 years now. We need to have shadows and baked lighting is incomplete.

**Comment by GraPhiX-Guru** [comment]
I have to agree this feature is a popular request along with 'blank' start map no terrain or sky, turning the sun off for indoor levels is a feature I think everybody wants with shadows to run along side it

**Comment by tarkus1971** [comment]
I think this feature should be implemented. Also how is the work on flashlight and dynamic light shadowing going. 

Switching off the sun is incredibly useful.

**Comment by Granada1** [comment]
It’s been a year since my clean level request ,Please 😀

**Comment by Teabone3** [comment]
Even if a dynamic sun might be a difficult implementation or just a complete drain on performance... a way to disable the sun entirely would be helpful.

I'm assuming a map would be black without the sun though and not simply "dark" ?

**Comment by plemsoft** [comment]
@Duchenkuke You can use the slider "sun surface factor" in the latest update to even out directional light, this also work on non lightmapped objects now. This will remove the sun effect on all objects/terrain.

If you like to test this in the beta you have to use "forceloadtestgameshaders=1" , Lee forgot to compile the shaders in the beta :)
