### ISSUE TITLE
[Max] cloned entities don't respect the material changes applied to the master object

### ISSUE THREAD

**Issue by smallg2020** [TheGameCreators/GameGuruRepo#4651]
if you try to clone an entity (with SpawnNewEntity(e)) which has had the materials settings changed (from within the editor) the cloned objects keep the original (base) materials and colours

**Comment by LeeBamberTGC** [comment]
@smallg2020 Fixed for next EXP build, let there be glowing rabbits:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/7e1ca97c-c2fb-4c1c-bb44-21378cfd7c2f)
