### ISSUE TITLE
GameGuru Max Importer Bug 

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4652]
This bug might be similar to the issue in GameGuru Classic #4602 

When importing an object to replace an existing object. Sometimes the object does not update properly or loses the object properties altogether after importing.

It looks like the object fails to overwrite the first time or fails to save overwrite.

Steps to reproduce. 

Create or use an existing model, import it into a new clean folder, and call it test_import_01. It does not matter if the object is fbx or obj. 

Change something small about the object externally from game guru like its UVs or simple model properties such as position. Reimport it as the same name and folder as before so you get the overwrite warning.

Click continue and you may or may not see the model update or adjust properly

Sometimes closing game guru fixes the issue, sometimes, it does not. If dose not, rooms sharing the model property will lose their position or other adjusted values. The only way to fix it after that is to remove the model manually from GameGuru Max and start from scratch.

If more information is needed, ill try to make a simpler test to show the issue better. 

Part One of Error

https://github.com/TheGameCreators/GameGuruRepo/assets/71521025/d5923264-e193-40d1-9f82-008a5130529c

Part Two of the error

https://github.com/TheGameCreators/GameGuruRepo/assets/71521025/0bbe19e7-0568-4bbd-bdfd-2f9ec1e1ccd3

**Comment by kadinshino** [comment]
New issue when importing objects after working on a single project for over 150 hours.

![folders](https://github.com/TheGameCreators/GameGuruRepo/assets/71521025/3da80bc6-6c67-477d-9eb6-b8d0177f0820)

When trying to import models, my models folder on the desktop no longer loads. I have to manually paste in the path to the object and where its located to upload models now. This bug seems to be a degrading issue with the amount of time spent on a single file.

**Comment by LeeBamberTGC** [comment]
@kadinshino Disappearing objects issue fixed relatively recently, and can still linger with corrupt levels. Should not happen with new levels but post here if you have an older level you would like restoring.
