### ISSUE TITLE
HUD.dbo not generating when creating new melee weapons

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#4655]
I have been re visiting the melee weapon workflow and imported a test weapon. during the process I have realized the HUD.dbo is no longer generating. I have tried verifying files and rolling back to the previous stable release with no luck. 

Furthermore I re named an already existing HUD.dbo in  a working weapon and it does not re generate in that folder either.

**Comment by LeeBamberTGC** [comment]
@42Pix3ls Are you looking for the HUD.dbo object in the writables location?  It's a little messy right now, but you need to copy the DBO file created in the writables to your gun folder to complete the weapon creation work. P.S. Thanks for making weapons for everyone!!

**Comment by LeeBamberTGC** [comment]
@42Pix3ls In the next EXP build the HUD.dbo file will be auto copied to the root area to save some time, and will correctly load the modified weapon first time.
