### ISSUE TITLE
New Parameters passed to _properties() as nil

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4657]
So I have this script that initially only had 2 parameters defined in the --DESCRIPTION:

After adding new parameters and reassigning the behavior (multiple times) and even after restaing Max (mostly because it crashed) the new parameters were all passed to the _properties() function as nil values. The values were showing correctly in the GUI, but they just weren't being passed in. I even tried changing the parameters to strings, and they were still passed as nil.

Out of frustration, I typed "Why is this not working????" at the end of the description line and it magically worked!? For some reason it finally decided to update the data.

***update

So I added another parameter to the script and it is doing the same thing again, only this time nothing I do seems to affect it. I've reloaded the level, reloaded the entire project, even restarted Max. I think there's something very strange going on... To try to deteremine the cause and maybe  a solution, I'm forcing a value of 999 in the _properties() function, but the value is still nil in the _init() function, so I force another value there, which works.

**Comment by davetgc** [comment]
Hi,

Can you please supply the script?

**Comment by TenebreGaming** [comment]
I would supply the script, but I wound up deleting it and starting over. If I encounter this again, I will definitely save the script.

**Comment by TenebreGaming** [comment]
So this is still sort of an ongoing thing when adding new properties to existing behaviors. I have found that a new parameter is defined but not assigned and as such will be nil until the value is changed from its "default" value in the UI, as it appears it only updates when a change is made.

**Comment by TenebreGaming** [comment]
This issue has apparently been resolved and is working as expected now.
