### ISSUE TITLE
Texture Apply to models Duplicates Library bug. GGMax

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4660]
New odd object bug. I would say it's a pretty major bug but I'm not sure how bugs are being classified to be worked on.

I am applying new textures to some existing walls I already have imported. Everything is already nested within the game guru max project files.

When trying to select a texture, for whatever reason, game guru MAX sometimes selects a random folder and starts copying textures to that path for no apparent reason outside of where the actual object lives.

So every time I apply a texture to a part or update a part to a new texture, game guru randomly thinks its ok to start loading other folders full of useless images and possibly broken paths. 

Multiple issues are happening in this video such as color and other properties not being read properly. but the underlying issue is it keeps duplicating textures when it should not.

[Files.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11547592/Files.zip)

Working file in case its object-specific 

https://github.com/TheGameCreators/GameGuruRepo/assets/71521025/fed66f2a-b10e-4223-a03f-c4c419c4bdd0

**Comment by LeeBamberTGC** [comment]
@kadinshino Thanks for the report, looks like an older folder was being used to deposit the local texture file copy when changing textures.  It is always best to ensure you select a texture that exists alongside your object, but if you are selecting from elsewhere, MAX will copy it over to associate with your object so all the texture files are local to the object, and only creates a duplicate file (and filename) if the texture cannot be simply copied as is.
