### ISSUE TITLE
New folders added to audiobank not being recognised without reboot.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4661]
As the little says, new folders aren't being picked up by MAX without a reboot.

**Comment by LeeBamberTGC** [comment]
@davetgc With developer mode active, there is now a REFRESH button in the library system you can press to refresh from the latest files on your local PC, ensuring you do not need to leave and return MAX to see any changes. We also have a HOT SWAP system in place to actively swap in any media changes to object and textures live inside the level editor.
