### ISSUE TITLE
GG MAX - Lensflare missing in standalone 

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#4662]
Title says it all.

Not even porting the files over manually doesnt help.

PLease fix it

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Tried with latest EXP build and could see lens flare in a simple level with some objects and sun high in the sky:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/cd35a87e-3654-41fc-b821-1a2cb64336a5)
