### ISSUE TITLE
GG MAX -- Musicinzone not working after player death

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#4663]
Title says it, after death, the music doesnt trigger again wich used to work in classic.
Here is the script I used: 
[musicinzone.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11562040/musicinzone.zip)

**Comment by LeeBamberTGC** [comment]
@Duchenkuke In latest EXP build, no player lives but do have checkpoint, so drop one of those in, run over it, then run through a second music zone with a different tune, get killed while new ambiaence playing on a loop, then listen as the music restores from the time you ran through the checkpoint to the first ambience loop. P.S. Standalone bug prevents checkpoint from working, another issue already reported.
