### ISSUE TITLE
[Max] Rotating Objects Bugged

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4664]
Using the rotate hotkey will rotate objects to odd values. Usually rotating the object 1 time will produce no errors, but rotating multiple times will cause the entity to rotate to 181 instead of 180. Or if rotating 3 times it will rotate to a value of 271 instead of 270. 

Sometimes rotating an object with the R hotkey will rotate the object randomly on a different axis than the X axis. 

Copy and pasting a group of objects or creating a group and then duplicating the group and trying to rotate the group will not rotate the group correctly. 

If an object is rotated 3 times to a value of 271 and then manually changed to 270 and then you later change the value to 0 and then copy and paste the object the new object will have a value of 1 and 1 for the X and Y axis instead of 0 and 0.

**Comment by Kitakazi** [comment]
I think this has been fixed now.

**Comment by Kitakazi** [comment]
Reopened this. Still happening.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Related to this one: https://github.com/TheGameCreators/GameGuruRepo/issues/2855

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for next EXP build by improving the AnglesFromMatrix function

**Comment by Kitakazi** [comment]
Reopened issue as this has started happening again. 

Usually rotating the object 1 time will produce no errors, but rotating multiple times will cause the entity to rotate to 181 instead of 180. Or if rotating 3 times it will rotate to a value of 271 instead of 270.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Seems you can enter 360 value to the Y axis gadget, should not be possible, the range is 0-359 and rounded, suspect this is the cause of the push from 180 to 181...more testing needed here.

**Comment by LeeBamberTGC** [comment]
@Kitakazi In the next EXP build the range for angles is now 0-359 rather than the redundant 0-360.  If you experience any other issues relating to object placement rotation, please do post here.
