### ISSUE TITLE
GG Max - EXP Build - Clones not using Navmesh / Collision ?

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4665]
After testing the Clone Entity again, i placed 12 flags, all linked to created a path. I placed one enemy character, with a pistol, set to always active, linked to the path, and let it choose random flag.
I placed several stock building, Some with steps, some without steps.
i then placed a clone entity zone, and cloned 12 of the one placed character.

The cloning process worked fine. All 12 clones were walking to a random flag on the path.
All clones were attacking me when they see me.
The only problem i see now is the clones, DONT use the steps on the buildings, and walk underneath the building, as you can see in the screenshot.

The RED circle is the 1 placed character, The YELLOW circles are clones.

![Untitled](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/c93e3c78-3983-4d4e-bc47-38f5c7e4b0a4)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you send me a VERY SMALL level with stock objects and a step by step when I should do to see this, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC I was trying to reproduce this on a small new map, but i found that they did actually walk the steps and come inside the house this time.
But i was seeing several bugs with the clones.
Sometimes, some clones would spawn without guns, yet still try and shoot you without a good, even though other clones in same game spawned with guns.

Other issue i see is that some clones dont walk a path, and seem to get stuck walking about 10 yards forward, then instantly teleporting back to were they were, and walking the same 10 yards constantly.

Cloning is far to buggy at mo to even try and use.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
He is a very simple blank level showing the clones teleporting back after walking 10 yards or something.
https://www.icloud.com/iclouddrive/00fZsiysLgQ2lnfTzDlhMob4g#Clone_Test

I will try and get the building bug test working tomorrow on a small level.

**Comment by LeeBamberTGC** [comment]
@Tum1370 The issue with the characters walking a patrol of 10 yards then resetting was due to the spawned ones being spawned in areas with no nav mesh. I have updated for the next EXP build so patrol script does not attempt to walk if they have no nav mesh under them.

Do you have a small level stock example of your original post, that clones once created do not use a navmesh?

**Comment by Tum1370** [comment]
@LeeBamberTGC Here is a small level with the bug of the clones not walking the stairs on stock buildings.
You spawn invulnerable, About 10 clones will spawn at a distance of 3000, They are suppose to all be set to "Always Active". They are suppose to choose a random flag path as you will see looking at map.

I noticed on this demo that some of the clones that spawn further out, DO NOT MOVE.

When you TEST, Try and get a lot of attention, and run in to one of the 2 houses i have placed.
The ONLY one that uses the steps and flooring on these stock buildings is the original character, All the spawns run through the floor and ignore steps.

[Clone Test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11819704/Clone.Test.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Right off the bat your level is a good one for testing. When I saw some very still characters, I did a run, clone exit, run, clone, exit test 6 times and all the clones hang around and are not removed when you exit test level, this should be my first thing to solve :)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6743e523-8ee0-4e8d-a104-9b4055d840af)

I will post here when I have made progress.

**Comment by Tum1370** [comment]
@LeeBamberTGC Hi, Have you made any more progress on this bug ? I still see its labeled Fixed, but with my testing i still bugs with the clones.

**Comment by LeeBamberTGC** [comment]
@Tum1370 No further progress on this as yet. Some nav mesh work but not one specifically tackling the above latest results. Do you mind creating a new FPM level with stock media with the latest EXP build and attach here. I can then quickly reproduce your latest findings and see if we can fix this sooner rather than later.
