### ISSUE TITLE
GameGuru Max - Character Creator Shirt Crash Bug

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#4670]
There are two shirts, one for adult male and one for adult female, that when selected will cause Max to crash. The video below demonstrates that other shirts can be selected with no issue, but as soon as these particular shirts are selected the software crashes. I was able to replicate this issue on two separate machines and verify that another user experienced the exact same issue.

https://youtu.be/ekXt_PuXoek

**Comment by MonkeyFrogStudio** [comment]
Happens for me, too.

**Comment by Blood-Moon-Interactive** [comment]
I retested this tonight since it'd been a long while and the issue no longer occurs. So it must've been fixed but never closed.
