### ISSUE TITLE
GG Max - EXP - Adding New Screen to Storyboard breaks certain mechanics 

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4674]
I just tried adding a NEW SCREEN to a Test Level.
I added a button (Named Select Level) on the TITLE SCREEN to go to this NEW SCREEN
On the NEW SCREEN i added 3 buttons, all going to a DIFFERENT LEVEL.
I Connected all the Levels and selected the ACTION for each button to go to that level.

Then TESTED GAME using STANALONE TEST ALL LEVELS to see how this worked.
It loaded the correct level, but the game had errors.
One Level TELEPORT didnt work, which worked fine normally.
Pressing ESCAPE brought up the PAUSED MENU from a totally different PROJECT.

I Have another github post open about bugs when adding NEW LOADING SCREENS.

Clearly the storyboard and adding NEW SCREENS, and NEW LOADING SCREENS needs fixing, as both of them create several errors in the game.

**Comment by casigus** [comment]
yeah ive had issues with the screens too! added a loading screen, and in the standalone none of the loading screens work apart from the first one.

**Comment by LeeBamberTGC** [comment]
@Tum1370 I am getting success with my extra TITLE SCREEN button to load level 2 and 3 of my test project:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4d8a9285-ab1f-41eb-af30-5a4236d66877)

Can you send me your game project and levels using stock media and let me know what to look out for as incorrectly performing levels, thanks!11111111111111111111111111111

**Comment by LeeBamberTGC** [comment]
@Tum1370 Also in case of a screen becoming corrupted internally, I have added to the new EXP build a Restore Screen which will fix any internal errors of a screen and restore it to stock.

**Comment by Tum1370** [comment]
@LeeBamberTGC After testing adding new screens, and having the option from title screen to select different starting levels, i can now confirm that this seems to be working properly and fixed. I dont seem to be able to reproduce this bug that i have reported so I will now close this issue.
Thanks for the fix :)
