### ISSUE TITLE
Bee and Wasp . Bugged. Sorry!!

### ISSUE THREAD

**Issue by Grogadog** [TheGameCreators/GameGuruRepo#4675]
The default sound is wrong. Okay no big deal, you can change it. But, Whatever the sound it continues after they are killed, like forever, so annoying !!

**Comment by davetgc** [comment]
Which assets are these and for which engine, Classic or MAX?

**Comment by Grogadog** [comment]
P.S. it is the same with any sound applied!
S.

**Comment by Grogadog** [comment]
Converted file to mono, still same result.
Tried to amend the lua but failed after many different approaches !! please
help with tip to detect death!

"C:\Program Files (x86)\Steam\steamapps\common\GameGuru
MAX\Files\audiobank\misc\knockingonwindow.wav" sound corrupt I think.
Steve

**Comment by AmenMoses** [comment]
@Line 208 just after the GravityOn(e) call add a line:
StopSound( e, 0 )

**Comment by Grogadog** [comment]
Thanks,  I tried this earlier, in various places within that if-then-end
before my email. and it didn't work !!! Lol now it does. Maybe I didnt save
before trying, Hey Ho!.
It is still audible a long way away.
Thanks
Steve

**Comment by AmenMoses** [comment]
Yep, can confirm that 3d sound positioning is no longer working in MAX.

**Comment by Grogadog** [comment]
Thanks, But the issue is the fact with this asset's sound, it can be heard
everywhere at the same volume!
Cheers Steve
Another slight bug.
If you craft (say a healing pot), with two plants (or whatever). all is
okay if you '*Use'* the resulting 'healing pot', but drop it and it is lost
forever.
Cheers

**Comment by Grogadog** [comment]
Hi Having re-read your comment, distance makes a difference with other
objects giving sound! going less the further away you are
Cheers Steve,
PS I know they really are nothing much to worry about!

**Comment by Necrym59** [comment]
fixed
