### ISSUE TITLE
alpha clipping bug

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4677]
trying to build a barrier around this area so people dont go walking off into the sea.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/cab7c3ab-6afd-4c2a-81fb-3d2433ac257a)

so was using these walls to build it and then setting the alpha to zero. When i do, it also sets all the other walls *which ive not selected* invisible too.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/a74ec0da-32e3-434e-8f4d-2dfb4b17645d)

**Comment by synchromesh62** [comment]
would these help to do a better job 
https://gamecreator.store/product/36495

**Comment by casigus** [comment]
Absolutely yeah! but this is still a bug! a random one at that which goes with my theory max has a memory leak/memory issue! :)

**Comment by synchromesh62** [comment]
Very weird .. 
I tried this myself and seemed to work as it should for me ?


https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/078e5f82-86d5-4981-beba-60739c886f3e

**Comment by davetgc** [comment]
I'm assigning this as a bug, but if anyone can find a way of 100% replicating this it would really help.

**Comment by LeeBamberTGC** [comment]
@casigus Also cannot reproduce, I dropped in three Aztec walls, selected the middle one, set the alpha clipping to zero, only that wall stopped rendering:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6121fb4d-764d-4517-88e5-b31f523861d7)
and in the game:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8366be1c-08ca-417b-b59a-b87149494832)

Setting to LOW in case someone can reproduce using stock assets and simple FPM level.

**Comment by casigus** [comment]
yeah ive not seen this bug since actually!
