### ISSUE TITLE
Standalone Produces Numerous Bugs 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4679]
I saved a Standalone of 2 levels earlier. I tested this small Standalone with the **"Standalone Test All Levels"** options from the Game Storyboard. Everything worked fine. So I saved the Standalone. 

Upon launching my .exe Standalone version I encountered large amounts of bugs that were not present in the **"Standalone Test All Levels."** 

Here is a strange one. Entities becoming solid colors. Here is what my wall should look like. 
![20230529223656_1](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/07cdd988-c498-4ecd-8bd7-618889f61fe8)

And this is what it looks like in my Standalone. 
<img width="1920" alt="Desktop Screenshot 2023 05 29 - 23 04 09 45" src="https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/174b5fdc-a32f-4ee7-9038-e37756e3954e">

Multiple entities have this bug. 
<img width="1920" alt="Desktop Screenshot 2023 05 29 - 23 05 48 99" src="https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/4b294b0d-118f-44a8-b383-82dc7c05a593">
<img width="1920" alt="Desktop Screenshot 2023 05 29 - 23 07 25 63" src="https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/40f0db68-ca65-46f9-83ce-1e4aef9db662">
<img width="1920" alt="Desktop Screenshot 2023 05 29 - 23 06 34 27" src="https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/abce7f29-b470-42ca-9d33-c6d1983c95f6">

Besides that bug, I experienced large amounts of the same ole standalone bugs. 
Tons of entities were not copied over. 
Most (but not all) entities using an _emissive map did not have the emissive map copied over. 
Additionally, on level 1 I had about 10 image in zone scripts throughout the level, only about 5 of them actually worked.  
Trigger Zones using the the Logic Connectors did not activate all objects when used, maybe on half of them. 
Any script that uses ActivateIfUsed(e) did not work at all. 
3D audio seems to play from random locations. 
Entities missing collision.
Entities that had "Double Sided" checked in under Custom Materials were no longer Double Sided. 
Some entities that had a new _color texture chosen under Custom Materials had reverted back to default, non custom texture. 

Once again, these bugs were not present in the **"Standalone Test All Levels."** 
I made a Standalone of each level individually and did not encounter the above bugs. Only when they were created in a multi-level Standalone do they appear.

**Comment by LeeBamberTGC** [comment]
@Kitakazi The way the bug is described, it sounds like it takes a combo of custom content and multiple levels in a standalone to recreate.   Would you be able to zip up your entire game project and all custom media so I can load and reproduce the standalone export issues?  I would ask or smaller stock media levels so I can see a simple recreation but I am guessing it all works fine when you deliberately try to recreate small parts of the issues you are seeing?

**Comment by Kitakazi** [comment]
Ok I was able to reproduce the entities changing to solid colors with some small FPMs. 
If I build just 1 single level, the bug does not happen and entities work and look as intended. But with 2 or more levels saved it will happen on all levels after level 1. 

https://drive.google.com/file/d/177rBitfsHIRtmZByZvYnJAof5JShonmX/view?usp=sharing
This zip file contains 2 small FPMs with some custom media. Level 1 is just filler, since this bug doesn't happen on level 1, you can just walk to the trigger zone which is inside the 5 Green Barrels.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/395c33b5-e85f-46df-9092-83a1b3bb72d8)


Level 2 loads you will see that entities with emissive maps have turned solid colors. 

Here is what they should look like.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/f1e60842-469e-4011-ba06-ed75341f34a2)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/960b3d23-2bff-4377-8fef-3fb284ccff3b)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/e9eacc05-14b7-4426-9d38-e023072908b7)

But some will actually be a solid color. I believe the emissive maps did not copy over for these entities. Some emissive maps are copied over while others are not. And only if multiple levels are saved during standalone. 

As for the other bugs I have listed such as trigger zones and image zones failing to work. I cannot reproduce these on a smaller FPM I will test more but may have to send you a download with my actual levels im working on.

**Comment by Kitakazi** [comment]
yea it wasn't copied over

**Comment by LeeBamberTGC** [comment]
@Kitakazi In the next EXP build _emissive and other missing texture support files will be copied over for all levels.  I tested with a quick model, but you can report here if it works with your original two-level project.
