### ISSUE TITLE
How to use .FPP properly

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#468]
Ok so was testing this feature, and I had some help from Bolt-Action Gaming.

He looked up the format in the code.

Map file and .Fpp file need to have the same name.  - ok
https://puu.sh/Cjc0Z/91204b04be.png
The add tag is this:
[standalone add files] - ok
The remove tag is this:
[standalone delete files] - ok

Syntax to write a path name:
\entitybank\subfolder\filename.ext - OK will write the folder, but will not fill with contents.

https://puu.sh/Cjc4k/bc1471e064.png
Note:
These are the extra files I was trying to add.
https://puu.sh/Cjc60/c2954b1233.png
 
I did not have these 2 objects placed in the map file, as was looking just to add files for testing.
Maybe that is part of the problem. All my standalones are built from a single folder when I create them and everything normally copies over. it is all custom media.

Map and fpp file

Can we get the proper way to use this?

[fpp_test_mapbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2687774/fpp_test_mapbank.zip)

Thank you.

**Comment by HierToo** [comment]
Ok,
your path in the fpp is wrong:
In your testmap it is:
\entitybank\subfolder\filename.ext
but it should be:
entitybank\subfolder\filename.ext

With the \ in front of entity bank, you go outside the files folder and then there are no files.
Look in the commit info for more information:
[https://github.com/TheGameCreators/GameGuruRepo/commit/c7c492597c362bf3e33420533c9b85c181ffb096](url)
Please close this issue, if it is fixed :)

**Comment by Pirate-Myke** [comment]
That procedure works,
Thank you.
