### ISSUE TITLE
Teleport Script Changes the Camera's FOV When Used

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4680]
Teleporting with the Teleport Behavior will change the camera FOV. 

Place a Zone and assigned Teleport Behavior. Select the box "Teleportation Effect"
Connect zone with the connector to an object. 
Enter the zone and now your camera has a reduced FOV seems to always set the FOV to 41. 

Also setting the mode to "single-use" does nothing as the player can continuously teleport by walking into the zone again.  

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/92ec25a3-8f01-4d78-8d65-db014906c930)

before I enter the teleport zone.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/3fed2b29-1e82-45c2-83d0-6de46709b52d)

after I am teleported. 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/146e891e-1e5b-4a12-9497-c6e8ff2b1c00)

**Comment by Necrym59** [comment]
Fixed

**Comment by Kitakazi** [comment]
Thank you!
