### ISSUE TITLE
Video play White Rectangle.

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#4682]
When using the Video trigger behaviour - A white rectangle appears for a very short period before the Video plays. I've tried various formats .Avi .mov and Mpeg. All with the same result.
AMD Video card RX580.
I think it maybe a bug.

**Comment by synchromesh62** [comment]
I can confirm this one. 
Noticed it myself when adding a video earlier.

**Comment by MartinCranshaw** [comment]
Video still showing White square.

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw I can reproduce this one, thanks!

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw Fixed for next EXP build.

**Comment by MartinCranshaw** [comment]
Brilliant well done Lee. It's not too bad if the Video involves Lightning
LOL.

*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by MartinCranshaw** [comment]
Fixed. Thank you.
