### ISSUE TITLE
Documentation required for different FOV Values

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#4684]
It seems that 
GetGamePlayerStateCameraFov() and g_PlayerFOV  ..report two different values
is there a specific reason for this or is it a bug, im not sure as to the reason for why we would have two different readings.

**Comment by LeeBamberTGC** [comment]
@Necrym59 The "g_PlayerFOV" is an internal FOV calculated and an adjustment to match for Classic used to work. The original value, and one controlled from the level editor too is controlled with SetGamePlayerStateCameraFov and GetGamePlayerStateCameraFov

**Comment by Necrym59** [comment]
Thanks Lee, should I close this one down or leave it open

**Comment by LeeBamberTGC** [comment]
We can leave it open until the documentation is released :)
