### ISSUE TITLE
MAX - SkyBox - skyspec sun setting issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#4685]
We had this many moons ago but tis back again in current EXP

If you add a new custom skybox the skypsect settings for position of sun are not used when you start the level
- you have to start the level
- tab tab and select the skybox
- then it will use the settings
- 
Matters not if you save the level after setting it right 
- an old bug returned

Note the issue is not seen with existing skyboxes or custom skys added some time ago
- it only happens with new ones added

Thanks for looking into it :)

**Comment by LeeBamberTGC** [comment]
@OldFlak I could not reproduce. I copied the sunset sky folder, renamed to "lee" including the files within, changed the skyspec to move the sun a little, and the sun position was moved correctly:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c993f381-d2ad-43be-a86f-ecb8bab2815a)

**Comment by OldFlak** [comment]
Hi Lee - I can still reproduce this issue.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/752f04e6-ffb9-41c7-8a15-3c2b54bf7556)

Here be a video
https://youtu.be/EeBP0dkhWXo

Have also emailed a link to the map and skybox to test - thanks for looking into it :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Quite right, and thanks for the explanation video. The sun could be seen it is correct place, but this was not saved with the level visuals data, sorted for the next EXP build.

**Comment by OldFlak** [comment]
Thanks Lee, perfect now saves the data - awesome!
