### ISSUE TITLE
Add more features to create rpg games!

### ISSUE THREAD

**Issue by xmailgame** [TheGameCreators/GameGuruRepo#4688]
**Add more features to create rpg games!**

**Comment by Lemuripest93** [comment]
Feature requests like these are not much help unless you expand on what you want, if you could give some examples of different features that have not already been asked for, that would really help the devs :)

**Comment by fearlesswee** [comment]
Please be very specific and deliberate with your feature requests, and to suggest one new thing per-request; this is so vague and unhelpful it could mean just about anything.

For future reference it helps to keep these points in mind when making a feature request:
- A specific, clear description of the new feature/mechanic/system you are suggesting
- A description of how the new feature/mechanic/system might work from an end-user standpoint (how might you set it up, how you might expect it to work from a technical standpoint, etc.)
- A couple of use-cases to help TGC and others understand why the new feature/mechanic/system might be important. (How might you make use of this feature in your game? Why do you need/want it?)
- Optional; but maybe some examples from other released games that demonstrate the new feature/mechanic/system in action, so TGC can get a better understanding of how such a thing might work in a fully developed game.

**Comment by davetgc** [comment]
As mentioned, we welcome suggestions, but you'll need to explain more.
