### ISSUE TITLE
Dynamic Entities Not Visible Behind Semi-Transparent Dynamic Entities

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#469]
If you have a semi-transparent entity, you will not be able to see dynamic entities behind it. Only static entities.

If its helpful to know, I have an entity with an alpha channel its its DNS textures and am using transparency = 4 in the FPE.

**Comment by Teabone3** [comment]
I think this is related to "if the player can see an entity than don't draw it on screen."

**Comment by synchromesh62** [comment]
@Teabone3 
Any chance you could supply a video of this for the March Bug fix ..

**Comment by LeeBamberTGC** [comment]
Sounds like an incorrectly set up custom entity. I created a simple level with transparent windows in the foreground and transparent plants and building in the background, and the rendering order was fine:

![image](https://user-images.githubusercontent.com/35840583/77497115-751eb680-6e44-11ea-9314-5746b7b848fb.png)

You may reopen this if you can provide a custom entity and FPM that shows a bug in the transparency system.

**Comment by sfkylcnky** [comment]
I used transparency=8 in fpe to solve the same issue I was having. Hope it will help you as well
