### ISSUE TITLE
Black screen when launching GGMax, then crash

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#4693]
Hello! Since around March, I am getting a black screen for a few seconds when launching Max before it closes itself (only the loading screen appears). I tried reverting back to a to the December release (I was in the exp build) and I still had the same issue, even though it used to work before in the same build. If I remember correctly, GGMax crashed while I was changing some the settings of a weapon, and since then I had the black screen problem. I also tried verifying files, re-installing Max completely, removing all assets that aren't in GGMax by default (I had GGClassic assets), and deleting the .fpm and .lst files of the level I was working on when the engine crashed. Any help? Thanks!

System Specs:
RTX 3060 Laptop
Ryzen 5600h
16GB of RAM

**Comment by davetgc** [comment]
This sounds like the old AMD big issue. It's possible files are missing for your card.

**Comment by waterdrinkingfox** [comment]
I have an nvidia though as I stated...

**Comment by davetgc** [comment]
Sorry, I misread.

**Comment by waterdrinkingfox** [comment]
I think I was tweaking with every value because they didn't seem to change anything sometimes. That or I was changing the damage and/or damage falloff values. Sorry I can't be more precise than that, it was a long time ago :/ However if it may be of any importance, I was changing the values directly within the editor.

**Comment by GraPhiX-Guru** [comment]
Hi can you check your Nvidia Control Panel and make sure MAX is set to your Nvidia card and not the discreet card (inbuilt),
last NVidia update on my laptop reset all my settings i had to set them back up.

**Comment by waterdrinkingfox** [comment]
Hello. Yes, MAX is already using my nvidia graphics card.

**Comment by LeeBamberTGC** [comment]
@waterdrinkingfox Can you send me the make and model of your gaming laptop that has the "RTX 3060 Ryzen 5600h", thanks!

**Comment by waterdrinkingfox** [comment]
Hello! It's the Lenovo Legion 5 2021.

**Comment by LeeBamberTGC** [comment]
@waterdrinkingfox The gaming laptop is well with spec, your hardware appears fine :)  I next suspect some corruption in the install, as the AMD issue did not crash, just show black.  If you get to the splash loading screen there is a chance your LOG file has been created. Can you find this file "Guru-MapEditor.log" in "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX" and attach here, thanks!

**Comment by waterdrinkingfox** [comment]
Here it is!

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/11805184/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@waterdrinkingfox Looks like MAX got all the way to the main loop without crashing, a good sign.  Can you delete this LOG file, then do a short screen recording and then run "steamapps\common\GameGuru MAX\GameGuruMAX.exe" (ensure your Steam Client is running and you are logged in when you do this), and send me the new LOG file and the video, I can then see exactly when (after the loop hits) where it crashes out, thanks!

**Comment by LeeBamberTGC** [comment]
@waterdrinkingfox I will close this as majoritally closed (not a word), and we can look at your specific LOG when you have time.
