### ISSUE TITLE
GGMAX - goindoors Trigger bug. 

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4694]
it seems that the goindoors and gooutdoors triggers to make the terrain disappear are not working as they should.

The function does trigger if you use the "activate object fields. So it is seeing the player enter and exit the zone if you use lights to see if the function is working. Just the terrain and water remain no matter if you go in or out of the zones or use external trigger zones to activate.

![goindoors](https://github.com/TheGameCreators/GameGuruRepo/assets/71521025/33f9bd08-7122-4027-b755-c57da65dd360)

**Comment by MartinCranshaw** [comment]
Same problem too. I notice that there is a Red cross on the Icon.

**Comment by synchromesh62** [comment]
I dont think this is a bubIm pretty sure the goindoors \ outdoors scripts are remnant's of the old terrain system and have never been usable in the new one

**Comment by synchromesh62** [comment]
dont think this is a bug
Im pretty sure the goindoors \ outdoors scripts are remnant's of the old terrain system and have never been usable in the new one
