### ISSUE TITLE
MAX - Outside Terrain Reflects On Interior Entities

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#4698]
Notice the reflection of color in tis screen shot. The room is fully enclosed, and all meshes are double-sided
The purple\pinkish color is coming from the outside terrain and or skybox
- the map is a flat (empty) map
- if you use the default square texture it is not noticeable due to its neutral colors
- 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/e0f0d1cd-ea20-45aa-97e4-59e4b4734972)

**Comment by LeeBamberTGC** [comment]
@OldFlak As soon as you add an Environment Probe inside the scene and expand the size to capture the walls, it will use that better env map than the default global env map that includes the sky

**Comment by OldFlak** [comment]
Hi Lee - thanks for the update.
Not seeing the issue in that level now (tad more fleshed out) so will consider it sorted.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/ee8cb0dc-e6d1-4503-9bae-98a0d1b082b4)

**Comment by LeeBamberTGC** [comment]
P.S. Looking AWESOME!
