### ISSUE TITLE
animations still not working.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4699]
built in blender. exported as  (.gltf) animated.

import into ggmax.

NO animations....

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/e0fc169f-4b16-4aef-8c86-4c494d6928ef)

animations work fine in 3d viewer, max doesn't pick them up.

I want to do cut scenes of the ship sinking in MAX so they match the game play, I can't do it because MAX isn't finding the animations.

**Comment by casigus** [comment]
model importing into MAX inverted....

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/bbe7a109-0a8c-4b25-b500-cee2e1a17157)


![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/d2c68313-3f73-413b-9ca5-2ccaa248ad8d)

**Comment by davetgc** [comment]
Is this the same bug reported as fixed here? #3626

**Comment by casigus** [comment]
oh yah! of course!!! yeah same bug!!
