### ISSUE TITLE
Scripts not copying over in Standalone using include

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#470]
I've found since the new monster update scripts that preciously worked fine are failing to copy over. Included files are not getting included it seems. This is a recurring issue for me, but I've been notified of this and in testing found that indeed it seems to be back :(

**Comment by Retrogamebloke** [comment]
The first is just in scriptbank, the second in the Dvader folder. I deliberately did this to test out the standalone's ability to sort through them properly with or without sub-folders. It will fail at this point, or did for me. Sorry not to state this above. Other scripts can still fail when all the scripts are in the dvader folder though.

I've tried one of my old store scripts plus a new one I have been working on, they both exhibit the same issue. It was brought to my attention by a customer. Each time the standalone fails to even load because of the missing scripts. Of course they can copy it manually, but that defeats the encoding and obviously that is not good.

The above scripts were just a test I did to show here. When I made a standalone using them the files were not copied over. I'll double check my version of GG, just in case but I think there is an issue here still. After all, I'm only chasing it because several (years old) scripts have apparently "stopped working" after selling many times over the years with no issues. First old script I tried showed the issue immediately :(

**Comment by Retrogamebloke** [comment]
Just made sure I have the latest version down (was working on PP before). The version you sent does work. Although it was not the same (scripts in different folders).
I've tried running my original from the same directory and it still fails to copy over :( There is no difference beyond the name of the script and the folder name :/ Obviously my Dvader directory has more stuff in from other scripts as well, but that shouldn't make any difference.
Bear in mind that I wrote this merely to demonstrate the issue I seem to now have with store scripts so I'm now even more concerned that something weird is amiss here.

**Comment by AmenMoses** [comment]
So the problem is:
1) GG has to see "Include(" in order to trigger the copying across of scripts, having a space between 'Include' and '(' breaks it.
2) GG does not further check included file for further "Include(" statements so the script must contain an "Include(" statement for and 'nested' "Includes(".

The code for this is in M-MapFile.cpp in function scanscriptfileandaddtocollection if anyone would like to change it to allow for more free-form scripting.

**Comment by Retrogamebloke** [comment]
That fixes it. Used to work fine with spaces down the line, but something has been updated since it seems (likely something to do with the encryption process at a guess). I've updated the known scripts with the issue.

**Comment by sfkylcnky** [comment]
#368

**Comment by plemsoft** [comment]
@Retrogamebloke Thanks for reporting this,

This has been fixed and are ready from the next update :)

Also support require and nested (include/require inside added include/require files).
