### ISSUE TITLE
Collectable settings crash GGMax

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#4700]
Hi there 

When I place a scroll and make it a collectable item, if I go to collectable settings GGMax just crashes. Has anyone else had this problem.

**Comment by Necrym59** [comment]
can you elaborate a bit, which scroll is it

**Comment by Tam51** [comment]
Hi Necrym59

When you set Scroll ( the one rolled up) or quest scroll to collectable and as soon as you click on collectable settings GGMax just closes down without any warning. I hope this helps in sorting out what the problem is.

**Comment by Necrym59** [comment]
@Tam51 
I dont seem to be having any problems with it and cant repeat you problem, perhaps somone else can see if its possible to repeat.
in the mean time do a file verify on your steam installation and see if any files redownload that may fix it.

**Comment by Tam51** [comment]
Hi  I needed to verify the files. After doing that I got it to work. Many thanks for helping

**Comment by Tam51** [comment]
Hi again 

GGMax has starting to the same thing as before. When you set Scroll ( the one rolled up) or quest scroll to collectable and as soon as you click on collectable settings GGMax just closes down without any warning. I have done a file verify twice now and even tried a re-install but the problem just keeps coming back. Can anyone shed any light on this matter

**Comment by Tam51** [comment]
Hi There

I have noticed that I can't make anything collectable now. When I go to collectable settings GGMax just closes down without any warning. I have tried a re-install of GGMax and a have done a file verify neither have worked. Can someone please shed some light on what's going on.

**Comment by Tam51** [comment]
Hi

I may have worked why it doesn't work. It doesn't work on a old level I was working on, so I now have to re-create that level from scratch. I shouldn't have to do this. I do hope this problem will be solved

**Comment by Necrym59** [comment]
You may not have to, try removing the .tsv files from the project folder and see if that fixes the problem

**Comment by Tam51** [comment]
Thanks for the advice I just tried that and I got it to work. Many Thanks Necrym59
