### ISSUE TITLE
melee characters just stand there and swings but won't chase 

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#4701]
I got around to messing with my game again and in the last level there's a character that chases you around with a knife trying to kill you. It worked before but after coming back all he does when he detects you is stand there and swing in place. He will no longer chase. Was there some kind of change to the script since I've been gone or is this a bug? I checked around to make sure there wasn't two melee scripts for different actions but that doesn't seem to be the case

**Comment by davetgc** [comment]
Can you please post an image of the character settings

**Comment by mike123yy** [comment]
I was trying pull up my character to give you a screen shot but an update went through and now I'm getting 2 errors and game guru keeps closing on me.  I'm not sure what's happening but let me try to get this figured out and I will post the settings.

<img width="1920" alt="error1" src="https://github.com/TheGameCreators/GameGuruRepo/assets/41445779/a23d2450-7888-4463-a106-01cd575ebe29">
<img width="1920" alt="error2" src="https://github.com/TheGameCreators/GameGuruRepo/assets/41445779/ac1d1c6a-e942-4419-a735-d9f4422288cc">

**Comment by mike123yy** [comment]
I turned off experimental build and it's working again.  Here's the screenshots of my settings
![settings1](https://github.com/TheGameCreators/GameGuruRepo/assets/41445779/e09535d2-1939-49a5-b2ae-acc4ebe59873)
![settings2](https://github.com/TheGameCreators/GameGuruRepo/assets/41445779/6cfd896c-bd7e-4743-80c2-a91dfbefe49d)
q

**Comment by mike123yy** [comment]
Any ideas?

**Comment by davetgc** [comment]
Are those rooms created with the Building Editor?

Is that a custom character or one created with the character creator?

I've tested the melee behaviors and the characters chase me, but I tested outside.

**Comment by mike123yy** [comment]
yeah, they are built with the building editor and the character was created with the character creator.  It was working before perfectly but after coming back to work on it some more sometime later it seems broken.  I did a test on a blank map just to make sure but it still doesn't work.  I tried to overwrite the melee script with a working one to see if that would help but it still glitch out.

**Comment by davetgc** [comment]
Thanks, that all helps.

**Comment by LeeBamberTGC** [comment]
@mike123yy A few things. First, ensure you are logged into the Steam client and have the next EXP build, those will help you sync to the latest scripts. The Melee Attack is a core script so the error related to missing files must be another one.  I have improved the Melee script since July so they can now patrol if a path is near, and will spot the player and attack. Ensure you give them a melee weapon as currently if you force a projectile weapon on them, they do strange things with it :)

**Comment by mike123yy** [comment]
> @mike123yy A few things. First, ensure you are logged into the Steam client and have the next EXP build, those will help you sync to the latest scripts. The Melee Attack is a core script so the error related to missing files must be another one. I have improved the Melee script since July so they can now patrol if a path is near, and will spot the player and attack. Ensure you give them a melee weapon as currently if you force a projectile weapon on them, they do strange things with it :)

I went ahead and updated Max to the latest experimental build and gave it another try. It still seems to be happening. It's using the Aztec dagger so it wouldn't be an issue with a projectile weapon.  I went ahead and made a quick video so you can look at the settings I'm using and watch what it's doing. Here's the link:
https://youtu.be/Sm1et4vMy9k
the character attacks like they're supposed to they just don't chase the character. Now I did just upgrade tons of stuff in my computer from Nvidia and Intel over to AMD. I know there have been some AMD issues, maybe this is a weird one caused by the hardware? Is probably a long shot but I figured I would mention it.

**Comment by LeeBamberTGC** [comment]
@mike123yy My guess is that the combo of indoors and character are causing it to freeze on the spot, perhaps no nav mesh. If the FPM level uses stock media, attach here and I can reproduce and check out the nav mesh. If custom, try making a new level with stock media and see if you can reproduce.  If all custom, email me the files I need and I will see what is happening. My email is lee@thegamecreators.com

**Comment by mike123yy** [comment]
I threw a character on a blank map with the melee animation for you to test. It still has the same reaction as it does with my built level So it should show what's going on. I would assume it was something to do with my level too but it did work before and it happens on a map with nothing but the character so I don't know What could be the problem. Anyway, I'll stop rambling :-) here's the attachment that:
https://drive.google.com/file/d/1vjfo7Y5wUpSzTMRvGssCYBJOfkLIKQ7Y/view?usp=sharing

**Comment by LeeBamberTGC** [comment]
@mike123yy Can you also provide a short video of what you see. I loaded and ran your level and the shappy ran towards me and started stabbing away, no issues here in next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/27a5693e-ef16-4ce4-9617-592f4d7d52b5)

**Comment by mike123yy** [comment]
No problem.  Here's what's happening on the blank map on my end :
https://youtu.be/XPGBEvk6bzs

**Comment by LeeBamberTGC** [comment]
@mike123yy Yep, script definately messed up :)  Make sure your writables area is clear of anything in scriptbank, and then use the attached latest Melee Combat script files from my latest build.
[melee_attack2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12371863/melee_attack2.zip)
Place them in "Max\Files\scriptbank\people" and select this specifically, then when you test game, use AI Management to show the nav mesh so we can make sure the character has one to move on:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/eedca495-63bf-45da-aae3-ddc4cf085751)

**Comment by mike123yy** [comment]
Yeah, that did it! They are back to chasing and stabbing again. Thanks for the help! I also checked my main game I was working on and the character navigates all the hallways perfectly again with no troubles.
