### ISSUE TITLE
Forest Biome "Cliffs" Use Wrong Texture

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4703]
I've been wondering why the "cliffs" in the forest biome looked wrong. They appear to be using the "wet riverbed gravel" texture instead of the "cliff rock" texture, resulting in very glossy mountains.

There doesn't appear to be a way to change the default textures, so this is pretty major but should be super simple to solve.

**Comment by davetgc** [comment]
Which biome are you using?

**Comment by TenebreGaming** [comment]
Forest biome

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Can you post a shot of what you see, and also post what you consider the righr texture MAX should be using, thanks!
