### ISSUE TITLE
Grass sound not playing and zombies dash bugs

### ISSUE THREAD

**Issue by Nixilliscyte** [TheGameCreators/GameGuruRepo#4704]
Hi there, just to report those 2 bugs that i came across today.

1st :
When creating the level with the generated terrain, let's say i use "forest" it generates everything for me the textures, the plants the trees, until now everything's running good but when i pass to the editor after validating/naming my terrain, when i test the game, the player makes no steps sound, comparing to if a do my level on my own (using brush with a empty terrain) and using the same grass texture, now, in the test, the player's makes steps sounds.

2nd :
When apply a dash animation to a zombi and click the "run the game button" to test, the zombie dash in a loop, it run like 4 steps forward then disappear then reappear at his initial place, dash again 4 steps, disappear and loop indefinetely.

Thanks ! keep up the good work !

**Comment by davetgc** [comment]
Hi, are you using the release version or the experimental build?

**Comment by Nixilliscyte** [comment]
Hi, i'm using the the release version, but it is ok, it's because i didn't hear the footsteps on grass (rock textures and other textures is ok), because it was hidden by the forest ambience sound, and it is barely audible with an headset but not directly with my laptop. So i can say it's solved, but a setting to ajust sounds volume in game, would be appreciated.

For the zombie dash bug, sometimes it happen sometimes not, i noticed that it happen frequently when the zombie is not far from a obstacle that is on his way. I also noticed this bug in the demo games proposed with the engine.

Thanks for the reply, overall Gameguru Max is good, and hope that with updates, it will be perfect.

Best Regards.
________________________________
De : davetgc ***@***.***>
Envoyé : mardi 13 juin 2023 09:38
À : TheGameCreators/GameGuruRepo ***@***.***>
Cc : Nixilliscyte ***@***.***>; Author ***@***.***>
Objet : Re: [TheGameCreators/GameGuruRepo] Grass sound not playing and zombies dash bugs (Issue #4704)


Hi, are you using the release version or the experimental build?
