### ISSUE TITLE
Zombies Stuttereing with player movement 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4705]
For Me Zombies stutter when player moves towards or away
Mostly with the Arms stretched out animation.
could be just me ?
any others.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/0c0ecfed-988a-4a1e-a304-9e543ee199cf

**Comment by DBird-1994** [comment]
@synchromesh62 I posted an almost identical video on discord on May 13 asking about this, but no one else at the time would confirm it was happening to them.     So yes, it is happening to me also.   The melee characters from the aztec dlc also do this but not quite as noticeable.

**Comment by synchromesh62** [comment]
For me its only been since the last couple of updates.

**Comment by davetgc** [comment]
This also appears to be affecting the characters using the Character Attack behaviour. Melee behavior seems fine.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 This highly resembles the anim reset on Zombies when the player shifts position to change the approach angle of the character. Rather than rotate alone, the AI resets a fresh walk animation during the transition, but when arms are outstretched it looks a little daft.  Have a few ideas :)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Adjusted zombie logic so it only resets its thought beyond 400 units. If the player is closer, the jerk will not happen, just a smooth rotation to its new location of the meal :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0240bf29-614a-4ccd-8988-4423586ca5b5)

**Comment by synchromesh62** [comment]
Thanks Lee i will check it out ..

**Comment by synchromesh62** [comment]
Ok Looks like the issue is fixed :)
Thanks Lee. Closing this one.
