### ISSUE TITLE
Animals in the Max Collection should make sounds

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4706]
There are sound files for the animals, but it appears that none of them actually make any sound. The mammal_generic.lua script does have one spot where sound is supposed to trigger, but I've not heard any. the bird.lua script has no mention of sound, nor does flying_insect.lua or fish.lua. The fpe files also don't have soundbanks specified.

**Comment by Necrym59** [comment]
Sound is not mono which is why they are heard all the time and not local to the insects.
[bees_and_wasps.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11832096/bees_and_wasps.zip)

**Comment by LeeBamberTGC** [comment]
@Necrym59 Where did these sound effects come from?  Are you the owner or can confirm they are license free, as I can add them to the audiobank misc testsounds folder, and I am assuming they are MONO so they can be used in 3D sound.

**Comment by Necrym59** [comment]
The ones in the zip above are mine so use feel free to use then as required

**Comment by LeeBamberTGC** [comment]
@Necrym59 Excellent, I will add to the next EXP Build :)
