### ISSUE TITLE
Saved map: terrain default height changed, leaving all entities under the terrain.

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#4709]
1) Made a flat map in the terrain generator
2) Started adding assets. 
3) Wanted to put some sand under a zone to make it stand out. Accidentally selected the terrain sculpting tools and put a small mound where the zone is.
4) Used the level tool to return the terrain to a uniform height, then painted a small patch of sand where the zone was. 
![Bob_Jane_01](https://github.com/TheGameCreators/GameGuruRepo/assets/60984223/a0140f9a-718e-4893-b86b-308779986515)
5) Saved level, quit MAX.
6) Re-opened MAX, loaded level. Now, all my entities are beneath the map and my zone is at the bottom of a deep hole. 
![hole](https://github.com/TheGameCreators/GameGuruRepo/assets/60984223/67e44561-eec9-4476-9125-6b495b333a23)
7) I can use the level tool to raise the height of the zone, but my entities remain permanently trapped under the map.

**Comment by LeeBamberTGC** [comment]
@AvengingEagle In next EXP build I tried following your steps, but when reoaded the level it looked fine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e75a9354-4b87-472f-88fe-33a1c42708a9)

When you said you created a flat map and added some entities, the EMPTY LEVEL produces a grey tile floor not grass, so I suspect I went wrong early on. Perhaps a short video so I can follow along exactly. I did fix an issue recently related to large holes being carved into the terrain, so might be worth testing the next EXP build as it might go away.
