### ISSUE TITLE
Black Screen in Game Demos 

### ISSUE THREAD

**Issue by elchejov** [TheGameCreators/GameGuruRepo#4711]
I installed well the trial version to test it. I load some demo game and I can see well the menu and the game HUD, even hear some sound, but the screen is always black. I have a Ryzen 6800U with IGPU 680M. I can play AAA games so it should be powerful enough to run gameguru. I read about the radeon bug but I thought it was already fixed. Any help?

Many thanks

**Comment by davetgc** [comment]
Hi, this does sound like another card affected by the AMD issue. Thanks for the report.

**Comment by LeeBamberTGC** [comment]
@elchejov Widenned the support for this fix. Also reported here: https://github.com/TheGameCreators/GameGuruRepo/issues/4789

**Comment by LeeBamberTGC** [comment]
Properly fixed now for next EXP build - was RSSetScissorRects and a recent AMD driver update!
