### ISSUE TITLE
GameGuru Max Runtime Error: 8003

### ISSUE THREAD

**Issue by DarthPickles666** [TheGameCreators/GameGuruRepo#4713]
Hi there, 

So I'm currently running the experimental build of GG Max. I have just updated after not being on my PC since Thursday and I am now receiving the following errors. I am unsure as to why this is happening, however if I revert back to the 26.04.2023 build, GG Max works fine. 

Any suggestions on how to fix this would be appreciated. 

Thanks. 
![1](https://github.com/TheGameCreators/GameGuruRepo/assets/101579658/b2a6ba69-c539-49cf-a2ee-81931d4f8ea3)

![2](https://github.com/TheGameCreators/GameGuruRepo/assets/101579658/64992275-ae08-47ca-ad00-6a1ac544c02b)

***Edit: I have verified the integrity of the files several times.

**Comment by 3coms** [comment]
Updated a few seconds ago, and getting the same.

**Comment by Technodweeb** [comment]
I am having the same experieince.  
I am first getting an error message that says: 
Error: 22 Folder: '(looking in C: user\loret\Documents\GameGuruApps\GameGuruMax\Files\scriptbank\Community\6704278)

I click OK and then get Runtime Error: 8003 () and then GGMax shuts down. 
I verified files and nothing was missing. I tried this several times.. and rebooted several times.

I am running the experimental Version of GGMax my PC Specs are ;
Processor: AMD Ryzen 9 5900X 12-Core Processor  3.70 GHz
Graphics : Nvidia GeForce RTX 3080 10Gb G DDR6X
RAM: 64GB
OS: Windows 11 Home Edition

Thanks!

**Comment by sirlion87** [comment]
Same here. Worked well until today's update.

**Comment by 3coms** [comment]
This GGMax issue was fixed after the last update. At least for me, it does. Ty guys, nice work. :)

**Comment by LeeBamberTGC** [comment]
@DarthPickles666 Does the latest EXP build resolve your issue?  This error relates to ongoing work with the new Workshop content system. P.S. Thanks for helping test this one :)
