### ISSUE TITLE
GG Max Weapon Texture Bug When Aiming Down Sight

### ISSUE THREAD

**Issue by GatoBaguette** [TheGameCreators/GameGuruRepo#4714]
**Hey everyone, Hope you are doing great!**

Ever since GG Max went v1 i noticed a frustrating bug with certain weapons, namely those using a different system for aiming down a sight where the texture does not display and instead creates a "ghosting" effect, which happens when engine does not have anything to display, so it simply shows what player is looking at instead or reflects the world around.

Anyone else having this problem? The only similar case was with the AK but i fixed that myself by removing the "Surface" texture file from documents.

For this weapon however i tried everythng and it remains that way. This weapon is from BSP's modern pack and the Sniper Rifle is the only gun i know that has this issue do to its "Lens" not working. Same also happens with other specific weapons from BSP that use the true "Aiming Down Sight" function. Scopes simply go haywire displaying partially or straight out go invisible and do the ghosting as seen below on the two image examples.

Let me know if there is a way to fix it or if it's a hardcoded issue that will be sorted in next bug fix update.

Thank you!

BSP's SASR bug - <a href='https://postimg.cc/NytP60C5' target='_blank'><img src='https://i.postimg.cc/Pqvskpmz/SR-Texture-Bug.png' border='0' alt='SR-Texture-Bug'/></a>

BSP's PP-2000 Submachine Gun - <a href='https://postimg.cc/qNqs66Tk' target='_blank'><img src='https://i.postimg.cc/Nj7pVRCr/P-Texture-Bug.png' border='0' alt='P-Texture-Bug'/></a>

**Comment by davetgc** [comment]
Hi, this weapons isn't officially supported by TGC as it's a 3rd party asset. @GatoBaguette - You might need to contact the artist. However, can anyone else confirm this problem?
