### ISSUE TITLE
Mouse lag input delay

### ISSUE THREAD

**Issue by sniffe1** [TheGameCreators/GameGuruRepo#4715]
prehistory
read  #4386 

thanks for the feature, Mr. Bamber...or is it an easter egg :-)

by the way, I would never use WASD

thanks for the hint in the last stream

![20230615_004258](https://github.com/TheGameCreators/GameGuruRepo/assets/105791530/34b7f846-3599-4b3e-988a-738efc314c7f)

**Comment by Kitakazi** [comment]
The smooth camera feature when using the arrow keys is amazing in my opinion. If it needs to be changed could it there be option to re-enable it? I use it quite often for making videos. Seems like it would be useful for cutscenes as well.

**Comment by Kitakazi** [comment]
@sniffe1 
Hey I just saw this myself so not sure if you are aware, but you can switch off the Smooth Camera when using the arrow keys. 
In your 
setup.ini file change
smoothcamerakeys=1
to
smoothcamerakeys=0

then launch Max and the arrow keys will no longer cause the camera to be smooth

**Comment by sniffe1** [comment]
thanks to you, kita

I've been doing it for a long time...

i think it should be an option in the settings
