### ISSUE TITLE
Transparency render issue

### ISSUE THREAD

**Issue by Gtox2** [TheGameCreators/GameGuruRepo#4716]
Render order of semi-transparent objects changes depending on whether you're in front of or behind the object.
https://github.com/TheGameCreators/GameGuruRepo/assets/136801805/c271935a-9f6e-47c6-a74d-8f5b856c3b79

**Comment by LeeBamberTGC** [comment]
@Gtox2 Can you email me the offending objects and a small description how you wish them to render. Transparent objects are sorted back to front. An object cannot be both behind and in front :)  There are some flags that can be used such as double sided for the effect of a transparent object inside another transparent object. Once I have the files, I will check it out:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e8cacae2-6ffe-4f6c-a9ed-da752d766326)
