### ISSUE TITLE
[Experimental] Trigger zones can no longer be renamed.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4719]
The name for trigger zones is now locked, so you can't rename them. Renaming is vital when you have numerous zones, for example Hurt or Healing zones and need to find the correct ones from the detailed object list.

**Comment by TenebreGaming** [comment]
I've not had any issues renaming trigger zones on the Experimental builds.

**Comment by synchromesh62** [comment]
> The name for trigger zones is now locked, so you can't rename them. Renaming is vital when you have numerous zones, for example Hurt or Healing zones and need to find the correct ones from the detailed object list.

To be honest i can still name zones ?

**Comment by davetgc** [comment]
Hmm.. Odd one then, as they are locked for me.

**Comment by LeeBamberTGC** [comment]
@davetgc Is this also true of a fresh project and level when adding a trigger zone?

**Comment by davetgc** [comment]
@LeeBamberTGC - This seems to be working again in the new build, even with old levels, so I'm guessing something changed either with the latest build, or at my end :)
