### ISSUE TITLE
Collecting Medkit Emits Injured Sound

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#472]
When you collect the medkits in the Collectables folder, a sound of the player being hurt will emit.

I originally fixed this issue myself and put it on Github and it was added. But it seems to have reverted now with later versions? In my fix it included not exceeding the players max health when using medkit type recovery health. Which is different from health boosts.

File: health.lua

**Comment by GameGuruEvan** [comment]
These are the recently updated SciFi medical and tool items, yes?  Would you please be able to send me a short clip of the issue so I can see what is happening?  

Also if you send me your custom script for limiting the health to gameguruevangelist@gmail.com I can make sure it is updated correctly.

**Comment by Teabone3** [comment]
No longer have my original script as it got replaced when i updated Game Guru but what I had in it was similar to this:

` if PlayerDist < 80 and g_PlayerHealth > 0 and g_gameloop_StartHealth <  g_PlayerHealth then`

This would prevent the player health from going over the maximum. Despite the variable being called Start Health, its actually the maximum health which is a modifiable variable. Additionally Game Guru maximum health in the visible HUD , is just a graphic unfortunately. But it should technically be using g_gameloop_StartHealth so it reflects the actual maximum health rather than always "100".

**Comment by GameGuruEvan** [comment]
Located original 'commit' in Github that modified the health.lua script to limit health.  Suspect roll-out of subsequent versions or DLC Updates have overwritten change.  Currently looking into how to permanently re-introduce the modification.

**Comment by Teabone3** [comment]
Greatly appreciated Evan

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Medi kits playing correct samples for me so I assume GameGuru Evan deatlt with this as he stated ..
