### ISSUE TITLE
MAX - Runtime LUA Error - Cause no nil check for line in Global lua

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#4725]
Line 822 does not perform a nil check - this breaks existing scripts
- tis a simple fix to be sure, but a required one

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/0a1374e6-76d3-4ace-af10-41c68f48e8fe)

**Comment by SampeyFS** [comment]
Yesss

**Comment by OldFlak** [comment]
Fixed now - Thanks team 👍
