### ISSUE TITLE
MAX - Characters sometimes seem to wait in an inactive blind/deaf T-pose state until the player gets line-of-sight.

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#4727]
Ran through the canyon offense level to test another problem, and noticed this issue. Sometimes, it seems like characters will lie in wait in a T-pose without any AI logic running until the player stumbles upon them, which allows the player to see them standing there in a T-pose for a second or two, and grants a large window where they'll slowly react to the player's presence, equip/draw their weapon, and then try to engage, making them very unthreatening and easy to take down. This also means they're "deaf" to player-made sounds, like gunshots, which can harm stealth-centric levels as an unseen enemy that hasn't yet been "awakened" will not respond to the player making noise.

I think I recall Lee mentioning about adding some kind of hardcoded line-of-sight check for NPCs where they wait until the player can see them before they "activate" their underlying NPC code/physics, but in my opinion this should also have a (tweakable) distance check, so if you get within X units of them regardless of line-of-sight, their AI will always "kick on" so you can't walk around a corner and see them all T-posing in a circle, and start to sluggishly "boot up".

**Comment by synchromesh62** [comment]
Is that with Always Active ticked as well ?

**Comment by fearlesswee** [comment]
> Is that with Always Active ticked as well ?

I haven't checked that, but I can say off the bat this shouldn't be considered the solution, as for performance reasons you don't want to have each and every NPC in the world active all at once. You can use zones and spawning as a sort of workaround, but it also has limitations; like only really being suited for a linear style game (as with open-ended or even full open-world level design you may walk into an enemy encounter and decided to back out, so you'd want them to go "back to sleep" once you get far enough), and being more and more tedious to set up the more enemy encounters you have.

There's definitely some other optimizations TGC can do to NPCs to help reduce their overhead without needing to have such a harsh "line of sight awakening" system; such as #3674 and #3675, both of which are extremely common in many modern games.

**Comment by davetgc** [comment]
What might be needed is a burst of physics on launch to set NPC's to idle stance when the level starts.

**Comment by fearlesswee** [comment]
> What might be needed is a burst of physics on launch to set NPC's to idle stance when the level starts.

This would presumably just fix the silly T-pose animation, but they'd still slowly "boot up" and would be deaf to player-made sounds until the player gazes upon them first. Unless I'm misunderstanding what you're proposing, which is certainly possible lol

**Comment by LeeBamberTGC** [comment]
@fearlesswee You can set the characters to always active and give them a path to follow, and they should do so, stiring them from their idle posture the moment the level starts. It s a performance hit for your level, but carefully used is fine.

**Comment by Kitakazi** [comment]
I think this is related but I have this issue as well. It doesn't happen on blank maps. But on my level I'm working on there is alot of entities and around 10 AI. None of them are spawned at the start. When they spawn in, even if set to always active, they will not begin patrolling until the player can see them.

**Comment by LeeBamberTGC** [comment]
@fearlesswee In next EXP build, when ALWAYS ACTIVE set to YES the dormancy system is disabled so characters aware from start of level

**Comment by fearlesswee** [comment]
Went to canyon offensive demo level (my sort of testbed level now lol) and played through it with the NPCs in their default configuration to find the NPCs that were most obviously T-posing and blind/deaf, and then set them to "always active" to gauge the improvements on a second run-through. Found they were a lot more responsive, and noticeably not T-posing when rounding the corner quickly. 

I do think that there should probably be a more clever solution to automatically "awaken" dormant NPCs regardless of always-active setting (perhaps an additional range-based check that trumps the line-of-sight check), but that borders more on a feature request rather than a bugfix. Closing as fixed.
