### ISSUE TITLE
conflict with new water features and transparency statement in fpe files

### ISSUE THREAD

**Issue by m2design** [TheGameCreators/GameGuruRepo#473]
I have shack models which include semi transparent glass for windows. To achieve this I require "transparency =2" to be included in the models fpe file. The models with windows work as designed in all
instances and locations, except when model is placed in the water, any portions of the model below the surface no longer visible but the windows still work. Changing the fpe statement to equal 1 or zero the portions below the water become visible as one would expect, but the transparent glass windows no longer work as intended. I believe the new water system has problem with some fpe transparency commands.
Trust me it's not the windows. Take any model's fpe and add a transparency command above 1 and the problem is apparent when model is placed in the water..

**Comment by m2design** [comment]
![desktop screenshot 2018 12 29 - 09 26 15 73](https://user-images.githubusercontent.com/33361413/50542533-75ae9b80-0b74-11e9-8a40-1f36b56ee0af.png)
![desktop screenshot 2018 12 29 - 09 32 03 77](https://user-images.githubusercontent.com/33361413/50542534-80693080-0b74-11e9-9b32-20b030cc974f.png)

**Comment by synchromesh62** [comment]
Most transparencies I see are set to 5 or 6 
Have you tried these settings ?

**Comment by m2design** [comment]
I have tried all transparency settings available. None of these Allow the model areas below the waterline to show up. transparency =1 solves the below water problem but then the window transparency no longer works.

**Comment by plemsoft** [comment]
@m2design Thanks for reporting this,

This has been fixed and are ready from the next update :)

**Comment by plemsoft** [comment]
Fix was removed as it generated another problems , so this is still open.

**Comment by plemsoft** [comment]
Added: Transparency = 8 option to fpe, let me know if this fix your issue , thanks :)

**Comment by m2design** [comment]
Preben, plemsoft
The transparency=8 in the fpe file solves al my problems, thanks

**Comment by m2design** [comment]
![Desktop Screenshot 2019 07 11 - 03 57 24 96](https://user-images.githubusercontent.com/33361413/61047448-5d75cf80-a394-11e9-931f-bd2ab34b2161.png)

![Desktop Screenshot 2019 07 11 - 03 56 52 30](https://user-images.githubusercontent.com/33361413/61047494-7c746180-a394-11e9-8b29-30c50b072010.png)

**Comment by m2design** [comment]
Transparency = 8 solves all of my problems

Fred
________________________________
