### ISSUE TITLE
Seggestions of new features

### ISSUE THREAD

**Issue by saccoforino** [TheGameCreators/GameGuruRepo#4730]
Hello everyone, especially developers. Congratulations on the work you are doing.
I wrote to ask some questions and clarifications and I take inspiration from the answers to propose some useful implementations:
1) a shortcut for a quick foreground focus of the object selected in the object list or of the player;
2) provide for the management of objects in layers or folders that can be made visible or hidden, blocked from selection, etc., for a much more orderly and easier management of game design;
3) a button to delete user assets or entire projects from the UI, without having to manually delete them from Windows...;
4) implementation of advanced Decals intended as a projection of images on 3D objects and not as simple planes approached to the surface. For example a bloodstain on an undulating terrain in this way would be possible and realistic;
5) the possibility of animating the shader emission of a material so as to be able to vary over time in intensity and color (example: a flashing luminous surface or with a variable colour).

**Comment by davetgc** [comment]
Hi, could you please add these as separate suggestions. It's easier for the dev team to handle enhancements as single threads rather than group requests. Thanks.

**Comment by saccoforino** [comment]
Done! Thanx.  Arch. Andrea Coppola Da: davetgcInviato: venerdì 23 giugno 2023 13:40A: TheGameCreators/GameGuruRepoCc: saccoforino; AuthorOggetto: Re: [TheGameCreators/GameGuruRepo] Seggestions of new features (Issue #4730) Hi, could you please add these as separate suggestions. It's easier for the dev team to handle enhancements as single threads rather than group requests. Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
