### ISSUE TITLE
Advanced decals

### ISSUE THREAD

**Issue by saccoforino** [TheGameCreators/GameGuruRepo#4734]
I suggest the implementation of advanced Decals intended as a projection of images on 3D objects and not as simple planes approached to the surface. For example a bloodstain on an undulating terrain in this way would be possible and realistic.

**Comment by MonkeyFrogStudio** [comment]
Already suggested here:

https://github.com/TheGameCreators/GameGuruRepo/issues/4620

**Comment by davetgc** [comment]
@MonkeyFrogStudio - Correct, I forgot that the reason I knew it was possible, was because you'd pointed it out!

Closed in favour of #4620
