### ISSUE TITLE
Standalones crashing since last update.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4737]
As the title states 
Standalones crashing since last update.
I tried a few of my projects with the same result. Starts to load then this.
I can only exit using ctrl+alt+del

![SA](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/73ed2495-23d2-4fb1-b8bd-5078eba37517)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Easily reproduced, thanks!  Will let you know when the fix is up:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/642b6836-bc6a-4ffb-bfdd-0d315efe99db)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed in new EXP build :)  Feel free to close this if it works for you.

**Comment by synchromesh62** [comment]
Confirmed working :)
Thanks Lee ..
