### ISSUE TITLE
Live updates from Necrym59 only showing after verify.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4738]
Live updates from Necrym59 ( scripts ) were instant.
After a lot of trying stuff with Necrym59 it appears any instant updates to behaviours now will only show up after verifying Max.
Not sure if its a bug or changed deliberatly to be that way ?

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Are you actively logged into Steam client when you launch MAX or running directly from Windows Explorer?  The sequence is that workshop stuff only kicks in when it knows the Steam User ID and can then check trusted items, subscribe to them and then download locally, and copy to your installation writables folder.

If we get more reports like this, I am tempted to add a tab to the HUB which reveals all these steps so you can see what is happening in the background. My hope it would be nice and automated, no need to do anything, but your issue suggests we might need eyes on this.

**Comment by synchromesh62** [comment]
> @synchromesh62 Are you actively logged into Steam client when you launch MAX or running directly from Windows Explorer? The sequence is that workshop stuff only kicks in when it knows the Steam User ID and can then check trusted items, subscribe to them and then download locally, and copy to your installation writables folder.
> 
> If we get more reports like this, I am tempted to add a tab to the HUB which reveals all these steps so you can see what is happening in the background. My hope it would be nice and automated, no need to do anything, but your issue suggests we might need eyes on this.

Always logged into Steam :)
I dont think i have ever tried to run Max in offline mode to be honest .

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I have made a small improvement to the copying of workshop items in the latest EXP build, and also added a missing trusted item to the workshop global file too. Can you let me know specifically what you discovered was missing in the files you do see in the EXP build from Steve, thanks!

**Comment by synchromesh62** [comment]
> @synchromesh62 I have made a small improvement to the copying of workshop items in the latest EXP build, and also added a missing trusted item to the workshop global file too. Can you let me know specifically what you discovered was missing in the files you do see in the EXP build from Steve, thanks!

Hi Lee .. Any Behaviour Steve updated or added would only show after a verify.
Also .. 
I Just instructed one user who updated to the EXP for the first time but had no behaviours listed
I had to get him to verify via Steam and restart so they could be seen. ... Related ?

**Comment by synchromesh62** [comment]
This appears to be working fine now.
I will re-open if we get any new reports

**Comment by synchromesh62** [comment]
This has started playing up again .. 
We need to verify any behaviour updates again.

**Comment by Necrym59** [comment]
Perhaps we could get a workshop refresh update button in Max to force for workshop update check so people dont have to do a verify.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 @Necrym59 In the next EXP build I have added a Workshop Tab in the HUB everyone can see, and a button in there that will trigger a full local download of the latest subscribed workshop items. Hopefully, that will help EXP testers before the public release :)
