### ISSUE TITLE
We need a "Remove Button" on texture slots

### ISSUE THREAD

**Issue by saccoforino** [TheGameCreators/GameGuruRepo#4739]
Hi, I noted that when you load a texture into the shader slot, there is not a way to remove it, but only to change it clicking on "..." button.
Maybe should be important and very usefull to have also a Remove texture button each slot.

**Comment by MonkeyFrogStudio** [comment]
As stated on Discord, this has already been requested here. Here's where they've been requested:

https://github.com/TheGameCreators/GameGuruRepo/issues/4196

https://github.com/TheGameCreators/GameGuruRepo/issues/3605

**Comment by davetgc** [comment]
Closed in favour of #4196 and #3605
