### ISSUE TITLE
understanding the engines limitations help

### ISSUE THREAD

**Issue by toonyman2020** [TheGameCreators/GameGuruRepo#4740]
right but in the front page it's not advertise or oriented as an FPS only! which is misleading. which gives the impression that you can make any 3d game you want without coding. I have seen videos of this but there isn't enough information as to what you can really do with it or i just can't get to them all i just don't have a lot of time it's whatever spare time I have. 

so all i had was what was on the store front info and some reviews which was a mixed bag! now i don't mind making an FPS type game but i'm disappointing that that's all you can make with this! and i seen video of the classic gameguru where you can do platformers and other types of games! so if this there newer version of that why or is this one going backwards? so is the game guru classic still more powerful than guru max? maybe that's the one I should have looked into but it's just too old and out dated so it seems and making anything with in today's high demand market for better quality games could be a waste of time.

so I can't change the viewing angle of the player or add any skills or behaviors to it? only what is given is that right? if you have a small team have you consider letting the rest of the world contribute in helping and making better improvement including adding all types of features that are not tied to a single genre which is something that should have been mentioned in the front page instead of sending someone on a goose chase seems like a very important and key feature worth mentioning. which i'm hoping this isn't the case and you can create any game without coding. otherwise trusting anything here would be of things to consider. 

I'm not looking for a refund or anything like that now that i have it just want to see if it get's to that point where you can create any game with it. cause FPS are just all over the place there be nothing unique about them so they be boring to make! you won't standout at all with this. games new to be fun period! having some uniqueness to it is what makes not only standout but can be a great and fun experience. 

and to do it without coding or much effort and just focus on creating that game without all these other distractions that is a great way to make and develop new games! i'm no coder and never will be I take on the design part way more than any coding any day and is why many have come here! when you can make, making games fun and playing them fun then you have something totally unique here! 

off the top of my head and from what i have been able to look at in Gurumax in the short times i have used! there just seems like there a lot of areas that needs improvement.

such as the character creation not too familiar with it but from what I can tell there shouldn't just be a character picker but more like a character morphed where you can modified body parts, like in cyberpunk (this should also include nude parts for mature games otherwise it's not a professional engine with limitations creativity should never have limitations there a lot of adults game on steam alone so there should be any excuses it needs to be as free as blender no limits) and you can change there age and other attribute including a character randomizer and a randomizer base on parameter setting such as ethnicity, age, skin color, language. this way you can group or create characters base on there race including alien race. you should be able to customize clothing and other things! this could be something more like vroid studios, daz studio, realillusion etc where you can truly customize every aspect of your character without creating your own characters but you still have that choice.

the map editor could probably use other shades I was sculpting a terrain field and when you get to the bottom is all dark there no light and you can't clip through the ground or anything at least i haven't gotten to that if you can. so maybe adding a way to see the environment from any position would be handy if this is not already implemented like blender how you can move anywhere and change render shader of all objects in the view scene.

well that's all i have found base on the limited time i have had time to use it.

**Comment by MonkeyFrogStudio** [comment]
Okay ... this site is where we report bugs and make feature requests for GameGuru MAX and GameGuru Classic. It's not a forum or Discord were someone posts long, multi-paragraph discussion-like topics. The Game Creators have both of these if you want to leave a long message like the one you've typed here. And, yes, I am going to post my own long response, despite what I just said. ;)

As far as the kind of game engine MAX is (i.e. making only FPS type games), there is a DEMO on Steam that anyone can try out and work with before actually purchasing the engine. So, you don't have only the website info. There's also a YouTube channel that TGC put out with well over 100 videos showing the development of MAX. It would be pretty easy to discern from watching these that MAX is an FPS game engine.

Having said that, MAX is not tied to a single "genre". The code for MAX is actually available so people can contribute. But just about everything can be extended via Behaviors created with lua. MAX already has something like a hundred or more Behaviors that provide a wide variety of things. As a result, using Behaviors, you can create an FPS game, an RPG game, a puzzle-solving game, a walking simulation game, etc., and any and all of these elements can be mixed and matched. Want quests? There's a Behavior for that. What skills for your player (strength, dexterity, etc.)? There's stuff for that, too! Need an inventory? It can be added ... or not ... all depending on what you want in your game. 

Currently 3rd person isn't there, but MAX is NOT finished yet. It's still being developed. 

The character creator will be extended later with more stuff. It takes time.

Later, the terrain editor will be expanded to allow you to more use your own trees, grasses, and plants, but you can already use your own materials, if you like.

If things get too dark, then turn on a light! The MAX editor has a light you can turn on to light up the area so you see more easily while working on your level.

So, I've written a novel back to you. But to sum up:

1 - GitHub is not the place for these types of posts. Instead, post specific bugs and requests that can be made actionable by the developers.
2 - Get to know the software. You admit to not having much time with it, so read the user-guide and the other included guides. Get your hands dirty and work with MAX until you understand it better.
3 - A good bit of what you want to do with MAX is already in MAX. See point 2.
4 - MAX is not finished being developed. New features will get added in time.

**Comment by synchromesh62** [comment]
Actually he was asking these questions and concerns on Steam and it was me that recommended he post them here so you can blame me for that one.

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 

No worries. He's got a few requests in there, certainly. If he'd posted each one separately (one for the character creator enhancements, etc.) then it would have been okay, I think. But most of what he's posted here is commentary. That just makes it difficult for the developers as they would have to read that wall-o-text to find the requests.

**Comment by davetgc** [comment]
@toonyman2020  Thanks for your feedback. As has been stated, MAX is still in development, and while it's true you can currently only make FPS games (As opposed to 3rd person), you can make quests, puzzle and shooters. If you're okay with FPS , you could also easily make a platformer.

Other game styles will come as we continue to develop new features.

If you would like to list your feature requests as separate issues, this will help the dev team when it comes to looking at user requests and speed up the addition of new additions.

**Comment by toonyman2020** [comment]
sorry for the long wall of text massage here! i just grab the whole thing I posted on steam and threw it here! it was the fastest and convenient choice at the time. 

How ever I think I can summarize this into an easier solution along with any new questions and or request.

**Questions?**
1. How big of  game map can you make cause it seems to have a limit in the engine? like how many skyrims or gta can you fit in this map wise?
2. the types of games styles can you make? such as platforms, fighting, simulations, rpg, action, FPS, as is not mentioned that isnot only an FPS game maker or at least it's not what's advertise as an FPS only game engine? 

and i quote "GameGuru MAX is a 3D game-maker that makes the creation of your game simple, quick and easy – no coding required! With all the tools and assets you need in one place you can start making your dream game in minutes!"

clearly it dose not mention that is only an FPS game engine but? a general game engine game creator! this is front page. and that is what is being paid and advertise otherwise it false advertisement! it even claims that you can make your dream game! again emphasizes that you can make any game with it that you want with the provided tools!

3. type of games you can create? such as games like stardew valley, animal crossing, mario 64, games like dreams on the PS4 games within games, VR and among other titles? such as adult titles again as is advertise and or claims or emphasizes on one being able to create there dream game whatever that may be without coding and with all the tools and assets ready?

**Requests:**
1. New and Improve Character Creation tool - Character Creation is actually terrible as you can only pick characters already made and maybe customize it a little and buggy (i'm trying not to use the word buggy as is in early development). so I'm requesting to changing or creating something better for what is in todays standard of character creation! such as morphing body parts like in daz studio, reallusion, vroid studio, cyberpunk 2077, VAM or VAMX etc. even blender has give us character poses, this new character could allow or unique character creation and that you can also import your own including your own nude model characters. there a new market for this kind a stuff to explore and give players something new and unique of experience! FPS games are just to overrate and overly done more than i can ever count!
 
this way it's not through max but the end user. simply put a guy like me we imply just want to make our game and not what g,g max wants us to make! creative freedom is the key word here! I want to be able make my games that i want and not the games you want me to make due to creative freedom limitations and without coding or creating assets as is advertise! is why i invested money and time into this and hope you guys hold up your end up of the deal! otherwise I can't give this a positive review! I just want a fair chance in creating the games I envision or dream of is why many are here! game engine can't have limitations those blender, unity or unreal have limitations? that what makes it a professional game engine this is currently not at the moment. i'm no coder nor will i ever be at this time otherwise i wouldn't even bother coming here. I just want to get straight into making games without all these other distractions and this what I hope you guys can deliver as advertise. an almost hassle free game engine no coding or asset creation is what this was advertise as. as an artist I just can't have limitations here hope you understand how insulting that really is.

anyways I hope this clears things up and that something can be worked out for all to be able to really create there games!

**Comment by MonkeyFrogStudio** [comment]
Once again, GitHub is only for BUG REPORTS and REQUESTS. Each bug report and each request should be in it's own thread, that way they can assign each one a severity (low, medium, high, etc.) and can assign the developer to work on it, etc. This thread needs to be closed, actually, and your request for an improved character creator made in it's own request thread.

This is NOT the place to ask questions like what kinds of games you can make with MAX, how large a map you can make, etc. As pointed out previously, that's what the Discord server is for and the TGC forum. Use them to ask these kinds of questions and to post your observations about MAX. 

It's pretty important to keep this repository clean, only for bugs and request, and not some wall of text.

**Comment by toonyman2020** [comment]
just wanted to clear things up that's all.

**Comment by davetgc** [comment]
@toonyman2020 - I think you raise some valid points, that I will discuss with the team. However, in future, we fully intend to expand on the engine, to include 3rd person, multiplayer and a load more, but it is true that to date we've focused on FPS and RPG style games.

Really, Discord is the place for these questions and comments, and you can use this link to join. https://discord.gg/ZJUjaang

With regards to your request, you've found the correct board, if you could post that as a separate issue, we can consider it for the future.

Thanks,
