### ISSUE TITLE
audio pause issue.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4745]
when the player had to pause the game (because everyone has to pause at some point) the level stops playing audio from the sound zone, or simply resets the loop. The problem here is because this game has a fair few monologues whilst the player is walking around exploring, it just breaks the momentum of the story/game. Im not sure if it's even possible with max, but ideally the audio needs to pause at the exact moment the menu is brought up, and when the menu's closed and back to the game, the audio needs to continue playing from where it left off.

**Comment by davetgc** [comment]
I've marked this as a bug and an enhancement as it seems like a bit of both.

**Comment by casigus** [comment]
yeah good thinking. People pause games, its a fact of life :D hope we can have that functionality with max :D

**Comment by LeeBamberTGC** [comment]
@casigus Fixed for the NEXT EXP build, active sounds are paused and resumed with no break in the play position :)

**Comment by casigus** [comment]
horay!!!!!! perfect!!! see its things like this that really makes a difference. people will love this even if they dont realise its happening! nice work.
