### ISSUE TITLE
Pause Menu Not Editable ( Reported as requested by Lee )

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4748]
At the moment you cannot remove buttons from the Pause menu.
So for example if i have a small Game \Demo and just want a basic start and Quit it would look like this.

![M1](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/1b38ef8b-1348-4eb7-bc8a-8ab15857ca4b)

However when i pause the game the **Load and Save** are always there as they cannot be removed.

![M2](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/f8fee981-3c92-4a81-8309-b95cf49f927a)

To be fair the other buttons are fine and can stay unremovable as they are game settings.
Its just the **Save and load** you may not want

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Agreed, it is useful to delete LOAD and SAVE from the pause screen, sorted for next EXP build.

**Comment by synchromesh62** [comment]
> @synchromesh62 Agreed, it is useful to delete LOAD and SAVE from the pause screen, sorted for next EXP build.

Perfect Lee i can confirm that works great :)
