### ISSUE TITLE
GG Max: Level Editor stopped saving objects & changes???

### ISSUE THREAD

**Issue by mauriegit** [TheGameCreators/GameGuruRepo#4750]
Good Day

My level editor has stopped saving objects & changes to the game level I am creating? It was still working normally last week?

As of this past Saturday, when I add any new objects, they don't save when I exit the program & return?

Also, I deleted existing objects & saved. I cannot re-add them as they do not save, even after quick Saving?  I have tried both using Max offline & online & through Steam app itself. Same problem? 

This is very frustrating as I now cannot continue building the level. Please assist. 

Kind regards

**Comment by RogeriaEscape** [comment]
Did you save the level ( Save level as .fpm file ? )

**Comment by davetgc** [comment]
Thanks for the report.

I can't replicate this. Is anyone else encountering a problem?

**Comment by mauriegit** [comment]
Hi Dave
Thanks for the reply.

Yes, this is strange. The levels in one of my other testing games work & save as normal.

The issue is on the main game I'm building. And it only started happening as of this past weekend?

There is nothing appear8ng wrong with my frame rate or CPU performance. More than sufficient space left on my SSD.

Please keep me posted.

Kind regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mauriegit** [comment]
Hi Dave
I ran a few quick new tests. Also re-ran the integrity files check on Steam for GG Max. No jssues.

I still have the same problem. However, I picked this up as well:

In my level on the level editor, if I select an existing  object and delete it, and then click either the quick save button, the File Save, or close the program and select "Save First", the changes are saved, and the object has been deleted and removed from my level where it was placed.

But the moment I do the exact opposite, and re add the object and Save, it does not save, and upon exiting the software and opening the level again, the object is gone. Same for new objects.

Please advise.

Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mauriegit** [comment]
Hi Dave

Just some new feedback:

I did some more testing.

 So the problem seems to have started shortly after I imported a building into my level, which I created using the Building Editor.

I have since deleted this building from my level, and it appears that all other objects and changes now save as "normal" again.

I won't close this ticket just yet. Please still check on your side if you can replicate.

Kind regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by davetgc** [comment]
Thanks, that helps.

**Comment by LeeBamberTGC** [comment]
@mauriegit Can you email me (lee@thegamecreators.com) your FPM level just before you add the new object and save, so I can see why the object is not being saved and allowed to be reloaded with the object in place. I assume you are using stock media for this test?

**Comment by mauriegit** [comment]
Hi Lee
Thank you for email.

Experiencing power outage currently so unf won't be able to email the level right  now.

Which file must I attach in the email, the game level in level bank folder?

Kind regards
Maurie

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mauriegit** [comment]
Hi Lee
Thank you. That's what I thought. Will try and send it to you once the power is restored.

In response to your earlier query, yes I am currently using a mixture of stock assets & DLC content for my level, though the Save issue started shortly after I imported a structure I made in the 3D Building Editor.

Kind regards.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mauriegit** [comment]
Hi Lee
Hope you are well

As requested, please see my attached level fpm file.

On the level, when walking up to the main gate of that fenced off complex, to the left is a security booth with a computer stat model set in it.  The security booth itself initially, was not a stock asset, but a building I made using 3D Building Editor. About a day after importing and adding that structure, my level stopped saving new objects entirely. Only after deleting the structure, and replacing it with a model from the stock Offworld station DLC, which I used for most of my level, did my game save objects as normal again.

Please can I request that you do not share my level with anyone other than yourself & your technical staff, as I intend to use Max only for private use/enjoyment. Also, I am relatively new to Max, & this level is my first main project I have been editing for the past few months.

Please contact me if you require further info.

Kind regards



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by LeeBamberTGC** [comment]
@mauriegit The file you emailed me was "mapbank_Operation BioRaid.fpm512x288". Can you send the actual mapbank file ending in .FPM, thanks!

**Comment by LeeBamberTGC** [comment]
@mauriegit Can you zip up all the non official DLC your level uses so I can reproduce exactly. Here are the missing media for the FPM you sent me:

MISSING MEDIA:
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_04_Base.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_04_Base.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_04_Floor.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_04_Floor.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_04_Top.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_04_Top.fpe
entitybank\Showcase\Joe - Military Ally.fpe=replaceentitybank\Showcase\Joe - Military Ally.fpe
entitybank\Cyberpunk Streets Booster Pack\Buildings\CS_Wall_01_Overhang.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Buildings\CS_Wall_01_Overhang.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Streets\CS_Street_Straight_2X.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Streets\CS_Street_Straight_2X.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Sidewalks\CS_Sidewalk_Straight_Edge.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Sidewalks\CS_Sidewalk_Straight_Edge.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_03_Base.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_03_Base.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_03_Floor.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_03_Floor.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_03_Top.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_03_Top.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_04_Base2.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_04_Base2.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_01_Floor.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_01_Floor.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_01_Base2.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_01_Base2.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_01_Top.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_01_Top.fpe
entitybank\Cyberpunk Streets Booster Pack\Buildings\CS_Wall_01.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Buildings\CS_Wall_01.fpe
entitybank\Cyberpunk Streets Booster Pack\Buildings\CS_Sound_Wall_Half.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Buildings\CS_Sound_Wall_Half.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Streets\CS_Street_Straight.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Streets\CS_Street_Straight.fpe
entitybank\Cyberpunk Streets Booster Pack\Buildings\CS_Wall_01_Window.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Buildings\CS_Wall_01_Window.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Sidewalks\CS_Sidewalk_Tile_2x2.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Sidewalks\CS_Sidewalk_Tile_2x2.fpe
entitybank\Cyberpunk Streets Booster Pack\Misc\Building Misc\CS_Neon_05.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Misc\Building Misc\CS_Neon_05.fpe
entitybank\Cyberpunk Streets Booster Pack\Misc\Sidewalk Misc\CS_Street_Lamp.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Misc\Sidewalk Misc\CS_Street_Lamp.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Streets\CS_Street_Manhole_Cover.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Streets\CS_Street_Manhole_Cover.fpe
entitybank\Cyberpunk Streets Booster Pack\Misc\Street Misc\CS_Stop_Light.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Misc\Street Misc\CS_Stop_Light.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Street Decals\CS_Street_Double_Center_Line.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Street Decals\CS_Street_Double_Center_Line.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Street Decals\CS_Street_Crosswalk_Decal.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Street Decals\CS_Street_Crosswalk_Decal.fpe
entitybank\Cyberpunk Streets Booster Pack\Misc\Sidewalk Misc\CS_Fireplug.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Misc\Sidewalk Misc\CS_Fireplug.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_02_Floor.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_02_Floor.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_02_Top.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_02_Top.fpe
entitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_01_Floor_Between.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Background Buildings\CS_BG_Building_01_Floor_Between.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Streets\CS_Street_Crosswalk_Metal_Blocker_Base.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Streets\CS_Street_Crosswalk_Metal_Blocker_Base.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Street Decals\CS_Street_Left_Turn_Arrow_Decal.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Street Decals\CS_Street_Left_Turn_Arrow_Decal.fpe
entitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Street Decals\CS_Street_Straight_Arrow_Only_Decal.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Streets and Sidewalks\Street Decals\CS_Street_Straight_Arrow_Only_Decal.fpe
entitybank\Cyberpunk Streets Booster Pack\Misc\Building Misc\CS_Neon_02.fpe=replaceentitybank\Cyberpunk Streets Booster Pack\Misc\Building Misc\CS_Neon_02.fpe
entitybank\Secret Bunker Booster Pack\Scenery\Signage\Bunker Sign Security 01.fpe=replaceentitybank\Secret Bunker Booster Pack\Scenery\Signage\Bunker Sign Security 01.fpe
entitybank\Secret Bunker Booster Pack\Scenery\Signage\Bunker Sign Airlock A1.fpe=replaceentitybank\Secret Bunker Booster Pack\Scenery\Signage\Bunker Sign Airlock A1.fpe
entitybank\User\buildingeditor\SecKiosk1.fpe=replaceentitybank\User\buildingeditor\SecKiosk1.fpe
entitybank\User\buildingeditor\SecKiosk1_smartchild.fpe=replaceentitybank\User\buildingeditor\SecKiosk1_smartchild.fpe
entitybank\User\charactercreatorplus\BNC Guard1.fpe=replaceentitybank\User\charactercreatorplus\BNC Guard1.fpe
entitybank\User\charactercreatorplus\BNCGuard3.fpe=replaceentitybank\User\charactercreatorplus\BNCGuard3.fpe
entitybank\User\charactercreatorplus\BNCGuard5.fpe=replaceentitybank\User\charactercreatorplus\BNCGuard5.fpe

(You can probably see why I like example FPMs that only use stock media to reproduce a bug) ;)

**Comment by mauriegit** [comment]
Hi Lee
Thank you for your email.

Yes I understand. Unfortunately, it's going to be very difficult for me to be able to zip and send all this info to you, and explain the rationale of my level.


Like I said previously, so far I have not seen this issue on my test level with stock objects, and have resolved it since on my level containing the DLCs.

But thank you very much for your assistance. Much appreciated.  I will let you know if I pick up any problem bugs.

Please let me know whether I should close this ticket.

Kind regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LeeBamberTGC** [comment]
@mauriegit I will close this and if you ever find a way to reproduce with stock media and a small level, we can reopen.

**Comment by mauriegit** [comment]
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
