### ISSUE TITLE
GG MAX - The image is displayed elsewhere

### ISSUE THREAD

**Issue by RogeriaEscape** [TheGameCreators/GameGuruRepo#4751]
Hi everyone ! 

I added Radar to my game and in the hud editor everything is ok but when i test the Game the radar moves up in the left corner
See here : [https://imgur.com/KIBYeUa](url)

in Editor : [https://imgur.com/5PlPgs6](url)

this bug/problem is only at radar after i tested , if i add another image or something everything works perfect.

**Comment by davetgc** [comment]
The radar isn't added via the HUID Editor, but via a behavior. You can adjust the position of the radar using the behavior. Does that solve your problem?

**Comment by davetgc** [comment]
@RogeriaEscape - Is this still an issue, or can I close this?

**Comment by RogeriaEscape** [comment]
It was my mistake, I had used it
"user defined global image" or "user defined global panel"

Now I added the normal image without these 2 options and selected the radar and it works.

The topic can be closed. T/C.
Solved.

Instead of adding the image from "visuals" I added the radar image from "readouts" category.

**Comment by RogeriaEscape** [comment]
Now works , T/C.   [https://imgur.com/a/8C9EAdD](url)
