### ISSUE TITLE
A vulkan question 

### ISSUE THREAD

**Issue by ShadowMasterOfGames** [TheGameCreators/GameGuruRepo#4752]
@LeeBamberTGC If DX 12 is a pain, why not upgrade to vulkan wicked engine instead of DX 12. For one, you already have vulkan in app game kit. Plus doesn't vulkan run on every graphics card already? New and old?

**Comment by davetgc** [comment]
I'll let Lee answer this one.

**Comment by davetgc** [comment]
I"m closing this as I've been assured that Vulkan isn't a viable option.
