### ISSUE TITLE
GameGuruMax - Bug - loop3dsound is not working correctly

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#4753]
So i've been playing around with audio for my game, ideally for the scene i'm about to show off i'd be able to play the same song simultaneously creating a nice fade in - fade out sort of effect when you walk by the speakers in the scene. Unfortunately that is not the case as you can see in this video: https://www.youtube.com/watch?v=lwzDdet1jPw

As can be seen, instead of fading in and out when you walk past the speakers, they restart the song entirely.

Now for the questions, is this working correctly? is it even the correct behavior for the desired effect? is the functionality missing entirely? i have tried both fadeinsound and fadeoutsound as well without much luck, i have played around with the different settings, like volume and range as well as setting the objects to 'always active' and hooking the objects up to a zone, hoping that this would trigger all three of the objects at once.

None of this seems to work, am i doing something wrong? can anyone else get this sort of scene to work? i can't be the only one trying to use music this way in my game.

**Comment by davetgc** [comment]
Are you using the WAV format?

**Comment by Lemuripest93** [comment]
I've tried both .WAV and .OGG.

**Comment by davetgc** [comment]
I've run some tests and this is working for me using the loop3Dsound behaviour. Can anyone else test this please.

**Comment by davetgc** [comment]
I've finally encountered some oddities, where sometimes the behaviour works as expected and other times does nothing.

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Are you using WAV MONO format as this is the only sound type that can use the LOOP3DSOUND script.

**Comment by Lemuripest93** [comment]
@LeeBamberTGC Not that i am aware of, i will reconvert the music track i was using into that format and see if that fixes the issue. I'll report back here with the results.

**Comment by Lemuripest93** [comment]
So i converted the track into WAV format with a MONO audio channel, but it still doesn't fix the issue, is the problem missing functionality? can 3 objects with 'Loop3DSound' play all at once with a certain distance between each other?

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Sure, 3D sounds are designed to intermix. Send me your small FPM using stock media to demo 3 3D sounds and let me know what I should be listening for and what is wrong, thanks!

**Comment by Lemuripest93** [comment]
@LeeBamberTGC Made a small flat map containing 3 shelves, each shelf has a laptop playing the same Country Loop song from the Max audio library, what you should notice when you run from each shelf is that the song restarts instead of continuously playing.
[Loop3DSoundTest.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12005157/Loop3DSoundTest.zip)

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Added new GetEntityAlwaysActive LUA command and updated some scripts, so now when you set specific loop3dsound scripts to always active they will start playing the moment the level starts, and then volume control is based on distance. This should give you the 'radio playing' effect across three devices in different locations without the start again issue you experienced. In NEXT EXP build.

**Comment by Lemuripest93** [comment]
Sounds great, can't wait to try it out :)

**Comment by Lemuripest93** [comment]
I can confirm that this has now fixed the lacking functionality and is working as intended from what i've tested, thank you so much for adding this, it's very much appreciated.

This will now be closed :)
