### ISSUE TITLE
teleport bug.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4754]
the teleport script is just broken. Here's what happens:

https://www.youtube.com/watch?v=Ut7aiu64lmg

the teleport script is not teleporting you to the designated zone, it just drops you in the air randomly.

**Comment by casigus** [comment]
the placement was inside a elevator and wasn't completely solid no, even when I took the entire area of the map away the bug was still happening! 

I have found in my testing, naming the trigger zone "exit" completely breaks the teleport system for some reason!! was suprised at that!!!

**Comment by LeeBamberTGC** [comment]
@casigus There has been some recent work in the EXP build that fixed issues relating to zone logic connections referencing older non existent objects in corrupt levels.  I assume this issue only happens with your existing larger levels and not with a fresh level with a simple zone, object and transport test added.
