### ISSUE TITLE
Only default weapons appearing as inventory items on collection

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4755]
As the title says, only the default guns are appearing as weapons in the inventory and hot keys when collected. If other weapons are added, they aren't appearing in the inventory or hot keys (in inventory). (e.g. from the Wasteland weapons and Wasteland Workshop).

**Comment by LeeBamberTGC** [comment]
@davetgc Fixed for non-stock weapons for next EXP build, was related to internal names not matching given visual names.

**Comment by LeeBamberTGC** [comment]
@davetgc PS. You may need to open the "collection - items.tsv" for the gameproject and delete all the weapon entries as they will have old collection item details in there.
