### ISSUE TITLE
Ladders point towards retired behaviour.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4756]
The ladders point toward a non-existent script, meaning they no longer work out of the box.

**Comment by LeeBamberTGC** [comment]
@davetgc I assume you are using the EXP build. Can I confirm you have Steam client active in the background as MAX will require a new workshop item to reconnect logic with newer versions of this script.

**Comment by davetgc** [comment]
@LeeBamberTGC , yes, the experimental build.

**Comment by LeeBamberTGC** [comment]
@davetgc Ouch, good find in the EXP build. We handle entities when loading a level, but not when just adding a new one. Fixed for the NEXT EXP build :)
