### ISSUE TITLE
creating stand alone game

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#4759]
when i try to create a stand alone game on game guru it says game guru not responding

**Comment by davetgc** [comment]
The process can be quite long, and windows can think that MAX is doing nothing. How long are you waiting?

**Comment by zeebon** [comment]
About 2 to 3 minutes

Sent from my iPhone

On 5 Jul 2023, at 06:57, davetgc ***@***.***> wrote:

﻿

The process can be quite long, and windows can think that MAX is doing nothing. How long are you waiting?

**Comment by davetgc** [comment]
Depending on the size of your level and your PC specs, it could take a lot longer than that.

**Comment by davetgc** [comment]
Can users please share some of their compile times for creating a Standalone? This would be useful for other users.

**Comment by synchromesh62** [comment]
Just tested a demo level ( not big ) and took 40 seconds

**Comment by zeebon** [comment]
Intel i7-10750h@ quad core 16 gig of ram win 11 home 22h2 nvidea GeForce rtx 3060

Sent from my iPhone

On 5 Jul 2023, at 13:23, davetgc ***@***.***> wrote:

﻿

@zeebon<https://github.com/zeebon> - Could you post your system specs please?

**Comment by davetgc** [comment]
@zeebon - Thank you. Could you please leave the build for say 30 minutes and let me know if it actually produces a standalone.

If it doesn't we'll need to start looking at assets, etc.

**Comment by zeebon** [comment]
Just tried it again it kicked in after 4 min and made a stand alone game thank you for your help and patience

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by davetgc** [comment]
No problem. Glad it's working.
