### ISSUE TITLE
Crash on Load Map

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#476]

**Comment by tarkus1971** [comment]
Getting a crash on any map on a new laptop, All map working on my main PC
Laptop specs below
https://www.argos.co.uk/product/8651925

The error is below. Have to use task manager to quite, endless loop. 
![gg error shot](https://user-images.githubusercontent.com/36561118/51086893-e85a7200-1743-11e9-9873-87901c640068.jpg)

All steam files verify OK

**Comment by tarkus1971** [comment]
This happens after I save a new map and then GG re-loads it, crashes, or I load an old map. This only occurs on this laptop, could it be the optane memory ?????  Anyone else had this problem.

**Comment by plemsoft** [comment]
Could be a permission problem, try to run as Admin and post if this fix it.

**Comment by tarkus1971** [comment]
sorry for delay, will re-install GG and see if running in admin fixes this.

**Comment by tarkus1971** [comment]
Running GG and steam in with admin privileges but still im getting this error.  Could it be because of the Intel UHD 620 built in GFX chip? 

GG was a clean install and all files verified.

**Comment by plemsoft** [comment]
@tarkus1971 Could you try to edit setup.ini and use "producelogfiles=1" , and then post the log file here :)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
No further reports from OP and have not been able to reproduce it so I can only assume he solved the issue .. Unable to link to his specs but does seem a system error rather than a GG one.
