### ISSUE TITLE
Crashing to desktop

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#4760]
GGMax is currently freezing then crashing to desktop for me (video below) This has happened twice before in the past 2 months and was rectified by updated my Nvidia drivers to the latest version.

This time, my drivers are all fully updated and everything is uptodate.

Basically, open max, and within approx 25 seconds it freezes everything other than close program in the top right corner.
if you watch my cursor move around the hub in max, youll see the various projects highlight/emboss correctly, then at 21 seconds, this stops happening when i move my mouse. at the end of the video i try to minimise the window, the screen goes white and crashes back to my desktop. Hope you can help.

With my previous experiences i presume its a local driver issue, however as everything is updated, it could be something else.

https://www.youtube.com/watch?v=M6JaF3mFwQY

**Comment by mav3r1ck198-1** [comment]
@MonkeyFrogStudio 3060ti

**Comment by MonkeyFrogStudio** [comment]
@mav3r1ck198-1 Wow. No idea why this is happening, then. I'm sure you tried to verify your MAX files, right?

**Comment by mav3r1ck198-1** [comment]
fixed a manual reinstall of the latest drivers
