### ISSUE TITLE
GameGuru Max - Crash bug when editing Save/Load Game Screens

### ISSUE THREAD

**Issue by Melburnian70** [TheGameCreators/GameGuruRepo#4764]
GameGuru Max crashes after adding an image to the Save/Load Game screens, sending it to the back, and then clicking on the last Save/Load slot.

You can also notice that the names of the slots change: they start out numbered 1-8, but after sending the image to the back, they change to 2, 3, 4, 5, 6, 7, 8, 8.

Steps to reproduce:

1. Open the Save Game or Load Game screen (it happens to both)
2. Take note of the slot names
3. Add a new image
4. Right-click it and 'Send to Back'
5. Notice the change in slot names
6. Click on the last slot and GG Max will crash

![save game screen](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/4c50a033-c558-40c1-b44a-657457a5f546)

![save game screen - send to back](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/3cea1af7-fbd7-4e2c-965c-8c10f91dd656)

![save game screen - bug](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/15afdffc-6f15-4d95-ace8-1df165644651)

**Comment by LeeBamberTGC** [comment]
@Melburnian70 Ncie find. Turns out the save and load scripts area little hardcoded when assigning the widget names for saving the game slot list. For now I have limited the front and back widget shufting to new items, and leave the original 9 widget (title and the slots) alone to prevent this corruption.  Wil be in the next EXP build.

**Comment by Melburnian70** [comment]
@LeeBamberTGC Thanks Lee. 

I tested this in the latest update (after verifying files) but clicking on the last Save/Load slot still crashes Max in my existing project that the crash previously occurred in. 

Another project which never had the bug, won't allow me to cause the bug to happen now, which is great. But is there a way to reset the Save/Load HUDs in my previous project so they don't crash?

**Comment by LeeBamberTGC** [comment]
The crash is due to a corrupt project. You can delete project.dat or e could add a Reset item in the drop-down?

**Comment by Melburnian70** [comment]
@LeeBamberTGC Thanks Lee, a drop-down to reset individual HUDs would be great, if that's possible!

**Comment by LeeBamberTGC** [comment]
@Melburnian70 I have added a restore option for default screens in the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/354f538e-7065-47ed-806d-7b1dd465ee76)

**Comment by Melburnian70** [comment]
@LeeBamberTGC Thanks Lee. After restoring the Save and Load HUDs, I can now click on the last Save/Load slots without crashing, but now when I click on the restored Back button I get the crash! I customised the Back button (and most elements) and restoring the HUDs looks like it left it there and added back in the original Back button which now crashes.
![save-screen-bug-update](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/cb59a91d-3d34-4472-8112-50289ee2e56a)

**Comment by LeeBamberTGC** [comment]
@Melburnian70 Thanks for the feedback. I have extended the restore to a more thorough and total one, now removes any old elements, resets all settings, etc so there is nothing left of any old element data in the newly restored screen though node relationships are retained along with some screen-specific stuff not directly screen or editor related.

**Comment by Melburnian70** [comment]
@LeeBamberTGC Thanks Lee, that's fixed the crash now! The numbering is still slightly off, but I'll mark this as complete as it has fixed the crash 😄  
![save-screen-bug-update-2](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/5f42452d-1bdb-408a-a014-f8e1d73c075c)
