### ISSUE TITLE
MAX - Huge performance hit/freeze from exploding barrels

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#4766]
Was playing Canyon Offensive to test out some of my combat improvements I was working on, and I noticed that the engine comes to a screeching halt whenever a barrel explodes. (Especially the clustered up groups of barrels, when they all go off it causes a 1-2 second freeze.)

To replicate, play the Canyon Offensive demo, and look for one of the explosive barrel clusters. Shooting them will cause a severe nosedive in performance, and often a full-on brief freeze. It seems to be more drastic/pronounced the more entities that are sitting near the barrel(s), so my guess is it might have something to do with the way explosions are looking for nearby entities to apply damage(?)

**Comment by fearlesswee** [comment]
Did some more testing; loaded up an "EMPTY" biome level, and placed some barrels in various scenarios, and shot them to measure the results:

20 or so barrels clustered together, with nothing nearby = Very heavy framerate drop, eventually freezing entirely, and then crash-to-desktop after 3-5 seconds of being frozen.

5 barrels clustered together, with nothing nearby = Minimal framerate drop, almost unnoticeable

1 barrel by it's lonesome = Essentially zero performance hit

1 barrel with 20 or so ammo pickups near it = Moderate performance hit, very slightly worse than the 5 barrels with nothing nearby

It would seem my hunch holds water; it has something to do with explosions going off with a lot of entities nearby/in the level

**Comment by MonkeyFrogStudio** [comment]
I did a test and am getting pretty massive frame losses here with exploding barrels. I set up 24 exploding barrels and shot them in an empty level. With vsync on, before shooting the barrels, the frame rate is a steady 100fps. When you shoot the barrels (as they are exploding), the frame rate drops to 60fps or so. Now, if you turn off vsync, then my frame rates are close to 300fps. When I shoot the barrels, the frame rate drops down to the same 60fps or so! 

60fps means I wouldn't notice the frame rate loss (most likely) on my machine, but I have a really good video card. With a lesser video card, I would assume this large of a frame rate hit would cause stuttering (at best) on some people's systems. 

Having said that, like the example @fearlesswee gives above, if I reduce the barrels down to 4, for example, the frame rate hit is barely noticeable. I get a single frame drop with vsync on (from 100 to 99).

I did the same test in a level filled with objects (my Cyberpunk Streets demo level). With one barrel, the frame rate drop similar to the above - from 100fps to 99fps. With 24 exploding barrels, the frame rate dropped similarly, too - from 100fps to about 60fps. 

So, for me, it didn't matter if the level was empty or filled with entities, the frame rate drop was about the same.

**Comment by davetgc** [comment]
I can confirm this. I didn't get a crash, but I'll mark his as high because it has been experienced.

**Comment by fearlesswee** [comment]
Closing this now as not only do barrels perform MUCH better now, but I've actually programmed my own explosive barrel system which offers a lot more customizability and uses particles, and performs super great, even with dozens of barrels going off at once :)
