### ISSUE TITLE
Spray Object Control UX

### ISSUE THREAD

**Issue by XTCTOM** [TheGameCreators/GameGuruRepo#4771]
I think the Spray Object checkbox and slider would be better placed on the left panel under the Current Objects panel. Because the right panel seems to be more about position and configuring a single selected object whereas the left panel is more about selecting objects for placement.

For example I had spray object enabled but I forgot and when I clicked an object from the Object List it confused me when it placed multiple, I thought it was a bug at first, especially as the spray indicator circle that normally appears did not appear. The spray control was collapsed out of view on the right. Having the controls always in view under the Current Object might make it more obvious and intuitive.

**Comment by MonkeyFrogStudio** [comment]
Hmmm ... the left-side panels are all about the KINDS of objects (models, zones, flags, probes). So you can drag from the left-side to place a particular kind of object. The right-side panels are for MANIPULATING those objects (translate, size, scale, materials, static, physics, etc.). As a result, I think that spray would fit better there since it isn't an object itself, but another method of manipulating the placement of objects. But that's just my opinion.

**Comment by XTCTOM** [comment]
Well spray is more of a placement tool than a manipulating object tool so the left panel which is more about selection and placement seems like a better fit imo.

It's like "I want to start placing this object I just picked, now how do I want to place it?" Individually or spray? Having the controls tighter to the object selection/placement controls makes more sense to me. But because the spray control is so far away from selection and can be collapsed out of view you tend to forget if it's enabled or not when selecting a different object. But yeah I can see how it can be a split preference. At the very least having the indicator cirlcle always shown when active, even when switching between objects would be nice.

**Comment by MonkeyFrogStudio** [comment]
Movement IS manipulation. That's what "translate" is (referenced in my previous quote). It's called "position" on the right-side panel. 

The left-side is for actual OBJECTS - single objects, like you see in the level object panel; game elements, like player start, zones, flags, probes, etc.; current objects and grouped objects. Everything over there is for showing which objects are available for you to use. SPRAY is not an object at all. It's a setting, like Grid Snapping is (which is on the right-side panels where all the tools are that you use to manipulate your objects). So SPRAY is a TOOL and TOOLS are on the right-side. Objects on the left, tools on the right. 

Now, I do think that Spray is misplaced where it is. At least I think it should go somewhere else on the right-side. Even better, I think that Spray should be activated via a key press ... maybe something you have to keep holding down to make it work. Once the key is released, you go back to normal placement mode.

**Comment by XTCTOM** [comment]
I know what translate means. But spraying isn't a movement tool nor a manipulation tool. It's a *placement* tool used when *adding* objects to the map and everything on the left panel is also about *adding* new objects to the map. I'm not suggesting any positioning tools be moved just the spray checkbox and it's radius but it's only a suggestion at the end of the day.

**Comment by MonkeyFrogStudio** [comment]
Spray is a paint tool, like when you paint in grass, trees, and other terrain plants. It's a paint tool just like when you paint terrain textures, etc. Thus, it uses a radius. All of the paint TOOLS are located on the right-side panel. None are on the left. So, again, the spray tool, being a tool, belongs on the right-side with all the other tools. 

Movement is placement, by the way. And, as you can see, the numeric entry for movement is also on the right-side with the rest of the tools. 

Sorry to be a stickler about this, but as far as the way the current MAX UI is set up, spray does not belong on the left side with all the objects. It's clearly a tool and it fits with the other tools it's meant to work with.

Of course, this is just my opinion. The developers have the final say, of course. ;)

**Comment by XTCTOM** [comment]
Movement and positioning are not the same as adding/placement. The terrain tools are all grouped together on the right because they are for editing and manipulating the terrain so yes they along belong together on the right. But object tools are split left and right. Controls for object selection and adding objects are on the left whilst object manipulation and properties are on the right. Spray is a placement/adding tool, it's not a movement tool and not it's used for manipulation or positioning.

Something exists: we go to the right panel to edit it.

Something doesn't exist: we go to the left panel to add it.

The terrain already exists so we go to the right panel to edit it even with painting grass etc. this is part of the editing terrain process. However my bush objects need to be added to the map so I go to the left panel to select the object and (imo) selecting whether to spray them or not would be part of that adding objects to map process. Having that option buried over on the right is not intuitive, especially for new users.

**Comment by XTCTOM** [comment]
I would like to also point out that if you click on another object to select it when spraying is enabled chaos ensues and you end up splatting out a load of objects you didn't want.

For example first I spray a load of bushes and then I click on a character to move it. When I click the character I end up cloning a bunch of them on the map. This is unlikely to be desired behaviour.

I think if you select or change to a different object to the one you are spraying then spray should probably be automatically disabled because it interferes with expected object selection. At the moment you have to remember to manually switch it off when you are finished with it and this is another reason why it should be a bit more prominently placed on the UI so you can see when it's on or not. If it automatically disabled on object change and always had the range circle visible then perhaps it would be fine where it is because you wouldn't need to monitor it's setting so much.

**Comment by davetgc** [comment]
I honestly like it where is it. What do others think?

**Comment by MonkeyFrogStudio** [comment]
It's simple (to me) - it's not an object or game element. Only objects and game elements are on the left-side panels. It's a setting, like grid snapping. Thus, belongs with the other similar tools.
