### ISSUE TITLE
GG Max - Building creates a hole which can destroy entire level 

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#4772]
Just look at this. When you zoom using editor's camera when this hole is there it suddenly just becomes black/yellow (depending on skybox), and you can't return to normal view. 

https://www.youtube.com/watch?v=dj6NOVmsC28

**Comment by davetgc** [comment]
@NewWave2137  - Are you able to supply the map file (Called an FPM file and located in your Mapbank folder.) where this has happened please?

**Comment by NewWave2137** [comment]
@davetgc  Just put a few buildings there and it should happen. 
[https://drive.google.com/file/d/1lYS38tg_HY071I4s2_p_yz0PhbFvSg3x/view?usp=sharing](url)

**Comment by LeeBamberTGC** [comment]
@NewWave2137 In the latest EXP build I added three buildings made with the Building Editor and they dropped into the level just fine, no holes in the terrain and no texture edging as shown in the video:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5279b246-48d6-4b4b-9b7f-6f0dbd2c73d1)

If you attach the FPM file of the level holding these buildings, and the building export files itself so the FPM can locate the offending building object, I may be able to see what you are seeing.

**Comment by NewWave2137** [comment]
I can confirm that it's not happening anymore.
