### ISSUE TITLE
Enhancement Request: auto save

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4773]
every game has an autosave.

Ggmax exported games needs an auto save.

My suggestion would b to make the check points also autosave, so if a player needs to reload, they can do taking them back to that check point!

**Comment by synchromesh62** [comment]
**every game has an autosave.**
They really don't. I recon 80% of my games on steam have manual save via terminal. Pause or on exit.
However .. Max already has a **Save Gamestate**  you can attach to a triggerzone anywhere you like :)

![SG](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/75073b7d-e26c-41ba-943a-12d44ed3e3ee)

**Comment by casigus** [comment]
outstanding.
