### ISSUE TITLE
GG Max: Allied Characters NOT engaging enemy characters 

### ISSUE THREAD

**Issue by mauriegit** [TheGameCreators/GameGuruRepo#4774]
Good Day
I seem to have encountered another bug on my level.

My Allied Characters, when approaching enemy characters, do not engage them with their weapons. My enemy characters as a result just mow them down?

It's not a critical issue for me at this stage, but please take note.

Kind regards

**Comment by davetgc** [comment]
I've actually noticed a lack of response from enemies as well using the character attack behavior.

**Comment by LeeBamberTGC** [comment]
@mauriegit In the latest EXP build, I dropped down three allies and six warriors, and the allies opened up on the enemies no problem:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/15817ec1-1b69-4a17-ad74-e6d20af502d9)

Can you attach a simple FPM level file using stock assets only showing the issue you are reporting, thanks!

**Comment by mauriegit** [comment]
Hi Lee
That the thing. I have a concept test level which I often use to test objects & behaviors.

I tested allies & enemies there in a similar way. All normal with no issues.

Also Lee, this issue is on the same level I emailed you on the other ticket for the Save Issue, which now no longer occurs.

Kind regards
Maurie

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LeeBamberTGC** [comment]
@mauriegit If this only happens on a larger older level, it may be due to corruption from dev work. You can try removing characters and behaviors associated with them, save as a new test level with no AI being used, then slowly add AI users back in to see if the problem is restored with the latest EXP build. Feel free to close this if the solution works.

**Comment by mauriegit** [comment]
Hi Lee
Thank you. I will have a look and let you know.

Yes, this level I have been building for the past few months, so I am putting a lot of time & effort into it. It is at least 3.5 months old.

Kind regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mauriegit** [comment]
Hi Lee & Dave
Issue appears resolved on my side now. Thank you.

I'll be closing this ticket. 
Kind regards
