### ISSUE TITLE
Character Creator Asset Crash List

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#4776]
When using the Character Creator there are certain parts that when selected will crash GGM after the following message pops up.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/f1f96198-535b-439b-b978-221c0f79cd6e)

List of broken parts that cause this are.
 
Adult Male
-T Shirt White Logo

Woman
-Blouse White (1/1 breaks, the one on 2/3 works)
-Blouse White Logo
-Shoes Black

**Comment by MonkeyFrogStudio** [comment]
Also reported here (at least some of it):

https://github.com/TheGameCreators/GameGuruRepo/issues/4670

**Comment by extremestrategy** [comment]
Oh, I didn't know some of it was already reported.

**Comment by MonkeyFrogStudio** [comment]
No worries. In this case, I believe you've reported more than the other post. And since the other was older, I think it's important that TGC know that these items cause crashes in MAX.

**Comment by LeeBamberTGC** [comment]
@extremestrategy Thanks, I can reproduce, leave with me :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0c8f7338-6cd7-47d2-b2c0-ac001fa75f94)

**Comment by LeeBamberTGC** [comment]
@extremestrategy Fixed for next EXP build, was related to some textures bing BC7 when they needed to be BC1 for the skin processing logic. Let me know if you find more in the stock collection!

**Comment by extremestrategy** [comment]
Fixed.
