### ISSUE TITLE
GG max Stamina issue

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4777]
The stamina and stamina bar are not working

**Comment by davetgc** [comment]
I can confirm this.

**Comment by LeeBamberTGC** [comment]
@Keepo1 In latest build, RPG Template shows working stamina bar, and I can run it down when running. Can you povide steps to reproduce what you are reporting:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/fba55f08-0ca3-44fc-a88f-48b0a7775832)
