### ISSUE TITLE
Helicopters break weapons.

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#4779]
When using the Boeing Apache Helicopter, if you crash the helicopter your weapons will not be usable upon respawning, and even trying to equip new ones via pick up or inventory will not allow the player to use them.

In order to replicate this place down the Apache and set the behavior to Aircraft, then launch the game, pick up a weapon, get into the Apache and then crash it, upon respawning your weapons will not appear your hand.

**Comment by LeeBamberTGC** [comment]
@extremestrategy In the latest EXP build I dropped in the gun and heli, collected the gun, rode the heli:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c815ef43-8c0a-4071-9b2a-65e5eddb2986)
then pressed Q to exit and I was back in the land with my weapon. Cannot reproduce.

**Comment by extremestrategy** [comment]
Thank you, I will contact him then.
