### ISSUE TITLE
.dbo encryption still flawed

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4781]
Although ,dbo and its materials are encrypted to the outside world it would appear that they can still be copied and used by other Max users meaning any assets in standalones are a free for all within the community.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 @MonkeyFrogStudio In the next EXP build you will no longer be able to use encrypted files in the MAX editor.

**Comment by synchromesh62** [comment]
> @synchromesh62 @MonkeyFrogStudio In the next EXP build you will no longer be able to use encrypted files in the MAX editor.
Confirmed as fixed .. 
Wont let me go anywhere near it :)
Thanks Lee
