### ISSUE TITLE
Wrong Startup Screen on Stand Alone Game

### ISSUE THREAD

**Issue by ockerdave** [TheGameCreators/GameGuruRepo#4782]
Problem saving Stand Alone Game, I altered the background images for Start Screen & Loading Screen, 
but on starting the compiled game, the altered screens did not show up only the vanilla screens provided 
by GGMAX.

**Comment by LeeBamberTGC** [comment]
@ockerdave I changed both screens with my own imags using a recent game project I created for some tests as you can see here:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/61534368-e5d9-4310-8ebf-12f500295e8e)

When I ran the standalone, I saw the splash and loading screen just fine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/19e3b293-7393-4434-9c7a-b4247369abc1)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/86e0f1d1-1dc6-4797-b8ff-e0e2217f0d41)

Can you try again with the next EXP build with a fresh game project and let me know how it goes. Ensure the images you select from are in the imagebank of your writables folder for the best effect.

**Comment by ockerdave** [comment]
Hi Lee, after building new game, first level, the changed Start Screen & Load Screen included my own image's. Now all working fine, including problems I had with the RPG Quests.
Just liked to include how much I like everything about Gameguru Max, you have taken it on the right direction, congratulations on a job well done.

**Comment by LeeBamberTGC** [comment]
@ockerdave My pleasure, thanks for confirming this fix!
