### ISSUE TITLE
GG MAX Build 2023-07-16 ( Experimental) : materials labels are invisible in the Asset Importer

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#4784]
Context : Scene with more than 20 items created in a Daz Studio 4.x project and exported as a single FBX file.

The GameGuru MAX Asset Importer handles easily that FBX file, but I need to make some manual adjustments on the textures because some textures are in .TIF format ( a format that can store the alpha transparency).

Problem (as shown in this screen capture) : the materials labels are invisible in the Asset Importer ( but they are well there ! ) 

 
![daz_fbx](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/1a1bf1fe-d935-4622-942d-7af5ba97e81e)

**Comment by MonkeyFrogStudio** [comment]
TIF is not a supported file format for objects (or for anything in MAX). I'm a bit surprised that the models came into MAX fine with TIF. You should be using DDS or PNG. DDS, depending on the version you convert to, will also support alpha channel and is much better when it comes to video memory management. 

From the GameGuru MAX User Manual:

_**The importer supports .OBJ, .FBX. .glTF, .X, .GLB and .DBO mesh formats. The
associated textures must be in PNG, JPG and DDS formats.**_

I've not tried importing a large set of objects as one FBX, but I can say that all my models, using DDS, come in to MAX fine with the material names shown in the importer.

**Comment by marcuswilm** [comment]
@MonkeyFrogStudio  @davetgc 
After having noticed that Daz Studio exported some textures in .TIF format I then edited the FBX file (saved in ascii format)  to replace all those .TIF extensions by .PNG ones.
Of course, at the same time I created new .PNG images for each .TIF images included in the MAP folder generated by Daz Studio ( I used the software 'xnconvert' for that purpose ).
Then I imported again that big FBX file with the correct images format defined in that file.
Therefore what you see in the screen capture shown in my previous comment is the status after that adjustment.

I also tested the .OBJ format ( no .TIF images included ) and the same problem occured in the Asset Importer ( materials labels are invisible).

BUT ... later after having posted that thread, I noticed that even though all the materials were correctly placed on each assets of the imported scene ( except for the setting 'transparency' relative to the .PNG images), I unfortunately noticed that the  majority of the materials was wrongly applied on the assets when I placed the imported scene in the GameGuru active level.

Good to know : the Microsoft 3D viewer shows correctly that scene created in Daz Studio and saved in FBX format.
![the_backyard_3d_viewer_microsoft](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/c7380590-91c3-4563-9053-b6fc8199a138)

(for your information : this is the page relative to that scene available in Daz Studio Store : https://www.daz3d.com/the-backyard )

Currently after having tested several hundreds import of assets (animated or not) in FBX, GLB, OBJ format during nearly two years of practice with GameGuru MAX, I consider that the .DBO format generated by GameGuru MAX offers a limited level of flexibility to the artists whatever the 3D art software they are using.

But it is only my humble opinion.

**Comment by MonkeyFrogStudio** [comment]
1 - It's is always preferable to import single objects than entire scenes (even if they are relatively small, like yours with only 20 objects in it). The scene you show here would be easy to reconstruct once all the parts are inside MAX.

2 - Perhaps the issue is with the way DAZ exports their files? I don't use DAZ3D, so I've no means to test this. I do know, though, that FBX and OBJ files that I create myself in Blender do import correctly into MAX with material names visible in the importer. MAX uses the ASSIMP importer, I believe. It needs to be able to read the file it's importing and get the material name from that file. If there's some sort of strangeness going on via DAZ's exporter, then that might be causing the issue (though it could well be MAX's fault, too). 

Out of curiosity, have you tried exporting only one object from DAZ and then importing that into MAX to see if the material names show up for that one object?

**Comment by marcuswilm** [comment]
@MonkeyFrogStudio  @davetgc 

MonkeyFrogStudio : answer to your question relative to the import of only one asset exported from Daz in FBX format, I may say that the problem with those invisible labels in the asset importer doesn't occur.
However to obtain the PBR quality of the materials on  the Daz Studio imported asset, manual adjustments are required and that could be a cumbersome task if it contains many materials.

I hope that I answered as expected to your question.

**Comment by marcuswilm** [comment]
@MonkeyFrogStudio  @davetgc 

Today ( after a good night ) I had some inspiration and I decided to test that Daz scene exported in ascii FBX format with an old GG MAX version (build 2022-08-19) and this experiment confirms that the invisibility of the materials labels  is a new problem that only occurs with the importer of the most recent steam build of GG MAX.

Indeed the materials labels are visible in the scrollable widget in the asset importer of the old alpha version of GG MAX.

However the problem with the materials wrongly applied on the assets of the scene ( once it is converted in .DBO format and placed in a level of a GG MAX project) already existed in that old version of GG MAX ( alpha build from TGC website).

Thanks to that experiment with the old version of GG MAX  I clearly noticed these points :  
-  the .FPE file relative to that imported scene contains 175 materials and 23 textures references.
-  the scrollable widget of the 'materials' section in the 'Object Tool' of GameGuru MAX shows only the labels for 100 materials.

This limitation explains why some assets in that scene imported in GG MAX are not correctly textured.

But that problem of invisible materials labels seems to be a bug inside the latest experimental builds of GG MAX (steam version).

**Comment by marcuswilm** [comment]
@MonkeyFrogStudio  @davetgc 

In my humble opinion it clearly appears that the asset importer of GameGuru MAX is still a work in progress as demonstrated with this commented screen capture.

![daz-metasequoia-ggmax-materials-import-export](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/34e75a65-6df0-4a1b-8795-bd2dc3b3ee89)


I could also add that the rigged animations for the bipeds in FBX format are wrongly imported in GameGuru MAX while the same animations are correctly imported in Blender.
