### ISSUE TITLE
Still black screen issue.

### ISSUE THREAD

**Issue by ScottCastle** [TheGameCreators/GameGuruRepo#4789]
I saw that there was a fix for this but it continues to happen on my computer, I have a AMD ryzen 7 6000 series, hope you can fix this further because I have yet been able to use the engine for months now.

**Comment by LeeBamberTGC** [comment]
@ScottCastle We tried threading the needle here with detecting specific AMD cards, but it seems MOST cards are having this little hiccup. I have modified the code for the next EXP build to emcompass pretty much any RX card now:

			if (pestrcasestr(cDeviceName, "AMD") || pestrcasestr(cDeviceName, "Radeon") )
			{
				//PE: Take all 6900,5600,6800,6600 RX serie if amd.
				if (pestrcasestr(cDeviceName, "RX"))
				{
					// more reports coming in, this time "AMD ryzen 7 6000" so lets assume ALL RX need the fix!
					//if (pestrcasestr(cDeviceName, "89") || pestrcasestr(cDeviceName, "79") || pestrcasestr(cDeviceName, "69") || pestrcasestr(cDeviceName, "68") || pestrcasestr(cDeviceName, "66") || pestrcasestr(cDeviceName, "67") || pestrcasestr(cDeviceName, "65"))
					{
						bIsAMDCard = true;
						break;
					}
				}
				else
				{
					//PE: special case for amd 5600 xt
					if(pestrcasestr(cDeviceName, "5600"))
					{
						bIsAMDCard = true;
						break;
					}
				}
			}

Let me know if this works for you in the next EXP build :)
