### ISSUE TITLE
Trees - Player can See Inside Trees when Close

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#479]
This is a bug that's been around for a while. The player can partly see inside the follow animated trees in the Foliage folder:

Tree01
Tree03
Tree07
Tree08
Tree09 (most obvious, due to its scale)

If the player stands close enough to the base of the tree, he will be able to peer inside them.

**Comment by plemsoft** [comment]
Not really a bug, i made it this way to fix the z-fighting issues we had , but i also made it so you can control this in the setup.ini , please make sure that you currently have this "lowestnearcamera=2". You can lower this value to 1 and you will not be able to see inside the trees but it will give you more z-fighting in the distance, so its a value you can use and adjust to your needs. I set it to 2 as it gives the best z-fighting result for most people.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

lowestnearcamera=1 will be used as default in the next update , this will let you adjust it using the "camera distance" in the tab tab menu :)
