### ISSUE TITLE
 imported models  do not save with the level- check FPE file. 

### ISSUE THREAD

**Issue by sciencebloke50** [TheGameCreators/GameGuruRepo#4790]
GGMAX - i have established today my imported animated characters that usually save with my levels are no longer saving. 
i imported them and they animate and work using the NPC control script, they react and are great in level after tweaking. the problem is as soon as i save the level they get erased. and this happens when the level remains. it is as though there is a clear out of these models dbo during saving. its not the npc script as i have tried to save without any changes or script. i have saved on a different level and the same occurs. i have also done the verify and it has loaded and saved the missing files but again the entities get deleted upon saving. i have used the goblin from the fantasy pack i brought in its DBO and updated and imported. but i have also done it with my models
character creator characters save with the program. it seems only imported models with animations and character settings disappear
i also note that during the save it displays missing behaviours and nothing similar on steam to use

another bug regarding imported characters animating and behaviours- if a character gets to about 1.5 sizes above the player a troll, they stick to the spot- again tested many ways but it seems imported models dont sit well at present with max.

kind regards

update screens of evidence
one shows an animated curtain just placed for show and then a goblin, no behaviour was attached during the photos. when i saved it said not responding then shows the the text no behaviours found and then saves and no monster but animated curtain remains
hope this helps further

**Comment by sciencebloke50** [comment]
thanks everyone for your help found the issue 

it was actually FPE files whilst altering it was saving as normal txt files so it was not taking it on board. 
PLEASE can you put this 5 days struggle into a do not save as anything other than fpe. and to make it be aware. i was just saving the opened fpe and it converted without my knowledge

**Comment by GraPhiX-Guru** [comment]
> thanks everyone for your help found the issue
> 
> it was actually FPE files whilst altering it was saving as normal txt files so it was not taking it on board. PLEASE can you put this 5 days struggle into a do not save as anything other than fpe. and to make it be aware. i was just saving the opened fpe and it converted without my knowledge

I have created an 'FPE' text editor when i have 5 mins i will post it on Forums, this only saves as .fpe so things like this wont happen ;)

**Comment by sciencebloke50** [comment]
Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
