### ISSUE TITLE
GameGuru Max bug: Graphics Settings HUD keeps zooming player camera

### ISSUE THREAD

**Issue by Melburnian70** [TheGameCreators/GameGuruRepo#4791]
After bringing up the Pause menu in-game, each time you click the Graphics Settings HUD the player's camera zooms in. This happens every time you do this, and the camera gets stuck in this zoomed in FOV when you click Resume Game.

See attached video.

**Steps to reproduce:**
1. Remove the background image from the Pause and Graphics Settings HUDs
2. Select Transparent Backdrop for both these HUDs
3. Play a standalone game and hit ESC to bring up the Pause menu
4. Click Graphics Settings and observe the camera zooming in
5. Click Back, then repeat step 4 to witness the camera zooming in every time.

https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/3ead7b99-a967-4047-be2d-e6dfacb7f7f0

**Comment by LeeBamberTGC** [comment]
@Melburnian70 Fixed for the next EXP build, related to a small micalc of how Plyer FOV in the HUD translated to the camera FOV applied to the game.

**Comment by Melburnian70** [comment]
@LeeBamberTGC Thanks Lee! I can confirm this has now been fixed in the latest update.
