### ISSUE TITLE
MAX - Lua command to end/fail the game

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#4792]
Currently, it is **_impossible_** to reach a game-over state in MAX. You can die an endless number of times, and there's no way to manually trigger a game-over state if the player fails an objective (for example, an NPC they must escort is killed by enemies, or they take too long to solve a puzzle in a given time limit.) If we had a simple "game over" command, we could solve all possible cases for a game over ourselves in custom behaviors. 

Something like "FailGame()" or "GameOver()" would be suitable.

**Comment by synchromesh62** [comment]
I think i posted pretty much the same here at the beginning of June
https://github.com/TheGameCreators/GameGuruRepo/issues/4692

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I will keep this one as the feature request, and regard the issue linked as the original bug report. As you say, right now it is impossible to die and go to the game over screen (bug). And a script/command to force an end to the game also makes sense, though you could achieve the same I imagine by setting the player health to zero, although it would be a gory way to end the game :)

**Comment by fearlesswee** [comment]
@LeeBamberTGC While you could (given the infinite lives glitch was fixed on the somewhat-related issue) it would come across as a bit "strange"; say the player fails protecting a VIP, why would their head spontaneously explode? Ideally it should trigger a separate game over screen, saying something like "You failed to protect a vital asset, we're withdrawing you immediately!" or similar. I think this should remain as a feature request like you said, since there's plenty of possible "game over" states that don't necessarily involve the player dying.

**Comment by Necrym59** [comment]
Seems thats more of a behaviour to end the game if conditions are not met, perhaps just a lua command to end the game is required and behaviours would monitor the conditions in a game rather than a fixed setting in max.

**Comment by LeeBamberTGC** [comment]
@fearlesswee @Necrym59 Pretty essential feature actually :)  Added WinGame() and LoseGame() commands so behaviors can now entirely decide what the level should do under any logic condition.  Will be in next EXP build, enjoy!

**Comment by fearlesswee** [comment]
Closing as "fixed" due to the addition of aforementioned commands. Always good to have more control over the game state :)
