### ISSUE TITLE
Problem with BOAT Behavior

### ISSUE THREAD

**Issue by saccoforino** [TheGameCreators/GameGuruRepo#4794]
Hi, I think there is a problem with BOAT Behavior. I can't change the Y position when controlling the boat.
Driving the boat, the hight remains very hight.
Please see video here: https://we.tl/t-0P99jttGJW

**Comment by LeeBamberTGC** [comment]
@saccoforino May have been fixed with the latest update from Steve: https://github.com/TheGameCreators/GameGuruRepo/issues/4810#issuecomment-1657104441
