### ISSUE TITLE
Crouching and walking off a high edge causes the player to fall to the ground instantly. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4795]
If you crouch-walk slowly off a ledge the player will fall down extremely fast compared to normally walking off a ledge. Like the player is instantly magnetized to the ground. 

Here is video showing the difference between a normal walk off a ledge and the bug when crouch walking off a ledge: 
https://youtu.be/QKk8TsR81WA

To reproduce **slowly** crouch walk off a high ledge. I set my move speed to 50 in the video. Everything else is default. 

Very noticeable when testing my levels as I have times where player crouches through vents and narrow areas and is suppose to fall down into a new room from above. This bug has existed since the start of Max I just didn't get around to reporting it :( 

Although extremely rare I have seen this bug happen when crouch walking and coming in contact with a right angles, like the spot where a floor meets a wall where there should be no way the player should be able to pass through them, but the engine instantly tries to pull the player to the ground terrain and pulls the player out of the level completely.

**Comment by MonkeyFrogStudio** [comment]
Could this be related to this one:

https://github.com/TheGameCreators/GameGuruRepo/issues/3285

**Comment by Kitakazi** [comment]
@davetgc Why was this closed this has not been fixed yet?

**Comment by davetgc** [comment]
@Kitakazi - Because it's a duplicate of https://github.com/TheGameCreators/GameGuruRepo/issues/3285

**Comment by Kitakazi** [comment]
@davetgc Ok it's just that issue is from June 2022...
