### ISSUE TITLE
Ai Navigation bug??

### ISSUE THREAD

**Issue by Vadam45** [TheGameCreators/GameGuruRepo#4799]
![1](https://github.com/TheGameCreators/GameGuruRepo/assets/140211115/99a85798-f547-4ef1-8fd8-9cdc57864a2f)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/140211115/1ea5cd11-1262-4192-9a80-5b0f5336ceca)
![3](https://github.com/TheGameCreators/GameGuruRepo/assets/140211115/6ef8e496-f76e-40d1-91e3-54fa42f7f621)
![4](https://github.com/TheGameCreators/GameGuruRepo/assets/140211115/8efc7b3e-dad4-4e98-a259-debc79a51a05)

If the doors are closed, the AI ​​navigation error will stick, if the doors are open, everything runs without problems

Bug?

**Comment by LeeBamberTGC** [comment]
@Vadam45 Chec,k out the latest EXP build, a new nav mesh blocker system is used that avoids switching off nav mesh polys.

**Comment by Vadam45** [comment]
Yes works!  And you other Gameguru max user can make this

Door script in your folder and on line 121 ( Code ) --- The default number is 30 but I am changing this to 5, see image
https://ibb.co/1dtZ7fd   

result https://ibb.co/rFLwxnR

Standart settings with number 30  https://ibb.co/Gd3KL9f

**Comment by Vadam45** [comment]
Thanks for you work! ❤️

**Comment by LeeBamberTGC** [comment]
@Vadam45 No worries, let me know if you spot any other nav mesh related issues as you work on your game :)
