### ISSUE TITLE
Character Creator - Material Index Issue

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#48]
Build: Public Preview

If you shoot the head of a character created with the Character Creator, sparks will admit as if you are shooting something metallic. It seems the incorrect material index is being assigned for the head limb of these generated characters.

**Comment by Duchenkuke** [comment]
lol yea. noticed that too.  even a metallic sound plays.

**Comment by Teabone3** [comment]
Maybe all the characters are really androids/synths

**Comment by LeeBamberTGC** [comment]
They won't be synths in the next build, decal is now influenced by the materialindex of the character entity.
