### ISSUE TITLE
Smart Groups rotating on map save

### ISSUE THREAD

**Issue by XTCTOM** [TheGameCreators/GameGuruRepo#4801]
I made a tunnel group out of "Crates - Box" and "Rock brown2". Saving the smart group and adding it to map is fine but after saving the map and reloading the map all of the previously placed smart groups are rotated. There doesn't seem to be a way to rotate the smart group in X or Z either.

![smartgroup_rotation_bug](https://github.com/TheGameCreators/GameGuruRepo/assets/139570511/067dc59a-6bca-489a-a8db-effd2e7e9687)

**Comment by LeeBamberTGC** [comment]
@XTCTOM Can you email me (lee@thegamecreators.com) the smart object you created and the level shown above, I can then see how the saved smart objects are not holding their rotation in the latest EXP build.

**Comment by XTCTOM** [comment]
Fixed in latest build. Thanks Lee.
