### ISSUE TITLE
Problem with alpha channel materials importing a new character

### ISSUE THREAD

**Issue by saccoforino** [TheGameCreators/GameGuruRepo#4803]
Hi,
I think this is a bug.
I explain you all the process:
1) I realized a character in Reallusione Character Creator 4, customizing armature and exporting it for Blender;
2) Materials are 2: one for body and eyelash; one for hair with alpha channel;
3) in Blender I fused all meshes inone and I selected eyelash crating a specific material (the same of body but using alpha channel for transparency);
4) I exported in FBX;

Now problems:
1) in Max the names of material slots are different and I can't understand why;
2) body material is OK, but eyelash and hair materials have problem with opacity and alpha channel impossible to fix.

I send you a video: https://we.tl/t-jvJdZNZUmE and all the assets to reproduce my work: https://we.tl/t-HUWU6rDzM0

Please, can you solve this problem or fix the bug?
Thanx.

**Comment by LeeBamberTGC** [comment]
@saccoforino Can you try using the EXP build (latest one) and see if you can recreate my settings for the eyelashes, I can get them double sided transparent and they look fine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/008fa927-5c5c-4823-93e1-860856c73d08)

**Comment by LeeBamberTGC** [comment]
@saccoforino Can you provide me with an FBX that has some animations inside. The lisa model with the geometry has no animation data, just a custom CC rig:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0ee25eb7-b374-47d2-87e1-c4a403246e58)

**Comment by saccoforino** [comment]
I tried just now. I restarted my PC and… solved!!! Why? I don’t know.Thank you so much!  Distinti saluti.Andrea CoppolaArchitect3D Artist3D Art Professor c/o Link Campus University - Rome3D Art Professor c/o Vigamus AcademyBlender Foundation Certified Trainer (BFCT)Blender Italia Association Certified Trainer (BIACT)Reallusion Certified TrainerDEEZL Founder (www.deezl.net)CG ACADEMY Founder (www.cgacademy.it) Da: Lee BamberInviato: lunedì 24 luglio 2023 21:15A: TheGameCreators/GameGuruRepoCc: saccoforino; MentionOggetto: Re: [TheGameCreators/GameGuruRepo] Problem with alpha channel materials importing a new character (Issue ***@***.*** Can you try using the EXP build (latest one) and see if you can recreate my settings for the eyelashes, I can get them double sided transparent and they look fine:—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
