### ISSUE TITLE
GG Classic - Character Creator - Color Tinting Attachements doesn't work right

### ISSUE THREAD

**Issue by DarinM1967** [TheGameCreators/GameGuruRepo#4805]
Using June 2023 update.  Open Character Creator, add head attachment, changed color tint of Head Attachment, Skin, Upper and Lower Attachments, assign weapon, save character.  Go into Entities in Left Toolbar, click "add new entity" then when Entity window opens, click the "+" to expand "user", then "+" next to "character creator, in the new Left Toolbar.  You should see your newly saved custom character with the right color tinting on it's "Head Attachment", "Skin", and "Upper Attachment".  Click to select them, then click the "Ok" button and place them on your level.  When you do that most of the time the custom character's color tints will revert back to default, save for their skin and "Head Attachment."  I have tested it numerous times with randomly created different levels and once in a while the custom colors stick, but most of the time they done.  Also facial tinting is still messed up, in that they are way, way too light. Probably due to how high the lighting on each hair is set in the texture.  I reported this issue on the Unofficial Discord if anyone wants to look at the screen shots. ![CharacterCreator02.jpg](https://github.com/TheGameCreators/GameGuruRepo/assets/6035850/289df381-f52e-448c-8ca1-0afbfe63ef06)

![CharacterCreator01.jpg](https://github.com/TheGameCreators/GameGuruRepo/assets/6035850/3e5fdc70-47c6-4e8c-8d04-7ef143597ab1)

**Comment by davetgc** [comment]
It would help if you could also post the screenshots here please.

**Comment by DarinM1967** [comment]
> It would help if you could also post the screenshots here please.

Just updated my original report with screen shots.  Hope they help.

**Comment by LeeBamberTGC** [comment]
@DarinM1967 Fixed for next BETA:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/3c12c7ed-26d2-498a-ae78-224e44001fdb)

**Comment by DarinM1967** [comment]
Wow! Thanks!  I'm sure once it's updated to main version, lot's of people
will be so happy.  Thanks again!
