### ISSUE TITLE
MAX - Health items collected from a container/vendor don't always work properly

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#4808]
If you set up an item using the default "health.lua" behavior, mark it collectible, and put it in a chest or vendor inventory, it will not always work properly when "Use" is pressed in the inventory.

Sometimes it'll work as expected; you press "Use" and you gain health. Sometimes "Use" does nothing, but dropping the item instead will strangely give you some health. Other times, neither work, and when dropping it, it'll just be deleted from existence and be wasted.

I've tried seeing if this was something about the physical item being too far from the container and the behavior "sleeping", so I tried ticking "always active" to see if that helps, but to no avail.

**Comment by LeeBamberTGC** [comment]
@fearlesswee Can you create a small stock media FPM level that I can load and run, then pick something up and USE it to see it not work, thanks!

**Comment by fearlesswee** [comment]
[HealthBugLevel.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12329730/HealthBugLevel.zip)

@LeeBamberTGC Yup! Sorry it took me a hot minute to get back to this.

To replicate, load the test game, open the chest, and retrieve the healing item, and try to use it directly from the inventory. This has a seemingly random chance to work, or not work, or sometimes not work when "used" is pressed, but strangely work when "drop" is pressed instead. You may need to exit and restart the test game multiple times to get it to occur, due to it seeming somewhat random.

**Comment by fearlesswee** [comment]
Quick test reveals that healing items retrieved from containers and/or vendors are working consistently now. Closing as "fixed" :)
