### ISSUE TITLE
Deformation Problems when using blender rig for FULL characters

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#4819]
the new blender MAX rig works perfectly when creating parts for the character creator, no issues there. However, every.single.time ive tried to uses the full skeleton to rig a full character rather than parts, i get the same off deformations in the same places on the NPC

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/82544140/b6efdd10-58b8-4748-8ee2-e599c8a96f1e)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/82544140/5cbc593f-dc87-47b8-8094-96dcb1691589)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/82544140/13fa0f9b-1628-4de5-994d-5f9c4c46a098)

It doesnt matter what character mesh i use, whether its high or low poly , whether the rig is completely hidden or parts show thorugh the mesh etc, but every time i try to add a full NPC this happens in the same places.

I presume im rigging it incorrectly, but wondered if @bond1mjb might have some pointers

Thank you in advance

**Comment by bond1mjb** [comment]
@mav3r1ck198-1   This looks like a skin-weighting issue to me.   While I have never skinned a character in Blender,  I presume it has very similar tools to 3ds Max - things like visualizing the weights, adjusting envelopes, weight-painting, etc.   I think you just need to dig in to some of Blender's skinning tools and fine tune the weighting.   Sorry I can't help more but Blender uses an entirely different workflow for skinning compared to 3ds Max, although the overall concepts are the same.

https://github.com/TheGameCreators/GameGuruRepo/assets/87768878/0238ba33-d037-4e26-873a-76dd75c2f836
