### ISSUE TITLE
GG Max - EXP BUILD - Why in the live stream for JULY did Lee mention only 6 HIGH bugs remain when my own list of HIGH bugs is more than 6

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4820]
@LeeBamberTGC As the title says, IN the live stream last night you mentioned that only 6 HIGH bugs remained for Max.
Clearly that count is wrong. I just checked my Bug list for the HIGH and i have 8 still OPEN. 
7 of which did not even show in that list you had on the Live Stream.
I have not reported ANY bugs now for ages as i had been waiting for you to catch up with my previously reported bugs, which to me now seems like they will not be getting fixed as they did not even show up in your List of HIGH bugs.

The RED Circled HIGH bug is marked as Fixed, but it is NOT fixed currently.

![Untitled](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/d931f4ab-4bc8-40df-a775-ead60096be1f)

**Comment by Kitakazi** [comment]
I agree it does seem strange that his internal list of "High" bugs is different than the bugs labeled High for the public but the bug fixing isn't going to just end for all of Max. That's just his internal list of bugs he's working on. If you think your bug(s) really need to be focused on maybe bump your report.  
I think I can say your standalone bug and maybe even the save game/ load game will possibly be fixed when the Projects feature is finished. Which it should hopefully fix a lot of other bugs and issues when that comes out.

**Comment by synchromesh62** [comment]
> @LeeBamberTGC As the title says, IN the live stream last night you mentioned that only 6 HIGH bugs remained for Max. Clearly that count is wrong. I just checked my Bug list for the HIGH and i have 8 still OPEN. 7 of which did not even show in that list you had on the Live Stream. I have not reported ANY bugs now for ages as i had been waiting for you to catch up with my previously reported bugs, which to me now seems like they will not be getting fixed as they did not even show up in your List of HIGH bugs.
> 
> The RED Circled HIGH bug is marked as Fixed, but it is NOT fixed currently.
> 
> ![Untitled](https://user-images.githubusercontent.com/66874403/256525473-d931f4ab-4bc8-40df-a775-ead60096be1f.png)
Many of these were marked as **fixed but need conformation**  but we didnt get the update till later last night 
Lee labels them fixed quite often before the update goes out.
Have you tried it today ?

**Comment by Tum1370** [comment]
These are not fixed, and not labeled as fixed.

**Comment by MonkeyFrogStudio** [comment]
He may have fixed the nav mesh one, but it may not be in the latest experimental build yet. Just guessing.

**Comment by LeeBamberTGC** [comment]
@Tum1370 The explanation is my filters, like so:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a79a15ec-436c-4b95-b60e-a48d6a663569)

I have added the missing MAX tags to all remaining HIGH bugs reported:
https://github.com/TheGameCreators/GameGuruRepo/issues?q=is%3Aopen+is%3Aissue+label%3Abug+label%3AHigh+-label%3A%22Fixed+but+need+confirmation.%22+

**Comment by Tum1370** [comment]
@LeeBamberTGC Thanks Lee for adjusting the tags on some of the high issue.
