### ISSUE TITLE
GameGuru MAX crashes after saving

### ISSUE THREAD

**Issue by xphilq** [TheGameCreators/GameGuruRepo#4822]
i save my project after about every third object. Sometimes the last three or two objects just aren't there anymore as if I never placed them. and since about 5 min now GameGuru Max crashes after every save.

pls help.

:)

**Comment by davetgc** [comment]
Please post your system specs. Is this a new issue for you, or has it happened since your started using MAX?

**Comment by PhilPK1** [comment]
I've only had this problem since 2 or 3 days.

**My System specs:**

**graphic card**: RTX 2060 _12GB VRAM_
**processor**: AMD Ryzen 5 2600
**RAM:** 16GB DDR4 _3200ghz_

**operating system**: _WIN 11 pro_
