### ISSUE TITLE
MAX: Building editor textures are upside down

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#4823]
The walls in the building editor are upside down. I noticed this when using a wood and plaster wall texture. The bottom of the texture should be wooden panels, the top should be plaster. But when you paint walls with it, the bottom is plaster whilst the top is panels.
[https://youtu.be/PVmwjmv6u7k](https://youtu.be/PVmwjmv6u7k)

**Comment by LeeBamberTGC** [comment]
@AvengingEagle Fixed for next EXP build :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/68666a98-0569-4474-9aaf-9586270c9e73)

**Comment by AvengingEagle** [comment]
This appears to be fixed now. Thanks!
