### ISSUE TITLE
Allies follow the player but don't attack enemies.

### ISSUE THREAD

**Issue by cdeweyh** [TheGameCreators/GameGuruRepo#4825]
I've tried it multiple ways but allies just stand around. Suggestions on what I may be doing wrong.

**Comment by davetgc** [comment]
Are you able to post an image of the character settings please, and ideally a small video of what's happening.

**Comment by cdeweyh** [comment]
First let me say thank you for responding so quickly. I appreciate any help you can give me. 
Let me know if this works for you, or I can try something else.

[](https://drive.google.com/file/d/1D0hILg1uUFot50O2vqwPIOPe9jixQyvA/view?usp=sharing)

**Comment by cdeweyh** [comment]
https://drive.google.com/file/d/1D0hILg1uUFot50O2vqwPIOPe9jixQyvA/view?usp=sharing
