### ISSUE TITLE
GameGuru MAX - MAX Object Guide PDF - Incorrect Information

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4829]
The MAX Object Guide PDF states the following:

![sealed](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/a1e66e7b-e681-4741-9bed-63bd466b6f90)

This is not correct. You can certainly use objects that are not sealed in MAX. In fact, there is this image in the guide:

![sealed2](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/5b82bc76-5d5f-4618-9e75-569b97562158)

This is supposed to be an example of an unsealed object. However, that object will work perfectly well in MAX. If, for example, that was a step, then if you put wall objects on either side, it would look just fine and look fine, too. Even without wall objects on either side, it would work as intended in MAX. 

The guide says this is necessary for MAX's collision system (to close objects), but that's not true, either. It won't matter which collision type you choose (box, sphere, polygonal, etc.), it will work, even if an object is open. 

Shadows will work correctly, too, depending on how the object is used. For example, if that example piece shown in the guide is used as steps with wall pieces on either side, then shadows will definitely get cast on the steps without an issue. 

This section needs to really be changed or removed from the guide.

**Comment by bond1mjb** [comment]
@MonkeyFrogStudio The reason for sealed meshes came late in development when some cliff models were not casting shadows correctly when the light source came from the backside.  I was tasked with sealing these models.     So the reason for sealed meshes is primarily correct shadow casting. 

Here are two pics showing the problem.  It might not be a problem with smaller models that get sealed automatically when they are surrounded by other geometry, but larger outdoor models can case a problem when the light direction is coming through the unsealed side.
![clifffront](https://github.com/TheGameCreators/GameGuruRepo/assets/87768878/039c9195-984f-4158-bc93-6292cb897a5b)
![cliffback](https://github.com/TheGameCreators/GameGuruRepo/assets/87768878/96247bda-372e-4ec6-88c9-35c4c2b142aa)

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb,

As stated in my OP - "Shadows will work correctly, too, _**depending on how the object is used**_."

If, for example, I am creating an interior only level, my wall parts do not need to be sealed. They can be open on both the bottom and top, if I want them to. Once I place in ceiling and floor pieces, and once I set up lighting inside the interior, everything will light and shadow correctly. 

However, the other part is not correct. Unsealed objects do not affect collision negatively.

**Comment by MonkeyFrogStudio** [comment]
Here's a simple example:

![seal3](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/7aa78480-eea6-4f8b-995c-4c12ba93bea9)

You can see two basic cubes, both casting nice shadows. However, the one on the right is not sealed as the bottom is missing. The one on the left is sealed. 

From the back side:

![seal4](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/82ea03c1-4e83-446c-ba06-1f72f771a5b8)

So, the unsealed object works fine in MAX in this case, even outdoors, because it has a top and all the sides. The bottom doesn't matter here due to the sun and the cubes being on the ground. So, objects don't need to be sealed (again, depending on how the object is used).
