### ISSUE TITLE
'Grenade' Weapon Is Not Damaging Characters or Entities. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4830]
Equip the Frag Grenade weapon and throw at a character. It will not damage them at all. It doesn't do any damage to characters or other entities.

**Comment by davetgc** [comment]
I think this is intermittent, as I've noticed it with explosions in general.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you attach a small FPM using stock media ready to reproduce, thanks!

**Comment by Kitakazi** [comment]
Done
[grenadetest.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12233217/grenadetest.zip)

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for next EXP build

**Comment by JCLEONITA** [comment]
i tested with my own grenade and zombie are correctly damaged
https://streamable.com/dkd7du

**Comment by LeeBamberTGC** [comment]
@JCLEONITA If the object can pre-calc visibility such as an immobile exploding barrel and the like, it will work. If there is some doubt as to the positions, it would not work out if damage was warrantied. An extra line of sight check in the new EXP build resolves this :)

**Comment by Kitakazi** [comment]
Thank you, closing as this is fixed.

**Comment by JCLEONITA** [comment]
> @JCLEONITA If the object can pre-calc visibility such as an immobile exploding barrel and the like, it will work. If there is some doubt as to the positions, it would not work out if damage was warrantied. An extra line of sight check in the new EXP build resolves this :)

ah.. ok cool... glad to know.. thanks Lee ..
