### ISSUE TITLE
Drag and Drop Entity enabled using CTRL+Click to select multiple entities does not work if there are other entities behind or near the one you are clicking.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4831]
If you have these options selected in the settings, 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/d9fcfe4e-51ca-4be5-b0c1-c8635847fc85)

it is impossible to select multiple entities unless the entities you are trying to CTRL+Click unless you have the terrain or the sky directly behind them. If any other entities are behind the one you are trying to select it will not work.
https://youtu.be/ByzJU_YAXHY

In the video I'm trying to select multiple objects the entire time by holding ctrl+clicking.

**Comment by davetgc** [comment]
Is this related to this issue? #4786

**Comment by MonkeyFrogStudio** [comment]
I've getting same behavior on my end. If there is anything beneath or behind, then you simply can't multi-select via CTRL+Click.
