### ISSUE TITLE
Water hader Lua functions misspelled

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4834]
The global Lua functions GetWaterTransparancy( ) and SetWaterTransparancy( ) are misspelled. This will cause confusion if/when people like me try to use them. They should be spelled GetWaterTranspar**e**ncy( ) and SetWaterTranspar**e**ncy( ). All other transparency functions have the propper spellings.

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Fixed for next EXP build.

**Comment by TenebreGaming** [comment]
LOL. I just noticed that I misspelled "Shader" in the title. It looks good now.
