### ISSUE TITLE
GAMEGURU MAX crash when click on purchased items into the Add panel of the editor

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#4835]
After i downloaded some items i purchased on TGC store trought Max Downlaoder every time i click on "purchased" field Max Crashes

Made steam check files but the problem persist

**Comment by davetgc** [comment]
Hi,

I'm not seeing this issue. It sounds like an issue with one of the assets you have purchased. Do you have a list of those assets please?
