### ISSUE TITLE
GG Max - Weird building wall texture issue in Standalone Game

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#4836]
I've got weird dark stripes on the walls created in Building Editor. It uses custom textures ("03_fiber-textured-wall1", link to my texture folder - https://drive.google.com/file/d/1zrx9oilHzWvIlaCIPcBrmoaMpxDRd9mz/view?usp=sharing). It does appear only in my bigger project (a few unfinished levels, but rendering it took some time). Most of them disappear after getting into graphics options (I don't know why). In the editor, everything looks ok.  When I try to replicate it on a small level and save it as a standalone it doesn't happen. I didn't show much on video but those stripes are everywhere. 

https://youtu.be/q2FTE5XUlIE

**Comment by davetgc** [comment]
Hi,

Can you please post your system specs.

**Comment by NewWave2137** [comment]
@davetgc  Windows 10 64bit, Geforce GTX 1650, Intel Core i5-9300H, 20 GB RAM DDR4

**Comment by LeeBamberTGC** [comment]
@NewWave2137 Created a new building after pointing to your custom textures, added a door then exported to MAX. Created a standalone from it then ran, I saw no seam in the wall. Can you do the same (attached my level) and see if you see it at your end:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8a9b1219-c949-4fd5-958d-128ea80ced89)

I have attached the level I used to make the standalone
[BADTEXTUREONBE.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13257286/BADTEXTUREONBE.zip)

I have also attached the building I made which needs to go to the "GameGuruApps\GameGuruMAX\Files\entitybank\User\buildingeditor" folder
[newtextureshere_smartchild.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13257291/newtextureshere_smartchild.zip)
