### ISSUE TITLE
Bug: Always active

### ISSUE THREAD

**Issue by Snake675** [TheGameCreators/GameGuruRepo#4837]
Hi

When an enemy has "Show at start" unchecked and "Always active" checked: When player gets in sight, NPC begins to attack while he is invisible. The weapon of the NPC is visible, shoots at player and does move forward and backwards in a funny way. When "Always active" is unchecked everything is ok.

Build: 2023.08.01

Best, FlyingKiwi

**Comment by TenebreGaming** [comment]
I haven't played around with this much myself, but I did notice that leaving them always active but not showing at start, they would still trigger sound effects. I do think that it should be more "Activate at Start" feature.
