### ISSUE TITLE
apbr_core bug

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#484]
Had this after the latest 144mb update yesterday, 30/01/19

apbr_core.fx(1253.15): warning X3206: implicit truncation of vector type. Task manager to quit GG only.

**Comment by plemsoft** [comment]
Just tried this with the latest release and did not have any issues, are you using the Beta ?

FYI: apbr_core.fx has not been updated for month.

@GameGuruEvan perhaps we could have some TAGS that people can use when they create a issue, to set what GG version this is about , would make it more simple to debug and see if this has already been fixed, im sure there are some issues in here that are from people still using the DX9 version or the Beta so ...

**Comment by plemsoft** [comment]
@tarkus1971 Thanks for reporting this,

Found it. Fixed from the next updated :)

At some point normals was changed to use float3 , so some settings.fx could trigger this.
