### ISSUE TITLE
Position, Rotating and Scaling Menu is Busted. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4840]
Open a level and select an entity. Now select a new entity, the options under the Object Tools to Position, Rotate and Scale will  be greyed out for **all** entities on the level. Only the very first entity selected will function as normal. Every other entity on the map will be greyed out. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/6396229a-a1da-4f08-ba92-9c78073739d9)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/1ff48b0e-7291-4981-a360-e774d85578cd)

**Comment by synchromesh62** [comment]
Tested and confirmed 
Even on a new map only the last item placed can be adjusted .. 
All the others grey out.

**Comment by MonkeyFrogStudio** [comment]
Happening here as well.

**Comment by AvengingEagle** [comment]
And here!

**Comment by fearlesswee** [comment]
Getting this here as well.

**Comment by synchromesh62** [comment]
> 

I know it does not solve the problem but just in case you havent tried ..
the R key still rotates and the scaling widget F4 still works .. May get you out of trouble for now :)

**Comment by Kitakazi** [comment]
Seems to be fixed now, closed.

**Comment by Kitakazi** [comment]
Just kidding... it was gone for about 5 minutes then came back and seems to be back permanently.

**Comment by DarthPickles666** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/101579658/9fffb872-b54f-425b-ab26-6e563fe929b1)

Yep, getting it here too, hasnt worked for the last week

**Comment by LeeBamberTGC** [comment]
@Kitakazi Check latest build and load the SWITCH ESCAPE and click a few objects in the first room, do you see them grey out (except the start marker which is supposed to grey out):
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/9e42ef46-62f1-41b5-a628-23360be157f3)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2c87766b-2884-4ff5-9d14-28091fae92ea)

**Comment by Kitakazi** [comment]
Yea everything seems to work fine in the Switch Escape.

**Comment by DarthPickles666** [comment]
Been away from Max for a week... Come back and it's still broken. Works fine on new maps. Broken as hell on everything else. 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/101579658/bc4977dd-3ba8-46be-b120-d79358f9f88b)

**Comment by LeeBamberTGC** [comment]
@Kitakazi @DarthPickles666 It seems the corruption caused by some copy/paste activity propagated waypoint zone references into non zones causing objects to behave like zones for the purpose of orientation. I have added code to the new EXP build that scans all objects after the waypoint load and cleans up non zones and zones alike, removing invalid zones and repairing corrupted objects. 

@Kitakazi The fix worked with the test 1.fpm objects, though the level itself (i.e. the terrain) seemed to have corruption also.  Do you have an earlier version of the "test.1.zip" perhaps, and can you confirm you also see a strange mess when looking at the level:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/04520469-9c05-4222-a746-fe46866d548c)

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Hi test 1.fpm seems to be fixed on my end. I do not have any of the corruption of the terrain that you are experiencing, however a user reported in another discord channel that same issue that had happened to his terrain. When he sent his level to other users they could not reproduce it and his levels were opening fine for them. So that may be a separate issue entirely. 

I do not have an earlier version of test 1. I just use that fpm for random testing I do ever back it up or anything.

**Comment by Kitakazi** [comment]
Actually maybe this is fixed now. I swear when I first went to test it I saw the bug but I cannot get it to happen anymore. :)

**Comment by Kitakazi** [comment]
I'm goin to wait a few days before closing, seems to be fixed as of now though.

**Comment by TenebreGaming** [comment]
After the initial fix was released, it corrected it for new entities but any level that had been worked on and saved prior to that still didn't work, even if resaved. Everything appears good now in all my files. I think the recent fix did its job!
