### ISSUE TITLE
GGMax EXP Build - Planar Reflection Doesn't Work, SSR is weird mess 

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#4843]
https://youtu.be/dcr9gXT52us

**Comment by synchromesh62** [comment]
You also need to set them as transparent.

**Comment by NewWave2137** [comment]
Few months later - it's still happening. My specs - Geforce GTX 1650, Intel Core i5 9300H, 20GB RAM DDR4.
