### ISSUE TITLE
Object library Search Crash bug

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#4844]
I'm experiencing  weird bug in max since everytime i open the object library and start t odigit to search something , max crashes..

all is fine if i go t osearch manually the object  in the subfolders ,as you can see in the video, but ifi try to search something typing in the search bar .max crashes

https://streamable.com/tzi2c0

[https://streamable.com/tzi2c0](url)

**Comment by MonkeyFrogStudio** [comment]
Hmmm ... I'm on the latest experimental build and can search fine using the search bar in the object library. Even using "T" gives me no issues on my end.

**Comment by JCLEONITA** [comment]
i dont know.. i added several imported asset on my max installation, mostly GG classic weapons nothing more.. but i dont think it's related to this..

**Comment by davetgc** [comment]
This is likely related to 3rd party models. Do you have a lot of non TGC media installed?

**Comment by mk831940** [comment]
I click to add assets, and while scrolling through (Scenery), Max crashes. It is as if I'm scrolling to fast, but that's not the case, I can scroll slow and it still crashes. I'm on the exp build. I do verify the random crash problem.
