### ISSUE TITLE
GG max bug

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4846]
the object panel optoins to stretch and rotate is disappearing.

https://github.com/TheGameCreators/GameGuruRepo/assets/109030026/739038c6-2f4b-40db-a3ca-f0891de2e1b1

**Comment by MonkeyFrogStudio** [comment]
Already reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/4840

Please do a search to see if already reported before posting a bug or request to help keep clutter down. Thanks. :)

**Comment by davetgc** [comment]
Closed as a duplicate
