### ISSUE TITLE
MAX - Storyboard "Go to level" logic for button not working correctly when loading screens are involved

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#4847]
In MAX's storyboard editor, we have the option to set a button to take the player to a specific level, which allows us to create alternative modes/campaigns that the player can choose from the main menu. However, there's a problem I've been running into; if you link this button from the storyboard directly to the level, then pressing the button you'll have the main menu "reload" itself as the loading screen, but you end up in the linked level as expected. 

However, if you then create a new loading screen, link the button to take you to that loading screen, and then link the loading screen to the desired level, pressing the button will instead use the wrong loading screen, and then take you into the standard "level 1" (or whatever you call it) that's tied to the "start new game" button.

Here is my placeholder main menu, with the "SURVIVAL MODE" button having the "go to another level" action selected.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/56294129/36c9ca35-8890-49da-b2d6-75d3574e8b67)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/56294129/a642c1b8-fbe4-4754-8d24-0eb62ac101d3)

Going out of this menu, this is what the storyboard as a whole looks like.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/56294129/86a1b4c7-ee95-49e2-a23c-fad43b6d2349)

You can see the link for "SURVIVAL MODE" is connected to "Loading Screen 2", which is then connected to the "SurvivalMode" level.

However, when doing "test standalone all levels", pressing the "SURVIVAL MODE" button instead brings the player to "Loading Screen" instead of "Loading Screen 2", and then loads them into the main game. (The level "TrulyEmpty")

If I instead bypass this loading screen and just connect to the level directly like so, then it will properly take the player to that level, but will cause the main menu to seemingly re-use itself as a loading screen, which is a bit awkward.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/56294129/d5934d6e-158b-4416-95c2-60642a38ef87)

This does mean it's the right link out of the main menu, since it does get to the proper level when the button is selected (not to mention pressing "NEW CAMPAIGN" will start up the main game properly), just that if this link is connected to a load screen before the desired level, it bugs out and doesn't know where the player should go.

**Comment by Duchenkuke** [comment]
I can confirm that. Have the same issue in my game project. Hoping for a fix rather soon.

**Comment by Duchenkuke** [comment]
> @fearlesswee In next EXP build you can now connect a button to a secondary loading screen and from that secondary loading screen to a level scene, and it will follow that path. Pressing START will reset to the primary loading screen.
awesome, and when can we expect the update?
This feature is mandartory in my standalone testing build.

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Will be uploaded before midnight tonight my time (most likely much sooner) :)

**Comment by Duchenkuke** [comment]
ahh awesome, thanks very much Lee! This really helps

**Comment by Duchenkuke** [comment]
hey Lee, has this fix been added to the EXP build yet ? I didnt get an update

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Should be up, can you send me this screen, thanks:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/dc292c91-9202-4174-b7dc-0aac70dbd53c)

**Comment by Duchenkuke** [comment]
![111](https://github.com/TheGameCreators/GameGuruRepo/assets/35990507/bb00f137-4608-4f62-a940-29a24241cfbd)


I tested it and it works. I replaced the exe in my standalone and that did it. Thanks very much lee :) 
This is really a cool feature!

I can confirm a fix on my side. It does have a small hickup where it loads the level 1 loading screen music but it changes to the right one after 2 seconds.

**Comment by LeeBamberTGC** [comment]
If the sound issue gets gnarly, feel free to post a fresh issue with an easy stock media level and I will attend :)

**Comment by Duchenkuke** [comment]
> If the sound issue gets gnarly, feel free to post a fresh issue with an easy stock media level and I will attend :)

thanks but I think it is something I can cope with. Could easily fix it by just delaying the audio file a bit.

**Comment by fearlesswee** [comment]
After a quick test I can also confirm it's fixed on my end. Thanks a ton Lee :)
