### ISSUE TITLE
Visual Logic Problem

### ISSUE THREAD

**Issue by ockerdave** [TheGameCreators/GameGuruRepo#4849]
Currently, when we activate Visual  Logic, we can hook a particular Key to a particular Door via connecting them one to the other. This is a great visual way of doing things. However, it quickly breaks down if the key and door are far apart, such as the key is on the opposite side of a very large level from the door. After the last two upgrades It has been impossible to drag from the ball over the key to the ball over the door across the quadrangle of the map to connect a key to a door. 
However it does connect and work ok until you get out of the GameGuru Max Software, of course the level is saved before I do this.
However on starting the software again and going into the level the Visual  Logic connection has disappeared. Another weird thing is that Visual  Logic connections to Characters still stay in place, unfortunately this has become very frustrating as no further development of my game can continue till I can open the door to the next section of my level. I have tried every possible way to make this work to no avail.

Many Thanks for your help.

![Connect Door   Key](https://github.com/TheGameCreators/GameGuruRepo/assets/111336007/c1247d7b-8ef9-4a5a-a07e-b0bb854ae904)

**Comment by davetgc** [comment]
While the visual system is useful, it does have limits when objects are far apart.

You can get around this by setting the Use Key panel of the door to the name of the key you want to use. You will find this in the Developer Settings

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/99803873/d8cd7def-1132-4696-9e3c-4401a00175d5)
