### ISSUE TITLE
Custom Slider Bar act Strange GGMAX 

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#4850]
in the video you ll see with the standard slider bar texture( the first gameplay) the health bar corrctly act when player lose health until player die
in the second gameplay with some custom texture.. after a while( after the zombie third attack) the health bar start to act weird and seems to slide to the left..
until exit from the correct position whne player dies

https://streamable.com/zxpb0o

**Comment by LeeBamberTGC** [comment]
@JCLEONITA You are not imagining it :)  Can you email me your two images you used for the health so I can reproduce exactly this issue:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/704fa4e7-012c-4094-b5c7-e3a9038613bb)
