### ISSUE TITLE
bug with behaviours of characters created with character creator

### ISSUE THREAD

**Issue by therickman** [TheGameCreators/GameGuruRepo#4851]
Hello, I am using steam's experimental version 2023.08.06.
I created two characters with character creator. Their behaviour is "get close and speak" and they are set to "neutral"
When I test a scene, they get killed by my allies, i.e Elektra and Jillo who are built-in characters.
The same happens if I change the settings of the created characters to " ally".

If I change the behaviour to "stand idle" or "stand and speak more", this does not happen. ( created neutral characters are not killes by allies )

**Comment by therickman** [comment]
The same problem happens with "stand and speak" behaviour.

**Comment by therickman** [comment]
But the issue also seems to be related to character creator : My created characters behave as expected ( ex  : "wander around", or "walk away") ONLY if they are set to ENEMY. They don't if set to NEUTRAL or ALLY.

**Comment by therickman** [comment]
Also, built-in characters work correctly. If I set Elektra to NEUTRAL with behaviour GET CLOSE AND SPEAK, she does so.

**Comment by LeeBamberTGC** [comment]
@therickman Can you create a small FPM level with stock characters (no custom ones) that show the issue you are having with the latest EXP build?  A recent fix solved the issue of ENEMY vs NEUTRAL selections for characters, but may not have resolved the issue you elude to above.

**Comment by therickman** [comment]
Hello Lee, thank you for your answer and sorry for the delay. In the attached scene, there are three stock characters and one made with character creator. Only the behaviour " get close and speak" works. Behaviours " wander around" and " go away" don't.
[github-test-scene-eric.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13307577/github-test-scene-eric.zip)

Done with latest exp build

Eric

**Comment by LeeBamberTGC** [comment]
@therickman Wander and Walk Away now target the player rather than the enemy which correct their behaviours for your level:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/d2121a2e-a2e6-402a-bba9-9422c79170c4)

In the NEXT EXP build :)

**Comment by therickman** [comment]
Thank you ! I will test and report.

**Comment by therickman** [comment]
Hello again, the behaviours now work correctly for Wander and Walk Away. Thank you for this correction!  BUT something is amiss : if I add an ally to the scene ( see attached file ), the character with "get close and speak" behaviour is treated as an enemy and shot down by the ally.
[github-test-scene-eric-2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13309858/github-test-scene-eric-2.zip)

**Comment by therickman** [comment]
This also happens if a neutral character has the behaviour " stand and speak"...

**Comment by synchromesh62** [comment]
Yes i think every other character is using the enemy code as a baseline at the moment.. 
An ally will help you right through the level to save a hostage .. Then he shoots him when he runs off :)
Shouldnt laugh but it is quite funny to see

**Comment by LeeBamberTGC** [comment]
@therickman I can reproduce for GET CLOSE AND SPEAK, even if the character is set to NEUTRAL or ALLY, they are still targetted:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2521e03d-36a1-4696-9c0c-7d8341a71058)
Fixed for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5eeb7d95-1733-470d-88d1-00c68c8009cb)

**Comment by therickman** [comment]
Hello, thank you very much for this fix. GET CLOSE AND SPEAK now works as intended. 
The remaining behaviour bug I have reported is this thread is this : with STAND  and SPEAK, the character set as neutral doesn't do anything ( but is not shot by the ally ). This happens with a standard character or one created with character creator. They don't speak even if a standard" wav" file has been assigned to them as a parameter of the behaviour.

**Comment by LeeBamberTGC** [comment]
@therickman Fixed for next EXP build.
