### ISSUE TITLE
big white block in the foreground when firing

### ISSUE THREAD

**Issue by therickman** [TheGameCreators/GameGuruRepo#4852]
Hello , 
with the latest experimental build ( 2023.08.6 ) downloaded about an hour ago, a big white block appears in the foreground when firing a weapon, and blocks the view as long as you shoot. It disappears when you stop shooting.

**Comment by MonkeyFrogStudio** [comment]
Not seeing that on my end. Does it happen with all weapons that fire (patrol rifle, etc.)? Or only one or a few?

**Comment by therickman** [comment]
The latest build fixes the problem ; however I notice that : 
- bullets no longer have impacts on the walls ( custom buildings ) , only on the ground.
- there's a new pickup style setting for weapons ( or I never saw it ?) , but if set to accurate, causes freezes. If set to "ranged", works ok.

**Comment by therickman** [comment]
the weapon was " assault rifle"

**Comment by davetgc** [comment]
I'm not seeing this either. Have you tried verifying your Steam build?

**Comment by therickman** [comment]
Hello, the issue is solved. By unchecking the "transparent" setting in the "materials" section of the affected buildings, bullet marks reappeared, although not at each gunshot. 
I had set materials to transparent because my custom buildings' windows rendered better ( they were just white without transparency on ). I think this can be closed.
