### ISSUE TITLE
Saves seem to have been corrupted last update, maps show up distorted.

### ISSUE THREAD

**Issue by Marine38Kilo** [TheGameCreators/GameGuruRepo#4854]
Greetings, was trying to report this glitch where opening any recent save now shows everything in some distortion. 
I've been working on these projects with no issues until the recent update.. sadly all maps show very strange artifacts.

**Comment by mauriegit** [comment]
Hi
I am also experiencing strange issues after the running Aug update this morning, on levels I'm working on, which did not appear before the update last week.

One of my games freezes at certain points, and the characters now shoot and move right through closed doors, even though all physics settings and behaviours are correct,

**Comment by Marine38Kilo** [comment]
I hope they can fix there issues some are having, its game breaking
ofcourse.. Ive got to Classic for a moment and actually found some cool
ideas to work on, sadly max will have to wait until they resolve this..

**Comment by mauriegit** [comment]
Hi

Good luck. I hope you succeed.

I'll stick to Max, even though I now have had to make some  frustrating changes to my levels to compensate for the new bugs.

But at least I got everything sort of in working order again.

Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Marine38Kilo** [comment]
Thank you, here is a new take on Mars in classic, also cineguru is really
nice. https://www.youtube.com/watch?v=plxEW7rO4RI

**Comment by mauriegit** [comment]
Hi
Wow that cinegraphic is stunning.

Enjoy.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by davetgc** [comment]
Hi, can anyone please add some more detail about corrupted levels. A video/screenshots, etc.

**Comment by mauriegit** [comment]
Hi Dave
Thank you. I have already managed to fix most of the issues I had. Don't know about the other user who logged this ticket.

If I pick up anything new I'll send some pics

Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
