### ISSUE TITLE
GameGuru MAX - Request - Weapon Importer

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4855]
This is really me just thinking out loud - but I think it would be nice to have a specific way of importing weapons into MAX. How I see this working is when you import a weapon, it would show you a hand/arm that you could rotate to view from different angles. The weapon would appear also and you'd be able to position the weapon in relation to the hand/arm, orienting it appropriately. The importer would make the proper "connection" so the weapon would get attached to the correct bone of the character armature. Then you could run it through a test, seeing the character run through various animations (sort of like is done in the Character Creator) so you can see your imported weapon "in action". If there are any issues, then the end-user could adjust the position, etc., of the weapon so it works well with MAX's characters and/or with the hands/arms used the for first-person view. 

The idea here is to make this process as simple as possible for those that don't create their own models.

**Comment by JCLEONITA** [comment]
completely support this... really needed feature missing for GG classic and requested from ages..

maybe it's time to repair.. LOL

**Comment by 3coms** [comment]
No gun fan, but yes, totally support the request.
Who knows maybe a cool weapon importer gets me most interested :)
