### ISSUE TITLE
At certain points in map, after changing terrain, you can't paint grass

### ISSUE THREAD

**Issue by UnknowNomad** [TheGameCreators/GameGuruRepo#486]
Reproduction:
1: Load blank map, click test game
2: Change terrain type to any
3: In F9 mode try to paint grass at whole map. At certain point, grass stops being automaticaly rendered
4: If you put Grass distance at anything other that currently (above +-30), grass will show.

If you need video, I will send.

**Comment by GameGuruEvan** [comment]
A video is always useful for diagnosing and replicating issues such as this.

**Comment by UnknowNomad** [comment]
This is the video:
[http://www.mediafire.com/file/uu2v1rw3j4s3add/Guru-MapEditor_2019_01_31_20_37_52_518.avi/file]

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Video and details provided above.

**Comment by LeeBamberTGC** [comment]
I think the bug report was that setting vegetation under 30 caused all grass to disappear which was indeed the case. I have amended the code so even the smallest vegetation slider setting shows some grass, so there is less confusion when painting grass in F9 and not seeing anything.
