### ISSUE TITLE
Create New Behavior button is not available

### ISSUE THREAD

**Issue by Sumantbag1992** [TheGameCreators/GameGuruRepo#4861]
The button to create any new behavior is unavailable and not shown in the behavior library...

**Comment by MonkeyFrogStudio** [comment]
It shows (and works) for me. I'm running the latest experimental build.

**Comment by Sumantbag1992** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/86064843/b7c3de14-1a4d-4b9c-b5bd-e9321356af0c)

but I'm not getting the option...

**Comment by MonkeyFrogStudio** [comment]
And I am:

![new](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/d9175c3c-492e-48e1-bb2b-5383694284cc)

Are you on the latest experimental build? If so, have you tried verifying your installation?

**Comment by Sumantbag1992** [comment]
> 

how to verify the installation ???

**Comment by MonkeyFrogStudio** [comment]
Open Steam and go to your Library where MAX is. Once there, click on the gear icon (toward the right side) and when the dropdown menu appears, select Properties. Once the Properties panel opens, select Installed Files from the left side. In Installed Files, click "Verify integrity of software files". This can take a moment, so let it do it's thing.

**Comment by Sumantbag1992** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/86064843/c8e3969a-8e13-45bc-a892-79357ebe4be6)

Still nothing...

**Comment by MonkeyFrogStudio** [comment]
That's a screen shot of the intro screen letting you know about updates ...

**Comment by Sumantbag1992** [comment]
yes, but I still didn't get the option enabled...

**Comment by Lemuripest93** [comment]
Hmm, i appear to have the same issue as @Sumantbag1992, i also verified the files and... nothing appears, i haven't touched GGM for a few weeks, but i have been consistently updating the program, not sure what's causing this.

![addbehaviormissing](https://github.com/TheGameCreators/GameGuruRepo/assets/104637906/e33a53b8-9db9-45df-a556-ad3d3cb1596b)

**Comment by AmenMoses** [comment]
Does it only appear when you have the *advanced* or *developer* settings selected?

**Comment by Sumantbag1992** [comment]
nope, always the same...

**Comment by davetgc** [comment]
I can't replicate this either. Does anyone else have this issue, or can shed any light?

**Comment by synchromesh62** [comment]
Perfect for me. Really strange ?

**Comment by synchromesh62** [comment]
> nope, always the same...

Mine turns on an off when i have this option ticked in the Developer settings 
worth double checking you have yours enabled.

![settings](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/b194cc17-60a0-4206-bcd5-3c94d479285a)

**Comment by Lemuripest93** [comment]
@synchromesh62 This fixed the problem for me. @Sumantbag1992 please try and tick the option shown above :)

**Comment by Sumantbag1992** [comment]
My problem has also been solved, thank you @synchromesh62...
