### ISSUE TITLE
Object Stuck Under Map

### ISSUE THREAD

**Issue by markybhoyuk** [TheGameCreators/GameGuruRepo#4862]
Hi there, 

I'm working on a project, and one of the objects (a zombie character) has become stuck under the map. 

I've tried to remove it, but I can't select it to remove it.  Is this something you can advise on? 

Thanks, 

Mark

**Comment by MonkeyFrogStudio** [comment]
Under Level Objects (left-top), use the dropdown arrow to expose a menu and select Detailed Object List:

![object](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/3f65f611-2ebb-41c8-9cd2-28ea898912c1)

Then you can work through your list to find your zombie. Clicking your object in the list will select it move the camera to where the object is. Make sure you have the widget (for movement) activated. Then you can move the zombie out from under the ground (or delete him, if you like).

**Comment by markybhoyuk** [comment]
Hi MonkeyFrogStudio, 

Thank you for your response. 

That worked perfectly, thank you for your assistance. 

You learn something new every day :)  

Thanks, 

Mark
