### ISSUE TITLE
I click to add assets, and while scrolling through (Scenery), Max crashes. It is as if I'm scrolling to fast, but that's not the case, I can scroll slow and it still crashes. I'm on the exp build. I do verify the random crash problem. It is TGC assets, stock only items not third party.

### ISSUE THREAD

**Issue by mk831940** [TheGameCreators/GameGuruRepo#4866]
I click to add assets, and while scrolling through (Scenery), Max crashes. It is as if I'm scrolling to fast, but that's not the case, I can scroll slow and it still crashes. I'm on the exp build. I do verify the random crash problem. It is TGC assets, stock only items not third party.

_Originally posted by @mk831940 in https://github.com/TheGameCreators/GameGuruRepo/issues/4844#issuecomment-1683079029_

**Comment by davetgc** [comment]
Can you please supply a video as it will help to know when MAX crashes.

**Comment by mk831940** [comment]
[https://youtu.be/on_HBV4cBrg](url)

**Comment by mk831940** [comment]
https://youtu.be/on_HBV4cBrg
sorry if it's not the best, but hope you get the idea.

**Comment by mk831940** [comment]
I removed all media that does not come with GGM, and the crash is no more.
