### ISSUE TITLE
Custom Weapons and Inventory Issue with Displaying Name/Description

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4868]
Hey I have some custom weapons I've got set up however when I select them in my inventory the global text does not work how it should. 

For example, I have a weapon named Pistol. In the gamecore folder this pistol is located in gamecore/guns/Kita/Pistol.
 When I select it in my inventory HUD screen it should say the "selected:title" on top then on the bottom it should show "selected:description" 
So it should read as the title Pistol and the description should say "A custom made Pistol." 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/41297d43-6c78-43c0-9ed8-77695e166383)

However when I open my inventory and select the pistol, it shows the title and description as being Kita\Pistol.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/ae0e3024-e101-40b1-af81-2a4806524559)

I believe this is because in the entitybank my Pistol.fpe references "isweapon      = Kita\Pistol" which is where it knows to find the pistol in the gamecore>guns folder. 
This issue does not happen with the enhanced weapons nor does it happen with my custom items. Only with weapons which I believe has to do with "isweapon = " because if I change isweapon = Kita\Pistol to just isweapon = Pistol then when I pick up the Pistol it will show in my inventory with the correct title and description. But then I can't actually use it or equip it as a gun because the isweapon = is not pointing to the correct place for the gamecore folder.

**Comment by davetgc** [comment]
Firearms are difficult to make, and it's very likely a mistake in the import. Are you able to supply the weapon to Lee?

**Comment by Kitakazi** [comment]
I don't think this is an import issue at all. I asked Necrym59 about this first and he believed it was a bug and to post this on github. I will email Lee the gun.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for the next EXP build, but for existing game projects you will need to open your "GameGuruApps\GameGuruMAX\Files\projectbank\xxx\collection - items.tsv" file and delete all the weapon entries so a correct entry for weapons can be started for the project.  Also delete "collection - items.ele", it will be reconstructed :)

**Comment by Kitakazi** [comment]
Nice! Closing issues as it is now fixed.
