### ISSUE TITLE
Sound4 is listed twice in the UI

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4870]
I have noticed that Sound4 is listed twice in the Developer Settings tab of the Object Tools in the UI. Changing one automatically changes the other, so one is just redundant and should be removed.

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Fixed for next EXP build.

**Comment by TenebreGaming** [comment]
This is fixed and closed.
