### ISSUE TITLE
Grenades go through the terrain if thrown straight down

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4871]
If you throw a grenade straight down it vanishes through the terrain. Also will go through any floor or entity near your feet. 
https://youtu.be/7PdKobXIJM0

If the grenade is shot as a projectile it will disappear also but radius at which it vanishes is much larger. In the video I'm using a non-stock weapon but the same thing happens if you use a stock weapon and change it to shoot the stock grenade as a projectile. 
https://youtu.be/WPk1ey_uE_I

**Comment by Kitakazi** [comment]
I believe this one has been fixed.

**Comment by Kitakazi** [comment]
Sorry this one isn't fixed, I thought it was but maybe I was wrong or it broke again.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Grenades no longer go through floor for next EXP build.

**Comment by Kitakazi** [comment]
"Can you show me the steps I need to do to "the same thing happens if you use a stock weapon and change it to shoot the stock grenade as a projectile" with only stock assets, thanks!"

Sure, step 1 is to open the Gunspec file of the ak47/assault rifle model. 
Then add this into the gunspec **projectile = enhanced\m67**
then go to a level and select the weapon, you can now shoot grenades.  But shooting near the players feet will cause them to go through the ground/terrain.

**Comment by LeeBamberTGC** [comment]
@Kitakazi I added the line to the gunspec, used the weapon straight down and the grenade stayed on the terrain:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a5dd83c9-f906-4f62-9804-486a4adbc00d)

Can you attach a simple stock level and place the start marker where the grenade goes through the floor, thanks!

**Comment by Kitakazi** [comment]
Hey I think fixing the grenades going through the terrain when thrown fixed the weapons shooting them through the terrain as well. Thanks you!!
