### ISSUE TITLE
Level crashes after loading project then opening level. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4875]
I have a level that I was working on and after the update today whenever I open my project storyboard, then load this level, if I select any entity on the map Max will crash to desktop. I have tried renaming and opening the FPM which did not work. 
The map will open normally and not crash if I open the map only and not load the project file with the HUDs and such. 

I first thought maybe it had to do with issue #4868 but I deleted all collectable items from the level. But when I tried to load the map with the project storyboard it still just crashed to desktop on the first entity I try and select. I also tried creating a new project and then opening the map but had same results. 

Also if I do not open my project and only open the map, if I select an entity and make it collectable once I click the Collectable Settings Max will crash to desktop. 

If I try to save standalone with this level it will crash to desktop.

**Comment by Kitakazi** [comment]
I noticed this too 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/6f82f343-8a06-4a1c-94c8-fff33fb73723)
it shows I have collection items but I have deleted all those from the map and cleared the collection items.tsv folder so I'm not sure why it is showing those or how to clear them.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you zip up the FPM level and the project folder and email me at lee@thegamecreators.com I can then try reproducing the crash, thanks!  Does it happen with any of the HUB demos?

**Comment by Kitakazi** [comment]
@LeeBamberTGC No it does not crash on any of the demo levels. Do you need the entire FPM with all the entities, scripts etc? If so it might take me a while to actually locate every entity. Trying to save the level as a standalone crashes to desktop. Maybe I can try and make a simplified version and see if it still crashes.

**Comment by LeeBamberTGC** [comment]
@Kitakazi You can start by sending me the FPM, and I can follow up with the entities I do not have. Thanks!

**Comment by LeeBamberTGC** [comment]
@Kitakazi I have sent you a detailed email with my findings, and more questions and requests for you.  Once I can get it to crash, we will be half way there :)

**Comment by Kitakazi** [comment]
Sent the remaining files with  instructions on how to reproduce the crash. Hopefully it can be reproduced.

**Comment by LeeBamberTGC** [comment]
@Kitakazi I identified a crash related to corrupt collection item list, and some related code too, and uploaded a new EXP build which allows me to load, run and produce a standalone from the project you sent me.   Let me know if this solves the reported crash, thanks!
