### ISSUE TITLE
Aircraft-Quick save

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#4876]
Hi I've built a flyable Aircraft.
The idea being that after a couple of attempts one could fly across a Lake and land the other side.
However if you crash the plane it doesn't respawn and you're back at the original Airport.
Tried using a checkpoint same result.
I'm guessing that the Checkpoint doesn't save settings.
Any help would be appreciated.

**Comment by MartinCranshaw** [comment]
I am using Necrym's Aircraft Behaviour.

**Comment by Necrym59** [comment]
I will look at it to respawn the plane at its original location after a crash as an option will that do?

**Comment by MartinCranshaw** [comment]
Thanks Necrym. I'll give it a try.

**Comment by davetgc** [comment]
@MartinCranshaw - Is this fixed now?

**Comment by MartinCranshaw** [comment]
Thanks fixed. Plane reloads on re-start in Stand Alone.
