### ISSUE TITLE
Not visible in the inventory

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4881]
ammunition, fuel canister does not create the collection instead the canister does not show up in the inventory

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/a2080022-dc37-46b3-bb47-e37f630bf03a)

selected but cannot be seen

**Comment by davetgc** [comment]
Have you created this as a collectable under collectable settings?

**Comment by SampeyFS** [comment]
yes no inventory

**Comment by LeeBamberTGC** [comment]
@SampeyFS And have you set the behavior to Collect Object?  By default the Jerry Can uses the FUEL script by Necrym:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/848d112e-25da-4e98-bad6-df954c60e93b)
