### ISSUE TITLE
transition between levels

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#4882]
will there be a correct transition between levels? I mean, so that the player can move with the preservation of all the items from level 1 to level 2 and so on.

**Comment by Necrym59** [comment]
Already in there isnt it ??

**Comment by MonkeyFrogStudio** [comment]
From what I recall, this is in and works, but only on a standalone game since you can't really change levels when testing.

**Comment by extremestrategy** [comment]
The inventory will always stick with the player between levels if the Inventory HUD is turned on I believe.

**Comment by davetgc** [comment]
I'm pretty sure this already works, can anyone report if there is a problem?

**Comment by Kitakazi** [comment]
@davetgc 
It doesn't work. If you go to level 1 from level 2 you will have no HUD items in inventory.
