### ISSUE TITLE
Game Guru max Causes Windows 11 x64 Error  (To be solved is important)

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4884]
Name of the application that generated the error: GameGuruMAX.exe, version: 0.0.0, timestamp: 0x64e3e347
Name of the module that generated the error: GameGuruMAX.exe, version: 0.0.0, timestamp: 0x64e3e347
Exception code: 0xc00005
Error offset 0x00000030feba
Process ID that generated the error: 0x0x26D0
Start time of the application that generated the error: 0x0x1D9D5CAF745DD7A
Path to the application that generated the error: D:\SteamGames\steamapps\common\GameGuru MAX\GameGuruMAX.exe
Path to the module that generated the error: D:\SteamGames\steamapps\common\GameGuru MAX\GameGuruMAX.exe
Report ID: 76c5f921-4170-424c-b9dc-3b790cbac5de
Full name of the package that generated the error: 
Application ID related to the package that generated the error:

**Comment by TenebreGaming** [comment]
I've not had any major issues with MAX on Windows 11.  Was the issue at startup or doing something specific?

**Comment by synchromesh62** [comment]
Nor me but @SampeyFS  i see you are showing your work on Discord so is this no longer an issue ?
if its sorted then please close this one

**Comment by davetgc** [comment]
I don't have a W11 machine to test on, so I'll leave this open to see if anyone else has an issue.
