### ISSUE TITLE
GGMAX - Game Saves possible problem

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#4888]
When loading a previously saved game in standalone the level seems to be reset to its initial state not to the state at which the save took place.

**Comment by SampeyFS** [comment]
Both also Max does not save when you do things

**Comment by MartinCranshaw** [comment]
I found that it doesn't save logic, task items etc. Making the Save useless and the game unplayable. Hoping that this will be fixed soon. Cheers and keep up the good work.
