### ISSUE TITLE
fire bug 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4889]
![20230829084627_1](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/71cf77a0-967c-42a5-b431-7ba405098f2f)

the fire has been removed from the start but you can see as you see

**Comment by davetgc** [comment]
Are you saying that once an object is deleted it's still visible?

**Comment by SampeyFS** [comment]
hide the fire at the start you see the osteso

**Comment by OobieDoob-Benoobie** [comment]
> Are you saying that once an object is deleted it's still visible?

He wants to make it so you have to find wood and adding the wood resource to the empty fire, will spawn the fire particle asset into the scene.

**Comment by davetgc** [comment]
Is this issue fixed for you now? You can spawn decals as you can other objects.
