### ISSUE TITLE
CINE GURU IN GG MAX

### ISSUE THREAD

**Issue by bruceleebra** [TheGameCreators/GameGuruRepo#4890]
Cine Guru on GG MAX is buggy on some cameras. If the camera is configured to zoom, or move in a certain way, the camera bugs and zooms in another random place or in another totally weird way.

**Comment by Granada1** [comment]
Cine Guru was developed for GG classic, MAX version is still in development 👍

Dave

**Comment by synchromesh62** [comment]
Ye although some things do work its not for Max

**Comment by MonkeyFrogStudio** [comment]
Also, this is the repository for GGMAX and GGClassic. CineGuru is a third-party application. Any issues with CineGuru should be taken up with the actual people developing the software.

**Comment by MonkeyFrogStudio** [comment]
Oh! I apologize, then. I thought it was only sold by the creators. Never mind then. :P

**Comment by AmenMoses** [comment]
Cine|Guru issues should be reported on the Cine|Guru discord as it is not a TGC product.
Also, as has been said it isn't even released for MAX yet!

**Comment by AmenMoses** [comment]
The user guide points to the discord I believe so it's not exactly a secret.

**Comment by davetgc** [comment]
Closed as not a MAX or Classic Issue.
