### ISSUE TITLE
Terrain editor undo is broken

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4894]
I can make a video if you need me to, but this is highly reproducable.

Generate a random map (I was using a 0.5 km map) and when saving the map, give it a previously unused name (it doesn't seem to happen as often if replacing an existing map.) Do some editing such as flatten and raise terrain. Make a few bumps or something, then attempt to undo it. 

1) the first undo sometimes doesn't do anything at all, sometimes undoes the first action instead of the last, and sometimes undoes someting in a middle step. (this seems random)
2) Sometimes the undo appears to do something random and completely unrelated to what you did (possibly due to it undoing a wrong step).
3) Sometimes rectangular regions get removed from the map.
4) You can sometimes undo more times than actions taken, and this causes the map to be in an invalid state. (this doesn't always happen but happens more often with a fresh map or after loading MAX.)
5) The undo system seems to start working properly after repeated loads of the map (like back out to storyboard and reload map.)

This is a screenshot of (3). Seemingly random rectangular chunks are missing.
![Screenshot 2023-08-30 171524](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/0d281914-0e9b-42d9-b7a9-478843757c31)

This is what it looks like after undoing too many times (when it does it).
![Screenshot 2023-08-30 175519](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/e9a3624e-a022-446f-bfc6-cfa5b027877b)

**Comment by davetgc** [comment]
I've just tested this, and it's working for me. Is anyone else experiencing an issue?

**Comment by extremestrategy** [comment]
@davetgc I am, I had an NPC set to flee upon taking damage phase straight through a closed warehouse door earlier today.

**Comment by extremestrategy** [comment]
I haven't had this in a long time, but I know it used to happen.

**Comment by davetgc** [comment]
I'm closing this for now. If it happens again, please reopen the issue.
