### ISSUE TITLE
transition from level to level

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#4895]
will the correct transition from level to level be added? I noticed that when switching to another level, the flashlight is not saved.

**Comment by MonkeyFrogStudio** [comment]
You already reported this here:

https://github.com/TheGameCreators/GameGuruRepo/issues/4882

No need to open a new thread about it. If you have new information, then post it with the old thread.

**Comment by davetgc** [comment]
Closed as duplicate.
