### ISSUE TITLE
"you can not create more loading screens for this project"

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#4897]
its not letting me make more loading screens

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/3721f5da-9d7e-4b04-8e45-ddfa3c8e86ea)

**Comment by casigus** [comment]
oh fixed it by creating a new project.

**Comment by casigus** [comment]
actually no, this is is still an issue.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/7cd01692-bd92-49a3-ae28-91a0daef688d)

**Comment by davetgc** [comment]
How many screens do you have?

**Comment by casigus** [comment]
49!
