### ISSUE TITLE
Specularity not functioning for PBR and DNIS models properly

### ISSUE THREAD

**Issue by boltactiongaming** [TheGameCreators/GameGuruRepo#490]
Since the november update, it appears that things are failing pretty badly with respect to DNIS and PBR specularity.  Notably if you take a stock GG asset with PBR or DNIS and modify the 'specular' value on the properties tab:

1 --> 100 shows virtually no difference

100+ causes it to get incrementally brighter as a whole vs increasing the specularity actually increasing.   At 200 it gets slightly whiter, at 1000 it becomes very white, and at 10000 it becomes completely white in many cases. It can be easily tested with any model.

Some testing via MikeP - https://www.youtube.com/watch?v=CQvDi3dsZkE&feature=youtu.be

This is completely different than previous iterations of GameGuru where the actual specular map would get shinier.  In this case it doesn't seem to be functioning properly at all. At bare minimum it's extremely inconsistent.

**Comment by plemsoft** [comment]
@boltactiongaming Thanks for reporting this.

Yes its just one of those that now ruin PBR , specular is now defined by roughness and metalness , then when we add per entity specular ( from fpe or from editor per object ) then it add this to the PBR and kind of ruin it.

I would prefer to remove it entirely , but people use it so somehow we must support it.

It got kind of weird when metalness/roughness got part of this and now the values can go above the limits and produce a white look, depending on metalness/roughness.

I will think about it and perhaps just limit the numbers so they cant go white.

But it will always be inconsistent as it depends on the PBR material from the textures so ...

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Preben Previously assigned to himself so no idea if its been improved ?

**Comment by plemsoft** [comment]
@boltactiongaming This has been fixed , and it will now act properly within the PBR shaders.

Really happy with this, you can really make metal shine now :)

100 - Normal:
![specular-normal](https://user-images.githubusercontent.com/18662417/77731308-f1f78f00-7002-11ea-9c73-b244109b7c77.jpg)

500 - Specular:
![specular-500](https://user-images.githubusercontent.com/18662417/77731360-0b004000-7003-11ea-92d5-d7c0e6126a04.jpg)

3000 - Specular:
![specular-3000](https://user-images.githubusercontent.com/18662417/77731383-194e5c00-7003-11ea-9ee4-b5696e72e781.jpg)

Nice shiny metal:
![specular-metal](https://user-images.githubusercontent.com/18662417/77731408-2703e180-7003-11ea-9569-71a57acd19e5.jpg)

**Comment by LeeBamberTGC** [comment]
Confirmed specular now tied to PBR specular code for a more accurate specular effect.
