### ISSUE TITLE
gameguru max not working

### ISSUE THREAD

**Issue by TheunknownK21** [TheGameCreators/GameGuruRepo#4900]
i just got gameguru max from steam but
when i boot up gameguru max it says Path Cannot Be Found
A component of path does not name an existing directory or path is an empty
for 'C:\Program Files (x86)\Steam\steamapps\common\GameGuru
MAX\Files\scriptbank\Community\6704278\core\' (looking in C:\Program Files
(x86)\Steam\steamapps\workshop\content\1247290) and then it crashes i tried reinstalling multiple times but it still says the same thing what can i do?

**Comment by davetgc** [comment]
Hi,

I'm sorry you're having problems. Firstly, could you please post your system specs?

From first glance, it looks like you're not being able to recover the files from Steam workshop, which is where we store all community behaviors.

**Comment by TheunknownK21** [comment]
> Hi,
> 
> I'm sorry you're having problems. Firstly, could you please post your system specs?
> 
> From first glance, it looks like you're not being able to recover the files from Steam workshop, which is where we store all community behaviors.

my system specs:

Processor	12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
Installed RAM	16.0 GB (15.6 GB usable)
Product ID	00342-21060-99020-AAOEM
System type	64-bit operating system, x64-based processor

**Comment by TheunknownK21** [comment]
So?

**Comment by davetgc** [comment]
Are you on Windows 10 or 11?

**Comment by TheunknownK21** [comment]
> Thanks,
> 
> Are you on Windows 10 or 11?
> 
> Can you also please post your graphic card specs.

I'm on windows 11 and graphics card is 
Nvidia GeForce RTX 3050 4GB GDDR6

**Comment by davetgc** [comment]
Thanks. You're within spec, so we'll have to look at other issues. I've referred this issue to our lead developer, in the meantime, has anyone else on W11 experienced this?

**Comment by TheunknownK21** [comment]
> Thanks. You're within spec, so we'll have to look at other issues. I've referred this issue to our lead developer, in the meantime, has anyone else on W11 experienced this?
I didn't see anyone talking about it on the gameguru max steam forum

**Comment by LeeBamberTGC** [comment]
@TheunknownK21 I suspect you are using the latest EXP build which has a bug in it that wipes out the custom writables location. I have uploaded a new EXP build, can you try that and let me know how it goes, thanks!

**Comment by davetgc** [comment]
@TheunknownK21 - Can you confirm that you are using the experimental build, and not the official release (the experimental build has new features and fixes which are available for testing before they are committed to the official release.).

**Comment by TheunknownK21** [comment]
> @TheunknownK21 - Can you confirm that you are using the experimental build, and not the official release (the experimental build has new features and fixes which are available for testing before they are committed to the official release.).

How to download the experimental build?

**Comment by TheunknownK21** [comment]
> @TheunknownK21 - Can you confirm that you are using the experimental build, and not the official release (the experimental build has new features and fixes which are available for testing before they are committed to the official release.).

i download the latest exp and it works!
thanks!

**Comment by davetgc** [comment]
@TheunknownK21 - That's great. Glad it's working for you.
 I'll close this now, but if you have problems again, please feel free to reopen or start a new thread if it's a different issue.
