### ISSUE TITLE
GGmax has lost the link or setup files to show the My Games tab listings... all MY Games have gone missing.

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#4903]
I just loaded the new experimental build ---

1. GGmax loads and shows the Demo Games tab ..
2. It Normally loads and shows the My Games tab..
3. I choose the My Games Tab.. it is empty ... nothing is left..

So GGmax has lost the link or setup files to show the My Games tab listings ...
My writable folders are still there but GGmax has lost the plot...

OK - I went back to the previous good build of GGmax
and loaded up... and all My Games where back...

Then went back to Experimental build...
loaded up and ALL My Games are gone..

**Comment by mk831940** [comment]
me too

**Comment by synchromesh62** [comment]
@thor49 
Is your GameGuruApps in a custom location ?
a couple reported the the update made a default GameGuruApps folder in their docs and max is pointing to that which is empty as it resets the path to default.
But their custom location is still there ... D\ GameGuruApps for example.
If thats the case for you it just needs re-pointing in settings.

**Comment by davetgc** [comment]
Confirmed.  Resetting the location has no effect.

**Comment by mk831940** [comment]
the location of my GGM is default. The writeable files are in the documents folder under Gameguru Apps. All on C: drive.
________________________________

**Comment by LeeBamberTGC** [comment]
@synchromesh62 @davetgc Can you both confirm this in the latest EXP build and also confirm you are both using your own custom writables location, thanks!

**Comment by LeeBamberTGC** [comment]
@thor49 @ALL Found the issue, will be sorted for the next EXP build :)

**Comment by synchromesh62** [comment]
> @synchromesh62 @davetgc Can you both confirm this in the latest EXP build and also confirm you are both using your own custom writables location, thanks!

Mine is default in Docs and no probs this end.
\Documents \ GameGuruApps \ GameGuruMAX \

**Comment by mk831940** [comment]
yes that is where my stuff is at. \Documents \ GameGuruApps \ GameGuruMAX \
________________________________

**Comment by mk831940** [comment]
all good on my end, old maps are still gone, but I uninstalled GGM last night and reinstalled it. Everything is in default directories., it was before too but I thought a reinstall would help.

**Comment by LeeBamberTGC** [comment]
@mk831940 Just uploaded a new EXP build that fixes the issue, which was related to the writables folder not being picked up when MAX starts, causing several different issues, this one and one related to workshop content updating, both resolved.
