### ISSUE TITLE
[Standalone] Trigger zones fail to activate characters

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4908]
Built a small standalone of 4 levels. On level 3 the triggerzones and switches will activate objects but will not spawn characters that have been set to not show at the start. This issue doesn't happen on level 1. This issue doesn't happen in the "Standalone Test All Levels" from the HUD. Only once the standalone is fully built does this issue appear. 

Additionally if I build level 3 as its own standalone these switches and triggerzones work fine. Only levels after w/e the first level is does this appear.

**Comment by Kitakazi** [comment]
Eh not just characters seems trigger zones fail to sometimes activate objects that are set to not show at start as well.

**Comment by OobieDoob-Benoobie** [comment]
yea. This has been one of the most annoying bugs for me. Im trying to get a demo of just a couple levels to compile properly, but they all use spawn and despawn triggers. This is one of the bugs holding me back. Its in the EXP build of max but theres another bug keeping me from being able to switch to public release.
