### ISSUE TITLE
Entity - Chainlink Fence - Animation Issue

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#491]
When you open the chainlink fence and attempt to close it again... as the handle comes down to lock the gate, the whole gate will, for a frame or two, completely disappear and reappear.

**Comment by GameGuruEvan** [comment]
Until next updated, can be resolved by modifying the (Chainlink Fence (Gate).fpe) file to read the following..

;anim
animmax       = 2
anim0         = 0,50
anim1         = 51,99
playanimineditor = 0

**Comment by Teabone3** [comment]
Thanks Evan
