### ISSUE TITLE
[Standalone] Particles created by the user do not showup in standalone games

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4910]
Particles created by the user do not show up in standalone games. This issue doesn't happen in the "Standalone Test All Levels" from the HUD. Only once the standalone is fully built does this issue appear.

**Comment by Kitakazi** [comment]
I also want to add I manually copied over all the files for the particles that were not showing up to see if that would fix as I don't think it copied them over. This did not fix the problem. Particles were located in Particlebank > User. The Standalone files created a User folder but it was empty. So I copied them into it but still didn't show the particles in standalone.

**Comment by OobieDoob-Benoobie** [comment]
I've noticed this as well.

**Comment by Kitakazi** [comment]
Just made a Standalone to test some levels and this is still an issue.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you create a small stock level and save as standalone that shows the particles missing in the export but okay when doing test level, thanks!

**Comment by Kitakazi** [comment]
I can make a small level showing the issue but this only happens with Particles created by the user with the Particle Editor. So it wont be stock a particle.
