### ISSUE TITLE
Add Function to Resource script

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4911]
good day in the script ( Resources ) can you add the spawner of the objects like the Eat script I ask for help xkè I do not know about scripts ( LUA)

**Comment by Necrym59** [comment]
This is because a recourse may not be just a re-growable plant but may be a crystal or some other single use item.
However i will look at puting an an option for respawning.

**Comment by SampeyFS** [comment]
Thank you very much because I need the plants
