### ISSUE TITLE
two malfunctioning scripts

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4912]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/48fac19d-cdd7-40c3-9471-ea08e7b14cf1)

1
this does not work when you are underwater

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/e8b07d6f-6b8f-44ef-934a-47992c85e886)

the second does not work the rage the practice from a distance take the gas can

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/004ca5b5-8dcc-49de-81df-f541f6cb9dca)

**Comment by synchromesh62** [comment]
> ![image](https://user-images.githubusercontent.com/108415264/266833870-48fac19d-cdd7-40c3-9471-ea08e7b14cf1.png)
> 
> 1 this does not work when you are underwater
What does not work when you are **underwater** ?
your pic is above water.

**Comment by SampeyFS** [comment]
yes

**Comment by synchromesh62** [comment]
> yes

You really need to explain your problems in more detail.
I tested it and it worked but still have no idea what your trying to say is wrong ?


https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/92e3b815-0a37-4b22-afe9-7ae81f75d57b

**Comment by Necrym59** [comment]
Water control: 
Control water height when activated by switch linked to an object or a zone.
Attach to an object and set to Physics=ON/OFF. Link to a switch or zone.
or can be also be attached to a zone directly.

**Comment by Necrym59** [comment]
The fuel behavior has been fixed for range!

**Comment by SampeyFS** [comment]
thank you for work you do for us i wanted to ask you the vendor script of the vending machines but the things are free can't you put them for a fee? thank you very much

**Comment by Necrym59** [comment]
Vendor has been updated to use money. Update your workshop items.
If these have all been fixed, please close the issue.

**Comment by SampeyFS** [comment]
thank you friend for everything
