### ISSUE TITLE
Max is not updating to newest Switch Behavior.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4913]
*EDIT* See below. Changed issue title as it was being caused by switch script not updating to newest. 

**Old post 
Enemies walking next to a Switch will trigger the switch even if the switch is set to Single Use. This leads to some pretty frustrating moments as I don't want enemies activating random switches just for being next to them. But the main issues is a switch that is set to Single Use. Because now an enemy can easily lock a player inside a room or elevator or w/e. It is cool that other characters can trigger switches but it would be nice if it was a setting on the switch script itself or something. And they should not be able to trigger a switch that is set to "Single Use" after it has been used....

Video showing how easy it is to get locked in an area >  https://youtu.be/HLzNqVWyF8g?si=1Lj3Q8Q9bIIQeFRc

**Comment by Necrym59** [comment]
Can you be more specific, the option to have an npc activate the switch is in the behavior?
![switch](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/b5ff964f-03b5-4bdf-9dc5-fa08681f3e06)
Make sure you have an updated behavior (from the video you seem to have an older one) , if so and is still a problem. Let me know and i will check it out but i cant seem to replicate the specific scenario.

**Comment by Kitakazi** [comment]
Hmm looks like my switch is not updated and that would explain it. Thanks closing.

**Comment by davetgc** [comment]
Can anyone else confirm scripts not updating?

**Comment by Necrym59** [comment]
I can confirm this, it is using the stock installed one regardless of any workshop updated one. 
An easy test is to copy the workshop core one into your  scriptbank/user  folder and attach that one to a switch. It will the show extra features.

**Comment by Kitakazi** [comment]
My script has updated. Closing this one.
