### ISSUE TITLE
Improve the Change Texture Behavior so you can specify the emissive strength for both texture selections

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4914]
The Change Texture Behavior used to pick up other textures like _emissive textures. But currently it is only picking up the _color texture and no others.

**Comment by LeeBamberTGC** [comment]
@Kitakazi In the latet EXP build I tested, I assigned a new texture set (inc. emissive) to the behaviour and in the game it switched and showed the emissive, but the emissive power was not copied over from the original object:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/29ffcda6-4de2-4ea3-9059-fbd0020ac095)

I have retagged as a feature request to add more controls to the behaviour to set the emissive power when the texture is changed:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/69c52881-c69a-4024-a764-f1333ab577b9)

**Comment by Kitakazi** [comment]
Ah sounds good, thanks.

**Comment by Kitakazi** [comment]
Closing since this has been added.
