### ISSUE TITLE
Carry script  It does not work 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4917]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/2ae7b5b5-2824-41b6-8830-cd5769d747b3)

The script does not work when you approach it does nothing

**Comment by synchromesh62** [comment]
Your pickup range is really low .. set it to about 150 then try again

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/7fa96741-3a81-43ae-bf24-75ad4f919d03)


I have tried but it does not work

**Comment by synchromesh62** [comment]
Are you also setting the weight of the object your picking up below 99 as stated in the description ?
Just tested and working fine here 
Anyone else having a problem ?

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b2c6f13e-2cfa-42af-b0f6-d2e459d740be)

Done see nothing try pass me your lua see if it works

**Comment by synchromesh62** [comment]
No you can leave the slider weight at 99 .. 
If you want to pick up a box for example you must make sure the weight of the box is set below 99 in box's settings.
The Lua script is fine but your not setting it up the item you want to pick up correctly.

**Comment by SampeyFS** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/aa408a15-5329-439b-9ed8-20f53f981373

**Comment by SampeyFS** [comment]
I solved it I found out what was wrong thank you very much friend
