### ISSUE TITLE
Level editor taking up 100% gpu usage and making pc extremley hot

### ISSUE THREAD

**Issue by LightofAlfheim** [TheGameCreators/GameGuruRepo#4919]
I already tried turning down editor graphics and disabling vsync. for refrence I have a Geforce GTX 1650 Super.

**Comment by MonkeyFrogStudio** [comment]
When I run MAX and am moving about in the view port, my GPU usage is about 40%. When doing nothing, it's at 0%. With a very heavy level, I am making out at 60%, but even in the same heavy level, it's normally around 40-45%.

**Comment by davetgc** [comment]
I'm not seeing an massive overuse of the GPU. Does anyone else have a similar issue?

**Comment by LightofAlfheim** [comment]
> I'm not seeing an massive overuse of the GPU. Does anyone else have a similar issue?

not that i know of, no

**Comment by LightofAlfheim** [comment]
my complete list of components:

MODEL 
HP Pavilion Gaming Desktop TG01-0xxx 
SERIAL NUMBER 
2MO0313TWW 
OPERATING SYSTEM 
Microsoft Windows 11 Home 
- Release ID: 2009 
- Version: 10.0.22621 
- Build: 22621 
CPU 
AMD Ryzen 5 3600 6-Core Processor               
- Clock speed: 3593MHz 
- Description: AMD64 Family 23 Model 113 Stepping 0 
GPU 
NVIDIA GeForce GTX 1650 SUPER 
- Refresh rate: 74Hz 
- Driver version: 31.0.15.3713 
RAM 
CT8G4DFRA32A.M4FE 
- Capacity: 8GB 
- Type: DDR4 
- Default clock speed: 3200MHz 
CT8G4DFRA32A.M4FE 
- Capacity: 8GB 
- Type: DDR4 
- Default clock speed: 3200MHz 
AUDIO 
USB Audio Device 
Realtek High Definition Audio 
NVIDIA High Definition Audio 
NVIDIA Virtual Audio Device (Wave Extensible) (WDM) 
Oculus Virtual Audio Device

**Comment by LightofAlfheim** [comment]
> The laptop GTX 1650 super only has 4GB of onboard memory (looked up it's specs to see). That's pretty tiny for today's games. That could be an issue with MAX?

i dont have the pavillion laptop i have the desktop, it seems that i cant find this exact model anymore.

**Comment by MonkeyFrogStudio** [comment]
The desktop version still only has 4GB of VRAM.

**Comment by sirlion87** [comment]
I have the same issue when running MAX on my laptop which is a MSI 11800f, 16GB RAM, GeForce 3070, which is well above what the engine should require. It got so hot in fact that I had to turn it off otherwise the keyboard would stop functioning.

**Comment by Ghost-l0l** [comment]
Maybe it's some issue with mobile GPUs?

 In 2022 I had gaming Asus with Ryzen7 5800H 16gb ram and RTX3070 and had similar issue. After just few minutes in GG Max fans were going close to 100% - it was getting loud and very hot. No other game/program I had was capable of getting that laptop to that heat level that quickly.

 Now I have normal desktop pc with Intel i7 10700k 32gb ram and RTX3070 (yup same card but for desktops) and It doesn't get hot at all. I can keep GPU fan manually set to around 30-35% and it doesn't reach 60 degrees even after 2-3 hours working with Max.

**Comment by sirlion87** [comment]
Yes I have a similar setup and same card (tho soon will be able to test on a 4090) it appears that desktop doesnt get affected.

**Comment by LightofAlfheim** [comment]
soooooooo... is Lee gonna come back to this??? lol

**Comment by MonkeyFrogStudio** [comment]
Patience. Your's isn't the only bug that Lee has to tackle.

**Comment by LightofAlfheim** [comment]
ive done a tad bit more research, and it turns out that , yes, mobile gpu's are the issue. had no problems on my dads old pc, but it seems that mobile gpu's are the only thing affected by this

**Comment by davetgc** [comment]
Thanks for the update. I'm going to close this for now as it is hardware related, and not a problem as such with MAX.

**Comment by SampeyFS** [comment]
Let's say one part heat rightly even a 3060 ti 8 GB heat would need to be fixed updated to the new version of Max's graphics engine
