### ISSUE TITLE
Spelling -  "objext exists"

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#492]
There is a spelling error in the global.lua script file

"GetObjectExist: x=GetObjectExist(obj) -- returns if the specified objext exists"

Object is spelled incorrectly. Should be "object exists" instead of "objxt exists"

**Comment by redagent101** [comment]
updated Global.lua file in my BugFixes_BOTR_June2019 branch.  "objxt exists" is comment text and won't affect functionality
