### ISSUE TITLE
GameGuru MAX - Storyboard issue with HUD screens

### ISSUE THREAD

**Issue by sirlion87** [TheGameCreators/GameGuruRepo#4921]
I currently have 8 Hud screens. Adding another custom Hud screen creates it always as screen number 7 for some reason, no matter what I do, even if the duplicate preview gets removed by entering and exiting the new panel, the number stays the same.
![immagine](https://github.com/TheGameCreators/GameGuruRepo/assets/92697844/1eecd981-8a87-4c97-add2-f7b5446e26ab)

**Comment by LeeBamberTGC** [comment]
@sirlion87 Fixed for next EXP build and will also place the new HUD screen next to the last known HUD for easier location and repositioning
