### ISSUE TITLE
GameGuruMAX - Reflection issues

### ISSUE THREAD

**Issue by sirlion87** [TheGameCreators/GameGuruRepo#4922]
I am using the Puddle model - but this behavior can be observed in any model in my level really - reflections appear distorted and stretched on the surface upon moving the camera around, examples
![immagine](https://github.com/TheGameCreators/GameGuruRepo/assets/92697844/31289d4f-5bf2-4436-913a-b0eb3361a4f3)
![immagine](https://github.com/TheGameCreators/GameGuruRepo/assets/92697844/f6d9efab-deb3-4bbd-8941-1d990a8ea900)
![immagine](https://github.com/TheGameCreators/GameGuruRepo/assets/92697844/688c9dcd-bc7e-406b-a719-b8429eea5d20)
These lines crossing inside the puddle flicker around the surface, this behavior happens on vertical surfaces as well

**Comment by davetgc** [comment]
Have you placed an environment probe near the puddle, this will help with rendering quality.

**Comment by sirlion87** [comment]
Seems like I found the issue. The puddle searches for a non-existent surface file at: 
entitybank\Basement Collection\Decals\Puddle_surface.dds
the Decal folder doesnt exist. Moreover, whenever I want to change file, the Surface field resets and it defaults to a blank space.

**Comment by LeeBamberTGC** [comment]
@sirlion87 Added the mssing puddle_surface.dds for the next EXP build :)  Thanks for the report!
