### ISSUE TITLE
GameGuru MAX - Inventory strings selected:title, selected:description and selected:image not showing up

### ISSUE THREAD

**Issue by sirlion87** [TheGameCreators/GameGuruRepo#4923]
While making an inventory screen - and re-making it again step by step just to be sure its not just that specific screen causing the issue - I found myself unable to see text and image of the selected items in my inventory.
Moreover, switching to a different map for testing, my inventory HUD screen in the storyboard got changed into a blank screen, I had to exit and enter the program again for it to properly register the "old" inventory screen again.

**Comment by sirlion87** [comment]
UPDATE: I believe that the issue is more serious, because I realize now that I cannot select the items at all. So it is not that it cannot detect the strings, more so that it cannot even register clicking on the item's icon.

**Comment by Necrym59** [comment]
Unknown what your talking about however the inventory screens will not work until a slide bar and slider are added
i think this may be your problem

**Comment by sirlion87** [comment]
Okay so let me understand this: adding a slider and a slide bar are both mandatory in order for the inventory screen to work? My inventory has only 8 slots so there is no need for a slide bar.

**Comment by Necrym59** [comment]
Yes you still need it even if you hide it

**Comment by sirlion87** [comment]
Okay I tried it, you were correct, that was the issue. This should be absolutely stated in bold somewhere, it is very confusing and not everyone would need a scrollbar handle for their whole inventory screen to work. Please make it clear. Moreover, there is still the issue of my buttons and text being positioned wrongly (they dont match the preview position in the storyboard) regardless this matter is solved.

**Comment by davetgc** [comment]
I'll close this as completed, but please create a new post for the buttons issue.
