### ISSUE TITLE
Candle does not save color

### ISSUE THREAD

**Issue by Cyllceaux** [TheGameCreators/GameGuruRepo#4926]
I use a candle and changed the color to red.

After reload the project, the light of the candle reset to yellow

**Comment by davetgc** [comment]
Is this just the candle, or all objects?

**Comment by Cyllceaux** [comment]
I recognized it only at candles.

**Comment by LeeBamberTGC** [comment]
@Cyllceaux I added a candle, changed light color to red, saved, exited MAX and relaunched, loaded level and the candle remained red, is this your report?
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2d3297e3-ad92-4ce0-910f-4970cf55db8a)

**Comment by Cyllceaux** [comment]
I did exact the same. The color of the candle resetted to yellow. I tried it a lot of times and it happend every time. It still happend after October Update 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/50920730/8a0a1ec7-c95d-4f7f-8e9f-15e4857d7b37)
It has the right Image, too
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/50920730/3b5b7ada-4d78-4ce0-bbe4-c6005b3e9174)
I create a little movie:

https://github.com/TheGameCreators/GameGuruRepo/assets/50920730/1a9ed210-d2d0-4902-ae21-2ab440a92a25

The jumping candle is another bug.

**Comment by LeeBamberTGC** [comment]
@Cyllceaux Can you attach here the level shown in the video, thanks!

**Comment by Cyllceaux** [comment]
Yes... sure :)
[Schatten.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13259819/Schatten.zip)

It's only for testing at the moment, so there is nothing special

**Comment by LeeBamberTGC** [comment]
@Cyllceaux I will also need the START.FPM level that is located in your writables mapbank folder:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/943947d0-2bdd-4afa-95c9-c4b08c7f4f1f)

**Comment by Cyllceaux** [comment]
I can't upload it. It is 12 MB compressed and the upload from github disallow files bigger than 10MB and other formats

**Comment by LeeBamberTGC** [comment]
@Cyllceaux You can use something like Google Drive to upload then share a public link.
