### ISSUE TITLE
GG MAX weapon bug. exp build

### ISSUE THREAD

**Issue by OobieDoob-Benoobie** [TheGameCreators/GameGuruRepo#4927]
If I put the compact combat rifle and the patrol rifle in any game, OR: both hand guns, (revolver and magnum)
once one is equipped and you shoot an enemy who has one or the other, (eg. you shoot the magnum and kill
an NPC using a revolver or a magnum) Once you pick up the dead NPC's ammo, it resets ALL ammo reserves to zero. 
You then cannot pick up any ammo for any gun you have even if its boxed ammo. You are stuck with
whats in the mag at the time the bug occurs until the weapons are empty and that's all you ever get.

**Comment by OobieDoob-Benoobie** [comment]
After further testing: 
No need to have both guns, just be sure to have the gun your looting the ammo for:

https://www.youtube.com/watch?v=wsf8iMk8CY0&ab_channel=jbirdmax

**Comment by davetgc** [comment]
Please post all issues as separate, and don't combine issues into a single post. Bugs can't be declared as fixed if the issues aren't related.

**Comment by OobieDoob-Benoobie** [comment]
Fair enough. 
Ive seen the compiler bug listed elsewhere.
Just left the gun bug.

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie Sorry about that, fixed in the next EXP build :)

**Comment by OobieDoob-Benoobie** [comment]
Sorry for the delay. 
Seems to be working as intended now. 
Thank You.

**Comment by OobieDoob-Benoobie** [comment]
Confirmed FIXED
