### ISSUE TITLE
Candle with texture problems

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4928]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/aaea6129-ef36-4190-b006-a3e7c418c1d3)

see the candle that to texture problems

**Comment by davetgc** [comment]
Is this default media?

**Comment by SampeyFS** [comment]
yes

**Comment by MonkeyFrogStudio** [comment]
All three stock candle sticks are showing up correctly for me.
