### ISSUE TITLE
GGMax - SetEntityTextureOffset(e,u,v)  in global.lua

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4930]
This might be a question, if its not a typo mistake in global.lua.

on line 2229 we have:

SetEntityTextureScale: SetEntityTextureScale(e,u,v) -- change the texture UV map of an entity to scale it (1.0=no change)
SetEntityTextureOffset: SetEntityTexture**Scale**(e,u,v) -- change the texture UV map of an entity to offset all coordinates (0.0=no change)

Shouldn't it be Offset not scale on that second line? Like so?:

SetEntityTextureScale: SetEntityTextureScale(e,u,v) -- change the texture UV map of an entity to scale it (1.0=no change)
SetEntityTextureOffset: SetEntityTexture**Offset**(e,u,v) -- change the texture UV map of an entity to offset all coordinates (0.0=no change)

**Comment by davetgc** [comment]
Looks like a typo.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Was a typo, thanks for spotting this, fixed for the next EXP build.
