### ISSUE TITLE
GG MAX BUG - Soundzone not working properly

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#4934]
I noticed some issues while working on my game:

the soundzones seem to be on a different location that I originally placed them in the editor
I have a sound for the player flashlight but the flashlight sound only works at the start and doesnt play when the player stands in certain parts of the level.

Same goes for doors, light switches etc

Please look into it and fix it. 
Thank you

**Comment by davetgc** [comment]
Are you saying the zones have moved, or aren't working when you enter them?

**Comment by Duchenkuke** [comment]
They moved and also arent working, its strange to explain
I think it could be easily replicated by placing a few soundzones and assigning sounds

**Comment by LeeBamberTGC** [comment]
@Duchenkuke I added three zones, assigned different sounds, they all worked in test level, thewn saved and reloaded, the zones did not move:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/168111a7-ab85-49ec-bd11-c3d0da1ef847)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c1dd25d5-eae2-4188-b2d7-eeea5c9eb9e2)

**Comment by Duchenkuke** [comment]
Okay cool, I honestly didnt test this in a few weeks - If I can reproduce it again I will let you know

**Comment by OobieDoob-Benoobie** [comment]
Working again for me. 
Just adding my two cents. :P
