### ISSUE TITLE
Stanalone crash

### ISSUE THREAD

**Issue by Dr-Colosso** [TheGameCreators/GameGuruRepo#4938]
My standalone game is crashing when loading my second level. Files are missing from the Titles bank and the particles bank. I replaced them and it works fine, but there may be others critical files not being placed in the standalone when compiled.

**Comment by OobieDoob-Benoobie** [comment]
same. 
After updating workshop items and verifying files through STEAM, its crashing at the end of second level.
@Dr-Colosso are you using radar? just curious.

**Comment by Dr-Colosso** [comment]
Yes I am using the radar on all levels. It seams a little glitchy on some levels.

**Comment by OobieDoob-Benoobie** [comment]
@Dr-Colosso How do you know what files are missing?

**Comment by Dr-Colosso** [comment]
I was counting the files because of a standalone game play crash and found the count was different in those two folders from the one in the Main Max folders. Because the test levels played fine I copied those two folders to my standalone it played all levels fine.

**Comment by davetgc** [comment]
Is the crash related to missing files?

**Comment by Dr-Colosso** [comment]
I believe it must be because when the files are replaced the game runs fine. Still some issues with saved games, but that I believe is another issue.

**Comment by OobieDoob-Benoobie** [comment]
One of the smaller patches seems to have fixed it for me.
Now it just crashes when compiling the .exe but I've figured out a workaround for that.

**Comment by OobieDoob-Benoobie** [comment]
> @OobieDoob-Benoobie - Glad that it's working, but could you share your workaround please. If it's a bug that's fixed by it, it will give us a clue as to why it's crashing.

What I did was right click on GGMAX in my STEAM game list on the left, go to "manage" and click on "Manage files" and find the GGMAX.exe file. Right click and drag to desktop and create shortcut. 
Then I shut down STEAM all the way.
Then launch GameGuruMax from the shortcut without STEAM running.
Compile my game into a stand alone and everything works fine. 

Not sure but might be STEAM timing out the program as its compiling? 
Maybe something else with STEAM???

**Comment by OobieDoob-Benoobie** [comment]
> Is the crash related to missing files?

Its now crashing for me at the end of level two, while loading level three. 
It locks up the moment I touch the win zone, and crashes to desktop shortly after that.
Trying to get a demo out and this is the blocker.

The particles were also not included in the standalone. both stock and particle creator ones. 
I copied them without incription from the GGMAX user file to the standalone particles bank folder to remedy.

Also the only way I can get it to make the standalone, is to run MAX independent from STEAM, and I kept 
moving my mouse during the compile process. (Don't check the "close GGMAX and open folder when complete" box)

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie Can you send a screenshot of the crash (or even better a video of the final moments as you load in level 3, thanks!

**Comment by OobieDoob-Benoobie** [comment]
Sent through email as Im not ready to share this with the public.
 TWO BUGS 2023.11.09.mp4.zip
<https://drive.google.com/file/d/1OAzTQU-qa9z39w6eAOxpShbYP1Z3qfYy/view?usp=drive_web>

**Comment by OobieDoob-Benoobie** [comment]
I tried again today and its much better. It still crashes loading level 5 sometimes in EXP standalone. Also I figured out why particles aren't showing up in standalone. Ill try to find that particular post here on GH.

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie Can you send your email again to "lee@thegamecreators.com" thanks!!

**Comment by OobieDoob-Benoobie** [comment]
Here you go buddy.
I uploaded it to YouTube so you don't have ot download it:

https://youtu.be/kwRaswc_Qq4

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie Do you think you can zip up your standalone game and email me at lee@thegamecreators.com so I can see if I can crash on level 5. It would help if I had some shortcuts in each level to quickly get to that level to see the crash :)

**Comment by Dr-Colosso** [comment]
I will save games at each level up to level 5, but the loaded save games
lose all ammo when loaded. Give me a bit to create a zip file for you.

**Comment by LeeBamberTGC** [comment]
@Dr-Colosso Replied by email, thanks for the standalone!
