### ISSUE TITLE
AMD Standalone black screen

### ISSUE THREAD

**Issue by mrfenix** [TheGameCreators/GameGuruRepo#4943]
The editor works perfectly fine but any 3d rendering in a standalone build results in a black screen. Audio can be heard and the pause menu works.

CPU: 5600x
GPU: RX 6800
Drivers version: 23.9.1
OS: Windows 10

**Comment by UltraVox001** [comment]
Hello all,
I confirm this problem.

Configuration :
Windows 11 Pro
64 gigabytes of RAM
Intel Core i5-12400F processor
AMD Radeon RX 6950 XT graphics card

**Comment by LeeBamberTGC** [comment]
@mrfenix Can you post a screenshot of your standalone game folder after running it, here is one of mine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/fffd8807-a8dd-4ca2-a2ef-af6be37f3c20)

**Comment by mrfenix** [comment]
@LeeBamberTGC sure thing. 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/234915/4c4ed47b-2303-49a0-9989-b6fddd6acf2b)

**Comment by LeeBamberTGC** [comment]
@mrfenix Looks like you have the required files in there :)  If poss, can you zip up your standalone game and email it to me at lee@thegamecreators.com and I will run it here, I have an AMD and might spot something.  I assume you get the black screen right away when you run Bounty.exe, no splash screen at all.

**Comment by UltraVox001** [comment]
![Bounty](https://github.com/TheGameCreators/GameGuruRepo/assets/96718175/56c7987c-ff64-4b49-a5b4-f1bc32b24173)

> I assume you get the black screen right away when you run Bounty.exe, no splash screen at all.

Negative. The game launches normally. There is a Menu and several presentation images. The screen goes black as soon as you take possession of the player on the terrain. Using key Esc correctly recalls the Menu and you can exit properly.

Sorry, but my current connection does not allow me to send a 3 gigabyte file :)

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Do you see "amdfix.ini" in your "X:\SteamLibrary\steamapps\common\GameGuru MAX" root folder?  If so, can you copy this to your standalone game root and let me know if that helps?

**Comment by UltraVox001** [comment]
> @UltraVox001 Do you see "amdfix.ini" in your "X:\SteamLibrary\steamapps\common\GameGuru MAX" root folder? If so, can you copy this to your standalone game root and let me know if that helps?

Yes Lee, the file "amdfix.ini" is present in the root, and simply copying it to the root of the game makes the game operational. :)
