### ISSUE TITLE
Report from Steam for Classic - LUT Filter Not Working

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4946]
**Reported on Steam** 
Hi, the LUT Filter is not working again, for me, following the most recent update. (It was working just fine before.) Thanks.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Just checked with the latest version and it seems to be working again. Just started a fresh map, added an entity, then set the LUT from the TAB TAB area, works fine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/00d76706-1142-41d2-a536-97f730a39f41)

**Comment by synchromesh62** [comment]
Ok thanks Lee i will let the user know and report back.
