### ISSUE TITLE
Back Button from Hub. No way to get back.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4947]
This was discussed in a stream and was going to be added
If you go from your level to the Hub you cannot get back.
Please add a button :)

![hub](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/8268b992-4076-4d33-87c8-1f0fd795de52)

**Comment by extremestrategy** [comment]
What would be be going back to though, there is nothing before this screen (except for the first time users) and for getting back into the level it's only a second to hit the edit project, the one you were just in would be the first one up, and then go back into the level.

**Comment by MonkeyFrogStudio** [comment]
That's sort of what I was thinking, too ... just click on your project and then select the level from the storyboard. I'm not sure why I would go from a level to the HUB anyway ... unless I was going to load up a new or different project.

**Comment by synchromesh62** [comment]
> What would be be going back to though, there is nothing before this screen (except for the first time users) and for getting back into the level it's only a second to hit the edit project, the one you were just in would be the first one up, and then go back into the level.

Ok so your working on a project
you want to check out a tutorial for example or for whatever reason.
then you want to go back where you were to continue editing.
Well you cant ..

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/fbbb564e-001a-4448-9a8e-eac955d18463

**Comment by MonkeyFrogStudio** [comment]
But you can. You click on the My Games tab, click on the game your working on, then click on your level via the Storyboard. That's not really any more clicks than what it took to get you from your level to the Tutorials. ;)

**Comment by davetgc** [comment]
I'm leaving this one as waiting for information to get some feedback from users.

**Comment by synchromesh62** [comment]
> But you can. You click on the My Games tab, click on the game your working on, then click on your level via the Storyboard. That's not really any more clicks than what it took to get you from your level to the Tutorials. ;)

Not if your loading your map from **File \ Load** and editing from there. Or start from the default map without creating a Project for it.
Doesnt matter i will close it .. There are more important things to be sorted.

**Comment by extremestrategy** [comment]
I understand it now, sorry about that, I agree that this could be useful.
