### ISSUE TITLE
Help Me!  Crash script Shop

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4948]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/950116a7-867b-4b91-8c01-48d698cb4cc1)

These are crashing I don't know if a problem of mine I don't know what it is 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/5ef51164-765f-4d3b-91d4-9b3131ef6e72)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6f75c70f-2c7b-4e9f-aeca-c979c415f509)

**Comment by AmenMoses** [comment]
Runtime error 501 is illegal image Id so I would say there is a Lua bug related to the image/sprite handling.

**Comment by SampeyFS** [comment]
ah you have to report to Necrym59

**Comment by SampeyFS** [comment]
Same problem in the script ( Vendor )

**Comment by extremestrategy** [comment]
@SampeyFS Try verifying the files, I had the same problem but after verification it fixed the problem.

**Comment by SampeyFS** [comment]
Yes already done many times it does nothing is a bug in the script

**Comment by extremestrategy** [comment]
I don't seem to have the issue, they both work for me.

**Comment by Necrym59** [comment]
Nothing wrong with the scripts - cant replicate|
you have to be more specific in your descriptions if you want help

**Comment by SampeyFS** [comment]
I wouldn't know where the problem is

**Comment by Necrym59** [comment]
It seems to me its somthing to do with an image your using, perhaps from an non stock object. Does it happen all the time or just on a particular object? The scripts themselves dont reference any so it has to do with somthing your using as far as i can see.

**Comment by SampeyFS** [comment]
I put the Flashlight Battery also hand weapons does it example accepts machetes

**Comment by SampeyFS** [comment]
hi how do i solve the problem? i tried all ways but nothing

**Comment by Necrym59** [comment]
Are these stock scripts or others

**Comment by SampeyFS** [comment]
Trader Shop , Shop, Vendor

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/1f491928-022e-4dd6-b8d3-5d40ca2061a7)

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/623e9a6e-fabf-4c35-8b9f-7921cc7e400b)

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/52c46447-01ea-43f7-814a-edf23084199d)
Trader I tried to buy zucchini saw came written this

**Comment by Necrym59** [comment]
These are not standard images so one may be corrupt or the wrong type im not sure but i can find nothing wrong with the scripts they run fine here.

**Comment by SampeyFS** [comment]
how do i go back to the previous version

**Comment by davetgc** [comment]
My guess is this is related to one of the custom images. Can you replicate using default media.

**Comment by SampeyFS** [comment]
That would be it doesn't support custom images? right?

**Comment by davetgc** [comment]
MAX supports custom images, it's likely an issue with one of the images you're using.

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/1934aa37-e668-45d3-8292-a47f1bbe68a1)


No it's not those xkè see they're all customized it does ostesso I think it's something xkè the inventory does it too when you go to the shop sometimes

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/4f1e6f20-950f-4709-b67c-781e21fcd62a)

I've done several tests I think it's a problem you max proppio of this problem xkè does it also the inventory sometimes I hope you solve the problem ( Not Solved by me )

**Comment by AmenMoses** [comment]
Right so I attempted to use my gg_debugger on this and found MAX has changed so much that it wasn't at all straightforward but we did eventually get two errors of note:

 Mon Sep 25 21:42:39 2023 !!Error!! GetImageWidth : Image Id out of range : 0 ( 50615 .. 105999 ) -stack traceback:
	.\scriptbank\gg_debugger\debug_main.lua:24: in function 'traceback'
	.\scriptbank\gg_debugger\debug_main.lua:31: in function 'ggDebugDoError'
	.\scriptbank\gg_debugger\debug_main.lua:76: in function 'ggDebugValidRange'
	.\scriptbank\gg_debugger\image_sprite_debug.lua:34: in function 'validImageId'
	.\scriptbank\gg_debugger\image_sprite_debug.lua:64: in function 'GetImageWidth'
	scriptbank\Community\6704278\core\rpg\eat.lua:87: in function <scriptbank\Community\6704278\core\rpg\eat.lua:79>

Mon Sep 25 21:42:59 2023 !!Error!! CreateSprite : Image Id out of range : 0 ( 50615 .. 105999 ) -stack traceback:
	.\scriptbank\gg_debugger\debug_main.lua:24: in function 'traceback'
	.\scriptbank\gg_debugger\debug_main.lua:31: in function 'ggDebugDoError'
	.\scriptbank\gg_debugger\debug_main.lua:76: in function 'ggDebugValidRange'
	.\scriptbank\gg_debugger\image_sprite_debug.lua:34: in function 'validImageId'
	.\scriptbank\gg_debugger\image_sprite_debug.lua:80: in function 'CreateSprite'
	scriptbank\Community\6704278\core\rpg\collect_object.lua:49: in function <scriptbank\Community\6704278\core\rpg\collect_object.lua:46>

In both cases the LoadImage function is returning 0 instead of a valid imageId, no idea why that might be but it might be a good idea to add some sanity checking into those scripts so that if the imageId is 0 put a Prompt on the screen instead of continuing on and potentially crashing inside the engine with the dreaded 501 error.

So basically I would change the code (both scripts are similar) to something like:
	if status[e] == "init" then
		local imgId = LoadImage( "imagebank\\cursors\\cross.png" )
		if imgId > 0 then
			local sp_imgwidth = GetImageWidth( imgId )
			local sp_imgheight = GetImageHeight( imgId )
			local sp_pointer = CreateSprite( imgId )
			SetSpriteSize( sp_pointer, -1, -1 )
			SetSpriteDepth( sp_pointer, 100 )
			SetSpritePosition( sp_pointer, 200, 200 )
			SetSpriteOffset( sp_pointer, sp_imgwidth / 2.0,  sp_imgheight / 2.0 )
			SetSpriteColor( sp_pointer, 255, 255, 255, 255 )
			status[e] = "endinit"
		else
			Prompt( "Cannot load imagebank\\cursors\\cross.png" )
		end
	end

Now it may be that neither of these are the cause of the main issue and it may be in one of the new functions that gg_debugger doesn't know about (and which don't seem to be documented in global.lua!) but this is all we have to go with at present.

**Comment by Necrym59** [comment]
Thats strange as the same piece of code is used everywher elsee without issue.  Perhaps i will dump it back to the old system that doesnt use pointer sprites. Now if we could use a special windows font for pointers it would make the job a snap and alleviate the need for sprite based poointers. altogether.

**Comment by Necrym59** [comment]
This has all been fixed

**Comment by SampeyFS** [comment]
yes

**Comment by SampeyFS** [comment]
it seems solved
