### ISSUE TITLE
They are not seen in the inventory

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4956]
These two items when you collect them do not show up in the inventory
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/4f862857-0553-4c74-a853-46ec595683d8)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/2494f417-f909-4b20-b9c0-83bd01ec1794)

**Comment by Necrym59** [comment]
They were designed before collectables was invented
Fuel was designed for another use behavior altogether!
Wood was never a scripted object perhaps make it a collectable item will do it.
I will look into it when i am able to.
