### ISSUE TITLE
Trying to path an entity from a behavior not assigned to it locks up the engine

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4962]
StartMoveAndRotateToXYZ() and MoveAndRotateToXYZ() Lua functions lock up the engine when being used from a behavior not assigned as the behavior of an entity itself. This doesn't seem to happen in an "empty" level but does in one with terrain.

I was debating whether or not to even report this, as this is out of the norm and I'm sure will rarely be attempted and can be worked around with a bit of work. It does represent a lockup issue though, and it took me hours to track it down.

**Comment by TenebreGaming** [comment]
I had it happen using both functions, though the StartMoveAndRotateToXYZ()
function may not always do it. This could be because internally they could
use the same/similar code for the MoveAndRotate part.

**Comment by smallg2020** [comment]
does the script above crash for you? (without uncommenting the moveandrotate and just leaving the startmove in)
in my tests it works fine until adding that line but it is would make sense that it's using the same logic for both as the character does move along the path with just startmove.

**Comment by TenebreGaming** [comment]
The script above runs fine. The script I originally found the isue in is fairly large and doing a lot of things and has been mostly rewritten, and I can't seem to reproduce the error using StartMoveAndRotateToXYZ( ) as I was before. It could have been something specific I was doing when trying to figure out the issue.

**Comment by smallg2020** [comment]
yh, seems to be working in the latest exp build

**Comment by LeeBamberTGC** [comment]
@smallg2020 No worries. I have just uploaded a new EXP build with an additional "RDIsWithinAndOverMesh" command, and attached a new script and FPM level, that should give you a nice running around behaviour that respects the obstacles everywhere and has a nice smooth running action.  @TenebreGaming Might be useful in your endevours :)
[pathtest.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12805078/pathtest.zip)
[DESS2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12805089/DESS2.zip)

**Comment by TenebreGaming** [comment]
It actually got worse in the new build. My original test level with no terrain now exibits the same behavior, though it worked before. But a very simple test script with nothing more than "MoveAndRotateToXYZ(2,0,0)" in its main locks up the engine.  it's possible that it's locking up because there is no previous path, but this call should be allowed. I will need to test this further.

**Comment by smallg2020** [comment]
> test script with nothing more than "MoveAndRotateToXYZ(2,0,0)" in 

are you calling findpath first?

**Comment by TenebreGaming** [comment]
The purpose of calling MoveAndRotateToXYZ(e,0,0) is to force movement of the entity to stop. I do it before repathing because it appears to help with updating the internal position in the pathing so I can grab it. This does however, mean it gets called sometimes prior to a path being found.  I can add a flag to avoid calling it if needed, but it should work as is without locking up. The call works fine within the module assigned as the behavor of the entity.

This was just the firt thing I tried. I do need to do more testing on it to see if the rest is fixed.

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Probably not a good idea to call "MoveAndRotateToXYZ(2,0,0)" as it is basically saying move zero speed, i.e. not move anywhere. Can you take the attachments I made and modify the script to use "MoveAndRotateToXYZ(2,0,0)" in a meaningful way and attach back here so I can see the freeze, thanks!

**Comment by TenebreGaming** [comment]
@LeeBamberTGC I am using MoveAndRotateToXYZ() to stop the character the same way it is used in the masterinterpreter.lua script.

I will do more testing on this and give an update for the report.
