### ISSUE TITLE
GameGuru MAX - Bug - Global Light Probe Not Properly Updating

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4964]
During yesterday's live broadcast, Lee talked about the way to resolve a lighting issue for interior-only levels. The answer was to place light probes throughout the interior level in order to stop the effects of the global light probe from affecting the interior pieces. While this works, I don't think it's a solution as I believe there's another bug, which I will get to in a moment.

The main reason it's not a solution to use light probes to block or nullify the global light probe is, if someone has a large interior level, they would need to manually place and size light probes every step of the way. Even in the example of the short hallway Lee used during the live broadcast, he ended up placing three of them to get the effect he wanted. Imagine if someone had dozens of such hallways, let alone rooms, etc.! That's just not a reasonable solution.

From my tests, I don't think it's necessary, because I think there's a bug - **_It appears that MAX is holding onto and using the OLD global light probe even if the environment settings have changed._** I'll try to explain.

I started a fresh empty level and built a section of hallway and stairs from the Offworld Station DLC. None of the environment settings were changed. Despite the hallway being sealed on both ends so exterior light couldn't get in, it looked like this:

![dark](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/0e9fe6f4-0835-49b4-8d1e-77769609ee49)

As you can see, the hallway is being effected by the default global light probe, which is illuminating the interior hallway. To attempt to counter this, I changed the environment settings:

![dark0](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/8dcd18f4-9ff6-4012-8e97-fa0b9685b80e)

As you can see, there's no sky, every source of lighting is pure black, etc. Even so, the hallway remained unchanged:

![dark1](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/09973d85-d1ca-4378-aa2a-a6a33ebaf81a)

Then I saved the level (still no change), exited MAX, reopened MAX, and then loaded the level back in. This is what I got:

![dark2](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/8e3f36b4-495a-461b-9ede-12561e7bd5c9)

As you can see, the hallway is perfectly dark, except for the emissive lights from the ceiling lights. I didn't place a single light probe to block or replace the default global light probe. It seems that, after a save and reload, the new sky settings (see above) were finally taken into account and, as a result, a true dark level was achieved without the use of any user-placed light probes.

This seems to indicate to me that the global light probe that's originally created by MAX with MAX's default environment/sky settings is not being updated properly, resulting in people not being able to get truly dark levels no matter what they set the environment to be like. However, once you finally get the level to update, you can achieve a truly dark level, even without use-placed light probes.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio I agree placing hundreds of env probes down into an interior style level is tedium, and once was the primary way of lighting levels back in the day.  More recent tools either automate this process, and then allow smaller manual tweaks, or have the env probe built into prefabs already correctly sized and configured for purpose.  In fact it was for this reason of not wanting the user to be tasked with adding all these probes that it was not included right away and was held back. The need for control of env maps however meant we did need them. We do need a 'faster/easier' way to get these probes into levels however, something to mull over.

Thanks for the above and the solution, I agree it looks like a remaining bug here and I will hopefully have good news when I dive into it and see what is happening with that global env map.  Will report back here when a new EXP build is up with a possible fix.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Thanks for looking into this.

I hear what you're saying and realize the importance of probes in these situations. I think that if the global light probe properly updated to whatever environment settings the end-user set, then there would be no need for them to have to put down any light probes to correct this (only place their own light probes where they want more control over reflections, etc.). It seems fairly obvious that the blue tinting people are getting in dark/black levels is from the global light probe still using the probe images from when the default sky was blue, etc. 

MAX has had a habit of holding on to old stuff before in other areas. Seems the global light probe just needs to be refreshed (take new images to use?) when the environment is changed by the end-user.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC BTW - as an added note - one user said they had to close MAX, load a completely different level first, and then load the dark level to show dark. I think this also indicates that something is causing the global light probe to not always refresh.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Turns out the global env probe refresh was pretty faulty, and never refreshed when changing things like skybox, etc. Now tied to env probe reset so can update for any major changes to the probe system, works out of the box in the next EXP build now :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/070d7dd7-562b-428f-a0ca-e099733e5523)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e7669814-1ab2-43d3-b1de-47d5e5efa790)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Glad to see the issue was found! I will certainly take a look at this when it's in the experimental build!

**Comment by synchromesh62** [comment]
> @MonkeyFrogStudio Turns out the global env probe refresh was pretty faulty, and never refreshed when changing things like skybox, etc. Now tied to env probe reset so can update for any major changes to the probe system, works out of the box in the next EXP build now :) ![image](https://user-images.githubusercontent.com/35840583/272254243-070d7dd7-562b-428f-a0ca-e099733e5523.png) ![image](https://user-images.githubusercontent.com/35840583/272254281-e7669814-1ab2-43d3-b1de-47d5e5efa790.png)

Lee i noticed my level had a lot of shimmering since todays update and pinned it down to probes .. Is it just me or is this a side effect of the global fix .. I dropped a probe in a corridor as an example ?


https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/581135bb-8376-41d1-aebb-98efb45b7790

**Comment by LeeBamberTGC** [comment]
@synchromesh62 That looks a little nasty, can you make up a stock media FPM level that shows the same thing, and attach here, I can then find out the issue. This COULD happen if more than 8 env probes are too close together I think.

**Comment by synchromesh62** [comment]
> @synchromesh62 That looks a little nasty, can you make up a stock media FPM level that shows the same thing, and attach here, I can then find out the issue. This COULD happen if more than 8 env probes are too close together I think.

I cannot seem to replicate it on a new map.
Looks like its just mine .. I will have to see if i can sort it :(

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC This doesn't look to be completely fixed. Let's say I have Skybox set to None; Lighting Color, Ambient Color, Horizon/Fog Color, and Atmospheric Color all set to pure black, then the interior level is completely dark inside. If I think switch the sky to Skybox, the level lights up due to the change. That's good. But then, if I switch back to None and reset all of the settings to black (Lighting Color, Ambient Color, etc.), the level remains lit:

![probe](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/0986f882-e0f1-49f4-9e97-239a409d936b)

I have to switch to Simulated Sky, which then causes the probe to update, darkening the level, and then back to None.

So, it looks like switching to None for the sky does not cause an update (or does not always cause an update).

Steps to follow (from above):

- Have sky set to None and turn everything to pure black (Lighting Color, etc.) and see the level get very dark (black, if inside with no lights)
- Switch to Skybox and watch the level get bright again (as it should)
- Switch back to None and change all the color stuff (Lighting Color, Ambient Color, etc.) to black and see that the level doesn't get dark like it did originally
- Switch to Simulated Sky and see that the level goes dark instantly
- Switch back to None and it's dark now, too

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
After spending the day on this i found the problem ( YAY )
The flicker light behaviour is conflicting with the probes .. No matter where or how far away the flicker light is it causes the glitch. 
LOL first thing i removed this morning and it did not work but forgot i had another on the map till about an hour ago .. Doh !!

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/9fc8e45b-717b-437c-b330-6ebcb71fd78c

**Comment by synchromesh62** [comment]
@MonkeyFrogStudio 
I agree its not completely fixed but i find if you set it and run the level is does go completely dark and stays that way when you exit ... If that helps..

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Was an easy repro, thanks!  In the next EXP build, when lights change, the env probe refresh is instant, no fade management:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f1570d65-ba2b-432b-b100-9a6fb0ab98b7)

**Comment by synchromesh62** [comment]
> @synchromesh62 Was an easy repro, thanks! In the next EXP build, when lights change, the env probe refresh is instant, no fade management

Confirmed as fixed. Thanks Lee 
Btw .. Setting darkness is now superb !!

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC You closed this, but the issue I reported above is still present. If you switch to a skybox and then back to none, even after you turn all the light settings to pure black, the level remains lit in the editor:

![probe](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/28520aa9-0f24-40db-917e-7d4d38d360ce)

It does display correctly when you run a test game, but it's not updating correctly in the editor. I detailed the steps to make this happen in my previous post above.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Can happen when multiple issues posted in one issue :) Reopened.

**Comment by synchromesh62** [comment]
Ye probably my fault as the probe error i reported was related to the same issue.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio In the next EXP build the probes update even if the global lighting colors and other settings are changed. Previously the probe only updated when the sky type was changed, not when the sky was subsequently color changed :)

**Comment by MonkeyFrogStudio** [comment]
Looks like it's working properly now. Thanks, @LeeBamberTGC !
