### ISSUE TITLE
Cannot save my standalone game

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#4966]
From TGC Support: also have a main issue with gameguru max since the most recent update i now cant save my standalone game i have tried 20+ times and even restarted my pc waited a day to try and it just crashed gameguru max everytime i try to save stand alone before the update it was fine. 

i found out why but this issue shouldnt be happening i made a backup of my game and deleted that level and tried again and it saved but i havnt modified any of them files in this txt file ive put below but i think its only happening since the latest update as everything saying it dont exist wasnt an issue before as it should exist

or it could have been when i purchased more dlc content to use from steam that updated the game files thats causing the error as i cant see any updates from you guys in the last week so if thats the case one of the purchased contents out of audio ambience booster pack, aztec game kit, particles booster pack they are the 3 i purchased since having this issue as it started on the 25th september which is when i purchased them as i know the issue is the level i have put in over 40 hours of work into and making a backup and deleting that level allows the standalone to be saved and i hope there is a fix for this as i dont want to have to remake that level due to this error and if not i will just have to redo it all due to something going wrong with something out of the 3 dlc content mentioned above interfering with content i owned and it updating to use these 3 packs messed with the current files before buying them

LOG:
32504 : Saving standalone from mapbank\Unknown Dungeon.fpm      S:268MB V: (7935,0)     
32506 : Tried adding path that does not exist: scriptbank\people\ai S:0MB   V: (7935,0)     
32519 : Tried adding path that does not exist: audiobank\materials\tarmac S:0MB   V: (7935,0)     
32521 : Tried adding path that does not exist: audiobank\music\theescape S:0MB   V: (7935,0)     
32527 : Tried adding path that does not exist: audiobank\voices\characters S:0MB   V: (7935,0)     
32531 : Tried adding path that does not exist: audiobank\character\soldier\onAggro S:0MB   V: (7935,0)     
32536 : Tried adding path that does not exist: audiobank\character\soldier\onAlert S:0MB   V: (7935,0)     
32542 : Tried adding path that does not exist: audiobank\character\soldier\onDeath S:0MB   V: (7935,0)     
32548 : Tried adding path that does not exist: audiobank\character\soldier\onHurt S:0MB   V: (7935,0)     
32553 : Tried adding path that does not exist: audiobank\character\soldier\onHurtPlayer S:0MB   V: (7935,0)     
32558 : Tried adding path that does not exist: audiobank\character\soldier\onIdle S:0MB   V: (7935,0)     
32564 : Tried adding path that does not exist: audiobank\character\soldier\onInteract S:0MB   V: (7935,0)     
32579 : Tried adding path that does not exist: effectbank\reloaded S:0MB   V: (7935,0)     
32579 : Tried adding path that does not exist: effectbank\reloaded\media S:0MB   V: (7935,0)     
32584 : Tried adding path that does not exist: effectbank\reloaded\media\materials S:0MB   V: (7935,0)     
32596 : Tried adding path that does not exist: languagebank\neutral\gamecore\huds\sliders S:0MB   V: (7935,0)     
32597 : Tried adding path that does not exist: languagebank\neutral\gamecore\huds\panels S:0MB   V: (7935,0)     
32603 : Tried adding path that does not exist: gamecore\decals\splat S:0MB   V: (7935,0)     
32616 : Tried adding path that does not exist: gamecore\projectiletypes\fantasy\fireball S:0MB   V: (7935,0)     
32616 : Tried adding path that does not exist: gamecore\projectiletypes\fantasy\magicbolt S:0MB   V: (7935,0)     
32621 : Tried adding path that does not exist: gamecore\projectiletypes\modern\handgrenade S:0MB   V: (7935,0)     
32626 : Tried adding path that does not exist: gamecore\projectiletypes\modern\rpggrenade S:0MB   V: (7935,0)     
32638 : Tried adding path that does not exist: terrainbank\temp\ S:0MB   V: (7935,0)     
32652 : Tried adding path that does not exist: terraintextures\mat0 S:0MB   V: (7935,0)     
32672 : Tried adding path that does not exist: terraintextures\mat33 S:0MB   V: (7935,0)     
32673 : Tried adding path that does not exist: terraintextures\mat34 S:0MB   V: (7935,0)     
32680 : Tried adding path that does not exist: terraintextures\mat35 S:0MB   V: (7935,0)     
32684 : Tried adding path that does not exist: terraintextures\mat36 S:0MB   V: (7935,0)     
32690 : Tried adding path that does not exist: terraintextures\mat37 S:0MB   V: (7935,0)     
32696 : Tried adding path that does not exist: terraintextures\mat38 S:0MB   V: (7935,0)     
32701 : Tried adding path that does not exist: terraintextures\mat39 S:0MB   V: (7935,0)     
32709 : Tried adding path that does not exist: terraintextures\mat40 S:-98MB V: (7836,0)     
32715 : Tried adding path that does not exist: terraintextures\mat41 S:0MB   V: (7836,0)     
32839 : Tried adding path that does not exist: skybank\None     S:0MB   V: (7837,0)     
32840 : Tried adding path that does not exist: terrainbank\     S:0MB   V: (7837,0)     
84968 : _mapfile_loadproject_fpm: mapbank\Overgrown.fpm C:\Program Files (x86)\Steam\steamapps\common\GameGuru MAX\Files S:-184MBV: (7652,0)     
84968 : LOADMAP: lm_emptylightmapandttsfilesfolder              S:0MB   V: (7652,0)     
84991 : LOADMAP: read FPM block                                 S:0MB   V: (7652,0)     
85365 : LOADMAP: load in visuals                                S:39MB  V: (7692,0)     
85457 : LOADMAP: apply visuals                                  S:0MB   V: (7692,0)     
85457 : Initialise sky textures                                 S:0MB   V: (7692,0)     
85463 : Load sky cube:skybank\None\None_cube.dds                S:0MB   V: (7692,0)     
85470 : Load player config                                      S:0MB   V: (7692,0)     
85476 : LOADING ENTITY BANK                                     S:0MB   V: (7692,0)     
86219 : Loading master objects: 10                              S:-212MBV: (7479,0)     
86224 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin D.dbo ) S:0MB   V: (7480,0)     
86311 : Loaded 1:Aztec Game Kit\Scenery\Ruins\Aztec Ruin D.fpe (9996) S:45MB  V: (7525,0)     
86319 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin G.dbo ) S:1MB   V: (7526,0)     
86395 : Loaded 2:Aztec Game Kit\Scenery\Ruins\Aztec Ruin G.fpe (9964) S:39MB  V: (7566,0)     
86401 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin J.dbo ) S:0MB   V: (7567,0)     
86482 : Loaded 3:Aztec Game Kit\Scenery\Ruins\Aztec Ruin J.fpe (14898) S:36MB  V: (7604,0)     
86487 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin H.dbo ) S:0MB   V: (7604,0)     
86565 : Loaded 4:Aztec Game Kit\Scenery\Ruins\Aztec Ruin H.fpe (14998) S:34MB  V: (7639,0)     
86571 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin I.dbo ) S:0MB   V: (7640,0)     
86649 : Loaded 5:Aztec Game Kit\Scenery\Ruins\Aztec Ruin I.fpe (15029) S:33MB  V: (7674,0)     
86654 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin F.dbo ) S:0MB   V: (7675,0)     
86731 : Loaded 6:Aztec Game Kit\Scenery\Ruins\Aztec Ruin F.fpe (10002) S:33MB  V: (7708,0)     
86736 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin E.dbo ) S:0MB   V: (7709,0)     
86812 : Loaded 7:Aztec Game Kit\Scenery\Ruins\Aztec Ruin E.fpe (9987) S:33MB  V: (7742,0)     
86818 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin A.dbo ) S:0MB   V: (7743,0)     
86894 : Loaded 8:Aztec Game Kit\Scenery\Ruins\Aztec Ruin A.fpe (4996) S:32MB  V: (7776,0)     
86902 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin B.dbo ) S:0MB   V: (7777,0)     
86977 : Loaded 9:Aztec Game Kit\Scenery\Ruins\Aztec Ruin B.fpe (9996) S:36MB  V: (7813,0)     
86982 : LoadObject( entitybank\Aztec Game Kit\Scenery\Ruins\Aztec Ruin C.dbo ) S:0MB   V: (7814,0)     
87059 : Loaded 10:Aztec Game Kit\Scenery\Ruins\Aztec Ruin C.fpe (9996) S:35MB  V: (7850,0)     
87059 : End Loading master objects:                             S:0MB   V: (7850,0)     
87066 : LOADING ENTITY ELEMENTS                                 S:0MB   V: (7850,0)     
87187 : Loading additional entities for collection item list    S:-254MBV: (7596,0)     
87198 : e:entity_loadelementsdata()                             S:4MB   V: (7600,0)     
87199 : Tried adding path that does not exist: skybank\None     S:0MB   V: (7600,0)     
87204 : Tried adding path that does not exist: terrainbank\     S:0MB   V: (7600,0)     

this is for gameguru max when i click save standalone it stays at 1% then crashes ive tried saving for over 24 hours now before the recent update it worked but since 26/09/2023 when i tried it hasnt worked and still isnt now

when i try and save as of 26/09/23 i havent been able to save and this happens to be an issue since the most recent update for gameguru max as it worked fine before hand
i found out why but this issue shouldnt be happening i made a backup of my game and deleted that level and tried again and it saved but i havnt modified any of them files in this txt file ive put below but i think its only happening since the latest update as everything saying it dont exist wasnt an issue before as it should exist 
or it could have been when i purchased more dlc content to use from steam that updated the game files thats causing the error as i cant see any updates from you guys in the last week so if thats the case one of the purchased contents out of audio ambience booster pack, aztec game kit, particles booster pack they are the 3 i purchased since having this issue as it started on the 25th september which is when i purchased them as i know the issue is the level i have put in over 40 hours of work into and making a backup and deleting that level allows the standalone to be saved and i hope there is a fix for this as i dont want to have to remake that level due to this error and if not i will just have to redo it all due to something going wrong with something out of the 3 dlc content mentioned above interfering with content i owned and it updating to use these 3 packs messed with the current files before buying them

i can 100% confirm its to do with the level i have on it and since purchasing the 3 dlc mentioned has interfere with my current files
as when i delete the map it saves a standalone perfectly and the issue began since the date of purchase of them 3 packs

here is the video of me showing it works without the level and it not working with the level and the map logs

**Comment by LeeBamberTGC** [comment]
NOTE: Thanks for the information, plenty here to look at, thanks!

**Comment by LeeBamberTGC** [comment]
Follow-Up From User: is there hope for this issue to be fixed then? or would i have to redo the level and will post on ther if i find anything else thank you

Answer: There is always hope.  It is now a reported issue and will be dealt with as a HIGH bug report.

**Comment by LeeBamberTGC** [comment]
I have added additional debug log code to the latest EXP build that will investigate this error:

"Tried adding path that does not exist: XXX"

This line shows a path that could not be found that explains the standalone crash, so the extra debug info will help us see where it is looking.  Once you run the new EXP build and try your standalone again, post the results of the new log data that you can find in "C:\Users\XXX\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log".

You can get the EXP build by using your Steam client, opening the product properties, find the BETA tab and select the EXPERIMENTAL branch of the software.

**Comment by LeeBamberTGC** [comment]
NOTE: Not reproducible and not reported elsewhere.

**Comment by OobieDoob-Benoobie** [comment]
Ive also been having an issue where GGMAX EXP and public builds are crashing when I try to create an exe
I have discovered a workaround though:

Open STEAM and find GameGuruMax in your list of installed games/software.
Right click on GameGuruMax and select "Manage" and then "Browse Local Files" then find the GameGuruMax.exe file.
Using the RIGHT mouse button, drag the file to your desktop and then click "Create shortcuts here".
You can close everything and shut down STEAM.
Now use that shortcut to launch GameGuruMax without STEAM running.
You should now be able to save a stand alone version of your game/demo/level.

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie I will add an INFO tag to this. If you can create a video showing STEAM LAUNCH MAX, save a standalone, then crash out, I can look at where the standalone got to and add some extra syncs so Steam does not detect an unresponsive app and force quit it.

**Comment by OobieDoob-Benoobie** [comment]
Ill work on that today.

**Comment by OobieDoob-Benoobie** [comment]
Ive been trying to build a small two or three level game and compile it to stand alone, but now GGMAX EXP is just crashing to desktop while compiling.  I shut down STEAM and tried to no avail. It sits for about 10 min. without the progress bar moving, then the bar goes up to about 98% and it sits there for a couple min. and crashes to desktop.
