### ISSUE TITLE
Hi @Dieter9999 - Did you mean to close this as resolved?

### ISSUE THREAD

**Issue by Dieter9999** [TheGameCreators/GameGuruRepo#4969]
Hi @Dieter9999 - Did you mean to close this as resolved?

_Originally posted by @davetgc in https://github.com/TheGameCreators/GameGuruRepo/issues/4958#issuecomment-1738803448_

**Comment by Dieter9999** [comment]
I do not close this.

**Comment by davetgc** [comment]
You've created a new issue. I'll close this one. You can reopen the other one.
