### ISSUE TITLE
Game Guru Max - standalone pc

### ISSUE THREAD

**Issue by Dieter9999** [TheGameCreators/GameGuruRepo#4971]
Hello,

i have bought GameGuru Max. It is great !
I have edit my first game and made it standalone. I copyed the standalone folder with GameGuru Max to
another pc, but the game do not run.

What should i do ? Please help me.

The GGMax PC:

CPU: AMD FX 6350
RAM: 16 GB RAM
OS: Windows 10 Pro
HDD: Seagate Hybrid HDD 2 TB
GPU: NVIDIA GeForce GTX 1060 3 GB

Standalone PC:

Notebook Dell Latitude E7440
CPU: Intel Core i5 4310U
RAM: 8 GB RAM
HDD: 256 GB SSD
GPU: Intel HD

All games made with GameGuru run on this Notebook very vell.

**Comment by MonkeyFrogStudio** [comment]
It looks like your standalone PC doesn't meet the minimum requirements to run either MAX or a MAX standalone game. Your GPU would be the main culprit here, since it's an integrated Intel HD GPU.

**Comment by davetgc** [comment]
I'd agree that that is the problem. You need a dedicated GPU to run MAX.
