### ISSUE TITLE
MAX: Muzzle flash on NPC's is in the wrong place

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4973]
The muzzle flash appears to be coming from the wrist:
![Screenshot 2023-09-28 160506](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/6d673bb3-940d-4845-adc8-8bc18d1e018f)
![Screenshot 2023-09-28 160536](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/0b4f1335-b9bd-4762-8542-5c9c203fd0a3)

Also, the muzzle flash doesn't appear to be using depth buffering so always renders between the camera and the NPC. This NPC is facing away from the camera:
![Screenshot 2023-09-28 160411](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/72c6cab4-aad6-47d9-b9e5-36765a5ac190)

**Comment by davetgc** [comment]
This could be related to ongoing weapon improvements.

**Comment by TenebreGaming** [comment]
Very likely related, I agree. I just added it here so it doesn't get missed.

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Fixed for the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4b3d666e-b83b-4168-a322-6506b671c9f0)

**Comment by TenebreGaming** [comment]
@LeeBamberTGC It is good at/near a facing angle of 0 and 180 degrees, but is way off at/near +/- 90 degrees.

**Comment by LeeBamberTGC** [comment]
@TenebreGaming I still have my level above to test muzzle flashes for characters. Can you send me a shot of what you mean that this still needs attention?  I have attached my stock level in case that helps.
[Uploading DESS2.zip…]()

**Comment by TenebreGaming** [comment]
Here's a full set of screenshots by facing angle:

~0 degrees, looks fine.
![Untitled_1 1 1](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/e525d809-f81a-4ce3-b97f-eec1c94d0cb5)

~45 degrees, flash is offset to left.
![Untitled_1 1 2](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/879e65b3-82d4-43dd-858a-e9cb718ee5af)

~90 degrees, flash centered at wrist and renders between character and camera.
![Untitled_1 1 3](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/582126be-d523-4c04-be34-e9576f97a109)

~135 degrees, flash offset to right.
![Untitled_1 1 5](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/b8a6e650-ebc8-434e-a06d-1294bf695abe)

~180 degrees, looks fine.
![Untitled_1 1 5](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/cfaea79f-2ba9-4531-8917-9b8e82fbef06)

~225 degrees (-135 degrees), flash offset to left.
![Untitled_1 1 6](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/78776689-d190-425f-90b9-30addff3b0a9)

~270 degrees (-90 degrees), flash centered on wrist and renders between character and camera.
![Untitled_1 1 9](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/b82ff7bc-fca1-4bea-9d80-41bdc417d5b9)

~315 degrees (-45 degress), flash offset to right
![Untitled_1 1 11](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/8af619ad-c763-476b-9098-20ad79d7bffc)

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Okay, gone full tracker now, and will allow the firespots to be visualized when in debug view mode :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2a9477a6-8f7b-4d3a-bfc3-acc60c9cce9c)

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Fixed for next EXP build.

**Comment by TenebreGaming** [comment]
Confirmed fixed in Build 2023.10.11
