### ISSUE TITLE
GG Max - Request: small modification to DoorRotate script

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#4974]
Hi, I want to ask if somebody could modify the Door Rotate script, so the door would react to a switch connected to it. Right now it can be opened only by approaching the door up close and pressing E; If I attach a switch to it, there's no reaction at all. 

![Screenshot_1](https://github.com/TheGameCreators/GameGuruRepo/assets/101792609/af11ae85-cfda-498b-8d36-94cd660df1a9)

**Comment by Necrym59** [comment]
This is why we have a 'Door Rotate Multi script' that can beopened by switch or zone

**Comment by Ghost-l0l** [comment]
Whoops, indeed there's a script for that; I didn't notice at first
Thank you for quick answer! :)

**Comment by Necrym59** [comment]
If this is fixed are the answer solved the problem please close the issue
