### ISSUE TITLE
Spawning locked door not retaining its setting

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4977]
Quite simply if you set a door to be locked and **Do not show on start**  when spawned it will always revert to **Press E to open** and will not be locked when it appears.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed for the next EXP build, door rotate now toggles the unlocked flag from HASKEY instead of using the activation flag which when connected to logic activates (and unlocks) before the user can get to the door.

**Comment by synchromesh62** [comment]
Awesome thanks Lee i will check and confirm

**Comment by synchromesh62** [comment]
Works perfectly but only for stock animated doors ( which is fine )
Just wondering if this could be adapted to ones using Door_rotate as well ?
If not no worries its job done and can be closed :)
Thanks Lee

**Comment by LeeBamberTGC** [comment]
@synchromesh62 new V22 versions of the door scripts for the next EXP build. Now create consistency between all three door types:

When not spawned at start, activating them will show them
When spawned at start and locked, activating them will unlock them
When spawned and unlocked, and in AUTO, activating them will perform their action
