### ISSUE TITLE
Water Control Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4978]
as you can see I have been underwater for a while but there is no lack of life 

![Screenshot 2023-09-29 201201](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/825b4854-4e58-4099-a6c5-c08f399f7cc3)
![Screenshot 2023-09-29 201319](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/5fa5b90a-4c18-44f8-981d-6b2b1400d155)

**Comment by Necrym59** [comment]
This does not explain the problem. Please elaborate on what the problem actually is and especially how to reproduce it

**Comment by SampeyFS** [comment]
Sorry my fault I had put two same script works

**Comment by SampeyFS** [comment]
simple to understand go underwater it does nothing but only on this map xkè in the empty it works I don't understand why it goes and doesn't go now it doesn't go as you see


https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6a7ec577-2c52-484f-bf1f-342e060e71aa

**Comment by Necrym59** [comment]
Do you have the scuba behavior on the map anywhere

**Comment by SampeyFS** [comment]
sisi done nothing does not work

**Comment by Necrym59** [comment]
That didnt answer my question! 
The behavior does work it may be your map.

**Comment by SampeyFS** [comment]
I put it to be able to swim but using the oxygen tank seems normal to me this I don't understand these nonsense questions

**Comment by SampeyFS** [comment]
I confused me with li script apologize this has nothing to do with it you are right
