### ISSUE TITLE
MAX EXP - Show Stopper - Objects Falling to Ground

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#4980]
In lates exp - 2023.09.28
Seeing some models falling to ground in standalone

In test-game
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/6e76b9aa-978a-43f7-8dd4-659e60a8c240)

In standalone
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/e52399ae-ade1-470c-aaa0-706850126ea3)

Using these settings in editor and using rotation 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/5dda8f9b-f484-422b-b68b-0b637e20748e)

Was fine in all previous builds.

Thanks for checking

**Comment by AmenMoses** [comment]
Hmm, either of 'physics off' or 'issimobile yes' should prevent that!

**Comment by OldFlak** [comment]
@AmenMoses - PM'd you on discord with script being used.

**Comment by AmenMoses** [comment]
Yep, script looks fine.  Definitely some sort of regression in the engine imo.

**Comment by davetgc** [comment]
Can you zip the behaviour up please and post it here.

**Comment by LeeBamberTGC** [comment]
@OldFlak You can zip things up and GitHub accepts ZIP files :)  If I can get something that I can reproduce with stock stuff, I can make a fix :)

**Comment by OldFlak** [comment]
@LeeBamberTGC Hi lee will get something together for you.
After further testing it seems to affect existing levels - I can't reproduce it in a new level.

I could zip up that whole level and send it to you if you think it worth it.
- but it is just an asset test level, and won't be used once we get projects - so is it worth fiddling with?

**Comment by LeeBamberTGC** [comment]
@OldFlak It helps best if I have the whole level and original media zipped up as then I can get as CLOSE as possible to what you are seeing. Even when I have everything exact there is not always a 100% chance of me seeing the issue, but we can but try.  Please send all to lee@thegamecreators.com along with anything you think I need to quickly reproduce and see what you see.

**Comment by LeeBamberTGC** [comment]
@OldFlak Makes sense. I have your original PROJECT SYSTEM email and will reply to that once I have a first draft of the system in place so you can test it. Once it works for you, it will be much easier to send me an entire project to reproduce the issues you are seeing.
