### ISSUE TITLE
Boat behavior not working and making you very low under sea or very high over your boat in the air!

### ISSUE THREAD

**Issue by Jessika07** [TheGameCreators/GameGuruRepo#4984]
My game use islands a lot, so i need the boat behavior to work.  
Right now, each time i start my version of GGMAx i have to replace my boat.lua behavior with my own file for it to work correctly.
I change a few lines to make it work.  line 209 seem to be the culprit, but i am far from being an expert.  
Check out my file and see if it works for you instead of the current behavior.
If it works, i hope the devs can see what is wrong and fix the behavior, because the boat is a very useful item when you create an outside open area with water in it.
For anyone interrested, this is my file;
((--https://drive.google.com/file/d/1iYBF0suKANCs88TfyHxw2zaiDccGgj3p/view?usp=drive_link--)
remove ((-- and --)) and copy in your browser to download the file.
I really hope this help!
;)

**Comment by Necrym59** [comment]
There appears to be nothing wrong with the behavior, can you be more specific or show a video as to what is happening.

**Comment by Jessika07** [comment]
Many thanks answering my question Necrym59!
i am using the experimental build 2023.09.28. of game Guru Max.

my problem was noticed by a few other users as well, (on steam discusion) but it seems no one could help, or people would say it works for them, which i found very hard to believe, since it stop working for me a few months ago, when i was not even using the experimental build, and thought THAT was why i had the problem; Thinking maybe my version was not updated.  it makes me stop using GGMax for a month thinking this was a bug into GGMax itself.

Now for your question, it is hard to know what you mean by 'the updated one or the stock version'.  I guess you mean if we took the behavior as a seperate entity and attached to the boat object, OR, if we use the boat itself and just adjust the value that come with the automatically attached behavior?  Well that would be difficult to remember as it was in my level since the beginning of development, so it is probably the automatically attached behavior.  Also, when we close and reopen GGMax, the behavior go back to the bad one, so we have to over write the file boat.lua again with mine.  I hope this give you a clue as what is wrong.

if we need to attach the behavior to overwrite the 'automatically attached one', it would be very useful and important to know this, inside gameguru max.  it would have save us 4 days of development searching for a solution.  Maybe a note when we load the boat, or more simply just put NO behavior into those objects automatically?  i think that would save a lot of headache...

Sorry i don't know how GitHub works for putting files here so i try many things;

the problem i had when boarding
![oversea1](https://github.com/TheGameCreators/GameGuruRepo/assets/67011561/acc50df2-8e9f-4e41-8c02-fc602f34971f)

the problem others had when boarding
![undersea1](https://github.com/TheGameCreators/GameGuruRepo/assets/67011561/626355c9-6d7e-4021-807c-5e41a2854479)

https://drive.google.com/file/d/1SEi701s0KcjkRvHJlUW9k3k8ZnNScjMS/view?usp=drive_link
https://drive.google.com/file/d/1ICJPBjOdq901NIIo_ABvdYnOQ0aY4rjX/view?usp=drive_link
  
[https://drive.google.com/file/d/1ICJPBjOdq901NIIo_ABvdYnOQ0aY4rjX/view?usp=drive_link](url)
[https://drive.google.com/file/d/1SEi701s0KcjkRvHJlUW9k3k8ZnNScjMS/view?usp=drive_link](url)

**Comment by Necrym59** [comment]
Re-apply the behavior using the one marked (by Necrym59) it should be working. You may have to verify files as the workshop update doesnt always seem to update the latest scripts. Updated ones by default are supposed to be used in preference if one exists - this problem has been reported and will get fixed during the bug fixing stage.

**Comment by Jessika07** [comment]
That is amazing Necrym59.  Thank you very much and just to say your behaviors are great and a big part of what makes GameGuru Max more than just a shooter maker.  i will post your answer to Steam as well so people know about how to solve this.  Thanks again!
;)

**Comment by davetgc** [comment]
Closed as fixed.
