### ISSUE TITLE
GGMAX - Behavior Images Problem

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#4985]
When using multiple selectable images in a behavior strange problems occur with the behavior images and dynamic panel.
The 1st image shows ok
The 2nd image doesnt show at all ??
The 3rd image flickers ?? 
Video of the problem below and attached is the matching behavior for testing.

https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/5f0db1cc-b5b6-4c82-8c3d-8dd54c458b65

[compass_v7.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12785906/compass_v7.zip)

**Comment by LeeBamberTGC** [comment]
@Necrym59 Fixed for the next EXP build, was related to a special image index to allow up to eight images to show in the behaviour selections, but as these elements where further down they exceeded the fixed property index, changed so the index only increments when an image is used to give the full eight at full performance.

**Comment by Necrym59** [comment]
Works perfectly now thanks Lee
