### ISSUE TITLE
MAX EXP - Outside Reflects on Interiors Back Again

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#4989]
#4698 - this issue has returned with a vengeance.
Image from latest build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/e01efb30-c817-4895-949a-1461e298ff69)

**Comment by OldFlak** [comment]
Update:
Even does it with sky off
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/80bd0ae1-01a8-44c4-9fa6-1f258d76a8bc)

And here in another level where it has no color anywhere in the scene:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/53d72aaf-da7b-4003-9928-097357595548)

**Comment by LeeBamberTGC** [comment]
@OldFlak Can you attach a small FPM using stock media (maybe the offworld corridors) and a step by step so I can see what you see. My own tests updated the env maps quite well when I toggled sky boxes and moved env probes.

**Comment by OldFlak** [comment]
@LeeBamberTGC Hi Lee I be your favorite thorn in the flesh :)

I have not been able to reproduce in a new level - since it is just an asset test level, and won't be used when projects get here, it is worth messing wasting time trying to sort it?

**Comment by LeeBamberTGC** [comment]
@OldFlak We can mark this one as fixed if not repro in new levels, and handle anything in existing projects if someone else reports. I am sure its something very minor at this stage.
