### ISSUE TITLE
Terrain settings not Saved

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#499]
The terrain reverts back to default terrain, after reloading a map or when saving map, gameguru then loads back the default terrain. 

Only workaround is to pick different terrain and then choose your terrain you had before. while in testgame.

**Comment by plemsoft** [comment]
@tarkus1971 Thanks for reporting this,

I tried different things but was not able to reproduce it on my system , so i assume this is something with your fpm , could you sent me the fpm that have this problems , so i can give it a test, thanks :)

if you prefer you can e-mail it to me: plemsoft@plemsoft.com

**Comment by synchromesh62** [comment]
Unable to replicate this and worked the same for me as Preben
With no further response from the OP. I assume Preben dealt directly with OP.
