### ISSUE TITLE
Slowdown in when exiting Test Game Editor ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4990]
This has been hampering me the last few days when testing and i exit test game but in doing the video it appears to be related to when you place a new start marker ... anyone else seeing this ?

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/2a5d5e90-44d9-4ed7-ada8-51e0c4e05af9

**Comment by C4ever08** [comment]
Yes I am having the same issue currently. If I move a start marker around in my level it slows right down. Even in test mode it's slow. When placing the Marker it's the same. I usually don't save and reload level and it works fine.

**Comment by davetgc** [comment]
There does seem to be a performance hit with the latest build, I'm seeing a drop of around 10% on my levels.

**Comment by SampeyFS** [comment]
Yes
