### ISSUE TITLE
GameGuru Max - GCS assets install

### ISSUE THREAD

**Issue by Dieter9999** [TheGameCreators/GameGuruRepo#4994]
Hi,

i have bought some assets from the GCS Store for my GameGuru Max. When i try to import them in GGMax appear the message:

Info: Could not find any Max compatible purchases to download.

GG Max is in GCS registered and i am log in GCS -Store already.

What should i do ?

**Comment by synchromesh62** [comment]
Are you sure the assets you purchased are specifically for Max and not Classic ?

**Comment by Dieter9999** [comment]
Yes: Gameguru max Industrial Sewer Pack

**Comment by davetgc** [comment]
The artist has been updating this pack for MAX, I'd suggest contacting the store in case there is an issue. It's worth remembering that The Game Creator store isn't run or managed by TGC, but by a third party.

**Comment by Dieter9999** [comment]
Thanks. I will send a messege to the GCS store.
