### ISSUE TITLE
GameGuru Max - Modern Day Booster Pack Secret Bunker - add a hatch

### ISSUE THREAD

**Issue by Dieter9999** [TheGameCreators/GameGuruRepo#4997]
Hi,

i have bought yet the "Booster Pack GameGuru MAX Modern Day Booster Pack - Secret Bunker".

I can not find hatches in the pack. How are i can add a hatch to the bunker asset ?

Thanks for the answers.

**Comment by wizardofid29** [comment]
You can add your own hatch model and use a script to teleport the player "outside". This model pack is an "indoor" environment, it is up to the developer for any functionality beyond the intended use. However it isn't out of the question that the artist of this DLC will provide future updates or new assets. This DLC will at some point in the future receive an update and companion DLCs that expand on the environment.  

However this DLC and others by the artist of this DLC will be adding objects, that allow this DLC and DLCs by the same artist,  to interconnect with one another on some level. Keep an eye on the gameguru max steam DLC page over the next few weeks and months for new and exciting content that expand the environments.  

There is already 2 DLCs in the works that will allow the secret bunker to connect with them with special Modular Objects.
