### ISSUE TITLE
Smoke decal from weapons is appearing above the players head. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4999]
The smoke decal for when the player shoots weapons is appearing above the players head. It used to appear where the muzzleflash would show. 
To reproduce this bug just equip the Assault Rifle / AK47 and walk backwards and shoot. The gunsmoke decal will be appearing at the top of your screen. 
![20231008144158_1](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/013b4677-d660-49f1-8e84-05ceb1867168)
![20231008144154_1](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/79e95255-8db6-407f-8ca1-c30a96a8630d)

**Comment by davetgc** [comment]
Is this related to this issue? #4973

**Comment by Kitakazi** [comment]
Hmm it probably is related but I'm not sure if fixing the muzzleflash for that issue will also fix the smokedecal for this one. I will test when I get home or whenever the next exp build is released.

**Comment by davetgc** [comment]
There's a fix for the muzzle flash, so if that doesn't fix your issue, I'll flag this as a different issue.

**Comment by extremestrategy** [comment]
I'm having this issue as well.

**Comment by Kitakazi** [comment]
The muzzleflash fix did not fix this problem

**Comment by Kitakazi** [comment]
I just wanted to add that the Brass that is ejected from weapons is also appearing above the players head

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for next EXP build :)
