### ISSUE TITLE
Normal Maps require -Y axis setting

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#5]
This may be nothing new but it would be good to indicate in any documentation if not present already.

(I had been using +X,+Y,+Z previously and what a difference using the correct settings makes! Some renderers use +Y but others use -Y. On a side note... having now used both, I can say that -Y normal maps are much more "human readable".)

**Comment by plemsoft** [comment]
now a fpe setting.
