### ISSUE TITLE
Serious issue ... files not encrypting 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#500]
Despite the little ( e ) for encryption I am now able to open all my textures, Menu pics, fpe's and sound files and use them from a standalone …

Can anyone else please confirm they can do the same … This is for Beta and Public Preview

**Comment by Pirate-Myke** [comment]
I can open the ones that I made for a demo on 3/17/2019
 Appears it may be broken. Let me check an older standalone.
The one I built from 1/13/2019 is encrypted and cant be opened.
*** Confirmed broken on my Beta build.
![_e_cursor-33](https://user-images.githubusercontent.com/35709303/54747721-e15d3f00-4b8c-11e9-84c0-ec4fd18bca67.png)
![_e_exit-to-desktop-hover](https://user-images.githubusercontent.com/35709303/54747762-00f46780-4b8d-11e9-8c7e-87427f066768.png)

**Comment by Pirate-Myke** [comment]
This is a major issue and needs to be handled. All the DLC that has been used in anyones standalone is open right now. Scripts, images, dbo files, music, everything.  URGENT!!!!!

**Comment by Pirate-Myke** [comment]
This is not a bug. Its an outright mistake. Turn the encryption back on, All the store stuff and all DLC are being ripped right now from all stand alones that are being built.

Jesus man. WTF

**Comment by AmenMoses** [comment]
Scripts are being pre-compiled for the standalone but none of the other files are being encrypted.

**Comment by Teabone3** [comment]
So basically everyone should hold off on doing any standalone builds for the time being?

**Comment by LeeBamberTGC** [comment]
Looks like the BETA and PP builds slipped through with Encrypt turned off. Switched back to on in new latest builds of BETA and PP uploaded just now.  I recommend you withdraw ANY standalones you created with the Feb Fixer BETA and PP builds, and replace them with standalones from this version.
