### ISSUE TITLE
Object Swich

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5000]
this script can be seen uses from a distance as you can see fr
![Screenshot 2023-10-10 124253](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/91511397-5ace-4f7e-a7b3-6deb1a4de30f)
![20231009212554_1](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/1ba5a7c2-82ef-4af5-b004-befad75e3cf6)
om the picture I can see it even from very far away

**Comment by davetgc** [comment]
Sorry, I'm not understanding the issue. Can the original poster, or anyone else shed some light on what's being reported here please?

**Comment by SampeyFS** [comment]
The usa writing can be seen very far away all there

**Comment by davetgc** [comment]
Okay, now I understand. Thanks for the additional information.

**Comment by Necrym59** [comment]
Fixed

**Comment by davetgc** [comment]
@SampeyFS - Is this fixed for you now?

**Comment by Necrym59** [comment]
This is definatley fixed
