### ISSUE TITLE
[Standalone] Setting an entity to Always Active doesn't work in Standalone

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5001]
Not sure what the correct name is for but I'm talking about how if a player moves like 3000 units away from an entity, any script on that entity no longer works until the player is back in range. Setting the entity to Always Active allows it to work at any distance. However once a standalone game is built the entity/script will not work at any range as if Always Active has no effect. This issue is not present in Test Game. Only once a standalone game has been created. 

To recreate
1.) Set up a Quest Poster and create a quest to deliver Test Item. Put some entity next to poster and name it Test Item.
2.) Set an entity as the Quest Receiver and set it far away, past the 3000 range of the where the Quest Poster is. 
3.) Attempt to deliver the item, it will not work because the Quest Poster will deactivate when the player moves to the Receiver past the 3000 range.
4.) Set all entities to Always Active.
5.) The player can now deliver the Item successfully. 
6.) Create a Standalone game. The player can no longer deliver the Quest Item because Always Active isn't actually setting entities/scripts to Always Active.  :(

**Comment by LeeBamberTGC** [comment]
@Kitakazi I modified the RPG Template level to move the witch leader to the other island, set the poster to always active and made a teleport to get there quickly. Made a standalone and it worked fine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0ef0539d-3e84-4dce-bda5-7fca37c111d4)

I did notice the quest information was not exported with the standalone, could that be the cause?

**Comment by LeeBamberTGC** [comment]
Modified RPG Template level map attached:
[RPG Template.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12872598/RPG.Template.zip)

**Comment by Kitakazi** [comment]
Hmm yea works fine for me too. Not sure why it wasnt happening with my own deliver quest. I remade the quest and it seems to work now too. Sorry for wasting time with this one.
