### ISSUE TITLE
Gameguru Max Entitybank folder depth limit Crashes Max

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#5002]
There is currently a bug that crashes max when the folder structure depth is more than 4 folders.

For example Entitybank/Myasset/Myassetblue/Dirty/Blue  
This will crash max when you try to explore than directory in the max library.

**Comment by AmenMoses** [comment]
I had this today, a bunch of models copied over from GGC started causing a crash when trying to view them in the library.

I finally noticed that some of them were missing the .bmp preview images so created some dummy ones and it seemed to fix it.

**Comment by wizardofid29** [comment]
> I had this today, a bunch of models copied over from GGC started causing a crash when trying to view them in the library.
> 
> I finally noticed that some of them were missing the .bmp preview images so created some dummy ones and it seemed to fix it.

The bmp isn't missing per say, it gets created once the file is accessed on a new computer, the FPE now contains the information of the bmp.
