### ISSUE TITLE
VR with Game Guru MAX

### ISSUE THREAD

**Issue by Dieter9999** [TheGameCreators/GameGuruRepo#5004]
Hi,

i would play frindly my new game with my OCULUS Rift 2. 

Wenn i start the game in VR mode, this message appear: Switching to HMD view.
The image than is very bad (red-yellow with black). And i has no idea how i to controlling the game. 
I control the game with my OCULUS controlers.

Who can help ?

Thanks.

**Comment by synchromesh62** [comment]
> Hi,
> 
> i would play frindly my new game with my OCULUS Rift 2.
> 
> Wenn i start the game in VR mode, this message appear: Switching to HMD view. The image than is very bad (red-yellow with black). And i has no idea how i to controlling the game. I control the game with my OCULUS controlers.
> 
> Who can help ?
> 
> Thanks.

No real work has been done in VR yet except preparation with weapons and very basic control.
VR is currently the Dev work we requested to be enabled so we could just play with it and run around our levels in VR.
Its nowhere near optimised or complete so i would just use it for messing with right now.
