### ISSUE TITLE
GameGuru MAX - Bug - Demos Default to No Hands/Weapons Shown

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#5006]
For me, when I select a demo and press Play Game (instead of Edit Game), when the game play begins, there are no arms and no weapons to be seen. I can fire, but cannot see the hands/weapon. If I go into each demo, it's default is No Preference for hand type. If I select one of the hand types, then the hand/weapon will now show up in the demo, even if I revert back to No Preference. 

I tested this on Island Showdown, Canyon Offensive, and Snowy Mountain Stroll.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Was accidentally forcing VR mode when using PLAY GAME. In next EXP build, it will force a non-VR experience when running the demo game from the PLAY GAME button

**Comment by MonkeyFrogStudio** [comment]
Appears to be fixed. Thanks! :)
