### ISSUE TITLE
Bug with Switch and Light system ?

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#5007]
Hello all,

For some time now, I haven't been able to operate Max's switches with a Light. As you can see in this screenshot, the operation to link a light with a switch is done normally. But yet it doesn't work. Clicking the switch does not change the state of the light.
![Switch_And_Light](https://github.com/TheGameCreators/GameGuruRepo/assets/96718175/2acc75f0-a5ed-4369-ae83-5bde410f4d90)
Is this a known bug ?
I haven't used Max for a long time and maybe something has changed in the way it's done ?
I'm using the Experimental version of Max on Steam.

I apologize if this bug has already been listed.
Thanks.

**Comment by synchromesh62** [comment]
@UltraVox001 
Just tested here and no probs ?
do you have the toggle light behaviour attached to the bulb ?

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/168d00e6-5ca6-459c-bc72-9aab55779bb0

**Comment by UltraVox001** [comment]
@synchromesh62
As I mentioned, I haven't used Max for a long time.
And so, I was trying a Switch on a ConstantLight. It couldn't work :-)
Sorry for the inconvenience and thanks again for your help.
