### ISSUE TITLE
Graphic block in Max excessive graphics load

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5008]
I have noticed in Max a problem of FPS freezing even when you are with the mouse when you move in the level it freezes a then FPS drops then restarts I have tried everything even formatting the PC but the problem consists I think it is a problem of Max Of excessive load of ram even at ( Level ) empty it does the freezes I have 16 of ram video card Nvidia 3060 Ti 8 GB Windows 11 Pro

(( Pretty serious problem to be fixed ))

**Comment by davetgc** [comment]
I've not noticed any major freezes or FPS drops on an empty level, can anyone else confirm this please?

**Comment by SampeyFS** [comment]
You have to do it when you're playing a game after it starts clicking the mouse

**Comment by davetgc** [comment]
Yes, and I've not be able to replicate it.
