### ISSUE TITLE
Max is creating items/weapons, duplicating them and putting them far under terrain. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5009]
I opened my level and noticed in the Detailed Object List it was showing some weapons and items that I had not placed in my level. When I clicked one it took me far outside the Editable Area and there were a ton of items/weapons far under the map. Some of these are weapons/items that have never been placed on this level or on any levels in this project. I then checked other levels and found the same issue on all of them. 

It's like it loaded random items from the Collectable Item list and duplicated them and placed them far under the map. 

Video: https://youtu.be/pauaz7KCerg

**Comment by davetgc** [comment]
There are a number of issues with the collectables list. I've also noticed blank entries in the list.

**Comment by LeeBamberTGC** [comment]
@Kitakazi These are auto-created when an object is in the collection list but not in the level as available.  This is needed when collection objects are spawned/dropped such as weapons dropped from characters holding a weapon type.  They need to be in the list for now in case any lagging bugs create multiple copies of them.

NOTE: Add a "(generated)" tag to the end of these types of created objects so we know they are placeholders for the system.

**Comment by Kitakazi** [comment]
All the duplicates it keeps creating is also filling up my visual behavior editor list. I only have like 2 scripts running on my test level but the list is just full of duplicate weapons and collectable items. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/b5adae66-40d5-4881-abd9-dc141f8ee731)

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you send me this FPM level so I can see what is in your shot, then I should be able to resolve this quickly, thanks!

**Comment by Kitakazi** [comment]
Here you go

[test_level.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13035385/test_level.zip)

**Comment by LeeBamberTGC** [comment]
@Kitakazi Try the latext EXP build, it should cleanup your level od duplicates :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2dac48cf-7602-446d-982b-63a399c45ef6)

**Comment by Kitakazi** [comment]
Yea new update fixed it. Thanks!
