### ISSUE TITLE
GGMAX Bug - Particles

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5010]
You see the particles always release the colored dots you have to restart Max to make them disappear

![Screenshot 2023-10-15 144317](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/d707cbc7-a4d9-4743-9b37-5df011e7d8dc)
![Screenshot 2023-10-15 133909](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/314960d4-8f60-479d-84db-5c9fcdb14158)

**Comment by davetgc** [comment]
I've also seen this, but haven't been able to replicate it, but I can confirm that it does happen.

@SampeyFS - Are you able to supply a map file (FPM), where this is happening?

**Comment by SampeyFS** [comment]
Where can I find it

**Comment by SampeyFS** [comment]
yes https://www.mediafire.com/file/anbznken38oi33y/Desert_survival_simulator.zip/file

**Comment by LeeBamberTGC** [comment]
@SampeyFS I loaded the FPM level and ran test game, no colored dots, just the scene you see:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/3d609ae7-46ec-4111-b7ed-6bbc5017395e)

Do I have to do something specific to see dots that I cannot get rid of?
