### ISSUE TITLE
Max corrupt files

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5011]
I noticed that just start Max stay 5 minutes close do the File Verification and reload them same 14 MB files every time so check the Steam files corrupt folder and find them inside so it means that those 14 MB files are corrupt

**Comment by synchromesh62** [comment]
> I noticed that just start Max stay 5 minutes close do the File Verification and reload them same 14 MB files every time so check the Steam files corrupt folder and find them inside so it means that those 14 MB files are corrupt

You will nearly always get an 8 files warning 
This is not corruption though. Verify checks everything and when Max starts it changed certain configurations or there are some you will set. Its just detecting the fact its not the same as a fresh install. Nothing to worry about and completely normal if this is what your seeing.
