### ISSUE TITLE
Max Issue - Scripts Not Working In Old Levels

### ISSUE THREAD

**Issue by DarthPickles666** [TheGameCreators/GameGuruRepo#5012]
So I'm having some issues with the scripts in my game. The level I am working on has had scripts working for the entire time I've been working on this game, and suddenly, none of them work. Mainly the Door scripts when linked to another item, like switches or keys. However, when I load a blank level and do the same layout, it works fine. I've attached a video to show better what I mean. I've spoken to Necrym and he has no idea why it is doing this. I have tried validating, deleting the objects (doors and switches) and replacing them, I've even tried adding the scripts to objects again and it hasnt worked. 

https://youtu.be/gqVu9Qf1gmE

**Comment by Necrym59** [comment]
Ive rolled back the sliding door script, as the new version has a problem - re verify and it should be ok

**Comment by davetgc** [comment]
@DarthPickles666 - Is this fixed for you?

**Comment by davetgc** [comment]
Closed as I'm assuming this is fixed. If it isn't feel free to reopen.
