### ISSUE TITLE
Gameguru Max Optimization Needs Serious Help

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5015]
Title says it all, I'm working on a city map, and it's getting to the point where loading the map is taking about 15 seconds, and if I die in Standalone mode I crash the whole engine, I know it's a map size thing, but if it goes to 5KM, and I'm only using (I think) about 2KM for the city, it should be able to run it.

**Comment by davetgc** [comment]
Hi, could you please post your system specs?

**Comment by extremestrategy** [comment]
Sure thing Dave.

Processor 12th Gen Intel(R) Core(TM) i9-12900K 3.20 GHz
Installed RAM 32.0 GB (31.7 GB usable)
System type 64-bit operating system, x64-based processor
Graphics Card Nivida GForce RTX 3060
Available Storage 560 GB
