### ISSUE TITLE
MAX EXP - LUA Slider Errors

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5016]
When you set a slider up in a behavior using something like:
`-- DESCRIPTION: Set [DELAYTIME=3(0,30)] seconds before volume decrease begins.`
The editor allows you to adjust the value up to 100, which of course will break the script somewhat.

If you change the 0 to 1 `DELAYTIME=3(1,30)` the slider will only go to 30

No matter what the first value is, the slider should be limited to the larger value which in this case is 30.

Thanks for checking...

**Comment by OldFlak** [comment]
Bumping this as it has broken a ton of custom behaviors :)

**Comment by OobieDoob-Benoobie** [comment]
This "BUG"? completely destroys NPC behaviors if you adjust any of their sliders.
Also gun damage slider ruins all other guns in your game.
ANY sliders are dangerous to play with. They shouldn't be.

**Comment by OldFlak** [comment]
Bumping again - this is still an issue :)

As we are on the bug bash run, and this affects behaviours reliability, it would be nice to have it sorted.

Thanks for checking.
