### ISSUE TITLE
High Frame Rate Causes A Variance In Character Move Speed

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5017]
The animation speed and character movespeed is completely messed up with custom characters after one of the last updates. Additionally damaging and an enemy just freezes them in place. This is with my characters I used the Visual Behavior Editor to make the AI for. 

All my custom characters move speed and animation speed is completely messed up. See this video this is the what my characters used to move like. https://youtu.be/LfLAkshp_fA?si=0DlaOHBRtx6ewlkK
Now using the exact same Behavior on the exact same character, this is what the characters currently move like. 
https://youtu.be/ZUQEe5EnIEk?si=IuZtdCS6zi-GHuo_

The move speed is insane and no longer matches the animation speed at all. 

 Additionally characters no longer fire off the Damage state, which you can see happen in the end of the video above. Once the character takes damage the logic box lights up yellow(sometimes) in the Damage state but it will always stay at the first box and not progress to the next logic box and instead freeze/lock the character up completely. 

@LeeBamberTGC I dunno this is a pretty big showstopper for me. I don't know how many other people create AI with the Visual Behavior Editor but this would completely wreck their characters.

**Comment by Kitakazi** [comment]
Well something really weird is going on with characters right now. The move speed and animation speed when moving is all messed up from how it was a week or two ago. 
Also it seems the stock characters bug out like 25% of the time when killing them, to where they do not enter a death animation they just lockup frozen.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you email me the character in the video and the script they are using, I can then create a blank level and see how they move in the current EXP build and discover their sudden boost in speed.

**Comment by Kitakazi** [comment]
Just sent you the character and script via email. Thank you!

**Comment by Kitakazi** [comment]
Ok I figured out what is causing this. Sorry for all the emails. Somehow the move-speed of entities is linked to framerate. My monitor is 165hz refresh rate and my computer can easily pump 165 with v-sync on and for whatever reason this is causing characters to zip across the map. 

If I change my refresh rate to 60hz then the characters all behave normally and move at normal speeds. But putting it at 165 causes these issues.

**Comment by Kitakazi** [comment]
Updated the title of this post. Higher frame rate causes characters to move at different speeds than when running at 60fps. I think the AI is moving the same amount each frame so with a higher frame rate it causes them to move much faster and zip across the level. 

AI characters should move independent of frame rate.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Started with stock level and character, and tried changing monitor refresh and VSYNC off and on:

1. Standard PATROL behavior with stock character: 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/71f0cd70-25b2-4a37-ba0f-13ffbe968815)

2. Set monitor to 24Hz and VSYNC ON: 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c58a7486-392e-439d-a608-1a0145fefd68)

3. Same 24Hz with VSYNC OFF:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/d94545f5-454c-4557-bbf8-a4cfb317d354)

In both cases foot planting and movement speed are perfect and identical movement speed, completely FPS-independent.

I have attached the level I used, can you reproduce the test and confirm my findings in the latest EXP build, thanks!
[CHARACTERMOVESPEED.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13229046/CHARACTERMOVESPEED.zip)

NOTE: I will next check out the custom character and script that was sent to me via email.

**Comment by Kitakazi** [comment]
Booooom! Thank you, amazing work. I will test when I get home later today.

**Comment by Kitakazi** [comment]
Yes just tested and it is indeed fix! Thanks!!!
