### ISSUE TITLE
Object library issue visual and duplications

### ISSUE THREAD

**Issue by andypmillard** [TheGameCreators/GameGuruRepo#5018]
In my objects library I have (not including user) 21 categories of which 7 now have items that are difficult to see or you cannot see at all due to the coloured background. It's ok if you individually click on an item to view it, but this makes it useless for searching for items.
The coloured background is fine on other items with the same coloured background even in the same category. It seems to be random. I could go through my stock and change them individually, but I have found that if I update the thumbnail either without doing anything else or by changing the background, the object then appears. But on reopening Max these objects now have a copy. 
This is a new install of the release 2023.05.10 plus my DLCs.
![image_2023-10-20_160316958](https://github.com/TheGameCreators/GameGuruRepo/assets/78655173/05bd65e7-365b-494d-a61b-0f4949b40913)

**Comment by MonkeyFrogStudio** [comment]
Not seeing any of that on my end. I looked up the Old Explosive Crate, for example, and this is what I get:

![object](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/3772151a-7410-402c-838e-ab91ddc473f7)

No duplicates, either.

Have you tried verifying your files via Steam?

**Comment by davetgc** [comment]
Have you tried verifying your files via Steam?

Try that first please and let us know if it fixes the issue.

**Comment by davetgc** [comment]
Is this still any issue for you?

**Comment by andypmillard** [comment]
Hi Dave, Yes this is still an issue, I also reinstalled Max and all DLCs. I thought I replied to the "is this still an issue" question by email. Perhaps I was supposed  answer that here. I just put up with the issue now.

**Comment by Kasseyus** [comment]
@andypmillard Are you using the standard version of MAX, or one of the beta versions?  (Experimental, DevTest, etc)
