### ISSUE TITLE
Unselectable entities (only selectable via drag select)

### ISSUE THREAD

**Issue by Belidos3D** [TheGameCreators/GameGuruRepo#502]
I know a few people have come across this issue. 

The issue is that you will place an animated entity on the map and then when you try to click it to select it will be as if it isn't there, it won't highlight green/red when you hover the mouse over it and clicking does nothing, the only way to reselect these entities is to box select them, which is a pain when they're next to other entities.

While working on some animated models (a wall that collapses when you hit it) i ran into this issue, and another issue, it wouldn't register a hit at all, no matter what script i used, including scripts i knew worked on some other animated objects. 

So i compared the models that worked against my own model that didn't, the .FPE was identical, the script was identical, everything appeared the same, but mine didn't work, so it must be the model right? I did some digging into the models and i found where the problem was!

Originally (and a common way of animating) i had created each block as a separate object within the mesh, so each had their own origin point, which was used for key frame animation. When you export you select all the objects to export, and the last one selected is the parent model.

Gameguru uses the origin of the parent object as the overall insertion point for the model, but what i think is happening is that although gameguru is using the parent objects origin point for the insertion point it gets confused when assigning things like hits and even selection to the object because it doesn't know which origin point to work with.

So instead i joined all the individual objects into one single mesh, then animated by adding bones for each part that i wanted to move, that way it only has one object origin point, exported it into GameGuru, and boom it worked perfectly! 

As a bonus, my animated entities can now be click selected without having to drag select them, so i think it's the same issue that was causing that problem too.

Edit: Yay i finally got GitHub to work, it refused to post anything up until today!

**Comment by Granada1** [comment]
You should post this on the forum ,might help a lot of people

**Comment by tarkus1971** [comment]
|I have had this too, on many store entities and some stock ones. Very hard to select an object in a busy level, and impossible to drag out a box if there is a lot of stuff in the level too.

**Comment by Teabone3** [comment]
I've been going back on my store items and fixing this issue with some of my older models. The anchor center points were offset.
