### ISSUE TITLE
Particle Bug With Stock Particle Portal5

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5020]
There is an issue with Particles made to look like circles or portals. For example the stock particle Portal5 looks like this inside the Particle Editor. 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/2f8da07e-745c-4779-b092-8091e0e0d5b9)

but inside Max it looks like this
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/acef1b92-bf09-48d4-af04-525ffabb27a5)

I think this was reported a very long time ago (like over a year ago) and if I remember correctly Lee actually demonstrated it was fixed on a live stream specifically with Portal5. However it is now back to its old ways and does not work correctly. The same issue occurs with any of the other Portal particles from the Particle Editor.

**Comment by OldFlak** [comment]
Yes, have seen this myself with various exports from PE - some work some don't. Can be hit and miss.
Has been that way from the get go :)

**Comment by OobieDoob-Benoobie** [comment]
Indeed this has been such an annoying bug. Not the worst but definitely annoying.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for the next EXP build and both boxes, lines and circles are now correct. Was caused by bad code in the particle effects shader related to the ROT command.  Also sorted rotations for some shapes too, so now you can place and rotate your plasma rings of fire :)

**Comment by Kitakazi** [comment]
Nice thank you!

**Comment by OobieDoob-Benoobie** [comment]
Now any particle affects using velocity based particle alignment cannot be rotated. 
but the others can.  

Here is a video. I refer to the VELOCITY oriented particles as VECTOR based, Same thing:

https://youtu.be/c8DZYCFVkWY

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie Thanks for the video, can you attach your custom particle export here then I can follow along. I also tried making my own velocity particle:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6f01d69e-abaf-4f66-b113-3e5a081c28af)

And when I dropped it into a level, I could effect the rotation even though it was a little mad:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e9502e99-38fa-43f1-a10e-f5dcc984762a)

**Comment by OobieDoob-Benoobie** [comment]
![RipgateRed_g](https://github.com/TheGameCreators/GameGuruRepo/assets/54692474/960f63c6-19dc-40a8-b8a2-07f2f205f461)
![RipgateRed_r](https://github.com/TheGameCreators/GameGuruRepo/assets/54692474/b4633ff9-fd1c-40eb-add9-f8bef9abe569)
![RipgateRed_sx](https://github.com/TheGameCreators/GameGuruRepo/assets/54692474/c6ca3189-0bf6-477f-98dd-e284d4b708dd)

**Comment by OobieDoob-Benoobie** [comment]
not sure i did that correctly

**Comment by OobieDoob-Benoobie** [comment]
here are the four files that export:

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie Find your particles folder like so: "Documents\GameGuruApps\GameGuruMAX\Files\particlesbank\user", then highlight all files then create a ZIP from them, then you can drag that zip file here.

**Comment by OobieDoob-Benoobie** [comment]
[GGMAX Particle RED.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13243990/GGMAX.Particle.RED.zip)

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie Fixed for next EXP build so vector types will rotate around their local position.

**Comment by OobieDoob-Benoobie** [comment]
Rotating now but badly deformed when doing so.
[https://youtu.be/kGmJ7itIG20](url)

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie Fixed for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2a6d6db2-6645-408d-8cec-dd33da457bc6)

**Comment by OobieDoob-Benoobie** [comment]
Awesome, thanks for the update!
youre amazing

**Comment by OobieDoob-Benoobie** [comment]
https://youtu.be/3-5qCTT0cY4

confirmed working
