### ISSUE TITLE
GG MAX: Custom particles (even vanilla ones) are missing in standalone folders.

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#5021]
Title says it, please fix it - thank you

**Comment by davetgc** [comment]
Just to confirm, are you saying that custom particles aren't being moved to standalone?

**Comment by Duchenkuke** [comment]
yes, not even stock ones. I had to copy them over manually, unencrypted of course

**Comment by OobieDoob-Benoobie** [comment]
This bug has already been posted:
https://github.com/TheGameCreators/GameGuruRepo/issues/5020

**Comment by davetgc** [comment]
Has this issue been fixed for you now?

**Comment by OobieDoob-Benoobie** [comment]
> Has this issue been fixed for you now?

Its still bugged for me as of 8th Nov. 23
I end up copying the entire folder from MAX to the standalone but without encryption.

**Comment by Duchenkuke** [comment]
I dont have gg max installed anymore, so I can't tell.
But last time I checked it wasnt fixed. That was 1,5 weeks ago

**Comment by OobieDoob-Benoobie** [comment]
its fully working now.
Lee just fixed it a few days ago. today is 11-10-23

**Comment by Tum1370** [comment]
I created a Standalone a day ago, and my custom particles did not get copied over to the standalone folder.
But other particles that were not even part of the level, was copied over the the standalone folder.
