### ISSUE TITLE
GG Max EXP - "Deactivate object" using trigger zone doesn't work 

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#5022]
Probably deactivating using switches also doesn't work.

https://youtu.be/gx81XwRVBQw

**Comment by synchromesh62** [comment]
not sure what your trying to do there but whatever it is that's not how it works ?

**Comment by synchromesh62** [comment]
> Probably deactivating using switches also doesn't work.
> 
> https://youtu.be/gx81XwRVBQw

not sure what your trying to do there but whatever it is that's not how it works.
You would do that for activating a door to open or something.
what are you expecting the chair to do ?

**Comment by OobieDoob-Benoobie** [comment]
> Probably deactivating using switches also doesn't work.
> 
> https://youtu.be/gx81XwRVBQw

Are you trying to make the sofa disappear?
If so, you have to use the "hideshow" LUA script on the sofa, and set it to hide, then link it to your trigger zone.

**Comment by davetgc** [comment]
@NewWave2137 - Have the suggestions solved your problem?
