### ISSUE TITLE
Weapons are bugged. Can't swap weapons with number keys. Picking up a weapon does not add it to the weapon hotbar. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5023]
Picking up multiple weapons doesn't let you use your number keys to select a weapon. If you have a project with the inventory HUD turned on picking up a weapon no longer shows it on your Weapons hotbar. Additionally, if you set the weapon to be a collectible item it will show up in your inventory and you can drag the weapons to the hotbar but you still cannot use your number keys to select the weapons.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Yes that is annoying. It is caused by the fact the weapon is really poking through the solid scene, but renders over it so you never see your weapon poke into things. Alas no-one told the shadow system:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4dee634f-eb01-4959-8216-79cd2047551b)
Reproduced!

**Comment by LeeBamberTGC** [comment]
@Kitakazi Introduced a small bug when fixing the zoom mode exit issue, sorted for next EXP build, and also stock weapons show in hotbar in my tests:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6ba8c16f-7d92-4721-968c-a1f427d391b2)

**Comment by Kitakazi** [comment]
Are you able to pickup multiple weapons and then select them using your number keys? I cannot select weapons using number keys currently. I still see no weapons on my hotbars as well.

**Comment by Kitakazi** [comment]
I can get the weapons to go into my inventory only if I assign to them the Collect Object behavior. If they are using weapon.lua then they will not go to my hotbar. It used to just put weapons directly onto my hotbar when they had the Weapon behavior.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you send me your game project folder zipped up and the FPM level you are using that holds the weapon you are collecting. If you use just stock art I can reproduce at this end. Right now when I make a fresh game project, add RPG screens, add an empty level with an AK, then test game, it works fine and puts it in the hotkey bar.

**Comment by Kitakazi** [comment]
Sent

**Comment by Kitakazi** [comment]
This is fixed now. Thanks!
