### ISSUE TITLE
Sky shader does not extend fog to cover entire sky, resulting in unrealistic scenery.  

### ISSUE THREAD

**Issue by boltactiongaming** [TheGameCreators/GameGuruRepo#5025]
In previous iterations of GameGuru, the sky box could be obscured by the fog.  Newer iterations seem to have changed this and while there was a short term fix using a customer shader ([https://forum.game-guru.com/thread/216862](See link)) it is no longer working.

As such, unless you are working on a completely clear day, there's no way to create believable night or fog scenery as the fog ends just above the horizon.

**Comment by synchromesh62** [comment]
Is this for Max or Classic ?

**Comment by boltactiongaming** [comment]
Classic.

**Comment by boltactiongaming** [comment]
Closing issue - this is resolvable by using settings.fx and setup.ini to addfogtosky
