### ISSUE TITLE
Weapons will pickup shadows from objects that they shouldn't be able too. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5027]
Not really sure how to word this one. Please see Video: https://youtu.be/zic83HdcAzE

But yea weapons are picking up shadows in front of objects casting shadows. In the video you can see the shadow goes onto the gun even though the object casting the shadow is in front of the gun, when the shadow being cast is behind the object. 

I would expect the gun to not receive a shadow from the object until it correctly intersects with the shadow.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Yes that is annoying. It is caused by the fact the weapon is really poking through the solid scene, but renders over it so you never see your weapon poke into things. Alas no-one told the shadow system:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4dee634f-eb01-4959-8216-79cd2047551b)
Reproduced!

**Comment by LeeBamberTGC** [comment]
@Kitakazi Demoting this one to LOW as I know the latest Wicked Engine has support for pure overlayed objects such as this weapon would need, so we can solve this with that or fix it when all mediums and highs are sorted. Hopefully, it is not too annoying:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/367d8d9b-4f51-4bed-a034-67f1752f0334)

**Comment by LeeBamberTGC** [comment]
@Kitakazi In the next EXP build the weapon uses a slightly rescaled shadow system so it does not pick up the shadow of penetration when pressing against a solid object:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/dd27751e-6989-499b-a7db-c4ec545ab7e4)

**Comment by Kitakazi** [comment]
Awesome!  Closing as this is now fixed.
