### ISSUE TITLE
Loading screen when the main character dies

### ISSUE THREAD

**Issue by VikSu79** [TheGameCreators/GameGuruRepo#5028]
Hello! Is there any way to make sure that after each death of the main character, a screen with its own image and its own inscription is loaded? Maybe what script is there? Or can this feature be added in the next updates of Game Guru Max? Thank you in advance for your help!

**Comment by davetgc** [comment]
Do you mean a game over screen? Because there is one of those in the storyboard.

**Comment by OobieDoob-Benoobie** [comment]
> Hello! Is there any way to make sure that after each death of the main character, a screen with its own image and its own inscription is loaded? Maybe what script is there? Or can this feature be added in the next updates of Game Guru Max? Thank you in advance for your help!

You mean like a screen with a photo of Humpty Dumpty after the player falls off a wall and dies? 
Or getting shot in the back could show a screen stating "You left enemies behind you!" maybe with
a background photo of someone throwing a potato at the back of someones head? lol

**Comment by davetgc** [comment]
@VikSu79 - Do you have anything else to add to this please? I'm tidying up open waiting for more information threads, and closing those that have been open too long without a response.
