### ISSUE TITLE
MAX exp and public builds- checkpoints not working 2023 Oct24

### ISSUE THREAD

**Issue by OobieDoob-Benoobie** [TheGameCreators/GameGuruRepo#5029]
Adding checkpoints is currently useless. 
I have very lengthy levels that can take significant time and effort to get through.
Having checkpoints in a game designed like this is essential to the flow and player satisfaction.
Currently when you die, it places you at the end game screen where you can star the entire
game over from the beginning or quit, regardless of weather or not you passed through
a checkpoint. This is not ideal.

This functionality works during editor testing and stand alone testing, but once the game has
been compiled into a stand alone game, its back to "Dying = end game" that gets instantly 
frustrating for the testers/players.

**Comment by extremestrategy** [comment]
I agree, the fixing of checkpoints is necessary, also being able to disable game win and loose screens could be good as well.

**Comment by LeeBamberTGC** [comment]
@OobieDoob-Benoobie No detects if checkpoints used and staves off the lives logic so the player can restart at last checkpoint in standalone exports for next EXP build.

**Comment by OobieDoob-Benoobie** [comment]
Seems to be working for me now.
Thank You Lee.
