### ISSUE TITLE
Allied NPC's tank framerates.

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5030]
When using Allied NPC's that are shooting weapons the fps inside of Gameguru Max takes a nose dive, and will go from 80-90 fps all the way down to 30, this does not happen with enemy NPC's and will only happen with allied units,  The Allied NPC is set to the Character Attack Behavior, and must be using a ranged weapon, when following the player there will be some effect, however once the shooting starts the FPS really starts to drop.

Reproduction Steps
Drop down a soldier NPC.
Set the NPC to allied, and give them the Compact Assault Rifle.
Duplicate him 5 times so there are 6 NPC's
Drop down some enemy NPC's near by preferably enough that they have to fire a couple volleys.
Watch the FPS in the corner of the screen.
Enjoy GGM 30FPS edition.

My PC Specs are.
Installed RAM: 32.0 GB (31.7 GB usable)
System type: 64-bit operating system, x64-based processor
Graphics Card: Nivida GForce RTX 3060
Available Storage: 560 GB
Setup: Windows 10 64 Bit
Monitor Resolution: 1920 x 1080

Edit:

Myke Price made this video demonstrating part of the issue. https://youtu.be/aJd_KCfqVAI

His specs are:
Intel(R) Core(TM) i5-8400 
CPU @ 2.81GHz, 32GB RAM, 
Nvidia gtx1050ti 4gb,
Windows 10 Home 64bit,
Screen resolution 1920 x 1080. 
System Passmark 3774

**Comment by davetgc** [comment]
Thanks for the system specs.

**Comment by extremestrategy** [comment]
Your welcome.

**Comment by Kitakazi** [comment]
This happens to me as well. Just 3 allied characters tank FPS for me. 

Intel i7 13700KF
Geforce RTX 4080 16gb vram
32gb DDR5 
Windows 11

**Comment by LeeBamberTGC** [comment]
@extremestrategy Followed the steps in the latest EXP build, siz on six:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/46660c65-82c7-4ca7-87e9-c6c6db421f25)

It was pretty much a massacre, but stayed at 60fps for me:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/fbd55add-2b2d-42d8-b7bb-f64aee7a63b5)

Can you send a staged stock level that can show a sharp drop in FPS, thanks!

**Comment by extremestrategy** [comment]
Well my GGM just got some very small update, and it seems to be a bit better, know it has to be like 30 to tank the FPS, @Kitakazi are you still having this problem, or did the update earlier today help yours as well?

**Comment by Kitakazi** [comment]
Yea I am still having this problem. 
@LeeBamberTGC During the Test make sure to move around while the characters are fighting. Moving around really seems to make the lag really bad.  
[allylag.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13232349/allylag.zip)

**Comment by LeeBamberTGC** [comment]
@Kitakazi I ran the test level and continually moved around with the player, never dropped below 60fps but did see spikes in the LUA logic of 2-4ms.  When you run on your PC, what range does your FPS go and what is the range of the LUA Logic line:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0b17be70-e6de-4e54-a367-406e0aefca21)

**Comment by Kitakazi** [comment]
My FPS is usually at 165 with Vsync On.  But when the allies and enemies start fighting it drops to 100-120 fps and sometimes goes to as low as 80-90. Which 80-90 sounds fast but is actually very slow for this computer. For reference I can run Cyberpunk 2077 on Ultra settings and Ultra Ray Tracing and it runs usually at 165 fps. 


The LUA Logic is about what yours is at - 2-4 however on my last Test Game I notice it shot up to around 16 a few times early on. But it typically stays around 2-4. And it still seemed to swing FPS wildly even when the Logic was around 2-4
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/52cf9d82-9797-4e07-9777-d28d469fdc57)

With the 3 bad guys just shooting me the FPS stays at 165. Well this screenshot dropped to 164.9 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/bfa40cc0-3ecb-4913-ba68-086c94870bca)

**Comment by extremestrategy** [comment]
Possibly then it could be the bullets are hurting the FPS? @Kitakazi

**Comment by Kitakazi** [comment]
Well that screenshot doesn't look like it but all those guys were shooting me in the bottom one. 
However it did seem like when the allies were in the damaged state,  FPS dropped alot. Im not sure about that tho.

**Comment by extremestrategy** [comment]
I don't know either, I'm just spitballing ideas here.

**Comment by LeeBamberTGC** [comment]
@Kitakazi If you are aiming for 165fps (165 frames per second), then your processing cap is around 5-6ms on both CPU and GPU, which means a LUA Logic of 2-4 (and sometimes higher) will definitely kick you out of 165fps.  Once a few more bugs have fallen, I will put a solid week into nothing but performance work, with stage one being to add a better profiler so we can see which parts of a script are eating too much MS and under what scenarios.
