### ISSUE TITLE
Feature request MAX Day Night behavior modification:

### ISSUE THREAD

**Issue by OobieDoob-Benoobie** [TheGameCreators/GameGuruRepo#5033]
Absolutely love the Day Night behavior script.
The only reason I can't use it is because there is no way to choose 
where the sun sets or rises. 
It seems to be locked to an arbitrary position.

**Comment by davetgc** [comment]
Hi, what is your thinking on being able to adjust the sun position at the start? Why would you want this? If you can explain more on this, we might be able to make some adjustments.

**Comment by Necrym59** [comment]
I will look at putting that option in soon

**Comment by OobieDoob-Benoobie** [comment]
> Hi, what is your thinking on being able to adjust the sun position at the start? Why would you want this? If you can explain more on this, we might be able to make some adjustments.

Hi @davetgc. 
On a couple levels, I have the character heading out towards the sunset and sunrise. I was hoping from the start that I would eventually be able to have the sun set in the direction the player is traveling. I had the sun on simulated sky settings, set right where I wanted West to be, as a guide to lay out my levels. 
But when I tried to use the 'day night' behavior, the sun would only go up from there. 
I tried to move it to the other side of the sky using simulated sky, but it would set where my East is. It will only go one direction.

**Comment by OobieDoob-Benoobie** [comment]
> I will look at putting that option in soon

OMG Thank You so much.

**Comment by Necrym59** [comment]
Its done just update workshop files and do a verify,
you now can adjust the Suns Roll, Pitch and Yaw to suit.

**Comment by OobieDoob-Benoobie** [comment]
Absolutely fantastic! 
Thank you so much Necrym59.
Confirmed working.
