### ISSUE TITLE
Destroying a character is generating a gun, even for unarmed characters.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#5034]
I'm using a simple behaviour to ragdoll characters on spawn for dead bodies.  This is creating an uncollectable gun besides the body, even for unarmed characters.

To replicate,  place any unarmed character. Replace the character attack behaviour with the attached destroy behavior. When the character ragdolls, a weapons will be spawned.

[user.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13194908/user.zip)

**Comment by LeeBamberTGC** [comment]
@davetgc Characters can some stock with associated weapons, and they will tend to drop these attachments UNLESS instructioned NOT TO.  As behaviours not designed to offer weapon choices can be used, I have added the HASWEAPON in the developer mode settings so you can wipe out the default weapon of characters so they have nothing to drop.  In the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/50ff4070-91c7-4c71-a8f7-0e51ebf25124)
