### ISSUE TITLE
GG Max - EXP - Enemy do not drop guns or ammo now

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5043]
As the title says, I have just tested a game i made, and now the enemies do not drop guns / ammo anymore.
I have tried re-adding the Character Attack script, but that does not fix the problem.

**Comment by LeeBamberTGC** [comment]
@Tum1370 So that weapons can be better handled and collected into the inventory, you now need to add the weapon into your level that the character wields and eventually might drop.  Once done, go to the weapon dropdown of the character and confirm the weapon is selected.

**Comment by Tum1370** [comment]
@LeeBamberTGC So you mean, if my enemies all use Magnums, and i want them to drop a Magnum with 4 bullets, I have to place a Magnum on the floor somewhere in the level, Then make it a collectable ?
Can the Magnum  place be hidden at start ?

**Comment by Tum1370** [comment]
@LeeBamberTGC  OK so i added a Magnum to the level is have, Made it so it wasnt there at start.
Now when i kill the enemy, the character does drop the gun, but when i move over the dead body it auto collects the ammo, but if i move away from the body, or even die and respawn, then go back to the body, It tries to loot the item again, constantly making a clicking / looting sound, But never actually loots again.

**Comment by Tum1370** [comment]
Also, another problem with this, I use the clone behaviour to spawn characters / enemies, rather than manually placing them.
And after killing the clones, They do not drop the Magnum or Ammo for looting.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for the extra info and scenarios, will check those out :)

**Comment by Kitakazi** [comment]
Hey I figured I would post here to not make a duplicate issue, although my problem is a little different. My enemies drop weapons when killed but the weapons they drop do not respect the "scale = x" set in the FPE of the weapon. I am using custom weapons and they originally imported rather big so I just scaled them down in the FPE. But they are really really big at default scale, my FPE scale setting is set to scale = 4. So at 100 the weapon is bigger than a bus lol.  The weapons dropped by enemies used to respect the scale set in the FPE file. It was only recently this started happening.

**Comment by Tum1370** [comment]
@LeeBamberTGC Additional information regarding this bug.
I have noticed on my test, i have the ammo drop amount set at 4.
I always loot 8 ammo, So seems like it is doubling the amount i have set in the setting,

**Comment by LeeBamberTGC** [comment]
@Kitakazi I set my MAX COLT scale to 500, placed it in the level, then assigned colt to the enemy, tested the level and he dropped the massive gun, can you give me a step by step how your own scaling efforts are going wrong (maybe use the MAX COLT as a stock example):
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/371d673b-9bca-4b0a-8b5e-fa1b7685d0e0)

@Tum1370 The ammo quantity issue is fixed for the next EXP build.  Checking out your die/respawn/clone report now..

**Comment by LeeBamberTGC** [comment]
@Tum1370 I created a scenario with a hurt zone and an enemy who drops a weapon. I killed the enemy, entered the zone so the player would die and respawn, then run to collect the weapon and it picked up okay:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ecf4d175-1b2e-4157-886a-3a95a22ef92e)

I am assuming then you mean the character dies/spawns/clones, trying that now...

**Comment by LeeBamberTGC** [comment]
@Tum1370 I changed the zone to CLONE ENTITY and cloned the enemy, so two of them attacked. Killed both and could collect both weapons:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/fb6e882f-eb40-4d19-8e3d-cf5dd7ba4358)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Finally tried killing one, collecting its dropped weapon, allowing the other clone to kill me, respawning then running back to the fallen enemy. No clicking sound and no weapon to recollect:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/01c194da-c6af-48f0-9f50-003b0ebe97e5)

See if you can use the MAX COLT weapon with a fresh level and attach that FPM level here and walk me through what you do to see the issue, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just done a small video clip of the bug happening.
This character is set to only drop 4 bullets as well.
The BLUE number, bottom left of the screen is the total bullets the character has.
After killing the character, the BLUE number goes up by 8, and not the set amount of 4   (This is obviously another bug)
Then look what happens after repeatedly going over the body and the clicking noise it makes.
But if you notice, it never collects any more ammo after the first time.


[2023-11-04 13-21-04_preview.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13256749/2023-11-04.13-21-04_preview.zip)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for the video! Any chance you can reproduce this with a blank level and stock character/weapon, or is this only happening in your custom level? P.S. The ammo fix will be in the NEXT exp build.

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just tried adding a stock character, and one of those character creator characters i had on the other level, but i placed these on a new blank level.
This time the weapon loot worked correctly for both the stock, and the old character creator enemies.

The bullet pick up amount was still incorrect though.

Problem is, how can this ruin older levels ?
Wont that upset many people when this goes live and it then starts ruining there older levels that many might have worked many hours on ?

Why would a change to dropping weapons just not work on an older level ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 When I say the fix is in the NEXT EXP build, I mean one that will be released in the "future". Unless you have some snazzy temporal version of Windows, you will not be able to test the fix until you get the future build that has the fix in it :)

GameGuru MAX is still very much in development and pretty early days for this software, having been almost completely rewritten we cannot rely on the years of past game maker code to come to the rescue.  Alas, you are the crash test dummies of this little experiment, and pretty much anyone else trying to make a game right now. 

Potentially ANY change can destroy anything that came before it, the best course is to save lots of back-ups so you can revert back to earlier states, and avoid starting any seriously professional projects with MAX. Creating the assets and story is safe enough, but level layouts and how scripts/engine work will be subject to changes for a while to come.

If you like, you can email me your level with custom media and a step by step of what I need to do to reproduce what you see on your PC and I will see if I can repair your level if you wish.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Could you send me one of your older levels that is messed up when you load it in and run, I will see if there is an opportunity to auto repair/replace so non-EXP users need to suffer. Thanks for your patience and understanding :)

**Comment by Kitakazi** [comment]
Hi Lee after doing some more testing regarding the weapon scale when dropped by characters, I believe if you change the character to Ally and then kill the ally the weapon will drop at the incorrect scale. See video https://youtu.be/yM0osQUC1s8

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok ill zip up a level, along with the character creator models, and a couple of other models i use so the level is working correct for you to see etc 
Ill email them to you. What is your email for me to send them to please ?
