### ISSUE TITLE
GG MAX - EXP - BUG - Cloning Script no longer works

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5044]
As the title says, Just tested the cloning script and it no longer works.
It doesnt spawn anything, all it seem to do is make the original entity disappear.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Just added a zone and a rabbit,m then visually linked them and set the clone quantity to 11, all seemed fine in latest EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6c84ea52-8925-481b-8b7a-943c390565e8)

**Comment by Necrym59** [comment]
@Tum1370 
On an older map delete the existing object with the behavior and 'save' the map then exit max and reload the map place a new object with the behavior usually fixes it.

**Comment by Tum1370** [comment]
@LeeBamberTGC THat is the older Clone Entity script that works fine like that.
It is the new one that does not work for me,

**Comment by Necrym59** [comment]
Just tested it on a new map and its functioning perfectly

**Comment by Tum1370** [comment]
@Necrym59 The old Clone Entity behavoiur was attached to a trigger zone, that the player start marker is starts in, So then the clones spawn at start of level.
The new script seem to have to be attached to an object.
So i attached this new one to a barrel, Made it always active, then used visual link to connect the trigger zone to the barrel, to trigger the clonings.
It didnt work or clone anything.
All that happened was the character disappeared.

**Comment by Necrym59** [comment]
Its designed to be attached to an object only and triggered by a zone or switch

**Comment by Tum1370** [comment]
Yes the trigger zone is suppose to trigger the barrel to clone the characters, It does not work for me.

**Comment by Necrym59** [comment]
can you supply me a sample map of it not working - os i can test it - thanks

**Comment by Tum1370** [comment]
Also, how do we have the clones set to just spawn once, when they are triggered, and have infinite life until they are killed ?

**Comment by Necrym59** [comment]
There now no longer have infinite life just set the lifespan to a 60 minutes if you think thats not eneought i can make it more
just link it to a one time trigger zone

**Comment by Tum1370** [comment]
We need infinite really, I dont see why remove it.
use to be a setting of 0

**Comment by Tum1370** [comment]
@Necrym59 Here is a very simple  new level. Clone doesnt spawn.

[New Clone Test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13244451/New.Clone.Test.zip)

**Comment by Tum1370** [comment]
Seems like a step backwards when the infinite lifespan is removed ?

**Comment by Necrym59** [comment]
You have the link to the startmarker not the zone is the issue here
infinit life span was a performance decision but you can respawn after the first cloning 
using the respawn setting for a timed respawn or after all dead respwning

**Comment by Tum1370** [comment]
Oh yes i see that its connect to start marker now rather than the zone.
I threw that together quickly as a test, i should of made sure it was connected properly, Sorry about that.

I cannot see how taking any functionality away is a good thing ?
Yes infinite lifespan maybe a performance issue in some situations, but that is a choice for the dev.

Like i said, My usage of the clones at the minute, was using them to spawn characters automatically, rather than manually placing them around the map. And whether i used clones, or manually added the characters, i was still having that same amount of character on the map, so therefore the performance would be the same.

But either way, This is a choice for the dev, when making the game, and then adjusting it, if you happen to find there are performance issues etc

**Comment by Necrym59** [comment]
This has been fixed and enhanced to include the Eternal Lifespan option

**Comment by Tum1370** [comment]
@Necrym59 Thanks for additional Eternal LIfespan option, I will now close this issue.
