### ISSUE TITLE
Just installed the October update and now any character assigned the NPC control (by Necrym59) attacks the player character even if the allegiance is set to neutral or ally.

### ISSUE THREAD

**Issue by PalmTree11** [TheGameCreators/GameGuruRepo#5045]

**Comment by synchromesh62** [comment]
The npc controller only attacks the player when detected as that's all its intended to do.
The allegiance has never been recognised in that behaviour as its for imported npc's and not stock.

**Comment by synchromesh62** [comment]
It does appear you were correct ( i stand corrected ) Necrym actually never told me he had added it as he forgot ..
He has also just fixed it so you need to update the workshop and then verify to try the new one :)

**Comment by PalmTree11** [comment]
That fixed it! Thank you!

**Comment by davetgc** [comment]
Fixed by Necyrm.
