### ISSUE TITLE
Trigger zones no longer spawning from isused field.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#5046]
As the title says, in the latest build trigger zones aren't spawning character from the ifused field.

To replicate.

Place a trigger zone, set the ifused field to XXX, place a character called XXX and set it to not show at start of level. It won't appear when spawned. There seems to be a few similar reports today, so possibly related.

**Comment by LeeBamberTGC** [comment]
@davetgc Silly one here, fixed for the next EXP build :)
