### ISSUE TITLE
GG MAX - EXP  - BUG - Loot drops

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5048]
I have just tested the LOOT DROP options that was added to Max.
If I set the THE CHANCE OF DROPPING ANYTHING to 100%, then set the CHANCE OF DROPPING LOOT OPTION 1 to 30%

No matter how many times i kill the enemy, It always drops LOOT OPTION 1.

Not really sure how the % works with this behaviour, But it certainly doesn't seem to work correctly.

What is the purpose of the first option, CHANCE OF DROPPIUNG ANYTHING ???

**Comment by MonkeyFrogStudio** [comment]
The first option, Chance of Dropping Anything, is the percentage chance that something or nothing will be dropped. If you set that to 50%, for example, there is a 1 in 2 chance that nothing will be dropped or something will be dropped. 

The other percent is if the first is true (something is to be dropped), then what percent is it to be this particular item. This is for when you have more than 1 item to be dropped. Say you have a candle, a stick, and a fork. If they are set to 30%, then you could end up with only a fork ... or maybe a fork and a stick or a fork and a candle or all three or any combination. 

Since you have the first set to 100% chance and only one item (Loot Option 1), then that second percentage means nothing since the Chance of Dropping Anything is set to 100%. That means that the NPC will 100% drop something and you've only given the NPC one thing to drop, so it has to drop it. If you give it more than one thing and a precent there, then it will drop something (it has to based on the first being set to 100%), but the other percent will determine what (one item, all items, some items) are dropped by the NPC.

If you want the NPC to sometimes drop nothing, then you have to set the Change of Dropping Anything to something other than 100%.

**Comment by Tum1370** [comment]
Thanks for the explanation, but the system is still very buggy.
I set the CHANCE TO DROP ANYTHING to 33 %

Then i set LOOT OPTION 1 to 100%

This should mean, there is only a 33% chance of dropping anything, but even with the 33% setting, the LOOT OPTION 1 drop everytime.

**Comment by davetgc** [comment]
To my eyes, that would mean there is a 100% chance to drop Loot Option 1, not there is a 33% of Option 1 being dropped.

**Comment by Tum1370** [comment]
Looking at the system, and the way Monkey Frog described it.
CHANCE TO DROP ANYTHING, means whether the system then looks any further to the drop options.
So if CHANCE TO DROP ANYTHING is set at 33% , that means there is only a 33% chance of the system even moving on to the other loot options.

I tested this with both methods as you can see from my posts, And it seems to me the system DOES NOT work correctly.

**Comment by Tum1370** [comment]
This is so EASY for EVERYONE to JUST TEST.

**Comment by MonkeyFrogStudio** [comment]
Could you please refrain from the capitalized words. It comes off as yelling.

**Comment by Tum1370** [comment]
No, 
It is not yelling, it is my method to point out the option.

**Comment by MonkeyFrogStudio** [comment]
Sigh.

**Comment by Tum1370** [comment]
Waiting for More Information ??
What more information do you need ?
This is either a bug, or not set up to work correctly...

Maybe try explaining what "Chance to Drop anything" actually means ?
And then what each "Loot Option" means ?

If it was me, and this is how a Loop in the script should be working.

"IF" , Chance to Drop Anything = TRUE  "Then"
         "IF" Loot Option 1 = TRUE  "Then 
                  Drop Loot Option 1
         "IF" Loot Option 2 = TRUE  "Then 
                  Drop Loot Option 2
         "IF" Loot Option 3 = TRUE  "Then 
                  Drop Loot Option 3
"EndIf"

Could you please explain how this is suppose to work, because it certainly does not work like what i have just explained.
And these options only activate the section afterwards, if the % number is True.

Therefore, if "Chance to Drop Anything" is only set at 33%
That should mean the chance of the enemy even dropping ANY loot is 33%

Then if that chance is TRUE, then the script should be then looking at the chances of what type of loot to drop.

It really annoys me when i point out something is not working as it should be, and people just blank what your trying to say, and say, yes its working fine.

**Comment by davetgc** [comment]
This is marked as a waiting on further information, as I want feedback from
other users. It may be a case of needing the wording to be corrected rather
than it being a bug. By getting an understanding of how others view the
issue helps 'FIX" possible problems.

My reading of Chance to Drop anything is the chance that nothing at all
will be dropped.

**Comment by Tum1370** [comment]
Like I said though, these issues sit here for many months, when not marked as a bug because they do not even get looked at. 

As in my sample where if the “ Chance to Drop Anything “ is set at 33%

This should mean, This enemy has a 33 % chance of actually dropping anything. Then if it has decided, yes I will drop something, it then starts looking at the Loot Drop Options. 

So If “ Loot Option 1 “ is set at 100%. This Loot is guaranteed to drop, but only if “  Chance to Drop Anything “  is met. 

If it does not work like this, Then What is the point of “ Chance to drop Anything “ ????


Why even have the “ Chance to Drop Anything “ ??

Each “ Loot Option “ already has its own percentage drop rate. 

But while this is set at Waiting for More Information, this bug will just sit here many months, maybe over a year. So there seems no point leaving this open.

**Comment by davetgc** [comment]
I've flagged this up to Lee for feedback. Sometimes we need to gather more feedback from a range of users.

If you close it, it won't get looked at all, so please be patient.

**Comment by LeeBamberTGC** [comment]
@Tum1370 I have added the necessary tags, should not be years to fix this one I feel :)

**Comment by Tum1370** [comment]
@LeeBamberTGC Am not sure what more information this bug is waiting for, this is related to the percentages not working correctly. 
Just tested this in latest exp build and it is still not working as it should do.
Maybe explain what each percentage means etc ?

Does "Chance to Drop Anything" actually mean the engine tests this first and if this is set at 50%, there is a 50% chance the engine will then look at the loot tables on what to drop ?

If the answer to the above question is true, then the system is bugged.
I have tested this many ways and none of the percentages seem to worked correctly. Clearly a bug and not waiting for more information.

**Comment by LeeBamberTGC** [comment]
Was waiting on more Loot comments. Might have overcomplicated this feature. Leave with me :)

**Comment by LeeBamberTGC** [comment]
Can confirm a chance drop of 1% dropped first time, something not right there:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/30dd21f0-3c0a-4afc-a203-4670eb121aa8)
