### ISSUE TITLE
There is a problem when loading a ready-made game project.

### ISSUE THREAD

**Issue by VikSu79** [TheGameCreators/GameGuruRepo#5049]
Hello! There is such a problem! When I import a game into a ready-made prekt, everything seems to be imported and the game is saved without any errors. I launch it and, when loading the game, somewhere in the middle of loading the slider, I get an error! I have to close everything. And so constantly! How to fix it? What is the problem? I understand it's something with the animation of the character's hands. I don't understand what's the matter??? Please help me fix this and launch a ready-made assembled game. Thank you in advance for your help. When loading a level, this error window pops up in the game menu. Failed to load object : F:\ GameGuruMax_Level\Bunker\My Games\Bunker_Ney\Files\gamecore\hands\Animations\Legacy enhancedmk19t.dbo

**Comment by MartinCranshaw** [comment]
I have the same problem with the new hands. Can't create stand alone as error message appears.
Also Arrow shadow appearing under spinning objects.

**Comment by VikSu79** [comment]
> У меня та же проблема с новыми руками. Невозможно создать автономный файл, поскольку появляется сообщение об ошибке. Также тень от стрелки появляется под вращающимися объектами.

Hi! I solved my problem. I had to remove the marker of the main character (this is from the point where the game starts). And I also had to delete and reinstall all the NPCs in the game, except for animals. fortunately, I don't have many of them. But you first try to delete the marker of the main character, then save, reboot. Then add the marker of the main character again. And after that, try importing the game. Everything worked for me.!!! In the course of something with the characters, namely with the main character.

**Comment by davetgc** [comment]
Thanks for the information. That will help Lee solves this one.

**Comment by VikSu79** [comment]
> Thanks for the information. That will help Lee solves this one.

It helped me! I have to figure it out myself and look for the reason. Look again, maybe there are double 3D objects in your project, which either are objects that should not be or are located outside your map. The engine cannot count them outside the map. There may be problems because of this. I had that too. After the deletion, everything went fine.

**Comment by MartinCranshaw** [comment]
Still not working for me. I created a new level. nothing on it apart from a start and Win zone. Works fine on test with the fem light arms in melee. However fails as a standalone with this message 
<img width="450" alt="image" src="https://github.com/TheGameCreators/GameGuruRepo/assets/38034903/2b0dacfc-c1a2-4362-9d34-35afa10b7f60">
Followed by runtime error 7018.
If I use the standard arms it also runs as a standalone.

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw Attach your emoty level that crashes standalone here and I will see if I can reproduce at this end with the latest EXP bui.ld, thanks!

**Comment by MartinCranshaw** [comment]
Hi Lee tried to attach zipped file but 694Mb
Apparently 25Mb  is the largest attachment.
So here is a link to zipped version https://drive.google.com/file/d/1LUsxv3do0vVYIDqWOE72cEEEgJyQne5H/view?usp=sharing

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw Thanks for the file, was able to reproduce it:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c6a7e9d7-079b-4896-ab87-5cb04b0746a6)

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw Try this new EXP build :)
