### ISSUE TITLE
GameGuru MAX - Bug - Import Uses Surface for Normal when Object has Multiple Materials

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#5051]
With the latest experimental build, if you import a model that has more than one material, MAX uses the SURFACE texture in both the NORMAL slot and the SURFACE slot. 

![surface1](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/12c1b181-2820-4a31-955c-3c55a214ee59)

This does not appear to happen when importing a model with only one material.

**Comment by 3coms** [comment]
![Normal_Surface_FAIL_GGMax_EXP_pic01](https://github.com/TheGameCreators/GameGuruRepo/assets/47690174/ab94b783-ffbf-47ad-8e54-ca75b1f4b2b3)

Running GGMax_EXP last updated.
Multi-material here.

**Comment by synchromesh62** [comment]
Confirmed .. Same result on Import 

![IMPORT](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/ec597f87-c824-418d-9d97-b0f6237bc99f)

**Comment by MonkeyFrogStudio** [comment]
Was also reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3139#issuecomment-1793446397

And Lee says fixed in next build.
