### ISSUE TITLE
utillib.lua Error

### ISSUE THREAD

**Issue by kushiya1122** [TheGameCreators/GameGuruRepo#5053]
![Screenshot 2023-11-06 194733](https://github.com/TheGameCreators/GameGuruRepo/assets/150064614/fd83022f-da28-4e55-b68b-b0f1d4798e03)
 

i need resolve this

**Comment by davetgc** [comment]
Are you using any custom behaviors?

**Comment by AmenMoses** [comment]
The dist parameter needs to be a number not a string.

What script/behaviour are you using that is calling this function?

**Comment by davetgc** [comment]
@kushiya1122 - Can you please supply some more information. Which behviour are you using? What value are you using for distance? As @AmenMoses mentioned, you appear to be using a string value.

**Comment by kushiya1122** [comment]
Nope .. it was come with new update.. also cannot take enemy wepons problem
with pickuo wepons.. cannot pickup wepons.. some

**Comment by kushiya1122** [comment]
Im using same behaviours come with application

**Comment by kushiya1122** [comment]
When i delete utilib. Lua gg max also not working..

**Comment by synchromesh62** [comment]
You need the utilib.lua , Max wont do much without it 
Can you try verifying and rebooting via Steam.

Right click on GameGuruMax in your Steam Library
Select Properties
Select Installed files
then select the Verify integrity of software files 
let it verify then try reboot and try again

**Comment by synchromesh62** [comment]
> When i delete utilib. Lua gg max also not working..
ou need the utilib.lua , Max wont do much without it
Can you try verifying and rebooting via Steam.

Right click on GameGuruMax in your Steam Library
Select Properties
Select Installed files
then select the Verify integrity of software files
let it verify then try reboot and try again

**Comment by synchromesh62** [comment]
You need the utilib.lua , Do not delete it
Can you try verifying and rebooting via Steam.

Right click on GameGuruMax in your Steam Library
Select Properties
Select Installed files
then select the Verify integrity of software files
let it verify then try reboot and try again

**Comment by kushiya1122** [comment]
If i reboot my project will Delete??

**Comment by synchromesh62** [comment]
Reboot is just turning your PC off and Powering it on again ?
why would that delete anything ?

**Comment by AmenMoses** [comment]
I've had a search through all the stock scripts I can find, i.e. all those in the MAX main scriptbank plus the community folder, and can't seen anywhere that a string could be passed down to this function.

I am on the exp build though so could be different from what you are running, also it could be a script from a DLC I don't have or something else you have installed.

@davetgc This sort of thing is what I created my debugger stuff for, I did make Lee aware of it and IIRC even sent him a copy!  What the engine could do with is a trace back logged for Lua detected errors so we can see what actual script is calling the function that catches the error.

**Comment by kushiya1122** [comment]
I did it several times

**Comment by AmenMoses** [comment]
Did what?

**Comment by AmenMoses** [comment]
What happened to "i need resolve this"?
