### ISSUE TITLE
Problem with throwing/placing things behind walls.

### ISSUE THREAD

**Issue by PetrNaj** [TheGameCreators/GameGuruRepo#5055]
[Video](https://youtu.be/UAUQUw4nWi0)

**Comment by extremestrategy** [comment]
Didn't you hear, GGM come with magical phasing abilities lol.

**Comment by LeeBamberTGC** [comment]
@PetrNaj Can you send me your exact level so I can reproduce. I tried to make one but my barrel would not go through the wall in the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e8c3bff9-8fab-42df-84d3-22771e628573)

**Comment by PetrNaj** [comment]
[map.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13627029/map.zip)

[new video](https://youtu.be/zprZNTRUESY)



The "carry_object.lua" script has been improved. But it's still not 100%. See new video

**Comment by LeeBamberTGC** [comment]
@PetrNaj Thanks for the FPM map!  I found I could walk sideways up to the wall, then rotate to face, then throw and that would penetrate.  I will sort now..

**Comment by LeeBamberTGC** [comment]
@PetrNaj Technically a third party script, but here is the fix and send to the author:

		--colobj[tEnt[e]]=IntersectAll(px,py,pz, px+rayX, py, pz+rayZ,-1) avoids pushing carryobj through wall!
		colobj[tEnt[e]]=IntersectAll(g_PlayerPosX,g_PlayerPosY,g_PlayerPosZ, px+rayX, py, pz+rayZ,g_Entity[tEnt[e]]['obj'])

Also attached.
[carry_object.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13628188/carry_object.zip)

**Comment by PetrNaj** [comment]
I didn't find any mistakes. It looks great. Thanks.
