### ISSUE TITLE
GGMAX Bug - Characters Drop Weapons at an Incorrect Scale

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5057]
Making this a new thread as it was def a different issue than when I posted this in Tums thread. 

Set the weapon Colt to scale = 500 in the FPE. 
Place a character on your level and assign him the weapon Max\Colt, then set him as an Ally
Kill the Ally and the weapon he drops will not be a scale of 500 but will instead be the default scale. 

Enemies drop the correct scale value. however allies do not. 

 See video https://youtu.be/yM0osQUC1s8

in the video 1 character is an enemy and 1 is an ally. Both should drop a giant 500 scale Colt but only the enemy does. 

*edit* Enemies and Allies both drop weapons at the incorrect scale value now. Always defaulting to scale = 100

**Comment by davetgc** [comment]
I do have to ask, why would you want to scale a weapon 500%?

**Comment by Kitakazi** [comment]
That was just to test with a stock model. 
My weapons in my game, which are custom weapons, imported at large sizes so I scaled them down in the importer till they looked good. For example my SMG weapon has a scale = 14 in the FPE. But when an ally is killed the weapon drops at the default size of 100. Which at the default 100 scale the SMG is the size of a bus.

**Comment by Kitakazi** [comment]
After the last update it seems enemies no longer drop weapons with respect to the Scale value set in the FPE.

**Comment by Kitakazi** [comment]
@davetgc I believe this is a bug because characters used to drop weapons with respect to the scale set in the FPE and that is what would make sense. Importing a weapon at the perfect scale for Max is not the easiest thing to do and would probably be hours of trial and error to import multiple weapons that way.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.

**Comment by Kasseyus** [comment]
@Kitakazi Thank you for clarifying.  I have now re-opened the issue and will investigate.

Your original video is no longer accessible.  Do you still have this to re-upload?

**Comment by Kasseyus** [comment]
@Kitakazi Also,  it may be useful to test with your custom SMG weapon.  If you don't mind sending it to me, it can be sent to chris@thegamecreators.com

**Comment by Kitakazi** [comment]
@Kasseyus 
Man this one might actually be fixed now. I tested it when you first asked if it was fixed and it was not however, I just tried it again to make a video and it seems to be working. So I'm gonna close this one for now.
