### ISSUE TITLE
Information \ Question

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5058]
What is it about Max and updates ..
Got up this morning and all the sliding doors not working
Its not a simple re-attach its **replacing with all new doors and setting it all up again** to get them to work.
Sometimes its just not doors that need resetting up.
I can understand re-attaching an updated behaviour but replacing all the assets as well ?
Is there any way to just refresh Max to prevent this ?
All i can assume is all the settings are saved to the .fpm and it does not refresh.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Regarding "all the sliding doors not working", does the slider door in the Switch Escape demo in the Hub not wotk for you?

**Comment by synchromesh62** [comment]
> @synchromesh62 Regarding "all the sliding doors not working", does the slider door in the Switch Escape demo in the Hub not wotk for you?

Ahh good call .. Never tried that ... i will take a look

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Yes the sliding door does work in switch escape ... very strange ?
On my current project i have only been able to get all doors working with V20 
Strange thing .. if i set them all at V23 nothing .. But if i attach just one door with v20 and they **all** work again.
Its like the .fpm is looking for V20 ?

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Internally we are up to V25 which also breaks older levels. Working on a new V26 now that should allow older levels and preset door settings to work as before.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
I tested V25 last night and apart from just selecting **Switched** instead of **Non** for triggers it works great.
I have triggers and timers set on my doors and V23 just killed it. I spent a day testing V23  to  try and set it up as i had it and ended up reverting to V20 as that was all i had in a backup. Im using the V25 right now with no issues ..

**Comment by synchromesh62** [comment]
> @synchromesh62 Was having a chat with Steve over email and even though V25 will break many older levels being worked on out there he strongly feels we should use this one as the stock script, and then update all the stock demo levels for sliding doors. Do you agree this is worth doing given the cleanup and extra functionality of the sliding door script?

Hi Lee .. Right now i would say go with Necryms latest. I have not had any issues with it so far and has pretty much all the functionality you could ever need.

**Comment by synchromesh62** [comment]
> @synchromesh62 Okay, lets hold our breath and hope it is the right decision. I loathe breaking legacy stuff, especially one purpose :)

Just tried the update and door_sliding V26 and all doors on all my levels now work perfectly .. **In fact it even fixed your Switch Escape** as last time i tested the door would automatically close instantly .. Now it opens and stays open .. Then closes via the switch as it should.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Yes I think we are okay with this one, the benefits are clear. We can close this and fingers crossed we have not angered the community!

**Comment by synchromesh62** [comment]
> @LeeBamberTGC I figured it out. Cant have "Multi Trigger enabled on the trigger zone.
> 
> Thank you for your help today. I know youre busy. Bless you.
Hope you dont mind i tested your map and yes you were right.
I tested the new door sliding pretty extensively before V26 was implemented and so far its been perfect for everyone so i got a bit worried there :)
