### ISSUE TITLE
Night Vision Q key conflict with french keyboard

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#5059]
Hello all,

On a french keyboard, the Player moves in the 3D environment with the ZQSD keys.

Z = Advance
Q = Left side
S = Back
D = Right side

So moving left (Q key) with nightvision On, turns Off nightvision.
The best (for me) would be to use the N key to Turn Night Vision On or Off.
Please rectify to the best of your ability. :)

Thank you.

**Comment by davetgc** [comment]
A good point, I'm on an AZERTY keyboard myself.

**Comment by Necrym59** [comment]
Until a localisation keybinding solution is done for max, i have adjusted the Nightvision to toggle On/Off just using the 'N' key
[nightvision_v16.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13324373/nightvision_v16.zip)

If you would be so kind as to test this and let me know how it goes, it may then be integrated as the version in the core.

**Comment by UltraVox001** [comment]
Forgive this question.
I need to drop your 3 files into :
C:\Users\MyName\Documents\GameGuruApps\GameGuruMAX\Files\scriptbank\Community\6704278\core\rpg ?

Unless I make a mistake, there is no change.

**Comment by Necrym59** [comment]
@UltraVox001 
Hi there mate how have you been, best if you run it from your own scriptbank 'user' folder for testing and re-apply the behavior to your nvgoggles model, otherwise its probably getting overwritten in the community one.

**Comment by UltraVox001** [comment]
@Necrym59 
I hope you're well. You've come a long way since we prepared your first plugins for Max :-)
It's OK now. This works great in the User folder.
Thanks for the update !
