### ISSUE TITLE
magicbolt cannot be used outside of fantasy directory

### ISSUE THREAD

**Issue by boltactiongaming** [TheGameCreators/GameGuruRepo#506]
If I copy /gamecore/projectiles/fantasy/magicbolt to a new folder, /gamecore/projectiles/test/magicbolt, it ceases to work and the gun will act as a standard raycaster (with bullet puffs and all), sans projectile.  This is of course after updating the gunspec flak and projectile fields from "fantasy\magicbolt" to "test\magicbolt".

Moreover I have many other 'older' projectiles functioning from the test\<foldername> structure without incident.  This issue is WHOLLY limited to magicbolt.

**Comment by plemsoft** [comment]
@boltactiongaming Thanks for reporting this,

It worked fine here in the latest version March 2019, are you using a older version ?

using "projectile    = test\magicbolt":

![magicbolt](https://user-images.githubusercontent.com/18662417/57578704-b6f37800-7491-11e9-8b68-57150ae6bec5.jpg)

**Comment by boltactiongaming** [comment]
I was initially using the 11/18 build but am now using the March fixer and still having the same issue. My issue is with custom projectiles made from magicbolt. So modifying it in the fantasy/magicbolt folder and it worked fine but when moving it to test/magicbolt it does not.

**Comment by plemsoft** [comment]
I did the same and moved it to test/magicbolt , added a new gun in a new folder and added "projectile = test\magicbolt" , and it worked , here is my setup:

![magicbolt-setup](https://user-images.githubusercontent.com/18662417/57627572-85190900-7598-11e9-8e9f-76b2a1e486c4.jpg)

Perhaps you could zip up your setup and email it to me: plemsoft@plemsoft.com :)

**Comment by boltactiongaming** [comment]
I will do so for you to test.

**Comment by boltactiongaming** [comment]
Turns out I had to reinstall from scratch to fix this.  I am still not sure what's wrong with my original but I renamed the original folder (GameGuru --> GameGuru_DX11_0319) and then redownloaded a completely fresh install of GG 3/2019 PP and it works.  So I have to assume this is something related to my old install that I cannot fix.
