### ISSUE TITLE
variable error

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#5061]
I have previously addressed this issue, but it has not been resolved yet. When a player takes a weapon or an item at level A and moves with it to level B, and then returns back to level A, the items that he took earlier are in their places, and are also in the player's inventory.

**Comment by MonkeyFrogStudio** [comment]
If you've previously addressed the issue here on GitHub, it would be good if you'd provide a link to the previous mention. Even better, simply update the original request instead of creating a new one. Lee and the TGC staff are going through all the bugs and requests here, even old ones.

**Comment by davetgc** [comment]
Could you please update the original report instead of posting a new one,

Thanks,
