### ISSUE TITLE
Characters can no longer be assigned a weapon

### ISSUE THREAD

**Issue by bsquish** [TheGameCreators/GameGuruRepo#5064]
Characters using the "Character Attack" behavior can only be assinged the Magnum Pistol.  Characters assigned the "Melee Attack" behavior cannot be assigned a weapon at all.  See pics.
![AE6D](https://github.com/TheGameCreators/GameGuruRepo/assets/150720332/651b25a3-2ebc-488c-90c0-83fa1599b7da)
![99BA](https://github.com/TheGameCreators/GameGuruRepo/assets/150720332/3618c17f-0c19-4751-8dbc-854d2000f10c)

**Comment by MonkeyFrogStudio** [comment]
Can confirm. It's the same here.

**Comment by casigus** [comment]
yep! noticed this too!

**Comment by LeeBamberTGC** [comment]
@bsquish Can you try a blank level with the Aztec Elder set to character attack and let me know if you see this:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/9e84c258-0dcd-4768-813b-ee3299d46a3a)

When changing to Melee Attack, I did notice a small bug so the COLT should not show up, but can see choices:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c5614ae3-d0fe-4b60-b158-e9c5deb0befb)

Can you reproduce what I am seeing in the latest EXP build?

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC With the latest experimental build I get the following:

Character Attack:
![ca](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/d0ea519e-8a3e-45c8-91b8-2499a1801068)

Melee:
![melee](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/0e4a8abc-f89f-4fdd-a5e9-0a8bb8b6296a)

Also, as you can see, her face and hair have not texture.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Could you delete the GAMECORE (backing up of course) from the writables:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5ae433ae-1b3d-4e19-913b-d4b2edf0c7c5)

And rerun MAX to see if more weapons show up for Character Attack, and then screenshot and post your guns folder:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6ba4d370-813e-4156-84c0-2ae53a7ac4b7)

Thanks!

**Comment by MonkeyFrogStudio** [comment]
After deleting the 'gamecore' folder in the writable area, I get a magnum pistol with Character Attack (same as what I posted above) and instead of No Weapon, I get an Aztec Dagger (and No Weapon) with Melee.

Here's the screen shot of the guns folder under the Steam install area:
![folder](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/8c2e7d5d-d1ae-4145-8bf8-1f2b71c3312a)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Just in case I have not updated some gun changes, try copying in a new COLT, the one I have on my system: https://drive.google.com/file/d/12R9KrLY90D85u-mlmS2SZN8xQAYW_FyN/view?usp=sharing

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC I replaced the colt folder with the one from your link. Re-ran MAX and I'm still only getting the Magnum with Character Attack and nothing else.

**Comment by bsquish** [comment]
@LeeBamberTGC I don't see the hair problem that @MonkeyFrogStudio  is seeing, but in a blank map I still can't assing a weapon.  Using the Character Attack behavior only gives me 2 options, using the Melee Attack gives no options at all, and trying to assing a weapon through the character creator only gives one option.
![1](https://github.com/TheGameCreators/GameGuruRepo/assets/150720332/7f39196a-d51d-4a74-8088-f5fa4dddfc39)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/150720332/30e8f051-15a5-4b00-8b25-ba0f11a7e01d)
![3](https://github.com/TheGameCreators/GameGuruRepo/assets/150720332/1231ab74-679b-4d6f-ace6-7ca190c14fc8)

**Comment by bsquish** [comment]
@LeeBamberTGC @MonkeyFrogStudio  I even tried rolling back to retail build, and that did not fix the problem.  I still cannot assign a weapon
![none](https://github.com/TheGameCreators/GameGuruRepo/assets/150720332/83cfa3fa-c033-4d89-a35d-7bf898eec689)
![noweapon](https://github.com/TheGameCreators/GameGuruRepo/assets/150720332/06537b7b-bbd7-4a71-a754-bf3b8967b237)

**Comment by LeeBamberTGC** [comment]
@bsquish Have you tried adding the weapon you want to the level then checking the list. I remember adding some code to ensure the weapon existed before allowing characters to be able to drop them.

**Comment by bsquish** [comment]
@LeeBamberTGC   That still didn't work for me.  The steps I tried:

1.  Create empty level
2.  Add aztec dagger to level
3. Add character to level and assign MELEE ATTACK behavior

The weapon dropdown is still empty and I can't assign a weapon.   But even if this did work I would argue it doesn't make a whole lot of sense to have place a player weapon pickup in the level in order to assign a weapon to an enemy.

![Clipboard-1](https://github.com/TheGameCreators/GameGuruRepo/assets/150720332/5002e277-0e52-47c8-ba19-cb32ec8f0be5)

**Comment by LeeBamberTGC** [comment]
@bsquish Yes I am debating whether the list should be a complete one, and an off-level item created when a weapon is introduced that does not have a physical object to associate with it (for the dropping and collecting into the inventory).  In your test above, can you try saving the level and then on reload, look at the drop-down to see if the dagger appears?

**Comment by bsquish** [comment]
@LeeBamberTGC Just tried it again today, and a recent update seems to have fixed the problem.  The weapon dropdown now allows me to select from all weapons.  I will close this issue.
