### ISSUE TITLE
my cyber city pack on the xmax guru 

### ISSUE THREAD

**Issue by Guruone2023** [TheGameCreators/GameGuruRepo#5065]
My game guru max says that in library i have several packages that have disappeared when i load up xmax game guru
so where have they gone and how more importantly do i get them back as at 24.00 each they arn't cheap

**Comment by davetgc** [comment]
I'm sorry you're having problems. Have you tried validating your Steam files?

If this doesn't solve the issue of missing files, you will likely need to contact Steam support. They will be best placed to help you, as we have no control over the Steam download system.

Can you also please post a screenshot of the DLC's being in your library, just in case 

Thanks,

**Comment by davetgc** [comment]
@Guruone2023 - This issue should be fixed now, could you please confirm?

**Comment by davetgc** [comment]
Confirmed as fixed.

**Comment by Guruone2023** [comment]
Thank you 

Sent from Yahoo Mail for iPhone


On Monday, November 20, 2023, 9:04 am, davetgc ***@***.***> wrote:




Closed #5065 as completed.
