### ISSUE TITLE
Instant crash on latest update this evening 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5066]
@LeeBamberTGC 
Instant crash on latest update this evening .. All maps failing .. Pause then kick out.
Confirmed by Necrym
Rolled back to Retail and thats fine.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/40f932c8-213b-454a-b7ba-0888bb9390e8

**Comment by Necrym59** [comment]
Appears to be some 'SendMessage' issues in the global.luaa lot of behaviours now no longer work anf either make Max crash instantly (as in the aircraft.lua) or throw errors when running. Also Hud calls are not working and Text commands are not working.
I suspect its a temp thing with what Lee is doing, i suspect he realises this. But good for him to know on here as well

**Comment by OmnixiaDEV** [comment]
Same issue here

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Yes this change has been put off for so long because it is quite destructive, but ultimately a benefit to script speeds and performance.   For the "All maps failing" issue, can you load and run the Switch Escape demo level and see the same crash issue?  Just tried and it is fine on my end:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/239ae9eb-8ca1-4bae-afca-d0edbc830892)

**Comment by LeeBamberTGC** [comment]
@Necrym59 I do not have new-haunted-main level, can you send me something stock that confirms the crash, thanks :)

**Comment by Necrym59** [comment]
@LeeBamberTGC 
Attached test level that will crash everytime run (due to the 'aircraft behavior' on the helecopter. 
Map also showsthe anomoly of the invisible gun trurret. Enjoy :)
[TestingLevel1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13358130/TestingLevel1.zip)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
**Yes this change has been put off for so long because it is quite destructive, but ultimately a benefit to script speeds and performance.** 

Hi Lee 
Ok this makes more sense of why this is happening, the majority of my projects have triggered events on start which is why i said **all maps failing**, I can remove some of these that will then make the level run without crashing. One in particular for me is the **Message behaviour**  which is easily testable and i have supplied a test zip. As Necrym59 states this would appear to be linked to **send message** used in behaviours.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Can you check none of your scripts use the SendMessageXX commands directly? In the new EXP build, they would do nothing at best and crash at worst.

**Comment by Necrym59** [comment]
@LeeBamberTGC 
Checked the behaviours none have any direct SendMessage Commands.
I ran a test on Indian Strike force and receivd this upon starting it
![Error1](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/191b2c86-740e-42fe-b5ac-9be4f956f776)
Further in after killing the first soldier this came up
![Error2](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/f6f0c558-ef05-4a4e-8466-cb96003963f7)
then crashed.
neither are anything to do with my behaviors.

**Comment by synchromesh62** [comment]
I get this with indian Strike force clicking Play Game from the Hub 
If i click ok it goes to the menu.

![C1](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/7e8c9a1b-51f7-4c4b-8366-78be84f202db)

**Comment by Necrym59** [comment]
@synchromesh62 
I can confirn the outright crash when activateing that behavior in your  "Crash Test" map

**Comment by synchromesh62** [comment]
I have also noticed the **Destroy** command no longer seems to function.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Can you confirm that when you drop in some ammo in an empty level you see the player can collect them:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6a246651-8787-41a4-a020-9e496bdc80b9)

The ammo script uses the DESTROY command to remove the ammo from the level.

**Comment by synchromesh62** [comment]
> @synchromesh62 Can you confirm that when you drop in some ammo in an empty level you see the player can collect them:
> 
> ![image](https://user-images.githubusercontent.com/35840583/283555814-6a246651-8787-41a4-a020-9e496bdc80b9.png)
> 
> The ammo script uses the DESTROY command to remove the ammo from the level.

Hi Lee .. Yes that works ..
Perhaps you can advise me then i use this command to destroy certain assets for example..  
**Destroy(151)**
This did work before the update and i have double checked they are still the correct numbers.
Has anything changed oe is there a new command for this ?

**Comment by LeeBamberTGC** [comment]
@synchromesh62 There is a VERY good chance the entity element numbers change between level saves in recent builds as new code cleans up gaps in the lists and removes corrupt entries too.   Using direct numbers is almost certain to break at some point.   As a further test I created a fresh level and added three objects to collect:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/99ace5f2-89bf-4243-8157-9127a1ecae28)
As you can see, it also uses the DESTROY command to remove them:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5d9e7365-4c6c-4e66-8671-9a0385f8e161)
Check the latest EXP build as I have made some significant fixes to correct some script command call errors.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
I have not changed anything since this report and all the items I had set to **Destroy** now work perfectly as intended.
Thanks Lee :)
