### ISSUE TITLE
GG Max - EXP Build - Videoinzone & Videoscene Error

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#5067]
![bugg](https://github.com/TheGameCreators/GameGuruRepo/assets/122213320/b33af71a-3441-4193-9fce-440e853a6d45)

It happens in the moment when video should appear.

**Comment by liviugamingro** [comment]
I can say that I also receive the same in some scriptures. also at global.lua

**Comment by Necrym59** [comment]
The bahaviour is fine other changes are effecting a lot of behaviors at the moment.

**Comment by LeeBamberTGC** [comment]
@NewWave2137 Fixed for next EXP build :)
