### ISSUE TITLE
enemies stuck in one spot!

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5069]
this chap (newly created) just wont move from this spot, does all the animations but is stuck!!

https://www.youtube.com/watch?v=GLOKFld-wdE

also when receiving damage whilst the shaky cam is triggered (I use it for a injured effect from a trigger zone, it seams to conflict with standard player damage causing unwanted camera effects as showed here)

https://www.youtube.com/watch?v=GLOKFld-wdE

**Comment by Necrym59** [comment]
Can you send me the FPE for the new character

**Comment by casigus** [comment]
ITS all the characters in ggmax, not just this one!

well the rats are doing ok thou!
________________________________

**Comment by LeeBamberTGC** [comment]
@casigus This can happen if there is no nav mesh for the character. Can you use the Show Debug Visuals to see if there is a nav mesh under the characters placed:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e3151ab0-93b5-40d6-b448-c89d90a98670)

**Comment by OmnixiaDEV** [comment]
I can confirm this bug happens to me with the older zombie assets in the library, I have standardized the Granny Zombie as my testing model as for some reason this bug does not affect that model

**Comment by LeeBamberTGC** [comment]
@OmnixiaDEV Which zombie does not move when you add it to an empty level?

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/016288a9-2a02-42e0-a5d6-d0211d5eba53)
