### ISSUE TITLE
Swap Behaviour

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#5070]
Swap Behaviour appears to have stopped working.
Tried it on different levels but no joy.
I'm guessing it has something to do with the latest update.

**Comment by Necrym59** [comment]
The bahaviour is fine other changes are effecting a lot of behaviors at the moment.

**Comment by MartinCranshaw** [comment]
Still not working for me. It used to work on one of my levels but stopped. I can't get it to work on new level either. I've tried numerous changes to settings isimmob\Always active etc. but no luck. No doubt I'm doing something daft cheers.

**Comment by synchromesh62** [comment]
> Still not working for me. It used to work on one of my levels but stopped. I can't get it to work on new level either. I've tried numerous changes to settings isimmob\Always active etc. but no luck. No doubt I'm doing something daft cheers.

Yes as mentioned by Necrym59 .. Behaviours are fine but the work Lee is doing on the Global is effecting them.
Roll back to the Retail until its complete. They will work fine in that build.

**Comment by MartinCranshaw** [comment]
Thanks for the reply. It's not desperate at the moment as long as I know
that it will work again in the future I can hang on . Cheers
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw For the next EXP build the SWAP behaviour will work again, and many other LUA commands that used a single parameter input to specify the entity number.

**Comment by MartinCranshaw** [comment]
Thanks Lee all fixed. Onwards and upwards.
