### ISSUE TITLE
VIDEOZONE ERROR.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5071]
this pops up when a video zone is placed. removing the video zone fixes the problem.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/8afb9af9-8da5-487e-ba2a-5016b701c2aa)

**Comment by liviugamingro** [comment]
I can say that I also receive the same in some scriptures. also at global.lua

**Comment by Necrym59** [comment]
The bahaviour itself is fine other changes are effecting a lot of behaviors at the moment.

**Comment by davetgc** [comment]
Closed as already reported.
