### ISSUE TITLE
saving the game error part 2

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5077]
saved my game work, this giant square hole has appeared on the map??

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/052f9bd4-6046-4999-8635-5994ba56a082)

no idea what steps lead to this other than saving it....

**Comment by casigus** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/0614bdfe-a131-4f0f-8a8a-cf0af0077dd1)

**Comment by synchromesh62** [comment]
Thats really strange .. You said you went back to retail .. You selected **"None"** for that right ?
Not any previous build.

**Comment by davetgc** [comment]
I've tried and I can't replicate this in retail, or EXP builds. Is anyone else having a similar problem? This is obviously concerning, even if it's only affecting certain systems.

**Comment by davetgc** [comment]
I'm closing this as a duplicate. @casigus - Please add any additional comments there.
