### ISSUE TITLE
GG Max - EXP Build - Code Switch Behavior doesn't work.

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#5078]
When I try to use item with code switch behavior the entire "write code to continue" part after pressing "e" doesn't appear.

**Comment by Necrym59** [comment]
The behavior is fine, just that changes in the exp build is effecting all behaviors that use the Text functions at the moment.

**Comment by davetgc** [comment]
Thanks, we're aware of the issue and are working on it.

**Comment by LeeBamberTGC** [comment]
@NewWave2137 In the updated LUA commands, the string was lost causing all text shown in this way not to show. Sorted for next EXP build :)
