### ISSUE TITLE
Im getting this error when I try to play any demo game supplied from GGM. Any idea on what to do?

### ISSUE THREAD

**Issue by mk831940** [TheGameCreators/GameGuruRepo#5079]
I'll post the two errors here, all I'm trying to do is launch any of the demo games. Yes, I'm using the exp build with latest update and verified.
[https://discord.com/channels/950796460683829329/1175219557892366386](url)
![first error](https://github.com/TheGameCreators/GameGuruRepo/assets/36519798/f47332e6-3140-4267-832f-27eefbae058c)
![second](https://github.com/TheGameCreators/GameGuruRepo/assets/36519798/ed070722-87c2-4d73-9a1d-8dc9895bf113)

**Comment by davetgc** [comment]
There is an ongoing issue with some Lua commands due to changes to the system. We are aware of it, and are working to fix it. If you move to the retail build, instead of the EXP build, the demos will run without issue.

**Comment by mk831940** [comment]
Thanks Dave.

**Comment by LeeBamberTGC** [comment]
@mk831940 Latest LUA improvements completely broke standalone menus, sorted for the next EXP build :)

**Comment by mk831940** [comment]
Yes, fixed.

**Comment by mk831940** [comment]
Thanks Lee.
