### ISSUE TITLE
Bulding Editor adds walls by itself

### ISSUE THREAD

**Issue by Peri32** [TheGameCreators/GameGuruRepo#5081]
Hello there, I tried the new building editor of Max and I noticed sometimes it adds some unwanted parts, for example, the wall I marked in the image added when I worked on the second floor 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/43548667/9ff926f7-ef20-4917-9ac1-7caf56b088f7)

**Comment by LeeBamberTGC** [comment]
@Peri32 Any chance you can create a video showing your steps to provoking the creation of this extra wall. I can then repeat what you did at my end and fix it, thanks!

**Comment by Peri32** [comment]
@LeeBamberTGC Sure I will try to trigger the bug, it didn't happened to me again since this time, I will try to find the trigger

**Comment by Peri32** [comment]
@LeeBamberTGC I tried to make it happend again but it didn't, maybe it fixed with the last update :P
