### ISSUE TITLE
Lost data from save/load games

### ISSUE THREAD

**Issue by Dr-Colosso** [TheGameCreators/GameGuruRepo#5082]
This may be related to issues you have already been working on, but I have noticed health, ammo, and some particles do not reload when starting a saved game in my standalone.

**Comment by LeeBamberTGC** [comment]
@Dr-Colosso In the latest EXP build I created a simple level with an enemy, a weapon and some ammo, then played to shoot one bullet and get hit a little, then saved the game, then used more ammo and got hit some more then reloaded the saved position and it retained them:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a84531bd-bddc-44bf-8edf-79e47b892f7e)

Can you reproduce this simple test, we can come to particles once we have ensured HEALTH and AMMO are preserved.

**Comment by Dr-Colosso** [comment]
Tested with the latest build health and ammo are restored when loading saved games, but the weapon in hand comes back with zero ammo until you switch weapons back and forth.

**Comment by LeeBamberTGC** [comment]
@Dr-Colosso Ammo reset bug fixed for the next EXP build :)

**Comment by Dr-Colosso** [comment]
Thanks for the help. I will share a link for the standalone when ready.
