### ISSUE TITLE
Bullets passing through top of enemies. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5083]
Hello, I have 2 separate enemy models and on both of them bullets pass through the top part of the enemies mesh. I have no idea why this is the case and have tried re importing the models with no luck.  It is  only the top part of the models heads. Everywhere else on their bodies registers hits properly. 

See video: https://www.youtube.com/watch?v=dPMJLnTy_DE

**Comment by davetgc** [comment]
Thanks for the report. What behaviours are you using for the character? As it's not a standard model, it's likely to be an issue related directly to the model.

You can try editing the created FPE and adding the command collisionscaling = 100,100, where the number represent the width and height, with 100 being the standard character creator scale. Try adjusting these settings to see if it helps.

**Comment by Kitakazi** [comment]
It doesn't matter what behavior I use, even using no behavior I will still have the same problem. 

I tried adding collisionscaling = 100,100 to the FPE but it didn't help. I also thought the problem was with the model but now I have imported another model which is the tentacle claw thing in the video and it has the same issue where the top part of the models "head" does not register when shot and bullets go straight through it. 

Any ideas on how to fix the model?

**Comment by davetgc** [comment]
Hi,

As I said, you might need to play around with the scaling, not just
100,100. If that doesn't work, we can look at other issues, but Lee will
need the model emailed to him.

Thanks,

**Comment by Kitakazi** [comment]
Ok I will mess around with the collisionscaling and I'll let you know if I have any luck. Thanks.

**Comment by LeeBamberTGC** [comment]
@Kitakazi I had a quick look and can confirm the bullet does not hit the head. I imported the DBO of this model and noticed a few things. First the raw scale is much larger than a standard MAX character so you could try reducing the export scale to be the same size as a typical MAX character:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/aa8cb4a6-676a-4b82-a037-1922e2b5ed4b)

Also, notice how the polygons are reverse-culled, this is my far the likeliest explanation, so enduring the polygon winding order is correct when you import may fix the collision issue which only detects a polygon hit on the visible side.

As you can see in test level, when double sided is switched off in the material, the character model is definately inverted:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b7323f21-826e-4e5b-b5d3-3016e473a62b)

Hope this helps with your export tests!!

**Comment by Kitakazi** [comment]
I already tried fixing the character so the l
Polygons aren't reversed. I did a small test once I fixed the mesh and It
didn't fix the problem of bullets going through the models head so I didn't
go through the hassle of reimporting it with all the animations etc.

I guess it could be the scale like you said  I'll try and reimport it at
the correct size.

**Comment by LeeBamberTGC** [comment]
@Kitakazi If you want to email me your original FBX model file, I can pass it through Ultimate Unwrap3D Pro and see if I can 'fix' the model for scale and collision, worth a shot!

**Comment by Kitakazi** [comment]
Ah thanks for the offer, but I believe I can fix this one myself. I have about 4 variations of this enemy the other 3 variations dont have this issue so I'm just going to remake this specific one, maybe make it look a little scarier and it should all be good.
