### ISSUE TITLE
Player weapons flickering on and off in player hands.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#5085]
Player weapons are now flickering on and off in the players hand as shown in the attached video. They are possibly being unequipped and reequipped. This only happens when the player is moving.

To replicate, give the player a weapons and move around.

https://github.com/TheGameCreators/GameGuruRepo/assets/99803873/dfedaca4-c9dc-4355-8032-3aedb224d975

**Comment by LeeBamberTGC** [comment]
@davetgc Can you attach a blank level with just one of the stock weapons that shows the same issue, thanks!
