### ISSUE TITLE
Allow non-static objects to add blockers to the navmesh for Characters/Enemies to avoid

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5088]
Enemies will walk through any object that isn't Static. See attached video for example: https://youtu.be/o8hVcJyPZqc

To reproduce: Select any object like a wall, or something big. 
Set the object to Physics On and make sure it has a physics shape attached to it. 
Place an enemy near the object and player on the other side.
The enemy will walk straight through the object. 

I used the Invisible behavior in my video for an example, maybe not the best choice since you can't see the object but you get the picture. Doesn't matter if entity is invisible or not...

**Comment by OobieDoob-Benoobie** [comment]
@Kitakazi As a workaround, you can place down a flag and rename it "NAVMESH LIMIT" and place one on each end of the wall or around a building, and logic link them. This should stop your NPCs from walking through walls.

**Comment by davetgc** [comment]
@LeeBamberTGC - Are you able to provide a small FPM demonstating this issue please?

**Comment by Kitakazi** [comment]
[test1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13519510/test1.zip)

**Comment by Kitakazi** [comment]
@OobieDoob-Benoobie Those Collision Shapes require the object to be static. This bug doesn't happen with static models.

**Comment by OobieDoob-Benoobie** [comment]
@Kitakazi Oh my apologies. I see what you're trying to do. 
Yea that W/O wont work then.
In this case placing NAVMESH LIMIT flags wont help you ether if the wall or object is to move.
I'm just barely learning LUA but I'll have a peak and see if there's something I can do.
Otherwise this is probably going to take a coder to figure out.
I wish you the very best luck with this.

**Comment by Kitakazi** [comment]
@OobieDoob-Benoobie @LeeBamberTGC 
https://youtu.be/f8FqH_W0lxA?si=XW8PbSr4Yz2OpSR5

It's not even about the objects be able to move or anything like that but big props that either are using a script or are animated but in place. For example this in this clip the bigger object that the enemy just walks through has the Behavior "glow" on it. Invisible walls require the object to not be static to use the Invisible wall script, so the enemies just walk through them now as well. 


I dunno enemies didn't use to pass through objects like this... 

Additionally the NAVMESH LIMIT flags are really janky. It seems to block characters from getting anywhere near where the navmesh limit flags are placed. So its worthless for trying to draw them around a big prop. And if the area is smaller like in my clip they just ignore the navmesh limit flags all together.  Probably because the engine thinks they are already inside the limit or something Im not sure but its only in larger area's that I can seem to get the Navmesh limit flags to even do anything.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Have you posted your game project to the WIP GAME PROJECTS on DISCORD?  I will be selecting a number of games from there that are far enough along to help with advice, more fixes, and features in early 2024 and it looks like your game more than qualifies :)  We will make sure MAX has the tools you need to create a great game experience!

**Comment by Kitakazi** [comment]
@LeeBamberTGC Yes sir I posted it a couple days ago, name of the project is Screos.

**Comment by LeeBamberTGC** [comment]
@Kitakazi That's great, I will be in touch before the years end with more deets :)

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Was just checking on this issue to see if this is still on the radar to be fixed? Not the most urgent issue but I am starting to feel this one more and more. Some area's in my game have big props that have scripts attached to them (they are animated, player must activate a switch to turn them on, etc) and currently with enemies able to just walk through them its hard to set up enemy encounters in these areas. 

This isn't the biggest issue at the moment but since it isn't tagged as a Bug I just don't want it to get forgotten about.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Check out the three door scripts, they are dynamic objects and use a navmesh command to dynamically create/destroy a blocker. The blocker does not change the navmesh but blocks an area on the nav mesh forcing AI to move around the obstacle. Start by viewing the navmesh when doors are opened and closed, then look at the LUA code, you might find we already have this feature for your purposes :)

**Comment by Kitakazi** [comment]
ah yea I didn't think about the door scripts and such. Thanks I'll look into it.
