### ISSUE TITLE
3rd Person Mode - Mouse Right Click

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#509]
In 3rd person if you press the right mouse click the character will automatically pivot to the direction of the cursor.

**Comment by LeeBamberTGC** [comment]
Is this not a good feature?

**Comment by Teabone3** [comment]
I've recently rewritten a 3rd person player script and have a preference over the fluid turn rather than the teleport/instant pivot in stock. The slow rotation (with a quick value) yields best results.

I originally thought this might not have been intentional. Its a good feature with the mouse just the nature of which the player turned seemed out of place as it wasn't animated or rotated in a visual way. Not a big deal however i was able to find a solution.

**Comment by LeeBamberTGC** [comment]
If you want to contribute the change here, I am happy to make it the official way this feature works :)
