### ISSUE TITLE
GameGuru MAX - Request - Hand Rotation for Melee Weapons

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#5091]
Currently, the rotation of the hand causes a larger melee weapon to take up a lot of screen real estate right through the middle of the screen. Here's an example with a custom dagger:

![arm_rotation_01](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/72f892f9-bd16-45b8-824a-f1a1f6878097)

If the hand were rotated a bit (and moved to the right side some), it would clear up the middle of the screen:

![arm_rotation_02](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/625350fd-7ea1-45cc-8d88-a0898f22e6c8)

**Comment by MonkeyFrogStudio** [comment]
BTW - the commands in the gunspec file don't seem to do anything on the new hands at all (handscale, hadposx, handrotx, etc.).

**Comment by DBird-1994** [comment]
@MonkeyFrogStudio Hey buddy if you have the wasteland weapon pack you'll get access to a whole bunch of extra hand animations.   The crowbar has the hand more upright like you want.   BTW, I think those commands you listed are for placing the weapons in the enemy's hands, not the player.
![crowbar](https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/e2b3cd61-81a0-449a-8ce8-04b154408ed6)

**Comment by MonkeyFrogStudio** [comment]
@DBird-1994 - That's a cool idea and I may do that. Thanks. Does the wasteland weapon pack work with the new hands/arms that allow you to swap them out? That's what I've been tinkering with.

**Comment by DBird-1994** [comment]
@MonkeyFrogStudio Well good news and bad news.  Yes all the weapons from the wasteland dlc's can use the new hands.  But it looks like about 75% of them are bugged right now.

On some of them, the weapons don't align to the hands properly, or the animations are completely wrong, like the running animations playing while it should be idle, etc.  I'd say avoid these dlc's for now.  These should really be fixed as they are paid dlc.

![screwdriver](https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/49a04b62-728f-404b-b160-4d5b5e313a20)

**Comment by MonkeyFrogStudio** [comment]
@DBird-1994 If you go into where the weapons are installed, there should be a hud.dbo file there. You can delete that. When you rerun MAX and the level with the weapon in it, it should recreate the hud.dbo file for that weapon. That should (is supposed to!) create a new hud.dbo that should work with the new hands.

The folder is in your user area (Documents/GameGuru Apps) under Files/gamecore/guns/ then look for your weapon(s). If it's a kit, it may first be under that kit name ... or maybe under user? I'm not exactly sure as I don't use any of the DLCs.

But try that and see if that sorts out your problem for you.

**Comment by DBird-1994** [comment]
@MonkeyFrogStudio I just tried as you suggested, and it did generate a new DBO.   But it didn't fix the problem,the weapons are still bugged.  I've opened an issue.  Sorry hope I didn't hijack your issue!

**Comment by MonkeyFrogStudio** [comment]
@DBird-1994 Nope! It's all good. The more issues we find and report, the better. :)
