### ISSUE TITLE
Most Wasteland Melee Weapons are Bugged

### ISSUE THREAD

**Issue by DBird-1994** [TheGameCreators/GameGuruRepo#5092]
On both of the Wasteland dlc's, most of the melee weapons are bugged.  Too many problems to list them all individually.  On some of them, the weapons don't align to the hands properly.  On MANY others, the animations are all wrong, like the running animation spilling over onto the idle animation.  Stuff like that.

![bat](https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/481de4ce-6aff-4084-8786-283993e46254)

**Comment by DBird-1994** [comment]
And here is a video showing an example of the animation problems that affect most of these weapons.  Notice how the running animation briefly spills over onto the idle animation.   And the actual animation while running is completely bugged, it keeps flipping between 2 animations from what I can see.

https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/696cef91-1780-491e-89ea-0820098bc15c

**Comment by davetgc** [comment]
Is this the EXP build?

**Comment by DBird-1994** [comment]
@davetgc  The weapons are bugged on both the EXP build, and also on the retail "last good public build"

**Comment by DBird-1994** [comment]
@davetgc Actually I just noticed you are also seeing the same problem on issue #5085 .   Just about all the wasteland weapons have these animation and visual glitches.

**Comment by davetgc** [comment]
@DBird-1994 - Thanks, that's useful to know.

**Comment by LeeBamberTGC** [comment]
@davetgc Just tested the wasteland weapons sample level and all weapons sit in the hands nicely:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/df881bda-df33-482e-841a-2c87e21b4537)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/67df2cfd-6d16-4e63-9e25-ce5b63a1f8ff)

Can you confirm all the weapons on the weapons wall can be picked up, and they walk, run and attack okay, thanks!

**Comment by DBird-1994** [comment]
Using the latest EXP everything looks good now, thank you for the fast fix @LeeBamberTGC

**Comment by davetgc** [comment]
@DBird-1994 - That's good to hear, are you happy for this to be closed?

**Comment by DBird-1994** [comment]
@davetgc Oh yes, sorry about that.  Sure this issue can be closed.
