### ISSUE TITLE
Player can't collect enemy weapons

### ISSUE THREAD

**Issue by Peri32** [TheGameCreators/GameGuruRepo#5094]
I remember it was possible to collect dead enemy weapons in an earlier version maybe I am wrong, anyway its a must-have feature

**Comment by davetgc** [comment]
For a player to collect a weapon now, it must be included somewhere in the level (hidden out of sight is good. I put mine on top of inaccessible places, like the tops of buildings.). The character will then spawn the weapon when killed. For example, if the character needs to drop the assault rifle, one must be included somewhere in the level.

**Comment by Peri32** [comment]
Hi, at this moment when I kill an enemy character when I step on the gun nothing happened, I can't collect it. I tried to find the option in the enemy character option something like "Can pickup weapon" like in the classic but I didn't find any option for it.

**Comment by davetgc** [comment]
There should be an option for this listed in the Behavior. Look there.

**Comment by Peri32** [comment]
I found it, have no idea how I missed it, my bad
