### ISSUE TITLE
Enemies can shoot/detect player from the walls (building creator) 

### ISSUE THREAD

**Issue by Peri32** [TheGameCreators/GameGuruRepo#5095]
Hi, I used the building creator, and I noticed the AI can shoot me from walls and doors sometimes, the AI sticks to the player's direction as close as it can, and gets too close to the walls and you can see his weapon pop out from the walls sometimes, it will be very good if the AI will understand the rooms better and know how to act inside to avoid this issues 

thanks.

**Comment by Peri32** [comment]
This is how it happen, hope it will help :) https://www.youtube.com/watch?v=zuZy071rnhY&ab_channel=EldarPeri

**Comment by LeeBamberTGC** [comment]
@Peri32 I can reproduce the issue now, thanks for the video:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/770f99f3-04e8-404b-b296-ab0b09832041)

**Comment by Peri32** [comment]
@LeeBamberTGC Glad to see it, you and the team do a great job :)
