### ISSUE TITLE
User Report on Steam ... Snowy Mountain Stroll Demo .. Ladder not working 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5096]
As stated above the ladder is not functioning in the EXP build when played from the Hub

**Comment by davetgc** [comment]
@LeeBamberTGC  - The ladder behaviour was changed and moved. This issue also applies to other ladders in the MAX collection.

**Comment by LeeBamberTGC** [comment]
@davetgc Added LADDER script back into the core scripts for the next EXP build.
