### ISSUE TITLE
Zombie Judders Returned ..

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5097]
Its back and worse than before unfortunately.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/d84a4580-feb0-4b2e-bbc2-0a65595e2d7e

**Comment by extremestrategy** [comment]
Can confirm, whenever the player hits the move buttons the zombies have issues and dance (so spam wasd to get them to truly dance).

**Comment by synchromesh62** [comment]
Confirmed as fixed in in this update.
Thanks Lee :)
