### ISSUE TITLE
Scripts not updating with some maps.

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5099]
Scripts that were used in older maps, sometimes don't update, or break altogether when the script gets updated, the main one is the Toxic Zone script, where in certain levels it throws errors and in others it doesn't throw any errors, in the below video I show that, and nothing different was done between the two.

https://youtu.be/teq3EihEj2o

Edit I noticed I used a different NPC post record, but I tested it with the primary soldier, and same issue.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
