### ISSUE TITLE
Fov resets itself during shooting ...

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#51]
In testgame mode I have encountered a new issue:

Whenever I shoot a weapon the FOV I have set (110) resets itself to a lower value...
Any Idea what the issue might be?

before shot:
![1](https://user-images.githubusercontent.com/35990507/35782012-12a494b0-09f2-11e8-9edf-21a9fdb04f18.PNG)

after shot.
![2](https://user-images.githubusercontent.com/35990507/35782013-12c21e18-09f2-11e8-82a6-46382fc96817.PNG)

**Comment by Duchenkuke** [comment]
I did some further testing today and came to this result:

When i set the weapon FOV to 100, its all fine, the FOV doesnt change then!
But when it is like 85 it reverts again when shooting, just like in the pic.

strange tho but for now I just set it to 100 and it keeps the issue away for now. This still should be fixed though.

**Comment by LeeBamberTGC** [comment]
Fixed for the next build. Was related to weapon decals FOV corrupting camera zero FOV
