### ISSUE TITLE
Particles are being scaled massively and causing level breakage. 

### ISSUE THREAD

**Issue by DarthPickles666** [TheGameCreators/GameGuruRepo#5101]
So for the last like two months or so I've been having issues with the particles. The scale has been increased MASSIVELY to the point that it's breaking my levels. It drops the entire software down to 1fps and I cant move, I cant use any of the buttons, nothing, so I cant even delete the particle that's broken. 

What you're seeing in the photo is one of the smoke particles that has been scaled up to the point it takes over the map. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/101579658/c020983b-e9f5-4202-9c51-c3c49d231368)

**Comment by davetgc** [comment]
I can't replicate this. Can you send a sample FPM please with that happening?

**Comment by LeeBamberTGC** [comment]
@DarthPickles666 I will check out the FPM now and report back here, and remove the particles from your level in case they are from an older corrupt level data so you can add newer particles in the level and carry on your project :)

**Comment by LeeBamberTGC** [comment]
@DarthPickles666 Find attached your level with all the particle removed, it was likely recent particle work "corrected" older particle markers and looked messy.  Placing new particles with the latest EXP build should help:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c109919a-2dc6-41b2-885a-11a1a57eae80)

A new EXP build feature allowed by the double click the "Particles" parent and delete all instances of all particles in one go, a nice feature for cases like this :)

[Prologue Part II (no particles).zip](https://github.com/TheGameCreators/GameGuruRepo/files/13686817/Prologue.Part.II.no.particles.zip)

P.S. I also changed MSAA to DISABLES as my old test AMD card cannot handle the MS feature!

**Comment by LeeBamberTGC** [comment]
@DarthPickles666 Just realised I wiped out all your custom media :)  You can try what I did above in the latest EXP build, or zip up and send me your users folder so I do not lose any media:

MISSING MEDIA:
entitybank\user\Thranta-class.fpe=replaceentitybank\user\Thranta-class.fpe
entitybank\user\Harrower.fpe=replaceentitybank\user\Harrower.fpe
entitybank\user\Defender-class light corvette.fpe=replaceentitybank\user\Defender-class light corvette.fpe
entitybank\user\Escape Pod.fpe=replaceentitybank\user\Escape Pod.fpe
entitybank\user\DeadRepublicTrooper1.fpe=replaceentitybank\user\DeadRepublicTrooper1.fpe
entitybank\user\DeadRepublicTrooper2.fpe=replaceentitybank\user\DeadRepublicTrooper2.fpe
entitybank\user\DeadRepublicTrooper3.fpe=replaceentitybank\user\DeadRepublicTrooper3.fpe
entitybank\user\DroidCorpse.fpe=replaceentitybank\user\DroidCorpse.fpe
entitybank\user\CrateSmall(Closed).fpe=replaceentitybank\user\CrateSmall(Closed).fpe
entitybank\user\Crate1(Closed).fpe=replaceentitybank\user\Crate1(Closed).fpe
entitybank\user\Crate1(Open).fpe=replaceentitybank\user\Crate1(Open).fpe
entitybank\user\LiberatorStarFighter(WingsClosed).fpe=replaceentitybank\user\LiberatorStarFighter(WingsClosed).fpe
entitybank\user\RepublicDropShip.fpe=replaceentitybank\user\RepublicDropShip.fpe
entitybank\user\CrateLargeOBJ.fpe=replaceentitybank\user\CrateLargeOBJ.fpe
entitybank\user\DeadRepublicTrooper5.fpe=replaceentitybank\user\DeadRepublicTrooper5.fpe
entitybank\user\Sith Fighter.fpe=replaceentitybank\user\Sith Fighter.fpe
entitybank\user\SorosuubCorpPortativeTablet.fpe=replaceentitybank\user\SorosuubCorpPortativeTablet.fpe
entitybank\user\forcewall.fpe=replaceentitybank\user\forcewall.fpe
