### ISSUE TITLE
Max Request - Allow Force to be Applied to Entites with LUA

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5102]
It would be nice to be able to spawn entities and have force applied to them so they can be forced into a certain direction when triggered or when spawned.

**Comment by AmenMoses** [comment]
What's wrong with PushObject?

**Comment by Kitakazi** [comment]
I didn't know PushObject was a command. Do you know of a stock script I can look at that uses it to see how it works?

**Comment by davetgc** [comment]
Does that answer your question?

**Comment by Kitakazi** [comment]
@davetgc 
@AmenMoses 
yea closing this for now. Thanks.
