### ISSUE TITLE
Add support to select all instances of a particular object and change certain properties (behaviour, cast shadow, etc)

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5104]
loaded up the titaic project again after a while, shocked to find all of the documents scripts are no longer working. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/b87fed2e-14e7-4cf4-bd2f-ce0f1a7d2b39)

everythings where it should be, nothing happens, document just won't show at all.

**Comment by casigus** [comment]
extra.

i have 100s of documents in the titanic game. All of them have defaulted to 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/0db8b5c5-f91f-41eb-9286-0bcf5c6879ae)


![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/f49ccda3-fbde-4e4f-9f8c-dd74ccc29a1c)


I get updates change things, but this is a massive set back. I have 100s of documents in the game.

**Comment by casigus** [comment]
ON TOP of that, PRESSING E no longer closes the document.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/1f891e84-6f1a-41cf-80dd-ee4df2a90163)


and for some reason its been changed to Q, which the script doesn't tell you about.

I've used this script on 100s of documents to tell the story AND its completely broke my titanic game.

WHY was this behaviour even changed??

it was perfectly fine as it was.


Imagine working on something for this long and now having to go through the entire project because one of the scripts changed?

Im not happy.

I cant even use a previous version of max.

its completely broken the core story telling mechanic of my game.

**Comment by LeeBamberTGC** [comment]
@casigus Can you create a small FPM using stock media only and the document script in use, I can then send to the original author of this script for you.

**Comment by casigus** [comment]
the document script works, the problem is I need to re-apply it to lots and lots of objects through out the entire game.

**Comment by LeeBamberTGC** [comment]
@casigus Funnily enough I was mulling over a feature to allow mass-selection of a specific object instance and change a property in one go. That should allow you to change all the behaviours of a specific object without finding each one in the level. Leave with me and I will report back :)

**Comment by casigus** [comment]
aha i mean that would be handy for everyone. regardless i still need to change every document in the titanic game with the updated scripttttttttt.

and believe meeeeee its like alot of documents to changeeeeeeeeee.

gonna wait till my heads abit clearer to start doing that.

but that ideas actually great yeah!

**Comment by LeeBamberTGC** [comment]
Here is the old and latest versions of this script in case it helps:

[document_v8.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13652837/document_v8.zip)
[document_v4.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13652839/document_v4.zip)

**Comment by casigus** [comment]
thank youuuuuuuuuuuuu

**Comment by LeeBamberTGC** [comment]
@casigus In the new EXP build you can modify whether a selection of objects can cast a shadow (something I need to work on performance on some demo levels), but I can also show you that you can multi-select many objects, then use the Developer Properties to manually change the script the objects use:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/04bd3eeb-12f6-452d-88da-41b935a007db)

I recommend changing them once to some other script, then saving, reloading, then entering the new script you would like them to use and save, reload again and all the objects will use that new script with default property values.

NOTE: Remember to make many backups when using the EXP build and/or saving or reloading large levels in projects.
