### ISSUE TITLE
Inventory error

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#5106]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/89519185/9cf1b312-de61-4586-baad-5a00eab0bf58)
when I add an rpg hud, my inventory system disappears completely and when I open the desired window there is nothing there. Also, the button responsible for inventory is inactive

**Comment by davetgc** [comment]
The inventory screen is part of the RPG huds, if you open up new RPG screens, your inventory will be refreshed. Is that the problem?

**Comment by Denis87z** [comment]
the problem is that there is no inventory in the screenshot. It doesn't work when you press the right key

**Comment by davetgc** [comment]
Are you on an AZERTY keyboard?

**Comment by Denis87z** [comment]
no

**Comment by LeeBamberTGC** [comment]
@Denis87z Are you using the EXP build uploaded yesterday?

**Comment by LeeBamberTGC** [comment]
@Denis87z @davetgc Fixed for the new EXP build, did not destroy anything, just hid them mistakenly from some new draw order code added elsewhere :)
