### ISSUE TITLE
crafting

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#5107]
when using scripts related to crafting items, the engine crashes without any error

**Comment by davetgc** [comment]
Which scripts?

**Comment by Denis87z** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/89519185/87fdc646-19c8-4d9b-9308-7e9ea3f20ce3)
recipe, resourse, resourse node

**Comment by davetgc** [comment]
Thanks, We'll look into it.

Are you running the experimental build or the retail build?

**Comment by Denis87z** [comment]
the retail build

**Comment by LeeBamberTGC** [comment]
@Denis87z Just ran through all the missions in the RPG Template which uses updated scripts and no crashes. Can you confirm?

**Comment by Necrym59** [comment]
are some of these scripts actually in the retail build yet??

**Comment by LeeBamberTGC** [comment]
@Necrym59 Yes, check out the folder for the RPG scripts now included in the out of the box files: "X:\SteamLibrary\steamapps\common\GameGuru MAX\Files\scriptbank\rpg"
