### ISSUE TITLE
The launcher crashes when running with the message

### ISSUE THREAD

**Issue by Mishahhi** [TheGameCreators/GameGuruRepo#5108]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/20231122/51369ab3-351b-4970-8366-84086ec514fc)

**Comment by Mishahhi** [comment]
Hm.. It's because of update AMD driver

**Comment by davetgc** [comment]
What AMD card are you using?

**Comment by Mishahhi** [comment]
> What AMD card are you using?

Radeon 5500XT (4GB)

**Comment by Mishahhi** [comment]
This is probably due to the drivers. The latest on AMD 'Adrenalin Edition' and last year's AMD 'PRO'
