### ISSUE TITLE
When you share a standalone to someone with an AMD card 5000/6000 series make sure you include those files

### ISSUE THREAD

**Issue by Jessika07** [TheGameCreators/GameGuruRepo#5109]
We had to add the files found into the guide for the AMD black screen fix again to make the executable works.

Fixing Black Screen For AMD RX 5000/6000 Series Owners 
A Guide for GameGuru MAX
By: iNeedCoffee3389
This is for all AMD RX 5000/6000 series owners who are experiencing black screens when loading into the program. Owners of other AMD cards might have the same issues, but it seems to be most common with the RX 5000/6000...

this is the link to the post/guide for the amd fix on steam;

https://steamcommunity.com/app/1247290/discussions/0/4038103682233596794/

basically you need to download 4 files for this to work.

https://drive.google.com/file/d/12ZW_eSLpRvUH4CWADOxfa8VpVanF8qce/view?usp=drive_link

https://drive.google.com/file/d/1201uOaf3YwXVNDZEOuIW6RP20d4Hls8h/view?usp=drive_link

https://drive.google.com/file/d/17O_fjX3u7GkImL3i_sIjy3w6pIsXzArx/view?usp=drive_link

https://drive.google.com/file/d/1_uR6rTzL4Yjk4Yit6kPy3lhsItoXzGuA/view?usp=drive_link

then you copy those into your executable game folder. it is what make it works if you have an AMD 6000 series card. Make me regret buying that card now.

What i don't really understand is that all my other games on steam work without a flaw. it is weird to me. Is really GGMAX the only program to use Vulkan engine? If so, how come AMD don't fix this problem once and for all. i downloaded the latest driver for my amd card yesterday.

So i don't get it.

But doing this will get it to work just fine... Hope this help!

**Comment by davetgc** [comment]
@LeeBamberTGC - Assigning the to you as a bug, as I'm guessing some files aren't transferring over to standalone.

**Comment by LeeBamberTGC** [comment]
@Jessika07 I tested the code that adds the DLLs to standalone games and it seems to work for me. Can you select the SWITCH ESCAPE demo and make a standalone from it. When you view the files you will see the DXGI.DLL and D3D11.DLL files are initially missing, but when you run the executable they will appear in the standalone root folder. Do you see these 2 files appear when you run the Switch Escape standalone demo level?

It seems the DLLs provided above are identical to the DLLs we are using to copy into the root area, so if the above does as described, it might be related to the need for the D3D9.DLL and D3D10CORE.DLL files also included above.

Let me know if (a) the two files appear on the initial run and that there is no black screen issue when you run the standalone executable on the second run, thanks!

**Comment by Jessika07** [comment]
Sorry it took so long, i have a hell of a job and christmas time is always crazy.

Yes, Mr. Lee, i did as told; (Switch Escape and make a standalone of it.)  once done, i click on it and make it run as if to play the game.  The 2 files you mentionned were created as expected.
But the game run black.  You can clearly see the hud with the one health point on the lower right.  The sound works fine too.  But no game 3d visual is shown.

After initial run, the folder look like this;

![AforLee1](https://github.com/TheGameCreators/GameGuruRepo/assets/67011561/71d203e9-dbc1-40c0-aabe-b35e1f965b3e)

**Comment by Jessika07** [comment]
now, adding just 2 files;
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/67011561/71f1bbb9-36b7-4ce3-adb1-1af66b991aca)

will make the Switch Escape demo standalone work just fine!

hope this help!

**Comment by Jessika07** [comment]
Oups...
i think i got your message wrong.  You mean the game normally work fine ON THE SECOND RUN BECAUSE IT CREATES THE FILES IT NEEDS?...

So basically running the game a second time should make it run fine without those 2 dll files?

Ok will try that again...  English is not my first language so...yeah...  ;)

**Comment by Jessika07** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/67011561/f42f6621-b657-438d-b677-34553dd6a071)

Ok, now that i start the game again, it does work fine!  Without having to add those 2 dll files into the folder.

We definitely need a text file named ; 'IF YOU HAVE AN AMD 5000_6000 SERIES PLEASE RUN THE GAME A SECOND TIME' into the folder of a created standalone...that would help a lot i think.

Thanks, i will advice on steam about this!

**Comment by LeeBamberTGC** [comment]
@Jessika07 Looks like you found the issue, nice work!  I will add some code that prompts the user when they first run the game that the AMD hot fix has been employed and exit the game on the first run, and then the second run we can skip the prompt. That should solve it until we find a better solution or we find the route cause of the AMD driver incompatibility with the current MAX DX11 native engine.

**Comment by LeeBamberTGC** [comment]
Fixed for next EXP build :)

**Comment by LeeBamberTGC** [comment]
Properly fixed now for next EXP build - was RSSetScissorRects and a recent AMD driver update!
