### ISSUE TITLE
Call to ravey_particles_update(); and possibly decalelement_control(); in wrong place.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#511]

**Comment by AmenMoses** [comment]
Currently in the code the call to update particles and decals is prior to the physics and Lua script execution.
This means that particles that are tied to entities will lag behind the positioning of the entity itself.

Simply moving the calls down to the end (just before the call to steam_gameloop();  (in M-Game.cpp) solves the problem and allows particle effect to be correctly  positioned wrt to entities.

**Comment by AmenMoses** [comment]
Dang this this is weird, can't add a description and it just closed itself on me!

**Comment by plemsoft** [comment]
That was a hard one :)
