### ISSUE TITLE
Some Questions about the GameGuru MAX arm rig

### ISSUE THREAD

**Issue by DBird-1994** [TheGameCreators/GameGuruRepo#5110]
I'm using the 3ds max verison of the arm rig that was recently released.   It works for the most part, but I have some questions.

1.  How would I go about making a left-handed weapon?  At the moment all melee weapons get attached to the right hand. This is true even if I explicity make left-handed animations, the weapon always follows the right hand.
2. How are weapons attached to the right hand?  In the rig, there is a bone named "Weapon_RightHand" but changing the location of this bone doesn't change the position of the weapon in game.  However, removing this bone from the rig causes the animation to be bugged.  So what is the purpose of this bone?

**Comment by davetgc** [comment]
At the moment only right handed weapons are supported.
