### ISSUE TITLE
GameGuru MAX - Request - Custom Folders in Level Objects Area

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#5111]
As levels get more and more complex with more and more objects added to the level, I think it would be great if we could create custom folders to organize our level objects:

![folders](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/ede5f441-6420-4d61-962e-a6236fa65195)

When I new object is added to a level, the end-user could drag-n-drop the object into an existing folder or they could create a new folder to place the object in ... or they could leave it right there in the root, if they like.

Of course, we would need a way to add folders, name and rename folders, and delete folders. We would also need a way to move from within a folder back to the root, etc.

**Comment by Necrym59** [comment]
Covered within the projects improvements, but i agree i like the graphical idea of folders

**Comment by MonkeyFrogStudio** [comment]
@Necrym59 We'll be able to create custom 'folders' to drag-n-drop out objects into, organizing them as we please, when projects are completed? If so, that's awesome. If it's something that MAX does automatically, like in the list view, then that's not what I'm requesting here.

For example, I might want to create a 'folder' to store objects based on a room name, like 'Science Lab Area' or some such. Or I might just want to keep all my creatures/monsters in one 'folder', etc.
