### ISSUE TITLE
The (Auto-Generated) Weapons are Causing Big Lag and Big LUA logic ms times. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5112]
I was working on a level and noticed the LUA logic ms times were constantly at 6ms even though I only had basic scripts in my level. 
After deleting every script to find the culprit the level still ran at about 6ms for LUA logic. That was when I found deleting all the Auto-Generated weapons fixed the issue. Giving a huge FPS boost and dropping the LUA logic to 1-2 ms. 

Video: https://www.youtube.com/watch?v=at-jYZ4YQBQ

It says they were "inactive" but they must still be active somehow, 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/2a269a17-c0b0-4713-bc39-bbd6c1e78162)

Also I don't even use 98% of the weapons that are auto-generated onto my levels I really wish I could stop this from happening. I own alot of weapon packs from the store and stuff that I'm not using for this project but it just puts every weapon on my levels. If I delete them it just puts them back after I reload lol.

SPECS:
13gen i7-13700KF 
NVIDIA GeForce RTX 4080 16gb vram
32gb RAM

**Comment by Kitakazi** [comment]
I removed my collection.tsv and .ele files and let it rebuild to see if some collectible item was causing the slowdown. But all that did was somehow make the issue alot worse somehow. Now LUA logic is at 10ms. 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/5deba64a-ade7-4d6e-b7a7-4a2e40ae9ff7)

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Can you look at this one? I'm not sure if this map is bugged or what the deal is. Any ideas?

**Comment by LeeBamberTGC** [comment]
@Kitakazi send me project folder and level. I will test with latest EXP build

**Comment by LeeBamberTGC** [comment]
@Kitakazi The very last EXP build shut down some excessive LUA logic calls related to autogen and spawned weapons, can you check again? :)

**Comment by Kitakazi** [comment]
I just checked it did not fix this level. Do you need the entire level or just the project folder and the .fpm?

**Comment by LeeBamberTGC** [comment]
@Kitakazi As you have a lot of custom stuff, we will resume via email to reproduce this one. I loaded in without the custom ones and there was no LUA Logic hit for weapons, just the shotgun at element #10.

**Comment by Kitakazi** [comment]
Just checking on this and seeing if you were able to reproduce the issue with the files I sent?

**Comment by LeeBamberTGC** [comment]
@Kitakazi I have your email, pride of place in my inbox, just clearing out the usual start-of-year issues before getting fully back into things, thanks for your patience :)

**Comment by Kitakazi** [comment]
Haha no worries I completely understand.

**Comment by Kitakazi** [comment]
fixed now.
