### ISSUE TITLE
Post From Borg on Steam .. Objects falling through the Ground in the Rain Forest.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5113]
**Can we get the objects falling through the Ground problem fixed
Every time you drop an item on the ground in rain forest. The item falls through the floor.**
Is there anyway this can be fixed it is very annoying especially since i gotta use it as a temporary object placement work around. Pretty crappy to craft a sawbench and then drop it to use it and poof it falls through the ground....

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I created an empty level in the RAINFOREST biome and added a barrel, it did not fall through the floor:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0a55b0a3-03da-427a-baa9-8bfdc7059596)

Perhaps BORG can come to the issues board and provide additional information?

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Ye i couldnt get the problem either. But he insisted it was something that needed fixing.
I will let him know.

**Comment by LeeBamberTGC** [comment]
@superdave69 Thanks for making the videos, shows the issue very clearly. In the last video at the end, it looks like the bread and steam did not appear on the floor when dropped. Is this what you mean when you say they fall through the floor?

**Comment by superdave69** [comment]
Yes that is what  mean. I noticed it happens with some resource nodes while mining and areas that are leveled for buildings.

**Comment by superdave69** [comment]
[https://www.dropbox.com/scl/fo/ds81v11zesptx1r6xhr9j/h?rlkey=yzig0xedegugbwg3hmr3xsmvv&dl=0](url)

you can get the Standalone here for testing purposes.

**Comment by LeeBamberTGC** [comment]
@superdave69 I have reconstructed your game project on my end, and can run okay. Tell me exactly what to do from the start position (and maybe after collecting the axe) where I need to go to see the issue that can be easily reproduced. Thanks!!

**Comment by LeeBamberTGC** [comment]
I assume somewhere around here:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c658cf47-d5bc-4b07-addd-7a993b3cfe84)

**Comment by superdave69** [comment]
Yes in that area.

**Comment by superdave69** [comment]
It’s why I was asking for a way to place items
And as you craft you gotta be required to have a unique tool for each crafting station or you be crafting steaks at forges logs at stoves etc

**Comment by LeeBamberTGC** [comment]
@superdave69 Found the issue. Seems the drop was using the navmesh Y, which does not align exactly with the real geometry of the level. Sorted for the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c548b7d7-7abf-42bf-8d18-461a5fec5bab)

**Comment by superdave69** [comment]
So it was a collision issue glad we got that fixed.  Now we gotta figure out why a bear model with less than 4k poly count lags out the game. Might be that performance issue you’re already trying to tackle. I’ll keep sending bugs your way. Scouts honor.lol

**Comment by LeeBamberTGC** [comment]
@superdave69 Send me your bear model and I will check it out. Massive slowdown suggests model variant issues, I have seen characters coming in with a MASSIVE boundbox in one of the frames that caused capsule collision to go nuts and drain the physics system.  Maybe you can post a new issue on this so we can handle it separate from this one :)
