### ISSUE TITLE
Text Zones-Bug

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#5114]
For some reason 'Text Zones' are showing up as Win Zones on the map.

**Comment by synchromesh62** [comment]
> For some reason 'Text Zones' are showing up as Win Zones on the map.

Im seeing this, Using EXP build 

![T-ZONE](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/50aba246-a2f7-4150-b087-90fb761ded4e)

**Comment by MartinCranshaw** [comment]
Yes that appears in editing mode. But when you press M in test mode. The text zone shows up as a 'Winzone' Dot. Thanks.

**Comment by MartinCranshaw** [comment]
![Start and text zone](https://github.com/TheGameCreators/GameGuruRepo/assets/38034903/2363df4c-20ca-4b52-a7df-eefcb9bbc22c)
![Map](https://github.com/TheGameCreators/GameGuruRepo/assets/38034903/5bfb195d-2660-43e9-9828-a7dd8f33caf3)

**Comment by MartinCranshaw** [comment]
If i put a trigger zone in and change the behaviour to text in zone it works fine and doesn't show up as Winzone on the Map.

**Comment by synchromesh62** [comment]
> Yes that appears in editing mode. But when you press M in test mode. The text zone shows up as a 'Winzone' Dot. Thanks.

Ahh right .. You didnt put that info in initially so could not really reproduce it :)

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw Fixed for next EXP build.

**Comment by MartinCranshaw** [comment]
Thanks.
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by MartinCranshaw** [comment]
Fixed in latest exp. Cheers
