### ISSUE TITLE
SoundSlot 4 is No Longer Working

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5115]
SoundSlot 4 no longer is working.
 Steps to reproduce:
Put a sound is Slot4 under the Developer Settings of an entity in the Object Tools.
Add a script that uses PlaySound(e,4) or LoopSound(e,4) 
Once the script is activated no sound will play.

**Comment by davetgc** [comment]
I'm pretty sure this is an old issue, as slot four was repurposed. I'll mark it as a question.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Updated for the next EXP so developer settings reflect the repurposing of sound4 and added sound6 too.

**Comment by Kitakazi** [comment]
I see where sound slots 5 and 6 are available to be used but I cannot get them to actually play sound when I put audio in those slots.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you attach a small level and script that uses these sounds (using stock media) and I can quickly test what you are seeing and make corrections as needed, thanks!

**Comment by Kitakazi** [comment]
Yea tomorrow night when I get back home I'll send it over

**Comment by Kitakazi** [comment]
[new_test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13767034/new_test.zip)

In the folder is a small test level with a triggerzone, a barrel and stock audio. Also in the folder is a script to play audio in sound slots 5 and 6. Will you see however that the sound in those slots will not actually play when the barrel is activated.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Most confusing I agree. I have updated the code so that specifying sound 5 and 6 in the properties lets you PlaySound 5 and 6 in the script. Just to fill the gap, when you try and play sound 4, it will play sound 5 (as you know there is NO way to specify a sound 4 as it was usurped ages ago for the DLUA system, a legacy crime we need to live with now) :)  Will be in the next EXP build.

**Comment by Kitakazi** [comment]
Ah I see. Well thanks for fixing this, closing as it is completed.
