### ISSUE TITLE
updates completely broke my game

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5117]
the recent updates completely broke my game.

documents no longer showing the attached images. (100s of documents in the game)
trigger zones no longer activating connected triggers.
teleporter zone no longer working (i have AN ENTIRE GOD DAM level where it teleports you around the map to differnt parts of the ship during the singking, all broken)

the trigger zones attached to the rise water script no longer works, win object no longer works,

PRETTY much everything in my Titanic game is BROKEN. I can't go back to a previous version of ggmax because it shows a completely empty map for every level.

I've cancelled the game today because theres not a snow balls hell in chance I'm going to go through the ENTIRE project and re-do every single trigger zone, document and exit zones (BECAUSE its completely wiped them out)

the same with the documents, its completely wiped every single one through out the entire game. 

im very very very very very very annoyed. its every single level of the project thats now completely wreckeed.

**Comment by casigus** [comment]
this is what day/night cycle now does when triggered in my game:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/19c38759-342a-41e7-aa2d-dac2c0792e13)


so, thats good isn't it. when you have entire leevels with day and nigyht cycles and ALL of them are now broken too???

WHY. IS EVERYTHING BROKEN.

**Comment by casigus** [comment]
this is the previous build of ggmax, 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/a7714614-0346-4c7a-9298-71a190ed81dd)

still broken...

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/cceae35d-cf84-4e0b-bf81-87ce98359632)

**Comment by casigus** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/41980a20-9944-4863-947e-6a248975c503)

**Comment by casigus** [comment]
and this.

https://youtu.be/rPXc1c_2xMM

**Comment by casigus** [comment]
yes. im reporting every single thing broken in my game. because your updates have completely broke EVERYTHING.

**Comment by davetgc** [comment]
Thanks for the reports. I'm obviously aware of the issues you're having and we want to work to resolve them.

**Comment by LeeBamberTGC** [comment]
@davetgc We are sorting this over email now as it is a large project. Got it up and running on my system now, just figuring out a freeze issue on the other end.  Was related to a few key scripts being added that overwrote really old ones that this multi-year project was using. The new Project System we are planning should ensure this does not happen in future.

**Comment by casigus** [comment]
I'm glad this will help other users out with projects in the future!!! so some goods come from it!!

**Comment by LeeBamberTGC** [comment]
@casigus Yes, your game is a perfect project to test the weaknesses of MAX right now!

**Comment by casigus** [comment]
ahah every cloud has a silver lining!

**Comment by LeeBamberTGC** [comment]
NOTE: All latest scripts respect all legacy versions of the scripts going back 2 years, with correct parameter ordering. Feel free to post script name and location if you discover a newer script that changes the order of legacy parameters.
