### ISSUE TITLE
winswitch

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5118]
this.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/0af9dc07-ed7b-4853-b23f-f16a011d7f12)

**Comment by casigus** [comment]
clicking OK casues a blank screen to now replace a game level....

**Comment by casigus** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/f78b3ee1-e570-4dbb-a061-ec6a7b45556d)

this is what now loads...

**Comment by Necrym59** [comment]
This isnt very helpful unless esxplained a bit better , can you be more specific as how and when it happened as it makes no sense.

**Comment by casigus** [comment]
open any of my titanic project levels, go to test. this warning appears and then the entire game level is black.

**Comment by LeeBamberTGC** [comment]
@Necrym59 I have emailed you a new script for this that retains backward compatibility with the really early versions of this script, and have since solved the black screen issue which was actually related to the day night script having its params mixed up.
