### ISSUE TITLE
GameGuru MAX and Classic... ATI Radeon 5500XT Powercolor model.

### ISSUE THREAD

**Issue by sweldon001** [TheGameCreators/GameGuruRepo#5119]
I try to launch GameGuru Classic, it gets stuck in launch cycling. When I run GameGuru Max it launches then can edit and play a single level map in Test mode, but when test is over, and you try to create a stand-alone game it never launches upon its single use and creation build. I have attached my DXDiag File as, showing what I have for a build. I cannot edit nor can I use my GameGuru Classic, nor can I run and edit and build with GameGuru Max. Please note, I used to have it working, but now it's like beating a dead horse to no avail.

[DxDiag.txt](https://github.com/TheGameCreators/GameGuruRepo/files/13727466/DxDiag.txt)

Here is also my MS Info File attached as well below (If it's not too big to post /otherwise I'll post it in chunks below)  : 

[msinfo32-MySystem.txt](https://github.com/TheGameCreators/GameGuruRepo/files/13727517/msinfo32-MySystem.txt)

**Comment by sweldon001** [comment]
The Posted ATI 5000 And 6000 Fix post ... Doesn't fix this issue as well. I have posted a screenshot of what is in the Root of the test game I have been working with, the window of the Fix File, to show there isn't much difference other than a few of the 4 files mentioned in the fix.

Here is a Screenshot of fix and file to use as well as root of single level game build below here : 

![ATI 5500XT or ATI 5000   6000 Fix files](https://github.com/TheGameCreators/GameGuruRepo/assets/4951678/09a11457-d9ad-4365-b8cd-f163e87fa2e5)

In this image it show on my root it has already the following files , but not the following extra files 👍 


It has : 

d3d11.dll
dxgi.dll

doesn't have the following :

d3d9.dll
d3d10core.dll

**Comment by sweldon001** [comment]
After replacing and or using just 2 of the file, you get this error posted below. With either 2 of the replacement files, and with all four of the replacement files.

![run time error standalone file with one level in it ](https://github.com/TheGameCreators/GameGuruRepo/assets/4951678/84edb935-f63b-4a00-a77b-0251f665f051)

**Comment by sweldon001** [comment]
I only hope allthis effort I am going thru will help fix this issue so I and other might enjoy GameGuru MAx / GameGuru Classic once again.

**Comment by sweldon001** [comment]
Here is another more that might help everyone out 2 log file from single player one level game I built that dies after, and before AMDFIx.INI extra......
[contents.txt](https://github.com/TheGameCreators/GameGuruRepo/files/13727703/contents.txt)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/13727704/Guru-MapEditor.log)
[test one SCOPE_d3d11.log](https://github.com/TheGameCreators/GameGuruRepo/files/13727705/test.one.SCOPE_d3d11.log)
[test one SCOPE_dxgi.log](https://github.com/TheGameCreators/GameGuruRepo/files/13727706/test.one.SCOPE_dxgi.log)
it is content file .log , guru-MapEditor Log, Test Game d3d11.log and game DXGI Log file.. Hope this help dev's.

**Comment by sweldon001** [comment]
Just now noticed the functionality of Keyboard shortcuts in GaemGuru Max don't work like PGUP PGDWN to move object up and down in view point area don't work as well.

**Comment by sweldon001** [comment]
Attempting to uninstall and reinstall GameGuru MAX and GameGuru Classic to see if it is a registry issue.

**Comment by error55o** [comment]
I have the same issue but... it's worse, I use 4 screens and it 100% black screens all of my monitors and I have to push the reset button to regain control of my pc, I'm running windows 11 pro 23H2 OS Build 22631.2861 with 64 gigs of ram, Processor is an AMD Ryzen 5 5600G with Radeon Graphics, 3901 Mhz, 6 Core(s), 12 Logical Processor(s), my graphics card is a Radeon RX 5500 XT with 8 gigs GDDR, you'd think I more than meet the needed specs

**Comment by LeeBamberTGC** [comment]
@sweldon001 You mentioned that "the functionality of Keyboard shortcuts in GaemGuru Max don't work like PGUP PGDWN to move object up and down" so I am assuming you are able to run MAX and see the level editor area with no black screen, can you confirm this?

@error55o Have you tried the EXP build as we have recently added support for the MSI variants of the XT graphics card which might resolve your black screen issue,

**Comment by sweldon001** [comment]
sorry thats xfx brand 5500Xt I am now attempting Asus 1060 video card 3gb...

**Comment by sweldon001** [comment]
Confirmed yes I can luanch GameGuru, but it seems like it mainly messed up for control and launching standalones ectra.

**Comment by error55o** [comment]
> @sweldon001 You mentioned that "the functionality of Keyboard shortcuts in GaemGuru Max don't work like PGUP PGDWN to move object up and down" so I am assuming you are able to run MAX and see the level editor area with no black screen, can you confirm this?
> 
> @error55o Have you tried the EXP build as we have recently added support for the MSI variants of the XT graphics card which might resolve your black screen issue,

if by EXP build you are referring to beta build, I tried this today and it still crashes out but my other monitors and control of my PC comes back though, I am currently typing this up with my main monitor black but my other monitors are fine, there is an hour glass mouse cursor on the screen with the game on though and nothing else is happening, while typing this, I had the prompt that the program isn't responding.

What kind of logs would you need to get a fuller understanding of what is happening with me?

**Comment by LeeBamberTGC** [comment]
@sweldon001 When you say "it seems like it mainly messed up for control and launching standalones", I will break it into two issues. Can you go into more detail on 'mainly messed up for control', do you mean the PGUP PGDN to move objects as you reported before?

@error55o Are you able to take a screenshot of your main monitor when it is in the black screen crash state you described, or take a mobile phone photo of it.  The black screen related to AMD is not a crash and just fails to render 3D. The crash suggests another type of issue.  You can find and attach the log file from here: "C:\Users\You\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log", thanks!

**Comment by sweldon001** [comment]
![ss of log file location](https://github.com/TheGameCreators/GameGuruRepo/assets/4951678/97844b58-4e11-41a6-9e22-8067037f070a)
no log file present.....

**Comment by sweldon001** [comment]
I just tried to run GameGuru MAX with different video card, Nvidia 1060 ASUS branded. It completely crashed out during launch....

**Comment by sweldon001** [comment]
When trying to rotate an object or move an object, Page Up and Page Down doesn't rotate the object in selection, nor will it move up down left or right with ;left mouse movement in editor. After compiler as standalone, it gives a crash, and no log file in folder of standalone game.

**Comment by sweldon001** [comment]
replace / re installed XFX ATI Radeon 5500 XT 8Gb Video card trying to rebuild standaalone.

**Comment by sweldon001** [comment]
![decrypt dbo missing](https://github.com/TheGameCreators/GameGuruRepo/assets/4951678/1e924d25-27fb-482b-a72d-db008329f596)
I fixed this one it is error with File Access.. It was also giving Error code 7018 ().
I have to manually take control of the folder in Temp area.

**Comment by error55o** [comment]
> @sweldon001 When you say "it seems like it mainly messed up for control and launching standalones", I will break it into two issues. Can you go into more detail on 'mainly messed up for control', do you mean the PGUP PGDN to move objects as you reported before?
> 
> @error55o Are you able to take a screenshot of your main monitor when it is in the black screen crash state you described, or take a mobile phone photo of it. The black screen related to AMD is not a crash and just fails to render 3D. The crash suggests another type of issue. You can find and attach the log file from here: "C:\Users\You\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log", thanks!

I was going to take a screenshot but... it'd just be a black square but I have taken a screen grab of the error window that is constant on all crashes, below is the log file requested and please feel free to ask if you need something else

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/39387292/86de8eb9-bcdd-4960-86b0-5cec996bd82d)

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/13786045/Guru-MapEditor.log)

**Comment by sweldon001** [comment]
When you say "it seems like it mainly messed up for control and launching standalones", I will break it into two issues. Can you go into more detail on 'mainly messed up for control', do you mean the PGUP PGDN to move objects as you reported before?

Yes I meant PGUP PGDN . They now function after taking control of folder above mentioned .

**Comment by sweldon001** [comment]
![run time error standalone file with one level in it ](https://github.com/TheGameCreators/GameGuruRepo/assets/4951678/617ee53c-a3f3-484e-ae49-1552cb3dc770)

**Comment by LeeBamberTGC** [comment]
@error55o Can you create a new issue and post the link here so we can split these? Seems @sweldon001 made progress on the original report posted here and I can close this one if all is well with the latest setup and all is working with the temp folder override and a good GPU configuration.

**Comment by LeeBamberTGC** [comment]
Properly fixed now for next EXP build - was RSSetScissorRects and a recent AMD driver update!
