### ISSUE TITLE
MAX EXP - Change Texture Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5120]
In current EXP Change Texture no longer works correctly.
- possibly another lua issue added in current bug bash?

https://youtu.be/uI_l6vylHwI?si=cXp0055BNDxUUS7-

Thanks for checking....

**Comment by LeeBamberTGC** [comment]
@OldFlak Can you send me the script file, you should find it at "Max\Files\scriptbank\objects\change_texture.lua", thanks!  We modified this one very recently to allow for backward compatibility with older projects.

**Comment by OldFlak** [comment]
Hi Lee, I am using the Community version - tried Updating Workshop Items - it still does the same

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/624bd059-187b-4fe0-8d1b-952a6214473b)

**Comment by OldFlak** [comment]
Just verified to test - and same for both behaviors
The video in Opening Post is in a new level created just to test the issue.

Here is another one just recorded - that exhibits the same issue:

Notice also that Plrinzone script now continually triggers until you leave it when set to Multi Trigger
- which explains why my door scripts stopped working in the same level

https://youtu.be/FLnc5ESql5M

Thanks for checking :)

**Comment by Necrym59** [comment]
Playerinzone is fixed and has been updated in the workshop and supplied in your other thread

**Comment by LeeBamberTGC** [comment]
@Necrym59 What version have you uploaded, just want to make sure I have the latest :)

**Comment by Necrym59** [comment]
@LeeBamberTGC
Change Texture v5  14/07/23
Nothings changed since then

**Comment by OldFlak** [comment]
Sorry team - still busted - it looks to me that it is not using the emissive textures properly

Just recorded this https://youtu.be/964gECft-sE
- Change Texture V5
- Plrinzone V7

Notice
- when the level first starts it is playing Texture 1 and using the _emissive
- when toggled by the zone it does change to Texture 2 but doesn't use the _emissive for it
- when changing back to Texture 1 it is not using the _emissive for that one either

Thanks checking it out :)

**Comment by LeeBamberTGC** [comment]
@Necrym59 See latest reported finding for this script, thanks Steve!

**Comment by Necrym59** [comment]
Ok Fixed and updated to v6 in the workshop core

**Comment by OldFlak** [comment]
@LeeBamberTGC Tested the latest V6 behavior and it works fine in new levels - but not old ones.

I am happy to go with that as I will be making every level from scratch when Projects get here, so will close this issue.

@Necrym59 Thanks for your hard work
@LeeBamberTGC Thanks for an AWESOME engine (yes I shouted it from the rooftop lol)
- MAX is just so cool and getting better by the minute :)
