### ISSUE TITLE
GameGuru Max Not working...crashes

### ISSUE THREAD

**Issue by Nader-B10** [TheGameCreators/GameGuruRepo#5121]
When you download and open it for the first time, it works normally, but when you turn it off and on again at another time, it crashes forever and will no longer work...See the embedded image to see what the problem is :

![Screenshot 2023-12-23 093352](https://github.com/TheGameCreators/GameGuruRepo/assets/113104542/6ad34a43-2082-4a64-856d-494a810359b2)

**Comment by davetgc** [comment]
Thanks for the report, can you please post your system specs.

**Comment by Nader-B10** [comment]
win 11
geforce GTX 1650
amd Ryzen 7 3750H
ram 16 GB


Note: Previously, several months ago, it was working normally without problems. The problem had previously appeared when transferring the drive from one storage space to another, but I do not know the reason for its recurrence this time.

**Comment by davetgc** [comment]
Thanks for the information

This sounds like missing drivers, have you tried validating your Steam
build?

**Comment by Nader-B10** [comment]
Do You mean verifying gameguru max files in steam ??..Yes, I did that, and I even tried deleting it and downloading it again, and the problem was solved almost upon first launch, and then later, when I opened it, I found the same problem.

**Comment by davetgc** [comment]
Ok, thanks for the clarification.

**Comment by LeeBamberTGC** [comment]
@Nader-B10 We have been doing some AMD black screen work and may have accidentally included your graphics card with the hot fix and thus breaking your experience. Try deleting the dxgi.dll and d3d11.dll from the Max root folder, then renaming "amdfix.ini" to "noamdfix.ini", then rerunning MAX. This might help restore to previous behaviour.

**Comment by Nader-B10** [comment]
> @Nader-B10 We have been doing some AMD black screen work and may have accidentally included your graphics card with the hot fix and thus breaking your experience. Try deleting the dxgi.dll and d3d11.dll from the Max root folder, then renaming "amdfix.ini" to "noamdfix.ini", then rerunning MAX. This might help restore to previous behaviour.

Thanks...this method worked for me

**Comment by Nader-B10** [comment]
> @Nader-B10 We have been doing some AMD black screen work and may have accidentally included your graphics card with the hot fix and thus breaking your experience. Try deleting the dxgi.dll and d3d11.dll from the Max root folder, then renaming "amdfix.ini" to "noamdfix.ini", then rerunning MAX. This might help restore to previous behaviour.

I discovered that I am facing the same problem with the building editor

**Comment by LeeBamberTGC** [comment]
@Nader-B10 That is very interesting, and seems like the HOTFIX that works for some AMD cards actually breaks other cards!  Looks like we need to go model by model to apply this fix more accurately, very interesting.  Can you confirm you definately have a "geforce GTX 1650" card installed in your PC and there is no AMD card (built-in or dedicated available in your system).

**Comment by Nader-B10** [comment]
@LeeBamberTGC  Yes, my graphics card is a GeForce GTX 1650, but there is also a graphics card integrated into the processor (AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx) 
![Screenshot 2023-12-29 011306](https://github.com/TheGameCreators/GameGuruRepo/assets/113104542/5174bc95-bbfd-46b9-8348-d9ef93e908e9)

**Comment by GraPhiX-Guru** [comment]
@Nader-B10  you need to change your 3d settings in nvidia control panel
![87403-img2](https://github.com/TheGameCreators/GameGuruRepo/assets/35724756/d5b0cae0-e16b-499f-94fe-983675b4818d)
Open the NVIDIA* Control Panel.
Under 3D Settings select Manage 3D Settings.
Click the Program Settings tab
Select or Add GameGuru MAX from the drop-down list.
Select the preferred graphics processor in the drop-down list. in your case select your Nvidia card.

once you do this Max will only use your nvidia card

**Comment by LeeBamberTGC** [comment]
@Nader-B10 Let me know if this advice worked for you. An interesting scenario with both AMD and NVIDIA GPUs in one box :)
