### ISSUE TITLE
Level selection missing from WinZone

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5122]
As the title states ..
**Go To Level** options missing from WinZone
We used to be able to traverse levels but this seems to be missing.

![level-logic](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/60dff664-6b8b-4d45-ab2a-fa3e95aef47c)

**Comment by synchromesh62** [comment]
EDIT .. 
Necrym69 has now updated the WinZone and sent it to Lee with the Level modes put back.
**All Hail Necrym69**  :)

**Comment by davetgc** [comment]
Hi @synchromesh62 - Can we count this as fixed, awaiting confirmation?
