### ISSUE TITLE
MAX - REQUEST - Enhanced Collision Mesh for OBJ and FBX

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5123]
Hi team,

MAX automagically places a Collision Mesh object when we name an OBJ mesh the same as the corresponding FBX model.

Could we have the same system when using OBJ Models by naming the Collision Mesh the same but with '2' on the end.
example:
- stairs.obj (the model with all complexity required)
- stairs2.obj (the collision mesh model to match)

I don't mind placing them by hand if I have to, but would be nice to have MAX do it automagically.

Thanks for considering :)

**Comment by MonkeyFrogStudio** [comment]
If you keep the collision mesh (obj) separate from your obj, then once you import it, it becomes a .dbo file. Then just place your collision mesh (obj) in the same folder as the newly created .dbo and set the collision type to Collision Mesh (I think that's 8 if you use the FPE file) and it will work. I know, not as convenient, but at least it will work.

I had asked them to actually let us append the obj collision mesh name with _cm (for 'collision mesh). So, if you had door.obj or door.fbx, you would have door_cm.obj.

**Comment by OldFlak** [comment]
@MonkeyFrogStudio - thanks man - appreciated!

DUH - What was I thinking!
I have been importing them and placing them manually - what a plank lol

But now you mention that you don't import the obj CM at all even if using them with FBX (clear evidence of a lack of Coffee)

Personally, I never change models at all when importing - like scale or anything - I just have them export at correct size for MAX.
- So that method would be ok
-  I think importing the CM into MAX would be a cleaner way of doing it - then it would create the FPE with messing under the hood (not afraid of doing that - just more convenient) which is why I mentioned the "2" for the differentiation of the two ( _cm makes more sense tho)

Thanks for the info :)

I will leave this open to see if team have any thoughts on adopting the _cm suffix in future - be a nice feature MAX! 👍

**Comment by davetgc** [comment]
I'm going to close this for now. If you feel it needs more attention, please open a new thread as a feature request. Thanks.

**Comment by OldFlak** [comment]
Hi Dave :) it is already a feature request - that is why I left it open?

**Comment by davetgc** [comment]
Reopened!

**Comment by OldFlak** [comment]
@davetgc Thank you :)

**Comment by OldFlak** [comment]
After more thought I think suggestion is on the money - so have added a feature request without the clutter.

Apologies for being a bugbear.

:) :)
