### ISSUE TITLE
MAX - EXP - Behaviors - Player In Zone bug

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5125]
Plrinzone behavior continually triggers until you leave it when set to Multi Trigger

https://youtu.be/FLnc5ESql5M

Thanks for checking :)

**Comment by Necrym59** [comment]
[plrinzone_v7.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13767316/plrinzone_v7.zip)
This should fix it with any luck

**Comment by OldFlak** [comment]
Thanks @Necrym59 Necrym will give it a test pronto 👍

**Comment by OldFlak** [comment]
@Necrym59 sorry to be a nuisance ")
But still busted - now it triggers continually after you leave it.

https://youtu.be/964gECft-sE

Thanks for checking

**Comment by Necrym59** [comment]
[plrinzone_v8.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13795512/plrinzone_v8.zip)
My stupid mistake should be ok now

**Comment by OldFlak** [comment]
Thanks Necrym, will check it out pronto :)

**Comment by OldFlak** [comment]
@Necrym59 - After quick test it seems to work mostly, but not reliably.
The first time I tried it worked the first time, but not after that (multi On) the second time it worked fine but only plays the audio on first entry.

My guess is MAX is holding onto the old one a bit there, so will have to remove it from the level and reset it up - will do that as later today and get back to you. Real life is dragging me out the door!

Thanks :)

**Comment by OldFlak** [comment]
@Necrym59 This sorted now thanks for your hard work :)
