### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#5126]
when i try to test level i get these two error messages 
scriptbank\community\\6704278\core\objects\\door_sliding .lua :102: attempt to index field '?' ( a nil value )

the other is the same except for door_sliding lua. :138 👍 

then the game just shuts down it has only started to happen after the last update up till then it was fine
 
             regards mark

**Comment by Necrym59** [comment]
remove the door scripts from all sliding doors, then save map then reapply the doors scripts to the objects and it should be ok
i assume they were operated by switches, if so select swttch as the door type.

**Comment by zeebon** [comment]
that did not work test level on other levels work a treat no problems its just the level after the update it worked fine up till then
________________________________

**Comment by Necrym59** [comment]
Hi Zeebon can you supply the map file if possible so i can have a look at it - thanks

**Comment by zeebon** [comment]
it's ok steve i have deleted that level and made a new one seems to be working now thanks anyway

regards zeebon
________________________________

**Comment by Necrym59** [comment]
ok no problems
rmember to close the issue down when you have a moment
