### ISSUE TITLE
Tree's being set to transparent is causing issues

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5127]
When a tree is placed down in GameGuru Max it's set to have transparency set automatically, this however is causing the shadows on the trees to vanish, I believe that the transparency should be turned off by default so that way the shadows don't have issues.

Steps to see the issue with shadows.

Place a tree in GameGuru Max.

Check that the materials are set to shadows turned on.

Select another object.

Run a test of the level.

Hit escape and check the tree.

**Comment by synchromesh62** [comment]
The trees already use the alpha slider .. 
At some point transparency has been enabled for some strange reason.

**Comment by LeeBamberTGC** [comment]
@extremestrategy Can I confirm you refer to trees that are objects you select and drop it, opposed to the tree system that provides thousands of level trees (see screenshot backdrop):
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/736110ad-9221-42e6-af15-2a79e97a09f5)

For the 'tree objects' let me know which trees have transparency incorrectly set for the trunk meshes. The idea was that we set the transparency for leave, but the trunk mesh as non transparent so it would cast SOME shadow without the cost of trying to cast a million semi-transparent tree leaves :)

**Comment by extremestrategy** [comment]
Yes, these are the placeable trees, the list of broken ones are acacia, birch, elm oak, and maple trees.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/12f5b417-f48d-4306-9ee8-d0db820fd460)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/bc77c5bd-d4ec-4adf-91c8-ad77958464a2)

**Comment by LeeBamberTGC** [comment]
@extremestrategy I tried the bark shadow only, but it looked wrong, so now al these trees have no transparency as the shadows look better than semi-transparency leaves in the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/4a6f524e-18dd-4f41-b784-11bc6aaed382)

**Comment by extremestrategy** [comment]
Trees are working now, thank you very much.
