### ISSUE TITLE
DLCs not being installed

### ISSUE THREAD

**Issue by larrygj** [TheGameCreators/GameGuruRepo#5129]
I have one DLC purchased in February and another bought yesterday, and neither are being installled. Why?

![Screenshot 2023-12-27 040845](https://github.com/TheGameCreators/GameGuruRepo/assets/44917988/f7f1250b-8a06-409e-bb7f-0d0b53def3c7)

**Comment by synchromesh62** [comment]
Are you on the EXP build or the Steam Retail ?

**Comment by synchromesh62** [comment]
Ok i just tried both the Retail and the Experimental build and both installed just fine for me ?
Try unticking the boxes ..wait 30 second then try ticking them again 
There is usually a 5 to 10 second wait for Steam to start the install. 
Also responded on Steam..

**Comment by davetgc** [comment]
Hi, I'm sorry that you're having problems.

Please follow @synchromesh62 advice and let us know if that helps? 

If it doesn't, could you please send a screenshot of your library, so I can see if the files are missing.

The first DLC should be called:

Booster Pack.

The animation booster pack is different as it isn't models, but additional animations for characters.  The easiest way to check if this is installed, is to place a character and change it's behavior to Play Animation. Find the Animation Choice drop-down under the setting for the behavior and click the small box to the right of the drop-down. This will take you to the animation browser.

The Animation Booster pack should be listed here as Booster, and contain 152 animation.

Please let us know how this goes for you.
