### ISSUE TITLE
Test Multiplayer Map Issue #2

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#513]
If you click or accidentally click (like me) the multiplayer button and then click "back" you're map will be completely empty and you will not be able to place entities on the map. Even if you click New Map. You must exit Game Guru and open again to be able to edit again.

I believe this is related to unsaved maps where the multiplayer button is pressed.

Issue is related to #505

**Comment by synchromesh62** [comment]
Icon was moved to avoid accidently clicking and a prompt added …
If you still miss both of those simply run tes tgame , press esc and the map returns.
