### ISSUE TITLE
some animations not exporting again

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5132]
We had this same big last year where some animations would not export.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/5c9dbb6f-5e87-495f-b7ef-5dd763612ce6)

this chap is suppose to be cleaning, in the export he's just frozen.

**Comment by LeeBamberTGC** [comment]
@casigus I cannot recog the character. Can you make a small FPM level using a stock character and a stock animation file, something I can test in level, and then test as a standalone export to see how the file disappears, it will help a lot :)

**Comment by casigus** [comment]
I'll export this guy over to you! it! the bug is very similar to one we had years ago where animations wouldn't work! Noticed some do and some just dont, this chap was made in fuse, with a basic animation of cleaning the floor, works fine in max, but the second he's exported in a standalone, he's just frozen. :)
