### ISSUE TITLE
Standalone Game Save Load Broken

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5133]
this has been a issue going back to gg classic, you save a game and then reload it and the scripts no longer work on the level you saved making the save/load system completely useless at any sort of big serious game project.

Just had a random error crash, didn't jot down the issue, but saved the game before hand.

Loaded the exported game back up, opened the save and everythings completely broken and all the scripts loose their functionanility.

as I've already said, this used to happen with game guru classic.

**Comment by casigus** [comment]
*update managed to load a saved game and the scripts seam to work, but this seams only possible upon starting a new game, HOWEVER then it goes to load the next level, it tried loading the 2nd level so yeah still useless!

**Comment by LeeBamberTGC** [comment]
@casigus Just for clarity, you are saying that a standalone game when saving the players position in the second level, and then reloading that saved game does not restore the player to the exact same spot and stats on level 2?

**Comment by casigus** [comment]
it restores the player to the same position, but completely breaks everything else, the save load system seams to switch all the .luas off.

Classic is the same oddly enough!

**Comment by LeeBamberTGC** [comment]
@casigus With my example above, can you tell me what to look out for when you say "everything else - switch all the .luas off.", thanks!

**Comment by casigus** [comment]
the doors scripiting turns off, enemy scripting, markers ect when loading in a saved game.

**Comment by LeeBamberTGC** [comment]
@casigus Thanks for the extra info, I will create a two level game project with a door, character and zone in each, and do some save/load game tests and post back here my results.

**Comment by LeeBamberTGC** [comment]
@casigus I created a two level standalone with a door, zone to trigger a character, my weapon and winzones in both. I saved at each stage (starting, opening door, shooting character, going to second level), and all worked fine, both loading and saving. I did spot a small bug that prevented the save game name from showing in the save/load screens and has been fixed. The load/save data issue you are experiencing must be something related to more complex level contents/scripts.  Can you create your own small game project from scratch (using 2 levels) that shows the save game data not working, thanks!

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/eeaa5c4d-3d02-40db-97bf-32199059b45a)

**Comment by casigus** [comment]
game guru classic has this same issue too, but I think it relates to the save/load system and the scripting for sure. What I'd do with the system is just have the save load system just completely re-load the game level for the start. Since this is an issue that also happened with classic, I think its something fundamentaly connected to how max and classic work!

i'll defo try and whack something together for you and see what happens and send over the results, but other than that I think the save/load system needs a overhall, or go with the idea of the save/load just loading the level from scratch. I know its not perfect, but when you have people like my self building larger game projects, it needs a system like this to work.

I'll get on this over the next week and get you the test levels, and see where we can go from there!

have a good weekend Lee! :)

**Comment by LeeBamberTGC** [comment]
@casigus New DEVTEST build uploaded with much improved game save refresh code, might help with some of your issues.

**Comment by casigus** [comment]
nice one Lee! I'll be sure to check it out, its hard to confirm if its fixed or not as this would require exporting a longer game than usual! but will defo try and test this for youu!
