### ISSUE TITLE
Items Collected Not Showing Inventory

### ISSUE THREAD

**Issue by superdave69** [TheGameCreators/GameGuruRepo#5134]
Items you collect and inventories for shops are no longer showing up.

**Comment by davetgc** [comment]
Thanks for the report, can you supply an FPM with this happening, using default media? It will make it easier for the team to replicate.

**Comment by superdave69** [comment]
Will do when I get back from the laundromat.

**Comment by superdave69** [comment]
https://youtu.be/iXRROuKdZCQ

**Comment by superdave69** [comment]
Hey Lee I got the items showing again the bugs not in the Inventory or collecting it's whenever an update for the scripts are issued it makes you have to reassign Item Identity in the collected item. I had to go and reassign everything. So it is working again from my end. but at this point every time there's an update it can break it again. So might be something to look at.

**Comment by LeeBamberTGC** [comment]
@superdave69 Glad you found a solution. In 2024 we will be introducing a new project system that separates your game project from the update system so that these 'sudden changes' can no longer break your project without your manual interventions :)

**Comment by superdave69** [comment]
Much appreciated. Also note that new video I posted it shows the performance lag I mentioned it may be script driven and not even the model. So I'm hoping the performance work you guys are working on helps it out. I just know there are going to be people that know less about programming and model editing than I do wanting to use this software. So getting thier models in as easy as possible is important. Maybe an auto configuration to help optomize polygons animations and textures. Where the engine  cleans this up as it's imported and set up. An enhancement suggestion that would probably go a long way.

**Comment by SampeyFS** [comment]
Ammunition is also not shown in the inventory
