### ISSUE TITLE
X Format Model Imports causing bad lag

### ISSUE THREAD

**Issue by superdave69** [TheGameCreators/GameGuruRepo#5135]
I have imported about 6 3D models following instructions to the T and have them in but they are causing bad lag in the engine. Need a model Optimizer built into the engine to help correct all model imports.

**Comment by davetgc** [comment]
What size are these models? How many polygons?

**Comment by mav3r1ck1981** [comment]
if this is an issue thats only affecting you, i would suggest its an issue with your system now Max? Max converts your assets to .dbo regardless of what format they are originally in so i think this is unlikely

**Comment by superdave69** [comment]
It’s not my system. My system has a 3050ti 16 gb ram 3.4 8 core processor and if it can run Hogwarts legacy on max graphics it’s definitely not my system. Second the models had to be scaled up as they much smaller than needed again should not effect performance and they are under 3,000 polygon count

**Comment by superdave69** [comment]
And I know what Max converts models to. But how well when it comes to different model import types.

**Comment by superdave69** [comment]
And instead of treating me like I don’t know what I’m talking about maybe take note of the information as this software is supposed to be designed for people that don’t know how to program and probably don’t know much about 3D modeling either so making it as easy to use for them as possible should be your goal

**Comment by superdave69** [comment]
In fact to get my point across I can get these models running better in Both copperxube 6 and Realm Crafter 1.26

**Comment by davetgc** [comment]
No one was suggesting you didn't know what you were talking about, but we do need some more information. Could you please post the system metrics so we can get an idea of the number of polygons and draw call?

Thanks.

**Comment by superdave69** [comment]
Due to copywrite infringement laws that prevent it know you would need to purchase them.
Wich you can do here: https://3drt.com/store/?subcats=Y&pcode_from_q=Y&pshort=Y&pfull=Y&pname=Y&pkeywords=Y&search_performed=Y&q=Wild+Animals&dispatch=products.search

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/9397481/ee0d061a-4053-44a1-a54b-a6dd5565aa5b)

Note the specs there.

**Comment by superdave69** [comment]
The only thing that may need modified is the Texture from TGA to PNG to reduce it's size but that should not effect anything.

**Comment by synchromesh62** [comment]
I did discuss this with you on discord and actually purchased the bear to try it.
**( Though i wish you sent me the link at the time as i paid more then that :( .. )**
 These are a couple including the bear both imported in from .x format.
 Perhaps its the pack ?
 But the Bear works fine for me. 
 
https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/96e6fdde-b734-48f5-8d45-b77360ce3a83

**Comment by superdave69** [comment]
Yeah I saw that video now add more stuff in with it. That’s when the lag happens in my scene I have a lot of stuff in it but it doesn’t happen when adding in the apocalypse models. I’m going to uninstall and reinstall game guru and see if it fixes it. Also I work a full time job. So I catch who’s on sorry not meaning to inconvenience ya.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/9397481/4fd83d5a-6f6a-4851-818b-6dfc13481339)

**Comment by superdave69** [comment]
Doing a complete re-installation and did a video card update. Will retest and report.

![Uploading image.jpg…]()

**Comment by superdave69** [comment]
Still lag just a little less. Still same issue of items not showing in inventory and not being able to pick them up. perhaps since update I need to reset those up. I'll try that. But I say it's probably an update broke it bug.

**Comment by superdave69** [comment]
https://youtu.be/rSB5M6AlovI

**Comment by earthling45** [comment]
> It’s not my system. My system has a 3050ti 16 gb ram 3.4 8 core processor and if it can run Hogwarts legacy on max graphics it’s definitely not my system. Second the models had to be scaled up as they much smaller than needed again should not effect performance and they are under 3,000 polygon count

3050 TI, 
This is a laptop i assume.
Not that this would be a problem, it is a good graphicscard with its own GDDR6 video memory albeit on the low side with only 4gb for GGM i think.
To see how much video memory you are using, MSI afterburner is a handy tool to monitor the system while playing your game, also temps are important because if it get's too hot you also lose performance because of throttling.

Happy new year.

**Comment by superdave69** [comment]
It is a $2,850.00 laptop An Acer Rtx to be precise with on board 16 gun of ram not 100% on the video card ram but I’d have to look. It is a Gaming laptop, so no it’s not low end. I’m still paying off in fact.

**Comment by earthling45** [comment]
> It is a $2,850.00 laptop An Acer Rtx to be precise with on board 16 gun of ram not 100% on the video card ram but I’d have to look. It is a Gaming laptop, so no it’s not low end. I’m still paying off in fact.

It isn't critique and i am sure it is a good system, just giving you some feedback on what the problem might be. :)
Another thing to think of with a laptop is power, of course you will want a good battery life but for gaming performance is important.
https://community.acer.com/en/kb/articles/15057-how-to-change-power-mode-in-windows-11#:~:text=Click%20on%20Start%20%E2%8A%9E%20and,%2C%20Balanced%2C%20or%20Best%20performance.

**Comment by superdave69** [comment]
I keep it powered by Ac anyway and yes I know that can deteriorate the batery in a laptop, however the batteres in this one you have to open the case to get to and they connect and reconnect rite by the board so when and if I need to make it portable i can do that they aren't too steep in price. Also I apprciate the feedback. I don't think it's so much my system I do think it's a perfamance  issue associated with call behaviors in the scripting. I mean I got alot going on in that level, so that is to be exspected. So I'm patiently waiting on a performance update. I'm also planning out a way to reduce the scene render demand as well by adding new maps that will work like areas. Example: Area in a forest that lead to a new map but of said forest type with the ability to travel back between them. Doing this will rejuvinate resources I alternatively would have to trigger clone as well as creatures. I think you get the idea. So for now I'm populating more animated models with intent on moveing them to different areas (maps) Kinda like they did in Skyrum. That way reducing render demand further.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
