### ISSUE TITLE
weapon flickering and automatically switching - GG CLASSIC

### ISSUE THREAD

**Issue by XScornGames** [TheGameCreators/GameGuruRepo#5136]
i have an urgent request concerning game guru classic engine ...an user had this follorwing problem :and i have no idea how i can fix it....so i thought maybe you guys have an idea...
![image (1)](https://github.com/TheGameCreators/GameGuruRepo/assets/147309432/9f68adc2-7621-482a-b60e-b4754e0ef4db)
![image (2)](https://github.com/TheGameCreators/GameGuruRepo/assets/147309432/e4b433ea-b18c-47a8-953a-3ae7015d8364)
![image (3)](https://github.com/TheGameCreators/GameGuruRepo/assets/147309432/f8f44de1-9f1e-41f1-a3eb-20e5101e1574)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/147309432/970c4182-2a18-44a6-8e0c-93e3ed76657a)

**Comment by davetgc** [comment]
@XScornGames : Just to confirm, this is a published game?
