### ISSUE TITLE
Multiple bug reports - I deleted my entire project

### ISSUE THREAD

**Issue by ArmedAndHammered3** [TheGameCreators/GameGuruRepo#5137]
So last night my Max game project was making major progress and running so fast i was amazed.  This morning i woke up and have zones not working, duplicating themselves and disappearing. I tried verification of files and even at 100% all verified having the same results over and over. I rewrote my copy of windows and put fresh Steam and Max in and still the same thing. Even on stock maps with zero added assets i am having files missing after every launch. I noticed there was an update and also heard a rumor of AMD but nobody spoke of it openly. Was so frustrated i deleted my entire game . If it wont work for me I'm sure not gonna try to sell it to anyone.  
Please advise me what is going on and what to do?

I am running the following in the attached photos

![MyComputerDetails — Mozilla Firefox 12_30_2023 1_20_51 AM](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/72a720b2-e321-4bbd-9eb3-ee22f6170f2b)

![MyComputerDetails — Mozilla Firefox 12_30_2023 1_21_09 AM](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/5d305ff4-8ccc-4835-a061-24d312918cc9)

**Comment by plemsoft** [comment]
More info about verification of files problem:

FYI @TGC:
MAX still write to : \Files\editors\gridedit\cfg.cfg should be moved to doc write.

These files do not match what is on workshop, so each time you validate and start MAX they get downloaded again.
\Guides\MaxLua\MaxLua.INI
\Guides\Weapons\Max_Weapons_Guide.pdf
\Guides\Quest\Max_Quest_Guide.pdf
\Guides\NPC\NPC_Control_Guide.pdf
\Guides\MaxLua\MaxLua.exe
\Guides\HUD\Max_HUD_Guide.pdf
\Guides\Behaviors\Max_Using_Behaviors_Guide.pdf

So you always end up with around 8 files always failing validation after you run Max.

@ArmedAndHammered3 _"I noticed there was an update and also heard a rumor of AMD but nobody spoke of it openly."_ , You have a AMD CPU and there is no problems with that , there is a problem with some AMD GPUs where a workaround has already been added to Max so that should also not be a problem.

Any of these do not have any impact on the actual levels your making, so the only problem here is that your zones are not working and disappearing/duplicating.

**Comment by ArmedAndHammered3** [comment]
Oh i forgot to mention it spawning multiple entity when i added 1 and in all sorts of crazy positions. Sometimes it would make 3 of them but I could delete them. Other times it would create 4-10 of them. It was enough to drive anyone crazy and i reacted poorly to seeing all my hard work crumble before my eyes. I try not to complain when strange things happen and i know there will be program errors. You guys are amazing and i just needed to vent on the issues i was having. Deleting my work was my own error, but the program pushed me off that cliff so to speak.  Thank You for all your hard work.

**Comment by Kitakazi** [comment]
That sounds like you pressed the I key and then tried to place your entity which will indeed spawn multiple copies. If you dont press it again you wont be able to delete them.

**Comment by ArmedAndHammered3** [comment]
I was not pressing the "I" key as my hand was on the mouse not the keyboard. The delete key is also 4-5 inches away from that key. I'm sorry but that particular key has nothing to do with placing an entity. The mouse is used to choose "ADD" and then you click on the entity and release the mouse button to add it to the screen.  At no point did i press the I key, but thank you for your input.

**Comment by OldFlak** [comment]
Sounds like you have selected the random spray option - it is far too easy to select by accident. Do it myself occasionally.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/fe64d09b-8081-4d0b-b23e-d709ea981107)

**Comment by ArmedAndHammered3** [comment]
I have objects that i saved over and over unticking themselves when i saved directly b4 and run the levels standalone, objects randomly vanishing until i click on the spot they were in and they suddenly reappear. I have red/green spots appearing around objects but only at certain camera angles, i 

https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/8b678a08-0660-4520-9ade-4125f479467b


https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/3a754d52-b46c-4d8c-9967-114c42881e2e


https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/03700c6a-2592-4a30-8899-d85cc3e3f8ef


https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/5fc372eb-9eff-4f82-8125-35b4e34989a7

get major lag and logic seems to completely stop even if i delete and recreate the entire level. Decals showing up in the Animation choices for Play Animation, color completely vanishing from clothing

https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/1f0a2b4e-a7a2-4269-afe9-1cec2fa6c7ff

I dont get any issues with clothing, assets or wierd spots on screen playing Scum Or Conan Exiles as you can see so Steam is ok as far as i can tell and its Fresh Instal.  My windows is brand new and boots from power button in about 20-25 to windows desktop logged in. My Graphics card (GTX 1660) has been fully tested for failure anywhere and it passes even on Extreme settings
![Unigine Heaven Benchmark 4 0 Basic (Direct3D11) 1_13_2024 3_48_12 AM](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/5459b5fd-ba39-41aa-95d7-6ba58d3ecffa)

Here is a ss from 3D Mark included of my rig. 

![3DMark Basic Edition 1_13_2024 4_49_44 AM](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/06ec3bfe-d614-4b77-afc8-07b11348423d)
![3DMark Basic Edition 1_13_2024 4_49_58 AM](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/d20bfc33-bb5d-4350-94db-530db8f3ef57)

My Hd is the Evo 870 SSD the other was plugged in during test on accident.
Am really bummed here cos i cant pinpoint the issue causing me all this grief.
I love the program and about 2 months ago it decided to start acting strange on me. Seems like i create all night and day and then to bed and when i wake everything that worked perfectly when i logged off is all bonkers and the simplest blank map with only 1 stock asset with no logic acts like it came from The World Beyond.  

I realize that people are giving advice they deem helpful but i know i am not doing what they are stating as i have checked repeatably and no matter what i do or try i get Outter Limits style game cration.  I have decided i am going to just make a simple game and post it to itch.io just to see if anyone can figure it all out.    I love your product but i am very discouraged by the results as of late.  It used to run so perfectly for me and now its just stressing me out.

Thank You All for your input and dont get me wrong if i sound disgruntled employee style with your posts.  Nothing against you in the slightest but i know when i only touch the mouse and when i only press 1 key.  I check all the boxes are good and things run as planned b4 i save anything as well as make a backup of everything beforehand. I am in no way perfect

Anyway thank you all for even taking the time to speak to me on these issues. Your support is greatly appreciated and i encourage more of it Please and Thank You.

**Comment by ArmedAndHammered3** [comment]
Oh and i swapped HDMI cable and checked my graphics card for overheating issues but zero found.

**Comment by LeeBamberTGC** [comment]
@ArmedAndHammered3 The best way GitHub issues board works is by tackling a single issue per thread, and then once that issue is fixed and confirmed, we move onto the next one. Had a hard time pulling out just how many issues are reported here :)  Can you pick the most serious of the above, and repeat it in reply and we can start with that one, thanks!
