### ISSUE TITLE
Update Crash ... 20 mins ago 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5138]
Tried rebooting etc but just get this 
Can anyone confirm ?

![crash](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/77228b86-5f5e-4ae1-aa04-f3c517eca5f7)

**Comment by mk831940** [comment]
Broken for me too guys. I don't get that error though, Just doesn't launch.

**Comment by fearlesswee** [comment]
Also crashing for me with no error message. Just refuses to boot up.

**Comment by synchromesh62** [comment]
Ye i only got that once ,,, Hopefully a clue for Lee
right now nothing, same as you

**Comment by Ratall** [comment]
Looks like Lee forgot to remove the optick performance analysis stuff before sending the code out. Easy mistake to make.

**Comment by synchromesh62** [comment]
On a good note the optimisation is working .. Crashes so fast now you dont see it Launch :)

**Comment by extremestrategy** [comment]
Doesn't launch, but no error.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Managed to compress the entire developer lifecycle into a single second, idea -> code it -> crash :) I seem to have left the OPTICK in the graphics engine, sorted for the new EXP build :)

**Comment by extremestrategy** [comment]
Working for me.

**Comment by ArmedAndHammered3** [comment]
Mine boots right up and now its not acting funny like in my post.

**Comment by synchromesh62** [comment]
> @synchromesh62 Managed to compress the entire developer lifecycle into a single second, idea -> code it -> crash :) I seem to have left the OPTICK in the graphics engine, sorted for the new EXP build :)

Confirmed All fixed now
Thanks Lee :)

**Comment by synchromesh62** [comment]
> Mine boots right up and now its not acting funny like in my post.

Na Lee fixed and updated already
