### ISSUE TITLE
Wicker Basket Thumbnails

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#514]
In the Barrels folder, Wicker Basket (open) and Wicker Basket (closed) are reversed in terms of their thumbnails. 

For instance the open one appears closed in the thumbnail and the closed one appears open.

**Comment by Teabone3** [comment]
To fix simply rename the thumbnails to be reversed.

**Comment by Teabone3** [comment]
Hi I noticed this issue is still not fixed (despite how easy it is to fix)

![barrels](https://user-images.githubusercontent.com/35990109/77784273-a52aad00-7030-11ea-9344-5e3663a73f4f.JPG)

**Comment by Teabone3** [comment]
This issue seems to be still present in 2020. If I provide the corrections, would that be helpful?

**Comment by LeeBamberTGC** [comment]
@Teabone3 Fixed for Tuesday's FIxes Update :)
