### ISSUE TITLE
Character using Max Rig not animating in test play unless selected in editor

### ISSUE THREAD

**Issue by Pixelwolfnet** [TheGameCreators/GameGuruRepo#5140]
I have added a number of custom characters to my game using the max rig to allow me to take full advantage of all of the scripts and animations however unless my character is selected before I launch the test game they don't play any of their animations. 
[NPC.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13799496/NPC.zip)

https://github.com/TheGameCreators/GameGuruRepo/assets/132238942/932ff57d-bb39-4cba-bfb4-37375c6e4784

I have attached one of my imported characters as well as a video showing what I mean.

The biggest problem is I have half a dozen characters that all just slide around the map unless selected but I can only select one at a time.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
