### ISSUE TITLE
Bugged animation zombie

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5141]
I was testing around, and this happened.

https://youtu.be/_YFJZGNVWG8

**Comment by davetgc** [comment]
What behavior are you using?

Can you supply an FPM where this happens?

**Comment by extremestrategy** [comment]
Sometimes Max does that for some reason, saving, exiting, and coming back in usually takes care of it.

**Comment by thecyrus** [comment]
@davetgc I was using the basic Zombie Attack, but it doesn’t happen every time, it happened in the example once and just recorded it.
