### ISSUE TITLE
MAX - REQUEST - Use Importer for Collision Mesh

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5147]
Hi Team - thanks for considering this request.

At the moment we have to add Collision Mesh's manually outside of MAX - which is easy enough of course.
I think some would prefer not to do so.

It would be useful if we can import the Collision mesh for models via MAX importer:
Perhaps we can name the Collision Mesh **modelx_cm** so **modelx** will find it when using the object in editor.
Just a thought . . . 

Advantages:
- would make the user experience a little more polished
- importing and using models in AMX would be a tad more coherent
- it would make MAX 'easier' for some

Thanks for considering :) :)

**Comment by MonkeyFrogStudio** [comment]
Yes, just like the MAX importer looks for all associated textures (albedo, normal, surface) it could also check for a custom collision mesh provided it had the correct naming (just like textures do). So, as is suggested, perhaps append the name with '_cm' (for 'collision mesh'). Therefore, if the end-user is importing bridge.fbx, they would have a bridge_cm.obj in the same folder. As long as that was the case, then the importer would find bridge_cm, automatically use it for a custom collision mesh, and automatically set the model's collision type to 'collision mesh' so the end-user would not have to do anything more than simply import their model. If no '_cm' model is found, then the importer would work as standard.
