### ISSUE TITLE
Cannot export from particle editor

### ISSUE THREAD

**Issue by DjScribblez** [TheGameCreators/GameGuruRepo#5149]
![image (1)](https://github.com/TheGameCreators/GameGuruRepo/assets/56238769/e382791f-cb78-49ae-838f-a63ce43faef2)
There is no export button within the particle editor for me. Tried in both the experimental version and retail version.
[Here](https://streamable.com/5fwufn) is a video showing the process.

GGM is not installed on my C drive and my writeable folder isn't either.

**Comment by davetgc** [comment]
Has anyone else seen this? It seems to be working for me.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
