### ISSUE TITLE
Droid Statue.X file is missing from the Scifi Pack\Drones folder

### ISSUE THREAD

**Issue by perelect** [TheGameCreators/GameGuruRepo#515]
Game Guru\Files\entitybank\Scifi Pack\Drones\Droid Statue.X file is missing.
There is a .dbo which the fpe uses but no .x file
I have recently done a new install of GG.

**Comment by GameGuruEvan** [comment]
This particular model does not have an X file.  Only the DBO file formed part of the DLC.
