### ISSUE TITLE
Weird shapes created in editor and not editable

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5150]
I don't know if this happened to anyone else, but randomly these shapes keep appearing and ruining maps IN STANDALONE TEST from the second map loaded, and they can not be modified.
At times, they disappear by themselves.

EDIT: 
I notice that the issue starts from the second level in the storyline, never from the first.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/96dfcda5-17f8-4ef4-8672-f1e175b300b8)

**Comment by thecyrus** [comment]
It's getting werider.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/6ada81bc-1254-4b4f-9634-f212d034ccc9)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/9c3036ad-9033-4288-b6ae-33b598dce6d0)

**Comment by thecyrus** [comment]
The levels look normal in the editor and in the test preview, but go nuts on the standalone level test.

**Comment by thecyrus** [comment]
I notice that it starts from the second level in the storyline, never from the first.

**Comment by thecyrus** [comment]
I notice that problem starts from the second level in the storyline, not from the first.
And it gets worse beyond the second.
Also, it doesn't load the ambience sound.

**Comment by ZD-ZMA** [comment]
this happens to me as well. your not alone. same with ambience

**Comment by thecyrus** [comment]
I'm thinking that it has to do with Buildings, the map at some point seems to generate a negative space of them...

**Comment by LeeBamberTGC** [comment]
@thecyrus Can you zip up your project folder for this one, along with all the FPM level files the project uses, I am hoping you are only using stock media so I can reproduce quickly at my end, thanks!

**Comment by thecyrus** [comment]
Yes @LeeBamberTGC I’ll upload one asap in the morning with stock media, only just keep in mind that it almost never happens while testing in the editor, but in standalone mode and while progressing levels.

**Comment by thecyrus** [comment]
Ok, I couldn't sleep and went ahead. :D

Test standalone and get to the Win Zone near the tree int the first level, then in the second level you should see the shape in the second level.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/e63fa9ad-8590-4dbe-9f2c-9d5134c789da)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/20018692-4ca5-494b-afd1-43a1ebe493b8)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/249cdbb7-4441-4d0c-a384-09215f653d12)

**Comment by thecyrus** [comment]
@LeeBamberTGC I just uploaded the project folder and added the two maps used.

Sorry for splitting into 3 files, the whole archive was little more than the 25MB limit.


[Test Terrain Shapes.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13999931/Test.Terrain.Shapes.zip)

[Mountain 1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13999933/Mountain.1.zip)

[Mountain 2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13999935/Mountain.2.zip)

**Comment by LeeBamberTGC** [comment]
@thecyrus Nice find!  Seems the old area flattening is being carried over:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b057b074-ce56-46e4-b101-24795f6c5bd7)
Should be an easy fix now, will post here when done :)

**Comment by LeeBamberTGC** [comment]
@thecyrus Seems the transition to a new standalone level pretty much never reset the flattened areas!  Ouch. Sorted for the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f398e6a9-cddc-41bc-b926-f253ce0dac91)

**Comment by thecyrus** [comment]
I've just tried the same demo I attached, and seems fixed now.
