### ISSUE TITLE
HUD unknown icon appear in game & FREEZE the GAME .

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5151]
Hi i was working hard creating my first level in ggmax EXPERIMENTAL, NOW i'm COMPLETELY STUCK
The game is STUCK because of a CURSOR icon appearing ALL the time who freeze my level, can't do ANYTHING

I was creating my level elements you can see here:
![ggmax_cave_rocks35](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/8b3fc63a-264d-4ee0-908f-10c9943a7ae4)
![ggmax_cave_rocks36](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/835b5aaa-08d2-4d88-9e6d-8417b3234ba9)
![ggmax_cave_rocks38](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/4ab9b108-d7c2-433a-b307-14bd008b5d79)

Then i decide to interact with a rock adding a behavior called "Examine" who add a text when the player is close to the object.
I run into some bugs.... and then i almost solved it, and decided to create a simple HUD icon
![ggmax_cave_script_wip06](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/733f6d90-9252-4713-9390-02b80f85821e)

i had this function before who was showing my custom cursor in game. 
![ggmax_cave_script_wip10](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/6dde65f1-d1d3-4433-bb37-7e2b16abf762)

but NOW i have NO MORE that option.
![ggmax_cave_script_wip13](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/5e410589-e2b9-43f1-8228-92f1198b1a40)

and the game keep showing that ICON i never added to my game
![ggmax_cave_script_wip14](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/27ef6035-440f-42e1-a787-e884b5a53591)

THIS is URGENT, i'm STUCK and i would like to have a real solution for this.

**Comment by imothep85** [comment]
I then decided to COMPLETELY delete the HUD in the storyboard to try to SOLVE it
![delete-bug01](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/a40f19c4-0700-488e-a725-bffc7fd113a2)

but ggmax recreate a default HUD everytime i reload the engine
![delete-bug03](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/c389d0eb-a03c-4f72-8037-f804d4765163)

SO i deleted it again and created a new hud 
![ggmax_cave_script_wip13](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/e6a8a57f-70f4-48bb-83be-18dbe515fbc0)


but the bug still appear, this after non the strange arrow icon started appearing from nowhere and it was the beginning of my nightmare.
![ggmax_cave_script_wip11](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/193c9bc0-a7a7-4066-86d9-be3cbeba333f)

i'm COMPLETELY stuck and need a serious HELP on that problem
i was talking to everyone here:
https://discord.com/channels/950796460683829329/950796461136826389

**Comment by imothep85** [comment]
I'm completely STUCK and i need to solve this this bug appeared from nowhere

**Comment by synchromesh62** [comment]
@imothep85 
It may pay if you do a video of the exact process your using from a blank Hud, Pop it on YouTube and post the link.
The pictures don't help that much.  
But it must be all stock behaviours ( un-edited ) to enable it to be reproduced

**Comment by imothep85** [comment]
I don't use any behavior now, i removed the ONLY ONE behavior i used for the entrance stone with the sculpted octopus.
But STILL the BUG is there i can't move the player anymore, and that cursor appear who freeze the level interactions using the keyboard
![ggmax_cave_rocks37](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/b4fba3f8-1fc8-4ccf-928f-cd8d26684c3c)
![door-no-behavior](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/34233a0d-e823-4673-84f1-cc06a9dd4c71)

**Comment by imothep85** [comment]
The problem COME from the In-Game HUD generated BY game guru.
 
When i create a new HUD "HUD screen 2" by default, i add my customs hud and it show inside the game BUT
BECAUSE ggmax KEEP creating the original "In-Game HUD" it block the property of my new HUD

**Comment by davetgc** [comment]
@imothep85 - Are you able to make a video as @synchromesh62 suggested?

**Comment by imothep85** [comment]
i solved it by removing the hud
