### ISSUE TITLE
MAX - EXP - Can't select models when inside buildings

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5152]
Hi Team,
We can untick the option **Stop object from being moved when camera inside** so we can select objects on interior scenes.
But this has been unreliable for some time now. Usually it does not work, and I have to use **Detailed object List** to select models.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/a77d948b-73ee-43ab-b80c-a560a02c8996)

Thanks for checking :)

**Comment by LeeBamberTGC** [comment]
@OldFlak This connects with another report about not being able to select a particle marker when you scale it up, and revealed some errors with the system. In the next EXP build a better system should ensure this feature only cancels a possible selection if the feature is ticked.  Let me know with a small stock level if this persists, thanks!
