### ISSUE TITLE
Combat Music doesn't work now

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5154]
It just starts for a couple seconds at the start of the level, then disappears and doesn't play while fighting.

**Comment by synchromesh62** [comment]
Combat Music has not worked for me in ages so i can confirm that.
Though at the time i thought it was me doing something wrong.

**Comment by davetgc** [comment]
Checked, same here.

**Comment by LeeBamberTGC** [comment]
@davetgc Try the AZTEC GAME KIT TEASER and let me know in the EXP build if the music changes when you open the door and the Warrior Attacks, thanks!

**Comment by thecyrus** [comment]
@LeeBamberTGC from what I've seen so far, it work in the Aztec GKT but acts as said above in other projects.

**Comment by OobieDoob-Benoobie** [comment]
[Aztek.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14002681/Aztek.zip)
Works in demo.

**Comment by thecyrus** [comment]
Yes, indeed but not in other scenarios.
