### ISSUE TITLE
Trigger delay function Not WAI (Working As Intended)

### ISSUE THREAD

**Issue by OobieDoob-Benoobie** [TheGameCreators/GameGuruRepo#5155]
I tried adding the delay to the door, but the sound gets played when the trigger is stepped on for some reason.

https://youtu.be/fBCkux6F_Pg

**Comment by davetgc** [comment]
Not sure what we're supposed to be seeing here. Can you try to explain more please?

**Comment by OobieDoob-Benoobie** [comment]
in the playerinzone behavior panel on the right, third slider down is a
delay timer to add a delay to the trigger.
Instead of being a delay, it just pauses the triggered event (after the
timer has run its course) and the event
never happens.
Until the trigger is walked over a second time. By now the player might be
long gone.

**Comment by OobieDoob-Benoobie** [comment]
The player steps into the trigger zone activating the timer if its set to have one. 
It should trigger the event after the timer.
It does not trigger the event after the timer unless the player is ether standing on the 
trigger zone or steps into the zone a second time. 
But it does play the sound for the event.
It used to work fine.

**Comment by davetgc** [comment]
Thank you, that's helpful.

**Comment by OobieDoob-Benoobie** [comment]
Is this still waiting for more info?

**Comment by Necrym59** [comment]
This is a Player In Zone - it cannot control things if your 'not' in zone that is the whole point. There is no error. 
You would have to find another way to achieve what you specifically want - perhaps trigger a 'timed event' behavior when entering the player-in-zone and allow that one to trigger whatever you want after a period.  (this is independent and what it is designed for)

**Comment by OobieDoob-Benoobie** [comment]
> This is a Player In Zone - it cannot control things if your 'not' in zone that is the whole point. There is no error. You would have to find another way to achieve what you specifically want - perhaps trigger a 'timed event' behavior when entering the player-in-zone and allow that one to trigger whatever you want after a period. (this is independent and what it is designed for)

Then you should remove the delay timer as it used to function and no longer does. 
unless of course you expect players to stand still for 3 min. on the "Playerinzone" with a timer, or the creator to design around this obvious bug.

apologies for the salt, but that seems like a cop out answer. 
This delay feature used to work and now it doesnt. 
Why would you have a spot on the floor to activate something elsewhere with a timer to time the event, where the  player ether has to stay at an invisible marker, or return to that spot in every occasion where you want to time playerinzone? 
The playerinzone is just to trigger yeah?

Or is it to stand and wait for the timer to run its course? 
Seems completely useless to have that timer then.

**Comment by Necrym59** [comment]
I will make a seperate function to trigger and make it not have the requirement of being in the zone (even though thats the point) when i have some time. Try and be a bit more civil and less abrasive in future if possible.
