### ISSUE TITLE
Investigate possible performance improvement related to IPCONFIG (Network Activity)

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5156]
I discovered something IMPORTANT about the MASSIVE LAGS in GameGuru Max.

When the software start to SERIOUSLY LAG i found the solution
in windows start the CMD and type: 
ipconfig/flushdns 
and then 
ipconfig/renew 

AND BOOM
GameGuru will restart without lagging

Maybe the developers can look to correct that huge problem ?
I tested it and solved that massive lag at start of GameGuru Max

**Comment by thecyrus** [comment]
Well, it's weird. What does GG Max have to do with DNS?

**Comment by imothep85** [comment]
i don't know... but it works...maybe something to do with steam ???

**Comment by davetgc** [comment]
Not sure this is linked to MAX, but maybe Lee has some insight.
