### ISSUE TITLE
Maps being deleted after verifying files.

### ISSUE THREAD

**Issue by superdave69** [TheGameCreators/GameGuruRepo#5159]
Lost 2 map levels while verifying files. Looks like I'm starting fresh with Harsh World Survival.....

**Comment by MonkeyFrogStudio** [comment]
Are you saving your maps in your user area (Documents > GameGuruApps > GameGuruMAX > Files > ...)? If you're saving your files in the Steam install area, this area is only for MAX and MAX content. Anything saved in there can get overwritten, etc.

**Comment by superdave69** [comment]
I export and save them in 3 back up folders I couldn’t get the maps to reimport correctly from those folders. I planned however to do clean up work and see if it corrects lack on my end. I am simply reporting the bug in this situation.

**Comment by davetgc** [comment]
@superdave69 - I've not seen this, can you report back after your clean up work, as nothing in the user folder should get deleted. If stored in the Steam MAX folder, the files can get overwritten.
