### ISSUE TITLE
Double Sided on a object not working

### ISSUE THREAD

**Issue by UA998** [TheGameCreators/GameGuruRepo#5162]
Recently I have encountered a bug in max that If I select both sides as polygon (Double Sided) on my 3D model so it is still not visible from outside and inside it has recently occurred because I have been turning my custom 3d models to double sided in max and they were visible from both sides but this time it isn't working I had restarted Game Guru Max but still the same issue .

![GameGuru MAX - Main Level  fpm_ 1_8_2024 10_15_27 PM](https://github.com/TheGameCreators/GameGuruRepo/assets/90584085/16bc7797-1965-4f62-8ddc-3afd201f7107)
![GameGuru MAX - Main Level  fpm_ 1_8_2024 10_15_39 PM](https://github.com/TheGameCreators/GameGuruRepo/assets/90584085/fbd8c5e0-257a-46ad-b55b-862d8e1205fd)

**Comment by davetgc** [comment]
Can you please email Lee@thegamecreators.com a sample model so that it can be tested? Please reference this post in your email.

**Comment by MonkeyFrogStudio** [comment]
Out of curiosity, does the model have more than one material? If so, you would need to tick Double-Sided for each material.

Also, Double-sided does not require Polygon under Collision Shape. That's a type of Collision method and has nothing to do with materials. Double-Sided only affects the material, making it visible on both sides of a polygonal face where the material is applied.

**Comment by OldFlak** [comment]
I have found in recent builds that double-sided gets ignored by MAX when changing it in the properties panel, whereas if it is set when importing it works fine.

**Comment by UA998** [comment]
It is working on a different 3D Model it seems that there was a problem in that 3D Model however I have figured out that it is not working on those objects which are joined together using blender for example I have joined 2 different objects together using blender and then exported it and imported it in ggm so in these kind of objects the double sided option is not working .

**Comment by MonkeyFrogStudio** [comment]
You have to ensure that ALL materials get the box ticked for Double Sided (well, all materials that you want to be double sided). To ensure this is the case, use the dropdown just below Enable Custom Materials, select each material in turn, and tick the Double Sided tick box for each one.

I have several models that I've imported as one model (all together as one) and double sided works if ticked.

**Comment by UA998** [comment]
Ok so we can safely say that it’s not a bug of ggm so Iam closing this issue .
