### ISSUE TITLE
I can Pickup items behind a wall

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5163]
https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/606bbdae-db2d-4394-a52f-1289edcbb3ce

**Comment by thecyrus** [comment]
Walls need to be more "solid", because apart from taking object behind them, you can been attacked by melee through them and often NPC's get stuck in.

**Comment by thecyrus** [comment]
Walls need to be more "solid", because apart from taking object behind them, you can be attacked by melee through them and often NPC's get stuck in.

**Comment by Necrym59** [comment]
OK binoculars has been fixed, i will go through any others that need the same treatment, if you note down any others doing the same let me know, thanks.

**Comment by thecyrus** [comment]
Thank you, of course I will.

**Comment by LeeBamberTGC** [comment]
@thecyrus Hopefully Necryms fix solved it for you, and we are updating the stock scripts with any updates from the workshop so hopefully we have caught all the 'object detector' scripts and made sure they ray cast correctly before giving you a detection

**Comment by Necrym59** [comment]
If this is fixed can you close the posting thanks.
