### ISSUE TITLE
Max crashes when trying to add an object to a level 

### ISSUE THREAD

**Issue by jasailor** [TheGameCreators/GameGuruRepo#5164]
What is the most likely cause of MAX (all versions) crashing when clicking the Add button?   All games including the demo games and previously created games now crash.   It does, however, do the placement of existing objects to the scene.  I have always used the experimental versions of MAX so I went back and tried to run older versions but it still crashes.   There are no error messages - just kicks me back to Steam.

**Comment by thecyrus** [comment]
I've seen it happen when importing some models.

**Comment by jasailor** [comment]
Reinstalled MAX and seemed to solve the problem.  We'll see!
