### ISSUE TITLE
Black screen on GameGuru Classic

### ISSUE THREAD

**Issue by naskivik** [TheGameCreators/GameGuruRepo#5167]
I am currently running GameGuru classic and all I can see is a black screen on launch with none of the buttons working if clicked.
Specs:
Device name	DESKTOP-9QNIAK8
Processor	AMD Ryzen 5 3600 6-Core Processor                 3.59 GHz
Installed RAM	16.0 GB
Device ID	43038827-B347-45F4-A35F-540A6721A38D
Product ID	00326-10034-50408-AA737
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
![guru](https://github.com/TheGameCreators/GameGuruRepo/assets/65699876/eeec8efb-4417-4794-802d-bd7ffe12a4a8)

**Comment by thecyrus** [comment]
I think graphics card is missing in the specs.

**Comment by Teabone3** [comment]
Has Game Guru Classic worked for you in the past with the same specs. Or are you just experiencing this now?
