### ISSUE TITLE
Weapons disappearing in level, while present in editor

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5168]
I'm having this issue, in test mode and standalone. Some weapons simply disappear, no matter how I place them.

https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/ad40da31-98c5-42e4-b11b-3ed1c42d97ed

**Comment by davetgc** [comment]
Thanks for the report. Can you please post an FPM where this is happening?

**Comment by thecyrus** [comment]
Sure, I'll upload the map I was testing weapons on.

**Comment by thecyrus** [comment]
[https://file.io/WA0C3cbm3pDU](url)

**Comment by LeeBamberTGC** [comment]
@thecyrus Can you reupload, the file has been deleted (The transfer you requested has been deleted). Google drive is a good free one and it will not erase your uploaded links :)
