### ISSUE TITLE
GGMax not being able to access store downloads

### ISSUE THREAD

**Issue by ZD-ZMA** [TheGameCreators/GameGuruRepo#5170]
![Screenshot (15)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/bdc5609d-6f9e-4728-beef-c01ea09c8b58)
![Screenshot (17)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/8d9833d4-35ff-4639-96a3-38479da5ca55)
![Screenshot (19)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/bfe2046b-23f1-4272-9de7-aa66d190f3fe)
![Screenshot (20)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/09d8fd7a-6f4c-43c9-a506-d59127c0f459)
![Screenshot (18)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/a43ee00c-3f94-4943-a746-b785a7a15d1a)

i have several pages worth of downloads. alot is for GGC, but alot for GGMax. i try to download through max and it doesnt seem to reconize that theres anything there... but clearly there is. i have to manually download everything which is a pain in the butt. if you have any questions, my discord is zd_zma. im actually in your discord server.

**Comment by ZD-ZMA** [comment]
i want to add that this wasnt originally an issue. i factory resetted my pc thinking i would seel it. but ended up not selling it because of reasons. so after redownloading GGC and GGMax... thats when i started having issues.

**Comment by GraPhiX-Guru** [comment]
You may be having issues because your Documents folder is defaulting to OneDrive rather than local, try turning OneDrive backup off for your docs folder, if it is OneDrive causing the issue you will have to use another local folder for your writables

**Comment by ZD-ZMA** [comment]
> You may be having issues because your Documents folder is defaulting to OneDrive rather than local, try turning OneDrive backup off for your docs folder, if it is OneDrive causing the issue you will have to use another local folder for your writables

i dont even have onedrive installed on my pc. i just checked. also what does that have to do with being able to contact TGC store?

**Comment by GraPhiX-Guru** [comment]
![one](https://github.com/TheGameCreators/GameGuruRepo/assets/35724756/90b65db7-eaad-4d0f-b767-fc343e376cf1)

You have your writables set to OneDrive, OneDrive only has 5Gb of storage (Free Version) for all of your items, pictures, desktop, documents, just mentioning that this will cause you issues, as far as downloading store items you will have to start MAX through Steam to allow store downloads, make sure you have logged into your store account before trying

**Comment by ZD-ZMA** [comment]
> ![one](https://private-user-images.githubusercontent.com/35724756/297013879-90b65db7-eaad-4d0f-b767-fc343e376cf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzY0NjksIm5iZiI6MTcwNTQ3NjE2OSwicGF0aCI6Ii8zNTcyNDc1Ni8yOTcwMTM4NzktOTBiNjVkYjctZWFhZC00ZDBmLWI3NjctZmMzNDNlMzc2Y2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA3MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MTY4MzQwOGY5MDNkNWM0M2M1ODAyZDI3MjMxOWFmNWYyMzU1ZGIwNmVmNTkxMGI0ODczNDJkNWUyZmViMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pvu_Xs6wAguvayNREdlgs25b0UZe2le4qBea1YZqJgw)
> 
> You have your writables set to OneDrive, OneDrive only has 5Gb of storage (Free Version) for all of your items, pictures, desktop, documents, just mentioning that this will cause you issues, as far as downloading store items you will have to start MAX through Steam to allow store downloads, make sure you have logged into your store account before trying

except as you can see, i wasnt selecting that. before i ever factory reset my pc i was able to use the same file that i selected and i never once had issues. so i know the problem isnt the onedrive thing like your claiming it is. also ive been opening up max through steam and i already allow store downloads. i log in each time before trying. your telling me basic common knowledge and repeating yourself while ignoring everything ive said and shown. at this point its obvious that its pointless to report any bugs because nobody is going to listen, nobody is going to help, and the bug isnt going to get fixed. this isnt the first time i reported a bug that i had to deal with people either ignoring what i was saying or people flat out called me a liar despite proof that i would show. (which is funny because someone else later reported the same issue and the guy who called me a liar didnt call him a liar and even helped him despite the other reporter no showing proof) seems like everyone in the TGC community has something against me as everyone is always starting shit with me and causing me problems. so fine. dont fix the bugs i report. ill close this since its obvious you dont care.
