### ISSUE TITLE
ZONES respawn when loading SAVED GAME and should not

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5171]
If you enter for example a sound zone that is meant to play only once in the game, then Save the game in that area, when you Load the game the zone plays again.
This can be an issue in many scenarios, for example when it Replays an introduction.

**Comment by Necrym59** [comment]
So your saying you dont want it to run a after a reload is that the idea

**Comment by thecyrus** [comment]
Yes. Imagine hearing your character saying “Hey, this area is very cool! It’s the first time I see it!”, and then the player saves the game, later he loads it and the zone respawns and passing from there he says it again.

**Comment by thecyrus** [comment]
@Necrym59 While you're here, I noticed that your Stealth Zone script is working fine except for zombies, with them has some flaws.

**Comment by Necrym59** [comment]
Trigger zones or anything for that matter that is destroyed prior to game save, shouldn’t be respawned in a loaded game.
This will have to be addresses in the save routine. It will have to be passed on to Lee.
I will check the stealth zone out.

**Comment by LeeBamberTGC** [comment]
@thecyrus Yes I can confirm this would be a bug as the ;save game' should remember all states and what has already been triggered, and restore those states, so you would not get the trigger again if you triggered it in a previous instance of the game you saved :)

**Comment by LeeBamberTGC** [comment]
Duplicated from earlier issue, so closing this so we can continue all tests related to this in one place: https://github.com/TheGameCreators/GameGuruRepo/issues/5133
