### ISSUE TITLE
"Continue Game" always equals to "Start Game"

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5172]
While editing screens I noticed that "Continue Game" function attached to a button always loads the first level, even if you were into another one before going to the Main Menu.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/f8c29a05-1338-4132-b514-59688c6f8544)

**Comment by davetgc** [comment]
I take it that this is happening in save standalone?

**Comment by thecyrus** [comment]
Yes, but also also while testing standalone mode.

**Comment by LeeBamberTGC** [comment]
@thecyrus Not tested this one very much, what did you expect CONTINUE GAME to do :)

**Comment by LeeBamberTGC** [comment]
NOTE: Might make sense tp rename this one to RESUME GAME :)

**Comment by thecyrus** [comment]
@LeeBamberTGC I mean, “Start Game” is supposed to start from the beginning, while “Continue Game” should do something different than starting from the first level, I guess it should resume from the last save or from the last level played.
