### ISSUE TITLE
MAX EXP and Release "Stand and speak" behavior not WAI

### ISSUE THREAD

**Issue by OobieDoob-Benoobie** [TheGameCreators/GameGuruRepo#5173]
Hello again fellas.
heres a link to video explaining whats happening. 

I might just be doing something wrong?

https://youtu.be/rX7IwRnrAxY

**Comment by LeeBamberTGC** [comment]
@AmenMoses Thanks for the find and fix, will be in the next EXP build.

**Comment by OobieDoob-Benoobie** [comment]
Confirming now that your fix did work.
Works in all my levels.

Thank You guys.

**Comment by OobieDoob-Benoobie** [comment]
@AmenMoses @LeeBamberTGC Ill close the thread.
