### ISSUE TITLE
Turning off shadows and move way away from position 0,0,0 causes graphic issues

### ISSUE THREAD

**Issue by ArmedAndHammered3** [TheGameCreators/GameGuruRepo#5174]
Hello,

So i am having a serious issue with Max graphics wise.  Red and Green pixelations on my screen that seem to grow worse every day yet they only appear using Max. I look down and they show up out of knowhere bottom of screen and today when i look in certain directions yet not up at all or forward unless i turn around.
I was told there is an issue that came up with AMD.
I have posted a link to a video of my issue.

 https://www.youtube.com/watch?v=8ng0i1DHNtE

![3DMark Basic Edition 1_13_2024 4_49_44 AM](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/73f81adb-e0c1-4fff-8ca6-0fbb568c117d)
![3DMark Basic Edition 1_13_2024 4_49_58 AM](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/e1331c15-a3c7-4d43-818b-415e1c73e157)

**Comment by AmenMoses** [comment]
Hmm, your GPU is NVIDIA not AMD, the processor is AMD but that would not be involved in the screen rendering issues you are seeing.

**Comment by ArmedAndHammered3** [comment]
Any idea why its happening then?

**Comment by AmenMoses** [comment]
No idea.  Just have to wait and see what Lee suggests.

**Comment by ArmedAndHammered3** [comment]
https://www.youtube.com/watch?v=t_fI6dATKVw

Clean install of both Steam and Max

**Comment by extremestrategy** [comment]
Woah, it's been a while since I've seen that.

**Comment by AmenMoses** [comment]
@extremestrategy Is there an earlier Issue covering this then?

I tested with an fpm @ArmedAndHammered3 sent me and I'm seeing it too so it's got nothing to do with drivers or graphics cards.

**Comment by extremestrategy** [comment]
@AmenMoses It's possible, but I'm unsure, I saw this about six months ago on a lot of the snow maps, however it was patched the following day, so I believe that the glitch's might be connected but not sure, I never reported it as I found it, and then it was patched the next day, I also saw it during early access as well on a lot of flat terrain levels, but after 1.0 a lot of those problems vanished.

**Comment by AmenMoses** [comment]
[Main_Map_copy.zip](https://github.com/TheGameCreators/GameGuruRepo/files/13955539/Main_Map_copy.zip)

That's the .fpm

**Comment by extremestrategy** [comment]
Odd observation @AmenMoses but is it possible it's a directional glitch?  Reason I ask is when I look in a certain direction the particles appear, but when I look away it bugs out.


Uploading glitch-1.mp4…

**Comment by plemsoft** [comment]
@LeeBamberTGC This is a terrain shader bug, it will happen if you turn off shadows and move way away from position 0,0,0 the shadow camera matrix is not updated and it will give floating point errors in the shader.
Fix:
```
In: \GameGuru Core\Guru-WickedMAX\GGTerrain\Shaders\PBR\lightingHF.hlsl
func:DirectionalLight
change : if (light.IsCastingShadow() && surface.IsReceiveShadow())
to: if (light.IsCastingShadow() && surface.IsReceiveShadow() && g_xFrame_ShadowRes2D > 0)
```
Also this will not process cascade shadows if they are disabled, @Optimizing :)

**Comment by LeeBamberTGC** [comment]
@plemsoft Fixed for the next DEVTEST build (finally)  :)  Thanks for the code!!
