### ISSUE TITLE
Possible broken scripts due to use of Video Slot and Sound1 fields

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5175]
Creating a script that allows player to play a video

When using sound slots as well - the Video Slot places the video path info in both the Video Slot and Sound1 slot.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/0a6ceb22-0e7d-49d2-bb23-a475039855b7)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/bbc7394c-fa43-4e5d-88b5-a8778c6c931c)

Also can we have multiple Video Slots (Video0, Video1, Video3)

Thanks for checking :)

**Comment by OldFlak** [comment]
Sigh - this is not an enhancement request - it is a bug recently introduced that affects existing scripts.
Lua bugs should be priority fix.

**Comment by Necrym59** [comment]
I agree thi is not an enhancment but a serious bug i have quite a few behaviors that use both, hopefully this is just a temporary thing while changes are made otherwise i will have to relook at all the behaviours to see which are affected.

**Comment by LeeBamberTGC** [comment]
@OldFlak The internal "soundset1_s" was always used to store the video string and respective video animation ID and has been this way since GGClassic. Can you tell me what has recently broken in respect to the video slot, as it might be something else not exactly related to how the video file and path is stored in the entity structure?

**Comment by OldFlak** [comment]
@LeeBamberTGC hi Lee. It has not broken any of my existing scripts. In conversation with other members I am under the impression that has broken some of theirs.

I noticed the anomaly when creating a new script recently, and appears to be in the bug department to me.
Maybe now is the time to rectify it, and add more video slots as well

:)

**Comment by LeeBamberTGC** [comment]
@OldFlak Multiple video slot fields would be a feature request, but we will leave this issue as a bug report and if you can contact those users who are experiencing script problems when using video slot and sound1 field, and have them post here we can clear up the confusion.
