### ISSUE TITLE
MAX - EXP - BUG - PromptDuration Ignores the Duration Time

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5176]
This is another script breaker.
It has been broken for some time now - noticed back in early December but was waiting to see if it got ironed out.

So when using `PromptDuration("blah blah blah", 3000)` the duration time is ignored. So no matter if the value is 2000 or 60,000, the prompt displays for about half a second or something like that.

Thanks for checking :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Good find, fixed for the next EXP build.

**Comment by OldFlak** [comment]
Thanks Lee all good now :)

Thanks for sorting it out 👍
