### ISSUE TITLE
MAX - EXP - BUG - Lua Slider Errors

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5177]
When you set a slider up in a behavior using something like:
-- DESCRIPTION: Set [DELAYTIME=3(0,30)] seconds before volume decrease begins.
The editor allows you to adjust the value up to 100, which of course will break the script somewhat.

If you change the 0 to 1 DELAYTIME=3(1,30) the slider will only go to 30

No matter what the first value is, the slider should be limited to the larger value which in this case is 30.

Thanks for checking...

Posted report on this back in October #5016 but got no response so creating another report for it here.

**Comment by LeeBamberTGC** [comment]
@OldFlak Thanks for recreating the issue, not sure why the issue was not picked up, might have been because it had no tags or assignee. This issue nice and tagged, can you attach a very small script that shows this issue in your step by step, will save me some time just in case I create a custom script that works :)

**Comment by OldFlak** [comment]
Hi @LeeBamberTGC ,
here be a script to show the issue - it does nothing, but shows how the sliders do not work correctly if the first value is zero

Just attach to an object, and adjust the sliders in the properties panel.
Hopefully the blurb in the info box makes it easy understood

Thanks for checking

[sliderbug.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14037296/sliderbug.zip)

**Comment by LeeBamberTGC** [comment]
@OldFlak Many thanks!

**Comment by LeeBamberTGC** [comment]
@OldFlak Fixed for next EXP build.

**Comment by OldFlak** [comment]
@LeeBamberTGC Sorry missed this - Yes! Tis sorted :)

👍 Many thanks
