### ISSUE TITLE
MAX - EXP - REQUEST - Random Spray Objects - Prevent Accidental Selection 

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5178]
The position it is in now makes it very easy to select by accident. This easily results in randomly spraying objects by mistake some of which end up under the terrain, and in turn requires a hunt for all the offending objects.

To me the following things make it annoying where it is

In part because of where it is
the Position, Rotating and Scaling tab always stay open
you can activate the spray by clicking any part of the text for the control
Request:

Make the folder closeable again (should be same as the others anyway
Make it a secondary selection after clicking a dropdown button

Thanks for considering :)

Was requested back in May #4638 - but still not seen yet

**Comment by imothep85** [comment]
I completely agree with that, we need that to be enhanced.
