### ISSUE TITLE
MAX - EXP - Sound4 Repurposed - Not Useful and Just Adds UI Clutter

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5179]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/c0d7cfae-454a-4e41-9550-e5fe7622b9f2)

My first response at seeing this was - why would we do this?
My second thought is, if for some obscure reason we have to hi-jack a sound slot for other use (??) why not take slot 6 and just hide it? 

What it has achieved is
- we have lost a sound slot at our disposal when writing scripts (even 7 slots is not enough btw)
- and we now have more UI clutter

Just an observation, and one I hope we can see fixed.
Make MAX Great :)

**Comment by OldFlak** [comment]
This too is **not** an enhancement request - I have scripts that use that sound slot, are now broken

**Comment by LeeBamberTGC** [comment]
@OldFlak Sound slot 4 was repurposed right back at the start of the DLUA work, I am curious how you where using this sound slot string and id value. Can you send me a script you have created that uses sound slot 4, thanks!  P.S. Prior to this work, when you saw sound slot 4 it was really sound slot 5, the UI update was meant to align things so you knew which slot you where really using internally.  I agree it is not ideal, but we have to build on legacy strangeness sometimes.

**Comment by OldFlak** [comment]
@LeeBamberTGC 
Hi Lee thanks for response.
OK was blissfully unaware of that, just revisited a level where my scripts reference (PlaySound(e,4) and they do in fact still work.

So while a little weird (to me anyhow) it really is not an issue then.

I just assumed it would break them - sorry for not checking first.

Will close this issue then.
