### ISSUE TITLE
GameGuru does not scale to my monitor's native resolution (4k)

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#518]
My monitor is the standard 4k resolution of 3840 x 2160. However when I press F11 in test mode it shows my resolution as being only 2560 x 1440. I have aspectratio = 1 in the setup.ini so it should be set to my monitors native resolution.

**Comment by Granada1** [comment]
Just tested and it is working for me

**Comment by Kitakazi** [comment]
Ok, I have no idea why my resolution would not be set to 3840 x 2160. I have just verified my files on steam and it still shows my resolution being 2560 x 1440. 
https://imgur.com/LrDDSoV

**Comment by Granada1** [comment]
I no it sounds stupid but is everything else ok,I had to get a decent lead after I upgraded my monitor

**Comment by Kitakazi** [comment]
Yea everything seems fine. GameGuru is the only program/game that does not recognize my monitors resolution of 3840x2160. But if I'm the only one who has this issue then I guess it's not big deal.

**Comment by Granada1** [comment]
Did you post on the forum, someone may have had the same problem

**Comment by Kitakazi** [comment]
Ok I posted to the forum and then 10  minutes after posting I figured it out. Even though I've had this problem for a loong time just so typical to fix it right after posting :( 
But it could still be a bug. 

You have to set the size of text to 100%. If you go Right Click Desktop>Display Settings> for 4k it recommends 150% on scaling so thats what it is on. Once I changed it to 100% it changed the resolution in the Test Game to my native res. However, although I have yet to test this, I'm pretty sure that this also effects games that have been built. SO that could be an issue because it's not feasible to have text scale set to 100% because you cant read anything. So nobody would actually have that set, not to mention if they have it set higher like to 175% or 200% Which is how I even discovered the solution. I set my monitor to 175% to read a text file better.

**Comment by Kitakazi** [comment]
Ok it seems like it only effects the text / hud in game.
