### ISSUE TITLE
Steam Free Trial Version : runtime error 501 image number 63201

### ISSUE THREAD

**Issue by SuperUserNameMan** [TheGameCreators/GameGuruRepo#5181]
Hi,

Just after the large "GameGuru MAX FREE TRIAL VERSION" loading screen, the window is blank white, and there is this tiny error message box : `Runtime error 501 image number 63201 ()` with `[OK]` button. 
Once clicked, the application closes itself.

I'm running it from Steam on Linux.
I tried using Proton Experimental, Proton 8 and 7. No difference.

**Comment by davetgc** [comment]
Hi,

Thanks for the report, but MAX is Windows only, and isn't intended to run on Linux.

**Comment by SuperUserNameMan** [comment]
Oh, that's bad news for Steam Deck gamers as well i guess :-/ 

I'm pretty sure it would not have required a lot of work to improve compatibility since most other Windows games and apps already run on Linux (and on the Steam Deck) using the Steam's compatibility layer Proton.
