### ISSUE TITLE
GGMAX - Bug/Enhancment - GetEntityInZone(e)

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#5185]
In NPC in Zone behavior uses the GetEntityInZone(e) command to detect an entity is in zone we need some way to switch off an entity that is not a character from being detected at all in the detection otherwise any object above/in the zone such as a door frame or roof is automatically seen as in the zone. This stops the usefullness of this type of zone from being used indoors for example.
Can we possibly get a switch in the command eg: GetEntityInZone(e,v) v = 0 for detection for static objects, 1 for active objects and and 2 for character. Until this is done the NPC in Zone behavior is only usefull for outdoor use.
Thankyou.

**Comment by davetgc** [comment]
I'm considering this an enhancement and a bug, as it stops the behavior from functioning in certain circumstances.

**Comment by LeeBamberTGC** [comment]
@davetgc @Necrym59 Just to weigh in, the GetEntityInZone command never had the capability to filter out which entities were detected so it is technically a request for additional functionality for this command. There is a way to do the above without expanding this command, however, it is a horrible hack that involves shifting the positions of all dynamic entities before this command is called, leaving only the ones you wish to detect, then after the call, shift all the entity positions back. I agree a nasty way to do it, but would get the job done.

I suggest a new command called:

GetEntityInZoneWithFilter(e,mode) where mode 0-default to allow all objects, even inactive ones, 1 to detect only active objects, 2 to only detect characters, 3 to only detect non-characters

Sound good?

**Comment by Necrym59** [comment]
Yes, Lee, i realise now that it probably never had that capability, i must admit i never tried it under these indoor circumstances until recently, so the newer command is an excellent idea as it gains a lot of flexibility with use for the zone for indoor and other scenarios

**Comment by davetgc** [comment]
That sounds like a good plan to me. If @Necrym59 ***@***.***> is
happy, I'm good with that.

**Comment by Necrym59** [comment]
Any chance on getting closer with this command?

**Comment by Necrym59** [comment]
Done thankyou very much
