### ISSUE TITLE
GGMAX - Lights Visibility & Scale Enhancement 

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5187]
Hi to everyone i'm making huge levels, the BIG problem i have is when i ADD lights on my levels, the LIGHTS are HARD to see and find, because the entities are too small, it is possible to make those entities bigger and change their color to something more visible ?
As you can see in this picture the lights entities are HARD to see and even close are hard to find.

![lights system to improve](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/611af3ef-43cf-4f56-b61a-dd345c423877)

**Comment by MonkeyFrogStudio** [comment]
I think lights are huge in MAX and can get in the way sometimes. Here's a screen shot of normal-sized objects with a few lights:

![light](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/aa16c917-2a9e-48d5-ac1a-e70f502fa09a)

If you have issues finding an object (including a light you've placed), you can use the Detailed Object List to find and select them by name.

**Comment by thecyrus** [comment]
It could probably have an object list to call single entities when needed.

**Comment by imothep85** [comment]
We NEED this kind of technical improvement, when you start working seriously with this game engine, the engine has to be able to find entities quickly without having to search around, and lamps are REALLY not visible, so with very large scenery, it becomes IMPOSSIBLE to find them quickly and make the necessary changes.

**Comment by imothep85** [comment]
THIS is what we really need for improving the actual system for the lights, the actual icons representing the LIGHTS have to be WHITE and bigger it's easier to FIND the lights and do the necessary changes in the level design.

![cave01_wip01b](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/5669da47-8bb1-4ebf-b93a-bb70296cc4b5)

**Comment by Necrym59** [comment]
This is why you have the Detailed Objects list - almost anything will be smaller on a bigger level, there is nothing wrong with the 3d light icons no need to change them to 2d icons achieves nothing. Perhaps an icon size slider may be the answer.

**Comment by MonkeyFrogStudio** [comment]
Agreed. If the light objects are bigger, then working on interior levels becomes a lot more difficult as they would block entire passageways, etc., making it difficult to see past them without hiding them. They are fine the way they are (size-wise).

**Comment by davetgc** [comment]
As has been stated, if you need to find a specific object in a level, you can use the detailed object list, which works very well.
