### ISSUE TITLE
BUG = PARTICLES IMPOSSIBLE TO  SELECT GGMAX

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5188]
Hi i added particles to my scene, and NOW it's impossible to select my particles i changed the scale of the particle to a big scale,
and then it become impossible to change the emitters, impossible to change the values, the particles can't be selected anymore.

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/8f7fe951-7ecc-4725-9a33-da500bd25c32

**Comment by davetgc** [comment]
Can you please post an FPM with this issue shown?

**Comment by imothep85** [comment]
i'm not going to make my project public, where i can send my fpm file.

**Comment by imothep85** [comment]
i sent you the fpm file

**Comment by wizardofid29** [comment]
FYI This isn't a bug per say but something impacting objects as a whole, particle being the exception perhaps.

What is happening here, with the increased size, the entire scaled size of the particle needs to be visible in editor camera in order for the particle to be select able. The larger the object the more visibility of the object is needed before you are able to select it, the smaller the object the closer you need to be.  

However in the case of the particles, it increases the size of the particle effects but the gimbal size remains the same. It is an easy enough fix, by making only the gimbal select able irrespective of scale.

**Comment by imothep85** [comment]
i hope it will be fixed :D

**Comment by LeeBamberTGC** [comment]
@imothep85 Fixed in the next EXP build and was related to a wider issue about things scaled up and the camera being 'sort of' inside them thus preventing them being selected.

**Comment by imothep85** [comment]
yeep i can change my particles again thanks.
