### ISSUE TITLE
CLASSIC: Video Texture does not work on Standalone

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5189]
In GG Classic PlayVideoOnEntity works in the test mode but gives this error in standalone saved.

I used the demo level to be sure.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12373041/0a9699ad-7ca7-4576-9509-3bdfcefc1522)

**Comment by Teabone3** [comment]
That's usually a common problem when new commands are added that handle external files. They just dont retain that information when exporting to standalone to copy over the files. I do know they have over time fixed this for some of the older commands. Perhaps this one needs to be added to that list?

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
