### ISSUE TITLE
GGMAX - Problem with lua command

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#5190]
There sems to be a problem with lua command 'SetGamePlayerStateCamAngleY(angle)" .
'GetGamePlayerStateCamAngleY(angle)" returns the correct angle but when applied with SetGamePlayerStateCamAngleY(angle)
does not seem to inhibit the player/camera angle as in the example below.

_if ( GetGamePlayerStateCamAngleY()<-45 ) then SetGamePlayerStateCamAngleY(-45) end
if ( GetGamePlayerStateCamAngleY()>45 ) then SetGamePlayerStateCamAngleY(45) end_

The same system applied to GetGamePlayerStateCamAngleX etc seems ok and applies a limit to the angle for up and down.
Just the left and right side limits dont seen to work.

**Comment by LeeBamberTGC** [comment]
@Necrym59 In gameplayercontrol.lua there is an override command:

SetGamePlayerStateCamAngleY(GetGamePlayerControlFinalCameraAngley()+(GetGamePlayerStateCamMouseMoveX()/ttRotationDivider))

Is this perhaps interfering with your own setting of the Y value?  As you can see, it gets its latest value originally from: GetGamePlayerControlFinalCameraAngley

**Comment by Necrym59** [comment]
Thanks Lee i hadnt thought of the overide, now sorted it out.
