### ISSUE TITLE
Audio User Subfolders contents don't get transfered to standalone game.

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5194]
If any subfolders are created inside of the audiobank user causing the path to be files/audiobank/user/example the example subfolder will not have the audio files inside of it get carried over when the game is exported as standalone, and adding them into the subfolder manually won't fix the bug.

**Comment by MonkeyFrogStudio** [comment]
All of this sort of thing will be fixed when they finally implement proper projects. Just an FYI.

**Comment by davetgc** [comment]
Flagged as a bug, but will certainly be fixed with the project system.

**Comment by LeeBamberTGC** [comment]
@extremestrategy As above, project system for the win, but I fixed this issue in the next EXP build so ANYTHING in the user folder will now be added to your standalone export as a short term hassle free measure.  With the new project system, I expect all redundant files to disappear from, future exports and make your file sizes more managable :)

**Comment by extremestrategy** [comment]
Seems to be fixed thank you.
