### ISSUE TITLE
Story Board Input Nodes not going to the right nodes.

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5195]
Inside of the story board, if a complex system is setup where there are multiple nodes going into one point it seems to bug out and cause the nodes to go into different locations, for example say you have a setup with a mission selector, and you have a previous and next buttons, that move between the maps, and then the missions are split up on different screens, those screens will start to overlap, and if you are in Sandstone Citadel and select purge you go to the assassination screen of the Deserted City.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/41132e55-8eb0-4925-8fad-7c89f962edbd)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/64b5f848-75e9-4a17-9da0-f149a19b2665)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/b4ca6b10-5804-4d87-a9b4-1b10b7d5ea54)

**Comment by extremestrategy** [comment]
@LeeBamberTGC Sorry, I forgot about this one for a bit, I sent you an email with a better explanation, however for reasons explained in the email I can't place a Google Drive link here, the bug seems to be caused when there are to many logic nodes going everywhere, and creating a duplicate project creates more issues as explained in the email.

**Comment by LeeBamberTGC** [comment]
@extremestrategy Fixed for next EXP build

**Comment by extremestrategy** [comment]
Fixed in the latest update.
