### ISSUE TITLE
GGMAX Bug - MAX Showing as "NOT RESPONDING" when loading a level that has a large collection list 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5196]
![Screenshot 2024-01-21 165414](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/ce6c8cdc-61c5-4b18-bb5d-e8547228174c)

This happens when you do several start-up tests of max to try something out like this

**Comment by davetgc** [comment]
Are you using custom media? That looks like a crash related to attempt to load corrupted files.

**Comment by SampeyFS** [comment]
no normal I started normal I did so

**Comment by davetgc** [comment]
Okay. I'd advise verifying your Steam files to see if this fixes the problem.

**Comment by casigus** [comment]
its not corrupted files it do with the project file its self being broken, its not custom media causing it. I deleted these 3 files and the project and maps work again. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/ca00dc67-4998-4aff-85c1-656dc82d7ff6)


try it! x

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/75894d62-1538-4420-9a63-301dab50def4)
the problem is still there, I removed everything, even the files, I had them done again but they are back to the same initial block because things are duplicated, it had been reported but it hasn't been fixed, max continues to duplicate ((objects not existing in the project))

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks for the collections file. Can you zip up and send me the whole projectbank\xxx that contains this file, I can then load the project and see what happens when the collection file is used with the first level loaded in.  Collection files will rebuild themselves based on the items in your level (those marked as collectables) and also use the collections ele file too.

When you mentioned "I deleted these 3 files and the project and maps work again.", what happened after that to make it not work again?  I assume you deleted the files, then launched MAX, loaded the game project, loaded the first level in the storyboard and you saw "maps work again.".  Did the collection files show up again after that, and then the next time you launched MAX you saw the not responding error?

**Comment by SampeyFS** [comment]
Yes now I send yes exactly as soon as you delete the files it loads ((almost immediately the game))

**Comment by SampeyFS** [comment]
yes now it crashes it takes a long time to start but it's those files xbecause I tried to remove it it starts almost immediately xbecause max dupplies objects as you see in the tsv files

**Comment by LeeBamberTGC** [comment]
@SampeyFS Can you post a screenshot here of the 'crash'? The one at the top of this thread is not a crash, but a "non-responsive" warning dialog only.

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/f182be2b-d010-4cf7-a24b-a571e7088388)
 start  games

**Comment by SampeyFS** [comment]
good morning Lee did you manage to find out why he does this?


________________________________
Da: Lee Bamber ***@***.***>
Inviato: Wednesday, March 20, 2024 9:44:33 PM
A: TheGameCreators/GameGuruRepo ***@***.***>
Cc: Studio Ascolese Games ***@***.***>; Mention ***@***.***>
Oggetto: Re: [TheGameCreators/GameGuruRepo] MAX Showing as "NOT RESPONDING" when loading a level that has a large collection list (Issue #5196)


@SampeyFS<https://github.com/SampeyFS> Can you post a screenshot here of the 'crash'? The one at the top of this thread is not a crash, but a "non-responsive" warning dialog only.

**Comment by LeeBamberTGC** [comment]
@SampeyFS Looks like the dialog you are seeing is not an out-and-out crash, but an unresponsive dialog. If you want 5-10 minutes does this dialog go away and enter the level for editing?

**Comment by SampeyFS** [comment]
yes after a while it comes in but it takes a long time
________________________________
Da: Lee Bamber ***@***.***>
Inviato: mercoledì 20 marzo 2024 21:44
A: TheGameCreators/GameGuruRepo ***@***.***>
Cc: Studio Ascolese Games ***@***.***>; Mention ***@***.***>
Oggetto: Re: [TheGameCreators/GameGuruRepo] MAX Showing as "NOT RESPONDING" when loading a level that has a large collection list (Issue #5196)


@SampeyFS<https://github.com/SampeyFS> Can you post a screenshot here of the 'crash'? The one at the top of this thread is not a crash, but a "non-responsive" warning dialog only.

**Comment by SampeyFS** [comment]
yes after a while it comes in but it takes a long time
________________________________
Da: Lee Bamber ***@***.***>
Inviato: giovedì 21 marzo 2024 17:14
A: TheGameCreators/GameGuruRepo ***@***.***>
Cc: Studio Ascolese Games ***@***.***>; Mention ***@***.***>
Oggetto: Re: [TheGameCreators/GameGuruRepo] MAX Showing as "NOT RESPONDING" when loading a level that has a large collection list (Issue #5196)


@SampeyFS<https://github.com/SampeyFS> Looks like the dialog you are seeing is not an out-and-out crash, but an unresponsive dialog. If you want 5-10 minutes does this dialog go away and enter the level for editing?

**Comment by LeeBamberTGC** [comment]
@SampeyFS Okay, thanks for confirming, I have something to go on now :)  Can you tell me how large your custom "User\GGClassic\" is and can you also email me the 2 FPM levels showing in the game project, thanks!

**Comment by LeeBamberTGC** [comment]
P.S. In the next EXP build I have added extra debug logging so we can see the timings of loading in a large collection file. When you get the next EXP update (in 10 minutes), run again and load the level, then send me your LOG file found here: "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log"

**Comment by SampeyFS** [comment]
OK OK

**Comment by SampeyFS** [comment]
Then the GGClassic folder is 3.16 GB.

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks for the info. A new EXP build has just been uploaded. Can you load you project again, then load your main level, and then send me the LOG file. I can then see the timings on loading all the collection items in, thanks!

**Comment by SampeyFS** [comment]
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/14705789/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@SampeyFS Looks like there are a lot of collection items that are not tied to any actual object in the level and being auto generated.  This might explain the slow loading times. I also compared your LOG timestamps for booting up and your system runs slightly slower than my test gaming laptop which only has 2 cores, so might point to a very large level with many objects causing the long loading time. When you removed the collection list, it only loaded the level objects and not the hidden auto generated objects from the collection file. I have emailed you a new collection list file TSV and ELE to replace the one you are using.  Hopefully it retains the details you have provided and points to actual objects to be loaded. You can delete any objects you no longer require for your game before loading the storyboard and the level for a quicker loading time.

**Comment by SampeyFS** [comment]
ah ok now i do and try it let's see thank you very much
