### ISSUE TITLE
xbox controller

### ISSUE THREAD

**Issue by exadion** [TheGameCreators/GameGuruRepo#52]
gameplayercontrol.lua refers to a variable JoyStickTwistY which doesn't exist
here:

ttjoyroty=((JoystickTwistY()+0.0)-32768.0)/32768.0

When xbox control is on the game crashes. globals.lu refers to JoyStickTwistX and JoyStickTwistZ. Z always seems to remain 0.

**Comment by LeeBamberTGC** [comment]
This has been fixed in the last PublicPreview build, and JoystickTwistY will be added to the global.lua help of the next build.
