### ISSUE TITLE
control slider for parallax seems to be missing.

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#5200]
Hi, i'm not seeing the slider for height control in the materials window.

![p1](https://github.com/TheGameCreators/GameGuruRepo/assets/35744254/21f3493c-08ed-42bd-a739-74f1217e4892)

is that hidden or placed somewhere else?

**Comment by MonkeyFrogStudio** [comment]
I'd requested a slider for height maps a long time back:

https://github.com/TheGameCreators/GameGuruRepo/issues/4538

**Comment by earthling45** [comment]
> I'd requested a slider for height maps a long time back:
> 
> #4538

Ohh yes, i see. :)

I regard that slider quite important and part of the core for setting up the material, not an enhancement.
Adjusting a heightmap in a paint program is quite destructive and should not be needed.

**Comment by davetgc** [comment]
Closed in favour of https://github.com/TheGameCreators/GameGuruRepo/issues/4538m but linked for reference.
