### ISSUE TITLE
GGMAX - XTERRAIN TOOL HUGE BUGS

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5201]
Hi, i purchased that tool to change ggmax default texture...i was happy at first....
So i started with a png 2048x2048 i generated the textures and it crashed...........
I restarted and it generated the texture....
Then i put those textures inside ggmax terrain textures and i launch ggmax...
In my scene, i have a MASSIVE cave, with holes in the ceiling and the sun pass by those to make an interesting scene.

I painted the ground with that fresh texture, and BOOM it generates a BLACK distance fog or something on the ground, with a small bright thing on the material...

I tried EVERYTHING....IMPOSSIBLE to REMOVE that black bug on my terrain scene....
![texturebug01](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/df65918f-78c7-4cc6-b297-96ee7b75ba2c)
![texturebug03](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/3a2f85b0-6730-48b7-8485-f676a81d78e6)
![texturebug05](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/1af7b6bc-cdf5-4d1f-a494-59dbc151ae8f)

When i paint with the DEFAULT ggmax textures i don't have that bug
![texture-works01](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/1976e52e-735e-44bc-adf1-04c1fb539306)

if i retest again with my generated texture it fails, and i get that massive black bug...
![texturebug07](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/64bb155d-14ac-42c5-8d1d-270b79f8f856)

OUTSIDE my cave it works
![texturebug06](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/462ecd52-e1f0-428a-ab95-d9aeb5884028)

The system is at the highest level of quality in ggmax, and shadows are in 2048, i tried every size....
SO
NOW...when i TRY to OPEN an original GGMAX texture..... the software TELLS ME...
INSUFFICIENT MEMORY..... i have 32gb ram, and 11gb video, 1tb ssd nvme2 windows 10.

![ERROR MEMORY](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/17de0e55-ff14-4055-9d74-686113e43d5e)

**Comment by imothep85** [comment]
in my purchasse download...
 i have only this version.....
![download old version only](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/5a019a31-1583-44c7-8646-ec7d460e426d)

**Comment by imothep85** [comment]
AGAIN, first picture my NEW texture who generates a MASSIVE black shadow in the distance....
![cave view](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/de82b8c8-f889-469a-84bd-c981e1c7f37b)


AND the same cave, with an ORIGINAL texture from ggmax, the bug disappear...
![cave view02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/b80dd3ca-0119-4583-a766-9a5edb9634fe)

**Comment by synchromesh62** [comment]
Closing this ... Nothing to do with TGC Or Max

**Comment by imothep85** [comment]
the problem was MIP's have changed  

"GraPhiX — Today at 8:54 PM
MIP's have changed LOL i dont get the Memo's 🤣  i will relase a patch ASAP"
