### ISSUE TITLE
Bug particles

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5202]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b8f01e92-2888-4c58-b7e0-b871c0db52b8)

Every time you put the particles on it comes out like that and it doesn't go away, it has to be waxed max and it goes away.

**Comment by davetgc** [comment]
I couldn't replicate this, can you please supply an FPM? (Map file)
