### ISSUE TITLE
BUG with Task Tool behavior

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5203]
hello, it's a bug with the behavior "task tool" in the pick-up  we select "automatic" the script doesn't work it's impossible to achieve the task. 
in "manual" it works but in "automatic" the behavior doesn't work

**Comment by Necrym59** [comment]
This has been fixed and checked - all working. Do a workshop update.

**Comment by davetgc** [comment]
@imothep85 - Can you confirm this is fixed?
