### ISSUE TITLE
Objects including in MAX library that aren't present in level.

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5209]
![Screenshot 2024-01-30 104512](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b097f40b-a323-4dc5-9386-1c2a66e84541)

Max Generates objects never placed in the scene I found many never placed

**Comment by davetgc** [comment]
Are you able to supply a copy of the FPM please? If you don't want to post it here, you can email it to Lee@thegamecreators.com referencing this post.

**Comment by SampeyFS** [comment]
https://www.dropbox.com/scl/fi/rnt2fnv3yox8c0g10c8sc/Forest.fpm?rlkey=yg7rwc8grldagdxk18ri4w2o5&dl=0

**Comment by LeeBamberTGC** [comment]
@SampeyFS When you see AUTO-GEN it means you have this object in your collection items list and the engine needs this object if the player was ever to buy such an item from a shop and then drop it into the level.  You can delete this object from the colleciton items list, and then you can delete from your level, then save, and it will not reappear, but the object will be removed from your collection items list so be careful you want to do this for your game project, not just that level.

**Comment by SampeyFS** [comment]
ah ok alright thanks Lee lo hope the hunting script will come out :)
