### ISSUE TITLE
NPC Control health set to 2050

### ISSUE THREAD

**Issue by Gh0wsty** [TheGameCreators/GameGuruRepo#5210]
The health for my custom character is set at 2050 and the character dies when it reaches 999.
Any health set in the character settings just adds onto the 2050. For example if i set the characters health to 1, the health will be 2051.
I have tried settings the FPE strength to 0, 250 and 500. All of which made no difference.

https://github.com/TheGameCreators/GameGuruRepo/assets/158174782/a3ecac48-95ee-4a0f-ac5f-6e55f55d51d3

**Comment by Necrym59** [comment]
And your question being??
It is still the value you set but internally it adds 1000 to deal with the death process at 999 it makes no differencet to gameplay.

**Comment by Gh0wsty** [comment]
> And your question being?? It is still the value you set but internally it adds 1000 to deal with the death process at 999 it makes no difference to gameplay.

That wasn’t the main problem, I just thought it was weird. 
The problem is I can’t change the health at all. I can only add on to the 1050 health. And if it’s intentional then why is the health set to 1050?

**Comment by Necrym59** [comment]
The NPC Controller was originally intended for legacy, non characater creator characters as such its handling of internal death state was a bit different. Essentially any if you have a character with with anything less than 50 it will ensure it starts at 50 + the 1000 to deal with the death process at 999 so essentially you still have 50 points. If you have a character health above 50 to begin with  it will just add the 1000 to deal with the death process at 999 so essentially you still have the original start health points.
Its an internal value and is shown only in the diagnostics for informational use. You can change the health in the character section.

**Comment by Gh0wsty** [comment]
> This has now been adjusted to reflect the true value in the readouts.

I’m sorry I think I’m explaining myself terribly. My problem isn’t the diagnostic. It’s the fact I can’t set my characters health to anything below 1050. So it takes far too much damage to kill them.
