### ISSUE TITLE
WinKill ignores headshots on zombie 02

### ISSUE THREAD

**Issue by Gh0wsty** [TheGameCreators/GameGuruRepo#5211]
Killing zombie 02 with a headshot using any of the prepackaged weapons does not effect the WinKill behaviour.

https://github.com/TheGameCreators/GameGuruRepo/assets/158174782/0ba43873-2bfc-4759-af36-6bd1ef0ab77c

**Comment by Necrym59** [comment]
Try a different zombie eg: Z4 and report the results if possible
