### ISSUE TITLE
Trigger Zone Low Fps

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5213]
![Screenshot 2024-01-31 110408](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/660fb7f0-7c67-4ccc-8119-9f90d317018a)
Big problem detected when you enter the Trigger Zone the FPS drops this does not happen right away as soon as you enter the Trigger Zone but after a while it starts to do as soon as you enter the Trigger Zone the FPS drops from 45 to 18 and stays there at 18

**Comment by Necrym59** [comment]
More explanations is required, what script is running on that zone for example?

**Comment by SampeyFS** [comment]
the script that does this is your NPC npc_itemdrop when you enter it does this by triggering the game

**Comment by synchromesh62** [comment]
> the script that does this is your NPC npc_itemdrop when you enter it does this by triggering the game

npc_itemdrop ?
Thats not supposed to connect to a zone ?
it connects to an asset .. No wonder its messing up.

**Comment by Necrym59** [comment]
There is no problem, it functions correctly, please close this posting.
