### ISSUE TITLE
GGMAX Bug - Blocking at project start-up

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5214]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/06cebd52-80ba-4105-ae30-f1add88737cd)

The project crashes when I start up, after a while it starts up again, I don't know what it is, I've checked everything, I've done this once before on the map (Empty), who can help me?

help

**Comment by davetgc** [comment]
We'll need some more information. It sounds like a local issue. The fact that the level will start suggests it's not a MAX issue. If you can narrow this down, we'll be able to investigate.

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/11decaa3-945c-49ef-a0cf-07429592bf31)
the problem is inside here I think it is due to the suspicious loading of the weapons shop xbecause if you put weapons on sale it does so I have tested it
