### ISSUE TITLE
GGClassic - Save/Load game in Standalone forgets about sound playing

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5217]
When there is a music playing, or other sound or ambience, and the player saves the game, then when he loads the level it's silent or however forgets about all that was happening, especially when you have 2 different music zones, and you already triggered the second one.

**Comment by Teabone3** [comment]
Interesting find. Seems the only workaround for now is using an additional custom global to remember that specific audio was playing or stopped.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
