### ISSUE TITLE
GGClassic - allowfragmentation = 2 and ammo set to 0

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#5218]
I noticed that, while "allowfragmentation = 2" in the setup.ini file prevents next levels to crash, it just sets weapons to 0 in the next level and it stays like that even if you collect ammo.

**Comment by thecyrus** [comment]
NOTE: it happens with Enhanced Weapons.

**Comment by thecyrus** [comment]
NOTE: it happens with **Enhanced Weapons**.

With stock weapons this doesn't seem to happen, but it makes most of the Enhanced Weapons Pack unusable.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
