### ISSUE TITLE
Terrain Visibility Flag in View Options

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#5219]
Add support to hide/show terrain from the View Options menu, and additionally a complete terrain off/on tick box for the level as a whole:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/65a4f81a-701a-4c7f-b5bb-c39528326178)

Work in the same way as toggling Trees/Grass/Water with the current MAX system for consistency.

NOTE: Terrain is a huge drain on performance, having this option should yeild a huge performance boost for levels that do not need terrain at all.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC A few questions on this:

- With the terrain off or hidden, can the camera go below where the terrain was? Currently, the camera collides with the 'terrain', even on an 'empty' level.
- Would you be able to place objects below where the terrain was, as if it's not even there (i.e. basements, sub-basements, lower levels, etc.)?
- How do you place objects at zero (ground level) without the terrain (if any of the above questions are true)? Most 3D game editors have a grid plane to represent zero along the XZ axis and objects can be snapped to it.

**Comment by Necrym59** [comment]
A semi-transparent and non collidable see through grid generated to the size of the playable map area should suffice for a guide for positioning of objects all new objects i should expect would be dropped at 0,0,0  (centre) in respect to the screen viewpoint.
positioning will then be free movement with the 3d world scope.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Yes, we can no turn off the terrain from being visible (thank you), but the camera in the editor still can't go below where the terrain was. This makes it difficult (if not impossible) to create interior sub-levels.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC What we really need is No Terrain at all (not just an invisible one) along with Snapping on the up/Y axis to help align objects when we create interior only levels.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Can you create two new issues from your suggestions above as it should be relatively easy to invoke the grid plane in the editor and switch off any terrain collision in the game itself.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Sure. But what about snapping on the Up/Y axis?

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC I'd already put in a request for snapping on the Up/Y axis back in November of 2021. You can read the thread here:

https://github.com/TheGameCreators/GameGuruRepo/issues/1568

**Comment by Necrym59** [comment]
Snapping on the Up/Y axis should be tied in with the grid options on the top bar as noted in the posts above

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Here they are:

Turn off collision on hidden terrain:
https://github.com/TheGameCreators/GameGuruRepo/issues/5420

Add grid plane when terrain hidden:
https://github.com/TheGameCreators/GameGuruRepo/issues/5421

**Comment by MonkeyFrogStudio** [comment]
> Snapping on the Up/Y axis should be tied in with the grid options on the top bar as noted in the post above

Indeed. But it still needs to be added, especially once collision is disabled for hidden terrain. So far, neither Classic nor MAX has snapping on the Up/Y axis and it's sorely needed, me thinks.

**Comment by Necrym59** [comment]
Yes i agree it is a must

**Comment by MonkeyFrogStudio** [comment]
Also, as a side note - as pointed out in the link below, there's really no reason to have separate snap settings for each axis (X, Y, and Z):

https://github.com/TheGameCreators/GameGuruRepo/issues/2667

I actually don't know of another 3D program, be it a modeling app or game creation system, that allows for different snap settings for each axis. So, it would be great to simplify this to have a simple snap setting (just one) that affects all three, X, Y, and Z.

**Comment by Necrym59** [comment]
No its not needed seperatley they can be locked to change together in sync would have been the obvious solution
