### ISSUE TITLE
Need better Project Files management system

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5224]
Something is breaking my project files, i've created new project files for titanic and for a time they work fine, and then with out any explanation when I try to test a level Max just completely freezes.

I have no idea how to replicate this error.

HOWEVER if I create another new project the levels load fine, however if I save that project and re-load it, it takes ages to load that level meaning something to do with max project files and levels are conflicting some where.

Heres what happens:

https://www.youtube.com/watch?v=waUU1CeVUHM

**Comment by SampeyFS** [comment]
Yes, I too have had this happen to me I have already reported it but it still hasn't been fixed

**Comment by SampeyFS** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/5196

**Comment by Necrym59** [comment]
Project System is being revamped internally i think just bear with it if you can

**Comment by davetgc** [comment]
I'm pretty sure the project system will fix this.

**Comment by SampeyFS** [comment]
yes it is in here xbecause I have done various tests and the problem goes back to here

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6053ffab-88b9-48e8-83f3-e64bead56e1e)

The problem is not solved now it still does but will you solve it?

**Comment by SampeyFS** [comment]
that correction I know nothing

**Comment by SampeyFS** [comment]
> @SampeyFS-Hai seguito la correzione fornita da@casigus ?
> 
> Provalo nel progetto interessato e fammi sapere se aiuta.
> 
> Grazie.
Maybe I have discovered the problem me and my team have removed the tsv files and rewritten all the shops basically the items you remove you have to ( delete also the Auto Gen ) xk why it always stays saved in the tsv we are testing ( it seems to work ) but we don't shout xk why even the first time it seemed

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks for the update, and yes the collectables files can get a little confused sometimes, a think we can bolster with the new project system, making them easier to monitor and manage.

**Comment by LeeBamberTGC** [comment]
The Central "New Project System Issue" now here: https://github.com/TheGameCreators/GameGuruRepo/issues/2301
