### ISSUE TITLE
Camera Shake Behavior

### ISSUE THREAD

**Issue by cdeweyh** [TheGameCreators/GameGuruRepo#5225]
The only once control does not work. Also, the shake effect increases during firefights making it unplayable.

**Comment by Necrym59** [comment]
No problem here can you be more specific as to how its being used!

**Comment by synchromesh62** [comment]
> The only once control does not work. Also, the shake effect increases during firefights making it unplayable.

Just did a test and seems to be working fine ?

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/a7c1d030-5b70-46c2-b33d-071b1ccb093a

**Comment by cdeweyh** [comment]
As I move through the level, the shake effect keeps recurring, and when I get into firefights the camera shake effects gets worse making it unplayable. I've tried all the settings, but I can't seem to get it to work.  Thanks for your time, I appreciate it.

________________________________

**Comment by cdeweyh** [comment]
[https://res.cdn.office.net/assets/mail/file-icon/png/video_16x16.png]2024-02-10 10-58-03.mp4<https://1drv.ms/v/s!As0OyMH2gfiahrZzTgKDpcz5dEzoSA>
Maybe this will help, let me know and thanks again for your time.​
________________________________

**Comment by Necrym59** [comment]
Try as i might i cant seem to replicate the problem, and neither can others, can you try and delete the particular behavior and save the map then re put in the behaivor and try again and see if it repeats the prblem.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
