### ISSUE TITLE
Amd error Failed to create the graphics device! error 80004005

### ISSUE THREAD

**Issue by Jacobthehorror** [TheGameCreators/GameGuruRepo#5227]
I have made my standalone game and i had one issue its only for amd that is broken but for nvidia is fine not sure what do 
![errore](https://github.com/TheGameCreators/GameGuruRepo/assets/158771993/707e9bfb-42e8-46ce-9bc0-cd7e4c21e9d5)

**Comment by Jacobthehorror** [comment]
@davetgc The problem got fixed the issue was my brother had to reinstall windows to make it work

**Comment by davetgc** [comment]
Thanks, glad it's fixed.

**Comment by Labsdj** [comment]
What version driver you got and the gpu and version windows [Jacobthehorror](https://github.com/Jacobthehorror) i got  same bug error on Windows 11
