### ISSUE TITLE
Craft Portable Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5228]
![Screenshot 2024-02-04 103305](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/de23287f-0cd0-49e5-b89e-5e7521e97e3f)
![Screenshot 2024-02-04 103255](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/00f787a9-0770-49f5-b4aa-090eef9a583c)
![Screenshot 2024-02-04 103250](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6164f308-ce75-4c11-80a7-52ee301a99c9)

As you can see when you take the craft portable bag you can see the object at the top

**Comment by Necrym59** [comment]
What object? can you please be more specific. Also please close any other posts that have been fixed,

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/9df969de-b8f7-416b-afe9-bacede26d41b)

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/500da5cb-04a6-40d0-89d7-d0a15e0e695f)
