### ISSUE TITLE
third person clipping bug

### ISSUE THREAD

**Issue by pauldidy** [TheGameCreators/GameGuruRepo#523]
third person clipping bug, also recorded by syncromesh.

video=youtube]TSeJeap2Xsg[/video

**Comment by LeeBamberTGC** [comment]
Is this the same as for issue 509?

**Comment by pauldidy** [comment]
No same as reported by syncromesh  #413

Clipping is not 100% on the right hand view as shown in the video
Tested with Stock characters as well .. The left hand zoom seems spot on.
https://youtu.be/2WzWcuF7LK4




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by synchromesh62** [comment]
Corno_1 has sent me a fix to try for this which works perfectly and I believe its added to his branch for merging.

**Comment by pauldidy** [comment]
Thanks hope so would be good.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
