### ISSUE TITLE
Items showing up in my level that are not placed GGMAX

### ISSUE THREAD

**Issue by C4ever08** [TheGameCreators/GameGuruRepo#5231]
Hello recently have ran into issue where if I make a new map in GGM. I now get models that show up in the level objects panel that i did not place as its a new level and is causing GGM to crash if placing an actual model. This even occurs on existing maps that don't have the items in level too. I have also tried to Verify but its still the same, And I also installed GGM on a new PC and its still happening. Also seems like the items are actually under the map and I can delete them but it seems they still are active somewhere as it still shows up in the panel.
![GameGuru MAX - planet fpm_ 2024-02-06 11_53_28 AM](https://github.com/TheGameCreators/GameGuruRepo/assets/80596156/7277dae3-617f-45c8-bac0-ecc73b046110)
 Here is also the FPM but it wont have my custom guns but the keys and Magnum are stock
[planet.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14183826/planet.zip)

**Comment by davetgc** [comment]
These are objects that are created by the crafting system and will be because you've flagged them as craft items, consumables or similar.

**Comment by C4ever08** [comment]
well I was messing with the RPG system for my huds in a separate level including just the key. My custom guns are not set for collectible for crafting its set up for pick up weapon so those should not be there. But when i loaded my game project and started working on it after i saved it those same items showed up in list again. I did delete the tsv files to see if that would work but it adds them back to my existing projects now. But on new maps it seems fine. It seems the same tsv files were in all my game project folders. Also the Magnum I've never used yet. but the ARC shot gun and energy gun are my custom ones.

**Comment by C4ever08** [comment]
Wanted to add I've also tried to delete these items as they seem to be stuck under the terrain. Once i do and save they somehow are still their so its confused me to why these items are being placed in my existing maps. And the only item i ever used for the questing script was that brass key.

**Comment by C4ever08** [comment]
Ok some news I have fixed the issue I think lol. So what happened tonight i thought there must be more to this so I had backups of my project and decided to delete all my game projects in documents folder. Then i thought Ill check the core files and opened project files where the demo maps are and saw a few in there that somehow ended up in there that were mine so I deleted those too. Then I put my project back in and loaded the first map and deleted the items and it actually deleted them this time I also checked other maps and can confirm it fixed it not sure why that happened. So you can now close this post now.
