### ISSUE TITLE
Shop Spawner  Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5239]
![Screenshot 2024-02-07 194958](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/ec67ff0e-65b8-445f-b6c8-b66f70d62614)
here's the problem look at the ( torch ) I put one in look at how many Max put in here's the reason why it locks up xbecause it doubles the items for sale by itself equal

**Comment by Necrym59** [comment]
You need to clear out the collection - items tsv reboot and try again and see if it replicates the problem then post that file here

**Comment by davetgc** [comment]
@SampeyFS - Can you please try the solution suggested and let me know if that works?

**Comment by SampeyFS** [comment]
yes I did it works as soon as I save it still puts the torch back on, however deleting that file replicates that initial blockage

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/74da11a9-d33e-4075-9421-8b4ca8b7e3bd)

**Comment by SampeyFS** [comment]
this object Chips has never been put in this project you see that you put it on your own

**Comment by SampeyFS** [comment]
I discovered the culprit of the blockage is this files collection - items.ele

**Comment by SampeyFS** [comment]
No always that problematic file has to be solved

**Comment by SampeyFS** [comment]
This blockage is still there we need you to solve it xbecause we risk ruining the projects we do! @davetgc

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/e4347825-4a81-4630-b565-858b93c40ec6)
fix the problem xke also freezes the PC is not solved the problem still does it

**Comment by SampeyFS** [comment]
![Senza nome](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/84ee96b9-25ff-4207-ae78-6cbe503e338e)
