### ISSUE TITLE
BUG ggmax PARTICLES kill shadows in level.

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5240]
Hi, in my game if i create a fire particle, and ADD it to my level, the SHADOWS are killed, the level become SUPER BRIGHT, EVEN if the particle is very small or far.

Here its my little fire particle that place is very very far from the begining of my level.
![fire particle kill shadows](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/3e848bf9-3536-4fe8-92e2-dbf6902c44c0)

when i start the game the level is super bright because of that particle, it's flat and has no more shadows.
![fire particle kill shadows results](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/0fdac56b-2410-4fcb-aabb-be27df7ef437)

WITHOUT the particle
my level is correct with the shadows and lights.
![without fire particle result](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/5652b00f-3313-4101-84ad-5d93a3b77a82)

ALSO when i create a particle the particle editor is NOT generating a thumbnail.
![particle no thumbnail](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/1fa963e7-f633-4db3-9601-704689714114)

**Comment by imothep85** [comment]
and here are all the parameters of my fire particle.
![fire particle01](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/06734cfa-8683-405b-a05f-94f87405308d)
![fire particle02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/a2399ad9-1539-45e2-8b17-6f2775c0ef54)
![fire particle03](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/415fe3bd-60ee-430e-8fb1-df9a22177ffa)
![fire particle04](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/987a5921-cb8f-45e6-a4c3-643e951440f9)

**Comment by LeeBamberTGC** [comment]
@imothep85 has this been resolved in recent EXP builds?  If not, are you able to create a small stock level using particles that come with MAX to reproduce the issue you describe where shadows are killed?

**Comment by imothep85** [comment]
as soon as ggmax EXP is fixed and working again i will do a test of particles to see if the problem is still exist !

**Comment by imothep85** [comment]
Hello Lee just to confirm that THIS problem is no more, my particles are working now in the latest EXP version, the particles doesn't kill the shadows anymore.
![particles working](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/9db1d414-4435-4c70-8d4c-00a5d58f84c6)
