### ISSUE TITLE
BUG - Enemy characters disabled when a flag is in the scene

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5242]
In this video I will demonstrate that by adding a flag to a scene it will disable the enemy characters. This does not seem to affect ally characters or zombies. I am of course using the experimental build. This bug has been replicated by Necrym59 independently.

https://youtu.be/VNQQ5fYrNAE

**Comment by Necrym59** [comment]
Confirmed

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive I created my own empty level and after adding the flag I still got attacked:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2146e1d3-9d5a-46de-955b-76cbc6fc3e8e)

Can you send me the FPM you used as it might be related to which soldiers were selected.

**Comment by DBird-1994** [comment]
I couldn't replicate this bug either.   They attack me whether there is a flag in the level or not.

https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/b275c9a4-dce3-4e82-98a2-0a668d92c8d6

**Comment by DBird-1994** [comment]
Actually I see the bug now, but I only see it if I have "Follow A Path" ticked in the behavior settings, if I turn that setting off they attack normally.

**Comment by Blood-Moon-Interactive** [comment]
Good call out DBird - I took the testing a bit further in this video and determined that the tick box does appear to be central to the bug, but so too does proximity to the flag. I'm also able to demonstrate that the bug is character and level agnostic. 

https://youtu.be/trtQzjL0iZ8

**Comment by LeeBamberTGC** [comment]
@DBird-1994 @Blood-Moon-Interactive A nice reproducible bug, well described, Lee likes :)  Thanks for your efforts!!

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive I have made a bunch of levels now, and they all frustratingly work for me, with ticks on and off, near and far, flag and no flag:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/bc5a9550-2fdb-4446-9972-7730b49986b6)

That offer of attaching the FPM level would really help, thanks!

**Comment by Blood-Moon-Interactive** [comment]
Oh sure they're on their best behavior for you....ok file sent

**Comment by earthling45** [comment]
Out of curiosity, if you guys select the demo horseshoe bend, is the ai working for you or are they just standing there but not attacking?

**Comment by DBird-1994** [comment]
@earthling45 For me they are standing motionless and not attacking on the horseshoe bend demo.   

https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/a3d3f811-c1b6-45f7-8b1b-44fa2deddd2c

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Thanks for the test level, was able to reproduce and fixed for the next EXP build.  Horseshow bend level and other levels that have characters that need to find paths also work again :)
