### ISSUE TITLE
Added function to Eat scripts

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5243]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/8db8bc9a-65e7-4b38-99c9-76484f9ec580)

I wonder if you could insert the function of putting food in the inventory like the Potion script, because then you can take food with you and use the one you don't respect when you're full by overstepping the eating or drinking bar.

**Comment by SampeyFS** [comment]
the small update that came out earlier caused the FPS to drop further  @LeeBamberTGC

**Comment by Necrym59** [comment]
Eat is for eating, just use a item pickup to ppickup and store in the inventory

**Comment by Necrym59** [comment]
Another behavior called "food" is available for this purpose - ensure you have updated your workshop items

**Comment by SampeyFS** [comment]
do you mean the Potion script xxxx does not respect the food bar goes over how come?

**Comment by SampeyFS** [comment]
thanks buddy
