### ISSUE TITLE
Weapon and Ammo.Lua's missing from the core ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5244]
As stated ..
weapon and ammo.Lua's seem to be missing from the core ?
The images are there but not the files.

![W1](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/98dec107-3449-456f-a78d-54823d45d284)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 That was a strange one. Fixed for new EXP build :)
