### ISSUE TITLE
Won Screen showing instead of Won Level - update 18 12 2023

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#5245]
still showing won screen instead of new won level the positioning have reverted to the old box symbols
tried validating the files in steam but still the same that is the last update i have received 

mark

**Comment by LeeBamberTGC** [comment]
@zeebon There is no WON SCREEN option, only WIN LEVEL and NEXT LEVEL. In the latest version WIN LEVEL allows you to move to a scene (screen) when the player exits the level, whereas NEXT LEVEL takes the player directly to another level:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b4277419-5a6a-4841-a9d6-049a82992f8e)
