### ISSUE TITLE
GG Max - Workshop not showing items or updating.... Just empty

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5249]
As the title says, My workshop is not updating or showing any items.
I have tried following the onscreen instructions of restarting Max, but same thing, Nothing is there.
I have verified Max files, and everything is correct.
I have deleted the Gameguru Folder in Documents and let it rewrite it. And as you can see from screenshot 2, there is no community folder even showing in there.

This means am missing a lot of behaviours, even things like weapon.lua is missing.

This is happening on both normal build and EXP build. 
No access to workshop.

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/5913e457-9ee0-4d79-815f-f27d57f4cd23)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/5774d168-ed61-4d85-b572-39436b302128)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Do you have the trusteditems file in your root folder:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b2d99970-3c9d-4f42-b6f4-9a6d6c69cfe8)

I currently see this in the EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/eb8c801e-4606-4c78-a9f6-afcf235d7373)

When I cluck the update button I see this:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e5f14317-bb68-4bb6-8b59-122465a0eab9)

Then this when I tab out and back in:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e9d5c52f-1c9d-4f98-bb99-4e283b782ab8)

I then exit and relaunch MAX and see Update behaviour on Steam client:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b371ab57-eaea-48fe-a1da-f20a20367765)

After about 2 minutes, the updating finishes:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/92c0821f-9c22-44a2-a26c-c9c453a8a33f)

Anbd when I return to the workshop tab, I see these screens:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a7793361-ba12-47d3-afbb-cbf768402db1)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/09ddaefc-a288-41d8-bc7f-3987a403f5aa)

At this time I can check the workshop internal folder, and see all the assets ready to copy to the community area:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/3ba6ee08-5754-4ea6-b735-fdfda55ca53f)

And here they are:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/9b76aa37-095e-4253-8fbd-6976cdca8608)

Can you go through the above steps and see how far you get, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Hi, Yes i have that file in the main gameguru max folder.
These are the numbers inside that file.

2980633676
2988575408
2992375810
2996155883
3006623648
3017318353
3026988517

**Comment by Tum1370** [comment]
My workshop list is just empty when i try and update it, And it remains empty after updating it.

**Comment by Tum1370** [comment]
![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/03016127-ffc1-4815-bf74-17c56751bdf4)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/f6704043-9015-47c2-b68c-b19067b6e853)
![3](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/d9951606-475b-45d9-b4d7-ca29152c3dd7)
![4](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/31c1266c-d42f-448a-aa9a-0a2faf816049)

**Comment by LeeBamberTGC** [comment]
@Tum1370 When you restart MAX, you should not see the RELAUNCH text. I take it after you relaunch, you only see the UPDATE button screen.  When you click the UPDATE button and then exit MAX, can you screenshot what your Steam client download area is doing. Follow my shots to know which parts to snapshot, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Nothing downloads from steam after clicking update after exiting max.
Also, i do not see that list of items that you see on yours.
Mine does not seem to access the steam workshop at all.

**Comment by Tum1370** [comment]
That page with Workshop items is just empty on my screen, Both before and after clicking update button.
And also after exiting and reloading Max, Just empty .

**Comment by Tum1370** [comment]
For some reason, Max does not see any workshop items, that is why my list is empty. 
Here is my screenshot of steam after exiting Max, after clicking Update and getting the message to exit.
![Untitled](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/299fb540-21e7-47aa-8e92-a86f7e62a90f)

Steam downloads nothing. As Max's list of workshop items was empty for me.

**Comment by Tum1370** [comment]
Your Max clearly has a list of workshop items listed before and after clicking update, Mine does not !

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for the extra info, looks like Steam is not (a) subscribing to the items or (b) prevented from downloading them.  When you launch MAX, alt tab back to the Steam Client page that shows this screen and wait for 2-3 minutes:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a8eb20cd-3a8a-4fd4-a039-aad30ce90862)

MAX should be subscribing in the background, and then instructing Steam to download the latest items.  It will not do this when MAX is not running, so needs to be launched and running when you view the Steam client downloads page.

Can we compare Steam download settings, just to make sure its not in there:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/e82ab050-2cd6-4194-a71d-082b2f122604)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6c34850c-4685-447a-86a9-278d2f56f3f5)

**Comment by Tum1370** [comment]
Still an empty list and nothing downloads after waiting.
As you can see from the screenshots, Max is running in the background, and steam client is above Max so you can check Max is actually running.
My Steam download settings are here to.

![3](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/7205c0fc-0567-445d-8b2d-7142c9b79690)
![4](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/d3a0dd1c-fee0-4201-813a-65888d089e54)
![5](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/f65e638f-140c-4115-856e-b57ca0be5e26)
![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/3d54d7a0-c753-44ef-b7ad-3169f9f9e288)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/6ee38beb-fe84-45c3-a664-afccae251d73)

**Comment by Tum1370** [comment]
@LeeBamberTGC Do you have any more news on this workshop bug ?
I have tried rolling back from EXP build to Normal build, and nothing happens still.
The workshop items are not listed in Max, and do not update.
Missing a lot of behaviours due to this !

**Comment by LeeBamberTGC** [comment]
@Tum1370 It may be Steam settings. Can you try setting yours to look like mine, then restart the PC and see if Steam acts differently with the same correct steps you made in the last post, thanks:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/44b57de2-17ee-4b0a-aa9a-32d93785f38d)

**Comment by Tum1370** [comment]
@LeeBamberTGC I didnt think making those changes would make any difference, And i was right.
Exactly the same.
No items show in workshop on Max, and updating does nothing.

![Untitled](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/33ca0eb8-6aa5-4248-89ac-187fb3c415ce)

**Comment by Tum1370** [comment]
@LeeBamberTGC I dont understand why this has suddenly stopped working, when it use to work fine.
For me, it seems Max related as its just not seeing that list of workshop items in Max, on the list.
Your list was populated, before even pressing update. 
Mine is just empty :(

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you locate the equivilant folder as shown here. It is the internal folder Steam uses to hold workshop assets before MAX copies them over:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/379a677e-cf57-48a9-8172-987db6288dd8)

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Hi, Yes that folder is there, and i also see that it has updated 11th february, and 1 folder updated 12th february.

But these folders and items are still not copying over to gameguruapps folder in mydocuments folder, and still not showing up in Max.
![Untitled](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/41e112e0-9b5c-45d1-8f71-a32f00c72fc2)

**Comment by Tum1370** [comment]
Your Max on the workshop page was populated with all these folders and items.
Mine to was like that, and these were all listed there.
Its just now they are not listed and not updating or showing anything in the workshop section on Max.

**Comment by LeeBamberTGC** [comment]
@Tum1370 That is interesting, and shows the workshop items do exist correctly internally for Steam, which means we need to look at the actual creation of the subscription list and the transfer to the writable folder.

Can you go to the Steam client and confirm you are subscribed to the core workshop items:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b27228cd-427e-4647-9b4f-0d8f6a93d619)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6c6d5066-2b5b-4c28-9757-0abcd5fcbe6a)

Here is what I see in my writables folder, can you send an equiv. shot:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/37cd06fe-91b9-4a5d-9c8b-2edcdb0e3606)

Thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC I didnt even know there was a workshop section on Steam for Gameguru Max. 
Just checking it now, but i dont think i have selected anything on there, and thought everything was done through the Max workshop section ?

**Comment by Tum1370** [comment]
@LeeBamberTGC How many items are there to subscribe to on Steam, section ? I do see 8 items there

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok i subscribed to all 8 available items in that section on Steam for Workshop. I then started Max, and i see the list of items in the workshop section in Max. I updated the list.
But after relaunching Max, I am now unsubscribed for all the items in the workshop that i just subscribed in steam to.

**Comment by Tum1370** [comment]
@LeeBamberTGC After rechecking this, I subscribed to all 8 of the available workshop items appearing in the steam workshop on the steam platform.
I then updated them all again, which seem to work.
Then after restarting Max, i then went back to the workshop section on Max, And the only item from the workshop that was showing up was "Lees Space Fleet"
All the items from Necrym were missing now.
And when i go back to the Steam platform and check what items am subscribed to, I am only subscribed to "Lees Space Fleet".
All the Necrym core files are unsubscribed.

These were unsubscribed by themselves. I did not unsubscribe them.

Is this possibly something to do with the Steam Syncing ? As i see Steam sync before launching Max ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 That is a good clue, seems MAX when launching obeys the instruction to provide the subscribed list and provides the assets, but when you updated the list by clicking the update button, it unsubscribed you (which it is supposed to do), but does not resubscribe you, which I think is the issue you are seeing.  For now you can subscribe via Steam client and allow MAX to update in the background over 10-20 minutes, no need to click the update button for now. I will add some debug code to see what is happening when this button is pressed, and hopefully when we run a new EXP build we can see what your system is doing different to mine.  We have confimed you have the file "WorkshopTrustedItems.ini" in the right place and nowhere else, so it might be related to that. I will post here when I have added some debug logging.

**Comment by LeeBamberTGC** [comment]
@Tum1370 I have uploaded a new EXP build with some extra debug log info., Can you run MAX as you have it now (i..e no workshop items listed), and then send me the LOG file that gets produced up to when you are on the Workshop Tab in the HUB, the file is here: "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log".  Thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just done this for you. I have added screenshots of Max workshop before and after update button pressed, and a screenshot of my Steam Workshop after i closed Max.

Not sure whether you changed anything but it didnt unsubscribe this time ?

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/1f236422-2da9-4b8f-90e0-beeb096adb38)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/3ba09674-ca66-47a1-904e-0bc4b8e7d893)
![3](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/4b46c6d7-f2e8-4cd3-aefa-bee1ab13f5ba)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/14284527/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@Tum1370 If you find time, can you also send me your "Guru-MapEditor.log" file once you are running and on the workshop stab screen, I would like to compare with my own log to make sure the same things are running in the right order, might explain your earlier issues.

**Comment by Tum1370** [comment]
@LeeBamberTGC ok, but what is the workshop stab screen ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 Workshop Tab Screen:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8c0f1619-e465-4e67-b36c-78b47c3cd870)

**Comment by Tum1370** [comment]
@LeeBamberTGC OK this is what i did here.
I loads Max, Then went to Workshop screen.
This is the screenshot, and the log of that.

I did not press Update.

I think you must of changed something already, as this page did not use to show that list for me.

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/be40ee1b-5d16-4e35-8123-e8633ff4ac01)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/14284790/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Your LOG file matches what I would expect, so at least we are running again :)  Now we have log info, if it happens again we will be in a better position to find any issues with the system. Will close this for now, but feel free to reopen if it happens a second time.
