### ISSUE TITLE
Save game-Now has a saved game in every project.

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#5250]
Good morning folk.
I was testing a game to see if the save mode worked. I now have this load screen in every project Complete with the save.
Tried deleting the button. Verified files, Deleted Temp files and rebooted But I can't get rid of the Save. Also tried resetting the loading screen but it still comes up the same. Cheers 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/38034903/3d5e0e90-0b8e-40b3-98f5-46d8df1d1fb2)

**Comment by MartinCranshaw** [comment]
Hi Lee, a quick video of what I've tried.
You can add to that running %temp% and rebooting.
I think it began after I added a quick save marker? Deleted them.
I have this savegame in every project. If I run any of them I can load that
level from the menu.
Cheers.

 Desktop 2024.02.12 - 15.46.28.01.mp4
<https://drive.google.com/file/d/1Eo8XBq-yf7zwEoVHJTnQQ2DlJZnFB42k/view?usp=drive_web>

*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by MartinCranshaw** [comment]
Hi, again
Just tried a new project. Exactly the same with the save game and load game
screen.
Steam updates automatically so I will have the latest exp build.
It's got me baffled.
Cheers
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by LeeBamberTGC** [comment]
Find attached some fresh project template files, try overwriting these in your Steam folder at this location:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/52a6bc4e-5928-434b-a7b0-f449bcaad6f6)

And see if it was these project files that became corrupt:
[ScreenEditor.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14241472/ScreenEditor.zip)

**Comment by MartinCranshaw** [comment]
[image: image.png]
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by MartinCranshaw** [comment]
Good Morning Lee,
I've tried replacing the Template files as suggested.
Sadly it hasn't worked. I still have the Save game.
Thanks
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw Can you try renaming this file "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX" (as a backup) and allowing a fresh writable folder to be created? This will check if any old rogue project files are interfering with the creation of a new project and fresh save game screen.

**Comment by MartinCranshaw** [comment]
Hi Lee. No, that didn't work. Cleared all my levels but they should be
restorable.
I also tried restoring the save and load but still no joy. cheers
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw I guess the time is right to check out one of your projects :)  Can you email your entire zipped up "\Max\Files\projectbank" folder to lee@thegamecreators.com

**Comment by MartinCranshaw** [comment]
Hi, I sent the files (Link). Any luck. Thanks Martin.

**Comment by LeeBamberTGC** [comment]
@MartinCranshaw Thanks for the files, always nice to reproduce quickly :)  The issue was the folder "savegames" which influenced the screen as it loaded in. I deleted this folder and then relaunched MAX and all your SAVE GAME screens are back to normal:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8ebeb244-0d20-491e-8ecf-924d5f1388cc)

I have fixed this in the next EXP build so that this folder is ignored when in Storyboard mode.

**Comment by MartinCranshaw** [comment]
Thanks Lee. I found the Save Game Files deleted them and the problem is solved.
