### ISSUE TITLE
Marketplace Object Download Fails To Work

### ISSUE THREAD

**Issue by Technodweeb** [TheGameCreators/GameGuruRepo#5253]
I am unable to import my newest purchases through your store using GameGuru Max Import Function.
I've been getting the error shown in the attached image since last week:

![GGmaxTCG Error](https://github.com/TheGameCreators/GameGuruRepo/assets/61712610/32742a6a-17b2-460c-b997-e58c171bb124)

It just says : Something Went Wrong.. and doesn't list anything else, including the folders that these are usually imported to.

I was signed into the store with my browser. I also tried signing out of the store to let GGMax open the browser for sign in to the store, but it never gets that far.. it just says Something went wrong.

I will also reported this to Store support.

Thanks!

Loretta

**Comment by extremestrategy** [comment]
Same problem here, I'm signed into Steam on the browser and local, signed into TGC and TGC store, TGC Store and Steam accounts are linked, and can't download my purchases.

**Comment by davetgc** [comment]
The store is run by a 3rd party. I'll get him to investigate first.

**Comment by jason-pnpd** [comment]
@LeeBamberTGC I have investigated from the store side of things and there does not appear to be an issue on our side, can you investigate on your side and try to work out why the error is happening. Possibly missing security keys on the build? I have tested an older build of GameGuru MAX and it works in that build.

**Comment by LeeBamberTGC** [comment]
@jason-pnpd I have sent you an email on this one. I have fixed one of the issues with this breaking in the latest EXP builds, but chasing down a follow-on issue I would like to solve before the next build.

**Comment by extremestrategy** [comment]
Seems to be working for me now, thank you Lee.

**Comment by Technodweeb** [comment]
It is working now.. someone fixed it.. thanks for checking!

------ Original Message ------
From: "davetgc" ***@***.***>
To: "TheGameCreators/GameGuruRepo" ***@***.***>
Cc: "LorettaM" ***@***.***>; "Author" 
***@***.***>
Sent: 2/20/2024 6:27:25 AM
Subject: Re: [TheGameCreators/GameGuruRepo] Issues with TCG Store Import 
(Issue #5253)
