### ISSUE TITLE
Script Weapon Bug 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5257]
https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/645a4649-ea5d-4ae2-b481-5a9a0f7cf3ff

After the recent update, it does not collect weapons

**Comment by SampeyFS** [comment]
For Accuracy it doesn't go on Accurate the other one works because it was set to Accurate it didn't go

**Comment by Necrym59** [comment]
This is fixed
