### ISSUE TITLE
I dont understand

### ISSUE THREAD

**Issue by ArmedAndHammered3** [TheGameCreators/GameGuruRepo#5258]
So i have reinsatlled Max and Steam so many times and had issues each time with wonky things appearing in Max that i did not place there in a folder.

These photos are some questionable items that are either messed up or shouldnt be there. 
This is a clean install.

![GameGuru MAX - 2_13_2024 10_37_37 AM (1)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/e6c3c1aa-09f4-4a45-833c-fbbc97e589c2)
![GameGuru MAX - 2_13_2024 10_37_37 AM (2)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/1b154eef-70e6-4460-91a2-40ec562b765c)
![GameGuru MAX - 2_13_2024 10_37_37 AM (3)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/3c5b7c37-0b73-4c1b-ae6b-257fa91a6d84)
![GameGuru MAX - 2_13_2024 10_37_37 AM (4)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/a750d8f8-42c6-4ca5-b840-71b015768fdd)
![GameGuru MAX - 2_13_2024 10_37_37 AM (5)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/e5fca98f-2d40-475e-8282-6b3aed57514e)
![GameGuru MAX - 2_13_2024 10_37_37 AM (6)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/59a8f480-df51-40e6-bde3-6ad3e6bd6f44)
![GameGuru MAX - 2_13_2024 10_37_37 AM (7)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/f28835bb-bc54-441e-ab36-3f00b0193e8f)
![GameGuru MAX - 2_13_2024 10_37_37 AM (8)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/305046e9-243b-40ca-93bf-c0924180af1b)
![GameGuru MAX - 2_13_2024 10_37_37 AM (9)](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/51340794-f505-4589-9fab-a6a069a3581e)

Is there a way to stop these from showing up in the x86 Max files cos its annoying and making my experience troublesome

**Comment by MonkeyFrogStudio** [comment]
There is a folder where custom stuff goes that's not part of the standard MAX install. These can be found at:

Documents > GameGuruApps > GameGuruMAX> Files > entitybank

Custom stuff normally gets stored there so that fresh installs and updates don't accidentally delete them. So, you might want to check that particular entitybank folder to see if the 'wonky stuff' is in there.

**Comment by ArmedAndHammered3** [comment]
Thank you Monkey Frog but that folder is completely empty as i always delete all traces of Max including documents and all steam fies including common when i reinstall Max. These files are from past uses and should not keep showing up if the documents folder was created on a brand new ssd. All documents of Max are blank so i cant figure out why i have these items.

**Comment by synchromesh62** [comment]
You have **" View All "** selected 
It will show every asset Max has in that list and there are around 1000 in those packs.

**Comment by ArmedAndHammered3** [comment]
EVERY ASSET IN THIS POST WAS STOCK ACCORDING TO STEAM AND MAX. 
.

**Comment by earthling45** [comment]
Steam cloud?

**Comment by Ghost-l0l** [comment]
@ArmedAndHammered3 IMO there's nothing really wrong here and you're panicking needlessly  ;p 
I'll try to explain:
 On the screenshots you are showing in the first post you can see only Max's stock media. They are not 'some questionable items' - just all stock assets that come with Max.  What You see on these screenshots is category called 'All' - and as the name suggests, it's showing all assets you have in your entitybank, in alphabetical order. 
 (These "Angry Eggs" come from easter pack, check out which DLCs you have installed on steam. )
  This 'All' category just lets you see all media combined from all folders at once. All these items you showing come with Max and there's nothing unusual about it. 
  Furthermore - that's how Max's media browser works in general, when you click on folder, it shows you assets in that folder AND all assets in all folders under that first folder's hierarchy.
 It's a bit different than normal folder browsing in windows. Can be a bit confusing for sure. 
 
 As for the doubled Hangar you mentioned, it's just a typo that was probably missed and both files are included in stock media. 
 
 Same with doubled FPE for 'red short industrial stairs'  - if you look closely, there's one letter missing in the first copy of that FPE :) 
 Just another typo. So Max see these 2 as different files, which is also completely normal. It's a human mistake, not Max's foult :) 
 But c'mon Max has hundreds of files in it's entitybank, few typos here and there ain't that bad ;p

**Comment by extremestrategy** [comment]
Yep, everything in the images is either Stock or DLC content.

**Comment by ArmedAndHammered3** [comment]
@extremestrategy @MonkeyFrogStudio @synchromesh62 @Ghost-l0l 
Thank You for clarifying the assets are all stock media and nothing was wrong.

**Comment by ArmedAndHammered3** [comment]
Nothing strange here at all. My mistake
![@Extreme Strategy - Discord 2_15_2024 12_29_41 PM](https://github.com/TheGameCreators/GameGuruRepo/assets/155216731/56fc680a-9fe7-4dda-9559-c8659490aeab)
