### ISSUE TITLE
GG Max - Bug - Looting Ammo - Repeats the pick up ammo message after the first time its picked up

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5259]
When looting ammo from a enemy, i find that after i have looted the ammo, and then left the body, If i go back to the body, it gives me the message of looting ammo again, BUT it does not loot any more ammo.
This message shows every time then i go near the body.

Is this just happening to me or are others seeing this ?

**Comment by Kitakazi** [comment]
Yea this happens to me as well.

**Comment by Tum1370** [comment]
@LeeBamberTGC @Kitakazi 

I know this issue has not even been marked as a bug yet, But i can now confirm this is working as it should do now.
Lee, the fix for the other bug with the old collection list and  autogen assault rifle was causing this bug. After testing the level after the other fix, this is working correctly.

For anyone else who has this bug, Try looking at the fix for my other issue, that fixed this for me as well.

This was the other fix.
https://github.com/TheGameCreators/GameGuruRepo/issues/5261

Ill close this issue now, as its not a bug.
