### ISSUE TITLE
GG Max - Exp - BUG -  How do we set the characters to drop ammo now ? I cannot see it anywhere ?

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5261]
Hi, As the title says, How do we get the characters to drop ammo now and set the amount that might drop etc ?
Has it been moved ?
Didnt it use to be on the Character Attack behaviour ?

Screenshot 1 is from my demo Horseshoe Bend, and you can see in the Character behaviour there is an option to Drop ammo and how much ?
Screenshot 2 is on latest build, and Character Attack is missing the option to Drop Ammo and select how much to drop ?

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/c9043e38-0b58-40a0-bc65-e16fdef8a49b)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/21491363-8516-47f8-9018-95af67df5dd2)

**Comment by Necrym59** [comment]
Tick the 'Player can take Loot checkbox', and add in what is wanted to be dropped.

**Comment by Tum1370** [comment]
I don’t see how that can work with ammo ?
There is no ammo in the drop list. 
And how would you set how much ammo dropped ?

Why are these 2 screenshots got different settings ?

**Comment by Necrym59** [comment]
I would say its going through some changes at the moment, but ammow ould probably be on the dropdowns later

**Comment by Tum1370** [comment]
So do you mean this at the moment ?

I have to place the ammo I want, in the map, set the amount to what I want, then set it as a collectable. 
Like we do with guns now. 

Then I can add it as loot ? And add the drop chance.

**Comment by Necrym59** [comment]
Well not really, but for now just set the "player can take weapon" and set its taken weapon ammo value for pickup

**Comment by Tum1370** [comment]
Ok, but that’s the problem here. 
there’s no option now for taking weapon and setting ammo pickup. 

I do have the gun placed in the level.

**Comment by Tum1370** [comment]
Just checked this again, And i noticed that some weapons are available and get a autogen on the collectables list.
The gun i was trying to use was the Magnum PIstol, And for some reason, Even though the enemy are selected to use this, Max does not autogen this weapon in the collectable list.
Therefore making it impossible to set the option to loot weapon and ammo.

This maybe a bug ?

**Comment by Tum1370** [comment]
@LeeBamberTGC @Necrym59 
Ok i think i have figure this problem out.
There seems to be a bug with some guns not auto generating on the collectables list for then allowing the Character Attack Behaviour to let you set Player Can Loot Gun, and the option for the ammo.

If you go to the Character Select behaviour, And go through the list of guns, youll see that some guns dont give that option to Pick Up the gun and ammo.

My level the characters only use Magnum Pistols, Yet in the collections list it auto generates an Assault Rifle .

Ill change this titles to a bug, because this is a bug.

**Comment by Tum1370** [comment]
@LeeBamberTGC I think this link should work for you to download it.
There are maps missing and maybe character creator characters will be missing.
And maybe some scripts are missing to.
This is an older project i was testing this on.

I have added to the zip, 1 map that has the assault rifle in collections list yet it is not in the level.
There are patrol Rifles in the level,  and the editor autogen this.
The characters all use Magnum Pistol, I actually added one of these to the level so they would drop the pistol.
The system does not autogen a magnum pistol for some reason.

https://www.icloud.com/iclouddrive/05e2QRIKsgNg_YJVxQiuHIjlw#For_Lee


PS:  I tried a new blank level, i added a normal character with a Magnum, Placed a magnum on the floor, And set the character to drop the weapon and ammo. This worked fine. 
This bug maybe something to do with this been an older level ??

**Comment by LeeBamberTGC** [comment]
@Tum1370 Yes there is a trick to this, something to improve in the future. Here is the sequence:
1. Select Detailed Object List: 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0dc1c090-725f-4992-8d54-f0fe26534d57)
2. Expand the assault rifle:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2f4d639c-b21d-4ef1-85e5-c882d71afa87)
3. Click the instance of the rifle in the list:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/1cc274d9-cb45-42e8-84c6-ec24b2750b0b)
4. Move the cursor into the level editor area:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0bb49bc2-e49c-4148-a180-3dd631572c50)
5. Press the DELETE key on your keyboard and the instance of the object will be deleted from the level:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/01aa827d-87a2-4b2b-8894-d8a10c702ee9)
6. Now save the level and the rifle will have been removed from the level. If you do not also remove it from the collection list, it will autogen the next time you load the level, so it is best to quit MAX, then delete the collection items files then relaunch and load the level, the rifle will stay deleted and start using the newer system to track collection items in the level.

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok thanks, didnt realise you could delete it by just moving the cursor in to the level editor, I thought i had to select that item in the level editor, and it was not there.

I have now got that Assault rifle deleted, I saved the level. Exited Max. Deleted the 2 collection files. Then reloaded Max.
I now see that the Magnum Pistol allows Character Attack behaviour to drop the weapon and set the ammo.

But there is still something strange in the Level Objects list.
That Assault Rifle still remains there, Even though there is no copies of it in the level anymore.
You can see on the screenshot that its in the list, but no copies are in the level. 
This is after saving level and exiting Max etc.

![Untitled](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/4308d777-8ce8-4585-b1ab-db5a5666e415)

Maybe just bugged due to older level ??

**Comment by LeeBamberTGC** [comment]
@Tum1370 That is just a querk of the level holding a reference to the parent in case the collection list update (from another level) might need the object after all, but the next time you save the level and the rifle is definately not there, it has a cleanup process to remove empty parent objects that have no reference to instances of itself.  It will disappear immediately after saving in this way:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/152b4d0c-3d08-42eb-9398-c21b70a2f3f9)

**Comment by Tum1370** [comment]
@LeeBamberTGC Ok thanks for the explanation.
Ye i just saved it a couple more times and it disappeared now from the item list.
Thanks for sorting this out, i will close this issue now as its been fixed.
Thanks again
