### ISSUE TITLE
GGM BUG - Freeze behavior stopped working.

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5262]
Recently I worked with Necrym to enhance this behavior for a project I'm working on and we had it working fine. That was about two weeks ago. The other day I went to continue my work and noticed that it stopped working altogether. This video will demonstrate using a brand new project & level which will be sent via email for testing.

https://youtu.be/eDKeS6OfwOs

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive V4 of the script works fine, bnt Necryms script V9 breaks as you see.  My first guess was the right one when I added these lines:

		if freeze[e].FreezeStyle == nil then
		Prompt("freeze[e].FreezeStyle")
		end

Cleaned up the script and removed the lines that really messed things up:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0eaea078-174e-4d1f-8ab8-ef72d5f845f5)

It appears the param FreezeStyle is NIL so no modes are going to fire off.  I have made a fix and called it V10 and will be in the next EXP build :)

**Comment by Blood-Moon-Interactive** [comment]
Looks like an American football play. Closest I can tell it looks like a running play where the quarterback intends to go for a first down on third and short.

**Comment by Necrym59** [comment]
its fixed
