### ISSUE TITLE
Script Resource Bugs

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5263]
The quantity of the Resources script does not work as you can see from the picture it picks up 1 out of 3 that I had set up

![Screenshot 2024-02-16 102336](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/3a8ee08d-61ee-4888-aa2b-19d8badb907c)
![Screenshot 2024-02-16 102423](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/bf956117-e758-4b53-8f62-0e991b999d45)

**Comment by Necrym59** [comment]
Fixed (please update your workshop files and/or verify) the Max installation behaviors will be updated in due course.

**Comment by SampeyFS** [comment]
thank you
