### ISSUE TITLE
Terrain being Corrupted in Standalones by the Autoflatten Feature

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5264]
Inside of standalone games, the terrain is getting glitched and corrupted, it's shooting straight down or straight up.

![20240216144759_1](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/172c830d-9e32-4fba-ac3f-bfe1b23f88d5)
![20240216144803_1](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/868a9ab3-2cbf-4e6c-ae68-cec5e9800562)
![20240216211522_1](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/6ea468cd-171a-4be6-8d51-3fd5f04e5080)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/eb0e7273-089d-48af-b93b-b8c0265b49a3)

**Comment by extremestrategy** [comment]
Right, I remember that, now the editor terrain works, but standalone terrain not so much, and to make it worse, it's very random, it'll hit different maps, with different sizes, and then be gone after restarting the game.

**Comment by extremestrategy** [comment]
Will do.

**Comment by LeeBamberTGC** [comment]
@extremestrategy Thanks for your email, the video link you sent showed as not available for me to view. If you could zip up the necessary materials so I can load and reproduce the terrain glitch issue, that would be best, thanks!

**Comment by extremestrategy** [comment]
@LeeBamberTGC Your welcome, I sent you two follow up emails, one with a Google Drive link for the video, and one with a question, because you mention wanting the FPM, and needed materials, firstly I use a lot of GGC assets, and sorting out which ones are use would be a pain, also you wanted to replicate the bug in GGM, which can't be done bcause the glitch only happens in an exported standalone that is separate from max, and there is no way to get it to happen 100% of the time, it's a bit random with where and how it effects the terrain.

**Comment by extremestrategy** [comment]
Hey Lee, I sent you the email the other day, I wound up giving you everything you need so the gamecore, assets, fpms, and project folder, just so you can recreate the whole thing if needed, hopefully you can figure out where in the export process the terrain is getting corrupted.

**Comment by LeeBamberTGC** [comment]
@extremestrategy I got all the files and was able to make a standalone from the project and level files. As you suggested, the bug is likely intermittent as I could not get the terrain to warp up and down, and could not spot any issues in the building flattening code.  As a way to narrow down the culpret, can you switch off your auto flattening mode in settings:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/20f3a05f-76d1-4267-9c5e-bc29322b0680)

Once done, this should remove the auto flatten effect under buildings and other required large objects, and then save that level and save a new standalone executable and see if the problem re-occurres. If not, then we can narrow it down to the code that flattens the floor based on the object requesting it.

**Comment by extremestrategy** [comment]
@LeeBamberTGC turning off the autoflatten in the object settings worked, the terrain is no longer causing the glitching, as such I am changing the name of the bug to match the issue, so now we know that auto flatten is bugging out terrain in exported standalones.

**Comment by LeeBamberTGC** [comment]
@extremestrategy I have added some extra debug info for the next EXP build that will dump the auto flatten real data to the LOG file when you enter the in-game menu of a standalone game level.  This is phase 1 of comparing what your system shows vs what my standalone shows built from the same level.  When you get the next EXP build dated today, make a standalone, edit the SETUP.INI file so "producelogfiles=2" then save that, run the game and enter the assassination level, then do that until you see the issue, then press ESCAPE to enter the in-game menu, and then copy and attach your LOG file so I can compare with mine.
