### ISSUE TITLE
Zombie headshot deaths not triggering behavior changes

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5265]
Inside of GameGuru Max there are scripts that trigger changes, or logic when an NPC dies, these are Radar, Winkill, etc, however if you are fighting a zombie a headshot it, killing the zombie, the zombie will not trigger any change, this effects all zombies inside of Max, the only way to handle it, is to shoot the zombie again post mortem (killing them for a third time?) and that will trigger updates, changes, etc.

https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/78ee8d63-2b11-46a8-9bc5-0247c8df74a6

**Comment by LeeBamberTGC** [comment]
@extremestrategy I created a room with a door, cloner object, zombie and soldier, and then logic linked the characters to the other things. No matter if headshot or not, none of the deaths triggered the door to open or the cloning to happen. Can you send me a sample stock level with a step by step, thanks:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a282975f-ab8a-41e9-b09a-915ac1262100)

P.S. Level took me 15 minutes to create and test, that's 15 minutes I was not fixing bugs ;)  Repro is literally most of the time I spend these days, finding the little buggers takes forever, fixing them minutes!

**Comment by extremestrategy** [comment]
Hey Lee, here's the Google Drive for the zombies not dying, I have a video discussing it, as well as the FPM, logs, etc, when I mention the chomper not being a problem, he seems to be the only one that doesn't give me problems, but people have mentioned in Assassins Unleashed that he was acting up as well, just an FYI, sorry for the misspeaks and tired voice in the video. [zombie headshots.zip](https://drive.google.com/file/d/1Ay20S3JivLueiLVG-sbY5ab-Kfmq1533/view?usp=sharing)

**Comment by LeeBamberTGC** [comment]
@extremestrategy Fixed for the next EXP build so that scripts cannot change character health if they are processing the ragdoll phase:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/37bb7f33-17f8-4ada-95ad-23c0928579a9)

**Comment by extremestrategy** [comment]
Thank you.
