### ISSUE TITLE
GGMAX - ASSET LIBRARY BUG - Updating a thumbnail image in the library adds that object's name to the search bar leaving that folder. Why?

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5269]
This is INCREDIBLY annoying as an artist when finalize a pack of dozens and dozens of assets, and it didn't used to do this.

For some reason now, when you update the thumbnail of an image in the asset library, after confirming your change and taking the new thumbnail image, it adds the name of that object to the search bar, which takes you OUT of the folder you were in!

This means if an artist wants to update all of the images in their pack before final submission, they now have to go to their pack's folder, click an item, take their final thumbnail image, then navigate BACK to that same folder, go to the next item and repeat over and over again for possibly over a hundred or more assets.

I know it sounds nitpicky, but this additional step is unnecessary and add more time to the process for pack artists. Before it was much faster. You'd click on an asset in "Folder A" to update it's thumbnail, it would do it, STAY in "Folder A", then you could simply move onto the next asset, and the next and so on and you were done with 100+ thumbnail images in just a few minutes. Now it leaves that folder entirely for every single thumbnail image updated, and you have go back into that folder manually, then scroll back down to where you left off update the next one image, and so on.

Please fix. :)

**Also, I'd like to resurface this request while on the subject of optimizing artist-flow in the asset library:**
https://github.com/TheGameCreators/GameGuruRepo/issues/4448

**Comment by davetgc** [comment]
I've found this too, and is is annoying..

**Comment by LeeBamberTGC** [comment]
@Kraven3D Fixed for next EXP build.

**Comment by Kraven3D** [comment]
@LeeBamberTGC , running the 04.11 build now. Confirmed this is now fixed. Thanks! Closing issue :)
