### ISSUE TITLE
GGMAX - Enhancement - Add a "weapon max carry limit" value to the player start marker to restrict how many guns the player can carry at once

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5270]
This way, the player can't run around with a dozen weapons in his back pocket like the Doom Marine.

Setting this value to "2" for example, would mean the player could only pick up a maximum of two weapons, before having to replace one.

**I will also link to this older request here since they relatively go hand in hand, which would be for the option to replace a weapon when picking up a new one to drop the old one on the ground that can be picked up later:**
https://github.com/TheGameCreators/GameGuruRepo/issues/4224

**Comment by Necrym59** [comment]
Already in
Use the preferred weapon slots setting "Slot Not Used" to limit the amount of weapons can be carried

**Comment by Kraven3D** [comment]
> Already in Use the preferred weapon slots setting "Slot Not Used" to limit the amount of weapons can be carried

Hmm, is this option only available in the experimental builds at the moment? I'm not seeing a "Slot Not Used" option under those tabs in Steam V12.18.23. 

Either way, thank you for adding it :)

**Comment by Necrym59** [comment]
Yes is in the experimental builds only at present

**Comment by Necrym59** [comment]
Issue is answered and closed
