### ISSUE TITLE
Dynamite problem  (My Problem)

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5273]
Now I'll explain my problem I made the mine I place the dynamite on the ground it doesn't show up on the ground then (( SHOOT FROM ANOTHER AREA THAT POSITIONED IT)) what can it be thanks for the help

**Comment by Necrym59** [comment]
?

**Comment by SampeyFS** [comment]
yes I place it but it falls somewhere else not in front of me do you know why? it seems to be a problem with the script because I did it on an empty map it also does it there that it doesn't fall near where you are
 
Add your comment here...
 

Add your comment here...

**Comment by SampeyFS** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/9f87960c-0961-456c-b8b7-79ff1ead4622

See for yourself you don't know where it falls

**Comment by SampeyFS** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/5c8f9787-67c9-4678-85aa-b34852f1d320

See for yourself you don't know where it falls

**Comment by Necrym59** [comment]
[dynamite.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14320367/dynamite.zip)
try that replacement ane let me know if its ok

**Comment by SampeyFS** [comment]
No it does the same thing you don't know where it falls you don't know where it shoots

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/769409b8-74c2-44e3-a9bd-eb654a6070d2)
Look where I am hahahah

**Comment by SampeyFS** [comment]
I see what's going on, it doesn't always fall close to you, it also falls away from you, that's why I didn't see it.

**Comment by Necrym59** [comment]
Works fine here..
https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/2e4baa5d-add8-4564-be50-a51fc513d16d

**Comment by SampeyFS** [comment]
see how come I don't?

**Comment by SampeyFS** [comment]
I don't understand why it doesn't pick up for me like it does for you in the empty map it works is an incredible thing this

**Comment by Blood-Moon-Interactive** [comment]
This appears to be a duplicate post of #5256. If that's right please close one of them to make sure there is no confusion.

**Comment by SampeyFS** [comment]
No that's another thing here the problem is with the script you put it on the ground but you can't see where it shoots but we've done several tests me and @Necrym59 but I don't understand even in my empty maps it does it to me now I don't understand what this annoying problem is

**Comment by Necrym59** [comment]
Well I have tested it and the behavior works as expected so have others it appears its somthing to do with your particular scenario.

**Comment by OobieDoob-Benoobie** [comment]
@SampeyFS 
You might already know this, but

This is what I would try:
1: Load up GameGuru MAX and once loaded, at the screen where you choose a game to work on, click the "_Workshop_" tab at the top of the list.
2: Then click "_Update workshop items_" under the list.
3: Then close GameGuru MAX and restart it.
4: Test to see if it works.

If not:
5: Close GameGuru MAX and open STEAM.
6: Find "**_GameGuru MAX_**" in the list on the left, and right click it. Then click "_Properties_" and Then "_Installed Files_".
7: Then on the next screen click on "_Verify integrity of software files_" and wait for it to complete.
8: Then do steps 1 through 4 again. 

That seems to help me with this type of issue.
