### ISSUE TITLE
Demo Game "Canyon offensive" made by Ghost lol : Level logic connections corrupt

### ISSUE THREAD

**Issue by marcuswilm** [TheGameCreators/GameGuruRepo#5275]
First of all I want to congratulate Ghost lol for the beautiful landscapes shown in that game.

I noticed a few problems with that game : 

1) When the game is opened in the editor, this message briefly appears : "some behavior scripts are missing ...". 
My question : Is there a way to rapidly find those missing behaviors  (perhaps in some log files) ?

![bug_canyon_offensive_missing_behavior_scripts](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/ab8591b4-f32c-4b2d-bece-fe7382778041)

2) The limbs of the enemies bodies are completely distorted when they are dead. 
Furthermore they often appear and attack while they bodies are oriented at the opposite direction of the player.
![bug_canyon_offensive_bad_pose_dead_enemies](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/60c815cb-60cf-4845-9705-57d1bea15ec4)

3)  It is impossible to complete the game because the door near the bunker is not correctly connected to the key found in the hangar.

![bug_canyon_offensive_bad_connections_keys](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/124d64f8-6a49-4069-895f-a70912cbc192)

4) As regularly observed in games created with GG Classic and MAX, when a saved game is reloaded then some activated switches or some found assets are forgotten by the engine.
I would like to know what kind of datas are currently stored in a saved game.

**Comment by earthling45** [comment]
![Naamloos](https://github.com/TheGameCreators/GameGuruRepo/assets/35744254/ed9bcfb6-21f2-4258-b7c0-9858a3bf56a5)

The characters parts need to be looked at, don't know for sure but i think this is because some vertices are missed during weight painting.
Would that also cause the weird distortion on the bodies?

**Comment by Ghost-l0l** [comment]
All example maps, this included were created on very early builds of Max, about 2 years ago, since then scripts were edited multiple times and moved to different folders, I guess that's why you see these problems with keys, doors and switches. 
I bet you will find the same kind of problems on other example maps too.
 
 As for enemies and weird distortions - that's something new, I haven't seen that bug before, It's probably worth reporting as it's own issue. Also worth checking out if this bug is specific to this map, or just sometimes happens in general? It looks like a pretty serious bug.

**Comment by marcuswilm** [comment]
@Ghost-l0l  @earthling45 
Thank you for your comments.

Ghost lol, I understand your explanations about those problems relative to the keys and switches.
I noticed that this demo was announced on 2024-Jan-10th by GameGuru on Facebook.
I think that the developers should test in depth the demo games before using them for their GG Max promotional campaigns.
The artistic content  (landscapes, assets, pbr textures) was so good that it inspired me to explore your game to the end even if it could be a hard time fighting so many enemies.
 

About those distortions appearing on dead enemies, before I post a new report especially dedicated to that bug I'll investigate if it occurs in other games.

earling45, the distortions shown in your screen capture are affecting the textures on the avatar. It could be compared with those ones found on the sides of high hills on GG Max terrain.
The distortions appearing on dead enemies as shown in my screen capture are more problematic.

**Comment by OobieDoob-Benoobie** [comment]
I was running into those dead character distortions and some characters running backward and facing away from the player while still shooting and harming the player.
I discovered that if I have ANY logic errors in my levels, (especially the larger levels) I run into this issue.
Just linking something incorrectly (Eg. logic linking a triggered object to something not set up to actually trigger) or using invalid settings like that will cause it. Also linking more than 8 or so items to a trigger zone or switch is bad. I now avoid going past 6 and use multiple triggers instead.

**Comment by marcuswilm** [comment]
@OobieDoob-Benoobie 
@LeeBamberTGC
@Ghost-l0l
@earthling45 
 
Jay, thank you for your comment. I am impressed by your in-depth analysis of that issue relative to dead characters distortions.
Your conclusion is a particularly useful information (if it is confirmed by the developers).
There are indeed many linked assets (including characters) in the game Canyon offensive, as shown in this screen capture :   
![links and triggers](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/4c749615-60f9-4aa8-80b4-9ab18b957200)

**Comment by LeeBamberTGC** [comment]
@marcuswilm Looks like you are using an old version of this level, can you zip up the "canyon offensive.fpm" FPM and attach here so I can compare it with the latest version in MAX. This is what I see with the last posted shot:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8bb5de4e-6c66-4128-addd-fa785dbfde74)

**Comment by marcuswilm** [comment]
@LeeBamberTGC
Thank you for your fast reply.
The zipped folder (fpm + lst) is too big for its attachment on Github.
Here is the shared link on my OneDrive : [https://1drv.ms/u/s!AjokN1FU3jK1pG3Z1UZ8hmpgfDwM?e=gsetgy](url)

Properties of that "canyon offensive.fpm" file :  
![canyon_offensive_properties](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/2ed6a329-d6ef-4ea0-bed7-a0a296bbfed5)

**Comment by LeeBamberTGC** [comment]
@marcuswilm I loaded the level you sent and it looks like this:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8dc84d2a-cc0a-4154-9547-994c2397ae36)

Not like this:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2ee1b937-57b8-4460-a9bc-c5825f9f1e0e)

Do you get the same?

**Comment by marcuswilm** [comment]
@LeeBamberTGC 
@Ghost-l0l 
@earthling45 
@OobieDoob-Benoobie 

Lee, I am confused for all that turmoil resulting from a fact of which I was unaware.
I apologize to everyone I wasted their time.

After having posted my comment and having uploaded the file .fpm requested in your comment, I made a long ride (more than 3 hours) with my mountain bike starting from the Yser Tower https://en.wikipedia.org/wiki/Battle_of_the_Yser
It is often during my daily rides on quiet roads that I find the solution to my problems.

Far from my computer I thought : "is it possible that a second version of that game "Canyon offensive" exists in my GG Max folders ?".

Discovering your new message I inspected the GG Max folder where my personal projects are stored and I found there another version of "Canyon offensive".

Therefore I come to the conclusion that the version stored in my personal folder is the one that appears in my GG Max Hub as shown in this screen capture :  
![GG max hub](https://github.com/TheGameCreators/GameGuruRepo/assets/94678034/232199a9-bd33-4dbb-b157-51aad0a1eff7)

In that folder with my personal GG Max projects, I also found a folder "Canyon offensive" in the "projectbank" dated 2023-June-14th.
It confirms that the version of "Canyon offensive" I played with is an old one as you correctly mentioned it in your first reply.

I see that many other game demos are stored in my personal folder. 

Please consider this report as closed. Thank you for your assistance.

**Comment by LeeBamberTGC** [comment]
@marcuswilm We will be introducing a better project system this year which should avoid these types of things, but thanks for your patience and providing the info to resolve this one :)

**Comment by marcuswilm** [comment]
@LeeBamberTGC Thank you for sharing that information relative to a better project system.
Thank you also for the kind words to me. Have a nice day.   :)
