### ISSUE TITLE
GGMAX - BUG - Duplicating multiple objects using copy/paste then undoing their duplication removes each duplicated object individually

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5276]
If you use the multi-selection tool to grab several assets at a time then copy and paste that group of assets, then undo that paste, the undo action removes just one of those duplicated assets at a time instead of undoing the entire duplication collectively.

Please fix. :)

**Comment by LeeBamberTGC** [comment]
@Kraven3D Fixed for the next EXP build.

**Comment by Kraven3D** [comment]
@LeeBamberTGC , thanks :) I don't run EXP builds. Would you prefer I wait until all of these fixes for my requests are added into the next official build to test them for myself and confirm, or would you rather pass them along to someone who uses the EXP builds so these can be closed sooner?

**Comment by LeeBamberTGC** [comment]
@Kraven3D Its fine to keep the issue unclosed, we usually go through them periodically and close any long-standing issues marked as fixed and uncontested :)

**Comment by Kraven3D** [comment]
@LeeBamberTGC , just tested on the 04.11 Steam build. Fix confirmed. Closing, thanks!
