### ISSUE TITLE
Added NPC Controll script function

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5277]
I was wondering if you can add the npc control sound radius (e.g. the bear) put the sound radius yes no you can hear it all over the map and it never stops? thank you very much

**Comment by Necrym59** [comment]
You have to be more specific!
Which sound slot is it thats causing the problem?
Are you using Mono sound file?
Send a screen shot of your sound settings!
Highlight in the screen shot the one causing the problem?

**Comment by SampeyFS** [comment]
I used these 3 but you can hear the sound of this bear very far away 
![Screenshot 2024-02-18 202813](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/ce2f71ba-9056-4c05-b2bb-31a4354b03be)
sound and mono

**Comment by Necrym59** [comment]
Yes but is it a "Mono" sound file, only mono is in 3d

**Comment by SampeyFS** [comment]
[Black Bear Single Roar 1 - QuickSounds.com.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14324153/Black.Bear.Single.Roar.1.-.QuickSounds.com.zip)

**Comment by SampeyFS** [comment]
[Bear.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14324175/Bear.zip)

**Comment by Necrym59** [comment]
[Black Bear-Mono_Sounds.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14324250/Black.Bear-Mono_Sounds.zip)
Try these

**Comment by Necrym59** [comment]
[Black Bear Mono_Sounds.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14324256/Black.Bear.Mono_Sounds.zip)
Try these ones

**Comment by SampeyFS** [comment]
thank you very much
