### ISSUE TITLE
GameGuru Max Retail Edition Stand and Speak More Error

### ISSUE THREAD

**Issue by ProhibitedTV** [TheGameCreators/GameGuruRepo#5278]
The stand and speak more behavior is broken in retail GameGuru Max. I have recorded the error in OBS. Forgive the choppy preview framerate. That only happens when OBS and GameGuru is in preview mode. I added four speaks to the character. The speech files are .mp3 files generated from ElevenLabs AI.

https://youtu.be/pz0be2uAmBQ

**Comment by OobieDoob-Benoobie** [comment]
I had previously posted this issue an instead of fixing it, after further explanation as per their request, they just deleted my post.
probably just a misunderstanding.
Here's the old video: (mine pops up an error message)  
[https://youtu.be/rX7IwRnrAxY](url)
https://youtu.be/rX7IwRnrAxY

**Comment by davetgc** [comment]
@OobieDoob-Benoobie - I'm sure this is just confusion, we'll look into it.

**Comment by LeeBamberTGC** [comment]
@ProhibitedTV In the latext EXP build we updated this script on the 20th Feb to fix the left over SendMessage issue, hope this works :)
