### ISSUE TITLE
Quest Giver Bug

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5279]
![Screenshot 2024-02-19 161537](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/e842871d-e097-48ae-a0d6-d34f2867faf0)
![Screenshot 2024-02-19 161558](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/afea8050-a65d-4621-93a2-36d5bd466ee0)

**Comment by SampeyFS** [comment]
as you see from the picture it makes me end the mission from where the mission starts was on the left the feeder instead makes it end where the mission starts

**Comment by SampeyFS** [comment]
![Screenshot 2024-02-19 162137](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/bf62d454-c01f-42fb-b372-2e9719e267a4)

**Comment by Necrym59** [comment]
That makes no sense
read the quest guide carefully

**Comment by SampeyFS** [comment]
it's not the first time I put them on but are you watching what it does?
