### ISSUE TITLE
Feature Request: choose different path for Save Standalone

### ISSUE THREAD

**Issue by tomik18** [TheGameCreators/GameGuruRepo#528]
it would be good if you could change it or choose another path to save the standalone. Some users (like me) have a C: SSD 128GB drive and there is not enough space to save a larger project, if I have multiple programs installed in Program Files.

**Comment by Teabone3** [comment]
A dialogue box similar to FPSC would be nice, allowing us to add more settings for the stanalone for example some of the info thats in the setup ini like dividetexture size, aspect ratio, hiding of terrain or water, etc. could hide it all under an advanced tab or a sectioned off part so it doesnt get in the way of the "simple" user base thats been targeted. 

But of course a save path would be ultimately perfect addition to this process.
