### ISSUE TITLE
RX 6600 Bug 

### ISSUE THREAD

**Issue by Labsdj** [TheGameCreators/GameGuruRepo#5281]
When i try open the GameGuru Max normal version build i got error describe in this link i post https://imgur.com/wiwqVwz  a error "Failed to create the graphics device ERROR 80004005" impossible to run the gameguru max Please fix this bug not fixed with experimental test update need to be fixed.

**Comment by davetgc** [comment]
Thanks for the reminder, but closed in favour of your other post: #5254
