### ISSUE TITLE
Max Crashing on Test Launch

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5282]
When working on my maps, I have Max crashing when I try and test my maps, it doesn't matter whether they are large, or if they only have a few objects, if I make a few modifications, save, and the launch the map, Max crashes upon launching.

**Comment by davetgc** [comment]
Is this happening on all maps? E.g. The sample maps? Or just yours?

**Comment by SampeyFS** [comment]
yes it does me too and I'm getting tired now of these bugs

**Comment by extremestrategy** [comment]
@davetgc  This only happens inside of exported standalones outside of Max, and this seems to effect only my maps, or the custom maps of others.

**Comment by extremestrategy** [comment]
This only happens on custom maps inside of Max, the demo ones seem to be fine.

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/f29ec539-66df-41e8-9adb-82555bb4761e)

Crash of Game Guru Max Windows 11 a saved them look how many times it crashed

**Comment by extremestrategy** [comment]
After a few updates it seems to have fixed itself.
