### ISSUE TITLE
 Max Bug Remove Buildings

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5283]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6c011b7c-b238-44ec-adc5-e29f0d2ea39f)

I had put everything a village max a removed everything it seems to me that now it's time to correct ste things

**Comment by davetgc** [comment]
Thanks for the report, but all that screenshot is some assets on a map. We'll need more information to help you. Do you have the original FPM (Map file) ?

**Comment by SampeyFS** [comment]
yes

**Comment by SampeyFS** [comment]
In addition I found out that max generates objects (( not present in the level)) at random example I generated level 1 objects and I am doing level 3

**Comment by davetgc** [comment]
Are those objects collectables or weapons in level 1? If so, they have to be auto generated so they work across all levels.
