### ISSUE TITLE
GGMAX - BUG - Assigning the "silent" material option to objects in the importer defaults them to use wood impact decals

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5284]
It didn't used to do this, but now it does. Sometimes, I don't want an object to have a material type assigned to it because it isn't wood, metal or concrete, so in the model importer, I assign it as "silent" (materialindex -1). This used to work well enough. Objects assigned as "silent" didn't leave bullet holes when getting shot or play specific material sound on impact.

Now however, it appears objects using "silent" as a material default to using the wood bullet hole decals when shot! No material sound on impact as far as I can tell, but I don't want to see wooden bullet holes when I shoot a fabric mattress!

Please fix. :)

**Comment by LeeBamberTGC** [comment]
@Kraven3D Confirned, sorting now:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/88f3e907-3a6a-41c8-9c39-dd96b04f851e)

**Comment by LeeBamberTGC** [comment]
Fixed for the next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/62701e46-50cb-4e6c-a6a2-179e4cd05dc7)
