### ISSUE TITLE
Bug RX 6600 Win11 and Win10 

### ISSUE THREAD

**Issue by Labsdj** [TheGameCreators/GameGuruRepo#5286]
I get same bug When i try open the GameGuru Max normal version build i got error describe in this link i post https://imgur.com/wiwqVwz impossible to use the engine. Please fix this bug both on the 2 Windows Win10 and Win11 the error presist again. Here now the log on Win10 i use nobeta its normal version, on Win10 and i get again the log file. 
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/14365970/Guru-MapEditor.log)

**Comment by Labsdj** [comment]
Any fix to this bug on Windows Devs??

**Comment by davetgc** [comment]
You'll need to post your system specs for each post as it makes it easier to track down problems. It's very likely to be a local issue as I'm not getting that error.

**Comment by Labsdj** [comment]
My Spects is this:

:::::::::::::::::::::::::::::::SPECTS::::::::::::::::::::::::::::::

CASE: MSI ATX MAG Vampiric 100R ARGB
CPU:AMD RYSEN 5 1600AF 3.2GHZ
RAM:G.SKILL 16GB DDR4 3200HZ OC
MOTHERBOARD:ASUS EX-A320M-GAMING
GRAPHIC CARD: POWERCOLOR RX 6600 8GB
M.2: XPG SPECTRIX S40G - 256GB
SSD: TEAM GROUP 120GB SATA III L3 EVO
SSD: MSI SPATIUM S270 - 480GB
HD: 2TB HD TOSHIBA + 1TB HD WD ELEMENTS USB 3.0
Windows 11 23H2 x64 PT-PT

**Comment by Labsdj** [comment]
I formatted several times in a row and the error remains in both Windows 10 and Windows 11, I don't know what else to do to stop having this error. I test with both the regular version of GameGuru Max and the current exp version.

**Comment by Labsdj** [comment]
However, I also have gameguru classic and it works well on all systems without any error. That's why I wonder if there are any errors in the GameGuru Max code.

**Comment by davetgc** [comment]
Thanks for the information, I suspect this is a problem with your GFX card, and compatibility.

**Comment by Labsdj** [comment]
The drivers are up to date. Is it from some setting in amd's Adrenaline Software? And that I was going to format the whole system for the 10th time again. Could you give me a clue or help me to solve this if on Linux gameguru max works well as I showed in the video on my youtube channel. This error happens exclusively with GameGuru Max.

**Comment by LeeBamberTGC** [comment]
Closing this as duplicated issue and more info on the other issue reported: https://github.com/TheGameCreators/GameGuruRepo/issues/5254
