### ISSUE TITLE
Animals Cause FPS Decline

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5287]
Yesterday I put in a 20 fish the FPS dropped from 75 to 50 FPS obvious the test should be done to a full (Non) empty or original map cmq it is the animal script that slows down the fps this I had already reported but as always not solved xkè was me

**Comment by davetgc** [comment]
Lee is working on performance, Hopefully he can find a reason for any major drops over the fact that you are running 20 complex behaviours in a small area.

**Comment by SampeyFS** [comment]
Thank you for the work you do

**Comment by Necrym59** [comment]
Did you use clone or put 20 specific fish in there

**Comment by SampeyFS** [comment]
Salmon and trout

**Comment by SampeyFS** [comment]
Thank you for improving the script can you also do the other one the foxes and rabbits etc also that does drop thank you  @Necrym59

**Comment by Necrym59** [comment]
You havent answered the question, did you place them individually or use the clone behavior to create them.

**Comment by SampeyFS** [comment]
no individually no clone put it manually

**Comment by SampeyFS** [comment]
OK but you mean the animals not the fish?

**Comment by SampeyFS** [comment]
I tried rabbits with clone entity but as soon as you enter the trigger it goes to ( 5 FPS) the game

**Comment by SampeyFS** [comment]
I've tried with everyone the 5 FPS thing only does it with the (White Rabbit)

**Comment by SampeyFS** [comment]
Cmq I tried with clone the FPS drop there the same according to me is the script of the ( Animals) the two rabbits the worst ones
