### ISSUE TITLE
Feature Request: Assets Seperate

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#529]
I have been thinking about this for a while but have not posted until now, I see movement on Bug Fixing and did not want to take anything away from that.

So now things are moving again I would like to pass this idea around, the biggest part of GG is its assets we have GB's of them would it be possible to split out all the assets into another GG app  'GG Asset Manager' so that all DLC's/Store purchases are controlled/maintained by this app rather than the GG editor (not sure how much code or overhead is required by GG to manage assets but this could be freed up).

With Asset Manager (AM) we could have things like a search field, we could have an FPE checker to highlight FPE's that could be incorrect, a thumbnail manager etc could even have a 3D interactive/preview of the asset using webGL or directx viewer.

the interface could be made simple i.e right click on an asset and choose 'Add to GG Editor' or 'Remove from GG Editor' this will then give us a very clean editor library with only the things we need in it AM could even have a 'Genre' filter the markers and other stuff could be left in the editor.

I am not really a coder I would have ago at doing this myself I could design an interface but that is as far as my skill set.

What do you guys think is this viable/doable pros/cons ?

**Comment by GraPhiX-Guru** [comment]
Being discussed here https://forum.game-guru.com/thread/220822

**Comment by perelect** [comment]
A couple of years ago my idea for this was to make a program that scanned the entity folder and cloned just the .bmp image of each entity and it location. 
Then it would convert the .bmp to .jpg and then use the proprieties of a .jpg for the tags.
That way you wouldn't need to modify any fpe or anything else in GG.
But you would still need the ability to drag entities into a GG map from an external app.
But this is all beyond my skill set.

![prop](https://user-images.githubusercontent.com/49008335/59581047-ed6a8580-9116-11e9-898f-9eec757e0dae.jpg)
