### ISSUE TITLE
[GGC] Text Zone - Typing in "Text to Appear" Field Does Nothing

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#5290]
Typing in "Text to Appear" within a Text Zone does nothing. However if you type the text in Sound0 it works. 

I'm assuming this is because the sound0 field is being utilized as a way to add a readable string, but it gets confusing when the text to appear area field allows for typing in, but yet does not actually work when given a string - which would be assumed at first glance to be the correct utilization of this field.

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
