### ISSUE TITLE
[GGC] Request: Rename Camera Zoom Percentage

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#5291]
Request to rename the Camera Settings (in tab+tab)  "Camera Zoom Percentage" to "Camera Weapon Zoom Percentage" or "Weapon Zoom Percentage".

I've noticed many people get confused with what this option does, and it will be a lot more self explanatory if it gave mention of weapon similar to "Weapon FOV". Since the Camera Zoom Percentage refers to only the weapons that have a zoom option.

in the core cpp I believe it would be this line:

t.slidersmenuvalue[g.slidersmenumax][3].name_s="Camera Zoom Percentage";

to:

t.slidersmenuvalue[g.slidersmenumax][3].name_s="Camera Weapon Zoom Percentage";

**Comment by Teabone3** [comment]
I've added a pull request for this for consideration:

https://github.com/TheGameCreators/GameGuruRepo/pull/5304/files

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
