### ISSUE TITLE
GGMAX - BUG - Water can NOT be added to new maps that selected the "Empty" terrain type in the terrain generator!

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5293]
When creating a new map, I often like using the "empty" terrain type in the terrain generator because I mostly create indoor environments and don't need a bunch of mountains the player will never see being rendered in the background.

However, something I recently noticed is there are NOT any options for water to be added to a map that was generated using the "Empty" terrain type because the tab with the water slider isn't there in the terrain editor! You also can't add water to your map later in the level editor after your new map's been generated because even though the water tab is there, it's empty!

"Empty", flat (no terrain generated) maps should STILL have the option to have water added to them.

Please fix :)

**Comment by MonkeyFrogStudio** [comment]
It's not broken or a bug. You can access water in an empty level, but you have to 'activate' it first. Twirl down the View Options menu on the left-side and tick both of the Water options for Editor and Level. Then you should be able to access your water sliders and more:

![water](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/fc30bd19-5f0e-4300-a42d-cf6b4e397dd4)

**Comment by Kraven3D** [comment]
Cool, thanks. Not a fan of it being off by default in one terrain type and not the other, but at least I have water now. 👍
