### ISSUE TITLE
GG Classic - new updates have significantly worse performance than old ones 

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#5298]
I'd love to use new Classic updates and get the bugs fixed, but every update from 2023 brings very bad performance loss. 

I tested it many times, and last version with good performance is September Fixes 2022  - yes, still from 2022. That version already was 64bit - it has parallax shader, luts, and some other new features. So just switching to 64bit alone wasn't the cause of this performance drop - something happened later. 

 I have test-levels that run in stable 70-75 fps (without drops or stutters, even if I spawn 10 badguys at once) on September Fixes 2022 release, but drop to around 40 fps on latest update (or really any update from 2023).  It's a huge drop. 

If it would be any helpful, I can record a video to elaborate more and  prove that it really happens :)

**Comment by Peri32** [comment]
I agree, I still use october 22 version, the last one I had good performance with.

**Comment by plemsoft** [comment]
@Ghost-l0l Should be fixed in the latest "public preview" , please check and close this issue if you see the same :)

**Comment by Peri32** [comment]
After the last update I can say the performance back to normal for me and even better, good job cheers 👍

**Comment by Ghost-l0l** [comment]
Yes, I can confirm too, performance is much better now, I can close this topic :)

**Comment by Ghost-l0l** [comment]
Yes, I can confirm too, performance is much better now, issue can be closed :)
