### ISSUE TITLE
Editor - No Instance Spray Circle

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#53]
Build: Public Preview

There no longer is a visible circle for when in Instance Spray Drawing Mode when you press "I" in the editor. Impossible to tell the spray distance.  On Windows 7.

**Comment by AmenMoses** [comment]
Verified not there on Win 10 either.

**Comment by AmenMoses** [comment]
Suspect this is the same problem as in issue #69

**Comment by plemsoft** [comment]
Fixed:
