### ISSUE TITLE
document script issue

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5300]
ever since the update, theres no Close option for scripts, NOW the Q does close it, but theres no prompt on the documents to close it.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/3231a095-c7e7-45a2-b940-f6bdefbe83d6)

**Comment by casigus** [comment]
yeah!! reason being is people will be like HOW DO YOU close this document!! :D

**Comment by Necrym59** [comment]
Are you using Local or Screen prompt mode?

**Comment by casigus** [comment]
I'LL get back to you aboot that next time I have the project open! :D

**Comment by Necrym59** [comment]
OK fixed

**Comment by casigus** [comment]
oh ahaha! nice one! ended up falling asleep!!! ill have a nosey now!

**Comment by casigus** [comment]
IT STAYS up for aboot 2 seconds but it is there!

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/3af002b3-5f75-41d0-9b17-87f20a547bfd)


thanks! :D

**Comment by Necrym59** [comment]
Test using the one in the workshop this one is much better for what you want.

**Comment by casigus** [comment]
top banana will do!!!! you are a legend! great work!!!
