### ISSUE TITLE
GGMAX Bug - Saving Crash Max

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5301]
Sometimes when you save your progress (( Inside Max) Max Crash and it closes but it doesn't do it all the time sometimes

**Comment by davetgc** [comment]
Does MAX still save your level, even though it crashes?

**Comment by SampeyFS** [comment]
yes

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
