### ISSUE TITLE
Lua error after a 300kb update ( missing or not found module_misclib )

### ISSUE THREAD

**Issue by era1382** [TheGameCreators/GameGuruRepo#5306]
Hey, after 300kb update which i downloaded, i'm getting lua error about module_misclib and it's can not be found.

I really worked on my map so i cant restart it. Can you help me with it?

**Comment by Necrym59** [comment]
[module_misclib.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14422712/module_misclib.zip)
Extract that and place it in your 
Steam\SteamApps\common\GameGuru MAX\Files\scriptbank  folder (if it isnt there already)

**Comment by era1382** [comment]
hey @Necrym59 thank you it fixed with the file you sent. you really saved my day. i will put this post on Steam Discussions which i created.
