### ISSUE TITLE
Bug Max

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5318]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/698b1b1b-627e-4617-8966-d650342a1257)
This problem I had reported it already max generates duplicate objects in TSV this is the problem maybe that it crashes when loading the test xbecause it doesn't find these objects fix this xbecause it ruins the ( PROJECTS )

**Comment by SampeyFS** [comment]
![Screenshot 2024-03-01 132950](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/ec1ba59a-7a60-4b5f-87a4-097d94d7ce49)

the object ( without Hud ) I put it the duplicate max alone

**Comment by davetgc** [comment]
Have you tried deleting the old file and regenerating it?

**Comment by SampeyFS** [comment]
It's back to the way it was before
