### ISSUE TITLE
Bug Animals

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5320]
Here is a bug to the animals when you shoot them they get back up as you see

https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b638adea-62a7-4080-8872-08785ec45dc6

**Comment by Necrym59** [comment]
Should be fixed

**Comment by SampeyFS** [comment]
Seems to work later I will try again

**Comment by SampeyFS** [comment]
I tried the Necryms script but it still does it

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/7a0d692e-f995-4af3-8690-fd12975b8d3f)

**Comment by SampeyFS** [comment]
I restarted it once more and it's working. it's just the red fox doing it

**Comment by Necrym59** [comment]
no it doesnt - tested here perfectly delete the fox and try again please

**Comment by SampeyFS** [comment]
yes it works now

**Comment by Necrym59** [comment]
excellent :)

**Comment by SampeyFS** [comment]
Good man you are exceptional
