### ISSUE TITLE
Standalone issue

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#5327]
spinning items are not showing up in standalone.
Logic conection activating (showing item) by using other item in standalone does not work.

**Comment by davetgc** [comment]
Can you please supply an FPM demonstrating this issue?

**Comment by Keepo1** [comment]
1. Spinning Bug
https://github.com/TheGameCreators/GameGuruR
![GameGuru MAX - noc1 fpm_ 05 03 2024 17_50_13](https://github.com/TheGameCreators/GameGuruRepo/assets/109030026/e65d48a3-5700-407a-9268-350ef0ebf2e4)
epo/assets/109030026/9cbb78dd-39ed-4c30-8bde-7bc54361338f

**Comment by Keepo1** [comment]
1. spinning bug
https://github.com/TheGameCreators/GameGuruRepo/assets/109030026/356f2644-83b8-43ad-bd67-15b15c031614



![GameGuru MAX - noc1 fpm_ 05 03 2024 17_50_13](https://github.com/TheGameCreators/GameGuruRepo/assets/109030026/fea33449-4bae-4c9d-a647-a12ff3173565)

**Comment by Keepo1** [comment]
2. Logic conection bug
https://github.com/TheGameCreators/GameGuruRepo/assets/109030026/ab55e166-97e4-48f2-a8c7-6b4badc2af0f

**Comment by Kasseyus** [comment]
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
