### ISSUE TITLE
standalone not working on AMD CPU

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5328]
Exported a standalone yesterday, a streamer loaded the game up on TWITCH, it loaded a blank screen (very reminicent of the AMD black screen bug we had a while ago) and then just crashed to desktop.

I dont know the exact specs of the PC but its a good pc that can run most AAA games newly released, but What I do know is the processor is an AMD.

Launched the game on my end, worked as intended. 

The game in question:

https://talentgaming.itch.io/the-willy-chocolate-experience

**Comment by davetgc** [comment]
We'll need to know the specs of his machine really. Can you try to get them please?

**Comment by casigus** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/de1afaaa-f9ed-49f8-b26c-a74db2884374)
  there we goo!

**Comment by LeeBamberTGC** [comment]
@casigus Thanks for the snapshot. What we really need is the GPU details as it is the AMD GPU graphic card that is causing the black screen issue. Can you also obtain a shot of the root folder of the standalone game so we can confirm the AMDFIX files are present, thanks!

**Comment by casigus** [comment]
can confirm the amdfix is there 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/5d0f5074-f335-45c3-af24-8ba3af799767)

but this has only happened on one machine, other users report the games worked fine, so it could just specificly be an issue with there pc rather than a max problem, (asked a few folks to give a test for me on their own amd systems and results seamed fine)

I'll close this issue for now as its only one computer effected.
