### ISSUE TITLE
Build game stalls after player initialization.

### ISSUE THREAD

**Issue by ArmedAndHammered3** [TheGameCreators/GameGuruRepo#5329]
[Guru-Game.log](https://github.com/TheGameCreators/GameGuruRepo/files/14491181/Guru-Game.log)

**Comment by Myke-Price** [comment]
Yes I have worked with [ArmedAndHammered3](https://github.com/ArmedAndHammered3) and can reproduce this in my log file also.
Getting all the file from him and building the game on my machine.
[Guru-Game.log](https://github.com/TheGameCreators/GameGuruRepo/files/14491202/Guru-Game.log)

My next step is to go thru the image files for the huds and see if I can find anything there.
I am on the exp build and they are on the public build.

**Comment by LeeBamberTGC** [comment]
@ArmedAndHammered3 From the log looks like the game started in 46 seconds from launching the standalone executable to playing the level. Based on your system CPU/Storage and the size of the level, this could be normal for MAX.  Can you email me your standalone game you created that shows the stall, and I can throw some debug at it.

**Comment by ArmedAndHammered3** [comment]
https://drive.google.com/file/d/1G7UNZ_4IxvKJ-2YTBNIPXEJ3wNMkTjws/view

Hi Lee, Thank You for responding. I think this was the game as it was the link I shared with Myke.
Sorry for the delay I lost track of the post.

**Comment by LeeBamberTGC** [comment]
@ArmedAndHammered3 In the latest EXP build this issue has been solved, it was all the duplicate collectables in your collection list being spawned at start for the shop(s).  Now they are created when you open the shop/trader. I would suggest you remove the duplicate items from the collection list and any other objects you do not need as collectables :)

**Comment by ArmedAndHammered3** [comment]
Sorry, didn't have a Shop/Trader anywhere in the game and are you saying I cannot have multiple copies of a collectable on a map? So, I made an item collectable and placed it several times on a map, and this caused my game to just spin?

**Comment by LeeBamberTGC** [comment]
@ArmedAndHammered3 You would not need a shop/trader, just a lot of collectables. The old way precloned them ready for ingame use but this took some time. Now they only create when needed in game so no more startup delay in EXP build.
