### ISSUE TITLE
Fantasy Booster Pack - Lake Town Heavy Textures

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5330]
The textures in this ( DLC ) are too heavy for this engine make the FPS drop badly insert less heavy textures for this ( Max's Actual engine ) I did some testing and realized this

**Comment by davetgc** [comment]
Thanks for the report. I'll discuss this with the artist, but I've not noticed any massive frame drops when using the pack.

**Comment by Necrym59** [comment]
No problem here
