### ISSUE TITLE
MAX - Add volume sliders for all audio zones.

### ISSUE THREAD

**Issue by harkinhails** [TheGameCreators/GameGuruRepo#5331]
Volume sliders should exist for all audio zones. It'll allow the developer to layer different sounds with different volumes. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/102403572/f35db1f9-9c7b-46f3-bad1-9699cf967c8b)

Adjusting volume for sounds in audio zones allows you to layer and setup audio in level based on volume adjustments. If you've ever edited a video or produced music, you know what I mean.

[https://www.youtube.com/watch?v=TAYlXmoYHGM](url)

The short clip I posted from test has background ambience and a small sound that plays when I near zombies. I wanted to place multiple but the volume of the sounds I wanted to play were different.

So now instead of just lowering the volume based on sound file in editor, I would have to edit the audio file itself, and make copy and import multiple copies based on volume alone. That makes no sense. A simple volume slider can do wonders for livening things up in your level.

**EXTRAS**: Maybe a quick fade-in and fade-out option for all audio files as well? This will allow people to fade in even the files which aren't perfectly looped, by certain amount of seconds (slide for 1-10 seconds, for example, or a field to enter value).

**Comment by synchromesh62** [comment]
> Necrym59 added a script to the workshop that adds volume slider on Trigger zone, allowing you to play sounds using it and controlling volume.
> 
> Unfortunately, even though slider works in controlling volume, playing sound using trigger also cuts of sound playing through other trigger, thus rendering this useless since sounds can't be layered on top of each other (which is the reason I want sound volume in the first place).
> 
> Basically, sound volume should allow playing sounds over each other while adjusting volume for sounds you want to play.
I have just been testing a layered version Necrym59 he had me try which seems to work well.  
However i would not hold up to much hope for the other 200 to be modified with volume sliders in any hurry.
for now it will just be the sound zone which should do what you need.

**Comment by Necrym59** [comment]
Sound is avery complex issue and Lee is working on changes plus improvements later i beleive, for now i have made the soundinzone with a volume and a overlay option i wont be tackling any more until i hear from lee on his plans.

**Comment by harkinhails** [comment]
> Sound is avery complex issue and Lee is working on changes plus improvements later i beleive, for now i have made the soundinzone with a volume and a overlay option i wont be tackling any more until i hear from lee on his plans.

The one you added only has sound cutting issue TBH. If that's fixed, your addition alone an add a lot of ways to liven things up in a level.

Thanks for looking into this.

**Comment by davetgc** [comment]
I'm going to close this one for now as there has been a response. Once we look into this further it can be reopened.
