### ISSUE TITLE
GGMAX Bug - Standalone Crash

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5336]
Can't extract with standalone as soon as you start it after 30 seconds it closes max

**Comment by SampeyFS** [comment]
Crash when you extract a (double) layer like I used to do if you do it with a ( single ) map it works

**Comment by davetgc** [comment]
I understand that MAX is crashing for you, but I don't understand what you mean by "Crash when you extract a (double) layer like I used to do if you do it with a ( single ) map it works" - Do you mean it's crashing if you try to save more than one level as a Standalone?

This sounds as if you're running out of memory.

**Comment by SampeyFS** [comment]
yes exactly when you extract the double level impossible I have 32 GB of ram ahhahahah

**Comment by davetgc** [comment]
Thank you.

**Comment by LeeBamberTGC** [comment]
@davetgc Can you explain what "extract the double level" means, there is no feature in MAX that can extract a double level.

**Comment by SampeyFS** [comment]
![Screenshot 2024-03-23 150546](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/61d1066d-5ed3-464b-8b79-12783d05030a)

**Comment by SampeyFS** [comment]
When you extract 2 levels sometimes it crashes by itself max

**Comment by LeeBamberTGC** [comment]
@SampeyFS What does "extract" mean?

**Comment by SampeyFS** [comment]
bring in game the game the I talk like this ahahahah

**Comment by davetgc** [comment]
Do you mean export, as in save a standalone, when you say extract?

**Comment by SampeyFS** [comment]
When you (( extract the game with standalone)) to test it ( without ) with Max you start it for (( extract it ) it stays 30 seconds then it closes max but ((it doesn't always do it))
