### ISSUE TITLE
MAX - Grainy terrain bug. [EXP]

### ISSUE THREAD

**Issue by harkinhails** [TheGameCreators/GameGuruRepo#5337]
Light Color is black, ambient white, sun intensity and exposure on max, all shadows off (though I did try with spot/point lights at 128 res shadows).

https://youtu.be/Qr4SNNYJ-OA
https://youtu.be/XP7eznFJucU

With SSR, Reflections, MSAA and SSAO On or off, I've tried different settings and values for all on EXP build. Weirdly enough, after recording these videos, this bug stopped happening, mostly. I can still see this bug a bit in distance where terrain hasn't rendered fully.

Kinda looks like terrain trying to render detail. In EXP build I've noticed this more (terrain details popping in) than non EXP, which is jarring  and is what Unreal 3 used to do with low rest terrain to high detailed one.

I did restart Max and test. Haven't been able to replicate it.

**Comment by davetgc** [comment]
Hi, Thanks for the report.

Could you please post your system specs and if possible a copy of the level (FPM file, found in the mapbank), so we can investigate further.

Many thanks,

**Comment by harkinhails** [comment]
> Hi, Thanks for the report.
> 
> Could you please post your system specs and if possible a copy of the level (FPM file, found in the mapbank), so we can investigate further.
> 
> Many thanks,

Since I made the video, the problem seems to have went away, can't replicate it the way it was in the video. Maybe it's because I removed the LUT filters or maybe it's because I restarted GGM that fixed it. You can try using LUT filters to see if the problem comes back.

It's on Windows 10 LTSC, 1060GTX (6gb), Ryzen 2600X, 32 GB DDR, running from SSD.

[A02.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14510849/A02.zip)

**Comment by davetgc** [comment]
Not to worry. I'm glad it's gone away, but if it comes back please let us know. I'll close this for now, but please feel free to reopen it if you need to.
