### ISSUE TITLE
Collectible Comes Dupplicated

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5338]
![Screenshot 2024-03-06 130009](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/aa072b02-f04f-4848-9253-f31c6759a132)

MAx generates objects ( not put in the level) showed one but there are many this (axe) was not put

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/817cb1e1-759e-4b3c-ac52-8401ab9bcdf7)

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/d5d5c415-dfb7-4cb0-9295-4ced9cdc0522)

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b3f32b17-33d7-4a82-aa70-5dc1bcd8c399)

**Comment by harkinhails** [comment]
Heh, this has been happening to me too.

Weapon I once spawned the player with show up permanently in the list on left, even though they aren't in the level or even on player anymore.

Like in this list, Assault Rifle, Hammer, Shovel and Revolver. I only used them as player's default weapon, but they aren't so anymore. But they still show up on the list, which is weird and just takes up space on the list.

![Clipboard02](https://github.com/TheGameCreators/GameGuruRepo/assets/102403572/0d71d24d-afdf-4f86-8ad1-6820224400ae)

**Comment by davetgc** [comment]
Are some of these entities in another level as part of your game?

**Comment by davetgc** [comment]
@SampeyFS - Please stop naming your issues as Max Bug or similar. It really helps the team if the title explains what the issue is. Many thanks.

**Comment by SampeyFS** [comment]
you can see from the photos max generates of items not put xwhy is the problem not max? that is me as stop there is little to joke we paid for it must work

**Comment by SampeyFS** [comment]
This is the respect you have on the buyer?

**Comment by SampeyFS** [comment]
the axe was never put in this level so it cannot exist there where it is (now)

**Comment by davetgc** [comment]
@SampeyFS - Thank you, and of course we have every respect for all of our users. However, we can't tell much from a screenshot, as all it shows is what's in your level. Obviously, if you say those items aren't there we believe you, but it is just a screenshot.

We do want to help you. We have been in contact on Discord before, so please feel free to contact me there and I will do what I can to work through these issues with you.

Many thanks.

Dave.

**Comment by Necrym59** [comment]
Its a cached weapon of 3 different types.  Just delete the colectables list and let it regenerate.

**Comment by davetgc** [comment]
@SampeyFS - Please follow Necyrms advice and let me know if that has solved the problem please.

**Comment by SampeyFS** [comment]
sisi I solved I close I understood xkè did so I close the question thank you
