### ISSUE TITLE
Save / Load not working correctly in Standalone.

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5341]
as you see from the picture the save works but it is not shown in the save menu even in the load it is shown but save xkè I tried
![Screenshot 2024-03-06 174952](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/41602cfe-6fef-4eea-a126-2445753b7674)
![Screenshot 2024-03-06 175001](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/c1d5f694-7e18-4b99-8f38-f8c2c774590f)

**Comment by SampeyFS** [comment]
![Screenshot 2024-03-06 180423](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6ea16fc3-6bf5-437e-94a8-7660407adda3)


Inside max I found the game save that I had made in the game (( Extracted from sandalone))which in game is not shown

**Comment by SampeyFS** [comment]
Test 1 Save Games

https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/8db9f928-815d-4f58-ae2f-2b72792c8b55

**Comment by davetgc** [comment]
@SampeyFS - Thanks for the video, that explains a lot more.

The Save and Load isn't working in a standalone game.

**Comment by SampeyFS** [comment]
You're welcome I'm glad I was helpful :=)

**Comment by SampeyFS** [comment]
I saw on steam in the post the update was corrected the saving problem but it still doesn't work you can't see the update it's like before

**Comment by LeeBamberTGC** [comment]
@SampeyFS Save game names show again in the next EXP build.

**Comment by SampeyFS** [comment]
thanks a lot buddy
