### ISSUE TITLE
GG:Classic (maybe GG:Max too?) DLC assets can cause problems with AI pathfinding, collisions and performance 

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#5343]
Hey, recently I was experimenting a bit with collision modes and forcesimbleobstacle modes in GG:classic. I found out that most assets from late DLC packs for classic will break AI pathfinding. I was able to get AI zombies to pretty consistently avoid obstacles with all media Im preparing myself, but couldn't get the same results with assets from DLCs.  Im about 99% sure that is because these assets have multiple bones hidden inside. Im talking about packs made by Dekogen, like 'Camping Pack'  'Walled Garden Pack' 'Construction Pack' 'Tool Shed Pack' etc - all the nice looking ones :) 
 
 This is a double-trouble for classic, because, as I said - it breaks the AI, but also It can break collisions sometimes and its just bad for performance in general.  Sure if you add 1 entity with bunch of bones hidden inside, you won't see a major drop in fps, but if you build a whole level with it - trust me it adds up very quickly ;) 
 
   These assets were later on added to Max too, so I'm guessing it can also cause some problems here. And a lot of Max's stock media are UnrealStore packs converted to dbo, probably in the same (wrong) way as before.  I can't open Max's dbo files, but If you can, please check out if there's any bones hiding in static meshes. And delete them if you can :)

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by Ghost-l0l** [comment]
Hard to say, bc since then I deleted all problematic assets from my entitybank;  I'd say for now the this can be closed, as I can't really recreate that in the same circumstances as back then.
