### ISSUE TITLE
Allow the looting of dead animals.

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5345]
I had an idea to create how to know Winter Forest Medieval it would be nice to have hunting of animals by getting meat and skin from them is ( my idea ) I am not familiar with scripts ( lua ) so I give an idea thank you for the work necrym 59 does

**Comment by davetgc** [comment]
This has been requested a few times, and is on the list for the future.

**Comment by Necrym59** [comment]
You can for the moment use the "npc_itemdrop" behavior to allow a npc or non npc to drop an item.

**Comment by davetgc** [comment]
@SampeyFS - Does that help?

**Comment by SampeyFS** [comment]
yes I tried that but I don't understand why it doesn't release the meat e.g. even in the map (empty It works) in my project it doesn't. can you tell me why?

**Comment by SampeyFS** [comment]
![Screenshot 2024-03-09 194451](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/49057df6-e00e-4f93-a6cf-334c20d1ac8a)

is the DLC axe comes out

**Comment by Necrym59** [comment]
Yes it works
