### ISSUE TITLE
Damage indicator Re-Ticks itself and does not stay unticked when saved  

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5346]
Damage indicator Re-Ticks itself and does not stay unticked when saved 
To Re-produce..
Load a game, set it to unticked and save game.
On reload it will be ticked again.
Nice easy one :)

![DI](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/91ff011d-280f-45c6-b51b-e4c8690f9178)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I toggled the damage indictor, saved level, left, loaded a second level, back out and loaded the first level again, the state was correct, then toggled back to the other state, saved, back out loaded other, back out, loaded first, and the state was correct.  The tick retains its state in my own test:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/fa1d40eb-7aba-4fa2-be8a-bc69ceb1cb55)

**Comment by synchromesh62** [comment]
Sorry Lee i didnt explain it properly :(

Load a game, set it to unticked and save game.
**Exit Max** 
On reload it will be ticked again.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/2885d09f-8611-4844-82f3-b4665c61bcfa
