### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by UA998** [TheGameCreators/GameGuruRepo#5347]
When I import my 3D model made with blender so my textures doesn't appear instead my model is set to default white colour iam tired of this plz tell me how to fix this issue

**Comment by davetgc** [comment]
You can apply your own textures manually, using the material settings in the importer. Please let me know if this solves your problem.

**Comment by MonkeyFrogStudio** [comment]
The issue doesn't seem to be a GameGuru MAX issue, but rather an issue of getting your textures out of Blender. You're going to need to generate your Blender textures into the textures/materials (_color, _normal, _surface - surface being a single texture holding AO, metal, and roughness) that MAX can use. Once you generate your textures/materials, you can then ensure the model in Blender uses them instead. Then, when you export from Blender and import into MAX, the textures should come with the model (they do for me). Else, as Dave says, once the textures are exported, you can use the material settings on import to apply your textures.
