### ISSUE TITLE
selected title does not work in chest

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5348]
![Screenshot 2024-03-09 121845](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6dc3eab8-27d9-4d88-bbc9-2f765843461e)
![Screenshot 2024-03-09 121900](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/2871539c-4f62-4c49-a99a-eec5e4cacb94)

**Comment by Necrym59** [comment]
Confirmed! The Selected Title Text does not show in the chest hud screen

**Comment by LeeBamberTGC** [comment]
@SampeyFS Fixed for next EXP build.

**Comment by SampeyFS** [comment]
great thank you
