### ISSUE TITLE
MAX BUG - Cloned Objects may not retain the correct weight

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5349]
In the video below I will demonstrate that a brick that would ordinarily be carriable is not able to be picked up when cloned. We _think_ this has to do with the weight of the object being set to the incorrect amount when the object is cloned. I will send a copy of the level via email.

https://youtu.be/1_BUrTPFxJA

[Prototype.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14547376/Prototype.zip)

**Comment by Necrym59** [comment]
Confirmed! An object originally set at weight of 100 is then adjusted to be lower eg: 80 for example then cloned i think is being set at the original setting. This should not happen, the new weight setting on the object should be cloned or be able to be set in lua code to 'get' then 'set' the new weight setting. There does not appear to be a "SettEntityWeight(e)" lua command to do it in code so we are stuck to get this cloning to either correctly get the designated weight at the time of cloning or needing a command so it can be done in the behavior.

**Comment by davetgc** [comment]
Confirmed here too.

**Comment by Necrym59** [comment]
Rather important this one

**Comment by Blood-Moon-Interactive** [comment]
Confirmed fix
