### ISSUE TITLE
When importing objects, MAX does not pay attention to multiple UV maps

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#5351]
In order to get quality texturing it is often the case that a single model will have multiple textures with sepatrate UV maps. But when trying to import, all the textures are using the same UV map.

**Comment by davetgc** [comment]
Are you applying them to the appropriate mesh when importing? Some imports might need manual intervention.

**Comment by MonkeyFrogStudio** [comment]
Just did a simple test. Here's a cube that consists of two UV maps and two materials imported into MAX:

![multi](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/0e979b4f-b31b-45ad-9974-b1e1c832f0db)

As you can see, the object comes in with both UVs intact and the correct materials applied to each set of UV maps.

**Comment by MonkeyFrogStudio** [comment]
Question @TenebreGaming - What software are you working in and how are you creating the different UV maps? 

What I did in the above example is separated the model into two, each having it's own UV map and applied a separate material to each. Then I exported 'both' parts as one single model from Blender and imported into MAX.

**Comment by TenebreGaming** [comment]
The object was created in Blender, and displays fine in other software. When attempting to import the object, the second material was using the same UV map as the first material. The first of the UV maps was an island set, while the second was a simple square. I wound up merging the two into a single texture and UV map, thouugh this meant losing some quality.

**Comment by MonkeyFrogStudio** [comment]
Not concerned about it showing up properly in other software, but does it show up properly in other game engines? 

The simple solution, as pointed out above, is to split your model up, one part for each UV map you need/want. Then, when exporting, select every part and export as one model. You will end up with one model with multiple UVs and multiple materials, just like the cube example I show above.

**Comment by MonkeyFrogStudio** [comment]
I'll have to play with this. Apparently Unreal accepts up to 7 UV maps per model. But I've not looked into how it works there.

**Comment by TenebreGaming** [comment]
I guess technically the two objects were joined so they probably looked like a single object to MAX. Blender does have the function to separate by material, splitting the objects apart, so that would be a good solution to avoid the issue. I know I have downloaded models from either Unity or Unreal that had multiple UVs on a single mesh (not split), but it was a while ago.

**Comment by Kraven3D** [comment]
I don't think this is a bug. I import multi-material meshes from Blender all the time. The scaffolding mini kit was the most recent example of this. The way that MonkeyFrog studio mentioned is an easy way to go about it.

Are you assigning the different materials to their appropriate faces in Blender under the materials tab and then clicking "Apply" to apply that material to the faces you have selected? If you're not doing this step, that information isn't being "baked" into the model on export. Just opening an additional texture with certain faces selected in the UV viewport isn't enough, even though it displays all of those different materials in Blender's 3D viewport.

**Comment by MonkeyFrogStudio** [comment]
"Are you assigning the different materials to their appropriate faces in Blender under the materials tab and then clicking "Apply" to apply that material to the faces you have selected?"

Just to be clear, he's not talking about assigning different materials to different faces, but having more than one UV map per object so that you can then have multiple materials/textures. For example (and not a good one, but it's what came to mind) - perhaps you want a single character model, but a separate UV map for just the head with it's own 1k texture and a separate UV map for just the body with it's own 1k texture, thus allowing for more detail in the head. 

Again, this could be done by having the head as it's own model and the body as another, then exporting both as one model. However, other engines, like Unreal, allow for more than one UV map, which would eliminate the need to split a single model into multiple pieces.

I could be missing something here, though. So, always open to learn.

**Comment by Kraven3D** [comment]
Ah, then I clearly misunderstood. I was going off of what he said here where he was mentioning different materials:

> When attempting to import the object (from .glb) the second material was using the same UV map as the first material. 

> There is no way as far as I can see to specify what UV map a material uses, but it is inside the file.

**Comment by MonkeyFrogStudio** [comment]
@Kraven3D From the title:

"MAX does not pay attention to multiple UV maps"

And from his post:

"In order to get quality texturing it is often the case that a single model will have multiple textures with **sepatrate UV maps**."

This is why I suggested splitting the model into more than one so each could have its own UV map. However, a brief search shows that Unreal allows for up to 7 UV maps per model. So, while splitting a model up is a solution that works in MAX, other engines allow for more than one UV map per single model.

**Comment by MonkeyFrogStudio** [comment]
Thanks. I will take a look in a bit. I should have checked that.

**Comment by TenebreGaming** [comment]
@Kraven3D Just because you have multiple textures and/or multiple materials doesn't mean you have multiple UV maps. The default UV map is a full square from 0,0 to 1,1 and has nothing to do with the texture size. You can use the same UV map for different side of a cube with no issues.  Unless you manually create and assign a new UV map, the object will only have one UV map. Like in the image below, there are two UV maps.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/a0b4f057-9bce-44a6-b51c-74564e6fa1a2)

One is square and one is not. For example, the next image shows both UV maps because all vertices are selected. (don't worry about all the wasted texture space in this, it's just an example and not actually used). The mesh part is a full square, while the rest is unwrapped. The main reason for wanting to do this is on part has transparency while the other does not. MAX will use only one of the UV maps, so the texturing will be wrong because the entire model is one single mesh.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/1973c4b4-65ce-4262-b207-bc23db817f04)

It's not really a big deal, but as it is actually common to do this and is supported by other engines, it should be supported. But since there reasonable workarounds it can be delayed until more important things are done.  I'm sure the code behind it would be a pain.

**Comment by MonkeyFrogStudio** [comment]
Just tested multiple UVs in MAX on a single object and it works perfectly. Here's what I did:

![two_1](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/dd6fe61f-b3d2-4f74-93f3-cafdc3fb937b)

The above image shows a single object - a cube. I selected 3 of the faces and created a UV map just for those three faces. Then I created a material (in Object Mode) and, in Edit Mode, applied that material to those three faces only.

![two_2](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/27a88b21-8050-4bcf-a864-5afd49794f33)

Then I selected the three remaining faces and created a UV map just for them. In Object Mode, I created a second material and then, in Edit Mode, applied the second material to just those three faces. 

As you can see, when I select one set of three faces or the other set of three, the different UV maps show up with the different texture applied.

I then exported it out to FBX and imported it into MAX. Again, this is one, single model. I never split it up in Blender. Here's the result in MAX:

![two_3](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/50700aeb-8c3e-4cb6-9a1c-4ce478b23a59)

As you can see, the single model comes in with both UV maps preserved and both materials applied exactly as I had it in Blender. So, MAX is supporting multiple UV maps per model.

**Comment by TenebreGaming** [comment]
I wonder if it's working for .fbx and mot .glb. I switched to .glb for various reasons. I will recreate the exact model and issue later when I have the time.

**Comment by TenebreGaming** [comment]
So this is very consistent for me.  This object has two UV maps (the default and one for the baked texture).

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/d09d445c-77de-47bf-b002-e39f35b64f28)

You can see that the shader is set to use the second UV map

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/2d157611-a72a-43fb-a757-7b19ddfcf62c)

And the object displays correctly in Blender

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/1be7e121-d8fc-4792-bd82-5b6b4df8cc7f)

And it displays correctly in the Windows Model Viewer

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/bab12ae4-076f-4342-984c-57a73c46b5e0)

But when trying to import it into MAX, it uses the first UV map and not the propper one

![Screenshot 2024-03-12 142650](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/7ab14c1a-e918-4197-babe-a2d23ebf4687)

The only way to make it work is to delete the first UV map from the object.

**Comment by Kraven3D** [comment]
Your best bet would be to upload the asset and textures here if possible so someone else can take a look at your model and see what's going on.

**Comment by TenebreGaming** [comment]
Anyway, I tested this with Unity and it didn't handle it either, so I'm going to close this report. I just won't use multiple UV maps on a single mesh. It's easy enough to split the mesh into individual components.

**Comment by MonkeyFrogStudio** [comment]
@TenebreGaming You don't have to split the mesh (unlike what I'd said previously). All you have to do is, in EDIT MODE, select the faces you want that correspond to the UV map you've made for them (you can select them via the UV map) and ASSIGN a material to just those faces. Rinse and repeat for each UV map you've made. Then each material will use its own material.

**Comment by TenebreGaming** [comment]
That is exactly what I was doing. And the exported model will load back
into Blender fine, will display with the Windows 3D Viewer file, but will
not load into MAX fine.

Try doing it with something more complex than a cube and show that it
works. I tested it with a cube and found that it worked because both UV
maps were actually the same and each face was using a square map from 0,0
to 1,1. Once I try something more complex with (dor example) smart UV
projection, it fails.
