### ISSUE TITLE
FPS Test Project

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5361]
I noticed that the FPS starts at 35 then drops to 20 it seems that there is something that always traps it at 20/25 FPS, I noticed this that it only does it in customized projects maybe it can help you solve the problem one of the drops are the clouds cloud

**Comment by Necrym59** [comment]
have you check with vsync on or off

**Comment by SampeyFS** [comment]
active or deactivated changes little it seems

**Comment by davetgc** [comment]
We're going to need a lot more information I'm afraid. All my levels run a 60fps for example, and performance is based on a lot of factors, models, the number of behaviours running, the size of the level, etc.

**Comment by SampeyFS** [comment]
Active behaviours always are night day cycle

NPC village Resources around mushrooms example 

Craft Table, rpg_player_state, the drop you get in the house and in the village looks like an excessive load of polygons or collisions but there is not so much to drop so far away from the buildings e.g. at the lake it goes up to 40 FPS as soon as you get close to that area (there seems to be something there) that annoys and loads the GPU a lot I did several tests and managed to get to 50 FPS many things that slow down are the HUDs if you need it I'll pass you the project

Translated with DeepL.com (free version)

**Comment by davetgc** [comment]
Can you post a screenshot showing the metrics? (Press TAB in test game), so we can see the FPS, and the polygons being displayed.

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/cf4da78f-883d-49a6-88e5-d49ac18fdd4c)
Zone  House

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/7d09c50f-8ba0-4a4a-832c-719da6a405f1)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/76e04937-2305-4d81-afbf-218da002da8d)
Village Zone

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b31b2567-20f8-449c-b0ad-1c11e3bbe92c)

lake zone

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/d0f4d7fd-17c0-4c0c-be38-f76f3739485e)
lake zone

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/7923e280-dec3-42a5-bf4a-329271423c12)

**Comment by SampeyFS** [comment]
Please write to me in private if you need help

**Comment by SampeyFS** [comment]
[dxdiagreport.txt](https://github.com/TheGameCreators/GameGuruRepo/files/14641731/dxdiagreport.txt)


This can perhaps help you
