### ISSUE TITLE
Added medieval costumes

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5363]
I'm creating the medieval video game Winter Forest Medieval but I need at least 3 medieval clothes, trousers, t-shirt and hats. It would be an idea to have these costumes to be able to create the medieval style video game (it would be nice to have them if it's possible) they were put together to create a man

**Comment by Necrym59** [comment]
Make some

**Comment by SampeyFS** [comment]
eh, being capable has never been done
