### ISSUE TITLE
Food Script Doesn't make the inventory eat

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5365]
They do not work from the shop to the inventory sometimes if you take it from the table and then eat it it works

https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/09091c16-595e-4ea6-b7a5-f99e94fcf863

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/44314ded-6bd1-4932-a18d-9d214c8b599c)

**Comment by SampeyFS** [comment]
@Necrym59  Problem Food

**Comment by Necrym59** [comment]
There is no problem

**Comment by SampeyFS** [comment]
simple when you eat he also lifts your waist and food when he is in the 'inventory' he doesn't eat it if you see the videos he shows them..

**Comment by davetgc** [comment]
Are you saying that the food can't be eaten directly from the inventory?

**Comment by SampeyFS** [comment]
Yes exactly, but when you ((eat)) also raise Health

**Comment by SampeyFS** [comment]
> ScreenRecorderProject2.mov 
> Oltre al cibo, viene caricata anche la vita dell'omino

@davetgc

**Comment by SampeyFS** [comment]
Watch my videos and see

**Comment by Necrym59** [comment]
These were updated yesterday, please check and update your workshop versions, i can find no problems. I have re-upped the workshop files again just in case steam didnt do the update yesterday.

**Comment by SampeyFS** [comment]
Yes, I also checked the files but it always does it

**Comment by Necrym59** [comment]
Then you not using the latest versions it seems or there is other versions in the same map that have to be updated

**Comment by SampeyFS** [comment]
yes now I check all the food

**Comment by SampeyFS** [comment]
the workshop hadn't been updated I have to be careful I had to write again to update everything anyway it works thanks I'm closing
