### ISSUE TITLE
Rset weapons

### ISSUE THREAD

**Issue by kushiya1122** [TheGameCreators/GameGuruRepo#5366]
how i remove all the weapons when player finish level and new level i want to 0 weapons how i do it plz

**Comment by davetgc** [comment]
This sounds like a feature request, as weapons are carried over normally.

**Comment by Necrym59** [comment]
Cant you just start a level with the character having no weapons, in its custom settings??

**Comment by kushiya1122** [comment]
> Cant you just start a level with the character having no weapons, in its custom settings??

 No i cant player bring all weapons and ammo next new level can i get start level no weapons

**Comment by Necrym59** [comment]
Update your workshop files then look for disarm_zone behavior, if you start the player off in that zone it should remove all weapons.

**Comment by kushiya1122** [comment]
> Update your workshop files then look for disarm_zone behavior, if you start the player off in that zone it should remove all weapons.

i found behavior weapons disarmd, but when plyer jump to next level it will armed again that zone not remove only hide weapons , can i fix it to remove weapons forever . start new level without weapon please 
![Screenshot 2024-03-29 180637](https://github.com/TheGameCreators/GameGuruRepo/assets/150064614/1f622f7f-cef9-42cf-8011-46034086e288)

**Comment by Necrym59** [comment]
No that isnt it this is the one to use
![discarm](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/9d6a679a-7acd-4d60-8cba-399739904cb0)

**Comment by kushiya1122** [comment]
i cant find this in my behavior box, how can i find it plz

**Comment by Necrym59** [comment]
If you cant see it then you must be running the Retail version of Max,
Here is the behavior.
[disarm_zone.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14817344/disarm_zone.zip)
Unzip it and place it in your - 'Documents\GameGuruApps\GameGuruMAX\Files\scriptbank\user folder"
then you should be able to see and add it in your game.

**Comment by kushiya1122** [comment]
thank you very much.
