### ISSUE TITLE
Max Refusing to Open

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5367]
After the last update GameGuru Max is refusing to open when the play button on Steam is clicked, launching from the exe gives the following error.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/b1292a25-6913-4d12-8003-3cd16e49307a)

**Comment by MonkeyFrogStudio** [comment]
Seems all of us are getting this with the last build. Please fix. :)

**Comment by synchromesh62** [comment]
Same for many. Bad update by the looks of it.
I was using it fine 20 mins ago before i applied it

**Comment by SampeyFS** [comment]
ah that's what it says to me too I was going crazy ahahha

**Comment by LeeBamberTGC** [comment]
@extremestrategy Sorry all, just working through an alternative auth system. New EXP build now up which resolves this one :)

**Comment by SampeyFS** [comment]
Imagine everyone can (( Make mistakes )) it's human

**Comment by extremestrategy** [comment]
Runs now just fine, thank you Lee.
