### ISSUE TITLE
day night error

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5371]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/1a289e32-b9cf-4047-b0e2-5e3d9385d908)

**Comment by SampeyFS** [comment]
You must put in Global example MyDay

then in the game screen put ( text ) ( MyDay ) is the day

**Comment by SampeyFS** [comment]
![Screenshot 2024-03-17 213109](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/36ea9c30-5e89-438d-86d2-173b8c50629c)
![Screenshot 2024-03-17 213221](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/0e0c9bdd-31ea-4539-a39e-7ba35fa59a4b)

**Comment by Necrym59** [comment]
It works as expected, I cannot understand what your problem is

**Comment by SampeyFS** [comment]
no it goes for me I'm showing him how to make it go

**Comment by Necrym59** [comment]
A trap for a blank or non existent global is now fixed in the latest version
