### ISSUE TITLE
BUG - GGMAX REFLECTIONS ARE NOT WORKING !

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5372]
In the latest version of ggmax Reflections are not working !
I need to reflect the walls on my floor object, but it's not working anymore.
Water is deactivated.
I added a probe to try the reflections, i saw that the floor object was reflecting only the probe, instead of the real environment.
Then i deleted the PROBE, but now the object keep always the probe reflections even if i change the texture.

![no reflections](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/cf1d67e3-c74d-4ccf-8ab6-bb470d79b8a0)

![probe bug](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/b8510b9b-22af-4c2d-b7e3-becfb8a27190)

**Comment by davetgc** [comment]
Does it work if water is on?

**Comment by imothep85** [comment]
If i activate the water, the water reflect my colored walls

**Comment by imothep85** [comment]
it was a problem with ggmax rebooted, now texture reflections works
