### ISSUE TITLE
BUG - Level state does not reset upon player death

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5373]
In the video I will demonstrate that the level state does not reset when the player dies. This can be a problem in certain circumstances where behaviors being used within the level depend on the initial state of the level. In this example I'm using collection count, but really this would effect any behavior that relies on the initial state of the level to begin with.

https://youtu.be/ekXCKTZst04

**Comment by davetgc** [comment]
Do you mean in standalone or text game?

**Comment by Blood-Moon-Interactive** [comment]
I was testing it in test mode but when I ported to stand alone it's not an issue. So disregard.
