### ISSUE TITLE
GG MAX BUG selection Environment Effects menus doesn't work !

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5375]
A new BUG, IF we have an locked object selected in the scene the menu environment effect can't be selected, doesn't work.
IF we deselect the object the menu appear and work..

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/e053faf6-e6f8-4519-9536-236f0b6d1132

**Comment by LeeBamberTGC** [comment]
@imothep85 Cannot reproduce with the latest EXP build. Can you reproduce this issue with an empty level and one locked object:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/7f71b296-8c96-445f-890f-e3cb17cd0269)

**Comment by imothep85** [comment]
i can't reproduce it because it was fixed apparently i don't have the bug anymore !
