### ISSUE TITLE
GG Max global_activator 

### ISSUE THREAD

**Issue by Jisafu** [TheGameCreators/GameGuruRepo#5377]
The global_activator activated when a certain value was exceeded, I wish it would activate when it was equal to or less than a certain value.

I solved the global_activator problem by changing the code 
"if currentvalue[e] **>**= glactivator[e].trigger_value then" 
to 
"if currentvalue[e] **<**= glactivator[e].trigger_value then"

A better solution would be to do it via a choice in the code, but my knowledge of lua is not good enough for that

**Comment by Necrym59** [comment]
I will look at bthis one in due course but i think if you have it activating below a certain value then the global should be reducing not increasing as it the cutoff point shouldnt matter.
