### ISSUE TITLE
GG Max loop3dsound

### ISSUE THREAD

**Issue by Jisafu** [TheGameCreators/GameGuruRepo#5378]
The loop3dsound played the sound immediately. You could turn it on and off with the switch, but I wanted to start with the sound off so I could turn it on afterwards.

I solved the loop3dsound problem by changing the code 
"function loop3dsound_properties(e, range, minvolume, maxvolume)
module_activationcontrol.init(e,**1**)" 
to 
"function loop3dsound_properties(e, range, minvolume, maxvolume)
module_activationcontrol.init(e,**0**)"

A better solution would be to do it via a choice in the code, but my knowledge of lua is not good enough for that.

**Comment by Necrym59** [comment]
I will look at this one in due course thanks
