### ISSUE TITLE
Tower Model does not produce a good navmesh on the staircase

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#5379]
You can see how the navmesh is broken in this screenshot. This is very recent, as it worked last week. The enemy cannot leave the tower anymore. This is the Watchtower Guardpost from MAX.

![Screenshot 2024-03-18 200835](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/c8dbbe24-e809-4ddd-8635-33d50f8705f7)

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Looks fine with the latest EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/af2b84ca-5b89-40ff-9a64-12c837cfb214)

**Comment by TenebreGaming** [comment]
@LeeBamberTGC It is still exactly as in the image I posted for me in build 2024.03.23.

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Can you attach the FPM level file, it might be how the tower is placed/rotated/etc

**Comment by TenebreGaming** [comment]
@LeeBamberTGC Interesting. So I found that just placing one in an empty level works fine like you showed. But it is still happening in the test level I have. But I was able to reprodice it by first placing down a "Warehouse - Brick" structure and then the watchtower. If I do it in the other order or remove the warehouse the navmesh is fine, even after adding the warehouse back in.

Here is the .fpm for testing.

[navmesh.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14743933/navmesh.zip)

**Comment by LeeBamberTGC** [comment]
@TenebreGaming I moved the tower a little and the nav mesh was restored. I think the tower model is an edge case asset, and will probably need some art tweaking to produce a wider bath for the nav mesh:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/38546bec-f83f-47f5-935c-e347ddb15f87)

For now I will amend the title so we can attend to the cause, which in this case is a staircase that is too narrow for the current nav mesh system.

**Comment by TenebreGaming** [comment]
I was able to allow passage of the NPCs by placing a piece of plywood down
against the stairs, so it's not a super high priority. Probably not
OSHA/HSE safe, but it will work.
