### ISSUE TITLE
collect gun through wall

### ISSUE THREAD

**Issue by Raj898** [TheGameCreators/GameGuruRepo#538]
Sometimes the hand show through wall and I can collect gun if shoot correct spot

https://vimeo.com/342885021

**Comment by Belidos3D** [comment]
This is not a bug, the scripts just aren't programmed to do this. 

The scripts could be altered to use ray tracing to detect visibility, there are some examples over on the forum by smallg and amenmoses.

**Comment by synchromesh62** [comment]
There is also and adjustable distance in the weapon.lua .. 
Changing the distance from 150 to 50 sorts it perfectly
