### ISSUE TITLE
Bugs in Building Editor Gameguru Max

### ISSUE THREAD

**Issue by Itaylana** [TheGameCreators/GameGuruRepo#5380]
I found a Bug in the Building Editor. When I create a House, save it and then insert it into the 3D Level Editor, some Textures are missing or changed. When I go back to the Bulding Editor and Load my House, everything is completely different. Deleted Walls are back and some Textures are replaced.
(Red Floor and the Corner from the Wall is Wrong) -Screens

![2](https://github.com/TheGameCreators/GameGuruRepo/assets/74021803/68f9cbfb-4989-4607-a337-d893d14b1e33)
![4](https://github.com/TheGameCreators/GameGuruRepo/assets/74021803/27c34605-7b57-41fe-88aa-25ff1750f923)

Next Proplem. How is it, when I want to Jump to Level to Level?
I create Two Levels with Trigger Zone and then, I choose in Behavior Mode the Teleport Script. In Dropmenu choose I "Go to speccific Level" and select Level 2. But when I Test, it dosent works and dont Jump to Level 2. Not in 3D Level Editor and not when I export This Game, as Standalone.

**Comment by Necrym59** [comment]
Do you have teleport set to Local or Level. The behavior works as expected here. In test mode it will just inform you at bottom of screen where it would teleport to. Only in standalone will it teleport to next level.

**Comment by davetgc** [comment]
@Itaylana  - Can you please post a separate post for each issue. Thanks.
