### ISSUE TITLE
MAX Trigger zones not working in one level but fine in others.

### ISSUE THREAD

**Issue by OobieDoob-Benoobie** [TheGameCreators/GameGuruRepo#5381]
If you need. I can give link to download said level through email.

Trigger zones like Text in zone and Music in zone especially. 
Having issues with sound playing in ANY zone, so I deleted most of them in troubleshooting attempts.

**Comment by Necrym59** [comment]
Zone behaviors and functioning as expected, can you be specific as to what happens and give details. Is this exp or retail release.

**Comment by OobieDoob-Benoobie** [comment]
> Zone behaviors and functioning as expected, can you be specific as to what happens and give details. Is this exp or retail release.

Yes of course. 
Its EXP build and I have tried updating DLC and doing STEAM file verification. 
I have also tried deleting zones and redoing them.
Maybe some configuration im getting wrong?

Explanation: 
1: I place a text marker on the ground in front of a locked, electronic gate stating "Gate activated remotely". 
When player walks over zone, nothing happens. (No text is displayed) 

2: I place a music trigger in a dark pathway to give ambiance and mood to the scenario.
When player walks over zone, nothing happens. (No sound is activated)

3: I place a Trigger zone to spawn in enemies behind the player, and add sound to the trigger.
When player walks over zone, the new NPCs spawn in but there;s no sound activation. 

It should be noted that I have a lot of my own music and ambiance that I made myself. It all worked until the latest update to EXP.

**Comment by OobieDoob-Benoobie** [comment]
Also I have completely redone most zones in an attempt to troubleshoot. Making sure my music and audio files are still in working order. Everything seems to be good until I test or try to make a standalone demo.

**Comment by Necrym59** [comment]
Is the zone too close to the gate/door so the prompt is being overwritten perhaps try moving it back and see if it works.
I tried all 3 scenarios without a problem, all i can suggest is delete the scriptbank folder in the steam installation and re-verify to get them again, also do a workshop update as well. If you still have issues report it back here.

**Comment by OobieDoob-Benoobie** [comment]
Sorry for the delay.
I tried deleting the scriptbank folder and running steam verification
again, and re downloading scripts
through MAX but it still doesn't work.
Also I noticed that if im standing near the gate or the switch that opens
it, I get an onscreen targeting reticule.

**Comment by Necrym59** [comment]
All the zones are functioning fine here. All i can suggest is you may have to supply the map for checking to see if there is somthing amiss. If i dont spot anything then Lee probably will.

**Comment by OobieDoob-Benoobie** [comment]
FC - 167.fpm
<https://drive.google.com/file/d/1x5xx5t7lz3FBZLFn8i2eQMw1eLpU_VME/view?usp=drive_web>
 FC - 167.lst
<https://drive.google.com/file/d/1TIQVru7Az2enKz9SPYj9493a91dGSS9Q/view?usp=drive_web>

**Comment by OobieDoob-Benoobie** [comment]
Sorry I dont know how to attach custom assets and sounds. Some stuff might
be missing.

**Comment by OobieDoob-Benoobie** [comment]
Now (Since latest update) NO SOUND is working from ANY of my Zones of all types. 
Spoken voice and prerecorded cut-scenes are the only one with sound on all of my levels now.

**Comment by OobieDoob-Benoobie** [comment]
> All i can suggest is you may have to supply the map for checking to see if there is somthing amiss. If i dont spot anything then Lee probably will.

I didnt realize Github is using my google drive. I gave you permission.

**Comment by Necrym59** [comment]
Well the map seems fine here
where exactly is the promlem area

**Comment by OobieDoob-Benoobie** [comment]
Here is a video of whats going on.
I figured if a picture is worth a thousand words....

Also thank you for spending time on this.

https://youtu.be/J7_zwGd6sHA

**Comment by Necrym59** [comment]
These have been fixed and will be in the next update.
Replace both these files in your max steam installation scriptbank\markers folder
[hurt.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14764406/hurt.zip)
[textinzone.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14764407/textinzone.zip)

**Comment by OobieDoob-Benoobie** [comment]
I replaced both files with the ones you provided.
Unfortunately this had no effect.
I suppose I'll wait for the update and see if something changes.

**Comment by Necrym59** [comment]
can you check to make sur you have replaced both the steam installation ones and the workshop ones, they definatley work on your map

**Comment by OobieDoob-Benoobie** [comment]
I Replaced the ones in my Docs folder (Workshop) as You suggested.
Sadly it may have made things worse.
After trying to get it working all day, I made this video to show whats
happening.

https://youtu.be/5Bdu35p1u3k

**Comment by Necrym59** [comment]
I cannot replicate the problems they all work fine here evenb on your map supplied the only thing i can suggest is verify in steam the max installation and see if it finds anuything to update.

**Comment by OobieDoob-Benoobie** [comment]
Im probably gonna have to reinstall.
Any idea whats going on here?
Im running all .exe files as admin:

https://youtu.be/-xU3Z_WWULE

**Comment by Necrym59** [comment]
I have no idea all i can suggest is either reinstall max or do a verify then also do a workshop update then see what happens but you will have to ensure that each of the zones are using the correct behavior files and then save. They do work as they are supposed to as far as i can see. If you still have a problem then post to Lee directly and see if he can help spot what it may be.

**Comment by OobieDoob-Benoobie** [comment]
I just reinstalled Max. It's now loading but crashing again when I try to
load that level.
I'm gonna try retail non EXP and see what happens. If it's still not
working as intended ill
contact Lee.

You've been absolutely amazing, and you have my utmost respect and
gratitude.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
