### ISSUE TITLE
Crash problem with custom materials after copy & paste.

### ISSUE THREAD

**Issue by RogeriaEscape** [TheGameCreators/GameGuruRepo#5382]
Hi everyone ! I have a problem with GGMax ( Stable version ) .
Sometimes , not everytime but sometimes when i add a block/asset or everything and i set custom material .png and when i want to copy paste that model/asset/..  the Engine crash. Only when i use custom material and copy paste on the map that thing.

 But is strange this crash is not everytime. But is still there and i lost my map unsaved.

**Comment by davetgc** [comment]
Hi, can you please post the asset and texture so that it can be tested. Thanks.

**Comment by RogeriaEscape** [comment]
The crash was on every type of asset. Even default from Booster pack or default from GGMax preinstalled.
Is not a specific asset.

**Comment by RogeriaEscape** [comment]
My crash was on : https://gamecreator.store/product/36804
but is not only for these assets.

**Comment by davetgc** [comment]
I've had to delete your link to the assets, as they are commercial and can't be shared publicly.  Could you please email the asset that causes the crash, and the texture being used to lee@thegamecreators.com so we can investigate. 

Can you also please post your system specs.

Many thanks,

**Comment by RogeriaEscape** [comment]
Ok Sir

**Comment by RogeriaEscape** [comment]
Ok this is the link : Textures
<https://screamingbrainstudios.itch.io/seamless-abstract-pack>

În dum., 24 mar. 2024 la 19:53, davetgc ***@***.***> a scris:

**Comment by RogeriaEscape** [comment]
My System spec :
i5 9400F
16 GB RAM
GTX 1060 6 GB
SSD

My PC run GGMax Ok.

În vin., 5 apr. 2024 la 08:18, davetgc ***@***.***> a scris:

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
