### ISSUE TITLE
Mask and rad does not work

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5387]
as you can see from the video, the mask does not work and the entire radiation cannot even be removed 

https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/569dcacd-43ec-4b43-8cec-b1e28298263a

**Comment by Necrym59** [comment]
On testing, they both work perfectly here -  double check you have and are using the correct latest versions of the behaviours.

**Comment by SampeyFS** [comment]
Yes I updated it twice but nothing

**Comment by synchromesh62** [comment]
> Yes I updated it twice but nothing

Necrym asked me to test independently 
Seems to work fine here 

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/dd711882-36ff-42cb-a391-8c456f5bbbcd

**Comment by SampeyFS** [comment]
I don't understand why it doesn't go for me all the time hahahah but even in the empty map it doesn't go

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/bc15684c-5234-48b7-aedf-f41ce82b8bc2)
I don't know why you see an empty map, it doesn't open, maybe it's like yesterday, the scripts don't update

**Comment by Necrym59** [comment]
Did you do as i said earlier - "Have you ticked the collectable checkbox for the Gasmask or Radsuit"

**Comment by SampeyFS** [comment]
yes i tried it now i woke up it works thank you very much i'll close
