### ISSUE TITLE
Soldier kick through wall when close door

### ISSUE THREAD

**Issue by Raj898** [TheGameCreators/GameGuruRepo#539]
When use eb editor and close the door the player is kicked when at door.
When use another Soldier from pack the player was not kicked the same or is there correct way to use eb editor?

https://vimeo.com/342885370

**Comment by synchromesh62** [comment]
@Raj898 
This video is using a third party character and script.
Could you please show a video using a stock character with the same issue or it could be excluded from the March fix list ..

**Comment by synchromesh62** [comment]
Unable to replicate with stock
