### ISSUE TITLE
Save \ Load in Standalone Broken 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5390]
Been at this all day and it all seems very broken
EXP.. 

1 .. No save Name generated when you try to reload the save
2 .. Ai on upper levels fall through to the floor
3 .. Ai run backwards
4 .. Many triggers fail to work 
These things can also happen simply just loading a second level in standalone

I did a quick video as a demonstration of some of what is happening.

**EDIT** I have reason to believe Lee is working in this area so it may just be a side effect of that,

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/44a0b2ef-aa28-4748-b827-a86f345c7b33

**Comment by SampeyFS** [comment]
yes I reported it too you can't see the save see

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Check the current EXP build, save game name now shows in the standalone. Send me the test stock level and I will check out the rest (which may also be fixed).

**Comment by synchromesh62** [comment]
> @synchromesh62 Check the current EXP build, save game name now shows in the standalone. Send me the test stock level and I will check out the rest (which may also be fixed).

Hi Lee here is a small standalone of that level you can try yourself to save you creating one from the .fpm
**Procedure..**
Start level and **"save"** right away 
walk forward to trigger the npc's
Let them kill you
**Load in the save** you did at the start 
walk forward again to trigger the npc's and one will have fallen through the floor an both run backwards.
If however its all fine for you than maybe its my end ?

https://drive.google.com/file/d/1oI8YnEm5o2KQg1K33HdDZXwUfHsu8ogl/view?usp=sharing


https://drive.google.com/file/d/1oI8YnEm5o2KQg1K33HdDZXwUfHsu8ogl/view?usp=sharing

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Great report, was able to reproduce quickly and easily:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/dd76fe97-e0c8-4bff-a3b2-433a5453e2ae)

Stand by...

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed for the next EXP build :)

**Comment by synchromesh62** [comment]
> @synchromesh62 Fixed for the next EXP build :)

Hi Lee Great News That now works great !!

However **Save Games** will need re-visiting at some point i fear as I'm finding a lot more things on loading a Save.
Door Blockers no longer block or not included in the save.  Some behaviours do not work ( or do not reset ) , Things become solid that are set to **Do Not Show** ( still hidden but solid )

I'm trying to go through it all now to make some kind of report that will make sense :(
