### ISSUE TITLE
Big Lag/Performance Issues After Newest Update

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5391]
Last night I was working on a level, everything was fine, Max was running smooth.  I open my project tonight, download newest update, and its now Max is running really bad. Completely locking up and freezing in editor and Test Game. Like it even hangs when I try and start a Test Game. 

I saw CPU spiking to over 100ms in the profiler when it freezes. I tried turning off the Culling cause the patch notes said more updates with that but turning it off did not help at all.  Not sure what else changed in the newest update but something is broke.

**Comment by OldFlak** [comment]
Yes, I be seeing frequent random 1-5 second lock-ups, at least every 5 seconds since todays update 
- Was not an issue at all yesterday 
- opened same map that ran a smooth as silk, but today frequent lockups, did not make any changes, tis just busted today
- fps doesn't change it just freezes at 60 fps
- disabling culling makes no difference

**Comment by extremestrategy** [comment]
Similar problem here, every few seconds my game locks up, and my FPS plummets from 70-80 down to 20-35, and then bounces back up, tried disabling culling as well, and it didn't help.

**Comment by plemsoft** [comment]
Also see this , @LeeBamberTGC is working on some thread optimizing, but one of the lines ruin wicked job system.
FYI: SetThreadAffinityMask(GetCurrentThread(), 1); , removing it makes everything normal again :)

**Comment by LeeBamberTGC** [comment]
@plemsoft Sorted for next EXP build, and in fact the modern recommendations are to leave thread management to the OS these days, gone are the days of controlling the fate of each thread :)

**Comment by OldFlak** [comment]
@plemsoft @LeeBamberTGC - thanks guys :)
