### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5395]
After saving the game and reloading it goes to 4 ( FPS )  

![Uploading Screenshot 2024-03-24 110711.png…]()

**Comment by SampeyFS** [comment]
![Screenshot 2024-03-24 110711](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/c5d9ffaa-babe-42c7-ac09-15dcd0c63ed7)

**Comment by davetgc** [comment]
So, this is your game that have the problem?

**Comment by SampeyFS** [comment]
yes when loading the save it does 4 FPS

**Comment by davetgc** [comment]
As I've mentioned before, we'll need copies of your levels to test out why this is happening, there's nothing we can do from a screenshot. Are you able to upload them somewhere (including any media) to share privately. ? (Don't post a link here), but you can contact me on Discord.).

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks for sending the standalone game. I also could not get the FPS down to 4fps after saving a game position near the horse and reloading.  I can tell from my FPS however that the level is somewhat intense and might produce some performance issues on certain systems:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/265d0dff-b024-4a6c-8209-457441e6883c)

Can you post your system specs (CPU/GPU/storage/etc), thanks!

**Comment by LeeBamberTGC** [comment]
@SampeyFS Do you mean when I first started the game, the fade-in sequence was REALLY SLOW (almost looked like it paused/frozen for 10-20 seconds) and then resumed normally after that?

**Comment by SampeyFS** [comment]
yes

**Comment by SampeyFS** [comment]
the problem comes from the items.tsv files

**Comment by SampeyFS** [comment]
he managed to understand the slowdown at the beginning of the game @LeeBamberTGC

**Comment by SampeyFS** [comment]
ah understood, let's hope for a solution

**Comment by SampeyFS** [comment]
good morning lee is there any word on the slowdown?

**Comment by LeeBamberTGC** [comment]
@SampeyFS For the next EXP build I have adjusted the shop item system so the objects are only cloned for the shop you open, so this way you can spread the items around various stores and traders to reduce the clone hit:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6b7e04c6-1220-4e4c-8bec-f4b971c552bc)

It also means there is no item cloning when the game first starts :)

**Comment by SampeyFS** [comment]
Thank you very much hopefully now I will try my team thanks you

**Comment by SampeyFS** [comment]
Perfect now will you also put the quantities of products ?

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b0d80272-656d-443f-b3e8-f19ef3fe2034)
@LeeBamberTGC  several lua errors come up like this one I don't know if it depends on that or on other updates

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/3b19fea0-1b98-4974-9f8a-e0cfb55df43d)

**Comment by LeeBamberTGC** [comment]
@Necrym59 Looks like a script issue with QUEST GIVER.

**Comment by Necrym59** [comment]
No errors found in the quest giver - i suspect this is related to all the other errors encountered since the last build, i told Sampey in the other thread the procedure to try to fix it, and if it persistes to supply a test map with the problem, I cannot chase the wind from screenshots im afaraid.
