### ISSUE TITLE
GG Max - EXP - Bug -  Character Attacks and Clones 

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5399]
Has something been changed with the Character Attack or clone behaviour.
I have a level that i use to test the cloning system.
This level was working perfect a few weeks ago.

The level uses the clone script. It turns 1 enemy, into 10 enemies.
Now after testing this level, i find that some Characters Attack, and Other Characters just ignore me.

So this means that some clones attack, and other clones do not attack.

I have tried removing Character Attack and re adding Character Attack to the character i clone.
I have tried removing Clone Script, and re adding Clone script.
Saving everything..

Still has the same thing, Some Attack, and Some ignore.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Can you attach a small level using stock media so I can trigger the cloning and see the behavior issues, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC 
The level i am having problems with is a test level, but i have used quite a bit of non stock media, so am finding it hard to be able to send this to you.
With it only been a test level for testing new stuf etc, I will wait now until you release the new Projects system, and create a new Test Game, that only uses Stock media, so then when i notice bugs on it, and can easily send it to you so you can look at it.

I will try to create a Test Game (using only stock media) that tries to use most systems in Max. This way when updates happen, we can find out bugs quickly, and i can easily send you everything etc

**Comment by Tum1370** [comment]
AM closing this issue as the newer issue on the latest MAx version is very similar
