### ISSUE TITLE
attack go into wall in third person view

### ISSUE THREAD

**Issue by Raj898** [TheGameCreators/GameGuruRepo#540]
When use third person for game. the player can not jump through wall and can attack through wall.

https://vimeo.com/342885903

**Comment by LeeBamberTGC** [comment]
@Raj898 If you had a character who would 'stretchy armstrong' a long arm and a fifteen foot sword forward, it WOULD go through a wall (and pretty much anything else). Can you specify which characters you notice this happening, thanks!

**Comment by LeeBamberTGC** [comment]
There is another issue related to this which I have marked as a ENHANCEMENT with the ability for characters to detect their visual bounds (even when animating) and apply collision so geometry is not intersected. An alternative is to have additional animations to trigger when facing a wall but this strays into artwork more than coding.
