### ISSUE TITLE
Characters aren't falling to the ground correctly when placed up in the air. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5400]
Characters/Enemies used to fall to the ground immediately after being spawned in if they were high above the ground. Now however if you place an enemy up in the air they just stay up in the sky and do not fall to the ground as you would expect. 

https://www.youtube.com/watch?v=W7TOykSqQJc

**Comment by Blood-Moon-Interactive** [comment]
Confirmed

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you tell me which version (from the Steam beta tab) shows the character falling to the ground when placed in the air?  It's not something I have tried as the character needs to associate with the nav mesh when the level starts.

**Comment by Kitakazi** [comment]
@LeeBamberTGC I can check the steam versions when I get home but I wont be back for another day.
However I know about 3 months or so ago something definitely changed. I had this section in a level where an enemy all comes crashing down through the ceiling while playing a falling animation and it looked really cool. Then roughly 3 months ago I noticed when that enemy would spawn he would play his falling animation before actually falling to the ground. Now he does not fall to the ground at all and stays stuck in the air. 

https://youtu.be/R2HvfWJPowA?si=4jPQrLAdc6JQ4eqb&t=136

at that time stamp you can see the ceiling sections falls and then about 1-2 seconds later the enemy falls to the ground. He used to fall at the same time the ceiling did. Now he just stays stuck up in the air.

**Comment by Kitakazi** [comment]
@LeeBamberTGC - alright you should be able to just go to the 2023.12.18 build. In this build the characters fall to the ground pretty quickly after being spawned in. Although there is still a very small delay before they actually become affected by the gravity. 

https://youtu.be/oydXY-aDpcw - this is from the 2023.12.18 build

**Comment by LeeBamberTGC** [comment]
@Kitakazi Thanks for confirming when the change happened. Turns out it was a performance optimization that prevented extra ray checks, but also stopped characters taking advantage of gravity. Added some "warmupcharacteratstart_f" magic to allow characters to fall from grace in the next EXP build.

**Comment by Kitakazi** [comment]
@LeeBamberTGC Awesome! Thank you sir I appreciate it.
