### ISSUE TITLE
BUG - Elevator is out of order

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5402]
In the video I will demonstrate that there is a problem with scripts that include the function to reset player position, such as elevator and zip line. The levels depicted in this video were made roughly 1 week ago and the behavior moved smoothly at that time. When speaking with Necrym he suggested the issue may have to do with the following:

```
SetFreezePosition(g_PlayerPosX,(g_Entity[e]['y'] + 38), g_PlayerPosZ)
TransportToFreezePositionOnly()
```

https://youtu.be/FbMIN9XGsKc

**Comment by Necrym59** [comment]
Yest those commands seem to be broken or not working correctly at present in this build, and they were working perfectly in previous builds

**Comment by LeeBamberTGC** [comment]
@Necrym59 Can you attach a stock level that uses a built-in script that shows this in action. I recently moved the physics calc to a separate thread for performance reasons and I suspect this has desynced the effect. Hopefully there is a solution that keeps the performance boost without reverting to the old way.

**Comment by Necrym59** [comment]
[MoveTests.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14764933/MoveTests.zip)
Sample map showing a few of the objectes effected
Ladders, platforms, ziplines, elevators.
Sometimes when you set a platform to 'always active' it works, but this doesnt work on ziplines or ladders

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Fixed for the current EXP build.

**Comment by Necrym59** [comment]
Still definatley somthing not right in there Lee especially with ladders and the zipline, lots of jitterey y movement
https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/8eb57a85-d08f-4070-b3f5-02ab896f564a

**Comment by Necrym59** [comment]
And the train one i was working on was perfectly smooth and is now broken as well with the jitterey y movement
https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/3c7aab30-7454-42b7-a00a-cce9b1613223

**Comment by LeeBamberTGC** [comment]
@Necrym59 No worries, I will add some code to the next EXP along with a new command called "SetPriorityToTransporter(e,1)" that will instruct the engine that the entity running the logic NEEDS to be updated every cycle, in case the user does not tick always active in the properties.  Alas I had to update every script that used "TransportToFreezePosition" so you might want to check the GitHub commit to show which scripts you need to update on your local PC to stay with the latest versions.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/496a22b2-3398-471c-94b1-15d9f8d30ff6)

There may still be an issue with the physics code itself (noticed player can 'sag' when staying half way up a ladder and moving along zipline, not related to logic calls, so not calling this fixed as yet :)

**Comment by Necrym59** [comment]
Ok Lee downloading and looking at them now
Why was winkill on that list it wouldnt use the new command??

**Comment by LeeBamberTGC** [comment]
@Necrym59 I gobbled a line from the script, no biggy :)

**Comment by LeeBamberTGC** [comment]
@Necrym59 Uploading new EXP build now - all working again :)

**Comment by Necrym59** [comment]
Ok cool i will wait for the update and check them all out and any others :)

**Comment by Necrym59** [comment]
Seem all is working smoothly at the moment Lee 
still having a smal problem with the train im working on but i will deal with you seperatley on that one.

**Comment by Blood-Moon-Interactive** [comment]
Confirmed the elevator in my level is back in service.
