### ISSUE TITLE
GGMAX Question - Mineral Textures 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5403]
I made the minerals for the mine in format ( DDS DXT 3/5 ) I also tried with PNG but I don't know if I'm wrong because when I export to Standalone it doesn't extract the textures of the ( Minerals )
Format tried

DDS DXT 3     

DDS DXT 5

PNG

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this.

Please let me know by replying to this issue and I will investigate further.
