### ISSUE TITLE
Cannot Create Standalone

### ISSUE THREAD

**Issue by ArmedAndHammered3** [TheGameCreators/GameGuruRepo#5405]
The latest update broke the ability to create a standalone copy.

**Comment by TenebreGaming** [comment]
I too tried to build a standalone and MAX crashed at 1%.

**Comment by ArmedAndHammered3** [comment]
This is basically the only function that the game engine must have and it does not work. Cant be the easiest game maker on the market if you cannot even export a game.  Btw its been broken way longer than the time this was originally posted (9hrs ago) and has not even gotten so much as a label yet.   Let me suggest one...BUG,   High,,, Needs Immediate Attention (Highest Priority).

**Comment by synchromesh62** [comment]
> This is basically the only function that the game engine must have and it does not work. Cant be the easiest game maker on the market if you cannot even export a game. Btw its been broken way longer than the time this was originally posted (9hrs ago) and has not even gotten so much as a label yet. Let me suggest one...BUG, High,,, Needs Immediate Attention (Highest Priority).

Remember your on the EXP build which is a Dev Test build. Things will break in the process and be rectified asap.
You really shouldn't be using the EXP unless your ok that this can happen. 
Test and Report is what its all about.

**Comment by SampeyFS** [comment]
this has already been reported

**Comment by ArmedAndHammered3** [comment]
@synchromesh this is on ALL Builds not just the EXP

**Comment by synchromesh62** [comment]
I did not add any false info i was just referring to this comment.
**" Cant be the easiest game maker on the market if you cannot even export a game. "**
I did not even say you were incorrect as this was already reported in the Latest EXP update in the last 12 hours but has not in the Retail which i also swap between and had to use to create my standalone yesterday. 
All i meant was as long as the retail works its not a big panic because it has not been looked at in the last 9 hours.
However apologies you took it that way and i will avoid any comments in the future.

**Comment by ArmedAndHammered3** [comment]
@synchromesh62    "Remember your on the EXP build which is a Dev Test build. ( Not the Retail )"   <----- This looks like an assumption to me therefore False Info added to my bug report. **I just simply don't understand why I can't post a report and Not have anyone try and place the blame on me.** I apologize again but **_this isn't a debate it's a bug being reported_**. It is cut and dry, solid info placed here for the Devs to look at, nothing more than that. **If you are not a Dev currently working on the game engine there is no need to try and pull attention away from what was reported.**  I cannot express this in any other way, shape or form.   It's broken, needs fixed, I reported it, end of story.

**Comment by ArmedAndHammered3** [comment]
Good thing I took screen shots of the missing comments above as well as the other ones that for some reason do not even show they were ever posted or deleted. **One might think I wouldn't be able to solve this Scooby Doo Mystery.**   **Looks like 3 of us have been censored and the 4th completely erased from the logs * I feel I am not going to get any help here if comments are being selectively deleted so I will just withdraw my report entirely.  Good luck with your future endeavors and editing operations.
Kirk Out!!!
