### ISSUE TITLE
Accept DLC Hud Problem

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5406]
![Screenshot 2024-03-27 144433](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b6a09ed7-dcf0-4c90-aa43-abc31e2349b3)
![Screenshot 2024-03-27 144328](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/dbf5b4ed-62fd-423a-86c9-9dc8756a7f6f)
![Screenshot 2024-03-27 143936](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/47753747-d807-444b-b6d4-1d79df68d082)

the axe does not take the hud and picks up problems in the shop as you see in the photos almost all do so

**Comment by Necrym59** [comment]
So you mean the icon you save as the collectable icon image is not being used is that what your saying?

**Comment by SampeyFS** [comment]
Yes, almost all of them do this

**Comment by SampeyFS** [comment]
https://youtu.be/94dcCFGumng  Compass problem Full HD

**Comment by SampeyFS** [comment]
https://youtu.be/94dcCFGumng Compass problem Full HD

**Comment by synchromesh62** [comment]
@SampeyFS 
Why are your shadows glitching so much ?
This also seems to be effecting your navbar.
I don't see any of that.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/5b566770-dbb1-48a3-bdcf-7916f49f0c48

**Comment by SampeyFS** [comment]
Yes, I solved the (bar) issue
