### ISSUE TITLE
GG Max- EXP - Fires gun when trying to select / use something in the inventory

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5407]
As the title says.
Max now fires your gun when you try to select (left click) an item in your inventory.
Will also fire your gun, when you left click the USE button in inventory.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Fixed for next EXP build :)

**Comment by Tum1370** [comment]
@LeeBamberTGC I can now confirm that this bug has been fixed, Thank you for the fix.
Ill now close this issue.
