### ISSUE TITLE
Gioco Crash Test

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5408]
From yesterday's latest updates max crashes while you are testing in your example project (you stop with the horse) sometimes fish.lua errors etc. come up on their own
![Screenshot 2024-03-27 202044](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/76996370-93e9-463a-b8ca-fe874aa59baf)

**Comment by SampeyFS** [comment]
This lua error also occurs with other quest lua scripts and others

**Comment by SampeyFS** [comment]
from the latest updates it crashes when you get on the horse and stop @LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@Necrym59 Any clues what this might be?
@SampeyFS Can you reproduce this with a blank level using only stock media and stock scripts?

**Comment by SampeyFS** [comment]
Captain alone we did not touch anything

**Comment by SampeyFS** [comment]
I tried with the horse in an empty level it crashes when you get on sometimes when you press S

**Comment by SampeyFS** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/56064540-2674-45e0-9d97-063f6bc360af

This also happens with the horse from yesterday before it was going S and crashes watch the video from yesterday before it was fine

**Comment by synchromesh62** [comment]
@SampeyFS 
You stated above .. **" This lua error also occurs with other quest lua scripts and others" **
Can  you name one of the stock ones that gives you the error. 
Lee does not have your Custom script or horse but can check the stock ones that give the same error that also need to be fixed.

**Comment by SampeyFS** [comment]
Yes I tried but I can't reproduce the errors only the lua error horse as you see in the video

**Comment by SampeyFS** [comment]
I've updated the scripts from the work shop, it doesn't seem to make these errors anymore, only the horse makes them when you just stop

**Comment by synchromesh62** [comment]
> Yes I tried but I can't reproduce the errors only the lua error horse as you see in the video

That being the case then only Necrym59 can really help as Lee has no knowledge of the script he created for you.
He does not come online till evenings.

**Comment by Necrym59** [comment]
The horse isnt my script, i didnt write it, i supplied it to you when you kept asking for it, i will have a look at it a bit later, i have a lot im doing just at the moment. 
Does removing the horse stop all the other errors? If so just remove it until i get a chance to look at it.

**Comment by SampeyFS** [comment]
![Screenshot 2024-03-28 182429](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/ff36133c-71ca-4d27-b1c8-d86b60c192b0)
I tested the empty level without getting an error (lua) but in my game I managed to figure out how this error happens. It happens when you open a door, enter the shop, get on the horse and it has happened to me many times as you can see in the picture when you open the ( Shop ) these errors appear (( I don't know about lua but I suspect this ))


See you enter the lua error shop

**Comment by SampeyFS** [comment]
yes indeed I had thought of removing it quietly I am in no hurry

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/d684756d-c233-4b39-a8fa-f6c6c6e01256)
It doesn't hit the horse as you can see, the owner does it when he removes it when he opens the shop after the modification which actually happens @LeeBamberTGC

**Comment by Necrym59** [comment]
I can find no errors, these scripts havent changed, i suggest you redownload a fresh version of GGMAX and the workshop or perhaps roll back to a previous version, then see if the problems persists, your images dont show what is happening and under what circumstances. You even said yourself that the errors started after an update so i suspect that shows where your problem lies.
Please also create a simple new test map where the specific error occurs and supply it so we can find out if there is a problem.

**Comment by SampeyFS** [comment]
Where can I find the work shop folder?

**Comment by Necrym59** [comment]
Just update the workshop scripts from the hub, but you should do a complete steam verify of max first

**Comment by SampeyFS** [comment]
I did everything I was told but every now and then error lua is still written I reinstalled max and also workshop but nothing when it happens randomly for example open a door but above all when you open the shop

**Comment by Necrym59** [comment]
Try deleteing your 'collection - items.tsv" file and let it rebuild and see if it happens

**Comment by SampeyFS** [comment]
OK OK I'll try thanks

**Comment by SampeyFS** [comment]
This also happened in an empty level same lua errors happen randomly difficult to reproduce I think it's a problem yes (( MAX ))

**Comment by PetrNaj** [comment]
> This also happened in an empty level same lua errors happen randomly difficult to reproduce I think it's a problem yes (( MAX ))

I have the same problem. Random Lua script crashes after recent updates. It's fine in the March version.

**Comment by SampeyFS** [comment]
yes exactly

**Comment by LeeBamberTGC** [comment]
@PetrNaj Can you attach a stock level that shows the "Random Lua script crash", thanks!

**Comment by SampeyFS** [comment]
These are causal crashes, it happened to me with the RPG scripts ordini.lua, fish.lua, NvBar.lua, Door.lua Question .lua, day_night.lua basically all RPGs but not all together but every now and then one in twenty (details) example open the shop door and start the Level test

**Comment by PetrNaj** [comment]
It's related to the distance.???

I'm getting errors with the doors.
Mostly 'door.lua', but also 'key.lua' and 'switch.lua'

Door.lua' returns an error on line 48.
"48...   if door[e]['range'] == nil then door[e]['range'] = 70 end"

key.lua returns an error on line 33.
33    if key[e].associatekeyatstart == 1 then
34		PerformLogicConnectionsAsKey(e)
35		key[e].associatekeyatstart = 0
36	 end


I had 'always active' checked for one distant monster. After unchecking it, the errors disappeared.
 I also noticed cursor and text flickering when the distance is greater. See the video.
(Sorry, my English isn't good)

[new video](https://www.youtube.com/watch?v=-8UTWZ2yrkc)

**Comment by LeeBamberTGC** [comment]
@PetrNaj I created a fresh level and dropped in a key, no crash when run:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/051345bc-4a0a-4daf-afdb-f1d94b4de070)

**Comment by PetrNaj** [comment]
Sorry. I don't speak English :(  I rely on the help of relatives and Google Translate.

I tested and searched for the cause of the errors.
I found the cause.
I need an explanation

Where can I send the level with the "error"?

**Comment by SampeyFS** [comment]
This problem is now present in the game exported from standalone and is spreading. Please solve this problem @LeeBamberTGC

**Comment by SampeyFS** [comment]
![Screenshot 2024-04-16 101743](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/19a5ea17-bd53-473b-8c39-49fcb04c811a)
Game exported with (standalone) lua error yes very frequent now the game time returns to 6 after loading the game save

**Comment by LeeBamberTGC** [comment]
@Necrym59 Did you have a hand in helping make the fish behaviour, perhaps you can find the cause of this script instability?

**Comment by SampeyFS** [comment]
it's not just that there are many scripts that come out it's written Fish.lua Resources.lua,Food .Lua they sell out randomly both in max and in games exported with standalone they don't work when loading the save the door.lua and light scripts

**Comment by Necrym59** [comment]
I didnt do the script initailly its Amens one i did make only the adjustment to allow for truning off the Randon sizing
however please try this one Sampey and let me know if it works
[fish_v4.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15004293/fish_v4.zip)

**Comment by synchromesh62** [comment]
@SampeyFS 
I just tried all the fish and all seem fine here ?
Do you have any other custom fish related scripts you are using in your RPG ?

**Comment by SampeyFS** [comment]
No No but as I said it's not just this one (Fish script) but many as I said last time now I'll give you the project try it

**Comment by Necrym59** [comment]
No the scripts work fine there is no instabilities or errors that can be repeated i suugesst you check your prject thourougly for non stanard scripts and delete them one by one to find the cause

**Comment by SampeyFS** [comment]
the only custom script is this fade corpses.lua makes dead npcs/animals disappear, the rest is yours

**Comment by SampeyFS** [comment]
[Lista script The Hermit.txt](https://github.com/TheGameCreators/GameGuruRepo/files/15007440/Lista.script.The.Hermit.txt)

**Comment by Necrym59** [comment]
Remove any 3rd party scripts first, then test, if any more errors note them down including the error then remove the one that gives an error and continue to do this until no errors occur. This is the only way to isolate which one (if any) is giving a problem.

**Comment by SampeyFS** [comment]
is the flame torch script missing from your scripts?

**Comment by SampeyFS** [comment]
let's remember the problem with util lib.lua, I reported it when the problem was closed  @davetgc

**Comment by Necrym59** [comment]
There is no Flametorch script

**Comment by PetrNaj** [comment]
> Sorry. I don't speak English :( I rely on the help of relatives and Google Translate.
> 
> I tested and searched for the cause of the errors. I found the cause. I need an explanation
> 
> Where can I send the level with the "error"?


The scripts are working well.
Why isn't anyone listening to me?

**Comment by davetgc** [comment]
@PetrNaj - If the scripts are working well, what is the problem? Several users,  including members of the development team have tested the reported errors, and the issue can't be replicated, which makes it difficult to fix it.

If you need to send a sample level, you can email it to Lee@thegamecreators.com with a reference linking to the relevant Github post.

**Comment by PetrNaj** [comment]
My level exhibited the same script errors as SampeyFS.
I've been searching for the cause.
The errors were showing up with doors, and various scripts.... key.lua door.lua hurt.lua
By gradually deleting, I ended up with furniture, doors, and an enemy.
I tried to replicate the error in MAXOV, but I couldn't. The errors only occur with imported objects.
For me, the issue arises with furniture, but only if set to polygon collision and an enemy is present on the map.
If I set the furniture to hull collision, everything is fine.
I don't know. I don't understand it.



NO ERROR
----------------
![7](https://github.com/TheGameCreators/GameGuruRepo/assets/129626644/5cfdb3f1-742e-431e-82c4-62d67e51b717)



ERROR
-------------
![1](https://github.com/TheGameCreators/GameGuruRepo/assets/129626644/226db85a-3a58-4db6-8758-e1809c1dc34f)
![8](https://github.com/TheGameCreators/GameGuruRepo/assets/129626644/577383f4-1eb3-4fae-a4bf-c8cbf95a5429)

**Comment by davetgc** [comment]
@PetrNaj - Interesting. Could you please email the object causing the crash to @LeeBamberTGC, and mention this GitHub issue in the email. Thanks.

**Comment by PetrNaj** [comment]
Sent.

Addendum:  The errors appear sometimes immediately and sometimes even after 2 minutes

**Comment by SampeyFS** [comment]
It seems that the scripts are unstable when the game is extracted with standalone, the game presents an error when saving with the utillib.lua script, try @LeeBamberTGC

**Comment by SampeyFS** [comment]
yes

**Comment by PetrNaj** [comment]
> @PetrNaj The "Ancient S_doorframe03_fbx.dbo" model was missing from the entity you zipped and sent, can you send that also, thanks. I tried the door object which did load fine, and attached a door rotate script and set up the object so it would stay put and all was fine, no crashing, even after 2 minutes: ![image](https://private-user-images.githubusercontent.com/35840583/324450962-4fdf23fe-8cd7-45ca-8e36-608c2f5d3f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjY4NDIsIm5iZiI6MTcxMzg2NjU0MiwicGF0aCI6Ii8zNTg0MDU4My8zMjQ0NTA5NjItNGZkZjIzZmUtOGNkNy00NWNhLThlMzYtNjA4YzJmNWQzZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MDM1ZGRjMjJjMTg5MTAyYWFjN2U5NzUzMjY2OWUxOGI0YzY3OWQxZDI2NTQyM2QwNGI4Y2U2NzRlOWM5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1FG0c1AE0drrOF2vQd6pCUDalCYSS1EPGvKwPFxmC9I)

My mistake! Sent again.  
"Yes, the doors are fine. The doorframe is causing the error. Check the settings, see images."

**Comment by SampeyFS** [comment]
Xk It has been closed, the problem is not solved, are things still closed randomly??  @davetgc

**Comment by Necrym59** [comment]
@SampeyFS You have been asked repeatedly for more information and responses from previous attempts to help and you never respond so it was closed. Even yourself said it seems to be a particular model as the cause. Please be more specific and respond accordingly we cannot guess things by just images, you need to supply detailed reports and do everything asked of you and to respond with the results.

**Comment by SampeyFS** [comment]
These lua errors now occur a lot when loading the save, in fact some lua don't work when loading the save so lua errors appear when loading the save

**Comment by davetgc** [comment]
@SampeyFS - Lee asked if you can reproduce this error in a fresh build? Can you answer please.

**Comment by SampeyFS** [comment]
In what sense is the update still being done?

**Comment by SampeyFS** [comment]
if you ask me with the update it was fixed it still doesn't do it when you export the game with (standalone) when loading the game lua errors occur or it doesn't load them

**Comment by davetgc** [comment]
@SampeyFS - I'll ask again, can you reproduce this with a new level?

**Comment by SampeyFS** [comment]
I'll try and see :)
