### ISSUE TITLE
Global.lua error

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5409]
![Screenshot 2024-03-29 135645](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/52518795-9224-4402-abd2-9e28ce17f9b7)

This morning I started the project and this error arrived which should concern play

**Comment by LeeBamberTGC** [comment]
@SampeyFS This relates to a call to GetPlayerDistance( e ) from another script where there is no entity created. See if you can find out which script is calling GetPlayerDistance with a bad entity value.

**Comment by SampeyFS** [comment]
I found thank you very much
