### ISSUE TITLE
NavBar Distance problem

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5410]
https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/23831119-31c8-4e75-9d22-58fe65d36693

**Comment by Necrym59** [comment]
It works as far as i can tell, that grainy video isnt clear and doesnt explain the problem, you have to supply details more clearly or we cannot help you

**Comment by SampeyFS** [comment]
When you are far away it flashes as well as being active
