### ISSUE TITLE
I have double scripts?

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#5411]
Hi
         I have 2 issues really, so I'll start with the scripts one first.

When I ever want to add a behaviour, I seem to have two versions of the same script. So do I delete some and if so which do I delete and which do I keep? (See Screen Shot.
![Screenshot 2024-03-31 002941](https://github.com/TheGameCreators/GameGuruRepo/assets/104730909/54ff48db-32de-4a86-9293-364f3424ad6d)

Also when I try and add something as a collectable, I tick the box that its collectable, but as soon as I go to the create collectable, It crashes back to desktop everytime. Any ideas?

Cheers in advance

**Comment by SampeyFS** [comment]
Something broke :-)

**Comment by synchromesh62** [comment]
@Curiosityuk 
Perfectly normal don't delete any.
The ones with ( Necrym59 ) are in the Workshop and are optional as they are updated live and likely to be newer versions or fixed versions if that was needed..
The ones without are stock the current stock behaviours.

@SampeyFS No nothing broke. :)
Meant to be that wau

**Comment by Curiosityuk** [comment]
> @Curiosityuk Perfectly normal don't delete any. The ones with ( Necrym59 ) are in the Workshop and are optional as they are updated live and likely to be newer versions or fixed versions if that was needed.. The ones without are the current stock behaviours.

Ah right, I suppose that makes sence. Thanks for the reply (y)
