### ISSUE TITLE
New command that allows greater distance checking when needed

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5412]
It looks like latest builds have altered the PlayerDistance check to a limited distance that really makes it only useful for doors?

Can we have a new command that allows greater distance checking when needed.

I have a couple models - a perimeter fence and shield  - that are quite large, and are activated based on the players distance to each one.

They worked fine previously - but now MAX does not to detect them till the player is way past the boundary of the models - so the whole idea is tanked :)

Zones are not an option because:
- as always, they are finicky at best, unless they are left as standard shape, on flat surface, and not near any locked object
- the perimeter fence 'reacts differently depending' on the players distance to it

Thanks for considering

**Comment by OldFlak** [comment]
This is how it used to work:
https://youtu.be/edp_yFPLmAI

But now distance check does not kick in till around 400 from center point of model.
 The model is 2600 diameter, and the distance check is set to kick in as 2700.

**Comment by OldFlak** [comment]
BUG not enhancement - this has been broken, by recent updates, so any recent work has now broken it....

**Comment by LeeBamberTGC** [comment]
@OldFlak Any logic-connected objects are now always handled, irrespective of distance.  If the object is a standalone, you can set the Always Active flag to ensure distance is not a factor when running its logic.  In the next EXP build.

**Comment by LeeBamberTGC** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2486707d-3244-402b-87d4-273c801b69c9)

**Comment by LeeBamberTGC** [comment]
@OldFlak Can you not use "Always active" on and then quickly reject further logic given a distance you provide via DLUA?

**Comment by OldFlak** [comment]
Yes - that be what I am doing now - just wondering if there is any advantage in the engine doing the check (as it was before) rather than via lua was all?
