### ISSUE TITLE
MAX - EXP - MAX Gets Model Orientation Confused

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5413]
This has been an issue since MAX went to over to Assimp - but thought it about time to report it.

It seems MAX gest confused as to the actual orientation of a model. You can see this when you put an entity in the scene and then rotate it, MAX will adjust it to its correct orientation. Here be an example using couple stock models:
https://youtu.be/Gty2WT4mQWg

This is also seen when getting objects to move via lua. Which is when it also becomes more of an issue, than an annoyance.

Sometimes when you edit the item via the properties bar and then run the level it will travel in the wrong direction. To fix you just have to rotate the object a few times so MAX can again work out the correct orientation.

Thnaks for checking :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Nice find, the orig quat was empty when dragged in and ignored the initial state, sorted for next EXP build.

**Comment by OldFlak** [comment]
This issue is sorted - thanks @LeeBamberTGC
