### ISSUE TITLE
Add automatic backup after each save to allow older levels to be recovered in case of FPM file disappearance/corruption

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#5415]
After opening a map (Test1A.fpm) and removing a zone that no longer had a connected behavior then saving the map back it crashed Max. Upon trying to reopen that map - the whole **map file no longer existed** even though the map thumbnail 
 reference existed in the storyboard, it just loads a default map.
![map1](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/cd85bd3c-1410-4c4c-af03-6d320e8b5e12)
(i have now no way to do a repeatable test if this  reason/scenario of Max crash above as the map file (Test1A.fpm) has now dissapeared into the ether, i am just left with these two files to console me.
![map1a](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/d7ab71d1-f16e-42dd-a0f6-c1639e938f0b)

The point being is the map was entirely lost. Max needs a simple auto backup system when opening a map for editing;- 
It needs to create a '.bak' file of the map when opening, as standard routine just in case this happens for whatever reason.

**Comment by synchromesh62** [comment]
In Classic we had a **.bak file** you could rename if you lost or messed your maps up which I requested back then from my experience with GTK Radiant and Quake mapping days and it was a very handy thing to have.

I think if there is **any possibility** Max can totally lose a map from the GameGuruApps folder this would be a welcome feature and one small step for a little peace of mind.

**Comment by Necrym59** [comment]
Losing maps has happened again to some people, this really need to be addressed a simple bak file creation before editing a map would be the best solution rather than losing it altogether.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Can you make a small video from scratch showing a game project being created, then a level, then saving the level, then showing the level as not existing in Windows Explorer?

**Comment by Necrym59** [comment]
@LeeBamberTGC  Sorry Lee, its  impossible to do this it has no modus operandi it was a random event for me as shown above, somthing happened when saving the file and it just left nothing, it hasnt happened before or since (so far) so its not really somthing i can repeat except by accident. I have since deleted those remaining files and moved on but others may have evidentry files. Others have had this happen apparently the same way appently:
**A post from Mav3r1ck1981:** ..thats another level with hours of work in thats disappeared. the fpm is now 1kb, sick to death of this now, the fpm is there, but only contains 1kb of data (previously it showed 79,000kb) the LST file lists all teh included assets in the level, but when i open it up its a blank map_

**Comment by LeeBamberTGC** [comment]
@Necrym59 As you say, in place of being able to reproduce, I will add a system to backup after every save so everyone has plenty of backups to return to if the worse should happen.

**Comment by LeeBamberTGC** [comment]
NOTE: There is another little documented feature that makes a local backup everytime an FPM is saved, making a copy of the version of the FPM file and renaming to ti a BAK file before the new FPM is overwritten. Open SETUP.INI and change "editorsavebak=0" to "editorsavebak=1" and save.  Now all your FPM files in MAPBANK will have a BAK file representing the previous instance of that FPM level.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Added for the next EXP build, just check out the newly created _automatedbackups folder. It will track the last ten versions of any FPM file saved, allowing plenty of versions to find the older level that avoids corruption or bad decisions (or files suddenly disappearing) :)
