### ISSUE TITLE
Loading screen shows then crash out immediately

### ISSUE THREAD

**Issue by MarioFe72** [TheGameCreators/GameGuruRepo#5416]
Hello. Having trouble getting Max to run. I have an AMD RX6600XT and after starting the max loading screen is displayed and then I go straight back to Steam. This has been going on for months. The workarounds don't help either. Are there any other tips?

**Comment by LeeBamberTGC** [comment]
Properly fixed now for next EXP build - was RSSetScissorRects and a recent AMD driver update!  Try the EXP build and let us know how it goes.

**Comment by LeeBamberTGC** [comment]
@MarioFe72 The AMD fix was related to a black screen showing when viewing the level editor, this crash out report is likely something else. Can you attach here the log file you will find here: "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log"

**Comment by MarioFe72** [comment]
Hello,
I have the files in the directory \Users\xxx\Documents\GameGuruApps\
completely deleted and reinstalled GameGuru Max again. Without beta version and without experimental version. And... It's running perfectly.
Thanks and greetings Mario

**Comment by synchromesh62** [comment]
> Hello, I have the files in the directory \Users\xxx\Documents\GameGuruApps completely deleted and reinstalled GameGuru Max again. Without beta version and without experimental version. And... It's running perfectly. Thanks and greetings Mario

Ahh there is only the EXP or the Retail which are currently identical after the update Friday which has the fix in both included.
Seems likely yours did not update properly but great News the fix works.
