### ISSUE TITLE
Have Logic Connections set the connected object to always active by default

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5425]
It seems the Logic connection distance has changed and will not activate until your in range.
**The video below explains** 
2 doors 1 switch
only the first door opens 
The second will not until you get closer.
Unfortunately this breaks a lot of connections in the level.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/cf5449e0-dd24-4cdb-8c5a-81e1e7a42792

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
That just messes everything up.
Hidden doors, forcefields etc have door blockers enabled when always active. :(

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Can you send me a screenshot of "forcefields have door blockers enabled when always active", thanks!

**Comment by Necrym59** [comment]
Links should be always active or what is the point of logic links if everything is range based activation?

**Comment by synchromesh62** [comment]
> @synchromesh62 Can you send me a screenshot of "forcefields have door blockers enabled when always active", thanks!

Hi Lee
Its a case of trying to do something unique and different with the behaviours.
I am using very fast doors for forcefields ( and hidden doors ) so in this arena ( below ) you can alternate the force fields.
**Great fun in battle** 
Not only does **always active** break then from alternating .. When hidden the blocker is still visible as the pic at the bottom shows so it just kills the whole level and other setups i have further along :(

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/ed3b5bda-4eb2-49ba-a3f1-ba030a352d0e

![FF](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/c4e2fe4d-70f0-4727-aa86-0094d0fef820)

**Comment by OldFlak** [comment]
Yeah, not sure why we want anything to be always active. If set active via logic links or ifused, then it should then become active no matter how far away it is. We be going backwards it seems :)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed for next EXP build :)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 It was one of the optimizations to regulate how much logic was being processed. Turned out a compressed level had potentially hundreds of LUA logic firing all the time, and if they used ray casts, it really crawled.  Most objects only need their logic when the player is close enough to engage with them typically.
