### ISSUE TITLE
Unstable FPS after latest update

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5426]
After the last update, cases of 20-10 FPS occurred when they didn't occur before, ranging from 65 / 75 FPS in the (Full) non-empty levels, in practice the FPS drops from 75 to 45 on their own

**Comment by RogeriaEscape** [comment]
STABLE or on EXP?

**Comment by davetgc** [comment]
@SampeyFS - Please keep your performance issues to a single post. YOu can update that post with new information. I'm closing this one as you have opened a lot.
