### ISSUE TITLE
Latest update with skip hub unticked question ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5429]
Before i do a reinstall i have my skip Hub ticked so it goes straight to the default map and crashes if i try to launch.
Just checking if its now supposed to look like this ? 
Or being done away with.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/a560135a-aa8d-4d9b-bffc-0f3fcce5b2ab

**Comment by SampeyFS** [comment]
it has been solved, I reported it first :) :)

**Comment by synchromesh62** [comment]
Perfect now so i will close this one 
Thanks Lee

**Comment by synchromesh62** [comment]
Perfect now thanks Lee so i will close this one :)
