### ISSUE TITLE
Player camera shake when under entity on hill

### ISSUE THREAD

**Issue by Raj898** [TheGameCreators/GameGuruRepo#543]
player walk slow and stand next to entity the screen can shake when look around.
when player run past fast the player camera moves with player.
can hear player run sound and no player walk sound here in video as well.

https://vimeo.com/342888201

**Comment by LeeBamberTGC** [comment]
Any chance you can provide the FPM for that level as the tree is positioned just right to produce the shake, thanks.

**Comment by Raj898** [comment]
I would like to provide. after film and test the game many times only terrain now after save.
I did place tree again on new game Foliage/tree03 so you can see and place your own to test.
At first it work in third person view yes, then move player around map and use attack when use right mouse click to look near tree and start to break yes. 

https://vimeo.com/343130376

**Comment by LeeBamberTGC** [comment]
Can you provide an FPM that uses stock media, thanks!

**Comment by Raj898** [comment]
Yes here is file before I continue with level game. file is not zipped as is .fpm for you. thank you too.
http://www.mediafire.com/file/47avam20041gco6/dadw.fpm/file

**Comment by LeeBamberTGC** [comment]
Added a new command to ignore objects that animate, and also changed some aspects of the third person control system to reduce the flickering for indoor scenes. Not perfect, but getting there.
