### ISSUE TITLE
Problems with Nvidia RTX video cards at Max

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5432]
When navigating within max with the mouse and the (W) button, FPS drops occur and the program freezes, then it restarts with the FPS, for example from 120 FPS, it drops to 19 FPS then it restarts. My card is RTX Nvidia 3060 Ti 8 GB These blocks also occurred when I had a GTX Nvidia 1650, apparently problems with the video codec

**Comment by MonkeyFrogStudio** [comment]
I'm running an RTX 3090ti with no issues in the max editor at all. What's your scene like? If you have a lot of objects in the scene, then perhaps that's causing an issue when you have a lot of them on screen at the same time, etc. In any case, there does not seem to be an issue with Nvidia RTX cards in MAX.

**Comment by synchromesh62** [comment]
> When navigating within max with the mouse and the (W) button, FPS drops occur and the program freezes, then it restarts with the FPS, for example from 120 FPS, it drops to 19 FPS then it restarts. My card is RTX Nvidia 3060 Ti 8 GB These blocks also occurred when I had a GTX Nvidia 1650, apparently problems with the video codec

Mine was stuttering and glitchy and i noticed **Vsync** had been turned **off** by default.
When i re-enabled it my level ran smooth as silk ... Try that.

**Comment by davetgc** [comment]
@SampeyFS - You report a lot of FPS issues that no one else can replicate. Which leads me to think that it's related to your levels. I know you've been in touch with Lee, I'd suggest forwarding your game to him, and seeing if he can track down the cause. Remember to reference this post.

**Comment by SampeyFS** [comment]
[dxdiagreport.txt](https://github.com/TheGameCreators/GameGuruRepo/files/14893778/dxdiagreport.txt)
 Here it says it all  @LeeBamberTGC

**Comment by Necrym59** [comment]
I have 3080 RTX and have no problems whatsoever - it may be your drivers - they seem well out of date

**Comment by Kitakazi** [comment]
I have an RTX 4080 and RTX 2080 and have never had this issue.

**Comment by SampeyFS** [comment]
Problem solved I close
