### ISSUE TITLE
Test Performance Update

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5434]
![Screenshot 2024-04-07 180517](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/bc2b9725-904c-4ba5-808b-02c16e39547b)
![Screenshot 2024-04-07 180541](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/cfe49fb0-6fd7-4f26-a8ec-ec119b485d87)
![Screenshot 2024-04-07 180715](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/ee13d578-3752-401b-a82e-897e22e55ee3)

It presents problems to the Terrain as you see after your download

**Comment by SampeyFS** [comment]
@LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@SampeyFS Try new one, black squares in the terrain fixed.

**Comment by SampeyFS** [comment]
Good menu of Max 300 FPS :-) solved chudo
