### ISSUE TITLE
Craft kit does not collect

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5435]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/e70a7d8e-c4d6-420e-aa7f-a2e784a8d3c7)

https://www.youtube.com/watch?v=nJBBDn6us_8

**Comment by Necrym59** [comment]
You have to set as "Collectable" and created a collectable item

**Comment by SampeyFS** [comment]
ah ok I tried it works thanks I'll close
