### ISSUE TITLE
INFO: Old levels using old trigger zone script versions may need refreshing in the level editor to work again

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5436]
these trigger zones dont play the sound I've set to them, 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/cea8cdeb-cbeb-44a7-b155-aa647232b1c6)

ive come up with a solution of just adding sound sounds to the spot!

**Comment by Necrym59** [comment]
Why dont your use a sound zone tahts what they are for?

**Comment by Kitakazi** [comment]
I noticed after last update alot of my levels that had triggerzones the audio would no longer play in. I replaced the triggerzones with new ones and it seemed to fix. But yea it was pretty annoying having to go through and redo the zones.

**Comment by synchromesh62** [comment]
> I noticed after last update alot of my levels that had triggerzones the audio would no longer play in. I replaced the triggerzones with new ones and it seemed to fix. But yea it was pretty annoying having to go through and redo the zones.

I had this on some and found just moving the volume slider down and up again solved the problem.
Mot as nad as replacing them.

**Comment by LeeBamberTGC** [comment]
@casigus This would only happen if a really old sound zone was used in a level, and then a substantially newer one came along during an update, causing a param value to be lost/moved.  I take it when you drop in a new fresh audio zone it works first time.

**Comment by casigus** [comment]
ive got alot of zones to replace aha! ok i'll give that a goo !

**Comment by OobieDoob-Benoobie** [comment]
> ive got alot of zones to replace aha! ok i'll give that a goo !

You have no idea 😆
