### ISSUE TITLE
GGMAX Bug - Some doors are failing to run their opening scripts

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5437]
this door from the secret bunker pack doesn't appear to show "E" to open when approaching the door.

theres also no collision when the door opens so it opens right through you.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/c49321c3-8a62-4042-a49f-3b2e04945d2e)

**Comment by davetgc** [comment]
Which behavior are you using?

**Comment by casigus** [comment]
the door/key behaviour that comes with max!

**Comment by casigus** [comment]
interestingly enough this bug seams to only happen on a old/populated level! so just tried to re-create the bug on a completely empty level using only doors and a key and it was fine, but in one of my populated levels the letter just appears fine.

**Comment by casigus** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/3b251b0b-364d-4dbd-ac28-e2c31418a568)

empty level with just doors.

populated level, doors:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/a54a1912-277c-41c2-aafe-ae7c36e9c66a)

**Comment by davetgc** [comment]
Would you be able to upload both the broken and the working level please and email a link to lee@thegamecreators.com?

**Comment by LeeBamberTGC** [comment]
@casigus Can I confirm this does not happen with new creations or levels, and only to older levels that used older scripts being loaded up into an engine that has newer scripts from an update?

**Comment by casigus** [comment]
FROM what I tried this morning, its older levels that cause this correct!!!

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
