### ISSUE TITLE
'If See Enemy" In the Visual Behavior Editor doesnt seem to work correctly. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5438]
Hi, I'm working on a script where an ally character goes to a flag and if they see an enemy while walking to the flag they will stop and attack the enemy.  There are a few more parts but thats the meat of it.

I've created a simple script with the Behavior Editor and if my ally is walking to the flag and an enemy is in their vision, and in range, then I would expect If See Enemy to return a True value. Instead it returns False. 

If See Enemy works correctly if the ally is not currently going towards the flag. But once it walks towards the flag, the logic box always returns False for If See Enemy even if it should not. Maybe this is not what the command If See Enemy is suppose to do? I'm not really sure any other way to get a character to target an enemy if they are suppose to be targeting a flag and moving to it first, before searching for enemies.
[testmap.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14899055/testmap.zip)

I have attached a map with this test script so you can see what I mean.

**Comment by Necrym59** [comment]
Ive had issues with allys always following the player even if an enemy is 3 feet away and ignoring them
somthing not quite right in there.

**Comment by LeeBamberTGC** [comment]
@Kitakazi The "if see enemy" has some special code to side step the issue of their current target and also takes into account the allegiance and the range they have been given. Check out any code from masterinterpreter.lua and search for "g_masterinterpreter_cond_ifseeenemy" to see all the implied logic of doing what you are attempting.

**Comment by Kitakazi** [comment]
@LeeBamberTGC Thanks I checked out the code you suggested and I think I understand. 
Unless I am missing something obvious I believe my Behavior that I attached with the level should work. 

My ally targets the flag. So it sets the flag as usestarget ==1 while it is moving to the flag. Then the code needs to check if the ally "sees" an enemy (g_masterinterpreter_cond_ifseeenemy) If an enemy is detected within the specified view range then the logic should switch to targeting the enemy with usestarget ==2

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/aa4cda4c-c557-4b61-b203-cf94c86cdd0a)

Here you can see If See Enemy is always returning false, even though it should now be firing off as True.

**Comment by LeeBamberTGC** [comment]
@Kitakazi I checked the stock character attack logic and there is no logic path that I can see where the Ally would follow a path, as you can see the instruction is to join with the player, and not do a patrol:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/174af7e2-65df-4426-a532-deceb1a3529f)

How are you getting your ally to follow a path?

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you attach the simple custom behaviour you mentioned and I will test with an enemy and ally character using that script, and see where If See Enemy fails for an ally.

**Comment by Kitakazi** [comment]
@LeeBamberTGC Yes sir here it is.
[kita test behavior.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14968518/kita.test.behavior.zip)

**Comment by LeeBamberTGC** [comment]
@Kitakazi I created a super simple level with the enemy using character attack and ally using your test attack script. The IF SEE ENEMY seems to be working as you can see in the shot:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a2b51b45-3ea3-4b74-b08d-fdb6eafd9507)

Notice the yellow highlighted block, the only way it could get there is if IF SEE ENEMY was TRUE when the enemy walked around the wall to get to his path to follow.  My level attached.

[IfAllySeeEnemy.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14996424/IfAllySeeEnemy.zip)

**Comment by Kitakazi** [comment]
Yes that is correct. However you should put a flag down, somewhere behind the enemy. When the Ally is walking to the flag, IF SEE ENEMY will not fire off as True. Even when the Ally is looking right at the enemy. 

This whole issue is because once the Ally targets the flag, it will not see any enemies.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Can you attach a modified version of my level I have attached that shows that IF SEE ENEMY never returns TRUE, thanks!

**Comment by Kitakazi** [comment]
Yes sir here you go. Just hit play and follow the Ally. 
[IfAllySeeEnemy.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15002673/IfAllySeeEnemy.zip)

**Comment by LeeBamberTGC** [comment]
@Kitakazi Great sample level, thanks!  Fixed for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6758a204-f4ea-44ea-b562-333ffc13cb3c)

**Comment by Kitakazi** [comment]
Hey I just tested this and noticed the Ally was now seeing enemies behind walls. I put the enemy in an enclosed space on the test level and it made the Ally bug out completely. I have attached the test level again so you can
[IfAllySeeEnemy.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15017569/IfAllySeeEnemy.zip)
 see and also here is a video showing this. 
https://youtu.be/FDeWAfHptPw

**Comment by LeeBamberTGC** [comment]
@Kitakazi Not a good idea to keep calling Target Flag as it resets if already set, best to set once and then follow the target as you can see here in your modified script:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/91e1614f-f583-40d2-8a10-9415e386d5bd)

**Comment by Kitakazi** [comment]
Ah yes sorry about that! Thanks!
