### ISSUE TITLE
MAX - EXP - Toolbar Background Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5439]
New one today - Toolbar background is semi-transparent.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/1f4fa551-0f3c-409a-b72f-5b23735d094c)

:)

**Comment by OldFlak** [comment]
No matter MAX decided to change my settings!

**Comment by davetgc** [comment]
So, is this fixed? If so, feel free to close it.

**Comment by MonkeyFrogStudio** [comment]
Talked to OldFlak and it turned out that, for some reason, 'Turn Off UI Transparency' had become unticked with the last update. The question, though, is why? It didn't untick when I updated. So, why did it for him?

**Comment by OldFlak** [comment]
Ah thought I had closed this - Sorry @davetgc
