### ISSUE TITLE
Enemy body through wall when dead third person view

### ISSUE THREAD

**Issue by Raj898** [TheGameCreators/GameGuruRepo#544]
Follow game guru tutorial and add building with enemy and enemy can be seen when start.
When enemy dead the body is through wall.

https://vimeo.com/342888426

**Comment by LeeBamberTGC** [comment]
Which characters do this, thanks!

**Comment by LeeBamberTGC** [comment]
NOTE: Closing for now, maybe this was fixed a while ago now :)
