### ISSUE TITLE
Support for a "seamless visual experience" mode vs "performance" mode

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5443]
Recent builds have introduced rendering issues, where objects are not drawn fast enough for a seamless visual experience.

Models and lights popping in as this short video shows: https://youtu.be/qYQzv1PSYgQ
- this is still apparent using the highest setting in Prebens new (awesome) optimization work

Thanks for checking

**Comment by synchromesh62** [comment]
Have you tried playing with unticking things unticking things like the shadow culling or adjusting the slider ?

![slider](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/b457e93c-eaec-4f74-80cb-644c8ec9f7d2)

**Comment by OldFlak** [comment]
Tried playing with all those settings - even turning them off completely I get the same issue.
More likely to do with the range cheking stuff Lee has been doing I would think

**Comment by OldFlak** [comment]
Yeah, I just guessing of course. We did have a similar issue way way back. 
Every part of that level is made up of modular pieces. So tis not drawing them fast enough when they initially come into camera view, and of course lights popping in suddenly makes it more apparent.

**Comment by OldFlak** [comment]
The mighty Preben is onto it so closing this.
More time for projects now Lee :)
