### ISSUE TITLE
GGMAX - A problem in adding custom weapons .

### ISSUE THREAD

**Issue by UA998** [TheGameCreators/GameGuruRepo#5444]
when we are adding a GUN in ggm by following the max custom weapons guide so there is a step which says : Use the GameGuru MAX Model Importer to convert your weapon model into a DBO format ..... So i want to say that how can we convert weapon model in DBO file by using ggm model importer becz there is no option to convert model into DBO file using ggm model importer ...... PLZ help

**Comment by synchromesh62** [comment]
> when we are adding a GUN in ggm by following the max custom weapons guide so there is a step which says : Use the GameGuru MAX Model Importer to convert your weapon model into a DBO format ..... So i want to say that how can we convert weapon model in DBO file by using ggm model importer becz there is no option to convert model into DBO file using ggm model importer ...... PLZ help

Also answered your same question on Steam.
When you import any model of any format into Max it becomes a .dbo file automatically.
All you need to do is browse to your imported folder and you will find it is now in a.dbo format.

**Comment by UA998** [comment]
> > when we are adding a GUN in ggm by following the max custom weapons guide so there is a step which says : Use the GameGuru MAX Model Importer to convert your weapon model into a DBO format ..... So i want to say that how can we convert weapon model in DBO file by using ggm model importer becz there is no option to convert model into DBO file using ggm model importer ...... PLZ help
> 
> Also answered your same question on Steam. When you import any model of any format into Max it becomes a .dbo file automatically. All you need to do is browse to your imported folder and you will find it is now in a.dbo format.

When I select my custom weapon from game marker and when I try to run it shows an error which says failed to load object then shows another error "runtime error  70180"

**Comment by Necrym59** [comment]
Seems like you havent done it correctly as per the instructions

**Comment by davetgc** [comment]
@UA998 - Have you had any luck with this by reimporting the weapons? Custom weapons are a bit of an art form at the moment and are definitely an advanced users feature.

**Comment by UA998** [comment]
> @UA998 - Have you had any luck with this by reimporting the weapons? Custom weapons are a bit of an art form at the moment and are definitely an advanced users feature.

did not work ): i just wanted to make my own custom weapon )::: will give it another try

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
