### ISSUE TITLE
GGMAX - Text and HUD's flickering Problem

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5445]
When using scripts such as Win Kill, or Navbar/Navbar Objective, when the object the script is attached to is set to always active, a flickering will start to happen.

Steps to replicate this:

Set an object in a map to either Win Kill (with an enemy of course), or Navbar,

Set the object to Always Active.

Move the player start marker away from the object.

Run the Map.

https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/28f9f387-b193-4d1d-82a2-fc50f02a8f61

https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/d502e130-908c-4318-9d93-9813fa40c107

**Comment by Necrym59** [comment]
Confirmed!
Some distance has been set in the optimisations that now effect anything beyond a fixed coded distance even if set to always active this will effects a lot of global style behaviors. Can we find a way to have 'always active' behaviors as not effected by this distance optimisation?

**Comment by SampeyFS** [comment]
yes I had reported this too but was told it was OK!

**Comment by LeeBamberTGC** [comment]
@extremestrategy Sorry about that, massive boo boo in the code. Now always active does what it says on the Tin :)  New EXP build available.

**Comment by SampeyFS** [comment]
https://www.youtube.com/watch?v=ppavLIeV7oc  lee still does it look

**Comment by Necrym59** [comment]
Not sure if your refering to a future update but as of GameGuru MAX Build 2024.04.11
it is still flickering when reaching 1000 units distance from the object with the global behavior, this also applies to any globals that show prompt or update text from a global object.

**Comment by SampeyFS** [comment]
ah OK I thought it would fix that I apologize

**Comment by Necrym59** [comment]
@SampeyFS 
In the Graphics and Performance panel turn off  "Lower animation and lua speed" setting and it will work.

**Comment by SampeyFS** [comment]
OK THANK YOU
