### ISSUE TITLE
GGMAX Bug - Standalone does not extract DDS textures 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5447]
![Screenshot 2024-04-11 142001](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/ce9f77cb-d56e-4103-ae05-2ba1eea64493)
![Screenshot 2024-04-11 142013](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/43f39c58-e75d-40c8-930d-6cf962ba8eb9)

**Comment by SampeyFS** [comment]
Standalone does not extract DDS textures as you see that is original not the extracted one also the problematic save loads below the map

**Comment by SampeyFS** [comment]
when loading the game save some scripts did not work I was locked in the house because the door (would not open) this was also done with other scripts after (LOADING) the save 


@davetgc

**Comment by LeeBamberTGC** [comment]
@SampeyFS I assume the object with the missing textures is a stock asset. Can you make and attach a small level using only this asset and confirm your standalone export ripped out this texture:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/32026c5b-9a8c-48d2-a56a-198fc97494fa)

I can then load the level and try making my own standalone to see if I can reproduce what you see, thanks!

**Comment by SampeyFS** [comment]
Just create a layer with that object and export it with standalone, I've now removed it

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by SampeyFS** [comment]
The problem is still there it does not extract textures

**Comment by Kasseyus** [comment]
@SampeyFS 
Does this problem affect just the Windmill asset, or are there other assets affected the same way?

**Comment by Kasseyus** [comment]
I have run a few tests and so far, I have been unable to re-create  this bug.,..
![image](https://github.com/user-attachments/assets/4e73a48a-8b8d-4617-b097-a3c1b490bb81)

If you encounter the issue again on your current project, can you please record a video of the process as this will help me to follow the steps you have taken to reproduce it.
