### ISSUE TITLE
Game export problem

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5450]
![Screenshot 2024-04-11 200101](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/920beb49-e5ef-4e9b-be7f-dc3dc7253cd2)

I saved the game and reloaded it says game exported with standalone

**Comment by SampeyFS** [comment]
This also happens when loading the save sometimes it doesn't load the items into the inventory

**Comment by SampeyFS** [comment]
![Screenshot 2024-04-12 122122](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/f7d62b27-424d-45ab-ba15-cc384fe7241f)
Load Games

**Comment by davetgc** [comment]
As mentioned before. We can't solve these kind of issues from screenshots. It's almost certainly a local issue. Have you emailed lee@thegamecreators.com with the files and maps for this project?

**Comment by SampeyFS** [comment]
I have solved it I have corrected the utillib.lua files error line 211 is in max the problem also said it   @Necrym59

**Comment by SampeyFS** [comment]
the problem is to be corrected in max yes it does it always does not close the problem I correct it (to my project) @davetgc
