### ISSUE TITLE
Night-day  Cut to the next day there are problems

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5452]
https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/c4144a5c-9d00-43f2-8487-9d324b68a1e5

There is a problem between the transition from 12:00 A.M. at 1:00 as you can see from the video

**Comment by Necrym59** [comment]
Thats not an explanation please clarify

**Comment by SampeyFS** [comment]
Watch the video between midnight and 1am (switch to the next day i.e. from Monday to Tuesday)

**Comment by SampeyFS** [comment]
See how he does it instead of shooting the next day in (top left)

**Comment by SampeyFS** [comment]
it stays still at 12 it doesn't go to 1

**Comment by SampeyFS** [comment]
[https://www.youtube.com/watch?v=wpYElj6bNaU](url)

**Comment by SampeyFS** [comment]
https://www.youtube.com/watch?v=wpYElj6bNaU
