### ISSUE TITLE
hurt zone error. 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5453]
i've got multiple hurt zones in this map and the first hurt zone triggers fine, does what its suppose to do, however for some reason entering a second trigger zone brings up this error and ggmax completely crashes.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/a332e87d-64ab-49fe-8ef0-ca1b9de61f87)

my working theory is that if there are multiple hurt zones with different levels of hurt it brings up the error.

**Comment by Necrym59** [comment]
Do you have a value in the USER GLOBAL AFFECTED FIELD??

**Comment by casigus** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/342e680d-1890-4a01-ae2f-115c034be279)

nope! :)  going to replace all the zones today and see how it goes. If its ok, I'll let you know !

**Comment by casigus** [comment]
Okiesd! I've replaced the behaviours with the "electrocute" which is pretty much doing what I needed and so far had no issues! :)
