### ISSUE TITLE
GGMAX Bug - moving door glitch

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5455]
since the update this door keeps moving randomly to different positions, unsure whats causing it.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/b5328973-7707-4dfd-8d00-682ff0c38f21)

**Comment by Necrym59** [comment]
Is it not set to immovable or is gravity on?

**Comment by casigus** [comment]
this is in the editor! so it shouldn't bee moving at all!

**Comment by Necrym59** [comment]
is it locked? I can only guess from that image as to what is happening.,

**Comment by casigus** [comment]
the door shouldn't be moving at all IN the editor.

**Comment by Kitakazi** [comment]
Yea I have seen this happen too recently. At least I think this is the same thing casigus is experiencing.  From the OffWorld Station DLC I have some of the Lockers in my level and I have noticed in the editor only sometimes the doors on the lockers will be at weird positions like completely off the model. Selecting the locker will then cause the door to go back to its original location.

**Comment by Necrym59** [comment]
Are these 'animated' doors by any chance

**Comment by LightofAlfheim** [comment]
Happens to me too. Tried locking the door in place and making it immobile, but the issue persists

**Comment by LightofAlfheim** [comment]
> Are these 'animated' doors by any chance

The issue is there for me, animated or not

**Comment by Necrym59** [comment]
Is it all types of doors or a just a specific one from that pack? Have you tried replacing it with another type of door with the same result? Im trying to isolate it down and as much information as possible helps if you want it resolved.

**Comment by LightofAlfheim** [comment]
It only seems to be the Secret Bunker pack doors, and I also hadn't changed the name of them.

**Comment by Necrym59** [comment]
I have tested every door in the Secret Bunker pack without any problems.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by casigus** [comment]
hello there!! ive not seen this for a while!

**Comment by Kasseyus** [comment]
Just working through the backlog :)
