### ISSUE TITLE
No Shadows - Broken Lightmapper

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#546]
Hi everyone,

I dont know why I'm only noticing this now, but I have a map that is exterior and interior and I dont seem to see any shadows indoors using the Sci-Fi DLC indoor pieces.

![gg shadows](https://user-images.githubusercontent.com/35990109/59736820-21ce6680-9229-11e9-82f6-272ce2fb43b8.jpg)

This image is of the scene before I lightmapped. After doing lightmap baking the interior model disappears completely.

It was brought to my attention how to get the lightmapper working again in DX11 with holding SHIFT (i used SHIFT-F3). How ever when it was finished there still was no shadows but not only that it completely removed all interior structural entities from the map!

I should also note that all media used is/was from Steam DLC. No custom media.

EDIT: Issue related to #102 #197 #135

**Comment by Teabone3** [comment]
The work that Duch did on Cold Contact is actually not achievable in the DX version of GG. This was back in the DX9 days. When the lightmapper worked as intended.

https://www.game-guru.com/showcase/game/cold-contract

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

Could you upload the fpm here or e-mail it to me at plemsoft@plemsoft.com , and i will have a look :)

**Comment by plemsoft** [comment]
@Teabone3 Tried the scify building you used and some random objects from the DLC , but i got shadows and it worked, could you sent me the .fpm your using so i can see if it generate the same result here ?

![scify-lmtest](https://user-images.githubusercontent.com/18662417/59927983-04beb100-943e-11e9-9cf6-956e749487fc.jpg)

**Comment by Teabone3** [comment]
Here is a test map. Anytime i make a map and use F3 Lightmap it makes the SCI-FI white room models disappear.

**Comment by Teabone3** [comment]
Figured out the cause!
PBRoverride must equal 1 in the setup INI.
Does that mean this is still a bug?

**Comment by Granada1** [comment]
Also could it be that the model has stacked uv

**Comment by plemsoft** [comment]
@Teabone3 Yes the lightmapper and pbroverride=0 (DNSI) produce problems but:

Added lightmapper support for pbroverride=0 (DNSI).

Ready from the next update , give it a good test :)

**Comment by plemsoft** [comment]
BTW: you should set you light to static when you use the lightmapper , also only "static" object will get light mapped.

**Comment by Teabone3** [comment]
I'm having a lot of problems.

So i turned the lights to static and then did the shift F3 lightmap process and now the animated sci-fi table is no longer animating and isn't illuminating properly. I'm assuming however this might have been fixed in the next update as illuminations will be supported from what i understand?

**Comment by plemsoft** [comment]
@Teabone3 Yes it will be added in a later update , i can see in your image your using a old version with no 
 lightmap illum support.

**Comment by Teabone3** [comment]
Perfect Preben thank you so much for your continued work around here!
