### ISSUE TITLE
levels I'm building are getting wiped completely

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#5460]
I had my full game I was working on and decided to add an extra level at the ending. I worked on it for about a week saving constantly and everything was going fine until the last time I saved and then the map when completely blank objects and terrain. I thought it might just be a glitch so I close the program and opened it back to confirm the level was completely wiped. So, I finally got back around to remaking the level and got it about halfway done and the same exact thing happened again. The entire level is wiped of objects and any modifications to the terrain. It just looks like a brand-new level with the gray flooring grid and nothing on it. I don't really know how to reproduce the error and show it because it seems to happen at random after saving. It could take days before it happens. Here's the files for my levels though. I don't know if anything can be saved or if there gone for good. But I would like to figure out why the error is happening because rebuilding the levels over and over and having them erased kind of sucks.e
[wiped levels.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14971903/wiped.levels.zip)

**Comment by davetgc** [comment]
Thanks for the report.  Sorry that this has happened.

**Comment by mike123yy** [comment]
> Thanks for the report. Sorry that this has happened.

it's  alright, hopefully my levels can help you guys figure out what's happening though. I don't know if there's anything else I can provide that would be useful to getting the bugs squashed but if there is let me know. Thanks

**Comment by LeeBamberTGC** [comment]
@mike123yy Thanks for the files you attached. Always a good idea to maintain multiple backups in multiple locations.  A good trick is to use Dropbox to store your mapbank files as they offer a timemachine service to go back in time to revert to earlier versions of a file. This way you can always step backwards to the last good version of your level without having to recreate from scratch.

**Comment by mike123yy** [comment]
> @mike123yy Thanks for the files you attached. Always a good idea to maintain multiple backups in multiple locations. A good trick is to use Dropbox to store your mapbank files as they offer a timemachine service to go back in time to revert to earlier versions of a file. This way you can always step backwards to the last good version of your level without having to recreate from scratch.

I will definitely start doing that once I get back in the mood to have another go at it.I should have been doing it before but it's something you don't really consider until something like this happens.

**Comment by LeeBamberTGC** [comment]
@mike123yy Wait until you lose a whole hard drive with years of files on it, then you will know what horror means :)

**Comment by mike123yy** [comment]
well,you got me beat  there... and gave me a dose of anxiety, LOL.

**Comment by AvengingEagle** [comment]
GameGuru Classic used to save duplicates of all maps as .bak files if I recall. Used to be handy on the odd occasion a map would corrupt; you simply renamed the .bak to .fpm and your level was essentially reinstated. 

I'm sorry Lee, but telling users to install Dropbox to guard against this sort of stuff is not an adequate solution, despite being a good practice to get into generally. If you had a car that broke down every 50 miles and the garage told you you should simply only drive it 49 miles at a time, you'd be pretty annoyed and - rightfully - ask the garage to just fix the car so you could drive it as much as you like.

Maybe MAX itself could have a version system? Automated saving every ten minutes, saved to a folder in mapbank, containing the last 10 autosaves (i.e. mymap_autosave_0011.fpm overwrites mymap_autosave_0001.fpm). Adobe does stuff like this in their products.

**Comment by synchromesh62** [comment]
The .bak file was handy in fact i think i suggested it originally for Classic from my experience mapping with GTKRadiant and for Quake based engines etc back in the day.
Personally i think it would be great to have it in Max.
I always back up regularly anyway as i don't really trust Windows let alone anything else :)

**Comment by LeeBamberTGC** [comment]
@mike123yy Thanks for your two levels, I created a new project and added both as level 1 and 2, but on loading them they already seem to be empty for the most part (level 1 has a door and level 2 is completely empty).  The log shows that level 1 tried to load some objects, can you zip and send those to me in case this is the level you are looking to recover:

MISSING MEDIA:
entitybank\user\buildingeditor\gas1.fpe=replaceentitybank\user\buildingeditor\gas1.fpe
entitybank\user\buildingeditor\gas1_smartchild.fpe=replaceentitybank\user\buildingeditor\gas1_smartchild.fpe
entitybank\User\windows\window big\window - xl.fpe=replaceentitybank\User\windows\window big\window - xl.fpe
entitybank\User\ebestructures\realtor big.fpe=replaceentitybank\User\ebestructures\realtor big.fpe

The trick with backing up your levels is to do so before they corrupt or lose objects :)  Do you have any of those older more progressed levels. This is what I see from your "epologe.fpm" level:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/41280ce3-b3ce-4622-be23-e6e4ec1eb360)

**Comment by mike123yy** [comment]
I could send you the file since trying to load by looking at your list of missing media it looks like it's only two EBE structures which would be the gas station and the realtor office and the window that goes along with it. If that's all it would recover it wouldn't be much better than just starting from scratch again anyway. Here's a video of what the levels actually look like Before they got deleted. There should be way more entities than that And also trees and landscape.
[https://www.youtube.com/watch?v=OsqcafWHNp0](url)
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/OsqcafWHNp0/0.jpg)](https://www.youtube.com/watch?v=OsqcafWHNp0)

these were the only two versions of the level I had and like I said I didn't back them up so I don't have any older half built versions of the level.I forgot to mention after I save the level for the last time and everything got deleted I did try to use the undo function but it wouldn't work after the corruption happened. Mostly what I was trying to accomplish with the post was to help you guys figure out why it was happening and to get it patched up. Like the guys were saying in the previous post above it would be helpful to have a function in case this happens to revert back to an auto saved level created by the program.I already figured my levels were most likely  dead.but if there's anything else I can send you that would help you guys figure out why the levels were wiped let me know

**Comment by LeeBamberTGC** [comment]
@mike123yy Going to put a rush on this new feature, and will close this one down for now but you can reopen if you find a way to reproduce the "make the level go missing/corrupt". Here is the new feature: https://github.com/TheGameCreators/GameGuruRepo/issues/5415
