### ISSUE TITLE
Max crashing when exporting game

### ISSUE THREAD

**Issue by LightofAlfheim** [TheGameCreators/GameGuruRepo#5462]
Max crashes when the standalone save gets to 1% for some reason... tried on multiple different projects and it does the same thing. Please do your best to respond quickly as I do need to put together a build soon 

https://github.com/TheGameCreators/GameGuruRepo/assets/32985460/d2069810-99d0-4e1e-b72c-038f10730f86

**Comment by davetgc** [comment]
Can you please post your system specs?

**Comment by LightofAlfheim** [comment]
OPERATING SYSTEM 
Microsoft Windows 11 Home 
- Release ID: 2009 
- Version: 10.0.22631 
- Build: 22631 
CPU 
AMD Ryzen 5 3600 6-Core Processor               
- Clock speed: 3600MHz 
- Description: AMD64 Family 23 Model 113 Stepping 0 
GPU 
- Driver version: 10.54.50.446 
NVIDIA GeForce GTX 1650 SUPER 
- Refresh rate: 74Hz 
- Driver version: 31.0.15.5186 
RAM 
- Capacity: 16GB
- Type: DDR4 
- Default clock speed: 3200MHz

**Comment by SampeyFS** [comment]
You always tell me that @davetgc

**Comment by davetgc** [comment]
@SampeyFS - Thanks. It's best with these kind of issues to get several reports, as the crashes can be from different causes, or related but complex issues.

**Comment by LeeBamberTGC** [comment]
@LightofAlfheim This is not a crash, this is a non-response freeze.  The 1% mark has a lot to do, especially with file reading and building, if you wait for 10-20 minutes on slower machines, it will continue and complete the standalone export.

**Comment by LeeBamberTGC** [comment]
@SampeyFS You recently send me a standalone of your game relating to another bug so I am assuming you do not have the above issue.

**Comment by SampeyFS** [comment]
no @LeeBamberTGC

**Comment by LightofAlfheim** [comment]
Okay, thanks for the help. This solved my issue and I will close it now.
