### ISSUE TITLE
Max crashing while testing all levels

### ISSUE THREAD

**Issue by LightofAlfheim** [TheGameCreators/GameGuruRepo#5466]
Another crash! I'm starting to get good at finding these...
This time it happens while using the "test all levels" button on the storyboard editor.
https://github.com/TheGameCreators/GameGuruRepo/assets/32985460/3dc801cb-0cfe-436d-81d0-43fd7e22efd3

**Comment by LightofAlfheim** [comment]
System: 
OPERATING SYSTEM
Microsoft Windows 11 Home

Release ID: 2009
Version: 10.0.22631
Build: 22631
CPU
AMD Ryzen 5 3600 6-Core Processor
Clock speed: 3600MHz
Description: AMD64 Family 23 Model 113 Stepping 0
GPU
Driver version: 10.54.50.446
NVIDIA GeForce GTX 1650 SUPER
Refresh rate: 74Hz
Driver version: 31.0.15.5186
RAM
Capacity: 16GB
Type: DDR4
Default clock speed: 3200MHz

**Comment by davetgc** [comment]
This does sound like a local issue as we're not  getting reports from others. Let's see if we can solve this for you.

Are you on the public build or the experimental?

Do  you get a crash if you test a newly created level?

Are you getting any error messages?

**Comment by LightofAlfheim** [comment]
Im on the public build
I do not
Also don't

It is also a very large level so my.... slightly... not good pc might be the issue.

**Comment by davetgc** [comment]
I see that Lee has solved your other issue, is this similar, in that the level is just taking a long time to build?

**Comment by SampeyFS** [comment]
I also confirm that it does this every now and then when you start the game and when you play

**Comment by LightofAlfheim** [comment]
> I see that Lee has solved your other issue, is this similar, in that the level is just taking a long time to build?

No, loading times are normal. The test level will just randomly crash.

**Comment by C4ever08** [comment]
I can confirm the crashing. And its random. I do find it happens on my outdoor level. My indoor levels seem fine. Like the level holds at 80 fps no drops when it crashes. And was working on previous update.

**Comment by LightofAlfheim** [comment]
Also, now the standalone game will randomly crash

**Comment by LeeBamberTGC** [comment]
@LightofAlfheim Can you zip up your standalone game and email it to me at lee@thegamecreators.com. I can run your standalone in a special debug mode and should be able to spot when it crashes and fix the issue.  Looks like there are lots of scripting happening so I am guessing it may be somewhere in that code, we will know for sure when I can repeat the crash on my PC :)

**Comment by LightofAlfheim** [comment]
> @LightofAlfheim Can you zip up your standalone game and email it to me at [lee@thegamecreators.com](mailto:lee@thegamecreators.com). I can run your standalone in a special debug mode and should be able to spot when it crashes and fix the issue. Looks like there are lots of scripting happening so I am guessing it may be somewhere in that code, we will know for sure when I can repeat the crash on my PC :)

Email sent!

**Comment by LeeBamberTGC** [comment]
@LightofAlfheim I played the standalone for about 10 minutes, using tutorial and non tutorial paths, and eventually flew around until the game ended. No crashes at my end and seemed to work well.  Can you make a video of starting the game and then showing the crash, there might be a particular series of actions that triggers it that I am not doing.

**Comment by SampeyFS** [comment]
It happened to me too today I picked up an object it crashed max specifically it was food I was picking up it closed max alone

@LeeBamberTGC

**Comment by LightofAlfheim** [comment]
> @LightofAlfheim I played the standalone for about 10 minutes, using tutorial and non tutorial paths, and eventually flew around until the game ended. No crashes at my end and seemed to work well. Can you make a video of starting the game and then showing the crash, there might be a particular series of actions that triggers it that I am not doing.
Ill send it through email because of the file limit on github

**Comment by SampeyFS** [comment]
Even this morning I was walking it simply stopped max and crashed it closed on its own without any writing the crashes are increasing  @LeeBamberTGC

**Comment by davetgc** [comment]
@SampeyFS - Are you running any other apps alongside MAX? It sounds as if you're running out of RAM.

**Comment by SampeyFS** [comment]
impossible I have 32 GB of ram :) :)

**Comment by davetgc** [comment]
@SampeyFS - So, it doesn't crash? As @LeeBamberTGC has a copy of your game, he'll try to replicate your issues, but I think he may be finding it hard to reproduce. A lot of us have looked at your game, and are struggling to find a crash.

Incidentally, its far from impossible that you could be running out of RAM, but unlikely with 32gb.  It all depends on the size of your games, the textures, media, etc.  Also, you haven't answered my question "Are you running any other apps alongside MAX?". This can also take up additional RAM.

**Comment by SampeyFS** [comment]
Discord is open and that's it

**Comment by LeeBamberTGC** [comment]
@LightofAlfheim Sorry for your report being slightly sidetracked :)  Can you send me that video and we can find the specific cause of your issue, thanks!

**Comment by LightofAlfheim** [comment]
access granted

**Comment by LeeBamberTGC** [comment]
@LightofAlfheim Many thanks, I can see your video now and the crash.  Are you up for running a debug version of the standalone executable so we can see what error pops up?  A random crash like this makes it hard to know where in the code the problem lies.

**Comment by LightofAlfheim** [comment]
By all means, sooner this is fixed the better!

**Comment by LeeBamberTGC** [comment]
@LightofAlfheim New DEVTEST branch created with the latest version that introduces some stability fixes. Email me and I will send you the password so you can test this fix.

**Comment by SampeyFS** [comment]
Yesterday, when I unpacked the game, it always crashes for me too

**Comment by LightofAlfheim** [comment]
> @LightofAlfheim New DEVTEST branch created with the latest version that introduces some stability fixes. Email me and I will send you the password so you can test this fix.

It worked! The problem is now solved on my end, thank you so much for helping with this.
