### ISSUE TITLE
MAX - EXP - Graphics and Performance - Possible Fog Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5469]
When selecting the **Highest (best for quality)** setting the fog washes out the terrain. Just wondering if that is intended?
Couple pics to show what I get:

Before:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/77b76d0f-2013-4957-9a84-7425b81707c5)

With highest setting enabled:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/c2dd7427-6eab-410b-91f9-d2eaa8852e1b)

Thanks for checking :)

**Comment by davetgc** [comment]
I think the second looks more realistic. Does anyone else have any comments?

**Comment by OldFlak** [comment]
Not an issue now.
Twas a bug - Preben has sorted it for next build.
