### ISSUE TITLE
Entities - Medieval Stone Walls Collision Issue

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#547]
The stone wall corner pieces in the Medieval folder have box collisions around them preventing the player and entities from going near them. They should be using poly collision mode not cube.

**Comment by Teabone3** [comment]
I have made a fix for this and several others

https://forum.game-guru.com/thread/220853

**Comment by UNIRD12B** [comment]
Hi guys, 
   Did you also need to add in the setting. .
simpleobstacle=?
In order for AI to be able to pass thru passages of objects ?
