### ISSUE TITLE
GGMAX Bug - Scripts stop working on saved levels (Public GGM)

### ISSUE THREAD

**Issue by C4ever08** [TheGameCreators/GameGuruRepo#5470]
Ok so the issue is that two of my levels. Adon city and my mining base level. The scripts in those levels throw errors. The other levels to my game seem fine using the same scripts. So I have manually gone in and took out the scripts  saved the game then load it again and re apply them. But after a bit walking around level the errors come back again. Now if i leave the scripts out of the levels they work fine no errors obviously. 

A lot of the errors that pop up are usually the same scripts Nav bar, Nav Bar objective, Npc_controller, Quest giver, Switch, Buy object, income generator. And yes I asked Necrym already about this too. And hes just as confused as me as they work fine for him. And like i said none of my other levels are affected. I also have seen a error say Global cant something ENT. It rarely pops up and I'm not sure why. I usually set my scripts as always active too. I have verified many times as well and have also went back to previous update and it all works fine. I also use just the normal scripts not the community folder ones. I can make a standalone if you need it as well for a better look into it.

![GameGuru MAX - New Adon Moon fpm 2024-04-13 4_46_15 PM](https://github.com/TheGameCreators/GameGuruRepo/assets/80596156/2a4f0625-c8a0-4d36-bce9-3493bb15476a)

![GameGuru MAX - Mantis Station lvl 1 fpm_ 2024-03-12 12_28_01 PM](https://github.com/TheGameCreators/GameGuruRepo/assets/80596156/a72ef7ba-c01e-4215-ba5e-ea55e15b2d9b)

![GameGuru MAX - New Adon Moon fpm 2024-04-13 4_47_29 PM](https://github.com/TheGameCreators/GameGuruRepo/assets/80596156/f6967f4b-8c1e-4d9c-a35f-a4a6dd46914b)

some of the errors.

**Comment by C4ever08** [comment]
@LeeBamberTGC I have sent you my standalone in Email btw as well.

**Comment by C4ever08** [comment]
Just a heads up in my Adon city map I can not change the Quest giver script or even interact with him at all as well as most script s you interact with. No prompt shows up then it decides to throw more errors. I noticed if  I erase the quest from the tsv file and make an new Quest it still wont work on that level. And every level has a Quest giver that works with no issue. It is a big level but it runs great and at a stand still trying to figure it out myself. I have also removed every script from the level so i was trying to add back one by one but same results.

**Comment by Necrym59** [comment]
Possibly related to same problem on
https://github.com/TheGameCreators/GameGuruRepo/issues/5463

**Comment by LeeBamberTGC** [comment]
@C4ever08 Several improvements to the save game reload system in the DEVTEST since April so might be worth checking out again to see if the issue has been resolved, and if you still get the errors you reported. The new DEVTEST password is: lettesterin42

**Comment by C4ever08** [comment]
I appreciate that thank you. And can confirm everything is in working order on the Devtest branch. You can now close this issue as resolved thanks Lee.
