### ISSUE TITLE
GGMAX Bug - MAX Crashes in Test Game When Ticking Render Static Shapes

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#5471]
When I run a test game, hit TabTab, click Physics and then tick Render Static Shapes, MAX crashes. This doesn't happen all the time. In fact, the pattern seems to be:

- Run MAX for the first time and load level
- Run test game
- Hit TabTab, twirl down Physics, tick Render Physics Shapes, then tick Render Static Shapes
- MAX crashes
- Restart MAX
- Rinse and repeat above, but MAX does not crash this time

I think I have an idea what may be causing this. I was creating custom collision meshes (.obj) to use with some models. I would take the .obj, copy it into the folder (entitybank/mycustomfolder), open the FPE for the model and change the collision mode to 8 (collision mesh) so it would use the new .obj as a collision mesh. Then I would start MAX and run a test level so I could see that the new collision mesh is good. Since the FPE was changed and the new .obj added, perhaps MAX doesn't like this and crashes. But after that, it runs fine. If I repeat this (i.e. add a different collision mesh for a different model) then I get the crash again. And, once again, a restart will work fine.

**Comment by Kitakazi** [comment]
I noticed this crash too the other day. When Ticking Render Static Shapes. Mine might have been slightly different though, when I click Render Static Shapes the editor will freeze for about 5 seconds. If I attempt to do anything during this freeze it will crash to desktop. If I wait it will eventually render the physics shapes like normal. So might not be exactly related to MonkeyFrogs but yea.. just wanted to mention I did experience crashing too specifically when clicking Render Static Shapes.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
