### ISSUE TITLE
GGMAX Bug - EXP - Not all files from the project appear after saving it to standalone version 

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#5477]
I created a project. It has two levels with two different ambient music tracks. When I save it to the standalone version - there is only first track (Ambient -> Plains) there. When I get to the second level there is no music and the track (Ambient -> Canyon) doesn't even exist in game files. Also rain particles I put there didn't appear when in the project everything looked fine.

**Comment by LeeBamberTGC** [comment]
@NewWave2137 A new DEVTEST build has been uploaded that now correctly adds all ambient and combat music track files to the standalone export, amongst other improvements such as the same happening when you use a remote project folder. Check it out and let me know if it works for your project!  The password for this test Steam beta build is: lettesterin42
