### ISSUE TITLE
GGMAX EXP Build - Only one Textzone works during entire level

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#5478]
When I put more than one Textzone in the level only the first one works. 

https://youtu.be/sXMfsHG_O9U

**Comment by LeeBamberTGC** [comment]
@NewWave2137 To speed up the fix, can you attach a stock FPM level created with two text zones and mark them with terrain paint, and then confirm that only one will work for me. That way when I try at my end, I know the level is definitely going to reproduce the issue for me.
