### ISSUE TITLE
Max Crashing after latest update.

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#5482]
Hi I started Max approx 5pm. It installed updates and Promptly crashed. I tried verifying the files but no joy. (re-booted,cleaned temps etc.) I've rolled back to 2024.03.01 it appears to work again.
Nvidia RTX460 Ti.
AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz
32GB 4000mhz DDR Memory
EXP version of Max.

**Comment by davetgc** [comment]
Confirmed and we are working to fix it. This crash only affects the Exp build, so please revert to the public build for a few days. We're sorry about the crash, and will get it back up and running asap.

**Comment by MartinCranshaw** [comment]
Ok, thanks for the update.
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by LeeBamberTGC** [comment]
Now Fixed :)

**Comment by MartinCranshaw** [comment]
Fixed. Thanks.
