### ISSUE TITLE
GGMAX Bug - Full screen HUDS draw over test game GUI

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5492]
Please fix.

https://github.com/TheGameCreators/GameGuruRepo/assets/160327315/48817a9f-d61b-4aa8-aaf9-ec46ce9c5864

**Comment by LeeBamberTGC** [comment]
@Kraven3D Fixed for next DEVTEST build:
![image](https://github.com/user-attachments/assets/cf167b94-ad95-4f48-999a-8cd8d4ba79b6)
