### ISSUE TITLE
Secmon Behavior Causes the Players HUD to Disappear. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5495]
edited title. see next post for description of bug.

**Comment by Kitakazi** [comment]
I figured out what is causing this. It is being caused by the Secmon behavior. The camera monitor script. When the player goes to use the monitor to view the camera it removes the players HUD including the prompt text. It does not return once the player exits the camera screen. 
https://youtu.be/xboArqoL7GA

**Comment by Necrym59** [comment]
@Kitakazi  Can you try this one and let me know if it fixes the problem
[secmon_test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15213829/secmon_test.zip)

**Comment by Kitakazi** [comment]
This did not fix it the issue. When I try this new behavior it does not show the built in image hud, it also does not let me exit the camera screen.

**Comment by Necrym59** [comment]
It works here, can you confirm your using the one above v31
if it still gives a problem can you send me the test level your using

**Comment by Kitakazi** [comment]
Here is my test level. The Green Barrell at the start has the Secmon script. 
[new_test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15214780/new_test.zip)

**Comment by Necrym59** [comment]
Applied the seccam to a new camera and set ALWAYS ACTIVE ON
Reapplied the secmon beahavior to a new barrel  set ALWAYS ACTIVE ON
worked perfectly

**Comment by Kitakazi** [comment]
Ah yea my bad I did not have always active on in my test level. The v31 does indeed fix this issue.
