### ISSUE TITLE
GGMAX Bug - Enemies are not damaged by Explosions

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5496]
Enemies are not hurt by explosions. 
https://youtu.be/JAll_tfzgyE

**Comment by sanjitam-cpu** [comment]
I was asked by Kasseyus on discord to add this extra information here.   Grenades do not affect stock characters, zombies, or aztec characters.  They only affect the low-poly characters for some reason.

https://github.com/user-attachments/assets/3e261bf9-2aa2-40ef-a9a5-39cd3f2cd0fe

**Comment by LeeBamberTGC** [comment]
@Kitakazi Looks like stock stuff, which is great!  Can you attach an FPM of this exact scene so I can quickly load and reproduce, the fix should be very quick then :)

**Comment by Kitakazi** [comment]
[explosion_test.zip](https://github.com/user-attachments/files/16489196/explosion_test.zip)
@LeeBamberTGC Here you go.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for the next DEVTEST build :)
