### ISSUE TITLE
GGMAX  Bug - Item location not being updated when placed in container. 

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#5498]
When transfering an object into a 'chest' from the inventory, an entity items 'container' name should **always** reflect its 'current container name' location, and should be ammended in items entry, 'container name field' of the tsv file when transferred across.  Currently it makes items not show up in chests in the same level or carried over to other levels as the container name stays as set initially in the tsv and isnt being updated.

Secondly:, the container selection "inventory:chest" is now redundent and no longer used and should be removed from the HUD container selection options drop down as the "inventory:container'' is the one used chest items.

**Comment by LeeBamberTGC** [comment]
@Necrym59 I have removed "inventory:chest" from the choices for the next DEVTEST, but can you give me a step by step with a blank project/level to show me when the issue of the chest vs inventory bug arises, thanks!

**Comment by Necrym59** [comment]
Hi Lee
Attached is a sample project with 2 simple levels
Each level has a chest model with 'chestplayer" as the container
A Golden Vase is in level1  as a collectable item with a container of 'none' to begin with as below.
![start-tsv](https://github.com/user-attachments/assets/735fba1c-6eea-4379-9d6e-e347d7715eda)

Pickup the Golden Vase in level1 and place it in the chest
(what should happen is that the tsv file should be updated as to the new container for that item) like so
![update-tsv](https://github.com/user-attachments/assets/6753ca1a-f316-4340-8073-722f6ca4033f)
otherwise the item will not show on level2 in the "chestplayer" found there.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Fixed for the next DEVTEST build, so you can now collect an object in level 1, move to level 2, and place the object in the chest in level 2.:
![image](https://github.com/user-attachments/assets/039b956e-9d28-45a0-b420-46ad04d35b90)

The TSV file should not change based on what happens in the game as this is simply the 'starting position and states' of all collection items, so items that move about in the game and saved/restored are handled elsewhere.

**Comment by Necrym59** [comment]
Sorry, I was under the assumtion it was in the tsv file as to its position. So if the object is placed in a chest in Level1 it will show in the chest of the same container name in leve2 now? Im interested to know how that is handled, is that saved internally somewhere.

**Comment by LeeBamberTGC** [comment]
@Necrym59 yes that would be the way it SHOULD work but not testing that one, just the ability to carry the object in your inventory from level one to level two and then place it in the chest on level 2 :)

**Comment by Necrym59** [comment]
Ah ok gotchya now :)
