### ISSUE TITLE
GGMax 3D Level Editor suggestion: 3D Level Editor toolbar

### ISSUE THREAD

**Issue by Melburnian70** [TheGameCreators/GameGuruRepo#5499]
**OBSERVATIONS** 
- Some of the Main Toolbar buttons are a mixture of edit modes and 3D Level Editor view options
- Some of the Object Tools are actually 3D Level Editor tools and settings

![3D Level Editor toolbar - Observations](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/99f840ba-5f0f-48f2-ad98-6ef99aa1c735)

**SUGGESTIONS** 
- Group together all edit mode buttons on the right of the Main Toolbar
- Move all 3D Level Editor tools and settings from the Object Tools panels into a new 3D Level Editor toolbar
- New toolbar includes tools for: moving, rotating and scaling objects; snapping to objects or grid; and toggling visibility of Visual Logic Connections, Editor Light and Camera View

![3D Level Editor toolbar - Snap to Grid](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/4f05357f-7dd0-4c57-aebd-2227cf12d0ae)

Feedback is welcome: I understand this is a conclusion I came up with based on how I use GGMax, so I'm interested to hear if this suits other people's use of GGMax.

**Comment by MonkeyFrogStudio** [comment]
Some of this has already been suggest (and, I believe, is going to be added soon-ish). You can see one of the requests for adding snapping to the top here:

https://github.com/TheGameCreators/GameGuruRepo/issues/4067

But instead of taking up viewport space, the idea is to move it to the blank space on the bar at the top.

**Comment by Melburnian70** [comment]
Ah, thanks @MonkeyFrogStudio sorry, I didn't see that previous ticket. 

My reasoning for adding a new toolbar was those settings/tools are contextual to the 3D Level Editor (even though it takes up more space). I was thinking the icons could be reduced down to 48px (from 64px) to compensate for the extra height. 

The tools in the toolbar could also change depending on which Edit Mode you're in: Object, Terrain, Environment, Weather.

**Comment by MonkeyFrogStudio** [comment]
Sure. In most 3D modelers and game engines, some of these appear in the viewport, but not on a bar. They are mainly 'floating' in a corner, out of the way. I like to have as much screen real estate as possible for the viewport ... one of the reasons I don't really like MAX's giant icons and bars ... like it's a kid's toy. ;)

**Comment by Melburnian70** [comment]
Yeah definitely could be a floating toolbar in the corner too!

LOL, yeah the icons are rather large. ;)

**Comment by Necrym59** [comment]
Better to have dynamic panels/bar for the context tools perhaps on the new tool bar when its done it could have a context property section that changes depending on tool mode selected. Most newer softrware with a lot of tool property modes and with flexible ui's are adopting dynamic property bars in a given area.

**Comment by Melburnian70** [comment]
Thanks for the feedback, guys. How about this iteration (see mockups below)?

- All Edit Modes (Object, Terrain, Texture, Trees, Vegetation, Environment, Weather) are grouped together in the main toolbar
- The selected Mode's tools are placed in a floating toolbar in the 3D Editor window
- The selected tool's settings remain in the right-hand panel
- Visibility toggles (Visual Logic Connections, Editor Light, Top-Down Camera) are placed in their own floating toolbar
- Icons are reduced from 64px to 48px

![3D Level Editor - Object Mode - Move tool](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/edeed981-1cec-4cef-b83d-67b93b6a20b4)

![3D Level Editor - Terrain Mode - Sculpt tool](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/4ae4692b-84f0-4a50-b656-40f3131f88a0)

![3D Level Editor - Texture Mode - Paint tool](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/df04b4fe-81e1-4314-a0f9-6af9ed66bc01)

![3D Level Editor - Trees - Paint tool](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/69e765b9-8aaf-40a6-b9a4-739dcb75a3d7)

![3D Level Editor - Vegetation - Paint tool](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/520bd07f-795a-431b-918a-873e11fdfc92)

**Comment by Necrym59** [comment]
There will be no floating icons or toolbars, a toolbar is planned for the section above the viewport any property context tools will be placed in there.
