### ISSUE TITLE
GGMAX Bug - Render BIAS Values Not Retained

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5501]
Render BIAS settings are not retained.
- set the render bias of an object
- save the level
- run the level, note the BIAS values are used in test game 👍 
- save and close MAX (to be sure)
- open MAX
- the render BIAS of the object is back to 👎 

This is the case even when the BIAS values are set in the FPE
- when bringing object in the render BIAS value is correct 👍 
- save and close MAX
- open MAX
- the render BIAS values of the object are back to 0 👎 

Thanks for checking :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Can you include a small level with say the puddle object and your chosen BIAS, then attach here with a screenshot of what it should look like? I can then reproduce, see the BIAS resetting and fix this one quickly :)

**Comment by OldFlak** [comment]
@LeeBamberTGC - I don't think it is to the importer.
When you add an object which already has a custom BIAS value set in the FPE via the importer, the model comes in with that setting into the level.
When you play the level, it works as expected.
When you save the level, the value is retained, and works as expected.
But when you close MAX and reopen it later the values are back to 0.000.

I will put a simple level together that demos this issue and the mono audio issue ( #5414 ) asap.

Thanks for checking :)

**Comment by OldFlak** [comment]
DM'd you on Discord @LeeBamberTGC 

Thanks for looking at this :)

**Comment by LeeBamberTGC** [comment]
@OldFlak I loaded your simple level, changed the puddle to 93 in the bias, saved, ran test level, returned to editor, still shows 93. Saved the level. Then exited MAX, relaunched, loaded the saved level, checked the material and it still shows BIAS of 93:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/54941b35-71a5-4d2a-9de7-aad25a1365ee)
Can you provide a step by step scenario using your level where this value is reset, thanks!

**Comment by OldFlak** [comment]
Hi @LeeBamberTGC thanks for looking into it.
The step-by-step guide is in the OP, or just do what you did in your previous post.

After testing in response to your last post, I found that a value of 93.750 comes in as 93.000 after restarting MAX
- so for me MAX is not recalling values after the decimal point
- as an example, 1.050 will be recalled as 1.000 when restarting the MAX

**Comment by LeeBamberTGC** [comment]
@OldFlak Solved in the next DEVTEST branch, replacing the float value slider with an integer slider. Bias values are set internally as integer values so this reduces confusion and does not result in the different values when save and reload.

**Comment by OldFlak** [comment]
@LeeBamberTGC thanks Lee - will check when get home and close if all good :)

**Comment by OldFlak** [comment]
This issue is sorted nicely - thanks @LeeBamberTGC
