### ISSUE TITLE
Importer texture issue

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5505]
Hello!

this is how it should look when importing!

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/edafea86-4fdc-4460-83c6-31186bc81355)

which is exactly how exported it in blender.

and when max imports it, it changes it to this...

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/1b518084-57b7-402e-af02-41344c9207dc)

which as you can see is completely the wrong texture !

**Comment by synchromesh62** [comment]
Looks to me like it has no normal or especially a surface texture ..
I can barely see it but it does appear to be there just very dark. 
Just something to try ?

**Comment by casigus** [comment]
noo the texture it has is completely wrong. checked and double checked. this is how it looks in blender, it exports as this and ggmax then imports it as this and its after the importing process is completed max changes the textures :) 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/9aea217b-5e5a-4cee-902c-c40d3bbec2ef)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/6ba33aae-3d81-4f4b-83ca-dc141dd8cd13)

tried to import it a few times and each time it completely changes the texture. 

heres me importing it:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/86c90f8f-f97d-473a-82bb-37b6dbadb57e)

*clicks import object*

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/7004b17f-d84f-43b2-af0d-0a07fdbff072)


max changes the texture.

**Comment by Kraven3D** [comment]
859K tris and 247K vertices? Doesn't max have a limit per object at 70K verts? Maybe that's the issue? It might not take effect until the asset's imported which is why it shows up fine in the importer but not in-game. Just a guess though, I only heard of the limit through Discord and never encountered it myself.

Simple way to test it would be to delete most of the city in Blender so only around 50K vertices are left in the object and then export that version and see if it imports properly.

**Comment by casigus** [comment]
ahahaha. yeah its most likely that. I'm using a tool in blender that scans entire maps and then imports the data as a 3d object, and its really cool actually. on top of that, apart from this texture issue Max is handling the large model really really well, no slow downs or anything, just wont do the textures!!! Added a different texture to the model (decaying building type material) and that works fine. so its defo related to the limit.

**Comment by casigus** [comment]
everythings on high as well, and runs quite smooth for me, and this PC isn't even that powerfull. 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/ef5cbc0b-cab8-40fc-8919-dafa77b9efc9)
 just a shame the textures not working for the model!

**Comment by davetgc** [comment]
The issue is almost certainly the huge number of faces. Maybe Lee can shed some light.

**Comment by casigus** [comment]
yeah! well if thats the case you can close this off then. I doubt anyone else is mad enough to try and import the entire city of liverpool into ggmax THAT being said I actually did manage to import the entire of liverpool into ggmax but using one texture.

**Comment by synchromesh62** [comment]
This does look pretty cool though i must admit 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/8f26a04b-3f51-4964-93e4-9493eb178bd1)

**Comment by LeeBamberTGC** [comment]
@casigus Can you email me the model you are importing and I will check locally, thanks!
