### ISSUE TITLE
Max Bug - Money Behavior not affecting designated global

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5506]
Hey Lee, I'm having some money problems and I'm hoping you can help a fella out. The video below will go into details, but ultimately there seems to be something peculiar happening with the Money script that can't be replicated by other scripts using similar code. Also the MyMoney variable seems to be hard coded to 90.

https://youtu.be/CvRVE6Sq0rg

**Comment by Necrym59** [comment]
Now fixed
