### ISSUE TITLE
GGMAX Enhancement - Configuring and shaping Zones

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5510]
Of course they have always been awkward :)

1) By default, they should have only four points imop.  I never see the need for five when using them as default, and if I need more than four it is always more than five. However they do have five, and of course you can add/remove more if required. 
- not a showstopper but a wish for :)

2) But if you delete any of the original points it deletes the whole zone
- Not good at all 

3) You also need to be careful placing the points near a locked object. You usually have to unlock the object and move it so you can grab the point again
- Been the same issue for ever, and makes them tedious to work with at best

4) Tis also a little annoying\unproductive how the points tend to adjust to the terrain height or the top of a nearby object. An option to tell all points to say at the same original height when placed would be very handy.
- Same as 3 but much more unproductive

Thanks for considering :)

**Comment by OldFlak** [comment]
And it easy to get weird things like this happening with zones :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/4be4b878-71c7-4037-939b-434e263efd2e)

**Comment by MonkeyFrogStudio** [comment]
Since we're talking about zones, I hope you don't mind if I link to my old request about zones here, too:

https://github.com/TheGameCreators/GameGuruRepo/issues/4362

**Comment by OldFlak** [comment]
Ah good point @MonkeyFrogStudio - missed that post (sorry bout that)

I was actually thinking that widgets would be cool for the points, when I was posting this thread.

**Comment by OldFlak** [comment]
Opened a new ticket here #5871
