### ISSUE TITLE
GGMAX Bug - Custom collision meshes cause frame skips, stuttering and possible crashes

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5512]
Custom collision meshes (collisionmode = 8) that have more than one mesh in them appear to now cause a MASSIVE drop to performance when the player is close to them. This was not the case prior to the 04/11 update. 

This issue doesn't appear to drop the frame rate, however it DOES cause severe stuttering and player movement skipping (which resembles lag) when the player gets close to them, which didn't occur before the 04/11 update.

Here is a video showing the issue, and an image showing what I mean by "more than one mesh" in a custom collision object (note the collision mesh is still exported as a single object, however not all vertices are connected, though this was NEVER an issue before):

https://github.com/TheGameCreators/GameGuruRepo/assets/160327315/6bd385ac-4ae8-4890-8bcd-63d89eccf113

![collision](https://github.com/TheGameCreators/GameGuruRepo/assets/160327315/ad5a6acc-3c2b-4f6e-8c8d-30b746fc4de6)

**Please note the Scaffolding Mini Kit (and all of my other DLCS for that matter), have several custom collision meshes in them that might now be affected.**

_(Please also note custom collision meshes can be much better optimized than hull collision, which is why I prefer them, so would strongly recommend this issue be fixed, rather than suggesting to use hull collision.)_

**Comment by Kraven3D** [comment]
**UPDATE:**
Having two or more entities that use custom collision meshes close to each other in the 04.11 build appear to cause such an issue with performance when the player gets near them that it causes a **CRASH!** I've tested this three times. Crashes every time. 

https://github.com/TheGameCreators/GameGuruRepo/assets/160327315/7fb15204-be80-410c-9c2c-cb25713df631

**Comment by SampeyFS** [comment]
yes yes

**Comment by LeeBamberTGC** [comment]
@Kraven3D Moved physics logic back into the main thread in the DEVTEST branch, Email me if you want to test this and I will give you the Steam beta password.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
