### ISSUE TITLE
GGMAX Bug - Game crashing

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#5513]
Every time you test the game it is very jerky then it freezes then  shuts down to the desk top it also has a nvidia gforce rtx 3060 laptop gu card the win ver is the 23h2 it was working fine until the last update

The problem seems to occur when you open a door killing characters is a bit jerky but it doesn't crash

Machine				Acer - Predator PH315-53
Operation System		Microsoft Windows 11 Home (64-bit) 
Memory				16 GB
Processor			Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Motherboard			CML - QX50_CMS
Video Cards			Intel(R) UHD Graphics
Monitors			        LG Display  LP156WFG-SPF
Hard Disk			SAMSUNG MZVLB512HBJQ-00007 (512.0 GB)
Network Card			Killer(R) Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter (201NGW)

**Comment by Necrym59** [comment]
Possibly related to
https://github.com/TheGameCreators/GameGuruRepo/issues/5512

**Comment by davetgc** [comment]
@zeebon - Why have you swapped to the internal card. Where you having problems with the Nvidia card?

**Comment by zeebon** [comment]
Thought it might have been causing the problem tried both but no difference so i sent a issue report
Sent from my iPhone

On 6 May 2024, at 14:56, davetgc ***@***.***> wrote:

﻿

@zeebon<https://github.com/zeebon> - Why have you swapped to the internal card. Where you having problems with the Nvidia card?

**Comment by LeeBamberTGC** [comment]
@zeebon Does this also happen with the HUB demos, such as the SWITCH ESCAPE demo game?

**Comment by zeebon** [comment]
Sorted that problem using work shop to run it seems more stable
