### ISSUE TITLE
GGMAX Bug -Crashes on start

### ISSUE THREAD

**Issue by Courtney556** [TheGameCreators/GameGuruRepo#5515]
This issue has already been discussed and apparently fixed for some people. However, I am experiencing the same thing happening when it boots up, shows me the title screen for a few seconds and than crashes. Even when reverting to old builds, it will still crash.

**Comment by SampeyFS** [comment]
I also confirm that my project (the hermit) crashes every now and then when it starts and closes on its own

**Comment by LeeBamberTGC** [comment]
@Courtney556 If this is still happening in the latest version, can you send me the LOG file that would have been produced and stored around here: "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX\Guru-MapEditor.log". Thanks!

**Comment by Courtney556** [comment]
I have found the fix for this. I had to prevent oneDrive from saving any of my files. I think its just the documents you have to disable, but I disabled them all and it works now.

1. Right click oneDrive on task bar
2. Select settings
3. Navigate to sync and backup
4. Disable documents backup

Should work after this!
