### ISSUE TITLE
Task Tool not working?

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#5520]
The task tool no longer seems to work as there is a problem with the Lua script.
Hopefully this is one of the behaviours being worked on.
PS. The FPS improvement has been quite dramatic. From 60 it's leapt up to 400fps on a small level. Well done to all involved.

**Comment by Necrym59** [comment]
It works here without a issue, Your problem is is not very descriptive can you be more specific as to what the problem actually is??

**Comment by MartinCranshaw** [comment]
Good Morning.
This is the message I get.
![Lua error](https://github.com/TheGameCreators/GameGuruRepo/assets/38034903/705c4a99-d9f0-4def-a720-087d9f02ec8a)

**Comment by Necrym59** [comment]
An updated working behvaiour has been uploaded to the workshop - reapply the tasktool object with the updated behavior.

**Comment by MartinCranshaw** [comment]
Thanks Steve.
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by Necrym59** [comment]
Is this now working for you?

**Comment by MartinCranshaw** [comment]
Fixed Thanks.
