### ISSUE TITLE
GGMAX Bug - Scope Overlays Not Getting Cleared On Level End

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5522]
For custom weapons, that have a sort of overlay, (I'm not sure what it's actually called) for the scope to make it zoom in, and have it appear that there is a target reticle, if you are still holding right mouse button to aim and zoom in, and then you quite the level, the overlay will reappear when you start the level again, this happens in both testing levels, and in standalone games.  This is primarily noticeable if you have a video at the start of your level as the overlay will sit over the video.

https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/991be8f2-4fdd-4d68-bc1a-7292dd558363

**Comment by LeeBamberTGC** [comment]
@extremestrategy I do not think there are any stock weapons that use this old method of zoom graphics, the closest I found was this:
![image](https://github.com/user-attachments/assets/80867f7e-2513-4917-83a0-669da6799672)

Do you know of any stock, DLC or Asset Store weapons that use the old method so I can reproduce with what I have here, thanks!

**Comment by extremestrategy** [comment]
@LeeBamberTGC I think that the ones that use the old zoom method would be the BSP weapons on the TGC Store, this is the pack that I'm using in the video https://gamecreator.store/bundle/11309 Is this something I should bring up to BSP?

**Comment by LeeBamberTGC** [comment]
@extremestrategy Yes anything third party created should refer to the author. Anything that is stock would be a bug of course.

**Comment by extremestrategy** [comment]
Alright I'll close this bug report then and mention it to BSP.
