### ISSUE TITLE
Astec2.0_V1.6

### ISSUE THREAD

**Issue by jaffrol** [TheGameCreators/GameGuruRepo#5526]
**_ASTEC-2.0-V1.6_**

![Capture_decran_2024-05-06_060640](https://github.com/TheGameCreators/GameGuruRepo/assets/125188887/c52a359a-ba3b-4045-ab5b-3f24573c2978)
![astec](https://github.com/TheGameCreators/GameGuruRepo/assets/125188887/20036893-75a5-407d-9458-10f2368893a6)
![astec1](https://github.com/TheGameCreators/GameGuruRepo/assets/125188887/53882aad-b0d7-4066-ab91-6ff75776b1c6)

Thank you 
[https://winordz.itch.io/astec-20](url)
Thank you in advance that the game is an opensource project don't forget that its a prototype not a finished game is especially on this project it will be available on steam workshop or on github.

![7379869](https://github.com/TheGameCreators/GameGuruRepo/assets/125188887/b965d85d-9aab-43d0-8d77-db755d6e9e8e)

**Comment by imothep85** [comment]
how do you got so much grass in ggmax ??

**Comment by imothep85** [comment]
well i put grass 100 in density and 700 in distance and i only get a little bit of grass...

**Comment by imothep85** [comment]
![grass crap result](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/1a692613-c0d8-47d5-a7fb-0b55b88e7ff7)
this is what i get.............catastrophic quality....

**Comment by jaffrol** [comment]
well ok I see asec the pack that I have is the one that I bought it's in the jungle forest pack it's in there but otherwise I'll send you a screen you will understand the grass that you see it's in a pack that I bought I don't know you it

**Comment by davetgc** [comment]
A good looking game, but this isn't the place to post WIP. If you want, you can add these type of posts to our Discord.

**Comment by jaffrol** [comment]
channel discord invalid please order new url please no connected from rejoind
