### ISSUE TITLE
Is more memory used with PBR textures?

### ISSUE THREAD

**Issue by Raj898** [TheGameCreators/GameGuruRepo#553]
On home page is indoor image and I watch tutorial and is dx9. I read some users mention this version recent on the forums. https://www.youtube.com/watch?v=d6-7m6QLQMA&t=119s

I read about memory usage recent on forum. I run Process Explorer program to view graphic card memory usage on both version. dx11 show 0.8 GB more total memory than the larger dx9 demo game in end of video.  https://vimeo.com/344027339

Is graphic memory usage counted in usage space for Game Guru like what is explained in link.
https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/does-1-gb-graphics-card-and-4gb-ram-make-the/d7cabc8d-f175-4bc4-a74d-23828450429d

Is the higher graphic memory usage because of PBR textures being used in demo?
And will free memory option in setup file be covered in a tutorial video? Thank you.

**Comment by LeeBamberTGC** [comment]
Is this a bug or a feature request?  General conversations can be done in our forums here: https://forum.game-guru.com/board/1

**Comment by Raj898** [comment]
I was unsure about result so I post and today not use PBR and use less resource. Thank you I will sign up.
This can be closed.
