### ISSUE TITLE
GGMAX Bug - Crashing when changing textures

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5531]
GGMAX crash when we select a prop in the scene and then we do some texture changes in Photoshop, in my case.
Every-time i change a texture, GGMAX crash.

**Comment by Necrym59** [comment]
Try reimporting the object or exiting Max while editing a texture.

**Comment by SampeyFS** [comment]
Yes it happened to me too (update the texture) of an object crascia max it happened to me too I confirm

**Comment by Necrym59** [comment]
Is it happening when editing while Max is open or when you reimport an object
