### ISSUE TITLE
Ifused appears not to be working again. 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5534]
As the title states it would appear the Ifused no longer functions.
Im using a lot of **Switch Combo.lua's** which rely on this function and maybe **CineGuru** as well.

**Comment by Blood-Moon-Interactive** [comment]
I can confirm that I'm not seeing any results from IfUsed using the Switch Combo behavior. However I am using IfUsed in Switch Count and that seems to work just fine. So it may be isolated to just this behavior.

**Comment by synchromesh62** [comment]
> I can confirm that I'm not seeing any results from IfUsed using the Switch Combo behavior. However I am using IfUsed in Switch Count and that seems to work just fine. So it may be isolated to just this behavior.

Hmm i tried just a bog standard switch using **ifused** to open a door and that failed ?
I will try again though .

**Comment by synchromesh62** [comment]
Tried again and definitely not working for me.
Perhaps someone else can give it a try also.

**Comment by synchromesh62** [comment]
Closing this one due to some Necrym updates that has rectified the situation.
