### ISSUE TITLE
GGMAX Bug - Steam Workshop not working

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5535]
Today I realized that workshop doesn't update the scripts, I had proof of this today with a script Necrym59  had updated and I didn't update it, ask him for confirmation too

**Comment by synchromesh62** [comment]
@SampeyFS 
Sometimes you have to do it a few times it seems and you will see a very fast verify to acknowledge this when you restart Max to confirm its updated but you **Must** launch from Steam for this process to work.
Launching from a Desktop icon will not update i have found.

**Comment by synchromesh62** [comment]
Just to clarify what i mentioned above I recorded the process .. It sometimes takes a couple of attempts sometimes for **Steam** to actually update so i think its more a **Steam issue** than Max but it will eventually update without the need for a verify. 

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/a9095ca5-5a95-47ef-b57c-231278b0bfa4
