### ISSUE TITLE
Particles are NOT in the exported game, like torches fire!

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5539]
I tried to compile my game to test it...
It doesn't work !
MASSIVE CRASHES with lot of different LUA errors !
it worked JUST ONCE after many trials...WIN 10 block the compiled game...
PARTICLES are NOT created & rendered in the compiled game, my torches are ALL empty... !
when i launch the game, it's completely EMPTY....when it works...
The game takes a LOT of processor power...
THEN it crashes when we try to change the graphics to test the medium & low resolution...

TERRIBLE...result........ i seriously hope it's going to be fixed....

![compiled game doesn't work02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/ca8126b3-0b44-4f59-a5a2-cae0e516b4b9)
[compiled game doesn't work04](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/a7b3d0f1-2e16-4d16-a825-5275815d7316)![compiled game doesn't work03](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/cd02cf8e-4893-4251-8c19-fd9f70f37aa3)

![compiled game doesn't work01](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/de4808dc-e206-4231-8796-318f82029742)

![particles not rendered](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/0c99af19-f858-44d9-813a-3d89dd8e2e62)

![compiled game doesn't work04](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/1e701960-9c78-465e-b89c-24af61f9e6f3)

And then..... it crashes... when it works, i tested the game for 1 or 2min....
![crash when testing the game](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/da17b76a-d9c5-482c-9019-60fe9d554515)

**Comment by SampeyFS** [comment]
sorry, can you tell me the requirements of your computer

**Comment by imothep85** [comment]
my computer is:
 
intel 7700k 
WIN10 
32gb ram
11gb nvidia ati TI 1080 
HDD ssd 500gb mv2 + 1tb hdd

it's scary because i spent now 4 months full time working extremely hard on my game with this engine....

**Comment by SampeyFS** [comment]
it seems strange that I'm playing 3 games now it works fine except for some problems with the lua but it doesn't cause a problem it depends on how you put the scripts and if you are in the experimental version or anyway there is something that doesn't add up if you get the written ones

**Comment by imothep85** [comment]
i dont use LUA in my games i just created my whole level, 
at this point, is NO interaction in the game 
only 1 script the SIT script of necrym and a another one for making some of my game elements levitate.

**Comment by SampeyFS** [comment]
I noticed from your photo that it consumes a lot of CPU, check that your processors are really unlocked with UnparkCpu

**Comment by imothep85** [comment]
............

**Comment by SampeyFS** [comment]
yes, in my opinion this program needs to be checked from head to toe

**Comment by EmpowerGamingPain** [comment]
I am also having some issues with exporting. I was concerned after reading several comments explaining issues regarding exports.
Before I want to invest a large ammount of time in a project I would like to be ensured that I would be able to export the project into its stand alone executable. Currently this does not seem to be the case. 
  
While testing the stand alone feature I tested exporting a single custom level which contains a mixture of assets from The Game Creator Store and Steam DLC and also with some game menu customizations. The export completes successfully. I launched the executable (Game Guru Max is closed) and the Splash screen launched, the Main menu appears, I am able to click through all of the menus created with no problem. I click the Start Game button and it launches the loading screen. Within 15-30 seconds the exe crashes with no error message or anything to work with. 

The Event Viewer in Windows does spit out the following error: 
Event ID: 1000 Application Error

Faulting application name: Internal game testing - War on Mars.exe, version: 0.0.0.0, time stamp: 0x66180945
Faulting module name: Internal game testing - War on Mars.exe, version: 0.0.0.0, time stamp: 0x66180945
Exception code: 0xc0000409
Fault offset: 0x000000000080e9d9
Faulting process id: 0x801c
Faulting application start time: 0x01dab868f38359e3
Faulting application path: C:\Users\Empower Gaming\Documents\GameGuruApps\GameGuruMAX\My Games\Internal game testing - War on Mars\Internal game testing - War on Mars.exe
Faulting module path: C:\Users\Empower Gaming\Documents\GameGuruApps\GameGuruMAX\My Games\Internal game testing - War on Mars\Internal game testing - War on Mars.exe
Report Id: 06a51f2b-9b3d-4f3f-bad6-bb80ffd3084d
Faulting package full name: 
Faulting package-relative application ID: 

Additionally it reports the following Event 1001 Windows Error Reporting (Error TXT file below) 

Fault bucket 1794168535017540875, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Internal game testing - War on Mars.exe
P2: 0.0.0.0
P3: 66180945
P4: Internal game testing - War on Mars.exe
P5: 0.0.0.0
P6: 66180945
P7: 000000000080e9d9
P8: c0000409
P9: 0000000000000002
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2DC6.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER30E4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER30F4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3102.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3122.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Internal game te_909f7db4e16a9289e4cc96198cae29de2d3c8a92_575fc45e_352dd2cc-6456-4069-8167-3dc6b2249c81

Analysis symbol: 
Rechecking for solution: 0
Report Id: 06a51f2b-9b3d-4f3f-bad6-bb80ffd3084d
Report Status: 268435456
Hashed bucket: 398b5f27e75fc615e8e62ac6d4e74d0b
Cab Guid: 0

[Report error.txt](https://github.com/user-attachments/files/15687594/Report.error.txt)


My System Specifications: 
AMD Ryzen 7 5700X (8 Cores, 16 Threads) 
AsRock B550 Steel Legend
32GB DDR4 3200Mhz CL16 (16x2)
2TB M.2 NVME Gen 4 
Nvidia GeForce RTX 3070 TI 8GB GDDR6
Windows 10 Pro 

Any thoughts?

**Comment by LeeBamberTGC** [comment]
@imothep85 Are you able to load one of the HUB Demo levels such as SWITCH ESCAPE and then save that as a standalone and run it without the reported crashes and errors?  If we can confirm this much works, we can then dive deeper into what might be issues related to more custom content in the game.  Thanks!

**Comment by imothep85** [comment]
You can put the problem on solved, everything works fine, when i compile the game BUT the particles are NOT in the exported game, like torches fire !

**Comment by SampeyFS** [comment]
That's right, it loads the CPU too much, it needs to be fixed, it's not good as it is

**Comment by LeeBamberTGC** [comment]
@imothep85 Marking as fixed as requested, but please post a new one when the next EXP build is released if you cannot confirm the export of particles now works for your standalone games.
