### ISSUE TITLE
GGMAX DEVTEST - Crash  Games e Bug 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5541]
![Screenshot 2024-05-13 163159](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/de83ec8f-73b7-4d88-95dc-13644f64dc49)

in the update just now in the devtest the game crashes returned, furthermore I went under the map and furthermore the scripts are still not called when loading the game

**Comment by SampeyFS** [comment]
![Screenshot 2024-05-13 163159](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/89ed333c-953f-47e5-b577-01be05c1907f)
![Screenshot 2024-05-13 164928](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/a0b776bd-3fb7-4e0b-91ce-b171d71a5175)
![Screenshot 2024-05-13 164935](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/62b95fa8-1d07-4f3f-b2f3-dd66851d72ef)

**Comment by SampeyFS** [comment]
Even inside buildings you sink then the game crashes

**Comment by SampeyFS** [comment]
It's a pleasure to help you if you have anything to test send me, I'm playing the game I can test better :-)

**Comment by SampeyFS** [comment]
Perfect, now it works, the problem of the scripts and the grass remains when you start the game, there is grass on the road
![Screenshot 2024-05-13 194623](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/524a38fa-2de2-4b67-b4a1-b8f3cc9d3a5a)

**Comment by SampeyFS** [comment]
Sorry because you're done, it has nothing to do with this, this is a crappy standalone @Necrym59

**Comment by LeeBamberTGC** [comment]
Marking this as fixed as the script and grass issues are reported elsewhere.

**Comment by SampeyFS** [comment]
Do you mean the loading of the lua?
