### ISSUE TITLE
Question - Spawn Resources

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5545]
As you can see from the photo I'm putting mushrooms etc around, the resource script needs the option how to eat the respawn time when you pick it up after a few minutes it will be respawned thank you so much

![Screenshot 2024-05-15 101324](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/4f71c35e-8751-46b8-8832-9552ae09f3b2)

**Comment by Necrym59** [comment]
Use the respawn in the resouorce node behavior

**Comment by SampeyFS** [comment]
that script only plugs one seedling why?

**Comment by Necrym59** [comment]
Because thats the way it works just copy and past it if you want more regrowing items.  The Resource will not be changed.
