### ISSUE TITLE
GGMAX Climbing problems

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5546]
i put this topic here because i don't know if it's a BUG or not !

In my game i have elevated paths, for example in my cave
some problems with the player when walking on flat surface with elevated angles...
i tried every option of the climb angle, nothing works... 
from 10 to 100. The character when he start walking on those paths more high he get, 
SLOWER he walk and then he eventually stop ! 
if I walk too low or too high, the character sticks as if he were walking on strong glue ! 
I'm stuck with that problem.

![climb_angle](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/c946f35b-3d32-4da9-ab75-d12bbdde18c9)
![climb_difficult_on_flat_surface](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/ab2c55fd-c41c-4836-8ea1-d5843cb90cd2)
![climb_difficult_on_flat_surface_02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/98ca6fb1-b353-4ad8-b8b8-e0e098e53006)
![climb_difficult_on_flat_surface_03](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/15289e07-eb82-422a-914a-d938f6f19e37)

**Comment by synchromesh62** [comment]
What happens if you set your Climb angle higher.
Try 200 just as a test.

**Comment by davetgc** [comment]
This sounds like an issue with the custom media. You'll need to send it to Lee so he can test.

**Comment by imothep85** [comment]
i solved that problem by adding little rocks in my paths it push the player when he walk in
