### ISSUE TITLE
GGMAX Bug - Vsync in editor stays ticked but reverts to Vsync off when exiting a test game 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5547]
As the title says ..
Vsync in editor stays ticked but reverts to Vsync off when exiting a test game .. Untick and re-tick re-enables it.
I did a quick vid to show the issue.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/2879c7a1-8aaf-41af-8fa7-253326f94144

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I have now modified and updated the tooltip so that the editor spaces always run at maximum performance (no vysnc) and VSync only works now in test game or standalone games, and restores this state when entering leaving a game.
