### ISSUE TITLE
GGMAX Bug - Smart Objects sometimes destroy random objects

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5548]
When we create smart objects they work from time to time, NOT all the time...
IF you PUT a smart object in the scene THEN create a second one, the same in another part of the game,
and later you decide to delete it, it will DESTROY the other smart object BUT ALSO RANDOM objects in your scene.

It happened to me and i spent HOURS adding details in my scene, when i deleted a smart object he removed another one from my level PLUS others objects close to the smart object....
![smart object destroy random objects](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/09df3295-82a4-4557-9963-f44a2b4488d2)

I ASK LEE TO BLOCK the smart object function, or remove it before it has to be re-created from SCRATCH !
Because SMART OBJECTS ARE NOT SMART AT ALL !

**Comment by imothep85** [comment]
HERE where my smart object wall has completely disappear with NO REASON, not deleted.. !
![self destroyed](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/e815f4b4-ae7f-42a2-9ec8-7e24ba66f9af)

NOW imagine what happen when you have to place all those details by hand one by one....

**Comment by LeeBamberTGC** [comment]
@imothep85 Can you show this happening in a small video using stock media smart objects with a fresh level, that way I can reproduce quickly and resolve this. There have been fixes recently that resolved some smart object / groups corruption from older legacy levels.

Also there is a new backup system so if your level messes up and you accidentally saved it, you will find an older version of your levels here: "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX\Files\mapbank\_automatedbackups"

**Comment by imothep85** [comment]
yes i saw that the game do backups now :D thanks for all your hard work Lee i will do a short video of course !

**Comment by imothep85** [comment]
Here first little video, i created a group of metal walls, then i duplicate them in the level, IF i chose one entity i dont like in the level and delete it, when i push "DELETE" on my keyboard it delete another random smart object present in the scene.

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/36e39758-9d44-4a2d-8858-0c5554b92a75

**Comment by imothep85** [comment]
Here a second little video,
when i select my arches entity and duplicate it in the scene, the smart object CREATE another object that the arches, and sometimes when i want to duplicate the smart object, it just create a little part of the smart object isolated....when i look at the smart object it show the correct objects inside, BUT instead of creating the arches it randomly create another object present in the level...

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/cddc320d-bc0a-4b34-b8fb-20f373f36188

**Comment by LeeBamberTGC** [comment]
@imothep85 I do not recognize those walls or arches sonI cannot reproduce exactly what you are doing in your video. Can you show this happening in a video using STOCK media smart objects with a FRESH level created from SCRATCH, then I can follow along step by step and then see the wrong group get deleted, thanks!

**Comment by imothep85** [comment]
here the video with stock assets
https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/da4a2431-c95e-4188-a2cc-0ff0649a8631

**Comment by LeeBamberTGC** [comment]
@imothep85 Looks like your video just shows the end of the process, so I could not create as you create or reproduce. From what you created, I also started with a fresh level, found the instrial trolley, created a line of 7, make it a group, saved the group and called it trolleywall, then added this to my local objects, then dragged in one after the other into the level:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2e51c24f-954d-4aa7-afaa-ec0f14f20471)

No matter what combo of deleting old ones and dragging in new ones, I could not get the wrong smart object to delete.  Whatever sequence you used is the cause of the corruption. Can you create a video showing from complete scratch the creation of the smart object and then its use, leading up to the wrong smart object being deleted from the level, thanks!

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
