### ISSUE TITLE
MAX - Player's hand sometimes stretches to infinity for a single frame

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#5551]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/56294129/23ee404a-4f3c-48a3-ab9f-8effcedc079a)

Had this bug for a while, but failed to capture it because it seems completely random.

Sometimes, regardless of weapon or hand choice, the player's hand will stretch infinitely long for a single frame, before returning to normal. This doesn't seem to happen with "legacy" weapons where the hands are a part of the weapon itself (i.e. the sci-fi weapons from the TGC Store do not have this issue.) so I presume it may have something to do with the new player hands system miscalculating a bone position or so.

**Comment by Necrym59** [comment]
Already reported

**Comment by fearlesswee** [comment]
@Necrym59 Didn't see that, lol. I'll close this and instead add this to the original report.
