### ISSUE TITLE
GGMax Text Zone

### ISSUE THREAD

**Issue by ockerdave** [TheGameCreators/GameGuruRepo#5557]
On entering Text Zone Error - scriptbank Text in Zone lua53 Attempt to perform Arithmetic
on field period (nil value) - Latest experimental Update

**Comment by synchromesh62** [comment]
Thought i would check this out whilst i was testing a few others
No probs here 
@ockerdave have you tried verifying in case the update did not sit well.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/b8c164d5-bce6-4627-a0ce-8d342e877b80

**Comment by ockerdave** [comment]
Thanx all, completed a verification of files, no files found. Found another area of my scene
were the text worked, but is a text box placed months ago, but placing a new text box 
shows no error message this time,, but never shows the text message.
