### ISSUE TITLE
GGMAX BUG ladder behavior 

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5561]
It's a BUG wit the ladder script behavior !
The script does not work as intended, when the player is CLOSE to the ladder, the text "e to use" or the text you put in place, appear.
BUT if the player is even looking to ANOTHER direction the ladder text appear, even...if the player is NOT facing or "LOOKING AT" the ladder...

here the player look at the ladder, the script appear
![ladder bug01](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/f246c819-0882-4ae5-88ab-f1d178635d51)

if the player is CLOSE to the ladder the script appear too even if the player is NOT looking at the ladder !
![ladder bug02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/0bf8e394-ab4e-492d-9f9a-06cdc71fc3c2)

**Comment by synchromesh62** [comment]
@imothep85 
Yes that script is older and not a bug as it was proximity based. 
Necrym can update it when he gets time but **enough with the Caps** 
Just the report is fine.

**Comment by Necrym59** [comment]
Its not BUGGED! Its Proximity based at the moment i will enhance it later.
