### ISSUE TITLE
GGMAX Bug - Particle Toggle

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5562]
Hey Lee - in the video below I'll demonstrate that particles do not toggle the same way that other things (such as lights or trigger zones) do. Happy to send the level along if you need it.

https://youtu.be/H2FiDZmmyeU

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Fixed for next DEVTEST build.
