### ISSUE TITLE
GGMAX Bug - Objects disappearing

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5563]
GGMAX keep deleting objects in my level 
The ceiling objects, disappear each time i save the game and reload, ggmax is reloading my game without the objects
here the roof completed and i save the project
![roof complete](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/f89f1c13-418a-422e-abf0-e36708a01e50)

here the roof removed by ggmax when i reload the software
![roof removed by ggmax when reloading the game](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/8832c7d7-d166-4675-ba0e-92bda3a440f7)
Smart objects are andomly rotated.... when i reload my level...
![smart object are randomly rotated](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/febffd02-c66f-4175-afef-99f274e26709)
![smart object are randomly rotated02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/f6f1dc33-6ba9-41c7-abdd-a0f658e40256)
Walls are missing....
![walls removed by ggmax when reloading the game 02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/6016140a-cf51-4dcc-8afa-b3585018fa2d)
Walls and roof are missing....
![walls   roof removed by ggmax when reloading the game 03](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/85e50181-1f26-4bfe-ab11-f4109b4ab698)

here the total numbers of objects assets in my catacomb level
![5859 objects in ggmax level the catacombs](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/c623348b-cbd0-4ffb-a6af-f78081763d80)

i tried 4x, each time GGMAX reload my game without those objects the software keep deleting some objects.
ALL my backups have the same problem, i want to know what is happening...

The development of my game is at a complete standstill until this problem is solved, and I'm wasting precious time.
and I'm not going to risk a 5th time putting objects back where I put them before.
I know of NO software in the WORLD that deletes or destroys objects in a level, none.

I thought the problem was due to the number of coffins objects in my scene, so I deleted a lot of them and gave the objects “collision box” as their collision.
I saved and ran it again, everything was there, then I closed the software, restarted ggmax and BOOM back to square zero...

HERE i recorded the video 3 min where you see that the objects disappear.
https://streamable.com/2kkaio

**Comment by imothep85** [comment]
and when i try to LOAD the autobackup in ggmax it crashes..........
![crash when trying to load ggmax backups](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/fb06face-7f06-4152-829c-8184206da0e4)

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
