### ISSUE TITLE
Hands/weapons glitching

### ISSUE THREAD

**Issue by Allfatherodin** [TheGameCreators/GameGuruRepo#5564]
Hi,
Encountered a weird bug, regardless of weapons or game type (Standalone and or playing via editor).
For some reason once 'hands' are out, it's glitching all over the screen. initially thinking it was a bug with my level, I made a couple extras to have the same effect.
I even tested out a couple Demo games like 'Bounty'. I've attached screenshots.

Best regards,
A fan
![Screenshot_3](https://github.com/TheGameCreators/GameGuruRepo/assets/18305493/2f000f06-646d-4da6-ba6d-e61f8a80b9c6)
![Screenshot_4](https://github.com/TheGameCreators/GameGuruRepo/assets/18305493/c7394720-103d-4ee8-9131-6c5d02b1d987)
![Screenshot_5](https://github.com/TheGameCreators/GameGuruRepo/assets/18305493/6ccb33b6-a533-4bf7-800a-ed514d4eb659)

**Comment by Allfatherodin** [comment]
OS: Windows 10 Pro 22H2
CPU: Ryzen 7 5700x
GPU: AMD RX 7600
Resolution: 1080p

**Comment by DBird-1994** [comment]
Same thing happening on my end.  Reported by another user a month ago and also confirmed by several other people.  Unfortunately only labeled as a medium visual bug.  #5485

**Comment by LeeBamberTGC** [comment]
@Allfatherodin @DBird-1994 Still not able to reproduce this one for oms reason. Can one of you make a small standalone that shows this right away when the game starts, and attach it here. At least I may have a chance of seeing it as is, and from there have a few clues as to what might be causing this one, thanks!

**Comment by DBird-1994** [comment]
@LeeBamberTGC I can no longer reproduce this in either the EXP or the 2024.06.18 build.  So the problem has fixed itself at some point at least on my end.
