### ISSUE TITLE
Door Sliding

### ISSUE THREAD

**Issue by webdvdesign** [TheGameCreators/GameGuruRepo#5567]
Hello, Is it possible to add a Display Prompt to the SLIDING DOOR behavior to have a local and screen display as well ? Can you add that function ? Thank you

**Comment by Necrym59** [comment]
Done, update your steam workshop items to get the latest version

**Comment by webdvdesign** [comment]
Thanks, you succeeded, but the cross is missing when the mouse is on the object to be clicked, and the click is only possible if the mouse (cross) is on the object. This way, in my case, the drawers just fold and when I click on one, the other opens as well.
![Drawer1](https://github.com/TheGameCreators/GameGuruRepo/assets/171261266/df429610-2dd2-4ee9-a718-946f99dfd69f)

**Comment by Necrym59** [comment]
No changes were made to that area, and that scenario isnt what you asked about, it was never designed for doors in such close proximity. I would need the sample objects to test with if you can supply them,

**Comment by Necrym59** [comment]
You can try this version it will crosshair only in manual mode when close
[door_sliding_v30.zip](https://github.com/user-attachments/files/15518011/door_sliding_v30.zip)

**Comment by webdvdesign** [comment]
[Bedroom_CabinetWhite.zip](https://github.com/user-attachments/files/15518776/Bedroom_CabinetWhite.zip)
If you need anything else, tell me :) Thank you

**Comment by Necrym59** [comment]
Did you try the supplied version as this does as asked

**Comment by webdvdesign** [comment]
![Drawer Object ](https://github.com/TheGameCreators/GameGuruRepo/assets/171261266/0f03a2c5-e31a-4726-a7e3-953f731bc93e)

1. (White cross) + shows a little below the object, it is possible to lift it up a little so that it perfectly shows when the point is on the object (it is the **Green border** where the beginning and where the end).
2. (**Red border**) Can the text be fixed under the cross? as on behavior the "door rotate".
 Thank you!
 It will then be perfectly done and can be useful to others who want to create a drawer.

**Comment by Necrym59** [comment]
No the cross show up when within range set and within the confines of the object area
Set the text to Local - The text can only be shown based on the xyz orgin of the object at this time
In either case you will have to adjust the orgin of the Draw

**Comment by webdvdesign** [comment]
https://www.youtube.com/watch?v=CV1pa0xYYKo

1. Is there a possibility to fix the trigger on a door that has fallen off down the model door, you can see on video.
2. Text under cross i put in place and that is  fixed :)

**Comment by Necrym59** [comment]
Moved text to centre screen under crosshair - updated to core and workshop
