### ISSUE TITLE
GGMAX Bug - Standalone Game Export Problem

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5568]
After today's latest update it does not enstrain these folders when you export with standalone
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/14b4117d-ff96-47de-b36e-5c2705dff7c9)

@LeeBamberTGC

**Comment by Necrym59** [comment]
What version are you using sampey ,you should be using the exp version

**Comment by SampeyFS** [comment]
I use devtest

**Comment by SampeyFS** [comment]
This problem concerns are the game The Hermit I wouldn't know the reason xk why it doesn't extract here files

**Comment by SampeyFS** [comment]
I wanted to warn you that the horse now works the only problem that to that the player when he is going always gets off the horse alone you always have to get back on the horse

**Comment by Necrym59** [comment]
The problem is that the DEVTEST isnt yet designed for export to standalone, if you wish to use standalones then use the other branch either the EXP or official releases.

**Comment by SampeyFS** [comment]
yes I also tried with experimental nothing does the same thing

**Comment by LeeBamberTGC** [comment]
@SampeyFS Best not to use DEVTEST for regular game project work, and if used to test a bug fix, revert back to EXP build which is working to export standalone for other users. If the crash is happening WHILE you are exporting a standalone, it could be related to memory or storage limits.  Can you make a small video showing the crash, thanks!

**Comment by SampeyFS** [comment]
ah okay okay
