### ISSUE TITLE
animated entities not animating after lightmapping

### ISSUE THREAD

**Issue by bonesy23438** [TheGameCreators/GameGuruRepo#557]
after lightmapping a level on F3 settings the animation of the conveyor in scipack dlc does not animate
![Desktop Screenshot 2019 06 26 - 08 32 13 03](https://user-images.githubusercontent.com/37757086/60170631-bd02a580-9800-11e9-95df-d4307fa79aa8.png)
screenshot shows how it looks in test game eg not animating .i have recompiled shaders

**Comment by bonesy23438** [comment]
character entities not showing death animation in test game.I have some custom made entities that randomly do not show death animation after being kileed.It laso happens with stock character entities.
![Desktop Screenshot 2019 06 26 - 08 34 21 49](https://user-images.githubusercontent.com/37757086/60171038-add02780-9801-11e9-8e63-92ea4cb1f426.png) gun basically drops to floor then character remains frozen

**Comment by LeeBamberTGC** [comment]
Can you provide an FPM using stock assets, thanks!

**Comment by plemsoft** [comment]
The lightmapper do not support animations, the problem is that the Conveyor*.fpe files should use "defaultstatic = 0" in the fpe.

There is a few other animated objects in the scifi pack that also has this problem.

**Comment by Teabone3** [comment]
I've noticed this issue when using the SCI-FI DLC

**Comment by BerntSunde** [comment]
Hey I just tried change the defaultstatic = 0, it didn't help. So i looked at the fpe file, and you need to change "effect        = effectbank\reloaded\entity_anim.fx" :) Now it works perfectly. Oh I also changed collision mode to 1, but i am not sure it was needed.

**Comment by Pirate-Myke** [comment]
I just found that all I needed to do was to set defaultstatic = 0 to get them to animate after light mapping.
Used entity_basic.fx shader.
