### ISSUE TITLE
Tree felling

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5576]
It would be nice to have a tree felling animation with animation to add in RPG Games example cuts the tree gets ruined and falls down I hope it will come out it is a very interesting script with wood resource revenue

**Comment by mav3r1ck1981** [comment]
you can kind of do this now with the resource nodes

**Comment by SampeyFS** [comment]
yes but with the animation falling I already use it as you say I meant

**Comment by Necrym59** [comment]
It would be an done in an animation no need for a script

**Comment by SampeyFS** [comment]
yes

**Comment by SampeyFS** [comment]
can the thing be done?

**Comment by Necrym59** [comment]
Do it in your animation
