### ISSUE TITLE
GGMAX Bug - Triggered 'do not show at start' entities do not vanish when destroyed

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5577]
As the title states .... Spawned items do not vanish when destroyed 
Both set to explodable but the one that is spawned explodes but remains.
Just to clarify the second drone is just set to **Do Not Show at Start** and triggered to spawn and fall via a zone 

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/cc66c844-29d6-423c-841d-d804d6a15729

**Comment by LeeBamberTGC** [comment]
@synchromesh62 To save me a few minutes of level building, could you attach a very small stock level that shows what your video shows, so I can quickly load, run, see, debug, fix and update., thanks :)

**Comment by synchromesh62** [comment]
> @synchromesh62 To save me a few minutes of level building, could you attach a very small stock level that shows what your video shows, so I can quickly load, run, see, debug, fix and update., thanks :)

Ahh course i didn't think.
Max does not have anything like a drone to be able to create a demo so you cannot test it yourself anyway.
No worries i will just have to scrap the idea  :(
Thanks for reading anyway.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 You can always send me your drone :) Does sound like you have found an edge case bug here and I would be happy to fix!

**Comment by synchromesh62** [comment]
> @synchromesh62 You can always send me your drone :) Does sound like you have found an edge case bug here and I would be happy to fix!

Ok thanks Lee its appreciated but in your own time i know your busy. **files are attached.**
I have compiled a simple test all pre-setup in the zip, Map and Asset which should just be a case of unzipping and copying it over and then running.
The drone on the left will explode and vanish when shot
The Zone will spawn the one on the right that will explode but stay there when shot.
This is what i see.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/8b98223c-dd2e-4b17-a492-a4670456033f
[Lee-Drone-Test.zip](https://github.com/user-attachments/files/15764978/Lee-Drone-Test.zip)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed for the next DEVTEST build, and also you can change your FPE to include "isviolent        = 0 " that will stop the blood splat when the bot id destroyed. I have also added a new EXPLOSION HEIGHT slider under the damage property so you can offer the center of the explosion to match the height of your robot :)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/08daa6ea-e102-4d82-95bf-6351e498b428)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Hi Lee .. Fantastic  
Thank you so much !!
This is now more like a feature for non human Characters than a fix :)
Really appreciated thanks ..

**Comment by synchromesh62** [comment]
And confirmed working !!
Superb !! Thanks again :)
