### ISSUE TITLE
Clone Entity Question     ( flying animals)

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5579]
I realized today that the animals that are swept stay up then come down when you approach how could I solve this problem ? thank you very much

**Comment by davetgc** [comment]
Do you mean that flying animals land?

**Comment by SampeyFS** [comment]
Yes, exactly, they are high up as soon as you get close they fall

**Comment by Necrym59** [comment]
Cannot replicate any problems

**Comment by SampeyFS** [comment]
Unfortunately it happens, it will be the trees, anyway, it will sweep them from the bottom, I think it's the collection of the plants
