### ISSUE TITLE
error when recompiling shaders

### ISSUE THREAD

**Issue by bonesy23438** [TheGameCreators/GameGuruRepo#558]
when recompiling shaders i get an error message on the effect_animate64.fxshader
![Desktop Screenshot 2019 06 26 - 11 10 37 79](https://user-images.githubusercontent.com/37757086/60172052-cccfb900-9803-11e9-8c76-f9cceb51525e.png)
![Desktop Screenshot 2019 06 26 - 11 10 30 07](https://user-images.githubusercontent.com/37757086/60172053-cccfb900-9803-11e9-953d-21fb272a0117.png)

**Comment by LeeBamberTGC** [comment]
I could not find "effect_animate64.fx" in the stock shaders, where does this one originate from, thanks!

**Comment by plemsoft** [comment]
@bonesy23438 Thanks for reporting this,

Ups Lee was faster then me:
Just use "decal_animate8.fx" it should do the same :)

**Comment by LeeBamberTGC** [comment]
Closing this issue as it relates to a non-stock shader file.
