### ISSUE TITLE
MAX - Heads are culled separately from the rest of the character.

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#5581]
[Video on Streamable](https://streamable.com/49xzk8)

What I think is happening is that the "apparent size culling" is culling the character's head mesh as a separate entity from the body, and since the head is much, much smaller, you'll see the head get culled based on it's size much sooner than the body, leading to this weird "headless" appearance. And, size apparent size culling doesn't appear to take into account FOV (i.e. using a scope) it can be very obvious.

**Comment by LeeBamberTGC** [comment]
@fearlesswee Fixed this issue so no characters will hide part of their body using the Apparent Size culling system.  Will be in the next DEVTEST build.
