### ISSUE TITLE
GGMAX Enhancement - RPG Inventory

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5583]
It should be improved the inventory in my opinion too simple I attach a photo of a nice inventory for max :-)
![UpdateV19Showcase4-1920x1080-0a212109a81adb6d5dd506c6dc2df94a](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/13fc73d4-190b-4ea9-b894-f89cc3f5b935)

**Comment by mav3r1ck1981** [comment]
is that an inventory that you have created? If so yeah its nice and clean i like that. Or are you asking for additional functions such as the menu bar at the top etc? Ive seen that you inventory screens at custom so im not 100% what you are asking for

**Comment by SampeyFS** [comment]
No is an example to show

**Comment by mav3r1ck1981** [comment]
you could set up everything on the one screen like this is you wanted to, with a bit of work anyway, this is my current vendor screen: 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/61555547/4853d5be-e466-43db-a66f-8b2c193d657c)
i think the only thing missing is the XP info

**Comment by Necrym59** [comment]
Those sort of enhancements will come but not for quite a while, a lot more needs doing first
