### ISSUE TITLE
GGM Max BUG - Player death leads to Game Over screen no matter what

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5585]
While doing a bit of play testing I discovered that if my player dies, they will be routed to the Game Over screen every time. It doesn't seem to matter whether the Game Over screen is even connected to anything (as depicted below. Furthermore, adding a checkpoint to the level is intended to allow the player to start again at a specific point in the event of death. However since death always routes to Game Over, the checkpoint is rendered useless. I am using the stable public build.

I feel strongly that game lives should be entirely within the hands of the developer. Some games require endless retries, others require finite (but in some cases multiple) lives, and others are intended to be one life only. One cannot design any game they want unless they are able to make this choice for themselves.

![image (1)](https://github.com/TheGameCreators/GameGuruRepo/assets/42441542/606973f3-d447-4380-a79e-56c4c6603e3d)

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Fixed for next DEVTEST build, reintroduced the LIVES property in player start marker properties for full control as described above. Also added a detection of checkpoint markers, and if they exist in the level, player is given infinite lives so they can return to the checkpoint.

**Comment by Blood-Moon-Interactive** [comment]
Confirmed fixed
