### ISSUE TITLE
Max close without any warning

### ISSUE THREAD

**Issue by Peri32** [TheGameCreators/GameGuruRepo#5587]
I've been waiting a long time for a script that can be used to create vehicles for MAX's large maps, and thanks to Necrym59 we got Speeder. But unfortunately, when I attach it to models and drive a bit in the test, the software suddenly crashes without any error message and I have no clue how to investigate it. I tried different models, including those that come with MAX.

Here is a video: https://www.youtube.com/watch?v=VrcD8Fr1ZxY

**Comment by Necrym59** [comment]
Cannot replicate this, it isnt the behavior as far as i can see, it may be the model your using or a conflict with somthing else on your system.

**Comment by Peri32** [comment]
Hi I tried different models also stock ones, I think its something about the speed I moving I am not sure
