### ISSUE TITLE
GG Max - EXP - Workshop items not showing or updating again

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#5588]
As the title says, this bug is now reappearing after you fixed it.
After starting GG Max today, my first move was to update workshop, and no items showed up again.
After checking Steam, i noticed that i am not even subscribed to the items.

This was fixed, and has suddenly stopped working again.

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/a5f4e743-6b03-4e3d-98e0-72d400ec9123)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/68f36a48-1093-49ce-9f13-e308e6c3df38)

**Comment by SampeyFS** [comment]
Yes Today

**Comment by Tum1370** [comment]
This does work, I had the bug before and Lee fixed it a good while ago.
It is something to do with how Max Subscribes and Unsubscribes to steam workshop.
Clearly its broken again, because for me, it was working fine, and now it is not.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Here is the link to the old bug report for this same thing. That was fixed, but has reappeared.
Maybe something in the post can help you fix this.

https://github.com/TheGameCreators/GameGuruRepo/issues/5249

**Comment by synchromesh62** [comment]
> This does not work, I had the bug before and Lee fixed it a good while ago. It is something to do with how Max Subscribes and Unsubscribes to steam workshop. Clearly its broken again, because for me, it was working fine, and now it is not.

Ok then no worries
Just odd its working for me .. 
We havent had any EXP or retail updates for quite some time.
I wonder if its Steam related ?

**Comment by mav3r1ck1981** [comment]
i had the same earlier today, a verify and multiple attempts fixed it

**Comment by Tum1370** [comment]
I just tried verifying files, and exactly the same.
Nothing in workshop is subscribed to, or even showing in the Steam Workshop page as you can see in the screenshot.
Only thing that shows for me is "Lees Space Fleet".

**Comment by synchromesh62** [comment]
> I just tried verifying files, and exactly the same. Nothing in workshop is subscribed to, or even showing in the Steam Workshop page as you can see in the screenshot. Only thing that shows for me is "Lees Space Fleet".

What is **Lees Space fleet** ?
Never seen that.. Is that a Max thing :)

**Comment by synchromesh62** [comment]
> I just tried verifying files, and exactly the same. Nothing in workshop is subscribed to, or even showing in the Steam Workshop page as you can see in the screenshot. Only thing that shows for me is "Lees Space Fleet".

I think your looking in the wrong place 
Your looking here ... 

![WS1](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/c8c8a761-6389-465a-8b5a-871ef4872d97)

You should be looking here ..

![WS2](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/f493f538-c0d7-499d-b3e2-7b23583004b3)

**Comment by Tum1370** [comment]
@LeeBamberTGC Please Lee, just follow the old posts, and not what other people are saying here.
THis is once again not working.
I am not looking in the wrong place.
Clearly, Max is Unsubscribing from these items.

As you can see from the screenshot, This is thew workshop for Max, and it is totally empty.


![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/800c254a-5f20-44cd-8827-f37bb4873a29)

**Comment by LeeBamberTGC** [comment]
@Tum1370 When you click the update workshop button, wait then exit MAX, do you see download activity on relaunching MAX inside the Steam client, like so:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a8874c30-cf0e-475c-a87e-ece7e0afa83d)

Do you have the "WorkshopTrustedItems.ini" in your MAX root folder, i.e:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b335f811-2045-4336-b575-21e5b63de793)

After the download has finished and the files update in the Workshop tab you should see this in the DEVTEST branch:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b0510a85-4561-44e6-a778-d0f099039926)

**Comment by Tum1370** [comment]
@LeeBamberTGC These are the same instructions you gave me on the old post regarding this same issue, that i have linked above.
Nothing updates as nothing is subsribed to on Steam.
The WorkshopTrustedItems file is there, and i have posted it here so you can check.

Before and After clicking update, the only item there is "Lees Space Fleet".
This is even after updating, shutting max down, and restarting, Many times. Nothing.

Please read that old post that i link, because you did figure this out in that.
I am not sure why this suddenly stopped working again, but it has.

OLD POST: Same issue.

https://github.com/TheGameCreators/GameGuruRepo/issues/5249

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/06324f4b-5eee-40bd-bfbf-32a6fa61e25a)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/d9a0307a-a7ce-4240-ab2f-a2003944cbb7)
![3](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/925f1979-7607-4d2c-b501-cc0f6b32ddf9)

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for the link to the old post, looks like I was in danger of going through that whole process again :)  Can you send me your latest .LOG file, the one that would be produced after you (a) clicked the update button, (b) waited for the prompt to close MAX, (c) close MAX, (d) relaunch MAX, open Steam client to view download activity, (e) wait until all download activity ceases, (f) exit MAX, relaunch for third time, (g) go to the Workshop tab, and wait until it finished any activity, then send me the .LOG file at that point in time, it should contain the debug data I need to know what is happening in the background. If you can also do a video recording of that whole sequence of steps, I can get a handle on where it might fail along the way, thanks!

**Comment by Tum1370** [comment]
@LeeBamberTGC AM sorry i can not do videos, and dont know where to upload them to.
I have followed your instructions exactly.
Launched Max, and gone to WORKSHOP tab
a. Click Update
b. Waited for prompt to shut Max
c.  Shut Max down.
d. Launched Max (Steam client had nothing downloading)
e. There was nothing to wait for as Steam downloaded nothing.
f.  Shut Mx down, Then relaunched Max.
g. Goto Workshop Tab again.

There is nothing showing up in the workshop tab, other than the Less Space Fleet.

When this was working fine, The Workshop had all the items showing, and not just Lees Space Fleet.
I dont know how many other ways there is for me to say this now. Workshop is totally empty in Max Other than Lees Space Fleet.

I have attached the LOG file after the instructions i followed.

The 2 images below are all that show up in Max Workshop tab, Before, and After clicking update, Everytime i launch Max, it is the same.
Nothing in workshop.

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/79173961-5e2b-4f05-9e84-b9899619cf75)
![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/99f1c290-2201-427a-8105-da5e9904e3f8)


[Guru-MapEditor.log](https://github.com/user-attachments/files/16030789/Guru-MapEditor.log)

**Comment by Tum1370** [comment]
@LeeBamberTGC Some additionally information regarding this.
I thought i would try going back to normal release rather than using Experimental version.
After setting BETA to NONE. All that happened on my Steam Client was the name of GameGuru Max changed.
Nothing downloaded, at all, Just in my library the name was changed to the none beta version.

Same again when i set BETA to EPERIMENTAL version.
Nothing Downloaded or updated.
Just the name of Max then in my library changed to saying Eperimental version.

Maybe this problem is related to Steam ???

**Comment by LeeBamberTGC** [comment]
@Tum1370 Thanks for the latest LOG file, it was useful. Looks like the workshop items are returning an item state of "k_EItemStateInstalled" instead of "k_EItemStateNone" which suggests they are subscribed to but out of date. I have added some code that will proceed to subscribe and download even if the installed stale state shows, that should get past the current impass. Let me know if you get further with the DEVTEST build just uploaded.

**Comment by Tum1370** [comment]
@LeeBamberTGC 
Thanks Lee, i have the workshop working now, All the items are once again showing up in the Workshop Tab.

Ill close this issue again now as its working correctly again. Thanks
