### ISSUE TITLE
EBE issues using Tab

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#559]
The EBE has an issue once you press "E" to exit
1 .. Sometimes your left with just a shadow after you press "E" to exit until you select an asset.
2 .. If you have a roof and press tab then assets you try to place are invisible
To demonstrate I have a room with half a roof.

Not Tabbed

![ebe1](https://user-images.githubusercontent.com/35708217/60217953-de49ad00-9865-11e9-8f2b-01caee6b9abe.png)

Tabbed

![ebe2](https://user-images.githubusercontent.com/35708217/60218043-0df8b500-9866-11e9-888c-78881ba59145.png)

**Comment by synchromesh62** [comment]
Any chance this will be looked at any time soon ?
Its really hindering the use of it :(

**Comment by LeeBamberTGC** [comment]
Was same as the other bug reported, this one also fixed. Shot to prove:

![image](https://user-images.githubusercontent.com/35840583/77478661-3f62d900-6e16-11ea-9042-05457c06f522.png)

**Comment by synchromesh62** [comment]
Fantastic !!
Thanks so much :)
