### ISSUE TITLE
Standalone does not make inventory work

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5590]
I moved my game after a long time you can't see anything in the inventory as you can see even the inventory handle

![Desktop Screenshot 2024 06 13 - 16 01 07 33](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/d1baa4c2-a96e-454b-a98b-f66ede60de44)
![Desktop Screenshot 2024 06 13 - 16 01 54 53](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/8586c498-0cd4-41f3-952a-119fa358f03f)

**Comment by SampeyFS** [comment]
![Desktop Screenshot 2024 06 13 - 16 16 35 03](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/bf05691f-771f-4d3c-ae3b-4b1a02bd82cb)
![Desktop Screenshot 2024 06 13 - 16 17 25 87](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/132f69a9-8425-4b18-9a99-551441d3b074)

**Comment by SampeyFS** [comment]
It hits my heart hard to say this but we're not there with max

**Comment by Necrym59** [comment]
Looks like you havent copied across the project container tsv files from the old project

**Comment by SampeyFS** [comment]
Yes, that's right, standalone doesn't extract the folder that contains the one, in fact I'm missing it  @Necrym59

**Comment by Necrym59** [comment]
Well copy it

**Comment by SampeyFS** [comment]
The inventory handle is still not working
