### ISSUE TITLE
GGMAX DEVTEST - Error when hurt if MyArmourToughness set higher than 10 

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#5591]
This errore will pop up when hurt in gameplay.
![gameplayererror](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/91d75e27-8435-49ff-b4cb-5d5b02acc20f)

**Comment by AmenMoses** [comment]
local user_defined_global_toughness = "MyArmourToughness"
     if user_defined_global_toughness > "" then 
      if _G["g_UserGlobal['"..user_defined_global_toughness.."']"] ~= nil then 
	   chanceofarmourdegredation = math.random(1,10 / _G["g_UserGlobal['"..user_defined_global_toughness.."']"])

If  g_UserGlobal.MyArmourToughness is 0 then 10/0 will give infinity and result in a NaN error in the parameter to math.random, that would cause the error shown.

I could suggest a fix if I knew what MyArmourToughness is supposed to represent!

**Comment by Necrym59** [comment]
It only seems happen if the "MyArmourToughness" value is set to higher than 10

**Comment by AmenMoses** [comment]
Ahh, that makes sense as then the second parameter to random will be less than the first, maybe that is what is generating the error.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Do you want to have a stab at error trapping the use of the MyArmourToughness variable and send me the code fix, I can then drop it in :)

**Comment by LeeBamberTGC** [comment]
@Necrym59 Fixed for next DEVTEST build!  The new code:

	   local oneintenchance = _G["g_UserGlobal['"..user_defined_global_toughness.."']"]
	   if oneintenchance < 1 then oneintenchance = 1 end
	   if oneintenchance > 10 then oneintenchance = 10 end
	   chanceofarmourdegredation = math.random(1,10 / oneintenchance)
	   if chanceofarmourdegredation ~= 1 then

**Comment by Necrym59** [comment]
forgive me isnt that the same as saying:- 

if _G["g_UserGlobal['"..user_defined_global_toughness.."']"] >= 10 then
   _G["g_UserGlobal['"..user_defined_global_toughness.."']"] == 10
end
chanceofarmourdegredation = math.random(1,10 / _G["g_UserGlobal['"..user_defined_global_toughness.."']"])

**Comment by LeeBamberTGC** [comment]
@Necrym59 That would have worked too :)  Many ways to swing a cat!  One small correction:

_G["g_UserGlobal['"..user_defined_global_toughness.."']"] = 10
