### ISSUE TITLE
GGMAX EXP - Possible bug with Occlusion & Object culling making object disappear.

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5593]
the function inside the engine "Object culling" make objects flickering disappearing of some kind...
They keep disappearing appearing all the time and it look like it's random...

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/7fdc7b0a-13a0-443f-bd6e-a0850afe814c

EXP VERSION
![levels are destroyed](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/2f640332-e086-4918-8d19-c5c11e180622)

**Comment by plemsoft** [comment]
@imothep85 When did this start ?, its been in the exp a long time now ?.
Also on the same screen could you try to check: "Debug" and "Debug Bouding Box" and record the same video with these on, thanks :)

**Comment by imothep85** [comment]
its new its just now in the latest exp version

**Comment by synchromesh62** [comment]
@plemsoft 
I can replicate this kind of thing here when the **Object Culling** tick box is enabled.
However my level is multi-textures and is a **single** Model 
I just don't tick that box as i assumed it worked for models in the distance but when its all one model I'm not so sure ?
The Vid shows me ticking it on and off in the editor.
Hope it helps bring something to light.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/a657598e-e181-4b00-8dfa-eecf4750959b

**Comment by imothep85** [comment]
Not only the object flickers, with the occlusion culling & object culling bug, 
but ALL my levels objects are now at wrong places....
and it's a massive fps drop... from 100fps now everything run at 12 to 20fps...
![fps storyboard](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/08f8a506-eae8-4ec4-9813-6b557f9b391a)

![fps level](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/7514aeba-3d7b-4ed6-bf5d-98df454945e2)

**Comment by Necrym59** [comment]
@imothep85 
_"so i prefer to not touch my game until the exp is fixed"_
That is not very helpful in solving any problems, if your not going to be more forthcoming in trying to trace an error then the post will be deleted.

**Comment by imothep85** [comment]
my game is now with all the object at wrong places, floating as you can see in the screenshot, i'm not going to take the risk to destroy 5 month of hard work on my game

**Comment by Necrym59** [comment]
Well if you cant take the time to help us find what the prblem is then dont expect anything

**Comment by imothep85** [comment]
help yes, but not to save my project

**Comment by synchromesh62** [comment]
> my game is now with all the object at wrong places, floating as you can see in the screenshot, i'm not going to take the risk to destroy 5 month of hard work on my game

As long as you have backed up the mapbank folder at least there shouldn't be a problem if you destroy the lot although i backup the GameGuruApps folder on a regular basis ... You just copy it back .. Quite a few times i have deliberately scrapped a level I'm not happy with and reverted back to a earlier backup.

**Comment by imothep85** [comment]
well i would like to know HOW is that possible that the engine moves the 3d objects and put them on wrong place...what part of the code does that....that a terrible problem i never saw in other engines.

**Comment by synchromesh62** [comment]
> well i would like to know HOW is that possible that the engine moves the 3d objects and put them on wrong place...what part of the code does that....that a terrible problem i never saw in other engines.

Yours is the only report so far of this particular issue so if you want it sorted the more info you can give about your level the better. Remember Lee has to try to replicate your issue to fix it.

**Comment by imothep85** [comment]
As I said, I didn't do anything, I just loaded the levels, and I saw all my objects floating, in the wrong place,
it happened once when the update was done, and the second tile everything was back to normal and now everything floats again.

Objects are moved VERTICALLY on the y axis, not horizontally BUT just vertically.

**Comment by imothep85** [comment]
Here i show in this video, the horror of what is happening NOW with the latest EXP version of ggmax !
shareallfiles.net/zTEYsS


ALL my levels (10 levels of my game)
ALL MY BACKUPS have the same problem, ALL.
The OBJECTS are misplaced, in the X axes.
In this video i show the level THE CAVE, all the cables, are now floating...
others props metals parts of my environment are floating....etc

**Comment by plemsoft** [comment]
For the record: the original issue here with  occlusion and flickering objects was fixed and will be in the next update. Also the problem from synchromesh62 was also fixed, @LeeBamberTGC In the latest commits.

**Comment by imothep85** [comment]
Thanks to all of you :D
