### ISSUE TITLE
GGMAX EXP latest version destroy levels, Y POSITION WRONG !!

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5595]
Here i show in this video, the horror of what is happening NOW with the latest EXP version of ggmax !
[shareallfiles.net/zTEYsS](https://github.com/TheGameCreators/GameGuruRepo/issues/shareallfiles.net/zTEYsS)
[https://streamable.com/3fglk7](url)

ALL my levels (10 levels of my game)
ALL MY BACKUPS have the same problem, ALL.
The OBJECTS are misplaced, in the Y axe.
In this video i show the level THE CAVE, all the cables, are now floating...
others props metals parts of my environment are floating....etc
In this video i load also different backups, made by ggmax and you can see that they have ALL the same problem !

The rest of my game, ALL my 10 levels, ALL the backups have now the same problem !....

**Comment by MonkeyFrogStudio** [comment]
Why ... why ... or WHY are you actually building an actual game using the EXPERIMENTAL version? It's for TESTING, not for creating your actual game.

**Comment by imothep85** [comment]
!!! I FOUND THE BUG !!!

it's generated by the .LOD system in ggmax !
IF DISABLED EVEYTHING IS BACK TO NORMAL
IF THE LOD IS ENABLED ALL THE SCENES ARE WRONG ON Y AXE
![LOD SYSTEM](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/7e28ed45-3a1e-400e-9f46-d3cd2f961b8c)
![fps level](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/9a39f363-c1a1-4beb-8e44-614f679fef3f)


and with the LOD of ggmax disabled....
everything is back to normal, but we cant use the lod then...
![LOD SYSTEM 02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/29502a7c-4e1f-494f-be38-a777ca571960)

**Comment by imothep85** [comment]
> Why ... why ... oh WHY are you actually building an actual game using the EXPERIMENTAL version? It's for TESTING, not for creating your actual game.

because i create HUD for ggmax for TGC !

**Comment by MonkeyFrogStudio** [comment]
Testing your HUD in experimental is one thing. Having a 10 level game in experimental is another. It's not wise to build a game in experimental ... at all. Because, you know, it's EXPERIMENTAL. And that means stuff will break. Use at your own risk, etc.

**Comment by imothep85** [comment]
my game was made in the standard public THEN Dave give me access to the exp; i switched to it to test & develop the HUD packs for tgc.

**Comment by MonkeyFrogStudio** [comment]
You can switch back and forth between experimental and public builds. So, you use experimental for the huds, but switch back to the public build for your game. This way, you don't run into the issues you're experiencing and complain about the 'horror' of what happened to all 10 of your levels.

**Comment by Necrym59** [comment]
Have you locked the object is place?
if it still gives problems then email/contact Preben if you think its a LOD problem

**Comment by imothep85** [comment]
i did he normally has all my game older version to check !

**Comment by imothep85** [comment]
FIXED by PREBEN with the latest version of his LOD tool !
