### ISSUE TITLE
GGMAX Bug - Perfomance problem, GPU frame rate drop

### ISSUE THREAD

**Issue by BryanDes** [TheGameCreators/GameGuruRepo#5598]
In the last update they did they made some graphical change and whatever changes they made is causing my GPU to go overboard after saving my level the frame rate drop in the video that's actually obs the issue i'm experiencing is the map mirror images and the yellow
[](url)https://youtu.be/DbP4EelWsvs

**Comment by BryanDes** [comment]
> @BryanDes - Can you post your system specs please.

Before the update that was released the 21th i didn't have any graphical or performance issues GGM was running super smoothly here is my CPU and GPU.  Processor

Intel® Core™ i5-8400 CPU @ 2.80GHz
Device Details
Manufacturer
GenuineIntel
Description
Intel64 Family 6 Model 158 Stepping 10
Architecture
x64
# of Cores
6
# of Threads
6
Processor Base Frequency
2808 MHz
Current Voltage
9.
Level 2 Cache
1536 Kb
Level 3 Cache
9216 Kb
Processor Id
0x906EA
Availability
Running at full power.


Intel® UHD Graphics 630
Driver Details
Up to date
Provider
Intel Corporation
Version
31.0.101.2115
Date
11/16/2022
Device Details
Adapter Compatibility
Intel Corporation
Video Processor
Intel® UHD Graphics Family
Resolution
1920 x 1080
Bits Per Pixel
32
Number of Colors
4294967296
Refresh Rate - Current
59 Hz
Refresh Rate - Maximum
60 Hz
Refresh Rate - Minimum
23 Hz
Adapter DAC Type
Internal
Availability
Running at full power
Status
This device is working properly.
Location
PCI bus 0, device 2, function 0
Device Id
PCI\VEN_8086&DEV_3E92&SUBSYS_12381025&REV_00\3&11583659&0&10

**Comment by BryanDes** [comment]
update i've just created a 5km procedurally generated level and it doesn't have the same issue as the blank level after saving the issue with this level is just a slight amount of framerate drop which i also didn't have before the update that was released the 21th

**Comment by SampeyFS** [comment]
Are you using an integrated video card? is normal Intel® UHD 630 graphics card

**Comment by BryanDes** [comment]
@SampeyFS Yes i am

**Comment by imothep85** [comment]
UHD 620/630.....

![main-qimg-e314c4b46d33a996ca9d94d0d92ca857-lq](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/277deb43-e0f4-4cc7-87fa-635c87516ac5)

**Comment by BryanDes** [comment]
@imothep85 - GTA V and Skyrim run super smoothly on my desktop

**Comment by SampeyFS** [comment]
Those kind of ( Video Cards ) use shared Ram can't make it run a program like Max you have to put a video card ( if it's not a laptop )

**Comment by SampeyFS** [comment]
![Desktop Screenshot 2024 06 26 - 12 54 29 48](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/333e3fff-5b57-46c9-803f-ce6dc0de6ef4)
:-) :-)

**Comment by imothep85** [comment]
310 fps in an empty level...

**Comment by BryanDes** [comment]
@imothep85 - When GGM was updated the 21th did it automatically apply higher level of visual graphics cause i've click the option Reset Visual and it fix the issue.
