### ISSUE TITLE
Improve entity painting

### ISSUE THREAD

**Issue by tomik18** [TheGameCreators/GameGuruRepo#560]
It would be a good idea to improve painting. It is very frustrating if you paint trees, and paint a tree on another tree.

**Comment by LeeBamberTGC** [comment]
Starting this off as a bug, as you should not be able to use the spray tool with a tree to paint on TOP of another tree, it should shuffle them within the radius.  If this is not the case, provide step by step on how to reproduce it.

**Comment by tomik18** [comment]
sorry Lee my fault, everything is OK
