### ISSUE TITLE
GGMAX Bug - Lights do not reset when loading a save.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5602]
As Stated .. Lights do not reset when loading a save.
As you see in the video i save the map **"before"** activating the lights.
Once the lights are activated I reload the save.

The Lights are still on..

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/a64a8d29-c4bb-48e4-933c-862bcd1d8a22

**Comment by SampeyFS** [comment]
Yes, I reported it a long time ago but it's still like this, even Lua doesn't work (some)

**Comment by LeeBamberTGC** [comment]
@SampeyFS Fixed for the next DEVTEST build - should be up in an hour.

**Comment by SampeyFS** [comment]
I confirm that the lights work correctly now there are the lua which instead (are loaded) when the save is loaded @LeeBamberTGC
