### ISSUE TITLE
GGMAX Bug - 3D sound breaks when near a triggered item

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#5604]
The 3-D loop sound script works fine on its own but when you put a triggered item within it sound range it breaks. I made a quick little demo showing the problem. I have an enemy that is in the zone with the 3-D sound and as soon as you step on the trigger to activate him the 3-D sound automatically goes to full volume or low volume and then it won't fade in and out at any distance. Here's the demo level.
[test 3d sound.zip](https://github.com/user-attachments/files/16042388/test.3d.sound.zip)

**Comment by Kitakazi** [comment]
I have also have this issue.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by mike123yy** [comment]
Yeah, it still happening. If you place one 3-D sound zone it seems to work fine but if you use more than one then they break. It seems to be the same with other sound zones too. If you use the fade in or fade out sound zone more than once they break as well.

**Comment by Kasseyus** [comment]
@mike123yy Can you please make a short video demonstrating this issue so I can attempt to recreate it on my system?

Also, are you running DevTest, Experimental or Default?

**Comment by mike123yy** [comment]
[3dsoundtest.zip](https://github.com/user-attachments/files/17401167/3dsoundtest.zip)
this is probably better than a video, I made a quick level with three clusters of trees. Each cluster has a 3-D sound zone placed next to it. If you walk up to the trees the sound will play but then it won't turn off. It doesn't seem to happen with one zone but once you go over that this happens. The original post was that the 3-D sound was breaking next to a trigger zone but with it malfunctioning without the trigger zone it's hard to tell if the original problem still happening or not. I made the map in the first post that should demonstrate the problem with triggers if it still happening.

**Comment by Kasseyus** [comment]
@mike123yy Hello.  The 3dsoundtest.zip file attached above seems to be corrupted, as I cannot load it into my copy of MAX.  Can you please re-send me the file and I can try again.

If you could give it another try first though, as that particular script was recently edited to resolve a similar, but unrelated bug which may have also fixed this issue.

**Comment by mike123yy** [comment]
I gave it a try on my already existing levels and everything was the same so I started putting together a new demonstration for you, but I noticed after testing my new demo everything was working properly. so, I went back to my old levels and deleted all the sound zones and redid them and now they all work properly. so whatever you guys did seem to fix the 3d sound zone. although, like I said if you have them placed down before the fix they seem to be broken so you have to replace them. not really a big deal though. other than that small hitch it seems to be working good!
