### ISSUE TITLE
GGM Bug - Adding too many items to loot table causes Max to crash

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5607]
While experimenting with the loot table in character behaviors (such as Character Attack), I wanted to know how many items we could add to the drop list. On the 10th item the software crashed so I tried again, and consistently it crashes on the 10th item. I then added a bunch of individual items, made them all collectible, and made sure no item was selected more than once and on the 10th item, Max crashed. This was done in the stable retail build. Video below demonstrates.

https://youtu.be/zD0-YllwQJY

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Fixed for next DEVTEST build, related to some bad string handling, now okay for 10 items:
![image](https://github.com/user-attachments/assets/b263b17d-20aa-45dd-b17a-721903d142e5)
