### ISSUE TITLE
Added Product Quantity shop function

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5608]
To have a correct shop you need to add the quantities of the product for example leathers 20 Quantities as shown in the photo

![Screenshot 2024-07-01 094245](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/a363ed6b-ac90-4ea1-ab9a-e3ab8c4e119b)

**Comment by Necrym59** [comment]
No, the individual item itself will not have a quantity. This will be dealth with later when quantities are part of the inventory system.
