### ISSUE TITLE
Soundslots 5 and 6 do not work with the Visual Behavior Editor

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5609]
In the Visual Behavior Editor if you select in the logic box "Always - Play Sound" and then try to add '5' or '6' it will not play the audio from those slots. 

Normal text scripts play the sound from those slots fine, its only in the Visual Behavior Editor you cannot play sound in slots 5 or 6.

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Can this issue be flagged as bug? It has nobody assigned to it and it's very lonely. :( 
Not sure if it's really a bug or if the additional SoundSlots 5 & 6 that were added just never got added into the visual behavior editor.

**Comment by LeeBamberTGC** [comment]
@Kitakazi You should be able to use PlaySound(e,5) and PlaySOund(e,6) so marking as a bug:
![image](https://github.com/user-attachments/assets/a0461f53-798b-4c67-96a0-ce97390399f0)
