### ISSUE TITLE
building editor black screen

### ISSUE THREAD

**Issue by ZD-ZMA** [TheGameCreators/GameGuruRepo#5615]
![Screenshot (296)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/307dcbd6-f264-481e-abcf-da76cacc0903)
building editor loading as black screen... reminds me of the amd issue we all had a few months ago...

**Comment by ZD-ZMA** [comment]
it sucks because i literally needed this right now and cant proceed the level without it...

**Comment by DBird-1994** [comment]
It's a known issue and has already been reported.  Unfortunately MAX is only getting 4 updates per year to the public build.  So the earliest you could hope to get a fix would be in September, sorry.

**Comment by ZD-ZMA** [comment]
> It's a known issue and has already been reported. Unfortunately MAX is only getting 4 updates per year to the public build. So the earliest you could hope to get a fix would be in September, sorry.

ah. i didnt know it was a known bug. sorry,
