### ISSUE TITLE
GGMAX Bug - GetGamePlayerStateCameraFov() and SetPlayerFOV(fov) is not setting the correct FOV

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5616]
The FOV commands above are busted. They do not set the correct player FOV. You can see this with the Teleport script, which uses the commands. Here is a video showing my FOV being changed to an incorrect FOV. 
https://youtu.be/eM5mVwYsNms

This video is using the teleport script but it doesn't matter which script simply using the commands 
GetGamePlayerStateCameraFov() and SetPlayerFOV(fov)
will give the player the incorrect FOV.

**Comment by LeeBamberTGC** [comment]
@Kitakazi The "GetGamePlayerStateCameraFov" and "SetPlayerFOV" commands are not the inverse of each other, for that you should use "GetGamePlayerStateCameraFov" and "SetGamePlayerStateCameraFov".

The "SetPlayerFOV" command is a modified command from way back legacy days and under the hood looks like:

t.visuals.CameraFOV_f = (20 + ((YourPassedInValue + 0.0) / 114.0)*180.0) / t.visuals.CameraASPECT_f;

What is it you are using these commands for, and are they used incorrectly in any of the stock scripts?

**Comment by Kitakazi** [comment]
I was trying to make a script that would let me set the Camera Plane when triggered. I made something like 

function setcameraplane_main(e)
 if g_Entity[e]['plrinzone']==1 then
   SetCameraPanelDistance(200)
end

And it did not work but it did change the value on the editor slider it just wasnt sending that value through. Preben told me that in order to make any camera script work you have to set the player FOV. Thus my script is now 

function setcameraplane_main(e)
 if g_Entity[e]['plrinzone']==1 then
   SetCameraPanelDistance(200)
   fov = GetGamePlayerStateCameraFov()   
   SetPlayerFOV(fov)
Destroy(e)
end
end

I will try using SetGamePlayerStateCameraFov and see if it works. 

Which yes the stock Teleporter script uses GetGamePlayerStateCameraFov and SetPlayerFOV which may be why it is broken and changing the players FOV when they walk through the teleporter. On the EXP version btw.

**Comment by LeeBamberTGC** [comment]
@Kitakazi For the next DEVTEST build I have added a new command called GetPlayerFOV so the set is more intuitive, but for now you can also use "g_PlayerFOV" instead of "GetGamePlayerStateCameraFov()"

**Comment by Kitakazi** [comment]
Sweet, thank you.

**Comment by AmenMoses** [comment]
@LeeBamberTGC  Cine|Guru uses SetCameraPanelFOV to reset the FOV after a cinematic, the value to set it back to is originally acquired using GetGamePlayerStateCameraFov().

Is this combination still working?

**Comment by LeeBamberTGC** [comment]
@AmenMoses Nothing was changed, just a new command added to complete the set. It would be great if someone can confirm the CineGuru FOV is properly restored after a sequence.

**Comment by Kitakazi** [comment]
I will test it out in a couple of days to make sure it's alright. I just got LASIK eye surgery this morning so can't do much for a day or two

**Comment by Kitakazi** [comment]
I just tested and everything is working fine :)
