### ISSUE TITLE
Maps no longer loading in properly

### ISSUE THREAD

**Issue by AverageIndieDev88** [TheGameCreators/GameGuruRepo#5619]
I've posted this in discussions on Steam, but sometime around the beginning of June 2024 there was an update and ever since then i can no longer work on my project. Hours worth of work just disappear when loading back into the editor. It's incredibly disheartening after spending money on assets, coming up with a story and solid road map, get this deep into it, and now nothing i build stays where its supposed to or just doesnt load in at all.
![20240709165338_1](https://github.com/TheGameCreators/GameGuruRepo/assets/175164827/70f56856-0923-4cc1-9944-fd863da12af8)
![20240709165221_1](https://github.com/TheGameCreators/GameGuruRepo/assets/175164827/5272d94d-2e59-4abf-8424-7e03c178cd13)

I'm wondering if it has something to do with trying to render everything in too fast and before anything can be dumped from the memory it just fails our rendering the rest and doesnt retry when memory is freed up. might make for longer times to load in but im sure everyone would rather an extra 2-3 minutes to load our maps to edit rather than hours of work just gone.

**Comment by LeeBamberTGC** [comment]
@AverageIndieDev88 We added an auto backup system not long ago that may have captured some of your older levels in their uncorrupted state. Can you email me (lee@thegamecreators.com" your FPM level that has been corrupted, plus any related FPM files that may exist in the auto backup area, typically found at: "GameGuruApps\GameGuruMAX\Files\mapbank\_automatedbackups". This issue reminds me of the old object group bug that has recently been fixed, and I am assuming you are perhaps on the latest public release from June.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
