### ISSUE TITLE
sleep system

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#5622]
I suggest adding a sleep system in the form of a script in the menu of which you can adjust the number of hours of rest in parallel with this, add a fatigue system. In addition to the above, add a bed and a sleeping bag

**Comment by SampeyFS** [comment]
Added Global Effet to link to RPG State like eating and drinking
![Screenshot 2023-09-20 234124](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/069b03c2-79b6-4ac8-a4b0-989193cd088f)

**Comment by Necrym59** [comment]
You can add whatever you want as a user global even a "fatigue" variable into the rpg player state etc.
There already is a sleep behaviour that can attach to whatever object, you can select the time to rest, i will add in the option to update a user global (eg update the "fatigue") as well soon.

**Comment by Necrym59** [comment]
Sleep has been updated to allow for a User Global _(eg: MyFatigue)_ to be modified with a value for every hour of sleep.

**Comment by SampeyFS** [comment]
A thousand thanks

**Comment by SampeyFS** [comment]
It works great the only problem is that when you sleep it goes over the bar like MyFood did which now works @Necrym59

**Comment by Necrym59** [comment]
@SampeyFS  - OK that problem has been fixed and the workshop version uplouded
