### ISSUE TITLE
Workshop does not update

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5623]
Workshop doesn't update it says it's updated but if it sees (today) it says 768 scripts but in the end there are 765 I know because you've seen them all one by one (you don't need to see the number) it puts them right but it doesn't update in max

**Comment by SampeyFS** [comment]
![image](https://github.com/user-attachments/assets/8d84f1f2-d5ea-4696-be2e-945fafdbc6d0)

**Comment by SampeyFS** [comment]
if you look it's the usual 765 nothing new so even a Czech sees it doesn't update ahahahah

**Comment by synchromesh62** [comment]
> if you look it's the usual 765 nothing new so even a Czech sees it doesn't update ahahahah @LeeBamberTGC

Are you following the screen prompts **Exactly** .. For example your screen shot tells you to relaunch Max telling me you have not completed the procedure .. This is how it should work and usually its a process where you have to relaunch Max a few times for Steam to Update.


https://github.com/user-attachments/assets/ea105f5d-c963-41f5-97f2-44852d0451d2

**Comment by SampeyFS** [comment]
yes nothing is always the same sorry but try

**Comment by SampeyFS** [comment]
You can update it tonight until tonight but it doesn't matter, they are always the same, it doesn't download anything

**Comment by LeeBamberTGC** [comment]
@SampeyFS This issue has been confirmed fixed in the DEVTEST build, are you using this build when updating and relaunching for the latest Workshop items?

**Comment by SampeyFS** [comment]
Yes but it hasn't updated for 3 days anymore, strange

**Comment by LeeBamberTGC** [comment]
@SampeyFS When you get the screen shown in your first image, it states:
![image](https://github.com/user-attachments/assets/8c42df0a-91a8-4ee7-9f03-e94e58e23b05)

You then need to exit MAX and relaunch it through the Steam client, and you will notice it will trigger an update of all the files, give it 10 minutes to complete. Then take a new snapshot of the workshop tab area so I can review the dates shown, thanks!

**Comment by SampeyFS** [comment]
![Screenshot 2024-08-20 085204](https://github.com/user-attachments/assets/91a148a9-45db-4b2c-a55d-0d3c3e6ff120)

**Comment by LeeBamberTGC** [comment]
@SampeyFS I compared your latest one with the shot you posted a while ago and it does look like it is updating your scripts:
![image](https://github.com/user-attachments/assets/bec5cf25-11a2-4c17-986f-105d5df5a78b)
