### ISSUE TITLE
GGMAX Possible Bug -  Text In Zone

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#5624]
The text game element doesn't to work it is hit and miss i have tried using the trigger point element that doesn't work but the ones i set up earlier all work very frustrating

zeebon

**Comment by Blood-Moon-Interactive** [comment]
Couple things - first make sure that you have updated your workshop items to eliminate that as the issue. Second try using a regular zone and just applying TextInZone behavior to it. See if that is any better. I honestly had forgotten the text zone was there but it makes me wonder if it's not referencing the most up-to-date behavior. Hope that helps - let us know

**Comment by zeebon** [comment]
Done all that still doesn’t work yet previous ones do even created a new level wouldn’t work on that

**Comment by zeebon** [comment]
Done all that still won’t work even made new level didn’t work on that either
Sent from my iPhone

On 13 Jul 2024, at 19:11, Blood Moon Interactive ***@***.***> wrote:

﻿

Couple things - first make sure that you have updated your workshop items to eliminate that as the issue. Second try using a regular zone and just applying TextInZone behavior to it. See if that is any better. I honestly had forgotten the text zone was there but it makes me wonder if it's not referencing the most up-to-date behavior. Hope that helps - let us know

**Comment by Necrym59** [comment]
Zeebon can you post a sample and video of a map that isnt working with the textinzone so i can investigate it.

**Comment by zeebon** [comment]
uninstalled the program then reinstalled it seems to have sorted the problem out thanks for your help and suggestion's
