### ISSUE TITLE
texture rename importer issue

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5626]
hello. Not sure if this is a ME problem with exporting blender work, but when importing the text name has alsorts of characters in the name in ggmax that shouldn't be there.

![image](https://github.com/user-attachments/assets/edb6386c-d0f1-4e3c-8bbc-889421b3391b)

and because its renaming them, it means i have to then manually import the textures which takes a while!

**Comment by casigus** [comment]
![image](https://github.com/user-attachments/assets/495819c3-e736-462e-b744-f4da387f4efb)

**Comment by GraPhiX-Guru** [comment]
looks like you have spaces in the texture names replace the spaces with underscores or remove them

**Comment by casigus** [comment]
noted!!! I'll give that a go!
