### ISSUE TITLE
GGMAX Bug - Game Executable Icon not transfering to exe for Stand Alone builds

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5632]
In the video below I'll demonstrate that while I have a custom icon created and added for my stand alone project, when the game is exported to stand alone the .exe file retains the default GameGuru Max icon instead.

https://youtu.be/VX1lynToqcI

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Fixed in the next DEVTEST build :)

**Comment by Blood-Moon-Interactive** [comment]
Confirmed icon updated
