### ISSUE TITLE
GGMAX Bug - Arrow Trap not working properly on all levels in stand alone but works fine in test.

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5633]
In the video below I will demonstrate that while the arrow trap behavior seems to work just fine in the test mode, when I build a stand alone it acts inconsistently. On one level the sound plays, but the arrow does not appear to fire at all. On another level in the same game, three arrow traps fire their arrows and those arrows cause damage, but no sound is played. For a while the sound played fine and the issue was isolated to just level 3, but as time has gone on and multiple stand alones have been build the sound stopped working on level 4.

https://youtu.be/5IIoU2OPXoA

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive For this one, set the arrows on the floor to static so that will stop them using the older arrowtrap script,. and for the active one onlevel 3 set to physics= no and always active = yes. Once I have the missing files I emailed you I can try this myself with a new standalone :)

**Comment by Blood-Moon-Interactive** [comment]
I made the changes you recommended, rebuilt the stand alone and tried again. Unfortunately that did not solve the issue. I also took one of the floors out to test the theory that the arrow was falling to the ground, and you are correct.

![image](https://github.com/user-attachments/assets/fa994775-8600-49f8-aa5d-e8f27c0a084e)

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive I have emailed you a new standalone I made just using your level 3 as a basic test. Go through the email and feedback directly, hopefully we can resolve this little but very mysterious mystery!

**Comment by Blood-Moon-Interactive** [comment]
Issue has been resolved
