### ISSUE TITLE
GGMAX Bug - Multiple Textinzones

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#5634]
https://github.com/user-attachments/assets/e89049c9-97d7-4c15-869b-f92832bf76f4

The problem has returned i have updated the work shop files a gain i am using build 2024.06 18 see attached video

**Comment by Blood-Moon-Interactive** [comment]
Good video! Are you using EXP build or the stable (retail) build? Helps narrow down the issue.

**Comment by zeebon** [comment]
I’m using the workshop as far as i am aware i have the retail key in steam how do i know which one i am using I have build 2024.06.18 how do you get the retail version i thought steam would have updated to that

**Comment by mav3r1ck1981** [comment]
Out of interest, what made you decide to create a text zone, rather than using the one built into the "game elements" menu? I mean no disrespect i was just curious. Ive just checked the built in textinzone on retail and experimental and it works on both (for me) It might be worth trying that instead of creating your own? I can confirm however that using a triggerzone and changing the behavior to Necryms "Textinzone" does not work on either build. i cant even get a triggerzone linked to another object with the "textinzone" behavior to trigger the text on screen,

![image](https://github.com/user-attachments/assets/385848f1-6589-4ddc-b948-d707bea513b1)

**Comment by zeebon** [comment]
I used the trigger zone because the one in game elements doesn’t work either

**Comment by mav3r1ck1981** [comment]
thats fair enough!

**Comment by Blood-Moon-Interactive** [comment]
> I’m using the workshop as far as i am aware i have the retail key in steam how do i know which one i am using I have build 2024.06.18 how do you get the retail version i thought steam would have updated to that

Unless you intentionally switched to the exp build through the property window, you're probably in the retail build. What I've observed is there are things being changed in the exp build that, when pushed to retail, will fix these issues. I think we're just over due for an update.

**Comment by DBird-1994** [comment]
> > I’m using the workshop as far as i am aware i have the retail key in steam how do i know which one i am using I have build 2024.06.18 how do you get the retail version i thought steam would have updated to that
> 
> Unless you intentionally switched to the exp build through the property window, you're probably in the retail build. What I've observed is there are things being changed in the exp build that, when pushed to retail, will fix these issues. I think we're just over due for an update.

I don't think we're overdue for an update just yet since they switched to quarterly updates for retail build.  Last update was in June so the next update won't be until September I think.    I believe the update schedule is now March/June/Sept/Dec.

**Comment by zeebon** [comment]
What I can’t understand is why it worked once then it stopped working yet the original one still works very confusing can anyone help I don’t won’t to uninstall it again

**Comment by synchromesh62** [comment]
> What I can’t understand is why it worked once then it stopped working yet the original one still works very confusing can anyone help I don’t won’t to uninstall it again

I think there is a bug that only one per map will work at the moment ...
I tried a blank map and it seems only the first one placed works.. I would bet as a test if you removed the one around the npc the other will work.

**Comment by zeebon** [comment]
No that didn’t work tried both trigger zone and game element still no joy

**Comment by zeebon** [comment]
Made a new level added the text element it worked added another it didn’t work removed the original the second one worked just what synchromesh62 predicted I will make a video showing this in action
