### ISSUE TITLE
LOW POLY DLC PROBLEMS

### ISSUE THREAD

**Issue by XScornGames** [TheGameCreators/GameGuruRepo#5640]
the dlc low poly mechanic thing has a bug....
![image](https://github.com/user-attachments/assets/85f452e4-2a09-4d29-88d0-5caadef39a51)
![image](https://github.com/user-attachments/assets/fb80e8ba-8854-4722-8fa0-050de27a446b)

the selected one big chain red the holder is turned around
inside out 😄
sorry wrong one the small oen is damaged
not the big one

**Comment by Kasseyus** [comment]
This issue has now been fixed.
