### ISSUE TITLE
GGMax Enhancement Storyboard/HUD screens

### ISSUE THREAD

**Issue by mav3r1ck1981** [TheGameCreators/GameGuruRepo#5646]
Would it be possible to have a new button option within the RPG HUD screens on the storyboard editor to allow for ALL in-game HUD screens to be accessed from ONE central screen in-game?

As a player, it can dramatically impact the immersion when you have you have to stop and remember which key to press to bring up a certain HUD screen (inventory/crafting/trading/stats etc) Yes, there is a text prompt to remind the player, and this option is fine, if a little dated. 

Most games with an RPG elements now have a central screen, most often the inventory screen, with tabs either at the very top, or side of the screen with which the other screens can be cycled. 

![image](https://github.com/user-attachments/assets/39342e44-b521-4b13-a915-5a49981f6a81)

You can see in the screenshot above from the roguelike Witchfire, that whilst the inventory screen is currently focused, that there are tabs at the top linking to the other useful screens. These can either be clicked on to access, OR cycled using the Q and E keys.

What im suggesting is that "go to another screen" Action is allowed in HUD screens, not just the NONE HUD screens as we have at present. 

![image](https://github.com/user-attachments/assets/b7ce5072-eb2f-4835-ab38-41ab5d4d2aa1)

While this wouldn't allow for "cycling" of the various screens, it would allow the player to access all the additional HUD screens from as central place, adding QOL to the gameplay add adding a more professional level to the project. As a dev, you could setup multiple buttons wherever you wanted on the screens (granted you would have to set them up on each screen you wanted to include) and have everything effectively central.

At present, "go to another screen" function is not available on any in-game HUD screens (theres probably a reason for this) It might not be possible, but if its simple to do, it would add another level of QOL.

**Comment by GraPhiX-Guru** [comment]
I agree a Tabbed HUD screen would be very useful, keeps things organised and tidy

**Comment by SampeyFS** [comment]
Good

**Comment by Necrym59** [comment]
Add a button to your screen (tab buttions) and in action select the HUD screen you wish to go to
![huds](https://github.com/user-attachments/assets/bc5714a8-3337-425d-8c74-ba13cc6cf2eb)

**Comment by mav3r1ck1981** [comment]
this absolutely kicks ass! Thanks @Necrym59 Everything works perfectly and tidies up the entire RPG screens

**Comment by SampeyFS** [comment]
A thousand thanks @Necrym59
