### ISSUE TITLE
Added Function to Camp Fire

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5647]
First of all I wanted to thank Necrym59 for the script, I wanted to ask if you could add it to light the fire, does it require wood resources? A thousand thanks

**Comment by Necrym59** [comment]
That would take quite a bit of work to do so no, not at this time. Like cooking it cannot be done without having resource classes created, this may come later on.

**Comment by Necrym59** [comment]
Updated, can now use a named collectable resource (eg: wood) for fuel.
