### ISSUE TITLE
Swimming---jump in water,,,,,,sink right to bottom...HELP !--latest beta---June 28B

### ISSUE THREAD

**Issue by UNIRD12B** [TheGameCreators/GameGuruRepo#565]
when you jump in the water your character sinks right to the bottom...

**Comment by plemsoft** [comment]
@UNIRD12B Thanks for reporting this,

This has been fixed and are will be in the next update:

https://github.com/TheGameCreators/GameGuruRepo/commit/df03dc0e2562f1d57d1fab277a30500d59b02cc0

**Comment by UNIRD12B** [comment]
Thx Lee
