### ISSUE TITLE
Game characters are not working, or moving.

### ISSUE THREAD

**Issue by MarineGuru** [TheGameCreators/GameGuruRepo#5653]
Greetings, I briefly mentioned some of these problems on discord and was recommended to ask any questions here.
So, it seems anytime I go to create any decently detailed maps, the ai stops working without any reason. Can you help? 
I can send the map if needed, also here is an example. 
https://www.youtube.com/watch?v=pJamu8uOQiM&feature=youtu.be
Thank you for any help! I will release these projects once everything is running correctly!

**Comment by Kitakazi** [comment]
Your title says "GGMAX" but in the video its GG Classic?

**Comment by MarineGuru** [comment]
hello guys, thanks for correcting the label. Like I mentioned I can provide the maps if you wish

**Comment by MarineGuru** [comment]
anyone here?

**Comment by MarineGuru** [comment]
Will do, just a number of the maps do contain assets from thegamesstore, if these are not stock media? sorry not sure if thats what you mean. Here are the maps though!

 First one, an Omaha beach remake where soldiers wont move. 
[OMAHA BEACH - NORMANDY.zip](https://github.com/user-attachments/files/16734992/OMAHA.BEACH.-.NORMANDY.zip)

**Comment by MarineGuru** [comment]
[- NAM - 2  DEMO.zip](https://github.com/user-attachments/files/16734997/-.NAM.-.2.DEMO.zip)
a vietnam demo, same issue

**Comment by MarineGuru** [comment]
[MARS GURU DEMO.zip](https://github.com/user-attachments/files/16735002/MARS.GURU.DEMO.zip)

and a mars game in progress!

**Comment by MarineGuru** [comment]
[Classic - MarsGURU- Demo.zip](https://github.com/user-attachments/files/16845825/Classic.-.MarsGURU-.Demo.zip)
Updated

**Comment by MarineGuru** [comment]
[Classic - MarsGURU DEMO.zip](https://github.com/user-attachments/files/16845940/Classic.-.MarsGURU.DEMO.zip)
 Landscape demo showcase. No monsters, if you could add anything let me know

**Comment by MarineGuru** [comment]
[MarsGURU DEMO.zip](https://github.com/user-attachments/files/16846681/MarsGURU.DEMO.zip)
*Updated

**Comment by MarineGuru** [comment]
[Classic - MarsGURU ALPHA DEMO1.zip](https://github.com/user-attachments/files/16847251/Classic.-.MarsGURU.ALPHA.DEMO1.zip)

**Comment by LeeBamberTGC** [comment]
@MarineGuru Any chance you can zip up the non-stock assets and email them to me in confidence at lee@thegamecreators.com

**Comment by MarineGuru** [comment]
Yessir!

**Comment by MarineGuru** [comment]
[GG - MARS DEMO.zip](https://github.com/user-attachments/files/16847532/GG.-.MARS.DEMO.zip)
I believe this has the correct map also, may not have included the DAT file, is there a quick way to pull up every asset? I could send the list via compressed and compile them today

**Comment by MarineGuru** [comment]
Uploading assets now to google drive, 1 hour

**Comment by MarineGuru** [comment]
[Uploading MarsTerrainAlpha.zip…]()
 Assets should be uploaded in email link from google drive! If you need anymore let me know

**Comment by MarineGuru** [comment]
All set!! let me know if these work

https://drive.google.com/drive/folders/1P5JGmnUbXvcV6ZWAuN3oRnnZtzNl0-sL?usp=drive_link

**Comment by MarineGuru** [comment]
Map revised for now, added ammo and weapons and 1 spider by Dagored inside the first base, on my end he stands still curious if it runs/?
[MARSGURU -TESTDEMO.zip](https://github.com/user-attachments/files/16875004/MARSGURU.-TESTDEMO.zip)
 other issue all npcs act in similar ways.

**Comment by LeeBamberTGC** [comment]
@MarineGuru Ensure that your DEBUG VISUALS slider is set to zero or your characters will not perform AI. Also when I placed a regular stock character next to this character, it worked fine and ran around shooting at me. This non-stock character you are using has something wrong with it as he continually reloads his weapon, so you need to speak with the original author of this one:
![image](https://github.com/user-attachments/assets/00e3e5de-efc7-45b0-b7c6-f14e4276c920)

**Comment by MarineGuru** [comment]
Thank you!! Will do

**Comment by MarineGuru** [comment]
Thank you!!
