### ISSUE TITLE
GGMAX DEVTEST - Library Items Not Showing 

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5654]
As of this morning when you go to add media - behaviors, models, etc - Nothing shows in the Library Window
This happens for both Projects and Normal Games

This is what I see for all items:
![image](https://github.com/user-attachments/assets/7b77e38e-80a7-497e-b1e3-3e420d009ae3)

Was fine yesterday

PS @LeeBamberTGC - Lee I sent an email about this Please disregard it 👍

**Comment by OldFlak** [comment]
Hi @LeeBamberTGC,

I have found the issue with this.
- unless you have your media in the default writable area they will not show up in the library.

To test, I copied the same folder structure in my projects to Documents\GameGuruApps\ and they show up, if I remove them again, then the library is empty.

So MAX is only pointing to the default GameGuruApps folder, whereas each project should point to it' own folder system.

**Comment by LeeBamberTGC** [comment]
@OldFlak Turns out my optimization to speed up storyboard loading, optimized away the library list refresh that collected remote project media file info. Oops. Put back in with some proper messaging to explain the delay.

**Comment by OldFlak** [comment]
@LeeBamberTGC - Thanks Lee - will check it out asap 👍

**Comment by OldFlak** [comment]
This is sorted - thanks Lee :)
