### ISSUE TITLE
GGMAX DEVTEST - Can Not Access Projects and Standard Games Simultaneously

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5655]
Can not access normal games unless I point to it using:
![image](https://github.com/user-attachments/assets/feb13c9f-f069-44f2-a1e0-ff9564fdd144)

That gives me this in the HUB:
![image](https://github.com/user-attachments/assets/dc712d26-7033-47c2-a3e8-afdf790f1319)

If I untick the box like so:
![image](https://github.com/user-attachments/assets/fd61b50f-acf5-4b48-b239-0c476c0a4e30)

That gives me this in the HUB:
![image](https://github.com/user-attachments/assets/a644f751-d41e-49a2-a87a-9fb144ae7af7)

The GameGuruApps folder looks like this:
![image](https://github.com/user-attachments/assets/f81f2349-22d9-4529-8e11-6e937f2fbff7)

Remote Project location also incudes rouge files and appears like this:
![image](https://github.com/user-attachments/assets/d287394f-9dc8-436a-a920-0a662004d41c)

I wonder if that is all related to the media no longer showing up in the library.

PS @LeeBamberTGC - Lee, I sent an email about this - please disregard that

**Comment by LeeBamberTGC** [comment]
@OldFlak I have dropped you an email with the sequence I am using in my tests. It is not unusual to have two different project collections if your custom writable location is located elsewhere and has different projects in there. The default location of "Documents\GameGuruApps\GameGuruMAX\Files\projectbank" would always retain the original projects.

**Comment by OldFlak** [comment]
@LeeBamberTGC yes, replied to your email - if we need to change location manually, that is fine for me 👍 

Would be a little more straight forward if Settings was accessible from the HUB - but no problem as is.

Closing as I was really wondering if that was how it was expected to behave - so it is not an issue after all :)
