### ISSUE TITLE
GGMAX DEVTEST - Items Missing From Remote Projects

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5656]
I customize everything in my projects :)
Here be list of items that need to be specific to each Project.

Lens Flares
- mine are customized and would be for each different Project

StoryBoard - Custom Fonts
- I use custom fonts in the storyboard and would do so for each different project

Games Screen Cursor
- I use custom ones and would do so for each different project

Game Screens LUA files?
- in the past I have customized these also, but not for MAX (yet)
- others may want to as well

Screen BloodSplat and Hit Indicator
- I use custom images in databank folder and would do so for each different project
- probably everything in databank should be Project Specific

GrassBank
- I only use custom grass and would do so for each different project
- I have a grassbank folder in the project - but MAX does not use it
- MAX still uses the grass in default SteamLibrary

Skyboxes
- They get copied over to the project - but MAX does not use those ones 
- MAX still uses the ones in default SteamLibrary

Thanks for considering :)

PS @LeeBamberTGC - Lee, please disregard any emails regarding some of these findings - this is a more exhaustive list👍

**Comment by mav3r1ck1981** [comment]
couldn't agree more with all of these, everything in my project is custom to my best abilities, id like to add particles to your list if you don't mind me jumping on here,

**Comment by MonkeyFrogStudio** [comment]
Everything ... and I mean EVERYTHING used in a project needs to get copied over. Especially if what you use in your game projects are custom assets (sounds, particles, UI elements, models, grasses, trees, etc. ... everything without exception).

**Comment by OldFlak** [comment]
Agree - only runtime files need to be added when creating a standalone - everything else should be in the project 

MAX is also copying media to the Project that is not used at all in the game - so some fine tuning is needed there too :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Answered most of your emails, and remaining questions posted here so we can keep things in one place:

Lens Flares
LEE: Copied when remote project created

StoryBoard - Custom Fonts
LEE: Copied when remote project created

Games Screen Cursor
LEE: Copied when remote project created in NEXT BUILD

Game Screens LUA files?
LEE: Scripts and related logic not copied over for now, still fixes and stability in the core logic before we can confidently make a copy and then NEVER update it via updates.  A future feature perhaps

Screen BloodSplat and Hit Indicator
LEE: Copied when remote project created (databank)

GrassBank
LEE: Copied when remote project created

Skyboxes
LEE: Copied when remote project created

I will investigate GRASS and SKY not being used in the standalone.

**Comment by LeeBamberTGC** [comment]
P.S. Wait for next DEVTEST build to confirm all this :)

**Comment by OldFlak** [comment]
@LeeBamberTGC - thanks for the updates - awesome work as usual 👍

**Comment by OldFlak** [comment]
@LeeBamberTGC Hi Lee :)

Bit more info on the Skybox issue:

TEST-GAME
It does the correct one in test-game but **only if ** one of the same name exists in steamlibrary. I noticed this when working on a new skybox. 
I made some updates to the one in the project, and it does use that one.
But if you delete the one in steamlibrary it then uses default sky

I will test if it does the same in standalone again soon.

**Comment by LeeBamberTGC** [comment]
@OldFlak Interesting finding!  When you are ready, send me the standalone of the level that fails to show the right skybox and also the custom skybox that I presume you placed in your remote project folder and selected for the level. From this I can unravel the mystery :)

**Comment by OldFlak** [comment]
@LeeBamberTGC Hi Lee some feedback for this thread

Scratch these of the list 👍 

Lens Flares
LEE: Copied when remote project created
Reply:
- Sorted 👍 Also works in standalone as expected

Games Screen Cursor
LEE: Copied when remote project created in NEXT BUILD
Reply:
- Sorted 👍 Also works in standalone as expected

Game Screens LUA files?
LEE: Scripts and related logic not copied over for now, still fixes and stability in the core logic before we can confidently make a copy and then NEVER update it via updates. A future feature perhaps
Reply:
- Makes sense 👍 
- I will create a feature thread for this for a future addition

Screen BloodSplat and Hit Indicator
LEE: Copied when remote project created (databank)
Reply:
- Sorted 👍 Also works in standalone as expected

-------------------

**Comment by OldFlak** [comment]
Still Issues with these:

StoryBoard - Custom Fonts
LEE: Copied when remote project created
Reply:
- the custom font is in my project doesn't show in list (storyboard)
- has to be in steamlibrary for MAX to find it
- uses the font in standalone but it is not in the standalone folder system

GrassBank
LEE: Copied when remote project created
Reply:
- Still issues with this (similar to skybox issue)
Test-Game
- default grass from steamlibrary is used instead of grass in project
Standalone 
- uses correct grass

Skyboxes
LEE: Copied when remote project created
Reply
Test-Game
Uses correct skybox, but only if skybox with same name is in steamlibrary
- if not max will use default sky
Standalone
- uses correct skybox

**Comment by OldFlak** [comment]
@LeeBamberTGC 
I will email a link to a standalone

**Comment by LeeBamberTGC** [comment]
@OldFlak I could not find your latest standalone in my inbox, can you do me a favor and resend, thanks!

**Comment by Necrym59** [comment]
Add to this list the "\Files\editors\lut" folder to be copied over by default on new projects as theey have the capability to be selected and changed within a game via behaviors.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Already in the latest DEVTEST when a new remote project is created:
![image](https://github.com/user-attachments/assets/e4f9fca2-e731-4ac5-bfd4-ba1765ee13bf)

**Comment by OldFlak** [comment]
@LeeBamberTGC - hi Lee :)
I have sent you a standalone, and here be couple vids that show what is happening in editor, and in standalone

Editor
https://youtu.be/DhahnQZ7YL8

Standalone
https://youtu.be/VvYWegfUPjs

Note these things:
In editor:
- using correct terrain texture
- using correct skybox (note only does so if there is one of same name in default steam location)
- 
- not using correct grass
- not using correct lens flare

In Standalone:
- using correct grass
- using correct skybox
- using correct lens flare
-
- not using correct terrain

I didn't show it in the test vids, but I get similar but mixed results with blood decals
- in editor it uses a mix of both those in project and the stock ones
- standalone uses only those in the project

**Comment by OldFlak** [comment]
Another potential issues I am seeing:
Identical file structure in default documents area
- what happens if we do a clean install of windows? will MAX put them back, or do we have to do so?

Random skybox duplicate
I use skyboxes with almost all of my levels
- but only one is duplicated in the default documents area. I feel like nothing should be there?

Also seeing a ton of stuff not being used in the project
- body parts, weapons, etc
- the main idea of projects is only what we actually add should be there :)

On the plus side standalone's now seem to have everything there (although I have not tested particles)

**Comment by LeeBamberTGC** [comment]
@OldFlak Thanks for your standalone, videos and help. In the next DEVTEST you will find the issues relating to the standalone export (terrain textures) and the editor issues (lensflare and grass) fixed for remote projects:
![image](https://github.com/user-attachments/assets/5d920b0a-1e2b-4c81-964f-7d169f69f818)

To your second point, with the latest DEVTEST and doing a fresh writables area (what you call the default documents area). You can do a fresh one by renaming the current one as a backup and allowing MAX to create a new writables folder and default files),

I then dropped in the REMO1 project folder in as the only manual addition so it was clean. Loaded the REMO1 project and then looked if any rogue files existed in the writables. Saw no extra skyboxes, and no body parts or weapons in either writables or the remote project area:

Fresh writables:
![image](https://github.com/user-attachments/assets/ee203965-565f-4be4-827f-677b06f96a22)

Basic default files and folders:
![image](https://github.com/user-attachments/assets/9596e276-c538-4d76-9f2a-648cc99b14f6)

My REMO1 project folder:
![image](https://github.com/user-attachments/assets/838910d9-d659-41c0-aaea-d472f91304de)

No body parts:
![image](https://github.com/user-attachments/assets/86904478-0e18-4cd7-8755-a2516076354f)

You will get files such as you describe if at ANY time you added such weapons, characters, etc to the project as currently (and perhaps always) there is no automatic system that DELETES files when it thinks they are not being used, such a system would be a little too destructive.

Next DEVTEST build up soon, just checking some other standalone related issues.

**Comment by OldFlak** [comment]
Hi @LeeBamberTGC 
The latest update has sorted some of theses issues.
Notably terrain and grass are working as expected in both editor and test-game - thanks!

Since the thread is getting super long I will close it and add individual thread for single items as required

Thanks for awesome dev tool
