### ISSUE TITLE
GGMAX DEVTEST BUG - Particle speed goes back to default after saving and closing level

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#5657]
So what's been happening is I've been placing down several particles for a fog affect and turning the animation speed down low. After placing more than five they seem to glitch out and go back to their default speed. You can click on them and then they will glitch back to the speed they're supposed to be at but then they go right back. It seems to happen a bit more when you duplicate the same particle and use it over and over again. For testing, it doesn't happen right away. It usually happens after you save your level and then come back to it and then they will start to glitch out from there.

**Comment by mike123yy** [comment]
Update: I switch back to the stable build since I was working with the dev test to fix other issues and it's not a problem there so I suppose this would be a new problem with the dev test version.

**Comment by mike123yy** [comment]
This is still broken and the current dev test. Particles don't obey the user set speed or transparency. As soon as you go into the particle properties and move the slider slightly they glitch back to their set speed but after saving and closing the project and then coming back they go right back to full speed. It's easy to reproduce, place down a couple particles and set their speed to very low then save the level. After that close game guru Max and then re-open your level and they will be moving back to default speed.

**Comment by mike123yy** [comment]
Now is broken on all builds

**Comment by Kasseyus** [comment]
@LeeBamberTGC 

Ticket Ref: https://github.com/TheGameCreators/GameGuruRepo/issues/5742

Appears to be a related issue (Reproduced in other thread)

**Comment by mike123yy** [comment]
I made this a couple months back but I did notice the new thread. I suppose I will keep an eye on that one instead.
