### ISSUE TITLE
GGMAX BUG - Zombie Grab Visual Glitch

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#5659]
When the zombie grabs the player to bite him/her, the screen flickers. 

Tested with Slother - Roamer Zombie

**Comment by Necrym59** [comment]
Confirmed, i have this too now

**Comment by LeeBamberTGC** [comment]
@Teabone3 Fxied for sure in next DEVTEST build ensuring camera no longer flickers when in brain feed mode!
