### ISSUE TITLE
Standalone - Titlesbank\Watermark

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#566]
Hi all
Since work is being done on adding dialogs used when build stand-alone:

**1) Tiltebank Folder:**
It would be good to be able to select the folder you want to use when building the stand-alone, or perhaps select a style_mygame.txt that points to the folder you want to use.

**2) Watermark Image:**
Wouldn't it make sense to include the watermark image in the respective folders in the titlesbank\mygame\resfolders. Rather than using the default GG ones in languagebank\english\artwork\watermark\watermark_images.

----

This would negate the need to overwrite the default watermark images used in test-game, and also negate the need for style.txt, as well as the need to edit\overwrite it every time GameGuru gets an update.

Reliquia....

**Comment by synchromesh62** [comment]
1 .. You can already do that in the style.txt
![style](https://user-images.githubusercontent.com/35708217/60384584-694dc180-9a77-11e9-8cb9-a7b946265d21.png)

2.. Agreed but lose the watermark " put your logo here " screens altogether. they are just another 12 screens we have to annoyingly edit so there pretty pointless really :(

**Comment by michaeloldman** [comment]
@synchromesh62 - Yes indeed :)
But if we could use the Build dialog to point to the folder to use
> This would ..... negate the need for style.txt, as well as the need to edit\overwrite it every time GameGuru gets an update.

Since work is being done on that part of the build stand-alone, it would be a good time to add it. Unless of course it is way complicated to do :)

Reliquia....

**Comment by LeeBamberTGC** [comment]
Not complicated, just premature. Our mission for 2019 is to get rid of all the bugs, music to the ears of pretty much every GameGuru user :) I modified the Save Standalone as I considered it a bug you could not cancel a particularly long save standalone process (impossible without terminating via task manager). Providing there is 'some way' to change the titles of your standalone, I would not consider it a bug at this stage (at least, compared to the others out there).

**Comment by michaeloldman** [comment]
Thanks for the input Lee :)

Yes, agreed it is not a bug, just an enhancement. Just puting it out there :)

If and when this gets any attention, please take into account point 2, personally I think that needs to be changed. It makes sense (at least to me) that ALL the images should be getting sourced from the same place.

Again thanks for chiming in :)

Reliquia....

**Comment by synchromesh62** [comment]
No I never saw it as a bug but did agree about losing those 12 watermark screens.
Always worth a try :)
