### ISSUE TITLE
GGMax Armour mechanics

### ISSUE THREAD

**Issue by tenser-spencer** [TheGameCreators/GameGuruRepo#5660]
I mentioned this on Steam  and synchromesh suggest I post it here. 

An observation regarding armour? It is an Important game mechanic.

Armour is a great resource. You wear it and it protects you. So if you are wearing armour, it protects your health and the amount of damage sustained to your health is reduced. And that is currently how it is set up in GGMax.

Except...
the armour never deteriorates. Whether you are shot a dozen times by a gun or step on a landmine, GGmax armour just protects and provides an invulnerable shield against damage. Invincibility is NOT fun gameplay. We need the armour to slowly deteriorate as it sustains damage. Eventually it will hit zero and have NO effect on protecting health. Just as it would in the real world. And that armor value should not fall below zero either.

Then the player has a reason to go look for more armour. And more health.

Is it possible to have this addressed.  And while here, a edit field to set what MAX Armour can be.  200 can be default.

**Comment by Necrym59** [comment]
This is being looked at at present
