### ISSUE TITLE
GGMAX Bug - Workshop is not downloading for Max

### ISSUE THREAD

**Issue by ShadowMasterOfGames** [TheGameCreators/GameGuruRepo#5662]
Workshop is not downloading anything for max, and yes I followed the steps as always. btw this happen all five times to try and get the behaviors to update.

here is screenshots
![Screenshot 2024-08-08 180616](https://github.com/user-attachments/assets/fd898b52-ccd5-43ef-a443-c343678151b0)
![Screenshot 2024-08-08 181118](https://github.com/user-attachments/assets/6c1416d3-b602-44c9-ae49-8206dc01ac81)
![Screenshot 2024-08-08 183541](https://github.com/user-attachments/assets/d57efc45-a850-42e8-b715-5a2378e1d253)

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames Can you attach a screenshot of the HUB workshop area AFTER you exited MAX and relaunched from Steam client, it should not then display the "RELAUNCH..." text as you can see in shots 2 and 3.

**Comment by synchromesh62** [comment]
@ShadowMasterOfGames 
Hi can you try exactly as this video shows .. You must follow the prompts **Exactly** and you should see steam apply the updates at the end .. Just updated the workshop myself and this works for me :)

https://github.com/user-attachments/assets/28c21e51-101f-4393-9e6b-0bc1d2de9e69

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC Here is a 5 mintues video and screenshot for you. Also, yes I am subscribed to all and even resubscribed to them as me and Necrym59 try to get workshop to work and @synchromesh62 watch the 5 minutes video

![Screenshot 2024-08-08 222052](https://github.com/user-attachments/assets/9a4b617b-99e8-4907-8d11-f00a07122637)

https://www.dropbox.com/scl/fi/804i4jq3i2yiu0zq1hqo1/Recording-2024-08-08-222718.mp4?rlkey=1q3vbxhseey4ivoacr9sfnsdm&st=e1tednnj&dl=0

**Comment by ShadowMasterOfGames** [comment]
I am get off my laptop, so will send more stuff as needed tomorrow when I get back on

**Comment by SampeyFS** [comment]
I've been saying this for a long time I was told no :-)

**Comment by synchromesh62** [comment]
@ShadowMasterOfGames 
Ok no worries just trying to help .. 
Many have followed the video on Discord and found it worked for them as they were not following the prompts exactly.
Also launching from Steam for some made a difference rather than a Desktop shortcut.

**Comment by ShadowMasterOfGames** [comment]
@synchromesh62 I have done both of those techniques. I truly thank you for trying to help, my friend. I do help that Lee can find the cause for this issues with workshop

**Comment by LeeBamberTGC** [comment]
@ShadowMasterOfGames In your video you had it working at 2:15 when you saw all the latest workshop items and the latest showing as 08/08/24:
![image](https://github.com/user-attachments/assets/05f9d132-6bd2-4dda-9dea-4715fb0f37d9)

You then continued clicking updates, exiting via Steam client, etc and basically messed the process from then on. As a tip, never click the STOP button in Steam Client, it does not allow MAx to do processes during the exit sequence.

**Comment by SampeyFS** [comment]
Update Dev Testing?

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC I will let know as soon as I am on my laptop (probably Sunday (tomorrow) if it is working on exp
