### ISSUE TITLE
Error Lua After the last buld (DevTesting)

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5663]
![image](https://github.com/user-attachments/assets/f8001554-a6c2-4e13-b543-f24e3dd9d194)

Loading save is written this lua error 

@LeeBamberTGC

**Comment by SampeyFS** [comment]
https://youtu.be/kq5BPYoZWMo

**Comment by SampeyFS** [comment]
![image](https://github.com/user-attachments/assets/597aafd2-9f54-4cbf-a24e-09326a6472cc)


error 60 line

**Comment by Necrym59** [comment]
What version are you running

**Comment by SampeyFS** [comment]
Yes

**Comment by SampeyFS** [comment]
Correct the error please @Necrym59

**Comment by LeeBamberTGC** [comment]
@SampeyFS Lots of improvements in the new DEVTEST build, that should improve the game save reload and also resolve the error you are seeing in your standalone executable (hopefully). If you still get the error, please do send me a new standalone of your game using the new DEVTEST build.

**Comment by SampeyFS** [comment]
The error is solved but lua are not loaded... campfire by Necrym other lua scripts are not loaded cuttable trees disappeared when loading save a disaster in loading lua  @LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@SampeyFS Can you make a small standalone including a single level showing the CAMPFIRE and the TREE, along with the latest of the scripts you are using? Both these scripts are not stock scripts so I will need the latest versions.

**Comment by Necrym59** [comment]
CAMPFIRE V10 attached lee
[campfire_v10.zip](https://github.com/user-attachments/files/16653221/campfire_v10.zip)

TREE is not one of mine so i have no idea i think it was one of old classics choppable tree scripts.

**Comment by SampeyFS** [comment]
Yes classic helped me AmenMoses to convert it indeed I thank him very much for the help it works well the script

**Comment by Necrym59** [comment]
@SampeyFS 
Yes but Lee has asked you to supply it

**Comment by SampeyFS** [comment]
sisi passed it to him by email

**Comment by SampeyFS** [comment]
![image](https://github.com/user-attachments/assets/6827efc5-bf79-478c-bbbe-56bde4f2022a)

**Comment by SampeyFS** [comment]
which script lee of plants?

**Comment by LeeBamberTGC** [comment]
@SampeyFS The one you referenced when you replied to Steve saying "sisi passed it to him by email"

**Comment by SampeyFS** [comment]
ok

**Comment by SampeyFS** [comment]
[Script tress.zip](https://github.com/user-attachments/files/16749773/Script.tress.zip)
Script send

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks, emailed received with scripts. See my email for the next step to reproduce this.

**Comment by Kasseyus** [comment]
@SampeyFS 

I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by SampeyFS** [comment]
Problem seems solved
