### ISSUE TITLE
GGMAX Bug - Rain and Snow Indoors

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#5665]
Rain and Snow doesn't appear to stop when going in doors.

**Comment by SampeyFS** [comment]
Yes, I noticed it today too

**Comment by plemsoft** [comment]
@LeeBamberTGC Fixed here: https://github.com/TheGameCreators/GameGuruMAX/pull/35

**Comment by LeeBamberTGC** [comment]
Fixed for next DEVTEST build.
