### ISSUE TITLE
model importer. 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5668]
exported this from Unreal imported into max, textures all gone and it doen't import correctly. 

![image](https://github.com/user-attachments/assets/ec13ab60-e2c8-4a83-87d1-453117537ab9)

just imported it into blender and. yeah all good.

![image](https://github.com/user-attachments/assets/2c27c473-fb78-4b4e-aaaa-0c1ad1a2b37f)

**Comment by casigus** [comment]
![image](https://github.com/user-attachments/assets/73829ca6-ef76-4a7d-b7ea-47ca71bb2e2b)

**Comment by mav3r1ck198-1** [comment]
Max doesn't recognise the parenting associations. That not Max's fault tbh as most modelling softwares have their own way of doing things. 

What was your workflow? Did your export from unreal as .fbx then import into something like.blender? Then export out into max? Or did you use the exported fbx from unreal and directly import them into max?  Often, the textures will have naming conventions setup to be recognised in unreal and so max doesn't always recognise them. 

If you've edited it in blender and renamed the textures for the pbr workflow that max uses, then yeah this is a possible bug. However if you've imported directly from unreal  it's.more to do with the files being setup for unreal than for max.

If you're planning to have the car as a static prop,  you can join  all the parts together in blender and export out. If its animated, I'd suggest joining together everything but the wheels, animating them and baking the animation to the model prior to exporting.

Of.course everything I've just said could be simply.wrong and if so I apologise but hit me up if I can help at all :)

Mav

**Comment by casigus** [comment]
yah ill open it in blender and check the parenting of the object, join and then export and see how it goes from there!

**Comment by ShadowMasterOfGames** [comment]
> yah ill open it in blender and check the parenting of the object, join and then export and see how it goes from there!

you can also export as GLB or GLTF straight from unreal, here is a link to [GameFromScratch](https://gamefromscratch.com/exporting-from-unreal-engine-to-godot-unity-or-blender/) page that he explains exactly how to get every thing out of unreal and into other game engine.
