### ISSUE TITLE
Object Library isn't showing my last folder in the list. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5670]
The Object Library doesn't show the last folder in my list. Well it shows the very very top pixels of the name its almost impossible to see.  But yea I cannot scroll down any further to select it. The last folder should be Wolf. I know I have seen other users complain about this on discord too. Pretty sure its been like this since Max first came out. 

If I type the name of the entities from that folder they show up its just impossible to actually select the folder to look through. 

![image](https://github.com/user-attachments/assets/268e1bce-70ea-4760-a2c3-acded268ed0e)
![image](https://github.com/user-attachments/assets/b6675c91-8f9e-42aa-a57e-31da8ff81707)

**Comment by DBird-1994** [comment]
@Kitakazi  Already reported here #5474 and recently updated as low priority
