### ISSUE TITLE
GGMAX  Bug - Smart objects/grouping bug

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5671]
grouped some objects together so I could copy them over to another level,  anddd nope, doesn't work. all that this "feature" does is drop some weapons THAT i didn't even put in the game, and objects that also didn't add to the group, and even then it causes this weird effect where the objects just fly at you or around the map again and again, 

![image](https://github.com/user-attachments/assets/5b6dd0be-71a1-414b-8898-4cf345053db7)

I tried copying and pasting the sections I wanted, copied on that level, went to paste them in the other level and max just randomly copied parts of the level i was working on.

**Comment by casigus** [comment]
and this is what it actually dropped in....weeapons and that odd thing that also wasn't in the group when creating it.
![image](https://github.com/user-attachments/assets/a5f06302-ce6f-4982-9bca-3615033044f9)

**Comment by Necrym59** [comment]
They look like the ones you have selected in the editor?
can you give more specific information and image of a specific group of objects then save the group and load that group on a blank level and see what happens with an image. Plus supply the group file.

**Comment by casigus** [comment]
Sure.  I'll  get more info and screen shots.  I'll get a recording done too.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by casigus** [comment]
last time checked yep, still an issue.

**Comment by Kasseyus** [comment]
@casigus I've tried to re-create this issue, but the smart objects seem to be working for me.  Can you please provide a short video showcasing what steps you are talking leading up to this issue, and this may help me to re-create it.

https://github.com/user-attachments/assets/518d4d13-96e5-4395-9fb2-7190feb95261
