### ISSUE TITLE
GGCLASSIC Bug - 2 problems with bullet impact decals

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#5672]
My today's issue is about bullet impact decals (dust, sparks, splinters etc). 

1. First problem - bullet impact decals don't show up if you're more than few meters away from the target. Well known issue among all users, but somehow never resolved.  In my opinion the bullet impacts should appear on distance that is 3X longer than currently programmed.
Same with blood when shooting enemies, and enemy muzzleflash decal when they shoot me :)  

2. Second problem - bullet impact decals always break after few test games. Instead of specific decals for different materials (stone, wood, metal etc) GGC will show only the simplest dustpuff (the one corresponding with materialindex = 0). That's a very annoying problem, bc in any fps game feedback from shooting things is super important :) 

If you're reading this - Thank You in advance! 
Cheers :)

**Comment by LeeBamberTGC** [comment]
@Ghost-l0l Decal appearance range extended from 800 units to 3000, I think modern computers can handle a few more decals :)  As to the second point, much harder to reproduce that one as the decals always reflect the correct material in my tests.  Got a little bored after spraying a few hundred bullets into this crate:
![image](https://github.com/user-attachments/assets/10f3c859-6200-4036-aff2-7c0364a0dd1c)
Perhaps there is a reliable way to reproduce with stock assets?

**Comment by Kasseyus** [comment]
@Ghost-l0l 

It's best  to do one ticket per issue to make troubleshooting and  resolution of bugs more efficient, as  multiple issues per ticket could risk some 'falling through the cracks'.

As the main  point of this ticket  has been resolved, I will mark is as completed, but if  the second issue persists, please can you raise a new ticket  and I will  be able to investigate.   If possible, a video showing the problem will also be useful.
