### ISSUE TITLE
victorian booster pack...

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5673]
hello.  when it comes to purchasing packs on the store, I think most people will expect those packs to be optimized for game guru max, however looking upon this.

![image](https://github.com/user-attachments/assets/85472774-feda-410b-a679-b1cd0e1cbdcf)

this wall is set as a polygon for a rather bumpy wall,  when it should be a box!

nit picky yes, but when you add a row of walls, and notice a hiccup in FPS, and then click on the wall that should be a box to see that for some reason its a polygon model, and then realise you need to delete all the walls, change the collision and re-add them the nit pick becomes a job ya didn't need to do.

its a fantastic Pack for sure! but stuff like this needs to be sorted!

k thanks.
BYEE

**Comment by Ghost-l0l** [comment]
that's a recurring theme in DLC packs, it was like that in GG Classic too :D 
Almost like a tradition at this point; 
 It can also be seen as a barrier separating real GameDevs from simple Drag-n-Droppers ;p
