### ISSUE TITLE
massive fps slow down for no reason. 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5675]
fps dropping super low, moments after placing ANY thing in the scene, camera becomes awrful and literally makes me feel sick. memory ususage is 33 gig and still clmbing for unknown reasons,. this map is very very empty, as I had to restart the build because the previous map whcih ran amazing suddenly runs like a piece of actual human poop. 

![image](https://github.com/user-attachments/assets/10818fa0-4f47-4bb7-9ba6-28c3b425f93a)

**Comment by SampeyFS** [comment]
Yes, a drop ihttps://github.com/TheGameCreators/GameGuruRepo/issues/5650n FPS has already been reported, but I can also confirm that

**Comment by SampeyFS** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/5650

**Comment by Necrym59** [comment]
More pertinent information is required to diagnose what the problem maybe.

**Comment by tenser-spencer** [comment]
What is the polycount on that "BuildingNice" ?  It looks highpoly.  And if it is highpoly  that would be the reason for the slow down.
