### ISSUE TITLE
GGMAX DEVTEST Bug - Standalone issue from today's build 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5679]
![Desktop Screenshot 2024 08 13 - 22 16 20 40](https://github.com/user-attachments/assets/86f68329-3e95-412e-9557-258f7fe516e0)
![Desktop Screenshot 2024 08 13 - 22 16 20 40](https://github.com/user-attachments/assets/cee764e3-5052-4d4b-9c63-0e779677409f)

**Comment by SampeyFS** [comment]
![Screenshot 2024-08-13 224622](https://github.com/user-attachments/assets/592bf8f9-7cdf-4f29-923e-c5d861db8a38)


((  Trees disappeared in standalone extraction ))

**Comment by LeeBamberTGC** [comment]
@SampeyFS Can you send me a standalone of a small level with the TREE and the original script from the author, then I can reproduce the issue which I assume to be that the trees disappear when you load a saved game.

**Comment by SampeyFS** [comment]
ok the problem is standalone which does not extract the plants

**Comment by LeeBamberTGC** [comment]
@SampeyFS I would need standalone of a small level with the TREE and the original TREE script to reproduce.

**Comment by SampeyFS** [comment]
yes I sent emails with everything :-)

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks!

**Comment by LeeBamberTGC** [comment]
@SampeyFS Is this issue now fixed for you in the latest DEVTEST branch?

**Comment by SampeyFS** [comment]
I have to try unfortunately I don't have a computer and it's being serviced due to a fault under warranty
