### ISSUE TITLE
GGMAX Possible Bug - Weapon Pool and Ammo allocation

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#5684]
I have a behavior that issues a gun when entering a vehicle or a building for example (sample below, which issues the AK to the player):

```
vehicle[e].weapon_name  = "enhanced\ak"
------------------------------------------------------------
if vehicle[e].weapon_name > "" then
     AddPlayerWeapon(vehicle[e].weapon_name)
     ActivateIfUsed(vehicle[e].weapon_name)
     ChangePlayerWeapon(vehicle[e].weapon_name)
     WeaponID = GetPlayerWeaponID()
     for index = 1, 10 do
         if WeaponID == GetWeaponID(vehicle[e].weapon_name) then
              GetWeaponSlot(index)
              local poolindex = GetWeaponPoolAmmoIndex(index)
              local amqty = GetWeaponPoolAmmo(poolindex)
              SetWeaponPoolAmmo(poolindex,amqty + 500)
              --SetWeaponAmmo(index,500)
         end
     end
end
```

It adds the correct gun to the player, it finds the correct gun ID, it refuses to find the poolindex to update the ammo and even using the
"SetWeaponAmmo" (remmed out above) command wont attribute ammo, im at a loss as to what im missing or if there is a bug??
It gives the gun without the default guns ammo ammo or added ammo.  (The gun is on the level)

**Comment by LeeBamberTGC** [comment]
@Necrym59 It was indeed a bug. Fixed for the next DEVTEST build if you use this script code:

-- LUA Script - precede every function and global member with lowercase name of script + '_main'

g_bird = {}

function bird_init(e)
	g_bird[e] = {}
	g_bird[e].once = 1
end

function bird_main(e)
	if g_Entity[e]['plrinzone'] == 1 then 
		if g_bird[e].once == 1 then
			PlaySound(e,0)
			g_bird[e].once = 0
			
			--check name of weapon as a debug
			--local WeaponID = GetPlayerWeaponID() 
			--local the_weapon = GetWeaponName(WeaponID)
			
			-- assign a weapon to be summoned and uses default reload ammo
			local the_weapon = "enhanced\\ar"
			ChangePlayerWeapon(the_weapon)
			
			-- or set the bullets and ammo pool clip manually
			local WeaponID = GetPlayerWeaponID() 
			for index = 1, 10 do
				if WeaponID == GetWeaponID(the_weapon) then
					local poolindex = GetWeaponPoolAmmoIndex(index)
					local amqty = GetWeaponPoolAmmo(poolindex)
					SetWeaponAmmo(index,123)
					SetWeaponPoolAmmo(poolindex,amqty + 500)
				end
			end
			
		end
		
	end
end
