### ISSUE TITLE
GGMAX Bug - Possible Collision problem in Standalone

### ISSUE THREAD

**Issue by antoniox116** [TheGameCreators/GameGuruRepo#5688]
hi i hope you can solve this problem.
when i am in the level editor the collisions with the walls work fine.
when i export the game, i try it and i go through the walls.
this is a frustrating thing, and as if max does not load the collisions i have done several attempts and also research.
i tried static
hull decomp
collission mesh
etc...
nothing to do exporting the game and trying it through the walls as if i were a ghost.
help thanks a lot!
![Desktop Screenshot 2024 08 23 - 17 17 36 10](https://github.com/user-attachments/assets/ddfdc7b4-664b-4b4f-a09e-73d3187ca3ee)

**Comment by casigus** [comment]
yeah I had this stupid issue from day one with max, and literally just had it again where the collisions just dont work for what ever reason.

its one thing after the other with this software really is. I doubt they'll fix it for you, ive been reporting this issue for years.

**Comment by Necrym59** [comment]
Please supply the version of Max you are using and the details on the spefcific model(s) giving the issue
even a sample of the issue if possible.

**Comment by antoniox116** [comment]
good morning, thanks for answering me.
so the entity is an ebe structures imported from game guru has always worked well for the past.
the version of Max I am not participating in any beta not even: previousdefault-the last good pubblic build.
in any case I also tried this but it is the exact same thing. I also tried the developer mode but nothing to do. I also tried to create a new project but it is the same thing. too bad because I would have liked to continue with this project.
for the rest I recorded 2 videos both in the level editor and in the standalone. but it does not let me upload the videos they are too big.
thanks for the support.
I forgot that the houses in the build collection have been playing the same trick on me for a while, they even become transparent.
thanks for understanding and for the support.

**Comment by antoniox116** [comment]
> Indica la versione di Max che stai utilizzando ei dettagli sui modelli specifici, allegando anche un campione del problema, se possibile.

good morning, thanks for answering me.
so the entity is an ebe structures imported from game guru has always worked well for the past.
the version of Max I am not participating in any beta not even: previousdefault-the last good pubblic build.
in any case I also tried this but it is the exact same thing. I also tried the developer mode but nothing to do. I also tried to create a new project but it is the same thing. too bad because I would have liked to continue with this project.
for the rest I recorded 2 videos both in the level editor and in the standalone. but it does not let me upload the videos they are too big.
thanks for the support.
I forgot that the houses in the build collection have been playing the same trick on me for a while, they even become transparent.
thanks for understanding and for the support.

**Comment by Kitakazi** [comment]
So you made the EBE model in classic? Did you actually import the .dbo with the Max importer or did you just drag the original .dbo and FPE file into Max? If so you should try importing the .dbo with Max's importer.

**Comment by Kitakazi** [comment]
It has been a while since I imported EBE structures into Max, maybe it is not longer possible to do so. However you should make sure your settings in your .FPE file of the entity has these same settings. 

defaultstatic = 1
collisionmode = 1
forcesimpleobstacle = 3
forceobstaclepolysize = 4.50
materialindex = 2
;EBE Builder Extras
isebe         = 0

This the settings for my EBE structures that were imported from classic and they work fine in Max. If this doesn't work maybe something else is going on.

**Comment by Kasseyus** [comment]
> for the rest I recorded 2 videos both in the level editor and in the standalone. but it does not let me upload the videos they are too big.

@antoniox116 Can you please try uploading the videos to YouTube and sharing the links here, as seeing the issue in action may help identify the issue.

**Comment by Kasseyus** [comment]
@antoniox116 

I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by antoniox116** [comment]
Hi, I'll try again today and let you know if anything has changed. thanks
for your interest

Il sab 12 ott 2024, 11:20 Kasseyus ***@***.***> ha scritto:

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
