### ISSUE TITLE
GGMAX Bug - Possible Collision Issue

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5690]
import a model.
half the collisons are missing.
you fall through the model, 
months of work once again wasted because of this piss take. I'm sick of this now. its one thing after the other.
fix the god dam program or stop selling it. 
![image](https://github.com/user-attachments/assets/c5f15192-dbb3-4316-86d4-ab86678a9ae0)
ggmax should still be in beta, this isn't acceptable for a full release title, it barely functions. 
if this continues, I'm going to contact steam and explain all the stresses and strains and issues because this has gone on too long now, you do these "we've fixed 1000s of bugs thing, and yet I'm still face with the same crap over and over and over again as the same bugs and problems just keep on coming back.

**Comment by casigus** [comment]
as for the screen shot before some one asks, max doesn't register the wall as existesting nor does it register the railings as existing. IN the engine, the editor clearly shows that there is a collision there as it lets me attach things, soon as max fires up BOOM NOPE naddda. This has been an issue since I started using max.

**Comment by Necrym59** [comment]
Can you try and give more information in your posts. What version are you using. Plus why has this not cropped up before. The importer is a third party importing library. Try giving details of the model, where its from how it was exported to what format etc. Information like that helps to diagnose a problem.  Even supplying the offending model would help. Making idle threats isnt very helpful and doesnt get things solved i might add.

**Comment by Kasseyus** [comment]
@casigus Hello casigus.  Issus like this are usually due to import settings or a misconfiguration.  Are you still experiencing a collision issue with your model(s)?

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
