### ISSUE TITLE
GGMAX Bug - Gun Smoke Rendered as Black Square Due (transparency Issue?)

### ISSUE THREAD

**Issue by korodai** [TheGameCreators/GameGuruRepo#5697]
Occasionally smoke from fired weapons appears as a black square. Restarting MAX fixes it. 

CPU Brand: Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
Speed: 3600 MHz
Cores: 8 logical processors, 8 physical processors

OS: Windows 10 (64 bit)

GPU: NVIDIA GeForce RTX 3070
Driver Version: 32.0.15.6070 (Date: 7/10/2024)
Primary Display Resolution: 1920 x 1080
VRAM: 8191 MB

RAM: 32 GB (32687 MB)

Total Available Space: 1,906,244 MB (~1.9 TB)

![20240819131256_1](https://github.com/user-attachments/assets/7da4a2dc-bb46-4b8b-8710-8961c0cc9323)
![20240819130853_1](https://github.com/user-attachments/assets/5cff84f9-baf9-4e87-80d9-1ddb17dcf1dd)

**Comment by mav3r1ck198-1** [comment]
This used to happen when the gunspec file couldn't reference the correct decal, either it was missing, spelled incorrectly, corrupted or in the wrong format. You could perhaps try deleting the smoke image for this particular gun and then verifying files to see if it returns the correct spec. Obviously back up your.folders first so as to not lose anything youve added

**Comment by korodai** [comment]
![20240918220716_2](https://github.com/user-attachments/assets/d9159655-76d5-41d6-b5eb-1051fc404d4a)
I verified all files but didn't delete anything and now I see textured decals. After restarting MAX, the decals look like smoke again. This is the patrol rifle.

**Comment by korodai** [comment]
![20240918220719_1](https://github.com/user-attachments/assets/a0a6285a-ace0-4087-aa82-554bb753ebe3)
![20240918220717_3](https://github.com/user-attachments/assets/b0910a04-e824-474e-b379-eda9a24f66d1)
![20240918221103_1](https://github.com/user-attachments/assets/183b0bbb-add9-4475-9866-075bd7df72bf)
Normal decals after restarting MAX.

**Comment by korodai** [comment]
And before this happened again, the test game became completely white. 
![20240918220536_1](https://github.com/user-attachments/assets/096abe55-f721-42ae-b36a-b79e4ff4241d)

**Comment by Kasseyus** [comment]
@korodai Does this happen with any other weapon, or just the patrol rifle?

**Comment by korodai** [comment]
It seems to happen with any weapon that is currently on the map.

**Comment by Kasseyus** [comment]
@korodai Are you using the default version of MAX, or using the Experimental or DevTest version?

Also, does this happen every time, or is it only occasionally.  Also, are you using any custom scripts?

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
