### ISSUE TITLE
GGMAX DEVTEST - Suspect File?

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5698]
Was browsing through the files that MAX is creating in the Default Documents area.
Wondering if this one is Legit
[editors.zip](https://github.com/user-attachments/files/16812317/editors.zip)
The info in the CGF file translates as "In memory of Hui Xuan Jie" according to google.

Is this legit, or is it from unsavory sources?

**Comment by AmenMoses** [comment]
I don't have that file!

**Comment by OldFlak** [comment]
There is another one inside levelbank/testmap/cgf.cgf
![image](https://github.com/user-attachments/assets/5c643663-6871-47c3-8436-368a11058599)

**Comment by MonkeyFrogStudio** [comment]
I have both of those (one in the editors section under gridedit and one in testmap). Both look look identical to each other, but don't look like the one in your screen shot. Like AmenMoses, they refer to a .fpm and .fpg file.

**Comment by OldFlak** [comment]
Ah, ok - thanks for the input guys. 

The google translation is what threw me. Probably about as accurate as it is with taking the shortest route in a street directory
