### ISSUE TITLE
Editor - Small Right Side X Closes Editor Instantly

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#57]
Build: Public Preview

If you happen to accidentally or purposely click the small x to the far right of your map, Game Guru executable will instantly close without prompting a warning of closure of Game Guru executable. This occurs on Windows 7. What is the purpose of that close function there? Can we remove it?

Please refer to image as I'm not referring to the red window x but a small x within the editor.
![right_x](https://user-images.githubusercontent.com/35990109/35902211-5b5a0be2-0ba8-11e8-97e2-04e0d04dc05d.jpg)

**Comment by LeeBamberTGC** [comment]
The little X does the same job as the big X, it will ask you if you want to save if you have unsaved work in the level, and then close down GameGuru.  The only instance of it closing without a prompt is if there is nothing to save, which means you don't lose any work.  This is the present functionality.
