### ISSUE TITLE
MAX Enhancement - Animated Image Support For HUD Images

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#5700]
The recent livestream showing the new "video frame" element had me thinking; what about .GIF support for HUD images? This way, we could have animated elements to a HUD screen, including the in-game HUD. Similar to the video frame, there should be options on whether or not this .GIF should loop or play through once. It should also support transparencies, so that the background can be visible behind the .GIF.

This would enable us to make more dynamic and visually interesting HUDs with some moving/dynamic elements to avoid the "static" feel, add an animated loading icon to our loading screens, and I'm sure a dozen other creative uses the community could come up with.

If .GIF isn't able to be added for one reason or another (licensing of the format or something else I'm not aware of), then perhaps instead MAX's "GIF" frame could instead be called an "Animated Image" frame, and then allow you to specify a sequence of individual images that it cycles through, sort of like a .GIF, with controls for time between images, whether or not it loops, etc. 

I had done a similar effect manually for my "Terminal" script, where the logo animation is a series of individual frame PNGs, which it cycles through with a time offset between each frame, in essence emulating an animated .GIF. This uses the legacy Sprite commands, rather than MAX's built-in HUD system.

**Comment by MonkeyFrogStudio** [comment]
No, we definitely don't want/need .gif support, imo. GIF is not only a very old format, but it's restricted to 256 colors only. Using your second method (a series of individual images played in sequence) is better ... or a small video file ... or even an APNG (animated PNG file) is better.

**Comment by fearlesswee** [comment]
@MonkeyFrogStudio 
I wasn't aware of APNG, if that's superior then yeah. My request would probably be phrased better as "General Animated Image Support" lol. GIF is just usually what comes to mind when someone talks about "an animated computer image" and it's the most commonly used online.

**Comment by MonkeyFrogStudio** [comment]
PNG and APGN do not have the 256 color limit that  GIF has. So, yeah, better. ;)

Animated HUD elements has been asked for before here. One such request is this one:

https://github.com/TheGameCreators/GameGuruRepo/issues/5676
