### ISSUE TITLE
GGMAX Enhancement - Add deployable object

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5702]
We need a script to place objects on the ground for example a Tent in the same system as a campfire for Survival,RPG games, this is what we need thanks guys

**Comment by mav3r1ck1981** [comment]
copy the script and rename the copy to tent, ignore most of the settings for light and particles, and voila! a deployable tent

**Comment by Necrym59** [comment]
Please try this and let me know if any problems.
[deployable_v2.zip](https://github.com/user-attachments/files/16887124/deployable_v2.zip)

**Comment by SampeyFS** [comment]
Thanks friend

**Comment by SampeyFS** [comment]
![Screenshot 2024-09-05 114404](https://github.com/user-attachments/assets/33eca305-bbc7-432f-8e16-2d670ea67afb)

**Comment by SampeyFS** [comment]
How do I associate sleep with the tent?

**Comment by SampeyFS** [comment]
![image](https://github.com/user-attachments/assets/14ddf4b3-1ca0-4d8c-9c44-08d24ce2f668)
 Error @Necrym59

**Comment by Necrym59** [comment]
This behavior allows for an object to have a behaviour attached to be collected/carried then deployed.
Apply this behavior to an object eg: a barrel or rock. Set AlwaysActive=ON

The 'named object' being deployed (eg: the Tent) must be set Physics ON, IsImobile=YES)
[deployable_v3.zip](https://github.com/user-attachments/files/16899862/deployable_v3.zip)
if you want to use the tent to activate the sleep behavior, attach the "sleep" behavior on the tent , it will behave as normal.

**Comment by SampeyFS** [comment]
hi you said that I can match with sleep how do I do it I couldn't understand how do I position the tents and make it sleep @Necrym59

**Comment by Necrym59** [comment]
The above post explains how
Add the 'Sleep behavior' to the tent

**Comment by SampeyFS** [comment]
Yes thanks I hadn't seen can you put that the button can be changed so I can place more objects?

**Comment by Necrym59** [comment]
No you can only have 1
