### ISSUE TITLE
GGMAX Bug -  Heal Zone  used to work,  now triggers arithmetic lua error message. 

### ISSUE THREAD

**Issue by tenser-spencer** [TheGameCreators/GameGuruRepo#5704]
Heal behavior attached to a trigger Zone  used to work,  now triggers arithmetic lua error message. see attached ingame screen capture.
![luanil-error](https://github.com/user-attachments/assets/84716bfd-f681-4967-a1df-703e427ae856)

**Comment by Necrym59** [comment]
Fixed and workshop core updated
