### ISSUE TITLE
GGCLASSIC - Camera jumps FreezePlayer() UnFreezePlayer()

### ISSUE THREAD

**Issue by DarinM1967** [TheGameCreators/GameGuruRepo#5707]
As was described back in 2018 by Flatlander, when using FreezPlayer() and UnFreezePlayer() the camera jumps erratically. Easy to replicate using the Oblivion/Fallout 3 like dialog script I have uploaded under GameGuru Classic\Product Chat\Camera jumps FreezePlayer() UnFreezePlayer()

**Comment by LeeBamberTGC** [comment]
@DarinM1967 Fixed in the next update, added new "" command and updated some scripts to handle mousemove deltas when frozen, and camera angle maintained and restored during the freezing process.

**Comment by DarinM1967** [comment]
Thanks Lee!  I summited to the forum the wrong script by mistake.  Reuploaded it and explained that you fixed the FreezePlayer() and UnFreezePlayer() bug and it will be in the next update!
