### ISSUE TITLE
GameGuru MAX Dev Build Bug - Particle spawning broken

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#5708]
Particles appear even when set to not show at start in the DEV build. Everything is fine in the EXP build.

**Comment by LeeBamberTGC** [comment]
@davetgc Tried with the latest DEVTEST build and added a stock particle, switched off preview and spawn and after the last emitter faded, there was no particle emitting in my level:
![image](https://github.com/user-attachments/assets/f1e076cf-e518-45e4-85c8-0beb779f63b3)
Can you check the latest in a similar setup?

**Comment by davetgc** [comment]
Hi Lee,

That does seem to be fixed now, however, I've discovered another error, and that is that particles marked as not showing at start can't be spawned from a trigger zone. I've attached an FPE demonstrating this.
[mapbank.zip](https://github.com/user-attachments/files/17109410/mapbank.zip)

**Comment by LeeBamberTGC** [comment]
@davetgc The link did not work but I created this quickly in the latest DEVTEST and it worked fine:
![image](https://github.com/user-attachments/assets/8d409ca5-d81d-49f0-b5d6-f09ad33f8c6b)

**Comment by LeeBamberTGC** [comment]
@davetgc Managed to get your link to download, you need to create a logic link for the trigger to spawn the particle:
![image](https://github.com/user-attachments/assets/0d89bc3b-5237-4d8d-b430-a458915925fb)

**Comment by davetgc** [comment]
Hi Lee,

That's okay when the particle is near to the trigger zone, but it really needs to work from the ifused field. For example, the object triggered could be quite some way from the trigger, making the logic link system inconvenient, or even impossible to use.

**Comment by LeeBamberTGC** [comment]
@davetgc Found it :)  Fixed for the next DEVTEST build.
