### ISSUE TITLE
work shop

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#5712]
the work shop is showing no items i tried up dating it still not showing tried validating files still not showing

**Comment by synchromesh62** [comment]
Are you launching from Steam and following the Prompts **exactly** 
Its usually a 3 restart process before you see steam updating .. Check out this vid and see if it helps 
In the last restart you should see Steam updating then you know its done.

https://github.com/user-attachments/assets/a411d1ff-b007-404b-aaa6-09880d4dcb76

**Comment by zeebon** [comment]
thanks for that seems to have sorted it

**Comment by synchromesh62** [comment]
> thanks for that seems to have sorted it

Excellent !!
Its a bit long winded but you soon get used to it quickly and it seems to take no time at all once you get the hang of it :)
