### ISSUE TITLE
GGMAX DEVTEST - Devtest Project System possible bug/problem

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5714]
@LeeBamberTGC 
Hi Lee
Last time i tested this it was really cool and seemed to work like a dream .. 
Everything was accessible and what i added to the map was copied to the Project folder.
I could even **"Save Project As "** and select an external folder and continue my project that way under a new name which was basically transferring an old Project to the new system.

Now it will not allow me to add anything except stock assets ?
Have I re-tested this at a bad time perhaps whilst work is being done ?

**Comment by LeeBamberTGC** [comment]
@synchromesh62 I just tried with the latest DEVTEST, creating a new remote project called REMO1, a blank level., imported a model I created, selected REFRESH to update my current project folder, then added the newly created object to the level, then checked the remote project folder and the entity files are there. Can you reproduce this to make sure you are working again, thanks!
![image](https://github.com/user-attachments/assets/e59b3674-46af-4cee-875d-614bdd9f68e0)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Hi Lee i tried it again and it still refuses to add any of my own custom work to the map ?
I can only add Stock so in the video i was only able to add a building from the Buildings Pack. 
**sorry you cant see the mouse working**  but i am selecting items honest :)

https://github.com/user-attachments/assets/e3a81ae9-5d78-42de-9a90-f5d87928dfd4

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Just did the same with my DEVTEST version and it allowed me to add characters:
![image](https://github.com/user-attachments/assets/c8fe8295-21d5-4ba1-8f38-956999391a61)

Can you snapshot (or better zip up) the tester folder that would have been created in the dropbox folder:
![image](https://github.com/user-attachments/assets/97794385-572a-46b2-ac05-f8046991209d)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Hi Lee .. 
Ok perhaps i have over complicated my explanation so i will try to explain this way ..
When i create a project the normal way i see all my content on the left, **Stock, Custom the lot** 

![add1](https://github.com/user-attachments/assets/63f8d4b3-a3f4-4c9e-9cc3-892c79ac19e7)

However when i create a project in the Custom Folder i only have access to the **stock** on the left.

![add2](https://github.com/user-attachments/assets/077c9e25-a215-4369-b34f-0041d17b0403)

Wheres my stuff :)
Does it mean in order to create a new project i have to re-import all my custom content again ?
**If this is the case then its working** But with hundreds of hours invested creating and importing assets I'm not to sure its what users are expecting to have to do ?

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Yes you have it right, the remote project system literally gives you a clean sheet to work on, and it was only at my insistence that you can still see stock object, some of the designers of the new project system wanted those to be hidden as well :)  Copying your custom content to the remote project folder is the right thing to do. If you want your custom content to be common to multiple projects (remote or otherwise), you can place them in your main MAX root entitybank (same location as where DLC are written)

**Comment by synchromesh62** [comment]
> @synchromesh62 Yes you have it right, the remote project system literally gives you a clean sheet to work on, and it was only at my insistence that you can still see stock object, some of the designers of the new project system wanted those to be hidden as well :) Copying your custom content to the remote project folder is the right thing to do. If you want your custom content to be common to multiple projects (remote or otherwise), you can place them in your main MAX root entitybank (same location as where DLC are written)

Ok Lee that's great .. 
I think the fact i could see the Stock content and not my own was what made me think there was a problem.
But the lightbulb went on when i copied one of my folders over out of curiosity and then the penny dropped to how it was supposed to all work :)
Thanks for responding and sorry for the confusion.
