### ISSUE TITLE
GGMAX Enhancement - The Winzone "fade out" 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5716]
Currently when the player hits a Winzone in a standalone game the screen does this slow fade to black. Can this please be removed the fading out looks really bad, and it causes problems. 

First, the fade just looks atrocious. It's not like a smooth fade to black its like a lagged out fade to black. A fade option might be useful for the Winzones but most of the time I just want the loading screen immediately. Player hits the Winzone, if I have not selected play video or show image or w/e then 99% of the time I just want it to immediately go to the loading screen for the next level. 

If you select play video for your Winzone you would expect the video to play and when the video ends you are immediately taken to the loading screen. Instead what happens, is the video ends and then it cuts back to the player camera just to show the fade out from where the player was looking when they hit the Winzone.

**Comment by Necrym59** [comment]
The fade out is fixed in the DevTest version
if no fadeout at all is required use this one instead of winzone
[winzone_nofade.zip](https://github.com/user-attachments/files/16926683/winzone_nofade.zip)
