### ISSUE TITLE
Possible conflict in behaviours

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5719]
These scripts conflict with each other when you place the tent this is written about the script (deployable)

![image](https://github.com/user-attachments/assets/56d8ce4d-f3c2-491e-b4f0-4caab605d1a2)

**Comment by Necrym59** [comment]
There is no conflict, I cannot duplicate, it functions normally.
I suggest you test by removing different scripts until you find the one causing the problem
