### ISSUE TITLE
Adding a Tutorial Script to Max

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5722]
It would be very useful for RPG gamers to have a tutorial script to understand in the early stages of the game what they have to do always if possible very useful to understand the mechanics of the game

thanks guys

**Comment by Necrym59** [comment]
Use a text zone for such things would be the answer

**Comment by SampeyFS** [comment]
Help area is better to understand the mechanics

**Comment by SampeyFS** [comment]
Why was it closed? @Necrym59
