### ISSUE TITLE
Standalone does not extract Textures  Dv Test

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5725]
![Desktop Screenshot 2024 09 14 - 17 59 49 86](https://github.com/user-attachments/assets/e9828c32-6906-40ae-8d17-cf8bed3e0bf7)
![Desktop Screenshot 2024 09 14 - 18 00 36 82](https://github.com/user-attachments/assets/c08822f1-020e-48a4-9a41-65899a2de2cc)

Still the same problem not extracting DDS textures reported but it is always like this the problem @LeeBamberTGC

**Comment by SampeyFS** [comment]
![Desktop Screenshot 2024 09 14 - 18 00 36 82](https://github.com/user-attachments/assets/24fde6d7-742e-486d-a9d3-e71d8dd3acac)
![Desktop Screenshot 2024 09 14 - 18 18 03 68](https://github.com/user-attachments/assets/2b769acb-3006-432b-8b7c-f09840f1b49e)
![Desktop Screenshot 2024 09 14 - 18 18 10 55](https://github.com/user-attachments/assets/500a5054-70e7-4fbf-a0b1-ae68f493be3c)

**Comment by mav3r1ck1981** [comment]
are they set up with the correct naming conventions for pbr? _color? _normal? _surface? etc? Have they been altered in the editor as these changed dont seem to stick.

**Comment by SampeyFS** [comment]
DDS

**Comment by SampeyFS** [comment]
Nobody touched them they are dds

**Comment by Necrym59** [comment]
Where did these models come from? It seems to be amodel import problem

**Comment by SampeyFS** [comment]
I bought the models from Andrea but they are not the ones I used before

**Comment by GraPhiX-Guru** [comment]
It would be very helpful if you could either type the name of the textures or post a screen shot of a list of the textures, I have seen this happen before, it is usually the texture names have illegal characters or spaces in heir names.
things like 'my asset_color.dds' or my 'asset_surface.dds' will not work they would need to be either 'my_asset.color.dds' or 'myasset_color.dds'

**Comment by synchromesh62** [comment]
100% This is a model \ texture issue and not a Max problem ( **or we would all be posting** )
As @GraPhiX-Guru states a screenshot of the texture names and format would go a long way to maybe solving the issue. 
Just being DDS means nothing as Max recognises various formats when creating a standalone but as @mav3r1ck1981 states its the naming conventions that are important. If Max does not recognise them it will not copy them to standalone.

**Comment by SampeyFS** [comment]
Akhenaton_BaseColor  Name

**Comment by mav3r1ck1981** [comment]
shouldnt the suffix for Max just be _color? with a lowercase "c" im not sure the capital letters will be recognised. Max can be very specific about such things. All the stock assets use _color _normal and _surface which are all lower case. 

I should also mention that expecting a perfect standalone from a DEVTEST version of software is expecting rather alot

**Comment by synchromesh62** [comment]
Akhenaton_color.dds
Akhenaton_normal.dds
Akhenaton_surface.dds

As an **example** this is more like something like Max would be expecting to see.
However you cannot just rename them in the imported folders.
You would have to rename them first separately then re-import the model and apply them on import to be sure.

**Comment by SampeyFS** [comment]
ah that's why they were like this when you bought them anyway

**Comment by SampeyFS** [comment]
![Screenshot 2024-09-15 171453](https://github.com/user-attachments/assets/aa941969-250c-4bcf-a9c9-1427d8af9d54)
![Screenshot 2024-09-15 171905](https://github.com/user-attachments/assets/08793bdc-2c21-4fcd-8a9b-7ad1ad372ffa)
as you can see, the fact as you say does not extract it

**Comment by mav3r1ck1981** [comment]
Have you edited ALL affected .fpe files for each of the models? They will
all reference the old names unless you reimport them all

**Comment by SampeyFS** [comment]
oh yeah you're right I forgot
