### ISSUE TITLE
GGMax Bug -  DEVTEST - Modifying Graphics Settings Mid-Game In Standalone Causes Grass To Appear

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5727]
![Desktop Screenshot 2024 09 17 - 13 29 30 64](https://github.com/user-attachments/assets/ecda2d9b-6c9d-4614-b8d4-c77353773869)
![Desktop Screenshot 2024 09 17 - 13 30 59 29](https://github.com/user-attachments/assets/e9e00ae1-cf36-4af2-b37f-af87389a6dd7)

**Comment by SampeyFS** [comment]
Export with standalone

**Comment by Kasseyus** [comment]
Can you please send me the level where this happens?

**Comment by SampeyFS** [comment]
I also made a video here what happens to the sky and the grass watch carefully

https://www.youtube.com/watch?v=p96lchCWNdo

**Comment by Kasseyus** [comment]
Ticket in relation to issue: https://github.com/TheGameCreators/GameGuruRepo/issues/5550

In this instance, I believe the problem may be in how the grass is placed in the world.

If an area of the map is assigned grass, then the density of the grass can be controlled in the editor, but adjusting the graphics setting in the standalone game can increase the quantity of grass, and the position of the grass. It looks like the area of your map that had had roads assigned to it, also allows grass to appear there, and when the settings are adjusted to a higher quality, more grass appears in more random locations - in this case in the middle of the road.

The solution to this is to draw out the areas of your roads to make sure the engine doesn't put any grass there at all. (with the grass painting tool, it will not affect the textures you have already painted)

On some terrain biomes where grass is spawned by default, drawing new terrain will also get rid of the grass, but in instances where this is not the case and grass has been painted on, it will remain there irrespective of the texture painted over the top of it.

If you find this problem persists, please let me know by replying to this ticket with a custom FPM file, containing only stock media that I can use to diagnose the issue, and I will be able to investigate further.
