### ISSUE TITLE
Western Asset Request

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5729]
I'm looking for a Western asset I hope a DLC will come out for the project after Desert Survival a new Western game project we need buildings a pack similar to Lake Fantasy I hope a paid DLC will also be made

**Comment by synchromesh62** [comment]
> I'm looking for a Western asset I hope a DLC will come out for the project after Desert Survival a new Western game project we need buildings a pack similar to Lake Fantasy I hope a paid DLC will also be made

This any good.
https://gamecreator.store/bundle/11009
