### ISSUE TITLE
GGMAX DEVTEST - Incorrect Terrain Textures In Standalone

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5731]
When creating standalone MAX is copying the default textures to the TerrainTextures folder.
And despite copying the custom terrain folders over, is not using the ones specified by the levels.

Here be a pic of the standalone terrain folder:
![image](https://github.com/user-attachments/assets/cfd8bfe9-ae06-4011-a8a3-1f9e6ed3d731)

In test-game MAX uses the correct textures, but not in standalone.

If I delete all the default textures, the terrain in each level is just black, which indicates that MAX is unaware that each level has a custom terrain folder assigned in the standalone.

Every level in the game has custom textures assigned - even those with terrain hidden - so the default ones should not be getting copied over at all.

Thanks for checking :)

**Comment by OldFlak** [comment]
Hi @LeeBamberTGC 
The recent update has sorted the terrain issue.

The only glitch with it now is that the **default textures** are still copied over to standalone, even tho all my levels use only custom ones

**Comment by LeeBamberTGC** [comment]
@OldFlak Fixed for the next DEVTEST build, save standalone no longer includes the default textures if you are using a remote project, instead copying directly from your remote folder any textures that are needed.  You WILL need to delete the default terrain textures that have been copied over when the remote project was first created.

**Comment by OldFlak** [comment]
Hi @LeeBamberTGC, I will test this tonight after work.

Thanks for your hard work :)
