### ISSUE TITLE
Automatic Placeable Rocks and Stones

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5733]
It would be very interesting to have Rocks and Stones Placeable like trees to do it more quickly without having to place rock by rock one by one which is very convenient.

**Comment by synchromesh62** [comment]
> It would be very interesting to have Rocks and Stones Placeable like trees to do it more quickly without having to place rock by rock one by one which is very convenient.

Press " I " to Spray 

https://github.com/user-attachments/assets/ad415be9-8704-459d-ac55-25403b391810

**Comment by Kasseyus** [comment]
As Synchromesh says, after selecting the object from the asset library, you can press, "I" on the keyboard to toggle between individual placement and spray placement.

The spray placement will also apply subtle modifications in scale and rotation so it doesn't look weird and uniform when painting.  The radius of the area to be sprayed/density of the rocks can be adjusted by scaling the cursor similar to terrain painting.

This can be done with any asset from the library.

Closing Ticket.
