### ISSUE TITLE
GGMAX DEVTEST - Skybox Anomalies

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5736]
I am still finding that Editor only uses my custom skyboxes if one with the same name exists in SteamLibrary location

To test I have:
I Created a cartoony skybox called 'skyportplanet' and places it in the SteamLibrary
![image](https://github.com/user-attachments/assets/6ac55ce0-4ae7-4e50-8785-2bc6e14e7087)

My Project has the correct sky called 'skyportplanet' 
![image](https://github.com/user-attachments/assets/4e2ed554-f9e2-40d1-9058-e946c90defd3)

In the editor it will only show the one in Projects if the one in Steam Library exist 
![image](https://github.com/user-attachments/assets/4409d6f3-9203-4ab2-8605-3671522ba55f)

If I remove the one from SteamLibrary - then MAX uses default sky
![image](https://github.com/user-attachments/assets/e997bd63-8235-4b96-93fb-1006f1851c55)

Thanks for checking

**Comment by LeeBamberTGC** [comment]
@OldFlak Fixed for next DEVTEST build :)

**Comment by OldFlak** [comment]
Awesome @LeeBamberTGC fixed 👍 

Great work
