### ISSUE TITLE
Bug Text Zone with XP and Levels    ( Dev Test )

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5737]
Conflict text area with XP increase xp by passing over the writing and it tells you you have leveled up by passing over the writing if you pay attention the xp bar goes up by walking over the writing

https://www.youtube.com/watch?v=i7_cF-1Erc4

**Comment by Kasseyus** [comment]
@SampeyFS I'm not sure what I'm looking at here.  Can you please break down the issue a little.  

What is the expected outcome verses that is actually happening.
Do you have overlapping zones in this scene and that is causing a conflict?
Do the zones work as intended separate from each other?
Are you using any custom scripts?

**Comment by SampeyFS** [comment]
the text script from XP when you hover over the script is from @Necrym59

**Comment by mav3r1ck1981** [comment]
the XP behaviour wasn't designed to be used with a trigger zone, so i think that's the issue. It was designed to be attached to a collectable object that when used/consumed will give the player the stated amount of XP. Having it set as a trgger zone, i assume will add XP EVERY time you walk over it. If you want an XP trigger zone behaviour, you will probably have to either ask Necrym directly (and hes very busy at present so i wouldnt hold your breath) or see if someone in the community can provide one.

I know this as i asked Necrym if he could provide a behaviour that allowed a item to be dropped by a killed NPC that would provide a small amount of XP,  and this is the script that be created. In my isntance the NPCs drop a crystal that provides an XP boost of 25 when collected. In that scenario, it works perfectly. Ive tested it again against the latest update, and it still works perfectly.

Personally, i don't think this is a bug, i think its a behaviour being used in a manner that it wasnt designed for meaning that the results aren't as hoped for.

**Comment by Kasseyus** [comment]
@SampeyFS For issues with custom scripts, it is advised that you contact the author directly in an effort to resolve the issue.

**Comment by Necrym59** [comment]
mav3r1ck1981 is correct its designed for an object not a zone - inappropriate use of the behavior would cause that
I will look at making adjustments to use a zone later

**Comment by SampeyFS** [comment]
sorry but don't you see that it's an area on the ground

**Comment by SampeyFS** [comment]
![image](https://github.com/user-attachments/assets/2f1761d9-fdda-4d78-890e-909ba7eeec75)
Zone???

**Comment by mav3r1ck1981** [comment]
look at your video above, theres a very obvious trigger zone directly below the text zone, the white polygon on the floor. i assume thats where the XP behavior is placed? if not, where is the XP behavior?
