### ISSUE TITLE
GGMAX Bug - Video Widget Error Leading to Crashes

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5739]
When using a video inside of the story screens, and then running the game inside of the normal standalone in max error 2001 will popup and then once the error is closed out GameGuru Max will crash, this works in custom screens, and loading screens and is in the latest EXP build. 

Here's a video of it happening. https://www.youtube.com/watch?v=nhijLhVrLdQ

**Comment by Kasseyus** [comment]
@extremestrategy Hello.  I am trying to re-create this bug in order to determine the cause.   I notice you have a lot of content in your storyboard.  Does this bug present itself if you try to place the video in the loading screen of a brand new project?

Also, is it just this particular video causing issues, or does it happen with any video used?  Could try with one of the stock videos for comparison?

**Comment by extremestrategy** [comment]
@Kasseyus I ran the tests as requested and stock videos work just fine, it seems to be any video that is custom that it has problems with, I have tested three videos that are custom made at various points of time, they have both visuals and audio and they all crashed Max with the same error.  All tests for this message were done with a new project I created just for this.

**Comment by Kasseyus** [comment]
Can you please send one of the custom videos that cause the crash to me at
***@***.*** so I can perform some additional testing.

**Comment by Kasseyus** [comment]
@LeeBamberTGC Confirmed Reproduction

In DEVTEST Build - Videos placed in the 'videobank/user' folder, either manually or using the import video tool will cause the above crash to occur.  The video files themselves are fine, and will play correctly when placed in the main videobank folder.

**Comment by mav3r1ck1981** [comment]
video screens work fine for me in an actual standalone, but they don't display at all in a test standalone or preview screen, this works for both custom and stock. BUT the loop video button DOES NOT WORK. it only plays the video through once and then stops

**Comment by Kasseyus** [comment]
@mav3r1ck1981 Although related, this is a separate issue.  Can you please create a new ticket for this issue, and I will investigate directly.   It's more practical to have one ticket per bug, so they can be investigated and resolved individually.

**Comment by mav3r1ck1981** [comment]
yeah my bad, i know better than to hijack a thread ;)

**Comment by LeeBamberTGC** [comment]
@Kasseyus Bingo:
![image](https://github.com/user-attachments/assets/aa321648-19b1-40ce-8cad-aaab4d709c30)
The only missing piece of the reproducible notes is that the videobank\user should be in the writables area, not the root area. Leave it with me now :)

**Comment by LeeBamberTGC** [comment]
@Kasseyus Such an easy one when it can be reproduced quickly :)  Fixed for next DEVTEST build.

**Comment by extremestrategy** [comment]
Just tested it, ti's fixed, thank you.
