### ISSUE TITLE
Strange issue in the latest update .. 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5740]
As the title states ... Strange issue in the latest update .. 

**EVERYTHING WORKS** 
No problems whatsoever, 
Everything I reported regarding saves, and fails on loading my other levels etc are fixed !!
Awesome update for me and current Projects running smooth as silk.
Nice one Guys .. Thanks so much. The hard work is appreciated.
Just wanted to let you know, 
Credit where its due  :)

**Comment by Necrym59** [comment]
I can verify this - it must be BUG! I shall escalate this to Lee :)

**Comment by LeeBamberTGC** [comment]
HAHA. Good one!

**Comment by Kasseyus** [comment]
Too hard to fix!
