### ISSUE TITLE
Generator Question

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5741]
From this error to Empty generator without petrol am I wrong or is it a script problem? thanks

https://www.youtube.com/watch?v=gJ9ct7FGeLI

@Necrym59

**Comment by SampeyFS** [comment]
![Screenshot 2024-09-23 133416](https://github.com/user-attachments/assets/74b4737f-e24d-4ab4-933a-9d1c75c3c248)

error when trying to start the generator without petrol in the video the lua error was not visible

**Comment by Necrym59** [comment]
Fixed and uploaded to workshop
