### ISSUE TITLE
GGMAX Bug - Audio from videos in the screen video option continues to play screens changed

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5743]
When a video is put inside one of the screens of the story board, if the video has an audio then the audio will continue to play if the screen the user is on has changed, what should happen is the video should top playing when the screens are changed but it isn't.

Video showing it https://youtu.be/rLpHiAIoPNI

**Comment by LeeBamberTGC** [comment]
@extremestrategy Fixed in next DEVTEST :)

**Comment by extremestrategy** [comment]
Fixed, thank you.
