### ISSUE TITLE
Level Zone Added function

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5746]
![Desktop Screenshot 2024 09 24 - 10 05 04 66](https://github.com/user-attachments/assets/92b683f1-949f-4661-9917-2aa014b05ce7)

It would be nice to have the addition of paid travel for my map example I have to make the trip to the mine by paying I hope it will be listened to this idea would be very useful

**Comment by Necrym59** [comment]
You can do this already by making a trader or shop to pay for somthing eg: perhaps a buy a ticket! The use the ticket with an object. Specific uses for your game is somthing you can work out yourself.

**Comment by SampeyFS** [comment]
I didn't understand what you mean

**Comment by SampeyFS** [comment]
![Screenshot 2024-09-25 130905](https://github.com/user-attachments/assets/33fe9cb1-62e7-4662-9820-cf116c1ec629)
I found how to do it but I need it to be bought always not just once can you do it?

**Comment by Necrym59** [comment]
Can you explain how you have set it up
Do you have a buy object linked to an levelzone?

**Comment by SampeyFS** [comment]
I set it to not delete the little man that would be the button to call the trigger level

**Comment by SampeyFS** [comment]
Hi, can you do it so that you can always buy it, not just once? Thanks @Necrym59

**Comment by Necrym59** [comment]
Have a 'Buy Object' (man) 'Delete on Buy' set to OFF - linked to a 'Level Zone' that is set to Spawn at Start OFF.
When you buy the zone is then activated, and you can go to another map selcted. To return setup the same on that map.
In standalone, when you return from other level it should be reset. Dont turn on 'reset states'.
