### ISSUE TITLE
GGMAX Bug - Can we please have the VR issue looked at before the Retail release.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5747]
Can we please have the VR issue investigated before the Retail release. ?
It might only be a 2 minute adjustment.
Otherwise it will be another 3 months to wait before the next main update :(

**Comment by GraPhiX-Guru** [comment]
Yes i would also like this

**Comment by Kasseyus** [comment]
@synchromesh62 Which issue - is this in relation to another (or other plural) VR issues?

**Comment by synchromesh62** [comment]
> @synchromesh62 Which issue - is this in relation to another (or other plural) VR issues?

Lee is already aware VR is not working .. All you see a little of a flatscreen above your eyeline and the rest is black.
Its been reported previously and Lee said he would fix it in the last Stream in Q&A.
This is pretty much what you see.. 

![VR](https://github.com/user-attachments/assets/927709f6-48c3-4ab4-8429-dc471237d602)

**Comment by synchromesh62** [comment]
Preben took a look at this for me this morning and found the problem
He has sent the fix to Lee so i wont close this just yet until its confirmed in the Devtest as fixed.

**Comment by plemsoft** [comment]
@LeeBamberTGC Fix added to latest pull :)

**Comment by synchromesh62** [comment]
Confirmed Fixed in the EXP update ..
Thanks Preben
