### ISSUE TITLE
Arrows keys as the WASD keys

### ISSUE THREAD

**Issue by MadLadDesigns** [TheGameCreators/GameGuruRepo#5751]
Could we PLEASE have an option to turn smooth movement for the arrow keys on / off? I'm left handed so use the arrow keys on everything for movement and the mouse in the left hand for turning. When I use them they seem to 'swish' the fov and then I can't turn with the mouse. This is the one thing stopping me from using GGMAX.

**Comment by Kasseyus** [comment]
Issue currently exist in GitHub, reference: https://github.com/TheGameCreators/GameGuruRepo/issues/5749
