### ISSUE TITLE
GGMAX Bug - Logic Links won't activate if the Player is more then 500 units away

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#5753]
When using logic links and ActivateIfUsed links from an entity/zone, triggering will not occur unless the player is within 500 range of the triggering entity/zone, which can limit their use in almost all scenarios, and disabling the lua optimization doesn't solve this problem.

**Comment by Necrym59** [comment]
Verified
Tested NPCINZONE and other entities wont trigger unless the player is within an arbitrary 500 range.

**Comment by AmenMoses** [comment]
It is actually 600 units according to my testing of the trigger zone.
Anyhow I assume this is some attempt at performance enhancement, i.e. limiting the amount of "in zone" checks that the engine has to do but if so this is entirely the wrong approach.
The better approach is a two-fold one:
1) When a zone is edited the distance from the origin to each node should be calculated and the largest value set as the detection range.
2) Add a parameter to each zone specifying  how often to do the detection check, default this to 1/10th second or something.  Let's call this detection period.
3) Within the engine create a separate list of all zones, every frame loop through this list and if check if the last time detection was done for this zone is greater than the detection period for this zone and if so do the processing if the player is within the detection range and note the time against this zone.

Just my two pennies worth as a professional real time software programmer.

**Comment by Kasseyus** [comment]
@LeeBamberTGC Verified

Screenshot:
![Trigger Zone Player](https://github.com/user-attachments/assets/d59676a4-8faa-41e6-9a1e-da3f09134671)

The sound effect will not trigger until you cross the threshold shown in the incredibly sophisticated screenshot diagram.

**Comment by Necrym59** [comment]
This has become a big problem for game logic now and need addressing as soon as possible as this effects other entities with attached behaviors not just zones. (Even with SetEntityAlwaysActive(e,1) set in the behavior ).

**Comment by synchromesh62** [comment]
We had this before and Lee put it back .. Currently my project and all the logic works perfectly in the EXP but this range thing breaks nearly all my logic in the Devtest :(
I hope it gets sorted as the alternative is just scrapping it :(

**Comment by plemsoft** [comment]
**Fixed the issue with the zones** , but do not know what the other problem is , tested logic link they work on large distances also tested "if used" it also work over large distances , could someone explain what other then zones do not work over large distances ? :)

**Comment by synchromesh62** [comment]
> **Fixed the issue with the zones** , but do not know what the other problem is , tested logic link they work on large distances also tested "if used" it also work over large distances , could someone explain what other then zones do not work over large distances ? :)

Fantastic !! 
Preben your amazing .. 
I will have to retry the Devtest and see if your one fix has rectified all :)

**Comment by synchromesh62** [comment]
@plemsoft 
Ok looks like the zones are now working. Yay !!
 But other things i thought were not triggering ( like AI ) are failing to spawn via a zone giving the impression it was the same issue. In this vid i have both these set to " **Do Not Show On Start** " which should appear when triggered.
 Yet they fail to appear .. This also may be why some think its the distance related thing.
 
https://github.com/user-attachments/assets/c8553c38-c2d9-4322-88ac-7d81a4d2a752

**Comment by plemsoft** [comment]
@synchromesh62 Need to wait for Lee to merge and compile a new devtest, he will add "fixed but need confirmation" when that have been done :)

**Comment by plemsoft** [comment]
@synchromesh62 The issue in your video , "Do not show on start" is also fixed, and waiting for Lee to compile a new DevTest :)

**Comment by synchromesh62** [comment]
> @synchromesh62 The issue in your video , "Do not show on start" is also fixed, and waiting for Lee to compile a new DevTest :)

Fantastic !!
Thanks Preben Your an absolute star :)

**Comment by synchromesh62** [comment]
@plemsoft 
All working perfectly .. Thank you so much :)
I cannot close it yet though in case the original OP confirms still has a problem but if your happy that if mines working his should be then please close at your discretion :)
Again thank you so much ...
