### ISSUE TITLE
 scripts disappeared on steam  workshop 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5754]
![Screenshot 2024-09-27 100522](https://github.com/user-attachments/assets/25a3c5c1-8e9d-4aa5-9cb0-99777ca8915c)

**Comment by LeeBamberTGC** [comment]
@SampeyFS Can you screenshot and send me the screen you see when you go here:
![image](https://github.com/user-attachments/assets/9887280f-1f80-457b-9fac-d7362a0653de)

**Comment by SampeyFS** [comment]
![Screenshot 2024-09-27 172306](https://github.com/user-attachments/assets/0b409468-9a7b-4f2f-b366-424c07b80bc6)

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks for the shot, looks like your workshop items are up to date.  What script do you know is missing?

**Comment by SampeyFS** [comment]
![image](https://github.com/user-attachments/assets/6a4314e1-b74d-4394-8fd4-e4a80a92bf23)

the necry scripts box is missing where you select them, you see it has disappeared

**Comment by SampeyFS** [comment]
Extra behaviors disappeared on steam @LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@SampeyFS What script "specifically" do you know is missing?

**Comment by SampeyFS** [comment]
the extra content of @Necrym

**Comment by Necrym59** [comment]
Hes talking about the extra behaviors in the workshop doesnt seem to be there anymore
![steam2](https://github.com/user-attachments/assets/04d03ff0-3651-4032-95d1-d6afeab12f39)
![steam`](https://github.com/user-attachments/assets/ddee7ddb-090d-4597-a088-ff26d1169b36)

**Comment by Necrym59** [comment]
Yet it shows up here
![steam3](https://github.com/user-attachments/assets/e8dec54d-6180-49b9-a348-349efaf5992f)

**Comment by SampeyFS** [comment]
![image](https://github.com/user-attachments/assets/aed04424-4069-40e9-b1c3-551b7b14829b)


Now it works I'm closing
