### ISSUE TITLE
GGMAX Bug - DEVTEST - Runtime error 501 terrain textures keep crashing program when trying to select them.

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#5756]
I ran into a new problem when trying to select the terrain textures in a new level I'm working on. They are fine at first but after working on the level for a while when you try to select the terrain textures I get this error message and then the program crashes. I've had this happen on two levels recently. I tried verifying the files on steam to make sure something wasn't corrupted or missing but that didn't seem to fix it. Here's a picture of the error message.
![error](https://github.com/user-attachments/assets/d753c5d2-2819-4f4e-9831-7712811a2f9c)

**Comment by Kasseyus** [comment]
@mike123yy I am attempting to reproduce this issue.  Would you be able to send me an FPM file of the map you were using when this crash occurred, and the terrain palette that you tried to switch to?

These can be sent to chris@thegamecreators.com

Also, at what point in the process did the crash occur?

**Comment by mike123yy** [comment]
I will send you that file right now. As far as the terrain palette I'm just using the default one but I did modify the mat 32 texture to be concrete instead of the blank checkered texture. Although the error above says it has an issue with Matt one and I did change everything back to default and got the same error. I will include the modified Mat texture anyway with the files I send. If I go to my test level that I use for testing models and scripts the textures work just fine. I figured out if I go to that level and save and then go back to my other level and click on the terrain textures icon I won't get a crash but I have to do that every time or it crashes automatically. Anyway, that email should be coming through any minute.

**Comment by Kasseyus** [comment]
Thank you.  I've received the files now and will run some tests shortly to see if I can re-produce the issue with them.

If you are able to record a video of the steps leading up to the crash, and the crash itself, that may also be useful in determining specifically the order of events where things are going wrong. 

Also, a couple more questions to help me narrow things down...
1> How did you try to use the modified mat32?  Did you create a copy of the default terrain textures and try to select it, or did you modify the default mat32 directly?
2> If you made a copy of all the default terrain textures, did you store them in the 'writable' terrainbank folder, or the 'root' terrainbank folder.
3> The video may help with this one, but what did you press to trigger the crash, e.g. the terrain painting tab, the texture selection itself, the option to switch folders, etc.

**Comment by mike123yy** [comment]
Here's a video showing how the crash happens:
[https://youtu.be/GS4gcOQ7R5Q](url)

I did create a copy of all the default textures and put them in the Max files in the my documents section but the order and the sounds were getting messed up so I modified the main folder terrain texture on the mat 32. After getting the crash though I verified all the files which made them go back to default and tried it then and it was still giving me the crash. You will see it in the video but to get the crash it happens when you click on the terrain painting tab. The odd part is the textures work fine with no problems on one map but it crashes on another.

**Comment by Kasseyus** [comment]
@mike123yy Could you please try verification of installation files through Steam and see if that makes any change?

**Comment by mike123yy** [comment]
I just verify the files and it said it acquired six missing ones but when I tried to select the terrain textures on the level the crash is still there with the same error code. I would assume three of those files it reacquired were the custom textures I added for asphalt, one was the cineguru max file but the other two I don't know.

**Comment by korodai** [comment]
This also happens to me on a level using the normal Steam version.  If I load a different level first and paint the terrain, then go back to the original level then I don't get the error.   63892 : Runtime Error: 501 : terraintextures\mat1\Color.dds ()  S:396MB V: (7935,0) 

![image](https://github.com/user-attachments/assets/61fa6a80-be11-4db2-90ae-890ee34ce99b)

**Comment by Kasseyus** [comment]
@mike123yy Does this error only occur on an existing level in your project?

Can you create a new level in a new project and paint terrain?

**Comment by mike123yy** [comment]
It only seems to be affecting the one level.  I tried a bunch of my older levels And made a new level but they don't seem to have a problem.  I got it fully painted by going to the other levels first and loading them and then going back to this level to get the textures to work like I said above. As long as it's an isolated incident I guess we can consider it closed but I noticed someone above gave a thumbs up to the issue so I would assume I'm not the only one who had the problem.

**Comment by Kasseyus** [comment]
@mike123yy 
Can you send me the FPM of the affected  level please?  If I can reproduce it locally, I may be able to figure out why it is crashing.

You can send it to chris@thegamecreatorrs.com

**Comment by mike123yy** [comment]
I just sent it, let me know if it doesn't show up and I will send it again

**Comment by Kasseyus** [comment]
@mike123yy It's an interesting problem.  Thank you for sending the FPM file.   I was able to use it to re-create the crash.

From what I can gather, *something* has happened to the first texture material, which MAX doesn't like.  It may be when you edited the default textures in this scene.  The fact it only affects this scene and no others further lends itself to the fact this is an  issue with the map file, rather than MAX itself.

The solution to this problem is as follows..

1> Load New Project
2>  Import Corrupted FPM File
3> Edit Starter Level to  Access Terrain  Palette
4> Load Corrupted FPM File
5>  Select, "RRESET DEFAULT TEXTURES"   (now that  you  can accesses this pane)
6> Draw on the map, just a few dots.  (to make a change)
7> Save Ass V2.  (e.g.,  sightings = sightings2)
8>  Delete Corrupted FPM from  the storyboard
9>  Quit  MAX and Re-Launch
10>  Import  V2 and place it where V1 was

Link to  Video  for  Clarity:
https://youtu.be/Qla7QBXK160

This should now be back to an editable state.  Once your  happy that V2 is identical to V1 and  your project is back on track, swiftly and forcefully eject V1 into space and throw it into the sun.

**Comment by Kasseyus** [comment]
Also, for any custom terrain textures, it is always advisable to make a new complete set, even if you only plan to edit a couple of them.

**Comment by mike123yy** [comment]
That fixed it, thanks for the help. When I was first doing the textures I copied the whole folder, renamed it and stuck it in the my documents folder so I could edit the ones I wanted but all the footfall sound effects seem to have gotten messed up doing it that way. Changing a texture in the main folder didn't seem to have that problem. I'm not sure why the footfall sounds would change just by having it in a different folder but that's why did it that way.

**Comment by digital-i-ghub** [comment]
Just chiming in that I'm getting this error as well, no custom terrain textures and on a relative fresh level used for behavior testing.  Error takes a while but has popped up on multiple projects.  Will try the Kasseyus work around and the other mentioned by mike123yy

![error code](https://github.com/user-attachments/assets/385eee87-72cf-4f5a-83e5-cd4e3c37fac3)

**Comment by therickman** [comment]
Hello , this is to report that I have the same problem, same error message.
Build : latest experimental as of 18/10/2024
steam version.
Happens when I try to paint terrain, when I click on the paint terrain tool ( button)

**Comment by Kasseyus** [comment]
@therickman I have posted a set of steps to follow to resolve this issue above.  The problem is caused by some sort of issue with the default terrain texture palette and they need to be restored to default.

**Comment by mike123yy** [comment]
This does seem to be a temporary fix.  I had it happen on another level and I did these steps to fix it but after a couple days it starts having the same problem again.

**Comment by Kasseyus** [comment]
@mike123yy It's been flagged as Officially Reproduced, so it's now on the list of confirmed bugs that are waiting to be fixed by the Dev Team.

The solution above is indeed a temporary solution, as it allows you  to carry on with your project while waiting, but it will be fixed properly in due course.

**Comment by plemsoft** [comment]
@Kasseyus Could you e-mail me the test level so I'm able to see what the problem is plemsoft@gmail.com , thanks :)
