### ISSUE TITLE
GGMAX Enhancement Request - Add Loot Table Option to Animal Behaviours 

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#5757]
Currently the loot table system added to NPC behaviors does not extend to animal behaviors such as mammal. Requesting that this feature be extended to any AI (i,e. rats, fish, birds, etc.)

I know this has been requested previously but the only instance I could find was #5345  which is closed. During that discussion it was suggested to use NPC Item Drop but this will not worked on cloned entities. 

Since I'm asking for stuff I'd also like to reference request #4455 which is currently open since it's related to the core use case leading to this request.

If request can't be done in the short term (i.e month or two) please notify me so I can plan around it.

**Comment by mav3r1ck1981** [comment]
second this please

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive In the next DEVTEST build, ANY character, even if an animal (technically a character flagged object) now offers the loot drop option:
![image](https://github.com/user-attachments/assets/0aadcae2-b1ce-45fd-a274-ce6aa0cd2a15)

**Comment by Blood-Moon-Interactive** [comment]
This works amazingly! Thanks so much, it's a huge help.
