### ISSUE TITLE
Sprite Scaling Bug

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#576]
Sprite jagged edges issue, no matter what scale I choose I get jagged lined edges to the sprites.

Large sprites at 1:1 are ok, just scaling is not smooth. 

see image (best to download and view at 1920x1080) 
![sprite_issue](https://user-images.githubusercontent.com/36561118/60682996-74488d80-9e8d-11e9-8cad-54c2ad9af984.jpg)

the sprite is below.
![happy1lrg](https://user-images.githubusercontent.com/36561118/60683008-83c7d680-9e8d-11e9-8e16-854e59c63dc4.png)

Im running at 1920x1080 resolution on windows 10.

**Comment by AmenMoses** [comment]
![same](https://user-images.githubusercontent.com/35708338/60760019-01bee580-a026-11e9-994f-9e13d5ac6d82.png)
Looks the same to me!

**Comment by LeeBamberTGC** [comment]
@tarkus1971 Are you using the latest Public Preview as it had a fix for this (sorting the half-pixel shift issue)

**Comment by tarkus1971** [comment]
Sorry for the delay, I'm using the BETA build Lee.  Yes AmenMoses maybe that is right, they look the same, maybe that smaller sprite just needs to be designed "bigger" in the 1st place, has anyone else listed a jagged sprite scaling bug.  If not then it might just be the lack of size in the sprite, design big and shrink it down I guess.......

**Comment by AmenMoses** [comment]
Just use a higher resolution image and let GG scale it down, make sure that the image background is pure alpha and the image hasn't been anti-aliased to a different background otherwise you will get strange results.

**Comment by tarkus1971** [comment]
Will try that as soon as I re-formatted and re-installed W10 on my Laptop which has been acting a little "odd" lately.

**Comment by synchromesh62** [comment]
Assuming this was worked out.
