### ISSUE TITLE
GGMAX Bug - Using the LUT Changer Behaviour Resets Water Level

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5761]
If you use the Watercontrol script and then afterwords use the LUT Changer script it will reset the water level. 
Video: https://youtu.be/rZbFs8RL0eY

How to reproduce. 
- Set your waterlevel 
- Assign Watercontrol Behavior to an entity. Set the Action to Lower. Adjustment amount to 500. 
-  Assign LUT Changer Behavior an entity.
- Add 2 trigger zones and connect 1 to the Watercontrol entity and 1 to the LUT Changer entity.
- Start your game and activate the Watercontrol to lower the water. 
- Next, walk into the triggerzone to activate the LUT Changer. 
- The water level will reset.

**Comment by Kasseyus** [comment]
@LeeBamberTGC
