### ISSUE TITLE
Loss of underwater particle transparency !

### ISSUE THREAD

**Issue by DJRossterman** [TheGameCreators/GameGuruRepo#5762]
Game no longer saves transparent particles, when saving game in-fo. when reloading level all transparent particles are reset, same happens when saving game and reloading game in play mode this happened after last update ! steam://openurl/https://youtu.be/3Adg6APuX9c

**Comment by mav3r1ck1981** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/5742

**Comment by Kasseyus** [comment]
Closing Duplicate Ticket - Please follow the other ticket for updates :)
