### ISSUE TITLE
to have the recording mode on or off [REQUEST]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#5763]
I know WASD are best for killing all them game, but in a game puzzle you don't really need it, just with the arrows you can play a game,
tbh I prefer arrows rather than WASD, so, can we have the both systems, so, you can choose one or other?
Now I'm experiencing and issue lossing RMB control in the game, and someone pointed me this has todo with the arrows use. 

https://github.com/TheGameCreators/GameGuruRepo/issues/5760

**Comment by Kasseyus** [comment]
@3coms The issue with the arrow keys already has a ticket, which has been successfully reproduced, so I will close this one.
