### ISSUE TITLE
GGMAX Bug - EXP build standalone yields a very strange result

### ISSUE THREAD

**Issue by LightofAlfheim** [TheGameCreators/GameGuruRepo#5764]
Menus are messed up, and loading into the game just puts me into the standard ggmax level. Whats even weirder, is that syncro tells me that EXP and release build are identical. However, this bug only happened when i saved standalone on the exp build. I go back to release and its normal. Thoughts?
![1002](https://github.com/user-attachments/assets/6ad0843f-d840-42ae-bcde-22488cb23548)

**Comment by Kasseyus** [comment]
@LightofAlfheim 

In order to try and reproduce this issue, I need a little more information.  Can you please make a longer video showing what  steps were taken before this point?

For example, is this a new project or a level on an existing project?

**Comment by Kasseyus** [comment]
@LightofAlfheim 
Are you still having this issue with your standalone?

**Comment by LightofAlfheim** [comment]
> @LightofAlfheim Are you still having this issue with your standalone?

sorry for not responding, i am not having this issue any more so ill mark as closed
