### ISSUE TITLE
Particles settings are Reset everytime you open your level

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5766]
On the EXP. 
Particles Opacity is reset to default 100 everytime you save a level, then close/reopen Max and then load the level. 

Video: https://youtu.be/eFprGai3OIM

To Reproduce: 
- Create a blank level and place a particle effect, something  like the thick smoke to to easily see. 
- Set the Opacity very low something like 5.
- Save the level and close Max.
- Reopen Max and load the level and the Particles Opacity will be as if  it was set to 100.

**Comment by mav3r1ck1981** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/5742

**Comment by Kitakazi** [comment]
Ah I saw your thread but only read the title. I will post my info over there thanks.
