### ISSUE TITLE
GGMAX Bug - Marker Elements from CineGuru are showing in the actual game when activated. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5769]
After last EXP version, Marker Elements from CineGuru appear inside cutscenes, and stay in the game world after the cutscene. Completely ruining cutscenes as you can image. I need this fixed asap or I will not be able to enter my game into the Halloween Contest.
Beyond irritated at the moment.   I paid money for CineGuru... then a GGMax update that has nothing to do with CineGuru, breaks it. 

I have multiple levels in my game with multiple little cutscenes and this happens on all of them. It isnt all the CineGuru elements, sometimes its the Camera elements, in other cutscenes in the trigger elements. 

This didn't happen last EXP version... Here is a video showing just how much this ruins my level. The camera element just blocks the whole screen lol. 
https://youtu.be/r7_hLQbFLvk

[cineguru bugmap.zip](https://github.com/user-attachments/files/17323852/cineguru.bugmap.zip)
Here is your simple FPM level showing the issue. Just walk into the trigger zone and you will see after the cutscene, the Camera Element from CineGuru will be visible in the game world.
And I believe EXP and Retail are the same versions at the moment? Let me be clear, I (tried) built this game specifically for this Halloween contest, I tried to build a very simple game, using basic stuff in Max that would play on its strengths and it's just always something man. Last Halloween it was the same thing... Made game with Max for Halloween contest. Had to jump through hoops and workarounds to get the game to build and be playable without noticeable bugs or issues. Now between this and particles just not working its just to much... 

![image](https://github.com/user-attachments/assets/8e4cae94-fd41-4e28-9bfe-d87d8ede9b55)

**Comment by plemsoft** [comment]
@LeeBamberTGC Reopen this as the bug is still in the changes you made and have NOT committed, so not sure what it is, I just made a version Kitakazi can use for the contest until the bug is really fixed :)

**Comment by LeeBamberTGC** [comment]
@plemsoft Can you point at the changes I have made, as far as I can see all my changes are committed and in the DEVTEST build.  Maybe you can show me the changes you made and I can compare with what I have here locally.

**Comment by plemsoft** [comment]
@LeeBamberTGC Think you misunderstood me :) , I did not have your latest changes in my version , and my version did not have the problems, so the bugs must have started from the commits that I did not have in mine, so think that's around 1 month back of your commits that must have introduced the bugs. I have not pulled the latest "main" yet with your changes, will do that later :)
