### ISSUE TITLE
Game Guru Error: This file is encrypted and cannot be loaded into GameGuru editor

### ISSUE THREAD

**Issue by Allfatherodin** [TheGameCreators/GameGuruRepo#5770]
Good evening GG Legends. For some reason this pops up when exporting a standalone upon launch.
From what I can see it doesn't affect gameplay, but I can't put this up as a game for people to play if this pops up.

It happens on any project, even a blank project with a spawn and a win zone. Is it a bug or have I done something wrong?

![error](https://github.com/user-attachments/assets/a47047fa-79af-44fc-a155-24f25af4b2b8)
![error2](https://github.com/user-attachments/assets/9496f570-bc33-4860-83b4-e7826c38f4b2)

I have tried finding logs in the standalone folders and the engine folders but cannot seem to see anything.

Cheers guys!

**Comment by SampeyFS** [comment]
yes they are already aware they are working on the problem

**Comment by Allfatherodin** [comment]
@SampeyFS great stuff!
tbf I have just tried the experimental thing (not sure, never used it) that was mentioned on #5397, although it took a while to create it with a load of not responding, the standalone does in fact launch without errors.

**Comment by Kasseyus** [comment]
Issue already logged and currently being investigated

Ref: https://github.com/TheGameCreators/GameGuruRepo/issues/5752
