### ISSUE TITLE
GGMAX Bug - " Save As " Backup Maps replacing the main level in Projects

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5771]
**" Save As "** Backup Maps replacing the main level in Projects. 
Not sure if this is a bug or now intentional ( it never did it before )
If you save a level as a backup it replaces your **Main Project level in the Hub** 
Not ideal if you do not notice and need that backup later only to find **that is the one you messed up.**
I don't think a **Save As** was intended to replace the main map ?

https://github.com/user-attachments/assets/83dad03a-2455-478e-8030-aa13eb533e7f

**Comment by Kasseyus** [comment]
I believe that is how it was designed to work, like other tools such  as Blender or Word, etc.

When you "Save As", you move to editing the new file, and the previous file remains in it's last saved state.

Backups would be preserved for both FPM files in the "_automatedbackups"  folder in the event  of a future critical failure.

@LeeBamberTGC , can you confirm?

**Comment by LeeBamberTGC** [comment]
@Kasseyus @synchromesh62 Yes the SAVE AS replaces the current level with the new saved level as it assumes this is the latest one that needs referencing. For back-ups, you can simply look into the "_automatedbackups" folder and all previous levels are stored there each time you save anything.

**Comment by synchromesh62** [comment]
@Kasseyus 
@LeeBamberTGC 

Ok thanks for confirming, like i said i wasn't sure if this was now intentional as it never did it before and i only noticed by accident. I will have to keep this in mind when editing in the future. 
My strict method of keeping backup maps has always been editing at least 3 of the same map ( **mymap1, mymap2, mymap3** ) and rotating them as I work. That way i always had something recent to go back to if one suddenly got corrupted or things went wrong but they were always saved independently never replacing the original in the Project hub which would normally been my last save in a heavy session.

This however will still be the case for at least 2 of them so no Biggy now I am aware of it and its working as intended.
Of course as stated we have the **automatedbackups** although non of this will stop me backing up my whole **GameGuruApps** folder to various drives weekly as i have done for years now.
Its not that I don't trust Max, I just don't trust Windows :)

**Comment by Kasseyus** [comment]
> I just don't trust Windows :)

This is the path to Wisdom. :D
