### ISSUE TITLE
GGMAX Bug - Importing .fbx requires 90 deg X rotation

### ISSUE THREAD

**Issue by Dr-Eyeball** [TheGameCreators/GameGuruRepo#5774]
Importing any .fbx requires a 90 deg X rotation, plus a altitude/height adjustment, plus re-centering.
Importing any .obj results in the model being upright (at it's origin) as expected.
###### I am uncertain whether this could simply be the default export options for various model editing programs (eg: blender).

This .obj model import is upright as expected.
![20241014125944_1](https://github.com/user-attachments/assets/bbf67108-e7b7-4f59-8ce6-8b79bf370a56)

This .fbx model import is rotated -90 degrees along x-axis.
![20241014130029_1](https://github.com/user-attachments/assets/36790f87-5938-4619-88b1-dc0dd8071b7c)

Because of the .fbx import rotation, it requires further rotation of 90 degrees along x-axis plus a altitude/height adjustment, plus centering.
![20241014130116_1](https://github.com/user-attachments/assets/f8e83eb1-2eb9-425b-9689-b2a8b541b592)

**Comment by Dr-Eyeball** [comment]
@Kasseyus 
See the other issue #5773 for details that Steam Verify Integrity failed to validate, which must have been the cause of this problem.

### Retested now:
I redid an existing door import #15, and the model is properly rotated.
I tried a new door import #14 and that model is properly rotated too.

You can consider this non-issue solved. Thanks.
## Close issue.

**Comment by Dr-Eyeball** [comment]
@Kasseyus 
Upon starting more imports today, I found the 90-degree rotation issue occurred on the first .fbx import. So I'll reopen this one.

**Comment by Kasseyus** [comment]
@Dr-Eyeball When Importing custom models, it is important to ensure that the models have clean transforms, for example, the models being correctly centred, with a scale and rotation modifier of 1.0.

For Example...
![image](https://github.com/user-attachments/assets/4e24cff0-e26e-47e1-ab37-41196fc95d5e)

If not, then you will see artifacts such as this during the import process.

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
