### ISSUE TITLE
GGMAX Bug - GameGuru Max does not create an executable for Windows.

### ISSUE THREAD

**Issue by TennisDeveloper357** [TheGameCreators/GameGuruRepo#5775]
GameGuru Max does not create an executable for Windows when exporting and saving a standalone game.

**Comment by TennisDeveloper357** [comment]
Exported standalone to another drive with more space. However, in running the game a runtime error occurred.

**Comment by Kasseyus** [comment]
Can you please provide video or screenshots of the error taking place?

**Comment by TennisDeveloper357** [comment]
The game was completed without the runtime error.  However, I keep obtaining an "encryption," error when the game starts.  This occurs twice with the same result.
![FileEncrupted](https://github.com/user-attachments/assets/48af8a27-564a-488a-89a1-b75a81d76691)

**Comment by AmenMoses** [comment]
Dupe of #5752?

**Comment by synchromesh62** [comment]
We all seem to be getting that prompt at the moment launching a standalone 
Usually if you click OK it then runs as normal .. Well it does for me anyway.

**Comment by Kasseyus** [comment]
> The game was completed without the runtime error. However, I keep obtaining an "encryption," error when the game starts. This occurs twice with the same result. ![FileEncrupted](https://private-user-images.githubusercontent.com/138147268/376778431-48af8a27-564a-488a-89a1-b75a81d76691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODIyMzAsIm5iZiI6MTcyOTA4MTkzMCwicGF0aCI6Ii8xMzgxNDcyNjgvMzc2Nzc4NDMxLTQ4YWY4YTI3LTU2NGEtNDg4YS04OWExLWI3NWE4MWQ3NjY5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxMjMyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTJmMmQ5OTgzMmQwOWJhNWZmZTNhMzcyNTlmMmM5ZjY5YWQ5NGRmNmNlOGE1ZjlkNTBiOTcyNjU1NGMxMWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nANkzmJJrvbB3BohC6X_nMZFRjpLRjbDvlS7YfsuM3g)

This bug is currently being investigated in another ticket.

**Comment by Kasseyus** [comment]
@TennisDeveloper357 When MAX failed to generate an executable, did it crash during the build process at either 5%, 22%, 33% or 85%?  (or any percent for that matter)

If so, may be a similar issue as: https://github.com/TheGameCreators/GameGuruRepo/issues/5728

**Comment by Kasseyus** [comment]
This issue should now be resolved from the September Update.
