### ISSUE TITLE
GGMAX Bug - [Standalone Export] Custom Material Textures Not Included Unless Used as Default on Another Entity

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5778]
Adding a new custom color texture to a model via Custom Materials will not copy over when you build a standalone game.
The texture file doesn't get included in the standalone build unless it’s also being used as a default texture elsewhere in the project. So the issue is that custom textures are being excluded from the build if they aren’t linked to a model as a primary texture.

- Open paint and create a new texture, like a solid green 512x512 img. 
- Export to your gameguru folder.
- Open a new level and drop in an entity. 
- Assign your new texture to the entity in the editor via the Custom Material tab. 
- Export Standalone and the texture will not be copied over into the Standalone folder.

**Comment by casigus** [comment]
i cant even get the texture to stay in game, even before exporting, it just switches back automaticly, same happens with emission textures. theres clearly some massive texture issues with ggmax. #5785 as example.
