### ISSUE TITLE
GGClassic Bug - "Undo" Bug Related to Entity Position

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#5779]
In Game Guru Classic editor, if you raise terrain that has static entities on it, and "undo" with control Z , the terrain will go back to its previous height however the static entity will remain floating and not restore to its original position in the previous state.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Dropped a barrel into an empty level, raised the terrain beneath it:
![image](https://github.com/user-attachments/assets/1d0ad630-55cb-459a-a857-cf0b4ed97cc2)

Then CTRL+Z to UNDO and the barrel returned to the floor along with the reversed terrain raise:
![image](https://github.com/user-attachments/assets/f8a12e86-3ad1-4770-b603-210813508056)

Can you provide steps that shows the UNDO 'not' working in this way, thanks!

**Comment by Teabone3** [comment]
Hi Lee, I've not been able to reproduce this issue since. It can be closed for now.
