### ISSUE TITLE
GGMAX Bug - Surface Texture Import Problems

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5785]
Overview
I encountered an issue with GameGuru Max (GGMax) while trying to add new surface textures to a model. The texture file, while successfully generated and placed in the correct directory, is not being recognized by GGMax’s texture system. Despite the file appearing correctly in the file system, GGMax fails to display or utilize the texture in its asset manager or texture system.

Absolutely! Here’s a write-up of your experience and the steps we've taken, which you can send to the developers of GameGuru Max. I’ll detail the issue, troubleshooting steps, and some suggestions for resolving the problem.

Issue Report: Texture Import Problems in GameGuru Max
Overview
I encountered an issue with GameGuru Max (GGMax) while trying to add new surface textures to a model. The texture file, while successfully generated and placed in the correct directory, is not being recognized by GGMax’s texture system. Despite the file appearing correctly in the file system, GGMax fails to display or utilize the texture in its asset manager or texture system.

System Info:
GGMax Version: [Add your GGMax version here]
Operating System: [Add your operating system here]
Texture Format Used: .dds
Steps Taken:
1. Texture Generation
A Python script was used to generate new surface textures following GGMax’s expected naming convention:

Original Texture Example: MI_ConcreteSmooth_BaseColor.png
Generated Surface Texture: MI_ConcreteSmooth_BaseColor_surface.dds
This process successfully created the surface textures, and they appeared in the correct directory (E:\New folder (3)\importers\Files\entitybank\New folder (3)).

2. GGMax Doesn’t Recognize the Texture
Although the textures are present in the folder, GGMax does not list them in its texture manager or apply them to the model. No errors or warnings are presented in GGMax, but the texture is simply not visible in the interface.

Troubleshooting Steps Tried:
1. Verified .dds Format
Tools used: GIMP, Paint.NET
The .dds texture files were verified to be in proper format and readable in external tools. This confirms that the files themselves are not corrupt.
2. Manual Re-import and Refresh Attempts
Attempted to manually re-import the textures into GGMax.
Attempted to refresh the asset folder and restart GGMax multiple times, but the new textures still did not appear in GGMax's interface.
3. Checked Folder Structure and Placement
Verified that the textures were placed in the correct folder, and the structure matched that of other textures already present and working in the project.
No discrepancies were found in folder placement.
4. Verified Naming Conventions
The naming convention of the textures followed what GGMax seems to expect, i.e., appending _surface.dds to the existing BaseColor texture names.
Despite this, GGMax still didn’t recognize the newly added texture.
5. Restarted GGMax and Reloaded the Project
Restarted GGMax and reloaded the project multiple times to trigger a rescan of the asset directory.
GGMax still did not detect the new texture, even after restarting.
Further Steps Suggested
1. Investigate Asset Import and Caching
It’s possible that GGMax has an internal caching or indexing mechanism that needs to be updated manually to detect new files. Some engines require metadata files or cache resets to recognize new assets.

Suggestion: If GGMax has a mechanism to clear the cache or manually force an asset rescan, providing these tools to users might help fix similar issues.
2. Texture Format Compatibility
While the .dds format is supported by GGMax, there could be specific compression settings or internal expectations that are preventing proper recognition of the file.

Suggestion: Clear documentation on acceptable .dds formats and any compression requirements for GGMax’s texture system would help users avoid this issue.
3. Folder Structure Requirements
Some engines require textures to be placed in specific subfolders (like a textures or materials folder). This isn’t documented in GGMax, but it might be worth investigating whether GGMax has similar folder placement rules.

Suggestion: Clarification from GGMax devs on whether specific folder structures are required for textures to be recognized would be helpful.
4. Automatic Asset Detection
If GGMax relies on manual imports for new assets, it might be beneficial to include a more robust file watcher that can automatically detect when new assets are added to the directory.

Conclusion
Despite successfully generating the expected texture files, GGMax is not detecting or utilizing them, suggesting a possible bug or missing feature in its asset management system. The troubleshooting steps taken have ruled out file corruption or naming issues, and we believe the problem lies within GGMax’s internal handling of new assets.

We would greatly appreciate assistance from the developers to resolve this issue or clarification on any additional steps required for proper asset recognition.

Let me know if you need anything else or any further clarifications for the report. Hopefully, the devs will be able to provide a fix!

**Comment by GraPhiX-Guru** [comment]
Your naming convention is the issue, rename your textures with a single _ i.e
MI_ConcreteSmooth_BaseColor_surface.dds should be MIConcreteSmooth_surface.dds

**Comment by casigus** [comment]
even re-naming them doesn't work.  manually adding them doesn't work. the .fpe doesn't even have the name ggmax has.

**Comment by mav3r1ck198-1** [comment]
Ive seen a couple of other posts with texture issues of late. I've not experienced this myself, but I do know that (a) Max doesn't like capital letters in the suffix ie. BaseColor but prefers basecolor, and (b) looking at the stock assets, _BaseColor isn't the standard suffix for how max reads the albedo of a pbr set. Standard is _color. 

I don't mean to be a pedant, and this sort of this is most likely NOT the issue, but ive just imported a model with the _BaseColor.dds suffix, and it didn't find the pbr set (same folder as model) and the changed the set to _color _normal and _surface, reimported the model and all 3 texture maps were in their respective slots.

**Comment by synchromesh62** [comment]
> Ive seen a couple of other posts with texture issues of late. I've not experienced this myself, but I do know that (a) Max doesn't like capital letters in the suffix ie. BaseColor but prefers basecolor, and (b) looking at the stock assets, _BaseColor isn't the standard suffix for how max reads the albedo of a pbr set. Standard is _color.
> 
> I don't mean to be a pedant, and this sort of this is most likely NOT the issue, but ive just imported a model with the _BaseColor.dds suffix, and it didn't find the pbr set (same folder as model) and the changed the set to _color _normal and _surface, reimported the model and all 3 texture maps were in their respective slots.

Have to agree i have seen this mistake done many times. Its best they are named to what Max expects .. 
Better to rename **mytexture_BaseColor.dds** to **mytexture_color.dds**  
Of course renaming may mean they need to be re-applied on import ( **a normal process** ) but it is the correct names and the correct way to do it especially if these are models from Sketchfab etc where they are named for the engines the creator uses.

**Comment by casigus** [comment]
noted. ill give your suggestions a go!  when you have like 77 textures to rename for diff models it can get abit urghh, but ill figure out a solution for sure. thanks !

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
