### ISSUE TITLE
GGMax Bug - Last Entity Placed In Map Disappears On Save

### ISSUE THREAD

**Issue by lordjulian-rebel** [TheGameCreators/GameGuruRepo#5787]
This happens sometimes. I am placing entities in a building that I created in Building Editor. Set not to move when working inside.

**Comment by Kasseyus** [comment]
@lordjulian-rebel Can you please confirm if you are using the DevTest, Experimental or Standard version of GameGuruMAX.

Also, are you able to reproduce this on a video so I can see directly what is happening, as this will help me to identify what is happening.

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
