### ISSUE TITLE
Editor - Welcome Screen

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#579]
If you go to Get Started in the editor and click Welcome Screen. Then tick to not show the welcome screen again. It will continually reappear with each new Game Guru start up.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Can you send a screenshot of the Welcome screen you see, thanks!

**Comment by synchromesh62** [comment]
Tested .. 
On very first boot you tick the "Welcome Screen" to turn it off next time you load GameGuru.
If you run the "Welcome Screen" from the Getting Started on the menu and ticK to skip your actually re-enabling it on boot … However if you tick to skip once again it removes it.
