### ISSUE TITLE
GGMAX Enhancement - Add particles support for Weapons, ( or Preben Weapon Maker Tool)

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#5794]
Add particles support for hud weapons , this way we can create animated weapon( mostly thanks to Preben Weapon maker) that holds light particles like torches, lighters, candles and so on

![image](https://github.com/user-attachments/assets/3d8a71b9-a939-4ad0-97d5-7b756f176a9f)

![image](https://github.com/user-attachments/assets/9aad3f88-4c4e-47fe-856e-db57e9b6f796)

**Comment by SampeyFS** [comment]
yes good it would be very nice to have them
