### ISSUE TITLE
GGMAX Enhancement - Add value input fields for all slider bars

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#5799]
![image](https://github.com/user-attachments/assets/b7cdcfeb-233a-4143-b398-3ac883eec0fd)

image is for reference only.. this should be added to all sliders in the editor

sometimes it's a pain to set the desired value

a great quality of life addtion should be to add the chance to manually specify a value inside the slider .. i think this can be a great improvement on current situation

**Comment by Necrym59** [comment]
Some have fixed ranges and shouldnt be changed tbh it could lead to more problems

**Comment by plemsoft** [comment]
@JCLEONITA Just hold CTRL while you click the slider , and it will allow you to enter the value :)

**Comment by JCLEONITA** [comment]
Whaaaat ?? really??? i didnt know about thhat and it's not mentione in the documentaiton.. thanks
