### ISSUE TITLE
Standalone crashes while loading 2nd level

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#58]
Title says it all...

I dont know how to fix this. Both levels are  ~ 30mb. Maybe its a memory Issue ?

**Comment by Teabone3** [comment]
Any 2nd level or just with the one game you are working on?

**Comment by Duchenkuke** [comment]
Well I only have this one.. ^^ 

Need to test other levels first..

**Comment by plemsoft** [comment]
The sprites on screen while loading could cause this , 30mb should not be a memory problem, anyway think this should be tested in the next PP release as this could have been fixed.

**Comment by Duchenkuke** [comment]
will do, thanks.


________________________________
Von: Preben Eriksen <notifications@github.com>
Gesendet: Dienstag, 13. Februar 2018 11:45
An: TheGameCreators/GameGuruRepo
Cc: Duchenkuke; Author
Betreff: Re: [TheGameCreators/GameGuruRepo] Standalone crashes while loading 2nd level (#58)


The sprites on screen while loading could cause this , 30mb should not be a memory problem, anyway think this should be tested in the next PP release as this could have been fixed.

**Comment by LeeBamberTGC** [comment]
Fixed a crash relating to adding the level name to the IFUSED field of the WinZone and then saving the file.  After fix, created a two-level game standalone and was able to move from the first to second level with no crash. Will be in next build.
