### ISSUE TITLE
Trees animation speed is veryfast and cannot be changed by animspeed (static trees)

### ISSUE THREAD

**Issue by TaurBen** [TheGameCreators/GameGuruRepo#580]
Hello there!
If you try to change the swinging speed of Animated trees (from the standard set of GG, such as: Spruce 01(Animated), Tree 09 (Animated) Tree 11 (Animated) and all others) then nothing will happen. 
I set animspeed=20 (or even 5) in the fpe file, however the speed of swaying trees remains unchanged.
The same, if you use any third-party animated models of plants (for example, from BSP). 
The fact is that all the animation is played very quickly and it seems like a storm is raging :) 

The "animspeed=XX" parameter starts working if you make the tree as "dynamic" (defaultstatic = 0). 
But in this case, there are serious difficulties arise: overall performance decreases ; collisionmode like 50-59 do not work propertly ; any AI-characters begin to experience problems with traversing these trees. 

At the moment, the only solution is to manually increase the number of animation frames to 1500-2500, by adding multiple copies of each animation frame using 3D software such as FragMotion, but it's a long and strange workaround, of course. 

PS. Checked in Public Preview 2019.07.01 July Update, this issue still exists.

**Comment by LeeBamberTGC** [comment]
Can you attach a small FPM with your tree with the animspeed you want, and we can take a closer look!

**Comment by TaurBen** [comment]
Hello, LeeBamberTGC! Below I have attached a FPM file, and zip archive with five standard models (from "entitybank/Foliage" folder ). 

[111Trees animSpeed _FPM.zip](https://github.com/TheGameCreators/GameGuruRepo/files/3482755/111Trees.animSpeed._FPM.zip)
[111TreesSpeed_entities.zip](https://github.com/TheGameCreators/GameGuruRepo/files/3482756/111TreesSpeed_entities.zip) (zip 12,3 Mb)
Unzip the archive to the root of the main folder Entitybank. After that, it should look like this "entitybank/111TreesSpeed/" 
Inside is a folder with the name "entitybank/111TreesSpeed/Changed trees and plants(set as dinamic plus Animspeed)" in which FPE-files are changed: added animspeed = NN and defaultstatic = 0

It is worth noting that the swing speed also depends on the number of animation frames (apparently).

So, there are trees on the map: Pine 03 (Animated), Spruce 01 (Animated) , Tree 09 (Animated). 
All of these models have 399(400) frames of animation  (as well as almost all other stock "foliage" entities). I also found entities with 199(200) frames of animation - this is Plant 05 (Animated) and Plant 06 (Animated). 

Since they are too small I increased them 10 times (plant05 and plant06) and also added a line "animspeed=nnn" in their .fpe files. Models with 200 frames are sometimes used by third-party artists. 
I cannot include an assets from BSP in this example, so I found stock assets "plant05\06"  and enlarged them for clarity (using Scale=1000 in .fpe)

On the test map, I placed the changed assets on stony sites and the original, unchanged trees and plants - just on the grass.
What is seen in the screenshot below: 
![scrshotAnimSpeedtest](https://user-images.githubusercontent.com/43651115/62720624-97d69900-ba34-11e9-8c93-231349030e7c.png)

As you can see on the map, the acceptable animation speed ranges from 75 to 150, but in general animspeed = about 100 is Okay (provided that animspeed will work correctly also with static entities).

**Comment by TaurBen** [comment]
Given that English is not my native language, I tried to draw everything as best as possible
Considering that English is not my native language, i tried to paint everything as best as possible. :)

**Comment by LeeBamberTGC** [comment]
Thanks for posting this on GitHub with files and suggestions, just what we need :)

**Comment by plemsoft** [comment]
@TaurBen Thanks for reporting this,

This has been fixed and will be in the next update :)

**Comment by TaurBen** [comment]
Great news! With enthusiasm I will wait for the next update. 
Thanks for your work !
