### ISSUE TITLE
GGMAX Enhancement - Lean/Peek System Mechanics

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#5803]
what aboutto  add Lean and Peek ability system  mechanics for player in MAx??

it will be add a lot for fps games and even for horror ones

it's a very common and useful feture to add depth to gameplay

https://youtu.be/9stXjuPYOwc

**Comment by JCLEONITA** [comment]
bump--- this could be doable???

**Comment by Teabone3** [comment]
Do-able for sure

https://www.youtube.com/watch?v=65k5pltXazw

EDIT: At a glance from Discord it seems there is this type of feature added to the core player behavior.

**Comment by Necrym59** [comment]
Its in the core 'Player Peek' behavior
