### ISSUE TITLE
GGMAX  Bug - Trigger Zone Global Affected behaviour

### ISSUE THREAD

**Issue by lordjulian-rebel** [TheGameCreators/GameGuruRepo#5806]
The 'effect' keeps changing from 'Add' to 'Accurate' and can't be changed back.

**Comment by Necrym59** [comment]
In the Ui you mean - its just not refreshed click on another object then click back

**Comment by Kasseyus** [comment]
@lordjulian-rebel Would you please be able to create a small video showing this issue  so I can try to re-create the steps.

**Comment by Necrym59** [comment]
He never seems to answer a request for clarifications

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
