### ISSUE TITLE
Report of GameGuruMax Steam Demo Expired.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5808]
As the title states 
I have had a report of the Max Steam Demo getting an **Expired Prompt**

**Comment by Kasseyus** [comment]
The Demo installs and runs fine for me, on multiple systems, although it is quite old (15/12/2023), it does work.

It could be that the person had it installed on their PC, but doesn't have Steam connected to the internet - triggering Valves 'need to connect every now and then' thing.  I'm can't be sure without any further specifics on the issue.
