### ISSUE TITLE
Sniper behavior no longer working

### ISSUE THREAD

**Issue by PalmTree11** [TheGameCreators/GameGuruRepo#5809]
Placed the sniper behavior on a character, made the appropriate adjustments to settings, etc. and the sniper no longer shoots at the player. He turns to face the player but that's it.

**Comment by Necrym59** [comment]
I think this is related to with this problem
https://github.com/TheGameCreators/GameGuruRepo/issues/5753
entities dont seem to be active if more than a certain distance from the player even if set to always active.
The problem has only appeared in the last few updates and is now becoming a hindrance to game logic unless addressed.

**Comment by plemsoft** [comment]
@PalmTree11 Necrym59 has fixed this and it should be updated shortly.

**Comment by Necrym59** [comment]
Updated to workshop

**Comment by PalmTree11** [comment]
I updated workshop, validated the files, relaunched Game Guru Max, and restarted my computer but unfortunately it still isn't working.

**Comment by PalmTree11** [comment]
Tried it again tonight and it is working!
