### ISSUE TITLE
Terrain sculpting tool....seems you cant resize it now.....stays one size only....

### ISSUE THREAD

**Issue by UNIRD12B** [TheGameCreators/GameGuruRepo#581]
Is there a new way to change the size of the terrain sculpting tool , as , both
- and + , no longer seem to function now.

Unird12b

**Comment by synchromesh62** [comment]
Working fine for me ?

**Comment by UNIRD12B** [comment]
You're right, 
  They work for me...just super slow compared to before.

Thx
