### ISSUE TITLE
GGMAX Bug - building editor broken

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5819]
i created a level with corridors with the building editor, saved it, reloaded ggmax building editor, nothing exist, no files saved....

**Comment by imothep85** [comment]
i cant watch your video

**Comment by Kasseyus** [comment]
Apologies.  Looks like I commented before the upload had completed.

Uploading BE LEVEL A - 480.mp4…

**Comment by Kasseyus** [comment]
Please ensure that when you save your BE creation, you also Export it.  Also please note that spaces in the filenames are not preserved, so for example, "BUILD SILO A" would become "BUILDSILOA".

Please see the video linked above for a practical demonstration, and if the problem still exists, please let me know by replying to this ticket and I will investigate further.  Providing a video if the steps you are taking will also be useful in helping me diagnose the issue.
