### ISSUE TITLE
Story zone - video lag - July update

### ISSUE THREAD

**Issue by czjohns** [TheGameCreators/GameGuruRepo#582]
Since the latest update, my video (or even default video thats shipped with GG) stutters and lags. When I switched to public-release-2019.03, the issue was fixed.

**Comment by synchromesh62** [comment]
Tested and can confirm a definite lag .. Pretty unwatchable to be honest.

**Comment by plemsoft** [comment]
@czjohns @synchromesh62 
Ups:
Edit setup.ini and set "videoprecacheframes=8" and give it a try.

It should have been set at 8 by default but somehow ... , sorry about that.

BTW: the old system used 18 precache frames but that should not be needed.

Let me know if this fix your issue , thanks :)

**Comment by czjohns** [comment]
Yes that fixed it!

**Comment by synchromesh62** [comment]
Yep sorted for me as well thanks Preben :)
