### ISSUE TITLE
GGMAX Enhancement - Classic Explosive script doesnt' work when an object with the "switch" behaviour is in the level

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#5820]
I 'm testing Grahpix explosive barrels/ script and noticed that the barrels explosion and debris works fine until i add  an object ( can be everything) with the switch behavior applied to it in the level 

if that object is present in the level the explosive barrels became bugged..
if i remove the obejct from level and restart the level  the bug remains until i close and open max again and relaunch the level ( without the switch stuff )

without switch in level
https://streamable.com/tcamjz

with switch in level
https://streamable.com/qk9370

`-- LUA Script - GraPhiX Explosion Script - Thank you to AmenMoses for the scripts he creates without them this would not have been possible.
-- DESCRIPTION: My Custom LUA Script
-- DESCRIPTION: graphix_explosion

local nonDebrisName = "exp1" -- reserve exp1 just for non-debris entities such as GG standard barrels. all they should name as exp1
-- and being treated as your original script stated. The debris ones should be treated a bit different since they are animated; we don't want them disappearing suddenly,as example. In fact we don't want them being hidden or destroyed, we want they generating debris, and these debris following the physisc and gravity laws while fallen to the ground.

local U  = require "scriptbank\\utillib"
local P  = require "scriptbank\\physlib"
local min = math.min
local emitterList    = {}
local explosion_name = {}

-- blastRadius set this to the distance you want explosions to be felt default is 300 units
local blastRadius    = 300
local maxDamage      = 150
local maxPlayerPush  = 10
local maxEntityPush  = 200

-- triggerHealth this setting adds to the entity strength.
-- the default setting in entities properties panel is 25 which equates to 1 shot changing to 50 2 shots etc..
local triggerHealth  = 1000

-- Emitter list the emitters control position and scale of each particle the emiiter name 
-- i.e boom1, boom2 is assinged in your image_List.
local namedEmitter = 
{  
    boom1 = 
          { animSpd = 1/2, SR = 0, freq = 64, lifeMin = 2000, lifeMax = 2000,
                     -- minX  minY  minZ  maxX  maxY  maxZ        
            offset = {    0,    50,    0,    0,   80,    0 },
            speed  = {    0,    0,    0,    0,    0,     0 },
            rotate = {                0,                0 }, -- currently only Z rotate processed
                     -- startMin startMax endMin endMax 
            scale  = {   200,     300,    100,   200 },
            alpha  = {   100,     255,   0,    0}
          },
    boom2 = 
          { animSpd = 1/2, SR = 0, freq = 64, lifeMin = 2000, lifeMax = 2000,
                     -- minX  minY  minZ  maxX  maxY  maxZ        
            offset = {    0,    50,    0,    0,   80,    0 },
            speed  = {    0,    0,    0,    0,    0,     0 },
            rotate = {                0,                0 }, -- currently only Z rotate processed
                     -- startMin startMax endMin endMax 
            scale  = {   300,     400,    100,   300 },
            alpha  = {   100,     200,   0,    0}
          },
    boom3 = 
          { animSpd = 1/2, SR = 0, freq = 64, lifeMin = 2000, lifeMax = 2000,
                     -- minX  minY  minZ  maxX  maxY  maxZ        
            offset = {    0,    90,    0,    0,   90,    0 },
            speed  = {    0,    0,    0,    0,    0,     0 },
            rotate = {                0,                0 }, -- currently only Z rotate processed
                     -- startMin startMax endMin endMax 
            scale  = {   200,     300,    200,   300 },
            alpha  = {   100,     200,   0,    50}
          },
    boom4 = 
          { animSpd = 1/2, SR = 0, freq = 64, lifeMin = 2000, lifeMax = 2000,
                     -- minX  minY  minZ  maxX  maxY  maxZ        
            offset = {    0,   20,    0,    0,   20,    0 },
            speed  = {    0,    0,    0,    0,    0,   0 },
            rotate = {                0,               0 }, -- currently only Z rotate processed
                     -- startMin startMax endMin endMax 
            scale  = {   200,     300,    100,   200 },
            alpha  = {   100,     200,   0,    0}
          },
    boom5 = 
          { animSpd = 1/2, SR = 0, freq = 64, lifeMin = 2000, lifeMax = 2000,
                     -- minX  minY  minZ  maxX  maxY  maxZ        
            offset = {    0,    0,    0,    0,    0,   0 },
            speed  = {    0,    0,    0,    0,    0,   0 },
            rotate = {                0,               0 }, -- currently only Z rotate processed
                     -- startMin startMax endMin endMax 
            scale  = {      0,       0,      0,     0 },
            alpha  = {      0,       0,      0,     0 }
          }
}

-- image_List this is the list of your decals/particle sheets keep the name the same has your image file name i.e. exp1 = exp1.dds
-- also the full path is required i.e. "effectbank\\explosion\\graphix\\exp1.dds"
-- emitName = the particle parametes set above 
-- imgFrames = the number of frames in your sprite sheets
-- imageNum must be a unique value some are reserved so just use 10 - 20
-- imploder is a boolean value false for a standard explosion if you have designed a implosion sprite sheet set it to true
-- PLEASE NOTE THIS VALUE DOES NOT CONVERT AN EXPLOSION TO AN IMPLOSION USE A SPRITE SHEET FOR THAT
local image_List = 
{   
    exp1 = { path     = "effectbank\\explosion\\graphix\\exp1.dds",
             emitName = 'boom1',
             imgFrames = 64,
             imageNum = 10,
             imploder = false },
    exp2 = { path = "effectbank\\explosion\\graphix\\exp2.dds", 
             emitName = 'boom3',
             imgFrames = 64,
             imageNum = 11,
             imploder = false },
    exp3 = { path = "effectbank\\explosion\\graphix\\exp3.dds",
             emitName = 'boom1',
             imgFrames = 64,
             imageNum = 12,
             imploder = false },
    exp4 = { path = "effectbank\\explosion\\graphix\\exp4.dds",
             emitName = 'boom1',
             imgFrames = 64,             
             imageNum = 13,
             imploder = false },
    exp5 = { path     = "effectbank\\explosion\\graphix\\exp5.dds",
             emitName = 'boom1',
             imgFrames = 64,
             imageNum = 14,
             imploder = false },
    exp6 = { path     = "effectbank\\explosion\\graphix\\exp6.dds",
             emitName = 'boom3',
             imgFrames = 64,
             imageNum = 15,
             imploder = false },
    exp7 = { path     = "effectbank\\explosion\\graphix\\exp7.dds",
             emitName = 'boom1',
             imgFrames = 64,
             imageNum = 16,
             imploder = false },
    exp8 = { path     = "effectbank\\explosion\\graphix\\exp8.dds",
             emitName = 'boom1',
             imgFrames = 64,
             imageNum = 17,
             imploder = false },
    exp9 = { path     = "effectbank\\explosion\\graphix\\exp9.dds",
             emitName = 'boom4',
             imgFrames = 64,
             imageNum = 18,
             imploder = false },
    exp10 = { path     = "effectbank\\explosion\\graphix\\exp10.dds",
             emitName = 'boom1',
             imgFrames = 64,
             imageNum = 19,
             imploder = false },
    exp11 = { path     = "effectbank\\explosion\\graphix\\exp11.dds",
             emitName = 'boom4',
             imgFrames = 64,
             imageNum = 20,
             imploder = false },
    imp1 = { path     = "effectbank\\explosion\\graphix\\imp1.dds",
             emitName = 'boom3',
             imgFrames = 64,
             imageNum = 21,
             imploder = true },
    imp2 = { path     = "effectbank\\explosion\\graphix\\imp2.dds",
             emitName = 'boom4',
             imgFrames = 64,
             imageNum = 22,
             imploder = true },
    imp3 = { path     = "effectbank\\explosion\\graphix\\imp3.dds",
             emitName = 'boom4',
             imgFrames = 64,
             imageNum = 23,
             imploder = true },
    imp4 = { path     = "effectbank\\explosion\\graphix\\imp4.dds",
             emitName = 'boom4',
             imgFrames = 64,
             imageNum = 24,
             imploder = true }
}

-- Unless you know what you are doing please do not alter any of the below script.
-- caller must load image. some clever stuff Amenmoses made
local function PE_CreateNamedEmitter( name, image, frames, entity )
            
    local et = namedEmitter[ name ]
    
    if et == nil then return end
    
    local emitter = ParticlesGetFreeEmitter()
    
    if emitter == -1 then return end
    
    local pos, spd, scl = et.offset, et.speed, et.scale
    -- this bit makes a cup of tea
    if entity == nil then
        ParticlesAddEmitterEx( emitter, et.animSpd, et.SR, 
                             pos[1], pos[2], pos[3], pos[4], pos[5], pos[6],
                             scl[1], scl[2], scl[3], scl[4],
                             spd[1], spd[2], spd[3], spd[4], spd[5], spd[6],
                             et.rotate[1], et.rotate[2], et.lifeMin, et.lifeMax,
                             et.alpha[1], et.alpha[2], et.alpha[3], et.alpha[4],
                             et.freq, -1, 0, image, frames )
    else
    -- this bit makes coffee
        ParticlesAddEmitterEx( emitter, et.animSpd, et.SR, 
                             pos[1], pos[2], pos[3], pos[4], pos[5], pos[6],
                             scl[1], scl[2], scl[3], scl[4],
                             spd[1], spd[2], spd[3], spd[4], spd[5], spd[6],
                             et.rotate[1], et.rotate[2], et.lifeMin, et.lifeMax,
                             et.alpha[1], et.alpha[2], et.alpha[3], et.alpha[4],
                             et.freq, entity, 0, image, frames ) 
    end
    
    return emitter
end

                                
function graphix_explosion_init_name(e, name)
    Include( "utillib.lua" )
    Include( "physlib.lua" )    
    explosion_name[e] = string.match(name,"_(%w+)")
    SetEntityHealth( e, g_Entity[e].health + triggerHealth )
end

local rnd = math.random

local function processExplosion( e, ex, ey, ez, imploder )
    
    -- get entity position
    local Ent = g_Entity[e]
    
    -- calculate distance from centre of explosion
    local dx, dy, dz = Ent.x - ex, Ent.y - ey, Ent.z - ez
    local dist = math.sqrt( dx^2 + dz^2 )

    -- calculate modifier based on distance
    local distMod = 1 - ( dist / blastRadius )
    
    -- handle physics push/pull
    local dims = P.GetObjectDimensions( Ent.obj )
    local force = min( maxEntityPush, dims.m * maxEntityPush * 100 * ( 100 / GetEntityWeight( e ) ) ) * distMod
    local vx, vy, vz = dx / dist, dy / dist, dz / dist
    -- suck it in 
    if imploder then 
        vx, vy, vz = -vx, 0, -vz
    end
    
    if ai_bot_state[ e ] == nil and explosion_name[e] == nonDebrisName then
        -- shove it out the way
        PushObject( Ent.obj, vx * force, vy * force , vz * force, rnd(), rnd(), rnd() )
        --PlayAnimation(e,0)
    end
    
    -- inflict damage on entity
    if explosion_name[e] ~= nil then
        -- trigger chain reaction with like minded entities
        SetEntityHealth( e, triggerHealth )
        PlayAnimation(e,0)  
    elseif
       ai_bot_state[ e ] ~= nil then
        -- remove health from NPCs based on how close to explosion
        local newHealth = Ent.health - math.modf( maxDamage * distMod )
        if newHealth > 0 then
            if HurtEntity ~= nil then
                HurtEntity( e, newHealth, 200, Ent.x - ex, Ent.y - ey, Ent.z - ez, vx * force, vy * force , vz * force )
            else
                SetEntityHealth( e, newHealth )
            end
        else
            if KillEntity ~= nil and explosion_name[e] == nonDebrisName then
                KillEntity( e, 200, vx * force, vy * force , vz * force )
            else
                SetEntityHealth( e, 100 )
            end
        end
    end
    
end

function graphix_explosion_main(e)

    -- if no sprite sheet do nothing
    if explosion_name[e] == nil then return end
    
    local Ent = g_Entity[e]
    if Ent.health > triggerHealth then return end
    
    -- put all those lovely images to use
    local emitter = emitterList[e]

    if emitter == nil then
        emitterList[e] = { used      = false,
                           boomImg   = ParticlesLoadImage( image_List[ explosion_name[e] ].path, 
                                                          image_List[ explosion_name[e] ].imageNum ),
                           emitNam   = image_List[ explosion_name[e] ].emitName,
                           imploder  = image_List[ explosion_name[e] ].imploder,
                           imgFrames = image_List[ explosion_name[e] ].imgFrames
                         }
        return
    end
    
    -- only use an emiiter if need to
    if not emitter.used then                        
        emitter.blowup = PE_CreateNamedEmitter( emitter.emitNam, emitter.boomImg, emitter.imgFrames, e)                             
        emitter.used = true
        ParticlesSetLife( emitter.blowup, 10, 2000, 2000, 0 , 0 )
        return
    end
        
    if emitter.timer == nil then
        ParticlesSetLife( emitter.blowup, 10, 2000, 2000, 1, 0 )
        emitter.timer = g_Time + 100
        
        -- 1.5 second delay to allow particle to fire
        StartTimer( e )
        -- play the sound assigned to sound0 in entity properties
        PlaySound( e, 0 )
        -- hide entity while we work out whats around it within range of blast

    ---------------------------------------------------------- modify by me 
        if explosion_name[e] == nonDebrisName then -- if GG standar barrels then
            Hide( e ) 
        else
            PlayAnimation(e,0)          
        end
    ----------------------------------------------------------------------  
            
        for _, v in pairs( U.ClosestEntities( blastRadius, 100, Ent.x, Ent.z) ) do
            if v ~= e then
                processExplosion( v, Ent.x, Ent.y, Ent.z, emitter.imploder )
            end
        end 
        
    elseif 
    
        -- run emitter effect
       g_Time > emitter.timer then
        ParticlesSetLife( emitter.blowup, 10, 2000, 2000, 0 , 0 )
        emitter.timer = math.huge
        -- assign damage to player if in range of blast 
        if U.PlayerCloserThanPos( Ent.x, Ent.y, Ent.z, blastRadius ) then
            --AmenMoses funky math stuff i wont pretend to know what it is
            local dx, dz = g_PlayerPosX - Ent.x, g_PlayerPosZ - Ent.z
            local angle = math.deg( math.atan2( dx, dz ) )
            local dist = math.sqrt( dx^2 + dz^2 )
            
            local distMod = 1 - ( dist / blastRadius )

            local damage = maxDamage
            -- if not an explosion limit damage to player       
            if emitter.imploder then 
                angle = WrapAngle( -angle )
                damage = damage / 2
            end
            
            -- push the player away 
            ForcePlayer( angle, maxPlayerPush * distMod )
            -- damage to player based on how close to explosion     
            damage = math.modf( damage * distMod )
            if damage > g_PlayerHealth then damage = g_PlayerHealth end
            -- SetPlayerHealth( g_PlayerHealth - damage )
            HurtPlayer(e,damage)
        end
                
    else
        -- delete the emitter then destroy the entity
        if GetTimer( e ) > 1500 and GetAnimationFrame(e) == GetEntityAnimationFinish ( e, 0 ) then -- forcing engine to wait to the last anim frame before exit.
            --StopAnimation(e,0)
            ParticlesDeleteEmitter( emitter.blowup )
            -- Destroy( e )

--------------------------------------------------------------- mod by me           
        if explosion_name[e] == nonDebrisName then -- if standard ones
            Destroy( e ) 
        else
            PlayAnimation(e,0)
            CollisionOn(e)          
        end 
---------------------------------------------------------------------------
        
        end
        
        if GetTimer( e ) > 4500 and GetAnimationFrame(e) == GetEntityAnimationFinish ( e, 0 ) then Destroy( e ) end
        
    end
end

function graphix_explosion_exit(e)
end
`

**Comment by JCLEONITA** [comment]
i dont know why the scirpt is posted this way on github, i seleccted the code tab..

**Comment by Necrym59** [comment]
Why are you using stuff from Classic in Max it doesnt always work as the systems are different

**Comment by AmenMoses** [comment]
The problem here is not the scripts themselves but the fact that animation in MAX is different from Classic.
I imported a single breakable barrel from Classic and in the animation pane thingy I renamed 'All' to 'Explode', then changed the animation part in the script from:
PlayAnimation(e,0)
to:
SetAnimationName(e,"Explode")
PlayAnimation(e)

This semi fixed the problem but for some reason the importer seemed to cut off the animation a few frames early.
Anyhow if you want the breakables from Classic to work properly in MAX that is what you would have to do (in addition to copying over the particle sheets from classic for the explosions of course).

As to why they appeared to work until a switch was placed on the level I have no idea, something to do with the switch being an animated entity using the new system which uses the new commands maybe makes the engine turn off support for the old animation system or some such shenanigans. 

Btw the old explosion script could really do with a rewrite before being used in MAX, for example selection of the explosion effect being picked from dynamic Lua doodad rather than by entity name would be a good start. (or even changing it to use the new particles system if someone wants to try and replicate all GraPhiX effects in it).

**Comment by JCLEONITA** [comment]
thanks Amen ( and Necrym too obviosuly too) for your reply

and i second this
"
Btw the old explosion script could really do with a rewrite before being used in MAX, for example selection of the explosion effect being picked from dynamic Lua doodad rather than by entity name would be a good start. (or even changing it to use the new particles system if someone wants to try and replicate all GraPhiX effects in it)."

btw since new particles are in the work maybe we just need t owait .. hopefully not too much

**Comment by AmenMoses** [comment]
Well it depends on what you mean by "new particles", Preben is working on getting Wicked particles available in MAX, if this effort also gives the same sort of Lua control as the "old" GGC particles then I am all for it as it gives the best of both worlds, i.e. the power and flexibility of the legacy system with the performance of GPU particles, but if you mean the existing MAX fake particles with a bit more Lua control then that all depends on how that pans out.

There is nothing wrong with the legacy particles btw, there are still many situations where they are the only option (see my posts on Discord for example) currently.  I think the only real downside of the legacy system is that they may not work well in VR but that doesn't seem to be much of a priority anymore anyhow.

**Comment by AmenMoses** [comment]
https://vimeo.com/1029818920

That's what the exploding barrel form GGC looks like in MAX with the edits I mentioned earlier btw.

**Comment by JCLEONITA** [comment]
> Particles problem has just been fixed, next update you can select an explosion particle in the break object behavior which should solve your problem

thanks this should be great too..

**Comment by AmenMoses** [comment]
> > https://vimeo.com/1029818920
> > That's what the exploding barrel from GGC looks like in MAX with the edits I mentioned earlier btw.
> 
> great.. do you think you can share the modified script ??
[graphix_explosion.zip](https://github.com/user-attachments/files/17791015/graphix_explosion.zip)

**Comment by JCLEONITA** [comment]
> > > https://vimeo.com/1029818920
> > > That's what the exploding barrel from GGC looks like in MAX with the edits I mentioned earlier btw.
> > 
> > 
> > great.. do you think you can share the modified script ??
> 
> [graphix_explosion.zip](https://github.com/user-attachments/files/17791015/graphix_explosion.zip)
> 
> https://vimeo.com/1030478564

many thanks... great .i  ll test asap

**Comment by JCLEONITA** [comment]
tried but when i place the barrels(breakable) and use your scirpt i shot the barrel but nothing happen.. do i need to set the barrel is some particual way?

**Comment by JCLEONITA** [comment]
yes i have this message

![image](https://github.com/user-attachments/assets/a9a2c3ad-a501-48b3-9c72-894807d67324)

**Comment by AmenMoses** [comment]
Go into the dynamic Lua and specify a particle sheet to use!

It should default to "exp1" but you can use any of the names of the sheets that GraPhiX provided.
