### ISSUE TITLE
GGMAX Enhancement - Add possibility to choose explosion effect or particle explosion effect to break object behaviour

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#5821]
because i noticed that behavior can only play explosion/break animation but if we check the can explode flag only the explosion is played and to the animation

 it should be great to have both

![image](https://github.com/user-attachments/assets/c4c69793-a074-4dfd-8f92-3fdc41083cc4)

**Comment by Necrym59** [comment]
Done just waiting for the next update with a particle problem being fixed

**Comment by LeeBamberTGC** [comment]
@JCLEONITA Will be in the next DEVTEST build :)  Many thanks to Preben The Fixer!

**Comment by JCLEONITA** [comment]
cool thanks to all of us

**Comment by Necrym59** [comment]
Is now working

**Comment by JCLEONITA** [comment]
> Is now working

cool... in devtest or in stable?

**Comment by Necrym59** [comment]
In the DevTest version at present - Just put in the particle name no path names - it works

**Comment by JCLEONITA** [comment]
ah.. o ki'm on stable actually

 which is the password for the devtest build?

**Comment by LeeBamberTGC** [comment]
lettesterin42

**Comment by JCLEONITA** [comment]
i downloaded the  lastest  devtest build and the script dont have the filed related to particles..

yesterday on stable one it had
![image](https://github.com/user-attachments/assets/fb58cd62-96ad-439d-85ef-06426387ad8d)

**Comment by Necrym59** [comment]
Update your workshop and use that version
