### ISSUE TITLE
GG? Bug - Choppy Audio

### ISSUE THREAD

**Issue by lordjulian-rebel** [TheGameCreators/GameGuruRepo#5823]
Audio playing via objects, zones, etc. is often choppy and sometimes doesn't play at all.

**Comment by Necrym59** [comment]
Cannot replicate. Have you tried using either the stock behavior or the workshop versions (which are updated more frequently).

**Comment by synchromesh62** [comment]
Nothing i can replicate or notice either.
I have audio conversations and all sorts on my levels without any problems

**Comment by Kasseyus** [comment]
@lordjulian-rebel 

1> Is this bug for GameGuruMAX or GameGuru Classic
2> Can you please provide a video clip of the issue happening to better gauge what might be causing the problem, including steps leading up to the issue.
3> Does this issue happen every time, or only sometimes?

**Comment by Kasseyus** [comment]
As this ticket has received no updates recently, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
