### ISSUE TITLE
Highlight: Outline

### ISSUE THREAD

**Issue by lordjulian-rebel** [TheGameCreators/GameGuruRepo#5824]
Very often, using the 'Collect Object', behavior, selecting Highlight > Outline makes no difference. The outline does not show.

**Comment by Necrym59** [comment]
Collect object and other behaviours with Highlighting are working and cannot replicate your problem. You will have to be more descriptive as to your useage and supply what version of Max you are using.

**Comment by Kasseyus** [comment]
As this ticket has received no updates recently, I will temporarily mark the issue as closed. Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
