### ISSUE TITLE
GGMAX Bug - DEVTEST - Memory Collection Issue

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5826]
MAX Editor no like to dump memory he rather collects more as he goes.
This level on a fresh run, clocks in at around 7.5 gig ( would be 3.5ish if the invisible terrain wasn't hogging around 4 gig), 
anyhow after stopping starting the editor for an hour or so testing a script he collects ram like honeybee collects nectar.

![memoryhog](https://github.com/user-attachments/assets/abddb481-fa70-458c-9b2c-55583e332318)

From other observations the editor adds around 2 gig or so on every successive test run.

Not tested to see if it does the same in Standalone.

Thanks for checking :)

**Comment by Kitakazi** [comment]
I have noticed this as well on the current EXP VERSION.

**Comment by OldFlak** [comment]
I have sent a level to Preben so he try to pinpoint what is causing it. (Probably something I am causing lol)
Will report back when he has had time to check it out.

**Comment by OldFlak** [comment]
Preben has found and fixed the memory leak when we get the fix is rolled out, I will confirm and close this thread :)

**Comment by Kasseyus** [comment]
@OldFlak This should now be fixed in the latest DevTest build.

**Comment by OldFlak** [comment]
hi @Kasseyus - Yes sorted :)

Thank you
