### ISSUE TITLE
GG MAX possible script problem

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5830]
![Desktop Screenshot 2024 11 18 - 13 39 11 46](https://github.com/user-attachments/assets/c14ca948-0817-4ee2-8065-93bc0f368181)

Using the deployable transport function v3 in some areas without mounting the tent it is written to sleep as you see in the image

**Comment by Necrym59** [comment]
Not able to duplicate supply a video if possible

**Comment by SampeyFS** [comment]
https://www.youtube.com/watch?v=2k_iyA6zOSI

**Comment by Necrym59** [comment]
Nothing wrong with the sleep behavior - 
have attached a replacement deploy behavior to test 
[deployable_named_v4.zip](https://github.com/user-attachments/files/17851839/deployable_named_v4.zip)

**Comment by SampeyFS** [comment]
now it seems to work with this script

**Comment by Necrym59** [comment]
Good
