### ISSUE TITLE
GGMAX Enhancement - Add option to hide object in game and in editor

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#5832]
like the title says. it should be really useful to can add the possibity to hide the mesh of an object ingame ( and  in the edtior too, if possible ) , so this ways we can have all stuffs of the object ative  and the mesh hidden..

for example if we have a big model with an unique mesh that incorrporate a ladder too, we cant apply the ladder behavior to the entire mesh (e.g. a watchtower)  but we can put a ladder object with a ladder behavior  in front of the ladder from the mesh , hide  the ladder mesh and use its behavior to have a working ladder on the mode with the integrate ladderl.. this is only a generic use case example..

 we already have the possiblity to siwtch off the mesh visibility with the clipping options of the model but this way  when we want to reselect again the hidden/clipped model it's a pain to casually click to try to finf it again.. with a simple check 

![image](https://github.com/user-attachments/assets/c2b136d1-d5e0-4049-8f6b-5b113480d944)

![image](https://github.com/user-attachments/assets/62ca7b7b-1236-4985-a070-0213c41910be)

![image](https://github.com/user-attachments/assets/b0506b6b-904d-433e-99d2-dec47d114cef)

**Comment by synchromesh62** [comment]
This was already answered on Discord for you.
Use the climber behaviour its made so you can hide the asset ingame but still see it in the editor.

**Comment by JCLEONITA** [comment]
ah.. thanks .. i didnt see the answer on discord about climber behavior .. good to know thanks
