### ISSUE TITLE
GGClassic Bug - runtime error 312

### ISSUE THREAD

**Issue by ArmedAndHammered3** [TheGameCreators/GameGuruRepo#5834]
Sprite size is too large on a factory install with nothing added or downloaded yet?
Have done 6 clean installs in a row and nothing added nor downloaded, all stock.
Keep getting runtime error 312 on every single Beta and normal version

Googled it and this is what i found.
RUNTIMEERROR_SPRITESIZEILLEGAL 312

All stock install I also cleared Steam download cache and same issue.
It keeps trying to access The Big Escape map at startup...fails and continues this way in a loop continually.
Verified files at least 10 times on 3 different versions, same result.
I rewrote windows to make sure this was an error with the app and every application i can find runs perfectly except this one.

Can you take a look please, Thank You.

**Comment by ArmedAndHammered3** [comment]
![GameGuru Classic 11_27_2024 10_47_56 PM](https://github.com/user-attachments/assets/14ac097a-a0be-4c19-8887-ee26a557ff35)

**Comment by ArmedAndHammered3** [comment]
Mysteriously went away for no apparent reason after reinstalling and verifying over 32 times. Whatever it was i wish i knew so i could share it with everyone.

**Comment by Kasseyus** [comment]
Sounds like this one was quite obscure, and would be problematic to resolve without being able to test while it is happening.  I will close this ticket for now, but please respond and I will re-open and investigate if it starts to happen again.
