### ISSUE TITLE
GGMax Bug - Zombie and Allied NPC Behaviour Not Acting As Intended

### ISSUE THREAD

**Issue by raffix99** [TheGameCreators/GameGuruRepo#5844]
hello, Just a post to signal than allied Npc most of the time don't attack zombies (from the main pack) or critters (from dlc) , also the "Dash" and "Hunchback" zombie attack are broken, thanx :)

**Comment by Kasseyus** [comment]
@raffix99 When you mention that the zombie attacks are broken - can you go into a little more detail, such as what are they doing compared to what they should be doing.  Also, if you can include a video reference of the bug in action, which may assist in diagnosing the issue.

**Comment by Kasseyus** [comment]
There is another issue that exists that seems to be the same bug - so I will close this ticket in order to maintain a more efficient system.  Please use https://github.com/TheGameCreators/GameGuruRepo/issues/5825 for any further comments in relation to this issie.

**Comment by raffix99** [comment]
Hello , here a video test I made, it seems than (with more new test) than
allied attack the zombies who are feeding , also I add critters with no
reaction, I made a new empty map, the allied npc attack some sort of
critters but not the others , best regards, Raphael

https://www.youtube.com/watch?v=V7I9Zm0zOaM
