### ISSUE TITLE
GGMax Bug - EXP - Weapon impact effects aren't showing up

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5846]
After the latest EXP update gunshots are not producing impact decals/particles. Tested Wood, Metal, Stone they dont show any impact effect at all.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for next DEVTEXT build.

**Comment by LeeBamberTGC** [comment]
@Kasseyus Ready!

**Comment by Kasseyus** [comment]
Confirmed.  Bullet impacts are now once again visible.

**Comment by Kitakazi** [comment]
Was this fix ever sent to the EXP version? I think there was an update since I posted this issue but I'm not 100% sure. In the current EXP bullet impacts are not visible and the issue is still there.

**Comment by LeeBamberTGC** [comment]
Just tested the latest DEVTEST and weapon bullet hits are working :)

![Image](https://github.com/user-attachments/assets/58ecfc0d-6c5d-44f9-a2bc-5061f6c67cc0)
