### ISSUE TITLE
GGMax Bug - Nov update 2024 breaks mouse actions

### ISSUE THREAD

**Issue by CRGSOS** [TheGameCreators/GameGuruRepo#5855]
Gameguru Max Nov 2024 update has lost my mouse so when game launched player cannot turn or look around. Any thoughts? OK before update. Rebooting pc does not help.

**Comment by Kasseyus** [comment]
Are you running a beta branch (DevTest/Experimental) or the Retail Build?

Also, does this mouse issue occur after using the arrow keys to move the player, or does it happen after using the WASD keys?

**Comment by Kasseyus** [comment]
It may be advisable to revert your copy of MAX to the last good public build until this is fixed.  You can access this here:
![image](https://github.com/user-attachments/assets/85f13392-78f1-4511-96d6-5c814debb321)

The connection with the arrow keys confirms to me that this is a known bug that is waiting to be fixed.
Original Ticket: https://github.com/TheGameCreators/GameGuruRepo/issues/5749

**Comment by Kasseyus** [comment]
I will close out this ticket in favour of the existing one, but as soon as this issue is fixed, I will update this ticket also.

**Comment by CRGSOS** [comment]
Dear Kasseyus
Thank you for the update and advice. It seems a rather serious issue! Incidentally using a separate non-arrow key after mouse freezes seems to release it temporarily.
Best wishes
Roger Grant

Sent from Mail for Windows 10
