### ISSUE TITLE
(GGMax) Sniper AI not firing

### ISSUE THREAD

**Issue by v9130** [TheGameCreators/GameGuruRepo#5858]
Sniper behavior NPC does not fire at the player.

Issue noticed on 10.12.2024 and verified again on 13.12.2024 Retail branch.

Repro:
-place an NPC with a sniper behavior
-set it's view range to 4000
-set it's engagement range to 4000
-play

Tested also side by side with regular combat behavior NPCs with same range settings and weapon (Assault Rifle) and these NPCs engage the player at these ranges while Sniper NPC doesn't engage at any range, just aim and track player movement.

**Comment by Necrym59** [comment]
Set the character to Always Active ON , and set its view range to the distance required (eg: 4000) in the Character settings

**Comment by v9130** [comment]
It's always active and view range is same.
Character Attack next to it with all same settings and weapon works as intended.

![ggm_1](https://github.com/user-attachments/assets/eadf2e17-c9b5-4be3-9d6a-a741141c9ebc)
![ggm_2](https://github.com/user-attachments/assets/87f48c05-eaec-4e4b-86d7-586a844ade56)
![ggm_3](https://github.com/user-attachments/assets/a4c34bb1-56c2-435f-ba7f-a92f86ad2758)

**Comment by Necrym59** [comment]
I think perhaps the sniper behavior hasnt been updated in the retail branch, you can try this version it definately works
[sniper_v8.zip](https://github.com/user-attachments/files/18137257/sniper_v8.zip)

**Comment by v9130** [comment]
> I think perhaps the sniper behavior hasnt been updated in the retail branch, you can try this version it definately works [sniper_v8.zip](https://github.com/user-attachments/files/18137257/sniper_v8.zip)

That works. Thanks!
