### ISSUE TITLE
GGMax Bug - max continously crashes on ADD obejct selection

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#5866]
max continue to crash everytime i go to asset folder to search for something.. i didnt added anything to max , tried steam files check, created a new project and new level but max crash always  when i click the ADD button..
i have a lot of custom  stuffs i added some time ago but until  yesterday all worked great ( i always tested everything i added over time when i added it)
but from yesterday evenining max  crash everytime i click  the ADD button in any level and in any proejct
what is goingo on?

https://streamable.com/wqf6yn

**Comment by JCLEONITA** [comment]
i cant use max anymore

**Comment by JCLEONITA** [comment]
i removed even all my custom media  but the problem happen the same

**Comment by Necrym59** [comment]
Fixed
