### ISSUE TITLE
3rd person Melee

### ISSUE THREAD

**Issue by SOLODESIGN** [TheGameCreators/GameGuruRepo#587]
The 3rd person Melee animation is not working properly when you select a Melee fantasy character and press the mouse button to attack in 3rd perspective. I am using the latest update patch and tried to use stock characters and use a character (Knight) from the character creator in GameGuru but they all do not work, they animate with all other movement just not the attack Melee animation.

**Comment by Belidos3D** [comment]
I've  had a look into this, the characters that are effected are the Fantasy DLC, and characers created using parts from the Fantasy DLC, looking at their FPE files the animation sets listed are a mess and have wither wrong or missing information. If i'm right that this is why this is happening then it shouldn't be hard to fix, would just need someone to work out the exact frames for each animation and enter the correct information into the FPS's for the characters and the parts.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed as above

**Comment by LeeBamberTGC** [comment]
Fixed a connected issue causing all Fantasy Characters to use a strange stutter melee attack, changed logic for single sweep damage per attack cleans up the action and Fantasy characters can now attack a third person character again unhindered.

**Comment by LeeBamberTGC** [comment]
Issue of some Fantasy Characters not using melee attack animation remains, a strange one, but next on Lee's list!!

**Comment by LeeBamberTGC** [comment]
Turns out the weapons held by these characters caused the system to think they should shoot. System now detects if the weapon is (7) bow, (8) axe or (10) sword status panel types and permits them to attack using the weapon's melee capability.  Also updated the Fantasy Character FPEs to specify the weapon melee attack frames.  TPP on these characters now work.
