### ISSUE TITLE
importer broken. 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5876]
I am writing to bring attention—once again—to the persistent and critical issues with GameGuru MAX’s handling of imported models. These problems have existed since the software's release, and despite repeated reports over the years, they remain unresolved. Below are the specifics of the issue and its impact:

Issue Description
When importing 3D models into GameGuru MAX, the engine consistently breaks them, even though the models appear fine in every other 3D software. Specifically:

The models appear exactly as designed in:
Blender
Unreal Engine
Various 3D model viewers (including lightweight tools like Windows 3D Viewer)
However, upon importing into GameGuru MAX, the models are broken in one or more of the following ways:
Flipped or incorrect orientation (axes are misaligned despite being properly exported).
Distorted collision or rendering issues.
Disappearing faces or inverted normals, even when normals are correctly calculated in the source file.
Materials or textures either fail to load or render incorrectly.
These issues occur regardless of whether the model is exported as .FBX, .OBJ, or other supported formats.

Reproduction Steps
Create a 3D model using Paint 3D (or any lightweight modeling software).
Export the model in a common format such as .FBX or .OBJ.
Open the model in Blender, Unreal Engine, or other 3D tools to confirm it displays correctly.
Import the model into GameGuru MAX.
Observe that the model breaks: flipped axes, missing faces, incorrect scale, or texture/material issues.
Why This Is a Serious Problem
Standard Compliance:

If a model works in every other program but fails in GameGuru MAX, it highlights a non-standard implementation in your import system.
This lack of compliance with industry standards (for .FBX, .OBJ, etc.) makes it unnecessarily difficult to use third-party assets in GameGuru MAX.
Persistent Frustration for Users:

This issue has been reported repeatedly since GameGuru MAX's initial release. For years, users—including myself—have flagged these problems with little to no resolution.
Impact on Workflow:

These issues force users to adopt extensive, time-consuming workarounds, such as:
Re-processing models in tools like Blender to apply additional transformations.
Editing .FPE files to fix scaling, rotation, or collision issues.
Experimenting with different formats and settings for hours to achieve what should work out of the box.
Barrier to Adoption:

Many users have reported switching to alternative engines (Unity, Unreal) because GameGuru MAX cannot reliably handle imported models.
Request for Action
To address this issue, I strongly urge the development team to:

Audit and Improve the Import Pipeline:

Ensure the handling of .FBX and .OBJ formats adheres to industry standards.
Automatically detect and correct axis orientation, scaling, and normals during import.
Provide detailed import logs or error feedback to assist users when things go wrong.
Implement Pre-Processing Tools:

Include a simple in-engine tool to adjust rotation, scale, and collision settings for imported models.
Acknowledge and Prioritize:

Acknowledge this as a long-standing, unresolved issue in your roadmap updates.
Provide a timeline for when users can expect improvements to the import system.
Conclusion
GameGuru MAX has tremendous potential, but the inability to handle even basic model imports is a glaring flaw that continues to undermine its usability and frustrate long-time supporters. I hope this report highlights the need for urgent action to address the problem once and for all.

3d viewer:
![Screenshot 2024-12-28 112356](https://github.com/user-attachments/assets/1a24458b-9b3b-4e03-9a78-5f05eedf051a)

blender
![Screenshot 2024-12-28 112419](https://github.com/user-attachments/assets/efc070fa-65f9-446c-beb5-d7373fe21f7a)

unreal
![Screenshot 2024-12-28 112934](https://github.com/user-attachments/assets/b983f997-e666-492c-a8ff-b38ffc816dff)

random website callled online model viewer I randomly googled: 
![Screenshot 2024-12-28 113147](https://github.com/user-attachments/assets/d47bd06b-93b1-4e5e-80aa-f68df1a8c98c)

another random site: 
![Screenshot 2024-12-28 113534](https://github.com/user-attachments/assets/08f81c21-cfa8-44ea-a78b-c47fa2ceadc1)

ALL as I exported. PERFECT.

Game guru Max: 

![Screenshot 2024-12-28 102958](https://github.com/user-attachments/assets/d468588d-f18b-4fc0-8f8b-abf27a33cb43)

ive been reportin this fince 2021.

ive been told it was something Ive done wrong.

yet every single other 3d app imports the model, as I made it and exported it.

max is the only one that destroys it.

[warnin.zip](https://github.com/user-attachments/files/18266025/warnin.zip)

**Comment by synchromesh62** [comment]
**I gave your warnin.zip a try** 
Imported into Max as is and got this result .. Failure but why ?
![M1](https://github.com/user-attachments/assets/ee9299cf-17e7-4fc8-bd3e-59989132c373)

I then checked the model in UU3D which showed hundreds of useless bones and not set correctly on its origin.
( UU3D usually shows the model in the state it really is. )
![UU3D1](https://github.com/user-attachments/assets/bc148b83-f188-4ba1-bf94-724daaff7f34)

I deleted the useless bones and reset the origin as it should be for Max.
![UU3D2](https://github.com/user-attachments/assets/71cd3d0e-2652-4477-b735-912612db47fd)

Finally saved as .fbx and then imported into Max with no problems.
Hope that helps in some way.
![M3](https://github.com/user-attachments/assets/814b80ba-1743-4500-8c0c-349e54d8f5ab)

**Comment by casigus** [comment]
![image](https://github.com/user-attachments/assets/319bc00e-2937-4b58-afa4-f1df90ecc0a7)
theres literally no bones in my version at all....

![Screenshot 2024-12-29 011309](https://github.com/user-attachments/assets/07356415-ba08-454a-89b7-f141f5783e9a)
![Screenshot 2024-12-29 011312](https://github.com/user-attachments/assets/3386f53d-50cc-43ec-8462-c0f7de85d5bb)

and the orgins off by a tiny tiny tiny tiny tiny little ammount?

![Screenshot 2024-12-29 011446](https://github.com/user-attachments/assets/64274a31-61ab-4d0f-a1b6-c860ed8ab872)

and yeah, when I add to That software, the bones appear???

![Screenshot 2024-12-29 011739](https://github.com/user-attachments/assets/2d49e6cd-6109-4280-adfc-37ea6c7d4cac)
![Screenshot 2024-12-29 011743](https://github.com/user-attachments/assets/2e8605f4-8da5-45b2-bab4-5b5d178355f2)

so where are those bones coming from?  and why isn't blender showing anything?

managed to get the sign in, imported it into blender, exported it, boom was fine textures n all, but just dont grasp why bones are being added when I've not needed to add bones since its a sign.

**Comment by synchromesh62** [comment]
No idea where the bones are coming from if you created the model from scratch yourself. But i do think they were part of the problem.
The origin is in the centre of the sign meaning it will always be halfway in the floor when you place it on the map in Max so if you want to avoid that the origin is best placed at the bottom .. 
btw .. On my import pic i accidently deleted a red texture for the text and its showing grey.
Just to be sure i re-imported with all the textures and it seems fine. 

![S1](https://github.com/user-attachments/assets/36c7dd94-71f1-44b0-88e8-43d3e95cc26c)

**Comment by casigus** [comment]
yeah made the model from scratch, so literally dont understand the random bones at all.

**Comment by synchromesh62** [comment]
> yeah made the model from scratch, so literally dont understand the random bones at all.

That's very strange then, perhaps a setting in blender ?
If it was a 3rd party model i could understand it being hidden in there.

Max has one thing going for it when it comes to importing which is it doesn't like anything with possible issues. So if it fails there is usually good reason. ( especially 3rd Party ) whereas other engines just load in whatever you throw at them whether they have issues or not which in my opinion is not a good thing.

If I do use other models ( even Classic ) i have a strict workflow i stick to by first loading the model into UU3D and setting rotation, origin and ensuring nothing is there that should not be. Then saving as .fbx
I then usually create a new PBR texture set so basically its as Max ready as i can get it.
This way i rarely have any problems.

**Comment by casigus** [comment]
yah ! alot of my imports are ok, but then a lot just do this?  with other game engines, it just seams to correct any issues, for example in Unreal, everythins imported as I'd built the sign,  so ideally ggmax needs something for these situations where it just see's theres a issue with the model and goes NOPE.  but as I've said before, I think .dbo is very dated, and thus leads to these sort of issues. thanks for the assist.

**Comment by synchromesh62** [comment]
> yah ! alot of my imports are ok, but then a lot just do this? with other game engines, it just seams to correct any issues, for example in Unreal, everythins imported as I'd built the sign, so ideally ggmax needs something for these situations where it just see's theres a issue with the model and goes NOPE. but as I've said before, I think .dbo is very dated, and thus leads to these sort of issues. thanks for the assist.

Actually when Max imports the model as it is either in .fbx, .x or .OBJ so what you see in the importer is how assimp sees the model. It only saves as .dbo so that would not effect it to be honest.

**Comment by casigus** [comment]
well ive found assimp is ok with .gltfs, always having issues with .fbx
