### ISSUE TITLE
Wierd Directory structures being created by Save Standalone 

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#592]
As a quick experiment I saved the levels supplied with the Abandoned Apartment and The Antiques in the Attic Packs as standalones,

As you can see in the attached screen grabs and tree output some very strange looking empty directory structures are appearing under the " ..\entitybank\abandoned apartment pack" and " ..\entitybank\antiques in the attic pack" directories.

I am using Build :2019.07.01 - July Update

![Antiques In The Attic entity bank](https://user-images.githubusercontent.com/35710601/62987222-062ab980-be82-11e9-9b9a-04b2ea500d72.PNG)

![Abandoned Apartment Pack entities](https://user-images.githubusercontent.com/35710601/62987215-02973280-be82-11e9-85e9-6a58689a6c6f.PNG)

[MYGamesTree.txt](https://github.com/TheGameCreators/GameGuruRepo/files/3499405/MYGamesTree.txt)

**Comment by plemsoft** [comment]
@Ratall Thanks for reporting this,

This has been fixed and will be in the next update :)
