### ISSUE TITLE
Animation issue when particles on screen as well.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#595]
When animated entities and particles on screen at same time the animation is broken.

No particles: https://vimeo.com/355148611

With particles (Vsync on): https://vimeo.com/355148760

With particles (Vsync 0ff): https://vimeo.com/355168011

GG version is latest PP, PC is brand new Win 10 desktop machine with RTX 2060 GPU.

**Comment by AmenMoses** [comment]
My theory is that something that is called from the particles code is using a global variable that is also used in the animation code but not initialised properly, maybe the frame rate or something similar.
I've looked myself (my VS is screwed at present) and haven't spotted any possible culprits but I'm not very familiar with the animation code.

**Comment by AmenMoses** [comment]
Tested a fix from Preben which seems to have solved the issue.

**Comment by plemsoft** [comment]
https://github.com/TheGameCreators/GameGuruRepo/pull/597/commits/17cceec8af375d8b50bb1a86b77b2a9e4005318e
