### ISSUE TITLE
Issue: Skybox Changing via LUA 

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#599]
Changing the skybox via LUA makes the terrain disappear for several frames.

**Comment by Teabone3** [comment]
Also noticed on some machines it will actually freeze the entire game for up to 5 seconds, during a transition. I have a game making use of this command so its an unfortunate discovery.

**Comment by Teabone3** [comment]
Unfortunately had to pause development of my game due to the issues related in this command. 

https://forum.game-guru.com/thread/221328

**Comment by Teabone3** [comment]
Okay this is very important, I just tried this in standalone and it seems to work perfectly with a very very minor stutter. If anyone else has experienced any issues with this command let us know. otherwise i think im closing the issue.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

The only difference from standalone and test game , is that when generating the new environment probe (for PBR) , then in test game it also save this new .dds file as a "cache file" , this is not really needed when called from lua , so i have removed this delay so standalone and test game is now the same.

Ready from the next update :)
