### ISSUE TITLE
Floorzone issue

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#600]
Floor zones cannot be laid in internal buildings whilst using "Tab" 
They mess up as soon as you try to manipulate them. This is of course on a second floor which they are supposed to be intended for as pics show.

![T1](https://user-images.githubusercontent.com/35708217/64169199-1dd3dd00-ce45-11e9-9951-b1458b753f90.png)

As soon as you try to drag any nodes they sink and attach to terrain.

![T2](https://user-images.githubusercontent.com/35708217/64169259-4c51b800-ce45-11e9-8e16-caa31a14ae1c.png)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Update .. Still does this but only using Tab .. If I do it via 3D view inside the building its fine but really awkward :(

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting the issue,

This has been fixed and will be in the next update :)

**Comment by synchromesh62** [comment]
Wow thanks Preben :)
I thought this one would be a right pain.

**Comment by LeeBamberTGC** [comment]
Confirmed as fixed, tried with the church model with top-down and clipping with TAB and the floor zone could be positioned perfectly.

![image](https://user-images.githubusercontent.com/35840583/77831258-01bbc400-7126-11ea-849b-e803ab288b7b.png)
