### ISSUE TITLE
Game Saves fail after a few times.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#602]
Gamesaves fail after a few attempts either not loading at all or loading without functions.
I did get round it myself using a single autosave at the beginning of the level but for a puzzle game that's ok for reloading on another day .. 

I could see it being a showstopper for others though.

**Comment by Kitakazi** [comment]
Hi, I'm commenting here with a similar issue I have been having involving save/load. Once I build about 5-6 semi-detailed levels of my game whenever a player saves their progress and then later goes to load into the level sometimes it will fail to load a massive amount of entities, including crucial scripts. Recently I had about half of my level fail to load. That is walls, enemies, scripts(that allow the player to proceed), lighting, etc. Did not load at all. 

This is obviously game breaking and like Synchromesh said, if this isn't fixed there is no point to continue to develop or working on any project.

**Comment by synchromesh62** [comment]
I also noticed the saves are numbered so if you save 6 files and then exit the game and delete the saves from the savegames folder when you return its clear but the first top new save is numbered 7 ?

**Comment by synchromesh62** [comment]
I actually got around this by removing the save menu completely and using an Autosave script that saves the start position of each level so I have only one load slot that's updated as you progress.

A great work around if you do not need to carry anything over like guns, items etc to the next level and very stable as it just saves the start position of the level your on.

**Comment by synchromesh62** [comment]
@Kitakazi 
Have you tried the " allowfragmentation=4 " in the setup.ini that was added in the recent update to clear all memory before reloading the level ?
This seems to have rectified the situation for many. Could you please try and confirm your results as soon as possible

**Comment by Kitakazi** [comment]
@synchromesh62 I cannot confirm as I have deleted those levels since I posted that. I currently do not have any levels made that were as detailed or intricate.  Sorry :(
This issue really only happened on very detailed levels, so it probably has to do with the memory limit?

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
This for me was totally random and varies on maps. Understandably you might not be able to pin this down without self testing. Best left until last perhaps.

**Comment by plemsoft** [comment]
@synchromesh62 Do you get the same error message as this one:

https://github.com/TheGameCreators/GameGuruRepo/issues/705


Or how do it crash any errors ?

**Comment by synchromesh62** [comment]
@plemsoft 
Hi Preben
No this one isnt the same. GG doesn't physically crash its just stops loading in the saved level
Either nothing happens when you click load or your just taken back to the menu screen.

**Comment by LeeBamberTGC** [comment]
Ideally we need a set of FPM levels using stock media that can be used to save a standalone, and then run a predictable number of save games to see this bug. So far there is no reproducible here and will be closed at the end of March if it cannot be confirmed. Using the new auto frag setting will resolve the memory issue, which may in turn resolve this issue, no way to know if this fixed it until we can recreate the bug without the new setting applied.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Understood.
Like I said above its totally random and can happen any time on any level so it looks like a wait and see if its fixed issue … Cant ask for any more than that under the circumstances  :)
Thanks for the info.

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Understood. As you know, repro is perhaps the hardest part of the bug hunt :)  I will assume the memory fragmentation issue was related to this one and we can call it fixed as I have now changed the defaults in SETUP.INI to:

profileinstandalone=0
allowfragmentation=2
standalonefreememorybetweenlevels=1
