### ISSUE TITLE
fillgameslots.lua can't be edited. Editing cause crashes

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#603]
in titlesbank\fillgameslots.lua the line "EMPTY PROGRESS SLOT" can not be edited in anyway to represent different languages for example. 
If it is changed in anyway either by deleting a space or adding a character or writing something different like "EMPZY PROGRESS SLOT" when you try to click any altered "EMPZY PROGRESS SLOT" from the main menu screens's load game part, the standalone will crash.

**Comment by AmenMoses** [comment]
If you change the string in fillgameslots.lua you will also need to change the same string in loadgame.lua.

**Comment by sfkylcnky** [comment]
Thank you AmenMoses.
