### ISSUE TITLE
BuildingsPack inside texture is not copied over standalone

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#604]
buildings pack\insides\flats buildings\flats building 1
buildings pack\insides\flats buildings\flats building 2
buildings pack\insides\gothic buildings\gothic building 2
buildings pack\insides\skyscrapers\skyscrapper 2

when using these buildings in a standalone certain .dds files are not copied over. Therefore 2 flat buildings don't have inside textures, skyscrapper doesn't have a stair and gothic building's roof is missing when you go inside. Copying the missing textures into the file by hand solves it but they won't be encrypted anymore.

**Comment by sfkylcnky** [comment]
buildings pack\shanty building 2
buildings pack\shanty building 4

has the same problem

**Comment by sfkylcnky** [comment]
I don't think this is an enhancement since the stated building's are perfectly fine in the editor. But when saved as standalone following .dds files don't get copied for related entities for instance:

shanty building 2b_d.dds
shanty building 4b_d.dds

**Comment by plemsoft** [comment]
@sfkylcnky Thanks for reporting this,

This has been fixed and will be in the next update :)
