### ISSUE TITLE
Antiques In The Attic Pack\Rug 3b texture is not copied over standalone

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#605]
Title says it all. Rug 3b is not visible in standalone. Copying the textures over to the standalone manually solves it but again it won't be encrypted anymore.

**Comment by plemsoft** [comment]
@sfkylcnky Thanks for reporting this,

This has been fixed and will be in the next update :)

**Comment by sfkylcnky** [comment]
Thank you plemsoft.
#604 is the same with this issue but somehow it is marked as enhancement

**Comment by plemsoft** [comment]
@sfkylcnky Thanks, did not see that one, just fixed it so will also be in the next update :)
