### ISSUE TITLE
Performance Update - 13/09/19 - Ignoring objects

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#612]
If a static object is set to "spawnatstart = no" in the entities properties panel, it is ignored. 

The object is visible in test game. 

Metal Door Large in valuable assets 2014 pack. Might be other objects too.

**Comment by synchromesh62** [comment]
Is that the only one ?
I just tried mine and stock with no probs so far .
Being a third party asset is probably something in his .fpe or model ?

**Comment by tarkus1971** [comment]
Yes Preben has maybe found the problem.
