### ISSUE TITLE
Vignette via LUA

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#615]
My map is completely white when I use these commands with the following values:

SetPostVignetteRadius(100)
SetPostVignetteIntensity(100)

and Game Guru in game set these to over 1000 and the screen is completely white. There needs to be a threshold here or some way to reset this back when exiting the map perhaps. Cause when you exit the test game and go back the effect is still there.

Noticed this issue occurred in 2016 mentioned by others and was not resolved since...

https://forum.game-guru.com/thread/214773?page=2

What is the correct values that should be used for these commands?

I'm assuming its similar to the following:
function SetBrightness(v)
 -- range of -0.5(0%) to 0.5(100%)
 SendMessageF("setbrightness",v)
end
function SetContrast(v)
 -- range of 0(0%) to 3.33(100%)

**Comment by Teabone3** [comment]
Please if anyone can help me it would be wonderful. As I'm not able to properly test my game now.

**Comment by exadion** [comment]
Not certain what the range is but I was able to recreate the issue.[ Created a level, made a player in zone to run the two commands. run test game ( get white screen ) exit test. rerun ( without player touching zone) Now it shows 10,000 on each bar.]

 I was able to use SetPostVignetteRadius(1)
SetPostVignetteIntensity(1) which set the bars to 100 and worked for me making everything visible again. I am guessing 100 made 10,000 and 1 made a hundred so probably a decimal between 0 and 1.

Also, the tab menu bars don't seem to update when changed by script. Basically start it, run the script. use esc to close it, then run a second time to see the changes.

**Comment by HierToo** [comment]
The slider value is multiplied with 100, so you need to use a value between 0-1.
You can not use the slider values in the lua functions

**Comment by Teabone3** [comment]
I was able to fix my map thankfully by doing the same. I think I may have even set it to 0. A description should be added to the global.lua for these commands to make the range to use very clear.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

To make it work on old and new levels ,the ranges for both can now be:
range: 0.0 - 1.0
or range: 0 - 100
And your not able to go above or below the allow ranges.

Ready from the next update :)

**Comment by Teabone3** [comment]
Thank you!

**Comment by Teabone3** [comment]
can this also be added to global.lua if not already

"range: 0.0 - 1.0 or range: 0 - 100"
