### ISSUE TITLE
Stand-Alone Issues - Beta 2019-09-16 Performance Build

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#616]
Pretty happy with this build - great work people

FYI:
All seems to work fine for me, except a couple of issues found thus far:
1) There is a black screen and the endless windows busy icon for 20-30 seconds when loading any level. Appears to be random one build it will do it next it won't.
This issue wasn't there in the July Beta - and sorta detracts from the experience.

2) When player has weapon on going to next level. If the next level uses FreezePlayer (eg while showing a message ) - the player will be running on the spot.

3) If player has weapon hidden, then hits escape, changes graphics\audio, the weapon will be shown on resume.

4) When choosing a different graphics option, it looks like the level looses all adjustments (goes back to default settings) until resuming game play.

5) Selecting an empty progress slot results in instant crash.

Thanks
Reliquia....

**Comment by plemsoft** [comment]
@michaeloldman 

> There is a black screen and the endless windows busy icon for 20-30 seconds when loading any level.

Could you try "producelogfiles=1" in setup.ini and post the log file here , it should show where the delay is :)

**Comment by michaeloldman** [comment]
@plemsoft 
OK will turn that on in settings.

Last build worked fine, will try another one tomorrow, I have been a getting a similar thing with Substance when saving, so could be Graphics driver, or maybe I had Substance running when the issue occurs in GG.

Thanks for reply

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting issue,

> 2: When player has weapon on going to next level. If the next level uses FreezePlayer (eg while showing a message ) - the player will be running on the spot..

Was not able to reproduce this , tried it with:
\Files\scriptbank\stories\The Big Escape\startdisplay.lua

And no running on the spot ? , perhaps you have another bug in your script , or if you still have this problem ,please submit as a new issue ( its hard to mark issues when there are more then one problem per issue).

All the other issues has been fixed :)
