### ISSUE TITLE
Defults weapons sounds missing Dryfire/Zoom

### ISSUE THREAD

**Issue by Peri32** [TheGameCreators/GameGuruRepo#618]
I noticed the sounds of the dry fire and the zoom is not playing at all with the default guns.

Thanks

**Comment by mtrm92** [comment]
thats not a bug its part of the last update

**Comment by Peri32** [comment]
I see, so the sounds will back soon?

בתאריך יום ו׳, 20 בספט׳ 2019, 17:57, מאת mtrm92 ‏<notifications@github.com>:

**Comment by Peri32** [comment]
Or is it done on purpose?

Thanks.

בתאריך שבת, 21 בספט׳ 2019, 0:54, מאת Eldar Peri ‏<eldarperi32@gmail.com>:

**Comment by mtrm92** [comment]
No sounds are gone 4 ever cuz the weapons doesnt contain dryfire animations, but heres a solution
https://forum.game-guru.com/thread/221117

**Comment by Peri32** [comment]
Thanks it a good solution, what about the zoom? in some games you can hear
the gun parts clicking while a zoom, I think it can add some feel to the
games.

‫בתאריך שבת, 21 בספט׳ 2019 ב-13:45 מאת ‪mtrm92‬‏ <‪notifications@github.com
‬‏>:‬

**Comment by mtrm92** [comment]
zoom?there was never a zoom sound, maybe only in the sniper rifle
