### ISSUE TITLE
TPS mode unplayable

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#619]
It is tiring to see something that works fine before an update gets buggy after it. Unfortunately this happens after every update. I am not even going to talk about the animation issues with 3rd person, we have already enough issues adressing that. After the latest update (july) you can not interact with doors in third person mode. Use any door and any character to launch TPS and you will see that door can not be opened or closed. From time to time Prompt will appear but not as it should be. Here is a .fpm for anyone to test and confirm is possible. I used Characters\Fantasy\Wizard Royal as third person and Fixtures\Doors\Standard Industrial Door as example

[door.zip](https://github.com/TheGameCreators/GameGuruRepo/files/3638823/door.zip)

**Comment by synchromesh62** [comment]
" It is tiring to see something that works fine before an update gets buggy after it. Unfortunately this happens after every update. " 

This is the Public Preview and not an update ..
This is exactly what its for so we can find and sort any issues before an official Update.

**Comment by sfkylcnky** [comment]
"This is the Public Preview and not an update .."

"After the latest update (july)"

**Comment by plemsoft** [comment]
@sfkylcnky Thanks for reporting this,

It has been fixed in the latest PP , please let me know if it fix your issue, thanks :)

**Comment by synchromesh62** [comment]
Confirmed working for me.
Thanks for another fix.
