### ISSUE TITLE
Particle Performance Drain

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#620]
When something with particles is on the map, the animations of guns and such get really messed up. 
I made a video for you to see the issue:
https://www.youtube.com/watch?v=7kW_evyj2JU&feature=youtu.be

**Comment by Duchenkuke** [comment]
Please note that I made that video on an empty map! The issues are FAR more severe on big maps with more entities! The animations get slowed down much more - reloading takes up to 10 seconds sometimes!

**Comment by michaeloldman** [comment]
Yeah, have the same issue with animated doors\gates.

On a map with a few items it works OK but when there be lots of doors and lots of other props an animated door can take ages to open\close.

Will make a vid as soon as possible.

OldFlak....

**Comment by Duchenkuke** [comment]
I apologize for any harsh comments - I edited the original post ^^

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 

Video demonstration supplied above.

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this,

The particle system has been updated and are now 100% faster , this do not mean that you will not see your issue if you also double your used particle effects , but with the ones in your video you should be fine. Your now able to use way more particle effects without getting a slow down.

Ready from the next update :)

**Comment by Duchenkuke** [comment]
very cool, thanks a lot :)

**Comment by LeeBamberTGC** [comment]
Code additions fine, particles run great!
