### ISSUE TITLE
Mouse scroll wheel

### ISSUE THREAD

**Issue by mtrm92** [TheGameCreators/GameGuruRepo#627]
Seems like its hard coded, theres no way to change the function of it from weapon change to any other one

**Comment by HierToo** [comment]
The mechanic is in gameplayercontrol.lua line 456.
There is a comment "-- Change weapon using scroll wheel"

**Comment by Kasseyus** [comment]
Script is located in the script bank folder of a standard Game Guru installation.  Recommended to make a backup of this file before any changes are made! :)

Will close this issue now.  Seems to be resolved.
