### ISSUE TITLE
BUG - Tab - Scroll wheel raising and lowering in Map Editor

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#628]
Using Tab and the scroll wheel to raise or lower the visible entities works, but the entities above the lowest view are obscured by taller entities as an "invisible mask" which you can only see terrain through. Will post pictures soon.

**Comment by tarkus1971** [comment]
Here is the dropbox link to video of bug. 

https://www.dropbox.com/s/1v95ezypy2wrimc/Tab%20-%20Mouse%20wheel%20height%20bug.mp4?dl=0

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed ,Video supplied above.

**Comment by LeeBamberTGC** [comment]
This has been fixed for entities created using the EBE building editor, which assigned the wrong shader to the final entity and did not allow the alpha slice code to clip the invisible parts in the shader. Also, if any of your custom entities use the shader "entity_basic.fx", change them to "apbr_basic.fx" and this problem will be fixed for those entities as well.
