### ISSUE TITLE
Polygons

### ISSUE THREAD

**Issue by mtrm92** [TheGameCreators/GameGuruRepo#629]
A general engine enhancement would be great, right now we have a pol limit for about 20k per model, in meanwhile unity 4 example have 65000

**Comment by Belidos3D** [comment]
"right now we have a pol limit for about 20k per model" 

No we don't if i remember right, that poly limit is for models with bones and is roughly 23k per mesh within the object, so if you have a model that is 22k for the body and 15k for the clothes and say 5k for the hair you can use it as long as the body, clothes, and hair are separate meshes/objects within the model.

As far as i know non-boned models have a 65,000 polygon limit.

**Comment by Kasseyus** [comment]
Given that explanation, seems like this issue is no longer an issue?  Will close for now.
