### ISSUE TITLE
Third Person Bug , Long overdue

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#639]
Any chance we can have this fixed as its really a show stopper for third person games.

Key forward and press key back = character stops = Perfect
Key back and press key forward = character stops but turns = acceptable 
Key right and press left = Michael Jackson = show stopper
Key right and press left = turns and does Michael Jackson = showstopper
Could we just have it so if you press another directional key they just stop if that's easiest.

 https://youtu.be/o6KVF_91Jb4

**Comment by Teabone3** [comment]
I posted this a long time ago and they closed the issue though the problem still remains

#168

**Comment by HierToo** [comment]
Sry, looks like I did not identify the problem completely the last time. Created a new fix.
You can look at the gameplayercontroller.lua with the link down here, override you own file and check if it works.
[https://github.com/TheGameCreators/GameGuruRepo/blob/b59c11dc5ff0bf62f04cdd701d866638a4a9e56c/GameGuru/Files/scriptbank/gameplayercontrol.lua](gameplayercontrol.lua)

**Comment by synchromesh62** [comment]
@HierToo 
Fantastic thanks .. Just tried it and it seems to work perfectly :)

**Comment by Kasseyus** [comment]
Issue appears to be resolved - closing.
