### ISSUE TITLE
Failure to save new settings in visual settings

### ISSUE THREAD

**Issue by m2design** [TheGameCreators/GameGuruRepo#640]
When using tab, tap and making changes to the visual setting panel during test mode and then exiting GG the program does not ask if I want to save the current map. Requiring to user to repeat the changes on next session

**Comment by synchromesh62** [comment]
A prompt would be good for that but to be honest if I make any changes on anything and im happy I manually save anyway. Usually 2 versions just in case :)

**Comment by plemsoft** [comment]
@m2design Thanks for reporting this,

This has been fixed and are ready from the next update :)
