### ISSUE TITLE
Terrain type problem

### ISSUE THREAD

**Issue by m2design** [TheGameCreators/GameGuruRepo#641]
This has become a real problem. I can no longer try different terrains to determine which terrain type I want to use in my existing maps.
**Test process:**
Load map and run test mode. Press tab, tab and in the World settings panel Select a different terrain type. New terrain is generated. Save map with new terrain. Exit GG. Reload GG and open the map that was just saved.
The terrain now displayed has reverted to the original terrain that was current before the change. In other words the new revised terrain that was generated has **not been saved**. Press tab, tab and look at the terrain type displayed in the world settings panel. It displays the name of the new generated terrain type but maps the old terrain.
Or  make a copy of "The big escape.fpm" file. Rename the copy created. Use the copy for the following...

Example:
Open the (the name you used for the copy.fpm". file. In the test mode press the TAB, TAB and display the panels. Make note of the terrain type displayed in the world settings. In the world settings panel under terrain type change the terrain to a different terrain. Make note of the new terrain name. Save the copy file that now displays the new terrain. IMPORTANT Exit GG. Open GG and open the file you just revised. Run test. The terrain in the just revised file will not show the terrain that was just changed but it will show the original terrain not the new one. TAB, TAB to display the World settings panel which will display the name of the revised Terrain as it should. But that new terrain will not be what is shown as the terrain displayed in the map. If you look at the DAT file in the mapbank folder you will see the dat file contains the Terrain type name in the copy file you have used but will never display that terrain file. 

This problem does not appear using smaller maps but does when, terrain changes are made, in maps of similar size to The big escape. 
REMEMBER do not use the original "The big escape" file you must use a copy so as not to corrupt the original.

**Comment by plemsoft** [comment]
@m2design Thanks for reporting this,

This has been fixed and are ready for the next update :)
