### ISSUE TITLE
Breakable Barrels etc standalone issue ..

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#644]
The scripts for breakables seem to be missing the call for  " quatlib.lua " in their scripts and are causing an issue when creating standalones when stock maps are created using them.
After some investigating it seems  ……. Include( "quatlib.lua" ) 
is missing from the... graphix_explosion.lua

![quatlib](https://user-images.githubusercontent.com/35708217/69763629-b2f52200-1165-11ea-9d13-e0c09ff02416.png)

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this,

This has been fixed and are ready for the next update :)

Also support require "" , and will scan recursively so include/require inside new added .lua scripts is also added.
