### ISSUE TITLE
Fpe commands that do not appear to work.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#645]
;Light Extras
lightcolor    = -256
lightrange    = 200
lightoffsetup = 15
lightoffsetz  = -10

;decals
decalmax      = 1
decal0        = flametorch

These do not appear to work, for example in the Meg pack 2 Cave pack there is a wall torch entity which from the fpe file should have flames and cast light but all you really get is a lump of wood.

When clicked on the entity act like it is a light source and parameters gives the light settings btw.

**Comment by Belidos3D** [comment]
I think those settings are legacy from when they were converted from FPSC (most of the early DLC packs were taken from FPSC) and were probably left in because they were intending to add those features but never got around to it.

**Comment by synchromesh62** [comment]
Indeed these are old Legacy commands
