### ISSUE TITLE
standalone doesn't open.keeps saying " the application was unable to start correctly (0x0000142). click ok to close the applcation.

### ISSUE THREAD

**Issue by ds-baba** [TheGameCreators/GameGuruRepo#647]
the update i have is 2018-11-26

**Comment by HierToo** [comment]
Update to the current GG version. This error occurs sometimes if someone use a outdated version.
If that does not help, you maybe have a corrupted windows system/graphic driver/virus.
[https://www.repairwin.com/fix-application-was-unable-to-start-correctly-0xc0000142-solved/](https://www.repairwin.com/fix-application-was-unable-to-start-correctly-0xc0000142-solved/)

**Comment by plemsoft** [comment]
@ds-baba Thanks for reporting this,

Yes try to update to the latest version , and let us know if this fix your issue :)

**Comment by ds-baba** [comment]
I installed a version from this year (don't know whether there is more version) and the standalone worked. the error message doesn't show up. but now there is another problem which is, it is not the game that I saved. the standalone starts with me underwater and few islands.

**Comment by plemsoft** [comment]
@ds-baba Thanks , i replied to your other issue.
