### ISSUE TITLE
P-LIST Projectile Cache is hardwired and shorts out

### ISSUE THREAD

**Issue by boltactiongaming** [TheGameCreators/GameGuruRepo#648]
I've been troubleshooting projectile-based issues for months since writing my article on how to make projectiles function with custom projectiles in GG.
Rapid fire projectiles, in particular, require pre-caching of at least 25 projectiles. Oftentimes you may need as many as 50-100 precached.  Unfortunately, the system has no means of errors for logging (please add this as well) 
In my case, I had two rapid fire projectiles setup.  One was a flamethrower, the other a plasma gun (ala doom).  The plasma weapon would not work if the flamethrower was setup.  Other projectiles worked intermittently.
Eventually through some help of preben creating a version which allowed me to see more accurate logging of what was being loaded, I was able to see that it's loading every projectile, even completely unused ones on every single game load (this is a tremendous waste of resources and genuinely should NOT be done, it is poor design).  This also occurs for every single gun that is in the G-List as well.

P-LIST (Projectile List) only has 8MB assigned to it.  This value is non-dynamic and is totally reliant upon you not having more than perhaps 1-3 projectiles built, maybe 4 or 5 if you are lucky.  Even reducing my texture sizes for animated projectiles (using magicbolt as the basis) to 1024/1024 with an 8x8 sprite sheet, I'm still pushing 1MB on the detail file.  

Proposed solutions:
* Better logging added to the base GG build.
* Throw an error message if it doesn't load, instead of defaulting to simple raycasting with no obvious source of a problem.
* Only load weapons actually relevant to the level, along with their related projectiles (if any) to reduce memory load.
* Dynamically reassign memory allocation for G-LIST and P-LIST based on number of entities being loaded

**Comment by plemsoft** [comment]
@boltactiongaming Thanks for reporting this.

Projectile cache will now only get setup when they are used.
Max cached projectiles can now expand if needed.

Ready from the next update :)
