### ISSUE TITLE
UI Issue - Can't See Editor Pointer Position

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#649]
I cannot see the coordinates of where the mouse is on the map. Usually its in the bottom right corner but I noticed in certain resolutions like the one I use, its not visible at all. Only the x value.
![position](https://user-images.githubusercontent.com/35990109/70196090-9dd44200-16d5-11ea-8060-2c0e6d33771c.JPG)

**Comment by Teabone3** [comment]
Was this by chance fixed in V3's new UI?

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed …
Also noticed when you place the mouse pointer om the lower right hand of the bat they cut parts of it as shown below … Possibly related 

![co-or](https://user-images.githubusercontent.com/35708217/74181686-a4cd8280-4c39-11ea-85a2-0a550eb8d1dc.png)

**Comment by LeeBamberTGC** [comment]
Adjusted space given to reduce width for the clip text, increasing space for the X and Z values and reduced width for the snap modes. Works better now.
