### ISSUE TITLE
"soundset" not working - soldiers dont use audio.

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#65]
I would like to know why there are no enemy sounds in the Public preview? I just need to type "male" in the soundset pannel of the soldier, right ? It doesnt work at all ! No sounds are played whatsoever.
It worked in DX9.. Maybe it is because of the AI tweaks ?

**Comment by Teabone3** [comment]
I was just about to post this. Also when you assign the soldiers a soundset it for some reason does not work.

**Comment by LeeBamberTGC** [comment]
Yes the new AI scripts do not use the SetCharacterSoundSet(e) command which was used in the old AI behaviors, and instead use the five sound slots in the entity properties:

-- sound0 : Start moving A
-- sound1 : Start strike
-- sound2 : Start moving B
-- sound3 : Get hurt A
-- sound4 : Get hurt B

If you want the new AI scripts to use the SetCharacterSoundSet(e) command, it would have to be an enhancement or addition to the existing latest scripts.

**Comment by Teabone3** [comment]
So no more random audio plays from a folder based on idle, alert, hurt, playerhurt, death etc?
