### ISSUE TITLE
when opening standalone, it's not the one i created. the standalone starts with me underwater and few islands.

### ISSUE THREAD

**Issue by ds-baba** [TheGameCreators/GameGuruRepo#651]

**Comment by plemsoft** [comment]
@ds-baba Thanks for reporting this,

Did you change the standalone .exe file name ? , it is used to find the first level of your game.

If not let me know the name of your standalone .exe file :)

**Comment by ds-baba** [comment]
nope. it is as it is. didn't change the name.

**Comment by JCLEONITA** [comment]
happened to me too several times in my standalone tests but i cannot maanged to reply the issue..
if it happen again i'll send the entire map to lee

**Comment by ds-baba** [comment]
![Annotation 2019-12-08 164253](https://user-images.githubusercontent.com/58467592/70388610-2e629900-19da-11ea-9c54-0ce83ab4ad7e.jpg)
![Annotation 2019-12-08 164525](https://user-images.githubusercontent.com/58467592/70388611-2e629900-19da-11ea-9f12-177d038063fd.jpg)

**Comment by synchromesh62** [comment]
Try replacing the start marker and also your map must be saved in the default " mapbank " folder as thats where GG looks for it … Its always one of these :)

**Comment by ds-baba** [comment]
@synchromesh62 thanks, dude. I put the file to the mapbank and it worked.
