### ISSUE TITLE
[Walled Garden Pack] Issue when placing multiple "Cemerary Gate" entities. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#652]
Currently if you place 2 or more copies of 
**"Cemerary Gate 01c" 
"Cemerary Gate 01d" 
"Cemerary Gate 01e"
 "Cemerary Gate 01f" 
 "Cemerary Gate 01g"** 
Then the texture on the entity will bug out. They then will look like the attached screenshot. Placing a single one of these entities causes no problems only when 2 or more are placed. 
![Desktop Screenshot 2019 12 08 - 00 21 24 61](https://user-images.githubusercontent.com/51464873/70385189-8b663c80-1951-11ea-8538-6210332dd145.png)

**Comment by synchromesh62** [comment]
Tested and confirmed Thanks to Myke …
The UV map is also moving in testgame

**Comment by LeeBamberTGC** [comment]
Seems these particular models, created from the old importer, did not like to be batched. Added a line to the FPE called "drawcalloptimizeroff=1" which excludes them from being drawcall batched, and this solved the issue.
