### ISSUE TITLE
HideHuds command issue

### ISSUE THREAD

**Issue by JCLEONITA** [TheGameCreators/GameGuruRepo#653]
Hi I noticed taht if i use a script which the HIdeHuds() command and after i eventually comment the command to display standard hud again the standard hud is not displayed anymore and i have to create a new  fresh scene/level  to make standard hud to be visible again even if the HideHuds() command is commented in the script..
pratically the command doesnt change in realtime and effect cannot be seen until a new level  is created  in the editor

**Comment by Teabone3** [comment]
What do you mean by comment the command?

To display you need ShowHud(e)

**Comment by synchromesh62** [comment]
Funny it does work on my game and my latest level by simply by making the entity its attached to static.
Yet on a blank map today it does not ? 
Perhaps I have something in another script in my game that causes it to reappear ?

**Comment by plemsoft** [comment]
@JCLEONITA Thanks for reporting this issue, this was fixed and will be in the next update, sorry for the delay this issue was not marked as a bug.
