### ISSUE TITLE
When shaders set to MEDIUM, realshadowresolution in setup.ini does nothing

### ISSUE THREAD

**Issue by UnknowNomad** [TheGameCreators/GameGuruRepo#656]
Reproduction:
1: Set realshadowresolution to low value (for example 64 or 256)
2: Launch any GameGuru map that have sun shadows active
3: Test game
3: Highest settings will have resolution set at this value, hovewer MEDIUM shaders will have it at higher value (1024?)

In the pictures it's shown with realshadowresolution=256
![Guru-MapEditor_2019_12_20_20_32_14_783](https://user-images.githubusercontent.com/38816061/71287755-7cc45000-2369-11ea-8c27-c368b921c796.jpg)
![Guru-MapEditor_2019_12_20_20_32_25_427](https://user-images.githubusercontent.com/38816061/71287768-81890400-2369-11ea-9413-863ac0417e2d.jpg)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Discribed as above

**Comment by plemsoft** [comment]
@UnknowNomad Thanks for reporting this, this has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment]
Confirmed as fixed.
