### ISSUE TITLE
Occlusion culling freakout + when occlusion is set to 0, grass doesn't draw at certain places

### ISSUE THREAD

**Issue by UnknowNomad** [TheGameCreators/GameGuruRepo#657]
See video and submitted level to check. Watch the video to the end to see both issues
Level is made exclusively with stock media, so everyone can check it out.
[Map.zip](https://github.com/TheGameCreators/GameGuruRepo/files/3989975/Map.zip)
[https://drive.google.com/open?id=1Uhyff1lQUDANUJP4QtVdrp2olmYqxfYK](url)

**Comment by UnknowNomad** [comment]
https://drive.google.com/open?id=1Uhyff1lQUDANUJP4QtVdrp2olmYqxfYK

**Comment by synchromesh62** [comment]
Hi UnkownNomad 
I tried your map and noticed the Occlusion was set to " 2 " 
Setting it to zero fixed it for me and I also noticed in your Video it was set to " 2 " 
Please try again and confirm that this could have been the problem as so far im not getting the issue.

**Comment by UnknowNomad** [comment]
With occlusion set to 0, it renders correctly, but there is severe performance hit because there is no occlusion. The difference shoudn't be that large with it set anything that 0, even 1 had this problem.
And grass rendering issue with occlusion set to 0 is a problematic.

**Comment by synchromesh62** [comment]
@UnknowNomad 
Ok no worries thanks for the Reply … My only thought is zero is off and anything after that is the lowest setting … However for me "OFF " ran very well and smooth not dipping much below 60 fps which I thought was impressive considering your using the whole map.

Either way its in the March bug fix so Lee and Preben  can check it out :)

**Comment by UnknowNomad** [comment]
Occlusion on 2-10 culls way less objects that 100, just test it on default maps, you will see the difference.

**Comment by plemsoft** [comment]
@UnknowNomad Thanks for your issue report, this has been fixed and will be in the next update.

**Comment by LeeBamberTGC** [comment]
Confirmed as fixed for next update.
