### ISSUE TITLE
When using baked lighting the Flashlight doesn't work right. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#660]
The Flashlight is incredibly bright on areas that are lit by lightmaps and almost not existent when aimed at an area that isn't lit by a lightmap.

**Comment by synchromesh62** [comment]
@Kitakazi 
Could you please confirm this with a video or pics of what your seeing.
I tried it but for a dark Environment but was able to adjust the slider setting do my desired effect.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
After further testing it does appear the torch does not work correctly after Lightmapping.
It appears a lot dimmer and almost useless .. Video added Below, full screen recommended to view.
https://youtu.be/ErFOVxqWVoI

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this.

This has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment]
I can confirm this fix for flash light strength on lightmapped surfaces for the next update.
