### ISSUE TITLE
LUA loaded Audio not copying to Standalone

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#661]
Audio loaded via LUA not copying over in standalone build process.

OGG and WAV file formats

**Comment by AmenMoses** [comment]
Looking at the code it only handles "LoadGlobalSound(", i.e. if there is a space before the open bracket it will not recognise the command properly.

**Comment by Belidos3D** [comment]
As a workaround until it is fixed, there is an easy way to get them to carry over, simply add the audio files to any model on the level, it doesn't need to access them or use them, just have them in the properties, and it will carry over to standalone.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
I think Amen has found the problem above.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this, this has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment]
Confirmed as fixed :)
