### ISSUE TITLE
The setup.ini settings enableplrspeedmods and disableweaponjams do not copy over to standalone. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#662]
In the setup.ini these 2 settings do not copy over to the setup.ini for standalone projects.  
enableplrspeedmods 
disableweaponjams

Obviously the work around is to copy and paste them into the standalone setup.ini file. So while not really a big deal I figured I might as well report it.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Tested and confirmed.

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this, this has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment]
Confirmed as fixed.
