### ISSUE TITLE
Motion Blur effect is bad

### ISSUE THREAD

**Issue by UnknowNomad** [TheGameCreators/GameGuruRepo#667]
1: Launch GameGuru
2: Load any of the sample levels
3: Test Game
4: in TAB TAB menu set Bloom to anything than 0, set Motion Blur Distance at 0 and Motion Blur intensity at 100
5: Motion Blur will be still very subtle, and there is no blur when running straight, only when turning the camera

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
This seemed to work fine for me and im assuming Motion Blur is only supposed to work when turning your head and not running ?

**Comment by UnknowNomad** [comment]
Actually, it worked when it was implemeted first in 2015, before C++ rewrite.

After then, it was always broken.

**Comment by plemsoft** [comment]
@UnknowNomad Thanks for reporting this,

I checked my old dx9 source and the code looked the same , 2015 that was also the dx9 version, or is it an even older one ?

Anyway as you say it is subtle so motion blur could use a improvement, but its not a bug this is how its been coded so ... I will change it to enhancement instead of bug :)

**Comment by UnknowNomad** [comment]
The first version of implementation, in 2015, before C++ conversion had it working well.

**Comment by plemsoft** [comment]
@UnknowNomad Yes i dont have that version, that must have been the DBP version ?, perhaps @LeeBamberTGC have the old code somewhere ? , anyway it would need a rewrite.

But would be funny to see the old version of GG :)

**Comment by LeeBamberTGC** [comment]
Agreed the work to make it 'better' should be classified as a feature. The motion blur works as presently designed here: 

![image](https://user-images.githubusercontent.com/35840583/77381338-8220a480-6d75-11ea-85fe-d6a48d4f22b6.png)
