### ISSUE TITLE
Pickup Items, Weapons etc Text

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#668]
Pickup objects such as weapons and alike, display text when you have them in view.. which is good. However if you look slightly to one angle and the object is no longer in view, the text will still display as if it is.

Its an issue that's been around for several years, was once corrected but reverted. Its related to angles. 

`PlayerDist = GetPlayerDistance(e)
 if PlayerDist < 150 then
	SourceAngle = g_PlayerAngY
	while SourceAngle < 0.0 do
		SourceAngle = SourceAngle + 360.0
	end	
	while SourceAngle > 340.0 do
		SourceAngle = SourceAngle - 360.0
	end
    PlayerDX = (g_Entity[e]['x'] - g_PlayerPosX)
    PlayerDZ = (g_Entity[e]['z'] - g_PlayerPosZ)
	DestAngle = math.atan2( PlayerDZ , PlayerDX )
	DestAngle = (DestAngle * 57.2957795) - 90.0
	Result = math.abs(math.abs(SourceAngle)-math.abs(DestAngle))
	if Result > 180 then
		Result = 0
	end	
	if Result < 20.0 then`

**Comment by AmenMoses** [comment]
Just change the scripts to use the utillib PlayerLookingNear function.

**Comment by Teabone3** [comment]
I don't feel comfortable with changing all stock and DLC weapons, items and ammo? I'm wondering if TGC can do this so that the future updates dont un-do what was once fixed.
