### ISSUE TITLE
Request - Saturation 

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#669]
A request for a Saturation Slider to be added alongside the Contrast and Brightness shader. The saturation slider would allow for us to add or remove colors. Good for creating black and white effects.

Also LUA commands to control the effect would be nice as well :)

**Comment by Belidos3D** [comment]
Yup, definitely need this and many more additions like this.

**Comment by Teabone3** [comment]
I can confirm that this is now added to Game Guru Classic. Only thing remaining would be the Lua command for the controller. Tanks so much guys for adding!
