### ISSUE TITLE
GameGuru editor Public Preview 2018 water fragments

### ISSUE THREAD

**Issue by tomik18** [TheGameCreators/GameGuruRepo#67]
Hello Lee i have issue with new Public Preview 2018 GG in editor i have fragments in water. screenshot attached
![waterfragment](https://user-images.githubusercontent.com/32257860/36245327-ed93e5c2-122a-11e8-9036-dddd46e259f1.png)

**Comment by plemsoft** [comment]
Hi tomik18,

The fragments are actually LOD terrain , you use this system to make your game faster, the more "dark" part you have in the water the better. The dark part display where the LOD terrain system is active.

So the more dark part you get the faster your game will run.

Try this. in your screen shot , if you select the "Level mode" tool , and put the cursor at one of the "dark" areas and then start to level the terrain below the water line , you will see that you get more "dark" areas , this is a good thing and display where the LOD will work.

This system is only active below the water where the terrain is flat , and you are NOT able to see the missing terrain when you run around inside your game.

**Comment by tomik18** [comment]
plemsoft thank you for clarification. So this is new feature in this update ?

**Comment by plemsoft** [comment]
Ohh i cant remember when it was first added , but it was also in the last DX9 version ;)
