### ISSUE TITLE
Wizard in Third person Very bad firing delay.. 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#672]
As the title says .
The Wizard has a very bad delay firing in third person … 
Push button and release before he actually fires.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed and retested.
To reproduce simply drag the Wizard on to the Start Marker and run test game.
Then try firing the mouse button.

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this,

I have investigated this , and found that it is not really a bug , but how the weapon staff is made.

What is happening is that it will fire, and then wait for the start fire animation to complete.

So this is how this weapon is suppose to work.

If your edit: \gamecore\guns\fantasy\Staff\gunspec.txt
And change:
"start fire = 31,45"
to:
"start fire = 44,45"

It will fire immediately, hope this answer your issues :)

**Comment by synchromesh62** [comment]
Hi Preben
The only reason I flagged it as a bug is that it never used to do this ? It worked perfectly fine and still does in older versions.
But if your edit works then that's brilliant thanks ..

**Comment by synchromesh62** [comment]
@plemsoft 
Confirmed Edit works :)

**Comment by LeeBamberTGC** [comment]
Made fixes to all four staff weapons for next update.
