### ISSUE TITLE
Dear Gamegurus - please fix the footstep sounds issues - video attached.

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#677]
Now that we are finally in the "bugfixing" phase, let me jump back in and report this annoying and long existing bug.

The Footstep sounds dont play when going down a hill, no matter how tiny that hill is.
walking UP a hill works fine. Flat terrain works too. I have made a video for this post, please have a closer look at what I mean. It should be fixable I think :) 

https://www.youtube.com/watch?v=Ljk47oKF8zs

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Tested and Confirmed that footsteps do not make any sound going downhill in any direction.

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this, fixed and ready from the next update :)

**Comment by LeeBamberTGC** [comment]
Works when walk down hill. When RUN down hill, no footsteps heard:

[RunDownTheHill-NoFootsteps.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4346819/RunDownTheHill-NoFootsteps.zip)

**Comment by plemsoft** [comment]
@LeeBamberTGC Fixed in latest commit, sometimes you will not touch the ground when running fast down, so it only trigger when you actually have a foot on the ground.

**Comment by LeeBamberTGC** [comment]
Confirmed as fixed :)
