### ISSUE TITLE
Save game issue

### ISSUE THREAD

**Issue by HierToo** [TheGameCreators/GameGuruRepo#678]
> I am currently alpha testing a game and ran into a major problem that can be quite frustrating for people intending to sell their game.
So here goes: You know how you can see your date and time at the lower right corner of your screen? Well GG does save the date and time of a saved game if you make a game save (that was not the most eloquent way to put it, but I am sure you follow)
Now, in windows you can have your date displayed in various formats. For the EU it would be 01/20/2020 and for the US: 01 - FEB - 20. However, it seems to be the case that if the game creator has a different format set up than the player, the game crashes while saving with the error you see in the attached images.

Forum link:
[https://forum.game-guru.com/thread/221506](https://forum.game-guru.com/thread/221506)

**Comment by 3coms** [comment]
Or better yet, why not allow the player to call the saved game as he wishes.
For example: Tower1, creppy house1, room2, and so on.
Just has to label buttons with the user input, rather than automatically, such as now.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
This seems to be rectified if using names rather than a date.

**Comment by 3coms** [comment]
Meantime I'Ve using:

strNewSlotName = g_iGameNameNumber .. ": " .. "GameSave " .. g_iGameNameNumber --os.date()

in savegame.lua file, and I've got:
GameSave1
GameSave2
GameSave3, and so on.

**Comment by 3coms** [comment]
I've got with user input, do not get results instantly, but when re-open the menu.

I think is necessary to force code to wait user input, before call save func.

**Comment by LeeBamberTGC** [comment]
This fixed with #705, also fixed here.
