### ISSUE TITLE
Five or Six things needing to be fixed

### ISSUE THREAD

**Issue by PCVeteran** [TheGameCreators/GameGuruRepo#679]
https://www.youtube.com/watch?v=Nk8qL4Kd7Wo

**Comment by PCVeteran** [comment]
https://www.youtube.com/watch?v=Nk8qL4Kd7Wo

**Comment by LeeBamberTGC** [comment]
@PCVeteran Could you provide links to the GitHub issues that report the ones in the video, thanks!

**Comment by synchromesh62** [comment]
@PCVeteran In order to help clear all the current Bugs in March could you please give detailed information or a video perhaps on how to reproduce these issues. Without being able to reproduce them or detailed information they are at risk of being excluded from the March bug fix undertaking

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
No actual bugs or reproductions given.
