### ISSUE TITLE
Latest Version not downloading store items

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#68]
Not a biggie and not sure if its just me but I have wiped my GG folder and downloaded the latest version all is fine except it will not synch with the TGC store it will not download purchased items I did a full backup before I wiped so I can drag my purchases over but I wanted to test this new version from scratch and the first thing I tried was to download my purchases and it does not work.

It could just be me but I thought I would raise it just in case
Regards
Kevan

**Comment by honkeyboy** [comment]
Have you tried opening the store page and downloading them while its open i had this a couple of times when i had closed the store webpage down. Worth a try m8 :)

**Comment by GraPhiX-Guru** [comment]
yeah tried that mate no joy :(

**Comment by earthling45** [comment]
The link seems to be broken, no list, no downloads.
I've tried it with a few free items and thus had the store page open. :)

**Comment by Pirate-Myke** [comment]
This is working for me. Had to press the GameGuru Store button twice for it to recognize that I was logged in. Then it gave me the list of items I just acquired. Then it downloaded them.

**Comment by earthling45** [comment]
Yes, it is working again :)

**Comment by GraPhiX-Guru** [comment]
Yes this is working for me too now :)
