### ISSUE TITLE
Free Flight View (right click + arrow keys)

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#688]
When in free flight view, holding right click allows you to look around and the arrows keys allow you to move the free flight camera position. However, if you use both together, the cursor will be relocated, regardless of whether you actually move the mouse or not. Eventually it will fly off the screen and, in you're on a 2 monitor system like me, you will end up right click the desktop on monitor 2. 

In this video, I demonstrate holding the right click down but not moving the mouse, and using the arrow keys. See how the cursor changes position every time, eventually creeping to the right of my screen and outside of the Game Guru editor window.

https://youtu.be/AgDOypbnRv4

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Video and details supplied above.

**Comment by plemsoft** [comment]
@AvengingEagle Thanks for reporting this, this has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment]
I can confirm this has been fixed.
