### ISSUE TITLE
0 Ambience is not total darkness

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#689]
Setting ambience to 0 does not remove all light from a scene like you'd expect. 

![0ambience](https://user-images.githubusercontent.com/60984223/74370248-ae3c2380-4dce-11ea-80a0-17d252792b70.jpg)

**Comment by synchromesh62** [comment]
@AvengingEagle 
For total darkness I think you would need to turn the " Surface Level Slider " down as well.
Can you see if that works for you first ?

**Comment by AvengingEagle** [comment]
All that does is reduce the effect of any lights in the scene. Sorta defeats the point. So basically I have a choice between total darkness where lights don't work, or lights that do work but with some ambience.

**Comment by synchromesh62** [comment]
@AvengingEagle 
I have asked Lee regarding this and apparently its neither a bug or enhancement.
The ambience is only one factor in the final lighting calculation. Its not meant to be totally dark.

**Comment by AvengingEagle** [comment]
Thank you for contacting Lee, @synchromesh62, but unfortunately I'm not satisfied with that answer. If I create a windowless room with no light sources in it, I should be able to make it pitch black surely? 

Ambience is the most fundamental step in any lighting calculation, it's literally step one. In any other program or engine, it would have a value between 0 and 100, with 0 being pitch black, and 100 being the _color/_d maps being rendered at their full native brightness.

**Comment by synchromesh62** [comment]
I tried this and didn't really have any problems …
I tabbed the settings at the end of the video ?
I had to tweak it till i was happy but i see what lee meant by ambience is only part of the process
https://youtu.be/deh-s7VQuQ0

**Comment by AvengingEagle** [comment]
OK, by playing around with Surface Level and the Surface RGB, it is possible to get pitch black, aside from some highlights I'm guessing are caused by the normal map. Here the Surface Level and Surface Red, Green, and Blue values are all set to 50. 
I was always hesitant to lower Surface Level as it has an effect on dynamic lights too and makes them damn near imperceptible. This image shows a single dynamic light on the left, and static lights on the right with the same hex value and range. Note how dim the dynamic light is. 
![1dyn_1static](https://user-images.githubusercontent.com/60984223/75183996-89836c80-573b-11ea-8ae6-e0a3be2210a0.jpg)

**Comment by AvengingEagle** [comment]
By placing 10 of those dynamic lights in the same spot, you can finally start to see them.
![10dyn_1static](https://user-images.githubusercontent.com/60984223/75184298-15959400-573c-11ea-9e41-160beb999047.jpg)

**Comment by AvengingEagle** [comment]
At 20 copies of the same dynamic light, we are approaching roughly equal luminance values for the dynamic lights versus the static ones. This leads me to believe dynamic lights are 20x dimmer than static lights, so either the shaders needs to account for this, or the engine does. Lights really should be the same brightness regardless of whether they are static of dynamic. 
![20dyn_1static](https://user-images.githubusercontent.com/60984223/75184340-280fcd80-573c-11ea-85a5-afdb4bb70f93.jpg)

**Comment by synchromesh62** [comment]
Weird ... Pics look awesome though.
My video had just one dynamic light set to a 550 range ( which is a lot ) but it takes into account the surface sliders at only half way … I guess the big question is .. If ambience was lower would that also cut the lighting out and has it been set at that perfect balance already ?

![light](https://user-images.githubusercontent.com/35708217/75186926-d9b0fd80-5740-11ea-9ada-1ea179b0bbf1.png)

**Comment by AvengingEagle** [comment]
A bit more testing seems to suggest that static lights are infact 6x brighter than dynamic ones. Here's 6 dynamic lights (left) next to 1 static light (right)
![6dyn_1static](https://user-images.githubusercontent.com/60984223/75189027-3e6e5700-5745-11ea-80bb-07c990b46d61.jpg)

**Comment by AvengingEagle** [comment]
I also tried using 1 dynamic light but increasing the range to 6x that of the static light, but it didn't really have the desired effect.
![1dyn750r_1static](https://user-images.githubusercontent.com/60984223/75189096-63fb6080-5745-11ea-8666-b627c4797e96.jpg)

**Comment by AvengingEagle** [comment]
Settings...
![1dyn750r_1static_settings](https://user-images.githubusercontent.com/60984223/75189202-9c9b3a00-5745-11ea-9d47-c5fa1538be32.jpg)

**Comment by synchromesh62** [comment]
How did the setting I used look ?
One of the other problems of course is our monitors, Remember the slider most games had to set the ingame brightness. we could be seeing our levels totally differently ..
![setting](https://user-images.githubusercontent.com/35708217/75189880-11bb3f00-5747-11ea-9435-697191f6b8e5.png)

**Comment by AvengingEagle** [comment]
Like this...
![1dyn750r_1static_synchro](https://user-images.githubusercontent.com/60984223/75202746-24903c80-5764-11ea-912e-19643c6cb679.jpg)

That's the same setup as my last image btw; 1 dynamic light set to 750 range, 1 static light set to 125 range. There's the slightest hint of light on the wall from the static light, but nothing from the dynamic.

**Comment by Kasseyus** [comment]
Historic Issue (6mo+).  Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.
