### ISSUE TITLE
Light markers in editor do not have range ring from above

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#69]
Light markers in editor do not have range ring from above.
https://puu.sh/zmCl4/2700472d86.jpg
https://puu.sh/zmClh/b70f8402c5.jpg
https://puu.sh/zmClE/914d443b46.jpg
https://puu.sh/zmCmG/387dfd2668.jpg

Repro steps:
Open Game Guru editor.
Place a light marker.
No range ring from above can be seen.
Go to free flight mode.
Get under the light and up to almost level with it.
Results:
You can see the range ring from underneath the light marker.
Repeatable:
Always
This has been this way since the DX11 updates started.

**Comment by tarkus1971** [comment]
Yes same here. Have to dip under to see it.

**Comment by AmenMoses** [comment]
This is probably related to the 'no range ring' in 'L' splatter mode or whatever it's called.  The code looks like it is enabling the ring in both cases so I'm guessing it's a render problem, maybe even a shader issue?

**Comment by plemsoft** [comment]
Fixed:
