### ISSUE TITLE
GetGlobalSoundExist, don't avoid GG crashing

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#695]
To recreate this error follow the steps below:
1- You create a map and add the player and a barrel.
2- Attach the script below to the barrel.
3- Run the level.

```
btn_clicked = 0
sound_end = 0 

function testing_getglobalsoundexist_init(e)
end

function testing_getglobalsoundexist_main(e)
	btn_clicked = 1
	sound_end = 1
	
	if GetGlobalSoundExist ( btn_clicked ) then 
		PlayGlobalSound ( btn_clicked ) 
		sound_end = GetGlobalSoundPlaying ( btn_clicked )
	else
		Prompt("sound does not exist: " ..btn_clicked )
	end	
end
```

You'll get "runtime error 3004 ()"
#define RUNTIMEERROR_SOUNDNOTEXIST
And GG crash.

Obviously the sound file does not exist, so this seems the logical consequence, but it is not so much if one thinks that the "GetGlobalSoundExist" command exists to deal with this error.

Or is it that the "GetGlobalSoundExist" command does not really fulfill its purpose? It does not prevent GG from crashing, GG seems to ignore this command completely and simply crash.

Could it be a mistake, or is there something missing to add to the internal code?

**Comment by AmenMoses** [comment]
It's probably not returning true/false.

Most GG functions return 1 or 0 to indicate true or false.

**Comment by synchromesh62** [comment]
@AmenMoses 
Hi Amen
Would this be considered a bug or just a coding mistake ?

**Comment by AmenMoses** [comment]
Scripting mistake you mean, yes although if global.lua doesn't specify what the function returns that should be fixed.

**Comment by synchromesh62** [comment]
Ok thanks Amen.. 
If it needs fixing then happy to label as Bug:)
Plus the fact you gave the solution will help Lee and Preben Greatly 

@LeeBamberTGC 
@plemsoft 
Confirmed as bug .. See AmenMoses solution above ..

**Comment by AmenMoses** [comment]
Just needs documenting properly in global.lua, no code change required.

All functions that return "1" & "0" for true/false should be likewise documented or maybe even grouped together with a covering comment saying that is the case.

**Comment by 3coms** [comment]
Engine is ignoring "GetGlobalSoundExist" flag, and/or do not getting their value,
Or mybe engine handling errors via internal rutine, and does no care external ones.

**Comment by AmenMoses** [comment]
Change it to if GetGlobalSoundExist( id ) == 1 then

**Comment by 3coms** [comment]
Nice one Amen, ty again. :)

**Comment by plemsoft** [comment]
@3coms This has been fixed so it now works in both cases, ready from the next update.
