### ISSUE TITLE
Entity MoveForward and Rotation Issues with Physics

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#696]
I noticed an issue related to MoveForward LUA command. This command works great alongside commands like Rotate which will allow you to make entities that move at angles , for example like an airplane or cars:

https://youtu.be/rIeA7cYR2uE

However I noticed when using MoveForward or MoveBackward commands with physics on and if the objects collide with anything, they will bump and rotate as expected, however the entity will no longer move forward, instead it will move sideways or whatever direction it was in before it changed its angle when it bumped/collided.

One way to test this is to place an entity down and give it a simple MoveForward command and place a immobile object ahead of it. Watch the entity hit the object and start to turn but then move sideways instead of the direction its facing.

**Comment by Teabone3** [comment]
What i think the problem is here is when an entity is rotated by physics, the data is not being translated to the entity's local rotation data. 

When i get some free time I'll do a check to see if this is the cause, by using the GetRotation commands to see if any of the local data has changed.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Explanation and video supplied above

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

This is not really a bug , physics has its own life and is not related to the MoveForward command that use its own rotation.

Anyway you can change the MoveForward rotation to reflect the physics/object if you wish, you can do something like this:

```
	CollisionOff(e)
	MoveForward(e,tforwardspeed)
	CollisionOn(e)
	SetPosition(e,GetEntityPositionX(e),GetEntityPositionY(e)-0.025,GetEntityPositionZ(e)) -- gravity
	SetRotation(e,0,GetEntityAngleY(e),0)

```

This will make the MoveForward command head in the direction that the object is pointing :)

**Comment by LeeBamberTGC** [comment]
@Teabone3 See if you can implement the solution Preben provides, and we can close this as a bug. There are no plans to add additional functionality to the Physics system at this time, but you can report this as a feature request in a new issue if you like, with a description of how you would like a physics-based object to react when you use the MoveForward command (with perhaps a parameter to indicate the amended behavior). If we change the way it works now, we will break someones game project that relies on how it functions now.
