### ISSUE TITLE
SetSkyTo causes massive visual shearing.

### ISSUE THREAD

**Issue by boltactiongaming** [TheGameCreators/GameGuruRepo#698]
The SetSkyTo command causes a massive visual flicker that is highly disruptive visually.
This happens even when setting the sky to the existing sky.

Recommendations:
1) Buffer the sky change before performing it
2) Don't attempt a sky change if it's the same sky.

**Comment by plemsoft** [comment]
@boltactiongaming Thanks for reporting this,

This has been fixed and will be in the next update , it dont get any faster then this :)

https://drive.google.com/file/d/1lPj1NTCNFRvIXZ_2JJZiojZG0pmH4F-A/view?usp=sharing

**Comment by LeeBamberTGC** [comment]
Can confirm the SetSkyTo command is super quick!

![image](https://user-images.githubusercontent.com/35840583/77831357-8a3a6480-7126-11ea-9d5c-5ba28390fb5e.png)
