### ISSUE TITLE
Illumination maps are very dim

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#7]
Also, glow areas are not affected by surface lights so they can appear darker than the rest of the model. However, glow areas are affected by ambient light so if set to zero it won't glow.

**Comment by plemsoft** [comment]
In settings.fx you can enable this:
//#define BOOSTILLUM
Just remove the // infront of the line so it looks like this:
#define BOOSTILLUM
That should fix it :)

Remember if you use the Public Preview you need to edit setup.ini and set:
forceloadtestgameshaders=1
This will allow you to make the shader changes in settings.fx

**Comment by LeeBamberTGC** [comment]
I have started a new wiki document which should hopefully consolidate all help resources into one place, and this little tip made it in as the first piece of advice in the shaders and lighting category :)
