### ISSUE TITLE
Entities not visible sometimes.

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#70]
In the forum thread of the new PP it is mentioned that sometimes the characters are not visible after closing testmode to return to the editor.
I've seen this happening with the 5/12 version so it is probably an old bug.
One which is happening in the PP is that at the first startup the EBE structure becomes invisible when closing EBE.
This only happens at the first time after starting GG and is repeatable.

https://forum.game-guru.com/thread/219343#msg2596093

**Comment by earthling45** [comment]
Ok, Preben already solved the EBE issue. :)
I'll try to find a repeatable way for the characters.

**Comment by earthling45** [comment]
I've made a safe with an animated door which either vanishes at the end of the animation or it remains visible only when the player is quite close to it.

<a href="http://www.youtube.com/watch?feature=player_embedded&v=1lDVgDdOhEU
" target="_blank"><img src="http://img.youtube.com/vi/1lDVgDdOhEU/0.jpg" 
alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

This has obviously to do with occlusion, hence i've set 'notanoccludee = 1' in the FPE in order to solve this.
But i do want to report on it because it is of course preferable that it can be occluded, even if it has an animation.
Is there a possibility to set a range for occlusion?
Or is this a bug? because if i do not drop the last frame in order to prevent the flashing, it flashes but remains visible and is thus not occluded.

**Comment by plemsoft** [comment]
> I'll try to find a repeatable way for the characters.
No need i believe im on top of this :) , about the safe this is another bug not related to this , but could you try to import the safe using the importer and see if you get the same problem ? , i think this could also be related to another bug a found.

**Comment by Pirate-Myke** [comment]
I have seen the post on the safe, I can check the mesh and see what it looks like

**Comment by earthling45** [comment]
Hi Preben, I've imported the safe using the importer but now it vanishes even while occluder and occludee are set to 'no' and the occlusion slider at 0 in tab/tab.
At the first try i had a black box and only the door was textured, the second attempt it was good but it vanishes.

Pirate Myke, let me know if i made a mistake in the mesh. :)

**Comment by Pirate-Myke** [comment]
Earthling45: Your mesh and animation of the safe work for me with out any issues the way you have it set up.
Placed it on a table from the scenery folder and still functioned properly for me without disappearing during the script and animation.

**Comment by earthling45** [comment]
Thanks for looking at the model Pirate Myke. :)

The generated .dbo behaves quite differently, after restarting GG it remains visible when the occlusion slider is at 0 but it seems to become a static object when the animation ends and the model is displaced.

<a href="http://www.youtube.com/watch?feature=player_embedded&v=uP0kmIOrYDI
" target="_blank"><img src="http://img.youtube.com/vi/uP0kmIOrYDI/0.jpg" 
alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

@Preben, i'll mail you the original and the generated .dbo so you can have a look at it. :)
