### ISSUE TITLE
FPE Reference Paths - Not all working - ! Bug NOT Enhancement !

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#700]
So when you create your FPE you can add the path references to be used as the defaults for the model when added to the editor.
For example:
effect = effectbank\reloaded\effect_name.fx
aimain = scriptbank\myfolder\myscript.lua
Sound0 = audiobank\myfolder\mysound.wav

But the references for sounds don't get added to properties when you plonk the model in the editor.
Tried these formats:
Sound0 = myfolder\mysound.wav
Sound0 = audiobank\myfolder\mysound.wav

Would be super cool if these could be sorted.

Thanks for reading :)

OldFlak....

**Comment by michaeloldman** [comment]
This is not a enhancement request.
Models included in DLC's have references to sound files. 
For example see Droids from Sci-Fi pack.
Since TGC references these paths in their own content, the paths should work. 

It is therefore a Bug :)

**Comment by synchromesh62** [comment]
Sounds are referenced through the properties and there is no available sound command for the .fpe ?
Labeled as enhancement as this would have to be added.
