### ISSUE TITLE
Ammo = zero always gives the player 1

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#702]
When placing any weapon which needs ammo in a level if you set the ammo field to zero you always get 1 of the weapon's ammo when you pick it up, I need this to be zero as I want the player to find an empty weapon then find the ammo for it.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed

**Comment by plemsoft** [comment]
@BodRH Thanks for reporting this, this has been fixed and will be in the next update :)

@synchromesh62 Also fixed for the player start marker.

**Comment by LeeBamberTGC** [comment]
Confirmed as fixed!
