### ISSUE TITLE
Gunspec Firerate settings not working as expected.

### ISSUE THREAD

**Issue by ErrantAI** [TheGameCreators/GameGuruRepo#703]
When setting firerate = x or alt firerate = x in an automatic weapon's gunspec.txt, the actual RoF seems reduced to the whole number value.

example: firerate = 3.8 produces the same RoF as firerate = 3.0

Most modern automatic weapons should reside in the = 2.5 - 4 range, so not being able to use these decimal values limits the amount of available variety.

I'm not sure if it was ever working fully or not but it becomes more apparent now that we have the fireloop = -1 option to properly time gunshot audio to firing instance.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Explanation above

**Comment by ErrantAI** [comment]
Note:  It's possible that the issue wasn't present last year.  I don't recall the Enhanced Weapon Pack Mk18 firing so fast.  It is set to firerate = 3.5 but definitely feels faster now (which would make sense if it is actually using a 3.0 firerate ingame)

**Comment by plemsoft** [comment]
@ErrantAI Thanks for reporting this , yes it has always used a int so it would always remove everything after the "." , anyway this has been fixed and will be in the next update :)

**Comment by ErrantAI** [comment]
Awesome!

**Comment by LeeBamberTGC** [comment]
Confirmed as fixed.
