### ISSUE TITLE
FPS Weapon "last start fire" animation incorrectly used when combined with "automatic fire"

### ISSUE THREAD

**Issue by ErrantAI** [TheGameCreators/GameGuruRepo#704]
This works fine when used in semi-auto guns without "automatic fire" anim. or with full-auto guns when only one bullet remains (no chance for successive automatic firing).

The issue manifests itself as sort of a hiccup at the end of a long burst of firing until gun is empty.
(video link: https://youtu.be/L87qtZ-RVsA )

This is because the engine is playing:

"start fire"
"automatic fire" (looped until one ammo remains)
"last start fire"
"last end fire"

Expected behavior is:

"start fire"
"automatic fire" (looped until fire key released)
"last end fire" (if zero ammo remains, otherwise play "end fire")

"Last start fire" should only play at the beginning of a firing sequence which has been initiated with only 1 ammo remaining in gun (The last shot)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Details and video above.

**Comment by ErrantAI** [comment]
Note, this is reproducible with the alt fire mode of the Enhanced Weapon Pack Mk18.
It should also be reproducable with the AKM but it's not discernable.

**Comment by plemsoft** [comment]
@ErrantAI Thanks for reporting this.

The current setup is like this:

If you fire with 1 bullet left:
last start fire"
"end fire"

If you fire  with 10 bullets left and stop before reaching 1 bullet left:
"start fire"
"automatic fire" looped
"end fire"

If you fire  with 10 bullets left and dont stop:
"start fire"
"automatic fire" looped
"last end fire"

It can never have more then one start and one end (and possible a loop) in the same fire sequence.

What you see in your video would be:
"start fire"
"automatic fire" (looped until one ammo remains)
"last end fire"
and then a dry fire...

I think your "last end fire" is pointing the gun slightly up in the air, and that is what we are seeing.

Anyway there dont seams to be any bugs in this code ? , could you confirm this , or make a step by step to reproduce this error, (and display what is expected to happen).

Thanks for your help :)

**Comment by ErrantAI** [comment]
@plemsoft 

Thanks for investigating this one, Preben.

It's easier to detect by audio rather than by visual because of the interruption in the string of gunfire.
It's also easier to detect with high RoF weapons.

For testing, you can use the Enhanced Weapons Pack Mk18. atl fire mode (keybind [V] by default).

Easy way to test is to edit the gunspec and add subtract 30 frames from the beginning of "alt last start fire" (This can be also tested in primary mode but you will need to uncomment the "automatic fire" anim line to activate it.

ie:
alt last start fire		= 2047,2048
becomes...
alt last start fire		= 2017,2048

Then make sure to force GG to reload gunspec by exiting/relaunching the editor or loading a new map.

In testgame, switch to alt fire [V] and proceed to fire full auto until empty.  It may jam while dumping the magazine but it doesn't matter as long as you have more than 1 ammo left (Just clear jam with [R] and continue shooting.  

When you get to the last shot, the gun will start humping wildly (the extra 30 frames you added now showing the automatic fire anim) and then fire the last shot.   I've tested via this method just now and is is how I can be sure that it's playing "(alt) start last fire" instead of skipping it as it should.

**Comment by plemsoft** [comment]
@ErrantAI Thanks that helped me see the problem :)

Actually it would stop the sequence when you had one bullet left, and then restart the sequence, so yes you would get "alt last start fire". This has been fixed and also you will now only get "Last start fire" when you start the sequence and have one ammo left.

**Comment by ErrantAI** [comment]
@plemsoft Excellent!  

Ahh that actually explains why I was noticing it more with some weapons vs. others.  I had though it may have been dependant on the length of a "last start fire" animation but my testing was inconsistent.  Makes more sense with your explanation that what I was picking up on was actually  length variation in "end fire" anims if it was prematurely ending the sequence then restarting it for the last shot.
Excited to see this and your RoF fix in the new build.

**Comment by LeeBamberTGC** [comment]
MK18 looks fine with the new fix, check out the PP build going up soon to confirm other weapons behave as expected.

**Comment by ErrantAI** [comment]
Just tested in 03.28 build
Appears to be **fix failed**.
Now, when firing full auto until empty.  It appears to be playing no "end fire" or "last end fire" at the end and goes straight from the automatic fire loop to the empty idle.  
This is objectively worse than prior to the fix.
If you guys don't have an effective way for logging which animations are being played, let me know and I can put together a specialized test harness.

**Comment by plemsoft** [comment]
Sure it does , here is the frames played in the video mk18:

https://drive.google.com/file/d/1NzC8KVk948k1x2QG4jJ618wSnrQ7kZuA/view?usp=sharing

57695 : Running start fire: (2027,2028)                         S:22MB  V: (798,0)      
57732 : Running loop: (2036,2043)                               S:0MB   V: (798,0)      
60403 : Running end fire: (2017,2018)                           S:-84MB V: (714,0)      
60456 : Running gdryfire: (2058,2064)                           S:0MB   V: (714,0) 

But its only 2 frames 2017,2018 so end pretty fast. try setting "alt end fire			= 2017,2055" and you will see it.

Please confirm that this is also what you see , thanks :)

**Comment by ErrantAI** [comment]
@plemsoft 
This makes more sense if this is the log but it is not correct as intended.
60403 : Running end fire: (2017,2018) S:-84MB V: (714,0)
Should be playing "alt last end fire" which is a 6 frame animation (2049,2055).
Locally, I am testing on different (new) guns.  Some of which are moure flourished in the last end fire and it is apparent that these anims are not playing.  It explains what I am seeing if it's only playing a regular (short frame) end fire then going to dryfire/empty idle.

**Comment by plemsoft** [comment]
@ErrantAI Thanks the alt last end fire has been added :)

Yes it is my own debug builds , im running out of time with this update , but will try to make a new setup.ini setting to enable this in a later update. Please open a new issue with this as an "enhancement" and i will assign myself , so i dont forget about it  :)

**Comment by ErrantAI** [comment]
@plemsoft Thanks!  This will also apply to the regular, non-alt mode (last end fire) under the same circumstances as well, yes?
I'll add the enhancement request straight away :)
