### ISSUE TITLE
Crash when trying to save a game in standalone

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#705]
Saving in a gameguru standalone works like maybe 3 times in a row but then it crashes and I got this error:

![asd](https://user-images.githubusercontent.com/35990507/75656990-84f01400-5c65-11ea-8d01-9e5e69534fee.JPG)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Possibly related to #678

**Comment by AmenMoses** [comment]
In theory changing that line to:
strNewSlotName = g_iGameNameNumber .. ": " .. os.date("%d/%m/%Y:%H:%M:%S") 
Should fix it.

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this, this is hard to reproduce, if i make a new .exe for you would you be able to test it and confirm that this has been fixed ? Thanks for your help :)

**Comment by Teabone3** [comment]
We have been looking into this one and we believe its related to a modified LUA script.

**Comment by LeeBamberTGC** [comment]
Implemented Preben and AmenMoses fixes for this one, should be fine now but check out the PP build to make sure it works with your specific projects.
