### ISSUE TITLE
lines visible when painting rock.

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#707]
See this image, https://i.imgur.com/mgBZhEM.jpg

In order to be sure that it is not something on my end, i've deleted and reïnstalled GG.

**Comment by synchromesh62** [comment]
@earthling45 
Confirmed I can see this in the editor but vanishes when I zoom in and out and I cannot see it in the test game … Could this be just the edge of the tile or can you see it ingame ?

![Lines](https://user-images.githubusercontent.com/35708217/75714383-83edcf80-5cc3-11ea-95d3-960c918310bf.png)
![line2](https://user-images.githubusercontent.com/35708217/75714390-87815680-5cc3-11ea-804b-789b70faf855.png)

**Comment by earthling45** [comment]
Thanks for the confirmation Synchromesh. :)

They are also visible in game,  many stripes when you move around until you are closer to the mountain edge.
The same happens with the other terrain textures, albeit it is less noticable.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
confirmed as above although I cannot see them in game but that could just be on my screen ?

**Comment by Kitakazi** [comment]
Hey, I've noticed this issue before in game as well. I've taken a  screenshot of what it looks like ingame, it is much easier to reproduce this bug when using baked lighting. 
It may be a little hard to see if viewing the pic from this site. But if you view full size and zoom in just a little bit, you can clearly see hard lines. 
![lines](https://user-images.githubusercontent.com/51464873/76137080-840d0880-5ffe-11ea-9e4c-ec7f179f293f.png)

**Comment by earthling45** [comment]
It seems to be a seamless texture, which texture is that?

It is different from what i meant in the OP as you can see in this image, the uv looks good, those lines occur with blending.
![dT4Tw14 1](https://user-images.githubusercontent.com/35744254/76152155-75852680-60bc-11ea-92d1-64af8615ef45.png)

**Comment by plemsoft** [comment]
@earthling45 Thanks, This has been fixed and will be in the next update :)

BTW: Also removed that white dot artifact that has been bugging me for ages.

**Comment by earthling45** [comment]
Thanks Preben. :)

Those spots were indeed quite annoyingly visible.
I've had spots on the leaves of a tree which reacted to the specular value when i made textures with 'materializer'. 
After redoing the roughness map by gray scaling the colormap and adjusting the values, this is now gone. :)

Since this is fixed, i'll close this issue.
