### ISSUE TITLE
Map Editor Just Shows a Black Screen

### ISSUE THREAD

**Issue by Random-gamedev** [TheGameCreators/GameGuruRepo#708]
When I launch Game Guru it just shows a black screen it will go to a grey screen then "crash" like a soft crash. The map editor doesn't load. ( https://youtu.be/3PzHenxal9g ) Sorry For Posting a Link i Can't Upload Video Files :) My Specs i5 4460s Gtx 1050Ti 8gb ddr3, used to work before i got a gtx 1050 

Only works in 2017/DX9 builds

**Comment by synchromesh62** [comment]
Hi there you do need help but its not a bug for Github.
Looks like you need to contact Customer Support for a hardware issue.
Go here and click the green question mark on the right ( halfway down the page )
https://forum.game-guru.com/
Give as much detail as you can regarding the make and model of your system.
Personally I would uninstall then reinstall GameGuru completely first

**Comment by Random-gamedev** [comment]
Hello synchromesh62 I have tried uninstalling and reinstalling Game Guru

**Comment by synchromesh62** [comment]
Directed to customer support
