### ISSUE TITLE
Bug Report KOMPENDIUM / Public Preview 15.2.2018

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#71]
THANKS for the new PP - I really see some good progress. It needs fixing but what DOES work is very good. I think I changed my mind about PBR :D

Here are some screenshots of all Bugs and graphic Problems I ran into since my testing:

Hope this helps and gets fixed soon :)

![guru-mapeditor 2018-02-15 17-14-02-70](https://user-images.githubusercontent.com/35990507/36268254-52bf8c58-1276-11e8-880e-13e99f6efd5d.jpg)
![guru-mapeditor 2018-02-15 17-14-36-10](https://user-images.githubusercontent.com/35990507/36268255-52e165d0-1276-11e8-8d1c-8939f19a86cb.jpg)
![guru-mapeditor 2018-02-15 17-15-21-88](https://user-images.githubusercontent.com/35990507/36268256-53067578-1276-11e8-96ad-ce756df0408e.jpg)
![guru-mapeditor 2018-02-15 16-51-16-84](https://user-images.githubusercontent.com/35990507/36268257-532f8224-1276-11e8-9c04-53fd1a32be30.jpg)
![guru-mapeditor 2018-02-15 16-56-59-71](https://user-images.githubusercontent.com/35990507/36268259-53512a3c-1276-11e8-8ba4-49d8eb6c340a.jpg)
![guru-mapeditor 2018-02-15 16-50-53-73](https://user-images.githubusercontent.com/35990507/36268261-5373e25c-1276-11e8-9748-cb7ae0bc2134.jpg)
![guru-mapeditor 2018-02-15 17-25-45-70](https://user-images.githubusercontent.com/35990507/36268263-539f3c22-1276-11e8-9ba6-f2175a0404b3.jpg)
![guru-mapeditor 2018-02-15 17-05-38-02](https://user-images.githubusercontent.com/35990507/36268265-53bb4bec-1276-11e8-9495-0b7536f80c33.jpg)
![guru-mapeditor 2018-02-15 17-13-31-71](https://user-images.githubusercontent.com/35990507/36268266-53db843e-1276-11e8-8876-4442e4326f7d.jpg)
![guru-mapeditor 2018-02-15 17-13-45-18](https://user-images.githubusercontent.com/35990507/36268267-53ff66ce-1276-11e8-8368-56d22e645781.jpg)

**Comment by Teabone3** [comment]
Most of these entities need to have the right shader applied as well as come with normal and spec maps that might be missing or non existent.
