### ISSUE TITLE
Explosion Sprite Sorting Incorrectly With Water

### ISSUE THREAD

**Issue by ErrantAI** [TheGameCreators/GameGuruRepo#714]
Certain elements of explosion effects have bad draw order/alpha sorting with water plane causing the sprite/decal to not render correctly when water is in the background.

Video: [https://youtu.be/Xz50632j_bw](url)

![ss+(2020-03-16+at+02 45 43)](https://user-images.githubusercontent.com/43529980/76743719-4dd33580-6730-11ea-9b87-d11574f5a7a7.jpg)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed , Video above but I had to copy and paste to see it.
https://www.youtube.com/watch?v=Xz50632j_bw&feature=youtu.be

**Comment by LeeBamberTGC** [comment]
Latest build has this one fixed. see shot:
![image](https://user-images.githubusercontent.com/35840583/76918800-1050e280-68bf-11ea-8556-16c954aab72a.png)

**Comment by LeeBamberTGC** [comment]
Report that this bug has returned, so need to look at sorting order of water, underwater entities and the explosion effect

**Comment by ErrantAI** [comment]
Specifically, it's the explosionSmokeName decal/particle that isn't sorting correctly with water.

**Comment by plemsoft** [comment]
@ErrantAI Thanks for reporting this issue , i just tried it in the 2020.12.08 - Christmas Fixes version, and it looks fine here:

What version are you using ?
Is there a way i can reproduce this ?

![smoke-particle](https://user-images.githubusercontent.com/18662417/109508870-977f7200-7aa0-11eb-954b-920b7dedc50f.jpg)

**Comment by ErrantAI** [comment]
@plemsoft I'm using the same 2020.12.08 - Christmas Fixes build and test with player facing the default angle.
As mentioned above, it's not the whole explosion effect.  It seems limited to the explosionSmokeName component (b.dds for the m67).  It's mostly noticeable after the initial flash (split second after your screenshot).
![Screenshot 2021-03-02 11-08-21](https://user-images.githubusercontent.com/43529980/109701701-2a271c00-7b48-11eb-8580-87ed232ec3c2.png)

**Comment by plemsoft** [comment]
@ErrantAI Thanks , could you try this "Guru-MapEditor.exe" and let me know if it fix your issue:

https://drive.google.com/file/d/1vKXeWXWdyk2_8EmpVNaH--M56UVrdgQi/view?usp=sharing

Thanks :)

**Comment by ErrantAI** [comment]
@plemsoft No joy. Issue still persists.
![Screenshot 2021-03-03 05-00-45](https://user-images.githubusercontent.com/43529980/109809939-c3ecd880-7bdd-11eb-8ff1-f74002f6ed40.png)

**Comment by plemsoft** [comment]
@ErrantAI Found it , could you try this version and let me know if it fix your issue:

https://drive.google.com/file/d/1vei2kRy2VBd3myPruol1huVV25vx60yn/view?usp=sharing

Thanks :)

**Comment by ErrantAI** [comment]
@plemsoft Sorry for the delay.  I finally got to test this and it works great.  Thanks!

**Comment by plemsoft** [comment]
@ErrantAI working on some changes, but needed your e-mail, so i can sent you a test version, could you give me a e-mail at plemsoft@plemsoft.com , i will then get back to you , thanks :)
