### ISSUE TITLE
terrain texture layers

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#716]
I'm trying stuff and while painting the terrain textures, i've noticed a problem with the blend mask as you can see in the video. :)

https://www.youtube.com/watch?v=xtNx5fkV09k

**Comment by synchromesh62** [comment]
Wow I have seem masking issues before but that edge weird ?
Do you get the same effect from all or is it just that particular texture and is it a stock one ?

**Comment by earthling45** [comment]
I've made another video which shows it more clearly i hope. :)
https://www.youtube.com/watch?v=U3Vbb09NBM0
Notice which textures i select and what i'm actually getting while painting.
The last grass texture which i select from row 3 does not remove the mask from the rock texture and hence we see a line appear.

![banding](https://user-images.githubusercontent.com/35744254/77282306-d79f7780-6cc9-11ea-898f-bfd420c895cd.jpg)

**Comment by earthling45** [comment]
These textures are all stock yes. :)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Second video supplied that shows the issue much better ..

**Comment by LeeBamberTGC** [comment]
@plemsoft Definately not right here. The texture selected should be the one painted onto the terrain. I also noticed in the latest compile that when a texture is custom selected (slot 15 just before the Rock for example), all the grass changes texture slightly. May need to go through and clean up the texture slot selection math.

**Comment by plemsoft** [comment]
@LeeBamberTGC slot 15 will active procedural terrain painting where your texture loaded has alpha 255 , this is what you see. All textures painted produce the correct RGB values.

@earthling45 Thanks for reporting this issue,

Sorry to say there is no way to prevent that blending. this is how the terrain system works.

The system will always blend from the right slot so you get a combination of your selected texture and the texture to the right.

You could add 2 slots with the same texture and use the left to draw , this would then mix it with the right texture (that are the same), so you get the result your looking for , like this:

![two-slots](https://user-images.githubusercontent.com/18662417/77749358-347c9400-7022-11ea-985e-c2734dba7cfa.jpg)

The texture blending with the right texture very depending on the slot you use , here is a heat map (red) that display how much each slot mix ( @LeeBamberTGC "texhigherfactor"):

![texhigherfactor](https://user-images.githubusercontent.com/18662417/77749540-7ad1f300-7022-11ea-9f11-dc5c64e95305.jpg)

@LeeBamberTGC Tried to not do texhigherfactor when we hit destination color:
```
   int iIgnorePureColors = trunc((VegShadowColor.b * 255));
   iIgnorePureColors = fmod(iIgnorePureColors, 17);

```
But that will just produce hard edges:

![hardedges](https://user-images.githubusercontent.com/18662417/77749994-49a5f280-7023-11ea-9371-336dc8339ca4.jpg)

Sorry no way to fix this , this is how it works. Use the 2 slot trick instead :)

**Comment by earthling45** [comment]
Thanks for the explanation Preben. :)
Will use the palette as you have explained or use the procedural terrain painting.

**Comment by LeeBamberTGC** [comment]
Indeed. To make changes to this core behavior would affect literally everyone's terrain in their game projects. We are designing a whole new terrain system for MAX and will be avoiding the issue of sequentially blended texture slots altogether.
