### ISSUE TITLE
Bug: Delete key not deleting entity

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#717]
If I am trying to delete an entity from a map, the delete key is not removing the entity when it is selected, only way to delete is with the widget.

**Comment by synchromesh62** [comment]
Hey Tarkus1971
Can you double check its not the old Num lock or Scrl lock keys on first …
If your on a desktop try disconnecting it and replugging it into usb as well.

I get this sometimes myself and its often the fact I have left those keys on when I start GG

**Comment by tarkus1971** [comment]
OK, It seems to be if num lock is ON i cannot delete, if OFF it's fine.  FIXED.

**Comment by Teabone3** [comment]
Is there any way this can be changed in GG so it doesnt happen? It can be frustrating at times having non-responsive keys due to the num key being accidently pressed.
