### ISSUE TITLE
Gameguru's Standalone exe counts as "Gameguru" in steam 

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#721]
My Game "Dark Skies: The Nemansk Incident" is currently in alpha testing stage on steam.

`https://store.steampowered.com/app/657480/Dark_Skies_The_Nemansk_Incident/?l=german`

All testers have gameguru installed too. 
When they run my game, their playtime counts for gameguru, not my game.
In the steam friends windows it also says they are playing "gameguru" and not dark skies.

Please make the .exe of the standalone game editable or something that I can change this matter.
Or is there anything else I need to do?

Help would be much appreciated!

**Comment by synchromesh62** [comment]
I have added a video to explain your issue for reference

Adding my game Protascope as a non steam game I can get the same results.
When I Launch you will see GameGuru is what shows as running.
https://youtu.be/JPOE9Hk7Zq0

**Comment by Duchenkuke** [comment]
very good

**Comment by LeeBamberTGC** [comment]
@Duchenkuke Have you changed the Number in the file "steam_appid.txt" to that of your Steam App, as this needs to reflect your AppID and not GameGuru's?

**Comment by Duchenkuke** [comment]
I didnt know that this was a thing ! No, guess i will change it now :D

**Comment by Duchenkuke** [comment]
yes, just checked it in the steam folder, the AppID is right. It's the one from my game, not gameguru... Still, I get the same problem :/

**Comment by Duchenkuke** [comment]
Now I changed the AppID to the DepotID - I have yet so see if this fixes it
Gimme some  time to investigate that please :)

**Comment by Duchenkuke** [comment]
CONFIRMED FIX: 

there was a second appID.txt file in that folder!  I didnt see it at first.
I changed the AppID to the right number again and this time it worked! Thanks Lee for helping me!
Finally I got this solved ! yaay ! :)

**Comment by Teabone3** [comment]
Glad to hear! I guess this issue can now be closed?

**Comment by LeeBamberTGC** [comment]
Glad I could help, issue resolved :)
