### ISSUE TITLE
transparency and lighting affected by sun direction?

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#722]
This might be a strange title but i'm not sure how to properly word it.
The problem is that models are only properly being illuminated on the sunside when using the flashlight.
On the shadowside, it is quite dim as you can see in the video.

https://www.youtube.com/watch?v=IE4JR3FsYq8

The other problem is with transparency, looking towards the sun direction, it renders properly, looking away from the sun direction, the windows aren't visible as you can see in the video.

https://www.youtube.com/watch?v=XrH_GrfaOGY

The windowcube can be downloaded here if you want to have a look at it.

https://drive.google.com/open?id=1BdsHJ237iZgpWYFkKzaXdv1mcCRndKZR

**Comment by LeeBamberTGC** [comment]
@earthling45 The flashlight dim issue has been fixed in the latest PP build, but let us know if this is not the case.

The window transparency issue is harder to understand. Can you create a level using stock assets and attach the FPM level here, and then describe what you expect to see through a step by step, from there we can see whether its intended functionality or a bug, thanks!

**Comment by earthling45** [comment]
Thanks Lee, i will look for an asset and see if i get the same result as with the cube, if so i'll make an fpm and drop it here. :)

**Comment by earthling45** [comment]
Hi Lee, you will find some transparency problems with entities from the buildingspack. (insides)
The windowcube which i've shared here was made at the request of m2design last friday and since the overwelming majority say it is best to have the glass separated, i'm going to leave it with this.
Instead of the windowcube i've made a simple two sided polygon, but then i'm faced with clipping problems.
Obviously i am doing something wrong here but i'm at a lost as to what i am doing wrong so hopefully you can push me in the right direction.
See the video of what i mean with clipping.
https://www.youtube.com/watch?v=DvAXNNFawN8

Model and textures.
https://drive.google.com/open?id=10tSE2LB3wEdDDXNSXjxjAhhfB6hK8v-9

**Comment by plemsoft** [comment]
@earthling45 Thanks for your issues,

I checked and everything in the engine is sorted correctly.

I found the problem with the industrialglass.x , the pivot point is not in the center of the object , so when sorting is going on , the right side glass will actually be closer to the camera then the glass just in front of you. ( as the pivot point is at the left side of the object, thats also why to only see this problem when you get near to the right side of the glass).

So to fix that problem , just place the center of the object in the middle. ( this is what is used to calculate the distance to the object and later sorting them ).

About transparency , and windowcube , you cant really make a object with more then one transparent side in a single object , as the draw order of transparent objects need to be from the back (the object longest away from the camera) to the front, or the depth buffer will discard the pixel. This is not a gamegure problem but a problem that are in all engines, just the way the GPU works.

To solve it , the most easy way is to make all glass into separate objects, so GameGuru can sort them in the correct order for you.

You can also add all glass in your object into separate meshes , and then "by hand" sort the meshes inside the object in the correct order. but this will also give problems if your able to see the glass from the other side of the object, so this way can only be used if you cant see into the object from one side.

But its way more easy using single objects , just make sure the pivot (center of the object) is in the middle, so we are able to sort the distance to the object correctly :)

Red = Not correct pivot.
Green = Where the pivot should be in the object.
Blue = the camera center , just think its your eyes, and distance to objects is calculated from here to the pivot point using a ray , and you will see the problem :)

![pivot](https://user-images.githubusercontent.com/18662417/77901580-1dd37880-7280-11ea-908b-82d96f082790.jpg)

**Comment by earthling45** [comment]
Preben, thank you so much for taking the time to check it out.
I'm going to change the .x file. :)

Much appreciated, thank you! this answer is going to solve problems for many i think.
