### ISSUE TITLE
Transparent glass conflict with water line

### ISSUE THREAD

**Issue by m2design** [TheGameCreators/GameGuruRepo#726]
Model with transparent window glass will not show the water plane when model goes below the waterline. everything is fine as long as the entity is above the waterline.

![Desktop Screenshot 2020 03 29 - 16 39 25 45](https://user-images.githubusercontent.com/33361413/77864225-44d86e80-71dc-11ea-82ec-9f7f28f3e100.png)
![Desktop Screenshot 2020 03 29 - 16 40 51 70](https://user-images.githubusercontent.com/33361413/77864233-4e61d680-71dc-11ea-80ae-cd8e458e4a8e.png)

**Comment by earthling45** [comment]
Last Friday, i was thinking about making the entity in two parts or have a base for the hut so that the entity which includes the glass stays above water.
I don't know if this approach is something you already apply, to your models but it can never hurt to share this idea. :)

**Comment by plemsoft** [comment]
@m2design Thanks for your issue,

Yes it is a problem , we can draw the water plane before or after the object. if we draw the water plane before the object , your able to see the object below the water , but are not able to see the water plane from within transparent objects inside the object. If you place a object below the water line then this mode is selected by GG , or if you use "transparency = 8".

The next option is to draw the water plane after the object, this way you will be able to see the water plane if you look out in a transparent area in the object , but if we do this, then you will not be able to see the object below the water ( like the problem you had last time and we added "transparency = 8") .

So its one of those , where it would be more simple to remove the glass and make it a separate object, The glass would then be above water and the object would be below , so everything would work.

This is just how transparency works in the GPU so there is nothing we can do , other then select one of the above 2 options, and they both have some kind of problem.

**Comment by m2design** [comment]
> Last Friday, i was thinking about making the entity in two parts or have a base for the hut so that the entity which includes the glass stays above water.
> I don't know if this approach is something you already apply, to your models but it can never hurt to share this idea. :)

Thanks, yes all of my models that are intended for water are on piers that I can adjust the height adjustment when placed in water. The transparency windows or part of the entity (not two entities)

**Comment by m2design** [comment]
> @m2design Thanks for your issue,
> Yes it is a problem , we can draw the water plane before or after the object. if we draw the water plane before the object , your able to see the object below the water , but are not able to see the water plane from within transparent objects inside the object. If you place a object below the water line then this mode is selected by GG , or if you use "transparency = 8".
> The next option is to draw the water plane after the object, this way you will be able to see the water plane if you look out in a transparent area in the object , but if we do this, then you will not be able to see the object below the water ( like the problem you had last time and we added "transparency = 8") .
> So its one of those , where it would be more simple to remove the glass and make it a separate object, The glass would then be above water and the object would be below , so everything would work.
> This is just how transparency works in the GPU so there is nothing we can do , other then select one of the above 2 options, and they both have some kind of problem.

plemsoft, Thanks for the reply. I totally understand the problem. I make good use of the transparency =8 setting for models placed on piers placed in the water.
