### ISSUE TITLE
EBE still has an small issue in the Bug free Update.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#727]
EBE  is just about there but has a new issue since update
Everything goes dark when you walk around 

Video Supplied
https://youtu.be/fuVBsTqcLqo
However after you Lightmap it looks fine

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting your issue,

This has been fixed for the next release :)

**Comment by synchromesh62** [comment]
Thanks Preben.
Your work is so much appreciated ..

**Comment by synchromesh62** [comment]
Confirmed now working :)
Thanks guys the ebe now seems very usable once again :)
