### ISSUE TITLE
3 Issues With Default Static

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#729]
1. If you have defaultstatic = 1 in your FPE, you will not be able to turn that entity until a dynamic from the editor. The toggle option will no longer be present in editor.

2 If you change defaultstatic = 0 hoping to then make your entities on your map dynamic or at the least grant the option to toggle within he editor, this wont be the case. All already placed entities will still be static with out the ability to change to dynamic. 

3. Any new object placed after you've made the FPE change for defaultstatic = 0 to allow for placing dynamic entities, you'll be able to place them as dynamic however not be able to turn them into static from the editor. The Option simply wont be there.

**To Reproduce:**
1. Create an entity or use an entity that has defaultstatic = 1
2. Place these static entities on your map and save the map
3. You will notice there is no longer an option to toggle default static
4. Change in FPE defaultstatic to 0.
5. Load your map, you will see all already placed objects are static and you will not be able to change them to dynamic.
6. Place the same entitity on your map from the library and they will be dynamic without the ability to change thme to static.

I noticed this issue didn't always used to be around, only up until a few years ago.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for your issue,

It will do this if the object has animations , then you cant toggle static and the object will always be dynamic.

I dont think this is a bug , as animated objects need to be dynamic ?

**Comment by LeeBamberTGC** [comment]
The software is not designed to manage changes to the FPE 'after' you use them in a level, but I will check this one out to see why it used to work years ago and no longer does.

**Comment by LeeBamberTGC** [comment]
@Teabone3 Just checked through your list, with the latest PP build scheduled to go out Friday PM:

1. I used the Blue Warehouse which has a defaultstatic=1 in it's FPE.  I can press the Y key to toggle between dynamic and static, and when I enter its properties the Static Mode property is editable:

![image](https://user-images.githubusercontent.com/35840583/78310746-c4e93600-7546-11ea-9824-c5579111ecb2.png)

2. This is the required functionality. The entity you place in the level will assume the static/dynamic state the FPE used at the time. Changing the FPE later on will not change the state of the entity in the level as this is stored as a per-entity property. You can of course delete the entity and select again from the local library (providing you exit the software and come back AFTER you change the FPE).

3. Looks like you are missing the STATIC MODE property, can you send me a screenshot of your entity properties for the Blue Warehouse building, thanks!

**Comment by LeeBamberTGC** [comment]
This issue cannot be reproduced, issue closed until more information can be sought.
