### ISSUE TITLE
Flashlight depends on surface Level ?

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#73]
why is the flashlight suddenly tied to the surface level ?

It was not like that in the previous PP.
Things like that ruin the visual setups of ppl's levels.
If it is possible, please change it back, or tell me why it behaves like that ;)

**Comment by Teabone3** [comment]
I think at some point we should completely re-haul the flashlight. One that references a PNG graphic would be nice.

https://www.youtube.com/watch?v=fzeEn7lsCOg

**Comment by Duchenkuke** [comment]
yeah that would be great. Make it more customisable.

**Comment by LeeBamberTGC** [comment]
Fixed for the next build so that flash lights are not influenced 'directly' by surface intensity. Also fixed issue of flash light not showing on terrain, related to an error in how terrain rendering got its cameraposition for light calculations.
