### ISSUE TITLE
Placing a soundzone (marker) crashes gg - March Version

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#732]
I am sorry to report but I had nothing but problems with the latest gg update.
I made a fresh install and manually copied over scripts and entities.
For 6 hours now, I have been trying to get the new version to work with my project.

I always get this issue when I want to place a soundzone. (when clicking left mouse button)

And no, I cant see any Log File.

![Unbenannt](https://user-images.githubusercontent.com/35990507/78107353-9ad42e80-73f5-11ea-9a09-b54a0f3189b6.JPG)

**Comment by Duchenkuke** [comment]
I validated my files via steam and that fixed it. But i wanted to avoid it because I have heavily modified the vanilla entitybank for my game. ( That's my fault tho, I know )

**Comment by LeeBamberTGC** [comment]
Glad you solved the issue. I have heard similar reports of Steam not entirely updating the product, and the advise of doing a fresh install often works wonders, but of course, backing up your hard work before hand is key!
