### ISSUE TITLE
Dragon enemy/asset crashes editor

### ISSUE THREAD

**Issue by PCVeteran** [TheGameCreators/GameGuruRepo#737]
Hello TGC team, I've ran into an issue when I was trying to use the dragon in the editor. The issue has the dragon enemy crashing the editor when selected by going to "Entity Library > Medieval > Dragons" then selecting the "Dragon" asset. I have no clue how or why this happens, but the asset crashes the editor after pressing Ok to select it for its use. If you need further information, on this matter, from my experience, I can be contacted at PCVeteran#1861 on Discord, where I am most frequent.

Regards,
-PCVeteran

**Comment by LeeBamberTGC** [comment]
Can anyone else confirm this bug report, I used the latest live build, selected the dragon, clicked OK, then dropped it into the level, then pressed TEST GAME, ran up to the dragon, everything is fine:

![image](https://user-images.githubusercontent.com/35840583/78280166-8df82d80-7510-11ea-84f9-d4e6d4d3de8f.png)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Just tested all fine for me. No crash or any problems noted.

**Comment by earthling45** [comment]
I also checked it but could select and place the dragon without any problem.

**Comment by Pirate-Myke** [comment]
Works for me.
https://puu.sh/FsFwx/1dcebe8f57.jpg
https://puu.sh/FsFwl/986dad704a.jpg
