### ISSUE TITLE
Firing the rocket launcher as 3rd person character freezes / stutters character movement

### ISSUE THREAD

**Issue by IvanErtlov** [TheGameCreators/GameGuruRepo#739]
Observed in: Mission Bug Free 31st of March

Description: Whenever a 3rd person RPG character fires his weapon, his movement becomes stuttering to frozen, while the framerate is constant. This effect disappears as soon the projectile is detonated.

Reproduction with stock:

1. Place player marker.
2. Place RPG Soldier on player marker
3. configure camera view to a higher top down view (300/500) 
4. Testrun game
5. Fire weapon and try to move

Repro Rate: 10/10

**Comment by LeeBamberTGC** [comment]
@IvanErtlov There was no RPG Soldier, so I selected Rocket Man, the 300 distance and 500 height is an odd configuration, but did test game as suggested. No stuttering, but the character will slow down when reloading the rocket, just as it does in FPS mode. Maybe post an FPM and video so I can reproduce much closer to what I did myself:

![image](https://user-images.githubusercontent.com/35840583/78282359-0dd3c700-7514-11ea-8aff-16c4017c7911.png)

**Comment by IvanErtlov** [comment]
@LeeBamberTGC Is it possible that the reload animation is not shown?

**Comment by LeeBamberTGC** [comment]
@IvanErtlov There is no reload animation in TPP. The only animations are movement and occasionally jumping. TPP support is limited. Do you still get the stutter in the latest PP build, and can you make a video of this bug, thanks.

**Comment by plemsoft** [comment]
@IvanErtlov In gameplayercontrol.lua

Change this block:

```
					if ( (GetGamePlayerStateGunMode() >= 121 and GetGamePlayerStateGunMode() <= 126) or (GetGamePlayerStateGunMode()>= 700 and GetGamePlayerStateGunMode() <= 707) or (GetGamePlayerStateGunMode() >= 7000 and GetGamePlayerStateGunMode()<= 7099) ) then 
						ttfinalplrspeed=ttfinalplrspeed*GetFireModeSettingsPlrReloadSpeedMod()
					end

```

With this block:

```
					if ( (GetGamePlayerStateGunMode() >= 121 and GetGamePlayerStateGunMode() <= 126) or (GetGamePlayerStateGunMode()>= 700 and GetGamePlayerStateGunMode() <= 707) or (GetGamePlayerStateGunMode() >= 7000 and GetGamePlayerStateGunMode()<= 7099) ) then 
						if ( GetGamePlayerControlThirdpersonEnabled() == 1 and GetGamePlayerStateGunMode() == 125 ) then
							-- No reload animation, allow walking at normal speed ...
							-- Prompt ( "mode=125" )
						else
							ttfinalplrspeed=ttfinalplrspeed*GetFireModeSettingsPlrReloadSpeedMod()
						end
					end

```

And tpp will walk normally while in reload animation :)

https://drive.google.com/file/d/1MPm73Abz2I42hryt747y1nAwNHKVy7tY/view?usp=sharing

@LeeBamberTGC As there is no tpp reload animation perhaps this would also make sense to add as default , it do look strange that they slow down and not doing anything :)

**Comment by plemsoft** [comment]
This has been fixed and will be in the next update.

**Comment by LeeBamberTGC** [comment]
New PP build uploaded to confirm this fix.

**Comment by plemsoft** [comment]
@IvanErtlov As you have not confirmed this fix , i expect that it is all working for you, if not just open a new issue , thanks :)
