### ISSUE TITLE
Flickering shadows when Entities are set on Medium

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#74]
Ok, I just started trying latest PP.

I run The Big Escape demo and found that shadows are "flickering" when moving, if you set Entities shader on Medium (and not on High).

Video:

https://youtu.be/Pj85RGqaeXU

**Comment by LeeBamberTGC** [comment]
Not reproducible on beta build for 10/04/18 - please verify this has been fixed.

**Comment by thecyrus** [comment]
I tried in the newest PP, and it didn't happen this time.

**Comment by plemsoft** [comment]
Tested in 14.04.2018 PP , seams to be fixed :)
