### ISSUE TITLE
AI pathfinding in building.

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#741]
Besides the problem with weapons, i've also read about problems with the AI and thus have made a building with the use of EBE in order to test it.
Here is the testmap with the building as i have set it up for testing.
[https://drive.google.com/open?id=1BbkXwbiJ79_V7u5JPAO6JAuX6tutjSwJ](url)

The AI seems to get lost and runs into walls, it could be that my setup is wrong, i've tried if laying down a path with waypoints would prevent the running into walls but it doesn't.
On ground level the soldier did very well but sometimes stopped moving forward for a few seconds.

https://www.youtube.com/watch?v=Di3dZ35Tq5E

**Comment by LeeBamberTGC** [comment]
@earthling45 A great little level and video, thanks for taking the time to demo the issue thoroughly!  I made my own version of the level (as the drive link did not work), and was able to make some fixes to the engine to shop shadowspeed optimization in TPP (as it flickers the shadow), and improved the AI to avoid 'sudden stop' you see when viewing the enemy from above, 

Also, you need to add a floorzone and connecting waypoint between terrain and floorzone area if you want enemies to follow you up stairs.  Apart from that, works nice now:

![image](https://user-images.githubusercontent.com/35840583/78316121-c589c880-7556-11ea-9d1a-e1c5752f0991.png)

**Comment by earthling45** [comment]
You mean the file was not downloadable?

But is is working really well with the latest PP as you can see. :)

https://www.youtube.com/watch?v=bii-QcHU6aU
