### ISSUE TITLE
 Build: april 7 2020 - Maximum Dynamic Lights - not working

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#745]
Hi all :)
Great work on the bugs people - thanks for hard work.

Reluctant to post this as you are no doubt very busy with getting MAX alpha out the door. But it may affect MAX as well so....

I posted a topic with regard to [Maximum Dynamic Lights](https://forum.game-guru.com/thread/221691#msg2628813) over on GG forums which was resolved with help prom Preben.

However with April 7 2020 build this is now almost completely non functional. 

Setting drawcalloptimizer=0 has no effect at all now.

I have updated the GG thread for more info.

Thanks for reading.

**Comment by plemsoft** [comment]
@michaeloldman Thanks for your issue,

1.
Try setting "drawcalloptimizeroff=1" in one of the red objects and let me know if that fix it.

2.
If possible generate a standalone of the level with the problem and e-mail me a link: plemsoft@plemsoft.com

3.
Try this attached version and let me know if that solves your issue.

[gg070420.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4442609/gg070420.zip)

**Comment by plemsoft** [comment]
Found your issue , please confirm using this attached version:

[gg070420-2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4442966/gg070420-2.zip)

**Comment by michaeloldman** [comment]
@Preben - well that was quick!

Copied those files over :)
Looks like windows is good at detecting overwritten exe's these days - which is a good thing. So when I first started the GG, Windows chimed in with a confirm to run the file dialog thing, which I did, and that caused the GG to go into 'resume previous session' mode. 

But after that it ran as usual and that fix did indeed sort the problem - awesome!

Thanks for you very speedy fix 👍

**Comment by LeeBamberTGC** [comment]
Latest PP build includes the above :)

**Comment by michaeloldman** [comment]
Hi Lee.
Just received b version. Verified all files to make sure. And all working again.
Thanks for speedy fix!

👍

**Comment by LeeBamberTGC** [comment]
No worries!
