### ISSUE TITLE
gameloop.lua corruption

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#746]
I am using official steam realease 2020.04.02 April Fixes and all files being verified by steam. gameloop.lua seems to be compiled before uploading rather than being editable. It may have been uploaded as the .exe version of gameloop.lua rather than non-compiled open lua code.

Can anyone check their gameloop.lua and confirm this is the scenario?

**Comment by AmenMoses** [comment]
Confirmed

**Comment by LeeBamberTGC** [comment]
Corrected for latest PP build just uploaded now. Need fix confirming, thanks!

**Comment by AmenMoses** [comment]
Fixed for me.

**Comment by sfkylcnky** [comment]
Many thanks for the fast fix! Can you mail me the lua please as I want to keep using the April Fixes release?

safak@chaos-design.net

**Comment by LeeBamberTGC** [comment]
Here you go:
[gameloop.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4463579/gameloop.zip)
