### ISSUE TITLE
ai_classiccharacter_apocalypse.lua issue

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#747]
Take for example German Zombie 6 from Classics\Characters\Zombie Apocalypse

Any time you kill the zombie it will jump on air after the death animation ends. Than it will die again. problem seems to be caused by the ai_classiccharacter_apocalypse.lua

**Comment by LeeBamberTGC** [comment]
Can you create a small FPM level with official media with a step by step to seeing the issue reproduce each time, thanks!

**Comment by sfkylcnky** [comment]
I randomly placed 3 characters that uses ai_classiccharacter_apocalypse.lua

Classics\Characters\Zombie Apocalypse\German Officer Zombie
Classics\Characters\Zombie Apocalypse\German Zombie 2
Classics\Characters\Zombie Apocalypse\German Zombie 3

kill the first zombie and wait until the death animation ends. It will repeat the death animation one more time. Same goes for other two zombies.

[test-zombie.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4460530/test-zombie.zip)

**Comment by LeeBamberTGC** [comment]
Fixed for next PP build this evening, added limbo state to scripts and updated engine to avoid playing CSI death animation if controlled entirely by script.
