### ISSUE TITLE
Classics Viral Outbreak Characters revives after death

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#748]
Following lua have problems on death of the characters:

ai_classiccharacter_decayed.lua
ai_classiccharacter_grendel.lua
ai_classiccharacter_pincher.lua

Kill any character that uses the given 3 lua commands. Take Decayed 2 Grendel 2 or Pincher 2 as an example. After killing these characters move very far away until you can see them rise from the dead. After they revive if you shoot them again they keep bleeding and keep their idle animation but they won't die or attack.

**Comment by sfkylcnky** [comment]
Following zip contains a small fpm and a sample video I took with my phone.

[bugvideo.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4460629/bugvideo.zip)

**Comment by plemsoft** [comment]
@sfkylcnky Thanks for reporting this,

To use these old scripts , you should set Always Active to "Yes" like this:

![alwaysactivwe](https://user-images.githubusercontent.com/18662417/80206381-7ce09f00-862c-11ea-8cad-f112c078c1fb.jpg)

These scripts need this to function like they was designed  :)

Hope this solves your issue.
