### ISSUE TITLE
Easter Pack character error

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#749]
Problem is caused at the characters that use the following lua

fast_enemy.lua
poison_flower.lua
poison_flower_walkable.lua

Take for example Poison Flower 02 (Walkable) from Easter Pack. Place the character and try starting the test game in the editor. You will get the following error and the characters will stuck in their idle animations:

![poison_flower](https://user-images.githubusercontent.com/37545408/78679103-7941de00-78f2-11ea-8240-e9a4c147317b.jpg)
 
Which can be rectified by commenting out the following line at the related luas:
eggradar_addEnemy(e)

**Comment by plemsoft** [comment]
@sfkylcnky Thanks for reporting this,

This has been fixed and will be in the next update :)
