### ISSUE TITLE
Default Sword does no damage

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#750]
Use the default Sword under the Weapons directory. Try killing any character by hitting their body.  No matter how many times you hit the enemy or the enemy's health, you can't kill with the sword. Except if you headshot, then they will die.

**Comment by sfkylcnky** [comment]
Problem can be rectified if the following line added at the related gunspec.txt

damage         = 50

gamecore\guns\medieval\Sword\gunspec.txt

**Comment by plemsoft** [comment]
@sfkylcnky Thanks for reporting this ,

This has been fixed and will be in the next update :)
