### ISSUE TITLE
multiple crashes in editor and test game

### ISSUE THREAD

**Issue by bonesy23438** [TheGameCreators/GameGuruRepo#753]
found that with the new build the editor crashes in any mode plus in test game when adding skyboxes worked perfectly fine before april 07b build
https://youtu.be/YOxAY40e4BU

**Comment by bonesy23438** [comment]
have found the problem the texture names were too long on my custom models sorry for the inconvinience all is good

**Comment by plemsoft** [comment]
@bonesy23438 Thanks for getting back , could you let me know the filename used that produced this issue , and perhaps also the full path to the image, just want to check why this happened , thanks :)

**Comment by bonesy23438** [comment]
hi heres an example of the naming that was on the textures as i have multiple textures for the pbr
battlecruiser_color_uvmapped_DefaultMaterial_.png and the filepath is 
Files\entitybank\user\assetforge\battlecruiser i shortened the filename to battlecruiser_color.png and it didnt seem to crash straight away as before when i scrolled to the model in editor
