### ISSUE TITLE
gridmode ebe

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#756]
I've placed a new buildingsite in gridmode and made a simple building.
 When placing the roof entities also in gridmode, they are not aligned as you can see in the video. :)
https://www.youtube.com/watch?v=d8XmsRS9cq4

**Comment by plemsoft** [comment]
@earthling45 Thanks for reporting this.

Unfortunately the roof is not a pure 100x100 objects so will not align directly, the good news is that you can control this yourself , if you edit the setup.ini and change these to lines:

From:
defaultebegridoffsetx=0
defaultebegridoffsetz=0

To:
defaultebegridoffsetx=40
defaultebegridoffsetz=40

It will then align with the roof block.

Also the current defaults (defaultebegridoffsetx=0,defaultebegridoffsetz=0) is not setup to align to a normal 100x100 block , this has been fixed for the new release :)

**Comment by earthling45** [comment]
Thanks Preben. :) 

If the alignment with 100x100 is fixed it should be good.
