### ISSUE TITLE
Zombies do not work since the last update ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#759]
It would seem Zombies do not work since the last update ?
Havent labeled it as a bug yet until I can get solid confirmation.
Now confirmed..

**Comment by Pirate-Myke** [comment]
I can confirm this error also. see video.

https://youtu.be/Oit8iZZtM3M

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
You know I hate to say it but do zombies really need to go via the Combat Core ? they just need to wander and kill you :)
I have attached 2 standalone scripts created by Smallg which work with this current build.
They wander until your detected, They also follow waypoints and die correctly and they also work in Co-op, MP. Could be worth a test to see what you thing :)

[zombie-waypoint.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4465708/zombie-waypoint.zip)

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this,

This has been fixed and will be in the next update :)

Im not sure about adding the other scrips thats up to @LeeBamberTGC , but the GG scripts will now also work with zoombies.

**Comment by synchromesh62** [comment]
@plemsoft 
Awesome thanks.
Yes the priority was to get them fixed and the additional scripts were a secondary consideration but they do give an enhanced experience even making your own level because they wander and you never know when one is right behind you :)
