### ISSUE TITLE
standalone not working as test mode

### ISSUE THREAD

**Issue by Grogadog** [TheGameCreators/GameGuruRepo#761]
No need for code with this one, 
I built a simple cube with ebe
I placed a weapon on top of the cube (mace)
I put the start on top of the cube,
ran in test mode, it was there available for pickup. 
made standalone
mace not visible, but message saying available for pickup.
and can pickup.
Most disconcerting as I have built a level for my game around an elaborate ebe, and I want to put weapons visible for pickup. anyone else having this problem

**Comment by Grogadog** [comment]
Decided to check this again this morning.
![weaponNoFlailbeforetest](https://user-images.githubusercontent.com/42348288/79681611-8aa0b980-8213-11ea-9459-ccc429f9d08f.jpg)
![weaponNoFlailDuringtest](https://user-images.githubusercontent.com/42348288/79681613-8bd1e680-8213-11ea-90cf-0f2533110b33.jpg)
![weaponNoFlailStandalone](https://user-images.githubusercontent.com/42348288/79681614-8c6a7d00-8213-11ea-9749-17d8f4f8b0f2.jpg)

After testing all the weapons I could find all the ranged weapons worked perfectly, all the hand weapons did not. as the three images show (I used the flail as an example), the flail was not visible in standalone, but was available for pickup.

**Comment by Grogadog** [comment]
last image red because I stepped on a proximity mine as I went to get screenshot, doh!

**Comment by Grogadog** [comment]
Done further testing, and attached the flail(spawn at start - no) to a key and, and set activate if used.
worked perfectly in test mode, but in standalone it was not visible, but pickupable, when picked up appears in your hand!!

**Comment by Grogadog** [comment]
although I discovered this fault when using ebe building. It is just the same in open terrain.
![Flail1 properties](https://user-images.githubusercontent.com/42348288/79682261-95118200-8218-11ea-9836-ac99d30abbba.jpg)

**Comment by AmenMoses** [comment]
Turn off occluder and occludee settings to see if that makes a difference.

**Comment by earthling45** [comment]
This is the same old problem as ever, textures not copied over while creating a stand alone file.
If you copy the required texture to the folder files/entitybank/weapons in the standalone directory, the weapon will be visible.

**Comment by Grogadog** [comment]
Thanks earthling45, will try that at some stage, I just worked round it.
If anyone would like to try what I've done in less than 4 weeks I put a download on my website.
but I dont know if I am allowed to put the link here
cheers

**Comment by Grogadog** [comment]
Tried it, worked, easy. opened two folders in windows, one showing the contents of  'entity bank > weapons' from the new standalone game  'Files' folder
the other showing same folder but from 'Game Guru > Files' folder.
If the item was sword then simply copied across 'Sword.X' and 'Sword_D2.dds'. 
ran the *.exe. and the swords were there to pickup. Cheers

**Comment by Grogadog** [comment]
missed out 'weapons' folder doh! to  both.

**Comment by earthling45** [comment]
You best keep it open i think so Lee and his team can make the required changes.
Doing it manually means that these files are not encrypted as they should be.

You might also want to read this i think. :)
[https://forum.game-guru.com/thread/220545](url)

**Comment by Grogadog** [comment]
Hi earthling 45, thanks for link to thread, I am sure it will be very
useful.
Just one double barrel question if you dont mind.
I realised after making the first level of a game that the
scriptbank folder is not littered with extra lua files that I save after
altering the defaults, so they would work how I wanted.
So now with level two of my game have made a folder specifically for my
altered lua files. i.e. scriptbank//castle2.
the question is will I need to add this to a '.fpp' file. And unless I am
missing something, or just dont know, where do you store the .fpp file
Cheers. Keep safe!
Grogadog
(my old world of warcraft name lol)
mobile 07789 704104
