### ISSUE TITLE
GG Classic - Startup Issue

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#763]
Hey all - thanks for hard work :)

Just wanted to report an issue when starting GG.
When starting GG, most times I get at least 10-30 seconds of black screen in the editor area, before it eventually loads the startup logo window. 

Occasionally it will not go past the black screen - so have to kill GG with Task Manager.

And on rare occasions it will load the intro window almost immediately.

When it does load it all runs with out any issues, so just an annoyance at startup.

Have been experiencing this issue since 7b and is still a problem in current build.

Just FYI :)

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting this,

Could you upload a .log file when this happen, that would really help , thanks :)

**Comment by michaeloldman** [comment]
Hi Preben
yeah, I think you can just ignore this issue - the GG is innocent :)

Started getting warning signs yesterday, windows wanting to check drive every time I booted up, so put a new drive in and GG loads lightning fast now.

So that makes two SSD's in less than three years for me! Staying with the trusty old mechanical ones from now on.

Thanks for looking at my issue, and for all the hard work your doing :)

**Comment by michaeloldman** [comment]
OK so spoke too soon.
After installing all downloads from the store and whatnot, I do still get a black screen for about 10 seconds or so now.

Where do we find the log files?

**Comment by plemsoft** [comment]
@michaeloldman Edit setup.ini and set: "producelogfiles=1" , then run GG and it will produce the .log file, it will be called "Guru-MapEditor.log" , just post this log file here and i have a look :)

**Comment by michaeloldman** [comment]
@plemsoft 
Here ya go - thanks for looking into it :)

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/4538859/Guru-MapEditor.log)

**Comment by plemsoft** [comment]
@michaeloldman Strange it do not look like you got a 10 sec black screen , the log display you got a screen within 4 sec ?

I can see you got a gameguru-news-banner , that will extent the load time a little.

It looks like everything loaded within around 27 sec (if i take the new banner stuff away ) , i think this is normal in Classic.

Also looks like everything loaded as it should , did you have any issues after you changed HD where you had to use "Task Manager to kill GG" ?.

Could you try to make a new .log and record a video at the same time , so i can see how it looks on your screen , that would really help :)

**Comment by michaeloldman** [comment]
No, not had to use Task manager to kill it since putting new drive in.

Everything loads and works fine. Had a pretty long day today so off for some shut-eye, but I will make a video tomorrow so you can see what I mean.

Thanks for response :)

**Comment by plemsoft** [comment]
@michaeloldman Think i found your issue , what your seeing is when the backbuffer get resized , could you try this version and let me know if it fix your issue thanks.

https://drive.google.com/file/d/1S4TJrb4JsFGwq2cIfSmkPz1FO8Sbe837/view?usp=sharing

You should backup your "Guru-MapEditor.exe" before trying this :)

**Comment by michaeloldman** [comment]
@plemsoft 
Hi Preben, sorry haven't made video yet. I find that the load times vary quite a bit and did not have a lot of time to play today.

The above Map-Editor replacement loads a lot faster, but would need to test it over a day or so, to know if it is consistent or not. The problem is the replacement Map-Editor kills half the lights in the level now. 

So would obviously prefer to put up with longer load times of the current release.

**Comment by plemsoft** [comment]
@michaeloldman Good find , the increased lights was not enabled in the new build. please try this version and let me know if everything is fine, thanks :)

https://drive.google.com/file/d/1b_4ygycN-fjIjzhoiN-Btw41mDWZadrq/view?usp=sharing

**Comment by michaeloldman** [comment]
@plemsoft 
Hi Preben, yeah that one works fine :)
I will test it over the course of today and let you know if it is consistent.

Thanks

**Comment by michaeloldman** [comment]
@plemsoft 
Hi Preben, so after a few GG starts through the day I can say the issue is still hit an miss.
The first two or three starts exhibit the behavior in this video:
https://vimeo.com/413534249

After the GG has been loaded a few times, it will then load fast evey time after that - like up and ready to use within 4 or 5 seconds.

All Windows 10 updates, and NVIDIA graphics drivers are up to date.

**Comment by plemsoft** [comment]
@michaeloldman Please also post the .log when you get that long delay :)

**Comment by LeeBamberTGC** [comment]
@michaeloldman Thanks for the video, really helps. I will be uploading a BETA/PP soon which you can try out as it will hopefully speed things up for you!

**Comment by michaeloldman** [comment]
@LeeBamberTGC 
@plemsoft 
Hi Lee, Preben, yeah that works great :)
Got the update, verified all files via steam, rebooted system - loads quick, and all works as expected.

Thanks for your hard work, and an awesome engine....

**Comment by LeeBamberTGC** [comment]
I am about to update the changes to BETA and PP from Preben's hot fixes so will close this in anticipation that all is well :)
