### ISSUE TITLE
chars entity do no damage

### ISSUE THREAD

**Issue by Grogadog** [TheGameCreators/GameGuruRepo#765]
In the video all the chars are from 'characters medieval' and have ai_fantasycharacter.lua is their 'main' script. they chase you but do no damage, please help as I want these chars in a level
[charDoDamage.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4505307/charDoDamage.zip)

**Comment by Grogadog** [comment]
if I attach a .lua from classics, - ai then at least they do damage but the animation is not correct

**Comment by plemsoft** [comment]
@Grogadog Thanks for reporting this,

Just tried the same as in your video , but it all worked fine here ? , did you modify "ai_fantasycharacter.lua" or anything else ? , if not could you post the .fpm that have the problem here , and i will try that , thanks :)

**Comment by Grogadog** [comment]
Will try on a clean installation on my laptop and get back, I could have tampered with the lua in my early ignorance, cheers. Steve

**Comment by Grogadog** [comment]
Just tried, the fantasy chars work, I must have corrupted the ai file,
copying files across from  laptop.
SOOOO sorry my bad.
Are there any ranged baddies in medievil chars. cant find on? Cheers and
many thanks
Keep safe,
Steve

mobile 07789 704104

**Comment by Grogadog** [comment]
still not copied over yet, takes a while, in the meantime here is the fpm,
which might show up something else I have done wrong, thanks
Steve

mobile 07789 704104

**Comment by Grogadog** [comment]
the copied over files work again soooo sorry
Steve

mobile 07789 704104

**Comment by plemsoft** [comment]
@Grogadog Thanks np :)
