### ISSUE TITLE
FBX INGAME BUG !

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#769]
Hi when i import from 3DS MAX my object in GG it WORKS my object has multiple textures!
![IMPORTED_FBX_BUG003](https://user-images.githubusercontent.com/8946215/80578761-48445d00-8a09-11ea-953d-129f41586f37.png)
![IMPORTED_FBX_BUG004](https://user-images.githubusercontent.com/8946215/80578776-4bd7e400-8a09-11ea-9a28-bad7a1b9e2f8.png)

When i paint the object in GG it works
![IMPORTED_FBX_BUG006](https://user-images.githubusercontent.com/8946215/80578821-598d6980-8a09-11ea-8039-d17db4b11114.png)

![IMPORTED_FBX_BUG006b](https://user-images.githubusercontent.com/8946215/80579437-5181f980-8a0a-11ea-8539-4b6f96e928ba.png)

But when i PLAY test the level it DOESN'T WORK !

![IMPORTED_FBX_BUG007](https://user-images.githubusercontent.com/8946215/80578895-7033c080-8a09-11ea-86b5-fa7ac0c2ff6e.png)

TEXTURES ARE GONE if i reload the level TEXTURES ARE GONE too !!

If i don't WANT collision BOXES & delete the collision box,  GG crash everytime !!!!
![IMPORTED_FBX_BUG005](https://user-images.githubusercontent.com/8946215/80579321-1ed80100-8a0a-11ea-8aa6-8f34808d91a7.png)

this is my fpe file
![IMPORTED_FBX_BUG008](https://user-images.githubusercontent.com/8946215/80580559-05d04f80-8a0c-11ea-91e0-72e7ddf5d7c1.png)

so i changed the fpe file names & the textures names and when i reload GG the TEXTURES are VISIBLE IN GG
![IMPORTED_FBX_BUG008b](https://user-images.githubusercontent.com/8946215/80582602-4a111f00-8a0f-11ea-8ded-53449293fd14.png)
![IMPORTED_FBX_BUG008c](https://user-images.githubusercontent.com/8946215/80582756-8cd2f700-8a0f-11ea-8a0d-2b2b756a57dd.png)

BUT when i start the game TEXTURES ARE NOT THERE !
![IMPORTED_FBX_BUG009](https://user-images.githubusercontent.com/8946215/80582842-b2f89700-8a0f-11ea-9243-9ce4b36bcc82.png)

I don't UNDERSTAND what is this problem !!!

**Comment by plemsoft** [comment]
@imothep85 Thanks for reporting this.

Make sure all the textures is in the same folder as the flower01.dbo file.

Also you had "textured = 0" in your first screenshot this should be "textured = " when you use multiply materials.

Im not sure about the crash you get when removing the collision box how do you do that, you just need to set "collisionmode = 0" in the fpe.

Did any of this fix your issue ? if not please post your model here so i can test it, if you dont want to post it here you can e-mail it to me at plemsoft@plemsoft.com

Let me know :)

**Comment by imothep85** [comment]
when i put collission mode to none in gg & i delete the collision box, GG crash all the time, just that !

**Comment by plemsoft** [comment]
@imothep85 How do you delete the collision box ?

**Comment by imothep85** [comment]
In the options when you import an fbx in the collision box menu

**Comment by plemsoft** [comment]
@imothep85 OK could you e-mail me the model so im able to test it , thanks, plemsoft@plemsoft.com

**Comment by imothep85** [comment]
its the same with any fbx object

**Comment by plemsoft** [comment]
@imothep85 Thanks just tested and yes it do crash when you delete the collision box.

This has been fixed and will be in the next update.

What about your "texture" problem did you fix that ?

**Comment by imothep85** [comment]
for the textures i FIXED it by doing an unwrap UVW under 3ds max, and created 1 texture for my 3d plant & it works IN GG & when i start the level thahts good but NOW
i have the horrible BUG with the collisions boxe, i put everything at no collison
BUT the collisions with the character when i walk in my flowers are still there when i test the level !!!!!

![flower02_D](https://user-images.githubusercontent.com/8946215/80593828-22778200-8a22-11ea-90cd-19ab1d7b96c0.png)

**Comment by plemsoft** [comment]
@imothep85 Just edit your .fpe end set "collisionmode = 11" and make sure "defaultstatic = 1" and it will work fine :)

This has also been fixed and will be in the next update , so you can just select "no collision" and make sure "default static" is set to "yes" then it will do it for you in the importer :)
