### ISSUE TITLE
Sci fi pack model snapping is way off

### ISSUE THREAD

**Issue by honkeyboy** [TheGameCreators/GameGuruRepo#77]
As of the last update the sci fi model pack models snapping is way off for me can anyone corfirm this for me plz

**Comment by earthling45** [comment]
I've tried it with the interior parts and it seemed to be ok.
But, and this might be my old grumpy brain, i could not get the doors to open.

**Comment by honkeyboy** [comment]
Yeah the doors have a different script attached m8, the snapping issue seems to have cured its self for the majority so maybe just needs bedding in. so this post can be closed :)

**Comment by earthling45** [comment]
The script in the scriptbank is broken, Pirate Myke uploaded a working script which you can find [here](https://forum.game-guru.com/thread/214469).

**Comment by Duchenkuke** [comment]
many many items are broken with the snap mode... This does not apply to the sci fi model pack only ^^
