### ISSUE TITLE
FileIO lua bug?

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#770]
My game features a puzzle that is gradually solved across multiple levels. The player must collect 16 pieces to build a full image. Each time they collect a piece, a new part of the picture is revealed. 

It relies on two scripts. Firstly, each piece runs a script that uses the entity's health as a reference to what piece of the puzzle it is and registers if the player has picked it up or not. Secondly, a control script runs from a hidden object in each level that writes whether a designated piece has been collected or not to a txt file in scriptbank using the FileIO LUA commands. As a piece is collected, the text file is updated. The text file is what allows Game Guru to track what pieces have been collected in previous levels. Here is a video showing how it is supposed to work:
https://youtu.be/XHbFsXrSTtM

Since the most recent update, if I try to run the control script - the one with the FileIO commands -in a map, the framerate drops to 0. I'd say I get 1 frame every 30 seconds. Some sort of catastrophic memory leak or something?

Have you done something to mess about with the FileIO commands?

**Comment by AmenMoses** [comment]
Can you send me the scripts.

**Comment by AmenMoses** [comment]
Can verify that the scripts are fine, or rather that they haven't changed since I wrote them and they worked perfectly on the previous build.

**Comment by AvengingEagle** [comment]
Verified the integrity of my install but still the problem persists.

**Comment by LeeBamberTGC** [comment]
Any chance you can attach a small; script, an FPM, and a step by step what I do to see the issue, I can track the changes recently and determine what is causing your issue, thanks!

**Comment by AvengingEagle** [comment]
[picturepuzzle.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4562913/picturepuzzle.zip)

Try this. I tried to make everything stock but let me know if I've forgotten any of the media.
For me, it works in that it creates a new .dat file and writes data to it, but the problem is it doesn't stop writing that data, so very quickly it fills the .dat file with thousands, even millions of characters and bring Game Guru to a standstill.

**Comment by AmenMoses** [comment]
Just to add that I tried to replicate it here on a simple level and it worked perfectly so this is rather a weird one!

**Comment by tarkus1971** [comment]
I tried my custom save load variable scripts on a very simple level. It worked fine.... the correct number of variables written and loaded in, player position also saved and loaded in fine. I will test on my main project later and report back.

**Comment by plemsoft** [comment]
@AvengingEagle Thanks for reporting this,

I just tried it in the old version  , and it did the same (slow down). The problem is with the script , it keep calling "fe_setPiece" , the reason is that when you use Destroy( e ) then Ent.health will be set to 0 and your line "if fe_gotPiece( Ent.health ) then Destroy( e ) end" will not work as Ent.health is now 0.

To fix it change your "fe_collect.lua" to:

```
-- LUA Script - precede every function and global member with lowercase name of script + '_main'
local U = require "scriptbank\\utillib"

function fe_collect_init( e )
	Include( "utillib.lua" )
end

function fe_collect_main( e )
	if fe_setPiece == nil then return end
	
	local Ent = g_Entity[ e ]

	if Ent.health == 0 then return end

	if fe_gotPiece( Ent.health ) then Destroy( e ) end
	
	RotateY(e,50)
	
	if U.PlayerLookingNear( e, 60, 80 ) then
		fe_setPiece( Ent.health )
		PlaySound(e,0)
		Destroy( e )
	end
end

```

@AmenMoses @tarkus1971 You must really have some really fast SSD :) , try making a Prompt ( counter ) just before "fe_setPiece( Ent.health )" and you will see it keep calling it.

**Comment by AvengingEagle** [comment]
Thank you @plemsoft - much obliged! 
Strange how this issue never presented itself in any previous build...
