### ISSUE TITLE
EBE structures vanishes when closing the building editor.

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#771]
As stated in the title, when i close the builder editor the structure vanishes. :)
The alignment is ok with X and Z on 50.
In order to prevent future issue reports, isn't it handy to have it set to 50 by default in the setup.ini?

**Comment by synchromesh62** [comment]
Confirmed ..
Something seems to have broken a lot of stuff that was fixed  :(

**Comment by plemsoft** [comment]
@earthling45 Thanks for reporting this , this has been fixed and will be in the next update :)

setup.ini was changed in the repo to 50,50 guess Lee did not spot it, i e-mail him.

@synchromesh62 Yes this update will have small issues popup like this , @LeeBamberTGC did some amazing work in the repo that define how we work on all products in the future including Classic, im sure he will update all about this. This was a needed step but also one that required changes in nearly ALL source files. So while it might look like a smaller update, behind the scene its huge, hope this explains it :)

**Comment by synchromesh62** [comment]
@plemsoft 
Oh I can see both you and Lee have put loads of work in to GG behind the scenes which is awesome so please dont get me wrong its really appreciated :)

I know ... I panicked :)

**Comment by earthling45** [comment]
Thanks Preben. :)
