### ISSUE TITLE
Model Dimming  

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#772]
I have some Drones in my levels both static and moving around 
Before this update they would also be illuminated .. Not sure what's going on here.
https://youtu.be/xDzCMyC681g

I also have one secondary issue that is used a lot in my game  " transportinzone.lua " 
This was directional ( you come out the same direction you go in ) so my levels have been created that way .. Now im bashing walls as if its reversed ..

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this,

If your using "apbr_anim.fx" and your object do not have any bones, consider it fixed.

If not please e-mail me the object so im able to test and see what the problem is , thanks :)
plemsoft@plemsoft.com

**Comment by plemsoft** [comment]
@synchromesh62 Fixed the transportinzone.lua issue, ready from the next update :)

**Comment by plemsoft** [comment]
@synchromesh62 Here is a update, let me know if it fix your issues , thanks :)

https://drive.google.com/file/d/1VVHYG5m8CrW6XrZoBSAG-wM1WRSc7-kk/view?usp=sharing

**Comment by synchromesh62** [comment]
@plemsoft 
Hi Preben 
Yes that WORKS great. Thanks so much that has saved me hours of work.
The model was made for me so not sure what it used :)

You didn't mention the " transportinzone.lua " problem but that also WORKS now :)
Could they have weirdly been related or did you fix that also ?

Either way many, many thanks.

**Comment by plemsoft** [comment]
@synchromesh62 Thanks , but i also wrote that i fixed the transport (see next post)  :)

**Comment by synchromesh62** [comment]
Whoops sorry Preben Missed that :)
