### ISSUE TITLE
cannot load any maps after update

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#773]
I have been creating a few new doors and made a map last night with just a door in it, this morning after the update i cannot load any maps GG goes into an endless loop :(
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/4562919/Guru-MapEditor.log)
[Guru-MapEditor-last.log](https://github.com/TheGameCreators/GameGuruRepo/files/4562920/Guru-MapEditor-last.log)

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this,

Did you save this map in Max at some point ?

**Comment by GraPhiX-Guru** [comment]
Hi Preben, no i did not, i do however have Max installed on another drive, it seems any model i have made in the past week causes the issue, give me your email and i will send you an asset that worked yesterday but not today

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks plemsoft@plemsoft.com :)

**Comment by GraPhiX-Guru** [comment]
thank you Files sent via we transfer

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks got your files.

Found the problem and fixed it, here is the update:
https://drive.google.com/file/d/1VVHYG5m8CrW6XrZoBSAG-wM1WRSc7-kk/view?usp=sharing

Let me know if it fix your issues , thanks :)

**Comment by GraPhiX-Guru** [comment]
Confirmed your fix works thank you very much :)
![snapshot5](https://user-images.githubusercontent.com/35724756/80797450-c6d00480-8b99-11ea-843a-c26f88e1c150.jpg)

**Comment by GraPhiX-Guru** [comment]
what was the issue ??

**Comment by AmenMoses** [comment]
Confirmed the fix works for me.  FLT level working again.

**Comment by GraPhiX-Guru** [comment]
thank you for the quick fix :) :)

**Comment by Teabone3** [comment]
I've been having this problem too with the latest update.
