### ISSUE TITLE
GG Classic character hair stays behind when put on map

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#776]
i have made a new map after the April fix with a new character and as soon as you put the npc down and they move the hair stays behind. also when you add a new script to the npc it happens again on the map. it looks like it only happens to the characters that has been made were you pick an extra head attachment like extra in hair at this point were you give the npc a new hair.

**Comment by plemsoft** [comment]
@Pcskiller Thanks for reporting this,

This has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment]
Uploaded as BETA/PP build. Please confirm the fix and we can close this issue,

**Comment by plemsoft** [comment]
@Pcskiller I assume this has been fixed , as i did not hear back from you , if you still have a problem, please just open a new issues :)
