### ISSUE TITLE
Breakable Wicker Basket - Explosion

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#779]
If you hit the barrel with a melee object it will explode and the player health will go to the negatives and you will not restart the level. You just remain dead with negative health.

Another issue is, why is the wicker basket exploding anyways? It makes no logical sense as its not a metal explosive drum.

It will sill explode if you do the following:
Even if you set the Explosion to "no" it will still explode
Also if you set Explosion damage to "0" it will still explode and injure the player.

My assumption was I'd be able to hit this wicker basket with a melee object and watch it break apart. Not explode like an explosive metal barrel.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue,

Your a scripter yourself and properly already know the answer :)

The script "graphix_explosion.lua" is what is generating the explosion. You can define the type of explosion you like by setting the "name" to the type of explosion you like , You can use "_exp1" to "_exp11" , and are also able to use "_imp1" - "_imp4" for different effects.


To make the player dead in the script search for "SetPlayerHealth" and replace that line with:

```
			local phealth = g_PlayerHealth - math.modf( damage * distMod )		
			if phealth <= 0 then
				phealth = 0
				SetGamePlayerControlDeadTime(Timer()+2000)
				g_PlayerHealth=0
			end
			SetPlayerHealth( phealth )

```

If you just want to see the explosion without getting hurt, just comment out or remove the line "SetPlayerHealth"

Its not really a bug but how the script was made. You could make a copy of the script and change it to act like you wish.

**Comment by GraPhiX-Guru** [comment]
@Teabone3 I will make an 'invisible' particle sheet and add it to the explosions folder so that you can still use the graphix_explosion.lua script all that would be needed as Preben has already mentioned is adjust the player damage so this will leave all the other effects in place 'physics' etc
