### ISSUE TITLE
EBE. Seamless textures are broken for EBE structures, GG Classic. Textures don't connect correctly.

### ISSUE THREAD

**Issue by janekste** [TheGameCreators/GameGuruRepo#782]
The seamless textures of EBE structures are broken. I don't know when it happened, but I only noticed it now. I started building an EBE house and saw it. Previously, seamless textures were connected correctly. Program version GameGuru 2020.05.05 - May Fixes, Publicpreview. Please fix this problem.
![image](https://user-images.githubusercontent.com/55485525/81395313-0fecff00-912c-11ea-8eaf-305a7be35b49.png)

Interestingly, the old EBE structures that I built a long time ago work correctly with seamless textures. There was no problem before. 
![image](https://user-images.githubusercontent.com/55485525/81395486-665a3d80-912c-11ea-8b98-0dda9adadd72.png)

One example of a seamless texture I attached to this theme.
[Seamless texture.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4598360/Seamless.texture.zip)

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 

Tested and Confirmed ..

**Comment by plemsoft** [comment]
@janekste Thanks for reporting this,

This has been fixed and will be in the next update :)

If you already have a ebe structure on your level that have this problem, after the next update: just select "edit" and save, to fix it on old levels/structures.
