### ISSUE TITLE
Multi-texture has issues with Draw Call Optimiser

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#783]
I noticed this awhile back but wasn't sure of the exact issue at first.
Multi textured objects do not texture correctly when close together (use the optimiser)
![texture_incorrect](https://user-images.githubusercontent.com/44620846/81423116-e80d9380-914b-11ea-973f-0af1c8a7fe9a.jpg)
When they are close the textures are not correct.
![texture_correct](https://user-images.githubusercontent.com/44620846/81423149-f6f44600-914b-11ea-8fed-318bc40e5651.jpg)
When you space them out so the draw call optimiser leaves them alone it looks fine, but of course slows down considerably.

**Comment by tarkus1971** [comment]
I have noticed this on some of kencharleslongs buildings, thought it was just texture error, but it looks like this was the problem. Good find.

**Comment by plemsoft** [comment]
@Retrogamebloke Thanks for reporting this.

Unfortunately its not possible, the optimizer cant batch object together that use different textures inside the different meshes , so in the first place it should never have been optimized.

This has been fixed , so it do not try to batch objects with different per mesh textures. Ready from the next update :)
