### ISSUE TITLE
Lightmapping causes door to jump to the left

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#785]
This is a peculiar one. Here is a static door entity I made a year ago. I carefully positioned it to appear open in this doorway. I'm using this entity a lot throughout my levels. In the editor, and in every test of the game until today, it looks like this:
![dooroffset01](https://user-images.githubusercontent.com/60984223/81975391-d716c380-961e-11ea-99a8-3a25213a1d09.jpg)

But as of today, the door has jumped a few unit to the left. 
![dooroffset02](https://user-images.githubusercontent.com/60984223/81975398-d8e08700-961e-11ea-8b1e-7a4e070e944a.jpg)

I have tested in the blank map and this only occurs once a level has been lightmapped. Interestingly, the collision still functions as if the door is in its proper position (i.e. you can pass through the left side of the door that sticks out where it shouldn't, and cannot pass through the area to the right where the door should be).

AE

**Comment by plemsoft** [comment]
@AvengingEagle Thanks for reporting this,

Its looks like the pivot of the object is causing this, are there anything special about this object ? , perhaps you could e-mail me the object so im able to test it: plemsoft@plemsoft.com

Or you could simple set the object to "dynamic" and it will also work, then the lightmapper will not touch it :)
