### ISSUE TITLE
New Update "May Fixes" causes testgamemode to crash again

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#788]
@Preben, you gave me an .exe file for the previous version wich fixed that issue - does that still work?
Or is the current exe needed for the improvements?

The Issue I have now is the same as in this post:
https://github.com/TheGameCreators/GameGuruRepo/issues/733

I will include a Log File too

**Comment by Duchenkuke** [comment]
[Guru-MapEditor-last.log](https://github.com/TheGameCreators/GameGuruRepo/files/4637955/Guru-MapEditor-last.log)

**Comment by Duchenkuke** [comment]
[Guru-MapEditor Log.txt](https://github.com/TheGameCreators/GameGuruRepo/files/4637957/Guru-MapEditor.Log.txt)

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this.

This has been fixed and will be in the next update :)

But your running on the limits on 32 bit with this level, so if you add more entities to the map you "might" run into the same again. Remember when running in the editor we use way more memory then running as standalone.
