### ISSUE TITLE
classic char unarmed brute, aggression not working

### ISSUE THREAD

**Issue by Grogadog** [TheGameCreators/GameGuruRepo#789]
unarmed brute from classic chars, does not attack. he will walk along a way-point track, and stand to look at you when in range but he does not attack, nor does he respond when attacked at close range. all the other classic chars I have checked work just fine. Is it a bug or just my system, tried it on new level with only that character. No lua changed or other entities in level.

**Comment by Grogadog** [comment]
[ai_classiccharacter_unarmed.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4642745/ai_classiccharacter_unarmed.zip)
the lua file from my scriptbank

**Comment by plemsoft** [comment]
@Grogadog Thanks for reporting this,

Its not a bug: Brute from classic , is not supposed to attack you , but only stare at you when you get close.

You can use the axe brute  if you want him to attack you :)

**Comment by Grogadog** [comment]
Thanks for that

mobile 07787 104849
