### ISSUE TITLE
Unlimited Dynamic Lights

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#79]
Now DX11 is progressing well, the lighting system would benefit from an overhaul, new flashlight, being able to alter its colour, brightness etc.

Dynamic lights which can be spot, flood, cone, movable via lua, and allow ONLY the dynamic lights to cast shadows when player is near them. The would enable the scene to look good and not have an entire level being shadowed by the sun. Being able to attach a dynamic light above the player, and move it with him would be amazing, Not like a flashlight more of an ambient aura of light.

**Comment by Belidos3D** [comment]
Yes please, we really need to at the very least triple the number of dynamic lights that can be active at once, the very low number we can have at the moment makes maps look odd with lights flickering on and off as you move about.

**Comment by honkeyboy** [comment]
Yeah agreed more a few more would be cool and or maybe auto fade so they dont just pop in and out might be a nice addition :)

**Comment by corrosionsting** [comment]
I want this too
