### ISSUE TITLE
Issue: Standalone Build Issue - Progress Pauses

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#791]
Whenever I am ready to build a game in Game Guru and I click build, the percentage of the standalone build process seems to only go up if the Game Guru program window is in focus. If you happen to switch over to another program like a browser, I noticed that the Standalone build process will not continue until you have the program window back in focus.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

This has been fixed and will now be able to run in the background, ready for the next update :)
