### ISSUE TITLE
Issue: Wizard Chararcter Thumbnails

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#792]
![wizards](https://user-images.githubusercontent.com/35990109/82397378-53921380-9a1e-11ea-925f-1835c89ca549.JPG)
For some reason, the Wizard Character Thumbnails are now all the same.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this.

Took my "old" dx9 version and checked, and they was also the same , so i assume they have always been the same ?

Anyway not really a bug , but how the artist have decided to present the wizard chars.

**Comment by plemsoft** [comment]
Forgot: If anyone got some better icons for the wizards , please post them here :)

**Comment by LeeBamberTGC** [comment]
NOTE: Thumbnails updated for clarity :)
