### ISSUE TITLE
Issue: Barrel Names

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#793]
Some of the newer barrels have a different name in their properties once placed in the editor, when compared to their Library name.

For Example, This "**Barrel (Wielded)**" is then called in the entity library, however once put into the editor and viewed from its properties its name is then "**_exp3**"

![barrels](https://user-images.githubusercontent.com/35990109/82397988-bdf78380-9a1f-11ea-9ca3-ec9732c3b2b8.JPG)

**Comment by synchromesh62** [comment]
This is not a Bug 
This is normal and I have tried to explain it on the discord 
"_exp3" is the name of the custom Explosion to use ( try _exp4 ) then shoot it .. in fact you can go up to "_exp11" Its all connected to "graphics_explosion.lua " which also controls the health everyone seems to be getting confused with.

**Comment by Teabone3** [comment]
Okay, good to know. As for some of us scripters we are using the naming within that field which can cause conflicts.

**Comment by Teabone3** [comment]
> The explosion health, radius etc is NOT set in properties its set in the "graphics_explosion.lua "

Sorry, I'm not sure what that has to do with this issue report. I understand how the internal script is working.

**Comment by Teabone3** [comment]
I'll close this issue. Some of us scripters like to use the global string variable of the "names". I can see that would cause a conflict with these particular items. Due to the nature of which the name field is being used in their native script.
