### ISSUE TITLE
Issue: Foliage - Bush 8 (animated)

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#794]
In the foliage folder Bush 8 (animated) is not set to immobile. 
If you place it in your map it fall fall and be pushable by the player and NPCs.

**Comment by mtrm92** [comment]
i dont have the problem with this bush

**Comment by Teabone3** [comment]
If you go up to the bush , you can push it with your player capsule.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this.

Just tried it and it works fine here , you cant move it and immobile is set to "off" by default , so i also dont see this problem ?
Could it be something else ?
