### ISSUE TITLE
Ray Cast not working properly on active entities + IntersectStatic doesn't appear to work

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#797]
In the video the entities on the left are all static, the ones on the right are all dynamic the crate has a script attached which raycasts N,S,E and W from the player position.

As can be seen the N & S dynamic entities only detect by the raycast when right in the centre of them whereas the static and W & E dynamic detect along the whole length.

The static entities all return the same object Id (85000) which I assume is because they have been grouped into a single draw call, so I have an extra call for them to the IntersectStatic function which I assumed would return the proper object Id but doesn't, so what is IntersectStatic for?

https://vimeo.com/423687613)

[raycast test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4697125/raycast.test.zip)

**Comment by smallg2020** [comment]
also getting the same thing here, if you watch the second half i swap to third person and you can clearly see the barrels i use to ray cast to, they only report the correct obstacle sometimes based on the camera rotation
[https://youtu.be/718m0VE-Dts](url)

[files.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4726344/files.zip)

**Comment by plemsoft** [comment]
@AmenMoses Thanks for reporting this,

This has been fixed and will be in the next update :) , if you use the draw call optimizer you can only use the IntersectStatic to check if you have a object in front of you or not, but not what object. to do that you would have to disable the draw call optimizer.

@smallg2020 Also tried your script and its also working perfectly now, thanks :)
