### ISSUE TITLE
Rastcast / IntersectAll Issues

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#800]
The raycaster with Intersect all for dynamic entities sometimes fails to return a collision if the player/camera is viewing various directions. Oddly enough the issue seems to be hit or miss. So its very hard to produce instructions on how to reproduce. 

My game project I have worked really hard is no longer something that can be completed due to this issue. As it relies heavily on the raycaster.

It seems to work perfectly fine with static entities however with dynamic it will return no collision sometimes from certain directions of the entity. Basically will return an object ID of 0 but in some angles will work but not others. The issue will als jump to a different entity leaving the previous one working as expected, if any property in the entity is changed.

[https://forum.game-guru.com/thread/221874](https://forum.game-guru.com/thread/221874)

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

This has been fixed and will be in the next update, looking forward to check out your dungeon crawler :)


Dup: https://github.com/TheGameCreators/GameGuruRepo/issues/797

**Comment by Teabone3** [comment]
Thanks so much for this one
