### ISSUE TITLE
Paste Sprite Issue

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#801]
I've been using paste sprite command for the cursor to move as the mouse cursor moves. I noticed however it lags behind as it won't calculate the point forms.

More on this issue can be read here:
https://forum.game-guru.com/thread/221929

As a workaround I'm now using Set Sprite Position which works as intended.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

This has been fixed and will be in the next update.

Thanks AmenMoses for finding and providing a bug fix :)
