### ISSUE TITLE
Non-accurate shadows from sloped surfaces

### ISSUE THREAD

**Issue by m2design** [TheGameCreators/GameGuruRepo#804]
I have not noticed this shadow problem before. See screen-shot. The tree base at the ground does not cast the proper shadow
![Desktop Screenshot 2020 07 01 - 14 53 27 07](https://user-images.githubusercontent.com/33361413/86295595-cfe64d80-bbab-11ea-96a2-3231800fb392.png)

**Comment by m2design** [comment]
![tree shadow](https://user-images.githubusercontent.com/33361413/86296933-e346e800-bbae-11ea-9564-8441fdcf777f.jpg)

**Comment by plemsoft** [comment]
@m2design Thanks for reporting this.

It looks like the sun position in your skybox, that are not fixed anymore, you can change the sun position in your "skyspec.txt" file, try to change to the "sunset" skybox and you will see the shadow follow the change, hope this info helps :)
