### ISSUE TITLE
Menu Music Slider ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#805]
Unless im missing something the Music slider doesnt change anything ?
It seems to be all locked into the sound slider.
I tried the official Ambience zone and using the musicinzone.lua but no response.

I havent labled it as a bug until im sure it is ?

**Comment by LeeBamberTGC** [comment]
This slider actually controls the internal music system (which is rarely used), but you can find the script here: scriptbank\music.lua

**Comment by synchromesh62** [comment]
Yep i figured i was missing something.
Thanks Lee but setting that up now for 15 levels is not really what i want to get into so i will just keep it as it is :)
