### ISSUE TITLE
Title.lua Issue referencing custom title.ogg (fix included)

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#809]
With Game Guru standalones we use the styles text file to reference custom folders for different title screen assets. However, while it does reference most assets properly in the correct folders it will not do so for the title screen music. Instead, it will directly point to the "default" folder's version of title.ogg and not the path of the custom folder stated in the styles file. 

To fix this in title.lua:

**LoadGlobalSound ( "titlesbank\\default\\title.ogg", 1 )**

should be changed to the following:

**LoadGlobalSound ( "titlesbank\\" .. g_strStyleFolder .. "\\title.ogg", 1 )**

**Comment by GraPhiX-Guru** [comment]
Hi Teabone3 :)
i noticed this a while ago, i never mentioned it because the default folder is always copied across in standalone no matter what you have in styles.txt so i had assumed default was required, in saying that Menu Creator does add ..g_strStyleFolder.. to the title.lua it creates.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this and providing a fix.

This has been changed for the next update :)
