### ISSUE TITLE
Issue: Custom Loadscreen Screen Cuts Off

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#812]
This is an issue not all will experience as I'm sure most people are not yet comfortable editing the title screen Lua files. However a few of us do, to add randomized backdrops during load screens and things like that.

I started using a system that will randomly display text tips on the loading screen. It actually works great. However I noticed once you exit back to the main menu and start the game a 2nd time, just below the Text the screen will cut through the background image and you will see an empty map in the background for the lower half of the screen, after about 50% of the loading process. 

I am unable to screen-grab this issue as it doesn't seem to let me capture that. What I could do if needed is take a cellphone photo of my monitor when the issue occurs or video.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this.

Not sure where to start with this one , could you make a small standalone that have this problem and e-mail me a link: plemsoft@plemsoft.com , please also include the .lua script that generate this issue not crypted, this way i can see/debug the problem, Thanks :)

**Comment by Teabone3** [comment]
Hey Preben, sending a standalone test that has this issue in it now. Sorry about the delay.

The file is in titlebank > peculiars > loading.lua

The line where the problem seems to occur is at:
TextCenterOnX(50,50,3,hint[rhint]) --shows your hint in the center of the screen

It works fine on first run of the standalone but if you go back to main menu and then click new game again you'll see a tear in the screen showing the map in the background of the loading screen.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for testing and confirming that this issue has been fixed , this fix will be in the next update :)
