### ISSUE TITLE
MAX [Alpha 5] Extract Entity Issues

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#817]
Hi team - awesome work so far, simply beautiful!

Couple issues with extracting entities:
1) Placing entity and then extracting: entity does not keep same height, will move to top of other entities. Not good for having interior and exterior of buildings as separate entities. 
- Example: sci-fi interior passage as one model, and outer hull as separate model.
- Example: Extracting lights for use inside a building
- Expected: Entity to keep same height when extracted.

2) Selecting Properties for entity in top down mode:
Hit G to put editor in top down mode. Select an entity, for example a light, click the properties icon in the right panel.
- Result: camera gets place over edge of map.
- Selecting an entity when camera is not in top down mode works fine.

3) Extracted entity moves under right panel (moving to mouse coords)
- Preferred: Entity to stay where it is when extracted.
- Perhaps something to look into for a work around at some stage :)

Can make video if you can't replicate your end :)

OldFlak....

**Comment by plemsoft** [comment]
@michaeloldman Tried all these they seams to be fixed now , also you now have "Extracted Y".

Let me know if any of these dont work for you in Beta3.
