### ISSUE TITLE
Gameguru Classic - .ogg sound files don't get encrypted when exported to standalone.

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#818]
Hey Team,

I would like this to be fixed because I want to protect my scratchmade media from being stolen.
As the title said, .ogg sound files don't get encrypted when exported to standalone. 
wav files are fine but I like to use ogg because it's size is smaller.

**Comment by qcrocknet2020** [comment]
I totally agree. This should be by default in MAX and Classic. OGG can easily be copied.
Thank you.

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this issue , .ogg has been added to the encrypter and will be available in the next update :)
