### ISSUE TITLE
Editor - Invisible Uber Solider 

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#82]
With a blank map and just a single uber solider , overtime between testing and returning to the editor, the solider will start to go invisible within the editor. Though if you move the camera around parts of it may appear while others disappear.

![dis](https://user-images.githubusercontent.com/35990109/36465589-d1361bca-16a3-11e8-8347-62044c2e6f4c.JPG)

**Comment by GraPhiX-Guru** [comment]
I have had this with most animated assets it is very random, my Mech Station also does it and its not a character
