### ISSUE TITLE
Camera Distance slider not working

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#822]
Mutliple Members of the Community have reported this issue now. The Camera distance slider does not work properly (sets itself to 100) even if it is set on a very low value.

Please fix it

**Comment by Duchenkuke** [comment]
https://forum.game-guru.com/thread/222168

I was able to reproduce the issue.

Check out the thread

**Comment by Duchenkuke** [comment]
I made a video regarding this issue:
https://www.youtube.com/watch?v=nGe2yRsEBSg

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by Duchenkuke** [comment]
awesome ! On behalf of all gameguru users:  Thank you very much Preben!
