### ISSUE TITLE
Max,Textures lighting from wrong side

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#824]
When I try to light s single skin level the textures light from the outside ,  put a light outside and the room lights up move the light inside and the room is dark .tried flipping normals with no luck 
![Doom Effort_016](https://user-images.githubusercontent.com/35897659/91965751-d8244b80-ed08-11ea-8966-a7dd7ee5b472.png)
Light inside
![Doom Effort_017](https://user-images.githubusercontent.com/35897659/91965786-e4100d80-ed08-11ea-8367-7e6c5f0b5493.png)
Light outside

**Comment by plemsoft** [comment]
@Granada1 Thanks for reporting this,

Try setting: "smoothangle = 101"
In the fpe and let me know if it fix your issue, thanks :)

**Comment by Granada1** [comment]
![smoothangle = 101](https://user-images.githubusercontent.com/35897659/92305518-08295400-ef80-11ea-8bd3-1b1e5ad67787.png)
That worked ,thank you. Had to shut down max to post as it keeps maxing out my CPU to 99% a few others are having the same problem

Windows 10 Pro 64 bit
GeForce RTX™ 2070 GAMING OC 8G 
AMD FX (tm)-9590 Eight-core Processor
31.96 GB RAM
3840 x 2160 ,60 Hz

**Comment by plemsoft** [comment]
@Granada1 Great , just to explain the problem , your model have inverse normals , FlipNormals in wicked only flip Y you still need to also invert X,Z , so properly when you export your model as .x , you should select "Invert Normals".

smoothangle = 101 , will just recalculate the normals and let them follow the triangles, so thats why it fix your problem.

**Comment by Granada1** [comment]
Thank you
