### ISSUE TITLE
RPG Rounds do not work in Standalone, fine in test game  (CLASSIC latest build)

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#825]
Previous build doesn't have this issue btw.

Drop a couple of RPG soldiers down, make a standalone and run it.  Player gets shot and killed as if by an RPG but no RPG round is seen and the sound effect is of a different weapon entirely (a pop gun maybe?)

**Comment by synchromesh62** [comment]
Tested and confirmed.,

**Comment by plemsoft** [comment]
@AmenMoses Thanks for reporting this issue, this has been fixed and will be in the next update :)
