### ISSUE TITLE
EBE Editor editing a second site, walls and parts are missing or not visible (Classic latest Build)

### ISSUE THREAD

**Issue by markfitz2014** [TheGameCreators/GameGuruRepo#826]
EBE Editor when saving an entity after editing a second site, walls and parts are missing or not visible (Classic latest Build)

I do not know if there is a height limit to editing on an EBE Site, but when i try to make a large hotel type building by using 4 ebe sites, i get missing parts on the second site some are walls some are the roof. Yet they are visible when editing just not after I save it and try to use in a level. The collision is there just not the visible entity parts. I am using standard. textures with Classic GG.

![EditMode](https://user-images.githubusercontent.com/14347431/92454090-0b0e8980-f1b8-11ea-92f0-309e399da488.PNG)
![Saved](https://user-images.githubusercontent.com/14347431/92454099-0e097a00-f1b8-11ea-857a-1916b7f5b207.PNG)

**Comment by plemsoft** [comment]
@markfitz2014 Thanks for reporting this issue.

I tried to reproduce it with no luck , it sound like you have a bad ".dbo" file. Could you try to load the ebe with the problems, and "edit" after that when your able to see that it looks correct, could you try to save it under a new name , and use that. Did this fix your issue ?

Thanks for your help :)

**Comment by markfitz2014** [comment]
Tried all that get the same results missing parts on the other ebe

**Comment by plemsoft** [comment]
@markfitz2014 Thanks , could you try to e-mail me the EBE buildings that have this problems so im able to test it, Thanks: plemsoft@plemsoft.com

**Comment by markfitz2014** [comment]
Sent email now. I have tried 3 or 4 times creating the second EBE site slightly different every time and completely from scratch on a new flat map. It is OK in "Edit Mode" just corrupts after saving. When you load the level map with the site's on the wall collision is there just no wall or roof prefabs in those areas. Strange!  I might be doing something wrong?  Spent way too much time trying to figure it out.

**Comment by plemsoft** [comment]
@markfitz2014 I checked your files , and yes you are hitting a maximum block numbers, there is a max block number to prevent the generated mesh for going over the limit , I have increased this so it goes to the absolute maximum , and your hotel now displays correctly.

This limit is only per material , so if you use another material your able to use the same blocks on the new material.

This has been fixed and will be in the next update :)

When you get the update , you should "edit" your structures and save , if you have the structures inside a "level" .fpm you should also save the level into a new name , after this your hotel will work.

**Comment by markfitz2014** [comment]
Thank you this will help a lot, thought I was doing something wrong as
there is no help or information on the details or specifications to what
the maximum number of prefab blocks can be used etc..
