### ISSUE TITLE
MAX and CLASSIC - Remove Preparing Core Files message?

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#828]
Can we please get the ability to remove the 'Preparing Core Files' message when loading a standalone game. As it is, the message simply detracts from a customized start screen experience.

Two options could be there for us:
- use a loading bar to indicate stuff is loading before going to the Title page - as long as we can fully customize it
- just have the ability to hide it all together

Thanks for considering.

OldFlak....

**Comment by fearlesswee** [comment]
I agree, the "Preparing core files" message is almost like the Unity splash in the way that it instantly creates a negative connotation in some peoples' minds. Removing it would be for the best in this regard as well.
