### ISSUE TITLE
Any chance we could have transparency with decals/particles fixed so it works properly?

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#829]
https://vimeo.com/457429501

Link is to a video with simple stock objects showing the problem.

**Comment by plemsoft** [comment]
@AmenMoses Thanks for reporting this issue.

It is the same problem as this:
https://github.com/TheGameCreators/GameGuruRepo/issues/722#issuecomment-605912425

The pivot of the "Glass Barrier.x" is not in the center , so GG cant sort it in the correct order.  The draw order of transparent objects need to be from the back (the object longest away from the camera) to the front, or the depth buffer will discard the pixel. This is not a gamegure problem but a problem that are in all engines, just the way the GPU works.

To fix it, you should move the pivot point in the object "Glass Barrier.x" so its exactly in the center. this way GG can order the objects in the correct order, it would be way to slow to add code to calculate the "real" pivot of the objects , as this need to be done for each object on each sync.

Check this image that display the pivot points, as you can see the "decal" that are not visible is actually closer to the camera then the "Glass Barrier.x".

![pivot](https://user-images.githubusercontent.com/18662417/98954259-e6a79400-24fd-11eb-99a4-86a4efbf0c25.jpg)


Hope this explains it. and sorry cant fix it, this is a artist thing :)

**Comment by AmenMoses** [comment]
Why is GG using the origin and not the object centre?  The object centre is already calculated isn't it?  (I added a Lua command some time ago that reads the objects centre GetObjectCentre which simply reads out already calculated and stored values)

All doors and windows and stuff in GG has the origin on one edge for positioning purposes, same as walls I believe.

**Comment by AmenMoses** [comment]
Btw, these aren't my models they are stock GG models, provided by GraPhiX I believe.  A lot of the stock models don't come with .X files so can't be edited by the users, so to my mind the choice3 comes down to either a) make a simple engine change to use the centre of the object in these calculations or b) trawl through how many gigabytes of models and 'fix' them.
I know which one I'd opt for.

**Comment by plemsoft** [comment]
@AmenMoses The center of the object is only calculated for the object bounding box , this do not account for rotation and scale, so you would also have to calculate this.

This is done on each sync for all objects, where the distance to camera is calculated, then this is sorted. if i also need to account for center of object and rotate/scale this point before calculating the distance , then levels with many objects would take a FPS drop.

Also this is ONLY a problem if you have a transparent object , with transparent objects inside, And only if the distance from the first object to the next is to close. If you moved the decals inside further away from the first object you would not notice this.

The community would not like a fps drop, so if this should be done, some speed from other areas would have to be found first.

**Comment by plemsoft** [comment]
@AmenMoses This has been added to the next update , this do not mean it solve all problems with this , but it works better, you will still see this issue , like if you have a very large glass object and smaller decals placed at the corners of this glass object, if this is the case the objects behind the glass will still be closer to the camera and the sorting would be wrong.
