### ISSUE TITLE
Standalone - missing entities ... files not getting copied over?

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#831]
I was doing a standalone test and saw quite a lot of missing entities in that particular level.

I check the folder and it seems the .x files are missing.

I am investigating that further.

**Comment by AmenMoses** [comment]
.x files are not copied over as the models use the .dbo files at runtime.

**Comment by Duchenkuke** [comment]
okay. The issue is still there tho.

**Comment by Duchenkuke** [comment]
I made some more research. I think the standalone has missing textures. Normal maps, specular maps, PBR and DNS.

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this issue.

Could you check if the missing Entity are missing some texture ? , im not sure what to look for here ?.

Or if you cant find it , e-mail me a link to the standalone , and let me know what entity do not display , then i can check myself. plemsoft@plemsoft.com :)

**Comment by Duchenkuke** [comment]
Hi preben, thank you for taking a look at the issues.

I just checked the folder for my standalone game. The texures for one of the missing entities there are (DNS)
In my standalone I have multiple missing assets that worked fine in previous gg versions like the tents from the stock buildings folder. 

Here, take a look at the folder:

![Unbenannt](https://user-images.githubusercontent.com/35990507/98989663-b37afa00-2529-11eb-826a-193f187dea88.JPG)

**Comment by plemsoft** [comment]
@Duchenkuke I can see that you have all the media in the standalone , so thats not the problem , could you try to run your standalone with "producelogfiles=1" in setup.ini , and when you run around and see that the "tents" is not there , quit and sent me the .log files here :)

You are properly running at the edge of available mem and perhaps that's the problem ?

Or if you sent me a download link to the standalone and let me know where on the map the tents is supposed to be , i can check it myself.

**Comment by Duchenkuke** [comment]
Hey Preben, I can send you a steam key. That would be the easiest way

**Comment by Duchenkuke** [comment]
please add me on steam and write me there for the key
The name's [GWINGA] Duchenkuke

**Comment by Duchenkuke** [comment]
@plemsoft or you can tell me your steam name ?

**Comment by plemsoft** [comment]
@Duchenkuke E-mail sent:

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for confirming the fix, this will be ready in the next update :)

**Comment by Duchenkuke** [comment]
awesome!
