### ISSUE TITLE
Draw Call Optimizer having problems with multi-textured entities

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#836]
Draw Call Optimizer still has a lot of trouble with multi-textured entities. 

![Desktop Screenshot 2020 10 19 - 00 09 05 99](https://user-images.githubusercontent.com/51464873/96404594-e509db00-11a0-11eb-997e-79b5a10a3938.png)
![Desktop Screenshot 2020 10 19 - 00 10 37 89](https://user-images.githubusercontent.com/51464873/96404601-e9ce8f00-11a0-11eb-82c9-a7b90439709a.png)

![Desktop Screenshot 2020 10 19 - 00 10 14 82](https://user-images.githubusercontent.com/51464873/96404607-efc47000-11a0-11eb-81d4-9fa9a5c5fb5a.png)
![Desktop Screenshot 2020 10 19 - 00 10 32 25](https://user-images.githubusercontent.com/51464873/96404613-f226ca00-11a0-11eb-9f81-c6bcf0845360.png)

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue,

Actually the draw call optimizer dont support multi-textured entities , it works by merging objects (and all included meshes) that use the same textures together. This cant be done on multi-textured entities.

It should already ignore multi-textured entities if you use the latest version , if you do and this one is not ignored, could you e-mail: plemsoft@plemsoft.com me the entity so i can test and made sure the DCO ignore this objects , Thanks :)

**Comment by Kitakazi** [comment]
Sent.

**Comment by plemsoft** [comment]
@Kitakazi Thanks , this has been fixed and will be in the next update :)

Until then, you can add this line to your objects fpe:

drawcalloptimizeroff=1

And they will also work.
