### ISSUE TITLE
Shadows flickering when shots fired.

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#837]
Look at the video and look at the shadows when the player fires a weapon.
This is a gameguru issue for a long time. Please fix it.

This also applies to singleplayer and standalone projects.
https://www.youtube.com/watch?v=KGnTB_zCepw&lc=UgxuAmiZ7r1gfaAZfJt4AaABAg

**Comment by plemsoft** [comment]
FYI: The muzzle flash "image" that are placed on the screen , was also displayed on the shadow cameras and blocking shadows. was a little hard to find :)

**Comment by Duchenkuke** [comment]
nice one! This was an issue for as long as I can remember 👍 
People will be very happy to see it fixed

Much appreciated Preben! Thanks for your work, it is a real blessing. Gameguru owe's you big time. And so do I.
