### ISSUE TITLE
Locked Entities After Test Mode Appear Visible Yet Still Locked

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#838]
If you lock an entity and then go to test game without unlocking it, when you exit test game, the entity will stay locked (despite being fully visible). It can however be unlocked by pressing SPACE however visually doesn't appear locked.

I'm assuming the best fix would be to make it once you exit (or start) Test Mode, all locked entities will be unlocked.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, This has been fixed and will be in the next update :)
