### ISSUE TITLE
GameGuru won't import mesh?

### ISSUE THREAD

**Issue by williamlionbear** [TheGameCreators/GameGuruRepo#839]
GameGuru is having problems with importing my mesh models, when I import the Engine resets the program and does this mosty of the time, its only now and again (rare) I get to import a model and then I can do the same process with other models which are simlar and the same, but it resets and starts the engine again?

**Comment by Duchenkuke** [comment]
this is not the gameguru forum. Post your issue there. Github is for bug reports only. Your issue could depend on the model you try to import.

**Comment by plemsoft** [comment]
@williamlionbear Thanks for reporting this , to see the issue i will need to model that have problems , you can e-mail it to me at plemsoft@plemsoft.com , and i will have a look :)

**Comment by plemsoft** [comment]
@williamlionbear Did not hear from you so assume the problem is solved, if you still have a issue please make a new issue and if possible please provide the object that crash the importer, thanks :)
