### ISSUE TITLE
Mutliple characters firing at the player will cause massive framerate drops and animation glitches.

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#841]
Title says it. Please look at the video I uploaded for this github bug report.
The framerate drops by a great amount if multiple enemies are firing with full auto weapons. 
All Animations like weapon and character animations are slowed down even tho the framerate is at 45.

https://www.youtube.com/watch?v=9wdzNg6RUms

Please check the other issues I posted also, they also need to be fixed for the christmas update.

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this issue, i have optimized it so its around 30% faster (when you have many characters firing), sent you a test version , please let me know if it fix your issue, Thanks :)

**Comment by Duchenkuke** [comment]
@plemsoft sounds great but I didnt receive the test version yet ?

**Comment by plemsoft** [comment]
@Duchenkuke Just sent you another e-mail :)

**Comment by plemsoft** [comment]
@Duchenkuke did the test version work better for you ?.

**Comment by Duchenkuke** [comment]
I will need to test it more, so far I have seen no real improvement.

I will try to record a new video today afternoon to see the exact difference to the previous video

**Comment by Duchenkuke** [comment]
I regret to inform you, that this issue still appears. Tested on the newest Version. I find github hard to keep track of the issues I posted so I forgot about this.

**Comment by Duchenkuke** [comment]
the bug applies to gg classic, not max

**Comment by Duchenkuke** [comment]
I will make a video, if that helps

After that I will try to replicate the issue with stock media
