### ISSUE TITLE
Opening the properties tab of an Entity causes the Entity to move. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#842]
This bug has been around for a very long time. It seems to only happen once I have a decent amount of entities in a scene, but I feel like it sometimes happens with smaller scenes. Either way once you hit a certain amount of stuff in your level the bug happens 100% of the time. It doesn't cause the entity to move very far but it moves enough to be a headache. 

To recreate:
Line up some entities perfectly then click on and open the properties panel. The entity should no longer be aligned. 
I have attached a video of the bug happening to me to show what I mean. 

https://www.youtube.com/watch?v=KH3ThQLT1lo

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue ,

This has been fixed and will be in the next update :)
