### ISSUE TITLE
Crouching under Entities then releasing crouch gives the player full move speed, while they are crouched.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#843]
Crouching under an object then releasing crouch gives the player the walk speed of standing, and even allows them to sprint. Even though they are still crouched. Even allowing the player to sprint full speed while maintaining crouched position. 

Crouching under or in an object such as a ventilation shaft and then releasing the crouch key should keep the crouched move speed. 

In this video you can see my move speed crouched when I am holding "C" and then when I let go of "C " my move speed increases. 

https://www.youtube.com/watch?v=pWT9DgTWadI

**Comment by plemsoft** [comment]
@Kitakazi Thanks for reporting this issue,

Im not sure if this is used as a feature in some other games, if you had a very long cave you need to move inside ?

But its a pretty easy to change:

in lua script 'gameplayercontrol.lua' change this line:

"if ( GetGamePlayerStatePlayerDucking() == 1 ) then "

to:

"if ( GetGamePlayerStatePlayerDucking() >= 1 ) then "

Thats it , let me know if this solves your issue , thanks :)

**Comment by Kitakazi** [comment]
Yes it solved my issue. Thank you.
