### ISSUE TITLE
Settings Panel - Specular no effect

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#844]
Adding an entity to a level, for example a boulder/rock if i go to the properties of the entity and adjust the specular value it as no effect, normally increasing the specular value gave the entity a 'wet' look

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this issue,

Specular is tied to PBR specular for a more accurate specular effect:

https://github.com/TheGameCreators/GameGuruRepo/issues/490#issuecomment-604850963

**Comment by plemsoft** [comment]
Dub already answered in other issue.
