### ISSUE TITLE
Path cannot be found [GG Classic - 2020 Christmas Fix] - [SOLVED]

### ISSUE THREAD

**Issue by MadLadDesigns** [TheGameCreators/GameGuruRepo#846]
Every time I try to run GG Classic (xmas edition 2020) I get the following error:

"Path Cannot Be Found - Path:mega pack 1\--desert_pack--sky01"

![Clipboard02](https://user-images.githubusercontent.com/75511721/101231257-e97f4a00-36a1-11eb-868f-01a00cbe582c.jpg)

I click OK then get the following error:

"Runtime Error: 8003 ()"
![Clipboard03](https://user-images.githubusercontent.com/75511721/101231269-f8fe9300-36a1-11eb-9b63-930c62fc21f2.jpg)

I click OK and it then goes on to:

"Resuming Previous Session"

After which it throws up the first error again.

**Comment by synchromesh62** [comment]
Odd one ?
Just installed myself and loaded fine.
Could be worth running through a verify ?

**Comment by MadLadDesigns** [comment]
I did a verify the files, I also reset my machine AND uninstalled and reinstalled Classic but still the same error. :(

**Comment by MadLadDesigns** [comment]
Edit: I've uninstalled it using a dedicated uninstaller (which removes leftover files) instead of the Steam uninstaller... then reinstalled it and it now works. :)

**Comment by synchromesh62** [comment]
Awesome you got it sorted !!
