### ISSUE TITLE
Footfall sound

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#847]
Please give us a setting to adjust the PlayerFootfallSound with out compromising the volume for the rest of the entities
We need to adjust the player footfall sound for any material that the player is going to walk on.
at this moment the footfall sound is to loud when using with ambient sound

**Comment by Pcskiller** [comment]
Any feed ack on this please. we just had a update / bug fix but what about this one? please

**Comment by Pcskiller** [comment]
So will we be able to have the ability to control the footfall
sound volume or how is it going to work?

**Comment by LeeBamberTGC** [comment]
@plemsoft Can chime in, but I think the cleanest way is to have a new property in the Player Start Marker that acts as a modulator for the volume of player footfalls, so you can set the volume to 50% or 200% of the general sound effects volume. That should give you plenty of control. For per-material adjustment I would recommend customising this file and doing it there for super fine control: audiobank\materials\materialdefault.txt

**Comment by Pcskiller** [comment]
Ok cool. Thanks a lot.
Thanks for all the hard work.

**Comment by LeeBamberTGC** [comment]
@Pcskiller Added new Player Start Marker property called Footfall Volume, defaults to 50 and you can set it 0 to 100 to tailor footfall sounds to the rest of the soundscape.  Will be in March Fixes uipdate.

**Comment by Pcskiller** [comment]
Awesome, thanks for the update!
Thanks Lee I appreciate this a lot.

**Comment by Pcskiller** [comment]
working great. Thanks.
