### ISSUE TITLE
[GG Classic - 2020 Christmas Fix]  Lasso erratic trying to select entity 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#848]
Lasso erratic trying to select entity. Video Below
https://youtu.be/7UyiaJ1c5BE

**Comment by MadLadDesigns** [comment]
Is Classic set to full screen? Or are you running it in a window?

**Comment by synchromesh62** [comment]
Set to full screen. 
Waiting to see if anyone else has the same problem though but i have done the verify and reboot,
Still the same.

**Comment by MadLadDesigns** [comment]
I had the same problem in MAX when it wasn't full screen, just thought it might be that.

**Comment by Granada1** [comment]
Just tried sometimes it’s ok sometimes I get a box above the entities, bit random

**Comment by Teabone3** [comment]
Experiencing the same issues as above. Something is off with it. the more right you click the further the box appears to the bottom right of the screen.

**Comment by synchromesh62** [comment]
Ok so deffo something wrong so i will lable as bug
Thanks for confirming guys

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this issue , yes this was related to Max also, it has been fixed in both version Max and Classic :)

**Comment by bluemeenie195** [comment]
I'm still having problems with the lassoing of entities

**Comment by plemsoft** [comment]
@bluemeenie195 It will be included in the next update :)

**Comment by bluemeenie195** [comment]
Thank you
