### ISSUE TITLE
Black weird textures

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#85]
Getting black texture patches in ALL the buildings in Valuable Assets Buildings Packs, 1,2 and 3.

Latest PP Version.

![va texture errors](https://user-images.githubusercontent.com/36561118/36547641-4054f7f4-17e6-11e8-9491-cf55ff715d2f.jpg)

**Comment by Teabone3** [comment]
Do you know if those models are using multi-textures?

**Comment by earthling45** [comment]
These models have a texture atlas and are applied through the FPE.
Set pbroverride=0 in the setup.ini and those black spots are gone.
Preben has mentioned this on the forum.

**Comment by tarkus1971** [comment]
Im not using PBR in my current project, so I really need pbroverride=1, will there be a better bug fix for this soon, rather than using that method?

**Comment by GraPhiX-Guru** [comment]
hi tarkus1971 I think you are confused pbroverride=1 is default it forces everything to use PBR pbroverride=0 allows the old stuff to render non PBR (the way they use to look)

**Comment by tarkus1971** [comment]
Thanks Graphix, but does the illumination still work in pbroverride, I know it was not working in one of the modes. Maybe that's been fixed now. 

Thanks for the info guys.

**Comment by plemsoft** [comment]
Yes this is happening on many different objects also stock, i take a look.
