### ISSUE TITLE
Issue: Enemy Weapon Flak Stays After Test Mode

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#851]
If an enemy fires its weapon, the flash decal will still be visible after exiting Test Mode. 

This is not a huge issue as when you Test Game again the decal will be removed. Just thought I'd point this one out.

![newbug](https://user-images.githubusercontent.com/35990109/101819758-adaa1180-3af3-11eb-894e-1653caf463fb.JPG)

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, i tried it with a few weapons but with no luck , could you let me know what weapon produce this ? , thanks for the help :)
