### ISSUE TITLE
Issue: "Entity: None Selected"

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#853]
When an entity is selected in the editor, in the lower bottom of the screen the text will change to say "Entity: None Selected"

This also means that the information displaying the Entity ID and Object ID disappears once selected.

**Comment by LeeBamberTGC** [comment]
K has fixed this, should be in next update March time :)

**Comment by plemsoft** [comment]
@Teabone3 Thanks , added extras info so it also display what entity and objects id is selected when your using the widget.
Ready from the next update :)
