### ISSUE TITLE
Issue: Trigger Zone Cannot Be Accessed or Moved

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#854]
What happens is a trigger zone will suddenly lose its inner circle graphic and once that happens you cannot select the Trigger Zone. You also cannot select its points. No matter what angle you look at it from.

The cause seems to be possibly related to when the zone points start stretch when moved on top of tall entities.  Even if you were to select over the entire trigger zone you will not be able to select it.

![trigger zone](https://user-images.githubusercontent.com/35990109/103193080-3a511f80-48a9-11eb-8daa-70550a4160a7.JPG)
![bug](https://user-images.githubusercontent.com/35990109/103193081-3ae9b600-48a9-11eb-9ae9-483b82932e7d.JPG)

I tried including the FPM ZIP here but its over 100MB even with nothing left on the map... so I've uploaded here for download:

[http://www.tyronemw.com/Trigger_Zone_Issue.zip](http://www.tyronemw.com/Trigger_Zone_Issue.zip)

**Comment by Teabone3** [comment]
For those also experiencing this issue, there is thankfully a fix for it! You hold shift and click one of the star points and it will delete the trigger zone. So while you cannot click the trigger zone in any way or move its points, you can delete one point to remove the buggy trigger zone.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue ,

This has been fixed and will be in the next update :)
