### ISSUE TITLE
Issue: Lightray inprints entities in sky?

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#855]
Noticed an odd visual issue with the Lightray tab slider. It will put bleached outlines of objects in the scene into the sky, mirrored, when I look up. 

![tree_sky](https://user-images.githubusercontent.com/35990109/103241438-352fb700-4921-11eb-9474-5adc6a6580a5.jpg)

I believe this may actually be an intentional visual feature, but it does look rather odd.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue ,

This would happen, if the light ray length is to small , could you try to increase the "Lightray length." and check if that fix your issue, thanks :)

But yes the settings quality/speed of the shader decide how good this effect is, and it will produce these kind of artifacts when the settings is set to low, we could increase the number of samples this effect use but it would have a speed impact, so if you could try and see if your able to fix it using the current settings available it would be great.

**Comment by Teabone3** [comment]
I've maxed out the lightray settings and while its still there, its less noticeable as being a silhouette of the trees. Could say increasing the length indeed may it look better

![tree](https://user-images.githubusercontent.com/35990109/110071540-37abf400-7d4a-11eb-88fb-7aeadeea2515.jpg)

**Comment by plemsoft** [comment]
@Teabone3 Found a problem with the shader and fixed it, will also fix the issue with object placed wrong like in your first screenshot :)
