### ISSUE TITLE
Issue: RotateObject and MoveForward

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#856]
With Lua, if you try to set the rotation of an object using a command like RotateObject(obj,x,y,z) and then use MoveForward(e,#) The character will not actually move forward, because only the visual entity mesh has rotated apparently not its collision mesh.

The collision mesh does rotate however if you use commands such as: RotateX(e,#), RotateY(e,#), RotateZ(e,#)

I should note that this is happening with Characters (ischaracter = 1) and I've not tested with other types of entities.

**Comment by LeeBamberTGC** [comment]
Are these commands not for non-character entities?

**Comment by plemsoft** [comment]
@Teabone3 I think i answered this somewhere else ? , anyway you should not mix direct object commands and entity commands, entity commands also rotate the internal variables for the entity, and it is this data that are used by "MoveForward(e,#)" that are also a entity command. So just use RotateX(e,#), RotateY(e,#), RotateZ(e,#) and everything will work :)
