### ISSUE TITLE
Issue: Timer Runs While Not In Test Mode

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#857]
I am not sure if this is intentional or not but for those using GetTimer(e) they may notice that when you leave Test Mode it actually does not reset back to 0. Infact the timer seems to actually start as soon as you launch Game Guru's editor.

The work around is using StartTimer(e) in the initialization function of any entity that has "if GetTimer(e)" in its main.

I may be mistake if this is an issue and just how the timer actually functions. In that case this report can be closed. It took me a couple years to realize the timer actually continues to count while only in the editor and even starts counting before any entity is placed.

**Comment by AmenMoses** [comment]
The timer is not really a timer at all, all it is is a wrapper function to access g_Time and returns the difference between it and the value it had last time you called StartTimer.  

So the question should be more like "should g_Time be reset to 0 for each test run?"

**Comment by Teabone3** [comment]
That's kind of what I'm getting at. I don't think it should be counting from where it left off. I think it should be set to 0 each time test mode is pressed.

**Comment by LeeBamberTGC** [comment]
Probably dangerous to change this fundamental functionality now. It pulls the value directly from the system timer.
