### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#859]
When using EBE, the zoom function (scrollwheel) does not work anymore.

**Comment by synchromesh62** [comment]
Scroll has only ever been for raising and lowering the floor level. Not zooming ?
 W and S keys for zooming in and out when using the EBE

**Comment by earthling45** [comment]
Ohh, i might be a bit rusty because i havent'used GG in a while. :)

I'll close this thread Synchromesh.
