### ISSUE TITLE
LUA - Skybox Changing

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#86]
This is an enhancement request. I'm wondering if it will be possible to change the skybox via LUA? Perhaps we would need to preload a series of skyboxes in LUA first then to call them similar to sprites with an index (1,2,3,4, etc)

2014 Request Video
[https://www.youtube.com/watch?v=lOe988NZSqg](https://www.youtube.com/watch?v=lOe988NZSqg)

**Comment by tarkus1971** [comment]
This would a great feature to have, especially if we had skyboxes, for say early morning, mid-day, late afternoon and nighttime, and had the ability to slowly set a fade amount between them, this could be a sort of realtime day night effect. Great thought Teabone.

**Comment by Teabone3** [comment]
That's the point :) I have everything i need for full day and night cycles except skybox changing and long waited particles system.
