### ISSUE TITLE
Game Guru Max crash

### ISSUE THREAD

**Issue by sirblockwood101** [TheGameCreators/GameGuruRepo#860]
installed latest Game Guru max beta and when trying to open program it just crashes to desktop no error!

**Comment by Granada1** [comment]
Need more info please , computer or laptop specs .graphics card etc

**Comment by sirblockwood101** [comment]
24gb ddr 3 ram,amd fx 8350 cpu,nvidia geforce gtx 750ti gpu windows 10

**Comment by synchromesh62** [comment]
That looks like it could be your problem right there **geforce gtx 750ti gpu**
The Minimum spec is a GTX 960.

**Comment by sirblockwood101** [comment]
great..thanks..friend wasted money..thanks again will have to tell him to get a refund

**Comment by DieHardCDN** [comment]
Lee, I have the same issue where the program crashes to the desktop without error.

These are my laptop spec's.

Operating System
	Windows 10 Home 64-bit
CPU
	Intel Core i7 @ 2.60GHz	58 °C
	Comet Lake 14nm Technology
RAM
	32.0GB
Motherboard
	Alienware Alienware m17 R3 (U3E1)
Graphics
	Generic PnP Monitor (3840x2160@60Hz)
	Intel UHD Graphics (Dell)
	4095MB NVIDIA GeForce RTX 2070 Super (Dell)	49 °C
	SLI Disabled
Storage
	953GB Micron 2300 NVMe 1024GB (RAID (SSD))
	465GB Crucial CT500P1SSD8 (RAID (SSD))
Optical Drives
	No optical disk drives detected
Audio
	Realtek Audio

**Comment by LeeBamberTGC** [comment]
Added additional info for when this happens again in the first build of 2021. We can then know more about this one.

**Comment by uboel** [comment]
Some more info:
- At first I installed GGM on my D: drive. I decided to uninstall it and try the installation on the default C: location. This didn't help.
- I'm running Windows Defender + MalwareBytes. I checked their logs...nothing about GGM is worrying them...
- I tried launching GGM as Administrator...it didn't help...

Here is what's shon in the Windows Event Viewer:

Faulting application name: GameGuruMAX.exe, version: 0.0.0.0, time stamp: 0x601d227e
Faulting module name: GameGuruMAX.exe, version: 0.0.0.0, time stamp: 0x601d227e
Exception code: 0xc0000005
Fault offset: 0x000000000038bf82
Faulting process id: 0x28e8
Faulting application start time: 0x01d6fe06f2d272a8
Faulting application path: C:\Program Files\GameGuruMAX\Max\GameGuruMAX.exe
Faulting module path: C:\Program Files\GameGuruMAX\Max\GameGuruMAX.exe
Report Id: d65fe7a4-e402-42d4-96d6-8db03ef98aa8
Faulting package full name: 
Faulting package-relative application ID:

**Comment by LeeBamberTGC** [comment]
Can you attach the file that may have been created here:

C:\Users\<yourPC>\Documents\GameGuruApps\GameGuruMAX

The file is "Guru-MapEditor.log" which holds a log of everything the EXE tried to do before it crashed. Let me know if you see this folder, and specifically this file, and if so, please attach it here, thanks!

**Comment by uboel** [comment]
Hi Lee,

Here is the file.

Cheers,

Ulric

**Comment by LeeBamberTGC** [comment]
That's great, points directly to the section "initbitmapfont".  Here is the function call and code:

void loadallfonts ( void )
{
	#ifdef WICKEDENGINE_PETEST
	// Uses truetype fonts, not old bitmap fonts
	#else
	image_setlegacyimageloading(true);
	for ( int c = 1 ; c < 8 ; c++ )
	{
		if (  ImageExist(g.bitmapfontimagetart+c) == 1 ) 
			DeleteImage (g.bitmapfontimagetart+c);
	}
	initbitmapfont("fontbank\\FPSCR-Font-24px",1);
	shrinkbitmapfont("fontbank\\FPSCR-Font-12px",2,1);
	initbitmapfont("fontbank\\FPSCR-Font-36px",3);
	initbitmapfont("fontbank\\FPSCR-Font-40px",4);
	initbitmapfont("fontbank\\FPSCR-Font-72px",5);
	initbitmapfont("fontbank\\FPSCR-Font-36px-Multiplayer",6);
	initbitmapfont("fontbank\\FPSCR-Font-25px",7);
	image_setlegacyimageloading(false);
	#endif
}

void initbitmapfont ( char* name_s, int index )
{
	int charindex = 0;
	float lastbh_f = 0;
	cstr char_s =  "";
	cstr line_s =  "";
	float bx1_f = 0;
	float bx2_f = 0;
	float by1_f = 0;
	float by2_f = 0;
	cstr png_s =  "";
	cstr txt_s =  "";
	float bh_f = 0;
	float bw_f = 0;
	cstr x1_s =  "";
	cstr x2_s =  "";
	cstr y1_s =  "";
	cstr y2_s =  "";
	int pos = 0;
	int n = 0;
	png_s=name_s;
	png_s += ".png";
	txt_s=name_s;
	txt_s += "-Subimages.fnt";
	if ( ImageExist(g.bitmapfontimagetart+index) == 0 ) 
	{
		LoadImage (  png_s.Get(),g.bitmapfontimagetart+index );
		OpenToRead (  1,txt_s.Get() );
		while (  FileEnd(1) == 0 ) 
		{
			line_s = ReadString (  1 );
			for ( n=1 ; n <= Len(line_s.Get()) ; n++ ) { if ( line_s.Get()[n-1] == ':' ) { pos=n-1 ; n=Len(line_s.Get()) ; } }
			char_s=Left(line_s.Get(),pos); line_s=Right(line_s.Get(),Len(line_s.Get())-(pos+1));
			for ( n=1 ; n <= Len(line_s.Get()) ; n++ ) { if ( line_s.Get()[n-1] == ':' ) { pos=n-1 ; n=Len(line_s.Get()) ; } }
			x1_s=Left(line_s.Get(),pos)  ; line_s=Right(line_s.Get(),Len(line_s.Get())-(pos+1));
			for ( n=1 ; n <= Len(line_s.Get()) ; n++ ) { if ( line_s.Get()[n-1] == ':' ) { pos=n-1 ; n=Len(line_s.Get()) ; } }
			y1_s=Left(line_s.Get(),pos) ; line_s=Right(line_s.Get(),Len(line_s.Get())-(pos+1));
			pos=Len(line_s.Get());
			for ( n=1 ; n <= Len(line_s.Get()) ; n++ ) { if ( line_s.Get()[n-1] == ':' ) { pos=n-1 ; n=Len(line_s.Get()) ; } }
			x2_s=Left(line_s.Get(),pos) ; line_s=Right(line_s.Get(),Len(line_s.Get())-(pos+1));
			for ( n=1 ; n <= Len(line_s.Get()) ; n++ ) { if ( line_s.Get()[n-1] == ':' ) { pos=n-1 ; n=Len(line_s.Get()) ; } }
			y2_s=line_s;
			charindex=ValF(char_s.Get());
			bx1_f=ValF(x1_s.Get());
			by1_f=ValF(y1_s.Get());
			bw_f=ValF(x2_s.Get());
			bh_f=ValF(y2_s.Get());
			if (  bh_f == 0  )  bh_f = lastbh_f;
			if (  lastbh_f == 0  )  lastbh_f = bh_f;
			bx2_f=bx1_f+bw_f;
			by2_f=by1_f+bh_f;
			t.bitmapfont[index][charindex].x1=bx1_f/(ImageWidth(g.bitmapfontimagetart+index)+0.0);
			t.bitmapfont[index][charindex].y1=by1_f/(ImageHeight(g.bitmapfontimagetart+index)+0.0);
			t.bitmapfont[index][charindex].x2=bx2_f/(ImageWidth(g.bitmapfontimagetart+index)+0.0);
			t.bitmapfont[index][charindex].y2=by2_f/(ImageHeight(g.bitmapfontimagetart+index)+0.0);
			t.bitmapfont[index][charindex].w=bw_f;
			t.bitmapfont[index][charindex].h=bh_f;
		}
		CloseFile (  1 );
	}
}

Do you spot anything that might cause a crash on your specific system?  Are you sure your fonts folder is not corrupted and all files being read aboive accounted for?

**Comment by uboel** [comment]
Under c:\Users\uboel\Documents\GameGuruApps\GameGuruMAX\Files\, I don't have a fontbank subdirectory. Is it normal ?
I have a fontbank subdir is located under c:\Program Files\GameGuruMAX\Max\Files. All the files that your code is trying to load are there.

![GGM fontbank](https://user-images.githubusercontent.com/28643164/107221395-e0995480-6a13-11eb-94b0-eac0f3dfe6d8.JPG)

**Comment by uboel** [comment]
After creating backup copies of both Files subdir, I tried to copy all the stuff from the one originally located under "program files" to the one located under "documents". I also did this test the other way around. GGM crashed both times. Here are the log files.
[Guru-MapEditor - Files from Documents to Program Files.log](https://github.com/TheGameCreators/GameGuruRepo/files/5943854/Guru-MapEditor.-.Files.from.Documents.to.Program.Files.log)
[Guru-MapEditor - Files from Program Files to Documents.log](https://github.com/TheGameCreators/GameGuruRepo/files/5943855/Guru-MapEditor.-.Files.from.Program.Files.to.Documents.log)

**Comment by LeeBamberTGC** [comment]
Nothing leaps out at me, but thanks for the extra info. Always helpful!

I take it you can run lots of other executables fine, lots of DirectX 11 games, etc with no problems?  

I have added extra debug tracing in this call, so the next build on Friday will show you more info, so we can find out where in the above code we are crashing out. Thanks again!

**Comment by uboel** [comment]
So far this computer let me run about everything I throw at it. I'm confident extra debug info will help pointing out the cause of the trouble.
After next update I'll let come back to you with the log file.

Cheers

Ulric

**Comment by uboel** [comment]
Hi Lee,

The updater did its job the last time I launched GGM...and now the program launches and I'm able to test it!
Great news isn't it? ;-)

Cheers,

Ulric

**Comment by LeeBamberTGC** [comment]
Great news, thanks for confirming the fix!
