### ISSUE TITLE
Issue - Entities Not Copying Over in Standalone Export

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#861]
I've made over 90 builds of my game and the last 4 have not had any changes made to the levels at all. Only additional sprites added and sound and new Lua additions. Now and for the first time ever im seeing missing entities in my standalone builds. No warnings or errors. So I have to play through my game just to find visually whats missing so i can move them over manually.

Not sure what the cause is but perhaps I've hit some kind of limit?

**Comment by Teabone3** [comment]
I'm going to close this issue report as the issue seems to not be occurring anymore for me.

**Comment by plemsoft** [comment]
@Teabone3 Could it be that you now export to another standalone folder name , we did find a issue that could exclude "rare" files when you exported, where the length of the destination folder+filename was the problem ?

Just for the record :)

Thanks for your help.
