### ISSUE TITLE
Text files not encrypted in standalone

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#863]
The title says it all. Text files are not encrypted in standalone, meaning a user can go and edit gunspec txt files to make the game easier. I also have lua scripts using the file IO commands to open and write to text files to store values between levels, collectables and inventory stuff; these become editable too, meaning players could effectively give themselves anything they need. I'm also working on a pack at the moment to uses a lot of user-generated text files to control thing, these would also be editable too.

**Comment by Kasseyus** [comment]
Added code to encrypt .txt files on standalone build.
