### ISSUE TITLE
terrain lod

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#865]
It seems that the three sliders are reversed, you'd want detail near and less further away so the values of mid and far should be lower than near i think or am i interpreting the working of this lod function wrongly?

Classic

**Comment by LeeBamberTGC** [comment]
Can you describe more clearly a step by step of what you are doing, and what result you see, and what you expected. Thanks.

**Comment by earthling45** [comment]
Well, i would expect to see a change in value, with that i mean a reduction or increase in polygons.
This happens only when altering the value of 'terrain lod near' but there is no change when altering 'mid' or 'far'.

**Comment by LeeBamberTGC** [comment]
Maybe produce a sample FPM using stock media and a description of what I should do in the level to see the issue, thanks.

**Comment by earthling45** [comment]
I'll close this topic, no reason to produce an example FPM becuase it is more of a question i had than a problem. :)
