### ISSUE TITLE
Runtime Error 3003

### ISSUE THREAD

**Issue by DieHardCDN** [TheGameCreators/GameGuruRepo#866]
Lee, I have the same issue where the program crashes to the desktop without error.

After I re-installed and re-booted this error came up.
![error](https://user-images.githubusercontent.com/77344978/104767698-33902c80-5732-11eb-90c3-70e5db5b06bf.JPG)

These are my laptop spec's.

Operating System
Windows 10 Home 64-bit
CPU
Intel Core i7 @ 2.60GHz 58 °C
Comet Lake 14nm Technology
RAM
32.0GB
Motherboard
Alienware Alienware m17 R3 (U3E1)
Graphics
Generic PnP Monitor (3840x2160@60Hz)
Intel UHD Graphics (Dell)
4095MB NVIDIA GeForce RTX 2070 Super (Dell) 49 °C
SLI Disabled
Storage
953GB Micron 2300 NVMe 1024GB (RAID (SSD))
465GB Crucial CT500P1SSD8 (RAID (SSD))
Optical Drives
No optical disk drives detected
Audio
Realtek Audio

**Comment by LeeBamberTGC** [comment]
This bug is reported in another bug report and replied to.
