### ISSUE TITLE
Lua SetWaterHeight function doesn't call the terrain_updatewaterphysics function after updating the water height.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#867]
As per issue description.

What this means is that changing the water level in Lua script looks like it works but the Bullet engine doesn't realise that the level has changed so the GetCharacterHitFloor returns the wrong answer.

**Comment by synchromesh62** [comment]
I added a video to show the effect.
Although the water lowers it still seems to be there.
https://youtu.be/_RS8BvslAgk

**Comment by plemsoft** [comment]
@AmenMoses Thanks for reporting this issue , and for the solution :)

This has been fixed and will be in the next update.
