### ISSUE TITLE
Runtime error 0 (Help Wanted)

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#868]
Dear Support Team, I am asking for your help.

This runtime error happens to players that use a laptop. How Can I fix it ?

https://forum.game-guru.com/thread/222468

**Comment by plemsoft** [comment]
@Duchenkuke Try this first: https://forum.game-guru.com/thread/222468#msg2638074

**Comment by Duchenkuke** [comment]
the issue was solved. thanks so much !!!!!
