### ISSUE TITLE
Tiny Installer Error [SOLVED]

### ISSUE THREAD

**Issue by MadLadDesigns** [TheGameCreators/GameGuruRepo#871]
When I try to install I get the following error. I saved the installer exe to my desktop.

![Clipboard01](https://user-images.githubusercontent.com/75511721/106314783-2743bd80-6262-11eb-9e93-4fd4cc959b89.jpg)

**Comment by synchromesh62** [comment]
I noticed on the forums you sorted this and said it was your AVG that caused the problem.
Can i confirm its now ok so i can close it ?

**Comment by MadLadDesigns** [comment]
Yes, sorry it was the Virus checker causing the problem.
