### ISSUE TITLE
144hz Monitor causes issues with MAX

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#873]
When using a 144hz refresh rate, footfall sounds are FAR slower than normal, and every animation plays in slow-motion. (NPCs walking, player weapons, etc.) However the actual FPS and the "rate" of the game seems unaffected. (Automatic weapons fire as fast as they should, the player can move around freely without issue, NPC logic works fine, 144 frames are being drawn each second, etc.)

Setting the monitor to only run at 60hz fixes these issues, meaning it's not my system and it's instead an issue with the engine being unable to handle the higher framerate.

**Comment by rvanner** [comment]
@fearlesswee Thanks for this great feedback. We are currently having the foot sounds re-recorded and playing them back needs to be the same for all users.

**Comment by plemsoft** [comment]
@fearlesswee As i remember Lee already fixed this issue, could you test this in the latest version and close this issue if its already fixed , Thanks for your help :)

**Comment by fearlesswee** [comment]
@plemsoft Oh haha I forgot about this issue, yeah this has been fixed for quite some time now!
