### ISSUE TITLE
Tiny Installer: Files are downloading and then setting back to zero and being rewritten over and over again

### ISSUE THREAD

**Issue by Stefos-art** [TheGameCreators/GameGuruRepo#877]
The problem as far as I can tell is with the texturebank, the files marked as uncompressed are not writing correctly, during updating (installing) the files grow to around 24 Meg then reset to zero and then the process restarts over and over again. I left the installer on for hours over night and it got nowhere! I have turned off all security on my computer including antivirus software and firewall.
I have tried different hard drives

My internet download speed is 5 MBit per second and I have also tried installing on a second computer with same results.
![Screenshot_140](https://user-images.githubusercontent.com/62201786/106458588-4b3d1400-6499-11eb-8326-262b3b748bb1.png)
![Screenshot_144](https://user-images.githubusercontent.com/62201786/106458616-51cb8b80-6499-11eb-91a4-17c5cc162194.png)

**Comment by PaulSJ** [comment]
[GameGuru MAX Updater.zip](https://github.com/TheGameCreators/GameGuruRepo/files/5959488/GameGuru.MAX.Updater.zip)
@Stefos-art Can you try the attached version and let me know what happens. If any errors occur then it should output an "install_errors.txt" file in the install directory

**Comment by Stefos-art** [comment]
Hi, no difference and no "install_errors.txt" is written.

**Comment by PaulSJ** [comment]
[GameGuru MAX Updater.zip](https://github.com/TheGameCreators/GameGuruRepo/files/5966626/GameGuru.MAX.Updater.zip)
@Stefos-art Please try this version and see if that changes anything. If it is still not working then can you copy one of the files it is continually overwriting mid download and upload it here (or elsewhere) so I can see what it is actually downloading?

**Comment by Stefos-art** [comment]
[terrain cracked mud_color (uncompressed) (2).zip](https://github.com/TheGameCreators/GameGuruRepo/files/5967719/terrain.cracked.mud_color.uncompressed.2.zip)
[terrain grass dark_color (uncompressed).zip](https://github.com/TheGameCreators/GameGuruRepo/files/5967735/terrain.grass.dark_color.uncompressed.zip)
Here is to versions of one file, please note when I was copying the file, it had reached 8MB and then reset to zero, which is what I have sent you, the other file just shows it building back up in size again then resets, other such files are doing the same.
Stefos

**Comment by Stefos-art** [comment]
terrain grass dark_color (uncompressed) again reset to zero while I was uploading files and writing text to you.

**Comment by PaulSJ** [comment]
@Stefos-art Roughly how long do these files download before they reset and start again?

**Comment by Stefos-art** [comment]
Depends on the size of the files, some reset when they have reached about 8MB some larger some smaller. As far as I can tell it is only this folder. Also how is it it has the same problem when trying to download on a second computer. They are totally seperate entities.

**Comment by Stefos-art** [comment]
Could it have something to do with my internet connection? if so nothing else is effected, I have downloaded massive games without problems. The internet is the only entity my 2 computers share.

**Comment by PaulSJ** [comment]
That's very strange. It would suggest something with the internet connection is causing it but I can't think of a reasonable explanation. I tried downloading the "terrain grass dark_color (uncompressed)" file from our server using a throttled connection to see if it would time out but it succeeded after 21 minutes of downloading just that file. 

It's possible the network connections are continually being reset, but that is very unusual and would suggest a network attack is going on.

I've created a version here [GameGuru MAX Updater.zip](https://github.com/TheGameCreators/GameGuruRepo/files/5973341/GameGuru.MAX.Updater.zip) that will show a message box as soon as a file fails to download, so no need for it to write the install_errors.txt file, hopefully that will reveal something

**Comment by Stefos-art** [comment]
![Screenshot_161](https://user-images.githubusercontent.com/62201786/107810049-b679c680-6d74-11eb-8fb0-1afff24783d0.png)
![Screenshot_162](https://user-images.githubusercontent.com/62201786/107810055-b974b700-6d74-11eb-86c4-4d8367968ac3.png)
![Screenshot_163](https://user-images.githubusercontent.com/62201786/107810059-bbd71100-6d74-11eb-8fb0-a96efb594523.png)
Here you go one after another, started a couple minutes into downloading.
I have a load of a friends internet box, going to try with that, will let you know how it goes.
Stefos

**Comment by Stefos-art** [comment]
![Screenshot_164](https://user-images.githubusercontent.com/62201786/107811107-584de300-6d76-11eb-9aa5-098125be3152.png)
Amazing!!!!!! It downloaded and installed the 1.2 GB within a couple of minutes!!! It my box or phone line, this box my frien lent me works off the 4G network! Thanks for all your help, looks like I am going to need a 4G network box!!

**Comment by PaulSJ** [comment]
Glad to hear you got it working
