### ISSUE TITLE
Max Editor gets progressively slower and slower over time

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#879]
It starts fine, editor runs smooth and tests are fast. But over time, especially if you alter the terrain with sculpting and textures and add grass it starts to really slow down. Terrain editing becomes super laggy and test builds can take minutes to complete; to the point that it looks like it has stopped responding.
I am using a Ryzen 1700, 970GTX, 1TB SSD, 16 gig on Win 10.

**Comment by Retrogamebloke** [comment]
After more tests in Max, this is definitely related to terrain edits, or seems to be. Placing objects on a flat unchanged terrain works way better. Although I can for sure say that Max is more hoggy than GG in general. I can't run it and flip between other programs without serious slowdown.

I can run easily GG for hours, while flipping into notepad for scripting and even blender for modelling with no issues. In Max I can barely run Youtube vids while it is running. So scripting is a nightmare and so far I have had to script in GG then copy over to max to test them, due to the slowdown I experience; not experienced slowdown typing into notepad or the like for many years. It may be my system of course, but I have a reasonable setup overall, and have no issues with GG or other engines in that regard.

Just a heads up. Max seems to run fine with placing objects and coping with a bunch, but even then, when multi-tasking really hits my system hard :(

**Comment by plemsoft** [comment]
@Retrogamebloke The terrain system is getting a rewrite and should fix this. also we fixed some memory leaks that could also be the cause why you see a slow down over time :)

**Comment by rvanner** [comment]
@Retrogamebloke Do you still experience this?

**Comment by plemsoft** [comment]
We have a new terrain system now.
