### ISSUE TITLE
Max - Losing textures on trees placed using I key.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#881]
As soon as you test the game the textures are lost, also does the same if you save it.
![in game](https://user-images.githubusercontent.com/44620846/106916233-d703aa00-66fe-11eb-9b4f-c2e56e582e8f.jpg)
![in editor](https://user-images.githubusercontent.com/44620846/106916265-de2ab800-66fe-11eb-8f98-6bbd588a46f6.jpg)
The single tree that has a texture is one I placed without the i key.

Not sure if this is related, but performance on that tiny bunch of trees was also horrible, dropping to about 30fps.

**Comment by LeeBamberTGC** [comment]
Try GameGuru MAX Build 2021.02.12. Drop-in a Birch and let me know if you see the leaves:

![image](https://user-images.githubusercontent.com/35840583/107645716-f2c3fe80-6c70-11eb-88a4-bce1489fa18e.png)

**Comment by Retrogamebloke** [comment]
This particular issue seems to be fixed. From quick tests anyway.
![trees](https://user-images.githubusercontent.com/44620846/111089761-22db1780-8525-11eb-8515-28845c58ccfa.jpg)
The only thing I notice here, is when saving and loading you get a massive white box hiding the map afterwards. but so far no missing textures for leaves that I can see.

**Comment by Retrogamebloke** [comment]
Oh, when using the i key to splatter stuff about seems you can't hold and drag anymore, the trees just keep spawning where they are first placed. Which for me isn't a major issue, I did that automatically in GG anyway to stop serious slowdown, but will look odd to many.

**Comment by plemsoft** [comment]
@Retrogamebloke Thanks for confirming the original bug fix :)
