### ISSUE TITLE
Walk though hill into water

### ISSUE THREAD

**Issue by andypmillard** [TheGameCreators/GameGuruRepo#883]
Apologies as I am new to git hub and may be doing this all wrong. I am not trying to build a game but test features so.... Made a hill with sculpt terrain tool then went into test level and most of the time I can walk through the hill into the water level inside the hill. This has happened on all last 3 builds. I tried the same thing each time - build hill test game. this happens more often than not.
Once it caused GGMax to crash, screen went black no error code.
I also loaded The Big Escape but I was walking in water with bits of long grass and the rest of the level was way up in the sky. Tried this a couple of times and sometimes the graphics are also sheared.
Setup: AMD Ryzen 7 3700X 8 core processor 3.59GHz, 16 GB ram,  Asus TUF gaming X570 plus motherboard, Gigabyte GTX1660 6GB graphics card, M2 pcle4 1TB hard drive and 2 931GB hard drives with dual monitors.

**Comment by synchromesh62** [comment]
Hi Andy
As you are aware Max has not been released as of yet and its only Pre-Order Customers that are getting the Test Builds.
These are still very early builds with lots of features still missing and are only really for testing at the moment.
Terrain is just a placement and is far from finished. Crashes are expected this early in development.
Updates are now Weekly so lots comin.
Hope that helps ..

**Comment by Digital-Prophet** [comment]
Hi Syncro.

Same issue as Andy. I know that this is still early and that there are missing features etc. On the forum Lee told us if we have issues we should report here - what the tracker is for as well as Beta and Alpha software right? 
So just that there is a record for the fix. When that works I guess the bug can just be closed. Since it is a bug and not working as it should I don't think it's unreasonable to post it here.
Can't wait for the updates. The mini installer is such a step in the right direction I think.

**Comment by MadjackGG** [comment]
I'm also seeing this issue.
To clarify; if I set up a simple level with a small hill and a player start marker, the first time I run the level the player avatar will walk over the hill as expected. But running the level thereafter, the player avatar just clips straight through the hill.

Reloading doesn't solve the issue; terrain collision is not being re-enabled after the first run.

Running latest build, W10 pro, Nvidia GTX1060 6gb video card.

**Comment by synchromesh62** [comment]
My bad
I took the first post from the OP more as a question and responded to it that way mainly because this issue is already on the Teamwork to do list but terrain just is not finished which is why its all over the place right now :)

**Comment by MadjackGG** [comment]
> My bad
> I took the first post from the OP more as a question and responded to it that way mainly because this issue is already on the Teamwork to do list but terrain just is not finished which is why its all over the place right now :)

No worries. 

Hopefully it's something that'll be fixed shortly because it makes building/testing levels not really worthwhile given it requires continual restarts to work correctly.

**Comment by Digital-Prophet** [comment]
> My bad
> I took the first post from the OP more as a question and responded to it that way mainly because this issue is already on the Teamwork to do list but terrain just is not finished which is why its all over the place right now :)

No probs :)

Just to add further testing info.
If one takes the standard level, and just dig a hole until you can see the water, make it a bit wide, you will then see the character walk on and his collision would be on where the default terrain level was and not follow the terrain down towards the water.

**Comment by LeeBamberTGC** [comment]
Check out the build this Friday to confirm this bug as fixed, thanks.
