### ISSUE TITLE
Skirt and Dress

### ISSUE THREAD

**Issue by Bollehopp** [TheGameCreators/GameGuruRepo#890]
Noticed today while playing around in gamegurumax that dress and skirt are exactly the same thing..
Just wanted to report this as I did report it in discord but didnt know it wasnt really official and that this was official. 
So basically the dress is not a dress its a skirt. Just making sure further delay will not be happening that dlc assets will not suffer from misnaming of files.

**Comment by rvanner** [comment]
@Bollehopp  We will deal with this when we come to enhance the character creator.

**Comment by rvanner** [comment]
The character creator selections will be refined soon. Closing this for now.
