### ISSUE TITLE
not fully loaded 16 mb not loaded

### ISSUE THREAD

**Issue by sciencebloke50** [TheGameCreators/GameGuruRepo#893]
hi this is in my error log approx 13mb will not verify or load in on verify approx it appears
also it does not show a log of changes

Download file failed hash check "ÐþH*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "Pñ H*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "!H*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "0Ï';*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "Î';*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "p!H*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "P!H*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "ÐH*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "ÐþH*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "Pñ H*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "!H*", HTTP status: 404, Internal Error: "None"
Download file failed hash check "0Ï';*", HTTP status: 404, Internal Error: "None"
this is approximately 500 more in the errores list

**Comment by PaulSJ** [comment]
This was an issue with the 2021.02.12 build, it should be fixed now

**Comment by sciencebloke50** [comment]
many thanks

regards

lee

________________________________
