### ISSUE TITLE
The UI is to small for 4k. Can we have the ability to resize the UI?

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#894]
Possible I missed it but it would be nice to be able to resize the UI. With a 4k monitor I can barely read things, and I've actually gotten a headache from squinting. Other programs dont really have this problem? I have attached a screenshot showing the size of my UI. Try sitting back a little bit in your chair and reading the text on screen. The worst spot is the top left menu bar imo. 

![cant read](https://user-images.githubusercontent.com/51464873/108032269-d8cf4680-6ff7-11eb-9cf5-97a5471a6f8b.jpg)

**Comment by rvanner** [comment]
@Kitakazi Yes it's too small and something we will need to deal with. We will consider it in our development plans later on.

**Comment by Kitakazi** [comment]
Looks like this isnt a problem anymore. With the latest update, selection issues are fixed. Disabling DPI awareness now correctly scales the editor with display settings. Thank you guys.
