### ISSUE TITLE
Entities firing in standalone causes desktop crash in classic

### ISSUE THREAD

**Issue by honkeyboy** [TheGameCreators/GameGuruRepo#895]
I'm pretty much using the standard ai_soldier atm, this doesn't happen in the editor just the standalone, i have tried various things to solve it but unfortunately to no avail. i have 1 start level with no combat characters on it and so use a winzone to various levels i get to that level fine and can run around no problem, as soon as the entity engages my character the game crashes to desktop, from what i can see not the other way around.

**Comment by Kitakazi** [comment]
Maybe make sure the audio of the enemies gun firing copied over? I had a similiar problem but it was a while ago, but I think it had to do with the audio of the gun fire. Make sure it is .wav 16bit mono. 

Not sure if this will help but hopefully.

**Comment by honkeyboy** [comment]
They have stock guns atm m8 just the cartoon raygun but yeah might be, will have a look thanks, I've pretty much pulled off all the scripts to retest later on today. fingers crossed

**Comment by honkeyboy** [comment]
After lots of deleting changing and generally messing about, the cause for some odd reason seems to be when i add multiple winzones to the map if i have just one everything works fine on adding a second the game crashes when the player enters combat? when i remove the second it works again?

**Comment by plemsoft** [comment]
@honkeyboy Thanks for reporting this issue, i tried to make a small level , and added multiply winzones , but it worked as expected, i just used the standard ai_soldier , could you try to make a small .fpm that have this problem ? , or perhaps e-mail me a download link to your standalone that have this problem, this way im able to run it with a debugger attached and see what the problem is.

e-mail: plemsoft@plemsoft.com

Thanks for your help :)

**Comment by honkeyboy** [comment]
Hi Preben, I have done it a different way now and completely rebuilt the maps it seems to be holding up so you can mark this one as solved m8 I'll mail you if the problem occurs again. Thanks :)

**Comment by plemsoft** [comment]
@honkeyboy Great news, yes just open a new issue if you get the same problems again , and email me a download link to the standalone so im able to track it down :)
