### ISSUE TITLE
Found a bug in gameguru max

### ISSUE THREAD

**Issue by Bollehopp** [TheGameCreators/GameGuruRepo#896]
Hiya just realized this might be how its meant to be for now (as its still in alpha) but I loaded up the test level, you are in a house there right no sky visible.. 
Well as I was in there I did changes to the Sky settings, changed them to night or so and IT alters the light in that cellar house.
So it alters the brightness in the inside of the cellar also altering skysettings.. Is this meant to happen or is it a bug?

**Comment by rvanner** [comment]
A future feature will allow you to stop this from happening. This is reported elsewhere in the issues list so I will close this issue to avoid too many issues being open.
