### ISSUE TITLE
Game guru disables screensaver in Windows 10 pro PP build 2018.02.xx directx11 preview

### ISSUE THREAD

**Issue by a3dartist** [TheGameCreators/GameGuruRepo#90]
Hi, everyone I have noticed that the screensaver in Windows 10 pro gets disabled when running game guru preview build! Also does it in current release as well! I have to reboot my computer after running game guru, is shut down because the screensaver doesn't work after shutting down game guru is there a way around it or is this a bug!

**Comment by LeeBamberTGC** [comment]
Is anyone else experiencing this on Windows 10 Pro?

**Comment by LeeBamberTGC** [comment]
Closing this issue as not able to reproduce.
