### ISSUE TITLE
Selecting Lights problem.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#900]
Selecting lights in Tab \ Clip mode is getting harder and harder.
You could once just select them with clip mode easily but now its as if you have to be spot on in a precise place which can take a few attempts using CTRL+Mouse Wheel as the video shows. 

https://youtu.be/si_6Xy2XBlE

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Comment by synchromesh62** [comment]
Fantastic Thanks Preben.
