### ISSUE TITLE
Program fails to start?

### ISSUE THREAD

**Issue by DectreDigital** [TheGameCreators/GameGuruRepo#901]
Hello all! I'm on the latest Beta although this issue has occurred with every version I've installed. 

The program opens, tries to load and just closes. No error message no nothing, I'm going to put my specs below and the log file.

Specs: 
CPU - Intel i5 - 4690k (@4.2ghz) 
RAM - 8GB DDR3 HyperX
GPU - GTX Titan Black 
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/6015253/Guru-MapEditor.log)

I can record it if it would help :D

**Comment by rvanner** [comment]
@DectreDigital Can you try the very latest version released on the 12th March and let us know if it's now okay or still an issue for you?

**Comment by DectreDigital** [comment]
It now runs yes, but any games I save stand-alone are not working, the same error happens. But I can at least make stuff.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rvanner** [comment]
Standalone is not finished, don't expect it to work until we showcase it.
