### ISSUE TITLE
Issue: Water Visibility

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#903]
When you start a new map and dig a hole to expose water. The water will not be visible unless you turn it on in the tab menu settings. I get emails/pms about this from new-comers to GG.

Might want to considering bumping the water and reflection graphics options by at least 1 point to not confuse new comers. 

Another person seems to have had this problem:

https://forum.game-guru.com/thread/222530

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue, this has been fixed for the next update , and thanks for your help :)
