### ISSUE TITLE
Issue with first entity placed on map not saving properly.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#904]
With MAX build 2021.02.12 when you save the level and reload it the first entity on the map isn't saved properly.

For example I placed 2 characters on the map, saved it and reloaded and only the second one placed is reloaded.

Second example, first entity placed is a zone, saved and reloaded and the zone outline is still visible but the zone entity itself is not there, i.e. it cannot be selected.

**Comment by AmenMoses** [comment]
Well this is so typically GG, just tried to replicate this with a new level so I could give a step by step guide to how to create it and it now isn't happening!

**Comment by rvanner** [comment]
OK, I will mark this as fixed for now. If it happens in the future then please re-report.
