### ISSUE TITLE
Almost 100 percent CPU use when adding terrain then pressing playtest

### ISSUE THREAD

**Issue by Bollehopp** [TheGameCreators/GameGuruRepo#905]
I noticed this today, I did the update in Gameguru max and after I applied a lot of terrain in my level. 
I also changed the water colour to red and made some hills.

After pressing playtest it crashed and I went to taskmanager in order to kill the app but it was showing at 97 percent cpu use.

**Comment by rvanner** [comment]
Terrain will be totally re-done in the months to come, don't worry, it will be far better and optimised.

**Comment by rvanner** [comment]
The new terrain system will replace this. Closing this down now.
