### ISSUE TITLE
Can not download GGmax files.  ( File list failed to parse )

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#907]
I have downloaded the latest small installer.exe
as soon as i want to download GGMax files i get an error. :.. File list failed to parse
https://forum.game-guru.com/thread/222488#msg2638413

**Comment by rvanner** [comment]
@Pcskiller Is this still an issue for you? Have you tried the latest version of the installer?

**Comment by rvanner** [comment]
@Pcskiller Is this still an issue for you with the latest Tiny Installer?

**Comment by Pcskiller** [comment]
Hi. i am at the work right now, i get of in about 2 hours, Wil download the
installer again and test. but up to the point were i have reported it, i
have not tested again, do not know if there were a new installer over the
last week or two.

**Comment by rvanner** [comment]
@Pcskiller  OK, I look forward to hearing back from you. If it does fail, can you make a video of what happens?

**Comment by Pcskiller** [comment]
ok. i will

**Comment by GraPhiX-Guru** [comment]
I can confirm this error on another system this system is based in UK

**Comment by GraPhiX-Guru** [comment]
@Pcskiller  can you try the install again i think the issue is now fixed

**Comment by Pcskiller** [comment]
Thank you so much it is downloading as i am typing here right now.
Please Say thanks to anyone who had an input to this problem

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rvanner** [comment]
Great to hear! I am marking this as fixed now.

**Comment by Pcskiller** [comment]
Great, thanks.
