### ISSUE TITLE
MAX installer trashed my installation.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#909]
![installer](https://user-images.githubusercontent.com/35708338/109717769-65ecd080-7b9e-11eb-8c11-83dc7c43404d.jpg)

[install_errors.txt](https://github.com/TheGameCreators/GameGuruRepo/files/6071928/install_errors.txt)

![Max folder](https://user-images.githubusercontent.com/35708338/109718191-ec091700-7b9e-11eb-8022-35ca3f4a5f16.jpg)

Needless to say it won't run anymore!

**Comment by AmenMoses** [comment]
Just to clarify, my issue is about the fact that if the installer fails to download the files for whatever reason it should not trash the existing installation!
After the installer failed the executables in the Max folder were 0 size as well as the two shown above.

**Comment by rvanner** [comment]
@LeeBamberTGC & @PaulSJ Can you comment on this issue please?

**Comment by LeeBamberTGC** [comment]
It is the process of the installer to replace files with older and newer versions of the file depending on which product version you select. This is a naturally destructive process. If you trash your installation with a specific version, you can of course choose the earlier or later version and verify the files against that version to restore your previous build, and the way the current installer is designed.

I have moved this to an enhancement request, as I assume you want the installer/updater to backup all present files before applying the update, so that the original files can be returned if the installation is cancelled part way through and requires a 'rollback'.

**Comment by rvanner** [comment]
@AmenMoses Does Lee's reply to your issue make sense to you?

**Comment by AmenMoses** [comment]
Not really, looking at the pictures I included you can see the updater has blatted over both the original and (new) executables, surely it should check that the (new) executables have downloaded correctly before overwriting the originals?

I believe this occurred during a problem with the TGC servers but the installer/updater should I think guard against that sort of thing.

**Comment by rvanner** [comment]
OK, thanks for your thoughts. We will cover it off here at TGC in future meetings.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Are you recommending the updater download into a temp location, and only if the downloaded file is in tact it should then delete the original and copy the temp file in its place as an extra measure of security?

**Comment by AmenMoses** [comment]
Or name the files new_<whatever>.exe (or something) until the update has completed successfully and then delete the old ones and rename the new ones.  Probably only necessary for the key executable files and critical files needed by them.  

Models and scripts etc can then be recovered by the verify if necessary.

Once the new files are dowloaded I assume they are checked for non-corruption?  Like against a checksum list or something?

**Comment by LeeBamberTGC** [comment]
Yes, we compare the checksum of the local file with the server file to ensure the file arrived in-tact. I will set this as a MEDIUM priority with the task of ensuring all files are successfully downloaded and verified before the current file on the local system is replaced. Thus avoiding the possibility of an EXE or other core file from being wiped out to 0Kb.

**Comment by LeeBamberTGC** [comment]
Some users are also getting a parse error. In those cases, try these steps:

1. Uninstall everything and manually delete anything at "C:\Program Files\GameGuruMAX"
2. Grab the very latest Tiny Installler from the TGC product page, this is critical as it has the newer updater needed
3. Delete all folders found here "C:\Users\leeba\AppData\Local\AGKApps\TheGameCreators" which allows the updater to relink the TGC login.

**Comment by rvanner** [comment]
The installer has changed significantly. Closing this for now.
