### ISSUE TITLE
Classic - FreezePlayer() rotates player widely when triggered

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#910]
Title explains it all. also UnFreezePlayer() does not work

**Comment by sfkylcnky** [comment]
can anyone confirm this?

**Comment by LeeBamberTGC** [comment]
@sfkylcnky For the next EXP build, Try out the zombie characters that use the zombie behavior in the build. I have beefed up the brainfeed event so you can see the freeze and unfreeze of the player at work:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/7467f586-02cd-4064-b91a-2fe30e778cec)
