### ISSUE TITLE
MAX version 05Mar2021: Object trail

### ISSUE THREAD

**Issue by redagent101** [TheGameCreators/GameGuruRepo#913]
When selecting the chess board object, a trail is left behind while moving the object.  Known issue?  This is on my laptop and not on my PC.  Still to test on PC.  I have verified the files.

![GGMax_05Mar2021_version_object trail issue](https://user-images.githubusercontent.com/15969299/110232046-2eba4e80-7f13-11eb-821e-81817b00a11a.png)

**Comment by synchromesh62** [comment]
Just tested on my pc and its fine my end.
Is it just the Chess Board ?

**Comment by redagent101** [comment]
I'll try some other stock assets on my laptop version of GGMAX asap.  Don't have the issue on my PC.

**Comment by redagent101** [comment]
yes it seems to be all entities that leave a trail on my laptop. maybe it's the internal GFX card.  PC is all good.

**Comment by LeeBamberTGC** [comment]
Looks like the stencil buffer is not being fully cleared (or at all).  Are you able to post your DXDIAG system specs of your laptop here so I can see the DirectX version, GPU graphics / driver versions, thanks.

**Comment by redagent101** [comment]
Here you go.... thanks Lee

[DxDiag.txt](https://github.com/TheGameCreators/GameGuruRepo/files/6169237/DxDiag.txt)

**Comment by LeeBamberTGC** [comment]
Looks like the laptop is not within min specifications, using a "Intel(R) HD Graphics Family". Do you know if your laptop has a dedicated GPU that exceeds a GTX 960?

**Comment by redagent101** [comment]
thanks Lee, I thought it might be that. No issues with PC all good.
