### ISSUE TITLE
Seeing light entity reflections on indoor level walls. 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#914]
As the title states
Seeing light entity reflections on indoor level walls.
Build 5-03-21

![image](https://user-images.githubusercontent.com/35708217/110466517-c6639c80-80cd-11eb-96a6-5dff5306e8f2.png)

**Comment by LeeBamberTGC** [comment]
I have had a good shufty through the Wicked shaders, and it seems the specular from the light is part of the PBR system overall. I guess the idea is that lights are placed near actual light sources like bulbs and skylights so the light from them makes sense, although it does show the 'trick' of using basic point lights to simulate more complex forms. I will put this down as an enhancement for a future feature that might be able to remove the specular contributed by the light source.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Ok Lee thanks for looking but my original Demo has gone from this 
https://youtu.be/D92Wn-uamb4 which looked awesome with its reflections etc before the repo 
to this ..
https://youtu.be/RZH7yMPDyF0 where the light bulb reflections kill that fantastic Shiny effect.
Its basically when you use the reflectiveness but its a pretty boring look without it ..
No worries i will have a play around.

**Comment by LeeBamberTGC** [comment]
Is the old version from before we upgraded to the latest Wicked Engine?

**Comment by synchromesh62** [comment]
Hi Lee
Yes the first vid was the original before the Repo,

**Comment by rvanner** [comment]
@michaeloldman Is this still a problem?
