### ISSUE TITLE
shadows.

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#915]
Hi, i've made a container but underneath you'll see no shadow until it is raised somewhat as you can see in the little video.

https://www.youtube.com/watch?v=m9L9VWuLB7I

This is of course not a stock model but i wonder if this can be fixed.
If you want to have a look at the model it can be downloaded from the link below.
https://drive.google.com/file/d/1KPsXSfKqibkdl-FGj6bAOR_YYvagQQsO/view?usp=sharing

**Comment by plemsoft** [comment]
@earthling45 Thanks for reporting this issue.

Yes its always hard to get thin geometry to block the light, anyway if you make it double sided and move it up 1 unit it will block the light on the ground correctly. so make these changes in your FPE.

Set:
cullmode         = 1
And Add:
offyoverride     = 1
smoothangle      = 101


Let me know if this fix your issue, Thanks :)
