### ISSUE TITLE
4k not usable. UI does not scale to display settings. Causes terrible selection issues with cursor. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#922]
This is NOT a feature request. This is a real problem. I don't think it is intended that the program be un-usable in 4k.

In 4k the cursor does not click where it is on the screen. I've posted this issue a while ago on GitHub under the title Selection Issues. I know now for a fact, it has to do with my monitor being in 4k.  Trying to simply click an entity on the map is impossible.
Because even if the cursor is directly on the entity, it isn't really clicking where the cursor is showing. 

I can't read anything on the UI unless I get 1 inch away from my monitor. It really is unusable. 
Changing the scaling in my Display Settings does nothing.  Since this is the only program I have (besides actual video games themselves) that does not scale with my computers Display Settings then I would guess this is somesort of bug.

. . I can't even read what i'm typing because it is so small. Probably lots of typos. im using the bug reporting system in engine.

System Specs:
None detected.

**Comment by Granada1** [comment]
I am using a 4 k monitor and it’s ok for me , bug reporting window is small but that’s it , I have my monitor scale set to 150 in computer settings

**Comment by Kitakazi** [comment]
And you can select things entities on the map? Does changing your
resolutions scaling in display settings do anything to the editor?

**Comment by Granada1** [comment]
I was selecting and moving lights ok last night during testing ,  I will test the selection box later tonight

**Comment by Kitakazi** [comment]
Alright cool thanks.

**Comment by Granada1** [comment]
You are rightabout the selection box i sent a bug report through Max with a vid link

**Comment by Kitakazi** [comment]
Sweet, thanks!

**Comment by Kitakazi** [comment]
Looks like this issue has been fixed. Selection now works correctly. Disabling DPI awareness now correctly scales the editor. Thank you TGC!
