### ISSUE TITLE
Grouped Objects don't respect rotated objects

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#948]
If you rotate an object in a group using the 1,2,3,4,5,6 keys, when you come to rotate a new version of that group it will mess up all the rotations.

System Specs:
None detected!

**Comment by plemsoft** [comment]
@rvanner Lee fixed the rotation of groups a few version back , also single rotation of a group object was blocked so should not be possible anymore.

**Comment by rvanner** [comment]
@plemsoft I just checked this, you can turn on the rotations using the Advanced options in settings. Good news is that it all works fine now.

**Comment by 3coms** [comment]
1- Grouped Objects don't respect rotated objects #948
a- Make 1 group (cellar stuff - 5 items)
b- Edit group
c- rotate one entity via gizmo, no problem.
d- try to rotate one entity via 1,2,3,4,5, keys, and rotate the whole group, no being able to rotate just 1 entity, via keys.
e- Try rotating via the "R" key, just one item rotates at a time.

@plemsoft  <you can turn on the rotations using the Advanced options in settings.>
Do you mean rotation via shortcuts?
I just have "allow axis rotation shortcuts" option, in settings>advance tab.
