### ISSUE TITLE
Box selection Problem

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#950]
Working on a 4K monitor box selection is offset from Pointer, my system monitor scale is set to 150.
Normal selection Seems ok

https://www.youtube.com/watch?v=8X0xLQDStDI

( i ticked the box to show Specs in the Max bug reporter )

System Specs:
None detected!

**Comment by plemsoft** [comment]
@Granada1 Do you remember if you had this problem is the last version ?

**Comment by Granada1** [comment]
Sorry I don’t remember , I always used the single selection

**Comment by plemsoft** [comment]
@LeeBamberTGC FYI: Cant test 4k, but the current version changed from GetScreenX to Convert3DTo2D , i changed this back to isolate the problem, but need confirmation if the new Friday version fix this, before i can continue the fix.

**Comment by Granada1** [comment]
I will test when the latest build is up

**Comment by LeeBamberTGC** [comment]
@Granada1 Your internal build version should be updated. Try again and post here your findings, this should help Preben narrow down the issue.

**Comment by Granada1** [comment]
@Lee ,Downloaded and vairified files to latest internal build ,problem still there on 4K

https://www.youtube.com/watch?v=mszVt1XO1FE

**Comment by LeeBamberTGC** [comment]
@plemsoft In latest commits, the issue remains for Granada. Give it another 30 minutes then I will assign it to myself and see if I can find the cause (and reproduce it here). I think I have a 4K somewhere :)

**Comment by plemsoft** [comment]
@Granada1 Found the problem, this has been fixed and will be in the next update :) , @LeeBamberTGC Actually this was the 2D in wicked that dont follow the DPI settings we use, i moved the wicked sprite function to imgui so it also follow all the windows DPI settings.

**Comment by Granada1** [comment]
Cool, thanks guys
