### ISSUE TITLE
Importer - Path Error

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#954]
When you create a custom path for imported models - even when created via File Explorer, and pointed to inside MAX, the importer crashes MAX when saving the file.
The error says it cant find the path.

In my test I have pointed the importer to save in an existing location on my D drive.
But MAX is looking for the path in Program Files on C drive. 

If I just use the default User location (also on my D drive) it works fine.

System Specs:
None detected!

**Comment by LeeBamberTGC** [comment]
@michaeloldman Can you confirm this fix in fridays build, thanks!

**Comment by michaeloldman** [comment]
Yes, can confirm this is now working correctly :)
