### ISSUE TITLE
Broken Fog

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#956]
The fog is black and the settings will not alter the colours.
The range settings also seen to be effected which is very apparent in the cellar demo.

System Specs:
None detected!

**Comment by plemsoft** [comment]
@synchromesh62 I know Lee improved this at some point , could you check if this is still in the latest version ? , also fog colors depend on many things if this is a indoor level try to set "Lighting Color" to black, this would give you more control over the actual fog color. And sure make sure to raise the "Fog Opacity" or you will not see the fog :)

**Comment by synchromesh62** [comment]
@plemsoft 
Hi Preben
Yes this seems to have been fixed. Before it was black only and you could not change the colours at all.
Thanks for the great work.
