### ISSUE TITLE
Paint texture thumb looks strange

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#957]
When changing the size of the paint terrain bar, the scale of the textures changes. One of the textures looks very strange - looks like a bug.

System Specs:
None detected!

**Comment by rvanner** [comment]
Here's an image showing what I see. The white ceramic one has red blotches showing.
![image](https://user-images.githubusercontent.com/1503593/110916148-67da3080-8310-11eb-9672-af78c13ea01c.png)

**Comment by plemsoft** [comment]
@rvanner This has been fixed and will be in the next update :)
