### ISSUE TITLE
Don't allow the same selection of objects to be grouped again

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#959]
1 Select two objects
2 Make them a group
3 You should not be able to make them into another group

Currently the group icon is de-highlighted but you can still click it and make a new one

**Comment by plemsoft** [comment]
@rvanner This has been fixed and will be in the next update.

**Comment by 3coms** [comment]
1- Select 5 items (cellar stuff)
2- Make a group 1
3- Make a group 2
4- Make a new group with groups 1,2. 

I've noticed when I select each group, it instantly gizmo appears, except the group 2, I can select it, but gizmo does not appear anywhere.
