### ISSUE TITLE
Character Creator - Head Attachement

### ISSUE THREAD

**Issue by Snake675** [TheGameCreators/GameGuruRepo#96]
Noticed a wierd thing about the head attachement. Its floating above the head (see picture).
![snake67_publicpreview_01](https://user-images.githubusercontent.com/32170531/36709829-47e059cc-1b7a-11e8-8a10-69c8db1c0db6.PNG)

**Comment by Teabone3** [comment]
I noticed this in the first PP as well. Though it was only in the editor. Also over time it just simply disappeared and fixed itself.

**Comment by LeeBamberTGC** [comment]
Cannot reproduce this on the beta build 10/04/18 - can you verify this has been fixed?

![image](https://user-images.githubusercontent.com/35840583/38555065-bdd692d2-3cbc-11e8-9c78-84c7a8ac06cd.png)

**Comment by Snake675** [comment]
Hi Lee

I will try it soon. I returned to the official build due to the bugs.

There I discovered an other big problem. It occurs in connection with one of my own script. I have already tried a lot of variations, always the same result. Of course it can be my mistake. In any case, I will install the latest build and am curious if the problem persists. If so, I will report that here.

**Comment by Snake675** [comment]
Just realised, I forgot my the code for steam :(

**Comment by Snake675** [comment]
I got the PP again by activating BETA in STEAM (had GG running in the first place). The build in the "about" is said to be 27/03/18. How can I get and install the latest 10/04/18 to check this?

**Comment by LeeBamberTGC** [comment]
Its curently only in the BETA build, but I will move it to PP once the beta testing team say its okay to go

**Comment by Snake675** [comment]
Ok. So I have to wait...

**Comment by Snake675** [comment]
Thanks.

**Comment by redagent101** [comment]
re-opened due to issue s
![hair](https://user-images.githubusercontent.com/15969299/61386923-077dbc00-a8ad-11e9-9a87-f31c176c2c43.jpg)
till exists, see attached pi

**Comment by LeeBamberTGC** [comment]
Can someone attach an FPE created in CC which shows this issue, none of my Character Creator characters render like this.

**Comment by redagent101** [comment]
same here, I can't reproduce this issue, just testing a standalone.

**Comment by redagent101** [comment]
here is the FPE PCS is using, which has some differences with the most current FPE character creator generates:
[man1.txt](https://github.com/TheGameCreators/GameGuruRepo/files/3403734/man1.txt)

**Comment by LeeBamberTGC** [comment]
Just renamed this text file to myman.fpe, added a myman.bmp, dropped him into a fresh level, ran test game and his hair is in tact. Still cannot reproduce:

![image](https://user-images.githubusercontent.com/35840583/61585111-35ccf700-ab4c-11e9-978f-954ddda6e1d0.png)

[myman.zip](https://github.com/TheGameCreators/GameGuruRepo/files/3414057/myman.zip)

Will close this if it cannot be reproduced.
