### ISSUE TITLE
GGMax_2021_03_12 does no flipping normals

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#962]
1- Open a map
2- Select entity and flip the normals
3- uncheck tickbox
It does no back to the original shape, in others words, it does no flip normals again.
Add some video YT link recreating the bug.

https://youtu.be/WMpGXWDqIwc

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by rvanner** [comment]
Same as bug #984?

**Comment by plemsoft** [comment]
@3coms Flip Normals was removed, i will change this into a feature request instead, but i suggest that this will be made in the importer instead, this way we have more control of the actual object data and normals and can adjust directly to fit the media.

**Comment by 3coms** [comment]
@ Rick
Yes, it does.

@ Preben
I copied you. :)

**Comment by 3coms** [comment]
Eh guys, have some question related to:
what normals do we need to use X or open gl?

**Comment by LeeBamberTGC** [comment]
Best to check the existing PBR texture normal maps for how the RGB channels are used for the normal map. For the normal vectors in the model, outward-facing normals as you would find in X files is what MAX needs.

**Comment by rvanner** [comment]
@3coms Did Lee's comment resolve this issue for you?

**Comment by 3coms** [comment]
Well, the issue was with a feature that atm is not on the UI, so yes, it is solved.
