### ISSUE TITLE
Items Highlighted

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#964]
All items Highlighted even when not selected

https://www.youtube.com/watch?v=GbP8WMzneBY

System Specs:
None detected!

**Comment by rvanner** [comment]
@Granada1 I'm not sure what you are showing in the video, can you detail the issue with more explanation please?

**Comment by Granada1** [comment]
@rvanner Hi as in the vid , all items in the three are highlighted even when you are not over them with the curser or selected , I thought it was men’t  to be the other way around

**Comment by rvanner** [comment]
@Granada1 I cannot seem to replicate this issue. Can you make a new scene and show this happening?

**Comment by Granada1** [comment]
@rvanner I will  on comp again tonight and redo level

**Comment by rvanner** [comment]
Thanks!
