### ISSUE TITLE
GPU spiking

### ISSUE THREAD

**Issue by Granada1** [TheGameCreators/GameGuruRepo#965]
GPU spiking when minimized

https://www.youtube.com/watch?v=89lBmp35iOA

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: To be filled by O.E.M.
Processor: AMD FX(tm)-9590 Eight-Core Processor            (8 CPUs), ~4.0GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 3840 x 2160 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by nomad5oul** [comment]
I am having a similar issue with CPU spiking when Max application is minimized

![cpuspike](https://user-images.githubusercontent.com/37256116/111013545-bb439180-8397-11eb-8a3c-1b0dedc172d0.png)

Windows 10 Pro 64 bit
GeForce GTX 1660 SUPER 6GB 
Intel i7 4770 Processor 3.4GHz
16 GB RAM
1920 x 1080 ,60 Hz

**Comment by plemsoft** [comment]
@Granada1 Thanks for reporting this issue, this has been fixed and will be in the next update :)
