### ISSUE TITLE
SSR - Out of Control

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#966]
SSR plays havok in any scene when enabled

This image shows a lot of pixilation - in test game it is lots of noise created by SSR

![SSR Running Amok And Escaping Light Syndrome](https://user-images.githubusercontent.com/12246318/111019193-bcb1a000-8411-11eb-97e0-5fb4a9d373a0.png)

System Specs:
None detected!

**Comment by rvanner** [comment]
@LeeBamberTGC from your Teamwork task "When using SSR there is a Fuzzy weirdness on surfaces going on - like it be raining on them - seems to be on metallic surfaces mostly"

**Comment by LeeBamberTGC** [comment]
The SSR technique is a bit of a hack for reflections, and does not look good in many scenarios. I have moved this to enhancement so we can perhaps look to limit where SSR is used, or replace it with a newer technique.

**Comment by michaeloldman** [comment]
@LeeBamberTGC No problems :)
