### ISSUE TITLE
X-Ray Vision

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#968]
Flashlight causes X-Ray vision when objects using transparency are behind a wall.
![X-Ray Vision](https://user-images.githubusercontent.com/12246318/111019814-a0affd80-8415-11eb-8823-095e5d16b9db.png)

Video Link: https://vimeo.com/522109222/62f18be18c

System Specs:
None detected!

**Comment by plemsoft** [comment]
@michaeloldman As i remember we fixed this one (transparent sorting) , could you check it in the latest version and let me know if you still see this issue, thanks for your help :)

**Comment by michaeloldman** [comment]
Hi Preben. Yes tried in latest version
Still present. (check Discord)

**Comment by plemsoft** [comment]
@michaeloldman Checked your new screenshot on discord, it looks like shadows , could you try to disable "cast shadows" on the unit that you see the xray on, and check from the other side if you still see the xray.

Also if you try to make that "wall" where you see the xray from, double sided , do you still see it ?

**Comment by michaeloldman** [comment]
@plemsoft Yes you be right it is a light inside the unit casting shadows.
"Also if you try to make that "wall" where you see the xray from, double sided , do you still see it ?"
- this doesn't work.

"could you try to disable "cast shadows" on the unit that you see the xray from, and check from the other side if you still see the xray."
- this does work.

It is related to issue #969 
So the best solution is to remove the light from inside the model....

**Comment by plemsoft** [comment]
@michaeloldman Just to make sure, if your "wall" have many meshes, please try to set it to double-sided on all meshes and let me know if that fix it, thanks :)

**Comment by michaeloldman** [comment]
Yes this works @plemsoft - but MAX is not saving any settings made in properties panel. So have to reset everything when re-opening the map, and usually even between consecutive test-game runs.

**Comment by plemsoft** [comment]
@michaeloldman Saving has been fixed and ready for the next update :)

**Comment by michaeloldman** [comment]
@plemsoft awesome thanks! :)

**Comment by michaeloldman** [comment]
FYI
Still not saving in latest build.

**Comment by rvanner** [comment]
@michaeloldman Is this now fixed for you?
