### ISSUE TITLE
Shadows Around Object With Transparency

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#969]
Shadows from outside hull are visible in this picture.

The Unit in the Center uses transparency, and seems to be the cause or related to this issue.

![ShadowTransparencyIssue](https://user-images.githubusercontent.com/12246318/111019482-9d1b7700-8413-11eb-9d20-1517ad352215.png)

Please see #968 X-Ray Vision

The same room without the Unit in it does not have the shadow issue.

![NO_ShadowTransparencyIssue](https://user-images.githubusercontent.com/12246318/111019520-d48a2380-8413-11eb-9714-f7855fe1ce61.png)

System Specs:
None detected!

**Comment by michaeloldman** [comment]
Build 2021.02.04 - Exhibits same issue :)

**Comment by plemsoft** [comment]
@michaeloldman Luckily i still had the "Unit" you sent me and i was able to reproduce it.

The problem is that the triangles is only visible from one side , so when you place a light (inside the unit, or on the other side of a wall that are only single sided) , then the geometry cant block the light and shadows.

To fix this in your top picture , just set the "Unit" to be "Double Sided" and it will block the light/shadows.

Sample:

![unit1](https://user-images.githubusercontent.com/18662417/117288728-1790d200-ae6c-11eb-9011-25e1b219e407.jpg)

![unit2](https://user-images.githubusercontent.com/18662417/117288748-1e1f4980-ae6c-11eb-8b87-1925d9e545db.jpg)

Let me know if this solves your issue, Thanks :)

**Comment by michaeloldman** [comment]
@plemsoft Yes you be right it is a light inside the unit casting shadows.
The model that you tested on does not use transparency and works fine.
The model in the opening pick does use transparency and does not solve issue when using double-sided. Actually the transparent parts are no longer working either, so not see-thru now (solid) 

I can email the model if you like.

**Comment by plemsoft** [comment]
@michaeloldman It should block the light if you set it to double-sided, no matter if its transparent or not, the unit have 2 meshes did you set it to double-sided on both meshes ? , if so and it still dont block the light/shadow , it would be great if you could e-mail me the model that have the problem, and i can test it :)

**Comment by michaeloldman** [comment]
@plemsoft Yes! that works :)
Was not aware of having to now assign settings to all separate meshes in the model - duh!

Solves the problem nicely :)

**Comment by michaeloldman** [comment]
@plemsoft - actually not sure if this solves the issue now.

After saving, closing, and then reopening the map it was all back to the original issue, and I couldn't get it to work again.

None of the settings are being saved atm so not sure if this issue is fixed at all yet....

**Comment by michaeloldman** [comment]
It works - but MAX is not saving settings made in properties panel. Mostly not even between consecutive test-game runs.

**Comment by LeeBamberTGC** [comment]
@michaeloldman I dropped in a few barrels and changed their properties, and the settings where preserved for each instance. See shot for a barrel I toggled the tickboxes:

![image](https://user-images.githubusercontent.com/35840583/117425011-482f4500-af1a-11eb-8555-e58e2fc00d24.png)

**Comment by michaeloldman** [comment]
Hi Lee :)
Yes, doesn't work for custom entities tho. 3com, Granada, and synchro seeing same I believe. Can follow on Discord :)

**Comment by plemsoft** [comment]
The problem here is if you change any settings > mesh 0 , they was not saved only mesh 0 changes.

This has been added, and it will now save all mesh changes to the fpm. Ready from the next update :)
