### ISSUE TITLE
Editor - Trigger Zone Always Active Option

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#97]
Enhancement

It would be nice to have an "always active" property field added to Trigger Zones so we can choose to have a trigger zone always active or not. Similar to entities.

**Comment by AmenMoses** [comment]
Why?  The whole point of a trigger zone is that it doesn't trigger until the player is actually in the zone so what is the point of making it active when the player isn't in the zone, what do you gain by doing that?

**Comment by thecyrus** [comment]
I think he means that we could need a Trigger zone that “spawns”.

**Comment by thecyrus** [comment]
And it’s a great idea.

**Comment by HierToo** [comment]
This would make the name misleading! It is a "TRIGGER"zone, not a always active zone!
There is definitely a better way to declare trigger conditions for a level. I will think about it.

**Comment by Teabone3** [comment]
There are situations where I have trigger zones "trigger" once the player has stepped on them. (that do not deactive when the player steps off.). However The situations stop their functionality once the player has reached a great distance from the zone. I have not found a suitable work around for this, as using only radius detection on barrels isnt beneficial to level design. Using point data purely in LUA is very time consuming when applying it to something like a barrel to create an irregular shape like a zone.

Only work around for this is having having the trigger zones always accompanied by entities (most likely barrels) to take on the further tasks to ensure they dont stop when the player is too far from the initial trigger.

I can see this is unflavored so never mind.

**Comment by HierToo** [comment]
Use the zone as a trigger for a process which you assign to an entity(always active).

**Comment by AmenMoses** [comment]
" .. see if i can replicate how trigger zones generate their shape data .. " or simply use my zones script. ;-)

**Comment by thecyrus** [comment]
And what about a "spawning" Trigger zone?
I mean one that is not always "there" but it can be activated by another trigger zone?

**Comment by Teabone3** [comment]
HierToo that's what I meant by a barrel to accompany it. But I was hoping for a better way to optimize this where the zone could do all the work. For now I will look at the new new zone points commands from AmenMoses; that should helped me out a lot. Not sure how I missed that thread. Thanks for sharing.

**Comment by Teabone3** [comment]
If an admin would like to close or lock this request that would be great.

**Comment by Teabone3** [comment]
Just so people away this isn't about making a script always active as if the player doesnt need to be on the trigger zone or not. I'm saying that we need some way to make trigger zones retain their functionality after the player has left their boundary points. Why be forced into using an additional script.. on an additional entity? I don't understand why I have to do so many work-arounds for just about everything in this engine? Anyways on the to the next topic.
