### ISSUE TITLE
Custom Materials - Rogue Texture References

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#971]
Max adds rogue texture references to 'vegbank' in Custom Materials, which cannot be deleted.

- assigns rogue _i map from vegbank
- also adds blank reference to 'vegbank\' in the Occlusion slot
![incorrectly assigned maps](https://user-images.githubusercontent.com/12246318/111020707-f4254a00-841b-11eb-99a1-fb25e52ceff8.png)

System Specs:
None detected!

**Comment by michaeloldman** [comment]
Build 2021.02.04 - Exhibits same issue :)

**Comment by plemsoft** [comment]
@michaeloldman Custom material had a rewrite could you please check this in the latest version, Thanks for your help :)

**Comment by michaeloldman** [comment]
@plemsoft This issue seams to be resolved now - thanks :)
