### ISSUE TITLE
Rotation still needs some work

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#973]
https://vimeo.com/523252526

Video speaks for itself.

**Comment by AmenMoses** [comment]
The algorithm needed for this: (assuming only Y rotation of a group allowed)
1) Calculate the centre of the group of entities.
2) Create a dummy entity positioned at the centre position, store the quaternion of this entity ( i.e. initially 0,0,0)
3) For each entity in the group calculate the positional offset of the object from the dummy entity and a quaternion representing the difference between the orientations.
4) When rotating apply the rotational change to the dummy entity. Then for each entity in the group:
     a) calculate the new position using the positional offset rotated by the new orientation of the dummy entity.
     b) calculate the new orientation from the new orientation modified by the stored rotational difference.

Like this:  https://vimeo.com/523260710
(imagine that the floor slab is the dummy entity)

Code for this can be found in the pickuppables.lua script btw. 

This method would work just as well for X & Z rotations btw.

**Comment by AmenMoses** [comment]
One slight complication worth mentioning is that different items in the group could have different origin points, so the orientation 'difference' stored in step 3 needs to take that into account.

**Comment by LeeBamberTGC** [comment]
@AmenMoses The multiple object rotation uses the last object clicked as the 'active object' for rotating around. I will check the inter-object offsets to ensure they also work.

Thanks the pseudo code, was really helpful, and the use of quaternions was the right way to go :)

**Comment by LeeBamberTGC** [comment]
Rotations for single objects and objects as part of a selection now have fixed rotations. Switch most of the code to using quaternions for consistency, and did some clean-up. The rotation system now uses GLOBAL axis rather than the mysterious euler based axis rotation order which was hugely counterintuitive. The new method is much simpler and so when you want to rotate on a Y axis that is what you see, no matter the orientation of the object itself.

Please test when we release the change this Friday, thanks!

**Comment by AmenMoses** [comment]
Well that is certainly a big improvement, pity it is limited to only one axis of rotation.  😉

**Comment by LeeBamberTGC** [comment]
Eulers now updated after widget rotation finished with global rotation. Bouncing between quat and euler not ideal, but this one is good for now. A future enhancement could be a choice of both euler and global rotations as there are scenarios where you want to rotate one axis after a global rotation (such as rotating the label of a barrel to face you if that barrel is lob sided).

**Comment by AmenMoses** [comment]
https://vimeo.com/550069124

When creating a group that contains a sub group the sub group remains in the left hand window and can be selected but any operations on it actually act on the group it is part of.
This could be really confusing so maybe either the sub-group should be separately *remembered* or deleted when part of a larger grouping?

**Comment by rvanner** [comment]
@AmenMoses Is this now fixed for you in the latest version?
