### ISSUE TITLE
Insane ram waste - 11 gbs

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#974]
Running level in GGMax_2021_03_12.
Complete scene polycount: 300k
Animations: 3
Of course GGMax get frized, has to kill process via TM

Maybe because a lot of anims together?

YT Ling showing the issue.

https://youtu.be/NtFTfpsYdf4

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by rvanner** [comment]
@3coms Are you able to share your level with us in a zip file?

**Comment by 3coms** [comment]
@ Richard Vanner
Of course. There is not stock stuff here, just a custom one.

Download google drive link
<https://drive.google.com/file/d/1Nbk5Fafx8UN7S9k2X6ThNGLIlywbJBsW/view?usp=sharing>

If you need something else, or something going wrong with these files,
please, let me know it.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rvanner** [comment]
I copied the files over but don't see anything in the editor, just some blue light objects.
![image](https://user-images.githubusercontent.com/1503593/111221013-ddc0ef00-85d1-11eb-8919-18044590dadb.png)

**Comment by 3coms** [comment]
I guess you are needing the full file paths, I'm going to send you a pic to
clarify. So you most likely have to create the folders, since fpm might be
pointing to that path.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by 3coms** [comment]
Sorry I miss the floor file path, sending another pic

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rvanner** [comment]
I am not seeing any of these pictures.

**Comment by 3coms** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rvanner** [comment]
@3coms If you are sending links to images then they are not showing up properly in GitHub. It's best if you just paste the image into the text box here on Github.

**Comment by 3coms** [comment]
![full file paths_Mod10_GGMax_Level](https://user-images.githubusercontent.com/47690174/111507781-4ed7e200-874b-11eb-90f8-e2e5be0f5d94.png)

![full file paths_Mod10_GGMax_Level_Pic02](https://user-images.githubusercontent.com/47690174/111507829-57c8b380-874b-11eb-8165-37a4b37b7a7e.png)

**Comment by 3coms** [comment]
You will have to create these folders to recreate the paths the fpm file is waiting for, though.
If you do no get open the fpm file, then since you already have the meshes you can recreate the level yourself.

**Comment by 3coms** [comment]
Sorry, but no very familiar with Github

**Comment by rvanner** [comment]
Thanks @3coms, I was able to load the level and see the frame rate issue. 

@LeeBamberTGC A somewhat small level has trouble being rendered at a fast frame rate, here are the stats:

![image](https://user-images.githubusercontent.com/1503593/111620354-817eea80-87de-11eb-93ce-96631aa0b44d.png)

**Comment by rvanner** [comment]
The scene looks like this;

![image](https://user-images.githubusercontent.com/1503593/111620465-a8d5b780-87de-11eb-98e4-222b24920bbc.png)

**Comment by 3coms** [comment]
There is not the whole scene, yours is missing the central ring with animated escalators.

![GGMa_2021_03_17_2_INSTANCES_PI02](https://user-images.githubusercontent.com/47690174/111632880-36bc9d00-87f5-11eb-80ab-04ceb2b89352.png)
 as you can see on the pic, GGMax is loading the level and does not respond, so I'm unable to run the level, take a shot of my stats and post the image here, I'm going to try again later, if I'm a lucky man, then I will post a pic with my stats in-game.

**Comment by 3coms** [comment]
![mod10_GGMax_very_last_build_High_ram_pic01](https://user-images.githubusercontent.com/47690174/111633382-bb0f2000-87f5-11eb-946d-3366f8991ce6.png)

Sorry wrong pic and I do not how to remove it, posting the right one.

**Comment by 3coms** [comment]
That shot was made a few minutes ago, with the very last build.
10 minutes and still GGMax does not respond - circle mouse pointer rounding.

**Comment by 3coms** [comment]
20 minutes and circle mouse pointer yet

![mod10_GGMax_very_last_build_High_ram_pic02](https://user-images.githubusercontent.com/47690174/111636308-a4b69380-87f8-11eb-959a-2480ca726777.png)

If someone has no idea about the sort of meshes I'm testing here, they are high poly most of them I have modeled them as is with the sake of testing GGMax, stressing out the engine with high poly meshes (100k-300k) and high texture res (4k-8k), and please do not talk me about the meshes/textures should be as small as possible in a real game, I already know that, this is just for testing purpose, I would like to know till where I can go with GGMax.

I'm going to kill the process via TM
Continue traying later just for help purpose, but I know with the last build just can test barrels, boxes, and so on, nothing complex like my meshes.

**Comment by 3coms** [comment]
If someone needs some reference to what I'm talking about, this is the link to the thread

https://forum.game-guru.com/thread/222207

There I have been updating the thread every day, modeling/texturing those meshes to test GGMax, I really know what I talking about.

**Comment by 3coms** [comment]
OK, I've managed to open/run level with the very last build.

In editor

![mod10_GGMax_very_last_build_High_ram_pic05](https://user-images.githubusercontent.com/47690174/111645580-1eeb1600-8801-11eb-990a-b74df80154ef.png)

in-game

![mod10_GGMax_very_last_build_High_ram_pic04](https://user-images.githubusercontent.com/47690174/111645622-2f9b8c00-8801-11eb-92e5-4f77a65ee788.png)

Short video

https://youtu.be/wyfu7cFQ3U4

**Comment by 3coms** [comment]
Playing a bit with the shadows>bias slider (in test game mode), crash and close via TM
Notice the shadows over the central ring. Going to add some pic showing my stats, maybe might help someone.

![GGMaxBF_update_crashing_High_ram_shadows_pic01](https://user-images.githubusercontent.com/47690174/111798402-52de3e00-88ca-11eb-9134-1d5ff533bdda.png)

**Comment by 3coms** [comment]
Today update
![mod10_GGMax_very_last_build_High_ram_pic06](https://user-images.githubusercontent.com/47690174/111798905-cf711c80-88ca-11eb-8819-21aacc820250.png)

**Comment by 3coms** [comment]
I must add that with the 2021_03_26 GGMax version I'm getting 2-3gbs of ram waste, that's cool.

![GGMax_2021_03_26_MOD10_Low_ram_Editor_pic01](https://user-images.githubusercontent.com/47690174/112875145-17aaee80-90c4-11eb-9e5a-d79afeb71bf4.png)

![GGMax_2021_03_26_MOD10_Low_ram_TestGame_pic01](https://user-images.githubusercontent.com/47690174/112875190-285b6480-90c4-11eb-8f9a-4712517711c4.png)

Video Link showing something wrong at the very beginning of the video, in the stairs, the image are like jumping, any idea?

https://youtu.be/K0J_DCNBB_4

**Comment by 3coms** [comment]
Guys, adding some pic so if this may give some clue.
GGMax 2021-04-09 version - still high ram usage, this time with simple stock chess plus the player marker, so you easily can replicate it.

![GGMax_2021_04_09_High_ram_usage_pic01](https://user-images.githubusercontent.com/47690174/114278827-dc001500-9a31-11eb-83cb-72f0d5c6e316.png)

I must add that all the entities have the same script attached to, the script so far is not that complex, although it will be, that's the idea.

**Comment by 3coms** [comment]
Well, can say the script has nothing to do since I've commented almost all the script, and high ram usage remains, going to explain how it does.
Load map > test map1 > back to editor - ram usage = 2gbs
 test map2 > back to editor - ram usage = 4gbs
 test map3 > back to editor - ram usage = 8gbs
 test map4 > back to editor - ram usage = 11gbs, as you can see in the above pic.

It looks like gradually increasing ram usage, does not clean the buffer as expected?

**Comment by LeeBamberTGC** [comment]
Internal build soon - worth checking again to see if the memory leak has been fixed for Friday build.

**Comment by 3coms** [comment]
Checked. it looks like the mem leak remains on this last build, please refer to the pic below. Here, just some meshes, no that high in polycount.

![Uploading GGMax_High_ram_usage_pic01.png…]()

**Comment by 3coms** [comment]
![Uploading GGMax_High_ram_usage_pic01.png…]()

**Comment by 3coms** [comment]
Can get the image here, try again

![GGMax_High_ram_usage_pic01](https://user-images.githubusercontent.com/47690174/115071188-37307c80-9ef6-11eb-8e10-3ffc70996525.png)

**Comment by plemsoft** [comment]
@3coms There was some memory tweaks in the latest version , could you check and see it had improved, thanks for your help :)

**Comment by 3coms** [comment]
@ Preben
It is already done. :)

[image: GGMax_2021_05_07_High_ram_usage_pic01.png]
Here just testing the new jungle stuff plus buildings you already have to.

**Comment by plemsoft** [comment]
@3coms Thanks :)

**Comment by 3coms** [comment]
Here just painting texture a bit, notice the already painted area in the pic below
![GGMax_2021_05_07_High_ram_usage_pic03](https://user-images.githubusercontent.com/47690174/117316694-191cc300-ae89-11eb-9dc4-5dfec7d3361c.png)

Notice how the painting tool is unpainting the already painted area, and of course, notice the ram usage as well.

![GGMax_2021_05_07_High_ram_usage_pic04](https://user-images.githubusercontent.com/47690174/117316969-60a34f00-ae89-11eb-871e-229e57db1f9d.png)

Here using grass tool, the same, grass tool removing the already grassy area, and the ram usage, well, no comments. :)

![GGMax_2021_05_07_High_ram_usage_pic05](https://user-images.githubusercontent.com/47690174/117317225-9d6f4600-ae89-11eb-802e-14477de35c23.png)

**Comment by LeeBamberTGC** [comment]
You can ignore any memory increase due to sculpting and painting the terrain. We are entirely rewriting this piece of the engine for a much more efficient one.

**Comment by 3coms** [comment]
Understood. :)
Anyway, 6g of ram usage, with just 2 buildings plus some Jungle stuff, is a lot for me. (The first one pic above, sorry, my internet conn failing to load the pic, so you have a link.)

**Comment by 3coms** [comment]
Still having issues with RAM waste at the very last build 2021-07-23.
I've noticed when this happens and GGMax became too slow, and most of the time you have to get out via TM, it takes a while to window to relocate memory, meantime all is going super-slow in the pc while the relocate memory process takes place.

![GGMax_Insane_RAM_waste_City_map_pic01](https://user-images.githubusercontent.com/47690174/127768130-3cbd2b5c-98f4-43a4-89a1-d96b4994dce9.png)

A bit of _malloc_, please. :)

**Comment by rvanner** [comment]
Closing this for now. Please review memory use when we make the new terrain system available as an alpha verion.
