### ISSUE TITLE
[GGC] Lightmapping issue: Static object still casts shadow from sun

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#975]
Occasionally I will find a static object that casts a dynamic shadow. This chandelier model is one such example. It static by default, and here is the fpe:

`;Saved by GameGuru Object Importer v1.000
;header
desc             = lustre (long)

;visualinfo
textured         = lustre_color.dds
textureref1       = lustre_color.dds
textureref2       = lustre_normal.dds
textureref3       = lustre_gloss.dds
textureref4       = lustre_illumination.dds
effect           = effectbank\reloaded\apbr_illum.fx
castshadow       = 0
transparency     = 0

;orientation
model            = lustre (long).dbo
offx             = 0
offy             = 0
offz             = 0
rotx             = 0
roty             = 0
rotz             = 0
scale            = 100
collisionmode    = 11
defaultstatic    = 1
materialindex    = 2
matrixmode       = 0
cullmode         = 0

;physics shapes
physicscount     = 0

;identity details
ischaracter      = 0
hasweapon        = 
isobjective      = 0
cantakeweapon    = 0

;statistics
strength         = 25
explodable       = 0
debrisshape      = 0

;ai
aimain           = default.lua

;spawn
spawnmax         = 0
spawndelay       = 0
spawnqty         = 0

;anim
animmax          = 0
anim0            = 0,0
playanimineditor = 0
ignorecsirefs    = 1
`
castshadow is set to 0, meaning it should not cast a dynamic shadow, but it still does.

![chandelier](https://user-images.githubusercontent.com/60984223/111072079-ef6e9d80-84d0-11eb-80f8-151d89ad1dce.jpg)

The only way to get rid of this is to turn off shadows in the tab-tab menus, but I still think it's a bug that a static object does this.

**Comment by plemsoft** [comment]
@AvengingEagle Thanks for reporting this issue.

To stop shadow from all sources , lightmapper , dynamic ... you must use:
castshadow = -1

Or you will still get a shadow.

Let me know if this solves your issue, Thanks.
