### ISSUE TITLE
[GGC] Lightmapping issue: some objects refuse to lightmap

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#976]
Some objects refuse to lightmap. This fireplace is made of two entities; the fireplace proper and a square looking chimney which I've stacked on top of itself multiple times to achieve the desired height. The problem is the fireplace and the first section of chimney do not receive any lightmapping for some reason, but the rest of the chimney does.

It's worth mention both of these objects use LODs, but that can't be an issue surely as some of the chimney has lightmaps fine.

![fireplace](https://user-images.githubusercontent.com/60984223/111072196-60ae5080-84d1-11eb-89d0-24a9c664e30d.jpg)

**Comment by plemsoft** [comment]
@AvengingEagle Thanks for reporting this issue, just make sure your FPE set it as static and you turn off physics. "physics=0" and it will lightmap, if this is the object from Graphix he has fixed the fpe and it now lightmap talked with him on discord :)

If you still cant get it to lightmap , email me a copy of everything and i will have a look: plemsoft@plemsoft.com

Let me know if this fix your issue, Thanks.

**Comment by AvengingEagle** [comment]
Graphix's version has fixed this issue. The original model had stacked UVs (not ideal). Curiously, I started getting the same problem as above on Graphix's version, but then I set my lightmap size to 512 in setup.ini and that seems to have fixed the issue.
