### ISSUE TITLE
[GGC] Lightmapping issue: Cannot obscure the sun

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#977]
My level is set at night. In the past, I was able to block out the sun by enclosing the entire level in a giant dome from the Galaxy Seed DLC. This doesn't appear to work any more. I have tried placing large building on top of the map to obscure the sun, but still the light shines through. 

https://youtu.be/KjiIu1WO-eo

The only solution I've found so far is to place small 200x200 ceiling entities over the whole map only a few units above the ceiling height, which is laborious, wasteful, and then blocks my view of the level.

**Comment by plemsoft** [comment]
@AvengingEagle Thanks for reporting this issue. I tried the "dome" and it did block all dynamic light, so i assume this is a lightmapper issue , if so you can block all light from the sun if you change "Setup.ini" and use:

lightmappingdeactivatedirectionallight=1

This will make sure that all light from the sun is blocked.

Let me know if this fix your issue, Thanks :)
