### ISSUE TITLE
[GGC] Lightmapping issue: castshadows = -1 yet still casts shadows

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#978]
I have a decal of some hay that I don't want to be included during lightmapping because the resulting shadows look unnatural and jarring. So I have set castshadow = -1 to exclude this entity from lightmapping altogether. Yet when I lightmap the level, the hay decal is still included and still casts a shadow on the floor below.

![hayshadow](https://user-images.githubusercontent.com/60984223/111072479-b20b0f80-84d2-11eb-85ba-da0dbe2ed142.jpg)

Correct me if I'm wrong, but I thought castshadow worked like this:
- 1 = exclude entity from lightmapping altogether (treat as dynamic entity even if static)
0 = does not cast dynamic shadow
1 = does cast dynamic shadow

**Comment by f1WN356Uh51a1W6cn** [comment]
It's not the ambient occlusion in tab-tab menu? It looks very similar to me at least

**Comment by AvengingEagle** [comment]
Ah, you're quite right, it is the SSAO. It's not a bug then. But how does one turn off the SSAO for one entity specific entity?

**Comment by plemsoft** [comment]
@AvengingEagle Thanks for your question , you cant disable SSAO for a single object, its a post process shader so will only work on all object, your only option is to disable SSAO completely.

**Comment by AvengingEagle** [comment]
This would be a useful addition to the engine, to be able to eliminate certain assets from the SSAO shader.
