### ISSUE TITLE
Illumination maps

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#98]
Are we going to get self illumination back? I have a few models that don't work because they have illumination maps.

Can we please have proper emissive maps for the PBR thank you

**Comment by Granada1** [comment]
I agree with this one I thought it would be included in the pbr from the start,make a lot of difference to models.

**Comment by tarkus1971** [comment]
Yes I agree as well. Much needed.

**Comment by Dimoxinil** [comment]
I agree. It would be very useful.

**Comment by Pirate-Myke** [comment]
Looking at the hand scanner in the scifi pack that was just added, I see that the hand glow is label hand scanner_emmisive.dds. It has dxt1 compression, but does not glow at all in the editor or test game.
Change the shader to apbr_illum.fx in the fpe file and the whole object is white in the editor.

Changed the texture extension to _illumination and the whole object glows white still. The whole texture has alpha value of 255.

Are we changing the extension to illumination maps to _emmisive or was that an oversight?

**Comment by GraPhiX-Guru** [comment]
Yeah there was a 'fudging' you had to do with the detail map and change something in the shader file. I think Lee said he did not want to use anymore resources for the maps but I for one think it is needed and that we should not have to 'fudge'

**Comment by Pirate-Myke** [comment]
The deal was that you cant use a detail map and illumination map in the same object as they use the same texture slot in the shader.
