### ISSUE TITLE
Paint Terrain

### ISSUE THREAD

**Issue by niijel** [TheGameCreators/GameGuruRepo#980]
Created a new terain texture - named it and it showed in terrain matrix. When selected it used the last selected texture not the newly created one. 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z170XP-SLI
Processor: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 CPUs), ~3.5GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 2560 x 1440 (32 bit) (59Hz)

**Comment by rvanner** [comment]
@niijel The terrain system is going to be totally re-done later.
