### ISSUE TITLE
Grouping Problems

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#981]
If I group cubes that are snapped together, I find that the snapping is difficult with the grouped item. Every time I drag in a group to the screen it adds a new one. A selected group does not want to snap on the Y axis at all and Enter does not work. 

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MS-7A32
Processor: AMD Ryzen 7 1700 Eight-Core Processor           (16 CPUs), ~3.0GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 970
Dedicated Memory: 4043 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by rvanner** [comment]
@Retrogamebloke I have split this into two issues. In future, please only report one issue per report, it makes it easier to manage. Thanks.

**Comment by plemsoft** [comment]
@Retrogamebloke Thanks for reporting this issue , in the current version , while you drag the group holding the mouse down , you can press "enter" to enable Y snap , i know in this version that you cant see what object in the group that do the snapping, this will be marked in the next version. Also the next version will have a new mode for placing objects/groups that make it more easy to do Y snapping , look out for the "+" icon in the next update :)

**Comment by LeeBamberTGC** [comment]
we are looking to overhaul the grid and floor detection system - will reveal in future broadcast :)
