### ISSUE TITLE
[MAX] Something about PBR is broken

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#982]
PBR rendering seems to have downgraded to GGC levels of quality (or more accurately lack thereof)

Here's a lever-action rifle rendered before the last 2 updates:
![image](https://user-images.githubusercontent.com/56294129/111108573-89fdc980-852f-11eb-9046-c4768b7cd99e.png)

Now here's the same exact rifle, same file, same textures, etc. rendered in the latest update:
![image](https://user-images.githubusercontent.com/56294129/111108612-9a15a900-852f-11eb-8806-9e12273e40a8.png)

It looks far more flat, colors are off, and it appears to be made of pale plastic, losing the metallic shine and glossy wood.

I do not know what is specifically broken but it appears PBR and normal maps simply aren't being applied. This effect seems to also happen on the included cellar demo level, everything looks comparatively "flat" and has lost all depth and shine.

**Comment by Kitakazi** [comment]
I can confirm my Max is busted graphically as well. 
Everything is very bright and very flat. 
Possibly as to due with the HDR-Eye-Adjusting effect. Really wish I could turn it off. 
Fog is busted as well.

**Comment by nomad5oul** [comment]
HDR might be washing out the normals and other texture detail

**Comment by LeeBamberTGC** [comment]
With ambience set to black (dynamic sun settings) and accounting for auto-exposure the latest build should have improved your render. We are looking at a toggle to switch off the dynamic tone mapping.
