### ISSUE TITLE
Tiny installer Failed to download list Error 0 when running updates to get rest of program

### ISSUE THREAD

**Issue by Amdroid** [TheGameCreators/GameGuruRepo#983]
![Running Tiny Installer](https://user-images.githubusercontent.com/10211819/111149113-5ef19500-8584-11eb-99b5-f32c8c2ebbd1.png)
![Updater Failed to parse list](https://user-images.githubusercontent.com/10211819/111149117-5f8a2b80-8584-11eb-9a8d-6cdbd9caf5d1.png)
![Updater](https://user-images.githubusercontent.com/10211819/111149120-6022c200-8584-11eb-8241-0d19382bf694.png)

Hi any chance this can be looked into I have downloaded the latest version and I never been able to get the program running. I have tried uninstalling / re installing just fails with the message Failed to download list 

I have tried to install to my D drive incase this makes a difference but still the same. it seems to miss the authentication step so perhaps this is the problem in case the data has got corrupted ? Cheers and thanks in advance. If there are switch parameters i can add these to give more info e.g debug mode etc.  

HP OMEN 17-cb0002na 17.3 Inch FHD 144 Hz Gaming Laptop, 
Intel Core i9-9880H, 32 GB RAM, 512 GB SSD, 1 TB HDD, 
NVIDIA GeForce RTX 2080 (8 GB GDDR6 Dedicated) Graphics, Windows 10

**Comment by rvanner** [comment]
@LeeBamberTGC Can you please reply to the author of this bug and help him get up and running.

**Comment by LeeBamberTGC** [comment]
Try grabbing the very latest Tiny Installer again from the TGC Products page, and also go to this folder and delete the contents: "C:\Users\leeba\AppData\Local\AGKApps\TheGameCreators"

**Comment by rvanner** [comment]
@Amdroid See Lee's comment above, can you try the latest installer from the TGC website and report back please?

**Comment by Amdroid** [comment]
Will do gonna grab a brew then give it a whirl Cheers ill update soon

**Comment by Amdroid** [comment]
> Try grabbing the very latest Tiny Installer again from the TGC Products page, and also go to this folder and delete the contents: "C:\Users\leeba\AppData\Local\AGKApps\TheGameCreators"

All sorted deleted  the AppData did a clean install now downloading logged in va steam ill finish watching the latest vid and get on with some more testing when its all done.
