### ISSUE TITLE
superflatterrain doesn't work

### ISSUE THREAD

**Issue by Dimoxinil** [TheGameCreators/GameGuruRepo#99]
If you activate the option superflatterrain=1 in the file setup.ini. The terrain doesn't appear and you you can not move/rotate/etc.. objects in the editor.

**Comment by plemsoft** [comment]
Dimoxinil,
FYI: superflatterrain=1 , always set the terrain to height 1000 , so in your current level you should raise the terrain to 1000 ( to fit your objects) and not lower your objects , this way you can switch to superflatterrain=1 when its working again. So Lock all objects and raise the terrain  :)

**Comment by plemsoft** [comment]
This fix is not complete but terrain is now visible, There is a problem with mouse input when using superflatten , not sure how the mouse input works, so have assigned this to Lee , Thanks Lee :)

**Comment by LeeBamberTGC** [comment]
Fixed issue of viewport changing with terrain, and not changing with no terrain. Fixes mouse issue for next beta build 10/04/18.
