### ISSUE TITLE
Selecting a model sometimes the yellow band disappears, makes you think it is not selected, but it is - random

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#993]

**Comment by LeeBamberTGC** [comment]
Dragged in an object, selected it, saw the yellow outline. The object has been selected. Not reprod.

**Comment by rvanner** [comment]
@LeeBamberTGC I think this came from your list on TW. Shut it down if you want. If it happens again we can reopen a new issue.
