### ISSUE TITLE
When I tried changing the color of the ambience from palette, I accidentally moved the palette window during test game this promptly crashed max,

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#996]
Lee's notes;

If you move the tab window during test game, straight up crashes max. Only solution is to delete the settings files users/local/tgc. This reverts to the old settings again. Once the window has been moved in test game it records the position of the tab menu.

**Comment by plemsoft** [comment]
@rvanner This issue was fixed a few version ago, thanks.
