### ISSUE TITLE
Lighting differences between last public one and this one - for the worse

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#998]
WizardofId's lighting issues;

![image](https://user-images.githubusercontent.com/1503593/111214937-72bfea00-85ca-11eb-9e1b-6c46e9a5cb46.png)

**Comment by LeeBamberTGC** [comment]
Even with ambience set right down to zero, the auto-exposure system will lighten scenes that earlier builds would keep black. I suspect adding a toggle for auto exposure to switch it off and return control of exposure to the lighting choices of the level designer should restore the earlier looking scene at the cost of not having a dynamic tone mapper.

**Comment by rvanner** [comment]
@LeeBamberTGC So are you making a note to add this new toggle to TW?

**Comment by LeeBamberTGC** [comment]
TIs marked on TW
